### ISSUE TITLE
.user.ini gets overwriten when updating

### ISSUE THREAD

**Issue by tYYGH** [owncloud/core#23012]
### Steps to reproduce
1. update OC

### Expected behaviour
Modified settings in .user.ini should be preserved, ie settings that have the same name and with a value different than the default.

### Actual behaviour
The .user.ini file is simply replaced.

### Server configuration
**Operating system**: Debian Linux

**Web server:** Nginx

**Database:** PostgreSQL

**PHP version:** 5.6

**ownCloud version:** any (update to 8.2.2 for instance)

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** updater app

**Signing status (ownCloud 9.0 and above):** n/a

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here :
```
No output, redirected to Files.
```

**List of activated apps:** core +calendar and contacts

```
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.2
  - contacts: 0.5.0.0
  - files: 1.2.0
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_external
  - files_locking
  - files_pdfviewer
  - mail
  - notifications
  - provisioning_api
  - templateeditor
  - user_external
  - user_ldap
  - user_webdavauth
```

**The content of config/config.php:**

```
    "system": {
        "instanceid": "ocd1972bbede",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwritehost": "yalis.fr:443",
        "overwrite.cli.url": "\/oc",
        "trusted_domains": [
            "yalis.fr"
        ],
        "datadirectory": "\/var\/owncloud",
        "blacklisted_files": [
            "~$*",
            ".~lock.*",
            "*~",
            "*.~*",
            "Thumbs.db",
            "desktop.ini",
            ".Trash*",
            ".DS_Store",
            ".ds_store"
        ],
        "dbtype": "pgsql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": false,
        "installed": true,
        "theme": "",
        "maintenance": false,
        "mail_from_address": "OwnCloud",
        "mail_smtpmode": "php",
        "mail_domain": "yalis.fr",
        "loglevel": 2,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "trashbin_retention_obligation": "auto"
    }
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Arch Linux

#### Web server error log
n/a

#### ownCloud log (data/owncloud.log)
n/a

#### Browser log
n/a

**Comment by LukasReschke** [comment]
This is at the moment the expected behaviour. The values need to be modified on each update if they are not globally defined.

**Comment by RealRancor** [comment]
Thats the expected behavior since a longer time and keeping the file also won't work with the new integrity check in oC 9.

**Comment by tYYGH** [comment]
Indeed, I just upgraded to 9.0 and saw the mess I got in after modifying this file. Fine.
Then what is the right place to override the values from this file? My slow home server is unusable with the default values.
You can’t just shrug this off. There is at least something missing from the documentation, unless I missed this information while looking for it.

**Comment by RealRancor** [comment]
You can just make your edits after the update.

**Comment by tYYGH** [comment]
Thanks RealRancor. OC does indeed work even if checks fail. Well, I found where to disable the checks in the code anyway (just “$result = array();” in the right place…).
