### ISSUE TITLE
ownCloud Ubuntu 15.04 repo is deleted.

### ISSUE THREAD

**Issue by tapir** [owncloud/core#23037]
### Steps to reproduce
1.Go to http://download.owncloud.org/download/repositories/stable/Ubuntu_15.04/

### Expected behaviour
See packages

### Actual behaviour
404 Not Found

**Comment by jnweiger** [comment]
Supported platforms are
<pre>
CenOS 7                 (CentOS 6: Files only)
Deb 7, 8,
RHEL 7                  (RHEL 6: Files only)
SLES 12                 (openSUSE 13.2, Leap: Files only, but deps for testing and nightly)
Ubuntu 14.04, 15.10     (12.04 + 14.10: Files only)
</pre>

Sorry, no Ubuntu 15.04 according to the plan.

**Comment by tapir** [comment]
May I ask why 15.10 but not 15.04? Seems a little bit random. I would understand if you guys just wanted to support LTS but then why 15.10?

Thanks

**Comment by aspdye** [comment]
Last Release + LTS Versions :wink: 
Not verry random.

**Comment by jnweiger** [comment]
@aspdye yep, that is the logic.
