### ISSUE TITLE
.htaccess and Let's Encrypt automation in cPanel

### ISSUE THREAD

**Issue by GJSchaller** [owncloud/core#23038]
I'm using SiteGround as a host, and they just started offering Let's Encrypt as a feature. I was able to install an SSL cert on my main site, but when I attempted to install a cert on my ownCloud site, I got an error that I lacked sufficient permissions.

A quick support ticket later, and it turns out the .htaccess file was blocking the Let's Encrypt process:

https://community.letsencrypt.org/t/the ... 04/5309/27

I was able to comment out the .htaccess long enough to install the cert, but want to look at this long-term - in the event I modify the file, I am guessing it will be overwritten in the future (such as when I upgrade to 8.2.4 or 9.0).

Is there a long-term solution to keep ownCloud secure, while allowing Let's Encrypt to install its certificate?

Thank you!

### Steps to reproduce
1. Install ownCloud on cPanel based server with Let's Encrypt available.
2. Attempt to install a Let's Encrypt SSL cert using cPanel app.

### Expected behaviour
SSL cert should be installed w/o error or issue.

### Actual behaviour
Error message from cPanel Let's Encrypt app noting the client lacks permissions.

### Server configuration
PHP Built On	Linux (redacted).sgvps.net 3.12.18-clouder0 #1 SMP Wed Jan 20 00:00:07 EET 2016 x86_64
Database Version	5.5.31-30.3-log
PHP Version	5.6.18
Web Server	Apache/2.2.24 (Unix) mod_hive/5.0 mod_ssl/2.2.24 OpenSSL/1.0.0-fips mod_auth_passthrough/2.1 mod_bwlimited/1.4 mod_fastcgi/2.4.6 mod_fcgid/2.3.6
WebServer to PHP Interface	cgi-fcgi

ownCloud version: 8.2.2

Updated from an older ownCloud or fresh install: updated from 7.x series

Where did you install ownCloud from: ZIP package

```

<?php
$CONFIG = array (
  'instanceid' => 'ocf410f23f67',
  'passwordsalt' => 'REDACTED',
  'trusted_domains' => 
  array (
    0 => 'owncloud.knightrealms.com',
  ),
  'datadirectory' => '/home/owncloud/public_html/data',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'knightrealms.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'REDACTED.sgvps.net',
  'mail_smtpport' => '25',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'outgoing@knightrealms.com',
  'mail_smtppassword' => 'REDACTED',
  'maintenance' => false,
  'secret' => 'REDACTED',
  'loglevel' => 3,
  'dbname' => 'owncloud_db',
  'dbhost' => 'localhost',
  'dbuser' => 'owncloud_db',
  'dbpassword' => 'REDACTED',
  'theme' => '',
  'trashbin_retention_obligation' => 'auto',
);
```

Are you using external storage, if yes which one: local

Are you using encryption: no

Are you using an external user-backend, if yes which one: No

**Comment by MorrisJobke** [comment]
This should not be addressed in the .htaccess file of the application but in the global server configuration. Just route the acme URLs to a different folder.

See https://github.com/owncloud/core/pull/21629#issuecomment-171308903

**Comment by GJSchaller** [comment]
For users on hosted servers, this may not be an option.  My host (SiteGround) offers owncloud as a ready-to-install package, but does not offer me control over the server itself.

**Comment by MorrisJobke** [comment]
> For users on hosted servers, this may not be an option. My host (SiteGround) offers owncloud as a ready-to-install package, but does not offer me control over the server itself.

Then maybe ask the host to provide this additional rules, because they are also highly environment dependent.
