### ISSUE TITLE
More standard way to release apps

### ISSUE THREAD

**Issue by pierreozoux** [owncloud/core#23033]
I'm trying to automate a bit my path to ownCloud v9, but it is not really uniformed between your apps.
(I hope it is the right place to open this)

Look how the packages look like:

```
https://github.com/owncloud/contacts/releases/download/v1.0.0.0/contacts.tar.gz
https://github.com/owncloud/calendar/releases/download/v1.0/calendar.tar.gz
https://github.com/owncloud/documents/releases/download/v0.12.0/documents.zip
```

I didn't check the other, but I'm sure you understand what I'm saying.
It would be nice to have a convention, at least for official packages.

something like: https://github.com/owncloud/contacts/releases/download/vX.Y.Z/app_name.tar.gz

What do you think?

**Comment by PVince81** [comment]
App releases must be done on the marketplace, not Github, that's the standard way.
