### ISSUE TITLE
Packages for Debian 7 and Ubuntu 14.10 missing?

### ISSUE THREAD

**Issue by Berdir** [owncloud/core#23047]
http://download.owncloud.org/download/repositories/stable/Debian_7.0/
http://download.owncloud.org/download/repositories/stable/Debian_8.0/

Debian 7 only has the owncloud-files package? Same for Ubuntu 14.10 vs. 15.10

**Comment by RealRancor** [comment]
14.10 seems to be not supported in general according to: https://github.com/owncloud/core/issues/23037

**Comment by RealRancor** [comment]
Ok, those differences are expected:

Ubuntu 14.04, 15.10     (12.04 + 14.10: Files only)
Deb 8        (Deb 7: Files only)

from https://github.com/owncloud/core/issues/23037#issuecomment-194368404

Files only probably just means "owncloud-files" only. Would be good if this is documented somewhere.

**Comment by RealRancor** [comment]
Ok, thats now described here: https://owncloud.org/blog/time-to-upgrade-to-owncloud-9-0/

I think its time to close here. :-)

**Comment by Berdir** [comment]
Thank you. Indeed, updating an existing installation by switching to owncloud-files worked fine for me. Maybe the blog post could be a bit clearer that you actually can do that?
