### ISSUE TITLE
owncloud update fail

### ISSUE THREAD

**Issue by theonlydoo** [owncloud/core#23042]
### Steps to reproduce
1.  ` sudo -u www-data php occ  upgrade`
2. `starting upgrade from 8.2.2.2 to 9.0.0.19`
3. `2016/03/09 17:02:04 [error] 23522#0: *40623 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare class OC_L10N in /var/www/owncloud/owncloud/lib/private/l10n.php on line 42`

### Expected behaviour
Update works

### Actual behaviour
`2016/03/09 17:02:04 [error] 23522#0: *40623 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot redeclare class OC_L10N in /var/www/owncloud/owncloud/lib/private/l10n.php on line 42`

### Server configuration
**Operating system**: Deb 7

**Web server:** Nginx 

**Database:** MariaDB

**PHP version:** 5.6 dotdeb

**ownCloud version:** 8.2.2.2 

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** https://download.owncloud.org/community/owncloud-9.0.0.tar.bz2

After upgrade, nothing works anymore and I can't even restore the original version :D

**Comment by LukasReschke** [comment]
Please make sure to upgrade properly. Delete all existing files except config and data before and then upload the new files. You are having old files that are now duplicates.

Replacing is not the right way to update ownCloud since the old files will stay :wink:

**Comment by theonlydoo** [comment]
```Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE `oc_notifications` (`notification_id` INT AUTO_INCREMENT NOT NULL, `app` VARCHAR(32) NOT NULL, `user` VARCHAR(64) NOT NULL, `timestamp` INT DEFAULT 0 NOT NULL, `object_type` VARCHAR(64) NOT NULL, `object_id` VARCHAR(64) NOT NULL, `subject` VARCHAR(64) NOT NULL, `subject_parameters` LONGTEXT DEFAULT NULL, `message` VARCHAR(64) DEFAULT NULL, `message_parameters` LONGTEXT DEFAULT NULL, `link` VARCHAR(4000) DEFAULT NULL, `actions` LONGTEXT DEFAULT NULL, INDEX oc_notifications_app (`app`), INDEX oc_notifications_user (`user`), INDEX oc_notifications_timestamp (`timestamp`), INDEX oc_notifications_object (`object_type`, `object_id`), PRIMARY KEY(`notification_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_notifications' already exists
Update failed
Maintenance mode is kept active
Reset log level
```
Next step : mysql drop this table

**Comment by theonlydoo** [comment]
```
Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_addressbooks' already exists
Update failed
```

**Comment by theonlydoo** [comment]
```Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE `oc_cards` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `addressbookid` INT DEFAULT 0 NOT NULL, `carddata` LONGBLOB DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `lastmodified` BIGINT UNSIGNED DEFAULT NULL, `etag` VARCHAR(32) DEFAULT NULL, `size` BIGINT UNSIGNED NOT NULL, PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_cards' already exists
Update failed
```
@LukasReschke I keep posting the table that I have to drop in order to update if you don't mind.

**Comment by LukasReschke** [comment]
@theonlydoo Sure. But I wonder why you have to drop these tables… That should not actually be necessary :confused:

**Comment by theonlydoo** [comment]
I only follow what Doctrine tells me here, it's sadly purely empiric

**Comment by theonlydoo** [comment]
I'm a long time user of ownCloud (since 3.x iirc) and it's from far the most painful upgrade that I've ever done :D

**Comment by theonlydoo** [comment]
OMG : https://github.com/owncloud/core/issues/23042#issuecomment-194387394 again

```
Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_addressbooks' already exists
Update failed
```

**Comment by theonlydoo** [comment]
Ok I think i'll just give up for now and try to restore my previous version ... @LukasReschke if you need any info regarding this bug i'll be glad to try again.

**Comment by Ark74** [comment]
So, no owncloud 9 for now. :-(

**Comment by theonlydoo** [comment]
Oh yes it works now :)
you have to mv all the directories and files except `data` and `config` and try again the upgrade.

don't forget to backup files and database right before that

**Comment by Ark74** [comment]
I did try today, that's the reason I'm here. I got the addressbooks error then the cards error, then I quit. Exporting and dropping tables.

Maybe I had to manually edit a file or wait to a new release.
You say it works, how did you do it?

I'm on a shared host with shell access.

**Comment by Ark74** [comment]
I've tried using the 9.0 release files, removed the config file and uploaded the files to the server, i get this output,

```
Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_addressbooks' already exists
Update failed
```
Is this issue related to share host servers?

**Comment by Ark74** [comment]
After exporting and dropping several tables i was able to complete the upgrade process, here the list of tables that i the upgrade process complained,

- oc_addressbookchanges
- oc_addressbooks
- oc_calendarchanges
- oc_calendarobjects
- oc_calendars
- oc_calendarsubscriptions
- oc_cards
- oc_cards_properties
- oc_dav_shares
- oc_schedulingobjects

After that i was able to finish the upgrade process, but i seems that the server is not well set.
I'm rolling back to 8.2

**Comment by theonlydoo** [comment]
not a good idea to use shared hosting even with ssh :)
like i said : from a *clean* setup, backed up, i ran a `rm -rf` of everything except `data` and `config` and then `rsync`ed the new files.

From here I ran the upgrade command : https://doc.owncloud.org/server/7.0/admin_manual/configuration/occ_command.html#upgrade-command 

and thats it.

**Comment by Ark74** [comment]
It's really funny, i did it again :)

My experience:
8.2.2 -> 9.0.0 = fail
8.2.3 -> 9.0.0 = success!

Same server same data base,  same steps, same downloaded files used both times.

Thanks for the support :)

**Comment by samuelstein** [comment]
I got the same problem with upgrading from owncloud 8.2.3 to nextcloud 9.0.51. 
Solution was deleting tables like @Ark74 mentioned plus table _oc_trusted_servers_
