### ISSUE TITLE
contact_birthdays calendar is writable even though it should be read-only

### ISSUE THREAD

**Issue by georgehrke** [owncloud/core#23046]
The contact_birthdays calendar is writable, it's supposed to be read-only as clarified in https://github.com/owncloud/calendar/issues/295#issuecomment-194391415

cc @DeepDiver1975

**Comment by georgehrke** [comment]
@DeepDiver1975 If you are already touching the corresponding code, would you mind adding a proper display name and calendar color?
(https://github.com/owncloud/calendar/issues/289)

**Comment by jancborchardt** [comment]
Tagged as sev2-high because it severly impacts the Calendar UX.

**Comment by enoch85** [comment]
Maybe this is related to the failing DAVDroid sync? What do you think @jancborchardt @georgehrke? It tries to sync birthdays - but this happens:

```
<?xml version="1.0" encoding="utf-8"?>[LF]
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">[LF]
  <s:sabredav-version>3.0.7</s:sabredav-version>[LF]
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>[LF]
  <s:message>Node with name 'contact_birthdays' could not be found</s:message>[LF]
</d:error>[LF]
```

**Comment by Akhenaton** [comment]
@enoch85 
Here, my DAVdroid sync well with both Calendar and Contacts, except for the birthdays feature (missing birthdays). It's only a little slower than the old apps.
It sync well also with the KDE Kontact PIM and Thunderbird Lightning & addressbook.

**Comment by enoch85** [comment]
@Akhenaton Yes, contacts and calendar (I think, as birthdays is a part of calendar) work fine, but birthdays fails.

**Comment by DeepDiver1975** [comment]
> I wonder if 'contact_birthdays' has not moved to 'contact-birthdays' ?..

no - see https://github.com/owncloud/core/blob/master/apps/dav/lib/caldav/birthdayservice.php#L31

**Comment by DeepDiver1975** [comment]
In case you are missing the bithday calendar - please run the occ command:

```shell
$ ./occ dav:sync-birthday-calendar

**Comment by enoch85** [comment]
Thanks @DeepDiver1975! Is there any way to sync <all> or do I have to specify each user?

**Comment by DeepDiver1975** [comment]
> Is there any way to sync all or do I have to specify each user?

calling the command without any argument will sync all users

**Comment by enoch85** [comment]
`sudo -u www-data php occ dav:sync-birthday-calendar` says that I need to specify user. Am I doing it wrong? If I specify user it works.

**Comment by nickvergessen** [comment]
@enoch85 https://github.com/owncloud/core/pull/23035

**Comment by DeepDiver1975** [comment]
> Am I doing it wrong? If I specify user it works.

Oh - there was a bug fix by @nickvergessen

**Comment by DeepDiver1975** [comment]
see :wink:

**Comment by enoch85** [comment]
That explains it. Thanks  @DeepDiver1975 @nickvergessen :)
