### ISSUE TITLE
After idle logout prefill user name in login form

### ISSUE THREAD

**Issue by lukas-buergi** [owncloud/core#23053]
When owncloud stays open for a long time in a browser window, the user is logged out.
When you reload the page or click a link to get to the login page, no matter whether you are an attacker or the owner of the account, you already know the account name: it's displayed in the top right corner. It's pretty unlikely the user wants to switch to another account in this scenario.

So I suggest prefilling the user name field on the login form in that case. Saves the user a little typing work.

Precedent: Google does something similar to this, guessing the user and just asking for the password again, sometimes.

Alternative: Don't even go to the login page, just open some message box and ask the user to supply the password again.

**Comment by LukasReschke** [comment]
cc @owncloud/designers

**Comment by jancborchardt** [comment]
Yeah, good call. As you say Google does it similarly. Prefilling the username is the easiest here.

@LukasReschke can you take care of it?

**Comment by jancborchardt** [comment]
(Also, the password field should then be focused of course.)

**Comment by LukasReschke** [comment]
> @LukasReschke can you take care of it?

I can take a look if we touch the whole authentication code in 9.1. ;)
