### ISSUE TITLE
Birthdays of contacts in a shared addressbook are not shown in the birthday calendar

### ISSUE THREAD

**Issue by AsamK** [owncloud/core#23051]
### Steps to reproduce
1. Let someone share an addressbook (with birthdays) with you
2. Upgrade to 9.0
3. Run "occ dav:sync-birthday-calendar USER"
4. Look at the birthday calendar

### Expected behaviour
The birthdays of all contacts (your own and the shared ones) should show up

### Actual behaviour
Only birthdays of contacts in my own addressbook show up

### Server configuration
**Operating system**:
Debian 8.0 x86_64

**Web server:**
Nginx

**Database:**
Mysql

**PHP version:**
7.0.3

**ownCloud version:** (see ownCloud admin page)
9.0

**Updated from an older ownCloud or fresh install:**
Updated from 8.2.2

**Where did you install ownCloud from:**
Manual tar.gz

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**Comment by LukasReschke** [comment]
cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
case closed - #23510 was merged - will be shipped with 9.1.0
