### ISSUE TITLE
Memcache exception error when upgrading from 8.2.2 to 9.0

### ISSUE THREAD

**Issue by Andreacroci** [owncloud/core#23058]
### Steps to reproduce
1. Try upgrading from OC 8.2.2 to 9.0 following these steps: https://doc.owncloud.org/server/9.0/admin_manual/maintenance/package_upgrade.html
2. Get to step "Run occ upgrade"

### Expected behaviour
Owncloud should upgrade to version 9.0

### Actual behaviour
I got these messages:

Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Starting code integrity check...
Exception: Error 3 interacting with memcached : CONNECTION FAILURE
Update failed
Maintenance mode is kept active
Reset log level

Memcached was working fine in OC version 8.2.2.

### Server configuration
Linux Ubuntu 14.04.3 LTS

**Web server:**
Apache 2.4

**Database:**
Mysql 5.7

**PHP version:**
5.6.19

**ownCloud version:** (see ownCloud admin page)
See error description

**Updated from an older ownCloud or fresh install:**
See above

**Where did you install ownCloud from:**
Repository

**Signing status (ownCloud 9.0 and above):**
Don't know

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

<!DOCTYPE html>

<html class="ng-csp" data-placeholder-focus="false" lang="en" >
	<head data-requesttoken="">
		<meta charset="utf-8">
		<title>
		ownCloud		</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="referrer" content="never">
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
		<meta name="apple-itunes-app" content="app-id=543672169">
		<meta name="theme-color" content="#1d2d44">
		<link rel="shortcut icon" href="Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

**List of activated apps:**

ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - calendar
  - contacts
  - encryption
  - external
  - files_locking
  - user_external
  - user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "oc1a4407e3c8",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwritewebroot": "\/owncloud",
        "overwrite.cli.url": "\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": true,
        "forcessl": true,
        "loglevel": "2",
        "check_for_working_webdav": true,
        "trusted_domains": [
            "andreacroci.ddns.net"
        ],
        "mail_from_address": "andrea.croci",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "mail.gmx.net",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_domain": "gmx.de",
        "mail_smtptimeout": 30,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Google Chrome

**Operating system:**
Same as above

#### Web server error log
```
nothing in there

#### ownCloud log (data/owncloud.log)
```
{"reqId":"lsrNId0sc+PCVwQyID9R","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.2.2 to 9.0.0.19","level":0,"time":"2016-03-09T20:11:36+00:00","method":"--","url":"--"}
{"reqId":"lsrNId0sc+PCVwQyID9R","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Error 3 interacting with memcached : CONNECTION FAILURE\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/memcache\\\/memcached.php(91): OC\\\\Memcache\\\\Memcached->verifyReturnCode()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/integritycheck\\\/checker.php(389): OC\\\\Memcache\\\\Memcached->remove('oc.integrityche...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/integritycheck\\\/checker.php(502): OC\\\\IntegrityCheck\\\\Checker->cleanResults()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(349): OC\\\\IntegrityCheck\\\\Checker->runInstanceVerification()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/updater.php(215): OC\\\\Updater->doUpgrade('9.0.0.19', '8.2.2.2')\\n#5 \\\/var\\\/www\\\/owncloud\\\/core\\\/command\\\/upgrade.php(225): OC\\\\Updater->upgrade()\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(840): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/console\\\/application.php(145): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#11 \\\/var\\\/www\\\/owncloud\\\/console.php(88): OC\\\\Console\\\\Application->run()\\n#12 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/memcache\\\/memcached.php\",\"Line\":174}","level":3,"time":"2016-03-09T20:12:04+00:00","method":"--","url":"--"}

#### Browser log
```
Sorry, but I don't know where to find my browser log

**Comment by LukasReschke** [comment]
Error 3 seems to be `MEMCACHED_CONNECTION_FAILURE`, are you sure that your memcached server is accessible from CLI?

**Comment by Andreacroci** [comment]
Hi Lukas,

thank you for your reply. You are right, I'm not at all sure the 
memcached server is accessible: indeed it was not running at all. Sorry 
for being such a newbie and not checking that before.

I re-did it and it went smoothly this time. I guess you may just go 
ahead and mark the issue as closed, unless you want me to do it.

My apologies again for wasting your time and please keep up the 
excellent work.
