### ISSUE TITLE
OC9 and IE 11 - cannot create new folders in WebUI - MKCOL exception recorded

### ISSUE THREAD

**Issue by ketolajuha** [owncloud/core#23067]
Fresh Install of OC9, when logging in with Internet Explorer v11 - cannot create new folders through WebUI. I can create folders with EDGE, Firefox, Chrome browsers without problems.

_(See - reference to issue #22274 where EDGE browser was fixed)_

Setup in short (sorry short setup, but I believe the trail leads to same issue as referenced issue):
• Browser installed in OS win10 with latest patches. (My IE version 11.103.10586.0)
• Clean install of Owncloud 9.

### Steps to reproduce
1. Fresh install of OC9
2. Win10 and IE11 - log in to OC and try to create a new folder.

### Expected behaviour
New folder should be created.

### Actual behaviour
Error - Could not create folder "new folder"  (see log)

### Server configuration
**Operating system**: Linux

**Web server:** Apache 2.2.31

**Database:** MariaDB 5.5.47-0064

**PHP version:**PHP 5.6.11 (cli)

**ownCloud version:** 9.0.0

#### ownCloud log (data/owncloud.log)

**Error Recorded to log:**

Exception: {"Message":"HTTP\/1.1 415 The request body for the MKCOL request must have an xml Content-Type","Exception":"Sabre\DAV\Exception\UnsupportedMediaType","Code":0,"Trace":"#0 [internal function]: Sabre\DAV\CorePlugin->httpMkcol(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#1 \/volume1\/web\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\Event\EventEmitter->emit('method:MKCOL', Array)\n#3 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#4 \/volume1\/web\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\DAV\Server->exec()\n#5 \/volume1\/web\/owncloud\/remote.php(138): require_once('\/volume1\/web\/ow...')\n#6 {main}","File":"\/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","Line":563,"User":"xxxxxx"}

**Comment by LukasReschke** [comment]
cc @owncloud/javascript

**Comment by MorrisJobke** [comment]
@LukasReschke This is not a sev1 (data loss)

**Comment by rullzer** [comment]
Mmmm you got to love MS... lets see if I can find a VM with IE11

**Comment by ketolajuha** [comment]
@rullzer Haha...me not loving it - just stumbled to this issue. But as the IE thingy is part of the newest Win10, I kinda figured this would be worthwhile to look into.

**Comment by rullzer** [comment]
Could not find IE11 on win10... but will check IE11 on win8.1 (https://dev.windows.com/en-us/microsoft-edge/tools/vms/linux/)

**Comment by ketolajuha** [comment]
@rullzer - It doesn't show up under "All Apps," but you can just use the Search box for finding it.

**Comment by rullzer** [comment]
@ketolajuha well you were right... IE11 is also on the win10 VM...
lets try to debug this...

**Comment by rullzer** [comment]
PR with fix in https://github.com/owncloud/core/pull/23084

**Comment by ketolajuha** [comment]
I can confirm the proposed fix - after adding same to IE dav client, folders **can be again created in stable OC 9.0.0.
**
Thanks!!!!!!
