### ISSUE TITLE
upload_max_filesize not being read - php7

### ISSUE THREAD

**Issue by kingfame** [owncloud/core#23061]
### Steps to reproduce
1. Change "maximum upload size" on the admin page.
2. Exit the admin page
3. Reload the admin page --> The change is not shown

### Expected behaviour
The change of the maximum upload size should be visible.

### Actual behaviour
The default value of "2mb" is shown. The problem is that the .htaccess file is written with `<IfModule mod_php5.c>`, which will not be read by php7?

### Server configuration
**Operating system**:
gentoo
**Web server:**
2.4.18-r1
**Database:**
mysql-5.6.28
**PHP version:**
7.0.4
**ownCloud version:** (see ownCloud admin page)
9.0.0
**Updated from an older ownCloud or fresh install:**
Fresh install, migrated the config/data from 8.2.2
**Where did you install ownCloud from:**
https://download.owncloud.org/community/owncloud-9.0.0.tar.bz2
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - music: 0.3.10
  - notes: 2.0.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - activity
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc2poiv2a0jf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.felix-blanke.de"
        ],
        "datadirectory": "\/data\/owncloud",
        "overwrite.cli.url": "http:\/\/10.0.0.1\/cloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "dbname": "owncloud",
        "dbhost": "c_mysql",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "asset-pipeline.enabled": false,
        "appstore.experimental.enabled": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "apache",
        "mail_domain": "felix-blanke.de",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.test.de",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
chrome
**Operating system:**
windows 7
#### Web server error log
```
Not needed.
```

#### ownCloud log (data/owncloud.log)
```
Not needed.
```

#### Browser log
```
Not needed.
```

**Comment by kingfame** [comment]
Sorry, seems to be a duplicate of this issue: https://github.com/owncloud/core/issues/21146

**Comment by LukasReschke** [comment]
Yep :)
