### ISSUE TITLE
Show correct versions for apps in oC internal appstore

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#23089]
### Steps to reproduce
1. Install ownCloud 9.0.0
2. Check category "Productivity" in oC internal Appstore for Calendar and Contacts
3. Calendar is showing up as Version 0.6.7, Contacts as 1.0.0.0
4. Enable Calendar and Contacts
5. Check category "Enabled" in oC internal Appstore for Calendar and Contacts
6. Calendar is showing up as Version 1.0, Contacts as 1.0.0.0

### Expected behaviour
Correct versions are shown in the "Productivity" category

### Actual behaviour
Wrong versions are shown in the "Productivity" category

Ref: https://github.com/owncloud/calendar/issues/308

**Comment by aspdye** [comment]
Isn't this https://github.com/owncloud/appstore-issues or is it a core-bug?

**Comment by georgehrke** [comment]
@aspdye No, this is the right place :)

**Comment by RealRancor** [comment]
I'm not really sure:

https://api.owncloud.com/v1/content/data?version=9x0x0x0&categories=922&approved=all
-> Showing calendar 0.6.7 and contacts 1.0.0.0

https://api.owncloud.com/v1/content/data?version=8x2x0x0&categories=922&approved=all
-> Showing calendar as 0.8.2 and contacts 0.5.0.0

**Comment by RealRancor** [comment]
@georgehrke Maybe you need to raise the version of the calendar app to 1.0 so the appstore is reporting the correct version?

**Comment by georgehrke** [comment]
Interesting :confused: 

Yes, so I'll just swap Content link 1 with Content link 4.

The issue seems to be in the API of the owncloud app store.
Then https://github.com/owncloud/appstore-issues would indeed be the correct repo :laughing:

**Comment by aspdye** [comment]
I did it :muscle: I was correct - first time :sweat_smile:

**Comment by RealRancor** [comment]
Works, https://api.owncloud.com/v1/content/data?version=9x0x0x0&categories=922&approved=all is now showing 1.0 :+1:
