### ISSUE TITLE
Sharing search while typing all lowercase for mixed case group

### ISSUE THREAD

**Issue by gvde** [owncloud/core#23085]
### Steps to reproduce
1. Click on the share symbol to share a file, contact, etc. to open the share text field
2. Enter an existing group name ("Abi90") all lowercase ("abi90")
3. see what is found while typing

### Expected behaviour
It should always only show the group "Abi90"

### Actual behaviour
It offers group "abi90 (Group)" when you enter "abi90". If offers "Abi90 (Group)" twice when you enter "Abi90". Enter anything shorter shows correctly "Abi90 (Group)" once.

Worse, at least for the contacts app choosing "abi90 (Group)" for sharing will not share, i.e. I guess the group name is case sensitive thus sharing with "abi90" won't work because the group is "Abi90".

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS

**Web server:**
Apache/2.4.7 (Ubuntu)

**Database:**
mysql  Ver 14.14 Distrib 5.5.47

**PHP version:**
PHP 5.5.9-1ubuntu4.14

**ownCloud version:** (see ownCloud admin page)
9.0.0.19

**Updated from an older ownCloud or fresh install:**
Updated from 8.2.2

**Where did you install ownCloud from:**
Packages

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ockoxl25xpg2",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.example.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/www.example.com\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "php",
        "mail_from_address": "g",
        "mail_domain": "example.com",
        "loglevel": 1,
        "theme": "",
        "maintenance": false,
        "appstore.experimental.enabled": false,
        "default_language": "de",
        "defaultapp": "contacts",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

No.

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration
**Browser:**
Firefox 45.0, Safari 9.0.3

**Operating system:**
OS X 10.11.3

#### Web server error log
```
While typing none but the access logs to 
GET /owncloud/ocs/v1.php/apps/files_sharing/api/v1/sharees?format=json&search=ab&perPage=200&itemType=file HTTP/1.1
```

#### ownCloud log (data/owncloud.log)
```
Nothing while typing.
```

#### Browser log
```
Nothing.
```

**Comment by LukasReschke** [comment]
cc @owncloud/sharing

**Comment by nickvergessen** [comment]
@gvde can you test https://github.com/owncloud/core/pull/23091 please

**Comment by gvde** [comment]
#23091 seems to fix the lower case issue. While typing "abi90" it finds "Abi90 (Group)", even when finished typing.

However, the duplicate for "Abi90" still remains. While typing "Abi90" everything is good (i.e. "Abi90 (Group)" is shown exactly once) until I enter the final "0". Then all of a sudden, "Abi90 (Group)" appears twice.

**Comment by nickvergessen** [comment]
@gvde thanks, fixed in a second commit

**Comment by gvde** [comment]
Working for me.
