### ISSUE TITLE
ownCloud 9: storage quota is "unlimited"

### ISSUE THREAD

**Issue by BenS89** [owncloud/core#23088]
### Steps to reproduce
1. Upgrade from ownCloud 8.2.2 to 9.0
2. Login as a user which has no storage quota limitation
3. Navigate to your personal page in the webinterface

### Expected behaviour
The quota limit is not declared as "unlimited". Instead, the maximum available storage capacity of the server is shown. Example: "You are using 12 GB of the available 250 GB"
250 GB would be the maximum available HDD capacity of the server.

### Actual behaviour
You read: "You are using 12 GB of the available unlimited"

### Server configuration
**Operating system**: Embedded QNAP Linux

**Web server:** Apache 2.4.12

**Database:** MariaDB 5.5

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page) 9.0

**Updated from an older ownCloud or fresh install:** Upgraded from 8.2.2

**Signing status (ownCloud 9.0 and above):** "No errors have been found."

**List of activated apps:**
Calendar 1.0
Contacts 1.0

**Comment by aspdye** [comment]
I am not sure, but isn't this the normal behavior of ownCloud? I think only admins see the maximum HDD storage if they have a "unlimited" quota. Let me reproduce this ...

**Comment by aspdye** [comment]
Okay... I have reproduced:

Also "admins" see UNLIMITED if they have an UNLIMITED quota. If you set the quota to 10 TB e.g., you will se not 10 TB - you will see the real free HDD space (of course, only if it is under 10 TB) :wink:

**Comment by LukasReschke** [comment]
@PVince81 That was done in https://github.com/owncloud/core/pull/22613 to fix https://github.com/owncloud/core/issues/19988

Expected behaviour or not?

cc'ing @jancborchardt as well

**Comment by nickvergessen** [comment]
This was changed 2-3 weeks ago, to fix an issue with the client:
https://github.com/owncloud/core/issues/19988
