### ISSUE TITLE
RewriteRule .* index.php [PT,E=PATH_INFO:$1] in .htaccess causes 404 if owncloud is in a subdirectory

### ISSUE THREAD

**Issue by wagnerand** [owncloud/core#23098]
### Steps to reproduce
1. Install owncloud 9.0.0 to a subdirectory, e.g. http://mydomain.com/owncloud
2. Try to access http://mydomain.com/owncloud

### Expected behaviour
Redirect to http://mydomain.com/owncloud/ -> Redirect to http://mydomain.com/owncloud/index.php

### Actual behaviour
Redirect to http://mydomain.com/owncloud/ -> 404

Changing `RewriteRule .* index.php [PT,E=PATH_INFO:$1]` to `RewriteRule . index.php [PT,E=PATH_INFO:$1]` fixed the issue. Even the official docs at https://httpd.apache.org/docs/current/mod/mod_rewrite.html#rewriterule say "...using a regex of . is often sufficient rather than .*...".

**Comment by LukasReschke** [comment]
Another workaround at https://github.com/owncloud/core/pull/23065. The suggested alternative approach is interesting and I'll also take a look later on that.
