### ISSUE TITLE
Information about that a Folder is shared does disappear after reloading the page

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#23092]
### Steps to reproduce
1. Share a Folder with a Group
2. See the "shared"-icon on the folder and the information that the folder is shared
3. Reload the page
4. Folder has no "shared"-icon and seems to be not shared
5. Click on the Folder to view Sharing Status
6. It will again tell you that it is shared when you go to "sharing"-section

### Expected behavior
Should be shown as shared everytime. Not only after loading the shares manual.

### Actual behavior
It does not :stuck_out_tongue_winking_eye:

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS
**Web server:**
Apache + Nginx Reserve Proxy
**Database:**
SQLite
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
9.0.0 (stable)
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
official source
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Safari
**Operating system:**
OS X El Capitan
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
is_readable(): open_basedir restriction in effect. File(/dev/urandom) is not within the allowed path(s): (/var/www/vhosts/oc.lineone.org/:/tmp/) at /var/www/vhosts/oc.lineone.org/httpdocs/owncloud/3rdparty/paragonie/random_compat/lib/random.php#66	
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
@aspdye are you observing this bug in the "All files" section or only in the other sections ?
The "All files" section should work fine.

The other ones have trouble, see https://github.com/owncloud/core/issues/22708

**Comment by aspdye** [comment]
It does *only* happen in the "All files" section. This is why i am a bit confused :confused:

**Comment by PVince81** [comment]
Hmm weird... ok shared with group, in case that matters.

@rullzer can you reproduce this ?

**Comment by rullzer** [comment]
Can't reproduce this...

@aspdye can you post the network console when you reload the page... and the specifically calls to the OCS Share API?

**Comment by PVince81** [comment]
Closing due to lack of feedback
