### ISSUE TITLE
OC 9.0 upgrade or new install impossible

### ISSUE THREAD

**Issue by D4rkPh0en1x** [owncloud/core#23097]
### Steps to reproduce
1. Upgrade from 8.2 to 9.0 or donfresh install
2. login
3. integrity check failed

### Expected behaviour
No error

### Actual behaviour
In the web I can't see my files and data

### Server configuration
**Operating system**:
Red Hat 7.0

**Web server:**
Apache 2.4.6

**Database:**
Mysql 5.6.29

**PHP version:**
5.6.19

**ownCloud version:** (see ownCloud admin page)
9.0.0

**Updated from an older ownCloud or fresh install:**
both

**Where did you install ownCloud from:**
downloaded zip and tar.gz extracted and uploaded it

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

Results
=======
- core
	- INVALID_HASH
		- core/doc/admin/_sources/configuration_files/collaborative_documents_configuration.txt
		- core/doc/admin/_static/style.css
		- core/fonts/LICENSE.txt
		- core/vendor/jquery-migrate/jquery-migrate.js
		- core/vendor/jquery-migrate/jquery-migrate.min.js
		- core/vendor/jsTimezoneDetect/jstz.js
- files_external
	- INVALID_HASH
		- 3rdparty/Dropbox/API.php
- files_texteditor
	- INVALID_HASH
		- js/vendor/ace/src-noconflict/mode-diff.js

**List of activated apps:**

Enabled:
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - notes: 2.0.0
  - notifications: 0.2.3
  - ownbackup: true
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: true
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - activity
  - encryption
  - external
  - gallery
  - user_external
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

<?php
$CONFIG = array (
  'instanceid' => 'ocg9x6jzz27v',
  'passwordsalt' =>
  'secret' => '
  'trusted_domains' => 
  array (
    0 => 'cloud.datateam.lu',
    1 => 'www.cloud.datateam.lu',
  ),
  'datadirectory' => '/home/cloud/public_html/data',
  'overwrite.cli.url' => 'https://cloud.datateam.lu',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => '',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'forcessl' => true,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => 1,
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mail_from_address' => 'support',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'datateam.lu',
  'theme' => '',
  'trashbin_retention_obligation' => 'auto',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
dropbox

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
IE/Chrome/Safari

**Operating system:**
iOS/Windows

#### Web server error log
```
Insert your webserver log here
```

error.log

rn] [pid 12572] [client 87.240.239.116:50511] mod_fcgid: stderr: PHP Fatal error:  Cannot redeclare class OC_L10N in /home/cloud/public_html/lib/private/l10n.php on line 42
[Tue Mar 08 17:34:41.620258 2016] [fcgid:warn] [pid 12580] [client 87.240.239.116:50516] mod_fcgid: stderr: PHP Fatal error:  Cannot redeclare class OC_L10N in /home/cloud/public_html/lib/private/l10n.php on line 42
[Tue Mar 08 17:35:02.630401 2016] [fcgid:warn] [pid 12570] [client 87.118.119.115:54243] mod_fcgid: stderr: PHP Fatal error:  Cannot redeclare class OC_L10N in /home/cloud/public_html/lib/private/l10n.php on line 42
[Tue Mar 08 17:35:45.532918 2016] [authz_core:error] [pid 29173] [client 87.240.239.116:50522] AH01630: client denied by server configuration: /home/cloud/public_html/config/
[Tue Mar 08 17:35:45.554201 2016] [authz_core:error] [pid 29173] [client 87.240.239.116:50522] AH01630: client denied by server configuration: /home/cloud/public_html/data/
[Tue Mar 08 17:35:54.292926 2016] [fcgid:warn] [pid 12572] [client 87.240.239.116:50528] mod_fcgid: stderr: PHP Warning:  require_once(lib/base.php): failed to open stream: No such file or directory in /home/cloud/public_html/index.php on line 37
[Tue Mar 08 17:35:54.292946 2016] [fcgid:warn] [pid 12572] [client 87.240.239.116:50528] mod_fcgid: stderr: PHP Fatal error:  require_once(): Failed opening required 'lib/base.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/cloud/public_html/index.php on line 37
[Tue Mar 08 17:36:21.444799 2016] [fcgid:warn] [pid 12580] [client 213.166.55.173:39224] mod_fcgid: stderr: PHP Warning:  require_once(lib/base.php): failed to open stream: No such file or directory in /home/cloud/public_html/status.php on line 30
[Tue Mar 08 17:36:21.444818 2016] [fcgid:warn] [pid 12580] [client 213.166.55.173:39224] mod_fcgid: stderr: PHP Fatal error:  require_once(): Failed opening required 'lib/base.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/cloud/public_html/status.php on line 30
[Tue Mar 08 17:36:53.458880 2016] [fcgid:warn] [pid 12574] [client 213.166.55.173:39607] mod_fcgid: stderr: PHP Warning:  require_once(lib/base.php): failed to open stream: No such file or directory in /home/cloud/public_html/status.php on line 30
[Tue Mar 08 17:36:53.458895 2016] [fcgid:warn] [pid 12574] [client 213.166.55.173:39607] mod_fcgid: stderr: PHP Fatal error:  require_once(): Failed opening required 'lib/base.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home/cloud/public_html/status.php on line 30
[Tue Mar 08 17:46:29.875719 2016] [fcgid:warn] [pid 29173] [client 213.166.55.173:47309] mod_fcgid: stderr: PHP Warning:  require_once(lib/base.php): failed to open stream: No such file or directory in /home/cloud/public_html/status.php on line 30
[Tue Mar 08 17:46:29.875745 2016] [fcgid:warn] [pid 29173] [client 213.166.55.173:47309] mod_fcgid: stderr: PHP Fatal error

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
multiple errors like:

{"reqId":"VuGFlkJh6W3sDfF3rXReVAAAAAc","remoteAddr":"88.207.217.223","app":"PHP","message":"Undefined index: newVersionString at \/home\/cloud\/public_html\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-10T14:32:54+00:00"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by LukasReschke** [comment]
You have incorrectly updated. For example rn] [pid 12572] [client 87.240.239.116:50511] mod_fcgid: stderr: PHP Fatal error: Cannot redeclare class OC_L10N in /home/cloud/public_html/lib/private/l10n.php on line 42 shows that you did not delete all files except config and data before updating. 

Please restore from a backup and then delete all data except config and data. Then upload the new files.

**Comment by D4rkPh0en1x** [comment]
all files were deleted and to be sure that I didn't do something wrong I did a fresh install with a new database in a new folder and I got exactly the same errors with the integrity check

Here the raw output

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/doc/admin/_sources/configuration_files/collaborative_documents_configuration.txt] => Array
                        (
                            [expected] => 251befed4a319c8e4b390b363a9bc8079b54991891204a4ff1cb551797931ba9f276903e1e5e8bde932afcb5e67d23f7939cea22e68c6bd7695e2b8ce654c5b3
                            [current] => 637ac6c02e3ef06cc19a9b465c5c0e6ae6777f9e5d5d52cae28482f350e3b348a5c3ba67ae693e95971373c326af98c27c7f04492aa836b6ab1348f7341ccb29
                        )

                    [core/doc/admin/_static/style.css] => Array
                        (
                            [expected] => 894b1bea3e2b6bc61824ffebc081339a6caf0b57cda7fa9b9c9a5965e2a165dc177055db176cb535ef465c927b4bc4848802fe3e1b0fb709194b3cb7d2f90f8d
                            [current] => 5d9fbe71f0eae36c5a9c50f98733cc9e7a5bc7b2b56e3937c4431cf5e54649667bbe8f5900cdcbfbaa8b1eb8d5476d42a278d210c38110411885ad818e3a963a
                        )

                    [core/fonts/LICENSE.txt] => Array
                        (
                            [expected] => 4cc5a12bfe984c0a50bf7943e2d70a948d520ef423677c77629707aace3a95aa378d205de929105d644680679e70ef2449479b360ad44896b75bafed66613272
                            [current] => 98f6b79b778f7b0a15415bd750c3a8a097d650511cb4ec8115188e115c47053fe700f578895c097051c9bc3dfb6197c2b13a15de203273e1a3218884f86e90e8
                        )

                    [core/vendor/jquery-migrate/jquery-migrate.js] => Array
                        (
                            [expected] => 083c7aaf7b7304b2610ed5ff851f840d5db24993814128b86f42e8e5749b76e7117f6f154a8465fb4f163c1105ec3c6a5757e9c48b95e869d101de9399780a0e
                            [current] => fc2f4d093d3c8ecbfd30f25c59f30e92bf7457664ecf8871247b1802671b05b674c047bfcd0c2c9a674b49ce0bab9cdaed2416f69797381c775019ec250cbc0d
                        )

                    [core/vendor/jquery-migrate/jquery-migrate.min.js] => Array
                        (
                            [expected] => 7c31817254b71d4cac10120aa2829614311658e468036d27eb43b063b392620c4611ec3db3b3600da3e48fb82a41c5579c048fbd9022156f038b2b6cb5d946b5
                            [current] => 7b68a43a22a41404a2ff58e0da6a237492cad0fc3e56d216980802b4d5fb483895262a7e049340d6670002bdf899ba88c319239e60d0aae1ac31d98556b0ad6e
                        )

                    [core/vendor/jsTimezoneDetect/jstz.js] => Array
                        (
                            [expected] => ece74dd6f5fc9587cf167dd17df51b66f70bd711f445da8d1d21bb1b0570f3c97b25d3ece110b08e2f2b294369d9b775cc169b666840a5b769ba338aa6d73d48
                            [current] => beae737d18aae6e8c5fdfb0bf3389b687ec746e6b334185710cc5b8f45b73b3c57442db541807ab440b55517ef2d138f4c40148abafcb6462481016b617e1f53
                        )

                )

        )

    [files_external] => Array
        (
            [INVALID_HASH] => Array
                (
                    [3rdparty/Dropbox/API.php] => Array
                        (
                            [expected] => a6866ef3ceeb26d9d4b2ccc343aeaf626c82f03e279962bc7d761a68e87e5a7916ff0bcf7a350e20889557336ed9c5dd1651cfe513fa04bb8a03cd6d8f9cc484
                            [current] => 917eed2c4f6359a4d0b8658a36404c83344b0bf72ccda614dd59f97d099b3d9ef4e86691401c64d3754c3f7e0fa163eab946a25dbc7bc65e1694ffd47a054317
                        )

                )

        )

    [files_texteditor] => Array
        (
            [INVALID_HASH] => Array
                (
                    [js/vendor/ace/src-noconflict/mode-diff.js] => Array
                        (
                            [expected] => 4a59b6376376b81e4e12ccc345065db62029a61035a88e19b1be3d7ec4cd9f86444121cca6d46c44a5f86e4f5b44d5109cbc77e80c07ff8dbce61f758b88e765
                            [current] => f8dbde2422c010af18b254a562c9e96865d5e58a698a191c855974f37d5a837ccc243ca85b2a8fbe81c61c53470b877e5b8b3e64cd2951c7f863bf49085aa5d7
                        )

                )

        )

)

**Comment by D4rkPh0en1x** [comment]
I see the error log is also not from now but from 2 days... no errors from today in the apache log
2 days ago I wanted to go to fast and simply overwrite the files instead of deleting all but I undo this...
Didn't had the time until now to look further and to do a fresh install...

**Comment by Nibbels** [comment]
I had exactly the same invalid hashes. After some (long) while I figured it out:

![img](https://cloud.githubusercontent.com/assets/3265671/15223715/1d93fef2-1876-11e6-9248-24546f427ee7.png)

I set Filezilla's Transfermode to Binary then those wrong hashes vanished. But I cannot explain this to myself. Its a CentOS 7 Server with PLESK 12.5.30 and Proftpd

**Comment by Nibbels** [comment]
![image](https://cloud.githubusercontent.com/assets/3265671/15223873/e5f08564-1876-11e6-855d-fbfedbdf5478.png)
![image](https://cloud.githubusercontent.com/assets/3265671/15223890/f75e2824-1876-11e6-81c3-648a5f6b0176.png) ... and I normally use explicit ftp over tls
