### ISSUE TITLE
 PHP Fatal error:  Can't use method return value in write context in /var/www/html/owncloud/apps/files_external/lib/google.php on line 268

### ISSUE THREAD

**Issue by apple601601601** [owncloud/core#23093]
### Steps to reproduce
1. `yum update` to update owncloud from version 8 to 9 from the 'ce_stable                            ownCloud Server stable Community Edition (CentOS_7) ' repository
2. sudo -u apache php occ upgrade to update
3. after successfully update to owncloud 9, access the web interface with admin account and visit menu "Settings" (or "Manage"? I don't know because it displays Chinese here on my machine, just go to the detailed setting page). And you will found the page is blank. Through F12 in browser you can see 'https://192.168.1.201/index.php/settings/admin' returns 500 error, and here is what I got from Apache ssl_error_log:
 [:error] [pid 91626] [client 192.168.1.3:8427] PHP Fatal error:  Can't use method return value in write context in /var/www/html/owncloud/apps/files_external/lib/google.php on line 268

### Expected behaviour
It should show the Settings/Manage page

### Actual behaviour
 after successfully update to owncloud 9, access the web interface with admin account and visit menu "Settings" (or "Manage"? I don't know because it displays Chinese here on my machine, just go to the detailed setting page). And you will found the page is blank. Through F12 in browser you can see 'https://192.168.1.201/index.php/settings/admin' returns 500 error, and here is what I got from Apache ssl_error_log:
 [:error] [pid 91626] [client 192.168.1.3:8427] PHP Fatal error:  Can't use method return value in write context in /var/www/html/owncloud/apps/files_external/lib/google.php on line 268

### Server configuration
**Operating system**: CentOS7

**Web server:** Apache

**Database:** Mariadb

**PHP version:** 5.4.16

**ownCloud version:** (see ownCloud admin page) 9.0.0

**Updated from an older ownCloud or fresh install:** Updated from version 8

**Where did you install ownCloud from:**  yum 'ce_stable      ownCloud Server stable Community Edition (CentOS_7) ' repository

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
`No errors have been found.`

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**
```
─
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxx',
  'passwordsalt' => 'xxxxxx',
  'secret' => 'xxxxxx',
  'trusted_domains' =>
  array (
    0 => '192.168.2.201',
    1 => '192.168.1.201',
  ),
  'datadirectory' => '/xxxxxx',
  'overwrite.cli.url' => 'http://192.168.2.201/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'xxxxxx',
  'dbhost' => 'xxxxxx',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxx',
  'dbpassword' => 'xxxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'updatechecker' => false,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/... no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

**Operating system:** Windows7

#### Web server error log
```
[:error] [pid 91786] [client 192.168.1.3:8362] PHP Fatal error:  Can't use method return value in write context in /var/www/html/owncloud/apps/files_external/lib/google.php on line 268
 [:error] [pid 91627] [client 192.168.1.3:8371] PHP Fatal error:  Can't use method return value in write context in /var/www/html/owncloud/apps/files_external/lib/google.php on line 268
```

#### ownCloud log (data/owncloud.log)
```
nothing abnormal there
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

I've checked on Github in core/apps/files_external/lib/google.php and seems this problem is already fixed, however it had not go in with the yum update command. Please have a check on that.

**Comment by LukasReschke** [comment]
Will be fixed with 9.0.1. Ref https://github.com/owncloud/core/commit/d14adb2351911030bd9eff4311493dd63826c5ee
