### ISSUE TITLE
New Install Problems (9.0.0)

### ISSUE THREAD

**Issue by D4rkPh0en1x** [owncloud/core#23107]
### Steps to reproduce
1.  9.0  fresh install
2. login
3. integrity check failed (for the web installer file even after deleting it) / not possible to add user / security & setup warnings doesn't load (turns endlessly) / app list stay empty so over the web i can't activate calendar/contacts etc

### Expected behaviour
No error

### Actual behaviour
In the web I can't see my files and data

### Server configuration
**Operating system**:
Red Hat 7.0

**Web server:**
Apache 2.4.6

**Database:**
Mysql 5.6.29

**PHP version:**
5.6.19

**ownCloud version:** (see ownCloud admin page)
9.0.0

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
installed with the web installer

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - calendar
  - contacts
  - encryption
  - external
  - files_external
  - notes
  - ownbackup
  - tasks
  - user_external
  - user_ldap 

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
<?php
$CONFIG = array (
  'instanceid' => 'ocuqwwpnel35',
  'passwordsalt' => ,
  'secret' => ,
  'trusted_domains' => 
  array (
    0 => 'cloud.datateam.lu',
  ),
  'datadirectory' => '/home/cloud/public_html/data',
  'overwrite.cli.url' => 'https://cloud.datateam.lu',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => ,
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => ,
  'dbpassword' => ,
  'logtimezone' => 'UTC',
  'installed' => true,
);
**Are you using external storage, if yes which one:** local/smb/sftp/...
not yet

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
IE/Chrome/Safari

**Operating system:**
iOS/Windows

#### Web server error log
```
Insert your webserver log here
```
no errors in the log for this fresh install

#### ownCloud log (data/owncloud.log)
```

{"reqId":"VuGU2-6CLT7701@UGSbc2AAAAAc","remoteAddr":"88.207.217.223","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_frank\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'cloud'@'localhost' for table 'user'","level":3,"time":"2016-03-10T15:38:03+00:00"}
{"reqId":"VuGU2-6CLT7701@UGSbc2AAAAAc","remoteAddr":"88.207.217.223","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `cloud` . * TO 'cloud'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1410 You are not allowed to create a user with GRANT","level":3,"time":"2016-03-10T15:38:03+00:00"}
{"reqId":"VuGU2-6CLT7701@UGSbc2AAAAAc","remoteAddr":"88.207.217.223","app":"PHP","message":"Undefined offset: 0 at \/home\/cloud\/public_html\/lib\/private\/setup\/mysql.php#46","level":3,"time":"2016-03-10T15:38:03+00:00"}
{"reqId":"VuGU2-6CLT7701@UGSbc2AAAAAc","remoteAddr":"88.207.217.223","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/installer.php(621): include('\\\/home\\\/cloud\\\/pub...')\\n#4 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/home\\\/cloud\\\/pub...')\\n#5 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/home\\\/cloud\\\/public_html\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/home\\\/cloud\\\/public_html\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-03-10T15:38:04+00:00"}
{"reqId":"VuGU2-6CLT7701@UGSbc2AAAAAc","remoteAddr":"88.207.217.223","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/installer.php(621): include('\\\/home\\\/cloud\\\/pub...')\\n#4 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/home\\\/cloud\\\/pub...')\\n#5 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/home\\\/cloud\\\/public_html\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/home\\\/cloud\\\/public_html\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/home\\\/cloud\\\/public_html\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/home\\\/cloud\\\/public_html\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-03-10T15:38:04+00:00"}
{"reqId":"VuGVUsaEDCPC3wFNSCMMEAAAAAA","remoteAddr":"87.118.119.115","app":"core","message":"Trusted domain error. \"87.118.119.115\" tried to access using \"www.cloud.datateam.lu\" as host.","level":2,"time":"2016-03-10T15:40:02+00:00"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by D4rkPh0en1x** [comment]
I just gave all the possible rights to the database user (even superuser rights) and that didn't Change anything (new install after changing this)

**Comment by D4rkPh0en1x** [comment]
Activating the apps like calendar and contacts over the occ command doesn't have any effects on the webside

**Comment by PVince81** [comment]
How did you manage to enable calendar app if you weren't able to setup the database in the first place ?

**Comment by PVince81** [comment]
This looks like a setup error:
```
SELECT command denied to user 'cloud'@'localhost' for table 'user'
```

What command did you use for setting up the permissions ?

**Comment by D4rkPh0en1x** [comment]
Hi
I activated calendar over the command line with the occ command as over the web it didn't work...
For the database permissions I changed them over virtualmin web system. So not only the permissions on the database but for the user in global (so for every database)

**Comment by PVince81** [comment]
Okay, so you did manage to get the database working. Because your message from https://github.com/owncloud/core/issues/23107#issuecomment-194929208 said changing the permissions didn't work.

Any log messages when trying to enable the calendar/contact apps ?

**Comment by D4rkPh0en1x** [comment]
Ah now I understand what you mean... sorry wasn't precise enough. 
Even with this db error in the log the db was generated, I could see all tables...
When I go over the web to page where I can enable the apps it just stays empty, no categories etc...
Same with the files...
In the admin the security and setup warnings just loads endless and no more entries in the log...
My 8.2.3 I just reinstalled this morning works without problems.. That is why I don't understand why the one version works and the other not...

**Comment by D4rkPh0en1x** [comment]
I can give you access on the test server I installed to see what's working before trying to upgrade again so you can see by yourself

**Comment by MorrisJobke** [comment]
@D4rkPh0en1x This seems to be clearly a setup issue. Could I ask you to open this in the forums: https://forum.owncloud.org

This here is a bug tracker and not a support platform. 

This seems to be a problem with the DB user permissions. Please check them again, that they are set properly. Thanks
