### ISSUE TITLE
"Add to owncloud" should offer some kind of visual feedback

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#23106]
### Steps to reproduce
1. Follow a public link
2. Click on "Add to owncloud
3. Type 666 and "Enter"
4. Wait

### Expected behaviour

There should be some visual feedback that the query is being executed. It's usually a spinner. In this case, it could be in the middle of the field.

### Actual behaviour

Nothing happens for 20-30 seconds. The user gets confused and thinks ownCloud is broken.
After a while, a message is shown letting the user know that that URL doesn't lead to a valid share.

There is also the case against endless spinners as it's not a clear indication that things are working, but it's better than nothing I think.

@jancborchardt

**Comment by jancborchardt** [comment]
Aaah yes – the icon-confirm (the arrow) should change into icon-loading-small of course! :)

@owncloud/javascript anyone down for doing this? Otherwise this is indeed a perfect junior job.
