### ISSUE TITLE
Files shared with me cannot be moved to folders I share

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#23111]
### Steps to reproduce
1. A shares File with B
2. File is shown in the root of B's instance
3. B creates folder F1
4. B creates folder F2
5. B shares folder F2. In my case both internally and via link
6. B moves file to F2
### Expected behaviour

The file should be moved to F2
### Actual behaviour

I get a "Could not move" error message.
If I move file to F1 it works though
And if I move another file to F2 it also works

So for some reason files shared with me cannot be moved to folders I share
### Server configuration

**ownCloud version:** stable9

---

@rullzer @PVince81

**Comment by rullzer** [comment]
This is by design. It can become a big mess if we allow nested shares like this. Cyclic shares. Explicit order required for share initialisation etc.

Also there is the problem with permissions. Assume you share the B with full permissions. But the folder shared with you is only R. Then now all of a sudden you have increased the permissions.

Those (among others) are reasons we decided not to support nested sharing. Since it really opens up a can of worms.

**Comment by oparoz** [comment]
*  Cyclic shares: OK, can lead to an infinite loop, but surely, it must be possible to identify that the sharee is the same as the original owner
* Explicit order required for share initialisation: Not sure I understand what the problem is here, so I'll have to trust you :)
* Permissions: I can see how that can increase the complexity of the system as you would have to track permissions of shares inside shares, but at the same time it's really useful. All children in a family share their personal picture folder with the parents' cloud. The parents can share this folder containing individual shares to their parents. Without the functionality in place, they will have to re-share each share individually

I think a good start would be to list the use cases and dangerous behaviours to avoid. Might be too early in this life's project to implement, but could be useful in the future.

**Comment by sbrl** [comment]
I'd love the ability to move files shared with me. If folders are out of scope and too complex, that's fine. Perhaps files shared with me can't be put inside shared folders? That would be an improvement on the current situation, and I for one would be fine with that limitation.

**Comment by sbrl** [comment]
@JanAckermann why close this issue? I strongly recommend against closing issues without explanation.
