### ISSUE TITLE
OC 9 Search broken

### ISSUE THREAD

**Issue by apg1980** [owncloud/core#23136]
My Environment:
Ubuntu 14.04
OC 9
Apache to 2.4.17
PHP to 5.5.29
MySQL to 5.6.25

I can search for files via the search field, results are displayed. After clicking on a result which is outside the root folder i get following message in the browser:

Not Found
The requested URL /files/index.php was not found on this server.

I cannot see any log entrys.
Files in the root directory can be opened via the search results.

**Comment by LukasReschke** [comment]
Can reproduce.
