### ISSUE TITLE
Trusted domains are being ignored.

### ISSUE THREAD

**Issue by texastoastt** [owncloud/core#23131]
### Steps to reproduce
1. Fresh install of 9.0.0
2. Add domain to trusted domain list
3. Test

### Expected behaviour
Access accepted when using trusted domain

### Actual behaviour
Generates message to add as a trusted domain every time, but can confirm the line is being added to config.php

### Server configuration
**Operating system**: CentOS 7

**Web server**: Apache

**Database**: MariaDB

**PHP version**: 5.4.16

**ownCloud version**: 9.0.0

**Updated from an older ownCloud or fresh install**: Fresh install

**Where did you install ownCloud from**: Owncloud repo

**Signing status (ownCloud 9.0 and above)**: 

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**

None

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocprsje3iele",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.11.22",
            "home.coreyboyd.com:25683",
            "home.coreyboyd.com:25683",
            "home.coreyboyd.com:25683"
        ],
        "datadirectory": "\/home\/owncloud",
        "overwrite.cli.url": "http:\/\/home.coreyboyd.com:25683",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "192.168.11.16",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "cloud",
        "mail_domain": "home.coreyboyd.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.tridenthosting.net",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
None

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:** Chrome

**Operating system:** Mac OSX El Capitan

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
Might be already fixed with https://github.com/owncloud/core/pull/23125

**Comment by LukasReschke** [comment]
Yep. That will fix it.
