### ISSUE TITLE
Multiple federated unsharing removes the last, not the removed one

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#23148]
### Steps to reproduce
1. UserA (serverA) share a file with these sharees:

user1(server1)
user2(server1)
user1(server2)
user2(server2)

The list of sharees is displayed in that order in UserA account

2. All the sharees accept the federated sharing
3. One of the sharees (for example, the first one: user1 in server1) does not want the file and removes (unshares) it

### Expected behaviour
The list of sharees for UserA is:

user2(server1)
user1(server2)
user2(server2)

user1(server1) was removed because the sharee unshared it

### Actual behaviour

The list of sharees for UserA is:

user1(server1)
user2(server1)
user1(server2)

It was removed the last one of the list instead of the unshared one. If another user unshared the content as well, it will be removed the last one of the list -> user1(server2)

### Server configuration
ServerA: {"installed":true,"maintenance":false,"version":"9.0.0.19","versionstring":"9.0.0","edition":""}
Server1: {"installed":true,"maintenance":false,"version":"9.0.0.19","versionstring":"9.0.0","edition":""}
Server2: {"installed":true,"maintenance":false,"version":"9.0.0.19","versionstring":"9.0.0","edition":""}

The usernames to check were the same as descripted before

**Comment by icewind1991** [comment]
Can reproduce, will look into it
