### ISSUE TITLE
Log successful login attempts

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#23146]
As of today the failed login attempts are logged, but it would be nice to log the successfull ones as well. Why? Because it gives a better control if you get bruteforced for example, "did they succeed". Today you don't know that.

Several large organisations also send an email when someone logged in from a new IP. It would be super if that could be implemented.

cc @LukasReschke

**Comment by ankitjain28may** [comment]
You want to enhance the feature, when someone login from other IP, a mail would be sent through your page.

**Comment by PVince81** [comment]
logging success is done in the admin_audit app.

as for brute-force protection, there is already an app for this use case: https://marketplace.owncloud.com/apps/brute_force_protection
