### ISSUE TITLE
Users which username finishes with '@' can not receive federated shares

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#23150]
### Steps to reproduce
1. Share a file/folder with a user "user@" in another server

### Expected behaviour
user@ is an available option to share with

### Actual behaviour
The file can not be share and this message is received:

Sharing <file> failed, could not find user1@@<server>, maybe the server is currently unreachable.

### Server configuration
ServerA: {"installed":true,"maintenance":false,"version":"9.0.0.19","versionstring":"9.0.0","edition":""}
Server1: {"installed":true,"maintenance":false,"version":"9.0.0.19","versionstring":"9.0.0","edition":""}

**Comment by PVince81** [comment]
@schiesbn @rullzer

**Comment by rullzer** [comment]
@jesmrec I can share with a user ending in an @.

Can you please double check?

**Comment by jesmrec** [comment]
Checked and works fine in

{"installed":true,"maintenance":false,"version":"9.0.0.19","versionstring":"9.0.0","edition":"Enterprise"}
