### ISSUE TITLE
Add setup check for libxml2 >= 2.7.0

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#23168]
As shown in https://github.com/owncloud/core/issues/23054#issuecomment-195423190 we require at least libxml2-2.7.0.

I suspect this to be already the case for some time. But in 9.0 we switched to webdav also for the webUI.

Note libxml2-2.7.0 was released in august 2008. So it should not be a common issues.

Would be good to add a check for this in the setup warning.

**Comment by PVince81** [comment]
I think Sabre 3.0 which we use in OC 9.0 is using a different XML approach, using some PHP XML methods. I guess these might be using libxml internally somehow...

**Comment by rullzer** [comment]
Yes. https://groups.google.com/d/msg/sabredav-discuss/9JxxSr7mGBY/gEM52ghVCgAJ
