### ISSUE TITLE
OCC upgrade failed - restarted server as db was down, reran upgrade and getting this "oc_trusted_servers" already exists. 

### ISSUE THREAD

**Issue by lbeckm3** [owncloud/core#23160]
Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing 'CREATE TABLE "oc_trusted_servers" ("id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "url" VARCHAR(512) NOT NULL, "url_hash" VARCHAR(255) DEFAULT '' NOT NULL, "token" VARCHAR(128) DEFAULT NULL, "shared_secret" VARCHAR(256) DEFAULT NULL, "status" INTEGER DEFAULT 2 NOT NULL, "sync_token" VARCHAR(512) DEFAULT NULL)': SQLSTATE[HY000]: General error: 1 table "oc_trusted_servers" already exists

Owncloud is on Ubuntu 14.04 and was done via apt.

**Comment by LukasReschke** [comment]
Please fill out the issue template. Thanks a lot.

Also if the upgrade failed to restore from a backup and then retry the update. Please try that again as well.

**Comment by lbeckm3** [comment]
I was able to correct the issue by migrating to MySQL and then dropping and
recreating the database.  I have a simple 2-user setup so no big deal.
Thanks!
