### ISSUE TITLE
Unable to decrypt files on 8.2.2

### ISSUE THREAD

**Issue by myjar** [owncloud/core#23177]
### Steps to reproduce
1. Click to download file
2. Files download begins then dies.

1. Try to decrypt users files from command line using recovery key.
2. Fails with 

 [-->-------------------------]PHP Fatal error:  Call to a member function get() on a non-object in /var/www/owncloud/apps/files_sharing/lib/updater.php on line 77

### Server configuration
Server: Ubuntu 14.04
Database: MYSQL
OC-Version: 8.2.2
PHP-Version:
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

Originally an update from version 8.0

We have had no issues until server was rebooted. But now 2 users have no access to their encrypted files.

**The content of config/config.php:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "docstore.myjar.com",
            "52.16.120.39"
        ],
        "datadirectory": "\/storage\/ocdata",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "oc3hhlrgxe29",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 0,
        "mail_smtphost": "mail.myjar.com",
        "filelocking.enabled": true,
        "ldapIgnoreNamingRules": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "docstore",
        "mail_domain": "myjar.com",
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "singleuser": true
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.1.3",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "2221"
        },
        "core": {
            "OC_Channel": "production",
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "encryption_enabled": "yes",
            "incoming_server2server_share_enabled": "yes",
            "installedat": "1441274219.2541",
            "lastcron": "1457783418",
            "lastupdateResult": "{\"version\":{},\"versionstring\":{},\"url\":{},\"web\":{}}",
            "lastupdatedat": "1457785239",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "files_sharing\/publicwebdav.php",
            "remote_files": "files\/appinfo\/remote.php",
            "remote_webdav": "files\/appinfo\/remote.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "shareapi_allow_public_upload": "yes",
            "shareapi_default_expire_date": "yes",
            "shareapi_enabled": "yes",
            "shareapi_enforce_expire_date": "yes",
            "shareapi_enforce_links_password": "yes"
        },
        "encryption": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "masterKeyId": "master_6efb3235",
            "publicShareKeyId": "pubShare_ebc0c491",
            "recoveryAdminEnabled": "1",
            "recoveryKeyId": "recoveryKey_ebc0c491",
            "types": "filesystem"
        },
        "external": {
            "enabled": "no",
            "installed_version": "1.2",
            "ocsid": "166046",
            "types": ""
        },
        "files": {
            "default_quota": "5 GB",
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_antivirus": {
            "av_chunk_size": "1024",
            "av_cmd_options": "",
            "av_host": "",
            "av_infected_action": "only_log",
            "av_mode": "executable",
            "av_path": "\/usr\/bin\/clamscan*",
            "av_port": "0",
            "av_socket": "\/var\/run\/clamav\/clamd.ctl",
            "enabled": "yes",
            "installed_version": "0.8.0.1",
            "ocsid": "157439",
            "types": "filesystem"
        },
        "files_external": {
            "\/Additionastorage": "1441698924",
            "\/local": "1441699114",
            "\/storage": "1441699030",
            "allow_user_mounting": "no",
            "enabled": "no",
            "installed_version": "0.3.0",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "\\OC\\Files\\Storage\\AmazonS3,\\OC\\Files\\Storage\\Dropbox,\\OC\\Files\\Storage\\FTP,\\OC\\Files\\Storage\\Google,\\OC\\Files\\Storage\\Swift,\\OC\\Files\\Storage\\OwnCloud,\\OC\\Files\\Storage\\SFTP,\\OC\\Files\\Storage\\SFTP_Key,\\OC\\Files\\Storage\\DAV"
        },
        "files_locking": {
            "enabled": "yes",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_mv": {
            "enabled": "no",
            "installed_version": "0.8.1a",
            "ocsid": "150271",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.7",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "104": "1450107892.8391",
            "105": "1450107892.8511",
            "106": "1450107892.8633",
            "107": "1450107892.8789",
            "108": "1450107892.8879",
            "109": "1450107892.9",
            "110": "1450107892.9124",
            "111": "1450107892.9287",
            "112": "1450107892.9409",
            "113": "1454525626.5607",
            "116": "1454525626.562",
            "122": "1454525626.5627",
            "123": "1454525626.5636",
            "124": "1454525626.5655",
            "125": "1454525626.5664",
            "126": "1452440289.4425",
            "127": "1454525626.5672",
            "128": "1454525626.568",
            "132": "1453209100.8393",
            "134": "1454525626.5697",
            "136": "1454525626.5706",
            "137": "1453370890.2956",
            "138": "1454525626.5714",
            "139": "1453370799.3047",
            "140": "1454525626.5722",
            "149": "1457001286.1592",
            "150": "1456307911.368",
            "151": "1457345192.055",
            "152": "1457345192.0563",
            "153": "1457345192.0571",
            "154": "1457345192.0589",
            "155": "1457345192.0597",
            "156": "1457345192.0605",
            "157": "1457345192.0629",
            "158": "1457345192.0638",
            "159": "1457345192.0645",
            "160": "1457345192.0667",
            "161": "1457418818.7326",
            "162": "1457418818.7409",
            "163": "1457418818.7531",
            "164": "1457418818.7654",
            "165": "1457418818.7776",
            "166": "1457418818.7899",
            "167": "1457418818.8021",
            "168": "1457418818.8143",
            "169": "1457418818.8266",
            "170": "1457418818.8412",
            "171": "1457418818.8512",
            "172": "1457418818.8633",
            "21": "1446112371.5819",
            "25": "1446112371.5837",
            "28": "1446112371.6483",
            "29": "1446112371.6605",
            "30": "1446112371.6728",
            "31": "1446112371.6851",
            "33": "1444227995.7149",
            "34": "1444227995.7262",
            "35": "1444227995.7875",
            "36": "1443424887.1543",
            "38": "1443004090.7607",
            "39": "1444227995.7997",
            "40": "1444227995.812",
            "41": "1444227995.8242",
            "5": "1446653911.8076",
            "54": "1443424887.2097",
            "6": "1446653911.8191",
            "61": "1452097529.8355",
            "62": "1452097529.8364",
            "63": "1452097529.8382",
            "7": "1446653911.8313",
            "70": "1444584693.5542",
            "75": "1446112371.6938",
            "76": "1453410834.182",
            "77": "1453410834.183",
            "78": "1453410834.1838",
            "79": "1453410834.1857",
            "8": "1446653911.8436",
            "80": "1453410834.1865",
            "81": "1453410834.1872",
            "82": "1453410834.1879",
            "83": "1453410834.1897",
            "91": "1446816577.1511",
            "92": "1446816577.1529",
            "93": "1446816577.1544",
            "94": "1446816577.1552",
            "enabled": "yes",
            "incoming_server2server_share_enabled": "yes",
            "installed_version": "0.7.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.0",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.7.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "files_videoviewer": {
            "enabled": "yes",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "14.2.0",
            "types": ""
        },
        "ownbackup": {
            "enabled": "yes",
            "installed_version": "0.3.8",
            "ocsid": "170674",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "no",
            "installed_version": "0.3.0",
            "types": "filesystem"
        },
        "storagecharts2": {
            "enabled": "no",
            "installed_version": "2.6.1",
            "types": ""
        },
        "templateeditor": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "updater": {
            "enabled": "yes",
            "installed_version": "0.6",
            "types": ""
        },
        "user_external": {
            "enabled": "yes",
            "installed_version": "0.4",
            "ocsid": "166060",
            "types": "authentication,prelogin"
        },
        "user_ldap": {
            "cleanUpJobOffset": "200",
            "enabled": "yes",
            "enforce_home_folder_naming_rule": "",
            "has_memberof_filter_support": "1",
            "home_folder_naming_rule": "",
            "installed_version": "0.7.1",
            "last_jpegPhoto_lookup": "0",
            "ldap_agent_password": "S2ZkcmczNDltQTNNTmFyZ2Y=",
            "ldap_attributes_for_group_search": "",
            "ldap_attributes_for_user_search": "",
            "ldap_backup_host": "",
            "ldap_backup_port": "",
            "ldap_base": "DC=txt,DC=local",
            "ldap_base_groups": "OU=Employee,DC=txt,DC=local",
            "ldap_base_users": "OU=Employee,DC=txt,DC=local",
            "ldap_cache_ttl": "600",
            "ldap_configuration_active": "1",
            "ldap_display_name": "displayname",
            "ldap_dn": "CN=OwnCloud_AD_Import,CN=Users,DC=txt,DC=local",
            "ldap_email_attr": "mail",
            "ldap_experienced_admin": "0",
            "ldap_expert_username_attr": "",
            "ldap_expert_uuid_group_attr": "",
            "ldap_expert_uuid_user_attr": "",
            "ldap_group_display_name": "cn",
            "ldap_group_filter": "(&(|(objectclass=group)))",
            "ldap_group_filter_mode": "0",
            "ldap_group_member_assoc_attribute": "member",
            "ldap_groupfilter_groups": "",
            "ldap_groupfilter_objectclass": "group",
            "ldap_host": "90.190.150.162",
            "ldap_login_filter": "(&(&(|(objectclass=person)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))",
            "ldap_login_filter_mode": "0",
            "ldap_loginfilter_attributes": "",
            "ldap_loginfilter_email": "1",
            "ldap_loginfilter_username": "1",
            "ldap_nested_groups": "0",
            "ldap_override_main_server": "",
            "ldap_paging_size": "500",
            "ldap_port": "15571",
            "ldap_quota_attr": "",
            "ldap_quota_def": "",
            "ldap_tls": "0",
            "ldap_turn_off_cert_check": "0",
            "ldap_user_filter_mode": "0",
            "ldap_userfilter_groups": "",
            "ldap_userfilter_objectclass": "user",
            "ldap_userlist_filter": "(&(|(objectclass=user)))",
            "types": "authentication",
            "use_memberof_to_detect_membership": "1"
        }
    }
}

```
**Are you using encryption:** yes

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
+-------------------------------+----------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                              |
+-------------------------------+----------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                            |
| hasPagedResultSupport         |                                                                                              |
| homeFolderNamingRule          |                                                                                              |
| lastJpegPhotoLookup           | 0                                                                                            |
| ldapAgentName                 | CN=OwnCloud_AD_Import,CN=Users,DC=txt,DC=local                                               |
| ldapAgentPassword             | ***                                                                                          |
| ldapAttributesForGroupSearch  |                                                                                              |
| ldapAttributesForUserSearch   |                                                                                              |
| ldapBackupHost                |                                                                                              |
| ldapBackupPort                |                                                                                              |
| ldapBase                      | DC=txt,DC=local                                                                              |
| ldapBaseGroups                | OU=Employee,DC=txt,DC=local                                                                  |
| ldapBaseUsers                 | OU=Employee,DC=txt,DC=local                                                                  |
| ldapCacheTTL                  | 600                                                                                          |
| ldapConfigurationActive       | 1                                                                                            |
| ldapEmailAttribute            | mail                                                                                         |
| ldapExperiencedAdmin          | 0                                                                                            |
| ldapExpertUUIDGroupAttr       |                                                                                              |
| ldapExpertUUIDUserAttr        |                                                                                              |
| ldapExpertUsernameAttr        |                                                                                              |
| ldapGroupDisplayName          | cn                                                                                           |
| ldapGroupFilter               | (&(|(objectclass=group)))                                                                    |
| ldapGroupFilterGroups         |                                                                                              |
| ldapGroupFilterMode           | 0                                                                                            |
| ldapGroupFilterObjectclass    | group                                                                                        |
| ldapGroupMemberAssocAttr      | member                                                                                       |
| ldapHost                      | 90.190.150.162                                                                               |
| ldapIgnoreNamingRules         |                                                                                              |
| ldapLoginFilter               | (&(&(|(objectclass=person)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                              |
| ldapLoginFilterEmail          | 1                                                                                            |
| ldapLoginFilterMode           | 0                                                                                            |
| ldapLoginFilterUsername       | 1                                                                                            |
| ldapNestedGroups              | 0                                                                                            |
| ldapOverrideMainServer        |                                                                                              |
| ldapPagingSize                | 500                                                                                          |
| ldapPort                      | 15571                                                                                        |
| ldapQuotaAttribute            |                                                                                              |
| ldapQuotaDefault              |                                                                                              |
| ldapTLS                       | 0                                                                                            |
| ldapUserDisplayName           | displayname                                                                                  |
| ldapUserFilter                | (&(|(objectclass=user)))                                                                     |
| ldapUserFilterGroups          |                                                                                              |
| ldapUserFilterMode            | 0                                                                                            |
| ldapUserFilterObjectclass     | user                                                                                         |
| ldapUuidGroupAttribute        | auto                                                                                         |
| ldapUuidUserAttribute         | auto                                                                                         |
| turnOffCertCheck              | 0                                                                                            |
| useMemberOfToDetectMembership | 1                                                                                            |
+-------------------------------+----------------------------------------------------------------------------------------------+

```
Trying to download any file from the user results in this type of error:

{"reqId":"U\/BRMR8ofmVPf7QfONRK","remoteAddr":"90.190.149.165","app":"webdav","message":"Exception: {\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(442): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('0ix2C63rZfZ1Qo4...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(281): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#2 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(67): fread(Resource id #36, 8192)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(88): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#5 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(70): file_put_contents('php:\\\/\\\/output', Resource id #39)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php\",\"Line\":324}","level":4,"time":"2016-03-12T11:42:27+00:00","method":"GET","url":"\/remote.php\/webdav\/AD\/Rebrand\/Touch%20Points%20&%20Timelines\/Rebrand%20Touch%20Points%202012-11-9.xlsx"}

I know for a fact that this file is not shared and is owned by the user in question.
```

**Comment by RealRancor** [comment]
Is this your forums thread: https://forum.owncloud.org/viewtopic.php?f=36&t=34271

It might be useful then to note that you have reverted to a backup and that this might be related to https://github.com/owncloud/core/issues/22042 as pointed out in the forums thread.

**Comment by myjar** [comment]
Yes that is my thread. I will close that as didn't think to raise it here at first.

The only part that was backed up and then restored was the actual user folders, and not the entire data folder, will this have an impact?

Will read through the link issue and update.

**Comment by myjar** [comment]
Ok, I have applied the patch and set encrypted to 1 on the users files, but I am still unable to download or see them.

What am I missing?

**Comment by myjar** [comment]
Ok, so eventually I am able to download about 90% of the files, but there is about 10% which are showing as 0kb and will not download. I know that these are actual documents etc. Any ideas on how to resolve this?

**Comment by myjar** [comment]
Clicking on any of these 0kb files gives a 403 forbidden error and nothing gets logged.

**Comment by PVince81** [comment]
@myjar can you find the matching entries for the 10% broken files in the "oc_filecache" ?

**Comment by PVince81** [comment]
@myjar by the way, please upgrade to 8.2.3 and try downloading them again. There is new code there that should repair broken file sizes.

**Comment by myjar** [comment]
What upgrade method should I use to upgrade to 8.2.3 ?

**Comment by PVince81** [comment]
See https://doc.owncloud.org/server/8.2/admin_manual/maintenance/upgrade.html#how-to-upgrade-your-owncloud-server

It depends what you used. If you used distro packages, then use distro packages to update.
If you used tarballs, then use tarballs for upgrade, see https://doc.owncloud.org/server/8.2/admin_manual/maintenance/manual_upgrade.html

**Comment by myjar** [comment]
Ok, I have run the upgrade, and nothing new was broken.

However the files that are reporting 0kb are still there and give a 403 forbidden when attempted to download them.

here is an example from the oc_filecache for one of the documents in question:

(9074,18,'files/AD/INTERNATIONAL/MYJAR Spain/Aemip/Aemip Code of Conduct.docx','10f0f18aaa037b7688d1775599220f46',8966,'Aemip Code of Conduct.docx',11,5,0,1453464890,1453464890,1,0,'7188c5a6b11d030aaafd51bceb87e982',27),(9075,18,'files/AD/INTERNATIONAL/MYJAR Spain/Aemip/Contact Report – Aemip 14.01.16.docx','c2bd614f20b4b34f8fd203c8ee768f59',8966,'Contact Report – Aemip 14.01.16.docx',11,5,0,1453105614,1453105614,1,0,'9fc523091afe9823ed035037b61ee493',27)

**Comment by myjar** [comment]
and I have run files:scan --all and it made no difference

**Comment by PVince81** [comment]
Which one is the "encrypted" flag ? Can you set `.headers on` ?

**Comment by myjar** [comment]
[oc_filecache export.csv.zip](https://github.com/owncloud/core/files/172197/oc_filecache.export.csv.zip)

**Comment by PVince81** [comment]
Hmm, for some reason the size in oc_filecache is set to 0. Try manually setting it to -1, then download the file twice. This should trigger the size-fixing code.

**Comment by myjar** [comment]
tried, and still no dice

**Comment by PVince81** [comment]
Did the size stay -1 in the database ? Does the file on-disk inside the "data" folder has a size > 0 ?

**Comment by myjar** [comment]
In the DB they are still -1 in size

This file in question is actually seen on the server as:

-rw-r--r--  1 www-data www-data 184492 Jan 22 12:14 Aemip Code of Conduct.docx

**Comment by PVince81** [comment]
Ok, then try setting the size in the DB to 184492 and download it **twice** in the web UI.

**Comment by PVince81** [comment]
also the question is whether this file is really encrypted. You can try opening the file directly inside the "data" folder. If the beginning of the file starts with "HBEGIN" then it's encrypted.

**Comment by myjar** [comment]
still 403 forbidden and 0kb

**Comment by PVince81** [comment]
I'm out of ideas now, sorry. You need to find more information about why you're getting 403.
Try setting "loglevel" to 0 and check owncloud.log, Apache's /var/log/apache2/error_log

Is the file really encrypted ?

**Comment by myjar** [comment]
File is encrypted, just checked and it indeed begins with HBEGIN

**Comment by myjar** [comment]
{"reqId":"8cI7PTHLxs5k3ldOZX6v","remoteAddr":"90.190.149.165","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(526): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('ryyO4SxA6\\\/fYxCl...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(445): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fixUnencryptedSize('files\\\/AD\\\/INTERN...', 184492, 184492)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(163): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->verifyUnencryptedSize('files\\\/AD\\\/INTERN...', 184492)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(285): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getMetaData('files\\\/AD\\\/INTERN...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(161): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->isReadable('files\\\/AD\\\/INTERN...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1024): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->isReadable('files\\\/AD\\\/INTERN...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(400): OC\\\\Files\\\\View->basicOperation('isReadable', '\\\/AD\\\/INTERNATION...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(672): OC\\\\Files\\\\View->isReadable('\\\/AD\\\/INTERNATION...')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files.php(164): OC\\\\Files\\\\Filesystem::isReadable('\\\/AD\\\/INTERNATION...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files.php(90): OC_Files::getSingleFile(Object(OC\\\\Files\\\\View), '\\\/AD\\\/INTERNATION...', 'Aemip Code of C...', false)\\n#10 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/download.php(53): OC_Files::get('\\\/AD\\\/INTERNATION...', Array, false)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#12 [internal function]: __lambda_func(Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func('?lambda_114', Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(849): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#15 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php\",\"Line\":324}","level":3,"time":"2016-03-14T15:31:36+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/download.php?dir=%2FAD%2FINTERNATIONAL%2FMYJAR%20Spain%2FAemip&files=Aemip%20Code%20of%20Conduct.docx"}


From logs, file is not shared

**Comment by PVince81** [comment]
Okay, can you check the encryption keys ? Post the contents of "data/$user/files_encryption/keys/files/$path_to_file/OC_DEFAULT_MODULE/". There should be a "fileKey" and a share key with the name of the owner.

**Comment by myjar** [comment]
No keys exist for this file

**Comment by myjar** [comment]
I have a backup from 4 days ago that does contain the keys, am I able to copy these across?

**Comment by PVince81** [comment]
That should work, yes

**Comment by myjar** [comment]
Ok, copied the backup across, and I no longer get the 403 forbidden error, but files that are showing as 0kb are still 0kb after attempting to download twice

**Comment by PVince81** [comment]
Now try again setting their size to -1 and download twice.

By the way, I'm assuming that you're on 8.2.3 now.

**Comment by myjar** [comment]
Correct on 8.2.3

will set to -1 and attempt again

**Comment by myjar** [comment]
still download as zero kb

is there a way to scan the folders and update the DB with the actual unencrypted size?

**Comment by PVince81** [comment]
No, because for that you need the user's passwords to decrypt the files.
Setting the size to -1 is the mechanism that is supposed to tell it to fix the size during the next download. Reference https://github.com/owncloud/core/pull/22579 (https://github.com/owncloud/core/pull/22579/files#diff-a36b9c0307e0126dd50baa38fb4bb74aR463)

@myjar do you still get the 403 error ?

**Comment by myjar** [comment]
We no longer get the 403 error, files will download but with zero kb file size.

As for users Passwords, I have them for the affected users.

**Comment by PVince81** [comment]
There is no mechanism so far to repair encrypted files for specific users unfortunately.
If setting the size to -1 and download the files twice doesn't work, then there must be something else hanging there.

Nothing new in the logs ?

**Comment by myjar** [comment]
Downloading any of these files gives nothing in the logs :(

**Comment by PVince81** [comment]
You could try adding logging statements here:
https://github.com/owncloud/core/pull/22579/files#diff-a36b9c0307e0126dd50baa38fb4bb74aR462
```php
\OC::$server->getLogger()->debug('must repair file path=' . $path . ' unencryptedSize=' . $unencryptedSize, array('app' => 'DEBUG'));
```

And then here https://github.com/owncloud/core/pull/22579/files#diff-a36b9c0307e0126dd50baa38fb4bb74aR494 add:
```php
\OC::$server->getLogger()->debug('fixUnencryptedSize path=' . $path . ' size=' . $size . ' unencryptedSize=' . $unencryptedSize, array('app' => 'DEBUG'));
```

Goal is to find out what is different in your situation compared to the expected one.

**Comment by PVince81** [comment]
@schiesbn looks like the size repair routine doesn't work here for some reason

**Comment by myjar** [comment]
{"reqId":"ny9\/wPXErLkaJFV7sL6Y","remoteAddr":"90.190.149.165","app":"DEBUG","message":"must repair file path=files\/Application\/MYJAR Limited\/Approved persons applications\/Andrew Dellow\/Draft forms\/AuPo_IndvDetailsPDF.pdf unencryptedSize=0","level":0,"time":"2016-03-14T16:32:47+00:00","method":"PUT","url":"\/remote.php\/webdav\/Application\/MYJAR%20Limited\/Approved%20persons%20applications\/Andrew%20Dellow\/Draft%20forms\/AuPo_IndvDetailsPDF.pdf"}

**Comment by myjar** [comment]
ignore the above: 

This is from clicking on a zero kb file:

{"reqId":"W\/CCC+vTY3rE9Xt6OGHi","remoteAddr":"90.190.149.165","app":"DEBUG","message":"must repair file path=files\/AD\/INTERNATIONAL\/NPSDaily.xls unencryptedSize=0","level":0,"time":"2016-03-14T16:33:53+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/download.php?dir=%2FAD%2FINTERNATIONAL&files=NPSDaily.xls"}

**Comment by PVince81** [comment]
Okay, maybe there was a misunderstanding. Please set the **size** column to -1.
Please ignore the `unencrypted_size` column in the database.

**Comment by myjar** [comment]
AH! Now it looks like we are getting files, ones not downloaded are marked as pending on the size

You guys are life savers!

**Comment by PVince81** [comment]
Yeah... I forgot that there was this old unused `unencrypted_size`... very easy to create misunderstandings.

**Comment by myjar** [comment]
No worries, I owe you a beer or 2 :)

**Comment by PVince81** [comment]
One question is: how did you get into this situation in the first place ? Did you try restoring files from backup ?

**Comment by myjar** [comment]
I restored from a backup, but I have a feeling I failed to shutdown the web server and this user performed some sync, either way, it got totally screwed up.

Seems resolved now tho. Many many thanks

**Comment by PVince81** [comment]
Okay, cool. I'll close this then.
