### ISSUE TITLE
No variable sent to listApps method in AppSettingsController

### ISSUE THREAD

**Issue by fengkaijia** [owncloud/core#23174]
### Steps to reproduce
1. Visit Apps Page https://OWNCLOUD/index.php/settings/apps
2. Click any tab but "Enabled", e.g. "Not enabled"

### Expected behaviour
Apps matching the tab name, e.g. "Game", displayed.

### Actual behaviour
It still displays all enabled apps.

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Nginx
**Database:**
MySQL
**PHP version:**
5.5
**ownCloud version:**
Sorry for late report. This happened a long long time ago, at first I just thought it was a cache issue, only till now (9.0) I debug the code.

After a few debug, I found the method controlling the listing of apps -- [listApps](https://github.com/owncloud/core/blob/master/settings/controller/appsettingscontroller.php#L189) function in appsettingscontroller.php didn't recieve any arguments when it's called from ```https://OWNCLOUD/index.php/settings/apps/list?category=???&includeUpdateInfo=?```, e.g. ```https://OWNCLOUD/index.php/settings/apps/list?category=tool&includeUpdateInfo=0```.

So the default value of two parameters: ```$category = '', $includeUpdateInfo = true``` is used. When ```$category``` is an empty string, ```$this->getCategory('')``` returned the default value ```self::CAT_ENABLED``` which lead to ```listApps``` method returning apps in the "Enabled" tab.

Unfortunately, I was unable to find the cause of this.

**Comment by PVince81** [comment]
Cannot reproduce on 9.0.0. The lists are properly filtered on my instances.

**Comment by fengkaijia** [comment]
I finally solved this issue by updating the nginx configuration file to [the latest official version](https://doc.owncloud.org/server/9.0/admin_manual/installation/nginx_configuration.html).

It appears my old nginx configuration (could be date back to ownCloud 7.0 or 6.0) has some conflict with the latest code, and somehow I didn't update the nginx configuration when upgrading to 8.0 and 9.0.

I attached some part of my broken configuration here:

```
rewrite ^/caldav(.*)$ /remote.php/caldav$1 redirect;
rewrite ^/carddav(.*)$ /remote.php/carddav$1 redirect;
rewrite ^/webdav(.*)$ /remote.php/webdav$1 redirect;

location / {
	rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
	rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

	rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
	rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;

	rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;

	try_files $uri $uri/ /index.php;
}

location ~ /remote.php/ {
	dav_methods PUT DELETE MKCOL COPY MOVE;
	dav_ext_methods PROPFIND OPTIONS;
	fastcgi_buffer_size 128k;
	fastcgi_buffers 64 256k;
	fastcgi_busy_buffers_size 256k;
	fastcgi_split_path_info ^(.+\.php)(/.+)$;
	fastcgi_pass unix:/var/run/php5-fpm.sock;
	fastcgi_index index.php;
	include fastcgi_params;
}

location ~ \.php$ {
	fastcgi_buffer_size 128k;
	fastcgi_buffers 64 256k;
	fastcgi_busy_buffers_size 256k;
	fastcgi_split_path_info ^(.+\.php)(/.+)$;
	fastcgi_pass unix:/var/run/php5-fpm.sock;
	fastcgi_index index.php;
	include fastcgi_params;
}
```

Now, I can display all apps correctly with the official configuration. I think a reminder to update nginx configuration in the upgrade guide should be welcomed.
