### ISSUE TITLE
Provisioning API addToGroup as group admin

### ISSUE THREAD

**Issue by michag86** [owncloud/core#23179]
Group admin cannot use addToGroup to do the same tasks like the user management in web ui.

https://github.com/owncloud/core/blob/v9.0.0/apps/provisioning_api/lib/users.php#L389

**Comment by PVince81** [comment]
@MTRichards

**Comment by MTRichards** [comment]
Right, because only the admin can add users to groups, group admins can only manage quota. Under consideration for future releases.

**Comment by michag86** [comment]
But if a group admin can manage groupA and groupB, the group admin can add a member of groupA to groupB.

**Comment by michag86** [comment]
@rullzer What do you think?
I can try to implement the same behaviour like the web usermanagement provides.

**Comment by rullzer** [comment]
@michag86 mmm let me think about this... the subadmin stuff is not very well defined to say the least. Could you write down in an issue the differences between what a subadmin can in the webUI and what a subadmin can in the provisioning API? That might make deciding what is desired easier?

CC: @DeepDiver1975

**Comment by PVince81** [comment]
From what I saw this is already implemented, there was only a bug in permission checking: https://github.com/owncloud/core/pull/25788
