### ISSUE TITLE
Integrity Check: Move excluded files/folders into config array

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#23186]
Ref https://github.com/owncloud/core/blob/5862a067d9d67d3ef70cb064009f81b47ed15efd/lib/private/integritycheck/iterator/excludefoldersbypathfilteriterator.php#L35-L41

**Comment by nickvergessen** [comment]
Btw, while you are on it, can you remove the skeleton folder `core/skeleton/` from the check?

**Comment by LukasReschke** [comment]
> Btw, while you are on it, can you remove the skeleton folder core/skeleton/ from the check?

Why? https://github.com/owncloud/core/blob/c7482eee4eaecefc3e8f68a8dbdce382a8858ac0/config/config.sample.php#L197-L202 is what one should use for custom skeletons :wink:

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/issues/23857#issuecomment-208487469

**Comment by LukasReschke** [comment]
No. That's just an user who updated incorrectly or used the wrong ZIP files or whatever. – That's a bug on their side

**Comment by beat** [comment]
stats and icon folders, and awstats-icon and awstatsicons links are standard for awstats (a popular open-source web-stats package). When installing OwnCloud into the top folder, with open-source VirtualMin panel (and default awstats enabled), those folders exist, and a way to ignore them should be added (e.g. in config.php file), same like content in data (and in config.php too) are ignored.

**Comment by PVince81** [comment]
cc @tomneedham

**Comment by dalenoe** [comment]
I know this is closed. However, I am wondering what is the best way to exclude a file from the integrity check? I have a custom haproxy-check.php script that resides in the same folder as owncloud, and that yellow message nagging in the admin section gets old.

**Comment by PVince81** [comment]
Setting to junior job. Might not be entry-level but should still be easy enough.

**Comment by voroyam** [comment]
In the ownCloud appliance, a certificate has to be imported in this dir
/var/www/owncloud/resources/config/ca-bundle.crt

After an upgrade the integrity check fails, telling me that the hash of this file is different than expected.

can we exclude this file or dir from the check?

**Comment by Peter-Prochaska** [comment]
We can exclude files, but not whole folders </statement>

**Comment by PVince81** [comment]
Basically, no we can't at the moment. But after implementing this ticket, only for files (not folders), it would become possible to configure those through config.php.

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/29126
