### ISSUE TITLE
owncloud upgrade from 8.2.2 to 9.0.0 fails

### ISSUE THREAD

**Issue by jejb** [owncloud/core#23183]
Log:

bedivere:~# sudo -u www-data /var/www/owncloud/occ  upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checking whether the database schema for <activity> can be updated (this can take a long time depending on the database size)
Checking whether the database schema for <files_sharing> can be updated (this can take a long time depending on the database size)
Checking whether the database schema for <files_trashbin> can be updated (this can take a long time depending on the database size)
Checking whether the database schema for <notifications> can be updated (this can take a long time depending on the database size)
Checked database schema update for apps
Updating database schema
Updated database
Disabled incompatible app: calendar
Disabled 3rd-party app: calendar
Disabled incompatible app: contacts
Disabled 3rd-party app: contacts
Disabled incompatible app: documents
Disabled 3rd-party app: documents
Disabled 3rd-party app: files_locking
Disabled 3rd-party app: files_videoviewer
Disabled 3rd-party app: updater
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 0.8
Updating <files_texteditor> ...
Updated <files_texteditor> to 2.1
Updating <gallery> ...
Updated <gallery> to 14.5.0
Updating <files> ...
Updated <files> to 1.4.4
Updating <activity> ...
Updated <activity> to 2.2.1
Updating <files_sharing> ...
Updated <files_sharing> to 0.9.1
Updating <files_trashbin> ...
Updated <files_trashbin> to 0.8.0
Updating <files_versions> ...
Updated <files_versions> to 1.2.0
Updating <notifications> ...
Updated <notifications> to 0.2.3
Updating <provisioning_api> ...
Updated <provisioning_api> to 0.4.1
Update 3rd-party app: calendar
Update 3rd-party app: contacts
Update 3rd-party app: documents
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred while executing 'PRAGMA journal_mode = WAL':

SQLSTATE[HY000]: General error: 10 disk I/O error
Update failed
Maintenance mode is kept active
Reset log level
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 10 disk I/O error' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77
Stack trace:
#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(77): PDO->prepare('UPDATE "oc_file...', Array)
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(984): Doctrine\DBAL\Driver\PDOConnection->prepare('UPDATE "oc_file...')
#2 /var/www/owncloud/lib/private/db/connection.php(205): Doctrine\DBAL\Connection->executeUpdate('UPDATE "oc_file...', Array, Array)
#3 /var/www/owncloud/lib/private/lock/dblockingprovider.php(263): OC\DB\Connection->executeUpdate('UPDATE `*PREFIX...', Array)
#4 [internal function]: OC\Lock\DBLockingProvider->releaseAll()
#5 {main}

Next exception 'Doctrine\DBAL\Driver\PDOException' with message 'SQLSTATE[HY000]: General error: 10 disk I/O error' in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:7 in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php on line 85

---

The kernel doesn't report any disk problems, so the I/O error above looks to be some type of sqlite3 internal problem

**Comment by jejb** [comment]
I think it might be something to do with the sqlite3 memory requirements.  Removing the data directory, restoring from backup, shutting down most of the running services and re-doing the update worked.

**Comment by RealRancor** [comment]
quoting @DeepDiver1975 from https://github.com/owncloud/core/issues/23013

>> Seems like nothing we can do about, right @DeepDiver1975 ?
>>
> no 

Please also just don't delete the issue template and provide the info asked within it in further reports.

Its also really advised to migrate from sqlite to MySQL or PostgreSQL for the reasons described in the documentation.
