### ISSUE TITLE
Missing Centos 6 repositories for 9.X.X

### ISSUE THREAD

**Issue by gmernov** [owncloud/core#23188]
Hi, as long as i see, there's no repository of the line 9.X.X for Centos 6.X. It would be nice be have such in: https://download.owncloud.org/download/repositories/stable/owncloud/

**Comment by LukasReschke** [comment]
cc @jnweiger

**Comment by RealRancor** [comment]
> This is the current list of platforms:
>
>    CenOS 7 (CentOS 6: Files only)

according to:

https://owncloud.org/blog/time-to-upgrade-to-owncloud-9-0/

so there should be at least a repo for CentOS 6 containing owncloud-files

**Comment by adrianvg** [comment]
So what does "CentOS 6: Files only" mean on the above link?
A manual install is required?

**Comment by RealRancor** [comment]
That is referring to that note:

> The owncloud-files package can be installed alone. It has only one packaging logic: obsolete and replace the 8.x owncloud packages. It requires no PHP, database, Apache webserver or other dependencies. An ownCloud server installed only from the owncloud-files package is not directly runnable, unless you made sure all dependencies are in place by hand.

**Comment by adrianvg** [comment]
Ok, thanks.
Let's hope the packager packs version 9 for us CentOS 6-users in a nearby future then. 8-)

**Comment by jnweiger** [comment]
https://download.owncloud.org/download/repositories/stable/owncloud-files/
has the package for CentOS_6

**Comment by RealRancor** [comment]
@jnweiger Honestly, there is something really broken with the communication about such breaking changes (this isn't the first time).

How should a user ever get to this link if this is not clearly communicated?

https://owncloud.org/install/#instructions-server -> Only links to https://download.owncloud.org/download/repositories/stable/owncloud/

https://owncloud.org/changelog -> Only linking to https://download.owncloud.org/download/repositories/9.0/owncloud/ and https://download.owncloud.org/download/repositories/stable/owncloud/

https://doc.owncloud.org/server/9.0/admin_manual/search.html?q=owncloud-files -> No note about "owncloud-files" there

https://owncloud.org/blog/time-to-upgrade-to-owncloud-9-0/ -> Is only talking about a "owncloud-files" package, not about an extra repository.

**Comment by RealRancor** [comment]
Ok, that needs to be corrected:

> https://doc.owncloud.org/server/9.0/admin_manual/search.html?q=owncloud-files -> No note about "owncloud-files" there

This is hidden deep into https://doc.owncloud.org/server/9.0/admin_manual/installation/linux_installation.html

**Comment by jnweiger** [comment]
Both, owncloud and owncloud-files are in the same repo. We should advertise them togeter in one web-page. 

Documenting two links makes it appear as if it were two repos. E.g. users could try to disable one, enable the other and be (again) confused about the result.

**Comment by RealRancor** [comment]
Just as a follow-up from https://github.com/owncloud/owncloud.org/issues/910:

There is now only one repos "owncloud": https://download.owncloud.org/download/repositories/stable/owncloud/ containing both, "owncloud" and "owncloud-files" packages.
