### ISSUE TITLE
File Search not working

### ISSUE THREAD

**Issue by SchroSct** [owncloud/core#23182]
### Steps to reproduce
1. Run owncloud 9.0
2. Search files

### Expected behaviour
Files should be listed.

### Actual behaviour
'Searching other places' and the spinner lasts forever.

### Server configuration
**Operating system**: 
Ubuntu 15.10

**Web server**: 
Apache2 2.4.12

**Database:** 
mysqld Ver 5.6.28

**PHP version:**  
PHP 5.6.11

**ownCloud version:** 
9.0.0 stable

**Updated from an older ownCloud or fresh install:** 
updated from 8.2.2

**Where did you install ownCloud from:** 
owncloud repos

**Signing status (ownCloud 9.0 and above):** 
Integrity passes.

{"reqId":"6WzNqDY3H20uMh+e5u6Y","remoteAddr":"x.x.x.x","app":"PHP","message":"array_slice() expects parameter 1 to be array, null given at \/var\/www\/owncloud\/lib\/private\/search.php#71","level":3,"time":"2016-03-12T16:05:00+00:00"}
{"reqId":"6WzNqDY3H20uMh+e5u6Y","remoteAddr":"x.x.x.x","app":"PHP","message":"array_merge(): Argument #2 is not an array at \/var\/www\/owncloud\/lib\/private\/search.php#72","level":3,"time":"2016-03-12T16:05:00+00:00"}
{"reqId":"uZ8+2iITb5uAOFWgAMJt","remoteAddr":"127.0.0.1","app":"PHP","message":"array_keys() expects parameter 1 to be array, boolean given at \/var\/www\/owncloud\/lib\/private\/group\/manager.php#283","level":3,"time":"2016-03-12T16:05:01+00:00"}
{"reqId":"uZ8+2iITb5uAOFWgAMJt","remoteAddr":"127.0.0.1","app":"PHP","message":"array_map(): Argument #2 should be an array at \/var\/www\/owncloud\/lib\/private\/group\/manager.php#283","level":3,"time":"2016-03-12T16:05:01+00:00"}

**Comment by LukasReschke** [comment]
Which apps do you happen to have installed? Thanks a lot.

**Comment by SchroSct** [comment]
Enabled:
  - activity: 2.2.1
  - bookmarks: 0.666666
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_clipboard: 0.4.2
  - files_external: 0.5.2
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mozilla_sync: 1.4
  - music: 0.3.10
  - notes: 2.0.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - search_lucene: 0.7.0
  - systemtags: 0.2
  - tasks: 0.9.0
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - chat
  - checksums
  - conversations
  - encryption
  - fbsync
  - files_embeddedvideo
  - ocdownloader
  - ocusagecharts
  - shorten
  - user_external
  - user_ldap

**Comment by digsig** [comment]
**same problem. when i disable calendar v1.0 the search works again from me.**
Class 'OC_Calendar_Calendar' not found at /var/www/owncloud/apps/tasks/service/tasksservice.php#112


Steps to reproduce

    Run calendar 1.0   
    Run owncloud 9.0
    Search files

Expected behaviour

Files should be listed.
Actual behaviour

'Searching other places' and the spinner lasts forever.
Server configuration

Operating system:
Debian 8

Web server:
Apache/2.4.10

Database:
mysqld 5.5.47

PHP version:

PHP 5.6.17

ownCloud version:
9.0.0

Updated from an older ownCloud or fresh install:
updated from 8.2.2.2

Where did you install ownCloud from:
owncloud repos

Signing status (ownCloud 9.0 and above):
Integrity passes.

**Comment by PVince81** [comment]
@digsig did you try upgrading the tasks app? From the error message it looks like the tasks app is expecting some old calendar class to exist.

**Comment by SchroSct** [comment]
I had tasks 0.9.0 and calendar 1.0.0 enabled.
When I disabled calendar 1.0.0 alone I did not get search back, when both tasks and calendar are disabled the search works.
If tasks is re-enabled then search fails again.

**Comment by Loki3000** [comment]
Same problem. The bug in lib/private/search.php
```php
$providerResults = $provider->search($query);
```
in some cases 'search' method returns null, so $results becomes null instead of array
```php
 $results = array_merge($results, $slicedResults);
```
as a result, client side gets null instead of valid json and hangs JS error "TypeError: e is null".

The solution is to replace in lib/private/search.php:69
```php
//old one
$providerResults = $provider->search($query);
//new one
if (!$providerResults = $provider->search($query)) continue;
```
after that search works fine.

**Comment by LukasReschke** [comment]
> in some cases 'search' method returns null, so $results becomes null instead of array

They should not return `null`. They should return an empty array as per the PHPDoc. If they return null then they are doing it wrong :wink:

**Comment by Loki3000** [comment]
I thought so, but too lazy to dig deeper :)
But if you need help, I'm ready to investigate quite carefully.

**Comment by PVince81** [comment]
Is this still happening with 9.0.4 ?

**Comment by SchroSct** [comment]
No problems for me anymore.

**Comment by PVince81** [comment]
Thanks
