### ISSUE TITLE
Provisioning API removeFromGroup for group admins

### ISSUE THREAD

**Issue by michag86** [owncloud/core#23180]
Group admins cannot remove themself from a group:
https://github.com/owncloud/core/blob/v9.0.0/apps/provisioning_api/lib/users.php#L450

But why? A group admin can remove everybody from a group that is member of a group he administrates. 

The only case where this should be denied if the group admin removes the user from the last group the user is member of and gives permission to the group admin. At the moment, this is possible and the group admin can make a user inaccessible from itself.

**Comment by PVince81** [comment]
@MTRichards

**Comment by michag86** [comment]
@rullzer What do you think?
I can try to implement the same behaviour like the web user management provides.

**Comment by PVince81** [comment]
From what I saw this is already implemented, there was only a bug in permission checking: https://github.com/owncloud/core/pull/25788
