### ISSUE TITLE
Give DAV-App its own Repository

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#23198]
I think, it would be a good idea, to give the dav-app (CalDAV, CardDAV, WebDAV) introduced with ownCloud 9 a new home. An own Repository. There are many new open issues (according to the Calendar and Contacts Backend) which have no direct connection to the "core".

**Comment by rullzer** [comment]
I don't feel this is a good idea. The new dav app is (and in the future even more) an essential part of core. And we need to make sure it gets tested as often as possible. So all CI should be run. For example all client (including the web UI) use webdav to show the files.

Maybe new labels for the caldav/carddav stuff would be a good idea.

**Comment by aspdye** [comment]
Splitting the label "app:dav" into:

app:dav_caldav
app:dav_carddav
app:dav_webdav

:wink: I understand the point with the CI tests :+1:

**Comment by DeepDiver1975** [comment]
We had long discussions about the location of the DAV app. We keep it in core.
