### ISSUE TITLE
Using directory /var/tmp does not work for shared hosters 

### ISSUE THREAD

**Issue by devlumberjack** [owncloud/core#23195]
### Steps to reproduce
1. Setup owncloud 9 on a shared hoster (e.g. strato.de)
2. Configure (MySQL DB, give admin the password) ... and so on 
> having a full set up owncloud env
3. Login as user (whoever), chosse "calendar app" > try to create a new calender 
4. can not create a new calendar via CalDav Client

### Expected behaviour
a new calendar should be created

### Actual behaviour
nothing
Excerpt from Logfile (all personal data are removed and replaced with xxx)

{"reqId":"xxx@xxxxxxxxxxxxxxxxxxxxxxxxxx","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"opendir(\/var\/tmp\/): failed to open dir: Permission denied at \/mnt\/webc\/a3\/70\/54043970\/htdocs\/xxxx\/cloud\/lib\/private\/tempmanager.php#187","level":3,"time":"2016-03-11T17:21:09+00:00"}

cloud = directory of owncloud intallation

### Server configuration
**Operating system**:
dont know, running it on a shared host, https://www.strato.de/

**Web server:**
dont know, running it on a shared host, https://www.strato.de/

**Database:**
mySQL 5.5.47

**PHP version:**
5.5

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.0 (stable)
$OC_Version = array(9,0,0,19);  // from version.php

**Calendar version:** (see ownCloud apps page)

**Updated from an older ownCloud or fresh install:**
fresh, clean install (setup in new, clean diretory and database)

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

added no apps after the new installation, here is the list

Activity 2.2.1
Collaborative tags 0.2
Comments 0.2
Deleted files 0.8.0
Federation 0.0.4
First Run Wizard 1.1
Gallery 14.5.0
Mail Template Editor 0.1
Notifications 0.2.3
PDF Viewer 0.8
Provisioning API 0.4.1
Share Files 0.9.1
Text Editor 2.1
Update notification 0.1.0
Versions 1.2.0
Video player 0.9.8
Calendar 1.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

no access, I'm using a shared host (www.strato.de)

**The content of config/config.php:**

do not have a own php config, using pre configured config.php from hoster

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
latest Mozilla Firefox

**Operating system:**
Windows 7, latests Patches installed

**CalDAV-clients:**
no, just using Webinterface

#### Web server error log

I do not have access to this log :-(

#### ownCloud log (data/owncloud.log)
```
{"reqId":"xxx@xxxxxxxxxxxxxxxxxxxxxxx","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"opendir(\/var\/tmp\/): failed to open dir: Permission denied at \/mnt\/webc\/a3\/70\/54043970\/htdocs\/cloud\/lib\/private\/tempmanager.php#187","level":3,"time":"2016-03-10T15:50:21+00:00"}
{"reqId":"xxx@xxxxxxxxxxxxxxxxxxxxxxx","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"opendir(\/var\/tmp\/): failed to open dir: Permission denied at \/mnt\/webc\/a3\/70\/54043970\/htdocs\/cloud\/lib\/private\/tempmanager.php#187","level":3,"time":"2016-03-10T15:50:39+00:00"}
{"reqId":"xxx@xxxxxxxxxxxxxxxxxxxxxxx","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"Undefined index: newVersionString at \/mnt\/webc\/a3\/70\/54043970\/htdocs\/cloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-10T15:51:26+00:00"}
{"reqId":"xxx@xxxxxxxxxxxxxxxxxxxxxxx","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"opendir(\/var\/tmp\/): failed to open dir: Permission denied at \/mnt\/webc\/a3\/70\/54043970\/htdocs\/cloud\/lib\/private\/tempmanager.php#187","level":3,"time":"2016-03-10T15:51:30+00:00"}
{"reqId":"xxx@xxxxxxxxxxxxxxxxxxxxxxx","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"opendir(\/var\/tmp\/): failed to open dir: Permission denied at \/mnt\/webc\/a3\/70\/54043970\/htdocs\/cloud\/lib\/private\/tempmanager.php#187","level":3,"time":"2016-03-10T15:51:45+00:00"}
{"reqId":"xxx@xxxxxxxxxxxxxxxxxxxxxxx","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"opendir(\/var\/tmp\/): failed to open dir: Permission denied at \/mnt\/webc\/a3\/70\/54043970\/htdocs\/cloud\/lib\/private\/tempmanager.php#187","level":3,"time":"2016-03-10T15:54:37+00:00"}
{"reqId":"xxx@xxxxxxxxxxxxxxxxxxxxxxx","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"opendir(\/var\/tmp\/): failed to open dir: Permission denied at \/mnt\/webc\/a3\/70\/54043970\/htdocs\/cloud\/lib\/private\/tempmanager.php#187","level":3,"time":"2016-03-10T15:55:14+00:00"}
{"reqId":"xxx@xxxxxxxxxxxxxxxxxxxxxxx","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"opendir(\/var\/tmp\/): failed to open dir: Permission denied at \/mnt\/webc\/a3\/70\/54043970\/htdocs\/cloud\/lib\/private\/tempmanager.php#187","level":3,"time":"2016-03-11T17:18:53+00:00"}
{"reqId":"xxx@xxxxxxxxxxxxxxxxxxxxxxx","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"opendir(\/var\/tmp\/): failed to open dir: Permission denied at \/mnt\/webc\/a3\/70\/54043970\/htdocs\/cloud\/lib\/private\/tempmanager.php#187","level":3,"time":"2016-03-11T17:19:17+00:00"}
{"reqId":"xxx@xxxxxxxxxxxxxxxxxxxxxxx","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"opendir(\/var\/tmp\/): failed to open dir: Permission denied at \/mnt\/webc\/a3\/70\/54043970\/htdocs\/cloud\/lib\/private\/tempmanager.php#187","level":3,"time":"2016-03-11T17:19:51+00:00"}
{"reqId":"xxx@xxxxxxxxxxxxxxxxxxxxxxx","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"opendir(\/var\/tmp\/): failed to open dir: Permission denied at \/mnt\/webc\/a3\/70\/54043970\/htdocs\/cloud\/lib\/private\/tempmanager.php#187","level":3,"time":"2016-03-11T17:19:58+00:00"}
{"reqId":"xxx@xxxxxxxxxxxxxxxxxxxxxxx","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"opendir(\/var\/tmp\/): failed to open dir: Permission denied at \/mnt\/webc\/a3\/70\/54043970\/htdocs\/cloud\/lib\/private\/tempmanager.php#187","level":3,"time":"2016-03-11T17:21:09+00:00"} 

#### Browser log
```
seems to be an error on the server, so I don't add the browser log.

Hint: I already created an issue for the calendar app (https://github.com/owncloud/calendar/issues/320), but I was told to create a new issue here.

**Comment by RealRancor** [comment]
@devlumberjack As written in https://github.com/owncloud/calendar/issues/320:

> On such limited / restricted environments you can specify:
> 
> https://github.com/owncloud/core/blob/v9.0.0/config/config.sample.php#L1041-L1049
> 
> I think there is no need to create a new issue in core as a config possibility to specify the tmp directory already exists.

**Comment by devlumberjack** [comment]
Thanks for the information and the link! I will try that. I think you can close the Issue.

Hint: I'm running owncloud 8.1.7 on such limited / restricted environment ...and had not to specify the temp directory. I will spread the info.

**Comment by RealRancor** [comment]
Hi,

i think you can keep this open until you have tested the config switch and if it works then you can close it on your own by hitting the "close" button below the comment field.

**Comment by devlumberjack** [comment]
With the given config parameter it works! Issue can be closed. Thanks for the help.
