### ISSUE TITLE
Ubuntu 12.04, 14.04 and 15.10 missing oC 8.2.3 packages

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#23196]
Currently only 14.10 and 15.04 have 8.2.3, the others have 8.2.2

https://download.owncloud.org/download/repositories/8.2/owncloud/

**Comment by tflidd** [comment]
There are two repos for Ubuntu:
https://download.owncloud.org/download/repositories/8.2/Ubuntu_14.04/
https://download.owncloud.org/download/repositories/8.2/xUbuntu_14.04/

the xUbuntu-versions are still on 8.2.2.

**Comment by PVince81** [comment]
@jnweiger please have a look

**Comment by jnweiger** [comment]
Redeployed packages into the mirrors. https://download.owncloud.org/download/repositories/8.2/owncloud/ now shows all with 8.2.3

The xUbuntu* are symbolic links to their normal Ubuntu* siblings. There is no more chance that they differ.

Thanks for the notice!
