### ISSUE TITLE
Name of shared external storage cannot be reused

### ISSUE THREAD

**Issue by Larx** [owncloud/core#23206]
### Steps to reproduce
1. Add an external storage folder, share it to other users, and then remove it again. On the surface, there now is no trace left of this folder.
2. Try to add another (or re-add the same) external storage folder with the same name and share it to other users.
3. In the other user's owncloud view, the folder appears with appended " (1)".

### Expected behaviour
If the shared folder is removed, it should be removed without any trace.
The newly shared folder should appear with the same name as it was declared by the user who shared it, even if there once has been a shared folder with the same name.

### Actual behaviour
The shared folder appears with appended " (1)" in the other users view. The "oc_appconfig" table seems to get filled up with the names of older shared external folders (appid "files_external"). (In fact, in my case it is so filled up during the lifetime of my oc installation that I cannot say if these are only external/shared or all external folders).

### Server configuration
**Operating system**:
Linux, openSUSE Tumbleweed
**Web server:**
Apache 2.4
**Database:**
MariaDB
**PHP version:**
5.6.18
**ownCloud version:** (see ownCloud admin page)
8.2.1
**Updated from an older ownCloud or fresh install:**
Updated
**Where did you install ownCloud from:**
Tarballs from homepage

**Comment by PVince81** [comment]
@Larx mind posting a few of those `oc_appconfig` entries ? AFAIK external storage shouldn't write anything there...

Please also try upgrading to 8.2.3, a lot of issues have been fixed since.

**Comment by PVince81** [comment]
@Larx also check "oc_storages" after deleting an external storage, maybe it still has a trace of some sorts.

**Comment by Larx** [comment]
![screenshot_20160314_190247](https://cloud.githubusercontent.com/assets/3582007/13754512/96b40f58-ea17-11e5-85ce-2b9473039e13.png)
I simply took a phpMyAdmin screenshot as I didn't know how to post those entries best. There are lots of lines like that in my oc_appconfig table, some are real old, others quite new.

**Comment by Larx** [comment]
I just looked at oc_storages. That's really a mess! It contains really old entries, lots of them.

**Comment by PVince81** [comment]
Ah right, these are the mtime of latest etag propagation.

You're right that there should be cleant up properly.

However this is unlikely the reason of the behavior you describe.

**Comment by PVince81** [comment]
My steps:

1. Login as admin
1. Create two users "user1" and "user2"
1. In the admin page, setup a SMB external storage with mount point "/smb", and select "user1" in the applicable field
1. Login as "user1"
1. Create a folder "/smb/extshared"
1. Login as "user2"
1. See that the folder "extshared" was received
1. Login as "admin"
1. Remove the SMB external storage
1. Recreate the same SMB storage under "/smb", again with "user1" as applicable
1. Login as "user1"
1. Share "/smb/extshared" with "user2"
1. Login as "user2"
1. Check folder name => it's "extshared"

Works for me in v8.2.3.

Maybe try again with that version ?

**Comment by Larx** [comment]
As the 9.0 upgrade messed up my setup and database, which seemingly was full of old cruft, I took the chance and set up everything anew. The leftover entries in the database where from external storage shared to other users, from my analysis. However, I will reopen the subject if it occurs again in 9.0.
