### ISSUE TITLE
.htaccess RewriteRule brakes non-standard alias

### ISSUE THREAD

**Issue by t0mcat1337** [owncloud/core#23207]
### Steps to reproduce
1. Install owncloud9 (In Ubuntu installed under /var/www/owncloud, the default DocumentRoot here is /var/www/html)
2. In Apache config change Alias from 'Alias /owncloud "/var/www/owncloud"' to 'Alias /somethingelse "/var/www/owncloud"'
3. In owncloud config insert "'overwritewebroot' => '/somethingelse',"
3. Open Browser with URL http://servername/somethingelse

### Expected behaviour
Owncloud should open under /somethingelse

### Actual behaviour
Apache gives a "404 Not Found - The requested URL /var/www/owncloud/index.php was not found on this server.", ignoring the Alias /somethingelse

### Server configuration
**Operating system**:
Ubuntu 15.04 LTS

**Web server:**
Apache 2.4.10

**Database:**
MySQL 5.6.28

**PHP version:**
5.6.4

**ownCloud version:** (see ownCloud admin page)
9.0

**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**
Official Package repository (http://download.owncloud.org/download/repositories/stable/xUbuntu_15.10/)

Figured out, that this RewriteRule in /var/www/owncloud/.htaccess seems to be responsible:

RewriteRule .* index.php [PT,E=PATH_INFO:$1]

When commented out, everything works as expected...

Here the contents of apaches logs with mod_rewrite trace3 enabled:

access.log
`111.222.333.444 - - [14/Mar/2016:07:38:57 +0100] "GET /somethingelse/ HTTP/1.1" 404 527 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0"`

error.log
`[Mon Mar 14 07:38:57.593998 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] strip per-dir prefix: /var/www/owncloud/ -> 
[Mon Mar 14 07:38:57.594058 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] applying pattern '.*' to uri ''
[Mon Mar 14 07:38:57.594086 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] strip per-dir prefix: /var/www/owncloud/ -> 
[Mon Mar 14 07:38:57.594132 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] applying pattern '^\\.well-known/host-meta' to uri ''
[Mon Mar 14 07:38:57.594149 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] strip per-dir prefix: /var/www/owncloud/ -> 
[Mon Mar 14 07:38:57.594164 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] applying pattern '^\\.well-known/host-meta\\.json' to uri ''
[Mon Mar 14 07:38:57.594180 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] strip per-dir prefix: /var/www/owncloud/ -> 
[Mon Mar 14 07:38:57.594196 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] applying pattern '^\\.well-known/carddav' to uri ''
[Mon Mar 14 07:38:57.594212 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] strip per-dir prefix: /var/www/owncloud/ -> 
[Mon Mar 14 07:38:57.594228 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] applying pattern '^\\.well-known/caldav' to uri ''
[Mon Mar 14 07:38:57.594244 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] strip per-dir prefix: /var/www/owncloud/ -> 
[Mon Mar 14 07:38:57.594259 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] applying pattern '^remote/(.*)' to uri ''
[Mon Mar 14 07:38:57.594275 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] strip per-dir prefix: /var/www/owncloud/ -> 
[Mon Mar 14 07:38:57.594291 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] applying pattern '^(build|tests|config|lib|3rdparty|templates)/.*' to uri ''
[Mon Mar 14 07:38:57.594310 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] strip per-dir prefix: /var/www/owncloud/ -> 
[Mon Mar 14 07:38:57.594326 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] applying pattern '^(\\.|autotest|occ|issue|indie|db_|console).*' to uri ''
[Mon Mar 14 07:38:57.594343 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] strip per-dir prefix: /var/www/owncloud/ -> 
[Mon Mar 14 07:38:57.594359 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] applying pattern '^core/js/oc.js$' to uri ''
[Mon Mar 14 07:38:57.594387 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] strip per-dir prefix: /var/www/owncloud/ -> 
[Mon Mar 14 07:38:57.594405 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] applying pattern '^core/preview.png$' to uri ''
[Mon Mar 14 07:38:57.594421 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] strip per-dir prefix: /var/www/owncloud/ -> 
[Mon Mar 14 07:38:57.594436 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] applying pattern '.*' to uri ''
[Mon Mar 14 07:38:57.594475 2016] [rewrite:trace2] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] rewrite '' -> 'index.php'
[Mon Mar 14 07:38:57.594494 2016] [rewrite:trace3] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] add per-dir prefix: index.php -> /var/www/owncloud/index.php
[Mon Mar 14 07:38:57.594512 2016] [rewrite:trace2] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] forcing '/var/www/owncloud/index.php' to get passed through to next API URI-to-filename handler
[Mon Mar 14 07:38:57.594529 2016] [rewrite:trace1] [pid 31265] mod_rewrite.c(475): [client 111.222.333.444:53744] 111.222.333.444 - - [servername/sid#7f7337825530][rid#7f731e8d00a0/initial] [perdir /var/www/owncloud/] internal redirect with /var/www/owncloud/index.php [INTERNAL REDIRECT]`

**Comment by RealRancor** [comment]
Can you try the patch in https://github.com/owncloud/core/pull/23029

**Comment by t0mcat1337** [comment]
Just looked at #23029 and I'm a little confused... In there, the .htaccess is modified (deleted RewriteRule .* ...) and  lib/private/setup.php (added RewriteBase...)
Then I looked at my installation and noticed, that the patch seems to be applied for lib/private/setup.php (the RewriteBase is included), but my .htaccess still includes the "RewriteRule .* .." despite it was removed in the patch...
