### ISSUE TITLE
files:scan normalizes unicode decomposed characters in filename before saving into files cache

### ISSUE THREAD

**Issue by pellaeon** [owncloud/core#23209]
### Steps to reproduce
1. Create a file on disk (with `touch` for example) with decomposed unicode characters in its name, for example these bytes:
```
00000000: 3038 2e46 7574 6172 6920 6465 2050 6172  08.Futari de Par
00000010: 6973 206e 6920 696b 6fcc 842e 6d70 330a  is ni iko...mp3.
```
`6fcc84` is the decomposition of `c58d` .
2. During `files:scan`, the filename is `normalizeUnicode()`'d at `cache->insert()` or `cache->update()`. Therefore `6fcc84` is replaced with `c58d` and stored into the files cache table.
3. When trying to access the file, `path` from the database is fed directly into `file_exists()`, `file_exists()` reports no such file.

### Expected behaviour
File is accessed successfully.

### Actual behaviour
ownCloud reports file not found.

### Server configuration
**Operating system**: FreeBSD 10.1-RELEASE-p15, ZFS

**Web server:** Apache 2.4

**Database:** Ver 15.1 Distrib 5.5.44-MariaDB

**PHP version:** PHP 5.6.14

**ownCloud version:** master `5862a06`

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** git

I read the discussions at #2377 , we don't support Mac OS X, why do we still normalize filenames for database?

**Comment by PVince81** [comment]
> I read the discussions at #2377 , we don't support Mac OS X, why do we still normalize filenames for database?

@pellaeon the situation might happen with external storages.

See also https://github.com/owncloud/core/issues/21365

**Comment by PVince81** [comment]
Due to https://github.com/owncloud/core/issues/21365 we had discussions about removing normalization, but from what I understood, Webdav and/or URLs require the normalized format to be able to be used at all and wouldn't support Mac's NFD format. This would mess up ownCloud.

**Comment by PVince81** [comment]
The use case of having such files directly in the data directory is not supported.

As for supporting NFD file names on external storages, 9.1 comes with a new advanced mount option to add compatibility.
