### ISSUE TITLE
Owncloud 9.0 does not allow to share files from ext. Dropbox folder

### ISSUE THREAD

**Issue by RosinSmoke** [owncloud/core#23210]
### Steps to reproduce
1. Enable server-side encryption
2. Connect external Dropbox storage
3. Place any file in storage,in my case, ODT file I wanted to collaboratively edit with Documents plugin. Files can be either uploaded directly or moved from other owncloud file tree location.
4. Try to share file with other user

### Expected behaviour
Sharing as it normally happens on local storage
[expected.png](https://raw.githubusercontent.com/RosinSmoke/content/master/expected.png)

### Actual behaviour
Textbox for username or group is gray with written "Re-sharing not allowed" even if it is allowed.
If file was previously on local storage and shared with other user, and even cooperative edit worked, moving it to DB location causes other user's Documents mode to see 2 files with the same name, but none of them is accessible, just white screen for 2 seconds and return to main Documents screen. In Files mode, however, other user still can see file, comment it, download and he is seen in list of users who I shared files with.
[actual.png](https://raw.githubusercontent.com/RosinSmoke/content/master/actual.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
PHP 5.5.9-1ubuntu4.14

**ownCloud version:** (see ownCloud admin page)
9.0

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
Repository marked as "stable" from installation instruction

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```

Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - dav: 0.1.5
  - documents: 0.12.0
  - encryption: 1.2.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - music: 0.3.10
  - news: 7.1.2
  - notifications: 0.2.3
  - ownnote: 1.07
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - federation
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocp18lf0efqq",
        "passwordsalt": "[removed]",
        "secret": "[removed]",
        "trusted_domains": [
            "[mydomain]"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/[mydomain]\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "database_duh",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "root",
        "dbpassword": "[removed]",
        "logtimezone": "UTC",
        "installed": true
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Only Dropbox, mentioned above. DB storage folder is mounted to owncloud's root folder.

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration
**Browser:**
FF 44.0.2

**Operating system:**
Windows 10

#### ownCloud log (data/owncloud.log)
[http://vpaste.net/cg1sC](http://vpaste.net/cg1sC)

#### Browser log
```
Need to get another person to do this, will be added later if needed
```

**Comment by LukasReschke** [comment]
@owncloud/sharing Expected behaviour or not?

**Comment by RosinSmoke** [comment]
@LukasReschke
Expected behaviour was editable text field where I usually enter someone's username, and the actual behavior is that text field is blocked. 
I've added 2 screenshots to the description to the "expected" and "actual" blocks

**Comment by rullzer** [comment]
Mmmm I see no reason (sharing wise) why that would not work.

@icewind1991 you touched the sharing permissions for external storages in 9.0 right? Anything particular we need to check here?

**Comment by PVince81** [comment]
Since 9.0 sharing is disabled by default for newly created external storages.

@RosinSmoke please check your Dropbox mount, there is a cog icon at the end of the row. In that dropdown, enable sharing.

If that still doesn't work, please reopen.

**Comment by RosinSmoke** [comment]
@PVince81
I still don't quite get where is the "cog". 
All clickable elements, opening drop-down lists, are [three-dot button](http://puu.sh/nHBv7/eb49dfa758.png), [user menu](https://puu.sh/nHBz3/939e4fb684.png), where I could get to [sharing options](http://puu.sh/nHBGF/4f7e85abbe.png) and, obviously, the app selector on the left part of upper toolbar, but still no one of them can change anything. I do miss something obvious, don't I?

**Comment by PVince81** [comment]
@RosinSmoke the cog is in the admin page or personal page, the place where you originally configured the Dropbox mount. The section is called "External Storages".

**Comment by RosinSmoke** [comment]
@PVince81
Oh, that's what you've told me about ( [screenshot](https://raw.githubusercontent.com/RosinSmoke/content/master/finally.png) ).
Yes, this worked, now sharing is available. Thank you very much!

Couple more things, though:

 - I failed to find it in 9.0 installation manual, can I ask your team to add the line to this guide, that explicitly mentions that one should enable sharing on ext. storages manually?

 - When I drag-n-drop shared .odt document to the ext.storage from local folder, the Documents app from other user account starts to see two similar tiles with its name. Both are clickable for online edit and lead to the same document, but it's just doubled. After second user edits it and closes the document, another attempt to do this shows error "_Failed to load this document. Please check if it can be opened with an external odt editor. This might also mean it has been unshared or deleted recently._" . Also file is seen by second user both from the current and the previous folder in the File mode. Uneditable here too. If after these actions a user, who created the file and moved it, tries to open it, he/she gets the same error, so, I guess, second user could not properly save it. The broken document also cannot be deleted from the Owncloud side, I just get the alert "_Error deleting <filename>_" so I have to go to Dropbox and delete it from their interface.
 - If I, as 1st user, move unshared .odt file from local storage (where second user cannot see it) to Dropbox ext. storage, second user can see the unshared file and edit it even though the 1st user did not manually share it with 2nd. I guess then, 2nd user's account is either able to cache other users' files, but does not display them in web interface, or Owncloud leaves the link to the file in ext. storage so that Documents app still could see it. Is this as it should be? File again gets broken after first edit by 2nd user.
 - If I, as 1st user, create unshared .odt file in local storage with Documents app (I could not find how to create it anywhere else with this tool), move it to Dropbox storage and share it before 2nd user takes any action, 2nd user again sees 2 files (in local storage and in Dropbox storage) and again is able to break the file after first edit via Documents tool.
 - If I, as 1st user, upload .odt file straight to the Dropbox storage, 2nd user again can see it too even if I did not share it with him. I guess, viewing rights are given to anyone who enters the Dropbox storage. Is this normal behavior? Then, after 2nd user edits this file, it gets broken again.
 - If I, as 1st user, upload .odt file straight to the Dropbox storage, then share it to 2nd user before 2nd user edits it, and then 2nd user again sees it twice, in the root folder of local storage and in the Dropbox folder. File gets broken after 1st edit by 2nd user.

So, I guess, I should rather open another issue with the last bunch of questions? If the file lays in the local storage it's editable as expected and does not get broken, but there is certainly something strange with the moving files to the Dropbox storage.

**Comment by PVince81** [comment]
@RosinSmoke please make separate tickets for separate issues.

Regarding documentation, @carlaschroder we should mention that sharing is disabled by default for external storages and that it can be enabled in the mount options (cog icon).

**Comment by carlaschroder** [comment]
This stuff is documented. However, buttons that appear only on mouseover aren't a good idea IMO. They don't save space, they just create confusion. I am going to open a ticket.

**Comment by PVince81** [comment]
It's not mouseover, you have to click on the cog. But you're right that it's a bit too hidden... that ext storage UI needs a good revamping.

**Comment by carlaschroder** [comment]
https://github.com/owncloud/core/issues/23316

**Comment by RosinSmoke** [comment]
[Doubled files 23295](https://github.com/owncloud/core/issues/23295)
