### ISSUE TITLE
Exclude Apps from beeing processed via the AssetPipeline

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#23219]
**This is a question / feature request for oC 9.x:**

Is there a possibility already existant or could it be implemented, that an app which has problems with an enabled asset pipeline (config parameter ``asset-pipeline.enabled true``) could be excluded from this functionality?

**Background:**
The current Calendar App (v 1.0) can not be used if asset-pipeline.enabled is activated due to an dependency to a 3rd party component which fails when asset-pipelining is enabled. 
But disabling the config parameter completely for all apps just beacuse one problematic app is not a good behaviour and counteracts the idea behind.

**Benefit:**
If this would be possible, we just can "tag" the problematic app (however done) and go for the fix without changing the config parameter. When the fix is implemented, untagging reenables the use of asset-pipelining for this particular app.

**Comment by PVince81** [comment]
@DeepDiver1975

**Comment by mmattel** [comment]
Seems that not only calendar has/had its challenges with:
https://github.com/owncloud/tasks/issues/290
https://github.com/owncloud/music/issues/434
(maybe more)

A exclusion based on "tagging" the App would really help (if possible of course)...

**Comment by mmattel** [comment]
Any ideas on that?

**Comment by mmattel** [comment]
No comments?

**Comment by DeepDiver1975** [comment]
Instead of adding more and more config options an workarounds I suggest we work on the explicit error.

**Comment by mmattel** [comment]
You are absolutely right an I can fully underline your statement !

As you may have read, not only calender is affected by this error. It is now taking a while to create a fix and in addition we have to deal with a 3rd party code causing the problem. In the meanwhile, asset pipeliing must be disabled for ALL apps not only the errous one.

My idea was just to ask if there could be a way found to get around this "all or nothing" behaviour, as asset pipelining has positive impacts on performance and data quantity transferred.

**Comment by PVince81** [comment]
Would this update of JSqueeze fix it ? https://github.com/owncloud/3rdparty/pull/266
