### ISSUE TITLE
Upload files with mtime in the far future crashes request and file scan

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#23228]
- having a file with a mtime in 2106 (yes - that was the mtime)
- upload this via ownCloud client
- the client transfers the mtime in ISO8601 I guess
- the file is properly placed in the data dir with the correct (2106) time stamp
- insert into file cache fails and all subsequent files:scans also throw errors like this:

```
An exception occurred while executing:
UPDATE `oc_filecache` SET `mtime` = ?, `etag` = ?, `storage_mtime`=? WHERE (`mtime` <> ? OR `etag` <> ? OR `storage_mtime` <> `?` OR fileid` = ? ' with params [4294967295, \"9bf156220dedae324370f6189f7dfe62\", 4294967295, 4294967295, \"9bf156220dedae324370f6189f7dfe62\", 4294967295, \"3739252\"]:
SQLSTATE[22003]: Number out of range: 1264 Out of range value for column 'mtime' at row 1
```

cc @DeepDiver1975 @nickvergessen @PVince81 

Workaround: run a `touch FILENAME` to adjust the time to a more recent date

**Comment by MorrisJobke** [comment]
also noticed together with @msrex

**Comment by PVince81** [comment]
We gotta be ready for the FUTURE!

**Comment by nickvergessen** [comment]
2038+ int limit...

Being ready means transform the column either to bigint or date. A changing a column (or two since storage_mtime and mtime suffer from it) is going to kill the update...

**Comment by MorrisJobke** [comment]
> Being ready means transform the column either to bigint or date.

Sure, but just crashing because of this ancient time format is kind of *meh*.

**Comment by PVince81** [comment]
Yeah, should probably handle errors better and then rollback the data when needed.

**Comment by MorrisJobke** [comment]
> Yeah, should probably handle errors better and then rollback the data when needed.

Or then does a hard cut on the timestamp and store it as "now".

**Comment by PVince81** [comment]
@guruz would this mess up with the client if we forced the data as "now" ?

**Comment by MorrisJobke** [comment]
> @guruz would this mess up with the client if we forced the data as "now" ?

I think we then need to also change the etag after the response is send again or am I wrong?

**Comment by nickvergessen** [comment]
Since this happens on the first write, there is no old etag?

**Comment by guruz** [comment]
Indeed if it is the first upload then there was no ETag anyway, so having a different mtime should be totally OK. The client (and other clients) will from then on use the mtime..

FYI @ogoffart

**Comment by PVince81** [comment]
Need to make the code and DB future-proof at some point.
