### ISSUE TITLE
Owncloud 8.2.2, 9.0.0 Login problem on php 7 with Memcache session storage

### ISSUE THREAD

**Issue by KuroNeko-san** [owncloud/core#23220]
======================

### First of all:
Thanks to all developers of this great product.
And sorry for my english, it is not my native language.

======================

### Steps to reproduce
1. log out from owncloud
2. set session.save_handler = memcache and configure server adress session.save_path = "10.10.96.2:11211" in php.ini
3. try to login with your username and password

### Expected behaviour
Redirect to file list

### Actual behaviour
Login page refreshes itself without any error.
In /owncloud/data/owncloud.log appears error about session_regenerate_id()

### Server configuration
**Operating system**:
Linux srvwww 2.6.32-573.8.1.el6.x86_64 #1 SMP Tue Nov 10 18:01:38 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
CentOS release 6.7 (Final)

**Web server:**
nginx version: nginx/1.8.0
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC)
built with OpenSSL 1.0.1e-fips 11 Feb 2013
TLS SNI support enabled

**Database:**
mysql  Ver 14.14 Distrib 5.5.44, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP 7.0.4 (cli) (built: Mar  2 2016 17:21:37) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

**ownCloud version:** (see ownCloud admin page)
8.2.2, 9.0.0

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
https://download.owncloud.org/community/owncloud-8.2.2.zip
https://download.owncloud.org/community/owncloud-9.0.0.zip

**Signing status (ownCloud 9.0 and above):**
cannot get withowt login

**List of activated apps:**
default

**The content of config/config.php:**
```
$CONFIG = array (
  'instanceid' => '======some letters and digits======',
  'passwordsalt' => '======some letters and digits======',
  'secret' => '======some letters and digits======',
  'trusted_domains' => 
  array (
    0 => 'myownsite.com',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://myownsite.com',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => 'owncloud',
  'dbhost' => '10.10.96.7',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owc',
  'dbpassword' => '======some letters and digits======',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcached_servers' => 
  array (
    0 => 
    array (
      0 => '10.10.96.2',
      1 => 11211,
    ),
  ),
);
```
**Are you using external storage, if yes which one:** local/smb/sftp/...
no and local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
FF 44.0.2
Google Chrome 48.0.2564.116

**Operating system:**
Windows 7 x64

#### Web server error log
nginx and php-fpm no produce any logs

#### ownCloud log (data/owncloud.log)
```
{"reqId":"pJvBA35rMgO7He91kLh\/","remoteAddr":"10.10.96.11","app":"PHP","message":"session_regenerate_id(): Failed to create(read) session ID: memcache (path: 10.10.96.2:11211) at \/var\/www\/html\/owncloud\/lib\/private\/user.php#247","level":3,"time":"2016-03-14T11:06:40+00:00"}
```

#### Browser log
no relevant logs in console

======================

### Possible reason:
https://bugs.php.net/bug.php?id=71187

======================

**Comment by PVince81** [comment]
@LukasReschke for session stuff

**Comment by LukasReschke** [comment]
@KuroNeko-san Can you try the patch from https://github.com/php-memcached-dev/php-memcached/pull/164? THX.

**Comment by KuroNeko-san** [comment]
@LukasReschke I'm using php-memcache instead of php-memcache**d**
This patch not for me, i think.
```
# rpm -qa | grep memcache
php70-php-pecl-memcache-3.0.9-0.2.20151130gitfdbd46b.el6.remi.x86_64
memcached-1.4.22-1.el6.remi.x86_64
```

**Comment by PVince81** [comment]
Please try again with 9.1.0beta2 and update php-memcached and PHP 7.
There were many fixes related to PHP 7.

If the problem persists, please reopen.
