### ISSUE TITLE
files:scan not available in maintenance mode

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#23227]
- enable maintenance mode
- run `./occ files:scan`
- actual: command is not available
- expected: files:scan runs

ownCloud 8.2.2

noticed together with @msrex 

This is because only some apps are loaded in maintenance mode. Could the files app be added to the list of apps that are loaded? cc @DeepDiver1975 @LukasReschke

**Comment by PVince81** [comment]
files:scan is available in single user mode, admins should use that instead
