### ISSUE TITLE
Investigating Same-site Cookies

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#23249]
Ref https://tools.ietf.org/html/draft-west-first-party-cookies-06 and https://twitter.com/mikewest/status/709676633712676864

**Comment by LukasReschke** [comment]
This is the problematic part. Mhm…

> 5.2.  Top-level Navigations
>
>   Setting the "SameSite" attribute in "strict" mode provides robust
   defense in depth against CSRF attacks, but has the potential to
   confuse users unless sites' developers carefully ensure that their
   session management systems deal reasonably well with top-level
   navigations.
>
>   Consider the scenario in which a user reads their email at MegaCorp
   Inc's webmail provider "https://example.com/".  They might expect
   that clicking on an emailed link to "https://projects.com/secret/
   project" would show them the secret project that they're authorized
   to see, but if "projects.com" has marked their session cookies as
   "SameSite", then this cross-site navigation won't send them along
   with the request. "projects.com" will render a 404 error to avoid
   leaking secret information, and the user will be quite confused.
>
>   Developers can avoid this confusion by adopting a session management
>   system that relies on not one, but two cookies: one conceptualy
>   granting "read" access, another granting "write" access.  The latter
>   could be marked as "SameSite", and its absence would provide a
>   reauthentication step before executing any non-idempotent action.
>   The former could drop the "SameSite" attribute entirely, or choose
>   the "Lax" version of enforcement, in order to allow users access to
>   data via top-level navigation.

**Comment by PVince81** [comment]
@Peter-Prochaska
