### ISSUE TITLE
Viewing the Admin page modifies external mount points

### ISSUE THREAD

**Issue by qwertymodo** [owncloud/core#23246]
### Steps to reproduce
1. Create an external mount point to a user's files root using occ files_external:import /path/to/mount.json on the mount.json file below
2. Open the Admin page in the Web GUI

mount.json:

---

```
{
    "user": {
        "user1": {
            "\/$user\/files\/": {
                "id": 1,
                "backend": "local",
                "authMechanism": "null::null",
                "options": {
                    "datadir": "\/mnt\/home\/user1"
                },
                "priority": 150,
                "mountOptions": {
                    "encrypt": false,
                    "previews": true,
                    "filesystem_check_changes": 1
                }
            }
        },
        "user2": {
            "\/$user\/files\/": {
                "id": 2,
                "backend": "local",
                "authMechanism": "null::null",
                "options": {
                    "datadir": "\/mnt\/home\/user2"
                },
                "priority": 150,
                "mountOptions": {
                    "encrypt": false,
                    "previews": true,
                    "filesystem_check_changes": 1
                }
            }
        }
    }
}
```

---
### Expected behaviour

Files should remain mounted as configured
### Actual behaviour

The mount works properly until the Admin page is opened.  When you open the Admin page, the mount gets renamed "Local" and upon returning to the file view, the root of the files listing now contains a single directory named "Local" and all of the files that used to be at the root are now inside that directory.  The relevant database changes seem to be oc_external_mounts.mount_point and oc_mounts.mount_point.  Changing these fields from /username/files/Local/ back to /username/files/ (oc_mounts) and /Local to / (oc_external_mounts) fixes the issue, but it occurs again every time you open the Admin page.
### Server configuration

**Operating system**:
FreeNAS (BSD jail)

**Web server:**
nginx

**Database:**
MySQL

**PHP version:**
5.6.19

**ownCloud version:** (see ownCloud admin page)
9.0.0 (stable)

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
Official download page

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
- activity: 2.2.1
- comments: 0.2
- dav: 0.1.5
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_external: 0.5.2
- files_mv: 0.8.2
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0

**The content of config/config.php:**
    {
        "system": {
            "memcache.local": "\OC\Memcache\APCu",
            "memcache.locking": "\OC\Memcache\Redis",
            "redis": {
                "host": "\/var\/run\/redis\/redis.sock",
                "port": 0,
                "timeout": 0
            },
            "instanceid": "ocrnlx64nnw4",
            "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
            "secret": "**_REMOVED SENSITIVE VALUE**_",
            "trusted_domains": [
                "**_REMOVED LOCAL IP**_",
                "**_REMOVED PUBLIC SERVER NAME**_"
            ],
            "datadirectory": "\/mnt\/owncloud",
            "overwrite.cli.url": "http:\/\/**_REMOVED LOCAL IP**_",
            "dbtype": "mysql",
            "version": "9.0.0.19",
            "dbname": "owncloud",
            "dbhost": "localhost:\/var\/run\/mysql\/mysql.sock",
            "dbtableprefix": "oc_",
            "dbuser": "**_REMOVED SENSITIVE VALUE**_",
            "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
            "logtimezone": "UTC",
            "installed": true
        }
    }

**Are you using external storage, if yes which one:
Local

**Are you using encryption:** 
No

**Are you using an external user-backend, if yes which one:
No
### Client configuration

**Browser:**
Chrome

**Operating system:**
Windows
#### Web server error log

None
#### ownCloud log (data/owncloud.log)

{"reqId":"CP9f5zjgEhbQghfOmabZ","remoteAddr":"**_REMOVED LOCAL IP**_","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-03-15T00:06:11+00:00"}

(The above line is repeated multiple times)

**Comment by LukasReschke** [comment]
@icewind1991 @Xenopathic Any ideas?

**Comment by Xenopathic** [comment]
So the external storages JS notices that the 'Mountpoint' field is empty, since the leading `/$user/files/` bit is removed when passing it around. It then tries to auto-fill that with the backend name, in this case Local. This in turn triggers an autosave, overwriting the mountpoint in the DB.

The problem stems from the fact that this usage of external storages was never really supported - we never documented this usage, and while it worked in most cases before it now broke because we weren't expecting it. If we want to allow users to mount external storages over their entire home directory (as is being done here), we should always display the leading '/' in the external storages GUI (prepending one if there isn't one already), so that this interaction is clear. The result of this would be that a storage mounted at 'foobar' before now appears as '/foobar', etc, which is probably OK for the UX side of things. Then a simple '/' in the mount point field mounts an external storage as described here, over the entire home directory.

Thoughts @icewind1991 @PVince81 ?

**Comment by Xenopathic** [comment]
Also, removing sev2-high and milestone since this was never supported usage.

**Comment by Chris611** [comment]
Will this ever be fixed?

**Comment by PVince81** [comment]
Setting "/" as mount point is not officially supported / tested.

Linked to ticket that would make it possible: https://github.com/owncloud/core/issues/13408
