### ISSUE TITLE
Antivirus app disappeared from app list in owncloud 9.0

### ISSUE THREAD

**Issue by arjanvs** [owncloud/core#23242]
Perhaps this is redundant with:
- https://github.com/owncloud/files_antivirus/issues/95

### Steps to reproduce
1. Install owncloud 9.0
2. Check webinterface apps

### Expected behaviour
Expected to see antivirus to link with clamav

### Actual behaviour
Nothing there, hence no virus protection

### Server configuration
GNU/linux Debian 8.0

**Comment by RealRancor** [comment]
@arjanvs https://apps.owncloud.com/content/show.php/Antivirus?content=157439 shows you that files_antivirus is not marked as compatible with oC9

**Comment by arjanvs** [comment]
@RealRancor if you are going by the book, you are correct

Nevertheless, according to documentation:
- https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/antivirus_configuration.html

This should work.

Depending on the view of owncloud project concerning IT-security, the following solutions are possible:
- If antivirus is important, it would be benificial to fix the antivirus app
- If antivirus is not important, delete the part about antivirus in the documentation

**Comment by RealRancor** [comment]
> If antivirus is important, it would be benificial to fix the antivirus app

This should be reported here: https://github.com/owncloud/files_antivirus/issues/

> If antivirus is not important, delete the part about antivirus in the documentation

This should be reported here: https://github.com/owncloud/documentation/issues

**Comment by arjanvs** [comment]
Nevertheless, I think a decision should be taken about the importance of antivirus. Definitely if a major release is about to be released.

**Comment by VicDeo** [comment]
Published
https://apps.owncloud.com/content/show.php/Antivirus?content=157439
https://github.com/owncloud/files_antivirus/releases/tag/stable9-0.8.0.1
