### ISSUE TITLE
File .ocdata is missing after installation and server cannot be opened.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#23254]
Using  master daily tarball owncloud-daily-master.tar.bz2 or enterprise equivalent, after installing, .ocdata file is missing in the data directory and server cannot be accessed.

**Comment by nickvergessen** [comment]
data dir is missing, but that is missing since ever, so it seems to not be packaging but a code change error

**Comment by PVince81** [comment]
Likely related to https://github.com/owncloud/core/pull/23171#issuecomment-196498027

**Comment by nickvergessen** [comment]
Yeah should be fixed with #23243

**Comment by nickvergessen** [comment]
I modified the EE tarball with #23243 and now I can install again.
