### ISSUE TITLE
Background job - email notification

### ISSUE THREAD

**Issue by valentin8709** [owncloud/core#23261]
### Steps to reproduce
I don't really know, my settings:
I enable everything in the "activity" settings to notify me changes by email (even my changes).
I setup the mail configuration in the admin panel, the test is ok, I can receive emails from owncloud.

### Expected behaviour
I should receive mails about any modifications.

### Actual behaviour
Everything seems to be alright in the activity app, but I don't receive any mails.

### Server configuration
**Operating system**: Linux Mint 17.3

**Web server:** Apache 2

**Database:** Mysql

**PHP version:** 5.6

**ownCloud version:** 9.0

**Updated from an older ownCloud or fresh install:** updated from 8.2.3

**Where did you install ownCloud from:** app "updater"

**List of activated apps:**

  - activity: 2.2.1
  - calendar: true
  - comments: 0.2
  - contacts: true
  - conversations: 0.2.3
  - dav: 0.1.5
  - direct_menu: 0.7.0
  - documents: true
  - external: 1.2
  - fbsync: 1.8.1
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_gpxviewer_extended: 1.5
  - files_locking: true
  - files_mv: true
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - gallery: 14.5.0
  - html5_videoplayer: true
  - mail: true
  - news: true
  - notes: true
  - notifications: 0.2.3
  - pinit: 1.0.1
  - polls: true
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - updatenotification: 0.1.0

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => 'oc3be3xe5gbf',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' =>
  array (
    0 => 'XXX',
    1 => 'XXX',
    2 => 'XXX',
  ),
  'datadirectory' => '/media/DATA',
  'overwrite.cli.url' => 'XXX',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'owncloud',
  'dbhost' => 'XXX',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'logtimezone' => 'UTC',
  'installed' => true,
  'blacklisted_files' =>
  array (
    0 => '.htaccess',
  ),
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'XXX',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'gmail.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpsecure' => 'ssl',
  'mail_smtphost' => 'imap.gmail.com',
  'mail_smtpport' => '465',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'XXX',
  'mail_smtppassword' => 'XXX',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
 array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'password' => '',
  ),
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
  'appstore.experimental.enabled' => true,
);

**Are you using external storage, if yes which one:** SFTP & Google Drive

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** NO

#### ownCloud log (data/owncloud.log)

Error while running background job (class: OCA\Activity\BackgroundJob\EmailNotification, arguments: ): {"Exception":"Exception","Message":"Session has been closed - no further changes to the session are allowed","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/session\/memory.php(49): OC\\Session\\Memory->validateSession()\n#1 \/var\/www\/owncloud\/lib\/private\/security\/csrf\/tokenstorage\/sessionstorage.php(63): OC\\Session\\Memory->set('requesttoken', 'N5g2UDE4zyfhOMu...')\n#2 \/var\/www\/owncloud\/lib\/private\/security\/csrf\/csrftokenmanager.php(57): OC\\Security\\CSRF\\TokenStorage\\SessionStorage->setToken('N5g2UDE4zyfhOMu...')\n#3 \/var\/www\/owncloud\/lib\/public\/util.php(496): OC\\Security\\CSRF\\CsrfTokenManager->getToken()\n#4 \/var\/www\/owncloud\/lib\/private\/template.php(75): OCP\\Util::callRegister()\n#5 \/var\/www\/owncloud\/apps\/activity\/lib\/mailqueuehandler.php(250): OC_Template->__construct('activity', 'email.notificat...', '')\n#6 \/var\/www\/owncloud\/apps\/activity\/lib\/backgroundjob\/emailnotification.php(134): OCA\\Activity\\MailQueueHandler->sendEmailToUser('valou', 'valentin.dole@p...', 'fr', 'Europe\/Berlin', 1458050429)\n#7 \/var\/www\/owncloud\/apps\/activity\/lib\/backgroundjob\/emailnotification.php(94): OCA\\Activity\\BackgroundJob\\EmailNotification->runStep(500, 1458050429)\n#8 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/job.php(52): OCA\\Activity\\BackgroundJob\\EmailNotification->run(NULL)\n#9 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/timedjob.php(53): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#10 \/var\/www\/owncloud\/cron.php(141): OC\\BackgroundJob\\TimedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#11 {main}","File":"\/var\/www\/owncloud\/lib\/private\/session\/memory.php","Line":105}

**Comment by PVince81** [comment]
Duplicate https://github.com/owncloud/core/issues/23205
