### ISSUE TITLE
Shared addressbook is always writable independently on "can edit" checkbox

### ISSUE THREAD

**Issue by p5n** [owncloud/core#23273]
### Steps to reproduce
1. Share addressbook with group (I used LDAP authentication)
2. Remove "can edit" check
3. Login with user that should have read-only access and drop contacts from addressbook

### Expected behaviour
AB obviously should be read only

### Actual behaviour
Any user can drop contents of shared addressbook

**Database:** mariadb

**PHP version:** 7.0.4

**ownCloud version:** (see ownCloud admin page) 9.0.0

**Updated from an older ownCloud or fresh install:** updated many times from some ancient version

Also I tried to change access to 2 or 3 in oc_dav_shares, but AB editable anyway

**Comment by LukasReschke** [comment]
@DeepDiver1975

**Comment by p5n** [comment]
Sorry, probably whole contact cannot be dropped, but anyway contacts are editable.

**Comment by DeepDiver1975** [comment]
> Share addressbook with group

does this apply to user based shares as well? THX

**Comment by p5n** [comment]
Yes, I was able to remove Notes field and edit Groups in AB shared directly to me by username.

**Comment by DeepDiver1975** [comment]
What client are you using?

**Comment by p5n** [comment]
Web UI
