### ISSUE TITLE
Documents App: "Error while sharing - error" when trying to share a file on owncloud 9.0.0

### ISSUE THREAD

**Issue by ValidationManager** [owncloud/core#23286]
### Steps to reproduce
1. Login, click on Documents App, select Document for editing
2. Click on Share button, enter 2 letters of another user and click on the autocompleted username to share
3. Dialog "Error while sharing - error" pops up. Sharing fails permanently.

### Expected behaviour
Sharing should be executed

### Actual behaviour
"Error while sharing - error" dialog is displayed

### Server configuration
**Operating system**:
Debian 8 x86_64
**Web server:**
Apache2
**Database:**
mysql Ver 15.1 Distrib 10.0.23-MariaDB
**PHP version:**
php 5.6.16-0+deb8u1 (fpm-fcgi)
**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.0 (stable)
**Updated from an older ownCloud or fresh install:**
fresh install via web installer into empty directory
**Where did you install ownCloud from:**
owncloud.org
**Signing status (ownCloud 9.0 and above):**
ownCloud 9.0.0 (stable)
```
**List of activated apps:**
Documents, Contacts, Calendar, Music, Activity, Gallery
```

  'instanceid' => 'xxxx',
  'passwordsalt' => 'xxxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'example.com',
  ),
  'datadirectory' => '/var/www/vhosts/example.com/httpdocs/owncloud/data',
  'overwrite.cli.url' => 'https://example.com/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'ownclouddb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'xxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'loglevel' => 0,
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'example.com',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'example',
  'mail_smtppassword' => 'example',
  'mail_smtphost' => 'example.com',
  'mail_smtpport' => '465',
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows (any current)
### Logs
#### Web server error log
no error when situation is triggered
Insert your webserver log here
nothing logged when situation is triggered

#### ownCloud log (data/owncloud.log)
nothing logged when situation is triggered. Also enabled verbose logging.

#### Browser log
```
Started Debug session in Firefox. Via breakpoints and call stack, root cause is found in share.js, lines 249 - 270. "result" object returned from share.php is empty (""), triggering this dialog to be shown. I am not aware how to debug deeper into share.php here. Please advise!

			return $.post(OC.filePath('core', 'ajax', 'share.php'),
				{
					action: 'share',
					itemType: itemType,
					itemSource: itemSource,
					shareType: shareType,
					shareWith: shareWith,
					permissions: permissions,
					itemSourceName: itemSourceName,
					expirationDate: expirationDate
				}, function (result) {
					if (result && result.status === 'success') {
						if (callback) {
							callback(result.data);
						}
					} else {
						if (_.isUndefined(errorCallback)) {
							var msg = t('core', 'Error');
							if (result.data && result.data.message) {
								msg = result.data.message;
							}
							OC.dialogs.alert(msg, t('core', 'Error while sharing'));

```

**Comment by LukasReschke** [comment]
Does sharing via the files interface work for you?

**Comment by ValidationManager** [comment]
Yes, sharing via files interfaces works as expected.

**Comment by LukasReschke** [comment]
cc @rullzer @PVince81 Wasn't there something with sharing and gallery as well? Maybe documents needs adjusting as well?

cc @VicDeo

**Comment by PVince81** [comment]
not sure, @oparoz might know

**Comment by rullzer** [comment]
Documents app is still using our removed internal endpoint. https://github.com/owncloud/documents/issues/622

Which is why it is not working yet.
