### ISSUE TITLE
iOS calendar event location messes up web interface of calendar

### ISSUE THREAD

**Issue by SamEliotFisher** [owncloud/core#23281]
Took me a while to figure out why the web interface acted so strangely. See **actual behaviour**. The Browser error log finally revealed the offender: An event location created in the native iOS calendar app. The browser log will give more detail. The location was set in the app by searching for an address (street and house no).

_Bottom line, a harmless event location set by the iOS calendar app prevented 80% of the calendar web interface from working._

By changing the event location to a simple String the web interface worked as expected. Setting up another event with a different location, again using the iOS calendar app to point to a specific address (and geo location) will again cause the mentioned **actual behaviour**.

### Steps to reproduce
1. Upgrade owncloud from latest 8.x to 9.0 via .tar.bz2
2. Update all apps
3. Open calendar web interface using firefox

### Expected behaviour
Display all calendars and according events.

### Actual behaviour
- Doesn't show any calendars or events for five seconds
- After five seconds it lists calendars on the left hand side (no events)
- One calendar keeps showing the loading circle gif (calendar A) (that doesn't change)
- When clicking on colored square to NOT display a certain calendar (calendar B) events of other calendars appear. However, not of the one with the loading circle gif (calendar A).
- Clicking again the square of calendar B will not display its events.
- Clicking the colored square of a third calendar (C) will display the events of calendar B, and remove events of calender C.
- Clicking it again doesn't change anything.
- Same behavior can be repeated by using calendar C and D.

### Server configuration
**Operating system**: 
Ubuntu 14.04

**Web server:**
nginx 

**Database:**
MySQL

**PHP version:**
PHP 5.5.9-1ubuntu4.14 (fpm-fcgi) (built: Oct 28 2015 01:38:24)

**ownCloud version:** (see ownCloud admin page)
9.0.0.19

**Updated from an older ownCloud or fresh install:**
Upgrade from latest 8.x

**Where did you install ownCloud from:**
.tar.bz2 from owncloud.org

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
  - activity: 2.2.1
  - announcementcenter: 1.1.1
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - documents: true
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - music: true
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc8ab27a8968",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/example.com",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "admin",
        "mail_smtpmode": "php",
        "mail_domain": "example.com",
        "maintenance": false,
        "theme": "",
        "forceSSLforSubdomains": true,
        "loglevel": 3,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": false
    }
}
```

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Are you using an external user-backend, if yes which one:** 
No

### Client configuration
**Browser:**
Firefox 45

**Operating system:**
Windows 10 64Bit

#### Web server error log
```
2016/03/15 21:24:40 [error] 14035#0: *30654 access forbidden by rule, client: XXX.XX.XX.XX, server: example.com, request: "GET /data/.ocdata HTTP/1.1", host: "example.com"
2016/03/15 21:24:45 [error] 14035#0: *30652 access forbidden by rule, client: XXX.XX.XX.XX, server: example.com, request: "GET /data/.ocdata HTTP/1.1", host: "example.com"
2016/03/15 21:50:30 [error] 14034#0: *31017 access forbidden by rule, client: XXX.XX.XX.XX, server: example.com, request: "GET /data/.ocdata HTTP/1.1", host: "example.com"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"2gdvqs+N99IjXYQLyUnx","remoteAddr":"XXX.XX.XX.XX","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-15T19:31:09+00:00"}
{"reqId":"iiHZxifaalwl3Ocj6lj\/","remoteAddr":"XXX.XX.XX.XX","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-15T20:24:38+00:00"}
{"reqId":"OslZrwePU2J6pN9re08V","remoteAddr":"XXX.XX.XX.XX","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-15T20:24:43+00:00"}
{"reqId":"jOJw97RbQdpzvA\/yUz57","remoteAddr":"XXX.XX.XX.XX","app":"PHP","message":"Undefined index: newVersionString at \/var\/www\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-15T20:50:28+00:00"}

```

#### Browser log
```
ParserError: Empty parameter name in ';VALUE=URI;X-ADDRESS="Köln, Deutschland";X-APPLE-MAPKIT-HANDLE=CAES4QEaEgmGGvXjXXVJQBGq4edGlcMbQCKMAQoHR2VybWFueRICREUaFk5vcnRoIFJoaW5lLVdlc3RwaGFsaWEqB0NvbG9nbmUyB0NvbG9nbmU6BTUwOTY5Qg1TdGFkdGJlemlyayAyUg1Qb2hsaWdzdHJhw59lWgExYg9Qb2hsaWdzdHJhw59lIDGKAQlab2xsc3RvY2uKAQ1TdGFkdGJlemlyayAyKg9Qb2hsaWdzdHJhw59lIDEyD1BvaGxpZ3N0cmHDn2UgMTINNTA5NjkgQ29sb2duZTIHR2VybWFueTg5QAE=;X-APPLE-RADIUS=99.82630764011634;X-APPLE-REFERENCEFRAME=1;X-TITLE=Pohligraße 1:geo:50.916928,6.940999'
```

setting up another event to see if its the location (yes it is):
```
ParserError: Empty parameter name in ';VALUE=URI;X-ADDRESS="Aachener Straße 186, 50931 Cologne, Germany";X-APPLE-MAPKIT-HANDLE=CAESxgIIrk0QxvenhruGj+/0ARoSCapkAKjid0lAEY4Yh0TrshtAItsBCgdHZXJtYW55EgJERRoWTm9ydGggUmhpbmUtV2VzdHBoYWxpYSoHQ29sb2duZTIHQ29sb2duZToFNTA5MzFCD0FhY2hlbmVyIFdlaWhlclIQQWFjaGVuZXIgU3RyYcOfZVoDMTg2YhRBYWNoZW5lciBTdHJhw59lIDE4NooBDVN0YWR0YmV6aXJrIDOKAQ1TdGFkdGJlemlyayAxigEKTGluZGVudGhhbIoBDU5ldXN0YWR0LU5vcmSKAQ1OZXVzdGFkdC1Tw7xkigEPQWFjaGVuZXIgV2VpaGVyKhRVbml2ZXJzaXTDpHRzc3RyYcOfZTIUQWFjaGVuZXIgU3RyYcOfZSAxODYyDTUwOTMxIENvbG9nbmUyB0dlcm1hbnk4OQ==;X-APPLE-RADIUS=13.13500507021464;X-APPLE-REFERENCEFRAME=1;X-TITLE=Universitätsstraße:geo:50.936605,6.924726'
```

**Comment by LukasReschke** [comment]
Browser site ParserError => Please reopen at https://github.com/owncloud/calendar
