### ISSUE TITLE
Double file when sharing file from ext storage where recipient also has access to said storage

### ISSUE THREAD

**Issue by RosinSmoke** [owncloud/core#23295]
### Steps to reproduce
1. Create a file as 1st user
2. Return to Files mode
3. Drag-n-drop the file to Dropbox location as 1st user (encryption is enabled and sharing is allowed for this Dropbox external storage) 
4. Log in as 2nd user
### Expected behaviour
1. If file was not shared by 1st user to 2nd, the file in Dropbox storage should not be seen by 2nd user
2. If file was shared before moving, 2nd user can see it in Dropbox location, nowhere else (after moving)
### Actual behavior

1) If file was not shared, 2nd user still can see the file created by 1st user

2) If file was shared, after moving it to the Dropbox location 2nd user can see it both in previous location and current location, while 1st user sees it in Dropbox storage

2.1) If the file is the .odt document and 2nd user opens it after moving via Documents app (reqires Open/LibreOffice on server), after editing it by 2nd user and closing the edit screen the next attempts to open it by anyone end with alert "_Failed to load this document. Please check if it can be opened with an external odt editor. This might also mean it has been unshared or deleted recently._" and returning to Documents app main screen with tiles.

2.1.1) No user can delete "broken" files from Owncloud web GUI, they can be deleted only from Dropbox directly

2.2) In the Documents app main screen 2nd user can see 2 tiles with this document, both lead to it and open edit screen. After edit and closing the file both tiles return the same alert, as in 2.1 to any user account.

3) If the file was uploaded to the Dropbox storage via Owncloud, after sharing it is also seen in the local storage folder. Doubled files behave same as described in p.2
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
PHP 5.5.9-1ubuntu4.14

**ownCloud version:** (see ownCloud admin page)
9.0

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
Repository marked as "stable" from installation instruction

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```

Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - dav: 0.1.5
  - documents: 0.12.0
  - encryption: 1.2.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - music: 0.3.10
  - news: 7.1.2
  - notifications: 0.2.3
  - ownnote: 1.07
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - federation
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocp18lf0efqq",
        "passwordsalt": "[removed]",
        "secret": "[removed]",
        "trusted_domains": [
            "[mydomain]"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/[mydomain]\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "database_duh",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "root",
        "dbpassword": "[removed]",
        "logtimezone": "UTC",
        "installed": true
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Only Dropbox, mentioned above. DB storage folder is mounted to owncloud's storage root folder.

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No
### Client configuration

**Browser:**
FF 44.0.2

**Operating system:**
Windows 10 / 7
#### ownCloud log (data/owncloud.log)

[http://pastebin.com/cxrJHEjV](http://pastebin.com/cxrJHEjV)
#### Browser log

```

```

**Comment by PVince81** [comment]
Thanks for the detailed report.
I tested Dropbox today and didn't see such issue, but I wasn't looking carefully.

Let me have another try.

**Comment by PVince81** [comment]
@RosinSmoke is your Dropbox storage a system-wide storage ? (configured in the admin page, not personal page) And it looks like you let all users access that same system-wide storage, is that correct ?

**Comment by PVince81** [comment]
also does user1 share with user2 or the other way around ? which user is the recipient ?

**Comment by RosinSmoke** [comment]
@PVince81
So, the DB location was added by root using admin page, mounted to the local storage root folder and is available for "admin" group and that group, where user1 and user2 are. 
User1 (who is group admin, if that matters) shares files to the user2 (who is not), and files were created/uploaded by user1 only, I should probably try all this backwards.

**Comment by PVince81** [comment]
My steps on v9.0.0:

1. Setup OC with "admin" as admin user
1. Enable encryption
1. Create two users "user1" and "user2" and add them both to group "group1"
1. Setup dropbox storage as "/dropbox", with applicable "admin (group)" and "group1 (group)"
1. Login as "user1"
1. Upload a file "/test.txt" (outside the dropbox)
1. Share "test.txt" with "user2"
1. Move "/test.txt" into "/dropbox" with drag and drop
1. Login as "user2"
1. Check whether "/test.txt" is visible

I don't get the same results.
In my case, the bug is that "user2" doesn't see the file "test.txt" at all in "All files" but only under "Shared with you".

I don't see any double files.

Also there's one thing I don't understand: you said that the dropbox folder is applicable for the group containing both user1 and user2, so it means that user2 already has access to the dropbox folder. In such case, why would user1 try to share it with user2 again ?

Please confirm that my steps are correct.

**Comment by PVince81** [comment]
Oh, I forgot to enable sharing... Trying again.

**Comment by PVince81** [comment]
Ok I think I understand what you mean with "doubled" file.

Basically "user2" has access to the same file through two means:
1) Through the "dropbox" folder that user has access to
2) Through the share

The sharing code is not able to find out whether the user is receiving the files through external storages.

CC @rullzer

**Comment by RosinSmoke** [comment]
@PVince81
Steps are correct, but can I ask you to also check this with the .odt files instead of .txt? I had to enable "Documents" app to do this.

I thought, that if storage is visible for another user it will act as local storage, when other user cannot see files of other users if not shared. So I assumed that if I create a file in DB storage I would have to share it with user2 if I want him to see it.

P.S.: I also checked with the Google Drive and there it just kicks me from the file edit mode when other user enters same file. Maybe I should give more attention to Documents app itself.

**Comment by PVince81** [comment]
I guess maybe the documents app doesn't like it when a file is accessible from two locations @VicDeo

**Comment by RosinSmoke** [comment]
```
Basically "user2" has access to the same file through two means:
1) Through the "dropbox" folder that user has access to
2) Through the share

The sharing code is not able to find out whether the user is receiving the files through external storages.
```

I just wanted to ask, is this the reason, why user2 can see the file in the local storage? I mean, if, for example, the user2 has no access to external storage, but has the file shared to him and file lies in this storage, is it a way to let him open it, when the System places link to root of local storage? (Just a guess, but I'm kinda interested how the System acts in cases when user has no rights for storage, but has the rights for file inside)

**Comment by PVince81** [comment]
If you remove "user2" from the "dropbox" storage "applicable" field, then "user2" will still see the file "/test.txt" through the share, it will appear as before in the root.

Basically every received share is like a virtual file/folder that appears in the user's local storage.

**Comment by rullzer** [comment]
We do tests if the recipient of a share already has access to a file. But this get expensive and complicated really fast for external storages.

Basically yes you see the same file twice... but it is accessed in 2 different ways. 

1. Direct (via the external storage).
2. Indirect via user1 and then to the external storage.

The thing is that we don't have the same level of control over external storages. So there is no easy solution here.

**Comment by PVince81** [comment]
Won't fix, too complicated without significant benefit for this special use case.
