### ISSUE TITLE
Integrity for themed mimetypes

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#23291]
- place the updated mime type icons into the theme
- then run `./occ maintenance:mimetype:update-js` to update a JSON file to announce the new mime type icons to the JS code base
- now the ions should be properly shown in the web UI

This will generate following content:

``` patch
diff --git a/core/js/mimetypelist.js b/core/js/mimetypelist.js
index 89c6e8c..989bd4f 100644
--- a/core/js/mimetypelist.js
+++ b/core/js/mimetypelist.js
@@ -107,5 +107,14 @@ OC.MimeTypeList={
     "x-office-presentation",
     "x-office-spreadsheet"
 ],
-   themes: []
+   themes: {
+    "myTheme": [
+        "folder",
+        "folder-drag-accept",
+        "folder-external",
+        "folder-public",
+        "folder-shared",
+        "folder-starred"
+    ]
+}
 };
```

@LukasReschke I think this will be causing issues with the integrity check.

**Comment by LukasReschke** [comment]
This is such a mess. Can't we put that stuff into a theme or so? :see_no_evil: 

Overwriting core files for this *shivers*………

**Comment by MorrisJobke** [comment]
cc @Xenopathic

**Comment by Xenopathic** [comment]
cc @rullzer

**Comment by MorrisJobke** [comment]
> cc @rullzer

I guess I mix you both always up :(

**Comment by Xenopathic** [comment]
@MorrisJobke We both worked on mimetype stuff, don't worry :smile:

**Comment by rullzer** [comment]
Ues let me take a look at that... but not now...

**Comment by rullzer** [comment]
Ok, had a quick look. We can add js files to themes (whoohoo)!

However, if a user chosed to add mimetype mappings (and then run the update command). We will still change core files. but I guess that is valid in that case. @LukasReschke ?

**Comment by MorrisJobke** [comment]
> but I guess that is valid in that case. @LukasReschke ?

I don't think, that this is a good idea.
