### ISSUE TITLE
/dev unreadable leads to blank page and upgrade error

### ISSUE THREAD

**Issue by Blackclaws** [owncloud/core#23297]
### Steps to reproduce
1. Install Owncloud 9.0
2. Revoke read and execute access to /dev folder for the http user
3. Owncloud only yields a blank page

1. Install Owncloud 8.2.3
2. Revoke read and execute access to /dev folder for the http user
3. Owncloud only yields a blank page
4. On upgrade to Owncloud 9.0 via occ upgrade you get "Cannot open source device" exception

### Expected behaviour
An error message telling what is wrong or just a warning saying that /dev/urandom is unavailable. This used to happen with older versions.

For the upgrade I would have expected a more verbose error message. "Cannot open source device" as it comes from mcrypt doesn't give you a lot of information.

### Actual behaviour
You get a blank page or a non verbose error message. In actuality the system crashes somewhere during the retrieval of CryptoWrapper from the DepedencyInjection System

### Server configuration
**Operating system**: Arch Linux

**Web server:** Nginx + PHP-FPM

**Database:** MariaDB

**PHP version:** 7.0.4

**ownCloud version:** (see ownCloud admin page) 8.2.3/9.0

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** Arch repositories / Zip files => Same behaviour

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Integrity checker has been disabled. Integrity cannot be verified.
**List of activated apps:**
Calendar/Contacts

(Without the database password, passwordsalt and secret)
$CONFIG = array (
  'instanceid' => 'ocz1hq1sawaa',
  'trusted_domains' =>
  array (
           redacted
  ),
  'datadirectory' => '/usr/share/webapps/owncloud/data',
  'overwrite.cli.url' => 'redacted',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'theme' => '',
  'loglevel' => 0,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
  'forcessl' => true,

**Are you using encryption:**no

**Comment by DeepDiver1975** [comment]
> You get a blank page or a non verbose error message. In actuality the system crashes somewhere during the retrieval of CryptoWrapper from the DepedencyInjection System

anything in the logs?

**Comment by PVince81** [comment]
Fixed with https://github.com/owncloud/core/pull/26075 where the exception is printed directly without template in case some base stuff like logger could not be inited yet.
