### ISSUE TITLE
Users can see the admin mounts and set their credentials from the personal page only if they're allowed to mount their own mounts

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#23294]
### Steps to reproduce
1. Setup several admin mounts with different type of credentials
2. Make sure the "Allow users to mount external storage" is unchecked
3. Go to the personal page

### Expected behaviour
Admin mounts that can be used by the current user should be shown there. Users can set their own credentials in mounts whose credentials type is  "user credentials"

### Actual behaviour
Nothing is shown. Users can only enter their credentials from the files page. Users who enter a valid but wrong credentials (to access with user A instead of user B, for example) can't change their credentials.

Information about admin mounts can only be seen from the personal page if the "Allow users to mount external storage" checkbox is checked. You can set the credentials for the "user credentials" mounts then.

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** ownCloud 9.0.0

**Updated from an older ownCloud or fresh install:** fresh install

**Are you using external storage, if yes which one:** yes

**Are you using encryption:** no

**Comment by PVince81** [comment]
@Xenopathic if you have a free minute ? :wink:

**Comment by PVince81** [comment]
The expected behavior is aligned on WND's previous behavior. So if we don't fix this it could be considered a regression. Increasing severity.

@Xenopathic let me know if you don't have time and I'll take care of it myself.

**Comment by Xenopathic** [comment]
The problem is that the entire GUI section gets disabled if that checkbox is unmarked. Do we want to show the GUI section if there aren't any applicable admin mounts configured, and that checkbox is unmarked? As described here, we definitely need to show the GUI section if there are some applicable admin mounts...

**Comment by PVince81** [comment]
Yes, let's always show the GUI, but remove the empty row so the user cannot add new mounts.

**Comment by MorrisJobke** [comment]
Backport to stable9 in  #23335
