### ISSUE TITLE
"Downloaded, Renamed Conflicting File" When syncing files from network share

### ISSUE THREAD

**Issue by zwollex** [owncloud/core#23298]
Hi,

I am syncing a folder which is located on a network share (SMB fileserver) and whenever I reboot or come back from sleep/hibernate, I keep getting these messages in the "recent changes" list. " Downloaded, Renamed conflicting file".

At first I was ignoring this because the files were still intact and looked fine to me. However, if I delete a file, it automatically rsync this file and placing it back. Also if I delete it from the web browser version, the file gets sycned back. So deleting doesn't work. I have not tried what will happen when you modify the file as these are static PDF files.

Using OS X El Capitan with latest 2.1.1 client version and 8.1.5 as server version.

Anyone else experiencing this?

**Comment by LukasReschke** [comment]
Please fill out the issue template. THX.
