### ISSUE TITLE
After upgrading from 8.2.2 to 9.0.0 all apache configurations for owncloud are missing

### ISSUE THREAD

**Issue by tps800** [owncloud/core#23305]
Refer to #23289

I've tested the provided fix by LukasReschke. Did not work. same as before. Moreover: since OC reported:
```
$ ./occ status
  - installed: true
  - version: 9.1.0.0
  - versionstring: 9.1.0 pre alpha
  - edition:
```

after installing the given *.tar.gz-file (https://download.owncloud.org/community/owncloud-daily-stable9.tar.bz2), while I reported having installed by *.rpm, I am now unable to go back to the 9.0.0-1.1-Version:
```
$ ./occ update
An unhandled exception has been thrown:
OC\HintException: [0]: Downgrading is not supported and is likely to cause unpredictable issues (from 9.1.0.0 to 9.0.0.19) ()
```

Any ideas?

**Comment by MorrisJobke** [comment]
> Any ideas?

Actually it's unsupported to roll back, but there shouldn't be any breaking changes since then. Simply place the 9.0.0 code (I guess this is provided by the rpms) and then change the version in config/config.php to `9.0.0.19`.
