### ISSUE TITLE
current-user-principal returns incorrect href.

### ISSUE THREAD

**Issue by gvde** [owncloud/core#23306]
Request the current user principal from carddav and it returns an incorrect href for the current user principal on owncloud 9:

```
$ curl  -u myself --data @propfind4.xml -H 'Depth: 0' -H 'Content-Type: application/xml; charset-utf-8' -X PROPFIND https://www.example.com/owncloud/remote.php/carddav/
```
with propfind4.xml:
```
<d:propfind xmlns:d="DAV:">
  <d:prop>
     <d:current-user-principal />
  </d:prop>
</d:propfind>
```
and after entering correct user password, returns:
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav">
 <d:response>
  <d:href>/owncloud/remote.php/carddav/</d:href>
  <d:propstat>
   <d:prop>
    <d:current-user-principal>
     <d:href>/owncloud/remote.php/carddav/principals/users/myself/</d:href>
    </d:current-user-principal>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
```
However, /owncloud/remote.php/carddav/principals/users/myself/ does not exist. The only principal uri that exists would be /owncloud/remote.php/carddav/principals/myself/

**Comment by LukasReschke** [comment]
cc @DeepDiver1975

**Comment by PVince81** [comment]
@DeepDiver1975 didn't you fix this already ? I remember seeing a PR that fixed hrefs

**Comment by DeepDiver1975** [comment]
The LegacyDAVACL plugin is performing the transformation of principals - which is not necessary in this case :cry:

**Comment by DeepDiver1975** [comment]
@gvde thanks a lot for this in depth testing - fix is available at https://github.com/owncloud/core/pull/23342
