### ISSUE TITLE
Invisible buttons should be visible

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/core#23316]
I suggest that the invisible gear and trash icons in external storages really need to be always visible, and not visible only on mouseover. Making users hunt for the secret controls doesn't seem like a good idea :) They don't save space, as the width of the panel is the same regardless if they are visible or not.

Where O where are the rest of the controls?

![external-storage-icons-1](https://cloud.githubusercontent.com/assets/8388387/13815780/22458970-eb49-11e5-86ad-55288192de8f.png)

Yay, I accidentally mouseovered the secret location and there they are!

![external-storage-icons-2](https://cloud.githubusercontent.com/assets/8388387/13816055/1ee0c730-eb4a-11e5-99a0-dbe68962807d.png)

**Comment by PVince81** [comment]
@owncloud/designers

**Comment by paurisa** [comment]
I found the stylesheet file that makes the element hidden and I'm already fixing this.

**Comment by paurisa** [comment]
This issue can be closed as a fix has already been implemented.
See: https://github.com/owncloud/core/pull/23397

**Comment by jancborchardt** [comment]
Nice, thanks a lot @paurisa! Looking forward to more design bug fixes from you :)

You are very welcome in our #owncloud-design channel on IRC (freenode) as well.

**Comment by carlaschroder** [comment]
Thanks everyone!
