### ISSUE TITLE
shared address book doesn't show through carddav

### ISSUE THREAD

**Issue by gvde** [owncloud/core#23328]
owncloud 9: If someone shares an address book with me, I can see the contacts from the address book online in the contacts app. However, through carddav the address book is not shown. If I do a:
```
$ curl -u myself --data @propfind3.xml -H 'Depth: 1' -H 'Content-Type: application/xml; charset-utf-8' -X PROPFIND https://www.example.com/owncloud/remote.php/carddav/addressbooks/myself/
```
with propfind3.xml containing:
```
<d:propfind xmlns:d="DAV:" xmlns:cs="http://calendarserver.org/ns/">
  <d:allprop/>
</d:propfind>
```
I only get this:
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav">
 <d:response>
  <d:href>/owncloud/remote.php/carddav/addressbooks/myself/</d:href>
  <d:propstat>
   <d:prop>
    <d:resourcetype>
     <d:collection/>
    </d:resourcetype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
 <d:response>
  <d:href>/owncloud/remote.php/carddav/addressbooks/myself/contacts/</d:href>
  <d:propstat>
   <d:prop>
    <d:resourcetype>
     <d:collection/>
     <card:addressbook/>
    </d:resourcetype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
```
which is my own collection and my own address book "contacts" but the shared one is missing.

The problem seems to be that getAddressBooksForUser is called with principal "principals/myself" from the getChildren in UserAddressBooks which only returns my own address books.

(Another call to getAddressBooksForUser from the hookmanager uses principal "principals/users/mysql" which does in fact return my own and the shared address book. So it seems an issue of the principal uri used.)

**Comment by DeepDiver1975** [comment]
> f someone shares an address book with me

@gvde shared with you explicitly or with a group you are in?

**Comment by gvde** [comment]
Oh. Forgot that: shared with a group I am in... also editing allowed.

**Comment by gvde** [comment]
Still open for me. Now change so far.

**Comment by DeepDiver1975** [comment]
> Still open for me. Now change so far.

something changed meanwhile - have to reanalyse :angry:

**Comment by DeepDiver1975** [comment]
I was only testing this with calendars - and not with addressbooks and one case slipped trough

@gvde THX for pushing again and again - I should have taken a  closer look much earlier - I'm sorry

**Comment by gvde** [comment]
With #23568 applied I now get this:

```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav">
 <d:response>
  <d:href>/owncloud/remote.php/carddav/addressbooks/myself/</d:href>
  <d:propstat>
   <d:prop>
    <d:resourcetype>
     <d:collection/>
    </d:resourcetype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
 <d:response>
  <d:href>/owncloud/remote.php/carddav/addressbooks/myself/contacts/</d:href>
  <d:propstat>
   <d:prop>
    <d:resourcetype>
     <d:collection/>
     <card:addressbook/>
    </d:resourcetype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
 <d:response>
  <d:href>/owncloud/remote.php/carddav/addressbooks/myself/contacts_shared_by_admin/</d:href>
  <d:propstat>
   <d:prop>
    <d:resourcetype>
     <d:collection/>
     <card:addressbook/>
    </d:resourcetype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
```

The shared address book is now listed. So that's a GO from me...
