### ISSUE TITLE
"Allow editing" capability in share by link not disabled

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#23325]
### Steps to reproduce
1. "Allow editing" capability is enabled in Share API
2. Share a folder by link -> The link is correctly created 
3. Enable the option "Allow editing" of the just created share 
4. Copy and paste the Share link in a browser -> New content can be uploaded to the shared folder
5. Disable "Allow editing" capability in Share API -> Share link does not show the option
6. Refresh the share link in the browser

### Actual behaviour
New content can be uploaded/New subfolders can be created through the link in the browser

### Expected behaviour
No content can be uploaded/No subfolders can be created, because the capability was disabled.

### Server configuration
{"installed":true,"maintenance":false,"version":"9.0.0.19","versionstring":"9.0.0","edition":"Enterprise"}

**Comment by PVince81** [comment]
@rullzer please have a look

**Comment by rullzer** [comment]
Ok PR incomming

**Comment by rullzer** [comment]
PR in #23346
