### ISSUE TITLE
setId is missing from IShare

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#23337]
`OC\Share20\Share` implements `\OCP\Share\IShare`

We can see this method claiming to be an implementation
```
	/**
	 * @inheritdoc
	 */
	public function setId($id) {
		$this->id = $id;
		return $this;
	}
```
https://github.com/owncloud/core/blob/73e37377771ecd24ca44bc3176e491977df0da10/lib/private/share20/share.php#L74-L80

but that's missing from the interface.

https://github.com/owncloud/core/blob/master/lib/public/share/ishare.php#L36

Another hint is that `setId` is also used quite often in tests after having fetched an instance of IShare via `getShareManager`.

@rullzer

**Comment by rullzer** [comment]
Yes, I'm still not sure how to solve it. Because consumers of the API should not touch the id basically. That should just be set by share providers.

**Comment by oparoz** [comment]
I though it might have been the reason it wasn't included.
So if you want to keep it that way, maybe change the comment on the method?

**Comment by rullzer** [comment]
Yeah. Does not solve to problem that we need it in test sometimes... (and mocking all those methods is a real pain).

**Comment by oparoz** [comment]
Definitely and I'm not sure what the best practice is in this case. Does it really make sense to only have the getter there if the setter is not supposed to be used?
Regarding tests, maybe mock that object once in a trait so that all tests which involve sharing can use it?

**Comment by PVince81** [comment]
@rullzer IIRC for the comments API the id setter is there, but throws an exception if there is already an id in the comment model.

**Comment by rullzer** [comment]
@PVince81 I like that approach... I'll take care of it.
