### ISSUE TITLE
Issues with file locking and inception ownCloud external storage

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#23330]
I just booted up my dev instance on the latest master, and pretty much everything in the web UI is not responding, and I'm seeing variations on the following error in the logs for inserts and deletes on oc_file_locks:

`General error: 1205 Lock wait timeout exceeded; try restarting transaction`

Running MariaDB, PHP 7, ownCloud master, DB file locking (obviously)

~~I don't know if my inception ownCloud external storage mount caused this, but it's certainly bad behaviour anyway.~~ The inception ownCloud mount causes this - I can only assume that some sort of exclusive lock is held, deadlocking the instance.

cc @icewind1991

**Comment by Xenopathic** [comment]
Almost certainly something to do with my inception ownCloud storage. It was configured with login credentials (store in session), that killed my ownCloud as soon as it was status checked.

**Comment by PVince81** [comment]
Can you clarify what you mean with "inception instance" ?

Are you connecting an ext storage to the same instance but another user/root ?

**Comment by Xenopathic** [comment]
So this seems to happen only if I configure an ownCloud mount to the same instance, with the same user, pointing at the root directory. Pointing at a sub-directory seems to work fine, and I haven't tested with different users.

Specifically, I'm seeing these errors:

```
{"reqId":"KMuN7Ltj7VU56\/vCzHnE","remoteAddr":"10.120.100.154","app":"core","message":"Exception while scanning file \"abc\": An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\"files\\\/e1174ab05e8a74580b286eab7d3dc512\", 1, 1458248314, \"files\\\/e1174ab05e8a74580b286eab7d3dc512\"]:\n\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction","level":0,"time":"2016-03-17T19:59:25+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/ownCloud1"}
{"reqId":"KMuN7Ltj7VU56\/vCzHnE","remoteAddr":"10.120.100.154","app":"core","message":"Exception while scanning file \"inception-mount\": An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\"files\\\/923b1fc46382c2225490d9df051a0f04\", 1, 1458248365, \"files\\\/923b1fc46382c2225490d9df051a0f04\"]:\n\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction","level":0,"time":"2016-03-17T20:00:16+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/ownCloud1"}
{"reqId":"KMuN7Ltj7VU56\/vCzHnE","remoteAddr":"10.120.100.154","app":"core","message":"Exception while scanning file \"Dropbox\": An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\"files\\\/ed0afa9df1d0ed148208213de62e48a0\", 1, 1458248416, \"files\\\/ed0afa9df1d0ed148208213de62e48a0\"]:\n\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction","level":0,"time":"2016-03-17T20:01:07+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/ownCloud1"}
```

**Comment by PVince81** [comment]
Setting to low as it isn't a proper use case.

**Comment by PVince81** [comment]
This use case doesn't make sense, closing
