### ISSUE TITLE
Problem to add user.

### ISSUE THREAD

**Issue by ibarragerman** [owncloud/core#23338]
### Steps to reproduce
1. After a clean installation ussing softaculus
2. When it trying to add a new user or group nothing happends.
3. If you check the error console appear the following error.

Failed to load resource: the server responded with a status of 403 (Forbidden)
users.js:827 Uncaught TypeError: Cannot read property 'message' of undefined

### Expected behaviour
Tell us what should happen
Creat a new user

### Actual behaviour
Tell us what happens instead
Nothing, only console error.

### Server configuration
**Operating system**:
linux

**Web server:**
apache

**Database:**
mysql

**PHP version:**
5

**ownCloud version:** (see ownCloud admin page)
8

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by LukasReschke** [comment]
Please provide more information such as the exact version etc.

**Comment by DeepDiver1975** [comment]
let's simply reopen this issue as soon as we have more information
