### ISSUE TITLE
External storage sharing options not easily found

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#23348]
It appears it is not always clear to users that we now by default disable sharing of files on external storages. And also not that clear how to enable it.

I suggest we add a note to the bottom of the sharing stating that sharing options per external storage can be configured in the external storage settings.

Or maybe we should open the configs by default when dding a new storage.

CC: @owncloud/designers

**Comment by PVince81** [comment]
Similar to https://github.com/owncloud/core/issues/23316

**Comment by RealRancor** [comment]
> It appears it is not always clear to users that we now by default disable sharing of files on external storages. And also not that clear how to enable it.

Raised: https://github.com/owncloud/documentation/issues/2281

But how should a user knows that if its not documented somewhere?

**Comment by PVince81** [comment]
duplicate of https://github.com/owncloud/core/issues/17795
