### ISSUE TITLE
Integrity check stumbles over lost+found special directory

### ISSUE THREAD

**Issue by stephan2012** [owncloud/core#23341]
Dear owncloud maintainers,

my ownCloud 9.0 installation lives on a dedicated ext4 filesystem mounted on /var/www/owncloud. As usual it has a _lost+found_ directory granting access to root only. ownCloud runs as a different user and has no access to it. Thats why the new integrity check throws an exception on it:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXCEPTION
		- UnexpectedValueException
		- RecursiveDirectoryIterator::__construct(/var/www/owncloud/lost+found): failed to open dir: Permission denied

Raw output
==========
Array
(
    [core] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => UnexpectedValueException
                    [message] => RecursiveDirectoryIterator::__construct(/var/www/owncloud/lost+found): failed to open dir: Permission denied
                )

        )

)
```

It would be nice if ownCloud just skips the _lost+found_ special directory on it's integrity check.

### Server configuration
**Operating system**: Debian GNU/Linux 8.3

**Web server:** Nginx 1.9.10

**Database:** MySQL 5.6.27

**PHP version:** 5.6.17

**ownCloud version:** ownCloud 9.0.0 (stable)

**Updated from an older ownCloud or fresh install:** Update

**Where did you install ownCloud from:** Official Debian packages

**Comment by PVince81** [comment]
@LukasReschke

**Comment by nomeata** [comment]
I can confirm this issue on my installation.

**Comment by RealRancor** [comment]
Should be easy to fix: https://github.com/owncloud/core/issues/23409

**Comment by stephan2012** [comment]
Works. Thank you. :-)
