### ISSUE TITLE
DAV app returns raw contact image instead of URL

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/core#23345]
### Steps to reproduce
1. Use OCP\Contacts\IManager::search
2. Use the 'PHOTO' attribute as url for the contacts image

### Expected behaviour
'PHOTO' should be a valid URL for an image that can be used in the browser, e.g. contact images in the mail app.

### Actual behaviour
'PHOTO' contains the raw image.

**ownCloud version:** (see ownCloud admin page)
9

That behavior changed when switching from the old contacts app to the new dav app and therefore breaks mail on oc9, see https://github.com/owncloud/mail/pull/1352 for a quick fix.

@DeepDiver1975 as discussed

**Comment by DeepDiver1975** [comment]
The old contacts app was returning a url - yes - here is the code

https://github.com/owncloudarchive/contacts/blob/master/lib/addressbookprovider.php#L162-L169

**Comment by DeepDiver1975** [comment]
I need to think about on how to fix this in the future.

@ChristophWurst with respect to the mail app as of today: as you can see there used to be a prefix given to the photo element: 

```php
$j['data']['PHOTO'] = "VALUE=uri:$url";
```

The mail app code should check for this and only use the url is given

**Comment by jancborchardt** [comment]
And this is definitely something we should backport, right? @karlitschek

**Comment by karlitschek** [comment]
yes. backport please

**Comment by DeepDiver1975** [comment]
> And this is definitely something we should backport,

once there is anything to be backported ...

**Comment by jancborchardt** [comment]
@DeepDiver1975 get to work ;)

**Comment by PVince81** [comment]
@DeepDiver1975 any update ?

**Comment by DeepDiver1975** [comment]
no time to look at this - sorry :cry:

**Comment by ChristophWurst** [comment]
9.2 then?

**Comment by PVince81** [comment]
@georgehrke can you help with this ?

**Comment by georgehrke** [comment]
sure :)
@DeepDiver1975 Do you have any requirements where in the DAV app this image endpoint should be?

**Comment by georgehrke** [comment]
@DeepDiver1975 One note about https://github.com/owncloud/core/blob/master/apps/dav/lib/CardDAV/AddressBookImpl.php

Right now you assume that the URI is always $UID.vcf, but this is only optional behavior and not required.
