### ISSUE TITLE
When deleting user warn admin if user has things shared with other users and ask whether to keep these (for the other users)

### ISSUE THREAD

**Issue by e-alfred** [owncloud/core#23356]
### Steps to reproduce
1. Delete a user as an admin.
### Expected behaviour

The admin should get warned if the user has folders/files/contacts/calendars shared with other users and get an option if he wants the other users to keep these folders/files/contacts/calendars etc in their directories.
### Actual behaviour

Everything this user shared with others is deleted. Restoring is not easy if encryption is enabled and the user is not existing in Owncloud anymore (no recovery key enabled).

**Comment by PVince81** [comment]
Note that in 9.0 there is a CLI command to transfer ownership to another user. But that's only for files and shares. Not calendar, etc.
