### ISSUE TITLE
Federated Sharing with trusted servers (Federation app) shows "at" instead of "@"

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#23357]
### Steps to reproduce

Set the federation app, and try to share a file/folder with a user in the trusted server (for example,  "remoteUser")

### Expected behaviour
Matching result:

remoteUser (@serverURL)

### Actual behaviour
Matching result:

remoteUser ( at serverURL)

### Server configuration
{"installed":true,"maintenance":false,"version":"9.0.0.19","versionstring":"9.0.0","edition":"Enterprise"}

**Comment by rullzer** [comment]
I think this was on purpose... @schiesbn

**Comment by schiesbn** [comment]
Yes, it was by purpose. I thought `user (at server)` fit better for a user interface element which should provide some additional information. I considered `user (@server)` to technical...  @jancborchardt what do you think?

**Comment by schiesbn** [comment]
For reference, this was the original issue which introduced the wording: https://github.com/owncloud/core/issues/22277 and here the corresponding pull request https://github.com/owncloud/core/pull/22351

**Comment by jesmrec** [comment]
technical or non-technical wording... that's a good question.
But if the server is not trusted, is mandatory to use the '@' to share with other servers. IMHO the wording should be the same whether the federated share is either trusted or non-trusted server.

**Comment by schiesbn** [comment]
The difference I see is that if it is neither a trusted server, nor you have the user in your local address book you have to enter the (technical cloud id). But if the user is in one of your address books you typically no longer share with the (technical) cloud ID but by the users name, in this case I think `John Doe (at owncloud.org)` looks nicer than `John Doe (@owncloud.org)`... But I don't have a strong opinion here, let's see what our UX experts say.

**Comment by schiesbn** [comment]
Also keep in mind the first part is not necessarily the user-id but in most cases the display name. This is imho also a reason against the `@` because this could suggest that you can combine the first part with the `@server` to get the cloud id of the user. Which is not the case.

**Comment by jancborchardt** [comment]
If we use the full name, as in `Ada Lovelace (at code.org)` then the `at` indeed looks better. Maybe we even fully cut the prefix to `Ada Lovelace (code.org)`?

**Comment by jesmrec** [comment]
When two remote users have the same full name, can be distinguished by hovering over the remote URL if i am not wrong. But mobile clients can not do that, so we will decide option "at" or option "@" (this is another question, not a core one) to distinguish them.  The point is that both server and clients behaves in the same way if it is possible.

**Comment by jancborchardt** [comment]
Right. So how it should look is probably like this:

For when there is only one person with that name:

> Ada Lovelace (code.org)

When there are multiple, include the username – only for these relevant people though!

> Ada Lovelace (ada@code.org)
> Ada Lovelace (alovelace@code.org)

**Comment by nasli** [comment]
:+1: @jancborchardt, if the first part is the display name, that is the best approach

**Comment by jesmrec** [comment]
I agree with using this "style"

**Comment by schiesbn** [comment]
So we all agree that the current approach is OK. If I missed something feel free to re-open.
