### ISSUE TITLE
\OC\Files hooks don't fire, for folder which only contains folders

### ISSUE THREAD

**Issue by karakayasemi** [owncloud/core#23360]
I writed an app that changes file ownership on the filesystem to actual ldap user who uploaded or created new files and folders. The reason why I done that is wanted to use linux filesystem quota for some reasons. 

To achieve this I used files hooks explained in the <a href="https://doc.owncloud.org/server/8.2/developer_manual/app/hooks.html?highlight=hook">Developper Manual 8.2</a>

In the app, I used postWrite and postCreate hooks to listen write and create events.

In my tests, I realized that if I uploaded a folder which contains only folders, but inner folders may have files and folder, hooks does not fire for only mentioned type folders.

I would see this as bug. Any help is very welcome...

### Steps to reproduce
1. Create a new folder
2. Create new subfolder inside the created folder in first step
3. Create a file in inside the created folder in second step
4. Drag and drop created folder in first step to web client
5. Listen postWrite and postCreate hooks

### Expected behaviour
Hooks should fire for all elements 

### Actual behaviour
Hooks does not fire for created folder in first step which contains only folder, for other elements it works fine.

### Server configuration
**Operating system**: RHEL 7.2
**Web server:** apache
**Database:** postgresql
**PHP version:** 5.4
**ownCloud version:** (see ownCloud admin page) 8.2.2
**Updated from an older ownCloud or fresh install:** fresh install
**Where did you install ownCloud from:** OwnCloud Rhel repos
**Are you using an external user-backend, if yes which one:** ActiveDirectory

**Comment by PVince81** [comment]
> Drag and drop created folder in first step to web client

Ok, so you used Chrome's special "upload folder" feature ?
I thought that when folders are empty it didn't work.

I suppose that folder creation should at least fire a post_create hook,

**Comment by PVince81** [comment]
Looks like when dropping only empty folders, the ajax/upload code doesn't run at all. So no wonder no hooks are triggered at all.

**Comment by PVince81** [comment]
Does it work if you manually create a folder in the web UI using the "New" menu ? And through Webdav ?

**Comment by karakayasemi** [comment]
I tested create a folder in the web UI and it worked, also i tried the problematic case with webdav, also it worked.

**Comment by PVince81** [comment]
Yeah, I think it's specific to the "folder upload" feature of Chrome. The code goes through ajax/upload.php which itself only cares about uploading the files and create the parent folders.
It looks like the parent folder creation might not go through the usual `mkdir` code, which is why the hooks aren't trigger. A quick look at ajax/upload.php didn't tell me where the folder is actually created.
Needs further research.

**Comment by karakayasemi** [comment]
Today i checked out ajax/upload.php to detect problematic part. In files/view.php fromTmpFile function, usual mkdir call is only working for file's parent directory. Does not care upper parent folders. I added a recursive function that creates parent non-existing folders and it works.
