### ISSUE TITLE
Addressbook sharing model

### ISSUE THREAD

**Issue by gvde** [owncloud/core#23375]
I wonder whether the current addressbook sharing model is really the best way to go.

Currently, any user can share an address book with another user/group. Just by sharing the address book "contacts", the recipients get a new addressbook called "contacts_shared_by_name" in their collection. The ACL of that new addressbook are "faked" to match whether the recipient may edit the content or not. The recipient sees everything from the original addressbook, however, IMHO these are two different addressbooks:

/addressbooks/user1/contacts
/addressbooks/user2/contacts_shared_by_user1

Moreover, user2 cannot do anything about the existence of that new shared address book. user1 just "pushes" into the collection of user2. If user1 shared 10 address books all ten would appear in the user2 collection. Worse: for clients like the OS X client which currently only (randomly) picks a single address book from a user collection to show, user1 is able to mess it up for user2 just by sharing something. (Not to mention possible side effects like searches etc. which go through all address books in a collection even though the user may only want to use some.)

I think, the "proper" way to handle that would be this:

1: sharing: if user1 wants to share something, all this really does is change the acl on an object. Thus, if user1 wants to grant read access /addressbooks/user1/contacts to user2 (i.e. share read-only with user2) this operation would just amend the acl of /addressbooks/user1/contacts with the read privilege for /principals/users/user2. That's it. As far as I understand the sabredav documentation, sabredav takes care to enforce those acls...

Thus, user1 can now tell user2 via e-mail or any other way that user2 is allowed to read /addressbooks/user1/contacts. Thus, for both users it's the same object with the identical uri on the same server.

2: user2 can create (multiple) addressbook collections (addressbookhomes) at will and add address books, either created by user2 or added by URI from someone else, i.e. an address book collection of user2 may contain addressbooks like this:

/addressbooks/user2/contacts
/addressbooks/user2/morecontacts
/addressbooks/user1/contacts

This way, user2 has full control which address books are actually in his collection. If someone shares an addressbook with him it's still up to user2 to add the address book or not.

3: Likewise, this would "directories of public addressbooks" where users can pick useful addressbooks or maybe even browse through the addressbook collections of other users (if that other user opened it for access).

This way, it uses the ACL for enforcement and the recipient of shared address book won't gets it pushed into his collection. Moreover, I think it's clearer for everyone if the same addressbook is always accessed through the same URI instead of two different ones.

Plus, user2 can may create his own address book "contacts_shared_by_user1" without getting into the way of an address book shared by user1. ;-)

I currently don't use calendars thus don't know about that, but of course, the same may apply there, too...

**Comment by LukasReschke** [comment]
cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
The acl of the original resource is adopted as well and it is possible for the share recipient to use that resource location as well.
The shared resource is moved into the home location to have an easier lookup and discovery.
Furthermore this was necessary with respect to migration from the previous versions.

Regarding the home polution issue: I want to implement notifcations in the future so that a user first has to accept the share before it is really shared with the user.

@gvde sorry for the short response - but I hope this brings more understanding about the current implementation.

**Comment by gvde** [comment]
Well, I think there should be an easy way for lookup and discovery anyway. Thus, I would say it's better to build a mechanism how the user can find and add public/shared objects to his collection (in addition to adding a link). 

Notifications may be nice if it's a user to user share to help sending out the link. But, for instance, if you share with a group this won't work: suppose you add someone later to the group. How does the new member know about the shared object?

In addition, I don't think it will scale. Suppose you shared a larger number of objects, then the user needs to decide immediately whether or not to accept the share. But how should the user know about it later, after he rejected the share initially.

For instance, we would like to set up shared calendars for our office meeting rooms. Each room is a separate calendar so that you can use the availability of some clients. For this to work, you need a way do discover/browser public/shared calendars and the user must be able to pick which he is interested in. It must be easily possible to review this and add/remove calendars of interest.

I don't see how notifications and pushing "linked" objects into the user collection will really work in the long run...
