### ISSUE TITLE
Open sidebar when clicking in the right part of rows in files view

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#23381]
### Steps to reproduce

1. Having a file or folder uploaded, try to open sidebar clicking at the right of the three dots.

### Expected behaviour
Sidebar opens.

I'd expect specially that the sidebar opens in the orange area:

![screen shot 2016-03-18 at 08 59 22](https://cloud.githubusercontent.com/assets/9048796/13872198/e29bab8c-ece8-11e5-8ae0-1c46b6c2cc58.png)

But perhaps it is interesting to allow opening sidebar in the pink area as well.

### Actual behaviour
Nothing happens.

**Comment by SergioBertolinSG** [comment]
cc @owncloud/designers

**Comment by PVince81** [comment]
setting to junior job, should be a matter of adjusting the click selector

**Comment by jancborchardt** [comment]
Yup! Just for the record I support this. ;) And it seems a great junior job.

**Comment by ErikPel** [comment]
I just checked it out and got it working. Right now it opens the sidebar on the size and date fields but not the share and ellipsis button. Is this enough or should I include those two as well?

@jancborchardt @SergioBertolinSG

**Comment by SergioBertolinSG** [comment]
@ErikPel what about the orange section in the picture?

**Comment by ErikPel** [comment]
@SergioBertolinSG like half way but the other half is taken by the ellipsis button padding. I could get it working by taking the right padding off the ellipsis button and adding it into padding-left of the size part but thought I'd ask first if there is a better way. Feels really dirty doing such thing for simple change like this.

**Comment by SergioBertolinSG** [comment]
@ErikPel ok, could you prepare a PR so we can test/review it?.

**Comment by jancborchardt** [comment]
@ErikPel do you want to be added to the owncloud-designers team? :)
