### ISSUE TITLE
owncloud 9 (error: could not generate a preview of this file) If the picture is into cifs share and reshared

### ISSUE THREAD

**Issue by husisusi** [owncloud/core#23407]
### Steps to reproduce
1. Mount cifs share 
2. Re-share this CIFS Folder
3. Find one Image (picture) in this shared cifs share and try to open it (Preview) 
4. error: could not generate a preview of this file
### Expected behaviour

Thumbnails is visibile of photos
A preview of the opened photo should appear.
### Actual behaviour

Thumbnails is visibile of photos, but  No preview appears (Size of photo does not matter),  instead on the top of the page: "error: could not generate a preview of this file"
### Server configuration

**Operating system**:
Debian 8.3

**Web server:**
nginx/1.6.2
**Database:**
mysql  Ver 14.14
**PHP version:**
PHP 5.6.17
**ownCloud version:** (see ownCloud admin page)
OC 9
**Updated from an older ownCloud or fresh install:**
Update
**Where did you install ownCloud from:**
https://download.owncloud.org/community/owncloud-9.0.0.tar.bz2
**Signing status (ownCloud 9.0 and above):**
All checks passed
the results here.
No errors have been found

**List of activated apps:**
 activity
 comments
 dav
 external
 federatedfilesharing
 federation
 files
 files_external
 files_pdfviewer
 files_sharing
 files_texteditor
 files_trashbin
 files_versions
 files_videoplayer
 firstrunwizard
 gallery
 notifications
 provisioning_api
 systemtags
 templateeditor
 updatenotification
 user_ldap

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => 'pass',
  'secret' => 'pass',
  'trusted_domains' => 
  array (
    0 => 'https://myURL',
  ),
  'datadirectory' => '/data',
  'overwrite.cli.url' => 'https://myURL',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'nameofDB',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XY',
  'dbpassword' => 'some',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => 2,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'smtp DNS',
  'mail_smtpport' => 'port',
  'mail_from_address' => 'someting',
  'mail_domain' => 'my domain',
  'mail_smtpsecure' => 'tls',
  'memcache.local' => '\OC\Memcache\APCu',
  'trashbin_retention_obligation' => 'auto',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes: smb
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes: LDAP
#### LDAP configuration (delete this part if not used)

 hasMemberOfFilterSupport        1  
 hasPagedResultSupport  
 homeFolderNamingRule  
 lastJpegPhotoLookup            0  
 ldapAgentName                  domain\user  
 ldapAgentPassword              ******\*  
 ldapAttributesForGroupSearch  
 ldapAttributesForUserSearch  
 ldapBackupHost  
 ldapBackupPort  
 ldapBase                       dc=ad1, dc=domain, dc=com  
 ldapBaseGroups                 dc=ad1, dc=domain, dc=com  
 ldapBaseUsers                  dc=ad1, dc=domain, dc=com  
 ldapCacheTTL                   600  
 ldapConfigurationActive        1  
 ldapDynamicGroupMemberURL  
 ldapEmailAttribute             mail  
 ldapExperiencedAdmin           0  
 ldapExpertUUIDGroupAttr  
 ldapExpertUUIDUserAttr  
 ldapExpertUsernameAttr  
 ldapGroupDisplayName           cn  
 ldapGroupFilter                (&((objectclass=group))((cn=Domänen-Benutzer))) 
 ldapGroupFilterGroups          Domänen-Benutzer  
 ldapGroupFilterMode            1  
 ldapGroupFilterObjectclass     group  
 ldapGroupMemberAssocAttr       member  
 ldapHost                       IP address  
 ldapIgnoreNamingRules  
 ldapLoginFilter                (&(&((objectclass=user)))(samaccountname=%uid))  
 ldapLoginFilterAttributes  
 ldapLoginFilterEmail           0  
 ldapLoginFilterMode            1  
 ldapLoginFilterUsername        1  
 ldapNestedGroups               0  
 ldapOverrideMainServer  
 ldapPagingSize                 500  
 ldapPort                       389  
 ldapQuotaAttribute  
 ldapQuotaDefault  
 ldapTLS                        1  
 ldapUserDisplayName            displayname  
 ldapUserDisplayName2  
 ldapUserFilter                 (&((objectclass=user)))  
 ldapUserFilterGroups  
 ldapUserFilterMode             0  
 ldapUserFilterObjectclass      user  
 ldapUuidGroupAttribute         auto  
 ldapUuidUserAttribute          auto  
 turnOffCertCheck               0  
 useMemberOfToDetectMembership  1                 
### Client configuration

**Browser:**
Firefox, Chrome
**Operating system:**
Linux, Windows
#### Web server error log

No errors and nothing important
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```

Exception: {"Exception":"OCP\Files\NotFoundException","Message":"File with id \"7993\" has not been found.","Code":0,"Trace":"#0 \/var\/www\/html\/oc\/apps\/files_sharing\/lib\/sharedstorage.php(82): OC\Files\View->getPath(7993)\n#1 \/var\/www\/html\/oc\/apps\/files_sharing\/lib\/sharedstorage.php(570): OC\Files\Storage\Shared->init()\n#2 \/var\/www\/html\/oc\/lib\/private\/files\/storage\/wrapper\/wrapper.php(381): OC\Files\Storage\Shared->getCache('', Object(OCA\Files_Trashbin\Storage))\n#3 \/var\/www\/html\/oc\/lib\/private\/files\/cache\/scanner.php(88): OC\Files\Storage\Wrapper\Wrapper->getCache()\n#4 \/var\/www\/html\/oc\/apps\/files_sharing\/lib\/sharedstorage.php(581): OC\Files\Cache\Scanner->__construct(Object(OCA\Files_Trashbin\Storage))\n#5 \/var\/www\/html\/oc\/lib\/private\/files\/storage\/wrapper\/wrapper.php(395): OC\Files\Storage\Shared->getScanner('', Object(OCA\Files_Trashbin\Storage))\n#6 \/var\/www\/html\/oc\/lib\/private\/files\/utils\/scanner.php(125): OC\Files\Storage\Wrapper\Wrapper->getScanner()\n#7 \/var\/www\/html\/oc\/apps\/files\/lib\/backgroundjob\/scanfiles.php(87): OC\Files\Utils\Scanner->backgroundScan('')\n#8 \/var\/www\/html\/oc\/apps\/files\/lib\/backgroundjob\/scanfiles.php(111): OCA\Files\BackgroundJob\ScanFiles->runScanner(Object(OC\User\User))\n#9 \/var\/www\/html\/oc\/lib\/private\/backgroundjob\/job.php(52): OCA\Files\BackgroundJob\ScanFiles->run(NULL)\n#10 \/var\/www\/html\/oc\/lib\/private\/backgroundjob\/timedjob.php(53): OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))\n#11 \/var\/www\/html\/oc\/cron.php(163): OC\BackgroundJob\TimedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))\n#12 {main}","File":"\/var\/www\/html\/oc\/lib\/private\/files\/view.php","Line":1639} 

Undefined offset: 0 at /var/www/html/oc/apps/gallery/environment/environment.php#200
 Exception: Could not locate file linked to ID: 7994 
#### Browser log

No Errors

**Comment by PVince81** [comment]
@oparoz @georgehrke wasn't there a duplicate ?

**Comment by oparoz** [comment]
@PVince81 - I don't recall... Looking at the logs, maybe the cache is out of date since the files is 404?

@husisusi - One thing to remember is that having a thumbnails is not a good indicator of if the filesystem is available and ready as those are store locally. It could be that this storage location had problem when you tried to open the preview. Are you able to download the images?

**Comment by husisusi** [comment]
Yes, I can Download the images.

**Comment by husisusi** [comment]
Okey! I have some news,

This issue is present, just if Max mount cifs share and  re-share it with someone (John), Max can open the preview without any issue but John can not open the preview ("error: could not generate a preview of this file")

Max is Local User and John is LDAP User!

**Comment by PVince81** [comment]
@husisusi can you try again with 9.1.0 beta 2 ? Could be similar to https://github.com/owncloud/core/issues/21173 which was fixed there.

**Comment by PVince81** [comment]
Please reopen if the issue still exists in the upcoming 8.2.6, 9.0.3 or the current 9.1.0 beta2.
The PR that might fix this is here: https://github.com/owncloud/core/pull/24564

**Comment by husisusi** [comment]
No, Version 9.1 beta 2 did not fix this issue.

**Comment by PVince81** [comment]
Too bad. Thanks, reopening then.

**Comment by macmadness86** [comment]
For the record, I have the same issue!

**Comment by vegas23** [comment]
+1 same issue. ver 9.1

**Comment by PVince81** [comment]
If upgrading to PHP 7.0 fixed the issue then this is likely an environment problem. Could also be related to the php-libsmbclient version used.

Closing as env issue. Please reopen if it still happens with latest PHP versions, latest php-libsmbclient module (0.9.0), with 10.0.4.
