### ISSUE TITLE
Expose storage / mount point properties via webdav

### ISSUE THREAD

**Issue by butonic** [owncloud/core#23406]
The client could react to the properties and use different sync intervals for different types of storage, probably read comments and tags, implement different sync algorithms, ...just an Idea.

Cc @DeepDiver @dragotin

**Comment by butonic** [comment]
Would also enable checksumming, end2end encryption, .... per folder, basically.

**Comment by PVince81** [comment]
Sounds good

**Comment by PVince81** [comment]
currently we already have the "M" permission (yeah, that really should be a separate property...) and desktop clients understand that these are external storages and react accordingly (they ask additional confirmation whether the user wants to sync those)
