### ISSUE TITLE
Allow an admin to change the data folder location on the server after installation

### ISSUE THREAD

**Issue by SamEliotFisher** [owncloud/core#23408]
Or simply provide a 'How-to' explaining how to do it.

**Comment by RealRancor** [comment]
See: https://github.com/owncloud/documentation/pull/1588

There needs to be two issues sorted out before this can be supported: https://github.com/owncloud/core/issues/18134, https://github.com/owncloud/core/issues/20628

**Comment by MorrisJobke** [comment]
I'm closing as @RealRancor answered this.
