### ISSUE TITLE
After upgrading from 8.2.2 to 8.2.3.2 WebDAV does not work any more.

### ISSUE THREAD

**Issue by tps800** [owncloud/core#23405]
### Steps to reproduce
1. Install OwnCloud, Configure OwnCloud, Configure LDAP access
2. Upgrade from 8.2.2 to 8.2.3
3. 
4. 

### Expected behaviour
webdav working

### Actual behaviour
webdav not working any more. Lots of errors 503 (503 Service Unavailable) in logs.
owncloud clients do not work any more too, as doesn't work WebDAV mounts on linux or Windows.

accessing the WebDAV URL given on pages https://<server>/owncloud/remote.php/webdav/ leads to message: "App not installed: dav". But: I was not able to find any app called "dav"!

Searching for this message gave back various issues with caldav, but nothing useful related to webdav.

WebDAV worked until the upgrade to available rpms in http://download.owncloud.org/download/repositories/8.2/CentOS_6

### Client configuration
**Operating system:** Ubuntu 14.04.5 LTS

**OwnCloud Client:** nightly

**Operating system:** Windows 7 Pro

**OwnCloud Client:** nightly

**Operating system:** Windows 10 Pro

**OwnCloud Client:** nightly

### Server configuration
**Operating system:** Oracle Linux 6.7

**Web server:** Apache 2.2.15-47.0.1

**Database:** PostgreSQL 9.5.0-1

**PHP version:** PHP 5.6.18-1
```
php56w-5.6.18-1.w6.x86_64
php56w-bcmath-5.6.18-1.w6.x86_64
php56w-cli-5.6.18-1.w6.x86_64
php56w-common-5.6.18-1.w6.x86_64
php56w-dba-5.6.18-1.w6.x86_64
php56w-devel-5.6.18-1.w6.x86_64
php56w-enchant-5.6.18-1.w6.x86_64
php56w-fpm-5.6.18-1.w6.x86_64
php56w-gd-5.6.18-1.w6.x86_64
php56w-imap-5.6.18-1.w6.x86_64
php56w-intl-5.6.18-1.w6.x86_64
php56w-ldap-5.6.18-1.w6.x86_64
php56w-mbstring-5.6.18-1.w6.x86_64
php56w-mcrypt-5.6.18-1.w6.x86_64
php56w-mysql-5.6.18-1.w6.x86_64
php56w-opcache-5.6.18-1.w6.x86_64
php56w-pdo-5.6.18-1.w6.x86_64
php56w-pear-1.10.1-1.w6.noarch
php56w-pecl-apcu-4.0.10-1.w6.x86_64
php56w-pecl-geoip-1.0.8-1.w6.x86_64
php56w-pecl-igbinary-1.2.1-2.w6.x86_64
php56w-pecl-imagick-3.4.0-0.1.RC4.w6.x86_64
php56w-pecl-memcache-3.0.8-2.w6.x86_64
php56w-pecl-redis-2.2.7-1.w6.x86_64
php56w-pgsql-5.6.18-1.w6.x86_64
php56w-process-5.6.18-1.w6.x86_64
php56w-pspell-5.6.18-1.w6.x86_64
php56w-recode-5.6.18-1.w6.x86_64
php56w-snmp-5.6.18-1.w6.x86_64
php56w-soap-5.6.18-1.w6.x86_64
php56w-tidy-5.6.18-1.w6.x86_64
php56w-xml-5.6.18-1.w6.x86_64
php56w-xmlrpc-5.6.18-1.w6.x86_64
php-pear-MDB2-2.5.0-0.9.b5.el6.noarch
php-pear-MDB2-Driver-mysqli-1.5.0-0.8.b4.el6.noarch
php-pear-Net-Curl-1.2.5-4.el6.noarch
```

**redis version:** redis-2.4.10-1

**ownCloud version before upgrade:** owncloud-8.2.2-1.1

**ownCloud version after upgrade:** owncloud-8.2.3.2

**Updated from an older ownCloud or fresh install:** Upgrade from 6.5

**Where did you install ownCloud from:** stable repos at http://download.owncloud.org/download/repositories/8.2/CentOS_6

```
Login as admin user into your ownCloud and access 
http://<server>/index.php/settings/integrity/failed 

Result:
jumps to https://<server>/owncloud/index.php/apps/files/

```

**List of activated apps:**
* Enabled:
 - activity: 2.3.0
 - announcementcenter: 1.0.2
 - dashboard: 1.1
 - documents: 0.11.1
 - files: 1.5.1
 - files_external: 0.6.0
 - files_gpxviewer_extended: 1.4
 - files_locking:
 - files_mv: 0.8.1a
 - files_pdfviewer: 0.8
 - files_share_qr: 0.1
 - files_sharing: 0.10.0
 - files_texteditor: 2.1
 - files_trashbin: 0.9.0
 - files_versions: 1.3.0
 - files_videoviewer: 0.1.3
 - galleryplus: 14.4.0
 - notifications: 0.3.0
 - ownnote: 1.07
 - passwordpolicy: 2.0.0
 - provisioning_api: 0.5.0
 - templateeditor: 0.1
 - user_ldap: 0.9.0
* Disabled:
 - EagleEye
 - encryption
 - external
 - firstrunwizard
 - gallery
 - imprint
 - updater
 - user_external

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '<server1>.<local1>.<domain1>',
    1 => '<server2>.<local2>.<domain2>',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '8.2.3.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => '',
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => '/owncloud',
  'secret' => '',
  'redis' => array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'proxy' => 'proxy-lb:8080',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
* Windows XP/7/8:
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (stable)
 * lynx (from cygwin)
 * w3m (from cygwin)
* Linux (Debian, Ubuntu 12.04/14.04/14.10, Fedora 19/20/21, Oracle Linux 6.5/7.0)
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (last available)
 * Konqueror (stable)
 * lynx (stable)
 * w3m (stable)

#### PHP
```
#
# PHP is an HTML-embedded scripting language which attempts to make it
# easy for developers to write dynamically generated webpages.
#
<IfModule prefork.c>
  LoadModule php5_module modules/libphp5.so
</IfModule>

<IfModule !prefork.c>
  LoadModule php5_module modules/libphp5-zts.so
</IfModule>

#
# Cause the PHP interpreter to handle files with a .php extension.
#
AddHandler php5-script .php
AddType text/html .php

#
# Add index.php to the list of files that will be served as directory
# indexes.
#
DirectoryIndex index.php

#
# Uncomment the following line to allow PHP to pretty-print .phps
# files as PHP source code:
#
#AddType application/x-httpd-php-source .phps

#
# Apache specific PHP configuration options
# those can be override in each configured vhost
#
php_value session.save_handler "files"
php_value session.save_path    "/var/lib/php/session"
php_value soap.wsdl_cache_dir  "/var/lib/php/wsdlcache"
```

#### owncloud
```
Alias /owncloud "/var/www/html/owncloud/"

<Directory /var/www/html/owncloud/>
  Options +FollowSymlinks
  AllowOverride All

 <IfModule mod_dav.c>
  Dav off
 </IfModule>

 SetEnv HOME /var/www/html/owncloud
 SetEnv HTTP_HOME /var/www/html/owncloud

</Directory>
```

#### Web server error log
```
10.160.2.12 - - [19/Mar/2016:00:05:43 +0100] "POST /owncloud/index.php/heartbeat HTTP/1.1" 200 -
10.160.2.12 - - [19/Mar/2016:00:05:44 +0100] "GET /owncloud/index.php/apps/notifications HTTP/1.1" 304 2
141.52.49.56 - - [19/Mar/2016:00:05:49 +0100] "GET /owncloud/index.php/apps/notifications HTTP/1.1" 304 2
10.160.2.12 - sct-muc [19/Mar/2016:00:05:50 +0100] "GET /owncloud/status.php HTTP/1.1" 200 95
10.160.2.12 - sct-muc [19/Mar/2016:00:05:50 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 503 290
46.244.168.176 - sct-muc [19/Mar/2016:00:05:54 +0100] "GET /owncloud/status.php HTTP/1.1" 200 95
46.244.168.176 - sct-muc [19/Mar/2016:00:05:54 +0100] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 503 290
46.244.168.176 - - [19/Mar/2016:00:05:56 +0100] "GET /owncloud/index.php/apps/notifications HTTP/1.1" 304 2

```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Browser log
```

**Comment by RealRancor** [comment]
Mhh, strange. This App "dav" is only part of oC9.

Maybe try to disable all 3rdpary / non shipped apps first to see if they are causing this problem.

**Comment by tps800** [comment]
Tried it. Did not solve this issue. Same WebDAV broken.
Since you mentioned oC9 I've tried to upgrade to oC9 looked OK, but trying to access
https://<server>/owncloud just leads to
```
Not Found

The requested URL /var/www/html/owncloud/index.php was not found on this server.
```
The rpms within the repositories:
 * ce:stable.repo (installing oC 9.0.0-1.1)
 * ce:testing.repo (installing oC 9.0.0-3.1)

both lead to a nonfunctional website.

I've tried to setup a new server using oC 8.2.3.2 as available in ce:8.2.repo. Same result. WebDAV does not work as expected. I could not test if older setups are working, because these are not available any more.

**Comment by PVince81** [comment]
@jvillafanez can you confirm whether the CensOS 6 packages for 8.2.3 work properly ?

**Comment by MorrisJobke** [comment]
> I've tried to setup a new server using oC 8.2.3.2 as available in ce:8.2.repo. Same result. WebDAV does not work as expected. I could not test if older setups are working, because these are not available any more.

Could it be the case that those 8.2.3 packages contain 9.0.0 somehow? cc @jnweiger

**Comment by tps800** [comment]
Within ownCloud Database tables I found one called public.oc_appconfig. Inside this table there where entries "dav":
```
dav.enabled=no
dav.installed_version=0.2.1
dav.types=filesystem
```
after changing "dav.enabled=no" to "dav.enabled=yes" WebDAV started working again, but now throws an error "internal server error".

**Comment by jnweiger** [comment]
@MorrisJobke checked version.php in the centos 6 repo. $OC_Version = array(8,2,3,2);
Also the download-pages now expose the exact version numbers:
https://download.owncloud.org/download/repositories/ce:/8.2/owncloud/ when you choose an operating system.

**Comment by jnweiger** [comment]
@tps800 Would it work when you try https:///owncloud/index.html instead of https:///owncloud -- if so, that is a new issue with redirectr rules, compare here: https://github.com/owncloud/core/issues/23405

**Comment by MorrisJobke** [comment]
> https:///owncloud/index.htm

https://owncloud/index.php

**Comment by tps800** [comment]
The servers URL: 
- https://<server>/owncloud
- https://<server>/owncloud/index.html
- https://<server>/owncloud/index.php

all work as expected -- in all cases I am prompted with the login dialog or, if I was logged in already, with my accounts page.

Trying to access owncloud (with a web browser via:
- https://<server>/owncloud/remote.php/webdav/

I am prompted with error 500 and the message "Internal server error".
I can upload or download files and folders accessing owncloud with a web-browser. I cant access owncloud using webdav.

**Comment by MorrisJobke** [comment]
Could you run `./occ status`? just to be sure which version is installed.

**Comment by tps800** [comment]
```
# su - -s /bin/bash apache
-bash-4.1$ cd /var/www/html/owncloud
-bash-4.1$ ./occ status
  - installed: true
  - version: 8.2.3.2
  - versionstring: 8.2.3
  - edition:
```

**Comment by tps800** [comment]
No changes since. It is 8.2.3.2.

**Comment by PVince81** [comment]
@tps800 can you try disabling the "files_external" app if you're using external storages ? I suspect that an unavailable/broken storage might be causing the 503 in Webdav.

**Comment by tps800** [comment]
Tried upgrading:

PHP 5.5.21:
```
php56w-5.6.21-1.w6.x86_64
php56w-bcmath-5.6.21-1.w6.x86_64
php56w-cli-5.6.21-1.w6.x86_64
php56w-common-5.6.21-1.w6.x86_64
php56w-dba-5.6.21-1.w6.x86_64
php56w-devel-5.6.21-1.w6.x86_64
php56w-enchant-5.6.21-1.w6.x86_64
php56w-fpm-5.6.21-1.w6.x86_64
php56w-gd-5.6.21-1.w6.x86_64
php56w-imap-5.6.21-1.w6.x86_64
php56w-intl-5.6.21-1.w6.x86_64
php56w-ldap-5.6.21-1.w6.x86_64
php56w-mbstring-5.6.21-1.w6.x86_64
php56w-mcrypt-5.6.21-1.w6.x86_64
php56w-mysql-5.6.21-1.w6.x86_64
php56w-opcache-5.6.21-1.w6.x86_64
php56w-pdo-5.6.21-1.w6.x86_64
php56w-pear-1.10.1-1.w6.noarch
php56w-pecl-apcu-4.0.11-1.w6.x86_64
php56w-pecl-geoip-1.0.8-1.w6.x86_64
php56w-pecl-igbinary-1.2.1-2.w6.x86_64
php56w-pecl-imagick-3.4.2-0.1.w6.x86_64
php56w-pecl-memcache-3.0.8-2.w6.x86_64
php56w-pecl-redis-2.2.7-1.w6.x86_64
php56w-pgsql-5.6.21-1.w6.x86_64
php56w-process-5.6.21-1.w6.x86_64
php56w-pspell-5.6.21-1.w6.x86_64
php56w-recode-5.6.21-1.w6.x86_64
php56w-snmp-5.6.21-1.w6.x86_64
php56w-soap-5.6.21-1.w6.x86_64
php56w-tidy-5.6.21-1.w6.x86_64
php56w-xml-5.6.21-1.w6.x86_64
php56w-xmlrpc-5.6.21-1.w6.x86_64
php-pear-MDB2-2.5.0-0.9.b5.el6.noarch
php-pear-MDB2-Driver-mysqli-1.5.0-0.8.b4.el6.noarch
php-pear-Net-Curl-1.2.5-4.el6.noarch
```

ownCloud 8.2.4.2:
```
# su - -s /bin/bash apache
-bash-4.1$ cd /var/www/html/owncloud
-bash-4.1$ ./occ status
  - installed: true
  - version: 8.2.4.2
  - versionstring: 8.2.4
  - edition:
-bash-4.1$
```

Tried it: Server answers on URL: https://lasair.bfs.de/owncloud/remote.php/webdav/
> "App not installed"

with or without "external storage" or "external sites" active or inactive. It does not matter.

I have tried so far:
  * remove all /var/www/html/owncloud, reinstall
  * remove database, restore
  * setup a new server, copy data, restore database

As soon as I restore the database and data, WebDAV is not available any more. I'll find entries
```
"dav";"enabled";"no"
"dav";"installed_version";"0.2.1"
"dav";"types";"filesystem"
```
in table "public.oc_appconfig". Setting "no" to "yes" enables WebDAV, but leads to error 500 requesting URL: https://lasair.bfs.de/owncloud/remote.php/webdav/

Right after installing and initializing the database WebDAV is working. After restoring the Database and Data it is not working any more.

**Comment by PVince81** [comment]
Any more luck with 9.0.3 ? :frowning:

**Comment by tps800** [comment]
Yes!

2016-07-13 9:49 GMT+02:00 Vincent Petry <notifications@github.com>:

> Any more luck with 9.0.3 ? 😦
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/owncloud/core/issues/23405#issuecomment-232281602>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAq2zLcRKiVW8mydHMS-C7RKQP9UgPERks5qVJiTgaJpZM4H0TGm>
> .
>



-- 
Thomas

**Comment by DeepDiver1975** [comment]
> Yes!

sounds like case closed
