### ISSUE TITLE
Feature Request: URL links in oC Web Interface

### ISSUE THREAD

**Issue by mbressman** [owncloud/core#23417]
Hopefully this is also the right place for feature requests (if not, I apologize in advance).

Feature Request:
Internet/Web Shortcuts (.URL files, etc.) that are stored on oC, when clicked in the web interface will actually launch the web shortcut page (i.e. open a new tab or browser window with the associated URL for the shortcut) instead of downloading the .URL file to the local machine.

Further Explanation:
Basically, I put a lot of .URL files (which are basically just web/internet shortcuts) in my oC v8.2 and they work fine when launching from a local folder that is sync'ed to oC, but when you try and click on them in the oC web interface they just download the .URL file to the local computer and then you have to go find it and double-click on it to go to the associated web page. It'd be great to get it so that when you click on these internet/web .URL file shortcuts in the oC web interface instead of downloading they just open up the web page associated with the .URL internet/web shortcut.  Thanks!

Associated Forum Post Link:
https://forum.owncloud.org/viewtopic.php?f=36&t=34457

**Comment by MorrisJobke** [comment]
That will not be implemented in the ownCloud core. This is something for a special app. Maybe open this in the apps issue tracker: https://github.com/owncloud/apps/issues
