### ISSUE TITLE
After upgrading from 8.2.2 to 9.0.0 being shown Index of /xx/apps/files in browser

### ISSUE THREAD

**Issue by PartisanEntity** [owncloud/core#23415]
### Steps to reproduce
1. Manual upgrade from OC 8.2.2 to 9.0.0
2. Visit OS in the browser
3. Update/Upgrade checks are initiated
4. Reload when prompted to do so

### Expected behaviour
OC should display the usual frontend interface (for example showing you your list of files and folders)

### Actual behaviour
Instead it is displaying the contents of /apps/files

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS (server edition)

**Web server:**
Apache/2.4.7

**Database:**
mysql  Ver 14.14 Distrib 5.5.47, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 5.5.9-1ubuntu4.14

**ownCloud version:** (see ownCloud admin page)
9.0.0

**Updated from an older ownCloud or fresh install:**
Updated from OC 8.2.2

**Where did you install ownCloud from:**
Downloaded the .zip from: https://owncloud.org/install/# 

**Signing status (ownCloud 9.0 and above):**
See eblow

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess
	- FILE_MISSING
		- .user.ini

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f40e7ca19cd76ff922ccd164e38f4d73806f66170cafa202fb470be225c813b4b242f4321da8a01bef1329e300acf3d137dbcbff058c501f166a2619031fc651
                            [current] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
                        )

                )

            [FILE_MISSING] => Array
                (
                    [.user.ini] => Array
                        (
                            [expected] => 0a557e3cdca4c2e3675deed761d79d109011dcdebbd9c7f6429f1d3476938ec95729543d7384651d1d0c48e26c5024cc5f517445920915a704ea748bdb903c5f
                            [current] => 
                        )

                )

        )

)
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap

```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "occ90b90c0ea",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/home\/john\/public\/domain.at\/public\/ocfolder\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "ocsomething",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": 0,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "www.domain.at",
            "domain.at"
        ],
        "mail_from_address": "john",
        "mail_smtpmode": "php",
        "mail_domain": "domain.at",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No (unless you mean https:// in that case yes)

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chromium Version 48.0.2564.116 Ubuntu 14.04 (64-bit)

**Operating system:**
Ubuntu 14.04 LTS Desktop

#### Web server error log
```
Nothing useful.
```

### Additional Info
The desktop sync client is working fine.

**Comment by MorrisJobke** [comment]
@LukasReschke Another issue related to the removed index.php ;)

**Comment by LukasReschke** [comment]
Please retry with https://download.owncloud.org/community/owncloud-daily-stable9.tar.bz2, this is very likely already fixed.

**Comment by PVince81** [comment]
Closing due to lack of feedback. This is likely already fixed.

**Comment by gabrielklein** [comment]
I've tried with owncloud-daily-stable9.tar.bz2 with no success.

The android application and linux application are working without problems. The web interface redirects to apps/files/

I have Ubuntu 16.04, PHP 7.0, MySQL and no special things on the linux part.
I use "let's encrypt".
Everything is running over SSL/HTTPS.

<IfModule mod_ssl.c>
<VirtualHost *:443>

	ServerName mysite.ch
	ServerAlias www.mysite.ch

	DocumentRoot "/home/web/mysite.ch/"

	<Location />
		Order allow,deny
		Allow from all
	</Location>

       
        Alias /webcam "/home/webcam/site"
        <Directory "/home/webcam/site">
                Options Indexes FollowSymLinks MultiViews
                AllowOverride all
                Order allow,deny
                allow from all
        </Directory>


	ErrorLog /var/log/apache2/error-mysite.ch.log

	# Possible values include: debug, info, notice, warn, error, crit,
	# alert, emerg.
	LogLevel warn

	CustomLog /var/log/apache2/access-mysite.ch.log combined

SSLCertificateFile /etc/letsencrypt/live/mysite.ch/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/mysite.ch/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains
"
Header always set Content-Security-Policy upgrade-insecure-requests
</VirtualHost>
</IfModule>

**Comment by gabrielklein** [comment]
Ok stupid mistake :) but I'm sure it happens to other people too.

Ihave unbzip2 / untar the folder in a subdirectory.
The I have "mv mysubdir/* ownCloudDir/"

The .htaccess is not moved when you do that...

I hope it will help other people.
