### ISSUE TITLE
Calender shared with a group is not available over CalDAV.

### ISSUE THREAD

**Issue by fr4nk3nst3in** [owncloud/core#23414]
Steps to reproduce

    Share calendar with a usergroup
    CalDAV in IOS does not shows shared calendar
    If same calender shared with single user it shows
    Group shared Calender over OC GUI is available under the point Subscription.

Expected behaviour

In OC 8 it was possible to share a calendar with an usergroup and was available over CalDAV for all users in the group.
Actual behaviour

Shared calender over 'Group' is not available by using CalDAV. But shared Calendar over 'User' is not available by using CalDAV

**Comment by DeepDiver1975** [comment]
Duplicate
