### ISSUE TITLE
bad sunday - owncloud update issue

### ISSUE THREAD

**Issue by christianep** [owncloud/core#23410]
I thought I should do the update which was called out inthe header everytime I logged in.
I shouldn´t have done this ...
It was a owncloud 8.03 running well with one fault: Zip Container packed by this version had not been unzipped on any MacOS computer. Bad for me, because most people I share something are loving their macs.
Well update installation started well - then this information popped up:
## Exception: Updates between multiple major versions and downgrades are unsupported.
Since then it´s not possible to log in - this screen appears. 
Well I´ve did the backup - there are now two folders: 8.0.3.4-70b9510e.zip  and 8.2.1.4.zip
I downloaded both - the 8.2.1.4 seems to contain the newer version and - The 8.0.3. **THIS FOLDER CAN´T BE OPEN** - Windows says it seems to be corrupt.

Short question - is there any chance to get my original version back including all data and the appearance I made? And why the hell the installer doesn´t not check before he starts.
It´s running on a kind of linux, is hosted at 1und1.de and the adress ist ee-shares.de.

Regards Christian

**Comment by RealRancor** [comment]
Hi,

please see this FAQ how to do a correct upgrade: https://forum.owncloud.org/viewtopic.php?f=17&t=32087

To get more support please create a new thread at the forums and close here. The issue tracker here is only used for reporting bugs.

**Comment by christianep** [comment]
Hi Xenopathic, thanks for reply - probably I´you are on the right - but I think it´s a mistake when the update starts before checking wether it´s possible or not. And I performed it from OC inside, with the updater.
Nevertheless - I thank you for your response - have a great day! Regards Christian

**Comment by RealRancor** [comment]
Hi,

> but I think it´s a mistake when the update starts before checking wether it´s possible or not. And I performed it from OC inside, with the updater.

this is tracked since a longer time in https://github.com/owncloud/appstore-issues/issues/4

Hopefully it gets resolved someday
