### ISSUE TITLE
AWS S3 external storage, can't even browse contents

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/core#23416]
### Steps to reproduce
1. Configure AWS S3 external storage (through administration, shared on few groups and individual users, mounted into subdirectory `Tech/Samples/S3`)
2. Have some content in bucket
3. Open directory `Tech/Samples/S3` in ownCloud web interface

### Expected behaviour
List of files/directories in bucket

### Actual behaviour
504 gateway timeout in AJAX request and directory not opening

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Nginx 1.9.6

**Database:** MariaDB 10

**PHP version:** 5.6.10

**ownCloud version:** 8.2.3 (the same on 8.2.2, previous versions worked, probably, it was 8.2.1)

**Updated from an older ownCloud or fresh install:** Upgraded few times

**Where did you install ownCloud from:** Automated docker image: https://github.com/nazar-pc/docker-webserver-apps/tree/master/owncloud

**Signing status (ownCloud 9.0 and above):** None

**List of activated apps:**

```
Enabled:
  - activity: 2.1.4
  - calendarplus: 1.1.1
  - contacts: 0.5.0.0
  - delete_confirmation: 1.1.0
  - documents: 0.11.1
  - files: 1.2.1
  - files_external: 0.3.0
  - files_locking: 
  - files_mv: 0.8.2
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - galleryplus: 14.4.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - search_lucene: 0.6.0
  - tasksplus: 1.0.3
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - direct_menu
  - encryption
  - external
  - gallery
  - user_external
  - user_ldap
  - user_webdavauth
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc3sgcp9bcpo",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "x.y.z"
        ],
        "datadirectory": "\/data\/nginx\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/x.y.z",
        "dbtype": "mysql",
        "version": "8.2.3.2",
        "dbname": "owncloud",
        "dbhost": "mysql",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "xyz",
        "mail_domain": "x.y.z",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "xyz",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 0,
        "log_rotate_size": 2097152,
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** AWS S3

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:** Firefox Nightly

**Operating system:** Ubuntu 16.04

#### Web server error log
Multiple lines like this:
```
2016/03/21 00:10:41 [error] 6#6: *3005701 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.17.42.1, server: default_server, request: "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2FTech%2FSamples%2FS3 HTTP/1.0", upstream: "fastcgi://172.17.0.17:9000", host: "x.y.z"
2016/03/21 00:38:28 [error] 5#5: *436 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.17.42.1, server: default_server, request: "GET /index.php/apps/files/ajax/list.php?dir=%2FTech%2FSamples%2FS3&sort=name&sortdirection=asc HTTP/1.0", upstream: "fastcgi://172.17.0.17:9000", host: "x.y.z"
```

#### ownCloud log (data/owncloud.log)
Multiple lines like following:
```
{"reqId":"CzXYbsPopgPVhUVuX4M2","remoteAddr":"172.17.42.1","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'test_file' is not accessible or present !!!","level":0,"time":"2016-03-21T00:22:45+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/list.php?dir=%2FTech%2FSamples%2FS3&sort=name&sortdirection=asc"}
```

#### Browser log
Nothing in console, 504 on mentioned AJAX requests

Everything is available in AWS console and another Python app also with token, but in ownCloud I can't even browse contents, not even talking about synchronization.

**Comment by PVince81** [comment]
Amazon S3 mount seems to work fine for me. Are there lots of file in yours ?

**Comment by PVince81** [comment]
Tested in v8.2.3

**Comment by nazar-pc** [comment]
63 files/directories in the root of the bucket

**Comment by PVince81** [comment]
Ok, apparently from your logs you're getting timeouts.

If previous versions worked, it means that the performance got worse.

In the end, we really need to implement a stat cache for S3: https://github.com/owncloud/core/issues/13147#issuecomment-170495696

**Comment by nazar-pc** [comment]
Can you suggest any workarounds in the meantime? Maybe I can comment out certain non-critical features in source code to give it some boost?
Uploading files using Python script is very fast, but ownCloud reaches timeouts.

**Comment by PVince81** [comment]
Is Python/Webdav able to display the file list from S3 ?

**Comment by nazar-pc** [comment]
In Python script it took 1.0752899646759033 seconds to fetch and convert from iterator to list() list of files.

**Comment by PVince81** [comment]
Hmmmm, so there's something the web UI takes a long time to do which Webdav doesn't.

Can you check the browser's network console and see which of the calls is taking all the time / timing out ? I'd suspect the "ajax/list.php" call to be the one, but that's not too different from Webdav.

**Comment by nazar-pc** [comment]
Here is what happens:
![2016-03-22 21-27-07](https://cloud.githubusercontent.com/assets/928965/13965054/56060132-f075-11e5-8ec0-8fd2e1c9407b.png)

WebDav interface from ownCloud also suffers from the same issue, I can't open S3 directory through WebDav either (through Nemo file manager, Nautilus fork) while other directories can be opened quickly.

**Comment by PVince81** [comment]
Doesn't the python script use Webdav too ? Did you use https://github.com/owncloud/pyocclient or another tool ?

It looks like ajax/scan.php is taking forever, and also list.php takes more than a minute.

I suggest you try running `occ files:scan --all` (or `occ files:scan --path=$user/files/s3mount`) to do the full pre-scan of the contents. Once it has been scanned at least once, it should hopefully not need to rescan it completely to be usable.

CC @icewind1991 at some point we need a solution to prevent scans to take too long for huge storages

**Comment by nazar-pc** [comment]
By python script I meant direct connection to AWS S3 API, not to ownCloud.
Currently running `occ files:scan --all`, each file takes ~0.5-1s to scan.
Also I've noticed S3 scanning is done for each user with whom this directory is shared. Would be good to avoid duplicated scanning for exactly the same files over and over again.

**Comment by nazar-pc** [comment]
`occ files:scan --all` didn't change anything.

**Comment by PVince81** [comment]
which I interpret as "the web UI / webdav is still very slow in S3".

In the external storage settings, there is a cog icon with an option "Check for changes". Try setting that option to "Never". It should hopefully prevent the scanner to try detecting changes over and over again.

**Comment by nazar-pc** [comment]
Well, setting "Check for changes" to "Never" allowed me to escape timeout, now request takes 55455ms, which is on the edge of the timeout, but there is some progress definitely.
Can I also prevent to calculate size of mounted directories? I'm pretty sure I saw such option one day, but can't find it now.

**Comment by PVince81** [comment]
I think the size calculation is done as part of the scanning process. So if "occ files:scan" has finished, then the calculation should be done.

When uploading files there however, the size change would be propagated but that happens on the local database, not on S3. There is no option to disable size calculation, maybe you mixed it up with something else.

Another thing you can try, not sure if relevant: delete/rename the file "apps/files/ajax/scan.php" which might also trigger some scanning.

**Comment by nazar-pc** [comment]
Tried to rename - doesn't seem to affect anything.

**Comment by nazar-pc** [comment]
ownCloud instance was on server in another country. When migrated to AWS EC2 in the same region where S3 is located - AJAX response is 255ms, everything seems good so far. It would not scale nicely I guess, but there is quite some space for now to survive until cache is implemented.

**Comment by PVince81** [comment]
Good to hear. Closing in favor of https://github.com/owncloud/core/issues/13147#issuecomment-199730312 for the stat cache
