### ISSUE TITLE
Feature Request: Add events counter api

### ISSUE THREAD

**Issue by Loki3000** [owncloud/core#23418]
It's to be good to give applications the ability to return the number of unread events.
![menu](https://cloud.githubusercontent.com/assets/12333165/13912126/1fd4218e-ef53-11e5-9dff-e913c201459a.png)
Now I have to switch between apps during work or keep opened several apps at same time.

**Comment by MorrisJobke** [comment]
cc @owncloud/designers is this actually wanted?

cc @nickvergessen @PVince81

**Comment by nickvergessen** [comment]
Duplicate of https://github.com/owncloud/core/issues/15309
