### ISSUE TITLE
Code signing error, curl, no internet and missing owncloud.conf

### ISSUE THREAD

**Issue by adrianvg** [owncloud/core#23428]
This is a multiple issue report.
A post is also available on [https://forum.owncloud.org/viewtopic.php?f=38&t=34451&p=111141](https://forum.owncloud.org/viewtopic.php?f=38&t=34451&p=111141).
Please let me know if you need more info. Thanks.

### Steps to reproduce
1. Add new CentOS 6-repo to existing working and current OC8 installation.
2. # su -u apache ./occ upgrade --dryrun
3. # su -u apache ./occ upgrade
4. Restart httpd.
5. Login using the web-gui.

### Expected behaviour
Httpd starts with no errors.
No code-signing errors.
Previous avatar-image should be retained.

### Actual behaviour
* Httpd doesn't start because the /etc/httpd/conf.d/owncloud.conf is missing.
* Chosen avatar image disappears and the standard-image shows.
* Code-sign errors keep popping up. checksetupcontroller.php has been modified with respect to all urls pointing to http://www.owncloud.org. With that url set I get the curl error as well as the "this server is not internet connected". Changing the url to http://owncloud.org removes the curl and no internet-errors but instead gives me a code-sign error.
* The OC9 otherwise works fine both from web-gui and with the desktop sync clients as well as android clients.

### Server configuration
**Operating system**: CentOS 6.7 x64

**Web server:** Httpd

**Database:** MySQL

**PHP version:** 5.5

**ownCloud version:** 9.0.0 (stable)

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** CLI

**Signing status (ownCloud 9.0 and above):** ```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- settings/controller/checksetupcontroller.php
	- EXTRA_FILE
		- indie.json

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [settings/controller/checksetupcontroller.php] => Array
                        (
                            [expected] => a32731e01aab740a71285009cbeb38216f42388c7e4dfb6b2dc941a27690f19267dd99dc1408df91f395d9eb169112237f605f4e7df686d675224aa503b45cc9
                            [current] => 3e48bd17c89beee8940b3045553a4d7a1dbe720f6ce15e983dc2fd1638210971d5683197705ace5ab2397f54297afbc3b02c394b73133c2f5ae44f605b96691b
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [indie.json] => Array
                        (
                            [expected] => 
                            [current] => 09c52e4fec07e803f9cbd5526da5b378f98a70fb6a28bd7c6a6b1a654afae6e06a98756aca485da1be2f2adada58b6c52258ddb621386385e7926b54989d1799
                        )

                )

        )

)

```

**List of activated apps:**
```
Enabled:
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocfdfc96a2a2',
  'passwordsalt' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'xxx',
    1 => 'xxx',
    2 => 'xxx',
  ),
  'datadirectory' => '/home/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'installed' => true,
  'maxZipInputSize' => 5261334937.6000004,
  'allowZipDownload' => true,
  'forcessl' => false,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'php',
  'loglevel' => 3,
  'secret' => 'xxx',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'mail_from_address' => 'webmaster',
  'mail_domain' => 'xxx',
  'has_internet_connection' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'trashbin_retention_obligation' => '15, auto',
  'updatechecker' => false,
);


**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No


### ownCloud log (data/owncloud.log)
The log is 200 MB big. I'll attach it on request.

**Comment by PVince81** [comment]
> Httpd doesn't start because the /etc/httpd/conf.d/owncloud.conf is missing.

So did you create one ?

CC @jnweiger

**Comment by PVince81** [comment]
> This is a multiple issue report.

Every issue should be reported as a separate ticket.

But first let's fine out what you did with "owncloud.conf" in case this is what is causing all your issues.

**Comment by adrianvg** [comment]
Sorry. Wasn't sure whether to make three separate issues or just one. Lesson learned for next time.
In any case, I found an older owncloud.rpmsave-file from 2015 in that folder. Renamed the file to owncloud.conf and restarted httpd. Httpd then started up normally.

**Comment by PVince81** [comment]
Ok thanks.

> Chosen avatar image disappears and the standard-image shows.

Please make a separate ticket for this one.

> Code-sign errors keep popping up. checksetupcontroller.php has been modified with respect to all urls pointing to http://www.owncloud.org. With that url set I get the curl error as well as the "this server is not internet connected". Changing the url to http://owncloud.org removes the curl and no internet-errors but instead gives me a code-sign error.

Did you manually modify "checksetupcontroller.php" ? If you get code sign errors it means someone modified your code, this is expected.

@LukasReschke did the ownCloud servers have a glitch of some sorts recently ?

**Comment by LukasReschke** [comment]
> @LukasReschke did the ownCloud servers have a glitch of some sorts recently ?

This is just the well-known old bug in RHEL / CentOS => https://bugzilla.redhat.com/show_bug.cgi?id=1269855

**Comment by adrianvg** [comment]
@PVince81:
I will, thanks.

I did modify "checksetupcontroller.php" in order to resolve the curl- and no internet connected server-problem that @LukasReschke refers to. I don't see any other way to fix that.

**Comment by rice-ua** [comment]
Hi all,
I also have integrity check error without manual modification of files.
As I can see files on my laptop(Win8) and on server(CentOS 6.7) have different size but they contains the same data.
I don't get how it is possible.

Mykhailo

**Comment by adrianvg** [comment]
Code-signing errors disappeared after last OC-update, even though I still have the edits done as mentioned in the OP.
AFAIC, I'm fine now. Proceeding to make separate tickets for the other issues per instruction from @PVince81.

**Comment by MorrisJobke** [comment]
> AFAIC, I'm fine now. Proceeding to make separate tickets for the other issues per instruction from @PVince81.

Okay. Closing this ticket then ;)
