### ISSUE TITLE
OC9 - Calendar authentication credentials need to be re-entered because the calendar naming has changed

### ISSUE THREAD

**Issue by j-ed** [owncloud/core#23427]
## Expected behavior
After upgrading from OC8.2.2 to OC9.0 it should be possible to access and use all
CalDAV calendars without re-entering the authentication credentials.

## Current behavior
The authentication credentials for all subscribed calendars need to be re-entered
in e.g. Thunderbird/Lightning because the calendar naming has slightly been changed.

Example:
OC 8.x: https://your-server-url (**ownCloud** (Name of calendar))
OC 9.x: https://your-server-url (**sabre/dav** (Name of calendar)) 

#### Server Configuration
OS: Linux 3.2.75
Web server: Apache2 2.4.18
Database: MariaDB 5.5.46
PHP version: 5.6.17
ownCloud version: 9.0.0
Calendar app version: 1.0.0 (20160320)
Updated from OC8.2.2

#### Client Configuration
Browser: Thunderbird 38.7.0/Lightning 4.0.7
Operating system: Windows 7

**Comment by j-ed** [comment]
Moved from Calendar to Core section: https://github.com/owncloud/calendar/issues/352#issuecomment-199207159

**Comment by PVince81** [comment]
@DeepDiver1975 @georgehrke

**Comment by tslben** [comment]
Workaround is to add "$this->realm = 'ownCloud';" to the constructor in /var/www/owncloud/apps/dav/lib/connector/sabre/auth.php although now you'll get an integrity check failure.  Also you have to do it every time there is an OC upgrade.  
But at least you won't get calls from 100 users saying "What's this dialog when I start Thunderbird and what the hell is sabre/dav?"

**Comment by mbiebl** [comment]
I've been bitten by this too. Please consider fixing this in a 9.0 stable update
