### ISSUE TITLE
Use PHP interfaces for user backends (and not implementsAction magic)

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#23421]
- provide a proper interface for the user backend to be implemented
- currently you need to implement some stuff of `OCP\UserInterface` (which should be named UserBackend), `OC_User_Backend` and some magic methods that are defined here: https://github.com/owncloud/core/blob/933f60e3147ad872acf3211dc826ebf528434681/lib/private/user/backend.php#L83-L92

We should move all of the `implementsAction` magic into proper interfaces that then could be checked on a language level rather than some magic methods that return a binary string to announce what is implemented.

cc @blizzz @butonic We talked about this already.

**Comment by DeepDiver1975** [comment]
with 9.1 we want to introduce the central user account table - this will have major impact on the user backend interfaces - good point in time to cleanup

**Comment by DeepDiver1975** [comment]
move to 9.2

**Comment by labkode** [comment]
@DeepDiver1975 @MorrisJobke @PVince81 
What is the best way to implement an IUserBackend and IGroupBackend ?
The solution we have now is a patch of the user_ldap app but we would like to have our own implementations easily attachable like the sharing provider.

Our implementation will retrieve users and groups from a custom service.

Thanks in advance

**Comment by DeepDiver1975** [comment]
@labkode for user backend go this way:

```php
class CernUserBackend implements \OCP\IUserBackend implements \OCP\UserBackend {
}

**Comment by DeepDiver1975** [comment]
and for groups backend:

```php
class CernGroupBackend implements \OCP\GroupInterface {
}

**Comment by labkode** [comment]
@DeepDiver1975 Thanks a lot Thomas.
After implementing these interfaces, how can we connect them to ownCloud core? 
I have found these two methods:

```
\OC::$server->getGroupManager()->addBackend(\OCP\GroupInterface);
\OC::$server->getUserManager()->registerBackend(\OCP\UserInterface);
```

Is this the correct way to include our implementation?

**Comment by DeepDiver1975** [comment]
This is one option - but you can also use the config option - see https://github.com/owncloud/apps/tree/master/user_external#ftp

**Comment by labkode** [comment]
Thanks Thomas, that makes much more sense

**Comment by labkode** [comment]
@DeepDiver1975 Hi Thomas,

the user_external for users works really well out of the box, is there anything similar to plug-in our group backend with the same smoothness to avoid `\OC::$server->getUserManager()->registerBackend(\OCP\UserInterface);`?

**Comment by DeepDiver1975** [comment]
> the user_external for users works really well out of the box, is there anything similar to plug-in our group backend with the same smoothness to

no - not yet :see_no_evil:

**Comment by PVince81** [comment]
@jvillafanez oh, look what I found... as we were just talking about this in https://github.com/owncloud/core/pull/26750

I see at least three interfaces:
- methods for read-only group + members provider
- methods for read-write group management
- methods for read-write group members management

**Comment by jvillafanez** [comment]
> * methods for read-write group management
> * methods for read-write group members management

I don't see an use case where different interfaces are needed for this. If you are able to create a group, you should be able to populate it. Although you could add members to existing groups even though you can't create new groups... 🤔 

In any case, the naming and the inheritance tree (if any) must be as clear as possible.

**Comment by PVince81** [comment]
missed opportunity to cleanup.

Moving to backlog for now unless someone else finds time to clean this up as part of another task.
