### ISSUE TITLE
file transfer ownership has to take care about tags and comments

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#23423]
@karlitschek @cmonteroluque basically a missing feature in 9.0 - therefore backport requested

**Comment by karlitschek** [comment]
backport of what? :-) First this needs to be developed. Not sure someone can develop this before 9.1?
What do you think?

**Comment by cmonteroluque** [comment]
I would have thought a 9.1 addition, why would it take priority over critical or high bugs now?

**Comment by PVince81** [comment]
@DeepDiver1975 are you talking about personal tags ? System tags have no ownership.

Regarding comments, not sure if there is anything to transfer. The comments would appear with the author name "[deleted user]" or so, which is more accurate than to put that person's words into another user's mouth...

**Comment by DeepDiver1975** [comment]
@PVince81 under perfect conditions we have nothing to do with comments and tags - but it still requires at least testing

**Comment by PVince81** [comment]
@DeepDiver1975 so is this ticket now about adding integration tests for these cases ?

**Comment by PVince81** [comment]
@owncloud/qa we now have automated tests for transfer ownership, so let's also add cases with comments and tags. For now only system tags would be transferred due to file id preservation, but not comments. (as far as I remember)

**Comment by PVince81** [comment]
Just tested manually, both tags and comments are transferred.

Will add test cases in QA repo: https://github.com/owncloud/QA/issues/188
