### ISSUE TITLE
Check for existing job is expensive with many jobs

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#23420]
- having a `oc_jobs` table that has many thousand entries
- try to insert a new job (like the version or trashbin expiry job)
- following query is created: 

``` sql
SELECT `id` FROM `oc_jobs` WHERE `class` = 'OC\\Command\\CommandJob' AND `argument` = '\"O:33:\\\"OCA\\\\Files_Versions\\\\Command\\\\Expire\\\":2:{s:43:\\\"\\u0000OCA\\\\Files_Versions\\\\Command\\\\Expire\\u0000fileName\\\";s:90:\\\"PATH\\\";s:39:\\\"\\u0000OCA\\\\Files_Versions\\\\Command\\\\Expire\\u0000user\\\";s:21:\\\"USERNAME\\\";}\"'`
```

This query is send because the insert checks before adding a new job: https://github.com/owncloud/core/blob/35bc315f596ac1ec9a90f4245f627ce22e62b0fc/lib/private/backgroundjob/joblist.php#L56

And it is really slow, because it needs a full table scan. There is no index on class and argument, because this index is not possible with MySQL.

The better way of handling this is to have a unique constraint on class and argument and not check while adding the new job, but catching the UniqueConstraintViolationException and then all is fine. This should be a lot faster.

00005004

cc @nickvergessen @LukasReschke @PVince81 Do you think this makes sense?

**Comment by PVince81** [comment]
I guess that should be fine, yes.

CC @icewind1991

**Comment by nickvergessen** [comment]
Unique keys also have a max length on mysql I guess?!

**Comment by MorrisJobke** [comment]
> Unique keys also have a max length on mysql I guess?!

That would be the question.

**Comment by nickvergessen** [comment]
They are also indexes, just special.

Just tested:
> Specified key was too long; max key length is 767 bytes

So not sure what we can do against this.

**Comment by rullzer** [comment]
Can't we create a hash from the class and the arguments? Then we can index on the hash and compare only a few entries...

**Comment by nickvergessen** [comment]
Yeah we could, however when creating two jobs that have the same hash ... :speak_no_evil:

**Comment by rullzer** [comment]
@nickvergessen well that is fine right... the hash is just to filter and to omit the full table scan... basically turn it into a hash table...

**Comment by rullzer** [comment]
PR in #25100

**Comment by PVince81** [comment]
@cdamken can you check the matching case ?

I'd rather move this to 10.0 because the solution needs database structure changes which we cannot backport.

**Comment by PVince81** [comment]
Moving to 10.0 as this is not backportable.

**Comment by PVince81** [comment]
moving to 10.1

**Comment by cdamken** [comment]
> @cdamken can you check the matching case ?

We have a new case here:
https://github.com/owncloud/enterprise/issues/2144
