### ISSUE TITLE
Dancing links in sidebar when using a language with long words.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#23429]
### Observed behaviour:

![dancing_links](https://cloud.githubusercontent.com/assets/9048796/13916177/5c43495a-ef59-11e5-818c-0ac8a27779de.gif)
### Expected behaviour:

Like in english, fixed links.

**Version**
{"installed":true,"maintenance":false,"version":"9.0.0.19","versionstring":"9.0.0","edition":"Enterprise"}

**Comment by PVince81** [comment]
@owncloud/designers 

I suspect that the one pixel of the underline is triggering wrapping. Might need to replace the 0px border with an invisible 1px border to prevent jumpy behavior.

**Comment by jancborchardt** [comment]
Yup. But the general issue is that, well … there are 4 different tabs and hence the wrapping happens in the first place. ;) Will be fixed by the https://github.com/owncloud/core/issues/20259 (combined Activity tab)

**Comment by PVince81** [comment]
moved to more general UX group ticket: https://github.com/owncloud/core/issues/27578
