### ISSUE TITLE
remote-share notification: Add size information

### ISSUE THREAD

**Issue by dragotin** [owncloud/core#23438]
### Expected behaviour

The notification coming for the user to accept external shares should contain the size of the new share. Users on clients that sync need the information to decide if they want to accept the share, and/or if they really want to sync it or not. This is needed to provide a useful UX on the clients, as accepting the share and setting the checkmark to sync it right away or not should be one step for the user.
### Actual behaviour

The size is not available.

@hodyroff @CaptionF as we talked about it... 1.
@jancborchardt 
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
9.0.0
**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by dragotin** [comment]
@nickvergessen asked me to open this here rather than owncloud/notifications#73

**Comment by nickvergessen** [comment]
https://github.com/owncloud/notifications/issues/73#issuecomment-199256494
> Note: the size could change between initiating remote share and the recipient reading the notification. And then we would display false information.

### Steps
1. Create a new folder
2. Remote share it
3. Upload stuff into it

### Expected
A suitable size

### Actual
Would display 0, or we need to calculate the size everytime notifications are displayed. Also we therefor have to connect to a server which we might not want to (the user didn't accept it yet). So not sure how to best deal with this.

**Comment by dragotin** [comment]
I think the current size of the remote share at the point of time where the share was created is suitable as  a first step.

Could we return the current size again in the result of the Accept-Request? Then the client could compare the sizes and ask the user if the sizes differ too much.

**Comment by nickvergessen** [comment]
That would be in https://github.com/owncloud/core/blob/59028cced0a4f7377de9c22012c7624440b14a56/apps/files_sharing/api/remote.php#L77-L79

I think that should be possible, what do you think @schiesbn
