### ISSUE TITLE
hierarchical right structure for groups

### ISSUE THREAD

**Issue by zanglerecke** [owncloud/core#23432]
### Steps to reproduce
1. have a User X with a Folder, have a second User which is part of 2 different Groups
2. share a Folder with a Group A with just the right to view
3. share this Folder with Group B with all rights
### Expected behaviour

Expected behavior is that this User can edit/share... all of those shared files
### Actual behaviour

Acutual the user is not allowed to edit/share.... just the right to view is given
### Server configuration

**ownCloud version:8.2.3 as well as 9.0.0

one of the applications is in an sports club. 
there are Members, and there are photographer, but some of them are both.
a member should see all photos, a photographer should upload and share photos.
if a photographer is both, a member and a photographer, he should be able to upload/share photos as well, but actually the smaller rights of the member is "stronger". 
if there is a 3ed group (Video), or a administrativ group (just clubadministrator, not webadministrator) it is a lot more complicated.

in some wiki-sites those rights are easy to understand. 
https://www.dokuwiki.org/acl

**Comment by zanglerecke** [comment]
i just checked: if the person gets rights as a single person instead of a group-Permission, it workes. but it is much easier to just have groups for that.

**Comment by PVince81** [comment]
@rullzer possibly duplicate of that other ticket regarding merging of permissions ?

**Comment by zanglerecke** [comment]
i do not find any other ticket regarding that. can u post the issue Nr.?

**Comment by rullzer** [comment]
yes we are looking into this for the future work of sharing 2.0. But we need to move over the itnernals first.

Merging shares is on the agenda.
