### ISSUE TITLE
Manual deletion of file versions.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#23435]
Currently versions of files cannot be deleted manually, only automatically or using occ command.

I suggest to add a trashbin icon on every file version to being able to remove it manually.

![screen shot 2016-03-21 at 14 00 19](https://cloud.githubusercontent.com/assets/9048796/13919361/48af85d4-ef6d-11e5-8112-5c1a69a1422e.png)

**Comment by nickvergessen** [comment]
With respect to the trashbin cleanup settings, that might become fairly complicated:
https://github.com/owncloud/core/blob/8e70351bda4f547818574425b890b1f421b5c3ef/config/config.sample.php#L376-L413

**Comment by PVince81** [comment]
@pmaier1 is there a use case for deleting versions manually ?

**Comment by phil-davis** [comment]
The webUI  for the trashbin has the ability to either delete or restore items.

There does not seem to be an API for deleting versions.

It seems reasonable to me for a user to be able to delete useless versions. But maybe I am the only one?
