### ISSUE TITLE
Set flag in oc_preferences after copying skeleton files

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#23430]
It's pointless to copy skeleton files over and over again when the home folder got missing at login time.
Also, the current logic makes it very tricky to detect whenever an individual folder is missing temporarily.

I suggest that whenever the home folder is missing and before the skeleton gets copied, we make a call to `oc_preferences` to check for a "skeleton_done" flag. If the flag is there, throw `StorageNotAvailableException` for the home folder.
Else, create the skeleton.

@MorrisJobke @icewind1991

**Comment by PVince81** [comment]
Tricky part is the migration: go through every user and check if the home folder is there, if yes, set the flag to "oc_appconfig" once.

**Comment by PVince81** [comment]
Thinking of it, we already have a flag "lastLogin" in the `oc_preferences` table. If a value is there, it means the user logged in at least once, so they must have a home folder already (assuming that there was no error...)

**Comment by PVince81** [comment]
In general I think we should try and detect intermittent unavailable home storage in many places in the code, or at least the critical code paths that might delete important stuff.

**Comment by icewind1991** [comment]
I would prefer a separate entry for the skeleton, migration could be done per user after the current check if the skeleton is copied

**Comment by mmattel** [comment]
:+1:

**Comment by PVince81** [comment]
Would also help solve https://github.com/owncloud/core/issues/25212. It sometimes happen that some other process already puts files in the home.

**Comment by PVince81** [comment]
Solved differently on 9.2 already using the last login value and a "first login" hook, closing.

https://github.com/owncloud/core/pull/26206
