### ISSUE TITLE
Federated sharing for calendars and contacts

### ISSUE THREAD

**Issue by schiessle** [owncloud/core#23449]
I created a issue at the contacts app (https://github.com/owncloud/contacts/issues/258) and the calendars app (https://github.com/owncloud/calendar/issues/357) repository to illustrate the idea.

I'm not a CardDAV/CalDAV expert but from what I understand both protocols should support almost everything needed for federated sharing of calendars and address books. So most code would probably be part of core and the apps would just have to accept federated cloud ids at the share dialog and pass it over to core to create the share.

What do you think?

cc @DeepDiver1975

**Comment by schiesbn** [comment]
cc @georgehrke for your information :smile:

**Comment by DeepDiver1975** [comment]
I assume the expectation is that we really "suck in" the calendar and contacts information basically as a clone - right?

This can be rather easily implemented because this is what we do already with respect to syncing the system addressbooks of federated clouds.

**Comment by schiesbn** [comment]
> I assume the expectation is that we really "suck in" the calendar and contacts information basically as a clone - right?

Yes, my idea was to work similar to CardDAV/CalDAV desktop/mobile clients and just sync the calendars and contacts Think that's the best way, also for performance reasons.

**Comment by DeepDiver1975** [comment]
> Think that's the best way, also for performance reasons.

yes - indeed - nothing to argue about that! :+1:

**Comment by FuzzyH** [comment]
Hello

I am very interesiert on this functionality.
It would solve my curent Owncloud Problems
Dose someone know when it will be finished?

Good day
Fuzzy

**Comment by EmilObermayr** [comment]
Any news about this topic?
This would improve Owncloud a lot for me.

**Comment by didierm** [comment]
ping

**Comment by didierm** [comment]
ping
