### ISSUE TITLE
Old version for php-smbclient in CE repos

### ISSUE THREAD

**Issue by Trefex** [owncloud/core#23446]
It seems that in OC 8.2, in the CE repositories, the version supplied for php-smbclient is:

0.5.0

http://download.owncloud.org/download/repositories/8.2/CentOS_7/x86_64/

However, the latest version in EPEL is 0.8.0.

WIth version 0.5.0, I get following error when install from CE repos.

```
[root@lcsb-oc1-server ~]# php date;
PHP Warning:  PHP Startup: libsmbclient: Unable to initialize module
Module compiled with module API=20100525
PHP    compiled with module API=20131226
These options need to match
 in Unknown on line 0
Could not open input file: date
```

Is it safe to use 0.8.0 from EPEL ?

http://koji.fedoraproject.org/koji/buildinfo?buildID=740708

**Comment by PVince81** [comment]
Hmmm, on the openSUSE repos I get this version: php5-libsmbclient-0.7.0-4.1oc.x86_64

I agree that we should upgrade to 0.8.0 at some point.

However, not sure why the CE repos are still providing the old version ? @jnweiger @jmaciasportela @icewind1991

**Comment by Trefex** [comment]
@PVince81 can somebody explain to me which repos to use?

owncloud.org or opensuse? :)

**Comment by PVince81** [comment]
Use the ones from owncloud.org.

What I meant is that my distro is openSUSE and the packages provided from owncloud.org for my distro did contain the version 0.7.0.

**Comment by Trefex** [comment]
Ya and on EPEL, it's 0.8.0

I upgraded now to that version. In fact, I never had one installed, so I went straight to 0.8.0 

Thanks !

**Comment by jnweiger** [comment]
Hmm, looks like its time to delete php5-libsmbclient from 
http://download.owncloud.org/download/repositories/8.2/CentOS_7/x86_64/ ? 
what do you think?

**Comment by PVince81** [comment]
@owncloud/packaging is that still the case ?

**Comment by crrodriguez** [comment]
SMB client package was updated to version 0.8.0 succesfully A while ago, closing.
