### ISSUE TITLE
fdupes with opensuse packages put symlinks instead of files in package

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#23441]
### Steps to reproduce
1. Fresh install on opensuse or sles from packages
2.launch owncloud 
3. go to a file and look for the share icon

### Expected behaviour
The share icon should be displayed

### Actual behaviour
There is no share icon

### Server configuration
**Operating system**:
opensuse Leap
**Web server:**
apache
**Database:**
mariadb
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
9.0
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
packages

### Client configuration
**Browser:**
chrome, firefox etc...
**Operating system:**
linux, macos

@jnweiger  as researched with you this is caused by fdupes symlinks in apache

**Comment by Kawohl** [comment]
@hodyroff

**Comment by PVince81** [comment]
I had a similar issue on my server.

In the end the problem was that I didn't have the correct directives in my owncloud.conf.

@Kawohl please double check whether "FollowSymLinks" is properly set, see https://doc.owncloud.org/server/9.0/admin_manual/installation/source_installation.html#apache-web-server-configuration

**Comment by PVince81** [comment]
=> not a bug

**Comment by Kawohl** [comment]
@PVince81  i understand,

on the other hand the openSuse package is the only one using fdupes. 

Imho it is better to have one behaviour for all  packages  for all distros.... .  Extrastuff for each distro  makes it hard to maintain and the package size doesn't really matter in this case. So why just not deliver the images in all distros instead of dupes?

**Comment by PVince81** [comment]
rpmlint usually complains if you have duplicate files, but I guess we could ignore those warnings then ? @jnweiger

**Comment by jnweiger** [comment]
As long as it is a warning, we'll ignore it.
We need the packages consistent amongst each other and consistent with the tar archive.
If we want to deliver symlinked duplicates, we should run fdupes when building the tar archive. 

I don't see that we really want this. There is no benefit regarding size. 
A general 'FollowSymlinks' allows apache to walk outside the webroot. This is a security implication.

https://github.com/owncloud/administration/commit/bc61bc5aba897e0e8aa22e45a3603cfba4656240
removes the fdupes call from the templates.

**Comment by jnweiger** [comment]
https://obs.int.owncloud.com/package/show/ce:9.0:testing/owncloud-files has the fix. Publishing in https://download.owncloud.org/download/repositories/testing/owncloud/
