### ISSUE TITLE
9.1: Anti Brute Force for Authentication

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#23459]
# Bruteforce prevention
## Requirements

Bruteforcing ownCloud credentials should not be feasible easily.
Should be possible to disable by an administrator.
## Technical implementation

Has to be implemented as an application. Core should offer support for bruteforce protection providers, this has the advantage that anybody who wants can implement their own protection. (e.g. querying for the trust of the IP etc…)
## Recommendations

This is a tough topic, basically the widely used approach is:
1. Check if user has provided valid credentials
2. If not: Block IP after a specific amount of requests

The problem being here is that ownCloud supports also APIs such as DAV which brings us the problem that in case somebody changes the password the user would be locked-out directly. We do not have CSRF tokens on such endpoints. Neither can we employ anything like a captcha.

Personally, I’d couple this together with the “enforce application specific passwords” switch in the config file. It allows us at least to implement this securely without risking a DoS vector. Once we are so far to make this default for new installations this will also enhance the security of all new ownCloud’s.

This gives us the advantage of:
Login endpoint has no CSRF => User cannot be locked out
Application Specific Passwords are long => Cannot be guessed.

**Comment by RealRancor** [comment]
@MTRichards Looks like this is tracked for oC 9.1 here: https://github.com/owncloud/core/issues/1580

**Comment by MTRichards** [comment]
Excellent, thank you. too many issues!

**Comment by MTRichards** [comment]
Estimation: 3 days

**Comment by rperezb** [comment]
@PVince81 what is the status of this one? curious for @owncloud/qa

**Comment by PVince81** [comment]
Feature didn't make it into 9.1, moving to 9.2 for now to reconsider.

@dragotin @DeepDiver1975

**Comment by DeepDiver1975** [comment]
Backlog fromy pov

**Comment by dragotin** [comment]
Backlog

**Comment by timeraider4u** [comment]
Maybe I am getting it wrong, but isn't this what [Fail2ban](http://www.fail2ban.org/wiki/index.php/Main_Page) is already providing? I am using it to block SSH accesses, but it can also be extended for OwnCloud. Wouldn't it be better to just provide the template files for Fail2ban and maybe a plug-in which shows information and state updates from Fail2ban?

**Comment by RealRancor** [comment]
@timeraider4u Yes, you're right. fail2ban should always used in favor of a solution written in PHP. A config for fail2ban is provided since a longer time at the forums (now central): https://central.owncloud.org/t/fail2ban-and-owncloud-8-x-9-0-x/837

The solution here is probably meant for users without root  / shell access to their systems. They can't use fail2ban there.

**Comment by hodyroff** [comment]
We will stick with fali2ban and clearly and broadly recommend it for security hardening. People also have policies in AD/LDAP or other tools they are using as IDP. This kind of service is way better done on the IP level comared with the PHP level. If people like to include something into ownCloud itself, if its an app or nicely configurable for Core people are welcome to make a PR.
