### ISSUE TITLE
calendar.network.multirealm

### ISSUE THREAD

**Issue by timreeves** [owncloud/core#23452]
### Steps to reproduce
1. Using Thunderbird + Lightning + SOGo Connector go to Settings | Extended | Configuration
2. In German: Einstellungen | Erweitert | Konfiguration
3. Search for calendar.network.multirealm
4. Doubleclick on it (changes from false to true)
5. Restart TB

### Expected behaviour
Old calendars, connecting to OC 8.2.3 should still work

### Actual behaviour
Nothing at all works. Not the old calendars, but also not the new ones on another host with OC 9.0.0, with the new style of URL. I got the tip from here:

https://doc.owncloud.org/server/9.0/user_manual/pim/calendar.html
This docu seems not in touch with currently visible reality!

### Server configuration
Ubuntu 12.04 (but irrelevant, it's a TB issue)

**Web server:**
Nginx

**Database:**
MySQL

**PHP version:**
7.0.4

**ownCloud version:** (see ownCloud admin page)
9.0.0

**Updated from an older ownCloud or fresh install:**
Updated from 8.2.3

**Where did you install ownCloud from:**
Command line from tarball

**Signing status (ownCloud 9.0 and above):**
Error free

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - calendar: true
  - contacts: true
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_external: 0.5.2
  - files_trashbin: 0.8.0
  - notifications: 0.2.3
  - updatenotification: 0.1.0

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc452bf87cea",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.biblische-reisen.de"
        ],
        "datadirectory": "\/var\/www\/vhosts\/biblische-reisen.de\/oc-data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloudbde",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": "2",
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "mail_from_address": "owncloud",
        "mail_domain": "biblische-reisen.de",
        "mail_smtpmode": "php",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "en",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "log_rotate_size": 10485760,
        "check_for_working_wellknown_setup": false,
        "check_for_working_htaccess": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0,
            "dbindex": 1
        },
        "trashbin_retention_obligation": "auto"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "8"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "0",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "0",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "global_cache_gc_lastrun": "1437227419",
            "installedat": "1404918632.0979",
            "lastcron": "1458576481",
            "lastupdateResult": "{\"version\":{},\"versionstring\":{},\"url\":{},\"web\":{}}",
            "lastupdatedat": "1458559298",
            "oc.integritycheck.checker": "[]",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "types": "filesystem"
        },
        "documents": {
            "converter": "local",
            "enabled": "no",
            "installed_version": "0.8.2",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "federation": {
            "enabled": "no",
            "installed_version": "0.0.4",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.4.4",
            "types": "filesystem"
        },
        "files_external": {
            "\/BackupLocalServer": "1437228678",
            "enabled": "yes",
            "installed_version": "0.5.2",
            "ocsid": "166048",
            "types": "filesystem"
        },
        "files_mv": {
            "enabled": "no",
            "installed_version": "0.8.1a",
            "ocsid": "150271",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "no",
            "installed_version": "0.7",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "no",
            "installed_version": "0.6.3",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "0.4",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "no",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "0.6.0",
            "ocsid": "166056",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.2.3",
            "types": "logging"
        },
        "provisioning_api": {
            "enabled": "no",
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction"
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.5.3",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "systemtags": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no"
        },
        "templateeditor": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        }
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration

**Operating system:**
Windows 10

**Comment by RealRancor** [comment]
@timreeves Documentation issues should be reported to https://github.com/owncloud/documentation/issues

Also please contact the Thunderbird community about such stuff like the "calendar.network.multirealm". e.g. this should be only used if you're using multiple accounts on the same server.

**Comment by timreeves** [comment]
Thanks for the prompt reply.
Indeed, the documentation issue has already been addressed:
https://github.com/owncloud/documentation/issues/2278
Re multirealm, yes obviously it's a TB issue, but I mentioned it here as it was noted in the current OC docs, leading me to think it would help, but it only made matters worse.
Re "nothing works" the problem goes away when reset mutlirealm to false and restart TB. Closing.
