### ISSUE TITLE
8.1.6 packages are missing at OBS repos

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#23465]
Hi,

seems the 8.1.6 packages are currently missing at the OBS repositories:

https://build.opensuse.org/package/show/isv:ownCloud:community:8.1/owncloud

-> Has currently owncloud-8.1.5.tar.bz2

**Comment by PVince81** [comment]
@jnweiger

**Comment by jnweiger** [comment]
Good catch!
https://build.opensuse.org/request/show/368490 did not make it. Sorry.

Rebuild in progress.

**Comment by jnweiger** [comment]
fixed.
