### ISSUE TITLE
(Almost) can't navigate away from the files list if external storage is not available

### ISSUE THREAD

**Issue by schiessle** [owncloud/core#23476]
I observed this on stable9 and master.

First you need to configure a external storage, I did it with a local ftp server. Then you shut down the ftp server and go to the files view and try to open one of the settings (admin, personal, user,...) or the apps menu. For a short time you will see a yellow banner with following text: "Some of the configured external mount points are not connected. Please click on the red row(s) for more information". Then the files view gets re-loaded. So there is no way to navigate away from the files view.

There are only two ways:

- first go to a sub-folder and then go the settings or app page

- or first click on the folder with the temporarily unavailable storage. This will show the same yellow banner but without re-loading the page. After that you can navigate to a settings page or the apps list

**Comment by PVince81** [comment]
>  So there is no way to navigate away from the files view.

So reloading the page or clicking on another app doesn't work either ?

**Comment by PVince81** [comment]
Should be fixed with https://github.com/owncloud/core/pull/25035

**Comment by PVince81** [comment]
I meant this one https://github.com/owncloud/core/pull/23735
