### ISSUE TITLE
9.0 - cannot create folder with IE11 and when I log in to folder shared with a link (without user name)

### ISSUE THREAD

**Issue by kpalik** [owncloud/core#23471]
### Steps to reproduce
1. Create folder and share it as a link (with "Allow editing") 
2. Log out (or use InPrivate session of IE11) and use link - you should see password-only login page - enter password and log in
3. Try to create folder - enter folder name and hit enter

### Expected behaviour
Folder should be created

### Actual behaviour
1. the layer with folder name is not closed
2. folder is not created
3. IE console shows 1 error (i have only polish version so translation can be wrong)

SCRIPT5007: Nie można ustawić właściwości „Authorization” dla niezdefiniowanego lub pustego odwołania (Cannot set property 'Authorization' of undefined ??)
File: iedavclient.js, line: 34, column: 5 

### Server configuration

**ownCloud version:** (see ownCloud admin page)
9.0 - latest fresh install on Ubuntu ubuntu-14.04.4-server-amd64 

### Client configuration
**Browser:**
IE11
**Operating system:**
Windows 8.1 x64

#### Browser log

Insert your browser log here, this could for example include:

a) The javascript console log

SCRIPT5007: Nie można ustawić właściwości „Authorization” dla niezdefiniowanego lub pustego odwołania  (Cannot set property 'Authorization' of undefined ??)
Plik: iedavclient.js, wiersz: 34, kolumna: 5

b) The network log 

empty

**Comment by PVince81** [comment]
Can you test whether https://github.com/owncloud/core/pull/23096 fixes the issue for you ?

**Comment by kpalik** [comment]
nope, AFAIK it is not related to this issue. In fact we used #23096 to fix issues with creating folders in IE11 (when logged in as normal user) but after this we discovered this issue - I think that the problem source is that you log in without user name and then the script fails on IE (and works on Firefox)

**Comment by PVince81** [comment]
Ok, thanks for testing.

**Comment by PVince81** [comment]
> InPrivate session of IE11

Hmm. Does it work in a regular session ?

**Comment by kpalik** [comment]
Nope, if I log out and use sharing link it won't work

**Comment by michaelstingl** [comment]
@PVince81 What is the status here?

00005721

**Comment by PVince81** [comment]
Ok, since you insist. Just had a quick look, seems like a trivial fix.

PR will follow soon

**Comment by PVince81** [comment]
here you go https://github.com/owncloud/core/pull/25233
