### ISSUE TITLE
Exported Calendar containing "apple location" not importable

### ISSUE THREAD

**Issue by stonie08** [owncloud/core#23483]
When exporting a calendar with events containing apple's location entry, the calendar cannot be imported anymore.

For testing purposes i created the following export of the calendar:
[testing.txt](https://github.com/owncloud/core/files/184347/testing.txt)

The file cannot be imported unless one removes the lines 36 to 44 starting with "X-APPLE-STRUCTURED-LOCATION"

### Steps to reproduce
1. Create calender over the Owncloud webinterface
2. Connect with CalDAV from an iOS 9.2/9.3 device (maybe also 8.x/9.x)
3. Create event in the iOS calendar app with a location (one of the locations from the suggestions that really exists)
4. Export the calendar via the owncloud webinterface
5. delete the calendar
6. try to import the previously exported calendar

### Expected behaviour
The calendar should be imported the way it has been exported

### Actual behaviour
The site shows a "fileneme.ics     analysing calendar" message without doing anything more.

![2016-03-22 15_57_16-kalender - owncloud](https://cloud.githubusercontent.com/assets/2730294/13955950/fdeb403a-f046-11e5-90dd-b8ef54554d9c.jpg)

### Server configuration
**Operating system**:
Debian Jessie
**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
PHP 5.6.17-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
Owncloud 9.0.0

**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**
Package Manager

```
No errors have been found.
```
----

### Client configuration
**Browser:**
Mozilla Firefox 45.0.1

**Operating system:**
Windows 7

#### Web server error log
----

#### ownCloud log (data/owncloud.log)
Nothing shown in the OC logfile while doing the actions, Log Level set to all

#### Browser log
---

**Comment by DeepDiver1975** [comment]
error in the browser console:

````
Uncaught ParserError: Empty parameter name in ';VALUE=URI;X-ADDRESS="Schönbrunner Schloßstraße 47, 1130 Wien, Österreich";X-APPLE-MAPKIT-HANDLE=CAESnAIIrk0Qz6nkjrrr/o7hARoSCdcAHIWoF0hAEQAAAPzuTzBAIqsBCgvDlnN0ZXJyZWljaBICQVQaBFdpZW4yBFdpZW46BDExMzBSHFNjaMO2bmJydW5uZXIgU2NobG/Dn3N0cmHDn2VaAjQ3Yh9TY2jDtm5icnVubmVyIFNjaGxvw59zdHJhw59lIDQ3chNTY2hsb3NzIFNjaMO2bmJydW5uigEUMTMuIEJlemlyaywgSGlldHppbmeKAQhIaWV0emluZ4oBC1NjaMO2bmJydW5uKhFTY2hvbmJydW5uIFBhbGFjZTIfU2Now7ZuYnJ1bm5lciBTY2hsb8Ofc3RyYcOfZSA0NzIJMTEzMCBXaWVuMgvDlnN0ZXJyZWljaA==;X-APPLE-RADIUS=13.35618262390424;X-APPLE-REFERENCEFRAME=1;X-TITLE=Schonbrunn Palace:geo:48.184830,16.312240'

**Comment by DeepDiver1975** [comment]
We better move this issue to the calendar repo

**Comment by georgehrke** [comment]
There already is, will link and close when I'm back home

Please excuse my brevity and typos.

**Comment by DeepDiver1975** [comment]
THX @georgehrke

**Comment by georgehrke** [comment]
dup of https://github.com/owncloud/calendar/issues/334
