### ISSUE TITLE
Shared (in a group) calendars do not work by using caldav anymore.

### ISSUE THREAD

**Issue by remkolodder** [owncloud/core#23494]
Steps to reproduce

Share calendar with a usergroup
CalDAV in IOS does not shows shared calendar
If same calender shared with single user it shows
Group shared Calender over OC GUI is available under the point Subscription.
Expected behaviour

In OC 8 it was possible to share a calendar with an usergroup and was available over CalDAV for all users in the group.

Actual behaviour

Shared calender over 'Group' is not available by using CalDAV. But shared Calendar over 'User' is not available by using CalDAV

I am reporting this for @fr4nk3nst3in
He reported this at https://github.com/owncloud/calendar/issues/350 where the issue was closed and mentioned that it should be reported in the main tree.

I have the same issues so I can vouch for this mentioning as well.

Please let me know what additional information is required. Thanks!

**Comment by Professi** [comment]
I can confirm this behaviour with DAVDroid in combination with OC 9. Under OC 8.x everything worked fine.

**Comment by DeepDiver1975** [comment]
Fixed with 9.0.1
