### ISSUE TITLE
Apps management UI accessibility

### ISSUE THREAD

**Issue by tyrylu** [owncloud/core#23492]
In Owncloud 9.0 the two likely buttons in the app list which switch between the display of enabled and disabled states are reported by NVDA screen reader as a simple list item e. g. no clickable status etc.
Also, the other categories aren't visible to screen reader in Firefox, but are in IE 11, not couting the weird state/non-semantic representation.
The semantic issue is also with the show description link.
You can try it if you access the screen with NVDA, it should say something sensible, which is not the case now.
Tried with Firefox 45. I doupt that the server configuration is important in this case, but it's a standard manual install on apache 2.4 with php 5.6 without any integrity errors.

**Comment by tyrylu** [comment]
One correction, the other categories sometimes show for the screen reader in Firefox also, so this behavior is not browser specific at all.

**Comment by PVince81** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
@tyrylu is this only the case in the apps management or elsewhere too, for example in the Files app left navigation?

Also, do you have a suggestion how to fix this? Thanks! :)

**Comment by tyrylu** [comment]
Hello.
If i understand the ui correctly, the left navigation is the menu vith items like all files, favorites, shared with me etc. If yes, this menu is alright.
From my experiments, the issue could be resolved relatively easily.
The current template line looks like:
<a>{{displayName}}</a>
For some reason, screen readers (or at least latest NVDA dev build) does not announce links without any href as links. So somethink like
<a href="#">{{displayName}}</a>
should fix it. May be it's in more places as well, i haven't looked as much into it.

**Comment by jancborchardt** [comment]
@tyrylu oh nice, that’s easy enough! Do you want to open a pull request to fix that yourself? It’s as easy as fixing it in this line: https://github.com/owncloud/core/blob/master/settings/templates/apps.php#L28
You can simply go to the top right, press »edit« on the file, it will automatically fork the project to your account and you can edit the file. Then you can open a pull request with the change. :)

**Comment by tyrylu** [comment]
Firstly, thank you for the file path pointer, it was really helpful.
And #24104 is the fix.
