### ISSUE TITLE
Groups cannot be deleted when name ends with backslash

### ISSUE THREAD

**Issue by mbrouwer88** [owncloud/core#23499]
### Steps to reproduce
1. Create a group with a trailing \ in the name, like "Test\"
2. Delete the group, Owncloud reports it's deleted.
3. Refresh the page, you see that the group was not deleted.

### Expected behaviour
The group should be deleted, regardless of the name used.

### Actual behaviour
The interface tells you it's deleted, but it's not.

### Server configuration
**Operating system**:
Debian 7
**Web server:**
Apache2
**Database:**
Mysql
**PHP version:**
5
**ownCloud version:** (see ownCloud admin page)
8.2.2
**Updated from an older ownCloud or fresh install:**
Updated
**Where did you install ownCloud from:**
APT-GET Owncloud repo
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
Only encryption module (default)
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
Yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Chrome and IE
**Operating system:**
Windows
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Oh wow, seems the browser made the request to the root which got redirected to the default URL:
![groupbacklash](https://cloud.githubusercontent.com/assets/277525/14609832/c0c95890-058b-11e6-9eda-0d6879fb2070.png)

CC @LukasReschke

**Comment by PVince81** [comment]
Observed on v9.0.1

**Comment by LukasReschke** [comment]
Patch is at https://github.com/owncloud/core/pull/24072
