### ISSUE TITLE
Error page is missing, just a xml appear.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#23500]
### Steps to reproduce

1. Recreate an error situation, for example try to access to encrypted files without encryption app enabled, or make firewall (EE) block access from a specific user agent and access using that user agent.

### Expected behaviour
Error page appears.

### Actual behaviour
An xml is returned.

Example while trying to open an encrypted file without encryption enabled:
![screen shot 2016-03-23 at 09 14 50](https://cloud.githubusercontent.com/assets/9048796/13979394/7ee0f4e6-f0d8-11e5-82d0-9552d013a3bb.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"9.0.1.0","versionstring":"9.0.1 beta","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**

```
{"reqId":"0V0fSwdCSmGNacysgO7n","remoteAddr":"HIDDEN_IP","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Encryption not ready: Module with id: OC_DEFAULT_MODULE does not exist.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/opt\\\/owncloud\\\/remote.php(138): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#7 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php\",\"Line\":311,\"User\":\"admin\"}","level":4,"time":"2016-03-23T08:25:59+00:00"}
```

### Client configuration

**browser**
Chrome

**Comment by SergioBertolinSG** [comment]
Reported previously in firewall, but it is more general: https://github.com/owncloud/firewall/issues/237

**Comment by PVince81** [comment]
How did you access the file ? Web UI download ? Where did you click ?
This is important to find out which mechanism is used.

Since you're getting XML, I guess that you clicked on a single file download link which leads to the Webdav endpoint.

Hmmmm... it feels wrong to have the Webdav endpoint detect whether the download comes from the browser to show an error page.

**Comment by PVince81** [comment]
A quick workaround would be to switch back to use "ajax/download.php"...

**Comment by PVince81** [comment]
I decided to revert back to ajax/download.php, PR is here: https://github.com/owncloud/core/pull/23521

**Comment by PVince81** [comment]
Something to try: do a HEAD request with `$.ajax` before starting the download.

**Comment by PVince81** [comment]
@DeepDiver1975 offered to have a look adding a Sabre plugin to return HTML contents.
Assigning to you, thanks!
