### ISSUE TITLE
Recent apps section in app store list

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#23502]
I suggest to introduce a new section "Recent apps" in the app store.
To find out which apps they are, just check "oc_appconfig" and find all apps that have "enabled" === "no". Such entries only exist if the app has at least be enabled once in the past.

This could also make it easier for admins to easily re-find the third party apps that were enabled in the past and reenable them after an upgrade.

@owncloud/designers @karlitschek @DeepDiver1975 @nickvergessen @MorrisJobke @LukasReschke

**Comment by nickvergessen** [comment]
Well first we should have the "apps ready for update" list

**Comment by PVince81** [comment]
Agreed. Did we have a ticket for this ?

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/issues/22892

**Comment by PVince81** [comment]
obsoleted by market app
