### ISSUE TITLE
AppConfig -> lastupdateResult

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#23524]
### Steps to reproduce
1. Use owncloud from OC 4.5 on, update through all major versions up to OC 7.0.8
2. Upgrade to OC 8.0.6
3. Upgrade further until 8.1.6

### Expected behaviour
I would expect the lastupdateResult to be 8.1.6.2. I never installed OC 8.0.2, I went directly to 8.0.6 and a few days later 8.1.1 (or 8.1.2).

Background: We have some users with update-error message that major versions can't be skipped. If they did the manual update, I was looking for a config value in the database that could indicate the version (should be in the config.php).

### Actual behaviour
appid -> core
configkey -> lastupdateResult
configvalue -> {"version":"8.0.2.0","versionstring":"ownCloud 8.0.2","url":"http:\/\/download.owncloud.org\/community\/owncloud-8.0.2.zip","web":"http:\/\/doc.owncloud.org\/server\/8.0\/admin_manual\/maintenance\/upgrade.html"}

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache/ mod_php

**Database:** Mysql

**ownCloud version:** 8.1.6.2

**Updated from an older ownCloud or fresh install:** older version, since 4.5 (I think)

**Where did you install ownCloud from:** manual upgrades

**Encryption:** Was disabled in OC 7.0

Is this config-key deprecated?

**Comment by LukasReschke** [comment]
This config key is used to indicate what last update the updater app found propagated on the update endpoint. It can be ignored and is just for caching reasons.
