### ISSUE TITLE
Contacts: Import of .vcf file does not import CATEGORIES

### ISSUE THREAD

**Issue by Larx** [owncloud/core#23529]
### Steps to reproduce
1. Back up old 8.2 contacts (export to file)
2. Fresh install of 9.0, import the .vcf-file
3. CATEGORIES are not reimported

### Expected behaviour
CATEGORIES (still present in the .vcf-file, btw) should be imported from the file.

### Actual behaviour
Everything (as far as I can see) but the CATEGORIES is imported

**Comment by DeepDiver1975** [comment]
We store the vcard as given in the DB.
I cannot imagine a reason why the categories are removed.
Can you give us an example vcard?
Thx

**Comment by Larx** [comment]
I stand corrected. ownCloud does not even import vcf files right now! So I reported wrong, yes, thinking back I had to use Evolution to transfer/reimport the contacts, and therefore it might not be OC's fault at all. However, lack of vcf import is another point :( .

**Comment by DeepDiver1975** [comment]
Vcard Import will be part of the next Version of the contacts app
