### ISSUE TITLE
[Enhancement] SSO with Office365 / Google Apps

### ISSUE THREAD

**Issue by EgoAleSum** [owncloud/core#23523]
Currently I'm allowing users to authenticate to ownCloud using LDAP, connecting to AD, but that is not ideal:
- LDAP is heavier (despite the "lightweight" in L :) ) as it requires PHP extensions to be installed, and ownCloud plugins
- LDAP is harder to integrate
- LDAP requires the creation of a service account

It would be a great enhancement if users could do SSO with Azure AD / Office365, or Google Apps. Services like Box and Dropbox for Business already integrate this capability.

**Comment by spinnix** [comment]
That would be great.

**Comment by PVince81** [comment]
Something that someone could implement as a separate app. There's already an [app for SAML](https://github.com/owncloud/apps/tree/master/user_saml) so it should be possible to use the same APIs for other SSO providers.

**Comment by EgoAleSum** [comment]
Hi @PVince81 please see this thread here too: https://help.nextcloud.com/t/office-365-oauth-authorization-flow-for-nextcloud/24401/5

I am not sure what I'm proposing can be implemented with a plugin only. We could implement OAuth just for authenticating against existing users in the NC database, and that might be done with a plugin, but would lead us to a half-baked implementation.

For example, the SAML app provides authentication, but users still need to configure LDAP if they want to get access to the directory.

If I were to suggest something "dramatic", it would be taking the authentication system as it stands today out of the Nextcloud monolith, and create a separate service that provides identity and directory services using OpenID Connect (could be something like https://github.com/ory/hydra ). Then, Nextcloud could be configured to leverage that OIDC server, or any other OIDC provider like Azure AD, Google, etc. The external service would be used for authentication, but also to get directory services. By moving everything to an external service, we could also simplify things like SAML and LDAP (e.g. for LDAP we could just implement Keycloak)...
