### ISSUE TITLE
cron.php exits with PHP Fatal error: Call to undefined method

### ISSUE THREAD

**Issue by cpt1gl0** [owncloud/core#23534]
### Steps to reproduce
1. Run cron.php

### Expected behaviour
cron.php should run without giving any errors.

### Actual behaviour
cron.php gives the error message:
_PHP Fatal error:  Call to undefined method OC\Files\Cache\FailedCache::correctFolderSize() in /var/vhosts/owncloud/lib/private/files/cache/scanner.php on line 457_

### Server configuration
**Operating system**:
Debian GNU/Linux
**Web server:**
apache
**Database:**
mysql
**PHP version:**
PHP 5.6.17-0+deb8u1
**ownCloud version:** (see ownCloud admin page)
9.0.1 beta
**Updated from an older ownCloud or fresh install:**
Updated from 9.0.0
**Where did you install ownCloud from:**
Downloaded tar archive from owncloud homepage.
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.6
  - documents: true
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0

Disabled:
  - activity
  - encryption
  - external
  - files_external
  - notes
  - user_external

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
{
    "system": {
        "instanceid": "52346c4d79e93",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/srv\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.1.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "ldapIgnoreNamingRules": false,
        "loglevel": 2,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "owncloud.treefish.org"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",
        "mail_domain": "treefish.org",
        "mail_smtphost": "localhost",
        "appstore.experimental.enabled": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto"
    },
    "apps": {
        "activity": {
            "enabled": "no",
            "installed_version": "2.2.1",
            "types": "filesystem"
        },
        "admin_migrate": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": null
        },
        "appframework": {
            "enabled": "no",
            "installed_version": "0.103",
            "ocsid": "158433",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "1465"
        },
        "bookmarks": {
            "enabled": "no",
            "installed_version": "0.4",
            "ocsid": "168710",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "0",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "contacts": {
            "backend_ldap": "true",
            "enabled": "yes",
            "installed_version": "0",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "OC_Channel": "stable",
            "backgroundjobs_mode": "cron",
            "backgroundjobs_task": "",
            "global_cache_gc_lastrun": "1439585342",
            "installedat": "1379167481.2395",
            "lastcron": "1458766804",
            "lastupdateResult": "{\"version\":{},\"versionstring\":{},\"url\":{},\"web\":{}}",
            "lastupdatedat": "1458771412",
            "oc.integritycheck.checker": "[]",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_ampache": "media\/remote.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_contactthumbnail": "contacts\/thumbnail.php",
            "remote_core.css": "\/core\/minimizer.php",
            "remote_core.js": "\/core\/minimizer.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_public_notification": "yes"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.1.6",
            "types": "filesystem"
        },
        "documents": {
            "enabled": "yes",
            "installed_version": "0",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.0.4",
            "types": "authentication"
        },
        "files": {
            "backgroundwatcher_previous_file": "1578",
            "backgroundwatcher_previous_folder": "1474",
            "cronjob_scan_files": "500",
            "default_quota": "5 GB",
            "enabled": "yes",
            "installed_version": "1.4.4",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "no",
            "enabled": "no",
            "installed_version": "0.2.3",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "\\OC\\Files\\Storage\\SFTP"
        },
        "files_imageviewer": {
            "enabled": "no",
            "installed_version": "1.0",
            "types": null
        },
        "files_odfviewer": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": null
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "122": "1442607493.8283",
            "123": "1442607494.0854",
            "124": "1442607494.3635",
            "126": "1442607494.7378",
            "127": "1440627346.6381",
            "138": "1450037054.3809",
            "141": "1452200606.4813",
            "142": "1453960551.2039",
            "146": "1451900662.3618",
            "147": "1451900662.4173",
            "152": "1454272920.4339",
            "153": "1454272920.4775",
            "155": "1454272920.5665",
            "159": "1453756848.1582",
            "161": "1453959499.2305",
            "162": "1458506374.5258",
            "163": "1454536795.1667",
            "164": "1454536795.2219",
            "165": "1454536795.2667",
            "169": "1455467814.803",
            "178": "1458407166.8463",
            "179": "1458407166.9408",
            "98": "1456142550.9664",
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "14.5.0",
            "types": ""
        },
        "galleryplus": {
            "enabled": "no",
            "installed_version": "14.3.0",
            "ocsid": "169116",
            "types": ""
        },
        "mail": {
            "enabled": "no",
            "installed_version": "0.2.1",
            "ocsid": "169914",
            "types": ""
        },
        "media": {
            "enabled": "no",
            "installed_version": "0.4.3",
            "types": null
        },
        "music": {
            "enabled": "no",
            "installed_version": "0.3.8",
            "ocsid": "164319",
            "types": "filesystem"
        },
        "news": {
            "enabled": "no",
            "installed_version": "6.1.1",
            "ocsid": "168040",
            "types": ""
        },
        "notes": {
            "enabled": "no",
            "installed_version": "2.0.0",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.2.3",
            "types": "logging"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction"
        },
        "roundcube": {
            "autoLogin": "1",
            "enabled": "no",
            "encryptstring1": "",
            "encryptstring2": "",
            "installed_version": "2.6.1",
            "maildir": "\/roundcube\/",
            "ocsid": "151523",
            "removeControlNav": "",
            "removeHeaderNav": "",
            "types": ""
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.7.0",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.8.1",
            "ocsid": "164356",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "user_ldap": {
            "bgjUpdateGroupsLastRun": "1384178228",
            "cleanUpJobOffset": "0",
            "enabled": "yes",
            "enforce_home_folder_naming_rule": "",
            "has_memberof_filter_support": "",
            "home_folder_naming_rule": "",
            "installed_version": "0.8.0",
            "last_jpegPhoto_lookup": "0",
            "ldap_agent_password": "",
            "ldap_attributes_for_group_search": "",
            "ldap_attributes_for_user_search": "",
            "ldap_backup_host": "",
            "ldap_backup_port": "389",
            "ldap_base": "ou=People,dc=treefish,dc=org",
            "ldap_base_groups": "ou=Group,dc=treefish,dc=org",
            "ldap_base_users": "ou=People,dc=treefish,dc=org",
            "ldap_cache_ttl": "600",
            "ldap_configuration_active": "1",
            "ldap_display_name": "cn",
            "ldap_dn": "",
            "ldap_dynamic_group_member_url": "",
            "ldap_email_attr": "preferredMail",
            "ldap_experienced_admin": "0",
            "ldap_expert_username_attr": "uid",
            "ldap_expert_uuid_attr": "",
            "ldap_expert_uuid_group_attr": "",
            "ldap_expert_uuid_user_attr": "",
            "ldap_group_display_name": "cn",
            "ldap_group_filter": "objectClass=posixGroup",
            "ldap_group_filter_mode": "1",
            "ldap_group_member_assoc_attribute": "memberUid",
            "ldap_groupfilter_groups": "",
            "ldap_groupfilter_objectclass": "",
            "ldap_host": "ldaps:\/\/tyr.treefish.org",
            "ldap_login_filter": "uid=%uid",
            "ldap_login_filter_mode": "1",
            "ldap_loginfilter_attributes": "",
            "ldap_loginfilter_email": "0",
            "ldap_loginfilter_username": "1",
            "ldap_nested_groups": "0",
            "ldap_override_main_server": "0",
            "ldap_paging_size": "500",
            "ldap_port": "636",
            "ldap_quota_attr": "",
            "ldap_quota_def": "",
            "ldap_tls": "",
            "ldap_turn_off_cert_check": "0",
            "ldap_user_display_name_2": "",
            "ldap_user_filter_mode": "1",
            "ldap_userfilter_groups": "",
            "ldap_userfilter_objectclass": "inetOrgPerson",
            "ldap_userlist_filter": "objectclass=inetOrgPerson",
            "ldap_uuid_attribute": "entryuuid",
            "ldap_uuid_group_attribute": "entryuuid",
            "ldap_uuid_user_attribute": "entryuuid",
            "s01has_memberof_filter_support": "",
            "s01home_folder_naming_rule": "",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_agent_password": "",
            "s01ldap_attributes_for_group_search": "",
            "s01ldap_attributes_for_user_search": "",
            "s01ldap_backup_host": "",
            "s01ldap_backup_port": "389",
            "s01ldap_base": "ou=virtual.treefish.org,ou=Domains,ou=Postfix,dc=treefish,dc=org",
            "s01ldap_base_groups": "ou=virtual.treefish.org,ou=Domains,ou=Postfix,dc=treefish,dc=org",
            "s01ldap_base_users": "ou=virtual.treefish.org,ou=Domains,ou=Postfix,dc=treefish,dc=org",
            "s01ldap_cache_ttl": "600",
            "s01ldap_configuration_active": "1",
            "s01ldap_display_name": "cn",
            "s01ldap_dn": "",
            "s01ldap_dynamic_group_member_url": "",
            "s01ldap_email_attr": "preferredMail",
            "s01ldap_experienced_admin": "0",
            "s01ldap_expert_username_attr": "uid",
            "s01ldap_expert_uuid_attr": "",
            "s01ldap_expert_uuid_group_attr": "",
            "s01ldap_expert_uuid_user_attr": "",
            "s01ldap_group_display_name": "cn",
            "s01ldap_group_filter": "objectClass=posixGroup",
            "s01ldap_group_filter_mode": "1",
            "s01ldap_group_member_assoc_attribute": "memberUid",
            "s01ldap_groupfilter_groups": "",
            "s01ldap_groupfilter_objectclass": "",
            "s01ldap_host": "ldaps:\/\/tyr.treefish.org",
            "s01ldap_login_filter": "uid=%uid",
            "s01ldap_login_filter_mode": "1",
            "s01ldap_loginfilter_attributes": "",
            "s01ldap_loginfilter_email": "1",
            "s01ldap_loginfilter_username": "0",
            "s01ldap_nested_groups": "0",
            "s01ldap_override_main_server": "0",
            "s01ldap_paging_size": "500",
            "s01ldap_port": "636",
            "s01ldap_quota_attr": "",
            "s01ldap_quota_def": "",
            "s01ldap_tls": "",
            "s01ldap_turn_off_cert_check": "0",
            "s01ldap_user_display_name_2": "",
            "s01ldap_user_filter_mode": "1",
            "s01ldap_userfilter_groups": "",
            "s01ldap_userfilter_objectclass": "mailUser",
            "s01ldap_userlist_filter": "(&(objectclass=mailUser)(objectClass=simpleSecurityObject))",
            "s01ldap_uuid_attribute": "entryuuid",
            "s01ldap_uuid_group_attribute": "entryuuid",
            "s01ldap_uuid_user_attribute": "entryuuid",
            "s01use_memberof_to_detect_membership": "1",
            "types": "authentication",
            "use_memberof_to_detect_membership": "1"
        },
        "user_migrate": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": null
        },
        "169914": {
            "enabled": "no"
        }
    }
}
**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
+-------------------------------+------------------------------+
| Configuration                 |                              |
+-------------------------------+------------------------------+
| hasMemberOfFilterSupport      |                              |
| hasPagedResultSupport         |                              |
| homeFolderNamingRule          |                              |
| lastJpegPhotoLookup           | 0                            |
| ldapAgentName                 |                              |
| ldapAgentPassword             | ***                          |
| ldapAttributesForGroupSearch  |                              |
| ldapAttributesForUserSearch   |                              |
| ldapBackupHost                |                              |
| ldapBackupPort                | 389                          |
| ldapBase                      | ou=People,dc=treefish,dc=org |
| ldapBaseGroups                | ou=Group,dc=treefish,dc=org  |
| ldapBaseUsers                 | ou=People,dc=treefish,dc=org |
| ldapCacheTTL                  | 600                          |
| ldapConfigurationActive       | 1                            |
| ldapDynamicGroupMemberURL     |                              |
| ldapEmailAttribute            | preferredMail                |
| ldapExperiencedAdmin          | 0                            |
| ldapExpertUUIDGroupAttr       |                              |
| ldapExpertUUIDUserAttr        |                              |
| ldapExpertUsernameAttr        | uid                          |
| ldapGroupDisplayName          | cn                           |
| ldapGroupFilter               | objectClass=posixGroup       |
| ldapGroupFilterGroups         |                              |
| ldapGroupFilterMode           | 1                            |
| ldapGroupFilterObjectclass    |                              |
| ldapGroupMemberAssocAttr      | memberUid                    |
| ldapHost                      | ldaps://tyr.treefish.org     |
| ldapIgnoreNamingRules         |                              |
| ldapLoginFilter               | uid=%uid                     |
| ldapLoginFilterAttributes     |                              |
| ldapLoginFilterEmail          | 0                            |
| ldapLoginFilterMode           | 1                            |
| ldapLoginFilterUsername       | 1                            |
| ldapNestedGroups              | 0                            |
| ldapOverrideMainServer        | 0                            |
| ldapPagingSize                | 500                          |
| ldapPort                      | 636                          |
| ldapQuotaAttribute            |                              |
| ldapQuotaDefault              |                              |
| ldapTLS                       |                              |
| ldapUserDisplayName           | cn                           |
| ldapUserDisplayName2          |                              |
| ldapUserFilter                | objectclass=inetOrgPerson    |
| ldapUserFilterGroups          |                              |
| ldapUserFilterMode            | 1                            |
| ldapUserFilterObjectclass     | inetOrgPerson                |
| ldapUuidGroupAttribute        | auto                         |
| ldapUuidUserAttribute         | auto                         |
| turnOffCertCheck              | 0                            |
| useMemberOfToDetectMembership | 1                            |
+-------------------------------+------------------------------+
+-------------------------------+------------------------------------------------------------------+
| Configuration                 | s01                                                              |
+-------------------------------+------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                  |
| hasPagedResultSupport         |                                                                  |
| homeFolderNamingRule          |                                                                  |
| lastJpegPhotoLookup           | 0                                                                |
| ldapAgentName                 |                                                                  |
| ldapAgentPassword             | ***                                                              |
| ldapAttributesForGroupSearch  |                                                                  |
| ldapAttributesForUserSearch   |                                                                  |
| ldapBackupHost                |                                                                  |
| ldapBackupPort                | 389                                                              |
| ldapBase                      | ou=virtual.treefish.org,ou=Domains,ou=Postfix,dc=treefish,dc=org |
| ldapBaseGroups                | ou=virtual.treefish.org,ou=Domains,ou=Postfix,dc=treefish,dc=org |
| ldapBaseUsers                 | ou=virtual.treefish.org,ou=Domains,ou=Postfix,dc=treefish,dc=org |
| ldapCacheTTL                  | 600                                                              |
| ldapConfigurationActive       | 1                                                                |
| ldapDynamicGroupMemberURL     |                                                                  |
| ldapEmailAttribute            | preferredMail                                                    |
| ldapExperiencedAdmin          | 0                                                                |
| ldapExpertUUIDGroupAttr       |                                                                  |
| ldapExpertUUIDUserAttr        |                                                                  |
| ldapExpertUsernameAttr        | uid                                                              |
| ldapGroupDisplayName          | cn                                                               |
| ldapGroupFilter               | objectClass=posixGroup                                           |
| ldapGroupFilterGroups         |                                                                  |
| ldapGroupFilterMode           | 1                                                                |
| ldapGroupFilterObjectclass    |                                                                  |
| ldapGroupMemberAssocAttr      | memberUid                                                        |
| ldapHost                      | ldaps://tyr.treefish.org                                         |
| ldapIgnoreNamingRules         |                                                                  |
| ldapLoginFilter               | uid=%uid                                                         |
| ldapLoginFilterAttributes     |                                                                  |
| ldapLoginFilterEmail          | 1                                                                |
| ldapLoginFilterMode           | 1                                                                |
| ldapLoginFilterUsername       | 0                                                                |
| ldapNestedGroups              | 0                                                                |
| ldapOverrideMainServer        | 0                                                                |
| ldapPagingSize                | 500                                                              |
| ldapPort                      | 636                                                              |
| ldapQuotaAttribute            |                                                                  |
| ldapQuotaDefault              |                                                                  |
| ldapTLS                       |                                                                  |
| ldapUserDisplayName           | cn                                                               |
| ldapUserDisplayName2          |                                                                  |
| ldapUserFilter                | (&(objectclass=mailUser)(objectClass=simpleSecurityObject))      |
| ldapUserFilterGroups          |                                                                  |
| ldapUserFilterMode            | 1                                                                |
| ldapUserFilterObjectclass     | mailUser                                                         |
| ldapUuidGroupAttribute        | auto                                                             |
| ldapUuidUserAttribute         | auto                                                             |
| turnOffCertCheck              | 0                                                                |
| useMemberOfToDetectMembership | 1                                                                |
+-------------------------------+------------------------------------------------------------------+
### Client configuration
**Browser:**
Firefox
**Operating system:**
Arch Linux
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
{"reqId":"XX","remoteAddr":"XX","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"File with id \\\"5029\\\" has not been found.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/vhosts\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/sharedstorage.php(90): OC\\\\Files\\\\View->getPath(5029)\\n#1 \\\/var\\\/vhosts\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/sharedstorage.php(581): OC\\\\Files\\\\Storage\\\\Shared->init()\\n#2 \\\/var\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(381): OC\\\\Files\\\\Storage\\\\Shared->getCache('', Object(OCA\\\\Files_Trashbin\\\\Storage))\\n#3 \\\/var\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1302): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->getCache('')\\n#4 \\\/var\\\/vhosts\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/serverfactory.php(125): OC\\\\Files\\\\View->getFileInfo('')\\n#5 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ServerFactory->OCA\\\\DAV\\\\Connector\\\\Sabre\\\\{closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/vhosts\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#7 \\\/var\\\/vhosts\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#8 \\\/var\\\/vhosts\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/vhosts\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/vhosts\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/vhosts\\\/own...')\\n#11 {main}\",\"File\":\"\\\/var\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1639}","level":3,"time":"2016-03-23T22:35:33+00:00"}
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
bug with 9.0.1 beta @icewind1991 can you have a look please? Did we change anything in this area? THX

**Comment by PVince81** [comment]
`OC\\Files\\View->getFileInfo('')`

Looks like this might be a single file share ?

@icewind1991 please have a look. Either it's another case of invalid shares or it's legitimate but the exception isn't caught cleanly.

**Comment by TomGem** [comment]
Fyi, I have the same exception with version 9.0.0.19.

After upgrading to OC9 I had the _"This directory is unavailable, please check the logs or contact the administrator"_ problem with several users.
Therefore I applied patch 23039:
```
wget https://patch-diff.githubusercontent.com/raw/owncloud/core/pull/23039.patch
patch -p1 < 23039.patch 
```

This solved the invalid shares problem (or/and deleted users in my case).

However, this patch maybe introduced the cron exception. I'm not sure, just a hint.


`occ app:list`
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0

Disabled:
  - bookmarks
  - encryption
  - files_external
  - firstrunwizard
  - user_external

**Comment by TomGem** [comment]
Just found a solution. I cleaned up my ldap remnants (deleted ldap users) as described in #23701.
Side effect: no more cron exceptions. :)

**Comment by Zibc** [comment]
Hi everyone,

I ran into the same issue last night after upgrading from 8.2.2 to 9.0.1.
I can't make the full bug report right now, I'll do that tonight or this week-end.

Debian8, MySql, Apache

**Comment by markus-k** [comment]
Same problem here with recently upgraded OC 9.0.1, cron is spamming me with this error. I don't have any external mounts, and ran the cli commands for cleaning up and rescanning, which didn't help.

**Comment by d--j** [comment]
You could try applying pull request #23972  
```shell
cd /path/to/owncloud
wget https://patch-diff.githubusercontent.com/raw/owncloud/core/pull/23972.patch
patch -p1 < 23972.patch
```

That worked for me.

**Comment by fuerst** [comment]
23972.patch does not apply to OC 9.0.1 because _lib/private/files/cache/scanner.php_ is different.

**Comment by d--j** [comment]
@fuerst Yes, sorry meanwhile the pull request does not apply cleanly on 9.0.1 anymore. Try this older version: [23972.patch](https://github.com/owncloud/core/files/222684/23972.patch.txt)

**Comment by PVince81** [comment]
Fix is here apparently: https://github.com/owncloud/core/pull/23972
