### ISSUE TITLE
open_basedir issue in router.php

### ISSUE THREAD

**Issue by hambiek** [owncloud/core#23533]
### Actual behaviour
On every run of the cron job, this is written to my logs:

`file_exists(): open_basedir restriction in effect. File(/appinfo/routes.php) is not within the allowed path(s): (...) at /usr/share/webapps/owncloud/lib/private/route/router.php#99`

Seems related to [#20128](https://github.com/owncloud/core/issues/20128), possibly something similar to [#22376](https://github.com/owncloud/core/pull/22376) needs to be done in `lib/private/route/router.php`?

### Server configuration
**Operating system**:
Arch Linux
**Web server:**
Nginx
**Database:**
mariaDB
**PHP version:**
7.0.4
**ownCloud version:**
9.0.0
**Updated from an older ownCloud or fresh install:**
updated
**Where did you install ownCloud from:**
arch linux packages

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - announcementcenter: true
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - documents: true
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_odfviewer: 0.1
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - logreader: true
  - music: true
  - ownnote: true
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
```

**The content of config/config.php:**

```
"instanceid": "**removed**",
"passwordsalt": "***REMOVED SENSITIVE VALUE***",
"secret": "***REMOVED SENSITIVE VALUE***",
"trusted_domains": [
    "**removed**",
    "**removed**",
],
"datadirectory": "\/storage\/data\/oc_data\/",
"overwrite.cli.url": "**removed**",
"dbtype": "mysql",
"version": "9.0.0.19",
"dbname": "ocdb",
"dbhost": "localhost",
"dbtableprefix": "oc_",
"dbuser": "***REMOVED SENSITIVE VALUE***",
"dbpassword": "***REMOVED SENSITIVE VALUE***",
"logtimezone": "UTC",
"installed": true,
"memcache.local": "\\OC\\Memcache\\APCu",
"apps_paths": [
    {
        "path": "\/usr\/share\/webapps\/owncloud\/apps",
        "url": "\/apps",
        "writable": false
    },
    {
        "path": "\/usr\/share\/webapps\/owncloud\/apps2",
        "url": "\/apps2",
        "writable": true
    }
],
"appstore.experimental.enabled": true,
"theme": "",
"loglevel": 1,
"maintenance": false,
"log_rotate_size": 52428800
```

**external storage**
no
**Are you using encryption:**
no

**Comment by LukasReschke** [comment]
Can you test https://github.com/owncloud/core/pull/23542? Thanks a lot.

**Comment by hambiek** [comment]
Patched `router.php`( [#23542](https://github.com/owncloud/core/pull/23542)): Now the cron job indeed runs without errors. Great, thanks a lot.
