### ISSUE TITLE
Feature: ability to delete contact_birthdays 

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#23537]
For the sake of my server resources, it would be great if I can delete the protected calendar contact_birthdays.

Currently you can see a delete button to it, but everytime you reload it comes back. Then, my cron is already slow and do not want it to compute something unnecessarily I do not need.

I think this ticket includes two things:
- make it deletable
- introduce a new option to prevent it from being auto-generated in the cron

For full story, see https://github.com/owncloud/calendar/issues/289#issuecomment-200569491

Thanks :)

**Comment by DeepDiver1975** [comment]
> Then, my cron is already slow and do not want it to compute something unnecessarily I do not need.

There is no cron involved - the birthday calendar is updated only if a contacts is added, edited or deleted. The performance impact is to be ignored from my pov.

In addition to the event driver approach there is a occ command which can be triggered to re-sync the calendar.

**Comment by binarykitchen** [comment]
@DeepDiver1975 oh okay. still, i d like to delete it. because it unnecessarily appears on other devices of mine and "steals" UI space

**Comment by DeepDiver1975** [comment]
Contributions are welcome! :wink:

Having a config switch should be rather easy to implement
