### ISSUE TITLE
Cannot share external storage mount points

### ISSUE THREAD

**Issue by tx7** [owncloud/core#23536]
### Steps to reproduce
1.Log into OC9 admin page.
2. Enabled External Storage>>Local
3. Put in the shared path, and enable sharing option

### Expected behaviour
Tell us what should happen
Local share is enabled.
### Actual behaviour
Tell us what happens instead
Local share is enabled, but it's not allow for admin user to re-share that share folder to other users or group.

Error Message: `Cannot increase permissions of /admin/files/Shared`

### Server configuration
**Operating system**:
 SMP Debian 3.16.7-ckt20-1+deb8u3~bpo70+1 (2016-01-19) x86_64 GNU/Linux
**Web server:**
Nginx 1.2.1-2.2+wheezy4 
**Database:**
5.5.47-0+deb7u1  

**PHP version:**
 5.4.45-0+deb7u2 

**ownCloud version:** (see ownCloud admin page)
9.0
**Updated from an older ownCloud or fresh install:**
Fresh Install

**Where did you install ownCloud from:**
/xxx/www/owncloud

**Signing status (ownCloud 9.0 and above):**

```

```

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_antivirus: 0.8.0.1
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - user_external
  - user_ldap

```


**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

{
    "system": {
        "instanceid": "ocboc03zyp7e",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.97",
            "***REMOVED SENSITIVE VALUE***""
        ],
        "datadirectory": "\/media\/54bf67db-da31-4c50-bb3c-27140944b223\/www\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***"",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "EST",
        "installed": true,
        "log_type": "owncloud",
        "log_authfailip": true,
        "allow_user_to_change_display_name": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": [
            [
                "localhost",
                11211
            ]
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "REMOVE SENSITIVE VALUE",
        "mail_domain": "yahoo.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.mail.yahoo.com",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Local
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
Cannot increase permissions of /admin/files/Shared
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Is your "Local" external storage read-only ?

CC @rullzer

**Comment by PVince81** [comment]
I'm able to reproduce this:

1. Create a folder "/srv/www/ocdata"
1. Set read-write web server permissions on it
1. Setup external storage of type "Local" as "/local"
1. Share "local" with another user "user1"

`data-permissions` is 23 and `data-share-permissions` is 31.

The share API call tries to share with permissions 31 but somehow it is refused, maybe because of the 23 ?

**Comment by tx7** [comment]
No, it has full permission.
As an admin, I have full access to the local drive via OC, but it wouldn't let me to re-share it to other users.
I gave full access to the folder for www-data:www-data.

**Comment by PVince81** [comment]
Note that for external storages, the "delete" permission is missing from the list since users are not allowed to delete the mount point. However, when sharing it should be allowed to share with 31 since we want users to be able to delete files inside the share.

Sharing a subfolder "/local/sub" works fine.
Also happens for other external storage mount points like "SMB".

@rullzer possibly another tricky permissions issue ?

**Comment by PVince81** [comment]
Still happens on stable9 / v9.0.1beta.

**Comment by PVince81** [comment]
On v8.2.3 it works correctly. The old API call sends the permissions as 31 too to share.php and it goes through:
```
action=share&itemType=folder&itemSource=9&shareType=0&shareWith=user1&permissions=31&itemSourceName=local
```

**Comment by tx7** [comment]
It worked for me on v8.2.2 with the same permission setup.

**Comment by rullzer** [comment]
yeah the old code did not properly check permissions. But I'm not sure how we should properly check this then. Because if the folder is empty. Then how do we know we actually have permissions to delete files inside.

@icewind1991 any idea how we can find all this out?

**Comment by rullzer** [comment]
The more I think about this the more I think we need new functionality for this.

I think we would need something like getSharePermissions for storages (maybe even just in the node api abstracted away). Since there ar so many possibilities else to cover in the share code.

**Comment by tx7** [comment]
Hi guys,

Is there a work around solution for this in the mean time?

**Comment by PVince81** [comment]
@rullzer maybe we can add a quick fix in the JS code specifically for external storage endpoints. What permissions would have to be passed to the sharing code to make it work ? (or anything to make it work like it did before)

**Comment by rullzer** [comment]
As discused with @PVince81 a quick hack could be to always allow delete permissions on mount points (that are not shares)... but we should fix it properly.

**Comment by rullzer** [comment]
PR in #23651

**Comment by tx7** [comment]
Guys,
Am I waiting for the new OC version for this solution?

**Comment by rullzer** [comment]
Will be in 9.0.1

**Comment by tx7** [comment]
Do you have an ETA?

Thanks.

**Comment by rullzer** [comment]
Planned for middle of next week

**Comment by PVince81** [comment]
https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule
