### ISSUE TITLE
make V8.2.3 available via repositories

### ISSUE THREAD

**Issue by brrrrrrrt** [owncloud/core#23538]
### Steps to reproduce
1. click the "Yellow Banner" telling that 8.2.3 is available
2. setup repository like recommended on the linked manual page
3. V8.2.3 is not available in the repo

### Expected behaviour
should upgrade to 8.2.3

### Actual behaviour
if updates are done through the package manager -> 9.0.0 gets installed

### Server configuration
**Operating system**:  Debian 8

**ownCloud version:** 8.2.2

i really thought - as 9.0.0 is the only version available via repo, it is stable - so i did the upgrade, which ended up in quite a mess, should have read the long list of known problems of version 9.0.0 before the upgrade, then i certainly wouldnt have done it. well, i had backups but didnt want to go back - and after some struggling i was able to get it working without major problems by using the 9.0.1beta from github. but with 9.0.0 from the repositories -> no way :-1: 

i am sure i will not be the only one stepping into that "trap", so it might be helpful for other users to have 8.2.3 in the repos too.

**Comment by DeepDiver1975** [comment]
@jnweiger

**Comment by RealRancor** [comment]
@brrrrrrrt 8.2.3 is available at https://download.owncloud.org/download/repositories/8.2/owncloud/ which is linked at https://owncloud.org/changelog/

**Comment by jnweiger** [comment]
@brrrrrrrt probably went this route:
https://doc.owncloud.org/server/8.2/admin_manual/maintenance/upgrade.html
-> chose first option, Linux Package Manager
https://doc.owncloud.org/server/8.2/admin_manual/maintenance/package_upgrade.html
-> choose 'The best method'  -> use ownCloud’s Open Build Service repository.
https://download.owncloud.org/download/repositories/stable/owncloud/
-> this features 9.0.0

Not exactly what the Update Notification banner promised.
I'd expect it would route users to 
https://download.owncloud.org/download/repositories/8.2/owncloud/

@carlaschroder do we want to explain the two possible routes 8.2.2->8.2.3 and 8.2.2->9.0.0 in https://doc.owncloud.org/server/8.2/admin_manual/maintenance/package_upgrade.html ?

**Comment by brrrrrrrt** [comment]
@RealRancor ah, thx, missed that one!

@jnweiger exactly, thats how it happened!

the Update Notification banner told me about 8.2.3 being released, i was already wondering when i ended up at a page where 9.0.0 seemed to be the only option.
