### ISSUE TITLE
Backgroundjob/cron improvements

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#23544]
The backgroundjob/cron system currently lacks some functionality that is getting more and more important.
1. Cron jobs can not give a time where they should run, e.g.:
   - Retention background jobs should be run outside the office hours, they may have huge load and it might also be confusing to users when the sync client suddenly frees their hdd from old files "randomly". (Ref https://github.com/owncloud/workflow/issues/53)
   - Daily acitivity emails should be send on/before the beginning of the (work) day and not 24h after the first action happened. It would also serve as a "what happened yesterday" recap. Similar for the weekly email, which should then be sent on/before monday morning.
2. Delayed tasks:
   - When adding a federated server we are syncing the address books with the federation app. If that fails, we don't need to retry it immediately. Would be nice to be able to set a background job to "run next in x minutes"
3. Allow multiple cron processes:
   - Currently only one cron can run at a time. That is because we lock the cron table. Instead we should only lock each task. Then multiple cron processes could run in parallel and work against the flood. Also each system cron should terminate after x minutes instead of running until all jobs have been executed, to make sure the number of cron-processes doesn't increase infinite. (This already happened to some universities, cron jobs running for more then an hour, because of the huge number of jobs.)
     The problem with long running tasks is that they require more and more memory, bringing your system to the limits.

cc @DeepDiver1975 @cmonteroluque @PVince81 @MTRichards

**Comment by cmonteroluque** [comment]
good ideas @nickvergessen . I am not sure where we can place this. I don't think 9.1 because it's going to be tight already, I presume a sysadmin can work around limitations in the meantime

**Comment by MorrisJobke** [comment]
So we aim for something like this: http://12factor.net/concurrency ;)

**Comment by nickvergessen** [comment]
## Proposal for problem 1

We need some more information a job can give. A min and max date and format. If the timestamp (beginning of the background job) happens to be between both, the job is executed, otherwise it's not. Example from retention:
* Format: `H:i`
* Min: `22:00`
* Max: `06:00`

**Problems:** The time should be specified by the admin. But that could then be the task of the retention app to allow this to be inserted.

## Proposal for problem 2

Simple column with a "first run" timestamp/datetime. At the same time we should call it "next run". This would allow us to check which jobs need to be executed, without having to load, instantiate them all, just to see oh we are not going to execute it now. We have to see how difficult the calculation for that is, in combination with problem 1, but should be doable.

## Proposal for problem 3

As already mentioned more columns in the jobs table. Cron processes lock a job by putting their "lock" in the table. When another process asks for the next job for execution, it receives the first job, with that has:

1. No lock
* Next run < process start

The global lock that we add at the moment is completly removed.

We can also add a max "get next time" for those cron processes. So if e.g. a job is already running longer then 10minutes, it does not call `getNext()` but terminates instead.

**Comment by DeepDiver1975** [comment]
# Alternate proposal for problem 3

0. a new background execution mode is introduced: job system
1. parallel execution using occ background:execute - which can be called multiple times on the same or different machines
2. exclusive access on the job entry in the jobs table is taken care of by using database technical like select for update
3. additional occ commands (later maybe web ui) are available for 

- list active executors including current job, execution duration, name, hostname, pid
- list jobs in the queue - total number and first 20
- remove jobs from the queue

**Comment by MorrisJobke** [comment]
I like @DeepDiver1975 s proposal.

**Comment by DeepDiver1975** [comment]
@karlitschek @cmonteroluque adding this to the 9.1 milestone - as discussed

**Comment by DeepDiver1975** [comment]
@icewind1991 with respect to your memory concerns - we can use a similar process model like laravel does https://github.com/laravel/framework/blob/5.2/src/Illuminate/Queue/Listener.php

**Comment by karlitschek** [comment]
ok. thanks

**Comment by MTRichards** [comment]
Estimation: 1 week for development

**Comment by cmonteroluque** [comment]
@DeepDiver1975 sure

**Comment by PVince81** [comment]
Moving to 9.2 for the remaining tasks

**Comment by PVince81** [comment]
Moving to backlog for now. Needs to be reconsidered and scheduled.

cc @pmaier1 more technical one involving background jobs / cron.
