### ISSUE TITLE
Scanner repeatedly scanning folders

### ISSUE THREAD

**Issue by icewind1991** [owncloud/core#23556]
In some situations (only with external storages?) the scanner will keep rescaning a folder every time it's accessed until the filescanner is ran from `occ` resulting into large performance issues due to the scanner accessing slow external storages.

This has been seen multiple times but no reproduction steps are known

see https://github.com/owncloud/core/issues/22463

**Comment by PVince81** [comment]
I wonder if this already existed in 8.2.3, as it is slower than 8.2.1, see https://github.com/owncloud/core/issues/23416#issuecomment-200776882

**Comment by icewind1991** [comment]
I think it does, I've run into it multiple times over the months but never paid to much attention to it since it only seems to happen sometimes

**Comment by PVince81** [comment]
@icewind1991 is this still an issue considering the recent changes to the scanner / background scan ?

**Comment by icewind1991** [comment]
afaik nothing has changed that would impact this

**Comment by PVince81** [comment]
Closing as I haven't seen this happen before. We'll reopen if observed again.
