### ISSUE TITLE
Still having issue: Two requests using FolderSync

### ISSUE THREAD

**Issue by loripino21** [owncloud/core#23559]
I just upgraded to owncloud 9.0.0, but I still have issue #21486 .

### Steps to reproduce
1. Just try to synchronize file using FolderSync.

### Expected behaviour
One request -> one upload

### Actual behaviour
Two requests are done before succeeding, causing useless uploads and waste of traffic:
192.168.0.101 - - [24/Mar/2016:14:43:37 +0100] "PUT /remote.php/webdav/Altro/[...].apk HTTP/1.1" 401 1053 "-" "android-cloud-api - Android 5.1.1" 338093
192.168.0.101 - lorenzo [24/Mar/2016:14:43:40 +0100] "PUT /remote.php/webdav/Altro/[...].apk HTTP/1.1" 201 875 "-" "android-cloud-api - Android 5.1.1" 7188100

### Server configuration
**Operating system**: xUbuntu 15.04

**Web server:** Apache 2

**Database:** MySQL 5.6

**PHP version:** 5.6.4

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** updated from OC 8.2.2 (or .2.1)

**Where did you install ownCloud from:** official package

**Signing status (ownCloud 9.0 and above):** 

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**

```
Only default and official ones, plus Tasks.
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => 'cloud..it',
    1 => '192.168.0.20',
    2 => '192.168.0.31',
  ),
  'overwritehost' => 'cloud..it',
  'datadirectory' => '/mnt/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'owncloud',
  'dbhost' => '192.168.0.100',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => '',
  'installed' => true,
  'loglevel' => 1,
  'theme' => '',
  'maintenance' => false,
  'secret' => '',
  'trashbin_retention_obligation' => 'auto',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'appstore.experimental.enabled' => true,
);
```

**Are you using external storage, if yes which one:** local, mounted smb storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** FolderSync

**Operating system:** Android

#### Web server error log
```
192.168.0.101 - - [24/Mar/2016:14:43:37 +0100] "PUT /remote.php/webdav/Altro/[...].apk HTTP/1.1" 401 1053 "-" "android-cloud-api - Android 5.1.1" 338093
192.168.0.101 - lorenzo [24/Mar/2016:14:43:40 +0100] "PUT /remote.php/webdav/Altro/[...].apk HTTP/1.1" 201 875 "-" "android-cloud-api - Android 5.1.1" 7188100
```

#### ownCloud log (data/owncloud.log)
```
no revelant data
```

**Comment by PVince81** [comment]
This is how basic auth works. The first request is there to ask what auth scheme to use, then the request responds with the appropriate header. Then the client uses that auth scheme to do the next request(s).

The question is whether FolderSync is implemented in a way that is able to keep session cookies ?
If not, then it won't be able to keep the session and has to reauthenticate for every request.

**Comment by PVince81** [comment]
CC @LukasReschke

**Comment by loripino21** [comment]
@PVince81 what you are saying sounds very strange to me. Please note that this issue repeats for EVERY file the app uploads, and causes the upload of the file to happen twice (even for big files! -> big lost of time and bandwidth).

**Comment by PVince81** [comment]
I'm not sure there is anything ownCloud can do about this, unless FolderSync would support keeping the session using cookies. Is there such an option in the app ?

Does it support token based authentication ? (which will be added in the future versions of ownCloud)

**Comment by PVince81** [comment]
CC @LukasReschke

**Comment by PVince81** [comment]
Or FolderSync needs to use the Authorization header and properly resend it as part of the protocol.

=> nothing that can be done on the OC side
