### ISSUE TITLE
API versioning for Webdav endpoints

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#23554]
Following the discussion at https://github.com/owncloud/core/issues/19988#issuecomment-200814386

To make it possible to keep stabler APIs especially in regards to federated sharing, we should look into providing versionned APIs.

Some OCS API endpoints already have versions like sharing.
The Webdav endpoints however, don't.

Considering that with Webdav there are several components involved in 9.0 (comments, systemtags, files, caldav, etc), we could change the webdav version scheme to have each app have an API version:
- `remote.php/dav/files/v1/...`
- `remote.php/dav/comments/v1/...`

The same for the public APIs used for federated sharing Webdav access:
- `public.php/webdav/v1/$token/...`

Etc.

Not sure whether this is useful or overkill.

In many cases for Webdav we can try avoiding breaking the behavior by introducing new properties instead of reusing old ones.

Versioning of APIs is mostly useful when the format of endpoints (paths), requests and others are changed, or the behavior of existing ones.

@DeepDiver1975 @MTRichards @rullzer @nickvergessen @schiesbn @icewind1991

**Comment by DeepDiver1975** [comment]
In case we really break the api that heavily we should look into adding new root resources to address these issues. This is basically required if we heavily change the protocol like e.g. use different verbs and different sub paths.

For anything else we can rely on content type - so in case we want to return a different structure for a resource we can set there version within the accept header.

**Comment by DeepDiver1975** [comment]
especially in case of files I see no reason to have files/v1 and files/v2 - what would be the difference?

**Comment by PVince81** [comment]
About adding new resources, yes that makes sense.

So if one day we'd really have a new "files" endpoint that works completely differently we'd simply call it "remote.php/dav/files.v2" or something.

This means that we don't need to introduce a "v1" right now. Closing
