### ISSUE TITLE
Files Application doesn't work / Webdav doesn't work?

### ISSUE THREAD

**Issue by drfuture** [owncloud/core#23560]
### Steps to reproduce
1. Login to Owncloud
2. Select "Files" (Dateien in German) Application
3. Wait....

### Expected behaviour
The Demo-Files (i found some on the Filesystem - this files normaly should be viewed after installation / creation a new account?) should be viewd, i should be able to upload files.

### Actual behaviour
The nice spinning-wheel is displayed ... as long as i wait.
If i drag&drop a File the Message "You don't have permission to upload ... here"
OwnCloud is fresh installed, no update etc. 

### Server configuration
**Operating system**:
Suse Linux 42.1

**Web server:**
Nginx 1.9.14 Build-String: ./configure --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --with-http_ssl_module --with-ipv6 --http-fastcgi-temp-path=/srv/www/temp/      - extra small for this test

**Database:**
MySQL 5.6.28

**PHP version:**
5.6.20 php-fpm as deamon / TCP-Socket

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
Manual from owncloud.org

**Signing status (ownCloud 9.0 and above):**
 No errors have been found.

**List of activated apps:**
Collaborative tags  0.2
Comments  0.2
Deleted files  0.8.0
First Run Wizard  1.1
Mail  0.4.2
Mail Template Editor  0.1
Notifications  0.2.3
PDF Viewer  0.8
Share Files  0.9.1
Text Editor  2.1
Update notification  0.1.0
Versions  1.2.0
Video player  0.9.8
Calendar  1.1
Contacts  1.1.0.0
Direct Menu  0.7.1

**The content of config/config.php:**
...
<?php
$CONFIG = array (
  'instanceid' => 'ocyizwfdz54j',
  'passwordsalt' => '00',
  'secret' => '00',
  'trusted_domains' => 
  array (
    0 => 'cloud.abc.de',
    1 => 'tester.de',
  ),
  'datadirectory' => '/home/www/abc.de/cloud/data',
  'overwrite.cli.url' => 'https://cloud.abc.de',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'user',
  'dbpassword' => 'password',
  'logtimezone' => 'UTC',
  'installed' => true,
  'defaultapp' => 'mail',
  'maintenance' => false,
  'loglevel' => 0,
);
...

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
IE11, Chrome 49

**Operating system:**
Windows 7, 11, Android 6

#### Web server error log
no entry found

#### ownCloud log (data/owncloud.log)
The last "Files" Test was today, so on the End of the Log, i found no new Log-Entry if i Start this App or Login again. I Pasted the Old messages of a Test with the Desktop-Owncloud APP to, there is a Login-Error with Auth. i Found a Hint to add a  "...pass_header Auhentification..." to nginx-config but no difference, so i can't login with the Desktop-Tool to and i think the Problem could be the same as cant open "Files"
>
Exception: {"Message":"HTTP/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\DAV\Exception\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#1 /home/www/abc.de/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 /home/www/abc.de/cloud/3rdparty/sabre/dav/lib/DAV/Server.php(446): Sabre\Event\EventEmitter->emit('beforeMethod', Array)\n#3 /home/www/abc.de/cloud/3rdparty/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#4 /home/www/abc.de/cloud/apps/dav/appinfo/v1/webdav.php(55): Sabre\DAV\Server->exec()\n#5 /home/www/abc.de/cloud/remote.php(138): require_once('/home/www/fho.d...')\n#6 {main}","File":"/home/www/abc.de/cloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","Line":188,"User":false}

**The content of nginx-vhost-config:**
...
upstream php-handler {
    server 127.0.0.1:1011;
    #server unix:/var/run/php5-fpm.sock;
}

server {
    listen 80;
    server_name cloud.fho.de;
    # enforce https
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl;
    server_name cloud.abc.de;

    ssl_certificate /etc/cert/certs/abc.de/fullchain.pem;
    ssl_certificate_key /etc/cert/certs/abc.de/privkey.pem;

    access_log /var/log/nginx/cloud.abc.de.access.log main;
    error_log /var/log/nginx/cloud.abc.de.error.log;

    # Add headers to serve security related headers
    # Before enabling Strict-Transport-Security headers please read into this topic first.
    #add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
    add_header X-Content-Type-Options nosniff;
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    add_header X-Download-Options noopen;
    add_header X-Permitted-Cross-Domain-Policies none;

    # Path to the root of your installation
    root /home/www/abc.de/cloud/;

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
        log_not_found off;
        access_log off;
    }

    # The following 2 rules are only needed for the user_webfinger app.
    # Uncomment it if you're planning to use this app.
    #rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
    #rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

    location = /.well-known/carddav { return 301 $scheme://$host/remote.php/dav; }
    location = /.well-known/caldav { return 301 $scheme://$host/remote.php/dav; }

    location /.well-known/acme-challenge {
        alias /srv/letsencrypt/challange;
    }

    # set max upload size
    client_max_body_size 512M;
    fastcgi_buffers 64 4K;

    # Disable gzip to avoid the removal of the ETag header
    gzip off;

    # Uncomment if your server is build with the ngx_pagespeed module
    # This module is currently not supported.
    #pagespeed off;

    error_page 403 /core/templates/403.php;
    error_page 404 /core/templates/404.php;

    location / {
        rewrite ^ /index.php$uri;
    }

    location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
    }
    location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
        deny all;
    location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
        deny all;
    }

    location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+|core/templates/40[34])\.php(?:$|/) {
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS on;
        fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice
        fastcgi_param front_controller_active true;
        fastcgi_pass php-handler;
        fastcgi_intercept_errors on;
    }

    location ~ ^/(?:updater|ocs-provider)(?:$|/) {
        try_files $uri/ =404;
        index index.php;
    }

    # Adding the cache control header for js and css files
    # Make sure it is BELOW the PHP block
    location ~* \.(?:css|js)$ {
        try_files $uri /index.php$uri$is_args$args;
        add_header Cache-Control "public, max-age=7200";
        # Add headers to serve security related headers
        # Before enabling Strict-Transport-Security headers please read into this topic first.
        #add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Robots-Tag none;
        add_header X-Download-Options noopen;
        add_header X-Permitted-Cross-Domain-Policies none;
        # Optional: Don't log access to assets
        access_log off;
    }
    location ~* \.(?:svg|gif|png|html|ttf|woff|ico|jpg|jpeg)$ {
        try_files $uri /index.php$uri$is_args$args;
        # Optional: Don't log access to other assets
        access_log off;
    }
}
...

**The content of nginx-BASIC-Config:**
...
user  wwwrun www;
worker_processes  1;
worker_rlimit_nofile 30000;
#error_log  error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    include ./vhost/*.vhost;
}
...

**The content of php-fpm-config:**
...
[cloud]
user = wwwrun
group = www
listen = 127.0.0.1:1011
listen.owner = wwwrun
listen.group = www
listen.mode = 0660

pm = dynamic
pm.max_children = 8
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 2
pm.max_requests = 10000

php_admin_value[disable_functions] = system
php_admin_flag[allow_url_fopen] = on
env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/sbin:/usr/sbin:/bin
env[TMP] = /srv/www/temp
env[TMPDIR] = /srv/www/temp
env[TEMP] = /srv/www/temp
...

**Comment by PVince81** [comment]
Can you go to the Admin page and check for the setup check errors ?
It is likely that something is misconfigured in your .htaccess, PHP or web server.

**Comment by drfuture** [comment]
hi, Thx for your answer,
the Error on Adminpage is:

- Ihr Webserver ist noch nicht hinreichend für Datei-Synchronisation konfiguriert, weil die WebDAV-Schnittstelle vermutlich defekt ist.

- Es wurde kein Memory Cache konfiguriert. Um die Leistung zu verbessern, konfigurieren Sie bitte einen Cache-Speicher, sofern vorhanden. Weitere Informationen finden Sie in unserer Dokumentation.

thx .htaccess has not changed from the official one, and nginx does not use any .htaccess.
the config is mostly from the installing guide on the onecloud wiki and a searched the last week a reason or a failur in my config. The only one i found was that i need full WebDav function on nginx so i installed the webdav_ext modul for "Propfind" and "options" that isn't build-in on nginx

but i forgot to post my webserver config:

nginx:
`upstream php-handler {
  server unix:/var/lib/php-fcgi_adm.sock;
}

server {
        listen 80;
        server_name cloud.abc.de;
        root /home/www/abc.de/;

        location /.well-known/acme-challenge {
                alias /srv/letsencrypt/challange;
        }

}

server {
        listen 443 ssl;
        server_name cloud.abc.de;
        root /home/www/abc.de/cloud/;

        access_log /var/log/nginx/cloud.abc.de.access.log main;
        error_log /var/log/nginx/cloud.abc.de.error.log;

        add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
        add_header X-Content-Type-Options nosniff;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Robots-Tag none;
        add_header X-Download-Options noopen;
        add_header X-Permitted-Cross-Domain-Policies none;

        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/cert/certs/abc.de/fullchain.pem;
        ssl_certificate_key /etc/cert/certs/abc.de/privkey.pem;
        ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
        ssl_prefer_server_ciphers on;

        ssl_stapling on;
        ssl_stapling_verify on;

        client_max_body_size 10G;

        # Disable gzip to avoid the removal of the ETag header
          gzip off;

        error_page 403 /core/templates/403.php;
        error_page 404 /core/templates/404.php;

        dav_methods PUT DELETE MKCOL COPY MOVE;
        dav_ext_methods PROPFIND OPTIONS;

        rewrite ^/.well-known/carddav /remote.php/dav/ permanent;
        rewrite ^/.well-known/caldav /remote.php/dav/ permanent;
        rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
        rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

        location = /robots.txt {
          allow all;
          log_not_found off;
          access_log off;
        }

        location ~ ^/(build|tests|config|lib|3rdparty|templates|data)/ {
                deny all;
        }

        location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
                deny all;
        }

        location / {
                rewrite ^/remote/(.*) /remote.php last;
                rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;
                try_files $uri $uri/ =404;
        }

        location ~ \.php(?:$|/) {
                fastcgi_pass_header Authorization;
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                fastcgi_param HTTPS on;
                fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice
                fastcgi_pass php-handler;
                fastcgi_intercept_errors on;
        }

        # Optional: set long EXPIRES header on static assets
        location ~* ^.+\.(jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
                expires 30d;
                # Optional: Don't log access to assets
                access_log off;
        }

}		`

additional fast-cgi php parameter:
`
fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;`

php-socket Config:
`user = www
group = www
listen = /var/lib/php-fcgi_adm.sock
listen.owner = www
listen.group = www
listen.mode = 0660

pm = dynamic
pm.max_children = 8
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 2
pm.max_requests = 10000

php_admin_value[disable_functions] = system
php_admin_flag[allow_url_fopen] = on
env[HOSTNAME] = $HOSTNAME
env[PATH] = /usr/local/bin:/usr/bin:/sbin:/usr/sbin:/bin
env[TMP] = /srv/www/temp
env[TMPDIR] = /srv/www/temp
env[TEMP] = /srv/www/temp`

the php-config herself is a bit long - so if a special parameter is necessary i can check this.
i set a logfile-path vor php execution herself and the log is empfy so in addition to the owncloud debug-information i postet - there should be no php-error.

**Comment by Xenopathic** [comment]
` dav_methods PUT DELETE MKCOL COPY MOVE;`

This tells nginx to handle WebDAV, which it should not. Please remove this line (and others related to the nginx DAV module).

**Comment by drfuture** [comment]
Hi Xenopathic,
i removed this lines and have no other line that i know that's webdav related. i added this lines after the problem with the option to fix it. But no difference.
So after remove the 2 lines i'ts the same. Nothing has changed.

i found a option for the php-fpm-worker "catch_workers_output = yes" - on a sabre<->nginx tutorial but if i enable that its the same too. :(

**Comment by drfuture** [comment]
Hello Again,
the Problem has not changed :(
Things i have done for the last weeks:

- update to 9.0.1
- update to php 5.6.20
- changed pw of my user to a very simple pw because there was a information of problems wie special charachters on webdav
- changed php-fpm form unix:sockets to tcp-ip because there was a problem with relay auth infos
- as posted above removed all dav_* on config

i removed the line "fastcgi_intercept_errors on" to - so i have more php-infos on owncloud.log but only that Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0

so if i use cal, files etc. whats in basic webdav i have no error and no function. If i try to connect by owncloud windows desktop client i have the Auth. error that i posted above.

any other ideas?

**Comment by drfuture** [comment]
I checked Webdav per Curl:
curl -D - -X PROPFIND -k https://Username:pw@cloud.fho.de/remote ... /Username/

there i can see my Folders on the .xml replay.
So Webdav normaly working?

Why i haven't any error by klicking / using "Files", "Calendar", Contacts etc. i have no Errors?
Can i activate other logging as "full log"

With other WebDav apps as OwnCloud, "Easy DAV" for example connect and answere that owncloud responded with a false .xml "multi-option response" not send or similar.

i removed now by a hint on Forum, http2 and full webdav support from nginx and upgraded to actual nginx 1.9.14 - no change.

**Comment by Xenopathic** [comment]
cc @DeepDiver1975

**Comment by josh4trunks** [comment]
@drfuture your nginx config is not correct for OC9
please see https://github.com/owncloud/documentation/wiki/ownCloud-9.x-nginx-config

**Comment by drfuture** [comment]
thx for info @josh4trunks i forgot this info - on the day i changed the nginx version i copyed this config 1:1 and only changed the root-dir and my socket-port .... sorry for that

maybe i can create a full list of my current config tomorrow to make it more easy to read.

**Comment by drfuture** [comment]
So i updated my Startposting to the actual config if fogot something just ask :+1:

**Comment by MorrisJobke** [comment]
> {"Message":"HTTP/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\DAV\Exception\NotAuthenticated",

This indeed looks like the webserver is not properly handling the authentication headers. As this is not really a bug in ownCloud but a setup issue I refer you to https://owncloud.org/support/ for more information about dealing with setup issues.

I also think that the linked Nginx docu by @josh4trunks works (at least @josh4trunks seems to have a working setup with Nginx and this configuration, right?)

Thanks :)

**Comment by josh4trunks** [comment]
yes, the nginx configuration in the wiki been confirmed by several people
