### ISSUE TITLE
VCARD VCAL verification

### ISSUE THREAD

**Issue by gvde** [owncloud/core#23566]
It would be helpful to have a tool which verifies the contacts/calendar objects in the database for RFC compliance and notify the user if there is something broken in the database.

Some possible ideas:
1. occ cli comand  (which should be part of the upgrade process as most often broken cards where created in previous versions...)
2. contacts & calendar app could notify the user if there is a broken object.
3. A warning should be part of the administration page like those integrity check and similar.

Of course, in normal processing broken cards should be handled gracefully and don't leave the carddav, caldav or web app in an undefined state...

**Comment by DeepDiver1975** [comment]
We should take care of a broken vcard or vcal shall not break the operations - we better log the broken entry and continue
