### ISSUE TITLE
WebDav problems - There was no handler found for this

### ISSUE THREAD

**Issue by mislav-eu** [owncloud/core#23565]
### Steps to reproduce
1. User1 have some files and shares folderX with some user/group
2. User1 or some other group maps his account under windows xp/windows 7/10/ubuntu 14 (webdav)
3. Try to open any shared file - you will be prompted and prompted for password few times and you just click cancel cancel and in the end files gets opened (on ubuntu sometimes the files doesn't even open)

### Expected behaviour
Tell us what should happen - shared files should be opened without any password prompts, just like normal user files which are not shared

### Actual behaviour
Tell us what happens instead - explained about in steps to reproduce

#### Server configuration
**Operating system**: Debian 8.3

**Web server:** Apache 2.4.10

**Database:** MariaDB 10

**PHP version:** PHP 5.6 

**ownCloud version:** (see ownCloud admin page) - 9.0.0 stable

**Updated from an older ownCloud or fresh install:** - updated from 8.2.2 stable

**Where did you install ownCloud from:** - from official sources list, through apt-get

**Signing status (ownCloud 9.0 and above):**  - how to get this?

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - documents
  - external
  - firstrunwizard
  - gallery
  - user_external
  - user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

```
{
    "system": {
        "instanceid": "XY",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XY"
        ],
        "datadirectory": "\/opt\/owncloud\/data",
        "overwrite.cli.url": "XY",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "XY",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 3,
        "logdateformat": "F d, Y H:i:s",
        "asset-pipeline.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "defaultapp": "files",
        "theme": "",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "ssl",
        "appstore.experimental.enabled": false,
        "singleuser": false,
        "knowledgebaseenabled": false,
        "check_for_working_htaccess": false,
        "log_rotate_size": 104857600,
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "XY",
        "mail_domain": "XY",
        "mail_smtphost": "XY",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "enable_previews": false,
        "filesystem_check_changes": 0,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "updatechecker": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/... - no external storage

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** - no external user-backend

### Client configuration 
**Browser:** Mozilla Firefox

**Operating system:** ubuntu 14.04 LTS (also tested on windows 7/10/xp)

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
Fatal 	webdav 	Exception: {"Message":"HTTP\/1.1 501 There was no handler found for this \"LOCK\" method","Exception":"Sabre\\DAV\\Exception\\NotImplemented","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#2 \/var\/www\/owncloud\/remote.php(138): require_once('\/var\/www\/ownclo...')\n#3 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":462,"User":"mMislavB"} 	2016-03-24T14:39:58+00:00

Fatal 	webdav 	Exception: {"Message":"HTTP\/1.1 501 There was no handler found for this \"LOCK\" method","Exception":"Sabre\\DAV\\Exception\\NotImplemented","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#2 \/var\/www\/owncloud\/remote.php(138): require_once('\/var\/www\/ownclo...')\n#3 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":462,"User":"mMislavB"} 	2016-03-24T14:39:51+00:00

Fatal 	webdav 	Exception: {"Message":"HTTP\/1.1 501 There was no handler found for this \"LOCK\" method","Exception":"Sabre\\DAV\\Exception\\NotImplemented","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#2 \/var\/www\/owncloud\/remote.php(138): require_once('\/var\/www\/ownclo...')\n#3 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":462,"User":"mMislavA"}

**Comment by DeepDiver1975** [comment]
@LukasReschke some more user agents for the locking fake provider?

**Comment by DeepDiver1975** [comment]
@mislav-eu we need to explicitly know which client is producing this error - THX

**Comment by PVince81** [comment]
> User1 or some other group maps his account under windows xp/windows 7/10/ubuntu 14 (webdav)

Can you elaborate ? What does "maps" mean here ? Is the the desktop client, or a specific Webdav client ?

**Comment by mislav-eu** [comment]
@DeepDiver1975  @PVince81  

I apologize. Maps = mapping the network drive. In other words for windows XP/7/10 I've tested the following:
Mapping Drives With Windows Explorer - https://doc.owncloud.org/server/9.0/user_manual/files/access_webdav.html#mapping-drives-with-windows-explorer

on my ubuntu 14.04 machine, I've tested with: Nautilus File Manager - https://doc.owncloud.org/server/9.0/user_manual/files/access_webdav.html#nautilus-file-manager

**Comment by PVince81** [comment]
@mislav-eu did you still see this in recent versions of OC ?
