### ISSUE TITLE
Theming image path

### ISSUE THREAD

**Issue by davidak** [owncloud/core#23569]
### Steps to reproduce
1. put an image named logo-mail.gif in the theme directory like `/var/www/owncloud/themes/<theme name>/core/img/logo-mail.gif`
2. open https://owncloud.kunde.de/core/img/logo-mail.gif in browser

### Expected behaviour
my image is served

### Actual behaviour
the default image is served

### Server configuration
**Operating system**: Ubuntu Server 14.04 LTS

**Web server:** Apache 2.4

**Database:** MySQL

**PHP version:** PHP/5.5.9-1ubuntu4.13

**ownCloud version:** 8.2.1 Community

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** manual with tar from owncloud.org

**Signing status (ownCloud 9.0 and above):** no

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP (ActiveDirectory)

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Chromium Version 46.0.2490.71 (64-bit)

**Operating system:** OS X 10.9.5

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Please use the issue template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

It would be good to know at least what ownCloud version you are using...

**Comment by PVince81** [comment]
Also note that this is a bug tracker, not a support platform.
For support, see https://owncloud.org/support

If you still think this is a bug, then please provide the information above.

**Comment by davidak** [comment]
@PVince81 sorry. i thought it would be easier only have the relevant informations. i don't have access to the server via ssh right now since it is an on-premise installation at one of our customers.

**Comment by LukasReschke** [comment]
Well. If you open the generic URL it will always serve the default. Use the ownCloud functions for templating in your app which will automatically resolve the correct image for you.

Anyways. Vincent is right, the mailing list is a better place for this.

**Comment by agross** [comment]
@LukasReschke 

> Use the ownCloud functions for templating in your app which will automatically resolve the correct image for you.

Which would be the function for templating? I use the default mail template, but I cannot get a themed `logo-mail.gif` to appear in my sharing mails.

```
<td bgcolor="<?php p($theme->getMailHeaderColor());?>">
<img src="<?php p(\OC::$server->getURLGenerator()->getAbsoluteURL(image_path('', 'logo-mail.gif'))); ?>" alt="<?php p($theme->getName()); ?>"/>
</td>
```
