### ISSUE TITLE
Error after upgrade owncloud via web interface

### ISSUE THREAD

**Issue by Thomas301263** [owncloud/core#23573]
Before the upgrade everything works well. After that no sync was working.
The error Message on admin page is:
Dein Webserver ist noch nicht hinreichend für Datei-Synchronisation konfiguriert, weil die WebDAV-Schnittstelle vermutlich defekt ist.
### Steps to reproduce
1.Update from 8.1.5.2-744609ac to 8.2.3.2
2.
3.

### Expected behaviour
Tell us what should happen
All should work normal after the upgrade cause it was working perfect before
### Actual behaviour
Tell us what happens instead
Sync between server and client is not working. After reinstallation of CARDDAV and CALDAV both are working again but the sql database could not stored back. 
### Server configuration
**Operating system**:
uname -a
Linux sielstetten 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
**Web server:**
apache2 -v
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2016-01-05T00:00:00
**Database:**
apt-cache show mysql-server | grep Version
Version: 5.5.47-0ubuntu0.14.04.1

**PHP version:**
php -v
PHP 5.6.19-1+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologie
**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.3 (stable) 
**Updated from an older ownCloud or fresh install:**
Update from 8.1.5.2-744609ac to 8.2.3.2
**Where did you install ownCloud from:**
Installation from webside like recomendations
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Not Found

The requested URL /index.php/settings/integrity/failed was not found on this server.
Apache/2.4.18 (Ubuntu) Server at 192.168.178.10 Port 443

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - calendar: 0.8.2
  - contacts: 0.5.0.0
  - external: 1.2
  - files: 1.4.4
  - files_antivirus: 0.8.0.1
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_unsharing: 0.4
  - files_versions: 1.2.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - libreonline: 0.1
  - music: 0.3.10
  - notifications: 0.2.3
  - ojsxc: 3.0.0
  - provisioning_api: 0.4.1
  - updater: 0.6
  - user_external: 0.4
  - weather: 1.3.1
Disabled:
  - appframework
  - chat
  - documents
  - encryption
  - files_embeddedvideo
  - files_locking
  - files_videojs-sublime
  - files_w2g
  - galleryplus
  - rainloop
  - search_lucene
  - sharelinks
  - templateeditor
  - user_ldap
  - user_webdavauth
  - videos

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc9a9ad333c2",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.178.10",
            "sielstetten.selfhost.me",
            "sielstetten"
        ],
        "datadirectory": "\/media\/cloud\/data",
        "dbtype": "mysql",
        "version": "8.2.3.2",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "smtp.live.com",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "owncloud",
        "overwrite.cli.url": "\/owncloud",
        "updatechecker": true,
        "has_internet_connection": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "appcodechecker": true,
        "loglevel": 0,
        "theme": "",
        "maintenance": false,
        "mail_smtpport": "587",
        "overwritewebroot": "\/owncloud",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "0": true,
        "enable_avatars": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "debug": true,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "user_webdavauth_url": "https:\/\/192.168.178.10\/webdav"
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 45.0
**Operating system:**
uname -a
Linux thomas 3.13.0-65-generic #106~precise1-Ubuntu SMP Fri Oct 2 22:06:48 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
#### Web server error log
```
All .logs are in attached file .zip
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
[logs.zip](https://github.com/owncloud/core/files/188347/logs.zip)
[syslog.zip](https://github.com/owncloud/core/files/188350/syslog.zip)

**Comment by tflidd** [comment]
You wrote that you don't use an external authentication backend, so I would disable `user_external`. And why do you have this is in your config-file?
````
"user_webdavauth_url": "https:\/\/192.168.178.10\/webdav"
````

Can you elaborate on your installation and upgrade procedure (manual/packet-manager/updater-app)? The broken webdav interface, is this a message from the owncloud-client or a native webdav-client?

**Comment by Thomas301263** [comment]
```
"user_webdavauth_url": "https:\/\/192.168.178.10\/webdav"
```
that's I have done a long time ago. I started to use owncloud V4 and remember that once there was something like that in documentation. I will uncomment it now.
I will disable user_external as well and try.
The message occurs if I open the admin => administration page and the owncloud clients 
(laptop and tablet) are not able to connect to owncloud. 
The client (laptop) message is that the dav module is not working and I do not understand why.

**Comment by Thomas301263** [comment]
ok all changes are done but the result is the same.

The upgrade procedure was like every time the same. I started the upgrade of owncloud from web as administrator and all was working well. If there were apps which were deactivated I activated that again which I was able to activate. The others I took the new one from the owncloud app site in the internet. All was working well starting from v5 - v6 - v7 - v8.1.x 
Maybe it can be a problem cause there also were updates of php5 and apache but I think there is all ok cause I can reach the server by https://localhost or http://localhost.
If you like I can open ssh that you can doublecheck all.

**Comment by tflidd** [comment]
If you have full access to your system, you can start the upgrade process from your terminal (you don't run into timeouts and you'll get some feedback):
````
sudo -u www-data php /var/www/owncloud/occ upgrade
````

Why, how and when did you update php? Did it work with OC 8.1.5? Your basic system is Ubuntu 14.04?

You apache-config is like in the documentation? https://doc.owncloud.org/server/8.2/admin_manual/installation/source_installation.html#apache-web-server-configuration

**Comment by Thomas301263** [comment]
Apache and php are updatet automatically if there are new packets by ubuntu server.
Yes am using Ubuntu 14.04 and the apache configuration is like documentation.
Now I try to do the upgrade again.

**Comment by Thomas301263** [comment]
```
root@sielstetten:~# sudo -u www-data php /var/www/owncloud/occ upgrade
ownCloud is already latest version
```
Before the last upgrade all was working that's why am wondering now.

**Comment by Thomas301263** [comment]
After a complete new installation of owncloud it is working again.
It had nothing to do with configuration of apache, php or config.php
It was simple a mistake of upgrading.

**Comment by PVince81** [comment]
Ok thanks, closing then
