### ISSUE TITLE
Mail linked to calendar is not the one choosen when i create / accept an event on Thunderbird

### ISSUE THREAD

**Issue by crazy-max** [owncloud/core#23578]
Hi!

Originally created on owncloud calendar repository (https://github.com/owncloud/calendar/issues/369).
### Steps to reproduce
1. Create a new calendar on Owncloud 9 on my account user@mail.com
2. Copy the caldav link on Thunderbird 38.7.0 (latest) to create a new calendar
3. Click on properties for the calendar created on Thunderbird and link an email address thunmail@mail.com
4. Create an event
### Expected behaviour

The mail choosen on Thunderbird calendar when i create or accept an event for this calendar must be the one selected in Thunderbird (thunmail@mail.com) like it does on Owncloud 8.2.
### Actual behaviour

When an event is created or accepted on Thunderbird, the mail address is not the one choosen on Thunderbird calendar (thundermail@mail.com) but the one on Owncloud (user@mail.com)
### Server configuration

**Operating system**:
Debian GNU/Linux 8 (jessie) 64bits

**Web server:**
Apache 2.4.10

**Database:**
MariaDB 10.1.12

**PHP version:**
PHP 5.6.17

**ownCloud version:** (see ownCloud admin page)
9.0.0.19

**Calendar version:** (see ownCloud apps page)
1.0

**Updated from an older ownCloud or fresh install:**
Fresh install

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "octsmzfmuh8e",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.0.0.1"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "logdateformat": "Y-m-d H:i:s",
        "logtimezone": "Europe\/Paris",
        "log_authfailip": true,
        "cron_log": true,
        "forcessl": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "enable_previews": false,
        "trashbin_retention_obligation": "7,15"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

NO

**Are you using encryption:** yes/no

NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

NO
### Client configuration

**Browser:**
Firefox 45.0.1

**Operating system:**
Debian Jessie

**CalDAV-clients:**
Thunderbird 38.7.0
DavDroid 0.9.1.3 (downloaded via Fdroid)

**Comment by crazy-max** [comment]
Hi @DeepDiver1975 !
Do you have an idea of the release date of a patch?
Thanks!

**Comment by DeepDiver1975** [comment]
@georgehrke any idea what could be different with respect to the dav backend implementation?
Is Thunderbird storing the email address within the calendar properties and we should use them within the event?

**Comment by georgehrke** [comment]
I setup thunderbird according to this bug report but I can't find the email address I used nowhere in the db 😕

**Comment by georgehrke** [comment]
It's in the `ORGANIZER` property of the corresponding event though

**Comment by georgehrke** [comment]
@DeepDiver1975 Why the `needs info` label? The email thunderbird wants the server to use is in the `ORGANIZER` property of the event.

**Comment by DeepDiver1975** [comment]
@georgehrke did you manage to reproduce @crazy-max issue or does it work as it's supposed to .... THX

**Comment by georgehrke** [comment]
On master it doesn't send no mail at all when the email in thunderbird doesn't match the one from the personal settings.

**Comment by DeepDiver1975** [comment]
> On master it doesn't send no mail at all when the email in thunderbird doesn't match the one from the personal settings.

which is actually quite clear - only if the organizer changes the event notifications are sent out

**Comment by georgehrke** [comment]
Well, but the organizer is defined in each event. The email set in the personal settings should be irrelevant here (imho)

**Comment by PVince81** [comment]
Any update ? Is this still an issue with recent versions ?

**Comment by crazy-max** [comment]
Hi, i have upgraded to 9.1.3, i will try to reproduce
I keep you in touch

**Comment by crazy-max** [comment]
Same issue :disappointed:

### Steps to reproduce
1. Create a new calendar on Owncloud 9.1.3.1 on my account user@mail.com
2. Copy the caldav link on Thunderbird 45.5.1 (latest) to create a new calendar
3. Click on properties for the calendar created on Thunderbird and link an email address thunmail@mail.com
4. Create an event

### Expected behaviour
The mail choosen on Thunderbird calendar when i create or accept an event for this calendar must be the one selected in Thunderbird (thunmail@mail.com) like it does on Owncloud 8.2.

### Actual behaviour
When an event is created or accepted on Thunderbird, the mail address is not the one choosen on Thunderbird calendar (thundermail@mail.com) but the one on Owncloud (user@mail.com)

### Server configuration

**Operating system**:
Debian GNU/Linux 8 (jessie) 64bits

**Web server:**
Apache 2.4.10

**Database:**
MariaDB 10.1.20

**PHP version:**
PHP 5.6.29

**ownCloud version:** (see ownCloud admin page)
9.1.3.1

**Calendar version:** (see ownCloud apps page)
1.4.1

**Updated from an older ownCloud or fresh install:**
Fresh install

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 0.3.0
  - contacts: 1.5.1
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - ownnote: 1.08
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - news
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "octsmzfmuh8e",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.0.0.1"
        ],
        "datadirectory": "\/var\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.1.3.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 1,
        "logdateformat": "Y-m-d H:i:s",
        "logtimezone": "Europe\/Paris",
        "log_authfailip": true,
        "cron_log": true,
        "forcessl": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "enable_previews": false,
        "trashbin_retention_obligation": "7,15",
        "maintenance": false,
        "htaccess.RewriteBase": "\/owncloud"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

NO

**Are you using encryption:** yes/no

NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

NO
### Client configuration

**Browser:**
Chrome 55.0.2900.0

**Operating system:**
Debian Jessie

**CalDAV-clients:**
Thunderbird 45.5.1
DavDroid 1.3.4.1 (downloaded via Fdroid)

**Comment by crazy-max** [comment]
Same behavior on eM Client 7

**Comment by crazy-max** [comment]
Any news about this issue ?

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
