### ISSUE TITLE
calendar generates broken links to core-js files

### ISSUE THREAD

**Issue by fireba11** [owncloud/core#23587]
### Steps to reproduce
1. open /apps/calendar/ in a browser

### Expected behaviour
calendar displays fine as usual

### Actual behaviour
no calendar entries are displayed

log says access to web/calendar/css/../../../core/css/multiselect.css
and web/calendar/js/../../../core/js/multiselect.js is blocked by php open_basedir.

that is correct since those paths would be outside or ownclouds web

### Server configuration
**Operating system**:
debian 8.3
**Web server:**
apache 2.4.10-10+deb8u4
**Database:**
mysql 14.14
**PHP version:**
5.6.17-0+deb8u1
**ownCloud version:** (see ownCloud admin page)
9.0.0
**Updated from an older ownCloud or fresh install:**
updated (removed everythin except config.php and data folder, then installed with web installer
**Where did you install ownCloud from:**
https://download.owncloud.com/download/community/setup-owncloud.php
**Signing status (ownCloud 9.0 and above):**
Results
=======
- core
	- INVALID_HASH
		- .htaccess
		- .user.ini
**List of activated apps:**
Enabled:

    activity: 2.2.1
    calendar: true
    comments: 0.2
    contacts: true
    dav: 0.1.5
    federatedfilesharing: 0.1.0
    federation: 0.0.4
    files: 1.4.4
    files_external: 0.5.2
    files_pdfviewer: 0.8
    files_sharing: 0.9.1
    files_texteditor: 2.1
    files_trashbin: 0.8.0
    files_versions: 1.2.0
    files_videoplayer: 0.9.8
    firstrunwizard: 1.1
    gallery: 14.5.0
    notifications: 0.2.3
    provisioning_api: 0.4.1
    systemtags: 0.2
    templateeditor: 0.1
    updatenotification: 0.1.0
	
Disabled:
    encryption
    external
    user_external
    user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/clients\/client1\/web43\/web\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "c1owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": 0,
        "check_for_working_webdav": false,
        "theme": "",
        "trusted_domains": [
            "owncloud.somedomain.com",
            "owncloud.somedomain.com"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "somedomain.com",
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto,30",
        "versions_retention_obligation": "auto,90",
        "maintenance": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
FF 45.0.1
**Operating system:**
Win10

**Comment by RealRancor** [comment]
@fireba11 Please fill out the complete issue template instead of removing it. Currently even the basic info like webserver and so on is missing.

**Comment by mundschenk-at** [comment]
I can confirm the issue for nginx/FreeBSD as well.

**Comment by PVince81** [comment]
Possibly routing issue @LukasReschke @DeepDiver1975 

@mundschenk-at is it also a brand new install for you ?

@mundschenk-at @fireba11 do you guys have the string "oc" in your domain name or ownCloud URL path ?

**Comment by mundschenk-at** [comment]
@PVince81 No, it's updated as well.

Regarding OC: The exact error message is:
`is_file(): open_basedir restriction in effect. File(<owncloud-dir>/calendar/css/../../../core/css/multiselect.css) is not within the allowed path(s): (<owncloud-dir>:<some other paths>) at <owncloud-dir>/lib/private/template/resourcelocator.php#101`

The origin for that spurious resource call is most likely https://github.com/owncloud/calendar/blob/f8cd928be631680f92bd59be798cf2dea1fe988a/templates/main.php#L27 so this issue should probably be moved to the `calendar` repository.

**Comment by RealRancor** [comment]
Matching report in the calendar repo: https://github.com/owncloud/calendar/issues/475

If its clear if core or calendar is creating this issue we can close one of those.

**Comment by georgehrke** [comment]
bug in calendar

**Comment by georgehrke** [comment]
it might actually be a bug in core where it tries to find the css file und checks different directories.

(Anyway, https://github.com/owncloud/calendar/blob/master/templates/main.php#L27 is definitely not the intended way to include this)

**Comment by fireba11** [comment]
Note: It's still flagged as "need info" but i don't know what info is needed. If that is still valid please specify so i can add it :-)

**Comment by PVince81** [comment]
Is this still happening with 9.0.4 and the latest calendar version ?

**Comment by georgehrke** [comment]
No, we removed the unnecessary js/css includes in the calendar app
