### ISSUE TITLE
Change name of files directly in the sidebar by clicking on the filename

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#23588]

**Comment by PVince81** [comment]
@owncloud/designers @schiesbn @nickvergessen

**Comment by skjnldsv** [comment]
Good idea, but the click is already used to enter a dir or download a file, should we remove those actions and add the rename instead? Or rename on double click for example?

**Comment by aspdye** [comment]
Or we provide an edit button (pencil) next to the filename :wink:

**Comment by skjnldsv** [comment]
We can also :+1:

**Comment by stefan-niedermann** [comment]
> Or rename on double click for example?

No double click, no context menu. It is hard to discover and will not work on mobile e.g.

> Or we provide an edit button (pencil) next to the filename :wink:

There has been a button which has moved to the dot-dot-dot-menu. One could discuss if edit is a highly-used action to give it a special behaviour again.

**Comment by skjnldsv** [comment]
@stefan-niedermann Long click for mobile?
Could be good, I wouldn't mind!

**Comment by aspdye** [comment]
@skjnldsv I don't know whether long click would work on **all** mobile devices (android, iOS, ...). Personally - I have never seen something like this on a mobile browser :confused:

**Comment by jancborchardt** [comment]
We shall never ever use long-click or double-click in the interface. _Ever_. They are not easily discoverable, not consistent across platfroms and not necessary in the first place.

I’d say in the sidebar clicking on the name to make it editable is fine. We don’t need that to have the action for navigating into it (for folders) or downloading/viewing (for files). It’s a nice enhancement.
