### ISSUE TITLE
Foldersync and Owncloud 9 

### ISSUE THREAD

**Issue by Happyfeet01** [owncloud/core#23580]
--> 
### Steps to reproduce
1. Try to upload an Mp4 video file with Foldersync for Android over webdav 

### Actual behaviour
Try to upload an mp4 videofile. 
Upload stops. 

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache2 2.4.7
**Database:**
mysql 14.14
**PHP version:**
5.5.9
**ownCloud version:** (see ownCloud admin page)
9
**Updated from an older ownCloud or fresh install:**
From OC 8.1 
**Where did you install ownCloud from:**
Manual install 

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - disablerememberlogin: 0.3
  - documents: true
  - encryption: 1.2.0
  - fbsync: 1.8.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_antivirus: 0.8.0.1
  - files_external: 0.5.2
  - files_mv: true
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - hls_streamplayer: true
  - html5_videoplayer: true
  - music: true
  - news: 7.1.2
  - notes: true
  - notifications: 0.2.3
  - ocdownloader: 1.5
  - provisioning_api: 0.4.1
  - shorten: 0.0.15
  - systemtags: 0.2
  - tasks: 0.9.0
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - external
  - libreonline
  - ownnote
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocpsovzwa7ww",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud-surfer.eu"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "datadirectory": "\/mnt\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/81.169.130.87\/",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "loglevel": 0,
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "singleuser": false,
        "mail_smtpmode": "php",
        "mail_from_address": "lars",
        "mail_domain": "cloud-surfer.eu",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.cloud-surfer.eu",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "updatechecker": true,
        "theme": ""
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Google drive 
**Are you using encryption:** yes/no
Yes

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```

```

#### ownCloud log (data/owncloud.log)
```
No relevant data 
```

#### foldersync log

``````
Write error ssl=0xb3694380:I/O Error during system call ;broken pipe
```

**Comment by PVince81** [comment]
> Write error ssl=0xb3694380:I/O Error during system call ;broken pipe

This looks like it might be an env issue / setup error, or timeout ?

Can you post the matching access_log entries to see how folder sync does its upload ?

**Comment by loripino21** [comment]
I have a similar issue. Uploading big mp4 files with FolderSync always fail.

**Comment by Happyfeet01** [comment]
Sorry for late response. The access say this:

'Error
151.252.218.xxx
404
PROPFIND /remote.php/webdav/SofortUpload/Bilder/MOV_0001.mp4 HTTP/1.1'

**Comment by Happyfeet01** [comment]
And this:

401
PROPFIND /remote.php/webdav/SofortUpload/Bilder/ HTTP/1.1
android-cloud-api - Android 6.0.1

**Comment by Happyfeet01** [comment]
Maybe similar to this issue an timeout error. https://github.com/owncloud/client/issues/1899

**Comment by PVince81** [comment]
If there is nothing in owncloud.log during the upload then maybe there's a timeout error.

Are you able to upload small mp4 files, less than 10 MB ?

**Comment by PVince81** [comment]
How about other big files that are not mp4 ?

Note that some web servers or web server modules (apache modules) might mess up with special file types. Make sure you don't have any such extra modules enabled.

**Comment by PVince81** [comment]
Closing due to lack of feedback
