### ISSUE TITLE
404 right after install (apache, php7)

### ISSUE THREAD

**Issue by vkalinsky** [owncloud/core#23584]
### Steps to reproduce
1. Install apache2
2. Install php7.0
3. git clone owncloud

### Actual behaviour
404: The requested URL /owncloud/index.php/apps/files/ was not found on this server.

### Server configuration
**Operating system**:
Linux mothership 4.2.0-34-generic #39~14.04.1-Ubuntu SMP Fri Mar 11 11:38:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
Apache/2.4.7

**Database:**
mysql

**PHP version:**
7.0.4

**ownCloud version:** (see ownCloud admin page)
9.0.1alpha (git/master)

**Updated from an older ownCloud or fresh install:**
Fresh, copied config.php from older setup.

**Where did you install ownCloud from:**
github

**Signing status (ownCloud 9.0 and above):**
n/a

**List of activated apps:**
n/a

**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => 'octzv952nd1l',
  'trusted_domains' => 
  array (
    0 => 'mothership.local',
  ),
  'datadirectory' => '/owncloud',
  'overwrite.cli.url' => 'http://mothership.local/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.0.0',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'integrity.check.disabled' => true,
);

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by tflidd** [comment]
Did you adopt your apache-configuration:
https://doc.owncloud.org/server/9.0/admin_manual/installation/source_installation.html

The github-master is the development version and should be used in productive environments, rather use the archives from https://owncloud.org/install/

**Comment by Xenopathic** [comment]
A 404 error indicates you have a problem with your environment, please contact https://owncloud.org/support for help
