### ISSUE TITLE
OC 9.0.0: Log file PHP Error: "Undefined index: newVersionString at owncloud/apps/updatenotification/templates/admin.php#8"

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/core#23586]
New installation / admin page shows PHP Error(s):

OC 9.0.0: Log file PHP Error:
"Undefined index: newVersionString at owncloud/apps/updatenotification/templates/admin.php#8"

**Comment by DeepDiver1975** [comment]
Duplicate - will be fixed with 9.0.1

**Comment by Wikinaut** [comment]
@DeepDiver1975 duplicate to which issue ? (I looked before posting, but could not find it)
