### ISSUE TITLE
OCP\IConfig->setUserValue not setting values on stable9, master and postgres

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/core#23583]
### Steps to reproduce
1. Install a fresh core with postgres
2. Enable the News app 7.1.2
3. Toggle a setting in the News app and reload the page

### Expected behaviour
The setting is persistet after a reload

### Actual behaviour
The setting is not persistet after a reload

### Server configuration
**Operating system**: Arch Linux

**Web server:** PHP built in and Apache

**Database:** Postgres

**PHP version:** 5.6 and 7

**ownCloud version:** stable9 and master

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** github

**List of activated apps:** 
```
Enabled:
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_sharing: 0.9.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - news: 7.1.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - files_external
  - testing
  - user_ldap
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocfprux1i8my',
  'passwordsalt' => 'hCqHmVq47UiamfgB11BuhvFZchT1Sj',
  'secret' => 'cVqOpPMBwuMCA3465xkEGKJykmBKWfbi95Y5wADQ1rJ7lxkX',
  'trusted_domains' => 
  array (
    0 => 'localhost:8080',
  ),
  'datadirectory' => '/home/bernhard/programming/core9/data',
  'overwrite.cli.url' => 'http://localhost:8080',
  'dbtype' => 'pgsql',
  'version' => '9.0.1.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => '2o3y9g0oawpbh0wrf74klu0r4d0mss',
  'logtimezone' => 'UTC',
  'installed' => true,
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Latest Firefox

**Operating system:** Arch Linux

#### Web server error log
Nothing in the logs

#### ownCloud log (data/owncloud.log)
Nothing in the logs

#### Browser log
Nothing in the logs

@LukasReschke @DeepDiver1975 @MorrisJobke @PVince81

**Comment by BernhardPosselt** [comment]
Everything works fine with sqlite btw

**Comment by BernhardPosselt** [comment]
Also probably has to do with setting boolean values (a guess)

**Comment by BernhardPosselt** [comment]
Ok, traced it down to the following: setting booleans on sqlite are stored as 1 or 0, for postgres they are saved as f and t.

**Comment by BernhardPosselt** [comment]
The solution is probably to either cast it to 1 and 0 or throw an exception if a boolean is being set

**Comment by PVince81** [comment]
Not a regression, then ?

**Comment by BernhardPosselt** [comment]
Very likely not

**Comment by robled** [comment]
Is there any way to update to the release that resolves this issue with the integrated updater?  Version 8 is not available to me when I have it check for updates.

**Comment by BernhardPosselt** [comment]
@robled https://github.com/owncloud/appstore-issues/issues/55 

For now until the app store issue is fixed you need to manually download the zip from github: https://github.com/owncloud/news/releases shows all releases, this is the zip https://github.com/owncloud/news/releases/download/8.0.0/news.tar.gz
