### ISSUE TITLE
[OC 9.0.0] Can't change language on Personal page

### ISSUE THREAD

**Issue by josh4trunks** [owncloud/core#23585]
### Steps to reproduce
1. Personal > Language
2. Language = Anything but the default English
3. Refresh page and it is reset

### Expected behaviour
Language changes should be saved like the other settings on that page

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: FreeBSD 10.1 64bit

**Web server:** NGINX

**Database:** MariaDB 10.1

**PHP version:** PHP 5.6

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** Updated from 8.2.3 recently

**Where did you install ownCloud from:** Install from source from https://owncloud.org/install/

**Signing status (ownCloud 9.0 and above):**
```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.1.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - music: true
  - news: 7.1.2
  - notes: 2.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - updatenotification: 0.1.0
Disabled:
  - external
  - federation
  - files_external
  - firstrunwizard
  - notifications
  - templateeditor
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocb072aa2d38",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.jruehlig.com"
        ],
        "datadirectory": "\/mnt\/files",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost:\/mnt\/mysql\/mysql.sock",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "syslog",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/tmp\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "mail_smtpmode": "smtp",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_domain": "jruehlig.com",
        "mail_from_address": "owncloud",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": true,
        "theme": "",
        "overwrite.cli.url": "https:\/\/www.jruehlig.com\/owncloud",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "asset-pipeline.enabled": false,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Markdown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ],
        "maintenance": false
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox / Chrome

**Operating system:** Linux / Android

#### Web server error log
```
Class 'OC' not found in /usr/local/www/owncloud/settings/ajax/setlanguage.php on line 27
```

#### ownCloud log (data/owncloud.log)
```
nothing relevant
```

#### Browser log
```
500 Internal Server Error - /owncloud/settings/ajax/setlanguage.php
```

#### Notes
* I have recently enabled "Pretty URLs" enabled
* I use a web_root of "/owncloud"

**Comment by DeepDiver1975** [comment]
Smells like an issue with pretty URLs

**Comment by josh4trunks** [comment]
good catch. I added an index. php to my URL and changing my language worked.

**Comment by Xenopathic** [comment]
I noticed you are using nginx - looks like you have an issue with the pretty URL handling in your configuration. Make sure that *any* access to PHP files goes through index.php, this means that a simple `try_files $uri ...` won't work.

**Comment by josh4trunks** [comment]
@Xenopathic I'm using the configuration that I'm helping develop for the docs here.
https://github.com/owncloud/documentation/issues/2014#issuecomment-199369134

So with pretty URLs enabled PHP should be passed /index.php PATH_INFO=/settings/ajax/setlanguage.php?
So basically if it's not specifically called out here then route it to /index.php?
https://github.com/owncloud/core/blob/master/.htaccess#L69-L77

Thanks

**Comment by Xenopathic** [comment]
@josh4trunks Yes, that's how it needs to be passed

**Comment by josh4trunks** [comment]
Ok, makes sense.

I'll need to adjust the documented nginx config more. 
https://github.com/owncloud/documentation/issues/2014#issuecomment-201949929
