### ISSUE TITLE
Feature request: Send daily reminders/list on calendar entries

### ISSUE THREAD

**Issue by marneu** [owncloud/core#23592]
### Wishlist
1. add a daily cron task for a daily email reminder on all events (own+shared)
3. make reminders/notifications based on a per user setting

### Expected behaviour
A german example for the daily reminder on 8.x installations can be found here https://www.std-soft.com/hm-service/code/23-kalender-notifikation-fuer-owncloud (This example won't work on 9 installations any more).

**Comment by Xenopathic** [comment]
You can already achieve this? You can set reminders in the calendar and will be notified by one of your devices at that time.

**Comment by marneu** [comment]
This is not the same, it not about a reminder on ONE event at an events's time or before. It's about a daily list in the morning with all events that occur on one day. This is an extended addition to a reminder. I was used to this for years when using google's cal. Anyway sorry to loose this functionality again.

**Comment by Xenopathic** [comment]
If you think the current calendar is lacking functionality, please open a feature request over at https://github.com/owncloud/calendar

**Comment by marneu** [comment]
Are you confident? Ping-pong is really frustrating ...
see: https://github.com/owncloud/calendar/issues/307#issuecomment-201907372
Eitherway, I will do the cron function by myself if I upgrade, just forget about it.

**Comment by georgehrke** [comment]
> That sounds like a feature that should be implemented by an app,

@Xenopathic: That's not possible, because there is no PHP API for the calendar. The only way for apps to access it is thru CalDAV via JS. Thus outsourcing it to an app is not possible (using the standard APIs).
Although I think only very few users would use this functionality. Given that this is possible via plain CalDAV, users who need this can just write a script.
