### ISSUE TITLE
Help Translate link in personal settings is wrong

### ISSUE THREAD

**Issue by thorsten19** [owncloud/core#23594]
**Steps to reproduce**
1. Login to Owncloud web interface
2. Select dropdown for login name and select Personal
3. Click on Help Translate 

**Expected behaviour**
Link should lead to the translation project on transifex.
https://www.transifex.com/projects/p/owncloud/

**Actual behaviour**
Link leads to a 403 forbidden access
https://www.transifex.com/projects/p/owncloud/team/en/

**Server configuration**
Operating system: Raspbian GNU/Linux 8 (jessie)
Web server: Apache
Database: MySql
PHP version: 5.5.44
ownCloud version: (see ownCloud admin page) 9.0.0

**Updated from an older ownCloud or fresh install:** Fresh install
**Client configuration**
Browser: Firefox 45.0.1
Operating system: Windows 7

**Comment by paurisa** [comment]
This issue can be closed as a fix has already been implemented.
See: https://github.com/owncloud/core/pull/23705
