### ISSUE TITLE
occ integrity:sign-app silently fails when it can't save the signature

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#23591]
### Steps to reproduce
1. `sudo -uwww-data ./occ integrity:sign-app --privateKey=../contacts.key --certificate=../contacts.crt --path=customapps/contacts/build/contacts`
### Expected behaviour
- I should get a message telling me signing was successful
- I should find a `signature.json` file within the appinfo folder of your application
### Actual behaviour
- `Successfully signed "customapps/contacts/build/contacts"`
- No trace of a `signature.json` file
### ownCloud log

```
"message":"file_put_contents(customapps\/contacts\/build\/contacts\/appinfo\/signature.json): failed to open stream: Permission denied at \/var\/www\/owncloud\/lib\/private\/integritycheck\/helpers\/fileaccesshelper.php#59

```

@LukasReschke

**Comment by PVince81** [comment]
@DeepDiver1975 I assume that the market will still give a better rating to signed apps ?

If yes we should improve the UX of such commands.

**Comment by VicDeo** [comment]
@PVince81 I guess no backports are needed. Closing as fixed.
