### ISSUE TITLE
Rename folder with lots of files seems to need to touch every file's db entry

### ISSUE THREAD

**Issue by Hengjie** [owncloud/core#23608]
### Steps to reproduce
1. Take a folder with 10K files
2. Go to owncloud web interface and change folder name
3. Wait

### Expected behaviour
Changing directory name should be instant.

### Actual behaviour
It takes ~120 seconds before the spinner on the folder stops spinning. Running `top` shows that MySQL and Apache are busy working on something. My best guess is that because it's a folder with over 10K files, it needs to touch every file's DB row for the update to happen.

### Server configuration
**Operating system**: Raspbian GNU/Linux 8 (jessie)

**Web server:** Apache/2.4.10 (Raspbian)

**Database:** MySQL Ver 14.14 Distrib 5.5.44

**PHP version:** 5.6.17-0+deb8u1

**ownCloud version:** 9.0

**Comment by DeepDiver1975** [comment]
Yes. All entries need to be touched given the current DB design of OC_filecache

**Comment by Hengjie** [comment]
Is there a particular reason why? It's good to see data being cached but I can't see how a join to a "folders" table via some "folder_id" being particularly slow.
