### ISSUE TITLE
Problem with encoding for certain french accent

### ISSUE THREAD

**Issue by guidtz** [owncloud/core#23607]
Hello,

I have problem to read certains files with french accent. For example a file is a pdf whih name "Présentation.pdf". When I try to open it in owncloud I have error : **Message: Unexpected server response (503) while retrieving PDF "https://myowncloud.com/remote.php/webdav/Pr%C3%A9sentation.pdf"
**
And when I try to sync it I have error on sync client :

`"app":"PHP","message":"fopen(\/var\/www\/myowncloud.com\/www\/data\/hisyl\/files\/Pr\u00e9sentation.pdf): failed to open stream: No such file or directory at \/var\/www\/myowncloud.com\/www\/lib\/private\/files\/storage\/local.php#247","level":3,"time":"March 28, 2016 07:29:30"}`

On Linux system I can do a ls on the file.

Owncloud version 9.0.0 (same problem in owncloud 8.2)
Linux distribution : Debian 8
Client version : 2.1.1 (Linux and Windows same problems).

Thanks for you're help

**Comment by PVince81** [comment]
This is likely a setup problem. Please double check that your server's locale/lang is en_US.UTF8.

How did you upload this file ?

**Comment by guidtz** [comment]
Hello,

  locale is in fr_FR.UTF-8.
File is hosted in a windows 2008 R2 server and share is mounted in the linux file system in directory of the user.
I test also with the external share / cifs and I have the same trouble.

Thanks

**Comment by PVince81** [comment]
Okay, next question: was the file uploaded to the Windows Server directly using a Mac (outside of ownCloud) ? Could be #21365

**Comment by guidtz** [comment]
I don't know. Perhaps is a big data server and there are users with Windows Clients and Mac Client. What can I do for testing and report informations ?

**Comment by PVince81** [comment]
> share is mounted in the linux file system in directory of the user.

So is it mounted by the user as an external storage ? (Using the "external storage secetion").
Or is it mounted as a Linux CIFS mount directly on the Linux filesystem ?

**Comment by PVince81** [comment]
Closing due to lack of feedback
