### ISSUE TITLE
[Feature Request] [OCC] user:add should be able to set a quota

### ISSUE THREAD

**Issue by ccoenen** [owncloud/core#23603]
Right now, `occ user:add` has options for setting groups and display names. I would like to suggest adding `--quota` to the options.

**My Motivation**
I have to provision an OC Install with ~200 users, and being able to set quotas from the commandline would help speed things up. Some of the users will not receive the default quota, and right now, i have to create them and afterwards manually search the "special" users from the admin panel.

**Comment by PVince81** [comment]
One alternative is to use the provisioning API: https://doc.owncloud.org/server/9.0/admin_manual/configuration_user/user_provisioning_api.html

I agree that it would be nice to have it on the OCC CLI too.

**Comment by ccoenen** [comment]
Thank you for the hint regarding the provisioning API. I have to admit that I didn't know about it, yet! This solves my immediate need.

**Comment by phil-davis** [comment]
Also needs quota modify with ``user:modify``

**Comment by phil-davis** [comment]
Seems a reasonable thing to me.

**Comment by TripleEmcoder** [comment]
+1 against letting this issue die

**Comment by phil-davis** [comment]
It seems reasonable to me that quota (and any other user attribute) should be able to be set from the command line.

**Comment by ccoenen** [comment]
\*starts staring contest with github-actions bot\*

**Comment by Keram-Yasin** [comment]
I found this command that works for NextCloud:
`user:setting layla files quota 1GB`

But It doesn't work on ownCloud. Is it too difficult to add this option to ownCloud?

**Comment by phil-davis** [comment]
> But It doesn't work on ownCloud. Is it too difficult to add this option to ownCloud?

PR welcome.

**Comment by Keram-Yasin** [comment]
> PR welcome.

I don't understand exactly what PR means. But I will try to dig out the codes to add this option.
