### ISSUE TITLE
Owncloud 9 dav not working

### ISSUE THREAD

**Issue by ltsavar** [owncloud/core#23601]
After Updating to OC9 I can't use the Calendar via Thunderbird anymore.
I get "401 No 'Authorization: Basic' header found" Messages and therefore I can't read or edit any calendar items anymore.
The only thing i found was https://forum.owncloud.org/viewtopic.php?t=30646 but I'm not using fcgi and noting on my settings changed between the update.

### Steps to reproduce
1. Update to owncloud 9

### Expected behaviour
Dav should work.

### Actual behaviour
Dav is not working.

### Server configuration
**Operating system**:
Debian 8.3

**Web server:**
Apache 2.4

**Database:**
MariaDB 5.5.47

**PHP version:**
 5.6.17

**ownCloud version:** (see ownCloud admin page)
9.0.0

**Updated from an older ownCloud or fresh install:**
Update von 8.2

**Where did you install ownCloud from:**
Debian Packages

**Signing status (ownCloud 9.0 and above):**
failed cause of .htaccess

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - announcementcenter: 1.1.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.0.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - imprint: 0.2.5
  - news: 5.2.8
  - notifications: 0.2.3
  - polls: 0.6.2
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - user_external: 0.4
Disabled:
  - bookmarks
  - encryption
  - html5_videoplayer
  - mail
  - mozilla_sync
  - ojsxc
  - ownnote
  - roundcube
  - tasks
  - updatenotification
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oca2453ae3ef",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "cloud.jit.cool",
            "jit.cool"
        ],
        "forcessl": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{mail04.jit-creatives.de:143\/imap\/readonly}"
                ]
            }
        ],
        "loglevel": 0,
        "dbname": "owncloud",
        "dbhost": "db01.jit-creatives.de",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
Thunderbird 38.7

#### Web server error log

141.62.31.244 - ingo [27/Mar/2016:16:25:10 +0200] "PROPFIND /remote.php/dav/ HTTP/1.1" 207 9045 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:38.0) Gecko/20100101 Thunderbird/38.7.0 Lightning/4.0.5.2"

#### ownCloud log (data/owncloud.log)
{"reqId":"KTcdqDCd\/pD3sX1F0y3a","remoteAddr":"109.42.1.236","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/caldav.php(75): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":false}","level":0,"time":"2016-03-27T13:11:07+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/caldav\/"}

**Comment by Xenopathic** [comment]
That is not an error, that's a debug log message. Please turn down your log level. In actual fact, the log message in your web server access log shows that Thunderbird seems to be connecting just fine.

**Comment by ltsavar** [comment]
So i turned it down to 2: WARN

Now i don't get any information (no error, nothing) in my owncloud log
But Dav is not working.

Before with debug on i get the information mention above and if i try to save a calendar entry "403 Permission denied to create file". But now nothing in owncloud log at all....

**Comment by ltsavar** [comment]
If i try curl -v https://jit.cool/remote.php/caldav -u ingo -X PROPFIND 
i get an 200 OK with the principals url
so yes thunderbird should connect correctly. i don't get it why no caldav client is working.

**Comment by Xenopathic** [comment]
@ltsavar Try using cadaver to browse the CalDAV endpoint, it's a DAV client on the command line. It should highlight any issues

**Comment by DeepDiver1975** [comment]
Which URL are you entering in Thunderbird?
Afaik you have to enter the full URL to the calendar

**Comment by drfuture** [comment]
Hi, does your "File" App work? i have the same error-message on my owncloud9 installation (all webdav funtions doesn not work and the authentification basic message is on the debug-log.
[https://github.com/owncloud/core/issues/23560](url)

**Comment by ltsavar** [comment]
No configured calendar is working. They where in 8.2
and i was told old URLs stil should work. 
So no i used the sort url for testing but all old url should work and they dont.
I tried updating to 9.0.1 Beta but still the Same Problem

**Comment by ltsavar** [comment]
@drfuture i tried the owncloud client now and yes it is not working either. so its the same bug.

**Comment by ltsavar** [comment]
@drfuture at least with 9.0.1 beta files are working. connection via webdav is working. strange. before it was a missconfiguration on my side.

**Comment by drfuture** [comment]
witch missconfig? maybe i have the same :dancer: i try the 9.0.1 later this day.

**Comment by ltsavar** [comment]
an apache missconfiguration. nothing to do with owncloud.
after trying so many things I decided to switch back to 8.2

**Comment by tallship** [comment]
@drfuture, @ltsavar, I was wondering, are you using the SoGo connector for CalDAV and/or CalDAV syncs. (You're using Thunderbird/38.7.0 and Lightning/4.0.5.2)? Right?

On the most current Thunderbird versions (i.e., 45x) are completely integrated with Lightning, which includes new native support for CalDAV and CardDav.

And next part may be a little OT, but what about your Androids and iPhones? Were they experiencing any sync issues after your upgrades to ownCloud 9.0? 

Are you running DAVdroid, or the other two ( CalDAV-sync and CardDav- Sync)? And are you using CAdroid for self-signed certs on your httpd srver's ownCloud installation?

**Comment by ltsavar** [comment]
@tallship We had 5 working Thunderbird Clients with 8.2. After Upgrading to 9.0 none worked. I know that the url changed but the old one should work as well. We are not using SoGo. Just plain Thunderbird with Lightning (updates automacigly so always the newest version).  Jolla/SailfishOS also could not connect to the owncloud. We are also using Android with Davdroid. I think it was also not working but im not sure. 
We are using a (paid) startssl certificate with multiple SANs. 

Other People may have the same problem: https://forum.owncloud.org/viewtopic.php?f=38&t=34865&hilit=thunderbird&sid=0dd30ded7167a860456b284a3ee5bea9

As mention before the RC of 9.0.1 did not fix the problem so I downgraded to 8.2 again. Everthing is working again with 8.2.

**Comment by Huster-at-github** [comment]
https://github.com/owncloud/core/issues/23601#issuecomment-203488844

@ltsavar 
What was wrong at your apache config? Maybe I have the same misconfiguration ....

**Comment by kdslkdsaldsal** [comment]
@Huster-at-github See https://central.owncloud.org/t/no-basic-authentication-headers-were-found-message/819 If you need further support please create a new thread at central and make sure that you're filling out the template shown when creating a new thread.

**Comment by ltsavar** [comment]
@Huster-at-github sorry i don't remember. But the Problem at that time was a Owncloud Problem. Thats why i was going back to 8.2. Some month later i updated again to owncloud 9 and the problem was gone.
