### ISSUE TITLE
[Feature Request] [OCC] adding shares from occ

### ISSUE THREAD

**Issue by ccoenen** [owncloud/core#23604]
I would like to suggest a new command - or subcommand - that facilitates automatically sharing files or directories.

This could look somewhat like this:

```sh
$ occ share:add --user="alice" --directory="accounting/2016" --shared-with="bob"
# alice now shares accounting/2016 with bob
```

Eventually, it would be amazing to set all the relevant things of a share

```sh
$ occ share:add --user="alice" --directory="accounting/2016" --shared-with="bob" --can-create --can-update --can-delete
```

Or even userless sharable urls, returned to STDOUT for further processing:

```sh
$ occ share:add --user="alice" --directory="accounting/2016" --url --expiration-date="2016-05-01" --password-from-env
# https://oc.example.com/index.php/s/B8ErvPywcGS0cq2
```

**Comment by PVince81** [comment]
One alternative is to use the Share API: https://doc.owncloud.org/server/9.0/developer_manual/core/ocs-share-api.html or use a tool like https://github.com/owncloud/pyocclient which provides functions to create shares.

The trouble with a CLI command is that you'd also need to give the user's password, else some cases like encryption won't work. Sharing with encryption requires the sharer's password to be able to use their encryption keys.

**Comment by PVince81** [comment]
CC @rullzer @DeepDiver1975

**Comment by ccoenen** [comment]
Thanks for the explanation regarding encryption, I didn't know this could interfere! In an "initial provisioning" scenario I'd probably be able to do this while still "knowing" the password, but it's probably a bad idea to have a command that's only useful within narrow constraints.

If it seems too large a task, please feel free to close this issue. I will not be offended, this is just a suggestion.

**Comment by PVince81** [comment]
I'm going to close this then. :smile:
