### ISSUE TITLE
OS X Contacts only shows Company name 

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#23609]
### Steps to reproduce
1. Create a Contact with ownCloud Contacts - Frontend
2. Give the Contact a Name **and** a company name 
3. Sync with OS X El Capitan Contacts App via CardDAV

### Expected behavior
Should sync the Name of the Person with the Organization he is associated with.

### Actual behavior
OS X El Capitan's Contacts app is only showing the company name as contacts name.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS
**Web server:**
Apache 2.4
**Database:**
SQLite
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
9.0

### Client configuration
**Browser:**
Safari 
**Operating system:**
OS X El Capitan

**Comment by DeepDiver1975** [comment]
Screenshots please and the vcard for testing -THX

**Comment by aspdye** [comment]
The vCard i would provide you is a "normal" one. *Max Mustermann* and *Musterfirma GmbH*.
Nothing special :wink:

Problem is, that OS X Contacts sees "Musterfirma GmbH" as name, and not as company. I hope we will resolve this by, https://github.com/owncloud/contacts/issues/335 or https://github.com/owncloud/contacts/issues/186 :grin:

**Comment by DeepDiver1975** [comment]
> Problem is, that OS X Contacts shows "Musterfirma GmbH" as name, and not as company. I hope we will resolve this by, owncloud/contacts#335 or owncloud/contacts#186 :grin:

this is no issue within the contacts app from my pov.

Still I find it interesting to see vcard and screenshots to get an understanding - THX

**Comment by DeepDiver1975** [comment]
> Still I find it interesting to see vcard and screenshots to get an understanding - THX

@aspdye can you provide this information please - otherwise I have to close this issue

**Comment by DeepDiver1975** [comment]
please reopen is still valid or requested data is available - THX
