### ISSUE TITLE
Update JSqueeze

### ISSUE THREAD

**Issue by georgehrke** [owncloud/core#23605]
The jsqueeze release we currently use has a bug the keeps the calendar away from supporting asset pipeline.

They just released a fix https://github.com/tchwork/jsqueeze/releases/tag/v2.0.4
yay \o/

Any chance we can backport this fix to ownCloud 9.0?

@DeepDiver1975 @PVince81

**Comment by mmattel** [comment]
:+1:

**Comment by DeepDiver1975** [comment]
PR welcome :wink:

**Comment by georgehrke** [comment]
sure :)

**Comment by mmattel** [comment]
https://github.com/owncloud/3rdparty/pull/266 update JSqueeze to version 2.0.4

**Comment by PVince81** [comment]
Looks like master is already pointing at the correct submodule. Closing.
