### ISSUE TITLE
remote.php errors after upgrade

### ISSUE THREAD

**Issue by TheOtterslider** [owncloud/core#23610]
**Steps to reproduce**
1. working 8.2.3 server
2. download and unzip 9.0.0 tar
3. copy config/config.php
4. upgrade (running occ upgrade manually from the command. it finished with no errors)

**Expected behaviour**
It should work

**Actual behaviour**
When I login, I get a "this directory is unavailable, please check the logs or contact the administrator error message displayed (for all users)
When I check the logs, they are full of this:

```
Error   PHP   require_once(): Failed opening required '/var/www/html/owncloud/apps/files/appinfo/remote.php' (include_path='/var/www/html/owncloud/3rdparty/pear/console_getopt:/var/www/html/owncloud/3rdparty/pear/pear_exception:/var/www/html/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/html/owncloud/3rdparty/pear/archive_tar:/var/www/html/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/owncloud/lib/private:/var/www/html/owncloud/config:/var/www/html/owncloud/3rdparty:/var/www/html/owncloud/apps:.:/usr/share/pear:/usr/share/php:/var/www/html/owncloud') at /var/www/html/owncloud/remote.php#138   2016-03-27T13:03:01+00:00

Error   PHP   require_once(/var/www/html/owncloud/apps/files/appinfo/remote.php): failed to open stream: No such file or directory at /var/www/html/owncloud/remote.php#138   2016-03-27T13:03:01+00:00

Error   PHP   require_once(): Failed opening required '/var/www/html/owncloud/apps/files/appinfo/remote.php' (include_path='/var/www/html/owncloud/3rdparty/pear/console_getopt:/var/www/html/owncloud/3rdparty/pear/pear_exception:/var/www/html/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/html/owncloud/3rdparty/pear/archive_tar:/var/www/html/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/owncloud/lib/private:/var/www/html/owncloud/config:/var/www/html/owncloud/3rdparty:/var/www/html/owncloud/apps:.:/usr/share/pear:/usr/share/php:/var/www/html/owncloud') at /var/www/html/owncloud/remote.php#138
```

I check...that file doesn't exist (/var/www/html/owncloud/apps/files/appinfo/remote.php). This is weird because I just unzipped the owncloud directory directly from the tar. But, I try to copy it and I get other errors (so I deleted it from files/appinfo and leave it in the root). I decide I'll just get it from github....hmm, it doesn't exist there.

If I go to https://MyHost/owncloud/remote.php/webdav I get a 500 error thrown
If I go to https://MyHost/owncloud/remote.php/dav I get prompted to login and then see the standard "this is the webdav interface" message

I **think** the root problem is something messed up with webdav. When I upgraded to 8.2.3, I had to run the upgrade twice because I had some similar problems. When I reenabled the contacts and calendar apps, then did the upgrade again everything started working (in 8.2.3). I can go in and enable apps,once I got to that point, I decided to upgrade to 9.

Just to clarify, what happened in the 8.2.3 upgrade was I upgraded, logged in just fine, enabled the contacts app, then got kicked out to the "you need to upgrade" web screen.  I reran the upgrade from the command line.  Same with calendar...enabled it, got kicked out to the "you need to upgrade" screen, so I rerean it from the command line.  By the time I was all finished, everything worked

Some more information, calendar and contacts work great...it is only files that is messed up.

RealRancor on the forums thought it was related to .htaccess issues.  I went and manually got the htaccess from the 9.0.1 beta branch.  it didn't appear to be different than the file I had, but I put it in anyway.  No change.

**Server configuration**
```Operating system: centos 6.7 (final)
Web server: apache 2.2.15
Database: mysql 5.1.73
PHP version: 5.6.18
ownCloud version (see ownCloud admin page): 9.0.0
Updated from an older ownCloud or fresh install: upgrade from 8.2.3```

**ownCloud log (data/owncloud.log):**

```
{"reqId":"FDSfwgNB9ZBx4Wwm5KGf","remoteAddr":"xxxxxxxxxxxx","app":"PHP","message":"require_once(): Failed opening required '\/var\/www\/html\/owncloud\/apps\/files\/appinfo\/remote.php' (include_path='\/var\/www\/html\/owncloud\/3rdparty\/pear\/console_getopt:\/var\/www\/html\/owncloud\/3rdparty\/pear\/pear_exception:\/var\/www\/html\/owncloud\/3rdparty\/pear\/pear-core-minimal\/src:\/var\/www\/html\/owncloud\/3rdparty\/pear\/archive_tar:\/var\/www\/html\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/var\/www\/html\/owncloud\/lib\/private:\/var\/www\/html\/owncloud\/config:\/var\/www\/html\/owncloud\/3rdparty:\/var\/www\/html\/owncloud\/apps:.:\/usr\/share\/pear:\/usr\/share\/php:\/var\/www\/html\/owncloud') at \/var\/www\/html\/owncloud\/remote.php#138","level":3,"time":"2016-03-27T13:09:25+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}

{"reqId":"MLsH7dvlieo3PEL\/pfuo","remoteAddr":"xxxxxxxxxxxx","app":"PHP","message":"require_once(\/var\/www\/html\/owncloud\/apps\/files\/appinfo\/remote.php): failed to open stream: No such file or directory at \/var\/www\/html\/owncloud\/remote.php#138","level":3,"time":"2016-03-27T13:09:57+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}

{"reqId":"MLsH7dvlieo3PEL\/pfuo","remoteAddr":"xxxxxxxxxxxx","app":"PHP","message":"require_once(): Failed opening required '\/var\/www\/html\/owncloud\/apps\/files\/appinfo\/remote.php' (include_path='\/var\/www\/html\/owncloud\/3rdparty\/pear\/console_getopt:\/var\/www\/html\/owncloud\/3rdparty\/pear\/pear_exception:\/var\/www\/html\/owncloud\/3rdparty\/pear\/pear-core-minimal\/src:\/var\/www\/html\/owncloud\/3rdparty\/pear\/archive_tar:\/var\/www\/html\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/var\/www\/html\/owncloud\/lib\/private:\/var\/www\/html\/owncloud\/config:\/var\/www\/html\/owncloud\/3rdparty:\/var\/www\/html\/owncloud\/apps:.:\/usr\/share\/pear:\/usr\/share\/php:\/var\/www\/html\/owncloud') at \/var\/www\/html\/owncloud\/remote.php#138","level":3,"time":"2016-03-27T13:09:57+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}

{"reqId":"HRlhElEdaXXobvB+vxaD","remoteAddr":"xxxxxxxxxxxx","app":"PHP","message":"require_once(\/var\/www\/html\/owncloud\/apps\/files\/appinfo\/remote.php): failed to open stream: No such file or directory at \/var\/www\/html\/owncloud\/remote.php#138","level":3,"time":"2016-03-27T13:10:29+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}

{"reqId":"HRlhElEdaXXobvB+vxaD","remoteAddr":"xxxxxxxxxxxx","app":"PHP","message":"require_once(): Failed opening required '\/var\/www\/html\/owncloud\/apps\/files\/appinfo\/remote.php' (include_path='\/var\/www\/html\/owncloud\/3rdparty\/pear\/console_getopt:\/var\/www\/html\/owncloud\/3rdparty\/pear\/pear_exception:\/var\/www\/html\/owncloud\/3rdparty\/pear\/pear-core-minimal\/src:\/var\/www\/html\/owncloud\/3rdparty\/pear\/archive_tar:\/var\/www\/html\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/var\/www\/html\/owncloud\/lib\/private:\/var\/www\/html\/owncloud\/config:\/var\/www\/html\/owncloud\/3rdparty:\/var\/www\/html\/owncloud\/apps:.:\/usr\/share\/pear:\/usr\/share\/php:\/var\/www\/html\/owncloud') at \/var\/www\/html\/owncloud\/remote.php#138","level":3,"time":"2016-03-27T13:10:29+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}

{"reqId":"iH+ZeaqCte8TFqg9CljO","remoteAddr":"xxxxxxxxxxxx","app":"PHP","message":"require_once(\/var\/www\/html\/owncloud\/apps\/files\/appinfo\/remote.php): failed to open stream: No such file or directory at \/var\/www\/html\/owncloud\/remote.php#138","level":3,"time":"2016-03-27T13:11:01+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}

{"reqId":"iH+ZeaqCte8TFqg9CljO","remoteAddr":"xxxxxxxxxxxx","app":"PHP","message":"require_once(): Failed opening required '\/var\/www\/html\/owncloud\/apps\/files\/appinfo\/remote.php' (include_path='\/var\/www\/html\/owncloud\/3rdparty\/pear\/console_getopt:\/var\/www\/html\/owncloud\/3rdparty\/pear\/pear_exception:\/var\/www\/html\/owncloud\/3rdparty\/pear\/pear-core-minimal\/src:\/var\/www\/html\/owncloud\/3rdparty\/pear\/archive_tar:\/var\/www\/html\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/var\/www\/html\/owncloud\/lib\/private:\/var\/www\/html\/owncloud\/config:\/var\/www\/html\/owncloud\/3rdparty:\/var\/www\/html\/owncloud\/apps:.:\/usr\/share\/pear:\/usr\/share\/php:\/var\/www\/html\/owncloud') at \/var\/www\/html\/owncloud\/remote.php#138","level":3,"time":"2016-03-27T13:11:01+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}

{"reqId":"VTOqfcIKmtFOWuxXahps","remoteAddr":"xxxxxxxxxxxx","app":"PHP","message":"require_once(\/var\/www\/html\/owncloud\/apps\/files\/appinfo\/remote.php): failed to open stream: No such file or directory at \/var\/www\/html\/owncloud\/remote.php#138","level":3,"time":"2016-03-27T13:11:36+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}

{"reqId":"VTOqfcIKmtFOWuxXahps","remoteAddr":xxxxxxxxxxxx","app":"PHP","message":"require_once(): Failed opening required '\/var\/www\/html\/owncloud\/apps\/files\/appinfo\/remote.php' (include_path='\/var\/www\/html\/owncloud\/3rdparty\/pear\/console_getopt:\/var\/www\/html\/owncloud\/3rdparty\/pear\/pear_exception:\/var\/www\/html\/owncloud\/3rdparty\/pear\/pear-core-minimal\/src:\/var\/www\/html\/owncloud\/3rdparty\/pear\/archive_tar:\/var\/www\/html\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/var\/www\/html\/owncloud\/lib\/private:\/var\/www\/html\/owncloud\/config:\/var\/www\/html\/owncloud\/3rdparty:\/var\/www\/html\/owncloud\/apps:.:\/usr\/share\/pear:\/usr\/share\/php:\/var\/www\/html\/owncloud') at \/var\/www\/html\/owncloud\/remote.php#138","level":3,"time":"2016-03-27T13:11:36+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
```

**Special configuration (external storage, external authentication, reverse proxy, server-side-encryption):** nothing special


**Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.**
```
No errors have been found.
```

List of activated apps:


If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.2.1
  - calendar: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - templateeditor: 0.1
Disabled:
  - encryption
  - external
  - files_videoplayer
  - systemtags
  - updatenotification
  - user_external
  - user_ldap
```

**The content of config/config.php:**


If you have access to your command line run e.g.:
sudo -u www-data php occ c
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
{
    "system": {
        "instanceid": "oc8e61b24903",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "MYDOMAIN"
        ],
        "datadirectory": "\/Path\/To\/DataDir\/",
        "overwrite.cli.url": "https:\/\/MYDOMAIN\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "admin",
        "mail_smtpmode": "php",
        "mail_domain": "MYDOMAIN",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "singleuser": false,
        "loglevel": 0
    }
}
```


**Are you using external storage, if yes which one:** local/smb/sftp/... - no

**Are you using encryption:** yes/no - no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... - no


**Browser:** - Chrome

**Operating system:** Mac OSx 10.11.3

### Logs
#### Web server error log
```
[Mon Mar 28 11:52:17 2016] [error] [client 74.195.15.177] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/owncloud/apps/files/appinfo/remote.php' (include_path='/var/www/html/owncloud/3rdparty/pear/console_getopt:/var/www/html/owncloud/3rdparty/pear/pear_exception:/var/www/html/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/html/owncloud/3rdparty/pear/archive_tar:/var/www/html/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/owncloud/lib/private:/var/www/html/owncloud/config:/var/www/html/owncloud/3rdparty:/var/www/html/owncloud/apps:.:/usr/share/pear:/usr/share/php:/var/www/html/owncloud') in /var/www/html/owncloud/remote.php on line 138
[Mon Mar 28 11:52:49 2016] [error] [client 74.195.15.177] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/owncloud/apps/files/appinfo/remote.php' (include_path='/var/www/html/owncloud/3rdparty/pear/console_getopt:/var/www/html/owncloud/3rdparty/pear/pear_exception:/var/www/html/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/html/owncloud/3rdparty/pear/archive_tar:/var/www/html/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/owncloud/lib/private:/var/www/html/owncloud/config:/var/www/html/owncloud/3rdparty:/var/www/html/owncloud/apps:.:/usr/share/pear:/usr/share/php:/var/www/html/owncloud') in /var/www/html/owncloud/remote.php on line 138
[Mon Mar 28 11:53:21 2016] [error] [client 74.195.15.177] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/owncloud/apps/files/appinfo/remote.php' (include_path='/var/www/html/owncloud/3rdparty/pear/console_getopt:/var/www/html/owncloud/3rdparty/pear/pear_exception:/var/www/html/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/html/owncloud/3rdparty/pear/archive_tar:/var/www/html/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/owncloud/lib/private:/var/www/html/owncloud/config:/var/www/html/owncloud/3rdparty:/var/www/html/owncloud/apps:.:/usr/share/pear:/usr/share/php:/var/www/html/owncloud') in /var/www/html/owncloud/remote.php on line 138
[Mon Mar 28 11:53:53 2016] [error] [client 74.195.15.177] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/owncloud/apps/files/appinfo/remote.php' (include_path='/var/www/html/owncloud/3rdparty/pear/console_getopt:/var/www/html/owncloud/3rdparty/pear/pear_exception:/var/www/html/owncloud/3rdparty/pear/pear-core-minimal/src:/var/www/html/owncloud/3rdparty/pear/archive_tar:/var/www/html/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/var/www/html/owncloud/lib/private:/var/www/html/owncloud/config:/var/www/html/owncloud/3rdparty:/var/www/html/owncloud/apps:.:/usr/share/pear:/usr/share/php:/var/www/html/owncloud') in /var/www/html/owncloud/remote.php on line 138
```

Edit - formatting

**Comment by TheOtterslider** [comment]
Sorry for the formatting issues.  I tried to tweak it, but ended up making it worse and less readable

**Comment by DeepDiver1975** [comment]
Looks like the upgrade didn't properly setup remote.PHP.

Please have a look in the DB - table OC_appconfig for entries which hold the value app/files/appinfo/remote.PHP

That value has to be changed to
apps/dav/appinfo/v1/webdav.php

**Comment by TheOtterslider** [comment]
DeepDiver1975, thanks for the info.  Most of this is put here so someone else can see what I did...but I also put it here on the hopes that I'll get some confirmation

Query:
```
select * from oc_appconfig where configvalue like '%appinfo%';
```
gives me
```
+-------+-----------------+-----------------------------+
| appid | configkey       | configvalue                 |
+-------+-----------------+-----------------------------+
| core  | remote_caldav   | calendar/appinfo/remote.php |
| core  | remote_calendar | calendar/appinfo/remote.php |
| core  | remote_carddav  | contacts/appinfo/remote.php |
| core  | remote_contacts | contacts/appinfo/remote.php |
| core  | remote_dav      | dav/appinfo/v2/remote.php   |
| core  | remote_files    | files/appinfo/remote.php    |
| core  | remote_filesync | files/appinfo/filesync.php  |
| core  | remote_webdav   | files/appinfo/remote.php    |
+-------+-----------------+-----------------------------+
8 rows in set (0.00 sec)

```

running query 
```
select * from oc_appconfig where appid = 'core' and configkey = 'remote_files';
```
gives me the one row I'm going to update
```
+-------+--------------+--------------------------+
| appid | configkey    | configvalue              |
+-------+--------------+--------------------------+
| core  | remote_files | files/appinfo/remote.php |
+-------+--------------+--------------------------+
1 row in set (0.00 sec)
```

now I'll update it
```
update oc_appconfig set configvalue = 'dav/appinfo/v1/webdav.php' where appid = 'core' and configkey = 'remote_files';
Query OK, 1 row affected (0.04 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```
confirm the change with
```
 select * from oc_appconfig where appid = 'core' and configkey = 'remote_files';
```
I can see the change
```
+-------+--------------+---------------------------+
| appid | configkey    | configvalue               |
+-------+--------------+---------------------------+
| core  | remote_files | dav/appinfo/v1/webdav.php |
+-------+--------------+---------------------------+
1 row in set (0.00 sec)
```

Do I need to update anything else in that table?

Results after testing = I still get the same error when I login.  I also get the same errors in the owncloud log.

**Comment by TheOtterslider** [comment]
@DeepDiver1975  -- can you confirm what the values should be in the table?

After testing the one entry above and it didn't work, I ran the following queries:

query 1
```
select * from oc_appconfig where configvalue like '%appinfo%';
```
that gave me
```
+-------+-----------------+-----------------------------+
| appid | configkey       | configvalue                 |
+-------+-----------------+-----------------------------+
| core  | remote_caldav   | calendar/appinfo/remote.php |
| core  | remote_calendar | calendar/appinfo/remote.php |
| core  | remote_carddav  | contacts/appinfo/remote.php |
| core  | remote_contacts | contacts/appinfo/remote.php |
| core  | remote_dav      | dav/appinfo/v2/remote.php   |
| core  | remote_files    | dav/appinfo/v1/webdav.php   |
| core  | remote_filesync | files/appinfo/filesync.php  |
| core  | remote_webdav   | files/appinfo/remote.php    |
+-------+-----------------+-----------------------------+
8 rows in set (0.00 sec)
```
I then ran these two update queries (I know you didn't explicitly say, but they made the two rows agree).  I was just testing a theory here

```
update oc_appconfig set configvalue = 'dav/appinfo/v1/remote.php' where appid = 'core' and configkey = 'remote_files';
Query OK, 1 row affected (0.06 sec)
Rows matched: 1  Changed: 1  Warnings: 0

update oc_appconfig set configvalue = 'dav/appinfo/v1/remote.php' where appid = 'core' and configkey = 'remote_dav';
Query OK, 1 row affected (0.03 sec)
Rows matched: 1  Changed: 1  Warnings: 0
```
That gave me
```
 select * from oc_appconfig where configvalue like '%appinfo%';
+-------+-----------------+-----------------------------+
| appid | configkey       | configvalue                 |
+-------+-----------------+-----------------------------+
| core  | remote_caldav   | calendar/appinfo/remote.php |
| core  | remote_calendar | calendar/appinfo/remote.php |
| core  | remote_carddav  | contacts/appinfo/remote.php |
| core  | remote_contacts | contacts/appinfo/remote.php |
| core  | remote_dav      | dav/appinfo/v1/remote.php   |
| core  | remote_files    | dav/appinfo/v1/remote.php   |
| core  | remote_filesync | files/appinfo/filesync.php  |
| core  | remote_webdav   | files/appinfo/remote.php    |
+-------+-----------------+-----------------------------+
8 rows in set (0.00 sec)
```
It didn't work so I set the two rows back to what they were before I started:
```
select * from oc_appconfig where configvalue like '%appinfo%';
+-------+-----------------+-----------------------------+
| appid | configkey       | configvalue                 |
+-------+-----------------+-----------------------------+
| core  | remote_caldav   | calendar/appinfo/remote.php |
| core  | remote_calendar | calendar/appinfo/remote.php |
| core  | remote_carddav  | contacts/appinfo/remote.php |
| core  | remote_contacts | contacts/appinfo/remote.php |
| core  | remote_dav      | dav/appinfo/v2/remote.php   |
| core  | remote_files    | dav/appinfo/v1/webdav.php   |
| core  | remote_filesync | files/appinfo/filesync.php  |
| core  | remote_webdav   | files/appinfo/remote.php    |
+-------+-----------------+-----------------------------+
8 rows in set (0.00 sec)
```

**Comment by DeepDiver1975** [comment]
You have to update the remote_webdav entry as well.
An also all other entries for calendar and contacts.

Really strange they did not get updated properly.

**Comment by PVince81** [comment]
Do you have log entries from the time where you ran the upgrade, in case there were errors ?

**Comment by TheOtterslider** [comment]
@DeepDiver1975 just to confirm ... all 8 rows shown above should have their configvalue set to dav/appinfo/v1/webdav.php  (I hate to have to undo something because I missed something simple)

**Comment by TheOtterslider** [comment]
@PVince81 let me check.  I know I ran occ with the --verbose flag and didn't get any errors reported to the console.

**Comment by TheOtterslider** [comment]
@PVince81 

Here's all I find in my owncloud.log file around the upgrade time:

```
{"reqId":"homvDxzPuUXtpq0pOnY7","remoteAddr":"","app":"core","message":"starting upgrade from 8.2.3.2 to 9.0.0.19","level":0,"time":"2016-03-27T01:09:20+00:00","method":"--","url":"--"}
{"reqId":"LuCxm0nMcqgxSquUwRvM","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"2016-03-27T01:15:10+00:00","method":"--","url":"--"}
{"reqId":"FubWzW3twI7CjomtwA3h","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"2016-03-27T01:30:07+00:00","method":"--","url":"--"}
{"reqId":"vq10R+inmnyoTMToctyn","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"2016-03-27T01:45:08+00:00","method":"--","url":"--"}
{"reqId":"zrnxbuqNX+f1HLBZVM6w","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"2016-03-27T02:00:13+00:00","method":"--","url":"--"}
{"reqId":"lwRLfGf\/vdtsUcYrB9TG","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"2016-03-27T02:15:05+00:00","method":"--","url":"--"}
{"reqId":"Zhf5A4YILjPvyBpbcw+3","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"2016-03-27T02:30:06+00:00","method":"--","url":"--"}
{"reqId":"2ePp0+\/\/7sXUngbOzklP","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"2016-03-27T02:45:07+00:00","method":"--","url":"--"}
{"reqId":"7sP7akOC\/+80D6m6S7us","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"2016-03-27T03:00:11+00:00","method":"--","url":"--"}
{"reqId":"7Nnk85K9H0otNnanU\/5Y","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"2016-03-27T03:15:04+00:00","method":"--","url":"--"}
{"reqId":"E85K+Fb4psKfVoaFTiox","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"2016-03-27T03:30:04+00:00","method":"--","url":"--"}
{"reqId":"DqwAf7f8QUlFhCvu8k10","remoteAddr":"","app":"cron","message":"Update required, skipping cron","level":0,"time":"2016-03-27T03:45:07+00:00","method":"--","url":"--"}
{"reqId":"Jbb3L0oB43Z2CGAfHejy","remoteAddr":"xxx.xxx.xxx.xxx","app":"PHP","message":"require_once(\/var\/www\/html\/owncloud\/apps\/files\/appinfo\/remote.php): failed to open stream: No such file or directory at \/var\/www\/html\/owncloud\/remote.php#138","level":3,"time":"2016-03-27T03:55:38+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
```

From looking at my other upgrades in the log, that looks normal.   I do see some errors from a previous upgrade so I know errors had been written (I had a mysql problem relating to my lock table size)

Perhaps there could be an enhancement request made:  when occ is run with --verbose, major steps done are written to the owncloud.log file  (just like what gets printed to the console...starting/finished type messages)

**Comment by TheOtterslider** [comment]
after looking through the code, I found what I thought were the correct values here in core/apps/dav/appinfo/info.xml.  I updated my table to:

```
select * from oc_appconfig where configvalue like '%appinfo%';
+-------+-----------------+----------------------------+
| appid | configkey       | configvalue                |
+-------+-----------------+----------------------------+
| core  | remote_caldav   | appinfo/v1/caldav.php      |
| core  | remote_calendar | appinfo/v1/caldav.php      |
| core  | remote_carddav  | appinfo/v1/carddav.php     |
| core  | remote_contacts | appinfo/v1/carddav.php     |
| core  | remote_dav      | dav/appinfo/v2/remote.php  |
| core  | remote_files    | dav/appinfo/v1/webdav.php  |
| core  | remote_filesync | files/appinfo/filesync.php |
| core  | remote_webdav   | dav/appinfo/v1/webdav.php  |
+-------+-----------------+----------------------------+
8 rows in set (0.00 sec)
```

I can login via the web interface now and see files.  I also still have my calendar and contacts.  My sync client appears to work too.  I just checked my android app and all appears ok there.  Looks like that resolved it

**Comment by DeepDiver1975** [comment]
@TheOtterslider the table is supposed to look like

![bildschirmfoto von 2016-04-05 09-43-51](https://cloud.githubusercontent.com/assets/1005065/14274665/f5dd871e-fb12-11e5-8fac-827dcc9c3e9a.png)

**Comment by TheOtterslider** [comment]
Thanks for the info @DeepDiver1975 .

I have an entry you don't have:  remote_filesync  Should it be updated to something?

**Comment by DeepDiver1975** [comment]
> I have an entry you don't have: remote_filesync Should it be updated to something?

no - this was never used

**Comment by TheOtterslider** [comment]
Super.  Thanks for all the help.

**Comment by TheOtterslider** [comment]
By the way, from where I sit the issue is resolved.  Should I close it now or wait for someone else to do it after a certain milestone?

**Comment by DeepDiver1975** [comment]
> Super. Thanks for all the help.

Happy to help out! Take care

**Comment by 88fingerslukee** [comment]
Please help me, I'm getting these same errors but I have no clue how there were solved for TheOtterslider.  What commands do I need to issue to alter my DB table?

**Comment by TheOtterslider** [comment]
@88fingerslukee -- What I did to resolve the problem was update some values in the database.  The upgrade should have done it, but it didn't ... for some reason.

>What commands do I need to issue to alter my DB table?
There is way too much that could go wrong here if done wrong and way too much dependent upon your exact configurations.  Here's an outline of what needs done:

0 - back up your database.  Now do it again.  Check it.  If you hose this, you'll have to restore it.  I cheat and cron the mysqldump command for all my active databases every night.  Before I do an upgrade, I'll run it manually.  You can do this by:
```
mysqldump --add-drop-table -u USERNAME -pPASSWORD_NO_SPACE DBNAME | gzip > /PATH/TO/BACKUP/FILE
```

1 - login to your database.  I used the mysql command line version to login as the root user:  
```
mysql -u root -p
```
then enter the password when prompted.

2 - you need to switch to the correct database:
```
use DBNameHere
```

3 - run a select to check the values.  This depends on the table prefix you used when you installed ownCloud the first time.
```
select * from PREFIX_appconfig where configvalue like '%appinfo%';
```

4 - this will spit out something like this:
```
+-------+-----------------+-----------------------------+
| appid | configkey       | configvalue                 |
+-------+-----------------+-----------------------------+
| core  | remote_caldav   | calendar/appinfo/remote.php |
| core  | remote_calendar | calendar/appinfo/remote.php |
| core  | remote_carddav  | contacts/appinfo/remote.php |
| core  | remote_contacts | contacts/appinfo/remote.php |
| core  | remote_dav      | dav/appinfo/v2/remote.php   |
| core  | remote_files    | files/appinfo/remote.php    |
| core  | remote_filesync | files/appinfo/filesync.php  |
| core  | remote_webdav   | files/appinfo/remote.php    |
+-------+-----------------+-----------------------------+
```

5 - compare your values to what the table is supposed to look like (https://github.com/owncloud/core/issues/23610#issuecomment-205704566)

6 - update anything that needs updated.  I did it one at a time by running this query.  The generic format for this in SQL is update TABLE set COLUMN = VALUE [WHERE]:
```
update PREFIX_appconfig set configvalue = CORRECT_VALUE where appid = 'core' and configkey = CONFIG_KEY_TO_UPDATE;
```

If done correctly, you should see something that says one row was updated.  Once everything is done, you should be good to go.

If you have mysql, the commands above will give you a good idea where to start.  There are easier ways (especially if you are running owncloud on a hosted server that has phpmyadmin), but that's how I did it.  They are also the most common denominator provided you have command line access to the server.  I personally don't have phpmyadmin installed on my box so I can't help you out there too much.

**Comment by 88fingerslukee** [comment]
@TheOtterslider 
Brilliant!! Thanks so much!

**Comment by sxdxfan** [comment]
Had the same issue, updated MySQL tables, this fixed everything except for the external links

Example link:
https://cloud.iidf.ru/index.php/s/K4U5hCfzpXVtVxS

'Download' button seems to work, but no files can be seen on the web

Any ideas?

**Comment by Jas2Ma** [comment]
Hi guys, solved the very same issue for me, too.
One question: I don't have the **remote_dav** entry. Anything bad about this?

**Comment by Finkregh** [comment]
I hit this issue today, upgrading from 8.1.something to 9.1.0, has this not been patched?

**Comment by Aikhjarto** [comment]
Just hit this bug when upgrading from 8.2.10 to 9.0.8.
Upgraded the database manually with:
```
update oc_appconfig set configvalue = 'dav/appinfo/v1/caldav.php' where appid = 'core' and configkey = 'remote_caldav';
update oc_appconfig set configvalue = 'dav/appinfo/v1/caldav.php' where appid = 'core' and configkey = 'remote_calendar';
update oc_appconfig set configvalue = 'dav/appinfo/v1/carddav.php' where appid = 'core' and configkey = 'remote_carddav';
update oc_appconfig set configvalue = 'dav/appinfo/v1/carddav.php' where appid = 'core' and configkey = 'remote_contacts';
update oc_appconfig set configvalue = 'dav/appinfo/v2/remote.php' where appid = 'core' and configkey = 'remote_dav';
update oc_appconfig set configvalue = 'dav/appinfo/v1/webdav.php' where appid = 'core' and configkey = 'remote_files';
update oc_appconfig set configvalue = 'dav/appinfo/v1/webdav.php' where appid = 'core' and configkey = 'remote_webdav';
```
However I had two issues that made me revert to 8.2.4:
* my calendars were gone afterwards for all users
* file access was not possible in singleuser mode as admin (but at least possible for other user when singleuser mode was disabled)

**Comment by TheOtterslider** [comment]
@Aikhjarto -- wasn't the upgrade to 9 when ownCloud made the change that

1. you had to reactivate non-core apps after the upgrade and
2. calendar, etc.. were no longer considered part of the core?

If I'm right, redo the upgrade (all the steps), login as your ownCloud admin user and reactivate the calendar app
