### ISSUE TITLE
"File not found" error when attempting to download single file or folder in the directory

### ISSUE THREAD

**Issue by xyrofreeze** [owncloud/core#23613]
### Steps to reproduce
1. Create Folder "Test1"
2. Navigate into "Test1", **EITHER** Create Folder "TestSub1" **OR** Create Text file "TestText1.txt"
3. Ensure /Test1/ folder only has 1 item in it
4. Attempt to download by **Ticking Checkbox** for Folder "TestSub1" and clicking **Download** on the table header

### Expected behaviour
Prompt for download

### Actual behaviour
"File not found" error page

### Server configuration
**Operating system**: Ubuntu Server 14.04.4 LTS

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page) 9.0.0

**Updated from an older ownCloud or fresh install:** Fresh Install

**Where did you install ownCloud from:** ownCloud Official

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
"system": {
	"instanceid": "ocm13mqs5bu2",
	"passwordsalt": "***REMOVED SENSITIVE VALUE***",
	"secret": "***REMOVED SENSITIVE VALUE***",
	"trusted_domains": [
		"xxx.xxx.x.xxx",
		"example.com"
	],
	"datadirectory": "\/media\/homenas",
	"overwrite.cli.url": "https:\/\/example.com\/owncloud",
	"dbtype": "mysql",
	"version": "9.0.0.19",
	"dbname": "ocdb",
	"dbhost": "localhost",
	"dbtableprefix": "oc_",
	"dbuser": "***REMOVED SENSITIVE VALUE***",
	"dbpassword": "***REMOVED SENSITIVE VALUE***",
	"logtimezone": "Asia\/Singapore",
	"installed": true,
	"mail_smtpmode": "smtp",
	"mail_smtpdebug": true,
	"memcache.local": "\\OC\\Memcache\\APCu",
	"mail_from_address": "ownCloud",
	"mail_domain": "example.com",
	"loglevel": 0,
	"mail_smtphost": "smtp.gmail.com",
	"mail_smtpport": "587",
	"mail_smtpsecure": "tls",
	"mail_smtpauth": 1,
	"mail_smtpauthtype": "LOGIN",
	"mail_smtpname": "***REMOVED SENSITIVE VALUE***",
	"mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 7 Ultimate 64-bit

#### Web server error log
```
No errors logged
```

#### ownCloud log (data/owncloud.log)
```
No errors logged
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

#### My Own Findings
```
**"File not found" error page URL:**
https://example.com/owncloud/index.php/apps/files/ajax/download.php?dir=%2F&files=TestSub1&downloadStartSecret=7y0xp2ehks7h5w6vproyfogvi

My understanding of the issue is this javascript function located in /owncloud/apps/files/js/filelist.js.
**Javascript Function:** _onClickDownloadSelected: function(event)

When only 1 folder or file exists in that directory, and by ticking the checkbox and clicking download.

Checks for **this.isAllSelected()** is true, so it updates the **dir** variable to 1 level up.
Checks for **this.getSelectedFiles().length > 1** is false, so it tries to generate URL for the 1 chosen filename.
Assuming my Test1 Folder is in root "/". These results in:
dir = /
filename = TestSub1

Ending up with "File not found" (URL above), because file (or folder) exists in /Test1/TestSub1
```

**Comment by PVince81** [comment]
Important addition: the checkbox to tick is the one for "TestSub1" and click "Download" on the table header.

I can reproduce this on v9.0.0.

**Comment by PVince81** [comment]
Direct download of the folder gives the URL: http://localhost/owncloud/index.php/apps/files/ajax/download.php?dir=%2FTest1&files=TestSub1&downloadStartSecret=311q6qmaxzaaif6r
But the broken URL gives http://localhost/owncloud/index.php/apps/files/ajax/download.php?dir=%2F&files=TestSub1&downloadStartSecret=7p03si27bmcjif6r

The "dir" value is missing for some reason. I think there is special logic in case "select all" is used but only a single folder is selected.

Also broken on stable9.

**Comment by xyrofreeze** [comment]
Thanks!
Updated the Steps to include Ticking Checkbox for "TestSub1"

**Comment by magicvodi** [comment]
Still reproducable on 2 different 9.0.2 instances.

**Comment by PVince81** [comment]
Setting to junior job, anyone with some JS skills might be able to fix it. (happy to assist if needed)

If no one steps up I'll take a look at this myself later for 9.0.3.

**Comment by RealRancor** [comment]
Possible fix in https://github.com/owncloud/core/issues/24800

**Comment by PVince81** [comment]
https://github.com/owncloud/core/issues/24800
