### ISSUE TITLE
[security enhancement] Get a security audit.

### ISSUE THREAD

**Issue by cluelessperson** [owncloud/core#23612]
Considering the size of ownclou, and usage within professional and enterprise environments, I suggest owncloud hire a 3rd party to properly analyze owncloud for potential security vulnerabilities.

"Being opensource" is not enough, and does not even remotely compare to security experts mapping entry points and vulnerable points of entry.

**Comment by DeepDiver1975** [comment]
We do that already. Thx

**Comment by LukasReschke** [comment]
For more information see also:

- https://hackerone.com/resources / https://hackerone.box.com/shared/static/4bswx4g1nx8f2kbrltx1orp0zhy6ij39.pdf?referrer=resources
- https://hackerone.com/owncloud
- https://statuscode.ch/2015/09/ownCloud-security-development-over-the-years
