### ISSUE TITLE
some files have not passed the integrity check - .htaccess

### ISSUE THREAD

**Issue by ghormoon** [owncloud/core#23615]
Hi, after upgrading from 8.2.2 to 9.0.0 (tar archive), I'm getting error that .htaccess did not pass integrity check. originally reported by someone else into gallery: https://github.com/owncloud/gallery/issues/580 with exact same wrong checksum.
Maybe OC shouldn't write the change or at least trust this variant of .htaccess.

.htaccess diff:
```
82,105d81
< #### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
< 
< ErrorDocument 403 /core/templates/403.php
< ErrorDocument 404 /core/templates/404.php
< <IfModule mod_rewrite.c>
<   RewriteBase /
<   <IfModule mod_env.c>
<     SetEnv front_controller_active true
<     <IfModule mod_dir.c>
<       DirectorySlash off
<     </IfModule>
<   </IfModule>
< </IfModule>
< #### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
< 
< <IfModule mod_rewrite.c>
<   RewriteBase /
<   <IfModule mod_env.c>
<     SetEnv front_controller_active true
<     <IfModule mod_dir.c>
<       DirectorySlash off
<     </IfModule>
<   </IfModule>
< </IfModule>
```

### Steps to reproduce
Not sure, something writes into .htacces after upgrade sometimes. I may try to play with this more if necessary.

### Expected behaviour
No error shown.

### Actual behaviour
Getting error:
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f40e7ca19cd76ff922ccd164e38f4d73806f66170cafa202fb470be225c813b4b242f4321da8a01bef1329e300acf3d137dbcbff058c501f166a2619031fc651
                            [current] => 7bae810b6f5ca98d062ac9985cac7fb2dc8e22d981ec41e8327e53a5ee7f33017b128bbb4ceefbe665dbd35f7a1ee3a0926c4278aeeeb6d7b4325197be1ed9a9
                        )

                )

        )

)
```

### Server configuration
**Operating system**: debian jessie

**Web server:** apache

**Database:** mysql

**PHP version:** 5.6.17+dfsg-0+deb8u1

**ownCloud version:** (see ownCloud admin page) 9.0.0

**Updated from an older ownCloud or fresh install:** updated from 8.2.2

**Where did you install ownCloud from:** 9.0.0 tar archive

**Signing status (ownCloud 9.0 and above):** enabled, error on .htaccess

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.1.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc3a91951a6b",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.ghorland.net",
            "owncloud-dav.ghorland.net",
            "oc-dav.ghorland.net",
            "oc.ghorland.net"
        ],
        "datadirectory": "\/home\/owncloud\/owncloud_data",
        "overwrite.cli.url": "https:\/\/owncloud.ghorland.net",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud_main",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "ghorland.net",
        "theme": "",
        "maintenance": false,
        "loglevel": 1,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true
    }
}
```

**Are you using external storage, if yes which one:** none

**Are you using encryption:** yes (default_encryption_module)

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Seamonkey 2.39

**Operating system:** Debian jessie

### Logs
if you need some, let me know.

**Comment by RealRancor** [comment]
The upcoming oC 9.0.1 has already fixes included for this topic: https://github.com/owncloud/core/pull/23250

**Comment by ghormoon** [comment]
should I test it with 9.0.1-beta or just wait? it's not an issue for me right now, I can test it when 9.0.1 comes out
if you want, I may test it with beta so it can be closed sooner

**Comment by tflidd** [comment]
@ghormoon If you can test the 9.0.1 beta, that's great.

**Comment by ghormoon** [comment]
upgrade 9.0.0 -> 9.0.1 beta fixed it in my case
I won't mess with users by downgrading and doing the upgrade directly, but if you want, I'm able to create testing environment from the 8.2.2 backup (and then upgrade directly to 9.0.1 beta). is it worth the time?

**Comment by PVince81** [comment]
No need to test 8.2.2 to 9.0.1 beta upgrade if the 9.0.0->9.0.1 beta already worked for you.
