### ISSUE TITLE
limit size download drectory

### ISSUE THREAD

**Issue by simpleuser99** [owncloud/core#23622]
Hello.
Please, give me advice, how can I limit download  size on server side when user download whole directory from web interface?
For example, user have dir about 100Gb, when he click download, became start to download archive of dir. I want that user can't download archive own directore more than 5Gb.

**Comment by LukasReschke** [comment]
This is a bug tracker, ask questions at other pages. See owncloud.org/support

**Comment by RealRancor** [comment]
Might be also a partly duplicate of https://github.com/owncloud/core/issues/16370
