### ISSUE TITLE
Experimental apps shown even though the setting is disabled

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#23623]
I’m seeing this:
![capture du 2016-03-28 23-31-23](https://cloud.githubusercontent.com/assets/925062/14107162/b5b606ea-f5b6-11e5-9119-f258cee907e0.png)

Any idea @LukasReschke @schiesbn?

**Comment by LukasReschke** [comment]
@jancborchardt Any chance you have the app locally already in the apps folder? In this case they are shown anyways.

**Comment by oparoz** [comment]
Duplicate of https://github.com/owncloud/core/issues/17122, closed by @jancborchardt :P 

![](https://cloud.githubusercontent.com/assets/323220/8355698/03d00114-1b51-11e5-9c88-29574dedae94.png)

**Comment by jancborchardt** [comment]
;D @oparoz damn, you are right.

@LukasReschke ok, so I guess since this is just a thing which happens for developers we leave it? Or what’s a proposal for a solution?

**Comment by oparoz** [comment]
@jancborchardt - This was my proposal: #17123

**Comment by jancborchardt** [comment]
Ok, closing in favor of https://github.com/owncloud/core/issues/17123 then.
