### ISSUE TITLE
2/3 of the hooks of OC\Files\Storage\Shared can point to unexisting files

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#23620]
### Steps to reproduce

1. Look at the hook for `file_put_contents`
2. Now look at the hooks for  `fopen`  and `file_get_contents`

### Expected behaviour

All targets should look like this:

`'target' => $this->getMountPoint() . '/' . $path`

### Actual behaviour

2/3 of targets looks like this:

`'target' => $this->getMountPoint() . $path`

@rullzer @PVince81

**Comment by PVince81** [comment]
@nickvergessen any insights ? Does it affect the activity app in some way ?

**Comment by nickvergessen** [comment]
Activity doesn't listen to them.

**Comment by PVince81** [comment]
See comments in the PR https://github.com/owncloud/core/pull/23648#issuecomment-222940959.

The issue with the missing path slash only exists in stable9, stable8.2. Please send PRs for these branches, thanks !

This qualifies as a backport @cmonteroluque @DeepDiver1975

**Comment by PVince81** [comment]
@oparoz Please send PRs for these branches, thanks !

(forgot to mention you :smile:)

**Comment by oparoz** [comment]
@PVince81 - I'll try :) I hope it's just a matter of cherry-picking what I did.

**Comment by rullzer** [comment]
I think this is fixed now...

**Comment by oparoz** [comment]
@rullzer Did you patch stable9?

**Comment by oparoz** [comment]
I would only argue that on 9.1 there is a consistency issue. It doesn't make sense to build some paths with a slash while others don't have it. I'm assuming that because it's now working, the extra slash can be removed.

**Comment by rullzer** [comment]
No I did not patch stable9... are we just missing a `/` somewhere there?

**Comment by oparoz** [comment]
>are we just missing a / somewhere there?

Yes, on 9, https://github.com/owncloud/core/pull/23648 is needed because things break without it

But I would still fix the inconsistency on master and remove all slashes.

I'm happy to make the changes

**Comment by rullzer** [comment]
@oparoz please do

**Comment by PVince81** [comment]
stable9: https://github.com/owncloud/core/pull/25519
stable8.2: https://github.com/owncloud/core/pull/25520

Please review

**Comment by oparoz** [comment]
Thanks very much for that, it totally skipped my mind :S

**Comment by PVince81** [comment]
All merged, closing
