### ISSUE TITLE
[Accesibility] System tags and comments textboxes in the sidebar have no label

### ISSUE THREAD

**Issue by davitol** [owncloud/core#23627]
### Steps to reproduce
1. In files view, open the sidebar of any file
2. Go to the comments menu
### Expected behaviour

System tags and comments textboxes should have the corresponding label
### Actual behaviour

System tags and comments textboxes labels are missed
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** "9.1.0 pre alpha","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
```
### Client configuration

**browser**
 Firefox.

![screen shot 2016-03-29 at 12 55 02](https://cloud.githubusercontent.com/assets/10596560/14110851/99167ab2-f5c8-11e5-9678-42de6932df86.png)

@owncloud/designers

**Comment by PVince81** [comment]
moved to more general UX group ticket: https://github.com/owncloud/core/issues/27578
