### ISSUE TITLE
Tooltips related to tags deletion do not disappear

### ISSUE THREAD

**Issue by davitol** [owncloud/core#23639]
### Steps to reproduce
1. In files view, open the sidebar of any file
2. Add some collaborative tags
3.  Click on the tags textbox in rder to show the tags list
4. Mouse over trashbin icon and delete one tag
### Expected behaviour

Delete tooltip related to tags should disappear
### Actual behaviour

Delete tooltip related to tags does not disappear
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** "9.0.1.1","versionstring":"9.0.1 RC1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
```
### Client configuration

**browser**

 Firefox.

![screen shot 2016-03-30 at 09 11 39](https://cloud.githubusercontent.com/assets/10596560/14134461/bdbbb136-f657-11e5-86d1-430efcbbf549.png)

Safari

![screen shot 2016-03-30 at 09 10 33](https://cloud.githubusercontent.com/assets/10596560/14134474/cb81d9e4-f657-11e5-8b01-f79f3838e498.png)

@owncloud/designers

**Comment by PVince81** [comment]
moved to more general UX group ticket: https://github.com/owncloud/core/issues/27578
