### ISSUE TITLE
[Sharing] In files view, the user that made the shares is not shown

### ISSUE THREAD

**Issue by davitol** [owncloud/core#23645]
### Steps to reproduce

1. With admin user, create two users (user1, user2)
2. user1: create a file and a folder and share with user2
3. Log in with user2 and accept the shares

### Expected behaviour

In files view, it should be shown who was the user that made the shares

### Actual behaviour

In files view, the user that made the shares is not shown

Note: It worked OK in oc 9.0.0. (regression)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** "9.0.1.1","versionstring":"9.0.1 RC1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Firefox, Safari

oC 9.0.0
![screen shot 2016-03-30 at 10 34 09](https://cloud.githubusercontent.com/assets/10596560/14136751/b557f808-f664-11e5-8446-dea5e5190572.png)

oC 9.0.1

![whomadewho](https://cloud.githubusercontent.com/assets/10596560/14136883/7b321806-f665-11e5-9a45-56b509595647.gif)

**Comment by rullzer** [comment]
@davitol are you doing ferderated shares?

**Comment by PVince81** [comment]
The screenshot "before" shows regular user shares but the "after" seems to show federated shares.

Here is my try with both fed shares and local shares.
8.2.3:
![share-status-8 2 3](https://cloud.githubusercontent.com/assets/277525/14148111/85c7ca16-f69e-11e5-9023-cb724046663f.png)

stable9:
![share-status-stable9](https://cloud.githubusercontent.com/assets/277525/14148196/dcff2c52-f69e-11e5-9f28-3ec857a03e9d.png)

Indeed, something seems wrong.

**Comment by PVince81** [comment]
`data-share-owner` is set, so something broke the code that displays the owner in the status.

**Comment by PVince81** [comment]
Debugging into `OC.Share.markFileAsShared`. The status is set correctly, but some mechanism is re-rendering the file row which discards it.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/23663
