### ISSUE TITLE
Missing dependency (php7.0-mbstring) in owncloud-deps-php7.0 Debian package

### ISSUE THREAD

**Issue by cippaciong** [owncloud/core#23644]
Hello, there is a problem with the current php7 dependencies of ownCloud 9.0 on Debian. While the php5 package is compiled with mbstring support, it isn't the same for php7 which comes with a separate `php7.0-mbstring` package. This is true both in the external [sury](https://packages.sury.org/php/) repository, which I'm using on Debian Stable, as well as in php7 packages from Debian Testing and Unstable.
Anyway that package is not installed by owncloud-deps-php7.0 and this leads to the error described below.

**Note 1**: I didn't installed  `owncloud-deps-php7.0` but only its php dependencies since I'm using nginx and not Apache
**Note 2**: The error came up once I installed the 3rd party app "Contacts" but I think is a *core* error and maybe other use cases can lead to it.

### Steps to reproduce
1. Install owncloud and php7 (I took the owncloud-deps-php7.0 dependencies as a reference)
2. Install the 3rd party app "Contacts" (I don't know if there are other ways to trigger this error)
3. Open the contact page

### Expected behaviour
The contact list should load and show up

### Actual behaviour
Contacts won't load (unless thee isn't any contact saved) and this error will show up in owncloud log:
```Error: Call to undefined function Sabre\VObject\mb_strcut() at /var/www/owncloud/3rdparty/sabre/vobject/lib/Property.php#247```

### Solution
Install the `php7.0-mbstring` package

### Server configuration
**Operating system**: Debian 8 (Stable)

**Web server:** nginx 1.9.10

**Database:** postgresql 9.4

**PHP version:** php7.0-fpm

**ownCloud version:** 9.0

**Updated from an older ownCloud or fresh install:** Updated from an older install

**Where did you install ownCloud from:** ownCloud repository for Debian

**Comment by LukasReschke** [comment]
cc @jnweiger

**Comment by jnweiger** [comment]
finxed in the template. 9.0.1 packages will have the fix.

**Comment by mitar** [comment]
Hm, this package does not seem to be available for Ubuntu 14.04 LTS?

**Comment by mitar** [comment]
Solved by installing `php5.6-mbstring` from https://launchpad.net/~ondrej/+archive/ubuntu/php
