### ISSUE TITLE
XCache isAvailable check fails in OC9

### ISSUE THREAD

**Issue by getriebesand** [owncloud/core#23653]
in my xcache.ini I have
xcache.var_size = 64M

core/lib/private/memcache/xcache.php XCache::isAvailable()
in OC8
$var_size = (int) ini_get('xcache.var_size');
$var_size is now 64

in OC9
$var_size = \OC::$server->getIniWrapper()->getNumeric('xcache.var_size')
$var_size is now false;

The Method  \OC::$server->getIniWrapper()->getNumeric() uses is_numeric() which fails on the string "64M"

**Comment by nickvergessen** [comment]
should use `getBytes` I guess?

**Comment by nickvergessen** [comment]
Can you test that @getriebesand

**Comment by getriebesand** [comment]
yes...getBytes('xcache.var_size') returns 67108864
