### ISSUE TITLE
Test all external storages with encryption enabled

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#23657]
Due to the problems with some external storages in 9.0 with regard to the stream wrapper (which returned less than 8192 bytes) I'm going to manually retest all external storages with encryption enabled as well.

- [x] Amazon S3
- [x] Dropbox
- [x] FTP (works with https://github.com/owncloud/core/pull/23442)
- [x] Google Drive (works with https://github.com/owncloud/core/pull/23660)
- [x] Local
- [x] OpenStack Object Storage
- [x] SMB
- [ ] Sharepoint
- [x] ownCloud (storage not encrypted as expected)
- [x] SFTP (works with https://github.com/owncloud/core/pull/23672)
- [x] WebDAV

cc @owncloud/qa @rperezb Is there any way that we can come up with some automated way to test them with encryption enabled as well? That would be rocking :rocket:

**Comment by LukasReschke** [comment]
Also cc @Xenopathic @icewind1991 @DeepDiver1975 might be worth to have https://github.com/owncloud/core/tree/0e687993c8afb36876e7d90c229b97b4aaf43b70/apps/files_external/tests adjusted to also run once with encryption enabled.

**Comment by LukasReschke** [comment]
cc @schiesbn As discussed

**Comment by LukasReschke** [comment]
Google works but seems broken in 9.0 due to another issue… Debugging…

**Comment by Xenopathic** [comment]
It would be better to isolate the behaviour that encryption sometimes breaks on, and create a unit test for that behaviour to apply for all storages. That way we keep true to individual unit tests which will make testing quicker and less prone to cross-component failures.

**Comment by rperezb** [comment]
@jvillafanez can you please help here

**Comment by LukasReschke** [comment]
@rperezb @jvillafanez @owncloud/qa I tested all storages except "OpenStack Object Storage", "SMB" and "Sharepoint". Could you give this a test as well? :rocket:

**Comment by jvillafanez** [comment]
Sure, I'm building a docker image to test OpenStack (in fact devstack), but it will require a bit of time. I hope the image is mostly ready today and we can test it tomorrow

**Comment by Xenopathic** [comment]
@jvillafanez We already have a Docker container - see xenopathic/ceph-keystone

**Comment by jvillafanez** [comment]
Unfortunately I can't make it work using docker. In my case, it complains about network issues trying to work with iptables, specially it doesn't have permissions to add new entries in iptables (I'm not willing to force heavy requirements)

The ceph-keystone didn't work for neither @Xenopathic nag me about this next week :wink: 
```
mounting via loopback
mount: Could not find any loop device. Maybe this kernel does not know
       about the loop device? (If so, recompile or `modprobe loop'.)
```

I'll use a VM as a fallback.

**Comment by jvillafanez** [comment]
:exclamation: 
Sharepoint downloads fail with a "Bad signature" error. Uploads looks good

**Comment by jvillafanez** [comment]
SMB works fine :+1:

**Comment by LukasReschke** [comment]
@jvillafanez Thanks. Let me see what I can do about Sharepoint fail. I have an idea :thought_balloon:

**Comment by LukasReschke** [comment]
@jvillafanez Can you test https://github.com/owncloud/sharepoint/pull/250?

**Comment by jvillafanez** [comment]
For sharepoint with encryptiont, file deletion isn't working, but renaming the file is (with and without the "Use RetryWrapper" patch)

**Comment by jvillafanez** [comment]
OpenStack works fine :+1:

**Comment by PVince81** [comment]
Can we close this and continue in the sharepoint ticket if that's the only one remaining ?
