### ISSUE TITLE
Preview thumbnail is not available for a file that has been transferred its ownership

### ISSUE THREAD

**Issue by davitol** [owncloud/core#23650]
### Steps to reproduce
1. With admin user via CLI transfer ownership from user1 to user2
2. Log in with user2 and browse into the new folder created with the files of user1
3. Edit a file (a new version is shown)
### Expected behaviour

The preview of the version should be visible
### Actual behaviour

A broken icon is shown

Note: It only happens with the files that has been  transferred their ownership
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** "9.0.1.1","versionstring":"9.0.1 RC1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
```
### Client configuration

**browser**
Firefox

![screen shot 2016-03-30 at 13 03 19](https://cloud.githubusercontent.com/assets/10596560/14140526/b8f2b6c8-f679-11e5-962c-ac265e56522d.png)

**Comment by PVince81** [comment]
Weird... the thumbnails should be regenerated.

CC @DeepDiver1975 @georgehrke @oparoz

**Comment by oparoz** [comment]
It's an activity problem -> @nickvergessen

**Comment by PVince81** [comment]
please try again with recent OC versions. I seem to remember that there was an older bug about versions previews that is already fixed.
