### ISSUE TITLE
Cron.php stops running after upgrade to 9.0.1 RC1

### ISSUE THREAD

**Issue by bboule** [owncloud/core#23658]
### Steps to reproduce
1.  Upgrade from OC 9.0.1 Beta to OC 9.0.1 RC1
2. Cron stops running 
3.

### Expected behaviour
Cron should continue to run
### Actual behaviour
When Cron.php attempts to run we see this:
PHP Fatal error:  Cannot make non static method OC\BackgroundJob\Job::run() static in class OCA\Files_Antivirus\Cron\Task in /var/www/html/owncloud/apps/files_antivirus/lib/cron/task.php on line 15

### Server configuration
**Operating system**:  CentOS7

**Web server:**Apache

**Database:**MySQL

**PHP version:** 5.6

**ownCloud version:** 9.0.1 RC1
**Updated from an older ownCloud or fresh install:  Update from 9.0.1 Beta

**Where did you install ownCloud from: TAR

**Comment by RealRancor** [comment]
Something for https://github.com/owncloud/files_antivirus/issues ?

**Comment by bboule** [comment]
OK... re-opened there...
