### ISSUE TITLE
Apps management doesn’t show author names correctly

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#23665]
Instead of reading the display names from info.xml it seems to show the very technical usernames:
![capture du 2016-03-30 18-32-26](https://cloud.githubusercontent.com/assets/925062/14149724/d77e9d06-f6a5-11e5-996e-85fc058269df.png)

cc @LukasReschke @karlitschek

**Comment by DeepDiver1975** [comment]
app store issue -> close
