### ISSUE TITLE
files:transfer-ownership misses some shares

### ISSUE THREAD

**Issue by jerrac** [owncloud/core#23669]
### Steps to reproduce
Run the command? I think this is likely rather specific to my instance...

### Expected behaviour
Files and shares should transfer.

### Actual behaviour
Only some files and shares transfer

### Notes
So, this issue arose after I figured out that our share links were throwing 500 errors due to invalid ldap users. A few users had left the active employees ldap ou. The first try failed because the user I was trying to transfer from was invalid. After forcing that user back into the active ou, it sort of worked. Except that some shares did not transfer. And it took 2 tries for the files to all transfer.

See: http://pastebin.com/udxjSM2g for what my shell looks like.

### Server configuration
**Operating system**:
 Ubuntu 14.04

**Web server:**
Apache 2.4

**Database:**
Mysql 5.6

**PHP version:**
5.5

**ownCloud version:** (see ownCloud admin page)
9.0.0
**Updated from an older ownCloud or fresh install:**
Updated from 8.1.3 to 8.2.3 to 9.0.0.
**Where did you install ownCloud from:**
tarball
**Signing status (ownCloud 9.0 and above):**

```
Results
=======
- core
	- INVALID_HASH
		- .htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f40e7ca19cd76ff922ccd164e38f4d73806f66170cafa202fb470be225c813b4b242f4321da8a01bef1329e300acf3d137dbcbff058c501f166a2619031fc651
                            [current] => 87af4d0158a16dfb0e9f2214c6325ece768c9c057ffc463c458a6bdd59d994768af6380cdbe6a984ebed27774ca159d971a53ac134f8d7f96e99ef75bf89b258
                        )

                )

        )

)
```
I modified the allowed upload sizes.

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - search_lucene: 0.7.0
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external

```

**The content of config/config.php:**

```
{
    "system": {
        "installed": true,
        "dbtype": "mysql",
        "dbname": "ws_prod_filehost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "remotesqlserver",
        "dbtableprefix": "oc_",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "blacklisted_files": [

        ],
        "overwritehost": "",
        "overwriteprotocol": "",
        "overwritewebroot": "",
        "overwritecondaddr": "",
        "proxy": "",
        "proxyuserpwd": "",
        "theme": "lane",
        "default_language": "en",
        "3rdpartyroot": "",
        "3rdpartyurl": "",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "knowledgebaseurl": "http:\/\/api.apps.owncloud.com\/v1",
        "appstoreenabled": true,
        "appstoreurl": "http:\/\/api.apps.owncloud.com\/v1",
        "mail_smtpdebug": false,
        "mail_smtpmode": "php",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "LOGIN",
        "trashbin_retention_obligation": "180, auto",
        "allow_user_to_change_display_name": true,
        "appcodechecker": "",
        "updatechecker": true,
        "log_type": "syslog",
        "logfile": "",
        "loglevel": 3,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",
        "xframe_restriction": true,
        "datadirectory": "\/mounts\/ws-data\/filehost-data\/prod",
        "maintenance": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "customclient_desktop": "http:\/\/owncloud.org\/sync-clients\/",
        "customclient_android": "https:\/\/play.google.com\/store\/apps\/details?id=com.owncloud.android",
        "customclient_ios": "https:\/\/itunes.apple.com\/us\/app\/owncloud\/id543672169?mt=8",
        "logdateformat": "F d, Y H:i:s",
        "instanceid": "525f0e87378ff",
        "version": "9.0.0.19",
        "ldapIgnoreNamingRules": false,
        "trusted_domains": [
            "blah.blah.ddd"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis"
    }
}


```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

**Comment by jerrac** [comment]
After some digging into the production database, as well as a backup, I figured out a couple things.

All files were transferred the first time.

The item_source, item_target, and file_source columns in oc_share were not updated with the new fileid from oc_filecache. 

Non-file or directory type shares were completely lost. That's why it goes from 85 shares to 75 in my pastebin. Though, that might make sense since the user they were shared with is the user I transferred them to.

Now I just need to manually update those columns...

**Comment by LukasReschke** [comment]
cc @DeepDiver1975

**Comment by jerrac** [comment]
I have, I think, fixed my immediate problems. I found the correct fileid in oc_filecache, then manually set the uid_owner, item_source, item_target, and file_source columns in oc_share to the correct values.

**Comment by PVince81** [comment]
Needs to be retested once 9.0.1 because the "invalid shares" situation should not throw errors as before

**Comment by jerrac** [comment]
I had been messing around oc_storages, and some other tables while figuring out what was wrong before I tried the transfer command. Today I spun up a test instance from the db dump I did before upgrading Friday, and upgraded 8.1.3 -> 8.2.3 -> 9.0.0. When I ran the transfer this time, it worked great.

So, chalk this up to me messing things up. :\ Sorry about that.
