### ISSUE TITLE
Public share links break when share owner becomes invalid

### ISSUE THREAD

**Issue by jerrac** [owncloud/core#23674]
This is in the case where the user simply looses access to the OwnCloud instance. Their data is not deleted. Like if an LDAP user is blocked from LDAP authentication. 

Since the user's data still exists, and the share is a public share, the share should still work. In my specific case, the user was an instructor and had shared a lot of video files that other instructors use in their classes. When those shares broke, lots of people were unhappy...

I'd like all shares to keep working until an admin does something with them. Like transferring file ownership, or fully deleting the user account.

Or, at least, OwnCloud should throw an error like "The user who owns this share is invalid. Contact your administrator." And then in the owncloud.log list the actual user. 

The way it is now, you just get a stack trace.
### Steps to reproduce
1. Make a public link share as a test user
2. Make the test user invalid without deleting data or shares.
3. Visit the share.
### Expected behaviour

Share link should work.
### Actual behaviour

OwnCloud throws a 500 error.
### Server configuration

**Operating system**:
 Ubuntu 14.04

**Web server:**
Apache 2.4

**Database:**
Mysql 5.6

**PHP version:**
5.5

**ownCloud version:** (see ownCloud admin page)
9.0.0
**Updated from an older ownCloud or fresh install:**
Updated from 8.1.3 to 8.2.3 to 9.0.0.
**Where did you install ownCloud from:**
tarball
**Signing status (ownCloud 9.0 and above):**

```
Results
=======
- core
    - INVALID_HASH
        - .htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f40e7ca19cd76ff922ccd164e38f4d73806f66170cafa202fb470be225c813b4b242f4321da8a01bef1329e300acf3d137dbcbff058c501f166a2619031fc651
                            [current] => 87af4d0158a16dfb0e9f2214c6325ece768c9c057ffc463c458a6bdd59d994768af6380cdbe6a984ebed27774ca159d971a53ac134f8d7f96e99ef75bf89b258
                        )

                )

        )

)
```

I modified the allowed upload sizes.

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - search_lucene: 0.7.0
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external

```

**The content of config/config.php:**

```
{
    "system": {
        "installed": true,
        "dbtype": "mysql",
        "dbname": "ws_prod_filehost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "remotesqlserver",
        "dbtableprefix": "oc_",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "blacklisted_files": [

        ],
        "overwritehost": "",
        "overwriteprotocol": "",
        "overwritewebroot": "",
        "overwritecondaddr": "",
        "proxy": "",
        "proxyuserpwd": "",
        "theme": "lane",
        "default_language": "en",
        "3rdpartyroot": "",
        "3rdpartyurl": "",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "knowledgebaseurl": "http:\/\/api.apps.owncloud.com\/v1",
        "appstoreenabled": true,
        "appstoreurl": "http:\/\/api.apps.owncloud.com\/v1",
        "mail_smtpdebug": false,
        "mail_smtpmode": "php",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "LOGIN",
        "trashbin_retention_obligation": "180, auto",
        "allow_user_to_change_display_name": true,
        "appcodechecker": "",
        "updatechecker": true,
        "log_type": "syslog",
        "logfile": "",
        "loglevel": 3,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",
        "xframe_restriction": true,
        "datadirectory": "\/mounts\/ws-data\/filehost-data\/prod",
        "maintenance": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "customclient_desktop": "http:\/\/owncloud.org\/sync-clients\/",
        "customclient_android": "https:\/\/play.google.com\/store\/apps\/details?id=com.owncloud.android",
        "customclient_ios": "https:\/\/itunes.apple.com\/us\/app\/owncloud\/id543672169?mt=8",
        "logdateformat": "F d, Y H:i:s",
        "instanceid": "525f0e87378ff",
        "version": "9.0.0.19",
        "ldapIgnoreNamingRules": false,
        "trusted_domains": [
            "blah.blah.ddd"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis"
    }
}


```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

**Comment by rullzer** [comment]
I don't think there is much we can do here. If we can't lookup the user we can't setup the path to link shares.

**Comment by LukasReschke** [comment]
cc @DeepDiver1975

**Comment by jerrac** [comment]
@rullzer You can't look up the user? Why? The user still exists in the database, as do all their shares. They just cannot authenticate. 

For example, cn=alpha,ou=employees,ou=active,ou=people,dc=blah,dc=tld is moved to cn=alpha,ou=employees,ou=**in**active,ou=people,dc=blah,dc=tld. Or OwnCloud is set up to only authorize users in a ldap group, and alpha is removed from that group. The first case is exactly what I experienced. The second is likely the better way of doing things on the ldap side.

In both cases, nothing in OwnCloud should change. The user just cannot authenticate.


Hrm, actually, thinking about this with a fresher mind, maybe things already work, and it's just my ldap systems odd way of moving ldap entries to deactivate an account that is the issue? 

Does the share system talk to ldap when someone accesses a share created by an ldap user? 'Cause from what happened, it seems to care about the full dn of the ldap user. Not just the part I say is their username.

**Comment by jerrac** [comment]
I just spent some time testing this. On 8.1.3, the shares worked just fine even when the user was inactive.

On 8.2.3, the shares throw 500 errors.

On 9.0.0 the shares throw 500 errors, and cause the 500 error page to refresh indefinitely. 

This is in the:

> For example, cn=alpha,ou=employees,ou=active,ou=people,dc=blah,dc=tld is moved to cn=alpha,ou=employees,ou=inactive,ou=people,dc=blah,dc=tld. 

situation.

I test shares from two different ldap users.

**Comment by hodyroff** [comment]
Please test with 9.1 occ has now a command to disable a user.

**Comment by PVince81** [comment]
in OC 10.0 (and maybe even 9.1) you can disable a user and there's also a transfer ownership command
