### ISSUE TITLE
Files app favorites

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#2368]
As a user, I would like to be able to bookmark certain files to make them extremely easy to access quickly, so that I can open and display files quickly on my iPad and other devices without having to negotiate through all of my existing files on ownCloud.

Can we add a file bookmark?

**Comment by Bugsbane** [comment]
What would be a thing of pure beauty, would be being able to share any given tag, in the exact same way we currently can share files.

I would love to be able to organize my photos according to my own system, and then have all the ones tagged "family" to automatically be shared with everyone in my family group, or to tag files with "client-updates" and automatically have them be shared with my client group.

Yes, I can manually share files with these groups now, but only files, and even then, it's still an extra step, for every single file, to have to tag it, and then also manually share it. I'm sure that having hundreds of individual files being manually shared must clutter the database more than just having the relevant files have a tag, and a single share entry to say that tag x is shared with y.

**Comment by DeepDiver1975** [comment]
@PVince81 missing todos are topic for OC8.1 from my understanding - right?

**Comment by PVince81** [comment]
When I asked @karlitschek he said it's ok to implement the "tags cleanup" part as part of 8.0, as far as I understood.
However I think the changes might be bigger, but I'll give it a shot within the next weeks and we'll see from the PRs.

**Comment by PVince81** [comment]
@Bugsbane interesting idea. Can you make a separate enhancement ticket for this ?

**Comment by karlitschek** [comment]
Yes. This can be seen as a bugfix. I don´t hope a lot of code is needed for that.

**Comment by Bugsbane** [comment]
@PVince81 Sure thing.

**Comment by SergioBertolinSG** [comment]
Related bugs of favorite feature:

- [ ] #13266

**Comment by nickvergessen** [comment]
@PVince81 this can be closed since all other sub tasks have their own tickets right?

**Comment by MorrisJobke** [comment]
@nickvergessen Let's keep it open untill we have a label for the tags feature to not lose the list of tag related issues. Something like `feature:tags" came in my mind ;)

**Comment by nickvergessen** [comment]
The label has been created and added to all the ticket *closing*
