### ISSUE TITLE
Returned info on link share modification ignored

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#23688]
1. enable the password policy app
2. set date max 3 days into future in password policy app
3. create a link share
4. set expiradtion date 1 month into future

The password policy app does it work. And makes sure the correct expiration date is set (this is reflected in the DB). But we ignore the returned value from the OCS Share API. So to the user it seems like the expiration date is the one set at 4.

The information is correct in case of a full page reload.

@pako81 

Setting to 9.0.2 as discussed with @PVince81 
@cmonteroluque FYI

**Comment by rullzer** [comment]
So the info is actually returened as part of the PUT response. And after the PUT we do another get (wich returns the same info). But we just ignore it all :wink:

**Comment by jesmrec** [comment]
@rullzer 

After step 4. the mobile clients have the 2. step date, so they keep the password policy default date although the user sends a new one if is a future date.

**Comment by rullzer** [comment]
@jesmrec awesome! thanks for checking!

**Comment by jesmrec** [comment]
:+1:

**Comment by PVince81** [comment]
@DeepDiver1975 is that what you fixed recently ?
