### ISSUE TITLE
Any menu which opens on click should also open on hover already

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#23683]
This is just to anticipate the click and make interaction on desktop a bit faster. A subsequent click should then of course not close it, but keep it open. (Cause otherwise it will interfere with the click action people are used to currently.)

This goes for the following menus, which are all popover-style:
- App menu in the top left
- User menu in the top right
- Action menu in the files list for every row
- Action menu when it’s used anywhere else, like in the app-navigation (like in News and to be coming in the Calendar app, see https://github.com/owncloud/calendar/pull/400) cc @BernhardPosselt @georgehrke 
- … anything I missed? (Like maybe even the bottom left Settings menu in-app? Not sure about that though since it’s not popover-style.)

cc @owncloud/designers @PVince81

**Comment by BernhardPosselt** [comment]
:+1: awesome idea, absolutely makes sense

**Comment by MorrisJobke** [comment]
> This is just to anticipate the click and make interaction on desktop a bit faster.

But we should not make the opening instant. It should be a bit delayed. Otherwise it will open a lot of menus by just moving your mouse over the interface.

**Comment by BernhardPosselt** [comment]
As far as I've understood it is that its like a normal hover menu, you hover over it and you you can go down and click it, did I understand that correctly?

**Comment by skjnldsv** [comment]
I'm okay but with a small delay too.
We should be able to do it css-side.

**Comment by jancborchardt** [comment]
Not sure we’ll be able to do it via CSS since the menus are triggered by JS as of now, no?

I’m fine with experimenting with instant opening or delay (like 300ms). Let’s see what works best.

**Comment by skjnldsv** [comment]
Yes, the delay should be small enough to not be felt like... a delay, but long enough to not be triggered by your mouse passing through :)

**Comment by PVince81** [comment]
Delays/animations can be done in CSS technically, but I'd still prefer to have delays/debounces in JS

**Comment by skjnldsv** [comment]
@PVince81 Out of curiosity, why? :)

**Comment by rullzer** [comment]
@skjnldsv I think @PVince81 prefers that stuff to be in javascript just so we have all the logic in one place. (I know I do). So if we have to fix delays and or debunces on an action we only have to do it in one location. And not try to have the cross browser mess.

**Comment by skjnldsv** [comment]
I see! :)
It's the opposite for me, css3 is now pretty everywhere accepted, not like 10years ago where it was a complete mess. Nowadays it's pretty convenient! But javascript tends to be very heavy, and using javascript to modify the design of a web page is against the purpose of css. css Was planned to design the whole page. I prefer to separate the uses, css: design; js: dom management and data. ;)

**Comment by paurisa** [comment]
Out of curiosity, how will it be implemented in the end? Through the JS files or the CSS files?

**Comment by jancborchardt** [comment]
@paurisa check out the related pull request (and review it if you like :) https://github.com/owncloud/core/pull/23902 – it's via JS

**Comment by paurisa** [comment]
@jancborchardt Thanks for the link.

**Comment by PVince81** [comment]
Moving to 9.2 as we're past feature freeze

**Comment by PVince81** [comment]
@felixheidecke thoughts ?

**Comment by felixheidecke** [comment]
This really is a global design decision and needs to be seen in the greater context. My quick answer (without any research and user tests) is that I do not support opening **any** menu on hover. This would more often open and close menus unintentionally while wiggling the mouse around the screen. Don't take control away from the user. _"If I decide to open a menu, I'll do it by my self"_

This also does not reflect the current state of interaction on desktops and especially on mobile devices where clicking (tapping) is the defacto standard to open and close apps and menus and such. Better keep those UI experiences closer together.
