### ISSUE TITLE
Encryption + ext storage + versions broken

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#23681]
### Steps

1. Enable encryption
1. Setup SFTP storage as "/sftp"
1. Upload a file through Webdav "/sftp/test.txt"
1. Upload the same file again to create versions
1. Try downloading a version of that file in the web UI

### Expected
Version works

### Actual
Version is broken, thumbnails broken.
Also: version file is not encrypted inside the files folder.

PR is here https://github.com/owncloud/core/pull/23675

@schiesbn @LukasReschke (raised for tracking purposes + test plan)

**Comment by PVince81** [comment]
@cmonteroluque FYI

**Comment by rperezb** [comment]
@owncloud/qa
