### ISSUE TITLE
Cannot share files with remote users - 403 error from API using web interface

### ISSUE THREAD

**Issue by Lovecannon** [owncloud/core#23680]
### Steps to reproduce
1. Try to share any document with a remote user from the web interface
2. The text input where you enter the username/remote user email grays out and has a spinning icon
3. It never stops spinning, and the Javascript console says that the script "/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json" returned a 403 Unauthorized error. 

### Expected behaviour
File gets shared.

### Actual behaviour
Nope. No file share. Just a 403 error. 

### Server configuration
**Operating system**: Ubuntu 14.04:

**Web server:** Nginx 1.8.1

**Database:** MariaDB 

**PHP version:** 5.6 (Latest)

**ownCloud version:** 9.0.0 (Stable)

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** .zip archive from website

**Signing status (ownCloud 9.0 and above):** ??

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

"No errors have been found."
```

**List of activated apps:**
All default apps except external storage (not being used for files that are being shared
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

<?php
$CONFIG = array (
  'instanceid' => 'ocnbyproknbb',
  'passwordsalt' => [redacted],
  'secret' => '[redacted]',
  'trusted_domains' => 
  array (
    0 => '[redacted]',
  ),
  'datadirectory' => '[redacted]',
  'overwrite.cli.url' => '[redacted]',
  'dbtype' => 'mysql',
  'version' => '9.0.0.19',
  **Sensitive DB Data removed
  'dbtableprefix' => 'oc_',
  logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\OC\Memcache\Redis',
  'redis' => array(
     'host' => '[redacted]',
     'port' => 6379,
      ),
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, Google Drive (not being used for the files being shared)

**Are you using encryption:** No

### Client configuration
**Browser:** Chrome

**Operating system:**
Windows

#### ownCloud log (data/owncloud.log)
```
{"reqId":"jbjbws1GOPC1WXHdcQxJ","remoteAddr":"","app":"PHP","message":"Undefined index: newVersionString at \/sites\/prod\/[redacted]\/releases\/20160330194235Z\/app\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-31T03:31:06+00:00"}
{"reqId":"DaBEYB27enpF+zLj0skq","remoteAddr":"","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-03-31T03:37:02+00:00"}
{"reqId":"NqBfhgKOXx2wlx7hB+mT","remoteAddr":"","app":"PHP","message":"Undefined index: newVersionString at \/sites\/prod\/[redacted]\/releases\/20160330194235Z\/app\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-31T03:46:51+00:00"}
{"reqId":"V0jCuavDwkAGS2rXuztz","remoteAddr":"","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-03-31T03:49:02+00:00"}
{"reqId":"PlifOWEO4vE8SvlinFlZ","remoteAddr":"","app":"PHP","message":"Undefined index: newVersionString at \/sites\/prod\/[redacted]\/releases\/20160330194235Z\/app\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-31T03:49:56+00:00"}
{"reqId":"HtrlANt86mfKPrnshvSN","remoteAddr":"","app":"PHP","message":"Undefined index: newVersionString at \/sites\/prod\/[redacted]\/releases\/20160330194235Z\/app\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-31T03:52:21+00:00"}
{"reqId":"xYyV3BMbzk5DOTGFg+YH","remoteAddr":"","app":"PHP","message":"Undefined index: newVersionString at \/sites\/prod\/[redacted]\/releases\/20160330194235Z\/app\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-31T03:56:30+00:00"}
{"reqId":"rHJrHUEkwOsQcgfD3KLz","remoteAddr":"","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-03-31T04:01:02+00:00"}
{"reqId":"60ZG7wvVLGaTu70SN1Sh","remoteAddr":"","app":"PHP","message":"Undefined index: newVersionString at \/sites\/prod\/[redacted]\/releases\/20160330194235Z\/app\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-31T04:02:47+00:00"}
{"reqId":"jb+SgdRfldA3Dd8l4tu0","remoteAddr":"","app":"PHP","message":"Undefined index: newVersionString at \/sites\/prod\/[redacted]\/releases\/20160330194235Z\/app\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-03-31T04:10:47+00:00"}
```

**Comment by blizzz** [comment]
@owncloud/sharing

**Comment by rullzer** [comment]
I just tested on stable9 and it works over here.

The 403 is kind of weird here. Can you do regular shares?

**Comment by Lovecannon** [comment]
Yes, I have no issues sharing with OwnCloud users/groups. It is only the remote users that causes the 403 error.

**Comment by rullzer** [comment]
Ok I'm going to need more setup info.

* Are you using https?
* Do both servers have valid certificates?
* which version is the remote ownCloud running

**Comment by Lovecannon** [comment]
Yes. I'm using HTTPS and the certificates are invalid. And by remote users, I mean just entering an email for sharing a link. Not a remote user of another ownCloud. 

Also on a side note, is it not possible to share links from external storage mounts? I set up an S3 bucket to store files since my server doesn't have the kind of space that my company wants and its working correctly, but all the share links are gone and it says "Resharing is not allowed" even though the allow resharing option in the admin area is enabled.

**Comment by rullzer** [comment]
Aha!

Yes sharing the link to a user is different. You need to enable e-mail notifications (in your admin settings). Then you create a link share. And then you can notify people by link.

If you enter a link share in the 'normal' input field it will try to create a deferated share.

**Comment by rullzer** [comment]
Regarding your S3 bucket. You need to enbale sharing in the admin settings of your external storage.

**Comment by Lovecannon** [comment]
Well I feel dumb now. I didn't even see the settings icon in the external storage area. Thanks. 

Also, just a suggestion but it isn't very obvious that you can't share links through email in that section and it might not be a good idea to have some kind of warning or something when you enter an email address.

**Comment by Lovecannon** [comment]
Sorry to bug you again but by any chance do you know if its possible to disable the default storage under the data directory and force an external storage to be used? I don't have a ton of space on the application server that's running OwnCloud so I only want to use the S3 bucket to store files + whatever personal external storage is for the user. I'd like to avoid anybody uploading to the server itself.

**Comment by rullzer** [comment]
@Lovecannon well a federated id is the same <user>@<server> so that is why it is hard to do this

Also no... this is not possibe...

Closing this as it is resolved.
