### ISSUE TITLE
ownCloud disfunctional when a to-be-trusted ownCloud's admin removes status.php (a thing you should never ever do)

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#23687]
### Steps to reproduce
1. as admin of ownCloud B, remove status.php
2. as user of ownCloud B send a federated share to ownCloud A
3. as receipient of ownCloud A, accept the share

### Expected behaviour

Trusted ownCloud verification should be attempted couple times, eventually it should fail gracefully and not be attempted anymore, or at least considered unverified. A badly setup foreign ownCloud should not render my ownCloud disfunctional.

### Actual behaviour

1. verification is attempt continuosly
2. log is flooded with exceptions
3. cron.php stuck

### Server configuration

ownCloud A

**Operating system**: Ubuntu 14.04

**Web server:** Apache2

**Database:** MySQL
 
**PHP version:** PHP 5.5.9

**ownCloud version:** 9.0

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tarball

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

ownCloud B runs 8.1.5.

#### ownCloud log (data/owncloud.log)
```
{"reqId":"yHfLspM+8hUzgNJScpEf","remoteAddr":"","app":"federation","message":"Exception: {\"Exception\":\"GuzzleHttp\\Exception\\ClientException\",\"Message\":\"Client error response [url] https://bad.owncloud.server//ocs/v2.php/apps/federation/api/v1/request-shared-secret?format=json [status code] 404 [reason phrase] Not Found\",\"Code\":404,\"Trace\":\"
#0 /path/to/owncloud/3rdparty/guzzlehttp/guzzle/src/Subscriber/HttpError.php(33): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Message\\Request), Object(GuzzleHttp\\Message\\Response))\
#1 /path/to/owncloud/3rdparty/guzzlehttp/guzzle/src/Event/Emitter.php(109): GuzzleHttp\\Subscriber\\HttpError->onComplete(Object(GuzzleHttp\\Event\\CompleteEvent), 'complete')\
#2 /path/to/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\\Event\\Emitter->emit('complete', Object(GuzzleHttp\\Event\\CompleteEvent))\
#3 /path/to/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))\
#4 /path/to/owncloud/3rdparty/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\\RequestFsm->GuzzleHttp\\{closure}(Array)\
#5 /path/to/owncloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL, NULL)\
#6 /path/to/owncloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\\Ring\\Future\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\
#7 /path/to/owncloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php(135): GuzzleHttp\\Message\\FutureResponse::proxy(Object(GuzzleHttp\\Ring\\Future\\CompletedFutureArray), Object(Closure))\
#8 /path/to/owncloud/3rdparty/guzzlehttp/guzzle/src/Client.php(165): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))\
#9 /path/to/owncloud/3rdparty/guzzlehttp/guzzle/src/Client.php(150): GuzzleHttp\\Client->send(Object(GuzzleHttp\\Message\\Request))\
#10 /path/to/owncloud/lib/private/http/client/client.php(191): GuzzleHttp\\Client->post('https://ownclou...', Array)\
#11 /path/to/owncloud/apps/federation/backgroundjob/requestsharedsecret.php(146): OC\\Http\\Client\\Client->post('https://ownclou...', Array)\
#12 /path/to/owncloud/lib/private/backgroundjob/job.php(52): OCA\\Federation\\BackgroundJob\\RequestSharedSecret->run(Array)\
#13 /path/to/owncloud/lib/private/backgroundjob/queuedjob.php(42): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\
#14 /path/to/owncloud/apps/federation/backgroundjob/requestsharedsecret.php(125): OC\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\
#15 /path/to/owncloud/apps/federation/backgroundjob/requestsharedsecret.php(116): OCA\\Federation\\BackgroundJob\\RequestSharedSecret->parentExecute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\
#16 /path/to/owncloud/cron.php(141): OCA\\Federation\\BackgroundJob\\RequestSharedSecret->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\
#17 {main}\",\"File\":\"/path/to/owncloud/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php\",\"Line\":89}","level":3,"time":"2016-03-30T09:46:32+00:00"}
```

after removing the server from "trusted servers" on the admin page:

```
file_get_contents(https://foreign.owncloud.com//status.php): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found at /path/to/owncloud/apps/files_sharing/lib/external/storage.php#260
```

Perhaps related to the federated shares? At least those work ;)

@schiesbn @rullzer

**Comment by PVince81** [comment]
also @icewind1991 @LukasReschke

**Comment by rullzer** [comment]
Ok this seems like we do something bad somewhere... and retry to often. Lets fix it...

**Comment by rullzer** [comment]
mmm status.php removal actually kind of work fine here... I do get flodded in the cron with not being able to exchange addressbooks. (since we only allow that over https).

Solution that I propose is to do this only once a day. That way the system will keep trying but only once a day. So that if somebody upgrades their installation to 9.0 or higher you can start exchaning. Or if they fix their setup etc.

**Comment by PVince81** [comment]
Too bad background jobs cannot auto-delay themselves in case of error.

Not sure if once a day is enough though, especially for such corner case.

I seem to remember that @schiessle said that some of the bkg jobs would only try a few times then give up. Maybe it was a different one, the one that syncs permissions.

**Comment by rullzer** [comment]
this one just continues as far as I can tell... no max retry or something

**Comment by rullzer** [comment]
Also this is about the initial setup. We could maybe implement some exponential backoff or so.

**Comment by nickvergessen** [comment]
The part of "killing cron" has been addressed with https://github.com/owncloud/core/pull/23436
This will make the background job being tested once per execution cycle, which I think is fine.

Closing as such.
