### ISSUE TITLE
Packaging: Installing owncloud does not install php-mysql

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#23685]
@jnweiger 
### Steps to reproduce

1.Fresh Install on Suse Leap
2. Use "owncloud"-package 
3. 
### Expected behaviour

After Installation all "required" because recommended packages should be installed.
### Actual behaviour

php5-mysql modul ist not installled
### Server configuration

**Operating system**:
opensuse Leap
**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**
fresh install from "owncloud" package
**Where did you install ownCloud from:**

**Comment by crrodriguez** [comment]
Fixed a long time ago.
