### ISSUE TITLE
When trying to decrypt a single user using occ it states to decrypt ALL files

### ISSUE THREAD

**Issue by e-alfred** [owncloud/core#23695]
### Steps to reproduce
1. Admin wants to decrypt a single user by issuing the command `sudo -u www-data php occ encryption:decrypt user`

### Expected behaviour
Only user should be decrypted without disabling the encryption backend for all the other users. The message should be unambigously telling you that only the selected user gets decrypted and act accordingly (i. e. not decrypting everything and disabling the encryption backend).

### Actual behaviour
The cli tool occ tells you this:

```
Disable server side encryption... done.

You are about to start to decrypt all files stored in your ownCloud.
It will depend on the encryption module and your setup if this is possible.
Depending on the number and size of your files this can take some time
Please make sure that no user access his files during this process!

Do you really want to continue? (y/n) 
```

### Server configuration
**Operating system**: Debian 8 "Jessie"

**Web server:** Apache 2.4.10 (from default repository)

**Database:** Mysql 5.5.46 (from default repository)

**PHP version:** 5.6.14 (from default repository)

**ownCloud version:** 8.2.3

**Updated from an older ownCloud or fresh install:** 8.1

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - encryption: 1.1.0
  - external: 1.2
  - files: 1.2.0
  - files_clipboard: 0.4.1
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - imprint: 0.2.5
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - search_lucene: 0.7.0
  - templateeditor: 0.1
  - files_trashbin
Disabled:
  - updater
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc8bj094mu3d",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***""
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***"",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "theme": "",
        "maintenance": false,
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "ldapIgnoreNamingRules": false,
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        }
    }
}

**Are you using encryption:** yes

**Comment by LukasReschke** [comment]
cc @owncloud/encryption
