### ISSUE TITLE
Avatar doesn't rotate JPGs based on exif data

### ISSUE THREAD

**Issue by josh4trunks** [owncloud/core#23697]
### Steps to reproduce
1. Settings > Personal
2. Upload a JPG which has exif rotation
3. Or.. Choose a JPG which has exif rotation data 
### Expected behaviour

Image should be automatically rotated based on exif data
### Actual behaviour

JPG's exif data is ignored. Images in crop area, and after cropping are not rotated properly.
### Server configuration

**Web server:** NGINX and Apache2.4

**PHP version:** 5.6

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** source

**Signing status (ownCloud 9.0 and above):**  All checks passed.

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Firefox and Chrome

**Operating system:** Linux and Android
#### Web server error log

```
Nothing relevant
```
#### ownCloud log (data/owncloud.log)

```
Nothing relevant
```
#### Browser log

```
Nothing relevant
```

**Comment by josh4trunks** [comment]
See my fix for this when `core/avatar/controller.php` was used.

https://github.com/owncloud/core/pull/8812#issue-34748288
Looks like this script was rewritten and the logic I added to do exif rotation for uploaded/encrypted files was not re-implemented.

**Comment by rullzer** [comment]
I'll have a look at this as I most likely broke it.

**Comment by josh4trunks** [comment]
i got files from disk working, I'll post my diff once I get uploaded files working (almost there!).

Then please feel free to create a PR and fix up my functions cause I'm just throwing in different functions until it works, lol.

**Comment by josh4trunks** [comment]
Alright this worked in my testing. Feel free to adapt this. I also still need to test with encryption enabled.

```
--- core/controller/avatarcontroller.php-orig	2016-03-31 05:29:15.149876484 -0700
+++ core/controller/avatarcontroller.php	2016-03-31 08:55:37.490876581 -0700
@@ -170,7 +170,8 @@
 					$headers
 				);
 			}
-			$content = $node->getContent();
+			$view = new \OC\Files\View();
+			$fileName = $view->getLocalFile($node->getPath());
 		} elseif (!is_null($files)) {
 			if (
 				$files['error'][0] === 0 &&
@@ -185,7 +186,8 @@
 					);
 				}
 				$this->cache->set('avatar_upload', file_get_contents($files['tmp_name'][0]), 7200);
-				$content = $this->cache->get('avatar_upload');
+				$view = new \OC\Files\View();
+				$fileName = $view->getLocalFile($userId.DIRECTORY_SEPARATOR.'cache'.DIRECTORY_SEPARATOR.'avatar_upload');
 				unlink($files['tmp_name'][0]);
 			} else {
 				return new DataResponse(
@@ -205,7 +207,7 @@
 
 		try {
 			$image = new \OC_Image();
-			$image->loadFromData($content);
+			$image->loadFromFile($fileName);
 			$image->fixOrientation();
 
 			if ($image->valid()) {
```

**Comment by josh4trunks** [comment]
The above seems to work with encryption =]

**Comment by rullzer** [comment]
Do you have a test file for me with rotation exif data?

**Comment by rullzer** [comment]
Because we want to move more and more to the Node API and away from views.

**Comment by josh4trunks** [comment]
Here's an example. The image should be in portrait not landscape.
![Uploading 20160329_124413.jpg…]()

I don't think it's possible to avoid views if you use fixOrientation. Maybe you can put the functions you need to get the full file path in fixOrientation()? But for now my changes fix this so owncloud doesn't look like a paritally baked product when you try setting up an avatar.

**Comment by josh4trunks** [comment]
@rullzer is there any way to get the full file path to a file without views? If not, I don't think we have a choice but to use it whenever presenting JPGs in ownCloud.

PHP's `exif_read_data` needs a full file path and can't work with streams.
http://grokbase.com/t/php/php-bugs/1372p2wp45/php-bug-req-65187-new-exif-read-data-add-support-for-stream-resource

**Comment by josh4trunks** [comment]
@rullzer do you still plan on working on this?
I can submit a PR with the change I proposed here https://github.com/owncloud/core/issues/23697#issuecomment-204000138

I understand it isn't preferred to use 'views' but I don't see any other solutions being presented to get the full file path.

**Comment by josh4trunks** [comment]
@rullzer Using Node, can we construct the full local file path with getMountPoint() and getPath()? I worry about local mountpoints, but I haven't experimented with this yet.

**Comment by rullzer** [comment]
@josh4trunks sorry been busy. Uhm you could get the path like that I think.

**Comment by josh4trunks** [comment]
No worries, just wanted to get rotation working eventually.
I'll look into those functions and see if they could work.

**Comment by rullzer** [comment]
I think I have a fix for the upload case...
The select file cache is harder since we don't have any quarantees that the file is on local storage

**Comment by josh4trunks** [comment]
I just tried browsing to and uploading the iamge above, and in both case the rotation still does not work as it should.

**Comment by PVince81** [comment]
Please reopen if problem still exists 10.0.4.
