### ISSUE TITLE
When restoring files of a deleted user by recreating it applying a new password to the private key fails

### ISSUE THREAD

**Issue by e-alfred** [owncloud/core#23693]
### Steps to reproduce
1. Delete user in the admin panel which deletes all files as well (backup of the user created before this operation, encryption enabled in owncloud, no recovery key)
2. Restore user by recreating it and setting a new password (the user should change it later, no recovery key enabled)
3. Log in to the user so everything needed is set up
4. Now copy the backed up files back into the newly created user directory (Keys, Files).
5. The user logs in with the password created by the admin and gets a message "Invalid private key for Encryption App. Please update your private key password in your personal settings to recover access to your encrypted files."
6. The user tries to change the password of the private key to the new one and gets "The old password was not correct, please try again.".  The old password is 100% correct and the date of the last change of the private key corresponds with the last change of the password by the user.

### Expected behavior
The password that secures the private key should be changed to the new one and the user should be able to access his encrypted files restored from the backups without problems.

### Actual behavior
The user gets the message that the password is incorrect all the time while trying to change the password of the private key. In the owncloud logs this message is shown:

`{"reqId":"ksTuCM2ELjNZhM65qsek","remoteAddr":"***REMOVED SENSITIVE VALUE***"","app":"no app in context","message":"Exception: {\"Exception\":\"OCA\\\\Encryption\\\\Exceptions\\\\PrivateKeyMissingException\",\"Message\":\"Private Key missing for user: please try to log-out and log-in again\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/keymanager.php(401): OCA\\\\Encryption\\\\Session->getPrivateKey()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(172): OCA\\\\Encryption\\\\KeyManager->getFileKey('\\\/user\\\/files...', 'user')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(248): OCA\\\\Encryption\\\\Crypto\\\\Encryption->begin('\\\/user\\\/files...', 'user', 'rb', Array, Array)\\n#3 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_open('ocencryption:\\\/\\\/', 'rb', 0, NULL)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(188): fopen('ocencryption:\\\/\\\/', 'rb', false, Resource id #50)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(170): OC\\\\Files\\\\Stream\\\\Encryption::wrapSource(Resource id #49, 'rb', Resource id #50, 'ocencryption', 'OC\\\\\\\\Files\\\\\\\\Stream...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/encryption.php(413): OC\\\\Files\\\\Stream\\\\Encryption::wrap(Resource id #49, 'files\\\/administr...', '\\\/user\\\/files...', Array, 'user', Object(OCA\\\\Encryption\\\\Crypto\\\\Encryption), Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Quota), Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption), Object(OC\\\\Encryption\\\\Util), Object(OC\\\\Encryption\\\\File), 'rb', 474160, 474160, 8192)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(286): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fopen('files\\\/administr...', 'rb')\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_antivirus\\\/lib\\\/avirwrapper.php(60): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('files\\\/administr...', 'rb')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1022): OCA\\\\Files_Antivirus\\\\AvirWrapper->fopen('files\\\/administr...', 'rb')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(872): OC\\\\Files\\\\View->basicOperation('fopen', '\\\/administration...', Array, 'rb')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(374): OC\\\\Files\\\\View->fopen('\\\/administration...', 'rb')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files.php(178): OC\\\\Files\\\\View->readfile('\\\/administration...')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files.php(90): OC_Files::getSingleFile(Object(OC\\\\Files\\\\View), '\\\/administration...', 'pp.pdf', false)\\n#14 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/download.php(53): OC_Files::get('\\\/administration...', Array, false)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#16 [internal function]: __lambda_func(Array)\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(291): call_user_func('\\\\x00lambda_521', Array)\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(849): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#19 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/session.php\",\"Line\":78}","level":3,"time":"2016-03-30T11:19:43+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/download.php?dir=%2Fadm%2Fdocs&files=pp.pdf"}`

Both the private and public key are located in the directory /data/user/files_encryption/OC_DEFAULT_MODULE/. The file keys are located in the directory /data/user/files_encryption/keys/. All files belong to www-data and have 755 permissions.

### Server configuration
**Operating system**: Debian 8 "Jessie"

**Web server:** Apache 2.4.10 (from default repository)

**Database:** Mysql 5.5.46 (from default repository)

**PHP version:** 5.6.14 (from default repository)

**ownCloud version:** 8.2.3

**Updated from an older ownCloud or fresh install:** 8.1

**List of activated apps:**
Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - documents: 0.11.0
  - encryption: 1.1.0
  - external: 1.2
  - files: 1.2.0
  - files_clipboard: 0.4.1
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - imprint: 0.2.5
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - search_lucene: 0.7.0
  - templateeditor: 0.1
Disabled:
  - files_trashbin
  - updater
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc8bj094mu3d",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***""
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***"",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "theme": "",
        "maintenance": false,
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "ldapIgnoreNamingRules": false,
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        }
    }
}

**Are you using encryption:** yes

### Client configuration
**Browser:** Firefox 45

**Operating system:** Kubuntu 14.04.3 LTS

**Comment by LukasReschke** [comment]
> Delete user in the admin panel which deletes all files as well (backup of the user created before this operation, encryption enabled in owncloud, no recovery key)
> Restore user by recreating it and setting a new password (the user should change it later, no recovery key enabled)

This is not something that we can support also considering the fact that in 9.0 some more additional data is stored in the filecache which would break with this.

**Comment by e-alfred** [comment]
Okay, so just for clarification: How can I restore certain encrypted files of a deleted user so they can be used by other users (i. e. shared files before deletion)? And why is this misleading 

> Invalid private key for Encryption App. Please update your private key password in your personal settings to recover access to your encrypted files.

 there if it is unsupported?
