### ISSUE TITLE
Fatal Errors, why?

### ISSUE THREAD

**Issue by Tealk144** [owncloud/core#23700]
Steps to reproduce
Dont know why this errors are in the log file

Server configuration
Operating system: Debian 8.0 jessie minimal
Web server: Apache/2.4.10 (Debian)
Database: mysqlnd 5.0.11
PHP version: 5.6.17-0+deb8u1
ownCloud version (see ownCloud admin page): 9.0.0 (stable)
Updated from an older ownCloud or fresh install: No
ownCloud log (data/owncloud.log): http://pastebin.com/s4pKAEfJ

Special configuration (external storage, external authentication, reverse proxy, server-side-encryption): Nothing

**Comment by DeepDiver1975** [comment]
Thats an issue in the search_lucene app - please reopen in the according repo - THX

**Comment by RealRancor** [comment]
@DeepDiver1975 Seems there are also various "Duplicate entry" errors from core tables in the logs
 Had pointed that user from the forums here as we can't help with such database / sql related stuff there.
