### ISSUE TITLE
files_videoplayer: error when video file is in subdirectory

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#23703]
### Steps to reproduce
1. OC 8.1.6 + patches https://github.com/owncloud/apps/pull/2160 and https://github.com/owncloud/core/pull/23301
2. Play mp4-video located in the root-directory -> works
3. Move file into subdirectory `test`
4. Cannot play file

### Expected behaviour
Play video file

### Actual behaviour
Window remains dark and can't load content.

Browser (FF 45.0.1, Win 7 Pro) console shows error:
`HTTP-Laden ist mit dem Status 404 fehlgeschlagen. Laden der Medienressource https://myserver/owncloud/remote.php/webdav/testSampleVideo_1280x720_5mb.mp4 fehlgeschlagen.`

A corresponding 404-error can be found in the apache-log.

`test` is the subdirectory so the links should be: https://myserver/owncloud/remote.php/webdav/test/SampleVideo_1280x720_5mb.mp4

### Server configuration
**Operating system**: Ubuntu 14.04/Apache/mod_php/mysql

**ownCloud version:** 8.1.6 (+ two patches from above)

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** manual install

**List of activated apps:**

```
 - activity: 2.0.2
 - bookmarks: 0.5
 - calendar: 0.7.4
 - contacts: 0.4.0.1
 - documents: 0.10.2
 - external: 1.2
 - files: 1.1.10
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.3
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - galleryplus: 14.4.0
 - maps: 0.0.6
 - news: 6.1.1
 - ownnote: 1.05
 - tasks: 0.8
```

Hope that's enough information.

**Comment by MorrisJobke** [comment]
@tflidd Could you try with https://download.owncloud.org/community/daily/owncloud-daily-stable8.1.tar.bz2

**Comment by MorrisJobke** [comment]
> @tflidd Could you try with https://download.owncloud.org/community/daily/owncloud-daily-stable8.1.tar.bz2

But let me first try it here again.

**Comment by MorrisJobke** [comment]
> But let me first try it here again.

I just tested and it works. Maybe the browser cache has still the old version, because the cache buster only works if the app version number is raised.

**Comment by tflidd** [comment]
Strange. I tried the owncloud-daily which is working. So I upgraded my current setup (8.1.6) to the daily stable-version and it is working as well. So; I'm not sure what went wrong, perhaps only a caching issue.

Sorry for the noise.
