### ISSUE TITLE
missing files: 3rdparty/Dropbox/API.php and js/vendor/ace/src-noconflict/mode-diff.js

### ISSUE THREAD

**Issue by SEETechWolf** [owncloud/core#23714]
### Steps to reproduce
1. clean install from owncloud-9.0.0.zip
2. integrity check lists two files 3rdparty/Dropbox/API.php and js/vendor/ace/src-noconflict/mode-diff.js thease ar not part of owncloud-9.0.0.zip

### Expected behaviour
Remove files from check or add files to zip

### Actual behaviour
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_external
	- INVALID_HASH
		- 3rdparty/Dropbox/API.php
- files_texteditor
	- INVALID_HASH
		- js/vendor/ace/src-noconflict/mode-diff.js

Raw output
==========
Array
(
    [files_external] => Array
        (
            [INVALID_HASH] => Array
                (
                    [3rdparty/Dropbox/API.php] => Array
                        (
                            [expected] => a6866ef3ceeb26d9d4b2ccc343aeaf626c82f03e279962bc7d761a68e87e5a7916ff0bcf7a350e20889557336ed9c5dd1651cfe513fa04bb8a03cd6d8f9cc484
                            [current] => 917eed2c4f6359a4d0b8658a36404c83344b0bf72ccda614dd59f97d099b3d9ef4e86691401c64d3754c3f7e0fa163eab946a25dbc7bc65e1694ffd47a054317
                        )

                )

        )

    [files_texteditor] => Array
        (
            [INVALID_HASH] => Array
                (
                    [js/vendor/ace/src-noconflict/mode-diff.js] => Array
                        (
                            [expected] => 4a59b6376376b81e4e12ccc345065db62029a61035a88e19b1be3d7ec4cd9f86444121cca6d46c44a5f86e4f5b44d5109cbc77e80c07ff8dbce61f758b88e765
                            [current] => 298cba4d3b472b418aca47db6522c752a4b5530de3f6f2d83eb42eb5fe4231356bfd860a7e2f735b3e5ced759dbc6ca26fc6a18c49bd7ffa07d5a6faa78ae51d
                        )

                )

        )

)

**Comment by LukasReschke** [comment]
> thease ar not part of owncloud-9.0.0.zip

Where did you get that ZIP from? https://download.owncloud.org/community/owncloud-9.0.0.zip has this file inside and they do pass the integrity test.

**Comment by SEETechWolf** [comment]
yes thats the link: https://download.owncloud.org/community/owncloud-9.0.0.zip
and this zip dose not even have a js folder
and it is missing the Dropbox folder
![missing js folder](https://cloud.githubusercontent.com/assets/16180461/14189913/280a3ef2-f790-11e5-9000-b7676725d6f9.png)
![missing dropbox folder](https://cloud.githubusercontent.com/assets/16180461/14189912/28059cc6-f790-11e5-92f7-4d25ea057b43.png)

**Comment by SEETechWolf** [comment]
I also downloaded the owncloud-9.0.0.tar.bz2 from the same location it mises the same two folders or files

**Comment by LukasReschke** [comment]
@SEETechWolf You're looking at the wrong place. Look at apps/files_external and apps/files_texteditor

**Comment by SEETechWolf** [comment]
OK thanks thats solved..
Then the message was missleading sorry

**Comment by dialogue2sourds** [comment]
Just for info, it's 2017 and the message is still missleading on the wrong 3rdParty directory (for an owncloud newbie) . Anyway You are all doing an amazing job , thank you.

**Comment by kdslkdsaldsal** [comment]
@dialogue2sourds There is an open feature request to change this and make it more clear available here: https://github.com/owncloud/core/issues/24110
