### ISSUE TITLE
Rackspace: No endpoints for service type

### ISSUE THREAD

**Issue by gillivj** [owncloud/core#23725]
Hi Guys,

I trying to attache Rackspace cloud files container as external storage in my owncloud v9.
I specified right Username and API Key as provided in rackspace, but it fails with error message 'No endpoints for service type [object-store]'. I don't see a input field for endpoint URL for rackspace authentication type. I believe, owncloud should use the endpoint url(https://identity.api.rackspacecloud.com/v2.0/) as configured in system.

Also, i noticed a bug where, i change the auth to openStack, and key-in some values, it will saved to oc_external_config. Then, when swicth the auth back to rackspace, i still see the old keys in db settings like tenant, url.

Please advice.
Thanks

**Comment by LukasReschke** [comment]
cc @icewind1991 @Xenopathic

**Comment by Xenopathic** [comment]
The URL is definitely correct, but unfortunately without a Rackspace account I can't test it.

However, the persistence of config settings is a serious problem, since those parameters will be passed through to the backend and could subtly break things. I'll have a look.

**Comment by gillivj** [comment]
Hi, 
Following image shows the owncloud setting for rackspace.
![image](https://cloud.githubusercontent.com/assets/11921696/14239248/298aaea4-fa6c-11e5-81cc-5e4a4b14d6d5.png)

I don't see any field for URL. But, it fails to attach with error 'No endpoints for service type' as show below.

Exception: {"Exception":"OpenCloud\\Common\\Exceptions\\EndpointError","Message":"No endpoints for service type [object-store], name [Rackspace Cloud Files], region [HKG] and urlType [publicURL]","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/3rdparty\/rackspace\/php-opencloud\/lib\/OpenCloud\/Common\/Service\/CatalogService.php(72): OpenCloud\\Common\\Service\\CatalogService->findEndpoint()\n#1 \/var\/www\/html\/owncloud\/3rdparty\/rackspace\/php-opencloud\/lib\/OpenCloud\/ObjectStore\/Service.php(43): OpenCloud\\Common\\Service\\CatalogService->__construct(Object(OpenCloud\\Rackspace), NULL, 'Rackspace Cloud...', 'HKG', NULL)\n#2 \/var\/www\/html\/owncloud\/3rdparty\/rackspace\/php-opencloud\/lib\/OpenCloud\/Common\/Service\/ServiceBuilder.php(43): OpenCloud\\ObjectStore\\Service->__construct(Object(OpenCloud\\Rackspace), NULL, 'Rackspace Cloud...', 'HKG', NULL)\n#3 \/var\/www\/html\/owncloud\/3rdparty\/rackspace\/php-opencloud\/lib\/OpenCloud\/OpenStack.php(459): OpenCloud\\Common\\Service\\ServiceBuilder::factory(Object(OpenCloud\\Rackspace), 'OpenCloud\\\\Objec...', Array)\n#4 \/var\/www\/html\/owncloud\/apps\/files_external\/lib\/swift.php(524): OpenCloud\\OpenStack->objectStoreService('Rackspace Cloud...', 'HKG')\n#5 \/var\/www\/html\/owncloud\/apps\/files_external\/lib\/swift.php(549): OC\\Files\\Storage\\Swift->getConnection()\n#6 \/var\/www\/html\/owncloud\/apps\/files_external\/lib\/swift.php(259): OC\\Files\\Storage\\Swift->getContainer()\n#7 \/var\/www\/html\/owncloud\/lib\/private\/files\/storage\/common.php(434): OC\\Files\\Storage\\Swift->stat('')\n#8 \/var\/www\/html\/owncloud\/apps\/files_external\/lib\/config.php(231): OC\\Files\\Storage\\Common->test(false)\n#9 \/var\/www\/html\/owncloud\/apps\/files_external\/controller\/storagescontroller.php(256): OC_Mount_Config::getBackendStatus('\\\\OC\\\\Files\\\\Stora...', Array, false)\n#10 \/var\/www\/html\/owncloud\/apps\/files_external\/controller\/userglobalstoragescontroller.php(117): OCA\\Files_External\\Controller\\StoragesController->updateStorageStatus(Object(OCA\\Files_external\\Lib\\StorageConfig))\n#11 [internal function]: OCA\\Files_External\\Controller\\UserGlobalStoragesController->show(12)\n#12 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(159): call_user_func_array(Array, Array)\n#13 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/http\/dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OCA\\Files_External\\Controller\\UserGlobalStoragesController), 'show')\n#14 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/app.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\Files_External\\Controller\\UserGlobalStoragesController), 'show')\n#15 \/var\/www\/html\/owncloud\/lib\/private\/appframework\/routing\/routeactionhandler.php(45): OC\\AppFramework\\App::main('UserGlobalStora...', 'show', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#16 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#17 \/var\/www\/html\/owncloud\/lib\/private\/route\/router.php(273): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#18 \/var\/www\/html\/owncloud\/lib\/base.php(873): OC\\Route\\Router->match('\/apps\/files_ext...')\n#19 \/var\/www\/html\/owncloud\/index.php(39): OC::handleRequest()\n#20 {main}","File":"\/var\/www\/html\/owncloud\/3rdparty\/rackspace\/php-opencloud\/lib\/OpenCloud\/Common\/Service\/CatalogService.php","Line":196}

**Comment by gillivj** [comment]
Hi, 
I just tried input 'CloudFiles' as service name and works.

**Comment by Xenopathic** [comment]
Ah, that explains it. Looks like a documentation issue then.

**Comment by gillivj** [comment]
yeah. Please include the note in doc then. Thanks man
