### ISSUE TITLE
Don’t create »default« address book if another one already exists

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#23720]
Besides, the »default« address book should be called »Contacts«, a less technical name. cc @DeepDiver1975

**Comment by aspdye** [comment]
Instead of "Default" or "Contacts" i think we should call it "Home" or "Private" :wink:

**Comment by DeepDiver1975** [comment]
This is already the case - the default calendar as well as the default addressbook are created only if the user has none - see https://github.com/owncloud/core/blob/master/apps/dav/lib/hookmanager.php#L106

**Comment by jancborchardt** [comment]
@DeepDiver1975 is it also called »Contacts«, as requested above? »default« is too technical.

**Comment by DeepDiver1975** [comment]
How shall we name the default calendar?

**Comment by jancborchardt** [comment]
@georgehrke what do you think? »Personal«, I’m thinking.

(When sharing, and there are several calendars by the same name, the username of the owner should be appended. Like »Personal (thomas)«.)

**Comment by georgehrke** [comment]
`Personal` sounds just fine :smile:
