### ISSUE TITLE
Error with mail?

### ISSUE THREAD

**Issue by Tealk144** [owncloud/core#23724]
Steps to reproduce
Dont know why this errors are in the log file

Server configuration
Operating system: Debian 8.0 jessie minimal
Web server: Apache/2.4.10 (Debian)
Database: mysqlnd 5.0.11
PHP version: 5.6.17-0+deb8u1
ownCloud version (see ownCloud admin page): 9.0.0 (stable)
Updated from an older ownCloud or fresh install: No
ownCloud log (data/owncloud.log):
`Error while running background job (class: OCA\Activity\BackgroundJob\EmailNotification, arguments: ): {"Exception":"Exception","Message":"Session has been closed - no further changes to the session are allowed","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/session\/memory.php(49): OC\\Session\\Memory->validateSession()\n#1 \/var\/www\/owncloud\/lib\/private\/security\/csrf\/tokenstorage\/sessionstorage.php(63): OC\\Session\\Memory->set('requesttoken', '4N2iHrczsrUVGQR...')\n#2 \/var\/www\/owncloud\/lib\/private\/security\/csrf\/csrftokenmanager.php(57): OC\\Security\\CSRF\\TokenStorage\\SessionStorage->setToken('4N2iHrczsrUVGQR...')\n#3 \/var\/www\/owncloud\/lib\/public\/util.php(496): OC\\Security\\CSRF\\CsrfTokenManager->getToken()\n#4 \/var\/www\/owncloud\/lib\/private\/template.php(75): OCP\\Util::callRegister()\n#5 \/var\/www\/owncloud\/apps\/activity\/lib\/mailqueuehandler.php(250): OC_Template->__construct('activity', 'email.notificat...', '')\n#6 \/var\/www\/owncloud\/apps\/activity\/lib\/backgroundjob\/emailnotification.php(134): OCA\\Activity\\MailQueueHandler->sendEmailToUser('xxx', 'xxx@xxx...', 'de_DE', 'Europe\/Berlin', 1459502108)\n#7 \/var\/www\/owncloud\/apps\/activity\/lib\/backgroundjob\/emailnotification.php(94): OCA\\Activity\\BackgroundJob\\EmailNotification->runStep(500, 1459502108)\n#8 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/job.php(52): OCA\\Activity\\BackgroundJob\\EmailNotification->run(NULL)\n#9 \/var\/www\/owncloud\/lib\/private\/backgroundjob\/timedjob.php(53): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#10 \/var\/www\/owncloud\/cron.php(141): OC\\BackgroundJob\\TimedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#11 {main}","File":"\/var\/www\/owncloud\/lib\/private\/session\/memory.php","Line":105}`

Special configuration (external storage, external authentication, reverse proxy, server-side-encryption): Nothing

**Comment by LukasReschke** [comment]
Fixed in 9.0.1. Please try the RC1.
