### ISSUE TITLE
 Cannot Access caldav/carddav in Thunderbird

### ISSUE THREAD

**Issue by dom-madrid** [owncloud/core#23738]
This was already reported in version 8 under  #22794, closed for config error, but still occurs. I tested the installation with litmus, and all seems fine. Litmus results are included at the end.

Steps to reproduce

```
In TB 38.6 with Lightning 4.0.7 (with or without Sogo plugin) - Owncloud 9 on Ubuntu 14.04
Connect to OC calendar or OC contacts
Nothing is shown - only error in TB
```

Expected behaviour

Calendar/Contact info should appear and synchronize with OC
Actual behaviour

Nothing happens. Error in TB as follow:
Timestamp: 01/04/2016 17:38:37
Warning: There has been an error reading data for calendar: OC Dom. However, this error is believed to be minor, so the program will attempt to continue. Error code: DAV_NOT_DAV. Description: The resource at https://www.solipym.net/apps/cloud/remote.php/caldav/calendars/mipc/personal is either not a DAV collection or not available
Source File: file:///C:/Users/mipc/AppData/Roaming/Thunderbird/Profiles/0wg9ecr7.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCalendarManager.js
Line: 960

and

Timestamp: 01/04/2016 17:38:37
Warning: There has been an error reading data for calendar: OC Remote. However, this error is believed to be minor, so the program will attempt to continue. Error code: READ_FAILED. Description:
Source File: file:///C:/Users/mipc/AppData/Roaming/Thunderbird/Profiles/0wg9ecr7.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCalendarManager.js
Line: 960

Server configuration

Operating system:
Linux Ubuntu 14.04.04 LTS
Web server:
Apache/2.4.7 (Ubuntu)
Database:
mysql Ver 14.14 Distrib 5.5.47, for debian-linux-gnu (x86_64) using readline 6.3
PHP version:
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
ownCloud version: (see ownCloud admin page)
ownCloud 8.2.2 (stable)
Updated from an older ownCloud or fresh install:
Updated from previous version
Where did you install ownCloud from:
Originally downloaded source from owncloud.org, then internal update
Signing status (ownCloud 9.0 and above):

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

List of activated apps:

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

Enabled:
- activity: 2.2.1
- calendar: 1.0
- comments: 0.2
- contacts: 1.1.0.0
- dav: 0.1.5
- documents: 0.12.0
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
  Disabled:
- encryption
- external
- files_external
- ownnote
- user_external
- user_ldap

The content of config/config.php:

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

{
    "system": {
        "instanceid": "ocossoh158cw",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "www.solipym.net",
            "www.solipym.com"
        ],
        "datadirectory": "\/srv\/data\/ocData",
        "overwrite.cli.url": "https:\/\/www.solipym.net\/apps\/cloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\OC\Memcache\APCu",
        "memcache.locking": "\OC\Memcache\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "mail_domain": "solipym.com",
        "mail_from_address": "cloud",
        "maintenance": false
    }
}

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

Are you using external storage, if yes which one: local/smb/sftp/...
no
Are you using encryption: yes/no
no
Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
no
Client configuration

Browser:
Firefox 44.0.2
Thunderbird 38.6
Operating system:
Win7 x64
Logs
Web server error log

Insert your webserver log here

ownCloud log (data/owncloud.log)

Insert your ownCloud log here

Browser log / Thunderbird log

Insert your browser log here, this could for example include:

See TB error log at the beginning

Litmus testing:

litmus https://www.solipym.net/apps/cloud/remote.php/webdav username password
-> running `basic':
1. init.................. pass
2. begin................. pass
3. options............... WARNING: server does not claim Class 2 compliance
   ...................... pass (with 1 warning)
4. put_get............... pass
5. put_get_utf8_segment.. pass
6. put_no_parent......... pass
7. mkcol_over_plain...... pass
8. delete................ pass
9. delete_null........... pass
10. delete_fragment....... pass
    1. mkcol................. pass
    2. mkcol_again........... pass
    3. delete_coll........... pass
    4. mkcol_no_parent....... pass
    5. mkcol_with_body....... pass
    6. finish................ pass
       <- summary for `basic': of 16 tests run: 16 passed, 0 failed. 100.0%
       -> 1 warning was issued.
       -> running`copymove':
11. init.................. pass
12. begin................. pass
13. copy_init............. pass
14. copy_simple........... pass
15. copy_overwrite........ pass
16. copy_nodestcoll....... pass
17. copy_cleanup.......... pass
18. copy_coll............. pass
19. copy_shallow.......... pass
20. move.................. pass
    1. move_coll............. pass
    2. move_cleanup.......... pass
    3. finish................ pass
       <- summary for `copymove': of 13 tests run: 13 passed, 0 failed. 100.0%
       -> running`props':
21. init.................. pass
22. begin................. pass
23. propfind_invalid...... pass
24. propfind_invalid2..... pass
25. propfind_d0........... pass
26. propinit.............. pass
27. propset............... pass
28. propget............... pass
29. propextended.......... pass
30. propmove.............. pass
    1. propget............... pass
    2. propdeletes........... pass
    3. propget............... pass
    4. propreplace........... pass
    5. propget............... pass
    6. propnullns............ pass
    7. propget............... pass
    8. prophighunicode....... pass
    9. propget............... FAIL (Property {http://example.com/neon/litmus/}high-unicode had value , expected )
    10. propremoveset......... pass
    11. propget............... pass
    12. propsetremove......... pass
    13. propget............... pass
    14. propvalnspace......... pass
    15. propwformed........... pass
    16. propinit.............. pass
    17. propmanyns............ pass
    18. propget............... pass
    19. propcleanup........... pass
    20. finish................ pass
        <- summary for `props': of 30 tests run: 29 passed, 1 failed. 96.7%
        See debug.log for network/debug traces.

**Comment by LukasReschke** [comment]
Please retest with 9.0.1 RC1 or RC2

**Comment by LukasReschke** [comment]
cc @DeepDiver1975

**Comment by dom-madrid** [comment]
Just installed Owncloud 9.0.1 RC2 from zip after archiving version 9.0.0
Copied the config file over the new folder, got an update process and a few apps disabled.
Re-enabled the calendar and address book apps.
Same results in TB.
Although lost of the description is in french, the error returned seems to indicates, that although it sees a DAV, it does not recognize it as CALDAV...

Error message as follow:
Horodatage : 08/04/2016 15:39:07
Avertissement : Une erreur est survenue lors de la lecture de données de l'agenda : OC_Domi. Cependant, l'erreur est certainement mineure ; le programme va donc essayer de poursuivre. Code d'erreur : DAV_DAV_NOT_CALDAV. Description : La ressource sur « https://www.solipym.net/apps/cloud/remote.php/dav/ » est une collection DAV mais n'est pas un agenda CalDAV
Fichier Source : file:///C:/Users/JCC/AppData/Roaming/Thunderbird/Profiles/k0f0vj26.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCalendarManager.js
Ligne : 960

and

Horodatage : 08/04/2016 15:39:07
Avertissement : Une erreur est survenue lors de la lecture de données de l'agenda : OC_Domi. Cependant, l'erreur est certainement mineure ; le programme va donc essayer de poursuivre. Code d'erreur : READ_FAILED. Description : 
Fichier Source : file:///C:/Users/JCC/AppData/Roaming/Thunderbird/Profiles/k0f0vj26.default/extensions/%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D/calendar-js/calCalendarManager.js
Ligne : 960

Litmus testing is as before.

**Comment by PVince81** [comment]
@georgehrke

**Comment by georgehrke** [comment]
@dom-madrid Can you still reproduce this with 9.0.3?

**Comment by dom-madrid** [comment]
Just updated to 9.0.3... No changes from the TB side. Same error messages. Only change since last testing TB upgraded to version 45.2.0 and Lightning to version 4.7.2

**Comment by kwoxer** [comment]
I have **9.0.2** and it works great. I'm using latest **Sogo** Addon and latest **Thunderbird** and **Windows 10**. I did it this way: http://www.kwoxer.de/2016/05/05/owncloud-mit-thunderbird-und-android-verbinden-komplettanleitung/#Thunderbird_Calendar_Connect

**Comment by dom-madrid** [comment]
Great catch. Although it was in german, I tried to follow the information provided.
By changing the URL from the 'Primary Caldav Address' to the specific address of the Calendar, it started to work.
I do not know if it is a user mistake or a bug, but I am happy it works.
If it is a user mistake (mine), maybe the use of the 'Primary Caldav Address' should be clarified to avoid further problems to others. If the address is wrong, what is it used for ? And if it should work, then it should be fixed.
Thanks

**Comment by kwoxer** [comment]
Let me know if it's working. Otherwise I'll investigate on this :) It should be just an URL issue I assume.

**Comment by dom-madrid** [comment]
Hi,
I guess you missed it in my answer from yesterday. It is working now with those changes. But the different URL are definitively misleading (and one is clearly not working).

**Comment by PVince81** [comment]
@DeepDiver1975 what do you think ?

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
