### ISSUE TITLE
Sabredav Unsupported Media Type","Exception":" in Calendar

### ISSUE THREAD

**Issue by Maulwurf16** [owncloud/core#23732]
One of my users shared a calendar with read/write Access with another. They synced the calendars with several mobile devices using several dav syncing Tools.

Suddenly the ownCloud calendar broke---BIG Times. All users with Access to the shared calendar can't load any of their calendars. Instead, the log throws this error

Problem is, I really cannot reproduce this.
However... If someone knows how to fix  this error, I'd be soooo glad :)

### Steps to reproduce
1. create shared calendar?
2. sync several times... neither I can reproduce this

### Expected behaviour
Calendars should load

### Actual behaviour
they don't

**ownCloud version:** 9.0
**Updated from an older ownCloud or fresh install:** Updated

#### ownCloud log (data/owncloud.log)
```
Exception: {"Message":"HTTP\/1.1 415 Unsupported Media Type","Exception":"Sabre\\DAV\\Exception\\ReportNotSupported","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/apps\/dav\/lib\/server.php(137): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v2\/remote.php(29): OCA\\DAV\\Server->exec()\n#6 \/var\/www\/owncloud\/remote.php(138): require_once('\/var\/www\/ownclo...')\n#7 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","Line":721,"User":"Sibel"}
```

**Comment by DeepDiver1975** [comment]
Would be good to know the client and best the request which is causing this trouble

**Comment by Maulwurf16** [comment]
Well now every (Webpage) call results in this error and the calendars aren't shown. So something must be in the mysql database.
I am now not really able to distinguish the Action which caused this error. However, there was a Windows phone trying to Setup caldav by using a fake apple id with the ownCloud credentials.

**Comment by Maulwurf16** [comment]
Ok BIG UPDATE here on my side.
We all switched to Microsoft Edge here. When Viewing the OwnCloud Calender with Edge, the above Error is given. However... switching back to Chrome and opening the calendar gives no error whatsoever and everything works like a charm. :O

**Comment by MorrisJobke** [comment]
According to https://github.com/owncloud/calendar/issues/309#issuecomment-194822622 Edge doesn't seem to be supported :(

This is also the core bug tracker. For issues with the calendar app (UI part) please open a ticket in the calendar bug tracker.

Thanks
