### ISSUE TITLE
Fake lock causes WebDAV connectivty problem - A device attached to the system is not functioning

### ISSUE THREAD

**Issue by gig13** [owncloud/core#23733]
### Steps to reproduce
1. Apply the patch for https://github.com/owncloud/core/pull/23103
2. Attempt to access ownCloud via the WebDAV mount
3. Try to login several times, receive an error message
### Expected behavior

The user should be able to connect via WebDAV files just as if they were using a standard Windows mount.
### Actual behavior

The user is prompted to authenticate when trying to open the files through WebDAV, and eventually can't login.
### Server configuration

**Operating system**: RHEL

**Web server:** Apache

**Database:** MySQL

**PHP version:** to obtain

**ownCloud version:** 8.2.1

**Updated from an older ownCloud or fresh install:** Updated

**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** AD
### Client configuration

**Browser:** IE

**Operating system:** Windows
#### ownCloud log (data/owncloud.log)

Attached on s3 also a sceen shot of the error
https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fcore%2F23733

@MorrisJobke 
Also reference https://github.com/owncloud/core/issues/22596

**Comment by gig13** [comment]
Check the logs for user ckerr between 8am EST - 9am EST.

**Comment by gig13** [comment]
@nickvergessen @MorrisJobke Any chance o look at the logs? Any additional information needed from the users?

**Comment by nickvergessen** [comment]
I see a lot of 
```json
{"reqId":"...","remoteAddr":"...","app":"PHP","message":"Class 'OC\\Connector\\Sabre\\ServerFactory' not found at ....\/htdocs\/apps\/files\/appinfo\/remote.php#35","level":3,"time":"2016-04-01T12:55:45+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/"}
```

Which seems like not all files are uploaded?

Other then that I only see `HTTP/1.1 401 No basic authentication headers were found`

**Comment by PVince81** [comment]
The patch was likely design to be applied on top of 8.2.3.
Maybe it doesn't work to patch 8.2.1 and would require more ?

**Comment by PVince81** [comment]
@DeepDiver1975 @felixboehm close ? Best is to ask for retry on 8.2.8 or later.

**Comment by PVince81** [comment]
@michaelstingl @cdamken

**Comment by michaelstingl** [comment]
Here is the linked screenshot:
![owncloud-webdav-issue](https://cloud.githubusercontent.com/assets/214010/22382436/f79874a4-e4c5-11e6-817b-19fb6df93ac2.png)

@cdamken Is this the usual issue users have with mounting oC WebDAV in Windows?
