### ISSUE TITLE
Sabre\\DAV\\Exception\\BadRequest

### ISSUE THREAD

**Issue by Tealk144** [owncloud/core#23730]
### Steps to reproduce
Upload files form my NAS with WebDAV

### Server configuration
**Operating system:** Debian 8.0 jessie minimal
**Web server:** Apache/2.4.10 (Debian)
**Database:** mysqlnd 5.0.11
**PHP version:** 5.6.17-0+deb8u1
**ownCloud version:** 9.0.0 (stable)
**Updated from an older ownCloud or fresh install:** No
**ownCloud log (data/owncloud.log):**
`Exception: {"Message":"HTTP\/1.1 400 expected filesize 1445 got 0","Exception":"Sabre\\DAV\\Exception\\BadRequest","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/dav\/lib\/connector\/sabre\/directory.php(134): OCA\\DAV\\Connector\\Sabre\\File->put(Resource id #42)\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1036): OCA\\DAV\\Connector\\Sabre\\Directory->createFile('157 (11 NSY) Di...', Resource id #42)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(525): Sabre\\DAV\\Server->createFile('B\\xC3\\xBCcher\/Star Wa...', Resource id #42, NULL)\n#3 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/owncloud\/remote.php(138): require_once('\/var\/www\/ownclo...')\n#9 {main}","File":"\/var\/www\/owncloud\/apps\/dav\/lib\/connector\/sabre\/file.php","Line":149,"User":"Tealk"}`

**Special configuration (external storage, external authentication, reverse proxy, server-side-encryption):** Nothing

**Comment by LukasReschke** [comment]
Please provide more information such as which NAS etc.

**Comment by Tealk144** [comment]
Synology DS213+ with DSM 6.0-7321 i use the Software CloudSync

**Comment by RealRancor** [comment]
@Tealk144 Did you had a look at https://forum.owncloud.org/viewtopic.php?f=17&t=32517

Most likely an environmental issue.
