### ISSUE TITLE
Install 8.1 daily: install problem with database (socket-path needed)

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#23744]
### Steps to reproduce
1. Use ubuntu14.04 system + apache + mod_php + mysql (via socket)
2. take 8.1 daily: https://download.owncloud.org/community/daily/owncloud-daily-stable8.1.tar.bz2
3. Try to install with mysql database, hostname: localhost (via web-interface)

### Expected behaviour
Install owncloud

### Actual behaviour
An error is shown that it cannot connect to mysql. I double checked the password, tried via root-account and with an already created user.

I get this error in the log:

````
{"reqId":"bJFzNB6dsjLsKhNs+LJR","remoteAddr":"my-ip","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/oc1\/lib\/private\/appframework\/http\/request.php#700","level":3,"time":"2016-04-01T20:39:51+00:00"}
````

I tried via the occ-command:
`sudo -u www-data php occ maintenance:install --database="mysql" --database-user="octest1" --database-pass="xxx" --database-name="octest1" --admin-pass="xxx" --database-host="localhost"`

I get this error in the terminal:
````
ownCloud is not installed - only a limited number of commands are available
MySQL/MariaDB username and/or password not valid
 -> You need to enter either an existing account or the administrator.
````
Again I can take the root account, same story. But if I add the socket-path, it works:
`sudo -u www-data php occ maintenance:install --database="mysql" --database-user="octest1" --database-pass="xxx" --database-name="octest1" --admin-pass="xxx" --database-host="localhost:/var/run/mysqld/mysqld.sock"`

Could be related to: https://github.com/owncloud/core/issues/16685 and https://github.com/owncloud/core/issues/15992
This fix (https://github.com/owncloud/core/pull/17078) seems not to be in the code, because I still find this line: https://github.com/owncloud/core/pull/17078/files#diff-4403c13f29a8b6e4b441e74ed7248123L661

**Owncloud version**: ownCloud 8.1.6 (daily) Build:2016-04-01T04:01:45+00:00 36a2d1a1f891a6da66bc1f500a7ceb871e759bd9

**Comment by PVince81** [comment]
Looks like an old issue, likely already fixed.

If it still occurs, please reopen.
