### ISSUE TITLE
[OC 9.0.0] Changing upload size does not work

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/core#23748]
I changed the upload size from 32 MB to 100 MB in the admin panel, and in my php.ini, and restarted my Apache server. I double-checked that the new value is indeed active via web applications e.g. via phpinfo().

However, when changing the value in OC Admin panel, and logout/login to OC, the new value is not taken into account. The old value is not changed.

Bug ? Feature ?

**Comment by RealRancor** [comment]
Running PHP7 (might be useful to provide such infos instead of deleting the issue template)? https://github.com/owncloud/core/issues/23061

**Comment by Wikinaut** [comment]
Yes! Running PHP 7.0.4

**Comment by RealRancor** [comment]
@Wikinaut Just add  this to your .htaccess: https://github.com/owncloud/core/blob/ee840171929edbeca8eafb32515817406da46051/.htaccess#L40-L50 and wait for oC 9.0.1 including this.

**Comment by Wikinaut** [comment]
problem was on > my < side. In ``php.ini``` I forgot to also change ``post_max_size = 100M`` !

Solved.

**Comment by Wikinaut** [comment]
@RealRancor I compile PHP from the sources, so I don't have the mod_php files(s).

> problem was on > my < side. In php.ini I forgot to also change post_max_size = 100M !
