### ISSUE TITLE
Namespace of share-permission webdav property should not be the ownCloud namespace

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#23741]
With https://github.com/owncloud/core/pull/22834 just in we add a new webdav property `oc:share-permissions`.

However, @LukasReschke pointed out that we may want to use a more generic namespace to make interaction with other projects easier. We then also need to document in that namepscae what the permissions means.

FYI @karlitschek

**Comment by karlitschek** [comment]
Agreed.
OCM, OCS or FEDERATION would all work for me.



Frank

**Comment by rullzer** [comment]
@karlitschek do we have urls for those namespaces? Since we can all them whatever we want they are just aliases to a URL...

**Comment by karlitschek** [comment]
@DeepDiver1975 What do you think?

**Comment by rullzer** [comment]
@DeepDiver1975 @karlitschek any news? Would be good to have the proper namespace before our clients start use this property.

**Comment by karlitschek** [comment]
@DeepDiver1975 ping

**Comment by DeepDiver1975** [comment]
All the federation specs are officially hosted at http://www.open-collaboration-services.org/ocs/ocs2-draft1.html - right?

So let's use this as namespace then: http://open-collaboration-services.org/ocs

Or we follow iana: http://www.iana.org/assignments/xml-registry/xml-registry.xhtml
and use urn:ietf:params:xml:ns:ocs - in accordance with urn:ietf:params:xml:ns:caldav and urn:ietf:params:xml:ns:carddav

**Comment by rullzer** [comment]
I think `http://open-collaboration-services.org/ocs` is easier. Iana requires more work to get the namespace in there I believe.
