### ISSUE TITLE
Update Problem from Version 7.0.4

### ISSUE THREAD

**Issue by Udo017** [owncloud/core#23755]
I check the update page last time unregulary and short. So I see "Up to date" and belive all was fine. Today I looked carfully and I see "Up to date. Last check 31.01.2030", long in the future!

To correct the date I put the line
\OC_Appconfig::setValue('core', 'lastupdatedat', time() - 3600);
in the ./apps/updater/update.php script and updated the page.
Now the date is in the past and the update to 8.2.1 is offer.
I start the update.
I works until the database update. I get the error:
Updating ownCloud to version 8.2.1, this may take a while.

Preparing update Set log level to debug - current level: "Warning" Turned on maintenance mode

Exception: Updates between multiple major versions and downgrades are unsupported.

The update was unsuccessful. Please report this issue to the ownCloud community.

So I do this : -)

I hope there is a way to get the owncloud work again.

### Expected behaviour
The update should work without errors.

### Actual behaviour
The error above is shown.

### Server configuration
**Operating system**:
Kernel 3.16.0-4-amd64
Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux

**WebServer version:
Apache/2.4.10 (Debian)
Server built:   Nov 28 2015 14:05:48 server:

**Database:
postgres 9.4

**PHP version:**
PHP 5.6.17-0+deb8u1 (cli) (built: Jan 13 2016 09:10:12) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

**Updated from an older ownCloud or fresh install:**
from an older (7.0.4)

**Where did you install ownCloud from:**
from your internet page

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
ownCloud will be updated to version 8.2.1
These apps will be updated:

    Files (files)
    Share Files (files_sharing)
    Deleted files (files_trashbin)
    Versions (files_versions)
    Updater (updater)

Please make sure that the database, the config folder and the data folder have been backed up before proceeding.
To avoid timeouts with larger installations, you can instead run the following command from your installation directory:

./occ upgrade

**List of activated apps:*
ownCloud or one of the apps require upgrade - only a limited number of commands are available
Enabled:
  - calendar: 0.6.4
  - contacts: 0.3.0.18
  - files: 1.1.9
  - files_antivirus: 0.4.2
  - files_sharing: 0.5.3
  - files_trashbin: 0.6.2
  - files_versions: 1.0.5
  - updater: 0.4
Disabled:
  - activity
  - admin_dependencies_chk
  - bookmarks
  - documents
  - external
  - files_encryption
  - files_external
  - files_pdfviewer
  - files_texteditor
  - files_videoviewer
  - firstrunwizard
  - gallery
  - search_lucene
  - templateeditor
  - user_external
  - user_ldap
  - user_webdavauth

**The content of config/config.php:**
ownCloud or one of the apps require upgrade - only a limited number of commands are available
{
    "system": {
        "instanceid": "oc1503578e5c",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.zuhause.de"
        ],
        "datadirectory": "\/data\/apache\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.domane.de",
        "dbtype": "pgsql",
        "version": "7.0.4.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "localhost",
        "mail_smtpport": "25",
        "mail_from_address": "owncloud",
        "mail_domain": "domane.de",
        "loglevel": "2"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:**
Mozilla FireFox 45

**Operating system:**
Linux Mint Debian Edition

#### Web server error log
Nothing from owncloud

#### ownCloud log (data/owncloud.log)
{"app":"PHP","message":"Array to string conversion at \/data\/apache\/owncloud\/lib\/private\/l10n\/string.php#57","level":3,"time":"2016-04-02T21:04:31+00:00"}
{"app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-04-02T21:06:32+00:00"}
{"app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-04-02T21:07:27+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166055","level":4,"time":"2016-04-02T21:08:25+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166045","level":4,"time":"2016-04-02T21:08:28+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166044","level":4,"time":"2016-04-02T21:08:32+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166050","level":4,"time":"2016-04-02T21:08:35+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166056","level":4,"time":"2016-04-02T21:08:37+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166053","level":4,"time":"2016-04-02T21:08:40+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166057","level":4,"time":"2016-04-02T21:08:42+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166043","level":4,"time":"2016-04-02T21:08:45+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166059","level":4,"time":"2016-04-02T21:08:48+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166054","level":4,"time":"2016-04-02T21:08:51+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166055","level":4,"time":"2016-04-02T21:08:53+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166052","level":4,"time":"2016-04-02T21:08:53+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166045","level":4,"time":"2016-04-02T21:08:56+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166038","level":4,"time":"2016-04-02T21:08:56+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166044","level":4,"time":"2016-04-02T21:08:59+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166051","level":4,"time":"2016-04-02T21:08:59+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166050","level":4,"time":"2016-04-02T21:09:01+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166049","level":4,"time":"2016-04-02T21:09:02+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166056","level":4,"time":"2016-04-02T21:09:05+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166053","level":4,"time":"2016-04-02T21:09:07+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166057","level":4,"time":"2016-04-02T21:09:10+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166043","level":4,"time":"2016-04-02T21:09:13+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166059","level":4,"time":"2016-04-02T21:09:15+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166054","level":4,"time":"2016-04-02T21:09:18+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166052","level":4,"time":"2016-04-02T21:09:21+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166038","level":4,"time":"2016-04-02T21:09:24+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166051","level":4,"time":"2016-04-02T21:09:27+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166049","level":4,"time":"2016-04-02T21:09:30+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166055","level":4,"time":"2016-04-02T21:09:39+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166045","level":4,"time":"2016-04-02T21:09:42+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166044","level":4,"time":"2016-04-02T21:09:45+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166050","level":4,"time":"2016-04-02T21:09:47+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166056","level":4,"time":"2016-04-02T21:09:50+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166053","level":4,"time":"2016-04-02T21:09:53+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166057","level":4,"time":"2016-04-02T21:09:55+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166043","level":4,"time":"2016-04-02T21:09:58+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166059","level":4,"time":"2016-04-02T21:10:01+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166054","level":4,"time":"2016-04-02T21:10:04+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166052","level":4,"time":"2016-04-02T21:10:07+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166038","level":4,"time":"2016-04-02T21:10:10+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166051","level":4,"time":"2016-04-02T21:10:13+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166049","level":4,"time":"2016-04-02T21:10:16+00:00"}
{"app":"PHP","message":"Array to string conversion at \/data\/apache\/owncloud\/lib\/private\/l10n\/string.php#57","level":3,"time":"2016-04-02T21:13:01+00:00"}
{"app":"PHP","message":"Array to string conversion at \/data\/apache\/owncloud\/lib\/private\/l10n\/string.php#57","level":3,"time":"2016-04-02T21:13:35+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:23:44+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:24:16+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:24:48+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:25:20+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:25:52+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:26:24+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:26:56+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:27:28+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:28:00+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:28:32+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:29:04+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:29:36+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:30:08+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:30:40+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:31:12+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:31:44+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:32:16+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:32:48+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:33:20+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:33:52+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:34:24+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:34:56+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\ServiceUnavailable: ","level":4,"time":"2016-04-02T21:35:28+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166055","level":4,"time":"2016-04-02T21:36:05+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166045","level":4,"time":"2016-04-02T21:36:09+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166044","level":4,"time":"2016-04-02T21:36:12+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166050","level":4,"time":"2016-04-02T21:36:14+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166056","level":4,"time":"2016-04-02T21:36:17+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166053","level":4,"time":"2016-04-02T21:36:20+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166057","level":4,"time":"2016-04-02T21:36:23+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166043","level":4,"time":"2016-04-02T21:36:26+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166059","level":4,"time":"2016-04-02T21:36:28+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166054","level":4,"time":"2016-04-02T21:36:31+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166052","level":4,"time":"2016-04-02T21:36:34+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166038","level":4,"time":"2016-04-02T21:36:37+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166051","level":4,"time":"2016-04-02T21:36:40+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166049","level":4,"time":"2016-04-02T21:36:43+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166055","level":4,"time":"2016-04-02T21:36:52+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166045","level":4,"time":"2016-04-02T21:36:54+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166044","level":4,"time":"2016-04-02T21:36:57+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166050","level":4,"time":"2016-04-02T21:37:00+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166056","level":4,"time":"2016-04-02T21:37:03+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166053","level":4,"time":"2016-04-02T21:37:06+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166057","level":4,"time":"2016-04-02T21:37:09+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166043","level":4,"time":"2016-04-02T21:37:12+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166059","level":4,"time":"2016-04-02T21:37:15+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166054","level":4,"time":"2016-04-02T21:37:18+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166052","level":4,"time":"2016-04-02T21:37:21+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166038","level":4,"time":"2016-04-02T21:37:23+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166051","level":4,"time":"2016-04-02T21:37:26+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166049","level":4,"time":"2016-04-02T21:37:29+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166055","level":4,"time":"2016-04-02T21:38:23+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166045","level":4,"time":"2016-04-02T21:38:26+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166044","level":4,"time":"2016-04-02T21:38:29+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166050","level":4,"time":"2016-04-02T21:38:31+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166056","level":4,"time":"2016-04-02T21:38:34+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166053","level":4,"time":"2016-04-02T21:38:37+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166057","level":4,"time":"2016-04-02T21:38:40+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166043","level":4,"time":"2016-04-02T21:38:42+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166059","level":4,"time":"2016-04-02T21:38:45+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166054","level":4,"time":"2016-04-02T21:38:48+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166052","level":4,"time":"2016-04-02T21:38:51+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166038","level":4,"time":"2016-04-02T21:38:54+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166051","level":4,"time":"2016-04-02T21:38:57+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166049","level":4,"time":"2016-04-02T21:39:00+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166055","level":4,"time":"2016-04-02T21:39:08+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166045","level":4,"time":"2016-04-02T21:39:11+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166044","level":4,"time":"2016-04-02T21:39:14+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166050","level":4,"time":"2016-04-02T21:39:17+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166056","level":4,"time":"2016-04-02T21:39:20+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166053","level":4,"time":"2016-04-02T21:39:22+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166057","level":4,"time":"2016-04-02T21:39:25+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166043","level":4,"time":"2016-04-02T21:39:29+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166059","level":4,"time":"2016-04-02T21:39:31+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166054","level":4,"time":"2016-04-02T21:39:34+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166052","level":4,"time":"2016-04-02T21:39:37+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166038","level":4,"time":"2016-04-02T21:39:39+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166051","level":4,"time":"2016-04-02T21:39:42+00:00"}
{"app":"core","message":"Invalid OCS content returned for app 166049","level":4,"time":"2016-04-02T21:39:45+00:00"}
{"app":"PHP","message":"Array to string conversion at \/data\/apache\/owncloud\/lib\/private\/l10n\/string.php#57","level":3,"time":"2016-04-02T21:40:04+00:00"}
{"app":"PHP","message":"Array to string conversion at \/data\/apache\/owncloud\/lib\/private\/l10n\/string.php#57","level":3,"time":"2016-04-02T21:49:49+00:00"}
{"app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-04-02T21:53:53+00:00"}
{"app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-04-02T21:54:03+00:00"}
{"reqId":"O+6Hf2Lq+sfJj9wn5D2x","remoteAddr":"192.168.2.65","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/app.php(118): OC_App::loadApp('files')\\n#1 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/util.php(130): OC_App::loadApps(Array)\\n#2 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/base.php(850): OC_Util::setupFS()\\n#3 \\\/data\\\/apache\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/app.php\",\"Line\":139}","level":3,"time":"2016-04-02T21:54:11+00:00"}
{"reqId":"fLVHCzxuEm5By50ZlRAh","remoteAddr":"192.168.2.65","app":"core","message":"starting upgrade from 7.0.4.2 to 8.2.1.4","level":0,"time":"2016-04-02T22:06:10+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=KwwCGlw9FxMAJxh%2BR0BXJhkrI3seJxoGGxVaOCsG%3ADcTy7VduEQiIwvgq6Hh55LbquM5tyC"}
{"reqId":"fLVHCzxuEm5By50ZlRAh","remoteAddr":"192.168.2.65","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Updates between multiple major versions and downgrades are unsupported.\",\"Code\":0,\"Trace\":\"#0 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.1.4', '7.0.4.2')\\n#1 \\\/data\\\/apache\\\/owncloud\\\/core\\\/ajax\\\/update.php(111): OC\\\\Updater->upgrade()\\n#2 {main}\",\"File\":\"\\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/updater.php\",\"Line\":285}","level":3,"time":"2016-04-02T22:06:10+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=KwwCGlw9FxMAJxh%2BR0BXJhkrI3seJxoGGxVaOCsG%3ADcTy7VduEQiIwvgq6Hh55LbquM5tyC"}
{"reqId":"r+F6+b431UUNkoMc+cn1","remoteAddr":"192.168.2.65","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/app.php(118): OC_App::loadApp('files')\\n#1 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/util.php(130): OC_App::loadApps(Array)\\n#2 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/base.php(850): OC_Util::setupFS()\\n#3 \\\/data\\\/apache\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/app.php\",\"Line\":139}","level":3,"time":"2016-04-02T22:07:32+00:00"}
{"reqId":"mbbks6izOD6ZnwbrkOZ4","remoteAddr":"192.168.2.65","app":"core","message":"starting upgrade from 7.0.4.2 to 8.2.1.4","level":0,"time":"2016-04-02T22:07:54+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=KRUOTAg6ATYNNQBWZ3JiYV4JDgV7OEtcFxUFIRYV%3AFzX%2FcQrPHCqaWDR6qjEKPS3%2ByMjmDP"}
{"reqId":"mbbks6izOD6ZnwbrkOZ4","remoteAddr":"192.168.2.65","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Updates between multiple major versions and downgrades are unsupported.\",\"Code\":0,\"Trace\":\"#0 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.1.4', '7.0.4.2')\\n#1 \\\/data\\\/apache\\\/owncloud\\\/core\\\/ajax\\\/update.php(111): OC\\\\Updater->upgrade()\\n#2 {main}\",\"File\":\"\\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/updater.php\",\"Line\":285}","level":3,"time":"2016-04-02T22:07:54+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=KRUOTAg6ATYNNQBWZ3JiYV4JDgV7OEtcFxUFIRYV%3AFzX%2FcQrPHCqaWDR6qjEKPS3%2ByMjmDP"}
{"reqId":"2ZUPSN7q\/\/SN\/YObpcgq","remoteAddr":"192.168.2.65","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/app.php(118): OC_App::loadApp('files')\\n#1 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/util.php(130): OC_App::loadApps(Array)\\n#2 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/base.php(850): OC_Util::setupFS()\\n#3 \\\/data\\\/apache\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/app.php\",\"Line\":139}","level":3,"time":"2016-04-02T22:08:57+00:00"}
{"reqId":"\/urKwXeSSHHHsQy5541l","remoteAddr":"192.168.2.65","app":"core","message":"starting upgrade from 7.0.4.2 to 8.2.1.4","level":0,"time":"2016-04-02T22:09:11+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=BV8zFFpeJABxAituWmEFIxtIen0dOgo9DGgsIT13%3Aj0ew15Wf4tZYjW5t4%2B136QrJb0Cmo2"}
{"reqId":"\/urKwXeSSHHHsQy5541l","remoteAddr":"192.168.2.65","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Updates between multiple major versions and downgrades are unsupported.\",\"Code\":0,\"Trace\":\"#0 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/updater.php(205): OC\\\\Updater->doUpgrade('8.2.1.4', '7.0.4.2')\\n#1 \\\/data\\\/apache\\\/owncloud\\\/core\\\/ajax\\\/update.php(111): OC\\\\Updater->upgrade()\\n#2 {main}\",\"File\":\"\\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/updater.php\",\"Line\":285}","level":3,"time":"2016-04-02T22:09:11+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=BV8zFFpeJABxAituWmEFIxtIen0dOgo9DGgsIT13%3Aj0ew15Wf4tZYjW5t4%2B136QrJb0Cmo2"}
{"reqId":"nEnqncmJ2KDPm+qL12et","remoteAddr":"192.168.2.65","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/app.php(118): OC_App::loadApp('files')\\n#1 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/util.php(130): OC_App::loadApps(Array)\\n#2 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/base.php(850): OC_Util::setupFS()\\n#3 \\\/data\\\/apache\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/app.php\",\"Line\":139}","level":3,"time":"2016-04-02T22:56:42+00:00"}
{"reqId":"lKukTC5G7cyWWwRZtno2","remoteAddr":"192.168.2.65","app":"index","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/app.php(118): OC_App::loadApp('files')\\n#1 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/util.php(130): OC_App::loadApps(Array)\\n#2 \\\/data\\\/apache\\\/owncloud\\\/lib\\\/base.php(850): OC_Util::setupFS()\\n#3 \\\/data\\\/apache\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/data\\\/apache\\\/owncloud\\\/lib\\\/private\\\/app.php\",\"Line\":139}","level":3,"time":"2016-04-02T23:01:34+00:00"}

**Comment by RealRancor** [comment]
@Udo017 Please close here and follow the instructions at this FAQ which describes how to do a correct upgrade:

https://forum.owncloud.org/viewtopic.php?f=17&t=32087

**Comment by Udo017** [comment]
Ok, Thank you.
