### ISSUE TITLE
OC9 Can't edit *.odt documents from files app after updating from 8.2 to 9.0

### ISSUE THREAD

**Issue by davodego** [owncloud/core#23753]
### Steps to reproduce
1. Got to files app and choose a odt file.
2. Click on the filename.
3. Download is started.

### Expected behaviour
On Click OC should go to documents app and show the contet of the odt file.

### Actual behaviour
Download option is started.

### Server configuration
**Operating system**: Ubuntu 14.04 LTS

**Web server:** Apache 2.4.7

**Database:** mysql 

**PHP version:** php 2.5.0

**ownCloud version:** (see ownCloud admin page): 9.0

**Updated from an older ownCloud or fresh install:** updatet from 8.2

**Where did you install ownCloud from:** owncloud download page with tar.bz2 package

**Signing status (ownCloud 9.0 and above):** 9.0.0.19

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
Enabled:
  - comments: 0.2
  - dav: 0.1.5
  - direct_menu: true
  - documents: true
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_antivirus: true
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_reader: true
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - galleryplus: true
  - html5_videoplayer: 1.0
  - imprint: 0.2.5
  - notes: 2.0.1
  - notifications: 0.2.3
  - ojsxc: true
  - provisioning_api: 0.4.1
  - rainloop: 4.12
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - activity
  - encryption
  - external
  - gallery
  - ownnote
  - user_external
  - user_ldap
 
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

{
    "system": {
        "instanceid": "xxx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "dienste.srvdg.de"
        ],
        "datadirectory": "\/var\/daten\/owncloud",
        "overwrite.cli.url": "https:\/\/dienste.srvdg.de\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",
        "mail_domain": "srvdg.local",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "localhost",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "mail_smtpsecure": "tls",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir "
    },
    "apps": {
        "activity": {
            "enabled": "no",
            "installed_version": "2.1.3",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "4"
        },
        "bookmarks": {
            "enabled": "no",
            "installed_version": "0.6",
            "ocsid": "168710",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "contactsplus": {
            "enabled": "no",
            "installed_version": "1.0.9",
            "ocsid": "171237",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1457717752.833",
            "lastcron": "1459619128",
            "lastupdateResult": "{\"version\":{},\"versionstring\":{},\"url\":{},\"web\":{}}",
            "lastupdatedat": "1459618312",
            "oc.integritycheck.checker": "[]",
            "public_documents": "documents\/public.php",
            "public_file": "shorty\/Array",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_contactsplus": "contactsplus\/appinfo\/remote.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes"
        },
        "daniel": {
            "documents": "save_path"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "types": "filesystem"
        },
        "direct_menu": {
            "enabled": "yes",
            "installed_version": "0",
            "ocsid": "169148",
            "types": ""
        },
        "documents": {
            "converter": "local",
            "enabled": "yes",
            "installed_version": "0",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.0.4",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.4.4",
            "types": "filesystem"
        },
        "files_antivirus": {
            "av_chunk_size": "1024",
            "av_cmd_options": "",
            "av_host": "",
            "av_infected_action": "only_log",
            "av_mode": "socket",
            "av_path": "\/usr\/bin\/clamscan",
            "av_port": "0",
            "av_socket": "\/var\/run\/clamav\/clamd.ctl",
            "enabled": "yes",
            "installed_version": "0",
            "ocsid": "157439",
            "signed": "true",
            "types": "filesystem"
        },
        "files_embeddedvideo": {
            "enabled": "no",
            "installed_version": "0.0.7",
            "ocsid": "169002",
            "types": ""
        },
        "files_epubviewer": {
            "enabled": "no",
            "installed_version": "7.0.5",
            "types": ""
        },
        "files_external": {
            "\/Filme": "1458384372",
            "\/Fotos": "1458384376",
            "\/Musik": "1458384374",
            "allow_user_mounting": "yes",
            "enabled": "yes",
            "installed_version": "0.5.2",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "dav,owncloud,sftp,\\OC\\Files\\Storage\\SFTP_Key"
        },
        "files_hubic": {
            "enabled": "no",
            "installed_version": "0.0.1",
            "types": "filesystem"
        },
        "files_mv": {
            "enabled": "no",
            "installed_version": "0.8.2",
            "ocsid": "150271",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8",
            "ocsid": "166049",
            "types": ""
        },
        "files_reader": {
            "enabled": "yes",
            "installed_version": "0",
            "ocsid": "167127",
            "types": ""
        },
        "files_sharing": {
            "5": "1458108176.4753",
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_videojs-sublime": {
            "enabled": "no",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "files_videoviewerplus": {
            "enabled": "no",
            "installed_version": "0.0.1",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "14.2.0",
            "types": ""
        },
        "galleryplus": {
            "enabled": "yes",
            "installed_version": "0",
            "ocsid": "169116",
            "types": ""
        },
        "hls_streamplayer": {
            "enabled": "no",
            "installed_version": "0.1",
            "ocsid": "174642",
            "types": ""
        },
        "html5_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.0",
            "ocsid": "173950",
            "types": ""
        },
        "imprint": {
            "content": "Daniel von der G\u00f6nna\nObere Arnst\u00e4dter Stra\u00dfe 8\n99448 Kranichfeld\n\nmailto:mail@irgendwieanders.eu\nxmpp:daniel@jabber.srvdg.de\npgp key:http:\/\/srvdg.de\/url\/key",
            "enabled": "yes",
            "installed_version": "0.2.5",
            "ocsid": "153220",
            "position-guest": "footer-right",
            "position-login": "footer-right",
            "position-user": "header-right",
            "types": ""
        },
        "news": {
            "enabled": "no",
            "installed_version": "7.1.2",
            "ocsid": "168040",
            "types": ""
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.2.3",
            "types": "logging"
        },
        "octv": {
            "enabled": "no",
            "installed_version": "0.0.1",
            "types": ""
        },
        "ojsxc": {
            "boshUrl": "\/http-bind\/",
            "enabled": "yes",
            "iceCredential": "",
            "iceSecret": "",
            "iceTtl": "",
            "iceUrl": "",
            "iceUsername": "",
            "installed_version": "0",
            "ocsid": "162257",
            "serverType": "external",
            "types": "prelogin",
            "xmppDomain": "jabber.srvdg.de",
            "xmppOverwrite": "true",
            "xmppResource": "owncloud",
            "xmppStartMinimized": "false"
        },
        "ownnote": {
            "enabled": "no",
            "installed_version": "0",
            "ocsid": "168512",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction"
        },
        "rainloop": {
            "enabled": "yes",
            "installed_version": "4.12",
            "rainloop-autologin": "1",
            "types": ""
        },
        "shorten": {
            "enabled": "no",
            "host": "https:\/\/dienste.srvdg.de\/url",
            "installed_version": "0.0.15",
            "ocsid": "168591",
            "types": "filesystem"
        },
        "shorty": {
            "enabled": "no",
            "installed_version": "0.5.0",
            "types": "internet,bookmark"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        }
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
Error 	files_antivirus 	Not Checked. No matching rules. Please check antivirus rules. File: 14316Account: Path: daniel/files/Documents/Privat/Handbücher/Samsung BD-E6300S-EN-GER-0607.pdf 	2016-04-02T17:45:27+00:00
Error 	PHP 	fwrite(): send of 4 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner/external.php#51 	2016-04-02T17:45:27+00:00
Error 	PHP 	fwrite(): send of 905 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner.php#68 	2016-04-02T17:45:27+00:00
Error	PHP	fwrite(): send of 905 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner.php#68	2016-04-02T17:45:27+00:00
Error	PHP	fwrite(): send of 1028 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner.php#68	2016-04-02T17:45:27+00:00
Error	PHP	fwrite(): send of 1028 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner.php#68	2016-04-02T17:45:27+00:00
Error	PHP	fwrite(): send of 1028 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner.php#68	2016-04-02T17:45:27+00:00
Error	PHP	fwrite(): send of 1028 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner.php#68	2016-04-02T17:45:27+00:00
Error	PHP	fwrite(): send of 1028 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner.php#68	2016-04-02T17:45:27+00:00
Error	PHP	fwrite(): send of 1028 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner.php#68	2016-04-02T17:45:27+00:00
Error	PHP	fwrite(): send of 1028 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner.php#68	2016-04-02T17:45:27+00:00
Error	PHP	fwrite(): send of 1028 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner.php#68	2016-04-02T17:45:27+00:00
Error	PHP	fwrite(): send of 1028 bytes failed with errno=32 Broken pipe at /var/www/owncloud/apps/files_antivirus/lib/scanner.php#68
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
Please re-open in https://github.com/owncloud/documents/issues after you made sure that you're running version 0.12.0 of the documents app.

**Comment by davodego** [comment]
Move to https://github.com/owncloud/documents/issues/619 and solved with https://github.com/owncloud/documents/pull/628

**Comment by RealRancor** [comment]
@davodego If its solved for you then you can close this on your own with the close button below the comment field.
