### ISSUE TITLE
owncloud-latest.tar.bz2 points to outdated version and md5sum doesn't match

### ISSUE THREAD

**Issue by envinyatar** [owncloud/core#23750]
http://download.owncloud.org/community/owncloud-latest.tar.bz2 points to version 8.2.2 but latest stable version is 9.0.0. Also owncloud-latest.tar.bz2 and owncloud-latest.tar.bz2.md5 doesn' match.

http://download.owncloud.org/community/owncloud-latest.tar.bz2 md5sum is
f5732baa2c0a5a44db3cf76775fe0c4f

http://download.owncloud.org/community/owncloud-latest.tar.bz2.md5 contains:
c9d642c1747b1ebcc0065b3b1acea6b5

**Comment by LukasReschke** [comment]
cc @karlitschek @cmonteroluque

**Comment by karlitschek** [comment]
This should be fixed automatically once we release 9.0.1

**Comment by cmonteroluque** [comment]
Files changed to 9.0.1 and build script updated.
