### ISSUE TITLE
Exported calendar filename has no file extension

### ISSUE THREAD

**Issue by stonie08** [owncloud/core#23751]
When exporting an owncloud calendar the filename is always "calendarname" (without file extension) while the import dialogue automatically filters for files with "*.ics". Therefore the exported filename should end with a .ics file extenson.
### Steps to reproduce
1. Create calendar
2. export created calendar
### Expected behaviour

Calendars should be exported with a name that is expected when importing the calendar, therefore ending on .ics.
### Actual behaviour

Calendars are only exported with the calendarname itself and without file extionsion
### Client configuration

**Browser:**
Mozilla Firefox 45.0.1

**Operating system:**
Windows 7

**CalDAV-clients:**
Browser

**Comment by Xenopathic** [comment]
I'm preparing a patch for the upstream Sabre DAV, which is where this comes from

**Comment by Xenopathic** [comment]
PR submitted at fruux/sabre-dav#812

**Comment by PVince81** [comment]
@DeepDiver1975 can you take over and check whether the upstream fix is now active as per our update of the libs ? Thanks

**Comment by DeepDiver1975** [comment]
fixed with the update to sabre-dav 3.2 - shipped with oc10
