### ISSUE TITLE
Integrity check always fails

### ISSUE THREAD

**Issue by Dreamsorcerer** [owncloud/core#23769]
After upgrading to OC 9, the integrity scan failed due to 488 extra files. Having deleted all of them, this continues to fail due to one file.

I delete the file, rescan, and it is back again.

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- 3rdparty/kriswallsmith/assetic/tests/Assetic/Test/Factory/Resource/Fixtures/dir1/file2.txt

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [3rdparty/kriswallsmith/assetic/tests/Assetic/Test/Factory/Resource/Fixtures/dir1/file2.txt] => Array
                        (
                            [expected] => 
                            [current] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
                        )

                )

        )

)
```

**Operating system**:
Debian

**Web server:**
Apache

**ownCloud version:**
9

**Updated from an older ownCloud or fresh install:**
8.2.2

**Where did you install ownCloud from:**
Debian repo (apt)

**Comment by nickvergessen** [comment]
The folder `3rdparty/kriswallsmith/assetic/tests/` is not in our repo, neither in our zips.
So I think you should report that to the debian repo?

**Comment by RealRancor** [comment]
@nickvergessen @LukasReschke Debian itself doesn't have oC9

**Comment by nickvergessen** [comment]
Well at least none of our packages contains it, so the warning is valid and good and actually does exactly what our should do... warn about files that should not be there.

**Comment by RealRancor** [comment]
Still this file/folder is one of a library of ownCloud and i doubt that the user has put that file in there.

**Comment by nickvergessen** [comment]
Not the user, but maybe 
> Where did you install ownCloud from:
Debian repo (apt)

**Comment by RealRancor** [comment]
Yes, but debian isn't providing ownCloud 9 at all:

https://packages.debian.org/search?keywords=owncloud

@Dreamsorcerer Can you confirm that you have used the official repository from download.owncloud.org?

**Comment by Dreamsorcerer** [comment]
Sorry, my mistake. It is the official OwnCloud repository, not Debian's repository.

deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /

**Comment by Dreamsorcerer** [comment]
Also, the only thing I've manually installed, and thus the only thing that should be at all non-standard is apps/notes/ from https://github.com/owncloud/notes

**Comment by Dreamsorcerer** [comment]
Actually, I may be wrong. I may have copied over the installation from a previous install, which was probably installed originally from the Ubuntu repos, then later updated from the owncloud.org ones.

I've just renamed the owncloud directory, reinstalled owncloud-files, and copied my data dir and config.php back in. And, now, everything is passing fine. So, this might actually be an artefact from a much older OC version, or from the Ubuntu/Debian version.
