### ISSUE TITLE
remote.php/dav is not working when using cURL

### ISSUE THREAD

**Issue by BernieO** [owncloud/core#23762]
I posted this issue already in the documentation-section, because I thought it was a documentation-issue. I've been pointed here by Xenopathic. Sorry for posting in the wrong section.
https://github.com/owncloud/documentation/issues/2330

### Steps to reproduce
1. Try to upload a file to webdav with cURL with `curl -u user:pass -T example.txt https://example.com/owncloud/remote.php/dav/example.txt` (like described here: https://doc.owncloud.org/server/9.0/user_manual/files/access_webdav.html#accessing-files-using-curl)

### Expected behaviour
File is uploaded to Owncloud

### Actual behaviour
Webserver answers with `403 Forbidden`

### possible workaround:
When the same command is used with `.../remote.php/webdav/...` the upload works as expected

### additional comments:
I also tried the other examples from the above linked documentation:
1. When trying to upload to a subdir with `.../remote.php/dav/subdir/...` the webserver answers with `404 Not Found`, though the subdirectory exists.
2. When trying to create a subfolder with `curl -X MKCOL` the webserver answers with `403 Forbidden`
3. When trying to move a file with `curl -X MOVE --header` the webserver answers with `409 Conflict`
4. When trying the last example in the documentation (get properties of files in root-folder) curl exits with `(23) Failed writing body`

numbers 1-3 work when using `remote.php/webdav` instead of using `remote.php/dav`
number 4 gives the same error when using webdav instead of dav

### Server configuration
**Operating system**:
Debian Jessie 8.4

**Web server:**
nginx 1.9.10

**Database:**
MariaDB 10.0.23

**PHP version:**
PHP Version 5.6.19-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
9.0.0 (stable)

**Updated from an older ownCloud or fresh install:**
updated

**Where did you install ownCloud from:**
the .tar.bz2-archive from here: https://owncloud.org/install/#instructions-server

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - calendar: true
  - contacts: 1.1.0.0
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_sharing: 0.9.1
Disabled:
  - activity
  - comments
  - encryption
  - external
  - federation
  - files_external
  - files_pdfviewer
  - files_texteditor
  - files_trashbin
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - gallery
  - notifications
  - provisioning_api
  - systemtags
  - templateeditor
  - updatenotification
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "525b03c150f9f",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/usr\/share\/nginx\/ocldata",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 524288,
        "log_rotate_sizerotation": 1048576,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maxZipInputSize": 104857600,
        "allowZipDownload": true,
        "enable_previews": false,
        "overwritewebroot": "\/ocl",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbname": "owncloud-db",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_from_address": "Owncloud",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": false,
        "debug": false
    }
}

```

**Are you using external storage, if yes which one:**
--> No external storage

**Are you using encryption:** yes/no
--> no encryption

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
--> no external user-backend

### Client configuration
curl 7.38.0

**Operating system:**

#### Web server error log
```
192.168.1.11 - user [04/Apr/2016:08:36:25 +0200] "MKCOL /ocl/remote.php/dav/Subfolder HTTP/1.1" 403 6858 "-" "curl/7.38.0"
192.168.1.11 - user [04/Apr/2016:08:36:53 +0200] "MOVE /ocl/remote.php/dav/Backup/example.txt HTTP/1.1" 409 236 "-" "curl/7.38.0"
192.168.1.11 - user [04/Apr/2016:08:37:33 +0200] "PUT /ocl/remote.php/dav/Backup/example.txt HTTP/1.1" 404 7037 "-" "curl/7.38.0"
192.168.1.11 - user [04/Apr/2016:08:37:40 +0200] "PUT /ocl/remote.php/dav/example.txt HTTP/1.1" 403 6883 "-" "curl/7.38.0"
192.168.1.11 - user [04/Apr/2016:08:38:35 +0200] "PROPFIND /ocl/remote.php/dav/Backup/ HTTP/1.1" 404 7012 "-" "curl/7.38.0"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"xQs+sVV4zz5rvNQPfhnF","remoteAddr":"192.168.1.11","app":"PHP","message":"stream_get_contents() expects parameter 2 to be long, string given at \/usr\/share\/nginx\/www\/ocl\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-04-04T08:36:25+02:00"}
{"reqId":"fRFhYDR8ztDL3U9MJlSX","remoteAddr":"192.168.1.11","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 409 The destination node is not found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Conflict\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/www\\\/ocl\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(624): Sabre\\\\DAV\\\\Server->getCopyAndMoveInfo(Object(Sabre\\\\HTTP\\\\Request))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/usr\\\/share\\\/nginx\\\/www\\\/ocl\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/share\\\/nginx\\\/www\\\/ocl\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#4 \\\/usr\\\/share\\\/nginx\\\/www\\\/ocl\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/usr\\\/share\\\/nginx\\\/www\\\/ocl\\\/apps\\\/dav\\\/lib\\\/server.php(137): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/usr\\\/share\\\/nginx\\\/www\\\/ocl\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(29): OCA\\\\DAV\\\\Server->exec()\\n#7 \\\/usr\\\/share\\\/nginx\\\/www\\\/ocl\\\/remote.php(138): require_once('\\\/usr\\\/share\\\/ngin...')\\n#8 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/www\\\/ocl\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":721,\"User\":\"user\"}","level":4,"time":"2016-04-04T08:36:53+02:00"}
{"reqId":"9ZGwSTvYj6gCPP5YSXG2","remoteAddr":"192.168.1.11","app":"PHP","message":"stream_get_contents() expects parameter 2 to be long, string given at \/usr\/share\/nginx\/www\/ocl\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-04-04T08:38:34+02:00"}
```

**Comment by rullzer** [comment]
Aaaah well you were actually right to report this in the doc repo. The new dav endpoint works somewhat different. I'll comment there.
Sorry for redirecting you once more....

**Comment by synthead** [comment]
Can you provide a link to your comment?

**Comment by BernieO** [comment]
There you go:
https://github.com/owncloud/documentation/issues/2330#issuecomment-205175284
