### ISSUE TITLE
Should not allow to store boolean values in oc_preferences

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#23776]
As per https://github.com/owncloud/core/issues/23761 

Failing test scenario:
```php
	public function testGetUserValueBoolean() {
		$config = $this->getConfig();

		$config->setUserValue('userGetUnset', 'appGetUnset', 'keyGetUnset1', false);
		$config->setUserValue('userGetUnset', 'appGetUnset', 'keyGetUnset2', true);

		$config = $this->getConfig();
		$this->assertEquals(false, $config->getUserValue('userGetUnset', 'appGetUnset', 'keyGetUnset1'));
		$this->assertEquals(true, $config->getUserValue('userGetUnset', 'appGetUnset', 'keyGetUnset2'));
	}
```

I think we should simply throw an exception in 9.1+ when someone tries to store a boolean, to make people aware of the problem. Opinions @DeepDiver1975 @MorrisJobke @LukasReschke

**Comment by MorrisJobke** [comment]
> I think we should simply throw an exception in 9.1+ when someone tries to store a boolean, to make people aware of the problem. Opinions @DeepDiver1975 @MorrisJobke @LukasReschke

Makes sense so far.
