### ISSUE TITLE
[SFTP] Upload hangs if the user doesn't have enough permissions in the backend

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#23781]
### Steps to reproduce
1. In the SFTP storage, setup a folder with read-only permissions with a couple of files in it (the user shouldn't be able to upload files in that folder)
2. Connect ownCloud to that SFTP storage, with an user (different than root) capable of reading but not writing in that folder
3. Go to that folder in ownCloud and verify you can see the files but you can delete them
4. Upload a file inside that folder

### Expected behaviour
An error is thrown (you don't have permissions to write in that folder)

### Actual behaviour
File upload gets stuck without any error message. 

### Server configuration
**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** sqlite3

**PHP version:** 5.5.9

**ownCloud version:** 9.0.1RC2

**Updated from an older ownCloud or fresh install:** fresh install

**Are you using external storage, if yes which one:** sftp

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
```
Nothing relevant
```

#### ownCloud log (data/owncloud.log)
```
Nothing relevant
```

**Comment by jvillafanez** [comment]
In addition, the lock over the file isn't released in those circumstances even if the upload is cancelled

**Comment by PVince81** [comment]
No, wrong! It's a bug in @icewind1991's streams.
There's an infinite loop here that doesn't check whether writing succeeded: https://github.com/icewind1991/Streams/blob/master/src/RetryWrapper.php#L61

Ouch.

**Comment by PVince81** [comment]
Raised here https://github.com/icewind1991/Streams/issues/3

There's also two other things I'm wondering about:
- why is phpseclib allowing us to fopen in write-mode in a read-only folder ? (CC @bantu)
- why are the permissions in ownCloud read-write for this folder ?
