### ISSUE TITLE
Updated calendar-shares loosing edit-rights

### ISSUE THREAD

**Issue by ionum** [owncloud/core#23796]
### Steps to reproduce
1. Update existing db with calendar-shares (with edit-right) from owncloud 8.2.x

### Expected behaviour
former-edit-rights-shares should be edit-rights-shares

### Actual behaviour
former-edit-rights-shares loosing edit-right

### Server configuration
mysql 5.5
owncloud 9.0.0
calendar 1.0

**Comment by DeepDiver1975** [comment]
fixed with 9.0.1
