### ISSUE TITLE
Missing share-keys for some files (high number of files in folder)

### ISSUE THREAD

**Issue by mislav-eu** [owncloud/core#23797]
### Steps to reproduce
1. The issue is probably connected with this one https://github.com/owncloud/core/issues/14647
2. Enable encryption/keys/add users - add files/folders under user1
3. Share this encrypted folder with new users - user2/user3/etc (or some group)

### Expected behaviour
Tell us what should happen - users should be able to access their shared files

### Actual behaviour
Tell us what happens instead - the problem is connected with huge amount of file-numbers definitely. There are other shared folders which contain one/two thousands of files and everything is fine there.

Here is the output of number of files in that shared folder:
$ find -type f | wc -l
28225

if we take a look on the same files_encryption keys files:
$ find -type f | wc -l
108107

As you can see, some files are missing their shared keys.

Anyway, the problem is basically that some shared files are working and some of them are not working. The whole process of un-sharing/sharing takes a while, around 20-30mins, but I watched the folder changes and you're probably doing 5-6 steps on each file so this is understandable time, however if I compare files that are not working/that are working, basically the problem is that in non-working files share key of userX is missing, whereas on the other hand files which are working are containing this key.

Is there maybe some maintenance tool to re-add missing shared keys maybe?

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache 2.4

**Database:** MariaDB 10.1

**PHP version:** PHP 5.6

**ownCloud version:** (see ownCloud admin page) ownCloud 9.0.0 (stable)

**Updated from an older ownCloud or fresh install:** Updated from 8.2.2 (which was updated from 8.1 clean installation)

**Where did you install ownCloud from:** via apt-get sources 

**Signing status (ownCloud 9.0 and above):** Where to find this?

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - external
  - firstrunwizard
  - gallery
  - notifications
  - user_external
  - user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 
  "system": {
        "instanceid": "oc30cx88yv6e",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XY"
        ],
        "datadirectory": "\/opt\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/XY",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "XY",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 3,
        "logdateformat": "F d, Y H:i:s",
        "asset-pipeline.enabled": true,
        "defaultapp": "files",
        "theme": "",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_domain": "XY",
        "mail_from_address": "XY",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "XY",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": false,
        "singleuser": false,
        "knowledgebaseenabled": false,
        "check_for_working_htaccess": false,
        "log_rotate_size": 104857600,
        "enable_previews": true,
        "filesystem_check_changes": 0,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "updatechecker": false
    }

```

**Are you using external storage, if yes which one:** local/smb/sftp/... - no external storage

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... - no external user-backend

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here

```
There are no logs associated with this - only error if you try to access this files - ask owner of the file to re-share it

**Comment by LukasReschke** [comment]
cc @owncloud/encryption

**Comment by mislav-eu** [comment]
@LukasReschke Do you have maybe some news about this? Is there many some command to re-generate missing ones or?

**Comment by schiesbn** [comment]
If you share a file with a group and later add new users to the group then this users won't have a share key. The user will get a notification to ask the owner to re-share the files with them. It is enough to to just share the file with the user and directly un-share it again. The important part is that it triggers the re-calculation of the recipients, ownCloud will detect the user is now a member of the group and a share key will be generated for him.

This can't be automated because in order to re-generate a share key you first have to decrypt the file and then re-encrypt it with the new set of users. This can't be done with a occ script but only by someone who already has access to the file.

Some possible solutions how it could be automated to some extend are discussed here: https://github.com/owncloud/core/issues/10010

Another solution is to use the master key instead of individual keys. But you can't migrate from individual keys to the master keys, you need to enable it right from the beginning.
