### ISSUE TITLE
Can't enable app through category if app folder exists, but app has not been enabled yet

### ISSUE THREAD

**Issue by heptathlon** [owncloud/core#23803]
### Steps to reproduce
1. Open the apps list (index.php/settings/apps)
2. Click on a category (Multimedia, Productivity, Game, Tool) which has at least one app listed
3. Find an app in that list which was never installed/enabled on your ownCloud installation (e.g. "Mail" app in "Productivity" category)
4. Download this app ("Mail") from the ownCloud app store (https://apps.owncloud.com/)
5. Copy the unzipped folder you just downloaded to your ownCloud's apps/ directory
6. Open the apps category ("Productivity") list in your browser once again
7. Click "Enable" on the app you downloaded
### Expected behaviour
- The app ("Mail") should be enabled as it was already downloaded manually
### Actual behaviour
- ownCloud downloads the app and then fails with "App directory already exists"
- However the app can be enabled through "Not enabled"
- If you enabled the app once through "Not enabled" and disabled it again, it can be re-enabled through the categories, e.g. "Productivity"
### Server configuration

**ownCloud version:**
Tried a fresh installation of ownCloud 8.2.2 and 9.0

**Comment by nickvergessen** [comment]
Well downloaded apps need to be enabled via the "Not enabled" section

I don't think there is a sane way to do it differently atm.

**Comment by DeepDiver1975** [comment]
We have to more clearly separate between local apps and appstore sections.
Furthermore we should handle such situations better and tell the user what to do ...
