### ISSUE TITLE
Contact Manager search does not properly format output

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#23810]
`\OCP\Contacts\IManager::search` claims to return `an array of contacts which are arrays of key-value-pairs`, it does however not seem to do that properly.

When installing the documents app and trying to share with another user `$contact['CLOUD']` is not an array but a single string. This fails as can be seen at https://github.com/owncloud/core/blob/v9.0.1RC2/core/ajax/share.php#L338-L353 

Leads to error messages like the following when trying to share in the documents app:

``` json
{
    "reqId": "D0Vt3qsCLsmfGwg4HHyu",
    "remoteAddr": "::1",
    "app": "PHP",
    "message": "Invalid argument supplied for foreach() at \/Users\/lukasreschke\/Documents\/Programming\/oc\/core\/ajax\/share.php#344",
    "level": 3,
    "time": "2016-04-05T14:31:27+00:00",
    "method": "GET",
    "url": "\/oc\/index.php\/core\/ajax\/share.php?fetch=getShareWith&search=tes&limit=200&itemType=file",
    "user": "admin"
}
```

<hr/>

cc @DeepDiver1975 @schiesbn

**Comment by jospoortvliet** [comment]
@VicDeo looks like the Documents app should be updated to use the public OCS API ;-)

**Comment by PVince81** [comment]
@DeepDiver1975 can you verify whether this is still an issue ?

**Comment by PVince81** [comment]
Closing due to lack of feedback
