### ISSUE TITLE
Expected user_input to be a string, NULL given (redux)

### ISSUE THREAD

**Issue by caldwellglobal** [owncloud/core#23815]
The first time I reported this, it was closed without addressing the underlying problem simply due to a code integrity check failure.  I uninstalled, deleted core files by hand, kept /config and /data, and then reinstalled.  It passed integrity check during the web-based upgrade process.

HOWEVER, the same problem still exists.  What should have been a reasonably simple upgrade has now broken our company's owncloud implementation for over a week.

Steps to reproduce

    Upgrade to 9.x including latest "testing"
    Try to login with either an LDAP user or a locally created user (one created with occ)

Server configuration

CentOS 7.2.1511
Apache 2.4
MariaDB
PHP 5.4.16
9.0.1~rc2-1.1 (yum repositories)

Login as admin user into your ownCloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.

sudo -u apache ./occ app:list
PHP Warning:  Module 'ldap' already loaded in Unknown on line 0
Enabled:
  - activity: 2.0.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.1.9
  - files_external: 0.2.3
  - files_pdfviewer: 0.8
  - files_sharing: 0.6.2
  - files_texteditor: 2.1
  - files_trashbin: 0.6.3
  - files_versions: 1.0.6
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 0.6.0
  - notifications: 0.2.3
  - provisioning_api: 0.2
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.6.1
Disabled:
  - encryption
  - external
  - files_locking
  - user_external
  - user_webdavauth

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc16f8dc3bd2',
  'passwordsalt' => '4835689a56c63b7d5ca664f2fe642e',
  'trusted_domains' => 
  array (
    0 => 'REDACTED',
    1 => 'REDACTED',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'version' => '9.0.1.2',
  'dbtype' => 'mysql',
  'dbhost' => 'localhost',
  'dbname' => 'owncloud',
  'dbuser' => 'owncloud',
  'dbpassword' => 'REDACTED',
  'dbtableprefix' => 'oc_',
  'installed' => true,
  'default_language' => 'en',
  'defaultapp' => 'files',
  'knowledgebaseenabled' => true,
  'enable_avatars' => true,
  'allow_user_to_change_display_name' => true,
  'session_keepalive' => true,
  'mail_domain' => 'REDACTED',
  'mail_from_address' => 'support',
  'mail_smtpdebug' => false,
  'mail_smtpmode' => 'php',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => 25,
  'mail_smtptimeout' => 10,
  'mail_smtpsecure' => '',
  'mail_smtpauth' => false,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'overwritehost' => '',
  'overwriteprotocol' => '',
  'overwritewebroot' => '',
  'overwritecondaddr' => '',
  'overwrite.cli.url' => '',
  'proxy' => '',
  'proxyuserpwd' => '',
  'trashbin_retention_obligation' => 'auto',
  'versions_retention_obligation' => 'auto',
  'appcodechecker' => true,
  'updatechecker' => false,
  'has_internet_connection' => true,
  'check_for_working_webdav' => true,
  'check_for_working_wellknown_setup' => true,
  'check_for_working_htaccess' => true,
  'config_is_read_only' => false,
  'log_type' => 'owncloud',
  'loglevel' => 2,
  'syslog_tag' => 'ownCloud',
  'log.condition' => 
  array (
    'shared_secret' => 'REDACTED',
    'users' => 
    array (
      0 => 'sample-user',
    ),
    'apps' => 
    array (
      0 => 'files',
    ),
  ),
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'America/New_York',
  'log_query' => false,
  'cron_log' => true,
  'cron.lockfile.location' => '',
  'log_rotate_size' => true,
  '3rdpartyroot' => '',
  '3rdpartyurl' => '',
  'customclient_desktop' => 'http://owncloud.org/sync-clients/',
  'customclient_android' => 'https://play.google.com/store/apps/details?id=com.owncloud.android',
  'customclient_ios' => 'https://itunes.apple.com/us/app/owncloud/id543672169?mt=8',
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'appstore.experimental.enabled' => false,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/owncloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'enable_previews' => true,
  'preview_max_x' => 2048,
  'preview_max_y' => 2048,
  'preview_max_scale_factor' => 10,
  'preview_max_filesize_image' => 50,
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'preview_office_cl_parameters' => ' --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ',
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\MP3',
    6 => 'OC\\Preview\\TXT',
    7 => 'OC\\Preview\\MarkDown',
  ),
  'ldapUserCleanupInterval' => 51,
  'comments.managerFactory' => '\\OC\\Comments\\ManagerFactory',
  'systemtags.managerFactory' => '\\OC\\SystemTag\\ManagerFactory',
  'maintenance' => false,
  'singleuser' => false,
  'openssl' => 
  array (
    'config' => '/etc/pki/tls/openssl.cnf',
  ),
  'enable_certificate_management' => false,
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'password' => '',
    'dbindex' => 0,
  ),
  'memcached_servers' => 
  array (
    0 => 
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),
  'cache_path' => '',
  'objectstore' => 
  array (
    'class' => 'OC\\Files\\ObjectStore\\Swift',
    'arguments' => 
    array (
      'username' => 'facebook100000123456789',
      'password' => 'REDACTED',
      'container' => 'owncloud',
      'autocreate' => true,
      'region' => 'RegionOne',
      'url' => 'http://8.21.28.222:5000/v2.0',
      'tenantName' => 'REDACTED',
      'serviceName' => 'swift',
      'urlType' => 'internal',
    ),
  ),
  'sharing.managerFactory' => '\\OC\\Share20\\ProviderFactory',
  'dbdriveroptions' => 
  array (
    1009 => '/file/path/to/ca_cert.pem',
  ),
  'sqlite.journal_mode' => 'DELETE',
  'supportedDatabases' => 
  array (
    0 => 'sqlite',
    1 => 'mysql',
    2 => 'pgsql',
    3 => 'oci',
  ),
  'tempdirectory' => '/tmp',
  'hashingCost' => 10,
  'blacklisted_files' => 
  array (
    0 => '.htaccess',
  ),
  'share_folder' => '/',
  'theme' => '',
  'cipher' => 'AES-256-CFB',
  'minimum.supported.desktop.version' => '1.7.0',
  'quota_include_external_storage' => false,
  'filesystem_check_changes' => 0,
  'part_file_in_storage' => true,
  'asset-pipeline.enabled' => false,
  'assetdirectory' => '/var/www/html/owncloud',
  'mount_file' => '/var/www/html/owncloud/data/mount.json',
  'filesystem_cache_readonly' => false,
  'secret' => 'REDACTED',
  'trusted_proxies' => 
  array (
    0 => '203.0.113.45',
    1 => '198.51.100.128',
  ),
  'forwarded_for_headers' => 
  array (
    0 => 'HTTP_X_FORWARDED',
    1 => 'HTTP_FORWARDED_FOR',
  ),
  'max_filesize_animated_gifs_public_sharing' => 10,
  'filelocking.enabled' => true,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'debug' => false,
  'copied_sample_config' => false,
);

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

{
    "system": {
        "instanceid": "oc16f8dc3bd2",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "version": "9.0.1.2",
        "dbtype": "mysql",
        "dbhost": "localhost",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "default_language": "en",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "session_keepalive": true,
        "mail_domain": "REDACTED",
        "mail_from_address": "support",
        "mail_smtpdebug": false,
        "mail_smtpmode": "php",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": 25,
        "mail_smtptimeout": 10,
        "mail_smtpsecure": "",
        "mail_smtpauth": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "",
        "overwriteprotocol": "",
        "overwritewebroot": "",
        "overwritecondaddr": "",
        "overwrite.cli.url": "",
        "proxy": "",
        "proxyuserpwd": "",
        "trashbin_retention_obligation": "auto, auto",
        "versions_retention_obligation": "auto",
        "appcodechecker": true,
        "updatechecker": false,
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_wellknown_setup": true,
        "check_for_working_htaccess": true,
        "config_is_read_only": false,
        "log_type": "owncloud",
        "loglevel": 2,
        "syslog_tag": "ownCloud",
        "log.condition": {
            "shared_secret": "REDACTED",
            "users": [
                "sample-user"
            ],
            "apps": [
                "files"
            ]
        },
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "America\/New_York",
        "log_query": false,
        "cron_log": true,
        "cron.lockfile.location": "",
        "log_rotate_size": true,
        "3rdpartyroot": "",
        "3rdpartyurl": "",
        "customclient_desktop": "http:\/\/owncloud.org\/sync-clients\/",
        "customclient_android": "https:\/\/play.google.com\/store\/apps\/details?id=com.owncloud.android",
        "customclient_ios": "https:\/\/itunes.apple.com\/us\/app\/owncloud\/id543672169?mt=8",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "appstore.experimental.enabled": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 10,
        "preview_max_filesize_image": 50,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "ldapUserCleanupInterval": 51,
        "comments.managerFactory": "\\OC\\Comments\\ManagerFactory",
        "systemtags.managerFactory": "\\OC\\SystemTag\\ManagerFactory",
        "maintenance": false,
        "singleuser": false,
        "openssl": {
            "config": "\/etc\/pki\/tls\/openssl.cnf"
        },
        "enable_certificate_management": false,
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "password": "",
            "dbindex": 0
        },
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "cache_path": "",
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\Swift",
            "arguments": {
                "username": "facebook100000123456789",
                "password": "***REMOVED SENSITIVE VALUE***",
                "container": "owncloud",
                "autocreate": true,
                "region": "RegionOne",
                "url": "http:\/\/8.21.28.222:5000\/v2.0",
                "tenantName": "facebook100000123456789",
                "serviceName": "swift",
                "urlType": "internal"
            }
        },
        "sharing.managerFactory": "\\OC\\Share20\\ProviderFactory",
        "dbdriveroptions": {
            "1009": 0
        },
        "sqlite.journal_mode": "DELETE",
        "supportedDatabases": [
            "sqlite",
            "mysql",
            "pgsql",
            "oci"
        ],
        "tempdirectory": "\/tmp",
        "hashingCost": 10,
        "blacklisted_files": [
            ".htaccess"
        ],
        "share_folder": "\/",
        "theme": "",
        "cipher": "AES-256-CFB",
        "minimum.supported.desktop.version": "1.7.0",
        "quota_include_external_storage": false,
        "filesystem_check_changes": 0,
        "part_file_in_storage": true,
        "asset-pipeline.enabled": false,
        "assetdirectory": "\/var\/www\/html\/owncloud",
        "mount_file": "\/var\/www\/html\/owncloud\/data\/mount.json",
        "filesystem_cache_readonly": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": [
            "203.0.113.45",
            "198.51.100.128"
        ],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "max_filesize_animated_gifs_public_sharing": 10,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "debug": false,
        "copied_sample_config": false
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "2"
        },
        "calendar": {
            "enabled": "no",
            "installed_version": "0.6.4",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "contacts": {
            "backend_ldap": "false",
            "enabled": "no",
            "installed_version": "0.3.0.18",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "webcron",
            "global_cache_gc_lastrun": "1414442450",
            "installedat": "1414442446.9055",
            "lastcron": "1414442471",
            "lastupdateResult": "{\"version\":\"8.2.2.2\",\"versionstring\":\"ownCloud 8.2.2\",\"url\":\"https:\\\/\\\/download.owncloud.org\\\/community\\\/owncloud-8.2.2.zip\",\"web\":\"https:\\\/\\\/doc.owncloud.org\\\/server\\\/8.2\\\/admin_manual\\\/maintenance\\\/upgrade.html\"}",
            "lastupdatedat": "0",
            "oc.integritycheck.checker": "[]",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "shareapi_allow_public_upload": "no",
            "shareapi_default_expire_date": "yes",
            "shareapi_enforce_links_password": "no",
            "shareapi_expire_after_n_days": "21"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.1.6",
            "types": "filesystem"
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0.8.2",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.0.4",
            "types": "authentication"
        },
        "files": {
            "enabled": "yes",
            "installed_version": "1.4.4",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "0.5.2",
            "ocsid": "166048",
            "types": "filesystem"
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "43": "1444274843.6258",
            "46": "1454011436.2699",
            "49": "1445582519.4512",
            "52": "1450118138.0783",
            "53": "1450118138.0789",
            "56": "1452027191.6216",
            "57": "1452311172.3983",
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "0.9.1",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "14.5.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.2.3",
            "types": "logging"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction"
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.5.3",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.4",
            "ocsid": "166059",
            "types": ""
        },
        "user_ldap": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "s01has_memberof_filter_support": "",
            "s01home_folder_naming_rule": "",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_agent_password": "WDNkenkzOTVqZg==",
            "s01ldap_attributes_for_group_search": "",
            "s01ldap_attributes_for_user_search": "",
            "s01ldap_backup_host": "",
            "s01ldap_backup_port": "",
            "s01ldap_base": "dc=REDACTED,dc=local",
            "s01ldap_base_groups": "dc=REDACTED,dc=local",
            "s01ldap_base_users": "ou=REDACTED,ou=Companies,dc=REDACTED,dc=local",
            "s01ldap_cache_ttl": "600",
            "s01ldap_configuration_active": "1",
            "s01ldap_display_name": "mail",
            "s01ldap_dn": "cn=admin,dc=REDACTED,dc=local",
            "s01ldap_dynamic_group_member_url": "",
            "s01ldap_email_attr": "",
            "s01ldap_experienced_admin": "0",
            "s01ldap_expert_username_attr": "",
            "s01ldap_expert_uuid_group_attr": "",
            "s01ldap_expert_uuid_user_attr": "",
            "s01ldap_group_display_name": "cn",
            "s01ldap_group_filter": "",
            "s01ldap_group_filter_mode": "0",
            "s01ldap_group_member_assoc_attribute": "uniqueMember",
            "s01ldap_groupfilter_groups": "",
            "s01ldap_groupfilter_objectclass": "",
            "s01ldap_host": "REDACTED",
            "s01ldap_login_filter": "(&(|(objectclass=REDACTED-user))(|(cn=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))",
            "s01ldap_login_filter_mode": "1",
            "s01ldap_loginfilter_attributes": "",
            "s01ldap_loginfilter_email": "1",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_nested_groups": "0",
            "s01ldap_nocase": "0",
            "s01ldap_override_main_server": "0",
            "s01ldap_paging_size": "500",
            "s01ldap_port": "389",
            "s01ldap_quota_attr": "",
            "s01ldap_quota_def": "",
            "s01ldap_tls": "0",
            "s01ldap_turn_off_cert_check": "1",
            "s01ldap_user_display_name_2": "",
            "s01ldap_user_filter_mode": "1",
            "s01ldap_userfilter_groups": "",
            "s01ldap_userfilter_objectclass": "REDACTED-user",
            "s01ldap_userlist_filter": "(|(objectclass=REDACTED-user))",
            "s01use_memberof_to_detect_membership": "1",
            "types": "authentication"
        }
    }
}

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
LDAP configuration (delete this part if not used)

+-------------------------------+------------------------------------------------------------------------------------+
| Configuration | s01 |
+-------------------------------+------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport | |
| hasPagedResultSupport | |
| homeFolderNamingRule | |
| lastJpegPhotoLookup | 0 |
| ldapAgentName | cn=admin,dc=REDACTED,dc=local |
| ldapAgentPassword | *** |
| ldapAttributesForGroupSearch | |
| ldapAttributesForUserSearch | |
| ldapBackupHost | |
| ldapBackupPort | |
| ldapBase | dc=REDACTED,dc=local |
| ldapBaseGroups | dc=REDACTED,dc=local |
| ldapBaseUsers | ou=REDACTED,ou=Companies,dc=REDACTED,dc=local |
| ldapCacheTTL | 600 |
| ldapConfigurationActive | 1 |
| ldapDynamicGroupMemberURL | |
| ldapEmailAttribute | |
| ldapExperiencedAdmin | 0 |
| ldapExpertUUIDGroupAttr | |
| ldapExpertUUIDUserAttr | |
| ldapExpertUsernameAttr | |
| ldapGroupDisplayName | cn |
| ldapGroupFilter | |
| ldapGroupFilterGroups | |
| ldapGroupFilterMode | 0 |
| ldapGroupFilterObjectclass | |
| ldapGroupMemberAssocAttr | uniqueMember |
| ldapHost | REDACTED |
| ldapIgnoreNamingRules | |
| ldapLoginFilter | (&(|(objectclass=REDACTED-user))(|(cn=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes | |
| ldapLoginFilterEmail | 1 |
| ldapLoginFilterMode | 1 |
| ldapLoginFilterUsername | 1 |
| ldapNestedGroups | 0 |
| ldapOverrideMainServer | 0 |
| ldapPagingSize | 500 |
| ldapPort | 389 |
| ldapQuotaAttribute | |
| ldapQuotaDefault | |
| ldapTLS | 0 |
| ldapUserDisplayName | mail |
| ldapUserDisplayName2 | |
| ldapUserFilter | (|(objectclass=REDACTED-user)) |
| ldapUserFilterGroups | |
| ldapUserFilterMode | 1 |
| ldapUserFilterObjectclass | REDACTED-user |
| ldapUuidGroupAttribute | auto |
| ldapUuidUserAttribute | auto |
| turnOffCertCheck | 1 |
| useMemberOfToDetectMembership | 1 |
+-------------------------------+------------------------------------------------------------------------------------+
Client configuration

Any
Logs
Web server error log

[04/Apr/2016:10:52:55 -0400] "HEAD /owncloud/remote.php/webdav/InstantUpload/ HTTP/1.1" 401 -
ownCloud log (data/owncloud.log)

{"reqId":"VwKB9T-hkIqSHyKT6nW1fwAAAAE","remoteAddr":"REDACTED-IP","app":"PHP","message":"Expected user_input to be a string, NULL given at \/var\/www\/html\/owncloud\/3rdparty\/symfony\/polyfill-php56\/Php56.php#33","level":3,"time":"April 04, 2016 11:02:13","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"--"}
{"reqId":"VwKB9T-hkIqSHyKT6nW1gAAAAAE","remoteAddr":"REDACTED-IP","app":"PHP","message":"Expected user_input to be a string, NULL given at \/var\/www\/html\/owncloud\/3rdparty\/symfony\/polyfill-php56\/Php56.php#33","level":3,"time":"April 04, 2016 11:02:13","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"--"}
{"reqId":"VwKB9T-hkIqSHyKT6nW1gAAAAAE","remoteAddr":"REDACTED-IP","app":"user_ldap","message":"function ldap_connect is not available. Make sure that the PHP ldap module is installed.","level":3,"time":"April 04, 2016 11:02:13","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"--"}
{"reqId":"VwKB9T-hkIqSHyKT6nW1gAAAAAE","remoteAddr":"REDACTED-IP","app":"user_ldap","message":"No LDAP Connection to server REDACTED","level":3,"time":"April 04, 2016 11:02:13","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"--"}
{"reqId":"VwKB9T-hkIqSHyKT6nW1gAAAAAE","remoteAddr":"REDACTED-IP","app":"user_ldap","message":"Exception: {\"Exception\":\"OC\\ServerNotAvailableException\",\"Message\":\"Connection to LDAP server could not be established\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/owncloud\\/apps\\/user_ldap\\/lib\\/access.php(845): OCA\\user_ldap\\lib\\Connection->getConnectionResource()\n#1 \\/var\\/www\\/html\\/owncloud\\/apps\\/user_ldap\\/lib\\/access.php(1011): OCA\\user_ldap\\lib\\Access->executeSearch('(&(|(objectclas...', Array, Array, NULL, NULL)\n#2 \\/var\\/www\\/html\\/owncloud\\/apps\\/user_ldap\\/lib\\/access.php(781): OCA\\user_ldap\\lib\\Access->search('(&(|(objectclas...', Array, Array, NULL, NULL)\n#3 \\/var\\/www\\/html\\/owncloud\\/apps\\/user_ldap\\/lib\\/access.php(704): OCA\\user_ldap\\lib\\Access->searchUsers('(&(|(objectclas...', Array, NULL, NULL)\n#4 \\/var\\/www\\/html\\/owncloud\\/apps\\/user_ldap\\/lib\\/access.php(678): OCA\\user_ldap\\lib\\Access->fetchListOfUsers('(&(|(objectclas...', Array)\n#5 \\/var\\/www\\/html\\/owncloud\\/apps\\/user_ldap\\/user_ldap.php(103): OCA\\user_ldap\\lib\\Access->fetchUsersByLoginName('REDACTED', Array, 1)\n#6 \\/var\\/www\\/html\\/owncloud\\/apps\\/user_ldap\\/user_ldap.php(120): OCA\\user_ldap\\USER_LDAP->getLDAPUserByLoginName('REDACTED')\n#7 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/user\\/manager.php(183): OCA\\user_ldap\\USER_LDAP->checkPassword(*** username and password replaced )\n#8 \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/user\\/session.php(219): OC\\User\\Manager->checkPassword( username and password replaced )\n#9 \\/var\\/www\\/html\\/owncloud\\/apps\\/dav\\/lib\\/connector\\/sabre\\/auth.php(106): OC\\User\\Session->login( username and password replaced ***)\n#10 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Auth\\/Backend\\/AbstractBasic.php(105): OCA\\DAV\\Connector\\Sabre\\Auth->validateUserPass('REDACTED', 'Penguin7##')\n#11 \\/var\\/www\\/html\\/owncloud\\/apps\\/dav\\/lib\\/connector\\/sabre\\/auth.php(220): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->check(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#12 \\/var\\/www\\/html\\/owncloud\\/apps\\/dav\\/lib\\/connector\\/sabre\\/auth.php(127): OCA\\DAV\\Connector\\Sabre\\Auth->auth(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#13 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Auth\\/Plugin.php(166): OCA\\DAV\\Connector\\Sabre\\Auth->check(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#14 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#15 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#16 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#17 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#18 \\/var\\/www\\/html\\/owncloud\\/apps\\/dav\\/appinfo\\/v1\\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#19 \\/var\\/www\\/html\\/owncloud\\/remote.php(138): require_once('\\/var\\/www\\/html\\/o...')\n#20 {main}\",\"File\":\"\\/var\\/www\\/html\\/owncloud\\/apps\\/user_ldap\\/lib\\/connection.php\",\"Line\":175}","level":3,"time":"April 04, 2016 11:02:13","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"--"}
{"reqId":"VwKB9T-hkIqSHyKT6nW1gAAAAAE","remoteAddr":"REDACTED-IP","app":"core","message":"Login failed: 'REDACTED' (Remote IP: 'REDACTED-IP')","level":2,"time":"April 04, 2016 11:02:13","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"--"}
Browser log

**Comment by RealRancor** [comment]
Hi,

not directly related to your issue but:

``'copied_sample_config' => false,``

is very likely not true. It seems that you have copied this completely config.sample.php file which is unsupported and can break your installation at any time.

**Comment by RealRancor** [comment]
Hi,

not directly related to your issue but:

``'copied_sample_config' => false,``

is very likely not true. It seems that you have copied this completely config.sample.php file which is unsupported and can break your installation at any time.

**Comment by LukasReschke** [comment]
Yes. Please don't base your config on the sample config. Just change defaults you really need to change.

**Comment by abhis27** [comment]
is it ok to write data dis as  "\/var\/www\/html\/owncloud\/data", ?
