### ISSUE TITLE
Read-only shared calendars are writeable via CalDav

### ISSUE THREAD

**Issue by nWRqenkF** [owncloud/core#23813]
### Steps to reproduce
1. Login as user A, share Calendar for user B, leave "can edit" unchecked
2. Login as user B in UI, Calendar of user A is visible. You cannot create an event via UI in calendar of user A
3. Connect via CalDAV to owncloud (e.g. DavDroid, SoGoConnector) as user B

### Expected behaviour
Primary calendar of user A and user B are visible
Events are editable (new events or updated events) in the calendar of user B.

### Actual behaviour
User B can create events in calendar of user A and can modify events in calendar of user A.

### Server configuration
**Operating system**: Debian Wheezy

**Web server:** nginx

**Database:** MySql

**PHP version:** 5.6.17

**ownCloud version:** (see ownCloud admin page) 9.0.0

**Contacts version:** (see ownCloud apps page) 1.0.0.0

**Updated from an older ownCloud or fresh install:** Updated from 8.2 from official apt-repositories

### Client configuration
**Browser:** Firefox 44.0

**Operating system:** Windows 7

**Comment by DeepDiver1975** [comment]
will be fixed with 9.0.1

**Comment by nWRqenkF** [comment]
seems that only calendars migrated from 8.x are effected.
Newly created calendars show the expected behaviour
