### ISSUE TITLE
Integrity check: 9,231,290,938,786.7 EXTRA_FILE errors.

### ISSUE THREAD

**Issue by 9662** [owncloud/core#23828]
Ok, so I made up that number. Still quite a few of them, though, as seen in the attached [file](https://github.com/owncloud/core/files/207632/failed.txt).

This is after upgrading the installation from 8.1 to 8.2.3 then onwards to 9. I do not recall what the original install was, probably version 6 something.

**Comment by RealRancor** [comment]
Hi,

no bug here. Please do a correct upgrade by deleting all files and folders except /data/ and /config/ before copy over the new files. If you have further questions use the options listed at https://owncloud.org/support

**Comment by 9662** [comment]
@RealRancor Thanks for the hint. Could you point me to a more specific link where the deleting of files and directories is discussed?

**Comment by RealRancor** [comment]
@9662 Please see:

> If you have further questions use the options listed at https://owncloud.org/support

**Comment by 9662** [comment]
> @9662 Please see:
>>   If you have further questions use the options listed at https://owncloud.org/support

That's hardly *specific*, isn't it? I couldn't find anywhere in the documentation anything directing me to delete everything minus `/data` and `/config`.

**Comment by RealRancor** [comment]
@9662 If you follow https://doc.owncloud.org/server/9.0/admin_manual/maintenance/manual_upgrade.html those steps are included.

**Comment by 9662** [comment]
> If you follow the correct upgrade instructions available at https://doc.owncloud.org/server/9.0/admin_manual/maintenance/manual_upgrade.html those steps are included.

That's a better resource than the link originally provided.
