### ISSUE TITLE
Make compatible for Firefox OS, becoming a WebApp in few steps

### ISSUE THREAD

**Issue by Vincent14** [owncloud/core#2382]
Firefox OS will be available on some smartphone in few days. I would suggest to make OC compatible with Firefox OS without having to build a dedicated App like for Android.

Because the theme is near of Responsive Design, there is only two main things that should be done:
- build a file at the installation of OC, the "manifest" (resources: https://marketplace.firefox.com/developers/docs/manifests // https://developer.mozilla.org/en-US/docs/Apps/Manifest )
- add WebAPI  functionnalities where it's needed, for example to a access the file system, sync, etc (resources: https://hacks.mozilla.org/2013/01/introducing-web-activities/ // https://hacks.mozilla.org/2013/02/using-webapis-to-make-the-web-layer-more-capable/ )

An other link to help to understand what could be done https://hacks.mozilla.org/2013/02/getting-started-with-open-web-apps-why-and-how/

I think OwnCloud have all to win with this.

**Comment by MorrisJobke** [comment]
Firefox OS is dead -> closing

**Comment by Mte90** [comment]
Firefox OS is not dead, https://blog.mozilla.org/blog/2015/12/09/firefox-os-pivot-to-connected-devices/

**Comment by mcepl** [comment]
> Firefox OS is not dead,

Just pinning for the fjords. I am certainly not a FxOS-hater (I owned four FxOS phones), but I think FxOS is a stone dead. Really. What is not dead however, and what I really like and believe in is the idea of HTML5-apps as The True Universal Apps. I really hate the world of special locked apps for each platform one.

**Comment by HLFH** [comment]
@mcepl 

> FxOS is a stone dead. [...] HTML5-apps as The True Universal Apps.

I fully agree with you. 

@MorrisJobke IMHO, this issue could be closed. It's quite some Newspeak ("Nov'langue in French") from Mozilla and the mozillians. Firefox OS is dead.

**Comment by MorrisJobke** [comment]
Okay. Currently also the web UI and the backend are tied together (we are working on making them separate things (but not because of FxOS) - I will close this here because it's not really a focus for us to get this deployed as FxOS app.

**Comment by rugk** [comment]
The only thing Mozilla stopped are the partnership with carriers and producers of mobile phones.
This does not mean that there won't be any mobile phones with FxOS any more...
https://discourse.mozilla-community.org/t/firefox-os-is-dead-no
