### ISSUE TITLE
Show App Notifications in the App Menu

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#23826]
We could show little red circles with a notification counter directly over some apps. This could be interesting for some apps like Mail (Number of new Mails), Calendar (Event Notifications) or Announcements (Number of Announcements not readed). 

We could provide this as an API, so that 3rdparty-apps could integrate this :wink: 

I am not sure, whether i am at the right place here. The App Menu is core i think, but maybe this is an enhancement for the notification-repository (too) :grin: 

cc @jancborchardt @nickvergessen

**Comment by nickvergessen** [comment]
There is already a ticket for this somewhere

**Comment by nickvergessen** [comment]
Here is the link for completeness: https://github.com/owncloud/core/issues/15309
