### ISSUE TITLE
upgrade from 8.2.3 to 9.0.1 leads to PHP Fatal error

### ISSUE THREAD

**Issue by himbeere** [owncloud/core#23836]
### Steps to reproduce
1. Upgrade to 9.0.1 by
- mv owncloud docroot to owncloud.bak
- tar xvzf v9.0.1.tar.gz to owncloud
- cp -a owncloud.bak/config owncloud/
- cp -a owncloud.bak/data owncloud/

php-error.log after starting apache:

`[07-Apr-2016 13:44:43 Europe/Berlin] PHP Fatal error:  Call to a member function getRequest() on null in /var/www/owncloud/lib/private/response.php on line 77`

### Expected behaviour
working 9.0.1 copy

### Actual behaviour
white page because of PHP Fatal error

### Server configuration
Linux

**Web server:**
Apache 2.4.18

**Database:**
Mysql Mariadb 10.1.13

**PHP version:**
PHP-5.6.20

thanks and cheers
t.

**Comment by LukasReschke** [comment]
We need some more informations such as:

- Your config file
- From what version you updated
- Installed apps…

**Comment by RealRancor** [comment]
Looks similar to https://github.com/owncloud/core/issues/23814, https://github.com/owncloud/core/issues/23031, https://github.com/owncloud/core/issues/21169

**Comment by himbeere** [comment]
Hello.

Here my config file.

`<?php
$CONFIG = array (
  'passwordsalt' => '31834428338477842223435741275732',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.2.3.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'password',
  'installed' => true,
  'instanceid' => '505b4a36ee5e3',
  'maintenance' => false,
  'theme' => '',
  'trusted_domains' => 
  array (
    0 => 'fluffycloud.de',
  ),
  'mail_smtpmode' => 'sendmail',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'domain.de',
  'secret' => 'a58431d7d2e3fbda9c6b144aef3d1561bece6a01ab7d79afc4703cab938b0fad39135bcc079345b55381d6fcef818cec',
  'loglevel' => 2,
);`

**Comment by himbeere** [comment]
Only calendar and contacts is installed.

**Comment by himbeere** [comment]
Don't know why this issue suddenly was closed. Maybe i hit the wrong button.

**Comment by RealRancor** [comment]
@himbeere Where did you get v9.0.1.tar.gz from? Via https://github.com/owncloud/core/releases? If yes this can be immediately closed as you can't use this archive to upgrade your instance. Please only use the tar.bz2 or zip files linked at https://owncloud.org/install/#instructions-server

**Comment by himbeere** [comment]
Ah okay. I see. I will close this issue.
.
