### ISSUE TITLE
Allow disabling of a single user

### ISSUE THREAD

**Issue by rullzer** [owncloud/core#23838]
To migrate users from one storage to the next without bringing down the whole system we must be able to disable single users.

This would then block out the users so we can safely transfer their data.
Ideally we make sure this is not to distruptive by throwing a 503 for shares from this user for example.

@DeepDiver1975 assigned to you as discussed.

**Comment by DeepDiver1975** [comment]
@LukasReschke should we add you idea regarding the version number to invalidate sessions into this?

**Comment by RealRancor** [comment]
Existing issue for the User Management: https://github.com/owncloud/core/issues/12601

**Comment by DeepDiver1975** [comment]
@RealRancor THX for keeping the mess sorted out! :wink:
