### ISSUE TITLE
Web shared links allowed to upload content with server capability disabled

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#23830]
### Steps to reproduce
1. Share a folder by link
2. Copy the link and paste it in a browser
3. Disable the capability "Allow public uploads". **Do not refresh the browser share URL**
### Actual behaviour

You can upload whatever you want although the capability is disabled. If you upload some pics, all of them are tried to be upload with the same name, causing name conflicts (perhaps another different issue)
### Expected behaviour

You can't upload because the capability was disabled
### Server configuration

{"installed":true,"maintenance":false,"version":"9.0.1.2","versionstring":"9.0.1 RC2","edition":"Enterprise"}

**Comment by nickvergessen** [comment]
I can not reproduce the conflict issue, but upload still works yes.

**Comment by nickvergessen** [comment]
@rullzer I think we could add a check for the global in https://github.com/owncloud/core/blob/60d8046c3574a5cc9c30bdfee57da9e1b3cec27c/apps/files/ajax/upload.php#L71-L71

The UI will not allow uploads after a page refresh, but if you know the endpoint you can still upload, when the link share was created with create permissions before the config was switched.

**Comment by rullzer** [comment]
@nickvergessen yes we could throw a 403 there somewhere.
We should also not forget this case when moving upload to webdav..

**Comment by jesmrec** [comment]
@nickvergessen 

sorry, i forgot an important detail. The conflict problem happens with Safari in mobile devices. In Chrome, Mozilla (at least) works fine.

**Comment by PVince81** [comment]
@jesmrec mind retrying with master where we now use Webdav PUT ? It should return 403 and display an error, no conflict dialog.

**Comment by PVince81** [comment]
Closing due to lack of feedback.

Please retry with 10.0 beta and reopen if the problem persists.
