### ISSUE TITLE
Give the ability to provide Presets for S3 endpoints in external storage

### ISSUE THREAD

**Issue by squidboylan** [owncloud/core#23849]
this is related to https://github.com/owncloud/core/pull/23283 (adding DreamObjects support to external storage options) so it can be accomplished in a better way. It would be cool to support presets for different S3 endpoints so it is easier for users to use them for their ownCloud storage. If we did this the users wouldn't have to look up info like host and port, they would instead select a preset that would have that info.

**Comment by nickvergessen** [comment]
Please add more details

**Comment by PVince81** [comment]
Would be better implemented as a separate app. We're going to move S3 and other external storages to be apps anyway.
