### ISSUE TITLE
Automatically login from other site: requesttoken needed

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/core#23846]
### Expected behaviour
With given username and password via post it should be possible to directly login.

### Steps to reproduce
1. Use a page where an user is authenticated. Username/password is the same due owncloud already gets these credentials via user_sql addon.
2. Click on a link to ownloud while logged in the other system.
3. Opens owncloud in new window, without entering the same credentials.

### Actual behaviour
Not working due to requesttoken is needed.
Workaround: modify passesCSRFCheck() to return always true in ./lib/private/appframework/http/request.php

I suppose the requesttoken is there for security reasons and should not be disabled, so I am searching for a way to avoid this.

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
8.0

**Comment by LukasReschke** [comment]
That's not possible to prevent login CSRF. If you want to achieve this you're probably best off by creating a simple app that takes username + password and then calls `\OC_User::login($loginname, password)`. If the right credentials are passed the user has been authenticated.

For enhanced security you might want to verify the referrer there as well or do some signature magic. – Note that this is private API (as in: Might break in major releases ;)) but for 9.1 we do have some plans to make some of the stuff more accessible to app devs.

**Comment by tobiasKaminsky** [comment]
Thank you for your quick reply!

I have created a custom app that calls this function:
```
public function login($username, $password){
		\OC_User::logout();
		$login = \OC_User::login($username, $password);
		return new DataResponse(['loggedIn' => $login]);
}
```

But I get in data/owncloud.log: 
{"reqId":"bca2d7ece490e4b46720cad45cb0d976",
"remoteAddr":"127.0.0.1",
"app":"index",
"message":"Exception: {\"Message\":\"Session has been closed - no further changes to the session as allowed\",\"Code\":0,\"Trace\":\"
#0 \\\/home\\\/tobi\\\/Daten\\\/arbeit\\\/iat-lokal\\\/owncloud\\\/lib\\\/private\\\/session\\\/internal.php(36): OC\\\\Session\\\\Internal->validateSession()\

Calling "\OC_User::checkPassword($username, $password)" is returning the username, indicating that credentials are right.

**Comment by LukasReschke** [comment]
@tobiasKaminsky `@UseSession` as annotation on that controller method and it should work. The session is closed for performance reasons automatically :)

**Comment by tobiasKaminsky** [comment]
Thank you for the last hint.
Now everything is working as expected!

**Comment by gklimm** [comment]
I have the same "problem". Can you please share this custom app?
