### ISSUE TITLE
Repeated authentication prompts when sharing a folder

### ISSUE THREAD

**Issue by ownbug** [owncloud/core#23843]
### Steps to reproduce
1. Install ownCloud 9.x
2. Create a folder.
3. Share the folder and set a password.

### Expected behaviour
We tend to share folders rather and sending multiple links to individual files. E.g http://s23.postimg.org/ro0ro3x9n/share.png
When someone accesses a shared folder, they should see a list of the files within the shared folder. This worked in versions prior to 9.x.

### Actual behaviour
The link can be accessed, but instead of seeing the files, the user is prompted to authenticate in an endless loop. Screenshot of prompt: http://s22.postimg.org/kam5t4wpd/auth.png

If a file is shared directly, the server behaves as normal. This issue only appears when a folder is shared.

### Server configuration
**Operating system**: 
Debian 8 64-bit
Linux owncloud 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux

**Web server:**
Apache 2.4.10

**Database:**
Postgres 9.4.7

**PHP version:**
PHP 5.6.19-0+deb8u1
Zend Engine v2.6.0, with Zend OPcache v7.0.6-dev

**ownCloud version:** (see ownCloud admin page)
9.0 and 9.0.0.19

**Updated from an older ownCloud or fresh install:**
Originally updated from 8.3. Same issue with a clean build.

**Where did you install ownCloud from:**
https://download.owncloud.org/community/owncloud-9.0.0.tar.bz2
https://github.com/owncloud/core/archive/master.zip

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - firstrunwizard: 1.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - files_videoplayer
  - gallery
  - templateeditor
  - user_external
  - user_ldap

**The content of config/config.php:**

'<?php
$CONFIG = array (
  'instanceid' => '<scrubbed>',
  'passwordsalt' => '<scrubbed>',
  'secret' => '<scrubbed>',
  'trusted_domains' =>
  array (
    0 => '<ip.addr>',
  ),
  'datadirectory' => '/usr/share/owncloud_data',
  'overwrite.cli.url' => 'https://<ip.addr>',
  'dbtype' => 'pgsql',
  'version' => '9.0.0.19',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '<scrubbed>',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'has_internet_connection' => true,
');

**Are you using external storage, if yes which one:** 
None.

**Are you using encryption:** 
None other than HTTPS.

**Are you using an external user-backend, if yes which one:** 
No.

### Client configuration
**Browser:**
Chrome 49.0.2623.110 m

**Operating system:**
Windows 8.1

#### Web server error log
[Thu Apr 07 07:35:04.194893 2016] [ssl:warn] [pid 9237] AH01906: owncloud:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Thu Apr 07 07:35:04.210986 2016] [mpm_prefork:notice] [pid 9237] AH00163: Apache/2.4.10 (Debian) OpenSSL/1.0.1k configured -- resuming normal operations
[Thu Apr 07 07:35:04.211103 2016] [core:notice] [pid 9237] AH00094: Command line: '/usr/sbin/apache2'
[Thu Apr 07 07:35:04.224006 2016] [:error] [pid 12456] avahi_entry_group_add_service_strlst("owncloud") failed: Invalid host name
[Thu Apr 07 07:35:04.226924 2016] [:error] [pid 12456] avahi_entry_group_add_service_strlst("owncloud") failed: Invalid host name

#### VirtualHost config
<VirtualHost _default_:443>
                ServerAdmin <scubbed>
                ServerName owncloud:443
                <IfModule mod_headers.c>
                        Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
                </IfModule>
                DocumentRoot /usr/share/owncloud
                SSLEngine on
                SSLCertificateFile /etc/apache2/ssl/apache.crt
            SSLCertificateKeyFile /etc/apache2/ssl/apache.key
        </VirtualHost>

#### ownCloud log (data/owncloud.log)
{"reqId":"<scrubbed>","remoteAddr":"<scrubbed>","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/usr\\\/share\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/usr\\\/share\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/installer.php(621): include('\\\/usr\\\/share\\\/ownc...')\\n#4 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/usr\\\/share\\\/ownc...')\\n#5 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/usr\\\/share\\\/owncloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/usr\\\/share\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/usr\\\/share\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-04-06T22:53:01+00:00"}
{"reqId":"<scrubbed>","remoteAddr":"<scrubbed>","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Calendar tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migratecalendars.php(84): OCA\\\\Dav\\\\Migration\\\\CalendarAdapter->setup()\\n#1 \\\/usr\\\/share\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(202): OCA\\\\Dav\\\\Migration\\\\MigrateCalendars->setup()\\n#2 \\\/usr\\\/share\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(27): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateCalendars()\\n#3 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/installer.php(621): include('\\\/usr\\\/share\\\/ownc...')\\n#4 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/usr\\\/share\\\/ownc...')\\n#5 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/usr\\\/share\\\/owncloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/usr\\\/share\\\/owncloud\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/usr\\\/share\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/usr\\\/share\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/calendaradapter.php\",\"Line\":68}","level":3,"time":"2016-04-06T22:53:01+00:00"}
{"reqId":"<scrubbed>","remoteAddr":"<scrubbed>","app":"PHP","message":"Undefined index: newVersionString at \/usr\/share\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-04-06T22:53:33+00:00"}
{"reqId":"<scrubbed>","remoteAddr":"<scrubbed>","app":"core","message":"Authentication cookie rejected for user <scrubbed>","level":2,"time":"2016-04-07T13:19:24+00:00"}
{"reqId":"<scrubbed>","remoteAddr":"<scrubbed>","app":"PHP","message":"Undefined index: newVersionString at \/usr\/share\/owncloud\/apps\/updatenotification\/templates\/admin.php#8","level":3,"time":"2016-04-07T13:36:16+00:00"}

#### Browser log
http://s22.postimg.org/kam5t4wpd/auth.png
Internet Explorer indicates a problem authenticating to Sabre/Dav.

**Comment by LukasReschke** [comment]
Can you retry with 9.0.1?

**Comment by LukasReschke** [comment]
=> https://owncloud.org/install/#testing-development

**Comment by ownbug** [comment]
Tested with 9.0.1RC2.
Same issue occurs.

**Comment by inpos** [comment]
9.0.1.3
Same issue

**Comment by ownbug** [comment]
Where did you get 9.0.1.3?

**Comment by inpos** [comment]
Same issue #23754

**Comment by inpos** [comment]
`root@cloud:/var/www/owncloud# cat version.php 
<?php 
$OC_Version = array(9,0,1,3);
$OC_VersionString = '9.0.1';`

Debian Jessie with official owncloud repo

**Comment by ownbug** [comment]
I see the gallery errors, but the issue occurs even if it's disabled:

Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - firstrunwizard: 1.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - files_videoplayer
  - gallery
  - templateeditor
  - user_external
  - user_ldap

**Comment by LukasReschke** [comment]
@ownbug @inpos Could you create a public share protected via password and share this? If you don't want to disclose your domain name you can find my mail address in my profile.

**Comment by ownbug** [comment]
Link sent directly to your email.

**Comment by inpos** [comment]
@LukasReschke Sent email

**Comment by DylannCordel** [comment]
Its a duplicate of #23754 opened 6 days ago.
Maybe you should close this one to prevent duplicate corrections ?

**Comment by inpos** [comment]
after upgrade packages I run occ upgrade and get
`Updated <dav> to 0.1.6`
`Exception: Sharing backend for file not found`
`Update failed`

And record from log:
`Apr  8 23:19:47 qnap ownCloud[14433]: {core} Exception: {"Exception":"Exception","Message":"Sharing backend for file not found","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/share\/share.php(1658): OC\\Share\\Share::getBackend('file')\n#1 ... `

May be it helps

**Comment by inpos** [comment]
repeat occ upgrade finished successful

**Comment by inpos** [comment]
Today I git clone from master and replace files in /var/www/owncloud
Issue has gone.
Current commit https://github.com/owncloud/core/commit/8e16e7bf34efb1bd7d97ee500ffe860d94fa55eb

**Comment by ownbug** [comment]
Issue resolved.

**Comment by RealRancor** [comment]
Refs: https://github.com/owncloud/core/issues/23754, https://github.com/owncloud/core/issues/23066

**Comment by inpos** [comment]
upgrade to 9.0.2-1.1 on Debian Jessie.
Same issue

**Comment by RealRancor** [comment]
@inpos https://github.com/owncloud/core/issues/23066

**Comment by kdslkdsaldsal** [comment]
@ncsatech  As you're running nextcloud you're mostly wrong in this issue tracker. Try it in the nextcloud issue tracker if you want infos about this topic.
