### ISSUE TITLE
Contacts and calendar apps disabled after upgrade to 9.0.1

### ISSUE THREAD

**Issue by codethief** [owncloud/core#23853]
### Steps to reproduce
1. Install ownCloud 9.0.0
2. Enable contacts and calendar apps, add some contacts & calendars / dates
3. Upgrade to ownCloud 9.0.1 using apt-get and ./occ upgrade

### Expected behaviour
The apps "contacts and calendar" should stay enabled (or get reenabled once the upgrade is finished).

### Actual behaviour
The contacts and calendar app got disabled (the data has been preserved, though). I only noticed this by chance (namely because I wanted to edit a contact through the web interface after the upgrade). The output of `./occ upgrade` (see below) was *all green*, which – at least to me – suggested that everything worked fine and I wouldn't need to look at the output carefully, let alone reenable the apps again.

### Server configuration
**Operating system**: Debian 8.4 (Jessie)

**Web server:** nginx 1.6.2

**Database:** MySQL 5.5.47

**PHP version:** PHP 5.6.19

**ownCloud version:** 9.0.1

**Updated from an older ownCloud or fresh install:**
Installed ownCloud 9.0.0 fresh from the Debian repositories (https://download.owncloud.org/download/repositories/stable/owncloud/); upgraded to 9.0.1 using apt-get and `./occ upgrade`

**Integrity test**
Output from http://example.com/index.php/settings/integrity/failed:
```
No errors have been found.
```

**List of activated apps:**
(After enabling contacts and calendar again)

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - contacts: 1.1.0.0
  - dav: 0.1.6
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - comments
  - external
  - files_external
  - systemtags
  - user_external
  - user_ldap
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

### Client configuration
**Browser:** Firefox

**Operating system:** Ubuntu

#### Web server error log
Nothing relevant

#### ownCloud log (data/owncloud.log)
```
{"reqId":"B+iteWRYqNoTMbwWq0fu","remoteAddr":"","app":"core","message":"starting upgrade from 9.0.0.19 to 9.0.1.3","level":0,"time":"2016-04-08T05:52:30+00:00","method":"--","url":"--","user":"--"}
{"reqId":"\/+sxZqzw\/MG9lkrApNJV","remoteAddr":"#####","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-04-08T05:58:40+00:00","method":"POST","url":"\/data\/index.php\/apps\/calendar\/v1\/view","user":"#####"}
{"reqId":"hhC3rUnelotQCWPXT54R","remoteAddr":"#####","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-04-08T06:05:56+00:00","method":"POST","url":"\/data\/index.php\/apps\/calendar\/v1\/view","user":"#####"}
```

#### Output of `./occ upgrade`

```
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checking whether the database schema for <dav> can be updated (this can take a long time depending on the database size)
Checked database schema update for apps
Updating database schema
Updated database
Disabled 3rd-party app: calendar <---------------------
Disabled 3rd-party app: contacts <---------------------
Updating <dav> ...
Updated <dav> to 0.1.6
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Reset log level
```

**Comment by RealRancor** [comment]
Hi,

disabling 3rd-party apps during an update/upgrade is the expected behaviour.

**Comment by codethief** [comment]
Oops, I guess I should've looked through more than just the first page of search results for "is:issue is:open apps disabled upgrade" here on GitHub. Thanks for the link!

**Comment by RealRancor** [comment]
When doing an update (e.g. 8.2.2 -> 8.2.3) and not an upgrade (e.g. 8.1.6 -> 8.2.3) it should be also safe to run ``occ upgrade`` with the ``--no-app-disable`` command: https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/occ_command.html#command-line-upgrade

**Comment by rullzer** [comment]
As said. Expected behaviour for now. Closing this.
