### ISSUE TITLE
Provide API for interaction with the LDAP backend

### ISSUE THREAD

**Issue by GitHubUser4234** [owncloud/core#23855]
_This is an enhancement I'm currently developing with mentorship from @blizzz :+1: , any suggestions for improvements or contributions are welcome._

Currently there's nothing that would let a thirdparty app interact with the LDAP backend. 

What we would need to do is to provide a public API in ownCloud core. The basic methods would be user centered:

**getLDAPAccess($uid)**: return the LDAP access for the specified user (since more than one LDAP server can be configured): This allows you to talk to the LDAP server and you do not need to worry about establishing connections and stuff 

**getUserDN($uid)**: translate an ownCloud username to the LDAP DN: This allows you to work with a user record. 

Those methods need to be specified in an interface "lib/public/ldap/ildapprovider.php", and a factory interface "lib/public/ldap/idapproviderfactory.php" needs to be offered which would return the provider.

There needs to be a default dummy implementation in core ("lib/private/provider.php" and "lib/private/providerfactory.php") that would just throw exceptions, and a real implementation in "apps/user_ldap/". When the real implemention of the provider is enabled in ownCloud's config.php and the user_ldap app is enabled, it should override the default implementation. 

The server ("lib/private/server.php") would provide an instance of that implementation by calling \OC::$server->getLDAPProvider() .

**Comment by GitHubUser4234** [comment]
I have committed the change:
[- Link of the commit ](https://github.com/GitHubUser4234/core/commit/3a4f0a1fc3b244d3a2866175458dbc6e105fbcf7)
[- Link of the repository](https://github.com/GitHubUser4234/core)

When calling the user_ldap provider from a testing app, I'm currently running into a problem occuring in the code snippet starting from [here](https://github.com/GitHubUser4234/core/blob/3a4f0a1fc3b244d3a2866175458dbc6e105fbcf7/apps/user_ldap/lib/ldapprovider.php#L37), somehow the 'LDAP' backend is not in the loop, maybe because it is called before the 'LDAP' backend is registered?  I have tried to uninstall and install the testing app again, but to no avail. Maybe something is wrong with this approach.

@blizzz : Please have a look at the code, your suggestions are highly welcome :smiley:

**Comment by blizzz** [comment]
@GitHubUser4234 cool stuff :) I left some comments on the commit you linked to.  

Could you also open a pull request? On your repository page, click the green button "New pull request" and open one against the original core. This will help us discuss and track changes first (no need to go through single commits), and especially enables us to merge it later :rocket:

**Comment by GitHubUser4234** [comment]
@blizzz : thanks a lot for reviewing, the pull request is created here: #23992

I have also added a comment for the problem described above [here](https://github.com/owncloud/core/pull/23992/files#diff-b52a867507df3671826c58dfd9c46512R43).

**Comment by blizzz** [comment]
@GitHubUser4234 superb, I am going to look at it tomorrow.

**Comment by PVince81** [comment]
PR was abandoned by submitter. If there is still interest in this feature, please reopen in the user_ldap repo @butonic
