### ISSUE TITLE
openSUSE Leap (possibly other version) packaging error

### ISSUE THREAD

**Issue by StopTrain** [owncloud/core#23850]
I had been dealing with an odd FollowSymLinks issue within my apache installation on openSUSE Leap 42.1 for quite a while. 

Upgraded to 9.0.1 and had the same issue.  Further digging revealed an issue in /etc/apache2/conf.d/owncloud.conf

Every path referring to /srv/www/htdocs/owncloud/owncloud had to be updated for it to work.

Each path, remove the extra owncloud so it looks like this: /srv/www/htdocs/owncloud

Restart apache, whammo.. all working!

here's the original owncloud.conf that I saw:

Alias /owncloud "/srv/www/htdocs/owncloud/owncloud/"
<Directory "/srv/www/htdocs/owncloud/owncloud">
  Options +FollowSymLinks
  AllowOverride All

  <IfModule mod_dav.c>
        Dav off
  </IfModule>

  SetEnv HOME /srv/www/htdocs/owncloud/owncloud
  SetEnv HTTP_HOME /srv/www/htdocs/owncloud/owncloud
</Directory>

<Directory "/srv/www/htdocs/owncloud/owncloud/data/">
  # just in case if .htaccess gets disabled
    Require all denied
</Directory>

**Comment by Xenopathic** [comment]
cc @jnweiger

**Comment by PVince81** [comment]
@owncloud/packaging

**Comment by crrodriguez** [comment]
cleaning up.. no such problem exist in current owncloud packages at all. the default apache configuration does not include duplicated "owncloud" paths.
