### ISSUE TITLE
Admin settings: order of navigation and content doesn’t match

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#23859]
Check out the navigation and content order:
![capture du 2016-04-08 14-43-42](https://cloud.githubusercontent.com/assets/925062/14383926/634a8b44-fd98-11e5-87f5-e1e39ce7888f.png)
In the navigation it’s Encryption, Federation etc., but in the content it’s encryption, Mail server, Log etc.

@schiesbn @PVince81 any idea?

**Comment by PVince81** [comment]
Still happening on 9.2 with non-english locale

**Comment by DeepDiver1975** [comment]
For oc 10 this should work properly - let's reopen in case it does not
