### ISSUE TITLE
carddav causes high server load and won't sync

### ISSUE THREAD

**Issue by dh-connect** [owncloud/core#23866]
### Steps to reproduce
1. try to load carddav address book after upgrade from oc 8.2.3.2 to 9.0.1.3
2. same behavior in webfrontend with latest contact app as well as in carddav client, spinning wheel with no response
3. causes timeout after several minutes, high load on server 10-20 apache2 processes with full cpu usages when trying to access contacts

no error in owncloud log

error from carddav client:
Der Vorgang konnte nicht abgeschlossen werden. (CoreDAVErrorDomain-Fehler 1.)

### Expected behaviour
show addressbook

### Actual behaviour
no response and timeout

### Server configuration
**Operating system**: Debian, Linux raspberrypi 4.1.19-v7+

**Web server:** Apache/2.4.10 (Raspbian)

**Database:** MySQL 5.5.44-0+deb8u1-log - (Raspbian)

**PHP version:** PHP 5.6.19-0+deb8u1 (cli)

**ownCloud version:** (see ownCloud admin page) 9.0.1 stable

**Updated from an older ownCloud or fresh install:** updated from 8.2.3.2

**Where did you install ownCloud from:** manual install from owncloud.org

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder


Enabled:
  - activity: 2.2.1
  - announcementcenter: 1.1.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.1.0.0
  - dav: 0.1.6
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - logreader: 1.1.2
  - mail: 0.4.1
  - mozilla_sync: 1.4
  - music: 0.3.10
  - news: 8.2.0
  - notes: 2.0.1
  - notifications: 0.2.3
  - ocsms: 1.6.3
  - ownbackup: 0.3.8
  - passwords: 18.0
  - provisioning_api: 0.4.1
  - qownnotesapi: 0.4.3
  - systemtags: 0.2
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
  - weather: 1.3.1
Disabled:
  - encryption
  - files_mv
  - user_ldap

```

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)


**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => '10.0.0.10',
    1 => 'xxx',
    2 => 'xxx',
    3 => 'xxx',
    4 => '10.8.0.1',
  ),
  'trusted_proxies' => 
  array (
    0 => '192.168.0.1',
    1 => '10.0.0.1',
  ),
 'datadirectory' => '/data/ownclouddata/ocd',
  'overwrite.cli.url' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'oc9',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
 'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'xxx',
  'mail_domain' => 'xxx',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'xxx',
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
  'appstore.experimental.enabled' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
  ),
  'cache_path' => '/data/ownclouddata/ocd/cache',
  'mail_smtpport' => '587',
  'app.mail.server-side-cache.enabled' => true,
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 45.0.1

**Operating system:** Mac OSX 10.11.4

#### Web server error log
```
Insert your webserver log here

no error in apache error.log

```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here

no error in owncloud.log
```

#### Browser log
```
Insert your browser log here, this could for example include:

```

**Comment by DeepDiver1975** [comment]
How many contacts are in how many addressbooks?

The observation is quite understandable regarding the contacts web ui - we are working on a much less resource consuming behavior.

For the carddav client (Apple Addressbook on MacOS I assume) this would be only understandable on an initial load of hugh addressbooks

**Comment by dh-connect** [comment]
I have 200 contacts in my address book ( 10 MB vcard file )
but I have more users with address books, 250 entries in card table, 1600 entries in card properties table, I let it run over night but still no response
yes, I'm using apple addressbook

**Comment by dh-connect** [comment]
i have 10 entries in addressbooks table

**Comment by dh-connect** [comment]
maybe corrupt data in the tables which causes problems?

**Comment by dh-connect** [comment]
it works now, I deleted all contacts from the tables
(I also made a copy of the tables before)
delete FROM `oc_cards` WHERE `addressbookid` = x;
delete FROM `oc_cards_properties` where `addressbookid` = x;

and used the Mac Adressbook  App to import the vcard data file,
I could see that the server filled the card and card properties table in the background

After the sync was done I could also see the contacts in the oc contacts web app,
the carddav sync to my phone works also now,
so I guess something went wrong with the data migration from 8 to 9.

**Comment by PVince81** [comment]
@DeepDiver1975 information was provided above

**Comment by DeepDiver1975** [comment]
> After the sync was done I could also see the contacts in the oc contacts web app,
> the carddav sync to my phone works also now,
> so I guess something went wrong with the data migration from 8 to 9.

Good to hear it is working again .... any chance to compare the database content before and after your cleanup operation?

**Comment by dh-connect** [comment]
sorry don't have the old database anymore

**Comment by PVince81** [comment]
Hmm okay. Closing the ticket then, probably was due to corrupt database like you said.
