### ISSUE TITLE
missing email template

### ISSUE THREAD

**Issue by Tealk144** [owncloud/core#23865]
Steps to reproduce
I select the template to edit

Server configuration
**Operating system:** Debian 8.0 jessie minimal
**Web server:** Apache/2.4.10 (Debian)
**Database:** mysqlnd 5.0.11
**PHP version:** 5.6.17-0+deb8u1
**ownCloud version (see ownCloud admin page):** 9.0.0 (stable)
**Updated from an older ownCloud or fresh install:** No
**ownCloud log (data/owncloud.log):** nothing
![a0pwo4z_700b_v1](https://cloud.githubusercontent.com/assets/12276250/14385360/4fee1ffe-fda0-11e5-85f9-984b7a5f857e.jpg)
**Special configuration** (external storage, external authentication, reverse proxy, server-side-encryption): server-side-encryption

**Comment by DeepDiver1975** [comment]
please reoping in http://github.com/owncloud/templateeditor
