### ISSUE TITLE
Upgrade from 9.0.0-2.1 to 9.0.1-1.1 (/var/www/owncloud/apps/dav/appinfo/application.php on line 222)

### ISSUE THREAD

**Issue by cFire** [owncloud/core#23870]
### Steps to reproduce
1. Installed owncloud 9.0.0-2.1 from debian package repo
2. apt-get upgrade to 9.0.1-1.1
3. as user www-data run php occ upgrade

### Expected behaviour
Upgrade proceeds as normal

### Actual behaviour
$ php occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checking whether the database schema for <dav> can be updated (this can take a long time depending on the database size)
Checked database schema update for apps
Updating database schema
Updated database
Disabled 3rd-party app: calendar
Disabled 3rd-party app: contacts
Disabled 3rd-party app: html5_videoplayer
Disabled 3rd-party app: music
Updating <dav> ...
PHP Fatal error:  Call to a member function getUID() on null in /var/www/owncloud/apps/dav/appinfo/application.php on line 222
$ 

### Server configuration
**Operating system:**
Debian GNU/Linux 8.4 (jessie)

**Web server:**
Apache/2.4.10

**Database:**
MySQL 5.5.47-0+deb8u1

**PHP version:**
PHP 5.5.47-0+deb8u1

**ownCloud version:**
9.0.1 (stable)

**Updated from an older ownCloud or fresh install:**
Updating from 9.0.0-2.1

**Where did you install ownCloud from:**
http://download.owncloud.org/download/repositories/stable/Debian_8.0/

**Signing status (ownCloud 9.0 and above):**
It's kind of a long list, if it's relevant for this issue, let me know and I'll paste it. (Note: There were a lot of failed checks in the version I was upgrading from too.)

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.1.0.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - music: 0.3.10
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
  - user_pwauth: 2.3
Disabled:
  - bookmarks
  - documents
  - encryption
  - external
  - files_external
  - html5_videoplayer
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "occc748d18e6",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/home\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "updatechecker": false,
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** 
All storage is local fs

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:** 
Unix user backend

### Client configuration
**Browser:**
N/A

**Operating system:**
N/A

#### Web server error log
```
No errors for this vhost
```

#### ownCloud log (data/owncloud.log)
Several entries similar to this one. Will paste more if useful.
```
{"reqId":"h3tG\/Q3JKvzIlUrbZAYl","remoteAddr":"***redacted***","app":"PHP","message":"Doctrine\\DBAL\\Exception\\TableNotFoundException: An exception occurred while executing 'SELECT * FROM `oc_notifications` WHERE `user` = ? ORDER BY `notification_id` DESC LIMIT 25' with params [\"***redacted***\"]:\n\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.oc_notifications' doesn't exist at \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php#53","level":3,"time":"2016-04-08T16:07:16+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"***redacted***"}
```

#### Browser log
```
N/A
```

**Comment by cFire** [comment]
I've done a temporary workaround in /var/www/owncloud/apps/dav/appinfo/application.php on line 222 to let the upgrade proceed:
```diff
- $migration->syncUser($user->getUID());
+ if($user != null) $migration->syncUser($user->getUID());
```

Obviously this is quite risky as I don't know why $user was null in the first place and the migration might not happen correctly.

**Comment by LukasReschke** [comment]
cc @DeepDiver1975

**Comment by nickvergessen** [comment]
Already backported for 9.0.2: https://github.com/owncloud/core/pull/23837
