### ISSUE TITLE
calendars and contacts after migration not shown

### ISSUE THREAD

**Issue by al-Iskandar** [owncloud/core#23872]
After Upgrade from OC 8.2.3 to OC 9.0.1 calendars and contacts are not shown although the migration scripts have been executed and although the database check according to http://morrisjobke.de/2016/03/07/ownCloud-9.0-calendar-migration-analysis/ shows the wished results no calendars or contacts are shown.
If I open the calendar app there are no calendars, no entries, only the plain calendar, and I cannot create a new calendar.
If I open the contacts app the app is loading and loading without end and result.
### Server configuration

**Operating system**: Debian 3.2.73

**Web server:**

**Database:** mysql (mysqlnd 5.0.12)

**PHP version:** 7.0.4

**ownCloud version:** (see ownCloud admin page): 9.0.1 (alos 9.0.0)

**Updated from an older ownCloud or fresh install:** Updated from 8.2.3

**Where did you install ownCloud from:** Official download from ownloud.org

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:** Fireforx / IronSQ

**Operating system:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
Hi,

sure you're runnig Debian 3.2.73 ?

**Comment by al-Iskandar** [comment]
According to php-info (C&P): I am not the administrator of the Server (shared whosting)

**Comment by RealRancor** [comment]
Ahh, thats Debian Wheezy. Shouldn't be affected by the outdated libxml2 issue.

- Which browser are you using?
- Are you getting an message about a not working WebDAV interface in your admin backend?
- Are calendar and contacts clients able to sync?

**Comment by al-Iskandar** [comment]
I tested with Firefox 45.0.1 and SRWare Iron 39.0.2100.0 (based on Chromium) for excluding the browser.
I copied the part of the owncloud.log from yesterday as attachment (with anonymised IPs and Usernames).

I did not test a client, also I made a roleback of my installation after some hours of despaired trial: I hope to find time for a new test at Monday.

[owncloud.log.txt](https://github.com/owncloud/core/files/211333/owncloud.log.txt)

**Comment by RealRancor** [comment]
Please empty your logfile and then open the contacts and calendar app to get only the relevant logentries. The current attached file is a way too large to be useful.

**Comment by al-Iskandar** [comment]
The following file has just the logs from the upgrade to the tests of calendar and contacts:

[owncloud.log-2.txt](https://github.com/owncloud/core/files/211876/owncloud.log-2.txt)


A trial with calendar app of Thunderbird was without success, the client could not access to any calendar.

**Comment by nickvergessen** [comment]
Are you using the new calendar and contacts app?

**Comment by al-Iskandar** [comment]
I deleted all files in the old owncloud directory (except the config.ini and the external stored directory data). Then I copied the files of the new version. After the database update and the first login I activated the calendar and contacts app from "inactive apps". It was in both cases version v1.x. So I think, I got the  new, internal, apps.

**Comment by whoshonky** [comment]
same here.
update from 8.2.2.2 to 9.0.2 though.
reactivated calendar and contacts and all content is missing.

**Comment by LukasReschke** [comment]
cc @DeepDiver1975

**Comment by al-Iskandar** [comment]
Still the same problem from v8.2.6 to 9.0.3

**Comment by whoshonky** [comment]
any news?

**Comment by DeepDiver1975** [comment]
You can manually migrate addressbooks and calendars using

```sh

/occ dav:migrate-calendars USERNAME

**Comment by al-Iskandar** [comment]
But this is not the solution, because according to http://morrisjobke.de/2016/03/07/ownCloud-9.0-calendar-migration-analysis/ the migration was made and also the manual migration according to that page did not work

**Comment by whoshonky** [comment]
@DeepDiver1975 Do you know if I can manually transfer the SQLite3 calendar and contact tables into the MySQL database that OwnCloud is using now?

**Comment by PVince81** [comment]
@whoshonky you can probably copy your sqlite instance, then run "db:convert-type" to convert the database to MySQL. If you're only interested in the calendar/contact tables, then pick these out of the MySQL dump.

**Comment by PVince81** [comment]
Closing as this is old and refers to old ownCloud versions. There were many fixes for caldav / carddav logic so it is likely this is fixed already. If the problem reappears for recent OC versions, feel free to reopen.
