### ISSUE TITLE
CalDAV CardDAV: add display name to list of sharees

### ISSUE THREAD

**Issue by georgehrke** [owncloud/core#23877]
Something like:
```
     <d:ace>
      <d:principal>
       <d:href>/remote.php/dav/principals/users/test1/</d:href>
       <oc:displayname>Test 1</oc:displayname>
      </d:principal>
      <d:grant>
       <d:privilege>
        <d:write-properties/>
       </d:privilege>
      </d:grant>
      <d:protected/>
     </d:ace>
     <d:ace>
      <d:principal>
       <d:href>/remote.php/dav/principals/users/test2/</d:href>
       <oc:displayname>Test 2</oc:displayname>
      </d:principal>
      <d:grant>
       <d:privilege>
        <d:read/>
       </d:privilege>
      </d:grant>
      <d:protected/>
     </d:ace>
```

**Comment by georgehrke** [comment]
cc @DeepDiver1975 @Henni

**Comment by DeepDiver1975** [comment]
There is an explicit list of sharees already which holds the displayname.

**Comment by georgehrke** [comment]
Can you point me to it please? :)

**Comment by DeepDiver1975** [comment]
here is the displayname filled - https://github.com/owncloud/core/blob/master/apps/dav/lib/dav/sharing/backend.php#L161

**Comment by DeepDiver1975** [comment]
this is the prop to ask for in the propfind: https://github.com/owncloud/core/blob/master/apps/dav/lib/dav/sharing/plugin.php#L191

**Comment by DeepDiver1975** [comment]
sample propfind - https://github.com/owncloud/core/blob/master/apps/dav/tests/travis/caldavtest/data/Resource/CalDAV/sharing/calendars/read-write/5.xml

**Comment by georgehrke** [comment]
Thx a lot :)
