### ISSUE TITLE
UTF glyphe does not work with comments

### ISSUE THREAD

**Issue by dragotin** [owncloud/core#23871]
ownCloud Server 9.0.0: If I paste a UTF 8 glyphe into the comments field, the web interface responds with the error message `[object Object]` and does not save the comment.

Comment: 😪 for example.

Error message: 
![3byteutf8](https://cloud.githubusercontent.com/assets/1070214/14390477/8c7a61e6-fdb7-11e5-8854-089f9f8bad6a.png)

**Comment by DeepDiver1975** [comment]
MySQL?
Which glyph? 4 Bytes?

**Comment by dragotin** [comment]
Yes, MySQL, but I don't think its a four byte glyphe. It was the one in the comment above that was unfortunately converted by github. Just try to paste a couple, you will see it failing soon. I dont think its the mysql problem with four byters.

**Comment by DeepDiver1975** [comment]
If it is a 4byte glyth - it's related to MySQL because we use a 3 Byte Charset.

**Comment by nickvergessen** [comment]
Well at least the error message should be better.

**Comment by nickvergessen** [comment]
happens for all dav errors

**Comment by dragotin** [comment]
I am not able to reproduce this with a 3 byte glyph, so it's probably only the mysql problem. Feel free to close, or fix the error message.

**Comment by DeepDiver1975** [comment]
fixing the error message should be taken care of

**Comment by PVince81** [comment]
Problem is: we currently don't parse Sabre exceptions because the library didn't support it, needs additional work: https://github.com/owncloud/core/issues/24304

The only thing I can do right now is show a generic message "Error occurred while posting message"

**Comment by PVince81** [comment]
PR for generic error message here https://github.com/owncloud/core/pull/25257
