### ISSUE TITLE
Remove mbstring.func_overload from PHP user configs

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#23874]
You cannot set `mbstring.func_overload` in htaccess or user.ini. See this for details:
https://secure.php.net/manual/en/mbstring.configuration.php

@LukasReschke @MorrisJobke

**Comment by oparoz** [comment]
And `always_populate_raw_post_data` is a < PHP7 only setting.

**Comment by Prakharsvnit** [comment]
@PVince81 @oparoz I'm confused whether you want to remove mbstring.func_overload from .user.ini or assign some value to it.AFAIK php_value of mbstring.func_overload is set to zero in both .htaccess and .user.ini .
