### ISSUE TITLE
Resharing in calender, contacts, etc.

### ISSUE THREAD

**Issue by jc97** [owncloud/core#23882]
Hello everybody,

please think about restricting the possibility of editing the share-configuration of shared calendars, especially if the recipient have no write-access or the option "resharing" on the admin page is disabled. 
See also https://github.com/owncloud/calendar/issues/430

**Comment by georgehrke** [comment]
cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
I suggest to to allow resharing as soon as a user has write access.

objections? @jancborchardt @georgehrke

**Comment by jc97** [comment]
I would at least suggest to consider the option "Allow resharing" on the admin page.
But: Recipients of shares should NEVER be able to remove other users from the share or change the permissions of other recipients.

**Comment by jancborchardt** [comment]
Agree with @DeepDiver1975 – let’s keep it simple in the first pass and simply allow resharing when someone has write permissions.

**Comment by jc97** [comment]
> simply allow resharing

so you mean, this users will only be able to add new shares?

> I would at least suggest to consider the option "Allow resharing" on the admin page.

When the restriction just considers the write permission (like DeepDiver1975 suggested) , then this is implemented by just one or two additional lines, isn't it?

**Comment by jancborchardt** [comment]
> so you mean, this users will only be able to add new shares?

No, that means that they will be able to manage the sharing. As sharing is not a chain but rather a pool, as we redesigned it in core as well.

**Comment by DeepDiver1975** [comment]
This is already implemented accordingly - write access is required to perform a share action
https://github.com/owncloud/core/blob/master/apps/dav/lib/dav/sharing/plugin.php#L163

Please reopen in case you have an explicit case where this is not behaving accordingly. THX
