### ISSUE TITLE
question: how to fix code signing problems?

### ISSUE THREAD

**Issue by dh-connect** [owncloud/core#23886]
My .htaccess in owncloud was worng, wrong path and I also changed upload size.

After that I got a problem with code signing with the mentioned files,
so I changed the hash in owncloud/core/signature.json

After doing that the code signing for core doesn't seem to work anymore:

How do you fix that problem?

```

Results
=======
- core
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature could not get verified.

Raw output
==========
Array
(
    [core] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature could not get verified.
                )

        )

)
```

**Comment by RealRancor** [comment]
Hi,

there is a big red warning "Please don’t modify the mentioned signature.json itself." at https://doc.owncloud.org/server/9.0/admin_manual/issues/code_signing.html

To get support fixing what you broke ask at e.g. the forums.

**Comment by dh-connect** [comment]
I saw that and also read the warning, but how do you fix it when you can't change the hash?

**Comment by RealRancor** [comment]
Please ask such questions at the forums as already advised. This issue tracker isn't the place to give support.

**Comment by dh-connect** [comment]
well okay thanks for the hint, but maybe it is also a software problem when a .htaccess file is signed which needs to be changed

**Comment by RealRancor** [comment]
@dh-connect ownCloud 9.0.1 has no issues if you're changing upload limits within the .htaccess

**Comment by dh-connect** [comment]
but changing the upload size causes the problem, because the setting is above that magic line 
#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
