### ISSUE TITLE
Updating to 9.0.1. filed - HELP! PLEASE

### ISSUE THREAD

**Issue by maxdevfud** [owncloud/core#23883]
Updating ownCloud to version 9.0.1, this may take a while.

Preparing update
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Starting code integrity check
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_appconfig` (`appid`,`configkey`,`configvalue`) SELECT ?,?,? FROM `oc_appconfig` WHERE `appid` = ? AND `configkey` = ? HAVING COUNT(*) = 0' with params ["core", "oc.integritycheck.checker", "[]", "core", "oc.integritycheck.checker"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
The update was unsuccessful. Please report this issue to the ownCloud community.

**Comment by RealRancor** [comment]
@maxdevfud Have you put the "MySQL server has gone away" message into your favorite search engine?

https://dev.mysql.com/doc/refman/5.7/en/gone-away.html

There are even some notes about that message available in the oC docs:

https://doc.owncloud.org/server/9.0/admin_manual/issues/general_troubleshooting.html#common-problems-error-messages

**Comment by maxdevfud** [comment]
Thanks. All sorted! Just ran it a couple of times till it went through. Might have been a problem on the side of my web host.
