### ISSUE TITLE
Wrong path in apache Alias directive (apache) in CentOS 7 

### ISSUE THREAD

**Issue by justinotherguy** [owncloud/core#23887]
### Steps to reproduce
1. install rpm packages for oc 9.0.1 from the repos indicated in https://download.owncloud.org/download/repositories/stable/owncloud/ into a cent os 7.2 running apache
2. "grep Alias /etc/httpd/conf.d/owncloud.conf" gives:
  Alias /owncloud "/var/www/html/owncloud/owncloud/"

### Expected behaviour
I would expect the grep to return
  Alias /owncloud "/var/www/html/owncloud/"
  ("owncloud" only once) as 
  a) /var/www/html/owncloud/owncloud/ does not exist (by default) and 
  b) /var/www/html/owncloud/ is the DocumentRoot

Please correct the config for the centos repo

### Actual behaviour
accessing http://<server>/ownloud results in a 404 error

### Server configuration
**Operating system**: CentOS 7.2 (7.2.1511)

**Web server:** Apache 2.4 (httpd-2.4.6-40.el7.centos.x86_64)

**Database:** irrelevant

**PHP version:** 5.4.16 (php-5.4.16-36.el7_1.x86_64)

**ownCloud version:** 9.0.1

**Updated from an older ownCloud or fresh install:**: no

**Where did you install ownCloud from:** http://download.owncloud.org/download/repositories/stable/CentOS_7/ce:stable.repo (taken from https://download.owncloud.org/download/repositories/stable/owncloud/)

**Signing status (ownCloud 9.0 and above):** ?

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
``` -> failing on the way already

**List of activated apps:** see above: n/a

**The content of config/config.php:** (empty file)


**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** irrelevant

**Operating system:** irrelevant

### Logs
#### Web server error log
no entries through this

access log says:
::1 - - [10/Apr/2016:00:43:21 +0200] "GET /owncloud/index.php HTTP/1.1" 404 216 "-" "Mozilla/5.0 (X11; Linux x86_64; r
v:38.0) Gecko/20100101 Firefox/38.0"

Let me know if you need further details.

Great project, BTW :)

**Comment by LukasReschke** [comment]
cc @jnweiger

**Comment by jnweiger** [comment]
Templates fixed. The change will appear in 9.0.2 packages.

**Comment by justinotherguy** [comment]
Great - thx! :)

**Comment by pminkler** [comment]
@jnweiger I'd really appreciate having this change ASAP.  Are you able to rebuild it into the current package?  If not, do you know when would 9.0.2 be released?

**Comment by jnweiger** [comment]
The original fix was only half a fix. We have the config file in both owncloud-files and owncloud (so that we care order independant)
