### ISSUE TITLE
Add try-catch to all image operations which require a large amount of memory

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#23889]
### Steps to reproduce
1. Set a low memory limit in PHP
2. Upload a large JPEG
3. Open the ownCloud log

### Expected behaviour
I should see a thumbnail

### Actual behaviour
I get the media type icon and this in the logs
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes) in /snaps/owncloud.sideload/LVnYLRhPbbMD/htdocs/lib/private/image.php on line 427`

The solution is probably to add a try catch to https://github.com/owncloud/core/blob/master/lib/private/image.php#L427
and all resizing operations.

See the PHP 7 doc: https://secure.php.net/manual/en/language.errors.php7.php

@georgehrke @icewind1991 

### Server configuration

**PHP version:** Any

**ownCloud version:** 9

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** owncloud-snap

**Comment by Xenopathic** [comment]
Unfortunately it's impossible to catch fatal errors in PHP :cry:

**Comment by oparoz** [comment]
@Xenopathic - You're wrong, it's possible since ownCloud 9.0 ;)

**Comment by oparoz** [comment]
Just realised, I didn't paste the link in the OP: https://secure.php.net/manual/en/class.error.php

**Comment by Xenopathic** [comment]
So only for PHP 7 then? We need to support PHP 5.x for a long time yet...

**Comment by oparoz** [comment]
>So only for PHP 7 then?

@Xenopathic - Nope, because now ownCloud includes the Symfony polyfill which means we can use some of PHP7's features today :)

**Comment by Xenopathic** [comment]
The key bit there is 'some of'. Catching fatal errors in PHP 5.x is impossible, they immediately terminate script execution.

**Comment by oparoz** [comment]
Well, the Symfony team believes they've figured it out, but I haven't tested it yet.

**Comment by oparoz** [comment]
https://github.com/symfony/polyfill-php70

**Comment by Xenopathic** [comment]
Actually, from what I've been reading, it looks like out of memory errors in PHP 7 do not get thrown as objects, but just directly trigger the error like in PHP 5.x (http://developers-club.com/posts/261451/ https://trowski.com/2015/06/24/throwable-exceptions-and-errors-in-php7/). So back to my original statement - this is impossible.

**Comment by oparoz** [comment]
Argh, you're right. Neither the PHP site nor the Symphony repo mention it clearly, but it seems that's a class of errors for which they weren't able to implement a catcher. I thought they somehow managed to introduce a buffer, but that out of memory error probably won't ever be solved...
