### ISSUE TITLE
How to use Pretty URL ?

### ISSUE THREAD

**Issue by messi89** [owncloud/core#23880]
Hi guys

Is the "pretty URLs" available on the owncloud 9.1.0 pre alpha (git) ? If yes, how to enable it on Apache2 ?

Thanks

**Comment by DeepDiver1975** [comment]
@LukasReschke looks like some documentation is missing about this part
CC @carlaschroder

**Comment by LukasReschke** [comment]
Have the `.htaccess` writable at installation and use the web to install and update your ownCloud. – All will be done automatically then.

If that is not possible check https://github.com/owncloud/core/blob/v9.0.1/lib/private/setup.php#L422-L432, but be aware that any custom modifications made to your web server config can break whatever you do. So better just have the file writable and use the web installer.

**Comment by messi89** [comment]
I never use web updater, I use git pull with occ upgrade

how to update with web ? (on the admin owncloud say that I have the last version)

**Comment by carlaschroder** [comment]
So...I am lost. What am I documenting?

**Comment by LukasReschke** [comment]
@carlaschroder Have `.htaccess` writable, have `mod_env` installed, have `mod_rewrite` installed and `overwrite.cli.url` has to be non-null in config.php. Then it is working.

**Comment by carlaschroder** [comment]
Thanks @LukasReschke

**Comment by carlaschroder** [comment]
master: 552b991d8223781347
stable9: caf52f9ef630c65fff

**Comment by messi89** [comment]
I add this to my htaccess
`<IfModule mod_rewrite.c> 
	RewriteRule . index.php [PT,E=PATH_INFO:$1]
	<IfModule mod_env.c>
		SetEnv front_controller_active true
		<IfModule mod_dir.c>
			DirectorySlash off
		</IfModule>
	</IfModule>
</IfModule>`

rewrite work but webdav (desktop client got a method not allow from remote.php/webdav)

when I execute 
`sudo -u www-data php occ maintenance:update:htaccess`

rewrite is deleted
