### ISSUE TITLE
download 6.x series links are broken

### ISSUE THREAD

**Issue by bulletxt** [owncloud/core#23885]
hi, as topic says download links from https://owncloud.org/changelog/#latest6 are broken, example: https://download.owncloud.org/community/owncloud-6.0.9.zip

I had a server on production (which never had problems after >2 years!!!) but decided to update it. Since it was 6.0.3 I wanted to first update it 6.0.9 and then go to 7 but as said link is broken.

Luckly I was able to still update to 7 without issues but still, links should get fixed 

thanks

**Comment by tflidd** [comment]
Sorry for hijacking this, but it concerns the same page and probably can be done at the same time:

The anchor to the latest 8-version is missing (the link within the document, the one you click on the top of the page in order to jump to the latest maintenance release): https://owncloud.org/changelog/#latest8.0

**Comment by RealRancor** [comment]
@tflidd I think that should be reported separately at https://github.com/owncloud/owncloud.org/issues as the issue about the missing file don't need changes to the page. It normally only need a re-upload of those missing files.

**Comment by RealRancor** [comment]
@LukasReschke I think this should be still kept open. At least the latest release of each branch should be available for download.

**Comment by tflidd** [comment]
I created a new issue: https://github.com/owncloud/owncloud.org/issues/928

**Comment by bulletxt** [comment]
Why is this closed?  https://download.owncloud.org/community/owncloud-6.0.9.tar.bz2 is not working yet.

**Comment by jobisoft** [comment]
Why is this closed? I was given an old 6.0.1 series owncloud instance and I cannot upgrade, because I cannot find 6.0.4/6/9, which I need before upgrading to 7. Any help?

**Comment by LukasReschke** [comment]
cc @karlitschek @cmonteroluque Anything that we can do about this?

**Comment by karlitschek** [comment]
try this link: https://download.owncloud.org/community/6/owncloud-6.0.9.tar.bz2

**Comment by jobisoft** [comment]
worked, thanks!

**Comment by RealRancor** [comment]
What are the next steps here? Create a new issue at https://github.com/owncloud/owncloud.org/issues to get the links fixed?

**Comment by karlitschek** [comment]
It seems that some people move the old releases intentionally to a different location to prevent people from installing outdated and insecure releases.

**Comment by DeepDiver1975** [comment]
From my understanding we should keep all packages available for download - moving them away is not really helpful as we can see in this case.

**Comment by border0464111** [comment]
From ** https://download.owncloud.org/community/6/owncloud-6.0.2.tar.bz2   **
In ** versions.php  **
it say 
```

<?php 
$OC_Version = array(9,0,1,3);
$OC_VersionString = '9.0.1';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array(8,2);
$OC_Build = '2016-04-06T21:37:20+00:00 54fc92c37233d248de8da842352c43dffdfc5f8d';

```

**Comment by border0464111** [comment]
> It seems that some people move the old releases intentionally to a different location to prevent people from installing outdated and insecure releases.

Doing this while not supporting multiple versions upgrade is kinda non-sense.

**Comment by RealRancor** [comment]
@border0464111 For now you can use the 6.0.9 package linked here:

https://github.com/owncloud/core/issues/23885#issuecomment-208935582

The 6.0.2 package is not needed if you're doing an upgrade, you only need the latest version of the major branch.

**Comment by tflidd** [comment]
This is still broken, there are not many people with OC 5 but there are:
https://forum.owncloud.org/viewtopic.php?f=38&t=37175

**Comment by PVince81** [comment]
@owncloud/packaging is this still an issue ?

**Comment by crrodriguez** [comment]
This is no longer an issue, the webpage allows you to download ancient releases.
