### ISSUE TITLE
Time traveler's birthday causes database exception

### ISSUE THREAD

**Issue by suraia** [owncloud/core#23898]
A contact with a birthday far in the future (2081) causes a database exception.

### Steps to reproduce
1. Upgrade ownCloud instance with time traveler contact
2. Birthday calendar generation fails

The same should also happen if a contact is simply updated with a birthday in the future. I have not tested this, though.

### Expected behaviour
Not supporting birthdays this far in the future is probably okay but if it can not be created/updated, it should be skipped instead of causing an exception.

### Actual behaviour
The loop in generateBirthdays() does not finish due to the exception.

### Server configuration
**Database:** PostgreSQL 9.4.7
**PHP version:** 5.6.11
**ownCloud version:** 9.0.1
**Updated from an older ownCloud or fresh install:** Upgrade from 8.2.3
**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

#### ownCloud log (data/owncloud.log)
`Numeric value out of range: 7 ERROR:  value "3521923200" is out of range for type integer`

**Comment by DeepDiver1975** [comment]
Actually the same issue as this one - https://github.com/owncloud/core/issues/24221

**Comment by DeepDiver1975** [comment]
fixed with https://github.com/owncloud/core/pull/24238
