### ISSUE TITLE
An error is shown trying to create a text file

### ISSUE THREAD

**Issue by davitol** [owncloud/core#23905]
### Steps to reproduce

1. Create a txt file in files view

### Expected behaviour

The file can be created and edited

### Actual behaviour

An error is shown

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**"9.1.0.0","versionstring":"9.1.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - admin_audit: 0.7
  - comments: 0.2
  - dav: 0.1.6
  - encryption
  - enterprise_key: 0.1.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firewall: 2.3.0
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - windows_network_drive: 0.2.33
  - workflow: 0.1.3
Disabled:
  - announcementcenter
  - external
  - files_antivirus
  - files_drop
  - files_ldap_home
  - objectstore
  - password_policy
  - sharepoint
  - user_external
  - user_ldap
  - user_shibboleth

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
{"reqId":"tTGpW3C7KhemSGXg4XZF","remoteAddr":"82.159.139.58","app":"PHP","message":"fread(): Length parameter must be greater than 0 at \/opt\/owncloud\/lib\/private\/files\/storage\/local.php#182","level":3,"time":"2016-04-11T10:06:32+00:00","method":"GET","url":"\/index.php\/apps\/files_texteditor\/ajax\/loadfile?filename=lonle.txt&dir=%2F","user":"admin"}
```
### Client configuration

**browser**

 Firefox

![screen shot 2016-04-11 at 12 06 41](https://cloud.githubusercontent.com/assets/10596560/14423809/099eff24-ffde-11e5-9fdb-92f2c362ccf0.png)

**Comment by nickvergessen** [comment]
Already fixed in new master:
https://github.com/owncloud/core/pull/23860
