### ISSUE TITLE
WebDAV URL in file app points to old WebDAV endpoint

### ISSUE THREAD

**Issue by ghost** [owncloud/core#23904]
### Steps to reproduce
1. Open files app
2. Open "Settings" at the bottom left
3. See WebDAV URL
### Expected behaviour

WebDAV URL is pointing to the new oC9+ dav endpoint:
http://example.com/remote.php/dav/files/$USERNAME
### Actual behaviour

WebDAV URL is pointing to the old oC8.2 WebDAV endpoint:
http://example.com/remote.php/webdav/

Code where this happens: https://github.com/owncloud/core/blob/63b01a3616193bbf08dc5844058b0677c014c3d1/apps/files/templates/appnavigation.php#L20

**Comment by MorrisJobke** [comment]
cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
The 'old' webdav endpoint is still valid so this is no a bigger issue - but I guess in the life cycle of 9.1 we can switch ....

**Comment by PVince81** [comment]
First switch the web UI to use it: https://github.com/owncloud/core/pull/25494
When doing so, many issues were found which are now solved.

**Comment by PVince81** [comment]
PR: https://github.com/owncloud/core/pull/29653

**Comment by PVince81** [comment]
Can't close... Github bug 😱
