### ISSUE TITLE
upgrade sequence ...

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#23913]
# current sequence
1. increase log level
2. enable maintenance mode
3. check if major version is not skipped
4. update htaccess
5. protect data folder
6. fix .ocdata file
7. pre upgrade repair steps
8. simulate core database schema
9. simulate apps database schemas (compatible, shipped and upgradeable)
10. database schema migration core
11. disable incompatible apps
12. disable any shipped apps as well as session and authentication app types
13. upgrade current enabled apps (order 'authentication', 'filesystem', 'logging')
14. load all authentication apps
15. install new shipped apps
16. post upgrade repair steps
17. code integrity
18. disable maintenance mode
19. reset log level

**Comment by DeepDiver1975** [comment]
TODO:
- [ ] occ upgrade is either fully automated or interactive
- [ ] web upgrade remains as is basically
- [ ] disable web upgrade if more then 100 users are used (+ link to docs on how to cli)
- [ ] updater cli calls oc upgrade with interactive mode
- [ ] updater web uses an http api to trigger upgrade

**Comment by PVince81** [comment]
/me subscribes

CC @VicDeo

**Comment by MorrisJobke** [comment]
> disable web upgrade if more then 100 users are used (+ link to docs on how to cli) (#23922)

This does only work for internal users. LDAP users are not counted because the check for upgrade happens before loading the authentication apps. 🙈

**Comment by MorrisJobke** [comment]
Check: https://github.com/owncloud/core/blob/afad27fafd996f0e2e7117d9f431f9eb63736569/lib/base.php#L822-L822
Loading auth apps: https://github.com/owncloud/core/blob/afad27fafd996f0e2e7117d9f431f9eb63736569/lib/base.php#L841

**Comment by DeepDiver1975** [comment]
I know - but we cannot load all auth apps before performing this check - test if ldap is enabled and assume this is a big installation?

**Comment by MorrisJobke** [comment]
> I know - but we cannot load all auth apps before performing this check - test if ldap is enabled and assume this is a big installation?

What about user_shibboleth? I guess we need to do some tricks here before we have the general user table (but that is 9.2). I'm fine with hard coding those two apps.

**Comment by PVince81** [comment]
@VicDeo @DeepDiver1975 tick more boxes in https://github.com/owncloud/core/issues/23913#issuecomment-208329654 ?

**Comment by PVince81** [comment]
@VicDeo please update

**Comment by PVince81** [comment]
moved to backlog

or close ?

**Comment by PVince81** [comment]
closing as obsolete
