### ISSUE TITLE
Upgrade documentation has inconsistent user listed

### ISSUE THREAD

**Issue by schrauger** [owncloud/core#23927]
https://doc.owncloud.org/server/9.0/admin_manual/maintenance/manual_upgrade.html

Under Step 10 of the Manual ownCloud Upgrade section, the command to run specifies the `apache` user, when all the other steps list that user as `www-data`.

While some may have `apache` as the web directory owner, it should still be changed to `www-data` to be consistent with all of the other commands on that page. As it is now, it makes that specific command in Step 10 look like it is supposed to be run by a different user than all the other commands.

Examples: All commands but the one in step 10 use `www-data` as the user.

- `sudo -u www-data php occ maintenance:mode --on`
- <code>sudo -u <b>apache</b> php occ upgrade</code>
- `sudo -u www-data php occ maintenance:mode --off`
- `sudo -u www-data php console.php files:scan --all`

**Comment by RealRancor** [comment]
@schrauger The documentation tracker is available here: https://github.com/owncloud/documentation/issues

That specific topic was discussed here: https://github.com/owncloud/documentation/pull/2311 and denied there.

**Comment by RealRancor** [comment]
cc @carlaschroder Now the third or forth time (https://github.com/owncloud/documentation/pull/2311, https://github.com/owncloud/documentation/pull/2337 and here) some one is confused about that difference in that docs. I really think that should be changed...

**Comment by schrauger** [comment]
@RealRancor Thanks for letting me know about the documentation tracker. I'll be sure to use that in the future. :-)
