### ISSUE TITLE
Default .htaccess config is ignored by mod_php7

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#23929]
The current .htaccess contains `<IfModule mod_php5.c>`.
AFAIK, this only works with PHP 5, so all those directives are ignored when people are using PHP 7.

@LukasReschke @MorrisJobke @DeepDiver1975

**Comment by LukasReschke** [comment]
Thou shall always use the latest release. That's already there since 9.0.1 :see_no_evil:

**Comment by RealRancor** [comment]
Exactly: https://github.com/owncloud/core/pull/23270

**Comment by oparoz** [comment]
Thanks, I was looking at the snap repo, which is still on 9.0.0...

There is still this minor issue though: https://github.com/owncloud/core/issues/23874
