### ISSUE TITLE
OC 9.0.1: Problems with the code integrity check

### ISSUE THREAD

**Issue by BenS89** [owncloud/core#23925]
### Steps to reproduce
1. Upgrade from ownCloud 9.0 to 9.0.1
2. Open the admin panel

### Expected behaviour
No problems with the code integrity as in ownCloud 9.0

### Actual behaviour
The message is shown: "There were problems with the code integrity check. More information…
ownCloud Administrator"

With the following output:

> Technical information
> =====================
> The following list covers which files have failed the integrity check. Please read
> the previous linked documentation to learn more about the errors and how to fix
> them.
> 
> Results
> =======
> - core
> 	- EXTRA_FILE
> 		- core/doc/user/_images/documents_personal_settings.png
> 		- core/doc/user/_images/oc_documents_col_edit.png
> 		- core/doc/user/_images/full_name.png
> 		- core/doc/user/_images/email_address_personal_settings.png
> 		- core/doc/user/_images/calendar_export.png
> 		- core/doc/user/_images/calendar_edit_event.png
> 		- core/doc/user/_images/oc_documents_share.png
> 		- core/doc/user/_images/calendar_import.png
> 		- core/doc/user/_images/profile_picture_personal_settings.png
> 		- core/doc/user/_images/calendar_create_event_share.png
> 		- core/doc/user/_images/password_change.png
> 		- core/doc/user/_images/calendar_create_event_repeat.png
> 		- core/doc/user/_images/notifications_personal_settings.png
> 		- core/doc/user/_images/sharepoint-drive-config-user.png
> 		- core/doc/user/_images/event_export.png
> 		- core/doc/user/_images/usage_indicator.png
> 		- core/doc/user/_images/language_personal_settings.png
> 		- core/doc/admin/_images/app-sharepoint-enable.png
> 		- core/doc/admin/_images/ldaphome-6.png
> 		- core/doc/admin/_images/ldaphome-4.png
> 		- core/doc/admin/_images/ldaphome-2.png
> 		- core/doc/admin/_images/logging-3.png
> 		- core/doc/admin/_images/sharepoint-drive-config.png
> 		- core/doc/admin/_images/ldaphome-3.png
> 		- core/doc/admin/_images/ucsint2.png
> 		- core/doc/admin/_images/ucsint1.png
> 		- core/doc/admin/_images/ldaphome-5.png
> 		- core/doc/admin/_images/ldaphome-1.png
> 		- core/doc/admin/_images/ucsint.png
> 		- core/doc/admin/_sources/installation/nginx_configuration.txt
> 		- core/doc/admin/_sources/installation/ucs_installation.txt
> 		- core/doc/admin/_sources/installation/yaws_configuration.txt
> 		- core/doc/admin/_sources/installation/hiawatha_configuration.txt
> 		- core/doc/admin/_sources/installation/macos_installation.txt
> 		- core/doc/admin/_sources/enterprise_files_drop/index.txt
> 		- core/doc/admin/_sources/enterprise_files_drop/files_drop.txt
> 		- core/doc/admin/installation/yaws_configuration.html
> 		- core/doc/admin/installation/ucs_installation.html
> 		- core/doc/admin/installation/hiawatha_configuration.html
> 		- core/doc/admin/installation/macos_installation.html
> 		- core/doc/admin/installation/nginx_configuration.html
> 		- core/doc/admin/enterprise_files_drop/index.html
> 		- core/doc/admin/enterprise_files_drop/files_drop.html
> - dav
> 	- EXTRA_FILE
> 		- lib/carddav/card.php
> - files_external
> 	- EXTRA_FILE
> 		- 3rdparty/icewind/streams/tests/NullWrapper.php
> 		- 3rdparty/icewind/streams/tests/CallbackWrapper.php
> 		- 3rdparty/icewind/streams/tests/IteratorDirectory.php
> 		- 3rdparty/icewind/streams/tests/Wrapper.php
> 		- 3rdparty/icewind/streams/tests/phpunit.xml
> 		- 3rdparty/icewind/streams/tests/bootstrap.php
> 		- lib/failedcache.php
> 		- lib/failedstorage.php

### Server configuration
**Operating system**: Embedded QNAP Linux

**Web server:** Apache 2.4.12

**Database:** MariaDB 5.5

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page) 9.0.1

**Updated from an older ownCloud or fresh install:** Upgraded from 9.0.0

**Signing status (ownCloud 9.0 and above):** See Post above

**List of activated apps:**
Calendar 1.0
Contacts 1.0

**Comment by Xenopathic** [comment]
Please remove the old ownCloud directory (keeping data and config of course) before extracting the new version.

**Comment by BenS89** [comment]
Worked great. Thanks!

**Comment by tripledee** [comment]
Hello. I remove the old owncloud directory (after baking up data and config), then reinstalled owncloud 9.1.3 on my Raspbian/Raspberry Pi and put the data/config files back. I still have the integrity check message and it gives exactly the same list of extra files as BenS89 had (in a different order). Any idea?

**Comment by kdslkdsaldsal** [comment]
@tripledee Please note this is a bugtracker. When having support questions please use https://central.owncloud.org/ instead. There you can login via your github account and you will also find a few threads and possible solutions there.

**Comment by tripledee** [comment]
Oh, sorry! Thanks
