### ISSUE TITLE
Remove storage of federated cloud share on unshare

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#23931]
* having serverA and serverB
* user1@serverA shares a folder to user2@serverB
* user2 accepts the share
* internally we create a storage with filecache entries in the DB
* somehow a unshare happens (either user1 removes the share or user2 unmounts the share)

### Expected behaviour

* storage and filecache entries are removed

### Actual behaviour

* storage and filecache entries are still available

This was reported yesterday by @helios07

@icewind1991 @schiesbn @rullzer @PVince81 Is there any reason to keep this data? I think this could be removed easily.

**Comment by MorrisJobke** [comment]
I can't judge on bug vs enhancement. I would put it into technical debt, because it "only" clutters the filecache.

**Comment by MorrisJobke** [comment]
Beside this we also need a cleanup step to remove previously removed stuff: https://github.com/owncloud/core/issues/23364

**Comment by rullzer** [comment]
I don't think there is a real reason to keep it.
Cleanup should be rather straight forward I think.

@icewind1991 do we have 'formal' methods to delete a storage (which will also take care of cleanup etc?)

**Comment by rullzer** [comment]
Maybe it would be better to schedule a background job that does the cleanup. Since even if the cleanup *should* be simple. There is always this few people that have a fedearated share with 100K entries.

**Comment by MorrisJobke** [comment]
> Maybe it would be better to schedule a background job that does the cleanup. Since even if the cleanup should be simple. There is always this few people that have a fedearated share with 100K entries.

Makes sense.

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/15701 ?  Or close the other one in favor of this one ?

**Comment by MorrisJobke** [comment]
> Duplicate of #15701 ? Or close the other one in favor of this one ?

Close as duplicate.
