### ISSUE TITLE
SMB external mount: ETAGs always invalidated by occ files:scan due to 3600s timezone diff in timestamps

### ISSUE THREAD

**Issue by moscicki** [owncloud/core#23932]
@PVince81 

Owncloud 8.2.3 and a SMB folder mounted:

After rescan with:

```
occ files:scan –all
```

all ETAGs are invalidated and all SMB files are re-downloaded.

We have instrumented the hasUpdated() function with extra logging to compare timestamps:

https://github.com/owncloud/core/blob/stable8.2/apps/files_external/lib/smb.php#L181

```
\OCP\Util::writeLog('ALBERTO'," mtime: on disk". $actualTime . " checked against " . $time, \OCP\Util::ERROR);
```

And the difference between mtime reported on disk and stored in oc_filecache is exactl 3600s (DST timezone problem?).

It looks to me that the timestamps are converted back and forth via local timezones -- which I think is wrong -- they should be stored as numbers and compared as such.

Also, maybe consider if hasUpdated() condition should not take into account 2s time resolution from a possible underlying Windows filesystem. In this case the condition should possible be:

```
 return $actualTime - $time + 2;
```

Check with the sync client guys who have been handling such cases on the client side.

**Comment by moscicki** [comment]
Addtional note: the condition should not assume time ordering (mtime may be set back in time by hand!).

**Comment by moscicki** [comment]
What puzzles me is that comparison of mtime is also done in other parts of the code. How is this consistent with hasUpdated() function?

Example:

https://github.com/owncloud/core/blob/d6ee1798cc5f9a641344f9e81bd3d770c6875e58/lib/private/files/cache/scanner.php#L182

**Comment by moscicki** [comment]
We also came to conclusion that an upper layer of the framework somehow changes the timestamp reported by this plugin. It is not a good sign for overall design.

**Comment by PVince81** [comment]
I think the way it is intended to work is to store the "storage_mtime" value, which is whatever the storage returns into the "storage_mtime" column. This is why this column is separate from "mtime".

Then when calling `hasUpdated()` , it should compare the value from "storage_mtime" with the new value returned by the remote storage to find out whether there is a difference.

If the remote SMB storage returns different values for unchanged files after crossing DST, then this logic won't work and would require workarounds.

If you say you found code paths that diverge from this logic then we need to look into these.

@icewind1991 can you clarify ?

**Comment by PVince81** [comment]
In the case of that SMB method, `$actualTime` would be the value returned by the SMB server and `$time` would be the value currently stored in the `storage_mtime` column.

**Comment by PVince81** [comment]
> the condition should not assume time ordering (mtime may be set back in time by hand!).

agreed

**Comment by PVince81** [comment]
@moscicki mind telling us more about the SMB storage ? Is it a Linux Samba server or a Windows machine ?

From what I remember hearing, FAT filesystems would be likely to have trouble with DST but NTFS should be fine.

**Comment by PVince81** [comment]
Closing due to lack of feedback.

As stated above, the storage_mtime is the value used to detect changes, which contains the value of the mtime as provided by the storage, regardless what timezone it's in. So if that one value changes compared to what was stored before, etags will be invalidated during the next scan.
