### ISSUE TITLE
Cannot download a skeleton file that has been moved into another folder

### ISSUE THREAD

**Issue by davitol** [owncloud/core#23949]
### Steps to reproduce

1. In files view root, create a new folder
2. Move a skeleton file/folder into this new folder
3. Browse into the folder
4. Select the skeleton file/folder and try to download it

### Expected behaviour

The skeleton file/folder should be downloaded

### Actual behaviour

An error is shown. No logs are printed in owncloud.log

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**"version":"9.0.1.3","versionstring":"9.0.1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - admin_audit: 0.7
  - comments: 0.2
  - dav: 0.1.6
  - encryption
  - enterprise_key: 0.1.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firewall: 2.3.0
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - windows_network_drive: 0.2.33
  - workflow: 0.1.3

Disabled:
  - announcementcenter
  - external
  - files_antivirus
  - files_drop
  - files_ldap_home
  - objectstore
  - password_policy
  - sharepoint
  - user_external
  - user_ldap
  - user_shibboleth

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**

 Firefox

![skeletondwn](https://cloud.githubusercontent.com/assets/10596560/14463149/35b22720-00ca-11e6-9b42-8b153c7413ab.gif)

**Comment by DeepDiver1975** [comment]
can you please anaylse the filesystem regarding permissions and where the file is actually living before and after the move - THX

**Comment by davitol** [comment]
e.g. Documents and Photos are two skeleton folders and I create a new folder called newfolder

drwxr-xr-x 2 www-data www-data 4096 Apr 12 14:39 Documents
drwxr-xr-x 2 www-data www-data 4096 Apr 12 14:40 newfolder
drwxr-xr-x 2 www-data www-data 4096 Apr 12 14:39 Photos

Then I move Photos to newfolder

data/admin/files/newfolder

drwxr-xr-x 2 www-data www-data 4096 Apr 12 14:39 Photos

If i try to download it, selecting it clicking on its checkbox and then clicking in download above, the download fails. But if I download it via the "three dots" menu, it works fine

**Comment by nickvergessen** [comment]
Can not reproduce with master.

**Comment by PVince81** [comment]
Works for me in 9.0.3RC1 enterprise.

@davitol please reopen if it still happens for you

**Comment by davitol** [comment]
Tested again in Master and 9.0.3.RC1 and it works fine
