### ISSUE TITLE
Files/folders are unchecked when we "favorite" them

### ISSUE THREAD

**Issue by davitol** [owncloud/core#23940]
### Steps to reproduce

1. In files view select some files/folders clicking in their checkboxes
2. Favorite some of them clicking on the star

### Expected behaviour

The files/folders should be kept selected and the checkboxes marked

### Actual behaviour

The files/folders are kept selected but the tick is not drawn in the checkboxes

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**"version":"9.0.1.3","versionstring":"9.0.1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - admin_audit: 0.7
  - comments: 0.2
  - dav: 0.1.6
  - encryption
  - enterprise_key: 0.1.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firewall: 2.3.0
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - windows_network_drive: 0.2.33
  - workflow: 0.1.3
Disabled:
  - announcementcenter
  - external
  - files_antivirus
  - files_drop
  - files_ldap_home
  - objectstore
  - password_policy
  - sharepoint
  - user_external
  - user_ldap
  - user_shibboleth

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**

 Firefox

![favochck](https://cloud.githubusercontent.com/assets/10596560/14459448/53e57722-00b8-11e6-9632-4fe30a007cbd.gif)

**Comment by nickvergessen** [comment]
Maybe something for you @ChristophWurst
