### ISSUE TITLE
Elements of the personal page are not right located when uploading a new profile image

### ISSUE THREAD

**Issue by davitol** [owncloud/core#23950]
### Steps to reproduce
1. Go to Personal Page
2. Upload a new profile picture
### Expected behaviour

The elements of the personal page should be kept in the right location
### Actual behaviour

The elements of the personal page are misplaced
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**"version":"9.0.1.3","versionstring":"9.0.1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Enabled:
- activity: 2.2.1
- admin_audit: 0.7
- comments: 0.2
- dav: 0.1.6
- encryption
- enterprise_key: 0.1.0
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_external: 0.5.2
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firewall: 2.3.0
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
- windows_network_drive: 0.2.33
- workflow: 0.1.3
  Disabled:
- announcementcenter
- external
- files_antivirus
- files_drop
- files_ldap_home
- objectstore
- password_policy
- sharepoint
- user_external
- user_ldap
- user_shibboleth

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
```
### Client configuration

**browser**

 Firefox

e.g. change password button

![screen shot 2016-04-12 at 16 26 17](https://cloud.githubusercontent.com/assets/10596560/14463636/2ba0039a-00cc-11e6-8cfe-aa51534ed34b.png)

e.g. Password is right-aligned

![screen shot 2016-04-12 at 16 27 20](https://cloud.githubusercontent.com/assets/10596560/14463659/3b960c5e-00cc-11e6-91a1-111d1a8c9d2e.png)

**Comment by SergioBertolinSG** [comment]
Problem is here: https://github.com/owncloud/core/blob/master/settings/css/settings.css#L31

I've been trying to move elements but they get positioned even worse. My suggestion is to show a dialog window instead of just showing it over the other elements.

**Comment by SergioBertolinSG** [comment]
Example using the merged settings:

![screen shot 2016-12-07 at 13 34 21](https://cloud.githubusercontent.com/assets/9048796/20967965/370b1e6e-bc82-11e6-8338-c8ea1f131e7c.png)

**Comment by PVince81** [comment]
moved to general design / UX / styling issues group ticket: https://github.com/owncloud/core/issues/27578
