### ISSUE TITLE
Empty Filelist after Upgrading from 8.2.3.2 to 9.0.1.3 via Updater App

### ISSUE THREAD

**Issue by sebastianroming** [owncloud/core#23967]
### Steps to reproduce
1. Update via Updater App
### Expected behaviour

See all files which have been there before (in Webinterface)
### Actual behaviour

Empty file list (in Webinterface). 
Physically all files are available in the /data/ directory.
### Server configuration

**Operating system**:
Linux

**Web server:**
Apache2

**Database:**
mysqlnd 5.0.11-dev

**PHP version:**
5.5.2.8

**ownCloud version:** (see ownCloud admin page)
9.0.1.3

**Updated from an older ownCloud or fresh install:**
8.2.3.2

**Where did you install ownCloud from:**
Updater App

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

Integrity checker has been disabled. Integrity cannot be verified.

**List of activated apps:**
Activity
Collaborative Tags
Comments
Deleted files
External storage support
External user support
Federation
First Run Wizard
Notifications
PDF Viewer
Provisioning API
Share Files
Text Editor
Update notification
Versions
File locking

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

No Access

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

```
<?php
$CONFIG = array (
  'instanceid' => 'oc5588cce7b1',
  'passwordsalt' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'cloud.example.de',
  ),
  'datadirectory' => '/path/to/directory/cloud.example.de/data',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'XXX',
  'dbhost' => '127.0.0.3',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'installed' => true,
  'loglevel' => '0',
  'theme' => '',
  'maintenance' => false,
  'secret' => 'XXX',
  'mail_from_address' => 'cloudserv',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'example.de',
  'trashbin_retention_obligation' => 'auto',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration

**Browser:**
Google Chrome

**Operating system:**
Windows 7 x64
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

```
cloud.example.de/:1 Error parsing header X-XSS-Protection: 1; mode=block, 1; mode=block: expected semicolon at character position 14. The default protections will be applied.
client.js?v=f5e4f1c…:183 PROPFIND http://cloud.example.de/remote.php/webdav/ 400 (Bad request: request method denied)dav.Client.request @ client.js?v=f5e4f1c…:183dav.Client.propFind @ client.js?v=f5e4f1c…:80Client.getFolderContents @ client.js?v=f5e4f1c…:402FileList.reload @ filelist.js?v=f5e4f1c…:1422FileList.changeDirectory @ filelist.js?v=f5e4f1c…:1321FileList._onUrlChanged @ filelist.js?v=f5e4f1c…:486x.event.dispatch @ jquery.min.js?v=f5e4f1c…:5v.handle @ jquery.min.js?v=f5e4f1c…:5x.event.trigger @ jquery.min.js?v=f5e4f1c…:5e.event.trigger @ jquery-migrate.min.js?v=f5e4f1c…:2(anonymous function) @ jquery.min.js?v=f5e4f1c…:5x.extend.each @ jquery.min.js?v=f5e4f1c…:4x.fn.x.each @ jquery.min.js?v=f5e4f1c…:4x.fn.extend.trigger @ jquery.min.js?v=f5e4f1c…:5OCA.Files.App._onPopState @ app.js?v=f5e4f1c…:209OCA.Files.App.initialize @ app.js?v=f5e4f1c…:88(anonymous function) @ app.js?v=f5e4f1c…:229(anonymous function) @ underscore.js?v=f5e4f1c…:768
filelist.js?v=f5e4f1c…:1487 Uncaught (in promise) TypeError: Cannot read property 'shift' of undefined(…)
```

**Comment by nickvergessen** [comment]
> `PROPFIND http://cloud.example.de/remote.php/webdav/ 400 (Bad request: request method denied)`

Sounds interesting, but may be caused by the XSS warning before it.

cc @LukasReschke

**Comment by RealRancor** [comment]
@sebastianroming Do you have to possibility to check where this broken header is coming from:

``X-XSS-Protection: 1; mode=block, 1; mode=block``

This should only look like:

``X-XSS-Protection: 1; mode=block``

**Comment by LukasReschke** [comment]
> Integrity checker has been disabled. Integrity cannot be verified.

Also enable that one.

**Comment by sebastianroming** [comment]
@LukasReschke How to enable? Sorry ... ;-)

@RealRancor Can't imagine how and where to check.

**Comment by LukasReschke** [comment]
@sebastianroming Please post your version.php.

**Comment by sebastianroming** [comment]
@LukasReschke 
```
<?php 
$OC_Version = array(9,0,1,3);
$OC_VersionString = '9.0.1';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array(8,2);
$OC_Build = '2016-04-06T21:37:20+00:00 54fc92c37233d248de8da842352c43dffdfc5f8d';
```

**Comment by sebastianroming** [comment]
Update on this:

It seems, this occurs only on the machine where the Update started from.
Completely deleted History data, cache, all session storages, local storages etc., but no files visible.

On all other machines (I tried several...) the files are visible.

**Comment by RealRancor** [comment]
> How to enable? Sorry ... ;-)

Its enabled by default and you haven't disabled it in your config.php. Something is really fishy here.

**Comment by sebastianroming** [comment]
Any updates on this?
It happens only on the computer, where I started the update from...
All browsers are affected, no files visible. 

It's really important to have access via web.

@RealRancor Sorry, no access to the webserver configuration :-/

**Comment by PVince81** [comment]
Maybe your web server doesn't allow the PROPFIND method ? Since 9.0 the web UI uses Webdav to retrieve the file list and do file operations, just like the desktop client does.

Are you able to connect to "remote.php/webdav" with a third party Webdav client like cadaver ?

Try this command (adjust accordingly):
```
curl -D - -u admin -X PROPFIND http://localhost/owncloud/remote.php/webdav/
```

**Comment by sebastianroming** [comment]
@PVince81 This behaviour is just on ONE Windows 7 device. All other devices show the filelist, so I believe that this is not the problem ;-)

**Comment by sebastianroming** [comment]
This can be closed. 
An update to the firewall did not allow PROPFIND methods anymore, as @PVince81 already mentioned. I did not recognize this.

Sorry for the inconvenience.

**Comment by RealRancor** [comment]
@sebastianroming Didn't you get the https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/security_setup_warnings.html#your-web-server-is-not-yet-set-up-properly-to-allow-file-synchronization warning in your admin backend? Normally this should warn you if the PROPFIND method is blocked.

**Comment by sebastianroming** [comment]
@RealRancor Nope, did not get this!

**Comment by RealRancor** [comment]
@PVince81 Mhhh, something to debug? The warning should definitely appear if a PROPFIND is not allowed to remote.php/webdav

**Comment by PVince81** [comment]
The setup check does a PROPFIND and checks whether the status is 207 or 401. If not, then it shows an error.

Not sure what the firewall was responding here, maybe the connection was aborted ?
Might be possible to detect aborted connections too. Reopening.

**Comment by sebastianroming** [comment]
@PVince81 Error 400

**Comment by PVince81** [comment]
@sebastianroming in this case you should see an error.
This is the JS code in question: https://github.com/owncloud/core/blob/v9.0.2/core/js/setupchecks.js#L27

**Comment by sebastianroming** [comment]
@PVince81 okay, will check that tomorrow again.

**Comment by PVince81** [comment]
Works for me on v9.0.2.
I made "remote.php/webdav" return a 400 error and the warning appears:
![webdav-400](https://cloud.githubusercontent.com/assets/277525/16413572/f90f1f12-3d32-11e6-8671-9f36cabaa302.png)

**Comment by PVince81** [comment]
> I made "remote.php/webdav" return a 400 error 

You mean in your firewall ?

**Comment by PVince81** [comment]
Closing due to lack of feedback
