### ISSUE TITLE
memcache php7

### ISSUE THREAD

**Issue by Tealk144** [owncloud/core#23968]
Hi, i have update my server today to PHP7.0.5 but im not able to get the Memcache running.
On PHP5.6 it was run fine.

<link rel="shortcut icon" href="Memcache \OC\Memcache\APCu not available for local cache Is the matching PHP module installed and enabled?

OwnCloud 9.0.0
PHPINFO: http://anzah.network/die_info-php.php

**Comment by LukasReschke** [comment]
Please install https://github.com/krakjoe/apcu-bc

**Comment by Tealk144** [comment]
ah ok sorry have only install the apcu :'(
Thank you for the fast answer
