### ISSUE TITLE
upgrading from 8.1 to 9.0.1

### ISSUE THREAD

**Issue by danjde** [owncloud/core#23988]
Hi ownclouders,

I'm using owcloud on shared hosting, data cripted.
I've try to upgrade owncloud server from 8.1 to 9.0.1, but during the upgrade process, this errors appears:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

The update was unsuccessful. Please report this issue to the ownCloud community.

many Thanks!

This my PHP environment:

System  Linux w-04.th.seeweb.it 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u3 x86_64
Build Date  Oct 17 2015 08:26:41
Server API  CGI/FastCGI
Virtual Directory Support   disabled
Configuration File (php.ini) Path   /etc/php5/cgi
Loaded Configuration File   /home/mhd/www.cosmogonia.org/conf/php.ini
Scan this dir for additional .ini files     /etc/php5/cgi/conf.d
Additional .ini files parsed    /etc/php5/cgi/conf.d/10-pdo.ini, /etc/php5/cgi/conf.d/20-curl.ini, /etc/php5/cgi/conf.d/20-gd.ini, /etc/php5/cgi/conf.d/20-mcrypt.ini, /etc/php5/cgi/conf.d/20-mysql.ini, /etc/php5/cgi/conf.d/20-mysqli.ini, /etc/php5/cgi/conf.d/20-pdo_mysql.ini, /etc/php5/cgi/conf.d/20-pdo_sqlite.ini, /etc/php5/cgi/conf.d/20-sqlite3.ini, /etc/php5/cgi/conf.d/20-xmlrpc.ini, /etc/php5/cgi/conf.d/20-xsl.ini, /etc/php5/cgi/conf.d/99-tophost.ini, /etc/php5/cgi/conf.d/sendmail.ini
PHP API     20100412
PHP Extension   20100525
Zend Extension  220100525
Zend Extension Build    API220100525,NTS
PHP Extension Build     API20100525,NTS
Debug Build     no
Thread Safety   disabled
Zend Signal Handling    disabled
Zend Memory Manager     enabled
Zend Multibyte Support  provided by mbstring
IPv6 Support    enabled
DTrace Support  disabled
Registered PHP Streams  https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip
Registered Stream Socket Transports tcp, udp, unix, udg, ssl, sslv3, tls
Registered Stream Filters   zlib._, bzip2._, convert.iconv._, string.rot13, string.toupper, string.tolower, string.strip_tags, convert._, consumed, dechunk, mcrypt._, mdecrypt._

**Comment by RealRancor** [comment]
@danjde Have you done the minor updates in between. An example upgrade path from e.g. 8.1.1 to 9.0.1 would be:

8.1.1 -> 8.1.6 -> 8.2.3 -> 9.0.1

In between the major upgrade steps (8.1->8.2->8.3) make sure that you have deleted all files and folders except /data/ and /config/

**Comment by danjde** [comment]
Ah, ok, I will do and then report.

many thanks!

**Comment by danjde** [comment]
Hello,
I've upgraded to 8.2, but when try to upgrade to 9.0.1 obtain the same result.
I've seen [here](https://github.com/owncloud/core/issues/9186) that seem an Mysql engine problem. Does Owncloud 9.0.1 use InnoDB Mysql engine other than MyIsam? My Mysql shared hosting plan does not support InnoDB...

many thanks

**Comment by PVince81** [comment]
@danjde ownCloud requires InnoDB. There was also an update routine added recently that automatically converts the MyIsam tables to InnoDB.

**Comment by RealRancor** [comment]
@PVince81 Is this requirement documented / checked somewhere (can't find with an short search). Recently we had a discussion about that  at the forums:

https://forum.owncloud.org/viewtopic.php?f=21&t=35106&start=10#p117078

**Comment by PVince81** [comment]
Indeed, seems to be missing.
I'll make a ticket and also reference to the PR that introduced the conversion which hopefully will contain more information.

**Comment by PVince81** [comment]
doc ticket: https://github.com/owncloud/documentation/issues/2491

**Comment by RealRancor** [comment]
@PVince81 Btw. is this really about InnoDB vs. MyISAM? It seems https://github.com/owncloud/core/pull/23508 had limited the keylength based on the comment in https://github.com/owncloud/core/issues/22968#issuecomment-194034820

**Comment by PVince81** [comment]
@RealRancor not sure. From what I understand about the linked ticket is that if a text field has no specified length it might clash with key lengths or so.

When looking at the table definition of the "oc_addressbooks" table it seems all lengths are properly set in OC 9.1.

Oh! But on OC 9.0 / stable9 the lengths aren't set.
Maybe we need to set them there too ? @DeepDiver1975

**Comment by DeepDiver1975** [comment]
> Oh! But on OC 9.0 / stable9 the lengths aren't set.
> Maybe we need to set them there too ? @DeepDiver1975

We did not apply these changes because we did not want to introduce any trouble on minor upgrade.
But we are now facing these issues on major upgrade - maybe we need to add a repair step?

**Comment by PVince81** [comment]
@DeepDiver1975 can you have a look and make a decision for the backport ? Thanks

**Comment by diman82** [comment]
I'm facing the same problem.
Is there any solution to it?

**Comment by PVince81** [comment]
is this still an issue with recent OC versions like 9.1.6 ?

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
