### ISSUE TITLE
Sharing with groups - problem with hints and capital letters

### ISSUE THREAD

**Issue by kpalik** [owncloud/core#23987]
### Steps to reproduce
1. Create any groups with capital letters (e.g. Company)
2. Try to share any folder using group name without using capital letters (e.g. company)
(see screens below)

### Expected behaviour
system should show us a hint with proper group name and folder should be shared with "Company" group even if we write "company" in user/group search field

### Actual behaviour
In sharing area, If we enter "company" in user/group search field system gives us a hint "company" but when we click on it system prevents adding this group and showa a message - "please specify a valid group". If we write "Company" everything works fine

### Server configuration

**ownCloud version:** (see ownCloud admin page)
9.0 - latest fresh install on Ubuntu ubuntu-14.04.4-server-amd64 

### Client configuration
**Browser:**
IE11
**Operating system:**
Windows 8.1 x64

scenario 1 

![own1](https://cloud.githubusercontent.com/assets/2924034/14520178/5311a700-0223-11e6-888d-d72d9e87518f.png)

scenario 2

![own2](https://cloud.githubusercontent.com/assets/2924034/14520211/93291df0-0223-11e6-829f-535ff500ea67.png)

**Comment by nickvergessen** [comment]
Should be fixed with ownCloud 9.0.1+
https://github.com/owncloud/core/pull/23223

**Comment by PVince81** [comment]
Please try again with OC 9.0.3 and reopen if the problem persists
