### ISSUE TITLE
[Tanslation] [CalDAV] Translate the Name of the Birthday Calendar

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#23982]
Since 9.0.1 we call contacts_birthdays "Contacts birthday", but i think we should also translate this :wink:

**Comment by DeepDiver1975** [comment]
Not possible. The name is stored on creation in the database. We might know the users language at that time but any client language or future language change by the user is not reflected.

I don't see this as a valuable improvement.

Finally the calendar name is usually only visible on setup where it is acceptable to see a not translated string.

**Comment by nickvergessen** [comment]
Well I think it would be possible to do that in the dav endpoint when giving out the info.
`if uri === 'contact_birthdays' then name = l->t()`

**Comment by DeepDiver1975** [comment]
Nice idea @nickvergessen - I was not thinking about this. THX

**Comment by DeepDiver1975** [comment]
@nickvergessen want to come up with a PR? Otherwise I'll do that these days.

**Comment by nickvergessen** [comment]
go ahead and have some fun ;)

**Comment by DeepDiver1975** [comment]
> go ahead and have some fun ;)

haha
