### ISSUE TITLE
CSP errors result in unusable page (Firefox)

### ISSUE THREAD

**Issue by Wonderfall** [owncloud/core#24002]
Hi, thanks your amazing work. :+1: 
I've been using ownCloud for a while, and recently I decided to move back to Firefox. But a strange problem is occurring... I've found some similar issues, but I don't understand them very well.

If needed, I can provide an account on my instance which is https://cloud.schrodinger.io.

### Steps to reproduce
1. Install ownCloud 9.0.1 using [this dockerfile](https://github.com/Wonderfall/dockerfiles/tree/master/owncloud).
2. Using Firefox, go to the "personal" page.

### Expected behaviour
The page should be displayed and nothing else should happens.

### Actual behaviour
The page is infinitely refreshing. I have this problem **only with Firefox**. Chrome and Safari are browsing fine.

### Server configuration
**Operating system**: Debian Jessie (host), Alpine Linux (container).

**Web server:** nginx 1.9.14.

**Database:** MariaDB 10.1.13 (another container, official mariadb).

**PHP version:** PHP 7.0.6.

**ownCloud version:** ownCloud 9.0.1.

**Updated from an older ownCloud or fresh install:** Fresh install.

**Where did you install ownCloud from:** https://hub.docker.com/r/wonderfall/owncloud/

**The content of settings/integrity/failed** : No errors have been found.

**List of activated apps:** Those by default, encryption module, calendar, contacts, documents. But I tried with none of them.

**The content of config/config.php:** https://paste.schrodinger.io/?43a78c29bf2558e4#reC/I8gWeIYuO6UZDIlcvmalzAxUXsWqLkIsOpPmZTs=

**Are you using external storage, if yes which one:** No.

**Are you using encryption:** Yes, but I tried without it enabled.

**Are you using an external user-backend, if yes which one:** No.

### Client configuration
**Browser:** Firefox 45.0.2 (desktop & mobile).

**Operating system:** OS X 10.11.4, Android 5.1.1.

#### Web server error log
Nothing special in error.log (both in owncloud container and reverse container).

#### ownCloud log (data/owncloud.log)
Nothing useful when I trigger "the loop".

#### Browser log
Hard to catch, since it's too fast...
```
L'utilisation de « getPreventDefault() » est obsolète. Utiliser « defaultPrevented » à la place. jquery.min.js:5:17117
Content Security Policy: La directive « frame-src » est obsolète. Veuillez utiliser la directive « child-src » à la place. <inconnu>
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: Les paramètres de la page ont empêché le chargement d'une ressource à self (« script-src https://cloud.schrodinger.io 'unsafe-eval' »).1 personal
```

**Comment by LukasReschke** [comment]
The CSP errors are a false positive created by Firefox and can very likely be ignored. This will be fixed once we updated our jQuery version.

> The page is infinitely refreshing. I have this problem only with Firefox. Chrome and Safari are browsing fine.

Please drop me a mail with test credentials.

**Comment by Wonderfall** [comment]
I sent you an e-mail two weeks ago, I don't know if it was helpful.
My problem mysteriously disappeared as I moved my base image to Alpine Linux.

**Comment by bonanza123** [comment]
For me, this issue still exists, e.g. when using themes from https://github.com/rafaelgou/owncloud-bootswatch-themes
