### ISSUE TITLE
Duplicate share icon on shared items with the same name

### ISSUE THREAD

**Issue by NadirRoGue** [owncloud/core#24001]
### Steps to reproduce
1. Create a folder with any name
2. Create a folder, with the same name as the previous one, inside another folder
3. Share both folders with any user

### Expected behaviour
They both appear in "Shared with others", behaving the same as any other share

### Actual behaviour
When you open details view of any of those folders, the share icon will be duplicated in both folders (see screenshot)

Tested on owncloud demo page (screenshot was taken from there)
![1](https://cloud.githubusercontent.com/assets/5183894/14531542/10822b18-025e-11e6-8b5d-e024a09fc3b6.png)

**Comment by PVince81** [comment]
Please try again with OC 9.0 or later, this should be fixed already.
