### ISSUE TITLE
Auto-calculate byte percentage in personal settings

### ISSUE THREAD

**Issue by SamanthaNguyen** [owncloud/core#24011]
- **Current**: No bugs, although this is a suggestion. The current format of the amount of space you're taking up goes like this:  "You have used x MB out of the available y GB"
- **Suggested**: Instead, it'd be nice if it auto-calculated a percentage and put to the side, so it would instead say: "You have used x MB out of the available y GB ( z%)"
- **Example**: If you used 3,000 MB out of 20GB for example, it would say this: "You have used 3000 MB out of the available 20GB (15%)"

**Comment by georgebarnick** [comment]
Think you mean 15%

**Comment by PVince81** [comment]
Pull requests welcome :smile:
