### ISSUE TITLE
Broken "Memcache \OC\Memcache\APCu not available for local cache Is the matching PHP module installed and enabled" on oC9

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#24015]
### Steps to reproduce
1. Install ownCloud 9.0.1
2. Have no php5-apcu or an outdated php5-apcu installed
3. Add ``'memcache.local' => '\OC\Memcache\APCu',`` to config/config.php
4. Refresh page

### Expected behaviour
Not broken warning should be shown

### Actual behaviour
A partly broken warning, containing some html code is shown:

```
<!DOCTYPE html>
<!--[if lte IE 8]><html class="ng-csp ie ie8 lte9 lte8" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if IE 9]><html class="ng-csp ie ie9 lte9" data-placeholder-focus="false" lang="en" ><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--><html class="ng-csp" data-placeholder-focus="false" lang="en" ><!--<![endif]-->
	<head data-requesttoken="">
		<meta charset="utf-8">
		<title>
		ownCloud		</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="referrer" content="never">
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
		<meta name="apple-itunes-app" content="app-id=543672169">
		<meta name="theme-color" content="#1d2d44">
		<link rel="shortcut icon" href="Memcache \OC\Memcache\APCu not available for local cache Is the matching PHP module installed and enabled?
```

### Server configuration
**Operating system**: Ubuntu 14.04
**Web server:** Apache2 2.4.7-1ubuntu4.9 with mod_php
**PHP version:** 5.5.9+dfsg-1ubuntu4.14
**ownCloud version:** 9.0.1
**Updated from an older ownCloud or fresh install:** Fresh
**Where did you install ownCloud from:** Official repositories
**Signing status (ownCloud 9.0 and above):** No errors have been found.

Everything else within the issue template doesn't seem relevant for me.

**Comment by LukasReschke** [comment]
https://github.com/owncloud/core/pull/23991 should fix that :wink:

**Comment by RealRancor** [comment]
Ahhh, got it. Posting screenshots / pictures instead of text is always good to not find such issues via the search. :-)
