### ISSUE TITLE
Owncloud doesn't see the disk extention done via LVM

### ISSUE THREAD

**Issue by HenkUyttenhove** [owncloud/core#24019]
### Steps to reproduce

I had an instance v9 in place but with disk of 100 GB, 77 GB available for Owncloud
My desktop distribution is Ubuntu 15.04 with the "Owncloud Desktop Client" version 1.8.1+dfsg-1ubuntu1 (build from version ee7102 on Aug 4 2015)

Because my disk was full, I added a disk and via LVM extented my disk:
root@------:~# df -h
Filesystem                     Size  Used Avail Use% Mounted on
udev                           487M  4.0K  487M   1% /dev
tmpfs                          100M  368K  100M   1% /run
_**/dev/mapper/kawandacloud-root  590G   77G  488G  14% /**_
none                           4.0K     0  4.0K   0% /sys/fs/cgroup
none                           5.0M     0  5.0M   0% /run/lock
none                           497M     0  497M   0% /run/shm
none                           100M     0  100M   0% /run/user
/dev/vda1                      228M  118M   98M  55% /boot

After the LVM resize, EXT4 resize and reboot, disk size was update (see above)
but Owncloud still delivers errors and Owncloud Desktop client is still giving message
67 Gib (100%) of 67 GiB server space in use
### Expected behaviour

Resizing the disk to 590 GB and rebooting was assumed to be enough to allow Owndisk to use more disk.
### Actual behaviour

Owncloud still is locked to old disk value
### Server configuration

**Operating system**:
Linux dropbox.kawanda.be 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
Apache/2.4.7 (Ubuntu)
**Database:**
Ver 15.1 Distrib 5.5.47-MariaDB
**PHP version:**
PHP 5.5.9-1ubuntu4.14
**ownCloud version:** (see ownCloud admin page)
v9
**Updated from an older ownCloud or fresh install:**
Upgrade via Owncloud
**Where did you install ownCloud from:**
Distri
**Signing status (ownCloud 9.0 and above):**

**Comment by RealRancor** [comment]
@HenkUyttenhove 

> 1.8.1+dfsg-1ubuntu1 

Please update to a recent version of the sync client which is 2.1.1

**Comment by tflidd** [comment]
Do you see the correct value on your personal page (in the webinterface)? Can you add or remove a file to trigger a new calculation of the free space?

**Comment by nickvergessen** [comment]
I guess the sync client stores the value for some minutes

**Comment by HenkUyttenhove** [comment]
I have added files via the sync client.  This first fails with message disk full, restarts and uploads all files as requested.  Don't know if sync client is cleaning.  Sync client is part Ubuntu repository so upgrade of client is not really wanted.

Using the web-interface (v9.01), I don't know where to see the free storage on the platform.  Can you please point me to where I can see this?  I have tried to find this in the admin interface but no luck.

**Comment by DeepDiver1975** [comment]
> Sync client is part Ubuntu repository so upgrade of client is not really wanted.

Please use the packages for the clients which we are providing - THX
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

**Comment by nickvergessen** [comment]
> Using the web-interface (v9.01), I don't know where to see the free storage on the platform. Can you please point me to where I can see this? I have tried to find this in the admin interface but no luck.

1. Click on username (Top right)
2. Personal
3. See first thing on the page:
![bildschirmfoto vom 2016-04-18 12 16 23](https://cloud.githubusercontent.com/assets/213943/14600927/7d4293f6-055f-11e6-9460-84dc8884c3be.png)

**Comment by HenkUyttenhove** [comment]
@nickvergessen 
Hi Nick,
This doesn't show me the available storage on Owncloud, only that I can use up to "unlimited".  To verify the total available storage on the platform, this won't work. ;(

**Comment by PVince81** [comment]
The web UI only shows the user's quota, not the full disk space. So if the quota is "Unlimited" it will show "Unlimited".

**Comment by PVince81** [comment]
It was observed before by other users that after increasing the size of a LVM partition, the PHP function `disk_free_space` didn't return the new value for some reason. This could be a bug in PHP.

You can try running this:
```php
<?php
   var_dump(disk_free_space('/path/to/owncloud/data/'));
```

**Comment by PVince81** [comment]
Closing due to lack of feedback. If PHP itself isn't able to provide the correct free space value there isn't anything that ownCloud can do at this stage.
