### ISSUE TITLE
Make Tags usable for users not want to collaborate with the whole instance

### ISSUE THREAD

**Issue by aspdye** [owncloud/core#24014]
The problem with the current tags is, that they are _global_. That is not always a problem, because there are cases in which this might be useful (collaboration, ...). But in some cases, i think tags should be private, so that only you (or your group you collaborate with) can see the tags. Especially for larger instances 😁 Because creating the tag "Pictures of Chris" will show the tag "Pictures of Chris" also to users, having nothing to do with Chris. 😅 
- [ ] Give an option to make your Tags invisible for others 
- [ ] Implement a 3-steps system for the tags: "Global", "Group", "Private"

What do you think? 😁

**Comment by LukasReschke** [comment]
cc @karlitschek @jancborchardt

**Comment by karlitschek** [comment]
yes. this is known. At the moment we decided to do global tags because it helps with collaboration. In the future we might also do private tags but I'm personally not 100% convinced that it is super useful. Not a lot of 'normal' tag their own files.
