### ISSUE TITLE
OCI.php wrong Oracle privileges check

### ISSUE THREAD

**Issue by pollopolea** [owncloud/core#24025]
Hello,
I don't know if this post should be here. But here I go:

lib/private/setup/oci.php

Behavior:
Original code checks for "CREATE ROLE" oracle privilege, if you have it  function createDBUser($connection) is called and these sql sentences are executed
: 
1 - ( CREATE USER [ Line 205] or ALTER USER   ); 
2 - GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, UNLIMITED TABLESPACE TO [...]

You are assuming that if you have "CREATE ROLE"  you are some kind of admin and you can "CREATE USER" or "ALTER USER" but this is not true. Maybe You should check all the privileges you need before go into the function createDBUser.

Original Code:
function setupDatababase()
Lines 92:93
		$query='SELECT count(*) FROM user_role_privs, role_sys_privs'
			." WHERE user_role_privs.granted_role = role_sys_privs.role AND privilege = 'CREATE ROLE'";

Modified Code:
$query=SELECT case when  (count(*) = 2) then 1 else 0 end  FROM user_role_privs, role_sys_privs  WHERE user_role_privs.granted_role = role_sys_privs.role AND privilege in ('CREATE USER', 'ALTER USER');

this check at least dbuser has  'CREATE' and 'ALTER USER' privileges and he can use them.

But this code is incomplete, you also need to check you have CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, UNLIMITED TABLESPACE  with admin options.

The sql code to check 7 privileges should be: 

SELECT case when  (count(*) = 7) then 1 else 0 end as all_privileges from
user_role_privs a1 inner join role_sys_privs a2 on  a1.granted_role = a2.role 
where (a2.privilege in ('CREATE USER', 'ALTER USER') ) or  
( a2.privilege in ('CREATE SESSION', 'CREATE TABLE', 'CREATE SEQUENCE', 'CREATE TRIGGER', 'UNLIMITED TABLESPACE') and a2.admin_option = 'YES');

**Comment by DeepDiver1975** [comment]
Thanks for your feedback and suggestions - can I ask you to submit this as a pull request?
Actual code diffs are easier to review :wink: THX

**Comment by PVince81** [comment]
PR was closed https://github.com/owncloud/core/pull/24039#issuecomment-227667980

If you still think this is important to have merged, feel free to reopen
