### ISSUE TITLE
Cannot scroll file list page on IE11 (shared by link)

### ISSUE THREAD

**Issue by moscicki** [owncloud/core#24028]
Owncloud version 8.2.2.

A directory containing many entries is shared by link. When I access this share by link I get a long listing of files -- this does not fit on a single page and requires scrolling.

However, scrolling does not work on IE11 (on other browsers yes).

**Comment by tflidd** [comment]
This was fixed in OC 8.2.3:
https://github.com/owncloud/files_pdfviewer/issues/90

**Comment by RealRancor** [comment]
Yepp, refs: https://github.com/owncloud/core/issues/20044 and https://owncloud.org/changelog/#latest8.2
