### ISSUE TITLE
Impossible to import contacts

### ISSUE THREAD

**Issue by Markus9973** [owncloud/core#24021]
### Steps to reproduce
1. go to Contacts
2. click on Settings (German: Einstellungen)
3. click on import
4. choose the file which has been exported via OC 8 before (contacts8.vcf) in the file dialog
5. click on open file

### Expected behaviour
The contacts of the vcf-file should have been imported and should be shown in contacts

### Actual behaviour
nothing happens. No message, no import, no contacts. It seems that the "Import"-Button opens the file selection dialog and allows to choose a file, but after clicking on "open" there is no functionality behind

### Server configuration
**Operating system**:
(don't know, it's a shared hosting at domain factory)
**Web server:**
(some apache, it's a shared hosting at domain factory)
**Database:**
MySQL 5.6.19
**PHP version:**
5.6.12
**ownCloud version:** (see ownCloud admin page)
9.0.1
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
setup-owncloud from owncloud.org
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

**List of activated apps:**

Calendar 1.1
Contacts 1.1.0.0
and the default activated apps 


**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox 45.02 or Chrome 49.0.2623.112 (same bug)

**Operating system:**
Windows 10

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
Known issue

**Comment by DeepDiver1975** [comment]
refs https://github.com/owncloud/contacts/issues/291 and others
