### ISSUE TITLE
user app (internal user account management) hangs when opened as "...jquery-1.10.2.js was not found on this server.

### ISSUE THREAD

**Issue by critzinger** [owncloud/core#24022]
Hello,

we have upgraded from 8.2.2 to 9.0.1.3
Now we have problems to manage our account (>800) over the internal user account management app.

The app hangs when opened. In firefox debugging console we can see "The requested URL /owncloud/core/vendor/jquery/jquery-1.10.2.js was not found on this server".

we have uploaded the jquery-1.10.2.js manually, but the failure still exists.

following apps are enabled / disabled

Enabled:

activity: 2.2.1
comments: 0.2
dav: 0.1.6
federatedfilesharing: 0.1.0
files: 1.4.4
files_sharing: 0.9.1
files_trashbin: 0.8.0
notifications: 0.2.3
provisioning_api: 0.4.1
systemtags: 0.2
templateeditor: 0.1
updatenotification: 0.1.0

Disabled:

encryption
external
federation
files_external
files_pdfviewer
files_texteditor
files_versions
files_videoplayer
firstrunwizard
gallery
user_external
user_ldap

OC Version: 9.0.1.3
Webserver: Apache 2.4
PHP. 5.6.19
OS: Debian Jessie

**Comment by LukasReschke** [comment]
Issue template :wink:

**Comment by critzinger** [comment]
we have OC Standard template with noch modfications

**Comment by RealRancor** [comment]
@critzinger He asked to fill out the issue template shown when creating a new issue. Thats what i have also told you in: https://github.com/owncloud/core/issues/21389#issuecomment-210347003

> Please create a new issue filling out the issue template shown.
