### ISSUE TITLE
MySQL dump syntax errors in SQL file

### ISSUE THREAD

**Issue by rubenverhoef** [owncloud/core#24038]
### Steps to reproduce
1. backup database with phpmyadmin
2. restore database with phpmyadmin
3.

### Expected behaviour
normally it should import the database without errors

### Actual behaviour
I get some SQL file syntax errors:
`ERROR 1064 (42000) at line 30113: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS' 'Operation type',
  'opspec' longtext COLLATE utf8_bin COMMENT 'json-string' at line 5`

When i open the sql file with MySQL workbench it gives a syntax error Unexpected 'AS' (as) on this line:
` 'optype' varchar(64) COLLATE utf8_bin DEFAULT NULL COMMENT AS 'Operation type',`

### Server configuration
**Operating system**:
FreeNAS 9.10

**Web server:**
Nginx 1.8

**Database:**
MySQL

**PHP version:**
7.0.5

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
owncloud.org/install

**Signing status (ownCloud 9.0 and above):**
not operating

**List of activated apps:**

not possible

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocszq3u80fap',
  'passwordsalt' => '***********',
  'secret' => '***********',
  'trusted_domains' => 
  array (
    0 => 'www.thuisverhoef.nl',
    1 => '192.168.0.6',
  ),
  'datadirectory' => '/media',
  'overwrite.cli.url' => 'https://www.thuisverhoef.nl/owncloud',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'owncloud',
  'dbhost' => '192.168.0.11',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '***********',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'thuisverhoef.nl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.ziggo.nl',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'thuisverhoef@ziggo.nl',
  'mail_smtppassword' => '***********',
  'appstore.experimental.enabled' => true,
  'maintenance' => false,
  'loglevel' => 2,
  'theme' => '',
  'asset-pipeline.enabled' => true,
);
**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by RealRancor** [comment]
@rubenverhoef How is importing and exporting in phpmyadmin related to ownCloud? You might want to try:

https://www.phpmyadmin.net/support/

Especially as this opspec and optype stuff is not part of the ownCloud database scheme:

https://github.com/owncloud/core/blob/v9.0.1/db_structure.xml

**Comment by rubenverhoef** [comment]
@RealRancor thanks for your reply. Now i know where to look.
