### ISSUE TITLE
Login background image blurry on 27' screen

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#24035]
Click on the image to see how it looks on my 27' screen :wink: 

Resolution is 2560x1440.

![2016-04-15_19-09-38](https://cloud.githubusercontent.com/assets/878997/14569231/aaf108ba-033d-11e6-9aad-87f0b799c4d0.png)

cc @karlitschek @jancborchardt @owncloud/designers

**Comment by LukasReschke** [comment]
Besides that, this rocks. Now we just need to figure out what to do with large screens. :wink:

**Comment by LukasReschke** [comment]
Also the checkbox can be kinda hidden depending on the screen resolution. Is there some CSS magic possibility to have it black if the background is white and white if it is darkish?

**Comment by skjnldsv** [comment]
You mean on the checkbox location, or calculating the whole image brightness?

**Comment by vincchan** [comment]
What about a blurred background? Seems to improve the visibility of the checkbox and doesn't make the low resolution of the image that apparent. 

<img width="1641" alt="screen shot 2016-04-15 at 23 02 47" src="https://cloud.githubusercontent.com/assets/868272/14574906/92830fbe-035e-11e6-9ec5-c9701269fe02.png">

**Comment by jancborchardt** [comment]
@vincchan yeah! I also thought about a blurred background initially, with 20px radius gaussian blur.

cc @ChristophWurst who had another enhancement to the background which improved the yellow tint.

Also as a sidenote @owncloud/designers we should try to center that log in box vertically on large displays like that. @Henni @skjnldsv let me guess – you have some flexbox-fu to do that? ;)

**Comment by ChristophWurst** [comment]
@jancborchardt as discussed, I created a b/w version of the image and added a blue tone to it afterwards:
![bildschirmfoto von 2016-04-15 20-01-28](https://cloud.githubusercontent.com/assets/1374172/14587682/57608e48-04b7-11e6-9e4d-344c0a7990c7.png)

**Comment by skjnldsv** [comment]
@jancborchardt or position absolute? 😆 

Just kidding, we should indeed use flex!

**Comment by jancborchardt** [comment]
@skjnldsv haha, stop making fun of that – we did need to support IE8 until not too long ago. ;D

**Comment by skjnldsv** [comment]
What about ie6?? :'(

**Comment by jancborchardt** [comment]
The only thing I’ll say about that is that this was my Halloween costume a few years ago:
![halloween-explorer](https://cloud.githubusercontent.com/assets/925062/14590409/153a3d28-04fa-11e6-92a6-9d61be22727a.jpg)

**Comment by skjnldsv** [comment]
AHahhahah! FA-BU-LOUS!

**Comment by DeepDiver1975** [comment]
We need to address the spinner issue as well ...

![bildschirmfoto von 2016-04-18 12-19-41](https://cloud.githubusercontent.com/assets/1005065/14601003/e7bc6c66-055f-11e6-99fd-123cbc15032f.png)

**Comment by jancborchardt** [comment]
Yeah, for the loading spinner we have: Switch to simpler looking loading spinner #19091

**Comment by MorrisJobke** [comment]
I would go for the blur.

**Comment by Henni** [comment]
Simple experiment with flexbox:
![login-flex](https://cloud.githubusercontent.com/assets/1267827/14629806/80ee1e8a-0609-11e6-808c-9e202e55dbe3.png)
![image](https://cloud.githubusercontent.com/assets/1267827/14629884/0cea89fa-060a-11e6-95cc-2eb9db87a11c.png)
I don't know how to fix the low contrast problem (especially in the footer), yet. Grey boxes are a bit harsh.

**Comment by skjnldsv** [comment]
Nice work!
Maybe adding a blur behind the text?

**Comment by Henni** [comment]
@skjnldsv probably won't solve the problem if the text is wide enough to cover the white clouds.

**Comment by skjnldsv** [comment]
Dynamically clip trough the image and change the text color?
http://salsita.github.io/jq-clipthru/demo/

**Comment by jancborchardt** [comment]
About the text: We just need to do it like we do in Gallery, add a dark text-shadow around the text:
```
text-shadow: 1px 1px 4px #333, 1px -1px 4px #333, -1px 1px 4px #333, -1px -1px 4px #333;
```

(see https://github.com/owncloud/gallery/blob/master/css/slideshow.css#L146)

**Comment by Henni** [comment]
@skjnldsv there is also a css property for this (except for IE & Edge) https://css-tricks.com/reverse-text-color-mix-blend-mode/ but I don't like the result.

@jancborchardt that approach looks like this:
![image](https://cloud.githubusercontent.com/assets/1267827/14630699/a3699204-060f-11e6-8177-a46b457d0bd2.png)
The result is ok, but the checkbox is still hardly visible.

**Comment by skjnldsv** [comment]
It's not that great! :/
Yep, there's the mix-blend-mode, but there are many possibility in it, revert the color, just darken it?
Worth a try I think :)

**Comment by PVince81** [comment]
@felixheidecke

**Comment by PVince81** [comment]
Backlog for now, unless @felixheidecke or someone else finds a new cloudy and sharper login image

**Comment by PVince81** [comment]
Login image has changed. Please reopen if new one is also blurry.
