### ISSUE TITLE
add username to unsupported client version exception

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#24034]
It is great that we log messages like that. But it would be helpful to also log the username so that the clients can be updated.

{"reqId":"i1k5okjAdkbDfnFy4QSd","remoteAddr":"96.59.15.53","app":"webdav","message":"Exception: 
{\"Message\":\"HTTP\\\/1.1 403 Unsupported client version.\",
\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Forbidden\",\"Code\":0,
\"Trace\":\"#0 [internal function]: 
OC\\\\Connector\\\\Sabre\\\\BlockLegacyClientPlugin->beforeHandler(Object(Sabre\\\\HTTP\\\\Request), 
Object(Sabre\\\\HTTP\\\\Response))\\n#1 
\\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.3\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): 
call_user_func_array(Array, Array)\\n#2 
\\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.3\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): 
Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 
\\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.3\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): 
Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), 
Object(Sabre\\\\HTTP\\\\Response))\\n#4 
\\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.3\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): 
Sabre\\\\DAV\\\\Server->exec()\\n#5 
\\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.3\\\/remote.php(137): 
require_once('\\\/srv\\\/www\\\/htdocs...')\\n#6 {main}\",\"File\":
\"\\\/srv\\\/www\\\/htdocs\\\/owncloud-8.2.3\\\/lib\\\/private\\\/connector\\\/sabre\\\/blocklegacyclientplugin.php\",
\"Line\":76}","level":0,"time":"2016-04-15T14:44:56+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}

**Comment by karlitschek** [comment]
@msrex FYI

**Comment by LukasReschke** [comment]
Thanks a lot for your feature request. In our latest and greatest release this has already been implemented.

https://github.com/owncloud/core/pull/23443
