### ISSUE TITLE
Only try to get a preview if PHP is capable of doing so

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#24045]
If the PHP memory limit is set too low, PHP will crash while trying to render a preview. It's not too much of an issue if the process' only task is to generate a preview, but if it's one of many, then this may have unforeseen consequences.

Here is one suggestion for a workaround:
1. Get dimension and bit depth of image to process
2. Calculate memory requirements to process the image with GD
3. Compare the result to `getMB(ini_get('memory_limit')) - <avg memory used by a process>. We could use something like 70MB for the amount of memory PHP "normally" uses
4. If there is not enough memory, don't create a max preview and the user will see the media type icon

Now, the biggest problem with this approach comes from the determination of the amount of RAM an average PHP process uses as it depends on how PHP was compiled and what's it's usually doing.
The solution is to not be conservative since this only affects devices low on RAM. As soon as people set the memory limit to 256MB, then there is plenty of memory available to process images up to 30MP, which is good enough for casual users.
Professionals will know that they need a server with plenty of memory and 512MB will allow them to process 75MP images.

---

@icewind1991 @georgehrke @MorrisJobke @mmattel @bugsbane

**Comment by simonbuehler** [comment]
adding to this,

i have some huge images stored on the server and it always fails to generate the preview, a setting to ignore images greater then dimension x*y would be great to reduce load
