### ISSUE TITLE
ldap_control_paged_result_response(): No server controls in result

### ISSUE THREAD

**Issue by migle** [owncloud/core#24040]
I just upgraded from owncloud 9.0 to owncloud 9.0.1.
Now, I get the following errors by mail from the cron job:

[owncloud][PHP][3] ldap_control_paged_result_response(): No server controls in result at /usr/local/www/owncloud/apps/user_ldap/lib/ldap.php#70
[owncloud][PHP][3] ldap_control_paged_result_response(): No server controls in result at /usr/local/www/owncloud/apps/user_ldap/lib/ldap.php#70
[owncloud][PHP][3] ldap_control_paged_result_response(): No server controls in result at /usr/local/www/owncloud/apps/user_ldap/lib/ldap.php#70
[owncloud][PHP][3] ldap_control_paged_result_response(): No server controls in result at /usr/local/www/owncloud/apps/user_ldap/lib/ldap.php#70

Despite this, most things that I can see appear to work just fine.

I think I also had an error with the cron job when I upgraded to 9.0, which took me to patch one file, but I can't find the fix in the Internet now, and I can't tell if the error was the same.

**Operating system**: FreeBSD 10.3-RELEASE
**Web server:** Apache 2.4 (from ports)
**Database:** MariaDB 5.5 (pre-compiled pkg)
**PHP version:** 5.6.20 (pre-compiled pkg)
**ownCloud version:** 9.0.1 (from ports, 9.0.1_1)
**Updated from an older ownCloud or fresh install:** upgraded from 9.0

**Where did you install ownCloud from:** from FreeBSD ports, port revision 9.0.1_1
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```
#### LDAP configuration

```
+-------------------------------+---------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                         |
+-------------------------------+---------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                                                         |
| hasPagedResultSupport         |                                                                                                         |
| homeFolderNamingRule          |                                                                                                         |
| lastJpegPhotoLookup           | 0                                                                                                       |
| ldapAgentName                 |                                                                                                         |
| ldapAgentPassword             | ***                                                                                                     |
| ldapAttributesForGroupSearch  |                                                                                                         |
| ldapAttributesForUserSearch   |                                                                                                         |
| ldapBackupHost                |                                                                                                         |
| ldapBackupPort                |                                                                                                         |
| ldapBase                      | dc=ramos,dc=link                                                                                        |
| ldapBaseGroups                | dc=ramos,dc=link                                                                                        |
| ldapBaseUsers                 | dc=ramos,dc=link                                                                                        |
| ldapCacheTTL                  | 600                                                                                                     |
| ldapConfigurationActive       | 1                                                                                                       |
| ldapDynamicGroupMemberURL     |                                                                                                         |
| ldapEmailAttribute            | mail                                                                                                    |
| ldapExperiencedAdmin          | 0                                                                                                       |
| ldapExpertUUIDGroupAttr       |                                                                                                         |
| ldapExpertUUIDUserAttr        |                                                                                                         |
| ldapExpertUsernameAttr        | uid                                                                                                     |
| ldapGroupDisplayName          | cn                                                                                                      |
| ldapGroupFilter               | (&(objectclass=posixGroup)(gidNumber>=2001))                                                            |
| ldapGroupFilterGroups         |                                                                                                         |
| ldapGroupFilterMode           | 1                                                                                                       |
| ldapGroupFilterObjectclass    | posixGroup                                                                                              |
| ldapGroupMemberAssocAttr      | memberUid                                                                                               |
| ldapHost                      | ldapi:///                                                                                               |
| ldapIgnoreNamingRules         |                                                                                                         |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(cn=%uid)(displayName=%uid)(givenName=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     | cn;displayName;givenName;mail                                                                           |
| ldapLoginFilterEmail          | 0                                                                                                       |
| ldapLoginFilterMode           | 0                                                                                                       |
| ldapLoginFilterUsername       | 1                                                                                                       |
| ldapNestedGroups              | 1                                                                                                       |
| ldapOverrideMainServer        |                                                                                                         |
| ldapPagingSize                | 0                                                                                                       |
| ldapPort                      | 389                                                                                                     |
| ldapQuotaAttribute            |                                                                                                         |
| ldapQuotaDefault              |                                                                                                         |
| ldapTLS                       | 1                                                                                                       |
| ldapUserDisplayName           | displayName                                                                                             |
| ldapUserDisplayName2          |                                                                                                         |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                                                                          |
| ldapUserFilterGroups          |                                                                                                         |
| ldapUserFilterMode            | 0                                                                                                       |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                                           |
| ldapUuidGroupAttribute        | auto                                                                                                    |
| ldapUuidUserAttribute         | auto                                                                                                    |
| turnOffCertCheck              | 0                                                                                                       |
| useMemberOfToDetectMembership | 1                                                                                                       |
+-------------------------------+---------------------------------------------------------------------------------------------------------+
```

I use OpenLDAP 2.4 and the core, inetorgperson schemas.

This is a family server, still small but growing.

Also, I changed recently to ldapi:/// where I used to have localhost.
Also, I've used both 500 and 0 for ldapPagingSize.

None of these changes anything.

Thank you,

**Comment by LukasReschke** [comment]
@owncloud/ldap

**Comment by RealRancor** [comment]
@migle Do you mean this one: https://mailman.owncloud.org/pipermail/user/2015-July/001717.html

**Comment by migle** [comment]
No, that can't be it. I may be confused about this, maybe it's some other service, the issue I found ended pointing to a commit in github, and I was able to do a change on a single line. Maybe it was not owncloud at all.

Anyway: in this case, I use OpenLDAP 2.4, which I think is able to do paged results. Also, slapd leaves no errors in the log.

So, a better description:
1) Everything appears to work
2) When I use the command line (the same happens with the cron job), this happens:

```
# su -m www -c './occ ldap:search myusername'
[owncloud][PHP][3] ldap_control_paged_result_response(): No server controls in result at /usr/local/www/owncloud/apps/user_ldap/lib/ldap.php#70
My Name (myusername)
```

So, the search works, despite the error message (and I don't need paged results, the directory is really small).

3) Obviously, I can get rid of those messages by modifying the code in apps/user_ldap/lib/connection.php, I change the constructor by setting:

`$this->hasPagedResultSupport = false;`

The thing is, this has been happening after the update to 9.0.1 and php was not updated, php 5.6 and the php ldap module remain at 5.6.20.

**Comment by blizzz** [comment]
@migle Cannot reproduce. Did anything happen on LDAP side (e.g. config change, update)?

**Comment by migle** [comment]
No changes on the server side for a long time (I use version control on the config). However, the upgrade from php 5.6.18 to 5.6.20 is fairly recent. Just not on the same day as the owncloud update. I'll try a downgrade later.

**Comment by blizzz** [comment]
If this really would make a difference, please keep us updated :)

**Comment by migle** [comment]
Here's more info, to keep you updated and maybe get some clue...
Note, paged searches are irrelevant to me with my small directory. What bothers me is having had to modify a php file to shut up an error message.

So, in `apps/user_ldap/lib/access.php`, in function initPagedSearch, at line 1760, at the call to ldap->controlPagedResult, a variable named `$cookie` is empty. Now, I can only guess the role of this variable, because I know nothing about the LDAP protocol... but I guess it shouldn't be empty here. I think I know this, because I inserted a line such as the following just before the call

```
\OCP\Util::writeLog('user_ldap', 'Cookie '.$cookie.empty($cookie), \OCP\Util::ERROR);
```

The slightly complicated logic above this call appears to partially avoid the situation of this `$cookie` being null, empty or 0. However, it does not avoid this case...

The funny thing is that neither this function, not the function that appears to generate a cookie (getPagedResultCookie) appears to have changed from 9.0.0 to 9.0.1.

So, I'm off to investigate getPagedResultCookie, however, I would really appreciate some wild guess or something. This is really hard to me, I've never touched PHP before. I just guessed that it would probably be an imperative language and I think I just learned that things get converted to strings automatically and dot is the string concatenation operator...

**Comment by migle** [comment]
No!
Almost solved.

Here it goes: I use an uncommon database backend for OpenLDAP. The normal today is MDB. I use the LDIF backend which just stores everything on text files without indices.

Why I do that is outside the scope of this issue. But, I run a small directory at home, with under 20 users. I've been running OpenLDAP for well over 10 years now, and over those years it has been the main cause of downtime here. I run the LDIF backend, because although it is not fast, it certainly is robust and easy to recover.

So, guessing, I guessed that the paged searches are not possible with the LDIF backend. And I guessed right. Just dumping my database to MDB and using the MDB backend made owncloud quiet.

So, don't hit me. There are two questions:

- This is not a recent change in my OpenLDAP configuration, I've been happily using LDIF for longer than I use owncloud. So, really, owncloud 9.0.0 probably was not using paged searches or was silent about this. You could have told me this: "perhaps that's because before 9.0.1 paged searches were not actually happening with OpenLDAP".
- So, we've found out about a scenario in which a server which usually supports paged searches, really does not. So the hasPagedResultSupport() test is not so good. While my LDIF backend is probably rare in production, maybe there are more backends which don't support them.
- When this fails, the number of errors for a single run of the cron job is large, sometimes two error messages, sometimes around ten... So, it would be nice to still be able to run the server without paged results and not getting the emails from cron every 15 minutes.

Right now, the fix for me is setting hasPagedResultsSupport to false without testing.

In any case, maybe you want to change this from "bug" to a "feature request" if you consider that the long term solution would be to have an option to deactivate paged searches (actually, you say that setting the page size to zero disabled paged searches, but it doesn't, so this could still be considered a bug).
Or, you could consider that the problem is that the test in hasPagedResultsSupport is not good and it is a bug.

In any case, I won't be offended.
Thank you,

Maybe you need help translating the LDAP-related options to portuguese? The current translation appears to be google-translated and is totally incomprehensible.

**Comment by PVince81** [comment]
Please reopen in [user_ldap app repo](https://github.com/owncloud/user_ldap) if issue persists with 10.0.4 and the latest user_ldap app from marketplace.
