### ISSUE TITLE
Show a warning in the admin section when the PHP memory limit is set below 192MB

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#24046]
If users of an instance with a memory limit set to 128MB try to process images taken with a modern smartphone, PHP will regularly die because it doesn't have enough memory to process those large images.
While we can try to prevent PHP from dying, we still have to notify admins that the limit is set quite low and that it could have unforeseen consequences.

I picked 192MB as it's the minimum required, but 256MB would be better.

@jancborchardt

**Comment by jancborchardt** [comment]
cc @DeepDiver1975 @LukasReschke @karlitschek something for the admin settings, either the »Security & setup warnings« section or ideally the »Tips & tricks« cause it’s not really a breaking thing, right?

**Comment by karlitschek** [comment]
hmmm. 128 is the default. so i assume that most people have thus set. is there no way to handle this gracefully like for example not process large image if the memory limit is too low?

**Comment by oparoz** [comment]
@karlitschek - Yes, that's #24045 , but some users will wonder why they only get the media type icon for some images, so I think admins should be given some information about the problem.

**Comment by karlitschek** [comment]
True True. Let's make it a hint only because most people with 128MB and no huge pictures shouldn't be confused with that :-)

**Comment by DeepDiver1975** [comment]
9.1? @karlitschek

**Comment by karlitschek** [comment]
yes please :-)

**Comment by yasirunilan** [comment]
Can I work on this issue

**Comment by ajborka** [comment]
Has anyone worked on this issue yet?

**Comment by kaustubh-welankar** [comment]
Can I work on this issue? I'm new to the community and will be able to solve this bug.

**Comment by PVince81** [comment]
@kaustubh-welankar there was no PR since last time so yes you can work on this 😄

**Comment by kaustubh-welankar** [comment]
@PVince81 
I plan to add some code at the end of the file settings/Panels/admin/securitywarning.php 
I'll use the inbuilt function memory_get_usage. What should the warning message say and what changes should I make to the l10n files?
