### ISSUE TITLE
Updating problem to  version 8.2.1 via update app

### ISSUE THREAD

**Issue by Dospanes** [owncloud/core#24063]
I try to update my owncloud with the updater app. Always when I try to login to ownlcloud I'm asked to update which fails with the following error message:

Updating ownCloud to version 8.2.1, this may take a while.

```
Preparing update
Set log level to debug - current level: "Warning"
Turned on maintenance mode
Exception: Updates between multiple major versions and downgrades are unsupported.
The update was unsuccessful. Please report this issue to the ownCloud community.
```

I know that this has already been reported e.g. here: #20640 and here: #20660 
but I don't know how to solve my problem. How can I disable the automatic updater and do the manual update? I have owncloud running on a Synology and can still access all the files via commandline or the Synology interface.

**Comment by RealRancor** [comment]
@Dospanes Please close here and see https://owncloud.org/support where to ask such support questions.

The forums have a FAQ https://forum.owncloud.org/viewtopic.php?f=17&t=32087. If you have further questions please ask there.

**Comment by Dospanes** [comment]
ok thanks!
