### ISSUE TITLE
File list doesn't refresh until I do a scan

### ISSUE THREAD

**Issue by bbouayad** [owncloud/core#24060]
### Steps to reproduce
1. Add or remove a file/directory from SSH/SFTP Client
2. Access to the server through owncloud web interface
3. New files aren't there / Old files are still there

### Expected behaviour
The owncloud web interface should show what the server currently contains

### Actual behaviour
It shows an old version of files/directories list which might actually be deleted yet

### Server configuration
**Operating system**:
Linux debian 3.2.0-4-amd64

**Web server:**
Apache 2.4.18

**Database:**
MySQL 5.6.28-1

**PHP version:**
PHP 5.6.19-2

**ownCloud version:** (see ownCloud admin page)
OC 9.0.0

**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**
Git repo 

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

  - activity: 2.2.1
  - calendar: 1.0
  - comments: 0.2
  - contacts: 1.1.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - galleryplus: 15.0.0
  - music: 0.3.10
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc57mss1v7z5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/example.com",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "loglevel": 0,
        "mail_smtpmode": "php",
        "mail_smtpsecure": "tls",
        "mail_from_address": "xxx.xxxx",
        "mail_domain": "hotmail.fr",
        "mail_smtphost": "smtp.live.com",
        "mail_smtpport": "587"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Local

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No


```

### Client configuration
**Browser:**
Chrome 

**Operating system:**
Windows 8.1

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"mIXRBSjYStfGiZiuZLKI","remoteAddr":"194.51.114.170","app":"no app in context","message":"Exception: {\"Exception\":\"DomainException\",\"Message\":\"Contacts tables are missing. Nothing to do.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/migrateaddressbooks.php(83): OCA\\\\Dav\\\\Migration\\\\AddressBookAdapter->setup()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/application.php(186): OCA\\\\Dav\\\\Migration\\\\MigrateAddressbooks->setup()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/install.php(26): OCA\\\\Dav\\\\AppInfo\\\\Application->migrateAddressbooks()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(621): include('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(572): OC_Installer::includeAppScript('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/installer.php(546): OC_Installer::installShippedApp('dav')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/setup.php(370): OC_Installer::installShippedApps()\\n#7 \\\/var\\\/www\\\/owncloud\\\/core\\\/controller\\\/setupcontroller.php(64): OC\\\\Setup->install(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(823): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/migration\\\/addressbookadapter.php\",\"Line\":72}","level":3,"time":"2016-03-29T15:40:11+00:00"}
```

**Comment by RealRancor** [comment]
@bbouayad You're not supposed to manually upload / put / modify stuff within the datadir. This is unsupported and documented at various places:

https://forum.owncloud.org/viewtopic.php?f=17&t=32183

**Comment by bbouayad** [comment]
Actually I don't upload / put / modify within the datadir. I have a symlink in my datadir to an external storage disk. I upload / put / modify files into this external disk and I have to scan the files in order to see what have changed in my owncloud web interface.

**Comment by RealRancor** [comment]
@bbouayad Symlinks are even worse:

https://doc.owncloud.org/server/9.0/admin_manual/release_notes.html#owncloud-does-not-follow-symlinks

Please don't do that and use the external storage app or a command line webdav client.

**Comment by bbouayad** [comment]
Ok my bad !
