### ISSUE TITLE
files:transfer-ownership command should show a warning message if there are no files/folders to be transferred.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#24061]
### Steps to reproduce
1. Create 2 oC users, user1 and user2
2. Delete all files that could exist in user1 account
3. As admin via CLI run  -->  sudo -u www-data ./occ files:transfer-ownership user1 user2
### Expected behaviour

A warning message like 'No files/folders to transfer' should be shown
### Actual behaviour

A new empty folder  is created in user2 account
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**"version":"9.0.1.3","versionstring":"9.0.1","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Enabled:
- activity: 2.2.1
- admin_audit: 0.7
- comments: 0.2
- dav: 0.1.6
- encryption
- enterprise_key: 0.1.0
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_external: 0.5.2
- files_pdfviewer: 0.8
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- firewall: 2.3.0
- firstrunwizard: 1.1
- gallery: 14.5.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
- windows_network_drive: 0.2.33
- workflow: 0.1.3
  Disabled:
- announcementcenter
- external
- files_antivirus
- files_drop
- files_ldap_home
- objectstore
- password_policy
- sharepoint
- user_external
- user_ldap
- user_shibboleth

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```

```
### Client configuration

**browser**

 Firefox

**Comment by PVince81** [comment]
Backlog for now, PRs welcome

**Comment by phil-davis** [comment]
Done by PR #30516 
Backport to ``stable10`` PR #30612
