### ISSUE TITLE
Word wrap causes tooltips to break after each letter

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/core#24069]
Apparently caused by #22760.

![bildschirmfoto von 2016-04-18 15-10-13](https://cloud.githubusercontent.com/assets/1374172/14605201/d01731be-0577-11e6-8ba3-55e90c305f5e.png)

@MorrisJobke @ErikPel was the fix backported?

**Comment by nickvergessen** [comment]
It was not backported yet

**Comment by MorrisJobke** [comment]
> @MorrisJobke @ErikPel was the fix backported?

Backports are (usually) always shown with the brown labels: see https://github.com/owncloud/core/pull/23935 for example ;)

**Comment by LukasReschke** [comment]
Also breaks the app labels.

**Comment by LukasReschke** [comment]
Revert is at https://github.com/owncloud/core/pull/24138
