### ISSUE TITLE
[oC 9.0.1] Apache error 404 with reverse proxy configured in .htaccess

### ISSUE THREAD

**Issue by zirydy** [owncloud/core#24077]
What used to work for me in setting up reverse proxy in ownCloud 7 & 8 isn't working anymore in ownCloud 9. I was hoping 9.0.1 would fix the issue as there were some Apache issues reported, but the problem still persists.

**Note:**
I have read the online documentation. It doesn't work on my setup without modifying `.htaccess`
https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/reverse_proxy_configuration.html

### Steps to reproduce
1. Install ownCloud 9.0.1
2. Set up reverse proxy (see `config.php` and `.htaccess` below)
3. Configure ownCloud using a browser

### Expected behaviour
ownCloud should run over reverse proxy

### Actual behaviour
An Apache error 404 is displayed:
> Object not found! 
> The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.
> Error 404
> If you think this is a server error, please contact the webmaster. 

### Server configuration
**Operating system**:
Debian 6

**Web server:**
Shared Hosting

**Database:**
MySQL 5.5.47

**PHP version:**
PHP 5.6

**ownCloud version:**
9.0.1

**Updated from an older ownCloud or fresh install:**
Fresh Install

**Where did you install ownCloud from:**
https://owncloud.org/install/

**The content of .htaccess**

```
[...]
<IfModule mod_rewrite.c>
  RewriteEngine on
  RewriteCond %{REMOTE_ADDR} !^10\.30\.7\.1(?:37|38|39|40)$
  RewriteRule ^ https://ssl.proxy.com/%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
[...]
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'overwritehost' => 'ssl.proxy.com',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/abc.com/owncloud',
  'overwritecondaddr' => '^10\\.30\\.7\\.1(?:37|38|39|40)$',
  'integrity.check.disabled' => true,
);
```

**Comment by LukasReschke** [comment]
Using a SSL proxy like ssl.proxy.com will make your whole ownCloud insecure. Everybody on that domain can do nasty stuff to your data. You don't want to do that.

It's a bad idea to use that. Your data is probably less secure than without using this SSL proxy stuff. The Same-Origin Policy is basically gone.

**Comment by LukasReschke** [comment]
Also: https://owncloud.org/support. We don't have an access for one of those SSL proxy thingies and require more information on where it is failing etc.

We also don't support any manual modifications in `.htaccess` which is what you have done.

**Comment by zirydy** [comment]
I suppose you read German... (guessing from your name and location)? I'm following the instruction below (from Host Europe):

Sounds like I won't be able to use ownCloud starting with version 9 then.

> > SSL-Verschlüsselung mit SSL-Proxy
> 
> Bei Ihrem Produkt ist es möglich, eine SSL-Verschlüsselung über unseren SSL-Proxy zu erreichen. Wie Sie diesen aktivieren und was Sie bei der Programmierung Ihrer Seite beachten müssen, erfahren Sie hier.
> 
> Um Daten im Web verschlüsselt zu übertragen, bedient man sich des SSL ("Secure Socket Layer"). Erkennbar sind solche Adressen durch die Angabe des Protokolls "https:" an Anfang der URL.
> 
> Die für dieses Verfahren notwendigen Zertifikate hängen von der Adresse (Hostname, "CN") ab. Darüber hinaus ist die Zertifizierung durch eine anerkannte Stelle ("CA") mit (nicht nur finanziellem) Aufwand verbunden. Desweiteren kann man pro IP-Adresse normalerweise nur ein SSL-Zertifikat nutzen. Der SSL-Proxy kann für alle Produkte mit dem Feature "SSL-Proxy" genutzt werden. Bei einigen Produkten ist aber auch die "Einbindung eigener SSL-Zertifikate möglich". Lesen Sie hier nach, wie für diese Produkte ein SSL-Zertifikat bestellt werden kann: 1. Schritt - Allgemeine Informationen.
> 
> Um Sie dennoch in den Genuss von SSL-Verschlüsslung kommen zu lassen, bedienen wir uns eines Kunstgriffes, "SSL-Proxy" genannt. Dieser erlaubt es, Ihre Domain unter "https://ssl.webpack.de/nureinbeispiel.de/" aufzurufen. Ersetzen Sie bitte "nureinbeispiel.de" durch den Namen Ihrer Domain. Dadurch gilt es bei der Programmierung der Seite darauf zu achten, dass alle Links relativ sind (z.B. "../index.html"), da Sie ansonsten bei absoluter Verlinkung wieder die unverschlüsselte Seite laden. Alternativ können Sie bestimmte Bereiche Ihrer Homepage auch direkt absolut auf die o.a. URL setzen, so dass diese immer über https aufgerufen werden.
> 
> Der SSL Proxy kann auch mit unseren Third Level Domains genutzt werden.
> 
> Natürlich können Sie Ihre Seiten nach wie vor über http unverschlüsselt abrufen. Sie möchten das Ihre Seite nur noch über https aufrufbar ist? Dies können Sie nur durch eine von Ihnen selbst zu erstellende .htaccess-Datei lösen, in dem Sie alle Aufrufe über http auf https umleiten. Unterstützt wird .htaccess ab dem Webpack L.
> 
> Auch die Verwendung von Subdomains und vollen Pfaden ist möglich (z.B.: https://ssl.webpack.de/secure.webpack-demo.de/gesichert/index.html).
> 
> 
> Für die Logfileauswertung ist zu beachten, dass dort nicht mehr die eigentliche IP-Adresse des abrufenden Rechners, sondern die unseres Proxy erscheint. Dies sind derzeit die IP-Adressen 10.30.7.137, 10.30.7.138, 10.30.7.139 und 10.30.7.140.
> 
> Möchten Sie sicherstellen, dass Ihre Webseite immer über den SSL-Proxy abgerufen wird, können Sie dies über eine .htaccess-Datei erreichen (ab WebPack L). Verwenden Sie hierzu folgende Regel:
> 
> RewriteEngine On
> RewriteCond %{REMOTE_ADDR} !^10.30.7.1(?:37|38|39|40)$
> RewriteRule ^ https://ssl.webpack.de/%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
> 
> Um aus Ihrem Skript heraus zu testen, ob der Zugriff über den Proxy erfolgt, ist eine Abfrage dieser Art möglich:
> 
> if( isset( $_SERVER['HTTP_X_FORWARDED_SERVER'] ) ) {
> echo "SSL-Proxy";
> } else {
> echo "Kein SSL-Proxy";
> }
