### ISSUE TITLE
 $HTTP_RAW_POST_DATA is deprecated

### ISSUE THREAD

**Issue by drfuture** [owncloud/core#24088]
### Steps to reproduce
1. populate php-error-messages
2. aktivate Full Log
3. look

### Expected behaviour
Don't show this Message

### Actual behaviour
Error:
Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0

### Server configuration
**Operating system**:
openSuse 42
**Web server:**
nginx 1.9.14
**Database:**
mysql
**PHP version:**
php5.6.20
**ownCloud version:** (see ownCloud admin page)
9.0.1
**Updated from an older ownCloud or fresh install:**
fresh install
**Where did you install ownCloud from:**
source
**Signing status (ownCloud 9.0 and above):**
ok
```
**List of activated apps:**
Collaborative tags 0.2
Comments 0.2
Deleted files 0.8.0
First Run Wizard 1.1
Mail 0.4.0
Mail Template Editor 0.1
Notifications 0.2.3
PDF Viewer 0.8
Share Files 0.9.1
Text Editor 2.1
Update notification 0.1.0
Versions 1.2.0
Video player 0.9.8
Calendar 1.0
Contacts 1.0.0.0
Direct Menu 0.7.1
```
**The content of config/config.php:**
<?php
$CONFIG = array (
'instanceid' => 'ocyizwfdz54j',
'passwordsalt' => '00',
'secret' => '00',
'trusted_domains' => 
array (
0 => 'cloud.abc.de',
1 => 'tester.de',
),
'datadirectory' => '/home/www/abc.de/cloud/data',
'overwrite.cli.url' => 'https://cloud.abc.de',
'dbtype' => 'mysql',
'version' => '9.0.0.19',
'dbname' => 'owncloud',
'dbhost' => 'localhost',
'dbtableprefix' => 'oc_',
'dbuser' => 'user',
'dbpassword' => 'password',
'logtimezone' => 'UTC',
'installed' => true,
'defaultapp' => 'mail',
'maintenance' => false,
'loglevel' => 0,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)
No
```

**Comment by RealRancor** [comment]
@drfuture Maybe just set that as advised:

> To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini

**Comment by drfuture** [comment]
:baby_chick: yes thats simple - and the error is not shown, I can disable the error-reporting too - but the funktion would be disabled in a newer php version and owncloud 9 is the *big* new version so in my opinion it would be great not to use depraced funktions.

**Comment by LukasReschke** [comment]
> but the funktion would be disabled in a newer php version and owncloud 9 is the big new version so in my opinion it would be great not to use depraced funktions.

The function is not used, it's just PHP that throws that warning. Either set the config flag or live with that warning. 😉
