### ISSUE TITLE
Folder size not propagated when uploading as share recipient with encryption enabled

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24105]
### Steps

1. Setup OC 9.0.1
1. Enable encryption
1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create a folder "test"
1. Share "test" with "user2"
1. Login as "user2"
1. Create a subfolder "test/sub"
1. Upload a non-empty file into "test/sub" in the web UI
1. Navigate to folder "test"
1. Check the size of the folder "sub"

### Expected result
Size of "sub" matches contents

### Actual result
Size of "sub" stays zero.
Entry in `oc_filecache` also has a size of zero.

### Versions
ownCloud 9.0.1

Note that if you do the same without encryption it works fine.
So I suspect that some of the fileinfo size overrides code is messing up with folder size propagation.

@schiesbn @icewind1991

**Comment by PVince81** [comment]
This is bad because it could also doesn't update the share owner's root folder size, so the usage quota isn't updated properly.

**Comment by PVince81** [comment]
Also the folder sizes cannot properly be corrected with occ files:scan because of encrypted size vs unencrypted size!

Regression check:
- v8.2.2: ok
- v8.2.3: ok
- stable8.2: ok
- v9.0.0: fail
- v9.0.1: fail

**Comment by PVince81** [comment]
Bisect was tough due to many internal server errors on the way.

It pointed at this commit: 1369f2c6840e6bbac50526236771cb730a74f975 from PR https://github.com/owncloud/core/pull/21851

Before that commit, even though the upload fails with 500 error, the folder size is correctly updated.
After that commit, the folder size is either -1 or 0. So not sure if that commits is directly related or if there is something else at play.

@icewind1991 can you have a look ?

**Comment by icewind1991** [comment]
Ok, could reproduce in a unit test

**Comment by icewind1991** [comment]
Fix is here https://github.com/owncloud/core/pull/24124
