### ISSUE TITLE
Reset storage availability when external storage config changed

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24114]
Whenever an external storage config has changed, the availability check for the storage needs to be reset to make sure the web UI can find it instead of assuming it's still unavailable.

This situation can be triggered by mounting an external storage, accessing it, then changing the remote password to make it unavailable. Then change the password in the config too.

There are three places where resetting the availability flag/timestamp should happen, if possible:
- as admin when changing the config for a system-wide mount (might be tricky to resolve to storages)
- as user when changing the config for a personal mount
- as user when entering a new password in the "credentials changed, please enter new password" dialog

The reason for resetting the flag is because whenever a user enters a new password, the storage might still be marked unavailable, so the user might think the password was wrong and will reenter it.

@icewind1991 @Xenopathic @MorrisJobke

**Comment by PVince81** [comment]
also ideally there should be an API to be able to reset that flag, not sure on what level

**Comment by Xenopathic** [comment]
It does, doesn't it? Changing the config in the settings triggers an immediate recheck, which will set the availability accordingly.

**Comment by Xenopathic** [comment]
Oh god, this might be a race condition. If ownCloud is in the process of rechecking availability when the storage config is changed, the storage might be marked as unavailable due to the race...

**Comment by PVince81** [comment]
Hmmm not sure. @jvillafanez said he couldn't reproduce the issue.

**Comment by PVince81** [comment]
Cannot reproduce => close
