### ISSUE TITLE
Clarify "apps" folder and "core" in integrity Check results

### ISSUE THREAD

**Issue by ghost** [owncloud/core#24110]
### Steps to reproduce
1. Have invalid files somewhere within an app in the /apps/ folder or in the root directory
2. Trigger integrity check
3. Check the failed files
### Expected behaviour

```
- /
      - INVALID_HASH
              - /index.php
              - /version.php
      - EXTRA_FILE
              - /test.php
- /apps/calendar
      - EXCEPTION
              - OC\IntegrityCheck\Exceptions\InvalidSignatureException
              - Signature data not found.
```
### Actual behaviour

```
- core
      - INVALID_HASH
              - /index.php
              - /version.php
      - EXTRA_FILE
              - /test.php
- calendar
      - EXCEPTION
              - OC\IntegrityCheck\Exceptions\InvalidSignatureException
              - Signature data not found.
```

The main problem here is that also a `core` folder exists within the ownCloud install folder. Furthermore its not always clear for a user that the `calendar` is located within the apps folder (https://github.com/owncloud/core/issues/24109)

cc @LukasReschke

**Comment by LukasReschke** [comment]
Good point. I'll see to adjust this, might indeed makee that stuff easier to understand :+1:

**Comment by RealRancor** [comment]
I see currently one issue but maybe that could be solved:

The /apps/ folder can be configured differently
