### ISSUE TITLE
Update from stable9 to master fails in web UI

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#24115]
Upgrade from stable9 (fix_24032) to master (hide-hidden-files) fails.

"Updates need to be installed. Please use the command line updater."

<img width="348" alt="bildschirmfoto 2016-04-20 um 11 23 39" src="https://cloud.githubusercontent.com/assets/245432/14669752/8b8e6bd8-06ea-11e6-95d7-82112c014dc8.png">

Works totally fine on command line, but web UI only shows the above.

cc @LukasReschke @DeepDiver1975

**Comment by Xenopathic** [comment]
Hah, looks like the default config values for `update.disable-web` introduced with #23922 are inconsistent - the update.php defaults to true (forcing occ) but the template defaults to false (allowing web update).  cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
I will take care
