### ISSUE TITLE
Forbid PROPPATCH on oc:checksum

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24125]
### Steps:

proppatch-checksum.txt:
```xml
<?xml version="1.0"?>
<d:propertyupdate xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:set>
    <d:prop>
                <oc:checksum>DEADBEEF</oc:checksum>
    </d:prop>
  </d:set>
</d:propertyupdate>
```

`curl -X PROPPATCH -H "Content-Type: text/xml" --data-binary "@proppatch-checksum.txt" http://admin:admin@localhost/owncloud/remote.php/files/welcome.txt`

### Expected result
Property NOT set, PROPPATCH response must return 403 for oc:checksum.

### Actual result
The property does not get set in `oc_filecache`, however it lands in the `oc_properties` table!

### Versions
ownCloud 9.1 git master

@rullzer I think you need to add something in the FilesPlugin to make this property read-only

**Comment by rullzer** [comment]
Ok will fix

**Comment by rullzer** [comment]
@PVince81 the reason this works is because the single checksum is not defined...

```xml
<?xml version="1.0"?>
<d:propertyupdate xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:set>
    <d:prop>
        <oc:checksums>
                <oc:checksum>DEADBEEF</oc:checksum>
        </oc:checksums>
    </d:prop>
  </d:set>
</d:propertyupdate>
```

Note the surrounding `oc:checkums`. We could still block the single version if you really want..

**Comment by PVince81** [comment]
Ah, of course. I forgot that the API accepts a list of checksums.
Then it works as expected.
