### ISSUE TITLE
Federated Sharing: Edit permission with/without delete

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#24128]
### Steps

User1 (Server1) shares a folder with User1 (Server2). Can edit disabled.

![screen shot 2016-04-20 at 18 46 13](https://cloud.githubusercontent.com/assets/14894746/14683060/1133288a-0729-11e6-8694-c298b35b37c9.png)

User1 (Server2) wants to re-share the folder with another user in the same server (User2)

![screen shot 2016-04-20 at 18 45 45](https://cloud.githubusercontent.com/assets/14894746/14683075/1e7d3f3a-0729-11e6-9bd7-6d4f27dc62c4.png)

### Actual Behaviour

User1 (Server2) can re-share with delete permission (minimum permissions = 25 ¿?) but he can not delete content of the folder. User2 is granted to delete but can not delete.

![screen shot 2016-04-20 at 18 51 18](https://cloud.githubusercontent.com/assets/14894746/14683084/2bc07e64-0729-11e6-8267-a5766a4bdb64.png)

### Expected Behaviour

Can edit permission = create + change + delete. If a federated sharee is not granted to edit, he can not neither create, nor change or delete. 

Related question: Why is 25 set as minimum permissions? 

Server version: 

{"installed":true,"maintenance":false,"version":"9.0.1.3","versionstring":"9.0.1","edition":"Enterprise"}

**Comment by rullzer** [comment]
Yes, known and will be fixed with https://github.com/owncloud/core/pull/23918

**Comment by rullzer** [comment]
@jesmrec can you retest on master?

**Comment by PVince81** [comment]
Somewhat related to https://github.com/owncloud/core/issues/24868

**Comment by PVince81** [comment]
Works for me on master. The delete permission appears when "can edit" was selected for a federated share.
