### ISSUE TITLE
no upgrade to version nine porposed

### ISSUE THREAD

**Issue by olaulau** [owncloud/core#24139]
### Expected behaviour
an upgrade should be available through the admin panel

### Actual behaviour
no upgrade possible, through admin panel.
php occ upgrade doesn't want to upgrade too ("ownCloud is already latest version")

### Server configuration
**Operating system**: 
ubuntu server 12.04

**Web server:** 
apache 2.2

**Database:** 
mariadb 10

**PHP version:** 
5.6 & 7.0

**ownCloud version:** (see ownCloud admin page)
8.2.3.2

**Updated from an older ownCloud or fresh install:**
upgraded many times since 8.1

**Where did you install ownCloud from:**
full tar.bz2 download

**List of activated apps:**
  - activity: 2.1.4
  - appframework: 0.104
  - bookmarks: 0.6
  - calendar: 0.8.2
  - contacts: 0.5.0.0
  - direct_menu: 0.7.1
  - documents: 0.11.1
  - encryption: 1.1.0
  - external: 1.2
  - files: 1.2.1
  - files_gpxviewer_extended: 1.4
  - files_locking: 
  - files_mv: 0.8.2
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - mozilla_sync: 1.4
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - storagecharts2: 2.6.1
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updater: 0.6

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocu5o6fpz5mn",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "test.laulau.ovh"
        ],
        "datadirectory": "\/data\/web\/b9\/2e\/25\/htdocs\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "8.2.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
firefox, chrome

**Operating system:**
ubuntu linux

**Comment by RealRancor** [comment]
Currently expected: http://owncloud.10557.n7.nabble.com/where-is-9-0-1-auto-updater-and-more-td17111.html

Only 9.0.2 will be available for the updater
