### ISSUE TITLE
Public link of shared folder shows no files

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#24147]
### Steps to reproduce
1. Share a folder with public link
2. Upload a file into the folder
3. Open public link

### Expected behaviour
File list should be displayed

### Actual behaviour
Only ownCloud header is visible, no file list:
> filelist.js?v=3e12e96…:209 Uncaught TypeError: Cannot read property 'getFilesConfig' of undefined

cc @rullzer you cleaned up too much
@schiesbn

**Comment by PVince81** [comment]
@nickvergessen is this happening in 9.0 too or master only ?

**Comment by nickvergessen** [comment]
Milestone is 9.1 :wink:

**Comment by rullzer** [comment]
I did not break it... bisect points me to: 6c5696d3a84ff71fc5ddb53b490bbc77f5c119f5
@ChristophWurst seems you broke it :wink:

**Comment by nickvergessen** [comment]
Right, filelist requires app since then, so @ChristophWurst caused it
