### ISSUE TITLE
Activity Stream does not show renamed files

### ISSUE THREAD

**Issue by alvar-freude** [owncloud/core#24176]
### Steps to reproduce
1. Create a folder or file (via eb interface or locally; when locally: wait until synced)
2. Rename it
3. Look at activity page in web frontend or oc_activity table in database

### Expected behavior
The renaming should be recorded in the activity

### Actual behavior
Nothing is recorded: the oc_activity table has no entry about the renamed file or folder – and therefore it can't be shown in activity stream.

Everything in the table oc_filecache is OK.

OC missed to record renamed files.

### Hint
In SQL we have a wonderful thing called triggers. Such things like history tables (like oc_activity) can't be wrong, when filled by triggers (except the triggers have bugs). And when everything is done right, it can't be manipulated by a broken app or unprivileged user (e.g. no write access to the history and changes in main table are logged automatically). But oc_filecache seems to miss a column "last_change_by" to do this here.

### Server configuration
**Operating system**: FreeBSD 10

**Web server:** Apache 2.4

**Database:** PostgreSQL 9.4

**PHP version:** 5.5

**ownCloud version:** ownCloud 9.0.1 (stable)

**Updated from an older ownCloud or fresh install:** Updated, but was the same in all older versions

**Where did you install ownCloud from:** FreeBSD pkg, locally build packages via Poudriere

**Signing status (ownCloud 9.0 and above):** 

```
No errors have been found.
```

**List of activated apps:**

```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.1.0.0
  - dav: 0.1.6
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - files_external
  - tasks
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
{
    "system": {
        "instanceid": "ocmaplttgufu",
        "dbtype": "pgsql",
        "dbhost": "**doesn't matter***",
        "dbname": "**maybe something***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "remember_login_cookie_lifetime": 3888000,
        "mail_domain": "***doesn't matter***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***doesn't matter***",
        "proxy": "***doesn't matter***:***doesn't matter***",
        "log_type": "syslog",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***doesn't matter***",
            "***doesn't matter***"
        ],
        "datadirectory": "\/usr\/local\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/***doesn't matter***",
        "overwriteprotocol": "https",
        "version": "9.0.1.3",
        "dbtableprefix": "oc_",
        "installed": true,
        "preview_libreoffice_path": "\/usr\/local\/bin\/libreoffice",
        "theme": "",
        "maintenance": false,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "loglevel": "0",
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": false
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** not OC encryption

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)

not used

### Client configuration
**Browser:** Obviously not dependent on browser …

**Operating system:** Obviously not dependent on client OS …

#### Web server error log

doesn't matter

#### ownCloud log (data/owncloud.log)
```
no log when doing this
```

#### Browser log

doesn't matter

**Comment by RealRancor** [comment]
@alvar-freude For issues within the activity app you should reopen that in:

https://github.com/owncloud/activity/issues

Before doing this make sure that you have activated the following in your personal settings:

- A file or folder has been changed (Stream ticked)
- List your own actions in the stream

**Comment by RealRancor** [comment]
@alvar-freude Ah, already available here: https://github.com/owncloud/activity/issues/375 so you could just close this issue and follow there.

**Comment by alvar-freude** [comment]
Yes, activity stream for renamed files is active. But nevertheless: the **logging** should happen always, only the display of the log message may be switched of.

**Comment by alvar-freude** [comment]
Sorry, i thought the logging itself is done in core. 
Therefore: closed.
