### ISSUE TITLE
User menu spinner keeps getting displayed on Ctrl+Click

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#24185]
This menu also needs the same fix as the apps menu: When you click an entry with Ctrl+Click, do not show the spinner and close the menu. :)

Follow-up to https://github.com/owncloud/core/pull/23916

**Comment by skjnldsv** [comment]
@ChristophWurst bump :D

**Comment by ChristophWurst** [comment]
9.1 is in feature freeze now, moving to 9.2

**Comment by PVince81** [comment]
moved to general design / UX / styling issues group ticket: https://github.com/owncloud/core/issues/27578
