### ISSUE TITLE
Personal & Admin settings restructuring

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#24188]
Currently the Personal and Admin settings are both very long pages with anchor navigation on the left side. This has several issues:
- Some sections like logging, LDAP and other admin settings don’t get the space they need or look strange in the page since they have intermittent scrollable areas or a tabbed interface.
- It’s a bit strange to navigate and see where sections and and others begin. Even with whitespace this is difficult to manage, so we should allow people to focus and make the left navigation the primary mode of navigation.

We would simply make it so that it’s multi-page, with the left navigation staying like it is, but opening the different sections. Basically like we do it in Files, Help and other apps already.
In that same pass, we should consolidate the Personal and Admin settings into one to simplify. In the user menu we would have one entry »Settings«. The left navigation would then have the few Personal settings entries on top. After a heading »Admin«, all the admin settings navigation entries would show.

cc @owncloud/designers and @ChristophWurst @karlitschek as discussed.

**Comment by jancborchardt** [comment]
A bit related: The ability to search in the settings: https://github.com/owncloud/core/issues/16875

**Comment by karlitschek** [comment]
yes. as discussed

**Comment by DeepDiver1975** [comment]
@ChristophWurst it might be necessary to adjust the OCP api in order to allow apps to register their setting pages. Please make sure the old mechanism continues to work.
Feel free to ping be in case of question regarding the OCP api
