### ISSUE TITLE
Login Button not working

### ISSUE THREAD

**Issue by cusatxpress** [owncloud/core#24190]
### Steps to reproduce

1. Downloaded setup-owncloud.php in the directory of my sub domain download.cusatxpress.com.
2. setuped the owncloud.
3. Synced the data.
4. and after a while, when i tried to login the **login seems not working (login button returns nothing).**

### Expected behaviour

1. After Admin username and password when pressed login / Enter press logs the admin/user in.

### Actual behaviour
1. Returns nothing. Simply sits there just like I never pressed login /Enter.

### Server configuration
**Linux**:

**Web server:**

**MySQL Database.**

**5.4.45**

**9.0.1** 

**Fresh Install:**

**setup-owncloud.php:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed  
paste the results here.  // **CANT LOGIN**
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php: <?php
$CONFIG = array (
  'instanceid' => 'ochlck7tlu2o',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'download.cusatxpress.com',
  ),
  'datadirectory' => '/home/USERNAME/public_html/download/data',
  'overwrite.cli.url' => 'http://download.cusatxpress.com',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => '',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
);
**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder,

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
<?php
$CONFIG = array (
  'instanceid' => 'ochlck7tlu2o',
  'passwordsalt' => '',
  'secret' => 'I2xTPc6/UISBVYG2waRhFwOfB+Anjd3ybASERByZRACOYApW',
  'trusted_domains' => 
  array (
    0 => 'download.cusatxpress.com',
  ),
  'datadirectory' => '/home/USERNAME/public_html/download/data',
  'overwrite.cli.url' => 'http://download.cusatxpress.com',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => '',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/... No
**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... No

**Comment by tflidd** [comment]
Owncloud-logfiles or webserver-logfiles don't reveal more details?

**Comment by sahilamanu** [comment]
Funny thing is, it works fine  on Mobile ( Chrome Android).

**Comment by nickvergessen** [comment]
Are you maybe using adblock and it prevents one of the JS files to be loaded?

**Comment by sahilamanu** [comment]
Thanks. I think the script was getting blocked. It's working now.

**Comment by cusatxpress** [comment]
Thanks .. working fine !!!
