### ISSUE TITLE
errors in owncloud.log

### ISSUE THREAD

**Issue by ikarus13** [owncloud/core#24194]
### Steps to reproduce
1. Listing content with Firefox
2.
3.

### Expected behaviour
Tell us what should happen
owncloud.log should stay clean...

### Actual behaviour
Tell us what happens instead

A lot of entries in owncloud.log like this:
{"reqId":"VxoDjEBNOWcL8-RiCrZBnwAAAAk","remoteAddr":"xxx.xxx.xxx.xx","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/owncloud\/apps\/files_external\/lib\/config\/configadapter.php#75","level":3,"time":"2016-04-22T12:57:16+02:00","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"xxxxx"}

### Server configuration
**Operating system**:
Scientific Linux release 7.2 (Nitrogen)
**Web server:**
httpd-2.4.6-40.sl7.x86_64
**Database:**
mariadb-server-5.5.47-1.el7_2.x86_64
**PHP version:**
PHP 7.0.5
**ownCloud version:** (see ownCloud admin page)
OC 9.0.1 stable
**Updated from an older ownCloud or fresh install:**
Update
**Where did you install ownCloud from:**
Repository
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: true
  - dav: 0.1.6
  - documents: true
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - news: 8.4.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - appframework
  - encryption
  - external
  - federation
  - firstrunwizard
  - mozilla_sync
  - superlog
  - user_external
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

--------------
sh-4.2$ php occ config:list system
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "instanceid": "513ef09ca9cb5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/html\/owncloud_data",
        "overwrite.cli.url": "\/var\/www\/html\/owncloud",
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "version": "9.0.1.3",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "forcessl": true,
        "theme": "",
        "log_type": "owncloud",
        "logfile": "\/var\/log\/owncloud.log",
        "logtimezone": "Europe\/Berlin",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "trusted_domains": [
            "xxxxxxxx.de",
            "xxxxxxxx"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtphost": "mail.xxxxxxx.de",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "xxxxxx",
        "mail_domain": "xxxxxxx.de",
        "updatechecker": false,
        "trashbin_retention_obligation": "auto"
    }
}
------------------------------------------------------

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
2 Directories as local storages which are mounted as samba and nfs


**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
"reqId":"VxoDjEBNOWcL8-RiCrZBnwAAAAk","remoteAddr":"xxx.xxx.xxx.xx","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/owncloud\/apps\/files_external\/lib\/config\/configadapter.php#75","level":3,"time":"2016-04-22T12:57:16+02:00","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"xxxxx"}
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ikarus13** [comment]
Hi,
good or bad news:
There is annother problem in combination. The reason for the logentries is that i set up the directories for multiple goups. And annother affect is, that i can see the root directory of the server instead of the shared directory. Nice to see files like password and so on...
If i delete the second group everything works well, no log entries.

Greetings,

ikarus

**Comment by RealRancor** [comment]
This sounds quite similar to https://github.com/owncloud/core/issues/23617 or am i wrong?

**Comment by ikarus13** [comment]
Yes, sounds so.
I will look into the database, but i am not an expert :-(

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/24003 and https://github.com/owncloud/core/issues/23771 which have more extensive logs
