### ISSUE TITLE
Deleting file is not possible if a file is shared to LDAP group and Login Filter doesn't contains uid attribute.

### ISSUE THREAD

**Issue by rogerfv1** [owncloud/core#24206]
### Steps to reproduce
1. Enable user_ldap plugin and set memberUID for Group-Member association.
2. Edit LDAP Login Attributes so that it doesn't use the uid attribute. You can use mail attribute instead of uid.
3. Create a ldap group and assign 2 members (user1 and user2) using memberUID.
4. With user1 share any file to ldap group.
5. With user2 try to delete the file shared by user1.

### Expected behaviour
User2 should be able to delete the file shared by user1.

### Actual behaviour
User2 can't delete the file shared by user1.
Error deleting file ""teste2_grupo.txt".

### Notes:
Deleting file works if uniqueMember is used in Group-Member association.

### Server configuration
**Operating system**: Debian 7 x86_64

**Web server:** Apache 2.2

**Database:** Postgresql 9.4

**PHP version:** 5.4.45-0+deb7u2

**ownCloud version:** 9.0.1

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** .deb

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - external
  - files_external
  - user_external

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocgh7p9w8qdx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "enable_avatars": false,
        "trusted_domains": [
            "lab1.drive.pae"
        ],
        "datadirectory": "\/opt\/data\/d_07275_drive",
        "3rdpartyroot": "\/var\/www\/owncloud",
        "memcache.local": "\\OC\\Memcache\\APC",
        "overwrite.cli.url": "http:\/\/lab1.drive.pae:8080",
        "dbtype": "pgsql",
        "version": "9.0.1.3",
        "dbname": "dbl_07275_drive_lab1",
        "dbhost": "10.31.80.236",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "logfile": "\/var\/log\/owncloud\/owncloud.log",
        "logtimezone": "UTC",
        "asset-pipeline.enabled": false,
        "ldapIgnoreNamingRules": false,
        "ldapUserCleanupInterval": 0,
        "mail_smtpmode": "smtp",
        "mail_from_address": "drive",
        "mail_domain": "pae.local.br",
        "mail_smtphost": "10.31.80.216",
        "mail_smtpport": "25",
        "has_internet_connection": false,
        "trashbin_retention_obligation": "30, auto",
        "versions_retention_obligation": "30, auto",
        "activity_expire_days": 30,
        "check_for_working_htaccess": true,
        "enable_previews": false,
        "log_rotate_size": 104857600,
        "tempdirectory": "\/tmp",
        "debug": true,
        "maintenance": false,
        "updatechecker": false,
        "cron_log": true,
        "installed": true
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/... no

**Are you using encryption:** yes/no yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... LDAP

#### LDAP configuration (delete this part if not used)

+-------------------------------+---------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                   |
+-------------------------------+---------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                 |
| hasPagedResultSupport         |                                                                                                   |
| homeFolderNamingRule          | attr:jdirectory                                                                                   |
| lastJpegPhotoLookup           | 0                                                                                                 |
| ldapAgentName                 | uid=usr_07275_jatai,ou=Servicos,ou=corp,dc=local,dc=com,dc=br                                    |
| ldapAgentPassword             | ***                                                                                               |
| ldapAttributesForGroupSearch  |                                                                                                   |
| ldapAttributesForUserSearch   | mail;sn;givenName;jmail                                                                           |
| ldapBackupHost                |                                                                                                   |
| ldapBackupPort                |                                                                                                   |
| ldapBase                      | dc=local,dc=com,dc=br                                                                            |
| ldapBaseGroups                | dc=local,dc=com,dc=br                                                                            |
| ldapBaseUsers                 | dc=local,dc=com,dc=br                                                                            |
| ldapCacheTTL                  | 0                                                                                                 |
| ldapConfigurationActive       | 1                                                                                                 |
| ldapDynamicGroupMemberURL     |                                                                                                   |
| ldapEmailAttribute            | mail                                                                                              |
| ldapExperiencedAdmin          | 1                                                                                                 |
| ldapExpertUUIDGroupAttr       |                                                                                                   |
| ldapExpertUUIDUserAttr        |                                                                                                   |
| ldapExpertUsernameAttr        |                                                                                                   |
| ldapGroupDisplayName          | cn                                                                                                |
| ldapGroupFilter               | (&(objectclass=jataiobject)(objectClass=posixGroup))                                              |
| ldapGroupFilterGroups         |                                                                                                   |
| ldapGroupFilterMode           | 0                                                                                                 |
| ldapGroupFilterObjectclass    |                                                                                                   |
| ldapGroupMemberAssocAttr      | memberUid                                                                                         |
| ldapHost                      | 10.39.17.103                                                                                      |
| ldapIgnoreNamingRules         |                                                                                                   |
| ldapLoginFilter               | (&(&(objectclass=jataiobject)(objectClass=person)(jdirectory=domain*))(|(mail=%uid)(jmail=%uid))) |
| ldapLoginFilterAttributes     |                                                                                                   |
| ldapLoginFilterEmail          | 0                                                                                                 |
| ldapLoginFilterMode           | 0                                                                                                 |
| ldapLoginFilterUsername       | 1                                                                                                 |
| ldapNestedGroups              | 0                                                                                                 |
| ldapOverrideMainServer        |                                                                                                   |
| ldapPagingSize                | 500                                                                                               |
| ldapPort                      | 389                                                                                               |
| ldapQuotaAttribute            | jquota                                                                                            |
| ldapQuotaDefault              | 1 GB                                                                                              |
| ldapTLS                       | 0                                                                                                 |
| ldapUserDisplayName           | cn                                                                                                |
| ldapUserDisplayName2          |                                                                                                   |
| ldapUserFilter                | (&(objectclass=jataiobject)(objectClass=person)(jdirectory=domain*))                              |
| ldapUserFilterGroups          |                                                                                                   |
| ldapUserFilterMode            | 0                                                                                                 |
| ldapUserFilterObjectclass     |                                                                                                   |
| ldapUuidGroupAttribute        | auto                                                                                              |
| ldapUuidUserAttribute         | auto                                                                                              |
| turnOffCertCheck              | 0                                                                                                 |
| useMemberOfToDetectMembership | 1                                                                                                 |
+-------------------------------+---------------------------------------------------------------------------------------------------+

#### ownCloud log (data/owncloud.log)
{"reqId":"lTfv3TIvsS\/0RF0a34G9","remoteAddr":"10.35.82.143","app":"user_ldap","message":"initializing paged search for  Filter (&(objectclass=jataiobject)(objectClass=posixGroup)) base Array\n(\n    [0] => cn=grupo_teste_drive,ou=grupos,dc=local,dc=com,dc=br\n)\n attr Array\n(\n    [0] => memberUid\n)\n limit 500 offset 0","level":0,"time":"2016-04-22T14:42:56+00:00","method":"DELETE","url":"\/remote.php\/webdav\/teste2_grupo.txt","user":"bb55ac81-341111e4-9f3dfd59-d0d6e068"}
{"reqId":"lTfv3TIvsS\/0RF0a34G9","remoteAddr":"10.35.82.143","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-04-22T14:42:56+00:00","method":"DELETE","url":"\/remote.php\/webdav\/teste2_grupo.txt","user":"bb55ac81-341111e4-9f3dfd59-d0d6e068"}
{"reqId":"lTfv3TIvsS\/0RF0a34G9","remoteAddr":"10.35.82.143","app":"user_ldap","message":"initializing paged search for  Filter (|(&(&(objectclass=jataiobject)(objectClass=person)(jdirectory=domain*))(|(mail=0)(jmail=0)))(&(&(objectclass=jataiobject)(objectClass=person)(jdirectory=domain*))(|(mail=1)(jmail=1)))) base Array\n(\n    [0] => dc=local,dc=com,dc=br\n)\n attr Array\n(\n    [0] => dn\n)\n limit 2 offset 0","level":0,"time":"2016-04-22T14:42:56+00:00","method":"DELETE","url":"\/remote.php\/webdav\/teste2_grupo.txt","user":"bb55ac81-341111e4-9f3dfd59-d0d6e068"}
{"reqId":"lTfv3TIvsS\/0RF0a34G9","remoteAddr":"10.35.82.143","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-04-22T14:42:56+00:00","method":"DELETE","url":"\/remote.php\/webdav\/teste2_grupo.txt","user":"bb55ac81-341111e4-9f3dfd59-d0d6e068"}
{"reqId":"lTfv3TIvsS\/0RF0a34G9","remoteAddr":"10.35.82.143","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 403 Forbidden\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Forbidden\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(285): Sabre\\\\DAV\\\\Tree->delete('teste2_grupo.tx...')\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php\",\"Line\":335,\"User\":\"bb55ac81-341111e4-9f3dfd59-d0d6e068\"}","level":0,"time":"2016-04-22T14:42:56+00:00","method":"DELETE","url":"\/remote.php\/webdav\/teste2_grupo.txt","user":"bb55ac81-341111e4-9f3dfd59-d0d6e068"}

**Comment by PVince81** [comment]
@blizzz

**Comment by PVince81** [comment]
Is this still an issue with 9.0.5 or 9.1.1 ? There were some fixes related to the memberUID.

cc @jvillafanez

**Comment by jvillafanez** [comment]
I've checked the changes between 9.0.1 and stable9 and I didn't see anything that could indicate that this is solved. I'm assuming this is still an issue.

Closing and moving the issue to the new repo -> https://github.com/owncloud/user_ldap/issues/5
