### ISSUE TITLE
PostgreSQL setup: allow specifying a TCP port

### ISSUE THREAD

**Issue by strk** [owncloud/core#24219]
### Steps to reproduce
1. install
2. go to /owncloud URI to do setup
3. select PostgreSQL database backend
### Expected behaviour

Be able to specify a TCP port, in addition to hostname, for the database
### Actual behaviour

No field exists to specify a port

**ownCloud version:** (see ownCloud admin page)
8.1.6

**Where did you install ownCloud from:**
http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_8.0/

**Comment by strk** [comment]
It looks like the port can be specified as part of the hostname, something like: `localhost:5432`
I think it would be useful to mention this possibility in the setup form.

**Comment by savanpatel** [comment]
Hello, I am interested in working on this feature/issue.

**Comment by DeepDiver1975** [comment]
> Hello, I am interested in working on this feature/issue.

@savanpatel you are welcome - let us know if you need any support

**Comment by PVince81** [comment]
moving to backlog, PRs welcome

**Comment by souravbadami** [comment]
@PVince81: Can we go with this ?
![screenshot from 2016-12-21 03 55 14](https://cloud.githubusercontent.com/assets/11073943/21370397/70d70cf2-c731-11e6-87e2-f14a3cc2bc47.png)

**Comment by strk** [comment]
Maybe the example should have a more likely port, like localhost:5432 ?
Also, what's the help text in the field, before "localhost" is typed in ?

**Comment by souravbadami** [comment]
Sure, I'll change the port number.
Re: placeholder for the host field, It's Database host.

**Comment by souravbadami** [comment]
Hey @strk! -- How do I manage the translations ?

**Comment by strk** [comment]
Placeholder should maybe be "Database host:port" ?

I don't know how to manage translations

**Comment by PVince81** [comment]
@souravbadami you don't need to care about translating, only make sure to use the `t` functions and you're good. A bot will take care of syncing the new texts with Transifex.

Your proposal sounds good: either a hint below the field or directly inside the placeholder.
Thanks!

**Comment by PVince81** [comment]
Merged https://github.com/owncloud/core/issues/26860
