### ISSUE TITLE
Setup Leads to a Internal Server Error (500)

### ISSUE THREAD

**Issue by GhostCyborg** [owncloud/core#24215]
# Actual behaviour

Every time I click 'Finish Setup' the server responds with a Internal Server Error.

# Server configuration

Operating system: CentOS

Web server: Apache

Database: MySQL or SQlite

PHP version: 5.6.14

ownCloud version: 9.0.1

# List of activated apps:
All Default App //Haven't been able to access ownCloud

The content of config/config.php:

<?php
$CONFIG = array (
  'instanceid' => 'Removed For Privacy Reasons',
  'passwordsalt' => 'Removed For Privacy Reasons',
  'secret' => 'Removed For Privacy Reasons',
  'trusted_domains' => 
  array (
    0 => 'domain.com',
  ),
  'datadirectory' => '/home/account name/public_html/owncloud/data',
  'overwrite.cli.url' => 'http://domain.com/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '9.0.1.3',
);

# Are you using external storage, if yes which one:
no

# Are you using encryption: 
no

# Are you using an external user-backend, if yes which one: 
client sync

# Logs
error_log says'
[23-Apr-2016 14:20:22 UTC] creating sqlite db
[23-Apr-2016 14:20:25 UTC] PHP Fatal error:  Out of memory (allocated 14942208) (tried to allocate 2255 bytes) in /home2/i1b9e0n3/public_html/owncloud/lib/private/log.php on line 287'

**Comment by RealRancor** [comment]
Hi,

> Logs aren't avaliable for some reason

unfortunately the bugreport is pretty useless without having thevlogfiles :-/

The 500 error is just a "catchall" generic error and you need the logfiles to know whats wrong here

**Comment by GhostCyborg** [comment]
Ok, I managed to get the log file:
error_log says '
[23-Apr-2016 14:20:22 UTC] creating sqlite db
[23-Apr-2016 14:20:25 UTC] PHP Fatal error:  Out of memory (allocated 14942208) (tried to allocate 2255 bytes) in /home/user/public_html/owncloud/lib/private/log.php on line 287'
That's the only log file i have.

**Comment by RealRancor** [comment]
Yes, thats the issue here. Your PHP has a memory_limit of 14942208 (14MB) configured which is far below the minimum of 128MB required by oC:

https://doc.owncloud.org/server/9.0/admin_manual/installation/system_requirements.html#memory

Nothing what can be done here at the bugteacker. Please close here and raise the menory_limit in your PHP to at least 128MB. For further questions you can use the forums or the users mailinglist: https://owncloud.org/support/

**Comment by GhostCyborg** [comment]
Ok, thank's alot :) :+1:

**Comment by RealRancor** [comment]
Ah, forgot to mention. The PHP directive to raise this limit is memory_limit like seen here: https://secure.php.net/manual/en/ini.core.php#ini.memory-limit

**Comment by GhostCyborg** [comment]
I changed the memory limit, and then ran 'phpinfo();' and it says that my memory limit is '512M' but i still get the same error'[23-Apr-2016 15:54:20 UTC] PHP Fatal error:  Out of memory (allocated 14942208) (tried to allocate 65552 bytes) in /home/user/public_html/owncloud/lib/private/log.php on line 226'

**Comment by RealRancor** [comment]
@GhostCyborg The message is still telling you the issue. Please use the forums or the users mailinglist, there is really nothing what can be done here from oC side except configuring your environment correctl.y

**Comment by GhostCyborg** [comment]
Ok.
