### ISSUE TITLE
Undefined index: extension at /var/www/owncloud/lib/private/installer.php#272

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#24228]
### Steps to reproduce
1. Have a bookmarks app 0.6 from oC 8.2 installed which got removed during the upgrade to 9.0.x
2. Get new version 0.7 of the bookmarks app for 9.0.x offered
3. Click on "enabled" within the oC internal appstore
4. See that the bookmarks app have been successfully installed
5. Have a look at the owncloud.log

### Expected behaviour
No log entry about an undefined index should be logged

### Actual behaviour
Log entry about an undefined index is logged. The entry is triggered from:

https://github.com/owncloud/core/blob/v9.0.1/lib/private/installer.php#L272

~~According to https://github.com/owncloud/core/issues/20242 this should have been already fixed with oC9, 8.2.1 and 8.1.5 with https://github.com/owncloud/core/pull/20196~~

### Server configuration
**PHP version:** 7.0.x

**ownCloud version:** 9.0.1

**Updated from an older ownCloud or fresh install:** Upgraded from oC 8.2.3

**Where did you install ownCloud from:** manual tar.bz2 archvie

**Signing status (ownCloud 9.0 and above):** No errors have been found.

#### ownCloud log (data/owncloud.log)
```
{"reqId":"8CcuXiPTXgmWTBY0Rpmq","remoteAddr":"xxx","app":"PHP","message":"Undefined index: extension at \/var\/www\/owncloud\/lib\/private\/installer.php#272","level":3,"time":"2016-04-25T06:18:38+02:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"xxx"}
```

**Comment by RealRancor** [comment]
Explanation why this is happening in https://github.com/owncloud/core/issues/20242#issuecomment-157004989:

> Two of the current bookmark apps tarballs will have no extension when they are being downloaded (hosted on an ownCloud and provided via link share). The missing extension causes the warning, but looking at the code it should not create other issues.

**Comment by nickvergessen** [comment]
Well, ask the app author to fix his downloads?

**Comment by RealRancor** [comment]
Mhhh, the app author is using whats provided by ownCloud (download shared by link). And that download is not providing an extension in the initial link.

**Comment by PVince81** [comment]
@blizzz didn't you take over the bookmarks app at some point ?

**Comment by blizzz** [comment]
@LukasReschke  did a fix for this https://github.com/owncloud/core/pull/20196 but apparently it is a new regression?

**Comment by blizzz** [comment]
Wait, @RealRancor the installation succeeded, only the log entry appeared? yes, of course there should be checked whether this index is present before using it.

**Comment by RealRancor** [comment]
@blizzz Exactly, the installation succeeded but only the log entry is shown:

> 4. See that the bookmarks app have been successfully installed

**Comment by RealRancor** [comment]
Sorry, wrong button

**Comment by blizzz** [comment]
Ok, https://github.com/owncloud/core/issues/24228#issuecomment-214421064 is unrelated. Go back to sleep @LukasReschke.

**Comment by blizzz** [comment]
Fix in https://github.com/owncloud/core/pull/24262
