### ISSUE TITLE
Use bigint instead of int for epoch fields

### ISSUE THREAD

**Issue by jknockaert** [owncloud/core#24221]
Epoch fields like firstoccurence and lastoccurence in the oc_calendarobjects table are defined as int datatype (at least in postgres). That doesn't allow dates beyond 2038. Such dates commonly occur for recurring items without end date, which by some clients are implicitly defined to happen 400 times. Upon syncing such an item (over caldav) the webserver gives a 500 and owncloud gives an error. So I suggest to use bigint for these fields rather than int (which fixed the issue for me).
Similar to #23004; differences are that for me the bug happened with postgres (rather than mysql) and with timestamps in the not-so-distant future (rather than timestamps before the unix epoch). In #23048 (fixing #23004) it was chosen not to change to bigint. Seems like we will continue to run into issues that way.

**Comment by jknockaert** [comment]
@DeepDiver1975 Could you have a look at this one?

**Comment by DeepDiver1975** [comment]
@jknockaert kan I ask you for an ical which is causing this issue? THX

**Comment by jknockaert** [comment]
@DeepDiver1975 This one should trigger the bug. I didn't test it myself, as my oc is now patched (and reversing the patch would corrupt the table data).
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//Mac OS X 10.9.2//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20101123T090850Z
UID:test1234567890
RRULE:FREQ=MONTHLY;COUNT=400
DTEND;VALUE=DATE:20101129
TRANSP:TRANSPARENT
SUMMARY:repeatingitem
DTSTART;VALUE=DATE:20101128
DTSTAMP:20140325T072016Z
X-APPLE-EWS-BUSYSTATUS:FREE
SEQUENCE:1
END:VEVENT
END:VCALENDAR
```

**Comment by DeepDiver1975** [comment]
THX @jknockaert

**Comment by DeepDiver1975** [comment]
fixed with https://github.com/owncloud/core/pull/24238
