### ISSUE TITLE
Emoji in a folder name

### ISSUE THREAD

**Issue by stefanovazzocell** [owncloud/core#24223]
### Steps to reproduce
1a. Try to create a folder named "🚀" --> Fails
1b. In one of your external storage, create a folder named "🚀"
2b. Try to look for the folder in OwnCloud --> Is not there

### Expected behavior
I would like the folder to show up in OwnCloud and I would like it to sync on my pc too.

### Actual behavior
The folder is neither listed on OwnCloud, nor in the pc synced with own cloud

### Server configuration
**Operating system:** Ubuntu 16.04 [server], Windows 10 Insider Preview [client]

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 7.0

**ownCloud version:** (see ownCloud admin page) 9.0.1 stable

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** php auto installer

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
_No errors have been found._
```

**List of activated apps:** 

```
IRRELEVANT
```

**The content of config/config.php:**

```
IRRELEVANT
```

**Are you using external storage, if yes which one:** LOCAL

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NO

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Chrome

**Operating system:** Windows

#### Web server error log
```
[NOT RELEVANT]
```

#### ownCloud log (data/owncloud.log)
```
	Exception: {"Message":"HTTP\/1.1 400 4-byte characters are not supported in file names","Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\InvalidPath","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1118): OCA\\DAV\\Connector\\Sabre\\Directory->getChild('\\xF0\\x9F\\x9A\\x80')\n#1 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(588): Sabre\\DAV\\Server->createCollection('\\xF0\\x9F\\x9A\\x80', Object(Sabre\\DAV\\MkCol))\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#5 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/html\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#7 \/var\/www\/html\/owncloud\/remote.php(138): require_once('\/var\/www\/html\/o...')\n#8 {main}","File":"\/var\/www\/html\/owncloud\/apps\/dav\/lib\/connector\/sabre\/directory.php","Line":196,"User":"stefanovazzocell"}
```

#### Browser log
```
client.js?v=274af88…:9 MKCOL https://stefanovazzoler.tk/owncloud/remote.php/webdav/%F0%9F%9A%80 400 ()
```

**Comment by RealRancor** [comment]
@stefanovazzocell There is currently no unicode support in ownCloud with MySQL. You can follow the following discussions if that will be supported in the future:

https://github.com/owncloud/core/issues/24009, https://github.com/owncloud/core/pull/17978 (linked a few still open issues)
