### ISSUE TITLE
Integrity Check failed : provisioning_api

### ISSUE THREAD

**Issue by hitam4450** [owncloud/core#24234]
Upgrading an existing OC 8.2.3 installation (without any glitsches9 resulted  in en error message 
in the yellow box!
Enclosed are screen shot of the error message and message of the app.
What causes this issue and how to resolve it ???

Many thanks in advance for your advice!
Havea nice, rewarding and successful day!

regards, hitam4450

![provisioning_api](https://cloud.githubusercontent.com/assets/9738727/14780284/9420749e-0adc-11e6-8864-89d6985b832d.png)
![provisioning_api2](https://cloud.githubusercontent.com/assets/9738727/14780285/942143c4-0adc-11e6-8129-0f7397279255.png)

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
jessie 8.3
**Web server:**
lighttpd 1.4.35
**Database:**
mysql 5.5
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
OC 9.0.1
**Updated from an older ownCloud or fresh install:**
Upgraded from 8.2.3
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by LukasReschke** [comment]
You are using the old version of the provisioning API. Make sure to replace also the apps folder properly with thew new files.

The one shipped with 9.0.0 is signed, the old one is not. Please double check that you replaced the app as well.

**Comment by hitam4450** [comment]
I just did an (automated) upgrade. How to check for it???

**Comment by LukasReschke** [comment]
> I just did an (automated) upgrade. 
How did you upgrade? Please provide always as much information as possible.

> How to check for it???

Look into the folder `apps/provisioning_api/appinfo` and post the content of `info.xml` here.

**Comment by hitam4450** [comment]
The content of info.xml:
<?xml version="1.0"?>
<info>
        <id>provisioning_api</id>
        <name>Provisioning API</name>
        <description>
                This application enables a set of APIs that external systems can use to create, edit, delete and query user
                attributes, query, set and remove groups, set quota and query total storage used in ownCloud. Group admin users
                can also query ownCloud and perform the same functions as an admin for groups they manage. The API also enables
                an admin to query for active ownCloud applications, application info, and to enable or disable an app remotely.
                Once the app is enabled, http requests can be used via a Basic Auth header to perform any of the functions
                listed above. More information is available in the Provisioning API documentation, including example calls
                and server responses.
        </description>
        <licence>AGPL</licence>
        <author>Tom Needham</author>
        <shipped>true</shipped>
        <default_enable/>
        <documentation>
                <admin>admin-provisioning-api</admin>
        </documentation>
        <version>0.3.0</version>
        <types>
                
                <filesystem/>
        </types>
        <dependencies>
                <owncloud min-version="8.2" />
        </dependencies>
</info>

**Comment by hitam4450** [comment]
I updated by the integrated updater, just the normal and usual way!
regards, hitam4450

**Comment by PVince81** [comment]
Is this still an issue with the latest packages ?

**Comment by DeepDiver1975** [comment]
> Is this still an issue with the latest packages ?

looks like not -> close
