### ISSUE TITLE
Catching undefined exception in versions expire

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#24233]
@schiesbn @VicDeo 

> ![bildschirmfoto vom 2016-04-25 11 46 56](https://cloud.githubusercontent.com/assets/213943/14780100/939b4ae0-0adb-11e6-9b8a-842ada92f561.png)

Affects 9.1 and 9.0 at least

**Comment by VicDeo** [comment]
and @LukasReschke I guess ;)
https://github.com/owncloud/core/commit/13e817e90166d85dbea98043583185778d192212#diff-5f784a90b1d00d186520a82b01a81c71

**Comment by PVince81** [comment]
So, anyone volunteers to fix this one liner ?

Too bad it's all static, so there will likely not be any matching unit test.
