### ISSUE TITLE
Calendar: updating event, update button has no effect

### ISSUE THREAD

**Issue by PartisanEntity** [owncloud/core#24239]
### Steps to reproduce
1. Login to the web version of your owncloud instance
2. Load your calendar
3. Go to an existing caleandar entry that was created under an older version of owncloud using an imported .ics file (version 8.2.3)
4. Click on the entry and change the date and time
5. click on the update button
6. as a test: creating a completely new event works

### Expected behaviour
After clicking on update the event window should close and the event should move to the newly selected date and time.

### Actual behaviour
Nothing appears to happen when "update" is clicked.

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS (server edition)

**Web server:**
Apache/2.4.7

**Database:**
mysql Ver 14.14 Distrib 5.5.47, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 5.5.9-1ubuntu4.14

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Updated from an older ownCloud or fresh install:**
Upgraded from owncloud 8.2.3 a couple days ago

**Where did you install ownCloud from:**
Upgraded using the manual upgrade method. zip file downloaded from owncloud

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
calendar
documents
contacts
tasks
```

**The content of config/config.php:**

```
to be updated once i have terminal access
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome Version 49.0.2623.112 m

**Operating system:**
Windows 7 Enterprise

#### Web server error log
```
To be updated once I have access
```

#### ownCloud log (data/owncloud.log)
```
Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/home\/john\/public\/domain.at\/public\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/home\/john\/public\/domain.at\/public\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/home\/john\/public\/domain.at\/public\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/home\/john\/public\/domain.at\/public\/cloud\/apps\/dav\/appinfo\/v1\/caldav.php(76): Sabre\\DAV\\Server->exec()\n#5 \/home\/john\/public\/domain.at\/public\/cloud\/remote.php(138): require_once('\/home\/john\/publi...')\n#6 {main}","File":"\/home\/john\/public\/domain.at\/public\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false}
```

#### Browser log
```
Nothing in console.
```

**Comment by zanglerecke** [comment]
confirm that behaviour..

**Comment by nickvergessen** [comment]
Please report at https://github.com/owncloud/calendar/issues/new

**Comment by PartisanEntity** [comment]
Thanks, done: https://github.com/owncloud/calendar/issues/493
