### ISSUE TITLE
Can not wrap storage of owner anymore

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#24249]
Since some day in the last week, I can not wrap non-shared-storages anymore.

### Steps to reproduce
1. As user1 create folder test1/test2/
2. Share test2 with user2
3. Tag test1 with "Tag"
4. Create a workflow autotagging rule to tag files with "Tag" when a parent is tagged with "Tag"
5. As user2 upload a file
6. Check that the file is tagged

### Expected behaviour
Tag is added

### Actual behaviour
Tag is not added

### Debugging
It works when you check out cdcabbd0b3f6209b2a312b30a84c381f125bcf68 which is the last merge commit before: https://github.com/owncloud/core/pull/23919

So I checked the storages and it looks like the sourceStorage inside the SharedStorage is created without being wrapped. I also checked with @schiesbn sitting next to me and there was never a try to wrap that storage.

Please help @rullzer @icewind1991

**Comment by rullzer** [comment]
I did not try with the workflow app yet. But probabaly it goes wrong in https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/sharedstorage.php#L84

Because that is where we get the storage that the jail wraps...

**Comment by rullzer** [comment]
When running a debug session... I do see the storage wrapper. But things go wrong when we try to run the plugin. This happens because the wrong cache is probabaly fetched there... I'll look into a bit more detail tomorrow.

**Comment by rullzer** [comment]
Could you try again with master.
I rebased this morning and it is working...

**Comment by rullzer** [comment]
Mmm so it seems the tag is not set using the webUI but when doing the PUT via webdav all works fine...

**Comment by rullzer** [comment]
PR in #24280

**Comment by icewind1991** [comment]
@nickvergessen try not applying the storage wrapper in app.php directly but instead in the filesystem `preSetup`

**Comment by nickvergessen** [comment]
Right, that fixes the issue on plain master. So we should make sure that all apps use that instead of registering in plain app.php?

**Comment by icewind1991** [comment]
Afaik all (our own) apps do it like that

**Comment by nickvergessen** [comment]
Well all our EE apps don't :P
