### ISSUE TITLE
UI Enhancement Suggestion: More aggressively announce App Updates.

### ISSUE THREAD

**Issue by tilllt** [owncloud/core#24258]
I was researching how to get rid of a bug in calendar in OC9 and only by gathering the version data for the bug report discovered there was an update to the Calendar App that fixed both of my problems. 

IMHO important App updates (like Calendar 1.0 to 1.1) should be more aggressively announced to the Admin User (me, in this case) since most admins probably rarely take a look at the App menu...

Maybe just in the same way that the OC updates themselves are announced?

Cheers,
t.

**Comment by RealRancor** [comment]
Some suggestions / ideas are already collected in:

https://github.com/owncloud/core/issues/17373, https://github.com/owncloud/core/issues/22031

**Comment by tilllt** [comment]
True, mine is absolutely a dupe of those you posted can be closed.
