### ISSUE TITLE
Error PHP	Undefined index

### ISSUE THREAD

**Issue by Raigan21** [owncloud/core#24265]
i am working with owncloud 9.0.X in  ubuntu server 14.04 lts and apache 2.

the last think i did was update the version of owncloud from 9 to 9.0.1  and later this errors begins to appear, nothing is working wrong and i don't see any problem but the log records this errors 2 or 3 times per day.

> Error PHP Undefined index: quota at /var/www/owncloud/settings/personal.php#143   2016-04-19T09:41:57-04:00
> Error PHP Undefined index: ownerDisplayName at /var/www/owncloud/apps/files/lib/helper.php#58 2016-04-19T09:41:37-04:00
> Error PHP Undefined index: owner at /var/www/owncloud/apps/files/lib/helper.php#57    2016-04-19T09:41:37-04:00
> Error PHP Undefined index: ownerDisplayName at /var/www/owncloud/apps/files/controller/viewcontroller.php#211 2016-04-19T09:41:36-04:00
> Error PHP Undefined index: owner at /var/www/owncloud/apps/files/controller/viewcontroller.php#210    2016-04-19T09:41:36-04:00
> Debug DeleteOrphanedItems 0 orphaned comment read marks deleted   2016-04-19T09:40:36-04:00
> Debug DeleteOrphanedItems 0 orphaned comments deleted 2016-04-19T09:40:36-04:00
> Debug DeleteOrphanedItems 0 orphaned user tag relations deleted   2016-04-19T09:40:36-04:00
> Debug DeleteOrphanedItems 0 orphaned system tag relations deleted 2016-04-19T09:40:36-04:00

thanks for the help

**Comment by PVince81** [comment]
This is not enough information to be able to reproduce or debug it. Please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

The first message seems to happen on the personal page. Can you go to your personal page and see whether it makes these messages appear ?

Maybe more information about what quota was set for the user triggering the messages could help too.

**Comment by Raigan21** [comment]
### Server configuration
**Operating system**: ubuntu 14

**Web server:**digitalocean

**Database:**mysql

**PHP version:**5.5.9

**ownCloud version:** 9.0.1

**Updated from an older ownCloud or fresh install:**9.0

**Where did you install ownCloud from:**digitalocean

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**
```
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "instanceid": "ocvjtglpiyap",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "saz-cloud.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "kum",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "America\/Montreal",
        "log_rotate_size": 6250000,
        "installed": true,
        "mail_smtpmode": "php",
        "loglevel": 0,
        "quota_include_external_storage": true,
        "maintenance": false,
        "theme": ""
    }
}
```

**Are you using external storage, if yes which one:**S3 (aws)

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:**no

### Client configuration
**Browser:**chrome

**Operating system:**windows 10

### Logs

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by Raigan21** [comment]
the only think that i modify in quota is add the external storage to the calculation.

the users cant modify or add external storage.

i review the personal.php but all is rigth

**Comment by PVince81** [comment]
Is this still happening on 9.1.3 or 9.0.7 ?
