### ISSUE TITLE
files:scan --path does not propagate the size

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#24271]
### Steps
1. Create empty folder in the UI: `test/test1/test2/`
2. Enter `test/test1/test2/` in the UI
3. `cp` a file into `data/admin/files/test/test1/test2`
4. Run `./occ files:scan --path="/admin/files/test/test1/test2"`

### Expected
Size of all folders should not be 0:
* `test/`
* `test/test1/`
* `test/test1/test2/`

### Actually
* `test/` = 0 :x: 
* `test/test1/` = 0 :x: 
* `test/test1/test2/` > 0 :white_check_mark: 

Confirmed on 8.2.3 and master

**Comment by PVince81** [comment]
@nickvergessen did the etag propagate at least or did it also stop at the requested path ?

Because I can imagine some people using `--path` for the files:scan workaround for external storages, and use the path option to avoid rescanning everything fully and limit it to their external storages.

**Comment by PVince81** [comment]
@icewind1991

**Comment by nickvergessen** [comment]
on my 8.2.3 installation at least the mtime got propagated to `test` and `test/test1`, I didn't note down the etag, so not sure.
