### ISSUE TITLE
No consitent languages in login screen

### ISSUE THREAD

**Issue by CCXX2016** [owncloud/core#24270]
Some browsers ignoring default language settings in config.php
e.g. Firefox (Win 10, 45.0.2) is interpreting language settings in config.php correctly.
At the same time eg. Safari (OSX, iOS) and Edge (Win10) are showing default English language in the login screen.

### Expected behaviour
Default language seetings of config.php should show up with any browser

### Actual behaviour
It seems like some browers (eg.Safari/Edge) ignoring the language settings at the login screen in config.php and always using default English.

**Web server:**
SharedHosting, using a subdomain with https

**Database:**
 MySQL 5.5.46

**PHP version:**
5.5.33

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Updated from an older ownCloud or fresh install:**
Fresh installation of 9.0.1

**Where did you install ownCloud from:**
offical webpage

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by nickvergessen** [comment]
We have 4 different ways to get the correct language:
1. We check the user preferences (does not apply when logged out)
2. We check the default_language config
3. We check the HTTP_ACCEPT_LANGUAGE header that is sent by the browser
4. We use `en`

Can you please provide the config information that is being asked for by the issue template?

**Comment by nickvergessen** [comment]
00004221 @MorrisJobke @pako81

**Comment by MorrisJobke** [comment]
We also got feedback, that even if the language is properly set for a logged in user it is not used in IE11 and Safari while Firefox and Chrome just work fine.

This could not be reproduced by @nickvergessen

**Comment by CCXX2016** [comment]
pls. find attached the config.php:

<?php
$CONFIG = array (
  'instanceid' => 'XXXX',
  'passwordsalt' => 'XXXX',
  'secret' => 'XXXX',
  'trusted_domains' => 
  array (
    0 => 'XXX',
  ),
  'datadirectory' => 'XXX',
  'overwrite.cli.url' => 'XXX',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'XXX',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXXX',
  'dbpassword' => 'XXXX',
  'logtimezone' => 'Europe/Berlin',
  'installed' => true,
  'loglevel' => 1,
  'logdateformat' => 'Y F d, H:i:s',
  'maintenance' => false,
  'knowledgebaseenabled' => false,
  'allow_user_to_change_display_name' => false,
  'remember_login_cookie_lifetime' => 1,
  'session_lifetime' => 43200,
  'enable_previews' => true,
  'preview_max_x' => 1600,
  'preview_max_y' => 1600,
  'preview_max_scale_factor' => 10,
  'preview_max_filesize_image' => 50,
  'mail_smtpmode' => 'php',
  'xframe_restriction' => true,
  'theme' => 'XXX',
  'filelocking.enabled' => true,
  'max_filesize_animated_gifs_public_sharing' => 10,
  'minimum.supported.desktop.version' => '2.1.1',
  'updatechecker' => true,
  'tempdirectory' => '/XXX/tmp/owncloudtemp',
  'appstore.experimental.enabled' => true,
  'default_language' => 'de',
);

**Comment by CCXX2016** [comment]
just to add. The post-login menus (eg user menu) after login into OC with these browsers (Safari, Edge) will be in default English language too. Regardless what is configured in config.php.

**Comment by nickvergessen** [comment]
are you using a theme? and do you have any `l10n` folders?

**Comment by CCXX2016** [comment]
Yes I'm using a theme. But just core and settings folder inside. No l10n oder language files included

**Comment by nickvergessen** [comment]
Can you try disabling it and test if that solves the issue?

**Comment by CCXX2016** [comment]
I tested it with unabled theme. It shows the same (wrong) behaviour.

**Comment by PluueeR** [comment]
Same problem here. Correct language is detected in Firefox (dutch version) but not in IE 11 (English OS, with Dutch language pack installed). I configured the default_language setting in config.php with no luck.

**Comment by MorrisJobke** [comment]
@nickvergessen tested with master, stable9 and 9.0.1.

**Comment by felixboehm** [comment]
@PluueeR how are settings in the IE11 Browser?

**Comment by PluueeR** [comment]
@felixboehm language is set to `Nederlands (Nederland) [nl-NL]`. In ownCloud version 8.2.3 everything works fine (see https://github.com/owncloud/core/issues/23842#issuecomment-216474581)

**Comment by nickvergessen** [comment]
Managed to reproduce it with my desktop pc, so I will dive into this now.
