### ISSUE TITLE
Filter implementation

### ISSUE THREAD

**Issue by c0fe** [owncloud/core#24296]
It would be great to have built in filter implemenation based on custom created filters. So let's say I have a number of files: customer orders, purchase orders, work orders and I want to add different filter options including file type "customer order" for example, date when service was provided (sometimes files can be uploaded later on) and other aspects.

**Comment by nickvergessen** [comment]
You can use tags for that since ownCloud 9.0

**Comment by c0fe** [comment]
I saw a tags plugin for OwnCloud but it stated that the only version it was working for was OwnCloud 8.0. Is tags now builtin within version 9.0?

**Comment by RealRancor** [comment]
@c0fe Yes, tags are builtin oC9:

> The new tag support in ownCloud 9 will help you organize your data and find what you are looking for even faster.

https://owncloud.org/nine/
