### ISSUE TITLE
Support absolute dates in ownCloud

### ISSUE THREAD

**Issue by dwt** [owncloud/core#24291]
### Steps to reproduce
1. Use Owncloud
2. Notice that it shows relative dates everywhere, and only shows absolute dates when hovering over them
3. Be quite annoyed
### Expected behaviour

We need a way to show absolute dates by default, as it is really hard to convert from 'see the file I edited on the 10th of july' to whatever that means as a relative date today. Especially so because that changes every day. :-( Absolute dates are accessible, but only via a hover, which means they cannot be searched for in the browser.
### Actual behaviour

Own cloud shows relative dates everywhere all the time. Absolute dates (at least for us) rule absolutely.
### Server configuration

**Operating system**:
centos 7

**Web server:**
apache

**Database:**
mysql

**PHP version:**
5.4.16

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Updated from an older ownCloud or fresh install:**
updated

**Where did you install ownCloud from:**
package manager

**Signing status (ownCloud 9.0 and above):**
signed (I think)

`No errors have been found.`

**List of activated apps:**

```
./occ app:list
Enabled:
  - activity: 2.2.1
  - calendar: true
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
```

**The content of config/config.php:**

```
./occ config:list system
{
    "system": {
        "instanceid": "fnord",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "some-domain"
        ],
        "datadirectory": "\/some\/path\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/some.url",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "forceSSLforSubdomains": false,
        "updatechecker": false,
        "theme": "",
        "loglevel": 0,
        "appstore.experimental.enabled": false,
        "maintenance": false,
        "trashbin_retention_obligation": "auto"
    }
}
```

From https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=date#file-versions it seems there is no option that allows this, so can you please add this?

**Comment by nickvergessen** [comment]
@jancborchardt

**Comment by PVince81** [comment]
hack: change/override `OC.Util.relativeModifiedDate` to simply call `OC.Util.formatDate` in js.js
