### ISSUE TITLE
External Storage with local server path exposes ROOT directory structure via WebDAV

### ISSUE THREAD

**Issue by pisc-software** [owncloud/core#24298]
### Steps to reproduce
1. Add a external storage to a local server path.
2. Access the owncloud Server via WebDAV
3. Open the storage path to the external storage
4. See all the root directory structure from the server.

### Expected behaviour
The subdirectory structure of the local server path should be shown (below the local server path).

### Actual behaviour
The root server directory structure is exposed.

### Server configuration
**Operating system**: CentOS 5

**Web server:** Apache 2

**Database:** MySql

**PHP version:** 5.4

**ownCloud version:** 9.0.1

**Updated from an older ownCloud or fresh install:** Updated from ownCloud 8

**Where did you install ownCloud from:** Manual update.

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** None

**Comment by Xenopathic** [comment]
Any log messages in owncloud.log?

**Comment by pisc-software** [comment]
See here, fresh log file from initial access via WebDAV and Screenshot how it looks from CyberDuck:

[screenshot_497](https://cloud.githubusercontent.com/assets/6881732/14844555/6f57d418-0c58-11e6-9ed6-0cec6882ec76.png)

[owncloud-log.txt](https://github.com/owncloud/core/files/238108/owncloud-log.txt)

The external storage:

[screenshot_498](https://cloud.githubusercontent.com/assets/6881732/14844601/c31403ce-0c58-11e6-84ab-ae795c5f9dc2.png)

The path of the local directory attached is:

/home/server/storage/repositories/share.pillwax.com/workspaces/csc

If you need anything else pls. let me know, or to try anything.

**Comment by LukasReschke** [comment]
This is fixed with https://github.com/owncloud/core/pull/24259.

@pisc-software Mind testing? THX.

**Comment by pisc-software** [comment]
Cool, updated the "files_external/service" files from the current master and issue is corrected.

Thanks for fast reacting.
