### ISSUE TITLE
no contacts visible after update to 9.0.1

### ISSUE THREAD

**Issue by Hubble1974** [owncloud/core#24300]
### Steps to reproduce
1. After Update I try to open the (activated) contact app
2.
3.

### Expected behaviour
I would like to see all contact as it works before the update.

### Actual behaviour
The app tells me, that there are no contacts and there is a never ending spinning wheel. Mobile clients also loose contact to the oc contacts.
As far as I understand in the log message (below) is, that it could be a problem with the field "Spitzname" (german for nickname). I have many of these messages in the log, each with different first letters - I suppose from the different nicknames. Is that true?
As a pretty much oc and php greenhorn, I don't know how to fix that and each hint is very appreciatet. Do I have to delete the field "Spitzname" in the Database or only the values or anything else?

### Server configuration
**Operating system**:

**Web server:**
on Synology DSM 6
**Database:**
Maria DB 5.5.47
**PHP version:**
5.6.17
**ownCloud version:** (see ownCloud admin page)
9.0.1
**Updated from an older ownCloud or fresh install:**
8.2.3
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```

#### ownCloud log (data/owncloud.log)
```
Exception: {"Message":"Invalid Mimedir file. Line starting at 4 did not follow iCalendar\/vCard conventions","Exception":"Sabre\\VObject\\ParseException","Code":0,"Trace":"#0 \/volume1\/web\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(189): Sabre\\VObject\\Parser\\MimeDir->readProperty(';=\"Spitzname: A...')\n#1 \/volume1\/web\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(137): Sabre\\VObject\\Parser\\MimeDir->parseLine(';=\"Spitzname: A...')\n#2 \/volume1\/web\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(63): Sabre\\VObject\\Parser\\MimeDir->parseDocument()\n#3 \/volume1\/web\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Reader.php(44): Sabre\\VObject\\Parser\\MimeDir->parse('BEGIN:VCARD\\r\\nVE...', 0)\n#4 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(797): Sabre\\VObject\\Reader::read('BEGIN:VCARD\\r\\nVE...')\n#5 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(259): Sabre\\CardDAV\\Plugin->convertVCard('BEGIN:VCARD\\r\\nVE...', 'vcard3')\n#6 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(198): Sabre\\CardDAV\\Plugin->addressbookMultiGetReport(Object(Sabre\\CardDAV\\Xml\\Request\\AddressBookMultiGetReport))\n#7 [internal function]: Sabre\\CardDAV\\Plugin->report('{urn:ietf:param...', Object(Sabre\\CardDAV\\Xml\\Request\\AddressBookMultiGetReport), 'addressbooks\/ad...')\n#8 \/volume1\/web\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#9 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(716): Sabre\\Event\\EventEmitter->emit('report', Array)\n#10 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#11 \/volume1\/web\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#12 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#13 \/volume1\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#14 \/volume1\/web\/owncloud\/apps\/dav\/appinfo\/v1\/carddav.php(75): Sabre\\DAV\\Server->exec()\n#15 \/volume1\/web\/owncloud\/remote.php(138): require_once('\/volume1\/web\/ow...')\n#16 {main}","File":"\/volume1\/web\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php","Line":385,"User":"admin"}

another error message, maybe also important:

Undefined index: at /volume1/web/owncloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php#344

**Comment by DeepDiver1975** [comment]
Please connect to the database and search through the table oc_cards - one of the cards is invalid and has to either be fixed or deleted.

**Comment by Hubble1974** [comment]
I forgot to write, that this is only one of many many error messages in the log. I have many such entries at the same time. They seem to be each equal except the letter A after "Spitzname". So it seems that each card is affected :-(

**Comment by PVince81** [comment]
Please try again with 9.0.5.
If the problem persists, please find the invalid entry and post it here to be able to find a way to fix such entries.
