### ISSUE TITLE
owncloud upgrade issue 8.04 to 8.2

### ISSUE THREAD

**Issue by blexfort** [owncloud/core#24308]
Hello!

Tonight tried to update in automatic mode owncloud (by pushing a button in the admin web-panel of woncloud to update). The system says: 

> "Exception: Updates between multiple major versions and downgrades are unsupported."

I do not have an access to terminal as I use remote hosting and can manage thing ONLY via FTP or WEB-interface. so, I cannot use any bash commands. So, please, could you point me how to sort it out ASAP?

Thanks!

**Comment by RealRancor** [comment]
@blexfort 

Please see: https://forum.owncloud.org/viewtopic.php?f=17&t=32087

You can close here and post at the forums if you have further questions / problems doing a correct upgrade.
