### ISSUE TITLE
ownCloud 9.0.2 security and setup warnings are endlessly reloading

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#24309]
Other users have reported this as well in the bug tracker, with ownCloud Proxy I now face this as well. I'm debugging this…

**Comment by LukasReschke** [comment]
> Mixed Content: The page at 'https://█████.owncloudconnect.com/owncloud/settings/admin' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://█████.owncloudconnect.com/owncloud/apps/files/'. This request has been blocked; the content must be served over HTTPS.
Navigated to https://█████.owncloudconnect.com/owncloud/settings/admin

**Comment by RealRancor** [comment]
Dup: https://github.com/owncloud/core/issues/24293 :-)

**Comment by Xenopathic** [comment]
@LukasReschke Do you get a warning printed before the reload with #24126 applied?

**Comment by PVince81** [comment]
Setting to critical as this makes the admin page unusable in such environments.

**Comment by PVince81** [comment]
CC @cmonteroluque FYI

**Comment by PVince81** [comment]
@LukasReschke any progress on the debugging front ?

**Comment by PVince81** [comment]
Likely an env issue, moving to 9.0.3 as it would still be good to find out what is going on

@cmonteroluque

**Comment by PVince81** [comment]
Ok, so the SSL warning might be causing a reload from what I read

**Comment by PVince81** [comment]
It looks like the global ajax error handler is getting a lot of false positives, and that only because it is assuming that a failed XmlHttpRequest is due to a cross-domain request trying to connect to an IDP in a SSO situation.

Anyway, I think we should backport https://github.com/owncloud/core/pull/24126 which will at least introduce a delay and give the admin a chance to see the current messages, which can already be useful to find out what is wrong in their env.

I'll prepare a backport PR.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/25035

**Comment by icewind1991** [comment]
@PVince81 is this closed with #25035 ?

**Comment by PVince81** [comment]
Kind of, yes. At least it gives admin a better chance of seeing warnings and debugging.

However it was reported again here https://github.com/owncloud/core/issues/25058#issuecomment-225174763 maybe with more chance to find out about the core issue.

**Comment by fuco809** [comment]
same issue here. OC9.0.2.2 + php7 + centos7(latest patches) proxy needed and configured in config.php and additional reverse-proxy apache in front - then issue appears when using http://ocserver but when using https it works. and when accessing directly to owncloud-apache (without reverse proxy) it works too with http (and https).

**Comment by fuco809** [comment]
![reload_site_oc9](https://cloud.githubusercontent.com/assets/14198012/16227977/6793cef8-37b4-11e6-840a-c34d7859dd65.png)

after login to OC i get the loop on /owncloud/apps/files/

i tried to figure out the root cause. it seems that js.js makes the reload (see screenshot)
i also tried #25058 tips with apache config and overwritehost/overwritehostport. - no effect.
i also tried OC9.0.3RC1, and there ist the 5sec delay message, but problem still exists.
any hints?

**Comment by PVince81** [comment]
js.js makes the reload because it detected an ajax error and believes that it was a cross-site SSO redirect. Currently there is no good way to detect such situations.

In your specific case you need to find out why the ajax call causes an error in the first place, likely an issue in your env.

**Comment by fuco809** [comment]
with browser debugging mode i found this message while loading the page, but i am not sure if this is relevant.

The requested URL /core/vendor/jquery/jquery-1.10.2.js was not found on this server.

**Comment by n2five6** [comment]
We have the same problem OC 9.0.2 behind an LB.
The LB delivers the SSL-Cert (no Cert is configured on server side).

If I try to debug the error with FF, I saw also that there is something with the Content-Security-Policy. Maybe it has also to do with the .ocdata error (that we have also).

![owncloud-redirect](https://cloud.githubusercontent.com/assets/20090647/16267572/cb0c3386-388a-11e6-9e10-0b9a4240e07d.jpg)

`[Wed Jun 22 15:08:20.835144 2016] [authz_core:error] [pid 3020] [client ██.██.██.██:12784] AH01630: client denied by server configuration: /srv/www/owncloud-lt/data/.ocdata`

**Comment by fuco809** [comment]
for my case i found the cause and a solution. the propfind http requests are somewhere filtered (IPS,...) and without them the page allways reloads. now after fixing this, the reloads disappear and all working fine.
@n2five6 : as your screenshot shows you have at least the same problem with propfind requests.

**Comment by PVince81** [comment]
Now thinking of it, I might have a solution to prevent the reload in case the setup checks are triggering the "global ajax error" condition. I'll add an exclusion flag for the setup checks.

**Comment by PVince81** [comment]
Fix here: https://github.com/owncloud/core/pull/25239

Can you guys who have the reload issue try it out ?

**Comment by fuco809** [comment]
applied the changes in core/js/setupchecks.js on a 9.0.1rc1 ... now the page reload (loop) dissappears, but OC not fully loading/not functionally because propfind http request times out (on my testserver).

**Comment by PVince81** [comment]
@fuco809 thanks. Yeah, there is indeed a setup issue on your side.

Goal of my PR was mostly to avoid the annoying reload while trying to figure out how to fix the env.

**Comment by n2five6** [comment]
@fuco809: Thanks! I looks like there will be something blocked on our LB. We opened now a support Ticket by KEMP. 

@PVince81: Is there a List which HTTP-Methods are used from ownCloud?

**Comment by PVince81** [comment]
I can't seem to find an explicitly list. Mostly the verbs commonly used by REST and Webdav APIs:
- GET
- POST
- PUT
- MOVE
- DELETE
- PROPPATCH
- PROPFIND
- REPORT
(from the top of my head)

**Comment by RealRancor** [comment]
There are also others like MKCOL. Personally i'm using those:

https://forum.owncloud.org/viewtopic.php?f=23&t=10519&p=26878#p26878

**Comment by NestorTejero** [comment]
On OwnCloud 9.1.0 we are getting the same error. Our code already contains the fix linked above, but it looks like it is just hiding the error, not going to the root cause.

We get this:
````
admin:1 Mixed Content: The page at 'https://owncloud.XXX.com/settings/admin' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://owncloud.XXX.com/apps/files/'. This request has been blocked; the content must be served over HTTPS.
````

Just for reference, we have an SSL certificate running in the server, so that the main page for OC is https://owncloud.XXX.com.

**Comment by PVince81** [comment]
Yes, the above code only removes the useless reloading to make it possible for you to examine the network console and other possible environment errors.
