### ISSUE TITLE
Submit comments in sidebar by CTRL+Enter

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/core#24302]
### Steps to reproduce
1. open the files app
2. open the sidebar by clicking a file
3. select the comments tab
4. enter some text
5. hit CTRL+Enter

### Expected behaviour
The form is submitted

### Actual behaviour
Nothing happens, I have to either click the submit button or use tab + enter.

**ownCloud version:**
9.1

@nickvergessen @schiesbn as discussed

**Comment by PVince81** [comment]
Don't make it easier for spammers :wink:

Good idea
