### ISSUE TITLE
Allow apps to have some uninstall routine

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#24306]
The app that I'm currently writing starts several external jobs that should be unregistered when the app gets uninstalled. 

There is the `ManagerEvent::EVENT_APP_DISABLE` event but that one is called after the app has been disabled (ref https://github.com/owncloud/core/blob/2ab4b1ce0402cca1903d06fb7977809088355891/lib/private/App/AppManager.php#L258)

Should we maybe have an appinfo.xml entry for an uninstall class? 

cc @karlitschek @DeepDiver1975

**Comment by DeepDiver1975** [comment]
> Should we maybe have an appinfo.xml entry for an uninstall class?

sounds reasonable - what about re-using repair steps here as well?

We already allow to define repair steps on upgrade before and after db migration (and soon async as well).
In addition to that we can also define some steps on install and uninstall - or even (re-)enable and disable?

**Comment by LukasReschke** [comment]
Sounds good 👍

**Comment by DeepDiver1975** [comment]
> (assuming the syntax will be similar to #24085)

yes
