### ISSUE TITLE
Increase arguments column on jobs table

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#24301]
The current jobs table only allows up to 4000 characters in the arguments column.
The problem is paths in ownCloud can be up to 4000 characters. So when you use the argument column for a path, you can not store any other information anymore.
Also since the information is also json_encoded you can't even store a path of max-length...

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
clob then ....

**Comment by PVince81** [comment]
I suppose that eventually having a separate key/value table that maps to job id will not do good performance-wise ? The key/values could be made to only be read whenever the job is actually required to execute, not in the initial queue fetch.

**Comment by nickvergessen** [comment]
Well with the check for duplicates that gets way to messy then. Lets just change the type

**Comment by PVince81** [comment]
Right, I forgot duplicate check.

Maybe if we had a hash column where job creators could set a generated id, it would be easier to find duplicates. For example, for versions expire the hash could be computed based on the file id or file name (forgot which).

**Comment by nickvergessen** [comment]
Blocked by https://github.com/owncloud/core/pull/24897

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/24897 was closed with "will not work".

@DeepDiver1975 what to do with this ticket then ?
