### ISSUE TITLE
Owncloud not restore

### ISSUE THREAD

**Issue by JoseClarcat** [owncloud/core#24324]
Good morning everyone,

My server Owncloud accidentally erased. I performed a daily backup of both the database and what directories. The database was PostgreSQL.

Create a new server with the same version Centos 7 and directories and restore the database as it indicated the official documentation Owncloud.

However, I can not get my Owncloud running again. Just let me access the local user, not the previous users who had configured LDAP.

In addition, I can not upload a file or with the local user.

### Steps to reproduce
1. Re-install Owncloud 9.0
2. Copy folder backup to new server
3. Restore BBDD
4. Crash Owncloyud

### Server configuration
**Operating system**:
Centos 7.2
**Web server:**
Apache httpd last version
**Database:**
PostgreSQL last version
**PHP version:**
PHP 5.6
**ownCloud version:** (see ownCloud admin page)
9
**Updated from an older ownCloud or fresh install:**
Restore from an older Owncloud
**Where did you install ownCloud from:**
Server in Hypervisor

Logs:

Apache:

[Thu Apr 28 10:19:06.800306 2016] [authz_core:error] [pid 25838] [client 192.168.0.8:52867] AH01630: client denied by server configuration: /var/www/html/owncloud/data/.ocdata
[Thu Apr 28 10:19:41.805033 2016] [:error] [pid 23684] [client 192.168.0.8:52897] PHP Fatal error:  Call to a member function getCache() on null in /var/www/html/owncloud/apps/files_sharing/lib/cache.php on line 67
[Thu Apr 28 10:20:16.918018 2016] [:error] [pid 23683] [client 192.168.0.8:52786] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 48 bytes) in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 77

Owncloud:

{"reqId":"VyHHc53FuOyfYrP2PQ9RCwAAAAQ","remoteAddr":"192.168.0.8","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\NotNullConstraintViolationException\",\"Message\":\"An exception occurred while executing 'INSERT INTO \\\"oc_filecache\\\" (\\\"mimepart\\\",\\\"mimetype\\\",\\\"mtime\\\",\\\"size\\\",\\\"etag\\\",\\\"storage_mtime\\\",\\\"permissions\\\",\\\"parent\\\",\\\"path_hash\\\",\\\"path\\\",\\\"name\\\",\\\"storage\\\") SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM \\\"oc_filecache\\\" WHERE \\\"storage\\\" = ? AND \\\"path_hash\\\" = ? HAVING COUNT(*) = 0' with params [3, null, 1461831516, 1067592, \\\"bc91ba973022b43434a1096154dddc43\\\", 1461831516, 27, 2, \\\"fdb8c6cd6ab557fb58cfb7d366828ad6\\\", \\\"files\\\\\\\/Guia_Uso_Rapido_Webmail_v1.docx\\\", \\\"Guia_Uso_Rapido_Webmail_v1.docx\\\", 1, 1, \\\"fdb8c6cd6ab557fb58cfb7d366828ad6\\\"]:\\n\\nSQLSTATE[23502]: Not null violation: 7 ERROR:  el valor null para la columna \\u00abmimetype\\u00bb viola la restricci\\u00f3n not null\\nDETAIL:  La fila que falla contiene (255317, 1, files\\\/Guia_Uso_Rapido_Webmail_v1.docx, fdb8c6cd6ab557fb58cfb7d366828ad6, 2, Guia_Uso_Rapido_Webmail_v1.docx, null, 3, 1067592, 1461831516, 1461831516, 0, 0, bc91ba973022b43434a1096154dddc43, 27, null).\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO \\\"oc...', Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(205): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO \\\"oc...', Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/db\\\/adapter.php(93): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `*P...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(243): OC\\\\DB\\\\Adapter->insertIfNotExist('*PREFIX*filecac...', Array, Array)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php(265): OC\\\\DB\\\\Connection->insertIfNotExist('*PREFIX*filecac...', Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/cache.php(220): OC\\\\Files\\\\Cache\\\\Cache->insert('files\\\/Guia_Uso_...', Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(251): OC\\\\Files\\\\Cache\\\\Cache->put('files\\\/Guia_Uso_...', Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(198): OC\\\\Files\\\\Cache\\\\Scanner->addToCache('files\\\/Guia_Uso_...', Array, -1)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/cache\\\/scanner.php(293): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('files\\\/Guia_Uso_...', 3, -1, NULL, true)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1240): OC\\\\Files\\\\Cache\\\\Scanner->scan('files\\\/Guia_Uso_...', false)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1281): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files\\\/Guia_Uso_...', '\\\/Guia_Uso_Rapid...')\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/filesystem.php(866): OC\\\\Files\\\\View->getFileInfo('\\\/Guia_Uso_Rapid...', true)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/upload.php(226): OC\\\\Files\\\\Filesystem::getFileInfo('\\\/Guia_Uso_Rapid...')\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#15 [internal function]: __lambda_func(Array)\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(276): call_user_func('\\\\x00lambda_85', Array)\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(882): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#18 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractPostgreSQLDriver.php\",\"Line\":57}","level":3,"time":"2016-04-28T08:18:59+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/files\/ajax\/upload.php","user":"root"}
{"reqId":"VyHHer4fo8acmj7aIlcFHAAAAAs","remoteAddr":"192.168.0.8","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2016-04-28T08:19:06+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"VyHHe74fo8acmj7aIlcFHwAAAAs","remoteAddr":"192.168.0.8","app":"user_ldap","message":"Count filter:  objectclass=*","level":0,"time":"2016-04-28T08:19:07+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php","user":"root"}
{"reqId":"VyHHe74fo8acmj7aIlcFHwAAAAs","remoteAddr":"192.168.0.8","app":"user_ldap","message":"initializing paged search for  Filter objectclass=* base Array\n(\n    [0] => OU=CLARCAT,DC=gijon,DC=clarcat,DC=local\n)\n attr Array\n(\n    [0] => dn\n)\n limit 500 offset 0","level":0,"time":"2016-04-28T08:19:07+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php","user":"root"}
{"reqId":"VyHHe74fo8acmj7aIlcFHwAAAAs","remoteAddr":"192.168.0.8","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-04-28T08:19:07+00:00","method":"POST","url":"\/owncloud\/index.php\/apps\/user_ldap\/ajax\/wizard.php","user":"root"}
{"reqId":"VyHHl4-HV3KMYPDiDjrOdQAAAAM","remoteAddr":"192.168.0.8","app":"PHP","message":"A session had already been started - ignoring session_start() at \/var\/www\/html\/owncloud\/lib\/private\/session\/internal.php#95","level":0,"time":"2016-04-28T08:19:35+00:00","method":"GET","url":"\/owncloud\/index.php?logout=true&requesttoken=MAkPIkp0BS0aAj8MOxVaMBcxNQ0UHCZcVCsEfStiLzc%3D%3AwhDPsL5Ew6ehrm8tVZxyMLTlbjU1ZZzS%2B9xHwweetS8%3D","user":"--"}
{"reqId":"VyHHl4-HV3KMYPDiDjrOdQAAAAM","remoteAddr":"192.168.0.8","app":"PHP","message":"PHP Startup: apc: Unable to initialize module\nModule compiled with module API=20100525\nPHP    compiled with module API=20131226\nThese options need to match\n at Unknown#0","level":3,"time":"2016-04-28T08:19:35+00:00","method":"GET","url":"\/owncloud\/index.php?logout=true&requesttoken=MAkPIkp0BS0aAj8MOxVaMBcxNQ0UHCZcVCsEfStiLzc%3D%3AwhDPsL5Ew6ehrm8tVZxyMLTlbjU1ZZzS%2B9xHwweetS8%3D","user":"--"}
{"reqId":"VyHHncA4Vbf1H@d9pXW3ugAAAAI","remoteAddr":"192.168.0.8","app":"PHP","message":"Argument 2 passed to OC\\Files\\Cache\\Shared_Cache::__construct() must implement interface OCP\\Files\\Storage\\IStorage, null given, called in \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php on line 574 and defined at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/cache.php#63","level":0,"time":"2016-04-28T08:19:41+00:00","method":"POST","url":"\/owncloud\/","user":"06B71773-C315-4635-93EC-82CF7F21708F"}
{"reqId":"VyHHncA4Vbf1H@d9pXW3ugAAAAI","remoteAddr":"192.168.0.8","app":"PHP","message":"Argument 3 passed to OC\\Files\\Cache\\Shared_Cache::__construct() must implement interface OCP\\Files\\Cache\\ICacheEntry, null given, called in \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php on line 574 and defined at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/cache.php#63","level":0,"time":"2016-04-28T08:19:41+00:00","method":"POST","url":"\/owncloud\/","user":"06B71773-C315-4635-93EC-82CF7F21708F"}
{"reqId":"VyHHncA4Vbf1H@d9pXW3ugAAAAI","remoteAddr":"192.168.0.8","app":"PHP","message":"Call to a member function getCache() on null at \/var\/www\/html\/owncloud\/apps\/files_sharing\/lib\/cache.php#67","level":3,"time":"2016-04-28T08:19:41+00:00","method":"POST","url":"\/owncloud\/","user":"06B71773-C315-4635-93EC-82CF7F21708F"}

**Comment by PVince81** [comment]
Did you also restore the "config.php" and apps you had in the old version ?

Strangely you seem to be getting an out of memory error.

Some messages even look like the source code is mixed up. Please make sure to delete the old source code before replacing it with the newly setup instance.

**Comment by PVince81** [comment]
Closing due to lack of feedback. See previous comment.
