### ISSUE TITLE
Packages: differentiate between ownCloud update and package revison update

### ISSUE THREAD

**Issue by ghost** [owncloud/core#24339]
Just had a user complaining about the package update process at the forums:

https://forum.owncloud.org/viewtopic.php?f=38&t=36352

The packages are currently showing:

> Leaving server in maintenance mode. Please run occ upgrade manually.
> 
> See https://doc.owncloud.org/server/9.0/admin_manual/maintenance/upgrade.html

even if only a package revision update is done:

> Unpacking owncloud (9.0.1-3.1) over (9.0.1-1.1) ...

However on such revision update of the package no occ upgrade run is needed and oC cloud be just put out of maintenance mode.

cc @jnweiger

**Comment by nickvergessen** [comment]
@jnweiger

**Comment by RealRancor** [comment]
Ref to the documentation issue: https://github.com/owncloud/documentation/issues/2403
