### ISSUE TITLE
After upgrade to 9.0 apps not listed

### ISSUE THREAD

**Issue by johnnydvc** [owncloud/core#24334]
### Steps to reproduce
1. Upgrade to 9.0 
2. Try to enable the apps (calendar, contacts etc.) that were disabled beforehand
3. Cannot enable apps -> incompatible (needs owncloud < 8.2)

### Expected behaviour
activate apps

### Actual behaviour
I cannot activate so I uninstall them. 
Then they disappear. No recommended apps.

### Server configuration
**Operating system**:
Debian 8

**Web server:**
nginx

**Database:**
mysql

**PHP version:**
5.6.20
**ownCloud version:** (see ownCloud admin page)
9.0.1

**Updated from an older ownCloud or fresh install:**

Upgrade from 8.2

**Where did you install ownCloud from:**

linux package manager

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - direct_menu: 0.7.1
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: 7.1.2
  - notes: 1.1.0
  - notifications: 0.2.3
  - ownbackup: 0.3.8
  - provisioning_api: 0.4.1
  - qownnotesapi: 0.4.3
  - systemtags: 0.2
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```{
    "system": {
        "instanceid": "ocugwb8v1qw1",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "picloud2.jstoexwl5axd8znt.myfritz.net"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/picloud2.jstoexwl5axd8znt.myfritz.net",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "default_language": "de",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "en3ster",
        "mail_domain": "gmail.com",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "password": ""
        },
        "updatechecker": false
    }
}

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
ff
**Operating system:**
ubuntu
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```


Insert your ownCloud log here
```
{"reqId":"zTKsYaEDyKfvQM+q42A2","remoteAddr":"92.196.110.160","app":"core","message":"Could not get application: cURL error 7: Failed to connect to api.owncloud.com port 443: No route to host","level":3,"time":"2016-04-28T20:24:44+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"pi"}

{"reqId":"AWkk7YpkwpxJfoeZhKbZ","remoteAddr":"92.196.110.160","app":"tasks","message":"Can not enable the Tasks app because the Calendar App is disabled.","level":3,"time":"2016-04-28T20:26:43+00:00","method":"GET","url":"\/index.php\/apps\/files","user":"pi"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by Xenopathic** [comment]
In 9.0 both Calendar and Contacts were partially merged into core, so the old versions that you had installed are no longer compatible. Please upgrade to the newer versions (from the app store or via your package manager)

**Comment by Xenopathic** [comment]
What's more, the error log `Failed to connect to api.owncloud.com port 443: No route to host` indicates you have a network problem preventing ownCloud reaching the ownCloud servers. You might want to fix that.

**Comment by johnnydvc** [comment]
> You might want to fix that.
I really do but I have not changed anything to my network. So what can be the problem.
I updated the contacts and calendar apps from git. Still  cannot reach the appstore.

**Comment by DeepDiver1975** [comment]
The appstore is currently down. Lets hope it will get back online.

**Comment by Nicola-Ranaldo** [comment]
The same network problem:

wget https://apps.owncloud.com
--2016-04-29 09:19:33--  https://apps.owncloud.com/
Resolving apps.owncloud.com (apps.owncloud.com)... 74.208.110.124
Connecting to apps.owncloud.com (apps.owncloud.com)|74.208.110.124|:443... failed: **No route to host.**

traceroute apps.owncloud.com
...
12  ae-6-0.bb-a.ga.mkc.us.oneandone.net (74.208.6.124)  140.346 ms  133.897 ms  134.816 ms
13  ae-11.gw-distp-a.slr.lxa.us.oneandone.net (74.208.1.229)  142.977 ms  138.984 ms  135.775 ms
14  ae-1.gw-prtr-r4-1a.slr.lxa.us.oneandone.net (74.208.1.176)  147.823 ms  150.402 ms  152.213 ms
15  s8.owncloud.com (216.250.125.20)  144.619 ms  141.246 ms  141.157 ms
16  s8.owncloud.com (216.250.125.20)  2924.095 ms **!H**  2897.775 ms **!H**  2897.175 ms **!H**
