### ISSUE TITLE
Bugs in shared link with video

### ISSUE THREAD

**Issue by lenz1111** [owncloud/core#24331]
### Steps to reproduce (owncloud 9.0.1):
1) Set in config.php:
'enabledPreviewProviders' => array ( 0 => 'OC\\\\Preview\\\\Movie' )

on share link it will looks like that:

![keyb1](https://cloud.githubusercontent.com/assets/18718374/14887078/68a83a98-0d54-11e6-8e12-6f379b54cf12.jpeg)

![keyb2](https://cloud.githubusercontent.com/assets/18718374/14887093/7c65471a-0d54-11e6-88b3-ed48a3df0f1a.jpeg)

2) Upload video with large size - preview_max_x / preview_max_y options are not used to set max video size in share link.

### Solution:

1. Disable video preview in shared link

2. Set &lt;video&gt; style: max-width, max-height with parameters from preview_max_x / preview_max_y

Patch:
[owncloud9_download_video_display_bugs.zip](https://github.com/owncloud/core/files/240582/owncloud9_download_video_display_bugs.zip)

**Comment by LukasReschke** [comment]
@lenz1111 Thanks a lot for your patch file! Can I ask you to open a pull request with this change? This would be utmost appreciated 🚀

**Comment by davitol** [comment]
@lenz1111  I cannot reproduce the issue. Could you please tell me which browser did you use and maybe could you provide me an example of file video to reproduce it?
I'm also available in https://webchat.freenode.net/?channels=owncloud-dev (IRC) as  davitol if you prefer. 
Thanks in advance.

**Comment by lenz1111** [comment]
@davitol In any browser. Make sure you have:
1. In config.php:
```
'enable_previews' => true,
'preview_max_x' => 640,
'preview_max_y' => 640,
'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Movie',
    1 => 'OC\\Preview\\Image',
  ),
```
2. _ffmpeg_ installed (thumbnails for video is generated correctly)

On download page (public share) you will see both video frame and thumbnail picture

I can show you example on my site if needed

**Comment by davitol** [comment]
@lenz1111 I reproduce it on Chrome version Version 50.0.2661.102 (64-bit). oC version 9.1.0.3","versionstring":"9.1.0 pre alpha","edition":""
Before appliying the patch
![screen shot 2016-05-24 at 08 45 31](https://cloud.githubusercontent.com/assets/10596560/15494849/fc2d575c-218c-11e6-8233-22d71e4a8142.png)

After applying 24346 patch
![screen shot 2016-05-24 at 08 46 57](https://cloud.githubusercontent.com/assets/10596560/15494865/0dab7342-218d-11e6-9b20-2faab8330355.png)

Maybe can be a better solution that locates the preview in the right position?

Thanks again for the PR

**Comment by lenz1111** [comment]
@davitol For me it does not look good when you start playing a video and see at the right thumbnail from video - there is a better solution for video:
`<video controls poster="/images/w3html5.gif">`
I think _poster_ is what we need here
