### ISSUE TITLE
Upgrade to 9.0.1.3 from 9.0.0: package from distro failed, release zip succeded but can't login!

### ISSUE THREAD

**Issue by qwc** [owncloud/core#24333]
### Steps to reproduce
If you have a archlinux system running with latest packages but owncloud9.0.0 from repo, try upgrading to latest package from repo. Maybe you'll have the same problems.
After a bunch of errors I've downloaded the latest owncloud release from the website and replaced the failing source instance.
I upgraded then with ````sudo -u http ./occ upgrade ```` which succeded. 
But now I am not able to login.

Setting the logging to debug and target to errorlog doesn't give any further information about the problem.

### Expected behaviour
Login possible.

### Actual behaviour
Just redirects to the login page.

### Server configuration
**Operating system**:
Arch Linux
**Web server:**
Apache 2.4
**Database:**
PostgreSQL 9.5.2
**PHP version:**
7.0.6
**ownCloud version:** (see ownCloud admin page)
9.0.1.3
**Updated from an older ownCloud or fresh install:**
Updated: 9.0.0
**Where did you install ownCloud from:**
First from Distro-Repo, which failed, then from release zip.
**Signing status (ownCloud 9.0 and above):**
?
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
When this would even be possible...
**List of activated apps:**
Enabled:
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_videoplayer: 0.9.8
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - activity
  - encryption
  - external
  - files_texteditor
  - files_trashbin
  - files_versions
  - firstrunwizard
  - gallery
  - user_external
  - user_ldap
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
{
    "system": {
        "instanceid": "52125c141ed2a",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/srv\/data\/owncloud\/data",
        "dbtype": "pgsql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "owncloud.mmo.to"
        ],
        "mail_smtpmode": "php",
        "mail_from_address": "wm",
        "mail_domain": "mmo.to",
        "share_folder": "\/Shared",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "debug": true,
        "singleuser": false,
        "log_type": "errorlog"
    },
    "apps": {
        "activity": {
            "ocsid": "166038",
            "enabled": "no",
            "types": "filesystem",
            "installed_version": "1.2.0"
        },
        "admin_dependencies_chk": {
            "installed_version": "0.01",
            "types": null,
            "enabled": "no"
        },
        "admin_migrate": {
            "installed_version": "0.1",
            "types": null,
            "enabled": "no"
        },
        "backgroundjob": {
            "lastjob": "13"
        },

        "bookmarks": {
            "installed_version": "0.3",
            "types": null,
            "enabled": "no"
        },
        "calendar": {
            "types": "",
            "ocsid": "168707",
            "enabled": "no",
            "installed_version": "1.1"
        },
        "checksum": {
            "installed_version": "0.1",
            "types": "filesystem",
            "ocsid": "160005",
            "enabled": "no"
        },
        "comments": {
            "installed_version": "0.2",
            "types": "logging",
            "enabled": "yes"
        },
        "contacts": {
            "ocsid": "168708",
            "types": "",
            "installed_version": "1.2.0.0",
            "enabled": "no"
        },
        "core": {
            "installedat": "1376935299.6073",
            "remote_core.css": "\/core\/minimizer.php",
            "remote_core.js": "\/core\/minimizer.php",
            "remote_contactthumbnail": "contacts\/thumbnail.php",
            "public_files": "files_sharing\/public.php",
            "remote_ampache": "media\/remote.php",
            "public_calendar": "calendar\/share.php",
            "public_caldav": "calendar\/share.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "global_cache_gc_lastrun": "1431586971",
            "backgroundjobs_task": "OC_Cache_FileGlobal-gc",
            "public_documents": "documents\/public.php",
            "repairlegacystoragesdone": "yes",
            "backgroundjobs_step": "queued_tasks",
            "public_gallery": "gallery\/public.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "lastupdateResult": "{\"version\":{},\"versionstring\":{},\"url\":{},\"web\":{}}",
            "lastcron": "1461867613",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "lastupdatedat": "0",
            "oc.integritycheck.checker": "[]"
        },
        "dav": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "0.1.6"
        },
        "documents": {
            "installed_version": "0.9.0",
            "types": "",
            "ocsid": "168711",
            "enabled": "no"
        },
        "federatedfilesharing": {
            "installed_version": "0.1.0",
            "types": "",
            "enabled": "yes"
        },
        "federation": {
            "installed_version": "0.0.4",
            "types": "authentication",
            "enabled": "yes"
        },
     
        "files": {
            "types": "filesystem",
            "default_quota": "1 GB",
            "enabled": "yes",
            "backgroundwatcher_previous_file": "623",
            "installed_version": "1.4.4",
            "backgroundwatcher_previous_folder": "1040",
            "cronjob_scan_files": "500"
        },
        "files_external": {
            "ocsid": "166048",
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "0.5.2",
            "user_mounting_backends": "owncloud,sftp,dropbox,googledrive,\\OC\\Files\\Storage\\SFTP_Key"
        },
        "files_imageviewer": {
            "installed_version": "1.0",
            "types": null,
            "enabled": "no"
        },
        "files_mv": {
            "installed_version": "0.6.0",
            "types": "filesystem",
            "ocsid": "150271",
            "enabled": "no"
        },
        "files_odfviewer": {
            "installed_version": "0.1",
            "types": null,
            "enabled": "no"
        },
        "files_pdfviewer": {
            "ocsid": "166049",
            "types": "",
            "enabled": "yes",
            "installed_version": "0.8"
        },
        "files_sharing": {
            "enabled": "yes",
            "types": "filesystem",
            "40": "1456070752.5083",
            "installed_version": "0.9.1",
            "41": "1455712755.7754"
        },
        "files_texteditor": {
            "installed_version": "0.3",
            "types": null,
            "enabled": "no"
        },
        
        "files_trashbin": {
            "installed_version": "0.4",
            "types": "filesystem",
            "enabled": "no"
        },
        "files_versions": {
            "installed_version": "1.0.3",
            "types": "filesystem",
            "enabled": "no"
        },
        "files_videoplayer": {
            "installed_version": "0.9.8",
            "types": "",
            "enabled": "yes"
        },
        "files_videoviewer": {
            "types": "",
            "installed_version": "0.1.2",
            "enabled": "no"
        },
        "firstrunwizard": {
            "installed_version": "1.0",
            "types": null,
            "enabled": "no"
        },
        "fluxx_compensator": {
            "installed_version": "0.2.4",
            "types": "base",
            "ocsid": "157091",
            "enabled": "no"
        },
        "gallery": {
            "types": "filesystem",
            "installed_version": "0.5.3",
            "enabled": "no"
        },
        "internal_messages": {
            "installed_version": "1.5",
            "types": null,
            "ocsid": "154784",
            "enabled": "no"
        },
        "journal": {
            "types": null,
            "ocsid": "154637",
            "installed_version": "0.3.2",
            "enabled": "no"
        },
      
        "media": {
            "installed_version": "0.4.3",
            "types": null,
            "enabled": "no"
        },
        "notifications": {
            "installed_version": "0.2.3",
            "types": "logging",
            "enabled": "yes"
        },
        "provisioning_api": {
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "search_lucene": {
            "types": "filesystem",
            "installed_version": "0.6.0",
            "enabled": "no",
            "ocsid": "168709"
        },
        "systemtags": {
            "installed_version": "0.2",
            "types": "logging",
            "enabled": "yes"
        },
        "tal": {
            "installed_version": "0.2.2",
            "types": null,
            "ocsid": "154632",
            "enabled": "no"
        },
        "tasks": {
            "types": "",
            "ocsid": "164356",
            "installed_version": "0",
            "enabled": "no"
        },
        "templateeditor": {
            "installed_version": "0.1",
            "types": "",
            "enabled": "yes"
        },
        "updatenotification": {
            "installed_version": "0.1.0",
            "types": "",
            "enabled": "yes"
        },
     
        "updater": {
            "ocsid": "166059",
            "types": "",
            "installed_version": "0.4",
            "enabled": "no"
        },
        "user_migrate": {
            "installed_version": "0.1",
            "types": null,
            "enabled": "no"
        },
        "user_photo": {
            "installed_version": "0.5",
            "types": null,
            "ocsid": "154679",
            "enabled": "no"
        }
    }
}
      
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
```

```

### Client configuration
**Browser:**
Firefox/rekonq/Chromium
**Operating system:**
Archlinux
#### Web server error log
```
[Thu Apr 28 20:20:13.078719 2016] [:error] [pid 987] [client 188.68.52.110:50530] [owncloud][DeleteOrphanedSharesJob][0] 0 orphaned share(s) deleted
```

#### ownCloud log (data/owncloud.log)
```
Nothing for this particular problem.
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
@qwc There is currently an issue with oC running on PHP 7.0.6 where you can find an upcoming fix in https://github.com/owncloud/core/pull/24326

**Comment by qwc** [comment]
Btw. where the **** are the Contact and Calendar apps? I'm using owncloud ONLY BECAUSE OF THESE!

**Comment by HLFH** [comment]
@qwc https://github.com/owncloud/contacts and https://github.com/owncloud/calendar. These apps were not fully working, so they have been removed from the core apps. Now that there is a finished redesign, you could download these new apps and enjoy them again.

@RealRancor Thanks. I can't login with PHP 7.0.6. So, I'll test this [PR](https://github.com/owncloud/core/pull/24326).

**Comment by RealRancor** [comment]
Please avoid using language like this.

The calendar and contacts apps are provided by https://apps.owncloud.com which is currentl down / not available.

**Comment by qwc** [comment]
Thanks @HLFH , installed them, they're working. 60% of my contacts still missing... I could kill someone for that, atm.

Sorry @RealRancor , but my my anger level this evening exceeds all known levels ever before...

**Comment by RealRancor** [comment]
Anger leads to the dark side...

**Comment by HLFH** [comment]
So the issue could be closed, dear jedi. [The PR](https://github.com/owncloud/core/pull/24326) is merged.

**Comment by qwc** [comment]
Yeah, closing it. 

Need to buy a punching bag, or just give me the address of the guy who's responsible for the fucking mess with my contacts now... (sry...)

**Comment by RealRancor** [comment]
There is no need to point fingers on someone...

**Comment by qwc** [comment]
Hey folks, sorry for everything I said. When you use owncloud for calendar and contacts as main reason you'll be very angry when something breaks.

In the end my wife deleted all contacts on our tablet thinking she was doing this on her account, but it was mine. So after this information I was able to restore the database with an older backup before this accident and everything is running smooth again. :)
