### ISSUE TITLE
Updater app

### ISSUE THREAD

**Issue by alve89** [owncloud/core#24338]
Is it possible that oC 9 is not available as an update (neither via updater app nor via `occ upgrade`) yet? In /settings/admin#updater I get displayed 

> Your version is up to date.

 and I'm using version 8.2.2.

Thanks!

**Comment by LukasReschke** [comment]
It is not yet available there, 9.0.2 to be released next week hopefully will soon be available via the updater app.

Apologize for the hassles 🚀

**Comment by RealRancor** [comment]
Also see: http://owncloud.10557.n7.nabble.com/where-is-9-0-1-auto-updater-and-more-td17111.html
