### ISSUE TITLE
Server does not store cksum in case of text files modified directly.

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/core#24348]
### Steps to reproduce
1. Sync a client with a server that has enable cksum capabilities.
2. Include a text file at sync shared folder
3. Check at Db that any file synced contains a cksum
4. Modify the text file directly from server browser
5. Check at Db that the text file does not contain a cksum.

### Expected behaviour

cksum has to be kept

### Actual behaviour

After modifying the file the cksum is empty

### Server configuration

Server Version : 9.1.0 Alpha,  enable cksum capabilities. --> @rullzer did it 😮 
Server OS: Ubuntu

### Client configuration

Client OS :  OS X El capitán 10.11.4
Client Version:  Version 2.2.0-nightly20160428 (build 3312)

**Comment by mcastroSG** [comment]
cc/ @PVince81 @dragotin @rullzer

**Comment by PVince81** [comment]
This is expected behavior. The ownCloud server does NOT compute any checksums and only stores whatever the desktop client is sending.

So if you modify a file, the checksum will get cleared because it was invalid.

**Comment by PVince81** [comment]
> So if you modify a file

I mean modify directly in ownCloud, not through desktop client
