### ISSUE TITLE
Bug with favicon not working

### ISSUE THREAD

**Issue by adinxtheman** [owncloud/core#24358]
### Steps to reproduce
1. Create favicon file
2. Replace favicon with new file like described in the ownCloud 9 documentation

### Expected behaviour
Favicon should show custom logo

### Actual behaviour
ownCloud logo remains

### Server configuration
**Operating system**: 
Ubuntu 16.04

**Web server:**Apache

**Database:**
MySQL 5.7

**PHP version:**
7

**ownCloud version:** 
9.0.1

**Updated from an older ownCloud or fresh install:**Fresh
Fresh

**Where did you install ownCloud from:**
 #OBS

### Client configuration
**Browser:**
Chrome 50

**Operating system:**

### Logs
No logs

**Comment by enoch85** [comment]
I can confirm this @jancborchardt

**Comment by RealRancor** [comment]
If you're using a theme then it might be a dup of https://github.com/owncloud/core/issues/23758

**Comment by PVince81** [comment]
Closing as dup. Please reopen if you were NOT using a theme.
