### ISSUE TITLE
As an ownCloud admin I would like configure shares for a specific user (by API)

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#24355]
A user asked me about API features:

> 1)  Is there an possibility to receive all the shares for an specific user by authorising as OwnCloud (Group) Admin?

Currently, it is only possible to get all the shares from the logged in user.

> 2) Do you know if there is also possibility to delete all the shares in once for a specific user by the API?

@MTRichards @MorrisJobke 

00005364

**Comment by rullzer** [comment]
1) No
2) No

I think we also don't want this on the normal endpoint. A separate app would be better suited for this.

*should* not be hard (logic in the share manager is there to do this). But will require some enginering time.

**Comment by PVince81** [comment]
1) was already requested here https://github.com/owncloud/core/issues/14545

**Comment by PVince81** [comment]
I'll close in favor of https://github.com/owncloud/core/issues/14545
