### ISSUE TITLE
Error 500 - OC does not work with PHP 7.0.6

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/core#24362]
Interner Serverfehler

Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.

Bitte wende Dich an den Serveradministrator, sollte dieser Fehler mehrfach auftreten, und füge Deiner Anfrage die unten stehenden technischen Details bei.

Weitere Details können im Serverprotokoll gefunden werden.

Details will follow later.

**Comment by Wikinaut** [comment]
owncloud.log shows:

{"reqId":"xxxxxxxxxx","remoteAddr":"","app":"remote","message":"The requested uri() cannot be processed by the script '\/owncloud\/remote.php')","level":4,"time":"2016-04-30T21:22:53+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php","user":"--"}

**Comment by RealRancor** [comment]
Hi,

ownCloud is currently not working with PHP 7.0.6: https://github.com/owncloud/core/pull/24343

**Comment by Wikinaut** [comment]
duplicate of https://github.com/owncloud/core/pull/24343
