### ISSUE TITLE
Export contacts and calendars via console [WISH]

### ISSUE THREAD

**Issue by silverhook** [owncloud/core#24361]
It would be great if the `occ` tool would have the feature to export the contacts and calendars into a standard vCal/vCard.

A use case is e.g. that your webserver times out a lot and you need to export data.

**Comment by DeepDiver1975** [comment]
well ... pure data export could be done on database level as well ....

**Comment by silverhook** [comment]
True, but only be (more or less) directly reusable for migrating to another ownCloud instance.

**Comment by hitam4450** [comment]
:thumbsup:
