### ISSUE TITLE
(solved) http://localhost/owncloud can't be accessed after installation of owncloud server 9.0.1

### ISSUE THREAD

**Issue by volkerwysk** [owncloud/core#24368]
### Steps to reproduce
1. Install the owncloud server
2. Try to open http://localhost/owncloud in a browser

### Expected behaviour
The owncloud login screen should occur.

### Actual behaviour
A 404 error from the web server

### Server configuration
**Operating system**:
Kubuntu 16.04

**Web server:**
apache 2.4.18

**Database:**
SQLite

**PHP version:**
7.0.4

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Updated from an older ownCloud or fresh install:**
both

**Where did you install ownCloud from:**
http://download.owncloud.org/download/repositories/stable/xUbuntu_16.04/

The bug is simple. The file owncloud.conf is installed in /etc/apache2/conf-available/, but it isn't activated in /etc/apache2/conf-enabled. Adding the required symlink solves the problem.

Happy hacking,
Volker Wysk

**Comment by RealRancor** [comment]
cc @jnweiger

**Comment by Xenopathic** [comment]
Please post the logs apt-get/aptitude during the upgrade

**Comment by volkerwysk** [comment]
Sorry, I've (de)installed a lot and it's hard to say which log applies. 

However, after purging the previous owncloud server (version 8) and related packages, the problem seems to vanish. When reinstalling everything, the /etc/apache2/conf-enabled/owncloud.conf symlink is created.

**Comment by rullzer** [comment]
Ok lets close then
