### ISSUE TITLE
XML parser error

### ISSUE THREAD

**Issue by stormsh** [owncloud/core#24371]
Hi there, after the Update to 9.0.1 I get an XML parser error with the [OPDS app](https://apps.owncloud.com/content/show.php/OPDS+catalog?content=168132) . I don't know if this is an issue with oc 9 or not. I've contacted the maintainer of OPDS catalog, but I didn't get a response yet. So I thought you guys might be able to give me some hints where I can start looking for the problem.

I updated to 9.0.1 from 8.2.3. OPDS app was already latest 0.6.15. Update with occ command. Went well on the first run.

### Expected behaviour
When I browse to https://mydomain.de/index.php/apps/files_opds/ I see the catalog page (looks like an rss feed)

### Actual behaviour
Instead I see an xml parser error:
```
XML-Verarbeitungsfehler: Nicht übereinstimmendes Tag. Erwartet: .
Adresse: https://mydomain.de/apps/files_opds/
Zeile Nr. 88, Spalte 8:
```

Line 88 changes, sometimes it's 88, or 89 or 90. Don't know why.

Firefox webdeveloper says in addition to the parsererror:

> Content Security Policy: Die Direktive 'frame-src' should not be used. Please use Direktive 'child-src' instead.

### Server configuration
Operating system: Ubuntu 14.04
Web server: apache 2.4
Database: Mysql
PHP version: 7.0.5
ownCloud version (see ownCloud admin page): 9.0.1
Updated from an older ownCloud or fresh install: 8.2.3
ownCloud log (data/owncloud.log): The log doesn't say anything but finished cron jobs, loglevel is debugg.

I use encryption, but this wasn't a problem before. I start to think, the problem is in the database. But even choosing a new folder fpr the library and disabling and enabling the plugin again doesn't do a thing.

Thx 4 f1.

st.

**Comment by DeepDiver1975** [comment]
This really has to be taken care of by the maintainer of the app - sorry there is not much we can do -> close

**Comment by stormsh** [comment]
Thought so. Thanks for the info anyway :)
