### ISSUE TITLE
Sharing with filter

### ISSUE THREAD

**Issue by ghost** [owncloud/core#24373]
Hey, this is a feature request. Is there any chance to share a folder but filter out some of the files?

For example, folder contains:

.picasaorginials/... (hidden folder)
.picasa.ini (hidden file)
image1.jpg
image2.jpg

So I would like to share the folder, but without the hidden folder/files.

**image1.jpg
image2.jpg**

Any chance to do so?

**Comment by rullzer** [comment]
This is not possible with the current way shares are handled in ownCloud. We basically share a folder. And then that folder is mounted by the recipient.

**Comment by PVince81** [comment]
won't fix for now
