### ISSUE TITLE
Calendar: Remove valarms from objects in read-only shared calendars

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/core#24377]
@georgehrke
Back in the old calendar app there was an open pull request made by you that removed the alarm from events in read-only sharedy calendars.
You postponed this PR due the calendar on OC9 uses another caldav implementation.

Is something like that already possible in OC9 or is it planned?

Old PR is: https://github.com/owncloudarchive/calendar/pull/668
Old issue: https://github.com/owncloudarchive/calendar/issues/547

**Comment by PVince81** [comment]
cc @DeepDiver1975

**Comment by vmuth** [comment]
Hello, we managed to solve this issue for owncloud 9.0 calendar. We have tested it a bit but it still needs testing. I don't know how to contribute code to the apps, so I just drag and drop the file here. This is a modification of the the file apps/dav/lib/caldav/caldavbackend.php

[caldavbackend.php_oc90-no-Alarm-For-ReadOnly-Shared-Calender.txt](https://github.com/owncloud/core/files/461943/caldavbackend.php_oc90-no-Alarm-For-ReadOnly-Shared-Calender.txt)

Thanks to Katinka for initial code!

**Comment by aartsr** [comment]
@vmuth I've tested your solution a bit today on OC 9.0.7 but am running into problems, have you gotten any further with this yourself by any chance?

**Comment by vmuth** [comment]
Hi @aartsr, sorry for the late reply. Which problems do you have with this code? How different is the caldavbackend.php from your original? There should only be differences in line 536, 586 and between 1396 - 1425.

**Comment by aartsr** [comment]
Hi @vmuth thank you for your reply. I've used the exact code in the txt-file you provided above in combination with OC 9.0.7 test install at Hostiso, which uses a private smtp server for e-mail notifications (tested to work). I created an event in _calendar X_ which is shared with _user a_ (read-only) and _user b_ (edit rights). 

Behaviour observed in the **OC web interface**:
> I can see the event in all 3 calendars. _Calendar a_ (read-only) shows all details, including reminder settings (which I cannot edit of course), and _calendar b_ (edit rights) shows all details, but empty reminder settings (which I can edit). So far so good, but I see no reminder popups, audio or emails being shown/sent to either user a or b, but also not the original user X. 
> I expected the original calendar to keep showing reminders and calendar a and b to not show reminders. From what I've been reading the reminder e-mails not being sent might be something that's fixed in OC v9.1 though.

Behaviour observed in **iPhone calendar**:
> When I connect my iPhone to each of the calendars mentioned above, all three of them will show reminders. 
> Here I expected only the original calendar X to show reminders and the other two to not show reminders.

I'm guessing the above behaviour is not what you're experiencing? May I ask what OC version seems to be working for you? Any tips are welcome.
