### ISSUE TITLE
Strange Failed File Integrity Check

### ISSUE THREAD

**Issue by c0fe** [owncloud/core#24398]
I got a fresh install of Owncloud on shared HostGator hosting and immediately I saw a tag saying that file check failed. I clicked on it for details and got the following:

http://hastebin.com/gelofoxika.coffee

I am not sure why this occurred. Can anyone please help?

**Comment by RealRancor** [comment]
When uploading via FTP make sure that you're using the correct transfer mode. Also make sure that those files didn't got corrupted during the transfer.

Overall this looks to me like something for the users mailinglist or the forums like described here: https://owncloud.org/support/

**Comment by c0fe** [comment]
HostGator FTP supports ASCII only.

**Comment by RealRancor** [comment]
Then choose a more reliable FTP client.

**Comment by c0fe** [comment]
Well I used Filezilla. Which one would you recommend?

**Comment by RealRancor** [comment]
I think we should continue at the forums as suggested. This is really nothing what should be discussed here...
