### ISSUE TITLE
[master/9.1] Cannot login with LDAP

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24409]
### Steps

1. Setup OC from scratch
1. Setup docker openLDAP from https://github.com/owncloud/administration/tree/master/ldap-testing and run `batchCreateUsers` to create zombies
1. Enable LDAP app in OC and configure it against that server
1. Log out
1. Log in as "zombie239" with password "zombie239"

### Expected
Login succeeds

### Actual
Login fails, 500 error

### Logs
Not sure if related:
```
{"reqId":"Fad2mMh8p2XLr+zXYaGz","remoteAddr":"127.0.0.1","app":"user_ldap","message":"Could not set avatar for uid=zombie239,ou=zombies,dc=owncloud,dc=com, because: \/b5f08ca6-a555-1035-9bf0-0163b017980d","level":1,"time":"2016-05-03T08:40:51+00:00","method":"POST","url":"\/owncloud\/","user":"b5f08ca6-a555-1035-9bf0-0163b017980d"}
{"reqId":"Fad2mMh8p2XLr+zXYaGz","remoteAddr":"127.0.0.1","app":"files_skeleton","message":"copying skeleton for b5f08ca6-a555-1035-9bf0-0163b017980d from \/srv\/www\/htdocs\/owncloud\/core\/skeleton to \/b5f08ca6-a555-1035-9bf0-0163b017980d\/files\/","level":0,"time":"2016-05-03T08:40:51+00:00","method":"POST","url":"\/owncloud\/","user":"b5f08ca6-a555-1035-9bf0-0163b017980d"}
```

### Versions
ownCloud 9.1 pre-alpha git master 547830d97edd2c4da46a2d7988873fdc65e00bb4

@blizzz @davicente @rullzer 

I'll bisect this...

**Comment by PVince81** [comment]
Works fine in v9.0.2RC2.

**Comment by PVince81** [comment]
Breaking commit 7adae4476f2a4488a00ce822cd2edc726b475c0e from https://github.com/owncloud/core/pull/23443 by @LukasReschke 

@LukasReschke can you have a look ?

**Comment by PVince81** [comment]
It's the "Log more information by default" one

**Comment by LukasReschke** [comment]
That is https://github.com/owncloud/core/pull/23799

Does this happen for all users for you? Me and Arthur had problems to reproduce this but I'll give it a try with that docker again then ;-)

**Comment by PVince81** [comment]
The docker comes with avatars, not sure if related or not.

It's not only happening at login time. Whenever the session is already there, on master the web UI shows "cannot display page; 500 error" but when I switch to before this commit, it works again, switch back, broken again.

**Comment by LukasReschke** [comment]
Will try to reproduce locally after lunch.

**Comment by PVince81** [comment]
Note, cherry-picking the workaround https://github.com/owncloud/core/pull/23799/commits/a50619200c6a08929dbe802118a6afadb376b866 on master fixes the issue.

(thanks @blizzz for pointing it out on IRC)

**Comment by MorrisJobke** [comment]
> Note, cherry-picking the workaround a506192 on master fixes the issue.

Could you create a PR for this?

**Comment by PVince81** [comment]
I could, but had the impression that @LukasReschke wanted to have a go at a cleaner non-workaroundy PR.

**Comment by PVince81** [comment]
Okay, this is actually a duplicate: https://github.com/owncloud/core/issues/24467
