### ISSUE TITLE
Improving memory usage / cache usage

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24403]
From @butonic:

> A non exhaustive search reveals other places where an array is used to cache data:
> 
> ```
> apps/user_ldap/group_ldap.php#L46
> apps/user_ldap/group_ldap.php#L51
> apps/dav/lib/connector/sabre/sharesplugin.php#L67
> apps/dav/lib/connector/sabre/tagsplugin.php#L80
> apps/dav/lib/connector/sabre/custompropertiesbackend.php#L75
> lib/private/Encryption/File.php#L35
> lib/private/Files/Config/UserMountCache.php#L54
> lib/private/Files/Config/UserMountCache.php#L61
> lib/private/Files/Storage/LocalTempFileTrait.php#L40
> ```
> 
> We should check them after we decide how to handle this. Not all of them justify using a CappedMemoryCache, eg: lib/private/Config.php#L42

@DeepDiver1975 @rullzer @icewind1991 @schiesbn @nickvergessen

**Comment by PVince81** [comment]
More context: when running background jobs, many classes that are used might cache objects forever. This causes the memory usage to increase significantly and many cached objects aren't necessarily reused.

So one idea was to introduce the `CappedCache` everywhere an array is used for caching.

**Comment by rullzer** [comment]
Using a capped cache is a quickfix. But we should evaluate each change as to not break stuff when the cache is expected to hold more elements...

**Comment by nickvergessen** [comment]
I'd also say that it is just hiding other issues, but yeah, maybe we can set the size to something really huge for debug mode, so it still wastes memory for developers?

**Comment by PVince81** [comment]
From @butonic in the other ticket, itemized:

- [ ] [apps/user_ldap/group_ldap.php#L46](https://github.com/owncloud/core/blob/master/apps/user_ldap/group_ldap.php#L46)
- [ ] [apps/user_ldap/group_ldap.php#L51](https://github.com/owncloud/core/blob/master/apps/user_ldap/group_ldap.php#L51)
- [ ] [apps/dav/lib/connector/sabre/sharesplugin.php#L67](https://github.com/owncloud/core/blob/master/apps/dav/lib/connector/sabre/sharesplugin.php#L67)
- [ ] [apps/dav/lib/connector/sabre/tagsplugin.php#L80](https://github.com/owncloud/core/blob/master/apps/dav/lib/connector/sabre/tagsplugin.php#L80)
- [ ] [apps/dav/lib/connector/sabre/custompropertiesbackend.php#L75](https://github.com/owncloud/core/blob/master/apps/dav/lib/connector/sabre/custompropertiesbackend.php#L75)
- [ ] [lib/private/Encryption/File.php#L35](https://github.com/owncloud/core/blob/master/lib/private/Encryption/File.php#L35)
- [ ] [lib/private/Files/Config/UserMountCache.php#L54](https://github.com/owncloud/core/blob/master/lib/private/Files/Config/UserMountCache.php#L54)
- [ ] [lib/private/Files/Config/UserMountCache.php#L61](https://github.com/owncloud/core/blob/master/lib/private/Files/Config/UserMountCache.php#L61)
- [ ] [lib/private/Files/Storage/LocalTempFileTrait.php#L40](https://github.com/owncloud/core/blob/master/lib/private/Files/Storage/LocalTempFileTrait.php#L40)

**Comment by PVince81** [comment]
- [ ] "$app->generateBirthdays();"

**Comment by PVince81** [comment]
@blizzz can you do the LDAP one, @icewind1991 the mount caches and FS ones, @DeepDiver1975 `generateBirthdays` ?

The Sabre ones are low prio because they aren't called during background jobs or updates.

**Comment by nickvergessen** [comment]
`generateBirthdays` is a meta one, it calls the userManager, so nothing to do there.

**Comment by PVince81** [comment]
- [x] capped cache in user database backend: https://github.com/owncloud/core/pull/24405

**Comment by butonic** [comment]
This breaks upgrades on instances with more than ~10000-15000 users

**Comment by felixboehm** [comment]
@cmonteroluque This needs backport for 9.0.3

**Comment by PVince81** [comment]
Not sure if we can backport ALL of them once they are fixed, but we should at least backport the most impactful pieces.

**Comment by cmonteroluque** [comment]
@PVince81 @felixboehm we should talk about which get backported. Later today during the issue review call

**Comment by rullzer** [comment]
> apps/user_ldap/group_ldap.php#L46
> apps/user_ldap/group_ldap.php#L51 

PR in #24869

**Comment by PVince81** [comment]
PR for user mount cache: https://github.com/owncloud/core/pull/25056

PR for encryption: https://github.com/owncloud/core/pull/25055

**Comment by PVince81** [comment]
Oops, this should stay on 9.1.

Once the backports are merged, the other remaining cases are not really relevant to memory usage. For example Sabre plugin aren't used when running cron operations or updates.

**Comment by PVince81** [comment]
Regarding lib/private/Files/Storage/LocalTempFileTrait.php#L40 I don't think we can make this a capped cache as we'd lose track of what temp files were created and will be unable to clean them up afterwards.
Also I think these kind of temp files are only used when uploading/downloading files from external storage, so shouldn't be triggered as part of cron or updates.

Capped cache for Encryption cache info cache and UserMountCache have been backported to stable9.

The Sabre ones aren't relevant for cron or updates.

Moving the rest to 9.2 now.

@butonic let me know if you think otherwise

**Comment by PVince81** [comment]
I think we're done here, see my comment for the unticked cases.
Closing.
