### ISSUE TITLE
Calendar: Contact birthdays show date of birth as the date of the event,

### ISSUE THREAD

**Issue by matiasdelellis** [owncloud/core#24429]
### Steps to reproduce
1. Configure owncloud 9.0 with contacts and calendar enabled,
2. Add a user with birtday field (eg. 1986-06-03).
3. See on calendar the birtday of new contact.

### Expected behaviour
* See the event repeatedly every year, but the date must include the current year !.

### Actual behaviour
It shows the date of birth, when the event is in 2016

### Server configuration

Not revelant..

### Screenshot
![captura de pantalla_2016-05-03_23-00-58](https://cloud.githubusercontent.com/assets/733715/15003554/4e4b6336-1183-11e6-886e-a780ed3f2423.png)

**Comment by matiasdelellis** [comment]
P.s:. WishList: would be great that instead of "Name's (Date of birth)" shows "Name's (YearOld Years)", and this should be translated,!. 

Thanks,
Regards

**Comment by DeepDiver1975** [comment]
The event title cannot be translated.
Regarding the Year: the birthday is a recurring event.
That birthday event in june 2016 is on that day.

**Comment by RealRancor** [comment]
> WishList: would be great that instead of "Name's (Date of birth)" shows "Name's (YearOld Years)"

For that probably https://github.com/owncloud/calendar/issues/490 should be re-opened.
