### ISSUE TITLE
PHP 7.0.6 isset() change bricks owncloud9

### ISSUE THREAD

**Issue by Exordian** [owncloud/core#24425]
### Steps to reproduce
1. Install PHP 7.0.6
2. Install clean owncloud 9.0.1
3. Application broken

### Expected behaviour
-

### Actual behaviour
`isset($this->server['REQUEST_URI'])` returns always false.
`print_r($this->server, true)` returns that `REQUEST_URI` is set and has a value
`$requestUri = isset($this->server['REQUEST_URI']) ? $this->server['REQUEST_URI'] : '';` does set `$requestUri` to `""`

I've already told the PHP maintainers about that, but the response was to fix the behaviour change in the application: https://bugs.php.net/bug.php?id=69659

### Server configuration
**Operating system**:
Ubuntu 16.04 LTS

**Web server:**
Nginx

**Database:**
MySQL

**PHP version:**
7.0.6

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Updated from an older ownCloud or fresh install:**
Fresh Install

**Comment by RealRancor** [comment]
Already known and also already fixed in the upcoming 9.0.2: https://github.com/owncloud/core/pull/24343
