### ISSUE TITLE
Ubuntu 16.04 OBS --> broken

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#24427]
Seems like the build failed for 16.04: https://download.owncloud.org/download/repositories/stable/xUbuntu_16.04/

cc @jnweiger

**Comment by jnweiger** [comment]
Yes. build is disabled due to https://github.com/owncloud/core/issues/24367

**Comment by enoch85** [comment]
Ok, thanks for the info. Anyway, I see this as well: `W: https://download.owncloud.org/download/repositories/9.0:/testing/Ubuntu_16.04/Release.gpg: Signature by key BCECA90325B072AB1245F739AB7C32C35180350A uses weak digest algorithm (SHA1)`

Could you please fix this in coming releases?

**Comment by RealRancor** [comment]
@enoch85 That is tracked here: https://github.com/owncloud/core/issues/23599 . Seems it needs to be fixed by the OBS guys.

**Comment by Kawohl** [comment]
Ubuntu 16.04
Installing the owncloud package does not provide mysql. It only appears as recommendation. 
Also apache has no owncloud.conf. 

This is the ouptput of Terminal: 

`root@4e608f068d19:/# apt-get install owncloud
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  apache2 apache2-bin apache2-data apache2-utils fontconfig-config fonts-dejavu-core libapache2-mod-php7.0 libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap libasn1-8-heimdal libbsd0
  libc-client2007e libcurl3 libedit2 libexpat1 libffi6 libfontconfig1 libfreetype6 libgd3 libgdbm3 libgmp10 libgnutls30 libgssapi-krb5-2 libgssapi3-heimdal libhcrypto4-heimdal libheimbase1-heimdal
  libheimntlm0-heimdal libhogweed4 libhx509-5-heimdal libicu55 libjbig0 libjpeg-turbo8 libjpeg8 libk5crypto3 libkeyutils1 libkrb5-26-heimdal libkrb5-3 libkrb5support0 libldap-2.4-2 liblua5.1-0 libmagic1
  libmcrypt4 libnettle6 libp11-kit0 libperl5.22 libpng12-0 libpq5 libroken18-heimdal librtmp1 libsasl2-2 libsasl2-modules-db libsqlite3-0 libtasn1-6 libtiff5 libvpx3 libwind0-heimdal libx11-6
  libx11-data libxau6 libxcb1 libxdmcp6 libxml2 libxpm4 libxslt1.1 libzip4 mime-support mlock owncloud-deps-php7.0 owncloud-files perl perl-modules-5.22 php-common php7.0-cli php7.0-common php7.0-curl
  php7.0-gd php7.0-imap php7.0-intl php7.0-json php7.0-mbstring php7.0-mcrypt php7.0-mysql php7.0-opcache php7.0-pgsql php7.0-readline php7.0-sqlite3 php7.0-xml php7.0-zip psmisc ucf
Suggested packages:
  www-browser apache2-doc apache2-suexec-pristine | apache2-suexec-custom ufw php-pear uw-mailutils libgd-tools gnutls-bin krb5-doc krb5-user file libmcrypt-dev mcrypt php7.0-ldap php-smbclient
  | libsmbclient perl-doc libterm-readline-gnu-perl | libterm-readline-perl-perl make`
**Recommended packages:
  ssl-cert krb5-locales libsasl2-modules xml-core file mysql-server | mariadb-server | postgresql curl exim4 | mail-transport-agent netbase rename**
`The following NEW packages will be installed:
  apache2 apache2-bin apache2-data apache2-utils fontconfig-config fonts-dejavu-core libapache2-mod-php7.0 libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap libasn1-8-heimdal libbsd0
  libc-client2007e libcurl3 libedit2 libexpat1 libffi6 libfontconfig1 libfreetype6 libgd3 libgdbm3 libgmp10 libgnutls30 libgssapi-krb5-2 libgssapi3-heimdal libhcrypto4-heimdal libheimbase1-heimdal
  libheimntlm0-heimdal libhogweed4 libhx509-5-heimdal libicu55 libjbig0 libjpeg-turbo8 libjpeg8 libk5crypto3 libkeyutils1 libkrb5-26-heimdal libkrb5-3 libkrb5support0 libldap-2.4-2 liblua5.1-0 libmagic1
  libmcrypt4 libnettle6 libp11-kit0 libperl5.22 libpng12-0 libpq5 libroken18-heimdal librtmp1 libsasl2-2 libsasl2-modules-db libsqlite3-0 libtasn1-6 libtiff5 libvpx3 libwind0-heimdal libx11-6
  libx11-data libxau6 libxcb1 libxdmcp6 libxml2 libxpm4 libxslt1.1 libzip4 mime-support mlock owncloud owncloud-deps-php7.0 owncloud-files perl perl-modules-5.22 php-common php7.0-cli php7.0-common
  php7.0-curl php7.0-gd php7.0-imap php7.0-intl php7.0-json php7.0-mbstring php7.0-mcrypt php7.0-mysql php7.0-opcache php7.0-pgsql php7.0-readline php7.0-sqlite3 php7.0-xml php7.0-zip psmisc ucf
0 upgraded, 93 newly installed, 0 to remove and 0 not upgraded.
Need to get 49.2 MB of archives.
After this operation, 217 MB of additional disk space will be used.
`
Afaik we want the owncloud package to be the "one-command-happy-package", so we should make shure the configuration and dependencies are all included.... .

**Comment by enoch85** [comment]
@Kawohl @jnweiger That is also true, MySQL have to be pre-installed, forgot about that. Thank you @Kawohl!

**Comment by jnweiger** [comment]
Recommended is correct for the database-server we cannot know at packaging time if a local or remote database is to be used.

**Comment by PVince81** [comment]
@jnweiger would your latest package fix affect this issue too ?

**Comment by jnweiger** [comment]
No. This is a wontfix. I've had enough complains from the community that we should not force to install a database server.

Also, Recommends are installed by default (since Lucid).
If all this means that with 16.04 they switched back, then the install command needs to be:

    sudo apt-get --install-recommends install owncloud
