### ISSUE TITLE
Maintenance mode

### ISSUE THREAD

**Issue by x61s** [owncloud/core#24430]
All the modern servers has conditions to enable autoupdates because of CVE. Everytime the server updates (everynight) the owncloud is falling into maintenance mode. This must have regulated option or must be disabled. Production servers must be predictable! Thanks.

**Comment by RealRancor** [comment]
> Production servers must be predictable!

How are automatic updates of a web application on a production server predictable? A sane thing you can do is to pin the oC version and do manual updates of oC while still doing the automatic security updates of your system.

**Comment by PVince81** [comment]
closing as there is a workaround: pin the package
