### ISSUE TITLE
Eliminate render-blocking JavaScript and CSS in above-the-fold content

### ISSUE THREAD

**Issue by BaVanDuong** [owncloud/core#24436]
I tried test page speed using https://developers.google.com/speed/pagespeed/insights
And error bellow:

====================

Your page has 2 blocking script resources and 1 blocking CSS resources. This causes a delay in rendering your page.
None of the above-the-fold content on your page could be rendered without waiting for the following resources to load. Try to defer or asynchronously load blocking resources, or inline the critical portions of those resources directly in the HTML.
Remove render-blocking JavaScript:
https://server.com/…oc.js?v=609fcfe6c355b070397e6b2e5c35f0b9
https://server.com/…sets/873b841a9634e73b8915f18e07d7a643.js
Optimize CSS Delivery of the following:
https://server.com/…ets/15b98332ece639313490d7612edd0b38.css

=======================
Any suggest for this issue?
Thank you!

**Comment by PVince81** [comment]
Unfortunately this is old and the links don't tell exactly where this is happening.

AFAIK there should be no more render-blocking sync ajax calls any more, at least not in core.
If you are able to provide more detailed information, feel free to reopen.
