### ISSUE TITLE
[External storage - Google Drive] Outdated API library

### ISSUE THREAD

**Issue by altyr** [owncloud/core#24431]
The version of google-api-php-client in used in Owncloud is not a stable release and out of date (1.0.6 beta). Considering there are multiple issues with Google Drive support I'd like to propose updating it to the newest stable release (1.1.7) .
Among the improvements is a way to configure retries when experiencing 403 errors (which lead to problems as reported in #20481 ) seen in google/google-api-php-client/pull/416 and fixes for bugs requiring workarounds in the files_external code.
With a small modification early tests have shown that it works as a drop-in update (see [https://github.com/altyr/core/compare/master...altyr:117](https://github.com/altyr/core/compare/master...altyr:117) for details).

**Comment by LukasReschke** [comment]
> With a small modification early tests have shown that it works as a drop-in update (see altyr@master...altyr:117 for details).

Would you mind submitting a pull request with these changes? Thanks a lot 🚀

**Comment by altyr** [comment]
There we go. Sorry for staying silent this long, i had to fix my repo after mistakenly creating my other pull request directly from my master branch...

**Comment by altyr** [comment]
The updated pull request is located at #24799

**Comment by PVince81** [comment]
Lib was updated in https://github.com/owncloud/core/pull/24799
