### ISSUE TITLE
Wrong Path in Apache Alias Directive CentOS 7

### ISSUE THREAD

**Issue by CheckYourSix** [owncloud/core#24447]
The bug outlined in the link below still exists in ownCloud 9.0.2 (stable). It was marked as being fixed for 9.0.2.

See here for all of the information: https://github.com/owncloud/core/issues/23887

**Comment by LukasReschke** [comment]
@jnweiger

**Comment by sorvani** [comment]
I upgraded an install from 8.2.4 to 9.0.2 today and ran into this.

Write up on what I did can be found here:
http://mangolassi.it/topic/9072/owncloud-8-2-4-to-9-0-2-upgrade-problem

**Comment by Kawohl** [comment]
@jnweiger  can confirm the wrong  apache-alias entry...

**Comment by jnweiger** [comment]
fixed the templates https://github.com/owncloud/core/issues/23887
