### ISSUE TITLE
OCR to Tags

### ISSUE THREAD

**Issue by c0fe** [owncloud/core#24443]
Is there any plugin or plans for a built in feature to generate tags based on information from specific information? For example if you have thousands of invoices that while have the same base design but various information and have the tags generated from the different information.

**Comment by Kawohl** [comment]
https://doc.owncloud.org/server/9.0/admin_manual/enterprise_file_management/files_tagging.html 

Please Note: This is an Enterprise Subscription Feature.

**Comment by c0fe** [comment]
I have looked at that but it doesn't really do what I am thinking.

**Comment by PVince81** [comment]
in the future: workflow plugins

**Comment by PVince81** [comment]
=> separate app. Please ask on http://central.owncloud.org/ if you need help for the APIs
