### ISSUE TITLE
Notification for missing External Storage makes OC9 stuck at default app.

### ISSUE THREAD

**Issue by tilllt** [owncloud/core#24452]
On my OC9 installation i have some external SFTP mount points. For some reason these are not reachable right now (which should not be a problem). Owncloud gives me a notification about those missing storage points on everything i click, which is OK. But then OC is returning me to the default app (in my case: Files). 

This means, i cannot enter anything else anymore, no other app but als not the admin or settings menu. i guess this is related to the notification system, but i cannot investigate further right now since i am not at my machine.

**Comment by PVince81** [comment]
Do you mean you have mount points "/sftp1", "/sftp2" that are not accessible "Storage not available2 and also some regular folder "/regular". And whenever you clicked on one of the accessible ones, the "regular" isn't accessible either ?

**Comment by tilllt** [comment]
Yes, basically my owncloud installation is based on local storage (with a lot of folders and content), only some external folders from my NAS are mounted via sftp. 

Another strange thing is that these mount points are actually not offline, I checked and I can access them. Does the external storage tool have a really short timeout? Maybe the NAS needed some seconds to spin up the HD again after a while of inactivity.

**Comment by tilllt** [comment]
But to clarify, I believe this is entirely a GUI issue.  Apparently on every click, OC fires an update event for the notification System, which for some reason reloads the gui of the files app. So I cannot get out of it anymore since the page is reloaded before the link I clicked is followed.

**Comment by PVince81** [comment]
Please try again with 9.0.2 or 9.0.3 RC1. I believe the problem you have is that some bug doesn't let you navigate away while ajax requests are pending: https://github.com/owncloud/core/pull/23487

If you're still seeing the issue, please reopen and use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
