### ISSUE TITLE
OC is bricked; PHP7.0: 404 Not Found /remote.php/caldav/principals/.....

### ISSUE THREAD

**Issue by peterkahl** [owncloud/core#24459]
<!--

My OC worked really well with PHP7.0 on nginx until about late March 20016. Around that time, when I upgraded my PHP7.0 to slightly newer version, OC broke and is BRICKED

### Actual behaviour
Getting status 404 on these URLs:
/remote.php/caldav/principals/........
/index.php/core/js/oc.js?v=....

This prevents me from even logging into OS.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
nginx 1.9.15

**Database:**
MariaDB

**PHP version:**
7.0.5

**ownCloud version:** (see ownCloud admin page)
Latest

**Updated from an older ownCloud or fresh install:**
Updated

**Comment by DeepDiver1975** [comment]
Anything in the server logs?

**Comment by peterkahl** [comment]
OC log shows nothing at all. 
Only my nginx log shows status 404.

**Comment by DeepDiver1975** [comment]
I'm sorry - but there is not much we can do. I'd suspect some config issues within nginx ... but I'm not sure.

**Comment by PVince81** [comment]
You might have more luck finding help in the forums or http://owncloud.org/support from other people using nginx

**Comment by RealRancor** [comment]
Make sure that you're running PHP 7.0.6, oC 9.0.2 and the config provided here:

https://github.com/owncloud/documentation/wiki/ownCloud-9.x-nginx-config

Working here without any issues

**Comment by Wiebelt** [comment]
Maybe you could add
```
echo '$this->server[\'REQUEST_URI\'] = '; var_dump($this->server['REQUEST_URI']);
                echo 'isset($this->server[\'REQUEST_URI\']) = '; var_dump(isset($this->server['REQUEST_URI']));

                echo '$_SERVER[\'REQUEST_URI\'] = '; var_dump($_SERVER['REQUEST_URI']);
                echo 'isset($_SERVER[\'REQUEST_URI\']) = '; var_dump(isset($_SERVER['REQUEST_URI']));
```

To the file lib/private/AppFramework/Http/Request.php after line 608, so after 
```
$requestUri = isset($this->server['REQUEST_URI']) ? $this->server['REQUEST_URI'] : '';
```

And then go to /index.php/core/js/oc.js and post the debug output here to see if it is the same bug i am affected by.

**Comment by Xenopathic** [comment]
@Wiebelt If you are experiencing an issue, please open an issue report, don't hijack this report with a request to the OP. However, you are probably experiencing the bug that was fixed with 9.0.2, so upgrade to that if you haven't already.

**Comment by peterkahl** [comment]
As I said, my nginx configuration had worked flawlessly for ~ 1 year, so I am confident that I know how to set up nginx properly.

**Comment by peterkahl** [comment]
Okay. I used this to unbrick OC: [https://github.com/owncloud/core/pull/24343/commits/a834531aef418688538adb809a796cf830c5385b](https://github.com/owncloud/core/pull/24343/commits/a834531aef418688538adb809a796cf830c5385b)

Now will try to upgrade to 9.0.2.
