### ISSUE TITLE
Upload timing problem from a local owncloud system to a federated share

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#24454]
### Steps to reproduce
- **Following setup:** two owncloud systems. System A (this system, 9.0.x) is local, system B (9.0.x) is remote and shares a folder (r/w) to user Z in system A. The max internet upload speed to the remote system is 5mbit/s. The local network speed is at minimum 20MB/s (WLAN).
- There is no quota set (unlimited) for user Z
- Uploading via the browser a videofile with a size of 165MB directly to the shared folder. It is important that there is a big difference between upload speed to local and from local to remote and a big filesize to transfer.
- You see the upload progress bar running (relatively quick) and the bar stops correctly at 100%. Monitoring the network on the uploading client shows that after finishing no more traffic is going on. This is as expected.
- Now the progress bar stops at 100% and nothing more is happening for a while. After some time, you get an error highlighted in a yellow bar in th browser that there was an error during uploading.
![image](https://cloud.githubusercontent.com/assets/3321281/15049736/3531a324-12f0-11e6-9f9a-82d1ee4ed889.png)
- When you reload the page,your videofile is not shown in the file list.
- After waiting more time and reloading the page, the uploaded file is shown and fully accessible.

1. There are no errors logged in owncloud and the webservers log (no php timeouts)
2. The upload via the browser gets buffered (stored) on the local system and from there uploaded to the federated target system.
3. It seems that we run into a internal timeout, but the system continues uploading
4. The upload finally succeeds, even the error message is shown in the browser

**Statement:**
We need to think about how to handle this szenario in a better way.

**Questions:**
- What happens if the upload speed is much lower respectively the time needed to upload data from system A to system B takes either much more time or the wire may get interrupted ect...
- What will be shown to the user when the upload to the local system A completes but takes a while to internally transfer to system B 

This behaviour has more than this impact described, because when you upload via the owncloud sync client, things get even more worse. But for this one I write a own issue in the client repository and link to this one.

### Expected behaviour
Upload should run without errors, maybe an additionally new way of showing where we really are.

**Suggestion:** showing an new and independent upload progress bar for these kind of internal uploads where it is not needed to be logged on via the browser, but when logged on and something is in progess showing that one. Like a progress bar for browser to system A, closes when finished and a second progress bar for all internal uploads for that user from system A to system B (or just think about a slow ftp wire ect)

### Actual behaviour
Described above

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page)
9.0.2 RC1 (daily) Build:2016-04-28T03:03:12+00:00 795f321a1985b682bff584f252dd6f2fd95dad65

**Updated from an older ownCloud or fresh install:**
updated from the latest downloadable tar

**Where did you install ownCloud from:**
tar

**Signing status (ownCloud 9.0 and above):**

```
Results
=======
- core
	- INVALID_HASH
		- 3rdparty/sabre/dav/composer.json
		- 3rdparty/sabre/dav/lib/CalDAV/Plugin.php
		- 3rdparty/sabre/dav/lib/DAV/Version.php
		- 3rdparty/sabre/dav/CHANGELOG.md
		- 3rdparty/composer/LICENSE
		- 3rdparty/composer/installed.json
		- 3rdparty/composer/autoload_classmap.php
		- 3rdparty/composer.lock
		- 3rdparty/composer.json

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [3rdparty/sabre/dav/composer.json] => Array
                        (
                            [expected] => a07fe7be4630028e2a904d1530f76f105ef299a654679ea8a5ec8dd5f76556e2c4afffe017caed32d7c6bfc4a6a1be26fcdf973e6303a2ecc00239ac39a1ec16
                            [current] => 075c6f3eeaa579c2c974725e89a373243452035aebd2bf7b2ebc79afef55d82ac0de54b3805ca950c0d92d7e88f715dc1487afe38815475afdbdbaa310d18c26
                        )

                    [3rdparty/sabre/dav/lib/CalDAV/Plugin.php] => Array
                        (
                            [expected] => c674009a1a62b833789b9f6d30affc5306147559103655505bb88915eecd961367dcfca593a53d65a16c81f6cc3b17b578805c34e82dfeeaf25a3b1ad6aeedb6
                            [current] => 205b4616980dd0bb635b67cf4f54ba66f06405fc72a7b19742be5d6fed4b11517f3160101cbf326ae17010741310ab8d3ed739cf4a07ee43a055f904efc0a142
                        )

                    [3rdparty/sabre/dav/lib/DAV/Version.php] => Array
                        (
                            [expected] => 197daddea9674aece439b4927c48a3a986fd16a3196be387ac825cb8350c9e5be0b1ed6567188debad27a672bf65fffe64f2051e8c206e8f9847ec24e1036793
                            [current] => 753a49f006305bb42c811aab2a8ea2fdd4d97e4697065e76781fdb632001b9f3776ba9223baa2fbf9cf2ad52ca00972f8ff97d1aaa8d9d894629e10dff61a617
                        )

                    [3rdparty/sabre/dav/CHANGELOG.md] => Array
                        (
                            [expected] => a00ce8728fee3d85aec04b5fcaf707cc928418d065e5fba0cfaa19017a59d1d2a583a31afa0538dc6779464c8312f32375805d9089eab234addff71053db0ee7
                            [current] => 1680660bf8eeba002066fa0299dd99b85052d8d5d78fe5549539160e8c71cac5e69e304232c8be824ae5a3484b7f4ec1a6e5ea39b8c4a5954d153bd94d5158ff
                        )

                    [3rdparty/composer/LICENSE] => Array
                        (
                            [expected] => 8e82aa3b2b27802b2c9d18fe596739e791f3d187b7d231d93baafa663da15813031e386f77a14ebd512695b061e896b7bef82e8f23e697a0761a8611d8c07b04
                            [current] => 90a255aa80d0e5a7c5bf84901dbd450249908434e0b4d97a7eb0d80b37ff072b2efc8bd4c57f16b618fcf46dcc8213c22baa860254bde06d9eea347ce3d592c0
                        )

                    [3rdparty/composer/installed.json] => Array
                        (
                            [expected] => a4d896ff2d5f565ea51aeb57e6f16504fbf79fc40822745793808a1d8e82fbc9381091f927720a79ba0e793c71539999a1fa767d17f84d6a30e9829400ed0722
                            [current] => 043dd72279d7bf65b8cf755620f4db22500a5c826ad770ce18d08bfd1fe961f72550f6d73fae38c0f6c37a69553ba223316ff1b8ac798809decf212d85afb056
                        )

                    [3rdparty/composer/autoload_classmap.php] => Array
                        (
                            [expected] => abe09be19b6d427283cbfa7c4156d2c342cd9368d7d0564828a00ae02c435b642e7092cef444f94635f370dbe507eb6b2aa05109b32d8fb5d8a65c3a5a1c658f
                            [current] => 4de95285a99044d62773dca1f7014a647ed8c6e08cfa587d1c8b865f49e9df776aa02c2d3b80939daf0eb0f497121757c499667938de17bbb2deb1c03f0090f0
                        )

                    [3rdparty/composer.lock] => Array
                        (
                            [expected] => 4009394ebef9351310157269ebfc244893b281dc40285482665a6dc27047e80ffca38f7ce912c30d95ea5b20a98bc8e0740b866d4f92211e912ba568c0e1486e
                            [current] => 8e82a37d2aa9b511306d51f2782c0b03f9bdc1ebd31856e576932d73cd8b9fe49b2c787a02a7ae122992c60a23dfad0e744c116b1db5622041f2498852677b4f
                        )

                    [3rdparty/composer.json] => Array
                        (
                            [expected] => 7309e217188a61a6ac39a5d4cd70b1c43e86b49d1bf903d72d561aa231a1481192f73e45fe20b8f85d57e95925bb6567d382bab5aaba661b533a589dc48287e7
                            [current] => a6a9174f672638566a53d43a82503872795c536fbc5e4562a9a43028542c33ecb2419749a393132d00f9518f0cb0c82cc81383073d697acb615026211e0d3293
                        )

                )

        )

)
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ock982ae3c5s",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx"
        ],
        "datadirectory": "\/var/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xxx",
        "dbtype": "mysql",
        "version": "9.0.2.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "assetdirectory": "\/mnt\/mm-eddie\/www\/owncloud",
        "asset-pipeline.enabled": true,
        "filesystem_check_changes": 1,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Raw"
        ],
        "loglevel": 2,
        "maintenance": false
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:** Opera

**Operating system:** W7x64

#### Web server error log
```
No corresponding error log
```

#### ownCloud log (data/owncloud.log)
```
No corresponding error log
```

**Comment by PVince81** [comment]
or instead of an additional progress bar, make it so that the file is directly streamed to the target instead of doing the "upload to tmp folder, then upload to final target" gymnastics. See the more general ticket: https://github.com/owncloud/core/issues/5949

Adding a new progress bar is likely to be very tricky, because PHP has no way to tell the UI about the current upload state from within a for-loop that copies blocks within a `fopen`. It would need some kind of persistent/pipe (socket IO?) to be able to tell the client that something is going on. Also it is not compatible with Webdav either, because a Webdav PUT doesn't return progress information.
The progress bar you see is really just the browser's block-uploading until PHP got the full file but hasn't closed the connection yet.
A separate progress bar would need a second separate endpoint that the UI would need to poll / listen to to receive updates. This is also tricky because PHP doesn't keep state between PHP requests, so it would also need a new table to track upload progress so that separate PHP requests can query it.

All in all, I think the second progress bar approach isn't worth it due to complexity.
We should rather try and find a way to directly stream to the remote Webdav server without going to temp space.

Code ref: https://github.com/owncloud/core/blob/v9.0.2/lib/private/files/storage/dav.php#L406

I think there were already some experiments about this but somehow I can't find the tickets/PRs any more.

**Comment by mmattel** [comment]
@PVince81 you are totally right, your approach of directly streaming it to the target storage is much better.

The current situation is really bad, because when using the sync client, you may run into a deadlock (especially with the sync client because uploading is automated).

I think it is necessary to evaluate all possible storage backends for their ability of direct streaming.

In case there is still the need for caching for some storage backends, we should imho think about to populate an additional info to the sync client that uploading for a particular cached file is still in progress to avoid recurring re-uploads. This would also include fixing the confusing uploading error message (see above). Just my 2c...

**Comment by PVince81** [comment]
Additional info for the sync client: this is as complicated as the progress bar as explained above.
This goes into "async upload" territory: https://github.com/owncloud/core/issues/12097

I'm going to close this ticket in favor of:
- async PUT: https://github.com/owncloud/core/issues/12097
- stream upload: https://github.com/owncloud/core/issues/5949
