### ISSUE TITLE
[9.0.1.3] Using hostname localhost instead of IP 127.0.0.1 throws SQLSTATE[HY000] [2002] No such file or directory error

### ISSUE THREAD

**Issue by andreasba** [owncloud/core#24463]
Good morning,

I hope this is the right place to post this issue - I have searched for it but did not found it.

### Steps to reproduce
1. Install fresh copy of OC via setup-owncloud.php
2. Migrate to MySQL (couldn't use MySQL in the first place because I am on a shared webhost and I cannot provide root MySQL access)
3. Try to load OC web-client at https://mycloudwebsite.com

### Expected behaviour
The OC webclient login should show up

### Actual behaviour
An internal server error is displayed. The log shows:

`{"reqId":"xxxxx","remoteAddr":"84.xxx.xxx.xxx","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\DBALException\",\"Message\":\"Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/www\\\/mycloudwebsite.com\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(429): OC\\\\DB\\\\Connection->connect()\\n#1 \\\/home\\\/www\\\/mycloudwebsite.com\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(389): Doctrine\\\\DBAL\\\\Connection->getDatabasePlatformVersion()\\n#2 \\\/home\\\/www\\\/mycloudwebsite.com\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(328): Doctrine\\\\DBAL\\\\Connection->detectDatabasePlatform()\\n#3 \\\/home\\\/www\\\/mycloudwebsite.com\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(621): Doctrine\\\\DBAL\\\\Connection->getDatabasePlatform()\\n#4 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/db\\\/connection.php(137): Doctrine\\\\DBAL\\\\Connection->setTransactionIsolation(2)\\n#5 \\\/home\\\/www\\\/mycloudwebsite.com\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DriverManager.php(172): OC\\\\DB\\\\Connection->__construct(Array, Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#6 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/db\\\/connectionfactory.php(116): Doctrine\\\\DBAL\\\\DriverManager::getConnection(Array, Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#7 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/server.php(366): OC\\\\DB\\\\ConnectionFactory->getConnection('mysql', Array)\\n#8 \\\/home\\\/www\\\/mycloudwebsite.com\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#9 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(102): Pimple\\\\Container->offsetGet('DatabaseConnect...')\\n#10 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/servercontainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('DatabaseConnect...')\\n#11 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/server.php(886): OC\\\\ServerContainer->query('DatabaseConnect...')\\n#12 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/server.php(260): OC\\\\Server->getDatabaseConnection()\\n#13 \\\/home\\\/www\\\/mycloudwebsite.com\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#14 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(102): Pimple\\\\Container->offsetGet('AppConfig')\\n#15 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/servercontainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('AppConfig')\\n#16 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/server.php(825): OC\\\\ServerContainer->query('AppConfig')\\n#17 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/util.php(424): OC\\\\Server->getAppConfig()\\n#18 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/util.php(357): OC_Util::loadVersion()\\n#19 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/public\\\/util.php(72): OC_Util::getVersion()\\n#20 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/defaults.php(52): OCP\\\\Util::getVersion()\\n#21 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/template.php(79): OC_Defaults->__construct()\\n#22 \\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/template.php(339): OC_Template->__construct('', 'exception', 'error', false)\\n#23 \\\/home\\\/www\\\/mycloudwebsite.com\\\/index.php(55): OC_Template::printExceptionErrorPage(Object(Doctrine\\\\DBAL\\\\DBALException))\\n#24 {main}\",\"File\":\"\\\/home\\\/www\\\/mycloudwebsite.com\\\/lib\\\/private\\\/db\\\/connection.php\",\"Line\":54}","level":3,"time":"2016-05-06T07:14:59+00:00","method":"GET","url":"\/","user":"--"}`

However, when I change my MySQL host in the config.php from localhost to 127.0.0.1, it works!

`user@server ~ # ping localhost
PING localhost (127.0.0.1) 56(84) bytes of data.
64 bytes from localhost (127.0.0.1): icmp_req=1 ttl=64 time=0.049 ms
64 bytes from localhost (127.0.0.1): icmp_req=2 ttl=64 time=0.030 ms
64 bytes from localhost (127.0.0.1): icmp_req=3 ttl=64 time=0.036 ms
^C
--- localhost ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.030/0.038/0.049/0.009 ms
`

### Server configuration
**Operating system**: Linux

**Web server:** Apache 2.x

**Database:** MySQL 5

**PHP version:** 7 (current stable)

**ownCloud version:** 9.0.1.3

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** via setup-owncloud.php script from owncloud.org

**Signing status (ownCloud 9.0 and above):** {"installed":true,"maintenance":false,"version":"9.0.1.3","versionstring":"9.0.1","edition":""}

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:** None? Except standard apps

Thanks
Andreas

**Comment by RealRancor** [comment]
Your PHP is wrongly configured and can't access the socket of your MySQL server (sockets are used when specified "localhost", tcp when choosing 127.0.0.1). A search on the net should guide you to further info.
