### ISSUE TITLE
Middle ground for 9.0+ integrity checking

### ISSUE THREAD

**Issue by hogarthj** [owncloud/core#24465]
I'm in the process of packaging 9.0.2 for Fedora/EPEL7 and I appreciate the reasons the integrity checking was added but the message about missing files is something I'd rather not have my users encounter.

In order to comply with our guidelines we need to carry out the unbundling however - which of course leads to this.

I'm aware of the hidden configuration option to disable the integrity checking - but that would affect validation of the apps from the store as well... which considering those apps don't come from RPM but just archive files would be well served to have validation (of signing and integrity).

Could we have an option (via hidden configuration if need be) to only carry out the checks on appstore additions?

**Comment by LukasReschke** [comment]
> Could we have an option (via hidden configuration if need be) to only carry out the checks on appstore additions?

That sounds sensible. The flag should:

1. Show a warning at `index.php/settings/integrity/failed` that the code checker has been disabled for core
2. Still perform check for apps

**Comment by hogarthj** [comment]
Thanks Lukas - that would be right in line with my thoughts on a nice way to handle it.

You guys still get the heads up it's a packaged (franken?) owncloud so in the initial instance hopefully the user would be directed to our bugtracker, and if it's something that's replicable in your vanilla version we can open an issue with you - or fix whatever packaging issue is causing it if not.

**Comment by PVince81** [comment]
@VicDeo can you take care of this ?

**Comment by PVince81** [comment]
@hogarthj you can now use "integrity.excluded.files" in the default config to specify what files should not be checked in case you removed them.

Please reopen if that solution is not suitable.
