### ISSUE TITLE
CalDAVBackend::createSubscription ignores a lot of properties

### ISSUE THREAD

**Issue by georgehrke** [owncloud/core#24469]
https://github.com/owncloud/core/blob/master/apps/dav/lib/caldav/caldavbackend.php#L1063-1070

This code only inserts the hardcoded values. Properties like displayname, color, order, stripAlerts and stripAttachments are simply ignored without further notice.

createCalendar inserts all supported properties: https://github.com/owncloud/core/blob/master/apps/dav/lib/caldav/caldavbackend.php#L378-380

**Comment by georgehrke** [comment]
cc @DeepDiver1975

**Comment by PVince81** [comment]
@georgehrke I set the severity to medium, let me know if it is worse

**Comment by georgehrke** [comment]
Medium is fine :)
