### ISSUE TITLE
GBK text files display garbage.

### ISSUE THREAD

**Issue by chansey97** [owncloud/core#24464]
### Steps to reproduce
1.create "gbk_testfile.txt" in windows7 (chinese version).
2.write "测试GBK中文乱码" and save.
2.upload this file to owncloud.
3.gbk_testfile.txt will display garbage (content is garbage).

### Expected behaviour
Display correct content (chinese encoding).

### Actual behaviour
Display garbage content.
Note: If I convert "gbk_testfile.txt" from GBK to UTF-8,  there is no problem (display correct content).

### Server configuration
**Operating system**:
ubuntu 14.04

**Web server:**
apache2

**Database:**
mysql 5.5.49

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.1 (stable)

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
https://owncloud.org/install/

**Signing status (ownCloud 9.0 and above):**
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
Activity 2.2.1
Collaborative tags 0.2
Comments 0.2
Deleted files 0.8.0
Federation 0.0.4
First Run Wizard
Gallery 14.5.0
Mail Template Editor 0.1
Notifications 0.2.3
PDF Viewer 0.8
Provisioning API 0.4.1
Share Files 0.9.1
Text Editor 2.1
Update notification 0.1.0
Versions 1.2.0
Video player 0.9.8

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => "***REMOVED SENSITIVE VALUE***",
  'passwordsalt' => "***REMOVED SENSITIVE VALUE***",
  'secret' => "***REMOVED SENSITIVE VALUE***",
  'trusted_domains' =>
  array (
    0 => "***REMOVED SENSITIVE VALUE***",
  ),
  'datadirectory' => "***REMOVED SENSITIVE VALUE***",
  'overwrite.cli.url' => "***REMOVED SENSITIVE VALUE***",
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => "***REMOVED SENSITIVE VALUE***",
  'dbhost' => "***REMOVED SENSITIVE VALUE***",
  'dbtableprefix' => "***REMOVED SENSITIVE VALUE***",
  'dbuser' => '"***REMOVED SENSITIVE VALUE***",
  'dbpassword' => "***REMOVED SENSITIVE VALUE***",
  'logtimezone' => 'UTC',
  'installed' => true,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows7 (note: ios owncloud client  can reproduce too)

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by chansey97** [comment]
Add some pictures:

Create gbk .txt in ultraedit:
![](https://github.com/chansey97/ocissue/blob/master/gbk_ultraedit.PNG?raw=true)
Display garbage:
![](https://github.com/chansey97/ocissue/blob/master/gbk_garbage.PNG?raw=true)

Create utf8 .txt in ultraedit:
![](https://github.com/chansey97/ocissue/blob/master/utf8_ultraedit.PNG?raw=true)
Display correct:
![](https://github.com/chansey97/ocissue/blob/master/utf8_garbage.PNG?raw=true)

**Comment by Xenopathic** [comment]
People still use non-UTF-8 charsets? :see_no_evil:

**Comment by chansey97** [comment]
@Xenopathic This because GBK characters is default encoding when you create .txt files in Windows7 (Chinese version).

**Comment by PVince81** [comment]
@Xenopathic not exactly. This is the text editor app and it has some auto-detection routines: https://github.com/owncloud/files_texteditor/blob/master/controller/filehandlingcontroller.php#L92

But it doesn't include any of the chinese encodings, not sure if those could cause false positives.

Also see https://github.com/owncloud/files_texteditor/pull/73
Closing as duplicate.

**Comment by chansey97** [comment]
@PVince81 Nice work! After merge this patch, the .txt file can display correct content.

**Comment by chansey97** [comment]
@PVince81 But on iOS device, GBK still display garbage..... (This patch only works on web version)

**Comment by PVince81** [comment]
@chansey97 yes of course, it's only the text editor app. ownCloud itself doesn't convert encodings as it is supposed to deliver the files as is (binary-same).

Maybe you are referring to the IOS app's file viewer, in this case please make a ticket here: https://github.com/owncloud/ios
The viewer bit of the clients will need to do the encoding conversion.

**Comment by chansey97** [comment]
@PVince81 Thanks for your reply. The file viewer of the iOS app maybe need add some encoding detect code which like php version. But I still found some issue in this case (maybe a design issue)

Now I can upload a gbk .txt file to owncloud, but when I edit and save this file in website, this file will be convert to UTF-8. I think this not a good idea, because this not "Synchronization".

I doesn't change the file encoding, why file encoding is changed when synchronization?

**Comment by PVince81** [comment]
@chansey97 the encoding must be changed, else the web browser will not be able to display the contents for the editor. It is not technically possible to mix UTF-8 encodings (default) with other encodings within the same HTML page.

One "solution" would be for the text editor to remember the encoding and then reuse it when saving the file. This would be a feature request for the text editor: https://github.com/owncloud/files_texteditor
