### ISSUE TITLE
OC\AppFramework\Http\Request::getRawPathInfo() is broken on PHP 7.0.6 and breaks routing. (it looks like it is a PHP bug!)

### ISSUE THREAD

**Issue by Wiebelt** [owncloud/core#24474]
### Steps to reproduce
1. Run owncloud under PHP 7.0.6
2. Try to access /index.php/core/js/oc.js and probably any other sub url

### Expected behaviour
You should get the oc.js javascript code.

### Actual behaviour
Instead you will get login page and it is not possible to log in.

### What i found when i debugged the code
What i found when i debugged the code was that getRawPathInfo returns a emtpy string, this in turn stops the routing from working correctly.

This is, after some more debugging caused by [the following line](https://github.com/owncloud/core/blob/master/lib/private/AppFramework/Http/Request.php#L608)
```php
 $requestUri = isset($this->server['REQUEST_URI']) ? $this->server['REQUEST_URI'] : '';
```

I added the following code to debug it some more: 
```php
                echo '$this->server[\'REQUEST_URI\'] = '; var_dump($this->server['REQUEST_URI']);
                echo 'isset($this->server[\'REQUEST_URI\']) = '; var_dump(isset($this->server['REQUEST_URI']));

                echo '$_SERVER[\'REQUEST_URI\'] = '; var_dump($_SERVER['REQUEST_URI']);
                echo 'isset($_SERVER[\'REQUEST_URI\']) = '; var_dump(isset($_SERVER['REQUEST_URI']));
```

What happens is that for some reason isset returns false even when $this->server['REQUEST_URI'] is set. It does work correctly on $_SERVER['REQUEST_URI'].

```
$this->server['REQUEST_URI'] = string(36) "/index.php/settings/integrity/failed"
isset($this->server['REQUEST_URI']) = bool(false)
$_SERVER['REQUEST_URI'] = string(36) "/index.php/settings/integrity/failed"
isset($_SERVER['REQUEST_URI']) = bool(true)
$requestUri = string(0) ""
```

This  is probably a PHP bug? What would i file it under? I cant recreate it yet without the owncloud code. I tried it with:
```php
$test = array('key' => 'value');
var_dump(isset($test['key']));
```
But this returns true like it is supposed to.

I also think this is also the reason for issue #24459

### Server configuration
**Operating system**: Debian GNU/Linux 8.4 (jessie)

**Web server:** nginx/1.8.1

**Database:** postgresql

**PHP version:** PHP 7.0.6-1~dotdeb+8.1, running as FPM

**ownCloud version:** 9.0.1

**Updated from an older ownCloud or fresh install:** Updated from the previous 8 version

**Where did you install ownCloud from:** Manual install

**Signing status (ownCloud 9.0 and above):** Dont know what this means?

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ock8k4vu8dtr",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "s.wiebelt.nl"
        ],
        "datadirectory": "\/home\/owncloud\/s.wiebelt.nl\/public\/data",
        "overwrite.cli.url": "https:\/\/s.wiebelt.nl",
        "dbtype": "pgsql",
        "version": "9.0.1.3",
        "dbname": "owncloud_owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "wiebelt.nl",
        "theme": "",
        "maintenance": false,
        "loglevel": 4,
        "trashbin_retention_obligation": "auto",
        "asset-pipeline.enabled": false,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "password": redacted
        }
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no.

**Are you using encryption:** yes/no
no.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no.

**Comment by Wiebelt** [comment]
I tried to replicate it with this:
```

<?php
class Test
{
        public function __construct()
        {
                $this->testArray = array('key' => 'value');
                $this->serverArray = $_SERVER;
        }

        public function bug()
        {
                var_dump(isset($this->testArray['key']));
                var_dump(isset($this->serverArray['REQUEST_URI']));
        }
}

$test = new Test;
$test->bug();
```

But that also works as expected and returns true for both.

**Comment by Glandos** [comment]
I confirm this. After adding the debug lines in getRawPathInfo, I got this when calling `/index.php/core/js/oc.js?v=14a752a1e8a152af7ad6c90e31e6a821`:

```
$this->server['REQUEST_URI'] = string(59) "/index.php/core/js/oc.js?v=14a752a1e8a152af7ad6c90e31e6a821"
isset($this->server['REQUEST_URI']) = bool(false)
$_SERVER['REQUEST_URI'] = string(59) "/index.php/core/js/oc.js?v=14a752a1e8a152af7ad6c90e31e6a821"
isset($_SERVER['REQUEST_URI']) = bool(true)
$this->server['REQUEST_URI'] = string(59) "/index.php/core/js/oc.js?v=14a752a1e8a152af7ad6c90e31e6a821"
isset($this->server['REQUEST_URI']) = bool(false)
$_SERVER['REQUEST_URI'] = string(59) "/index.php/core/js/oc.js?v=14a752a1e8a152af7ad6c90e31e6a821"
isset($_SERVER['REQUEST_URI']) = bool(true)
```

I am using Debian/testing, and this issue happens right after migrating from PHP 7.0.4 to 7.0.6.

This hacky-do-not-try-this-at-home patch solved the problem for me:

``` patch
diff --git a/lib/private/appframework/http/request.php b/lib/private/appframework/http/request.php
index c415e60..e393381 100644
--- a/lib/private/appframework/http/request.php
+++ b/lib/private/appframework/http/request.php
@@ -595,7 +595,7 @@ class Request implements \ArrayAccess, \Countable, IRequest {
         * @return string Path info
         */
        public function getRawPathInfo() {
-               $requestUri = isset($this->server['REQUEST_URI']) ? $this->server['REQUEST_URI'] : '';
+               $requestUri = isset($_SERVER['REQUEST_URI']) ? $this->server['REQUEST_URI'] : '';
                // remove too many leading slashes - can be caused by reverse proxy configuration
                if (strpos($requestUri, '/') === 0) {
                        $requestUri = '/' . ltrim($requestUri, '/');
```

**Comment by Wiebelt** [comment]
Using $_SERVER is indeed a albeit hacky work around for this specific problem. 

isset() not working correct really does make me worry about the corectness of other code though. Other lines of code might take wrong decisions because of this and cause other more subtle and hard to find bugs that wont surface as fast.

Using PHP5 for now is probably a better and safer "workaround" until this gets fixed.

**Comment by Xenopathic** [comment]
This was fixed with 9.0.2. Please upgrade

**Comment by RealRancor** [comment]
The fix itself is here: https://github.com/owncloud/core/pull/24343

**Comment by Wiebelt** [comment]
Upgrading to 9.0.2 fixed it, thanks! I'll read the info about the bugfix later since im curious now :-)
