### ISSUE TITLE
No update anymore on stable channel...

### ISSUE THREAD

**Issue by valentin8709** [owncloud/core#24479]
I have noticed that I don't have update notification / possibility anymore in the update app... Running owncloud 9.0.1, stable channel, php 7.0.0, apache 2 and Mysql on Linux Mint 17.3. The only way to update is to download the last archive and uncompress it to the actual folder.

Is it normal? Thank you for your answers =)

**Comment by RealRancor** [comment]
@valentin8709 Yes, thats currently expected:

> Those waiting for an update notification from the updater app won’t have to wait much longer. We ran in some issues at the 9.0.1 release but these have been resolved, a new updater server is being tested and things should start working by the end of this week. The Virtual Machine images have not yet been fully updated, these will come as soon as possible.

https://owncloud.org/blog/maintenance-releases-9-0-2-8-2-4-8-1-7-8-0-12-and-7-0-14-out-time-to-upgrade/

**Comment by valentin8709** [comment]
Okay thank you very much =)
