### ISSUE TITLE
Allow alternate port option for sftp external storage

### ISSUE THREAD

**Issue by markc** [owncloud/core#24477]
As far as I can tell this is the right place to request an enhancement. I can't find a more dedicated project for external storage apps and a search here for "sftp port" does not show any related issues.

IMHO it is almost mandatory to allow for alternate port option when setting up SFTP external storage. The default port 22 attracts a lot of scripted probing and the simplest way to avoid most of it is to run a ssh server on any alternate port. However when selecting the SFTP external storage option there is no choice for any other port so this is a request for such an option to be added to the external storage app.

**Comment by Xenopathic** [comment]
It is mandatory. That's why we do support it, as is clearly stated in the second paragraph of the [documentation](https://doc.owncloud.org/server/9.0/admin_manual/configuration_files/external_storage/sftp.html)
