### ISSUE TITLE
Copy link to clipboard from various fields

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24472]
There might be new APIs that makes it possible to copy stuff into the clipboard through Javascript.

It would be nice to auto-copy links whenever a link field is highlighted.
Some examples:
- [ ] Webdav link in files app sidebar bottom section: https://github.com/owncloud/core/issues/14415
- [x] Public link share links
- [ ] Permalinks (https://github.com/owncloud/core/issues/11732)

Also I wonder if it would help somehow with mobile (CC @oparoz)

@georgehrke @rullzer 

On Github, I believe you need to have flash enabled for the copy functions to work. But we'd likely not want flash (optionally) due to security reasons, can you confirm @LukasReschke ?

**Comment by LukasReschke** [comment]
> But we'd likely not want flash (optionally) due to security reasons, can you confirm @LukasReschke ?

That's correct. Also Flash files won't execute due to our CSP :)

**Comment by PVince81** [comment]
https://clipboardjs.com/

**Comment by oparoz** [comment]
>https://clipboardjs.com/

Doesn't this require the use of an extra button?

**Comment by nickvergessen** [comment]
* Activity RSS link
* Calendar DAV url

**Comment by oparoz** [comment]
Maybe having a [copy] button isn't such a bad idea. Just saw a user struggle with the fact that the whole URL isn't showed when trying to copy a shared link.

**Comment by PVince81** [comment]
Some work has started by @DeepDiver1975 for public links.
There are still other fields that could use the copy functionality:
- Webdav: https://github.com/owncloud/core/issues/14415

**Comment by Prakharsvnit** [comment]
Hi,
I've installed owncloud on my local machine following instructions [here.](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-owncloud-on-ubuntu-16-04).

I couldn't understand what all links(webdav, permalinks)  want to copy on clipboard.

Please help me in getting started.

**Comment by vedularaghu** [comment]
Hi, Is the issue still open?
