### ISSUE TITLE
Video preview (transcoded mp4) in the thumbnails folder

### ISSUE THREAD

**Issue by lenz1111** [owncloud/core#24480]
### Steps to reproduce

When you uploaded a video in large resolution (4K for example) - video player will not play it smoothly (especially on slow internet connection) - due to the size of video. Similar problem is when your movie is in the format not supported by browsers.
### Expected behaviour

We can transcode uploaded movies to smaller size and the correct format and save it in the thumbnails folder (we have to do it async in the background process) then the video player will be playing transcoded video (if available, else original video).

Proposition for transcoding movie (when: `'enable_movie_transcode' => true` is enabled in the config file) that should work with ffmpeg and avconv:

https://github.com/lenz1111/core/compare/master...lenz1111:video_transcode

This is example of using preview video in files_videoplayer:

https://github.com/lenz1111/files_videoplayer/compare/master...lenz1111:video_transcode

All should work on owncloud 9.0.

This is just my proposition...

**Comment by lenz1111** [comment]
@davitol Try again - I fixed my code:
1. set in config.php:
```
'preview_max_x' => 640,
'preview_max_y' => 640,
'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Movie',
    1 => 'OC\\Preview\\Image',
  ),
  'enable_movie_transcode' => true,
```
(enable preview and set size of preview video)
2. Make sure you have working _ffmpeg_ / _avconv_ in your system (recommended _ffmpeg_)
3. Upload video - after upload _ffmpeg_ should start in background and then it should create file preview.mp4 in thumbnails/ folder
4. If file preview.mp4 exists - files_videoplayer should use it for preview

Patch:
Tested with current owncloud/master owncloud/files_videoplayer/master 
[video_trancode_patch.zip](https://github.com/owncloud/core/files/272641/video_trancode_patch.zip)

Try it

**Comment by davitol** [comment]
@lenz1111 @PVince81 :+1: Following the steps writen in your comment https://github.com/owncloud/core/issues/24480#issuecomment-220325060 it WFM :clap:

**Comment by felixboehm** [comment]
https://github.com/owncloud/ios/issues/787

**Comment by butonic** [comment]
patch might need some polish otherwise pretty cool. we could move the preview generation to a background job...
