### ISSUE TITLE
Make "Enable Encryption" checkbox toggle

### ISSUE THREAD

**Issue by JonasDralle** [owncloud/core#24485]
Make the "encrypt" Button toggle so i can flick encryption on/off
or (the lazy method) add a link to the doc that explains me how to disable encryption. It's not obvious to the end user that he/she has to disable the plugin instead of the checkbox even tho it's a checkbox and it implies to be toogled to enable/disable.

* * *

### Steps to reproduce
log in as admin and go to the encryption settings (_/owncloud/index.php/settings/admin#encryptionAPI_)

### Expected behaviour
Here I can enable/disable encryption and change/delete the recovery key

### Actual behaviour
"Enable"-Button is grayed out and not usable

Why should I know that I need to disable the plugin to decrypt all files serverwide?

please add an label that explains to me how do disable (link do doc maybe?)
or even better: give me an option to toggle encryption

you have a checkbox but i cannot use it like an checkbox. This is confusing

### Server configuration

**ownCloud version:** 8.2.2

**Are you using external storage, if yes which one:** buildin SATA harddrive

**Comment by PVince81** [comment]
@schiesbn

**Comment by JonasDralle** [comment]
thank you for considering this

**Comment by DeepDiver1975** [comment]
This behavior was implemented on purpose - once enabled it is not possible to disable encryption without risking data loss due to corruption because encrypted files will not longer be detected.

Adding doc links might be helpful

**Comment by JonasDralle** [comment]
why don't you decrypt everything instead of losing it? It's not like i am adding or removing remote servers all day

**Comment by DeepDiver1975** [comment]
> why don't you decrypt everything instead of losing it?

Decrypting all files for all users can take forever - we might run into timeouts via the web which is bad.
Furthermore some external storages you have configured might be temporarily not available which will possible result is corruption as well.

**Comment by JonasDralle** [comment]
yea ok i see your point
please mark this issue as closed as soon as the documentation link is added

have a good day and thanks for the info

**Comment by DeepDiver1975** [comment]
Looking at ownCloud 9 and 9.1 from my point of view there is enough documentation added

![bildschirmfoto von 2016-06-21 11-00-45](https://cloud.githubusercontent.com/assets/1005065/16223819/85c0f9b0-379f-11e6-8214-2159c1a5ed23.png)

The ``i`` icon points over to https://doc.owncloud.org/server/9.1/admin_manual/configuration_files/encryption_configuration.html
