### ISSUE TITLE
no (proper) indication if a process runs out-of-memory

### ISSUE THREAD

**Issue by h-2** [owncloud/core#24481]
### Steps to reproduce
1. misconfigure your swap or otherwise be low on RAM
2. have your cron-job or or on-demand updater crash because of out-of-ram
3. not have your files updated ever again
### Expected behaviour

Owncloud should give some indication somewhere that something went wrong.
### Actual behaviour

No indication of any unexpected behaviour. Nothing in the owncloud log and nothing in the web-server log.
### Server configuration

**Operating system**: FreeBSD 

**Web server:** lighttpd

**Database:** postgres

**PHP version:** 5.6.20

**ownCloud version:** 9.0.1 (stable)

**Updated from an older ownCloud or fresh install:** updated 

**Where did you install ownCloud from:** packages

**Comment by DeepDiver1975** [comment]
Generally speaking out of memory exceptions are written to the log.

**Comment by rullzer** [comment]
I think this is more of a setup issue. PHP should log that it ran out of memory (with a stack trace). ownCloud itself does not know this info since the moment the exception occurs php will shutdown and not throw a nice exception.

**Comment by nickvergessen** [comment]
Also note, for cron we did some improvements in the last maintenance releases. 8.1.x-9.0.y

**Comment by PVince81** [comment]
I don't think there is much we can do here. PHP is supposed to log an error message already and I've seen it do so. Maybe there are some rare situations in which it is not able to.
