### ISSUE TITLE
Fully automated grant process to access dropbox and google drive external storages

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#24496]
At the moment, user interaction is required to grant access to those storages (clicking the "grant access" button when setting up the storage).

In order to test these two storages automatically, we need this process to be fully automatic, without any user interaction.

Preparing the test account and getting the client ID and secret will be done in advance.

@PVince81 @DeepDiver1975 @cmonteroluque I'd like this to be in 9.1 but I think this is too complex to be in with the time we have, so probably better to have it for 9.2

**Comment by PVince81** [comment]
@jvillafanez if you have a way to get the token outside of ownCloud, it might be possible to set that token directly to the config using OCC:

**Comment by PVince81** [comment]
@jvillafanez did you gain new insights about this while looking into GDrive stuff ?

**Comment by jvillafanez** [comment]
I'm not sure if this will be possible.

I've been researching about service accounts, but it doesn't seem we can use them for this purpose. I think by default, the service account will have its own gdrive storage so it won't be able to read the storage for the user. The other option would be to grant the domain-wide authority to the service account to be able to impersonate users in the domain, but I'm not sure what are the requirements and it doesn't seem I can set it up properly.

Anyway, in the best scenario, we'll likely need to change the configuration for the mount to ask for the configuration file for the service account (it can't be set up with client_id + client_secret).

**Comment by PVince81** [comment]
Likely not possible. Could be researched as part of these apps individually.
