### ISSUE TITLE
Auto-repair ghost files

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24499]
In some bug situations, it can happen that a file was removed from storage but the filecache still contains it. In such situations, it is impossible for the user to delete the file while it still appears in the web UI and Webdav.

One solution is usually running `occ files:scan`.

However, it would be good if ownCloud could detect this situation and auto-clean the bogus entry.
To detect this:
- whenever accessing/deleting a file that is in the file cache but file operation returns "not found"

@icewind1991

**Comment by DeepDiver1975** [comment]
> whenever accessing/deleting a file that is in the file cache but file operation returns "not found"

but we have to be careful with temporal scenarios ...

**Comment by PVince81** [comment]
> but we have to be careful with temporal scenarios ...

Indeed, maybe call `file_exists` again on that file to verify that it is indeed gone. (for example after a failed fopen)

**Comment by rullzer** [comment]
I get it... but this 'could' open up a can of worms. If a mountpoint is not there (user mounting external disk as their data dir for example) a sync from the client might delete all entries... and with it all shares/comments etc.

Wouldn't it be better to allow deletion of not found files? But a get would return a temp not available?

**Comment by PVince81** [comment]
Fixed by https://github.com/owncloud/core/pull/24813 by detecting a failed deletion and then calling `file_exists` to double check.
