### ISSUE TITLE
occ command to clear all locks

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24494]
In some OC versions like OC < 9.0.2 in can happen that the database contains stray locks due to bugs.

We should write a repair step that clears these stray locks at update time.

@icewind1991 let's do this in the hardening phase of 9.1

CC @cmonteroluque

**Comment by RealRancor** [comment]
Fixes https://github.com/owncloud/core/issues/21360

**Comment by simsala** [comment]
Still happening in version 9.0.2.
Lock table just keeps on growing and is never cleared.

**Comment by simsala** [comment]
Related to https://github.com/owncloud/core/issues/20380 and https://github.com/owncloud/core/issues/24507
Seeing both effects on my 9.0.2.
Details here and config can be found here:https://github.com/owncloud/core/issues/20380

So this is affecting OC ≤ 9.0.2.

**Comment by PVince81** [comment]
@icewind1991 please have a look why there are still stray locks

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/25064

**Comment by PVince81** [comment]
Closing due to https://github.com/owncloud/core/pull/25064#issuecomment-225500270

The TTL should already take care of this.
If the TTL doesn't work it's a different issue, there are already otherreports of stray locks staying longer than necessary.

**Comment by mdonges** [comment]
is it possible to trigger the repair step manually?

e.g via a new feature as 
occ files:release-stary-locks

or ist there already an existing way?

I updated my instance to 9.1.4 but still could not get rid of the locks....

**Comment by PVince81** [comment]
An occ command is a good idea.

But a lock cannot be detected as stray as long as its timeout hasn't been reached.
So the command would rather clear ALL locks and should be run in maintenance mode to avoid disrupting transfers that might be in progress.
