### ISSUE TITLE
Integrity Check: Skeleton folder should be excluded by default

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#24519]
Not all my friends like squirrels, so I removed` Squirrel.jpg` from the default skeleton folder.

### Steps to reproduce
1. delete `core/skeleton/Photos/Squirrel.jpg`

### Expected behaviour
Skeleton folder should be excluded by default

### Actual behaviour
ownCloud complains about missing Squirrel.jpg

![admin_-_owncloud](https://cloud.githubusercontent.com/assets/214010/15120275/4064652e-1615-11e6-811e-ff1fec52d3fd.png)

### Server configuration
**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.2 (stable)

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
https://download.owncloud.org/community/owncloud-9.0.2.zip

**Signing status (ownCloud 9.0 and above):**

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- FILE_MISSING
		- core/skeleton/Photos/Squirrel.jpg

Raw output
==========
Array
(
    [core] => Array
        (
            [FILE_MISSING] => Array
                (
                    [core/skeleton/Photos/Squirrel.jpg] => Array
                        (
                            [expected] => 11e1baf404f0d2a1548337715e7904289ff51010438c1cdabcf6b0e34b8536af4b6e3cb3bca59be38022c70a5f3420eab4c25c4e9ca645f7527e1f6fca8202c8
                            [current] => 
                        )

                )

        )

)
```

**List of activated apps:**

```
php occ app:list
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
php occ config:list system
{
    "system": {
        "instanceid": "ocje0ie8com7",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mst.works"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "9.0.2.2",
        "logtimezone": "UTC",
        "installed": true
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome 50

**Operating system:**
Mac OS X 10.11.4

@LukasReschke Could this be set as default for https://github.com/owncloud/core/issues/23186 ? /cc @MorrisJobke 

00005431

**Comment by LukasReschke** [comment]
No. It should not. They should configure a custom skeleton folder, check the config file...

**Comment by LukasReschke** [comment]
Check https://github.com/owncloud/core/blob/master/config/config.sample.php#L197-202

**Comment by michaelstingl** [comment]
@LukasReschke Thanks!

**Comment by bobblkabb** [comment]
skeletondirectory setting in config.php doesn't work for me:

'skeletondirectory' => '', [actually I don't want any 'skeletons' for new users]
'skeletondirectory' => '/media/usb/skeleton' [an empty folder]
