### ISSUE TITLE
Duplicate entries in language selector

### ISSUE THREAD

**Issue by knutschneider** [owncloud/core#24536]
### Steps to reproduce
1. Open /index.php/settings/personal
2. If German is selected, there are many duplicate entries
3. See screenshot

### Server configuration
**ownCloud version:** (see ownCloud admin page)
9.0.1

![img](https://cloud.githubusercontent.com/assets/19285963/15146302/ddf01374-16ba-11e6-8f71-b6642fd5a086.png)

**Comment by Xenopathic** [comment]
Confirmed. Slightly concerningly, despite the display name being the same, each option is actually a different language...

**Comment by nickvergessen** [comment]
I'll have a look tomorrow
