### ISSUE TITLE
[8.2.2] Share by link expiration time exceeded

### ISSUE THREAD

**Issue by NadirRoGue** [owncloud/core#24533]
When creating a share by link close to midnight (00:00), some users have reported problems with the expiration date even when they do not set it, in other words, they let the client set the default expiration date to the server's config maximun period. The server answered the expiration date exceeded the max allowed time. After a small investigation, we discover this problem is caused by missmatches between user's computer clock and server's clock. The ideal approach would be, in case the user does not especify an expiration date, to use the request time on the server to avoid this conflict.

**Comment by PVince81** [comment]
@rullzer

**Comment by rullzer** [comment]
People should be asleep at that time ;)

I see the issue. But I'm not entirely sure how to fix it yet. Without creating an API nightmare. I'll think about this.

**Comment by rullzer** [comment]
@NadirRoGue 9.0 handles this already a bit better. And all fixes will go against 9.0...

**Comment by PVince81** [comment]
Please try again with OC 9.0.6 or later and reopen if the problem persists
