### ISSUE TITLE
cant disable federated cloud after update to 8.2.4

### ISSUE THREAD

**Issue by pandorra2** [owncloud/core#24547]
hi,
ive updated from 8.2.3 to 8.2.4, stable channel. update succeeded and everything is fine except federated shares... it has been activated during update and now i cant disable it anymore. unchecking the two options, reload the page, and theyre checked again...
someone able to reproduce?

**Comment by PVince81** [comment]
Indeed! It seems to be a UI bug.

If you check `select * from oc_appconfig where configkey like '%server2server%';` you'll see that they are correctly disabled. For some reason the UI doesn't correctly show that state.

@rullzer @schiesbn

**Comment by PVince81** [comment]
Seems to work fine in 9.0.2.

**Comment by pandorra2** [comment]
@PVince81 
don't want to tell you wrong but doesn't seem to be just a UI bug - in every albums top right corner i can add the album to another dropbox. haven't tried to do so though, but at least the function is shown. therefore it's at least not just an admins UI bug but at two locations ;)

wished i could report for 9.x also but can't update

**Comment by PVince81** [comment]
@pandorra2 have you tried `select * from oc_appconfig where configkey like '%server2server%';` ?

>  to another dropbox

Can you clarify ? What album ? Are you talking about the gallery app ?

**Comment by pandorra2** [comment]
oh, typo - another owncloud of course! federated shares...

and yes, only within the gallery app. "fixed" it with CSS meanwhile:

#save-button {
    display: none;
}

**Comment by PVince81** [comment]
This is the breaking PR https://github.com/owncloud/core/pull/23505

And this PR would fix it: https://github.com/owncloud/core/pull/24656
