### ISSUE TITLE
no entry in "Contact birthdays" after Upgrade

### ISSUE THREAD

**Issue by Pablo1978** [owncloud/core#24553]
Hello....

I missed Entry in my calendars "Contact birthdays" after Upgrade. My OC Upgrade Path: 8.2.3 > 9.0.0 > 9.0.1.3 > 9.0.2 . My Contacts (App: Contacts 1.2.0.0) have got Birthday entry but i don`t see it on my calendar.

**What i have do it before that i create this post:**
1. www-data@raspi:~/owncloud$ ./occ dav:sync-birthday-calendar
..Start birthday calendar sync for all users ...
4 [====================]
ps. i have only 4 users

Result: anymore no entry on my calendar

**Comment by DeepDiver1975** [comment]
Can you please export the contacts who has the birthday set?
You can wipe sensitive data of course.

Do you see the birthday in and other carddav client?

**Comment by Pablo1978** [comment]
on my iPhone and other iOS-Device i see the Birthday from my contacts.
On the OC-Database the Birthday Entry present: example: "BDAY:1982-03-29".

> Can you please export the contacts who has the birthday set?
> You can wipe sensitive data of course.
Do you want i export a Contact and reimport that contact...?

**Comment by Pablo1978** [comment]
The Issue can Closed - Thank you, Thomas
