### ISSUE TITLE
files:transfer-ownership command could be extended to allow per file and directory transfer

### ISSUE THREAD

**Issue by agamez** [owncloud/core#24579]
Right now it's only possible to transfer all the files a user owns, but sometimes it's useful to change only a directory.

For example, in a company environment, someone may be the manager of some project and hereby own a shared work folder with the name of this project. If this project management is passed to a coworker, and maybe the original owner of the directory is even removed from this project at all, ownership of this directory should be passed to the new person in charge.

**Comment by PVince81** [comment]
Implemented here https://github.com/owncloud/core/pull/27343 and available since OC 10.0
