### ISSUE TITLE
Inconsistent results: userExists vs checkPassword

### ISSUE THREAD

**Issue by llvilanova** [owncloud/core#24581]
Hi! I'm using the debian packages you provide for OC 9.0.2-1.1, and enabled the "bookmarks" and "user_ldap" applications that ship with it.

I've discovered the inconsistency through bookmark's REST API, but it should be independent of that app.

The problem: when bookmark's `returnAsJson` calls `userExists($user)` for my already logged-in user, it returns false. If I instead use `checkPassword($user, $password)` it works correctly.

So it clearly sounds like an inconsistency to me.

Thanks!

**Comment by Xenopathic** [comment]
Is this an issue report, a feature request or what? Please fill in the issue template if it is the former.

**Comment by llvilanova** [comment]
### Steps to reproduce

1. Install & configure the `bookmarks` and `user_ldap` apps.
2. Log in to the webpage with user `name` (so `user_ldap` is working).
3. python -c 'import requests ; print requests.get("https://system/owncloud/apps/bookmarks/public/rest/v1/bookmark", params={"user":"name", "password":"pass"}).content'

### Expected behaviour

Get a list of the user's bookmarks.

### Actual behaviour

The request has this content: `{"status":"error","message":"User could not be identified"}`

Function `returnAsJson` in file `/apps/bookmarks/controller/rest/publiccontroller.php` raises the error message after a call to `userExists($user)`. If I replace that with a call to `checkPassword($user, $password)` (used later in the same function) the user is authenticated successfully.

This seems to me like `userExists` is erroneously returning false. This is why I did not report it in bookmark's repository, if you think this is an issue with bookmark, tell me an I'll forward this issue to them.

### Server configuration
**Operating system**: Debian stable

**Web server:** Apache 2.4.10-10+deb8u4

**Database:** None configured (owncloud's default sqlite)

**PHP version:** 5.6.20+dfsg-0+deb8u1

**ownCloud version:** 9.0.2-1.1

**Updated from an older ownCloud or fresh install:** Updated from debian's stable version (7.0.4+dfsg-4~deb8u4), but your package is installed on a separate directory and did not reuse the existing database.

**Where did you install ownCloud from:**  your debian repository

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - bookmarks: true
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - galleryplus: 15.0.0
  - music: 0.3.11
  - news: 8.7.5
  - notifications: 0.2.3
  - ojsxc: 3.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0

Disabled:
  - encryption
  - external
  - files_external
  - user_external

**The content of config/config.php:**

<pre>
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocv335tvcv3r",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "system"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/system\/owncloud",
        "dbtype": "sqlite3",
        "version": "9.0.2.2",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "root",
        "mail_domain": "heygate.gso.ac.upc.edu",
        "ldapIgnoreNamingRules": false,
        "loglevel": 2
    }
}
</pre>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)

<pre>
+-------------------------------+---------------------------------------------+
| Configuration                 |                                             |
+-------------------------------+---------------------------------------------+
| hasMemberOfFilterSupport      |                                             |
| hasPagedResultSupport         |                                             |
| homeFolderNamingRule          |                                             |
| lastJpegPhotoLookup           | 0                                           |
| ldapAgentName                 |                                             |
| ldapAgentPassword             | ***                                         |
| ldapAttributesForGroupSearch  |                                             |
| ldapAttributesForUserSearch   |                                             |
| ldapBackupHost                |                                             |
| ldapBackupPort                |                                             |
| ldapBase                      | dc=system                  |
| ldapBaseGroups                | ou=Groups,dc=system        |
| ldapBaseUsers                 | ou=People,dc=system        |
| ldapCacheTTL                  | 600                                         |
| ldapConfigurationActive       | 1                                           |
| ldapDynamicGroupMemberURL     |                                             |
| ldapEmailAttribute            |                                             |
| ldapExperiencedAdmin          | 0                                           |
| ldapExpertUUIDGroupAttr       |                                             |
| ldapExpertUUIDUserAttr        |                                             |
| ldapExpertUsernameAttr        |                                             |
| ldapGroupDisplayName          | cn                                          |
| ldapGroupFilter               | (&(|(objectclass=groupType)))               |
| ldapGroupFilterGroups         |                                             |
| ldapGroupFilterMode           | 0                                           |
| ldapGroupFilterObjectclass    | groupType                                   |
| ldapGroupMemberAssocAttr      | uniqueMember                                |
| ldapHost                      | ldap                         |
| ldapIgnoreNamingRules         |                                             |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                             |
| ldapLoginFilterEmail          | 0                                           |
| ldapLoginFilterMode           | 0                                           |
| ldapLoginFilterUsername       | 1                                           |
| ldapNestedGroups              | 0                                           |
| ldapOverrideMainServer        |                                             |
| ldapPagingSize                | 500                                         |
| ldapPort                      | 389                                         |
| ldapQuotaAttribute            |                                             |
| ldapQuotaDefault              |                                             |
| ldapTLS                       | 0                                           |
| ldapUserDisplayName           | cn                                          |
| ldapUserDisplayName2          |                                             |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))              |
| ldapUserFilterGroups          |                                             |
| ldapUserFilterMode            | 0                                           |
| ldapUserFilterObjectclass     | inetOrgPerson                               |
| ldapUuidGroupAttribute        | auto                                        |
| ldapUuidUserAttribute         | auto                                        |
| turnOffCertCheck              | 0                                           |
| useMemberOfToDetectMembership | 1                                           |
+-------------------------------+---------------------------------------------+
</pre>

### Client configuration
**Browser:** Epiphany 3.20.1-2

**Operating system:** Debian testing

### Logs
#### Web server error log

none

#### ownCloud log (data/owncloud.log)

<pre>
{"reqId":"60eOXFC69a7YW6p4RIvP","remoteAddr":"...","app":"user_ldap","message":"No DN found for  on ldap","level":0,"time":"2016-05-11T19:34:14+00:00","method":"GET","url":"\/owncloud\/apps\/bookmarks\/public\/rest\/v1\/bookmark?user=name","user":"--"}
{"reqId":"60eOXFC69a7YW6p4RIvP","remoteAddr":"...","app":"user_ldap","message":"No DN found for name on ldap","level":0,"time":"2016-05-11T19:34:14+00:00","method":"GET","url":"\/owncloud\/apps\/bookmarks\/public\/rest\/v1\/bookmark?user=name","user":"--"}
</pre>

#### Browser log

none

**Comment by Xenopathic** [comment]
I'm guessing this happens with LDAP users? Does it also happen with a local DB user?

cc @owncloud/ldap Looks like `userExists()` isn't working properly?

**Comment by blizzz** [comment]
userExists() expects a username as parameter, checkPassword however a login name. checkPassword returns you the username on successful login.

**Comment by llvilanova** [comment]
@Xenopathic: yes it happens for ldap users, but not for my "admin" user created right after the installation (supposedly stored on OC's database).

@blizz: Looking at the users list as an admin, I see the username is a random string for LDAP users, while it's the loginname for the manually added user after installation. Isn't it inconsistent to accept different things for `userExists` and `checkPassword`, or to use a random username in `user_ldap`?

**Comment by blizzz** [comment]
> Looking at the users list as an admin, I see the username is a random string for LDAP users

You're probably seeing the UUID.

> while it's the loginname for the manually added user after installation.

I insist, this is the username. See below.

> Isn't it inconsistent to accept different things for userExists and checkPassword, or to use a random username in user_ldap?

No. There can be different loginnames with LDAP. For local users the login name is case insensitive. The username is always fixed.

**Comment by llvilanova** [comment]
> > while it's the loginname for the manually added user after installation.

> I insist, this is the username. See below.

Yes, I get that. What I mean is that for LDAP the username is a UUID, while for "native" users, the username is the same as the loginname. That's what seems inconsistent to me.

If that is still considered as the intended behavior, I'll forward this as a bug to the bookmarks app.

**Comment by blizzz** [comment]
> Yes, I get that. What I mean is that for LDAP the username is a UUID, while for "native" users, the username is the same as the loginname. That's what seems inconsistent to me.

This is not correct. As explained in https://github.com/owncloud/core/issues/24581#issuecomment-218896840, a local user with username "luis" has following valid loginnames:

* luis
* Luis
* lUis
* luIs
* luiS
* LUis
* LuIs
* LuiS
* lUIs
* lUiS
* luIS
* LUIs
* LUiS
* LuIS
* lUIS

and in future also the email address, if set.

Then, what the username of the LDAP user is created of is by default the UUID, however this is also configurable (see documentation).

> If that is still considered as the intended behavior, I'll forward this as a bug to the bookmarks app.

Yes, please open a bug report there. I close it here therefore.
