### ISSUE TITLE
Weird field names for contacts

### ISSUE THREAD

**Issue by ngrundmann** [owncloud/core#24584]
### Steps to reproduce
1. Synchronize contacts in "Contacts" on OS X

### Expected behaviour
Field names should be human readable like "Work, Home, Mobile Phone"

### Actual behaviour
Shows field names like "HOME,PREF or WORK,VOICE\ or INTERNET,HOME"

### Server configuration
**Operating system:** Debian 8.4

**Web server:** Apache 2.4.10

**Database:** MySQL

**PHP version:** 5.6.20

**ownCloud version:** 9.0.2

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** owncloud.org

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_antivirus: 0.8.0.1
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - passwordpolicy: 1.1
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari

**Operating system:** OS X 10.11.4

I don't know if this is related to Apple or ownCloud. I have a ticket opened at Apple regarding the sync of more than one address book on OS X and told my supporter this problem already. But I wanted to know if someone can tell me where this problem might be.

**Comment by DeepDiver1975** [comment]
Where did you create the contact?

**Comment by ngrundmann** [comment]
When I create the contact on OS X the label is right at least for a phone number. (label "private" in "contacts" and label "home" in ownCloud). When I add an e-mail address with the label "private" on OS X, ownCloud calls it "internet home" that might be okay too.
When I add a phone number and an e-mail address (both label "Home") in ownCloud all other phone numbers and e-mail address are called "HOME,VOICE,pref", "HOME,VOICE" or "INTERNET,HOME" on OS X. Except the e-mail address I added via ownCloud. This one is called "Privat" on OS X like it should be.

**Comment by GMTA** [comment]
Another easy way to reproduce this:
# Sync contacts to iOS 10 (iPhone, iPad, etc.)
# Add phone or email field with "home" or "work" designation
# Edit the contact in the OwnCloud tasks app: change the label to something else
# Sync the contact back to iOS

**Comment by DeepDiver1975** [comment]
this has to be reopened in the contacts repo https://github.com/owncloud/contacts - THX
