### ISSUE TITLE
Federation of 2 x OC 9.02 servers incl. self signed certificate - fails

### ISSUE THREAD

**Issue by hitam4450** [owncloud/core#24583]
### Steps to reproduce
1. setup 2 Oc instances
2. add the address of one OC server into the field for trusted servers (incl. self-signed certificate)
3. results in the following error message:

![oc902_federation](https://cloud.githubusercontent.com/assets/9738727/15189158/91ac8944-17a9-11e6-9658-3bea829112e7.png)
### Expected behaviour

Tell us what should happen
The servers should trust each other
### Actual behaviour

Tell us what happens instead
The do not trust each other
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
Both servers ru 9.0.2 (latest version and build)
**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
You might need to import the self-signed certs like described here:

https://doc.owncloud.org/server/9.0/admin_manual/configuration_files/external_storage_configuration_gui.html#using-self-signed-certificates

Looks to me like something for the documentation of federated sharing

**Comment by MorrisJobke** [comment]
cc @schiesbn @LukasReschke

**Comment by PVince81** [comment]
Is this still an issue ?

**Comment by PVince81** [comment]
Closing due to lack of feedback. Please make sure you imported the self-signed certs.
