### ISSUE TITLE
CalDAV: Moving single Event from recurring Events results in duplicated Event

### ISSUE THREAD

**Issue by waybackrider** [owncloud/core#24591]
### Steps to reproduce
1. Create Calendar in Owncloud an connect this by CalDAV to Thunderbird/Lightning (but can also be reproduced on Android using DAVdroid)
2. Create an Recurring Event in Lightning (e.g. recurring every second day)
3. Sync to Owncloud -> everything is fine
4. Move one of the Events one Day forward (e.g by drag and drop)
5. Sync to Owncloud -> A new Event is created but the old stayed in the Owncloud Calendar

### Expected behaviour
The moved Event should be moved to the new Place

### Actual behaviour
A new Event in created (it's ok so far), but the old one is not getting deleted. The old one also seems to get touched by CalDAV because ist recurrance Settings are removed. Lightning Calendar also shows properly so Owncloud and Lightning are out of sync right now.

### Server configuration
**Operating system**:
Raspbian Jessie / Kernel 4.4.9
**Web server:**
Apache 2.4.10
**Database:**
MySQL 5.5.44
**PHP version:**
PHP 5.6.20
**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.2 (stable)
**Updated from an older ownCloud or fresh install:**
fresh install
**Where did you install ownCloud from:**
download.owncloud.org

**List of activated apps:**
Calendar,
Addressbook

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 46
**Operating system:**
Win10

**Comment by DeepDiver1975** [comment]
@georgehrke mind taking a look?

I guess this more an issue of the calendar app .... THX

**Comment by georgehrke** [comment]
Bug is reproducible,
sample data:
```
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20160530T122157Z
LAST-MODIFIED:20160530T122304Z
DTSTAMP:20160530T122304Z
UID:2769ad98-4cc3-e448-947a-12a10098beb2
SUMMARY:Test
RRULE:FREQ=WEEKLY
DTSTART;TZID=Europe/Berlin:20160511T150000
DTEND;TZID=Europe/Berlin:20160511T160000
TRANSP:OPAQUE
X-MOZ-GENERATION:1
END:VEVENT
BEGIN:VEVENT
CREATED:20160530T122222Z
LAST-MODIFIED:20160530T122304Z
DTSTAMP:20160530T122304Z
UID:2769ad98-4cc3-e448-947a-12a10098beb2
SUMMARY:Test
RECURRENCE-ID;TZID=Europe/Berlin:20160525T150000
DTSTART;TZID=Europe/Berlin:20160526T150000
DTEND;TZID=Europe/Berlin:20160526T160000
SEQUENCE:1
TRANSP:OPAQUE
X-MOZ-GENERATION:1
END:VEVENT
END:VCALENDAR
```

The first `VEVENT` block doesn't contain any `EXDATE` which I think is necessary.
Anyway, this is not a bug in core. if anything, this is a bug in the calendar, so let's move it there.

**Comment by georgehrke** [comment]
Issue in calendar repo: https://github.com/owncloud/calendar/issues/562

**Comment by DeepDiver1975** [comment]
> Issue in calendar repo: owncloud/calendar#562

thx
