### ISSUE TITLE
Search bar (Users) malfunction

### ISSUE THREAD

**Issue by crysman** [owncloud/core#24598]
Search bar does IMHO a bad job in searching, because it uses an **input**\* mask (string%) whereas I think ***_input**_\* (%string%) would be more useful - that is to be able to search less precisely and not requiring the input from the very beginning.
### Steps to reproduce
1. go to Users admin panel as an admin account
2. having an user "Myfavourite" try to search for "favourite"
### Expected behaviour

The user "Myfavourite" is found.
### Actual behaviour

It is not found.
### Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 5.5.x

**ownCloud version:** (see ownCloud admin page) latest 8.x available

**Updated from an older ownCloud or fresh install:** updated

Related issue: https://github.com/owncloud/core/issues/24595

**Comment by PVince81** [comment]
@georgehrke @MTRichards @blizzz

**Comment by blizzz** [comment]
I think we had it once like this (Didn't recheck the code now). Otherwise there are performance costs when starting with an asterisk.

In LDAP we allow the user to prepend the asterisk to achieve such behavior.

**Comment by MTRichards** [comment]
If I recall, as @blizzz said this became a problem with scale. For very large user searches this took minutes to respond, which destroyed the experience of sharing.

**Comment by crysman** [comment]
Understand.

So is there an official possibility to put in the mask explicitely? I've tried % and it works (which is what I need) - is this a sustainable solution or just a coincidence of having correct version? Please, maintain it. 

And secondly, I think having a help HTML "title" attribute which would inform users about the possibility of including the % metacharacter would be good to have. What do you think?

**Comment by PVince81** [comment]
should work now, medial search available for account table.

If the problem persists with 10.0.4 please reopen.
