### ISSUE TITLE
New spinner appears on every picture when previewing it.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#24596]
### Steps to reproduce:
1. Open a picture in the files view and see the preview. 

### Observed behaviour:

<img width="1086" alt="screen shot 2016-05-12 at 11 08 29" src="https://cloud.githubusercontent.com/assets/9048796/15209616/6735cc1e-1832-11e6-8516-5f95d6ec741c.png">

### Expected behaviour:
No spinner on pictures.

**Version**
{"installed":true,"maintenance":false,"version":"9.1.0.1","versionstring":"9.1.0 pre alpha","edition":""}

**Comment by SergioBertolinSG** [comment]
@skjnldsv perhaps?

**Comment by skjnldsv** [comment]
Eheh, hello! :)
I'm taking a look on it in 5min!

**Comment by skjnldsv** [comment]
It's a owncloud/gallery issue. 
See owncloud/gallery#647.

**Comment by SergioBertolinSG** [comment]
Thanks @skjnldsv, fixed on master.
