### ISSUE TITLE
Expose easier job interface in public namespace

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#24611]
This was already discussed for the more specific stuff (TimedJob for example) in https://github.com/owncloud/core/issues/18756

@BernhardPosselt came up with this again and I also got hit by this:

```
20:14 <BernhardPosselt> apart from that OCP\BackgroundJob is also deprecated
20:15 <BernhardPosselt> is this the interface that i need to implement? https://github.com/owncloud/core/blob/master/lib/public/BackgroundJob/IJob.php
20:15 <BernhardPosselt> why do i need to implement all those getters and setters?
20:15 <BernhardPosselt> all other implementations are private
20:16 <BernhardPosselt> the job api is just broken
```

Maybe we want to expose a smaller interface that could then use the abstract class `Job` - https://github.com/owncloud/core/blob/6b5db081a55b9a7675e30a9c43950f412420bcd7/lib/private/BackgroundJob/Job.php

@PVince81 @icewind1991 @DeepDiver1975 What is the plan here?

**Comment by MorrisJobke** [comment]
Maybe also @nickvergessen

**Comment by BernhardPosselt** [comment]
Ah right, thought I added him

**Comment by MorrisJobke** [comment]
Kill this as duplicate of https://github.com/owncloud/core/issues/24609
