### ISSUE TITLE
Update davclient.js and adjust JS files client

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24612]
Update davclient.js to include https://github.com/evert/davclient.js/pull/20

Since the format of the sub-elements changed, this will break folder parsing due to "resourcetype" element.
This will need to be adjusted as well in js/files/client.js

@georgehrke can you take care of this ? I know you'll need the lib update.

Let me know if you need help with the files part.

**Comment by PVince81** [comment]
@georgehrke any update on this ?

We can't update to the latest davclient.js commit because it breaks core due to API result change.
For now had to hard-code the commit to the previous version.

**Comment by georgehrke** [comment]
My suggestion in the davclient repo to revert my change would make this obsolete

**Comment by PVince81** [comment]
PR was reverted, closing
