### ISSUE TITLE
Background job to adjust mimetypes

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24629]
Whenever new mimetypes get added to the list of known ones, a repair step runs during an update to find all existing files that need adjusting.
This approach is unefficient with lots of files.

After discussing in https://github.com/owncloud/core/pull/22875, a new background job needs to be written that can adjust the mime types of files in a running system.

An alternative approach would be to implement this as part of the "occ files:scan --all" command which anyway examines all possibles files. However the latter might be less efficient if there are only a handful of files to adjust.

@mmattel @VicDeo @karlitschek @MorrisJobke @cmonteroluque @DeepDiver1975

**Comment by PVince81** [comment]
It is likely that there won't be enough time to implement this for 9.1.

A quickfix approach might be to reuse the existing repair step for mime types and adjust it to be only runnable from the CLI.
In this case, the following mimetypes need to be added to it:
- https://github.com/owncloud/core/issues/22875
- https://github.com/owncloud/core/issues/24006

But ideal approach would be to have a background job that processes all the files.

**Comment by karlitschek** [comment]
yes. a background job is the way to go. If this is not doable in time then then maybe a cli repair step is fine because it is not super critical if a file doesn't has the right mimetype. better then an exploding oc ;-)

**Comment by cmonteroluque** [comment]
@PVince81 I agree. We can figure out next steps once we're done with the devel schedule for 9.1

**Comment by PVince81** [comment]
@DeepDiver1975 @butonic we haven't added new mimetypes recently, so might not be urgent, but we need to do this eventually.

Backlog ? Note that if at some point we start adding new mimetypes / mimetype fixes again, we'll **have** to do it with the background job approach instead.

**Comment by PVince81** [comment]
no feedback, no time, no volunteers => backlog for now.
