### ISSUE TITLE
Search for file works but doesn`t show whole result in large directories

### ISSUE THREAD

**Issue by vpecinka** [owncloud/core#24623]
### Steps to reproduce
1. in web browser enter directory with many entries (more then loaded by default per view)
2. search for any item (directory or file) within this directory but at the end of listing (not loaded in view yet)
3. the result shows numbers of found items, but they are not visible

### Expected behaviour
You should see the item in result even if you didn`t scroll to the bottom of the page previously.

### Actual behaviour
Probably the directory listing (containing many items) reads and display only part of it and reads the rest only when user scrolls down. If I search for an item from the bottom part of listing, it founds it but doesn`t display. Repeating the search in the same directory (exactly: delete the search keyword and enter it again) shows more and more results. For example: searching pro "z" say that found 9 items, but show only 1 (from top of the listing). Removing "z" from search field and entering "z" again show again found 9 items and displaying 5. Repeating search again show 9 items found and displaying all of them.

It seems there is out of sync search and view :-) If I scroll through whole directory (to load items into view) and search after that, it show whole result.

### Server configuration
**ownCloud version:** 8.2.4.

### Client configuration
**Browser:**  Safari, Firefox
**Operating system:** OSX

#### Browser log
It is empty

**Comment by PVince81** [comment]
Not sure how the search code checks the files in the current list. There are different APIs on the `FileList` class, some that get the files from the visible lists, others that get the whole list. I suspect the search code uses the wrong one.

**Comment by vpecinka** [comment]
Another not working example: go to the directory listing through quick links on the left side, e.g. "Shared with you". In the root view you can search and it works. But if you enter any directory shared with you (Shared with you -> andy directory) and search in it, the file list doesn`t disappear and searching (busy icon) is located below the list... with long listing it looks like no searching is performed, because busy icon is out of view...

**Comment by ChristophWurst** [comment]
dup of https://github.com/owncloud/core/issues/25205?

**Comment by PVince81** [comment]
Yep, dupe
