### ISSUE TITLE
owncloud-deps-php7.0 pulls in unused dependencies

### ISSUE THREAD

**Issue by ebeinroth** [owncloud/core#24624]
I'm trying to install owncloud on debian using the owncloud repository at http://download.owncloud.org/download/repositories/stable/Debian_8.0/. I will be using php7, nginx and pgsql.

When selecting the owncloud-files and owncloud-deps-php7.0 packages, there are many unused dependencies being installed:
- lots of apache packages
- unused client libs for other database servers 

Actual:

The package owncloud-deps-php7.0 depends on libapache2-mod-php7.0, although owncloud can also be used with an alternative httpd and the package allows for the selection of an alternative httpd.

Also, the package pulls in pgsql, mysql and sqlite. I would assume most people only use one type of database, hence it should be enough to have only one of them installed.

Expected:

The package should:
1. include an alternative to libapache2-mod-php7.0 like php7.0-fpm, since libapache2-mod-php7.0 does not work with something like nginx.
2. depend on (psql | mysql | sqlite) and not install all of them

**Comment by PVince81** [comment]
@jnweiger

**Comment by RealRancor** [comment]
This is intended as stated in the documentation:

> owncloud-files is available for the following distributions, but not owncoud-deps. You will have to install your own LAMP stack first. This allows you to create your own custom LAMP stack without dependency conflicts with the ownCloud package.

https://doc.owncloud.org/server/9.0/admin_manual/installation/linux_installation.html

So just use owncloud-files instead.

**Comment by ebeinroth** [comment]
I'm already doing that - but it requires me to have 9 php packages explicitly installed. This feels more like a work around, than a solution.

If we would improve the package as suggested, I would only need to have the owncloud package explicitly installed. All other packages would be dependencies of owncloud.

It's always nice to have a cleaner system.

**Comment by scottalanmiller** [comment]
Package appears to be missing for CentOS  7, as well.

**Comment by Ardakilic** [comment]
+1, I'm using nginx and PHP7 and I don't want to install unrelated apache dependencies, so I'm stuck with manual installation methods. I'd appreciate a way to install it without Apache.

**Comment by RealRancor** [comment]
@Ardakilic Just install owncloud-files which is for users which don't want to run Apache

**Comment by Ardakilic** [comment]
@RealRancor What's the point then? I still have to install and configure every other dependency manually, right ?

**Comment by RealRancor** [comment]
@Ardakilic The point is probably that only Apache is officially supported and that both dependency packages are exactly made for that environment.

**Comment by Ardakilic** [comment]
@RealRancor  Oh I see. I wish there were packages specifically for Nginx, too.

**Comment by RealRancor** [comment]
This is now partly fixed with https://github.com/owncloud/administration/commit/8482c61c54ac3d2021a2eeed71d4fe38cef6e4ad

**Comment by PVince81** [comment]
Is this still an issue ?

cc @crrodriguez

**Comment by crrodriguez** [comment]
already fixed
