### ISSUE TITLE
Language dropdown issues with non-translated titles of languages

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#24639]
For other languages which are not English, this is a glitch I see in the language dropdown – the current language being repeated a bunch of times:
![language list](https://cloud.githubusercontent.com/assets/925062/15268975/d09584d2-19f0-11e6-8589-5ffafd610213.png)
Then at the bottom you have some crazy technical language codes … (which should not be shown like that – we should translate them by hand if needed)
![languagelist](https://cloud.githubusercontent.com/assets/925062/15268976/d096d760-19f0-11e6-9442-7b834896a106.png)

Now with English, you have a lot more languages with language codes, so it seems the above glitch with current language repetition is related:
![languagelist2](https://cloud.githubusercontent.com/assets/925062/15268974/cefc8bfc-19f0-11e6-8318-04bd41962c5d.png)

cc @DeepDiver1975 (we don’t have @owncloud/translation ;)

**Comment by michaelstingl** [comment]
related to https://github.com/owncloud/core/issues/24536 ?

**Comment by DeepDiver1975** [comment]
Yes. Thanks.

**Comment by jancborchardt** [comment]
No it’s not. The issue with the untranslated technical language names still appears. The repeated language name was just a symptom.

Please reopen.

**Comment by DeepDiver1975** [comment]
> No it’s not. The issue with the untranslated technical language names still appears.

As explained already many times - the language names have to be translated by the individual language. If they don't do so there is little we can do.
