### ISSUE TITLE
PHP module GD not installed.

### ISSUE THREAD

**Issue by me88** [owncloud/core#24637]
### Steps to reproduce
1. Ubuntu 16.04 LTS 
2. Install PHP Version 7.0.4-7ubuntu2
3. Install **sudo apt-get install php7.0-gd**
4. Download and unzip owncloud 9.0.2 on /var/www/html/owncloud
5. Go to  'myadress.com'/owncloud

### Expected behaviour
Should be able to install owncloud from scratch.

### Actual behaviour
Get the following message:

```
```
PHP module GD not installed.
Please ask your server administrator to install the module.
PHP modules have been installed, but they are still listed as missing?
Please ask your server administrator to restart the web server.
```

```

### Server configuration
**Operating system**:

**Web server:**
`Linux me-530U3C-530U4C 4.4.0-22-generic #39-Ubuntu SMP Thu May 5 16:53:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Database:**
`mysql  Ver 14.14 Distrib 5.7.12, for Linux (x86_64) using  EditLine wrapper`

**PHP version:**
```
PHP 7.0.4-7ubuntu2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

**ownCloud version:** (see ownCloud admin page)
9.0.2 downloaded from owncloud.org 14may2015 15:00 CET

**Updated from an older ownCloud or fresh install:**
Fresh Install

**Where did you install ownCloud from:**
From owncloud.org

**Comment by thopiekar** [comment]
```sudo apt-get install php7.0-gd``` is not enough.
Now php7 has also a tool called ```phpenmod```, so after installation of the ```gd``` module via APT you'll also need to enable it via ```sudo phpenmod gd```.

At least it worked for me :wink: 

Regards

**Comment by me88** [comment]
I did `sudo phpenmod gd`
I even reboot my machine but it's still not working.

**Comment by me88** [comment]
OK i did a 
sudo apt-get purge php7.0-gd
sudo apt-get install php7.0-gd
sudo phpenmod gd 

Works
Something went probably wrong with the first installation of gd

**Comment by thopiekar** [comment]
Great! I wasn't expecting that there was something wrong :sweat_smile: 

Regards

**Comment by rebroad** [comment]
Why has this been closed? It's still an issue with the latest owncloud - i.e. the documentation does not mention to install php7.0-gd

**Comment by akashsharma32** [comment]
PHP module dom not installed.
Please ask your server administrator to install the module.

PHP module XMLWriter not installed.
Please ask your server administrator to install the module.

PHP module XMLReader not installed.
Please ask your server administrator to install the module.

PHP module libxml not installed.
Please ask your server administrator to install the module.

PHP module SimpleXML not installed.
Please ask your server administrator to install the module.

PHP modules have been installed, but they are still listed as missing?
Please ask your server administrator to restart the web server.


How to resolve this error?

**Comment by sharidas** [comment]
> How to resolve this error?

Based on the distribution, you could try searching for php-xml or so. For instance Ubuntu 18.04 has `php7.2-xml` which when installed should resolve your errors.

**Comment by jose2016** [comment]
Thanks @thopiekar is working
