### ISSUE TITLE
mpm-itk / webdav error after upgrade to 8.2.5

### ISSUE THREAD

**Issue by peewee4711** [owncloud/core#24633]
Today I upgrade from ownCloud 8.2.2 to 8.2.5 using the web interface.
Upgrade proceeded without any errors however all clients stopped working immediately after the upgrade.
There are no errors or anything to indicate major issues in the owncloud.log however my Apache log is getting spammed with the following errors:
[Fri May 13 15:41:16.192538 2016] [mpm_itk:error] [pid 3306] child died with signal 11

### Expected behaviour
I should be able to use ownCloud client as before the upgrade.
I should be able to view files uploaded to ownCloud in the web interface.
I should not be seeing new errors on the ownCloud admin page.

### Actual behaviour
None of my clients are able to connect to ownCloud.

All Files load up as empty using the web interface.

There are no errors or anything to indicate major issues in the owncloud.log however my Apache log is getting spammed with the following errors:
[Fri May 13 15:41:16.192538 2016] [mpm_itk:error] [pid 3306] child died with signal 11

On the ownCloud admin page I get the following error/warning:
Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken.
I assume this error is directly related to the mpm-itk errors I am getting in my Apache error log. If I move my ownCloud installation folder then the errors stop. I am not having any issues with any other web pages hosted using mpm-itk.

### Server configuration
Operating system: Debian Stable
Web server: Apache 2.4.10-10+deb8u4 - mpm-itk
Database: Postgresql
PHP version: 5.6.20+dfsg-0+deb8u1
ownCloud version (see ownCloud admin page): 8.2.5 (stable)
Updated from an older ownCloud or fresh install: Upgrade from 8.2.2
ownCloud log (data/owncloud.log):

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
This seems to just redirect to the Files area.

**List of activated apps:**
Enabled:
  - files: 1.2.1
  - files_pdfviewer: 0.7.1
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_versions: 1.1.0
  - gallery: 14.2.0
  - updater: 0.6

**The content of config/config.php:**
{
    "system": {
        "instanceid": "513141e9a4a43",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/owncloud-data",
        "dbtype": "pgsql",
        "version": "8.2.5.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "forcessl": true,
        "loglevel": 0,
        "trusted_domains": [
            "ssl.mydomain.dk"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "ssl.mydomain.dk",
        "mail_smtpport": "25",
        "mail_from_address": "owncloud",
        "mail_domain": "mydomain.dk"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Mozilla Firefox

**Operating system:**
Debian Testing

#### Web server error log
[Fri May 13 16:57:00.304677 2016] [mpm_itk:error] [pid 10014] child died with signal 11
[Fri May 13 16:57:05.357905 2016] [mpm_itk:error] [pid 10018] child died with signal 11
[Fri May 13 16:57:11.622137 2016] [mpm_itk:error] [pid 10008] child died with signal 11
[Fri May 13 16:57:13.633424 2016] [mpm_itk:error] [pid 10017] child died with signal 11

#### ownCloud log (data/owncloud.log)
Nothing of interest

**Comment by Xenopathic** [comment]
As per the [documentation](https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/performance_tuning/webserver_tips.html), Apache MPM is unsupported since PHP isn't thread-safe, please use prefork instead. Not sure if that's the cause of your problems though.

**Comment by RealRancor** [comment]
@Xenopathic @LukasReschke 

> mpm-itk is based on the traditional prefork MPM, which means it's non-threaded; in short, this means you can run non-thread-aware code (like many PHP extensions) without problems.

from http://mpm-itk.sesse.net/

**Comment by peewee4711** [comment]
Thank you @RealRancor.
I decided to try to upgrade to 9.0.2 and it has solved the issue. No more errors and everything seems to be working right. I do think that it is important that mpm-itk is not disregarded as way to run ownCloud since it is based on prefork but have the ability to run individual vhosts under separate uid and/or gid.

**Comment by chriseqipe** [comment]
We had the same problem on one of our oc intances. The Apache process also died with signal 11. Upgrade to 9.0.2 solved the problem. I investigated the cause and saw that the since oc 8.2.4 goes into an endless recursive loop on certain user group relations crashing the php process....
