### ISSUE TITLE
`occ app:list --output json_pretty` prints invalid JSON

### ISSUE THREAD

**Issue by oswajas** [owncloud/core#24635]
### Steps to reproduce
1. occ maintenance:mode --on
2. occ app:list --output json_pretty
### Expected behaviour

Print only valid json to standard output.
### Actual behaviour

Print "ownCloud is in maintenance mode - no app have been loaded" to standard output before the JSON.
### Server configuration

**ownCloud version:** 8.2.4

**Comment by PVince81** [comment]
I think that error message should be output to stderr instead, it's probably not the case right now.

In case of maintenance mode, not sure why the app list cannot be retrieved. So it should either return nothing at all on stdout (+ error on stderr) or need to find a way to output the app list even when in maintenance mode.

**Comment by noveens** [comment]
@PVince81 ,

I can't seem to find any command in OCC that the "maintenance:mode --on" could affect.
It just seems to be a warning which is being printed.
IMHO we should leave it as is, or never print it at all.

Suggestions are welcome :-)

**Comment by PVince81** [comment]
```
% occ app:list  --output json_pretty
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "enabled": {
        "comments": "0.3.0",
        "dav": "0.2.7",
        "federatedfilesharing": "0.3.0",
        "federation": "0.1.0",
        "files": "1.5.1",
        "files_external": true,
        "files_sharing": "0.10.0",
        "files_trashbin": "0.9.0",
        "files_versions": "1.3.0",
        "provisioning_api": "0.5.0",
        "systemtags": "0.3.0",
        "updatenotification": "0.2.1"
    },
    "disabled": {
        "admin_migrate": null,
        "apptemplate": null,
        "contacts": null,
        "customgroups": null,
        "django_auth": null,
        "emoji": null,
        "encryption": null,
        "encryption_dummy": null,
        "example-theme": null,
        "external": null,
        "files_archive": null,
        "files_odfviewer": null,
        "files_sgfviewer": null,
        "files_svgedit": null,
        "files_videoviewer": null,
        "firstrunwizard": null,
        "fluxx_compensator": null,
        "gallery": null,
        "impress": null,
        "imprint": null,
        "ownpad_lite": null,
        "pong": null,
        "pushnotifications": null,
        "reader": null,
        "search": null,
        "tattoo": null,
        "testing": null,
        "user_external": null,
        "user_ldap": null,
        "user_migrate": null,
        "user_oauth": null,
        "user_openid_provider": null,
        "user_persona": null,
        "user_saml": null,
        "user_vd": null,
        "user_webfinger": null
    }
}
```

This is invalid JSON because of the warning and useless for people who want to script it.

Are you familiar with the difference between stdout and stderr ?

Try redirecting this output to a file: the file will contain the warning.
However if the warning is written to stderr instead of stdout, redirecting the output to a file will only contain the JSON but the warning will still appear on the console.

Not sure how to achieve that with Symfony's command / `$output`. The simplest way is `printf(STDERR, "message\n");`

**Comment by noveens** [comment]
@PVince81 ,

I'm quite familiar with STDERR and STDOUT,

So this bug requires to print the maintenance warning to printed in STDERR.
Is that it?

**Comment by PVince81** [comment]
@noveens yes, as stated in my first comment
