### ISSUE TITLE
Erreur interne du serveur ...

### ISSUE THREAD

**Issue by livier** [owncloud/core#24649]
### Steps to reproduce
1. Maybe I made some mistake : Had problems with contacts app and ...
	Tried to use https://github.com/owncloud/contacts/releases/tag/v0.0.0.63 
	by renaming /apps/contacts and installing the 0.0.0.63 one
Visited apps page of my Owncloud and do not think having activated one, But what should have a random click done, do not thin so but surprise to read about ldap I never used !
2.Trying to load one off my Owncloud page, reproduced on diffrents links to calendar page, contact page, first page ... same thing
3.

### Expected behaviour
Should show the page I expect

### Actual behaviour
Message that say :

Erreur interne du serveur
Le serveur a rencontré une erreur interne et est incapable d'exécuter votre requête.
Veuillez contacter l'administrateur du serveur si cette erreur apparaît plusieurs fois. Veuillez joindre les détails techniques à votre rapport.
Le fichier journal du serveur peut fournir plus de renseignements.
Renseignements techniques
    Adresse distante : 172.97.196.91
    ID de la demande : i5wNqlrl1W39B6gRZ6Fq

### Server configuration
**Operating system**:
Debian 8 uptodate

**Web server:**
Apache 2.4

**Database:**
mariaDB 

**PHP version:**
PHP Version 5.6.20-0+deb8u1

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**
9.0.1-3.1

**Where did you install ownCloud from:**
deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /

**Signing status (ownCloud 9.0 and above):**
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 

Same page as said a few questions ago
```

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

```
same answer as any "php occ" command
www-data@debian:~/owncloud$ php occ app:list
An unhandled exception has been thrown:
exception 'OCP\AutoloadNotAllowedException' with message 'Autoload path not allowed: /var/www/owncloud/apps/user_ldap/user_ldap.php' in /var/www/owncloud/lib/autoloader.php:152
Stack trace:
#0 /var/www/owncloud/lib/autoloader.php(172): OC\Autoloader->isValidPath('/var/www/ownclo...')
#1 [internal function]: OC\Autoloader->load('OCA\\user_ldap\\U...')
#2 /var/www/owncloud/apps/user_cas/lib/ldap_backend_adapter.php(35): spl_autoload_call('OCA\\user_ldap\\U...')
#3 /var/www/owncloud/apps/user_cas/user_cas.php(25): require_once('/var/www/ownclo...')
#4 /var/www/owncloud/apps/user_cas/appinfo/app.php(30): require_once('/var/www/ownclo...')
#5 /var/www/owncloud/lib/private/app.php(163): require_once('/var/www/ownclo...')
#6 /var/www/owncloud/lib/private/app.php(144): OC_App::requireAppFile('user_cas')
#7 /var/www/owncloud/lib/private/app.php(117): OC_App::loadApp('user_cas')
#8 /var/www/owncloud/lib/private/user.php(129): OC_App::loadApps(Array)
#9 /var/www/owncloud/lib/base.php(644): OC_User::setupBackends()
#10 /var/www/owncloud/lib/base.php(1112): OC::init()
#11 /var/www/owncloud/console.php(46): require_once('/var/www/ownclo...')
#12 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#13 {main}www-data@debian:~/owncloud$ 

**The content of config/config.php:**
From the file : 
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'xxxxxxxxxxxxx',
    1 => 'xxxxxxxxxxxxxxxxxx',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'xxxxxxxxxxxxxxxxxxx',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'logtimezone' => 'UTC',
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxxxxxxxxxxxxxxxx',
  'forceSSLforSubdomains' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'xxxxxxxxxxxx',
  'mail_domain' => 'xxxxxxxxxxxxxxxx',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'xxxxxxxxxxxxxxxxxx',
  'mail_smtpname' => 'xxxxxxxxxxxxxxxxxx',
  'mail_smtppassword' => 'xxxxxxxxxxxxx',
  'loglevel' => 2,
  'theme' => '',
  'trashbin_retention_obligation' => 'auto',
  'appstore.experimental.enabled' => true,
  'updatechecker' => false,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No, Not as far as I know 
But what about "ldap" I fin in the error message ?

### Client configuration
**Browser:**
Firefox 46.0

**Operating system:**

#### Web server error log
[Sun May 15 20:53:10.795533 2016] [core:info] [pid 14152] [client 172.97.196.91:15396] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/angular/angular.js
[Sun May 15 20:53:10.823395 2016] [core:info] [pid 21670] [client 172.97.196.91:15400] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/angular-route/angular-route.js
[Sun May 15 20:53:10.980065 2016] [core:info] [pid 21668] [client 172.97.196.91:15384] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/angular-uuid4/angular-uuid4.js
[Sun May 15 20:53:10.999705 2016] [core:info] [pid 23913] [client 172.97.196.91:15399] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/angular-cache/dist/angular-cache.js
[Sun May 15 20:53:11.084931 2016] [core:info] [pid 21669] [client 172.97.196.91:15385] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/vcard/src/vcard.js
[Sun May 15 20:53:11.103266 2016] [core:info] [pid 21668] [client 172.97.196.91:15384] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/public/script.js
[Sun May 15 20:53:11.142949 2016] [core:info] [pid 23913] [client 172.97.196.91:15399] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/angular-bootstrap/ui-bootstrap.min.js
[Sun May 15 20:53:11.179659 2016] [core:info] [pid 23915] [client 172.97.196.91:15395] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js
[Sun May 15 20:53:11.212114 2016] [core:info] [pid 21669] [client 172.97.196.91:15385] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/jquery-timepicker/jquery.ui.timepicker.js
[Sun May 15 20:53:11.448086 2016] [core:info] [pid 14152] [client 172.97.196.91:15396] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/angular-sanitize/angular-sanitize.js
[Sun May 15 20:53:12.253419 2016] [core:info] [pid 28596] [client 172.97.196.91:15402] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/angular/angular.js
[Sun May 15 20:53:12.262960 2016] [core:info] [pid 25091] [client 172.97.196.91:15394] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/ui-select/dist/select.js
[Sun May 15 20:53:12.706172 2016] [core:info] [pid 21670] [client 172.97.196.91:15400] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/angular-route/angular-route.js
[Sun May 15 20:53:12.865319 2016] [core:info] [pid 28596] [client 172.97.196.91:15402] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/angular-uuid4/angular-uuid4.js
[Sun May 15 20:53:13.715753 2016] [core:info] [pid 28596] [client 172.97.196.91:15402] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/angular-cache/dist/angular-cache.js
[Sun May 15 20:53:13.968535 2016] [core:info] [pid 28596] [client 172.97.196.91:15402] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/angular-sanitize/angular-sanitize.js
[Sun May 15 20:53:14.310345 2016] [core:info] [pid 28596] [client 172.97.196.91:15402] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/ui-select/dist/select.js
[Sun May 15 20:53:14.644706 2016] [core:info] [pid 28596] [client 172.97.196.91:15402] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/vcard/src/vcard.js
[Sun May 15 20:53:15.087239 2016] [core:info] [pid 28596] [client 172.97.196.91:15402] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/angular-bootstrap/ui-bootstrap.min.js
[Sun May 15 20:53:15.220366 2016] [core:info] [pid 28596] [client 172.97.196.91:15402] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/angular-bootstrap/ui-bootstrap-tpls.min.js
[Sun May 15 20:53:15.429591 2016] [core:info] [pid 28596] [client 172.97.196.91:15402] AH00128: File does not exist: /var/www/owncloud/apps/contacts/js/vendor/jquery-timepicker/jquery.ui.timepicker.js

#### ownCloud log (data/owncloud.log)
{"reqId":"G88UlF9qiwp+DkmVQ9df","remoteAddr":"172.97.196.91","app":"PHP","message":"OCP\\AutoloadNotAllowedException: Autoload path not allowed: \/var\/www\/owncloud\/apps\/user_ldap\/user_ldap.php at \/var\/www\/owncloud\/lib\/autoloader.php#152","level":3,"time":"2016-05-16T03:29:00+00:00","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"xavier"}
{"reqId":"GfOWSFaOv63pfPqrcE+f","remoteAddr":"172.97.196.91","app":"PHP","message":"OCP\\AutoloadNotAllowedException: Autoload path not allowed: \/var\/www\/owncloud\/apps\/user_ldap\/user_ldap.php at \/var\/www\/owncloud\/lib\/autoloader.php#152","level":3,"time":"2016-05-16T03:29:30+00:00","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"xavier"}
{"reqId":"E8THO9vernOsDspRv1n6","remoteAddr":"172.97.196.91","app":"PHP","message":"OCP\\AutoloadNotAllowedException: Autoload path not allowed: \/var\/www\/owncloud\/apps\/user_ldap\/user_ldap.php at \/var\/www\/owncloud\/lib\/autoloader.php#152","level":3,"time":"2016-05-16T03:30:00+00:00","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"xavier"}
{"reqId":"t1w7aUOET2zru7c+D8My","remoteAddr":"172.97.196.91","app":"PHP","message":"OCP\\AutoloadNotAllowedException: Autoload path not allowed: \/var\/www\/owncloud\/apps\/user_ldap\/user_ldap.php at \/var\/www\/owncloud\/lib\/autoloader.php#152","level":3,"time":"2016-05-16T03:30:31+00:00","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"xavier"}
{"reqId":"4jVJ6d4NJH3iiVVp528X","remoteAddr":"172.97.196.91","app":"PHP","message":"OCP\\AutoloadNotAllowedException: Autoload path not allowed: \/var\/www\/owncloud\/apps\/user_ldap\/user_ldap.php at \/var\/www\/owncloud\/lib\/autoloader.php#152","level":3,"time":"2016-05-16T03:31:00+00:00","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"xavier"}
{"reqId":"QWZR63LaOECo6DmljsW0","remoteAddr":"172.97.196.91","app":"PHP","message":"OCP\\AutoloadNotAllowedException: Autoload path not allowed: \/var\/www\/owncloud\/apps\/user_ldap\/user_ldap.php at \/var\/www\/owncloud\/lib\/autoloader.php#152","level":3,"time":"2016-05-16T03:31:30+00:00","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"xavier"}
{"reqId":"ZUrdaEzeAKrbX2WoR0Au","remoteAddr":"172.97.196.91","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php(172): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/ownclo...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\user_ldap\\\\\\\\U...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/lib\\\/ldap_backend_adapter.php(35): spl_autoload_call('OCA\\\\\\\\user_ldap\\\\\\\\U...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/user_cas.php(25): require_once('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/appinfo\\\/app.php(30): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(163): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/
lib\\\/private\\\/app.php(144): OC_App::requireAppFile('user_cas')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(117): OC_App::loadApp('user_cas')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user.php(129): OC_App::loadApps(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(644): OC_User::setupBackends()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(1112): OC::init()\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(37): require_once('\\\/var\\\/www\\\/ownclo...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":152}","level":3,"time":"2016-05-16T03:31:32+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=productivity&includeUpdateInfo=0","user":"xavier"}
{"reqId":"9mP5m8qUTBXguCfhx8gA","remoteAddr":"172.97.196.91","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php(172): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/ownclo...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\user_ldap\\\\\\\\U...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/lib\\\/ldap_backend_adapter.php(35): spl_autoload_call('OCA\\\\\\\\user_ldap\\\\\\\\U...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/user_cas.php(25): require_once('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/appinfo\\\/app.php(30): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(163): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/
lib\\\/private\\\/app.php(144): OC_App::requireAppFile('user_cas')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(117): OC_App::loadApp('user_cas')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user.php(129): OC_App::loadApps(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(644): OC_User::setupBackends()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(1112): OC::init()\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(37): require_once('\\\/var\\\/www\\\/ownclo...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":152}","level":3,"time":"2016-05-16T03:31:32+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/list?category=productivity&includeUpdateInfo=1","user":"xavier"}
{"reqId":"tIXYbX6mh+kI7z\/3Y89D","remoteAddr":"172.97.196.91","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php(172): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/ownclo...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\user_ldap\\\\\\\\U...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/lib\\\/ldap_backend_adapter.php(35): spl_autoload_call('OCA\\\\\\\\user_ldap\\\\\\\\U...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/user_cas.php(25): require_once('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/appinfo\\\/app.php(30): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(163): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/
lib\\\/private\\\/app.php(144): OC_App::requireAppFile('user_cas')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(117): OC_App::loadApp('user_cas')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user.php(129): OC_App::loadApps(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(644): OC_User::setupBackends()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(1112): OC::init()\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(37): require_once('\\\/var\\\/www\\\/ownclo...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":152}","level":3,"time":"2016-05-16T03:31:42+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps?category=productivity","user":"xavier"}
{"reqId":"s83SG8mnpYw5lsQ80Cv6","remoteAddr":"172.97.196.91","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php(172): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/ownclo...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\user_ldap\\\\\\\\U...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/lib\\\/ldap_backend_adapter.php(35): spl_autoload_call('OCA\\\\\\\\user_ldap\\\\\\\\U...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/user_cas.php(25): require_once('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/appinfo\\\/app.php(30): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(163): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/
lib\\\/private\\\/app.php(144): OC_App::requireAppFile('user_cas')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(117): OC_App::loadApp('user_cas')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user.php(129): OC_App::loadApps(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(644): OC_User::setupBackends()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(1112): OC::init()\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(37): require_once('\\\/var\\\/www\\\/ownclo...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":152}","level":3,"time":"2016-05-16T03:32:07+00:00","method":"GET","url":"\/owncloud\/","user":"xavier"}
{"reqId":"DA8VbKPh8ioJ3bIFF9M+","remoteAddr":"172.97.196.91","app":"remote","message":"Autoload path not allowed: \/var\/www\/owncloud\/apps\/user_ldap\/user_ldap.php","level":4,"time":"2016-05-16T03:33:48+00:00","method":"PUT","url":"\/owncloud\/remote.php\/carddav\/addressbooks\/xavier\/Proches\/d1d9dfd6-60eb-49fc-ab7c-03293c0ce00e.vcf","user":"--"}
{"reqId":"RsbJ3X9RlgsGuJ+lKFEq","remoteAddr":"172.97.196.91","app":"remote","message":"Autoload path not allowed: \/var\/www\/owncloud\/apps\/user_ldap\/user_ldap.php","level":4,"time":"2016-05-16T03:33:49+00:00","method":"PUT","url":"\/owncloud\/remote.php\/carddav\/addressbooks\/xavier\/Proches\/d1d9dfd6-60eb-49fc-ab7c-03293c0ce00e.vcf","user":"--"}
{"reqId":"6gImJC5qWyza5oanZNcf","remoteAddr":"172.97.196.91","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php(172): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/ownclo...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\user_ldap\\\\\\\\U...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/lib\\\/ldap_backend_adapter.php(35): spl_autoload_call('OCA\\\\\\\\user_ldap\\\\\\\\U...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/user_cas.php(25): require_once('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/appinfo\\\/app.php(30): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(163): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/
lib\\\/private\\\/app.php(144): OC_App::requireAppFile('user_cas')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(117): OC_App::loadApp('user_cas')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user.php(129): OC_App::loadApps(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(644): OC_User::setupBackends()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(1112): OC::init()\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(37): require_once('\\\/var\\\/www\\\/ownclo...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":152}","level":3,"time":"2016-05-16T03:33:56+00:00","method":"GET","url":"\/owncloud\/","user":"xavier"}
{"reqId":"rB3RTsLFtsv2hA1NqEia","remoteAddr":"172.97.196.91","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_ldap\\\/user_ldap.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php(172): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/ownclo...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\user_ldap\\\\\\\\U...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/lib\\\/ldap_backend_adapter.php(35): spl_autoload_call('OCA\\\\\\\\user_ldap\\\\\\\\U...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/user_cas.php(25): require_once('\\\/var\\\/www\\\/ownclo...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/user_cas\\\/appinfo\\\/app.php(30): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(163): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/
lib\\\/private\\\/app.php(144): OC_App::requireAppFile('user_cas')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(117): OC_App::loadApp('user_cas')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/user.php(129): OC_App::loadApps(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(644): OC_User::setupBackends()\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(1112): OC::init()\\n#11 \\\/var\\\/www\\\/owncloud\\\/index.php(37): require_once('\\\/var\\\/www\\\/ownclo...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":152}","level":3,"time":"2016-05-16T03:37:09+00:00","method":"GET","url":"\/owncloud\/","user":"xavier"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
Do not know how to catch it, 
Hope it is not mandatory

**Comment by RealRancor** [comment]
@livier Please don't use a development version of ownCloud or an app if you're not familiar with development or debugging of such issues. Instead switch back to the latest stable release.

**Comment by livier** [comment]
Ok, I'll don't do it again ...
But know, How I get back to a working Owncloud
apt-get reconfigure Owncloud ?

**Comment by PVince81** [comment]
Best would be to uninstall the package and reinstall from scratch.
If you have data in your instance, make sure to backup the "config" and "data" folders.

**Comment by livier** [comment]
Done, Thanks
rename owncloud dir -> réinstall owncloud-> copy back config file + move back data dir -> done
I had backup of data base, but in fact it did not move.
Still have problem with contacts app, and understood it should be solve in 1.3 version witch is scheduled for 29 mai.
For a personal purpose it is (just) boring, but for a organisational or professional purpose it should be harmful.  I find Owncloud very nice and dynamic, but often too much bugs for production, I hesitate some times to recommend it. 
Must we consider release versions as Beta and wait months before adopting new versions ?

**Comment by PVince81** [comment]
Mind pointing to the ticket about the contacts app ?

**Comment by DarkMatter26** [comment]
same error fresh install : 9.0.2
on windows  xampp php 7.0.6

Fatal error: Uncaught Error: Class 'OCP\AutoloadNotAllowedException' not found in C:\- Portable\xampp-portable\xampp\htdocs\owncloud\lib\autoloader.php:152 Stack trace: 
#0 C:\- Portable\xampp-portable\xampp\htdocs\owncloud\lib\autoloader.php(172): OC\Autoloader->isValidPath('C:\\- Portable\\x...') 
#1 [internal function]: OC\Autoloader->load('OCP\\AutoloadNot...') 
#2 C:\- Portable\xampp-portable\xampp\htdocs\owncloud\lib\autoloader.php(152): spl_autoload_call('OCP\\AutoloadNot...') 
#3 C:\- Portable\xampp-portable\xampp\htdocs\owncloud\lib\autoloader.php(172): OC\Autoloader->isValidPath('C:\\- Portable\\x...') 
#4 [internal function]: OC\Autoloader->load('OC\\Config') 
#5 C:\- Portable\xampp-portable\xampp\htdocs\owncloud\lib\base.php(133): spl_autoload_call('OC\\Config') 
#6 C:\- Portable\xampp-portable\xampp\htdocs\owncloud\lib\base.php(506): OC::initPaths() 
#7 C:\- Portable\xampp-portable\xampp\htdocs\owncloud\lib\base.php(1112): OC::init() 
#8 C:\- Portable\xampp-portable\xampp\htdocs\owncloud\index.php(37): require_once('C in C:\- Portable\xampp-portable\xampp\htdocs\owncloud\lib\autoloader.php on line 152

**Comment by RealRancor** [comment]
@DarkMatter26 You can't run ownCloud on Windows as stated at various places like:

https://owncloud.org/install/#instructions-server

> ownCloud Server does not support Microsoft Windows.
