### ISSUE TITLE
Some files have not passed the integrity check

### ISSUE THREAD

**Issue by rburkholder1089** [owncloud/core#24652]
### Steps to reproduce
1. Download the latest version of OwnCloud from https://download.owncloud.org/community/owncloud-9.0.2.zip.
2. Install and configure.
3. Go to admin#security-warning.

### Expected behaviour
Code Signing will pass.

### Actual behaviour
Code signing fails:

- core
	- INVALID_HASH
		- core/doc/admin/_sources/configuration_files/collaborative_documents_configuration.txt
		- core/doc/admin/_static/img/note_pencil.svg
		- core/doc/admin/_static/img/warning.svg
		- core/doc/admin/_static/style.css
		- core/fonts/LICENSE.txt
		- core/vendor/jquery-migrate/jquery-migrate.js
		- core/vendor/jquery-migrate/jquery-migrate.min.js
		- core/vendor/jsTimezoneDetect/jstz.js
- files_texteditor
	- INVALID_HASH
		- js/vendor/ace/src-noconflict/mode-diff.js
- files_external
	- INVALID_HASH
		- 3rdparty/Dropbox/API.php

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 9.0.2

**Updated from an older ownCloud or fresh install:** Fresh Install

**Where did you install ownCloud from:** https://download.owncloud.org/community/owncloud-9.0.2.zip

**Signing status (ownCloud 9.0 and above):** On

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/doc/admin/_sources/configuration_files/collaborative_documents_configuration.txt
		- core/doc/admin/_static/img/note_pencil.svg
		- core/doc/admin/_static/img/warning.svg
		- core/doc/admin/_static/style.css
		- core/fonts/LICENSE.txt
		- core/vendor/jquery-migrate/jquery-migrate.js
		- core/vendor/jquery-migrate/jquery-migrate.min.js
		- core/vendor/jsTimezoneDetect/jstz.js
- files_texteditor
	- INVALID_HASH
		- js/vendor/ace/src-noconflict/mode-diff.js
- files_external
	- INVALID_HASH
		- 3rdparty/Dropbox/API.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/doc/admin/_sources/configuration_files/collaborative_documents_configuration.txt] => Array
                        (
                            [expected] => 251befed4a319c8e4b390b363a9bc8079b54991891204a4ff1cb551797931ba9f276903e1e5e8bde932afcb5e67d23f7939cea22e68c6bd7695e2b8ce654c5b3
                            [current] => 637ac6c02e3ef06cc19a9b465c5c0e6ae6777f9e5d5d52cae28482f350e3b348a5c3ba67ae693e95971373c326af98c27c7f04492aa836b6ab1348f7341ccb29
                        )

                    [core/doc/admin/_static/img/note_pencil.svg] => Array
                        (
                            [expected] => 78b9df57afe9468145e6e375cd1f61274b269b9c3019726a99e043ae952367acf53cf471cbc5b3dcca2e68367c2c4422d4a9f9a9fdbb11f9b962845ac77857de
                            [current] => 97117ce2827cc1b742678b52fc100de1e7d3fdb1adeea04a301c012e7f95b66e10a369c6a83ba89a707c4232b5e31fba3d5e58b0e0d970f22031d0704eebb5a9
                        )

                    [core/doc/admin/_static/img/warning.svg] => Array
                        (
                            [expected] => e8647b47ef1531b8c2fcdd51f76996fe85476467fc694540f3dcf8ce7e7da489e99edae5a158742da71c07dc09ccfaf721f01c1c4bda3f5bae9b711981b71a1b
                            [current] => 85687f19cf204716e9b1c608682aa22c045b6f8284a3496db07f13200952491bfea54deee7ef11115c0dedfd87443c7022ef05792892a8a984866752c8ec5726
                        )

                    [core/doc/admin/_static/style.css] => Array
                        (
                            [expected] => 894b1bea3e2b6bc61824ffebc081339a6caf0b57cda7fa9b9c9a5965e2a165dc177055db176cb535ef465c927b4bc4848802fe3e1b0fb709194b3cb7d2f90f8d
                            [current] => 5d9fbe71f0eae36c5a9c50f98733cc9e7a5bc7b2b56e3937c4431cf5e54649667bbe8f5900cdcbfbaa8b1eb8d5476d42a278d210c38110411885ad818e3a963a
                        )

                    [core/fonts/LICENSE.txt] => Array
                        (
                            [expected] => 4cc5a12bfe984c0a50bf7943e2d70a948d520ef423677c77629707aace3a95aa378d205de929105d644680679e70ef2449479b360ad44896b75bafed66613272
                            [current] => 98f6b79b778f7b0a15415bd750c3a8a097d650511cb4ec8115188e115c47053fe700f578895c097051c9bc3dfb6197c2b13a15de203273e1a3218884f86e90e8
                        )

                    [core/vendor/jquery-migrate/jquery-migrate.js] => Array
                        (
                            [expected] => 083c7aaf7b7304b2610ed5ff851f840d5db24993814128b86f42e8e5749b76e7117f6f154a8465fb4f163c1105ec3c6a5757e9c48b95e869d101de9399780a0e
                            [current] => fc2f4d093d3c8ecbfd30f25c59f30e92bf7457664ecf8871247b1802671b05b674c047bfcd0c2c9a674b49ce0bab9cdaed2416f69797381c775019ec250cbc0d
                        )

                    [core/vendor/jquery-migrate/jquery-migrate.min.js] => Array
                        (
                            [expected] => 7c31817254b71d4cac10120aa2829614311658e468036d27eb43b063b392620c4611ec3db3b3600da3e48fb82a41c5579c048fbd9022156f038b2b6cb5d946b5
                            [current] => 7b68a43a22a41404a2ff58e0da6a237492cad0fc3e56d216980802b4d5fb483895262a7e049340d6670002bdf899ba88c319239e60d0aae1ac31d98556b0ad6e
                        )

                    [core/vendor/jsTimezoneDetect/jstz.js] => Array
                        (
                            [expected] => ece74dd6f5fc9587cf167dd17df51b66f70bd711f445da8d1d21bb1b0570f3c97b25d3ece110b08e2f2b294369d9b775cc169b666840a5b769ba338aa6d73d48
                            [current] => beae737d18aae6e8c5fdfb0bf3389b687ec746e6b334185710cc5b8f45b73b3c57442db541807ab440b55517ef2d138f4c40148abafcb6462481016b617e1f53
                        )

                )

        )

    [files_texteditor] => Array
        (
            [INVALID_HASH] => Array
                (
                    [js/vendor/ace/src-noconflict/mode-diff.js] => Array
                        (
                            [expected] => 4a59b6376376b81e4e12ccc345065db62029a61035a88e19b1be3d7ec4cd9f86444121cca6d46c44a5f86e4f5b44d5109cbc77e80c07ff8dbce61f758b88e765
                            [current] => f8dbde2422c010af18b254a562c9e96865d5e58a698a191c855974f37d5a837ccc243ca85b2a8fbe81c61c53470b877e5b8b3e64cd2951c7f863bf49085aa5d7
                        )

                )

        )

    [files_external] => Array
        (
            [INVALID_HASH] => Array
                (
                    [3rdparty/Dropbox/API.php] => Array
                        (
                            [expected] => a6866ef3ceeb26d9d4b2ccc343aeaf626c82f03e279962bc7d761a68e87e5a7916ff0bcf7a350e20889557336ed9c5dd1651cfe513fa04bb8a03cd6d8f9cc484
                            [current] => 917eed2c4f6359a4d0b8658a36404c83344b0bf72ccda614dd59f97d099b3d9ef4e86691401c64d3754c3f7e0fa163eab946a25dbc7bc65e1694ffd47a054317
                        )

                )

        )

)
```

**List of activated apps:** Activity
Collaborative Tags
Comments
Deleted Files
Federation
First Run Wizard
Gallery
LDAP user and group backend
Mail Template Editor
Notifications
PDF Viewer
Provisioning API
Share files
Text Editor
Update Notifications
Versions
Video Player

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder


Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
```

**The content of config/config.php:** <?php
$CONFIG = array (
  'instanceid' => 'occ2r0gcf6x1',
  'passwordsalt' => 'Redacted',
  'secret' => 'Redacted',
  'trusted_domains' => 
  array (
    0 => 'Redacted',
    1 => 'Redacted',
  ),
  'datadirectory' => '/media/datapart/owncloud/data',
  'overwrite.cli.url' => 'Redacted',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => 'owncloud_db',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'Redacted',
  'dbpassword' => 'Redacted',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'Redacted',
  'ldapIgnoreNamingRules' => false,
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** No

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 7 SP1

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
Can you re-try with: https://download.owncloud.org/community/owncloud-9.0.2.tar.bz2

**Comment by rburkholder1089** [comment]
Same issue. I did not reinstall though, I just copied the effected files. Here are the results:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess
		- core/doc/admin/_sources/configuration_files/collaborative_documents_configuration.txt
		- core/doc/admin/_static/img/note_pencil.svg
		- core/doc/admin/_static/img/warning.svg
		- core/doc/admin/_static/style.css
		- core/fonts/LICENSE.txt
		- core/vendor/jquery-migrate/jquery-migrate.js
		- core/vendor/jquery-migrate/jquery-migrate.min.js
		- core/vendor/jsTimezoneDetect/jstz.js
- files_texteditor
	- INVALID_HASH
		- js/vendor/ace/src-noconflict/mode-diff.js
- files_external
	- INVALID_HASH
		- 3rdparty/Dropbox/API.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => 451fd1fa17239d8d1fa31c5b22dce5ef6710b93ff90a4705416e452d3f4cf22f387b49e98bd01a69ce2a2da8a2613298c37cd306955ed16808755afbbc32d38f
                            [current] => 62802bfac446e1f1dd0bb6277dd0ff5a882aca936d8d70d931a704d8176c28579061a5fa218a27b69f22f7fabe41e0caf6c547cafd3d19a75c85776aa6caaac0
                        )

                    [core/doc/admin/_sources/configuration_files/collaborative_documents_configuration.txt] => Array
                        (
                            [expected] => 251befed4a319c8e4b390b363a9bc8079b54991891204a4ff1cb551797931ba9f276903e1e5e8bde932afcb5e67d23f7939cea22e68c6bd7695e2b8ce654c5b3
                            [current] => 637ac6c02e3ef06cc19a9b465c5c0e6ae6777f9e5d5d52cae28482f350e3b348a5c3ba67ae693e95971373c326af98c27c7f04492aa836b6ab1348f7341ccb29
                        )

                    [core/doc/admin/_static/img/note_pencil.svg] => Array
                        (
                            [expected] => 78b9df57afe9468145e6e375cd1f61274b269b9c3019726a99e043ae952367acf53cf471cbc5b3dcca2e68367c2c4422d4a9f9a9fdbb11f9b962845ac77857de
                            [current] => 97117ce2827cc1b742678b52fc100de1e7d3fdb1adeea04a301c012e7f95b66e10a369c6a83ba89a707c4232b5e31fba3d5e58b0e0d970f22031d0704eebb5a9
                        )

                    [core/doc/admin/_static/img/warning.svg] => Array
                        (
                            [expected] => e8647b47ef1531b8c2fcdd51f76996fe85476467fc694540f3dcf8ce7e7da489e99edae5a158742da71c07dc09ccfaf721f01c1c4bda3f5bae9b711981b71a1b
                            [current] => 85687f19cf204716e9b1c608682aa22c045b6f8284a3496db07f13200952491bfea54deee7ef11115c0dedfd87443c7022ef05792892a8a984866752c8ec5726
                        )

                    [core/doc/admin/_static/style.css] => Array
                        (
                            [expected] => 894b1bea3e2b6bc61824ffebc081339a6caf0b57cda7fa9b9c9a5965e2a165dc177055db176cb535ef465c927b4bc4848802fe3e1b0fb709194b3cb7d2f90f8d
                            [current] => 5d9fbe71f0eae36c5a9c50f98733cc9e7a5bc7b2b56e3937c4431cf5e54649667bbe8f5900cdcbfbaa8b1eb8d5476d42a278d210c38110411885ad818e3a963a
                        )

                    [core/fonts/LICENSE.txt] => Array
                        (
                            [expected] => 4cc5a12bfe984c0a50bf7943e2d70a948d520ef423677c77629707aace3a95aa378d205de929105d644680679e70ef2449479b360ad44896b75bafed66613272
                            [current] => 98f6b79b778f7b0a15415bd750c3a8a097d650511cb4ec8115188e115c47053fe700f578895c097051c9bc3dfb6197c2b13a15de203273e1a3218884f86e90e8
                        )

                    [core/vendor/jquery-migrate/jquery-migrate.js] => Array
                        (
                            [expected] => 083c7aaf7b7304b2610ed5ff851f840d5db24993814128b86f42e8e5749b76e7117f6f154a8465fb4f163c1105ec3c6a5757e9c48b95e869d101de9399780a0e
                            [current] => fc2f4d093d3c8ecbfd30f25c59f30e92bf7457664ecf8871247b1802671b05b674c047bfcd0c2c9a674b49ce0bab9cdaed2416f69797381c775019ec250cbc0d
                        )

                    [core/vendor/jquery-migrate/jquery-migrate.min.js] => Array
                        (
                            [expected] => 7c31817254b71d4cac10120aa2829614311658e468036d27eb43b063b392620c4611ec3db3b3600da3e48fb82a41c5579c048fbd9022156f038b2b6cb5d946b5
                            [current] => 7b68a43a22a41404a2ff58e0da6a237492cad0fc3e56d216980802b4d5fb483895262a7e049340d6670002bdf899ba88c319239e60d0aae1ac31d98556b0ad6e
                        )

                    [core/vendor/jsTimezoneDetect/jstz.js] => Array
                        (
                            [expected] => ece74dd6f5fc9587cf167dd17df51b66f70bd711f445da8d1d21bb1b0570f3c97b25d3ece110b08e2f2b294369d9b775cc169b666840a5b769ba338aa6d73d48
                            [current] => beae737d18aae6e8c5fdfb0bf3389b687ec746e6b334185710cc5b8f45b73b3c57442db541807ab440b55517ef2d138f4c40148abafcb6462481016b617e1f53
                        )

                )

        )

    [files_texteditor] => Array
        (
            [INVALID_HASH] => Array
                (
                    [js/vendor/ace/src-noconflict/mode-diff.js] => Array
                        (
                            [expected] => 4a59b6376376b81e4e12ccc345065db62029a61035a88e19b1be3d7ec4cd9f86444121cca6d46c44a5f86e4f5b44d5109cbc77e80c07ff8dbce61f758b88e765
                            [current] => f8dbde2422c010af18b254a562c9e96865d5e58a698a191c855974f37d5a837ccc243ca85b2a8fbe81c61c53470b877e5b8b3e64cd2951c7f863bf49085aa5d7
                        )

                )

        )

    [files_external] => Array
        (
            [INVALID_HASH] => Array
                (
                    [3rdparty/Dropbox/API.php] => Array
                        (
                            [expected] => a6866ef3ceeb26d9d4b2ccc343aeaf626c82f03e279962bc7d761a68e87e5a7916ff0bcf7a350e20889557336ed9c5dd1651cfe513fa04bb8a03cd6d8f9cc484
                            [current] => 917eed2c4f6359a4d0b8658a36404c83344b0bf72ccda614dd59f97d099b3d9ef4e86691401c64d3754c3f7e0fa163eab946a25dbc7bc65e1694ffd47a054317
                        )

                )

        )

)

**Comment by PVince81** [comment]
@rburkholder1089 did you click "rescan files" to refresh the hashes?

**Comment by rburkholder1089** [comment]
I did.

**Comment by PVince81** [comment]
Please try again with 9.0.4, should be fine now.

Make sure you deleted older source code before replacing with the new version.

If the integrity issue is still there, please reopen.

**Comment by hanski** [comment]
Ran into this issue today, while upgrading an old owncloud 5.x installation. Problem was with my FTP client's settings. Transfer mode needs to be set to "binary"!

**Comment by RealRancor** [comment]
Yes, thats correct. The documentation about these integrity errors at:

https://doc.owncloud.org/server/latest/admin_manual/issues/code_signing.html#fixing-invalid-code-integrity-messages

have a blue notes box about the transfer mode (ASCII vs. binary).
