### ISSUE TITLE
template for richdocuments and so one

### ISSUE THREAD

**Issue by ArnoldSchiller** [owncloud/core#24662]
### Steps to reproduce
1.  richdocuments and other apps use use \OCP\AppFramework\Http\TemplateResponse;
2.  Three types are implemented
   $basename = $this->l10n->t('Neuer Text.odt');
                 switch ($mimetype) {
                         case 'application/vnd.oasis.opendocument.spreadsheet':
                                 $basename = $this->l10n->t('Neue Tabelle.ods');
                                 break;
                         case 'application/vnd.oasis.opendocument.presentation':
                                 $basename = $this->l10n->t('Neue Presentation.odp');
3. for the future it would be nice if there are templates for other application/vnd.oasis.opendocument
### Expected behaviour

Templates for all application/vnd.oasis.opendocument
### Actual behaviour

Only 4 exists html, odt, ods, odp

**Comment by PVince81** [comment]
Out of curiosity, where are these templates used currently ?

**Comment by ArnoldSchiller** [comment]
Add the moment richdocuments create office-Document  "New Spreadsheet" is template.ods and "New Presentetion" is template.odp. Every "New Document" not only richdocuments use template.odt. 

If you want a Draw from Libreoffice Online to create then you need template.odg for example.

**Comment by PVince81** [comment]
Ah! "Libreoffice Online" uses it, nice :smile:

**Comment by ArnoldSchiller** [comment]
Hmpf und das einem deutschen auf Englisch, wo mein Englisch doch eh so mies ist ... :+1: :smile:

**Comment by PVince81** [comment]
Please reopen in https://github.com/owncloud/richdocuments. The templates must be provided by the app itself.
