### ISSUE TITLE
quota option "other" description incorrectly replaced

### ISSUE THREAD

**Issue by humblemumble** [owncloud/core#24664]
### Steps to reproduce
1. navigate in web interface to user management
2. choose custom quota via other (in SVK translation for example ine)
3. choose for example 5 (5bytes)
4. then try to change it, and in the menu, description changes to B, and the option other (ine) is missing
5. when you choose B, it behaves like option other, so the description seems to be replaced incorrectly

### Expected behaviour
the option other (ine) shoule be always present, so users know what to choose in case of setting up custom quotas

### Actual behaviour
string other is replaced by unit description

### Server configuration
**Operating system**: Centos 7, x86_64

**Web server:** Apache 2.4 distribution based

**Database:** Mariadb 5.5 distribution based

**PHP version:** 5.4 distribution based

**ownCloud version:** 9.0.2

**Updated from an older ownCloud or fresh install:**fresh install

**Where did you install ownCloud from:**repositories for rhel7/centos 7

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_sharing: 0.9.1
  - files_trashbin: 0.8.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - files_pdfviewer
  - files_texteditor
  - files_versions
  - gallery
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "updatechecker": false,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "partner.mydomain.org"
        ],
        "datadirectory": "\/srv\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "filesystem_check_changes": 0,
        "memcache.local": "\\OC\\Memcache\\APC",
        "asset-pipeline.enabled": true,
        "forcessl": true,
        "xframe_restriction": true,
        "enable_previews": false,
        "has_internet_connection": false,
        "loglevel": 1,
        "log_type": "syslog",
        "logfile": "logs_redirected_to.syslog",
        "mail_smtpmode": "smtp",
        "mail_from_address": "root",
        "mail_domain": "partner.mydomain.org",
        "mail_smtphost": "smtp.mydomain.org",
        "mail_smtpsecure": "tls",
        "theme": "mydomain",
        "default_language": "sk_SK",
        "skeletondirectory": "\/var\/www\/html\/owncloud\/themes\/mydomain\/skeleton",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "config_is_read_only": true,
        "tempdirectory": "\/srv\/owncloud\/tmp",
        "instanceid": "oc5t6kkbm1wo"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "2"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1463346557.6004",
            "lastcron": "1463476501",
            "lastupdatedat": "1463346557.6557",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "shareapi_allow_public_notification": "yes"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.1.6",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.0.4",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.4.4",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "no",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "14.5.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.2.3",
            "types": "logging"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        }
    }
}

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**Firefox 46

**Operating system:** Ubuntu 15.10

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Ah yes, I saw this one a bunch of times.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/25253

**Comment by SergioBertolinSG** [comment]
Dup of https://github.com/owncloud/core/issues/19038
