### ISSUE TITLE
[stable8] unit test failing

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#24663]
@schiesbn @rullzer can you please have a look? THX

````
 OCA\Files_Encryption\Tests\Share.testRemoteShareFile
 Stack Trace

OCA\Files_Encryption\Tests\Share::testRemoteShareFile
Exception: Sharing 1208 failed, could not find user1@server1, maybe the server is currently unreachable.

/ssd/jenkins/workspace/server-stable8/database/sqlite/label/SLAVE/lib/private/share/share.php:761
/ssd/jenkins/workspace/server-stable8/database/sqlite/label/SLAVE/lib/public/share.php:236
/ssd/jenkins/workspace/server-stable8/database/sqlite/label/SLAVE/apps/files_encryption/tests/share.php:643

**Comment by schiesbn** [comment]
Tried it with sqlite and postgresql but couldn't reproduce it... All tests pass locally.

**Comment by schiesbn** [comment]
... also a manual test showed that federated shares with encryption works on stable8 (8cee246880fdd652807c973aaadc535ee328258a)

**Comment by DeepDiver1975** [comment]
> Exception: Sharing 1208 failed, could not find user1@server1, maybe the server is currently unreachable.

Is it really trying to connect to that server? This server cannot exist and throwing that error is quite expected - isn't it?

Even if not reproducible - what could be the reason for this to fail?

THX

**Comment by rullzer** [comment]
@DeepDiver1975 probabaly some mocking going wrong...

**Comment by DeepDiver1975** [comment]
@rullzer maybe you find the time to have a look? THX

**Comment by rullzer** [comment]
Mmmm I'm unsure as how that ever worked... do some bisecting tomorrow

**Comment by DeepDiver1975** [comment]
Thx

**Comment by rullzer** [comment]
Mmmm my bisect is not giving me much... somewhere in the stable8 branch we really messed up and basically everything breaks for me:

```Uncaught exception 'Exception' with message 'Not installed' in /tmp/a/core/lib/base.php:223```

Which kind of makes it impossible to do a proper bisect.

I also see no mocking in place for this so I'm still unsure how this ever worked.

Nasy hack would be to just remove the test... not clean at all... but I'm out of other ideas for now

**Comment by PVince81** [comment]
@DeepDiver1975 is this still an issue ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 is this still an issue ?

no - https://ci.owncloud.org/view/server%20stable8/job/server-stable8/

I finally fixed it myself ...
