### ISSUE TITLE
Wishlist from mobile & QA team

### ISSUE THREAD

**Issue by davivel** [owncloud/core#24674]
- [ ] Web browser info is all via API so Clients can use same ; cc @javiergonzper 
- [ ] Versions API; favorites API; search API; TrashBin API; know when a path is in a (external storage | sync | share | shared link) folder ; Icon replacement of external storage icon ; cc @rperezb 
- [ ] Error code and success code standards (in APIs) ; cc @SergioBertolinSG 
- [ ] Know server Auth mechanism (basicAuth, 2 Factor) ; cc @rperezb 

cc @MTRichards , @cmonteroluque

**Comment by PVince81** [comment]
Oh it's you lego batman. Looking forward to subtickets with details :smile: 

Here are a few:
- versions API: https://github.com/owncloud/core/issues/10571
- trashbin API: https://github.com/owncloud/core/issues/15646
- favorites API: need to move to Webdav REPORT: https://github.com/owncloud/core/issues/23263
- search API: ?
- info about mount type: it's available in oc:permissions **somehow** but isn't clean. Would be nice to have proper Webdav properties.
- info about shared/shared link: try requesting the "oc:share-types" property :smile: (CC @rullzer)

**Comment by davivel** [comment]
Thanks, @PVince81 . Yes, that's me :-D 

Mentioned people per entry is expected to provide some more detail and create subtickets if needed.

**Comment by SergioBertolinSG** [comment]
HTTP standard codes for provisioning API: https://github.com/owncloud/core/issues/13092

**Comment by cmonteroluque** [comment]
https://github.com/owncloud/client/issues/4854

**Comment by cmonteroluque** [comment]
linking both lists

**Comment by PVince81** [comment]
versions API coming soon...
