### ISSUE TITLE
Making Favorites Consistent Across Platforms

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#24671]
As an ownCloud user, I want favorites within the mobile apps to be the same as favorites on the server, so that I can find my most important files fast on any ownCloud web, mobile or desktop client.

Acceptance Criteria:
-   We will normalize icons used on all platforms – favorites become a yellow star (like on server)
-   Same behavior of favorites on all platforms – using the web interface as a reference point
-   Favorites are only synced if the “keep in sync” option is checked for a folder or favorite on a specific device
-   Favorite meta data is synced in the mobile device no matter what
-   Favorites are available for files and folders
-   Children folders and files of a parent folder can be favorited, and the favorited children also appears in the favorite filter view – in a flat structure
-   A folder is inherited, so if a folder is favorited, the files in it are considered favorites, but are not favorited with a star individually 
-   Desktop could use shortcuts in a special “favorite” folder somewhere, but we need to discuss in more detail how to handle this (see desktop issue below)

Ultimate goal is to use the virtual file system to allow desktop users to view all files, synced or not, and then sync the flies locally.

Related issues:

Server
Favorites view on server https://github.com/owncloud/core/issues/23920

Desktop
Do we need Favorites on Desktop? https://github.com/owncloud/client/issues/4844 

Mobile
iOS:
Favorites filter (needs to line up with Android) https://github.com/owncloud/ios/issues/652

Android: 
Favorites shortcut https://github.com/owncloud/android/issues/867

EDITED @rperezb
- [00005264](https://na25.salesforce.com/5003100000ZbdHC?srPos=0&srKp=500)
- [00005645](https://na25.salesforce.com/5003100000bqSIL?srPos=0&srKp=500)

**Comment by SergioBertolinSG** [comment]
@DeepDiver1975 @PVince81 Will this feature require work from server side?

Currently files/folder can be favorited/unfavorited from webdav interface.

**Comment by DeepDiver1975** [comment]
favorites are a special type of tags which can be set via webdav

**Comment by davivel** [comment]
As custom properties then, right?

**Comment by SergioBertolinSG** [comment]
Yes, the property is "{http://owncloud.org/ns}favorite". "1" is favorite "" is not favorite.

**Comment by davivel** [comment]
In this case, we can know if the files/folders we discover / refresh are favorite or not.

But there is no way to get all the favorite files of a user in a single request, right? 

That should allow us start, but not sure if will satisfy user expectations...

Addition or deletion of tags don't provoke the ETag changes, right?

**Comment by SergioBertolinSG** [comment]
This questions are more for @PVince81.
I think currently you'd have to request all the files/folders with a propfind and choose the ones with favorite "1" to get that list.

**Comment by nasli** [comment]
Until we can get all the favorites for an account, I would not recommend display a cropped favorite list view that the user would expect represents all the favorites he has.

**Comment by PVince81** [comment]
> But there is no way to get all the favorite files of a user in a single request, right? 

No public API for this yet, to be added as part of the REPORT method: https://github.com/owncloud/core/issues/23263

**Comment by PVince81** [comment]
Note that the REPORT method would return a flat list of files, no hierarchy. I hope this would suit the requirements.

**Comment by davivel** [comment]
I think so, the current criteria for the UI is showing a flat list in the favorites section, seems fit perfectly.

In mobile we still didn't use this method before. May I guess it accepts pagination parameters?

**Comment by PVince81** [comment]
No pagination yet but hopefully we'll add it for 9.2 because we'd also
like to use REPORT for search.

**Comment by Kawohl** [comment]
For reference 00006428

**Comment by cdamken** [comment]
@pmaier1 @hodyroff

**Comment by DeepDiver1975** [comment]
> No pagination yet but hopefully we'll add it for 9.2 because we'd also

https://github.com/owncloud/core/pull/26507 - will add pagination - for tag based search as well as favorites as well as the unfiltered file list

**Comment by butonic** [comment]
Not a top 10 SF case -> blue ticket

**Comment by PVince81** [comment]
server side API exists for favorites: https://github.com/owncloud/documentation/issues/2950

Closing the server ticket as the server part is done. Please open/refer to client-specific tickets.
