### ISSUE TITLE
Investigate ActivityPub

### ISSUE THREAD

**Issue by butonic** [owncloud/core#24683]
from https://w3c-social.github.io/activitypub/ or https://www.w3.org/TR/activitypub/

> ## Abstract
>
> The ActivityPub protocol is a social networking protocol based upon the ActivityStreams 2.0 data
> format. It is based upon experience gained from implementing and working with the OStatus and
> Pump.io protocols.
>
>## Overview
>
> The ActivityPub protocol is broadly based on the distribution of
> *activities*, described using ActivityStreams; these activities
> are produced in response to a user performing an activity. Most activities
> are purely responsive in nature - they are produced as a response to a
> user *having* done something. In addition, certain activities posted
> by a user to their outbox may trigger certain
> operations on the user's behalf. Finally, activities may have side effects
> as they propogate throughout the social graph. As an example of this:
> 
> 1. A user posts the `like` activity to their outbox. This
>         activity causes the user's server to perform an activity on behalf of
>         the user; in particular, it adds the specified object to the collection
>         of objects the user has liked.
> 2. A consequence of the above activity is that the server hosting
>         the liked object will be notified of the operation, and will normally
>         add the activity to the list of "likes" the object has received.
> 3. Finally, the server receiving the like will distribute this activity
>         to everyone it distributed the original object to.

looks similar to some of the things OCS does ...

cc @nickvergessen @karlitschek

**Comment by nickvergessen** [comment]
See activity app

**Comment by karlitschek** [comment]
@butonic I completely agree. I'm actually a member of the W3C working group that develops this spec. And I started to implement a library for this spec. https://github.com/karlitschek/SocialPub  WIP of course.
I think it would be a great API to expose the activities events to the outside and maybe consume events from other servers. This would be a nice improvement for federation. :-)

**Comment by nickvergessen** [comment]
See https://github.com/owncloud/activity/issues/494 and the follow up issues
