### ISSUE TITLE
Use standard HTTP codes in new versions of OCS APIs

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#24688]
Current versions of provisioning API, sharing API and perhaps others are returning custom codes, both for success or error.

Incoming new versions of OCS APIs should follow http code standards http://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml.

Some discussion is already happening in:
provisioning api:  https://github.com/owncloud/core/issues/13092
sharing api:         https://github.com/owncloud/core/issues/22209

**Comment by nickvergessen** [comment]
We are infect already doing that for new stuff, e.g. https://github.com/owncloud/activity/blob/master/docs/endpoint-v2.md#http-status
https://github.com/owncloud/notifications/blob/master/lib/Controller/EndpointController.php#L135-L136
https://github.com/owncloud/notifications/blob/master/lib/Controller/EndpointController.php#L153

We simply can't change that on old endpoints.
But that is also why we have ocs/v2.php which serves the status code as http code when it's in range:
https://github.com/owncloud/core/blob/46bdf6ea2b1e10c2f4d2fae214ecc81b188fa981/lib/private/legacy/api.php#L496-L499

So nothing really "to discuss" here, it's a design decision that has already been made and will be taken care of in the future.

cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
Indeed @nickvergessen

**Comment by DeepDiver1975** [comment]
This is also part of the official ocs spec

**Comment by SergioBertolinSG** [comment]
Good, this is a wish, so a granted wish.

Anyway I guess I am not reading the right spec, here https://freedesktop.org/wiki/Specifications/open-collaboration-services/ it is still using not standard codes.

**Comment by nickvergessen** [comment]
Well that are all v1/ routes and as said above we can't change existing routes and their return codes, because apps might depend on them.

**Comment by DeepDiver1975** [comment]
@karlitschek @LukasReschke where is the specification located for the v2 routes?
