### ISSUE TITLE
Floating point exception in the client

### ISSUE THREAD

**Issue by jpschewe** [owncloud/core#24690]
I recently upgraded to version 2.2.0-2.2 of the client using the ubuntu repository 
`deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_15.10/ /`
I am running Ubuntu 15.10.
I noticed that my client icon was disappearing so I ran it from the command line. It started out fine and did a sync. After some time I noticed the icon was gone. I checked the terminal window and had:
{{{
>owncloud
Floating point exception (core dumped)
}}}

Here is the back trace from gdb:
{{{
>gdb `type -p owncloud` core
GNU gdb (Ubuntu 7.10-1ubuntu2) 7.10
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/owncloud...(no debugging symbols found)...done.
[New LWP 1015]
[New LWP 1016]
[New LWP 1026]
[New LWP 1017]
[New LWP 1025]
[New LWP 1018]
[New LWP 1020]
[New LWP 1041]
[New LWP 1055]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `owncloud'.
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x00007fc943b3b776 in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
[Current thread is 1 (Thread 0x7fc943e87800 (LWP 1015))]
(gdb) bt
#0  0x00007fc943b3b776 in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#1  0x00007fc943b3c4d6 in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#2  0x00007fc943b2ff3b in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#3  0x00007fc943b303b3 in ?? ()
   from /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
#4  0x00007fc951c5d651 in QObject::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fc95264cb8c in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007fc952652230 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007fc951c2bf1b in QCoreApplication::notifyInternal(QObject*, QEvent*)
    () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fc951c2e057 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fc951c82e73 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fc94d1fbff7 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007fc94d1fc250 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
#12 0x00007fc94d1fc2fc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007fc951c8327f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007fc951c2975a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007fc951c312cc in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x000000000046d9d9 in main ()
}}}

The end of .owncloudsync.log contains this after the last file that was synced last night:
{{{
#=#=#=# Syncrun started  until  (0 msec)
#=#=#=# Syncrun started  until  (0 msec)
#=#=#=# Syncrun started  until  (0 msec)
#=#=#=# Syncrun started  until  (0 msec)
#=#=#=# Syncrun started  until  (0 msec)
#=#=#=# Syncrun started  until  (0 msec)
}}}

The timestamps on the dot files in my owncloud directory show that the client last wrote to the files about 45 minutes before I woke up. This means it ran about 8 hours before crashing.

I'll run the client in gdb this time to see if I can catch something else.

**Comment by nickvergessen** [comment]
Please report in the client repo: https://github.com/owncloud/client/

Also the missing icon already has a lot of open issues, so you can have a look at those, e.g. https://github.com/owncloud/client/issues/4693#issuecomment-215944779
