### ISSUE TITLE
OC download URL does not fetch latest OC version but old one

### ISSUE THREAD

**Issue by autrui** [owncloud/core#24708]
I have a script that updates my owncloud. It relies on the URL _download.owncloud.org/community/owncloud-**latest**.tar.bz2_ to get the latest OC version.
But somehow I always end up getting version 9.0.**1** even though 9.0.**2** was already announced on the OC download page quite some time ago.

Is there something wrong with 9.0.**2** or why does the URL still point to the 9.0.**1** file?  

If you possibly can it would really help to keep the URL for the latest OC version up-to-date. Using that URL makes many things a lot easier for me.
Thanks for your help.

_____
**Steps to reproduce**
1. try downloading OC from https://download.owncloud.org/community/owncloud-latest.tar.bz2
2. it still points to version 9.0.1, not 9.0.2

**Expected behaviour**
I get the latest OC version. That's what this URL is for I guess.

**Actual behaviour**
I get 9.0.1, not the latest one.

**Comment by nickvergessen** [comment]
Yeah, we are currently not distributing the 9.0.2 via the updater, because the updater has an issue:
https://github.com/owncloud/updater/issues/350

To not break any further instances, the update shipping was disabled, until the updater was fixed.

Close @PVince81 ?

**Comment by PVince81** [comment]
I think this URL has nothing to do with the updater. It's just a plain link to which the website points.

@danimo @jospoortvliet do you know ?

**Comment by nickvergessen** [comment]
https://github.com/owncloud/administration-internal/pull/17 :cough:

**Comment by PVince81** [comment]
@nickvergessen I think the updater doesn't use the URL with "owncloud-latest.tar.bz2" but rather URLs like "owncloud-$version.tar.bz2".

The URL with "latest" in it is rather used from the web pages and needs to be updated separately.
