### ISSUE TITLE
Optimize thumbnails for faster transfer

### ISSUE THREAD

**Issue by Glandos** [owncloud/core#24700]
### Steps to reproduce
1. Go to a folder containing elements that can be previewed
2. Preview thumbnails get generated
3. They can be further optimized by using jpegoptim or zopflipng (or pngcrush, or optipng)
### Expected behaviour

Image thumbnails should be crunched as much as possible. They are generated only once, and then served many times.
### Actual behaviour

Thumbnails are only created using default `image*` PHP functions.
### Server configuration

**Operating system**: 
Debian/testing
**Web server:**
nginx
**Database:**
Postgresql
**PHP version:**
7.0.6
**ownCloud version:** (see ownCloud admin page)
9.1
**Updated from an older ownCloud or fresh install:**
Updated
**Where did you install ownCloud from:**
Git
**Signing status (ownCloud 9.0 and above):**

Integrity checker has been disabled. Integrity cannot be verified.

```
**List of activated apps:**
  - activity: 2.2.1
  - admin_migrate: 0.1
  - bookmarks: 0.666666
  - comments: 0.2
  - dav: 0.1.6
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoviewer: 0.1.3
  - gallery: 14.5.0
  - music: 0.3.11
  - notes: 2.0.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - search_lucene: 0.7.0
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
  - user_migrate: 0.1
```

**The content of config/config.php:**

```
{
    "system": {
        "datadirectory": "\/media\/nas\/shares\/",
        "dbtype": "pgsql",
        "version": "9.0.2.2",
        "installedat": "1325338463.9158",
        "lastupdatedat": "1337694133.2558",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 1,
        "log_rotate_size": 10485760,
        "apps_paths": [
            {
                "path": "\/var\/www\/cloud.example.com\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/cloud.example.com\/owncloud\/apps_repo",
                "url": "\/apps_repo",
                "writable": false
            },
            {
                "path": "\/var\/www\/cloud.example.com\/owncloud\/apps_other",
                "url": "\/apps_other",
                "writable": true
            }
        ],
        "instanceid": "5076f7a67458c",
        "maintenance": false,
        "theme": "",
        "singleuser": false,
        "trusted_domains": [
            "cloud.example.com"
        ],
        "mail_smtpmode": "php",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "asset-pipeline.enabled": true,
        "forcessl": true,
        "secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

No log involved
#### ownCloud log (data/owncloud.log)

No log involved
#### Browser log

No log involved

**Comment by Glandos** [comment]
Hi!

Is this a auto-close? Or a duplicate?

**Comment by JanAckermann** [comment]
This has been closed because of the stale tag, feel free to reopen =)
