### ISSUE TITLE
Connection error in mobile app when 'installed' -> 'true' 

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#24714]
### Steps to reproduce
1. use `'installed' => 'true',` instead of `'installed' => true,` in config/config.php
2. Normal login via browser works
3. Login via mobile app

### Expected behaviour
Login works/wrong setting is corrected/clear error reporting

### Actual behaviour
App shows `It is not possible to connect to the server at this time`. But then I can access files (iOS 3.4.9). It seems to be only the initial connection check. Nothing in the logfiles.

related: https://github.com/owncloud/ios/issues/380 https://github.com/owncloud/android/issues/509 https://forum.owncloud.org/viewtopic.php?f=24&t=36650

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache

**Database:** MariaDB

**PHP version:** php 7 (dotdeb)

**ownCloud version:** 8.2.5

**Comment by nickvergessen** [comment]
Well the installed should be a boolean and not a string, so I guess when it errors it's okay?
We only set it to booleans, so try to find out why it was a string for you and fix that ;)

**Comment by tflidd** [comment]
As you see in the references, some users set it to a string for whatever 
reason. For users, it is quite common to change or add values in the 
config.php, and if their owncloud doesn't work they'll try everything. 
Shouldn't there be some kind of verification of variables?

There is no problem if there is an error. However, the handling is very 
inconsistent. Why does it throw an error on the mobile app but there is 
nothing on the webinterface (perhaps some hidden errors?). To debug 
this, it's a nightmare.

A lot of servers check their configuration files for syntax errors 
(webservers, mailservers, ...).

**Comment by RealRancor** [comment]
@nickvergessen We have a user at the forums stating he never touched that config on his own:

https://forum.owncloud.org/viewtopic.php?f=24&t=36650&start=10#p116891
