### ISSUE TITLE
mobile Client: Thumbnail Gallery

### ISSUE THREAD

**Issue by TDannhauer** [owncloud/core#24711]
It would be great to have a thumbnail gallery in the iOS client like on the webpage.

With medium size thumbnails, it would be possible to watch Photos on iOS without fully loading all pictures.

**Comment by MTRichards** [comment]
@javiergonzper @nasli did we release the streamedthumbnails for iOS yet? That gets the thumbnails 
I know it is not mobile, gallery per se - just wanted to put the latest here if it was different.

**Comment by tobiasKaminsky** [comment]
In android this is possible via these PR (by me):
- https://github.com/owncloud/android/pull/1599: Just preload a screen optimized (~50kb) image into cache and show this. It can also be used to share via whatsapp, email. If neccessary still a real download can be triggered.
- https://github.com/owncloud/android/pull/1466: Pinch zooms allows to adjust the number of columns in the grid view from (currently fix) 3 to 10 via pinch gesture.

**Comment by nickvergessen** [comment]
Should be reported in the iOS repo? https://github.com/owncloud/ios/issues
