### ISSUE TITLE
'Login failed' log entries when using token auth

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/core#24727]
### Steps to reproduce
1. Create a device password (PR #24703)
2. Configure desktop sync client with generated password
3. Watch the log file

### Expected behaviour
Client syncs without error

### Actual behaviour
``Login failed: 'username' (Remote IP: '::1')`` logged to owncloud.log

Sync seems to work though.

### Server configuration
**Operating system**:

**Web server:**
PHP built-in

**Database:**
Sqlite

**PHP version:**
7.0.6

**ownCloud version:** (see ownCloud admin page)
master

**Comment by rullzer** [comment]
Could be related to sessions... and the client not sending the token with each request. Which might fail for some reason?

**Comment by rullzer** [comment]
Maybe you can analyze with the MITMproxy?

**Comment by ChristophWurst** [comment]
Found it. It happens only if DAV clients authenticate with token instead of the user password. As a interim solution we're creating session tokens for dav clients 5e55dfb2d6d594e813bca9733886ac46e537b6c5. If the password is then checked (is done on login and every 5 minutes), the user backend says the password is wrong and (User)Manager::checkPassword throws an exception.

This means creating session tokens for DAV clients is a bad solution and we should fix that ASAP. @LukasReschke any idea?

**Comment by ChristophWurst** [comment]
https://github.com/owncloud/core/blob/6ace14b6ad34821c8cf51b4854aa624c116c3c9e/lib/private/User/Session.php#L291-L296 can also lead to that exception being thrown if the client authenticates via token. The problem here is unrelated to the one above though and can be fixed easily by inverting the order (try token auth first).
