### ISSUE TITLE
LDAP not adding AD users error on line #733 apps/user_ldap/lib/access.php

### ISSUE THREAD

**Issue by isaiespino** [owncloud/core#24733]
### Steps to reproduce
1. follow instructions for LDAP setup - configuration OK
2. go to users
3. get back to logs

### Expected behaviour
have AD users listed on oc users

### Actual behaviour
keep loading at users

### Server configuration
**Operating system**:
Ubuntu Server 14.04
**Web server:**
Apache 2.2
**Database:**
MySql
**PHP version:**
5.5
**ownCloud version:** (see ownCloud admin page)
9.0.2
**Updated from an older ownCloud or fresh install:**
fresh install
**Where did you install ownCloud from:**
tar.bz - manually
**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocyuqgqeu4nm",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.eplogistics.com"
        ],
        "datadirectory": "\/var\/www\/owncloud_data",
        "overwrite.cli.url": "http:\/\/10.0.100.203",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "administrator",
        "mail_smtpmode": "php",
        "mail_domain": "eplogistics.com",
        "ldapIgnoreNamingRules": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 0
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory
#### LDAP configuration (delete this part if not used)

+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                                 |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                               |
| hasPagedResultSupport         |                                                                                                                                                 |
| homeFolderNamingRule          |                                                                                                                                                 |
| lastJpegPhotoLookup           | 0                                                                                                                                               |
| ldapAgentName                 | cn="administrator",cn="users",dc="eplogistics",dc="com"                                                                                         |
| ldapAgentPassword             | ***                                                                                                                                             |
| ldapAttributesForGroupSearch  |                                                                                                                                                 |
| ldapAttributesForUserSearch   |                                                                                                                                                 |
| ldapBackupHost                |                                                                                                                                                 |
| ldapBackupPort                |                                                                                                                                                 |
| ldapBase                      | CN="users",DC="eplogistics",DC="com"                                                                                                            |
| ldapBaseGroups                | CN="users",DC="eplogistics",DC="com"                                                                                                            |
| ldapBaseUsers                 | CN="users",DC="eplogistics",DC="com"                                                                                                            |
| ldapCacheTTL                  | 600                                                                                                                                             |
| ldapConfigurationActive       | 1                                                                                                                                               |
| ldapDynamicGroupMemberURL     |                                                                                                                                                 |
| ldapEmailAttribute            |                                                                                                                                                 |
| ldapExperiencedAdmin          | 0                                                                                                                                               |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                 |
| ldapExpertUUIDUserAttr        |                                                                                                                                                 |
| ldapExpertUsernameAttr        |                                                                                                                                                 |
| ldapGroupDisplayName          | cn                                                                                                                                              |
| ldapGroupFilter               |                                                                                                                                                 |
| ldapGroupFilterGroups         |                                                                                                                                                 |
| ldapGroupFilterMode           | 0                                                                                                                                               |
| ldapGroupFilterObjectclass    |                                                                                                                                                 |
| ldapGroupMemberAssocAttr      | member                                                                                                                                          |
| ldapHost                      | 192.168.50.30                                                                                                                                   |
| ldapIgnoreNamingRules         |                                                                                                                                                 |
| ldapLoginFilter               | (&(&(|(objectclass=user))(|(|(memberof=CN=spark,CN=Users,DC=eplogistics,DC=com)(primaryGroupID=1197))))(|(mailPrimaryAddress=%uid)(mail=%uid))) |
| ldapLoginFilterAttributes     |                                                                                                                                                 |
| ldapLoginFilterEmail          | 1                                                                                                                                               |
| ldapLoginFilterMode           | 0                                                                                                                                               |
| ldapLoginFilterUsername       | 0                                                                                                                                               |
| ldapNestedGroups              | 0                                                                                                                                               |
| ldapOverrideMainServer        |                                                                                                                                                 |
| ldapPagingSize                | 500                                                                                                                                             |
| ldapPort                      | 389                                                                                                                                             |
| ldapQuotaAttribute            |                                                                                                                                                 |
| ldapQuotaDefault              |                                                                                                                                                 |
| ldapTLS                       | 0                                                                                                                                               |
| ldapUserDisplayName           | displayName                                                                                                                                     |
| ldapUserDisplayName2          |                                                                                                                                                 |
| ldapUserFilter                | (&(|(objectclass=user))(|(|(memberof=CN=spark,CN=Users,DC=eplogistics,DC=com)(primaryGroupID=1197))))                                           |
| ldapUserFilterGroups          | spark                                                                                                                                           |
| ldapUserFilterMode            | 0                                                                                                                                               |
| ldapUserFilterObjectclass     | user                                                                                                                                            |
| ldapUuidGroupAttribute        | auto                                                                                                                                            |
| ldapUuidUserAttribute         | auto                                                                                                                                            |
| turnOffCertCheck              | 1                                                                                                                                               |
| useMemberOfToDetectMembership | 1                                                                                                                                               |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------+

### Client configuration
Chrome Versión 45.0.2454.99

**Operating system:**
Windows 7 x64
### Logs
Error	PHP	Call to a member function processAttributes() on a non-object at /var/www/html/apps/user_ldap/lib/access.php#733	2016-05-19T15:58:04+00:00
Error	PHP	Call to a member function processAttributes() on a non-object at /var/www/html/apps/user_ldap/lib/access.php#733	2016-05-19T15:57:41+00:00
Error	PHP	Call to a member function processAttributes() on a non-object at /var/www/html/apps/user_ldap/lib/access.php#733	2016-05-19T15:56:43+00:00
Error	PHP	Call to a member function processAttributes() on a non-object at /var/www/html/apps/user_ldap/lib/access.php#733	2016-05-19T15:44:17+00:00

#### ownCloud log (data/owncloud.log)
{"reqId":"sIhUZxzfAje8q3JsQLmS","remoteAddr":"192.168.52.1","app":"PHP","message":"Call to a member function processAttributes() on a non-object at \/var\/www\/html\/apps\/user_ldap\/lib\/access.php#733","level":3,"time":"2016-05-19T16:20:10+00:00","method":"GET","url":"\/index.php\/settings\/users\/users?offset=0&limit=250&gid=&pattern=","user":"administrator@eplogistics.com"}

**Comment by sd-demon** [comment]
confirmed from my side - same error after fresh install of owncloud 9.0.2

Server configuration
Operating system: Debian/wheezy
Web server: Apache/2.2.22
Database: Mysql
PHP version: PHP 5.4.45-0+deb7u2
ownCloud version (see ownCloud admin page): 9.0.2
Updated from an older ownCloud or fresh install: fresh
ownCloud log (data/owncloud.log):

{"reqId":"pyWOMjO18YY986CW+L1B","remoteAddr":"5.147.253.110","app":"PHP","message":"Call to a member function processAttributes() on a non-object at \/srv\/webapps\/rb-owncloud\/production\/releases\/1\/public\/apps\/user_ldap\/lib\/access.php#733","level":3,"time":"2016-05-19T15:57:31+00:00","method":"POST","url":"\/","user":"--"}

Just user_ldap

mysql oc_ldap_user_mapping
mysql> select * from oc_ldap_user_mapping;
| ldap_dn | owncloud_name | directory_uuid |
+-----------------------------------------------+-------------------+-------------------+
| cn=firstname lastname,cn=users,dc=xxx,dc=xxxx | firstname.lastname | firstname.lastname |
+-----------------------------------------------+-------------------+-------------------+

**Comment by sd-demon** [comment]
Owncloud 8.2 also affected -.-

**Comment by PVince81** [comment]
@blizzz @davicente

**Comment by davicente** [comment]
@isaiespino @sd-demon I cannot reproduce. I have tested with 9.0.2 and 8.2 and works to me, users retrieved correctly and those log errors don't appear from AD
As I can see in the LDAP configuration, you have applied some LDAP filters. I'm thinking if the problem could be in those filters. Could you test with the default filters in a fresh instalation and see if it fails? just to discard that affects.
I'm available too in #owncloud-dev (IRC) if you have more details to reproduce it.

**Comment by blizzz** [comment]
There is no check happening when $user is null. LDAP backend's user manager will return that if no corresponding entry can be found for the provided DN that comes right from LDAP. Could not guess why it behaves like this (missing displayname attribute? should not behave like this. Filter/Base settings? Should not return such users in first place). Adding null check is one thing, but understanding what is going on there is more worth. I have nothing to test/reproduce currently.

**Comment by sd-demon** [comment]
file: user_ldap/lib/access.php
located in function isDNPartOfBase($dn, bases);
i dont know why but this could not work:

you wont find: "CN=Search Daemon,CN=Users,DC=foo,DC=bar"
in CN="Search Daemon",CN="Users",DC="rb",DC="intern"


`my bugfix is:  $base = str_replace ( '"' , '' , $base ); `
than everything works as expected

**Comment by davicente** [comment]
@sd-demon, if I'm not wrong, what you suggest shouldn't do anything, because previously it calls $this->sanitizeDN method, and there it makes this replacement:  '\"' => '\5c22',   -> so, it there shouldn't be any quotes at that time. Do you agree?

**Comment by sd-demon** [comment]
@davicente 

Well yes i agree, but thats what it does on my server - downloaded as archive from https://owncloud.org/

Original DN without the replace: 
 	CN="Users",DC="rb",DC="intern"
with the replace:
	CN=Users,DC=rb,DC=intern

Thats was the strange behavior on OC 8 and OC9.0.2 

regards Demon

**Comment by davicente** [comment]
@isaiespino @sd-demon I have created a branch called 24733_AD_users_list_keep_loading from stable9 with the fix suggested by @blizzz. Could you test if it solves the problem for you?

**Comment by sd-demon** [comment]
@davicente me? well yes, need to do the dev setup ... so wait

**Comment by sd-demon** [comment]
@davicente 
`LDAP Login: Could not get user object for DN cn=my name,cn=users,dc=rb,dc=intern. Maybe the LDAP entry has no set display name attribute?`

Checked Config twice, same as on our production (with my own patch)

**Comment by davicente** [comment]
@sd-demon so, now the problem is when you try to login, not showing the list of AD users, right?
In that case, in user_ldap::checkPassword method is trying to get the user with de DN, but without sanitize it previously. In this case it could cause what you have said before. 
So, your proposal would make sense here.

**Comment by PVince81** [comment]
This PR from @butonic adds a check for null users, in case they aren't found https://github.com/owncloud/core/pull/25062. It might not solve the issue but at least would avoid such errors.
Well, the PR would only log the failing user and carry on.

**Comment by PVince81** [comment]
Please try again with 9.0.3 or 9.0.4RC1 which contains the fix from https://github.com/owncloud/core/issues/25062

If the problem persists, please reopen.
