### ISSUE TITLE
if DAV clients log in via username and token, the session is killed

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/core#24730]
### Steps to reproduce
1. Generate a token
2. Configure your sync client with user:token
3. Start syncing

### Expected behaviour
The sync clients can authenticate successfully and a browser session is created (#24543 will fix that)

### Actual behaviour
The sync client can authenticate successfully, but as soon as the token is validated (can happen on login and on subsequent requests) the session is killed as the login password is wrong (when creating the session token the login password is actually a token).

The problematic code is here https://github.com/owncloud/core/blob/65eae43ab122bf1d04a5d6f8bee8e8b5ec439276/apps/dav/lib/Connector/Sabre/Auth.php#L106

A session token is created on successful client login. However, if the client uses a token instead of a password, we'd need to restore (decrypt) the login password first and then create the session token.

cc @LukasReschke

**Comment by PVince81** [comment]
Looks rather critical to me

**Comment by ChristophWurst** [comment]
This is tricky. I thought that we could kill session tokens for token-authenticated clients. However, the ``last_login_check`` timestamp that prevent checking the password/user enabled state on every request is saved to the session. Hence, we'd need to have sessions for those clients too (php sessions, not session tokens to be clear). But then we run into another problem as the current implementation would assume there is a session token for an active php session and as there is none, the user will be logged out.

I have to re-think this.

**Comment by PVince81** [comment]
> I have to re-think this.

I hope this won't require big code changes ?

**Comment by ChristophWurst** [comment]
https://github.com/owncloud/core/pull/24973 in conjunction with creating session tokens for clients (we do that already) should be enough for now.

**Comment by PVince81** [comment]
Tested, works :+1:

**Comment by PVince81** [comment]
@nickvergessen can you redo a quick test since you were having issues ?

**Comment by ChristophWurst** [comment]
@PVince81 please comment on the PR ;-)

**Comment by PVince81** [comment]
Too many tabs...
