### ISSUE TITLE
File Locked

### ISSUE THREAD

**Issue by felixxarcom** [owncloud/core#24737]
Hi,

On my owncloud a user copy a folder with data in and directly rename the folder without sync or before syn with owncloud server.

This directory never sync totally with server and when we try to open a file into this directory from web appear this message:

Some idea to unlock this files?
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception>
<s:message>
"SGQ QUALITAT/SGQ DOC/00 DOCS GENERALS QUALITAT/00 Actes de Reunió de G.Qualitat/16-02-11 Reunió Qualitat - copia" is locked
</s:message>
</d:error>

All users that sync this folder into subforders chain receive the same, your windows client owncloud is always trying syncing to server. At moment my last option is owncloud windows client per owncloud windows client disabling this folder of syncing 

Thanks a lot for any good suggestion

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Cent OS 5**:

**Apache/nGinx:**

**Database:** MySQL

**PHP version:** v5.4.xx

**ownCloud version:** (see ownCloud admin page) v9.0.0 stable

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
First try upgrading to 9.0.2 to get the latest fixes.

While in maintenance mode, `delete from oc_file_locks`.

Was there a PHP timeout involved at some point ? The locks shouldn't stay forever like this.

**Comment by PVince81** [comment]
@icewind1991

**Comment by RealRancor** [comment]
Related / dup: https://github.com/owncloud/core/issues/20380 ?

**Comment by PVince81** [comment]
Closing as duplicate, it is likely the ajax cron problem and there was no feedback anyway
