### ISSUE TITLE
Ability to cancel two factor auth

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/core#24745]
### Steps to reproduce
1. Log in
2. See 2FA challenge page

### Expected behaviour
There should be a button/link to log out the current user.

### Actual behaviour
2FA is enforced, the only way to cancel it is clearing cookies.

**ownCloud version:**
9.1.0.2

cc @PVince81 @LukasReschke

**Comment by nickvergessen** [comment]
Should we have the cancel only on the "select challenge" page, or also on the challenge itself?

On the other hand I think when someone successfully logged in as a different user, we don't need to make it too easy ;)

**Comment by ChristophWurst** [comment]
I'd say on both pages. But maybe not as prominent as the ``Verify`` button, but something like a small link underneath the provider form.
