### ISSUE TITLE
Give an option to hide the user's name who the calendar is shared from

### ISSUE THREAD

**Issue by RikuXan** [owncloud/core#24747]
Would it be possible to add an option that changes the calendar's display name in the left sidebar of the calendar overview screen, so that it does not display the calendar's owner for shared calendars?

For somewhat long calendar names, the name display results in the text being cut off by the sidebar which looks sloppy. Alternatively, the display name could also be line wrapped to solve this.

**Comment by RealRancor** [comment]
Hi,

please re-open in https://github.com/owncloud/calendar/issues where the issue tracker of the calendar app is located.

**Comment by RikuXan** [comment]
I did actually open it in owncloud/calendar first, I was told to re-open it here. From what I was told as a reason, it depends on where the displayName is actually created, in the client calendar app, or on the CalDAV backend. Would you know how this works?

**Comment by RealRancor** [comment]
Maybe they didn't understand your issue correctly? If i understand you correctly you only want to hide that name because its sometimes its too long and has display issues in the calendar app?

Then adding an option to hide a username is just a dirty workaround from my PoV.

**Comment by RikuXan** [comment]
That is true, so you think adding a line wrap if the line is cut off would be a better idea? That would definitely be part of the client app, as far as I understand it then.

**Comment by RealRancor** [comment]
That is probably something you should discuss with the developers of the calendar app. :-)

**Comment by georgehrke** [comment]
@RealRancor The problem is that the caldav server does not allow changing the displayname of a shared calendar. If this was implemented, @RikuXan could simply remove the name of the owner or change the order of calendar name and owner however they like to.

**Comment by georgehrke** [comment]
which makes this a dup of https://github.com/owncloud/core/issues/22176

**Comment by RealRancor** [comment]
@georgehrke Still the calendar app could handle the current situation and add a linebreak in between the received display name or am i wrong?

**Comment by georgehrke** [comment]
That would be possible in theory, but I don't want to start messing with the displayname. This will give us headache when this issue is fixed in 9.1 and we still try to support 9.0.

**Comment by RealRancor** [comment]
Ah, ok. Didn't thought about this.
