### ISSUE TITLE
Direct file access over url

### ISSUE THREAD

**Issue by Raunter** [owncloud/core#24746]
how can I disable, direct access to files through url as shown below ?

http://grupoboiadeiro.com.br/owncloud/remote.php/webdav/123268parafusoecia.pdf

Version 9.0.2
Database: MySql

Actual Behavior : Download of file
Expected Behavior: prompt for credentials or deny direct access

**Comment by RealRancor** [comment]
@Raunter Close your browser and open the URL again. There Basic Auth is used so this stays in your browser until you're closing it. Afterwards the credentials are asked (just tested that from here).

If you need further help please ask such questions at either the forums or the users mailinglist: https://owncloud.org/support/

**Comment by Raunter** [comment]
@RealRancor thank you
