### ISSUE TITLE
Can't 

### ISSUE THREAD

**Issue by sbrl** [owncloud/core#24758]
### Steps to reproduce
1. Attempt to log into owncloud

### Expected behaviour
Tell us what should happen

I am able to log into ownCloud successfully.

### Actual behaviour
Tell us what happens instead

I am unable to login. Hitting enter has no effect at all.

### Server configuration
**Operating system**: Linux starbeamrainbowlabs.com 2.6.32-042stab111.12 #1 SMP Thu Sep 17 11:38:20 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

**Web server:** `nginx version: nginx/1.10.0
built with OpenSSL 1.0.2d 9 Jul 2015
TLS SNI support enabled
configure arguments: --with-cc-opt='-g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' --prefix=/usr/share/nginx --conf-path=/etc/nginx/nginx.conf --http-log-path=/var/log/nginx/access.log --error-log-path=/var/log/nginx/error.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --with-debug --with-pcre-jit --with-ipv6 --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module --with-http_auth_request_module --with-http_addition_module --with-http_dav_module --with-http_geoip_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module --with-http_v2_module --with-http_sub_module --with-http_xslt_module --with-stream --with-stream_ssl_module --with-mail --with-mail_ssl_module --with-threads --add-module=/build/nginx-X1enFe/nginx-1.10.0/debian/modules/nginx-auth-pam --add-module=/build/nginx-X1enFe/nginx-1.10.0/debian/modules/nginx-dav-ext-module --add-module=/build/nginx-X1enFe/nginx-1.10.0/debian/modules/nginx-echo --add-module=/build/nginx-X1enFe/nginx-1.10.0/debian/modules/nginx-upstream-fair --add-module=/build/nginx-X1enFe/nginx-1.10.0/debian/modules/ngx_http_substitutions_filter_module`

**Database:** SQLite

**PHP version:** `PHP 7.0.6-13+donate.sury.org~wily+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies`

**ownCloud version:** From `status.php`: `{"installed":true,"maintenance":false,"version":"9.0.0.19","versionstring":"9.0.0","edition":""}`

Note that I can't log in, so I am unable to check the admin page.

**Updated from an older ownCloud or fresh install:** I have updated from the 8.x branch and it _was_ working, but now it is not.

**Where did you install ownCloud from:** owncloud.org, manually

**Signing status (ownCloud 9.0 and above):** I have no idea what you are asking for here.

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

I am unable to login to access the requested page.

**List of activated apps:**

```Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.5
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - logreader: 1.1.2
  - music: 0.3.11
  - notifications: 0.2.3
  - ojsxc: 3.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.8.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
Disabled:
  - announcementcenter
  - encryption
  - files_versions
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc7nu0qgtr6j",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "trusted_domains": [
            "admin.starbeamrainbowlabs.com",
            "owncloud.starbeamrainbowlabs.com"
        ],
        "datadirectory": "\/srv\/owncloud-data",
        "overwrite.cli.url": "https:\/\/admin.starbeamrainbowlabs.com\/owncloud",
        "dbtype": "sqlite3",
        "version": "9.0.0.19",
        "installed": true,
        "forcessl": false,
        "mail_from_address": "postasaurus",
        "mail_smtpmode": "sendmail",
        "mail_domain": "starbeamrainbowlabs.com",
        "forceSSLforSubdomains": false,
        "theme": "",
        "ldapIgnoreNamingRules": false,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```

**Are you using external storage, if yes which one:** ?

**Are you using encryption:** Nope

**Are you using an external user-backend, if yes which one:** Nope

### Client configuration
**Browser:** 	51.0.2704.54 (Official Build) beta (64-bit)

**Operating system:** `Linux Snowflake 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

#### Web server error log
```
Nothing recent that's related.
```

#### ownCloud log (data/owncloud.log)
```
Nothing recent.
```

#### Browser log
```
oc.js?v=6660072…:1 Uncaught SyntaxError: Unexpected token <
shareconfigmodel.js?v=6660072…:24 Uncaught ReferenceError: oc_appconfig is not defined(anonymous function) @ shareconfigmodel.js?v=6660072…:24(anonymous function) @ shareconfigmodel.js?v=6660072…:89
js.js?v=6660072…:203 Uncaught TypeError: Cannot read property 'substring' of undefinedfilePath @ js.js?v=6660072…:203(anonymous function) @ viewer.js?v=6660072…:4
ojsxc.js?v=6660072…:167 Uncaught TypeError: Cannot read property 'match' of undefined
```

Note that every document request in the network console returns a 200. Also note that `oc.js` returns the login page for some seriously strange reason.

Here's my nginx config:

```
server {
	listen	80;
	listen	[::]:80;
	listen	443 ssl http2;
	listen	[::]:443 ssl http2;
	
	server_name	owncloud.starbeamrainbowlabs.com;
	ssl_certificate		/etc/letsencrypt/live/owncloud.starbeamrainbowlabs.com-0001/fullchain.pem;
	ssl_certificate_key	/etc/letsencrypt/live/owncloud.starbeamrainbowlabs.com-0001/privkey.pem;
	
	add_header	strict-transport-security	"max-age=31536000;";
	add_header	x-xss-protection			"1; mode=block";
	#add_header	x-content-type-options		"nosniff";
	add_header	x-robots-tag				"none";
	#add_header	x-frame-options				"sameorigin";
	
	index	index.html index.php;
	root	/srv/owncloud;
	
	error_page 403 /core/templates/403.php;
	error_page 404 /core/templates/404.php;
	
	rewrite ^/.well-known/carddav /remote.php/carddav/ permanent;
	rewrite ^/.well-known/caldav /remote.php/caldav/ permanent;
	
	location / {
		rewrite ^ /index.php$uri;
		
		try_files $uri $uri/ =404;
	}
	
	location /jabber/bosh {
		proxy_pass			http://[::]:5280;
		proxy_set_header	x-proxy-server		nginx;
		proxy_set_header	host				admin.starbeamrainbowlabs.com;
		proxy_set_header	x-originating-ip	$remote_addr;
	}
	
	location ~ \.php(?:$|/) {
		fastcgi_split_path_info ^(.+\.php)(/.+)$;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
		fastcgi_param HTTPS on;
		fastcgi_param modHeadersAvailable true; #Avoid sending the security headers twice
#		fastcgi_pass unix:/var/run/php5-fpm.sock;
		fastcgi_pass unix:/run/php/php7.0-fpm.sock;
		fastcgi_intercept_errors on;
	}

	location ~* \.(?:svg|gif|png|html|ttf|woff|ico|jpg|jpeg)$ {
		try_files $uri /index.php$uri$is_args$args;
		# Optional: Don't log access to other assets
		#access_log off;
	}
	
	location ~* \.(?:css|js)$ {
		try_files $uri /index.php$uri$is_args$args;
	}
	
	location ~ ^/(build|tests|config|lib|3rdparty|templates|data)/ {
		deny all;
	}
	
	#location ^~/.well_known/acme-challenge/ {
	#	allow all;
	#}
	
	location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
		deny all;
	}
	
	#location ~ /\. {
	#	deny all;
	#}
	#
	#location ^~ /.well_known/ {
	#	allow all;
	#}
	
	location ~* data/ {
		deny all;
	}
}
```

**Comment by RealRancor** [comment]
@sbrl Please always update to the latest available oC version (which is currently 9.0.2) before reporting bugs / issues. In this case oC 9.0.2 fixes this issue with PHP 7.0.6: https://github.com/owncloud/core/pull/24343

**Comment by sbrl** [comment]
@RealRancor If I run `sudo -u www-data ./occ upgrade` it prints `ownCloud is already latest version`, even though `sudo -u www-data ./occ --version` prints `ownCloud version 9.0.0`.

**Comment by RealRancor** [comment]
@sbrl ./occ upgrade won't check for new oC versions nor won't it download and install new updates. Please see the doc.owncloud.org how to do a manual update

**Comment by sbrl** [comment]
@RealRancor Right. I'll do one in a little bit - I'm a bit busy right now.

**Comment by sbrl** [comment]
@RealRancor That seems to have solved the problem. Thanks!

In future, I think it would be helpful if `occ upgrade` did tell you about minor releases. Naturally I expect an upgrade command to do _all_ upgrade, not just major ones. Example: `apt-get`.

**Comment by RealRancor** [comment]
@sbrl Please read the description of the ``occ upgrade`` command when running just ``occ``:

> run upgrade routines after installation of a new release. The release has to be installed before.

**Comment by sbrl** [comment]
@RealRancor Oh, wow! I managed to misread that a grand total on half a dozen times then. I find that this kind of thing happens fairly frequently :(
