### ISSUE TITLE
3rd party pear.php.net/package/Archive_Tar  is outdated 

### ISSUE THREAD

**Issue by coldtobi** [owncloud/core#24755]
Repository [1] : 1.4.0 (or 1.4.1, not clear commit message)

Upstream[2] : 1.4.2

Changelog: 
1.4.2
- Fix reading of archives with files > 8GB
- Performance optimizations
- Do not try to call require_once on PEAR.php if it has already been loaded by the autoloader

[1] https://github.com/owncloud/3rdparty/tree/master/pear/archive_tar
[2] http://pear.php.net/package/Archive_Tar/

**Comment by butonic** [comment]
Confirmed:

> We have an issue with downloading large files. A user shares a couple of files by public link.
>
> When downloading all files (17,9 GB), the download completes but the archive (.tar on my Mac) is corrupt. The same happens when you select all files (8.9 GB) from the same folder
> 
> However, when I select one or more smaller files (1 GB), the archive extracts without an error. 
> 
> We’ve tested this with MacOS Yosemite / El Capitan and Windows 10, all 64-bit. 
> 
> We didn’t find anything suspicious in our logs, so hopefully you can help us out :) 
> 
> We’re running Owncloud 8.2.5 on Apache 2.2.15, behind HAproxy 1.5.14, all CentOS 6.8.

cc @DeepDiver1975 @McNetic for zipstreamer stuff

**Comment by DeepDiver1975** [comment]
> for zipstreamer stuff

zipstreamer is unrelated to archive tar

**Comment by butonic** [comment]
is it? I thought on mac we fell back to tar for streamed downloads of multiple files ...

**Comment by DeepDiver1975** [comment]
This is tarstreamer - yer another component

**Comment by PVince81** [comment]
Did we update this on master ?

**Comment by PVince81** [comment]
Please reopen if this is still an issue with 10.0.4
