### ISSUE TITLE
Upload problem for files more than 60-80MB 

### ISSUE THREAD

**Issue by alichakery** [owncloud/core#24761]
### Steps to reproduce
Upload any file more than 60-80MB

### Expected behaviour
Files to be uploaded 

### Actual behaviour
It gets stuck at the end of the upload (when the upload bar goes to the end) and nothing happens...

And sometime it says : Can not get the file info 

Note: We have increased the upload size to 2048M in php.ini and we double checked it according to OC documentation.

Note2: We have SFTP external storage but we do all of our tests on local storage and we have added SFTP storages to each account separately  not globally.

### Server configuration
**Operating system**: 
CloudLinux

**Web server:** 
LiteSpeed

**Database:**
MariaDB

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
8.2.5

**Updated from an older ownCloud or fresh install:**
8.2.4

**Where did you install ownCloud from:**
OC.org

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here :


It redirects me back to the home (files)

```

**List of activated apps:**
All default plugins Plus :
Calendar
Notes
Bookmarks
contacts
News
Direct Menu

```

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'domain.com',
  ),
  'overwrite.cli.url' => 'http://domain.com',
  'dbtype' => 'mysql',
  'version' => '8.2.5.2',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'dddd_,
  'logtimezone' => 'UTC',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SFTP (But I also installed a fresh OC without any changes and it acts the same.)

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Safari/Chrome/FireFox/Opera

**Operating system:**
Mac OSX / Windows / Windows Server 2012

#### Web server error log
```
Error logs from litespeed
2016-05-22 23:12:01.244 [INFO] [216.246.6.148:64565:HTTP2-3] File not found [/home/uzer/public_html/404.shtml]

Domlogs:
216.246.6.148 - - [22/May/2016:23:00:09 +0200] "GET /cp/index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 205 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
216.246.6.148 - - [22/May/2016:23:02:48 +0200] "POST /cp/index.php/apps/files/ajax/upload.php HTTP/1.1" 200 273 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
216.246.6.148 - - [22/May/2016:23:05:32 +0200] "GET /cp/index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 205 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
216.246.6.148 - - [22/May/2016:23:08:35 +0200] "POST /cp/index.php/heartbeat HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
216.246.6.148 - - [22/May/2016:23:07:48 +0200] "POST /cp/index.php/apps/files/ajax/upload.php HTTP/1.1" 200 273 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
216.246.6.148 - - [22/May/2016:23:10:35 +0200] "GET /cp/index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 205 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
216.246.6.148 - - [22/May/2016:23:11:59 +0200] "GET /cp/phpinfo.php HTTP/1.1" 200 27116 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
216.246.6.148 - - [22/May/2016:23:12:01 +0200] "GET /favicon.ico HTTP/1.1" 404 1148 "https://domain.com/cp/phpinfo.php" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
216.246.6.148 - - [22/May/2016:23:12:25 +0200] "POST /cp/index.php/apps/files/ajax/upload.php HTTP/1.1" 200 273 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
216.246.6.148 - - [22/May/2016:23:15:11 +0200] "GET /cp/index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 205 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"

Full last 10 lines from the php error logs:
[07-Feb-2016 16:44:00 UTC] PHP Fatal error:  Out of memory (allocated 19398656) (tried to allocate 16512 bytes) in /home/uzer/public_html/cp/lib/private/image.php on line 512
[07-Feb-2016 16:44:01 UTC] PHP Fatal error:  Out of memory (allocated 82051072) (tried to allocate 12384 bytes) in /home/uzer/public_html/cp/lib/private/image.php on line 424
[07-Feb-2016 16:44:05 UTC] PHP Fatal error:  Out of memory (allocated 110624768) (tried to allocate 12384 bytes) in /home/uzer/public_html/cp/lib/private/image.php on line 424
[07-Feb-2016 16:44:06 UTC] PHP Fatal error:  Out of memory (allocated 62128128) (tried to allocate 16512 bytes) in /home/uzer/public_html/cp/lib/private/image.php on line 512
[07-Feb-2016 16:44:06 UTC] PHP Fatal error:  Out of memory (allocated 82051072) (tried to allocate 12384 bytes) in /home/uzer/public_html/cp/lib/private/image.php on line 424
[07-Feb-2016 16:44:11 UTC] PHP Fatal error:  Out of memory (allocated 111935488) (tried to allocate 12384 bytes) in /home/uzer/public_html/cp/lib/private/image.php on line 424
[07-Feb-2016 16:44:12 UTC] PHP Fatal error:  Out of memory (allocated 116916224) (tried to allocate 12384 bytes) in /home/uzer/public_html/cp/lib/private/image.php on line 424
[09-May-2016 14:38:23 UTC] PHP Fatal error:  Class 'OC\Encryption\Util' not found in /home/uzer/public_html/cp/lib/private/server.php on line 99
[21-May-2016 23:23:00 UTC] PHP Fatal error:  Class 'OC\Hooks\PublicEmitter' not found in /home/uzer/public_html/cp/lib/private/user/manager.php on line 49
[21-May-2016 23:25:40 UTC] PHP Fatal error:  Class 'Sabre\DAV\CorePlugin' not found in /home/uzer/public_html/cp/3rdparty/sabre/dav/lib/DAV/Server.php on line 231

```

#### ownCloud log (data/owncloud.log)
```
Fatal	webdav	Exception: {"Message":"HTTP\/1.1 423 \"My File Box\/Music\/Old\/Cat Stevens - Greatest Hits - Album.mp3-chunking-3202066672-14-7\" is locked","Exception":"OC\\Connector\\Sabre\\Exception\\FileLocked","Code":0,"Trace":"#0 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('Cat Stevens - G...', Resource id #351)\n#1 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('My File Box\/Mus...', Resource id #351, NULL)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#5 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/home\/uzer\/public_html\/cp\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#7 \/home\/uzer\/public_html\/cp\/remote.php(137): require_once('\/home\/uzer\/p...')\n#8 {main}","File":"\/home\/uzer\/public_html\/cp\/lib\/private\/connector\/sabre\/directory.php","Line":121}	2016-05-22T15:51:56+00:00
Fatal	webdav	

Exception: {"Message":"HTTP\/1.1 423 \"My File Box\/Music\/Old\/Cat Stevens - Greatest Hits - Album.mp3-chunking-3202066672-14-7\" is locked","Exception":"OC\\Connector\\Sabre\\Exception\\FileLocked","Code":0,"Trace":"#0 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('Cat Stevens - G...', Resource id #351)\n#1 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('My File Box\/Mus...', Resource id #351, NULL)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#5 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/home\/uzer\/public_html\/cp\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#7 \/home\/uzer\/public_html\/cp\/remote.php(137): require_once('\/home\/uzer\/p...')\n#8 {main}","File":"\/home\/uzer\/public_html\/cp\/lib\/private\/connector\/sabre\/directory.php","Line":121}	2016-05-22T15:50:17+00:00
Fatal	webdav	

Exception: {"Message":"HTTP\/1.1 423 \"My File Box\/Music\/Old\/Cat Stevens - Greatest Hits - Album.mp3-chunking-3202066672-14-7\" is locked","Exception":"OC\\Connector\\Sabre\\Exception\\FileLocked","Code":0,"Trace":"#0 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('Cat Stevens - G...', Resource id #351)\n#1 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('My File Box\/Mus...', Resource id #351, NULL)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#5 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/home\/uzer\/public_html\/cp\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#7 \/home\/uzer\/public_html\/cp\/remote.php(137): require_once('\/home\/uzer\/p...')\n#8 {main}","File":"\/home\/uzer\/public_html\/cp\/lib\/private\/connector\/sabre\/directory.php","Line":121}	2016-05-22T15:49:08+00:00
Fatal	webdav

	Exception: {"Message":"HTTP\/1.1 423 \"My File Box\/Music\/Old\/Cat Stevens - Greatest Hits - Album.mp3-chunking-3202066672-14-7\" is locked","Exception":"OC\\Connector\\Sabre\\Exception\\FileLocked","Code":0,"Trace":"#0 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1053): OC\\Connector\\Sabre\\Directory->createFile('Cat Stevens - G...', Resource id #351)\n#1 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('My File Box\/Mus...', Resource id #351, NULL)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#5 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/home\/uzer\/public_html\/cp\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#7 \/home\/uzer\/public_html\/cp\/remote.php(137): require_once('\/home\/uzer\/p...')\n#8 {main}","File":"\/home\/uzer\/public_html\/cp\/lib\/private\/connector\/sabre\/directory.php","Line":121}	2016-05-22T15:48:04+00:00
Error	files	Upload error: 3 - 


The uploaded file was only partially uploaded	2016-05-22T15:02:45+00:00


Fatal	webdav	Exception: {"Message":"HTTP\/1.1 503 Encryption not ready: Module with id: OC_DEFAULT_MODULE does not exist.","Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Code":0,"Trace":"#0 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(82): OC\\Connector\\Sabre\\File->get()\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#4 \/home\/uzer\/public_html\/cp\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/home\/uzer\/public_html\/cp\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#6 \/home\/uzer\/public_html\/cp\/remote.php(137): require_once('\/home\/uzer\/p...')\n#7 {main}","File":"\/home\/uzer\/public_html\/cp\/lib\/private\/connector\/sabre\/file.php","Line":293}	2016-05-22T07:06:05+00:00

```

Any Help is really appreciated !

**Comment by PVince81** [comment]
Ok, from the logs I see you are uploading with the web UI.
It is likely that you are running into timeouts for some reason.

**Comment by nickvergessen** [comment]
Not a timeout but `PHP Fatal error:  Out of memory`

**Comment by alichakery** [comment]
I did every server side changes that I knew to solve this issue like increasing the execution time to 1 hour ... but still no luck ...

What would you recommend ?

Thanks

**Comment by RealRancor** [comment]
@alichakery You need to raise the ``memory_limit`` of your PHP (hint: php.ini) to a sane value. Currently it seems this is configured to around 18M where oC needs a minimum of 128M

**Comment by alichakery** [comment]
@RealRancor .. Well as I remember my memory limit was 256M !!!!

Let me check and I will update you with the results ...

**Comment by alichakery** [comment]
My memory_limit is 512 MB ... please take a look at this screenshot :

![screen shot 2016-05-23 at 15 09 01](https://cloud.githubusercontent.com/assets/12240218/15471968/0b2a107c-20f9-11e6-8a18-8c99fb3801e6.png)

**Comment by alichakery** [comment]
I switched my PHP to PHP7 using CloudLinux php selector now I have two new errors in owncloud log :

`Error	PHP	Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2 "No such file or directory") at /home/qkjbnmoj/cloud.fatholladzade/lib/private/db/connection.php#54	2016-05-23T13:11:43+00:00

Error	PHP	Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2 "No such file or directory") at /home/qkjbnmoj/cloud.fatholladzade/lib/private/db/connection.php#54	2016-05-23T13:11:42+00:00`

**Comment by alichakery** [comment]
Any help would be appreciated !

**Comment by PVince81** [comment]
Please note that this is a bug tracker not a support platform
For support, please check http://owncloud.org/support

**Comment by alichakery** [comment]
I am not looking to get support here.. I am trying to solve this bug if it is possible ... 

I noticed that almost no one has the same environment as mine (CloudLinux+LiteSpeed) so I kind of doubt if this issue get solved ... (since both CloudLinux and LiteSpeed are paid services)

Anyways thank you for the reply.

**Comment by PVince81** [comment]
512MB should be enough.

The memory error appears in image.php in the code that generates previews, are you uploading huge images ?

CC @georgehrke @oparoz

**Comment by RealRancor** [comment]
I think the memory limit is a misleading. Those where from February.

**Comment by alichakery** [comment]
Actually no.. I am trying to upload ZIP files... 

It is funny because in 3 previous versions I was able to upload files till 513M , then I increased the limit to 2048 in php settings... and then an update was out.. after the update everything went crazy like this.

please note that 60M is ridiculous ... My server is powerful enough to handle such a task (64GB of Ram and 6 core intel CPU) ...

I would be able to provide you with a test hosting account + a fresh instal of OC for further investigations.

It is a long time which I am using this script and it helped me a lot.. this is the least thing that I can do for OC.

Thanks again

**Comment by alichakery** [comment]
Would you please take a look at my php configurations and see if everything is properly configured from this aspect?

Thank you

**Comment by alichakery** [comment]
We have been investigating this issue and our server admins replied back with this:

Do you have any suggestions please?

--------

It looks like the file upload has aborted in the midway and the application error logs didn't show any relevant information. The Apache error logs show the following during the process,

****************************************************************************
2016-05-27 06:22:07.908 [INFO] [193.170.69.37:62742] File not found [/home/sf6aws4/public_html/account/status.php]
2016-05-27 06:22:07.908 [INFO] [193.170.69.37:62742] File not found [/home/sf6aws4/public_html/404.shtml]
2016-05-27 06:22:07.926 [INFO] [193.170.69.37:62742-1#APVH_5.9.157.245:443_mysecure.space] File not found [/home/sf6aws4/public_html/account/owncloud/status.php]
2016-05-27 06:22:07.926 [INFO] [193.170.69.37:62742-1#APVH_5.9.157.245:443_mysecure.space] File not found [/home/sf6aws4/public_html/404.shtml]
2016-05-27 06:22:39.910 [INFO] [193.170.69.37:62743] File not found [/home/sf6aws4/public_html/account/status.php]
2016-05-27 06:22:39.911 [INFO] [193.170.69.37:62743] File not found [/home/sf6aws4/public_html/404.shtml]
2016-05-27 06:22:39.929 [INFO] [193.170.69.37:62743-1#APVH_5.9.157.245:443_mysecure.space] File not found [/home/sf6aws4/public_html/account/owncloud/status.php]
2016-05-27 06:22:39.929 [INFO] [193.170.69.37:62743-1#APVH_5.9.157.245:443_mysecure.space] File not found [/home/sf6aws4/public_html/404.shtml]
2016-05-27 06:23:11.911 [INFO] [193.170.69.37:62744] File not found [/home/sf6aws4/public_html/account/status.php]
2016-05-27 06:23:11.911 [INFO] [193.170.69.37:62744] File not found [/home/sf6aws4/public_html/404.shtml]
2016-05-27 06:23:11.928 [INFO] [193.170.69.37:62744-1#APVH_5.9.157.245:443_mysecure.space] File not found [/home/sf6aws4/public_html/account/owncloud/status.php]
2016-05-27 06:23:11.928 [INFO] [193.170.69.37:62744-1#APVH_5.9.157.245:443_mysecure.space] File not found [/home/sf6aws4/public_html/404.shtml]
****************************************************************************

**Comment by alichakery** [comment]
any ideas ?

**Comment by alichakery** [comment]
Ok, I have to say that LiteSpeed support is just great, TBH I have not seen any support as good as LiteSpeed sofar ...


Although this issue was not related to the web server but they helped us to find the problem.

This was related to LVE Manager of CloudLinux that "I/O limit" should has been set to unlimited.

I have to say that LiteSpeed is 100% compatible with OwnCloud and I would really recommend using this wevserver because it would provide you with a great performance while unlike NGiNX you would not have to deal with many configurations. 

It is also compatible with Plesk, cPanel and DirectAdmin control panels.

A big thumbs up for them and anyone who tried to help me here.

Best Regards,
Ali.

**Comment by alichakery** [comment]
Ok and to make it more complete regarding uploading files (larger than 513MB) , additional setting is needed to be changed in LiteSpeed Control Panel.

This is where this setting is located :
LiteSpeed ControlPanel  -> Server -> Tuning -> Max Request Body Size (bytes): 500M

This is an additional security option to prevent DoS attacks and you should change it to whatever value which you need in addition to changing phpini -or- .htaccess directives regarding upload file size.

I hope it helps.

Best Regards,
Ali.
