### ISSUE TITLE
Ability to query for user defined values using occ

### ISSUE THREAD

**Issue by juliushaertl** [owncloud/core#24770]
### Steps to reproduce
1. Try to debug user defined values of apps

### Expected behaviour
It should be easy to get userdefined values for the apps installed using the occ command.

### Actual behaviour
It is not possible at the moment.

### Server configuration

**ownCloud version:** 9.1.0.3

**Comment by PVince81** [comment]
Are you referring to the `./occ config` commands ?

Seems it would be nice to have it for `oc_preferences` too.

@nickvergessen

**Comment by nickvergessen** [comment]
partly, but yes I can see cases for that as well

**Comment by juliushaertl** [comment]
@PVince81: Right, just like config:app:get, it would be nice to have the following for user values:

```
config:user:get <app> <uid> <name>
config:user:set <app> <uid> <name> <value>
config:user:delete <app> <uid> <name>
config:user:list <app> <uid>
```

**Comment by nickvergessen** [comment]
PR in https://github.com/owncloud/core/issues/25083

List: `user:setting <uid> <app>`
Get: `user:setting <uid> <app> <key>`
Set: `user:setting <uid> <app> <key> --value "new value"`
Delete: `user:setting <uid> <app> <key> --delete`
