### ISSUE TITLE
Cannot move files using new dav endpoint 

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#24776]
### Steps to reproduce:

Having a file called prueba.txt and a folder called Documents in the admin root folder user account do:
1. Using admin user connect using cadaver to the new webdav endpoint (/remote.php/dav/files/admin)
2. Move prueba.txt into documents.
```
mv prueba.txt Documents
```

### Expected behaviour:
"prueba.txt" is moved into "Documents".

### Actual behaviour
Moving `/remote.php/dav/files/admin/prueba.txt' to `/remote.php/dav/files/admin/Documents/prueba.txt':  failed:
404 Not Found

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Current master
{"installed":true,"maintenance":false,"version":"9.1.0.2","versionstring":"9.1.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```


```

### Client configuration

Cadaver.

**Comment by PVince81** [comment]
@DeepDiver1975
