### ISSUE TITLE
Token generated through /token/generate route does now show up in devices

### ISSUE THREAD

**Issue by danimo** [owncloud/core#24784]
### Steps to reproduce
1. Using master, run `curl -X POST -d user=Admin -d password=Password -d name="MyDevice" https://owncloud/index.php/token/generate`
2. successfully run `curl -X PROPFIND -u 'Admin:<token>' https://owncloud/remote.php/webdav/`
3. Check "My Devices" in Personal Settings

### Expected behaviour
I see "MyDevice" in the "My Devices" view.

### Actual behaviour
The "My Devices" view remains empty.

### Server configuration
**Operating system**: Ubuntu 

**Web server:** Apache

**Database:** MariaDB

**PHP version:** `PHP 5.5.9-1ubuntu4.13`

**ownCloud version:** (see ownCloud admin page)
master as of `c10d8a37f70ecdfeea49b646cd2af96e12895c52`

**Updated from an older ownCloud or fresh install:**

fresh

**Where did you install ownCloud from:**

git

**Comment by ChristophWurst** [comment]
fixed by #24748
