### ISSUE TITLE
Token from /token/generate route does now show in Devices view

### ISSUE THREAD

**Issue by danimo** [owncloud/core#24785]
### Steps to reproduce
1. run `curl -X POST -d user=Admin -d password=Password -d name="My Device" https://owncloud/index.php/token/generate`
2. Check Devices in user's Personal Settings.

### Expected behaviour

Device "My Device" shows up in Personal Settings under "Devices"

### Actual behaviour

Device "My Device" does not show up.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** PHP 5.5.9-1ubuntu4.13

**ownCloud version:** master (`c10d8a37f70ecdfeea49b646cd2af96e12895c52`)

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** git

**Signing status (ownCloud 9.0 and above):** good

**Comment by ChristophWurst** [comment]
Could you please post the response too? Do you get a new token?

**Comment by danimo** [comment]
I do, and that token also works with WebDAV operations, like so:

`curl -X PROPFIND -u 'Admin:<token>' https://owncloud/remote.php/webdav/`

**Comment by ChristophWurst** [comment]
Found it. The token is generated for the UID 'admin', whereas the login name is 'Admin'. I need to find out why we're listing tokens for 'Admin' though, I intended to list tokens for the currently logged in user's UID, not the login name.
