### ISSUE TITLE
2006 MySQL server has gone away – Owncloud 9.0.2.2

### ISSUE THREAD

**Issue by Buzut** [owncloud/core#24782]
I know this issue is not that new because I've googled and have seen it [here](https://github.com/owncloud/core/issues/15407) and [there](https://forum.owncloud.org/viewtopic.php?t=26712). But I've tried to modify my DB config and it doesn't look to solve the problem.

The actual log:
`[Mon May 23 14:49:19.209231 2016] [:error] [pid 7788] [client 83.61.36.110:55589] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)\n#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(989): Doctrine\\DBAL\\Driver\\PDOStatement->execute(Array)\n#2 /var/www/owncloud/lib/private/db/connection.php(205): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\n#3 /var/www/owncloud/lib/private/lock/dblockingprovider.php(262): OC\\DB\\Connection->executeUpdate('UPDATE `oc_file...', Array)\n#4 [internal function]: OC\\Lock\\DBLockingProvider->releaseAll()\n#5 {main}\n\nNext Doctrine\\DBAL\\Driver\\PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93\nStack trace:\n#0 /var/www/owncloud/3rdparty/doctrine/db in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115`

My config:
- Ubuntu 16.04,
- oC 9.0.2.2,
- Apache 2.4.18,
- PHP 7.0.4,
- MariaDB 10.01

MariaDB conf:

    #
    # * Fine Tuning
    #
    max_connections         = 100
    connect_timeout         = 5
    wait_timeout            = 600
    max_allowed_packet      = 512M
    thread_cache_size       = 128
    sort_buffer_size        = 4M
    bulk_insert_buffer_size = 16M
    tmp_table_size          = 32M
    max_heap_table_size     = 32M

It seem that `wait_timeout` and `max_allowed_packet`, which based upon what I've read, are the usual suspects, have quite reasonable values.

**Comment by nickvergessen** [comment]
Well `MySQL server has gone away` is more a support issue then a bug in our software.
Please try googling and otherwise post your question in the forum: https://forum.owncloud.org/
