### ISSUE TITLE
 Bogus downgrade error message related to browser session

### ISSUE THREAD

**Issue by APTX** [owncloud/core#24793]
ownCloud stores a version in a user session which can lead to an error similar to:

> Downgrading is not supported and is likely to cause unpredictable issues (from 9.0.2.2 to 9.0.1.3)

I'm not really sure how I got ownCloud in such a state but clearing ownCloud cookies resolved the issue. While I was getting this error in one browser ownCloud continued to work in other browsers.

A probable cause of this issue was discovered on IRC:

> <BernhardPosselt> APTX: https://github.com/owncloud/core/blob/master/lib/private/legacy/util.php#L367
> <BernhardPosselt> APTX: https://github.com/owncloud/core/blob/master/lib/private/legacy/util.php#L1419
> <BernhardPosselt> so what happens is that they use the version from the current session
> <BernhardPosselt> your cookie is used to open a specific session
> <BernhardPosselt> which might still include the old one
> <BernhardPosselt> using the version from the session is probably not a good idea

**Comment by nickvergessen** [comment]
Well downgrading is not supported :speak_no_evil:
When your session has a higher version then what you now have locally, you did one.

Sure the message is odd, but sounds like low priority to me.

**Comment by APTX** [comment]
I did not downgrade anything. No files were changed since the upgrade to 9.0.2 (last modified date matches). version.php contains:
> $OC_Version = array(9,0,2,2);
$OC_VersionString = '9.0.2';

As I mentioned I only got the error in one browser. I don't know how the session got the way it did on that one browser. In the other browsers I could run the integrity check and it passed.

**Comment by PVince81** [comment]
Won't fix unless someone volunteers to spend the time to debug this corner case.
