### ISSUE TITLE
Login by e-mail is only possible with browsers

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/core#24791]
Thanks to https://github.com/owncloud/core/pull/24389 it's possible to log in to ownCloud by e-mail address. However, that enhancement was only added to the LoginController, which means only browser sessions are affected. As a user I want to be able to configure clients with the same credentials I use for the browser login. It is unexpected that the same credentials work on the browser, but not on APIs.

### Steps to reproduce
1. Configure e-mail address
2. Configure your (sync) client and use the e-mail address as username

### Expected behaviour
Login should succeed.

### Actual behaviour
Login fails.

**ownCloud version:**
9.1.0

cc @DeepDiver1975 @PVince81 
also @MTRichards as this is a requirement of #23458

**Comment by PVince81** [comment]
@ChristophWurst any update on this ? Is it difficult ?

CC @DeepDiver1975 @dragotin

**Comment by DeepDiver1975** [comment]
I'll take care of that
