### ISSUE TITLE
Search provider class not found in file search

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24803]
### Steps

1. Go to files app
1. Open the search field on the top right
1. Type in any string
1. Wait for results

### Expected result
Results appear eventually, or "not found" message

### Actual result
Spinner spins forever

### Logs
```
{"reqId":"6wUpiwUMaYXhK4Yzhe06","remoteAddr":"127.0.0.1","app":"PHP","message":"Class 'OCP\\Search\\Provider' not found at \/srv\/www\/htdocs\/owncloud\/lib\/private\/Search\/Provider\/File.php#32","level":3,"time":"2016-05-24T09:41:09+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/search?query=wel&inApps%5B%5D=files&page=1&size=30","user":"admin"}
```

### Versions
Observed on 9.1 pre-alpha git master 452542747cf895eaac69d7ca486a2dcb655785d0
Regression from v9.0.2

@georgehrke

**Comment by nickvergessen** [comment]
File is not PSR-4, will fix

**Comment by georgehrke** [comment]
Hm, works for me with PHP 5.6. Is the behavior different for PHP 7?

**Comment by PVince81** [comment]
I have php5-5.6.21-1.1.x86_64

**Comment by nickvergessen** [comment]
@georgehrke not on latest master
