### ISSUE TITLE
Download as ZIP spinner out of place

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24802]
### Steps

1. Upload several files in the web UI
1. Select files
1. Click on "Download" in the toolbar above the column headers

### Expected result
Spinner looks alright

### Actual rresult
Spinner looks out of place / too big

@skjnldsv can you have a look ? Are these different spinner sizes for the new one ?

@owncloud/designers

**Comment by alpsleonardo** [comment]
Hi @PVince81, can I take a look in this issue?

**Comment by alpsleonardo** [comment]
@PVince81 I fixed, what do I have to do to pull request, I am not on the contributors's list yet.

**Comment by skjnldsv** [comment]
@alpsleonardo see #24822 this is already fixed. :)

**Comment by alpsleonardo** [comment]
@skjnldsv Thank you! How can I become a contributor?

**Comment by skjnldsv** [comment]
For this pr or you mean owncloud org in general?

**Comment by alpsleonardo** [comment]
Yes :)

On Thu, May 26, 2016 at 12:35 PM John Molakvoæ <notifications@github.com>
wrote:

> For this pr or you mean owncloud org in general?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/core/issues/24802#issuecomment-221924941>
>
-- 
Leonardo Alps
Software Developer

**Comment by skjnldsv** [comment]
Yes to which one of my option? X)

**Comment by alpsleonardo** [comment]
Sorry @skjnldsv, I meant owncloud org in general

**Comment by skjnldsv** [comment]
You need to see with someone like @PVince81 @jancborchardt @DeepDiver1975  or @BernhardPosselt

**Comment by alpsleonardo** [comment]
Okay @skjnldsv ! Thank you so much for your help! I will send a email to them

**Comment by skjnldsv** [comment]
Or come to the irc! freenode#owncloud-dev!

**Comment by PVince81** [comment]
@alpsleonardo best is to send your first pull request from your fork and then the process will start from there :smile:

**Comment by alpsleonardo** [comment]
Thank you @PVince81 I will do that
