### ISSUE TITLE
[OC 9.0.2.2] User count don't reflect users who use imap auth as backend

### ISSUE THREAD

**Issue by xshadow** [owncloud/core#24810]
### Steps to reproduce
1. Use owncloud 9.0.2.2 with user_external imap authentification
2. Login in with an account that is authenticated via ldap
3. Login as Admin, go to users, see the user count
### Expected behaviour

The number of users should reflect the count of all users who have a directory on the server.
### Actual behaviour

Only the users that are created via owncloud are counted.
### Server configuration

**Operating system**: Debian 8

**Web server:** Apache 2.4

**Database:** mysql  Ver 14.14 Distrib 5.5.49,

**PHP version:** mysql  Ver 14.14 Distrib 5.5.49,

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** gz-package from download page 

**Signing status (ownCloud 9.0 and above):**  passed 

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.1
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - galleryplus: 15.0.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
Disabled:
  - encryption
  - external
  - files_external
  - gallery
  - user_ldap
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'mail_domain' => 'foobar',
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'cloud.foobar.net',
  ),
  'datadirectory' => '/var/www/cloud.foobar.net/htdocs/data',
  'overwrite.cli.url' => 'https://cloud.foobar.net',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => 'cloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'cloud',
  'dbpassword' => 'XXX',
  'logtimezone' => 'UTC',
  'default_language' => 'de',
  'installed' => true,
  'memcache.local' => '\OC\Memcache\APCu',
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{imap.strato.de:993/imap/ssl}',
        1 => 'foobar',
      ),
    ),
  ),

);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes , Imap
### Client configuration

**Browser:** FF46.0.1

**Operating system:**  Debian 8

**Comment by nickvergessen** [comment]
> Only the users that are created via owncloud are counted.

not entirely correct. It lists all users from any known backends. The problem is that the IMAP backend doesn't allow user iteration IIRC.

**Comment by xshadow** [comment]
Thanks for that information. 

But wouldn't it be useful to count the directories that are present on the server and reflect the user count ?

**Comment by nickvergessen** [comment]
Well that is somewhat misleading then, when you can not manage the users, also pagination and total number of items are then off leading to other issues. That is why we ended up with the current situation.

**Comment by mmccarn** [comment]
In case this helps...

I modified OC/apps/user_external/lib/imap.php to add new imap users to a group.

In 'Users', the 'Everyone' group shows all user accounts with the wrong count, but the imap group shows an accurate count of imap users.
![userst](http://snag.gy/vWSz8u.jpg)

Starting around line 45 in OC/apps/user_external/lib/imap.php:


    if($mbox !== FALSE) {
        imap_close($mbox);
        $uid = mb_strtolower($uid);
        $this->storeUser($uid);
        /** 
        * Add the two OC_Group lines below to put all new imap users into my-imap-group
        */
        OC_Group::createGroup('my-imap-group');
        OC_Group::addToGroup('$uid,'my-imap-group');
        return $uid;


This will give you integrity check errors:
![integrity check warning](https://snag.gy/oLb3iR.jpg)

**Comment by nickvergessen** [comment]
Well for groups we count the user-group assignments, but for "everyone" we iterate over the the user backends and ask for the number of users, but IMAP does not support that, iirc.

**Comment by PVince81** [comment]
Counting the user's homes wouldn't be accurate either some users might not have logged in any more.

Now in OC 10 we have the user account table so it might be possible to use that to count users. This is likely the same as counting home folders where only IMAP users who logged in at least once could be counted.

**Comment by PVince81** [comment]
Olease try again with 10.0.4 where the account table is in place. I expect that the user manager is now able to see all users who have logged in (autoprovisioning)
