### ISSUE TITLE
Update documentation or code for APCu with OwnCloud 9 with PHP 7

### ISSUE THREAD

**Issue by robarchibald** [owncloud/core#24823]
**Background & server setup**
My experience here comes from 2 servers.  My new server is running Ubuntu 16.04 with PHP 7.0 and OwnCloud 9.0.2 on Nginx 1.10.0.  On that server APCu doesn't work unless I set `apc.enable_cli=1`.  My prior server is running Ubuntu 14.04 with PHP 5.5.9 and OwnCloud 8.2.2 on Nginx 1.8.0.  In installed the trusty backport of APCu and it runs fine without having to set `apc.enable_cli=1`

**Confusion: what is really recommended?**
According to @enoch85 in issue https://github.com/owncloud/core/issues/21994, "Redis with PHP 7 
works, and is the preferred cache instead of APCu"

According to https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/caching_configuration.html, APCu is recommended over Redis for memcache.local.  It states "APCu is faster at local caching than Redis. If you have enough memory, use APCu for Memory Caching and Redis for File Locking. If you are low on memory, use Redis for both."

The official documentation seems to be the more complete answer, yes?  If there is a change to recommend Redis, that would be good to update.  

**Install documentation confusion**
If APCu is still the recommendation, I think a change should still be made.  APCu is a bit troublesome to get working under PHP 7 and OwnCloud 9.  In order to get it working, one needs to set `apc.enable_cli=1`.  It was my understanding that patch #21308 was going to fix this so that the cli setting wasn't needed.  All the newest documentation states that this isn't necessary, so I kept pulling my hair out thinking something else was wrong.

I finally went to look at the code at lib/private/memcache/apcu.php.  Here is the line checking for apc.enable_cli under OwnCloud 9: 
```
elseif (!\OC::$server->getIniWrapper()->getBool('apc.enable_cli') && \OC::$CLI) {
```
OwnCloud 8.2 and which I'm running with php5 on another server runs this check:
```
elseif (!ini_get('apc.enable_cli') && \OC::$CLI) {
```
Unfortunately, I'm no expert on php and couldn't figure out how to check the output of `OC::$server->getIniWrapper()->getBool('apc.enable_cli')` from a simple php -a command-line session, but I can tell by process of elimination that OC$CLI is set to true on OwnCloud 9 under php 7 because I could only get past this check by setting `apc.enable_cli=1`.  I was able to verify that `ini_get('apc.enable_cli')` is returning false as expected on my old box.  Hence, I can verify through behavioral testing that:

- Ubuntu 14.04 running OwnCloud 8.2.2 under php 5.5.9 on Nginx 1.8.0.  OC::$CLI === **false**
- Ubuntu 16.04 running OwnCloud 9.0.2 under php 7.0 on Nginx 1.10.0.  OC::$CLI === **true**

**How to fix:**
Because of this, the only way to get past this for me on my Ubuntu 16.04/OwnCloud 9.0.2/php 7.0/Nginx 1.10.0 box was to is to set `apc.enable_cli=1`. According to https://owncloud.org/blog/making-owncloud-faster-through-caching/, this is not supposed to be required starting with 8.1.1.  I see a bunch of issues posted here with APCu not working.  Perhaps these are all the same issue I was having due to the incorrect code or documentation.

Long-term steps to fix are:

- Update documentation for OwnCloud 9 with PHP 7 to set `apc.enable_cli=1`
- Fix whatever code is setting $OC::$CLI to be true while running OwnCloud 9 with PHP 7 on NGINX
- If APCu isn't the recommendation anymore, update the documentation accordingly

To be clear, OwnCloud 9 APCu is working fine for me through setting `apc.enable_cli=1`.  My only goal here is to get clarification so we can help others hitting the same issue.

**Comment by RealRancor** [comment]
Hi,

apc.enable_cli=1 is definitely not needed anymore on such a setup so there might be something else broken in your PHP environment.

**Comment by enoch85** [comment]
Redis handles file locking which APCu doesn't that's why I stated that it's recomended. I don't even use APCu on my server(s) at all - Redis is used and works great!

**Comment by Xenopathic** [comment]
The code that sets `OC::$CLI` has not changed since ownCloud 8.1. You must have some environment change causing ownCloud to think you are running from the CLI, can you get a value from `php_sapi_name()` to confirm this? Note, you will have to run that function from a script executed by your web server, not from the command line.

**Comment by robarchibald** [comment]
Well, this is interesting.  I installed OwnCloud 9 on my Ubuntu 14.04/php 5.5.9/Nginx 1.8.0 box and now its logs are filling up with the "Memcache \OC\Memcache\APCu not available for local cache" message that started this whole journey for me.  So, apparently this isn't a php7 or Nginx 1.10 or Ubuntu 16.04 issue.  I'm going to see if I can figure out how to to do what @Xenopathic  has suggested and get the value of `OC::$CLI` and `OC::$server->getIniWrapper()->getBool('apc.enable_cli')` as well as `php_sapi_name()`.  While apparently the code setting `OC::$CLI` hasn't changed since OwnCloud 8.1, the code to get `apc.enable_cli` has recently changed, so maybe my process of elimination wasn't correct and the troublesome value was that one.  In any case, I'll report back my findings.  Thanks!

**Comment by RealRancor** [comment]
@robarchibald Just to clarify:

This issue is about getting the ``Memcache \OC\Memcache\APCu not available for local cache`` in your logfile. You're not getting a ``No memory cache has been configured. To enhance your performance please configure a memcache if available.`` in your admin backend?

If yes you can directly close here after you have set your loglevel config.php option from 0 or 1 to the default of 2. A memcache is not needed for occ or cron and you also don't get this message in the default loglevel.

**Comment by robarchibald** [comment]
This has been most instructive for me.  I created a simple php page which output some debug info.  Lo and behold, `\OC\Memcache\APCu::isAvailable()` was returning true on both servers, even without setting `apc.enable_cli=1`.  So all was working fine on the web... but wait, there's more.  Add to that the information provided by @RealRancor, and I finally understand what was happening.  

In my logs I saw a bunch of `{cli} Memcache \OC\Memcache\APCu not available for local cache` error messages.  Well, those were happening because my install script uses the occ command-line to install the application.  Cron.php runs from the command-line too.  Because I was doing multiple installs trying to get it all to work right, I saw lots of errors and thought these errors were coming from the web UI.  Turns out they were coming from the usage of occ.  There was also an error every time cron.php runs.  When I set `apc.enable_cli=1` the errors went away since APCu was now available to the command-line too.  But, obviously I don't care whether APCu is available for the occ command.  I'm not sure whether I should care if APCu is available for cron.php.

Now that I fully understand, I would recommend that either:

- The `{cli} Memcache \OC\Memcache\APCu not available for local cache` error not be shown for command-line interaction if it indeed isn't needed **OR**
- Documentation should show that `apc.enable_cli` should be set to 1 if it is important that APCu be available from the command-line

Phew!  Thanks for the help!

**Comment by robarchibald** [comment]
FYI @RealRancor, my loglevel was indeed set to 1.  From looking at the place where the `{cli} Memcache \OC\Memcache\APCu not available for local cache` is logged, it looks like this message is correctly logging at loglevel=1.  

I would argue that the info message is not very clear since it makes it seem as if APCu isn't working when it is working fine for the web.  So, perhaps the better suggestion for my recommendation 1 is: change the info message for the cli when APCu isn't working so that people don't think there is a problem.

**Comment by Xenopathic** [comment]
For some memcaches it is important that occ also has it enabled, hence the INFO level log message. Unlike for the web interface, it's not considered an error from the CLI, but that message will still be printed.

So, is there an issue here that needs fixing?

**Comment by RealRancor** [comment]
@Xenopathic If its important for some memcaches together with occ the only thing what needs to be fixed is the documentation. I'm reading that fact for the very first time.

**Comment by robarchibald** [comment]
Yes, I'd agree that the only thing needed to change here is the documentation, and possibly the info message to make it more clear that this isn't an error

**Comment by RealRancor** [comment]
@robarchibald Completely forgot about this. From my PoV this is still just a documentation issue so i've created https://github.com/owncloud/documentation/issues/2546

I think this one here can closed as documentation stuff is normally tracked in a separate repository.

**Comment by robarchibald** [comment]
Agreed that this can be closed. Thanks fo the help and clarification

**Comment by RealRancor** [comment]
Write-up done in a FAQ entry on central:

https://central.owncloud.org/t/memcache-oc-memcache-apcu-not-available-for-local-distributed-cache/1241

Hope i got everything right.

**Comment by robarchibald** [comment]
Looks good. Thanks for the follow-up!

 

Blessings,

Rob Archibald
