### ISSUE TITLE
Path already shared with this group when not shared

### ISSUE THREAD

**Issue by rroseselavy42** [owncloud/core#24821]
It looks like in some sort of circumstance, a folder can be not shared, but still be marked as shared. I'm still getting details on how this happened but it seems like there should be some sort of check to prevent this from happening. 

### Steps to reproduce
1.  Unshare group
2. Reshare group
3. Path already shared with this group

### Expected behaviour
Tell us what should happen
When unshared and reshared I should be able to share again. 
### Actual behaviour
Tell us what happens instead
Share is not shared again and says that it is. 
### Server configuration
**Operating system**:
Debian 8 Jessie
**Web server:**
Server version: Apache/2.4.10 (Debian)
**Database:**
mysql  Ver 15.1 Distrib 10.0.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
9.0.2
**Updated from an older ownCloud or fresh install:**
updated
**Where did you install ownCloud from:**
Owncloud Repo
**Signing status (ownCloud 9.0 and above):**
good
No errors have been found.
**List of activated apps:**
```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
```

**The content of config/config.php:**

```json
{
   "system": {
        "instanceid": "",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
           ***REDACTED***
        ],
        "datadirectory": "\/srv\/owncloud\/",
        "overwrite.cli.url": "***REDACTED***",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "EST",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "owncloud",
        "mail_domain": ".org",
        "mail_smtphost": "",
        "mail_smtpport": "587",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/tmp\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "forcessl": true,
        "asset-pipeline.enabled": true,
        "loglevel": 2,
        "maintenance": false,
        "ldapIgnoreNamingRules": false,
        "theme": "",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "log_rotate_size": 2097152
    }
}
```
                           
**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by PVince81** [comment]
@owncloud/sharing

**Comment by PVince81** [comment]
Please try again with 9.0.4, likely related to https://github.com/owncloud/core/issues/25359
