### ISSUE TITLE
[occ commands] Cannot set log level to minimum through occ command (CLI)

### ISSUE THREAD

**Issue by davicente** [owncloud/core#24829]
### Steps to reproduce

1. go to terminal and execute following command:
`sudo -u www-data ./occ log:manage --level 0`

### Expected behaviour
Log level should be set to 0 level
`Enabled logging backend: owncloud
Log level: Debug (0)
Log timezone: UTC`

### Actual behaviour
Log level remains in previous level
`Enabled logging backend: owncloud
Log level: Info (1)
Log timezone: UTC`

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**
"9.1.0.4","versionstring":"9.1.0 pre alpha","edition":""

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
No logs

### Client configuration

**browser**

![logslevel](https://cloud.githubusercontent.com/assets/752240/15533223/ef01879c-2263-11e6-8451-5f1ef8ca2606.JPG)

**Comment by nickvergessen** [comment]
`./occ config:system:set loglevel --value="0" --type=int` can be used as a work around.
Will fix the other command though
