### ISSUE TITLE
Ability to upload a new version of a file through the web interface (replace files)

### ISSUE THREAD

**Issue by nekohayo** [owncloud/core#24857]
From what I can see on an Owncloud 9 instance, there is no way at all to upload a new "version" of a file. The "+" button doesn't have that (and is not contextual to your selection anyway), the toolbar doesn't have that when a file is selected with its checkbox, and the selected file sidebar's "Versions" section doesn't have that either.

Ideally this should be in the sidebar's "Versions" section, something that says "Drag and drop a file here to upload a new version while keeping the same name" or something.

**Comment by RealRancor** [comment]
Works here as expected:

- Create local file called "foo.txt"
- Enter text "bar" into it
- Open https://demo.owncloud.org
- Upload file via the "+" button
- Change content of file "foo.txt" locally to "foobar"
- Upload file via the "+" button
- Get "1 File conflict" popup with the content "Which files do you want to keep? If you select both versions, the copied file will have a number added to its name."
- Choose "New file"
- Check "Details" of the file and got a new version of it

**Comment by nekohayo** [comment]
I tried out your steps, the issue for me is that 1) it replaces the file but does not create a new "version" in the sidebar  2) you can't do that from the Versions tab of the sidebar, which is where I expected to be able to have a drop area + "upload a new version" button, for discoverability.

**Comment by RealRancor** [comment]
@nekohayo As you havn't provided any infos about your used oC version and so one (hint: shown issue template) this might be a bug in your older used version.

**Comment by PVince81** [comment]
Overwriting a file from the web UI or Webdav should always create a new version.
However keep in mind that the versions app has an algorithm that "thins out" versions, so older versions might get discarded automatically. See https://doc.owncloud.org/server/9.0/admin_manual/configuration_files/file_versioning.html#controlling-file-versions-and-aging

**Comment by PVince81** [comment]
Converting to enhancement request.

@owncloud/designers see the proposed additional workflow in the original post

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/8063. We could provide an option to always keep all versions.

Another alternative is to write a new versions app that behaves differently.
