### ISSUE TITLE
Remember redirect_url when logging in with a second factor

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/core#24850]
While solving the 2FA challenge the redirect url is lost.

### Steps to reproduce
1. Enable a 2FA provider
2. Go to a ownCloud page that needs login
3. Get redirected to the login page (redirect url is encoded in the url)
4. Solve 2FA challenge

### Expected behaviour
The user should be redirected to the URL that was requested originally.

### Actual behaviour
The user is redirected to the files app.

**ownCloud version:**
9.1.0

ref #24559

**Comment by PVince81** [comment]
Yeah, was just about to raise this :smile:

**Comment by ChristophWurst** [comment]
@PVince81 what options do we have to remember that URL apart from putting it into all URLs? The problem is that 2FA providers create/send the form with the challenge token. If they don't send the request_url param there, it will break browser-based client login :-/
How about storing it in the session?
