### ISSUE TITLE
Preview thumbnail is not available sorting deleted files

### ISSUE THREAD

**Issue by davitol** [owncloud/core#24866]
### Steps to reproduce

1. Delete some files with thumbnail preview
2. Go to Deleted files page
3. Click on 'deleted time' in order to sort them

### Expected behaviour

The thumbnail preview should be visible

### Actual behaviour

The trashbin background icon is not shown properly 

The thumbnail preview is lost

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**
""9.1.0.5","versionstring":"9.1.0 beta 1","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```

```
### Client configuration

**browser**

Firefox & other browsers

![deletethumbnails](https://cloud.githubusercontent.com/assets/10596560/15582482/936f0972-2371-11e6-9856-96c245f16164.gif)

**Comment by PVince81** [comment]
this was fixed a long time ago, should work fine in 9.0.5 and 9.1.1
