### ISSUE TITLE
Trashbin background icon is not shown properly using Edge as browser

### ISSUE THREAD

**Issue by davitol** [owncloud/core#24865]
### Steps to reproduce
1. Go to deleted files menu using Edge as browser and delete the files of the trashbin
### Expected behaviour

The trashbin background icon should be shown
### Actual behaviour

The trashbin background icon is not shown properly 

Note: It happens just after deleting the files. If the screen is refreshed, the background icon is shown ok
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**
""9.1.0.5","versionstring":"9.1.0 beta 1","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```

```
### Client configuration

**browser**

 Edge

![screen shot 2016-05-26 at 16 48 10](https://cloud.githubusercontent.com/assets/10596560/15578768/110ff248-2362-11e6-9ee1-9c67f099bb1f.png)

Firefox & other browsers

![screen shot 2016-05-26 at 16 48 17](https://cloud.githubusercontent.com/assets/10596560/15578777/192e3ac0-2362-11e6-9e50-e4d24d06473a.png)

@owncloud/designers

**Comment by davitol** [comment]
Same behaviour in other menus:

e.g Share by link
Edge
![screen shot 2016-05-26 at 17 00 31](https://cloud.githubusercontent.com/assets/10596560/15579177/c8f13092-2363-11e6-92b3-e8d1b45d71fe.png)



Other browser:

![screen shot 2016-05-26 at 17 03 00](https://cloud.githubusercontent.com/assets/10596560/15579170/c1f98e92-2363-11e6-9027-c35b12e1abea.png)

**Comment by PVince81** [comment]
moved to more general UX group ticket: https://github.com/owncloud/core/issues/27578
