### ISSUE TITLE
Weird behaviour of the LDAP status gauge

### ISSUE THREAD

**Issue by davitol** [owncloud/core#24860]
### Steps to reproduce
1. Go to Admin Page menu and set a LDAP configuration in server tab
2.  Click on Detect Base DN Button (Green light is set in the gauge)
3. Browse to Users tab and click on back button to go back to the Server tab
### Expected behaviour

The green light should be kept in Server Tab
### Actual behaviour

The green light is lost
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:"9.1.0.3","versionstring":"9.1.0 pre alpha","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```

```
### Client configuration

**browser**

 Firefox

![ldapweirdwr](https://cloud.githubusercontent.com/assets/10596560/15570688/986835dc-2337-11e6-9961-5046d3ad01c1.gif)

@davicente @owncloud/ldap

**Comment by PVince81** [comment]
moved to grouped UX ticket: https://github.com/owncloud/user_ldap/issues/69
