### ISSUE TITLE
Unable to auto log in after enabling "External Storage" app

### ISSUE THREAD

**Issue by FiveYellowMice** [owncloud/core#24879]
### Steps to reproduce
1. Enable the "External Storage" app via GUI.
2. Close the browser.
3. Open the browser again, visit my ownCloud page.

### Expected behaviour
Logged in and shows my files if I checked the "remember" checkbox last time, or shows log in page that has a "remember" checkbox.

### Actual behaviour
Not logged in, shows log in page but the "remember" checkbox has disappeared.

![screenshot_20160528_164955](https://cloud.githubusercontent.com/assets/9077203/15625697/491059c4-24f4-11e6-9ce0-fb3f1fb35a2c.png)

### Server configuration
**Operating system:** Fedora 23

**Web server:** Nginx-reverse-proxied Apache 2.4.18

**Database:** MariaDB 10.0.23

**PHP version:** 5.6.21

**ownCloud version:** 8.2.4

**Updated from an older ownCloud or fresh install:** Updated from an older version

**Where did you install ownCloud from:** Package manager

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

Nothing, it redirects me to `/index.php/apps/files/`.
```

**List of activated apps:** 

Enabled:
  - activity: 2.1.4
  - files: 1.2.1
  - files_external: 0.3.0
  - files_pdfviewer: 0.7.1
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1

Disabled:
  - encryption
  - external
  - user_external
  - user_ldap

**The content of config/config.php:**

```
{
    "system": {
        "log_type": "syslog",
        "datadirectory": "\/var\/lib\/owncloud\/data",
        "updatechecker": false,
        "check_for_working_htaccess": false,
        "asset-pipeline.enabled": false,
        "assetdirectory": "\/var\/lib\/owncloud",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "apps_paths": [
            {
                "path": "\/usr\/share\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/owncloud\/apps",
                "url": "\/apps-appstore",
                "writable": true
            }
        ],
        "instanceid": "ocb14ro2uvpg",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.fiveyellowmice.com"
        ],
        "overwrite.cli.url": "http:\/\/owncloud.fiveyellowmice.com",
        "dbtype": "mysql",
        "version": "8.2.4.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "appstore.experimental.enabled": false,
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}
```

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** WebDAV

### Client configuration
**Browser:** Chrome 51.0.2704.63 (64-bit), 50.0.2661.89, 50.0.2661.95

**Operating system:** Arch Linux, Android 6.0.1, iOS 9.3.2

#### Web server error log
```
[Sun May 22 03:38:02.965516 2016] [auth_digest:notice] [pid 18356] AH01757: generating secret for digest authentication ...
[Sun May 22 03:38:02.965882 2016] [http2:warn] [pid 18356] AH02951: mod_ssl does not seem to be enabled
[Sun May 22 03:38:02.972919 2016] [lbmethod_heartbeat:notice] [pid 18356] AH02282: No slotmem from mod_heartmonitor
[Sun May 22 03:38:03.233836 2016] [mpm_prefork:notice] [pid 18356] AH00163: Apache/2.4.18 (Fedora) PHP/5.6.21 configured -- resuming normal operations
[Sun May 22 03:38:03.233889 2016] [core:notice] [pid 18356] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Sat May 28 06:38:17.073720 2016] [:error] [pid 13793] [client ::1:57166] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction' in /usr/share/php/Doctrine/DBAL/Driver/PDOStatement.php:91\nStack trace:\n#0 /usr/share/php/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)\n#1 /usr/share/php/Doctrine/DBAL/Connection.php(989): Doctrine\\DBAL\\Driver\\PDOStatement->execute(Array)\n#2 /usr/share/owncloud/lib/private/db/connection.php(203): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)\n#3 /usr/share/owncloud/lib/private/lock/dblockingprovider.php(261): OC\\DB\\Connection->executeUpdate('UPDATE `*PREFIX...', Array)\n#4 [internal function]: OC\\Lock\\DBLockingProvider->releaseAll()\n#5 {main}\n\nNext exception 'Doctrine\\DBAL\\Driver\\PDOException' with message 'SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction' in /usr/share/php/Doctrine/DBAL/Driver/PDOStatement.php:93\nStack trace:\n#0 /usr/s in /usr/share/php/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
```

#### ownCloud log (data/owncloud.log)

Empty.

#### Browser log

None.

**Comment by RealRancor** [comment]
@FiveYellowMice You can close here as this is the expected behavior:

> Some apps like files_external or encryption will disable the Stay logged in checkbox.

https://doc.owncloud.org/server/9.0/user_manual/webinterface.html

**Comment by FiveYellowMice** [comment]
I see. #13335 added it. Hope this can be fixed in a later version because it's not a good UX.

**Comment by RealRancor** [comment]
@FiveYellowMice You still can create a new feature request for that (e.g. only disable the auto login if an external storage not supporting it is enabled).
