### ISSUE TITLE
Turn off admin warnings or hide. 

### ISSUE THREAD

**Issue by FriedCircuits** [owncloud/core#24878]
I have owncloud setup with IIS front end for HTTPS using URL rewriting. So owncloud is not directly public facing. Is there a way to stop the warnings messages about SSL. Or have a settings in the admin page that SSL is offloaded, so owncloud knows about it. 

For example:

The "Strict-Transport-Security" HTTP header is not configured to at least "15768000" seconds.

### Server configuration
**Operating system**:
Ubuntu Server 14.04
**Web server:**
apache2 and IIS(SSL off loading) on Win 2012 R2
**Database:**
mysql 5.7
**PHP version:**
php 5.6
**ownCloud version:** (see ownCloud admin page)
9.0.2
**Updated from an older ownCloud or fresh install:**
Updated from older
**Where did you install ownCloud from:**
ppa

**Comment by DeepDiver1975** [comment]
There is no way to disable these checks. But even with IIS the warning is still valid - right?

**Comment by RealRancor** [comment]
> But even with IIS the warning is still valid - right?

Exactly. ownCloud is checking the existence of HSTS on its main URL (e.g. examplce.com) so this one (probably IIS) needs to provide the HSTS headers.

**Comment by FriedCircuits** [comment]
Thank you. I didn't think that ownCloud was checking the main URL. I found some sites on how to configure HSTS on IIS. I will give that a try.
