### ISSUE TITLE
can´t fix  integrity check errors

### ISSUE THREAD

**Issue by BearTi** [owncloud/core#24884]
Hi,

I recently update to versoin 9 of the ownCloud server and hosting it on a shared webspace.

I deleted all file (except the config and data folder) and then copied the new (version 9) files on my server. Everything went well, I can reach my server, log in and so on.

My problem ist, that I get an error message regarding the integrity check:

```
Results
=======
- core
	- INVALID_HASH
		- core/doc/admin/_sources/configuration_files/collaborative_documents_configuration.txt
		- core/doc/admin/_static/img/note_pencil.svg
		- core/doc/admin/_static/img/warning.svg
		- core/doc/admin/_static/style.css
		- core/fonts/LICENSE.txt
		- core/vendor/jquery-migrate/jquery-migrate.js
		- core/vendor/jquery-migrate/jquery-migrate.min.js
		- core/vendor/jsTimezoneDetect/jstz.js
- files_texteditor
	- INVALID_HASH
		- js/vendor/ace/src-noconflict/mode-diff.js
- files_external
	- INVALID_HASH
		- 3rdparty/Dropbox/API.php
```

I can´t fix this problems, even if I copy these files from the original TAR-file, I get these error.

Any idea?
To you need more information?

Thanks

**Comment by RealRancor** [comment]
Have you rescanned the integrity after copy the new files? Also try to fiddel around with the to ansfer mode of your FTP client.

**Comment by BearTi** [comment]
yes, I did a rescan and I tried different ftp clients etc. 

I can't understand why just these files have the integrity problem...

**Comment by LukasReschke** [comment]
Configure your FTP client to use Binary Transfer instead of ASCII transfer.

**Comment by BearTi** [comment]
It worked!

Thanks a lot!
