### ISSUE TITLE
Unable to Find the Code file

### ISSUE THREAD

**Issue by Waqar731** [owncloud/core#24883]
Hi
I have installed latest version of Owncloud successfully on my machine. First of all i got the login screen. Then i successfully login and go to first page after login screen. Now On this page there is a button with the name 'upload file' as can be shown in the screenshot attached below.
My question is that in which file the code behind this upload button is written? Actually i want to customize the code which is written behind the upload button.

Regards
Waqar Hussain

https://fbcdn-sphotos-c-a.akamaihd.net/hphotos-ak-xfp1/v/t35.0-12/13282716_1183289405055413_31947294_o.png?oh=569e921e26fd3bc44030393c34f066db&oe=574BAC18&__gda__=1464581746_5def4d05ac21d9bbf62660cae4e1cfcb

**Comment by RealRancor** [comment]
@Waqar731 The issue tracker is not the place to ask such questions. Please use https://mailman.owncloud.org/mailman/listinfo/devel instead

Please close here and also close the other opened issues in https://github.com/owncloud/documentation/issues/2456 and https://github.com/owncloud/owncloud.org/issues/965

**Comment by RealRancor** [comment]
@DeepDiver1975 Please also close https://github.com/owncloud/apps/issues/2180 and https://github.com/owncloud/apps/issues/2179
