### ISSUE TITLE
keep folders when syncing file shares

### ISSUE THREAD

**Issue by kinesias** [owncloud/core#24890]
Hi guys, 

it's a pity owncloud doesn't keep the parenting folders when syncing file shares!
Especially, when two files in two separate folders have the same names, owncloud doesn't sync them correctly. 

Steps to reproduce
1. make two folders: "folder a" and "folder b"
2. now, put the file "1.png" in each of the two folders
3. share both files "folder a/1.png" and "folder b/1.png" with user "dummy". 

Expected behaviour
Tell us what should happen:
- The sync client should make two folders "folder a" containing the share for "1.png", and "folder b", containting the share for "1.png"

Actual behaviour
Tell us what happens instead:
- it makes a folder "folder a" containting the share for "1.png"
- and it puts another share for "1.png" into the root folder, NOT creating a "folder b". 

owncloud should ALWAYS keep the parenting folders when syncing shared files!

Imagine this situation: 
you have two folders
- the first, named "nice houses", containing "1.jpg", "2.jpg", "3.jpg"
- the second, named "ugly houses", containing "4.jpg", "5.jpg" and "6.jpg"

Now, you share the files 1, 2, 3, 4, 5, 6.jpg with user "james". 
As soon as james syncs his local owncloud folder, he gets the shares for the files
1.jpg, 2.jpg, 3.jpg, 4.jpg, 5.jpg, 6.jpg -- but the are ALL in the SAME folder (the root folder)!!

---> so he can't tell if the houses belong to the folders "nice houses" or "ugly houses"

Any ideas how to fix this problem??

cheers, 
Matthias

Server configuration
Operating system: OSX
Web server: apache
Database: mysql
PHP version: 5.5
ownCloud version (see ownCloud admin page): 9.0.2

**Comment by nickvergessen** [comment]
I don't think that matches the expectation.
Parent folder names are considered private, so when I share a subfile none of the parent names should be leaked with the share.
This is our design decision how folders/parents are handled. When you want to tell people that a house is beautiful you can either leave a comment, or you need to share the folder containing the files.

**Comment by kinesias** [comment]
why should parent folders be private?
This one person has made a nice structure for her files, and when syncing them, her friend just gets the chaos and one messy folder!!

**Comment by kinesias** [comment]
Why did you muzzle me? Even if that is your design decision, it doesn't solve the issue with duplicates being handled weirdly.

**Comment by nickvergessen** [comment]
No one "muzzled" you, as said in the other ticket you can simply reopen this one. I will do that for you now, but we don't need duplicate issues, that only splits the discussion into two places.

**Comment by RealRancor** [comment]
@nickvergessen If a contributor is closing an issue a user  can't re-open the issue

**Comment by nickvergessen** [comment]
Ah, didn't know that, that's odd

**Comment by hodyroff** [comment]
Can this be reproduced with the newest server 9.1.1 and the newest desktop client?
@SamuAlfageme

**Comment by PVince81** [comment]
when sharing a file "ugly houses/4.jpg" alone to another user, it would make it even more confusing if that user receives a folder "ugly houses" that only contains "4.jpg" alone without the other ugly houses. When the two users are talking, the recipient will wonder why they don't see the other files in that same folder. It becomes even more complicated once the recipient start adding new files into "ugly houses" and expect that the other user also receives these files. The other user won't.
And if we do say that whatever is uploaded additionally to "ugly houses", the other user also sees, then what happens if a file with such name already exists there ?

This is getting complicated to manage not only on the code side but also on the user experience side.
