### ISSUE TITLE
conflict when two file shares have the same name 

### ISSUE THREAD

**Issue by kinesias** [owncloud/core#24892]
Steps to reproduce
1. make two folders: "folder a" and "folder b"
2. now, put the file "1.png" in each of the two folders
3. share both files "folder a/1.png" and "folder b/1.png" with user "dummy".

Expected behaviour
The sync client should make two folders "folder a" containing the share for "1.png", and "folder b", containting the share for "1.png"

Actual behaviour
it makes one folder "folder a" containting the share for "1.png"
and it puts another share for "1.png" into the root folder, NOT creating a "folder b".

I don't think this is the correct way of handling fileshare duplicates.

**Comment by nickvergessen** [comment]
Please do not open a duplicate issue, if you want to discuss this further you can reopen the existing one.
