### ISSUE TITLE
Problem updating owncloud on Centos 7 from 8.1.6-13.1 to 8.2.4-1.el7

### ISSUE THREAD

**Issue by Alambra** [owncloud/core#24891]
### Steps to reproduce
1. Installed Owncloud 8.1.6-13.1 on Centos 7 Server
2. yum update
3.

### Expected behaviour
Update of owncloud to newest version

### Actual behaviour
Error Message: 
file /etc/httpd/conf.d/owncloud.conf from install of owncloud-httpd-8.2.4-1.el7.noarch conflicts with file from package owncloud-config-apache-8.1.6-13.1.noarch

### Server configuration
Centos 7

Apache

MariaDB

Owncloud 8.1.6-13.1

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '***CENSORED***',
  'passwordsalt' => '***CENSORED***',
  'secret' => '***CENSORED***',
  'trusted_domains' =>
  array (
    0 => 'www.censoreddomainname.com',
    1 => 'censoreddomainname.com',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://censoreddomainname.com/myowncloud',
  'dbtype' => 'sqlite3',
  'version' => '8.1.6.2',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => '***CENSORED***',
  'mail_smtpmode' => 'sendmail',
  'mail_domain' => '***CENSORED***',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no, but supporting https (TLS)

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by RealRancor** [comment]
@nickvergessen Nothing what can be done from oC side. The OP is mixing oC packages with distro packages (there is no owncloud-http in the official repos) which is causing this issue.

**Comment by maziv** [comment]
I have the same problem. Where can i find a solution for the problem?

**Comment by RealRancor** [comment]
@maziv Don't mixing distro and official owncloud.org packages is the solution for this problem.
