### ISSUE TITLE
Ldap Objectclass Filter not used correctly?

### ISSUE THREAD

**Issue by Constey** [owncloud/core#24910]
### Steps to reproduce
1. Add LDAP Config
2. (Filter) for Userconfig
3. Check the oc_preferences table
### Expected behaviour

Only LDAP Objects with the class "user" should be imported.
### Actual behaviour

There are aswell "contacts" which get imported. They appear in the oc_preferences table with userid = 0, or userid = null;
They dont appear under the Admin -> Users. 
In the owncloud.log it is shown "objectClass=*" for ldap search.
### Server configuration

**Operating system**: Ubuntu 14.04.4 LTS

**Web server:**
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jan 14 2016 17:45:23

**Database:**
mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
9.0.2 (Stable)

**Updated from an older ownCloud or fresh install:**
Updated from 9.0.1 (install)

**Where did you install ownCloud from:**
deb http://download.owncloud.org/download/repositories/stable/xUbuntu_14.04/ /

**Signing status (ownCloud 9.0 and above):**
ok, except modified htacces.

**List of activated apps:**
Enabled:
- _files_videoplayer: 0.9.8
- activity: 2.2.1
- comments: 0.2
- dav: 0.1.6
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_external: 0.5.2
- files_pdfviewer: 0.8.1
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- galleryplus: 15.0.0
- notifications: 0.2.3
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
- user_ldap: 0.8.0

**The content of config/config.php:**

<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => '*******_',
  'passwordsalt' => '**_****_',
  'secret' => '**_****_',
  'trusted_domains' =>
  array (
    0 => '10.0.123.180',
    1 => '**_FQDN**_',
    2 => '10.0.213.16',
  ),
  'datadirectory' => '/media/owncloud',
  'overwrite.cli.url' => '**_FQDN**_',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '**_*******_',
  'logtimezone' => 'UTC',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'memcache.local' => '\OC\Memcache\Memcached',
  'memcache.distributed' => '\OC\Memcache\Memcached',
  'memcached_servers' =>
  array (
    0 =>
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),
  'maintenance' => false,
  'loglevel' => 0,
  'default_language' => 'de_DE',
  'mail_domain' => '**_DOMAIN***_',
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '**_IP*****',
  'mail_smtpport' => '25',
  'theme' => 'drm',
);

**Are you using external storage, if yes which one:** 
local

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
Active Directory (2008 R2 Level)
#### LDAP configuration (delete this part if not used)

+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                 |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                   |
| hasPagedResultSupport         |                                                                                                                                     |
| homeFolderNamingRule          | attr:sAMAccountName                                                                                                                 |
| lastJpegPhotoLookup           | 0                                                                                                                                   |
| ldapAgentName                 | CN=***_,OU=**__,OU=_**_,DC=**__,DC=info                             |
| ldapAgentPassword             | *_\*                                                                                                                                 |
| ldapAttributesForGroupSearch  |                                                                                                                                     |
| ldapAttributesForUserSearch   |                                                                                                                                     |
| ldapBackupHost                |                                                                                                                                     |
| ldapBackupPort                | 389                                                                                                                                 |
| ldapBase                      | OU=***_,DC=**__,DC=info                                                                                                      |
| ldapBaseGroups                | OU=_**_,DC=**__,DC=info                                                                                                      |
| ldapBaseUsers                 | OU=_**_,DC=**__,DC=info                                                                                                      |
| ldapCacheTTL                  | 30                                                                                                                                  |
| ldapConfigurationActive       | 1                                                                                                                                   |
| ldapDynamicGroupMemberURL     |                                                                                                                                     |
| ldapEmailAttribute            | mail                                                                                                                                |
| ldapExperiencedAdmin          | 1                                                                                                                                   |
| ldapExpertUUIDGroupAttr       |                                                                                                                                     |
| ldapExpertUUIDUserAttr        |                                                                                                                                     |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                                      |
| ldapGroupDisplayName          | displayname                                                                                                                         |
| ldapGroupFilter               | (&(objectClass=group)(cn=SG_))                                                                                                      |
| ldapGroupFilterGroups         |                                                                                                                                     |
| ldapGroupFilterMode           | 0                                                                                                                                   |
| ldapGroupFilterObjectclass    |                                                                                                                                     |
| ldapGroupMemberAssocAttr      | member                                                                                                                              |
| ldapHost                      | 10.0.100.21                                                                                                                         |
| ldapIgnoreNamingRules         |                                                                                                                                     |
| ldapLoginFilter               | (&(memberOf:1.2.840.113556.1.4.1941:=CN=***_,OU=Access,OU=Groups,OU=**__,DC=_**_,DC=info)(sAMAccountName=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                                     |
| ldapLoginFilterEmail          | 0                                                                                                                                   |
| ldapLoginFilterMode           | 0                                                                                                                                   |
| ldapLoginFilterUsername       | 1                                                                                                                                   |
| ldapNestedGroups              | 1                                                                                                                                   |
| ldapOverrideMainServer        |                                                                                                                                     |
| ldapPagingSize                | 500                                                                                                                                 |
| ldapPort                      | 389                                                                                                                                 |
| ldapQuotaAttribute            |                                                                                                                                     |
| ldapQuotaDefault              | 40GB                                                                                                                                |
| ldapTLS                       | 0                                                                                                                                   |
| ldapUserDisplayName           | displayName                                                                                                                         |
| ldapUserDisplayName2          |                                                                                                                                     |
| ldapUserFilter                | (&(memberOf:1.2.840.113556.1.4.1941:=CN=**__,OU=Access,OU=Groups,OU=_**_,DC=**_*,DC=info)(objectClass=user))    |
| ldapUserFilterGroups          |                                                                                                                                     |
| ldapUserFilterMode            | 1                                                                                                                                   |
| ldapUserFilterObjectclass     | user                                                                                                                                |
| ldapUuidGroupAttribute        | auto                                                                                                                                |
| ldapUuidUserAttribute         | auto                                                                                                                                |
| turnOffCertCheck              | 0                                                                                                                                   |
| useMemberOfToDetectMembership | 1                                                                                                                                   |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
### Client configuration

**Browser:**
Chrome

**Operating system:**
Win 7 / 10 independent
#### Web server error log

[Mon May 30 06:48:37.944273 2016] [ssl:warn] [pid 5219] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Mon May 30 06:48:37.944388 2016] [mpm_prefork:notice] [pid 5219] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.17 OpenSSL/1.0.1f configured -- resuming normal operations
[Mon May 30 06:48:37.944399 2016] [core:notice] [pid 5219] AH00094: Command line: '/usr/sbin/apache2'
....
access.log:
(KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
**_IP**_ - - [31/May/2016:10:21:19 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 4197 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0"
**_IP**_ - - [31/May/2016:10:21:27 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 1149 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
**_IP**_ - - [31/May/2016:10:21:42 +0200] "POST /heartbeat HTTP/1.1" 200 998 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
**_IP**_ - - [31/May/2016:10:21:42 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 1149 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
**_IP**_ - - [31/May/2016:10:21:49 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 1149 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0"
#### ownCloud log (data/owncloud.log)

{"reqId":"KyMDbY2O9ir3doZxnvdy","remoteAddr":"**_IP**_","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-31T08:14:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"**_User.Name**_"}
{"reqId":"KyMDbY2O9ir3doZxnvdy","remoteAddr":"**_IP**_","app":"user_ldap","message":"Requested attribute memberof not found for cn=security group 2,ou=security,ou=groups,ou=company,dc=domain,dc=info","level":0,"time":"2016-05-31T08:14:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"**_User.Name**_"}
{"reqId":"KyMDbY2O9ir3doZxnvdy","remoteAddr":"**_IP**_","app":"user_ldap","message":"initializing paged search for  Filter objectClass=\* base Array\n(\n    [0] => cn=security group 3,ou=security,ou=groups,ou=company,dc=domain,dc=info\n)\n attr Array\n(\n    [0] => memberOf\n)\n limit 500 offset 0","level":0,"time":"2016-05-31T08:14:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"**_User.Name**_"}
{"reqId":"KyMDbY2O9ir3doZxnvdy","remoteAddr":"**_IP**_","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-31T08:14:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"**_User.Name**_"}
{"reqId":"KyMDbY2O9ir3doZxnvdy","remoteAddr":"**_IP**_","app":"user_ldap","message":"Requested attribute memberof not found for cn=security group 5,ou=security,ou=groups,ou=company,dc=domain,dc=info","level":0,"time":"2016-05-31T08:14:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"**_User.Name**_"}
{"reqId":"KyMDbY2O9ir3doZxnvdy","remoteAddr":"**_IP**_","app":"user_ldap","message":"initializing paged search for  Filter objectClass=\* base Array\n(\n    [0] => cn=security group 1,ou=security,ou=groups,ou=company,dc=domain,dc=info\n)\n attr Array\n(\n    [0] => memberOf\n)\n limit 500 offset 0","level":0,"time":"2016-05-31T08:14:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"**_User.Name**_"}
{"reqId":"KyMDbY2O9ir3doZxnvdy","remoteAddr":"**_IP**_","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-31T08:14:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"**_User.Name**_"}
{"reqId":"KyMDbY2O9ir3doZxnvdy","remoteAddr":"**_IP**_","app":"user_ldap","message":"Requested attribute memberof not found for cn=security group 4,ou=security,ou=groups,ou=company,dc=domain,dc=info","level":0,"time":"2016-05-31T08:14:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"**_User.Name**_"}
{"reqId":"KyMDbY2O9ir3doZxnvdy","remoteAddr":"**_IP**_","app":"user_ldap","message":"initializing paged search for  Filter objectClass=\* base Array\n(\n    [0] => cn=security group 6,ou=security,ou=groups,ou=company,dc=domain,dc=info\n)\n attr Array\n(\n    [0] => memberOf\n)\n limit 500 offset 0","level":0,"time":"2016-05-31T08:14:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"**_User.Name**_"}
{"reqId":"KyMDbY2O9ir3doZxnvdy","remoteAddr":"**_IP**_","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-05-31T08:14:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"**_User.Name**_"}
{"reqId":"KyMDbY2O9ir3doZxnvdy","remoteAddr":"**_IP**_","app":"user_ldap","message":"Requested attribute memberof not found for cn=security group,ou=security,ou=groups,ou=company,dc=domain,dc=info","level":0,"time":"2016-05-31T08:14:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"**_User.Name**_"}
{"reqId":"KyMDbY2O9ir3doZxnvdy","remoteAddr":"**_IP**_","app":"user_ldap","message":"initializing paged search for  Filter objectClass=\* base Array\n(\n    [0] => cn=security group 7,ou=security,ou=groups,ou=company,dc=domain,dc=info\n)\n attr Array\n(\n    [0] => memberOf\n)\n limit 500 offset 0","level":0,"time":"2016-05-31T08:14:20+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"**_User.Name**_"}
#### Browser log

not relevant

**Comment by PVince81** [comment]
@owncloud/ldap

**Comment by PVince81** [comment]
Please reopen in user_ldap app repo if issue persists with 10.0.4 and the latest user_ldap app from marketplace.
