### ISSUE TITLE
Users can log out by killing the session token (unintentionally)

### ISSUE THREAD

**Issue by davitol** [owncloud/core#24911]
### Steps to reproduce
1. Start owncloud session from several browser devices
2. Go to the personal page
3. Delete your own session
### Expected behaviour

The users should not be able to delete their current sessions
### Actual behaviour

The users can log out by killing the session token
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:""9.1.0.5","versionstring":"9.1.0 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```

```
### Client configuration

**browser**

 Chrome

![deletesessions](https://cloud.githubusercontent.com/assets/10596560/15668758/2ff211d2-271d-11e6-9f15-56f058a48d17.gif)

@ChristophWurst

**Comment by ChristophWurst** [comment]
@davitol maybe one of the first sessions you killed was your own, active session. That would log you out, hence the error message.

**Comment by davitol** [comment]
Mmmm could be, but sometime it lets me to delete all the sessions (if i refresh the screen, then I am redirected to ownCloud log in page)

![screen shot 2016-05-31 at 11 01 28](https://cloud.githubusercontent.com/assets/10596560/15669188/451b733a-271f-11e6-9d5a-0ec68d7007cc.png)

**Comment by ChristophWurst** [comment]
The token validity is only checked once per five minutes. This means sometimes you're fast enough and the check happens afterwards, sometimes you are too slow and it happens in between your requests.

**Comment by ChristophWurst** [comment]
Hence the real issue here is that users can log themselves out (unintentionally) by killing the session.

**Comment by davitol** [comment]
@ChristophWurst Let's rename the issue. Thanks for the info

**Comment by nickvergessen** [comment]
@ChristophWurst maybe we should send back a 401 when killing the current session, on ajax requests that will trigger a reload to the login page iirc cc @PVince81

**Comment by davitol** [comment]
Reproduced in "9.1.1.2","versionstring":"9.1.1 RC3","edition":"Enterprise"

![sessiondelete](https://cloud.githubusercontent.com/assets/10596560/18628459/9dc3cbf2-7e60-11e6-8798-fde05f5683d3.gif)

**Comment by PVince81** [comment]
@davitol this was not backported apparently.

**Comment by davitol** [comment]
Already fixed in 10.0.0.1 alpha version, so let's close it
