### ISSUE TITLE
Change text in Personal Page related to Sessions

### ISSUE THREAD

**Issue by davitol** [owncloud/core#24913]
### Steps to reproduce

1. Start owncloud session from several browser devices
2. Go to the personal page, sessions section

### Expected behaviour

The text shown does not mention only web browsers due to there are other possibilities like mobile apps or desktop client.

### Actual behaviour

The text shown is:

These are the web browsers currently logged in to your ownCloud.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:""9.1.0.5","versionstring":"9.1.0 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```

```
### Client configuration

**browser**

 Chrome

![screen shot 2016-05-31 at 10 50 27](https://cloud.githubusercontent.com/assets/10596560/15668831/9261266e-271d-11e6-9b8c-3378e660240f.png)

@ChristophWurst @owncloud/designers

**Comment by ChristophWurst** [comment]
Yes, this is confusing. The long term goal is to not use sessions for clients which will also remove those entries.

**Comment by nickvergessen** [comment]
I'd say we should fix the mis-wording for 9.1

**Comment by MTRichards** [comment]
How about: These are the clients currently logged in to your ownCloud.

**Comment by MTRichards** [comment]
https://github.com/owncloud/core/pull/24923

**Comment by SergioBertolinSG** [comment]
This was fixed.
