### ISSUE TITLE
A row/session is created for each request using a oC client

### ISSUE THREAD

**Issue by davitol** [owncloud/core#24920]
### Steps to reproduce

1. Start ownCloud session from several browser devices
2. Go to the personal page
3. Connect via app mobile to the oC server.
4. Open a folder and open a file.

### Expected behaviour

Only one row should appear for each session

### Actual behaviour

A row is created for each request.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:""9.1.0.5","versionstring":"9.1.0 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```

```
### Client configuration

**browser**

 Chrome

![screen shot 2016-05-31 at 12 47 31](https://cloud.githubusercontent.com/assets/10596560/15672037/65f4aaf4-272e-11e6-932f-dd441bbc9f85.png)

@ChristophWurst @PVince81

**Comment by PVince81** [comment]
I think we have a solution @ChristophWurst

**Comment by ChristophWurst** [comment]
Yes, the solution is to use an up-to-date core master ;-)
