### ISSUE TITLE
Feature Request / security: encrypt mail smpt password in config.php

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#24925]
Below is a fraction of the content from config.php when used to fill in the issue template.
When you look into config.php directly, `mail_smtppassword` is written in cleartext.
**Feature Request / security:** store the password encrypted - like the DB pwd.

```
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "owncloud",
        "mail_domain": "xxxx",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "xxxx",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
```

**Comment by PVince81** [comment]
Or store the mail config stuff in the database... also encrypted.

The trouble with config.php is that it's also supposed to be editable by an admin, which means an admin would also need the possibility of specifying the values manually and also a password, which in this case would be unencrypted.

In my POV ideally such config needs to be moved to the database.
See related ticket https://github.com/owncloud/core/issues/11843

**Comment by mmattel** [comment]
Hmmm, the database password is also, as far I know, not direct editable. What would the difference be to the smpt-password? Moving all email settings to the database is a great idea, but isn´t that a big coding effort?

**Comment by PVince81** [comment]
Moving email settings might be just a matter of doing the following:
1) renaming a method call from `allConfig->getSystemValue("smtp_...")` to `allConfig->getAppValue("core", "smtp_...")`
2) writing a repair step that copies the values there on upgrade.
3) adding some extra code to encrypt the password value, there are helper functions for that

For those who like to do cluster deployment, they can use the `occ config:*` commands to set these values.

**Comment by RealRancor** [comment]
Is it really worth the effort? Storing the password encrypted in the database just looks like some obfuscation to me. oC needs to decrypt the password anyway so an attacker is probably always able to get it.

**Comment by mmattel** [comment]
@RealRancor principly correct, but I would like to put stones on the road and not present passwords on the red carpet...

**Comment by RealRancor** [comment]
@mmattel In the db they are still on the red carpet from my PoV. There are probably better places to protect the password then on application level.

**Comment by mmattel** [comment]
However made, cleartext is a no-go :scream_cat:

**Comment by rullzer** [comment]
So solution (requires some work but hey..)

1. create a local mail relay
2. configure local mail relay usually they allow you to store your password 'encrypted'
3. configure ownCloud to send mail via the local relay.

Of course the 'local' relay can also be a different server in your trusted network.
I think this is best. As I see no way for ownCloud to do this properly if you are truley paranoid.

**Comment by tflidd** [comment]
The database password is clear-text (but often auto-generated, therefore complex and a crypto-like looking). You can change it anytime you want.

Obfuscating the password is rather dangerous because people could rely on it and take their normal mail account which could contain sensitive information. If they have to enter a clear-text password, they'll prefer to create a specific account for owncloud.

**Comment by mmattel** [comment]
For the config report we have ``$sensitiveValues`` at ``lib/private/SystemConfig.php#L39``
which is one important step hiding sensitive data.

Is there any progress for config.php to avoid cleartext on some mail parameters?

**Comment by DeepDiver1975** [comment]
> Is there any progress for config.php to avoid cleartext on some mail parameters?

no - anything we can think of is just snake oil ...

**Comment by PVince81** [comment]
I'd rather move these values to the database. Then they can be encrypted or whatever.

config.php is intended to be manually editable by the admin.

See https://github.com/owncloud/core/issues/11843
