### ISSUE TITLE
[Announcements][9.1.0beta1]Owncloud does not send announcements

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/core#24934]
### Steps to reproduce
1. As Admin enable Announcements center app
2. Go to Announcement center
3. Write a new announcement

### Expected behaviour
Announcements generated should be sent to the clients connected to the server

### Actual behaviour
Announcements are generated but not sent.

### Server configuration
**Operating system:**
Ubuntu 14.04.1 LTS
**Web server:**
Apache2
**Database:**
Server version: 5.5.46-0ubuntu0.14.04.2 (Ubuntu)
**PHP version:**
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46
**ownCloud version:**
ownCloud Enterprise Edition 9.1.0 beta 1 (testing)

**List of activated apps:**
Announcement Center

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'updatechecker' => false,
  'supportedDatabases' => 
  array (
    0 => 'mysql',
    1 => 'pgsql',
    2 => 'oci',
  ),
  'instanceid' => 'oco48z2585bc',
  'passwordsalt' => 'ZZZZ',
  'secret' => 'XXXXX',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'XXXXXX',
  ),
  'datadirectory' => '/opt/owncloud/data',
  'overwrite.cli.url' => 'XXXX',
  'dbtype' => 'mysql',
  'version' => '9.1.0.5',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => 'oc_admin',
  'dbpassword' => '1xgukCfhszo+kYlKpQN8ZK0JCmrvHo',
  'logtimezone' => 'UTC',
  'installed' => true,
  'license-key' => 'demo-20160625-80e046c4d642dfa0-a9a2295f',
);

```

**Are you using encryption:** 
No

**Comment by RealRancor** [comment]
@mcastroSG Shouldn't this be re-opened in https://github.com/owncloud/announcementcenter/issues

**Comment by nickvergessen** [comment]
Not really, the app generates notifications, if the notifications are shown in the web UI, but not in the client, it's either a time/cache problem and solves itself after the next poll, or it is an issue with the client. :wink:

**Comment by nickvergessen** [comment]
@mcastroSG can you confirm that the notifications are shown in the web UI but not in the client?

**Comment by mcastroSG** [comment]
@nickvergessen  as could be seen at the snapshot announcement is generated and could be checked on GUI but something is not working because nothing appears on client 😭 

![screen shot 2016-06-01 at 15 12 37](https://cloud.githubusercontent.com/assets/18436398/15710674/55128854-280b-11e6-90b8-6a927692f182.png)

`wget http://XXXX:YYYY@serverOC/ocs/v2.php/apps/notifications/api/v1/notifications`

returns 

`<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>200</statuscode>
  <message/>
 </meta>
 <data/>
</ocs>
`

**Comment by nickvergessen** [comment]
Did the background jobs get executed?

**Comment by mcastroSG** [comment]
Setting Background Jobs

- **AJAX**:

1.- Create a new announcement
2.- Navigate to All files section several times and info related to "Last  cron job execution" is updated but there is no announcement at any client.

- **WebCron**:

1.- Create a new announcement
2.- Wait 15 minutes to test, "Last  cron job execution" is not updated (I mean it´s supposed to be launch every 15 minutes but we found "Last cron job execution: 17 minutes ago") and  there is no announcement at any client.

- **Cron**:

1.- Create a new announcement
2.- Execute cron.php  and announcements are sent to the clients.

Hope it helps

**Comment by RealRancor** [comment]
- WebCron needs a call to cron.php from an external system or via browser

**Comment by nickvergessen** [comment]
Ajax cron needs to be executed a couple of times, because it only ever runs one
