### ISSUE TITLE
Missing "file_get_contents" and "file_put_contents" hooks on master/9.1

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#24937]
It looks like we lost these hooks during refactoring ?!

See the hooks triggered by "file_get_contents" and "file_put_contents" here: https://github.com/owncloud/core/blob/v9.0.2/apps/files_sharing/lib/sharedstorage.php#L327

After this commit 6123badbfa22b79167c4b41f84a38b372f033a2e they're gone and don't seem to be triggered from anywhere.

@rullzer @icewind1991 

CC @oparoz

**Comment by PVince81** [comment]
This qualifies as API breakage as there might be apps listening to such hooks.
Since @oparoz raised this issue https://github.com/owncloud/core/issues/23620 before, they might be used by the gallery app.

**Comment by oparoz** [comment]
Thanks for noticing the problem @PVince81! It's needed to track shared files.

**Comment by PVince81** [comment]
In theory there might be new ways for doing it, but for the sake of backward compatibility we need to keep these. There was no deprecation notice for those, so they're supposed to stay.

**Comment by icewind1991** [comment]
I can't find any code in master that uses these hooks

**Comment by PVince81** [comment]
@icewind1991 what about gallery ?

**Comment by PVince81** [comment]
In general it is fine to get rid of hooks, but as per API policy we should first deprecate them and announce it publicly. And then after 2-3 years remove them after app devs had time to adjust.

**Comment by oparoz** [comment]
@PVince81 - Gallery is not using hooks yet as they were not working properly, as documented, until recently.

**Comment by rullzer** [comment]
Ah mmm my bad...

**Comment by guruz** [comment]
I don't see many ```\OCP\Util::emitHook``` in general (in master branch), is that normal?
The hook name sounds quite specific, what is an ```ISharedStorage```? I don't see any comment.

**Comment by oparoz** [comment]
Just to confirm that the restored hooks work as expected
