### ISSUE TITLE
Bad UX with perma links

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#24939]
### Steps to reproduce
1. Share folder with user1
2. As user1 open the folder
3. As admin delete and recreate user1
4. As user1 refresh the page and login with the form

### Expected behaviour
Should see the files list

### Actual behaviour
Exception-like window with file not found:
> File not found
The specified document has not been found on the server.
You can click here to return to ownCloud.

The problem is, the file id does not exist anymore, I thought I broke my instance, until I realized the fileid in the URL. I think we should either go back to the file list silently or with a yellow banner.
But not stay on the exception page.

@PVince81

**Comment by alpsleonardo** [comment]
Hi @nickvergessen, I simulated here and happened as you described, would you be okay if I get this issue to fix it?

**Comment by nickvergessen** [comment]
Sure, go ahead

**Comment by alpsleonardo** [comment]
@nickvergessen Thank you! :)
