### ISSUE TITLE
unable to install owncloud-client from repository on download.opensuse.org

### ISSUE THREAD

**Issue by kelanden** [owncloud/core#24930]
I am unable to install owncloud-client from the CentOS 7 repository on download.opensuse.org.

### Steps to reproduce
Per the directions [here](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client):

    su
    cd /etc/yum.repos.d/
    wget http://download.opensuse.org/repositories/isv:ownCloud:desktop/CentOS_7/isv:ownCloud:desktop.repo
    yum -y install owncloud-client

### Expected behaviour
I expect that owncloud-client and dependencies should be installed successfully.

### Actual behaviour
However, the installation fails because the following packages are not available for download:

 -  owncloud-client-l10n-2.2.0-9.1.x86_64
 -  opt-libqt5keychain0-0.6.2-1.1.x86_64
 -  libowncloudsync0-2.2.0-9.1.x86_64
 - owncloud-client-2.2.0-9.1.x86_64

### Client configuration
**Browser:**
yum 3.4.3
wget 1.14

**Operating system:**
CentOS Linux release 7.2.1511 (Core) 

#### yum log
    Loaded plugins: fastestmirror, langpacks
    Loading mirror speeds from cached hostfile
     * base: mirror.n5tech.com
     * extras: ftpmirror.your.org
     * updates: mirror.san.fastserv.com
    Resolving Dependencies
    --> Running transaction check
    ---> Package owncloud-client.x86_64 0:2.2.0-9.1 will be installed
    --> Processing Dependency: libowncloudsync0 = 2.2.0 for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: opt-qt5-qtbase for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: opt-qt5-qtbase-gui for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: owncloud-client-l10n for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: opt-qt5-qtwebkit for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: libQt5WebKitWidgets.so.5()(64bit) for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: libQt5Widgets.so.5()(64bit) for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: libQt5Network.so.5()(64bit) for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: libQt5Xml.so.5()(64bit) for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: libQt5Sql.so.5()(64bit) for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: libowncloudsync.so.0()(64bit) for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: libQt5Core.so.5()(64bit) for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: libQt5Gui.so.5()(64bit) for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: libQt5DBus.so.5()(64bit) for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: libocsync.so.0()(64bit) for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: libQt5WebKit.so.5()(64bit) for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: libQt5Concurrent.so.5()(64bit) for package: owncloud-client-2.2.0-9.1.x86_64
    --> Processing Dependency: libqt5keychain.so.0()(64bit) for package: owncloud-client-2.2.0-9.1.x86_64
    --> Running transaction check
    ---> Package libowncloudsync0.x86_64 0:2.2.0-9.1 will be installed
    ---> Package opt-libqt5keychain0.x86_64 0:0.6.2-1.1 will be installed
    ---> Package opt-qt5-qtbase.x86_64 0:5.4.2-4.2 will be installed
    ---> Package opt-qt5-qtbase-gui.x86_64 0:5.4.2-4.2 will be installed
    --> Processing Dependency: libxcb-icccm.so.4()(64bit) for package: opt-qt5-qtbase-gui-5.4.2-4.2.x86_64
    --> Processing Dependency: libxcb-sync.so.0()(64bit) for package: opt-qt5-qtbase-gui-5.4.2-4.2.x86_64
    --> Processing Dependency: libxcb-keysyms.so.1()(64bit) for package: opt-qt5-qtbase-gui-5.4.2-4.2.x86_64
    --> Processing Dependency: libxcb-render-util.so.0()(64bit) for package: opt-qt5-qtbase-gui-5.4.2-4.2.x86_64
    --> Processing Dependency: libGLESv2.so.2()(64bit) for package: opt-qt5-qtbase-gui-5.4.2-4.2.x86_64
    --> Processing Dependency: libxcb-image.so.0()(64bit) for package: opt-qt5-qtbase-gui-5.4.2-4.2.x86_64
    ---> Package opt-qt5-qtwebkit.x86_64 0:5.4.2-2.4 will be installed
    ---> Package owncloud-client-l10n.x86_64 0:2.2.0-9.1 will be installed
    --> Running transaction check
    ---> Package compat-libxcb.x86_64 0:1.9-1.el7 will be installed
    ---> Package mesa-libGLES.x86_64 0:10.6.5-3.20150824.el7 will be installed
    ---> Package xcb-util-image.x86_64 0:0.4.0-2.el7 will be installed
    ---> Package xcb-util-keysyms.x86_64 0:0.4.0-1.el7 will be installed
    ---> Package xcb-util-renderutil.x86_64 0:0.3.9-3.el7 will be installed
    ---> Package xcb-util-wm.x86_64 0:0.4.1-5.el7 will be installed
    --> Finished Dependency Resolution
    
    Dependencies Resolved
    
    ================================================================================
     Package              Arch   Version                 Repository            Size
    ================================================================================
    Installing:
     owncloud-client      x86_64 2.2.0-9.1               isv_ownCloud_desktop 1.0 M
    Installing for dependencies:
     compat-libxcb        x86_64 1.9-1.el7               base                  44 k
     libowncloudsync0     x86_64 2.2.0-9.1               isv_ownCloud_desktop 424 k
     mesa-libGLES         x86_64 10.6.5-3.20150824.el7   base                  30 k
     opt-libqt5keychain0  x86_64 0.6.2-1.1               isv_ownCloud_desktop  56 k
     opt-qt5-qtbase       x86_64 5.4.2-4.2               isv_ownCloud_desktop 3.1 M
     opt-qt5-qtbase-gui   x86_64 5.4.2-4.2               isv_ownCloud_desktop 5.1 M
     opt-qt5-qtwebkit     x86_64 5.4.2-2.4               isv_ownCloud_desktop  10 M
     owncloud-client-l10n x86_64 2.2.0-9.1               isv_ownCloud_desktop 398 k
     xcb-util-image       x86_64 0.4.0-2.el7             base                  15 k
     xcb-util-keysyms     x86_64 0.4.0-1.el7             base                  10 k
     xcb-util-renderutil  x86_64 0.3.9-3.el7             base                  12 k
     xcb-util-wm          x86_64 0.4.1-5.el7             base                  25 k
    
    Transaction Summary
    ================================================================================
    Install  1 Package (+12 Dependent packages)
    
    Total size: 21 M
    Total download size: 1.9 M
    Installed size: 69 M
    Downloading packages:
    No Presto metadata available for isv_ownCloud_desktop
    http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/desktop/CentOS_7/x86_64/libowncloudsync0-2.2.0-9.1.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
    Trying other mirror.
    To address this issue please refer to the below knowledge base article 
    
    https://access.redhat.com/articles/1320623
    
    If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/
    
    http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/desktop/CentOS_7/x86_64/opt-libqt5keychain0-0.6.2-1.1.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
    Trying other mirror.
    http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/desktop/CentOS_7/x86_64/owncloud-client-2.2.0-9.1.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
    Trying other mirror.
    http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/desktop/CentOS_7/x86_64/owncloud-client-l10n-2.2.0-9.1.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
    Trying other mirror.
    
    
    Error downloading packages:
      owncloud-client-l10n-2.2.0-9.1.x86_64: [Errno 256] No more mirrors to try.
      opt-libqt5keychain0-0.6.2-1.1.x86_64: [Errno 256] No more mirrors to try.
      libowncloudsync0-2.2.0-9.1.x86_64: [Errno 256] No more mirrors to try.
      owncloud-client-2.2.0-9.1.x86_64: [Errno 256] No more mirrors to try.

**Comment by danimo** [comment]
@jnweiger please

**Comment by jnweiger** [comment]
Fixed CentOS7 repos to no longer borrow build depdendencies from fedora19.
Fixed spec file of qt5-qttools in :testing to be identical to :nightly and require opt-qt5-qtbase-devel (with correct opt- prefix!)

**Comment by jnweiger** [comment]
https://build.opensuse.org/package/binary/isv:ownCloud:community:nightly/qt5-qttools?arch=x86_64&filename=opt-qt5-qttools-devel-5.4.2-4.2.x86_64.rpm&repository=CentOS_7

Installs fine on my centos7 machine. Fix ready for 2.2.1

**Comment by viniciuscb** [comment]
I am having the same problem for OpenSuse Tumbleweed
Repos: http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/openSUSE_Tumbleweed/

Not found **libqt5keychain0** anywhere.

Message: 
```
➜  ~ sudo zypper install owncloud-client
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides libqt5keychain0 >= 0.6.2 needed by libowncloudsync0-2.2.0-9.9.x86_64
 Solution 1: do not install owncloud-client-2.2.0-9.9.x86_64
 Solution 2: break libowncloudsync0-2.2.0-9.9.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c] (c): 
```

**Comment by jnweiger** [comment]
right now, openSUSE mirrors are updating to host our 2.2.1 release. 
I see the new qt5keychain1-0.7.0 already replaced qt5keychain0-0.6.2 there, but all our owncloud-client packages are still at 2.2.0 -- this is inconsistent, sorry for that. 
It should resolve to a consistent state within the next hour.

**Comment by viniciuscb** [comment]
Now it installed, however another error happened, in execution:

```
➜  ~ owncloud
owncloud: relocation error: /usr/lib64/libQt5Qml.so.5: symbol _ZTI14QObjectPrivate, version Qt_5 not defined in file libQt5Core.so.5 with link time reference
```

If necessary, please specify what additional kind of information I should provide to you to better understand this problem.
