### ISSUE TITLE
"Your storage is full, files can not be updated" on a VPS at 50% capacity, personal allowance is set to "unlimited"

### ISSUE THREAD

**Issue by mikebabb** [owncloud/core#24942]
I'm having trouble getting ownCloud to continue working on a hosted VPS following a disk space upgrade from 30GB to 60GB and uploading a large set of data. When I log in to ownCloud I receive the message "Your storage is full, files can not be updated or synced anymore!", but my VPS control panel says the server's disk is only at 50% usage (30GB/60GB), and the "personal" tab of ownCloud correctly reports "You are using 18.3 GB of Unlimited".

If I change my personal data allowance to something else (I set 60GB to test), the message becomes "You are using 18.3 GB of 18.3GB". Setting it back to "unlimited" returns "You are using 18.3 GB of Unlimited" again.

I have tried the workarounds detailed at https://github.com/owncloud/core/issues/18886, but it appears they no longer work as of ownCloud 9.

### Steps to reproduce
1. Increase storage space on a hosted VPS (30GB to 60GB)
2. Attempt to sync data

### Expected behaviour
ownCloud functions as normal

### Actual behaviour
I log in to ownCloud and receive the message "Your storage is full, files can not be updated or synced anymore". VPS control panel says VPS is at 50% usage (30GB/60GB), and "personal" tab of ownCloud says "You are using 18.3 GB of Unlimited", which is correct.

### Server configuration
**Operating system**: Ubuntu 12.04 LTS

**Web server:** Apache

**Database:** MySQL

**PHP version:** Unknown

**ownCloud version:** 9.0.2 stable

**Updated from an older ownCloud or fresh install:** Updated

**Signing status (ownCloud 9.0 and above):** Passed

**List of activated apps:**

- ownNote
- Encryption module

**Are you using external storage, if yes which one:** No

**Are you using encryption:** Yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome

**Operating system:** Ubuntu 16.04 LTS

**Comment by RealRancor** [comment]
@mikebabb Please close here and follow https://github.com/owncloud/core/issues/18886 No need to have two open issues about the same problem open.

**Comment by mikebabb** [comment]
For future reference, this actually ended up being a fault on the server. The host had updated the server control panel to indicate 60GB disk capacity, when the upgrade hadn't actually taken place and ownCloud was repeatedly running out of space on the 30GB disk.
