### ISSUE TITLE
Default link to the download page of sync-clients is broken 

### ISSUE THREAD

**Issue by cmvdsanden** [owncloud/core#24952]
### Steps to reproduce
1. Login into OC
2. Go to you Personal page
3. Click on the Desktop Apps icon to go the download page for the sync-clients

### Expected behaviour
You should go to the owncloud.org page where you can download the native owncloud sync clients

### Actual behaviour
Due to a reorganisation of the owncloud.org website, the address of the webpage to download an sync client has changed, from https://owncloud.org/sync-clients/ to https://owncloud.org/install/.
Can the address in the sample config be updated to the correct link. 

We can do it locally at our own OC service, but it would help if in the sample config in the repository also a working address is provided instead of a broken link which resolves into a "Sorry" page.

### Server configuration
**Operating system**:
N/A
**Web server:**
N/A
**Database:**
N/A
**PHP version:**
N/A
**ownCloud version:** (see ownCloud admin page)
9.0.2

**Updated from an older ownCloud or fresh install:**
N/A, the fault is still in the code of the repository.
https://github.com/owncloud/core/blob/master/config/config.sample.php#L645

**Where did you install ownCloud from:**
N/A

**Signing status (ownCloud 9.0 and above):**
N/A

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
I am a user, not an admin

**List of activated apps:**
N/A

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by nickvergessen** [comment]
@danimo I guess we should add a redirect

**Comment by cmvdsanden** [comment]
This is also a possible solution and works for the current running OC instances. This would be great, then we have not to update the link in our running OC instance. But I would assume that also the link in the sample config is updated to new install page, else you should always maintain the old redirects. 

But you are the best people to judges how you want to fix this.

**Comment by cmvdsanden** [comment]
Thanks for fixen.

Greetz.,
Mark

**Comment by cmvdsanden** [comment]
Sorry to bother you again. I tested it in my OC instance with Chrome and Safari, but I get an error of to many redirects. Below the URL which is generated after clicking on the desktop icon on my personal page.

https://owncloud.org/sync-clients/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/install/#install-clients

The install page is not opened.

**Comment by nickvergessen** [comment]
Yeah, already poked the server guys

**Comment by nickvergessen** [comment]
Fixed
