### ISSUE TITLE
Rewrite Rules: possible improvements

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#24968]
Applies to current master,

**Apache:** 
https://github.com/owncloud/core/blob/52add798d4d814b5276e324c2e98404ff0abe020/.htaccess
**nginx:** https://github.com/owncloud/documentation/blob/master/admin_manual/installation/nginx_owncloud_9x.rst

Following question:
Tested it with ``http://htaccess.mwl.be`` respectively ``https://regex101.com/#python``

**Finding 1:**
Apache
```
RewriteRule ^(build|tests|config|lib|3rdparty|templates)/.* - [R=404,L]
```
nginx
```
location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ { deny all; }
```

**Changes 1:**
I would propose to change the ``location`` rule to: ``^/(build|tests|config|lib|3rdparty|templates)/.*`` which matches the RewriteRule, removing ``|data`` and no need to Non-capturing with ``?:``. (the `/`after the caret is necessary in case of nginx to point to the root) 

**Finding 2:**
Apache
```
RewriteRule ^(\.|autotest|occ|issue|indie|db_|console).* - [R=404,L]
```
nginx
```
location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) { deny all; }
```
From my POV, the regex is in both cases wrong.
In the ``RewriteRule`` it would match not only eg ``.occ`` but also ``.occm``
In the ``location`` block it would start matching with the dot ``.``

**Changes 2:**
I would propose the following adoptions:
Apache
```
RewriteRule ^\.(autotest|occ|issue|indie|db_|console)$ - [R=404,L]
```
nginx
```
location ~ ^/\.(autotest|occ|issue|indie|db_|console)$ { deny all; }
```
(the `/`after the caret is necessary in case of nginx to point to the root)

@LukasReschke  @josh4trunks
Feedback welcomed, if positive, I would file a PR

**Comment by josh4trunks** [comment]
Thanks for the suggestions. Here's my comments

#### 1 ####
* Does Apache not block requests to `/data/`? I have a feeling when /data/ is created it creates an .htaccess in there blocking every request, in which case I don't agree with this change.
* These should stay as non-capturing because the result is never referenced. I suggest this is changed to non-capturing for apache.
* `.*` at the end is implied by nginx regex locations and just would make regex processing slightly longer. Does apache's rewrite need this?

#### 2 ####
* I do not think you are reading the regex properly. this matches anything with a `.` at the beginining like `.hidden` and also `occ`
* see above, suggest apache is changed to non-capturing
* if you add the $ at the end db_structures.xml won't be blocked

**Comment by mmattel** [comment]
@josh4trunks 
1
- shame on me :speak_no_evil: yes there is a .htaccess in data, I have overseen that, location is correct containing ``|data``
- we should do a PR for non-capturing in .htaccess 
- ``.*`` in Apache, don´t know, did not know that this is implied by nginx. I thought nginx is following standard regex and there it make a small difference see when you use the regex testers, but maybe I am wrong here too

2
- again you are correct :speak_no_evil: (where is the hole where I can jump into...)
- we should do a PR for non-capturing in .htaccess 
- this is the one I do not understand, because it is not in the query list nor a dot file

Additional question:
- Why do we use ``deny all;`` and not ``return 404; break;`` (like ``[R=404,L]``)
- Because when I use ``return 404; break;``, I can add a location statement to prevent error logging of ``.ocdata`` access like  `location ^/data/\.ocdata { access_log off; }``

**Comment by mmattel** [comment]
Update regarding the move from ``deny all`` to ``return 404; break;`` and add ``location ^/data/\.ocdata { access_log off; }``
Have tried it and it works. The data directory stays inaccessible and error logs for ``./ocdata`` access are supressed. Will do a documentation PR.

**Comment by josh4trunks** [comment]
@mmattel regarding the **db_structures.xml**, that was just one example. My point is whoever wrote that regex made it open ended. Closing it off with a `$` would allow access to multiple things like all hidden files (starting with`.`), **autotest.sh**, **console.php**. We could either fully specify the files / add more logic like `.*`, or leave it open ended as it is.

Can you test if removing the `.*` from the end of apache's rules still blocks access to those files/folders. I have a feeling it is redundant and can be removed from apache.

**Comment by josh4trunks** [comment]
@mmattel do you still see any reason for the nginx changes discussed here?

**Comment by mmattel** [comment]
I have put this issue here as it affects .htaccess (core) and nginx (documentation) and Apache has a higher precedence over nginx. Will be closed when the corresponding PR´s will get merged/rejected.

**Comment by josh4trunks** [comment]
I see makes sense, sorry thought this was a PR when I wrote that.

**Comment by mmattel** [comment]
Can be closed because the 2 referenced PR´s have been merged
