### ISSUE TITLE
Add external authentication sources to plugable auth

### ISSUE THREAD

**Issue by chris001** [owncloud/core#24967]
Request to add external authentication sources to owncloud plugable auth.

For example the owncloud autheticator module of privacyidea:
https://github.com/privacyidea/privacyidea/issues/410#issuecomment-221807538

**Comment by nickvergessen** [comment]
@ChristophWurst you wrote 2FA, is this now possible?

**Comment by PVince81** [comment]
AFAIK privacyidea is already available now. cc @cornelinux
