### ISSUE TITLE
Repository error on latest owncloud appliance

### ISSUE THREAD

**Issue by dbolton** [owncloud/core#24960]
### Steps to reproduce
1. Install the latest owncloud appliance for Ubuntu
2. apt-get update

### Expected behaviour
Update should run without errors

### Actual behaviour
The update ends with the following error message. (Note there is a "8.2" in the URL that may need to be changed to "9.0")

```
...
W: Failed to fetch http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.2:/testing:/Ubuntu_14.04/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
admin@owncloud:~$
```

### Server configuration
**Operating system**: Ubuntu 14.04.2, 64 bit (latest owncloud appliance)

**ownCloud version:** 9.0.2

**Updated from an older ownCloud or fresh install:** Fresh

**Where did you install ownCloud from:** https://owncloud.org/install/#instructions-server

```

**Comment by RealRancor** [comment]
@dbolton Please re-open in https://github.com/owncloud/vm/issues

**Comment by dbolton** [comment]
Re-opened as https://github.com/owncloud/vm/issues/49
