### ISSUE TITLE
Login form moves down to the centre when window is narrow

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#24977]
### Steps to reproduce
1. Go to the login page
2. Drag the right edge of the window towards the left edge
### Expected behaviour

The form should stay where it is
### Actual behaviour

The form jumps down, to the middle of the window

**Comment by felixheidecke** [comment]
@oparoz Why would you consider this an issue?

**Comment by oparoz** [comment]
Because all the navigation buttons are at the top, so the original design of having the form near the top make sense. Droping it down when reaching a certain width sound like a bug more than a feature.

**Comment by PVince81** [comment]
moved to general design / UX / styling issues group ticket: https://github.com/owncloud/core/issues/27578
