### ISSUE TITLE
External Storage - 'All Files' and client sync hide

### ISSUE THREAD

**Issue by williambargent** [owncloud/core#24970]
I have multiple(7) external shares mounted to my OwnCloud for all users however I don't want these to appearer in the sync client or WebDAV could there be a setting added to prevent this

Also many clients are getting frustrated by these shares being displayed in 'All Files'. At the moment they are being hidden by CSS. Can there be another section which just shows personal files and the use then has the ability to chooses which they want as their default view.

**Comment by mmattel** [comment]
For the sync client, dupe of #7234

**Comment by williambargent** [comment]
I saw that, it just didn't mention the WebDAV part. I want to force the use of the mounted share to owncloud site only as their not personal to the user.

**Comment by PVince81** [comment]
There is currently no such setting, tagging as enhancement

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/issues/7234 as it's very close use case
