### ISSUE TITLE
Shares can be created without uid_initiator

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#24981]
### Steps to reproduce
1. Create a share like this `$share = \OCP\Share::shareItem('file', 1234, 0, 'tester', \OCP\Constants::PERMISSION_ALL)`
2. Login as user tester
### Expected behaviour

User should be able to log in
### Actual behaviour

Share 2.0 throws an exception because `uid_initiator` is null.

```
Exception trace:
 () at /lib/private/Share20/Share.php:287
 OC\Share20\Share->setSharedBy() at /lib/private/Share20/DefaultShareProvider.php:761
 OC\Share20\DefaultShareProvider->createShare() at /lib/private/Share20/DefaultShareProvider.php:625
 OC\Share20\DefaultShareProvider->getSharedWith() at /lib/private/Share20/Manager.php:950
 OC\Share20\Manager->getSharedWith() at /apps/files_sharing/lib/MountProvider.php:61
 OCA\Files_Sharing\MountProvider->getMountsForUser() at /lib/private/Files/Config/MountProviderCollection.php:76
 OC\Files\Config\MountProviderCollection->OC\Files\Config\{closure}() at n/a:n/a
 array_map() at /lib/private/Files/Config/MountProviderCollection.php:77
 OC\Files\Config\MountProviderCollection->getMountsForUser() at /lib/private/Files/Filesystem.php:422
 OC\Files\Filesystem::initMountPoints() at /lib/private/Files/Filesystem.php:370
 OC\Files\Filesystem::init() at /lib/private/legacy/util.php:225
 OC_Util::setupFS() at /tests/lib/TestCase.php:336
 Test\TestCase::loginAsUser() at /apps/gallery/tests/_support/Helper/CoreTestCase.php:49
```

[This change](https://github.com/owncloud/core/commit/78be766cf543d738a3822a3cd614634acb7262d0) introduced the additional check, but things kept working for a while, so something else must have happened between April 15th at 8:26 and April 21st 8:22
### Server configuration

**PHP version:** 7.0.7

**ownCloud version:** master

**Updated from an older ownCloud or fresh install:** rolling

**Are you using encryption:** no
#### ownCloud log (data/owncloud.log)

```
{"reqId":"y2CN+VfeG9bPeVR9lzjJ","remoteAddr":"","app":"no app in context","message":"getSharedWith: {\"id\":\"681\",\"share_type\":\"0\",\"share_with\":\"tester\",\"uid_owner\":\"sharer\",\"parent\":null,\"item_type\":\"file\",\"item_source\":\"301338\",\"item_target\":\"\/301338\",\"file_source\":\"301338\",\"file_target\":\"\/testimage-wide.png\",\"permissions\":\"23\",\"stime\":\"1465161408\",\"accepted\":\"0\",\"expiration\":null,\"token\":null,\"mail_send\":\"0\",\"uid_initiator\":null}","level":"debug","time":"2016-06-05T22:33:57+00:00","method":"--","url":"--","user":"tester"}
```

**Comment by nickvergessen** [comment]
@rullzer looks like the initiator is missing from https://github.com/owncloud/core/blob/718f0757e497f58ddbd783e69227ce6987dff59f/lib/private/Share/Share.php#L2432-L2460

**Comment by rullzer** [comment]
Yes I know \OCP\Share should have been removed/deprecated and calling the new function... but the whole refactoring was pushed back.

**Comment by oparoz** [comment]
@rullzer - Do you have an example of where you create a share using the new code? Seems like we can't create one in one go but have to use lots of setters?

**Comment by rullzer** [comment]
yes you have to use a lot of setters... but you can chain them.

```php
$share = $shareManager->newShare();
$share->setNode(<NODE>)
    ->setShareType(<TYPE>)
    .....
$share = $shareManager->createShare($share);
```

It was done this way to have it more explicit.
There are no helper functions as of now to do this in 1 go.

**Comment by oparoz** [comment]
Thank you @rullzer. I'll give it a go.

**Comment by oparoz** [comment]
OK, there are other problems in Share 2.0.

In `generalCreateChecks` you have this:

```
if ($share->getShareType() === \OCP\Share::SHARE_TYPE_LINK) {
            if ($share->getSharedWith() !== null) {
                throw new \InvalidArgumentException('SharedWith should be empty');
            }
}
```

But if we set sharedWith to null, then we fail another test

```
    public function setSharedWith($sharedWith) {
        if (!is_string($sharedWith)) {
            throw new \InvalidArgumentException();
        }
        $this->sharedWith = $sharedWith;
        return $this;
    }
```

**Comment by rullzer** [comment]
mmm ok fair enough... but you just don't set the shareWith then. but indeed should be fixed.

**Comment by oparoz** [comment]
@rullzer - Then you run into this check

```
            if (!$this->userManager->userExists($share->getSharedWith())) {
                throw new \InvalidArgumentException('SharedWith is not a valid user');
            }
```

**Comment by oparoz** [comment]
I doubt it's the problem since the sharetype is used as a condition which fails for another reason, so null is correct, but the check for sharetype is wrong since null is not a string.

**Comment by rullzer** [comment]
@oparoz maybe a look at https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/API/Share20OCS.php#L239 will help. That is the OCS share endpoint. Which is used the default way to create shares.

I don't know what you are trying to do but maybe that helps,

**Comment by oparoz** [comment]
Thanks @rullzer, I'll have a look.

I just need to replace the call I put in the OP, but apparently it requires more changes than just changing method as some of the parameters have also changed.

**Comment by rullzer** [comment]
I've been looking into this to see if I can wrap the new sharemanager in the `shareItem` function but there is to much magic going on there. So I can't wrap it a 100%.

But on the other hand it currently already breaks stuff.

@PVince81 should we just wrap it and deprecate it? Or remove it all together?

**Comment by oparoz** [comment]
I've opened a new bug for that here: https://github.com/owncloud/core/issues/25065

**Comment by oparoz** [comment]
That was my fault, creating a share doesn't return a token any more.

**Comment by PVince81** [comment]
@rullzer we can't remove it directly as we need to first deprecated it since it's in the public API namespace.

How many % are missing from the wrapping workaround ? Any side effects ?

**Comment by rullzer** [comment]
@PVince81 just look at the create function... I see no way to wrap all the functionality properly...

**Comment by rullzer** [comment]
uhm `share` function in lib/private/share.php that is

**Comment by PVince81** [comment]
Apparently when creating a reshare it sets the owner wrong, this messes up the unit tests from https://github.com/owncloud/core/pull/26389 which still use the old API.

**Comment by PVince81** [comment]
I have the feeling that there is no good solution to this apart from using the new API directly. Also we'll remove the legacy Share API in 9.2.

Closing.
