### ISSUE TITLE
Check loginname when authenticating with basic auth and device token

### ISSUE THREAD

**Issue by ChristophWurst** [owncloud/core#24985]
Starting with 9.1 it is possible to use HTTP basic auth with username and device token. The current implementation does *not* check the username if a token is used as password. Hence one could use a random username. While that works for the first request, sub-sequent requests will be logged out as soon as the password check is performed. That check uses the loginname+password stored in the token.

Although this will kill performance for session-less clients, we have to check the loginname against the user-backend if we want to fix that.

The current behavior also breaks any clients that rely on that check.

cc @PVince81 not sure how critical this is in the scope of 9.1

@owncloud/desktop-developers @owncloud/android-developers @owncloud/ios-developers

**Comment by ChristophWurst** [comment]
To be clear: This does *not* mean that user1 can log in as user2 by using a valid token (that was created for user1). The token login process just does not check the loginname if the token is detected.

**Comment by ogoffart** [comment]
This might let the client log as the wrong user which might be quite damaging for the sync. (As another user's data will now be seen)

**Comment by PVince81** [comment]
From my understanding the user id is ignored when you use a token. It is internally mapped to the correct user in the server.

But if the client relies on the user name to map stuff, it might break there.

**Comment by PVince81** [comment]
Setting to critical for now until this is cleared

**Comment by guruz** [comment]
> we have to check the loginname against the user-backend if we want to fix that.

Why not store the username in the PHP session and check against that? No need to re-ask the backend..

**Comment by ChristophWurst** [comment]
@guruz it's only about the very first request, sub-sequent requests don't need that check.
