### ISSUE TITLE
Security issue: Move datadir protection check back from .ocdata to htaccess.txt

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#24987]
In https://github.com/owncloud/core/pull/22054 the check for the protection of the datadir was moved to check if the .ocdata is accessible via the internet.

Checking if the .ocdata is not accessible is no proof if the datadir is protected. Most webserver setups out there are denying the access to those "dot" files by default. There is no guarantee that the datadir is protected by the assumption that the .ocdata is not accessible.

**Comment by PVince81** [comment]
@RealRancor thanks, I didn't realize.

My local setup doesn't have a "htaccess.txt" file so I guess we need to re-add logic to generate this file ?

**Comment by PVince81** [comment]
Fix will require backport to 9.0

**Comment by RealRancor** [comment]
Just checked the apache2 config of Ubuntu which has only:

```
<FilesMatch "^\.ht">
        Require all denied
</FilesMatch>
```

and nginx only:

```
location ~ /\.ht {
    deny all;
}
```

Still its quite common that "dot" files are blocked.

**Comment by nickvergessen** [comment]
sounds good, wanna fix it @RealRancor

**Comment by PVince81** [comment]
We first need to decide how to fix it.
Do we want to add code that generates a "htaccess.txt" file ? Where ?
And then change the UI part to check this file instead of ".ocdata".

**Comment by mmattel** [comment]
FYI, the original naming of the file was: ``htaccesstest.txt``
Currently there is only one place where this file is mentioned in core: see https://github.com/owncloud/core/blob/c0a19ecd2d4878684a135764e9cf4a175e5f591e/lib/private/legacy/util.php#L1150

**Comment by PVince81** [comment]
Hmm, maybe loading the admin page could auto-create that file and then the ajax call could check it.

But then the file will get a chance to be deleted again. Might be ok though.

**Comment by PVince81** [comment]
Is it bad if the file never gets deleted ? Or we could call it "_htaccesstest.txt" or something that looks more like a temporary file ?

**Comment by nickvergessen** [comment]
honestly I'd say suffix test should be enough for people to know okay I might not delete this file.
If it is never deleted, it should also not be a problem.

**Comment by PVince81** [comment]
so "htaccess.test" then

**Comment by PVince81** [comment]
Okay, now I understand what you meant. "htaccesstest.txt" should then be enough.

Let's see if I can implement this without duplicating too much code...

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/25014

**Comment by RealRancor** [comment]
> Is it bad if the file never gets deleted ?

From what i understand https://github.com/owncloud/core/pull/22054 was implemented because of https://github.com/owncloud/core/issues/20199 where an existing htaccesstest.txt caused a false positive.
