### ISSUE TITLE
Cannot decrypt a user's account called 0 via occ command

### ISSUE THREAD

**Issue by davitol** [owncloud/core#24994]
### Steps to reproduce

1. Create a oC user called "0"
2. Encrypt your oC server via occ command
3. Try to decrypt "0"'s account via occ command ```occ encryption:decrypt 0```

### Expected behaviour

Running ```occ encryption:decrypt 0``` command should decrypt "0"'s account

### Actual behaviour

The CLI is taking 0 parameter as empty, so the whole oC server will be decrypted 

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:""9.1.0.5","versionstring":"9.1.0 beta 1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
Yes
**Logs**
```

```
### Client configuration

**browser**

**Comment by nickvergessen** [comment]
Btw I don't really think username `'0'` is a sev2 case, but anyway PR is already here.
