### ISSUE TITLE
SQL-Error on Upgrade to 9.0.2

### ISSUE THREAD

**Issue by tmaex** [owncloud/core#24996]
### Steps to reproduce
1. apt-get dist-upgrade (including owncloud)
2. disable maintenance mode
3. open owncloud in browser, do the update

### Expected behaviour
updating database

### Actual behaviour

notifications: An exception occurred while executing 'CREATE TABLE `oc_notifications` (`notification_id` INT AUTO_INCREMENT NOT NULL, `app` VARCHAR(32) NOT NULL, `user` VARCHAR(64) NOT NULL, `timestamp` INT DEFAULT 0 NOT NULL, `object_type` VARCHAR(64) NOT NULL, `object_id` VARCHAR(64) NOT NULL, `subject` VARCHAR(64) NOT NULL, `subject_parameters` LONGTEXT DEFAULT NULL, `message` VARCHAR(64) DEFAULT NULL, `message_parameters` LONGTEXT DEFAULT NULL, `link` VARCHAR(4000) DEFAULT NULL, `actions` LONGTEXT DEFAULT NULL, INDEX oc_notifications_app (`app`), INDEX oc_notifications_user (`user`), INDEX oc_notifications_timestamp (`timestamp`), INDEX oc_notifications_object (`object_type`, `object_id`), PRIMARY KEY(`notification_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_notifications' already exists

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 5.6.20

**ownCloud version:** 9.0.2

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** debian repo

----

I think the tail is unimportent, tell me if you don't think so.

I simply droped the table by hand and did the upgrade again.

**Comment by aronovgj** [comment]
https://github.com/owncloud/core/issues/23867#issuecomment-221182668

**Comment by nickvergessen** [comment]
Yeah, tehre have been several reports already, please use the search.
