### ISSUE TITLE
Shared from you view shows wrong folder names

### ISSUE THREAD

**Issue by scriptPilot** [owncloud/core#24997]
When I share a folder FOLDER-A to a person and he is first renaming to FOLDER-B and then sharing it as well, in "Shared from you" (or similiar in english) view shows still the olf name FOLDER-A. In the folder view he will the the new folder name.

**Comment by rullzer** [comment]
Ah yes. True. This is (for now) the way the API works. But it is a nice enhacncement indeed.

**Comment by scriptPilot** [comment]
Thank you for that Information. But I think we have a BUG as well - why? So if the FOLDER-A is shared and shared again, the second sharer could click on the Folder in the "Shared from you" view without any Problem. But If he has changed the Name of the shared Folder, after click on the (original) title he will get to the main Folder, not to the one he has clicked on ...

**Comment by rullzer** [comment]
Aah that is a bug indeed. Let see..

**Comment by rullzer** [comment]
O the joy... basically the output we return depends on who is calling... (and with which parameters)... I think I know how to make it work but lets see..
