### ISSUE TITLE
[CI] postgres on master is failing

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#25002]
![bildschirmfoto von 2016-06-07 14-24-46](https://cloud.githubusercontent.com/assets/1005065/15857430/b426dd86-2cbb-11e6-8dc8-28ae4e0662d9.png)

**Comment by DeepDiver1975** [comment]
Broken since this change - https://github.com/owncloud/core/commit/bf917d7063ed9328a8d367343ac2a6574917ddfb

@PVince81 @icewind1991

**Comment by DeepDiver1975** [comment]
regression since https://github.com/owncloud/core/pull/24813

**Comment by icewind1991** [comment]
will have a go at it

**Comment by DeepDiver1975** [comment]
> will have a go at it

Thanks a lot!

**Comment by nickvergessen** [comment]
Same for oracle btw:
```
ORA-01400: cannot insert NULL into ("AUTOTEST"."oc_filecache"."mtime")
```

But I guess a fix will be the same to both

**Comment by icewind1991** [comment]
Fix is here https://github.com/owncloud/core/pull/25005
