### ISSUE TITLE
Admin Page not Opening Properly

### ISSUE THREAD

**Issue by Waqar731** [owncloud/core#25013]
Hi,
Today at (7 june 2016) I downloaded owncloud server from official website and install with the help of this link. http://sharadchhetri.com/2015/04/26/install-owncloud-8-on-ubuntu-server-14-04/
Final when i write the   http://localhost/owncloud/index.php
 on browser then I am only getting empty page.
Why I am not being shown the Admin page properly as expected?

Thanks

**Comment by RealRancor** [comment]
@Waqar731 Please use the forums or the users mailinglist https://owncloud.org/support/ for installation help.
