### ISSUE TITLE
Add Apache Chemistry (CMIS protocol) for sync and remote drive mount

### ISSUE THREAD

**Issue by chris001** [owncloud/core#25016]
Would be smart to add a second protocol (besides the current WebDAV) for communicating between owncloud client and owncloud server, to sync files, and open/edit files remotely, 
Apache Chemistry supports an IETF approved standard protocol called CMIS, which is specialized for dealing with file servers, all the mainstream systems support it, sharepoint, everything.
Just add the free Chemstry CMIS PHP libraries for client and server.
This Apache Chemistry CMIS protocol fits this needs of owncloud users perfectly...

**Comment by hodyroff** [comment]
CMIS is something we like to do in the backend, as an additional external protocol. Why would it be helpful between server and client? Would you join a team working on the backend implementation?

**Comment by PVince81** [comment]
I don't think this would be part of core, but could be implemented as a separate app that uses the PHP APIs to wire it up to CMIS.
