### ISSUE TITLE
New local user creates the user physically in the data directory during first logon

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#25020]
### Steps to reproduce
1. Create a new local user
2. Do NOT logon with this user name
3. Run ``sudo -uwww-data ./occ files:scan --all -v

### Expected behaviour
No errors printed to the console

### Actual behaviour
A error is printed at the console:
```
Starting scan for user x out of y (user_x)
Home storage for user user_x not writable
Make sure you're running the scan command only as the user the web server runs as
```
Looking at the data directory, the user setup has not finalized as the user directory with it´s underlaying structure is not present. When the user first logs on, the filesystem structure is created for him. This structure will get deleted when the user gets deleted.
This means, that the scan command must fail with this particular user because of missing filesystem structures beeing created during user creation. Supressing the error message as possible solution is not a good idea...

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** nginx 1.9.14

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.2 RC1 (daily) Build:2016-04-28T03:03:12+00:00 795f321a1985b682bff584f252dd6f2fd95dad65

**Updated from an older ownCloud or fresh install:**
This was a fresh setup from tar and updated once, daily channel

**Where did you install ownCloud from:**
tar

**Signing status (ownCloud 9.0 and above):**

```
Datei nicht gefunden
Das ausgewählte Dokument wurde auf dem Server nicht gefunden.
Sie können zur Rückkehr zu ownCloud hier klicken.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ock982ae3c5s",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxx"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xxxx",
        "dbtype": "mysql",
        "version": "9.0.2.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "assetdirectory": "\/var\/www\/owncloud",
        "asset-pipeline.enabled": true,
        "filesystem_check_changes": 1,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Raw"
        ],
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "owncloud",
        "mail_domain": "xxxx",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "xxxx",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:** Opera

**Operating system:** W7x64

#### owncloud.log
no corresponding log entries

**Comment by PVince81** [comment]
> Supressing the error message as possible solution is not a good idea...

But that's what you put under "Expected behavior" :wink: 

I see two possibilities:
1) do suppress the error message in the right place in the code (quick fix)
or
2) do create the home folder for the user

The problem with 2) is that it might not work with encryption, because the skeleton files will be copied and might require the user to be logged in. I'm not 100% sure, it might work but then the skeleton files will not be encrypted, which isn't a big issue I guess.

**Comment by PVince81** [comment]
Most importantly: the scanner must **continue** running and not abort!

**Comment by PVince81** [comment]
@icewind1991 what do you think ?

**Comment by mmattel** [comment]
Question:
Do we have a database entry or can we check if the user has logged on at least once?
If yes, we could check in case the filesystem reports the missing structure the situation and surpress the "false" error message (respectively skip the user), but do a proper logging in case there is a real problem because the files in the filesystem are missing.

**Comment by PVince81** [comment]
There is no clear indication in the database whether the structure was created.

Hmm, there is a "last login time" flag somewhere, but I wouldn't want to rely on that.

Another idea is to check whether the oc_storage/oc_filecache contains any entries for that user. When the structure is not created, it is likely that the "files" entry in the oc_filecache doesn't exist yet.

**Comment by PVince81** [comment]
and also need to take race conditions into account in case someone logs in while the scanning is running.

**Comment by mmattel** [comment]
Q: if I go to accounts I can see in the last column when the user has last logged on. For those who never did you have "Never". How is that gathered? Could it be reused?

**Comment by PVince81** [comment]
@mmattel that's the value of "lastLogin" in the "oc_preferences" table. But as I said above it might not be accurate.

Ideally at some point I'd like to have another value "skeleton was initialized" to be more clear about this, see https://github.com/owncloud/core/issues/23430

**Comment by icewind1991** [comment]
https://github.com/owncloud/core/pull/25028 prevents the error in the file scanner
