### ISSUE TITLE
Click on "deleted" column title in the trashbin messes file names and previews.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#25032]
### Steps to reproduce:

1. Upload some files to a user account.
2. Delete some files.
3. Go to the trashbin, click on the "Deleted" column title.
4. Click again.

### Expected behaviour:
File rows get sorted by date.

### Actual behaviour
File names changes wrongly and the preview images are gone.

![screen shot 2016-06-08 at 16 16 43](https://cloud.githubusercontent.com/assets/9048796/15897382/87c4c210-2d94-11e6-82ed-f5227cb117f7.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Current master
{"installed":true,"maintenance":false,"version":"9.1.0.7","versionstring":"9.1.0 beta 1","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```


```

### Client configuration

Cadaver.

**Comment by nickvergessen** [comment]
Nice, I expect the missing previews are related to the file name changing.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/25238
