### ISSUE TITLE
CardDAV: multiple groups are served as one CATEGORY with "," in name

### ISSUE THREAD

**Issue by rfc2822** [owncloud/core#25030]
### Steps to reproduce
1. Add a contact with two categories, let's say "CatA" and "CatB"
2. Fetch the VCard for this contact via CardDAV.

### Expected behaviour
Because OwnCloud states to support VCard 4, the appropriate mechanism (KIND/MEMBER) should be used. However, this is another problem. When using VCard3 CATEGORIES (like OwnCloud currently does), the expected output would be:

```
CATEGORIES:CatA,CatB
```

### Actual behaviour

Instead, the `,` is escaped:

```
CATEGORIES:CatA\,CatB
```

which of course causes clients to assign the contact to a new group "CatA,CatB" instead of the two groups "CatA" and "CatB".

### Server configuration
**Operating system**: Debian GNU/Linux 8.4 (jessie)

**Web server:** Apache/2.4.10 (Debian)

**Database:** MySQL 5.5.49-0+deb7u1 (Debian)

**PHP version:** PHP 5.6.19-0+deb8u1

**ownCloud version:** 9.0.2

**Updated from an older ownCloud or fresh install:** fresh install of 9.x, but I don't know if there was an update from 9.0.x (I don't think so)

**Where did you install ownCloud from:** http://download.owncloud.org/download/repositories/stable/Debian_8.0/

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.2.0.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.9.0
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
root@debian-test:/var/www/owncloud# sudo -u www-data php occ config:list system
{
    "system": {
        "updatechecker": false,
        "instanceid": "ockii5e7dtm3",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "debian-test.lan"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/debian-test.lan\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "appstore.experimental.enabled": false,
        "maintenance": false,
        "loglevel": 2
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### ownCloud log (data/owncloud.log)

no log entries are created when doing the  GET

**Comment by nickvergessen** [comment]
Did you create the contact or assign the groups with the owncloud contacts app, or with another app, e.g. phone

**Comment by rfc2822** [comment]
Doesn't matter, the problem occurs in both cases (just tested).

**Comment by DeepDiver1975** [comment]
> Doesn't matter, the problem occurs in both cases (just tested).

It should make a difference - the vcard is not touched by the backend code.

**Comment by nickvergessen** [comment]
I can see this in the contacts app, it sends the invalid `\,` in the vcard to the server.

**Comment by DeepDiver1975** [comment]
so this is an error in contacts and has to be reported there - https://github.com/owncloud/contacts

most probably this is related to the used vcard library - we has simiar issue in the past already

**Comment by nickvergessen** [comment]
Reported in https://github.com/owncloud/contacts/issues/433
