### ISSUE TITLE
renamed filename does not get changed on shared file on origin

### ISSUE THREAD

**Issue by duckdiver** [owncloud/core#25031]
### Steps to reproduce
1. Share a file with internal AD-user or external use, allow to change file
2. receiving user renames the filename
3. filename gets not renamed on origin user portal 
4. so there are different filename but the File Rights still are available

### Expected behaviour
Tell us what should happen

i would expect that the filename will also change on the origin usersite

### Actual behaviour
Tell us what happens instead

filename will stay the same on origin usersite, but on the shared usersite the new filename will be displayed

### Server configuration
**Operating system**:

Linux 

**Web server:**
mysql

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
V9.0.2

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by nickvergessen** [comment]
That is basically the expected behaviour. This is even necessary, because otherwise if a user receives two shares form two people with the same name, it would trigger a rename for one of the shares and a whole set of renames (even circulary) would trigger.
