### ISSUE TITLE
Consolidate device token with session

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25059]
When using clients like cadaver, no cookies are used. So even with a device token, it will generate a new authentication every time.

One idea would be to find a way to make the same device token reuse the same session.
Not sure about security implications though.

As discussedon IRC @ChristophWurst @DeepDiver1975 @guruz @rullzer

**Comment by ChristophWurst** [comment]
How about something like https://github.com/owncloud/core/pull/24742?

**Comment by PVince81** [comment]
Yeah, that would make sense because the non-cookies clients cannot be kicked out anyway since they will re-auth. They can still be kicked out by revoking the device token instead of the session token.

**Comment by guruz** [comment]
@PVince81 You mean session ID not token right?

**Comment by PVince81** [comment]
yeah, session ID (which is internally mapped by a session token I believe)

**Comment by PVince81** [comment]
Some arguments against the consolidation: some people might use the device token for multiple apps on the same device. For example on an Android phone: use the same device token for CalDAV sync and also for the official mobile client.

**Comment by PVince81** [comment]
Another idea: if a client only ever sent a single request with a single session/auth, don't show this one in the UI. This would usually mean that the client doesn't support sessions.
A client that does would send at least 2 requests with the same session/cookie.

**Comment by PVince81** [comment]
also: have those single-request-session ones expire more quickly then the ones with more than one request ?

**Comment by ChristophWurst** [comment]
> Another idea: if a client only ever sent a single request with a single session/auth, don't show this one in the UI. This would usually mean that the client doesn't support sessions.
> A client that does would send at least 2 requests with the same session/cookie.

Isn't that exactly what the cookie magic in https://github.com/owncloud/core/pull/24742 does?


> also: have those single-request-session ones expire more quickly then the ones with more than one request ?

I wouldn't even create tokens for those connections. Only if the cookie is set (second request if client supports them) we should create the session token.

However, https://github.com/owncloud/core/pull/24742#issuecomment-225173484 could be a solution.
