### ISSUE TITLE
OC\Share20\Share could not be converted to string

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#25065]
### Steps to reproduce
1. `OCP\Share::getShareByToken($token, false);`

### Expected behaviour

I should be getting a "linkitem"

### Actual behaviour

An exception is raised

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:** 7.0.7

**ownCloud version:** master

### Logs

```
  [Doctrine\DBAL\DBALException] An exception occurred while executing 'SELECT * FROM `oc_share` WHERE `token` = ? LIMIT 1' with params [{}]:

Object of class OC\Share20\Share could not be converted to string
                                                                                                                                                         
#1  /3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php:174
#2  /lib/private/legacy/db/statementwrapper.php:73
#3  /lib/private/Share/Share.php:512
#4  /lib/public/Share.php:191
```

**Comment by rullzer** [comment]
What is the actual code you try to call? Because this looks like you want to pass a new share into the old sharing code.

**Comment by oparoz** [comment]
>Because this looks like you want to pass a new share into the old sharing code.

And that's what I don't understand. I'm just retrieving a share via `OCP\Share::getShareByToken`. It has nothing to do with Share 2.0

https://github.com/owncloud/gallery/blob/0f4df90a064bee39d7330cd04fcf906ab23417fb/tests/integration/GalleryIntegrationTest.php#L128

**Comment by oparoz** [comment]
False alarm, I didn't pay attention to the fact that creating a share doesn't return a token any more with Share 2.0

**Comment by rullzer** [comment]
@oparoz yeah it returns a share object. I would suggest btw that you use the sharemanager for all operations btw.

**Comment by oparoz** [comment]
@rullzer - That's what I ended up doing as it was on the cards anyway
