### ISSUE TITLE
Webdav + Microsoft Office is producing errors

### ISSUE THREAD

**Issue by n3m3s1s** [owncloud/core#25066]
### Steps to reproduce
1. Setup Owncloud from Repository
2. Use Nginx (just deactivated apache and setup nginx)
3. Enable Encryption Module
4. Use Owncloud clients on OS X
5. Use Microsoft Office in it

### Expected behavior
Normal Sync

### Actual behavior
I get a lot of errors. Though everyone is using the same system and the same client, just two clients produce a lot of errors. I cannot reproduce them it just seems to randomly happen. One client is able to correspond with me through a shared folder. He just sometimes cannot sync a file he saved. The other client is not able to sync anything at all. 
My client is not producing any error at all.
The errors are blow.

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
nginx
**Database:**
sqlite3
**PHP version:**
PHP 5.5.9-1ubuntu4.17
**ownCloud version:** (see ownCloud admin page)
9.0.2 (from Repository)
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
repository
**Signing status (ownCloud 9.0 and above):**
?
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
Calendar, Activity, Collaborative tags, comments, Default encryption module, Deleted Files, Federation, First Run Wizard, Gallery, Mail Template Editor, Notifications, PDF Viewer, Provisioning API, Share Files, Text Editor, Update notification, Versions, Video Player

(So basically standard + Calendar + Encryption)
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocw26smheqbc",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "whatever.tld"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/whatever.tld",
        "dbtype": "sqlite3",
        "version": "9.0.2.2",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "test.supervisor",
        "mail_smtpmode": "smtp",
        "mail_domain": "whatever.com",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "imap.whatever.com",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "loglevel": 1
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
Yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Official Owncloud Client so probably Webdav

### Client configuration
**Browser:**
Browser works. ownCloud Client version: 2.1.1
**Operating system:**
OS X El Capitan
#### Web server error log
```
Insert your webserver log here
```
[error] 21449#0: *28194 access forbidden by rule, client: x.x.x.x, server: example.tld, request: "GET /data/.ocdata HTTP/1.1", host: "example.tld"
2016/06/10 05:00:06 [error] 21447#0: *28578 access forbidden by rule, client: x.x.x.x, server: example.tld, request: "GET /data/.ocdata HTTP/1.1", host: "example.tld"
2016/06/10 05:47:09 [error] 21447#0: *28798 access forbidden by rule, client: x.x.x.x, server: example.tld, request: "GET /data/.ocdata HTTP/1.1", host: "example.tld"
2016/06/10 05:51:53 [error] 21447#0: *28824 access forbidden by rule, client: x.x.x.x, server: example.tld, request: "GET /data/.ocdata HTTP/1.1", host: "example.tld"
2016/06/10 11:38:15 [error] 21447#0: *29880 access forbidden by rule, client: x.x.x.x, server: example.tld, request: "GET /data/.ocdata HTTP/1.1", host: "example.tld"
#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
Fatal,webdav:
Exception: {"Message":"HTTP/1.1 423 “filename“ is locked","Exception":"OCA\DAV\Connector\Sabre\Exception\FileLocked","Code":0,"Trace":"#0 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(1070): OCA\DAV\Connector\Sabre\File->put(Resource id #47)
#1 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(511): Sabre\DAV\Server->updateFile(‚filename‘, Resource id #47, NULL)
#2 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#3 /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#4 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(459): Sabre\Event\EventEmitter->emit('method:PUT', Array)
#5 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#6 /var/www/owncloud/apps/dav/appinfo/v1/webdav.php(55): Sabre\DAV\Server->exec()
#7 /var/www/owncloud/remote.php(138): require_once('/var/www/ownclo...')
#8 {main}","File":"/var/www/owncloud/apps/dav/lib/connector/sabre/file.php","Line":174,"User“:“username“}

______________
Error, no App in context:

Exception: {"Exception":"OCP\Lock\LockedException","Message":"\"filename\" is locked","Code":0,"Trace":"#0 /var/www/owncloud/lib/private/files/view.php(1956): OC\Files\View->lockPath('/files/filename...', 1, false)
#1 /var/www/owncloud/lib/private/files/view.php(803): OC\Files\View->lockFile('/files/filename...', 1)
#2 /var/www/owncloud/apps/files_versions/lib/storage.php(193): OC\Files\View->copy('files//filename...', 'files_versions/...')
#3 /var/www/owncloud/apps/files_versions/lib/hooks.php(60): OCA\Files_Versions\Storage::store('/filename ...')
#4 [internal function]: OCA\Files_Versions\Hooks::write_hook(Array)
#5 /var/www/owncloud/lib/private/hook.php(105): call_user_func(Array, Array)
#6 /var/www/owncloud/lib/private/filechunking.php(215): OC_Hook::emit('OC_Filesystem', 'write', Array)
#7 /var/www/owncloud/apps/dav/lib/connector/sabre/file.php(436): OC_FileChunking->file_assemble(Object(OCA\Files_Trashbin\Storage), 'foldername...', '/username/files/filename...')
#8 /var/www/owncloud/apps/dav/lib/connector/sabre/file.php(103): OCA\DAV\Connector\Sabre\File->createFileChunked(Resource id #47)
#9 /var/www/owncloud/apps/dav/lib/connector/sabre/directory.php(134): OCA\DAV\Connector\Sabre\File->put(Resource id #47)
#10 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(1036): OCA\DAV\Connector\Sabre\Directory->createFile('filename...', Resource id #47)
#11 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(523): Sabre\DAV\Server->createFile('filename...', Resource id #47, NULL)
#12 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#13 /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#14 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(459): Sabre\Event\EventEmitter->emit('method:PUT', Array)
#15 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#16 /var/www/owncloud/apps/dav/appinfo/v1/webdav.php(55): Sabre\DAV\Server->exec()
#17 /var/www/owncloud/remote.php(138): require_once('/var/www/ownclo...')
#18 {main}","File":"/var/www/owncloud/lib/private/files/view.php","Line":1858}

____________________
Fatal, WebDav
Exception: {"Message":"An exception occurred while executing 'UPDATE \"oc_filecache\" SET \"storage\" = ?, \"path\" = ?, \"path_hash\" = ?, \"name\" = ?, \"parent\" =? WHERE \"fileid\" = ?' with params [\"4\", \"filename\", \"bf9e3b29283a65bbeec16eb454a3c613\", \"filename\", -1, 1070]:

SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_filecache.storage, oc_filecache.path_hash","Exception":"Doctrine\DBAL\Exception\UniqueConstraintViolationException","Code":0,"Trace":"#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(116): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(836): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE \"oc_file...', Array)
#2 /var/www/owncloud/lib/private/db/connection.php(184): Doctrine\DBAL\Connection->executeQuery('UPDATE \"oc_file...', Array, Array, NULL)
#3 /var/www/owncloud/lib/private/files/cache/cache.php(527): OC\DB\Connection->executeQuery('UPDATE `*PREFIX...', Array)
#4 /var/www/owncloud/lib/private/files/cache/wrapper/cachewrapper.php(183): OC\Files\Cache\Cache->moveFromCache(Object(OC\Files\Cache\HomeCache), 'files/filename...', 'foldername...')
#5 /var/www/owncloud/lib/private/files/cache/updater.php(186): OC\Files\Cache\Wrapper\CacheWrapper->moveFromCache(Object(OC\Files\Cache\HomeCache), 'files/filename...', 'foldername...')
#6 /var/www/owncloud/lib/private/files/view.php(321): OC\Files\Cache\Updater->renameFromStorage(Object(OCA\Files_Trashbin\Storage), 'files/filename...', 'foldername...')
#7 /var/www/owncloud/lib/private/files/view.php(746): OC\Files\View->renameUpdate(Object(OCA\Files_Trashbin\Storage), Object(OCA\Files_Trashbin\Storage), 'files/filename...', 'foldername...')
#8 /var/www/owncloud/apps/dav/lib/connector/sabre/objecttree.php(241): OC\Files\View->rename('filename...', 'filename...')
#9 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(640): OCA\DAV\Connector\Sabre\ObjectTree->move('Filename...', 'filename...')
#10 [internal function]: Sabre\DAV\CorePlugin->httpMove(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#11 /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#12 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(459): Sabre\Event\EventEmitter->emit('method:MOVE', Array)
#13 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#14 /var/www/owncloud/apps/dav/appinfo/v1/webdav.php(55): Sabre\DAV\Server->exec()
#15 /var/www/owncloud/remote.php(138): require_once('/var/www/ownclo...')
#16 {main}","File":"/var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php","Line":48,"User":"anotheruser"}

_________
Fatal, WebDav
Exception: {"Message":"Bad Signature","Exception":"OC\HintException","Code":0,"Trace":"#0 /var/www/owncloud/apps/encryption/lib/crypto/crypt.php(463): OCA\Encryption\Crypto\Crypt->checkSignature('/ENi56RX96ZjMXV...', '???i??>??????e9...', 'f87105308f80173...')
#1 /var/www/owncloud/apps/encryption/lib/crypto/encryption.php(363): OCA\Encryption\Crypto\Crypt->symmetricDecryptFileContent('/ENi56RX96ZjMXV...', '???i??>??????e9...', 'AES-256-CTR', 0, 0)
#2 /var/www/owncloud/lib/private/files/stream/encryption.php(459): OCA\Encryption\Crypto\Encryption->decrypt('/ENi56RX96ZjMXV...', 0)
#3 /var/www/owncloud/lib/private/files/stream/encryption.php(290): OC\Files\Stream\Encryption->readCache()
#4 [internal function]: OC\Files\Stream\Encryption->stream_read(8192)
#5 /var/www/owncloud/lib/private/helper.php(315): fread(Resource id #85, 8192)
#6 /var/www/owncloud/lib/private/files/storage/wrapper/encryption.php(744): OC_Helper::streamCopy(Resource id #85, Resource id #95)
#7 /var/www/owncloud/lib/private/files/storage/wrapper/encryption.php(641): OC\Files\Storage\Wrapper\Encryption->copyBetweenStorage(Object(OCA\Files_Trashbin\Storage), 'files_trashbin/...', 'files_trashbin/...', false, false)
#8 /var/www/owncloud/lib/private/files/storage/wrapper/wrapper.php(544): OC\Files\Storage\Wrapper\Encryption->copyFromStorage(Object(OCA\Files_Trashbin\Storage), 'files_trashbin/...', 'files_trashbin/...')
#9 /var/www/owncloud/lib/private/files/view.php(840): OC\Files\Storage\Wrapper\Wrapper->copyFromStorage(Object(OCA\Files_Trashbin\Storage), 'files_trashbin/...', 'files_trashbin/...')
#10 /var/www/owncloud/apps/files_trashbin/lib/trashbin.php(757): OC\Files\View->copy('username/files_trashb...', 'anotheruser/files_t...')
#11 /var/www/owncloud/apps/files_trashbin/lib/trashbin.php(180): OCA\Files_Trashbin\Trashbin::copy_recursive('username/files_trashb...', 'anotheruser/files_t...', Object(OC\Files\View))
#12 /var/www/owncloud/apps/files_trashbin/lib/trashbin.php(264): OCA\Files_Trashbin\Trashbin::copyFilesToUser('/filename ...', 'username', 'filename...', 'anotheruser', 1465372022)
#13 /var/www/owncloud/apps/files_trashbin/lib/storage.php(160): OCA\Files_Trashbin\Trashbin::move2trash('filename...')
#14 /var/www/owncloud/apps/files_trashbin/lib/storage.php(95): OCA\Files_Trashbin\Storage->doDelete('foldername...', 'unlink')
#15 /var/www/owncloud/lib/private/files/view.php(1063): OCA\Files_Trashbin\Storage->unlink('foldername...')
#16 /var/www/owncloud/lib/private/files/view.php(645): OC\Files\View->basicOperation('unlink', '/filename ...', Array)
#17 /var/www/owncloud/apps/dav/lib/connector/sabre/file.php(333): OC\Files\View->unlink('/filename ...')
#18 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Tree.php(179): OCA\DAV\Connector\Sabre\File->delete()
#19 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(635): Sabre\DAV\Tree->delete('filename...')
#20 [internal function]: Sabre\DAV\CorePlugin->httpMove(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#21 /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#22 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(459): Sabre\Event\EventEmitter->emit('method:MOVE', Array)
#23 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#24 /var/www/owncloud/apps/dav/appinfo/v1/webdav.php(55): Sabre\DAV\Server->exec()
#25 /var/www/owncloud/remote.php(138): require_once('/var/www/ownclo...')
#26 {main}","File":"/var/www/owncloud/apps/encryption/lib/crypto/crypt.php","Line":483,"User":"anotheruser"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
No browser problems...

Any suggestions?

**Comment by tflidd** [comment]
I would use a real database https://doc.owncloud.org/server/9.0/admin_manual/installation/installation_wizard.html#database-choice, two clients and parallel uploads could already be too much for sqlite.

I wouldn't turn on the encryption app because you are not using external storage (shouldn't be related to your problem): https://doc.owncloud.org/server/9.0/admin_manual/configuration_files/encryption_configuration.html?highlight=encryption

**Comment by nickvergessen** [comment]
Yeah the lock and the database error should be solvable by switching to a different DB.

**Comment by nickvergessen** [comment]
For the bad signature issue see https://github.com/owncloud/core/issues/24620

**Comment by nickvergessen** [comment]
I think we can close this?

**Comment by n3m3s1s** [comment]
Ok so that is a Bug to be fixed? I'll then just wait for the fix.
I just migrated to the new Database and we're now producing much less errors. The only one that just popped up is this:
Error	PHP	Undefined index: path at /var/www/owncloud/apps/files_sharing/lib/cache.php#83

Wich has been reported here: #24919 
Since there seems to be no fix so far, we can close this thread.
Thanks again
