### ISSUE TITLE
Ubuntu 16.04 packages of 8.2 depend on (unavailable) php5?

### ISSUE THREAD

**Issue by emmenlau** [owncloud/core#25072]
### Steps to reproduce
1. `echo 'deb http://download.owncloud.org/download/repositories/8.2/Ubuntu_16.04/ /'| sudo tee /etc/apt/sources.list.d/owncloud.list`
2. `sudo apt-get update`
3. `sudo apt-get install --force-yes owncloud=8.2.5-1.1 owncloud-server=8.2.5-1.1`

### Expected behaviour
owncloud 8.2 should get installed.

### Actual behaviour
owncloud 8.2 can not be installed.
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud-server : Depends: php5 (>= 5.4.0) but it is not installable
                   Depends: php5-mysqlnd but it is not installable or
                            php5-mysql but it is not installable
                   Depends: php5-sqlite but it is not installable
                   Depends: php5-pgsql but it is not installable
                   Depends: php5-common but it is not installable
                   Depends: php5-gd but it is not installable
                   Depends: php5-intl but it is not installable
                   Depends: php5-mcrypt but it is not installable
                   Depends: php5-curl but it is not installable
                   Depends: php5-json but it is not installable
                   Depends: php5-ldap but it is not installable
                   Depends: php5-cli but it is not installable
                   Depends: php5-cgi but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### Server configuration
**Operating system**: Ubuntu 16.04 amd64

**Comment by Kawohl** [comment]
@emmenlau ubuntu 16.04 doesn't provide php5 it uses php7  

@jnweiger we need to use php7 instead of php5 dependencies.

**Comment by emmenlau** [comment]
It would be awesome if you could make a php7 release of 8.2 for Ubuntu 16.04. Highly appreciated!
Note that mysql was also updated by a minor version.

**Comment by jnweiger** [comment]
@emmenlau please try instead:
```
apt-get install owncloud-files
```
This package installs the complete owncloud code, but without any dependencies. 
So you need to look after the required php7 deps yourself. Would that work for you?

**Comment by emmenlau** [comment]
Perfect, this solves the issue for me! I did:
```
sudo apt-get install owncloud-files=8.2.5-1.1 owncloud-deps-php7.0
```
and could upgrade owncloud from 8.1 to 8.2 without problems. Then it was easy to install 9.0:
```
sudo apt-get install owncloud
```
and finally upgrade the database to 9.0. Thanks!
