### ISSUE TITLE
Constraint violation insert into filecache / upload many small files

### ISSUE THREAD

**Issue by chrsch** [owncloud/core#25070]
Hi all,

I've been struggling with this issue for days now. This is not exactly a new topic but I have worked through all suggestions and tickets I was able to find on github and elsewhere without success.

Tickets probably relates:
https://github.com/owncloud/core/issues/18502 // Suggestion is to use filesystem_check_changes => 0; in config.php --> No difference for me whether 1 or 2
https://github.com/owncloud/core/issues/13934 // Suggestion is to ensure MariaDB transaction isolation is READ-COMITTED. Was REPEATABLE-READ for me, but switching to READ-COMITTED didn't make a difference for me at all.
https://github.com/owncloud/core/issues/19068 // Solution here was turn on file locking via redis --> Didn't solve the problem for me, I already have file locking via redis. Turning file lockin on/off didn't make a difference. Also tried locking without redis.
https://github.com/owncloud/core/issues/14701 // Just related with a good summary by @DeepDiver1975 what may be going on.
### Steps to reproduce
1. Get some folder with many small file, e. g. node js project. E. .g clone https://github.com/linnovate/mean
2. Setup a sync folder to sync the cloned repository to ownCloud
3. Wait some time for the insert into filecache error to pop up, will happen within 1-2 minutes with a server configuration providing good performance
### Expected behaviour

The upload must finish without errors.
### Actual behaviour

There are "Insert into filecache.. constraint violation duplicate entry" errors from time to time on random files.
### Server configuration

**Operating system**: 
Ubuntu 14.04 LTS

**Web server:** 
Apache 2.4.7 with modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php5_module (shared)
 proxy_module (shared)
 proxy_http_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)

**Database:** 
Maria DB Galera Cluster Maser-Master Active-Backup
Maria DB: Ver 15.1 Distrib 5.5.49-MariaDB
wsrep_provider_version, 25.3.15(r3578)

**PHP version:**
5.6.22 with modules 
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib
[Zend Modules]
Zend OPcache

**ownCloud version:**
9.0.2

**Updated from an older ownCloud or fresh install:**
Update from 8.2.5

**Where did you install ownCloud from:**
Manual

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Enabled:
- activity: 2.2.1
- bookmarks: 0.7
- calendar: 1.2.2
- comments: 0.2
- contacts: 1.3.1.0
- dav: 0.1.6
- encryption: 1.2.0
- federatedfilesharing: 0.1.0
- federation: 0.0.4
- files: 1.4.4
- files_pdfviewer: 0.8.1
- files_sharing: 0.9.1
- files_texteditor: 2.1
- files_trashbin: 0.8.0
- files_versions: 1.2.0
- files_videoplayer: 0.9.8
- galleryplus: 15.0.0
- imprint: 0.2.5
- mail: 0.5.1
- news: 8.8.0
- notifications: 0.2.3
- passwords: 18.0
- provisioning_api: 0.4.1
- systemtags: 0.2
- templateeditor: 0.1
- updatenotification: 0.1.0
  Disabled:
- documents
- external
- files_clipboard
- files_external
- firstrunwizard
- gallery
- user_external
- user_ldap
- user_otp
- user_rcdevsopenotp

**The content of config/config.php:**
{
    "system": {
        "instanceid": "xxxxxxxxxx",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "xxxxxxxxxx"
        ],
        "datadirectory": "\/var\/xxxxxxxxx",
        "overwrite.cli.url": "https:\/\/xxxxxxxxxx",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "xxxxxxxxx",
        "dbhost": "xxxxxxxxx",
        "dbtableprefix": "",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "mail_domain": "xxxxxxxxx",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "xxxxxxxxxx",
        "mail_smtpport": "25",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtppassword": "**_REMOVED SENSITIVE VALUE**_",
        "mail_from_address": "no-reply",
        "forcessl": true,
        "default_language": "de",
        "asset-pipeline.enabled": false,
        "activity_expire_days": 360,
        "theme": "xxxxxxxxxx",
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",
        "memcache.local": "\OC\Memcache\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\OC\Memcache\Redis",
        "memcache.locking": "\OC\Memcache\Redis",
        "redis": {
            "host": "xxxxxxxxxx",
            "port": 6389,
            "timeout": 0,
            "dbindex": 0,
            "password": "xxxxxxxxx"
        },
        "maintenance": false,
        "loglevel": "0",
        "singleuser": false,
        "filesystem_check_changes": 0
    }
}

**Are you using external storage, if yes which one:**
no

**Are you using encryption:**
yes

**Are you using an external user-backend, if yes which one:**
no
### Client configuration

**Browser:**
Chrome 51

**Operating system:**
Windows 10
#### Web server error log

No errrors in apache2 log
#### ownCloud log (data/owncloud.log)

no errors in owncloud.log on loglevel 0...
#### ownCloud Client log

[owncloud.log.zip](https://github.com/owncloud/core/files/317158/owncloud.log.zip)

**Comment by tflidd** [comment]
Just a small reminder of this topic I opened: https://github.com/owncloud/core/issues/20967
In the end we were testing with about 10000 files, they were uploading without problems it just took some time. But I didn't see such problems (even on OC 9.0beta1). I will see if I can find this vserver-image and retest on OC 9.0.2.

There is a similar report (https://github.com/owncloud/core/issues/25066) but on a completely different setup (sqlite, nginx, encryption on, client 2.1.1 on OS X).

**Comment by nickvergessen** [comment]
Which tables are affected, only filecache?

**Comment by chrsch** [comment]
@nickvergessen Yes only filecache table is affected. No other errors.

**Comment by chrsch** [comment]
@DeepDiver1975 Sorry for being unspecific at this point. The error is logged in the ownCloud client. I can provide a client log if this is of any help.

Basically it is the error shown in the attached screenshot happening from time to time for random files. I just reproduced this by syncing a node js project to an empty folder in the cloud.

![2016-06-13 18_50_03-info-center](https://cloud.githubusercontent.com/assets/198256/16015978/9acbdb98-3198-11e6-9139-a514c5eb4e40.png)

**Comment by chrsch** [comment]
Added the client log, sorry for the delay. This is the corresponding log to the screenshot posted before. If you need any further information let me know.

**Comment by chrsch** [comment]
Any news on this?

**Comment by chrsch** [comment]
This problem persists with OC 9.0.3 and Client 2.2.2.

**Comment by PVince81** [comment]
This can likely only happen in highly parallel environment where multiple PHP requests are trying to insert the same entry at the same time for some reason.

Transactional file locking and the database transaction isolation mode should protect from this.
However you reported that it still happens in your env.

I also find it unlogical that several processes would write the exact same database entry at the same time. In the past it used to be due to the background scanner finding an entry on disk that was added by another process while that other process didn't update the DB yet, so they'd both insert the entry. But with `filesystem_check_changes` set to 0 (and the locking changes) this shouldn't happen either.

So far I have no idea what else it could be.

**Comment by PVince81** [comment]
When looking into a similar issue with locking https://github.com/owncloud/core/pull/25512 I found that sometimes one must expect a "Duplicate entry" situation due to race conditions when using `insertIfNotExist`.

Considering that this situation is normal, we need to find a way for the file cache code to detect this and recover, and prevent this error to reach the user.

In the case of locking, it would recover by doing an UPDATE after detecting the error instead of insert.

**Comment by joeyjy** [comment]
I met the same problem, it seems to occur randomly, I enabled encryption module and using objectstorage, also set 'filesystem_check_changes' => 0 and using transactional file locking...
When stuff sync many small files using desktop client, it randomly pops out such error, duplicate entry when insert into balabala

**Comment by joeyjy** [comment]
@PVince81 If I use 'INSERT IGNORE' or 'ON DUPLICATE KEY UPDATE', does it matter? if it will damage the system?

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
Note, 10.0.5 will have upsert which will hopefully fix this, see #28698
