### ISSUE TITLE
Cron fails: "another instance of cron.php is still running", yet no lock file

### ISSUE THREAD

**Issue by vasyugan** [owncloud/core#25086]
### Steps to reproduce
 If I knew how a third party can reproduce the issue, I would probably know what causes it, which I don't.

Yet this is the local setup:

Apache running in an LXC container with Ubuntu Trusty with apache at package version 2.4.7-1ubuntu4.9, It is using a suexec ftp setup, where for each user, it is running in a chroot under their respective UID.

The following apache packages are installed:

ii  apache2                               2.4.7-1ubuntu4.9                    amd64        Apache HTTP Server
ii  apache2-bin                           2.4.7-1ubuntu4.9                    amd64        Apache HTTP Server (binary files and modules)
ii  apache2-data                          2.4.7-1ubuntu4.9                    all          Apache HTTP Server (common files)
ii  apache2-mpm-prefork                   2.4.7-1ubuntu4.9                    amd64        transitional prefork MPM package for apache2
ii  apache2-suexec-pristine               2.4.7-1ubuntu4.9                    amd64        Apache HTTP Server standard suexec program for mod_suexec
ii  apache2-utils                         2.4.7-1ubuntu4.9                    amd64        Apache HTTP Server (utility programs for web servers)
rc  apache2.2-common                      2.2.22-1ubuntu1.8                   amd64        Apache HTTP Server common files
ii  libapache2-mod-fcgid                  1:2.3.9-1                           amd64        FastCGI interface module for Apache 2
ii  libapache2-mod-geoip                  1.2.8-2                             amd64        GeoIP support for apache2
ii  libapache2-mod-svn                    1.8.8-1ubuntu3.2                    amd64        Apache Subversion server modules for Apache httpd

the following php packages are installed:

ii  php-auth-sasl                         1.0.6-1                             all          Abstraction of various SASL mechanism responses
ii  php-mail-mime                         1.8.8-1                             all          PHP PEAR module for creating MIME messages
ii  php-mail-mimedecode                   1.5.5-2                             all          Provides a class to decode mime messages
ii  php-net-smtp                          1.6.1-1                             all          PHP PEAR module implementing SMTP protocol
ii  php-net-socket                        1.0.14-1                            all          PHP PEAR Network Socket Interface module
ii  php-pear                              5.5.9+dfsg-1ubuntu4.17              all          PEAR - PHP Extension and Application Repository
ii  php5                                  5.5.9+dfsg-1ubuntu4.17              all          server-side, HTML-embedded scripting language (metapackage)
ii  php5-cgi                              5.5.9+dfsg-1ubuntu4.17              amd64        server-side, HTML-embedded scripting language (CGI binary)
ii  php5-cli                              5.5.9+dfsg-1ubuntu4.17              amd64        command-line interpreter for the php5 scripting language
ii  php5-common                           5.5.9+dfsg-1ubuntu4.17              amd64        Common files for packages built from the php5 source
ii  php5-curl                             5.5.9+dfsg-1ubuntu4.17              amd64        CURL module for php5
ii  php5-dev                              5.5.9+dfsg-1ubuntu4.17              amd64        Files for PHP5 module development
ii  php5-gd                               5.5.9+dfsg-1ubuntu4.17              amd64        GD module for php5
ii  php5-imap                             5.4.6-0ubuntu5                      amd64        IMAP module for php5
ii  php5-intl                             5.5.9+dfsg-1ubuntu4.17              amd64        internationalisation module for php5
ii  php5-json                             1.3.2-2build1                       amd64        JSON module for php5
ii  php5-ldap                             5.5.9+dfsg-1ubuntu4.17              amd64        LDAP module for php5
ii  php5-mcrypt                           5.4.6-0ubuntu5                      amd64        MCrypt module for php5
ii  php5-mysql                            5.5.9+dfsg-1ubuntu4.17              amd64        MySQL module for php5
ii  php5-oauth                            1.2.3-1build1                       amd64        OAuth 1.0 consumer and provider extension
ii  php5-readline                         5.5.9+dfsg-1ubuntu4.17              amd64        Readline module for php5
rc  php5-redis                            2.2.4-1build2                       amd64        PHP extension for interfacing with Redis
ii  php5-sqlite                           5.5.9+dfsg-1ubuntu4.17              amd64        SQLite module for php5
rc  php5-suhosin                          0.9.33-1                            amd64        advanced protection module for php5
ii  pkg-php-tools                         1.11                                all          various packaging tools and scripts for PHP packages

ownCloud uses redis for memory caching.

Cronjobs are executed by the system crond.

The data directory is outside the webserver root

Mysql is used for the database

### Expected behaviour
Tell us what should happen

cronjobs should continue to work as they did until 20 days ago,

### Actual behaviour
Tell us what happens instead

running cron.php by php cli immediately fails with the message "another instance of cron.php is still running". Strangely, there is no lock file in the data directory. I looked into the code and it seems that there is where I should expect the file:

                $config = OC::$server->getConfig();
                $instanceId = $config->getSystemValue('instanceid');
                $lockFileName = 'owncloud-server-' . $instanceId . '-cron.lock';
                $lockDirectory = $config->getSystemValue('cron.lockfile.location', sys_get_temp_dir());
                $lockDirectory = rtrim($lockDirectory, '\\/');
                $lockFile = $lockDirectory . '/' . $lockFileName;

### Server configuration
Ubuntu Trusty in LXC
Apache 2.4.7 FPM Suexec

**Database:**

Mysql

**PHP version:**
5.5.9
**ownCloud version:** (see ownCloud admin page)

ownCloud 8.2.5 (stable) 

**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**
downloaded tarball from ownclould.org

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
 Activity 2.1.4
von Frank Karlitschek, Joas Schilling (AGPL-Lizenziert)
Offiziell
Beschreibung anzeigen…

Deleted files 0.7.0
von Bjoern Schiessle (AGPL-Lizenziert)
Offiziell
Beschreibung anzeigen…

External Sites 1.2
von Frank Karlitschek (AGPL-Lizenziert)
Offiziell
Beschreibung anzeigen…
Nur für bestimmte Gruppen aktivieren
First Run Wizard 1.1
von Frank Karlitschek, Jan-Christoph Borchardt (AGPL-Lizenziert)
Offiziell
Beschreibung anzeigen…
Nur für bestimmte Gruppen aktivieren
Mail 0.5.1
von Thomas Müller, Jan-Christoph Borchardt, Christoph Wurst, Steffen Lindner, Lukas Reschke, Thomas Imbreckx, Robin McCorkell, Clement Wong & many more … (AGPL-Lizenziert)
Offiziell
Beschreibung anzeigen…
Nur für bestimmte Gruppen aktivieren
Notifications 0.1.0
von Joas Schilling (AGPL-Lizenziert)
Offiziell
Beschreibung anzeigen…

PDF Viewer 0.7.1
von Thomas Müller, Lukas Reschke (AGPL-Lizenziert)
Offiziell
Beschreibung anzeigen…
Nur für bestimmte Gruppen aktivieren
Provisioning API 0.3.0
von Tom Needham (AGPL-Lizenziert)
Offiziell
Beschreibung anzeigen…

Share Files 0.7.0
von Michael Gapczynski, Bjoern Schiessle (AGPL-Lizenziert)
Offiziell
Beschreibung anzeigen…

Text Editor 2.0
von Tom Needham, Björn Schießle (AGPL-Lizenziert)
Offiziell
Beschreibung anzeigen…
Nur für bestimmte Gruppen aktivieren
Updater 0.6
von Victor Dubiniuk (AGPL-Lizenziert)
Offiziell
Beschreibung anzeigen…
Nur für bestimmte Gruppen aktivieren
Versions 1.1.0
von Frank Karlitschek, Bjoern Schiessle (AGPL-Lizenziert)
Offiziell
Beschreibung anzeigen…

Video Viewer 0.1.3
von Victor Dubiniuk (AGPL-Lizenziert)
Offiziell
Beschreibung anzeigen…
Nur für bestimmte Gruppen aktivieren
Calendar 0.8.2
von Georg Ehrke, Bart Visscher, Jakob Sack (AGPL-Lizenziert)
Geprüft
Beschreibung anzeigen…
Nur für bestimmte Gruppen aktivieren
Contacts 0.5.0.0
von Jakob Sack,Thomas Tanghus (AGPL-Lizenziert)
Geprüft
Beschreibung anzeigen…
Nur für bestimmte Gruppen aktivieren
Documents 0.11.1
von Frank Karlitschek, Victor Dubiniuk (AGPL-Lizenziert)
Geprüft
Beschreibung anzeigen…
Nur für bestimmte Gruppen aktivieren
Gallery+ 15.0.0
von Olivier Paroz, Robin Appelman (AGPL-Lizenziert)
Geprüft
Beschreibung anzeigen…
Nur für 
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration

(N/A)

#### Web server error log
```
Insert your webserver log here
```
N/A
#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:
N/A

**Comment by vasyugan** [comment]
Found a stale lock file in /tmp which I then removed and it continued to work. /tmp is outside of the reach of normal web server users so this seems like a very bad choice.

**Comment by PVince81** [comment]
Hmmm, from what I see the temp file location is configuration and defaults to `sys_get_temp_dir()`.
Maybe that piece of code should have used the `TempManager` instead to get a valid location.

Note that it is possible to configure the cron lock file location in config.php: https://github.com/owncloud/core/blob/v8.2.3/config/config.sample.php#L590

**Comment by DeepDiver1975** [comment]
Furthermore starting with 9.1 multiple cron executors can run in parallel.
