### ISSUE TITLE
Share link send email with old expiration date when date picker still open

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25092]
### Steps
1. Go to the share link panel
2. Tick "Share with link"
3. Type in an email address but don't click "send"
4. Open the date picker for expiration and pick a date D1
5. Close it
6. Open the picker again and change the date to another date D2 directly in the input field (not the picker)
7. Click directly on "Send"
### Expected

Email sent with correct date D2.
### Actual

Email sent with date D1. However after sending the backend still had the date updated to D2 due to the blur event.

@rullzer @michaelstingl

**Comment by michaelstingl** [comment]
@PVince81 Who can help here? @felixheidecke ?

**Comment by felixheidecke** [comment]
I'll have a look.

**Comment by felixheidecke** [comment]
This is *probably* because `click` is triggered ahead of `blur`. Fixing PR will follow.

**Comment by felixheidecke** [comment]
Well … tougher than I thought :sweat_smile:

**Comment by Kawohl** [comment]
@felixheidecke any update?

**Comment by cdamken** [comment]
> @felixheidecke any update?

Ping

**Comment by butonic** [comment]
@felixheidecke can you elaborate on what causes the problem maybe someone else can take over. This is getting old?

**Comment by felixheidecke** [comment]
Sorry, no update so far. There are too many other tasks currently. :-(

**Comment by butonic** [comment]
can you elaborate on what the problem is so someone else may take over.

**Comment by cdamken** [comment]
Probably this explanation helps:

---

I just tested this in OC9.1.5 - still broken. The expiry date jumped back to May 11th immediately after I hit the send button. However, the email still contains the incorrect date (in this case May 25th).

**Comment by PVince81** [comment]
will be obsoleted in 10.0 because the flow of the dialog is different...

**Comment by cdamken** [comment]
I will try to reproduce in 10.0

**Comment by PVince81** [comment]
@cdamken did it work correctly with 10.0.2 ?

**Comment by felixboehm** [comment]
@cdamken please follow up. removing green

**Comment by tomneedham** [comment]
Works in OC10
