### ISSUE TITLE
webdav endpoints

### ISSUE THREAD

**Issue by scion4581** [owncloud/core#25112]
Sorry about that, but i cant find any docs about webdav endpoints! 

In official manual there are only few methods with CURL create, move file, get list

But where I can get all operation list? Cause I will try to make upload files, delete and so on using dav

Thanks

**Comment by nickvergessen** [comment]
Well I guess easiest is to use something like cadaver, then connect to your webdav endpoint and press tab, then it lists the commands:
```
$ cadaver http://localhost/remote.php/dav/
Authentication required for ownCloud on server `localhost':
Username: admin
Password: 
dav:/remote.php/dav/> 
?           checkout    describe    h           lls         mkcol       open        pwd         showlocks
about       chexec      discover    help        lock        mkdir       propdel     quit        steal
bye         close       echo        history     logout      more        propget     rm          uncheckout
cat         copy        edit        label       lpwd        move        propnames   rmcol       unlock
cd          cp          exit        lcd         ls          mput        propset     search      unset
checkin     delete      get         less        mget        mv          put         set         version
dav:/remote.php/dav/> 
```

Then you can google for each of those commands, e.g. `webdav mkcol` to see what it does and how it works.

Anyway since webdav is a standard and not something from us, I'm closing this.

**Comment by scion4581** [comment]
Oh, many thanks! Last tip, is owncloud dav implementation has some searching of file? 

for example i need get info about only one file. Also I'm trying search command - "There is no handler found for this SEARCH method"

It would be great just something "curl -u user:pass http://owncloud/remote.php/dav/files/user/some_file.jpg"

**Comment by DeepDiver1975** [comment]
> Oh, many thanks! Last tip, is owncloud dav implementation has some searching of file?

We have plans to get this in for 9.2

**Comment by DeepDiver1975** [comment]
> It would be great just something "curl -u user:pass http://owncloud/remote.php/dav/files/user/some_file.jpg"

this is working

**Comment by scion4581** [comment]
@DeepDiver1975 thnks but this command get file, maybe exist some method to get only info about this file?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 thnks but this command get file, maybe exist some method to get only info about this file?

this is done with webdav request PROFIND - which is possible via curl as well

**Comment by houssem-yahiaoui** [comment]
@DeepDiver1975 I'm trying to execute this command :
curl -u user:pass http://owncloud/remote.php/webdav/file.pdf

 with no success, the webdav keep on telling me i have a problem with user and pass

and i want to know, when we interact with owncloud webdav, is there any root directory to add after the webdav like server/ownloud/remote.php/webdav/files or  the /webdav is the root directory ?

**Comment by DeepDiver1975** [comment]
```sh
$ curl -v -u admin:admin http://localhost:8888/remote.php/webdav/welcome.txt
*   Trying ::1...
* Connected to localhost (::1) port 8888 (#0)
* Server auth using Basic with user 'admin'
> GET /remote.php/webdav/welcome.txt HTTP/1.1
> Host: localhost:8888
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Host: localhost:8888
< Connection: close
< X-Powered-By: PHP/5.6.21
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=ko7QhVa4zYexMwUIaG8N9flermXcSL9X1NDgyxPuew2BVyOhJLKrEYIC82ok0rADVpXtqcqAMc6sXJxMI3p9h6Q6%2Bk99icv5fY9TTRPL3L%2Fs4jeP8Hu%2FTDP%2FP2WP7%2FkS; path=/; httponly
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: Sameorigin
< X-Robots-Tag: none
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Content-Security-Policy: default-src 'none';
< Set-Cookie: ocno0mrfi4bp=6r5k5jcpn8acnfmerkj488d0r1; path=/; HttpOnly
< Set-Cookie: cookie_test=test; expires=Wed, 22-Jun-2016 13:18:42 GMT; Max-Age=3600
< Content-type: text/plain;charset=UTF-8
< Last-Modified: Wed, 22 Jun 2016 12:18:08 GMT
< ETag: "06d695a982040888e625ca8a75faa9f7"
< Content-Length: 163
< OC-ETag: "06d695a982040888e625ca8a75faa9f7"
< 
Welcome to your ownCloud account!

This is just an example file for developers and git users. 
The packaged and released versions will come with better examples.

* Closing connection 0

**Comment by houssem-yahiaoui** [comment]
@DeepDiver1975, i made some research and the windows problem thing is a thing apparently, things don't work when i use my windows cmder curl command but it does when i moved to ubuntu. i don't know if there's an issue here about it but I will post anyway. thanks @DeepDiver1975
