### ISSUE TITLE
Prevent emptying trash bin

### ISSUE THREAD

**Issue by mitar** [owncloud/core#25127]
A feature request.

In our setup multiple users share the same account to simply manages files between them. This works pretty well, but we would like to prevent emptying trash bin by that user. So user should be able to upload files, move them around, organize them, and move them to trash, but not delete files from trash itself.

**Comment by PVince81** [comment]
Is there a reason why using sharing wasn't suitable for your use case ?

When using a common share (shared by an admin) every user has their own trashbin. So if a recipient deletes a file, it is copied to both the admin's trashbin and also that user's trashbin.

**Comment by mitar** [comment]
Just because we do not want to deal with user management. It is much easier to share username and password than having individual usernames for everyone.

**Comment by tflidd** [comment]
You could authenticate against an IMAP server...
Or you share the folder from an admin user so the files should still be in the admin's trash.

**Comment by mitar** [comment]
> You could authenticate against an IMAP server...

This does not change the fact that users would have more than one username. So instead of saying: login with this username and password, we would have to add something to IMAP server for each new user, tell them their password.

> Or you share the folder from an admin user so the files should still be in the admin's trash.

And the non-admin user would be also adding files to this same folder? But this complicates things because then people have to know to go to that shared folder and do stuff there, instead in the main folder after login.

**Comment by tflidd** [comment]
I was just supposing you were already running an IMAP server or any other 3rd party authentication supported by nextcloud.

>> Or you share the folder from an admin user so the files should still be in the admin's trash.
> 
> And the non-admin user would be also adding files to this same folder? But this complicates things because then people have to know to go to that shared folder and do stuff there, instead in the main folder after login.

Yes, it is only a workaround.

**Comment by hodyroff** [comment]
Multi-User environment is a core concept of ownCloud. Maybe just work with anonymous links ... or any other type of workaround. But disallowing emptying trash makes no sense. ownCloud is about self-service and also supporting so many authentication mechanisms that something else should fit.
IMHO this can be closed.

**Comment by mitar** [comment]
There are different use cases, not sure why one would be less important than other?

**Comment by PVince81** [comment]
So far it seems your use case is very specific, and also you are using a non-recommended approach for user accounts by having a shared password.
I doubt that there are lots of other setups out there using ownCloud in a similar way.

The right approach I think would be to look into ways for improving OC in a way that removes your need to have a shared account in the first place. Maybe user management is too complicated and can be improved ?

The other trouble with supporting too many use cases (and especially rare ones) is that it increases the complexity of the code and makes it difficult to maintain and test all possible use cases every time (making sure all still work), so it's best to focus on the most common use cases.

**Comment by mitar** [comment]
Yes, even simpler setup would be to not even have username and password. :-) To just have a public ownCloud which we protect with a firewall.

Really imagine it like a web-based anonymous FTP. Is this use case so strange? I do not really get it. It was pretty common.

So people upload files, people download files, people move them around and organize them. We just do not want that files are deleted (or they should be deleted by an admin only).

So you are saying that you can simplify anonymous FTP by introducing easy way for each user to have their own username and password? Not sure how can that ever be as easy to use.

**Comment by hodyroff** [comment]
Your use case would be done with the anonymous link. By checking it right now I did realize that we don't have the complete CRUDS functionality there, we have only "editing" or not "editing". Looks like you would need "create" and "change" but not "delete". Right? Trash bin of course would be 100% reserved for the user who actually owns the files or got them shared.

**Comment by mitar** [comment]
What do you mean with an anonymous link? So people would have to open a link which then they could be using as a folder and put all stuff in and add more stuff and move it around?

I think using anonymous link is less user friendly (you have to remember it, or have a redirect/shortener somewhere).

I in fact like that they can move things to trash. Just not empty it.

I think it would be easier to add a permission to the system for emptying trash than changing anonymous links, but OK.

**Comment by PVince81** [comment]
@hodyroff there's a ticket to introduce CRUDS for link shares: https://github.com/owncloud/core/issues/20699

**Comment by mitar** [comment]
Does it also work for anonymous links?

The issue is that users would not have an account to upload and create files. Would this work?

**Comment by PVince81** [comment]
@mitar if you create an anonymous link share (with "allow editing" and give it to all users, they will be able to upload/download files there and also create folders, delete files, etc (at least since 9.0).

When deleting files in a link share, the share owner (who has an account) will have the file appear in the trashbin. But the trashbin isn't visible to the anonymous users.

**Comment by hodyroff** [comment]
Seems like we don't need to change anonymous links at all for you at this time. Perfect. You can shorten the links as you like. CRUDS for anonymous will be discussed in #20699. Closing.
