### ISSUE TITLE
The GPG public key is not available 

### ISSUE THREAD

**Issue by jimcc** [owncloud/core#25124]
Hello, This is just a missing file from your installation page on at:

https://owncloud.org/install/#instructions-server

Verify the authenticity via PGP (.tar.bz2 /.zip). The ownCloud GPG key is here.

"is here" is a link to:  https://owncloud.org/owncloud.asc

This link is dead so we can not verify the authenticity

**Comment by DeepDiver1975** [comment]
@danimo issue with the infrastructure?

**Comment by RealRancor** [comment]
Also reported here: https://github.com/owncloud/core/issues/25124

**Comment by danimo** [comment]
Fixed

**Comment by jimcc** [comment]
Thank you :-)
