### ISSUE TITLE
Upgrade from 9.0.1 to 9.0.2 fails with Table 'oc_addressbooks' already exists

### ISSUE THREAD

**Issue by okias** [owncloud/core#25125]
### Server configuration
**Operating system**:
Gentoo amd64
**Web server:**
nginx 1.10.0
**Database:**
MariaDB 10
**PHP version:**
5.6.21
**ownCloud version:** (see ownCloud admin page)
9.0.1

# sudo -u www-data php occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Disabled 3rd-party app: calendar
Disabled 3rd-party app: contacts
Disabled 3rd-party app: mail
Disabled 3rd-party app: music
Disabled 3rd-party app: news
Disabled 3rd-party app: notes
Disabled 3rd-party app: tasks
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 0.8.1
Update 3rd-party app: calendar
Update 3rd-party app: contacts
Update 3rd-party app: mail
Update 3rd-party app: news
Update 3rd-party app: tasks
dav: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_addressbooks' already exists
Starting code integrity check...
Finished code integrity check
Update successful
Maintenance mode is kept active
Reset log level

**Comment by aronovgj** [comment]
https://github.com/owncloud/core/issues/23867

**Comment by nickvergessen** [comment]
Closing as duplicate

**Comment by okias** [comment]
quoting 8.2 to 9.0 bug "That's a new table from 9.0, the one from 8.2 contacts app was called oc_contacts_addressbooks.".

Question is, why when upgrading from 9.0.1 to 9.0.2 pop up this? This table should be there and it's fine. THIS IS DIFFERENT BUG (at least by behaviour). There  should be no migration required.

Also I have feeling I been fighting bug #23867 when moving to 9.0..
