### ISSUE TITLE
Log is written in owncloud.log file when 'allow editing' option is checked for a folder shared via link

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25136]
### Steps to reproduce

1. In files view, create a folder
2. Share it via link
3. Click in 'Allow editing' checkbox

### Expected behaviour

The shared folder should be editable and no log should be shown

### Actual behaviour

A log is written in owncloud.log

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:""9.0.2.2","versionstring":"9.0.2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
{"reqId":"9RATy3cRd0pqoUyxz9gu","remoteAddr":"82.159.139.58","app":"PHP","message":"Undefined index: token at \/opt\/owncloud\/apps\/admin_audit\/handlers\/sharing.php#51","level":3,"time":"2016-06-16T09:20:03+00:00","method":"PUT","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares\/5?format=json","user":"admin"}
```
### Client configuration

**browser**

FIrefox

**Comment by nickvergessen** [comment]
Needs to be reported and fixed in the admin_audit app:
```diff
diff --git a/admin_audit/handlers/sharing.php b/admin_audit/handlers/sharing.php
index bd0f510..f456456 100644
--- a/admin_audit/handlers/sharing.php
+++ b/admin_audit/handlers/sharing.php
@@ -48,7 +48,9 @@ class Sharing extends Base {
 
                if ($arguments['shareType'] == Share::SHARE_TYPE_LINK) {
                        $target = 'a public link';
-                       $target .= ', token: ' . $arguments['token'];
+                       if (isset($arguments['token'])) {
+                               $target .= ', token: ' . $arguments['token'];
+                       }
                        if (!empty($arguments['shareWith'])) {
                                $target .= ', with password';
                        } else {
```
