### ISSUE TITLE
Log is written in owncloud.log file when creating a folder

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25131]
### Steps to reproduce

1. Create a folder in ownCloud

### Expected behaviour

The folder is created and no log is written in owncloud.log

### Actual behaviour

A log is written in owncloud.log

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:"9.1.0.8","versionstring":"9.1.0 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```
{"reqId":"6a4OBTOZpc8rNysS+s4c","remoteAddr":"82.159.139.58","app":"PHP","message":"Undefined index: extension at \/opt\/owncloud\/apps\/workflow\/lib\/Engine\/Wrapper\/StorageWrapper.php#60","level":3,"time":"2016-06-16T08:05:53+00:00","method":"MKCOL","url":"\/remote.php\/webdav\/Foldername","user":"admin"}
```
### Client configuration

**browser**

FIrefox

**Comment by nickvergessen** [comment]
Patch needs to be done in the workflow app:
```diff
diff --git a/lib/Engine/Wrapper/StorageWrapper.php b/lib/Engine/Wrapper/StorageWrapper.php
index 72d89bf..04988ed 100644
--- a/lib/Engine/Wrapper/StorageWrapper.php
+++ b/lib/Engine/Wrapper/StorageWrapper.php
@@ -57,7 +57,7 @@ class StorageWrapper extends Wrapper {
                // test.txt.ocTransferId3462648575.part
                $pathInfo = pathinfo($path);
 
-               if ($pathInfo['extension'] === 'part') {
+               if (isset($pathInfo['extension']) && $pathInfo['extension'] === 'part') {
                        // test.txt.ocTransferId3462648575
                        $pathInfo2 = pathinfo($pathInfo['filename']);
                        if (preg_match('/^ocTransferId\d+$/', $pathInfo2['extension'])) {
```
