### ISSUE TITLE
Storage entry left behind when deleting a remote share

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#25130]
1. Login with two users and check the `oc_storages` table
2. Create a remote share
3. As recipient accept the share
4. Check the `oc_storages` table
5. As recipient "unshare from self"
6. Check the `oc_storages` table
### Expected

The result of 6 and 4 are different, the `shared::` entry should be removed
### Actual

Stray entry is left behind

**Comment by PVince81** [comment]
Closing as duplicate of https://github.com/owncloud/core/issues/15701
