### ISSUE TITLE
Files are unselected when we favorite them

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25145]
### Steps to reproduce
1. In files view, select a file
2. Favorite the file
### Expected behaviour

The file should be kept selected

Note (This is the current behaviour in Master branch)
### Actual behaviour

The file is unchecked as selected
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:""9.0.2.2","versionstring":"9.0.2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```

```
### Client configuration

**browser**

FIrefox

Stable9

![favostable9](https://cloud.githubusercontent.com/assets/10596560/16116351/aa651818-33cc-11e6-8905-6ae419285c3e.gif)

Master
![masterfavo](https://cloud.githubusercontent.com/assets/10596560/16116353/aff98228-33cc-11e6-8415-018977515f1e.gif)

**Comment by mjobst-necls** [comment]
![screencast 2016-11-02 17 38 50](https://cloud.githubusercontent.com/assets/23121972/19937976/7f345acc-a123-11e6-9d04-f7f3bb84a665.gif)

This seems to be fixed

**Comment by davitol** [comment]
Tested in "version":"9.2.0.2","versionstring":"9.2.0 pre alpha" and it is fixed so let's close it. Thanks @mjobst-necls for checking the issue.

**Comment by mjobst-necls** [comment]
Ah. maybe I made a mistake, that's why I deleted my post. In the description is the enterprise edition mentioned. I just tested the current master branch version.

**Comment by davitol** [comment]
@mjobst-necls Yes, but i've checked in both versions and it does not happen in any of them, so you were right 😄

**Comment by mjobst-necls** [comment]
Great ;-)
