### ISSUE TITLE
"Create folder" and skeleton folders are always created with the same etag as the root folder

### ISSUE THREAD

**Issue by oparoz** [owncloud/core#25152]
### Steps to reproduce

1. Open oC in Chrome
1. Create a new album from the GUI
1. Add an image to the folder
1. Press F12, go to the "Network" tab
1. Click on Gallery
1. Click on the line which starts with `files/list?location=`
1. Select the "Preview" tab
1. Click on the "albums" entry

### Expected behaviour

All albums should have a different etags

### Actual behaviour

The root folder, labelled "undefined" has the same etag as the album which was just created.

---

@PVince81 @icewind1991

**Comment by PVince81** [comment]
In general etags aren't like checksums. I was told that it is acceptable to have the same etag on several filecache entries. The most important is that the etag changes to another value whenever a change is detected.

**Comment by oparoz** [comment]
Not according to the documentation:
https://github.com/owncloud/client/wiki/Etags-and-file-ids

**Comment by oparoz** [comment]
In the end, I can adapt the code in Gallery, but if this is the new behaviour, then I think it should be documented somewhere so that everyone is made aware of that change.

**Comment by PVince81** [comment]
Let me see if I can find @icewind1991's statement in one of his speed-optimizing PRs

**Comment by oparoz** [comment]
:)

**Comment by PVince81** [comment]
Here it is: https://github.com/owncloud/core/pull/20229#discussion_r43649767

And it's from a PR that did not get merged. Phew.

**Comment by PVince81** [comment]
In this case let's say it's a bug.

I think the skeleton code is already doing some weird magic and might bypass some stuff due to it running "too early" before the FS was setup. So it's likely that the etag creation logic is not correct.

**Comment by oparoz** [comment]
FYI, It does work on stable 9.
Also the last comment in that PR mentions a new propagator, so maybe that introduced the change?

But yeah, if this wasn't intentional, then it's best to fix it for now.

**Comment by PVince81** [comment]
@oparoz Works for me on master af98e3e641220db4ddf38a9270f535603526f6c5:
```
MariaDB [owncloud]> select fileid, path, size, etag from oc_filecache where storage=4 order by path;
+--------+-----------------------+------+----------------------------------+
| fileid | path                  | size | etag                             |
+--------+-----------------------+------+----------------------------------+
|    270 |                       |  175 | 576bacdc053b6                    |
|    271 | cache                 |    0 | 576bacd98a7a3                    |
|    272 | files                 |  175 | 576bacdbdff0e                    |
|    274 | files/skel1           |   12 | 576bacdb81675                    |
|    275 | files/skel1/hello.txt |   12 | f07cc9af1ca85993febda566bd1d6a8e |
|    276 | files/skel2           |    0 | 576bacdbcf8dd                    |
|    273 | files/welcome.txt     |  163 | ac2428b1dcda1c43cfe99f0631839546 |
+--------+-----------------------+------+----------------------------------+
```

This is for a new user.
This is my skeleton folder:
```
skeleton
skeleton/welcome.txt
skeleton/skel1
skeleton/skel1/hello.txt
skeleton/skel2
```

**Comment by oparoz** [comment]
Just tried the steps in the OP with the latest master and the bug is gone :)
