### ISSUE TITLE
"An error occurred!  Bad Signature" when trying access encrypted external stored file.

### ISSUE THREAD

**Issue by gladpark** [owncloud/core#25178]
Hello, I'm having problems opening files that I recently uploaded to owncloud.  I see there are similar issues but they were not using external storage and I didn't enable encryption after added the files, it was enabled before I uploaded them. 

Thank you! 

### Steps to reproduce
1.  Used owncloud from pre-installed Digital Ocean droplet, then upgraded to 9.0.2
2. Enabled encryption on external storage
3. Added Dropbox as external storage
4. Uploaded all documents using the owncloud client sync to external  storage
5. When I try to view encrypted files (txt files) via the web interface it get the error "An error occurred! Bad Signature"
6. If I try to download the  file I get "This site can’t be reached", "The webpage at https://xxxxxxxx/remote.php/webdav/Dropbox/Documents/IT/xxxxxxxxx.txt?downloadStartSecret=xxxxxxxxxxxxxxxxxxxxx might be temporarily down or it may have moved permanently to a new web address."

### Expected behaviour
The  files should be accessible. 

### Actual behaviour
Described above. 

### Server configuration
**Operating system**:
Ubuntu 14.04 3.13.0-85-generic  (Digitial Ocean pre-built droplet)

**Web server:**
Apache/2.4.7 

**Database:**
mysql-server-5.5

**PHP version:**
PHP 5.5.9-1ubuntu4.17

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.2.2

**Updated from an older ownCloud or fresh install:**
ownCloud 9.0.1

**Where did you install ownCloud from:**
Digital Ocean pre-installed Droplet

**Signing status (ownCloud 9.0 and above):**

"No errors have been found."

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - dav: 0.1.6
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - galleryplus: 15.0.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - calendar
  - comments
  - external
  - federation
  - gallery
  - systemtags
  - user_external
  - user_ldap

**The content of config/config.php:**
<?php
$CONFIG = array (
  'updatechecker' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'passwordsalt' => '***REMOVED SENSITIVE VALUE***',
  'secret' => '***REMOVED SENSITIVE VALUE***',
  'trusted_domains' => 
  array (
    0 => '***REMOVED SENSITIVE VALUE***',
    1 => '***REMOVED SENSITIVE VALUE***',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://localhost',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'jug',
  'dbuser' => 'owncloud',
  'dbpassword' => '***REMOVED SENSITIVE VALUE***',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => 'oc8np8fycbhy',
  'mail_smtpmode' => 'sendmail',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

{
    "system": {
        "updatechecker": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "jug",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "oc8np8fycbhy",
        "mail_smtpmode": "sendmail",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}

**Are you using external storage, if yes which one:** Yes, Dropbox and Google Drive

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**  Chrome Version 51.0.2704.84

**Operating system:** Ubuntu and Windows 10

### Logs
#### Web server error log
```
root@owncloud-sgp1:/var/log/apache2# tail 100 error.log
tail: cannot open ‘100’ for reading: No such file or directory
==> error.log <==
[Mon Jun 13 19:55:37.249162 2016] [authz_core:error] [pid 12968] [client 203.42.55.204:39034] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Mon Jun 13 19:58:25.226228 2016] [authz_core:error] [pid 12969] [client 203.42.55.204:39135] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Mon Jun 13 22:59:38.581006 2016] [authz_core:error] [pid 16432] [client 203.42.55.204:43877] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Tue Jun 14 02:16:48.259709 2016] [:error] [pid 21382] [client 203.42.55.204:49675] PHP Warning:  Unknown: POST Content-Length of 9223372036854775807 bytes exceeds the limit of 4294967296 bytes in Unknown on line 0
[Tue Jun 14 02:57:20.244691 2016] [authz_core:error] [pid 21253] [client 203.42.55.204:50882] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Tue Jun 14 23:25:54.644621 2016] [:error] [pid 31256] [client 203.42.55.204:25798] PHP Fatal error:  Maximum execution time of 60 seconds exceeded in Unknown on line 0
[Wed Jun 15 02:31:17.413566 2016] [authz_core:error] [pid 32401] [client 49.2.231.202:62547] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Wed Jun 15 06:04:38.460199 2016] [core:error] [pid 1582] [client 169.229.3.91:50449] AH00126: Invalid URI in request :\x7f\x1a\x85\x86\xcf4\xba\x15\x95f\xd2\xc5\x80\xe5z\xb0\xa1#\xa5\x96i\r\x87\xb3\xde\x1a\xafY\x8al\xb5\xfe4
[Thu Jun 16 02:20:47.538579 2016] [authz_core:error] [pid 20348] [client 203.42.55.204:53674] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata
[Sun Jun 19 00:01:01.739836 2016] [authz_core:error] [pid 14513] [client 203.17.70.53:50213] AH01630: client denied by server configuration: /var/www/owncloud/data/.ocdata

#### ownCloud log (data/owncloud.log)

{"reqId":"zz3nWrqUvp+7uVwlNKmN","remoteAddr":"XXXXX","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:80) at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-06-19T03:42:54+00:00","method":"GET","url":"\/remote.php\/webdav\/Dropbox\/Documents\/IT\/XXXXX?downloadStartSecret=XXXXXX","user":"admin"}

**Comment by PVince81** [comment]
I tried with v9.0.2 and Dropbox, uploading files with encryption enabled. I was able to redownload them properly.

Do you have older files on Dropbox that you encrypted with another / older / previous ownCloud instance ?

**Comment by gladpark** [comment]
No, everything was uploaded just the once using the OC default encryption.  I can actually download most of the files.  

It's just certain files are giving me the Bad Signature error.  Both have been text files.  The first I created via the OC web-interface, moved it around a couple directories and it gave me a Bad Signature.  I restored the file from a previous version and I could access it.   I raised this issue for the second time it happened. Another text file which I didn't move, didn't make it with the web-interface, I just lost access, no previous versions..  

Seems a bit random..

**Comment by gladpark** [comment]
Can't download any files anymore.  Not much point to keeping it.  Removed the OC instance. 

The only common error I see on the admin page is:

Error	PHP	Cannot modify header information - headers already sent by (output started at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php:80) at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#63

Unsolved mystery.

**Comment by brunodegoyrans** [comment]
Hello

I have exactly the same issue since 2 days. I don't know what happened 2 days ago. But I have lost hundreds of files, and now I have this "bad signature" when I try to download some files with the web interface.

"bad signature" appears in owncloud.log
When I try to donwload, I have this error in the navigator: 
```
Ce site est inaccessible

Il se peut que la page Web à l'adresse https://youdonthavetoknowmyserver/owncloud/remote.php/webdav/BILP/Activité%20CABANE/MODELES%20de%20cabane%20SKETCHUP/Modèle%20N°27/Modèle%2027A/Modèle%2027A.layout?downloadStartSecret=9eqlq1xh7brlhp9xp6gjeb3xr soit temporairement inaccessible ou qu'elle ait été déplacée de façon permanente à une autre adresse Web.
ERR_INVALID_RESPONSE
```
