### ISSUE TITLE
integrate app via http

### ISSUE THREAD

**Issue by RoswellKnigth** [owncloud/core#25176]
owncload is possible to integrate a Web application ?? I want to integrate owncload like I did with dropbox in a web application for users to access through my application to owncload, but I realize that only allow applications to integrate webdavs. excuse my English, my native language is Spanish. I hope you can help me with this question.

**Comment by RealRancor** [comment]
@RoswellKnigth This issue tracker is used for bugreports and feature requests only. Please ask such questions at e.g. the developers mailinglist: https://mailman.owncloud.org/mailman/listinfo/devel
