### ISSUE TITLE
An internal error occured.

### ISSUE THREAD

**Issue by tassum** [owncloud/core#25179]
Steps to reproduce
1. I upgraded to the latest ownCloud 9 Version.
2. Adding a new user in the GUI and trying to login 
3.I get the following error message:

"An internal error occured.
Please try again or contact your administrator."

Expected behaviour
Login should work and userdata should be added

Actual behaviour

After adding a new user in the GUI and trying to login I get the following error message:

"An internal error occured.
Please try again or contact your administrator."

After this I get a Browser message also if I try to login with an old (normally working) user.

"Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

Technical details
Remote Address: 192.168.0.254
Request ID: wsgkBIGikgsMuOoFi/r/"

In the users data folder there is only this content:

drwxr-xr-x 3 www-data www-data 4096 Jun 16 13:30 .
drwxrwx--- 84 www-data www-data 4096 Jun 16 13:30 ..
drwxr-xr-x 2 www-data www-data 4096 Jun 16 13:30 cache

Looks like the folder /files gets not created and thats why it is running into the problem ...

sudo -u www-data php occ maintenance:repair without any effect.

I did a complete fresh ownCloud 9.0.2 Installation, reloaded the existing MySQL-Dump, and integrated the data folder. 

Everything works but I still can not add a new user without the above error.

Server configuration
Operating system: Ubuntu 14.04.1
Web server: Apache
Database: MySQL
PHP version: PHP 5.5.9-1ubuntu4.17
ownCloud version (see ownCloud admin page): ownCloud 9.0.2 (stable)
Updated from an older ownCloud or fresh install: Updated
ownCloud log (data/owncloud.log):

"reqId":"wsgkBIGikgsMuOoFi\/r\/","remoteAddr":"192.168.0.254","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/controller\\\/viewcontroller.php(111): OC_Helper::getStorageInfo('\\\/', false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/controller\\\/viewcontroller.php(174): OCA\\\\Files\\\\Controller\\\\ViewController->getStorageInfo()\\n#2 [internal function]: OCA\\\\Files\\\\Controller\\\\ViewController->index('', '')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(159): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/http\\\/dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/app.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/appframework\\\/routing\\\/routeactionhandler.php(45): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#7 [internal function]: OC\\\\AppFramework\\\\routing\\\\RouteActionHandler->__invoke(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(276): call_user_func(Object(OC\\\\AppFramework\\\\routing\\\\RouteActionHandler), Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(882): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#10 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/helper.php\",\"Line\":605}","level":3,"time":"2016-06-16T11:42:36+00:00","method":"GET","url":"\/owncloud\/apps\/files\/","user":"joeline"}

Data is stored in a separate partition /ocdata but has not changed. 

Reproducing the issue the /var/log/apache2/error.log shows:

[Sat Jun 18 08:10:25.296588 2016] [mpm_prefork:notice] [pid 2051] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.17 configured -- resuming normal operations
[Sat Jun 18 08:10:25.296667 2016] [core:notice] [pid 2051] AH00094: Command line: '/usr/sbin/apache2'
[Sat Jun 18 08:11:30.354865 2016] [:error] [pid 2063] [client 192.168.0.254:27077] script '/var/www/owncloud/apps/files/cron.php' not found or unable to stat
[Sat Jun 18 08:11:36.281936 2016] [:error] [pid 2072] [client 192.168.0.254:27083] script '/var/www/owncloud/apps/files/cron.php' not found or unable to stat
[Sat Jun 18 08:11:46.994649 2016] [core:notice] [pid 2051] AH00051: child pid 2054 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Sat Jun 18 08:11:46.994765 2016] [core:notice] [pid 2051] AH00051: child pid 2055 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Sat Jun 18 08:11:46.994791 2016] [core:notice] [pid 2051] AH00051: child pid 2056 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Sat Jun 18 08:11:46.994827 2016] [core:notice] [pid 2051] AH00051: child pid 2067 exit signal Segmentation fault (11), possible coredump in /etc/apache2
[Sat Jun 18 08:11:49.998136 2016] [core:warn] [pid 2051] AH00045: child process 2062 still did not exit, sending a SIGTERM
[Sat Jun 18 08:11:52.000409 2016] [core:warn] [pid 2051] AH00045: child process 2062 still did not exit, sending a SIGTERM
[Sat Jun 18 08:11:54.002651 2016] [core:warn] [pid 2051] AH00045: child process 2062 still did not exit, sending a SIGTERM
[Sat Jun 18 08:11:56.004931 2016] [core:error] [pid 2051] AH00046: child process 2062 still did not exit, sending a SIGKILL
[Sat Jun 18 08:11:57.006279 2016] [mpm_prefork:notice] [pid 2051] AH00169: caught SIGTERM, shutting down

Searching for the file cron.php - found in:

/var/www/owncloud/cron.php
/var/www/owncloud/core/command/background/cron.php

The update was done this way:

apt-get upgrade
apt-get install owncloud 
sudo -u www-data php /var/www/owncloud/occ maintenance:mode --off
sudo -u www-data php /var/www/owncloud/occ upgrade --skip-migration-test

sudo -u www-data php occ integrity:check-core -> no output message

I did a complete fresh install into a new Proxmox VM and imported the mysaql dump and the /ocdata partition (from the original VM with this problem) to get sure no files are missing but the problem still exists. All partitions are only 35% in use at a max. There is a RAID configured on the Proxmox host - existing users can still work as expected and upload files - the only problem is that no new users can be added.

I remember that I resized the ocdata partition after the upgrade - not sure if the problem exists before - but the filesystem looks OK.
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - firstrunwizard: 1.1
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
Disabled:
  - encryption
  - external
  - files_external
  - files_videoplayer
  - gallery
  - updatenotification
  - user_external
  - user_ldap

**The content of config/config.php:**

```
root@vlmuc15:/var/www/owncloud/config# cat config.php 
<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'oc63risd8e3l',
  'passwordsalt' => 'deleted',
  'secret' => 'deleted',
  'trusted_domains' => 
  array (
    0 => 'owncloud-test02.pentos.com',
  ),
  'datadirectory' => '/ocdata',
  'overwrite.cli.url' => 'http://owncloud-test02.pentos.com/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc-user',
  'dbpassword' => 'deleted',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

only lckal partitions (see above) for /var/lib/mysql and /ocdata - nfs for backup

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

sudo -u www-data php occ ldap:show-config

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace.          
                                                                  

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
see above
**Operating system:**
see above
#### Web server error log
```
inserted above
```

#### ownCloud log (data/owncloud.log)
```
inserted above```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Weird, does it happens for every new user you create in the ownCloud users page ?

> I did a complete fresh ownCloud 9.0.2 Installation, reloaded the existing MySQL-Dump, and integrated the data folder. 

Did you also restore the config folder ?

**Comment by tassum** [comment]
Hi Vincent,

thanks for your response. It happens with every new user I create. I did 
not restore the config folder. I edited config.php from fresh up on the 
testing mirror system..

Regards

Thomas


Thomas Assum
Consultant 

Buchtipp: SuccessFactors Grundlagen, Prozesse, Implementierung.

Pentos AG | Landsberger Str. 110 | 80339 München
Tel: +49 89 3815381-69 | Fax: +49 89 3815381-42 | Mobil: +49 152 21952622 
E-Mail: thomas.assum@pentos.com | www.pentos.com

Vorstand: Dr. Nikolaus Krasser, Ingo Martinz, Wolfgang Kuchelmeister
Vorsitzender des Aufsichtsrats: Max Nussbaumer | Registergericht: München, 
HRB 132417

**Comment by tassum** [comment]
Hi Vincent,

if I add a user through the GUI and then add the directories /files and 
/cache with the correct rights, it seems to work after the second login. 
Another interesting thing is, that in the GUI you see normally on the 
right top your username after logging in. For none of the existing users 
the username ist shown expect the new one I added with manual folder 
creation ....

It looks like something happened to the database ? Do you have any hints 
for comparing special tables or something like that ?

Thanks in advance and best regards,

Thomas


Thomas Assum
Consultant 

Buchtipp: SuccessFactors Grundlagen, Prozesse, Implementierung.

Pentos AG | Landsberger Str. 110 | 80339 München
Tel: +49 89 3815381-69 | Fax: +49 89 3815381-42 | Mobil: +49 152 21952622 
E-Mail: thomas.assum@pentos.com | www.pentos.com

Vorstand: Dr. Nikolaus Krasser, Ingo Martinz, Wolfgang Kuchelmeister
Vorsitzender des Aufsichtsrats: Max Nussbaumer | Registergericht: München, 
HRB 132417

**Comment by tassum** [comment]
Hi Vincent,

found out on my testing system that an apt-get install --reinstall 
owncloud-files fixed the issue with the missing usernames in the GUI. 
Could it have any negative impact on the system ?

Thy and regards,

Thomas


Thomas Assum
Consultant 

Buchtipp: SuccessFactors Grundlagen, Prozesse, Implementierung.

Pentos AG | Landsberger Str. 110 | 80339 München
Tel: +49 89 3815381-69 | Fax: +49 89 3815381-42 | Mobil: +49 152 21952622 
E-Mail: thomas.assum@pentos.com | www.pentos.com

Vorstand: Dr. Nikolaus Krasser, Ingo Martinz, Wolfgang Kuchelmeister
Vorsitzender des Aufsichtsrats: Max Nussbaumer | Registergericht: München, 
HRB 132417





From:   Thomas Assum/Pentos/DE
To:     owncloud/core 
<reply@reply.github.com>
Date:   22.06.2016 13:49
Subject:        Re: [owncloud/core] An internal error occured. (#25179)


Hi Vincent,

if I add a user through the GUI and then add the directories /files and 
/cache with the correct rights, it seems to work after the second login. 
Another interesting thing is, that in the GUI you see normally on the 
right top your username after logging in. For none of the existing users 
the username ist shown expect the new one I added with manual folder 
creation ....

It looks like something happened to the database ? Do you have any hints 
for comparing special tables or something like that ?

Thanks in advance and best regards,

Thomas


Thomas Assum
Consultant 

Buchtipp: SuccessFactors Grundlagen, Prozesse, Implementierung.

Pentos AG | Landsberger Str. 110 | 80339 München
Tel: +49 89 3815381-69 | Fax: +49 89 3815381-42 | Mobil: +49 152 21952622 
E-Mail: thomas.assum@pentos.com | www.pentos.com

Vorstand: Dr. Nikolaus Krasser, Ingo Martinz, Wolfgang Kuchelmeister
Vorsitzender des Aufsichtsrats: Max Nussbaumer | Registergericht: München, 
HRB 132417

**Comment by PVince81** [comment]
@tassum should be fine as it would only replace the source code from my understanding. I suspect that there was something wrong with the sources.
