### ISSUE TITLE
Files and folders shared with a group including the sharer are shared with himself as well.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#25186]
### Steps to reproduce:

1. As admin create several users, including 'user1' and make them belong to a group 'group1'.
2. As 'user1' share a folder or file with 'group1'.

### Expected behaviour:
All users except 'user1' gets the share from 'user1'.

### Actual behaviour
'user1' now have the file/folder twice, he has received his own share too.

<img width="914" alt="screen shot 2016-06-20 at 12 53 32" src="https://cloud.githubusercontent.com/assets/9048796/16191743/1227a8dc-36e6-11e6-814f-f37c73ea289b.png">

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
Current master
{"installed":true,"maintenance":false,"version":"9.1.0.8","versionstring":"9.1.0 beta 2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```


```

### Client configuration

Chrome, Firefox.

**Comment by PVince81** [comment]
Possibly a regression ?

**Comment by PVince81** [comment]
@owncloud/sharing

**Comment by PVince81** [comment]
Works fine on stable8.2 and stable9.

Broken in 9.1.0beta2. => regression

**Comment by PVince81** [comment]
The first bad commit could be any of:
6123badbfa22b79167c4b41f84a38b372f033a2e
afa37d363fe1bedfe85a4dbd53adb091f3b014b2

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/25190
