### ISSUE TITLE
New Owncloud version without upgraded linux packages

### ISSUE THREAD

**Issue by nessor** [owncloud/core#25180]
I run the OwnCloud v8.2.2. The system say that the version 8.2.5 is available. Because I installed OwnCloud via the repository, it should be possible to upgrade the package via "apt-get upgrade" or "apt-get install owncloud". 

But in both possibilities linux say me that 8.2.2 is ne newest version of owncloud

**Comment by Kawohl** [comment]
@nessor could you please show the contents of:
/etc/apt/sources.list.d/owncloud.list.

**Comment by nessor** [comment]
sure:

`deb http://download.owncloud.org/download/repositories/8.2/xUbuntu_14.04/ /`

**Comment by Kawohl** [comment]
that was related to a change in the repos, you would have to reimport it again:
from e.g. here: https://download.owncloud.org/download/repositories/8.2/owncloud/
we are now on 9.1 please update to the latest minor version and then to 9.0 latest version and then to 9.1 to make sure everything goes smoothe. Please also make a backup before doing so.
