### ISSUE TITLE
Log is written in owncloud.log file when searching for a tag set to a file in tags section

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25182]
### Steps to reproduce

1. In files view, set a tag to a file in the sidebar
2. Go to tags view
3. Search for the previous tag

### Expected behaviour

The file tagged should appear and no logs should be shown

### Actual behaviour

A log is written in owncloud.log

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:""9.0.3.1","versionstring":"9.0.3 RC1","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** GDrive/DropBox,S3

**Are you using encryption:** 
No

**Logs**
```
{"reqId":"WxKB8xABV+nzQ1xTzQvq","remoteAddr":"82.159.139.58","app":"PHP","message":"Invalid argument supplied for foreach() at \/opt\/owncloud\/apps\/dav\/lib\/connector\/sabre\/sharetypelist.php#68","level":3,"time":"2016-06-20T07:07:10+00:00","method":"REPORT","url":"\/remote.php\/webdav\/","user":"admin"}
```

### Client configuration

**browser**

Firefox

**Comment by PVince81** [comment]
Cannot reproduce on master, likely to be fixed already.
