### ISSUE TITLE
This server has no working Internet connection in owncloud 9

### ISSUE THREAD

**Issue by Revnixcad** [owncloud/core#25191]
**Error**
![no internet connection](https://cloud.githubusercontent.com/assets/19774235/16197536/b8456486-3702-11e6-8a53-33643164596f.PNG)

"This server has no working Internet connection. This means that some of the features like mounting external  storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features."

**What i did already:**
Read multiple solutions noting worked for me
-set has_internet_connection to false in my config.php true or fals dont work.
-copy "config/ca-bundle.crt" in /config folder
-checked the internet connection with owncloud.org

**Operating system:** Owncloud
**Web server:**Apache
**Database:**MySQL
**PHP version:**5.6
**ownCloud version:** 9.0.1 (stable)
**Updated from an older ownCloud or fresh install:** fresh install
**Where did you install ownCloud from:** owncloud php file

**Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed** 
`No errors have been found.`

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => '~',
  'passwordsalt' => '~',
  'secret' => '~',
  'trusted_domains' => 
  array (
    0 => 'www.~.nl',
    1 => '~.nl',
    2 => 'localhost',
  ),
  'datadirectory' => '/home/vhosts/~.nl/httpdocs/documenten/data',
  'overwrite.cli.url' => 'https://~.nl/documenten',
  'forcessl' => true,
  'has_internet_connection' => false,
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => '~',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'cvadmin',
  'dbpassword' => '~',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => 'cvwageningen',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '~.nl',
  'mail_smtpauth' => 1,
  'mail_smtpname' => ~.nl',
  'mail_smtppassword' => '~',
  'mail_smtpport' => '25',
  'mail_from_address' => 'info',
  'mail_domain' => '~.nl',
  'mail_smtpauthtype' => 'LOGIN',
  'loglevel' => 0,
  'knowledgebaseenabled' => false,
  'enable_avatars' => false,
  'maintenance' => false,
  'activity_expire_days' => 365,
  'memcache.local' => '',
 );
```

**Are you using encryption:** no

### Client configuration
**Browser:** Chrome
**Operating system:** Windows 10

**Comment by RealRancor** [comment]
Hi,

> Operating system: Owncloud

ownCloud is not an operating system. I think it would really help if you could gather the info which OS you're running.

Furthermore having a look at your data/owncloud.log for possible errors might be useful

**Comment by Revnixcad** [comment]
Here is the owncloud log.

[owncloud log.pdf](https://github.com/owncloud/core/files/324394/owncloud.log.pdf)

Server is running on linux

**Comment by RealRancor** [comment]
First try to disable your broken theme (there are a lots of errors from that in your logfiles). Remove:

'theme' => 'cvwageningen',

from your config.php.

Afterwards also fix this error:

> Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '‐1' in php.ini

and empty your owncloud.log to only have relevant logentries for this issue in the logfile.

> Server is running on linux

Can you specify which linux?

**Comment by tflidd** [comment]
Perhaps you should set this:
`  'has_internet_connection' => false,`
to `true`?

**Comment by Revnixcad** [comment]
@tflidd 
I set it to true not working.

@RealRancor 
I fixed the things you said. but  i cant find out wich lunix our webserver is running.
I've to wait for an answer from my hosting provider.

**Comment by Revnixcad** [comment]
The hosting provider wont tell me the linux version.

**Comment by Revnixcad** [comment]
the default theme give the same error

**Comment by Revnixcad** [comment]
anyone suggestions?

Also the following(i think its related to the same problem.)
i can send an inventation email :+1: 

but an update notification by email from the activity app wont work.

**Comment by PVince81** [comment]
> but an update notification by email from the activity app wont work.

separate issue ?

Please make sure that cron is configured correctly https://doc.owncloud.org/server/9.1/admin_manual/configuration_server/background_jobs_configuration.html

Note that such emails are only sent when cron run and the default is ajax cron, which only runs when people actually browse the web UI. Also see https://github.com/owncloud/core/issues/20380#issuecomment-242696228 for more info about the ajax cron issues with hosting providers.
