### ISSUE TITLE
occ command encryption:decrypt user does not appear in the list of available occ commands

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25194]
### Steps to reproduce

1. Run the following command ``sudo -u www-data ./occ``
2. Check the list of available occ commands

### Expected behaviour

command ``encryption:decrypt user``should be shown

### Actual behaviour

command ``encryption:decrypt user`` does not appear in the list

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:""9.1.0.8","versionstring":"9.1.0 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**
```
```

### Client configuration

**browser**

**Comment by DeepDiver1975** [comment]
> command encryption:decrypt usershould be shown

why? this command simply does not exist

**Comment by davitol** [comment]
Got it, decrypt is expanded to decrypt-all so let's close it. Thx for the info @DeepDiver1975
