### ISSUE TITLE
Renaming old files funcionality

### ISSUE THREAD

**Issue by apmauj** [owncloud/core#25193]
Hi all! This is my first post, i was asked to deploy a solution very similar to owncloud, the thing is that there are batch processes that will upload / download files (along with people), but the idea is to have always the newer file with the "name" of the file..

Here is a example..
If I upload a hello.txt, and then upload a newer version, the new one is renamed "hello (1).txt" (i dont want to replace the file, because i could "need" it in case of a bad overwrite).

It would be good to have a functionality that renames the old file into "hello (1).txt" and then upload a newer file called "hello.txt".

I havent found info regarding this subject, please forgive me if this was already asked.

**Comment by PVince81** [comment]
There is the versioning app, but that one will create versioned files internally.

I suppose it should be possible to write an app that does what you want but I don't think it would be included as part of the core experience, more like a third party app, especially considering that core already provides its own versioning system.

**Comment by apmauj** [comment]
I will be using it over an external storage over SMB / CIFS, not sure if versioning would do the trick..
Now you have 2 options, to rename newer or overwrite, it would be cool to have a third option to rename older before copying..
A third app should be nice also, im pretty new to this, im using it now with latest appliance 9.0.2 and not very sure about adding apps (I've done it in version 7 with wamp but the access to third apps looked easier..).

Thanks for your time!

**Comment by PVince81** [comment]
This is a rather uncommon use case. If there is a need for this, could be implemented as a separate app.
