### ISSUE TITLE
filtering long filelists does not reveal files at the bottom

### ISSUE THREAD

**Issue by butonic** [owncloud/core#25205]
### Steps to reproduce
1. Create a folder 'searchfiltertest' with 1000 files named a1.txt to a1000.txt and a file zzz.txt
  The quickest way to do that is on the filesystem as the www-data user:
```
for f in `seq 1 1000` ; do touch a$f.txt ; done
touch zzz.txt
php occ files:scan admin
```
2. navigate into the folder 'searchfiltertest' 
3. search for zzz to trigger the filter mechanism

### Expected behaviour
you should see zzz.txt in the filelist

### Actual behaviour
You only see *1 file matches 'zzz'* but not the file

### Server configuration
**Operating system**: debian7
**Web server:** apache 2.4
**Database:** oracle, mysql
**PHP version:** 5.6
**ownCloud version:** 8.2, 9.0, 9.1 / master
**Updated from an older ownCloud or fresh install:** fresh
**Where did you install ownCloud from:** git

It is fairly easy to reproduce. @PVince81 I have not yet looked into the filtering mechanism for tags ... are we reusing the search filter code or does that use new logic?

**Comment by PVince81** [comment]
Tags has no connection at all with the search code.

The "Tags" section in the navigation bar uses a REPORT Webdav method to retrieve a filtered result set

**Comment by butonic** [comment]
Sorting by name ascending of course shows zzz.txt but filtering is supposed to always work. I guess the problem is related to the filelist not having been fully populated. The whole filelist is available as we currently don't do any paging yet.

**Comment by butonic** [comment]
So it kind of makes more sesnse to fix this by switching to a REPORT for files, right? cc @DeepDiver1975

**Comment by PVince81** [comment]
Eventually, maybe it makes sense to also make the files search feature use REPORT, yeah...

This also ties in somehow with the other topic of having paginated results, which also goes in the direction of REPORT.

**Comment by PVince81** [comment]
I'll set this to 9.2 now if not critical

**Comment by PVince81** [comment]
Ok, I'll move it back to 9.1 and then we can set this to 9.1.1 for the quickfix.

But the "full" fix with REPORT will be for 9.2

**Comment by butonic** [comment]
yes, makes sense. Thx

**Comment by butonic** [comment]
pagination tracked in https://github.com/owncloud/core/issues/13915

**Comment by PVince81** [comment]
Just tried it. It doesn't have to be long. As long as the result hasn't been rendered yet because it's on the next page, it won't appear in the list.

A possible workaround would be to force rendering of all elements/pages when calling `setFilter`.
One idea would be to call `_nextPage` as long as the number of visible results is inferior to the number of known to exist results.

**Comment by PVince81** [comment]
Quickfix here https://github.com/owncloud/core/pull/25237
