### ISSUE TITLE
Running user:resetpassword command it is possible to set an empty password via CLI

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25206]
### Steps to reproduce
1. Create a oC user (e.g. user1)
2. Run `./occ  user:resetpassword user1`command via CLI ( Enter a new password: is requested)
3. Do not enter any password, hit enter key. (Confirm the new password: is requested)
4. Do not enter any password, hit enter key.
### Expected behaviour

It should not be possible to set an empty password when changing a user's password
### Actual behaviour

No password is set to the user and there is no chance to log in oC via webUI
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:"9.1.0.8","versionstring":"9.1.0 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
```
### Client configuration

**browser**

**Comment by sharidas** [comment]
Closing this issue.
