### ISSUE TITLE
Cannot search for an AD user using Username as pattern

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25216]
### Steps to reproduce
1. Configure an Active Directory
2. Go to the users menu
3. Try to search for a AD user using the Username as pattern
### Expected behaviour

The user should be shown in the search results
### Actual behaviour

No results were found
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:"9.1.0.8","versionstring":"9.1.0 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
```
### Client configuration

**browser**

![searchacd](https://cloud.githubusercontent.com/assets/10596560/16263114/ee8549e6-3872-11e6-8ffe-f5192f651234.gif)

**Comment by PVince81** [comment]
@owncloud/ldap 

I think this was always the case before, there might be a ticket for it.

**Comment by jvillafanez** [comment]
I looked into this the last week, and there is a couple of behavoral mismatches between LDAP and "normal" users:

* As stated in the issue, searches over the username field don't work with LDAP user but do work with "normal" users
* Searches over the display name field will check only the beginning of it with LDAP users, but with normal users it will check the whole of it.

    For example, having a display name like "username1", if the search is for an LDAP user, "usern" will show results, but "nam" won't return any result. For local users, both searches will show results.

The first point won't be easy so resolve. I think the username field comes from the mapping table in the DB. There might be some LDAP fields to check (such as the entryUUID), but we'll also need to take into account the UUID overwrite. We also need to take into account the different LDAP servers and if we're using other attribute as UUID. It's difficult to foresee the changes.

The second point seems easier, but we also need to take into acount the behaviour of each LDAP servers

**Comment by scolebrook** [comment]
@davitol What attributes are in the user search attributes list on the advanced tab of your ldap config? In 8.2.5 the search is always performed left to right on all the listed attributes. I don't have a 9.1 system to confirm the same behaviour. But you should be able to search on any attribute. To search by username, add the attribute you use for username to the list. In an AD setup this is most likely samAccountName.

Keep in mind that if you use multiple directories, samAccountName is not guaranteed to be unique across them all. We use userPrincipleName instead for our login filter and searches. The left part is the same so searches match the same way but if we have a user with the same username in two directories it's still possible to uniquely specify them.

**Comment by PVince81** [comment]
@davitol any update on the previous question ?

**Comment by PVince81** [comment]
@davitol please update

**Comment by PVince81** [comment]
@jvillafanez is this a bug or misunderstanding ?

**Comment by davitol** [comment]
@PVince81 Tested in 9.1.5 RC1 and it works reasonably OK setting the sAMAccountName as UserName and in the 'user search attributes' on the advanced tab, so let's close the ticket
