### ISSUE TITLE
[occ commands] Cannot set log level to minimum through occ command (CLI)

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25210]
### Steps to reproduce

1. Run ``./occ log:manage --level=0`` command via CLI

### Expected behaviour
Log level should be set to 0 level
`Enabled logging backend: owncloud
Log level: Debug (0)
Log timezone: UTC`

### Actual behaviour
Enabled logging backend: owncloud
Log level: Error (3)
Log timezone: UTC

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**
"versionstring: 9.0.3 RC1"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
No logs

### Client configuration

**browser**

**Comment by PVince81** [comment]
It was fixed in 9.1 https://github.com/owncloud/core/issues/24829
