### ISSUE TITLE
make thumbnail, trashbin and version paths configurable

### ISSUE THREAD

**Issue by butonic** [owncloud/core#25213]
In large Installations storage cost can be improved by placing data on different storages, eg:
- thumbnails on SSDs for performance
- trash on cheaper HDDs
- versions on a ceph bucket
- data on a glusterfs (just as an example)

For scalability the data should be placed in prefixed user dirs in each case, eg: 
- `/mnt/oc_trash/al/ice/files_trashbin`
- `/mnt/oc_versions/bo/b/files_versions`
- `/mnt/oc_data/pe/ter/files`
- `/mnt/oc_thumbnails/to/m/thumbnails`
- `/mnt/oc_cache/to/m/cache`

For cache we already have `cache_path` in the config.php. This FR just extends the functionality to other types of data and proposes to _always_ prefix user dirs. It is not really needed to make that configurable. (although a userid prefix could be configured like `'userid_prefix' => '#/##'` which would lead to `data/p/et/er`. Also keep in mind that the puth might come from the database in the future and no longer can or should be derived from the userid, as it may become a simple integer.)

**Comment by felixboehm** [comment]
Awesome!

**Comment by PVince81** [comment]
If we move the metadata to a separate folder like we did for avatars "data/avatars", this might become easier.

**Comment by PVince81** [comment]
Decouple home storages https://github.com/owncloud/core/issues/29502 where we can go further and let the admin configure metadata storage as well.
