### ISSUE TITLE
ownCloud config report downloaded shows sensitive values

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25218]
### Steps to reproduce

1. Go to admin menu
2. Download ownCloud config report

### Expected behaviour

The sensitive values should not be shown as it happens for some of them e.g. (LDAP pwd)

### Actual behaviour

Some sensitive values are shown in the report:

``
"Environment": {
            "HOSTNAME": "b97d2504fe65",
            "HOME": "\/opt\/owncloud",
            "OC_FQDN": "XXXXXXX",
            "OC_ADMIN_PASS": "**RealPassword**",
``

``
"OC_URL": "http:\/\/owncloud:RealPassword@docker.XXXXX:1080\/enterprise\/owncloud-daily-enterprise-complete-master.tar.bz2",
``

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:"9.1.0.8","versionstring":"9.1.0 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**

**Comment by PVince81** [comment]
What is "OC_ADMIN_PASS" and "OC_URL" ? These values aren't defined by ownCloud itself but by your test environment. There is no way that the ownCloud config report code can detect which env variables contain sensitive values and which ones don't. Closing as invalid.

In general on a productive server, environment variables would not contain passwords.
