### ISSUE TITLE
Security warning misleadingly

### ISSUE THREAD

**Issue by falavu** [owncloud/core#25217]
### Steps to reproduce
1. go to ~/index.php/settings/admin
2. see the first Line: »cURL verwendet eine veraltete OpenSSL Version (OpenSSL/1.0.1). Bitte aktualisiere dein Betriebsystem, …«
3.

### Expected behaviour
i expected an Information which I understand.

### Actual behaviour
i get an information which i do not understand completely: does this mean the Operating System of my Computer or the Machine that runs the OC-Server? The Problem is: i do not have Access to this Machine. So i do not know, what i can do. 

### Server configuration
**Operating system**: Linux 

**Web server:** Apache 

**Database:** MySQL 

**PHP version:** 5.4

**ownCloud version:** (see ownCloud admin page): 9.0.2 

**Updated from an older ownCloud or fresh install:**: fresh 

**Where did you install ownCloud from:**: One-CLick-INstaller from all-inkl.com 

**Signing status (ownCloud 9.0 and above):** [what does this mean?] 

```


### Client configuration
**Browser:** Firefox 

**Operating system:**: OSX 10.11.5

**Comment by RealRancor** [comment]
This mentioned operating system is the one on your server at all-inkl.com and from my PoV the message is not misleading. As this is a shared hoster the only thing you can do is to ignore the warning or switch to an hoster not running an ancient operating system.

**Comment by falavu** [comment]
Thanks for the Information.
This was not only a Question: the Text in the Admin-Page should be 
more self explaining.

**Comment by RealRancor** [comment]
The Setup & Security Warning are only for the server-side and shows you self explaining that you need to upgrade your Operating System. What additional infos are you expecting here?

**Comment by falavu** [comment]
Thank You for the quick Reply.

> The Setup & Security Warning are only for the server-side […]
>
Yes, thanks, i understand this.


> […] and shows you self explaining […]
>
For me it was not self explaining – so why i ask for

> […] that you need to upgrade your Operating System. What 
> additional infos are you expecting here?
>
Not here – it would be nice for people like me, to write the 
information, you gave me here, on the admin-server-page– for the 
future; no one will ask any more

**Comment by RealRancor** [comment]
The admin page is currently saying:

> cURL is using an outdated version xxx. Please update your operating system or features such as installing and updating apps via the app store or Federated Cloud Sharing will not work reliably.

What infos are you missing here?
