### ISSUE TITLE
files is corrupted and owncloud client failed to sync after restoring the sharing files to earlier version

### ISSUE THREAD

**Issue by kenyang001** [owncloud/core#25211]
[owncloud error log.txt](https://github.com/owncloud/core/files/327118/owncloud.error.log.txt)
[owncloud error log.txt](https://github.com/owncloud/core/files/327120/owncloud.error.log.txt)

 
Steps to reproduce
1.in a shared folder, create a word/excel, or just create a file, and then share it to other people in ownCloud, edit the file several times to have a few versions. then restore the file to older verion by click Details>>Versions on owncloud web interface.
2， the server-side encryption is enabled

actually, we have already found the corrupted file issue for a long time, however, we are still unable to reproduce this problem. meanwhile we get file corrupt even when not doing restore versions, so there are definitely other conditions that cause the same symptoms, could you help us for this corrupt file problem. if you need any further information, please let me know. thnaks.

Expected behaviour
the file can be downloaded and syncing probably by all shared people after we restore the file to old version.

Actual behaviour
the file failed to download in web interface, and owncloud client failed to syn after we restore the file to old one

Server configuration
Operating system: ubuntu14.04
Web server: Apache
Database: mysql
PHP version: PHP 5.5.9-1ubuntu4.16 
ownCloud version (see ownCloud admin page):9.0.2
Updated from an older ownCloud or fresh install: upgraded from an older owncloud
ownCloud log (data/owncloud.log): error log attached

Special configuration (external storage, external authentication, reverse proxy, server-side-encryption):
server-side-encryption enabled.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - encryption: 1.2.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'ocf1aff97781',
  'passwordsalt' => 'b62657fe287903f92ea9f6938beb8b',
  'secret' => 'cbd0eaad117579cfaeb334e6b6ecfa0f1c4e2d1d6ac15039e6cc746d3afaf1a5375caf2d914e1dcab5745d3559527432',
  'trusted_domains' =>
  array (
    0 => ' my ip address',
    1 => 'my domain',
  ),
  'datadirectory' => '/datadriveF/data',
  'overwrite.cli.url' => 'https://my domain',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => 'ownlcloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'my db user',
  'dbpassword' => 'my db password',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'domain',
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'smtp.officefdasfasdf365.com',
  'mail_smtpport' => '587',
  'mail_from_address' => 'adfadsfadsfmin',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'email',
  'mail_smtppassword' => 'emiail password',
  'loglevel' => 0,
  'logtimezone' => 'Asia/Shanghai',
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'forceSSLforSubdomains' => true,
  'singleuser' => false,
  'trashbin_retention_obligation' => 'auto',
);

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Thanks for your report.

There is already another report of such issues but the actual reason for the corruption is still unknown: https://github.com/owncloud/core/issues/23928
