### ISSUE TITLE
Some Tooltips does not disappear  

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/core#25220]
### Steps to reproduce
1. As user A on server A share a file or folder with user B on server B
2. As user B use browser and go to all files view
3. Click on userA@serverA legend that appears near file name

![tooltip](https://cloud.githubusercontent.com/assets/18436398/16264134/0cc576c4-3878-11e6-83f0-bfa88c259d23.png)
### Expected behaviour

Tooltip should disappear after click
### Actual behaviour

Tooltip does not disappear.
### Server configuration

**Operating system:**
Ubuntu 14.04.1 LTS
**Web server:**
Apache2
**Database:**
Server version: 5.5.46-0ubuntu0.14.04.2 (Ubuntu)
**PHP version:**
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46
**ownCloud version: (see ownCloud admin page)**
ownCloud Enterprise Edition 9.1.0 beta 1 (testing)

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:**
Chrome 51
**Operating system:**
OSX El capitán 10.11.5

**Comment by PVince81** [comment]
moved to more general UX group ticket: https://github.com/owncloud/core/issues/27578
