### ISSUE TITLE
[9.1beta testing] asset pipeline breaks personal page, session & device section

### ISSUE THREAD

**Issue by felixboehm** [owncloud/core#25241]
Wenn ich die asset_pipeline aktiviert habe funktioniert die „Personal“ Page nicht richtig. Es werden keine Sessions und Devices angezeigt (statt dessen nur Kreise) und es erfolgt bei einigen Buttons (Create new device password, Language) keine Reaktion.
Ohne asset Pipeline funktioniert das alles.
### Steps to reproduce
1. 9.1beta1, activate asset pipeline
2. browse to personal page

### Expected behaviour
Personal page content visible and functional

### Actual behaviour
- Section for Session and Devices does break with missing assets / images
- Buttons are not working

### Server configuration
**Operating system**: 9.1beta1

**Comment by PVince81** [comment]
@felixboehm english please

**Comment by PVince81** [comment]
Just tried 9.1.0beta1 and the device+token sections have a spinner that never stops.

**Comment by PVince81** [comment]
Same on 9.1.0beta2 and master.

Evaluating `OC.Settings` in the browser console shows that none of the files "settings/js/authtoken*.js" were loaded.

Maybe the way how they are added is wrong ?

@DeepDiver1975 @ChristophWurst

**Comment by PVince81** [comment]
Ah, more info:

```
a3ba413….js:875
 Uncaught TypeError: Cannot read property 'Model' of undefined(anonymous function) @ a3ba413….js:875
(anonymous function) @ a3ba413….js:875
```

**Comment by PVince81** [comment]
Ok, seems the backbone lib isn't loaded, need to use `OC.Backbone` instead.
I'll take care of it.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/25251
