### ISSUE TITLE
Visual annoyance in the installation page

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#25242]
### Steps to reproduce:
1. Get current master and go to the installation page.
2. Put a long password which fills the password field.

### Observed behaviour:

![screen shot 2016-06-23 at 12 50 03](https://cloud.githubusercontent.com/assets/9048796/16300639/37a8c93a-3941-11e6-8ad4-45c8c62db235.png)

**Comment by PVince81** [comment]
@owncloud/designers

**Comment by MorrisJobke** [comment]
I guess this is a missing `margin-right`. Right click and inspect the password field. Check if there is still the margin-right a bit bigger than the margin-left.

**Comment by SergioBertolinSG** [comment]
Seems that it is being overridden.

<img width="250" alt="screen shot 2016-06-24 at 10 43 47" src="https://cloud.githubusercontent.com/assets/9048796/16332874/ac2ce7ac-39f8-11e6-87a7-2aa3d3da0695.png">

**Comment by jancborchardt** [comment]
It needs to be padding-right. There should be a considerable amount, like 30px.

**Comment by andmckvr13** [comment]
Hello, I'm a new developer. Is anyone working on this fix? this seems like a relatively easy fix for a newbie like myself. I no one is working on this I'd love to give it a shot

**Comment by DeepDiver1975** [comment]
> Hello, I'm a new developer. Is anyone working on this fix? this seems like a relatively easy fix for a newbie like myself. I no one is working on this I'd love to give it a shot

you are very much welcome to give it a shot - welcome to the show

**Comment by andmckvr13** [comment]
@DeepDiver1975 Thank you. The repo is rather large, in which file is the installation CSS in?

**Comment by DeepDiver1975** [comment]
All relevant styles should be in core/css/*.css
