### ISSUE TITLE
Receiving a local share folder from two users deduplication broken

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25244]
### Steps

1. Create three users "user1", "user2", "user3"
1. As "user1" create a folder "test" with a file "test/one.txt" inside
1. Share "test" with "user3"
1. As "user2" create a folder "test" with a file "test/two.txt" inside
1. Share "test" with "user3"
1. Login as "user3"

### Expected result
Two folders "test" and "test (2)"

### Actual result
Only a folder "test" with "two.txt" inside, from user2

### Versions
ownCloud 9.0.2

@owncloud/sharing @owncloud/filesystem  regression

**Comment by PVince81** [comment]
Looks like the deduplication code with "moveShare" isn't triggered at all.

**Comment by PVince81** [comment]
CC @owncloud/qa we need tests for such cases

**Comment by rullzer** [comment]
See https://github.com/owncloud/core/pull/25113

**Comment by PVince81** [comment]
@rullzer okay, I think "deduplication" was used wrongly here. Basically we expect two folders to appear instead of one. It's the reverse from grouping.

I tried 9.0.3RC1 and the bug is still there.
However on master (af98e3e641220db4ddf38a9270f535603526f6c5) it is fixed. Maybe a reverse bisect will help find out what to backport.

**Comment by rullzer** [comment]
O right... that is different...
mmmm the logic there should handle it... good to see that it is working on master...

**Comment by PVince81** [comment]
I'll do a reverse bisect

**Comment by PVince81** [comment]
Here we go, this commit fixes it on master: 411fac892a86814b0625cfcbedbc2d575308cbeb from this PR https://github.com/owncloud/core/pull/23937

Looks like we missed a backport there. Will backport it.
