### ISSUE TITLE
"Missing public key for user xyz" while sharing a folder

### ISSUE THREAD

**Issue by DaDenniX** [owncloud/core#25246]
Hi there,
### Steps to reproduce
1. Login as user
2. share a folder to another local user ABC
3. Message "Public Key missing for User: xyz" appears for a completely different user than I typed in
4. refresh the site and see, that the folder is shared to the user typed in
5. the user can't download content (receives "this site can't be reached")
### Expected behaviour

everything should work as designed, user should be able to download content from a shared folder
### Actual behaviour

user can't access this shared folder (message: "this site can't be reached")
### Server configuration

**Operating system**: Debian 7

**Web server:** Apache 2.2.22

**Database:** MySQL 5.5.47

**PHP version:** PHP 5.6.19-dotdeb

**ownCloud version:** (see ownCloud admin page) 9.0.0

**Updated from an older ownCloud or fresh install:** upgraded from older (OC 8)

**Where did you install ownCloud from:** tarball

**Signing status (ownCloud 9.0 and above):** ?

No errors have been found.

**List of activated apps:**

> sudo -u www-data php occ app:list
> Enabled:
> - activity: 2.2.1
> - calendar: true
> - comments: 0.2
> - contacts: true
> - dav: 0.1.5
> - encryption: 1.2.0
> - federatedfilesharing: 0.1.0
> - federation: 0.0.4
> - files: 1.4.4
> - files_pdfviewer: 0.8
> - files_sharing: 0.9.1
> - files_texteditor: 2.1
> - files_trashbin: 0.8.0
> - files_versions: 1.2.0
> - files_videoplayer: 0.9.8
> - firstrunwizard: 1.1
> - gallery: 14.5.0
> - notifications: 0.2.3
> - provisioning_api: 0.4.1
> - systemtags: 0.2
> - templateeditor: 0.1
> - updatenotification: 0.1.0
>   Disabled:
> - external
> - files_external
> - user_external
> - user_ldap

**The content of config/config.php:**

> sudo -u www-data php occ config:list system
> {
>     "system": {
>         "instanceid": "ocyetdokb659",
>         "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
>         "secret": "**_REMOVED SENSITIVE VALUE**_",
>         "trusted_domains": [
>             [...]
>         ],
>         "datadirectory": "\/home\/www\/xxx\/httpdocs\/data",
>         "overwrite.cli.url": "https:\/\/xxx",
>         "dbtype": "mysql",
>         "version": "9.0.0.19",
>         "dbname": "cloud",
>         "dbhost": "localhost",
>         "dbtableprefix": "oc_",
>         "dbuser": "**_REMOVED SENSITIVE VALUE**_",
>         "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
>         "logtimezone": "UTC",
>         "installed": true,
>         "enable_previews": true,
>         "preview_max_x": 2048,
>         "preview_max_y": 2048,
>         "preview_max_scale_factor": 10,
>         "mail_smtpmode": "smtp",
>         "mail_from_address": "no-reply",
>         "mail_domain": "xxx",
>         "mail_smtpsecure": "ssl",
>         "mail_smtpauthtype": "LOGIN",
>         "mail_smtpauth": 1,
>         "mail_smtphost": "xxx",
>         "mail_smtpport": "465",
>         "mail_smtpname": "**_REMOVED SENSITIVE VALUE**_",
>         "mail_smtppassword": "**_REMOVED SENSITIVE VALUE**_",
>         "loglevel": 3,
>         "asset-pipeline.enabled": false,
>         "maintenance": false,
>         "theme": "",
>         "trashbin_retention_obligation": "auto",
>         "memcache.local": "\OC\Memcache\APCu"
>     }
> }

**Are you using external storage, if yes which one:**
No, just local

**Are you using encryption:**
yes

**Are you using an external user-backend, if yes which one:**
No
### Client configuration

**Browser:** Google Chrome Version 45.0.2454.93 (64-bit)
**Operating system:** Linux Mint 17

client configuration doesn't matter, it affects all clients
#### ownCloud log (data/owncloud.log)

{"reqId":"jIAVA9vq7Oh4V0JNx7Fn","remoteAddr":"xxx","app":"PHP","message":"OCA\Encryption\Exceptions\PublicKeyMissingException: Public Key missing for user: XYZ at \/home\/www\/xxx\/httpdocs\/apps\/encrypti}
{"reqId":"zskRoWzXPxQDP47atVvk","remoteAddr":"xxx","app":"no app in context","message":"Exception: {\"Exception\":\"OCA\\Encryption\\Exceptions\\PublicKeyMissingException\",\"Message\":\"Public Key missing for user: XYZ}
Exception: {"Exception":"OCA\Encryption\Exceptions\PublicKeyMissingException","Message":"Public Key missing for user: XYZ","Code":0,"Trace":"#0 \/home\/www\/xxx\/httpdocs\/apps\/encryption\/lib\/crypto\/encryption.php(393): OCA\Encryption\KeyManager->getPublicKey('XYZ')\n#1 \/home\/www\/xxx\/httpdocs\/lib\/private\/encryption\/update.php(181): OCA\Encryption\Crypto\Encryption->update('\/house\/files\/Al...', 'house', Array)\n#2 \/home\/www\/xxx\/httpdocs\/lib\/private\/encryption\/update.php(90): OC\Encryption\Update->update('\/house\/files\/\/A...')\n#3 \/home\/www\/xxx\/httpdocs\/lib\/private\/encryption\/hookmanager.php(35): OC\Encryption\Update->postShared(Array)\n#4 [internal function]: OC\Encryption\HookManager::postShared(Array)\n#5 \/home\/www\/xxx\/httpdocs\/lib\/private\/hook.php(105): call_user_func(Array, Array)\n#6 \/home\/www\/xxx\/httpdocs\/lib\/private\/share20\/manager.php(595): OC_Hook::emit('OCP\\Share', 'post_shared', Array)\n#7 \/home\/www\/xxx\/httpdocs\/apps\/files_sharing\/api\/share20ocs.php(370): OC\Share20\Manager->createShare(Object(OC\Share20\Share))\n#8 \/home\/www\/xxx\/httpdocs\/apps\/files_sharing\/api\/ocssharewrapper.php(44): OCA\Files_Sharing\API\Share20OCS->createShare()\n#9 [internal function]: OCA\Files_Sharing\API\OCSShareWrapper->createShare(Array)\n#10 \/home\/www\/xxx\/httpdocs\/lib\/private\/api.php(175): call_user_func(Array, Array)\n#11 [internal function]: OC_API::call(Array)\n#12 \/home\/www\/xxx\/httpdocs\/lib\/private\/route\/router.php(273): call_user_func(Array, Array)\n#13 \/home\/www\/xxx\/httpdocs\/ocs\/v1.php(52): OC\Route\Router->match('\/ocs\/apps\/files...')\n#14 \/home\/www\/xxx\/httpdocs\/ocs\/v2.php(22): require_once('\/home\/www\/cloud...')\n#15 {main}","File":"\/home\/www\/xxx\/httpdocs\/apps\/encryption\/lib\/keymanager.php","Line":530} 

thanks for having a look.
cheers,
dennis

**Comment by RealRancor** [comment]
> ownCloud version: (see ownCloud admin page) 9.0.0

Not sure but it always worth to use the latest available (stable) release which is currently 9.0.2 before creating a bugreport.

**Comment by PVince81** [comment]
Please post the contents of the folder(s) "data/$user/files_encryption/OC_DEFAULT_MODULE"
It is likely that this user's public key is missing for some unknown reason.

**Comment by DaDenniX** [comment]
I will update the owncloud tomorrow. It is not possible to do this now.

the contents of the folders are:

.../data/XXX/files_encryption/OC_DEFAULT_MODULE:
-rw-r--r-- 1 www-data www-data 4.4K Jun 21 14:48 XXX.privateKey
-rw-r--r-- 1 www-data www-data  800 Jun 21 14:48 XXX.publicKey

$ cat XXX.publicKey
-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsGSQ34N7D8Earvbrg9Bu
[...]
-----END PUBLIC KEY-----

This is also for all other users with the same error. All public and private keys exists.

**Comment by DaDenniX** [comment]
I can't update my installation. It says:
 ./occ upgrade
 ownCloud is already latest version

Channel is set to stable.

**Comment by RealRancor** [comment]
./occ upgrade won't download or install an update/upgrade. Instead follow the documentation available here:

https://doc.owncloud.org/server/9.0/admin_manual/maintenance/manual_upgrade.html

**Comment by PVince81** [comment]
Please try again with 9.0.7 or more recent version.
If the problem persists for newly created users, please reopen.
