### ISSUE TITLE
Content Security Policy issue after PHP upgrade

### ISSUE THREAD

**Issue by beauraF** [owncloud/core#25278]
Hi,

After a PHP upgrade, I can't access to my owncloud. I encounter a Content Security Policy issue. Any idea ? :(

### Server configuration
**Operating system**:
Debian Jessie

**Web server:**
Nginx 1.10.1

**PHP version:**
PHP 7.0.8-1

**ownCloud version:** (see ownCloud admin page)
Last owncloud 9 release

### Client configuration
**Browser:**
Firefox (last release)
Chrome (last release)
Safari (last release)

**Operating system:**
Mac OSX

#### ownCloud log (data/owncloud.log)
{"reqId":"mc7IVTAP8fXei8vUBdYT","remoteAddr":"*.*.*.*","app":"PHP","message":"Error: Call to undefined function OC\\App\\simplexml_load_file() at \/var\/www\/owncloud\/lib\/private\/app\/infoparser.php#60","level":3,"time":"2016-06-27T15:57:42+00:00","method":"GET","url":"\/","user":"--"}

#### Browser log
Content Security Policy: La directive « frame-src » est obsolète. Veuillez utiliser la directive « child-src » à la place. (source inconnue)
Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« script-src https://cloud.example.com 'unsafe-eval' »).

**Comment by RealRancor** [comment]
@beauraF See: https://forum.owncloud.org/viewtopic.php?f=38&t=37509#p119120

For such support questions please also use either the forums or the users mailinglist (See: https://owncloud.org/support/)

**Comment by beauraF** [comment]
Thank you very much @RealRancor ! It fixes the problem. 

Have a nice day !
