### ISSUE TITLE
Connecting to SFTP using login credentials, store in session fails

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#25272]
### Steps to reproduce

1. Enable external storage and mount a SFTP folder using login credentials store in session available for all users.
2. Using admin user create a user with SFTP credentials.
3. Login using user created in 2. Try to access SFTP folder.
 
### Expected behaviour
User can access SFTP folder.

### Actual behaviour
That user cannot access using session credentials.

Server configuration

Operating system:
Centos 6.6

Web server:
Apache

Database:
MySQL

PHP version:
5.5.9

ownCloud version: (see ownCloud admin page)
Master branch
{"installed":true,"maintenance":false,"version":"9.1.0.9","versionstring":"9.1.0 beta 2","edition":"Enterprise"}

Updated from an older ownCloud or fresh install:
Fresh

The content of config/config.php:

Are you using external storage, if yes which one: local/smb/sftp/...
Yes SFTP.

Are you using encryption: 
No

Logs
```
{"reqId":"LzYZLpb6jXR2q4EqFVtK","remoteAddr":"HIDDEN_IP","app":"files_external","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Login failed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SFTP.php(155): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SFTP->getConnection()\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(231): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SFTP->test(false, false)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(255): OC_Mount_Config::getBackendStatus('\\\\OCA\\\\Files_Exte...', Array, false, false)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/UserGlobalStoragesController.php(119): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_External\\\\Lib\\\\StorageConfig), false)\\n#4 [internal function]: OCA\\\\Files_External\\\\Controller\\\\UserGlobalStoragesController->show(1, false)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\UserGlobalStoragesController), 'show')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(110): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\UserGlobalStoragesController), 'show')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('UserGlobalStora...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(879): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SFTP.php\",\"Line\":140}","level":3,"time":"2016-06-27T07:44:09+00:00","method":"GET","url":"\/index.php\/apps\/files_external\/userglobalstorages\/1?testOnly=false","user":"admin"}
```
Client configuration

browser
Chrome

**Comment by SergioBertolinSG** [comment]
cc @owncloud/filesystem

**Comment by PVince81** [comment]
I'm getting a different error on master:
"There was an error with message: Insufficient data: No session credentials saved. Do you want to review mount point config in admin settings page?"

and nothing in the log.

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
711bc7469ae3261e3813a82e3807691ec3904098
8f58b89c3f01c31cc7b6c59830741af048559e2e
af0930fe59971ce610270a873a4c2d70012a8534
4728308a9ec79fe41b137b9d401c3c2f56f27f4d
We cannot bisect more!

**Comment by PVince81** [comment]
Worked properly in v9.0.2

**Comment by PVince81** [comment]
Regression likely introduced through https://github.com/owncloud/core/pull/24585 by @Xenopathic

**Comment by PVince81** [comment]
I did some debugging and it looks like the hook connection from the auth backend is done **after** the postLogin hook was already triggered, which is too late.

**Comment by PVince81** [comment]
So much for being lazy... loading

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/25273
It removes lazy loading for auth mechanisms as a quickfix.
