### ISSUE TITLE
owncloud-deps-php7.0 must not depend on libapache2-mod-php7.0, but on php7.0 instead

### ISSUE THREAD

**Issue by oerdnj** [owncloud/core#25283]
With my PHP Debian packaging hat on, ...

The `owncloud-deps-php7.0` package forces users to pull apache2 PHP SAPI instead allowing them to pick the right one (apache2, fpm, cgi). You need to change to `owncloud-deps-php7.0` to depend on `php7.0` which is the correct dependency as `php7.0` itself depends on `libapache2-mod-php7.0 | php7.0-fpm | php7.0-cgi` (picking `libapache2-mod-php7.0`) as a first choice.

**Comment by RealRancor** [comment]
@oerdnj AFAIK ``libapache2-mod-php7.0`` is the only officially supported Apache module. If you want to use other unsupported modules you could install ``owncloud-files``

**Comment by oerdnj** [comment]
It's not duplicate per se. I am suggesting a solution that will work same (as `libapache2-mod-php7.0` is the first dependency, so it will get picked) while adding ability to manually pick different PHP SAPI. It will not cause any harm, but it will enhance the package.

**Comment by enoch85** [comment]
cc @jnweiger

**Comment by jnweiger** [comment]
Good news, that php7.0 itself pulls in one of the apache modules. thanks @oerdnj 

We also have this dependency:
```apache2 (>= 2.4.0) | httpd```
in the same package. Probably also redundant. Right?

**Comment by oerdnj** [comment]
@jnweiger `apache2 | httpd` is fine as:
```
$ apt-cache show nginx-full | grep Provides
Provides: httpd, httpd-cgi, nginx
```
So it picks the right default, but allows installation of other webservers.

**Comment by jnweiger** [comment]
Ok. Thanks. keeping the apache2 | httpd clause.

Hmm, I have to investigate the removal of the libapache2-mod-php7.0 dependency. My smoke tests seem to explode without it.

**Comment by oerdnj** [comment]
@jnweiger Try `libapache2-mod-php7.0 | php7.0` instead

**Comment by jnweiger** [comment]
@oerdnj that's it! thanks.

**Comment by jnweiger** [comment]
9.0.3 has the fix.

**Comment by enoch85** [comment]
This breaks the VM that is installed from packages. Instead of the regular ownCloud login I get a page with alot of text.

```
<?php
/**
 * @author Jörn Friedrich Dreyer <jfd@butonic.de>
 * @author Lukas Reschke <lukas@owncloud.com>
 * @author Morris Jobke <hey@morrisjobke.de>
 * @author Robin Appelman <icewind@owncloud.com>
 * @author Thomas Müller <thomas.mueller@tmit.eu>
 * @author Vincent Petry <pvince81@owncloud.com>
 *
 * @copyright Copyright (c) 2016, ownCloud, Inc.
 * @license AGPL-3.0
 *
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License, version 3,
 * along with this program.  If not, see <http://www.gnu.org/licenses/>
 *
 */

// Show warning if a PHP version below 5.4.0 is used, this has to happen here
// because base.php will already use 5.4 syntax.
if (version_compare(PHP_VERSION, '5.4.0') === -1) {
	echo 'This version of ownCloud requires at least PHP 5.4.0<br/>';
	echo 'You are currently running ' . PHP_VERSION . '. Please update your PHP version.';
	return;
}

try {
	
	require_once 'lib/base.php';

	OC::handleRequest();

} catch(\OC\ServiceUnavailableException $ex) {
	\OCP\Util::logException('index', $ex);

	//show the user a detailed error page
	OC_Response::setStatus(OC_Response::STATUS_SERVICE_UNAVAILABLE);
	OC_Template::printExceptionErrorPage($ex);
} catch (\OC\HintException $ex) {
	OC_Response::setStatus(OC_Response::STATUS_SERVICE_UNAVAILABLE);
	OC_Template::printErrorPage($ex->getMessage(), $ex->getHint());
} catch (Exception $ex) {
	\OCP\Util::logException('index', $ex);

	//show the user a detailed error page
	OC_Response::setStatus(OC_Response::STATUS_INTERNAL_SERVER_ERROR);
	OC_Template::printExceptionErrorPage($ex);
}
```

**Comment by enoch85** [comment]
@jnweiger ---^

**Comment by enoch85** [comment]
Installing libapache2-mod-php7.0 seperatly fixes it again. Please revert that fix, or make it work again. Thank you.

(Just lost 2 hours due to this due to repackaging, *wohaa*)

**Comment by oerdnj** [comment]
Could you provide `/var/log/apt` logs to see what really happened?

**Comment by enoch85** [comment]
@oerdnj Sorry, already packaged the new VMs and thrown away the old ones. But feel free to test for yourself: https://github.com/enoch85/ownCloud-VM/blob/master/production/owncloud_install_production.sh

Remove this line: https://github.com/enoch85/ownCloud-VM/blob/master/production/owncloud_install_production.sh#L236

It will complain about Redis if you do that, but I left the other lines if you want to run it via mods-availible instead: https://github.com/enoch85/ownCloud-VM/blob/master/static/redis-server-ubuntu16.sh#L50-L54

A clean Ubuntu 16.04 Server (VM) is required.

Thanks for testing!

**Comment by Bebef** [comment]
Seems that 9.1.0-1.1 (in Ubuntu 16.04) still has the dependency?

**Comment by ypid** [comment]
Note that on Ubuntu 14.04 (and others), the virtual package "php7.0" does not exist so this will not detect an already installed PHP FPM.

```
$ lsb_release -a           
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
$ aptitude search '~Pphp7.0'
$ 
```

**Comment by enoch85** [comment]
@Bebef If you install owncloud via `apt-get` you will automatically get the dependencies. If you want to install owncloud without any dependencies you have to install `owncloud-files`.

**Comment by hodyroff** [comment]
owncloud-files is the default we recommend. closing.
