### ISSUE TITLE
Issue with sharing to group and user in group

### ISSUE THREAD

**Issue by nneul** [owncloud/core#25282]
### Steps to reproduce
A1. Share to a group that contains X 
A2. Try to share to X

B1. Share to X
B2. Share to a group that contains X

### Expected behaviour
Should be the same, in both cases, should be allowed. Since I might share to the group read-only and then one user in the group read-write

### Actual behaviour
B works fine. A throws up error saying it's already shared to X, even though it's only shared to a group that contains X.

**Comment by hodyroff** [comment]
If you give full rights to the group, this is correct behaviour. Please retest with giving read only to the group and full rights to the user. It should actually work. Please add which version you are testing with.

**Comment by nneul** [comment]
1. I'd disagree with that being 'correct' - or at least not necessarily the most useful. Just because a given user has the rights as being part of a group doesn't mean they shouldn't be able to have them granted directly. Think if you're planning on removing the group access, or it is known to be temporary. Certainly highlighting in the UI that the permissions are currently redundant would be great (would love to see that indicator). Or even a warning that they already have the permissions, but still adding them. 

2. Added group - unchecked the 'can edit' checkbox. Tried to add individual user - still get the error.

3. 9.0.2 tarball install on ubuntu 16.04.

**Comment by PVince81** [comment]
Similar to https://github.com/owncloud/core/issues/18984

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/issues/25113 that seems to address this

**Comment by PVince81** [comment]
Please try again with 9.0.4, the error was a regression and was fixed there.
