### ISSUE TITLE
'apt-get update' complains about a weak digest. This is about #23599

### ISSUE THREAD

**Issue by takenek** [owncloud/core#25295]
When patch will be merge to stable ?
Got it in sources.list: 
deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /

and still:
W: http://download.owncloud.org/download/repositories/stable/Debian_8.0/Release.gpg: Signature by key BCECA90325B072AB1245F739AB7C32C35180350A uses weak digest algorithm (SHA1)

Best Regards
TaKeN

**Comment by georgehrke** [comment]
cc @danimo @jnweiger

**Comment by sandprickle** [comment]
Also on Ubuntu xenial stable repo.

**Comment by eldiablo62** [comment]
I have also the problem . Some people have the solution ? 
: http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/Release.gpg: Signature by key DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B uses weak digest algorithm (SHA1)

**Comment by RealRancor** [comment]
@takenek The repositories are now signed with a strong algorithm so you can close this issue.

If re-importing the new key doesn't work for you note the following steps:

> I was able to fix it by removing the package source, followed by running apt-get update. After adding the source again, everything installed fine. Weirdly just running apt-get clean instead, which I thought does the same, did not fix my issue.

https://github.com/owncloud/client/issues/5055#issuecomment-255063655

**Comment by crrodriguez** [comment]
This issue was fixed like @ghost said, closing
