### ISSUE TITLE
Allow admins to revoke authentication tokens

### ISSUE THREAD

**Issue by butonic** [owncloud/core#25307]
Currently, users can revoke a token themselves. Admins should be able to revoke them as well to remain in control.

**Comment by butonic** [comment]
cc @danimo @felixboehm @ChristophWurst @DeepDiver1975

**Comment by PVince81** [comment]
Yeah, some ideas we discussed with @ChristophWurst for the UI:

- provide a search field in the admin page to be able to search for a user and then display that user's sessions with "Disconnect" buttons.
- maybe add a button "Disconnect all" too

Not sure if this should be a dedicated page.
Also thought about adding a link from the users page, but as I understand there are some user managers (shibboleth, IMAP?) where there is no user list so one still needs to be able to search by user to perform the operation.

**Comment by PVince81** [comment]
cc @tomneedham 

I thought we had an occ command for this already

**Comment by tomneedham** [comment]
Whats the roadmap for these token with OAuth now here? OCC commands should be around as well.

**Comment by PVince81** [comment]
I'm moving this to triage for future scheduling. @pmaier1
