### ISSUE TITLE
Centos installer apache configuration issue

### ISSUE THREAD

**Issue by fondemen** [owncloud/core#25306]
### Steps to reproduce
1. Install a fresh CentOS 7 box
2. Apply instructions given at https://download.owncloud.org/download/repositories/stable/owncloud/ for CentOS
3. yum install owncloud

### Expected behaviour
Apache is up and running, one can query http://localhost/owncloud and get the owncloud installation wizard
/etc/httpd/conf.d/owncloud.conf contains references to /var/www/html/owncloud

### Actual behaviour
Apache is up and running, but http://localhost/owncloud leads to a 404 error
/etc/httpd/conf.d/owncloud.conf contains references to /var/www/html/owncloud/owncloud

sed -i 's;owncloud/owncloud;owncloud;g' /etc/httpd/conf.d/owncloud.conf is enough to solve the issue

### Server configuration
**Operating system**:
CentOS Linux release 7.2.1511 (Core)

**Web server:**
Apache 2.4.6

**Database:**
NC

**PHP version:**
5.4.16

**ownCloud version:** (see ownCloud admin page) 
9.0.2-1.1

**Updated from an older ownCloud or fresh install:** 
Fresh install

**Where did you install ownCloud from:** 
https://download.owncloud.org/download/repositories/stable/owncloud/

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
NC

**List of activated apps:**
NC

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Error (I guess because config.php was not generated)...

**The content of config/config.php:**
Empty

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
No config.php

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Opera, curl, ...

**Operating system:**
MacOS X, Linux, ...

#### Web server error log
```
Insert your webserver log here
```
NC

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
NC

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
NC

**Comment by RealRancor** [comment]
Mhhh, strange. Normally this should have been already fixed: https://github.com/owncloud/core/issues/23887

cc @jnweiger

**Comment by PVince81** [comment]
Is this still an issue ? If yes, please reopen.

CC @owncloud/packaging
