### ISSUE TITLE
Client 2.2.2 Win10 x64: Junction links are being synced

### ISSUE THREAD

**Issue by Pathduck** [owncloud/core#25303]
Since the 2.2.2 update the client has started syncing directories linked by junction points (symlinks on Windows). 

I am syncing My Documents folder, on Windows this contains a "My Games" folder which often gets very large. I have created a junction point to another drive to save space on c:. 

Earlier versions of the OC client did not sync these, I believe junctions stopped syncing some 1.x release. Now they are suddenly back to working, and I did not find any thing in the release log to explain why they would now work when before they did not. If they now are expected to work I have to rethink my folder setup.

### Steps to reproduce
1. Create an NTFS junction point in a synced folder 
2. Start client and add folder
3. The files in the linked folder will also be synced

### Expected behaviour
I would expect links (junction points) to not be synced

### Actual behaviour
The files in the linked folder are synced

### Server configuration
Owncloud 9.0
I don't own the server, it's a shared hosting solution. I assume this is a client issue.

### Client configuration
Firefox 47
Owncloud Client 2.2.2

**Operating system:**
Windows 10 x64

**Comment by RealRancor** [comment]
@Pathduck Please re-open at https://github.com/owncloud/client/issues where the issue tracker of the sync client is located

**Comment by Pathduck** [comment]
Oh sorry about that, will do.
