### ISSUE TITLE
Request file sharing with permalink

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25317]
In 9.1 we introduced permalinks: https://github.com/owncloud/core/issues/11732

When a user who doesn't have access to the file opens the permalink, they currently get a 404 not found page.

A nice addition would be to convert this into a "request access" page which would prompt the owner of the file/folder in a notification to share it with that user.

@owncloud/designers @dragotin

**Comment by dragotin** [comment]
From a sync- or mobile client perspective, it would be cool if the user on the client would not have to decide if he needs to create a *public link* or a *local link* or share with a owncloud user.

If the local link is used from an not registered user, the server should create a notification like "A user wants to access file xyz - do you want to allow that?" - With the potential answers *No", *Yes, for the file*, "*Yes, the whole folder*" in case it is a file in a folder.

**Comment by PVince81** [comment]
Indeed, the other question here is we can somehow merge the local link with public link functionality to have a unified way of sharing.

**Comment by dragotin** [comment]
Yes, basically that is the idea. That would really make ownCloud a better platform.

**Comment by PVince81** [comment]
The request access page:

- if user is external, enter email address
    - choose whether to become guest user or just receive public link
- if user has a login
    - click button to get direct user share
    - or: select group from their membership groups to request the share to go to (if we want this)

After validating, if a user/group share was requested, the share in question should appear already in the list of current user shares, but with an indicator that it's pending and buttons to accept/reject.
