### ISSUE TITLE
OC_DB::getDbStructure() doesn't support longblob mysql field type

### ISSUE THREAD

**Issue by pbek** [owncloud/core#25316]
### Steps to reproduce
1. calling a `$this->odb->getDbStructure( $structureFile )` to export table `oc_calendarobjects` in <https://github.com/pbek/ownbackup/blob/develop/service/backupservice.php>
2. in the resulting XML the column `calendardata` only has `<field><name>calendardata</name></field>`
3. a restore of the data of the table fails with an exception `An exception occurred while executing 'INSERT INTO `oc_calendarobjects` ............ 9DFC-0A47CCE054A9"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'calendardata' in 'where clause'`

### Expected behaviour
The field `calendardata` should look like this: `<field><name>calendardata</name><type>clob</type><notnull>false</notnull></field>` or `<field><name>calendardata</name><type>blob</type></field>` 

(depends on where you look, I used `owncloud/core/apps/dav/tests/unit/migration/calendar_schema.xml` and `owncloud/core/apps/dav/appinfo/database.xml` as reference)

### Actual behaviour
The field `calendardata` looks like this: `<field><name>calendardata</name></field>`

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0.4

**ownCloud version:** (see ownCloud admin page)
9.1.0.8 and 9.0.2

**Updated from an older ownCloud or fresh install:**
upgrade from 8.x

**List of activated apps:**

```
Enabled:
  - activity: 2.1.3
  - calendar: 1.2.2
  - comments: 0.3.0
  - contacts: 1.3.1.0
  - dav: 0.2.4
  - encryption: 1.3.0
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - music: 0.3.11
  - notes: 2.0.1
  - ownbackup: 0.3.8
  - provisioning_api: 0.5.0
  - qownnotesapi: 0.4.4
  - systemtags: 0.3.0
  - tasks: 0.9.1
  - updatenotification: 0.2.1
Disabled:
  - announcementcenter
  - bookmarks
  - chat
  - documents
  - gallery
  - news
  - ownnote
  - sharelinks
  - testing
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ociuf2r3opzp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/my-user\/Web\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost:8080",
        "dbtype": "mysql",
        "version": "9.1.0.8",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "singleuser": false,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by DeepDiver1975** [comment]
Please don't use classes outside of the Namespace OCP.

This specific method is unused for ages obsiously.
We better remove that one.

In case you want to have a database export please use the methods around doctrine Schema. The current Schema can be retrieved from the connection

**Comment by pbek** [comment]
Thank you for the quick answer. How is ownCloud currently migrating tables? I tried to do the same for ownbackup back then... We need to store and restore tables.
