### ISSUE TITLE
Unnecessary RewriteBase / change on update to 9.0.3

### ISSUE THREAD

**Issue by Vinschni** [owncloud/core#25319]
Upgrade from 9.0.2 to 9.0.3 changes _RewriteBase /youralias_ in .htaccess to _RewriteBase /_

This causes 404 error if not changed back if an alias is used under apache.

**Comment by RealRancor** [comment]
@Vinschni configure your ``overwrite.cli.url`` and ``htaccess.RewriteBase`` in your config.php correctly (See https://github.com/owncloud/documentation/issues/2431#issuecomment-221982282) and a correct RewriteBase should be set automatically.

**Comment by Vinschni** [comment]
That pice of Dokumentation was missing in my mind. I now understood that overwrite.cli.url configures RewriteBase on update.

**Comment by RealRancor** [comment]
@Vinschni Unfortunately its not really documented but hopefully someone will do that as those are infos which are really missing within the documentation.

**Comment by hodyroff** [comment]
@jnweiger FYI
