### ISSUE TITLE
Share indicator not appearing upon sharing, only after refresh

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25311]
### Steps
1. Create a folder "test"
2. Share "test" with another user or with link
3. Check the share icon/indicator on the row
### Expected result

Share indicator is updated to say "Shared"
### Actual result

The row is re-rendered, but the indicator still doesn't say anything.
Only after refreshing the page it says "Shared".
### Versions

Observed on v9.0.2 and v9.1.0RC1

Regression from v8.2.5

**Comment by PVince81** [comment]
@mcastroSG are you saying it also happens on 8.2.6 ?

**Comment by mcastroSG** [comment]
@PVince81 it´s happening on 8.2.6. and if you share by link files once it´s unshared in case of click on "Sharing" section icon disappears but for folders it remains, does not matter what you do.

**Comment by PVince81** [comment]
Oh, it only happens for folders, not files

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/25838
