### ISSUE TITLE
share file with specified user, failed, Public Key missing

### ISSUE THREAD

**Issue by joeyjy** [owncloud/core#25321]
### Steps to reproduce
1. share a file or folder to a specified user 
2.
3.

### Expected behaviour
login with the shared user and load that file, google chrome error ERR_INVALID_RESPONSE,
server log Could not encrypt file...Public Key missing for user

### Actual behaviour
upload successfully

### Server configuration
**Operating system**: Centos7

**Web server:** apache 2.4

**Database:** mysql 5.5

**PHP version:** 5.4

**ownCloud version:** (see ownCloud admin page) 9.0.1

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
  - user_ldap: 0.8.0
Disabled:
  - external
  - files_texteditor
  - firstrunwizard
  - user_cas
  - user_shib
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocubu9q7jih1",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.18.6.115",
            "10.18.6.116",
            "owncloud.matrix.ctripcorp.com"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/10.18.6.115",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "cdrive_db",
        "dbhost": "10.18.6.116",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "keysalt": "shitoc",
        "default_language": "zh_CN",
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\Swift",
            "arguments": {
                "username": "swift",
                "password": "***REMOVED SENSITIVE VALUE***",
                "container": "owncloudbase",
                "autocreate": true,
                "region": "RegionOne",
                "url": "http:\/\/cloud.matrix.ctripcorp.com:5000\/v2.0",
                "tenantName": "service",
                "serviceName": "swift",
                "urlType": "internal"
            }
        },
        "loglevel": 2,
        "ldapIgnoreNamingRules": false
    }
}
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/... Ceph objectstorage swift

**Are you using encryption:** yes/no yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... LDAP

#### LDAP configuration (delete this part if not used)
+-------------------------------+----------------------+
| Configuration                 | s01                  |
+-------------------------------+----------------------+
| hasMemberOfFilterSupport      | 0                    |
| hasPagedResultSupport         |                      |
| homeFolderNamingRule          |                      |
| lastJpegPhotoLookup           | 0                    |
| ldapAgentName                 |                      |
| ldapAgentPassword             | ***                  |
| ldapAttributesForGroupSearch  |                      |
| ldapAttributesForUserSearch   |                      |
| ldapBackupHost                |                      |
| ldapBackupPort                |                      |
| ldapBase                      |                      |
| ldapBaseGroups                |                      |
| ldapBaseUsers                 |                      |
| ldapCacheTTL                  | 600                  |
| ldapConfigurationActive       | 0                    |
| ldapDynamicGroupMemberURL     |                      |
| ldapEmailAttribute            |                      |
| ldapExperiencedAdmin          | 0                    |
| ldapExpertUUIDGroupAttr       |                      |
| ldapExpertUUIDUserAttr        |                      |
| ldapExpertUsernameAttr        |                      |
| ldapGroupDisplayName          | cn                   |
| ldapGroupFilter               |                      |
| ldapGroupFilterGroups         |                      |
| ldapGroupFilterMode           | 0                    |
| ldapGroupFilterObjectclass    |                      |
| ldapGroupMemberAssocAttr      | uniqueMember         |
| ldapHost                      | cn1.global.ctrip.com |
| ldapIgnoreNamingRules         |                      |
| ldapLoginFilter               |                      |
| ldapLoginFilterAttributes     |                      |
| ldapLoginFilterEmail          | 0                    |
| ldapLoginFilterMode           | 0                    |
| ldapLoginFilterUsername       | 1                    |
| ldapNestedGroups              | 0                    |
| ldapOverrideMainServer        |                      |
| ldapPagingSize                | 500                  |
| ldapPort                      | 389                  |
| ldapQuotaAttribute            |                      |
| ldapQuotaDefault              |                      |
| ldapTLS                       | 0                    |
| ldapUserDisplayName           | displayName          |
| ldapUserDisplayName2          |                      |
| ldapUserFilter                |                      |
| ldapUserFilterGroups          |                      |
| ldapUserFilterMode            | 0                    |
| ldapUserFilterObjectclass     |                      |
| ldapUuidGroupAttribute        | auto                 |
| ldapUuidUserAttribute         | auto                 |
| turnOffCertCheck              | 0                    |
| useMemberOfToDetectMembership | 1                    |
+-------------------------------+----------------------+
```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** google chrome

**Operating system:** windows7 basic

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
`{"reqId":"V3YaiqLrERYU0FBoAslOewAAAAg","remoteAddr":"10.32.51.48","app":"no app in context","message":"Could not encrypt file for 102A70CB-DC26-4784-B4FB-81D2F275CEF6: Public Key missing for user: 102A70CB-DC26-4784-B4FB-81D2F275CEF6","level":2,"time":"2016-07-01T07:23:55+00:00","method":"POST","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json","user":"cdrive"}
{"reqId":"V3Ybye9oVE6GVtPlrvx@YgAAAAs","remoteAddr":"10.32.51.48","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2016-07-01T07:29:15+00:00","method":"GET","url":"\/remote.php\/webdav\/test.pcapng","user":"102A70CB-DC26-4784-B4FB-81D2F275CEF6"}
{"reqId":"V3Ybye9oVE6GVtPlrvx@YgAAAAs","remoteAddr":"10.32.51.48","app":"webdav","message":"Exception: {\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(459): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('M8ldbHE+XrGEOW8...', 0)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(290): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#2 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(83): fread(Resource id #700, 8192)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(91): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#5 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #704, Resource id #714, '35295824')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php\",\"Line\":360,\"User\":\"102A70CB-DC26-4784-B4FB-81D2F275CEF6\"}","level":4,"time":"2016-07-01T07:29:15+00:00","method":"GET","url":"\/remote.php\/webdav\/test.pcapng","user":"102A70CB-DC26-4784-B4FB-81D2F275CEF6"}
{"reqId":"V3Ybye9oVE6GVtPlrvx@YgAAAAs","remoteAddr":"10.32.51.48","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:80) at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-07-01T07:29:15+00:00","method":"GET","url":"\/remote.php\/webdav\/test.pcapng","user":"102A70CB-DC26-4784-B4FB-81D2F275CEF6"}
{"reqId":"V3Ybye9oVE6GVtPlrvx@YgAAAAs","remoteAddr":"10.32.51.48","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:80) at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-07-01T07:29:15+00:00","method":"GET","url":"\/remote.php\/webdav\/test.pcapng","user":"102A70CB-DC26-4784-B4FB-81D2F275CEF6"}
{"reqId":"V3Ybye9oVE6GVtPlrvx@YgAAAAs","remoteAddr":"10.32.51.48","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:80) at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-07-01T07:29:15+00:00","method":"GET","url":"\/remote.php\/webdav\/test.pcapng","user":"102A70CB-DC26-4784-B4FB-81D2F275CEF6"}
{"reqId":"V3Ybye9oVE6GVtPlrvx@YgAAAAs","remoteAddr":"10.32.51.48","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:80) at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-07-01T07:29:15+00:00","method":"GET","url":"\/remote.php\/webdav\/test.pcapng","user":"102A70CB-DC26-4784-B4FB-81D2F275CEF6"}
{"reqId":"V3Ybye9oVE6GVtPlrvx@YgAAAAs","remoteAddr":"10.32.51.48","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:80) at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-07-01T07:29:15+00:00","method":"GET","url":"\/remote.php\/webdav\/test.pcapng","user":"102A70CB-DC26-4784-B4FB-81D2F275CEF6"}
{"reqId":"V3Ybye9oVE6GVtPlrvx@YgAAAAs","remoteAddr":"10.32.51.48","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:80) at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-07-01T07:29:15+00:00","method":"GET","url":"\/remote.php\/webdav\/test.pcapng","user":"102A70CB-DC26-4784-B4FB-81D2F275CEF6"}
{"reqId":"V3Ybye9oVE6GVtPlrvx@YgAAAAs","remoteAddr":"10.32.51.48","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php:80) at \/var\/www\/html\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-07-01T07:29:15+00:00","method":"GET","url":"\/remote.php\/webdav\/test.pcapng","user":"102A70CB-DC26-4784-B4FB-81D2F275CEF6"}`
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

Hi OC team,

I enabled encryption and use ceph object storage in owncloud, when share a file or a folder to a  specified user, failed, user can't download it, but can see it in the file list, according to owncloud.log, saying **Public Key missing**, can you help me with this? Thanks!

**Comment by joeyjy** [comment]
even myself, can't download file :(

**Comment by PVince81** [comment]
@joeyjy possible duplicate of https://github.com/owncloud/core/issues/25246 ?

Please check if you can find the user's public key: https://github.com/owncloud/core/issues/25246#issuecomment-228765851

**Comment by joeyjy** [comment]
@PVince81 no public key found in objectstorage... how to recover it for user?

**Comment by joeyjy** [comment]
@PVince81 if I want to enable both object storage as primary storage+encryption+LDAP, is there an order to start them? I mean firstly enable object storage, and then encryption, finally LDAP?

**Comment by butonic** [comment]
technically, encryption and objectstorage are compatible, but you need to place encryption keys in a separate (shared) storage to not run into performance issues. If key access is fast performance should be acceptable.

ldap should not interfere with thas setup.

@joeyjy start with objectstorage, then enable master key based encryption (unless you have a really good reason to use individual user keys), finally enable ldap.

**Comment by joeyjy** [comment]
@butonic thanks for reply! How to enable master key based encryption? I enabled serverside encryption in admin page, then activated default encryption module in apps page, is this master key based encryption? I found every user has a private key and a public key

**Comment by PVince81** [comment]
@joeyjy `occ encryption:enable-master-key`.
Only do this on new installs.

**Comment by joeyjy** [comment]
@PVince81 Thanks!
