### ISSUE TITLE
Race condition could insert duplicate async jobs

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25322]
When inserting a job into the JobList queue, it's done in two steps:
1. Check if such job already exists: https://github.com/owncloud/core/blob/v9.0.3/lib/private/backgroundjob/joblist.php#L56
2. If not, insert a new one: https://github.com/owncloud/core/blob/v9.0.3/lib/private/backgroundjob/joblist.php#L69

However, the whole thing isn't wrapper in a transaction. This means that if two processes try and insert the exact same job at the exact same time, they'll both do the check at the same time, find that there is no duplicate, then insert both at the same time.

Not sure if the hash approach will help here: https://github.com/owncloud/core/pull/25100 ?
@butonic 

Does anything speak against wrapping these two calls in a transaction or will it make everything too slow ? @DeepDiver1975 @butonic

**Comment by butonic** [comment]
yes, fixed by https://github.com/owncloud/core/issues/25322

**Comment by PVince81** [comment]
Maybe a quickfix for 8.2/9.0 would be possible ?

**Comment by PVince81** [comment]
Moving to 8.2.9

**Comment by PVince81** [comment]
Can we finish https://github.com/owncloud/core/pull/25100 then ?

**Comment by PVince81** [comment]
not backportable, close ?

**Comment by PVince81** [comment]
Seems no one cares -> close.
The consequence is mostly some wasted cpu cycles in rare race condition cases.

I hope we can finish https://github.com/owncloud/core/pull/25100 then for 10.0
