### ISSUE TITLE
Add IAppManager->getAppPath method

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25336]
@scolebrook for https://github.com/owncloud/apps/pull/2129

**Comment by PVince81** [comment]
Moving to backlog.

Unless @DeepDiver1975 wants to add it as part of the new IAppManager APIs ?

**Comment by PVince81** [comment]
@phisch did you consider adding this as part of your work on making app path resolution better ?

**Comment by PVince81** [comment]
@VicDeo can you take care ? Hopefully not too complicated.

**Comment by VicDeo** [comment]
Done in 10.0.5
