### ISSUE TITLE
Button for downloading photos while on preview on a web browser.

### ISSUE THREAD

**Issue by jonesints** [owncloud/core#25333]
This is a feature request, which I believe would come in really handy for many. 
When browsing photos on a web browser, owncloud shows previews which is great, and even has a Play button for a slideshow.
But when wanting to download a photo currently displayed on preview, one has to exit this preview, and try and locate the last file previewed by lookiong between all the filenames and very small thumbnails. It'd make things a lot easier and quicker to have a Download button next to the Play button while a photo is loaded.

**Comment by PVince81** [comment]
If you're talking about the fullscreen preview, it's part of the gallery app: https://github.com/owncloud/gallery

**Comment by jonesints** [comment]
The Gallery has that function, but I have many photos which I access directly like in any other directory full of files and not through the Gallery: the photo preview function already exists when browsing files in folders, so it's the fastest way by far to see photos in any given folder. 

It could really do with that extra button to download a file, just like the Gallery preview, or any PDF preview has.

**Comment by PVince81** [comment]
@jonesints so are you talking about the preview in the sidebar then ?

**Comment by PVince81** [comment]
@jonesints mind posting a screenshot ? That could help clarify.

My point was that the fullscreen preview code is not provided by ownCloud itself but by the gallery app. If you disable the gallery app, you don't get previews. So adding a download button in the fullscreen preview needs to be done in the gallery app code.

Unless you are talking about something else.

**Comment by jonesints** [comment]
@PVince81 Thanks I see now: disabling the Gallery app disables the fullscreen Preview of photos altogether, not just when visiting the Gallery itself. Here's a screenshot of the Preview when browsing a typical folder containing photos, and another within the Gallery section (note the download icon on the second screenshot)

![photo_fullscreen_preview_outside_gallery](https://cloud.githubusercontent.com/assets/12374920/16586301/0dd07056-42bd-11e6-9ffa-8d0c8bf87916.png)
![photo_fullscreen_preview_within_gallery](https://cloud.githubusercontent.com/assets/12374920/16586361/71fb9434-42bd-11e6-82b3-6b79501ab2c5.png)

The Gallery App version in question is 14.5.0 on a server running 9.0.3, and affects all previous versions.

How would I move this feature request to owncloud/gallery?

**Comment by PVince81** [comment]
I raised a ticket there for you: https://github.com/owncloud/gallery/issues/686
