### ISSUE TITLE
Owncloud non-functional with "illegal instruction" errors, post-upgrade

### ISSUE THREAD

**Issue by mach-o** [owncloud/core#25348]
Owncloud has been non-functional since I upgraded it last night. I have also been receiving emails that look like the following every twenty minutes since then:

Subject: Cron <root@raspberrypi>   [ -x /usr/lib/php5/sessionclean ] && /usr/lib/php5/sessionclean
Body: Illegal instruction

This started when I ran a regular upgrade:

$ sudo aptitude upgrade
[snip]
Preparing to unpack .../libmysqlclient18_5.6.30-1~bpo8+1_armhf.deb ...
Unpacking libmysqlclient18:armhf (5.6.30-1~bpo8+1) over (5.5.46-0+deb7u1) ...
Preparing to unpack .../owncloud-files_9.0.3-3.1_all.deb ...
Unpacking owncloud-files (9.0.3-3.1) over (9.0.2-1.1) ...
Preparing to unpack .../owncloud-deps-php5_9.0.3-2.1_all.deb ...
owncloud-deps-php5: occ maintenance:mode --on
Illegal instruction
Unpacking owncloud-deps-php5 (9.0.3-2.1) over (9.0.2-1.1) ...
Conf owncloud disabled.
To activate the new configuration, you need to run:
  service apache2 reload
Preparing to unpack .../owncloud_9.0.3-2.1_all.deb ...
Unpacking owncloud (9.0.3-2.1) over (9.0.2-1.1) ...
Setting up libmysqlclient18:armhf (5.6.30-1~bpo8+1) ...
Setting up owncloud-files (9.0.3-3.1) ...
Setting up owncloud-deps-php5 (9.0.3-2.1) ...
Enabling conf owncloud.
To activate the new configuration, you need to run:
  service apache2 reload
Job for apache2.service failed. See 'systemctl status apache2.service' and 'journalctl -xn' for details.
apache2_invoke rewrite: already enabled
Job for apache2.service failed. See 'systemctl status apache2.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript apache2, action "restart" failed.
apache2_invoke owncloud: already enabled
Job for apache2.service failed. See 'systemctl status apache2.service' and 'journalctl -xn' for details.
invoke-rc.d: initscript apache2, action "reload" failed.
Leaving server in maintenance mode. Please run occ upgrade manually.

See https://doc.owncloud.org/server/9.0/admin_manual/maintenance/upgrade.html

Illegal instruction
Setting up owncloud (9.0.3-2.1) ...
Processing triggers for libc-bin (2.19-18+deb8u4) ...

[later:]
$ sudo service apache2 reload
Job for apache2.service failed. See 'systemctl status apache2.service' and 'journalctl -xn' for details.
$ systemctl status apache2.service
* apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2)
   Active: failed (Result: exit-code) since Sun 2016-07-03 22:01:33 EDT; 10h ago
$ journalctl -xn
No journal files were found.

I am running owncloud on a Rasbperry Pi running the raspbian operating system:

$ uname -a
Linux raspberrypi 4.1.19+ #858 Tue Mar 15 15:52:03 GMT 2016 armv6l GNU/Linux
$ cat /etc/apt/sources.list.d/owncloud.list 
deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /
$ apache2 -v
Server version: Apache/2.4.10 (Raspbian)
Server built:   Jan 23 2016 22:26:49
$ php5 -v
Illegal instruction
$ mysqld --version
160704  8:18:44 [Warning] Using unique option prefix key_buffer instead of key_buffer_size is deprecated and will be removed in a future release. Please use the full name instead.
mysqld  Ver 5.5.46-0+deb7u1 for debian-linux-gnu on armv7l ((Debian)
$ dpkg -l owncloud | grep owncloud
ii  owncloud       9.0.3-2.1    all          ownCloud - Server
$ sudo -u www-data php occ app:list
$ sudo cat config/config.php 
<?php
$CONFIG = array (
  'instanceid' => '[redacted]',
  'passwordsalt' => '[redacted]',
  'secret' => '[redacted]',
  'trusted_domains' => 
  array (
    0 => '[redacted]',
    1 => '[redacted]',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => '[redacted]',
  'dbtype' => 'mysql',
  'version' => '9.0.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '[redacted]',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
  ),
  'theme' => '',
  'loglevel' => 1,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
  'updatechecker' => false,
);
$ sudo -u www-data php occ config:list system
$ sudo -u www-data php occ ldap:show-config

**Comment by DeepDiver1975** [comment]
@jnweiger THX

**Comment by mach-o** [comment]
Also: Is it possible this is an unrelated problem in php5? (see especially the output of "php5 -v" above)

**Comment by crrodriguez** [comment]
"SIGILL"  (Illegal instruction) is raised when the CPU does not understand an instruction...

Where did you got PHP5 and does it work by itself.. you can try php5 -i

**Comment by crrodriguez** [comment]
So, you got the wrong php5 package for your distribution 's ABI, most likely you ended with a armv7 package instead of an armv6. hence illegal instruction.
This is not an owncloud bug, thanks for your report.
