### ISSUE TITLE
Exception: Updates between multiple major versions and downgrades are unsupported.

### ISSUE THREAD

**Issue by amaranthnet** [owncloud/core#25354]
1. Ubuntu 14.04LTS server, been running OwnCloud for years. Presently at 7.0.4
2. apt-get upgrade said "owncloud" held back.
3. forced the issue with apt-get upgrade owncloud
4. All looked fine until I went to the web page for the Owncloud server, started DB upgrade
5. Blew out with "Exception: Updates between multiple major versions and downgrades are unsupported."

Seems a bit late to be telling me the upgrade isn't supported when I've already installed it with apt-get. Perhaps the package script might have been the place for that information?

Not clear how to properly upgrade this server.

Since I run the Owncloud server under VMware, I rolled back to a version of the server from earlier today, to get back to a functional state.

### Server configuration
**Operating system**: Ubuntu 14.04LTS

**Web server:** Apache (from that distro)

**Database:** MySQL (from the Ubuntu LTS distro)

**PHP version:** (from Ubuntu LTS distro)

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

Update from 7.0.4 to latest (8.2.1?, that's what the admin page on my owncloud server says is current)

**Where did you install ownCloud from:**

repository via apt-get

**Comment by RealRancor** [comment]
Hi,

quoting from the documentation:

> It is best to keep your ownCloud server upgraded regularly, and to install all point releases and major releases without skipping any of them, as skipping releases increases the risk of errors. Major releases are 8.0, 8.1, 8.2, and 9.0. Point releases are intermediate releases for each major release. For example, 8.0.9 and 8.1.3 are point releases. Skipping major releases is not supported.

Further info are available here: https://doc.owncloud.org/server/9.0/admin_manual/maintenance/package_upgrade.html#upgrading-across-skipped-releases

As there is very likely nothing what could be done from package side please close here. If you need further help please ask at either the users mailinglist or the forums (see https://owncloud.org/support).

**Comment by amaranthnet** [comment]
Note that the whole point of having the repository connected in was to avoid this issue and keep it updated.

I disagree that the package installation script could not have compared major versions and refused the installation. If the software, once installed, can know and complain about this, then the package script could too.

**Comment by RealRancor** [comment]
There is no point in having this check doubled. Its already checked within oC and no upgrade is done by oC if a skipped upgrade is detected.

**Comment by amaranthnet** [comment]
Except for the fact that a functional, in-use server can be rendered broken, requiring a restoration from backup, rather than a simple notice that some other work is needed. My suggestion provides advantage to keep functional, production systems from being damaged unnecessarily. That has value. I'm sorry but we may well simply never agree.

**Comment by amaranthnet** [comment]
Oh, and the screen that showed the error EXPLICITLY says to post here. So if this isn't the right place, then perhaps that's an additional bug to be fixed.

**Comment by RealRancor** [comment]
This wrong statement to report it here is already fixed in newer versions: https://github.com/owncloud/core/issues/21367

**Comment by RealRancor** [comment]
Seems oC 9.0.0 has already additional info about this in the exception: https://github.com/owncloud/core/blob/v9.0.0/core/js/update.js#L66

**Comment by amaranthnet** [comment]
Great. Well, since there is apparently no update path (nor useful documentation) on getting from release 7 to 9, nor any on the intermediate steps, I am in the process of building a new server using Ubuntu 16.04LTS, on which I will install 9.x, build all-new user accounts and re-upload everything there. Perhaps once on 9.x, which now has code in the script to deal with this issue, I won't again run into an issue of the install script blowing out a server.

**Comment by RealRancor** [comment]
https://doc.owncloud.org/server/9.0/admin_manual/maintenance/package_upgrade.html#upgrading-across-skipped-releases

already contains intermediate steps / clear instructions how you can upgrade step by step via the packages

**Comment by DeepDiver1975** [comment]
The docs tell perfectly how upgrade should be executed. Im closing this
