### ISSUE TITLE
Improve quota validation including a regexp which matches expected formats

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#25358]
Curently an admin user can enter a number probably followed by letters.
For example: "200", "15MB" or "5 GB" "20B".
Basically it's a number probably followed by letters.

Also floating point can be entered, but only in english style "2.5GB". Using a non english format for floats will lead to an old bug "4,5GB" also something like "45/0". 

So the proposed enhancement by @PVince81 in https://github.com/owncloud/core/pull/25253 is to develop a regexp to validate better this values.

**Comment by PVince81** [comment]
Thanks for the ticket, makes sense

**Comment by andypmw** [comment]
Hi guys, I am create a regex formula for this issue:
`^( +)?([+-])?[\s+]?([0-9]*)(\.([0-9]+))?( +)?(b|kb|mb|gb|tb|pb|eb|zb|yb)?`

I will try to write on PHP and create pull request

**Comment by PVince81** [comment]
@andypmw sounds good, thanks!

**Comment by SergioBertolinSG** [comment]
> I will try to write on PHP and create pull request

I guess this validation should be done in the frontend: settings/js/users/users.js https://github.com/owncloud/core/blob/master/settings/js/users/users.js

**Comment by Kawohl** [comment]
@andypmw Did you make any progress yet?

**Comment by PVince81** [comment]
@ppaysant has added a new JS method for parsing this kind of strings, see https://github.com/owncloud/core/pull/26789

**Comment by SamuAlfageme** [comment]
Think this is a must, since input an invalid quota (e.g. any alphanumeric string) and you'll end up with this funky quota list made with `B`s:

![screen shot 2016-12-14 at 10 34 56](https://cloud.githubusercontent.com/assets/2644445/21176876/fdd84952-c1e8-11e6-9e2b-a7312573e990.png)

Note that the last "`Other`" option has been replaced by another `B`.

**Comment by individual-it** [comment]
reopening as this is not fixed yet  #27257 only fixed the function that could potentially be used for validation but its not implemented in the onQuotaSelect function.
maybe I should not have put in "prerapation to fix #25358" in the header of the PR

**Comment by SergioBertolinSG** [comment]
Tested and works fine. 

But repeated values are added to the dropdown. They vanish when reloading the page. @PVince81 there is an open issue about this bug? I cannot find it.

**Comment by phil-davis** [comment]
The fix here did not allow a 0 byte quota to be entered. See separate issue #29105 and PR #29109

**Comment by phil-davis** [comment]
@SergioBertolinSG  I raised a separate issue #29122 for the repeated values added to the dropdown.
