### ISSUE TITLE
Cannot trust servers with Federation app in oC 9.1 RC1 version

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25362]
### Steps to reproduce

1. Configure two certified oC servers server1 and server2
2. In both servers, modify in /opt/owncloud/config.php the following line
e.g 'overwrite.cli.url' => 'https://server1' and 'https://server2' respectively
3. In admin menu, in Federation section, we write down the url of the other server
4. Back to the CLI, we run the following commands in /opt/owncloud:
```
sudo -u www-data php cron.php (on server1, server2, server1, server2)
sudo -u www-data ./occ dav:sync-system-addressbook (on server1 a server2) 
sudo -u www-data ./occ federation:sync-addressbooks (on server1, server2)
```

### Expected behaviour

After that the address books should be synced and auto complete should work. Trusted server gauge in webUI coloured in green

### Actual behaviour

sudo -u www-data ./occ federation:sync-addressbooks
    1 [->--------------------------]Error while syncing https://docker.oc.solidgear.es:58359 : Unauthorized

Note: It worked fine in oC 9.1.0. pre alpha version
### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:"9.1.0.8","versionstring":"9.1.0 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**

Firefox

**Comment by davitol** [comment]
@schiessle @PVince81

**Comment by PVince81** [comment]
> In both servers, modify in /opt/owncloud/config.php the following line e.g 'overwrite.cli.url' => 'https://urlownserver'

The same CLI URL for both servers ? Sounds fishy.

**Comment by davitol** [comment]
@PVince81 No, the own server url in each one

**Comment by PVince81** [comment]
@davitol yeah, thought so. Never assume that it's obvious for readers and be as explicit as you can in the future :smile:

**Comment by PVince81** [comment]
Hmm, this worked for me:
```
/srv/www/htdocs/owncloudtest # cd ..
/srv/www/htdocs # cd owncloud
/srv/www/htdocs/owncloud # sudo -uwwwrun php cron.php 
/srv/www/htdocs/owncloud # cd ..
/srv/www/htdocs # cd owncloudtest/
/srv/www/htdocs/owncloudtest # sudo -uwwwrun php cron.php 
/srv/www/htdocs/owncloudtest # cd ..
/srv/www/htdocs # cd owncloud
/srv/www/htdocs/owncloud # sudo -uwwwrun php cron.php 
/srv/www/htdocs/owncloud # cd ..
/srv/www/htdocs # cd owncloudtest/
/srv/www/htdocs/owncloudtest # sudo -uwwwrun php cron.php 
/srv/www/htdocs/owncloudtest # cd ..
/srv/www/htdocs # cd owncloud
/srv/www/htdocs/owncloud # sudo -uwwwrun php^C
/srv/www/htdocs/owncloud # sudo -uwwwrun ./occ dav:sync-system-addressbook
Syncing users ...
    1 [============================]
/srv/www/htdocs/owncloud # cd ..
/srv/www/htdocs # cd owncloudtest/
/srv/www/htdocs/owncloudtest # sudo -uwwwrun ./occ dav:sync-system-addressbook
Syncing users ...
    1 [============================]
/srv/www/htdocs/owncloudtest # cd ..
/srv/www/htdocs # cd owncloud
/srv/www/htdocs/owncloud # sudo -uwwwrun ./occ federation:sync-addressbooks 
    1 [============================]
/srv/www/htdocs/owncloud # cd ..
/srv/www/htdocs # cd owncloudtest/
/srv/www/htdocs/owncloudtest # sudo -uwwwrun ./occ federation:sync-addressbooks 
    0 [>---------------------------]
```

I used v9.1.0beta2 from git as server1 and v9.1.0beta2 from tarball as server2.

Will retry with two tarballs, just in case.

**Comment by davitol** [comment]
@PVince81 If you have the chance to test it with v9.1.0.RC1 instead of beta2 and it works, please post it here

**Comment by PVince81** [comment]
Same result with two v9.1.0beta2 tarballs.

@davitol can you reproduce this consistently ?

Will try with RC1.

**Comment by PVince81** [comment]
Ah, also mine was with the community tarballs, not enterprise.

**Comment by PVince81** [comment]
I retried this time with the enterprise tarballs for 9.1.0RC1 but the result is exactly the same, it works.

Note that I used http instead of https (I don't have certified servers)

@davitol the error you saw "Unauthorized" rather looks like the target server denied the request or maybe it had federation disabled or something. I don't think it's related to SSL, it's more like it's getting a 401 permission denied.

If I remember correctly, it uses a token as password so maybe the token became invalid for some reason.

**Comment by davitol** [comment]
```tail -f owncloud.log 
{"reqId":"guVPd87bFgFkDKHSrb1e","remoteAddr":"172.17.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 Unauthorized\",\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\PasswordLoginForbidden\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php(105): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->validateUserPass('system', 'u59T9ksLEwYUMdW...')\\n#1 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(242): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php(146): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(166): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Auth->check(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#7 \\\/opt\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(166): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/opt\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(29): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/opt\\\/owncloud\\\/remote.php(164): require_once('\\\/opt\\\/owncloud\\\/a...')\\n#11 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Auth.php\",\"Line\":132,\"User\":false}","level":4,"time":"2016-07-05T10:39:33+00:00","method":"REPORT","url":"\/remote.php\/dav\/addressbooks\/system\/system\/system","user":"--"}
```
@PVince81 this log can be related to this behaviour

**Comment by PVince81** [comment]
@davitol do you have an env where this happens consistently when repeated ?

**Comment by PVince81** [comment]
@DeepDiver1975 please help, trusted server issue

**Comment by davitol** [comment]
@PVince81 @DeepDiver1975 
```{"reqId":"XOg8BDG\/pqxtCXB1bnmz","remoteAddr":"","app":"dav","message":"Authorization failed, remove address book: https:\/\/docker.xxxxxxxxx9","level":1,"time":"2016-07-13T15:57:01+00:00","method":"--","url":"--","user":"--"}
```
