### ISSUE TITLE
Missing sharing menu bouton icone since upgrade 8.2-->9.0.2

### ISSUE THREAD

**Issue by Gwen22200** [owncloud/core#25386]
I have upgrade my owncloud 8.2 to 9.0.2
The upgrade is ok in manually mode. I can connect every user account, and i found all data.
Nevertheless, all sharing bouton, sharing tab... is missing.
It is impossible to share any files or folders.Every information of sharing disapeared from the web interface.

To find a solution 
I do a fresh install without data of owncloud 9.0.2 with postgres and everything looks fine.
I try to restore data in postgresql and data folder but the problem come...

I think that the probleme seems to come from postgresql or a database paramater with the upgrade.

Do you have any idea ?

ps: Sorry for my poor english, i write english like a spanish cow

### Steps to reproduce
1. Upgrade 8.2 to 9.0.2

### Server configuration
**Operating system**: ubuntu server 14.04

**Web server:** Apache

**Database:** Postgresql 9.3

**PHP version:** 5.5.12

**ownCloud version:** 9.0.2

**List of activated apps:**
  - activity: 2.2.1
  - announcementcenter: true
  - apporder: true
  - comments: 0.2
  - contacts: true
  - dav: 0.1.6
  - documents: true
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - mail: true
  - notifications: 0.2.3
  - ownbackup: true
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
Disabled:
  - encryption
  - files_sharing
  - gallery
  - piwik
  - user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "***********************",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "**********************"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/**************\/owncloud",
        "dbtype": "pgsql",
        "version": "9.0.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "noreply",
        "mail_domain": "***********************",
        "mail_smtphost": "************************",
        "mail_smtpport": "587",
        "mail_smtpdebug": true,
        "mail_smtptimeout": 30,
        "appstore.experimental.enabled": true,
        "mail_smtpauthtype": "LOGIN",
        "maintenance": false,
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 3,
        "logtimezone": "UTC"
    }
}

**Are you using external storage, if yes which one:**
Yes local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser: **
Firefox, chrome
**Operating system:**
W7, Ubuntu

#### Web server error log
Nothing

**Comment by PVince81** [comment]
Please try again with 9.0.5 or 9.1.1 and reopen if the problem persists, and also add owncloud.log.
