### ISSUE TITLE
occ ldap:check-user command does not work using the uid as argument until the user logs-in for the 1st time

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25404]
### Steps to reproduce

1. Configure a LDAP backend
2. In the LDAP wizard, in the expert tab set Internal Username Attribute as uid
3. Run via CLI occ ldap:check-user uid

### Expected behaviour

The availability of the user 

### Actual behaviour

The given user is not a recognized LDAP user

Note: Once the user logs the first time, ldap:check-user command works fine with the uid.
Note2: Using the id of the user, ldap:check-user command works without need of log-in at least once.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:"9.1.0.8","versionstring":"9.1.0 beta 2","edition":"Enterprise"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
 
Firefox

@jvillafanez

**Comment by jvillafanez** [comment]
Works for me. The users must be mapped in the DB though.

**Comment by davitol** [comment]
> The users must be mapped in the DB though.

It is needed as precondition for ldap:check-user command, then let's close this issue. 

Thanks @jvillafanez
