### ISSUE TITLE
.htaccess file content from data misplaced into root after manual upgrade vom 9.0.2.2 to 9.0.3

### ISSUE THREAD

**Issue by juliangieseke** [owncloud/core#25406]
Hello guys,

I'm not exactly sure what happend here, but my OC-Installation was inaccessible after manual upgrading it from 9.0.2 to 9.0.3 - see details below.

 
### Old Config
`ssh@server:/www/htdocs/mydomain/web$ cat config/config.php
<?php
$CONFIG = array (
  …
  'datadirectory' => '/www/htdocs/mydomain/data',
  'overwrite.cli.url' => 'https://mydomain',
  …
  'tempdirectory' => '/www/htdocs/mydomain/tmp',
  …
  'htaccess.RewriteBase' => '/',
  …
);`
=> Maybe helpful: htaccess rewrite doesnt works because mod_env isnt enabled on my shared hosting.

### Steps to reproduce
1. php occ maintenance:mode --on
2. do manual upgrade
3. php occ upgrade

### Expected behaviour
OC should be working with Maintenance-Mode on

### Actual behaviour
.htaccess file-content from data folder is misplaced into .htaccess in root folder…
=> "deny from all" means nothing is accessible…

### Server configuration
**Operating system**:
ubuntu
**Web server:**
apache
**Database:**
mysql
**PHP version:**
PHP 5.5.35-nmm1 (cli) (built: May  3 2016 11:52:52) 
**ownCloud version:** (see ownCloud admin page)
see above
**Updated from an older ownCloud or fresh install:**
update
**Where did you install ownCloud from:**
https://download.owncloud.org/community/owncloud-9.0.3.zip
**Signing status (ownCloud 9.0 and above):**

```
file integrity: .htaccess had wrong hash… (already fixed)
```

**List of activated apps:**
```
Enabled:
  - activity: 2.2.1
  - announcementcenter: 1.1.2
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.5.2
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
see above
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
nope

**Are you using encryption:** yes/no
nope

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
nope

#### Web server error log
```
shared hosting - but no errors were noticed.
```

#### ownCloud log (data/owncloud.log)
```
empty
```

**Comment by DeepDiver1975** [comment]
Can you please post your htaccess?

**Comment by juliangieseke** [comment]
sadly no, had to fix everything asap and forgot to save a copy of the corrupted file :(

it looked like a merged version of /data/.htaccess/ (which is generated by OC?!) and the (also generated) stuff of /.htaccess. As I had some extra code in it (enabled php error log…), I assume OC had some kind of a path-problem.

I also was not able to reproduce it on a second (fresh) install.


it looked like something like this:
```
# Generated by ownCloud on 2016-07-07 07:55:06
# line below if for Apache 2.4
<ifModule mod_authz_core.c>
Require all denied
</ifModule>

# line below if for Apache 2.2
<ifModule !mod_authz_core.c>
deny from all
Satisfy All
</ifModule>

# section for Apache 2.2 and 2.4
IndexIgnore *
#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####

ErrorDocument 403 /core/templates/403.php
ErrorDocument 404 /core/templates/404.php
<IfModule mod_rewrite.c>
  Options -MultiViews
  RewriteRule ^core/js/oc.js$ index.php [PT,E=PATH_INFO:$1]
  RewriteRule ^core/preview.png$ index.php [PT,E=PATH_INFO:$1]
  RewriteCond %{REQUEST_FILENAME} !\.(css|js|svg|gif|png|html|ttf|woff|ico|jpg|jpeg)$
  RewriteCond %{REQUEST_FILENAME} !core/img/favicon.ico$
  RewriteCond %{REQUEST_FILENAME} !/remote.php
  RewriteCond %{REQUEST_FILENAME} !/public.php
  RewriteCond %{REQUEST_FILENAME} !/cron.php
  RewriteCond %{REQUEST_FILENAME} !/core/ajax/update.php
  RewriteCond %{REQUEST_FILENAME} !/status.php
  RewriteCond %{REQUEST_FILENAME} !/ocs/v1.php
  RewriteCond %{REQUEST_FILENAME} !/ocs/v2.php
  RewriteCond %{REQUEST_FILENAME} !/updater/
  RewriteCond %{REQUEST_FILENAME} !/ocs-provider/
  RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge/.*
  RewriteRule . index.php [PT,E=PATH_INFO:$1]
  RewriteBase /
  <IfModule mod_env.c>
    SetEnv front_controller_active true
    <IfModule mod_dir.c>
      DirectorySlash off
    </IfModule>
  </IfModule>
</IfModule>
```

**Comment by DeepDiver1975** [comment]
hmmm .... pretty hard to tell then what the issue was in your case.

Unfortunately I have no idea how to track this down.

I suggest to close this for now - we can reopen this as soon as additional information is available or someone else is facing this issue.

Thanks @juliangieseke

**Comment by juliangieseke** [comment]
totally fine, im also absolutely not sure what happened there…

i assume it is related to that rewrite stuff, i tried to enable "pretty urls" a few weeks ago but it didnt worked… maybe something got f*cked up after that.
