### ISSUE TITLE
Wrong German translation: "authentifizieren"

### ISSUE THREAD

**Issue by cornelinux** [owncloud/core#25412]
There is the translation

"Bitte **authentifizieren** Sie sich mit einem zweiten Faktor. "

(You can grep for this text).
The German text is wrong. It has to be:

"Bitte **authentisieren** Sie sich mit einem zweiten Faktor. "

The German language distinguishes between "Authentifizierung" (what the server does) and "Authentisierung" (what the user does).

https://de.wikipedia.org/wiki/Authentifizierung

**Comment by DeepDiver1975** [comment]
@cornelinux THX for your report. Which version of ownCloud is affected?

**Comment by cornelinux** [comment]
@DeepDiver1975, sorry for not mentioning. I was using 9.1RC. So it is in the master branch within the new 2FA-Framework.

**Comment by DeepDiver1975** [comment]
I just fixed the translation strings on transifex right away. THX
