### ISSUE TITLE
Folders duplicated several times after OC upgrade

### ISSUE THREAD

**Issue by JochenHWezel** [owncloud/core#25415]
after OC upgrade to 9.0.3, I find many folders with copies (interestingly: the copies are also marked as shared as the origin folders are; all the shared folders are shared by another user with me):

![image](https://cloud.githubusercontent.com/assets/14078625/16668637/253032aa-4492-11e6-9d25-52e3dfd2ac09.png)

Please: how to remove these duplicate folders?
- for my user 
- for the many other users using our owncloud instance (I can't go and login for each separate user and do some manual check and cleanup for duplicated shared folders)

**Comment by JochenHWezel** [comment]
Maybe a hint: the more recipient groups defined for a share, the more duplicated folders appear
But: it's not a simple mathematical formula, but maybe he useful hint ;-)
Example: "Bilder & Videos" is shared to 7 different user groups, Datenaustausch (Inbox) is shared again to 7 user groups, another folder "Kasse" appears with just a 2nd copy - and the origin folder "Kasse" is shared with 2 different user groups, again a folder "Technik" is shared with 2 different user groups, but it doesn't appear with an additional folder copy.

After setting a star to the very first "Allgemein" folder and after waiting a few minutes (or reload the page), all copies of the folder have got a star.
Removing the star from the 6th Allgemein folder and putting a start at "Bilder & Videos" folder and reloading the directory, the star disappears for ALL Allgemein folders but appears for all "Bilder & Videos" folders.

**Comment by SergioBertolinSG** [comment]
This seems a duplicated of https://github.com/owncloud/core/issues/24575

**Comment by PVince81** [comment]
Yes, duplicate.
