### ISSUE TITLE
No delete right on shared folder

### ISSUE THREAD

**Issue by AceSlash** [owncloud/core#25445]
### Steps to reproduce
1. Share a folder to someone, give all possible permissions, in my case: "create" and "change"
![sharing_folder](https://cloud.githubusercontent.com/assets/5392990/16739106/ddf3eff8-4798-11e6-9c1a-724dbf132441.png)
2. The user cannot delete any files in the shared folder on the web interface with the message "No permission to delete" when he overs the trash bin icon
![owncloud_delete](https://cloud.githubusercontent.com/assets/5392990/16739119/e8df8eea-4798-11e6-8fdc-0479fa0711ce.png)
3. with the desktop client, deleting a file makes it comes back almost immediately 

### Expected behaviour
The user should be able to delete any files in the shared folder, or a "delete" right should be added when sharing a folder.

### Actual behaviour
The user cannot delete anything and there is no way to give him this right.

### Server configuration
**Operating system**: Debian GNU/Linux 7 (wheezy)

**Web server:** httpd apache 2.2

**Database:** postgresql 9.3.13

**PHP version:** 5.5.37

**ownCloud version:** 8.1.8

**Updated from an older ownCloud or fresh install:** updated several time from Owncloud 6 I think

**Where did you install ownCloud from:** Owncloud Debian official repo: `deb http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.1/Debian_7.0/ /`

**List of activated apps:** 

```
Enabled:
 - activity: 2.0.2
 - files: 1.1.10
 - files_pdfviewer: 0.7.1
 - files_sharing: 0.6.3
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - templateeditor: 0.1
 - user_ldap: 0.6.1.1
Disabled:
 - encryption
 - external
 - files_external
 - files_locking
 - provisioning_api
 - updater
 - user_external
 - user_webdavauth
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => 'box.example.com',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '8.1.8.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost:6001',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'ldapIgnoreNamingRules' => false,
  'log_type' => 'owncloud',
  'logfile' => '/var/log/owncloud/owncloud.log',
  'loglevel' => 2,
  'logdateformat' => 'Y-m-d H:i:s T',
  'logtimezone' => 'Europe/Paris',
  'log_query' => false,
  'log_authfailip' => false,
  'log_rotate_size' => 104857600,
  'default_language' => 'fr',
  'maintenance' => false,
  'theme' => '',
  'mail_from_address' => 'box',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'example.com',
  'enable_previews' => true,
  'preview_libreoffice_path' => '/usr/bin/libreoffice4.3',
  'secret' => '',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '127.0.0.1',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
);
```

**Are you using external storage, if yes which one:** no external storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)

```
I don' think this is relevant...
```

### Client configuration
**Browser:** Chrome, Firefox

**Operating system:** tested on Windows 10, Fedora 24, Windows 7, Ubuntu 16.04

I saw other ticket like #12145 but the user rights on the files are correct. The owner of the share can still delete files.

**Comment by PVince81** [comment]
@AceSlash does it happen for old shares or also for new shares?

**Comment by PVince81** [comment]
@owncloud/sharing

**Comment by AceSlash** [comment]
@PVince81 : you are right, the problem does not happen with a new share: I correctly see all 3 rights: create, change and delete.

Furthermore, I've done more tests and for "old" users that had access to this share since ~ 1 year ago, the UI doesn't show "delete" either but they can delete stuff normally.

I suppose that it worked when the share was created and the old users correctly have all permissions. The "delete" option must have disappeared during an Owncloud update. 

In the meantime, I suppose that I can add the "delete" right to my last users in the database?

**Comment by PVince81** [comment]
Okay, that's useful information.

IIRC you can work it around by running "occ files:scan --all" on the CLI and it should fix the internal permissions. There was a bug in order OC versions where the permissions were not set properly for some reason.

**Comment by AceSlash** [comment]
@PVince81 : I finished the `occ files:scan --all` but it didn't change anything.

However I looked into the database and I saw that the users with the issue had a permission of value `7` in the table `oc_share` for the `file_target` of the bugged share where my working users have a permission of `15`. I updated my bugged users and gave them a permission of `15` and it solved the issue: they can delete files normally now.

**Comment by PVince81** [comment]
@AceSlash it might be because the original sharer removed "can delete". But probably didn't and maybe a bug changed the permissions during migration. No idea.

**Comment by AceSlash** [comment]
@PVince81 well I'm the one who shared the folder and I didn't remove the "can delete" permission :-p

Is it possible to re-add the "delete" permission to the UI using a database update? I looked a bit at the different tables but couldn't find the relevant one.

I'm also thinking about moving up in release channel, either to 8.2 or all the way to 9.0, any idea if this kind of upgrade would fix the UI issue?

**Comment by PVince81** [comment]
Which UI issue are you talking about ? If a share was shared without "can delete" permission, the recipient won't see the "delete" action in the web UI.

So if you think the permissions were wrong in the database for some reason, the sharer should also see that "can delete" is not ticked in the share dialog. If you update the database column, it should then appear as ticked.

**Comment by AceSlash** [comment]
@PVince81 Please look carefully at my first screenshot: I am the owner of the shared folder, but there is no "delete" right that I can add, this what I meant by "the UI issue".

For a new share, I have the "delete" right option that I can add to users. Even when I look at my "old" users that had the correct permission, I don't see a "delete" right, it simply does not appear (but they have it). After I updated the database, the "delete" option is still not here.

**Comment by PVince81** [comment]
Ok, so there are possibly two bugs. The permissions you saw in the "oc_share" table only affects what the recipients see.

However for the original owner of the share, the permissions are not related to shares. The permissions are in "oc_filecache" instead.

**Comment by AceSlash** [comment]
As seen with you on IRC, the shared folder does have a permission of "31" in the database (as it should be) but the web interface still show a permission of "23" for an unknown reason.

As debugging it getting difficult at this point, I'll come back to this ticket when I upgrade to 8.2 or 9.0 to see if the update solves the issue.

**Comment by PVince81** [comment]
Please reopen if you still had this issue with 9.0.5 or 9.1.1, thanks
