### ISSUE TITLE
Notification before an shared Link expires

### ISSUE THREAD

**Issue by xXxOUTLAWxXx** [owncloud/core#25454]
Dear All,

is there any chance to configure notification before an Link expires by email?

I want to upload License Documentaries which has an expiration Date. Before they are expired i would like to get an information.

I didn´t found an Option by myself.

**MySQl**

**PHP7:**

**ownCloud version 9.0.2:** (see ownCloud admin page)

**Comment by PVince81** [comment]
There is currently no way but must be technically possible.
Tagging as enhancement / feature request.

**Comment by PVince81** [comment]
This would likely be a background job and would need to send a user notification when approaching expiration.

**Comment by PVince81** [comment]
@pmaier1 as discussed at some point
