### ISSUE TITLE
Owncloud file management externally

### ISSUE THREAD

**Issue by scion4581** [owncloud/core#25462]
Sorry about question here, but I feel lost with that all owncloud futures, API's and so on.

What we have capabilities to manage file externally? 

For now I create my own external REST app that using web dav calls to upload files, delete files, create folders and so on. I worry about, do I need to use web dav locking/unlocking futures? Or this is server side(owncloud) job?

Secondly, is this only one method to achieve point of this post using web dav or maybe I could create some rest owncloud app that take care of external file operations? But I didnt find any examples except out of the box "files app" :(

Please point me to the right direction, which method to use? (now my rest implementation works pretty well, i am using just one user credentials, but i am worry about locks/unlocks)

Thanks

**Comment by PVince81** [comment]
Please note that this is a bug tracker and not a help platform.

Please send your question to the owncloud-devel mailing list and it will be answered there.

**Comment by PVince81** [comment]
also see https://owncloud.org/support/

**Comment by scion4581** [comment]
sorry, thanks
