### ISSUE TITLE
Сan not delete a group with a slash in the group name

### ISSUE THREAD

**Issue by LbISbIi** [owncloud/core#25465]
Hello.
In ownCloud 9.0.3 (stable) with administrator rights, i can`t delete a group with a slash in the group name.
I created a group called test, and it is removed from the list.
The name of the problematic folder - users\123

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/23499.

You might want to try with this patch https://github.com/owncloud/core/pull/24072
