### ISSUE TITLE
It is possible to create 'app passwords' without name

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25490]
### Steps to reproduce
1. Go to personal page
2. Without writing a app name, create a app password
### Expected behaviour

A warning related no 'app name' was set should appear, and the 'app password' should not ve create
### Actual behaviour

It is possible to create a new 'app password'  without writing an 'app name'
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**
9.1.0.12","versionstring":"9.1.0 RC2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
```
### Client configuration

**browser**

Firefox

![screen shot 2016-07-15 at 14 01 35](https://cloud.githubusercontent.com/assets/10596560/16873842/032c15f2-4a96-11e6-8518-a9c6759d2a64.png)

**Comment by hodyroff** [comment]
What's the problem, if I don't want to name it, I don't name it. This is by design and not a bug. Please reopen if you think otherwise.
