### ISSUE TITLE
API: Regular user with group admin perms cannot alter group memberships

### ISSUE THREAD

**Issue by dercorn** [owncloud/core#25496]
### Steps to reproduce
1. try something like this with a non-admin user with group admin permissions:
```
curl -X POST --user <user>:<password> https://owncloud.server/files82/ocs/v1.php/cloud/users/uiserid/groups/  -d groupid=“testgroup"
```
2. Receive a status code of either 999 or 997

### Expected behaviour
The API call should modify users group memberships.

### Actual behaviour
You receive an error

This was tested on oc 8.2.5 and 9.0.3. This behaviour was consistent on both versions.

[00005763](https://na25.salesforce.com/5003100000cpFgY?srPos=0&srKp=500)

**Comment by cdamken** [comment]
@DeepDiver1975 @PVince81 Any clue why can be modify the memberships?

**Comment by cdamken** [comment]
@tomneedham I remember you created the API, could you tell us what should be expected?

**Comment by PVince81** [comment]
Does changing memberships work in the UI ?

Maybe there's a bug in this API. (note that the UI doesn't use this API)

**Comment by PVince81** [comment]
You need to remove the trailing slash after "groups" to have the correct API call.

Still, it doesn't work on 9.0.4, confirmed.
From what I see in the code it only checks whether the user is an admin, not subadmin.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/25788

**Comment by cdamken** [comment]
Thanks @PVince81 !
