### ISSUE TITLE
New chunking API assembly very slow

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25493]
1. MKCOL "remote.php/dav/uploads/admin//upload1"
1. PUT "remote.php/dav/uploads/admin//upload1/chunk1"
1. PUT "remote.php/dav/uploads/admin//upload1/chunk2"
1. ...
1. MOVE "remote.php/dav/uploads/admin/upload1/.file" "/

The log is full of:
```
{"reqId":"F\/ZNEkFJpvVKHaXmVZ5v","remoteAddr":"127.0.0.1","app":"PHP","message":"rewinddir(): 580 is not a valid Directory resource at \/srv\/www\/htdocs\/owncloud\/3rdparty\/icewind\/streams\/src\/Wrapper.php#31","level":0,"time":"2016-07-15T13:55:03+00:00","method":"MOVE","url":"\/owncloud\/remote.php\/dav\/uploads\/admin\/web-file-upload-6f94f2b4d25d450367941f158bfe4ab1-1468590809462\/.file","user":"admin"}
```

A quick debugging session showed that for every `fread` in the stream copy (every 8k bytes) it will resolve the matching chunk and do a `$node->get()`, which internally does an `fopen` **every time**.

Even worse is that the encryption storage wrapper is applied too which is known to make fopen slow by checking the encryption header.

Some possible solutions:
- cache the resolved nodes
- make sure we have as few storage wrappers as possible applied when reading chunks, ideally none at all

@DeepDiver1975

**Comment by PVince81** [comment]
It takes 40 seconds for the final MOVE of a 120mb, and I have a SSD...

**Comment by DeepDiver1975** [comment]
comparisons in the past between old and new chunking have shown much worse numbers with the old chunking.

What was the chunk size?

**Comment by PVince81** [comment]
The chunk size was 10 MB.

I think the old chunking code has many bypasses that prevent storage wrappers to mess around.
But also, we didn't do a `fopen` of the same file repeatedly for every 8k bytes.

You can test it with https://github.com/owncloud/core/pull/21237, upload a 120mb file in the web UI and observe the network console. (final MOVE)

**Comment by PVince81** [comment]
Two things to optimize:
- [ ] stream_read's `getStream` must cache the resource instead of doing a fopen every 8k bytes
- [ ] prevent storage wrappers to be applied for the "dav/uploads/*" (or matching internal) paths

**Comment by PVince81** [comment]
- [ ] also "getNodeForPosition" is called for every 8k byte, could also be slow in the long run.
Maybe we should change the algo to simply keep reading the current node until it runs out and only then call `getNodeForPosition` again

**Comment by PVince81** [comment]
also am thinking that here is a good opportunity to have checksums of some sorts, just to make sure that no bugs are causing broken files to be written...

**Comment by PVince81** [comment]
PR to fix AssemblyStream: https://github.com/owncloud/core/pull/26062

Next up: take care of the unneeded storage wrappers

**Comment by PVince81** [comment]
I'm setting this to 9.1.2 since we had the new DAV endpoint and might want to backport

**Comment by guruz** [comment]
I'm all for making checksums mandatory with this new API.

We're looking into doing the same for the batching/bundling API. https://github.com/owncloud/client/pull/5155#issuecomment-245230297

**Comment by PVince81** [comment]
fixed
