### ISSUE TITLE
A log appears in owncloud.log file when we share a file with a never logged user in an encrypted oC server

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25515]
### Steps to reproduce
1. Enable LDAP app
2. Configure a LDAP users backend
3. Enable encryption  app and encrypt the oC server
4. With admin user create a file and share it with a never logged before LDAP user
### Expected behaviour

No log should be shown and the file should be shared
### Actual behaviour

A log is written in owncloud.log
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**
9.1.0.12","versionstring":"9.1.0 RC2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"cXOnXzokxlILsg+GvFQu","remoteAddr":"82.159.139.58","app":"no app in context","message":"Could not encrypt file for aaliyah_armstrong: Public Key missing for user: aaliyah_armstrong","level":2,"time":"2016-07-18T11:25:47+00:00","method":"POST","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json","user":"admin"}
```
### Client configuration

**browser**

Firefox

**Comment by PVince81** [comment]
Not technically possible to share with user if the user has not created a key pair by logging in as that user's password is required.

Best is to use master key for such use cases, closing.
