### ISSUE TITLE
A log is shown in owncloud.log when sharing a file with an LDAP user

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25514]
### Steps to reproduce
1. Enable LDAP app
2. Configure a LDAP users backend
3. With admin user create a file and share it with an LDAP user
### Expected behaviour

No log should be shown and the file should be shared
### Actual behaviour

A log is written in owncloud.log
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**
9.1.0.12","versionstring":"9.1.0 RC2","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"NlkA9pNwmBHpwKW2X42n","remoteAddr":"82.159.139.58","app":"PHP","message":"usort(): Array was modified by the user comparison function at \/opt\/owncloud\/lib\/private\/User\/Manager.php#255","level":3,"time":"2016-07-18T11:39:20+00:00","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=aaliy&perPage=200&itemType=file","user":"admin"}
```
### Client configuration

**browser**

Firefox

@jvillafanez

**Comment by PVince81** [comment]
Please reopen in [user_ldap app repo](https://github.com/owncloud/user_ldap) if issue persists with 10.0.4 and the latest user_ldap app from marketplace.
