### ISSUE TITLE
No feedback when changing passwords as administrator

### ISSUE THREAD

**Issue by tfrdidi** [owncloud/core#25532]
### Steps to reproduce
1. Go to `<owncloudBaseUri>/settings/users`
2. Change password of a user
3. Press Enter

### Expected behaviour
I would expect some feedback if it worked or not.

### Actual behaviour
No feedback shown.

### Server configuration
**Operating system**: CentOS Linux release 7.2.1511 (Core)

**Web server**: Apache/2.4.6 (CentOS)

**Database:** MariaDB

**PHP version:** PHP 5.5.37

**ownCloud version:** 9.0.3 (stable)

**Updated from an older ownCloud or fresh install:** upgrade from 9.0.1 (stable)

**Where did you install ownCloud from:** yum

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - documents: 0.12.0
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_antivirus: 0.8.0.2
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - passwordpolicy: 1.1
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - external
  - federation
  - user_external
  - user_ldap

**The content of config/config.php:**

<?php
$CONFIG = array (
  'default_language' => 'de',
  'updatechecker' => false,
  'instanceid' => '...',
  'passwordsalt' => '...',
  'secret' => '...',
  'trusted_domains' =>
  array (
    0 => '...',
    1 => '...',
  ),
  'datadirectory' => '/srv/owncloud-data/',
  'overwrite.cli.url' => '...',
  'dbtype' => 'mysql',
  'version' => '9.0.3.2',
  'dbname' => '...',
  'dbhost' => '...',
  'dbtableprefix' => '...',
  'dbuser' => '...',
  'dbpassword' => '...',
  'logtimezone' => 'Europe/Berlin',
  'installed' => true,
  'mail_from_address' => 'hostmaster',
  'mail_smtpmode' => 'php',
  'mail_domain' => '...',
  'singleuser' => false,
  'appstore.experimental.enabled' => true,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\MP3',
    6 => 'OC\\Preview\\TXT',
    7 => 'OC\\Preview\\MarkDown',
    8 => 'OC\\Preview\\PDF',
  ),
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'htaccess.RewriteBase' => '/owncloud',
  'theme' => '...',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
);
?>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome/FF/IE

**Operating system:**
Win 10

**Comment by PVince81** [comment]
At least a yellow notification would be nice: `OC.Notification.showTemporary(...)`

Tagging as junior job

**Comment by kavishdahekar** [comment]
I have identified the solution for the above issue. Should I go ahead and create a pull request?
```
if (result.status != 'success') {
	OC.Notification.showTemporary(t('admin', result.data.message));
}else{
	// shows message indicating success
	OC.Notification.showTemporary(t('admin', "Password changed successfully!"));
}
```

**Comment by tfrdidi** [comment]
Looks good to me. But I suggest to use the i18n-version of "Password changed successfully!" to allow the translation of this string.

**Comment by JackWillDavis** [comment]
I have an active pull request with this fix. I would suggest not having the != success in the IF statement. If something goes wrong, we don't want to default back to displaying a success message in the ELSE.

See: https://github.com/JackWillDavis/core/pull/1

**Comment by PVince81** [comment]
@JackWillDavis you need to send the pull request back to the fork. That PR is pointing to your own fork as target.

**Comment by JackWillDavis** [comment]
@PVince81 ahh you're right, I'm still getting used to contributions to open source on here. I will sort this out shortly.

**Comment by JackWillDavis** [comment]
@PVince81 I've just set up a PR with the correct target this time! Let me know if there is anything more I can do to this.

https://github.com/owncloud/core/pull/25753

**Comment by JackWillDavis** [comment]
New PR: https://github.com/owncloud/core/pull/25756

**Comment by DeepDiver1975** [comment]
thanks @JackWillDavis - great job

**Comment by JackWillDavis** [comment]
Thanks very much!
