### ISSUE TITLE
after upgrade to 9.0.4 again not passed the integrity check.

### ISSUE THREAD

**Issue by CHazz** [owncloud/core#25544]
it's frustrating that there is no way to upgrade without errors ..

I tried to replace files .. and still error (The solution is to upload the correct), why file is correct ? new old not working notthing working ..

it is very difficult to make a statement to recreating signature.json or automatic download correct files?

thank you for help 
- INVALID_HASH:
  - 3rdparty/guzzlehttp/guzzle/src/Client.php:
    - expected: 34b6d5b6bf056c25c4986eef62b44dd5a8508affc120234394df55c6b9580312d19498b78398c78b55884b393f51c6997deff5c8bfd6578585c7a1fde8d9d604
    - current: e0f216ffc761d8a00d920e2eca953634661be6eac3d97fa302a9f2b6ec7385c3ede8c266a716aa98bed051db8d65f432514eb7ebce4250dc26fd697135b29f59
  - 3rdparty/patches.txt:
    - expected: c9c980044146368b809b774e171a2f08345c75a7c622f3153d3c2881ee06dcd9abbe3e342f3ea36b2e8e85c2f77610286de1576c60d14c3532b6ec2fca1a1e1e
    - current: 71583637c38ab528bd6e1552c01b933bc08f83a5c5af2bd335bca971266360aa73bbaa1edfc7e50bdd061d26444e3000ccc500883e2877305e2dcee792f0c462
# Results
- core
  - INVALID_HASH
    - 3rdparty/guzzlehttp/guzzle/src/Client.php
    - 3rdparty/patches.txt
# Raw output

Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [3rdparty/guzzlehttp/guzzle/src/Client.php] => Array
                        (
                            [expected] => 34b6d5b6bf056c25c4986eef62b44dd5a8508affc120234394df55c6b9580312d19498b78398c78b55884b393f51c6997deff5c8bfd6578585c7a1fde8d9d604
                            [current] => e0f216ffc761d8a00d920e2eca953634661be6eac3d97fa302a9f2b6ec7385c3ede8c266a716aa98bed051db8d65f432514eb7ebce4250dc26fd697135b29f59
                        )

```
                [3rdparty/patches.txt] => Array
                    (
                        [expected] => c9c980044146368b809b774e171a2f08345c75a7c622f3153d3c2881ee06dcd9abbe3e342f3ea36b2e8e85c2f77610286de1576c60d14c3532b6ec2fca1a1e1e
                        [current] => 71583637c38ab528bd6e1552c01b933bc08f83a5c5af2bd335bca971266360aa73bbaa1edfc7e50bdd061d26444e3000ccc500883e2877305e2dcee792f0c462
                    )

            )

    )
```

)

**Comment by abpostelnicu** [comment]
same problem here:

Results
=======
- core
	- INVALID_HASH
		- 3rdparty/guzzlehttp/guzzle/src/Client.php
		- 3rdparty/patches.txt

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [3rdparty/guzzlehttp/guzzle/src/Client.php] => Array
                        (
                            [expected] => 34b6d5b6bf056c25c4986eef62b44dd5a8508affc120234394df55c6b9580312d19498b78398c78b55884b393f51c6997deff5c8bfd6578585c7a1fde8d9d604
                            [current] => def9cb679ae55b41a425a57ecb49bd010d948f47f5436e9c619e20fd1185fd9e9a21cc46d43c214bab69f70df771058b85c27f304bafddd54421e1aba3485fb3
                        )

                    [3rdparty/patches.txt] => Array
                        (
                            [expected] => c9c980044146368b809b774e171a2f08345c75a7c622f3153d3c2881ee06dcd9abbe3e342f3ea36b2e8e85c2f77610286de1576c60d14c3532b6ec2fca1a1e1e
                            [current] => 4e5c76601cd13c1122641fd50e47d81abdd5abe75390ab9d1cbb70e59f5d9f88e1c76dafebee17b62a1bccb0fa70b319b76511a3670cdec6398a6a1204026db2
                        )

                )

        )

)

**Comment by RealRancor** [comment]
@CHazz Instead of complaining please provide the info (as asked in the shown issue template when creating a new issue) how you did the update. This helps a lot more to know why you're facing this issue.

**Comment by abpostelnicu** [comment]
I've updated using the automatic procedure, through the web interface.

**Comment by PVince81** [comment]
Please also state from which version you were upgrading.

Upgrades with auto-updater was tested for all 9.0.x versions to 9.0.4 and there was no such issue. So would be good to find out what part of your setup might be causing it.

I just redid a test updating from 9.0.3 tarball to 9.0.4 using the auto-updater. There are no integrity check issues after that.

**Comment by PVince81** [comment]
Note: this patch was added between 9.0.4 RC1 and 9.0.4 final, could be a clue.

**Comment by abpostelnicu** [comment]
If i'm not mistaking i've been updating from the previous version 9.0.3 or 9.0.2

**Comment by PVince81** [comment]
@abpostelnicu you might be able to find out by reading owncloud.log, I think it adds a line like "updating from version XX to YY"

**Comment by abpostelnicu** [comment]
This is it:
"starting upgrade from 9.0.2.2 to 9.0.4.1","level":0

**Comment by abpostelnicu** [comment]
maybe this helps as well, after this update i get the following php errors:

Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0

**Comment by tyepez** [comment]
Tengo el mismo problema.

**Comment by RealRancor** [comment]
@tyepez If you are affected by the same issue and can't add additional info it is enough to use the "thumbs up" button at the first post. This avoids that the issue gets flooded with comments not providing additional info.

**Comment by tyepez** [comment]
Hi friends,
Please help me with the files: 3rdparty/guzzlehttp/guzzle/src/Client.php, 3rdparty/patches.txt, with the correct hash.

[3rdparty/guzzlehttp/guzzle/src/Client.php] => 34b6d5b6bf056c25c4986eef62b44dd5a8508affc120234394df55c6b9580312d19498b78398c78b55884b393f51c6997deff5c8bfd6578585c7a1fde8d9d604
[3rdparty/patches.txt] => c9c980044146368b809b774e171a2f08345c75a7c622f3153d3c2881ee06dcd9abbe3e342f3ea36b2e8e85c2f77610286de1576c60d14c3532b6ec2fca1a1e1e

Results
=======
- core
	- INVALID_HASH
		- 3rdparty/guzzlehttp/guzzle/src/Client.php
		- 3rdparty/patches.txt

Raw output

[core] => Array

[INVALID_HASH] => Array

[3rdparty/guzzlehttp/guzzle/src/Client.php] => Array
[expected] => 34b6d5b6bf056c25c4986eef62b44dd5a8508affc120234394df55c6b9580312d19498b78398c78b55884b393f51c6997deff5c8bfd6578585c7a1fde8d9d604
[current] => def9cb679ae55b41a425a57ecb49bd010d948f47f5436e9c619e20fd1185fd9e9a21cc46d43c214bab69f70df771058b85c27f304bafddd54421e1aba3485fb3

[3rdparty/patches.txt] => Array
[expected] => c9c980044146368b809b774e171a2f08345c75a7c622f3153d3c2881ee06dcd9abbe3e342f3ea36b2e8e85c2f77610286de1576c60d14c3532b6ec2fca1a1e1e
[current] => 4e5c76601cd13c1122641fd50e47d81abdd5abe75390ab9d1cbb70e59f5d9f88e1c76dafebee17b62a1bccb0fa70b319b76511a3670cdec6398a6a1204026db2

**Comment by PVince81** [comment]
@tyepez you should be able to get the correct source files from the 9.0.4 tarball. It also contains the matching signature json files

**Comment by tyepez** [comment]
@PVince81 thanks, It works great! I downloades new files form source.

**Comment by sushidave** [comment]
Exactly the same error here after upgrading from 9.0.1.3 to 9.0.4.1 by the Updater App. The issue persists after replacing Client.php and patches.txt from the source files.

**Comment by PVince81** [comment]
@sushidave can you post the full error with hashes ? Did you mean they are exactly the same as before ? Did you try clicking "Rescan" ?

**Comment by sushidave** [comment]
@PVince81 It was the same error with the same hashes as shown above. But meanwhile the error does not appear in our installations anymore.

**Comment by Iskenof** [comment]
i have the same problem

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- 3rdparty/guzzlehttp/guzzle/src/Client.php
		- 3rdparty/patches.txt

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [3rdparty/guzzlehttp/guzzle/src/Client.php] => Array
                        (
                            [expected] => 34b6d5b6bf056c25c4986eef62b44dd5a8508affc120234394df55c6b9580312d19498b78398c78b55884b393f51c6997deff5c8bfd6578585c7a1fde8d9d604
                            [current] => def9cb679ae55b41a425a57ecb49bd010d948f47f5436e9c619e20fd1185fd9e9a21cc46d43c214bab69f70df771058b85c27f304bafddd54421e1aba3485fb3
                        )

                    [3rdparty/patches.txt] => Array
                        (
                            [expected] => c9c980044146368b809b774e171a2f08345c75a7c622f3153d3c2881ee06dcd9abbe3e342f3ea36b2e8e85c2f77610286de1576c60d14c3532b6ec2fca1a1e1e
                            [current] => 4e5c76601cd13c1122641fd50e47d81abdd5abe75390ab9d1cbb70e59f5d9f88e1c76dafebee17b62a1bccb0fa70b319b76511a3670cdec6398a6a1204026db2
                        )

                )

        )

)

after rescan is the same hash error code

**Comment by foliz** [comment]
Hi, same here:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- 3rdparty/guzzlehttp/guzzle/src/Client.php
		- 3rdparty/patches.txt

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [3rdparty/guzzlehttp/guzzle/src/Client.php] => Array
                        (
                            [expected] => 34b6d5b6bf056c25c4986eef62b44dd5a8508affc120234394df55c6b9580312d19498b78398c78b55884b393f51c6997deff5c8bfd6578585c7a1fde8d9d604
                            [current] => def9cb679ae55b41a425a57ecb49bd010d948f47f5436e9c619e20fd1185fd9e9a21cc46d43c214bab69f70df771058b85c27f304bafddd54421e1aba3485fb3
                        )

                    [3rdparty/patches.txt] => Array
                        (
                            [expected] => c9c980044146368b809b774e171a2f08345c75a7c622f3153d3c2881ee06dcd9abbe3e342f3ea36b2e8e85c2f77610286de1576c60d14c3532b6ec2fca1a1e1e
                            [current] => 4e5c76601cd13c1122641fd50e47d81abdd5abe75390ab9d1cbb70e59f5d9f88e1c76dafebee17b62a1bccb0fa70b319b76511a3670cdec6398a6a1204026db2
                        )

                )

        )

)
```

**Comment by renezw** [comment]
Hi, same here after updating from 9.0.1.3 to 9.0.4:

[failed.txt](https://github.com/owncloud/core/files/468962/failed.txt)

**Comment by PVince81** [comment]
I tried the following:

1. Extract 9.0.1 from the tarball from https://download.owncloud.org/community//owncloud-9.0.1.tar.bz2
1. Make sure the whole folder is accessible for the web server user (I did `chown -R wwwrun:www owncloud`)
1. Setup OC with MySQL/MariaDB
1. Go to admin page
1. If the update doesn't appear yet, force a refresh by running `delete from oc_appconfig where configkey='lastupdatedat';` in the database
1. Open updater
1. Update to 9.0.4 (stable channel)
1. Click "Start", wait for update
1. Refresh the page
1. Go to admin page

Hmmm, now I'm seeing these too.

@VicDeo

**Comment by PVince81** [comment]
When installing 9.0.4 from scratch there is no error.

@VicDeo from what I see the 3rdparty folder hasn't been properly updated from the new tarball.
To see it, run the steps from https://github.com/owncloud/core/issues/25544#issuecomment-246608035.
Then deploy another 9.0.4 in a separate folder.
Diff both folders, you'll see that apart from config.php and .htaccess differences, the files mentionned in the integrity check haven't been updated.

**Comment by PVince81** [comment]
To all here, you can fix your installation as follows:

1. Delete / move away the "3rdparty" folder
1. Download the https://download.owncloud.org/community//owncloud-9.0.4.tar.bz2 tarball
1. Copy the "3rdparty" folder from the tarball into your ownCloud folder
1. Go to admin page
1. Click "Rescan" in the integrity check warning

**Comment by PVince81** [comment]
I suspect that the 3rdparty bug was a bug in the updater bundled with older OC 9.0.x versions. @VicDeo we might need a post-repair action that fixes the 3rdparty folder in case we came from an older version.

**Comment by VicDeo** [comment]
@PVince81 May be it's better trigger an integrity check in the postrepair step and fix files that have different hashes as it is suggested above?

**Comment by VicDeo** [comment]
@PVince81 migration to 9.0.5 will solve this issue automatically. Only 9.0.0 and 9.0.1 has incorrect handling of 3rdparty libraries.
In a long run we need consider implementation of integrity repair in addition to integrity check.

**Comment by PVince81** [comment]
Indeed. Question is whether 9.0.1->9.0.5 will fail too? If yes then we might want to force the update path through 9.0.4 in the update server.

@VicDeo can you test these paths?

**Comment by VicDeo** [comment]
@PVince81  I thought that a plan was always update to 9.0.4 first
https://github.com/owncloud/administration-internal/pull/32

**Comment by PVince81** [comment]
@VicDeo no, the original plan was to force update through 9.0.3, but then 9.0.3 was broken too. Then we released 9.0.4 which looked fine initially so we removed the restriction.

@VicDeo now if you say that the upgrade path 9.0.1->9.0.4->9.0.5 works fine (with 9.0.4 having the error from here), then let's adjust the update server to always go through 9.0.4.

**Comment by PVince81** [comment]
I was only able to reproduce this issue by upgrading from 9.0.1 straight to 9.0.4.
9.0.2 to 9.0.4 seems fine.

**Comment by PVince81** [comment]
I did local test upgrading 9.0.1->9.0.4->9.0.5RC2 and the integrity check warnings are gone, the 3rdparty folder is updated properly.

Let's leave this ticket open until the update server is delivering 9.0.5.

**Comment by PVince81** [comment]
9.0.5 is now delivered in the update server, closing
