### ISSUE TITLE
[OC 9.1.0] Incorrect version tag

### ISSUE THREAD

**Issue by vwxyutarooo** [owncloud/core#25545]
I've trying to update 9.1.0RC2 to 9.1.0, then following message appeared.

```
Downgrading is not supported and is likely to cause unpredictable issues (from 9.1.0.12 to 9.0.4.1)
Downgrading is not supported and is likely to cause unpredictable issues (from 9.1.0.12 to 9.0.4.1)
```

Because `v9.1.0` tagged to wrong commit.
- [6f4931a](https://github.com/owncloud/core/commit/6f4931a085bcd26346bdfdf7c5a6f832df78d473)
- [v9.1.0](https://github.com/owncloud/core/releases/tag/v9.1.0)

```
+$OC_Version = array(9, 0, 4, 1);
+$OC_VersionString = '9.0.4';
```

**Comment by DeepDiver1975** [comment]
@danimo

**Comment by PVince81** [comment]
Huh? What happened ? I verified the tag yesterday and it looked good.

**Comment by PVince81** [comment]
@danimo is on it

**Comment by danimo** [comment]
Fixed. Please verify with git pull --tags.

**Comment by PVince81** [comment]
Just checked, the tag is correct now

**Comment by vwxyutarooo** [comment]
It's fixed! Thanks guys.
