### ISSUE TITLE
Can't share with link a SMB mounted folder

### ISSUE THREAD

**Issue by SpecBlackHat** [owncloud/core#25540]
### Steps to reproduce
1. Mount any folder by SMB
2. Try to share it with link
3. Get an error - Resharing is not allowed

### Expected behaviour
User must able to share folders with links.
It works on 8.3 version.

### Actual behaviour
On 9.0.3 i can't share smb mounted folders with link

### Server configuration
**Operating system**: FreeBSD 10.3

**Web server:** Apache24

**Database:** MySQL56

**PHP version:** 56

**ownCloud version:** (see ownCloud admin page) 9.0.3

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** From ports

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**List of activated apps:**
Activity  2.2.1
Collaborative tags  0.2
Comments  0.2
Default encryption module  1.2.0
Deleted files  0.8.0
External storage support  0.5.2
Federation  0.0.4
First Run Wizard  1.1
Gallery  14.5.0
Mail Template Editor  0.1
Notifications  0.2.3
PDF Viewer  0.8.1
Provisioning API  0.4.1
Share Files  0.9.1
Text Editor  2.1
Update notification  0.1.0
Versions  1.2.0
Video player  0.9.8
Contacts  1.3.1.0
Music  0.3.11

**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** yes

### Client configuration
**Browser:** Chrome 51.0.2704.103 m

**Operating system:** Windows Pro x86

**Comment by RealRancor** [comment]
@SpecBlackHat Probably one of those:

> New option for the ownCloud admin to enable or disable sharing on individual external mountpoints (see Mount Options). Sharing on such mountpoints is disabled by default.

from https://doc.owncloud.org/server/9.0/admin_manual/release_notes.html#changes-in-9-0

or

> The drawbacks are that sharing is disabled when this mechanism is in use, as ownCloud has no access to the storage credentials, and background file scanning does not work.

from https://doc.owncloud.org/server/9.0/admin_manual/configuration_files/external_storage/auth_mechanisms.html#password-based-mechanisms

**Comment by SpecBlackHat** [comment]
The first is right.
Thanks!!!
