### ISSUE TITLE
cannot increase permissions

### ISSUE THREAD

**Issue by thedudede** [owncloud/core#25542]
When I try to change permissions I get the following error-message: (sorry partialy german)

"Fehler beim Teilen
Cannot increase permissions"

In english it should be "error sharing..."

The strange thing is: when I decrease the permissions it works fine. But increasing it afterwards leads to the error.
When I completly remove the permission and grant it again, the user has full access again.

ownCloud 9.0.3 (stable) running under ubuntu 16

Update:
I have just updated to 9.0.4-1.1
but still the same issue

**Comment by PVince81** [comment]
Can you give more information on your sharing situation ? Who shares what with whom with what permissions ? Also include the reshares if there are any.

And then, who is trying to change the permissions to cause this error ?

**Comment by thedudede** [comment]
it's a "fresh" system.
only 2 users and one group so far
The admin-user shares with a group.

But let me try, if sharing with the user leads to the same problem.
well that's strange... sharing with the user works normally...

next trial: 
I will login with the user and share with the group.
the same behaviour.. 
(sharing with user works normally, but increasing the access-rights for the group fails)

**Comment by marciofoz** [comment]
Hi, I use OC 9.1 and have the same problem.
To reproduce:
The user (the group admin) create the folder with all permissions and share the folder with the same group. Then the same user remove all permissions and try select any permission again.  Then I see the message "Cannot increase permissions".

**Comment by PVince81** [comment]
My steps:

1. Install OC v9.1.0
1. Create a user "subadmin"
1. Add "subadmin" to group "group1"
1. Make "subadmin" a subadmin of group "group1"
1. Login as "subadmin"
1. Create a user "user1" in group "group1"
1. Create a folder "test"
1. Share "test" with "group1" with all permissions
1. Remove permissions
1. Re-add permissions

Expected: can readd permissions
Actual: "Cannot increase permissions"

Ouch. => regression

**Comment by PVince81** [comment]
Quick workaround is to unshare from "group1" then share again.

**Comment by PVince81** [comment]
Okay, I think I see what the problem is: since the user who shares is also in the receiving group, the logic that checks the max allowed permissions is confused. But really, it should ignore the permissions since the user is the owner of the share.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/25966
