### ISSUE TITLE
Error: Class 'OCA\\Files_Sharing\\API\\Server2Server and apps folder empty after upgrading to 9.0.4.1 

### ISSUE THREAD

**Issue by fabricedev** [owncloud/core#25546]
### Steps to reproduce
1. Running system with version 9.0.3.2.

### Expected behaviour
Everything works fine after upgrade

### Actual behaviour
Fatal error "Error: Class 'OCA\\Files_Sharing\\API\\Server2Server"

### Server configuration
**Operating system**:
Distributor ID: Debian
Description:    Debian GNU/Linux 8.5 (jessie)
Release:        8.5
Codename:       jessie

**Web server:**
Server version: Apache/2.4.10 (Debian)
Server built:   Jul 20 2016 06:48:18

**Database:**
mysql  Ver 15.1 Distrib 10.1.16-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP 7.0.8-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-1~dotdeb+8.1, Copyright (c) 1999-2016, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
9.0.3.2.

**Updated from an older ownCloud or fresh install:**
Fresh

**Where did you install ownCloud from:**
tar from oc website

**List of activated apps:**

Aaaarggg !! The apps folder is totally empty NOW !!!

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Too late !!

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
{
    "system": {
        "instanceid": "oc0kar51fbge",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.xxxx.fr"
        ],
        "datadirectory": "\/chome\/webdat\/ocdat",
        "overwrite.cli.url": "https:\/\/www.xxxx.fr\/cloud",
        "dbtype": "mysql",
        "version": "9.0.4.1",
        "dbname": "OC9",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "127.0.0.1",
            "port": 6379
        },
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

Here is my update log
[info] Execution of upgrade:detect command started
[info] ownCloud 9.0.3.2 found
[info] Execution of upgrade:detect command stopped. Exit code is 0
[info] Execution of upgrade:checkSystem command started
[info] Execution of upgrade:checkSystem command stopped. Exit code is 0
[info] Execution of upgrade:checkpoint command started
[info] Execution of upgrade:checkpoint command stopped. Exit code is 0
[info] Execution of upgrade:detect command started
[info] ownCloud 9.0.3.2 found
[info] Execution of upgrade:detect command stopped. Exit code is 0
[info] Execution of upgrade:disableNotShippedApps command started
[info] Execution of upgrade:disableNotShippedApps command stopped. Exit code is 0
[info] Execution of upgrade:executeCoreUpgradeScripts command started
[debug] Replacing 3rdparty
[debug] Replacing config
[debug] Replacing core
[debug] Replacing l10n
[debug] Replacing lib
[debug] Replacing ocs
[debug] Replacing ocs-provider
[debug] Replacing resources
[debug] Replacing settings
[debug] Replacing .htaccess
[debug] Replacing .mailmap
[debug] Replacing .tag
[debug] Replacing .user.ini
[debug] Replacing AUTHORS
[debug] Replacing console.php
[debug] Replacing COPYING-AGPL
[debug] Replacing cron.php
[debug] Replacing db_structure.xml
[debug] Replacing index.html
[debug] Replacing index.php
[debug] Replacing indie.json
[debug] Replacing occ
[debug] Replacing public.php
[debug] Replacing remote.php
[debug] Replacing robots.txt
[debug] Replacing status.php
[debug] Replacing version.php
[info] Execution of upgrade:executeCoreUpgradeScripts command stopped. Exit code is 0
[info] Execution of upgrade:start command started
[info] Execution of upgrade:info command started
[info] Execution of upgrade:info command stopped. Exit code is 0
[info] Execution of upgrade:checkSystem command started
[info] Execution of upgrade:checkSystem command stopped. Exit code is 0

My ownloud log : 
{"reqId":"PFonsgCCyBwg+dHQKc9X","remoteAddr":"x.x.x.x","app":"PHP","message":"Error: Class 'OCA\\Files_Sharing\\API\\Server2Server' not found at \/chome\/web\/oc\/owncloud\/ocs\/routes.php#102","level":3,"time":"2016-07-21T08:24:43+00:00","method":"GET","url":"\/cloud\/","user":"--"}
{"reqId":"t79ZesLYRmANLzvsUIed","remoteAddr":"x.x.x.x","app":"PHP","message":"Error: Class 'OCA\\Files_Sharing\\API\\Server2Server' not found at \/chome\/web\/oc\/owncloud\/ocs\/routes.php#102","level":3,"time":"2016-07-21T08:24:44+00:00","method":"GET","url":"\/cloud\/","user":"--"}
r

**Comment by PVince81** [comment]
Okay, so you have two issues ? Empty apps folder and this error above ?

@VicDeo can you have a look at this log ?

**Comment by PVince81** [comment]
@fabricedev as a workaround for you to recover, download the 9.0.4 tarball: http://download.owncloud.org/community/owncloud-9.0.4.tar.bz2 and use the source code from there

**Comment by fabricedev** [comment]
Thanks, but as a workaround, I just going to use a fresh install of the new 9.1.0 :-)

My purpose was more to inform you on a deadly update for you to find what was wrong than resurect my old installation.

**Comment by VicDeo** [comment]
The same issue, a missing class belongs to the missing files_sharing app. Take apps and updater from 9.0.4 than check core integrity That's itSent from my Huawei Mobile-------- Исходное сообщение --------Тема: Re: [owncloud/core] Error: Class 'OCA\\Files_Sharing\\API\\Server2Server and apps folder empty after upgrading to 9.0.4.1 (#25546)От: Vincent Petry Кому: owncloud/core Копия: VicDeo ,Mention Okay, so you have two issues ? Empty apps folder and this error above ?

@VicDeo can you have a look at this log ?

**Comment by PVince81** [comment]
Closing due to lack of feedback
