### ISSUE TITLE
oc_properties must use fileid instead of path

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25563]
The oc_properties table contains any custom Webdav properties that might have been set by third party clients.

The trouble is that this table contains the full path to the target file and doesn't properly detect renames... so properties can get lost.
Furthermore, the column is too small and longer paths might not fit.

To be able to better preserve properties, we should make this table use the fileid instead of the path.

@DeepDiver1975

**Comment by PVince81** [comment]
The code in question is here: https://github.com/owncloud/core/blob/master/apps/dav/lib/Files/CustomPropertiesBackend.php

The tricky part is migrating from the old structure to the new one, basically trying to identify the files by path to find their ids. I suspect that in many envs entries are orphaned already, so need to clean those up.

- [ ] use fileid instead of path in https://github.com/owncloud/core/blob/master/apps/dav/lib/Files/CustomPropertiesBackend.php
- [ ] migrate existing paths to the fileid
- [ ] delete entries that cannot be resolved at migration time (show warning?)

**Comment by VicDeo** [comment]
@PVince81 should I keep old fields in DB for migration or populate existing entries into the new table before migration?

**Comment by PVince81** [comment]
Is it cheaper to create a new table than migrating the existing table and deleting the column ?

I'd say that we migrate the data to the new structure and delete the old structure once we're done. No deprecation.

Note that in 10.0 we have Doctrine migrations, so you could/should use that instead of repair steps when doing the migration.

CC @DeepDiver1975 @butonic

**Comment by VicDeo** [comment]
@PVince81 >in 10.0 we have Doctrine migrations
it is still under development, isn't it?

**Comment by PVince81** [comment]
No, it already works. But core doesn't have a single migration checked in yet.
I've used it in the customgroups app for database initialization: https://github.com/owncloud/customgroups/tree/master/appinfo/Migrations

**Comment by VicDeo** [comment]
@PVince81 @DeepDiver1975 any reason why we have `oc_properties` table in core `db_structure.xml` and not in `app/dav/appinfo/database.xml`?

**Comment by PVince81** [comment]
We probably never moved it when creating the "dav" app.
