### ISSUE TITLE
'defaultapp' setting broken after upgrading to 9.1

### ISSUE THREAD

**Issue by apircalabu** [owncloud/core#25562]
Reproduced on 2 CentOS 7 installations. On both, after upgrading via yum using ce_stable repo, OC takes me to files regardless of what the value for 'defaultapp' is in config.php. 'roundcube' used to be the value, but I've tried with 'activity', 'tasks', 'calendar' and 'contacts' and the behaviour is similar.
How to reproduce:
- occ maintenance:mode --on
- Upgrade from either 9.0.3 or 9.0.4 to 9.1.0 using "yum update"
- occ upgrade
- occ maintenance:mode --off
- Re-enable the apps previously disabled by the installer using occ app:enable <app>
- Each time you login and you'll be taken to /apps/files/

**Comment by DeepDiver1975** [comment]
Please help testing - https://github.com/owncloud/core/pull/25600

**Comment by apircalabu** [comment]
Fix confirmed, thanks.
