### ISSUE TITLE
Feature Request: Passwordless login

### ISSUE THREAD

**Issue by leonelwilliams** [owncloud/core#25560]
I'd love to see Passwordless login (https://passwordless.net/, https://hacks.mozilla.org/2014/10/passwordless-authentication-secure-simple-and-fast-to-deploy/) as an authenication plugin

It'd lower the friction of creating/remembering passwords and eliminate password reuse from affecting their ownCloud installation directly.

Essentially passwordless login is:
    - Enter email/username into login form
    - Aplication sends an email with a URL to click
    - Application notifies user (via response to form submission) to check their email to continue logging in
    - User clicks on link from email and is logged in

**Comment by PVince81** [comment]
Depending how this works (I didn't check the details), it should be possible to write an app that implements the "user management" APIs, a bit like the IMAP and other auth modules: https://github.com/owncloud/apps/tree/master/user_external

**Comment by PVince81** [comment]
=> separate app, not core
