### ISSUE TITLE
Can't play video in shared link using chrome and no sound in firefox

### ISSUE THREAD

**Issue by joeyjy** [owncloud/core#25561]
### Steps to reproduce
1. use 'share link' to share a mp4 file
2. open that link and click play button
3.

### Expected behaviour
smoothly view the mp4

### Actual behaviour
play button is disabled（in Chrome）
can play video but with no sound (in Firefox)

### Server configuration
**Operating system**: Centos 7

**Web server:** apache 2.4

**Database:** mysql 5.5

**PHP version:** 5.4

**ownCloud version:** (see ownCloud admin page) 9.0.1

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_cas: 1.1
  - user_ldap: 0.8.0
Disabled:
  - external
  - files_external
  - firstrunwizard
  - user_external
  - user_shib
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocsqodv3wcw7",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.cloud.corp.com",
            "10.9.113.195",
            "10.9.113.196",
            "10.9.113.194",
            "10.9.113.197"
        ],
        "datadirectory": "\/var\/www\/html\/Cdrive\/data",
        "overwrite.cli.url": "https:\/\/oc.cloud.corp.com",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "occlouddb",
        "dbhost": "occloud.mysql.db.corp.com:55944",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "keysalt": "B25m5g87EacYjY",
        "default_language": "zh_CN",
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\Swift",
            "arguments": {
                "username": "swift",
                "password": "***REMOVED SENSITIVE VALUE***",
                "container": "cdrivesystemdev",
                "autocreate": true,
                "region": "regionOne",
                "url": "http:\/\/cloud.ops.sh.corp.com:5000\/v2.0",
                "tenantName": "admin",
                "serviceName": "swift",
                "urlType": "internal"
            }
        },
        "integrity.check.disabled": true,
        "ldapIgnoreNamingRules": false,
        "loglevel": 2,
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APC",
        "redis": {
            "host": "10.9.113.196",
            "port": 6379,
            "timeout": 0,
            "password": ""
        },
        "mail_smtpmode": "smtp",
        "mail_smtphost": "appmail.sh.corp.com",
        "mail_smtpport": "25",
        "mail_from_address": "cloud-storage",
        "mail_domain": "corp.com",
        "asset-pipeline.enabled": true,
        "installed": true
    }
}
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** Ceph swift

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Chrome 49.0.2623.87 and Firefox 47.0.1

**Operating system:** windows7 basic

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

Hi OC,

I'm using owncloud9.0.1, after I shared a mp4 file to my staff using 'share link', they can't play it in chrome, the play button is disabled in the web plungin. when using firefox, we can play it but with no sound, the sound button is disabled. need your help :)

Thanks!

**Comment by RealRancor** [comment]
@joeyjy 
> ownCloud version: (see ownCloud admin page) 9.0.1

Before posting new issues please always update to a recent version first. 9.0.4 is the current stable version where 9.0.3 already includes a fix for such issues: #24830, https://github.com/owncloud/files_videoplayer/issues/45

**Comment by PVince81** [comment]
If it still doesn't work, also try updating to the latest Chrome or Firefox version, in case their video/audio APIs are changed. I think the video player doesn't auto-transcode anything so your browser might need to have mp4 codec support enabled.

**Comment by joeyjy** [comment]
@RealRancor @PVince81 Thanks guys, I'll close this issue
