### ISSUE TITLE
Updater from 0C 9.0.3 to 9.0.4 does not work using PHP 7.0.9 

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25566]
### Steps to reproduce

1. In admin view, click on open updater button

### Expected behaviour

No log should be shown and the update should start.

### Actual behaviour

A log is written in owncloud.log and the button seems useless

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0.9

**ownCloud version:**

"version":"9.0.3.2","versionstring":"9.0.3","edition":"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"iaJluC8gASwZLNYTSn91","remoteAddr":"","app":"PHP","message":"Error: Call to undefined function OC\\App\\simplexml_load_file() at \/opt\/owncloud\/lib\/private\/app\/infoparser.php#60","level":3,"time":"2016-07-22T07:55:11+00:00","method":"--","url":"--","user":"--"}
```
### Client configuration

**browser**
 
Firefox

@VicDeo  @DeepDiver1975

**Comment by RealRancor** [comment]
@davitol ``apt-get install php7.0-xml`` should do the trick

**Comment by davitol** [comment]
@RealRancor 

> apt-get install php7.0-xml

it solved the log problem, but the button keeps useless 😢

**Comment by RealRancor** [comment]
@davitol The button issue is tracked in https://github.com/owncloud/core/issues/25551

But the missing php7.0-xml probably should be also checked within the setup check or am i wrong?

**Comment by RealRancor** [comment]
Mhhh, normally you should get warned that SimpleXML is not loaded / avaliable:

https://github.com/owncloud/core/blob/v9.0.3/lib/private/util.php#L740

**Comment by PVince81** [comment]
@VicDeo

**Comment by VicDeo** [comment]
@davitol what does `which php` say?

**Comment by davitol** [comment]
> which php

/usr/bin/php

**Comment by davitol** [comment]
BTW i've tried again with the latest PR https://github.com/owncloud/administration-internal/pull/32 adn I got no problems updating from 9.0.3 to 9.0.5 so IMHO we can close this issue. If someone has any problems related to this issue please reopen the ticket
