### ISSUE TITLE
Update to 9.1 will add index.php to the share links

### ISSUE THREAD

**Issue by HelFANS** [owncloud/core#25574]
### Steps to reproduce
1. On Ubuntu 14.04 update from ownCloud version 9.0.4 to 9.1
2. sudo -u www-data php occ upgrade -> sucessfully
3. Previously shared links are supplemented by index.php e.g.</br>
with 9.0.4: </br>
https://cloud.domain.de/s/TzIlm6JPwRfFmL8
</br>
</br>
in 9.1: the link is shown as:  
https://cloud.domain.de/index.php/s/TzIlm6JPwRfFmL8

The old link is not working anymore.

### Expected behaviour
Do not modify the share links during the update.

### Actual behaviour
all defeied share links are modified

### Server configuration
Ubuntu 14.04.4 LTS"

Server version: Apache/2.4.7 (Ubuntu)

mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64)

PHP 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57)

Update from 9.0.4 to 9.1

Ubuntu repository with apt-get dist-upgrade

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - _calendar
  - _contacts
  - appframework
  - encryption
  - external
  - files_antivirus
  - files_embeddedvideo
  - files_external
  - files_mv
  - files_tree
  - files_versions
  - fluxx_compensator
  - gallery-backup
  - mozilla_sync
  - notes
  - ocusagecharts
  - search_lucene
  - user_external
  - user_ldap
  - videos

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'xxxx',
  'passwordsalt' => 'yyyy',
  'trusted_domains' =>
  array (
    0 => 'cloud.domain.de',
    1 => '172.18.1.2',
    2 => '172.18.1.2',
    3 => '172.18.1.1',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '9.0.4.1',
  'installed' => true,
  'loglevel' => '0',
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'enable_previews' => true,
  'preview_max_x' => NULL,
  'preview_max_y' => NULL,
  'preview_max_scale_factor' => 10,
  'trashbin_retention_obligation' => '60, auto',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1:3306',
  'dbuser' => 'oc_mysql_user',
  'dbpassword' => 'xyyxyxyxyxyx',
  'secret' => 'nnnnnnnnnnnnnnnnnnnnn',
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'domain.de',
  'updatechecker' => false,
  'htaccess.RewriteBase' => '/',

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
```

### Client configuration
**Browser:**
Firefox 47.0

**Operating system:**
Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ishmot** [comment]
I had this same issue.  Was able to fix the problem by re-inserting this info into my .htaccess file which was somehow removed during the update:

`ErrorDocument 403 /core/templates/403.php
ErrorDocument 404 /core/templates/404.php
<IfModule mod_rewrite.c>
  Options -MultiViews
  RewriteRule ^core/js/oc.js$ index.php [PT,E=PATH_INFO:$1]
  RewriteRule ^core/preview.png$ index.php [PT,E=PATH_INFO:$1]
  RewriteCond %{REQUEST_FILENAME} !\.(css|js|svg|gif|png|html|ttf|woff|ico|jpg|jpeg)$
  RewriteCond %{REQUEST_FILENAME} !core/img/favicon.ico$
  RewriteCond %{REQUEST_FILENAME} !/remote.php
  RewriteCond %{REQUEST_FILENAME} !/public.php
  RewriteCond %{REQUEST_FILENAME} !/cron.php
  RewriteCond %{REQUEST_FILENAME} !/core/ajax/update.php
  RewriteCond %{REQUEST_FILENAME} !/status.php
  RewriteCond %{REQUEST_FILENAME} !/ocs/v1.php
  RewriteCond %{REQUEST_FILENAME} !/ocs/v2.php
  RewriteCond %{REQUEST_FILENAME} !/updater/
  RewriteCond %{REQUEST_FILENAME} !/ocs-provider/
  RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge/.*
  RewriteRule . index.php [PT,E=PATH_INFO:$1]
  RewriteBase /
  <IfModule mod_env.c>
    SetEnv front_controller_active true
    <IfModule mod_dir.c>
      DirectorySlash off
    </IfModule>
  </IfModule>
</IfModule>
`

**Comment by HelFANS** [comment]
Thank you very much. 
I have added the rewrite part into the .htaccess and the problem was solved.
