### ISSUE TITLE
Birthday calendar event isn't delete after sync

### ISSUE THREAD

**Issue by pulcov** [owncloud/core#25572]
### Steps to reproduce
1. On phone, get contact with birthday
2. Delete birthday entry
3. Synchronize

### Expected behaviour
Birthday date is removed in contact apps
Birthday event is removed in calendar apps

### Actual behaviour
Birthday date is removed in contact apps
Birthday event remain in calendar apps

### Server configuration
**Operating system**:
Debian Jessie 8

**Web server:**
Apache 2.4.10

**Database:**
MySQL

**PHP version:**
PHP 5.6.23

**ownCloud version:** (see ownCloud admin page)
9.1

**Updated from an older ownCloud or fresh install:**
Updated from an older ownCloud

**Where did you install ownCloud from:**
Debian rep

**Signing status (ownCloud 9.0 and above):**
integrity check is disabled

### Client configuration
**Browser:**
(Sync) Davdroid 1.2

**Operating system:**
Android 5.1

**Comment by DeepDiver1975** [comment]
I cannot reproduce this.

Here is the  ode in question which removes the birthday entry - https://github.com/owncloud/core/blob/master/apps/dav/lib/CalDAV/BirthdayService.php#L69
