### ISSUE TITLE
SwitfMailer Self Signed Certificate

### ISSUE THREAD

**Issue by marcotuna** [owncloud/core#25585]
### Steps to reproduce
1. Add an email account whose mail server uses a self signed certificate
2. Try to send a test email
### Expected behaviour

It should send an email to the mail account
### Actual behaviour

It doens't send the email. I actualy fixed the issue by adding:
`$options['ssl']['verify_peer'] = false;`
`$options['ssl']['verify_peer_name'] = false;`
Under the line 262 on the file 3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php
### Server configuration

**Operating system**: FreeBSD 10.3

**Web server:** Nginx 1.10.0

**Database:** MariaDB 10.1

**PHP version:** PHP 7.0.7

**ownCloud version:** 9.0.4 Stable

**Updated from an older ownCloud or fresh install:** Currently it is updated but when it was fresh install the error still happens

**Where did you install ownCloud from:** Owncloud website

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - user_external: 0.4
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_ldap
```

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'xx',
  'passwordsalt' => 'xx',
  'secret' => 'xx',
  'trusted_domains' => 
  array (
    0 => 'xx.com',
    1 => 'www.xx.com',
    2 => 'xx.com',
    3 => 'www.xx.com',
  ),
  'datadirectory' => '/usr/local/www/domains/xx/public_html/data',
  'overwrite.cli.url' => 'xx',
  'dbtype' => 'mysql',
  'version' => '9.0.4.1',
  'dbname' => 'xx',
  'dbhost' => 'xx',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xx',
  'dbpassword' => 'xx',
  'logtimezone' => 'Europe/Lisbon',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'loglevel' => 0,
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'xx',
  'mail_domain' => 'xx',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'xx',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'xx',
  'mail_smtppassword' => 'xx',
  'updater.secret' => 'xx',
  'htaccess.RewriteBase' => '/',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Google Chrome

**Operating system:** Windows 10
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"M8P1AOybRQmDP\/qmYRNI","remoteAddr":"xx","app":"PHP","message":"stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed at \/usr\/local\/www\/domains\/owncloud.xx.com\/public_html\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Transport\/StreamBuffer.php#95","level":3,"time":"2016-07-23T10:19:12+01:00","method":"POST","url":"\/index.php\/settings\/admin\/mailtest","user":"admin"}
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
@marcotuna 

Setting https://github.com/owncloud/core/blob/v9.0.4/config/config.sample.php#L902 to true and importing the self signed cert in your admin backend should do the trick:

https://github.com/owncloud/core/pull/21336

**Comment by marcotuna** [comment]
@RealRancor I am having issues uploading the root certificate.
It shows: "An error occurred. Please upload an ASCII-encoded PEM certificate."
I've already tried to upload a PEM, DER, PKCS #7 and it does not work

**Comment by RealRancor** [comment]
Then you probably have a not correctly formatted / encoded certificate

**Comment by marcotuna** [comment]
@RealRancor I belive that my cert is correctly encoded / formatted.
I even tried certs from this website: https://www.geotrust.com/resources/root-certificates/
None of them works, I always get the same error

**Comment by PVince81** [comment]
or the SSL libraries have a bug and need updating ?

**Comment by PVince81** [comment]
Likely an env issue, closing. You might want to check or post on http://central.owncloud.org/ for further help
