### ISSUE TITLE
Ability to specific SFTP port in GUI

### ISSUE THREAD

**Issue by macmadness86** [owncloud/core#25584]
### Steps to reproduce
1. Add external storage support
2. Add SFTP Storage Location
3. Specify port other than 22 (can't, because it is hardcoded [forum.owncloud](https://forum.owncloud.org/viewtopic.php?t=11407))

### Expected behaviour
New field should exist where user can specify a different port.

### Actual behaviour
Field is missing, port 22 is implicitly used.

### Server configuration
**Operating system**:
4.6.4-1-ARCH x86_64 GNU/Linux

**Web server:**
nginx version: nginx/1.10.1

**Database:**
mysql 

**PHP version:**
PHP 7.0.9 (cli) (built: Jul 20 2016 17:12:28) ( NTS )

**ownCloud version:** (see ownCloud admin page)
ownCloud version 9.1.0

**Updated from an older ownCloud or fresh install:**
updated from previous version.

**Where did you install ownCloud from:**
Arch User Repository

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - calendar: 1.2.2
  - comments: 0.3.0
  - contacts: 1.3.1.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - mail: 0.5.2
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1

**Comment by RealRancor** [comment]
> The Host field is required; a port can be specified as part of the Host field in the following format: hostname.domain:port. The default port is 22 (SSH).

from https://doc.owncloud.org/server/9.0/admin_manual/configuration_files/external_storage/sftp.html#sftp
