### ISSUE TITLE
After Upgrade Code integrity check fails

### ISSUE THREAD

**Issue by TheAppService** [owncloud/core#25589]
After Upgrading to the newest owncloud version I always get the Code Integrity Check failed message. The suggested site with more information prints out this:
`Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- tasks
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate has been revoked.

Raw output
==========
Array
(
    [tasks] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate has been revoked.
                )

        )

)
`

Any idea where the problem could be ? I've got full access to my Linux Webserver (Nginx), ergo, full command line access.

Best regards and thank's for help in advance

Daniel

**Comment by TheAppService** [comment]
Upgrade to the newest Task's version fixed the issue

**Comment by RealRancor** [comment]
Please also see:

https://doc.owncloud.org/server/9.0/admin_manual/issues/code_signing.html#fixing-invalid-code-integrity-messages

which leads you to the issue tracker of that app and this report there:

https://github.com/owncloud/tasks/issues/328

**Comment by shaneonabike** [comment]
Well that wiki page is great but actually it doesn't same much about the Ceritificate related issue. Just that the signing was revoked. It kinda leaves people a tad bit in the dark.

**Comment by RealRancor** [comment]
@shaneonabike Feel free to contribute additional documentation at https://github.com/owncloud/documentation/issues
