### ISSUE TITLE
After upgrade to 9.1.0.15, accessing OC through a browser yields "Internal Server Error" 

### ISSUE THREAD

**Issue by gdgeorge** [owncloud/core#25583]
### Steps to reproduce
1. Looks like it's acting the same way as after the last update (see [https://github.com/owncloud/core/issues/24426](https://github.com/owncloud/core/issues/24426))
2. Successful update using OCC, and Maintenance Mode turned off.
3. Attempt to browse to the OC site.

### Expected behaviour
Should load the login page.

### Actual behaviour
Internal Server Error

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
PHP 7.0.8-0ubuntu0.16.04.1
 with Zend OPcache v7.0.8-0ubuntu0.16.04.1

**ownCloud version:** (see ownCloud admin page)
sudo -u www-data php occ status
  - installed: true
  - version: 9.1.0.15
  - versionstring: 9.1.0
  - edition:
**Updated from an older ownCloud or fresh install:**
Update

**Where did you install ownCloud from:**
Repository, using apt-get

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

Internal Server Error....
The Apache log for 

```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
 sudo -u www-data php occ app:list
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - files_mv
  - user_external
  - user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
 sudo -u www-data php occ config:list system
{
    "system": {
        "updatechecker": false,
        "instanceid": "oci9zh73wckk",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "lampr",
            "cloud.echo4golf.com"
        ],
        "datadirectory": "\/var\/www\/sf_cloud",
        "overwrite.cli.url": "\/",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 2,
        "htaccess.RewriteBase": "\/"
    }
}
or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windoze 10
#### Web server error log
[Fri Jul 22 10:37:33.735839 2016] [authz_core:error] [pid 1271] [client 188.64.222.101:37838] AH01630: client denied by server configuration: /owncloud
[Fri Jul 22 10:37:34.276277 2016] [authz_core:error] [pid 2996] [client 188.64.222.101:38065] AH01630: client denied by server configuration: /owncloud
[Fri Jul 22 10:37:34.288461 2016] [authz_core:error] [pid 2919] [client 188.64.222.101:38064] AH01630: client denied by server configuration: /owncloud
[Fri Jul 22 10:37:34.314102 2016] [authz_core:error] [pid 1253] [client 188.64.222.101:38066] AH01630: client denied by server configuration: /owncloud
[Fri Jul 22 10:37:34.322551 2016] [authz_core:error] [pid 1257] [client 188.64.222.101:38067] AH01630: client denied by server configuration: /owncloud
[Fri Jul 22 10:37:34.930427 2016] [authz_core:error] [pid 2996] [client 188.64.222.101:38337] AH01630: client denied by server configuration: /owncloud
[Fri Jul 22 10:37:34.937332 2016] [authz_core:error] [pid 1256] [client 188.64.222.101:38335] AH01630: client denied by server configuration: /owncloud
[Fri Jul 22 12:17:45.808798 2016] [authz_core:error] [pid 1253] [client 54.80.63.234:38720] AH01630: client denied by server configuration: /owncloud
[Fri Jul 22 17:11:43.051831 2016] [mpm_prefork:notice] [pid 1187] AH00171: Graceful restart requested, doing restart
AH00112: Warning: DocumentRoot [/owncloud] does not exist
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
{"reqId":"DtHhAXHH1KUUO76hkS3I","remoteAddr":"192.168.1.1","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/login) cannot be processed by the script '\\\/owncloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(838): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php\",\"Line\":631}","level":3,"time":"2016-07-23T00:26:17+00:00","method":"GET","url":"\/login?redirect_url=%252Findex.php%252Fsettings%252Fintegrity%252Ffailed","user":"--"}
{"reqId":"c5RaS1YHPJ0sEMDJkIeZ","remoteAddr":"192.168.1.1","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/login) cannot be processed by the script '\\\/owncloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(838): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php\",\"Line\":631}","level":3,"time":"2016-07-23T00:30:06+00:00","method":"HEAD","url":"\/login","user":"--"}
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
If you're accessing your oC instance via http://example.com/owncloud then you have configured both settings here wrong:

'htaccess.RewriteBase' => '/' should

be:

'htaccess.RewriteBase' => '/owncloud'

and:

'overwrite.cli.url' => '/'

should be:

'overwrite.cli.url' => 'http://example.com'

Afterwards run:

occ maintenance:update:htaccess

Ref: https://github.com/owncloud/documentation/issues/2431

**Comment by gdgeorge** [comment]
Hi Real, 

Thanks for the reply.  This install is accessed directly via a sub-domain, i.e. cloud.echo4golf.com.  I had successfully applied the fix for #24426 last time, but managed to bork it when I tried this time.  

Changing the value of 'overwrite.cli.url'  from '/' to 'https://cloud.echo4golf.com/' did the trick and I'm gtg.

Best,
Jerry
echo4golf

**Comment by RealRancor** [comment]
@gdgeorge You can close this issue on your own by hitting the "Close" button below the comment field.

**Comment by gdgeorge** [comment]
Done. Thanks again.
