### ISSUE TITLE
Upgrade to 9.1.0 shows Exception "files can't be disabled"

### ISSUE THREAD

**Issue by GetMike** [owncloud/core#25597]
### Steps to reproduce
1. Download latest owncloud version owncloud-9.1.0.zip
2. Upgrade manually like description
3. Run occ upgrade

### Expected behaviour
Upgrade to version 9.1.0 should be done

### Actual behaviour
Exception is shown:

PHP Warning:  Module 'pdo_mysql' already loaded in Unknown on line 0
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
 Done
 24/24 [============================] 100%
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Exception: files can't be disabled.
Update failed
Maintenance mode is kept active
Reset log level

### Server configuration
**Operating system**:
bananian linux 3.4

**Web server:**
nginx

**Database:**
mysql

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
9.0.2.2

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.2.1
  - apporder: 0.1.1
  - bookmarks: 0.7
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - conversations: 0.2.3
  - dav: 0.1.6
  - direct_menu: 0.8.0
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_antivirus: 0.8.0.1
  - files_external: 0.5.2
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - gpxpod: 1.0.0
  - mail: 0.5.2
  - maps: 0.0.6
  - notifications: 0.2.3
  - ocsms: 1.7.0
  - ownnote: 1.08
  - passwords: 18.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.9.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
  - weather: 1.3.3
Disabled:
  - encryption
  - external
  - news
  - notes
  - registration
  - user_external
  - user_ldap

**The content of config/config.php:**

"system": {
        "instanceid": "...",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "...",
            "..."
        ],
        "datadirectory": "\/var\/secure\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/...\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": true,
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 0,
        "activity_expire_days": 90

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"Q6DJES7c06r6\/BRnigHs","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"files can't be disabled.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/secure\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(407): OC\\\\App\\\\AppManager->disableApp('files')\\n#1 \\\/var\\\/secure\\\/owncloud\\\/lib\\\/private\\\/Updater.php(405): OC_App::disable('files')\\n#2 \\\/var\\\/secure\\\/owncloud\\\/lib\\\/private\\\/Updater.php(250): OC\\\\Updater->checkAppsRequirements()\\n#3 \\\/var\\\/secure\\\/owncloud\\\/lib\\\/private\\\/Updater.php(150): OC\\\\Updater->doUpgrade('9.1.0.15', '9.0.2.2')\\n#4 \\\/var\\\/secure\\\/owncloud\\\/core\\\/Command\\\/Upgrade.php(290): OC\\\\Updater->upgrade()\\n#5 \\\/var\\\/secure\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#6 \\\/var\\\/secure\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(844): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/var\\\/secure\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/secure\\\/owncloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/usr\\\/share\\\/owncloud\\\/console.php(43): Symfony\\\\Component\\\\Console\\\\Application->run()\\n#10 \\\/usr\\\/share\\\/owncloud\\\/occ(11): require_once('\\\/usr\\\/share\\\/ownc...')\\n#11 {main}\",\"File\":\"\\\/var\\\/secure\\\/owncloud\\\/lib\\\/private\\\/App\\\/AppManager.php\",\"Line\":256}","level":3,"time":"2016-07-25T07:26:45+00:00","method":"--","url":"--","user":"--"}

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
@GetMike Had a chat with a user in IRC yesterday about the very same issue. This is caused by a wrong done upgrade where the old files (of e.g. 9.0.4) are just overwritten with the new files without deleting the old files first.

So make sure that you delete all files and folders except /data/ and /config/ before you're extracting the new files of oC 9.1.0 to your install folder.

**Comment by GetMike** [comment]
Thanks for your immediate answer! That's confusing me, because I created a completely new directory, where I unzipped the new version of owncloud. Then I just copied all the apps-files from the old owncloud installation, the files from the data-directory and the config.php file ... all other files and directories are from the new installation.
So what could be the cause for this exception? Or what should I do in a different way to get the upgrade through?

**Comment by GetMike** [comment]
Found this in the log - maybe it helps:
{"reqId":"17mK+en1W6OwZ6E\/jJeZ","remoteAddr":"10.130.20.14","app":"PHP","message":"Call to undefined method OCA\\Activity\\FilesHooksStatic::register() at \/var\/secure\/owncloud\/apps\/activity\/appinfo\/app.php#41","level":3,"time":"2016-07-25T08:18:06+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=f4f4edf3d54306202d8625a8948f71e8","user":"--"}

**Comment by RealRancor** [comment]
> Then I just copied all the apps-files from the old owncloud installation, 

This is your issue. You never ever should copy over the old apps folder to the new installation.

**Comment by DeepDiver1975** [comment]
https://doc.owncloud.org/server/9.1/admin_manual/maintenance/manual_upgrade.html
