### ISSUE TITLE
Files deleted on client after data loss on server

### ISSUE THREAD

**Issue by sagamusix** [owncloud/core#25592]
### Steps to reproduce
I have had an outage on my ownCloud server where the external data storage was disconnected while it was running and syncing, leading to several files being lost. I did a cleanup with fsck to make sure the file system is consistent and then ran occ files:scan to make sure that the server database is also consistent and does not contain missing or truncated files.
I just looked into my client log to see that several files were deleted through the client.  Those files are indeed also missing on the server (but some of them were not on the server before the drive was disconnected, either - some were new files just added to the client today), but **none** of those files turn up in the "deleted" folder on the server.

### Expected behaviour
Files that were removed on the server due to a clean-up should never be deleted on the client.

### Actual behaviour
See above.

### Server configuration
**Operating system**: Bananian (Debian Jessie)

**Web server:** Apache2

**Database:** MySQL

**ownCloud version:** 9.0.4

**Updated from an older ownCloud or fresh install:** Upgraded from previous 9.0.x stable

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

### Client configuration

**Operating system:** Windows 7

**Comment by RealRancor** [comment]
> Files that were removed on the server due to a clean-up should never be deleted on the client.

Files deleted / removed on the server are always deleted on the client. Thats the expected behavior:

> The process of synchronization keeps files in two separate repositories the same. When synchronized:
>
> - If a file is added to one repository it is copied to the other synchronized repository.
> - When a file is changed in one repository, the change is propagated to any other synchronized repository.
> - If a file is deleted in one repository, it is deleted in any other.

https://doc.owncloud.org/desktop/2.2/architecture.html#the-synchronization-process

A feature request for the client to handle such "backup" situations is available here: https://github.com/owncloud/client/issues/2325

**Comment by sagamusix** [comment]
Note that I didn't delete the files on the server myself - I would agree if they were deleted on the server due to me manually hitting the delete button in the browser, but not if it happens because the file is lost on the server for whatever reason.

**Comment by RealRancor** [comment]
I think you can still close here and follow in https://github.com/owncloud/client/issues/2325

Such stuff needs to be handled by the client as discussed there.
