### ISSUE TITLE
OC Instance fails to remember user session after manual upgrade to 9.1.0

### ISSUE THREAD

**Issue by the-vindicar** [owncloud/core#25602]
### Steps to reproduce
1. Configure a 8.2.7 instance, create a user.
2. Configure Firefox to discard cookies when closed, add owncloud instance host to exceptions as "always allow".
3. Log into the instance, close the browser (all windows, so its process terminates).
4. Open Firefox again, open owncloud instance URL, make sure it remembers current user.
5. Perform manual upgrade (delete, unzip, occ upgrade) to 9.0.4
6. Perform manual upgrade (delete, unzip, occ upgrade) to 9.1.0
7. Log into the instance, close the browser (all windows, so its process terminates).
8. Open Firefox again, open owncloud instance URL.

### Expected behaviour
Owncloud should remember logged in user, just as it did at version 8.2.7.

### Actual behaviour
Login page is shown, apparently user session was not saved.

### Server configuration
**Operating system:** Ubuntu server edition, Linux 2366 2.6.32-042stab113.12

**Web server:** lighttpd/1.4.33 (ssl)

**Database:** mysql  Ver 14.14 Distrib 5.5.50, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:** PHP 5.5.9-1ubuntu4.17 (cli) (built: May 19 2016 19:05:57)

**ownCloud version:** OwnCloud 9.1.0 stable

**Updated from an older ownCloud or fresh install:** manually upgraded from 8.2.7 via 9.0.4

**Where did you install ownCloud from:** owncloud.org

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - news: 8.8.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - calendar
  - comments
  - encryption
  - external
  - federation
  - files_antivirus
  - files_external
  - files_sharing
  - firstrunwizard
  - systemtags
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocr62wwe0tyw",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "vindicar.name",
            "outerhaven.vnet",
            "10.42.0.1"
        ],
        "session_lifetime": 2592000,
        "datadirectory": "\/var\/www\/vindicar.name\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/vindicar.name\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "logfile": "\/var\/log\/owncloud-access.log",
        "loglevel": 2,
        "log_authfailip": true,
        "maintenance": false,
        "theme": "",
        "trashbin_retention_obligation": "auto",
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "vindicar.name"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 47.0.1, tested with and without addons.

**Operating system:** Windows 10 x64 Home Edition

#### Excerpt from web server error log
```
2016-07-24 13:48:23: (mod_fastcgi.c.2673) FastCGI-stderr: PHP Fatal error:  Class '\OCP\Backgroundjob' not found in /var/www/vindicar.name/owncloud/apps/news/config/appconfig.php on line 88
2016-07-24 13:48:28: (mod_fastcgi.c.2673) FastCGI-stderr: PHP Fatal error:  Class '\OCP\Backgroundjob' not found in /var/www/vindicar.name/owncloud/apps/news/config/appconfig.php on line 88
2016-07-24 16:22:28: (connections.c.305) SSL: 1 error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
2016-07-24 21:21:05: (connections.c.1559) SSL: error:00000000:lib(0):func(0):reason(0)
2016-07-25 00:48:47: (connections.c.305) SSL: 1 error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
2016-07-25 08:26:25: (connections.c.305) SSL: 1 error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
```
After reading owncloud forum, I patched '\OCP\Backgroundjob' to '\OCP\BackgroundJob' in news/config/appconfig.php which allowed ownCloud news app to function.

#### ownCloud log (data/owncloud.log)
log file is empty.

#### JS Console after logging in:
```
window.controllers is obsolete. Don't use it to determine UA. ace.js:1716:0
```

#### HTTP Headers for login reply
```
Cache-Control: no-cache, must-revalidate
Content-Length: 0
Content-Security-Policy: default-src 'none';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self'
Content-Type: text/html; charset=UTF-8
Date: Mon, 25 Jul 2016 12:50:53 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Location: /owncloud/index.php/apps/files/
Pragma: no-cache
Server: lighttpd/1.4.33
Set-Cookie: ocr62wwe0tyw=9h75lrs2km003dkuqq39mgu8a4; path=/owncloud; secure; HttpOnly
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: Sameorigin
X-Permitted-Cross-Domain-Policies: none
X-Powered-By: PHP/5.5.9-1ubuntu4.17
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
strict-transport-security: max-age=63072000; includeSubdomains; preload
```

I stress again that ownCloud session was remembered properly before upgrade to OC9, and neither browser nor web-server configuration hasn't been changed. If I set Firefox to keep cookies until they expire, session is still not remembered. Hence I blame it on OC9 update.
It happens for admin, pre-upgrade user account and post-upgrade testing account.
You can try logging into my instance for testing. 
URL: https://vindicar.name/owncloud/
User: test
Password: test

**Comment by cthil** [comment]
Can confirm this, upgraded from 9.0.4 to 9.1.0. The list of open sessions in the user preferences grows but I have to login each time even if I tick the checkbox to remember the session. Safari and Chromium on OS X.

**Comment by pulcov** [comment]
I confirm this also. Upgrade from 9.0.4 to 9.1.0

**Comment by the-vindicar** [comment]
Okay, if I got that correct, the problem is in this header:
```Set-Cookie: ocr62wwe0tyw=9h75lrs2km003dkuqq39mgu8a4; path=/owncloud; secure; HttpOnly```
The cookie has no expiration date specified, which results in a [session cookie](https://en.wikipedia.org/wiki/HTTP_cookie#Session_cookie) being set. Which is, as expected, expires the moment browser is closed...

I'm now trying to find the part of code that's responsible for setting session cookies, so I can patch it.

**Comment by the-vindicar** [comment]
After adding some debug lines I've identified the problem: [session.cookie_lifetime](http://php.net/manual/en/session.configuration.php#ini.session.cookie-lifetime) in /etc/php5/cgi/php.ini was set to 0. Changing it to 2592000 (~1 month) fixed the issue.
However, I'm unsure why the very same configuration worked fine before. I can only assume that earlier versions of ownCloud were using [ini_set()](http://php.net/manual/en/function.ini-set.php) or [session_set_cookie_params()](http://php.net/manual/en/function.session-set-cookie-params.php) to change the default session cookie lifetime to something appropriate, while 9.1.0 doesn't do it anymore for whatever reason.
