### ISSUE TITLE
'Fix classification for calendar objects' loads all users even when 'oc_calendarobjects' is empty

### ISSUE THREAD

**Issue by sbraz** [owncloud/core#25617]
As discussed with @DeepDiver1975 on IRC.
### Steps to reproduce
* Upgrade from 9.03 to 9.1.0
* Have an empty `oc_calendarobjects` table

### Expected behaviour
The `Fix classification for calendar objects` step should only take a second.

### Actual behaviour
The upgrade script [iterates over all users](https://github.com/owncloud/core/blob/5a058f6c0ef64ff0272fcdb58478f9c6611d6819/apps/dav/lib/Migration/Classification.php#L86-L90) which makes the process really slow on a setup with a lot of LDAP users.

**Comment by DeepDiver1975** [comment]
THX @sbraz

**Comment by DeepDiver1975** [comment]
fixed with #25638
