### ISSUE TITLE
Error during Upgrade 9.0.3 -> 9.1.0: Does not follow Symlinks anymore

### ISSUE THREAD

**Issue by unraun** [owncloud/core#25613]
### Steps to reproduce
(Happens since first installation via script)
1. Moving all encryption key folders "files_encryption" to an USB stick (/media/owncloudKeys, ext4 filesystem)
2. Creating symlink on old folder location to the new location
3. Example: 
mv /home/user/owncloud/data/files_encryption /media/owncloudKeys/files_encryption
ln -s /media/owncloudKeys/files_encryption /home/user/owncloud/data/files_encryption

(Now:)
4. apt-get install --only-upgrade owncloud*
5. Upgrading in browser
(same error also happened with "occ upgrade" in commandline)

### Expected behaviour
Successful upgrade to the next version. This has worked in the all OwnCloud versions prior to 9.1. for me without problems.

### Actual behaviour
Error from OwnCloud: "Following symlinks is not allowed"

Detailled Errormessages:
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Prüfen, ob das Datenbankschema aktualisiert werden kann (dies kann je nach Datenbankgröße sehr lange dauern)
[1 / 24]: Überprüfe Tabelle oc_appconfig
[2 / 24]: Überprüfe Tabelle oc_storages
[3 / 24]: Überprüfe Tabelle oc_mounts
[4 / 24]: Überprüfe Tabelle oc_mimetypes
[5 / 24]: Überprüfe Tabelle oc_filecache
[6 / 24]: Überprüfe Tabelle oc_group_user
[7 / 24]: Überprüfe Tabelle oc_group_admin
[8 / 24]: Überprüfe Tabelle oc_groups
[9 / 24]: Überprüfe Tabelle oc_preferences
[10 / 24]: Überprüfe Tabelle oc_properties
[11 / 24]: Überprüfe Tabelle oc_share
[12 / 24]: Überprüfe Tabelle oc_jobs
[13 / 24]: Überprüfe Tabelle oc_users
[14 / 24]: Überprüfe Tabelle oc_authtoken
[15 / 24]: Überprüfe Tabelle oc_vcategory
[16 / 24]: Überprüfe Tabelle oc_vcategory_to_object
[17 / 24]: Überprüfe Tabelle oc_systemtag
[18 / 24]: Überprüfe Tabelle oc_systemtag_object_mapping
[19 / 24]: Überprüfe Tabelle oc_systemtag_group
[20 / 24]: Überprüfe Tabelle oc_privatedata
[21 / 24]: Überprüfe Tabelle oc_file_locks
[22 / 24]: Überprüfe Tabelle oc_comments
[23 / 24]: Überprüfe Tabelle oc_comments_read_markers
[24 / 24]: Überprüfe Tabelle oc_credentials
Datenbankschema-Aktualisierung überprüft
Es wird nach Updates für die Apps gesucht
Prüfen, ob das Datenbankschema für files_sharing aktualisiert werden kann (dies kann je nach Datenbankgröße sehr lange dauern)
[1 / 1]: Überprüfe Tabelle oc_share_external
Prüfen, ob das Datenbankschema für notifications aktualisiert werden kann (dies kann je nach Datenbankgröße sehr lange dauern)
[1 / 1]: Überprüfe Tabelle oc_notifications
Datenbankschema-Aktualisierung für Apps überprüft
Datenbank-Schema wird upgedatet
Datenbank aktualisiert
OCP\Files\ForbiddenException: Following symlinks is not allowed ('/home/user/owncloud/data/files_encryption/OC_DEFAULT_MODULE/pubShare_97bc9a53.publicKey' -> '/media/owncloudKeys/files_encryption/OC_DEFAULT_MODULE/pubShare_97bc9a53.publicKey/' not inside '/home/user/owncloud/data/')

### Server configuration
**Operating system**: Debian 8.4

**Web server:** Apache/2.4.18 (Debian)

**Database:** mysql  Ver 14.14 Distrib 5.5.50, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:** PHP 5.6.23-0+deb8u1 (cli) (built: Jul 12 2016 07:33:16) 

**ownCloud version:** 9.0.3 (stable). Upgrading to 9.1.0

**Updated from an older ownCloud or fresh install:** Updated from older ownCloud. First install was 9.0.1

**Where did you install ownCloud from:** OwnCloud Repository for Debian 8.0 (owncloud + owncloud_files)
(https://download.owncloud.org/download/repositories/stable/owncloud/)

**Signing status (ownCloud 9.0 and above):** Login not possible, due to failed upgrade

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - calendar: 1.3.1
  - comments: 0.2
  - dav: 0.1.6
  - encryption: 1.2.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - external
  - files_antivirus
  - files_external
  - files_trashbin
  - registration
  - user_external
  - user_ldap

**The content of config/config.php:**

{
    "system": {
        "updatechecker": false,
        "instanceid": "ocpq8079exk6",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "..."
        ],
        "datadirectory": "\/home\/user\/owncloud\/data\/",
        "overwrite.cli.url": "...",
        "dbtype": "mysql",
        "version": "9.0.3.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "CEST",
        "installed": true,
        "loglevel": 2,
        "log_authfailip": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "enable_previews": false,
        "default_language": "de",
        "maintenance": false,
        "theme": "",
        "htaccess.RewriteBase": "\/"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 10

#### Web server error log
Is empty

#### ownCloud log (data/owncloud.log)
{"reqId":"oK+jgky+lVt\/9KfXqw1n","remoteAddr":"...","app":"core","message":"starting upgrade from 9.0.3.2 to 9.1.0.15","level":0,"time":"2016-07-26T09:32:49+01:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=Wwh5IVU%2BGgp%2BA3YuKWcMGCl8aQUvdi1qai0DPwoJLww%3D%3ApyNF7dPXIJFmCUtVKN0ag9E83cTFRxZYtnnVjt3t5FQ%3D","user":"--"}
{"reqId":"oK+jgky+lVt\/9KfXqw1n","remoteAddr":"...","app":"core","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\ForbiddenException\",\"Message\":\"Following symlinks is not allowed ('\\\/home\\\/user\\\/owncloud\\\/data\\\/files_encryption\\\/OC_DEFAULT_MODULE\\\/pubShare_97bc9a53.publicKey' -> '\\\/media\\\/owncloudKeys\\\/files_encryption\\\/OC_DEFAULT_MODULE\\\/pubShare_97bc9a53.publicKey\\\/' not inside '\\\/home\\\/user\\\/owncloud\\\/data\\\/')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Local.php(166): OC\\\\Files\\\\Storage\\\\Local->getSourcePath('files_encryptio...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(219): OC\\\\Files\\\\Storage\\\\Local->file_exists('files_encryptio...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1118): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('files_encryptio...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(523): OC\\\\Files\\\\View->basicOperation('file_exists', '\\\/files_encrypti...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(190): OC\\\\Files\\\\View->file_exists('\\\/files_encrypti...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Encryption\\\/Keys\\\/Storage.php(101): OC\\\\Encryption\\\\Keys\\\\Storage->getKey('\\\/files_encrypti...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/KeyManager.php(558): OC\\\\Encryption\\\\Keys\\\\Storage->getSystemUserKey('pubShare_97bc9a...', 'OC_DEFAULT_MODU...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/KeyManager.php(157): OCA\\\\Encryption\\\\KeyManager->getPublicShareKey()\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/Users\\\/Setup.php(85): OCA\\\\Encryption\\\\KeyManager->validateShareKey()\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/AppInfo\\\/Application.php(72): OCA\\\\Encryption\\\\Users\\\\Setup->setupSystem()\\n#10 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/appinfo\\\/app.php(29): OCA\\\\Encryption\\\\AppInfo\\\\Application->__construct(Array, true)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(186): require_once('\\\/var\\\/www\\\/ownclo...')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(149): OC_App::requireAppFile('encryption')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(381): OC_App::loadApp('encryption', false)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(251): OC\\\\Updater->doAppUpgrade()\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(150): OC\\\\Updater->doUpgrade('9.1.0.15', '9.0.3.2')\\n#16 \\\/var\\\/www\\\/owncloud\\\/core\\\/ajax\\\/update.php(193): OC\\\\Updater->upgrade()\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Local.php\",\"Line\":370}","level":3,"time":"2016-07-26T09:33:31+01:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=Wwh5IVU%2BGgp%2BA3YuKWcMGCl8aQUvdi1qai0DPwoJLww%3D%3ApyNF7dPXIJFmCUtVKN0ag9E83cTFRxZYtnnVjt3t5FQ%3D","user":"--"}

**Comment by RealRancor** [comment]
@unraun This is the expected behavior since 9.1: https://github.com/owncloud/documentation/issues/2493

Additionally using symlinks within the datadir itself are unsupported since a longer time (oC 8.0.x)

https://doc.owncloud.org/server/9.1/admin_manual/release_notes.html#owncloud-does-not-follow-symlinks

**Comment by DeepDiver1975** [comment]
to relocate the key folder please have a look at the occ command encryption:change-key-storage-root

**Comment by bstidham** [comment]
How do you configure where individual "files" directories reside without symlinks? I have it configured so that "data" to resides in the default location but individual user data/files/bsitidham maps to be /media/DRIVE/, and data/files/someoneelse maps to /media/DRIVE/someoneelse. This is how i had things working until upgrading broke the setup. I don't want all the other folders data holds on my external drive, just the content data mapped to specific locations. Thanks, Bill

**Comment by PVince81** [comment]
Due to security reasons, ownCloud doesn't follow symlinks inside the data folder any more, see https://github.com/owncloud/core/pull/24899.

You can use `mount --bind` instead.

**Comment by cweiske** [comment]
bind mount works here.

**Comment by bstidham** [comment]
Ended up just commenting the exception. I think I did a grep for the error message to find it.
