### ISSUE TITLE
occ throws unhandled exception

### ISSUE THREAD

**Issue by CNSKnight** [owncloud/core#25619]
this look like a fairly straight-forward oversite, but therein completely chokes the upgrade
```
Updating <federation> ...
An unhandled exception has been thrown:
Error: Call to undefined method OCA\Federation\AppInfo\Application::setupCron() in /var/www/owncloud/apps/federation/appinfo/update.php:23
Stack trace:
#0 /var/www/owncloud/lib/private/legacy/app.php(1192): include()
#1 /var/www/owncloud/lib/private/Updater.php(374): OC_App::updateApp('federation')
```

**Comment by DeepDiver1975** [comment]
9.1 update?

**Comment by CNSKnight** [comment]
yes'sir

**Comment by CNSKnight** [comment]
ubuntu .deb if it wasn't clear

**Comment by DeepDiver1975** [comment]
> /var/www/owncloud/apps/federation/appinfo/update.php

this file does not exist in the 9.1 release - see https://github.com/owncloud/core/tree/stable9.1/apps/federation/appinfo

it must be a left over from a previous installation.



> ubuntu .deb if it wasn't clear

what is the repo location?

**Comment by CNSKnight** [comment]
wget -nv
https://download.owncloud.org/download/repositories/9.1/Ubuntu_16.04/Release.key
-O Release.key
sh -c "echo 'deb
http://download.owncloud.org/download/repositories/9.1/Ubuntu_16.04/ /' >>
/etc/apt/sources.list.d/owncloud.list"
:)

**Comment by DeepDiver1975** [comment]
@jnweiger please have a look - thx

**Comment by jnweiger** [comment]
@DeepDiver1975 wouldn't the integrity checker find such left over files?
The Debian package installer does not touch unknown files.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 wouldn't the integrity checker find such left over files?

yes - @CNSKnight can you provide the integrity check report please? THX

**Comment by PVince81** [comment]
Closing due to lack of feedback
