### ISSUE TITLE
unclear error message after failing extension update

### ISSUE THREAD

**Issue by schiran** [owncloud/core#25627]
After Update from 8.1.0 to 8.2.1 things ended up in unclear error message, when trying to update Extensions.

![owncloud-2016-07-27](https://cloud.githubusercontent.com/assets/20678417/17168666/f232348c-53e3-11e6-80e0-a899e0b30c6a.png)

There should at least be comment on what to do next.

**Comment by RealRancor** [comment]
@schiran 
This text was already improved / extended in oC 9.0+:

https://github.com/owncloud/core/issues/25354#issuecomment-230384721
