### ISSUE TITLE
Error  Insufficient Storage (Sabre\DAV\Exception\InsufficientStorage)

### ISSUE THREAD

**Issue by rikideveloper** [owncloud/core#25620]
Hello i have problem with sync .doc file from windows and mac client of owncloud to owncloud server (Ubuntu), the message of error is:

_ERROR:_
**Continue blacklisting: Error downloading https:/myserver/owncloud/remote.php/webdav/Copie progetti EIB/ETS 5/AB Trasmissioni/valz.doc-chunking-2234905358-2-0 - server replied: Insufficient Storage (Sabre\DAV\Exception\InsufficientStorage)**

how can solve this error?

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
@rikideveloper Please fill out the shown issue template instead of just leaving it empty. Currently even the basic info about your running oC version and your environment is missing.

**Comment by rikideveloper** [comment]
The version of owncloud is 9.1.0

**Comment by RealRancor** [comment]
Please fill out the issue template as asked.

**Comment by SergioBertolinSG** [comment]
Duplicated https://github.com/owncloud/core/issues/25582
