### ISSUE TITLE
Webdav Error in Log-File: Duplicate entry 'files_sharing-46': UniqueConstraintViolationException

### ISSUE THREAD

**Issue by kiwee90** [owncloud/core#25624]
### Steps to reproduce
1. Simply Uploading files via client

### Actual behaviour
In the log-file I'll get this Error:
`Exception: {"Message":"An exception occurred while executing 'INSERT INTO `oc_appconfig` (`appid`,`configkey`,`configvalue`) SELECT ?,?,? FROM `oc_appconfig` WHERE `appid` = ? AND `configkey` = ? HAVING COUNT(*) = 0' with params [\"files_sharing\", \"46\", 1469564088.2161, \"files_sharing\", \"46\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files_sharing-46' for key 'PRIMARY'","Exception":"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","Code":0,"Trace":"#0 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/lib\/private\/db\/connection.php(203): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\n#3 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/lib\/private\/db\/adapter.php(93): OC\\DB\\Connection->executeUpdate('INSERT INTO `*P...', Array)\n#4 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/lib\/private\/db\/connection.php(242): OC\\DB\\Adapter->insertIfNotExist('*PREFIX*appconf...', Array, Array)\n#5 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/lib\/private\/appconfig.php(160): OC\\DB\\Connection->insertIfNotExist('*PREFIX*appconf...', Array, Array)\n#6 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/lib\/private\/allconfig.php(159): OC\\AppConfig->setValue('files_sharing', '46', 1469564088.2161)\n#7 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/apps\/files_sharing\/lib\/propagation\/recipientpropagator.php(167): OC\\AllConfig->setAppValue('files_sharing', '46', 1469564088.2161)\n#8 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/apps\/files_sharing\/lib\/propagation\/recipientpropagator.php(192): OCA\\Files_Sharing\\Propagation\\RecipientPropagator->markDirty(Array, 1469564088.2161)\n#9 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/apps\/files_sharing\/lib\/propagation\/recipientpropagator.php(178): OCA\\Files_Sharing\\Propagation\\RecipientPropagator->propagateById(42226)\n#10 [internal function]: OCA\\Files_Sharing\\Propagation\\RecipientPropagator->OCA\\Files_Sharing\\Propagation\\{closure}('\/DACH-Marketing', Array)\n#11 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/lib\/private\/hooks\/emittertrait.php(98): call_user_func_array(Object(Closure), Array)\n#12 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/lib\/private\/files\/cache\/changepropagator.php(80): OC\\Hooks\\BasicEmitter->emit('\\\\OC\\\\Files', 'propagate', Array)\n#13 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/lib\/private\/files\/cache\/updater.php(136): OC\\Files\\Cache\\ChangePropagator->propagateChanges(NULL)\n#14 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/lib\/private\/files\/view.php(1039): OC\\Files\\Cache\\Updater->update('\/DACH-Marketing...')\n#15 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/lib\/private\/files\/view.php(251): OC\\Files\\View->basicOperation('mkdir', '\/DACH-Marketing...', Array)\n#16 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/lib\/private\/connector\/sabre\/directory.php(142): OC\\Files\\View->mkdir('\/DACH-Marketing...')\n#17 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1177): OC\\Connector\\Sabre\\Directory->createDirectory('Highlight-Aufst...')\n#18 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(583): Sabre\\DAV\\Server->createCollection('DACH-Marketing\/...', Array, Array)\n#19 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#20 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#21 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#22 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#23 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/apps\/files\/appinfo\/remote.php(56): Sabre\\DAV\\Server->exec()\n#24 \/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/remote.php(137): require_once('\/var\/www\/virtua...')\n#25 {main}","File":"\/var\/www\/virtual\/serverunity.de\/cloud\/htdocs\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":66} `

Client tolds a internal server error at this timestamp:
` 26.07.2016 22:52:47,  server replied: Internal Server Error`

### Server configuration
**Operating system**: Debian Jessie 8
4.6.0-md

**Web server:**
Server version: Apache/2.4.10 (Debian)
Server built:   Jul 20 2016 06:48:18

**Database:**
5.7.13-1debian8

**PHP version:**
PHP 5.6.23-0+deb8u1 (cli) (built: Jul 12 2016 07:33:16)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with XCache v3.2.0, Copyright (c) 2005-2014, by mOo
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with XCache Optimizer v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Cacher v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Coverager v3.2.0, Copyright (c) 2005-2014, by mOo

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.7 (stable) 

**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**
Homepage

**List of activated apps:**

Enabled:
  - activity: 2.1.4
  - files: 1.2.1
  - files_pdfviewer: 0.7.1
  - files_sharing: 0.7.0
  - files_trashbin: 0.7.0
  - firstrunwizard: 1.1
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - files_texteditor
  - files_versions
  - files_videoviewer
  - gallery
  - notifications
  - user_external
  - user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "*private*",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "*private*"
        ],
        "datadirectory": "*private*",
        "overwrite.cli.url": "*private*",
        "dbtype": "mysql",
        "version": "8.2.7.1",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 1048576000,
        "cron_log": true,
        "installed": true,
        "default_language": "de",
        "defaultapp": "files",
        "trashbin_retention_obligation": "7, auto",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "mail_from_address": "*private*",
        "mail_smtpmode": "smtp",
        "mail_domain": "*private*",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "localhost",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### Web server error log
See above

**Comment by PVince81** [comment]
Weird...

@owncloud/sharing @owncloud/filesystem

**Comment by PVince81** [comment]
In OC < 9 there were entries created in oc_appconfig for every share by share id. The entries existed to tell the future setupFS that an etag propagation for these shares needs to be done. This is used to avoid propagating etags right away to all possible recipients because it would be slow.

Now if there is a duplicate entry error it is likely that two files that were uploaded in parallel both inserted the same entry at exactly the same time into the database and only one won. Why are they inserting and not updating ? Probably because before inserting they both first checked the database if the entry exists, but it didn't exist.

This error can be ignored as one of the entries will still exist in the database and propagation will work correctly.

You might want to upgrade to 9.0 where etag propagation was improved and doesn't require such mechanism any more.
