### ISSUE TITLE
 The problem with upgrading to 9.1.0

### ISSUE THREAD

**Issue by kkeker** [owncloud/core#25635]
### Steps to reproduce
1. "apt-get update && apt-get upgrade -y" to update the system and owncloud from the official repository.
2. After that I went to her page ownclod and saw a that the system is in a the stage of of renovation, but this page has not disappeared.
3. Half an hour later I restarted the system, but the message is gone.
4. I tried to update via the link /updater/ creating the necessary secret.
5. I saw a message: [GuzzleHttp\Exception\RequestException] 
 cURL error 60: SSL certificate problem: self signed certificate 
6. I found this issue https://github.com/owncloud/richdocuments/issues/35 and added a self-signed certificate to the end of the file owncloud/resources/config/ca-bundle.crt but the message of the paragraph 5 appears still!

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
cat /etc/issue
Ubuntu 15.10 \n \l

**Web server:**
apache2ctl -v
Server version: Apache/2.4.12 (Ubuntu)
Server built:   Jul 15 2016 15:32:10

**Database:**
mysql -V
mysql  Ver 14.14 Distrib 5.6.31, for debian-linux-gnu (x86_64) using  EditLine wrapper

**PHP version:**
php -v
PHP 5.6.11-1ubuntu3.4 (cli)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
9.1.0

**Updated from an older ownCloud or fresh install:**
Upgrading from 9.0.2.2

**Where did you install ownCloud from:**
Official owncloud repository for Ubuntu.

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

sudo -u www-data php occ app:list
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_antivirus: 0.8.0.1
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - galleryplus: 15.1.0
  - mail: 0.5.2
  - music: 0.3.11
  - notes: 2.0.1
  - notifications: 0.2.3
  - ojsxc: 3.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.9.1
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - pdflintview
  - user_external
  - user_ldap

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

sudo -u www-data php occ config:list system
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocfzrovdiec5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXXXXXXXXX:8443"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/XXXXXXXXX:8443\/",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "maintenance": true
    }
}

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

local FS, LXC-container

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

Google Chrome
**Operating system:**

Windows 10 64-bit

#### Web server error log
82.204.146.206 - k.keker [28/Jul/2016:14:40:49 +0300] "GET /status.php HTTP/1.1" 200 2616 "-" "Mozilla/5.0 (Windows) mirall/2.2.2 (build 6192)"
82.204.146.206 - k.keker [28/Jul/2016:14:40:49 +0300] "PROPFIND /remote.php/webdav/ HTTP/1.1" 503 886 "-" "Mozilla/5.0 (Windows) mirall/2.2.2 (build 6192)"
82.204.146.206 - - [28/Jul/2016:14:40:54 +0300] "GET /status.php HTTP/1.1" 200 1038 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
82.204.146.206 - - [28/Jul/2016:14:41:14 +0300] "GET /status.php HTTP/1.1" 200 1038 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
82.204.146.206 - k.keker [28/Jul/2016:14:41:21 +0300] "GET /status.php HTTP/1.1" 200 2616 "-" "Mozilla/5.0 (Windows) mirall/2.2.2 (build 6192)"
82.204.146.206 - k.keker [28/Jul/2016:14:41:21 +0300] "PROPFIND /remote.php/webdav/ HTTP/1.1" 503 886 "-" "Mozilla/5.0 (Windows) mirall/2.2.2 (build 6192)"
82.204.146.206 - - [28/Jul/2016:14:41:34 +0300] "GET /status.php HTTP/1.1" 200 1038 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
82.204.146.206 - k.keker [28/Jul/2016:14:41:53 +0300] "GET /status.php HTTP/1.1" 200 2616 "-" "Mozilla/5.0 (Windows) mirall/2.2.2 (build 6192)"
82.204.146.206 - k.keker [28/Jul/2016:14:41:53 +0300] "PROPFIND /remote.php/webdav/ HTTP/1.1" 503 886 "-" "Mozilla/5.0 (Windows) mirall/2.2.2 (build 6192)"
82.204.146.206 - - [28/Jul/2016:14:41:54 +0300] "GET /status.php HTTP/1.1" 200 1038 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
82.204.146.206 - - [28/Jul/2016:14:42:14 +0300] "GET /status.php HTTP/1.1" 200 1038 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
82.204.146.206 - k.keker [28/Jul/2016:14:42:25 +0300] "GET /status.php HTTP/1.1" 200 2616 "-" "Mozilla/5.0 (Windows) mirall/2.2.2 (build 6192)"
82.204.146.206 - k.keker [28/Jul/2016:14:42:25 +0300] "PROPFIND /remote.php/webdav/ HTTP/1.1" 503 886 "-" "Mozilla/5.0 (Windows) mirall/2.2.2 (build 6192)"
82.204.146.206 - - [28/Jul/2016:14:42:34 +0300] "GET /status.php HTTP/1.1" 200 1038 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
82.204.146.206 - - [28/Jul/2016:14:42:54 +0300] "GET /status.php HTTP/1.1" 200 1038 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
82.204.146.206 - k.keker [28/Jul/2016:14:42:57 +0300] "GET /status.php HTTP/1.1" 200 2616 "-" "Mozilla/5.0 (Windows) mirall/2.2.2 (build 6192)"
82.204.146.206 - k.keker [28/Jul/2016:14:42:57 +0300] "PROPFIND /remote.php/webdav/ HTTP/1.1" 503 886 "-" "Mozilla/5.0 (Windows) mirall/2.2.2 (build 6192)"
82.204.146.206 - - [28/Jul/2016:14:43:14 +0300] "GET /status.php HTTP/1.1" 200 2611 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
82.204.146.206 - k.keker [28/Jul/2016:14:43:29 +0300] "GET /status.php HTTP/1.1" 200 2616 "-" "Mozilla/5.0 (Windows) mirall/2.2.2 (build 6192)"
82.204.146.206 - k.keker [28/Jul/2016:14:43:29 +0300] "PROPFIND /remote.php/webdav/ HTTP/1.1" 503 886 "-" "Mozilla/5.0 (Windows) mirall/2.2.2 (build 6192)"
82.204.146.206 - - [28/Jul/2016:14:43:34 +0300] "GET /status.php HTTP/1.1" 200 1038 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
82.204.146.206 - - [28/Jul/2016:14:43:54 +0300] "GET /status.php HTTP/1.1" 200 1038 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36"
82.204.146.206 - k.keker [28/Jul/2016:14:44:01 +0300] "GET /status.php HTTP/1.1" 200 2616 "-" "Mozilla/5.0 (Windows) mirall/2.2.2 (build 6192)"
82.204.146.206 - k.keker [28/Jul/2016:14:44:01 +0300] "PROPFIND /remote.php/webdav/ HTTP/1.1" 503 886 "-" "Mozilla/5.0 (Windows) mirall/2.2.2 (build 6192)"

Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
[owncloud.txt](https://github.com/owncloud/core/files/388272/owncloud.txt)

Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Thanks for the detailed report, but I don't understand what issue you are having and what you are trying to achieve.

Also I see that you are trying to update with Debian packages, which is fine. Don't use the "updater" app as it's not compatible with distro packages. This app shouldn't be bundled with the distro packages. If it is, then it's a packaging issue.

CC @jnweiger

**Comment by kkeker** [comment]
The problem is that the usual update packages from a repository destroyed a working product. Now I always see a message about updating the web.

**Comment by kkeker** [comment]
How can I recover the system without losing data?

**Comment by jnweiger** [comment]
@kkeker can you send us a screenshot please? i am not sure what you are seeing.

**Comment by kkeker** [comment]
I performed a standard update via apt-get upgrade and now I see it all the time http://take.ms/oxgsU service stopped working.

**Comment by jnweiger** [comment]
The screenshot shows normal behaviour after package update. All package updates trigger maintenance mode and remain in maintenance mode. It is expected that an admin reviews the success and then runs occ maintenance:mode --off to resume normal operation.

**Comment by kkeker** [comment]
Thank you!

The problem was solved two commands:
occ maintenance:mode --off
occ upgrade

**Comment by PVince81** [comment]
related topic: https://central.owncloud.org/t/config-switch-to-decide-in-which-mode-oc-goes-after-a-successful-occ-upgrade/1754
