### ISSUE TITLE
isv:ownCloud:community owncloud should redirect to owncloud.org

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#25637]
Currently we have version 8.1.x at https://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud with no indication that there are newer versions available.

This is an important entry point, as an attempt of installing owncloud on Ubuntu_14.04 points there:
![u](https://cloud.githubusercontent.com/assets/1108546/17212472/d27454ee-54cf-11e6-8cce-349c4f6d5399.png)

The correct new location is
  https://download.owncloud.org/download/repositories/stable/owncloud/

Possible improvements:
- Put dummy packages there, similar to the Ubuntu upstream package, with a message, refering to the new location
- Forward the new location to Ubuntu upstream
- Check with SUSE OBS team, if it is possible to include a message in the autogenerated download page.

**Comment by dragotin** [comment]
what can I do about this?

**Comment by PVince81** [comment]
is this still an issue @jnweiger @crrodriguez ?

**Comment by crrodriguez** [comment]
Other than documenting and providing a clear download URL to current releases..nothing to do for now here.
