### ISSUE TITLE
Update 9.0.4 --> 9.1.0

### ISSUE THREAD

**Issue by hitam4450** [owncloud/core#25632]
Hi, updating from 9.0.4 (stable) to OC 9.1.0 is only available, if one choose the **"beta"** channel, no upgrade on the stable and production possible!

Bug or feature ??

regards, hitam4450

**Comment by RealRancor** [comment]
> feature ??

As always after each major release. You should be long enough in this community to know that major releases have a delay until they are made available as a stable release via the updater.

**Comment by hitam4450** [comment]
@RealRancor: Thank you for your reminder. I kinow, that it takes a "few" days, until a major release will be made available by the updater! However, until now a **stable release like 9.1.0**  was **NOT** available on the beta channel. It is suppose to be available on the **Stable"** instead, this is **NOT** the case **NOW!**

regards, hitam4450

**Comment by RealRancor** [comment]
Then be happy that you get this major release earlier then the usual 1 month after the release in the beta channel

**Comment by hitam4450** [comment]
on https://owncloud.org/changelog/ the release 9.1 is **NOT** labeled as beta!

regards, hitam4450

**Comment by RealRancor** [comment]
> on https://owncloud.org/changelog/ the release 9.1 is NOT labeled as beta!

Still the "beta" channel is a way better (especially for impatient users) then "stable". To fill the gap between "stable" (which is currently 9.0.4 from my PoV) and a new major release (like 9.1.0) i have suggested https://github.com/owncloud/core/issues/25633

I think you can close here and see if https://github.com/owncloud/core/issues/25633 will be accepted.
