### ISSUE TITLE
Upgrade Issue

### ISSUE THREAD

**Issue by queencity13** [owncloud/core#25640]
I manually upgraded my OwnCloud server to 8.1.9 yesterday which put my server into maintenance mode. It's still showing maintenance mode this morning and when I remove the maintenance mode I get start update in my web browser. I had to upgrade my php to php5 which I did before trying to upgrade my OwnCloud server. I've restarted my php services and rebooted the server itself. In the web browser I click the update button and I then get an error message asking me to report the issue. I've attached a screenshot of the error. Please advise on how to proceed.

![screen shot 2016-07-28 at 9 46 18 am](https://cloud.githubusercontent.com/assets/462672/17214684/258b4c8c-54a8-11e6-8fbc-9b13d32b8449.png)

![screen shot 2016-07-28 at 9 42 16 am](https://cloud.githubusercontent.com/assets/462672/17214653/ff1e8816-54a7-11e6-87fe-8bf7d1c7e389.png)
![screen shot 2016-07-28 at 9 45 10 am](https://cloud.githubusercontent.com/assets/462672/17214652/ff1aced8-54a7-11e6-993c-eb14d288fc04.png)

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
https://central.owncloud.org/t/updates-between-multiple-major-versions-are-unsupported/815
