### ISSUE TITLE
Federated share from 8.2 to 9.1 does not allow resharing - already shared

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#25649]
### Steps to reproduce
1. User1 (server1 v8.2) shares a folder with User2 (server2 v9.1) 
2. User2 (server2 v9.1) accept the share
3.  User2 (server2 v9.1) reshares the folder with user3 (server3) (no matter the server3 version)
### Expected behaviour

User2 (server2 v9.1) can reshare
### Actual behaviour

User2 (server2 v9.1) can not reshare, receiving the following:

File is already shared with user@server
### Server configuration

server1: 
{"installed":true,"maintenance":false,"version":"8.2.6.2","versionstring":"8.2.6","edition":"Enterprise"}

server2:
{"installed":true,"maintenance":false,"version":"9.1.0.15","versionstring":"9.1.0","edition":"Enterprise"}

Traces in server2:

`{"reqId":"u\/fOD4W9LwdryEAyw7zG","remoteAddr":"xxx.xxx.xxx.xxx","app":"core","message":"Exception while scanning storage \"shared::f7932ea0b4bc3359323e329bbfd3edf3\": Sabre\\HTTP\\ClientHttpException: Unauthorized","level":3,"time":"2016-07-29T11:38:50+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"user1"}`

**Comment by PVince81** [comment]
Can you post the exact user names and user strings you used when sharing ?
For federated shares, the only check done to see if a share already exists is on the federated id (like user1@server.owncloud.com)

**Comment by jesmrec** [comment]
The usernames i use are user1, user2... and the federated id is like the one you posted (user@server)

A couple of screenshots to clarify:

When the sharee tries to reshare the folder "Mypics":

![screen shot 2016-08-10 at 09 52 53](https://cloud.githubusercontent.com/assets/14894746/17546107/cbe0f41e-5ee0-11e6-80db-51f7eb27172c.png)

The error message shows that it is already shared but it is not:

![screen shot 2016-08-10 at 09 53 18](https://cloud.githubusercontent.com/assets/14894746/17546123/e3987fdc-5ee0-11e6-8afa-05f8b135d92d.png)

Only happens if the second sharee is also federated.

**Comment by PVince81** [comment]
Is this still reproducible with more recent versions ?

**Comment by jesmrec** [comment]
@PVince81 

I have checked the original scenario and the error does not happen.

So, we can close this.

**Comment by PVince81** [comment]
Thanks
