### ISSUE TITLE
Tasks not showing in IE11 and Microsoft Edge

### ISSUE THREAD

**Issue by Dennis1993** [owncloud/core#25643]
### Steps to reproduce
1. install a fresh owncloud 9.1.0
2. activate the tasks app
3. insert a new Task
4. refresh the page and all entries not shown

### Expected behaviour
Show me my tasks

### Actual behaviour
Tasks not shown

### Server configuration
**Operating system**:
Apache 2.4

**Web server:**
all-inkl.com

**Database:**
MySQL 5.6

**PHP version:**
7.0.8

**ownCloud version:** (see ownCloud admin page)
9.1.0

**Updated from an older ownCloud or fresh install:**
fresh installation

**Where did you install ownCloud from:**
owncloud

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**
 Deleted files 
 Mail Template Editor 
Notifications
 PDF Viewer 
 Share Files 
 Text Editor 
 Update notification 
Versions
 Video player 
Calendar
Tasks

**The content of config/config.php:**
Default, no changes!

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
IE11, Edge
With Firefox it works and Safari on iPhone with iOS 9.3.3

**Operating system:**
Windows 10 and iOS

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Exception: {"Message":"HTTP\/1.1 415 Unsupported Media Type","Exception":"Sabre\\DAV\\Exception\\ReportNotSupported","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/www\/htdocs\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/www\/htdocs\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#3 \/www\/htdocs\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/www\/htdocs\/cloud\/apps\/dav\/lib\/Server.php(169): Sabre\\DAV\\Server->exec()\n#5 \/www\/htdocs\/cloud\/apps\/dav\/appinfo\/v2\/remote.php(29): OCA\\DAV\\Server->exec()\n#6 \/www\/htdocs\/cloud\/remote.php(164): require_once('\/www\/htdocs\/clo...')\n#7 {main}","File":"\/www\/htdocs\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","Line":719,"User":"Dennis1993"}

XMLReader::XML(): Empty string supplied as input at /www/htdocs/cloud/3rdparty/sabre/xml/lib/Service.php#116
```

![unbenannt](https://cloud.githubusercontent.com/assets/1473674/17225618/0471d1e8-5506-11e6-8615-718d9a507b94.PNG)

**SAME PROBLEM IN CALENDAR APP!!! THE CALENDAR NOT LOADING!**
Look at this, please for screenshots: https://github.com/nextcloud/server/issues/457

**Comment by RealRancor** [comment]
@Dennis1993 Please note that the issue tracker of the the task app is located here:

https://github.com/owncloud/tasks/issues

Please re-open this issue there. For the calendar app IE/Edge is just not supported:

> We don't support Internet Explorer or Egde. Patches for IE8+ and Edge are accepted though.

https://github.com/owncloud/calendar#supported-browsers

Swtich to a sane browser like Firefox or Chromium and you won't have this issue.

**Comment by Dennis1993** [comment]
Oh, sorry. I do that, thank you! :)

**Comment by RealRancor** [comment]
@Dennis1993 You can close this issue on your own by hitting the "Close" button below this comment field.
