### ISSUE TITLE
Ubuntu 16.04 - owncloud-deps-php5 package

### ISSUE THREAD

**Issue by oserban** [owncloud/core#25659]
On Ubuntu 16.04 the owncloud-deps-php5 has not been upgraded to support php 7.0.
I manually configured everything with php 7.0 and it works, but this package fails to update.

**Comment by RealRancor** [comment]
@oserban On Ubuntu 16.04 you need to use owncloud-deps-php7.0 instead of the (obviously?) wrong owncloud-deps-php5

**Comment by oserban** [comment]
It was (obviously) my mistake, thank you for pointing that out. 

It is still very confusing that deps-php5 is still available when php7 is now default. 

This issue can be closed now, thanks.

**Comment by RealRancor** [comment]
@jnweiger Maybe it would make sense to remove the owncloud-deps-php5 from the 16.04 repositories? 

But when thinking about it it could be also possible that some users are still running PHP 5.x from a ppa for various reasons.

**Comment by oserban** [comment]
Considering that you need to setup a custom ppa for php5,  I would say that those users run a custom stack => they manage their own dependencies => they'll use owncloud-files only anyway

**Comment by oserban** [comment]
Tried to install the deps-php7.0 package, but owncloud still has a dependency on deps-php5 package  (see bellow). Currently, trying to install the 7.0 package creates a conflict. Here are the dependencies for the owncloud 9.1.0-1.1 package:

Package: owncloud
Version: 9.1.0-1.1
Architecture: all
Maintainer: Juergen Weigert <jw@owncloud.com>
Installed-Size: 9
Depends: owncloud-files (>= 9.1.0), owncloud-deps-php5 (>= 9.1.0) | owncloud-deps

@jnweiger Do you think this is something that can be fixed?

**Comment by jnweiger** [comment]
@oserban Please help me understand what should be fixed.
Are you saying that it is not possible to install owncloud-deps-php7.0 on your system? In case allowing a choice of owncloud-deps-php5 and owncloud-deps-php7.0 is a bad thing for you, a more specific example of wrong behaviour might be helpful to understand the situation. 
In general, I believe the choice operator in the control file is very helpful.

**Comment by oserban** [comment]
I upgraded my server to Ubuntu 16.04, php7.0 recently. Until then, the owncloud package has been installed with owncloud-deps-php5.
When I am trying to install owncloud-deps-php7.0 it says that the config files are already written by owncloud-deps-php5 and the install fails. When I am trying to remove owncloud-deps-php5 to install owncloud-deps-php7.0, it tries to uninstall the owncloud package as well, which I don't want ... 
So at the moment I am stuck with this configuration:
owncloud + owncloud-deps-php5
with a manual config of php7.0 and all its requirements. 

Hope this helps.

**Comment by jnweiger** [comment]
I see. Upgrading from Ubuntu 14.x or 15.x to 16.04 can cause this.

I am adding mutual Breaks: Replaces: and Conflicts: clauses to each of the pwncloud-deps-php* packages. Please check out if that solves your issue:

http://download.owncloud.org/download/repositories/9.1:/testing/owncloud

**Comment by oserban** [comment]
Sorry, I get the same error. The owncloud package is properly updated, but when I try to install owncloud-deps-php7.0 I get the same error. 

Unpacking owncloud-deps-php7.0 (9.1.0-2.1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-deps-php7.0_9.1.0-2.1_all.deb (--unpack):
 trying to overwrite '/etc/apache2/conf-available/owncloud.conf', which is also in package owncloud-deps-php5 9.1.0-1.1

Hope this helps.

**Comment by oserban** [comment]
I fixed the issue, not by using your workaround, but by manually removing the owncloud-deps-php5 package.

Mini-tutorial:
1. set the owncloud-files to manual install in apt (this will prevent uninstalling the package while removing dependencies)
```bash
apt-get install owncloud-files
```
2. remove owncloud-deps-php5 (don't purge and don't force). If something looks fishy do not continue ...
```bash
apt-get remove owncloud-deps-php5
```
This should remove owncloud-deps-php5 and owncloud packages. owncloud is safe to remove since it is a metapackage only and you are not purging any settings. 

3. Install owncloud-deps-php7.0
```bash
apt-get install owncloud-deps-php7.0 owncloud 
```

@jnweiger I think owncloud is a dangerous package in its current form :-) What I actually mean is that users should be instructed to install owncloud-files and owncloud-deps-phpXX in the tutorial, rather than one package fixes all version ...

**Comment by jnweiger** [comment]
Thanks for the manual solution. 
The ubuntu 16.04 packages in :testing should behave correctly in cases like yours. also avoiding the 'dangerous' suggestion to remove owncloud.


Am 31. Juli 2016 17:22:36 MESZ, schrieb "Ovidiu Șerban" <notifications@github.com>:
>I fixed the issue, not by using your workaround, but by manually
>removing the owncloud-deps-php5 package.
>
>Mini-tutorial:
>1. set the owncloud-files to manual install in apt (this will prevent
>uninstalling the package while removing dependencies)
>```bash
>apt-get install owncloud-files
>```
>2. remove owncloud-deps-php5 (don't purge and don't force). If
>something looks fishy do not continue ...
>```bash
>apt-get remove owncloud-deps-php5
>```
>This should remove owncloud-deps-php5 and owncloud packages. owncloud
>is safe to remove since it is a metapackage only and you are not
>purging any settings. 
>
>3. Install owncloud-deps-php7.0
>```bash
>apt-get install owncloud-deps-php7.0 owncloud 
>```
>
>@jnweiger I think owncloud is a dangerous package in its current form
>:-) What I actually mean is that users should be instructed to install
>owncloud-files and owncloud-deps-phpXX in the tutorial, rather than one
>package fixes all version ...
>
>
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/core/issues/25659#issuecomment-236435905

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by oserban** [comment]
Unfortunately, it does not solve the problem. Tested after you told me to try again (approx 22h ago) and it did not work.
