### ISSUE TITLE
Remove trailing whitespaces

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#25651]
## Problem:

Trailing whitespace in folder and file names are not supported by some OS. And mostly they are used by accident. So syncing stops, produces errors, ... or creates problems during decryption (https://central.owncloud.org/t/encryption-decryption-and-sharing-mess/1110).
## Solution:

Remove trailing whitespace (rename files or folders
## Question:

Is there a legitimate use for trailing whitespaces?

**Comment by PVince81** [comment]
The question is when and where to remove them.

One thing we cannot do is have one name "X" in oc_filecache but on-disk have another name "Y".
Also we cannot have a file "Z" on the client-side but have it mapped to a name "X".
This is because we'd need a mapping table that maps the file as seen by the client or Webdav to the real file name.

I also don't think we can let the sync client automatically rename files on the client side ?

**Comment by PVince81** [comment]
The easiest way I guess would be to blacklist those files, but the client/server would need to be more verbose about such files not being synced.

**Comment by tflidd** [comment]
If such files are blacklisted, there must be a very good verbose message. We had some support requests and sometimes it is very difficult to see if there is a whitespace.

What I thought: If after the upload, the new file contains a trailing whitespace, the server renames the file to the non-whitespace version. Only if there is an existing file of that name, there should be an error.

**Comment by PVince81** [comment]
@tflidd if the server renames the file by trimming the whitespaces, then the sync client will redownload it as it will count as a rename. The question is whether this is ok for users.

**Comment by RealRancor** [comment]
> The question is whether this is ok for users.

I doubt that. People probably will complain about this behavior

**Comment by PVince81** [comment]
Hmmm, but in general a trailing whitespace should not hurt, unless there are parts of the OC code that trim it when they shouldn't. Maybe we should rather focus on fixing the actual issues.

**Comment by RealRancor** [comment]
Quoting from: https://github.com/owncloud/client/issues/3902#issuecomment-144202364

> Leading/trailing whitespace is generally a user typo anyway, which can be easily trimmed.
>
> File and folder names shouldn't end with spaces or periods on windows:

> > Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".
>
> https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#naming_conventions
>
> This also means "foobar..." is not an acceptable folder name on windows.

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/issues/28164
