### ISSUE TITLE
Bring back simpler UI

### ISSUE THREAD

**Issue by skironDotNet** [owncloud/core#25658]
I noticed that in new version of OC there is one "plus" the "+" button, you have to click it then you can click upload. Who got that idea? I mean how is this is an improvement to always click twice?
There is plenty of room on the bar an "new" and "upload" icons were just fine.
I know I can modify html/css myself but then updates will bring it back, any options/config/settings to setup/customize buttons

Thanks!

**Comment by SergioBertolinSG** [comment]
This is a debate for https://central.owncloud.org/ not here. Please open it there with Development tag.

**Comment by SergioBertolinSG** [comment]
I've open it already: https://central.owncloud.org/t/separate-creation-buttons-on-files-view/1315

**Comment by skironDotNet** [comment]
Thanks!
