### ISSUE TITLE
Trying to replace owncloud 8.1 with 9.1

### ISSUE THREAD

**Issue by amca01** [owncloud/core#25661]
Now I know I can't do this update directly; but as it is I've cleared out my original `/var/www/owncloud` directory (aside from the `data` and `config` directories), and unzipped owncloud 9.1 into it.  I've backed up the `data` and `config` directories, as well as the owncloud MySQL database to elsewhere on the system - which is Ubuntu 14.04 server.

However, of course when I attempt to open up owncloud in my browser I can't, as it won't allow me to update between two major versions..  As I see it I have two choices:

1. Put my initial owncloud 8.1 back again and upgrade in stages until I reach the current version.
2. Wipe all of owncloud from my system (except for my backups!) and install 9.1 as though I was doing it for the first time.

Any suggestions?

**Comment by RealRancor** [comment]
@amca01 This is a bugtracker which shouldn't be used for such setup and installation questions. Please close here and use https://central.owncloud.org/ for it. There you will also find a FAQ explaining what to do:

https://central.owncloud.org/t/updates-between-multiple-major-versions-are-unsupported/815
