### ISSUE TITLE
SQl Error SQlSTATE[28000] [1045]

### ISSUE THREAD

**Issue by hitam4450** [owncloud/core#25664]
Hi to All,

I installed OC 9.1 from scratch and completely new.
At the last page of wizard
I entered the admin name & password, the same user name for mysql, the root password for mysql, database i named it owncloud and at  localhost.
After pressing finishing installation I received the following error message:
SQlSTATE[28000] [1045] access denied for user@localhost (using password ; YES)

I took from a list of ODBC error Codes

28000             Invalid authorization specification                                       SQLBrowseConnect
                                                                                                                    SQLConnect
                                                                                                                    SQLDriverConnect

Sorry, i am not a mysql expert!

What went wrong and how resolve it ??

Many, many thanks in advance!

regards, hitam4450

**Comment by RealRancor** [comment]
@hitam4450 Please don't use the bugtracker for support question. Instead stick on your posted thread at central:

https://central.owncloud.org/t/sql-error-sqlstate-28000-1045/1254

**Comment by hitam4450** [comment]
Hi RealRancor,

I found somebodies similar error message and at that time you suggested to report it to Github Bugtracker. In the meantime I solved the problem!

regards, hitam4450
