### ISSUE TITLE
failed to change the data directory

### ISSUE THREAD

**Issue by zhonger** [owncloud/core#25660]
### Expected behaviour
failed to move data directroy to other directory

### Actual behaviour
1.config/config.php change
2.cp -rf data/* /home/data/cloud

### Server configuration
**Operating system**:ubuntu server 14.04 LTS

**Web server:** nginx+apache

**Database:** mysql 5.6

**PHP version:** 5.6.7

**ownCloud version:** (see ownCloud admin page) 9.1

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** owncloud.org

**Signing status (ownCloud 9.0 and above):**

```
文件目录 (/home/data/cloud) 无效
请确保文件根目录下包含有一个名为“.ocdata”的文件。
```

**List of activated apps:**

```
none
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocwujrkpf13w',
  'passwordsalt' => '******',
  'secret' => '******',
  'trusted_domains' => 
  array (
    0 => 'yun.shu.aixinwu.org',
  ),
  'datadirectory' => '/home/data/cloud',
  'overwrite.cli.url' => 'http://yun.shu.aixinwu.org',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'dbname' => 'yun',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '*******',
  'dbpassword' => '******',
  'logtimezone' => 'UTC',
  'installed' => true,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Comment by RealRancor** [comment]
@zhonger Currently the info what failed is completely missing. You should also note that moving the datadir after the installation is not supported:

https://github.com/owncloud/documentation/issues/2303

For now its the best to start from scratch and choose the new datadir during the installation.

**Comment by jnweiger** [comment]
I did not try, but in theory, a symbolic link should be able to solve the issue. It allows owncloud to see the datadir where it is expected, and still have it physically at the desired external storage.

My idea is roughly:

1. do **not** change config/config.php 
2. mv -rf data/* /home/data/cloud
3. rmdir data
4. ln -s /home/data/cloud data

**Comment by zhonger** [comment]
@jnweiger According to your method , I have a try. But it comes the same error notes 
```
文件目录 (/home/wwwroot/yun.shu.aixinwu.org/data) 无效
请确保文件根目录下包含有一个名为“.ocdata”的文件。
```

**Comment by RealRancor** [comment]
@zhonger You can't expect that people translating this error into english.

**Comment by zhonger** [comment]
I'm so sorry.Here is the error in English.
```
The data directory(/home/wwwroot/yun.shu.aixinwu.org/data) is invalid.
Please check that there is a file '.ocdata' in the data root directory.
```

**Comment by RealRancor** [comment]
I think we should continue to discuss this in https://central.owncloud.org/ as this is unlikely a bug in ownCloud but more a setup question.

**Comment by zhonger** [comment]
ok

**Comment by RealRancor** [comment]
@zhonger As you got this solved according to your forum post:

https://central.owncloud.org/t/cant-create-or-write-into-the-data-directoy-home-data-cloud/1252

you can close here by hitting the Close button below the comment field.
