### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/core#2566]
Info: 
did an update to stabe5 today and i started to see lots of:
error while running hook (\OC\Files\Cache\Updater::renameHook): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '718-98a1b40e4d02c64b650fdf9b6f5ed87d' for key 'fs_storage_path_hash' while the clients were connecting with webdav.

fs_storage_path_hash' was obviously different for many of the entries in the log.
Is this exact case i've found the entry in the table oc_filecache:

*************************** 1. row ***************************
  storage: 718
     path: files/test/test4/test-blx.bib
path_hash: 98a1b40e4d02c64b650fdf9b6f5ed87d
*************************** 2. row ***************************

This file seems to have been uploaded fine and this is obviously the case with other files which trigger this error in the log.

This is very critical and i hope the devs will give it high priority!

Thank you!

@schiesbn @icewind1991 @MTGap

**Comment by DeepDiver1975** [comment]
moving off oc8 as we are still analyzing the issue - nothing to do for oc8

**Comment by cdamken** [comment]
@icewind1991 about your question: https://github.com/owncloud/core/issues/2566#issuecomment-63059144

S3-ownCloud\Shared\owncloud\support\github-issues\core\2566\Another-Query-Output.txt

**Comment by butonic** [comment]
also adding green ticket

**Comment by cdamken** [comment]
Any news about the Another-Query-Output.txt?

**Comment by PVince81** [comment]
We might have a way now to reproduce this more consistently: https://github.com/owncloud/core/issues/13934
Should make it possible to finally debug this.

**Comment by DeepDiver1975** [comment]
> We might have a way now to reproduce this more consistently: #13934

let's close this one in favor of #13934
