### ISSUE TITLE
A log appears in owncloud.log file when we change the 'Available for' field for a mountpoint

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25687]
### Steps to reproduce
1. In admin view, set log level to fatal issues only
2. Configure an external storage mountpoint (SFTP)
3. Change the value in 'Available for' field
### Expected behaviour

No log should be shown
### Actual behaviour

A log is written in owncloud.log 
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.6

**ownCloud version:**

"9.2.0.1","versionstring":"9.2.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
Yes, SFTP

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"st4HrgQrp0uBcAWnwxT7","remoteAddr":"82.159.139.58","app":"PHP","message":"usort(): Array was modified by the user comparison function at \/opt\/owncloud\/lib\/private\/User\/Manager.php#255","level":3,"time":"2016-08-02T15:58:54+00:00","method":"GET","url":"\/index.php\/apps\/files_external\/applicable?pattern=a&limit=30&offset=0&_=1470153452274","user":"admin"}
```
### Client configuration

**browser**

**Comment by PVince81** [comment]
can't find this code in OC 10, closing. Please reopen if this still happens
