### ISSUE TITLE
Deletion of groups of files including hidden files doesn't erase all the files.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#25680]
### Steps to reproduce:

1. Create a folder called FOLDER.
2. Upload 6 files, being 2 of them hidden files (.filename).
3. Select all 6 files.
4. Click in delete button to remove all of them.

### Expected behaviour:
6 files are deleted.

### Actual behaviour
4 files are deleted, hidden ones remain.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0.9

**ownCloud version:** (see ownCloud admin page)
Current master
{"installed":true,"maintenance":false,"version":"9.2.0.1","versionstring":"9.2.0 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```


```

### Client configuration

Chrome, Safari

**Comment by PVince81** [comment]
Will look into it as part of 9.1.1 or 9.1.2

**Comment by PVince81** [comment]
WIP PR here https://github.com/owncloud/core/pull/25846

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/25856
