### ISSUE TITLE
Unable to connect to Windows 2012R2 Active Directory / LDAP error

### ISSUE THREAD

**Issue by ctg-owncloud** [owncloud/core#25685]
### Steps to reproduce
1.  Open ownCloud Admin page
2. Select LDAP
3. Enter the Active Directory server IP address
4. Select DETECT PORT
5. Error occurs - "Please specify the port, it could not be auto-detected"
6. Connected to Port 389 on Active Directory server by using Telnet and its successful - but ownCloud doesnt connect to Active Directory

### Expected behaviour
On our Ubuntu installations, when we detect port, Port 389 is entered in this box.

### Actual behaviour
On our CentOs 7 installation, we are unable to detect the port and we are unable to detect the Base DN - Could not detect Base DN, please enter it manually.

### Server configuration
**Operating system**:
OC - CentOS Linux release 7.2.1511 (Core) 
AD - Windows 2012R2 Standard

**Web server:**
Server version: Apache/2.4.6 (CentOS)

**Database:**
5.5.47-MariaDB 

**PHP version:**
PHP 5.6.24 (cli) (built: Jul 21 2016 14:27:54)

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.1.0 (stable)

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
Downloaded from owncloud.org website

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Not Found

The requested URL /index.php/settings/integrity/failed was not found on this server.

**List of activated apps:**
LDAP
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
sudo: unable to initialize policy plugin

**The content of config/config.php:**
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'ocvulmlfijy9',
  'passwordsalt' => 'xPb00tYK1IqFnZE7gKzQd3S1Vi6q7D',
  'secret' => '9PrIjXr4tktxApxVy41pb66hZTBkKa5wa6ZDW6X2F5zEoFaO',
  'trusted_domains' =>
  array (
    0 => '192.168.150.169',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://192.168.150.169/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '9.1.0.15',
  'dbname' => 'owncloud_db',
  'dbhost' => '192.168.150.169',
  'dbtableprefix' => 'oc_',
  'logtimezone' => 'UTC',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
);
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No, cant get to that stage as yet

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes = Active Directory

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
I guess this is more suitable to ask this in the forum - https://central.owncloud.org/ - THX
