### ISSUE TITLE
New chunking: etags on the final MOVE

### ISSUE THREAD

**Issue by ogoffart** [owncloud/core#25682]
The MOVE command of the .file from the uploads to the taget  folder does not return the new etag as a header  (ETag, or better, OC-ETag)
This is required so the client know the etag for which a specific file is uploaded.

Also, if we specify the If-Match header of the expected destination etag, we get a 412 precondition failed when the etag match

**Comment by DeepDiver1975** [comment]
> Also, if we specify the If-Match header of the expected destination etag, we get a 412 precondition failed when the etag match

where do you get the expected etag from?
etags are server generated - or am I missing anything?

**Comment by ogoffart** [comment]
The expected etag comes from the client database,or the previous PROPFIND. 
The client sees that the server has the file.txt with the etag "abcd", that's the same as the one in the DB and deduce that the file has not been modified on the server.  The client sees that the local file has een modified. It should upload the file, no conflict.
However, if at the same time, another client uploads or change the file, we should have a conflict situation.
By checking  the if-match, the server can make sure that no other client has changed the file in between the last PROPFIND and the actual MOVE

**Comment by DeepDiver1975** [comment]
I see - it's the etag of the previous destination. I'll have a look

**Comment by DeepDiver1975** [comment]
Hmmm ... the if match logic is only applied to the source of the MOVE request but not on the destination.

I guess we need to invent something on our own here ...

@dragotin

**Comment by DeepDiver1975** [comment]
- [ ] Missing if-match header on move
- [ ] add capability for new chunking

**Comment by PVince81** [comment]
I see merged PRs, is this solved or is there more to it ?

**Comment by DeepDiver1975** [comment]
> I see merged PRs, is this solved or is there more to it ?

we are done
