### ISSUE TITLE
Disable encryption when file size is large than 3GB (using object storage)

### ISSUE THREAD

**Issue by joeyjy** [owncloud/core#25697]
Hi OC team,

I'm using object storage to store all users' files, user will spend a lot of time to download a large file(e.g. ISO file).

Normally, a downloading request will make the server firstly get the file from object storage, then decrypt that file, finally send the file to user, right?

I know the decryption process doesn't cost much time, but encryption will make file size increase about 30%, it means downloading a 3GB file might actually cost time as much as downloading 3GB + 3GB*30%(from obj storage to owncloud server) + 3GB(from owncloud server to user client) data, am I right?

So wondering if I can modify a bit source code to make this happen? disable encryption when handling large file.
I have a 3 months PHP experience... If it isn't very complex, can you point out which files I should working on, thank you very much!

**Comment by RealRancor** [comment]
@joeyjy If you don't want to report a bug or request a feature then please use:

https://central.owncloud.org/c/development

for such questions.

**Comment by joeyjy** [comment]
@RealRancor Oh, I see, sorry for posting in wrong place
