### ISSUE TITLE
More specific link to documentation (large setups)

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#25699]
The update via webinterface is blocked for large setups and users are motivated to use manual upgrade procedure via terminal. The linked documentation doesn't really help, it should be more specific.

ref: https://central.owncloud.org/t/problem-with-owncloud-update/1355

Currently it links to:
http://doc.owncloud.org/server/9.0/go.php?to=admin-cli-upgrade
-> https://doc.owncloud.org/server/9.0/admin_manual/

but this would be better: https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/occ_command.html?highlight=occ#command-line-upgrade

I can't find the key `admin-cli-upgrade` in this list: https://github.com/owncloud/documentation/blob/master/go.php, so there is probably more "magic" going on ;-)

**Comment by RealRancor** [comment]
> I can't find the key admin-cli-upgrade in this list: https://github.com/owncloud/documentation/blob/master/go.php, so there is probably more "magic" going on ;-)

Nice catch, that needs to be added there: https://github.com/owncloud/documentation/issues/2556
