### ISSUE TITLE
Local Storage share

### ISSUE THREAD

**Issue by IvonneBurgos** [owncloud/core#25701]
Hello, I got an issue with a Local Storage. I mount a Local Storage for a group of users and it works, but I want to share it. I check the option 'Enable sharing', and when I try to share it, the option keeps loading and never ends
### Steps to reproduce
1. Create a local storage
2. Enable sharing option
3.Share it with another user

### Expected behaviour
Share the storage

### Actual behaviour
Keeps loading

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
PHP 5.5.9
**ownCloud version:** (see ownCloud admin page)
9.0.4
**Updated from an older ownCloud or fresh install:**
from 9.0 

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Comment by DeepDiver1975** [comment]
I'm already analysing this issue which has been reported many times already.
Also comments and Tags don't work.

**Comment by DeepDiver1975** [comment]
@SergioBertolinSG may I ask you to write an integration test for this?

````
  0. as user 1 mount local folder as 'Local'
   1. as user create a folder inside 'Local' named 'foo'
   2. as user 1 share 'Local' with user 2
   3. as user 2 share 'Local/foo' by link
   4. expect a link share to be returned

**Comment by DeepDiver1975** [comment]
same as https://github.com/owncloud/core/issues/25464

**Comment by DeepDiver1975** [comment]
@IvonneBurgos a fix is here - please help testing - https://github.com/owncloud/core/pull/25703

**Comment by IvonneBurgos** [comment]
Hello, thanks for your answer. I'm not a pro user and I dont understand how to fix the problem. I found the file and added the lines but I dont think that's how it works. 
But with that,I didnt fix the problem. I'm developing an app and it creates a folder with the name of the user into the Local Storage. And those folders are the ones, users may want to share later. After I added the lines, the folders already created were gone, they were in the Local Storage but didnt appear listed. 
Please explain me how to use the answer.
