### ISSUE TITLE
OwnCloud doesn’t work well with many images

### ISSUE THREAD

**Issue by dult** [owncloud/core#25704]
### Steps to reproduce

1) Have a folder with 6000 image files and over 24gb of data.
2) Search made from outside the folder shows image links that can be opened.
(search made from inside the folder only returns image links of images that had been scrolled to).
### Expected behaviour

Clicking/opening in new window should load the image for download.
### Actual behaviour

Server starts loading then freezes.
### Specs

CentOS 7.2 X86_64 Standard

Intel Xeon E3-1230
16GB RAM DDR3 ECC
2x 1TB SATA 3
RAID 1 Hardware

SQLite
PHP5.6

ownCloud 8.2.7 Stable

Fresh install from 8.2.

From ownCloud files.

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
Doesn't show nothing in chrome and firefox.

Activated apps.
Activity
Deleted files 
First Run Wizard 
Gallery
Mail Template Editor 
Notifications
PDF Viewer 
Provisioning API 
Share Files 
Text Editor 
Updater
Versions
Video Viewer 

<?php
$CONFIG = array (
  'instanceid' => '**_',
  'passwordsalt' => '**_',
  'secret' => '/**_',
  'trusted_domains' => 
  array (
    0 => '**_',
  ),
  'datadirectory' => '/home/**_/public_html/data',
  'overwrite.cli.url' => 'http://**_',
  'dbtype' => 'sqlite3',
  'version' => '8.2.7.1',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
);

**Are you using external storage, if yes which one: NO

**Are you using encryption: NO

**Are you using an external user-backend, if yes which one: NO
### Client configuration

Chrome, IE11, Firefox
Windows 10,
### Webserver log

[server.txt](https://github.com/owncloud/core/files/403681/server.txt)
### ownCloud log (data/owncloud.log)

[owncloud.txt](https://github.com/owncloud/core/files/403677/owncloud.txt)

**Comment by hodyroff** [comment]
Can you reproduce this with the newest version 9.1.0, please?

**Comment by dult** [comment]
I've updated my owncloud to 9.1.

It still can't open images when clicked in the folder with 6000 images.

What extra information is necessary?

**Comment by PVince81** [comment]
Does it also hang if you try opening the very first image inside the folder without scrolling down ?

If it's slow, then it means the gallery app (which is the one providing the popup image) maybe first tries to render all 6000 rows before opening the popup, which is likely to be slow.

**Comment by PVince81** [comment]
Note: it is likely a bug in the gallery app because that's the one that opens the slideshow preview.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
