### ISSUE TITLE
Undefined Offset php error in LoginController on login failure

### ISSUE THREAD

**Issue by kontaxis** [owncloud/core#25714]
### Steps to reproduce
1. Try to log in with an invalid password.
2. Check owncloud.log

### Expected behaviour
There should be no php errors in owncloud.log

### Actual behaviour
Owncloud.log contains the following errors:
Error PHP Invalid argument supplied for foreach() at /var/www/owncloud/core/templates/login.php#23
Error PHP Undefined offset: 1 at /var/www/owncloud/core/Controller/LoginController.php#117
Warning core Login failed: 'someuser' (Remote IP: 'x.y.z.w')

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** 9.1.0

**Updated from an older ownCloud or fresh install:** Upgraded from 9.0.4

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by scottysmart** [comment]
I'm also experiencing this issue from a clean deployment.

Version 9.1.0 of ownCloud. Exactly the same errors in the log file as mentioned in this article (in the Actual Behaviour section). Deployed either manually or via Softaculous with our web host. This only seems to have been an issue with ownCloud 9.1.0 in my experience with this so far.

The only difference is, after the initial setup, I cannot log in at all. I know I have the correct username and password for admin though am receiving the "Wrong Password" message when trying to sign in. This is what prompted me to look at the logs.

As I cannot log in, cannot provide signing status info. As is a new deployment, have not yet added any additional apps. Also, not using LDAP.

Hopefully this information helps in some way?
