### ISSUE TITLE
Storages for all the users are created even though they never logged in

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#25719]
### Steps to reproduce
1. Configure an LDAP with a lot of users
2. Navigate through the ownCloud admin account
### Expected behaviour

Only the storages for the admin user are created
### Actual behaviour

Storages for all the users are created

```
mysql> select count(*) from storages;
+----------+
| count(*) |
+----------+
|     3043 |
+----------+
```
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 9.1.0

**Updated from an older ownCloud or fresh install:** fresh install
### Notes:

https://github.com/owncloud/core/commit/391bc49dabb39e31739c849b83bb490cabf9da3d might be the cause. Not sure if this might include external storages.

**Comment by PVince81** [comment]
This is because you went to the users page and it fetched the avatar for the users...
Starting with 9.2 the avatars are stored elsewhere, so they don't require a home storage to be mounted/configured.

Please reopen if you still see this on master.
