### ISSUE TITLE
owncloud 9.1 checkbox to stay logged in does not work

### ISSUE THREAD

**Issue by covici** [owncloud/core#25716]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```Hi.  I was using 9.0.2 and things worked, after upgrading to 9.1.0 the checkbox to stay logged in does nothing, so every time I go to my owncloud I have to log in again.

I am using internet explorer 11 under windows 10.

**Comment by RealRancor** [comment]
@covici Please fill out the issue template. In the current state your reported issue is pretty useless

**Comment by covici** [comment]
Not sure what you need, steps to reproduce, just log in check the
checkbox and then logout and then log back in again.  Current behavior I
need to enter the user name and password, expected behavior that I get
logged in immediately.   Server is on Gentoo Linux kernel 4.4.12.  What
more do you need?

RealRancor <notifications@github.com> wrote:

> @covici Please fill out the issue template. In the current state your reported issue is pretty useless
> 
> ---
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/owncloud/core/issues/25716#issuecomment-238142412
> 
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by RealRancor** [comment]
@covici Everything whats needed is asked in the issue template you havn't filled out.

**Comment by covici** [comment]
I have edited my initial comment to include what you are asking.

**Comment by RealRancor** [comment]
@DeepDiver1975 Could you re-open here (users can't do that on their own) as additional infos were provided now.

**Comment by covici** [comment]
So has anyone worked on this -- its quite annoying to me, or is it fixed in a later version and if so which one?

**Comment by RealRancor** [comment]
@covici See https://github.com/owncloud/core/issues/26027
