### ISSUE TITLE
E-mail login fails when two users have the same e-mail address

### ISSUE THREAD

**Issue by kontaxis** [owncloud/core#25715]
### Steps to reproduce
1. Create two users with the same e-mail address in their profile. Alternatively update two existing users with the same e-mail address.
2. Try to log in using that e-mail address and either user's password.

### Expected behaviour
Two options:
a) make sure that e-mail addresses are unique. If we are going to treat them as user identifiers they need to be unique. Do not allow a second user to update his/her profile with an e-mail address already present in a different profile.
b) Given an e-mail address and a password find the correct user and log in. So if Alice and Bob have user@example.com as their e-mail address and their passwords are alice1 and bob1 then user@example.com:alice1 should access Alice's account and user@example.com:bob1 should access Bob's account.

I prefer (a) because (b) could lead to unauthorized access in an extreme case: Alice has password 123 and Bob has password 1234. Bob mistypes his password as 123 and accesses Alice's account because they share the same e-mail address.

### Actual behaviour
Login failure. The user gets back no explanation. This could lead to denial of service. A malicious user can update his profile with the victim's e-mail address. Then neither the malicious user not the victim will be able to log in with the e-mail address victim@example.com. Even if the victim tries to reset their password, the new password will not work either as long as it is is used in combination with the e-mail address.

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** 9.1.0

**Updated from an older ownCloud or fresh install:** Upgraded from 9.0.4

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
> a) make sure that e-mail addresses are unique. If we are going to treat them as user identifiers they need to be unique. Do not allow a second user to update his/her profile with an e-mail address already present in a different profile.

I prefer to go into this direction - once we have https://github.com/owncloud/core/issues/23558 this will work that way.

Until then my requirement for implementing this feature was to have only one user with one email address - as soon as two users have the same login will be denied.

So this currently works for my as designed.

Thanks for reporting this!
