### ISSUE TITLE
A log appears in owncloud.log file when create deleting a mountpoint that contains $user variable in the remote subfolder

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25721]
### Steps to reproduce
1. Configure an external mountpoint with the following configuration (e.g. wnd)
2. In Admin view, delete the mountpoint.

![screen shot 2016-08-08 at 12 24 19](https://cloud.githubusercontent.com/assets/10596560/17477825/c9aa854a-5d67-11e6-8656-ea40764b7b47.png)
### Expected behaviour

No log should be shown. 
### Actual behaviour

A log is written in owncloud.log
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.6

**ownCloud version:**

"9.2.0.1","versionstring":"9.2.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
Yes, WND

**Are you using encryption:** 
Yes

**Logs**

```
{"reqId":"aJITVXVGJ\/+h4sPkMRRW","remoteAddr":"82.159.139.58","app":"files_external","message":"Exception: \"Cannot compute storage id for deletion due to $user vars in the configuration\"","level":3,"time":"2016-08-08T10:51:10+00:00","method":"DELETE","url":"\/index.php\/apps\/files_external\/globalstorages\/3","user":"admin"}
```
### Client configuration

**browser**

Firefox

**Comment by PVince81** [comment]
Yes, this is intentional. We can't fix this.
