### ISSUE TITLE
warning messages in admin page

### ISSUE THREAD

**Issue by dddango** [owncloud/core#25729]
Hello!

### Steps to reproduce
1. login as admin
2. go to admin page
3. see warnings

### Expected behaviour
no warnings

### Actual behaviour
    The "X-Content-Type-Options" HTTP header is not configured to equal to "nosniff". This is a potential security or privacy risk and we recommend adjusting this setting.
    The "X-Frame-Options" HTTP header is not configured to equal to "SAMEORIGIN". This is a potential security or privacy risk and we recommend adjusting this setting.

http://i.imgur.com/NDXpmSE.png
See the image for more details on /var/www/owncloud/.htaccess. Is it not working or?

also my /etc/apache2/sites-enabled/configurefile.conf doesn't have same headers.
So I don't think it's double sending headers.

### Server configuration
**Operating system**:
ubuntu 16.04

**Web server:**
apache2

**Database:**
mySQL

**PHP version:**
PHP Version => 7.0.8-0ubuntu0.16.04.2

**ownCloud version:** (see ownCloud admin page)
9.1.0(stable)

**Updated from an older ownCloud or fresh install:**
Fresh Install

**Where did you install ownCloud from:**
deb http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**Comment by RealRancor** [comment]
@dddango Please close here and use https://central.owncloud.org/c/help/miscellaneous for such support questions.
