### ISSUE TITLE
Synology owncloud hazardous status (failed package migration from v6.x to v8.x)

### ISSUE THREAD

**Issue by farpet** [owncloud/core#25722]
### Steps to reproduce
1. Updating ownCloud to version 8.1.1, from v6.x
2. Exception: Updates between multiple major versions are unsupported. 
3. The update was unsuccessful

### Expected behaviour
Tell us what should happen : I expect migration successful ?

### Actual behaviour
Tell us what happens instead
Exception: Updates between multiple major versions are unsupported.
The update was unsuccessful
when I migrated to DSM 6, owncloud v6 stoped working, 
inadvertently I clicked on migrate to owncloud v8 what I didn't want to do before an export :(
and 
http://<MyServer>/owncloud/remote.php/carddav/addressbooks/<MyUser>/contacts/
https://<MyServer>/owncloud/remote.php/caldav/calendars/<MyUser>/defaultcalendar
doesn't work anymore :(

### Server configuration
**Operating system**: Synology (migrated to DSM v6)

**Web server:** : Synology Appache

**Database:** : MariaDB

**PHP version:** : PHP 5.6.11

**ownCloud version:** (see ownCloud admin page) : v8.1.1

**Updated from an older ownCloud or fresh install:** : v6.x

**Where did you install ownCloud from:** : Pasckage Synology

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
An unhandled exception has been thrown:
exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver: could not find driver' in /volume1/web/owncloud/lib/private/db/connection.php:50
Stack trace:
#0 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /volume1/web/owncloud/lib/private/db/connection.php(83): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /volume1/web/owncloud/lib/private/db/connectionfactory.php(124): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /volume1/web/owncloud/lib/private/server.php(300): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /volume1/web/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#9 /volume1/web/owncloud/lib/private/appframework/utility/simplecontainer.php(96): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /volume1/web/owncloud/lib/private/server.php(695): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /volume1/web/owncloud/lib/private/db.php(42): OC\Server->getDatabaseConnection()
#12 /volume1/web/owncloud/lib/private/server.php(208): OC_DB::getConnection()
#13 /volume1/web/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#14 /volume1/web/owncloud/lib/private/appframework/utility/simplecontainer.php(96): Pimple\Container->offsetGet('AppConfig')
#15 /volume1/web/owncloud/lib/private/server.php(641): OC\AppFramework\Utility\SimpleContainer->query('AppConfig')
#16 /volume1/web/owncloud/lib/private/server.php(342): OC\Server->getAppConfig()
#17 /volume1/web/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#18 /volume1/web/owncloud/lib/private/appframework/utility/simplecontainer.php(96): Pimple\Container->offsetGet('AppManager')
#19 /volume1/web/owncloud/lib/private/server.php(861): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#20 /volume1/web/owncloud/lib/private/app.php(238): OC\Server->getAppManager()
#21 /volume1/web/owncloud/lib/private/app.php(93): OC_App::getEnabledApps()
#22 /volume1/web/owncloud/lib/base.php(592): OC_App::loadApps(Array)
#23 /volume1/web/owncloud/lib/base.php(1121): OC::init()
#24 /volume1/web/owncloud/console.php(41): require_once('/volume1/web/ow...')
#25 /volume1/web/owncloud/occ(11): require_once('/volume1/web/ow...')

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
An unhandled exception has been thrown:
exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver: could not find driver' in /volume1/web/owncloud/lib/private/db/connection.php:50
Stack trace:
#0 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /volume1/web/owncloud/lib/private/db/connection.php(83): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /volume1/web/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /volume1/web/owncloud/lib/private/db/connectionfactory.php(124): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /volume1/web/owncloud/lib/private/server.php(300): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /volume1/web/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#9 /volume1/web/owncloud/lib/private/appframework/utility/simplecontainer.php(96): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /volume1/web/owncloud/lib/private/server.php(695): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /volume1/web/owncloud/lib/private/db.php(42): OC\Server->getDatabaseConnection()
#12 /volume1/web/owncloud/lib/private/server.php(208): OC_DB::getConnection()
#13 /volume1/web/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#14 /volume1/web/owncloud/lib/private/appframework/utility/simplecontainer.php(96): Pimple\Container->offsetGet('AppConfig')
#15 /volume1/web/owncloud/lib/private/server.php(641): OC\AppFramework\Utility\SimpleContainer->query('AppConfig')
#16 /volume1/web/owncloud/lib/private/server.php(342): OC\Server->getAppConfig()
#17 /volume1/web/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(112): OC\Server->OC\{closure}(Object(OC\Server))
#18 /volume1/web/owncloud/lib/private/appframework/utility/simplecontainer.php(96): Pimple\Container->offsetGet('AppManager')
#19 /volume1/web/owncloud/lib/private/server.php(861): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#20 /volume1/web/owncloud/lib/private/app.php(238): OC\Server->getAppManager()
#21 /volume1/web/owncloud/lib/private/app.php(93): OC_App::getEnabledApps()
#22 /volume1/web/owncloud/lib/base.php(592): OC_App::loadApps(Array)
#23 /volume1/web/owncloud/lib/base.php(1121): OC::init()
#24 /volume1/web/owncloud/console.php(41): require_once('/volume1/web/ow...')
#25 /volume1/web/owncloud/occ(11): require_once('/volume1/web/ow...')

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';
MySQL returned an empty result set (i.e. zero rows)


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
@farpet Please close here and follow the instructions in:

https://central.owncloud.org/t/updates-between-multiple-major-versions-are-unsupported/815

how to do a correct upgrade. If you need further support on how to do a correct upgrade please create a new thread at central.

**Comment by bahamut714** [comment]
dont even bother the upgrade will fail this likely fat retard realrancor doesnt know what they are talking about

**Comment by farpet** [comment]
So what to do to at least extract data ? I still have access to DB,
 can I export manually (SQL, PHPMyAdmin) my Contacts and Calendar items, for e.g.: I just need to export : SELECT fullname,carddata FROM contacts_cards WHERE addressbookid=3 ORDER BY contacts_cards.addressbookid ASC

thank you in advance

**Comment by RealRancor** [comment]
As advised please ask such questions at central. As you have already asked it there have some patience until some one is answering it: https://central.owncloud.org/t/owncloud-sql-manual-export-to-vcf-ics/1500

A short term measure is to revert to your backup and do the upgrade step by step as described in the linked FAQ.
