### ISSUE TITLE
A log appears in owncloud.log file when create a file in an encrypted mountpoint for each available user

### ISSUE THREAD

**Issue by davitol** [owncloud/core#25720]
### Steps to reproduce
1. Configure an LDAP user server in oC 
2. Enable and encrypt the oC server
3. Configure an external mountpoint with the following configuration (e.g. wnd)

![screen shot 2016-08-08 at 12 24 19](https://cloud.githubusercontent.com/assets/10596560/17477067/47dd4cf4-5d63-11e6-872b-3c8f1a77d306.png)
1. In Files view, browse into the mountpoint and create a new file via oC webUI.
### Expected behaviour

No log should be shown. It should not search for all users that are 
### Actual behaviour

A log is written in owncloud.log for each LDAP user related to encryption
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.6

**ownCloud version:**

"9.2.0.1","versionstring":"9.2.0 pre alpha","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
Yes, WND

**Are you using encryption:** 
Yes

**Logs**

It is printed for each user:

```
{"reqId":"qgDeit9Bq4MVBN84\/pi2","remoteAddr":"82.159.139.58","app":"encryption","message":"no public key found for user \"f136cad8-ac9d-1035-89f5-6ba4a3e8a9b9\", user will not be able to read the file","level":2,"time":"2016-08-08T09:34:11+00:00","method":"PUT","url":"\/remote.php\/webdav\/WindowsNetworkDrive\/lalalrara.txt","user":"admin"}
```
### Client configuration

**browser**

Firefox

**Comment by davitol** [comment]
removing ldap tag, due to it happens with local users too. The key is if the user where created before the encryption I guess...

```
{"reqId":"HPkikLpKJkpC2fJN2boj","remoteAddr":"82.159.139.58","app":"encryption","message":"no public key found for user \"antes\", user will not be able to read the file","level":2,"time":"2016-08-08T10:41:35+00:00","method":"PUT","url":"\/remote.php\/webdav\/WindowsNetworkDrive\/explourer.txt","user":"admin"}
```

**Comment by PVince81** [comment]
moving to backlog

unless that is polluting the logs continuously in common use cases

**Comment by PVince81** [comment]
If this is not polluting the log repeatedly, won't fix.

This is a generic message from encryption app. Apart from deleting it I don't see an easy way to conditionally log it or not depending on the code path.
