### ISSUE TITLE
Music app keeps hanging and is basically unusable.

### ISSUE THREAD

**Issue by memorex1** [owncloud/core#25726]
### Steps to reproduce
1.Open the music app, wait a few seconds.
2.
3.*My collection on owncloud 7k songs big.*

### Expected behaviour
Tell us what should happen
Listening to astonishing music.
### Actual behaviour
Tell us what happens instead
The loading symbol appears, after a few secs the page is unresponsive. Chrome asks to close the webpage. If you wait long enough you can play a song, but every input leads to an unresponsive page.
 
### Server configuration
**Operating system**:
ubuntu 16.04
**Web server:**
apache 2
**Database:**
MariaDB
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
9.04
**Updated from an older ownCloud or fresh install:**
updated
**Where did you install ownCloud from:**
from the tarball on the owncloud website
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
`No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

jonathan@37-97-187-174:~$ sudo -u www-data php occ config:list system
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/enchant.so' - /usr/lib/php/20151012/enchant.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/gmp.so' - /usr/lib/php/20151012/gmp.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/imap.so' - /usr/lib/php/20151012/imap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/interbase.so' - /usr/lib/php/20151012/interbase.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/ldap.so' - /usr/lib/php/20151012/ldap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/odbc.so' - /usr/lib/php/20151012/odbc.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo_firebird.so' - /usr/lib/php/20151012/pdo_firebird.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo_odbc.so' - /usr/lib/php/20151012/pdo_odbc.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo_pgsql.so' - /usr/lib/php/20151012/pdo_pgsql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pdo_sqlite.so' - /usr/lib/php/20151012/pdo_sqlite.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pgsql.so' - /usr/lib/php/20151012/pgsql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/pspell.so' - /usr/lib/php/20151012/pspell.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/recode.so' - /usr/lib/php/20151012/recode.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/snmp.so' - /usr/lib/php/20151012/snmp.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/soap.so' - /usr/lib/php/20151012/soap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/sqlite3.so' - /usr/lib/php/20151012/sqlite3.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/tidy.so' - /usr/lib/php/20151012/tidy.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/xmlrpc.so' - /usr/lib/php/20151012/xmlrpc.so: cannot open shared object file: No such file or directory in Unknown on line 0

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

<?php
$CONFIG = array (
  'instanceid' => 'octymipzp2bt',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'cloud2.ofnie.eu',
    1 => 'cloud.ofnie.eu',
  ),
  'datadirectory' => '/owncloudData/data',
  'overwrite.cli.url' => 'http://cloud.ofnie.eu',
  'dbtype' => 'mysql',
  'version' => '9.0.4.1',
  'dbname' => 'ownclouddb',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'memorex',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => '',
  'mail_domain' => 'gmail.com',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => '587',
  'mail_smtpname' => '@gmail.com',
  'mail_smtppassword' => '',
  'loglevel' => 3,
  'theme' => '',
  'maintenance' => false,
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'appstore.experimental.enabled' => true,
);









**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
Yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome
**Operating system:**
Win7
### Logs
#### Web server error log
```
Insert your webserver log here
```[Mon Aug 08 06:25:07.900535 2016] [mpm_prefork:notice] [pid 4926] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g-f$
[Mon Aug 08 06:25:07.900570 2016] [core:notice] [pid 4926] AH00094: Command line: '/usr/sbin/apache2'
---
[Sun Aug 07 06:25:07.914045 2016] [mpm_prefork:notice] [pid 4926] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g-f$
[Sun Aug 07 06:25:07.914138 2016] [core:notice] [pid 4926] AH00094: Command line: '/usr/sbin/apache2'
[Mon Aug 08 06:25:07.159556 2016] [mpm_prefork:notice] [pid 4926] AH00171: Graceful restart requested, doing resta$



#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
``You can find it at: "https://cloud.ofnie.eu/index.php/s/GTSQZ0XiQ06rcnV" password = 'logfile'

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
@memorex1 Please re-open in https://github.com/owncloud/music/issues where the issue tracker of the music app is located.

**Comment by memorex1** [comment]
I have reopend it in the mentioned forum. Thanks for the reply!
