### ISSUE TITLE
LDAP can't login - oc_cards problem with VCARD

### ISSUE THREAD

**Issue by Olvikolvi** [owncloud/core#25730]
version: 9.0.1.3

One of my users can't login via LDAP. Problem seems to be large VCARD data which breaks mysql connection..

An exception occurred while executing 'UPDATE `oc_cards` SET `carddata` = ?, `lastmodified` = ?, `size` = ?, `etag` = ? WHERE (`uri` = ?) AND (`addressbookid` = ?)' with params [\\\"BEGIN:VCARD\\\\r\\\\nVERSION:3.0\\\\r\\\\nPRODID:-\\\\\\\/\\\\\\\/Sabre\\\\\\\/\\\\\\\/Sabre VObject 3.5.0\\\\\\\/\\\\\\\/EN\+very long string with "binary" vcard data.....

Then next mysql query gives error "MySQL server has gone away" and user cant login..

**Comment by DeepDiver1975** [comment]
I guess this is related to a very big avatar picture - what is the size of the avatar?

**Comment by Olvikolvi** [comment]
VCARD size is 6MB, and there is large png avatar image..

**Comment by DeepDiver1975** [comment]
> and there is large png avatar image..

how large?

**Comment by DeepDiver1975** [comment]
can you reduce the size of the avatar?

**Comment by Olvikolvi** [comment]
Yes I can remove it, but maby you still shuld make some kind of check to your code to avoid this kind of problems because end users does this kind of weird thinks because they can..

**Comment by DeepDiver1975** [comment]
> but maby you still shuld make some kind of check to your code to avoid this kind of problems because end users does this kind of weird thinks because they can..

sure :see_no_evil:

**Comment by Touchwoody** [comment]
This might be a database issue. 
mysql has a parameter max_allowed_packet, which defines the maximum size of any packet resp. parameter send to the database (see http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_max_allowed_packet). 
Default for mysql is 4MB (resp. 1MB for older versions <5.5).

Owncloud allows avatar pictures up to 20MB. So if you try to write this to oc_cards into the database, it will fail. 

Workaround: set max_allowed_packet to 20971520.
