### ISSUE TITLE
Upgrade from cPanel EA 3 to EA 4 caused internal server error

### ISSUE THREAD

**Issue by NesooseN** [owncloud/core#25750]
Hi, I am getting this error after moving cPanel EA3 to EA4:

OC 9 on Apache 2.4, PHP 5.6 with sqlite 3.6.20

Error is:

{"reqId":"V6pHJRDEz69RziYM9J3TKgAAAA8","remoteAddr":"31.223.135.61","app":"index","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'SELECT * FROM \\\"oc_appconfig\\\"':\\n\\nSQLSTATE[HY000]: General error: 26 file is encrypted or is not a database\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/larr490\\\/public_html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/home\\\/larr490\\\/public_html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT * FROM \\\"...', Array)\\n#2 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/db\\\/connection.php(184): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT * FROM \\\"...', Array, Array, NULL)\\n#3 \\\/home\\\/larr490\\\/public_html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT * FROM `...', Array, Array)\\n#4 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/db\\\/querybuilder\\\/querybuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/appconfig.php(274): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/appconfig.php(77): OC\\\\AppConfig->loadConfigValues()\\n#7 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/appconfig.php(253): OC\\\\AppConfig->getApps()\\n#8 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/app.php(1046): OC\\\\AppConfig->getValues(false, 'installed_versi...')\\n#9 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/server.php(290): OC_App::getAppVersions()\\n#10 \\\/home\\\/larr490\\\/public_html\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#11 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(102): Pimple\\\\Container->offsetGet('MemCacheFactory')\\n#12 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/servercontainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('MemCacheFactory')\\n#13 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/server.php(891): OC\\\\ServerContainer->query('MemCacheFactory')\\n#14 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/server.php(415): OC\\\\Server->getMemCacheFactory()\\n#15 \\\/home\\\/larr490\\\/public_html\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#16 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/appframework\\\/utility\\\/simplecontainer.php(102): Pimple\\\\Container->offsetGet('AppManager')\\n#17 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/servercontainer.php(87): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('AppManager')\\n#18 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/server.php(1077): OC\\\\ServerContainer->query('AppManager')\\n#19 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/app.php(254): OC\\\\Server->getAppManager()\\n#20 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/private\\\/app.php(103): OC_App::getEnabledApps()\\n#21 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/base.php(660): OC_App::loadApps(Array)\\n#22 \\\/home\\\/larr490\\\/public_html\\\/lib\\\/base.php(1197): OC::init()\\n#23 \\\/home\\\/larr490\\\/public_html\\\/index.php(37): require_once('\\\/home\\\/larr490\\\/p...')\\n#24 {main}\",\"File\":\"\\\/home\\\/larr490\\\/public_html\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":85}","level":3,"time":"2016-08-09T21:12:05+00:00","method":"GET","url":"\/index.php","user":"--"}

**Comment by RealRancor** [comment]
You might get some pointers here:

http://stackoverflow.com/questions/1513849/error-file-is-encrypted-or-is-not-a-database
