### ISSUE TITLE
defaultapp configuration is not respected

### ISSUE THREAD

**Issue by scriptPilot** [owncloud/core#25781]
After update to ownCloud 9.1, my configuration value defaultapp = "rainloop" is not respected anymore. ownCloud starts with files app. The rainloop folder exists within the apps folder and rainloop is working without any problems after the update.

**Comment by DeepDiver1975** [comment]
already fixed - will be shipped with 9.1.1

**Comment by RealRancor** [comment]
Should be also findable via the search: https://github.com/owncloud/core/issues/25562
