### ISSUE TITLE
Dot work 

### ISSUE THREAD

**Issue by badredaha** [owncloud/core#25796]
Dear owncloud team,

i work hard since 15 days to build owncloud code source for Mac OS X 10.11 and nothing work :(.

i can run application from xCode but none of dmg or pkg work when i build it :s 

### Steps to reproduce
1. i following step by step https://doc.owncloud.org/desktop/2.0/building.html for Mac os X
2. First bug : QtWebKitWidget and QTWebKit does not exist into qt 5.6.1-1
3. i download Qt editor for trying to open project. and i found that Qt Editor download version of Qt that has QtWebKitWidget and QTWebKit
3. i hack the steps and i force copied QtWebKitWidget and QTWebKit into /usr/local/qt5/5.6.1-1/lib
4. i download CMAKE UI and i generet xCode project
5. i correct some importation like : qtkeychain.h and dlyb 
6. i copied some library not found from other versions
7. i finaly run application into xCode with RUN target owncloud and everthing work
8. i run package or install it generate me pkg and .dmg but if i started nothing work and i have this exception from owncloudcmd i hade this : Reason: Incompatible library version: owncloudcmd requires version 5.6.0 or later, but QtNetwork provides version 5.4.0

### Expected behaviour
i want have a dmg or pkg or my bin have framework and all informations embedded :( plz help

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
Please don't use a bugtracker for support questions. Use https://central.owncloud.org/c/development/client-development instead
