### ISSUE TITLE
OwnCloud nginx serves wrng mimetype for .js

### ISSUE THREAD

**Issue by rob9** [owncloud/core#25792]
SETUP
* OwnCloud 9.0.2 stable
* nginx configuration from here: [https://doc.owncloud.org/server/9.0/admin_manual/installation/nginx_owncloud_9x.html](https://doc.owncloud.org/server/9.0/admin_manual/installation/nginx_owncloud_9x.html)
* Install calendar 1.3.2 from [https://github.com/owncloud/calendar](https://github.com/owncloud/calendar)
* Browser: Chromium, Ubuntu 16.04 amd64
  * Display browser JavaScript Console
* In Owncloud, select Calendar from the selector in upper right to the right of the cloud icon

BUG: page looks like garbage b/c angular does not start
Console displays:
> Refused to execute script from 'https:/(owncloud)/apps/calendar/js/public/app.js?v=7b237bb3caf3ec72f70785a20454296f' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

* nginx by itself serves upp .js just fine with mime type application/javascript
* Any .js cached by owncloud core, or served via owncloud core has bad mime type text/html

The administration manual has some unhelpful statements about mime types
* does /var/www/owncloud/resources/config/mimetypemapping.json replace or override /var/www/owncloud/resources/config/mimetypemapping.dist.json?
  * ie. should I copy the .dist or just have the ones I want to change
* What does one have to do to make mime types take effect
  * cd /var/www/owncloud/ && sudo -u www-data ./occ maintenance:mimetype:update-db
  * maintenance:mimetype:update-js
  * sudo -u www-data php occ maintenance:mode --on
  * something else?
* sudo -u www-data php ./occ maintenance:mimetype:update-db inserts records into the table oc_mimetypes, that has id to mimetype-text only. However, Owncloud does not actually use this information.

How does anyone make this work?

Why does owncloud core serve the wrong mime-type in the first place?

**Comment by RealRancor** [comment]
@rob9 Please use https://central.owncloud.org/ for such support question. The nginx config linked above and oC 9.0.x is known to work on tons of such setups so it must be something special/non default in your environment causing this behavior

**Comment by rob9** [comment]
It's a bug in Calendar 1.3.2: it asks for js files that do not exist, and then get served empty text files

**Comment by RealRancor** [comment]
Looks more like a wrong packaged archive released by your distro (if you're on Arch): https://github.com/owncloud/calendar/issues/686
