### ISSUE TITLE
Error to download/sync files from a specific sharing folder

### ISSUE THREAD

**Issue by kenyang001** [owncloud/core#25806]
### Steps to reproduce
1.   encrypion app enabled
2.  folder sharing
3.  word/excel files.

### Expected behaviour
some of files from a sharing folder failed to download/sync

### Actual behaviour
download/sync properly

### Server configuration
**Operating system**: 
ubuntu 14.04 64-bit

**Web server:**
apache2

**Database:**
mysql
**PHP version:**
php5
**ownCloud version:** (see ownCloud admin page)
9.0.4
**Updated from an older ownCloud or fresh install:**
from an older owncloud
**Where did you install ownCloud from:**
upgrade from updater app
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - encryption: 1.2.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - files_external
  - user_external
  - user_ldap


**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
<?php
$CONFIG = array (
  'instanceid' => 'ocf1aff97781',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'ip address',
    1 => 'cloud.domain.com',
  ),
  'datadirectory' => '/datadriveF/data',
  'overwrite.cli.url' => 'https://domin.com',
  'dbtype' => 'mysql',
  'version' => '9.0.4.1',
  'dbname' => '',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'domain.com',
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'smtp.office365.com',
  'mail_smtpport' => '587',
  'mail_from_address' => 'admin',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'email address',
  'mail_smtppassword' => 'passwordE',
  'loglevel' => 3,
  'logtimezone' => 'Asia/Shanghai',
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'forceSSLforSubdomains' => true,
  'singleuser' => false,
  'trashbin_retention_obligation' => 'auto',
  'htaccess.RewriteBase' => '/',
);




**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
[server error log.txt](https://github.com/owncloud/core/files/418192/server.error.log.txt)
![client error](https://cloud.githubusercontent.com/assets/10448085/17667209/828fc13c-6336-11e6-9ec4-7a9fd7d88e91.JPG)

```

**Comment by PVince81** [comment]
The error seems to say that the file doesn't exist in the data folder, can you check ?
It is likely that the file exists in the oc_filecache table but no in the data folder (inconsistency).

Usually such inconsistencies could be fixed by running `occ files:scan --all`.

**Comment by kenyang001** [comment]
@PVince81  Hi Vincent,  I scanned that folder by occ files:scan --path,, now it looks the download/syncing is normal . 
could you let me know why this happens or how can we prevent it from corrupting in future? thanks a lot.

**Comment by PVince81** [comment]
It is likely that the corruption is due to a PHP timeout during upload or delete for big files for example. Basically, OC didn't have time to finish properly preparing the encryption keys or updating the oc_filecache table. You can reduce the occurrences of such timeouts by increasing the PHP timeout in php.ini. Unfortunately it seems there is no way to completely prevent this. The problem with PHP timeouts is that PHP would just kill the process even if it hasn't finished its work.

There are some ideas to improve this in the future by using asynchronous file operations, but it would be a big change in the architecture: https://github.com/owncloud/core/issues/24509

**Comment by kenyang001** [comment]
@PVince81  Hi Vincent,  thanks for your answer, it seems we have another sharing folder having the same problem.
my current php.ini file's  max_execution_time =30 , Max_input_time = 60.
could you give advice for the best value for ownCloud system. thanks.
