### ISSUE TITLE
Some functions used in personal template doesn't exist in User class

### ISSUE THREAD

**Issue by lahmizzar** [owncloud/core#25824]
**canUserChangeDisplayName => canChangeDisplayName**
https://github.com/owncloud/core/blob/master/settings/personal.php#L161
`$tmpl->assign('passwordChangeSupported', OC_User::canUserChangePassword(OC_User::getUser()));`
and here
https://github.com/owncloud/core/blob/master/lib/private/User/User.php#L288-L295
```
	/**
	 * check if the backend supports changing display names
	 *
	 * @return bool
	 */
	public function canChangeDisplayName() {
		if ($this->config->getSystemValue('allow_user_to_change_display_name') === false) {
			return false;
		}
		return $this->backend->implementsActions(Backend::SET_DISPLAYNAME);
	}
```

**canUserChangeDisplayName => canChangeDisplayName**
https://github.com/owncloud/core/blob/master/settings/personal.php#L162
`$tmpl->assign('displayNameChangeSupported', OC_User::canUserChangeDisplayName(OC_User::getUser()));`
and here
https://github.com/owncloud/core/blob/master/lib/private/User/User.php#L297-L307
```
	/**
	 * check if the backend supports changing display names
	 *
	 * @return bool
	 */
	public function canChangeDisplayName() {
		if ($this->config->getSystemValue('allow_user_to_change_display_name') === false) {
			return false;
		}
		return $this->backend->implementsActions(Backend::SET_DISPLAYNAME);
	}
```

**Comment by PVince81** [comment]
If that was an issue, the personal page wouldn't work at all.

A quick grep showed that the function is actually in another User object: https://github.com/owncloud/core/blob/master/lib/private/legacy/user.php#L416

Still, thanks for noticing. I'm surprised too...

Closing this as it's not an issue.
