### ISSUE TITLE
[Feature Request] status.php should also print out the source name

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#25822]
When you do url/status.php you get printed out: (example)
``{"installed":true,"maintenance":false,"version":"9.1.0.15","versionstring":"9.1.0","edition":""}``

This FR is about to add the source name "ownCloud" to differenciate from other forks.
``{"installed":true,"maintenance":false,"version":"9.1.0.15","versionstring":"9.1.0","edition":"","source":"ownCloud"}``

@PVince81, @DeepDiver1975

**Comment by PVince81** [comment]
You mean the value of the "vendor" field in version.php ?

PRs welcome :smile:

**Comment by PVince81** [comment]
Now thinking of it, some people white label their ownClouds and might not want the word "owncloud" to appear in any output, so not sure. Maybe it should be the product name from the theme instead ?

**Comment by mmattel** [comment]
yes - vendor...

**Comment by mmattel** [comment]
good point. where do I find (query) the product name to be printed out?

**Comment by PVince81** [comment]
Seems to be:
```php
$defaults = new \OC_Defaults();
$defaults->getName()
```

Not sure if this causes additional overhead.

**Comment by icewind1991** [comment]
For vendor I wouldn't put the themed name in there, it makes more sense to have separate fields for vendor and product name imo

**Comment by mmattel** [comment]
PR merged - closing
