### ISSUE TITLE
INVALID_HASH for .user.ini and .htaccess

### ISSUE THREAD

**Issue by redoverture** [owncloud/core#25825]
### Steps to reproduce
1. Download and Install ownCloud
2. Switch from SQLite to mySQL
3. Open Administration Panel

### Expected behaviour
Error-free operation after new configuration

### Actual behaviour
Errors from valid configuration files

### Server configuration
**Operating system**: Raspbian armv7 GNU/Linux

**Web server:** nginx

**Database:** mySQL

**PHP version:** PHP 5.6.24-0+deb8u1

**ownCloud version:** 9.1.0 (stable)

**Updated from an older ownCloud or fresh install:** Fresh Install

**Where did you install ownCloud from:** Linux package manager

**Signing status (ownCloud 9.0 and above):**

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess
		- .user.ini

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => ab5f4c44ba2f9c66f2ed25c3ad3d84660b2808cca11ffa8fe2778a648a054d8ada495a0bf4715dc873aac1efe8dfd92a72f9a24441d8f5240834e639325fd892
                            [current] => b68b2eea45d2e988af5167161c3ddaec6f016d90531eb3e838e5fafbbe5a00d14be1f814ffb9c89511b2096b2d20ef084a42793c6a3542d8e9fdd07acb3e21d6
                        )

                    [.user.ini] => Array
                        (
                            [expected] => 0a557e3cdca4c2e3675deed761d79d109011dcdebbd9c7f6429f1d3476938ec95729543d7384651d1d0c48e26c5024cc5f517445920915a704ea748bdb903c5f
                            [current] => 5b6ac2ca5a69488f86635f42b48b029072961b67a01fcc2b9dd90ab2fd70690ab23794dd7acdc4e008bfde794724e586878e7a3ccc8c905ae9d8bc86a255c02a
                        )

                )

        )

)
```

Default enabled applications

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```
<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'ocemmed7kths',
  'passwordsalt' => REDACTED
  'secret' => REDACTED
  'trusted_domains' =>
  array (
    0 => 'cloud.blackadar.me',
  ),
  'datadirectory' => '/media/cloud',
  'overwrite.cli.url' => 'https://cloud.blackadar.me',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'dbname' => 'cloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_jordan7',
  'dbpassword' => REDACTED
  'logtimezone' => 'UTC',
  'installed' => true,
);

**Are you using external storage, if yes which one:** Yes, external NTFS drive

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome 53.0.2785.57 beta-m (64-bit)

**Operating system:** Windows 10 OS Build 1058.545

**Comment by PVince81** [comment]
Can you confirm that you didn't modify these files ?

**Comment by redoverture** [comment]
I did not, but replacing the files with new copies from the repository seems to have fixed the issue. I would have to assume the files were either corrupted or modified by another process during the installation. Thanks!
