### ISSUE TITLE
Warning: Trusted domain error - Netcraft SSL Server Survey

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#25839]
### Steps to reproduce

There are no clear steps for reproduction as this is triggered from the outside.
But I do get owncloud log entries "Trusted domain error".

sss.yyy.zz (my onwcloud instance) logs an attempt to a failed trust access to another instance on the same server xxx.yy.zz (test, dev).

The question is, why (how) are trusted domain errors triggered and can that be prevented? Is there a security leak (on my side, in the code)? The subdomains (xxx) in question are in the hosters DNS but have never been published by me (except to letsencrypt). Therefor this logging is very courios to me...

**nginx access log:**

```
159.203.67.209 - - [17/Aug/2016:10:52:18 +0200] "GET / HTTP/1.1" 400 6910 "-" "Netcraft SSL Server Survey - contact info@netcraft.com"
```

**owncloud log:**

```
{"reqId":"HI5hbnu16jJMh2eBPW2h","remoteAddr":"159.203.67.209","app":"core","message":"Trusted domain error. \"159.203.67.209\" tried
to access using \"xxx.yyy.zz\" as host.","level":2,"time":"2016-08-17T10:52:18+02:00","method":"GET","url":"\/","user":"--"}
```
### Expected behaviour

No logging of an owncloud warning
### Actual behaviour

A warning is triggered
### Server configuration

**Operating system**: Ubuntu 14.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page) 9.1.0 stable

**Updated from an older ownCloud or fresh install:** no

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - logreader: 1.1.5
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ock7fv8dydb8",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "sss.yyy.zz"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/sss.yyy.zz",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "asset-pipeline.enabled": false,
        "filesystem_check_changes": 1,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Raw"
        ],
        "mail_from_address": "xxx",
        "mail_smtpmode": "smtp",
        "mail_domain": "xxxx",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "xxxx",
        "mail_smtpport": "587",
        "loglevel": 2,
        "maintenance": false
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:** Opera

**Operating system:** W7x64
#### Web server error log

see above
#### ownCloud log (data/owncloud.log)

see above

**Comment by RealRancor** [comment]
Info about the trusted domain is available here:

https://doc.owncloud.org/server/9.1/admin_manual/installation/installation_wizard.html#trusted-domains

The message in the logfile means that external system is acessing a hostname (host: header in the request) which is not allowed in your trusted_domains config.php setting.

There is most likely nothing to do here from oC side except to lower the loglevel for those messages if you're getting annoyed by them

**Comment by mmattel** [comment]
From the documantation:
> All URLs used to access your ownCloud server must be whitelisted in your config.php file, under the trusted_domains setting. Users are allowed to log into ownCloud only when they point their browsers to a URL that is listed in the trusted_domains setting.

From my understanding,  if I have eg 3 different subdomains but let them point to one owncloud webroot and I want to access via all of the three subdomains my instance, I need to maintain the trusted_domains setting propely.

domain + webroot:
```
sub1.dom.com -->/var/www/owncloud 
sub2.dom.com -->/var/www/owncloud
sub3.dom.com -->/var/www/owncloud
```
```
'trusted_domains' =>
  array (
   0 => 'sub1.dom.com',
   1 => 'sub2.dom.com',
   2 => 'sub3.dom.com',
),
```

So if I would go in via sub2.dom.com and trusted_domains is not setup properly, I end up getting the error message.

But my setup is looking like that 
domain + webroot:
```
sub1.dom.com -->/var/www/owncloud1
sub2.dom.com -->/var/www/owncloud2
sub3.dom.com -->/var/www/owncloud3
```

owncloud1:
```
'trusted_domains' =>
  array (
   0 => 'sub1.dom.com',
),
```
...

There are no nginx access log entries for all other subdomains present, neither access or error...

My question is now, how is it possible that a request coming from sub1.dom.com can point internally at owncloud to sub2.dom.com? For me this looks like very weird.

**Comment by PVince81** [comment]
Is "sub2.dom.com" referenced anywhere else in config.php like the CLI URL ? Or was it at some point sent as share link by email ?

Which one of these is "xxx.yy.zz" you mentioned in the original posts ?

**Comment by mmattel** [comment]
@PVince81 

Sorry for the confusion regarding using the terms sub1.dom.com and sss.yyy.zz ect.

```
sub1.dom.com -->/var/www/owncloud1 --> sss.yyy.zz --> trusted_domains' => array (0 => 'sub1.dom.com',)
sub2.dom.com -->/var/www/owncloud2 --> xxx.yyy.zz --> trusted_domains' => array (0 => 'sub2.dom.com',)
sub3.dom.com -->/var/www/owncloud3 --> vvv.yyy.zz --> trusted_domains' => array (0 => 'sub3.dom.com',)
```

The domains are only registered in their belonging config.php only in the trusted_domains section and not in any other instance.

sss.yyy.zz (productive onwcloud instance) --> logging where the warning occured
xxx.yyy.zz (test) --> referenced in the warning
...

All instances are for their own, seperated and fenced, so no cross handling.
I also never did link sharing between productive and test (one of the other instances)

I just can repeat my question, how is it possible that a request coming from sub1.dom.com can internally point at owncloud to sub2.dom.com as there is no reference between those two?

**Comment by PVince81** [comment]
No idea, this shouldn't be possible.

Maybe grep "sub2.dom.com" and "xxx.yyy.zz" in the source code of all the instances (including config.php)
Then check if the databases contain these strings too, "oc_share_external", "oc_jobs".

If "test" is the test system, maybe you forgot to change the domain name when switching it to productive.

**Comment by mmattel** [comment]
My words, should not be possible - but it happened...

"oc_share_external", "oc_jobs" are ok

Running grep -r sub2.dom.com over www shows exact 2 entries in config.php for this related instance
trusted_domains and overwrite.cli.url
And the entries in owncloud.log for the instance.

Same for all other instances. So all is fenced and clean.

nginx is setup. When I install a new instance, I:
- stop services where necessary
- kill the db for that instance
- rename the current one
- install the new one under the old name from scratch
- restore if necessary the users data
- and start the services again
- delete the renamed old instance

I never "upgrade" from test to prod.

**Comment by PVince81** [comment]
Could it be something that got cached in redis and got reused by the other instance ?
I don't think the fed share coding caches anything there though.

And as you reinstall everything from scratch, the instanceid would change too, so there shouldn't be any caching conflicts.

Now thinking of redis, do they all share the same redis server instance ? I don't think any instance prefix is used with memcache.

**Comment by mmattel** [comment]
Yes they share the same redis server instance. The setup in config.php for all instances look more or less the same. But continuing this thought makes my neck hairs raise up...

Was just looking at subdomain2 nginx access log - Netcraft entry is present (continious entries in the webservers log about once a month) but looking with the related IP address in owncloud.log NO correspondent entries are present.

grep Netcraft /var/log/nginx/instance2.access.log
--> get the IP_address

grep IP_address /var/www/instance2/data/owncloud.log
--> no result

subdomain2 runs: - version: 9.1.0.8 - versionstring: 9.1.0 beta 2
(for the terminology: subdomain2 accesses instance2)

hmmm....

**Comment by RealRancor** [comment]
Maybe some noticed that those are external systems that accessing this subdomains? As an admin you can't influence.

oC is just checking and verifying the host headers here (host header poisoning).

As an external user you could even access sub1.foo.com with an host header of sub1.bar.com and oC would throw that message.

@mmattel If you want to understand whats happening here you probably need to read into that host header topic first.

**Comment by RealRancor** [comment]
Maybe some noticed that those are external systems that accessing this subdomains? As an admin you can't influence these.

oC is just checking and verifying the host headers here (host header poisoning).

As an external user you could even access sub1.foo.com with an host header of sub1.bar.com and oC would throw that message. I don't see anything what needs to be done here from oC side except maybe to lower the loglevel for those messages.

@mmattel If you want to understand whats happening here you probably need to read into that host header topic first.

**Comment by mmattel** [comment]
@RealRancor 
you are highlighting a good point - host header poisoning.
That could explain why access via subdomain1 triggers a warning for subdomain2. As the code currently does not seem to cover this properly, the warning is possibly misleading. Could be a possible improvement for owncloud, at least in the error handling eg defining a new text for this case.
Generally speaking, owncloud is throwing the request away as it does not fit, but the reason for could be described better minimizing confusion for admins or catching and logging nothing, to be defined.

**Comment by PVince81** [comment]
Seems this was mostly a misunderstanding or env issue. Closing.
