### ISSUE TITLE
[Stable9] Public shared folder with edit permissions doesn't show creation button and doesn't allow uploads.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#25848]
### Steps to reproduce:

1. Share a folder by link. Allow editing.
2. Open link in edge browser.

### Expected behaviour:
You can upload new files and create folders using '+' button.

### Actual behaviour
No '+' button appears.

![screen shot 2016-08-18 at 10 33 02](https://cloud.githubusercontent.com/assets/9048796/17767206/4b294bd2-652f-11e6-8cda-9e400219c207.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0.9

**ownCloud version:** (see ownCloud admin page)
Current stable9
{"installed":true,"maintenance":false,"version":"9.0.4.2","versionstring":"9.0.4","edition":"Enterprise"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```


```

### Browser configuration

Microsoft Edge

**Comment by PVince81** [comment]
Is this still happening in 9.0.5 ? I guess this is specific to Edge ?

**Comment by SergioBertolinSG** [comment]
Not happening in 9.0.5 using edge.
