### ISSUE TITLE
New folder button in web ui shows a cut box.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#25840]
### Steps to reproduce:

Using firefox do:
1. Click on '+' button to create a new folder.

### Expected behaviour:
a whole box appears.

### Actual behaviour
Cut box appears.

![screen shot 2016-08-17 at 13 06 14](https://cloud.githubusercontent.com/assets/9048796/17734380/302b642c-647c-11e6-8212-1cad449fcf8c.png)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0.9

**ownCloud version:** (see ownCloud admin page)
Current master
{"installed":true,"maintenance":false,"version":"9.2.0.1","versionstring":"9.2.0 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```


```

### Browser configuration

Firefox

**Comment by felixheidecke** [comment]
Did you (perhaps accidentally) increase zoom?
If not, please provide FF Version.

**Comment by SergioBertolinSG** [comment]
This is no longer happening.
