### ISSUE TITLE
Synced contacts do not show up until page is refreshed

### ISSUE THREAD

**Issue by gtozzi** [owncloud/core#25847]
Hi there!
This is a very nice software that works smoothly out-of-the-box almost all the time… thank you!

Anyway, even best software have some bugs; I believe I've found a minor one:

### Steps to reproduce
1. Setup a carddav contacts sync on your device
2. Open the contacts page in owncloud web
3. Add a contact on your device
4. Sync the newly added contact with owncloud
5. Search for the newly added contact in the already open owncloud web page

### Expected behaviour
I would expect the newly added contact to show up in the search from the web page or the page to display a warning saying that it is out-to-date and needs to be refreshed.

### Actual behaviour
The newly added contact does not show up in the web contacts page and it gives no clue on the need for a refresh.

### Server configuration
**Operating system**: Ubuntu GNU/Linux 16.04
**Web server:** Apache
**Database:** MySQL
**PHP version:** 7.0.8
**ownCloud version:** 9.0.4
**Updated from an older ownCloud or fresh install:** updated (6 -> 7 -> 8)
**Where did you install ownCloud from:** tarball

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: true
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 48
**Operating system:** Linux

#### Web server error log
Nothing owncloud related

#### ownCloud log (data/owncloud.log)
Only some "login failed" errors

#### Browser log
Nothing

**Comment by DeepDiver1975** [comment]
should be opened in https://github.com/ownclooud/contacts - THX
