### ISSUE TITLE
Display hidden files in file summary separately

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25855]
### Steps

1. Create two hidden folders ".abc" and ".def"
1. Create a visible folder "zzz"
1. Refresh the page => only "zzz" visible
1. Select all

### Expected result
Bottom and selection summary shows "3 folders (2 hidden)"

### Actual result
Summary shows "3 folders" but the folders aren't visible, so might be confusing for users.

@owncloud/designers @SergioBertolinSG

**Comment by SergioBertolinSG** [comment]
This happens with files as well.

![screen shot 2016-08-19 at 09 11 27](https://cloud.githubusercontent.com/assets/9048796/17801954/85fdf5e6-65ed-11e6-9641-8d5d3d5cf7b3.png)

**Comment by PVince81** [comment]
Another possible confusion:

1. Have 2 hidden files and 3 visible files
1. Click the "select all" checkbox
1. Manually untick the checkbox for 3 visible files

As a user, I'd expect the "select all" checkbox to go off since I deselected everything. But since there are hidden files still selected, it doesn't behave that way.

One idea I had: besides adding "X hidden entries" in the summary, also add it in the selection summary and make it clickable. When clicked, it will temporarily toggle displaying the hidden files.
