### ISSUE TITLE
OTP - Error: this app cannot be enabled because it makes the server unstable

### ISSUE THREAD

**Issue by PaddyMack** [owncloud/core#25862]
### Steps to reproduce
1. Retrieve https://apps.owncloud.com/content/show.php/One+Time+Password+Backend?content=159196 and copy content to /var/www/owncloud/apps/user_otp
2. Navigate to apps in ownCloud and hit enable
3. **error**

### Expected behaviour
App should enable

### Actual behaviour
Initially error:
"Error: this app cannot be enabled because it makes the server unstable"

On setting : 'asset-pipeline.enabled' => false on config.php I get 'Error while enabling app' followed by a total loss of availability of ownCloud. Removing that line returned things to normal.

### Server configuration
Retrieved and installed VMX package from ownCloud website earlier today.

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

"No errors have been found."
```

**List of activated apps:**
Activity  2.3.2
Collaborative tags  0.3.0
Comments  0.3.0
Deleted files  0.9.0
*External storage support  0.6.0
Federation  0.1.0
First run wizard  1.1
Gallery  15.0.0
**LDAP user and group backend  0.9.0
Mail Template Editor  0.1
Notifications  0.3.0
PDF Viewer  0.8.1
Provisioning API  0.5.0
Share Files  0.10.0
Text Editor  2.1
Update notification  0.2.1
Versions  1.3.0
Video player  0.9.8

*had to APT-GET smbclient
** had to APT-GET php5-ldap
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
        "instanceid": "ocow55fosl6g",
>         "passwordsalt": "***REMOVED SENSITIVE VALUE***",
>         "secret": "***REMOVED SENSITIVE VALUE***",
>         "trusted_domains": [
>             "localhost",
>             "10.248.0.0\/16",
>             "vNAT2112.ncp.co.uk",
>             "10.248.116.158",
>             "ncpcloud.ncp.co.uk"
>         ],
>         "datadirectory": "\/var\/www\/owncloud\/data",
>         "overwrite.cli.url": "http:\/\/localhost\/owncloud",
>         "dbtype": "mysql",
>         "version": "9.1.0.15",
>         "dbname": "oc",
>         "dbhost": "localhost",
>         "dbtableprefix": "oc_",
>         "dbuser": "***REMOVED SENSITIVE VALUE***",
>         "dbpassword": "***REMOVED SENSITIVE VALUE***",
>         "logtimezone": "UTC",
>         "installed": true,
>         "mail_smtpmode": "smtp",
>         "mail_from_address": "ownCloud",
>         "mail_domain": "ncp.co.uk",
>         "mail_smtphost": "golf.ncp.co.uk",
>         "mail_smtpport": "25",
>         "ldapIgnoreNamingRules": false
>     }

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes  -  SMB

**Are you using encryption:** yes/no
No


### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 8.1
### Logs
#### ownCloud log (data/owncloud.log)
```
{"reqId":"IIG\/t9AMNbqWTQxqeHTw","remoteAddr":"10.248.123.85","app":"PHP","message":"Call to undefined method OC_User::getUsedBackends() at \/var\/www\/owncloud\/apps\/user_otp\/appinfo\/app.php#45","level":3,"time":"2016-08-$-18T22:24:50+00:00","method":"GET","url":"\/index.php\/apps\/files","user":"admin"}

```

**Comment by DeepDiver1975** [comment]
Please get in touch with the author of the app.
