### ISSUE TITLE
Shared folder by link has delete button bad positioned, appearing when it shouldn't and not behaving correctly.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#25871]
### Steps to reproduce:

1. Share a folder by link giving edit permissions having several files in it.
2. Open the link. (Check the column titles)
3. Select a file.
4. Click on the delete button.

### Expected behaviour:
Buttons correctly positioned.
File removed from list after being deleted.

### Actual behaviour
Wild delete button appears.

![screen shot 2016-08-19 at 12 53 28](https://cloud.githubusercontent.com/assets/9048796/17807692/9cc264fa-660c-11e6-8642-98fca96f618a.png)

File spinner keeps spinning after a file is deleted. And not removed from list until a refresh.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0.9

**ownCloud version:** (see ownCloud admin page)
Current master
{"installed":true,"maintenance":false,"version":"9.2.0.1","versionstring":"9.2.0 pre alpha","edition":""}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```


```

### Browser configuration

Tested on Firefox, Chrome and Safari.

**Comment by PVince81** [comment]
Argh, seems to be a regression introduced by the hidden files summary.
Also happens on stable9.1

**Comment by PVince81** [comment]
In my case, opening the public link with existing files is enough to display the bogus links in the header.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/25885
