### ISSUE TITLE
Default calendar "Personal" isn't translated and doesn't have a color

### ISSUE THREAD

**Issue by tcitworld** [owncloud/core#25880]
"Personal" calendar has it's `displayname` not translated in https://github.com/owncloud/core/blob/master/apps/dav/lib/HookManager.php#L109 

Also, it does not provide a color, leading to https://github.com/owncloud/calendar/issues/712

The same could go with the default Address book "Contacts".

**Comment by DeepDiver1975** [comment]
At time if creation we only have a limited understanding of the users language preference.

Id leave it to the users to change the displayname as they like.

**Comment by DeepDiver1975** [comment]
Settings a color is quite reasonable.
Pull request welcome.

**Comment by tcitworld** [comment]
In that case, could it be set to the default server language ?

**Comment by DeepDiver1975** [comment]
Might make sense - yes.
Im okay to wrap the displayname with a translation call.

**Comment by tcitworld** [comment]
PR didn't seem to work.
