### ISSUE TITLE
Toggle to hide/show hidden files

### ISSUE THREAD

**Issue by vincentqb** [owncloud/core#2589]
**EDIT by @jancborchardt**

Solution:
We have a settings area in the Files app now so that’s perfect for putting a setting checkbox called »Show hidden files«. Which would be disabled by default.
The setting should be persistent across sessions, if changed.

Don’t bother reading the comment thread.

**Comment by MorrisJobke** [comment]
Another easier approach: #15206

**Comment by blizzz** [comment]
#15206 is merged, do we consider this as resolved?

**Comment by PVince81** [comment]
I don't think it's solve, I don't see any toggle in the UI.

**Comment by jancborchardt** [comment]
Please read the original issue which I edited some time ago to say this:

> We have a settings area in the Files app now so that’s perfect for putting a setting checkbox called »Show hidden files«. Which would be disabled by default.
> 
> The setting should be persistent across sessions, if changed.

That’s the acceptance criteria. And we should finally do this for 9.0 as no other properly designed file manager by default exposes hidden files (however they are defined) to people using the system.

**Comment by jancborchardt** [comment]
Also here @MTRichards would be good to have this considered for 9.1.

**Comment by MTRichards** [comment]
How do you know what is a hidden file? Do we have a master list?

**Comment by MTRichards** [comment]
Can consider for 9.1.

**Comment by MTRichards** [comment]
probably also .directory files, which show up.

>How do you know what is a hidden file? Do we have a master list?

Note: Desktop client has a "sync hidden files" option, this should just apply the same list to the server.

**Comment by jancborchardt** [comment]
Yep. Compiling this list is part of the task, and just using the same list as the desktop client uses is good.

**Comment by dragotin** [comment]
We will add the `.directory` files to the clients ignore list, it is unfortunately missing there.

**Comment by jancborchardt** [comment]
FINALLY! @ChristophWurst is the man!

:rocket:

**Comment by PVince81** [comment]
Regression: https://github.com/owncloud/core/issues/25309
