### ISSUE TITLE
LDAP avatar only loaded at the second login

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25894]
### Steps
1. Setup LDAP using this docker: https://github.com/owncloud/administration/tree/master/ldap-testing and run `batchCreateUsers.php`, it comes with avatars
2. Setup LDAP in OC
3. Login as "zombie1" with password "zombie1"
4. Check avatar
5. Log out, log in again
### Expected result

Avatar appears the first time
### Actual result

Avatar only updated after the second login

Observed on v9.1.1RC1 and also v8.2.6 (while checking if it was a regression)

@owncloud/ldap

**Comment by PVince81** [comment]
Not really critical. Most users likely never notice as they'll focus on something else during their first login.
And then when second login comes it's already fixed.

Moving to backlog

**Comment by butonic** [comment]
Fixed with account table and ldap logic rewrite.
