### ISSUE TITLE
Calendars are not deleted when an user is deleted

### ISSUE THREAD

**Issue by tcitworld** [owncloud/core#25912]
### Steps to reproduce
1. Create an user. The default calendar is created for him/her
2. Delete the user

### Expected behaviour
Calendar should be deleted inside database

### Actual behaviour
Calendar is not deleted in database (`oc_calendars` table)

### Server configuration
**Database:** SQLite

**PHP version:** 7.0

**ownCloud version:** (see ownCloud admin page) git master

**Comment by DeepDiver1975** [comment]
should be added in here https://github.com/owncloud/core/blob/master/apps/dav/lib/HookManager.php#L92-L101

pull request welcome - THX @tcitworld

**Comment by tcitworld** [comment]
Same goes with address books.

**Comment by Pazu** [comment]
Is it the case that orphaned calendars and addressbooks left behind by previous user deletions will be deleted after upgrading to 9.2?

**Comment by DeepDiver1975** [comment]
> by previous user deletions will be deleted after upgrading to 9.2?

there is nothing inplace as of now

**Comment by koenlek** [comment]
We have orphaned calenders which I would like to delete. It's fine with me to delete them manually from the database. 

Any instructions how I should do that?
