### ISSUE TITLE
ldap + external storage + home share

### ISSUE THREAD

**Issue by keros** [owncloud/core#25919]
Hi

My system:
Owncloud 9.1.0

My setup:
Samba4 (ldap users and file shares)
Owncloud with:
  ldap users and groups plugin
  external storage plugin

How it currently works:
User logs in with his ldap credentials and sees the files and static configured samba shares (projects, ...)
Until here everything works fine.

What I know need:
The user should see his private home share (\\server\home\username).
https://doc.owncloud.org/server/9.1/admin_manual/configuration_files/external_storage/smb.html

> Remote Subfolder: The remote subfolder inside the Samba share to mount (optional, defaults to /). To assign the ownCloud logon username automatically to the subfolder, use $user instead of a particular subfolder name.

So I setup a share with "session credentials" to "\\server\home\$user"
The Problem is now that in "$user" is not the "login username" (like "j.doe") stored. In this variable is the LDAP username (56A3E433-2410-9053-F552-A5C419FB9927).
So if the user logs in the system tries to mount "\server\home\56A3E433-2410-9053-F552-A5C419FB9927" which will not work.

It would be nice if there where extra variables or ldap attributes (sAMAccountName) which I can use.

**Comment by mateusz-skala** [comment]
Go to Administrator-> LDAP Settings -> Expert tab -> Internal User Name -> and insert ldap attribute for ex. sAMAccountName

**Comment by keros** [comment]
thx for the workaround
that should also work for me

**Comment by PVince81** [comment]
@jvillafanez

**Comment by PVince81** [comment]
Seems to be the known "sAMAccountName" issue with workaround. @cdamken do we have a generic ticket for this ?
