### ISSUE TITLE
FR: Implement option to have visibility into a folder on clients without downloading

### ISSUE THREAD

**Issue by nneul** [owncloud/core#25921]
Ideal implementation would be to have desktop functionality like you have on mobile - where the content is not retrieved unless specifically requested. However, I realize that is non-trivial and very non-cross-platform to support.

Here's an easier suggested implementation:

Allow setting a flag on a folder that says "One way uploads". 
Behavior of the folder would be:
 *   Newly added remote files - do not show up
 *   Newly added remote _folders_ - get added locally empty with the same flag set
 *   Newly added local files -> uploaded to remote
 *   Deleted/changed remote files -> deleted/changed locally if it exists

Obviously this folder would be useless for browsing, but it would be perfect for stuff like gallery uploads, or the instant upload folder for photos. 

An additional secondary feature for folders like this that would be useful:

*   Allow setting a "local copy expiration" - where after the expiration has passed, the local copy is virtually deleted, but NOT deleted from the remote server. 

In case you need a more clear scenario - here's a use case - Figure 20-50 GB photo album. Would like to be able to add/upload content to it from multiple desktops, laptop, mobile, etc. Really don't want the extra 20-50GB of space used on every desktop/laptop though, particularly if they have smaller SSDs or are on lower bandwidth connections.

**Comment by tflidd** [comment]
This could solve the problem as well:
https://github.com/owncloud/client/issues/4341

**Comment by nneul** [comment]
@tflidd Definitely, though as that other issue makes pretty clear - that's a BIG effort and quite complicated. Thinking the above might be a much simpler starting point.

**Comment by hodyroff** [comment]
More client related, then server related. But: Why not use a WebDAV client for this purpose? The ownCloud Desktop is really about bi-directional selective syncing. WebDAV does offer the browsing experience from the mobile apps.

**Comment by nneul** [comment]
That's definitely an interesting approach and might be a workaround.

I was thinking of this as just an extension of the existing check for whether to automatically start downloading big folders.

**Comment by DeepDiver1975** [comment]
I dont see why this should be kept open. THX
