### ISSUE TITLE
very slow downloading a file which was shared to a group contains over 5000 user

### ISSUE THREAD

**Issue by joeyjy** [owncloud/core#25923]
### Steps to reproduce
1.download a file(40 kb) which was shared to over 5000 users
2.
3.

### Expected behaviour
fast and smooth

### Actual behaviour
very slow response, waiting for over 5 mins, the filesize is only 40 kb

### Server configuration
**Operating system**: 
centos 7
**Web server:** 
apache
**Database:**
mysql
**PHP version:**
5.4
**ownCloud version:** (see ownCloud admin page)
9.0.1
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
ceph object storage
**Are you using encryption:** yes/no 
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

Dear OC team,

I find it is very slow to download a file which was shared to many user, I'm using object storage as primary storage and with encryption enabled.

Thanks!

**Comment by PVince81** [comment]
Have you tried downloading the same file but without having it shared to many users and it's much faster ?

Would be good to upgrade to at least 9.0.4 and try again as 9.0.1 is already quite old.
