### ISSUE TITLE
Missing Hook-Calls when trash is deleted

### ISSUE THREAD

**Issue by stevenbuehner** [owncloud/core#25926]
Hi there,
I believe that we have bug here in the delteAll() function of the files_trashbin app: https://github.com/owncloud/core/blob/master/apps/files_trashbin/lib/Trashbin.php#L469.

When a single (or multiple files, but not (!) all files) file is deleted from the trashbin, two hooks are fired (preDelete, delete). https://github.com/owncloud/core/blob/master/apps/files_trashbin/lib/Trashbin.php#L509 
Other apps are then able to delete their file-associated metadata as well. But when the whole trashbin is deleted via deleteAll(), no hooks are fired at all. Which means, that other apps can't delete their meta-data.

I understand that deleteAll() was included to optimize performance. But I think that the hooks still need to be fired on a per file basis. Is there a performant way to iterate over all items in trash_bin to fire the hooks?

**Comment by PVince81** [comment]
Indeed. Are you able to provide a fix ?
Thanks

**Comment by stevenbuehner** [comment]
Yes, maybe. I am still figuring out the filesystem :-). If you can point me to an example of how to recursively iterate through a folder (in a performant way) I could provide a patch.

**Comment by PVince81** [comment]
@stevenbuehner I seem to remember that the delete hooks never recursively iterate over subfolders.

So if there's a folder "base/sub/something" and a user deletes "base" from trash, the hook will only be triggered for the deleted one "base", not the subdirs. I think the previews code had to recurse by itself: 

For the "delete all" case, I think it's ok to iterate over the first level of the trashbin and fire hooks for each entry, but don't recurse. Best is to have a look at the class "lib/private/preview.php" and how it deals with hooks. I did have a look there and didn't see any recursion... hmmm... @georgehrke clues ?

**Comment by stevenbuehner** [comment]
I submitted a fix. Please have a look at it.

**Comment by PVince81** [comment]
fixed through your PR https://github.com/owncloud/core/issues/25942, thanks
