### ISSUE TITLE
strpos() expects parameter 1 to be string, array given in settings/admin.php

### ISSUE THREAD

**Issue by mrow4a** [owncloud/core#25930]
1. Install new master from git
2. With phpStorm debug till line 200 in /var/www/owncloud/settings/admin.php
3. Wew obtain sth like that:
![bug](https://cloud.githubusercontent.com/assets/13368647/17933299/dac471d4-6a13-11e6-8ac6-aa3dcf997f80.png)
4. Expect in you owncloud.log sth like that:

>{"reqId":"1HUFy5JzrXVU9SnadbJe","remoteAddr":"127.0.0.1","app":"PHP","message":"strpos() >expects parameter 1 to be string, array given at >\/var\/www\/owncloud\/settings\/admin.php#216","level":3,"time":"2016-08->24T13:54:40+00:00","method":"GET","url":"\/index.php\/settings\/admin","user":"admin"}

### Expected behaviour
we are passing string to strpos

### Actual behaviour
We are passing array to strpos

### Server configuration
**Operating system**:
Linux

**ownCloud version:** (see ownCloud admin page)
(9, 2, 0, 1)
**Updated from an older ownCloud or fresh install:**
No
**Where did you install ownCloud from:**
Git

**Comment by mrow4a** [comment]
@DeepDiver1975 @PVince81 @cdamken

**Comment by mrow4a** [comment]
And it is because of that:
https://github.com/owncloud/core/commit/53f492d71de460f691b93ca3cc1cd2356f103d04

e.g.:
```
foreach ($source as $form) {
$forms[] = include $form;		 +			$page = include $form['page'];
$forms[] = [
'appId' => $form['appId'],
'page' => $page,
];
}		  		
return $forms;
```

**Comment by mrow4a** [comment]
https://github.com/owncloud/core/pull/25528

**Comment by cdamken** [comment]
Duplicated from https://github.com/owncloud/core/issues/25925
