### ISSUE TITLE
Redirect loop after updating httpd (apache) to >= 2.4.21

### ISSUE THREAD

**Issue by Flonix** [owncloud/core#25949]
### Steps to reproduce
1. Install system updates on Fedora 23
2. Restart webserver 
3. No longer able to login because of redirect loop

### Expected behaviour
Successful login

### Actual behaviour
Redirect loop. Browser stops with "too many redirects"

### Server configuration
**Operating system**: Fedora 23

**Web server:**
Affected is httpd with version >= 2.4.21,
PHP is configured via proxy redirect to a chrootet php-fpm instance.

**Database:** MariaDB 10.0.25

**PHP version:** 5.6.23

**ownCloud version:** (see ownCloud admin page)
Testet with 9.0.4 and 9.1.0 (both versions affected)

This issue was introduced with apache/httpd version 2.4.21.
Maybe with this change (copied from the changelog):

`
  *) mod_proxy_fcgi: Avoid passing a filename of proxy:fcgi:// as
     SCRIPT_FILENAME to a FastCGI server. PR59618.
     [Jacob Champion <champion.pxi gmail.com>]
`

After switching back to version 2.4.18 (which is the previous version on Fedora 23) both tested owncloud versions (9.0.4 and 9.1.0) are working again.

**Comment by RealRancor** [comment]
Good start probably would be that you contact http://httpd.apache.org/support.html and ask them what changes where made in between the mentioned versions which could cause such issues. Might be also just a bug in Apache or PHP similar to https://github.com/owncloud/core/issues/20856 or https://bugs.php.net/bug.php?id=65641

The second PHP bug e.g. caused a similar behavior https://github.com/owncloud/core/issues/22411

**Comment by Flonix** [comment]
Why did you close this issue? Was it fixed?

**Comment by RealRancor** [comment]
@Flonix See the pointers above.

**Comment by RealRancor** [comment]
Workaround how to fix your configuration to solve this configuration / apache issue:

```
-      ProxyPassMatch  .*\.php.*       fcgi://127.0.0.1:9000/opt/www/owncloud$0
+      <FilesMatch "\.php$">
+                SetHandler "proxy:fcgi://127.0.0.1:9000"
+      </FilesMatch>
```

from https://github.com/owncloud/core/issues/26868#issuecomment-268994053

**Comment by Flonix** [comment]
@ghost: Thanks for the hint! But it does not work in chrooted environments.

**Comment by kdslkdsaldsal** [comment]
@Flonix Alternatives:

1. Switch to Apache + mod_php
2. Switch to nginx + php-fpm
3. Contact a community dedicated to your used webserver how to get this to work in chrooted environments

**Comment by mkormendy** [comment]
mod_php is way too slow .. php-fpm is much much faster .. php-fpm works just fine with apache

**Comment by kdslkdsaldsal** [comment]
> There is something not right with owncloud.

More likely that there is something wrong with the webservers config: https://github.com/owncloud/core/issues/26868#issuecomment-268994053

**Comment by mkormendy** [comment]
> More likely that there is something wrong with the webservers config

Actually this didn't resolve my issue but I applauded his retort to @Ghost's ridiculousness.
