### ISSUE TITLE
White Screen of Death on misconfiguration

### ISSUE THREAD

**Issue by butonic** [owncloud/core#25945]
When setting up a non existing appfolder in config.php users get a white screen of death in the browser, no log is written. When using occ the admin will see

``` console
App directory "/home/jfd/Repositories/oc/stable9.1/apps-repos" not found! Please put the ownCloud apps folder in the ownCloud folder or the folder above. You can also configure the location in the config.php file.% 
```

The problem is that when the RuntimeExceptions are thrown `\OC::$server` is still null.
https://github.com/owncloud/core/blob/master/lib/base.php#L204
https://github.com/owncloud/core/blob/master/lib/base.php#L211

This causes https://github.com/owncloud/core/blob/master/lib/private/legacy/response.php#L78 to die horribly with a NPE ... which in turn dies horribly in https://github.com/owncloud/core/blob/master/index.php#L57

**Comment by IljaN** [comment]
We probably should try to decouple request/response from server...

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/core/issues/26512.

But I'm pretty sure we'll find more code paths that might to such errors in the future. When we find them, let's open new tickets/PRs then.
