### ISSUE TITLE
errors with phpunit-5.5.2

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#25941]
While testing autotest.sh sqlite against phpunit-5.5.2 I find there is

* many warnings about deprecated methods. Examples:
  - PHPUnit_Framework_TestCase::getMock() is deprecated, use PHPUnit_Framework_TestCase::createMock() or PHPUnit_Framework_TestCase::getMockBuilder() instead

* several errors, where datastructures changed: Examples:
 - tests/lib/Share20/ManagerTest.php::264 Undefined index: pre
 - tests/lib/Share20/ManagerTest.php:853 Undefined index: listener

**Comment by DeepDiver1975** [comment]
Once we have #25513 merged we will pin an exact version of phpunit and adjust our code base accordingly.

**Comment by PVince81** [comment]
Oh noes, but we use `getMock` very often. Sad if we'd need to change them all to another way.

**Comment by PVince81** [comment]
solved or are these more errors ?

**Comment by DeepDiver1975** [comment]
> solved or are these more errors ?

solved from my understanding
