### ISSUE TITLE
PHP Fatal error: Call to a member function getGID() on a non-object in settings/personal.php on line 158

### ISSUE THREAD

**Issue by preske87** [owncloud/core#25952]
### Steps to reproduce
1. Access Personal Page
### Expected behaviour

Display of the Personal-Page
### Actual behaviour

HTTP 500 Error
### Server configuration

**Operating system**: 
any
**Web server:**
any
**Database:**
any
**PHP version:**
any
**ownCloud version:** (see ownCloud admin page)
8.2.7
**Updated from an older ownCloud or fresh install:**
8.2.3
**Where did you install ownCloud from:**
ZIP
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by preske87** [comment]
Issue was already reported via https://github.com/owncloud/core/issues/17516, but still latest 8.2.7 does include the bug. Same fix as in link (https://github.com/owncloud/core/issues/17516) does solve it.

**Comment by PVince81** [comment]
@preske87 do you mean you applied https://github.com/owncloud/core/pull/17704 as patch and it solves the issue ?

**Comment by preske87** [comment]
@PVince81 : Well, I don't know what has been changed in the context of #17516, but the issue is marked as "fixed" in there (at least with version 8.1), but it still occurs in 8.2.7.

**Comment by PVince81** [comment]
> Same fix as in link (#17516) does solve it.

I thought you meant you tested the fix on 8.2. Fine if you didn't.

**Comment by VicDeo** [comment]
@preske87 does the user that is opening personal page belong to any group?

**Comment by VicDeo** [comment]
please also specify user backends you are using

**Comment by preske87** [comment]
@VicDeo 

on "please also specify user backends you are using" - not sure what you mean there

the user I was testing this with belonged to multiple groups

**Comment by PVince81** [comment]
@preske87 are you using local ownCloud users or another user backend like LDAP or IMAP ?

**Comment by PVince81** [comment]
Closing due to lack of feedback
