### ISSUE TITLE
Cannot share folder to a user on another server with a username containing spaces

### ISSUE THREAD

**Issue by vojeroen** [owncloud/core#25955]
### Steps to reproduce
1. Open ownCloud website and click to button to share a folder
2. Input a link to a user on another server (federated sharing) containg spaces, e.g. `Firstname Lastname@otherserver.com`

### Expected behaviour
The folder must be shared with the selected user.

### Actual behaviour
ownCloud does not share the folder and gives the error "no users or groups found matching `Firstname Lastname@otherserver.com` (or similar, my ownCloud is not in English).

### Server configuration
**Operating system:** raspbian on raspberry pi 3
**Web server:** apache
**Database:** postgresql
**ownCloud version:** 9.0.4

This issue has been discussed here: https://central.owncloud.org/t/federated-sharing-with-spaces-in-usernames/1878. If you need any more details, please let me know.

**Comment by tflidd** [comment]
I did test a few more versions.
OC 8.2.7 is working.

OC 9.0.4, OC 9.0.5RC1, OC9.1.1RC1 are NOT working. So it fails for all OC9.0+.

If I use the `core/js/sharedialogview.js` from OC 8.2.7, it works in OC 9.1.1RC1!

**Comment by PVince81** [comment]
@tflidd thanks for the info. Looks like `sharedialogview.js` from 8.2.7 uses the old API endpoint.
So this means the new API endpoint might have trouble with spaces.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/25967
