### ISSUE TITLE
Chrome refused to load the font because of its Content Security Policy

### ISSUE THREAD

**Issue by imdreamrunner** [owncloud/core#25965]
### Steps to reproduce
1. Install OC 9.1
2. Use default theme or example theme
3. Browse to homepage and open developer console, you can see a bunch of errors saying: Refused to load the font 'data:font/woff;base64,d...' because it violates the following Content Security Policy directive: "font-src 'self'".

### Expected behaviour
There should not be such errors.

### Actual behaviour
The errors to load fonts are displayed

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache 2

**Database:** MYSQL 5.5.50

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page) Yogurt Cloud 9.1.0 (stable)

**Updated from an older ownCloud or fresh install:** Updated from 9.0

**Where did you install ownCloud from:** Aug 2016

**Signing status (ownCloud 9.0 and above):** 

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "yogurt.cloud"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/yogurt.cloud",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "nnh",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "xxx",
        "mail_domain": "xxx,
        "mail_smtpmode": "php",
        "mail_from_address": "no-reply",
        "loglevel": 0
    }
}
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome 52

**Operating system:** Mac OS X

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
jquery.min.js?v=3900652…:4Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAJd6ABIAAAABdegAAAAAAACWIAAAAVoAAAKDAAAAA…SYUnjpYfcSDw49uhYFPVe8dHZcYGS7Cfk4MMJ7zwjznvGw3PMA2Oo6+tf/wpSdPlSR/ADe7uPx' because it violates the following Content Security Policy directive: "font-src 'self'".
offset @ jquery.min.js?v=3900652…:4(anonymous function) @ jquery-ui.custom.js?v=3900652…:1466(anonymous function) @ jquery-ui.custom.js?v=3900652…:1471(anonymous function) @ jquery-ui.custom.js?v=3900652…:1473
jquery.min.js?v=3900652…:4Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAKD5ABIAAAABjrQAAAAAAACfoAAAAVkAAAKCAAAAA…mFlx52L/Hg0KNrUdBzxUtnxwVGtpuQjwMjvPeMMO8ZD8s9D4CtrqN//S9M2ek/FckP9vfjlA==' because it violates the following Content Security Policy directive: "font-src 'self'".
offset @ jquery.min.js?v=3900652…:4(anonymous function) @ jquery-ui.custom.js?v=3900652…:1466(anonymous function) @ jquery-ui.custom.js?v=3900652…:1471(anonymous function) @ jquery-ui.custom.js?v=3900652…:1473
jquery.min.js?v=3900652…:4Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAIt0ABEAAAABQDwAAQABAAAAAAAAAAAAAAAAAAAAA…CwKGBmIIpVWLACJWGwAUVjI2KwAiNEswkKAwIrswsQAwIrsxEWAwIrWbIEKAZFUkSzCxAEAisA' because it violates the following Content Security Policy directive: "font-src 'self'".
offset @ jquery.min.js?v=3900652…:4(anonymous function) @ jquery-ui.custom.js?v=3900652…:1466(anonymous function) @ jquery-ui.custom.js?v=3900652…:1471(anonymous function) @ jquery-ui.custom.js?v=3900652…:1473
jquery.min.js?v=3900652…:4Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAI3gABIAAAABRWQAAQABAAAAAAAAAAAAAAAAAAAAA…IwnaGGIYHBlUELLMKwH6htK8MUhmKGIAYjqCImVEUgs1mBOtm1gRYpuNZmSrgAALqcEVgAAAA=' because it violates the following Content Security Policy directive: "font-src 'self'".
offset @ jquery.min.js?v=3900652…:4(anonymous function) @ jquery-ui.custom.js?v=3900652…:1466(anonymous function) @ jquery-ui.custom.js?v=3900652…:1471(anonymous function) @ jquery-ui.custom.js?v=3900652…:1473
jquery.min.js?v=3900652…:4Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAI7kABEAAAABPbQAAQABAAAAAAAAAAAAAAAAAAAAA…hgZiCKVViwAiVhsAFFYyNisAIjRLMJCgMCK7MLEAMCK7MRFgMCK1myBCgGRVJEswsQBAIrAA==' because it violates the following Content Security Policy directive: "font-src 'self'".
offset @ jquery.min.js?v=3900652…:4(anonymous function) @ jquery-ui.custom.js?v=3900652…:1466(anonymous function) @ jquery-ui.custom.js?v=3900652…:1471(anonymous function) @ jquery-ui.custom.js?v=3900652…:1473
jquery.min.js?v=3900652…:4Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAEzMABMAAAAAezAAAQAAAAAAAAAAAAAAAAAAAAAAA…1qIN4ujgYGRhaHjuSQCJCSSCAAGifAwcSjtYPxf+sGlt6NTECdrCkuALy2JpcAAVT4eScAAA==' because it violates the following Content Security Policy directive: "font-src 'self'".
offset @ jquery.min.js?v=3900652…:4(anonymous function) @ jquery-ui.custom.js?v=3900652…:1466(anonymous function) @ jquery-ui.custom.js?v=3900652…:1471(anonymous function) @ jquery-ui.custom.js?v=3900652…:1473
jquery.min.js?v=3900652…:4Refused to load the font 'data:font/woff;base64,d09GRgABAAAAAIw4ABEAAAABQcAAAQABAAAAAAAAAAAAAAAAAAAAA…hgZiCKVViwAiVhsAFFYyNisAIjRLMJCgMCK7MLEAMCK7MRFgMCK1myBCgGRVJEswsQBAIrAA==' because it violates the following Content Security Policy directive: "font-src 'self'".
```

I've found similar issue [here](https://github.com/owncloud/core/issues/21362) but that one should be solved.

**Comment by PVince81** [comment]
@butonic I heard you're familiar with CSP ?

**Comment by butonic** [comment]
Hm, [data URIs are considered unsafe](https://developer.mozilla.org/en-US/docs/Web/Security/CSP/CSP_policy_directives#Data). Not sure which app produces them. does not happen with a minimal core setup. Will need to test with the release.

**Comment by butonic** [comment]
I cannot reproduce this with chrome 54 on windows, nor firefox 48 un ubuntu xenial.

In fact, I don't see any 'data:' URIs being requested.

@imdreamrunner did you activate the asset pipeline? is there a cache somewhere? can you provide a test account?

**Comment by imdreamrunner** [comment]
@butonic Thank you so much for your help. You may login here https://yogurt.cloud/ with `test` as username and password. but you don't need to login to see the error.

I didn't configure any proxy for this website. It's installed on an VPS by Ubuntu package manager.

As far as I can see, the error is from jquery-ui.

Hope these information help.

**Comment by imdreamrunner** [comment]
I did a clean install just now. After when The error has disappeared. Sorry for not testing well.

**Comment by butonic** [comment]
@imdreamrunner just a quick post mortem. Did you by chance update from 9.0 to 9.1 by copying the files of 9.1 on top of 9.0? That may leave some unwanted files from the old release and may cause problems. As the Docs say please always move away the old src and then copy the config (dete should raside outside of the owncloud folder anyway).

@PVince81 @DeepDiver1975 should we add the version to the owncloud folder inside the tar so users do not accidentally overwrite sources and get a mish mash of code? I personally always rename it after unpacking, copy my config and then update a symbolic link that is served by apache ...

**Comment by butonic** [comment]
I guess thats a question for central ...

**Comment by imdreamrunner** [comment]
@butonic I just remember maybe it's because of my mistake during upgrade. I first use `apt-get` to upgrade. But later I delete the maintenance mode in `config.php` and then run the `occ upgrade` command.

I forgot about it when I encounter the error. Again apologise for not testing thoroughly. ^_^

**Comment by butonic** [comment]
@imdreamrunner nevermind, glad it works for you :)
