### ISSUE TITLE
Port Dropbox external storage to the new API

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25969]
The old Dropbox API is deprecated https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/ and will be killed by Dropbox on 28. June 2017.

This means the external storage plugin needs to be ported to the new API.

According to ownCloud's EOL timeline https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule, at this time the oldest supported ownCloud version would be 9.0.x

Ideally, the porting should be done in a separate repository "files_external_dropbox" instead of core (as per https://github.com/owncloud/core/issues/18160.

Not sure about OC < 9.2, maybe need to backport the change there.

Thoughts ? @DeepDiver1975

**Comment by PVince81** [comment]
I just remembered that we wanted to look into porting more storages over to flysystem: https://github.com/thephpleague/flysystem

But flysystem will have the same problem: https://github.com/thephpleague/flysystem-dropbox/issues/14

In general we could maybe write a generic flysystem storage adapter which would make it possible to plug in any of the supported flysystem ones, including the new dropbox adapter if it ever gets written.

**Comment by karakayasemi** [comment]
There is no official Dropbox v2 api and Dropbox said that they do not have plan to release official v2 api, related thread here: https://www.dropboxforum.com/t5/API-support/PHP-SDK-for-API-v2/m-p/173491/highlight/true#M6700

Because of that, flysystem do not have plan to port dropbox v1 adapter to v2. 

In @PVince81 GSOC 2017 Dropbox v2 integration project road map, we are planning to port Flysystem Dropbox v1 adapter to v2. If we Port Flysystem Dropbox v1 adapter to v2, which community version of Dropbox v2 api will be used?

**Comment by PVince81** [comment]
With API you mean what SDK to use ? This is to be discussed / cleared out here https://github.com/thephpleague/flysystem-dropbox/issues/14

It should use one of the community SDKs then: https://github.com/thephpleague/flysystem-dropbox/issues/14#issuecomment-281112999

**Comment by Hemant-Mann** [comment]
Hello @PVince81 I would like to work on this project as a part of GSOC. I have successfully setup the owncloud development environment as described by you [here](https://central.owncloud.org/t/gsoc17-dropbox-v2-integration/5901/2)

I have also started writing the flysystem-dropbox adapter [v2-Adapter](https://github.com/Hemant-Mann/flysystem-dropbox/tree/api-v2) using one of the community SDK  [Dropbox SDK](https://github.com/kunalvarma05/dropbox-php-sdk/)

**Comment by PVince81** [comment]
PR to remove Dropbox v1 storage from core: https://github.com/owncloud/core/pull/28073

Note that the new app is a complete rewrite that uses flysystem so there is no need to keep the old code.

**Comment by individual-it** [comment]
using this SDK https://github.com/kunalvarma05/dropbox-php-sdk for an other project of mine. Works great and I can recommend it

**Comment by Hemant-Mann** [comment]
@individual-it I have been working on this as a part of GSoC'17. As discussed with my mentor @butonic  a new files_external dropbox will be developed based on the lines of [Files External FTP](https://github.com/owncloud/files_external_ftp) using flysystem. Current project progress can be seen [here](https://github.com/Hemant-Mann/files_external_dropbox/tree/authscheme_builtin)

**Comment by individual-it** [comment]
Just a quick info: Dropbox extended the Dropbox API v1 deprecation timeline. The new date is September 28th, 2017 https://blogs.dropbox.com/developers/2017/06/updated-api-v1-deprecation-timeline/

**Comment by PVince81** [comment]
Thanks, but we should still get moving quickly

**Comment by lefherz** [comment]
@Hemant-Mann I'm writing a https://central.owncloud.org post tomorrow, to inform the community of the v1 API EOL, and that you're writing a new app for this. Can I say that you are happy about contributions?

**Comment by Hemant-Mann** [comment]
Hey @lefherz I guess as part of **GSoC** i'll have to code the app but I'll be happy for suggestions, code reviews, any potential bugs that may be there in the code.

**Comment by stuckj** [comment]
Ah. This explains why dropbox just stopped working for my installation. Looks like the deadline was passed.

**Comment by phil-davis** [comment]
@stuckj have a look at https://github.com/owncloud/files_external_dropbox
v1.0.0 release was tagged a few days ago:
https://github.com/owncloud/files_external_dropbox/releases/tag/v1.0.0

**Comment by sbrl** [comment]
Would that work with nextcloud?

**Comment by lefherz** [comment]
The app is not written to work with nextcloud, I recommend to use it with ownCloud.

**Comment by pmaier1** [comment]
Reference to ownCloud marketplace for official release: https://marketplace.owncloud.com/apps/files_external_dropbox
Closing here.
