### ISSUE TITLE
Exception: Updates between multiple major versions and downgrades are unsupported.

### ISSUE THREAD

**Issue by cromoteca** [owncloud/core#25960]
I got this message and I think it's two bugs in one. First bug is that I simply accepted the update from the web interface: an unsupported update shouldn't be proposed at all. Second bug is that I keep receiving this message every time I try to access my OwnCloud home page, so I can't go back to it and cancel the update. I'm stuck and I can't use my cloud at all.

**Comment by RealRancor** [comment]
@cromoteca Please close here (there is currently nothing to do from oC side here), follow the instructions provided here:

https://central.owncloud.org/t/updates-between-multiple-major-versions-are-unsupported/815

and create a new thread at central if you need further help on how to do a correct upgrade.

**Comment by cromoteca** [comment]
I'm a developer too and this is one of the worst bugs I've ever seen. I didn't chose the update: the web interface has offered it to me. I simply accepted. I restored my old version from backup and I'm not going to upgrade as I'm scared. @RealRancor are you sure that "there is currently nothing to do from oC side here"? I think that fixing the upgrade notifications is quite urgent instead.

**Comment by RealRancor** [comment]
Recent oC versions are already providing the step by step upgrades since quite some time:

https://github.com/owncloud/appstore-issues/issues/4

If that doesn't happen you're either using a very outdated updater URL or oC version. Just some guessing game as you have deleted the issue template shown when creating a new bug and haven't provided any info about your environment.

**Comment by cromoteca** [comment]
I did it because I was stuck at the upgrade page which didn't work, so it was not easy to provide the requested information. Now that I restored, I can tell you that I'm at version 8.0.3 (stable), it suggests upgrading to 8.2.1. The update center allows me to upgrade with a click, but it will fail.

**Comment by cromoteca** [comment]
I guess that the problem is that 8.1 is a major upgrade that cannot be skipped, while the interface just avoids the direct upgrade to 9.x.
