### ISSUE TITLE
updating from 9.0.4 to 9.1 fails with Call to undefined method: setupCron()

### ISSUE THREAD

**Issue by mihailstoynov** [owncloud/core#25962]
I have 9.0.4 running in docker. Updates from 9.0.2 and 9.03 worked fine.
I wanted to update to 9.1.0-apache (the official docker image)

I ran so I can login in the owncloud machine with the www-data user:
$ docker exec -ti owncloud su -s /bin/bash -c '/bin/bash' www-data
then:
$ php occ upgrade
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
 Done
 24/24 [============================] 100%
Checked database schema update
Checking updates of apps
Checking whether the database schema for <activity> can be updated (this can take a long time depending on the database size)
 Done
 2/2 [============================] 100%
Checking whether the database schema for <dav> can be updated (this can take a long time depending on the database size)
 Done
 10/10 [============================] 100%
Checking whether the database schema for <federation> can be updated (this can take a long time depending on the database size)
 Done
 1/1 [============================] 100%
Checking whether the database schema for <files_antivirus> can be updated (this can take a long time depending on the database size)
 Done
 2/2 [============================] 100%
Checking whether the database schema for <files_sharing> can be updated (this can take a long time depending on the database size)
 Done
 1/1 [============================] 100%
Checking whether the database schema for <files_trashbin> can be updated (this can take a long time depending on the database size)
 Done
 1/1 [============================] 100%
Checking whether the database schema for <notifications> can be updated (this can take a long time depending on the database size)
 Done
 1/1 [============================] 100%
Checked database schema update for apps
Updating database schema
Updated database
Updating <federation> ...
PHP Fatal error:  Call to undefined method OCA\Federation\AppInfo\Application::setupCron() in /var/www/html/apps/federation/appinfo/update.php on line 23

### Expected behaviour
to be able to update

### Actual behaviour
had an error:
PHP Fatal error:  Call to undefined method OCA\Federation\AppInfo\Application::setupCron() in /var/www/html/apps/federation/appinfo/update.php on line 23

### Server configuration
**Operating system**:
docker image owncloud:9.1.0-apache
before update I was on owncloud:9.0.4

**Web server:**

**Database:**
mysql:5.7.12

**PHP version:**
whatever is in the docker image

**ownCloud version:** (see ownCloud admin page)
9.1

**Updated from an older ownCloud or fresh install:**
from 9.0.4

**Where did you install ownCloud from:**
official docker image

**Signing status (ownCloud 9.0 and above):**
before installation: No errors have been found.

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
only the default ones and piwik

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
nothing special, added a few trusted domains and a custom theme
both have worked for a while without trouble

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
I'm linking docker volumes, nothing special

**Are you using encryption:** yes/no
file system enc: no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
I update using the console

**Operating system:**
whatever is in the docker image

#### Web server error log
```
not applicable
```

#### ownCloud log (data/owncloud.log)
```
not applicable
```

#### Browser log
```
not applicable

**Comment by DeepDiver1975** [comment]
/var/www/html/apps/federation/appinfo/update.php is  not part of 9.1. You did not upgrade  accordIng to the docs - you have to delete all source files before installing the new Release.

**Comment by mihailstoynov** [comment]
What about my apps, will they be recreated with the proper config?

**Comment by mihailstoynov** [comment]
I mean when I update I preserve data/ config/ themes/ and apps/. Is that correct?
