### ISSUE TITLE
Sharing dialog: Names sorting is case sensitive

### ISSUE THREAD

**Issue by jaller94** [owncloud/core#25971]
### Steps to reproduce
1. Create users: "Peter A.", "peter B.", "Petra".
2. Create a folder and open the Sharing dialog.
3. Type "Pet" into the people search.

![fa7d7634-6bed-11e6-8123-ccd2c94610b1](https://cloud.githubusercontent.com/assets/10872136/18051367/440d24fe-6df4-11e6-8683-87dd3f105a1b.png)
### Expected behaviour

The names should be ordered by the alphabet and case-insensitive. They are sorted like that on the Admin page "Users". "Petra" should be after "peter B.".
### Actual behaviour

"Petra" gets displayed before "peter B." because he starts on a lower p.
### Server configuration

**ownCloud version:** at least from 9.0.2 until 9.1.0

**Updated from an older ownCloud or fresh install:** affects both
### Client configuration

**Browser:** Firefox 45 / Chrome 51

**Operating system:** Ubuntu 16.04 / Windows 7

**Comment by jaller94** [comment]
The same issue in Nextcloud: nextcloud/server#1094.

**Comment by PVince81** [comment]
Which database are you using ?
The sorting might be dependent on the database sort.

Considering that the autocomplete should (I hope!) limit the number of results, it should be possible to re-sort the results using `OC.naturalSortCompare` on the client side.

**Comment by jaller94** [comment]
Both servers do have the issue:

* **sqlite** with Nextcloud 9.0.52
* **MariaDB 10.0.25** with Nextcloud 10.0

They run on the same webserver with PHP 7.0.8.

SQLite3 module version: 0.7-dev

SQLite Library: 3.8.10.2

MySQL Client API version: mysqlnd 5.0.12-dev - 20150407

_(Sorry for posting the results of the Nextcloud instances.. I can't check the ownCloud instances right now.)_

**Comment by PVince81** [comment]
fix through https://github.com/owncloud/core/issues/26950
