### ISSUE TITLE
occ command to migrate data folder

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#25970]
Because moving the data folder can be tricky and require some DB adjustments, it would be a good idea to have this be done with an occ command.

`occ maintenance:migrate-data-folder targetfolder"

As an additional precaution, the current data folder should be saved into the database. If the admin manually changes the folder location in config.php without running the occ command, an error will be displayed in the web UI.

Now you might ask, why not have this old value in the database already and do the migration "on the fly" the next time the web UI is opened ? PHP timeouts could occur...

@tflidd @realrancor @carlaschroeder @deepdiver1975 @butonic thoughts ?

**Comment by PVince81** [comment]
The command would do the following changes:

1. Read old data dir from config.php
1. Check if oc_storages contains a storage with the format "local::" + old data dir (md5'd if required), if yes, rename it to the new path
1. (optional and probably not needed: iterate over all users who might have an unresolved legacy "local::" storage and fix its path as well)
1. Set "datadirectory" in config.php to the target directory
1. Write data directory in "oc_appconfig" as well

**Comment by PVince81** [comment]
As stated above, if the admin manually changed the value in "config.php" to the new data directory, an error will be displayed in the web UI telling the admin to run "occ maintenance:migrate-data-directory". If no argument is given, it would use the value currently passed as new value and the one from oc_appconfig as the old one.

If the admin changed both... boo!

**Comment by RealRancor** [comment]
Sounds good. A lot of people are struggling with this task so a occ command could support them with this task.

> @carlaschroeder

@carlaschroder :smile:

**Comment by carlaschroder** [comment]
Nice. Yes, this is a good thing.

**Comment by mmattel** [comment]
@PVince81 
> The command would do the following changes:

To be added / mentioned: changing into maintenance mode and back when done

https://github.com/owncloud/core/issues/25708 ([Feature Request] ./occ user:logonlist) would be of help as part of the preperation

**Comment by tflidd** [comment]
Just a thing that came into my mind: What if you migrate your setup to a different setup and you don't have a ssh-terminal to run the occ-command?

Is it possible to store the data-directory only in one location in the database or config-file that the user can also change it manually?

**Comment by PVince81** [comment]
Ideally the data dir should only be stored in config.php.

But due to history and legacy reasons, there is still one place where the data dir hard-codes itself to the database and that is for the root storage entry. In practice, that root storage shouldn't be used any more at least since 9.0 or 9.1. There was a time where encryption might have used API calls that would use it indirectly.

**Comment by RealRancor** [comment]
@PVince81 According to your post here the logrotate job is also using an absolute path: https://github.com/owncloud/core/issues/20628

**Comment by PVince81** [comment]
Arghhhhhhh, yes... then that one would need fixing too.

**Comment by cdamken** [comment]
for now a good workaround/recommendation:

for example:
original folder:  var/www/owncloud/data
new folder: /mnt/owncloud

- Turn of the apache.
- Rsync  the folders -> rsync -avz var/www/owncloud/data /mnt/owncloud
- Create a symbolic link  -> ln -s  /mnt/owncloud /www/owncloud/data
- Probably check the permits again. ref: https://doc.owncloud.org/server/9.1/admin_manual/installation/installation_wizard.html#strong-perms-label
- turn on the apache again
 
Then is not necessary the fix and additionally you can move the data folder to a mounted storage.

@PVince81 @pmaier1 What do you think about this?

**Comment by pmaier1** [comment]
> Then is not necessary the fix and additionally you can move the data folder to a mounted storage.

@PVince81 @pmaier1 What do you think about this?

This is the hacky way which works as well, i guess, but we should provide proper ways to do this so thumbs up @PVince81. Btw. why is moving to mounted storage an addition? Should be possible with an occ command as well.

**Comment by PVince81** [comment]
There is no difference between mounted storage or not.

The problem is mostly about hard-coded paths in the DB which need to be updated. It has nothing to do with mounted or not.

I'd like to move this to backlog unless we think it's important for 10.0

**Comment by PVince81** [comment]
Backlog for now, unless someone wants to chime in and implement this ?

**Comment by RealRancor** [comment]
@PVince81 If this is not getting implemented then https://github.com/owncloud/documentation/issues/2303 really needs to be picked up by some one. People are constantly moving their datadir around and breaking their installations.

**Comment by felixboehm** [comment]
datadirectory should not be configured in config.php
- programmatically not writeable in scaleout
- allows admin to change config, which destroys ownCloud

ownCloud would have to handle changes gracefully, if configurable by admin.
So an occ command to (re-)set the datadirectory makes sense, as it allows
- checking and validating the new folder
- change the config in all neccessary places

Last, single place of truth would be category awesome.

I think this brings stability to ownCloud and that is most important.
Yet it would need major changes in the way ownCloud configures stuff.
So I suggest it for planning milestone, would be 10.0.4

**Comment by PVince81** [comment]
Moving "datadirectory" out of config.php would make sense, additionally to the occ command. Note that this config key is read from many different places in the code so would need to touch a lot of places and also hope that apps aren't using it at all (they're supposed to use our FS APIs instead).

**Comment by mmattel** [comment]
imho, one of the main prerequisites is #26861, just my 2c ...

**Comment by PVince81** [comment]
@mmattel not only that, there are now other locations that might include the path to the data directory in "oc_accounts"

**Comment by PVince81** [comment]
When asking @felixboehm about why p1 priority, the discussed turned into this: https://github.com/owncloud/core/issues/29444

**Comment by PVince81** [comment]
- [ ] update log rotate

**Comment by Dino-type-assertion5** [comment]
https://stackdev.space/questions/navigate-to-the-parent-directory-from-the-absolute-path



I sourced the insight
