### ISSUE TITLE
Override of core language strings for mailtemplates not working for custom theme

### ISSUE THREAD

**Issue by danielkoch** [owncloud/core#25989]
### Steps to reproduce
1. Create custom theme `<custom-theme>` under `<owncloud>/themes/`
2. Create file `<owncloud>/themes/<custom-theme>/core/l10n/en_GB.js`
3. Insert content:

```
OC.L10N.register(
    "core", {
        "Hey there,<br><br>just letting you know that %s shared <strong>%s</strong> with you.<br><a href=\"%s\">View it!</a><br><br>" : "Hey there owncloud change,<br><br>just letting you know that %s shared <strong>%s</strong> with you.<br><a href=\"%s\">View it!</a><br><br>",
    },
    "nplurals=2; plural=(n != 1);"
);
```
1. Create file `<owncloud>/themes/<custom-theme>/core/l10n/en_GB.json`
2. Insert content:

```
{
    "translations": {
        "Hey there,<br><br>just letting you know that %s shared <strong>%s</strong> with you.<br><a href=\"%s\">View it!</a><br><br>" : "Hey there owncloud change,<br><br>just letting you know that %s shared <strong>%s</strong> with you.<br><a href=\"%s\">View it!</a><br><br>",
    },
    "pluralForm": "nplurals=2; plural=(n != 1);"
}
```
### Expected behaviour

The translated language string should be used for the share notification mail (mail should start with "Hey there owncloud change, ...").
### Actual behaviour

The default language string is used (mail starts with "Hey there, ..."), string coming from https://github.com/owncloud/core/blob/master/core/l10n/en_GB.json#L279
### Server configuration

**Operating system**:
CentOS

**Web server:**
Apache

**Database:**
MySQL
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
9.1.0

**Where did you install ownCloud from:**
Archive file

**Comment by danielkoch** [comment]
**Update:**
For me it is totally unclear where the translations and also the templates are coming from. For me:
1. Translation for the the configurable mails doesn't work at all (created an individual mail template under `<owncloud>/themes/<custom-theme>/templates/mail.php` (this template is not used by ownCloud and also the mail is not translated into the language the users has selected in his settings)
2. Even if I change the core translation files (f.e. https://github.com/owncloud/core/blob/master/core/l10n/en_GB.json#L232) the mail content doesn't change

**Comment by PVince81** [comment]
This should work. Now you say you changed "en_GB", so the question is whether the mail sending code is actually using this locale or "en_US". I believe the chosen locale is based on what the recipient picked as their locale settings in the personal page.

**Comment by PVince81** [comment]
Okay, I did the override like you did and made sure the recipient has selected "en_GB" as language.

You're right, the email doesn't get translated for some reason.

**Comment by PVince81** [comment]
Hmm, even if I pick french, it seems the mail doesn't care about the language.

I also found this ticket: https://github.com/owncloud/core/issues/25989

**Comment by PVince81** [comment]
Indeed, here's the ticket in question https://github.com/owncloud/core/issues/7417
