### ISSUE TITLE
Encryption module is not able to read file

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/core#25980]
Lately, we have an issue with the encryption module being unable to read/decrypt files:
"reqId":"V8UbhPdwa8bN6xxAGYQlvgAAAAk","remoteAddr":"N.N.N.N","app":"no app in context","message":"Exception: {\"Exception\":\"OC\\Encryption\\Exceptions\\DecryptionFailedException\",\"Message\":\"Encryption module \\"Default encryption module\\" is not able to read
app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 503 Encryption not ready: Private Key missing for user: please try to log-out and log-in again\"

The web UI login warns about Invalid private key for Encryption app. Please update your private key password in your personal settings.
The personal settings change password field i can see: your private key password no longer matches your log-in password.
 Attempt to update private key password  hangs with "save in progress". 
### Steps to reproduce
1. Change password for a user on an oC instance with encryption enabled.
   2.Login and enter password to update private key
2. Sync data using the client and get 503/operation failes.
### Expected behaviour

Tell us what should happen
### Actual behaviour

Tell us what happens instead
### Server configuration

**Operating system**:
Centos 6.7
**Web server:**
Nginx reverse proxy + Apache 2.4
**Database:**
MariaDB 10.0
**PHP version:**
5.6.23
**ownCloud version:** (see ownCloud admin page)
stable9
**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**
git stable9

"system": {
        "instanceid": "",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "sub.example.com",
            "www.sub.example.com"
        ],
        "datadirectory": "\/home\/sub.example.com\/data",
        "dbtype": "mysql",
        "version": "9.0.5.0",
        "dbname": "oc_01",
        "dbhost": "sub.example.com",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "apps_paths": [
            {
                "path": "\/home\/sub.example.com\/apps",
                "url": "\/apps",
                "writable": true
            },
        ],
        "filesystem_check_changes": 0,
        "memcache.local": "\OC\Memcache\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\OC\Memcache\Redis",
        "redis": {
            "host": "N.N.N.N",
            "port": 6379
        },
        "theme": "custom",
        "maintenance": false,
        "loglevel": 0,
        "mail_smtpmode": "php",
        "trashbin_retention_obligation": "auto",
        "singleuser": false
    }

**Are you using external storage, if yes which one:** none

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** None

**Comment by fossxplorer** [comment]
This issue has been existent already on 9.0.2 (prior to upgrade to 9.0.5). Right now i'm on RC1/stable9 as noted above.

**Comment by PVince81** [comment]
> Sync data using the client and get 503/operation failes.

Did you try restarting the sync client? It is likely that it's still using the old session which contains the old encryption key that doesn't match the new password.

Note that starting with 9.1 changing a user's password will kick out all their sessions which would solve such issues.

**Comment by PVince81** [comment]
Closing due to lack of feedback, cannot reproduce
