### ISSUE TITLE
Avatar image resolving doesn't support case change in uid.

### ISSUE THREAD

**Issue by digination** [owncloud/core#25993]
### Steps to reproduce
1. create an user with a mixed-case uid, say 'SilentBob'
2. add an avatar to it.
3. Try to resolv SilentBob's avatar from the url: http://owncloud_fqdn/index.php/avatar/silentbob/64.
### Expected behaviour

http://owncloud_fqdn/index.php/avatar/silentbob/64 should return the avatar of SilentBob, since most of the user functions in OC are ignoring case.
### Actual behaviour

Whe ngoing to http://owncloud_fqdn/index.php/avatar/silentbob/64, the avatar is not returned, and only a json string with data: {'displayname': 'silentbob'} is displayed.
### Resolving clue

The main problem comes from the fact that in userManager.get() , testing user existance and retrieving of user infos are 2 different functions:

```
public function get($uid) {

                if (isset($this->cachedUsers[$uid])) { //check the cache first to prevent having to loop over the backends
                        return $this->cachedUsers[$uid];
                }

                foreach ($this->backends as $backend) {

                        // userExists MUST return the REAL, MIXED CASE UID and not just a boolean !
                        if ($backend->userExists($uid)) {

                           //So that getUserObject() will have the REAL, MIXED CASE UID.
                            return $this->getUserObject($uid, $backend);
                        }
                }
                return null;
}

```
### Server configuration

**Operating system**:
Ubuntu Server 16.04 LTS x84
**Web server:**
Apache 2.4
**Database:**
sqlite 3
**PHP version:**
7.0.8
**ownCloud version:** (see ownCloud admin page)
9.0.2
**Updated from an older ownCloud or fresh install:**
Fresh
**Where did you install ownCloud from:**
git
**Signing status (ownCloud 9.0 and above):**

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

```

**List of activated apps:**

```

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

```

**The content of config/config.php:**

```

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```

With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT \* FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.

```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```

Insert your webserver log here

```

#### ownCloud log (data/owncloud.log)
```

Insert your ownCloud log here

```

#### Browser log
```

Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...

```
```

**Comment by PVince81** [comment]
Is there any place in the OC code that calls the URL all lower case ? I'd expect any code paths to always use the user id as it is.

**Comment by digination** [comment]
Honestly I don't know for OC core , but i know for a fact that the case can occur in 3rd part apps.

**Comment by PVince81** [comment]
Please try again with https://github.com/owncloud/core/pull/26271#issuecomment-251881034 which should fix user casing issues with avatar request.
