### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function getRequest()

### ISSUE THREAD

**Issue by Sailing74** [owncloud/core#25996]
### Steps to reproduce
1. Try to access main owncloud URL

### Expected behaviour
The owncloud welcome/login page should load.

### Actual behaviour
Timeout / Error 500

### Server configuration
**Operating system**: 
Ubuntu 16.04.1

**Web server:** 
Apache2 2.4.18

**Database:** 
mysql 5.7.13

**PHP version:** 
PHP 7.0.8

**ownCloud version:** 
9.0.4-1.1 (see ownCloud admin page)
(admin page not accessible, see above)

**Updated from an older ownCloud or fresh install:** 
updated from 8.2.3

**Where did you install ownCloud from:**
repos

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Login not possible

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '51f6b97ddcbb5',
  'passwordsalt' => 'xxx',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '9.0.4.1',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'loglevel' => '1',
  'log_rotate_size' => 10485760,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'www.mydomain.com',
    1 => '192.168.1.103',
  ),
  'share_folder' => '/Shared',
  'mail_domain' => 'mydomain.com',
  'mail_from_address' => 'postmaster',
  'mail_smtpdebug' => false,
  'mail_smtpmode' => 'sendmail',
  'logtimezone' => 'Europe/Berlin',
  'overwrite.cli.url' => 'https://www.mydomain.com/owncloud',
  'secret' => 'xxx',
  'trashbin_retention_obligation' => 'auto',
  'updatechecker' => false,
  'htaccess.RewriteBase' => '/owncloud',
);

```

**Are you using external storage, if yes which one:** 
owncloud sits on nfs mount

**Are you using encryption:** 
yes

**Are you using an external user-backend, if yes which one:** 
no

### Client configuration
**Browser:**
any

**Operating system:**
any

#### Web server error log
```
[Wed Aug 31 18:31:23.360595 2016] [:error] [pid 2706] [client 192.168.1.3:51038] PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /var/www/owncloud/lib/public/util.php:166\nStack trace:\n#0 /var/www/owncloud/index.php(51): OCP\\Util::logException('index', Object(Exception))\n#1 {main}\n  thrown in /var/www/owncloud/lib/public/util.php on line 166
[Wed Aug 31 18:31:47.369043 2016] [:error] [pid 2632] [client 192.168.2.29:50363] PHP Fatal error:  Uncaught Error: Call to a member function getRequest() on null in /var/www/owncloud/lib/private/response.php:77\nStack trace:\n#0 /var/www/owncloud/status.php(51): OC_Response::setStatus(500)\n#1 {main}\n  thrown in /var/www/owncloud/lib/private/response.php on line 77
[Wed Aug 31 18:31:53.385855 2016] [:error] [pid 3419] [client 192.168.1.3:51039] PHP Fatal error:  Uncaught Error: Call to a member function getRequest() on null in /var/www/owncloud/lib/private/response.php:77\nStack trace:\n#0 /var/www/owncloud/status.php(51): OC_Response::setStatus(500)\n#1 {main}\n  thrown in /var/www/owncloud/lib/private/response.php on line 77
[Wed Aug 31 18:32:05.416679 2016] [:error] [pid 3420] [client 192.168.1.24:55851] PHP Fatal error:  Uncaught Error: Call to a member function getRequest() on null in /var/www/owncloud/lib/private/response.php:77\nStack trace:\n#0 /var/www/owncloud/status.php(51): OC_Response::setStatus(500)\n#1 {main}\n  thrown in /var/www/owncloud/lib/private/response.php on line 77
```

#### ownCloud log (data/owncloud.log)
no log created

#### Browser log
n.a.

**Comment by RealRancor** [comment]
Most likely a permission issue like discussed here: https://github.com/owncloud/core/issues/19959

**Comment by Sailing74** [comment]
Well, the permissions for config.php look good to me:

```
/var/www/owncloud/config# ls -l
-rw-r----- 1 www-data www-data  1056 Aug  7 12:24 config.php
-rwxrwxr-- 1 www-data www-data 39446 Jul 18 19:40 config.sample.php
-rwxrwxr-- 1 www-data www-data   105 Jul 19 17:29 disable-updatechecker.config.php
```

To be sure, I also reran the permissions script from [https://doc.owncloud.org/server/9.0/admin_manual/installation/installation_wizard.html#strong-perms-label](url), but that didn't change anything, either.

Happy to check any other permissions, but I don't quite know which, as the error messages don't tell me a lot...

**Comment by ZWS2014** [comment]
@Sailing74 I ran into the same problem. It transpired to be a misconfiguration in config.php - in my case, I missed a comma in an array. So, I'd suggest double checking your config.php for typos etc.

Perhaps the dev team might consider a config sanity check which throws an appropriate error in the event that it's been corked ...

**Comment by Sailing74** [comment]
Thanks. Out of some desperation, I gave Nextcloud a try. Not sure what's different, but it's working for me now. So I guess I'll close this issue.

**Comment by RealRancor** [comment]
> Not sure what's different, but it's working for me now.

Most likely that it is a fresh (non-broken / wrong configured) installation and the same would have worked if you did a fresh installation with ownCloud.

**Comment by hutber** [comment]
I've the same problem now and there are no errors in my file, nor permissions and still having it sadly!
