### ISSUE TITLE
Generate JS files from translation JSON

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26005]
Now that we have a makefile, we can do this:
- add a new target "l10n-js"
- the target creates a "build" folder inside every "l10n" and generates the JS file required for loading it in the JS side
- change JS code to load the file from the build folder

That is, unless we decide that non-async JS apps are not allowed any more and require every app to have entry points in which case we could read the json file asynchronously, always.

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
well - both js and json translation files are generated. Generating js from json will just add another step but what will be the benefit? We still need to ship both files.

but maybe I missunderstand?

**Comment by PVince81** [comment]
yeah... no benefit unless we add the generation step for both inside the makefile.
