### ISSUE TITLE
nginx - Hint on example

### ISSUE THREAD

**Issue by Speedy1991** [owncloud/core#26026]
### Steps to reproduce
1. LTS 16.04 Ubuntu Server
2. Fresh OwnCloud 9.1
3. nginx version: nginx/1.10.0 (Ubuntu)

### Expected behaviour
All Icons should be shown

### Actual behaviour
*.svg are not shown (e.g. add.svg in the upper left corner for creating folders/files)

### Fix:
- Mime Type have to be set in */etc/nginx/mime.types*:

    image/svg+xml                         svg svgz;

Would be nice to add this hint in the nginx example (on the homepage)
(https://doc.owncloud.org/server/9.0/admin_manual/installation/nginx_owncloud_9x.html)

**Comment by RealRancor** [comment]
@Speedy1991 If that mimetype is missing in the Ubuntu package please directly report a bug to them. Thats nothing what should be solved by oC

**Comment by RealRancor** [comment]
@Speedy1991 Have re-verified this:

- archives from https://nginx.org/en/download.html
- packages from www.dotdeb.org
- packages from Debian (1.6.2 from stable and 1.10.1 from testing

 includes the ``image/svg+xml svg svgz;`` in the mime.types.

 So please close here and report this as a bug to Ubuntu, this is really nothing what should be documented within the documentation of a web application.

**Comment by RealRancor** [comment]
And just tested with http://packages.ubuntu.com/xenial/all/nginx-common/download which also includes the ``image/svg+xml svg svgz;``

:question:

**Comment by Speedy1991** [comment]
Well thats strange, i just tested in a VM and u are right.
On my two vServers (fresh installed)
*image/svg+xml svg svgz;*
was missing.
Thanks for your help

**Comment by RealRancor** [comment]
It still might be interesting why you didn't had that in your mime.types file. I don't think that you have deleted only that one so maybe that was a bug in previous Ubuntu versions?
