### ISSUE TITLE
re:    OneDrive folder disappears after Renaming during synch-- https://github.com/owncloud/core/issues/7046

### ISSUE THREAD

**Issue by netrover18** [owncloud/core#26028]
This closed thread describes what happened to me.  In my case, I was synching some photos between my laptop (Windows 10) and OneDrive.  I changed the name of the folder from Pictures to Photos, then a popup appeared that said" OneDrive requests permission to upload 2 files" which I think I closed, and then the file disappeared.  It was very quick.  The file is not in my Recycle Bin, and cannot be located in Search Everything (using Photos and Pictures).

The thread addressed a bunch of technical issues, but I don't think any of them mentioned whether or not a file that disappears due to this glitch can be retrieved.  Can my photos be retrieved?  Thanks for any help.

**Comment by PVince81** [comment]
Please note that this is a bug tracker but not a support platform: http://owncloud.org/support

If you think you found a bug, please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

So far I don't see any relationship between ownCloud and OneDrive here.
