### ISSUE TITLE
How to recover files by using the recovery key?

### ISSUE THREAD

**Issue by owndude** [owncloud/core#26022]
I just don't see the field where to use it. I have set it (even changed the password for it now), and I am the user who needs to recover his files (admin). Where is the field where I can enter the password and decrypt my files?

P.S. I asked in the forums, but was pointed here by a member after no answer was given.

**Comment by PVince81** [comment]
Did you check the personal page ?

**Comment by PVince81** [comment]
See https://doc.owncloud.org/server/9.1/admin_manual/configuration_files/encryption_configuration.html

and if you're trying to decrypt the files, see the "decrypt-all" command with user argument here https://doc.owncloud.org/server/9.1/admin_manual/configuration_server/occ_command.html
