### ISSUE TITLE
Owncloud/Nextcloud and contacts apps (iOS 5.1.1)

### ISSUE THREAD

**Issue by GH16** [owncloud/core#26024]
### Steps to reproduce
Add contacts with an iPad1 with the last iOS version (5.1.1) with an Owncloud/Nextcloud HTTPS connection

### Expected behaviour
The Owncloud/NextCloud contacts are shown in the iOS 5.1.1 App

### Actual behaviour
As soon as I have entered all information and try to save the settings the following error appears: Connection via SSL not possible. Do you like to configure the account without SSL

**Database:**
mysql

**ownCloud version:** (see ownCloud admin page)
Nextcloud and Ownloud

### Client configuration
iOS 5.1.1 contacs App

**Operating system:**
iOS 5.1.1

**Comment by RealRancor** [comment]
Hi,

i think thats most likely a configuration / environment issue where you can get better support at https://central.owncloud.org/
