### ISSUE TITLE
Filepicker folder selection is not possible any more

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26034]
### Steps

1. Open the web browser with a logged in user
1. Create a folder "test"
1. Run the following code in the JS console:
```
                OC.dialogs.filepicker(
                    'Please select a folder',
                    function() { console.log('done: ', arguments); },
                    false,
                    'httpd/unix-directory'
                );
```
1. Click the folder "test"
1. Click "Choose"

### Expected result
"Choose" button can be clicked

### Actual result
"Choose" button is disabled, selection is impossible.

### Versions
9.2 pre-alpha / git master
Regression introduced through https://github.com/owncloud/core/pull/25900

@sharidas mind having a look ? I think you need to check if the filter mime type is "httpd/unix-directory", then don't disable the "Choose" button.

Note: setting to high because it breaks some apps that require folder selection (like files_drop)

**Comment by sharidas** [comment]
@PVince81 Sure I will take a look into it.
