### ISSUE TITLE
Bad array wrapping in DependencyAnalyzer.php::analyzeCommands()

### ISSUE THREAD

**Issue by Worst45** [owncloud/core#26073]
Bug tested in Owncloud version 9.1.0.

I made an app with following dependencies in info.xml:
```xml
<dependencies>
	<command os="Linux">/usr/local/bin/myscript.sh</command>
	<os>Linux</os>
	<owncloud min-version="9.1" max-version="9.2" />
</dependencies>

```

When I try to enable it, I have the following error:

>     The command line tool Array could not be found
>     The command line tool /usr/local/bin/myscript.sh could not be found
> 

(OK for the second line, I must add the folder to php config or whatever.)
The problem is the 1st line...

In your code (`/lib/private/App/DependencyAnalyzer.php::analyzeCommands()`), your analyzer try to wrap single command in an array of commands, to parse it easily:
```php
if (!is_array($commands)) {
	$commands = array($commands);
}
```
But this is wrong, as a single command is ALSO an array.

I fixed it by adding some tests on your condition, like this:
```php
$isArray = array($commands);
if (! $isArray || ($isArray && (isset($commands['@attributes']) || isset($commands['@value'])))) {
	$commands = array($commands);
}
```

(Not very sexy, but it works)

**Comment by DeepDiver1975** [comment]
looks reasonable - mind submitting a pr? THX

**Comment by Worst45** [comment]
I never did it before... I will try be please be patient :)

**Comment by DeepDiver1975** [comment]
this can be fixed just like this - https://github.com/owncloud/core/pull/26295/files#diff-570f12cecdb80862500a0f7a963f99c6R226
