### ISSUE TITLE
 Changes in Quota behaviour with Owncloud 9 & LDAP

### ISSUE THREAD

**Issue by christianlx** [owncloud/core#26074]
Hi,
since 2 years we use Owncloud in our company, we've used the quota functionnality as this :

LDAP connection from an active Directory
In the LDAP configurator, advanced tab, default quota is set to 2GB. In the quota field, we put "title"

The behaviour was that everyone with a blank title field in his AD account property had 2 GB. For users with special needs we changed the title field in Active Directory with 3 GB for example. This has always work with 7, 8, 8.1, 8.2

Since I've updated to 9, it still works for old users but for new ones, I'm obliged to set the "quota field" to 2GB in Active Directory. If I don't, the new user is stucked with a 0 bytes free space.

Is there anyone here has the same problem ? Bug ou not ? I didn't find anything in the documentation about a change of this feature.

Regards,
Christian.
### Steps to reproduce
1. Set 2GB as default and leave the choosen ldap field blank
2. The quota is 0 whereas before 9 was 2G
   3.
### Expected behaviour

The new user should have the default Owncloud quota
### Actual behaviour

New user avec 0 bytes
### Server configuration

**Operating system**: 
Centos 6.8

**Web server:** 
apache

**Database:**
MySQL

**PHP version:** 
5.5

**ownCloud version:** (see ownCloud admin page)
9.0.4

**Updated from an older ownCloud or fresh install:**
Updated from 8.2 without errors

**Where did you install ownCloud from:**
Owncloud repo for Centos

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
Only officials (calendars and contacts)

```


**The content of config/config.php:**

```

 "system": {
        "instanceid": "oc9a639e41f5",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "myurl.com"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/myurl\/ownclou                                                                                 d",
        "dbtype": "mysql",
        "version": "9.0.4.1",
        "dbname": "OWNCLOUD",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "installed": true,
        "forcessl": true,
        "ldapIgnoreNamingRules": false,
        "ldapUserCleanupInterval": 180,
        "mail_domain": "mydomain.com",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "mymailserver.com",
        "mail_smtpport": 587,
        "mail_smtpauth": true,
        "mail_smtpname": "**_REMOVED SENSITIVE VALUE**_",
        "mail_smtppassword": "**_REMOVED SENSITIVE VALUE**_",
        "theme": "",
        "maintenance": false,
        "logtimezone": "Europe\/Paris",
        "memcache.local": "\OC\Memcache\APCu",
        "logfile": "\/var\/log\/owncloud.log",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "loglevel": 2,
        "updatechecker": false,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
YES
#### LDAP configuration (delete this part if not used)

```

| hasMemberOfFilterSupport      | 1                                                                                                                                                                                             |
| hasPagedResultSupport         |                                                                                                                                                                                               |
| homeFolderNamingRule          |                                                                                                                                                                                               |
| lastJpegPhotoLookup           | 0                                                                                                                                                                                             |
| ldapAgentName                 | CN=service ad,OU=Services,DC=,DC=,DC=com                                                                                                                                    |
| ldapAgentPassword             | **\*                                                                                                                                                                                           |
| ldapAttributesForGroupSearch  |                                                                                                                                                                                               |
| ldapAttributesForUserSearch   |                                                                                                                                                                                               |
| ldapBackupHost                | mydcbackup.mydomain.com                                                                                                                                                               |
| ldapBackupPort                | 389                                                                                                                                                                                           |
| ldapBase                      | DC=,DC=,DC=com                                                                                                                                                              |
| ldapBaseGroups                | DC=,DC=,DC=com                                                                                                                                                              |
| ldapBaseUsers                 | DC=,DC=DC=com                                                                                                                                                              |
| ldapCacheTTL                  | 600                                                                                                                                                                                           |
| ldapConfigurationActive       | 1                                                                                                                                                                                             |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                                               |
| ldapEmailAttribute            | mail                                                                                                                                                                                          |
| ldapExperiencedAdmin          | 0                                                                                                                                                                                             |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                                               |
| ldapExpertUUIDUserAttr        | sAMAccountName                                                                                                                                                                                |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                                                                                                |
| ldapGroupDisplayName          | cn                                                                                                                                                                                            |
| ldapGroupFilter               | (&(|(objectclass=group))(|(cn=OWNCLOUD*)))                                                                                                                                                    |
| ldapGroupFilterGroups         | OWNCLOUD                                                                                                                                                                                      |
| ldapGroupFilterMode           | 1                                                                                                                                                                                             |
| ldapGroupFilterObjectclass    | group                                                                                                                                                                                         |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                                                        |
| ldapHost                      | mydc.mydomain.com                                                                                                                                                               |
| ldapIgnoreNamingRules         |                                                                                                                                                                                               |
| ldapLoginFilter               | (&(&(|(objectclass=user))(|(memberof=CN=OWNCLOUD,OU=Fonctionnels,OU=Groupes,DC=,DC=,DC=com)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))(|(mail=%uid)))) |
| ldapLoginFilterAttributes     | mail                                                                                                                                                                                          |
| ldapLoginFilterEmail          | 1                                                                                                                                                                                             |
| ldapLoginFilterMode           | 0                                                                                                                                                                                             |
| ldapLoginFilterUsername       | 1                                                                                                                                                                                             |
| ldapNestedGroups              | 0                                                                                                                                                                                             |
| ldapOverrideMainServer        | 0                                                                                                                                                                                             |
| ldapPagingSize                | 500                                                                                                                                                                                           |
| ldapPort                      | 389                                                                                                                                                                                           |
| ldapQuotaAttribute            | title                                                                                                                                                                                         |
| ldapQuotaDefault              | 2GB                                                                                                                                                                                           |
| ldapTLS                       | 0                                                                                                                                                                                             |
| ldapUserDisplayName           | displayname                                                                                                                                                                                   |
| ldapUserDisplayName2          |                                                                                                                                                                                               |
| ldapUserFilter                | (&(|(objectclass=user))(|(memberof=CN=OWNCLOUD,OU=Fonctionnels,OU=Groupes,DC=,DC=a,DC=com)))                                                                                 |
| ldapUserFilterGroups          | OWNCLOUD                                                                                                                                                                                      |
| ldapUserFilterMode            | 1                                                                                                                                                                                             |
| ldapUserFilterObjectclass     | user                                                                                                                                                                                          |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                                          |
| ldapUuidUserAttribute         | auto                                                                                                                                                                                          |
| turnOffCertCheck              | 0                                                                                                                                                                                             |
| useMemberOfToDetectMembership | 1                                                              

```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```

Insert your webserver log here

```

#### ownCloud log (data/owncloud.log)
```

No error inside

```

#### Browser log
```

Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...

```
```

**Comment by PVince81** [comment]
@cdamken @felixboehm @owncloud/ldap known issue ?

**Comment by PVince81** [comment]
@jvillafanez

**Comment by PVince81** [comment]
@cdamken @jvillafanez have you seen this quota behavior change before ?

**Comment by jvillafanez** [comment]
So far I've only reproduced the issue hacking the DB and setting the quota for the target user as empty (`""`, not null).
```
mysql> select * from preferences;
+--------+----------------+-----------+-------------+
| userid | appid          | configkey | configvalue |
+--------+----------------+-----------+-------------+
| admin  | core           | lang      | en          |
| admin  | files          | quota     |             |
| admin  | firstrunwizard | show      | 0           |
| admin  | login          | lastLogin | 1489393616  |
+--------+----------------+-----------+-------------+
```
@christianlx could you verify this for the affected accounts?

I still need to investigate how the ldap app sets that empty value in the DB.

There is also something really weird if the quota attribute has a value without whitespace trimming.

I wonder if the LDAP app is feching empty values somehow from the LDAP server, specially the quota one.

**Comment by christianlx** [comment]
Hi, 

since this bug, Ive updated to 9.0.8. The problem is not exactly the same. Here's the evolution. 

I've just created this test account ochr-e1mxxx, here's the mysql record

![image](https://cloud.githubusercontent.com/assets/10811230/23861450/5afe62da-080a-11e7-88fc-9a3fdde80c8b.png)

Here's the default quota in the general config

![image](https://cloud.githubusercontent.com/assets/10811230/23861481/76ca20e4-080a-11e7-9ae9-34d8018a747c.png)

In the AD account, i let the title field blank

![image](https://cloud.githubusercontent.com/assets/10811230/23861517/97049e02-080a-11e7-9028-ae818b8d625e.png)

I should have for this user a 2Gb quota... but when I log on....

![image](https://cloud.githubusercontent.com/assets/10811230/23861580/c9823f10-080a-11e7-868e-3c8ae4a15aed.png)

I have 1 GB, just amazing....

**Comment by butonic** [comment]
@christianlx Can you show us the result of
```sql
SELECT * FROM oc_preferences WHERE userid="ochr-e1mxxx"
```

after a login there should be an entry with the quota
```
| ochr-e1mxxx  | files          | quota     | ?           |
```

@jvillafanez 
```php
<php
var_dump(\OC_Helper::computerFileSize(''));
var_dump(\OC_Helper::computerFileSize(' '));
var_dump(OC_Helper::humanFileSize(false));
```
both computerFileSize calls return false. The humanFileSize call produces `string(2) " B"` which is ... broken IMO. In any case `setQuota('')` might store `" B"` in the preferences table: https://github.com/owncloud/core/blob/stable9.1/lib/private/User/User.php#L359-L364

But only if the `updateQuota()` call tries to pass an empty string or string containing only spaces: https://github.com/owncloud/core/blob/stable9.1/apps/user_ldap/lib/User/User.php#L459-L478

It might make sense to change `isset($ldapEntry[$attr])` to `!empty(trim($ldapEntry[$attr][0]))` in https://github.com/owncloud/core/blob/stable9.1/apps/user_ldap/lib/User/User.php#L166-L166

Hmmm no empty won't work if quota has been set to `0`. So we need to use isset and manually check for 'emptyness', eg: `if(isset($ldapEntry[$attr][0]) && trim($ldapEntry[$attr][0]) !== '' ) {`

better yet, log an error if the value is empty so the admin has a chance of finding the problem.

**Comment by christianlx** [comment]
Here's the result

mysql> select * FROM oc_preferences WHERE userid="ochr-e1mxxx";
+-------------+-----------+------------------------+---------------+
| userid      | appid     | configkey              | configvalue   |
+-------------+-----------+------------------------+---------------+
| ochr-e1mxxx | core      | lang                   | fr            |
| ochr-e1mxxx | core      | timezone               | Europe/Berlin |
| ochr-e1mxxx | login     | lastLogin              | 1489419172    |
| ochr-e1mxxx | user_ldap | displayName            | ochr-e1mxxx   |
| ochr-e1mxxx | user_ldap | firstLoginAccomplished | 1             |
| ochr-e1mxxx | user_ldap | homePath               |               |
| ochr-e1mxxx | user_ldap | lastFeatureRefresh     | 1489419172    |
| ochr-e1mxxx | user_ldap | uid                    | ochr-e1mxxx   |
+-------------+-----------+------------------------+---------------+
8 rows in set (0.00 sec)

**Comment by christianlx** [comment]
Just FYI, I've updated today my server to 9.1.4. No other changes (still Centos 6.8, php 5.5). 
- The bug is still here
- The request result on oc_preferences table is the same.

Regards,
Christian.

**Comment by jvillafanez** [comment]
https://github.com/owncloud/user_ldap/pull/64 might fix this or at least help to debug what's going on.

You might want to try the patch inside an ownCloud VM to verify it solves your problem. Don't apply patches on production!

I expect the patch to be in 10.0 and likely to be backported to previous versions. Stay tuned.

**Comment by PVince81** [comment]
please try with 9.1.5 RC1

**Comment by cdamken** [comment]
@PVince81 Does this fix https://github.com/owncloud/enterprise/issues/1865 too?

**Comment by jvillafanez** [comment]
It should. Note the cases described in the PR to know what are the expectations for the quota.

**Comment by christianlx** [comment]
I've updated my two servers today, bug is fixed. Thanks to all.

**Comment by PVince81** [comment]
great to hear!
