### ISSUE TITLE
RC2: code integrity complaints 

### ISSUE THREAD

**Issue by thommierother** [owncloud/core#26084]
RC2 from http://download.owncloud.org/community/testing/owncloud-9.1.1RC2.tar.bz2 shows a number of failed code integrity checks:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- updater/vendor/guzzlehttp/guzzle/.editorconfig
		- updater/vendor/guzzlehttp/guzzle/phpunit.xml.dist
		- updater/vendor/guzzlehttp/guzzle/.gitignore
		- updater/vendor/guzzlehttp/guzzle/build/packager.php
		- core/doc/admin/operations/scaling_multiple_machines.html
		- core/doc/admin/operations/theming.html
		- core/doc/admin/operations/considerations_on_monitoring.html
		- core/doc/admin/operations/index.html
		- core/doc/admin/_sources/operations/theming.txt
		- core/doc/admin/_sources/operations/scaling_multiple_machines.txt
		- core/doc/admin/_sources/operations/considerations_on_monitoring.txt
		- core/doc/admin/_sources/operations/index.txt
		- core/doc/admin/_images/scaling-2.png
		- core/doc/admin/_images/scaling-1.png
		- core/doc/admin/_images/scaling-3.png
		- core/doc/admin/_images/scaling-4.png
		- core/doc/admin/_images/scaling-5.png

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [updater/vendor/guzzlehttp/guzzle/.editorconfig] => Array
                        (
                            [expected] => 
                            [current] => 0d0045db995a39ded163cdcfe6a479094c56d4fffc69a12e9610cedf0d7c8720a7d63be71115bbe6f27e42ffede0ef13857f6471a7e84d05ab25a6b092d118a6
                        )

                    [updater/vendor/guzzlehttp/guzzle/phpunit.xml.dist] => Array
                        (
                            [expected] => 
                            [current] => 347f6428cf0251a6f7a5e4d733704cd1ae678753deb707f42a47f43cbcc0285f1bbae93356a033d8287c67656560d503e3cb4ffb2e8a21dfb172b2d8b2d8ecc6
                        )

                    [updater/vendor/guzzlehttp/guzzle/.gitignore] => Array
                        (
                            [expected] => 
                            [current] => 02a5899bcc65148dc7a419391b26cba2152b425970eef5d7a6ea803ffae90f9aafc2aceb3ef40f78ab86ce6df619683570496d1b6a1aa719aefa59384e69f8c5
                        )

                    [updater/vendor/guzzlehttp/guzzle/build/packager.php] => Array
                        (
                            [expected] => 
                            [current] => bcca8cf3b9b99a7a5d41bcdb529df4f6551439faad4394852d17e93c125fc0b3564f83e4870b3a85ac19a51baeead871bdd1df60def25a4c9c04ab72fe017b10
                        )

                    [core/doc/admin/operations/scaling_multiple_machines.html] => Array
                        (
                            [expected] => 
                            [current] => 413cca15143dc6663f250fbcdd609c06790ecaff289c6707f49d37b2a65dc5f4dd8383f9ff60e31e368048ad32e3705a42a2f99d9a666ca74470d6e13dbb4742
                        )

                    [core/doc/admin/operations/theming.html] => Array
                        (
                            [expected] => 
                            [current] => 7e3489850d92fecba0a41b63bc2e7c1fa55ce6aa793d162a9b62f5f567e30a470ddb97a40322255333d59c9877bdc37e74d9ff2c01860ae5b9cbd028edf9e2c3
                        )

                    [core/doc/admin/operations/considerations_on_monitoring.html] => Array
                        (
                            [expected] => 
                            [current] => c21c5b9516b7cfa449e397d394a5f2e86b2ed009a8766db2909d5844c28e975ac1939c8b8df883fa4034d50134f37ce77a80420f3b95d3f7606c4e2d1049886f
                        )

                    [core/doc/admin/operations/index.html] => Array
                        (
                            [expected] => 
                            [current] => d57fb872a7a9fc0c515a7ce3417801472e9519c961cf9614e8f5f43cf72c0b2b6e64e0557030e1c206f2a2bab795eb61946ca7a3b1cc5186af92015c72d50304
                        )

                    [core/doc/admin/_sources/operations/theming.txt] => Array
                        (
                            [expected] => 
                            [current] => c55457bd79e6db0aede0d08e73d96195a992e3e72f77c466904637d03247f91591d5033e9ad44e7948578e940cfb1f05226165c40e2761f4d9f0be4e2f99814f
                        )

                    [core/doc/admin/_sources/operations/scaling_multiple_machines.txt] => Array
                        (
                            [expected] => 
                            [current] => d09e012c412c1d0c53636eb09797671149624fd40946a74907137d9b1aa350a35cd03e7e1f91690802ccd032bdb4c48d06f534892a09c47a5f6eaa0b50691719
                        )

                    [core/doc/admin/_sources/operations/considerations_on_monitoring.txt] => Array
                        (
                            [expected] => 
                            [current] => 39afd2e509698659a607f35e1c3791234fc912ec1f3a7ed2db43003be4fefa691d275eae893a0939f629442ec37da118577a53501f31b01bfc8744b2fe218130
                        )

                    [core/doc/admin/_sources/operations/index.txt] => Array
                        (
                            [expected] => 
                            [current] => ce961af1c09f596695dbea280acc44a18d593da9588cafc5e9c0c6c1ba8a294454351885329a8f0768045f30d3691722445756fadd9972dbaf9e0ec3b794e1f2
                        )

                    [core/doc/admin/_images/scaling-2.png] => Array
                        (
                            [expected] => 
                            [current] => 905fb2c68431cc3114de143c948ec46d3d606f221d435407a6c3885f32fe0349e351524ae67f791189565a925c8c66fd2227200f55e2c7e86b5cdb0f8a6fe5c1
                        )

                    [core/doc/admin/_images/scaling-1.png] => Array
                        (
                            [expected] => 
                            [current] => 76d420375b3ab2c255b07ddb1f6565ac1a146beb7f390e2d59e6cc48db00e5f89fc6f25747af454b29829e14b4921b54733e72c77b67726d083c748e05d22bdd
                        )

                    [core/doc/admin/_images/scaling-3.png] => Array
                        (
                            [expected] => 
                            [current] => 2936e7706335b23f469308f4d5bc09b5b8c235738e0bea7eeba89c0dd3b5dba532bfd9818a8ac4b07e262771b5c1b3aa270db31ddc456ea4e016f6c3c38a04a3
                        )

                    [core/doc/admin/_images/scaling-4.png] => Array
                        (
                            [expected] => 
                            [current] => 5d22ce7c851c30ee154aa52a5ecca3d2264c08a5ea643aea6eafd2e547b78e14ffb16e928f1381cd5f62705c16a12cb4bf3a39863eed72d5abce56d32c74cc02
                        )

                    [core/doc/admin/_images/scaling-5.png] => Array
                        (
                            [expected] => 
                            [current] => 11cd56a854c2e70e298c597b1e338b46f012e83dfa5d213be73989e1cb0e2b3fb0b5dc145fd2353147b64b1c5502c89631ceb137164512d595c26789b85c14e6
                        )

                )

        )

) 

-

**Comment by thommierother** [comment]
ah, sorry, THAT was my fault. Re-installed, re-checked with occ integrity:check-core, all fine. Sorry for disturbing ;-)

**Comment by RealRancor** [comment]
Yeah, thats needed since oC 9.x as files can changed even between minor releases which are triggering this integrity issues.
