### ISSUE TITLE
How to enable console.log in owncloud?

### ISSUE THREAD

**Issue by millsoft** [owncloud/core#26081]
Is it just me or is the console.log disabled in owncloud? It didn't work in OC8 and is not working in 9 either.
When I use console.log I get.

```
console.log("Hello");
VM2900:1 Uncaught TypeError: console.log is not a function(…)
```

I have no Idea how to enable it, or why it was disabled in the first place as this is a very important function for development. I tried **delete console.log** but this is not working either.
Browser is Chrome.

**Comment by DeepDiver1975** [comment]
please try to remove the following lines https://github.com/owncloud/core/blob/master/core/js/js.js#L29-L41 and let us know

**Comment by millsoft** [comment]
yeah I uncommented that part few days ago.. but it still is not working. Also cleared the cache. Is OC caching the JS files somewhere?
I paused the execution in js.js and tried console.log, and it worked. Then when I continued the execution of OC it loaded even more files and console.log stopped working. Beside js.js, some other js file must be removing console.log.

I also tried to enable the debug mode, didn't help.

**Comment by millsoft** [comment]
@DeepDiver1975 I see you created a fix? wow, that would be awesome. I will try it. Thank you very much.

**Comment by PVince81** [comment]
@millsoft the alternative is to set "debug" to true in config.php which would enable console logging in JS.

**Comment by millsoft** [comment]
@PVince81 yeah, I tried that. But somehow didn't work for me. For now I am using the chrome developer debugging console. I just open the JS file I need and add some breakpoints so I can see the values.
