### ISSUE TITLE
Cant access, delete or sync files

### ISSUE THREAD

**Issue by jorgedferreira** [owncloud/core#26083]
### Steps to reproduce
1. Unzip a large folder (it's  83725 small files)
2. After a few hours i noticed it and deleted the folder from the client machine
3. Sync is not working anymore, files are still there, can't delete the folder on web view.

### Expected behavior
Deleting the folder should remove the folder and files from the server, and all other clients.

### Actual behavior
Folder is still on the web interface (and also i can't delete anything on the web interface)

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Nginx 1.4.6

**Database:** Mysql 5.5

**PHP version:** 5.5.9

**ownCloud version:** 9.1.0.15

**Updated from an older ownCloud or fresh install:** Updated from 9.0.1 i think, but already had problem.

**Where did you install ownCloud from:** apt

**Signing status (ownCloud 9.0 and above):** no integrity issues

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - calendar
  - contacts
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocqo72xbrg72",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "somewhere.eu",
            "www.somewhere.eu"
        ],
        "datadirectory": "\/home\/somewhere\/private\/data",
        "overwrite.cli.url": "http:\/\/somewhere.eu",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud_cs2",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "notificacoes",
        "mail_smtpmode": "php",
        "mail_domain": "partilha.eu",
        "loglevel": 1,
        "maintenance": false,
        "updatechecker": false
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox/Safari

**Operating system:** Windows 10, OSX 10.11

#### Web server error log
```
2016/09/09 12:50:58 [error] 5594#0: *2151100 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 82 bytes) in /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 128" while reading response header from upstream, client: 177.148.221.227, server: somwhere.eu, request: "PROPFIND /remote.php/webdav/path/to/the/folder HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "www.somewhere.eu"
```

#### ownCloud log (data/owncloud.log)
```
No new error is added to the log. But i get "This directory is unavailable, please check the logs or contact the administrator" notification on the web app when trying to get to the folder.
```

**Comment by RealRancor** [comment]
> Allowed memory size of 536870912 bytes exhausted (tried to allocate 82 bytes)

You need to raise the memory_limit within your PHP configuration (php.ini)

**Comment by jorgedferreira** [comment]
@RealRancor  Yes... i noticed that was the obvious solution, but the notion "Throw more hardware at it!" isn't a solution. I've given it 4GB RAM limit and still does not work. It's not a solution and it will never be a solution. 
If a PDOStatement is using more that 512MB of RAM i'm pretty sure it's not doing it right. Why is there no way to setup pagination? Why would the software try to load everything from the database at once? This is purely insane.
I'm not even talking about *not having* a Delete option in the web frontend...

**Comment by jorgedferreira** [comment]
To any that may find themselves in this situation, what i did to at least resolve it was:
1. Went into the server and navigated to the data folder of the user, found the troublesome folder with 83k files and removed it
2. Went to owncloud folder and ran sudo -u www-data php occ files:scan username (where username is the real username..)

Took 10 seconds and now i have sync again and can navigate on the web interface, for what it's worth since i can't actually delete anything there...
