### ISSUE TITLE
when i am enter admin with password  if locally there is no problem but if from wan we can access and facing fallowing  problem.  kindly help me any one﻿

### ISSUE THREAD

**Issue by meowncloud** [owncloud/core#26088]
when i am enter admin with password  if locally there is no problem but if from wan we can access and facing fallowing  problem.

kindly help me any one﻿

**Comment by RealRancor** [comment]
Same as in #26089 :

@meowncloud The issue tracker here is not the place to ask for support.

Please close here, create a new thread in https://central.owncloud.org/c/help/oc-server and PLEASE PLEASE make sure that you're filling out the issue template shown there to provide more info about your environment.
