### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by meowncloud** [owncloud/core#26089]
![remote addrees](https://cloud.githubusercontent.com/assets/21293613/18410483/da164f6a-777d-11e6-9a0a-91269e775bfd.png)

when i am enter admin with password  if locally there is no problem but if from wan we can access and facing fallowing  problem.

kindly help me any

**Comment by RealRancor** [comment]
@meowncloud The issue tracker here is not the place to ask for support. Create a new thread in https://central.owncloud.org/c/help/oc-server and PLEASE PLEASE make sure that you're filling out the issue template shown there to provide more info about your environment.

**Comment by RealRancor** [comment]
@meowncloud Ahh, forgot to mention:

Once you want to report a bug here at this issue tracker please also make sure that you're filling out the issue template shown when creating a new bug in here. Without filling this template out bugreports are nearly useless.
