### ISSUE TITLE
Trash icon distorted after clicking on it with IE11

### ISSUE THREAD

**Issue by LoliconSuspect** [owncloud/core#26093]
### Steps to reproduce
1. Go to trash.
2. Click on the trash icon visible in the centre: 
![unnamed](https://cloud.githubusercontent.com/assets/19573104/18417046/1650a50e-7826-11e6-8961-c4d9ac5bf667.png)

### Expected behaviour
Nothing out of the ordinary.

### Actual behaviour
The icon looks distorted:
![unnamed 1](https://cloud.githubusercontent.com/assets/19573104/18417048/27b313b8-7826-11e6-915a-ae9b4f9a9a65.png)

And it stays in that way until I click somewhere else.
This situation happens only in IE11.

### Server configuration
**Operating system**: Ubuntu Linux 14.04.4 x64

**Web server:** Apache 2.4.7

**Database:** MySQL 5.5.47

**PHP version:** PHP 5.5.9

**ownCloud version:** 9.0.1

**Updated from an older ownCloud or fresh install:** updated from 9.0.0

**Where did you install ownCloud from:** https://download.owncloud.org/download/repositories/stable/owncloud/

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocdyf4f6b35c",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/***REMOVED SENSITIVE VALUE***\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Warsaw",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis.sock",
            "port": 0,
            "timeout": 0,
            "dbindex": 0
        },
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF"
        ],
        "maintenance": false,
        "loglevel": 3,
        "appstore.experimental.enabled": true,
        "singleuser": false
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** IE11

**Operating system:** Windows 10 x64

**Comment by RealRancor** [comment]
> ownCloud version: 9.0.1

from the issue template shown when creating a new issue:

> Before reporting any issues please make sure that you're using the latest available version for your major branch (e.g. 9.0.x), see https://owncloud.org/changelog/

**Comment by DeepDiver1975** [comment]
closing for now - please reopen once verified that this issue still exists in the latest version
