### ISSUE TITLE
no Share icon for non Admin users

### ISSUE THREAD

**Issue by danlight** [owncloud/core#26090]
### Steps to reproduce
Existing User A
Create new user B
Create Group C
Make User A and user B members of Group C

I've not tried turning sharing off/on because I don't want to create a problem for other users who currently have files shared. I don't know if there existing shares setup will be lost.

More testing:
Make both user A and B members of admin group
share icon is available to both users
User A shares a folder "SharedFromUserA"
User B shares a folder "SharedFromUserB"

Both users see the shared folders from each other

Remove User B from admin

User B Still sees shared "FromUserA" but loses the share icon
User A still sees "SharedFromUserB"

Remove User A from admin group
User A loses share icon
shared folders disappear from both Users

### Expected behaviour
Uses A and B should be able to share folders with each other

### Actual behaviour
New users cannot share any folder/file because there is no share icon in the web UI
If I add a User to the admin group the share icon shows up for them.

### Server configuration
Web Server: Apache/2.4.6 (CentOS)
Database:Ver 15.1 Distrib 5.5.50-MariaDB, for Linux (x86_64) using readline 5.1
PHP Version: PHP 5.6.25 (cli) 
ownCloud 9.1.0 updated from 9.0, 8.2, 8.1, etc
Installed from owncloud

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Integrity checker has been disabled. Integrity cannot be verified.

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - ownbackup: true
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocrlgbamclkk',
  'passwordsalt' => 'REMOVED',
  'secret' => 'REMOVED',
  'trusted_domains' =>
  array (
    0 => 'FQDN-REMOVED',
  ),
  'datadirectory' => '/ocdata',
  'overwrite.cli.url' => 'https://FQDN-REMOVED',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'REMOVED',
  'dbpassword' => '',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'forcessl' => true,
  'mail_domain' => 'REMOVED',
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'REMOVED',
  'appstore.experimental.enabled' => false,
  'loglevel' => 0,
  'trashbin_retention_obligation' => 'auto',
  'updatechecker' => false,
);
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

{
    "system": {
        "instanceid": "ocrlgbamclkk",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "iwdfiles.intelliware.ca"
        ],
        "datadirectory": "\/ocdata",
        "overwrite.cli.url": "https:\/\/iwdfiles.intelliware.ca",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "forcessl": true,
        "mail_domain": "REMOVED",
        "mail_smtpmode": "php",
        "mail_from_address": "REMOVED",
        "appstore.experimental.enabled": false,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
all storage is local

**Are you using encryption:** yes/no
No encryption

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No external backend
```

### Client configuration
**Browser:**
Chrome, iE, firefox

**Operating system:**
MS Windows 10, Windows 7

#### Web server error log
```
Insert your webserver log here
```
[error.log.gz](https://github.com/owncloud/core/files/465603/error.log.gz)
[owncloud_log.gz](https://github.com/owncloud/core/files/465604/owncloud_log.gz)

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Please try upgrading to v9.1.1RC2. In v9.1.0 there were many bugs related to sharing that were fixed there, including some related to group members.

**Comment by danlight** [comment]
FYI - Before updating to 9.1.1 I disabled sharing and enabled it again. that seemed to fix the missing share icons and all the pre existing shares came back.
I'm back in business. Thanks for your guidance.
