### ISSUE TITLE
Translate to latvian 

### ISSUE THREAD

**Issue by dpmmqb** [owncloud/core#26097]
Hello,

Ever since I updated my OC to v. 9.1 some words and phrases on latvian language is displayed in english. Tried under Chrome, Firefox (without cookies).

###Server configuration

Operating system: Ubuntu 14.04.2 LTS
Web server: Apache/2.4.12
Database: MySQL
PHP version: 5.6.23
ownCloud version: 9.1.0 Stable

Updated from an older ownCloud or fresh install: 9.0.3
Where did you install ownCloud from: owncloud.org

Signing status (ownCloud 9.0 and above):

No errors have been found.

I have translate phrases on latvian, but I do it only for Google Chrome. In Mozilla another words wasn't translated. In .docx file is marked words, this have no translation.

We tried with sys admin config .js and .json, but it doesn't work.

Translations:

"Comments" : "Komentāri"
	"Gallery" : "Bildes"
	"Personal info" : "Personāla informācija"
	"Sessions" : "Sesijas"
	"App passwords" : "Lietojuma parole"
	"Federated cloud" : "Ārējie mākoni"
	"Picture provided by original account" : "Attēls no oriģināla profila"
	"Browser" : "Interneta pārlūks"
	"Most recent activity" : "Pēdējās aktivitātes"
	"These are the web, desktop and mobile clients currently logged in to your OwnCloud" : "Šeit ir sesijas, kas ielogojas tavā OwnCloud, izmantojot web, datoru un mobilu ierīču klientus"
	"An app password is a passcode that gives an app or device permissions to accesss you OwnCloud account" : "Lietojumu parole ir piekļuves atslēga, kas dod aplikācijām vai ierīcēm piekļuves tiesības tavam OwnCloud profilam"
	"App name" : "Lietojuma nosaukums"
	"Create new app password" : "Izvedot jaunu lietojuma paroli"
	"If you want to support the project join development or spread the word!" : "Ja Jūs gribat attīstīt projektu, pievienojieties izstrādātajiem vai izplatiet ziņas!"
	"Limit notifications about creation and changes to your favorite files(Stream only)" : "Ierobežot paziņojumus, ja Jūsu iecienītie faili tiek izveidoti vai izmainīti (attēlot tikai plūsmā)"
	"Infected files has been found" : "Tika atrasti inficētie faili"
	"Comments for files (always listed in stream)" : "Komentāri failiem (vienmēr ir attēloti plūsmā)"
	"System tags for a file have been modified" : "Sistēmas tagi failiem ir modificēti"
	"List your own file action in the stream" : "Jūsu darbību saraksts plūsmā"

Thanks!
[Translate_Sfiles.docx](https://github.com/owncloud/core/files/467286/Translate_Sfiles.docx)

**Comment by DeepDiver1975** [comment]
Please join your translation project on transifex

**Comment by RealRancor** [comment]
Ref: https://www.transifex.com/owncloud-org/owncloud/
