### ISSUE TITLE
video gallery compatibility with mobile devices

### ISSUE THREAD

**Issue by Flexmaen** [owncloud/core#26092]
Shared video links won't work on iPhone

### Steps to reproduce
1. Upload an MP4 video in your gallery folder
2. Create a share link
3. Open this link on a mobile device e.g. iPhone or Blackberry 10

### Expected behaviour
You'd be able to see the video.

### Actual behaviour
Video does not work on iPhone.
Error Message on BB10 is "Error when retreiving video data. Server might have been stopped during recaiving."
Video worked on Android though.

### Server configuration
**ownCloud version:** (see ownCloud admin page)
8.1

**Comment by RealRancor** [comment]
Hi,

please update to a recent version of oC (9.0.4 or 9.1.0) where this is working as expected. If you're on PHP7 you need to wait for 9.0.5 or 9.1.1 which ships an additional fix.

**Comment by DeepDiver1975** [comment]
thx @RealRancor
