### ISSUE TITLE
Uploading of 0 bytes files with uncommon/unknown is not possible

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#26106]
### Steps to reproduce
1. create zero byte file "EmptyTest.blubb" on computer
2. try to upload "EmptyTest.blubb" with web UI (drag/drop or "+" with file selector)

### Expected behaviour
Uploading zero byte files should just work.

### Actual behaviour
`Error uploading file "EmptyTest.blubb": Unable to upload EmptyTest.blubb as it is a directory or has 0 bytes`

<img width="1058" alt="emptytest_-_files_-_owncloud" src="https://cloud.githubusercontent.com/assets/214010/18484932/e9c92ce2-79ea-11e6-8a08-be5915233d75.png">

### Server configuration

**ownCloud version:** (see ownCloud admin page)
```
{"installed":true,"maintenance":false,"version":"9.1.0.15","versionstring":"9.1.0","edition":""}
```

**Signing status (ownCloud 9.0 and above):**
```
No errors have been found.
```

### Client configuration
**Browser:**
Chrome 53

**Operating system:**
Mac OS 10.11.8

#### ownCloud log (data/owncloud.log)
```
no related entry
```

#### Browser log
```
no related entry
```

Maybe related: https://github.com/owncloud/core/issues/19116

@DeepDiver1975 

00006142

**Comment by RealRancor** [comment]
> Maybe related: #19116 

Duplicate from my PoV

**Comment by PVince81** [comment]
Duplicate, yes
