### ISSUE TITLE
RPMs for ownCloud 7.0.15 are no longer available.

### ISSUE THREAD

**Issue by ralmond** [owncloud/core#26100]
I'm trying to follow the recommended upgrade sequence for an old version of ownCloud (currently 7.0.4).  The first step seems to be to bring it up to 7.0.15

### Steps to reproduce
1. cd /etc/yum.repos.d/
2. wget http://download.opensuse.org/repositories/isv:ownCloud:community:7.0/RedHat_RHEL7/isv:ownCloud:community:7.0.repo
3. yum upgrade owncloud

### Expected behaviour
---> Package owncloud.noarch 0:7.0.4-17.1 will be updated
---> Package owncloud.noarch 0:7.0.15-1.1 will be an update
---> Package owncloud-3rdparty.noarch 0:7.0.4-17.1 will be updated
---> Package owncloud-3rdparty.noarch 0:7.0.15-1.1 will be an update
RPMs for indicated packages will be downloaded and installed.

### Actual behaviour
http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community%3A/7.0/RedHat_RHEL6/noarch/owncloud-7.0.15-1.1.noarch.rpm: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community%3A/7.0/RedHat_RHEL6/noarch/owncloud-3rdparty-7.0.15-1.1.noarch.rpm: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"

### Server configuration
**Operating system**:
RHEL 6.3
**Web server:**
Apache 2.2.15
**Database:**

**PHP version:**
5.4
**ownCloud version:** (see ownCloud admin page)
7.0.4
**Updated from an older ownCloud or fresh install:**
Problem occurs during upgrade process.
**Where did you install ownCloud from:**
isv:ownCloud:community.repo (some time ago).
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
cc @jnweiger

**Comment by PVince81** [comment]
@owncloud/packaging problem with the mirrors ?

**Comment by PVince81** [comment]
The links work for me by the way: `wget http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community%3A/7.0/RedHat_RHEL6/noarch/owncloud-7.0.15-1.1.noarch.rpm`

Probably some other of the OBS mirrors is missing the file.

**Comment by jnweiger** [comment]
I see some mixup in the description: 
* Machine is RHEL 6.3, 
* repo file is RedHat_RHEL7
* quoted failures are from a RHEL_6 repo. 

@ralmond please doublecheck that data.

WORKSFORME: 
wget http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community%3A/7.0/RedHat_RHEL7/noarch/owncloud-7.0.15-1.1.noarch.rpm

wget http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community%3A/7.0/RedHat_RHEL6/noarch/owncloud-7.0.15-1.1.noarch.rpm

I am getting my mirror redirect to end up at  http://ftp5.gwdg.de/pub/opensuse/repositories/isv:/ownCloud:/community:/7.0
@ralmond Please paste the full output you get on the wget commands, I am doing. This should have the name of the openSUSE mirror that fails.

**Comment by ralmond** [comment]
> On Sep 13, 2016, at 5:19 AM, Jürgen Weigert <notifications@github.com> wrote:
> 
> I see some mixup in the description:
> 
> 	• Machine is RHEL 6.3,
> 	• repo file is RedHat_RHEL7
> 	• quoted failures are from a RHEL_6 repo.
> @ralmond please doublecheck that data.
> 
Sorry.  I grabbed the wrong link when posting the issue.  I am using the RHEL_6 repo.



> WORKSFORME: 
> wget http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community%3A/7.0/RedHat_RHEL7/noarch/owncloud-7.0.15-1.1.noarch.rpm
> 
> wget http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community%3A/7.0/RedHat_RHEL6/noarch/owncloud-7.0.15-1.1.noarch.rpm
> 
> I am getting my mirror redirect to end up at http://ftp5.gwdg.de/pub/opensuse/repositories/isv:/ownCloud:/community:/7.0
> @ralmond Please paste the full output you get on the wget commands, I am doing. This should have the name of the openSUSE mirror that fails.
> 

I'm getting:
wget http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community%3A/7.0/RedHat_RHEL6/noarch/owncloud-7.0.15-1.1.noarch.rpm
--2016-09-13 11:00:35--  http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/community%3A/7.0/RedHat_RHEL6/noarch/owncloud-7.0.15-1.1.noarch.rpm
Resolving download.opensuse.org... 195.135.221.134, 2001:67c:2178:8::13
Connecting to download.opensuse.org|195.135.221.134|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://opensuse.c3sl.ufpr.br/repositories/isv:/ownCloud:/community:/7.0/RedHat_RHEL6/noarch/owncloud-7.0.15-1.1.noarch.rpm [following]
--2016-09-13 11:00:36--  http://opensuse.c3sl.ufpr.br/repositories/isv:/ownCloud:/community:/7.0/RedHat_RHEL6/noarch/owncloud-7.0.15-1.1.noarch.rpm
Resolving opensuse.c3sl.ufpr.br... 200.236.31.10, 2801:82:80ff:8000::b
Connecting to opensuse.c3sl.ufpr.br|200.236.31.10|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-09-13 11:00:36 ERROR 404: Not Found.

I hope this helps.
	--Russell Almond

**Comment by jnweiger** [comment]
Forwarded the URL to admin@opensuse.org

**Comment by PVince81** [comment]
@ralmond has it been solved already, does it work now ?

**Comment by ralmond** [comment]
Yes.  Just verified.  I was able to download and upgrade to 7.0.15.

Thanks for your help.
	--Russell
