### ISSUE TITLE
LDAP users can still log in after their access has been revoked

### ISSUE THREAD

**Issue by MegaBrutal** [owncloud/core#26108]
LDAP users whose accesses have been revoked (not qualifying the LDAP filters anymore) are still happily log in to the ownCloud instance. I don't really want them to be permanently removed automatically, but it would be great if
– ownCloud would not allow them to log in while they are excluded by the filters;
– I would have an option to MANUALLY remove them if I want to.
This way, I could temporarily ban users or have them deleted permanently, whichever I choose. Is it the right issue to discuss this, or should I open a new?

### Steps to reproduce
1. Set up LDAP authentication with custom filter.
2. Add users to LDAP. Log in with an LDAP user, upload some files, generate some activity.
3. Make a change in LDAP so the user does not qualify the LDAP filters anymore, but don't delete the user from LDAP entirely. (My actual case is to control access with a host / hostObject attribute. I added and then removed this attribute.)

### Expected behaviour
The user should not be able to log in anymore.

### Actual behaviour
The user can log in without any problems, even after several days. Although the user does not show upon the „Users” list anymore, he may happily enjoy the wide range of ownCloud features unhindered, like other legit users. All files and settings of the user are retained.

### Server configuration
**Operating system**:
Ubuntu 16.04.1 LTS

**Web server:**
Apache/2.4.18 (Ubuntu)

**Database:**
mysqld  Ver 10.0.25-MariaDB-0ubuntu0.16.04.1 for debian-linux-gnu on x86_64 (Ubuntu 16.04)

**PHP version:**
PHP 7.0.8-0ubuntu0.16.04.2

**Crontab:**
```
# crontab -l -u www-data
*/15 * * * * php -f /var/www/owncloud/cron.php
```

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.1.0 (stable)

**Updated from an older ownCloud or fresh install:**
Fresh install.

**Where did you install ownCloud from:**
deb http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ /

**Signing status (ownCloud 9.0 and above):**
I don't know how to check that.

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
See below.

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.3.2
  - calendar: 1.3.3
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - richdocuments: 1.1.4
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_ldap: 0.9.0
Disabled:
  - documents
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external

**The content of config/config.php:**
```
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => '*CONFIDENTIAL*',
  'passwordsalt' => '*CONFIDENTIAL*',
  'secret' => '*CONFIDENTIAL*',
  'trusted_domains' => 
  array (
    0 => 'owncloud.lan',
    1 => '*CONFIDENTIAL: public URL*',
  ),
  'datadirectory' => '/srv/owncloud_data/',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'dbname' => 'db_owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_ocadmin',
  'dbpassword' => '*CONFIDENTIAL*',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'htaccess.RewriteBase' => '/',
  'ldapIgnoreNamingRules' => false,
  'loglevel' => 0,
  'mail_smtpmode' => 'php',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:**
No.

**Are you using an external user-backend, if yes which one:**
LDAP (OpenLDAP)

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
```
+-------------------------------+--------------------------------------------------------------------------------------+
| Configuration                 |                                                                                      |
+-------------------------------+--------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                                      |
| hasPagedResultSupport         |                                                                                      |
| homeFolderNamingRule          |                                                                                      |
| lastJpegPhotoLookup           | 0                                                                                    |
| ldapAgentName                 |                                                                                      |
| ldapAgentPassword             | ***                                                                                  |
| ldapAttributesForGroupSearch  |                                                                                      |
| ldapAttributesForUserSearch   |                                                                                      |
| ldapBackupHost                |                                                                                      |
| ldapBackupPort                |                                                                                      |
| ldapBase                      | dc=megabrutal,dc=com                                                                 |
| ldapBaseGroups                | dc=megabrutal,dc=com                                                                 |
| ldapBaseUsers                 | dc=megabrutal,dc=com                                                                 |
| ldapCacheTTL                  | 600                                                                                  |
| ldapConfigurationActive       | 1                                                                                    |
| ldapDynamicGroupMemberURL     |                                                                                      |
| ldapEmailAttribute            | mail                                                                                 |
| ldapExperiencedAdmin          | 0                                                                                    |
| ldapExpertUUIDGroupAttr       |                                                                                      |
| ldapExpertUUIDUserAttr        |                                                                                      |
| ldapExpertUsernameAttr        | uid                                                                                  |
| ldapGroupDisplayName          | cn                                                                                   |
| ldapGroupFilter               |                                                                                      |
| ldapGroupFilterGroups         |                                                                                      |
| ldapGroupFilterMode           | 0                                                                                    |
| ldapGroupFilterObjectclass    |                                                                                      |
| ldapGroupMemberAssocAttr      | memberUid                                                                            |
| ldapHost                      | ldap://ldap1.lan/                                                                    |
| ldapIgnoreNamingRules         |                                                                                      |
| ldapLoginFilter               | (&(|(objectclass=posixAccount))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                      |
| ldapLoginFilterEmail          | 1                                                                                    |
| ldapLoginFilterMode           | 0                                                                                    |
| ldapLoginFilterUsername       | 1                                                                                    |
| ldapNestedGroups              | 0                                                                                    |
| ldapOverrideMainServer        |                                                                                      |
| ldapPagingSize                | 500                                                                                  |
| ldapPort                      | 7636                                                                                 |
| ldapQuotaAttribute            |                                                                                      |
| ldapQuotaDefault              |                                                                                      |
| ldapTLS                       | 0                                                                                    |
| ldapUserDisplayName           | sn                                                                                   |
| ldapUserDisplayName2          |                                                                                      |
| ldapUserFilter                | (&(objectclass=posixAccount)(host=owncloud))                     |
| ldapUserFilterGroups          |                                                                                      |
| ldapUserFilterMode            | 1                                                                                    |
| ldapUserFilterObjectclass     | posixAccount                                                                         |
| ldapUuidGroupAttribute        | auto                                                                                 |
| ldapUuidUserAttribute         | auto                                                                                 |
| turnOffCertCheck              | 0                                                                                    |
| useMemberOfToDetectMembership | 1                                                                                    |
+-------------------------------+--------------------------------------------------------------------------------------+
```

### Client configuration
**Browser:**
Not relevant.

**Operating system:**
Not relevant.

#### Web server error log
```
Insert your webserver log here
```
Not relevant.

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
Too much data, please give me instructions what to grep for.

#### Browser log
Not relevant.

**Comment by PVince81** [comment]
@owncloud/ldap @felixboehm @jvillafanez

**Comment by jvillafanez** [comment]
@MegaBrutal Your login filter doesn't have any "revocation" attribute. As long as the user is a posixAccount and the uid matches the LDAP uid or mail, that user will be able to access.

You might want to modify the login filter to something like `(&(|(objectclass=posixAccount))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))(!(loginShell=/sbin/nologin)))` so when you want to disable access to ownCloud for a specific user you can change the shell in the LDAP server. This is obviously an example, and you should adjust to your needs.

**Comment by RealRancor** [comment]
@jvillafanez Something for the documentation? The LDAP documentation is lacking quite a lot of such LDAP internals and most LDAP questions for such issues are unanswered at central.owncloud.org

**Comment by jvillafanez** [comment]
@RealRancor The problem I see is that LDAP in general requires a lot of knowledge and also depends heavily on the LDAP server configuration.

The average user (me included) will look for specific information and copy & paste whatever is there. The solution for this issue (if it fits with what @MegaBrutal wants) might not work for other user as such. It's user's responsability to read a bit between the lines and check possiblities.

Anyway, pinging @carlaschroder in case there is something to extract from here. Feel free to ping me in central.owncloud.org. I'll try to help the best I can.

**Comment by carlaschroder** [comment]
@jvillafanez I'll look at it. As you say, we expect the LDAP server admin to know what they're doing, and not expect us to teach them system administration. Maybe an LDAP tips page in the Wiki would be good for this; I'll think it over.

**Comment by MegaBrutal** [comment]
I did not really realize that I need to look at the login filter, and that it can enable users those are filtered out by the user filter. Maybe it would be sane to run both filters on the user and only let it in if it qualifies both the user and login filters.

This is what helped me:
`(&(|(objectclass=posixAccount))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))(host=owncloud))`
This needs to be set as login filter on the Login Attributes tab.

**Comment by butonic** [comment]
I guess for the documentation we need two examples for ldap. One is active directory, which determines most of the attributes that are used. Tho other is openldap, but I there the configuration is much more custom. Having specific AD examples should help already. What openldap scenario should we choose? redhat? suse? gosa? or the [debian based](https://wiki.debian.org/LDAP/OpenLDAPSetup) one? I am asking because LDAP besically can store everything. Depending on the scenario different attributes and object classes will be used, which makes LDAP look complicated when it is actually just flexible. openldap is so flexible thet they even store the config in ldap itself ... reminds me of inception ...

**Comment by jvillafanez** [comment]
Issue solved. Closing.

**Comment by carlaschroder** [comment]
Let's see if a doc Wiki page encourages some useful sharing of information.
https://github.com/owncloud/documentation/wiki/LDAP-Tips-for-Active-Directory-and-openLDAP
