### ISSUE TITLE
Activity notifications are stuck

### ISSUE THREAD

**Issue by MegaBrutal** [owncloud/core#26107]
### Steps to reproduce
Can't reproduce, as I have no idea what might cause the problem in the first place. Sure that I changed the e-mail settings multiple times as I was testing this issue: #26086.

All users' notification setting is to send notifications hourly.

### Expected behaviour
Activity notifications should be sent to users within an hour after an activity happens. A user should get only one notification of a particular event.

### Actual behaviour
No users get activity notifications, except the admin. The admin gets notifications of the same events (those happened several days ago) every day.

### Server configuration
**Operating system**:
Ubuntu 16.04.1 LTS

**Web server:**
Apache/2.4.18 (Ubuntu)

**Database:**
mysqld  Ver 10.0.25-MariaDB-0ubuntu0.16.04.1 for debian-linux-gnu on x86_64 (Ubuntu 16.04)

**PHP version:**
PHP 7.0.8-0ubuntu0.16.04.2

**Crontab:**
```
# crontab -l -u www-data
*/15 * * * * php -f /var/www/owncloud/cron.php
```

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.1.0 (stable)

**Updated from an older ownCloud or fresh install:**
Fresh install.

**Where did you install ownCloud from:**
deb http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ /

**Signing status (ownCloud 9.0 and above):**
I don't know how to check that.

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
See below.

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.3.2
  - calendar: 1.3.3
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - richdocuments: 1.1.4
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_ldap: 0.9.0
Disabled:
  - documents
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external

**The content of config/config.php:**
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => '*CONFIDENTIAL*',
  'passwordsalt' => '*CONFIDENTIAL*',
  'secret' => '*CONFIDENTIAL*',
  'trusted_domains' => 
  array (
    0 => 'owncloud.lan',
    1 => '*CONFIDENTIAL: public URL*',
  ),
  'datadirectory' => '/srv/owncloud_data/',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'dbname' => 'db_owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_ocadmin',
  'dbpassword' => '*CONFIDENTIAL*',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'htaccess.RewriteBase' => '/',
  'ldapIgnoreNamingRules' => false,
  'loglevel' => 0,
  'mail_smtpmode' => 'php',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:**
No.

**Are you using an external user-backend, if yes which one:**
LDAP (OpenLDAP)

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
+-------------------------------+--------------------------------------------------------------------------------------+
| Configuration                 |                                                                                      |
+-------------------------------+--------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                                      |
| hasPagedResultSupport         |                                                                                      |
| homeFolderNamingRule          |                                                                                      |
| lastJpegPhotoLookup           | 0                                                                                    |
| ldapAgentName                 |                                                                                      |
| ldapAgentPassword             | ***                                                                                  |
| ldapAttributesForGroupSearch  |                                                                                      |
| ldapAttributesForUserSearch   |                                                                                      |
| ldapBackupHost                |                                                                                      |
| ldapBackupPort                |                                                                                      |
| ldapBase                      | dc=megabrutal,dc=com                                                                 |
| ldapBaseGroups                | dc=megabrutal,dc=com                                                                 |
| ldapBaseUsers                 | dc=megabrutal,dc=com                                                                 |
| ldapCacheTTL                  | 600                                                                                  |
| ldapConfigurationActive       | 1                                                                                    |
| ldapDynamicGroupMemberURL     |                                                                                      |
| ldapEmailAttribute            | mail                                                                                 |
| ldapExperiencedAdmin          | 0                                                                                    |
| ldapExpertUUIDGroupAttr       |                                                                                      |
| ldapExpertUUIDUserAttr        |                                                                                      |
| ldapExpertUsernameAttr        | uid                                                                                  |
| ldapGroupDisplayName          | cn                                                                                   |
| ldapGroupFilter               |                                                                                      |
| ldapGroupFilterGroups         |                                                                                      |
| ldapGroupFilterMode           | 0                                                                                    |
| ldapGroupFilterObjectclass    |                                                                                      |
| ldapGroupMemberAssocAttr      | memberUid                                                                            |
| ldapHost                      | ldap://ldap1.lan/                                                                    |
| ldapIgnoreNamingRules         |                                                                                      |
| ldapLoginFilter               | (&(|(objectclass=posixAccount))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                      |
| ldapLoginFilterEmail          | 1                                                                                    |
| ldapLoginFilterMode           | 0                                                                                    |
| ldapLoginFilterUsername       | 1                                                                                    |
| ldapNestedGroups              | 0                                                                                    |
| ldapOverrideMainServer        |                                                                                      |
| ldapPagingSize                | 500                                                                                  |
| ldapPort                      | 7636                                                                                 |
| ldapQuotaAttribute            |                                                                                      |
| ldapQuotaDefault              |                                                                                      |
| ldapTLS                       | 0                                                                                    |
| ldapUserDisplayName           | sn                                                                                   |
| ldapUserDisplayName2          |                                                                                      |
| ldapUserFilter                | (&(objectclass=posixAccount)(host=owncloud))                     |
| ldapUserFilterGroups          |                                                                                      |
| ldapUserFilterMode            | 1                                                                                    |
| ldapUserFilterObjectclass     | posixAccount                                                                         |
| ldapUuidGroupAttribute        | auto                                                                                 |
| ldapUuidUserAttribute         | auto                                                                                 |
| turnOffCertCheck              | 0                                                                                    |
| useMemberOfToDetectMembership | 1                                                                                    |
+-------------------------------+--------------------------------------------------------------------------------------+

### Client configuration
**Browser:**
Not relevant.

**Operating system:**
Not relevant.

#### Web server error log
```
Insert your webserver log here
```
Not relevant.

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
Too much data, please give me instructions what to grep for.

#### Browser log
Not relevant.

**Comment by PVince81** [comment]
Please try with 9.1.1RC2.

Maybe something in cron got stuck

**Comment by MegaBrutal** [comment]
Is it safe to upgrade to 9.1.1RC2, which does not seem to be a stable version?

**Comment by MegaBrutal** [comment]
I took the risk and upgraded to 9.1.1RC2, but it does not seem to solve the issue.

Is there any way to debug the cron.php script, especially the activity notification job?

**Comment by MegaBrutal** [comment]
Now it suddenly started to work. All users got their notifications retroactively at 19:30 (~1,5 hours ago). I'll continue to monitor the status, let's hope the notifications won't be repeated. I also wonder why 7:30 and 19:30 are the magical times when notifications may be sent, when they should be sent within an hour after an activity happens.

**Comment by PVince81** [comment]
You can check the oc_jobs table which contains all the one-time and recurring jobs to be run by cron.

**Comment by PVince81** [comment]
For activity notifications you can force them by running `update oc_activity_mq set amq_latest_send=0` and running cron.

If a lot of notifications are stuck it is likely that not all of them will be sent at once but require several cron runs to process them all.
