### ISSUE TITLE
Share link seems to be gone after upgrading to 9.1.

### ISSUE THREAD

**Issue by andreasba** [owncloud/core#26109]
### Steps to reproduce
1. Login to owncloud
2. Look for the share link
3. Being buffled that it is gone

### Expected behaviour
I should be able to share files

### Actual behaviour
Nothing

### Server configuration
**Operating system**:
Linux
**Web server:**
Apache
**Database:**
MySQL 5
**PHP version:**
PHP 7
**ownCloud version:** (see ownCloud admin page)
9.1.0
**Updated from an older ownCloud or fresh install:**
Upgraded according to manual
**Where did you install ownCloud from:**
owncloud.org

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
```
Enabled:
  - dav: 0.2.5
  - documents: true
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - provisioning_api: 0.5.0
  - templateeditor: 0.1
Disabled:
  - activity
  - comments
  - encryption
  - external
  - federation
  - files_antivirus
  - files_external
  - files_sharing
  - files_versions
  - firstrunwizard
  - music
  - notifications
  - systemtags
  - updatenotification
  - user_external
  - user_ldap
```
**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocplts7t5i64",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.domain"
        ],
        "datadirectory": "\/home\/ownclouddata",
        "overwrite.cli.url": "https:\/\/my.domain",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "maintenance": false,
        "dbname": "xxxxxxx_db1",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "asset-pipeline.enabled": true,
        "mail_from_address": "admin",
        "mail_smtpmode": "php",
        "mail_domain": "my.domain",
        "log_rotate_size": 1048576,
        "appstore.experimental.enabled": true,
        "loglevel": 0,
        "htaccess.RewriteBase": "\/",
        "theme": ""
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

I really think that the error sits before the screen but I cannot see what I could be doing wrong. And Yes, sharing is allowed for all users:

![unbenannt](https://cloud.githubusercontent.com/assets/15323226/18489109/7c89d67e-79fc-11e6-9090-82bdc643f3c2.PNG)

Edit: See, no share link anywhere to be seen!

![nolink](https://cloud.githubusercontent.com/assets/15323226/18489711/088e22f4-79ff-11e6-91c5-a3612992df91.PNG)

Is this really a bug?!

Thanks
Andreas

**Comment by RealRancor** [comment]
You have "files_sharing" disabled which is the reason for your issue.

**Comment by andreasba** [comment]
Thank you @RealRancor, stupid me!
