### ISSUE TITLE
Check in changelogs ?

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26117]
Idea: shortly before making a release, update and check in a changelog file.
The version tag will also be applied at this point.

To think about:
- one changelog in core that includes the changes in all bundled/shipped apps ?
- or one changelog per app ? need a script to compile them automatically at release time ?

@dragotin @DeepDiver1975

**Comment by PVince81** [comment]
- script to convert the changelogs to HTML for publishing on the website, probably something for the website repo

**Comment by PVince81** [comment]
See https://github.com/owncloud/client/blob/master/ChangeLog for an example format from the client

**Comment by PVince81** [comment]
- another tricky part:
    - master changelog should include all changes of all versions, so the 9.2 changelog would contain changes from 9.1
    - but then if we backport changes to stable9.1, need to update changelog of stable9.1 and also master
    - backport to stable8.1 need update changelog of all branches in-between, etc

**Comment by PVince81** [comment]
- or maintain the changelog in the documentation repo instead ? (the problem with branches still exists)
    - in docs repo could also compile the changelog to different formats

**Comment by PVince81** [comment]
regardless where the changelog is stored, it would be good to have a script to generate the HTML of the website based on the original changelog: https://github.com/owncloud/owncloud.org/issues/1047

**Comment by PVince81** [comment]
Had a discussion with @DeepDiver1975 @pmaier1 @felixboehm and others about this and we agreed that it would make sense to checkin changelogs, especially for apps.

The approach would be as follows:
- CHANGELOG.md only contains entries for the current major version
- stable branches / backports would update the changelog of the previous major version. Entries from this log do not exist on master as per the previous rule
- every PR comes with a changelog entry
- I suggest using the format from http://keepachangelog.com/en/1.0.0/

**Comment by PVince81** [comment]
@tboerger has suggested the gitlab approach: having a changelog folder and a script to compile the changelog based on its contents. Would help avoid conflicts on the CHANGELOG.md file for every single PR

**Comment by butonic** [comment]
The `changelogs/unreleased` folder contains .yml files for the merged PRs, see https://gitlab.com/gitlab-org/gitlab-ce/tree/master/changelogs/unreleased

To adhere to http://keepachangelog.com/en/1.0.0/ the .yml files should contain the type of change so that we can generate the proper `Added`, `Changed`, `Deprecated`, `Removed`, `Fixed`, and `Security` entries.

Also see https://gitlab.com/help/development/changelog.md on [Writing good changelog entries](https://gitlab.com/help/development/changelog.md#writing-good-changelog-entries)

**Comment by PVince81** [comment]
it was discussed that we should checkin changelogs in every repo and also that every PR comes with an update to the changelog

**Comment by PVince81** [comment]
One thing that bothers me about "keep a changelog" examples is that it doesn't refer to any pull request ids or issue ids. I think we should continue to include them for reference, unless they are considered to be noise and useless for the target audience.

**Comment by PVince81** [comment]
Another tricky bit is that to compile the changelog for owncloud.org/changelog we'd need to gather the CHANGELOG.md not only of core but also for every bundled apps like "market" and "configreport"

**Comment by PVince81** [comment]
First PR for stable10: https://github.com/owncloud/core/pull/28632

**Comment by pmaier1** [comment]
> I think we should continue to include them for reference, unless they are considered to be noise and useless for the target audience.

References would be nice, of course.

> First PR for stable10: #28632

Yay, good job, thanks! :+1:

**Comment by PVince81** [comment]
And what to do with the wiki page https://github.com/owncloud/core/wiki/ownCloud-10.0-Features ?

Now that we add features in 10.0.3 we should probably add them there too.
Or retire this wiki page and make it redirect to the changelog file which contains an "Added" section for new features.

**Comment by PVince81** [comment]
done in stable10
