### ISSUE TITLE
Update php-opencloud

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26111]
Now that we agreed that OC 9.2 will only support PHP >= 5.6, we should be able to update the php-opencloud library to the latest version which I believe fixed auth problems and large object support.

@DeepDiver1975 @butonic

**Comment by PVince81** [comment]
This one https://github.com/rackspace/php-opencloud tells about PHP 5.4 being the minimum and its version is < 2

Version 2 is here: https://github.com/php-opencloud/openstack

**Comment by PVince81** [comment]
I also see that flysystem's adapter is based on v2 too https://github.com/nimbusoftltd/flysystem-openstack-swift

So maybe we just port ours to the adapter ?

**Comment by PVince81** [comment]
Ouch:
```
  Problem 1
    - php-opencloud/common v1.0.5 requires php ~7.0 -> your PHP version (5.6.24) does not satisfy that requirement.
    - php-opencloud/common v1.0.4 requires php ~7.0 -> your PHP version (5.6.24) does not satisfy that requirement.
    - php-opencloud/common v1.0.3 requires php ~7.0 -> your PHP version (5.6.24) does not satisfy that requirement.
    - php-opencloud/common v1.0.2 requires php ~7.0 -> your PHP version (5.6.24) does not satisfy that requirement.
    - php-opencloud/common v1.0.1 requires php ~7.0 -> your PHP version (5.6.24) does not satisfy that requirement.
    - php-opencloud/common v1.0.0 requires php ~7.0 -> your PHP version (5.6.24) does not satisfy that requirement.
    - php-opencloud/openstack v2.0.0 requires php-opencloud/common ~1.0 -> satisfiable by php-opencloud/common[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5].
    - Installation request for php-opencloud/openstack v2.0.0 -> satisfiable by php-opencloud/openstack[v2.0.0].
```

Requires PHP 7 now ?!

**Comment by DeepDiver1975** [comment]
We need to move this stuff out of core.
One app which takes care about this swift primary and secondary storage.
This one app can then support php 7+ only

**Comment by PVince81** [comment]
Hmm indeed, but then we still need to maintain the other app for PHP 5.6 support.
So we could have a separate new SWIFT app and still keep the old SWIFT one as well.

**Comment by chrone81** [comment]
Will this support uploading large object storage to custom S3 such as one on Ceph?

I always got this below error when uploading more than 5GB of file to ownCloud external storage via custom Amazon S3 (Ceph object storage). The ownCloud is using master encryption key.

`""app":"files_external","message":"Exception: {\"Exception\":\"Aws\\\\S3\\\\Exception\\\\EntityTooLargeException\""`

**Comment by butonic** [comment]
meanwhile there is v3 of the openstack identity api: https://developer.openstack.org/api-ref/identity/v3/ It is supported by https://github.com/php-opencloud/openstack ... but that one requires PHP7 ... it does seem to support v2 and v3: https://github.com/php-opencloud/openstack/tree/master/src/Identity

**Comment by PVince81** [comment]
I heard SWIFT is deprecated now in favor of S3, close ?
