### ISSUE TITLE
MemCache (redis backend) returns invalid imagePath values when switching theme

### ISSUE THREAD

**Issue by j0inty** [owncloud/core#26120]
As @supersn0b was developing a new ownCloud 9 theme for us he noticed that the new created favicon.ico file was never seen in the browser on our production environment. On his devBox he didn't ran into this problem.

I remeber that he don't use a MemCache at his devBox so I was really sure that this might be a memcache problem. After some investigation of the lib/private/URLGenerator.php I found out that the imagePath comes always from the MemCache and there is no extra validation check about a changed theme.

So the requested value is always valid and the rendered imagePath is incorrect.

regards
j0inty
### Steps to reproduce
1. Create and activate a new owncloud theme where you also create a new favicon.ico for it.
2. Refresh the page in your browser and then have a look at the &lt;link rel="icon" ....&gt; html header line.
3. As you can see the old theme imagePath value was used as long you have the MemCache::Redis activated or unset the cacheKey value.
### Expected behaviour

The &lt;link rel="icon" href="/themes/mrmobo-owncloud-theme/core/img/favicon.ico"&gt; should have the theme imagePath for favicon.ico.
### Actual behaviour

&lt;link rel="icon" href="/core/img/favicon.ico"&gt;  -- will created with the old value from redis cache with key similar to "imagePath-$app-$image". 

```
public function imagePath($app, $image)
 {
    $cache = $this->cacheFactory->create('imagePath');
    $cacheKey = $app.'-'.$image;
    if($key = $cache->get($cacheKey)) {
        return $key;
    }

       // Read the selected theme from the config file
    $theme = \OC_Util::getTheme();
```

$key is always a valid value from memcache but the wrong for the configured theme. A quick and dirty fix was to used the theme name as part of the cachekey.

```
// Read the selected theme from the config file
$theme = \OC_Util::getTheme();

// The theme config value will be part of the cachekey for images 
$cacheKey = (($theme != '') ? $theme .'-' : '') . $app .'-'. $image;
if($key = $cache->get($cacheKey)) {
    return $key;
}
```

Then the correct imagePath for the favicon.ico for will returned and the template gets rendered with the correct favicon.ico imagePath.
### Server configuration

**Operating system**:

Linux megatron 4.7.3-hardened #8 SMP Fri Sep 9 19:48:06 CEST 2016 x86_64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz GenuineIntel GNU/Linux

**Web server:**
megatron owncloud # qlist -Iv apache
app-admin/apache-tools-2.4.23
www-apache/mod_security-2.7.7
www-apache/modsecurity-crs-2.2.7
www-apache/passenger-4.0.60
www-servers/apache-2.4.23-r1

**Database:**
megatron owncloud # qlist -Iv postgres
app-eselect/eselect-postgresql-1.2.1
dev-db/postgresql-9.5.4

megatron owncloud # postmaster -V
postgres (PostgreSQL) 9.5.4

**PHP version:**
PHP 7.0.11-pl0-gentoo

*\* Redis **
dev-db/redis-3.2.3
dev-php/pecl-redis-3.0.0

**ownCloud version:** (see ownCloud admin page)
9.1.0.15

**Updated from an older ownCloud or fresh install:**

This ownCloud instance is up & runnig since version 8.0 on our gentoo hardened box.

**Where did you install ownCloud from:**
www-apps/owncloud-9.1.0

**Signing status (ownCloud 9.0 and above):**

```
Results
=======
- core
    - INVALID_HASH
        - .htaccess
    - EXTRA_FILE
        - .webapp-owncloud-9.1.0
- files_antivirus
    - EXTRA_FILE
        - CONTRIBUTING.md
        - README.md
        - appinfo/version

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => ab5f4c44ba2f9c66f2ed25c3ad3d84660b2808cca11ffa8fe2778a648a054d8ada495a0bf4715dc873aac1efe8dfd92a72f9a24441d8f5240834e639325fd892
                            [current] => f0871ca355e4dd7cdee18065356146e3c191eae1148d80399dffbf0fe755fe31138d7aadb71053cc583ad9986477ed5a6c1773aef62695ada80a6e3d87ead68b
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [.webapp-owncloud-9.1.0] => Array
                        (
                            [expected] => 
                            [current] => 
                        )

                )

        )

    [files_antivirus] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [CONTRIBUTING.md] => Array
                        (
                            [expected] => 
                            [current] => 0de5eddd29b6be1a62c71bf217edf2c5b163916842f9976326d5254e14853fc138692ede064994a934cc911b0cd42a502db20e7be0f867af9a4c631a61ace4dc
                        )

                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => d197f4b4e0a845261162fdc8ad5a500e579c68c9306471558da14eb3474b70889772fd88fea1161be341421c4dba3bbc63c5e85a8378b38a75d76dbdb1e3264a
                        )

                    [appinfo/version] => Array
                        (
                            [expected] => 
                            [current] => 145eb15cbba3d7bf919b3b7f3b2a02124d057b256ba8a34898e28a1ef6d9a8a4ebb8613f419744576332530bc528a43243b61f99f5481ca23e4d7961a9668591
                        )

                )

        )

)
```

**List of activated apps:**

```
megatron owncloud # sudo -u apache ./occ app:list
Enabled:
  - activity: 2.3.2
  - bookmarks: 0.9.0
  - calendar: 1.3.3
  - comments: 0.3.0
  - contacts: 1.4.0.0
  - dav: 0.2.5
  - external: 1.2
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_videoplayer: 0.9.8
  - files_videoviewerplus: 0.2.0
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - mail: 0.5.3
  - music: 0.3.12
  - notifications: 0.3.0
  - ocsms: 1.7.0
  - ownnote: 1.06
  - provisioning_api: 0.5.0
  - qownnotesapi: 16.09.0
  - shorten: 0.0.15
  - systemtags: 0.3.0
  - tasks: 0.9.3
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - announcementcenter
  - documents
  - encryption
  - files_antivirus
  - files_versions
  - galleryplus
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
megatron owncloud # sudo -u apache php ./occ config:list system
{
    "system": {
        "instanceid": "oc741421755d",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/home\/owncloud\/mrmobo\/data",
        "dbtype": "pgsql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost:\/run\/postgresql\/.s.PGSQL.5432",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/apache2\/owncloud.log",
        "logdateformat": "d-m H:i:s",
        "loglevel": 0,
        "forcessl": true,
        "theme": "mrmobo-owncloud-theme",
        "maintenance": false,
        "trusted_domains": [
            "www.stollfuss.net",
            "stollfuss.net"
        ],
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mrmobo.de",
        "mail_from_address": "noreply",
        "mail_domain": "mrmobo.de",
        "xframe_restriction": false,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "mail_smtpport": "25",
        "cron_log": true,
        "cron.lockfile.location": "\/var\/log\/apache2",
        "trashbin_retention_obligation": "auto",
        "versions_retention_obligation": "disabled",
        "log_rotate_size": 15728640,
        "debug": false,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "minimum.supported.desktop.version": "2.2.0",
        "quota_include_external_storage": false,
        "enable_previews": false
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

We are using external storages of type "local" only.

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

No LDAP in use.
### Client configuration

**Browser:**

```
FireFox 48.0.2 
```

**Operating system:**

```
Win 7 x64
Linux x86_64 (Gentoo, Kubuntu)
```
#### Web server error log

There is no error logging, because there is not really an error occured.
#### ownCloud log (data/owncloud.log)

There is no error logging, because there is not really an error occured.

**Comment by PVince81** [comment]
Thanks for the detailed report.

I guess your fix about putting the theme name in the cache key is an acceptable solution.
A more complex alternative would be to try and detect theme change and clear all the cached keys. To detect a theme change an idea would be to store the theme name in the cache as well (or in oc_appconfig) and then compare with the value that's in config.php

Your proposed solution seems to be more elegant.

@DeepDiver1975 what do you think ?

**Comment by PVince81** [comment]
@phisch

**Comment by PVince81** [comment]
@j0inty can you try with https://github.com/owncloud/core/pull/27319 ?

**Comment by phisch** [comment]
@j0inty because of your :+1: regarding #27319, i assume your problem has been solved. That's why i am closing this issue. We can re-open it if you are still experiencing any issues with this!
