### ISSUE TITLE
error twoFactorAuth

### ISSUE THREAD

**Issue by Blisk** [owncloud/core#26127]
### Steps to reproduce
1. this error is in owncloud /owncloud/data/owncloud.log
and filling my log file up all the time and it grows insane

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

{"reqId":"","remoteAddr":"123.123.123.123","app":"PHP","message":"Undefined index: two-factor-providers at \/var\/www\/owncloud\/lib\/private\/Authentication\/TwoFactorAuth\/Manager.php#111","level":3,"time":"2016-09-16T11:17:27+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/categories","user":"user"}
{"reqId":"","remoteAddr":"123.123.123.123","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/lib\/private\/Authentication\/TwoFactorAuth\/Manager.php#112","level":3,"time":"2016-09-16T11:17:27+00:00","method":"GET","url":"\/owncloud\/index.php\/settings\/apps\/categories","user":"user"}

### Server configuration
**Operating system**:
centos 7.2
**Web server:**
apache 2.4.6
**Database:**
5.5.5
**PHP version:**
5.4.16
**ownCloud version:** (see ownCloud admin page)
9.1
**Updated from an older ownCloud or fresh install:**
updated from 7
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**
X
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'cloud.povej.net',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://my.domain.net',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_denis',
  'dbpassword' => '',
  'installed' => true,
  'theme' => '',
  'loglevel' => 0,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto, auto',
  'mail_from_address' => 'info',
  'mail_smtpmode' => 'php',
  'mail_domain' => ',my.domain.net',

'memcache.local' => '\OC\Memcache\APC',
'preview_libreoffice_path' => '/usr/lib64/libreoffice',

  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    11 => 'OC\\Preview\\Illustrator',
    12 => 'OC\\Preview\\Postscript',
    13 => 'OC\\Preview\\Photoshop',
    14 => 'OC\\Preview\\TIFF'
  ),

);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
firefox
**Operating system:**
win 7
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
After a short search here for "two-factor-providers" the https://github.com/owncloud/core/pull/25606 is popping up which is fixing this with oC 9.1.1 which gets released in a few days.

So you can close here and try 9.1.1 RC3 or wait for the final 9.1.1 release

**Comment by Blisk** [comment]
OK thank you I will wait.
