### ISSUE TITLE
FR: Do not show TwoFactor list, if only one exists

### ISSUE THREAD

**Issue by cornelinux** [owncloud/core#26134]
### Steps to reproduce
1. define only *one* twofactor provider
2. login with owncloud credentials
3. user needs to "select" the one provider from the list of one.

### Expected behaviour
2FA is sometimes anoying for the user anyway. So if there is only one provider, he should not do the additional click to select the only provider. OC should not display the list with one entry but directly choose this provider. Save this additional click.

### Actual behaviour
s.o.

### Server configuration
**Operating system**: N/A

**Web server:** N/A

**Database:** N/A

**PHP version:** N/A

**ownCloud version:** (see ownCloud admin page) 9.1

**Updated from an older ownCloud or fresh install:** N/A

**Where did you install ownCloud from:** owncloud.org

**Signing status (ownCloud 9.0 and above):** ?

**List of activated apps:** privacyIDEA two factor provider

**The content of config/config.php:** N/A

**Are you using external storage, if yes which one:** N/A

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** internal user DB

### Client configuration
**Browser:** chrome

**Operating system:** Linux

**Comment by PVince81** [comment]
Hmm, indeed.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/26141

@cornelinux mind helping to test it with your provider ?

**Comment by cornelinux** [comment]
@PVince81 what would be the recommended way to do this.
Where can I clone a branch or PR?

**Comment by PVince81** [comment]
@cornelinux you could simply download the PR as patch if that's easier for you: https://github.com/owncloud/core/pull/26141.patch

**Comment by cornelinux** [comment]
Thx. I just tested it. Works like a charm with the privacyIDEA 2FA App. :+1:
