### ISSUE TITLE
Is it possible to move allowSymlinks in config.php?

### ISSUE THREAD

**Issue by Loki3000** [owncloud/core#26132]
Using symlinks is very useful.
I know that from 8 version symlinks disabled by default, but maybe lets  allow administrators enables it for it's own risks?

**Comment by RealRancor** [comment]
@Loki3000 I think the support of symlinks within t he datadir were not disabled by fun or to annoy admins. There is a reason why this was done and i guess its unlikely that this will be configurable.

Just use the external storage app with the "local mount" option instead.

**Comment by Loki3000** [comment]
The reasons are known. So administrators could decide to allow risks of symlinks or not.
In fact, until the eighth version this was normal behaviour. And now symlinks could be enabled by changing only one property in class. So why to not move this property in config file?

**Comment by RealRancor** [comment]
Symlinks are unsupported since oC 8.0 (and probably also before):

https://doc.owncloud.org/server/8.0/admin_manual/release_notes.html#owncloud-does-not-follow-symlinks

And no, administrators shouldn't be able to decide to do something unsupported and take the risk. This will cause un-reproduceable issues and reports here at the issue tracker and the forums.

**Comment by Loki3000** [comment]
> Symlinks are unsupported since oC 8.0
I wrote it in previous message. Seven versions before it was normal.

>And no, administrators shouldn't be able
Who decided that? Administrators must solve their tasks. If these tasks require symbolic links, then I would prefer to have such a tool.

**Comment by DeepDiver1975** [comment]
Solve tasks as in getting unexpected behaviour and data loss?

As explained: we did things on purpose.

**Comment by RealRancor** [comment]
> I wrote it in previous message. Seven versions before it was normal.

Yes, until someone noticed:

> getting unexpected behaviour and data loss?



>Who decided that?

Most likely the people which needs to handle bugreports of users/administrators which are not following the release note and do unsupported stuff causing the mentioned unexpected behavior and data loss.
