### ISSUE TITLE
OBS install instructions: use ">" instead of ">>" for the echo comand of owncloud.lst

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#26130]
Currently the OBS install instructions is telling people to do something like:

``sh -c "echo 'deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /' >> /etc/apt/sources.list.d/owncloud.list"``

This might cause multiple entries in the owncloud.list as people are known to blindly copy over stuff without thinking first. Instead of ``>>`` i suggest to use ``>`` which is overwriting the content of the file instead of writing an additional entry into it.

Affected are the owncloud server repositories (opensuse as well as own at owncloud.org) as well as the client repository.

cc @jnweiger

**Comment by PVince81** [comment]
@owncloud/packaging

**Comment by RealRancor** [comment]
OBS PR here: https://github.com/openSUSE/software-o-o/pull/106

**Comment by RealRancor** [comment]
https://github.com/openSUSE/software-o-o/pull/106 was merged so closing here.

https://download.owncloud.org/download/repositories/stable/owncloud/ already has the correct ``>`` and https://software.opensuse.org/download/package?project=isv:ownCloud:community:8.0&package=owncloud probably just needs to be updated with a new OBS version.
