### ISSUE TITLE
Bug: New User can not login with 2FA

### ISSUE THREAD

**Issue by cornelinux** [owncloud/core#26137]
### Steps to reproduce
1. Create a new user, who never has logged in.
2. Install a 2FA provider. I installed owncloud_privacyidea, it might also work with TOTP. This provider should be ACTIVE for the new user.
3. Now the new user tries to log in for the first time.
4. He enter his owncloud credentials.
5. Before he can actually choose a 2FA provider he ends up in some kind of Javascript loop.

### Expected behaviour
The user should be able to 

### Actual behaviour
Obviously the welcome Popup tries to be displayed. But it interferes with the 2FA choosing dialog. The welcome popup pops up over and over again, the user can not choose the 2FA provider and can not log in.

The browser console contains:

    Failed to parse sourcemap
    https://xxxxx//index.php/login/jquery.min.map

VM1390:10 Uncaught ReferenceError: SVGSupport is not defined
onComplete	@	VM1390:10
trigger	@	VM1389:192
complete	@	VM1389:657
callback	@	VM1389:743
complete	@	VM1389:551
d.complete	@	VM1346:3
j	@	VM1346:2
fireWith	@	VM1346:2
i	@	VM1346:3
n.fx.tick	@	VM1346:3

### Server configuration
**Operating system**: N/A

**Web server:** Apache2

**Database:** Mysql

**PHP version:** php7

**ownCloud version:** 9.1

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** owncloud.org

**Signing status (ownCloud 9.0 and above):** 

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

Bummer. Can not do this due to loop.

**List of activated apps:**

twofactor_privacyidea

**The content of config/config.php:** N/A

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** internal

### Client configuration
**Browser:** chrome

**Operating system:**  ubuntu 16.04

**Comment by PVince81** [comment]
If that's in 9.1.0 please try with 9.1.1 RC2, there was an infinite JS loop problem on the 2FA selection page.

**Comment by cornelinux** [comment]
Thx. What is the recommended way to install 9.1.1RC2?

**Comment by PVince81** [comment]
@cornelinux well it depends how you installed the previous version.
In general I'd recommend simply using the tarballs that can be found on the owncloud.org website.
But for now I'd say just wait a day or two for the 9.1.1 final release to be out then download the tarball.

**Comment by cornelinux** [comment]
9.1.1RC3 still has the same problem.

The user "cornelius" authenticated successfully. But the user "neuer" has not been logged in previously.
https://www.privacyidea.org/wp-content/uploads/2016/09/owncloud-loop.mp4

**Comment by PVince81** [comment]
Ouch, now I see it. Workaround would be to disable the first run wizard app.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/firstrunwizard/issues/52
