### ISSUE TITLE
Admin view, 'Generate Password' and 'Revoke credentials' buttons should have the same width

### ISSUE THREAD

**Issue by davitol** [owncloud/core#26144]
### Steps to reproduce

1. Go to admin view
2. Generate a password

### Expected behaviour

Both buttons should have the same width

### Actual behaviour

'Generate password' button is a bit wider than the 'revoke credentials' one.

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0.8

**ownCloud version:**

9.1.1.2","versionstring":"9.1.1 RC3"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
```
### Client configuration

**browser**
 
Firefox

![screen shot 2016-09-19 at 12 03 32](https://cloud.githubusercontent.com/assets/10596560/18628650/7ed7adca-7e61-11e6-8894-8f6310ae0e61.png)

**Comment by felixheidecke** [comment]
The button width is content-aware. Other languages might even produce greater differences in width. IMHO *no bug*.

**Comment by davitol** [comment]
@felixheidecke Thanks for your comment. Let's close it then
