### ISSUE TITLE
Error On UPDATER & UPDATING. "cPanel server"

### ISSUE THREAD

**Issue by pixadex** [owncloud/core#26159]
### Steps to reproduce
1.Updater
2.
3.

### Expected behaviour
FIX ERROR to normal.
### Actual behaviour
Doesn't want to update proberly.
### Server configuration
**Operating system**:
9.0.3
**Web server:**

**Database:**
cpanel
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
9.0.3-9.04?
**Updated from an older ownCloud or fresh install:**
older owncloud
**Where did you install ownCloud from:**
cpanel
**Signing status (ownCloud 9.0 and above):**
9.0.3-9.0.4?
**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

EROR MESSAGE on UPDATER

Fatal error: Uncaught exception 'Symfony\Component\Process\Exception\RuntimeException' with message 'The Process class relies on proc_open, which is not available on your PHP installation.' in /home/rspixade/public_html/owncloud/owncloud/updater/vendor/symfony/process/Process.php:144 Stack trace: #0 /home/rspixade/public_html/owncloud/owncloud/updater/src/Utils/OccRunner.php(45): Symfony\Component\Process\Process->__construct('php /home/rspix...') #1 /home/rspixade/public_html/owncloud/owncloud/updater/src/Utils/OccRunner.php(56): Owncloud\Updater\Utils\OccRunner->run('config:list --p...') #2 /home/rspixade/public_html/owncloud/owncloud/updater/src/Utils/ConfigReader.php(106): Owncloud\Updater\Utils\OccRunner->runJson('config:list --p...') #3 /home/rspixade/public_html/owncloud/owncloud/updater/src/Utils/ConfigReader.php(50): Owncloud\Updater\Utils\ConfigReader->load() #4 /home/rspixade/public_html/owncloud/owncloud/updater/src/Controller/IndexController.php(96): Owncloud\Updater\Utils\ConfigReader->init() #5 /home/rspixa in /home/rspixade/public_html/owncloud/owncloud/updater/vendor/symfony/process/Process.php on line 144

**Comment by RealRancor** [comment]
> The Process class relies on proc_open, which is not available on your PHP installation.

Either enable this php function (see google on how to do that) or don't use the updater app and do a manual upgrade:

https://doc.owncloud.org/server/9.1/admin_manual/maintenance/manual_upgrade.html

**Comment by pixadex** [comment]
Do I enable that on owncloud or cpanel?

**Comment by RealRancor** [comment]
In PHP itself. How to do this on Cpanel is something you need to ask at a Cpanel support. Product support can't be given in here

**Comment by pixadex** [comment]
what version of php though

**Comment by pixadex** [comment]
And I also have this error on ownclodu ADMIN "You are accessing this site via HTTP. We strongly suggest you configure your server to require using HTTPS instead as described in our"

**Comment by RealRancor** [comment]
This is a bugtracker, not a support forum

**Comment by pixadex** [comment]
also installing into owncloud? or just enabling it ?

**Comment by pixadex** [comment]
have you read the top?

**Comment by pixadex** [comment]
/dev/urandom is not readable by PHP which is highly discouraged for security reasons. Further information can be found in our

**Comment by pixadex** [comment]
and plus how do manually do it on cpanel server because I'm remote sever. manual update seems like post to be on my computer but its not.

**Comment by RealRancor** [comment]
> This is a bugtracker, not a support forum

**Comment by pixadex** [comment]
I was talk to server admin and php automatically on? so what else the problem then?

**Comment by RealRancor** [comment]
@DeepDiver1975 Also something to close here.
