### ISSUE TITLE
[SMB External Storage] Some big files being corrupted when downloaded

### ISSUE THREAD

**Issue by MrJackJonesIII** [owncloud/core#26155]
### Steps to reproduce
1. Add an external smb share (Movies) to a windows machine in the oc webinterface
2. It should be a share with lots of big files, mine is 3,5TB of movies, 1445 Folders with 11288 Files, structure is /Movies/A/A_Movie/A_Movie.mkv
3. Let occ scan the files
4. Go to oc webinterface, browse to /Movies/A/. The folder /A_Movie will show the correct size (say 5G) and that it's been scanned a few minutes ago. 
5. Enter the folder. The movie file will show a way t.oo small size (say 300M). 
6. Download the file. It will only be 300M. 
7. Start playing it. It will start running but just a portion of actual length.
8. In the web interface navigate back to the level with the movie folders /Movies/A/. now the folder /A_Movie will show the smaller size (300M) and that it's been scanned a few month ago. 
### Expected behaviour

The files should be downloaded without being corrupted.
### Actual behaviour

see above

Important notice:
You'll see some BadMethodCallException errors in the logs. I got rid of these by applying the patch from https://github.com/owncloud/core/issues/25506

libsmbclient-php is installed
### Server configuration

**Operating system**: Raspian Jessy

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7

**ownCloud version:** 9.1

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** repo

**Signing status (ownCloud 9.0 and above):** all good

**List of activated apps:**

Enabled:
- activity: 2.3.2
- calendar: 1.3.3
- comments: 0.3.0
- contacts: 1.3.1.0
- dav: 0.2.5
- federatedfilesharing: 0.3.0
- federation: 0.1.0
- files: 1.5.1
- files_external: 0.6.0
- files_pdfviewer: 0.8.1
- files_sharing: 0.10.0
- files_texteditor: 2.1
- files_trashbin: 0.9.0
- files_versions: 1.3.0
- firstrunwizard: 1.1
- gallery: 15.0.0
- notifications: 0.3.0
- provisioning_api: 0.5.0
- systemtags: 0.3.0
- tasks: 0.9.3
- templateeditor: 0.1
- updatenotification: 0.2.1
  Disabled:
- encryption
- external
- files_antivirus
- files_videoplayer
- user_external
- user_ldap

**The content of config/config.php:**

{
    "system": {
        "updatechecker": false,
        "instanceid": "ocfodyqednuy",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "192.168.77.13",
            "owncloud.mydomain.de",
            "cloud.mydomain.de",
            "owncloud",
            "mmrp01"
        ],
        "datadirectory": "\/data\/owncloud",
        "overwrite.cli.url": "http:\/\/owncloud.mydomain\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\OC\Memcache\APCu"
    }
}

```

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
Tested with Firefox and Chrome

**Operating system:** Windows 8 and 10

### Logs
#### Web server error log
[Mon Sep 19 16:15:44.548251 2016] [mpm_prefork:notice] [pid 7025] AH00163: Apache/2.4.23 (Raspbian) OpenSSL/1.0.2h configured -- resuming normal operations
[Mon Sep 19 16:15:44.548485 2016] [core:notice] [pid 7025] AH00094: Command line: '/usr/sbin/apache2'
[Mon Sep 19 16:34:02.978567 2016] [:error] [pid 7036] [client 188.199.177.1:54217] PHP Warning:  smbclient_state_errno(): supplied resource is not a valid smbclient state resource in /var/www/owncloud/apps/files$
[Mon Sep 19 16:34:02.979364 2016] [:error] [pid 7036] [client 188.199.177.1:54217] PHP Fatal error:  Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in /var/www/$


#### ownCloud log (data/owncloud.log)
{"reqId":"eZE47O80FMbnq7np6InQ","remoteAddr":"","app":"files","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"Not in batch\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(143): OC\\\\Files\\\\Cache\\\\Propagator->commitBatch()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(52): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/var\\\/www\\\/owncloud\\\/cron.php(122): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Propagator.php\",\"Line\":145}","level":3,"time":"2016-09-19T14:15:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"eZE47O80FMbnq7np6InQ","remoteAddr":"","app":"files","message":"Exception: {\"Exception\":\"BadMethodCallException\",\"Message\":\"Not in batch\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(143): OC\\\\Files\\\\Cache\\\\Propagator->commitBatch()\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(52): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/var\\\/www\\\/owncloud\\\/cron.php(122): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Propagator.php\",\"Line\":145}","level":3,"time":"2016-09-19T14:15:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"IX1ZGjcjwviefO1fVEfv","remoteAddr":"188.199.177.1","app":"PHP","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/owncloud\/lib\/private\/Files\/Filesystem.php:772\nStack trace:\n#0 \/var\/www\/owncloud\/lib\/private\/Files\/View.php(2032): OC\\Files\\Filesystem::normalizePath('\/michael\/files\/...')\n#1 \/var\/www\/owncloud\/lib\/private\/Files\/View.php(1150): OC\\Files\\View->unlockFile('\/Filme\/A\/Americ...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/owncloud\/lib\/private\/Files\/Filesystem.php#772","level":3,"time":"2016-09-19T14:35:54+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"michael"}
{"reqId":"wwDw28jAf4wNWnYAT6Bn","remoteAddr":"881.991.771.1","app":"core","message":"Trusted domain error. \"881.991.771.1\" tried to access using \"79.200.198.76\" as host.","level":2,"time":"2016-09-19T15:14:42+00:00","method":"GET","url":"\/","user":"--"}

Some more info:
- Windows server where the share with the files reside is WHS 2011 with a DriveBender drive pool.
- OC is running on Raspberry Pi



```

**Comment by PVince81** [comment]
@jvillafanez maybe some trouble with bigger files

**Comment by PVince81** [comment]
You might want to try again with 9.1.1RC2 or 9.1.1 final when it's out in the next few days. It contains a fix for the BadMethodCallException.

**Comment by MrJackJonesIII** [comment]
I guess you're advise is for the BadMethodCallException thing atm and not about the big files thing right?

**Comment by PVince81** [comment]
Yes. But I guess having the ability to run occ files:scan properly might help fix things sometimes.

**Comment by jvillafanez** [comment]
Some things to check with smbclient (please, install the application if not yet installed).

1. Download the same file with smbclient and check if the file transfer stops at some point. If smbclient can't do that, ownCloud neither.
2. You've said that first the file size is correct, then download the file with a wrong size and finally the file has a wrong size shown in ownCloud. After all this, check the file size that the smbclient application reports, and also check the file in windows.

It would be very interesting if you can provide some wireshark traces to know what happen with the file transfer. So far, the only information I have is http://sead1.open.ac.uk/samba_analysis/bugzilla/bugentry_6558.html which might fit in your scenario. Quoting from the link:
```
Try to set "keepalive = 0" in the [global] section of your smb.conf.
```

@owncloud/qa to check and reproduce this scenario

**Comment by MrJackJonesIII** [comment]
Ok, I did some tests.

> Download the same file with smbclient

I did that and the file gets downloaded properly:
![screenshot_mmnote_2016-09-20 12 06 43](https://cloud.githubusercontent.com/assets/1665937/18667262/2376f7fe-7f30-11e6-95dd-8f41b68f62f5.jpg)

> check the file size that the smbclient application reports, and also check the file in windows.

Fine as well...
![screenshot_mmnote_2016-09-20 11 54 12](https://cloud.githubusercontent.com/assets/1665937/18667228/f8d90f46-7f2f-11e6-907a-faa9a3f143e7.jpg)
![screenshot_mmnote_2016-09-20 11 52 48](https://cloud.githubusercontent.com/assets/1665937/18667236/01e57c28-7f30-11e6-899e-030d8a502f3e.jpg)

I can do some wiresharking this afternoon. Never done that so it might take some time. I guess it be better to be cautious with the results. Where do you want me to send them to?
And I'll check the keepalive setting later as well.

**Comment by jvillafanez** [comment]
I just want to know if there is a connection error between ownCloud and windows at some point. Just a couple of screenshots showing the error (or success) are enough. Just save the trace somewhere in case we need more info.

**Comment by MrJackJonesIII** [comment]
I noticed something which might be of interest: I just had occ do a scan on the files an even after that the Folder size was wrong. And the results of the scan were 1205 folders and 10361 files. Which is less than 1445/11288 from the scan yesterday when oc showed the correct folder size initially.

And something else came to my mind: There is this hidden setting on the share on how to check for changes. This is set to check on access on my sys. 
![screenshot_mmnote_2016-09-20 12 56 28](https://cloud.githubusercontent.com/assets/1665937/18667810/5bf8196c-7f32-11e6-97ad-d27e76a12e20.jpg)
As the size gets set to the wrong small size when entering the folder this might be of interest I guess?

**Comment by MrJackJonesIII** [comment]
Allright, I'll come back to you with the results later...

**Comment by MrJackJonesIII** [comment]
Ok, I traced the download in wireshark. To be honest I have no f.. clue for what I am looking. Can you please point me in the right direction? 
Those are the last lines after the download completed and I stopped the trace:
![screen_mmstation_20160920_16h28m44s](https://cloud.githubusercontent.com/assets/1665937/18674441/8879ee1c-7f4f-11e6-8dfe-48f880d6d3fd.jpg)
This one should have been the 5G something file from above. OC webinterface showed 1,5G and firefox downloaded without complaining. Again the file started to play but vlc quit after some time.

**Comment by MrJackJonesIII** [comment]
Some more info: I copied the directory with the movie into my oc user folder on the rpi and had occ run the scan again. The file is showing up fine there with 5.5GB and it's downloaded completely.

**Comment by jvillafanez** [comment]
More information to understand the trace a bit: http://stackoverflow.com/questions/13049828/fin-vs-rst-in-tcp-connections

So 10.0.2.15 is the first to close the connection and I guess 79.200.198.76 just follows. So, who is who? I guess 10.0.2.15 is the windows machine. If this is the case, does windows close the connection before finishing sending all the file?

You can also filter by protocol to only show SMB or SMB2 traffic. Maybe there is more meaningful information there.

**Comment by MrJackJonesIII** [comment]
Yes you're right 10.0.2.15 is the windows client and 79.200.198.76 is the rpi with oc. This brings me to the idea that I might have gotten your intention wrong... Do you want me to run the trace on the windows server to see what is happening between win server <> oc instead of looking at windows client/browser <> oc?

**Comment by jvillafanez** [comment]
Yes, please.

There shouldn't be an issue between client and ownCloud because ownCloud is (probably) sending all the info it has, even though it isn't the complete file. The problem should be in the connection between ownCloud and the windows server.

Just the be sure, does the ownCloud server has plenty of free space to hold the whole file? ownCloud  might be downloading the file to the server before sending it to the client.

**Comment by MrJackJonesIII** [comment]
So did some tracing again...
First regarding your question about the available disk space: The rpi has 13GB of that. It's not plenty but should suffice I guess. 
I tried to make any sense of the traces but to be honest my skills here are quit limited. I'd send the respective parts of the trace to you if you're fine with that?

**Comment by MrJackJonesIII** [comment]
I've sent you a mail...

**Comment by MrJackJonesIII** [comment]
Are you thinking of https://github.com/eduardok/libsmbclient-php ?
This is already installed.

**Comment by jvillafanez** [comment]
Yes, but the problem are those 2 errors; they might be related to the issue. By using a default installation we can detect if your installation has some kind of environmental problem.

There is also another thing we can do to confirm where is the problem: you can try a curl request like `curl -u user:password -v -o /dev/null http://10.40.30.21:8130/remote.php/webdav/welcome.txt` and check the "Content-Length" header.

```
$ curl -u user:password -v -o /dev/null http://10.40.30.21:8130/remote.php/webdav/welcome.txt
* Hostname was NOT found in DNS cache
*   Trying 10.40.30.21...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to 10.40.30.21 (10.40.30.21) port 8130 (#0)
* Server auth using Basic with user 'admin'
> GET /remote.php/webdav/welcome.txt HTTP/1.1
> Authorization: Basic YWRtaW46UGFzc3dvcmQ=
> User-Agent: curl/7.35.0
> Host: 10.40.30.21:8130
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Tue, 27 Sep 2016 06:57:40 GMT
* Server Apache/2.4.7 (Ubuntu) is not blacklisted
< Server: Apache/2.4.7 (Ubuntu)
< X-Powered-By: PHP/5.5.9-1ubuntu4.16
< Set-Cookie: oclraio8xgrp=bhe1qo87djoltj5gptgh46nf54; path=/; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=gg4yOlzn7tMdMVNVhx0GU1O%2FLHFz5%2BkGfiMsyVqDar4g04Rl%2BdcUCE8R9AcOruEyHcX0pkf0gfXx3dsQygUwfvtt3mRG2CgmxlnfmmfIqgolUxm1y486dgadwN739fM8; path=/; httponly
< Content-Security-Policy: default-src 'none';
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: Sameorigin
< X-Robots-Tag: none
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Set-Cookie: oclraio8xgrp=la79nmqamtduabpmd3873dm8c1; path=/; HttpOnly
< Set-Cookie: cookie_test=test; expires=Tue, 27-Sep-2016 07:57:40 GMT; Max-Age=3600
< Last-Modified: Thu, 04 Aug 2016 12:49:21 GMT
< ETag: "9ff20fece03bf141111f9bd09f03ea5e"
< Content-Length: 163              <<------------ HERE
< Content-Disposition: attachment; filename*=UTF-8''welcome.txt; filename="welcome.txt"
< OC-ETag: "9ff20fece03bf141111f9bd09f03ea5e"
< Vary: Accept-Encoding
< Content-Type: text/plain;charset=UTF-8
< 
{ [data not shown]
100   163  100   163    0     0    523      0 --:--:-- --:--:-- --:--:--   525
* Connection #0 to host 10.40.30.21 left intact
```
The content length should match the size of your file (around 1.5GB). If the filesize is less, it make obvious the code has a bug somewhere, probably in the size calculation. We can also discard an issue in the transfer between ownCloud and the client.

**Comment by MrJackJonesIII** [comment]
@jvillafanez 
Thanks for the the new hints. I'll set up an virtual box with a fresh clean install of oc and check.
I tried to curl my current install as you suggested but please help me out here with some additional info: From your last words I assume that you want me to curl directly to the file in question. Please give me some hints on how to do that. I am not sure about the syntax of the link. I tried to use the local link given by oc on the details tab of the file and the download link as well. The first will give me 
`< Content-Length: 43
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Robots-Tag: none
< X-Frame-Options: SAMEORIGIN
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Content-Type: application/json; charset=utf-8` 
and the download link will throw an error `bash: syntax error near unexpected token `('`

**Comment by MrJackJonesIII** [comment]
So, I got some news... I figured out the webdav link to the file and did the curl again. 
`curl -u user:pass -v -o /dev/null https://cloud.mydomain.de/remote.php/webdav/Filme/A/American%20Movie%20(2013)%20-%20tt1800241/American%Movie%20(2013)%20-%20tt1800241.mkv`
It didn't go through and gave me the error about the ( again. So I changed the folder and all files in it to Movie_year_tt123456 and did a occ scan again. Now the correct filesize (5GB) will be kept on entering the folder but the file will still be downloaded with the wrong size (1.5GB)
Curling the ranamed file will give me this:
`root@mmrp01:/var/www/owncloud# curl -u user:pass -v -o /dev/null https://cloud.mydomain.de/remote.php/webdav/Filme/A/American_Movie_2013_tt1234567/American_Movie_2013_tt1234567.mkv
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 192.168.2.3...
* Connected to cloud.mydomain.de (192.168.2.3) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: CN=cloud.mydomain.de
*        start date: 2016-08-16 14:52:00 GMT
*        expire date: 2016-11-14 14:52:00 GMT
*        subjectAltName: cloud.mydomain.de matched
*        issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*        SSL certificate verify ok.
* Server auth using Basic with user 'user'
> GET /remote.php/webdav/Filme/A/American_Movie_2013_tt1234567/American_Movie_2013_tt1234567.mkv HTTP/1.1
> Authorization: Basic bWFzdGVybWlnOkszbmQwazFuZw==
> User-Agent: curl/7.38.0
> Host: cloud.mydomain.de
> Accept: */*
>
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0< HTTP/1.1 401 Unauthorized
< Date: Tue, 27 Sep 2016 09:17:42 GMT
* Server Apache/2.4.23 (Raspbian) is not blacklisted
< Server: Apache/2.4.23 (Raspbian)
< Strict-Transport-Security: max-age=15552000; includeSubDomains
< Set-Cookie: ocfodyqednuy=onn11n3t2cehu90lqml88hjq83; path=/; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=wNfjgUE860yTptmGW5qohXq9JFArgdC5jM7UaZzTx96TIQpAbHef8q5BdvLEYOfUQWg03y96w7RJPbunKSY7QNVxZmQcfvsKo3e8VaZdZufTnocTNHS3M4t03gH8nS13; path=/; secure; HttpOnly
< Content-Security-Policy: default-src 'none';
< Set-Cookie: ocfodyqednuy=qevc2o2va45tsb0j42a9plte30; path=/; secure; HttpOnly
* Authentication problem. Ignoring this.
< WWW-Authenticate: Basic realm="ownCloud"
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Robots-Tag: none
< X-Frame-Options: SAMEORIGIN
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Content-Length: 234
< Content-Type: application/xml; charset=utf-8
<
{ [data not shown]
100   234  100   234    0     0    302      0 --:--:-- --:--:-- --:--:--   303
* Connection #0 to host cloud.mydomain.de left intact`

**Comment by jvillafanez** [comment]
You need to provide your credentials to access to your ownCloud account:
```
curl -u {your-user}:{your-password} -v -o /dev/null http://blabla/bla.....
```
I think if you omit the password you'll be asked for it (in case you don't want to provide your password in cleartext.

**Comment by MrJackJonesIII** [comment]
Ah damn... Stupid... Took the wrong credentials... I'll be right back with the new result...

**Comment by MrJackJonesIII** [comment]
Hi, sorry, took me a little longer...
So as it turned out it didn't work with user:path. The cursor just kept blinking with this. With omitting the password and entering it on request it worked. And curl is getting a file of 1.5G. Should be 5G...
 
![screenshot_mmnote_2016-09-27 14 42 04](https://cloud.githubusercontent.com/assets/1665937/18873614/9e2139a2-84c0-11e6-901e-0116d40d6782.jpg)

After doing the occ scan I get same result.

**Comment by jvillafanez** [comment]
So far all the tests that I'm doing are passing fine in my machine 😕 (ubuntu 16.04, php7 and ownCloud 9.1.1; php-smbclient library installed)

Checked with a file of around 1.5GB and another with near 5GB.

**Comment by MrJackJonesIII** [comment]
Ok. I've set up a completely fresh install on a virtual machine. And it is working as it should...😕
Differences to my production system are:
- os is ubuntu 16.04 and not raspian
- I do use sqlite and not mysql
- caching is not enabled
- ssl is not set up
- the virtual box is running on the windows server as host so network requests and traffic should be way snappier then from the raspi
What do think is best to do now? Bring the test machine as near as it gets to the production system step-by-step?

**Comment by MrJackJonesIII** [comment]
So I did some more testing on the test machine:
- I converted to mysql: No change, the files are still fine
- Enabled APCu for caching: No change
- Set up ssl: No change

I disabled caching on the productive machine as well to no avail.

**Comment by jvillafanez** [comment]
If the code is the same in both systems, there might be issues with the libsmbclient library installed in your machine, or with the php bindings.

**Comment by MrJackJonesIII** [comment]
Ok, I think I know what went wrong. Not exactly but I found out, that installing owncloud in a default current state on rpi is not as easy as I thought. OC and some dependencies seem to be available from default raspian repos and those old versions are getting preferred when installing with apt-get. I'm currently figuring out how to force the install from a specific repo and will get back as soon as I managed to do a vanilla install...

**Comment by MrJackJonesIII** [comment]
Ok, this sucks... I did a complete fresh install of raspian and oc on the rpi. I managed to do a vanilla install from the oc debian repo which will give me php5. Which sucks cause it is way slower that php7 but I can live with that. I did the exact same steps for installing libsmbclient-php (php5-dev and libsmbclient-dev, then pecl install smbclient) as on the virtual ubuntu machine. The result it that I the exact same corrupted files as before.

**Comment by PVince81** [comment]
More info in the linked ticket https://github.com/eduardok/libsmbclient-php/issues/43#issuecomment-250966064 pointing at a potential Icewind/SMB issue

**Comment by PVince81** [comment]
Is the file corrupted or truncated ? If truncated, duplicate of https://github.com/owncloud/core/issues/21171

**Comment by PVince81** [comment]
Closing due to lack of feedback
