### ISSUE TITLE
403 error /remote.php/dav/admin/CALENDARNAME

### ISSUE THREAD

**Issue by jordivn** [owncloud/core#26163]
### Steps to reproduce
1. On fresh install add Calendar app
2. Add an calendar
3.

### Expected behaviour
Calendar added

### Actual behaviour
Nothing and in the developer consol show:
https://jordivn.nl/remote.php/dav/calendars/admin/spat/ 403 (Forbidden)

### Server configuration
**Operating system**:
Linux ?? (Shared Hosting)
**Web server:**
Apache 2.4.17
**Database:**
MySQL 5.5.34
**PHP version:**
Php 5.5.32
**Server version:** (see your admin page)
9.1.0
**Calendar version:** (see the apps page)
1.4.0
**Updated from an older installed version or fresh install:**
fresh
**Signing status (ownCloud/Nextcloud 9.0 and above):**
ownCloud
```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
- activity
- collaborative tags
- comments
- deleted files
- federation
- first run wizard
- gallery
- mail template editor
- notifications
- pfd viewer
- provisioning API
- Share Files
- Text Editor
- Update Notification
- Versions
- Video player
- Calendar

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc3zc369ca85',
  'passwordsalt' => 'YkLHCqbT3uu9y07vS9vCE6MZ3MMQIj',
  'secret' => 'JN2WmHDd0WSDkay4bp9H9qzylNkyg+piM74X/KNJhoufjV+K',
  'trusted_domains' => 
  array (
    0 => 'jordivn.nl',
  ),
  'datadirectory' => '/home/websedb46/domains/jordivn.nl/private_html/data',
  'overwrite.cli.url' => 'https://jordivn.nl',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'dbname' => 'websedb46_oc',
  'dbhost' => '10.3.0.106',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'websedb46_oc',
  'dbpassword' => '***',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
);

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10
#### Web server error log
```
Insert your webserver log here
```

#### Log file (data/owncloud.log)
```
none
```

#### Browser log
```

spat/	403	xhr	client.js?v=f002ec0…:183	2.1 KB	248 ms	
notifications?format=json	200	xhr	jquery.js:8630	896 B	440 ms	
3.00 s4.00 s5.00 s6.00 s7.00 s8.00 s9.00 s10.00 s
2 requests ❘ 3.0 KB transferred

Console





Preserve log
﻿
jquery-migrate.min.js?v=f002ec0…:2 JQMIGRATE: Migrate is installed, version 1.4.0
https://jordivn.nl/remote.php/dav/calendars/admin/spat/ Failed to load resource: the server responded with a status of 403 (Forbidden)
client.js?v=f002ec0…:183 MKCOL https://jordivn.nl/remote.php/dav/calendars/admin/spat/ 403 (Forbidden)
﻿

**Comment by RealRancor** [comment]
Your shared hoster has most likely some restrictions in place not allowing this MKCOL http verb. Please close here and follow this FAQ containing all known info about such environmental issues:

https://central.owncloud.org/t/how-to-fix-caldav-carddav-webdav-problems/852

As you're on a shared hoster you might need to contact the support of that hoster
