### ISSUE TITLE
Allow to install not present apps via `occ`

### ISSUE THREAD

**Issue by ypid** [owncloud/core#26166]
### Steps to reproduce
1. ownCloud installation without `contacts` app installed
2. Run `sudo -u www-data php occ app:enable contacts`
### Expected behaviour

Install and enable the app.
### Actual behaviour

contacts not found
### Server configuration

**ownCloud version**: 9.0.4

Ref: https://github.com/owncloud/core/issues/26126
### Client configuration

Ref: https://github.com/owncloud/core/issues/26126
### Solution

As the command is called `occ app:enable` I think a `--install` or something would be nice. Alternatively, maybe a extra subcommands could be added like `occ app:install`?
### Refs

Tracked downstream: https://github.com/debops/ansible-owncloud/issues/61
Related to: https://github.com/owncloud/core/issues/20838

**Comment by DeepDiver1975** [comment]
I like the idea - anybody is welcome to contribute and submit a PR.

**Comment by PVince81** [comment]
Obsoleted by market commands. @DeepDiver1975 please link to documentation about commands, thanks.
