### ISSUE TITLE
[App development] custom detailed side view triggers sharing

### ISSUE THREAD

**Issue by labkode** [owncloud/core#26177]
@DeepDiver1975 @PVince81 
I am developing an alternative app trashbin for EOS, but when I add my side view with EOS specific contents, the view also loads Sharing stuff and triggers sharing calls. How can I avoid to trigger this behaviour?
The code that adds the my custom view is here: https://github.com/cernbox/files_eostrashbin/blob/master/js/filelist.js#L54

![sideview-triggers-sharing](https://cloud.githubusercontent.com/assets/5175912/18742007/5972e060-80b2-11e6-9253-17e6161fafc7.png)

**Comment by PVince81** [comment]
Maybe because the sharing tab is the first tab so it loads its content ?

**Comment by PVince81** [comment]
Try commenting out this line https://github.com/owncloud/core/blob/v9.0.5/apps/files_sharing/js/share.js#L180 to avoid share tab registration and see if the problem disappears

**Comment by labkode** [comment]
@PVince81 Commenting that line worked like a charm, but if I do that I remove the share view from the normal file view. Is there a way to de-register that sharing view ? 

I think one app (sharing) should not dictate the behaviour of other apps, or at least the sideview should be per application.

Thank you

**Comment by PVince81** [comment]
By default if any app is providing a FileList, the sharing tab will register itself in the sidebar.
So far the exceptions are hard-coded here: https://github.com/owncloud/core/blob/v9.0.5/apps/files_sharing/js/share.js#L32

So a quick hack for you would be to set the id of your file list to be "trashbin" which will prevent other tabs like versions, activity, etc to register themselves there.

**Comment by labkode** [comment]
Thanks, that works for now, but I think that this should be improved towards a better API, like a config variable in the OCA.Share app.

Cheers

**Comment by PVince81** [comment]
@labkode this doesn't only apply to the share tab but also to any other tab and third party app that might add tabs to the details view.

Imagine if someone writes an app to for example show EXIF info in a new tab. They'd want their tab to appear on all regular file lists like "All files", "Shared with you", etc. The trashbin list is rather an exception.
So we need a better API to let a FileList specify whether it's a regular file list (all detail tabs welcome) or a special file list (no tabs welcome) like yours or trashbin.

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/26228
