### ISSUE TITLE
Error On UPDATER & UPDATING. "cPanel server"

### ISSUE THREAD

**Issue by pixadex** [owncloud/core#26174]
Hello one of the support people close my issus and did't resolve it, I'm using payed server can't manually update it, when I update through updater I get 
Fatal error: Uncaught Symfony\Component\Process\Exception\RuntimeException: The Process class relies on proc_open, which is not available on your PHP installation. in /home/rspixade/public_html/owncloud/owncloud/updater/vendor/symfony/process/Process.php:144 Stack trace: #0 /home/rspixade/public_html/owncloud/owncloud/updater/src/Utils/OccRunner.php(45): Symfony\Component\Process\Process->__construct('php /home/rspix...') #1 /home/rspixade/public_html/owncloud/owncloud/updater/src/Utils/OccRunner.php(56): Owncloud\Updater\Utils\OccRunner->run('config:list --p...') #2 /home/rspixade/public_html/owncloud/owncloud/updater/src/Utils/ConfigReader.php(106): Owncloud\Updater\Utils\OccRunner->runJson('config:list --p...') #3 /home/rspixade/public_html/owncloud/owncloud/updater/src/Utils/ConfigReader.php(50): Owncloud\Updater\Utils\ConfigReader->load() #4 /home/rspixade/public_html/owncloud/owncloud/updater/src/Controller/IndexController.php(96): Owncloud\Updater\Utils\ConfigReader->init() #5 /home/rspixade/public_html/owncloud/ow in /home/rspixade/public_html/owncloud/owncloud/updater/vendor/symfony/process/Process.php on line 144

Very important need this to be fix I have very important stuff on there.
THANK YOU.

**Comment by RealRancor** [comment]
@pixadex This is no support forum as already written in your other issue. Support for cpanel is available here: http://cpanel.com/support/

**Comment by pixadex** [comment]
proc_open what will that do.

**Comment by PVince81** [comment]
The new updaters will not require proc_open any more, closing.

cc @VicDeo
