### ISSUE TITLE
Recent GitHub refs on https://owncloud.org/changelog result in 404

### ISSUE THREAD

**Issue by ypid** [owncloud/core#26179]
URL: https://owncloud.org/changelog
Example: 

Version 9.1.1 Sep 20 2016
`Core: Remove OCS response body for HTTP status 204 and 304 which disturbed some firewalls - core/#25835`

The `core/#25835` points to: `https://github.com/owncloud/core/issue/25835`
Which should be: `https://github.com/owncloud/core/issues/25835` or `https://github.com/owncloud/core/pull/25835`

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/owncloud.org/pull/1059 already but maybe the website has a caching issue @jnweiger ?

**Comment by DeepDiver1975** [comment]
Still not updated ......

**Comment by jnweiger** [comment]
Fixed. 
The cron with github checkout had failed with a merge conflict.
