### ISSUE TITLE
Encryption not ready error after data migration from one storage backend to another

### ISSUE THREAD

**Issue by joeyjy** [owncloud/core#26175]
### Steps to reproduce
1. stop httpd
2. create a ceph container named 'test' and migrate data in old container to 'test'
3. change objectstore->arguments->container to test
4. start httpd

### Expected behaviour
upload and download successfully

### Actual behaviour
error page shows:
Service Unavailable
Encryption not ready: multikeydecrypt with share key failed:error:0407106B:rsa routines:RSA_padding_check_PKCS1_type_2:block type is not 02

### Server configuration
**Operating system**:
Centos 7
**Web server:**
apache
**Database:**
mysql
**PHP version:**
5.4
**ownCloud version:** (see ownCloud admin page)
9.0.1
**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**
official website
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocywzvuknfvm',
  'passwordsalt' => 'ab6GMwatP/Y2YW3CN8GB5LDqXVnSc/',
  'secret' => 'OUlEOr5rh4W6MSqdKP+g0K795JCwJYP6zlEsXJNPunaVun70',
  'trusted_domains' =>
  array (
    0 => '10.17.1.102',
  ),
  'datadirectory' => '/var/www/html/oc/data',
  'overwrite.cli.url' => 'https://10.17.1.102',
  'dbtype' => 'mysql',
  'version' => '9.0.1.3',
  'dbname' => 'oc',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_cdrive2',
  'dbpassword' => 'LmJbur0aKliIbx56ypWFvmCZJUgAJW',
  'objectstore' =>
  array (
    'class' => 'OC\\Files\\ObjectStore\\Swift',
    'arguments' =>
    array (
      'username' => 'swift',
      'password' => 'swift!@#$',
      'container' => 'test',
      'autocreate' => true,
      'region' => 'RegionOne',
      'url' => 'http://vdesktop.cn1.global.com:5000/v2.0',
      'tenantName' => 'admin',
      'serviceName' => 'swift',
      'urlType' => 'internal',
    ),
  ),
  'logtimezone' => 'UTC',
  'installed' => true,
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
ceph objectstorage
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ldap
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
chrome
**Operating system:**
windows7
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
{"reqId":"V@NKdf1vPeOA4BjD3ha5XwAAAAw","remoteAddr":"10.32.51.48","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 **503 Encryption not ready: multikeydecrypt with share key failed:error:0407106B:rsa routines:RSA_padding_check_PKCS1_type_2:block type is not 02**\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/CDrive\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/CDrive\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/CDrive\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/CDrive\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/CDrive\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/CDrive\\\/remote.php(138): require_once('\\\/var\\\/www\\\/html\\\/C...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/CDrive\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php\",\"Line\":311,\"User\":\"cdrive\"}","level":4,"time":"2016-09-22T03:05:26+00:00","method":"GET","url":"\/remote.php\/webdav\/Documents\/FileZilla_3.17.0.0_win64_setup.exe","user":"cdrive"}
{"reqId":"V@NKdf1vPeOA4BjD3ha5XwAAAAw","remoteAddr":"10.32.51.48","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/html\/CDrive\/3rdparty\/sabre\/http\/lib\/Sapi.php:83) at \/var\/www\/html\/CDrive\/3rdparty\/sabre\/http\/lib\/Sapi.php#58","level":3,"time":"2016-09-22T03:05:26+00:00","method":"GET","url":"\/remote.php\/webdav\/Documents\/FileZilla_3.17.0.0_win64_setup.exe","user":"cdrive"}
{"reqId":"V@NKdf1vPeOA4BjD3ha5XwAAAAw","remoteAddr":"10.32.51.48","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/html\/CDrive\/3rdparty\/sabre\/http\/lib\/Sapi.php:83) at \/var\/www\/html\/CDrive\/3rdparty\/sabre\/http\/lib\/Sapi.php#63","level":3,"time":"2016-09-22T03:05:26+00:00","method":"GET","url":"\/remote.php\/webdav\/Documents\/FileZilla_3.17.0.0_win64_setup.exe","user":"cdrive"}
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

Dear OC team,

This error occurred after data migration to a new Ceph container, I'm sure that all the data has same etag and same size, I think there's no problem with data migration. Very werid, I can't download old files now, with regard to the new uploaded files, there's no problem, need your help :)

**Comment by RealRancor** [comment]
> ownCloud version: (see ownCloud admin page) 9.0.1

from the shown template you have filled out:

> Before reporting any issues please make sure that you're using the latest available version for your major branch (e.g. 9.0.x), see https://owncloud.org/changelog/

This avoids that you're reporting issues which might be already fixed in newer versions (9.0.5/9.1.1)

**Comment by PVince81** [comment]
How did you migrate the data ? You likely had to write a special script for that because the format how the data is stored in a home object store is different, with the object id being the file id from oc_filecache.

**Comment by joeyjy** [comment]
@RealRancor I know I should update to latest version, but I have changed some templates to meet the needs of my company, I'm not sure if it would have some problem after update..

**Comment by joeyjy** [comment]
@PVince81 Always thank you for your reply! Here's my migrating script(python), if there's any problem?

**import swiftclient

u = 'user'
k = 'password'

conn = swiftclient.client.Connection(authurl='http://vdesktop.cn1.global.com:5000/v2.0',
                                     user=u,
                                     key=k,
                                     tenant_name='admin',
                                     auth_version='2.0',
                                     os_options={'region_name': 'regionOne'})                                                                                                       

for data in conn.get_container('oc_live')[1]:
    print '{0}\t{1}\t{2}'.format(data['name'], data['bytes'], data['last_modified'])
    obj_tuple = conn.get_object('oc_live', data['name'])
    conn.put_object('oc_test', data['name'], contents=obj_tuple[1])**

**Comment by PVince81** [comment]
is `data['name']` the object key ? this needs to be the file id. It's a flat list of file id as key to object

**Comment by joeyjy** [comment]
@PVince81 yes, file name in ceph is same format, example:
urn:oid:13
urn:oid:14
urn:oid:15
urn:oid:16
urn:oid:19
urn:oid:20
urn:oid:26
urn:oid:27
urn:oid:28
urn:oid:31
...

**Comment by PVince81** [comment]
and did you also import all the encryption keys with the same method ?

**Comment by joeyjy** [comment]
@PVince81 yes, I imported everything into new container includes keys, I'm sure that every file is same as before, with same size and same MD5

**Comment by joeyjy** [comment]
@PVince81 seems if I use same container name, this problem goes away... So decryption process also depends on ceph container's name?

**Comment by PVince81** [comment]
> same container name

What do you mean ?

**Comment by PVince81** [comment]
Encryption doesn't depend on anything in particular as long as the keys are accessible.
ownCloud has a virtual file system and when home object store is configured it would store everything in the object store instead of local filesystem.

**Comment by joeyjy** [comment]
@PVince81 The origin Ceph container name is oc_live, I changed the destination container name from test to oc_live on my new Ceph cluster, then migrating data, everything is ok now.

**Comment by PVince81** [comment]
Ah, I thought you migrated from local FS to Ceph but not from Ceph to Ceph...

It is likely that the container name is stored in the storage id in oc_storages, you could check that.
If yes, then it needs to be kept to prevent losing the index.
