### ISSUE TITLE
302 Redirect to default application/url

### ISSUE THREAD

**Issue by labkode** [owncloud/core#26185]
@DeepDiver1975 @PVince81 

I have developed an application to manage EOS versions, the ajax call for retrieving the versions is made and hit this url:

```
http://localhost/core/index.php/apps/files_eosversions/ajax/getEosVersions.php?source=%2F4234_001.pdf&start=0
```

but I got a redirect to the default application/url. See full trace below:

RESPONSE
```
HTTP/1.1 302 Found

Date: Thu, 22 Sep 2016 13:06:53 GMT

Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.16

X-Powered-By: PHP/5.4.16

Expires: Thu, 19 Nov 1981 08:52:00 GMT

Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0

Pragma: no-cache

content-security-policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *

X-XSS-Protection: 1; mode=block

X-Content-Type-Options: nosniff

X-Frame-Options: Sameorigin

X-Robots-Tag: none

x-download-options: noopen

X-Permitted-Cross-Domain-Policies: none

Location: http://localhost/core/index.php/apps/files/

Content-Length: 0

Keep-Alive: timeout=5, max=97

Connection: Keep-Alive

Content-Type: text/html; charset=UTF-8
```

Is there any flow/check in ownCloud that redirects to default app/url ?

**Comment by labkode** [comment]
just forget it, it was a typo in the ajax url :(

**Comment by PVince81** [comment]
why not use the app framework with proper routes ?
the ajax/* approach is more likely to be insecure if not done properly.

See https://github.com/owncloud/core/blob/master/apps/files/appinfo/routes.php#L42 and https://github.com/owncloud/core/blob/master/apps/files/lib/Controller/ApiController.php#L119 and https://github.com/owncloud/core/blob/master/apps/files/lib/AppInfo/Application.php#L41 for an example.

**Comment by labkode** [comment]
Thanks for the hint, I based my trashbin and versions on ownCloud's, and I could not see those routes.
Is there a reason why you don't use the new AppFramework in your apps ?

**Comment by PVince81** [comment]
Yes, because we didn't have time to refactor these apps yet to the new APIs...

**Comment by labkode** [comment]
@PVince81, great! So I will use the new API format for my apps.
Cheers
