### ISSUE TITLE
User cannot increase permissions on his own group share if he's inside the group

### ISSUE THREAD

**Issue by ckamm** [owncloud/core#26182]
**ownCloud version:** 9.0.5.2

### Steps to reproduce
1. Set up such that you have a user A and a group G that contains A (like "admin" and "admin (group)")
2. As A, share something with group G using the web interface.
3. Remove the share or edit permission and try to re-add it.

### Expected behaviour
It should work since A is the owner of the share.

### Actual behaviour
The permissions cannot be added again. There's an error with status code 404 and the message "Cannot increase permissions". 

### Analysis
That's because the share is both incoming and outgoing for A and the permission-setting code in `apps/files_sharing/lib/API/Share20OCS.php` checks that one doesn't increase permissions for incoming shares. Therefore A cannot increase the permissions on his own share.

### Related
The bug can also be triggered from the desktop client, see owncloud/client#5197

**Comment by SergioBertolinSG** [comment]
I've added an integration test for this case https://github.com/owncloud/core/pull/26183

**Comment by davitol** [comment]
@SergioBertolinSG Milestone changed to 9.0.6 due to it cannot be reproduced in 9.1.1 version (in 9.1.0.15 i was able to reproduce it). So maybe there's a fix in 9.1.1 that IMHO should be backported to 9.0.6

**Comment by PVince81** [comment]
Okay, I'll backport https://github.com/owncloud/core/pull/26045 to 9.0

**Comment by PVince81** [comment]
here you go https://github.com/owncloud/core/pull/26187

**Comment by PVince81** [comment]
8.2.8 does not seem to be affected

**Comment by ckamm** [comment]
@PVince81 Duplicate of #25542?

**Comment by PVince81** [comment]
Yes. Now backported to 9.0.6 through https://github.com/owncloud/core/pull/26187
