### ISSUE TITLE
beta release channel is falsely providing 9.1.0 RC1

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#26191]
Currently the beta channel is providing 9.1.0 RC1 for 9.0.4 users:

https://updates.owncloud.com/server/?version=9x0x4x7x1382907615.86x1435439812xbetaxx2015-02-07T02:34:55+00:00

There are currently at least the following issues:

1. The response has "9.1.0" where actually 9.1.0 RC1 is delivered
2. 9.0.4 users are not pushed to 9.0.5 first
3. If no newer release (like 9.1.2 RC1) is available users should always be redirected to the latest available stable release (e.g. 9.1.1)
4. If 3. isn't applicable no older beta/release candidate should be provided in the "beta" release channel

**Comment by RealRancor** [comment]
From my PoV this should be solved with high priority:

Especially as impatient people are able to change to the "beta" channel too easily where they falsely see that 9.1.0 is provided there where they are actually getting an older testing version like 9.1.0 RC1.

I don't know how many people have updated to 9.1.0 RC1, broken there installations and falsely reported issues which might have been already fixed in the Final release of oC 9.1.0 (There where RC2, RC3 and RC4 in between).

**Comment by PVince81** [comment]
We're working on the next update server update (currently being tested) where all the maintenance releases will be enabled.
I've now added a commit that will switch beta to 9.1.1 final for now.

**Comment by PVince81** [comment]
Ah, and 9.0.4 users don't need to go through 9.0.5 first because the fix that is in 9.0.5 is also in 9.1.0 so it should be fine.

**Comment by PVince81** [comment]
cc @VicDeo

**Comment by PVince81** [comment]
Hmm, I see that the forced upgrade path is supposed to go through 9.0.4. I'll add that to the beta channel as well...

**Comment by RealRancor** [comment]
Thanks. Please also take proper updating of the update server into the release management. I think its not that good if such a old version like 9.1.0 RC1 is provided if RC2-4 was already released.

> Ah, and 9.0.4 users don't need to go through 9.0.5 first because the fix that is in 9.0.5 is also in 9.1.0 so it should be fine.

In this case yes, but maybe there are other cases where they should go to the latest 9.0.x first.

**Comment by PVince81** [comment]
Solved with the latest update server push
