### ISSUE TITLE
Provide API to let apps register their own Sabre plugins

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26195]
Considering that we want Webdav to be the main API in ownCloud, we need a way to let apps register their own Sabre plugins.

@DeepDiver1975 @butonic @mrow4a

**Comment by PVince81** [comment]
This is a prerequisite for trashbin and versions to be able to provide their own endpoints: https://github.com/owncloud/core/issues/10571 https://github.com/owncloud/core/issues/15646

**Comment by DeepDiver1975** [comment]
> Considering that we want Webdav to be the main API in ownCloud, we need a way to let apps register their own Sabre plugins.

I'd add this to the info.xml

```xml
<sabre>
   <plugins>
       <plugin>\OCA\TrashBin\Sabre\VersionPlugin</plugin>
   </plugins>
   <rootcollection>
       <collection>\OCA\TrashBin\Sabre\VersionsRootCollection</collection>
   </rootcollection>
</sabre>

**Comment by PVince81** [comment]
How about dependency injection ?

With this format it means the given classes must have a constructor without arguments.

Maybe we should rather expect a facade class `SabrePluginsProvider` which itself would receive the DAV server and register plugins as needed.

**Comment by DeepDiver1975** [comment]
These classes can be used in the server container to be resolves - we do this for repairsteps and jobs as well

**Comment by DeepDiver1975** [comment]
see https://github.com/owncloud/core/blob/master/lib/private/Repair.php#L102

**Comment by PVince81** [comment]
As we're writing more apps and move more to be in the market, we'll need this mechanism.

**Comment by PVince81** [comment]
Now the interesting part is that now we could move the comments app code (Sabre plugins + managers + DB structure) completely to the comments app. Same for system tags...

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/core/pull/26761

I need to do more actual testing to see if everything fits correctly.
Some concerns:
- when should these app plugins be registered ?
    - inside the `beforeMethod` block that waits for auth ?
    - at the very end ? (this is what the PR does now)
    - what about auth ?
- where should the collection be registered ?
    - at the very end ? (this is what the PR does now)
    - what about auth ?
    - potential naming conflict as the collection provides its own name, maybe we should namespace it to the name of the app ?

For the auth part one idea is to have an attribute `<plugin needs-auth=true>...</plugin>` and same for collections. This would move their registration into the authenticated block.
Or we'd expect the plugins + collections to always implement the ACL schemes. Not sure how to do that though and not sure if it's compatible with the way we do auth now.

@DeepDiver1975 thoughts ?

**Comment by PVince81** [comment]
Interestingly this also means that CalDAV/CardDAV could be moved to their own separate apps and even be disable-able...
