### ISSUE TITLE
[8.2] Updater not using config value

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26199]
In 8.2 we have introduced the config.php value "updater.server.url" which is used by core code.

However it looks like the feed reader from the updater app isn't using it: https://github.com/owncloud/updater/blob/v8.2.8/lib/channel.php#L78

This could cause inconsistencies when testing updates.

@VicDeo please fix

@davitol FYI as discussed

**Comment by PVince81** [comment]
Somehow it works fine on my local env and I can get updates, but on @davitol's env it didn't

**Comment by VicDeo** [comment]
[8.2] https://github.com/owncloud/updater/pull/380
[8.1] https://github.com/owncloud/updater/pull/381
[8.0] https://github.com/owncloud/updater/pull/382
