### ISSUE TITLE
Show warning that windows is unsupported instead of throwing an exception

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#26208]
There are still people trying to run ownCloud on windows like seen e.g. at https://github.com/owncloud/core/issues/26207, https://github.com/owncloud/core/issues/24649#issuecomment-220858095 or https://central.owncloud.org/t/blank-page-on-local-xampp-nothing-to-display-no-login-page-no-any-other-contant/2231

IIRC in older versions a warning was shown that windows isn't supported. Current oC versions are just bailing out with an internal server error / white page and an autoload exception in the logfiles.

To avoid repeating reported issues it could make sense to show such a warning again instead of throwing an internal server error.

*Edit* exception examples:

``
{"reqId":"JfnIJsPx3KCJNNLcbn7y","remoteAddr":"::1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: C:\\\\xampp\\\\htdocs\\\\owncloud\\\\lib\\\\private\\\\legacy\\\\util.php\",\"Code\":0,\"Trace\":\"#0 C:\\\\xampp\\\\htdocs\\\\owncloud\\\\lib\\\\autoloader.php(157): OC\\\\Autoloader->isValidPath('C:\\\\\\\\xampp\\\\\\\\htdocs...')\\n#1 [internal function]: OC\\\\Autoloader->load('OC_Util')\\n#2 C:\\\\xampp\\\\htdocs\\\\owncloud\\\\lib\\\\base.php(557): spl_autoload_call('OC_Util')\\n#3 C:\\\\xampp\\\\htdocs\\\\owncloud\\\\lib\\\\base.php(973): OC::init()\\n#4 C:\\\\xampp\\\\htdocs\\\\owncloud\\\\index.php(37): require('C:\\\\\\\\xampp\\\\\\\\htdocs...')\\n#5 {main}\",\"File\":\"C:\\\\xampp\\\\htdocs\\\\owncloud\\\\lib\\\\autoloader.php\",\"Line\":133}","level":3,"time":"2016-09-23T20:52:25+00:00","method":"GET","url":"\/owncloud\/","user":"--"}
[Fri Sep 23 23:52:25.940459 2016] [:error] [pid 8032:tid 1880] [client ::1:51765] PHP Fatal error: Uncaught exception 'OCP\AutoloadNotAllowedException' with message 'Autoload path not allowed: C:\xampp\htdocs\owncloud\lib\private\legacy\response.php' in C:\xampp\htdocs\owncloud\lib\autoloader.php:133\nStack trace:\n#0 C:\xampp\htdocs\owncloud\lib\autoloader.php(157): OC\Autoloader->isValidPath('C:\\xampp\\htdocs...')\n#1 [internal function]: OC\Autoloader->load('OC_Response')\n#2 C:\xampp\htdocs\owncloud\index.php(54): spl_autoload_call('OC_Response')\n#3 {main}\n thrown in C:\xampp\htdocs\owncloud\lib\autoloader.php on line 133
``

and

``
Fatal error: Uncaught Error: Class 'OCP\AutoloadNotAllowedException' not found in C:- Portable\xampp-portable\xampp\htdocs\owncloud\lib\autoloader.php:152 Stack trace:
#0 C:- Portable\xampp-portable\xampp\htdocs\owncloud\lib\autoloader.php(172): OC\Autoloader->isValidPath('C:\- Portable\x...')
#1 [internal function]: OC\Autoloader->load('OCP\AutoloadNot...')
#2 C:- Portable\xampp-portable\xampp\htdocs\owncloud\lib\autoloader.php(152): spl_autoload_call('OCP\AutoloadNot...')
#3 C:- Portable\xampp-portable\xampp\htdocs\owncloud\lib\autoloader.php(172): OC\Autoloader->isValidPath('C:\- Portable\x...')
#4 [internal function]: OC\Autoloader->load('OC\Config')
#5 C:- Portable\xampp-portable\xampp\htdocs\owncloud\lib\base.php(133): spl_autoload_call('OC\Config')
#6 C:- Portable\xampp-portable\xampp\htdocs\owncloud\lib\base.php(506): OC::initPaths()
#7 C:- Portable\xampp-portable\xampp\htdocs\owncloud\lib\base.php(1112): OC::init()
#8 C:- Portable\xampp-portable\xampp\htdocs\owncloud\index.php(37): require_once('C in C:- Portable\xampp-portable\xampp\htdocs\owncloud\lib\autoloader.php on line 152
``

**Comment by RealRancor** [comment]
The code from https://github.com/owncloud/core/pull/14540 seems to be still there: https://github.com/owncloud/core/blob/v9.1.1/lib/private/legacy/util.php#L651

It seems oC is not able to get there to warn the user

**Comment by andypmw** [comment]
Hi @RealRancor ,
i think the problem is the PHP's shortarray syntax.

as you pointed line 651:
`$errors[] = ['error' => 'error_123', 'hint' => 'It is an error'];`

When I read the code at line 644 and line 667, the PHP array syntax:
`$errors[] = array('error' => 'error_123', 'hint' => 'It is an error');`

**Comment by RealRancor** [comment]
@andypmw Thanks for the research.

> So the older version than PHP 5.4 will face this problem. 

Doesn't look like this. The users in https://github.com/owncloud/core/issues/26207 had used PHP 5.5 where the user in https://github.com/owncloud/core/issues/24649#issuecomment-220858095 even PHP 7.0.x

**Comment by RealRancor** [comment]
Why we not just fail directly in the index.php like its done for PHP? PR here: https://github.com/owncloud/core/pull/26316

**Comment by PVince81** [comment]
Argh... yeah index.php might be easier.
The trouble with all this is that depending on what PHP version someone is running on Windows, not all source code might load properly.

**Comment by RealRancor** [comment]
https://github.com/owncloud/core/issues/26316 was merged so closing.
