### ISSUE TITLE
OC 8.2 to 9.1 share migration issue

### ISSUE THREAD

**Issue by wraythezw** [owncloud/core#26210]
Hi,
 Upgraded from 8.2.28 to 9.1.1, users & data migrated.. However shares are not working.

 oc_share shows shares item_source do not match the oc_filecache fileID. However file path is correct.

Is there a known fix? We have hundreds of shares, rebuilding them is a process we would very much like to avoid.

Running occ maintenace:repair flushes the entire oc_share table as their "items" referenced by the item_source do not exist.

**Comment by RealRancor** [comment]
Please fill out the shown issue template when creating a new issue. Currently even the basic info about your environment is missing

**Comment by PVince81** [comment]
also add these info:

did you move the data folder ? do you have a path discrepancy in oc_storages ?

**Comment by PVince81** [comment]
closing due to lack of feedback
