### ISSUE TITLE
Error: Class 'OCA\\DAV\\Connector\\Sabre\\ExceptionLoggerPlugin' not found

### ISSUE THREAD

**Issue by dergilb99** [owncloud/core#26217]
### Steps to reproduce
Having ownCloud up and running

(The file exists (/owncloud/apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php) and is not empty.)

### Expected behaviour
Rejoice: Class 'OCA\\DAV\\Connector\\Sabre\\ExceptionLoggerPlugin' was found

### Actual behaviour
Error: Class 'OCA\\DAV\\Connector\\Sabre\\ExceptionLoggerPlugin' not found

### Server configuration (wouldn't it be awesome, if you could just enter this somewhere in your profile instead of pasting it in everytime?)

**Operating system**:
Solaris Unix (Hosted by Strato)

**Web server:**
Apache 2.2

**Database:**
MySQL 5.5.48

**PHP version:**
7.0.107.0.10

**ownCloud version:**
9.1.1 (stable)

**Updated from an older ownCloud or fresh install:**
Update from 9.1.0

**Where did you install ownCloud from:**
mydubiousfilez.hu

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Activity 2.3.2 
Default encryption module 1.3.0 
Deleted files 0.9.0 
First run wizard 1.1 
Gallery 15.0.0 
Notifications 0.3.0 
Provisioning API 0.5.0 
Share Files 0.10.0 
Update notification 0.2.1 
Versions 1.3.0 
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'datadirectory' => '/mnt/web024/a2/74/12345678/htdocs/owncloud_data',
  'tempdirectory' => '/mnt/web024/a2/74/12345678/htdocs/owncloud_data/temp',
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '9.1.1.3',
  'dbname' => 'xxx',
  'dbhost' => 'rdbms.strato.de',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'log_rotate_size' => 31457280,
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'www.abc.de',
  ),
  'theme' => '',
  'loglevel' => 2,
  'overwrite.cli.url' => 'https://www.abc.de/owncloud',
  'htaccess.RewriteBase' => '/owncloud',
  'updater.secret' => 'xxx',
);
```

**Are you using external storage, if yes which one:**

No.

**Are you using encryption:**

Yes.

**Are you using an external user-backend, if yes which one:**

No.

### Client configuration
**Browser:**
Firefox 49.0.1 (64 bit)

**Operating system:**

Windows 10 Pro (64 bit)

#### ownCloud log (data/owncloud.log)
```
{"reqId":"V@gYCMCoKxsAAGscA6kAAAFI","remoteAddr":"x.x.x.x","app":"PHP","message":"Error: Class 'OCA\\DAV\\Connector\\Sabre\\ExceptionLoggerPlugin' not found at \/mnt\/web024\/a2\/74\/12345678\/htdocs\/owncloud\/remote.php#54","level":3,"time":"2016-09-25T18:33:18+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","user":"--"}
```

**Comment by PVince81** [comment]
Maybe APC caching issue ? Does restarting the web server solve it ?

**Comment by dergilb99** [comment]
> Does restarting the web server solve it ?

Would love to try, but Strato would kill me if I succeeded. Or just sue me.

**Comment by PVince81** [comment]
@dergilb99 so with all the weirdness you saw lately, is this problem still happening ?

**Comment by dergilb99** [comment]
> @dergilb99 so with all the weirdness you saw lately, is this problem still happening ?

Current log file says no, but this cloud was sleeping for a while and no clients are connected. I will setup a new user for testing purposes.

My guess would be no. If I encounter it again, I reopen this thread. It is so frustrating not knowing what's going on.

**Comment by skriesch** [comment]
That's happening again with ownCloud 9.1.3 on Ubuntu 14.04: https://central.owncloud.org/t/massive-get-status-php-requests/5852

**Comment by jamiehutber** [comment]
I'm getting the same thing with `Ubuntu 16.04.2 LTS` I did do a reset and the error is still happening.

`ownCloud version 9.1.0`

**Comment by skriesch** [comment]
There are some fixes in 9.1.4. Can you upgrade?

**Comment by jamiehutber** [comment]
I have tried upgrading with `sudo apt-get update && sudo apt-get install ownCloud` but it said I have the latest version.

**Comment by jamiehutber** [comment]
@skriesch

**Comment by skriesch** [comment]
Uase that on the command line: https://doc.owncloud.org/server/9.1/admin_manual/maintenance/upgrade.html

**Comment by hdijkema** [comment]
I've got this issue when I enable 'memcache.local'. Version 9.1.6.2.
It's a manual installation of owncloud, upgraded from 7 to 9.1 (in several steps). DB Backend: Pgsql 9.4.
I tried maintenance:repair.
Don't know what to do now.

PHP Fatal error:  Class 'OCA\\DAV\\Connector\\Sabre\\ExceptionLoggerPlugin' not found in /data/www/owncloud/remote.php on line 54

**Comment by skriesch** [comment]
Describe your upgrade process, please.

**Comment by hdijkema** [comment]
Very simple.

I started with a working owncloud 7.0.

I did following:

`su - www-data`
`cd <www-dir>`
`mv owncloud owncloud70`
`wget https://download.owncloud.org/community/owncloud-8.0.16.tar.bz2`
`tar xjf owncloud-8.0.16.tar.bz2`
`cd owncloud`
`cp ../owncloud70/config/config.php config`
`php occ upgrade`

It upgraded succesfully.

I repeated the same procedure with

owncloud-10.0.2.tar.bz2  owncloud-8.1.12.tar.bz2  owncloud-9.0.10.tar.bz2
owncloud-8.0.16.tar.bz2  owncloud-8.2.11.tar.bz2  owncloud-9.1.6.tar.bz2

`https://download.owncloud.org/community/owncloud-8.1.12.tar.bz2`
`https://download.owncloud.org/community/owncloud-8.2.11.tar.bz2`
`https://download.owncloud.org/community/owncloud-9.0.10.tar.bz2`
`https://download.owncloud.org/community/owncloud-9.1.6.tar.bz2`

They all were successfull (according to the own owncloud messages).

and finally

`https://download.owncloud.org/community/owncloud-10.0.2.tar.bz2`

Which failed in a very early stage. So I stopped upgrading after 9.1.6.

After that, I had a working owncloud configuration, that warned me about the omission of a memory caching functionality. 

When I enabled it in config.php, I got the error.

**Comment by skriesch** [comment]
Yes. A new issue is important in such a case.
