### ISSUE TITLE
Logged message about If-Match etag not matching

### ISSUE THREAD

**Issue by tonybluem** [owncloud/core#26211]
Hello,

please excuse my bad english - but I´m not a native speaker.

My ownCloud runs with no apparent problems. But I geht this log-message (Debug carddav ):

Exception: {"Message":"HTTP\/1.1 412 An If-Match header was specified, but none of the specified the ETags matched.","Exception":"Sabre\DAV\Exception\PreconditionFailed","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(454): Sabre\DAV\Server->checkPreconditions(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#2 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/carddav.php(82): Sabre\DAV\Server->exec()\n#3 \/var\/www\/owncloud\/remote.php(164): require_once('\/var\/www\/ownclo...')\n#4 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":1267,"User":"my_username"}

What should it tell me?

How can I repar this?

Server-Configuration
System: Ubuntu 16.04
Webserver: apache2
Database-Type: mysql
ownCloud-Version: 9.1.0.15

**Comment by PVince81** [comment]
How and when does it happen ? How to reproduce it ?

@guruz are you familiar with this message ? Could be a legitimate conflict situation in which the message could be ignored. If that's the case we could move that thing to a debug log.

**Comment by guruz** [comment]
This could happen if you'll upload a file during the current sync, but in the meantime (after the sync run started) another client (e.g. a colleague for a shared file or another machine of yours for a non-shared file or you youtself in the webinterface editor) already updated the same file.

**Comment by PVince81** [comment]
oh, now I see this is carddav. Could still be an expected situation.

@DeepDiver1975 do you know ?

**Comment by PVince81** [comment]
closing due to lack of feedback (no answer to my question from https://github.com/owncloud/core/issues/26211#issuecomment-249842979)
