### ISSUE TITLE
[master] LDAP app not loaded during upgrade

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26226]
Observed while running https://github.com/owncloud/core/pull/26124

The UserManager object only iterates over local users.

Debugging showed that this call https://github.com/owncloud/core/blob/master/lib/private/Updater.php#L283 doesn't load any apps because `loadApps` checks for the maintenance flag and skips loading.

@DeepDiver1975 has anything changed here recently ?

**Comment by PVince81** [comment]
Okay, easier steps:

1. Enable LDAP app
1. Increase version in version.php
1. Set a breakpoint at https://github.com/owncloud/core/blob/master/lib/private/Updater.php#L283
1. Run occ upgrade
1. Debug into `loadApps` and see that it returns directly.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 has anything changed here recently ?

nothing I can think of right away ...

**Comment by PVince81** [comment]
I'm not yet 100% sure it's that `loadApps` call. When debugging on 9.1 it seems to also skip but worked because maybe it was enabled before.

In general it does seem that `loadApps('authentication')` never does anything so it doesn't fulfil its purpose.

**Comment by PVince81** [comment]
silly me, I forgot that user_ldap is now in a separate repo...

Not critical then.

However it is still suspicious that `loadApps('authentication')` doesn't do anything, could hide potential issues.

**Comment by PVince81** [comment]
Raised https://github.com/owncloud/core/issues/26227 for an addition update check to make sure all auth apps are loaded.
