### ISSUE TITLE
Add warning on update that an app's code is missing

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26227]
When loading apps during an upgrade, first check whether the app's code is really there.

For example if user_ldap is missing but is enabled, if someone runs an upgrade the repair steps will miss the LDAP users silently.

Best would be to be more strict here and stop the upgrade early.

This happened to me while testing an update from git v9.1.1 to master and forgot to check out the user_ldap repo on master.

@DeepDiver1975 @butonic @VicDeo

**Comment by PVince81** [comment]
I suppose this kind of situation could also happen when people upgrade using tarballs and forget to also move over the installed apps code. This is especially important for authentication apps.

**Comment by PVince81** [comment]
@VicDeo can you look into this ? Goal is mostly to make sure that we're not breaking up

Let me know if you need help to setup LDAP quickly for the sake of testing. I usually use this docker https://github.com/owncloud/administration/tree/master/ldap-testing + zombies.

To reproduce the issue:

1. Checkout stable9.1 where LDAP is bundled
1. Set it up
1. Setup LDAP with some users
1. Checkout master but do NOT check out the user_ldap app (it's not bundled any more)
1. Run upgrade in verbose mode
1. Check the logs / progress and see whether LDAP users were iterated over, they are likely not

### Expected result
Before the upgrade, when loading authentication apps, notice that code is missing and abort

### Actual result
Upgrade runs but repair steps do not run on LDAP users since the app is missing.

**Comment by VicDeo** [comment]
@PVince81 Should it break for _any_ missing app or user_ldap only?

**Comment by PVince81** [comment]
I'd say for any app that is expected to be there.

**Comment by PVince81** [comment]
was added in 10.0.0
