### ISSUE TITLE
Alternative way to install owncloud deb ? (apt-get install failing)

### ISSUE THREAD

**Issue by psychicLocust** [owncloud/core#26224]
I can download package manually with wget but apt-get cannot dowload anything from download.owncloud.org. Is there an alternative for installing owncloud deb ? (download everything and use dpkg ?)

### Steps to reproduce
1. Followed instructions here (https://download.owncloud.org/download/repositories/stable/owncloud/) for Ubuntu 14.04
2. apt-get update
3. apt-get install owncloud

### Expected behaviour
apt-get install should install owncloud

### Actual behaviour

Tried everything but apt-get cannot download anything from the repo

```
Err http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/  owncloud-files 9.1.1-1.1
  Échec de la connexion [IP : 85.10.210.219 80]
Err http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/  owncloud-deps-php5 9.1.1-1.1
  Échec de la connexion [IP : 148.251.209.106 80]
Err http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/  owncloud 9.1.1-1.1
  Échec de la connexion [IP : 85.10.210.219 80]
E: Impossible de récupérer http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/./all/owncloud-files_9.1.1-1.1_all.deb  Échec de la connexion [IP : 85.10.210.219 80]

E: Impossible de récupérer http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/./all/owncloud-deps-php5_9.1.1-1.1_all.deb  Échec de la connexion [IP : 148.251.209.106 80]

E: Impossible de récupérer http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/./all/owncloud_9.1.1-1.1_all.deb  Échec de la connexion [IP : 85.10.210.219 80]
```

**Comment by pmaier1** [comment]
@jnweiger

**Comment by jnweiger** [comment]
It works for me like this:
<pre>
RUN wget -nv https://download.owncloud.org/download/repositories/ce:/9.1/Ubuntu_14.04/Release.key -O - | apt-key add -
RUN echo 'deb https://download.owncloud.org/download/repositories/ce:/9.1//Ubuntu_14.04/ /' >> /etc/apt/sources.list.d/owncloud.list
RUN apt-get -q -y update
RUN apt-get install owncloud
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  owncloud-deps-php5 owncloud-files
Suggested packages:
  php5-apcu php-apc php5-imagick php5-ldap php-smbclient libsmbclient
  owncloud-deps
The following NEW packages will be installed:
  owncloud owncloud-deps-php5 owncloud-files
0 upgraded, 3 newly installed, 0 to remove and 2 not upgraded.
Need to get 24.2 MB of archives.
After this operation, 93.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Fetched 24.2 MB in 9s (2529 kB/s)
Selecting previously unselected package owncloud-files.
(Reading database ... 14354 files and directories currently installed.)
Preparing to unpack .../owncloud-files_9.1.1-1.1_all.deb ...
Unpacking owncloud-files (9.1.1-1.1) ...
Selecting previously unselected package owncloud-deps-php5.
Preparing to unpack .../owncloud-deps-php5_9.1.1-1.1_all.deb ...
Unpacking owncloud-deps-php5 (9.1.1-1.1) ...
Selecting previously unselected package owncloud.
Preparing to unpack .../owncloud_9.1.1-1.1_all.deb ...
Unpacking owncloud (9.1.1-1.1) ...
Setting up owncloud-files (9.1.1-1.1) ...
Setting up owncloud-deps-php5 (9.1.1-1.1) ...
</pre>

**Comment by jnweiger** [comment]
Oh,
<pre>
 dig -x 85.10.210.219 | grep -C1 ANSWER
;; ANSWER SECTION:
219.210.10.85.in-addr.arpa. 85921 IN	PTR	dl-oc-s11.owncloud.com.
</pre>
You are using an owncloud.com mirror instead of an owncloud.org mirror for downloading the community version. Did you misstype the URL somwehere?

**Comment by psychicLocust** [comment]
Ok don't know what might be happening ...

**Comment by jnweiger** [comment]
Is your apt using a proxy of some sort?

**Comment by psychicLocust** [comment]
Got some kind of captive portal between server and internet. As wget is working ok and apt is able to download from standard ubuntu repositories I wasn't sure this might be the reason. Will have a look into it. Thanks again.

**Comment by jnweiger** [comment]
@psychicLocust you could ask a local admin, how they block and allow things....
