### ISSUE TITLE
'Shared word' disappears when whe set the file as favorite in files view

### ISSUE THREAD

**Issue by davitol** [owncloud/core#26241]
### Steps to reproduce
1. Share a file with a user
2. Set this file as favorite
### Expected behaviour

The file should be kept shown as shared
### Actual behaviour

'Shared word' is no longer shown. It is need to refresh the browser to get the file marked as shared again
### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.4

**ownCloud version:**

"9.2.0.1","versionstring":"9.2.0 pre alpha"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
```
### Client configuration

**browser**

Firefox

![favsh](https://cloud.githubusercontent.com/assets/10596560/18910968/b23b1e20-857a-11e6-8242-b2936f0293d5.gif)

**Comment by SergioBertolinSG** [comment]
This is fixed in https://github.com/owncloud/core/pull/26535

Following this steps https://github.com/owncloud/core/pull/26535#issuecomment-259723052

To make it work following current steps it requires https://github.com/owncloud/core/pull/25838 to be merged first.

**Comment by hodyroff** [comment]
Works for me in 10.0 Beta. What is missing to close?

**Comment by davitol** [comment]
> Works for me in 10.0 Beta. What is missing to close?

@hodyroff Just testes in beta and I can keep reproducing the issue

Browser: Firefox 52.0.1 (64-bit)
