### ISSUE TITLE
Converter::updateCard unconditionally *adds* image to user vCard

### ISSUE THREAD

**Issue by shtrom** [owncloud/core#26242]
### Steps to reproduce
1. use the user_ldap plugin (which updates the avatar from LDAP after each login: https://github.com/owncloud/user_ldap/blob/master/lib/User/User.php#L474-L483)
2. set a user image in LDAP
3. watch as the PHOTO field is repeatedly added to the user's vCard blob in `oc_cards`, until the database can hold no more (triggering doctrine/dbal#2523 in passing)

### Expected behaviour
Only one PHOTO field is present in the vCard

### Actual behaviour
Duplicate PHOTO fields keep getting added to the user's vCard

### Cause
`Converter::updateCard` unconditionally adds the given photo to the vCard, rather than replace it: https://github.com/owncloud/core/blob/a9e633db0cd04cb6288ce74c197153920a0b4665/apps/dav/lib/CardDAV/Converter.php#L93-L96 ; probably a missing `unset($vCard->PHOTO);`?

### Server configuration
**Operating system**: OpenBSD 6.0

**Web server:** apache-httpd-2.4.23

**Database:** MySQL (mariadb-server-10.0.25p0v1)

**PHP version:** php-5.6.23p0

**ownCloud version:** (see ownCloud admin page) 9.0.2

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** OpenBSD ports

**Comment by DeepDiver1975** [comment]
all prs got merged - THX

**Comment by fmkaiser** [comment]
@DeepDiver1975 sorry to re-open this, but it appears the fix was not backported to 9.0 despite being mentioned in the release notes.

We just stumbled across this issue again in 9.0.6 EE.

**Comment by DeepDiver1975** [comment]
This is true - just a sec ....

**Comment by DeepDiver1975** [comment]
@fmkaiser here we go - please test - THX

https://github.com/owncloud/core/pull/26991

**Comment by fmkaiser** [comment]
@DeepDiver1975 I applied the fix on our servers (on top of 9.0.6 EE).

Looks good so far, but I'd like to watch it for a bit longer and will come back to you on Monday.

Our case was a bit differnet than described in the initial report.
Same outcome - oc_cards.carddata grows with more and more PHOTO objects until MySQL max_allowed_packet is reached, then the user can't log in anymore.
However while we do use LDAP, we don't have any user images in it, the users that were affected uploaded their avatar in ownCloud.

My guess is that the avatar somehow still gets written to the DB on LDAP sync, so it is likely the same bug.

**Comment by fmkaiser** [comment]
@DeepDiver1975 looks good still, thanks again for the quick reaction!
