### ISSUE TITLE
Human readable url.

### ISSUE THREAD

**Issue by Dm3Ch** [owncloud/core#26253]
Have you got settings or plans for human readable url?

I understand that it is not very important think, but it is cool.

**Comment by DeepDiver1975** [comment]
Can you be a bit more precise on what you are expecting?  Thx

**Comment by Dm3Ch** [comment]
Could you at least add default nginx/apache recipes, which will remove index.php from url?

**Comment by DeepDiver1975** [comment]
Please follow the docs. Index.php can be removed.
