### ISSUE TITLE
General error: 2006 MySQL server has gone away

### ISSUE THREAD

**Issue by oscarenzo** [owncloud/core#26254]
After update from 9.0.0 -> 9.1.1, for cron system I have configure a cron job to call cron.php, all the default apps work as well, contacts, calendar, etc and share with sync clients and website, the problem is sometimes after the cron run I receive this error:

`PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)
#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(987): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/html/owncloud/lib/private/DB/Connection.php(209): Doctrine\DBAL\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)
#3 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(208): OC\DB\Connection->executeUpdate('UPDATE `*PREFIX...', Array, Array)
#4 /var/www/html/owncloud/lib/private/DB/QueryBuilder/QueryBuilder.php(141): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /var/www/html/owncloud/lib/private/Lock/DBLockingProvider.php(277): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 [intern in /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115`

Then in the owncloud log show:

`{"reqId":"wXaBAEs1CxezC31W9Dce","remoteAddr":"","app":"cron","message":"An exception occurred while executing 'UPDATE `oc_jobs` SET `reserved_at` = '0' WHERE `id` = ?' with params [\"39161\"]:\n\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away","level":4,"time":"September 29, 2016 18:30:13","method":"--","url":"--","user":"--"}
`
### Server configuration
**Operating system**:
CentOS release 6.8 (Final)

**Web server:**
Server version: Apache/2.2.15 (Unix)
Server built:   Jul 18 2016 15:24:00
Architecture:   64-bit

**Database:**
mysql  Ver 14.14 Distrib 5.5.52

**PHP version:**
PHP 5.5.38 (cli)

**ownCloud version:** (see ownCloud admin page)
9.1.1

**Updated from an older ownCloud or fresh install:**
*Updated from an older ownCloud 

**Where did you install ownCloud from:**
From zip installed

**Signing status (ownCloud 9.0 and above):**
- installed: true
  - version: 9.1.1.3
  - versionstring: 9.1.1
```

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.0
  - comments: 0.3.0
  - contacts: 1.4.0.0
  - dav: 0.2.6
  - external: 1.1
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1

**Comment by DeepDiver1975** [comment]
Maybe you can retry with an higher mysql timeout

**Comment by RealRancor** [comment]
https://doc.owncloud.org/server/9.1/admin_manual/configuration_database/linux_database_configuration.html#how-to-workaround-general-error-2006-mysql-server-has-gone-away

**Comment by oscarenzo** [comment]
thank you DeepDiver1975 and RealRancor, these was the problem, I up the value for:

wait_timeout
max_allowed_packet

Now work as well.
