### ISSUE TITLE
oC 9.0.5 and 8.2.8 missing from repositories

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#26252]
Seems the 9.0.5 and 8.2.8 releases are currently missing from:

https://download.owncloud.org/download/repositories/9.0/owncloud/
https://download.owncloud.org/download/repositories/8.2/owncloud/

9.1.1:

https://download.owncloud.org/download/repositories/9.1/owncloud/

as well as 8.1.10 are there:

https://software.opensuse.org/download/package?project=isv:ownCloud:community:8.1&package=owncloud

cc @jnweiger

**Comment by davitol** [comment]
https://download.owncloud.org/download/repositories/8.0/owncloud/

8.0.15. packages are no longer available via URL?

**Comment by RealRancor** [comment]
@davitol Everything below 8.2 is available at the OpenSUSE OBS:

https://software.opensuse.org/download/package?project=isv:ownCloud:community:8.1&package=owncloud

https://software.opensuse.org/download/package?project=isv:ownCloud:community:8.0&package=owncloud

**Comment by PVince81** [comment]
@owncloud/packaging

**Comment by bitking** [comment]
Any ETA on this?

**Comment by Trefex** [comment]
Same for me.

I'm waiting for the patches of https://github.com/owncloud/core/issues/25555 amongst others. 

Getting quite critical here.

Thank you,
T

**Comment by jnweiger** [comment]
repo-admin.py was not sufficiently robust. Fixed.
Repos updated. 

@Trefex sorry for the delay, I was not aware that the publishing had failed here. If you find more, please reopen!

**Comment by jnweiger** [comment]
8.2.8 is also on its way...

**Comment by jnweiger** [comment]
8.2.8 done. (Internal obs crashed while copying. ...)

**Comment by RealRancor** [comment]
@jnweiger 9.0.5 is there but 8.2.8 seems to be still missing

**Comment by Kawohl** [comment]
@crrodriguez do you have an idea?

**Comment by Kawohl** [comment]
for reference https://central.owncloud.org/t/problems-installing-from-linux-distribution-packages/3502

**Comment by jnweiger** [comment]
8.2.8 done. Again. I believe I was on the old server, when I did it 2 weeks ago. Sorry.

**Comment by IngoBelka** [comment]
@all
Currently I get this error message (in German) while trying to upgrade to 8.2.8:

W: Während der Überprüfung der Signatur trat ein Fehler auf. Das Repository wurde nicht aktualisiert und die vorherigen Indexdateien werden verwendet. GPG-Fehler: http://download.owncloud.org  Release: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 47AE7F72479BC94B
W: Während der Überprüfung der Signatur trat ein Fehler auf. Das Repository wurde nicht aktualisiert und die vorherigen Indexdateien werden verwendet. GPG-Fehler: http://download.owncloud.org  Release: Die folgenden Signaturen konnten nicht überprüft werden, weil ihr öffentlicher Schlüssel nicht verfügbar ist: NO_PUBKEY 47AE7F72479BC94B
W: Fehlschlag beim Holen von http://download.owncloud.org/download/repositories/8.2/xUbuntu_14.04/Release
W: Fehlschlag beim Holen von http://download.owncloud.org/download/repositories/8.2/Ubuntu_14.04/Release
W: Einige Indexdateien konnten nicht heruntergeladen werden. Sie wurden ignoriert oder alte an ihrer Stelle benutzt.

**Comment by RealRancor** [comment]
@IngoBelka Please don't hijack issues with unrelated problems. You just need to follow the instructions at the download page and import the correct signatures.

Closing here as 9.0.5 and 8.2.8 are available at the repositories.
