### ISSUE TITLE
Integrity check warning on daily master (9.2)

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26269]
Download and install daily master.
Check admin page.

As discussed in https://github.com/owncloud/updater/issues/379#issuecomment-250847431

Need to check the build scripts, maybe they're doing something slightly differently since the introduction of make.

CC @VicDeo @davitol

**Comment by PVince81** [comment]
Works for me with today's build: ownCloud 9.2.0 pre alpha (daily) Build:2016-10-06T03:01:15+00:00 10d19b2e7aaf6713111de4f1f3c82ad2b1b8b4d1

From https://download.owncloud.org/community/daily/owncloud-daily-master.tar.bz2

There are no integrity check warnings at all.

@VicDeo did you mean those warnings appear after updating ? Maybe the updater isn't clearing some files ?

**Comment by VicDeo** [comment]
@PVince81 What I mean is 
- wget a daily package 
- unpack a daily package
- # grep false core/signature.json 
```
# grep false core/signature.json 
        "lib\/composer\/bin\/doctrine-dbal": false,
        "lib\/composer\/bin\/generate_vcards": false,
        "lib\/composer\/bin\/naturalselection": false,
        "lib\/composer\/bin\/sabredav": false,
        "lib\/composer\/bin\/vobject": false,
```

nothing more

**Comment by VicDeo** [comment]
rechecking with the latest daily

**Comment by VicDeo** [comment]
@PVince81 nothing changed:
```
        "lib\/composer\/bin\/doctrine-dbal": false,
        "lib\/composer\/bin\/generate_vcards": false,
        "lib\/composer\/bin\/naturalselection": false,
        "lib\/composer\/bin\/sabredav": false,
        "lib\/composer\/bin\/vobject": false,
```

Steps
1. download https://download.owncloud.org/community/daily/owncloud-daily-master.zip
2. open `/owncloud/core/signature.json` in any editor
3. search for string __false__

**Comment by PVince81** [comment]
This PR should fix this: https://github.com/owncloud/core/pull/26445
There were stray symlinks from composer.
