### ISSUE TITLE
Clicking on updater daily advice 8.2.7 to 8.2.8, the documentation is opened in the same tab 

### ISSUE THREAD

**Issue by davitol** [owncloud/core#26260]
![screen shot 2016-09-30 at 13 45 58](https://cloud.githubusercontent.com/assets/10596560/18990778/768a608e-8714-11e6-8524-6a235cf56dfe.png)
The info should be opened in other tab as it is done in other versions

**Comment by PVince81** [comment]
fixed through https://github.com/owncloud/core/issues/26261
