### ISSUE TITLE
Update of "Overview Maintenance and Release Schedule" wiki page needed

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#26284]
There are currently two issues on https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule :
1. The overview says oC 9.2 will be released in December 2016 however the list below says the release date is in February 2017
2. EOL of oC 8.0 seems to be planned for October 2016 (so mostly now) but that branch has 8.0.16 (TBD) listed which probably won't be released in the next three weeks?

Could someone with the background knowledge update that page if needed?

**Comment by PVince81** [comment]
@DeepDiver1975 @hodyroff @dragotin what do you think ?

December 2016 or February 2017 for 9.2.0 ?

**Comment by PVince81** [comment]
cc @pmaier1

**Comment by DeepDiver1975** [comment]
> February 2017 for 9.2.0 ?

from my understanding - name it 10?

**Comment by PVince81** [comment]
it's more about the date than the version number. But yes, if it's Feb 2017 then it's 10. If it's December then it's 9.2...

**Comment by DeepDiver1975** [comment]
@hodyroff @pmaier1

**Comment by pmaier1** [comment]
I would like to see oC 10 later next year for that we have more time for improvements and are therefore able to deliver a 'groundbreaking version 10' (I'm wearing the marketing hat here). Since the release schedule actually is predetermined we don't have much choice, do we? 9.2 should be released as planned in December. Is there a possibility for a 9.3 in between?

**Comment by RealRancor** [comment]
@pmaier1 The issue here itself is more about the actual dates for oC 9.2 (not 9.3 or 10). Because the current list in:

https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

shows "December 2016" as the release date in:

https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule#overview

but "2017-02-23" as the "Public announcement" oC 9.2 in:

https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule#owncloud-920

**Comment by pmaier1** [comment]
Ok, so the plan is to do the next release in february. If this is 9.2 or 10 will be decided within the next week. As of now we stay with 9.2 as WIP version number.

**Comment by RealRancor** [comment]
So the wiki page got updated with the correct date in the mean time -> close
