### ISSUE TITLE
Installed the yum install owncloud way once, still the selection in personal's language just English in it.

### ISSUE THREAD

**Issue by meteor58** [owncloud/core#26286]
I used the chrome48 and ie11, the phenomenon is still the same, can not choose other languages, only a English.

 
### Steps to reproduce

1.Installed CentOS7.0,and selected in Chinese.
2.Installed Lnmp1.3 version(Linux+Nginx+Mysql+PHP)
3.Installed OwnCloud 9.1.1
### Expected behaviour

Tell us what should happen
the selection in personal's language just English in it.
### Actual behaviour

Tell us what happens instead
### Server configuration

**Operating system**:
CentOS7
**Web server:**
Nginx1.10
**Database:**
MySQL
**PHP version:**
PHP7
**ownCloud version:** (see ownCloud admin page)
OwnCloud9.1.1
**Updated from an older ownCloud or fresh install:**
New install
**Where did you install ownCloud from:**
yum install
**Signing status (ownCloud 9.0 and above):**
OwnCloud9.1.1

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

Login as admin
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Can you check the signing status on the admin page ?
It is likely that something is wrong with the source code (missing files) if it doesn't display all languages.

**Comment by meteor58** [comment]
How to check the signing status？

Is this:
php does not seem to be setup properly to query system environment variables. The test with getenv("PATH") only returns an empty response.
Please check the installation documentation ↗ for php configuration notes and the php configuration of your server, especially when using php-fpm.
The PHP module 'fileinfo' is missing. We strongly recommend to enable this module to get best results with mime-type detection.

How to solve it?

**Comment by meteor58** [comment]
I installed the yum install owncloud way once, still the selection in personal's language just English in it.
I think this way will not missing files...

**Comment by skriesch** [comment]
@meteor58: It seems files are missing in the source code. That isn't your mistake. You should go to the admin page and check the status there.

**Comment by meteor58** [comment]
oh,I find this reason. I remove the scandir() in php.ini and it's ok.
Thank you for your reply.

**Comment by RealRancor** [comment]
Thats why you should always have a look at your servers logfile like shown in your filled out issue template. A PHP function added to the disabled_functions of the php.ini will be logged in your logfiles.

Are there any reasons why you have added scandir() to the disabled_functions?

**Comment by meteor58** [comment]
I use an integrated environment to install application services,it is lnmp1.3(http://lnmp.org),it installed nginx1.10.0、mysql14.14 and php7.0.7.The php's default php.ini have scandir() to the disable_functions.
In my impression of the official PHP(above 5) or more began to added scandir() to the disable_functions.

**Comment by skriesch** [comment]
Can you give us the used download link?

**Comment by meteor58** [comment]
the install command:
yum install screen
screen -S lnmp
wget -c http://soft.vpser.net/lnmp/lnmp1.3-full.tar.gz && tar zxf lnmp1.3-full.tar.gz && cd lnmp1.3-full && ./install.sh lnmp

the install manual url：
http://lnmp.org/install.html

**Comment by comeback01** [comment]
Hello,

Did you find the solution?

I have the same problem with lnmp.org, I is housed on a server ARM

I deactivated scandir (), but I always English, I can not change the language.

Thank you for your help

**Comment by DeepDiver1975** [comment]
Case closed

**Comment by RealRancor** [comment]
@comeback01 Please use https://central.owncloud.org/ for such questions as this issue discussed here was caused by a broken environment / PHP configuration (as happens quite often these days where people are messing around with default configs).

**Comment by meteor58** [comment]
@comeback01 .this issue is closed.Have you check your log in Owncloud?
