### ISSUE TITLE
Upgrade from 9.0.5 to 9.1.1 - Call to undefined method OCA\DAV\AppInfo\Application::setupCron

### ISSUE THREAD

**Issue by Chalmc80** [owncloud/core#26298]
I have done a step upgrade from 9.0.2, 9.0.4 then 9.0.5 over the past week before jumping to 9.1.1 today. I am seeing the following error message -

Checked database schema update for apps
Updating database schema
Updated database
Updating <dav> ...
Fix classification for calendar objects
 Done
    0/0 [>---------------------------]   0%
An unhandled exception has been thrown:
Error: Call to undefined method OCA\DAV\AppInfo\Application::setupCron() in /var/www/html/owncloud/apps/dav/appinfo/update.php:25
Stack trace:
#0 /var/www/html/owncloud/lib/private/legacy/app.php(1192): include()
#1 /var/www/html/owncloud/lib/private/Updater.php(374): OC_App::updateApp('dav')
#2 /var/www/html/owncloud/lib/private/Updater.php(251): OC\Updater->doAppUpgrade()
#3 /var/www/html/owncloud/lib/private/Updater.php(150): OC\Updater->doUpgrade('9.1.1.3', '9.0.5.2')
#4 /var/www/html/owncloud/core/Command/Upgrade.php(290): OC\Updater->upgrade()
#5 /var/www/html/owncloud/3rdparty/symfony/console/Command/Command.php(259): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/owncloud/3rdparty/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/owncloud/3rdparty/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/owncloud/3rdparty/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/owncloud/lib/private/Console/Application.php(146): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/owncloud/console.php(94): OC\Console\Application->run()
#11 /var/www/html/owncloud/occ(11): require_once('/var/www/html/o...')

### Steps to reproduce
1. cd /tmp
2. wget https://download.owncloud.org/community/owncloud-9.1.1.tar.bz2
3. tar xjf owncloud-9.1.1.tar.bz2
4. service httpd stop
5. mv /var/www/html/owncloud /var/www/html/owncloud_9.0.5
6. cp -rp owncloud /var/www/html/owncloud
7. cp /var/www/html/owncloud_9.0.5/config/config.php /var/www/html/owncloud/config/config.php
8. ./oc_strong_perms.sh - contents below. 
9. service httpd start
10. cd /var/www/html/owncloud/
11. sudo -u apache php occ upgrade

**Contents of oc_strong_perms.sh, standard strong permissions on ownCloud documentation**
#!/bin/bash
ocpath='/var/www/html/owncloud'
htuser='apache'
htgroup='apache'
rootuser='root'

printf "Creating possible missing Directories\n"
mkdir -p $ocpath/data
mkdir -p $ocpath/assets
mkdir -p $ocpath/updater

printf "chmod Files and Directories\n"
find ${ocpath}/ -type f -print0 | xargs -0 chmod 0640
find ${ocpath}/ -type d -print0 | xargs -0 chmod 0750

printf "chown Directories\n"
chown -R ${rootuser}:${htgroup} ${ocpath}/
chown -R ${htuser}:${htgroup} ${ocpath}/apps/
chown -R ${htuser}:${htgroup} ${ocpath}/assets/
chown -R ${htuser}:${htgroup} ${ocpath}/config/
chown -R ${htuser}:${htgroup} ${ocpath}/data/
chown -R ${htuser}:${htgroup} ${ocpath}/themes/
chown -R ${htuser}:${htgroup} ${ocpath}/updater/

chmod +x ${ocpath}/occ

printf "chmod/chown .htaccess\n"
if [ -f ${ocpath}/.htaccess ]
 then
  chmod 0644 ${ocpath}/.htaccess
  chown ${rootuser}:${htgroup} ${ocpath}/.htaccess
fi
if [ -f ${ocpath}/data/.htaccess ]
 then
  chmod 0644 ${ocpath}/data/.htaccess
  chown ${rootuser}:${htgroup} ${ocpath}/data/.htaccess
fi

### Actual behaviour
Fix classification for calendar objects
 Done
    0/0 [>---------------------------]   0%
An unhandled exception has been thrown:
Error: Call to undefined method OCA\DAV\AppInfo\Application::setupCron() in /var/www/html/owncloud/apps/dav/appinfo/update.php:25
Stack trace:
#0 /var/www/html/owncloud/lib/private/legacy/app.php(1192): include()
#1 /var/www/html/owncloud/lib/private/Updater.php(374): OC_App::updateApp('dav')
#2 /var/www/html/owncloud/lib/private/Updater.php(251): OC\Updater->doAppUpgrade()
#3 /var/www/html/owncloud/lib/private/Updater.php(150): OC\Updater->doUpgrade('9.1.1.3', '9.0.5.2')
#4 /var/www/html/owncloud/core/Command/Upgrade.php(290): OC\Updater->upgrade()
#5 /var/www/html/owncloud/3rdparty/symfony/console/Command/Command.php(259): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/owncloud/3rdparty/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/owncloud/3rdparty/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/owncloud/3rdparty/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/owncloud/lib/private/Console/Application.php(146): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/owncloud/console.php(94): OC\Console\Application->run()
#11 /var/www/html/owncloud/occ(11): require_once('/var/www/html/o...')

### Server configuration
**Operating System:**
centos-release-7-2.1511.el7.centos.2.10.x86_64

**Web server:**
Server version: Apache/2.4.6 (CentOS)
Server built:   Jul 18 2016 15:30:14
Server's Module Magic Number: 20120211:24
Server loaded:  APR 1.4.8, APR-UTIL 1.5.2
Compiled using: APR 1.4.8, APR-UTIL 1.5.2
Architecture:   64-bit

**Database:**
mysql  Ver 15.1 Distrib 5.5.50-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP 7.0.11 (cli) (built: Sep 17 2016 09:23:18) ( NTS )

**ownCloud version:** (see ownCloud admin page)
9.1.1

**Updated from an older ownCloud or fresh install:**
Updated from 9.0.5

**Where did you install ownCloud from:**
.tar.bz2

**Signing status (ownCloud 9.0 and above):**
Currently in maintenance mode can't get this result

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - notifications: 0.2.3
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_ldap: 0.9.0
Disabled:
  - calendar
  - contacts
  - encryption
  - external
  - federation
  - files_antivirus
  - files_external
  - firstrunwizard
  - provisioning_api
  - user_external

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocklt6cib7bo",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/mnt\/data\/owncloud",
        "overwrite.cli.url": "http:\/\/***REMOVED SENSITIVE VALUE***\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.5.2",
        "dbname": "OWNCLOUDDB",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "no-reply",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "ldapIgnoreNamingRules": false,
        "maintenance": true,
        "loglevel": 0,
        "htaccess.RewriteBase": "\/owncloud"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

### Client configuration
Chrome / Firefox / IE

**Operating system:**
Windows 10

#### Browser log

**Comment by DeepDiver1975** [comment]
> /var/www/html/owncloud/apps/dav/appinfo/update.php:25

this file no longer exists in 9.1.x - I assume you upgrade mechanism went wrong.
You need to remove all files and folders besides config and data before dropping in the new release.

**Comment by Chalmc80** [comment]
> You need to remove all files and folders besides config and data before dropping in the new release.

I've read a few different posts and see that is usually the fix but since I am doing mv /var/www/html/owncloud /var/www/html/owncloud_9.0.5 then cp-rp /tmp/owncloud /var/www/html/owncloud it shouldn't have anything from the previous release in there?

**Comment by DeepDiver1975** [comment]
> /var/www/html/owncloud/apps/dav/appinfo/update.php

Does that file exist in your installation?
It is not part of the release ...
