### ISSUE TITLE
Shared directory access group when we add a new user in the group

### ISSUE THREAD

**Issue by BertrandEW** [owncloud/core#26290]
### Steps to reproduce
1. Install OwnCloud 9.1.1 on Debian 7.11
2. Enable server-side encryption
3. Configure Groups, Users, and Shared directories
4. Add some files on one Shared directory (named "DirectoryA") for a Group (named "GroupA")
5. Add a new user on this Group (named "GroupA")
6. The new user can see the directories on "DirectoryA", but can not see/download files
7. Even if I'm waiting the cron (in crontab), the issue is still the same.

### Expected behaviour

On step 6:, The new user can open and see the files

### Actual behaviour

On step 6.: The new user can not open and see the files.
A workaround is 
After add the user on the "GroupA":
1. Share the directory "DirectoryA" with the new user (with the same right as the "GroupA")
2. Unshare/remove the new user on the directory "DirectoryA"
3. Can open and see the files with the new user

Can we find a solution to reconfigure the Group right when we add a new user?

### Server configuration
**Operating system**:
# cat /etc/debian_version 
7.11

**Web server:**
# apachectl -V
Server version: Apache/2.2.22 (Debian)
Server built:   Jul 20 2016 05:07:11
Server's Module Magic Number: 20051115:30
Server loaded:  APR 1.4.6, APR-Util 1.4.1
Compiled using: APR 1.4.6, APR-Util 1.4.1
Architecture:   64-bit
Server MPM:     Prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APACHE_MPM_DIR="server/mpm/prefork"
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=128
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_LOCKFILE="/var/run/apache2/accept.lock"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"

**Database:**
# mysql -V
mysql  Ver 14.14 Distrib 5.5.52, for debian-linux-gnu (x86_64) using readline 6.2

**PHP version:**
# php --version
PHP 5.4.45-0+deb7u5 (cli) (built: Aug 30 2016 20:15:34) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
# cat /etc/apt/sources.list.d/owncloud.list 
deb http://download.owncloud.org/download/repositories/stable/Debian_7.0/ /
# apt-get install owncloud

**Signing status (ownCloud 9.0 and above):**
Version
ownCloud 9.1.1 (stable)
Developed by the ownCloud community, the source code is licensed under the AGPL. 

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
<<
No errors have been found.
>>

**List of activated apps:**

# sudo -u www-data php occ app:list
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.6
  - encryption: 1.3.0
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - ownbackup: 0.3.8
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - external
  - files_antivirus
  - files_external
  - mail
  - user_external
  - user_ldap

**The content of config/config.php:**

# sudo -u www-data php occ config:list system
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocn8qu3563yx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.1.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",		
		"mail_from_address": "owncloud",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "localhost",
        "mail_smtpport": "25",
        "memcache.local": "\\OC\\Memcache\\APC",
        "memcached_servers": [
            [
                "localhost",
                11211
            ],
            [
                "***REMOVED SENSITIVE VALUE***",
                11211
            ],
            [
                "***REMOVED SENSITIVE VALUE***",
                11211
            ]
        ],
        "skeletondirectory": "",
        "versions_retention_obligation": "30, auto"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...

no external storage, only local

**Are you using encryption:** yes/no

yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

### Client configuration
**Browser:**

IE, FF, GC

**Operating system:**

Windows 10, Fedora 24

### Logs

Provide later if need it

**Comment by RealRancor** [comment]
@BertrandEW A feature request / discussion for that exists at https://github.com/owncloud/core/issues/10010 so you can close this issue and continue to watch the issue there if something happens in this direction.

**Comment by PVince81** [comment]
Closing as duplicate.
Still, thanks for the thorough report
