### ISSUE TITLE
Encryption "on" and password reset makes all files unreadable again

### ISSUE THREAD

**Issue by GrimDemon** [owncloud/core#26294]
### Steps to reproduce
1. Turn on encrpytion and admin recovery key
2. Create new user account and login to that account
3. Reset password using admin account and recovery key
4. Login to user account again with new password

### Expected behaviour
I thought that after using admin recovery key all files will be available.

### Actual behaviour
We got standard information that "password was changed externaly bla bla please provide your old password bla bla bla".

### Server configuration
**Operating system:** Red Hat Enterprise Linux Server 7.2

**Web server:** Apache 2.4.6

**Database:** MariaDB 5.5.50

**PHP version:** 5.6.26

**ownCloud version:** 9.1.1

**Updated from an older ownCloud or fresh install:** 9.0

**Where did you install ownCloud from:** From owncloud.org package tar.bz2

**Signing status (ownCloud 9.0 and above):** No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.6
  - encryption: 1.3.0
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - external
  - files_antivirus
  - files_external
  - passwordpolicy
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocguc5ugdk7a",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.125.12.16",
            "10.125.12.17",
            "10.125.11.16",
            "10.125.11.17",
            "v-csb-p-ocapp1.xxx.pl",
            "v-csb-p-ocapp2.xxx.pl",
            "cloud.xxx.pl",
            "91.233.18.91"
        ],
        "datadirectory": "\/var\/www\/data",
        "overwrite.cli.url": "https:\/\/cloud.xxx.pl",
        "dbtype": "mysql",
        "version": "9.1.1.3",
        "dbname": "owncloud",
        "dbhost": "10.125.13.16",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Warsaw",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "10.125.13.16",
            "port": 6379
        },
        "theme": "redesigned",
        "mail_smtpmode": "smtp",
        "mail_from_address": "cloud",
        "mail_domain": "xxx.pl",
        "mail_smtphost": "10.125.12.26",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "htaccess.RewriteBase": "\/",
        "proxy": "10.125.3.2:8080",
        "singleuser": false
    }
}

**Are you using external storage, if yes which one:** none

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** Firefox 49 / Edge 25

**Operating system:** Windows 10

#### Web server error log
nothing interesting

#### ownCloud log (data/owncloud.log)
{"reqId":"V-dfWPizIaoDTnu1nHicdAAAAAE","remoteAddr":"10.110.48.7","app":"no app in context","message":"Could not decrypt the private key from user \"kornik\"\" during login. Assume password change on the user back-end. Error message: Bad Signature","level":2,"time":"2016-10-07T10:39:53+02:00","method":"POST","url":"\/login","user":"kornik"}
{"reqId":"V-df4M-bFMIDmNVXSEmW0QAAAAM","remoteAddr":"10.110.48.7","app":"core","message":"Login failed: 'kornik' (Remote IP: '10.110.48.7')","level":2,"time":"2016-10-07T10:42:09+02:00","method":"POST","url":"\/login","user":"--"}
{"reqId":"V-dgENPicGhEW4RSjOrT8gAAAAg","remoteAddr":"10.110.48.7","app":"core","message":"Login failed: 'kornik' (Remote IP: '10.110.48.7')","level":2,"time":"2016-10-07T10:42:57+02:00","method":"POST","url":"\/login?user=kornik","user":"--"}
{"reqId":"V-dgK8-bFMIDmNVXSEmW0wAAAAM","remoteAddr":"10.110.48.7","app":"no app in context","message":"Could not decrypt the private key from user \"kornik\"\" during login. Assume password change on the user back-end. Error message: Bad Signature","level":2,"time":"2016-10-07T10:43:25+02:00","method":"POST","url":"\/login?user=kornik","user":"kornik"}
{"reqId":"V-dhZaVAQHoe3uWDJCXw1gAAAAo","remoteAddr":"213.5.212.157","app":"no app in context","message":"Could not decrypt the private key from user \"jolka\"\" during login. Assume password change on the user back-end. Error message: Bad Signature","level":2,"time":"2016-10-07T10:48:39+02:00","method":"POST","url":"\/login","user":"jolka"}

#### Browser log
doesnt matter here

**Comment by GrimDemon** [comment]
Bug described in #16388 doesn't helped me :/

**Comment by PVince81** [comment]
@GrimDemon after creating the user's account, the user needs to opt-in to allow recovery key in the personal page. Did you do that ?

**Comment by GrimDemon** [comment]
Seriously? I'm a moron, I was pretty sure that this option wasn't there earlier and instead user could create his own recovery key. OK, now it works. Jesus :| Thx!

**Comment by PVince81** [comment]
Happens :smile:
