### ISSUE TITLE
windows path 260 char

### ISSUE THREAD

**Issue by LZMA** [owncloud/core#2630]
If the file path exceeds 260 characters, the client crashes
Owncloud server 5
Client 1.2
So windows7 IIS
Php 5.3
Mysql 5.2

**Comment by clementhk** [comment]
https://msdn.microsoft.com/en-us/library/aa365247(v=VS.85).aspx

> Maximum Path Length Limitation
> In the Windows API (with some exceptions discussed in the following paragraphs), the maximum length for a path is MAX_PATH, which is defined as 260 characters. A local path is structured in the following order: drive letter, colon, backslash, name components separated by backslashes, and a terminating null character. For example, the maximum path on drive D is "D:\some 256-character path string<NUL>" where "<NUL>" represents the invisible terminating null character for the current system codepage. (The characters < > are used here for visual clarity and cannot be part of a valid path string.)
> Note  File I/O functions in the Windows API convert "/" to "\" as part of converting the name to an NT-style name, except when using the "\\?\" prefix as detailed in the following sections.
> The Windows API has many functions that also have Unicode versions to permit an extended-length path for a maximum total path length of 32,767 characters. This type of path is composed of components separated by backslashes, each up to the value returned in the lpMaximumComponentLength parameter of the GetVolumeInformation function (this value is commonly 255 characters). To specify an extended-length path, use the "\\?\" prefix. For example, "\\?\D:\very long path".

**Comment by clementhk** [comment]
So all we need to do is just use `\?\` prefix, I think.
