### ISSUE TITLE
Client continues to download files even after delete on server

### ISSUE THREAD

**Issue by Croydon** [owncloud/core#26302]
### Steps to reproduce
1. Have many, many files on the server which are not yet synced to client1
2. Start client1, as expected the client is downloading the new files
3. Start client2 on a second computer which already has the files, which are new to client1 (in my case, they are coming from this computer)
4. Delete the new files on the second computer, client2 will delete them now on the server
5. The files new to client1 are succesfull deleted on the server
6. client1 is continuing to download the "new" files, which should be already deleted
### Expected behaviour

After deleting the files from the server, all clients should stop downloading these files and if neccessary delete them locally as always.
### Actual behaviour

The client is continuing downloading the deleted files from the server. This can be a huge deal when it is about huge files or many, many, many files (#25115).
### Server configuration

**Operating system**: Win7, 64-bit

**Web server:** Ubuntu 16.04, Apache

**Database:** MariaDB 10.2

**PHP version:** PHP 7.0

**ownCloud version:** 9.1.0

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** download.owncloud.org repository

**Signing status (ownCloud 9.0 and above):** _What does this mean?_

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

>Enabled:
  - activity: 2.3.2
  - calendar: 1.4.0
  - comments: 0.3.0
  - contacts: 1.4.0.0
  - dav: 0.2.5
  - encryption: 1.3.0
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - external
  - files_antivirus
  - news
  - ownnote
  - user_external
  - user_ldap


```

**Stuff from config/config.php which could matter:**

>  'datadirectory' => '/var/www/owncloud/data',
>   'dbtype' => 'mysql',
>   'version' => '9.1.0.15',
>   'logtimezone' => 'Europe/Berlin',
>   'installed' => true,
>   'asset-pipeline.enabled' => false,
>   'filelocking.enabled' => true,
>   'memcache.local' => '\OC\Memcache\Redis',
>   'memcache.distributed' => '\OC\Memcache\Redis',
>   'memcache.locking' => '\OC\Memcache\Redis',
>   'redis' => 
>   array (
>     'host' => 'localhost',
>     'port' => 6379,
>     'timeout' => 0,
>   ),
>   'share_folder' => '/shared/',
>   'loglevel' => 3,
>   'maintenance' => false,
>   'forcessl' => true,
>   'forceSSLforSubdomains' => true,
>   'updatechecker' => false,
>   'htaccess.RewriteBase' => '/',

```

**Are you using external storage, if yes which one:** none

**Are you using encryption:** yes

```

**Comment by PVince81** [comment]
> client1 is continuing to download the "new" files, which should be already deleted

This is probably because of the way how the client works, phase-wise.
From what I remember it first does the "discovery" phase to find out what to sync.
Then after that it enters the "sync" phase where it syncs the list of whatever it has prepared to sync.

Maybe in your use case it is still in the "sync" phase and continues to process the current list.
However it will at some point notice that the file it wanted to download is deleted, so it would abort and restart the discovery phase, which will then prepare a new sync list which doesn't contain the deleted files.

I think this is by design.

@guruz @ogoffart @dragotin any comments ?

**Comment by guruz** [comment]
The description by @PVince81 is correct. At the moment this is by design.

As the sync goes on the client1 should see each file on download as 404 and just ignore them.

**Comment by Croydon** [comment]
@guruz But the client didn't get any 404, it just behaved like the files would still be there (I checked it also via browser in the web ui, they were definitely gone). It did go on for several minutes. Thanks to a server update my client lost then connection and the sync queue was cleaned, but I'm pretty sure the client would have just continued downloading all files. These files were many tiny ones, so it's also not just the recent file or something.

**Comment by PVince81** [comment]
Are you sure client2 was already finished deleting the files ?
Was it a deletion of files or folders ? You might be able to find out by looking at the access log and see whether the "DELETE" method from client2 was sent for every file individually or for the whole folder.

But in any case that shouldn't make a difference. If the deletion was not finished, then it is likely that client2 would still have download access to the files. Deletion can take some time because files will be moved to the trashbin.

**Comment by guruz** [comment]
The current downloads (3-6 in parallel) yes.

The ones he did not start yet should get a 404 when started.

Did you see otherwise?

**Comment by hodyroff** [comment]
Please reopen when you provide the needed information.

**Comment by Croydon** [comment]
Sorry, slipped through my notification spam.

> Was it a deletion of files or folders ?

Of folders.

> Maybe in your use case it is still in the "sync" phase and continues to process the current list.
However it will at some point notice that the file it wanted to download is deleted, so it would abort and restart the discovery phase, which will then prepare a new sync list which doesn't contain the deleted files.
I think this is by design.

Imo it shouldn't just finish the current list but notice the file deletion at some point. In my case (and for sure others) this would mean a major performance boost. (again especially in combination with many, many small files (or just gigant files on the other hand..)).

> But in any case that shouldn't make a difference. If the deletion was not finished, then it is likely that client2 would still have download access to the files. 

(You meant client1). Client2 has finishing deleting the files and as I said I also could saw them deleted via the website UI. Files were gone.

>The current downloads (3-6 in parallel) yes.
The ones he did not start yet should get a 404 when started.
Did you see otherwise?

Yes, all of these files are very small, just a few bytes till kilobytes. So in this time client1 definitely downloaded more than 6 files.

@hodyroff I can't reopen by myself 😄

**Comment by PVince81** [comment]
This is a client issue, raised in the client repo https://github.com/owncloud/client/issues/5411

**Comment by ckamm** [comment]
Even with the phase-wise operation of the client I don't see how this would happen. Yes, the client will attempt to download the deleted files, but should receive a 404 on each deleted file and proceed to the next one. If I read @Croydon correctly, he says his client was somehow able to download files that had been deleted from the server - which should not be possible.
