### ISSUE TITLE
Exception: Updates between multiple major versions and downgrades are unsupported.

### ISSUE THREAD

**Issue by sinasafarnezhadian** [owncloud/core#26305]
Exception: Updates between multiple major versions and downgrades are unsupported.

**Comment by RealRancor** [comment]
@sinasafarnezhadian Please close here. This is not a support forums (especially not when providing that few info).

To fix your issue itself read this FAQ: https://central.owncloud.org/t/updates-between-multiple-major-versions-and-downgrades-are-unsupported/815

and ask for support there.
