### ISSUE TITLE
Upgrade from 9.1.0 to 9.1.1 fails if LDAP connection is lost

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#26300]
### Steps to reproduce
1. Setup an ownCloud 9.1.0 with a working LDAP connection
2. Make sure LDAP users are loaded in ownCloud normally
3. Drop the LDAP server so ownCloud can't connect to it
4. Upgrade to 9.1.1
### Expected behaviour

I guess one of the following:
- LDAP (and any authention app) is disabled before the upgrade so the upgrade can continue normally (probably not a good solution)
- The upgrade checks the connectivity to each of the authentication mechanism before starting. This might require some methods to check the connections in any authentication app.
### Actual behaviour

Upgrade fails updating LDAP

```
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checking whether the database schema for <dav> can be updated (this can take a long time depending on the database size)
 Done                                                        
 7/7 [============================] 100%                     
Checked database schema update for apps
Updating database schema
Updated database
Updating <dav> ...
Fix classification for calendar objects
 Done                                                        
    0/0 [>---------------------------]   0%                  
Updated <dav> to 0.2.6
OC\ServerNotAvailableException: Lost connection to LDAP server.
Update failed
Maintenance mode is kept active
Reset log level
```
### Server configuration

**Operating system**: ubuntu 14.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 5.5.9

**ownCloud version:** 9.1.1

**Updated from an older ownCloud or fresh install:** 9.1.0
### Notes
- This scenario will likely fail in any previous versions.
- Next run seems to work with the LDAP connection active (although I'm not sure if there is any "hidden" consecuence such as app migration not performed. Next run log:
  
  ```
  ownCloud or one of the apps require upgrade - only a limited number of commands are available
  You may use your browser or the occ upgrade command to do the upgrade
  Set log level to debug
  Checking whether the database schema can be updated (this can take a long time depending on the database size)
  Checked database schema update
  Checking updates of apps
  Checked database schema update for apps
  Updating database schema
  Updated database
  Drop old database tables
  Done                                            
  28/28 [============================] 100%       
  Remove old (< 9.0) calendar/contact shares
  Done                                            
  4/4 [============================] 100%         
  Fix permissions so avatars can be stored again
  Done                                            
  2/2 [============================] 100%         
  Repair unmerged shares
  Done                                            
  1002/1002 [============================] 100%   
  Update successful
  Maintenance mode is kept active
  Reset log level
  ```

@PVince81 @DeepDiver1975 setting to 9.2 for now.

**Comment by DeepDiver1975** [comment]
This will be solved with the user account table - see https://github.com/owncloud/core/issues/23558

**Comment by jvillafanez** [comment]
Just one thing that comes into my mind: if we wan't to keep the files in their respective backends (sftp, dropbox, smb, etc), why do we want to bring and sync user information into ownCloud?

If we require pagination and the LDAP or whatever doesn't support, then you have bad luck: this is the best we can do, if you need more try another server which support pagination. Bring all the accounts will also bring issues we're already facing, specially with account synchronization between ownCloud and LDAP. It's important to notice that we support installations with more than 100k of users, and all of that will be duplicated in ownCloud.

For LDAP pagination, we should research Virtual List View Controls, which seems to be supported by some of the LDAP providers (checked OpenDS, AD and NetIQ). Some more: http://blog.dzhuvinov.com/?p=956

**Comment by PVince81** [comment]
Needs to be retested with 9.1.5 RC1 and also with 10.0 with the account table.

@davitol assigning to you

**Comment by PVince81** [comment]
@davitol ping

**Comment by PVince81** [comment]
@davitol please verify

**Comment by PVince81** [comment]
moving to QA milestone then to be tested with 10.0.3

**Comment by PVince81** [comment]
I'm closing this issue then. If QA finds that it's still broken in 10, please put back to development milestone
