### ISSUE TITLE
Closing photo preview reloads file list

### ISSUE THREAD

**Issue by qwertymodo** [owncloud/core#26318]
### Steps to reproduce
1. Open the WebGUI and navigate to a folder containing enough photos to require scrolling
2. Scroll down a ways and click on a photo to view the full-screen preview
3. Close the photo preview
### Expected behaviour

The page should just return to the file list at the same position it was when you clicked the photo, and should still have the photo thumbnails loaded so it responds quickly.
### Actual behaviour

The entire folder list reloads, scrolled back to the beginning of the list.  This requires not only scrolling back to where you were, but reloading all of the photo thumbnails as you go.
### Server configuration

**Operating system:** FreeNAS (custom BSD jail, not the default plugin)

**Web server:** nginx

**Database:** MySQL

**PHP version:** 5.6.19

**ownCloud version:** (see ownCloud admin page) 9.1.0 stable

**Updated from an older ownCloud or fresh install:** upgrade

**Where did you install ownCloud from:** https://download.owncloud.org/community/owncloud-9.1.0.tar.bz2

**Signing status:** No errors have been found

**List of activated apps:**
Enabled:
- activity: 2.3.2
- comments: 0.3.0
- dav: 0.2.5
- federatedfilesharing: 0.3.0
- federation: 0.1.0
- files: 1.5.1
- files_external: 0.6.0
- files_pdfviewer: 0.8.1
- files_sharing: 0.10.0
- files_texteditor: 2.1
- files_trashbin: 0.9.0
- files_versions: 1.3.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 15.0.0
- notifications: 0.3.0
- provisioning_api: 0.5.0
- systemtags: 0.3.0
- templateeditor: 0.1
- updatenotification: 0.2.1
  Disabled:
- encryption
- external
- files_antivirus
- files_mv
- user_external
- user_ldap

**The content of config/config.php:**
{
    "system": {
        "enable_previews": true,
        "preview_libreoffice_path": "\/usr\/local\/bin\/libreoffice",
        "memcache.local": "\OC\Memcache\APCu",
        "memcache.locking": "\OC\Memcache\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "instanceid": "ocrnlx64nnw4",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "**_localip**_",
            "**_public DNS hostname**_"
        ],
        "datadirectory": "\/mnt\/owncloud",
        "overwrite.cli.url": "http:\/\/**_localip**_",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost:\/var\/run\/mysql\/mysql.sock",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "loglevel": 0,
        "htaccess.RewriteBase": "\/"
    }
}

**Are you using external storage, if yes which one:** Yes, local

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No
### Client configuration

**Browser:** Chrome/Firefox

**Operating system:** Windows 10 x64
### Logs

N/A

**Comment by PVince81** [comment]
Photo preview is from the gallery app. Need to investigate.

**Comment by michaelstingl** [comment]
@UnitedMarsupials reported this for `files_videoplayer` too:

> ### Steps to reproduce
> 1. Open an oC folder with lots of media files.
> 2. Scroll down to the bottom half of the list.
> 3. Click on a video-file to view it.
> 4. Close the video.
> 
> ### Expected behaviour
> The list of files should remain just as it was before you clicked on the video.
> 
> ### Actual behaviour
> The list of files jumps back all the way up to the beginning, making it difficult to resume one's work.
> 
> ### Server configuration
> 
> ### Client
> I observed this with Firefox. Maybe, other browsers don't do that...

I'm adding this here because it looks like a issue with the foundation for the preview apps. @UnitedMarsupials please provide information about your setup.

**Comment by UnitedMarsupials** [comment]
> @UnitedMarsupials please provide information about your setup.

I'd be happy to answer any follow-up questions, but I think, I already provided all the relevant details... No?

**Comment by michaelstingl** [comment]
@UnitedMarsupials This is the information that is normally needed to investigate server issues:
https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

```
### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**
```

**Comment by UnitedMarsupials** [comment]
> This is the information that is normally needed to investigate server issues

But this is not a "server" issue -- this is, obviously, something about the JavaScript-code and/or the CSS.

**ownCloud version:**
9.1.4 stable
**Updated from an older ownCloud or fresh install:**
Updated from 9.1.2 (I think)
**Where did you install ownCloud from:**
[FreeBSD port](http://freshports.net/www/owncloud)
**Signing status (ownCloud 9.0 and above):**
All clear.

**Comment by qwertymodo** [comment]
Yeah, I get that you guys always want relevant config to reproduce properly, but this isn't a bug so much as normal functional behavior that should be reconsidered and reworked. It's been this way for awhile, completely independent of server configuration or client browser.

**Comment by PVince81** [comment]
@noveens would you be able to debug this ? Even if you can't fix it, at least find some clues what the JS code is doing / where the reloading is happening.

**Comment by noveens** [comment]
@PVince81 ,
Sure would love to.

**Comment by noveens** [comment]
PR Here:
https://github.com/owncloud/gallery/pull/716

@PVince81

**Comment by UnitedMarsupials** [comment]
> PR Here: owncloud/gallery#716

I applied the diff by hand-editing the `js/slideshowcontrols.js` and the list of files is no longer reset after viewing an _image_.

Unfortunately, it is still reset after watching a _video_.

**Comment by noveens** [comment]
My bad, didn't see about the video part.
Will update the PR soon.

**Comment by UnitedMarsupials** [comment]
> My bad, didn't see about the video part. Will update the PR soon.

What about other file-types -- such as PDFs? Is each one handled separately?..

**Comment by noveens** [comment]
yes, this was a bug in the gallery app, so I suppose we shoud open a ticket at the respective apps and not core.

**Comment by michaelstingl** [comment]
Sorry, I was wrong with my guess. Here you can find the individual repositories:

- https://github.com/owncloud/files_videoplayer
- https://github.com/owncloud/files_pdfviewer
- https://github.com/owncloud/files_texteditor
- https://github.com/owncloud/ (all other repos)

Each has own issues to report and fix bugs.

**Comment by PVince81** [comment]
Please wait before fixing the other ones, we first need to agree on the gallery fix. It's not as easy because of the URL / history.

Let's finish the gallery fix first and when it's merged use it as an example for the other apps too.

**Comment by PVince81** [comment]
I think we should fix https://github.com/owncloud/core/issues/15520 instead, it will prevent reloading the file list when the URL is changed by the browser back button but the path argument did not change.

**Comment by noveens** [comment]
@PVince81 ,
Will fixing #15520 solve this, since here we are simply calling window.history.back( ) which IMO depends on the browser and will force a refresh?

**Comment by noveens** [comment]
Everyone, please have a look and add your opinions:
https://github.com/owncloud/gallery/pull/716#issuecomment-283147823

**Comment by PVince81** [comment]
> Will fixing #15520 solve this, since here we are simply calling window.history.back( ) which IMO depends on the browser and will force a refresh?

Yes it will. `window.history.back()` doesn't always force a page refresh. The history API allows for changing the URL through Javascript and catching events (onpopstate) when the URL changes. The bug from https://github.com/owncloud/core/issues/15520 is that even though we catch the event, we still refresh the file list (not the whole page) because we didn't check whether the file list path changed or not.

**Comment by noveens** [comment]
@PVince81 ,
My bad, I didn't know that window.history.back() didn't force a refresh.
I'll fix the bugs.

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/27282 should fix this
