### ISSUE TITLE
OCC not functioning on shared host

### ISSUE THREAD

**Issue by boydhako** [owncloud/core#26314]
I'm on Bluehost and running OCC in the stated means doesn't work. The PHP predefined constant for __DIR__ isn't "found" since I'm unable to execute the script using the account that the web server operates under.

### Server configuration
**Operating system**:
 Some form of linux

Linux <host redacted> 3.12.50-39.ELK6.x86_64 #1 SMP Mon Nov 2 03:10:26 CST 2015 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
Apache I think. It's locked to where I can't get the info.

**Database:**
mysql

**PHP version:**
PHP 5.2.17 (cgi-fcgi) (built: Oct  2 2013 09:23:52)

**ownCloud version:** (see ownCloud admin page)
all versions... I've been updating from 8.1 to 9.2 and it always happens.

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**
Initial install was with the web installer. Web installer didn't work for Major upgrades, so I had to manually upgrade via tar

**Signing status (ownCloud 9.0 and above):**

Integrity checker has been disabled. Integrity cannot be verified.

Here's the output I get

```
X-Powered-By: PHP/5.2.17
Content-type: text/html

<br />
<b>Warning</b>:  require_once(__DIR__/console.php) [<a href='function.require-once'>function.require-once</a>]: failed to open stream: No such file or directory in <b>/home2/boydhana/public_html/cloud.boydhanaleiako.me/occ</b> on line <b>11</b><br />
<br />
<b>Fatal error</b>:  require_once() [<a href='function.require'>function.require</a>]: Failed opening required '__DIR__/console.php' (include_path='.:/usr/share/pear:/usr/share/php') in <b>/home2/boydhana/public_html/cloud.boydhanaleiako.me/occ</b> on line <b>11</b><br />
```

**Comment by RealRancor** [comment]
@boydhako 
> X-Powered-By: PHP/5.2.17

ownCloud won't run with such an outdated version of PHP (oC needs PHP 5.4+).

**Comment by boydhako** [comment]
@RealRancor 
Derp... my bad. Bluehost has multiple versions of php running. I used php 5.6 and got the following when trying to run the OCC list command.
PHP 5.6.24 (cgi-fcgi) (built: Jul 22 2016 14:21:17)

```
Set-Cookie: oc2df3dadbfa=67i1jbmn0ce8qirnloee6238s7; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=awzkZXfzWJyedrnUzGFDT2VmdIdNvt8NlvCVcpCciRfmuBN09tx9JkZNs7MOskrPLgVcJhW7Z25fqREylP%2Fts0fDfBwOqR7XIc%2BjCiln5H0dqo%2FYtLTgZwLFHSZn5y0Y; path=/; httponly
Content-Security-Policy:default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Content-type: text/html; charset=UTF-8

This script can be run from the command line only

```
<img width="971" alt="screen shot 2016-10-08 at 04 33 01" src="https://cloud.githubusercontent.com/assets/1613821/19213781/5e73b5de-8d10-11e6-8959-7764d9c7054a.png">

Note: I also used `php-cli occ list` and got the following.

```
Warning: require_once(__DIR__/console.php): failed to open stream: No such file or directory in /home2/boydhana/public_html/cloud.boydhanaleiako.me/occ on line 11

Fatal error: require_once(): Failed opening required '__DIR__/console.php' (include_path='.:/usr/share/pear:/usr/share/php') in /home2/boydhana/public_html/cloud.boydhanaleiako.me/occ on line 11

```

**Comment by RealRancor** [comment]
Hi,

as written:

> Overall this is a configuration issue on your / your hosters side so please close here. If you need further support see https://owncloud.org/support/ where to get it.

The issue tracker is unfortunately not the correct place to discuss this issue.

**Comment by boydhako** [comment]
meh...

https://central.owncloud.org/t/unable-to-execute-occ-on-shared-host/2907
