### ISSUE TITLE
Use old PHP syntax in index.php (PHP 5.4/PHP 5.6)

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#26317]
Wile doing https://github.com/owncloud/core/pull/26316 i've noticed that the index.php uses the new short syntax introduced with PHP 5.4:

https://github.com/owncloud/core/blob/v9.1.1/index.php#L42

This means users won't see the message in https://github.com/owncloud/core/blob/v9.1.1/index.php#L29 as soon as they are using a PHP version lower then PHP 5.4...

I'm also not quite sure if there are any special syntax in the index.php concerning PHP 5.6 in master?

**Comment by PVince81** [comment]
I don't see any, so should be fine as long as it doesn't reach the `try` block and the static class usage which are likely to load the other files.

**Comment by RealRancor** [comment]
Try to load the index.php on PHP 5.3 and it mostly will fail to parse the file itself
