### ISSUE TITLE
Why is my owncloud scattered across my system ?

### ISSUE THREAD

**Issue by elouet** [owncloud/core#26326]
I come from a version 7.0 debian install and trying to upgrade manually to 9.1. 

This is a painful process. I am now stuck in maintenance mode, with lots of questions, left wondering how such a mess is possible. I currently have version 8.0 and 8.1 installed in /var/www with a symbolic link /var/www/owncloud pointing to various versions as I upgrade 7.0 => 8.0 => 8.1 => 8.2 => 9.0 => 9.1
I use tarballs that I unzip under /var/www.

I still, however, have /usr/share/owncloud and /var/lib/owncloud and /etc/owncloud (supposedly) left over from previous package-based  installed, and this seems to interfere big time with the tarballs.

What do I need to do then ? Uninstall packages ? I'm really scared this is only going to break more things.

If not for the painful upgrades, Owncloud really rocks, thanks all for this nice bit of software !

**Comment by elouet** [comment]
OK, got it (partially) : turns out that this page : https://owncloud.org/blog/upgrading-owncloud-on-debian-stable-to-official-packages/ 
partially documents the process, but some extra steps are required (removing some left-over file in /etc/apache2/conf.d/)... 
Now I'm stuck with missing dependencies...

**Comment by RealRancor** [comment]
@elouet Please note this is a bugtracker not a support forums. Please close here and see https://owncloud.org/support/ for resources where to ask such support questions.
