### ISSUE TITLE
CSRF Token Leakage Through HTTP GET

### ISSUE THREAD

**Issue by wioxjk** [owncloud/core#26336]
This is accessible via /owncloud/core/js/sharedialogmailview.js

`<form id="emailPrivateLink" class="emailPrivateLinkForm">' +
            '    <input id="email" class="emailField" value="{{email}}" placeholder="{{mailPrivatePlaceholder}}" type="text">' +
            '    <input id="emailButton" class="emailButton" type="submit" value="{{mailButtonText}}">' +
            '</form>`

Found it using the Detectify search engine

**Comment by PVince81** [comment]
This is only a JS template stored inside a JS string. AFAIK there is no logic that would inject the CSRF token there. Can you post a screenshot of the DOM inspector showing a render of the form with the token inside ?

**Comment by PVince81** [comment]
cc @Peter-Prochaska

**Comment by PVince81** [comment]
Closing due to lack of feedback, I don't think there is an issue here.

**Comment by wioxjk** [comment]
Hi,

Sorry for the delay. I was using Detectify and it found this when scanning my site.

This seems to be fixed after the latest patch from Owncloud. I am not getting this "error" anymore.
