### ISSUE TITLE
owncloud 9.1.0 - Kalender und Aufgaben keine Daten

### ISSUE THREAD

**Issue by blueskyfeeling** [owncloud/core#26338]
Hallo,

ich habe ein Problem mit dem Aufruf meiner Daten aus dem owncloud-Kalender und den owncloud-Aufgaben. Zuhause auf dem PC funktioniert der Aufruf einwandfrei.

Im Geschäft kann ich Dateien, Mails, Kontakte anschauen, aber eben keine Kalender- und Aufgabeneinträge. Das sehe ich ständig einen bewegenden Kreis ohne Resultate.

Wie kann das sein? Ich verwende geschäftlich den Internet Explorer 11.

**Comment by DeepDiver1975** [comment]
> Ich verwende geschäftlich den Internet Explorer 11.

Looks like calendar is not supporting IE11 - see https://github.com/owncloud/calendar#supported-browsers
