### ISSUE TITLE
DAV auth backend registered twice in DAV v2

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26351]
Observed on master (89078909e95bc62a746711e6b161efa8dbefd4a3) with a debugger into lib/composer/sabre/dav/lib/DAV/Auth/Plugin.php `beforeMethod`:

```
  $this->backends                = (array[4]);
    $this->backends[0]           = (object|OCA\DAV\Connector\Sabre\Auth[7])+;
    $this->backends[1]           = (object|OCA\DAV\DAV\PublicAuth[1])+;
    $this->backends[2]           = (object|OCA\Federation\DAV\FedAuth[3])+;
    $this->backends[3]           = (object|OCA\DAV\Connector\Sabre\Auth[7])+;
```

Not sure if this can have side effects apart from checking the auth twice.

cc @DeepDiver1975

**Comment by PVince81** [comment]
ewwww, three "WWW-Authenticate" headers:
```
  % curl -D - -X PROPFIND http://localhost/owncloud/remote.php/dav/files/admin/
HTTP/1.1 401 Unauthorized
Date: Wed, 12 Oct 2016 09:16:39 GMT
Server: Apache
X-Powered-By: PHP/5.6.26
Set-Cookie: oc2d13a6a068=4em2kcitqtrb0kiem0i0ao9v60odfbmll2t0pdvnkh6veqch3o91; path=/owncloud; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=U77Dnd9s7ODpnSz1mBhqNdtIgDv%2BRfxAJpOl5ZPy0D%2BWSav1arbbAa00Db5ixq1EQHLNnRknEVNKj%2FS4s9B3modzQdsZL4qTMPUiZl3z3ejcsAVuMra80%2B0SWh4PnZIc; path=/owncloud; httponly
Content-Security-Policy: default-src 'none';
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
WWW-Authenticate: Basic realm="ownCloud"
WWW-Authenticate: Basic realm="ownCloud"
WWW-Authenticate: Basic realm="ownCloud"
Content-Length: 558
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured</s:message>
</d:error>
```

**Comment by PVince81** [comment]
This results in a weird compoung error message

**Comment by PVince81** [comment]
The old endpoint only has one.

On stable9 and stable9.1, there are two such headers instead of four. And no duplicate backends.
```
    $this->backends[0]           = (object|OCA\Federation\DAV\FedAuth[3])+;
    $this->backends[1]           = (object|OCA\DAV\Connector\Sabre\Auth[7])+;
```

So this is a regression from stable9.1

**Comment by PVince81** [comment]
introduced in 83083488815e51a0e46cf2dd5a6a23f6e352f66a from @tcitworld for calendar public sharing: https://github.com/owncloud/core/pull/25351

@tcitworld any reason why you are re-registering the auth backend at the beginning here: https://github.com/owncloud/core/blob/master/apps/dav/lib/Server.php#L79 ? Needed to make public access work ?

That one was purposefully registered as the last one, see https://github.com/owncloud/core/blob/master/apps/dav/lib/Server.php#L87.

**Comment by tcitworld** [comment]
Hmm, I think that's more an oversight than an intended thing when @DeepDiver1975 introduced the PublicAuth backend.

**Comment by PVince81** [comment]
Would it be possible to remove it again and test whether public calendar share still works ?

**Comment by tcitworld** [comment]
Works. See https://github.com/owncloud/core/pull/26353

**Comment by RealRancor** [comment]
> ewwww, three "WWW-Authenticate" headers:

On stable9 there are two headers: So its not directly caused by the calendar sharing implementation: https://github.com/owncloud/core/issues/26412
