### ISSUE TITLE
Activity notification loop - an email sent to all every 30 minutes

### ISSUE THREAD

**Issue by wherf** [owncloud/core#26369]
### Steps to reproduce
1.The server is sending the activity email to all users every thirty minutes with teh same content
2. This happened after a share to all was set at a top level folder and then a share to all was set on a sub-level folder. This possibly led to a loop
3.

### Expected behaviour
The activety email should only go out for new activities and not be repeated
### Actual behaviour
The server is sending the activity email to all users every thirty minutes with teh same content
### Server configuration
**Operating system**:
ubuntu
**Web server:**
apache
**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
8.2.8
**Updated from an older ownCloud or fresh install:**
fresh install
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
@wherf any exceptions in owncloud.log ?

Maybe there is an error happening after sending the emails but before deleting the entries from the database.

**Comment by wherf** [comment]
Thanks for the comment- yes there is an error

OCP\Files\not found Exception
Error while trying to create shared mount

Sounds like access rights, where should I look?

Von: Vincent Petry [mailto:notifications@github.com]
Gesendet: Montag, 17. Oktober 2016 11:04
An: owncloud/core
Cc: Wolf Dieter Herf; Mention
Betreff: Re: [owncloud/core] Activity notification loop - an email sent to all every 30 minutes (#26369)


@wherf<https://github.com/wherf> any exceptions in owncloud.log ?

Maybe there is an error happening after sending the emails but before deleting the entries from the database.

**Comment by PVince81** [comment]
I don't think it's access right. Can you paste the matching log entry here from owncloud.log ?

**Comment by PVince81** [comment]
Maybe it is trying to send emails for activities about shares that don't exist any more, especially if these are old entries. The database table oc_activity_mq contains a list of all activities pending to be sent.

**Comment by wherf** [comment]
Ah, this is the case, yes we deleted a number of folders

Can I modify the table or the live system, which webtool would you recommend?  If I clear the oc_activity_mq would that resolve teh issue?

Von: Vincent Petry [mailto:notifications@github.com]
Gesendet: Dienstag, 18. Oktober 2016 08:51
An: owncloud/core
Cc: Wolf Dieter Herf; Mention
Betreff: Re: [owncloud/core] Activity notification loop - an email sent to all every 30 minutes (#26369)


Maybe it is trying to send emails for activities about shares that don't exist any more, especially if these are old entries. The database table oc_activity_mq contains a list of all activities pending to be sent.

**Comment by PVince81** [comment]
If you clear that table it will not send any of the pending notifications any more. But I think it might solve the issue for you in the future.

**Comment by wherf** [comment]
The log is being filled with this single error all the time, Ist now already 2GB big

Maybe thats the issue?


{"reqId":"JwPJXq0bbkQM+fadjNvW","remoteAddr":"91.64.60.106","app":"no app in context","message":"Error while trying to create shared mount","level":3,"time":"2016-09-07T16:14:56+00:00","method":"GET","url":"\/index.php\/avatar\/m.kapst\/32","user":"Intranet"}

{"reqId":"Xm6ZX2+PMzEzdr5pdsGr","remoteAddr":"91.64.60.106","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Share20\\\/DefaultShareProvider.php(437): OC\\\\Share20\\\\Share->getNode()\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Share20\\\/Manager.php(878): OC\\\\Share20\\\\DefaultShareProvider->move(Object(OC\\\\Share20\\\\Share), 'Intranet')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedMount.php(120): OC\\\\Share20\\\\Manager->moveShare(Object(OC\\\\Share20\\\\Share), 'Intranet')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedMount.php(102): OCA\\\\Files_Sharing\\\\SharedMount->updateFileTarget('\\\/Klasse 2010 (2...', Object(OC\\\\Share20\\\\Share))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/SharedMount.php(73): OCA\\\\Files_Sharing\\\\SharedMount->verifyMountPoint(Object(OC\\\\Share20\\\\Share), Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/MountProvider.php(91): OCA\\\\Files_Sharing\\\\SharedMount->__construct('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, Array, Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(77): OCA\\\\Files_Sharing\\\\MountProvider->getMountsForUser(Object(OC\\\\User\\\\User), Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\n#7 [internal function]: OC\\\\Files\\\\Config\\\\MountProviderCollection->OC\\\\Files\\\\Config\\\\{closure}(Object(OCA\\\\Files_Sharing\\\\MountProvider))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(78): array_map(Object(Closure), Array)\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(423): OC\\\\Files\\\\Config\\\\MountProviderCollection->getMountsForUser(Object(OC\\\\User\\\\User))\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(371): OC\\\\Files\\\\Filesystem::initMountPoints('Intranet')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/util.php(227): OC\\\\Files\\\\Filesystem::init('Intranet', '\\\/Intranet\\\/files')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/api.php(353): OC_Util::setupFS('Intranet')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/api.php(300): OC_API::loginUser()\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/api.php(159): OC_API::isAuthorised(Array)\\n#15 [internal function]: OC_API::call(Array)\\n#16 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(293): call_user_func(Array, Array)\\n#17 \\\/var\\\/www\\\/nextcloud\\\/ocs\\\/v1.php(61): OC\\\\Route\\\\Router->match('\\\/ocs\\\/apps\\\/files...')\\n#18 \\\/var\\\/www\\\/nextcloud\\\/ocs\\\/v2.php(23): require_once('\\\/var\\\/www\\\/nextcl...')\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Share20\\\/Share.php\",\"Line\":163}","level":3,"time":"2016-09-07T16:14:57+00:00","method":"PUT","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares\/83?format=json","user":"Intranet"}
{

Von: Vincent Petry [mailto:notifications@github.com]
Gesendet: Dienstag, 18. Oktober 2016 08:57
An: owncloud/core
Cc: Wolf Dieter Herf; Mention
Betreff: Re: [owncloud/core] Activity notification loop - an email sent to all every 30 minutes (#26369)


If you clear that table it will not send any of the pending notifications any more. But I think it might solve the issue for you in the future.

**Comment by PVince81** [comment]
is this owncloud or nextcloud ? some of the code might not be 100% the same so the issue could be different...

**Comment by wherf** [comment]
nextcloud - the first version

Maybe you can give me a pointer to what it could be

Von: Vincent Petry [mailto:notifications@github.com]
Gesendet: Dienstag, 18. Oktober 2016 09:03
An: owncloud/core
Cc: Wolf Dieter Herf; Mention
Betreff: Re: [owncloud/core] Activity notification loop - an email sent to all every 30 minutes (#26369)


is this owncloud or nextcloud ? some of the code might not be 100% the same so the issue could be different...

**Comment by PVince81** [comment]
This here is the bug tracker for owncloud. The one for nextcloud is there https://github.com/nextcloud/, please reopen there.

But in your report you mentioned OC 8.2.8 ?

**Comment by wherf** [comment]
Will do, I have two system , one an owncloud 8.28 and one a nextcloud 10, posted the issue in the wrong bug tracker by mistake, sorry

Von: Vincent Petry [mailto:notifications@github.com]
Gesendet: Dienstag, 18. Oktober 2016 09:08
An: owncloud/core
Cc: Wolf Dieter Herf; Mention
Betreff: Re: [owncloud/core] Activity notification loop - an email sent to all every 30 minutes (#26369)


This here is the bug tracker for owncloud. The one for nextcloud is there https://github.com/nextcloud/, please reopen there.

But in your report you mentioned OC 8.2.8 ?

**Comment by PVince81** [comment]
No worries, closing then.

**Comment by wherf** [comment]
You sound colonial "No worries" is a typical "Seth Efrican" or "Aussie" saying

Von: Vincent Petry [mailto:notifications@github.com]
Gesendet: Dienstag, 18. Oktober 2016 09:17
An: owncloud/core
Cc: Wolf Dieter Herf; Mention
Betreff: Re: [owncloud/core] Activity notification loop - an email sent to all every 30 minutes (#26369)


No worries, closing then.
