### ISSUE TITLE
[9.1.0] Changing passwords as admin doesn't work

### ISSUE THREAD

**Issue by mankra** [owncloud/core#26378]
### Steps to reproduce
1. Login with admin account
2. Goto users page
3. Click on the pencil on the right of a password field
4. Enter a new password
5. Hit return
### Expected behaviour

Password is changed and admin is noticed about the successful change.
### Actual behaviour

Nothing happens. Password is not changed.
### Server configuration

**Operating system**: Debian GNU/Linux 8.1 (jessie)

**Web server:** Apache 2

**Database:** MariaDB 10.0.26 (Plesk 12.5)

**PHP version:** 5.6.24-0+deb8u1 (cli)

**ownCloud version:** 9.1 stable

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** owncloud.org

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.5
  - encryption: 1.3.0
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - passwords: 20-beta5
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ochs3d11a9si",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.krd.land"
        ],
        "datadirectory": "\/var\/www\/vhosts\/krd.zone\/owncloud.krd.land\/data",
        "overwrite.cli.url": "http:\/\/owncloud.krd.land",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_domain": "krd.land",
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.krd.zone",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```

**Are you using external storage:** no

**Are you using encryption:** yes

**Are you using an external user-backend:** no
### Client configuration

**Browser:** Mozilla Firefox 49.0.1

**Operating system:** Windows 7 x64
#### Web server error log

```
No errors occurring within the web server log.
```
#### ownCloud log (data/owncloud.log)

```
Only these errors occur within the owncloud.log, but they're related to login failing:

{"reqId":"QZgnqglvOR3UEtZfQisy","remoteAddr":"***REMOVED SENSITIVE VALUE***","app":"core","message":"Login failed: '***REMOVED SENSITIVE VALUE***' (Remote IP: '***REMOVED SENSITIVE VALUE***')","level":2,"time":"2016-10-14T09:42:04+00:00","method":"POST","url":"\/index.php\/login","user":"--"}
{"reqId":"obHSjQnGm\/CmmqgWF4Ve","remoteAddr":"***REMOVED SENSITIVE VALUE***","app":"PHP","message":"Undefined offset: 1 at \/var\/www\/vhosts\/krd.zone\/owncloud.krd.land\/core\/Controller\/LoginController.php#117","level":3,"time":"2016-10-14T09:42:04+00:00","method":"GET","url":"\/index.php\/login?user=***REMOVED SENSITIVE VALUE***","user":"--"}
{"reqId":"obHSjQnGm\/CmmqgWF4Ve","remoteAddr":"***REMOVED SENSITIVE VALUE***","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/vhosts\/krd.zone\/owncloud.krd.land\/core\/templates\/login.php#23","level":3,"time":"2016-10-14T09:42:04+00:00","method":"GET","url":"\/index.php\/login?user=***REMOVED SENSITIVE VALUE***","user":"--"}
```
#### Browser log

```
No errors occuring within the browser log.
```

**Comment by SergioBertolinSG** [comment]
Just tried stable9.1 with encryption, no problems at all changing users passwords.

**Comment by SergioBertolinSG** [comment]
I guess it is related with this app:
 - passwords: 20-beta5

**Comment by RealRancor** [comment]
Could be, or the usage of an outdated version like 9.1.0 where 9.1.1 is already available.

**Comment by mankra** [comment]
I relied on the built in updater to tell me that a new version is available, but it does not do so. It still tells me that 9.1.0 is up to date using the stable channel, while on the website 9.1.1 is stated as a stable release.

I will test wether the bug is gone with 9.1.1 next week.

I don't think that the passwords app is responsible, as it doesn't change anything with the user management as far as I know. It just adds the functionality of a password safe.

**Comment by mankra** [comment]
I tested with 9.1.2 and it still simply does nothing.

**Comment by RealRancor** [comment]
@mankra Then you might want to re-check your logfiles (server and browser) again after the update. There is most likely something logged which you have missed (e.g. a Forbidden message in your browser or similar when saving a password).

Testing different browsers and PCs (to see if a browser plugin might cause this) should be also done.

**Comment by mankra** [comment]
There's no logged error as far as I can see. It looks like it just does nothing:
- no reloading of the website
- no suspicious javascript action
- it just changes back to the asterisks and the password is not changed.

From the changelog:
> Core: Display feedback in users page when changing password - [core/#25532](https://github.com/owncloud/core/issues/25532)

As far as I can tell:
- I have a normal Firefox browser 49.0.2 with Adblock deactivated at my owncloud page.
- I installed owncloud manually the way how it's described on the homepage.
- I installed the passwords app by simply extracting it in the apps folder and activated it.
- I activated the default encryption module and set a restoration key.
- Everything works fine except the problem described above.

**Comment by RealRancor** [comment]
> I installed the passwords app by simply extracting it in the apps folder and activated it.

And have you disabled it (and possible other 3rdparty apps) as asked twice?

**Comment by mankra** [comment]
Yes, and it was how I expected: It has nothing to do with the owncloud user management, it just adds a password safe for existing users.

**Comment by RealRancor** [comment]
>  It has nothing to do with the owncloud user management, it just adds a password safe for existing users.

That doesn't matter in this case as seen on e.g. the files_mv app (https://github.com/owncloud/core/issues/26503). It has nothing to do with the mentioned apps but still breaks them.

After you disabled the app its guaranteed that it is not the source of this issue.

**Comment by PVince81** [comment]
Please try again with disabled third party apps
