### ISSUE TITLE
Just updated, slow sync - webdav file locked 

### ISSUE THREAD

**Issue by signmeuptwice** [owncloud/core#26374]
So I just updated from 9.01 to 9.11 and it is my first update. Everything semed fine until I began adding new files and now I have yellow icons, webdav error and very slow syncing (if at all)
Not sure what is happening :((

followed the steps from the manual. updated with apt-get, used occ, ran permission script

Steps to reproduce
1.sync file from desktop client

Expected behaviour
Tell us what should happen
sync file

Actual behaviour
Tell us what happens instead
very slow
client stuck on upload for 24 hours now
yellow icon on folder but everything green inside
uploading new files seems to be working
log show a lot of fatal error webdav (file is locked)

Server configuration
Operating system: debian 8.3 latest
Web server: apache latest
Database: Mysql latest
PHP version: latest
ownCloud version (see ownCloud admin page): 9.1.1
Updated from an older ownCloud or fresh install: updated from 9.01

Special configuration (external storage, external authentication, reverse proxy, server-side-encryption): encryption enabled

note:
The only thing I am not sure if I did right in the upgrade is the permission script.
Never done this before but here is what I did:

1 - created a file called "script" and pasted the content provided by the OC manual
2 typed "sudo script", also tried "sudo script script"

every time I got no feedback but no error either. Not sure if I messed things up with permissions this way ?

thanks

**Comment by signmeuptwice** [comment]
something I am not understanding also maybe related. My dates are wrong; in the activity tab it says for some tasks: "in 7 hours" what does that mean ? is it doing a task that needs time ?

**Comment by signmeuptwice** [comment]
I cannot upload anything now !!!! please help

**Comment by signmeuptwice** [comment]
![untitled copy](https://cloud.githubusercontent.com/assets/18756447/19402962/233db888-925c-11e6-9682-8f7ea5d50b6d.jpg)
Are my permissions correct ?

**Comment by signmeuptwice** [comment]
Did a file scan and got these errors:
Exception while scanning: "files/185d6962245f7a515367d06c2213175e" is locked
#0 /var/www/owncloud/lib/private/Files/Storage/Common.php(668): OC\Lock\DBLockingProvider->acquireLock('files/185d69622...', 1)
#1 /var/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(584): OC\Files\Storage\Common->acquireLock('files/Documents...', 1, Object(OC\Lock\DBLockingProvider))
#2 /var/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(584): OC\Files\Storage\Wrapper\Wrapper->acquireLock('files/Documents...', 1, Object(OC\Lock\DBLockingProvider))
#3 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(140): OC\Files\Storage\Wrapper\Wrapper->acquireLock('files/Documents...', 1, Object(OC\Lock\DBLockingProvider))
#4 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(409): OC\Files\Cache\Scanner->scanFile('files/Documents...', 3, '36390', NULL, true)
#5 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(377): OC\Files\Cache\Scanner->handleChildren('files/Documents...', true, 3, '36390', true, 32831)
#6 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(380): OC\Files\Cache\Scanner->scanChildren('files/Documents...', true, 3, '36390', true)
#7 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(380): OC\Files\Cache\Scanner->scanChildren('files/Documents...', true, 3, '7531', true)
#8 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(380): OC\Files\Cache\Scanner->scanChildren('files/Documents...', true, 3, '7168', true)
#9 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(380): OC\Files\Cache\Scanner->scanChildren('files/Documents...', true, 3, '7136', true)
#10 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(380): OC\Files\Cache\Scanner->scanChildren('files/Documents', true, 3, '26', true)
#11 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(380): OC\Files\Cache\Scanner->scanChildren('files', true, 3, '2', true)
#12 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(311): OC\Files\Cache\Scanner->scanChildren('', true, 3, 1, true)
#13 /var/www/owncloud/lib/private/Files/Utils/Scanner.php(195): OC\Files\Cache\Scanner->scan('', true, 3)
#14 /var/www/owncloud/apps/files/lib/Command/Scan.php(158): OC\Files\Utils\Scanner->scan('/sinewavz')
#15 /var/www/owncloud/apps/files/lib/Command/Scan.php(226): OCA\Files\Command\Scan->scanFiles('user1', '/user1', false, Object(Symfony\Component\Console\Output\ConsoleOutput), false)
#16 /var/www/owncloud/3rdparty/symfony/console/Command/Command.php(259): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/owncloud/core/Command/Base.php(158): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/owncloud/3rdparty/symfony/console/Application.php(844): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/owncloud/3rdparty/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/owncloud/3rdparty/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/owncloud/lib/private/Console/Application.php(146): Symfony\Component\Console\Application->run(NULL, NULL)
#22 /var/www/owncloud/console.php(94): OC\Console\Application->run()
#23 {main}

**Comment by signmeuptwice** [comment]
xxxxx@xxxxxx:/var/www/owncloud$ sudo -u www-data php owncloud/updater/application.php
Could not open input file: owncloud/updater/application.php

**Comment by signmeuptwice** [comment]
I think I found the issue. I have this folder I deleted a while ago that shows on my web interface only ant it says pending.. All files in the folders are locked. Trying to delete the folder from the web interface gives an error. What to do ? Can I run a script to fix this ? Looks like a db issue ?

**Comment by signmeuptwice** [comment]
Making more progress but now completely stuck. I recreated the folder manually and began downloading some of the files from the web interface and placing them on my desktop client folder. Somehow this seemed to unblock the folder and all the files in the folder got deleted on the web too but I am left with the main folder and one subfolder that I cannot delete. 
- all I get when I try to delete manually from the web interface is: Error deleting file "Images". 
- when I try deleting "images " from the client nothing happens and the file is still on the web interface

**Comment by signmeuptwice** [comment]
sudo -u www-data php /var/www/owncloud/updater/application.php
ownCloud updater 1.0 - CLI based ownCloud server upgrades
Checking system health.


                                                                                              
  [Symfony\Component\Process\Exception\ProcessFailedException]                                
  The command "php /var/www/owncloud/occ --no-warnings app:list --output=json '--shipped fal  
  se'" failed.                                                                                
  Exit Code: 1(General error)                                                                 
  Output:                                                                                     
  ================                                                                            
  Error Output:                                                                               
  ================                                                                            
                                                                                              
    [Symfony\Component\Console\Exception\RuntimeException]                                    
    The "--shipped false" option does not exist.                                              
                                                                                              
  app:list [--output [OUTPUT]] [--shipped SHIPPED]                                            
                                                                                              


upgrade:checkSystem

**Comment by signmeuptwice** [comment]
any of this help ? Im really stuck here... Any way to rebuild my database ? why do I get jobs happening in 7 hours on the web interface ? Really stuck !!!! Webdav is taking the piss :(

**Comment by signmeuptwice** [comment]
no support at all then ? I provided a lot of information ... Should I move to nextcloud then ? :((((

**Comment by RealRancor** [comment]
A perfect base to get help:

- Being impatient
- Flooding the issue with unnecessary comments instead of using the edit button
- Throwing stuff like "should i move to nextcloud" around -> They mostly also don't want such users
- Thinking that a bugtracker is an instant support channel

What you could do here to actually provide all needed info once some one has time too look after this is, to strip down / delete all your comments and collect all real info which you think are relevant for this issue in your initial report.

**Comment by signmeuptwice** [comment]
Thanks RealRancor for the usual reply where you never... I have become used to it by now.. All my posts are real info. If it is not real enough for you then don't reply... Sorry Im not a master at programing like you. 
If anyone if offended by my comment on nextcloud and saying that "they don't want such user" is real crazy; I comment what I want. I have given a huge amount of technical infos and it is not the first time I get file locked on webdav. I had that with oc 8.xx and now 9.xx and the net has plenty of example like mine so if there is no fix for that or method to diagnose then I can't rely on oc... 
So now do you have the slightest clue to point me in the right direction ? If you don't then ask for the specific info you need. That is a CONSTRUCTIVE attitude. If you don't know just let me be but policing like you do is just being a jerk.

**Comment by RealRancor** [comment]
You're really expecting that one reads through 10 comments full of "no support at all then" or posts of wrong occ usage to get all needed info? And no, these posts are not "real info".

So please follow my advise and strip down your comments to the minimum.

**Comment by signmeuptwice** [comment]
whatever... Maybe someone else will help and even if I wanted to do what you say I could not because each post is a different side of the issue and I don't understand all the interactions so all I would do is copy paste which would not change anything.

**Comment by PVince81** [comment]
Try switching to system cron if you're using ajax cron, ref https://github.com/owncloud/core/issues/20380

**Comment by PVince81** [comment]
please let us now whether using system cron helped solve the issue

**Comment by PVince81** [comment]
Please reopen if it didn't
