### ISSUE TITLE
No confirmation dialog upon user deletion

### ISSUE THREAD

**Issue by chrone81** [owncloud/core#26388]
### Steps to reproduce
1. Login as admin.
2. Delete a user.
3. No confirmation dialog upon user deletion.

### Expected behaviour
There should have been a confirmation dialog before deleting a user to avoid accidentally deletion.

### Actual behaviour
Owncloud deletes the user without confirmation at all.

### Server configuration
**Operating system**:
Ubuntu 16.04.1 LTS x64

**Web server:**
Apache 2.4.18

**Database:**
MariaDB 10.1 Galera

**PHP version:**
7.0.8

**ownCloud version:** (see ownCloud admin page)
9.1.1

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
Official repository

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
All official apps excepts for Antivirus App for files due to it slows down user creation for like a minute or two.
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.6
  - encryption: 1.3.0
  - external: true
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_external: 0.4
  - user_ldap: 0.9.0
Disabled:
  - files_antivirus

**Comment by RealRancor** [comment]
This is by design and adding that feature was rejected for the reasons explained here: https://github.com/owncloud/core/issues/14945#issuecomment-82387715
