### ISSUE TITLE
iPhone 6s iOS 10.0.2 Calendar won't sync

### ISSUE THREAD

**Issue by K4lim** [owncloud/core#26394]
### Steps to reproduce
1. Install fresh copy of Owncloud with Calendar App
2. Configure server in the iPhone
3. Open Calendar app
3. http://imgur.com/a/1n03u  <- Used this settings.

### Expected behaviour
show any dates or labels.

### Actual behaviour
shows nothing

### Server configuration

Web server 	Apache
HTTP response code 	403
content-encoding 	gzip
server 	Apache
transfer-encoding 	chunked

Only specs I can tell you, sorry.

**ownCloud version:** (see ownCloud admin page)

ownCloud 9.1.1 (stable)

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
downloaded from official site

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Contacts, Calendar, ToDo,  Default encryption module 
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '******',
  'passwordsalt' => '******',
  'secret' => '******',
  'trusted_domains' => 
  array (
    0 => 'www.cloud.******.me',
    1 => 'cloud.******.me',
  ),
  'datadirectory' => '/homepages/3/******/htdocs/******/cloud/data',
  'overwrite.cli.url' => 'http://www.cloud.******.me',
  'dbtype' => 'mysql',
  'version' => '9.1.1.3',
  'dbname' => '******',
  'dbhost' => '******',
  'dbtableprefix' => 'oc_',
  'dbuser' => '******',
  'dbpassword' => '******',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
);
```

**Comment by RealRancor** [comment]
@K4lim Please note this is a bugtracker for ownCloud. For support questions like this https://central.owncloud.org/ needs to be used.

So please close here and open a new thread at central (you can use your github account there). When doing so make sure that you're providing an example URL you have used.
