### ISSUE TITLE
Problems changing password

### ISSUE THREAD

**Issue by gzdncs** [owncloud/core#26397]
I am using owncloud 9.0.0
I am trying to create an automated tool with selenium to change the password of the users programatically but when I click on password's `<span>` it changes to `<input>` then it changes back inmediatly so I can't write the password.
So I changed my approach and I am trying to modify the record in the table oc_users of the database but I would like to use the same function that owncloud uses. Can you tell me which function is owncloud using so I can use the same? because I don't understand what does `1|$` means.
Or please let me know where is the documentation of the password encryption so I can create my own php function.
If you have a different approach to suggest it would be very appreciated.
Thanks in advance.

**Comment by RealRancor** [comment]
@gzdncs Please note this is a bugtracker for ownCloud. For support questions like this https://central.owncloud.org/ needs to be used.

So please close here and open a new thread at central (you can use your github account there).

**Comment by PVince81** [comment]
also you should first try with the latest version 9.0.5 where the bug might be fixed already, and use the issue template when reporting bugs: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
