### ISSUE TITLE
can only upload one file by one...

### ISSUE THREAD

**Issue by silelmot** [owncloud/core#26393]
Just a quick question if this is known or totaly new?

when i  try to upload to a shared folder, and i select more files , only the first one is uploaded, and then the progress bar stops and no other file is uploaded anymore. 
if i try to upload just one file the progress bar also didnt remove after finishing and i have to reload the page manually to see the new files.

**Comment by RealRancor** [comment]
@silelmot Please fill out the issue template shown when creating a new issue. Reports like this, where even the basic infos like used ownCloud version are missing are mostly useless.

In general questions like this should be first directed to https://central.owncloud.org/. If this is indeed a bug it can be reported here.
