### ISSUE TITLE
7 Zip issue

### ISSUE THREAD

**Issue by VedranOP** [owncloud/core#26414]
Dear Community,

Actions:

1. Shared a folder with a link
2. Download folder as a .zip file
3. When I extract it using 7 zip I get a header error 
4. Using WinRAR everything is ok.

Environment: Win OS 7, 10.
Help?
Thank you in advance

**Comment by RealRancor** [comment]
@VedranOP Please fill out the issue template shown when creating a new issue. Reports like this which are even missing the mandatory info are pretty useless.
