### ISSUE TITLE
stable9: Duplicated www-authenticate header on new remote.php/dav endpoint

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#26412]
### Steps to reproduce
1. Run curl -I http://example.com/remote.php/dav
2. Run curl -I http://example.com/remote.php/webdav
3. See that the first call contains two `WWW-Authenticate: Basic realm="sabre/dav"`
4. See that the second call contains one `WWW-Authenticate: Basic realm="sabre/dav"`
### Expected behaviour

Only one WWW-Authenticate header is sent back in the new remote.php/dav endpoint
### Actual behaviour

Two WWW-Authenticate header are sent back in the new remote.php/dav endpoint
### Server configuration

**ownCloud version:** 9.0.5

Everything else is unrelated from my PoV as this was observed on various other oC 9.0.x systems available out there found with a google dork like:

`inurl:/status.php owncloud`

**Comment by PVince81** [comment]
Yeah, I've seen this before in newer versions: https://github.com/owncloud/core/issues/26351#issuecomment-253161768

Might be because we have multiple DAV Auth backends registered and they all fail in a series and each one sets that header again. (IIRC)

Need to find another approach.

**Comment by RealRancor** [comment]
Yeah, just also noticed this at https://github.com/owncloud/core/issues/26351 :-)

**Comment by PVince81** [comment]
Looks like @DeepDiver1975 found a solution, maybe we can backport that piece https://github.com/owncloud/core/pull/26353#issuecomment-255331479

**Comment by adduxa** [comment]
### Issue side effect: <br>Double auth header makes Windows WebDav client unable to connect.

It trying to perform `Negotiate Authentication` instead of `Basic` for no reason, except for the double `WWW-Authenticate` header.

Network log for `/remote.php/webdav/`:
```
> OPTIONS /remote.php/webdav HTTP/1.1
< HTTP/1.1 401 Unauthorized
  WWW-Authenticate: Basic realm="ownCloud"

> OPTIONS /remote.php/webdav HTTP/1.1
  Authorization: Basic BasicAuthTokenHere=
< HTTP/1.1 200 OK
```

Network log for `/remote.php/dav/USERNAME/`:
```
> OPTIONS /remote.php/dav/files/USERNAME HTTP/1.1
< HTTP/1.1 401 Unauthorized
  WWW-Authenticate: Basic realm="ownCloud"
  WWW-Authenticate: Basic realm="ownCloud"

> OPTIONS /remote.php/dav/files/USERNAME HTTP/1.1
  Authorization: Negotiate ReallyLongManyCharactersNegotiateAuthorizationTokenHere==
< HTTP/1.1 401 Unauthorized
  WWW-Authenticate: Basic realm="ownCloud"
  WWW-Authenticate: Basic realm="ownCloud"
```
_(Identical headers for both requests are removed)_

**Comment by PVince81** [comment]
Duplicate headers should be fixed in 9.2 / master already but we can try and backport some parts of the fixes for older versions.

**Comment by PVince81** [comment]
@DeepDiver1975 can you backport https://github.com/owncloud/core/pull/26353#issuecomment-255331479 to 9.1 and 9.0 ?

**Comment by PVince81** [comment]
AFAIK the fix is only for the remote.php/dav endpoint. There was no duplicate header on the "remote.php/webdav" header. Maybe the issue from @adduxa is different and is still causing duplicate headers. Can you test with https://github.com/owncloud/core/issues/26688 ?

**Comment by adduxa** [comment]
@PVince81 yep, only one header and now it's working. Thanks @DeepDiver1975 for fix!
P.S. I have 9.1, so #26687 for me
