### ISSUE TITLE
index.php: Correctly check for upper PHP versions as well 

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#26431]
In the current index.php for e.g. 9.1.1 only the min. version of PHP is checked:

https://github.com/owncloud/core/blob/v9.1.1/index.php#L27-L33

However people will definitely trying to run oC 9.1.1 on e.g. PHP 7.1 (few RCs are out) where only master/9.2 is compatible with PHP 7.1 (https://github.com/owncloud/core/pull/25346)

stable8 + stable8.1 is already testing for the max. version of PHP 7.0.0 but stable8.2, stable9.0 and stable9.1 is not testing that.

**Comment by PVince81** [comment]
PRs for stable9, stable9.1 merged.

Submit another PR for stable8.2 ?

**Comment by RealRancor** [comment]
I think the chance that people are installing 8.2 once 7.1 is out is unlikely. Thats why i havn't created PRs against stable8.2 and below.
