### ISSUE TITLE
Internet Explorer 11: no files

### ISSUE THREAD

**Issue by SteBre** [owncloud/core#26438]
Hi there,

I downloaded latest VM image with ubuntu 14.04.2 and owncloud 9.1.1
Everything works fine - i thought - even I used Internet Explorer 11 (11.0.9600.18499 on Windows7 or even 11.321.14393.0 on Windows 10).

When loging in (local user oder ldap user, does not matter), screen ist empty:
there are no files and no possibility to create folders, upload files, and so on.

![94b6ce4e23f6b789482e2324485dbe4c11b4e097](https://cloud.githubusercontent.com/assets/22978703/19594168/3768f700-9784-11e6-93c9-99167db86c49.png)

After that I'm using firefox or chrome with exact this user, works.
Back to internet explorer, login, works.

So it seems that there is a finishing process for every profile when loging in the first time and then it works, and this process does not finish when using IE?

Is this behavior reproducible at onyone else of you?

thank you

**Comment by SteBre** [comment]
fyi:

i tried same procedure on an public owncloud site which i found in google: https://friends.nimmerland.de/login

same result, create new user, login with IE11 = no function
after login with firefox the functionality is given in IE11, too.

**Comment by jmooves** [comment]
I also have this issue with 9.1.0.  I can't recall seeing it with our users with any version before 9.0

**Comment by PVince81** [comment]
When setting up v9.1.1 from git with only core, all works fine in IE11.
However when using the v9.1.1 tarball I also get an empty page with a jquery error:
```
Unexpected call to method or property access.
File: jquery.min.js, Line: 3, Column: 5682
```

So it could be related to some of the enabled apps.

**Comment by PVince81** [comment]
Ok, found it: try disabling the "first run wizard" app.
It usually shows a popup window the first time a user logs in.

This is why after logging in in Firefox the problem disappears.

**Comment by PVince81** [comment]
The IE11 debugger in all its glory:
![ie11-firstrunwizard](https://cloud.githubusercontent.com/assets/277525/19939510/a443414c-a129-11e6-8570-e3c283dc19ff.png)

It seems jquery.colorbox is having trouble with IE11. I'm a bit surprised because this could mean that the first run wizard never worked with IE11 before...

**Comment by PVince81** [comment]
Looks like it worked in OC 8.1.9... So possibly caused by a recent jquery update.

**Comment by PVince81** [comment]
Also works in 9.0.5.

**Comment by PVince81** [comment]
Yeah, looks like it's the jquery update: 7186975e35d03312f46b27d808a98f7bc6064078 from https://github.com/owncloud/core/pull/23993

Let's see if there is an update colorbox version...

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/firstrunwizard/pull/56
