### ISSUE TITLE
Uploading of 0 bytes files is not possible in external storages mountpoints

### ISSUE THREAD

**Issue by davitol** [owncloud/core#26439]
### Steps to reproduce

1. Upload an empty file (0 bytes) using the web UI inside a MountPoint (tested with WND and DropBox)

### Expected behaviour
File is uploaded.

### Actual behaviour
File is not uploaded because it has 0 bytes.
A warning is shown: "Error uploading file "0bytes": Unable to upload 0bytes as it is a directory or has 0 bytes"

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** 
"version":"9.1.1.3","versionstring":"9.1.1"

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, DropBox and WND
**Are you using encryption:** 
No

**Logs**
```
```
### Client configuration

**browser**
Chrome.

**Comment by davitol** [comment]
Same behaviour that happen before for regular storage: https://github.com/owncloud/core/issues/19116

**Comment by PVince81** [comment]
Try again with 9.1.2RC2, the fix is there: https://github.com/owncloud/core/pull/26135

Also, not related to external storages.

**Comment by davitol** [comment]
> Try again with 9.1.2RC2, the fix is there: #26135

Works!!! Let's close this issue
