### ISSUE TITLE
Group admin should be able to set default share to same group for new uploads / files.

### ISSUE THREAD

**Issue by dfixbugs1** [owncloud/core#26446]
### Steps to reproduce

1.
2.
3.
### Expected behaviour

There should be a way to set the default sharing for new files uploaded. For example, it should be possible that anyone in a group can see a file uploaded by anyone else in the group. Otherwise, it forces newbie users to share the file, instead of just uploading it and expecting that anyone in the group can see it.

Use case: I want clients to be able to upload a file using an account assigned to them. They should need to know virtually NOTHING about sharing and owncloud. Just upload a file. From my account which is a member of their and many other groups, I should be able to see the file. But I can't unless they take the extra step of sharing it. The group admin should be able to set the default permissions / sharing of all files added by a group member. Then all they have to do is upload it, and if the group admin desires, all group members can see it without an extra need for the uploader person to learn how to share.
### Actual behaviour

Tell us what happens instead
### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by RealRancor** [comment]
This is already possible. Use a group admin and share a folder to a group. Then set the quota for each group member to 0 byte. Afterwards the group users can only upload files to that folder which is shared to anyone of the group.

No need to overengineer stuff by adding more and more extra stuff for edge use-cases

**Comment by dfixbugs1** [comment]
I think I can skip the quota = 0 byte step for my purposes. It may create end-user confusion as well when they try to upload in the wrong place.

 

Is there any way to set the folder from a login URL that we provide to a end-user (see use case – untrained end-user uploading files)? Or to have the login default to view inside the group’s folder?

**Comment by hodyroff** [comment]
You might want to look at the skeleton feature: https://doc.owncloud.org/server/9.1/admin_manual/configuration_files/default_files_configuration.html
Really seems like workarounds are possible today and not necessarily a common use case.
Of course, if a PR comes we would still look at it. Please reopen if an identifyable problem or feature request exists.
