### ISSUE TITLE
APC not available

### ISSUE THREAD

**Issue by mathieufrh** [owncloud/core#26444]
### Steps to reproduce
1. Install owncloud on debian 7
2. Install php-apc
3. Edit the config to use APC for caching

### Expected behaviour
APC is used for caching.

### Actual behaviour
It seems like APC isn't used.
I don't know how the use of APC is implemented in the code. But I got the following error log each time the cron job is running.

I successfully install the `php-apc` package and enable it.
I actually use owncloud in a chrooted environnement.

```
{"reqId":"Ilx8paadA2ju0fOmlwFB","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APC not available for local cache","level":1,"time":"2016-10-21T14:00:01+00:00","method":"--","url":"--"}
{"reqId":"Ilx8paadA2ju0fOmlwFB","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APC not available for distributed cache","level":1,"time":"2016-10-21T14:00:01+00:00","method":"--","url":"--"}
```

### Server configuration
**Operating system**: Debian 7

**Web server:** Apache 2.2.22

**Database:** MySQL server 5.5.41

**PHP version:** PHP 5.4.38 (yeah I know I should move to 5.5 but the server runs other services that I haven't upgrade to use 5.5)

**ownCloud version:** 9.0.0

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** git stable branch

**Signing status (ownCloud 9.0 and above):**  Sorry I disable integrity checker.

**List of activated apps:** 

```
Enabled:
  - activity: 2.2.3
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.5
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - files_versions
  - firstrunwizard
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocl4w3y4pz2m",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "\/htdocs\/data",
        "overwrite.cli.url": "https:\/\/example.com",
        "share_folder": "\/Shared",
        "default_language": "fr",
        "dbtype": "mysql",
        "version": "9.0.0.19",
        "dbname": "example_owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "overwriteprotocol": "https",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_domain": "example.com",
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "forcessl": true,
        "proxy": "172.18.8.24:3128",
        "appcodechecker": true,
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/apps.owncloud.com\/",
        "mail_from_address": "admin",
        "integrity.check.disabled": true,
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "memcache.local": "\\OC\\Memcache\\APC"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 45.4.0

**Operating system:** Debian 8

#### Web server error log
```
Nothing particular
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"Ilx8paadA2ju0fOmlwFB","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APC not available for local cache","level":1,"time":"2016-10-21T14:00:01+00:00","method":"--","url":"--"}
{"reqId":"Ilx8paadA2ju0fOmlwFB","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APC not available for distributed cache","level":1,"time":"2016-10-21T14:00:01+00:00","method":"--","url":"--"}
{"reqId":"Ilx8paadA2ju0fOmlwFB","remoteAddr":"","app":"cron","message":"Run job with ID 63885","level":0,"time":"2016-10-21T14:00:02+00:00","method":"--","url":"--"}
[...]
```

#### Browser log
```
Nothing particular here
```

**Comment by RealRancor** [comment]
@mathieufrh Please note this is a bugtracker of ownCloud. Support requests like this should go to https://central.owncloud.org/

There you might also find some existing threads / answers.

**Comment by PVince81** [comment]
also please make sure you are using the latest version of OC, either 9.0.5 or 9.1.1

**Comment by RealRancor** [comment]
@PVince81 The logentries / question here was clarified in https://central.owncloud.org/t/apc-not-available/3498 so you could close this one here.
