### ISSUE TITLE
Question: What will happen after data/ dir suddenly disappeared

### ISSUE THREAD

**Issue by dumblob** [owncloud/core#26450]
I could not find any answer to the following question (not even using Google, GitHub issues, etc.). The closest I found is a very old commit https://github.com/owncloud/documentation/pull/1588/files , but it doesn't say anything about consequences.

What everything will happen with the running ownCloud server with connected clients (using both - some WebDAV client and the official ownCloud client) if the `data/` directory suddenly disappeared (e.g. due to some network issue in case it's a mounted network disk; or due to an unintentional unmounting by hand)? Will ownCloud server notice? Or will continue and use the "new" `data/` directory? Or will ownCloud switch to the "installation" mode and therefore show admin options on the login web page? Or what will be the exact behavior of ownCloud?

**Comment by RealRancor** [comment]
@dumblob Please note this is a bugtracker of ownCloud. Support requests / questions like this needs to go to https://central.owncloud.org/

**Comment by dumblob** [comment]
In my opinion this is a technical issue, not a support request/question. Let's rephrase the *Issue* to not be a question, but rather a serious bug.

All ownCloud versions (including the 9.2 development version) has totally undefined and undocumented behavior in case the `data/` directory suddenly disappeared (e.g. due to some network issue in case it's a mounted network disk; or due to an unintentional unmounting by hand; or due to corruption of RAID; or whatever other common reason) while the ownCloud server were running and had connected clients (both WebDAV clients and clients using the official ownCloud client).

1. Please meticulously document exact ownCloud behavior in this situation. Including, but not limited to what everything will ownCloud notice, how will be the *empty* or *unreachable* (infinite waiting times for disk operations) `data/` directory used after the incident, and how to prevent ownCloud showing the "installation" login web page (disclosing among other things admin options).

2. Implement some measures and precautions to handle this situation gracefully.

**Comment by RealRancor** [comment]
@dumblob Measures are already in place, i'm not pointing you out of fun to the support forums. ;-)

If you're missing documentation about that create a new issue at https://github.com/owncloud/documentation/issues

**Comment by PVince81** [comment]
https://github.com/owncloud/documentation/issues/2694 hope this clears it out

note that the owncloud installation page will not display in case of missing data directory because that information is stored in "config.php". So only if "config/config.php" is missing it would think that OC isn't installed.

**Comment by dumblob** [comment]
@RealRancor of course I didn't mean you're replying so out of fun, but if such an important information is missing in documentation, I consider it automatically not being implemented and thus a serious bug. Moreover I didn't want to sign up to ownCloud forums for such technical stuff if I already have a GitHub account. It would be nice to allow GitHubbers to write even support questions here, because it's not a big deal to use GitHub APIs to merge these issues with your ownCloud forums.

@PVince81 thank you. That information (including the `config/config.php` presence) is exactly what I was looking for and what made me calmer.

**Comment by RealRancor** [comment]
> Moreover I didn't want to sign up to ownCloud forums for such technical stuff if I already have a GitHub account. It would be nice to allow GitHubbers to write even support questions here, because it's not a big deal to use GitHub APIs to merge these issues with your ownCloud forums.

You can use your github account to login at the forums. A bugtracker is just not the place to ask technical questions as it would just flood this whole tracker and real bugs would be lost / unnoticed.
