### ISSUE TITLE
Administration settings - Documentation Links deprecated

### ISSUE THREAD

**Issue by tfrdidi** [owncloud/core#26451]
### Steps to reproduce
1. Open the administration settings in the web UI
2. Click on one of the "i"s to get directly to the documentation - this affects all of the "i"s!
### Expected behaviour

The docu from the actual version (9.1) should be opened and the redirection to the corresponding topic should be done, e.g. clicking on the link beside the sharing should open https://doc.owncloud.org/server/9.1/admin_manual/configuration_files/file_sharing_configuration.html.
### Actual behaviour

I get redirected to https://doc.owncloud.org/server/8.0/admin_manual/, which is neither my working version of owncloud nor the corresponding topic.
### Server configuration

**Operating system**: CentOS Linux release 7.2.1511 (Core)

**Web server:** Apache/2.4.6 (CentOS)

**Database:** MariaDB

**PHP version:** PHP 5.5.37

**ownCloud version:** 9.1.1 (stable)

**Updated from an older ownCloud or fresh install:** updated from 9.1.0

**Where did you install ownCloud from:** yum

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**List of activated apps:**

Enabled:
•activity: 2.2.1
•comments: 0.2
•dav: 0.1.6
•documents: 0.12.0
•encryption: 1.2.0
•federatedfilesharing: 0.1.0
•files: 1.4.4
•files_antivirus: 0.8.0.2
•files_external: 0.5.2
•files_pdfviewer: 0.8.1
•files_sharing: 0.9.1
•files_texteditor: 2.1
•files_trashbin: 0.8.0
•files_versions: 1.2.0
•files_videoplayer: 0.9.8
•firstrunwizard: 1.1
•gallery: 14.5.0
•notifications: 0.2.3
•passwordpolicy: 1.1
•provisioning_api: 0.4.1
•systemtags: 0.2
•templateeditor: 0.1
•updatenotification: 0.1.0 Disabled:
•external
•federation
•user_external
•user_ldap

**The content of config/config.php:**

<?php
 $CONFIG = array (
 'default_language' => 'de',
 'updatechecker' => false,
 'instanceid' => '...',
 'passwordsalt' => '...',
 'secret' => '...',
 'trusted_domains' =>
 array (
 0 => '...',
 1 => '...',
 ),
 'datadirectory' => '/srv/owncloud-data/',
 'overwrite.cli.url' => '...',
 'dbtype' => 'mysql',
 'version' => '9.0.3.2',
 'dbname' => '...',
 'dbhost' => '...',
 'dbtableprefix' => '...',
 'dbuser' => '...',
 'dbpassword' => '...',
 'logtimezone' => 'Europe/Berlin',
 'installed' => true,
 'mail_from_address' => 'hostmaster',
 'mail_smtpmode' => 'php',
 'mail_domain' => '...',
 'singleuser' => false,
 'appstore.experimental.enabled' => true,
 'enabledPreviewProviders' =>
 array (
 0 => 'OC\Preview\PNG',
 1 => 'OC\Preview\JPEG',
 2 => 'OC\Preview\GIF',
 3 => 'OC\Preview\BMP',
 4 => 'OC\Preview\XBitmap',
 5 => 'OC\Preview\MP3',
 6 => 'OC\Preview\TXT',
 7 => 'OC\Preview\MarkDown',
 8 => 'OC\Preview\PDF',
 ),
 'theme' => '',
 'loglevel' => 2,
 'maintenance' => false,
 'htaccess.RewriteBase' => '/owncloud',
 'theme' => '...',
 'preview_libreoffice_path' => '/usr/bin/libreoffice',
 );
 ?>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** independent

**Operating system:** Win 10
#### Browser log

Browser-Network-log for the "i" beside sharing:
GET /server/8.0/go.php?to=admin-sharing HTTP/1.1
Host: doc.owncloud.org
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: de,en-US;q=0.8,en;q=0.6,es;q=0.4,fr;q=0.2

HTTP/1.1 302 Moved Temporarily
Date: Mon, 24 Oct 2016 06:50:55 GMT
Server: Apache
Strict-Transport-Security: max-age=63072000
X-Xss-Protection: 1; mode=block
Location: https://doc.owncloud.org/server/8.0/admin_manual
Content-Length: 0
Keep-Alive: timeout=15, max=100
Connection: Keep-Alive
Content-Type: text/html; charset=utf-8

**Comment by PVince81** [comment]
Works for me with OC installed from the 9.1.1 tarball.

I went to the admin page, scrolled down to "Sharing" then clicked on the "i".
The URL points to https://doc.owncloud.org/server/9.1/go.php?to=admin-sharing and gets redirected to https://doc.owncloud.org/server/9.1/admin_manual/configuration_files/file_sharing_configuration.html

**Comment by RealRancor** [comment]
/server/8.0/go.php?to=admin-sharing is requested so this is most likely caused by a broken / not updated theme used by @tfrdidi

**Comment by PVince81** [comment]
Not sure if the old updater did it properly, but from what I see the new updater doesn't update the theme properly: https://github.com/owncloud/updater/issues/402

**Comment by PVince81** [comment]
Please fix your theme, your config seems to show that you have a custom theme and the URL can be overridden/specified there.

As for the updater bug https://github.com/owncloud/updater/issues/402 it was fixed in recent versions.
