### ISSUE TITLE
Integrity check cannot detect broken apps if they have no signature.json

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26463]
See https://github.com/owncloud/updater/issues/379

Basically when updating from OC <= 9 where signature.json did not exist, if an update fails then the app stays on the old version. But since it has no signature.json, the integrity check skips it...

In a similar fashion it could happen that an app from OC > 9 did not get updated but appears valid because it still has the old signature.json file.

Ideal would be to have an additional integrity check to make sure the app's code was updated as well. Maybe the checksum could be based on every bundled app's "appinfo/signature.json" file.

@RealRancor @DeepDiver1975 @VicDeo @davitol

**Comment by PVince81** [comment]
I suggest to extend the integrity check with the following approach:

When looking for signature.json in an app:
1) If the app is in shipped.json and the signature is missing => add error entry in the results for that app
2) If the app is not in shipped.json and the signature is missing => ignore

This is because whenever we check signature for the whole bundle, it means that we expect a signature to exist for all shipped apps as well.

**Comment by PVince81** [comment]
@VicDeo can you have a look ? Ties in somehow with the updater.

**Comment by VicDeo** [comment]
@PVince81 As I see `OC\IntegrityCheck\Checker::runInstanceVerification` does exactly what you described.

**Comment by PVince81** [comment]
Hmmm, but it didn't work. Or does it work correctly in recent versions ? Can you verify ?

**Comment by VicDeo** [comment]
@PVince81 hmmmm. Are you sure that we need to report that app from shipped.json is missing? :)
https://github.com/owncloud/core/blob/master/core/shipped.json#L8

**Comment by VicDeo** [comment]
For all shipped apps something like `apps/files/appinfo/signature.json:"hash"` can be added to the core/signature.json to validate if all signature data are available and correct

**Comment by VicDeo** [comment]
The same for 9.0.4.
Steps:
1. Modify core (e.g. by adding a new file into the OC root dir)
2. Remove `signature.json` for any shipped app
3. run `php occ integrity:check-core`
4. See that only core modifications are reported 
5. Login into the web ui as an admin
6. Click  Rescan in admin area
7. See that both core modifications and missing signature are reported

**Comment by VicDeo** [comment]
@PVince81 btw your own comment clearly proves that it works on upgrade: https://github.com/owncloud/updater/issues/379#issuecomment-255731255

**Comment by PVince81** [comment]
Hmm, then maybe it was fixed in 9.0.5 then ?

**Comment by VicDeo** [comment]
@PVince81 See https://github.com/owncloud/core/issues/26463#issuecomment-262619896
my 9.0.4 also reports missing signature (as expected).
CLI integrity check works a bit differently than Web. 
I've submitted https://github.com/owncloud/core/pull/26755 to make it consistent.

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/26755 is merged.

Close or is there anything remaining ?

**Comment by VicDeo** [comment]
yes, both https://github.com/owncloud/core/issues/26704 and https://github.com/owncloud/core/pull/26755 address this.
