### ISSUE TITLE
Photoshop file preview issue

### ISSUE THREAD

**Issue by imadsani** [owncloud/core#26478]
### Steps to reproduce
1. Install Owncloud 9.1.1
2. Install imageMagick & php-imagick
3. add the following to config:
'enabledPreviewProviders' => array(
        'OC\Preview\Photoshop',
        'OC\Preview\Illustrator',
),
4. Open HTOP and upload PSD file

### Expected behaviour
Preview of uploaded PSD should be generated.

### Actual behaviour
Depending on the server CPU, in my scenario, 2 httpd threads hit 100% and do not come down until apache is manually restarted 

### Server configuration
**Operating system**: CentOS 7.2

**Web server:** Apache 2.4
 
**Database:** MariaDB 10.1

**PHP version:** PHP 5.6

**ownCloud version:** 9.1.1

**Updated from an older ownCloud or fresh install:** Fresh Install

**Where did you install ownCloud from:** Owncloud.com

**Signing status (ownCloud 9.0 and above):** 9.1.1

**List of activated apps:**

Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.6
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1

**The content of config/config.php:**

{
    "system": {
        "instanceid": "oc2znqqhj8qc",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.123.230"
        ],
        "log_type": "owncloud",
        "logfile": "\/var\/log\/owncloud.log",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\PDF"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.123.230\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.1.3",
        "dbname": "owncloud438",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** local

### Client configuration
**Browser:** Chrome

**Operating system:** Win 10

**Comment by PVince81** [comment]
There is no possible quick fix for this. If a preview takes too long to create, then the PHP timeout should kill the process at some point. Ideal would be to have a separate process to create previews as discussed in: https://github.com/owncloud/core/issues/11685

Closing in favor of https://github.com/owncloud/core/issues/11685

**Comment by RealRancor** [comment]
From https://central.owncloud.org/t/file-previews-cause-cpu-choke/3528:

> Figured out the problem, this isn't an issue with OC. Turn's out I had ImageMagick 6.7 installed, default shipped with CentOS. Tried converting a PSD to PNG via command line and experienced the same issue.
> 
> Upgraded to ImageMagick7 using remi's repo and everything's working dandy now.
