### ISSUE TITLE
OCP alternative to toTmpFile ?

### ISSUE THREAD

**Issue by Rello** [owncloud/core#26470]
in Audioplayer I was using:

> $userView =  new View('/' . $this -> userId . '/files');
> ...
> $fileName = $userView->toTmpFile($audio['path']);
> unlink($fileName);

but I learned that it is dependent on `\OC\Files\View` which I am not supposed to use.

Alternative is to use `\OCP\Files\IRootFolder` 

> $userView = $this->rootFolder->getUserFolder($this -> userId);
> ...
> $fileName = $userView->toTmpFile($audio->getPath());

but toTmpFile is not available.

Why did I use toTmpFile?
because $userView->getLocalFile($audio['path']) created tmp files for everything on external storage (e.g. SMB).
But these were only cleaned up after the session finished so the tmp folder was flooded with 1000s of files for big libraries.

Is there a better approach?
is there a getLocalFile() alternative in IRootFolder?

https://github.com/Rello/audioplayer/blob/820f651f16e9777aadb12f24ec064f5206377797/controller/scannercontroller.php#L543-L554

**Comment by PVince81** [comment]
I browsed through the source code and there might be a way to call `getLocalFile()` on the storage:

```php
    $userFolder = $this->rootFolder->getUserFolder($this->userId);
    $audioFile = $userFolder->get('path/to/audio.ogg');
    // get the storage on which the audio file is on
    $audioFileStorage = $audioFile->getStorage();
    // call getLocalFile using the internal path (which is relative to the storage root)
    $audioFileStorage->getLocalFile($audioFileStorage->getInternalPath());
```

I suppose it should be possible to add `getLocalFile()` directly on the `File` interface and do all of this internally in the future.

Hope this helps :smile:

**Comment by Rello** [comment]
I somehow cant get your approach to work:

```
$userView = $this->rootFolder->getUserFolder($this -> userId);
$audios = $userView->searchByMime('audio/mpeg');
foreach($audios as $audio) {
$audioFile = $userView->get($audio->getPath());
...

```
I get the path from the $audios object - but this can not be sued in your suggestion.
it will return a final file called `/Admin/files/Admin/files/defect-image.mp3`

but even if I get all the objects right - it does not solve the issue that I specifically need to know the TMP-File to clean in up again, correct?

**Comment by PVince81** [comment]
Ah, I think `searchByMime` already gives you `File` objects, so no need to call `$userView->get` on them.

Hmm, if the problem you're trying to solve is clearing the temp files, then it might be a core issue then.
I don't think it's an app's responsibility to care about whether a file is read from temp space or directly from storage.

And you say the clearing only happens at session end, which is too late. Hmm...
I wonder whether it was always like this or whether it is related to your specific use case, streaming.

One problem I see with streaming and temp files is as follows: from what I remember, the JS library will not always read the whole file but issue range requests. For example requests the first 1MB then when reaching the end of that block it would request the next 1MB. If the temp file gets deleted between the two requests, then it means that file needs to be redownloaded from whatever storage it is on for every block. So there is an advantage to having such temp files living a bit longer, at least for streaming.

Maybe a proper solution would be to have some kind of timeout mechanism: if a temp file wasn't used for more than X minutes, then delete it.

**Comment by PVince81** [comment]
Looking at the TempManager and the `toTmpFile` function, it looks like there is no explicit logic to clean up temporary files at the end of the session. I only see the usage of `tempnam`: https://github.com/owncloud/core/blob/v9.1.2RC2/lib/private/TempManager.php#L88. Looking at the PHP docs it doesn't look like such files would be deleted automatically.

I see some code in `TempManager` like `cleanOld` but it doesn't seem to be used anywhere else.

Ok, so it seems that it would require some API changes to introduce new temp file APIs that is able to track how often the same temp file was opened. Would require having a call that does the `fopen` itself.

Let's go back to the short term then, achieving what you wanted: delete the temp file inside the app:

> but even if I get all the objects right - it does not solve the issue that I specifically need to know the TMP-File to clean in up again, correct?

If you call `getLocalFile()` on the storage instance it should return the full path to the temporary file, so you'll should be able to delete it afterwards. Let me know if that doesn't work.

**Comment by Rello** [comment]
what am I missing here? still trying to combine all your information:

```
$userView = $this->rootFolder->getUserFolder($this -> userId);
$audios = $userView->searchByMime('audio/mpeg');
foreach($audios as $audio) {
$audioFile = $userView->get($audio);
$audioFileStorage = $audioFile->getStorage();
$fileName = $audioFileStorage->getLocalFile($audioFileStorage->getInternalPath());
$ThisFileInfo = $getID3->analyze($fileName);
```

your remark regarding getLocalFile() could work - as long as I check for external/encrypted status.
if not, I would also unlink a non-temp-file

**Comment by Rello** [comment]
by the way: for the getID3 to work, I don´t need the Local File, but the `getInternalPath`
but this is also not an option of `\OCP\Files\Node`.
also missing - same as toTmpFile.

```
getLocalFile: /var/owncloud/Admin/files/Admin/files/defect-image.mp3
getInternalPath: files/defect-image.mp3
```

do you have another suggestion to get the internal path via iRootFolder?

**Comment by Rello** [comment]
Hello @PVince81 
thank you for your help. I managed to transfer everything to OCP.

here is what I have done:

```
use \OCP\Files\IRootFolder;
$this->rootFolder = $rootFolder;
$userView = $this->rootFolder->getUserFolder($this -> userId);
$audios = $userView->searchByMime('audio/mpeg');
foreach($audios as $audio) {
			$fileName = $audio->getStorage()->getLocalFile($audio->getInternalPath());				
			$ThisFileInfo = $getID3->analyze($fileName);
			if (!$audio->getStorage()->isLocal($audio->getInternalPath())) {
				unlink($fileName);
			}
...
```

The isLocal is important to only delete tmp-files and not correct/local ones...
Any objections? :-)

it still creates the Temp-Files für external files, which is **really** slow.
I was talking to icewind already to avoid this and he was proposing some stream setup. But I could not get it done.
Any Idea?

**Comment by PVince81** [comment]
Hmm, your original question about an alternative to `toTmpFile`. As far as I know this is what `getLocalFile` does. Both approaches are of course slow with external storages because it needs to download the whole file.

If your purpose here is only to analyze the id3 you might need to find an id3 library that can work with streams. If you have one, then instead of using `getLocalFile` you can simply do a `fopen()` on the file and pass the stream to the id3 library. When using `fopen()`, most external storages will deliver a stream when possible (and fallback to a temp file when not)

**Comment by PVince81** [comment]
@Rello for dev questions please send posts to central in the future and ping me there as @PVince81. Thanks
