### ISSUE TITLE
Disable old update server

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#26492]
Seems there are still old versions of oC floating around which are using the URL to the old update server http://apps.owncloud.com/updater.php like seen in https://github.com/owncloud/core/issues/26491

This update server is currently providing 8.2.1 for all users like seen in the link or when requesting:

https://apps.owncloud.com/updater.php?version=8x0x0x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00

To avoid such issues please disable the old http://apps.owncloud.com/updater.php server which is not providing the step by step upgrades like the new server.

**Comment by DeepDiver1975** [comment]
@jnweiger 
Maybe we perform a redirect to the new server?

**Comment by RealRancor** [comment]
Might be another possibility. Might be possible to to some rewrites from:

https://apps.owncloud.com/updater.php?version=8x0x0x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00

to

https://updates.owncloud.com/server/?version=8x0x0x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00


Seems also that:

https://api.owncloud.com/updater.php?version=8x0x0x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00

is also having the old update server. Don't know if this URL was also used in a few other older releases?

**Comment by PVince81** [comment]
@VicDeo

**Comment by VicDeo** [comment]
@PVince81 I have no ssh access there

**Comment by PVince81** [comment]
@VicDeo I pinged you because I seem to remember that you already mentionned the redirect approach before.

For ssh access need to ask @jnweiger @crrodriguez

**Comment by jnweiger** [comment]
@VicDeo I've placed your github ssh-key into oc@api.owncloud.com

Please log in there and find the symbolic link updater.php 
This file controls both,
* https://apps.owncloud.com/updater.php and 
* https://api.owncloud.com/updater.php

**Comment by VicDeo** [comment]
@jnweiger thanks!

**Comment by VicDeo** [comment]
@PVince81 an old update server queries a new one now.

**Comment by RealRancor** [comment]
Confirmed by testing the posted links above so closing here for now. Thanks for fix :+1:
