### ISSUE TITLE
online upgrade to 8.2.1 failed

### ISSUE THREAD

**Issue by geohei** [owncloud/core#26491]
Hi.

I triggered a 7.x upgrade to 8.2.1 today.

I used the admin account on the web interface.

Step 1-3 went fine, but the database upgrade failed.

Here the messages:

```
ownCloud will be updated to version 8.2.1
These apps will be updated:

    Activity (activity)
    Files (files)
    External storage support (files_external)
    PDF Viewer (files_pdfviewer)
    Share Files (files_sharing)
    Text Editor (files_texteditor)
    Deleted files (files_trashbin)
    Versions (files_versions)
    Gallery (gallery)
    Updater (updater)

Please make sure that the database, the config folder and the data folder have been backed up before proceeding.
To avoid timeouts with larger installations, you can instead run the following command from your installation directory:

./occ upgrade
```

```
Updating ownCloud to version 8.2.1, this may take a while.

Preparing update
Set log level to debug - current level: "Debug"
Turned on maintenance mode
Exception: Updates between multiple major versions and downgrades are unsupported.
The update was unsuccessful. Please report this issue to the ownCloud community.`

```

What else do you need?

**Comment by RealRancor** [comment]
@geohei Please note this is a bugtracker and no support forum. Instead please use https://central.owncloud.org/ for that.

As the seen issue is a limitation in older versions like oC7 which are unsupported you won't get a fix for that and you could close this issue.

At central there is a FAQ item explaining the needed steps how to do a correct upgrade:

https://central.owncloud.org/t/updates-between-multiple-major-versions-and-downgrades-are-unsupported/815

**Comment by geohei** [comment]
Thanks for the answer.

I believe my initial this was oC 8.0.4.
I considered this as a bug since the web interface Updater suggested upgrade to 8.2.1, which failed.
I posted into the forum.

**Comment by RealRancor** [comment]
@geohei No need, the old update server providing this upgrade path to 8.2.1 was disabled based on the discussion in https://github.com/owncloud/core/issues/26492

Such outdated instances are also now getting the step-by-step updated without the dangerous to skip a major release. I think you could close this for now.

**Comment by PVince81** [comment]
@VicDeo can you confirm that this is solved, then close ?

**Comment by VicDeo** [comment]
https://apps.owncloud.com/updater.php?version=8x0x0x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00
offers 8.0.16 for 8.0.0

https://apps.owncloud.com/updater.php?version=8x0x16x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00
https://apps.owncloud.com/updater.php?version=8x1x1x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00
offers 8.1.11 for 8.0.16 and 8.1.1 

https://apps.owncloud.com/updater.php?version=8x1x11x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00
https://apps.owncloud.com/updater.php?version=8x2x0x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00
offers 8.2.9 for 8.1.11 and 8.2.0

Everything is correct.
