### ISSUE TITLE
ownCloud adds "(2)" to shared folders

### ISSUE THREAD

**Issue by XjeEDK** [owncloud/core#26497]
### Steps to reproduce
1. user1 share folder to user2

### Expected behaviour
user2 should see the shared folder from user1 with the correct name

### Actual behaviour
for user 2: every week (2) is added. for example after 3 weeks "folder (2) (2) (2)"
for user 1: folder name does not change.

### Server configuration
**Operating system**: CentOS Linux release 7.2.1511 (Core)

**Web server:** Apache 2.4.6-40.el7.centos.4

**Database:** MariaDB 5.5.50-1.el7_2

**PHP version:** 5.4.16-36.3.el7_2

**ownCloud version:** ownCloud 9.1.0 (stable)

**Updated from an older ownCloud or fresh install:** Maybe updated from 8. Not sure.

**Where did you install ownCloud from:** rpm, epel repository

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**
Activity
Collaborative tags
Comments
Deleted files
Federation
First run wizard
Gallery
LDAP user and group backend
Mail Template Editor
Notifications
PDF Viewer
Provisioning API
Share Files
Text Editor
Update notification
Versions
Video player

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'oco9kxowi56v',
  'trusted_domains' =>
  array (
    0 => 'xyz.net',
  ),
  'datadirectory' => '/data',
  'overwrite.cli.url' => 'http://xyz.net/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.0.15',
  'dbname' => 'dbname',
  'dbhost' => 'dbhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'dbuser',
  'logtimezone' => 'UTC',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'trashbin_retention_obligation' => '10, auto',
  'ldapUserCleanupInterval' => 10,
  'loglevel' => 2,
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Firefox / Chrome

**Operating system:** Windows 7

**Comment by RealRancor** [comment]
> ownCloud version: ownCloud 9.1.0 (stable)

From the issue template you have filled out:

> Before reporting any issues please make sure that you're using the latest available version for your major branch (e.g. 9.0.x), see https://owncloud.org/changelog/

In your case 9.1.1 is current which already has fixed this issue as seen in: https://github.com/owncloud/core/issues/24575

**Comment by PVince81** [comment]
It's more likely to be https://github.com/owncloud/core/issues/25718 especially since you're using LDAP. You can either try updating to 9.1.2RC2, wait for 9.1.2 final or patch your setup https://github.com/owncloud/core/issues/25718#issuecomment-255763344
