### ISSUE TITLE
Remove files_move from appstore

### ISSUE THREAD

**Issue by RealRancor** [owncloud/core#26503]
Hi,

the files_move app (https://apps.owncloud.com/content/show.php/Files+move?content=150271) is known to cause various bugs like explained at:

 owncloud/gallery#701, owncloud/gallery#699, owncloud/gallery#702, https://github.com/eotryx/oc_files_mv/pull/29#issuecomment-252847925, https://github.com/eotryx/oc_files_mv/issues/27 (and some other issues).

As the app developer seems to not getting active to include an already provided fix: https://github.com/eotryx/oc_files_mv/pull/29 i would suggest to remove that app from the appstore for now. This prevents that people are installing that app on newer oC versions and breaking their instance with that.

One additional issue is that the app itself is not enforcing an upper version in its info.xml:

https://github.com/eotryx/oc_files_mv/blob/master/appinfo/info.xml#L13

so oC9.1 user are e.g. also getting updates which breaks gallery, documents and maybe also other apps and functionalities of oC.

**Comment by PVince81** [comment]
@DeepDiver1975 @felixboehm what do you think ?

**Comment by PVince81** [comment]
Doesn't the app store also have a field to set max version, maybe if we just set the value there the app store will stop delivering the app for future versions ?

On the other hand people who already have the app enabled might still suffer from the problem due to incomplete info.xml

**Comment by RealRancor** [comment]
The files_mv app has set a maximum required: ownCloud 9.0 but that doesn't solve the issue that:

- people who already have the app enabled might still suffer from the problem due to incomplete info.xml
- people are still able to download and activate that app from the appstore manually due to the incomplete info.xml

**Comment by DeepDiver1975** [comment]
As first action I remove the approved state of the app - it will be listed as experimental app for now.

**Comment by PVince81** [comment]
I guess that should be enough for now, closing
