### ISSUE TITLE
Add an option for allowing or not autocompletion in the email field dialog when sharing.

### ISSUE THREAD

**Issue by voundaries** [owncloud/core#26504]
When "Allow users to send mail notification for shared files" option is enabled on the settings, it shows the email field for link sharing.

When typing the email address for sharing, it autocompletes and also shows other users' id's and addresses registered on the server. This leaks info to admins and other users.

As mentioned by @xshadow on issue #24872 :

It would be nice to have the following features:

Give the administrators the opportunity to globally disable username autocompletion on sharing (in config/config.php)
Give the user the possibility to decide if he/she wants to be found or not (in the user settings)

Or
**Add an option for allowing or not autocompletion in the email field dialog when sharing.**

**Comment by PVince81** [comment]
Hmm, I think this should be made part of the existing option "Allow username autocompletion in share dialog. If this is disabled the full username needs to be entered."

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/issues/26559

**Comment by PVince81** [comment]
The PR doesn't add a new option but reuses the existing one to also exclude email completion, that should be enough.
