### ISSUE TITLE
ownCloud server (& client), request: File locked by [User]

### ISSUE THREAD

**Issue by victorbw** [owncloud/core#26505]
Hi everybody

Are there any plans of letting ownCloud-sync-clients be able to lock down files (mostly usual documents) when somebody else is already manipulating it?

Well, i know there are other collaboration-tools out there, but wouldnt his be a nice feature for instances where a lot people are working on the same documents without having issues not being able to track changes?

I was thinking about something like this behaviour on the ownCloud-client and servers (some sort of pseudo-code/process):

```
1. ownCloud server setting: lock file on sync-client when in use

2. ownCloud sync-client: when opening file, check if not locked by other sync-client (db-entry)

3. if NOT locked, open document -> lock document with db-entry on server-side (first come - first serve)

4. if LOCKED, message: "document is in use by [user]

5. when document closed AND successfully synced, release lock on server
```

im sadly not good enough in php nor mysql to contribute some sort of satisfying code :(

best regards

**edit: formatting

**Comment by RealRancor** [comment]
@victorbw It might be possible that your request is matching this existing feature request: https://github.com/owncloud/core/issues/20983
