### ISSUE TITLE
Signature by key uses weak digest algorithm (SHA1)

### ISSUE THREAD

**Issue by ajn142** [owncloud/core#26500]
### Steps to reproduce
1. Navigate to https://download.owncloud.org/download/repositories/stable/owncloud/
2. Follow instructions under the heading Ubuntu_16.04 owncloud-9.1.1-1.2, listed below.

`wget -nv https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/Release.key -O Release.key`

`apt-key add - < Release.key`

`sh -c "echo 'deb http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ /' > /etc/apt/sources.list.d/owncloud.list"`

`apt-get update`
### Expected behaviour

apt-get update should run cleanly, with no error related to the addition of the ownCloud repository
### Actual behaviour

Error below is received.
`W: http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/Release.gpg: Signature by key DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B uses weak digest algorithm (SHA1)`
### Server configuration

**Operating system**:
Ubuntu 16.04.1

**ownCloud version:** (see ownCloud admin page)
Ubuntu_16.04 owncloud-9.1.1-1.2

**Updated from an older ownCloud or fresh install:**
Fresh Install

**Where did you install ownCloud from:**
https://download.owncloud.org/download/repositories/stable/owncloud/

**Signing status (ownCloud 9.0 and above):**
Unsure

At this point I haven't included anything below, in largely because I haven't gotten that far in the installation and setup process. I saw some reference to this happening if you had an old key installed, but this is my first time installing ownCloud, on a relatively fresh install of 16.04.1, and once I saw reference to that, I removed the key and tried the process again, but the issue continued to occur.

**Comment by PVince81** [comment]
@owncloud/packaging

**Comment by RealRancor** [comment]
Most likely the common issue that people are either importing the wrong key or they have some older previously imported key and their import is not overwriting them.

@ajn142 

Make sure that you have removed all previous keys shown with:

apt-key list

**Comment by ajn142** [comment]
@RealRancor 
Can you tell me where I would locate the correct key, if it is not the one listed in the procedure on the https://download.owncloud.org/download/repositories/stable/owncloud/ page? I've already cleared that key and retried once, with the same result (which was somewhat expected, given that I was going through the same steps). Again, my first time encountering the issue was the first time `apt-get update` was run after installing the key.

I'd like to get it taken care of on my end, and more importantly, get the steps on that page updated if needed so that no one else following the official documentation runs in to the same error.

**Comment by RealRancor** [comment]
@ajn142 Please read my complete reply. If you had imported the weak-signed key previously you can import the key tons of times and it won't solve your issue.

**Comment by ajn142** [comment]
@RealRancor 

I did read your complete reply. I have already deleted the key found at https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/Release.key using `apt-key del` and then verified the key was removed by using `apt-key list`. As you stated, this resolved the issue with the warning received in the intial bug report. However, this is the only key the documentation for installing on Ubuntu 16.04 lists. If I import it again, the same issue occurs, as expected. I did this to ensure that the documentation I was following was incorrect, rather than a mistake in following the documentation on my part causing this issue.

It's obvious at this point that I need to remove this key again, and import the correct key. What is not obvious, based on the official documentation found at https://download.owncloud.org/download/repositories/stable/owncloud/, is what the correct key is. I'd like to know that, and to save anyone else the trouble of encountering this issue and filing a bug report for it, wasting both your time and theirs, I'd like to see the documentation corrected if possible.

**Comment by RealRancor** [comment]
The documentation is correct and importing the https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/Release.key on a Ubuntu 16.04 system doesn't show your mentioned issue.

**Comment by ajn142** [comment]
That's very strange. I am going to repeat these steps again, and I'll be happy to provide a full transcript of the shell session I do it in. Maybe I'm just losing my mind here.

**Comment by RealRancor** [comment]
Just remembered that one user reported that this is a limitation of ubuntu as the repo is cached somehow. 

> I was able to fix it by removing the package source, followed by running apt-get update. After adding the source again, everything installed fine. Weirdly just running apt-get clean instead, which I thought does the same, did not fix my issue.

https://github.com/owncloud/client/issues/5055#issuecomment-255063655

Thats the reason why i had pointed you to a ubuntu community which can help a way better with such stuff.

**Comment by ajn142** [comment]
And it's still happening for me. Maybe I'm making a mistake here that I'm not catching, but at this point I'm fairly confident i'm following the documentation on that page to a T. Here's a copy of the session below.

root@server:/home/user# apt-key list
/etc/apt/trusted.gpg
    --------------------
pub   1024D/437D05B5 2004-09-12
uid                  Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>
sub   2048g/79164387 2004-09-12

pub   1024D/FBB75451 2004-12-30
uid                  Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>

pub   4096R/C0B21F32 2012-05-11
uid                  Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>

pub   4096R/EFE21092 2012-05-11
uid                  Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>

pub   2048R/479BC94B 2013-08-26 [expires: 2018-08-25]
uid                  ownCloud build service <obsrun@localhost>
sub   2048R/8DE365D9 2013-08-26 [expires: 2018-08-25]
sub   2048D/86EB6027 2013-08-26 [expires: 2018-08-25]
sub   2048g/1722EF54 2013-08-26 [expires: 2018-08-25]

root@server:/home/user# apt-key del 479BC94B
OK
root@server:/home/user# apt-key list
/etc/apt/trusted.gpg
    --------------------
pub   1024D/437D05B5 2004-09-12
uid                  Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>
sub   2048g/79164387 2004-09-12

pub   1024D/FBB75451 2004-12-30
uid                  Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>

pub   4096R/C0B21F32 2012-05-11
uid                  Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>

pub   4096R/EFE21092 2012-05-11
uid                  Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>

root@server:/home/user# wget -nv https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/Release.key -O Release.key
2016-10-27 18:15:41 URL:https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/Release.key [4502/4502] -> "Release.key" [1]
root@server:/home/user# apt-key add - < Release.key
OK
root@server:/home/user# apt-key list
/etc/apt/trusted.gpg
    --------------------
pub   1024D/437D05B5 2004-09-12
uid                  Ubuntu Archive Automatic Signing Key <ftpmaster@ubuntu.com>
sub   2048g/79164387 2004-09-12

pub   1024D/FBB75451 2004-12-30
uid                  Ubuntu CD Image Automatic Signing Key <cdimage@ubuntu.com>

pub   4096R/C0B21F32 2012-05-11
uid                  Ubuntu Archive Automatic Signing Key (2012) <ftpmaster@ubuntu.com>

pub   4096R/EFE21092 2012-05-11
uid                  Ubuntu CD Image Automatic Signing Key (2012) <cdimage@ubuntu.com>

pub   2048R/479BC94B 2013-08-26 [expires: 2018-08-25]
uid                  ownCloud build service <obsrun@localhost>
sub   2048R/8DE365D9 2013-08-26 [expires: 2018-08-25]
sub   2048D/86EB6027 2013-08-26 [expires: 2018-08-25]
sub   2048g/1722EF54 2013-08-26 [expires: 2018-08-25]

root@server:/home/user# apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [95.7 kB]
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]
Ign:4 http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  InRelease
Hit:5 http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  Release
Get:6 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease [92.2 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu xenial-updates/main Sources [201 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe Sources [107 kB]
Get:10 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [414 kB]
Get:11 http://us.archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages [408 kB]
Get:12 http://security.ubuntu.com/ubuntu xenial-security/main Sources [43.9 kB]
Get:13 http://us.archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [159 kB]
Get:14 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [356 kB]
Get:15 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe i386 Packages [353 kB]
Get:16 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [158 kB]
Get:17 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [128 kB]
Get:18 http://security.ubuntu.com/ubuntu xenial-security/main i386 Packages [154 kB]
Get:19 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [51.9 kB]
Get:20 http://security.ubuntu.com/ubuntu xenial-security/universe i386 Packages [51.8 kB]
Fetched 2,868 kB in 1s (1,874 kB/s)
Reading package lists... Done
W: http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/Release.gpg: Signature by key DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B uses weak digest algorithm (SHA1)

**Comment by ajn142** [comment]
> Just remembered that one user reported that this is a limitation of ubuntu as the repo is cached somehow.

>>I was able to fix it by removing the package source, followed by running apt-get update. After adding the source again, everything installed fine. Weirdly just running apt-get clean instead, which I thought does the same, did not fix my issue.
owncloud/client#5055 (comment)

>Thats the reason why i had pointed you to a ubuntu community which can help a way better with such stuff.

I never found reference to that. Let me try it again with that added step, hopefully that will fix it and leave things a bit clearer for everyone.

**Comment by RealRancor** [comment]
@ajn142 See my reply few seconds after yours. If that isn't working please follow:

> You might want to get some help from a Ubuntu community why your system is showing issues others similar / same don't have.

There is nothing wrong with the signature of the repository and you really should ask for support from some ubuntu guys.

**Comment by ajn142** [comment]
I've tried the steps listed in your reply, with no change in behavior noted. I'm also seeing the same behavior on a freshly installed machine that I brought up just to test this. On the second machine, I used the instructions at https://download.owncloud.org/download/repositories/stable/owncloud/, found by clicking on the Ubuntu logo, underneath the heading Ubuntu_16.04 owncloud-9.1.1-1.2. Again, this second machine was installed just to test this, has never been used for anything before, and I'll be taking it down as soon as I resolve this. I understand that you believe the issue was related to my one server in particular, or a quirk of Ubuntu when the old certificate has been installed, but from my end, this doesn't seem to be the case.

The one thing I seem to see consistently among all of the bug reports you have linked is that the individuals reporting fixed are installing from the repository at http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/ and not the repository at https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/. Unless I'm misunderstanding something here, the repository at the openSUSE site is for the owncloud-client package, while the one at the ownCloud site is for the normal owncloud package that I would run on my server.

I believe a relevant comment by another user and yourself can be found at the following links, respectively.
https://github.com/owncloud/client/issues/5055#issuecomment-249481928
https://github.com/owncloud/client/issues/5055#issuecomment-249485789

I can't seem to locate any follow up to either of those regarding a new key being added for the repository at https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/.

**Comment by ajn142** [comment]
And I stand corrected, I did locate your updates to the certificate in: https://github.com/owncloud/owncloud.org/pull/1079

I still note the pattern that the only people who have this issue are using the https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ repository, and none of them have reported it as being fixed, but I can't seem to make heads or tails of the root cause. I can't find anything with Ubuntu that would cause this, and so far the help I've sought with their community support hasn't turned up anything. At this point, I think I'm going to give up on using the packages, and just install by tarball. Perhaps at some point someone on one end or the other will find what is causing your repository to throw this error, and I can move to the packages then.

**Comment by RealRancor** [comment]
Ok, that is really wired. I was also able to re-produce this now against the stable repository. It seems something got changed in between since my last test and the repositories are now signed again with a weak signature.

@jnweiger Did something actually changed at the OBS instance at https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ to get to this state back?

**Comment by Kawohl** [comment]
@crrodriguez @jnweiger

**Comment by Kawohl** [comment]
@crrodriguez @jnweiger

**Comment by crrodriguez** [comment]
All the signature problems were, as far as I know.. fixed already.
