### ISSUE TITLE
Version tab view enhancements

### ISSUE THREAD

**Issue by mjobst-necls** [owncloud/core#26510]
### Steps to reproduce
1. Go to Details for any file which has at least two versions.
2. The file size on version tab is not shown and the favourite button does not seem to be clickable because the opacity doesn't change on mouse over.
### Expected behaviour

The file size of each version should be shown.
The favourite "star" button should change its opacity on mouse over. 
Have a look at the screenshot below for further information.
### Actual behaviour

The file size of each version is not shown.
The favourite "star" button does not change its opacity on mouse over.
### Server configuration

**Operating system**:
Doesn't matter

**Web server:**
Doesn't matter

**Database:**
Doesn't matter

**PHP version:**
Doesn't matter

**ownCloud version:** (see ownCloud admin page)
Any version

**Updated from an older ownCloud or fresh install:**
Doesn't matter

**Where did you install ownCloud from:**
Doesn't matter

**Signing status (ownCloud 9.0 and above):**
Doesn't matter

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Webdav
### Client configuration

**Browser:**
Internet Explorer 8, Current Google Chrome, Current Firefox

**Operating system:**
Windows 7, Ubuntu 16.04
#### Web server error log

Doesn't matter
#### ownCloud log (data/owncloud.log)

Doesn't matter
#### Browser log

No error reported.
#### Screenshot

![screenshot from 2016-10-29 21-51-33](https://cloud.githubusercontent.com/assets/23121972/19832381/cd3e945c-9e22-11e6-83b7-57f7da282afb.png)

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/core/issues/26511
