### ISSUE TITLE
Directories and files with special characters

### ISSUE THREAD

**Issue by jmoudy** [owncloud/core#26521]
I have an OwnCloud made from the appliance Ubuntu_14.04-owncloud-9.1.1-1.1-201609201317.ova

I pointed it to a local file system that has an lot of existing data. I found numerous errors issuing a occ files:scans command. One of those is below. The actual file name is: Verdi - Rigoletto- É il sol dell'anima.mp3

 Entry "/admin/files/Local/Music/iTunes/Music/Verdi - Rigoletto- ▒ il sol dell'anima.mp3" will not be accessible due to incompatible encoding

I found it was even less tolerant of the single quote char in the directory names like Hits From the '80s .

I saw that other bugs, like bug 959 referenced something like this, but they were old closed bugs. Am I missing something simple here?

This is fairly easy to recreate so I'm happy to provide more info.

**Comment by jmoudy** [comment]
The filesystem I was accessing was a CIFS filesystem mounted from a different machine. 

I added the iocharset=utf8 option on mount (which also required installing linux-generic to the appliance) and now things are playing nicely.

**Comment by arpadox** [comment]
Stumbled upon this same issue whilst scanning 
`sudo -u www-data php7.0 occ files:scan --all`
a CIFS-mounted folder (fstab entry follows)
`//192.168.1.254/disk_1/STORAGE/sub2/  /var/www/owncloud/data/adminuser/files/     cifs    guest,iocharset=utf8,uid=33,gid=33,rw,file_mode=0750,dir_mode=0750,noperm 0 0`
Where uid 33 is www-data.

Error:

`Starting scan for user 1 out of 1 (adminuser)
stat: cannot stat '/var/www/owncloud/data/adminuser/files/mydisk/Programma di contabilit': No such file or directory
Exception during scan: ErrorException: Undefined index: size
#0 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(421)...`

Error output ellipsized. Problematic folder name should be "Programma di contabilità".

Renaming this folder causes a different error in a different dir:

`/files/mydisk/sub90/Animazioni e curiosit': No such file or directory
stat: cannot stat '/var/www/owncloud/data/adminuser/files/mydisk/sub90/Animazioni e curiosit/ppl.gif': No such file or directory
stat: cannot stat '/var/www/owncloud/data/adminuser/files/mydisk/sub90/Animazioni e curiosit/ppl.gif': No such file or directory
stat: cannot stat '/var/www/owncloud/data/adminuser/files/mydisk/sub90/Animazioni e curiosit/ppl.gif': No such file or directory
	Entry "/adminuser/files/mydisk/sub90/Animazioni e curiosit�/ppl.gif" will not be accessible due to incompatible encoding
stat: cannot stat '/var/www/owncloud/data/adminuser/files/mydisk/sub90/Animazioni e curiosit/undo.jpeg': No such file or directory
stat: cannot stat '/var/www/owncloud/data/adminuser/files/mydisk/sub90/Animazioni e curiosit/undo.jpeg': No such file or directory
stat: cannot stat '/var/www/owncloud/data/adminuser/files/mydisk/sub90/Animazioni e curiosit/undo.jpeg': No such file or directory
	Entry "/adminuser/files/mydisk/sub90/Animazioni e curiosit�/undo.jpeg" will not be accessible due to incompatible encoding`
...ellipsized...
`Exception during scan: ErrorException: Undefined index: size
#0 /var/www/owncloud/lib/private/Files/Cache/Scanner.php(421)...`

The problematic folder name should be "Animazioni e curiosità".

I already have `iocharset=utf8` in the fstab line, and `default_charset = "UTF-8"` in both /etc/php/7.0/cli/php.ini and fpm's.
