### ISSUE TITLE
SSL certificate problem after upgrade vom 9.0.4 to 9.1.1

### ISSUE THREAD

**Issue by jovobe** [owncloud/core#26537]
### Steps to reproduce
1. Upgrade oc from 9.0.4 to 9.1.1
2.
3.

### Expected behaviour
No errors should occur

### Actual behaviour
After the upgrade the oc log gets spammed with errors about certificate. See error logs section. The problem here is, that there is no information dumped about which certificate is invalid.

### Server configuration
**Operating system**:
Ubuntu 14.04.5 LTS
**Web server:**
Apache/2.4.7 (Ubuntu)
**Database:**
mysql  Ver 14.14 Distrib 5.5.53
**PHP version:**
PHP 5.5.9-1ubuntu4.20
**ownCloud version:** (see ownCloud admin page)
9.1.1
**Updated from an older ownCloud or fresh install:**
9.0.4
**Where did you install ownCloud from:**
https://download.owncloud.org/community/owncloud-9.1.1.tar.bz2
**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - calendar: true
  - comments: 0.3.0
  - contacts: 1.4.0.0
  - dav: 0.2.6
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1

**The content of config/config.php:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.1.1.3",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "forcessl": true,
        "theme": "",
        "loglevel": 2,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "logtimezone": "Europe\/Berlin",
        "logdateformat": "d.m.Y H:i:s",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "filelocking.enabled": "true",
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "mail_smtpport": "587",
        "mail_smtphost": "localhost",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Google Chrome (Version 54.0.2840.71 (64-bit))
**Operating system:**
macOS Sierra (Version 10.12.1)
#### Web server error log
Nothing

#### ownCloud log (data/owncloud.log)
`{"reqId":"REMOVED","remoteAddr":"REMOVED","app":"core","message":"cURL error 60: SSL certificate problem: certificate has expired","level":3,"time":"03.11.2016 10:08:31","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"REMOVED"}
{"reqId":"REMOVED","remoteAddr":"REMOVED","app":"core","message":"cURL error 60: SSL certificate problem: certificate has expired","level":3,"time":"03.11.2016 10:09:43","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"REMOVED"}`

#### Browser log
Nothing

**Comment by PVince81** [comment]
Hmm, it could be that you are receiving federated shares from another server on which the certificate has expired.

**Comment by jovobe** [comment]
@PVince81 Thanks very much! This was exactly the problem. I forgot the share, becuase it wasn't showing up in the web version. I just deleted it from the oc_share_external table and the certificate error logs are gone 👍

**Comment by jovobe** [comment]
@PVince81 Anyhow a better error message would be very helpful.

**Comment by RealRancor** [comment]
@jovobe It would make sense if you create a new feature request for this :-)

**Comment by jovobe** [comment]
@RealRancor Thanks, i'll do it.
