### ISSUE TITLE
Error after Installation with sites

### ISSUE THREAD

**Issue by Kopf02** [owncloud/core#26531]
When I have finished the Setup I instantly get an 404 Not Found error and the URL is http://cloud.URL.eu/index.php/apps/files/ when I remove the index.php I get an 403 Forbidden error. I had also removed all Data and install it again but the error is the same.

### Server configuration
**Operating system**: Debian 8

**Web server:** Nginx

**Database:** MysQL

**PHP version:** 

**ownCloud version:** 9.1.1-1.2

**Updated from an older ownCloud or fresh install:** No

**Where did you install ownCloud from:** Via apt install woncloud and adding the keys before

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
-> Didn't Work :/ 403 Forbidden error

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.6
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocnxya3rrzpc",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.playunity.eu"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/cloud.URL.eu",
        "dbtype": "mysql",
        "version": "9.1.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

### Client configuration
**Browser:** Google Chrome and Firefox

**Operating system:** Windows 10

**Comment by Kopf02** [comment]
Sorry for my Bad English :/

**Comment by RealRancor** [comment]
@Kopf02 Please note this is a bugtracker of ownCloud. Configuration issues / support requests like yours needs to go to https://central.owncloud.org/c/help/oc-server

Before posting there make sure that you're using the nginx config for oC 9 provided at doc.owncloud.org

**Comment by Kopf02** [comment]
@RealRancor Oh Thank You! I'm new srorry.
I will check out the page!

**Comment by PVince81** [comment]
Closing this for now as this looks like a setup issue.
