### ISSUE TITLE
Transfer ownership fails if storage exists with user password

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26530]
### Steps

1. Create two users "user1" and "user2"
1. Setup an external storage "/sftp" with type "SFTP" and pick the mode "Log-in credentials, save in session"
1. Login as "user1" and see that the "/sftp" mount can be accessed
1. Create a local folder "/test" (NOT inside the mount point)
1. Run the transfer ownership command for "user1" to "user2".

### Expected
Only folder "test" (and skeleton files if they were there) was transferred to "user2"

### Actual
Nothing transferred, error during mounting:
```
                                            
  [OCP\Files\StorageNotAvailableException]  
  No session credentials saved              
                                            

                                            
  [OCP\Files\StorageNotAvailableException]  
  No session credentials saved              
                                            

                                                                         
  [OCA\Files_External\Lib\InsufficientDataForMeaningfulAnswerException]  
  No session credentials saved                                           
```

### Versions
Observed on 9.0.5

Unavailable storages must be ignored during transfer.
Even better: any external storages cannot be transferred anyway, so don't bother mounting them!

**Comment by PVince81** [comment]
cc @DeepDiver1975

**Comment by PVince81** [comment]
@Kawohl @cdamken please let me know whether the case from https://github.com/owncloud/core/issues/23881#issuecomment-256600503 shows similar errors to what I posted above.

Fix for this is here: https://github.com/owncloud/core/issues/26533

**Comment by cdamken** [comment]
@PVince81 Sofar I remember the error had nothing to do with the credentials.

The configuration in WND that I have is:
![wnd does not work](https://cloud.githubusercontent.com/assets/7264495/19963848/aeab5a44-a1be-11e6-9826-03c96b05a4a4.PNG)

**Comment by PVince81** [comment]
@cdamken okay, thanks for the details.

I'm able to reproduce the issue, steps:

1. Create two users "user1" and "user2", but never login with those
1. Setup WND with "Log-in credentials, save in database"
1. Transfer files either from "user1" to "user2" or the reverse.

### Expected result
Transfer succeeds

### Actual result
```
# sudo -uwwwrun ./occ files:transfer-ownership user1 user2
Analysing files of user1 ...
    0 [>---------------------------]
                                            
  [OCP\Files\StorageNotAvailableException]  
  No login credentials saved                
                                            

                                            
  [OCP\Files\StorageNotAvailableException]  
  No login credentials saved                
                                            

                                                                         
  [OCA\Files_External\Lib\InsufficientDataForMeaningfulAnswerException]  
  No login credentials saved                                             
```

**Comment by PVince81** [comment]
Tried the same scenario with the fix from https://github.com/owncloud/core/pull/26533 and the error disappears, the transfer completes. Note that the patch doesn't apply on top of OC 9.0 due to file name differences, but we will provide a backport.

**Comment by cdamken** [comment]
@PVince81 is the problem fixed also when the external storage is AWS S3?

**Comment by PVince81** [comment]
@cdamken the fix is independent from storage type, so it should work for S3 as well
