### ISSUE TITLE
SMB/CIFS using OC login - missed 

### ISSUE THREAD

**Issue by sarraceno** [owncloud/core#26544]
Hi!

Did migrated from 8.5 till 9.1.1, and in the end the shares using OC login plugin did not disapear from config, but in the end, they were not working.

After investigation it seems this is being deprecated...
I did try to use same kind of functionality, and is not possible when I try to have a "Folder Name" for share that has login name.

Which was possible with "SMB/CIFS using OC login", if you may remember was provided a check box that told to Owncloud to mount/access to a CIFS share with the name of login/username.

So the issue is a missing functionality, simple one...

Or am I doing some dum action or any requirements may be missing?

My system is Ubuntu Server 14.04, Owncloud 9.1.1, DB is MySQL.

Regards!

**Comment by RealRancor** [comment]
@sarraceno It might help to post a short screenshot what you're actually missing.
