### ISSUE TITLE
7zip issue with owncloud

### ISSUE THREAD

**Issue by VedranOP** [owncloud/core#26545]
### Steps to reproduce
1. Share a folder using using a link
2. User downloads the folder, which is becomes and zip file
3. When user uses 7zip to extract it, he gets a header error. But all seems ok.
No matter what size upload folder and it does not have any special char
4. Using WinRar no error messages and all fine

### Expected behaviour
Extract with no error

### Actual behaviour
Extract with "Headers error"

### Server configuration
Operating system: Ubuntu 16.04
Web server: normal LAMP from Ubuntu installation
Database: normal LAMP from Ubuntu installation
PHP version: normal LAMP from Ubuntu installation
ownCloud version (see ownCloud admin page): ownCloud 9.1.1 (stable)
Updated from an older ownCloud or fresh install: fresh install
Special configuration (external storage, external authentication, reverse proxy, server-side-encryption): no

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
"No errors have been found."
```

**List of activated apps:**
same issue with no additional application

```

### Client configuration
**Browser:**
Any browser

**Operating system:**
Windows any

**Comment by PVince81** [comment]
Are there file names with special characters inside folder ?

**Comment by VedranOP** [comment]
No special unfortunatelly. But I would like to add when I open it in 7zip then go extract and choose folder it is ok. So basically when I use extract right click "shortcuts" I get that error.

**Comment by DeepDiver1975** [comment]
Whats the size of the zip?

**Comment by VedranOP** [comment]
I tried with 1 picture folder and it is the same story. Tired multiple times with various uploaded folders.

**Comment by VedranOP** [comment]
*bump*

**Comment by DeepDiver1975** [comment]
This is basically a known "issue" - some zip tools don't support all specifications of of zip.
Not much we can do -> close
