### ISSUE TITLE
Feature Request: Dropbox like file picker javascript integration

### ISSUE THREAD

**Issue by shyamal890** [owncloud/core#26557]
It would be great to have owncloud file picker integration for webapps.

**Comment by hodyroff** [comment]
Can you give us more detail how this would look like? And how that's different/better compared with using WebDAV from your webapp?

**Comment by PVince81** [comment]
This is something to be developed outside of core, possibly in a separate library.

The good news is that there is now a JS library https://github.com/owncloud/core/issues/13586 that will make it possible to connect to OC from outside with CORS (once https://github.com/owncloud/core/pull/28852 is merged). This would make it possible to develop a file picker, either in the same library or a separate one using js-owncloud-client.

cc @noveens
