### ISSUE TITLE
Cannot delete 'ownCloud Manual.pdf', clean install 9.1.1

### ISSUE THREAD

**Issue by sv13** [owncloud/core#26556]
### Steps to reproduce
1. Try to delete owncloud manual pdf created at first login

### Expected behaviour
File deleted successfully

### Actual behaviour
Error deleting file "ownCloud Manual.pdf".

### Server configuration
**Operating system**:
debian jessie (docker container)
**Web server:**
apache 2.4.10-10+deb8u7
**Database:**
sqlite
**PHP version:**
php-fpm 7.0.12-1~dotdeb+8.1 (apache uses php-fpm unix socket)
**ownCloud version:** (see ownCloud admin page)
9.1.1 (stable)
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/
package: owncloud-files
**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'datadirectory' => '/owncloud_data',
  'updatechecker' => false,
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '9.1.1.3',
  'logtimezone' => 'UTC',
  'installed' => true,
);
```

**Are you using external storage, if yes which one:** no.

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
firefox 48
**Operating system:**
ubuntu 16
#### Web server error log
no errors

#### ownCloud log (data/owncloud.log)
```
Exception: {"Message":"Requested uri (\/owncloud\/remote.php\/webdav\/ownCloud%20Manual.pdf) is out of base uri (\/remote.php\/webdav\/)","Exception":"LogicException","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1225): Sabre\\HTTP\\Request->getPath()\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(454): Sabre\\DAV\\Server->checkPreconditions(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(56): Sabre\\DAV\\Server->exec()\n#4 \/var\/www\/owncloud\/remote.php(164): require_once('\/var\/www\/ownclo...')\n#5 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Request.php","Line":214,"User":"admin"} 
```

### Browser log
when trying to preview pdf, response 500
`Requested uri (/owncloud/remote.php/webdav/ownCloud%20Manual.pdf) is out of base uri (/remote.php/webdav/)`

#  **I can:**
- **delete every other file/directory created at first login**
- upload files, create txt files, create directories and delete all of them
- preview other uploaded pdf's

**Comment by RealRancor** [comment]
@sv13 

> **php-fpm 7.0.12-1~dotdeb+8.1 (apache uses php-fpm unix socket)**

Try to switch your setup to Apache + mod_php (official supported) or nginx + php-fpm (community supported). You're most likely won't get any support for Apache + php-fpm / fastcgi / fcgi et al.

**Comment by sv13** [comment]
@RealRancor 
It appears to work on nginx, I assumed that's not the server side issue, because it was only this one file I couldn't delete.

**Comment by RealRancor** [comment]
@sv13 If it works on nginx then its most likely another bug in apache <-> php-fpm as seen in the past (e.g. https://github.com/owncloud/core/pull/25800)
