### ISSUE TITLE
Drag & Drop folders to itself is causes Could not move message

### ISSUE THREAD

**Issue by mjobst-necls** [owncloud/core#26554]
### Steps to reproduce
1. go to any folder containing a folder
2. drag & drop this folder to itself
3. the error message 'Could not move "%filename%"' appears

### Expected behaviour
The drag & drop of a folder to itself should not trigger any action.

### Actual behaviour
A move action is triggered and the server sends a conflict status

![screencast 2016-11-05 18-54-08](https://cloud.githubusercontent.com/assets/23121972/20032495/5dc08d24-a38b-11e6-8adf-0c24b6d000da.gif)

### Server configuration

**ownCloud version:** (see ownCloud admin page)
v9.1.2, but worked in v8.2.8

### Client configuration
**Browser:**
Chrome and Firefox

**Operating system:**
Ubuntu 16.04

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
jquery.js:5562 GET http://cloud.localhost/core/img/filetypes/folder.png 404 (Not Found)xa @ jquery.js:5562css @ jquery.js:6027(anonymous function) @ jquery.js:6132n.access @ jquery.js:3516css @ jquery.js:6114_createHelper @ jquery-ui.custom.js?v=f26600e…:1766(anonymous function) @ jquery-ui.custom.js?v=f26600e…:405_mouseStart @ jquery-ui.custom.js?v=f26600e…:1565(anonymous function) @ jquery-ui.custom.js?v=f26600e…:405_mouseMove @ jquery-ui.custom.js?v=f26600e…:942(anonymous function) @ jquery-ui.custom.js?v=f26600e…:405_mouseMoveDelegate @ jquery-ui.custom.js?v=f26600e…:914dispatch @ jquery.js:4435r.handle @ jquery.js:4121
client.js?v=f26600e…:181 MOVE http://cloud.localhost/remote.php/webdav/1 409 (Conflict)

**Comment by mjobst-necls** [comment]
I think the best approach is to disable dropping on on the dragging row temporarily.

**Comment by PVince81** [comment]
Fixed by yourself in https://github.com/owncloud/core/issues/26555, thanks!
