### ISSUE TITLE
Still problems with image display

### ISSUE THREAD

**Issue by tcpluess** [owncloud/core#26551]
### Steps to reproduce
I have some photos which are not properly displayed in ownCloud, i.e. the photos have no thumbnail and if the photo is opened, the error "Could not generate a preview of this file" appears. However, the photo can be opened just fine with Paint, Gimp, Photoshop or any other image software.

Link to a such a photo which is not properly displayed:
http://files.kooltek.net/owncloud_fail.jpg

The issue is definitely not related to the size of the images. I have images which are larger (both in number of pixels and/or number of MBytes) which are correctly displayed.

This seems to be related to #21873, which claims to be fixed with OC 9.1.

### Expected behaviour
The preview should appear as for other pictures, and ownCloud should be able to open it to display it in larger size.

### Actual behaviour
No thumbnail created, not possible to open photograph in ownCloud, 

### Server configuration
**Operating system**: CentOS 6.8 (Linux 2.6.32-642.6.2.el6.x86_64 #1 SMP Wed Oct 26 06:52:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)

**Web server:** Apache/2.2.15 (Unix)

**Database:** MySQL 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64)

**PHP version:** PHP 5.6.27 (cli) (built: Oct 15 2016 21:31:59)

**ownCloud version:** ownCloud 9.1.1 (stable)

**Updated from an older ownCloud or fresh install:** updated from 9.0

**Where did you install ownCloud from:** manual (ZIP download, then manual install)

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - audioplayer: 1.2.2
  - comments: 0.3.0
  - dav: 0.2.6
  - direct_menu: 0.9.2
  - documents: 0.13.1
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - bookmarks
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "och5vup3sgqe",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/data\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.1.3",
        "activity_expire_days": 30,
        "versions_retention_obligation": "auto, 30",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Zurich",
        "log_authfailip": true,
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "theme": "",
        "loglevel": 3,
        "maintenance": false,
        "htaccess.RewriteBase": "\/owncloud",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "preview_max_x": 1024,
        "preview_max_y": 768
    }
}
```

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 49

**Operating system:** Windows 7 x64

**Comment by RealRancor** [comment]
> Mhhh, it might be also possible that your system doesn't allow the set PHP configuration parameters via ini_set during runtime and so the workaround introduced in that linked issue doesn't work on your system: https://github.com/owncloud/core/pull/21950/files#diff-3267a2e9d16decfe96b1574917f584dbR476

-> https://central.owncloud.org/t/owncloud-fails-to-display-certain-jpgs/3751/2

**Comment by RealRancor** [comment]
> As mentioned above, if my configuration doesn't allow ini_set during runtime then how to solve?

You (or the support of your hoster) can also set this ``gd.jpeg_ignore_warning`` to ``1`` globally in the php.ini

**Comment by PVince81** [comment]
Environment issue, not solvable from inside ownCloud
