### ISSUE TITLE
can not set speed limit for files from owncloud

### ISSUE THREAD

**Issue by ymg2006** [owncloud/core#26581]
### Steps to reproduce
1.i can set download and rate limit for files with apache2 but it won't apply rules to files from owncloud :
    SetOutputFilter RATE_LIMIT
    SetEnv rate-limit 400
    MaxConnPerIP 16
    Require all granted
i have tested with files directly downloaded and downloading them from owncloud.
would you mind tell me where is own cloud download.php files , and how they downloaded from site/cloud ?

### Server configuration
**Operating system**:
centos 7
**Web server:**
apache 2.4
**Database:**
mariadb
**PHP version:**
7

**Comment by RealRancor** [comment]
@ymg2006 Please note this is a bugtracker for ownCloud. Support questions like this needs to go to https://central.owncloud.org/ (or even better to a apache specific forums like http://www.apachelounge.com/)
