### ISSUE TITLE
[Feature request] per user default app selection

### ISSUE THREAD

**Issue by jadesoturi** [owncloud/core#26580]
Hi.

So, I was wondering if it's possible to add a feature so that users can select a default app in Personal settings.

I know its possible to change it in the config file, but that affects all users. 

Thanks in advance!

//jadesoturi

**Comment by RealRancor** [comment]
> This issue could be closed. It's available with the plugin [https://apps.owncloud.com/content/show.php/AppOrder?content=174715](AppOrder)

https://github.com/owncloud/core/issues/8160#issuecomment-245030873

**Comment by pmaier1** [comment]
I just tested the app. It doesn't let you change the default app/landing page app which was requested here, does it?

**Comment by RealRancor** [comment]
The app page at https://apps.owncloud.com/content/show.php/AppOrder?content=174715 has:

> **0.3.0**
> 
> Set default landing page per user (See README.md for details)

**Comment by pmaier1** [comment]
> The app page at https://apps.owncloud.com/content/show.php/AppOrder?content=174715 has:

    0.3.0

    Set default landing page per user (See README.md for details)

Ok true, needs some config tweaking as explained in README.md though. Closing therefore.
