### ISSUE TITLE
swift external storage fails on ssl openstack endpoint

### ISSUE THREAD

**Issue by stefanost67** [owncloud/core#26596]
The bug I am reporting dates back to owncloud 9.0 (if not before). It also shows up in nextcloud. 
It does not show up when the Swift object storage is accessed through plain http (no SSL). Tested it on multiple Swift platforms know to be working at production level with correctly configured commercial SSL certificates .

### Steps to reproduce
1. Configure Swift external storage over an SSL endpoint
2. upload files
3. download files

### Expected behaviour

Files should be uploaded/downloaded correctly

### Actual behaviour

Files are uploaded/listed correctly
File downloaded from swift client are uncorrupted
File downloaded from owncloud web ui or sync client is a html page. The body content is

"Can't read file"

### Server configuration
**Operating system**:
up-to-date ubuntu 16.04
**Web server:**
apache 2.4.18 (up-to date)
**Database:**
percona-xtradb-cluster-server-5.6
**PHP version:**
PHP 7.0.8-0ubuntu0.16.04.3
**ownCloud version:** (see ownCloud admin page)
9.1.1
**Updated from an older ownCloud or fresh install:**
updated from older (irrelevant)
**Where did you install ownCloud from:**
distribution repository
**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**List of activated apps:**
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: true
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_ldap: 0.9.0

**The content of config/config.php:**
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocqbuteresm7",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "172.16.2.202",
            "localhost",
            "lngs.infn.it",
            "gsbox9-2.lngs.infn.it",
            "gsbox-2.lngs.infn.it",
            "gsbox.lngs.infn.it"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/gsbox.lngs.infn.it\/",
        "dbtype": "mysql",
        "version": "9.1.1.3",
        "dbname": "oc9",
        "dbhost": "172.16.1.167",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 3,
        "log_type": "syslog",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "proxy": "http:\/\/wwwcache.lngs.infn.it:80",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_from_address": "gsbox",
        "mail_domain": "lngs.infn.it",
        "mail_smtphost": "smtp.lngs.infn.it",
        "mail_smtpport": "25",
        "theme": "lngs",
        "htaccess.RewriteBase": "\/",
        "maintenance": false
    }
}
**Are you using external storage, if yes which one:** local/smb/sftp/...
local
S3 (ceph)
swift (would like to)

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)

+-------------------------------+---------------------------------------------------------------------------------------+
| Configuration                 |                                                                                       |
+-------------------------------+---------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                                       |
| hasPagedResultSupport         |                                                                                       |
| homeFolderNamingRule          | attr:uniqueidentifier                                                                 |
| lastJpegPhotoLookup           | 0                                                                                     |
| ldapAgentName                 |                                                                                       |
| ldapAgentPassword             | ***                                                                                   |
| ldapAttributesForGroupSearch  | cn                                                                                    |
| ldapAttributesForUserSearch   | uid;sn                                                                                |
| ldapBackupHost                |                                                                                       |
| ldapBackupPort                |                                                                                       |
| ldapBase                      | ou=cloudstorage,dc=lngs,dc=infn,dc=it                                                 |
| ldapBaseGroups                | ou=groups,ou=cloudstorage,dc=lngs,dc=infn,dc=it                                       |
| ldapBaseUsers                 | ou=accounts,ou=cloudstorage,dc=lngs,dc=infn,dc=it                                     |
| ldapCacheTTL                  | 600                                                                                   |
| ldapConfigurationActive       | 1                                                                                     |
| ldapDynamicGroupMemberURL     |                                                                                       |
| ldapEmailAttribute            | mail                                                                                  |
| ldapExperiencedAdmin          | 0                                                                                     |
| ldapExpertUUIDGroupAttr       | uniqueidentifier                                                                      |
| ldapExpertUUIDUserAttr        | uniqueidentifier                                                                      |
| ldapExpertUsernameAttr        | uniqueidentifier                                                                      |
| ldapGroupDisplayName          | cn                                                                                    |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)))                                                        |
| ldapGroupFilterGroups         |                                                                                       |
| ldapGroupFilterMode           | 1                                                                                     |
| ldapGroupFilterObjectclass    | posixGroup                                                                            |
| ldapGroupMemberAssocAttr      | memberUid                                                                             |
| ldapHost                      | ldaps://ds.lngs.infn.it                                                               |
| ldapIgnoreNamingRules         |                                                                                       |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                       |
| ldapLoginFilterEmail          | 1                                                                                     |
| ldapLoginFilterMode           | 0                                                                                     |
| ldapLoginFilterUsername       | 1                                                                                     |
| ldapNestedGroups              | 0                                                                                     |
| ldapOverrideMainServer        | 0                                                                                     |
| ldapPagingSize                | 500                                                                                   |
| ldapPort                      | 636                                                                                   |
| ldapQuotaAttribute            |                                                                                       |
| ldapQuotaDefault              |                                                                                       |
| ldapTLS                       | 0                                                                                     |
| ldapUserDisplayName           | uid                                                                                   |
| ldapUserDisplayName2          |                                                                                       |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                                                        |
| ldapUserFilterGroups          |                                                                                       |
| ldapUserFilterMode            | 0                                                                                     |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                         |
| ldapUuidGroupAttribute        | auto                                                                                  |
| ldapUuidUserAttribute         | auto                                                                                  |
| turnOffCertCheck              | 0                                                                                     |
| useMemberOfToDetectMembership | 1                                                                                     |
+-------------------------------+---------------------------------------------------------------------------------------+

### Client configuration
**Browser:**
any
**Operating system:**
any
#### Web server error log
none
#### ownCloud log (data/owncloud.log)
{"reqId":"AH1bduDMvtj7aU1zbDu9","remoteAddr":"172.17.22.70","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/3rdparty\/guzzle\/stream\/Guzzle\/Stream\/PhpStreamRequestFactory.php#268","level":3,"time":"2016-11-10T10:05:13+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/download.php?dir=%2Fswift&files=13-Cima_San_Giacomo_Punta_Cerena.pdf&downloadStartSecret=p1z200bzmexty3fkz1l9pb9","user":"admin"}
{"reqId":"AH1bduDMvtj7aU1zbDu9","remoteAddr":"172.17.22.70","app":"no app in context","message":"Exception: {\"Exception\":\"Guzzle\\\\Common\\\\Exception\\\\RuntimeException\",\"Message\":\"Error creating resource.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzle\\\/stream\\\/Guzzle\\\/Stream\\\/PhpStreamRequestFactory.php(218): Guzzle\\\\Stream\\\\PhpStreamRequestFactory->createResource(Object(Closure))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzle\\\/stream\\\/Guzzle\\\/Stream\\\/PhpStreamRequestFactory.php(62): Guzzle\\\\Stream\\\\PhpStreamRequestFactory->createStream(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/Swift.php(377): Guzzle\\\\Stream\\\\PhpStreamRequestFactory->fromRequest(Object(Guzzle\\\\Http\\\\Message\\\\Request))\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(293): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\Swift->fopen('13-Cima_San_Gia...', 'r')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/PermissionsMask.php(111): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('13-Cima_San_Gia...', 'r')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(293): OC\\\\Files\\\\Storage\\\\Wrapper\\\\PermissionsMask->fopen('13-Cima_San_Gia...', 'r')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(317): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('13-Cima_San_Gia...', 'r')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(848): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->fopen('13-Cima_San_Gia...', 'r')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(916): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->readFirstBlock('13-Cima_San_Gia...')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(378): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getHeader('13-Cima_San_Gia...')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(293): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fopen('13-Cima_San_Gia...', 'rb')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1117): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('13-Cima_San_Gia...', 'rb')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(962): OC\\\\Files\\\\View->basicOperation('fopen', '\\\/swift\\\/13-Cima_...', Array, 'rb')\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(425): OC\\\\Files\\\\View->fopen('\\\/swift\\\/13-Cima_...', 'rb')\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/files.php(303): OC\\\\Files\\\\View->readfile('\\\/swift\\\/13-Cima_...')\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/files.php(119): OC_Files::getSingleFile(Object(OC\\\\Files\\\\View), '\\\/swift', '13-Cima_San_Gia...', Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/ajax\\\/download.php(62): OC_Files::get('\\\/swift', '13-Cima_San_Gia...', Array)\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#18 [internal function]: __lambda_func()\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func('\\\\x00lambda_91', Array)\\n#20 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#21 \\\/var\\\/www\\\/owncloud\\\/index.php(39): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/guzzle\\\/stream\\\/Guzzle\\\/Stream\\\/PhpStreamRequestFactory.php\",\"Line\":271}","level":3,"time":"2016-11-10T10:05:13+00:00","method":"GET","url":"\/index.php\/apps\/files\/ajax\/download.php?dir=%2Fswift&files=13-Cima_San_Giacomo_Punta_Cerena.pdf&downloadStartSecret=p1z200bzmexty3fkz1l9pb9","user":"admin"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by hodyroff** [comment]
Swift will be deprecated in favor of full S3 support. Which also works with Swift inside Openstack.
