### ISSUE TITLE
Update from 8.1.0 to 8.2.9 fails during database schema check

### ISSUE THREAD

**Issue by philis** [owncloud/core#26605]
Hey all,
I'm trying to upgrade my 8.1.0 version of OC to the current version. As the instructions ask me to do all mayor releases first, I am trying to go for the 8.2.9. version first.

Here is my failure message. I have copied config.php and data directory to the newly creates oc directory

### Steps to reproduce
sudo -u www-data php occ upgrade

### Expected behaviour
update database for OC 8.2.9

### Actual behaviour
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_oc_share_u70zdmvkomi9u` SELECT * FROM `oc_share`':

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY'
Update failed

### Server configuration
**Operating system**:
SMP Debian 3.16.7-ckt25-2 (2016-04-08)

**Web server:**
Server version: Apache/2.4.10 (Debian)
Server built:   Sep 16 2016 10:02:24

**Database:**
Server-Typ: MySQL
Server Version: 5.5.53-0+deb8u1 - (Debian)
Protokoll-Version: 10

**PHP version:**
PHP 5.6.27-0+deb8u1 (cli) (built: Oct 23 2016 13:05:56)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
8.1.0

**Updated from an older ownCloud or fresh install:**
Trying to upgrade to 8.2.9

**Where did you install ownCloud from:**
.tar.bz2

**Signing status (ownCloud 9.0 and above):**

**List of activated apps:**

{"reqId":"wNMobtJfeciRAjSwVm1J","remoteAddr":"","app":"core","message":"User backend OC_User_IMAP not found.","level":3,"time":"November 10, 2016 22:51:20"}
Enabled:
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - files: 1.1.9
Disabled:
 - activity
 - encryption
 - external
 - files_external
 - files_locking
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_ldap
 - user_webdavauth

**The content of config/config.php:**

{"reqId":"qjEBJaxg4UpAj+JXXWYZ","remoteAddr":"","app":"core","message":"User backend OC_User_IMAP not found.","level":3,"time":"November 10, 2016 22:50:18"}

  [InvalidArgumentException]
  There are no commands defined in the "config" namespace.

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav/Caldav

**Comment by RealRancor** [comment]
Hi,

if you're on 8.1.0 the correct upgrade path would be:

8.1.0 -> 8.1.11 -> 8.2.9

**Comment by philis** [comment]
Hi,

unfortunately the problem is the same when trying to upgrade to 8.1.11

**Comment by philis** [comment]
Any further ideas how to update my OC server?

**Comment by philis** [comment]
Must habe been som SQL issue. I changed the primary key of the affected row ant then the update ran thru.
