### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by ataraxiafr** [owncloud/core#26616]
Hi,

The admin can connect to my cloud but there is an internal error for the other users. In the owncloud logs, I get this:
`Error 	index 	Exception: {"Exception":"OCP\\Files\\NotFoundException","Message":"","Code":0,"Trace":"#0 \/var\/www\/cloud.debian-economist.eu\/lib\/private\/Files\/Node\/Node.php(222): OC\\Files\\Node\\Node->getFileInfo()\n#1 \/var\/www\/cloud.debian-economist.eu\/lib\/private\/Files\/Node\/Node.php(105): OC\\Files\\Node\\Node->getPermissions()\n#2 \/var\/www\/cloud.debian-economist.eu\/lib\/private\/Files\/Node\/Folder.php(139): OC\\Files\\Node\\Node->checkPermissions(4)\n#3 \/var\/www\/cloud.debian-economist.eu\/lib\/private\/Files\/Node\/Root.php(351): OC\\Files\\Node\\Folder->newFolder('\/files')\n#4 \/var\/www\/cloud.debian-economist.eu\/lib\/private\/Server.php(809): OC\\Files\\Node\\Root->getUserFolder('prefpol')\n#5 \/var\/www\/cloud.debian-economist.eu\/lib\/private\/User\/Session.php(384): OC\\Server->getUserFolder('prefpol')\n#6 \/var\/www\/cloud.debian-economist.eu\/lib\/private\/User\/Session.php(438): OC\\User\\Session->prepareUserLogin()\n#7 \/var\/www\/cloud.debian-economist.eu\/lib\/private\/User\/Session.php(287): OC\\User\\Session->loginWithPassword(*** sensitive parameters replaced ***)\n#8 \/var\/www\/cloud.debian-economist.eu\/core\/Controller\/LoginController.php(196): OC\\User\\Session->login(*** sensitive parameters replaced ***)\n#9 [internal function]: OC\\Core\\Controller\\LoginController->tryLogin(*** sensitive parameters replaced ***)\n#10 \/var\/www\/cloud.debian-economist.eu\/lib\/private\/AppFramework\/Http\/Dispatcher.php(159): call_user_func_array(Array, Array)\n#11 \/var\/www\/cloud.debian-economist.eu\/lib\/private\/AppFramework\/Http\/Dispatcher.php(89): OC\\AppFramework\\Http\\Dispatcher->executeController(Object(OC\\Core\\Controller\\LoginController), 'tryLogin')\n#12 \/var\/www\/cloud.debian-economist.eu\/lib\/private\/AppFramework\/App.php(110): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OC\\Core\\Controller\\LoginController), 'tryLogin')\n#13 \/var\/www\/cloud.debian-economist.eu\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php(46): OC\\AppFramework\\App::main('LoginController', 'tryLogin', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#14 [internal function]: OC\\AppFramework\\Routing\\RouteActionHandler->__invoke(Array)\n#15 \/var\/www\/cloud.debian-economist.eu\/lib\/private\/Route\/Router.php(280): call_user_func(Object(OC\\AppFramework\\Routing\\RouteActionHandler), Array)\n#16 \/var\/www\/cloud.debian-economist.eu\/lib\/base.php(891): OC\\Route\\Router->match('\/login')\n#17 \/var\/www\/cloud.debian-economist.eu\/index.php(39): OC::handleRequest()\n#18 {main}","File":"\/var\/www\/cloud.debian-economist.eu\/lib\/private\/Files\/Node\/Node.php","Line":85} 	2016-11-13T23:32:37+00:00 `

I submitted the issue here after I was advised to so on the [ownloud central forum](https://central.owncloud.org/t/index-error-user-can-not-log-in/3630 "Index error: user can not log in").

**Comment by PVince81** [comment]
"external authentifcation" which ? LDAP ?

**Comment by ataraxiafr** [comment]
PVince81, thanks for the tip. I visited the applications and I saw that the application " LDAP user and group backend " was not enabled because there was no library LDAP installed. I installed the package php5-ldap on my debian server. Then, I deleted the user accounts I created with my admin accounts. I restarted apache2 and I created new users. It works now.
