### ISSUE TITLE
Internal Server Error : Session has been closed

### ISSUE THREAD

**Issue by mrbrainin** [owncloud/core#26622]
![cloud](https://cloud.githubusercontent.com/assets/12426363/20262297/9fd10ca4-aa87-11e6-8a09-1399e6267fd0.jpg)

Kindly Support and How to fix this error. 

I am try use some Apps in owncloud. After a few min this error was occur.  

Error Log : `{"reqId":"WCk@1K3tvhUAABf3T@IAAAAf","remoteAddr":"117.218.193.54","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Session has been closed - no further changes to the session are allowed\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/mrbrain\\\/public_html\\\/asbr\\\/lib\\\/private\\\/Session\\\/Memory.php(52): OC\\\\Session\\\\Memory->validateSession()\\n#1 \\\/home\\\/mrbrain\\\/public_html\\\/asbr\\\/lib\\\/private\\\/Security\\\/CSRF\\\/TokenStorage\\\/SessionStorage.php(63): OC\\\\Session\\\\Memory->set('requesttoken', 'PZMbWdFv4Q7WIWl...')\\n#2 \\\/home\\\/mrbrain\\\/public_html\\\/asbr\\\/lib\\\/private\\\/Security\\\/CSRF\\\/CsrfTokenManager.php(57): OC\\\\Security\\\\CSRF\\\\TokenStorage\\\\SessionStorage->setToken('PZMbWdFv4Q7WIWl...')\\n#3 \\\/home\\\/mrbrain\\\/public_html\\\/asbr\\\/lib\\\/public\\\/Util.php(505): OC\\\\Security\\\\CSRF\\\\CsrfTokenManager->getToken(*** sensitive parameters replaced ***)\\n#4 \\\/home\\\/mrbrain\\\/public_html\\\/asbr\\\/lib\\\/private\\\/AppFramework\\\/Middleware\\\/Security\\\/SecurityMiddleware.php(138): OCP\\\\Util::callRegister()\\n#5 \\\/home\\\/mrbrain\\\/public_html\\\/asbr\\\/lib\\\/private\\\/AppFramework\\\/Middleware\\\/MiddlewareDispatcher.php(93): OC\\\\AppFramework\\\\Middleware\\\\Security\\\\SecurityMiddleware->beforeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'showLoginForm')\\n#6 \\\/home\\\/mrbrain\\\/public_html\\\/asbr\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(88): OC\\\\AppFramework\\\\Middleware\\\\MiddlewareDispatcher->beforeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'showLoginForm')\\n#7 \\\/home\\\/mrbrain\\\/public_html\\\/asbr\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'showLoginForm')\\n#8 \\\/home\\\/mrbrain\\\/public_html\\\/asbr\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('LoginController', 'showLoginForm', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/home\\\/mrbrain\\\/public_html\\\/asbr\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#11 \\\/home\\\/mrbrain\\\/public_html\\\/asbr\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/login')\\n#12 \\\/home\\\/mrbrain\\\/public_html\\\/asbr\\\/index.php(54): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/home\\\/mrbrain\\\/public_html\\\/asbr\\\/lib\\\/private\\\/Session\\\/Memory.php\",\"Line\":119}","level":3,"time":"2016-11-14T04:34:28+00:00","method":"GET","url":"\/index.php\/login","user":"--"}`

**Comment by RealRancor** [comment]
@mrbrainin Please fill out the issue template shown when creating a new issue. This is not shown there just for fun and the information asked there are absolutely needed. Currently its not even known which oC version you're running...

**Comment by mrbrainin** [comment]
OC_Version = array(9,1,2,5)
OC_VersionString = '9.1.2';

**Comment by RealRancor** [comment]
> @mrbrainin Please fill out the issue template shown when creating a new issue. This is not shown there just for fun and the information asked there are absolutely needed

**Comment by alien2003** [comment]
I have the ssame issue on Arch Linux:
`{"reqId":"x+g3XVYCkosAwF2C279D","remoteAddr":"192.168.12.254","app":"PHP","message":"trim() expects parameter 1 to be string, array given at \/srv\/webapps\/owncloud\/lib\/private\/AppFramework\/App.php#56","level":3,"time":"2016
-11-20T00:12:12+00:00","method":"GET","url":"\/owncloud\/","user":"--"}
{"reqId":"x+g3XVYCkosAwF2C279D","remoteAddr":"192.168.12.254","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Session has been closed - no further changes to the session are allowed\",\"Code\":0,\"T
race\":\"#0 \\\/srv\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Memory.php(52): OC\\\\Session\\\\Memory->validateSession()\\n#1 \\\/srv\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/Security\\\/CSRF\\\/TokenStorage\\\/Se
ssionStorage.php(63): OC\\\\Session\\\\Memory->set('requesttoken', 'RVsxcxFu6q8xSrD...')\\n#2 \\\/srv\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/Security\\\/CSRF\\\/CsrfTokenManager.php(57): OC\\\\Security\\\\CSRF\\\\TokenStorag
e\\\\SessionStorage->setToken('RVsxcxFu6q8xSrD...')\\n#3 \\\/srv\\\/webapps\\\/owncloud\\\/lib\\\/public\\\/Util.php(505): OC\\\\Security\\\\CSRF\\\\CsrfTokenManager->getToken(*** sensitive parameters replaced ***)\\n#4 \\\/srv\\
\/webapps\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(79): OCP\\\\Util::callRegister()\\n#5 \\\/srv\\\/webapps\\\/owncloud\\\/lib\\\/base.php(396): OC_Template->__construct('', 'update.admin', 'guest')\\n#6 \\\/srv\\\
/webapps\\\/owncloud\\\/lib\\\/base.php(338): OC::printUpgradePage()\\n#7 \\\/srv\\\/webapps\\\/owncloud\\\/lib\\\/base.php(841): OC::checkUpgrade(true)\\n#8 \\\/srv\\\/webapps\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n
#9 {main}\",\"File\":\"\\\/srv\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Memory.php\",\"Line\":119}","level":3,"time":"2016-11-20T00:12:12+00:00","method":"GET","url":"\/owncloud\/","user":"--"}`

**Comment by RealRancor** [comment]
@alien2003 As it seems that @mrbrainin can't manage to provide the asked information you might want to provide the infos about your environment by filling out the issue template. Just copy the https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md into a comment and fill out the asked info.

**Comment by LoggSar** [comment]
Hi there
same problem here after installing the update.
I dont know exactly mrbrainin story, so I tell you mine.

I've updated my instance today. Until today I used sqlite as database.
After updating I got an error message (error 5 - access denied)
Because I've altready planned to switch to mysql i switched.

Now I cant see the login window and get the error shown by mrbrainin.

**My Config:**

```
OS: Debian 8
Webserver: apache
DB-Type: mysql
PHP-Version:5.6.27
ownCloud-Version : 9.1.2.5
Update (very first installation: 6.0) and problems with every update since then
```

_My Config.PHP_

```
<?php
$CONFIG = array (
  'instanceid' => '52076a5584116',
  'passwordsalt' => 'cfe740ac14df5595eeff25fd52ccec',
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://meine-seite.com',
  'htaccess.RewriteBase' => '/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.2.5',
  'installed' => true,
  'forcessl' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 0,
  'trusted_domains' => 'meine-seite.com',
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'meine-seite.com',
  'secret' => 'sdkfjasdfjölasdjkfölajsdöflkjadsölfjködlkjföladsjkfölasdjföladsjfölakjsdf',
  'forceSSLforSubdomains' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'trashbin_retention_obligation' => 'auto',
  'updatechecker' => false,
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbuser' => 'user',
  'dbpassword' => 'password',
);

```
Is this enough now?

**Comment by LoggSar** [comment]
so now I completly confused:

the combination

```
  'overwrite.cli.url' => 'http://0.0.0.0/owcloud',
  'htaccess.RewriteBase' => '/owncloud',

```
and
```
  'overwrite.cli.url' => 'http://0.0.0.0',
  'htaccess.RewriteBase' => '/owncloud',

```
gives the well known error 

```
  'overwrite.cli.url' => 'http://0.0.0.0/owcloud',
  'htaccess.RewriteBase' => '/',

```
says 
404 not found
The requested URL /index.php was not found on this server.

```
  'overwrite.cli.url' => 'http://0.0.0.0/owcloud',

```
says
The requested URL /index.php was not found on this server.


the log looks like this:

> 0.0.0.0 - - [22/Nov/2016:20:55:06 +0100] "GET /owncloud/login HTTP/1.1" 404 2912 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36 Vivaldi/1.5.658.31"
> 0.0.0.0 - - [22/Nov/2016:20:55:07 +0100] "GET /owncloud/login HTTP/1.1" 404 838 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36 Vivaldi/1.5.658.31"
> 0.0.0.0 - - [22/Nov/2016:20:57:08 +0100] "GET /owncloud/login HTTP/1.1" 404 976 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36 Vivaldi/1.5.658.31"
> 0.0.0.0 - - [22/Nov/2016:20:57:09 +0100] "GET /owncloud/login HTTP/1.1" 404 838 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36 Vivaldi/1.5.658.31"
> 0.0.0.0 - - [22/Nov/2016:20:58:04 +0100] "GET /owncloud/login HTTP/1.1" 500 10067 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36 Vivaldi/1.5.658.31"
> 0.0.0.0 - - [22/Nov/2016:20:58:05 +0100] "GET /owncloud/core/img/favicon.ico HTTP/1.1" 200 5684 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36 Vivaldi/1.5.658.31"
> 

what to do now?
moving to nextcloud?

**Comment by RealRancor** [comment]
> moving to nextcloud?

*sigh* The new "form of pressure" these days if thinks are not going fast enough... 🙄

**Comment by RealRancor** [comment]
@LoggSar Please note this is a bugtracker, no support channel. If someone has the time and the knowledge he/she will look into that issue. Furthermore there is no single reason to post stuff like "should is switch to nextcloud" in here.

> I'm using Owncloud now since version 6 and - no joke - I had problems at every(!), really every update since then. 

And i'm using my ownCloud installation since 4.0.something and - no joke - I had no single(!) problem with any of the updates / upgrades since then.

> The second thing is - this server/this installation is used by a douzen people. 

If you're relying on a working installation please do backups to be able to revert to a working state. This is documented everywhere. And before  you're stating "are people not testing" the releases see: https://owncloud.org/faq/#upgradeyet

> but I would expect an hint or a tip or an explanation how this parameters work together and depend from each other.

It seems the search on https://doc.owncloud.org/server/latest/admin_manual/search.html doesn't work for that parameters but by clicking around (or by having a look into your config.sample.php you will find the documentation about that parameters there:

https://doc.owncloud.org/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#proxy-configurations

https://doc.owncloud.org/server/latest/admin_manual/configuration_server/index_php_less_urls.html

**Comment by LoggSar** [comment]
So, after a quite long night..I'm even more confused.

The Problem didn t had to do with the config.php. It was the pllugin Ownbackup. As I deactivated this plugin I could log on. 

Why reported some people this problem and could fix it witch changes in the config.php if the main reason is obviously the plugin.

Well, its working. Whitout this plugin, but its working.

Thanks for all - Its not my issue, so I cant close it.
Bye

**Comment by RealRancor** [comment]
Thanks for posting this info. As 3rdparty apps are known to break during updates and upgrades its recommended to disabling them during this process.

As @mrbrainin and @alien2003 didn't provided the asked information up to now we can't be sure if the issue from them is also caused by that app. Guys, if not using the issue template could you at least post your installed apps?

**Comment by RealRancor** [comment]
@mrbrainin and @alien2003 Ping? Could you confirm that you had installed this 3rdparty app causing that issue?

**Comment by mrbrainin** [comment]
Yes mr @RealRancor I agree but how to resolve the issue.

**Comment by RealRancor** [comment]
@mrbrainin If you had installed this app please close here as this is not an issue in ownCloud itself but in that 3rdparty app which already got fixed by the app developer with a new version.

To get your installation to a working state see the following suggestion: https://github.com/owncloud/core/issues/26739#issuecomment-263293210

**Comment by mrbrainin** [comment]
@ RealRancor i can't login into Appliaction . How can i fix error.

Can i remove 3rd Party folder ? or what can i do ? for this error

<https://htmlsig.com/t/000001BWH431>

Mahendrakumar Rengaraju / Inventor
engrmahe@gmai.com, mahendra@mrbrain.in / 8144093959

59B, South Street,Aravakurichi, Karur, Tamilnadu, India
mrbrain.in

[image: Facebook] <https://htmlsig.com/t/000001C078FA> [image: LinkedIn]
<https://htmlsig.com/t/000001C42BY0> [image: Skype]
<https://htmlsig.com/t/000001C10QTZ> [image: Youtube]
<https://htmlsig.com/t/000001BYTJGW> [image: Github]
<https://htmlsig.com/t/000001BZAC53>

Genius is one percent inspiration and ninety-nine percent perspiration.
This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.

**Comment by RealRancor** [comment]
@mrbrainin Please note this is a bugtracker for ownCloud. The issue here is no bug in oC so please close here as already advised. You can get further support to get your installation up and running at https://central.owncloud.org/categories
