### ISSUE TITLE
Typo: An error occured while verifying the token

### ISSUE THREAD

**Issue by cornelinux** [owncloud/core#26627]
In the current master branch 9.1.x is a typo:

"An error occured while verifying the token"

must be

"An error occur**r**ed while verifying the token" (two "r"'s)

**Comment by PVince81** [comment]
@cornelinux PRs welcome 😉

**Comment by cornelinux** [comment]
:-) Well I can adapt the code, but I do not know how to fix the translations!

**Comment by cornelinux** [comment]
hm, this is fixed. Who fixed this? :-)
