### ISSUE TITLE
Fed share appear in share autocomplete when searching for same email address

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26647]
### Steps

1. Login as admin
1. Setup OC with a user "user@example.com" where "example.com" is the host of the current server
1. Create a folder "test"
1. Share "test" with "user@example.com"

### Expected result
Only one result "user@example.com"

### Actual result
Two results: "user@example.com" and "user@example.com (remote)"

Suggested quickfix: if there are two results with the same user id then remove the remote one, because the domain name matches the current server.

The fix could either be done on the JS side or better in the federated share provider, or in the code that gathers the result.

@cdamken

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/26648 @cdamken

**Comment by Helios07** [comment]
Are there any news on this? Will it make it in 9.1.5?

**Comment by PVince81** [comment]
It will likely make it into 9.1.5. PR must be reviewed.
