### ISSUE TITLE
CSP problems

### ISSUE THREAD

**Issue by Yamakaky** [owncloud/core#26645]
I get two warnings on the main page of my owncloud 9.1:

- `Content Security Policy: "frame-src" is outdated, you should use "child-src"`
- `Content Security Policy: a resource was blocked in self (« script-src https://<me> 'unsafe-eval' »)`

`<me>` is the address of my installation.
(Sorry for the inexact translation, I use Firefox in french)

**Comment by RealRancor** [comment]
frame-src can be ignored as CSP3 (current deaft) will "undeprecate" it again:

**Comment by landryb** [comment]
I don't know if it's the *same* issue, but im also experiencing the second problem:

```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://<my.fqdn> 'unsafe-eval'”).
```

Using firefox 51beta as a client, and the install is 9.1.2 running on OpenBSD, with php 5.6.23 and served by nginx 1.10.1.

**Comment by RealRancor** [comment]
@landryb See:

> For the other it might make really sense if you're filling out the issue template shown when creating a new issue. Currently nearly every info about your environment is missing.

**Comment by PVince81** [comment]
Not enough info to be able to reproduce or fix -> close.
