### ISSUE TITLE
Freenas upgrade: Failed to connect the database

### ISSUE THREAD

**Issue by zhjwpku** [owncloud/core#26640]
### Server configuration
Operating system: Freebsd

ownCloud version: 9.1.2

Updated from version 9.1.0

Where did you install ownCloud from: I't a freenas plugin

### Error
First, I update the plugin on freenas webpage, then when i reopen the ownCloud address, it tells me that I got a big instance, so I jump into the help page and run the following command:
![php_pdoerr](https://cloud.githubusercontent.com/assets/12639404/20330845/7a17f0d0-abdc-11e6-99ec-4d172279c713.PNG)

I checked the php configuration and got this:
![php_ini](https://cloud.githubusercontent.com/assets/12639404/20330875/a9c9b1e2-abdc-11e6-8540-afa8efc08ea1.PNG)

And I run the `php-config`, give out that the php --prefix is '/usr/pbi/owncloud-amd64/lib/php'
Then I think that must be the wrong path cause the problem, I simply make a little trick by create a soft link from freenas jail path to '/usr/pbi/owncloud-amd64/lib/php', after which the `PDO not fond` error gone, but another problem occurs:
![upgrade_err](https://cloud.githubusercontent.com/assets/12639404/20331055/e9783560-abdd-11e6-8e51-be43e0f2e3e3.PNG)

I am familiar with PHP, after some trying,  still got no lucky. So I came here to find help.

By the way, I'm not very sure this is the right place to ask this question and I am not sure I can follow the issue convention. Sorry if i made a mistake.

Please help ;)

**Comment by RealRancor** [comment]
> I'm not very sure this is the right place to ask this question 

I think in your case https://central.owncloud.org/ is the correct place as this is an environmental issue rather then a oC bug. Some support channel of your used Distro might be even better.

**Comment by zhjwpku** [comment]
Sure, closed. Thanks!

**Comment by RealRancor** [comment]
Ah, just also have remembered: https://github.com/owncloud/documentation/wiki/Tips-for-occ-on-shared-hosting

Might be also valid for you.
