### ISSUE TITLE
same PHP executable for WebHost and CLI

### ISSUE THREAD

**Issue by olaulau** [owncloud/core#26650]
### Steps to reproduce
1. have an apache webserver with many php handlers (i.e. for providing multiple PHP versions to users)
2. try to upgrade owncloud on a webhost which runs a PHP executable which is not the default

### Expected behaviour
upgrader executes occ command, which should use the same as the webhost, or provide a way to configure it

### Actual behaviour
occ command use default PHP executable.
In my case (ubuntu 12.04) it is PHP 5.3.29, which is less that requirements (5.4). my webhost is using a different PHP handler with another PHP executable.

### Server configuration
**Operating system**:
ubuntu server 12.04 amd64
**Web server:**
apache
**Database:**
mariadb
**PHP version:**
webhost: 5.6, default : 5.3
**ownCloud version:** (see ownCloud admin page)
9.0.2
**Updated from an older ownCloud or fresh install:**
updated
**Where did you install ownCloud from:**
tar.gz
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
> upgrader executes occ command, which should use the same as the webhost, or provide a way to configure it

this is out of scope of our capabilities. It's up to the admin of the system to make sure this is setup properly.

**Comment by RealRancor** [comment]
> It's up to the admin of the system to make sure this is setup properly.

Completely agree. If they are capable to switch between PHP versions on webserver level they should also just switch the /usr/bin/php binary and point it to the correct PHP version ownCloud is expecting.

**Comment by olaulau** [comment]
But if you provide a way to change PHP version at the webhost / directory level, not on the whole system, your reasoning doesn't work.
Maybe a config var for the PHP binary path should help people to make easy upgrade with reasonable dev cost.
