### ISSUE TITLE
Create activity entries for remote changes on external storage

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26656]
With "remote changes" it is means "changes that were done directly on the storage outside of ownCloud".

Whenever a remote change is detected by ownCloud (when possible) for an external storage, create an activity entry for it.

Possible activities:
- a file "test.txt" that wasn't there in the last scan is now here: "someone created file 'test.txt'"
- a file "test.txt" that existed before is now gone: "someone deleted file 'test.txt'"
- a file "test.txt" that existed before and its metadata has changed like size, mtime: "someone modified file 'test.txt'"
- if possible to detect moves/renames on such storages: "someone moved/renamed file X to Y"

Limitations:
- the kind of activities that can be detected from a storage is **very limited** to what the storage is able to tell us. By default the scanner checks for mtime changes and changes are usually not detected reliably, see https://github.com/owncloud/core/issues/11797
- we cannot know which user made the change, so the label will always have to say "some remote user" or something similar
- activities might appear repeated for system-wide storages. From what I remember on the technical level activity entries need to be created for every user who has access to the storage because every user has their own activity list. (this is technically doable but can become expensive for many users and many activities)

This feature would also make it possible then to send emails with such activities.

@DeepDiver1975 @jvillafanez

**Comment by jvillafanez** [comment]
> we cannot know which user made the change, so the label will always have to say "some remote user" or something similar

I don't know if the storage id or the mount point could be meaningful here, something like "this file has been added to this storage"

> activities might appear repeated for system-wide storages. From what I remember on the technical level activity entries need to be created for every user who has access to the storage because every user has their own activity list. (this is technically doable but can become expensive for many users and many activities)

I don't understand why they might be repeated. It's fine that each activity item is duplicated and set into several activity streams, once per user, but there shouldn't be anything more. Anyway, as you've said, when the number of users grows it will become very expensive.

Maybe a storage activity stream where users who have access to the storage can read from?

**Comment by cdamken** [comment]
@pmaier1 @PVince81 Any ETA here?

**Comment by PVince81** [comment]
this is in backlog, needs scheduling and careful design.

Triggering regular file hooks during scan could cause unwanted side effects. Maybe we need new hooks for update detection. Only once we have the hooks we can create activities. So there are two phases:

1) design and introduce hooks for when a remote change was detected, trigger said hooks
2) enhance activity app to generate activity entries when said hooks are triggered

Note that we're still missing activities for rename, so these would be missing here too: https://github.com/owncloud/core/pull/27074
