### ISSUE TITLE
theme configuration gets lost when upgrading via occ

### ISSUE THREAD

**Issue by eehmke** [owncloud/core#26657]
### Steps to reproduce

I have a owncloud installation running with a custom theme. The theme is configured in the config/config.php file and worked fine with owncloud 9.1.1. Then I upgraded the installation to 9.1.2 using the manual upgrade procedure https://doc.owncloud.org/server/9.0/admin_manual/maintenance/manual_upgrade.html. Additional to the mentioned procedure, I also copied my custom theme folder into the new directory.
The upgrade worked fine.

### Expected behaviour
The theme configuration should be kept.

### Actual behaviour
The owncloud web came up with the default theme. When I checked the config.php file, the theme option was reset  to
'theme' => ''
When I reentered the theme, it was working as expected.

### Server configuration
**Operating system**: Debian 8.6

**Web server:** Apache 2..4.10

**Database:** MySQL 5.5

**PHP version:** 5.6

**ownCloud version:** 9.1.2

**Updated from an older ownCloud or fresh install:** 9.1.1

**Where did you install ownCloud from:** zip file

**The content of config/config.php:**
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocxgfrwcforp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.mydomain.de",
        ],
        "datadirectory": "\/var\/lib\/owncloud\/mydata",
        "overwrite.cli.url": "https:\/\/cloud.mydomain.de",
        "default_language": "de",
        "theme": "my-theme",
        "dbtype": "mysql",
        "version": "9.1.2.5",
        "dbname": "owncloud_db",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "maintenance": false,
        "logfile": "owncloud.log",
        "loglevel": 0,
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "mydomain.de",
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}

### Client configuration
**Browser:** Firefox

**Operating system:**
Linux Mint 17.3

**Comment by DeepDiver1975** [comment]
The theme is disabled intentionally and has to manually be enabled by the admin after upgrade.

**Comment by eehmke** [comment]
Ok. At least there should be a hint in the upgrade guide.

**Comment by DeepDiver1975** [comment]
> At least there should be a hint in the upgrade guide.

I bet there is :wink:
