### ISSUE TITLE
OCS capabilities endpoint auth retrieves version too late, causing 500

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26663]
### Steps

1. `curl -u admin:admin -X GET 'http://localhost/owncloud/ocs/v1.php/cloud/capabilities?format=json' -D -`

### Expected result
200 response with contents.

### Actual result
500 response with contents.
Note that it only happens in @ogoffart's test environment with the desktop client at the moment.

We analyzed the problem and noticed that due to another bug (https://github.com/owncloud/core/issues/26651) the desktop client would receive a new session through the capabilities endpoint.

The issue is that when we reach `CloudController::getCapabilities()` the session was already closed because the controller has no `@UseSession` clause, which makes sense. However, inside that method the method `\OCP\Util::getVersion()` is called which will retrieve the current OC version from "version.php" and store it in the session, if it's not there yet. Since in this specific scenario the session was just created, the version isn't there yet so it tries to write to the session which was already closed (read-only). This makes the 500 Internal server error happen.

However it is not clear why we could only reproduce this on @ogoffart's environment.

To be investigated:
- does base.php call `getVersion()` earlier when calling the v1.php OCS endpoint ?

### Versions
Observed on master.

**Comment by PVince81** [comment]
A quickfix is to call `\OCP\Util::getVersion()` once inside `v1.php` directly after the `require_once` from base.php. This will make sure that if the version was not stored in the session, it will store it there at this point, which is before the session got closed by the app framework in the `SessionMiddleware` class.

**Comment by PVince81** [comment]
Looks like normally the version is always retrieved in base.php in `checkServer()` the earliest.

So maybe something in @ogoffart's env is producing an exception before that line but for some reason isn't logged or thrown anywhere. (I remember that `require_once` might not always pass exceptions through)

**Comment by ogoffart** [comment]
> A quickfix is to call \OCP\Util::getVersion() once inside v1.php directly after the require_once from base.php. 

I confirm this vixes the problem.

> Looks like normally the version is always retrieved in base.php in checkServer() the earliest.

This is also hapenning in my environment.
For some reason, however it seems the environement is cleared later.


Adding `return true;` at the begining of the function supportsCookies in Session.php also fixes the problem.

**Comment by PVince81** [comment]
I still don't get it. At the beginning of `v1.php` there are calls to `needsUpgrade()` which itself already calls `\OCP\Util::getVersion()`. There is still something very twisted happening here.

**Comment by ogoffart** [comment]
I think the session gets reset inbetween, because the test cookie is not present

**Comment by DeepDiver1975** [comment]
@ogoffart mind testing the current master to see it this issue is gone? THX

**Comment by ogoffart** [comment]
The 500 error seems to be fixed, thank :+1: 

But I still can see that the cookie_test cookie is still sent without the path set, this causes the client to create more PHP sessions than necessary.

**Comment by PVince81** [comment]
The cookie_test is a different issue: https://github.com/owncloud/core/issues/26651
