### ISSUE TITLE
Add openSUSE Leap 42.2 repo

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26662]
Please add the openSUSE Leap 42.2 repo in the build list, currently http://download.owncloud.org/download/repositories/stable/openSUSE_Leap_42.2 does not exist.

@owncloud/packaging

**Comment by PVince81** [comment]
Workaround: use the 42.1 repo instead, works for me

**Comment by Kawohl** [comment]
@crrodriguez

**Comment by jnweiger** [comment]
leap 42.2, sles12-sp2, ubuntu-16.10 added to ce:9.1 ee:9.1 in obs.int.
Please identify unneeded repos and remove. 
Please also update desktop project, if needed.

**Comment by crrodriguez** [comment]
Requested repository has been published now.

**Comment by PVince81** [comment]
It's missing here: https://download.owncloud.org/download/repositories/testing/owncloud/

```
File '/repodata/repomd.xml' not found on medium 'http://download.owncloud.org/download/repositories/9.1:/testing/openSUSE_Leap_42.2'
```

Reopening

**Comment by PVince81** [comment]
The "stable" repo is there, yes

**Comment by jnweiger** [comment]
* removed ubuntu-12.04 from devel, ee:9.1:testing and ce:9.1:testing
* added leap 42.2 to devel, ee:9.1:testing and ce:9.1:testing

@crrodriguez It needs another click on publish_ee when everthying has built. thnaks!

**Comment by PVince81** [comment]
@crrodriguez ping, I think everything should have finished building by now

**Comment by Kawohl** [comment]
its up.

**Comment by crrodriguez** [comment]
@PVince81 packages are building right now. fixed.
