### ISSUE TITLE
Updater-App doesn´t show Updates any more

### ISSUE THREAD

**Issue by Octopus2** [owncloud/core#26668]
### Steps to reproduce
1. Go to the admin-section and look for updates

### Expected behaviour
1. Stabel-Channel should show Version 8.2.9, (or at least Version 8.2.8)

### Actual behaviour
1. Stabel-Channel doesn´t show any updates 
2. Beta-Channel shows Version 9.0.4

### Server configuration
**ownCloud version:** 8.2.7

**Comment by RealRancor** [comment]
@Octopus2 This is a known behavior. Once there are no issues with an update/upgrade like 8.2.7 -> 8.2.9 -> 9.0.6 the update will be enabled.

**Comment by PVince81** [comment]
Please try again, some updates were published recently.
