### ISSUE TITLE
i changed the theme nothing else

### ISSUE THREAD

**Issue by Smiril** [owncloud/core#26679]
this line will make desaster

 'theme' => 'Umbrella'

own theme design from scratch (example) was be used and not modyfied strong 
i build in live sessions on my own OC Server a new theme what's right for me and myself.

change it back to:

 'theme' => 'example'

login possible

**Comment by RealRancor** [comment]
@Smiril Please note this is a bugtracker of ownCloud. Support requests like this needs to go to https://central.owncloud.org/
