### ISSUE TITLE
OC_DEFAULT_MODULE does not exist

### ISSUE THREAD

**Issue by denisblum** [owncloud/core#26670]
Hi,
i'm using OwnCloud 9.1.0 stable

Until 3 days ago everything went well. Round about 10 user are working with my owncloud as a foto-cloud. 
To have more security i activate antivir and backup and encription. After that, all the new files cant be opened or download.
Error:
OC_DEFAULT_MODULE does not exist

With older files everything is ok.

I deacitvate the apps but i still receive the error.

Please help.

**Comment by PVince81** [comment]
what if you keep only encryption enabled but not backup and antivirus ?

Please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

**Comment by denisblum** [comment]
I'm not sure, if i want to test it. 
The problem was only by folders / files which are generated after activating antivirus, backup and so on. i deactivated the tools and made all folders / files new. now it works.

**Comment by PVince81** [comment]
Encryption works, I can guarantee that. It works on my own server and I have never seen such errors there.

However when combined with antivirus I'm not sure, that's why I asked whether you could keep encryption enabled but disable antivirus and backup to see if the problem disappears.

Without further information we won't be able to help you.

**Comment by denisblum** [comment]
Thankx for your support.
I build up a test cloud. i will test your idea and give you feedback.

**Comment by RealRancor** [comment]
@denisblum You might also want to explain what "activated backup" means. There is no such functionality included in oC so you probably have installed a 3rdparty app?

**Comment by denisblum** [comment]
Hi, yes of course.
You can find "OwnBackup" under "APPS".

**Comment by PVince81** [comment]
Any update ? Did disabling the apps make encryption work again ?

If yes, this is likely a bug in one of these apps. Please report the app's repository.

Else try again with 9.1.3 and use the issue template https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md
