### ISSUE TITLE
occ upgrade fails with Sabre\VObject\Recur\NoInstancesException

### ISSUE THREAD

**Issue by ivomaintz** [owncloud/core#26677]
### Steps to reproduce
1. upgrade owncloud from 9.1.1 to 9.1.2 on ubuntu 14.04
2. upgrade fails with

Updating <dav> ...
Fix classification for calendar objects
 Starting ...                                 
  363/1875 [=====>----------------------]  19%Sabre\VObject\Recur\NoInstancesException: This recurrence rule does not generate any valid instances
Update failed

### Expected behaviour
upgrade should run successfully.

### Server configuration
**OS.**
Ubuntu 14.04
**Web server:**
Apache 2.4.7
**Database:**
mysql 5.5.53
**PHP version:**
5.5.9
**ownCloud version:** (see ownCloud admin page)
9.1.2
**Updated from an older ownCloud or fresh install:**
updated from 9.1.1
**Where did you install ownCloud from:**
I installed it with apt from http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/

**Signing status (ownCloud 9.0 and above):**
Can't login into owncloud
**List of activated apps:**
Enabled:
  - dav: 0.2.6
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - firstrunwizard: 1.1
Disabled:
  - activity
  - bookmarks
  - calendar
  - chat
  - comments
  - contacts
  - documents
  - encryption
  - external
  - federation
  - files_antivirus
  - files_external
  - files_pdfviewer
  - files_sharing
  - files_texteditor
  - files_trashbin
  - files_versions
  - files_videoplayer
  - gallery
  - mail
  - mozilla_sync
  - music
  - notes
  - notifications
  - owncloud_editdoc
  - ownnote
  - provisioning_api
  - search_lucene
  - systemtags
  - templateeditor
  - updatenotification
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "5204b7f34e2db",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/owncloud\/data",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "dbtype": "mysql",
        "version": "9.1.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "ldapIgnoreNamingRules": false,
        "loglevel": "3",
        "theme": "",
        "maintenance": false,
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "mailhost.cms.hu-berlin.de",
        "mail_smtptimeout": 30,
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "thbpcloud.de",
            "biologie.hu-berlin.de"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-i\n  nline'; frame-src *; img-src *; font-src 'self' data:; media-src *",
        "mail_from_address": "maintziv",
        "mail_domain": "hu-berlin.de",
        "updatechecker": false,
        "trashbin_retention_obligation": "auto"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)
mysql> SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';
+-----------+-----------------------------------+---------------------------------------------+
| appid     | configkey                         | configvalue                                 |
+-----------+-----------------------------------+---------------------------------------------+
| user_ldap | bgjUpdateGroupsLastRun            | 1377631524                                  |
| user_ldap | cleanUpJobOffset                  | 150                                         |
| user_ldap | enabled                           | yes                                         |
| user_ldap | enforce_home_folder_naming_rule   |                                             |
| user_ldap | has_memberof_filter_support       |                                             |
| user_ldap | home_folder_naming_rule           |                                             |
| user_ldap | installed_version                 | 0.9.0                                       |
| user_ldap | last_jpegPhoto_lookup             | 0                                           |
| user_ldap | ldap_agent_password               |                                             |
| user_ldap | ldap_attributes_for_group_search  |                                             |
| user_ldap | ldap_attributes_for_user_search   |                                             |
| user_ldap | ldap_backup_host                  |                                             |
| user_ldap | ldap_backup_port                  | 389                                         |
| user_ldap | ldap_base                         | dc=xxxxxxxxx      |
| user_ldap | ldap_base_groups                  | dc=xxxxxxxx     |
| user_ldap | ldap_base_users                   | dc=xxxxxxxxxx      |
| user_ldap | ldap_cache_ttl                    | 600                                         |
| user_ldap | ldap_configuration_active         | 1                                           |
| user_ldap | ldap_display_name                 | cn                                          |
| user_ldap | ldap_dn                           |                                             |
| user_ldap | ldap_dynamic_group_member_url     |                                             |
| user_ldap | ldap_email_attr                   | mail                                        |
| user_ldap | ldap_experienced_admin            | 0                                           |
| user_ldap | ldap_expert_username_attr         |                                             |
| user_ldap | ldap_expert_uuid_attr             |                                             |
| user_ldap | ldap_expert_uuid_group_attr       |                                             |
| user_ldap | ldap_expert_uuid_user_attr        |                                             |
| user_ldap | ldap_group_display_name           | cn                                          |
| user_ldap | ldap_group_filter                 | (&(|(objectclass=posixGroup))(|(cn=test))) |
| user_ldap | ldap_group_filter_mode            | 0                                           |
| user_ldap | ldap_group_member_assoc_attribute | memberUid                                   |
| user_ldap | ldap_groupfilter_groups           | test                                       |
| user_ldap | ldap_groupfilter_objectclass      |                                             |
| user_ldap | ldap_host                         | 000.000.000.000                               |
| user_ldap | ldap_login_filter                 | (&(|(objectclass=inetOrgPerson))(uid=%uid)) |
| user_ldap | ldap_login_filter_mode            | 0                                           |
| user_ldap | ldap_loginfilter_attributes       |                                             |
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

| user_ldap | ldap_loginfilter_email            | 0                                           |
| user_ldap | ldap_loginfilter_username         | 1                                           |
| user_ldap | ldap_nested_groups                | 0                                           |
| user_ldap | ldap_override_main_server         | 0                                           |
| user_ldap | ldap_paging_size                  | 500                                         |
| user_ldap | ldap_port                         | 389                                         |
| user_ldap | ldap_quota_attr                   |                                             |
| user_ldap | ldap_quota_def                    |                                             |
| user_ldap | ldap_tls                          | 1                                           |
| user_ldap | ldap_turn_off_cert_check          | 1                                           |
| user_ldap | ldap_user_display_name_2          |                                             |
| user_ldap | ldap_user_filter_mode             | 0                                           |
| user_ldap | ldap_userfilter_groups            |                                             |
| user_ldap | ldap_userfilter_objectclass       | inetOrgPerson                               |
| user_ldap | ldap_userlist_filter              | (|(objectclass=inetOrgPerson))              |
| user_ldap | ldap_uuid_attribute               | entryuuid                                   |
| user_ldap | ldap_uuid_group_attribute         | entryuuid                                   |
| user_ldap | ldap_uuid_user_attribute          | entryuuid                                   |
| user_ldap | types                             | authentication                              |
| user_ldap | use_memberof_to_detect_membership | 1                                           |
+-----------+-----------------------------------+---------------------------------------------+

### Client configuration
**Browser:**
Firefox
**Operating system:**
ubuntu 16.04
### Logs
```
#### ownCloud log (data/owncloud.log)
```
[owncloud.txt](https://github.com/owncloud/core/files/604290/owncloud.txt)

```

**Comment by DeepDiver1975** [comment]
You are having an invalid calendar object in your database.

I'll try to make it a bit more fault tolerant ...

**Comment by ivomaintz** [comment]
Hi,

What can I do? Could I identify (and delete) the invalid object?

**Comment by ivomaintz** [comment]
I still found no solution for this. Just tried again to upgrade to 9.1.4, same error.
Is there any chance to delete/repair the invalid entry?

**Comment by ivomaintz** [comment]
Finally managed it - I deleted in mysql in the owncloud database the entry id 363 from oc_calendarobjects.
But I do not know, what I might have broken. Anyway, all seems to be ok now
