### ISSUE TITLE
First run - This content failed to load.

### ISSUE THREAD

**Issue by motatuc** [owncloud/core#26689]
Hello.

Just installed Nextcloud on my server with the setup-nextcloud.php-script.
Finished without any problems.
Login working fine. But loading content is not possible - opening layers stay empty and show: This content failed to load.

### Steps to reproduce
1. Login Nextcloud
2. Layer window opens
3. Error message and window stays empty.
4. Choose another app, or any other option -> empty layer window with same error message.

### Expected behaviour
This window should contain content.

### Actual behaviour
Window stays empty and throws error message.

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

-> No errors have been found.
```

**List of activated apps:**

Standard activated apps.

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**PHP-VERSION:** "PHP/5.5.38"

My browser also tells me this:
.../nextcloud/index.php/apps/firstrunwizard/wizard.php -> 404
../nextcloud/index.php/apps/files/ajax/getstoragestats.php?dir=/ -> 404
../nextcloud/index.php/apps/firstrunwizard/ajax/disable.php -> 404
![screenshot from 2016-11-22 17-17-23](https://cloud.githubusercontent.com/assets/15171154/20532310/d2a2ed48-b0d9-11e6-858b-5fe5de7d655e.png)

**Comment by RealRancor** [comment]
> Just installed Nextcloud on my server with the setup-nextcloud.php-script.

Please note this is a bugtracker for ownCloud. As you have installed Nextcloud please close here and report the issue to https://github.com/nextcloud/server/issues

**Comment by motatuc** [comment]
Thanks.
