### ISSUE TITLE
Change \OC\User logout hook to be executed AFTER Ownclouds logout routine and session termination

### ISSUE THREAD

**Issue by felixrupp** [owncloud/core#26692]
### Steps to reproduce
1. Register own user backend with authentication (e.g. CAS authentication)
2. Login with your own backend, do your stuff
3. Logout from Owncloud; your logout hook is beeing executed, but in my case (CAS auth) the external auth component needs a http-request to log me out. After that it’s impossible to correctly terminate the owncloud session.

### Expected behaviour
Owncloud session must be destroyed, after the custom logout hooks are fired

### Actual behaviour
Owncloud fires custom logout hooks and prevents correct owncloud logout itself

### Server configuration
**Operating system**: Debian 8/Ubuntu 12

**Web server:** Apache 2.4

**Database:** MySQL 5.5x

**PHP version:** 5.5x and 5.6x

**ownCloud version:** 9.1.1

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** Debian repo

**Signing status (ownCloud 9.0 and above):** nothing special

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:** Only stock apps plus my own: user_cas

**The content of config/config.php:**

	<?php
	$CONFIG = array (
	  'updatechecker' => false,
	  'instanceid' => 'oc1s5n0h5i4j',
	  'trusted_domains' => 
	  array (
	    0 => 'localhost',
	  ),
	  'passwordsalt' => '+PPY/lMG6CGAGjucGT70FnHTE/ShO8',
	  'secret' => 'fh3ThDOxwmmAY+IH7pRjw7tbZAAzgg2ph3enhgIUJ9ZBKmc3',
	  'datadirectory' => '/var/www/owncloud/data',
	  'overwrite.cli.url' => 'http://localhost/owncloud',
	  'dbtype' => 'mysql',
	  'version' => '9.1.1.3',
	  'dbname' => 'oc',
	  'dbhost' => 'localhost',
	  'dbtableprefix' => 'oc_',
	  'logtimezone' => 'UTC',
	  'installed' => true,
	  'memcache.local' => '\\OC\\Memcache\\APCu',
	  'appstore.experimental.enabled' => true,
	  'debug' => true,
	  'theme' => '',
	  'loglevel' => 0,
	  'maintenance' => false,
	);
**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** YES, user_cas -> CAS auth backend

### Client configuration
**Browser:** Safari 10.0.1

**Operating system:** Mac OS X 10.10.5

#### Web server error log
Nothing special seen

#### ownCloud log (data/owncloud.log)
Nothing special seen

#### Browser log
Nothing special seen

**Comment by PVince81** [comment]
I'm not sure if it's safe to fix the hook to fire after logout right now as it could affect other user backends.
So maybe an idea would be to add yet another hook "post_logout" that happens after ownCloud did its own logout.

**Comment by felixrupp** [comment]
That sounds like a valid plan ;) ! Would be great if there is a possibility to add a second hook!

**Comment by PVince81** [comment]
I suggest you add it yourself and submit a PR. This also makes it possible for you to test with your app to see if it works as expected.

From what I see the current logout hook is triggered here: https://github.com/owncloud/core/blob/master/lib/private/User/Session.php#L715

There is also some forwarding to the old static style hook here: https://github.com/owncloud/core/blob/master/lib/private/Server.php#L278
