### ISSUE TITLE
FR: Exclude URLs from proxy settings

### ISSUE THREAD

**Issue by cornelinux** [owncloud/core#26708]
### Expected behaviour
I would like to exclude certain URLs from the owncloud proxy settings.

### Actual behaviour
I seems not to be possible.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MySQL

**PHP version:**

**ownCloud version:** 9.1

It does not seem possible to exclude URLs from the owncloud system wide proxy settings in config.php
My app "privacyIDEA owncloud App" communicates to a local privacyidea authentication server, which is sometimes located in a different, secure subnet and might not be reached by the proxy, which is specified in the default proxy settings.

See https://central.owncloud.org/t/exclude-host-from-proxy-settings/4153

Thus is a proxy is configured in config.php, it is not possible to reach the internal authetication server.

The proxy settings are set before each GET and POST Request in lib/private/Http/Client/Client.php@IClient:setDefaultOptions, which is called before *every* GET or POST request.

## Implementation Variant A

I suggest to add settings in config.php a parameter like

	"proxy_exclude_urls" => ["url1", "url2", "url3"]

Clear the proxy settings like

	$this->client->setDefaultOption("proxy", "")

before each GET and POST request using a method

	private function isURLinProxyExcludes($uri)

which reads the configuration and checks if any of the excludeUrls in the LIST is the starting part of the URI requested.

## Implementation Variant B

Another possibility could be to add a new parameter to th get and post methods like:

        public function get($uri, array $options = [], $proxy=0) {

To determine if:

  1. the system wide proxy should be used
  2. no proxy should be used
  3. a special (own) proxy should be used.

I think I like the second possibility, since it is more flexible, and my app can decide on its in in the POST request, how to handle proxies.

**Comment by hodyroff** [comment]
Sounds like a good idea, can you do a PR and mention @PVince81 for review?

**Comment by PVince81** [comment]
@cornelinux another variant would be to add getter/setter on the http client object to enable/disable the proxy. You could then call it before you call then set it back afterwards.

One drawback is that if someone forgets to reset the proxy back then subsequent calls would fail. This could also happen if there's an uncaught exception which would make it bypass the "reset proxy back" call.

So maybe your variant 2 is the best.

**Comment by cornelinux** [comment]
hm, since the "proxy" setting is directly passed to the guzzle client there might even be a simple solution for me to configure this in the config.php. I am just verifying this. If so, I would improve this documentation:

https://doc.owncloud.org/server/9.1/admin_manual/configuration_server/config_sample_php_parameters.html

Is this also maintained in git and is it possible to do a PR?

**Comment by PVince81** [comment]
@cornelinux if you do a PR to change config.sample.php there is a script that the documentation people will run to convert it to proper documentation.

cc @carlaschroder

**Comment by cornelinux** [comment]
OK, I start to understand this here. The problem arises from the implementation of the HTTP Client:
https://github.com/owncloud/core/blob/master/lib/private/Http/Client/Client.php#L91

The getProxyUri function is implemented in this way, that it will only allow strings - or convert everything to a string.
But the guzzle client, which is used underneath allows rather sophisticated proxy settings:
http://docs.guzzlephp.org/en/v5/request-options.html?highlight=proxy#proxy

You can in fact already provide the exclusion in the proxy definition. I would like to add such an array with a "no" element to the config/config.php proxy setting. I think the is by far the most simple way.

But for this we need to fix the *private getProxyUri()* so that it will not stringify the array.
We should keep up the backward compatibility...

**Comment by PVince81** [comment]
If `getProxyUri()` is private then there must be a way around it. Is it really necessary to stringify the array with the way you suggested to make it work ?

**Comment by carlaschroder** [comment]
> @cornelinux if you do a PR to change config.sample.php there is a script that the documentation people will run to convert it to proper documentation.

The converter script is at https://github.com/owncloud/administration/tree/master/config-sample-converter. Anyone can use it, and then open a PR with the updated config.sample.php for the Admin manual.

**Comment by cornelinux** [comment]
Unfortunately the guzzle client does not behave as documented and expected. 
I need some more time to look into this and maybe open an issue with guzzle.
This is why the prio in combination with the effort to fix this caused the delay in the processing of this issue ;-)

**Comment by PVince81** [comment]
This is fine, no worries. Take your time 😄

**Comment by cornelinux** [comment]
Hm, such a long break here. I am looking at my App-Code again and I am wondering, if we need to change the core at all or if we only need to adapt the developer documentation. I am using ``IClientService $httpClientService``.

            if ($noproxy === "1") {
                $options["proxy"] = ["https" => "", "http" => ""];
            }
            $client = $this->httpClientService->newClient();
            $res = $client->post($url, $options);

**Comment by PVince81** [comment]
Moving this to backlog, unless you think this is not needed any more.

**Comment by PVince81** [comment]
@cornelinux is this still relevant / needed ?

**Comment by cornelinux** [comment]
@PVince81 I don't think so.
I close it and will come back with a new issue, if something pops up....
