### ISSUE TITLE
File Modified Date is Changed When Using WebDav and File Manager

### ISSUE THREAD

**Issue by viking2** [owncloud/core#26718]
I access ownCloud using a WebDav and NetDrive2 to create a network Drive (W:\)
With my local **file manager**, I transfer a file from my local drive to a ownCloud directory W:\Test.

However, when I transfer the file, the file modified date is changed to the date of the transfer. How can I keep the modified date?

Note that this doesn't happen when I use the desktop Sync client.

p.s. I found a similar issue here: https://github.com/owncloud/core/issues/21762 . However that concerned modified file date when uploading a file by browser.

**Comment by hodyroff** [comment]
https://github.com/owncloud/core/pull/21237
It depends on your WebDAV client. We have the mechanisms available but the client, like the browser must support it. Please reopen if you see a bug here ...
