### ISSUE TITLE
spam of error after upgrade to 9.1.1 to 9.2.0

### ISSUE THREAD

**Issue by leo-yip** [owncloud/core#26728]
### Steps to reproduce
1. upgrade owncloud from 9.1.1 to 9.2
2. upgrade php from 5.5 to 5.6
3.

### Actual behaviour
spam of error:

Error	PHP	You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at /var/www/html/owncloud/lib/composer/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php#18	2016-11-26T13:54:31+00:00

![image](https://cloud.githubusercontent.com/assets/19850742/20640807/3f1fc62e-b424-11e6-985a-b977317b42f6.png)

### Server configuration
CENTOS 7

PHP version: 5.6.28

ownCloud version: ownCloud 9.2.0 pre alpha (daily) Build:2016-09-14

Updated from ownCloud 9.1.1

Where did you install ownCloud from: yum upgrade

no integrity failed
```

**Comment by RealRancor** [comment]
And have you installed the PHP intl extension as advised??

**Comment by leo-yip** [comment]
thanks, after yum install php-intl, no more error.

**Comment by RealRancor** [comment]
@leo-yip Then please close this issue as the message is expected
