### ISSUE TITLE
 Internal Server Error after Upgrading to 9.1.2.5 from 9.1.1.3

### ISSUE THREAD

**Issue by capnjb** [owncloud/core#26729]
Internal Server Error after Upgrading to 9.1.2.5 from 9.1.1.3
After Upgrading to 9.1.2.5 from 9.1.1.3 - Internal Server Error

[b]Steps to reproduce[/b]
1. yum update
2. run ./occ upgrade (seemed to run OK)
3. Log in and access to files and app appeared normal.
4. After computer reboot the errors surfaced

[b]Expected behaviour[/b]
Normal log in with access to files and apps

[b]Actual behaviour[/b]
*** Attempting to Login
Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
Technical details
    Remote Address: 192.168.10.254
    Request ID: WDjxi96PwM011CKDgf7aiQAAAAI

*** Attempt to run ./occ (anything) as user apache
-bash-4.2$ ./occ
An unhandled exception has been thrown:
OCP\AutoloadNotAllowedException: Autoload path not allowed: /var/www/html/owncloud/apps/gallery/appinfo/application.php in /var/www/html/owncloud/lib/autoloader.php:133
Stack trace:
#0 /var/www/html/owncloud/lib/autoloader.php(157): OC\Autoloader->isValidPath('/var/www/html/o...')
#1 [internal function]: OC\Autoloader->load('OCA\\Gallery\\App...')
#2 /var/www/html/owncloud/apps/_gallery/appinfo/app.php(19): spl_autoload_call('OCA\\Gallery\\App...')
#3 /var/www/html/owncloud/lib/private/legacy/app.php(187): require_once('/var/www/html/o...')
#4 /var/www/html/owncloud/lib/private/legacy/app.php(150): OC_App::requireAppFile('_gallery')
#5 /var/www/html/owncloud/lib/private/legacy/app.php(120): OC_App::loadApp('_gallery')
#6 /var/www/html/owncloud/lib/private/Console/Application.php(95): OC_App::loadApps()
#7 /var/www/html/owncloud/console.php(101): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/owncloud/occ(11): require_once('/var/www/html/o...')
#9 {main}-bash-4.2$ 
-bash-4.2$ 

[b]Server configuration[/b]
Operating system: CentOS 7.2.1511
Web server: Apache 2.4.6
Database: mysql
PHP version: 7.0.12
ownCloud version (see ownCloud admin page): 9.1.2.5 (unable to access GUI)
Updated from an older ownCloud or fresh install: Updated via terminal ./occ upgrade
Special configuration (external storage, external authentication, reverse proxy, server-side-encryption):
Several external storage shares, few apps: calendar, activity, comments, gallery No Encryption, No https

[b]ownCloud log (data/owncloud.log)[/b]
[code]
\/kVJT++D9Yaria","remoteAddr":"","app":"core","message":"starting upgrade from 9.1.1.3 to 9.1.2.5","level":0,"time":"2016-11-25T05:51:39+00:00","method":"--","url":"--","user":"--"}
{"reqId":"g2Mas0\/kVJT++D9Yaria","remoteAddr":"","app":"PHP","message":"file_put_contents(\/var\/www\/html\/owncloud\/data\/.htaccess): failed to open stream: Permission denied at \/var\/www\/html\/owncloud\/lib\/private\/Setup.php#500","level":3,"time":"2016-11-25T05:51:39+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WDfYlXbhS-TqUWZkUZIrvwAAAAQ","remoteAddr":"192.168.10.254","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/gallery\\\/appinfo\\\/application.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/autoloader.php(157): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/html\\\/o...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Gallery\\\\\\\\App...')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/_gallery\\\/appinfo\\\/app.php(19): spl_autoload_call('OCA\\\\\\\\Gallery\\\\\\\\App...')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(187): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(150): OC_App::requireAppFile('_gallery')\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(120): OC_App::loadApp('_gallery')\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(887): OC_App::loadApps()\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/autoloader.php\",\"Line\":133}","level":3,"time":"2016-11-25T06:22:13+00:00","method":"GET","url":"\/owncloud\/","user":"--"}
{"reqId":"WDfYvLqGi-
[/code]

[b]Integrity status for oC9+[/b]
Unable to access GUI
*** 161128 - More information
The Apache webserver functions properly with my test web pages and the ownCloud index page does load but complains about the Internal Server Error above.  Additionally what is strange is the reported "Remote Address:" is the IP of my LAN Router & DNS Server.

**Comment by PVince81** [comment]
Try renaming the "_gallery" folder to "gallery".
I think this error happens because the app id doesn't match the folder name.

**Comment by capnjb** [comment]
PVince81,
Hummm... _galley was an older version that I had "commented" out.  there already was a "galley".  Interesting that this was not an error in previous updates.  But I deleted the directory and all is good again!  Must have been some updates to the code integrity.
Thank you so much... I was scratching my head what could have possibly gone wrong.

**Comment by capnjb** [comment]
Issue Resolved!
