### ISSUE TITLE
Erasing folder over sync-client and the server decided to keep it

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#26722]
### Steps to reproduce
1. Mount ownCloud over Webdav and work in one folder with Office/Libre-Office files. (One of the Locking files are kept - Probably while connection broken or similar)
2. Sync the folder with the sync-client - Use selective sync to select it.
3. Erase the folder with all the files.
4. The folder does not exist anymore but the sync-client has still marked to be synced.

### Expected behavior
I have no real expectations, but I can propose some scenarios:

Possibility 1.- Sync-client gives a waring that the folder could not be fully erased because its not empty or has no privileges in the server side : `Folder still exist after deleting (Probably hidden or non-synced files still exist on the server) - Please open your web-browser remove the folder manually or contact yous system administration for more assistance` 

Possibility 2.-  Just the Sync-client unmarks the folder to have the same behavior as local folder fulfilling the expectation from the erase folder and a Warning appears: `Folder was not empty - unmarked from selective sync)`

Possibility 3.- The server  erases the whole content of the folder and files ad add it in the activity.

### Actual behavior
Selective sync is still showing that the folder will be synced, the folder does be appear anymore in the local filesystem and no warnings appears of the weird behavior

### ownCloud Server 
9.1.2

### ownCloud Client
2.2.4

@hodyroff @guruz @pvince81 @pmaier1

**Comment by PVince81** [comment]
@cdamken any details about the actual server-side permissions ? I don't see any step asking to set some folder read-only or so.

**Comment by hodyroff** [comment]
Issue moved to [owncloud/client #5336](https://github.com/owncloud/client/issues/5336) via [**ZenHub**](https://www.zenhub.com/)
