### ISSUE TITLE
Avatar directory can't be created, and that blocks use of owncloud for a freshly created user.

### ISSUE THREAD

**Issue by ppaysant** [owncloud/core#26724]
### Steps to reproduce
1. log as admin
2. create a new user in admin page
3. delog then log as this new user

Datadir is set to "/data/owncloud9" (absolute dir, without ending slash)

### Expected behaviour
Files list should appear

### Actual behaviour
Error message with stack trace which main part is :
```
Message : No create permission for folder /avatars/4a
Fichier : /var/www/nfs.owncloud9.chez.moi/lib/private/Files/Node/Folder.php
Ligne : 160
```

### Server configuration
**Operating system**: centOS 7.2

**Web server:**: apache 2.4

**Database:**: mariadb 5.5.4

**PHP version:**: 5.6.5

**ownCloud version:**
 - version: 9.2.0.3
 - versionstring: 9.2.0 pre alpha

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** git master

**Signing status (ownCloud 9.0 and above):**
integrity checker disabled

**List of activated apps:**
  - comments: 0.3.0
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - lotsofusers: 0.0.1
  - updatenotification: 0.2.1

**The content of config/config.php:**

```
{
    "system": {
        "debug": true,
        "instanceid": "octyy6ynadta",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud9.chez.moi"
        ],
        "datadirectory": "\/data\/owncloud9",
        "overwrite.cli.url": "https:\/\/owncloud9.chez.moi",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "9.2.0.3",
        "dbname": "owncloud9",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "appstoreenabled": false,
        "default_language": "fr",
        "enable_avatars": false,
        "enable_previews": true,
        "has_internet_connection": false,
        "allow_user_to_change_display_name": false,
        "updatechecker": false,
        "knowledgebaseenabled": false,
        "theme": ""
    }
}
```

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
Only web client tested.

#### ownCloud log (data/owncloud.log)
```
{"reqId":"WDhWXzSJ5-8ylmIOUL4CfAAAAAM","remoteAddr":"172.16.81.1","app":"index","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotPermittedException\",\"Message\":\"No create permission for folder \\\/avatars\\\/4a\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nfs.owncloud9.chez.moi\\\/lib\\\/private\\\/AvatarManager.php(98): OC\\\\Files\\\\Node\\\\Folder->newFolder('4a')\\n#1 \\\/var\\\/www\\\/nfs.owncloud9.chez.moi\\\/lib\\\/private\\\/AvatarManager.php(119): OC\\\\AvatarManager->getFolder(Object(OC\\\\Files\\\\Node\\\\Folder), '4a')\\n#2 \\\/var\\\/www\\\/nfs.owncloud9.chez.moi\\\/lib\\\/private\\\/AvatarManager.php(90): OC\\\\AvatarManager->getAvatarFolder(Object(OC\\\\User\\\\User))\\n#3 \\\/var\\\/www\\\/nfs.owncloud9.chez.moi\\\/lib\\\/private\\\/TemplateLayout.php(114): OC\\\\AvatarManager->getAvatar('luser1')\\n#4 \\\/var\\\/www\\\/nfs.owncloud9.chez.moi\\\/lib\\\/private\\\/legacy\\\/template.php(225): OC\\\\TemplateLayout->__construct('user', 'files')\\n#5 \\\/var\\\/www\\\/nfs.owncloud9.chez.moi\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(156): OC_Template->fetchPage()\\n#6 \\\/var\\\/www\\\/nfs.owncloud9.chez.moi\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(112): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#7 \\\/var\\\/www\\\/nfs.owncloud9.chez.moi\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#8 \\\/var\\\/www\\\/nfs.owncloud9.chez.moi\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#9 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#10 \\\/var\\\/www\\\/nfs.owncloud9.chez.moi\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#11 \\\/var\\\/www\\\/nfs.owncloud9.chez.moi\\\/lib\\\/base.php(894): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#12 \\\/var\\\/www\\\/nfs.owncloud9.chez.moi\\\/index.php(46): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/nfs.owncloud9.chez.moi\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php\",\"Line\":164}","level":3,"time":"2016-11-25T15:18:56+00:00","method":"GET","url":"\/apps\/files\/","user":"luser1"}
```

(This type of logs are awfully unreadable... There is a enhancement point here)

### Additional informations

1. My datadir is set to "/data/owncloud9" (see conf), but the script tries to create /avatars/4a without prepending datadir.

2. As you can see in conf section, I set the enable_avatars to false... Which seems to have no effect on the avatar dir creation.

**Comment by PVince81** [comment]
So there are two issues:

1) it still tries to create a folder even when "enable_avatars" is false

2) for some reason the avatar folder becomes absolute instead of being relative to the data dir

**Comment by PVince81** [comment]
Looks like oc_filecache contains the avatar entries and on your env we saw that the perms were 17 instead of 31 for the "avatars" entry. Now I could imagine that the perms were wrong on disk at first when OC scanned the folder for some reason, but the filecache did not auto-update.

Also I checked locally (manually set perms to 17 for that entry), that occ files:scan does not update the entry.

I'm wondering why and whether this info should really be stored in the filecache at all...

**Comment by ppaysant** [comment]
Updating the oc_filecache table for the "avatars" line, it works. I close this issue.
Many thanks

**Comment by CristianCardosoA** [comment]
"Updating the oc_filecache table for the "avatars" line" what does this mean ? SQL command update?

**Comment by CristianCardosoA** [comment]
![captura de pantalla 2018-06-15 a la s 11 41 05 p m](https://user-images.githubusercontent.com/18292956/41495809-9b8d145e-70f5-11e8-9701-025049ca7712.png)

**Comment by CristianCardosoA** [comment]
![captura de pantalla 2018-06-15 a la s 11 42 58 p m](https://user-images.githubusercontent.com/18292956/41495818-deb50e76-70f5-11e8-85e6-273f872533fd.png)

**Comment by ppaysant** [comment]
@CristianCardosoA wrote:
> "Updating the oc_filecache table for the "avatars" line" what does this mean ? SQL command update?

Exactly, changing "permissions" column from value = 17 to value = 31 was the solution for me. Seems that the values in your db are correct (looking at your first sreenshot).
Anyway, it was two years ago, and I currently do not work on owncloud code anymore, so I can't help more :/
