### ISSUE TITLE
internal server error after update to owncloud 9.1.2-1.1

### ISSUE THREAD

**Issue by flolerchi** [owncloud/core#26739]
### Steps to reproduce
1. I made an automatic update via apt-get
2. after the finished installation I started my owncloud web interface again
3. I switched off the maintenance mode to start the web update
4. I refreshed the webside
5. an internal error was shown

### Expected behaviour
Owncloud should run like it did since the last several updates

### Actual behaviour
Internal Server Error

The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.

More details can be found in the server log.

### Server configuration
Operating system: Ubuntu 15.10
Web server: Apache/2.4.12 (Ubuntu) Server built:   Jul 15 2016 15:32:10
Database: mysql  Ver 14.14 Distrib 5.6.31, for debian-linux-gnu (x86_64) using  EditLine wrapper
PHP version: PHP 5.6.11-1ubuntu3.4 (cli)
ownCloud version: version: 9.1.2.5, versionstring: 9.1.2
Updated from an older ownCloud or fresh install:
/var/log/apt/history.log:
Start-Date: 2016-11-25  12:08:05
Commandline: apt-get upgrade
Upgrade: owncloud:amd64 (9.1.1-1.2, 9.1.2-1.1), owncloud-deps-php5:amd64 (9.1.1-1.2, 9.1.2-1.1), owncloud-files:amd64 (9.1.1-1.2, 9.1.2-1.1)
End-Date: 2016-11-25  12:08:49
Where did you install ownCloud from:
over apt-get 
Signing status (ownCloud 9.0 and above):**
not possible to access!

**List of activated apps:**

ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.0
  - comments: 0.3.0
  - contacts: 1.4.0.0
  - dav: 0.2.6
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: true
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - ownbackup: 0.3.8
  - ownnote: 1.08
  - systemtags: 0.3.0
  - tasks: 0.9.3
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - music
  - news
  - provisioning_api
  - user_external
  - user_ldap

**The content of config/config.php:**

ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "maintenance": false,
        "instanceid": "ochohkpam790",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "serverhome",
            "flolerchi.istmein.de"
        ],
        "datadirectory": "\/media\/FLO-Raid\/88_owncloud",
        "overwrite.cli.url": "https:\/\/xxx\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.2-1.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "mail_smtpauth": 1,
        "asset-pipeline.enabled": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "default_language": "en",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "session_lifetime": 86400,
        "session_keepalive": false,
        "trashbin_auto_expire": false,
        "updatechecker": false,
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "config_is_read_only": false,
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "appstore.experimental.enabled": false,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "htaccess.RewriteBase": "\/owncloud"
    }
}

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
```
[Mon Nov 28 15:26:17.046406 2016] [mpm_prefork:notice] [pid 14147] AH00163: Apache/2.4.12 (Ubuntu) OpenSSL/1.0.2d configured -- resuming normal operations
[Mon Nov 28 15:26:17.046434 2016] [core:notice] [pid 14147] AH00094: Command line: '/usr/sbin/apache2'
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"TgpHWh0Uq67UMwtuV+ej","remoteAddr":"192.168.178.33","app":"PHP","message":"trim() expects parameter 1 to be string, array given at \/var\/www\/owncloud\/lib\/private\/AppFramework\/App.php#56","level":3,"time":"2016-11-28T14:31:24+00:00","method":"GET","url":"\/owncloud\/","user":"--"}


{"reqId":"TgpHWh0Uq67UMwtuV+ej","remoteAddr":"192.168.178.33","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Session has been closed - no further changes to the session are allowed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Memory.php(52): OC\\\\Session\\\\Memory->validateSession()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Security\\\/CSRF\\\/TokenStorage\\\/SessionStorage.php(63): OC\\\\Session\\\\Memory->set('requesttoken', 'URvbmtx15C+HPXi...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Security\\\/CSRF\\\/CsrfTokenManager.php(57): OC\\\\Security\\\\CSRF\\\\TokenStorage\\\\SessionStorage->setToken('URvbmtx15C+HPXi...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/Util.php(505): OC\\\\Security\\\\CSRF\\\\CsrfTokenManager->getToken(*** sensitive parameters replaced ***)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(79): OCP\\\\Util::callRegister()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(396): OC_Template->__construct('', 'update.admin', 'guest')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(338): OC::printUpgradePage()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(841): OC::checkUpgrade(true)\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Session\\\/Memory.php\",\"Line\":119}","level":3,"time":"2016-11-28T14:31:24+00:00","method":"GET","url":"\/owncloud\/","user":"--"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

Internal Server Error

The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.

More details can be found in the server log.

Technical details

    Remote Address: 192.168.178.33
    Request ID: 0iqIFQncM3SDT+zVJl6m

**Comment by RealRancor** [comment]
@flolerchi This is a known bug in the following 3rdparty app:

> ownbackup: 0.3.8

causing this issue as you can see here: https://github.com/pbek/ownbackup/issues/7

I think you can close this issue here immediately. To get to a working oC back remove that app from your path/to/owncloud/apps folder and use a current version of that app.

**Comment by flolerchi** [comment]
I started the command update via "sudo -u www-data php occ upgrade". This solved also my problem without any uninstall of ownbackup.

**Comment by flolerchi** [comment]
With "sudo -u www-data php occ upgrade" i found now a solution without removing 3rdparty app.
