### ISSUE TITLE
8.2.9 community repo is empty

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#26730]
There are no packages in 
http://download.owncloud.org/download/repositories/8.2.9/Ubuntu_14.04/
but the final release is in http://download.owncloud.org/download/repositories/8.2.9:/testing/Ubuntu_14.04/

please fix!

**Comment by RealRancor** [comment]
@jnweiger But it is in:

https://download.owncloud.org/download/repositories/8.2/Ubuntu_14.04/

Is the version based URL in http://download.owncloud.org/download/repositories/8.2.9/Ubuntu_14.04/  really needed?

**Comment by crrodriguez** [comment]
fixed

**Comment by jnweiger** [comment]
thanks!
