### ISSUE TITLE
Database is Locked SQLITE, Upgrade 8.2.7-1.1 to 9.0.6-1.1

### ISSUE THREAD

**Issue by vanboom** [owncloud/core#26732]
### Steps to reproduce
1. `apt-get install owncloud-files=9.0.6-1.1`
2. `sudo -u www-data php occ upgrade`

### Actual behaviour
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO "oc_jobs" ("class", "argument", "last_run") VALUES(?, ?, ?)' with params ["OCA\\Federation\\SyncJob", "null", 0]:
SQLSTATE[HY000]: General error: 5 database is locked
Update failed
```

### Server configuration
Ubuntu 16.04

**Web server:** Apache

**Database:** SQLITE3

Trying to work my way through the upgrade path to the latest version, but not able to get 9.0.6 to upgrade.

Thanks!

**Comment by RealRancor** [comment]
@vanboom No need to report an bug here. Database locked messages are known issues of SQlite (see google). Thats why you shouldn't use SQlite on productive oC installations as documented at various parts of doc.owncloud.org

Please close here and migrate to MySQL or PostgreSQL before doing the upgrade. If you need further help then you can get support at https://central.owncloud.org/

**Comment by vanboom** [comment]
The upgrade path does not work.  Migrating to MySQL worked OK.  Closing this issue, BUT I still consider the upgrade failure with SQLITE to be a BUG.
