### ISSUE TITLE
owncloud.org SSL certificate has expired

### ISSUE THREAD

**Issue by AdamPS** [owncloud/core#26733]
This is an operational problem for OwnCloud, and not a bug in code, but not sure how else to report it.

owncloud.org SSL certificate has expired, so we cannot access https://owncloud.org/ - not even add a manual exception due to HSTS.

Thanks

**Comment by RealRancor** [comment]
@AdamPS I think you can close this one as https://github.com/owncloud/owncloud.org/issues/1107 was reported before

**Comment by AdamPS** [comment]
Thanks and sorry for the duplicate

**Comment by RealRancor** [comment]
No need to say sorry :-). Its not always clear which issue belongs in which repository.

Hope they fix that soon.

**Comment by draht** [comment]
it was fixed 20 minutes ago.
