### ISSUE TITLE
Notification alert can not be removed and block access to the menu in mobile browser

### ISSUE THREAD

**Issue by nasli** [owncloud/core#26749]
### Steps to reproduce
1. Open owncloud in a mobile browser and a notification appears on the top
2. Try to go to contacts app

### Expected behaviour
We can removed the alert and access to the menu
![menuappsoc](https://cloud.githubusercontent.com/assets/6570505/20762060/6f1fb9f2-b725-11e6-8fbc-0e5ac47d3b62.png)

### Actual behaviour
Menu is blocked behind the notification
![notificationalertblockmenu](https://cloud.githubusercontent.com/assets/6570505/20761695/1e28fbe0-b724-11e6-877d-f00e75dc23d6.png)

### Server configuration

**ownCloud version:** (see ownCloud admin page)
9.2.0 pre alpha, 9.2.0.3

**Updated from an older ownCloud or fresh install:**
fresh

**Where did you install ownCloud from:**
master branch 

### Client configuration
**Browser:**
Safari, iPhone 6

**Operating system:**
iOS 10.1.1

**Comment by PVince81** [comment]
Hmm ok, the notification must be made closable by passing extra arguments to the notification call.

**Comment by noveens** [comment]
@PVince81 ,
Will a button at the top-right corner to close the notification suffice for this bug?

**Comment by PVince81** [comment]
@noveens yes, but don't reimplement this yourself. Only need to pass an extra arg to `OC.Notification.showTemporary(message)`: https://github.com/owncloud/core/issues/26749#issuecomment-264169847. Add an additional function argument `{type: 'error'}`

**Comment by noveens** [comment]
@PVince81 ,
I'll look into it.

**Comment by noveens** [comment]
@PVince81 ,
So do I need to add the extra arg in all notification balloons?

**Comment by PVince81** [comment]
Not all, only the ones relevant to this issue.

If you find other error cases where it makes sense then feel free to add it too.

**Comment by noveens** [comment]
@PVince81 ,
closed?
