### ISSUE TITLE
9.1 Flood email

### ISSUE THREAD

**Issue by bat553** [owncloud/core#26740]
Hi ! I have a public cloud and I was victim of a reset password spam. 100 mail in 10 minutes... Can you add a waiting time between requests ?

PS: Sorry for my English :-/

**Comment by Kawohl** [comment]
please check your fail2ban configuration.

**Comment by Kawohl** [comment]
@bat553 
Sorry for the brief reply. You can enable timeouts and bans by installing fail2ban and adding rules for owncloud. You can find some stuff here: https://central.owncloud.org/t/fail2ban-and-owncloud-8-x-9-0-x/837 .  I will close here for now.
