### ISSUE TITLE
Bug with 1 bit bmp

### ISSUE THREAD

**Issue by Temtaime** [owncloud/core#26758]
### Steps to reproduce
1. Download http://cloud.acomirei.ru/index.php/s/0sHvBwXpMKxYxTK and unzip
2. Upload 3.bmp to the server using web ui

### Expected behaviour
The server generates correct preview image.

### Actual behaviour
Tons of

> {"reqId":"+iIwdobvVxHII3QewZ5J","remoteAddr":"10.0.0.101","app":"PHP","message":"unpack(): Type n: not enough input, need 2, have 1 at \/var\/www\/html\/owncloud\/lib\/private\/legacy\/image.php#748","level":3,"time":"2016-12-02T11:04:27+00:00","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/256\/256\/2_\u0420\u0430\u0441\u0447\u0435\u0442 \u0447\u0435\u0440\u0432\u044f\u0447\u043d\u043e\u0439 \u043f\u0435\u0440\u0435\u0434\u0430\u0447\u0438\/3.bmp","user":"denis"}
> {"reqId":"+iIwdobvVxHII3QewZ5J","remoteAddr":"10.0.0.101","app":"PHP","message":"unpack(): Type n: not enough input, need 2, have 1 at \/var\/www\/html\/owncloud\/lib\/private\/legacy\/image.php#748","level":3,"time":"2016-12-02T11:04:27+00:00","method":"GET","url":"\/index.php\/apps\/files\/api\/v1\/thumbnail\/256\/256\/2_\u0420\u0430\u0441\u0447\u0435\u0442 \u0447\u0435\u0440\u0432\u044f\u0447\u043d\u043e\u0439 \u043f\u0435\u0440\u0435\u0434\u0430\u0447\u0438\/3.bmp","user":"denis"}

The server hangs and doesn't stop to populate a log file - when i found the bug the size of the log file was about 50GB.

### Server configuration
**Operating system**: 
Centos 7.0.

**Web server:**
Cherokee.

**Database:**
MySQL.

**PHP version:**
5.6.

**ownCloud version:** (see ownCloud admin page)
9.1.2.

**Updated from an older ownCloud or fresh install:**
Updated from an older.

**Where did you install ownCloud from:**
Using owncloud repo.

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - gallery
  - templateeditor
  - updatenotification
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocikxtf5b3ao",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.acomirei.ru"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/cloud.acomirei.ru",
        "dbtype": "mysql",
        "version": "9.1.2.5",
        "dbname": "c_user",
        "dbhost": "10.0.0.101",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_domain": "cloud.acomirei.ru",
        "mail_from_address": "admin",
        "mail_smtphost": "10.0.0.101",
        "theme": "",
        "loglevel": 3,
        "maintenance": false,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "updatechecker": false
    }
}
```

**Are you using external storage, if yes which one:**
No.

**Are you using encryption:**
No.

**Are you using an external user-backend, if yes which one:**
No.

**Comment by PVince81** [comment]
Filling the logs like this is not good. Hopefully might be able to prevent this.
