### ISSUE TITLE
[When updating any app] "Es ist eine Aktualisierung verfügbar." message is not cleared when updating finished.

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/core#26769]
* Nextcloud 10.0.1
* Server Debian 8

When updating an App which requires updating, on the Apps screen section for that specific App the string `"Es ist eine Aktualisierung verfügbar."` is not cleared when the updating starts or ends.

**Comment by PVince81** [comment]
This is the bug tracker for ownCloud, not Nextcloud.
