### ISSUE TITLE
InfoParser not properly parsing single background-job, single command, etc

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26760]
### Steps

1. Add a breakpoint in `lib/private/InfoParse->parse()`
1. Open the web UI
1. When at the breakpoint, continue until it stops for either the files_trashbin or files_versions app
1. Evaluate `$array['background']['job']` and notice that it's not an array because it's a single item

```
  $array['background-jobs']      = (array[1]);
    $array['background-jobs']['job'] = (string[44]) 'OCA\Files_Trashbin\BackgroundJob\ExpireTrash';
```

When there is more than one item then it becomes an array...

For some reason the bkg job is still registered properly, but I'm not sure about the other parts.

Discovered while working on https://github.com/owncloud/core/issues/26195 where I'll add a new `sabre` XML entry.

@DeepDiver1975 this is a potential issue with any of the new info.xml tags you have added, please have a look.

**Comment by PVince81** [comment]
When did you add these new entries, hopefully only 9.2 ? Would be good to double check them all and see if they are parsed properly for single items.

Setting as critical until we can confirm that all still works properly, somehow...

@DeepDiver1975 please have a look, thanks.

**Comment by PVince81** [comment]
Just checked for commands, and it works but it's only by sheer luck.
This is from `loadCommandsFromInfoXml()`:
```
$commands                        = (array[1]);
  $commands['command']           = (string[49]) 'OCA\Federation\Command\SyncFederationAddressBooks';


// by property_get
$commands                        = (array[3]);
  $commands[0]                   = (string[22]) 'OCA\Files\Command\Scan';
  $commands[1]                   = (string[37]) 'OCA\Files\Command\DeleteOrphanedFiles';
  $commands[2]                   = (string[35]) 'OCA\Files\Command\TransferOwnership';
```

sometimes the index is a number, sometimes it's just `command` when it's a single item... a bug that cancels another one ?

**Comment by PVince81** [comment]
or maybe this is all by design... would be good if you could confirm.

**Comment by DeepDiver1975** [comment]
This codeblock is making sure this properly is populated:
https://github.com/owncloud/core/blob/master/lib/private/App/InfoParser.php#L124-L126

**Comment by PVince81** [comment]
Yeah, I figured that out in the end... a bit obscure but ok

**Comment by DeepDiver1975** [comment]
> a bit obscure but ok

I know - but this is how the xml parser works ...
