### ISSUE TITLE
php 7.1 tasks

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#26764]
This is an overview ticket to get an understanding of things which need to be done to get ownCloud ready for php 7.1

- upgrade guzzlehttp - see https://travis-ci.org/owncloud/contacts/jobs/181311505#L1460

**Comment by PVince81** [comment]
do it! or is it more complicated than just updating the composer version ?

**Comment by DeepDiver1975** [comment]
there is an api break in gruzzle 5x to 6x .... I'm having a look ....

**Comment by DeepDiver1975** [comment]
stupid me - php7.1 on stable9 is pointless

**Comment by ofus** [comment]
> stupid me - php7.1 on stable9 is pointless
Why?

**Comment by DeepDiver1975** [comment]
oc 10 will come with 7.1 support
