### ISSUE TITLE
Hook doesn't work with getRootFolder()

### ISSUE THREAD

**Issue by Kitounet** [owncloud/core#26778]
Hello everyone,

I'm a beginner in developing owncloud apps and I actually have a problem for implementing the hooks.
I followed this documentation https://doc.owncloud.org/server/9.2/developer_manual/app/hooks.html and tested with the getUserManager() function and it worked. (I saw with the logger if it worked or not)
But I'm applying the same code's logic with getRootFolder() and nothing happens.

It is a knew issues ? or am I doing something bad ?

Thanks to you.

### Steps to reproduce
1.preWrite
2.preCreate
3.postWrite
4.postCreate

### Expected behaviour
Hook should be called.

### Actual behaviour
Nothing , no error, no debug messages.

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache/2.4.18
**Database:**
SQL Lite
**PHP version:**
PHP 5.6.28
**ownCloud version:** (see ownCloud admin page)
9.2.0
**Updated from an older ownCloud or fresh install:**
fresh install
**Where did you install ownCloud from:**
Git

**Comment by PVince81** [comment]
Mind posting the code how you register the hooks for `getUserFolder()` and `getRootFolder()` ?

**Comment by PVince81** [comment]
also important: what file actions are you performing for which you expect the hook to be created.
More precisely: are you listening for hooks with the same user who is doing the file action ?

**Comment by Kitounet** [comment]
Hi,

Yes sure here is the code.
```
<?php
//app.php
namespace OCA\FilesQuota\AppInfo;

use OCP\AppFramework\App;

require_once __DIR__ . '/autoload.php';

$appli = new Application();
$appli->getContainer()->query('RootHooks')->register();

$app = new App('filesquota');
$container = $app->getContainer();

$container->query('OCP\INavigationManager')->add(function () use ($container) {
	$urlGenerator = $container->query('OCP\IURLGenerator');
	$l10n = $container->query('OCP\IL10N');
	return [
		// the string under which your app will be referenced in owncloud
		'id' => 'filesquota',

		// sorting weight for the navigation. The higher the number, the higher
		// will it be listed in the navigation
		'order' => 10,

		// the route that will be shown on startup
		'href' => $urlGenerator->linkToRoute('filesquota.page.index'),

		// the icon that will be shown in the navigation
		// this file needs to exist in img/
		'icon' => $urlGenerator->imagePath('filesquota', 'app.svg'),

		// the title of your application. This will be used in the
		// navigation or on the settings page of your app
		'name' => $l10n->t('Files Quota'),
	];
});
```
```
<?php
//application.php
namespace OCA\FilesQuota\AppInfo;

use \OCP\AppFramework\App;

use \OCA\FilesQuota\Hooks\RootHooks;
use OCP\IContainer;


class Application extends App {

	public function __construct(array $urlParams=array()){
		parent::__construct('filesquota', $urlParams);

		$container = $this->getContainer();

		/**
		 * Controllers
		 */
		$container->registerService('RootHooks', function($c) {
			return new RootHooks(
				$c->query('ServerContainer')->getRootFolder(),
				$c->query('Logger'),
				$c->query('AppName')
			);
		});

		$container->registerService('Logger', function($c) {
			return $c->query('ServerContainer')->getLogger();
		});
	}
}
```
```
<?php
//roothooks.php
namespace OCA\FilesQuota\Hooks;

use OCP\ILogger;


class RootHooks {

	private $rootFolder;
	private	$logger;
	private	$appName;

	public function __construct($rootFolder, ILogger $logger, $appName){
		$this->rootFolder = $rootFolder;
		$this->logger = $logger;
		$this->appName = $appName;
	}

	public function register() {
		$callback = function(\OCP\Files\Node $node) {
			// your code that executes before $node is writed
			$this->log("LOGTEST");
		};
		$this->rootFolder->listen('\OC\Files', 'preWrite', $callback);
	}


	public function log($message) {
		$this->logger->error($message, array('app' => $this->appName));
	}

}
```
I tried to upload a file or create a folder, I saw in the core that when a folder or a file is created it will emit the "preWrite" and "preCreate".
I'm not sure if I really get your last question. I'm using the administrator account.
My hooks is not supposed to listen every users actions ?

Thanks for your help.

**Comment by PVince81** [comment]
Thanks, I need to try this locally.

Question: you said that the hooks work with `getUserFolder` and as you seem to be writing a quota app, I think using that one should already be enough. Is there a particular reason why you prefer hooking into `getRootFolder()` instead ?

Side note: an alternative to hook is using defining and registering storage wrappers, but I don't think there is any good doc about this.

**Comment by Kitounet** [comment]
I said the hooks worked with `getUserManager() `not `getUserFolder()`, just as shown in the doc.
The class returned by `getUserFolder()` seems to not have listen function in the core, this is why I'm using `getRootFolder()`.

I saw nothing about an alternative to hooks, can I ask you more information ?

Thanks

**Comment by PVince81** [comment]
Argh, ok. I read `getUserFolder()` when you wrote `getUserManager()`.

Regarding storage wrappers, here is an example for the trashbin: https://github.com/owncloud/core/blob/master/apps/files_trashbin/lib/Storage.php#L32

And here is how to register a storage wrapper from inside an app with the presetup hook: https://github.com/owncloud/core/blob/master/apps/files_trashbin/lib/Trashbin.php#L943 and https://github.com/owncloud/core/blob/master/apps/files_trashbin/lib/Storage.php#L181
I just realized that it's all private APIs... Need to move these to the public namespace at some point.
Raised here: https://github.com/owncloud/core/issues/26786

Regarding the `getRootFolder()` hooks, I remember trying it lately and it worked. Will try again.

**Comment by PVince81** [comment]
Oh, now I remember when it was, see this ticket: https://github.com/owncloud/core/issues/20564

Does your app have the type "filesystem" ?

**Comment by Kitounet** [comment]
Thanks for the information about storage wrappers!

I found this ticket yesterday and added "filesystem" inside info.xml and it didn't solve my problem.
```
<?xml version="1.0"?>
<info>
    <id>filesquota</id>
    <name>Files Quota</name>
    <description>My first ownCloud app</description>
    <licence>AGPL</licence>
    <author>Benoît Bizet</author>
    <version>0.0.1</version>
    <namespace>FilesQuota</namespace>
	<type>
		<filesystem/>
	</type>
    <category>other</category>
    <dependencies>
        <owncloud min-version="9.0" />
    </dependencies>
</info>
```

**Comment by PVince81** [comment]
Try with `types` in plural 😄

**Comment by Kitounet** [comment]
I changed in `types` and it's still the same.
I would have preferred to have a typing error.

**Comment by PVince81** [comment]
Works for me with your code when creating a folder:

```
{"reqId":"CLE3dEkQUtbDpqpVsumT","remoteAddr":"127.0.0.1","app":"filesquota","message":"LOGTEST","level":3,"time":"2016-12-07T09:19:50+00:00","method":"MKCOL","url":"\/owncloud\/remote.php\/webdav\/x","user":"admin"}
```

I copy-paste the files from the ticket.
Had to comment out the navigation manager stuff and also commented out the `autoloader.php` line.
And in info.xml I change the type to be plural as well.

This is with the latest OC master (c206d4b0361ba8c8583aec3e49d0a9d4d77a08cc)

**Comment by PVince81** [comment]
I zipped it up for you to test on your env: https://s3.owncloud.com/owncloud/index.php/s/z4psgUO5BK2yx6I

**Comment by Kitounet** [comment]
Ok I tested it on my env and I got something strange.
I got the logs only when I'm creating an User. It's like I'm using `getUserManager()` with "preCreate".
I edited the logs message to see if I'm using the last code and it seems that I'm using the right one.

> {"reqId":"TudB5HvYuBRR6aIklvWz","remoteAddr":"127.0.0.1","app":"filesquota","message":"LOGTEST 1234","level":3,"time":"2016-12-07T09:56:37+00:00","method":"POST","url":"\/index.php\/settings\/users\/users","user":"root"}

It's using a different method and url and I don't know why.

**Comment by PVince81** [comment]
@Kitounet ah, you're creating a new user in the users page ? I think when you do that it might create the home folder (+ copying skeleton files) for that user and indirectly triggering these root folder hooks.

**Comment by Kitounet** [comment]
Yes I'm creating new users in the users page.
You have probably right because I got 3 logs when I'm creating a new user.
But is it normal that I don't receive logs when I'm uploading files or creating folder with the files page ? ?

**Comment by PVince81** [comment]
> creating folder with the files page

that's not normal. With the code I sent you this worked for me.
I also retried now with an upload, both work:

```
{"reqId":"hVQ4TBo52\/SuNPFm0jtp","remoteAddr":"127.0.0.1","app":"filesquota","message":"LOGTEST","level":3,"time":"2016-12-07T10:24:27+00:00","method":"MKCOL","url":"\/owncloud\/remote.php\/webdav\/y","user":"admin"}
{"reqId":"mhdqfKZyFHNy9\/6t\/K0P","remoteAddr":"127.0.0.1","app":"filesquota","message":"LOGTEST","level":3,"time":"2016-12-07T10:24:36+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/y\/teste.jpg","user":"admin"}
```

Does my code work in your environment ? If yes, then maybe need to figure out the small differences.

**Comment by Kitounet** [comment]
I just copied and past your codes in my env, but it doesn't work inside the files page, it worked only when I'm creating an User.

Thanks for your help again.

**Comment by PVince81** [comment]
Hmm then maybe there is a race condition related to other enabled apps ?

I'm using OC from git without any extra repos.

When you say "copy-pasted my code", do you mean overwrote your app's code ? I suggest you move away your own app and then just extract the zip as is and test. This is just in case there are some weird side effects.

**Comment by Kitounet** [comment]
I'm using only the core of Owncloud, no extra apps.
Yes I overwrote my app's code . And I did what you said and still have the same problem.

**Comment by PVince81** [comment]
Try adding a log statement before and after registering the hook, maybe that code doesn't run for some reason.

I suggest you setup a PHP debugger (with XDebug) and step into the emitter code.

Here is the stack trace I get when the hook is fired for a directory creation, this can give you an idea where to look and where it is usually fired:
```
0  OCA\FilesQuota\Hooks\RootHooks->OCA\FilesQuota\Hooks\{closure}() /srv/www/htdocs/owncloud/apps/filesquota/lib/Hooks/RootHooks.php:23
1  call_user_func_array:{/srv/www/htdocs/owncloud/lib/private/Hooks/EmitterTrait.php:98}() /srv/www/htdocs/owncloud/lib/private/Hooks/EmitterTrait.php:98
2  OC\Hooks\BasicEmitter->emit() /srv/www/htdocs/owncloud/lib/private/Hooks/EmitterTrait.php:98
3  OC\Hooks\PublicEmitter->emit() /srv/www/htdocs/owncloud/lib/private/Hooks/PublicEmitter.php:32
4  OC\Files\Node\Root->emit() /srv/www/htdocs/owncloud/lib/private/Files/Node/Root.php:118
5  OC\Files\Node\HookConnector->write() /srv/www/htdocs/owncloud/lib/private/Files/Node/HookConnector.php:78
6  OC_Hook::emit() /srv/www/htdocs/owncloud/lib/private/legacy/hook.php:105
7  OC\Files\View->runHooks() /srv/www/htdocs/owncloud/lib/private/Files/View.php:1229
8  OC\Files\View->basicOperation() /srv/www/htdocs/owncloud/lib/private/Files/View.php:1107
9  OC\Files\View->mkdir() /srv/www/htdocs/owncloud/lib/private/Files/View.php:261
10 OCA\DAV\Connector\Sabre\Directory->createDirectory() /srv/www/htdocs/owncloud/apps/dav/lib/Connector/Sabre/Directory.php:188
11 Sabre\DAV\Server->createCollection() /srv/www/htdocs/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php:1186
12 Sabre\DAV\CorePlugin->httpMkcol() /srv/www/htdocs/owncloud/lib/composer/sabre/dav/lib/DAV/CorePlugin.php:590
13 call_user_func_array:{/srv/www/htdocs/owncloud/lib/composer/sabre/event/lib/EventEmitterTrait.php:105}() /srv/www/htdocs/owncloud/lib/composer/sabre/event/lib/EventEmitterTrait.php:105
14 Sabre\Event\EventEmitter->emit() /srv/www/htdocs/owncloud/lib/composer/sabre/event/lib/EventEmitterTrait.php:105
15 Sabre\DAV\Server->invokeMethod() /srv/www/htdocs/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php:479
16 Sabre\DAV\Server->exec() /srv/www/htdocs/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php:254
17 require_once()  /srv/www/htdocs/owncloud/apps/dav/appinfo/v1/webdav.php:57
18 {main}          /srv/www/htdocs/owncloud/remote.php:164
```

**Comment by Kitounet** [comment]
OK thanks , I will look and come back at you if I have some news.

**Comment by Kitounet** [comment]
Well, I fixed the problem with a lot of luck.
During my installation of XDebug, I had to install some php libraries and I did some modifications because Ubuntu16.04 want to use php7.0 instead of php5.6.
And since my log is shown when I upload a file and create a folder.

Thank you for your help and patience.
I will keep an eye on the storage wrappers too.

**Comment by PVince81** [comment]
No worries, glad it works now.

Are you by any chance working on this feature https://github.com/owncloud/core/issues/20334 ? (number of files quota)
If yes, feel free to drop a note there.

**Comment by Kitounet** [comment]
Yes i'm working on this feature.

**Comment by Kitounet** [comment]
Hello again,

I'm sorry to reopen this subject but I'm actually trying to stop the upload of a files from an hook and I can't see any way to do that.
Did I missed something ? 

Thank you

**Comment by PVince81** [comment]
Try setting `$run` to 0 in the hook handler.

Best would be to use a storage wrapper instead, see how the quota storage wrapper works: https://github.com/owncloud/core/blob/master/lib/private/Files/Storage/Wrapper/Quota.php#L30.
Registration works this way: https://github.com/owncloud/core/blob/master/lib/private/legacy/util.php#L185.
To register from within an app, do it in the presetup hook as shown in this old app: https://github.com/owncloud/files_locking/blob/master/appinfo/app.php#L3 and https://github.com/owncloud/files_locking/blob/master/lib/lockingwrapper.php#L199.
Then from `fopen` or `file_put_contents` you can throw an exception to block upload.

By the way, this is a bug tracker not a support platform. Next time ask your question on http://central.owncloud.org/ and ping me there.

**Comment by Kitounet** [comment]
I'm really sorry,

I sent a message on [](http://central.owncloud.org/ )(h[ttps://central.owncloud.org/t/a-way-to-cancel-an-action-who-precede-a-hook/4528](url)) but no answer this is why I tried here. (sorry again)

I will look at your links and if I have other questions, I will use the platform.

Thanks again and happy new year by the way.

**Comment by PVince81** [comment]
@Kitounet no worries. Seems I wasn't subscribed to that category, subscribed now.
