### ISSUE TITLE
Remove settings/tests and core/js/tests from 9.1 tarballs

### ISSUE THREAD

**Issue by butonic** [owncloud/core#26770]
```console
➜  9.1.1-dist find . -name tests
./settings/tests
./core/js/tests
```

VeraCode warns about hardcoded passwords ... kill the tests from the tars. Master [already does](https://github.com/owncloud/core/blob/master/Makefile#L202-L203).

cc @PVince81 if you want to clean up 9.1 tarballs a little

**Comment by PVince81** [comment]
Yeah, master has the magic makefile... Will need to tweak the release scripts.

**Comment by butonic** [comment]
awesome @PVince81 being awesome!
