### ISSUE TITLE
Redirect loop

### ISSUE THREAD

**Issue by ReWage** [owncloud/core#26776]
I have fresh installation of owncloud.
After going to main page of Owncloud Chrome browser gives error "ERR_TOO_MANY_REDIRECTS".

Server configuration:

Operating system: Ubuntu 16.04.1 LTS
Web server: Ajenti V (nginx)
Database: Mysql
PHP version: 7.0
ownCloud version: 9.1.2.5

**Comment by RealRancor** [comment]
@ReWage Please note this is is a bugtracker of ownCloud. For support questions like this  https://central.owncloud.org/ needs to be used.
