### ISSUE TITLE
PHP unit tests side effect depriving legit tests from their DB connection

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26771]
Basically you have two test classes A and B (in this order, alphabetically), extending `\Test\Testcase`.
In class B you specify `@group DB` but not in class A.

For some reason class B receives `null` when calling `\OC::$server->getDatabaseConnection()`.

See reproduction case here: https://github.com/owncloud/customgroups/pull/9

@DeepDiver1975

**Comment by DeepDiver1975** [comment]
because of this https://github.com/owncloud/customgroups/pull/9#discussion_r91068083

parent implementations of setupo and teardown need to be called
