### ISSUE TITLE
Admin / Users linked to LDAP not usable with thousands of users

### ISSUE THREAD

**Issue by ennder** [owncloud/core#26780]
Hi,
We are using Owncloud here with around a thousand of users linked to our LDAP.
Owncloud is really a nice software.

The only part of it that lacks some optimisation is the Users administration.
The page takes minutes to display after a few messages from the browser telling us that it takes too much time to display. Moreover the search input can't stop this process.

We have tested with multiple versions of Firefox and Chrome.

Our current version : 9.0.2 (stable)

**Comment by ennder** [comment]
Sorry, It seems this issues duplicates this one : #26234

**Comment by ennder** [comment]
And this one :  #25922

**Comment by RealRancor** [comment]
@ennder Exactly, this looks like a duplicate of the ones above. As you're running an quite outdated version (9.0.6 and 9.1.2 are current) you don't have this fixes yet.

In general its also highly advised to always use a recent version before reporting any issues. This makes sure you're not reporting issues already fixed.

**Comment by ennder** [comment]
I close the issue the upgrade to 9.0.6 gives a big improvement on this point
