### ISSUE TITLE
Video playback fails on skipping with external files

### ISSUE THREAD

**Issue by ManOki** [owncloud/core#26799]
### Steps to reproduce
1. create some external share (via SMB/DAV, ie. DAV your own owncloud)
2. put some large video inside the share
2. publish large video to mediaplayer, ie kodi [wiki](http://kodi.wiki/view/webDAV)
3. play video and skip directly to the middle

### Expected behaviour
kodi jumps to the middle and continue playing from there
this works fine for videos, which are not external files in owncloud

### Actual behaviour
kodi stops playing the video at all, sometimes reject the skip and plays from current state

### Server configuration
**Operating system:** Linux Debian 8 Jessie

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 5.** (current Jessie Release)

**ownCloud version:** 9.1.2 (stable)

**Updated from an older ownCloud or fresh install:** updated since 6

**Where did you install ownCloud from:** official owncloud release via apt

**Signing status (ownCloud 9.0 and above):** all fine

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 0.3.0
  - contacts: 1.5.1
  - dav: 0.2.7
  - direct_menu: 0.9.2
  - documents: 0.13.1
  - external: 1.2
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - mail: 0.6.0
  - notifications: 0.3.0
  - ownnote: 1.08
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.3
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_external: 0.4
Disabled:
  - announcementcenter
  - bookmarks
  - encryption
  - files_antivirus
  - firstrunwizard
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.1.2.5",
        "updatechecker": false,
        "appstore.experimental.enabled": true,
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "loglevel": 0,
        "logtimezone": "UTC",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "enable_previews": true,
        "preview_max_filesize_image": -1,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "maintenance": false,
        "theme": "",
        "htaccess.RewriteBase": "\/owncloud",
        "overwritewebroot": "\/owncloud"
    }
}
```

**Are you using external storage, if yes which one:** smb/sftp/dav

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Kodi:** 16.1

**Operating system:** Rasbian (current release)

**Comment by PVince81** [comment]
@jknockaert IIRC you were also using Kodi with OC. 
Have you observed such issue before for range requests ?

**Comment by jknockaert** [comment]
This may be a fairly tough one to debug, as the issue may be with how the external dav backend handles range requests. When I was working on http range request support in the encryption module I had to fix quite some bugs in sabredav for it to work properly; so my suspicion is with the external backend rather than with oc.

**Comment by ManOki** [comment]
As I wrote, this is not just DAV backend. I tested SMB, FTP, SFTP and DAV.

**Comment by PVince81** [comment]
I find this a bit surprising. While I'm not sure about `fseek` support in FTP and DAV, I'm pretty sure that SFTP does support fseek. SMB likely too.

**Comment by jknockaert** [comment]
Proper functionality shouldn't depend on fseek support; there's a (inefficient) fallback implemented that simply reads through the file and abolishes the unwanted part. But of course all depends on proper implementation on the side of the backend. I will have a closer look to this one when I have time.

**Comment by jknockaert** [comment]
Well, it can still be a bug in Kodi.

**Comment by PVince81** [comment]
Indeed, there's that inefficient fallback.

I just tried the following locally:

1. Upload big buck bunny in mp4 format to a SFTP ext storage
1. Mount SFTP as "/sftp"
1. Open the video file in the web UI (with bundled video player app enabled)
1. Skip forward
1. Observe access_log

Skipping works correctly and happens quickly and I can see in access_log that it the video player indeed used range requests because the HTTP status code is 206 (partial content).

So it is likely a bug in kodi, or kodi is doing range requests in a way that ownCloud doesn't recognize or support.

@ManOki can you check your access log and see whether kodi is doing range requests ? Are you able to get the details of such requests for example with wireshark ?

CC @lenz1111

**Comment by jknockaert** [comment]
Kodi's webdav client is a quite sophisticated implementation. It may well do things no other client does while staying within the specs of the webdav protocol. So further investigation (including logging the corresponding http requests) would be the first step.

**Comment by ManOki** [comment]
I also tried playing some video directly from the normal owncloud storage (no external files, no other partition and no symbolic link etc.) and this setting works perfectly. So I guess, there is no problem within kodi but in the external files implementation in owncloud.

**Comment by jknockaert** [comment]
@ManOki The first thing to look at would be how ownCloud interacts with the external storage. But the Kodi webdav client is quite a thing, it may be optimising its requests in one way or another, resulting in different http range requests for fast (internal) owncloud storage compared to slow (external) owncloud storage.

**Comment by ManOki** [comment]
Ok, I'll do the test procedure, @PVince81 described and post the access_log.

**Comment by ManOki** [comment]
I tested it again and everything was fine this time. I don't know, what happened last time (some days ago), that the setting failed, but thanks for the help anyway. I'll close this ticket now and reopen it, if I see such an odd behaviour again. (I'll do some testing the next days or weeks).
