### ISSUE TITLE
Show changelog for update version on admin panel

### ISSUE THREAD

**Issue by mjobst-necls** [owncloud/core#26796]
### Steps to reproduce
1. Open %server_url%/index.php/settings/admin#updater
2. A hint is shown that a new version is available, but the changes to this version are not shown at this point.

### Expected behaviour
![screenshot from 2016-12-07 13-49-33](https://cloud.githubusercontent.com/assets/23121972/20968399/b7b103b0-bc84-11e6-9b92-1b96a4c00d2a.png)

Clicking the information icon a new window with the url https://owncloud.org/changelog/#latest8.2 should be opened.

### Actual behaviour
![screenshot from 2016-12-07 13-54-19](https://cloud.githubusercontent.com/assets/23121972/20968395/b0e3e71e-bc84-11e6-8e19-ed28d462aa56.png)

### Server configuration
**ownCloud version:** (see ownCloud admin page)
all

**Comment by PVince81** [comment]
Thanks, ping @VicDeo when you're done, he's the updater expert 😄
