### ISSUE TITLE
Add config.php option to enable mounting local storage

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#26801]
Currently an admin is able to mount the local root file system via files_external and (depending on permissions of the web server user) get access to all files that are not explicitly protected. In the web server document root you even have write access. I'd consider this as a real security flaw that should be turned off by default with the possibility to explicitly activate it if needed.

**Proposal:
Add config.php option 'mount_local_storage' => false**

@PVince81 @DeepDiver1975 @hodyroff

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/26653
