### ISSUE TITLE
Feature Requests - add loading while owncloud is not prepared

### ISSUE THREAD

**Issue by ymg2006** [owncloud/core#26803]
it would be so nice if a loading js added while page is not prepared (first time loading page), it would be better if that shows while logining in (after password entered).animated css or png would be so nice while it could be themed like http://tobiasahlin.com/spinkit/ or http://ricostacruz.com/nprogress/ .

**Comment by PVince81** [comment]
Unless someone is interested in contributing with a PR, closing
