### ISSUE TITLE
Upload progress bar: wrong plural for German translation

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#26804]
In the upload progress bar, German words use wrong plural.

**Wrong:**
Sekunde ==> Sekundes
Minute ==> Minutes
Stunde ==> Stundes

![image001](https://cloud.githubusercontent.com/assets/214010/21050596/e169f3d6-be1b-11e6-8fea-99f510283c3d.png)

**Correct:**
Sekunde ==> Sekunden
Minute ==> Minuten
Stunde ==> Stunden

### Steps to reproduce
1. Install 9.1.2
2. Login and switch language to "German" on Personal page
3. Upload large file

### Expected behaviour
German UI should have correct plural.

### Actual behaviour
German UI has incorrect plural.

### Server configuration

**ownCloud version:** (see ownCloud admin page)
9.1.2

**Where did you install ownCloud from:**

Docker:
https://hub.docker.com/_/owncloud/

00006728

**Comment by hodyroff** [comment]
fixed. You can do it in Transifex yourself ;) Please check in next daily.

**Comment by michaelstingl** [comment]
`{plural_s}` seems to require some PHP magic. Just changing to `{plural_n}` in Transifex breaks it.

<img width="524" alt="dateien_-_owncloud" src="https://cloud.githubusercontent.com/assets/214010/21265288/093bc8be-c3a1-11e6-99b1-557a99c6f090.png">

**Comment by michaelstingl** [comment]
introduced here: https://github.com/owncloud/core/pull/24605/files#diff-9112ab761e9b96bef644fc2c1f6e35c1 /cc @DeepDiver1975

**Comment by luckydonald** [comment]
Funfact: I'm german, but didn't see that while implementing.

**Comment by DeepDiver1975** [comment]
> Funfact: I'm german, but didn't see that coming while implementing back then.

don't worry - we fixed it - still an awesome contribution!

THX @luckydonald
