### ISSUE TITLE
hash_hmac(): Unknown hashing algorithm

### ISSUE THREAD

**Issue by caique02** [owncloud/core#26802]
### Steps to reproduce
1. It's happening randomly.
2. Not able to view any image thumbnail due to this error.
3.

### Expected behaviour
Tell us what should happen
Randomly navigating doing all kind of operations (upload / download files)

### Actual behaviour
Tell us what happens instead
It's making apache server to hang.

### Server configuration
**Operating system**:
     Publisher: solaris
       Version: 0.5.11 (Oracle Solaris 11.3.1.5.0)
 Build Release: 5.11
        Branch: 0.175.3.1.0.5.0
SunOS solapp01 5.11 11.3 i86pc i386 i86pc

**Web server:**
Server version: Apache/2.4.23 (Unix)
Server built:   Nov 30 2016 21:53:12

**Database:**
Server version: 5.5.43 MySQL Community Server (GPL)

**PHP version:**
PHP 7.0.13 (cli) (built: Dec  8 2016 19:23:23) ( ZTS )

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.1.2 (stable)

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
https://owncloud.org/

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => 'ocqh78myoxjv',
  'passwordsalt' => 'xyz',
  'secret' => 'xyz',
  'trusted_domains' => 
  array (
    0 => 'xyz',
  ),
  'datadirectory' => '/usr/local/apache2/htdocs/owncloud/data',
  'overwrite.cli.url' => 'http://www.xyz.tk/',
  'dbtype' => 'mysql',
  'version' => '9.1.2.5',
  'dbname' => 'owncloudb',
  'dbhost' => '192.168.1.105',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_xyz5',
  'dbpassword' => 'xyz',
  'logtimezone' => 'UTC',
  'installed' => true,
);
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
{
    "system": {
        "instanceid": "ocqh78myoxjv",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "ezcloud.tk"
        ],
        "datadirectory": "\/usr\/local\/apache2\/htdocs\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/www.xyz.tk\/",
        "dbtype": "mysql",
        "version": "9.1.2.5",
        "dbname": "owncloudb",
        "dbhost": "192.168.1.105",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}
or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Safari

**Operating system:**
Mac OS

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
359M Dec  8 22:18 owncloud.log
Same message:
{"reqId":"ieX+qPmDXzvDk+hFbVoc","remoteAddr":"xxxxxxxx","app":"PHP","message":"hash_hmac(): Unknown hashing algorithm: sha1 at \/usr\/local\/apache2\/htdocs\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib\/Crypt\/Hash.php#308","level":3,"time":"2016-12-09T06:18:00+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"--"}
{"reqId":"VDA4S8PVdbbHROYiVL2Y","remoteAddr":"xxxxxxxxx","app":"PHP","message":"hash_hmac(): Unknown hashing algorithm: sha1 at \/usr\/local\/apache2\/htdocs\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib\/Crypt\/Hash.php#308","level":3,"time":"2016-12-09T06:18:00+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"--"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by caique02** [comment]
![screen shot 2016-12-08 at 11 37 57 pm](https://cloud.githubusercontent.com/assets/24470770/21041373/72a99144-bd9f-11e6-896d-b74af6b3d1bf.png)

**Comment by DeepDiver1975** [comment]
> Unknown hashing algorithm: sha1

hmmm ... no sha1 algo available - no idea if we can run without it. AFAIK we use sha1 everywhere ..

please run following command to see which algos are availble:

```sh
$ php -r "print_r(hash_algos());"

**Comment by caique02** [comment]
Yeah something is going wrong. Some pictures works and some pictures don't. When I restart the apache all alogs works (sha1 sha512 and sha256) but when I start to see this error in the log file some algorithm stop to work. Not sure why. Please find bellow the result:

# /usr/local/bin/php -r "print_r(hash_algos());"
Array
(
    [0] => md2
    [1] => md4
    [2] => md5
    [3] => sha1
    [4] => sha224
    [5] => sha256
    [6] => sha384
    [7] => sha512
    [8] => ripemd128
    [9] => ripemd160
    [10] => ripemd256
    [11] => ripemd320
    [12] => whirlpool
    [13] => tiger128,3
    [14] => tiger160,3
    [15] => tiger192,3
    [16] => tiger128,4
    [17] => tiger160,4
    [18] => tiger192,4
    [19] => snefru
    [20] => snefru256
    [21] => gost
    [22] => gost-crypto
    [23] => adler32
    [24] => crc32
    [25] => crc32b
    [26] => fnv132
    [27] => fnv1a32
    [28] => fnv164
    [29] => fnv1a64
    [30] => joaat
    [31] => haval128,3
    [32] => haval160,3
    [33] => haval192,3
    [34] => haval224,3
    [35] => haval256,3
    [36] => haval128,4
    [37] => haval160,4
    [38] => haval192,4
    [39] => haval224,4
    [40] => haval256,4
    [41] => haval128,5
    [42] => haval160,5
    [43] => haval192,5
    [44] => haval224,5
    [45] => haval256,5
)

**Comment by PVince81** [comment]
Well, if the PHP function work for a while and suddenly stops working, then there is something wrong with the PHP or Apache env. I don't think it's related directly to ownCloud.

I guess that such weird side effects might appear if the server is somehow running out of memory and functions or libraries cannot properly initialize themselves. That could maybe fit with the preview creation code paths. Are these previews for huge files that are triggering the issue ?

**Comment by caique02** [comment]
No. Not big files. Sometimes one directory with only two pictures raise the error. And this only happen with pictures.

This is the output of var_dump(hash_algos())) when everything is working:
array(46) { [0]=> string(3) "md2" [1]=> string(3) "md4" [2]=> string(3) "md5" [3]=> string(4) "sha1" [4]=> string(6) "sha224" [5]=> string(6) "sha256" [6]=> string(6) "sha384" [7]=> string(6) "sha512" [8]=> string(9) "ripemd128" [9]=> string(9) "ripemd160" [10]=> string(9) "ripemd256" [11]=> string(9) "ripemd320" [12]=> string(9) "whirlpool" [13]=> string(10) "tiger128,3" [14]=> string(10) "tiger160,3" [15]=> string(10) "tiger192,3" [16]=> string(10) "tiger128,4" [17]=> string(10) "tiger160,4" [18]=> string(10) "tiger192,4" [19]=> string(6) "snefru" [20]=> string(9) "snefru256" [21]=> string(4) "gost" [22]=> string(11) "gost-crypto" [23]=> string(7) "adler32" [24]=> string(5) "crc32" [25]=> string(6) "crc32b" [26]=> string(6) "fnv132" [27]=> string(7) "fnv1a32" [28]=> string(6) "fnv164" [29]=> string(7) "fnv1a64" [30]=> string(5) "joaat" [31]=> string(10) "haval128,3" [32]=> string(10) "haval160,3" [33]=> string(10) "haval192,3" [34]=> string(10) "haval224,3" [35]=> string(10) "haval256,3" [36]=> string(10) "haval128,4" [37]=> string(10) "haval160,4" [38]=> string(10) "haval192,4" [39]=> string(10) "haval224,4" [40]=> string(10) "haval256,4" [41]=> string(10) "haval128,5" [42]=> string(10) "haval160,5" [43]=> string(10) "haval192,5" [44]=> string(10) "haval224,5" [45]=> string(10) "haval256,5" }

This is the output when start to print the errors ######:
array(46) { [0]=> string(258) "UTF-8!��-S�length!�J4���DOMAttr!��h! �W ���domattr!�������� �h!" [1]=> string(2) "oc" [2]=> string(258) "512M!{l��R�config!h�8Y �c!item!�h!4��|�item!" [3]=> string(258) "UTF-8!�pUTF-8!�%����adler32 1getUserData1�3�vtَ�getuserdata1" [4]=> string(7) "mysqlnd" [5]=> string(12599) "�!`�h!��h!�i!��h! �h!��h!`�h!��h!`�e!@�e!�-x����getname!�e!`�h!P�e!;>���recover!1�&UTF-8!a�&512M!{l��R�config!h�8Y �c!item!�h!4��|�item!��h!��-S�length!item!�+�n�����yn���� !4��|�item!_��|�data!��-S�length!��&UTF-8!��-S�length!�J4���DOMAttr!��h! �W ���domattr!�������� �h!isId!n��|�isid!��h!F�|�name!��h!BW�1�value!��h!b��ζ��tagName!�v 4���DOMText!��h! �a ���domtext!6�������IMG_XPM!handle!  �h!qؐS�handle!�>F����message!AqUTF-8!�pUTF-8!�%����adler32 1getUserData1�3�vtَ�getuserdata1getNodePath1���-َ�getnodepath1	getLineNo1 �!�0�w�	getlineno1C14NFile1��Z���c14nfile1 �QY��nodeName1 �p�s��w�	nodeValue1 ��QY��nodeType1 .v�fr� parentNode1 B��g�Ip� childNodes1 ��5v$�p� firstChild1 ҄Cn�w�	lastChild1 ����b��previousSibling1 l�j<���nextSibling1 ��r�;p� attributes1 Ϡ*o!T� ownerDocument1 b�wO��;�namespaceURI1 Q/6��w�	localName1 ��2�����textContent1�OK�!�DOMNameSpaceNode1X�eZ�Vϵdomnamespacenode1�QY��nodeName1�p�s��w� nodeValue1��QY��nodeType1Q/6��w�	localName1b�wO��;�namespaceURI1Ϡ*o!T� ownerDocument1.v�fr� parentNode1ث������DOMDocumentFragment1xP�i ;�domdocumentfragment1__construct1ߢ��>b�__construct1	appendXML1��#��w�	appendxml1�)�Q�̿DOMDocument1d���#��domdocument1 createElement1#�qnI�� createelement1createDocumentFragment1,�B.��k�createdocumentfragment1createTextNode1�&�}�w��createtextnode1 createComment1�U��mI�� createcomment1createCDATASection1ˊ���?�createcdatasection1createAttribute1m�/'Z��createattribute1createEntityReference1��������createentityreference1getElementsByTagName1��lӑ� �getelementsbytagname1 importNode1�f�F�Mq� importnode1createElementNS1�t}�^��createelementns1createAttributeNS1Nb"��createattributens1getElementsByTagNameNS1���aT��getelementsbytagnamens1getElementById1�����޳�getelementbyid1	adoptNode1��-�x�w�	adoptnode1normalizeDocument1R������normalizedocument1 renameNode1��9�a�r� renamenode1__construct1ߢ��>b�__construct1validate1�!n����validate1xinclude1�%պ��xinclude1loadHTML1Zk�qE��loadhtml1loadHTMLFile1�C^�^�loadhtmlfile1saveHTML1�X�����savehtml1saveHTMLFile1�@N�A��savehtmlfile1schemaValidate1p��š �schemavalidate1schemaValidateSource1�jn�*�schemavalidatesource1relaxNGValidate1��d�z~ʈrelaxngvalidate1relaxNGValidateSource1Q�u�2���relaxngvalidatesource1registerNodeClass1fw'o�&3�registernodeclass1��#c��implementation1N��aHS�documentElement1&��� ^��actualEncoding1[2����encoding1��"�i���xmlEncoding1.Q�WJ�r� standalone1Q�\fx�� xmlStandalone1�	]/��s� xmlVersion1�{?.��f�strictErrorChecking1T������documentURI1�à9����formatOutput1���ED@G�validateOnParse1[��Q�S��resolveExternals1��j���preserveWhiteSpace1Ɯ�����substituteEntities1g�����̿DOMNodeList1�2r#��domnodelist1n�Rm]�DOMNamedNodeMap1.���n��domnamednodemap1getNamedItem1����^�i�getnameditem1setNamedItem1%;/����setnameditem1removeNamedItem1Gd a���removenameditem1getNamedItemNS1z��4��getnameditemns1setNamedItemNS1���J}��setnameditemns1removeNamedItemNS1��4}��R�removenameditemns1������DOMCharacterData1lt3ȅ'ܻdomcharacterdataa��e��f8��n����L��n����`�_ap�e��fHn����o��n����`�_a��e��fx��n�������n����`�_ap�e��f8Hn������n����`�_a��e��f���n�������n����`�_ap�e��fhHn�������n����`�_a��e��f��n����ź�n����`�_ap�e��fX��n�������n����`�_a��e��f���n����u��n����`�_ap�e��fؿ�n����p��n����`�_a��e��f��n�������n����`�_ap�e��fX��n�����àn����`�_a��e��f���n�����àn����`�_ap�e��f���n�����àn����`�_a�g��fX��n����!Ġn����`�_ag��f�Hn�����Πn����`�_" [6]=> string(4) "512M" [7]=> string(258) "UTF-8!a�&512M!{l��R�config!h�8Y �c!item!�h!" [8]=> string(16) "/\/\/(.*):(.*)@/" [9]=> string(9) "ripemd160" [10]=> string(12) "memory_limit" [11]=> string(9) "ripemd320" [12]=> string(8589934592) "" [13]=> string(10) "tiger128,3" [14]=> string(15) "default_charset" [15]=> string(10) "tiger192,3" [16]=> string(20) "phpparser_autoloader" [17]=> string(10) "tiger160,4" [18]=> string(10) "tiger192,4" [19]=> string(14131) "}!`ae	���`�h	! �����h	!�ae��� �h	!kx�c �c!�e�����h	!-i!�be��� �h !�����@i!�ce ���`�h	!���������h	!`de��h!� ��hS�prefix!��e �)f���baseURI!r�0�|�c14n���!��eHp�e��Y!������hS�prefix!��e��h!6load! �e�h!X�-�|�load!p�esave!������e! feT˝|�save!� ��h!�fe@��e!������h!�eitem!'���e!�ge �i!h�����h	!�he �h!�������`�h	!`ie�>�|�code!<	���0�e	!�ie�h!���� �����h	!`je��� �h	!C ��ha�je@5Y �c��c.?�n����@�Ra�����5Y �c��c4@�n����@�Ra�le��c �c`�cFC�n����@�Ra�����c �c��c#��n����@�Ra`ne��c �c@�c�~�n����@�Ra�����c �c��c���n����@�R�oe�cp�e ����@�e�Q�n���������w�n�����������n���������w�n��������9��n�������n�����?d$Οn����@�o����`�_`sea����� g��eX��n����:9�n����`�_!�se������������������������������e����4��|��gp&eQDaI�HY^��te�&e�������#S���e�&e������nF �/�0�e'e��F.(�7���e0'e����&��?�M��P�e`'e����nmL�������e�'e��}�|�����e!������������������������������P������-S���f���C8m���eP(e����o��f�ş��e�(e����w�$�����e�(e#�P4n(!x�P�e�(e��f�ş��e)e�����MB�v����e@)e�����x�.ɪ��ep)e�aP�e�g�}g8��n����S֠n����`�_�����P�g�}g���n����)ڠn����`�_ث������P!g=o���������)�Q�̿�"g�=o������e5g�����c��e ����P�e�Q�n���������w�n�����������n���������w�n��������9��n�������n�����?d$Οn������o����`�_����a�e@g��e���n����<�n����`�_!������������������������������e�����-x����@g`�e����B�M8E���e� ?�>|�P�e�/e`��j������e0e����}V���b���e00e�m�"9�Z���e`0e��1%Y�U��@�e�0e`Gx�G˫���e f�a�ep�e��eش�n����H<�n����`�_!)����������������������������`P������-S���f˦ϛ�v��P�epf�����~(��ȟ��e�f:#s=]���e�f�)�?9R�ɘ�efX�(��ȟP�e0f^㦴\Yj����e`f�x�ds��0�e�fAa��e��e0�f���n�������n����`�_q���������������������������������e����4��|�`%T���٥���e�f�����h����P�e	fTT��������e@	f����2%�R_����ep	fB�$���^ߜ��e�	fA�2a鮶����e�	f�=���p��e f����,��T��P�e0 f����.S0�v����e` f����`�e��e(A6�����'�CURLE_FTP_CANT_RECONNECTA6Z7P�K>�CURLE_FTP_COULDNT_GET_SIZEA6<'_7���CURLE_FTP_COULDNT_RETR_FILEA6T�����CURLE_FTP_COULDNT_SET_ASCIIA6����CURLE_FTP_COULDNT_SET_BINARYA6������CURLE_FTP_COULDNT_STOR_FILEA6�.fN�L>�CURLE_FTP_COULDNT_USE_RESTA6���_\T=�!CURLE_FTP_USER_PASSWORD_INCORRECTA6�����CURLE_FTP_WEIRD_227_FORMATA6�+�~���CURLE_FTP_WEIRD_PASS_REPLYA6��e���CURLE_FTP_WEIRD_PASV_REPLYA6��ۯC_�CURLE_FTP_WEIRD_SERVER_REPLYA6l��$��CURLE_FTP_WEIRD_USER_REPLYA6����~�CURLE_FUNCTION_NOT_FOUNDA6�$�@*���CURLE_HTTP_RETURNED_ERRORA6y@y��2�CURLE_LDAP_SEARCH_FAILEDA6��t=y���CURLE_OPERATION_TIMEDOUTA6�f����K�CURLE_OPERATION_TIMEOUTEDA62�4t!lQ�CURLE_SSL_ENGINE_NOTFOUNDA6�ПR�~�CURLE_SSL_ENGINE_SETFAILEDA6~<�tp��CURLE_SSL_PEER_CERTIFICATEA6�b�b�7�CURLE_SSL_PINNEDPUBKEYNOTMATCHA6 �g��`�CURLE_TELNET_OPTION_SYNTAXA6��L2���CURLE_TOO_MANY_REDIRECTSA6��6�R��CURLE_UNKNOWN_TELNET_OPTIONA6�&�2R<�CURLE_UNSUPPORTED_PROTOCOLA6�ܜ�q[�CURLE_URL_MALFORMAT_USERA6�s2Ъ�� CURLINFO_CONTENT_LENGTH_DOWNLOADA6Ƌ�xx��CURLINFO_CONTENT_LENGTH_UPLOADA6O�G"&��CURLINFO_NAMELOOKUP_TIMEA6@�I�)C�CURLINFO_PRETRANSFER_TIMEA6+�KK4�CURLINFO_SSL_VERIFYRESULTA6��d�Q��CURLINFO_STARTTRANSFER_TIMEA6GDd#�>h�CURLM_CALL_MULTI_PERFORMA6�E��4\�CURL_LOCK_DATA_SSL_SESSIONA6��٤l�CURL_TIMECOND_IFMODSINCEA6�M�.�*�CURL_TIMECOND_IFUNMODSINCEA6�.i�2��CURLINFO_HTTP_CONNECTCODEA6�/򵡱ѐCURLOPT_FTP_CREATE_MISSING_DIRSA6��nF �/�CURLINFO_PROXYAUTH_AVAILA6�F.(�7�CURLOPT_FTP_RESPONSE_TIMEOUTA6lv�K��`�CURLOPT_IGNORE_CONTENT_LENGTHA6~"EcU�CURLOPT_FTP_SKIP_PASV_IPA6?��CURLOPT_FTP_ALTERNATIVE_TO_USERA6<%�>��%�CURLOPT_MAX_RECV_SPEED_LARGEA6��A�r��CURLOPT_MAX_SEND_SPEED_LARGEA6� N�\���CURLE_SSL_CACERT_BADFILEA6"�hB��K�CURLOPT_SSL_SESSIONID_CACHEA6�����[�CURLOPT_SSH_PRIVATE_KEYFILEA6�$D\K��CURLOPT_SSH_PUBLIC_KEYFILEA6}V���b�CURLOPT_CONNECTTIMEOUT_MSA6�m�"9�Z�CURLOPT_HTTP_CONTENT_DECODINGA6�1%Y�U��CURLOPT_HTTP_TRANSFER_DECODINGA6�U���%�CURLOPT_NEW_DIRECTORY_PERMSA6㦴\Yj��CURLOPT_SSH_HOST_PUBLIC_KEY_MD5A6x�ds��CURLOPT_PROXY_TRANSFER_MODEA62%�R_��CURLPROXY_SOCKS5_HOSTNAMEA6�2a鮶��CURLINFO_APPCONNECT_TIMEA65��ڿ���CURLINFO_CONDITION_UNMETA6��{��CURLOPT_SOCKS5_GSSAPI_NECA6;�%�l)*�CURLOPT_SOCKS5_GSSAPI_SERVICEA6�P������CURLFTP_CREATE_DIR_RETRYA6���;��XML_ATTRIBUTE_ENUMERATIONAd�d?�domprocessinginstruction�fA�����iselementcontentwhitespaceAľ������DOMProcessingInstructionAisWhitespaceInElementContentAisElementContentWhitespaceA���P=� �createprocessinginstructionA6�q' ��,�DOM_HIERARCHY_REQUEST_ERRA6�Z�V�D�DOM_INVALID_CHARACTER_ERRA6ŋ��V���DOM_NO_MODIFICATION_ALLOWED_ERRA6�PZ�E�b�DOM_INVALID_MODIFICATION_ERRA6�9�j/��FILTER_SANITIZE_STRIPPEDA6a�V:��R�FILTER_SANITIZE_SPECIAL_CHARSA6�\I�H-�"FILTER_SANITIZE_FULL_SPECIAL_CHARSA6������.�FILTER_SANITIZE_NUMBER_INTA6�/��pv�FIL" [20]=> string(22) "mbstring.func_overload" [21]=> string(258) "UTF-8!�%����adler32 1getUserData1�3�vtَ�getuserdata1getNodePath" [22]=> string(11) "gost-crypto" [23]=> string(7) "adler32" [24]=> string(1) "0" [25]=> string(6) "crc32b" [26]=> string(6) "fnv132" [27]=> string(7) "fnv1a32" [28]=> string(6) "fnv164" [29]=> string(7) "fnv1a64" [30]=> string(5) "joaat" [31]=> string(10) "haval128,3" [32]=> string(10) "haval160,3" [33]=> string(10) "haval192,3" [34]=> string(10) "haval224,3" [35]=> string(10) "haval256,3" [36]=> string(10) "haval128,4" [37]=> string(10) "haval160,4" [38]=> string(10) "haval192,4" [39]=> string(10) "haval224,4" [40]=> string(10) "haval256,4" [41]=> string(10) "haval128,5" [42]=> string(10) "haval160,5" [43]=> string(10) "haval192,5" [44]=> string(10) "haval224,5" [45]=> string(10) "haval256,5" }

**Comment by DeepDiver1975** [comment]
According to the log this is not related to image processing. This happens while processing notifications

**Comment by caique02** [comment]
![screen shot 2016-12-09 at 1 23 46 am](https://cloud.githubusercontent.com/assets/24470770/21043916/37126cf0-bdae-11e6-8494-08322f7ce639.png)

**Comment by caique02** [comment]
As you can see the pic.jpeg with 30k does not shows the thumbnail but the png file with 144KB shows.

**Comment by caique02** [comment]
Seems to be something related to jpg and jpeg pictures. I uploaded a lot of png files and they're all working correct. I'll attach the picture.

**Comment by caique02** [comment]
![screen shot 2016-12-09 at 1 38 00 am](https://cloud.githubusercontent.com/assets/24470770/21044339/4d65f740-bdb0-11e6-93d1-cd933867fe1f.png)
