### ISSUE TITLE
ownCloud 9.1.x: Current user is not logged in

### ISSUE THREAD

**Issue by maximd1** [owncloud/core#26828]
Hello,

after upgrade from 9.0.4 to 9.1.2 (and 9.1.3) I can't login to the ownCloud via WebUI - clean login page after the entering credentials. I am getting following error message in the ownCloud.log:

{"reqId":"WFK-zydSIMV@7YkRpthzVwAAAAQ","remoteAddr":"192.168.0.1","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2016-12-15T16:07:43+00:00","method":"GET","url":"\/apps\/files\/","user":"--"}

I can login and work with ownCloud through the mobile app and WebDAV.

My browsers are Chrome 54.0.2840.99 m (64-bit), Firefox 38.0.1. 

Server where ownCloud is installed is:

CentOS 7.2.1511
Apache 2.4
PostgreSQL 9.6
PHP 5.6.28 (cli) (built: Nov 10 2016 20:36:59)
ownCloud:
  owncloud-9.1.3-1.1.noarch
  owncloud-deps-php5-9.1.3-1.1.noarch
  owncloud-files-9.1.3-1.1.noarch

Installed apps:

Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - files_sharing
  - user_external
  - user_ldap

Browser's consoles are clean.

session.save_handler = memcache (but the same behaviour is with "files").

Please help.

Thank you.

**Comment by RealRancor** [comment]
@maximd1 Please fill out the complete issue template shown when creating a new issue. Especially the installed apps are important, thats also why this issue template is asking you that details you're currently missing.

**Comment by maximd1** [comment]
Please see update above.

**Comment by PVince81** [comment]
Can you temporarily disable memcache and see if it works properly without ?

**Comment by RealRancor** [comment]
> Can you temporarily disable memcache and see if it works properly without ?

Good point. @maximd1 Please also post your config.php (thats why i had asked you to fill out the issue template). If you fill out the complete issue template it really helps here so its not needed to ask again for informations which you could have already provided.

**Comment by maximd1** [comment]
The same issue with session.save_handler = "files":

{"reqId":"WFPKHcpX4SOGAlsUIEKiGQAAAAQ","remoteAddr":"192.168.0.1","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2016-12-16T11:03:57+00:00","method":"GET","url":"\/apps\/files\/","user":"--"}

/etc/php.ini:

session.save_handler = files
session.save_path = "/tmp"

/etc/httpd/httpd.conf:

<VirtualHost *:443>
    ServerAdmin admin@domain.com
    ServerName ****************
    ServerAlias *************
    DocumentRoot /var/www/owncloud
    ErrorLog /var/log/httpd/oc-error_log
    CustomLog /var/log/httpd/oc-access_log common
    DirectoryIndex index.html
    AddDefaultCharset UTF-8

    SSLEngine on
    SSLOptions +StrictRequire

    SSLProtocol -all +TLSv1 +SSLv3
    SSLCipherSuite HIGH:MEDIUM:!aNULL:+SHA1:+MD5:+HIGH:+MEDIUM

    SSLVerifyClient none
    SSLProxyEngine off

    SSLCertificateFile /etc/httpd/conf/crt/1.crt
    SSLCertificateKeyFile /etc/httpd/conf/crt/1.key

    Header always add Strict-Transport-Security "max-age=15768000"

    SetEnv HOME /var/www/owncloud
    SetEnv HTTP_HOME /var/www/owncloud

    <Directory /var/www/owncloud/>
             SSLRequireSSL
             Options FollowSymLinks
             AllowOverride All
             Order Allow,Deny
             Allow from all

              SetEnv MOD_X_SENDFILE_ENABLED 1
              XSendFile On
              XSendFilePath /var/tmp
    </Directory>
</VirtualHost>


config.php:

<?php
$CONFIG = array (
  'debug' => true,
  'instanceid' => 'occa32317cf9',
  'passwordsalt' => '***************',
  'secret' => '*******************************',
  'trusted_domains' =>.
  array (
    0 => 'domain1',
    1 => 'domain2',
  ),
  'datadirectory' => '/mnt/NAS/HomeCloud',
  'overwrite.cli.url' => 'https://********',
  'dbtype' => 'pgsql',
  'version' => '9.1.3.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost:5432',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => '*************',
  'installed' => true,
  'mail_smtpmode' => 'php',
  'mail_from_address' => 'services',
  'mail_domain' => '*******',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '587',
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'services',
  'mail_smtppassword' => '**********',
  'mail_smtpsecure' => 'tls',
  'loglevel' => 0,
  'trashbin_retention_obligation' => 'auto',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\OC\Memcache\Memcached',
  'memcached_servers' => array(
       array('127.0.0.1', 11211),
  ),
  'asset-pipeline.enabled' => true,
  'htaccess.RewriteBase' => '/',
  'updatechecker' => false,
);

**Comment by RealRancor** [comment]
> 'memcache.distributed' => '\OC\Memcache\Memcached',

This is what i was looking after. Have you restarted the memcached on the system after the upgrade?

**Comment by maximd1** [comment]
yes, sure

**Comment by RealRancor** [comment]
Then try to remove this from your config.php:

```
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\OC\Memcache\Memcached',
  'memcached_servers' => array(
       array('127.0.0.1', 11211),
  ),
```

I think thats what @PVince81 is referring to:

> Can you temporarily disable memcache and see if it works properly without ?

**Comment by maximd1** [comment]
I removed the memcache's directives - nothing happened, the same issue.

**Comment by maximd1** [comment]
I fixed the issue by session.auto_start = 0.

**Comment by RealRancor** [comment]
@PVince81 Something to document or even something for the check of oC?

**Comment by RealRancor** [comment]
Ref: https://github.com/owncloud/documentation/issues/2769

**Comment by maximd1** [comment]
Thank you.
