### ISSUE TITLE
API to get user's storage usage

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26829]
Use cases:

- an admin wants to check how much storage is used vs quota by every user (storage report)
- an admin wants to check the storage usage vs quota of a specific user

If we decide to add this on the provisioning API, I suggest to add a new specific endpoint to query storage usage data + quota. We should not reuse the existing endpoints because adding this info could make these calls slower, even for those who are not interested in the extra values.

Estimate 4-5 md (which includes API design)

Thoughts ? @hodyroff @pmaier1 @DeepDiver1975

**Comment by PVince81** [comment]
For reference, the magic SQL query to find that information: https://github.com/owncloud/core/issues/1344#issuecomment-245526902

**Comment by PVince81** [comment]
Already available through provisioning API:
```
  % curl -X GET --user admin:admin http://localhost/owncloud/ocs/v1.php/cloud/users/admin
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <enabled>true</enabled>
  <quota>
   <free>1073651712</free>
   <used>163</used>
   <total>1073651875</total>
   <relative>0</relative>
  </quota>
  <email/>
  <displayname>admin</displayname>
  <two_factor_auth_enabled>false</two_factor_auth_enabled>
 </data>
</ocs>
```

**Comment by tummimadhu** [comment]
This Data is shown only for Admin i.e 
 <quota>
   <free>1073651712</free>
   <used>163</used>
   <total>1073651875</total>
   <relative>0</relative>
  </quota>

But for user it does not show fields under quota, it just GET's
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data>
  <enabled>true</enabled>
  <quota/>
  <email/>
  <displayname>user3</displayname>
 </data>
</ocs>

Any Idea how to get these fields for user as well???

Thanks in Advance.

**Comment by PVince81** [comment]
@tummimadhu please open a new issue and use the issue template there and specify your OC version and also more details about what you mean with "user". AFAIK regular users cannot use the provisioning API unless they are group admins.

**Comment by tummimadhu** [comment]
Sure, reported a fresh issue and it also worked as the user needs to be logged in to get the quota details
