### ISSUE TITLE
Download link for VHDX-Image broken

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#26833]
### Steps to reproduce
1. owncloud.org
2. download appliance, choose vhdx image
3. error 404 for https://download.owncloud.org/community/production/vm/Ubuntu_14.04-owncloud-9.1.3-1.1-201612151819.vhdx.zip

@enoch85 

reported in the forum: https://central.owncloud.org/t/owncloud-9-1-3-vhdx-appliance-file-missing-not-found-on-this-server/4571

**Comment by Kawohl** [comment]
@jnweiger 
@crrodriguez

**Comment by jnweiger** [comment]
https://download.owncloud.org/community/production/vm/Ubuntu_14.04-owncloud-9.1.3-1.1-201612151819.vhdx.zip
is back.
