### ISSUE TITLE
owncloud 9.0.7 - Centos 6 - files missing in repo

### ISSUE THREAD

**Issue by UH-Nerion** [owncloud/core#26857]
Hello,

at http://download.owncloud.org/download/repositories/9.0/CentOS_6/ the files for owncloud 9.0.7 is missing. So I am unable to upgrade from owncloud 8.2 to 9.0.7

Only owncloud-files-9.0.7-1.1.noarch.rpm is available, but owncloud-9.0.7-1.1.noarch.rpm is missing.

Could you check this urgently please.
I am unable to upgrade from 8.2 to 9.1 because of missing step to upgrade to 9.0

Thanks

**Comment by UH-Nerion** [comment]
Seems to be that owncloud-9.0.7-1.1.noarch.rpm is not needed for upgrade.

**Comment by PVince81** [comment]
@crrodriguez please have a look

**Comment by RealRancor** [comment]
@PVince81 This can be closed. For CentOS 6 only the owncloud-files package is available as explained here:

https://doc.owncloud.org/server/9.0/admin_manual/installation/linux_installation.html#changes-in-owncloud-9

**Comment by PVince81** [comment]
@RealRancor thanks for the clarification
