### ISSUE TITLE
Update version in master to 10.0.0.X

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#26866]
Current master version is 9.2.0.3 it should be changed before releasing.

It will require also to update the minimum required version in apps.

**Comment by PVince81** [comment]
@IljaN I'll let you take care of this. It's an opportunity to surf around all bundled app repos to get to know them a bit 😄 
I suggest you start with the release tarballs to find out what's bundled.

**Comment by SergioBertolinSG** [comment]
https://doc.owncloud.org  here is is still using 9.2 also.

**Comment by IljaN** [comment]
@PVince81 Is it sufficient to modify the version.php in core, and  owncloud min/max Version in info.xml of every bundled app?

**Comment by PVince81** [comment]
@IljaN yes, that should be enough. Thanks

**Comment by IljaN** [comment]
@PVince81 PR's for all bundled apps have been created, altough I am seening a few CI fails, because Jenkins apparently checks out version 9.2 thus the apps can not be installed.
