### ISSUE TITLE
Shared Calender links has changed

### ISSUE THREAD

**Issue by JB1985** [owncloud/core#26862]
### Steps to reproduce
1. Add or delete a event in Lightning (maybe in ios too?)

### Expected behaviour
It should be add a event or to delete one.

### Actual behaviour
Event is not added, get 404 in the error logs.

### Server configuration
**Operating system**: Debian jessie

**Web server:** Apache 2.4

**Database:** mySQL5.5

**PHP version:** PHP5.6

**ownCloud version:** 9.1.3

**Updated from an older ownCloud or fresh install:** Updated from 9.0.1

**Where did you install ownCloud from:** from sources

**Signing status (ownCloud 9.0 and above):**

**Are you using external storage, if yes which one:** local
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Thunderbird with Lightning

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
404 error
```

After updating owncloud from 9.0.1 to 9.0.3 the link to the calenders has changed from remote.php/caldav to remote.php/dav and it isnt possible to add a event with the old link.

I must delete the calender in lighning with the old link and add new with the new link, than it works.

On my own calender, works well with the old link. Only with shared calender with write permission I cant write/delete anything.

**Comment by PVince81** [comment]
> 404 error

No actual log entries ?

**Comment by PVince81** [comment]
Also post the result of `select * from oc_appconfig where appid='core'`

**Comment by PVince81** [comment]
config.php would be useful too (in case of memcache or other such subtleties)

**Comment by PVince81** [comment]
@DeepDiver1975

**Comment by JB1985** [comment]
Log:

[22/Dec/2016:08:51:49 +0100] "PUT /remote.php/caldav/calendars/USER/pers%C3%B6nlich1_shared_by_user/008e6bdd-bfd5-49e2-9ec6-7c579cf04b93.ics HTTP/1.1" 404 6975 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Thunderbird/45.5.1 Lightning/4.7.4"

SQL result:

appid 	configkey 	configvalue
core 	global_cache_gc_lastrun 	1437630557
core 	installedat 	1416301481.0023
core 	lastcron 	1482389424
core 	lastupdateResult 	[]
core 	lastupdatedat 	1482239505
core 	oc.integritycheck.checker 	[]
core 	public_caldav 	calendar/share.php
core 	public_calendar 	calendar/share.php
core 	public_documents 	documents/public.php
core 	public_files 	files_sharing/public.php
core 	public_gallery 	gallery/public.php
core 	public_webdav 	dav/appinfo/v1/publicwebdav.php
core 	remote_caldav 	dav/appinfo/v1/caldav.php
core 	remote_calendar 	dav/appinfo/v1/caldav.php
core 	remote_carddav 	dav/appinfo/v1/carddav.php
core 	remote_contacts 	dav/appinfo/v1/carddav.php
core 	remote_dav 	dav/appinfo/v2/remote.php
core 	remote_files 	dav/appinfo/v1/webdav.php
core 	remote_filesync 	files/appinfo/filesync.php
core 	remote_mozilla_sync 	mozilla_sync/appinfo/remote.php
core 	remote_webdav 	dav/appinfo/v1/webdav.php
core 	repairlegacystoragesdone 	yes
core 	shareapi_allow_public_upload 	yes

Part of config.php

 'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'loglevel' => 4,
  'trashbin_retention_obligation' => 'auto',
  'debug' => false,
  'htaccess.RewriteBase' => '/',

**Comment by DeepDiver1975** [comment]
> After updating owncloud from 9.0.1 to 9.0.3 the link to the calenders has changed from remote.php/caldav to remote.php/dav

this change did happen from 8.2 to 9.0 - nothing new.
But the missing write permission is an issue ....

**Comment by DeepDiver1975** [comment]
> [22/Dec/2016:08:51:49 +0100] "PUT /remote.php/caldav/calendars/USER/pers%C3%B6nlich1_shared_by_user/008e6bdd-bfd5-49e2-9ec6-7c579cf04b93.ics HTTP/1.1" 404 6975 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Thunderbird/45.5.1 Lightning/4.7.4"

do you see any log entries the same time in data/owncloud.log?

**Comment by JB1985** [comment]
No. nothing in the owncloud.log

But sorry, I have updated 9.1.1 to 9.1.3

**Comment by DeepDiver1975** [comment]
please set the log level to debug(0) and let's see ...

**Comment by JB1985** [comment]
Exception: {"Message":"HTTP\/1.1 404 Principal with name users not found","Exception":"Sabre\\DAV\\Exception\\NotFound","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(76): Sabre\\DAVACL\\AbstractPrincipalCollection->getChild('users')\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(71): Sabre\\DAV\\Tree->getNodeForPath('principals\/user...')\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(903): Sabre\\DAV\\Tree->getNodeForPath('principals\/user...')\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(768): Sabre\\DAV\\Server->getPropertiesForPath('principals\/user...', Array, 0)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Schedule\/Plugin.php(568): Sabre\\DAV\\Server->getProperties('principals\/user...', Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Schedule\/Plugin.php(284): Sabre\\CalDAV\\Schedule\\Plugin->getAddressesForPrincipal('principals\/user...')\n#6 [internal function]: Sabre\\CalDAV\\Schedule\\Plugin->calendarObjectChange(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response), Object(Sabre\\VObject\\Component\\VCalendar), 'calendars\/USER...', false, true)\n#7 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#8 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(889): Sabre\\Event\\EventEmitter->emit('calendarObjectC...', Array)\n#9 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(771): Sabre\\CalDAV\\Plugin->validateICalendar('BEGIN:VCALENDAR...', 'calendars\/rzkv0...', false, Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response), true)\n#10 [internal function]: Sabre\\CalDAV\\Plugin->beforeCreateFile('calendars\/rzkv0...', 'BEGIN:VCALENDAR...', Object(OCA\\DAV\\CalDAV\\Calendar), false)\n#11 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#12 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1034): Sabre\\Event\\EventEmitter->emit('beforeCreateFil...', Array)\n#13 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(523): Sabre\\DAV\\Server->createFile('calendars\/rzkv0...', 'BEGIN:VCALENDAR...', NULL)\n#14 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#15 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#16 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#17 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#18 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/caldav.php(83): Sabre\\DAV\\Server->exec()\n#19 \/var\/www\/owncloud\/remote.php(164): require_once('\/var\/www\/ownclo...')\n#20 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAVACL\/AbstractPrincipalCollection.php","Line":118,"User":"USER"}

**Comment by DeepDiver1975** [comment]
this was fixed with 10.0.0 - see https://github.com/owncloud/core/pull/27792
