### ISSUE TITLE
Endless login-loop

### ISSUE THREAD

**Issue by UnitedMarsupials** [owncloud/core#26868]
Hello!
I am trying to setup ownCloud for the first time and can not get past the "endless login" redirection loop. I've found a number of references to the problem online, none with a definite solution.
Here is my configuration:

- FreeBSD-10.3
- Apache-2.4.23
- PHP-7.0.14 (using FPM)
- PostgreSQL-9.3.15
- ownCloud-9.1.2

ownCloud is installed under `/opt/www/owncloud` and I have a dedicated vhost just for it: oc.example.net

The `owncloud.conf` is thus:
```
<VirtualHost *:8443>
	SSLEngine	on
	SSLCertificateFile	/opt/certs/example.net.crt
	SSLCertificateKeyFile	/opt/certs/example.net.key


	ServerName	oc.example.net
	ServerAlias	oc.example.com

	LogLevel	proxy:trace3
	ProxyPassMatch	.*\.php.*	fcgi://127.0.0.1:9000/opt/www/owncloud$0

	DocumentRoot	/opt/www/owncloud
	#DirectoryIndex	index.php

	<Directory /opt/www/owncloud>
		AllowOverride	All
		Require	all granted
		SetEnv HOME /opt/www/owncloud
		SetEnv HTTP_HOME /opt/www/owncloud
	</Directory>
</VirtualHost>
```

There is an OC-provided `.htaccess` inside the `/opt/www/owncloud` -- I did not modify it.

The problem, as I say, is a continuous redirection loop of https://oc.example.net:8443/index.php/login to itself. Using `tcpdump` on port 9000, I can see the application repeatedly replying with the following headers:
```
Status: 302 Found
X-Powered-By: PHP/7.0.14
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Security-Policy:default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Location: https://oc.example.net:8443/index.php/login
Content-type: text/html; charset=UTF-8
```
Please, advise. Thank you!

**Comment by RealRancor** [comment]
@UnitedMarsupials See https://github.com/owncloud/core/issues/7719

Switch to

1.Apache + mod_php (officially supported)
2. nginx + php-fpm (community supported)

Both combinations are not showing this issue

**Comment by UnitedMarsupials** [comment]
That's a strange response, @RealRancor. More like something a low-paid front-end "support engineer" would read from his script over the phone: "You use what? Unix? Sorry, we only support Windows and MacOS here."

Of course, people have used Apache + php-fpm -- indeed, [some documentation](https://doc.owncloud.org/server/9.0/admin_manual/installation/source_installation.html)  mentions such a combination. Is the support "official"? Who cares -- I'm not filing a warranty claim here... If you have nothing to say, don't say anything.

**Comment by UnitedMarsupials** [comment]
Having added some debug statements, I can see, that the `handleLogin`-method goes through the three known methods:

- handleApacheAuth
- tryTokenLogin
- tryBasicAuthLogin

and finally returns `false`, which causes another redirect to login. But I'm never prompted for authentication -- not by the browser, not by a form.  Another debug statement confirms, that the attempt to `OC_App::loadApps(['authentication'])` _succeeds_ -- and yet, I see no login-prompts.

Should Apache be asking for authentication (Basic, Require valid-user)?

**Comment by RealRancor** [comment]
@UnitedMarsupials This is a bugtracker for ownCloud, no support forum. Furthermore it is known that oC won't run with Apache + php-fpm as already pointed: https://github.com/owncloud/core/issues/7719 and they won't change that: https://github.com/owncloud/core/issues/7719#issuecomment-238562035

This means "official support", and yes you need to care about that when opening and issue for a problem which is already known.

**Comment by UnitedMarsupials** [comment]
Whatever, @RealRancor, whatever. All one needs to get Apache + FPM combo to work is a change like:
```
-      ProxyPassMatch  .*\.php.*       fcgi://127.0.0.1:9000/opt/www/owncloud$0
+      <FilesMatch "\.php$">
+                SetHandler "proxy:fcgi://127.0.0.1:9000"
+      </FilesMatch>
```
Found on [this page](https://help.nextcloud.com/t/endless-redirect-302-given-back-from-index-php/1651/6).

**Comment by mkormendy** [comment]
Thanks @UnitedMarsupials!
