### ISSUE TITLE
[Question] Changing the background of the login page

### ISSUE THREAD

**Issue by Somebody2804** [owncloud/core#26878]
Hi! I'm not sure if this is an issue or not but here you go.

I'm trying to change the background on the login screen page of owncloud 9.1.3 because of reasons ;)
I've looked through documentation and couldn't find anything there, and I've experimented with config.php but had no success there.

> /* log in screen background color */
/* gradient of the header color and a brighter shade */
/* can also be a flat color or an image */

This exists in the config.php file but I can't figure out how to code an image to display instead of a gradient.

All help is much appreciated!

Thanks!

**Comment by RealRancor** [comment]
@Somebody2804 Please note this is a bugtracker of ownCloud, no support channel. For such questions please use https://central.owncloud.org/ instead. There you will find a few existing posts how to achieve what you're looking for. Furthermore changing such theming is also documented at https://doc.owncloud.org
