### ISSUE TITLE
[THEME] Change list page

### ISSUE THREAD

**Issue by quentingosset** [owncloud/core#26879]
Hello, I call you because I have a question and I would like to know if it is achievable.

Here I already own my own cloud theme and I would like to apply it to owncloud. Currently I succeeded for the login page, but I would like to edit this page: /owncloud/index.php/apps/files/ Is this possible?
If this is not possible, is it possible to recover some function of owncloud and inject them into my own design?

Thanks for your support.

**Comment by PhilippSchaffrath** [comment]
It is possible to overwrite app templates through a theme. Please refer to https://doc.owncloud.org/server/9.1/developer_manual/core/theming.html

Although keep in mind, in 10.0 theming will be possible with a more simple directory structure. Documentation will be updated accordingly when its time :)

**Comment by PVince81** [comment]
Please note that this is a bug tracker and not a support platform. For support, see http://owncloud.org/support
