### ISSUE TITLE
Remove "Your storage is full" if quota is explicitly set to 0

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26874]
In some use cases, the admin sets the quota to zero to create a read-only account.
Such account can still receive shares and use these.

In these scenarios, the message "Your storage is full" in the web UI doesn't make sense so it should be removed.

Might also be relevant for the future guest account feature.

CC @butonic @pmaier1

**Comment by grischdian** [comment]
Tried to get the error but cannot reproduce it. Where do you get the "Your Storage is full"? 
Created a new clean Instance and added a User with 0B Quota. Shared a folder but could not get the message to appear.

**Comment by AkshitKrNagpal** [comment]
Hi @PVince81 , @grischdian 
I am new here.
I was also unable to reproduce message "Your Storage is full".
But messages like "You are using 0 B of 0 B" and "Error uploading file, Not enough free space, only 0B is left" doesn't make sense. 

Also I would like to point out that if admin sets user quota to 0B, that user can still do the following things.
- create empty text files and share with others
- edit and share files (if admin accidentally gave him permission)

**Comment by pmaier1** [comment]
Yes, the mentioned error messages are meaningless and should be removed in case 'quota=0'
Furthermore, thanks for the input @AkshitKrNagpal:
> create empty text files and share with others

-> should be prevented if quota=0

> edit and share files (if admin accidentally gave him permission)

-> I'd consider this as expected behavior if permissions are granted.

**Comment by PVince81** [comment]
Redid my steps:

1. Setup OC 9.1.3 locally
1. Login as admin
1. Create a user "user1"
1. Set that user's quota to "0" and hit enter (it will become "0 B")
1. Login as "user1"

You're right, it doesn't happen in OC 9.1.3 nor master.

Not sure what I did to make it happen. If I see it again, I'll reopen.
Sorry for the noise.
