### ISSUE TITLE
Download links broken

### ISSUE THREAD

**Issue by tflidd** [owncloud/core#26877]
https://central.owncloud.org/t/download-von-version-8-0-16-wo/4707

also broken from owncloud.org/changelog as well as some others.

**Comment by zpanderson** [comment]
I'm having the same issue.  Is there any alternative download as a workaround?

**Comment by hansa-git** [comment]
Would be great if someone could replace the broken links from this site (https://central.owncloud.org/t/owncloud-server-maintenance-releases-8-0-16-8-1-11-8-2-9-9-0-6-and-9-1-2/3801), so all downloads are available again. The Updater in owncloud just downloads a file named 8.0.16.zip that is 0 Bytes big...

**Comment by tflidd** [comment]
@jnweiger

**Comment by jnweiger** [comment]
I've tested the 5 links in the initial post. They all seem to work by now. Um, that is -- at least for me??

**Comment by hansa-git** [comment]
Yeah, now they work.

They have been corrected 2 days after my post.

 

Von: Jürgen Weigert [mailto:notifications@github.com] 
Gesendet: Dienstag, 3. Januar 2017 11:32
An: owncloud/core
Cc: hansa-git; Comment
Betreff: Re: [owncloud/core] Download links broken (#26877)

 

I've tested the 5 links in the initial post. They all seem to work by now. Um, that is -- at least for me??
