### ISSUE TITLE
Each synchronization attempt stalls, since an initial synchronization was forcefully interrupted

### ISSUE THREAD

**Issue by stefaanderoeck** [owncloud/core#26881]
Setup:
- owncloud server 9.1.3 (on VPS running Ubuntu 14.04)
- owncloud client 2.2.4 (on laptop running Mint 18)

### Steps to reproduce
1. Add files to laptop's owncloud directory
2. During their synchronization, cause out-of-memory killing on the server, which in turn causes the synchronization to fail. 
3. Try to recover from this by synchronizing again

### Observed behaviour
Synchronization after the initial error condition stalls, i.e. waits forever, until it triggers a timeout, and then repeats this over and over. 

### Expected behaviour
Ideally, synchronization would just succeed. 
If errors occur during further synchronization attempts, they should indeed be that: errors - instead of just pausing forever. If any files are still marked as locked (due to an initial error condition), they should be skipped, and other files should still be synchronized. 

### Server configuration
**Operating system**: Ubuntu 14.04.05 LTS
**Web server:** apache 2.4.7
**Database:** mysql 5.5.53
**PHP version:** 5.5.9
**ownCloud version:** 9.1.3
**Updated from an older ownCloud or fresh install:** updated
**Where did you install ownCloud from:** deb http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/ /
**Signing status (ownCloud 9.0 and above):**
No errors have been found.
**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - galleryplus
  - user_external
  - user_ldap
**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc1ikcpuige5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "167.160.191.164",
            "vps3.stefaanenhanne.be",
            "cloud.stefaanenhanne.be",
            "vps4.stefaanenhanne.be"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/cloud.stefaanenhanne.be\/",
        "dbtype": "mysql",
        "version": "9.1.3.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}
**Are you using external storage, if yes which one:** local/smb/sftp/...
  no
**Are you using encryption:**
  yes (ssl certificate)
**Are you using an external user-backend, if yes which one:**
  no, not currently

### Client configuration
**Browser:** not applicable
**Operating system:**  Mint 18
owncloud desktop client: (owncloud --version)
ownCloud version 2.2.4
Using Qt 4.8.7

#### Web server error log
[error-owncloud.log.gz](https://github.com/owncloud/core/files/675617/error-owncloud.log.gz)

#### ownCloud log (data/owncloud.log)
[owncloud.log.gz](https://github.com/owncloud/core/files/675592/owncloud.log.gz)

#### Browser log
not applicable

#### Further information:
1) OOM killing happened on: Dec 26 11:55:26 EET
2) Mysql server has not been restarted since, nor has it logged any error message

**Comment by PVince81** [comment]
@guruz

**Comment by guruz** [comment]
What do you mean after the timeout this happens over and over?
What does the client UI show?
What do you see when running the client with log output 
```owncloud --logfile -```
thanks

**Comment by stefaanderoeck** [comment]
What I see in the client UI, is that on each synchronization attempt, after only seconds, it claims to have synchronized a small number of files and a small amount of data (less than 10Mb). But that's where it stays. The synchronization speed (Mb/second) then lowers and lowers, estimated time becomes "# years" rather than "# minutes". Until then finally it times out, and starts over again. 

I have looked at the owncloud client logfile, but no new messages appear while timing out, nor did I notice anything out of the ordinary in the messages appearing from the start of synchronization up until timing out. 

Eventually, it recovers, but seemingly not within the first 24h after the initial error (I suspect server-side locks on the files pending synchronization).

**Comment by guruz** [comment]
I wonder if a Qt 5 based build could help here, we had glitches with connectivity that were fixed by using a different Qt version.

The Qt 5 builds are work in progress

**Comment by stefaanderoeck** [comment]
I don't think connectivity is the issue here. Connections get dropped, that's life, people move around with their laptop, jump from one Wifi to the other, or just close their laptop such that it goes to sleep...

What I am concerned about here is that, after loss of connectivity, this can apparently result in synchronizations that don't recover (within the first 24h, give or take).

**Comment by guruz** [comment]
@stefaanderoeck Please try the 5.6.2 based builds: https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client

(Ref https://github.com/owncloud/client/issues/5470 )

**Comment by PVince81** [comment]
if the problem persists with recent versions of OC and the clients, please reopen
