### ISSUE TITLE
file direct link of a shared folder

### ISSUE THREAD

**Issue by msarmad2** [owncloud/core#26889]
is there any way to make direct link of a file from a shared folder in owncloud.
e.g: I have a shared folder by:
https://fumdrive.um.ac.ir/index.php/s/AiCd9aLVqEQt7J
and a file in it link:
text.txt
and I want to make direct link of the file (file is not shared because there are many files with specific names)

**Comment by hodyroff** [comment]
Questions should go to: central.owncloud.org please!
