### ISSUE TITLE
Error while deleting file on Owncloud 9.0.6

### ISSUE THREAD

**Issue by bitking** [owncloud/core#26897]
Hi there i got the following problem.

After uploading a zip files of 1,3 GB and deleting it i get an error saying the file is locked.

How can i resolve this?

--> 
### Steps to reproduce
1. Upload a zip file of 1,3GB
2. After the upload try to delete it
3. See an error when using

### Expected behaviour
Delete the file

### Actual behaviour
Doesnt delete the file

### Server configuration
**Operating system**:
Ubuntu 14.04.5 LTS

**Web server:**
Apache2

**Database:**
mysql  Ver 14.14 Distrib 5.5.53

**PHP version:**
PHP 5.5.9-1ubuntu4.20

**ownCloud version:** (see ownCloud admin page)
9.0.6

**Updated from an older ownCloud or fresh install:**
Fresh

**Where did you install ownCloud from:**
Official Ubuntu repository

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
Collaborative tags
Comments
External Sites
Federation
First Run Wizard
LDAP user and group backend  
Mail Template Editor
Notifications  
PDF Viewer
Provisioning API
Share Files
Text Editor
Update notification
Video player
Documents  

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
{"reqId":"I07bKNfJHhbm1xSui6gB","remoteAddr":"10.200.200.183","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"OLVG_OOST_NS.zip\\\" is locked\",\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(285): Sabre\\\\DAV\\\\Tree->delete('OLVG_OOST_NS.zi...')\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php\",\"Line\":342,\"User\":\"212681\"}","level":4,"time":"2017-01-04T15:58:05+01:00","method":"DELETE","url":"\/remote.php\/webdav\/OLVG_OOST_NS.zip","user":"212681"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by bitking** [comment]
Weird, it took 15 minutes to be able to delete the file.

Not sure how that is possible.

**Comment by HunorR** [comment]
i have the same problem, and in the logs i have the folowing:

> Exception: {"Message":"HTTP\/1.1 423 \"windows\/win7_32.iso\" is locked","Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\FileLocked","Code":0,"Trace":"#0 \/home\/owncloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(179): OCA\\DAV\\Connector\\Sabre\\File->delete()\n#1 \/home\/owncloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(285): Sabre\\DAV\\Tree->delete('windows\/win7_32...')\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpDelete(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/home\/owncloud\/public_html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/home\/owncloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:DELETE', Array)\n#5 \/home\/owncloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/home\/owncloud\/public_html\/apps\/dav\/appinfo\/v1\/webdav.php(56): Sabre\\DAV\\Server->exec()\n#7 \/home\/owncloud\/public_html\/remote.php(164): require_once('\/home\/owncloud\/...')\n#8 {main}","File":"\/home\/owncloud\/public_html\/apps\/dav\/lib\/Connector\/Sabre\/File.php","Line":342,"User":"hunor"} 

How can i unlock this file?
