### ISSUE TITLE
Rename "External storages" to "External storage"

### ISSUE THREAD

**Issue by jbicha** [owncloud/core#26905]
Nextcloud 11 with the "External storage support" enabled.

In the right sidebar, "External storages" should be renamed to "External storage". Storage is a collective plural noun in English and does not need a letter S at the end. Dropping the S would also match the text on the external storage settings page.

![nextcloud-global-credentials](https://cloud.githubusercontent.com/assets/876259/21740529/37c0c636-d48a-11e6-9bb0-214493213900.png)

**Comment by jbicha** [comment]
Duplicate of https://github.com/nextcloud/server/issues/2973 but maybe y'all want this too?

**Comment by SergioBertolinSG** [comment]
![screen shot 2017-01-09 at 10 39 48](https://cloud.githubusercontent.com/assets/9048796/21762269/0ca00118-d658-11e6-9d56-1396b9e9a74d.png)

**Comment by jbicha** [comment]
Great., but shouldn't only the first word be capitalized?
```
-External Storage
+External storage
```
The same for "Federated Cloud" unless it's being used as a brand name where the capitalization matters more than UI consistency.
