### ISSUE TITLE
Unable to get the Name of logged in User

### ISSUE THREAD

**Issue by Waqar731** [owncloud/core#26908]
Hi,
I am trying to get the user name who is currently logged in. For this  I am trying following line of code in upload.php file.
`echo OCP\User::getUser();`

**But**
Actually I want that when I upload any file then before uploading I want to show the name of the logged in user on top of page. But I m unable to see.

**How to fix this?**

**Comment by PVince81** [comment]
This is a bug tracker, not a support platform. Please post to https://central.owncloud.org/c/development

Also it is not clear what you are trying to achieve. Make sure to include a more complete script there.

**Comment by PVince81** [comment]
and if you think this is a bug, then please reopen and use the issue template: https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

**Comment by Waqar731** [comment]
Then please give me answer here
https://central.owncloud.org/t/unable-to-get-the-name-of-logged-in-user/4972 @PVince81
