### ISSUE TITLE
cURL/SSL error when upgrading from 9.1.1 to 9.1.2

### ISSUE THREAD

**Issue by dassencio** [owncloud/core#26906]
### Steps to reproduce
1. Go to the Admin area
2. Click on "Open updater"

### Expected behaviour
The update process starts.

### Actual behaviour
The following is shown on the screen:

cURL error 51: SSL: no alternative certificate subject name matches target host name 'localhost' 

### Server configuration
**Operating system**: Ubuntu/Linux

**Web server:**

**Database:** MySQL

**PHP version:** 5.6 and 7.0 (problem occurred with both versions)

**ownCloud version:** 9.1.1

**Updated from an older ownCloud or fresh install:** updated from 9.1

**Where did you install ownCloud from:** installed at web host

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Integrity checker has been disabled. Integrity cannot be verified.

**List of activated apps:**
Default encryption module 1.3.0
Deleted files 0.9.0
First run wizard 1.1
Gallery 15.0.0
Mail Template Editor 0.1
Notifications 0.3.0
PDF Viewer 0.8.1
Share Files 0.10.0
Text Editor 2.1
Update notification 0.2.1
Video player 0.9.8
Calendar 1.4.1
Contacts 1.5.1
Audio Player 1.4.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
(not possible)

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox / Chromium

**Operating system:**
Ubuntu/Linux

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
@dassencio are you using SSL with a valid certificate ?

Seems the updater app is using "localhost" with HTTPS for which the cert is likely not verifiable.

@VicDeo any input on this ?

**Comment by dassencio** [comment]
@PVince81 : the certificate is valid and signed by Let's Encrypt. I've tried it both on Firefox and Chromium; both browsers accept it without a warning.

And yes, the "Common Name (CN)" field is correctly set to the ownCloud URL instance I'm running (it's not localhost).

**Comment by VicDeo** [comment]
@PVince81 Just the same with https://github.com/owncloud/updater/issues/414#issuecomment-266526686
If there is none of `$_SERVER['HTTP_X_FORWARDED_HOST']` `$_SERVER['HTTP_HOST']`
`$_SERVER['SERVER_NAME']` set - it will fallback to localhost

**Comment by PVince81** [comment]
@VicDeo so is this something that needs to be documented to make sure it's not missing in the setup ?

**Comment by geekonthepc** [comment]
I can confirm that I've experienced this issue too with the same environment apart from using Debian. The updater fails with this error when using Let's Encrypt at the certificate provider.

The _workaround_ is to turn off the verify function within guzzlehttp's config - however I've been strongly advised that this will have significant security risks.

**Comment by VicDeo** [comment]
@geekonthepc are you using nginx?

**Comment by geekonthepc** [comment]
@VicDeo No, afraid not. I'm using Apache 2.4.

**Comment by JonasDralle** [comment]
having the same issue
[Image of Error + Screenshot of SSL Cert used](https://i.imgur.com/cofZNQH.png)

The log displays
> Warning / core 
> Invalid request to occ controller. Details: "Web executor is not allowed to run from a host [MY EXTERNAL IP HERE]

running ownCloud Version 9.1.3 via stable channel

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**The content of config/config.php:**
https://pastebin.com/LCXiS0tm

**List of activated apps:**
https://pastebin.com/0R9CLHGX

**Are you using external storage, if yes which one:**
none

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
none

### Client configuration
**Browser:** Firefox 54

**Operating system:** Windows 10 Pro

#### Browser log
![](https://i.imgur.com/SNGtcZ0.png)

**Comment by VicDeo** [comment]
Fixed down to stable9 with 
https://github.com/owncloud/updater/pull/443
https://github.com/owncloud/updater/pull/441
https://github.com/owncloud/updater/pull/438
https://github.com/owncloud/updater/pull/434

Please change your `updater/src/Utils/OccRunner.php`  using **one** of PRs above as a reference 
 that matches your ownCloud version.
