### ISSUE TITLE
SMB shares has stoped work (FreeBSD)

### ISSUE THREAD

**Issue by SpecBlackHat** [owncloud/core#26910]
### Steps to reproduce
1. Update to owncloud-9.1.3
2. Try to mount SMB shares
3. It start to endless loading

### Expected behaviour
It should connected and show green round instead loading circle.

### Actual behaviour
Showing loading circle.

### Server configuration
**Operating system**: FreeBSD 10.3

**Web server:** Apache 24

**Database:** MySQL 5.6.34

**PHP version:** 56

**ownCloud version:** (see ownCloud admin page) 9.1.3

**Updated from an older ownCloud or fresh install:** Update

**Where did you install ownCloud from:** Ports

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

Can not access there - endless loading
```

SMB shares work before updating.

**Comment by SpecBlackHat** [comment]
![1](https://cloud.githubusercontent.com/assets/1147104/21790057/6646b0ea-d725-11e6-8707-9f4ed73b0e09.PNG)

This is how it looks like.

**Comment by SergioBertolinSG** [comment]
Just tried SMB storage with 9.1.3, no problems found. 

Please note that freebsd is not a supported OS: https://doc.owncloud.org/server/latest/admin_manual/installation/system_requirements.html#supported-platforms

**Comment by PVince81** [comment]
Any logs ?

**Comment by SpecBlackHat** [comment]
SergioBertolinSG commented 10 hours ago
Just tried SMB storage with 9.1.3, no problems found.

Please note that freebsd is not a supported OS: https://doc.owncloud.org/server/latest/admin_manual/installation/system_requirements.html#supported-platforms

I know, but it works well before upgrade to last version.

**Comment by SpecBlackHat** [comment]
Here is last log with warnings\errors

Error	encryption	Encryption Library, symmetrical encryption failed no content given	2017-01-11T01:17:11+00:00
Error	PHP	Undefined variable: data at /usr/local/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php#250	2017-01-11T01:17:10+00:00
Error	PHP	Missing argument 2 for OC\Files\Storage\Wrapper\Wrapper::file_put_contents(), called in /usr/local/www/owncloud/lib/private/Files/View.php on line 1119 and defined at /usr/local/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php#249	2017-01-11T01:17:10+00:00
Error	encryption	Encryption Library:error:02001002:system library:fopen:No such file or directory	2017-01-11T01:17:10+00:00
Error	encryption	Encryption library couldn't export users private key, please check your servers OpenSSL configuration."no user given"	2017-01-11T01:17:10+00:00
Error	encryption	Encryption library openssl_pkey_new() fails: error:2006D080:BIO routines:BIO_new_file:no such file	2017-01-11T01:17:10+00:00
Error	encryption	Encryption Library couldn't generate users key-pair for "no user given"	2017-01-11T01:17:10+00:00
Error	encryption	Encryption Library, symmetrical encryption failed no content given	2017-01-11T01:17:09+00:00
Error	PHP	Undefined variable: data at /usr/local/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php#250	2017-01-11T01:17:08+00:00
Error	PHP	Missing argument 2 for OC\Files\Storage\Wrapper\Wrapper::file_put_contents(), called in /usr/local/www/owncloud/lib/private/Files/View.php on line 1119 and defined at /usr/local/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php#249	2017-01-11T01:17:08+00:00
Error	encryption	Encryption Library:error:02001002:system library:fopen:No such file or directory	2017-01-11T01:17:08+00:00
Error	encryption	Encryption library couldn't export users private key, please check your servers OpenSSL configuration."no user given"	2017-01-11T01:17:08+00:00
Error	encryption	Encryption library openssl_pkey_new() fails: error:2006D080:BIO routines:BIO_new_file:no such file	2017-01-11T01:17:08+00:00
Error	encryption	Encryption Library couldn't generate users key-pair for "no user given"	2017-01-11T01:17:08+00:00
Error	encryption	Encryption Library, symmetrical encryption failed no content given	2017-01-11T01:17:07+00:00
Error	PHP	Undefined variable: data at /usr/local/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php#250	2017-01-11T01:17:07+00:00
Error	PHP	Missing argument 2 for OC\Files\Storage\Wrapper\Wrapper::file_put_contents(), called in /usr/local/www/owncloud/lib/private/Files/View.php on line 1119 and defined at /usr/local/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php#249	2017-01-11T01:17:07+00:00
Error	encryption	Encryption Library:error:02001002:system library:fopen:No such file or directory	2017-01-11T01:17:07+00:00
Error	encryption	Encryption library couldn't export users private key, please check your servers OpenSSL configuration."no user given"	2017-01-11T01:17:07+00:00
Error	encryption	Encryption library openssl_pkey_new() fails: error:2006D080:BIO routines:BIO_new_file:no such file	2017-01-11T01:17:07+00:00
Error	encryption	Encryption Library couldn't generate users key-pair for "no user given"	2017-01-11T01:17:07+00:00
Error	encryption	Encryption Library, symmetrical encryption failed no content given	2017-01-11T01:17:06+00:00
Error	PHP	Undefined variable: data at /usr/local/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php#250	2017-01-11T01:17:05+00:00

**Comment by PVince81** [comment]
Hmm, are you using encryption ? Are files on the SMB storage encrypted ?
It is possible that the SMB storage code fails because of these encryption errors, so you might want to try and solve these first.

**Comment by SpecBlackHat** [comment]
Hmm, are you using encryption ? Are files on the SMB storage encrypted ?
It is possible that the SMB storage code fails because of these encryption errors, so you might want to try and solve these first.

Yes we are using encryption.
Files on SMB are not encrypted.

**Comment by SpecBlackHat** [comment]
![1](https://cloud.githubusercontent.com/assets/1147104/21838304/fc542890-d81c-11e6-8625-43bb60001d71.PNG)

**Comment by SpecBlackHat** [comment]
It is possible that the SMB storage code fails because of these encryption errors, so you might want to try and solve these first. - how to solve this? I can open any files on share without any problems so i don't think that they are encrypted. And in SMB mount options i off using encription (you can see it on screenshop above)

**Comment by SpecBlackHat** [comment]
Maby you need any other logs?
Today i'd try again to connect an external smb storage.
No any new errors like in log above, and as before - did not work.

**Comment by PVince81** [comment]
Do you have the php5-libsmbclient module installed maybe ? Usually it helps fixing SMB issues.
Did you have it before the upgrade and maybe it disappeared after ?

**Comment by SpecBlackHat** [comment]
Do you have the php5-libsmbclient module installed maybe ?
I think yep
/usr/local/include/libsmbclient.h
/usr/local/lib/libsmbclient.a
/usr/local/lib/libsmbclient.so
/usr/local/lib/libsmbclient.so.0

Did you have it before the upgrade and maybe it disappeared after ?
I have this after upgrade. Everything works well before.

**Comment by PVince81** [comment]
I meant the PHP library for libsmbclient: /usr/lib64/php5/extensions/libsmbclient.so

**Comment by SpecBlackHat** [comment]
"I meant the PHP library for libsmbclient: /usr/lib64/php5/extensions/libsmbclient.so" - i think the directory depends of OS. On freebsd it place here /usr/local/lib/libsmbclient.so
BTW, pkg install php5-libsmbclient return that it can not find such package.
If i run make config from /usr/ports/php56-extensions - there is no such module in the list.

How to reinstall this library?

**Comment by SpecBlackHat** [comment]
Here my php library

/usr/local/lib/php/20131226/smbclient.so

**Comment by PVince81** [comment]
Maybe try updating it. Not sure how on FreeBSD.

**Comment by SpecBlackHat** [comment]
![1](https://cloud.githubusercontent.com/assets/1147104/21880379/6061abd2-d8ea-11e6-84fd-5da1d4d88fa3.PNG)

Here is all PHP extensions on my OS.

Maybe try updating it. Not sure how on FreeBSD. - it's uptodate, nothing to update.

**Comment by SpecBlackHat** [comment]
Try to reinstall owncloud.
No changes.

Any other logs need?

**Comment by SpecBlackHat** [comment]
Return old version from backup - same result. Endless circle.

**Comment by shockrifleut** [comment]
I had the same problem on a FreeBSD 10.3 box, but I don't think it's in any way related to OC.
Directly using smbclient from the shell showed exactly the same behaviour, where on every other machine the shares worked fine.
After building samba4 (4.4.5) from the ports, the samba4 version of smbclient (using Samba 4.4.5) worked again. So I also built and installed libsmbclient (from the samba4 source!) and the php-smbclient extension by hand and everything works again like a charm now.
My guess is, that an update of php56 on FreeBSD broke smbclient and libsmbclient in some way (and just take a look on the screenshot posted above - every other PHP extension is dated Dec, 13th, only smbclient is still from Aug, 5th).

**Comment by SpecBlackHat** [comment]
After building samba4 (4.4.5) from the ports, the samba4 version of smbclient (using Samba 4.4.5) worked again. So I also built and installed libsmbclient (from the samba4 source!) and the php-smbclient extension by hand and everything works again like a charm now. - Can you write more details please? I had try to reinstall samba from the ports but it does not help. How to built and install libsmbclient from the source and php-smbclient extension?

**Comment by SpecBlackHat** [comment]
>

**Comment by SpecBlackHat** [comment]
Had reinstall:
samba-libsmbclient
samba-smbclient
pecl-smbclient

Nothing changed. Don't work. Endless circle.

![default](https://cloud.githubusercontent.com/assets/1147104/22230446/449a4cd6-e229-11e6-958d-234ecb7f3880.PNG)

**Comment by shockrifleut** [comment]
I was spending a few hours with this issue... First of all, I wiped all **samba36** related stuff from the system (it's marked **DEPRECATED** by the FreeBSD people anyway).
Afterwards I updated my ports tree (portsnap fetch, portsnap extract) and built and installed net/samba44 (make install).
Unfortunately this does not install libsmbclient, so I did **not** clean the samba44 build, but copied libsmbclient.so from the tree to /usr/local/lib and created the appropriate symlink to libsmbclient.so.0.
Then I cloned the php-libsmbclient extension from Git, configured it with --with-libsmbclient=/usr/local and installed it.
That's probably not the best way to do it, but it worked for me.

**Comment by SpecBlackHat** [comment]
Hm, reinstall samba44, the libsmbclient.so was installed successfully.
The same result - endless circle....

Here is the last log file

Error	encryption	Encryption Library, symmetrical encryption failed no content given	2017-01-23T02:33:38+00:00
Error	PHP	Undefined variable: data at /usr/local/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php#250	2017-01-23T02:33:38+00:00
Error	PHP	Missing argument 2 for OC\Files\Storage\Wrapper\Wrapper::file_put_contents(), called in /usr/local/www/owncloud/lib/private/Files/View.php on line 1119 and defined at /usr/local/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php#249	2017-01-23T02:33:38+00:00
Error	encryption	Encryption Library:error:02001002:system library:fopen:No such file or directory	2017-01-23T02:33:38+00:00
Error	encryption	Encryption library couldn't export users private key, please check your servers OpenSSL configuration."no user given"	2017-01-23T02:33:38+00:00
Error	encryption	Encryption library openssl_pkey_new() fails: error:2006D080:BIO routines:BIO_new_file:no such file	2017-01-23T02:33:38+00:00
Error	encryption	Encryption Library couldn't generate users key-pair for "no user given"	2017-01-23T02:33:38+00:00
Error	encryption	Encryption Library, symmetrical encryption failed no content given	2017-01-23T02:33:37+00:00
Error	PHP	Undefined variable: data at /usr/local/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php#250	2017-01-23T02:33:36+00:00
Error	PHP	Missing argument 2 for OC\Files\Storage\Wrapper\Wrapper::file_put_contents(), called in /usr/local/www/owncloud/lib/private/Files/View.php on line 1119 and defined at /usr/local/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php#249	2017-01-23T02:33:36+00:00
Error	encryption	Encryption Library:error:02001002:system library:fopen:No such file or directory	2017-01-23T02:33:36+00:00
Error	encryption	Encryption library couldn't export users private key, please check your servers OpenSSL configuration."no user given"	2017-01-23T02:33:36+00:00
Error	encryption	Encryption library openssl_pkey_new() fails: error:2006D080:BIO routines:BIO_new_file:no such file	2017-01-23T02:33:36+00:00
Error	encryption	Encryption Library couldn't generate users key-pair for "no user given"	2017-01-23T02:33:36+00:00
Error	encryption	Encryption Library, symmetrical encryption failed no content given	2017-01-23T02:33:35+00:00
Error	PHP	Undefined variable: data at /usr/local/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php#250	2017-01-23T02:33:35+00:00
Error	PHP	Missing argument 2 for OC\Files\Storage\Wrapper\Wrapper::file_put_contents(), called in /usr/local/www/owncloud/lib/private/Files/View.php on line 1119 and defined at /usr/local/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php#249	2017-01-23T02:33:35+00:00
Error	encryption	Encryption Library:error:02001002:system library:fopen:No such file or directory	2017-01-23T02:33:35+00:00
Error	encryption	Encryption library couldn't export users private key, please check your servers OpenSSL configuration."no user given"	2017-01-23T02:33:35+00:00
Error	encryption	Encryption library openssl_pkey_new() fails: error:2006D080:BIO routines:BIO_new_file:no such file	2017-01-23T02:33:35+00:00
Error	encryption	Encryption Library couldn't generate users key-pair for "no user given"	2017-01-23T02:33:35+00:00
Error	encryption	Encryption Library, symmetrical encryption failed no content given	2017-01-23T02:33:34+00:00
Error	PHP	Undefined variable: data at /usr/local/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php#250	2017-01-23T02:33:33+00:00
Error	PHP	Missing argument 2 for OC\Files\Storage\Wrapper\Wrapper::file_put_contents(), called in /usr/local/www/owncloud/lib/private/Files/View.php on line 1119 and defined at /usr/local/www/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php#249	2017-01-23T02:33:33+00:00
Error	encryption	Encryption Library:error:02001002:system library:fopen:No such file or directory	2017-01-23T02:33:33+00:00
Error	encryption	Encryption library couldn't export users private key, please check your servers OpenSSL configuration."no user given"	2017-01-23T02:33:33+00:00
Error	encryption	Encryption library openssl_pkey_new() fails: error:2006D080:BIO routines:BIO_new_file:no such file	2017-01-23T02:33:33+00:00
Error	encryption	Encryption Library couldn't generate users key-pair for "no user given"	2017-01-23T02:33:33+00:00

**Comment by SpecBlackHat** [comment]
Had try to turn off encryption.
No changes. Endless circle....
Don't know whats wrong and how to fix it...

**Comment by SpecBlackHat** [comment]
I decided to migrate oc from FreeBSD to Debian. Had move DB and Data folder. But when i login i see a message that my keys does not work and i must reinitialize they. When i try to do it i got nothing.

**Comment by SpecBlackHat** [comment]
I had try to decrypt all files to move on new server, but when u try to turn on Decryption password i got this
![4](https://cloud.githubusercontent.com/assets/1147104/22448583/1a292a62-e7a6-11e6-88fd-a54702124402.PNG)

**Comment by SpecBlackHat** [comment]
And this is the last errors when i try to set up a recovery password
rror	encryption	Encryption Library:error:02001002:system library:fopen:No such file or directory	2017-01-31T01:14:59+00:00
Error	encryption	Encryption library couldn't export users private key, please check your servers OpenSSL configuration.admin	2017-01-31T01:14:59+00:00
Error	encryption	Encryption library openssl_pkey_new() fails: error:2006D080:BIO routines:BIO_new_file:no such file	2017-01-31T01:14:59+00:00

**Comment by SpecBlackHat** [comment]
Had fix error with OpenSSL (is can not find a config file openssl.conf, make a copy of default config file and error has gone). Next i had create a recovery password. Then i had recover all files. Move to Debian server DB and files backup. Next i had manually edit DB to turn encryption off and delete keys from files backup. Next i had turn on encryption on Debian server, it create new keys and now everything work well. Btw, smb shares work too )
