### ISSUE TITLE
Federation user autocomplete not working

### ISSUE THREAD

**Issue by polcape** [owncloud/core#26914]
### Steps to reproduce
1. I have federated each other 5 Onwcloud version 9.1.3 
2. In Federation Admin section not all of them have a green light
3. So autocomplete not working (is enable the relative option)

### Expected behaviour
Whe I type a username for sharing a file or folder the system autocomplete the field.

### Actual behaviour
Whe I type a username for sharing a file or folder the system not automplete. I have to insert the format user@owncloud

###List of activated apps

Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: 0.9.0.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1

**Comment by PVince81** [comment]
> In Federation Admin section not all of them have a green light

So this is likely the problem

**Comment by PVince81** [comment]
Any logs ?

@DeepDiver1975 was there a command to force-syncing or force-pairing ?

**Comment by polcape** [comment]
@PVince81 Yes, this is the problem (no green light --> no syncronization of users)
In the logs I see nothing of relevant, what part I have to copy and past? (Do I find a particular keyword?)

**Comment by PVince81** [comment]
I think there is usually a background job (cron) that will take care of pairing. I hope @DeepDiver1975 can provide the details as I'm not familiar with that part.

**Comment by polcape** [comment]
Any news on this?

**Comment by polcape** [comment]
Please help me on this problem. Thanks

**Comment by polcape** [comment]
Any news on my question? @DeepDiver1975 can you help me?

**Comment by polcape** [comment]
Please, can you help me?

**Comment by PVince81** [comment]
https://owncloud.org/support/

**Comment by bcutter** [comment]
Having the same issue. So well, let´s start with:

`GuzzleHttp\Exception\ServerException: Server error response [url] https://ownclouddomain.de/ocs/v2.php/apps/federation/api/v1/request-shared-secret?format=json [status code] 500 [reason phrase] Internal Server Error`

for a Owncloud and

`GuzzleHttp\Exception\ClientException: Client error response [url] https://nextclouddomain.de//ocs/v2.php/apps/federation/api/v1/request-shared-secret?format=json [status code] 400 [reason phrase] Bad request
`
for a Nextcloud federation. Also only yellow lights for both in admin page. More details on those logs needed? They appear once for every federation connected on every cron run (15 minutes) and flood the log...

**Comment by davitol** [comment]
@polcape @bcutter Tested in my oC server and Federation user autocomplete WFM.

Please follow these steps that maybe can help you:

In both containers, we modify in /opt/owncloud/config.php the following line

e.g 'overwrite.cli.url' => 'https://myserver1.com'

so the own urlserver is written in the file. ( 'https://myserver1.com' in server1 and  'https://myserver2.com' in server 2)


After editing this line, we browse into the webUI and we activate the Federation app if is not enabled.

In admin menu, in Federation section, we write down the url of the other server

e.g.  'https://myserver1.com'


Back to the CLI, we run the following commands in /opt/owncloud

sudo -u www-data php cron.php (on server1, server2, server1, server2)

sudo -u www-data ./occ dav:sync-system-addressbook (on server1 a server2)

sudo -u www-data ./occ federation:sync-addressbooks (on server1, server2)

After that the address books should be synced and auto complete should work

The green light now appears in both servers.

Note just for checking: In oC database, there's a table named trusted servers. Once we had run 'php cron.php', the shared secret field should be filled with a number. 


As said, please follow the steps above and let us know if it worked for you.

**Comment by polcape** [comment]
Hi @davitol I have made all the steps above (I have already enable the federation so I can't disabled it) but all light are yellow again.

**Comment by bcutter** [comment]
@davitol:

Wanted to try it. But:
1) What/where is "/opt/owncloud/config.php"? I have a /owncloud/config/config.php
2) 'overwrite.cli.url' => 'https://myserver1.com'
==> I have "'overwrite.cli.url' => '/owncloud',", because OwnCloud needs to be function at several names (at least one from internal, which is different to the external name (dyndns)). So I don´t think this fixed e. g. "https://externalowncloudaddress.tld/owncloud" makes any sense to me.
3) I´m only in control of **my** OwnCloud server. Therefore I can´t perform any of your listed steps on "server2". What about just merging a fix for this to master?
4) At least (I know I´m a bad testing user so far) I can confirm: With status yellow I have no shared secret in "oc_trusted_servers" table of database. Token YES, Status YES (2), shared_secret also empty.

**Comment by polcape** [comment]
Hi, in my oc_trusted_servers I have shared_secret filled but the status is 2 and sync_token NULL

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
