### ISSUE TITLE
https://demo.owncloud.org DOWN

### ISSUE THREAD

**Issue by glannes31** [owncloud/core#26921]
Hello,

The demo site is redirecting to the owncloud.org site .

**Comment by PVince81** [comment]
@Kawohl @jnweiger

**Comment by Kawohl** [comment]
@glannes31, 
yes we are currently doing a rework of it. Please be a little patient and we will have a new and flashy demo running.

**Comment by glannes31** [comment]
thanks for your answer , i close the issue
