### ISSUE TITLE
Cannot upgrade from 8.2.8 to any higher version

### ISSUE THREAD

**Issue by Sikarjan** [owncloud/core#26932]
### Steps to reproduce
1. Clear all files from owncloud besides config (data is not in this folder)
2. Download and unzip a newer version e.g. 8.2.9, 9.0.0, 9.0.5, 9.0.6 or 9.0.7
3. open index.php

### Expected behaviour
Upgrade to newer version

### Actual behaviour
I get a message that an error occurred and that I shall reload the page. After that I am in maintenance mode.

### Server configuration
**Operating system**:
Linux(?) shared hosting Parallels

**Web server:**
shared hosting Parallels

**Database:**
MySQL

**PHP version:**
5.4.28

**ownCloud version:** (see ownCloud admin page)
8.2.8.2

**Updated from an older ownCloud or fresh install:**
updated from ?

**Where did you install ownCloud from:**
Downloaded zip file from owncloud.org

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
cannot log in.
**List of activated apps:**
calendar and contacts
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
shared hoster

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'someID',
  'passwordsalt' => 'someSalt',
  'secret' => 'someSecret',
  'trusted_domains' => 
  array (
    0 => 'oc.domain.de',
  ),
  'datadirectory' => '/.../data',
  'overwrite.cli.url' => 'https://oc.innobiz.de',
  'dbtype' => 'mysql',
  'version' => '8.2.8.2',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'user',
  'dbpassword' => 'password',
  'installed' => true,
  'forceSSLforSubdomains' => true,
  'theme' => '',
  'maintenance' => true,
  'loglevel' => 0,
  'trashbin_retention_obligation' => 30,
  'trashbin_auto_expire' => true,
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
I use OC to sync my contacts and calendars

### Client configuration
**Browser:**
Vivaldi

**Operating system:**
Mac

#### Web server error log
```
Log is empty
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"cPr7ru4l+BEtu+umy\/6u","remoteAddr":"000.000.81.25","app":"core","message":"starting upgrade from 8.2.8.2 to 9.0.7.1","level":0,"time":"2017-01-12T19:28:30+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=UGB3diEpJQpJfSAiAAYJOHk1HElzYHd9Cx0LFC0%2B%3A561NNfKO3Likbv8N7Gdx832%2FQerMekrLY77gXv6h","user":"--"}
```

### Notes
I did not get an information that 8.2.9 is available the admin page told me that my installation is up to date.

**Comment by PVince81** [comment]
Maybe try running the upgrade on the command line instead with `occ ugprade`. Let's hope it will have more useful error messages.

**Comment by Sikarjan** [comment]
Sorry but my webspace provide does not over me a command line (ssh access).

I guess by know this installation is seriously broken. Is it possible to rescue the contacts and calendars? Can I do a fresh installation of the newest release and impart the contact and calendar table?

**Comment by Sikarjan** [comment]
I did a fresh install with the latest OC and imported the old stuff manually.
