### ISSUE TITLE
Alternative key storage location doesn't delete all keys after deleting user

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#26936]
### Steps

1. Setup OC v9.1.3
1. `occ app:enable encryption`.
1. `occ encryption:enable`
1. `mkdir data/enckeys; chown wwwrun:www data/enckeys` (adjust for permissions accordingly)
1. `occ encryption:change-key-storage-root enckeys`
1. Login as admin
1. Create a user "user1"
1. Login as "user1"
1. Check "data/enckeys/user1/" and subdirs: keys are present
1. Login as admin
1. Delete "user1" (need to wait 7s or navigate away)
1. Check "data/enckeys/user1/" and subdirs

### Expected result
The folder "data/enckeys/user1" must be gone just like "data/user1".

### Actual result
"data/user1" is gone but the keys folder "data/enckeys/user1" still exist with contents.
Only the user's publicKey was deleted.

### Versions
Observed in ownCloud 9.1.3.
I suspect that this never worked properly.

I don't think this is critical, @Peter-Prochaska correct me if you think otherwise.

**Comment by DeepDiver1975** [comment]
Fixed with #29144

**Comment by DeepDiver1975** [comment]
@PVince81 shall we backport this?

**Comment by PVince81** [comment]
@DeepDiver1975 ok for backport
