### ISSUE TITLE
Manual upgrade 9.1.1 to 9.1.3 failed

### ISSUE THREAD

**Issue by Mysterycz** [owncloud/core#26930]
Hello, I am using Ubuntu 14.04, Apache2, PHP 5.6 and Mysql 5.5.4. I was doing many manual OC upgrades before without any problems but this time I am experiencing issue when I use sudo -u www-data php occ upgrade ... It shows error:

Owncloud is in maintenance mode
Maybe an upgrade is already in process. Please check the logfile (data/owncloud.log). If you want to re-run the upgrade procedure, remove the "maintenance mode" from config.php and call this script again.

Well, owncloud.log is empty. When I turn off maintenance mode it shows that OC is is already at latest version (which is not). When I try to login via browser it shows that I have to do upgrade from command line.

So what I have done:

1, Downloaded last Oc version from your site
2, Set maintanance mode ON
3, Stopped web server
4, Renamed OC folder to owncloud-9.1.1
5, Unpacked new owncloud to right folder
6, Copied Config, APP Documents and my template (2nd time without Doc and template)
7, I Restarted web server
8, And finally I used sudo -u www-data php occ upgrade
9, I was staring to errors which I wrote at the beggining of this thread 

Version.php:

$OC_Version = array(9,1,3,1);
$OC_VersionString = '9.1.3';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array(9,0);
$OC_Build = '2016-12-12T17:43:04+00:00 f9a867b70c217463289a741d4d26079eb2a80dfd';

Version in Config.php is 9.1.1.3

Still unable to manually upgrade ...

root@owncloud:/var/www/owncloud# sudo -u www-data php occ upgrade
ownCloud is in maintenance mode - no app have been loaded
ownCloud is in maintenance mode
Maybe an upgrade is already in process. Please check the logfile (data/owncloud.log). If you want to re-run the upgrade procedure, remove the "maintenance mode" from config.php and call this script again.
root@owncloud:/var/www/owncloud# mc (I turned maintanance off)

root@owncloud:/var/www/owncloud# sudo -u www-data php occ upgrade
ownCloud is already latest version

I didn't copy any template or apps. Just fresh OC 9.1.3 + config

Is it bug or am I doing something wrong? I found same problem in nextcloud forum but he solved it by not coppying Documents Apps and Calendar, but this is not working for me. If you need any more info, let me know.

**Comment by Mysterycz** [comment]
Hello, one more info.

I cloned owncloud server (1:1) to another VM host and tried manual upgrade again. This time without switching server to maintanance mode and it works like a charm. So steps 2,3,7 are useless and without them it is working as expected. I will try it soon on my primary server and I will let you know :-)

**Comment by Mysterycz** [comment]
Hello, it is working ok without turning OC to maintanace mode before manual update. Strange.

**Comment by PVince81** [comment]
Maybe some env issue. Closing.
