### ISSUE TITLE
[Request] option for users to set time period after which a file or folder can be auto deleted

### ISSUE THREAD

**Issue by ArchPrime** [owncloud/core#26940]
Please note a similar request exists but seems to have been closed in error

### Server configuration
**Operating system**:
OS6 (on ReadyNAS device)
**Web server:**

**Database:**

**PHP version:**
Not known

**ownCloud version:** (see ownCloud admin page)
9.13
**Updated from an older ownCloud or fresh install:**
Fresh install

Need a way for large temporary files in a designated folder to be automatically deleted after either a certain number of days, or preferably once a certain folder size threshold is exceeded, with oldest files being deleted first  (the folder itself should remain)

This is distinct from just the shared status being deleted.  The objective is to clear disk space in a folder that is only intended to contain temporary files - for example as part of a rotating weekly backup system, or large files intended to be associated with email messages (along the lines of WeTransfer) and never used again.

I understand NextCloud has some sort of app called 'files_retention' that may work along these lines, but like most users I know nothing about Linux, have no way to install either NextCloud or that app on my readyNAS device, and have no way to enable command line access or access to system files directly anyway without voiding support from the device manufacturer.  

Either a core update or approved 3rd party app would be the optimal solution for most users

**Comment by noveens** [comment]
@PVince81 ,

Does this solution seem okay:

1. Have a ```Temp``` folder (Hard Coded) which stores some files for a certain fixed duration of time.
2. The time can be taken as a User Input through a form.
3. After each file crosses ```x (User Input)``` units of time, the file gets deleted.

Doubt:

1. Should the file be deleted as soon as the time is up, or when a page reload has occurred

**Comment by ArchPrime** [comment]
Even better would be for deletion of the oldest  files to only occur if an incoming file would exceed the allocated folder size - that way old files remain available right up until deletion is necessary.

If deletion criteria is only based on age, files that are part of a cloud backup cycle system that fails for some reason at the client end would be quickly deleted, even though there are no newer incoming backups available

**Comment by PVince81** [comment]
=> to be implemented as separate app that registers a background job.

Not part of the core platform.
