### ISSUE TITLE
[enhancement] Support user authentication for local storage

### ISSUE THREAD

**Issue by mvglasow** [owncloud/core#26943]
I have a bunch of files on my ownCloud server that I access in a number of ways, including SSH and Samba. These files have regular Unix permissions set, as they are enforced when accessing the files via these mechanisms.

To make these files accessible via ownCloud, I have added them as CIFS remote storage and pass through ownCloud credentials (every ownCloud user has a corresponding local user and Samba user, and passwords are kept in sync). However, this comes at the expense of extra overhead for SMB.

I expect local storage would be faster, but this comes with the limitation that I’d have to grant the web server user permissions on all files. Different access permissions would apply depending on how the files are being accessed—a file might be writable through Samba but not through ownCloud, or vice versa, or be completely inaccessible one way but accessible the other way.

As an improvement, I’d suggest a way to support passing credentials to local storage in the same way it’s being done for SMB shares today (either “user credentials, save in session” or explicit credentials, as available for admin-assigned SMB folders).

**Comment by PVince81** [comment]
> As an improvement, I’d suggest a way to support passing credentials to local storage in the same way it’s being done for SMB shares today (either “user credentials, save in session” or explicit credentials, as available for admin-assigned SMB folders).

How would that work ? Everything is triggered from PHP and as the web server user. You'd likely need to give special privileges to the web server user to be able to mount/access Linux FS mount points that have different permissions.
