### ISSUE TITLE
missing xml.keys in SLES repos 

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#26947]
Hey folks,

we have a problem with our SLES repos there are no keys available where i would expect them https://download.owncloud.org/download/repositories/stable/SLE_12_SP1/repodata/repomd.xml.key

`rpm --import https://download.owncloud.org/download/repositories/stable/SLE_12_SP1/repodata/repomd.xml.key`
results in 

`error:https://download.owncloud.org/download/repositories/stable/SLE_12_SP1/repodata/repomd.xml.key: import read failed(2).`

For the SLES versions.

Imho we should have also qa on our packages.

@crrodriguez 
@jnweiger

**Comment by crrodriguez** [comment]
fixed long time ago.
