### ISSUE TITLE
Proposal: output of servername in status.php

### ISSUE THREAD

**Issue by pako81** [owncloud/core#26941]
For diagnostic reasons it is helpful in a clustered environment to see where we're having a problem. So, it might be helpful to change status.php like this:

```
/[root@owncloud01.MS owncloud]# diff status.php status2.php // 
//33c33// 
//< // 
//---// 
//> $servername = gethostname();// 
//36a37// 
//> 'servername'=>$servername,// 
//  
```

**Comment by kdslkdsaldsal** [comment]
@pako81 The best is probably to create a Pull Request with your suggested changes to the status.php for discussion.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/issues/26973

**Comment by pako81** [comment]
Nice :)

**Comment by tomneedham** [comment]
Needs reviving, and conditional based on a config.php tag, default false, and add to OCP::getStatusInfo.
