### ISSUE TITLE
Request:  Able to send files via email from OC web gui

### ISSUE THREAD

**Issue by wioxjk** [owncloud/core#26952]
As the title suggested, is it possible to implement any feature like this?

Ofcourse,  the files sent as an attachment can't be too big.

**Comment by DeepDiver1975** [comment]
From my pov this is absolutly in the opposite direct of what owncloud is trying to provide to the users.
Instead of duplicating content by sending copies to various collaborators via email we should encourage users to share and work collaborativly on the original resource.

**Comment by wioxjk** [comment]
@DeepDiver1975 
I totally get your point and for the most parts it is the most optimal thing to do.

But sometimes, I just want to send a picture to my colleague or friends directly to their email. Not just a link to the file on my OC server.
I mean, this should'nt be that hard to implement (maybee a hidden option in one config file or something)

**Comment by wioxjk** [comment]
Accidently closed this,,

**Comment by PVince81** [comment]
Since this is a rather specific use case, this doesn't belong to core. Someone could implement this as a separate app.
