### ISSUE TITLE
Can't set a user's quota back to Unlimited

### ISSUE THREAD

**Issue by jturcotte** [owncloud/core#26975]
### Steps to reproduce
1. Go tu user admin page, set quota to 1GB
2. Once applied, try setting quota back to Unlimited

### Expected behaviour
Quota is set back to unlimited

### Actual behaviour
Orange error box at the top saying `Invalid quota value "none"` and refreshing the page shows that the quota wasn't changed.

### Server configuration
**Operating system**:
macOS (I assume this doesn't matter, it works with 9.1.2 on the same setup)

**Web server:**
nginx

**Database:**
sqlite

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
master (1f7167a96bd9c8510f9b69d865a637c87f52015f)

**Updated from an older ownCloud or fresh install:**
fresh

**Where did you install ownCloud from:**
git + make

### Client configuration
**Browser:**
Safari 10.0.2
Same error in Chrome

**Operating system:**
macOS 10.12.2

**Comment by PVince81** [comment]
@VicDeo some bisecting fun ?

**Comment by VicDeo** [comment]
@PVince81 I see you  ;) https://github.com/owncloud/core/commit/819b7c45a94dd86e673a478d13ae100e9bc34ad4#diff-69cbab0a372c067f4ea645443652066c

**Comment by VicDeo** [comment]
For Unlimited quota the value is 'none'

**Comment by PVince81** [comment]
@VicDeo argh. Thanks for finding it. Can you fix it ?
