### ISSUE TITLE
ChunkingNG: Stray chunks are never deleted

### ISSUE THREAD

**Issue by jturcotte** [owncloud/core#26981]
### Steps to reproduce
1. Start uploading a 500MB file using the client 2.3
2. While chunks are still being uploaded, touch the source file (or move it out of the directory, and in again after the sync). The sync will be aborted and a new one will try to re-upload chunks from the start, using a new transfer-ID and leaving old chunk files on the server.
3. Complete the sync
4. Repeat every day for 4 months

### Expected behaviour
Chunks of failed uploads are periodically deleted from the server's `data/$user/uploads/` directory.

Since chunks are now accessible through WebDAV we could, in addition, issue a DELETE on the collection from the client if that verb is implemented for `/uploads/`. But there will still be cases where the client won't be able to clean itself up (for example if a client is shut down and then uninstalled in the middle of a chunked upload).

### Actual behaviour
Chunks accumulate and fill the disk, the admin must clean them up manually (but do they still remain in the DB?)

The "old chunking" chunks of a user seem to be cleaned up every time that user logs into the web interface. It would already help if this was the case.

### Server configuration
**ownCloud version:** (see ownCloud admin page)
master (1f7167a96bd9c8510f9b69d865a637c87f52015f)

**Comment by ogoffart** [comment]
The client could issue a DELETE on the uploads directory if it detects stale uploads data on the database. But there might be cases where we would miss it.

**Comment by guruz** [comment]
Should need to respect this setting
https://github.com/owncloud/core/blob/850ad9c47e53706d6e7abec794afb76e4f032ff8/config/config.sample.php#L980
https://github.com/owncloud/core/search?utf8=%E2%9C%93&q=cache_chunk_gc_ttl&type=Code

**Comment by PVince81** [comment]
Maybe we need something like https://github.com/owncloud/core/issues/14646.

But maybe the DELETE idea is not bad. @DeepDiver1975 how was it intended to work / be used ?

**Comment by ogoffart** [comment]
With this pull request, the client would try to delete stale chunks: https://github.com/owncloud/client/pull/5480

**Comment by PVince81** [comment]
We'll likely still need a background job that cleans stray chunks if a transfer hasn't been updated since a while. Maybe it could check the mtime of the "uploads/$transferId" to decide whether any chunk were updated before deleting the stray abandoned transfer.

**Comment by guruz** [comment]
> Maybe it could check the mtime of the "uploads/$transferId" folder to decide whether any chunk were updated before deleting the stray abandoned transfer.

I remember the old algorithmn deleted individual old chunks and let newer ones live. Which can lead to strange resuming situations where the client "loops" around the chunk number.

So as @PVince81 said, the new one should do it per upload directory and not per chunk!

**Comment by DeepDiver1975** [comment]
I'm going to implement this as an occ command - admins can place this in their cron as they like

**Comment by PVince81** [comment]
moving to "planned" for next release. A PR is in the works https://github.com/owncloud/core/issues/28587
