### ISSUE TITLE
Weird connecting behaviour

### ISSUE THREAD

**Issue by Ninoscorp** [owncloud/core#26994]
Today I installed owncloud, installed LAMP, then owncloud, when i try to connect to my owncloud with the router ip it connects fine, but if i try to use its IP or my DNS it doesnt want to connect, just says 
"Access Error: 404 -- Not Found" i checked all the steps and everything seems to work, anything else i should try?

**Comment by kdslkdsaldsal** [comment]
@Ninoscorp Please note this is a bugtracker for ownCloud. Setup / environmental issues and questions needs to go to https://central.owncloud.org/c/help/miscellaneous

Please close here and follow the link above. When posting there (you can use your github account there) make sure that you're filling out the issue template shown there.
