### ISSUE TITLE
ownCloud is not compatible with PHP 7.1

### ISSUE THREAD

**Issue by ck19912** [owncloud/core#26998]
I have upgraded my php to 7.1.1 and now ownCloud won't work.

Now i get the following error:
`This version of ownCloud is not compatible with PHP 7.1.
You are currently running 7.1.1. Please use at least ownCloud 9.2.0.`

When will ownCloud support php 7.1?

**Comment by kdslkdsaldsal** [comment]
Duplicate of https://github.com/owncloud/core/issues/25858 with an answer to your question in https://github.com/owncloud/core/issues/25858#issuecomment-272661658
