### ISSUE TITLE
Theme is ignored

### ISSUE THREAD

**Issue by joshuacox** [owncloud/core#27038]
### Steps to reproduce
1.  add this to your styles.php in `OWNCLOUD/themes/MyTheme/core/css`
```
#app-nagigation {
        background-color: #000000;
}

```

2.  Put `'theme' => 'MyTheme'`, into the `/config/config.php` file.
3. reload page, inspect  <div id="app-navigation">

### Expected behaviour
Tell us what should happen

background should be black

### Actual behaviour
Tell us what happens instead

background is `#FFF`

### Server configuration
**Operating system**: docker official owncloud image

**Web server:** rancherOS

**ownCloud version:** (see ownCloud admin page)

Custom Cloud 9.1.3 (stable)

**Where did you install ownCloud from:**

docker

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
none default out of box docker install
```

**Are you using external storage, if yes which one:** nfs

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
firefox

**Operating system:**
arch linux up to date

**Comment by PVince81** [comment]
@PhilippSchaffrath

**Comment by michaelstingl** [comment]
@joshuacox typo in `#app-nagigation` ?

**Comment by joshuacox** [comment]
lol, really?  ha, closing
