### ISSUE TITLE
2FA page reload / refresh

### ISSUE THREAD

**Issue by cornelinux** [owncloud/core#27053]
### Steps to reproduce
1. Using owncloud 9.1.3 EE
2. Install a 2FA App like the privacyIDEA ownCLoud App
3. configure 2FA app
4. login with user name password and wait for the screen to enter the OTP value.

The page will be reloaded after 5 secs.

See:
https://help.nextcloud.com/t/2fa-login-page-refresh/2740
See:
When I remove these lines: everything is fine. (DIsclaimer: I do not know, what I am doing! ;-)
https://github.com/owncloud/core/blob/master/lib/private/AppFramework/Http/Request.php#L653-L657

### Expected behaviour
The page should not reload

### Actual behaviour
It does reload

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
nginx

**Database:**
mysql
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
9.1.3

**Updated from an older ownCloud or fresh install:**
No

**Comment by PVince81** [comment]
@DeepDiver1975 @phisch @IljaN can you guys review https://github.com/owncloud/core/issues/26882 ?

**Comment by cornelinux** [comment]
It does not happen in Enterprise Edition 10.0.2 (anymore).

**Comment by DeepDiver1975** [comment]
> It does not happen in Enterprise Edition 10.0.2 (anymore).

case closed then? 😕

**Comment by cornelinux** [comment]
Ok die me...
