### ISSUE TITLE
End-to-End (Frontend) testing

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#27055]
Currently there are PHPUnit Tests and Karma tests in OwnCloud. I would suggest to add End-to-End tests that run on real browsers so more cases can be covered.
My suggestion is to use [Selenium](http://seleniumhq.org) for it.

- [tests can run on multiple browsers (including mobile)](http://www.seleniumhq.org/docs/01_introducing_selenium.jsp#supported-browsers-and-platforms)
- actions are performed exactly the same a user would do them. selenium performs real action in the browser (mouse click, key strokes, etc.)
- visibility of objects can be tested
- positions of objects can be tested
- content of objects can be tested 
- tests can be written in PHP or JS
- ...

I will make a PR with a practical implementation of selenium

**List of potential PRs that would benefit of selenium tests:**
Can't set a user's quota back to Unlimited #26975
Fix long display names #27059

**Comment by PVince81** [comment]
@owncloud/qa @felixboehm

**Comment by individual-it** [comment]
closing because implemented
