### ISSUE TITLE
OCS provisioning API to enable/disable a user

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27061]
Make it possible to change the value of the "enabled" attribute using the provisioning API.

To round up the feature https://github.com/owncloud/core/issues/12601 a bit.

**Comment by noveens** [comment]
@PVince81 ,
what exactly is the significance of the "enabled" attribute,
and what exactly needs to be solved in this issue?

**Comment by DeepDiver1975** [comment]
Already existing in oc10 - https://github.com/owncloud/core/blob/master/apps/provisioning_api/appinfo/routes.php#L49-L50

**Comment by DeepDiver1975** [comment]
9.1 as well - https://github.com/owncloud/core/blob/stable9.1/apps/provisioning_api/appinfo/routes.php#L49-L50

**Comment by PVince81** [comment]
Ah ok... I tried to PUT the value to the attribute but that didn't work.

**Comment by SamuAlfageme** [comment]
@PVince81 hmmm... 

> I tried to PUT the value to the attribute but that didn't work 

I just stumbled upon this old https://github.com/owncloud/documentation/issues/2599 issue. And I believe there's some non-deterministic behavior in the OCS APis related to the use of the `OCS-APIREQUEST` header in some requests. Might explain what you saw there. Care to do a quick test?

**Comment by PVince81** [comment]
@SamuAlfageme nothing to do with OCS-APIREQUEST. I simply used the wrong route.

If you do a PUT with the "enabled=true" value the backend just ignores the value.
You need to do a PUT on the "/$userId/enable" endpoint
