### ISSUE TITLE
Updating from 8.2 to 9.0 : calendar and contacts (seemingly) gone

### ISSUE THREAD

**Issue by mlkiefer** [owncloud/core#27064]
### Steps to reproduce
Upgrade owncloud from 8.2 to 9.0

### Expected behaviour
Contacts and calendar entries should be visible in the apps.

### Actual behaviour

Not sure if this is a bug but I think it might save people in the same situation a lot of time, so I file it here. The solution is included so you can close it directly, but it is documented somewhere.

I had some troubles migrating from owncloud 8.2.* to 9.0.* 
My contacts and calendar were gone after the upgrade to 9. Neither in the respective apps nor in the CalDAV or CardDAV folders, any entry was there.
The main cause seems to have been that I tried updating (also to 9.0) some months ago, when 9.0 freshly came out.  At that time, the upgrade failed (contacts and calendar entries went missing) so I rolled back to 8.2 However, I seem to have forgotten to revert the database. When I was trying the update again, the calendars and contacts were completely gone, as well as the files.

After some hours of reading, I found out that there were two problems: The updater seems to have stumbled over some remnant database tables from the previous try. Furthermore, some configuration concerning the (Web- Cal- Card-)DAV interfaces was not adapted to the new scheme.

### Solution

Here is what I did to fix these issues:

Remove stale tables for calendars, addressbooks and owncloud federation
`# mysql -u root -p

DROP TABLE oc_calendarchanges;
DROP TABLE oc_calendars;
DROP TABLE oc_calendarobjects;
DROP TABLE oc_calendarsubscriptions;
DROP TABLE oc_schedulingobjects;

DROP TABLE oc_addressbookchanges;
DROP TABLE oc_addressbooks;
DROP TABLE oc_cards;
DROP TABLE oc_cards_properties;
DROP TABLE oc_dav_shares;

DROP TABLE oc_trusted_servers;`

`sudo -u www-data php occ upgrade`

Change the URLs for the *DAV services
`update oc_appconfig set configvalue = 'dav/appinfo/v1/caldav.php' where appid = 'core' and configkey = 'remote_caldav';
update oc_appconfig set configvalue = 'dav/appinfo/v1/caldav.php' where appid = 'core' and configkey = 'remote_calendar';

update oc_appconfig set configvalue = 'dav/appinfo/v1/carddav.php' where appid = 'core' and configkey = 'remote_carddav';
update oc_appconfig set configvalue = 'dav/appinfo/v1/carddav.php' where appid = 'core' and configkey = 'remote_contacts';

update oc_appconfig set configvalue = 'dav/appinfo/v1/webdav.php' where appid = 'core' and configkey = 'remote_files';
update oc_appconfig set configvalue = 'dav/appinfo/v1/webdav.php' where appid = 'core' and configkey = 'remote_webdav';`

### Server configuration
**Operating system**:
GNU/Linux bananian stable

**Web server:**
nginx

**Database:**
mysql 5.5

**PHP version:**
5

**ownCloud version:** (see ownCloud admin page)
8.2

**Comment by kdslkdsaldsal** [comment]
@mlkiefer Thanks for posting. It looks like something which could perfectly fit into a new tutorial at https://central.owncloud.org/c/help/howto-tutorial

Concerning "bug" i doubt that ownCloud is and will be capable to repair such a broken setup where the files where downgraded but not the database itself.

**Comment by mlkiefer** [comment]
I can't edit in that forum. Too few XP points. So someone else has to do that.

**Comment by PVince81** [comment]
Not knowing what kind of troubles you had will make it impossible to reproduce and to fix.

Also it is likely that these were older versions of OC and many bugs were fixed already. Closed.
