### ISSUE TITLE
Issues with version 8.2 with Mysql:"Database <mysql> is not support"

### ISSUE THREAD

**Issue by guilherme-sir-loop** [owncloud/core#27070]
I had had a bug with sqlite, so as walkthrought i used mysql, but after i typed this command:
occ maintenance:install  --database “mysql” --database-name “owncloud” --database-user "root" --database-pass "password" --admin-user "admin" --admin-pass "password"
I received a error:
Database <mysql> is not support

**Comment by DeepDiver1975** [comment]
most probably you miss the mysql module for php - please run php -m

**Comment by guilherme-sir-loop** [comment]
Yes, thank you.
The mysql module is not on the list.
