### ISSUE TITLE
Add option for linux version of MSSQL

### ISSUE THREAD

**Issue by photodude** [owncloud/core#27087]
### Steps to reproduce
Look at database options, only the following are listed

- MySQL / MariaDB
- PostgreSQL
- Oracle (ownCloud Enterprise edition only)

### Expected behavior
MSSQL linux version should be available. as the linux flavor has been out since March 2016

instructions on how to install
http://www.tecmint.com/install-ms-sql-server-centos-ubuntu-linux/

docker image
https://hub.docker.com/r/microsoft/mssql-server-linux/

SQL Server on Linux Documentation
https://docs.microsoft.com/en-us/sql/linux/

**Comment by PVince81** [comment]
It is already a lot of work to support MySQL (and soon to be added utf-8mb4 support), PostgreSQL, SQLite and Oracle. And the more databases are added, the less "custom" features can be used.

If MSSQL is to be added back again, it would be good if someone would volunteer to maintain this long term, someone who uses this on a productive system.

Unfortunately DB support cannot be added through apps as it ties in too closely within the system. One needs the DB to be setup to be able to enable apps. So it wouldn't be possible to let apps provide database functionality.

@hodyroff @DeepDiver1975 @pmaier1

**Comment by PVince81** [comment]
Won't fix
