### ISSUE TITLE
owncloud 8.2.*: incorrect parameter (__FILE__) for tempnam in getTempBaseDir in lib/private/tempmanager.php:228

### ISSUE THREAD

**Issue by iprok** [owncloud/core#27084]
I use owncloud 8.2.10.

On 228th line of lib/private/tempmanager.php we have:
                $temp = tempnam(__FILE__, '');
It surely should be 
                $temp = tempnam(dirname(__FILE__), '');

or something like so. 

Now to the $temp is always assigned '/tmp' and, if /tmp is not accessible (open_basedir restriction for example) then logs are flooded by this errors:
"tempnam(): open_basedir restriction in effect. File(\/tmp) is not within the allowed path(s)

I have special temp directory for owncloud and have set it in config.php using tempdirectory. So there should be no error about /tmp/.

**Comment by iprok** [comment]
Or even better string should be
`$temp = @tempnam(dirname(FILE), '');`

**Comment by kdslkdsaldsal** [comment]
> I have special temp directory for owncloud and have set it in config.php using tempdirectory. So there should be no error about /tmp/.

Might be also due to the issue discussed here that this doesn't work as expected: https://github.com/owncloud/core/issues/22011

**Comment by kdslkdsaldsal** [comment]
Closing as oC 8.2 is EOL since a few month and newer versions like 9.0.x+ are already using the correct "dirname".
