### ISSUE TITLE
status.php should return a descriptive edition text in case it is not Enterprise

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#27091]
Current printout when having a non enterprise edition:
```{"installed":true,"maintenance":false,"version":"9.1.4.2","versionstring":"9.1.4","edition":""}```

I suggest for the edition instead of beeing empty in case it is not the enterprise version to print "Community".

```{"installed":true,"maintenance":false,"version":"9.1.4.2","versionstring":"9.1.4","edition":"Community"}```

Code segment at https://github.com/owncloud/core/blob/17cff0b0bae1ffd9781d4c41a12012ad6e8e6a42/lib/private/legacy/util.php#L392

There are some additional code fragments that need a small adoption in case of, because currently ``getEditionString()`` is  queried against empty:

https://github.com/owncloud/core/search?p=2&q=getEditionString&type=Code&utf8=✓

**Comment by PVince81** [comment]
As far as I remember the edition string comes from version.php and for the community version it is empty.

Maybe we should change that in the build script instead of adding special code paths.

That would be a nice fit for 10.0.

**Comment by mmattel** [comment]
Does not seem to come from version.php.
That is the code segment I referenced above...
```
	/**
	 * @description get the current installed edition of ownCloud. There is the community
	 * edition that just returns an empty string and the enterprise edition
	 * that returns "Enterprise".
	 * @return string
	 */
	public static function getEditionString() {
		if (OC_App::isEnabled('enterprise_key')) {
			return "Enterprise";
		} else {
			return "";
		}
	}
```
