### ISSUE TITLE
weird behaviour in email test 'gauge' in personal settings page

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27096]
![mailgauge](https://cloud.githubusercontent.com/assets/10596560/22686662/46fb6792-ed25-11e6-90f5-7564f958d4d8.gif)

oC Version: "10.0.0.0","versionstring":"10.0.0","edition"

**Comment by DeepDiver1975** [comment]
yes - copy and paste is not recognized as input

@felixheidecke any idea?

**Comment by felixheidecke** [comment]
@davitol could you please provide browser name and version?

**Comment by DeepDiver1975** [comment]
> @davitol could you please provide browser name and version?

I have observed that in chrome - I guess this is an issue in every browser

**Comment by davitol** [comment]
@felixheidecke Tested in Mozilla FireFox 51.0.1 (64-bit) for MacOSX and Google Chrome Version 56.0.2924.87 (64-bit) for MacOSX

**Comment by felixheidecke** [comment]
@davitol Could you test again using this PR?
https://github.com/owncloud/core/pull/27273
