### ISSUE TITLE
status.php does not return the productname

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#27090]
### Steps to reproduce
1. access mydomain.com/status.php in the browser

### Expected behaviour
Tell us what should happen
```{"installed":true,"maintenance":false,"version":"9.1.4.2","versionstring":"9.1.4","edition":"","productname":"owncloud"}```
At least "productname" should be printed like edition...

### Actual behaviour
```{"installed":true,"maintenance":false,"version":"9.1.4.2","versionstring":"9.1.4","edition":""}```

status.php should do the printout, see code starting with:
https://github.com/owncloud/core/blob/master/status.php#L39

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7

**ownCloud version:** 9.1.4

**Updated from an older ownCloud or fresh install:** update

**Where did you install ownCloud from:** tar

**Are you using encryption:** no

### Client configuration
**Browser:** Opera

**Operating system:** W7x64

There are no errors or log entries written

**Comment by PVince81** [comment]
Hmm, indeed. Even with a theme it seems to not work.

@phisch

**Comment by mmattel** [comment]
When using core via git (v10.0.x), all items are shown:
```
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.0.0.1","versionstring":"10.0.0","edition":"","productname":"ownCloud"}
```
@Prakharsvnit #27214 has nothing to do with this issue

@PVince81 @phisch something has changed between the versions. I have just tried with a git version of core and it works as expected. @PVince81 can you doubelcheck?

**Comment by Prakharsvnit** [comment]
@mmattel status.php has been changed .
`$defaults = new \OCP\Defaults();
	$values= [
		'installed'=>$installed,
		'maintenance' => $maintenance,
		'needsDbUpgrade' => \OCP\Util::needUpgrade(),
		'version'=>implode('.', \OCP\Util::getVersion()),
		'versionstring'=>OC_Util::getVersionString(),
		'edition'=>OC_Util::getEditionString(),
		'productname'=>$defaults->getName()];`

**Comment by PVince81** [comment]
@mmattel close ?

**Comment by mmattel** [comment]
yes, thanks
