### ISSUE TITLE
Active Directory Could Not Connect

### ISSUE THREAD

**Issue by badincite** [owncloud/core#27100]
Trying to get active directory to connect and I just get could not connect to ldap. The ports are open on the server.

ownCloud Version 9.1.4 (Stable)

Server 2012 r2 Active Directory

Installed php v7.0-ldap

![image](https://cloud.githubusercontent.com/assets/7386290/22694795/8c07e86a-ed16-11e6-8d6a-61e198494cd6.png)

![image](https://cloud.githubusercontent.com/assets/7386290/22694817/a8467514-ed16-11e6-931b-f1ddc89391dc.png)

**Comment by PVince81** [comment]
@jvillafanez @cdamken @davitol can you confirm that ownCloud works with PHP 7 and AD 2012 ?

**Comment by davitol** [comment]
@PVince81 PHP 7.0.9-1+deb.sury.org~trusty+1 and Active Directory 2008 with oC "9.1.4.2","versionstring":"9.1.4" works fine. Unfortunately I don't have a AD 2012 available

**Comment by badincite** [comment]
I got it connected using anonymous but then it wont connect 2 seconds later. The error log is showing this Configuration Error (prefix ): login filter does not contain %uid place holder.  I'm guessing because the user field is blank

**Comment by badincite** [comment]
All my users are CN=ownclouduser not UID in the distinguishedName Attribute is there away to change owncloud to look at CN instead?

**Comment by cdamken** [comment]
AD 2012 Works with php7

I'm almost always testing against that.

Is it possible to test it with a non anonymous user with rights to read?

**Comment by badincite** [comment]
Yeah ive tired it doesnt connect I'm assuming since active directory uses CN instead of UID. I've installed the Unix attributes just had to wait to reboot the server. I will post back with the outcome

**Comment by cdamken** [comment]
You can change the uid to cn in the expert tab, then clear all the mapping

**Comment by badincite** [comment]
The unix stuff didnt help, which setting would I change to do that in the experts tab?

**Comment by jvillafanez** [comment]
Write the '%uid' placeholder somewhere in the login filter. That placeholder will be replaced with the actual ownCloud's username at login time to fetch the user from the LDAP server.

As an example of login filter (the default one):
```
(&(&(|(objectclass=inetOrgPerson)))(uid=%uid))
```

**Comment by badincite** [comment]
I've gotten it to connect but and it says there are 84 users but it couldn't not detect displayName attributes please specify it under advanced.  

Here's what I got under users
(&(&(objectClass=inetOrgPerson)(memberOf=OU=Chesapeake Controls Users,dc=CCI,dc=WORK)))

Under Login Attributes I tired setting it to user CommonName but I haven't had any luck. What are the & signs indicating? Looking at the documentation it differs then what was auto generated by owncloud.


I tired 
(&(&(objectClass=inetOrgPerson)(memberOf=OU=Chesapeake Controls  Users,dc=CCI,dc=WORK)(cn=%uid)

Auto Generated
(&(&(objectClass=inetOrgPerson)(memberOf=OU=Chesapeake Controls  Users,dc=CCI,dc=WORK)

The documentation is only using 1 &
(&(objectClass=inetOrgPerson)(memberOf=cn=owncloudusers,ou=groups,
dc=example,dc=com)(uid=%uid)

**Comment by cdamken** [comment]
IMO this is a issue for central.owncloud.org and not a Engineering Fix problem.

> I've gotten it to connect but and it says there are 84 users but it couldn't not detect displayName attributes please specify it under advanced.

Do **ALL** user have a dysplayName? Do you already configured the Expert tab?

Could you provide some log files to see what oC and Apache says?

**Comment by badincite** [comment]
Your probably right its not engineering at this point.
Do ALL user have a dysplayName? Yes
Do you already configured the Expert tab? No I haven't touched it I'm unsure what to change

I think the issue might be my VM has multiple lan connections one separate vlans. It appears it's trying to go out the other vlan to access the AD Server. My AD Server is at 10.38.0.15 on interface 2 I figured it would default to the connection that had the same subnet. 

Owncloud Log
{"reqId":"\/J4SPOFm8hpgMvrhAJwU","remoteAddr":"192.168.38.1","app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place holder.","level":2,"time":"2017-02-18T20:00:00+00:00","method":"POST","url":"\/index.php\/apps\/user_ldap\/ajax\/wizard.php","user":"admin"}
{"reqId":"\/J4SPOFm8hpgMvrhAJwU","remoteAddr":"192.168.38.1","app":"user_ldap","message":"Configuration Error (prefix ): login filter does not contain %uid place

**Comment by davitol** [comment]
@PVince81 Close due to it is a configuration problem and move to central.owncloud.org ?

**Comment by PVince81** [comment]
Please reopen in [user_ldap app repo](https://github.com/owncloud/user_ldap) if issue persists with 10.0.4 and the latest user_ldap app from marketplace.
