### ISSUE TITLE
Owncloud webdav error deleted a random stationary file without me even being around the computer to interact with my files. Why?

### ISSUE THREAD

**Issue by arjones85** [owncloud/core#27116]
### Steps to reproduce
1. Be me riding the bus, not interacting with my files. Nobody else is home.
2. Get to work and see zip file was deleted
3. Look at error log and see error.  :(

### Expected behaviour
File shouldn't have been deleted

### Actual behaviour
File was deleted

### Server configuration
**Operating system**: CentOS 6

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page)  9.1.4

**Updated from an older ownCloud or fresh install:** Fresh

**Where did you install ownCloud from:** Source

Integrity check: No errors have been found.

**The content of config/config.php:**

```
<?php
$CONFIG = array (
 
  'datadirectory' => '/home/cloud/data',
  'overwrite.cli.url' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '9.1.4.2',
  'dbname' => 'cloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'logtimezone' => 'UTC',
  'installed' => true,

);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...   No

**Are you using encryption:** yes/no   No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...   No

### Client configuration
**Browser:**   Firefox

**Operating system:**  Windows

#### Web server error log

[Wed Feb 08 06:13:23 2017] [warn] [client X] (70007)The timeout specified has expired: mod_fcgid: can't get data from http client
[Wed Feb 08 06:13:23 2017] [warn] [client X] (70007)The timeout specified has expired: mod_fcgid: can't get data from http client
[Wed Feb 08 06:13:23 2017] [warn] [client X] (70007)The timeout specified has expired: mod_fcgid: can't get data from http client
[Wed Feb 08 06:29:32 2017] [warn] [client X] (104)Connection reset by peer: mod_fcgid: error reading data from FastCGI server
[Wed Feb 08 06:29:32 2017] [warn] [client X] (104)Connection reset by peer: mod_fcgid: ap_pass_brigade failed in handle_request_ipc function
[Wed Feb 08 09:38:51 2017] [error] [client X] File does not exist: /home/cloud/public_html/favicon.ico
[Wed Feb 08 09:38:51 2017] [error] [client X] File does not exist: /home/cloud/public_html/favicon.ico

#### ownCloud log (data/owncloud.log)

Log: http://pastebin.com/MEhiBZVW

#### Browser log

Here's the apache access log during that time. The "offending" IP that issued the DELETE according to the logs is my home IP address, which doesn't make any sense as I had been on the bus for a solid 30 minutes at that time. Nobody else is home, nobody deleted this file.

I use the latest Windows Desktop sync client on all hosts.

X.246 - - [08/Feb/2017:08:32:01 -0600] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 354 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
X.233 - - [08/Feb/2017:08:32:19 -0600] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
X.233 - - [08/Feb/2017:08:32:21 -0600] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 2579 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
X.233 - - [08/Feb/2017:08:32:22 -0600] "PROPFIND /remote.php/webdav/Workout%20Videos HTTP/1.1" 207 1422 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
X.233 - - [08/Feb/2017:08:32:22 -0600] "DELETE /remote.php/webdav/Workout%20Videos/Shaun.T.Hip.Hop.Abs.zip HTTP/1.1" 204 - "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
X.233 - - [08/Feb/2017:08:32:23 -0600] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 374 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
X.246 - - [08/Feb/2017:08:32:28 -0600] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 413 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
X.246 - - [08/Feb/2017:08:32:31 -0600] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 354 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
X.246 - - [08/Feb/2017:08:32:31 -0600] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"

**Comment by PVince81** [comment]
Latest Desktop Client being which version ? (stable/beta, please provide a number)

@guruz @ogoffart any idea what kind of glitch could cause the desktop client to decide to delete a file without any user interaction ?

**Comment by arjones85** [comment]
Stable, 2.2.4.

**Comment by guruz** [comment]
@PVince81 you can see the version in the user agent in the log above, FYI

@arjones85 You gave also reported https://github.com/owncloud/client/issues/5524
Do you think your ISP/modem could interfere here too? https://github.com/owncloud/client/issues/5524#issuecomment-278939419

**Comment by arjones85** [comment]
It is quite possible my connection went down again that morning, but I would certainly hope that would not lead to files being randomly deleted - that's not a good thing. I've never had Dropbox or Google Drive delete files because of a connection glitch! :)

**Comment by guruz** [comment]
Could you check the ```.owncloudsync.log``` in your local sync dir for the line containing ```Shaun.T.Hip.Hop.Abs.zip```?

**Comment by PVince81** [comment]
What if the XML parser is trying to be clever and while seeing an unclosed tag, it automatically closes it ?

So if you'd receive a body like:
```xml
<multistatus>
   <d:response>
   </d:response>
   ... // cut connection here
</multistatus>
```

in this case the desktop client would think that the file missing after the connection cut does not exist.

This is really exxagerating, I don't think a proper XML parser would do that. But as we don't have many ideas right now, could be a way to explore...

@arjones85 was this file in the middle of a folder listing or was it alone on the folder ?

The crazy scenario I mentioned above would only be possible if the file was the last entry in the folder.

**Comment by guruz** [comment]
@PVince81 Should not happen. Else we'd get this issue all time I think.
https://github.com/owncloud/client/blob/c6f4f446192e5f11df80186e391b636471c15984/src/libsync/networkjobs.cpp#L352

**Comment by ogoffart** [comment]
The client deletes the file, mean that the client could not find the file on the local file system.

Is the file on the local file system?

If yes, there might be a bug in the client that makes it not see this file. Maybe access problem or permission? There was such bugs in the past but i tought there were all fixed.

If no, maybe the file was actually removed by another process that is not owncloud and that is not an ownclud bug.  But maybe the owncloud client has also deleted that file for an unkown reason.

Where there also other operations involved such as rename or move of some folder in the same time?

**Comment by arjones85** [comment]
The file was alone by itself at that time in a folder. It did have several more files in flight that morning that hadn't finished uploading that I canceled because of my connection glitch that morning (and they had started over). That file had finished. 

The connection glitch happened 2 hours before this file had the mysterious delete come through. I had accessed it on another Windows desktop about 20 minutes after I canceled the upload of the rest of them to ensure it was uploaded successfully (and not corrupted) and it was.

I'll try to get y'all the other log you are after. I'm evaluating this product for a company wanting to use it in house so this is just junk data I'm moving around with it right now. Manager wants me to eval some others as well so it might be a bit before I can return back to this one.

Thanks again for taking a look!

**Comment by arjones85** [comment]
ogoffart, the file really was deleted. Gone from the client and server. Nothing weird running on any of the clients, only Microsoft security essentials and it did not flag the zip as a problem.

**Comment by arjones85** [comment]
Closing issue out, team made a decision to go with a competing product so we won't be investing additional time in this one. Having syncing issues with the clients (#5520) and data being removed randomly (this issue) caused nervousness, and we didn't have any of these issues with the other product. 

Thanks for the feedback and assistance!
