### ISSUE TITLE
share problem when updating files

### ISSUE THREAD

**Issue by ThomasWitzany** [owncloud/core#27110]
when I update a file (overwrite new version) the shared user does not get an eMail notification

**Comment by kdslkdsaldsal** [comment]
@ThomasWitzany Please fill out the issue template shown when creating a new issue. Reports like this, which even is missing the used ownCloud version are pretty useless.

When reporting issues please always take some time and go through that mentioned issue template. This is asking you all info which are needed to help here. Without that information its not possible to help, sad but true.
