### ISSUE TITLE
error running cron.php

### ISSUE THREAD

**Issue by fsantiago07044** [owncloud/core#27122]
### Steps to reproduce
1. enable / run cron.php as system cron job or via cli manually
2. ensure you're running php 7.0.15 on system server
3.

### Expected behaviour
1. Work

### Actual behaviour
PHP Fatal error:  Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /var/www/html/owncloud/lib/private/DB/Connection.php:58
Stack trace:
#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/html/owncloud/lib/private/DB/Connection.php(141): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Ob in /var/www/html/owncloud/lib/private/DB/Connection.php on line 58
PHP Fatal error:  Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /var/www/html/owncloud/lib/private/DB/Connection.php:58
Stack trace:
#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/html/owncloud/lib/private/DB/Connection.php(141): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Ob in /var/www/html/owncloud/lib/private/DB/Connection.php on line 58

### Server configuration
centos 7.3.1611

**Web server:**
nginx 1.11.9

**Database:**
mariadb

**PHP version:**
7.0.15

**ownCloud version:** (see ownCloud admin page)

9.1.4 stable, 

**Updated from an older ownCloud or fresh install:**

fresh install

**Where did you install ownCloud from:**

yum install owncloud-files

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

```

**List of activated apps:**

Activity  2.3.2
Admin Config Report  0.1.1
Collaborative tags  0.3.0
Comments  0.3.0
Default encryption module  1.3.0
Deleted files  0.9.0
Federation  0.1.0
First run wizard  1.1
Gallery  15.0.0
Mail Template Editor  0.1
Notifications  0.3.0
PDF Viewer  0.8.1
Provisioning API  0.5.0
Share Files  0.10.0
Text Editor  2.1
Update notification  0.2.1
Versions  1.3.0
Video player  0.9.8

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /var/www/html/owncloud/lib/private/DB/Connection.php:58
Stack trace:
#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/html/owncloud/lib/private/DB/Connection.php(141): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/html/owncloud/lib/private/DB/ConnectionFactory.php(120): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/html/owncloud/lib/private/Server.php(414): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/html/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /var/www/html/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /var/www/html/owncloud/lib/private/Server.php(973): OC\ServerContainer->query('DatabaseConnect...')
#12 /var/www/html/owncloud/lib/private/Server.php(219): OC\Server->getDatabaseConnection()
#13 /var/www/html/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#14 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('OC\\Authenticati...')
#15 /var/www/html/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#16 /var/www/html/owncloud/lib/private/Server.php(223): OC\ServerContainer->query('OC\\Authenticati...')
#17 /var/www/html/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#18 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('OC\\Authenticati...')
#19 /var/www/html/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#20 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(150): OC\ServerContainer->query('OC\\Authenticati...')
#21 /var/www/html/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#22 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('OC\\Authenticati...')
#23 /var/www/html/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#24 /var/www/html/owncloud/lib/private/Server.php(238): OC\ServerContainer->query('OC\\Authenticati...')
#25 /var/www/html/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#26 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('UserSession')
#27 /var/www/html/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
#28 /var/www/html/owncloud/lib/private/Server.php(850): OC\ServerContainer->query('UserSession')
#29 /var/www/html/owncloud/lib/private/Server.php(458): OC\Server->getUserSession()
#30 /var/www/html/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#31 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('AppManager')
#32 /var/www/html/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#33 /var/www/html/owncloud/lib/private/Server.php(1150): OC\ServerContainer->query('AppManager')
#34 /var/www/html/owncloud/lib/private/legacy/app.php(285): OC\Server->getAppManager()
#35 /var/www/html/owncloud/lib/private/legacy/app.php(106): OC_App::getEnabledApps()
#36 /var/www/html/owncloud/lib/base.php(573): OC_App::loadApps(Array)
#37 /var/www/html/owncloud/lib/base.php(973): OC::init()
#38 /var/www/html/owncloud/console.php(58): require_once('/var/www/html/o...')
#39 /var/www/html/owncloud/occ(11): require_once('/var/www/html/o...')
#40 {main}[root@server201782020379 owncloud]# 

```

**The content of config/config.php:**

<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => '',
  'dbtype' => 'mysql',
  'version' => '9.1.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => '',
  'mail_domain' => '',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => ',
  'mail_smtpport' => '587',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'redis' => array (
    'host' => '127.0.0.1',
    'port' => 6379,
    'timeout' => 0.0,
    'password' => '',
  ),
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: could not find driver in /var/www/html/owncloud/lib/private/DB/Connection.php:58
Stack trace:
#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/html/owncloud/lib/private/DB/Connection.php(141): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/html/owncloud/lib/private/DB/ConnectionFactory.php(120): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/html/owncloud/lib/private/Server.php(414): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/html/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /var/www/html/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /var/www/html/owncloud/lib/private/Server.php(973): OC\ServerContainer->query('DatabaseConnect...')
#12 /var/www/html/owncloud/lib/private/Server.php(219): OC\Server->getDatabaseConnection()
#13 /var/www/html/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#14 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('OC\\Authenticati...')
#15 /var/www/html/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#16 /var/www/html/owncloud/lib/private/Server.php(223): OC\ServerContainer->query('OC\\Authenticati...')
#17 /var/www/html/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#18 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('OC\\Authenticati...')
#19 /var/www/html/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#20 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(150): OC\ServerContainer->query('OC\\Authenticati...')
#21 /var/www/html/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#22 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('OC\\Authenticati...')
#23 /var/www/html/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#24 /var/www/html/owncloud/lib/private/Server.php(238): OC\ServerContainer->query('OC\\Authenticati...')
#25 /var/www/html/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#26 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('UserSession')
#27 /var/www/html/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
#28 /var/www/html/owncloud/lib/private/Server.php(850): OC\ServerContainer->query('UserSession')
#29 /var/www/html/owncloud/lib/private/Server.php(458): OC\Server->getUserSession()
#30 /var/www/html/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#31 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('AppManager')
#32 /var/www/html/owncloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#33 /var/www/html/owncloud/lib/private/Server.php(1150): OC\ServerContainer->query('AppManager')
#34 /var/www/html/owncloud/lib/private/legacy/app.php(285): OC\Server->getAppManager()
#35 /var/www/html/owncloud/lib/private/legacy/app.php(106): OC_App::getEnabledApps()
#36 /var/www/html/owncloud/lib/base.php(573): OC_App::loadApps(Array)
#37 /var/www/html/owncloud/lib/base.php(973): OC::init()
#38 /var/www/html/owncloud/console.php(58): require_once('/var/www/html/o...')
#39 /var/www/html/owncloud/occ(11): require_once('/var/www/html/o...')
#40 {main}[root@server201782020379 owncloud]# 

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => '',
  'dbtype' => 'mysql',
  'version' => '9.1.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => '',
  'mail_domain' => '',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => ',
  'mail_smtpport' => '587',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'redis' => array (
    'host' => '127.0.0.1',
    'port' => 6379,
    'timeout' => 0.0,
    'password' => '',
  ),
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

```

### Client configuration
**Browser:**
latest google chrome

**Operating system:**
windows 10 / fedora 25

### Logs
#### Web server error log
```
no pertinent errors present

```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"","remoteAddr":"","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user '' for table 'user'","level":3,"time":"2017-02-09T00:21:55+00:00","method":"POST","url":"\/index.php","user":"--"}
{"reqId":"","remoteAddr":"","app":"mysql.setup","message":"Database creation failed: An exception occurred while executing 'GRANT ALL PRIVILEGES ON `owncloud` . * TO ''':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user '' to database 'owncloud'","level":3,"time":"2017-02-09T00:21:55+00:00","method":"POST","url":"\/index.php","user":"--"}
{"reqId":"","remoteAddr":"","app":"index","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 8 passed to OC\\\\Core\\\\Controller\\\\AvatarController::__construct() must implement interface OCP\\\\Files\\\\Folder, null given, called in \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/Application.php on line 96\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/Application.php(96): OC\\\\Core\\\\Controller\\\\AvatarController->__construct('core', Object(OC\\\\AppFramework\\\\Http\\\\Request), Object(OC\\\\AvatarManager), Object(OC\\\\Cache\\\\File), Object(OC\\\\L10N\\\\L10N), Object(OC\\\\User\\\\Manager), Object(OC\\\\User\\\\Session), NULL, Object(OC\\\\Log))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Core\\\\Application->OC\\\\Core\\\\{closure}(Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(102): Pimple\\\\Container->offsetGet('AvatarControlle...')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(82): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('AvatarControlle...')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('AvatarControlle...', 'getAvatar', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#5 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/avatar\\\/...')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/Controller\\\/AvatarController.php\",\"Line\":81}","level":3,"time":"2017-02-09T00:49:04+00:00","method":"GET","url":"\/index.php\/avatar\/\/336","user":"--"}

```

#### Browser log
```
Insert your browser log here, this could for example include:

no browser errors present

```

**Comment by fsantiago07044** [comment]
updated all details as i moved versions and also included further info.

**Comment by DeepDiver1975** [comment]
The database module is not available in cli mode of your php installation. 

Please run php -m

**Comment by fsantiago07044** [comment]
On February 9, 2017 1:58:28 AM EST, "Thomas Müller" <notifications@github.com> wrote:
>The database module is not available in cli mode of your php
>installation. 
>
>Please run php -m

Thanks. You answered my question and solved the problem but not in the way you may think. I made a silly error. 

I installed php 7 from the remi repo. It places a symlink under /use/bin called php70, pointing at /opt/remi/php70/root/usr/bin/php. Knowing I installed php70 from remi, I borked my grep when I ran an ls against /usr/bin just to confirm my php binary location and it only returned php70, not php. So I was trying to use that one. Once I tried php, it works fine. Thank you and sorry. 

The command php -m returns the mysql module in the list but php70 -m obviously does not:

bz2
calendar
Core
ctype
curl
date
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mbstring
openssl
pcntl
pcre
PDO
pdo_sqlite
Phar
readline
Reflection
session
sockets
SPL
sqlite3
standard
tokenizer
zlib

[Zend Modules]


Thanks again. 

- Fabian S.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
