### ISSUE TITLE
Add column for execution duration in oc_jobs table

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27137]
Could be useful for debugging.

@DeepDiver1975 @butonic @jvillafanez

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/issues/27144

**Comment by noveens** [comment]
@PVince81 ,
you'll have to close this, forgot the protip :P

**Comment by PVince81** [comment]
@noveens thanks for this great addition!
