### ISSUE TITLE
Integrity check fails after update to 9.1.4 due to stray .gitignore files

### ISSUE THREAD

**Issue by sagamusix** [owncloud/core#27139]
I am using the ownCloud package repository for Debian. I upgraded to v9.1.4 from the previous stable version, and now I get a warning that integrity checks failed. This appears to happen due to stray .gitignore files in several 3rdparty sub-directories. The expected hash is empty, so I guess those files should not be there.

### Steps to reproduce
1. Upgrade to latest ownCloud core using the Debian packages provided by ownCloud (not Debian's own packages)
2. Do the upgrade through occ
3. Go to administration panel to find a warning about integrity checks.

### Server configuration
**Operating system**: Bananian (~Debian Jessie)

**Web server:** Apache 2.4.10

**Database:** MariaDB

**PHP version:** 5.6.30

**ownCloud version:** 9.1.4

**Updated from an older ownCloud or fresh install:** Updated (this is whole issue, after all)

**Where did you install ownCloud from:** ownCloud Debian repository

**Comment by hodyroff** [comment]
@crrodriguez

**Comment by PVince81** [comment]
I don't think it's a problem with the release script because there was no change there regarding to git files.

@crrodriguez let me know what you find.

**Comment by sagamusix** [comment]
Full list:
```
- core
	- EXTRA_FILE
		- 3rdparty/3rdparty/rackspace/php-opencloud/.gitignore
		- 3rdparty/3rdparty/sabre/dav/.gitignore
		- 3rdparty/3rdparty/sabre/vobject/.gitignore
		- 3rdparty/3rdparty/sabre/xml/.gitignore
		- 3rdparty/3rdparty/sabre/event/.gitignore
		- 3rdparty/3rdparty/sabre/http/.gitignore
		- 3rdparty/3rdparty/sabre/uri/composer.json
		- 3rdparty/3rdparty/sabre/uri/lib/functions.php
		- 3rdparty/3rdparty/sabre/uri/lib/Version.php
		- 3rdparty/3rdparty/sabre/uri/CHANGELOG.md
		- 3rdparty/3rdparty/sabre/uri/.gitignore
		- 3rdparty/3rdparty/composer.json
		- 3rdparty/3rdparty/react/promise/.gitignore
		- 3rdparty/3rdparty/lukasreschke/id3parser/.gitignore
		- 3rdparty/3rdparty/doctrine/common/.gitmodules
		- 3rdparty/3rdparty/doctrine/common/.gitignore
		- 3rdparty/3rdparty/doctrine/inflector/.gitignore
		- 3rdparty/3rdparty/doctrine/cache/.gitignore
		- 3rdparty/3rdparty/doctrine/collections/.gitignore
		- 3rdparty/3rdparty/icewind/streams/src/CallbackWrapper.php
		- 3rdparty/3rdparty/icewind/streams/src/Path.php
		- 3rdparty/3rdparty/icewind/streams/src/Wrapper.php
		- 3rdparty/3rdparty/icewind/streams/.gitignore
		- 3rdparty/3rdparty/bantu/ini-get-wrapper/.gitignore
		- 3rdparty/3rdparty/pear/pear-core-minimal/.gitignore
		- 3rdparty/3rdparty/pear/pear_exception/.gitignore
		- 3rdparty/3rdparty/pear/console_getopt/.gitignore
		- 3rdparty/3rdparty/pear/archive_tar/.gitignore
		- 3rdparty/3rdparty/composer.lock
		- 3rdparty/3rdparty/composer/installed.json
		- 3rdparty/3rdparty/composer/autoload_classmap.php
		- 3rdparty/3rdparty/composer/autoload_real.php
		- 3rdparty/3rdparty/.gitignore
		- updater/updater/vendor/pimple/pimple/.gitignore
		- updater/updater/vendor/guzzlehttp/ringphp/.gitignore
		- updater/updater/vendor/guzzlehttp/streams/.gitignore
		- updater/updater/vendor/symfony/console/.gitignore
		- updater/updater/vendor/psr/log/.gitignore
		- updater/updater/.gitignore
```

**Comment by crrodriguez** [comment]
I will make sure .gitignore files are never packaged.. however the PHP scripts are most likely necessary for operation

**Comment by PVince81** [comment]
build scripts were updated to not package gitignore
