### ISSUE TITLE
Move files in interface (feature request)

### ISSUE THREAD

**Issue by robertboyl** [owncloud/core#27140]
As per https://central.owncloud.org/t/move-files-in-web-interface/5422/3

Maybe there could be a Move inside menu where there's rename, delete, etc. Some might not notice its possible to drag and drop.

Thanks.

**Comment by kdslkdsaldsal** [comment]
@robertboyl Hi, this is a duplicate of https://github.com/owncloud/core/issues/10656 so you can close this feature request here. If you have additional notes / suggestions how to implement this you might want to post them at the previous link
