### ISSUE TITLE
Bad UX saving the modifications of a retention period rule

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27147]
If you modify a rule, a tick appears, and it is needed to click on it in order to save the modifications made in the rule. I guess it would be better a 'save button'

![workflowsave](https://cloud.githubusercontent.com/assets/10596560/22877916/e88d376e-f1d7-11e6-8419-6daedde57bb7.gif)

**Comment by PVince81** [comment]
please reopen in the workflow repo
