### ISSUE TITLE
Cannot enable user_ldap

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27154]
### Steps

1. Check out core from git
1. Purposefully forget to check out the user_ldap app
1. Setup OC
1. `occ app:enable user_ldap`

### Expected
Useful error message

### Actual
Useless error message

```
± % occ app:enable user_ldap                    
An unhandled exception has been thrown:
TypeError: Argument 1 passed to OC\App\DependencyAnalyzer::analyze() must be of the type array, null given, called in /srv/www/htdocs/owncloud/lib/private/legacy/app.php on line 1178 and defined in /srv/www/htdocs/owncloud/lib/private/App/DependencyAnalyzer.php:53
Stack trace:
#0 /srv/www/htdocs/owncloud/lib/private/legacy/app.php(1178): OC\App\DependencyAnalyzer->analyze(NULL)
#1 /srv/www/htdocs/owncloud/lib/private/legacy/app.php(348): OC_App::checkAppDependencies(Object(OC\AllConfig), Object(OC\L10N\L10N), NULL)
#2 /srv/www/htdocs/owncloud/core/Command/App/Enable.php(75): OC_App::enable('user_ldap')
#3 /srv/www/htdocs/owncloud/lib/composer/symfony/console/Command/Command.php(256): OC\Core\Command\App\Enable->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /srv/www/htdocs/owncloud/lib/composer/symfony/console/Application.php(818): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /srv/www/htdocs/owncloud/lib/composer/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\App\Enable), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /srv/www/htdocs/owncloud/lib/composer/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /srv/www/htdocs/owncloud/lib/private/Console/Application.php(158): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /srv/www/htdocs/owncloud/console.php(99): OC\Console\Application->run()
#9 /srv/www/htdocs/owncloud/occ(11): require_once('/srv/www/htdocs...')
#10 {main}
```

### Versions
master / 10.0 pre-alpha

Not sure if this is a regression.

@VicDeo can you have a look ?

**Comment by PVince81** [comment]
Even worse: I can't even enable user_ldap even when the app is there.
Same error message.

**Comment by PVince81** [comment]
Looks like this is specific to the user_ldap app.
Activity app works fine.

Weiiird

**Comment by PVince81** [comment]
After checking out the user_ldap repo into the apps folder, the LDAP app still doesn't appear in the new "Apps" section in the settings.

`occ app:list` shows it disabled.

**Comment by DeepDiver1975** [comment]
hint: this happens if the info.xml cannot be loaded - due to what ever reason

**Comment by PVince81** [comment]
Oh well... then I'll debug this myself

**Comment by PVince81** [comment]
Ok, here's what is happening:

- apps/user_ldap contained an older user_ldap app from another branch
- apps3/user_ldap contains the most recent user_ldap from git.

In past versions, OC was able to figure out which one of both to load based on supported versions.
This apparently stopped working.

**Comment by DeepDiver1975** [comment]
> In past versions, OC was able to figure out which one of both to load based on supported versions.
> This apparently stopped working.

afaik it never worked properly if the same app was installed multiple times.
We should bail out with an exception in this scenario

**Comment by PVince81** [comment]
Damn, I deleted the version in apps/user_ldap and can't recreate the problem now.

Not sure what version that was. Neither the stable9.1 version not a past git version can reproduce the problem.

The weird thing is that the folder was there but `git status` didn't seem to see it as a change.
Maybe a temporary ghost... Oh well, let's not waste more time with this.
