### ISSUE TITLE
Feature Request: Log: giving "Invalidating tokens older than" an "App" name

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#27167]
Currently we have in the log following entries:
``no app in context`` ``Invalidating tokens older than ...``

What about if we write
``Backgroundjob`` ``Invalidating tokens older than ...`` ?

**Comment by PVince81** [comment]
I suggest moving the log statement to the matching background job first then adjust the app name.

Currently we don't have an app name for background jobs, in this case the code lives in core so technically the app name would be "core".

**Comment by PVince81** [comment]
Turns out there's the string "cron" for background jobs, so we could use that.

@mmattel PR ?

**Comment by noveens** [comment]
@PVince81 ,
close the issue?

**Comment by mmattel** [comment]
Closing, fix in #27201
