### ISSUE TITLE
Streaming *.mov files does not work

### ISSUE THREAD

**Issue by marbetschar** [owncloud/core#27161]
### Steps to reproduce
1. Upload *.mov file to ownCloud
2. Share folder containing the *.mov file with a public link
3. Open the public link and try to open the *.mov file in the browser

### Expected behaviour
The video should be played within the browser.

### Actual behaviour
ownClouds shows the following error:
![owncloud](https://cloud.githubusercontent.com/assets/392542/22971946/d78f340c-f377-11e6-936e-c79cd90c9333.png)

### Server configuration
**Operating system**: Ubuntu 14.04 LTE
**Web server:** NGINX
**Database:** MariaDB
**PHP version:** 5.7
**ownCloud version:** 9.0.2
**Updated from an older ownCloud or fresh install:**
**Where did you install ownCloud from:**
**Signing status (ownCloud 9.0 and above):**

```
http://example.com/index.php/settings/integrity/failed:
No errors have been found.
```

**Comment by DeepDiver1975** [comment]
Which browser are you using?

**Comment by marbetschar** [comment]
**macOS**
- [ ] Safari Version 10.1 (12603.1.23.1): Does **not** work
- [ ] Chrome Version 56.0.2924.87 (64-bit): Does **not** work
- [X] Firefox 51.0.1 (64-Bit): Does work - **yeeehaaa!!**

**iOS 10.2.1**
- [ ] Safari: Does **not** work

**Comment by kdslkdsaldsal** [comment]
@marbetschar 

> ownCloud version: 9.0.2

This is far to outdated to report issues here (you're currently missing 6 updates: https://owncloud.org/changelog/#latest9.0)

The following FAQ has all needed info about such issues: https://central.owncloud.org/t/how-to-get-shared-videos-to-play-in-the-browser/1128

**Comment by marbetschar** [comment]
@kdslkdsaldsal thanks for pointing this out. I will update the ownCloud instance in the next few days.

Unfortunately the FAQ did not solve the problem - and I've not found any hints in the release notes that this sort of problem has been wiped out.

**Comment by DeepDiver1975** [comment]
@marbetschar to some extend we rely on browsers supporting the codec - there is no much we can do given the current implementation.

**Comment by kdslkdsaldsal** [comment]
@marbetschar You need at least ownCloud 9.0.3 for shared link video playback as explained in the FAQ. Everything else is up to your browser as explained by @DeepDiver1975

**Comment by PVince81** [comment]
To be able to stream formats unsupported by browsers, would require on-the-fly transcoding: https://github.com/owncloud/core/issues/24480

Closing in favor of that ticket
