### ISSUE TITLE
SQL table "oc_documents_invite" missing primary key

### ISSUE THREAD

**Issue by bluikko** [owncloud/core#27164]
The table "oc_documents_invite" is missing primary key. For example Galera replication requires primary keys on all tables. Could the primary key please be added?

**Comment by kdslkdsaldsal** [comment]
@bluikko Could you please re-open this in the issue tracker of the documents app located here: https://github.com/owncloud/documents/issues

Thnx

**Comment by bluikko** [comment]
Done.

https://github.com/owncloud/documents/issues/682
