### ISSUE TITLE
Global credentials for external storage section is located in additonal menu instead of Storage

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27166]
### Steps to reproduce
1. As oC go to additional section in settings menu

### Expected behaviour
The Global credentials for external storage section should be in Storage menu

### Actual behaviour
Global credentials for external storage section are located in addtional menu

![screen shot 2017-02-15 at 16 43 14](https://cloud.githubusercontent.com/assets/10596560/22982109/6a066c44-f39e-11e6-916b-fa4623f349f4.png)

@tomneedham

**Comment by DeepDiver1975** [comment]
@tomneedham

**Comment by tomneedham** [comment]
Hmm which app provides this panel?

**Comment by DeepDiver1975** [comment]
> Hmm which app provides this panel?

https://github.com/owncloud/windows_network_drive/blob/be5a6d859322c7751b8b8e6f76a33c039b1bc3f0/templates/globalauth.php#L7
