### ISSUE TITLE
Errors on first time login

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#27178]
### Steps to reproduce
1. Clone core (only) for dev purposes
2. Do the first time setup

### Expected behaviour
No error should be logged 

### Actual behaviour
Error gets logged

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** (see ownCloud admin page)
10, Clone from Core yesterday

**Updated from an older ownCloud or fresh install:** No

**Where did you install ownCloud from:** git

### Client configuration
**Browser:** Opera

**Operating system:** Ubuntu 16.04

#### ownCloud log (data/owncloud.log)
```
{"reqId":"J1rZhVdpCj6gGXqA22lo","remoteAddr":"127.0.0.1","app":"PHP","message":"Missing argument 1 for OC\\User\\Session::prepareUserLogin(), called in \/var\/www\/owncloud\/core\/lib\/private\/User\/Session.php on line 510 and defined at \/var\/www\/owncloud\/core\/lib\/private\/User\/Session.php#380","level":3,"time":"2017-02-18T17:21:24+01:00","method":"GET","url":"\/apps\/files\/","user":"user_x"}

{"reqId":"J1rZhVdpCj6gGXqA22lo","remoteAddr":"127.0.0.1","app":"PHP","message":"Undefined variable: firstTimeLogin at \/var\/www\/owncloud\/core\/lib\/private\/User\/Session.php#388","level":3,"time":"2017-02-18T17:21:24+01:00","method":"GET","url":"\/apps\/files\/","user":"user_x"}
```

**session.php**

https://github.com/owncloud/core/blob/f10d105ea2f2d0822693313ddcd6f9b2eaac6ebe/lib/private/User/Session.php#L510
``$this->prepareUserLogin();``

https://github.com/owncloud/core/blob/f10d105ea2f2d0822693313ddcd6f9b2eaac6ebe/lib/private/User/Session.php#L380
``protected function prepareUserLogin($firstTimeLogin) {``

https://github.com/owncloud/core/blob/f10d105ea2f2d0822693313ddcd6f9b2eaac6ebe/lib/private/User/Session.php#L388
``if ($firstTimeLogin) {``

**Comment by DeepDiver1975** [comment]
I have seen this as well these days - here is the fix: https://github.com/owncloud/core/pull/27165/files#diff-9c47cee6ac987e5256aeee509f91ddb1R380

**Comment by mmattel** [comment]
Just to have the solution to this issue stated here like you see in the big diff,
it is: ``protected function prepareUserLogin($firstTimeLogin = false) {``

**Comment by PVince81** [comment]
Likely obsolete. Please reopen if still happening with OC 10.0 beta or latest master
