### ISSUE TITLE
Wrong LDAP Search Results when we set several User Search Attributes and we search by a pattern with an space

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27171]
### Steps to reproduce

1. As admin user go to admin page
2. Configure a LDAP instance and set several User Search Attributes
3. Go to user page and search a pattern that contains an space

### Expected behaviour

Search results match with the pattern

### Actual behaviour

Search results do not match with the pattern searched

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.0"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**

 Mozilla

**Results without setting any User Search Attributes**

![screen shot 2017-02-16 at 09 24 14](https://cloud.githubusercontent.com/assets/10596560/23013437/d83314ce-f42a-11e6-9342-ba965deeff25.png)

**Results setting several User Search Attributes**

![screen shot 2017-02-16 at 09 22 45](https://cloud.githubusercontent.com/assets/10596560/23013456/f09837d8-f42a-11e6-813e-c8d54b6c3740.png)

 
![screen shot 2017-02-16 at 09 23 40](https://cloud.githubusercontent.com/assets/10596560/23013463/f830efbc-f42a-11e6-96cc-3f25cd85204a.png)

@jvillafanez FYI

**Comment by PVince81** [comment]
@davitol next time please raise in the LDAP repo: https://github.com/owncloud/user_ldap

**Comment by PVince81** [comment]
Please reopen in [user_ldap app repo](https://github.com/owncloud/user_ldap) if issue persists with 10.0.4 and the latest user_ldap app from marketplace.
