### ISSUE TITLE
oc8.0.16,the folder name can not be chinese charts

### ISSUE THREAD

**Issue by woeoio** [owncloud/core#27170]
### Steps to reproduce
1.rename anyone folder.
2.review show "files"
3.and can not be use again.

### Expected behaviour
Tell us what should happen
oc8.0.16,the folder name can not be chinese charts,if name it,well show "files" name,and can not be use again.but i try to upload a chinese name file,it well show and can be download to use.
### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
windows8.1
**Web server:**
apache
**Database:**
mysql
**PHP version:**
php5.4
**ownCloud version:** (see ownCloud admin page)
oc8.1
**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**
my pc
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
here,can i use smb for my main data path,like: smb://user:pwd@host/folder?
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
no
```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
chrime
**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by woeoio** [comment]
我遇到传说中的中文bug了吗？我的oc8.1，新建，重命名，上传，文件夹都不能使用中文名字，否则就变成“files”文件夹名字，而且不能点开，但是可以上传中文文件，也可以正常下载，（数据目录的实际文件名其实已经被过滤掉了中文，比如“照片1.jpg”变成了“1.jpg"。同样，也不可以重命名这个文件，除非使用英文字符，难道那么多人用oc，一个人都没碰到中文文件名的问题吗？

**Comment by woeoio** [comment]
![image](https://cloud.githubusercontent.com/assets/24835883/23003721/93427154-f42d-11e6-8f07-21c94a750e5a.png)

**Comment by woeoio** [comment]
![image](https://cloud.githubusercontent.com/assets/24835883/23003777/ec7f327a-f42d-11e6-843c-c6513e76ffb3.png)

**Comment by kdslkdsaldsal** [comment]
@woeoio Please note that running ownCloud on windows hosts is unsupported since a longer time as stated at various places. Furthermore oC 8.0 reached its End-of-life a few months ago.

There won't be any support or bugfixes for your current setup. Instead please setup ownCloud 9.1.4 on a linux based host (e.g. the Community VM / Appliance from https://owncloud.org/install/#edition) and try again.

**Comment by woeoio** [comment]
thank you for reply this issue,but i really need to run it on my windows,because my data need share other way,so i am checking oc8.1's codes now,maybe i can fix it.good lock: you and me.

**Comment by woeoio** [comment]
@kdslkdsaldsal thank you!

**Comment by woeoio** [comment]
i try new version in VM already,that is not my bast choice,

**Comment by kdslkdsaldsal** [comment]
@woeoio You can't run ownCloud on windows.

**Comment by woeoio** [comment]
sorry,i use oc8.0.16, not v8.1,

**Comment by kdslkdsaldsal** [comment]
See:

> Even oC 8.0 won't run reliable on Windows due to the limiations of PHP on Windows.

Please close here as there is no point to discuss this further.

**Comment by woeoio** [comment]
ok
i well close.

**Comment by woeoio** [comment]
也许有人也会碰到这种问题，只是oc写的太差了，国内很多php文件管理器都支持中文，而且相当好，我已经换了一款软件了，痛弃oc

**Comment by woeoio** [comment]
交流 QQ: 215879458

**Comment by kdslkdsaldsal** [comment]
> 也许有人也会碰到这种问题，只是oc写的太差了，国内很多php文件管理器都支持中文，而且相当好，我已经换了一款软件了，痛弃oc

Online translation:

> Some people may encounter such a problem, but oc wrote too bad, many domestic php file manager support Chinese, and very good, I have changed a software, and abandoned oc

As written above, this is not about Chinese chars itself. The problem is from the fact that you're insisting on using an unsupported version of ownCloud (8.0) on an unsupported operating system (Windows).

If you're facing issues with Chinese chars on a recent ownCloud version 9.1.4 the developers are very happy to fix any bugs you're facing.

**Comment by PVince81** [comment]
@woeoio 最好是要用Linux操作系统。在服务器上应该用UTF-8。这样从Windows客户端上载的文件可以有汉字的名字。
