### ISSUE TITLE
Swarm filesystem

### ISSUE THREAD

**Issue by hynese** [owncloud/core#27180]
Feature request: Can we integrate with [Swarm ](http://swarm-gateways.net/bzz:/theswarm.eth/)distributed filesystem?

There's a FUSE driver for Swarm coming very soon. I wonder how can my owncloud take advantage?

**Comment by hodyroff** [comment]
ownCloud works with any file system which can be mounted in Linux. However: we can not recommend FUSE drivers unless they are very, very, very stable and tested. All FUSE drivers I am aware of don't provide reliable stability, integrity and performance. There is always the possibility to do a native integration, of course thats a lot of work but can bring specific features to live (like CERN does with their EOS file system).
Nothing to do for ownCloud at this time.

**Comment by hynese** [comment]
@hodyroff Thank you very kindly for your message. I understand that FUSE for Swarm is coming soon. There was a slide on FUSE in Paris a few days ago: http://swarm-gateways.net/bzz:/swarm-edcon-slides.test/#22 It's good to know that FUSE drivers aren't recommended. I'll keep this in mind. The EOS filesystem is a very useful reference point. Regards to you,
