### ISSUE TITLE
Failing Jenkins Continuous Integration

### ISSUE THREAD

**Issue by imujjwal96** [owncloud/core#27187]
### Actual behaviour
Almost all the recent pull requests are failing Jenkins continuous integration and are showing a similar output in its log. I do not know if the problem is in the PRs, but having the same log for so many PR's seems fishy

![image](https://cloud.githubusercontent.com/assets/8245662/23138568/322d0d4e-f7ce-11e6-90da-b289bf51fe27.png)

**Comment by DeepDiver1975** [comment]
after server reboot the issue seems gone.
