### ISSUE TITLE
Overlapping progress bar and description of an app.

### ISSUE THREAD

**Issue by noveens** [owncloud/core#27182]
### Steps to reproduce
1. Go to the apps page in setting menu (under the admin bar)
2. Click on the show-description button of the app while the progress bar is still running.

### Screenshot
![bug](https://cloud.githubusercontent.com/assets/23054294/23136297/1a98d156-f7c2-11e6-88e2-0ff665f5c8e2.png)

### Expected behaviour
The progress bar should not overlap with the description of the app.

### Actual behaviour
The progress bar overlaps with the description of the app.

### Server configuration
**Operating system**:
Ubuntu 16.10

**Web server:**
apache

**Database:**
sqlite

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
10.0.0

**Updated from an older ownCloud or fresh install:**
fresh clone of owncloud's core repository

**Where did you install ownCloud from:**
Clone of OC's core repository

**Signing status (ownCloud 9.0 and above):**
None

**List of activated apps:**
```
Enabled:
  - comments: 0.3.0
  - dav: 0.2.8
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - files_external
  - testing
```
**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocr5wxqbp599",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/var\/www\/core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/core",
        "dbtype": "sqlite3",
        "version": "10.0.0.4",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "maintenance": false
    }
}
```
**Are you using external storage, if yes which one:** /var/www/core/data

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
google chrome stable

**Operating system:**
ubuntu 16.10

#### Web server error log

None required
#### ownCloud log (data/owncloud.log)

None required
#### Browser log

None required

**Comment by noveens** [comment]
@tomneedham ,
Can you have a look?

**Comment by tomneedham** [comment]
Hey @noveens what progress bar is this?

**Comment by noveens** [comment]
@tomneedham ,
Even I don't know, it just keeps on loading on my local server.

**Comment by tomneedham** [comment]
Is it a circular progress indicator? And this is still appearing after the list of enabled apps has loaded? Could you send me a gif / screenshot?

**Comment by noveens** [comment]
Sorry forgot to put the screenshot link, edited the bug description.
