### ISSUE TITLE
drag and drop folder with chinese characters name  throw an invalidstateerror exception

### ISSUE THREAD

**Issue by ncist2011** [owncloud/core#27199]
### Steps to reproduce
1.drag and drop folder with chinese characters name to web GUI, using Firefox on windows, for example: the name is 测试
2.you will see the exception

### Actual behaviour
error uploading file "invalidStateError" no file was uploaded, unknown error

### Server configuration
**Operating system**:
ubuntu 16.04
**Web server:**
apache
**Database:**
mysql
**PHP version:**
5.5.9
**ownCloud version:** (see ownCloud admin page)
9.1.3

### Client configuration
**Browser:**
firefox  
**Operating system:**
windows7
![qq20170221-0](https://cloud.githubusercontent.com/assets/4124982/23164803/ec14e826-f873-11e6-8627-76ecd3feba8c.png)

**Comment by hodyroff** [comment]
Does this happen with all browsers? Did it work in previous versions?

**Comment by ncist2011** [comment]
This only happens in Firefox,  no matter what version it is

**Comment by PVince81** [comment]
Does it work without Chinese characters ?

As far as I know Firefox doesn't support folder upload at all currently, only Chromium.

Not an ownCloud bug, closing
