### ISSUE TITLE
Errors in "Settings" get logged

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#27198]
### Steps to reproduce
1. Clone core (only) for dev purposes
2. Do the first time setup
3. Switch to Settings (errors are also thrown when you change in settings eg the language and the page gets reloaded)

### Expected behaviour
No error should be logged 

### Actual behaviour
Errors get logged

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.0 + Redis

**ownCloud version:** (see ownCloud admin page)
10, Clone from Core yesterday

**Updated from an older ownCloud or fresh install:** No

**Where did you install ownCloud from:** git

### Client configuration
**Browser:** Opera

**Operating system:** Ubuntu 16.04

#### ownCloud log (data/owncloud.log)
```
{"reqId":"NQHIRdrIj5FnEClC+LmO","remoteAddr":"127.0.0.1","app":"PHP","message":"Illegal offset type in isset or empty at \/var\/www\/owncloud\/core\/lib\/private\/Cache\/CappedMemoryCache.php#41","level":3,"time":"2017-02-21T13:02:17+01:00","method":"GET","url":"\/settings\/personal","user":"user_x"}

{"reqId":"NQHIRdrIj5FnEClC+LmO","remoteAddr":"127.0.0.1","app":"PHP","message":"Object of class OC\\User\\User could not be converted to string at \/var\/www\/owncloud\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#91","level":3,"time":"2017-02-21T13:02:17+01:00","method":"GET","url":"\/settings\/personal","user":"user_x"}

{"reqId":"NQHIRdrIj5FnEClC+LmO","remoteAddr":"127.0.0.1","app":"PHP","message":"Illegal offset type at \/var\/www\/owncloud\/core\/lib\/private\/Cache\/CappedMemoryCache.php#49","level":3,"time":"2017-02-21T13:02:17+01:00","method":"GET","url":"\/settings\/personal","user":"user_x"}

```

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/core/pull/27197
