### ISSUE TITLE
Cannot install owncloud on RHEL7

### ISSUE THREAD

**Issue by tdiesler** [owncloud/core#27200]
Following the instructions on https://download.owncloud.org/download/repositories/stable/owncloud

for a RHEL7 instance on EC2, I get

```
$ sudo yum install -y owncloud
...
---> Package owncloud-deps-php5.noarch 0:9.1.4-2.1 will be installed
--> Processing Dependency: php-mbstring for package: owncloud-deps-php5-9.1.4-2.1.noarch
--> Finished Dependency Resolution
Error: Package: owncloud-deps-php5-9.1.4-2.1.noarch (ce_stable)
           Requires: php-mbstring
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by tdiesler** [comment]
As a workaround, you can do this before you install owncloud

```
$ sudo yum update -y
$ sudo yum-config-manager --enable rhui-REGION-rhel-server-optional
$ sudo yum install -y wget
```

**Comment by hodyroff** [comment]
@crrodriguez please check

**Comment by tdiesler** [comment]
After that, I hit the SELinux wall, which may be related to #26345

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
