### ISSUE TITLE
CardDAV: Sync with user backend

### ISSUE THREAD

**Issue by juliusstoerrle** [owncloud/core#27217]
Is there a way to sync contacts with the user backend?

I got the IMAP user backend enabled and it would be great to automatically create contactc when they log in (register/get created). 
I mean with all backends not just with IMAP.

Looking into the code of the `app/dav/` I can see that there are hooks registered on those events.
They seem to create new contacts but I m not sure and I definitely can't see any in the UI.

**Comment by PVince81** [comment]
What contacts are you talking about ? The contacts from the IMAP server address book if it's a mail server ?

Or are you talking about converting user contacts to actual ownCloud users ? This sounds quite dangerous as it could give anyone access to ownCloud. But on the other hand, these users do not have any password at all so could not login anyway...

Can you describe the use case in detail ?

**Comment by juliusstoerrle** [comment]
No if a user Logs in with his IMAP login credentials for the first time. A new user is registered in OwnCloud, right? 
Our emails look like firstname.lastname@example.com.
So we got the users name and his email.

With this data present I now want to automatically create a CardDav Contact.

**Comment by PVince81** [comment]
Ah, so this is specific to the IMAP backend because other backends to not necessarily login with email address. This needs to be done by the IMAP backend after logging in.

In what address book should the Carddav contact be created ? For the current user only or all users in the instance ? (can take a while, needs iterating over all users)

**Comment by juliusstoerrle** [comment]
Well its probably the easiest to do it for the IMAP Backend but you cloud do it for everybody and update the contact as soon as they provide a email address for their account.

I would suggest creating a setting to choose a global address book you can share. But I don't know if that's possible. Just creating it for that user does not make any sense from my point of view. If it takes a while to loop other them maybe its best to create a cron job?

**Comment by PVince81** [comment]
Hmm, there is actually already a hidden system address book for all local users. It is not exposed anywhere currently.

@DeepDiver1975

**Comment by juliusstoerrle** [comment]
We do have a different solution now, so we don't need this anymore, if you want feel free to close this issue.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
