### ISSUE TITLE
typo in sftp public key 

### ISSUE THREAD

**Issue by revna** [owncloud/core#27228]
in apps/files_external/lib/Controller/AjaxController.php
--> private function generateSshKeys()

$key['publicKey'] = str_replace('phpseclib-generated-key', gethostname(), $key['publickey']);

creates a new array entry "public**K**ey" instead of replace the "publickey" field.
...

**Comment by PVince81** [comment]
PRs welcome

**Comment by PVince81** [comment]
fixed in https://github.com/owncloud/core/issues/27234
