### ISSUE TITLE
Feature Request: printout of status.php output on top when showing Settings/General

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#27231]
### Steps to reproduce
1. Open tab user_name/Settings/General

### Feature Request
On top show the output of status.php, maybe in a nice view

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7

**ownCloud version:** git 10.0

**Comment by mmattel** [comment]
@PVince81 now you have to decide :smiley: 
Seems that @noveens and myself have been working on the same fix at the same time...

**Comment by tomneedham** [comment]
Ahhh nice work @mmattel. I was actually just writing out some pointers for @noveens to help with his PR and move it to more like this style 😉

**Comment by noveens** [comment]
Lol, what are the odds? :p
Nice work, @mmattel :+1:

**Comment by mmattel** [comment]
Closing, fix #27238 was merged
