### ISSUE TITLE
Cannot enable TOTP TwoFactor (Google Authenticator) 

### ISSUE THREAD

**Issue by tdiesler** [owncloud/core#27230]
With a fresh install from owncloud-9.1.4.2, I see

```
Signature could not get checked. Please contact the app developer and check your admin screen.
```
when trying to enable TOTP TwoFactor Version 0.4.1

Happens on EC2 RHEL7 

CrossRef: https://github.com/tdiesler/owncloud/issues/4

**Comment by DeepDiver1975** [comment]
> With a fresh install from owncloud-9.1.4.2, I see

where did you get the app from?

**Comment by kdslkdsaldsal** [comment]
@DeepDiver1975 This broken version is spread via the appstore at https://apps.owncloud.com/ to ownCloud users and won't be fixed by the app developer according to: https://github.com/nextcloud/twofactor_totp/issues/125#issuecomment-274415903

**Comment by tdiesler** [comment]
Renders this [marketing video](https://www.youtube.com/watch?v=x0tZZsefAWw) obsolete

**Comment by DeepDiver1975** [comment]
0.4.2 was just uploaded to fix the certificate problem - closing

**Comment by kdslkdsaldsal** [comment]
^ FYI
@gunph1ld from https://github.com/nextcloud/twofactor_totp/issues/146
@Slowhand93 from https://github.com/nextcloud/twofactor_totp/issues/142
@tribut from https://github.com/nextcloud/twofactor_totp/issues/90
