### ISSUE TITLE
Share Link via Email throws error

### ISSUE THREAD

**Issue by preske87** [owncloud/core#27241]
### Steps to reproduce
1. create a new share
2. select to "share link via mail"
3. click the send-button

### Expected behaviour
An email should be send to the mail in the to-field

### Actual behaviour
an error is thrown

![image](https://cloud.githubusercontent.com/assets/17173636/23292897/17e088c0-fa63-11e6-815b-23f3e1a48f34.png)

### Server configuration
**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.6.30

**ownCloud version:** 9.1.1

**Updated from an older ownCloud or fresh install:** upgraded from older

**Where did you install ownCloud from:** installer

**Signing status (ownCloud 9.0 and above):**

```
Integrity checker has been disabled. Integrity cannot be verified.
```

**List of activated apps:**
```
Enabled:
  - activity: 2.3.2
  - bookmarks: 0.9.0
  - calendar: 1.4.0
  - comments: 0.3.0
  - contacts: 1.4.0.0
  - dav: true
  - documents: 0.13.1
  - federatedfilesharing: true
  - files: 1.5.1
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.3
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - federation
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'ocdzcs74e5d4',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'cloud-prod.leit-werk.org',
    1 => 'cloud.leit-werk.org',
  ),
  'datadirectory' => '/var/www/vhosts/leit-werk.org/cloud.leit-werk.org/ownCloudData',
  'overwrite.cli.url' => 'https://cloud-prod.leit-werk.org',
  'dbtype' => 'mysql',
  'version' => '9.1.1.3',
  'dbname' => 'cloud-prod',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'integrity.checked.disabled' => false,
  'logtimezone' => 'UTC',
  'logfile' => '/var/www/vhosts/leit-werk.org/cloud.leit-werk.org/ownCloudLogs/owncloud.log',
  'forcessl' => true,
  'installed' => true,
  'mail_from_address' => 'xxx@leit-werk.org',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'smtp.leit-werk.org',
  'mail_smtpauth' => true,
  'mail_smtpname' => 'xxx@leit-werk.org',
  'mail_smtppassword' => 'xxxxx',
  'mail_domain' => 'leit-werk.org',
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'loglevel' => 4,
  'trashbin_retention_obligation' => 'auto',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

**Operating system:** macOS

#### ownCloud log (data/owncloud.log)
```
{"reqId":"WK-SvX8AAAEAAFBgQVIAAAAB","remoteAddr":"79.224.147.58","app":"sharing","message":"Can't send mail with public link to preske87@gmail.com: Address in mailbox given [cloud@leit-werk.org@localhost.localdomain] does not comply with RFC 2822, 3.6.2.","level":3,"time":"2017-02-24T06:29:17+00:00","method":"POST","url":"\/index.php\/core\/ajax\/share.php","user":"philipp"}
```

**Comment by hodyroff** [comment]
"[cloud@leit-werk.org@localhost.localdomain] does not comply" obviously your configuration does not yet work. You were never able to send an email this way, or? https://doc.owncloud.org/server/9.1/admin_manual/configuration_server/email_configuration.html
Would also upgrade to 9.1.4

**Comment by preske87** [comment]
Hi,

no, cannot recall ever having received emails.. But the @localhost.localdomain makes somehow sense when using internal mail, but shouldn't it be using smtp with my configuration? Am I missing another config switch?

**Comment by PVince81** [comment]
Did you try with 9.1.4 ?

**Comment by PVince81** [comment]
now you can even try with 9.1.5.

please reopen
