### ISSUE TITLE
Advise about X-Download-Options“-HTTP-Header in Administration

### ISSUE THREAD

**Issue by preske87** [owncloud/core#27242]
### Steps to reproduce
1. Accessing Administration

### Expected behaviour
No warning

### Actual behaviour
Warnings 
```
Der „X-Download-Options“-HTTP-Header ist nicht so konfiguriert, dass er „noopen“ entspricht. Dies ist ein potentielles Sicherheitsrisiko und es wird empfohlen, diese Einstellung zu ändern.
Der „X-Permitted-Cross-Domain-Policies“-HTTP-Header ist nicht so konfiguriert, dass er „none“ entspricht. Dies ist ein potentielles Sicherheitsrisiko und es wird empfohlen, diese Einstellung zu ändern.
```

### Server configuration
**Operating system**: Ubuntu

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 5.6.30

**ownCloud version:** 9.1.1

**Updated from an older ownCloud or fresh install:** upgraded

**Where did you install ownCloud from:** installer

### Server configuration
**Apache Config:**
```
<IfModule mod_headers.c>
	Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
	Header set X-Permitted-Cross-Domain-Policies "none"
	Header set X-Download-Options "noopen"
</IfModule>
```

**nginx.conf**
```
add_header X-Download-Options noopen;
add_header X-Permitted-Cross-Domain-Policies none;
```

### Client configuration
**Browser:** Chrome

**Operating system:** macOS

**Comment by kdslkdsaldsal** [comment]
@preske87 Please note this is a bugtracker for ownCloud. Please close here and jump over to central.owncloud.org (you can login via github there) for support how to configure your webserver.
