### ISSUE TITLE
Updating to 9.1.4 - OC\DB\MigrationException

### ISSUE THREAD

**Issue by alisonw** [owncloud/core#27240]
Updating to 9.1.4 - OC\DB\MigrationException

New install of Owncloud 9.1.4 using existing 9.1.0.15 database and config file. Both web and CLI (sudo -u www-data ./occ upgrade) give this message and a request to report it here.

"OC\DB\MigrationException: An exception occurred while executing 'INSERT INTO `oc_oc_appconfig_vkqr9fqxvklmw` SELECT * FROM `oc_appconfig`': SQLSTATE[HY000]: General error: 1665 Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED."

Environment:
Linux 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 
Apache/2.4.18 (Ubuntu) 
PHP Version 7.0.15-0ubuntu0.16.04.2
(mysql)  Ver 15.1 Distrib 10.1.21-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - dav: 0.2.5
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - configreport
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

{
    "system": {
        "instanceid": "oc22iu1918dt",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
==REMOVED SENSITIVE VALUE==
        ],
        "datadirectory": "\/store1\/CLOUD",
        "overwrite.cli.url": "https:\/\/zz1.uk:8000",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud9",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "theme": ""
    }

Not using LDAP.

MariaDB [owncloud]> SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';
Empty set (0.02 sec)

owncloud.log is empty

**Comment by alisonw** [comment]
(Probably needless to say, but this is a show-stopper as clients nor web interface can access stored data)

**Comment by kdslkdsaldsal** [comment]
@alisonw 
> Cannot execute statement: impossible to write to binary log since BINLOG_FORMAT = STATEMENT and at least one table uses a storage engine limited to row-based logging. InnoDB is limited to row-logging when transaction isolation level is READ COMMITTED or READ UNCOMMITTED."

See the documentation available here:

https://doc.owncloud.org/server/latest/admin_manual/maintenance/upgrade.html#troubleshooting
https://doc.owncloud.org/server/latest/admin_manual/installation/source_installation.html#binlog-format-statement
https://doc.owncloud.org/server/latest/admin_manual/configuration_database/linux_database_configuration.html#mysql-mariadb-with-binary-logging-enabled

**Comment by alisonw** [comment]
Many thanks  @kdslkdsaldsal - I did try a search here first but didn't come up with anything which seemed relevant and when the web update errored it requested I report it, so did.

For others who may come across this, add to your /etc/mysql/my,cnf
    binlog-format           = MIXED
and restart.
