### ISSUE TITLE
Default favicon shown even using a customized theme

### ISSUE THREAD

**Issue by MariusTimmer** [owncloud/core#27288]
### Steps to reproduce
1. Install a owncloud instance (9.0.8)
2. Install a customized theme (including a favicon)
2. Goto the login
3. The default favicon is shown

### Expected behaviour
The favicon from the theming should be shown.

### Actual behaviour
The default favicon is shown.

### Server configuration
**Operating system**: CentOS

**Web server:** Apache

**Database:** MySQL

**PHP version:**

**ownCloud version:** 9.0.8

**Updated from an older ownCloud or fresh install:** Update

**Where did you install ownCloud from:** Subversion

**List of activated apps:** none

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox, Chrome

**Operating system:** Windows 7, Ubuntu 16.04, OS X El Capitan

**Comment by phisch** [comment]
Closed because all PR's have been merged
