### ISSUE TITLE
Do not show a full screen error when 'Allow users to mount external storage' is disabled and we try to configure a mount via Files view

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27285]
### Steps to reproduce

1.  As admin user, configure a oC server with 'Allow users to mount external storage' disabled (personal mounts)
2. As regular user click in files view in External Storage section
3. Click on 'You can add external storages in the personal settings' link

### Expected behaviour

A warning should be should or the link should not be visible

### Actual behaviour

An error is shown full screen (see gif below)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.0"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**

 Mozilla

![errormext](https://cloud.githubusercontent.com/assets/10596560/23460799/6d09625e-fe87-11e6-8c4d-45cb18b58db6.gif)

**Comment by PVince81** [comment]
Is the link correct ? It should point to the new settings section that says "Admin disable ext storage".

That is, after https://github.com/owncloud/core/pull/27196 is merged
