### ISSUE TITLE
Rows are not updated after sharing via web ui.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#27294]
### Steps to reproduce:

1. Share a file or folder using web ui. 

### Expected behaviour

The word Shared appears on the row.

### Actual behaviour

It doesn't update the row.

![shared_problem](https://cloud.githubusercontent.com/assets/9048796/23501839/cf46ebae-ff35-11e6-92f3-fa7451a36fc5.gif)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
Current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.0.1","versionstring":"10.0.0","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```


```
### Client configuration

Chrome

**Comment by noveens** [comment]
Addition:

Refresh the page after enabling the share option.
When removing the share option ( via GUI ), 
The text "Shared" in the row doesn't go away + icon doesn't change.

**Comment by individual-it** [comment]
The second part of the problem (removing share does not update icon+text) seemed to have started with this commit https://github.com/owncloud/core/commit/7e463bfb5fd86b02bb2e5130b61affa460c7c3f0

Cannot find a version where the word Shared appears on the row when sharing. Went back till 9.2

**Comment by individual-it** [comment]
@PVince81 is this a duplicate of #25311 ?

**Comment by SergioBertolinSG** [comment]
Yes, it is a duplicate. Closing.

**Comment by SergioBertolinSG** [comment]
Being fixed here https://github.com/owncloud/core/pull/25838
