### ISSUE TITLE
Suggestion limited on firstname

### ISSUE THREAD

**Issue by sif77** [owncloud/core#27309]
In the text input "Share with users and groups", the suggestion seems to be limited on firstname. What is the way to allow full name suggestion ?

**Comment by kdslkdsaldsal** [comment]
Most likely answered in https://github.com/owncloud/core/issues/26781#issuecomment-269330776.

For further questions (e.g. if its not a bug) please use https://central.owncloud.org/

**Comment by PVince81** [comment]
If a bug, please reopen and use the issue template https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md
