### ISSUE TITLE
Auth - Session

### ISSUE THREAD

**Issue by patrikx3** [owncloud/core#27313]
It is a simple question.
I am using the users_ldap component.
What is weird is that when I refresh a page or click multiple times on the web page I can see on my server it generates a new LDAP/Samba Auth.

Which is weird. It doesn't need to use any other user backend once we are in an authed session.
I was thinking that once the user is in the session, it is not hitting the auth backend, 
but it is not. every time http request, it also generates a new auth backend.

So then why do we use the session?

right now with users_ldap / samba it is very high cpu usage and it is weird why it hits the auth backend every time a new request is generated when it is in the session already,

**Comment by PVince81** [comment]
@jvillafanez can you explain why the LDAP session is not kept/stored in a PHP session ?

**Comment by patrikx3** [comment]
when i click multiple times on the web, it hits samba every times (via the ldap component)

when i use the admin which does not use ldap in owncloud/nextcloud, it does not hit samba
it should use ldap only when i login, still it constant does auth.

not using *cloud:
![image](https://cloud.githubusercontent.com/assets/4770180/23606370/b383350c-0260-11e7-8b27-72f49f9718a1.png)

i use owncloud for its own admin user (root) - multiple refreshes, not using samba at all
![image](https://cloud.githubusercontent.com/assets/4770180/23606793/9066c974-0262-11e7-9042-964e31de757d.png)

i use ldap backend user (patrikx3) - it uses samba with high cpu usage
![image](https://cloud.githubusercontent.com/assets/4770180/23606708/34887738-0262-11e7-8560-cf44521c40fc.png)

**Comment by patrikx3** [comment]
it should not hit samba zero %

**Comment by DeepDiver1975** [comment]
@patrikx3 this owncloud version are you running?

**Comment by patrikx3** [comment]
sorry i moved to nextcloud, they said it was the bettter.
but i useed the latest version from debian yesterday, but the error though it is the same, 

should i only quest from nextcloud then? i  think it is the same core code.

**Comment by patrikx3** [comment]
or is it the users_ldap component is wrong?

**Comment by patrikx3** [comment]
but i think it is a session error, because the ldap should not be used after the session is working and auth is done right?

**Comment by DeepDiver1975** [comment]
> sorry i moved to nextcloud, they said it was the bettter.

haha - and DropBox say they have the better file sync - right?

If you use ownCloud you are happily welcome here to get help in analysing your issues.
In any other case .....

**Comment by patrikx3** [comment]
ok i revert to owncloud and i send you the same issue ok?

**Comment by PVince81** [comment]
user has left Github (ghost), no further info will be provided for the issue -> close
