### ISSUE TITLE
Creating a new app password, trashbin icon does not appear

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27311]
### Steps to reproduce

1. Go to setting menu
2. In Personal section, go to Security menu
3. Create a new app password

### Expected behaviour

A trashbin icon should appear in order to let us delete the new password

### Actual behaviour

it is needed to refresh the browser in order to make the trashbin icon appear.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.6.

**ownCloud version:**

"version":"10.0.0.0"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**

 Mozilla

![screen shot 2017-03-06 at 10 08 38](https://cloud.githubusercontent.com/assets/10596560/23603355/29801a7e-0255-11e7-8601-78651f60a6f5.png)

@tomneedham

**Comment by VicDeo** [comment]
@davitol the fix is merged.

**Comment by davitol** [comment]
Checked and works. Thx for the info @VicDeo
