### ISSUE TITLE
App provided sections with translations and icons?

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#27327]
Discussion issue.

With the changes to how settings panels are registered in 10.0 it is currently not possible for an app to self-register a settings 'Section' (left hand grouping) themselves. This was partly  by design (to encourage sensible grouping and not just a free-for-all lets-go-crazy situation) and partly to reduce the scope of the massive PR that was required to merge in the changes. 

My hope was we could create a sensible collection of sections registered in core, with appropriate translations (https://github.com/owncloud/core/blob/master/lib/private/Settings/SettingsManager.php#L195) and icons. The SettingsManager only shows sections which actually contain panels and the rest are hidden. 

Question: Do we still want to allow apps to register their own panels, or can we come up with a set of internal sections that meet the requirements?

Adding a section to core currently involves adding one line to the SettingsManager class and a line in the core.css to provide the correct icon file. Personally, I think directing apps into predefined sections will result in a much better UI/UX for users, but we need to ensure we have a nice collection of sections to catch the panels.

Current list:

Personal

| SectionID | Description | Icon
| --- | --- | --- |
| general | Generic user settings like profile / avatar | person/user |
| storage | Quota, mounts, file handling | folder |
| security | App passwords, two factor... | padlock |
| encryption | Encryption settings | padlock |
| additional | Legacy apps / misc | dots |

Admin

| SectionID | Description | Icon
| --- | --- | --- |
| general | General admin settings / tips / info | cog |
| storage | Mounting settings, file handling, upload | folder |
| security | Security tips | padlock |
| authentication | User backends | padlock |
| encryption | Encryption settings / status | padlock |
| sharing | Sharing settings | share |
| monitoring | Logs / monitoring info | search |
| apps | App management  | list |
| updates | Update management | update |
| additional | Legacy apps / misc | dots |

@PVince81 @DeepDiver1975

**Comment by PVince81** [comment]
Some sections require an independent section and cannot easily share sections with other sections because it would break the UX.

See customgroups example:
![Custom Groups](https://cloud.owncloud.com/index.php/s/oXqsdsoDtkiF0DF/download)

Another example is the apps list.

If we would try having this crammed into a subsection, it means the scrolling panel would need to have a fixed height and it would feel weird to manage apps/groups within a very small container.

**Comment by DeepDiver1975** [comment]
> Question: Do we still want to allow apps to register their own panels, or can we come up with a set of internal sections that meet the requirements?

any app can register panels and sections

**Comment by tomneedham** [comment]
> any app can register panels and sections

Yes, but at the moment we just uppercase the id and give it a generic cog icon: https://github.com/owncloud/core/blob/master/lib/private/Settings/SettingsManager.php#L406. Translation isn't supported properly here.

**Comment by PVince81** [comment]
We need a proper solution.

@pmaier1 @felixheidecke from a design perspective, do you agree that apps should be able to add panels in the settings page ? I think not all apps can fit in existing ones.

For example custom groups doesn't fit into "Authentication" where LDAP goes. So it needs its own section, with a name that can be translated.

Setting to 10.0.1

**Comment by tomneedham** [comment]
This is fixed/implemented here: https://github.com/owncloud/core/pull/27634 just need to add a couple of tests when I get some time hopefully this weekend

**Comment by tomneedham** [comment]
https://github.com/owncloud/core/pull/27634 is merged
