### ISSUE TITLE
Owncloud 9.1.4 SMTP error

### ISSUE THREAD

**Issue by janarzz** [owncloud/core#27325]
Hei,
after owncloud upgrade 9.1.2 to 9.1.4 not working SMTP
I give this error: 
A problem occurred while sending the email. Please revise your settings. (Error: Failed to authenticate on SMTP server with username "cuser@email.com" using 0 possible authenticators)

Any solution ?

I use:
Ubuntu server 16.04.2
PHP version 5.6
Apache 2.4.25

**Comment by arlenn** [comment]
Also experiencing this error with 9.1.4 and Gmail SMTP.

Raspbian-Jessie
PHP 5.6
Nginx 1.6.2

**Comment by janarzz** [comment]
Hey, when this bug fixed ?

**Comment by PVince81** [comment]
Please try again with 10.0.4. If the problem persists, please reopen and use the issue template: https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md
