### ISSUE TITLE
Adjust Makefile to run selenium tests locally

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27336]
@individual-it @SergioBertolinSG @DeepDiver1975 is that even possible or requires saucelab ?

I'd like to have a command `make tests-selenium` that sets it up locally and runs the tests for development purposes.

**Comment by SergioBertolinSG** [comment]
That can only run in an environment with graphic interface, chrome, chrome webdriver installed. Run java -jar selenium-server-standalone-3.1.0.jar -port 4445 and have the environment variables required correctly set.

**Comment by SergioBertolinSG** [comment]
It would be nice if a headless webdriver can do the same and pass the tests correctly.

**Comment by individual-it** [comment]
I think a headless webdriver would do what we want. The whole idea is to test the app in a real browser the same way a user would do.
Could the make file test if a GUI is available if yes download the chrome driver, selenium and then run it as described here: https://github.com/owncloud/core/pull/27316 in "run tests locally"?

**Comment by PVince81** [comment]
might be possible, yes.

else for headless mode it is also possible to spawn a virtual X server

**Comment by PVince81** [comment]
from our discussions, we're not going to do that
