### ISSUE TITLE
Selenium test run failures on PR

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27354]
For example see: https://travis-ci.org/owncloud/core/jobs/209472858

```
bash: apps/dav/tests/travis/selenium/install.sh: No such file or directory
```

@individual-it @DeepDiver1975

**Comment by individual-it** [comment]
What is special about the DAV tests? Why are the extra script running for it?
If we don't need them for the selenium tests, then we could just disable them for the selenium test case.

`sh -c "if [ '$TEST_DAV' = '1' ] && [ '$TC' != 'selenium' ]; then bash apps/dav/tests/travis/$TC/install.sh; fi"`

**Comment by DeepDiver1975** [comment]
let me try to fix this ....

**Comment by DeepDiver1975** [comment]
okay - I have more pressing stuf to take care of - anybody is welcome to have a look into this

**Comment by DeepDiver1975** [comment]
sorry

**Comment by individual-it** [comment]
Is there actually a reason why travis is limited to only 1 concurrent job?

**Comment by DeepDiver1975** [comment]
> Is there actually a reason why travis is limited to only 1 concurrent job?

not really - default setting?
