### ISSUE TITLE
make for first time setup reports one warning and one error

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#27355]
### Steps to reproduce
1. clone core
2. run make, or make clean and make

### Expected behaviour
No errors / warnings 

### Actual behaviour
One error, one warning
make does not finish successfully

### Server configuration
**Operating system**: Ubuntu 16.04

**nodejs, bower**
Installed according: https://github.com/owncloud/documentation/issues/2886
```
nodejs –v
v7.7.2

npm –v
4.1.2

bower -v
1.8.0
```

**PHP version:** 7.0

**ownCloud version:** 10, git clone

**make result**

```
/usr/bin/npm install --prefix build
npm WARN prefer global marked@0.3.6 should be installed with -g

> phantomjs-prebuilt@2.1.14 install /var/www/owncloud/core/build/node_modules/phantomjs-prebuilt
> node install.js

module.js:472
    throw err;
    ^

Error: Cannot find module '/var/www/owncloud/core/build/node_modules/phantomjs-prebuilt/install.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3
```

**Comment by PVince81** [comment]
like old / outdated. please try again with recent version
