### ISSUE TITLE
Many pop-ups show if keep clicking wrongly mounted external storage

### ISSUE THREAD

**Issue by noveens** [owncloud/core#27357]
### Steps to reproduce
1. Wrongly mount an external storage of your choice ( I chose Local )
2. Go to file list, the wrongly mounted folder must be in red, keep clicking on it

### ScreenShots
![a](https://cloud.githubusercontent.com/assets/23054294/23793772/ee09f026-05b2-11e7-8687-b69c46fd1867.gif)

### Expected behaviour
Only one pop-up should show

### Actual behaviour
Many pop-ups appear

### Server configuration
**Operating system**:
Ubuntu 16.10

**Web server:**
Apache

**Database:**
Sqlite

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
10.0.0.1

**Updated from an older ownCloud or fresh install:**
fresh

**Where did you install ownCloud from:**
GitHub

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.2.8
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - example-theme
  - testing
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "ocopyznqq7cy",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/var\/www\/core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/core",
        "dbtype": "sqlite3",
        "version": "10.0.0.1",
        "logtimezone": "UTC",
        "installed": true,
        "dbname": "owncloud",
        "dbhost": "localhost:5432",
        "dbtableprefix": "oc_"
    }
}
```

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

### Client configuration
**Browser:**
Google Chrome Stable

**Operating system:**
ubuntu 16.10

#### Web server error log
```
Not Necessary
```

#### ownCloud log (data/owncloud.log)
```
Not Necessary
```

#### Browser log
```
Not Necessary
```

@PVince81 @tomneedham @owncloud/design

**Comment by noveens** [comment]
IMHO, 
we should not allow any other user input until one input is given to the alert box.

@PVince81 opinions?

**Comment by phisch** [comment]
Indeed, a popup should overlay over the whole screen preventing any more userinput.
Also i think a popup should be something that requires immediate user interaction (like "sure you want to delete..."). Since this message does not require immediate user interaction, it should be a notification (one of the messages that pop up at the top of the screen). We could also provide different levels of notifications like `notification`, `warning` and `error`.

I haven't looked into the js code that is responsible for popups, but do we have a centralized queue implementation there?

**Comment by PVince81** [comment]
Check the code, someone probably forgot to pass `true` for the "modal" argument.
