### ISSUE TITLE
Suggestion : keyboard shortcuts to select multiple files in files list

### ISSUE THREAD

**Issue by noveens** [owncloud/core#27359]
Suggestion :

We should try to to introduce atleast few shortcuts for selection ( SHIFT plus UP/DOWN ), deletion ( DEL to delete ).

Any additions are welcome.

@PVince81 @owncloud/design @DeepDiver1975

**Comment by PVince81** [comment]
Note that there is already some old code related to keyboard but it's broken, so first step would be to fix them: https://github.com/owncloud/core/issues/19442 and https://github.com/owncloud/core/issues/9740

**Comment by noveens** [comment]
@PVince81 ,
Will look into both the issues, thanks for the start :-)

**Comment by PVince81** [comment]
Closing in favor of general files app keyboard issue ticket: https://github.com/owncloud/core/issues/27580
