### ISSUE TITLE
[10.0] Request an app password from the web UI link on the desktop client login now points to the wrong location

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/core#27360]
When pointing to an ownCloud 10.0 with the desktop client and prompted with the login, the `click here to request an app password from the web interface` link is not redirected to the new `Settings > Personal > Security` section (where the form to request a new application password is located now).

#### Old link was:

`https://[SERVER]/index.php/settings/personal?#apppasswords` that would need to be redirected to...

#### the new link:

`https://[SERVER]/index.php/settings/personal?sectionid=security` (maybe also with section selector like the first one: `#apppasswords` in case that settings page grows and needs scrolling to be found)

Eventually, @owncloud/desktop-developers would need to adjust this hardcoded value: https://github.com/owncloud/client/blob/master/src/gui/creds/httpcredentialsgui.cpp#L78-L79

**Comment by ckamm** [comment]
@tomneedham @SamuAlfageme So if the server version is >= 10.0, the client should use the new `?sectionid=security#apppasswords` url?

**Comment by tomneedham** [comment]
the url is now `/index.php/settings/personal?sectionid=security#apppasswords` but we could add a route in here to handle backwards compatibility @DeepDiver1975 ??

**Comment by ckamm** [comment]
@tomneedham  That'd be good, we can switch to the new url in 2.3.1, probably.
