### ISSUE TITLE
Cannot upload files with ".properties" extension with foldersync

### ISSUE THREAD

**Issue by xaviermiller** [owncloud/core#27368]
Hi,

With owncloud 9.1.4, I cannot upload Titanium Backup .properties files with foldersync (lite).
It was OK until 9.1.3

### Steps to reproduce
1. Create a file with .properties extension on your android device
2. Try to sync with foldersync (lite)
3. Error : "Malformed content type: |"

### Expected behaviour
Be able to sync files with .properties extension using foldersync (lite) again

### Actual behaviour
cannot upload files with .properties extension using foldersync (lite)

### Server configuration
**Operating system**: Gentoo Linux (Portage 2.3.4 (python 2.7.13-final-0, default/linux/amd64/13.0/no-multilib, gcc-5.4.0, glibc-2.24-r1, 4.10.2-gentoo x86_64))

**Web server:** nginx 1.11.10

**Database:** sqlite 3.17

**PHP version:** php-fpm 7.0.16

**ownCloud version:** 9.1.4

**Updated from an older ownCloud or fresh install:** updated from 8, 9, ... (2 years old installation)

**Where did you install ownCloud from:** Gentoo Linux (emerge owncloud)

**Signing status (ownCloud 9.0 and above):**

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- .webapp-owncloud-9.1.3

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.webapp-owncloud-9.1.3] => Array
                        (
                            [expected] => 
                            [current] => 
                        )

                )

        )

)
```

**List of activated apps:**
Files, Contacts, Calendar

**The content of config/config.php:**
NO

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
internal webdav (sabre)

### Client configuration
**Browser:**
using foldersync lite app
**Operating system:**
android 7.1.1 (LineageOS 14.1)

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"g1Fgsg2fut9c\/DOeYA82","remoteAddr":"192.168.178.35","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name TitaniumBackup\\\/android.ext.shared-20170310-010038.properties could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(903): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('TitaniumBackup\\\/...')\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(334): Sabre\\\\DAV\\\\Server->getPropertiesForPath('TitaniumBackup\\\/...', Array, 0)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/localh...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":170,\"User\":\"xavier-mobile\"}","level":0,"time":"2017-03-12T20:31:34+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/TitaniumBackup\/android.ext.shared-20170310-010038.properties","user":"xavier-mobile"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by xaviermiller** [comment]
I don't know if this helps, but the problem is also reported for nextcloud: https://github.com/nextcloud/server/issues/3792

**Comment by PVince81** [comment]
Are you able to inspect the traffic ? If there is an issue with content-type header it could either be the request or response content type. Would be good to have a look.

Could also be a bug in foldersync.

**Comment by xaviermiller** [comment]
Hi!

I can upload a .proterties file with curl without any problem. So the problem seems to be at the side of foldersync.

I will open a bug there.

**Comment by PVince81** [comment]
Thanks, closing then

**Comment by WladyX** [comment]
Can you pls give the link to the bug opened for foldersync?
Sorry for spamming.

**Comment by xaviermiller** [comment]
Hi! I sent a mail but I didn't receive any feedback.

**Comment by kdslkdsaldsal** [comment]
> updated to server 10.0.1 this morning, some time later also foldersync got updated and now it seems to work :slight_smile: not sure which of the two updates fixed the issue.

-> https://central.owncloud.org/t/cannot-upload-files-with-properties-extension-with-foldersync/7826/3
