### ISSUE TITLE
9.1.4 Upgrade invalid file list does not show list

### ISSUE THREAD

**Issue by LeeLammert** [owncloud/core#27367]
### Steps to reproduce
1.  Upgrade to 9.1.4 via package manager
2.  Complete maintenance cycle
3.  Login via webUI and view list of invalid files

### Expected behaviour
Show a list of files that need to be deleted.

### Actual behaviour
The link shows one file at a time!!! Must use "Rescan" for each individual file.

### Server configuration
**Operating system**:
OpenSuSE 13.2

**Web server:**
Apache /home/lvl/ownCloud/[NAVVF] BOD/BOD Archives/Reunions/Reunion Sample Documents.zip

**Database:**
mariadb 10.0.27-2.27.1

**PHP version:**
5.6.1

**ownCloud version:** (see ownCloud admin page)
9.1.4-2.1

**Updated from an older ownCloud or fresh install:**
Updated from previous version

**Where did you install ownCloud from:**
http://download.owncloud.org/download/repositories/9.1/openSUSE_13.2

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system

The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/e
n/book.pcntl.php
{
    "system": {
        "instanceid": "ocv9r6b3bpn5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.omnitec.net"
        ],
        "datadirectory": "\/u\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/oc.omnitec.net",
        "dbtype": "mysql",
        "version": "9.1.4.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 0,
        "updatechecker": false,
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

```

### Client configuration
**Browser:**
Firefox 50.1.0

**Operating system:**
OpenSuSE 13.2

### Logs
#### Web server error log
n/a
```
Insert your webserver log here
n/a
```

#### ownCloud log (data/owncloud.log)
n/a
```
Insert your ownCloud log here
n/a
```

**Comment by PVince81** [comment]
if you installed from the official distro packages, there shouldn't be any invalid files in the integrity check, if that's what you meant.

If not, please expand the steps to explain where exactly you went and what you clicked.

**Comment by PVince81** [comment]
Closing due to lack of feedback
