### ISSUE TITLE
Delete of file not possible - Duplicate entry for key 'fs_storage_path_hash'

### ISSUE THREAD

**Issue by michaelof** [owncloud/core#27369]
### Steps to reproduce
- unfortunately NOT reproducible.
Steps:
1. add  file(s) via drag and drop top browser
2. make local changes to file(s)
3. add  again same file(s) via drag and drop top browser
4. try to delete file(s)

### Expected behaviour
file(s) should be deleted

### Actual behaviour
got a yellow error message on top ( "error while deleting ....")
owncloud log  appended below.
trying again to delete file(s) now results indifferent error "file(s) are locked ..."

### Server configuration
**Operating system**:
OpenSuse 42.2
**Web server:**
Apache 2.4.23
**Database:**
MariaDB 10.0.29
**PHP version:**
5.5.14
**ownCloud version:** (see ownCloud admin page)
9.1.4 (stable)
**Updated from an older ownCloud or fresh install:**
updated, not sure about starting point, I believe 8.something
**Where did you install ownCloud from:**
OpenSuse packages on http://download.owncloud.org/download/repositories/stable/openSUSE_Leap_42.2
**Signing status (ownCloud 9.0 and above):**
"No errors have been found."

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.1
  - dav: 0.2.7
  - encryption: 1.3.0
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.4
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
**The content of config/config.php:**
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocv90mja2d89",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:10080",
            "owncloud.domain.tld"
        ],
        "datadirectory": "\/srv\/www\/htdocs\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost:10080\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.4.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_smtpsecure": "tls",
        "mail_from_address": "owncloud",
        "mail_domain": "domain.tld",
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "theme": "",
        "loglevel": 0
    }
}
**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
yes, webdav
### Client configuration
**Browser:**
several, mainly Firefox. on OpenSuse and Android
**Operating system:**
OpenSuse, Android, iOS, WIN..., ...

#### Web server error log
no relevant errors in apache's log

#### ownCloud log (data/owncloud.log)
Exception: {"Message":"An exception occurred while executing 'UPDATE `oc_filecache` SET `storage` = ?, `path` = ?, `path_hash` = ?, `name` = ?, `parent` =? WHERE `fileid` = ?' with params [\"1\", \"files_encryption\\\/keys\\\/files_trashbin\\\/files\\\/<FILENAME>.d1489350583\", \"21c74ade176a765731b6b68b697b3859\", \"<FILENAME>.d1489350583\", 1274, 925]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-21c74ade176a765731b6b68b697b3859' for key 'fs_storage_path_hash'","Exception":"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","Code":0,"Trace":"#0 \/srv\/www\/htdocs\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/srv\/www\/htdocs\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(836): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'UPDATE `oc_file...', Array)\n#2 \/srv\/www\/htdocs\/owncloud\/lib\/private\/DB\/Connection.php(188): Doctrine\\DBAL\\Connection->executeQuery('UPDATE `oc_file...', Array, Array, NULL)\n#3 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/Cache\/Cache.php(524): OC\\DB\\Connection->executeQuery('UPDATE `*PREFIX...', Array)\n#4 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/Cache\/Cache.php(474): OC\\Files\\Cache\\Cache->moveFromCache(Object(OC\\Files\\Cache\\HomeCache), 'files_encryptio...', 'files_encryptio...')\n#5 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/Cache\/Updater.php(195): OC\\Files\\Cache\\Cache->move('files_encryptio...', 'files_encryptio...')\n#6 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/View.php(326): OC\\Files\\Cache\\Updater->renameFromStorage(Object(OCA\\Files_Trashbin\\Storage), 'files_encryptio...', 'files_encryptio...')\n#7 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/View.php(799): OC\\Files\\View->renameUpdate(Object(OCA\\Files_Trashbin\\Storage), Object(OCA\\Files_Trashbin\\Storage), 'files_encryptio...', 'files_encryptio...')\n#8 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Encryption\/Keys\/Storage.php(283): OC\\Files\\View->rename('\/<USER>....', '\/<USER>....')\n#9 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php(279): OC\\Encryption\\Keys\\Storage->renameKeys('\/<USER>....', '\/<USER>....')\n#10 \/srv\/www\/htdocs\/owncloud\/apps\/files_trashbin\/lib\/Storage.php(78): OC\\Files\\Storage\\Wrapper\\Encryption->rename('files\/Documents...', 'files_trashbin\/...')\n#11 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(561): OCA\\Files_Trashbin\\Storage->rename('files\/Documents...', 'files_trashbin\/...')\n#12 \/srv\/www\/htdocs\/owncloud\/apps\/files_trashbin\/lib\/Trashbin.php(246): OC\\Files\\Storage\\Wrapper\\Wrapper->moveFromStorage(Object(OCA\\Files_Trashbin\\Storage), 'files\/Documents...', 'files_trashbin\/...')\n#13 \/srv\/www\/htdocs\/owncloud\/apps\/files_trashbin\/lib\/Storage.php(160): OCA\\Files_Trashbin\\Trashbin::move2trash('Documents\/<PATH>l...')\n#14 \/srv\/www\/htdocs\/owncloud\/apps\/files_trashbin\/lib\/Storage.php(95): OCA\\Files_Trashbin\\Storage->doDelete('files\/Documents...', 'unlink')\n#15 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/View.php(1119): OCA\\Files_Trashbin\\Storage->unlink('files\/Documents...')\n#16 \/srv\/www\/htdocs\/owncloud\/lib\/private\/Files\/View.php(690): OC\\Files\\View->basicOperation('unlink', '\/Documents\/<PATH>...', Array)\n#17 \/srv\/www\/htdocs\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php(333): OC\\Files\\View->unlink('\/Documents\/<PATH>...')\n#18 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(179): OCA\\DAV\\Connector\\Sabre\\File->delete()\n#19 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(285): Sabre\\DAV\\Tree->delete('Documents\/<PATH>l...')\n#20 [internal function]: Sabre\\DAV\\CorePlugin->httpDelete(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#21 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#22 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:DELETE', Array)\n#23 \/srv\/www\/htdocs\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#24 \/srv\/www\/htdocs\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(57): Sabre\\DAV\\Server->exec()\n#25 \/srv\/www\/htdocs\/owncloud\/remote.php(164): require_once('\/srv\/www\/htdocs...')\n#26 {main}","File":"\/srv\/www\/htdocs\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":66,"User":"<USER>"}

#### Browser log
no relevant log in Browser log

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/issues/22563

known issue that happen randomly, difficult to catch
