### ISSUE TITLE
Download links 8.0.0 broken

### ISSUE THREAD

**Issue by nibbsification** [owncloud/core#27366]
Hello community,

could please help me someone where to get the owncloud server release 8.0.0 as I need to upgrade from 7.0.15 on an hosted instance.

Thank you very much.

**Comment by tomneedham** [comment]
Tracked here: https://github.com/owncloud/owncloud.org/issues/1153

**Comment by tomneedham** [comment]
You can also use https://github.com/owncloud/core/releases/tag/v8.0.0 in the mean time

**Comment by kdslkdsaldsal** [comment]
@nibbsification 
> the owncloud server release 8.0.0 as I need to upgrade from 7.0.15 on an hosted instance.

You don't need 8.0.0 to do such an upgrade. The correct upgrade would be 7.0.15 -> 8.0.16 (not 8.0.0) and 8.0.16 is available / works at https://owncloud.org/changelog/#latest8.0

**Comment by nibbsification** [comment]
Thank you very much for your input lads. I will try that.
