### ISSUE TITLE
Automatic Login and direct access to the Files page.

### ISSUE THREAD

**Issue by sugunaSubramanian** [owncloud/core#27379]
We have a front end which does the double authentication. The Front end is written in jsp. The username and password passed to this front end would be the username and password for the owncloud. I would like to automatically login without navigating through the login page, may be, by calling a script which takes me to the Files/ Applications page directly. How to achieve the same.

**Comment by kdslkdsaldsal** [comment]
@sugunaSubramanian Please note this is a bugtracker for ownCloud. If you have questions how to implement something then please close here and ask your question at https://central.owncloud.org/ (you can login with your github account there).
