### ISSUE TITLE
Update issue 9.0.8

### ISSUE THREAD

**Issue by micha0808** [owncloud/core#27393]
Update issue 9.0.8
Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'CREATE TABLE `oc_mounts` (`id` INT AUTO_INCREMENT NOT NULL, `storage_id` INT NOT NULL, `root_id` INT NOT NULL, `user_id` VARCHAR(64) NOT NULL, `mount_point` VARCHAR(4000) NOT NULL, INDEX mounts_user_index (`user_id`), INDEX mounts_storage_index (`storage_id`), INDEX mounts_root_index (`root_id`), UNIQUE INDEX mounts_user_root_index (`user_id`, `root_id`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB' at line 1

**Comment by kdslkdsaldsal** [comment]
@micha0808 Please fill out the issue template shown when creating a new issue. This is asking you various mandatory info about your environment and isn't shown just for fun.

**Comment by kdslkdsaldsal** [comment]
@micha0808 Ping? Bugreports without providing the asked information (fire and forget like) are pretty useless: They are just filling up this issue tracker and causing work to people (like me or others reading this).
