### ISSUE TITLE
TOTP Enhancement

### ISSUE THREAD

**Issue by stkjj** [owncloud/core#27399]
Comprehensive description

[Concept] MFA Authentication with TOTP-QR, eMail Fallback and Backup Verification Code

not only for user, but also admin - possible, because of fallback solutions
configurable which method is primary
validation for first use not at login, but direct after shooting QR-Code
eMail fallback like: https://github.com/pluginkollektiv/2-Step-Verification
warning message when QR-Code is taken, that no one else is taking it (hey, it's the master-key, that could be compromised in this stage!)

![5153aa86-eb01-11e6-9c4a-0a76e2b8ed0b](https://cloud.githubusercontent.com/assets/832642/23994523/936f97d2-0a45-11e7-9914-3f4a557b4fea.jpg)
![512546aa-eb01-11e6-8b70-0fb9927fe3bb](https://cloud.githubusercontent.com/assets/832642/23994524/93942976-0a45-11e7-9524-b4acf2467250.jpg)
![51578566-eb01-11e6-82e9-64ae473549f2](https://cloud.githubusercontent.com/assets/832642/23994525/93986068-0a45-11e7-9cd8-e91130e975db.jpg)

**Comment by karakayasemi** [comment]
I added validation for first use at settings for one of the determined enhancement. Please review.
https://github.com/owncloud/twofactor_totp/pull/5

**Comment by karakayasemi** [comment]
Could you please review first working version of two-factor backup codes app.
karakayasemi/twofactor_backup_codes#1
