### ISSUE TITLE
Reorder the elements of the log entries to make the logs easier to read

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#27397]
This is a current log entry:
```
{"reqId":"Q71WK4Sp6B03QqpOoxit","remoteAddr":"173.18.243.1","app":"core","message":"Generating preview for \"\/xxxx\/yyyy\/zzzz\/0000.txt\" with \"OC\\Preview\\TXT\"","level":0,"time":"2017-03-13T09:15:10-07:00","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fxxxx%2Fyyyyy%2Fzzzzz%2F0000.txt&c=589c9d17172bc&x=32&y=32&forceIcon=0","user":"mbs"}
```

The new log entry should look like the following:
```
{"reqId":"Q71WK4Sp6B03QqpOoxit","level":0,"time":"2017-03-13T09:15:10-07:00","remoteAddr":"173.18.243.1","user":"mbs","app":"core","method":"GET","url":"\/index.php\/core\/preview.png?file=%2Fxxxxx%2Fyyyyy%2Fzzzz%2F0000.txt&c=589c9d17172bc&x=32&y=32&forceIcon=0","message":"Generating preview for \"\/xxxxx\/yyyyy\/zzzz\/0000.txt\" with \"OC\\Preview\\TXT\""}
```

As an additional change, the reqId should replace the `/` to any other alphanumeric character ( @DeepDiver1975 @PVince81  , this extra change should be harmless)

#### Reasons for this change

* The reqId should have a fixed length, so the vision isn't shifted. Right now this isn't always happening due to `/` being escaped. The intention is that this char doesn't appear so we don't need to escape.
* Log level and time should already be fixed length, so we just need to move them to the beginning of the string. The reason is the same as the previous point.
* The next elements are the remoteAddr, user and app. The remoteAddr should be the first of the bunch because it's the more "stable": length should be between 11, 13, and 15 chars, but the length difference should be minimum. The user is usually associated with an ip (obviously not always true), so it's better to keep them side by side. Finally, the app is the last of the bunch because while we can't assume any length, but it shouldn't grow like crazy.
* The method and url should also be side by side, being the method the first because we can't assume anything about the url.
* The message should be always the last.

#### Important note

The format of each entry will still be generated using json. This can't be changed because there could be apps relying on this format.

**Comment by mmattel** [comment]
I like the idea.
Q: would this impact the output when using owncloud log in rsyslog format?
If yes how?

**Comment by jvillafanez** [comment]
I don't think it will affect. The log handler is different so this will only apply to ownCloud logger.

**Comment by viraj96** [comment]
I guess the reqId comes from `getID()` function in `Request.php`. But there it seems to generate a random sequence of 20 characters. So all we need to do is, check if the reqID consists of `/` and if it does, recreate the reqID?

**Comment by jvillafanez** [comment]
I think the `generate` function accepts a list of chars that will be used. It should be easy to provide a list without the `/` char, so there is no need to recreate the ID.

> but that would mean it would change it for all other places as well

As the docs states, the `getID` doesn't intend to provide an unique uid for the request and it should be used mainly for logging purposes. I don't expect that changing one char to another will be dramatic. Anyway, it's possible to check how that function is being used (if it's being used outside of logging) in order to minimize any side effect.

**Comment by kdslkdsaldsal** [comment]
Please keep in mind to note such changes to the log syntax within the Changelog of the release. You will definitely get complains of users (using fail2ban for example) if you change the log syntax silently (see e.g. https://github.com/owncloud/core/issues/1580).

**Comment by jvillafanez** [comment]
@kdslkdsaldsal I'll make sure it will appear in the changelog, and in central.

**Comment by butonic** [comment]
not only fail2ban but also log management systems like splunk or elk will need adjusting if they only used regex
