### ISSUE TITLE
Selenium fails with login

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27396]
@individual-it not sure when these started happening, possibly after merging your last PR but I didn't bisect to verify.

We now see these failures on lots of PRs: https://travis-ci.org/owncloud/core/jobs/211436896

```
...
@AdminLogin

  Scenario Outline: change quota to a valid value                  # /home/travis/build/owncloud/core/tests/ui/features/users.feature:4

    Given quota of user "admin" is set to "<start_quota>"          # UsersContext::quotaOfUserIsSetTo()

    When quota of user "admin" is changed to "<wished_quota>"      # UsersContext::quotaOfUserIsChangedTo()

    And page is reloaded                                           # UsersContext::pageIsReloaded()

    Then quota of user "admin" should be set to "<expected_quota>" # UsersContext::quotaOfUserShouldBeSetTo()

    Examples:

      | start_quota | wished_quota | expected_quota |

      ┌─ @BeforeScenario @AdminLogin # FeatureContext::setUpScenario()

      │

      ╳  Expected to be on "http://owncloud:8888/index.php/login" but found "" instead (SensioLabs\Behat\PageObjectExtension\PageObject\Exception\UnexpectedPageException)

      │

      | Unlimited   | 5 GB         | 5 GB           |

      ┌─ @BeforeScenario @AdminLogin # FeatureContext::setUpScenario()

      │

      ╳  Expected to be on "http://owncloud:8888/index.php/login" but found "" instead (SensioLabs\Behat\PageObjectExtension\PageObject\Exception\UnexpectedPageException)

...
```

@individual-it mind having a look ?
Thanks

**Comment by individual-it** [comment]
strange, it did run fine for a while
can you post the saucelabs URL for one of those tests?
When running the tests locally I'm getting CSFR error during login. Anything changed there in the last time? Strange I can login manually without any trouble

**Comment by DeepDiver1975** [comment]
Oh I guess the trouble is within the trial version of sauce expired yesterday :man_facepalming:

**Comment by PVince81** [comment]
Do we really need Saucelabs ? Would it be possible to run selenium tests in headless mode on our Jenkins infrastructure instead ? If the future brings lots of new tests then it is likely going to explode in size and duration...

**Comment by DeepDiver1975** [comment]
> Do we really need Saucelabs ? Would it be possible to run selenium tests in headless mode on our Jenkins infrastructure instead ? If the future brings lots of new tests then it is likely going to explode in size and duration...

I just asked sause to convert my account into an open source account ... let's see ...

**Comment by SergioBertolinSG** [comment]
@PVince81 I guess the main benefit is that you can have tests running using different drivers and check behaviour against different browsers.

Headless doesn't behave exactly the same as the other drivers.

**Comment by PVince81** [comment]
Ok, but it is also possible to setup a virtual X server and have the browsers run there.

**Comment by individual-it** [comment]
@PVince81 so you suggesting to run the selenium tests completely in travis, without saucelabs?

**Comment by DeepDiver1975** [comment]
Okay - we have an open source account now with saucelabs ... let's see ...

**Comment by DeepDiver1975** [comment]
green now again
