### ISSUE TITLE
OCS Share API

### ISSUE THREAD

**Issue by maimalash** [owncloud/core#27400]
i review OCS Share API from this link 
https://doc.owncloud.org/server/8.2/developer_manual/core/ocs-share-api.html
 and there is not Statuscodes =200
when i share file with a user that own this file response get you can't share this file with file owner 
with Statuscodes =200 
you use 
ocs/v1.php/apps/files_sharing/api/v1/shares with paremter
from where you get Statuscodes =200 and how you know file owner

**Comment by kdslkdsaldsal** [comment]
@maimalash Please note this is a bugtracker for ownCloud. Please close here and:

1. if you have questions to the OCS Share API ask your question at https://central.owncloud.org/ (you can login with your github credentials there)

2. if there is a problem with the documentation create a new issue in https://github.com/owncloud/documentation/issues

It might also help if you take some time and write your issue down more clearly. I think i'm not the only one who doesn't understand what issue you're currently facing.

**Comment by maimalash** [comment]
Sorry if i am not clear i'm asking about Statuscodes =200 in CreateRemoteShareOperation when i share file with file owner i get this error code "sharing failed because the user is xxx is the original shares " in documentation Create a new Share there is this 
Statuscodes:
100 - successful
400 - unknown share type
403 - public upload was disabled by the admin
404 - file couldn’t be shared
from where Statuscodes =200 comes and how we know file owner
