### ISSUE TITLE
won't update  

### ISSUE THREAD

**Issue by rasco2** [owncloud/core#27402]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen
I run  the new update 

### Actual behaviour
Tell us what happens instead

Updating ownCloud to version 9.0.8, this may take a while.

Preparing update
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
contacts_old: An exception occurred while executing 'CREATE TABLE `oc_contacts_addressbooks` (`id` INT UNSIGNED AUTO_INCREMENT NOT NULL, `userid` VARCHAR(255) DEFAULT '' NOT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(200) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `ctag` INT UNSIGNED DEFAULT 1 NOT NULL, `active` INT DEFAULT 1 NOT NULL, INDEX c_addressbook_userid_index (`userid`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_contacts_addressbooks' already exists

### Server configuration
**Operating system**:
Debian 7.6
**Web server:**
Apache2
**Database:**
php myadmin
**PHP version:**
php 5.5.27
**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**
ownCloud 8.2.9 
**Where did you install ownCloud from:**
web  /settings/admin#updater
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
ownCloud will be updated to version 9.0.8

Please make sure that the database, the config folder and the data folder have been backed up before proceeding.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by kdslkdsaldsal** [comment]
This looks like a duplicate of https://github.com/owncloud/core/issues/23867

**Comment by rasco2** [comment]
I am closing this issue,   
but just wanted to mention that  for the apps when i enable one of them,i get that exact same error message.
