### ISSUE TITLE
MySQL to use 4-byte unicode - possible migration step needed

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#27409]
**First:**
Maybe I missed that, but when changing a 3-byte unicode MySQL to use 4-byte unicode and also enabling it in owncloud https://github.com/owncloud/core/blob/master/config/config.sample.php#L1084-L1107
this does not mean that it is really used.

When you setup a fresh new database - yes.
But having a existing one - no. 
Tables need to be converted first. This creates imho misleading expectations.
https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-conversion.html

There should be a process in core converting the tables automatically (forth and back).
Then things are clean. We can not have the admin doing this manually.
There must be a kind of migration step or a ./occ command

**Second:**
Enabling it is one thing, but is there a impact on db backup and restore?
Backup 3-byte and restore on 4-byte ect.

**Documentation:**
Independent of the above possibilities and conversion, there must be a documentation note to cover that. https://github.com/owncloud/documentation/pull/2926

@DeepDiver1975 
@settermjd

**Comment by DeepDiver1975** [comment]
> There must be a kind of migration step or a ./occ command

there is

![bildschirmfoto von 2017-03-17 16-32-53](https://cloud.githubusercontent.com/assets/1005065/24050540/68438fb0-0b2f-11e7-88d9-0f2212ca1be0.png)

**Comment by mmattel** [comment]
Great, no mentioning found about that ...

@settermjd 
- To be added in the docmentation PR
- I also propose a note / cross ref to the documentation in https://github.com/owncloud/core/blob/master/config/config.sample.php#L1084-L1107

@DeepDiver1975 
- From the documentation PR: ...Let me double check config.sample.php - maybe this needs some adoptions as well... - Any update on this one as it affects config.sample.php?
- Any backup/restore impact(s) as written above?

**Comment by DeepDiver1975** [comment]
I guess this is addressed with #27441

**Comment by mmattel** [comment]
@DeepDiver1975 
Slightly disagree.
- There is no mentioning that the parameter is set automatically in config.php during setup or when ./occ run successfully
- There is no mentioning what happens if the parameter is manually turned back to false when it was tue before
- There must be a note for existing instances beeing upgraded with regards to backup/restore behavior. eg is a DB restore from 3-byte layout possible to a 4-byte layout ect.

**Comment by DeepDiver1975** [comment]
> There is no mentioning that the parameter is set automatically in config.php during setup or when ./occ run successfully

isn't this enough? https://github.com/owncloud/core/blob/a0049f132df6a2dfe54db94ae8b8aee24a265dbc/config/config.sample.php#L1085-L1090

if now I happily accept a different doc bloc - I'm good at coding but bad on doc 😉 



> There is no mentioning what happens if the parameter is manually turned back to false when it was tue before

to me this is just like with any other config setting: don't mess with it 😉 
but again - let's add some more doc in config sample



> There must be a note for existing instances beeing upgraded with regards to backup/restore behavior. eg is a DB restore from 3-byte layout possible to a 4-byte layout ect.

hmmmm - usually I'd expect that files, db and config are backed up together at the (almost) same time.
none of the three can life without the other

**Comment by mmattel** [comment]
The current text block describes the situation during first time setup, but not when upgrading an existing installation.
Yes, you are right, not playing around is always a good thing, but it would help to understand the impact if the DB and owncloud is enabled for 4-byte but the parameter is set to false (whyever). Maybe you can bring some insight into to have a fundament for doc text.
Backup/restore: just imagine you do a backup then the upgrade and one week later something went wrong, no change in config.php. You simply restore the DB (whyever...), but it has the old scheme. What might be the impact? Maybe none, maybe some, it should be mentioned in the docs.

By addressing these topics, we create clarity and avoid confusion or misunderstanding

**Comment by DeepDiver1975** [comment]
> The current text block describes the situation during first time setup, but not when upgrading an existing installation.

https://github.com/owncloud/core/blob/a0049f132df6a2dfe54db94ae8b8aee24a265dbc/config/config.sample.php#L1085-L1090

```php
/**
 * If requirements are met (see below) this setting is set to true during setup
 * and MySQL can handle 4 byte characters instead of 3 byte characters.
 *
 * If you want to convert a 3-byte setup into a 4-byte setup please run the
 * migration command:
 * ./occ db:convert-mysql-charset
 *

**Comment by mmattel** [comment]
you are right, but there is no statement that the occ command sets the parameter after running successfully... :smile:

**Comment by PVince81** [comment]
solved ?

**Comment by mmattel** [comment]
We need documentation update and an answer what happens if the paramete is set to false when it was true before, eg the occ command run successfully

**Comment by DeepDiver1975** [comment]
> We need documentation update and an answer what happens if the paramete is set to false when it was true before, eg the occ command run successfully

let's move this over to the documentation repo @settermjd

**Comment by mmattel** [comment]
Lets add a statement to config.sample.php that the occ command sets the parameter on successful run, maybe also a note to get more details in documentation.
@settermjd will need the info from you regarding the question I raised above so he can update the doc accordingly.

**Comment by DeepDiver1975** [comment]
> Lets add a statement to config.sample.php that the occ command sets the parameter on successful run, maybe also a note to get more details in documentation.

fine by me - @mmattel wanna submit a pr? THX

**Comment by mmattel** [comment]
@DeepDiver1975 done

Please state what happens if the environemt is set to 4 bytes and the parameter gets reset to false (3 bytes)
Having that, @settermjd could finalize the documentation part.

**Comment by PVince81** [comment]
@DeepDiver1975 ^
