### ISSUE TITLE
Bug with creating folder when copy-pasting the name

### ISSUE THREAD

**Issue by AlexKononenko** [owncloud/core#27411]
When I try to create folder and copy-paste the name (e.g. I copied it from some Excel document) I get Error.

But when I enter the name - everything is ok.

**Comment by kdslkdsaldsal** [comment]
@AlexKononenko Please fill out the issue template shown when creating a new issue. This is asking you various mandatory info about your environment which are needed to help here (there is a reason why this template is shown).

**Comment by PVince81** [comment]
can't help without the requested info
