### ISSUE TITLE
Owncloud 9.1.4 upgrade with deprecated dependencies

### ISSUE THREAD

**Issue by maximd1** [owncloud/core#27414]
Hello,

today's yum update follows with this stuff:

Resolving Dependencies
--> Running transaction check
---> Package **owncloud.noarch 0:9.1.4-2.1** will be updated
---> Package **owncloud.noarch 0:9.1.4-3.el7** will be an update
...
---> Package **php-common.x86_64 0:5.4.16-42.el7** will be installed
...
--> Processing Conflict: php56w-common-5.6.30-1.w7.x86_64 conflicts php-common < 5.6
--> Finished Dependency Resolution
Error: php56w-common conflicts with php-common-5.4.16-42.el7.x86_64

Meanwhile I have php 5.6:

[maximd@WWW ~]$ php -v
PHP 5.6.30 (cli) (built: Jan 19 2017 22:31:39)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

[maximd@WWW ~]$ rpm -qva | grep php
php56w-5.6.30-1.w7.x86_64
owncloud-deps-php5-9.1.4-2.1.noarch
php56w-pecl-memcache-3.0.8-2.w7.x86_64
php56w-common-5.6.30-1.w7.x86_64
php56w-pecl-apcu-4.0.11-1.w7.x86_64
php56w-process-5.6.30-1.w7.x86_64
php56w-gd-5.6.30-1.w7.x86_64
php56w-mysql-5.6.30-1.w7.x86_64
php56w-xml-5.6.30-1.w7.x86_64
php56w-pecl-memcached-2.2.0-1.w7.x86_64
php56w-pdo-5.6.30-1.w7.x86_64
php56w-opcache-5.6.30-1.w7.x86_64
php56w-pecl-igbinary-2.0.1-1.w7.x86_64
php56w-pear-1.10.1-1.w7.noarch
php56w-mbstring-5.6.30-1.w7.x86_64
php56w-ldap-5.6.30-1.w7.x86_64
php56w-pgsql-5.6.30-1.w7.x86_64
php56w-cli-5.6.30-1.w7.x86_64

Current version of Owncloud server is **owncloud-9.1.4-2.1.noarch**.

I use Centos 7.3.1611 with kernel 3.10.0-514.10.2.el7.x86_64, repository is:

[ce_stable]
name=ownCloud Server Version stable (CentOS_7)
type=rpm-md
baseurl=http://download.owncloud.org/download/repositories/stable/CentOS_7
gpgcheck=1
gpgkey=http://download.owncloud.org/download/repositories/stable/CentOS_7/repodata/repomd.xml.key
enabled=1

How to fix the issue?

Thank you.

**Comment by PVince81** [comment]
@crrodriguez please have a look

**Comment by kdslkdsaldsal** [comment]
Just to clarify:

The OP is using a 3rdparty repository "webstatic" which provides this PHP 5.6 package "php56w". This is no official package from CentOS 7.

**Comment by crrodriguez** [comment]
Well.. owncloud actually needs php-common .. php56w-common should provide php-common = %{version} and obsolete php-common < %{version} this does not look like a bug in the owncloud package IMHO.

**Comment by TheOtterslider** [comment]
Long story, but I hand-installed the dependancies of ownCloud and found these packages threw the error mentioned by @maximd1 

php-dropbox-php-Dropbox
php-mcnetic-zipstreamer
php-pecl-apfd
php-pecl-http
php-pecl-http1
php-pecl-json-post
php-pecl-oauth
php-pecl-propro
php-pecl-raphf
