### ISSUE TITLE
 Feature Request: occ command to list users like ./occ user:list [--admin] [options to filter]

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#27425]
@PVince81 as discussed on IRC

This FR is about a new occ command to list existing users.
It is not about listing users beeing logged on, but just existing once.

**Parameters:**
--admin ... list only users with admin rights

[options] ... ideas:
--json (output format)
--long (default: short, what to print out)
--quantity:xxx (default: 10, how many users are printed)
--filter:name* (filter usernames)
... more ideas to be added

**Examples:**
./occ user:list
12 users found, 1 admin

./occ user:list --admin
user_x

./occ user:list --admin --long
user_x user_x@mydomain.com

./occ user:list --filter:z*
no users found

**Comment by mmattel** [comment]
Complements each other
https://github.com/owncloud/core/issues/26972 Proposal: add new occ command to list users

**Comment by PVince81** [comment]
duplicate of https://github.com/owncloud/core/issues/27425

**Comment by mmattel** [comment]
as @DeepDiver1975 already identified in the referenced issue, we have now a user:list command.
Proposing to close.

**Comment by mmattel** [comment]
Closing, command has been implemented
