### ISSUE TITLE
Lost 'secret' config value

### ISSUE THREAD

**Issue by PeterFour** [owncloud/core#27428]
While doing a backup of my config.php file it got corrupted and I lost the  'secret' value.

Is there any way to decrypt the files on the server ?

**Comment by PeterFour** [comment]
UPDATE: Managed to recover the secret string thanks to photorec

However I still have the flash message saying that the key is not correct and needs to be updated, but the decrypt-all command works ?

**Comment by DeepDiver1975** [comment]
please use the forum to ask for help - https://central.owncloud.org/
