### ISSUE TITLE
Transfer ownership must work with master key

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27427]
Transfer ownership should be possible because it doesn't require any user's specific password.

Currently it doesn't:

### Steps:
1. `cd tests/integration`
1. Edit transfer-ownership.feature and remove "no_encryption" tags
1. `sudo -u wwwrun OC_TEST_ENCRYPTION_MASTER_KEY_ENABLED=1 ./run.sh features/transfer-ownership.feature`

### Expected:
All tests passing.

### Actual:
Transfer ownership refuses to work because it detects encryption.

- [ ] adjust `isReadyForUser` to return true if master key is used
- [ ] somehow detect that encrypted files are ok when master key is enabled instead of asking for decryption. This is a bit tricky because it requires calling non-specific encryption manager APIs.

Maybe add a method to the encryption modules to let them tell whether moving files between users can be done without their passwords ?

@pmaier1 will become more important when we start fading out the default encryption

**Comment by sharidas** [comment]
Sure

**Comment by butonic** [comment]
@pmaier1 @PVince81 we fade out the individual user key based encryption?

**Comment by PVince81** [comment]
While the merged PRs seem to work, there is a risk that it will not always work correctly in case the storage wrappers are setup differently. The problem is here: https://github.com/owncloud/core/pull/28107/files#diff-938b56891f3079e628cfda1c331911b7R366

This adds an argument to `fopen` which at first look seemed fine but in hindsight I remembered that if the encryption wrapper is itself wrapped by another `fopen` wrapper, the latter will likely not forward the value to the encryption wrapper, so it would break.

So far we are lucky that it works fine for transfer ownership but could break with third party apps.

I'm moving this ticket to "planned" now to look into other ways to pass around that value. This is quite tricky with the current architecture without resorting to globals...

**Comment by PVince81** [comment]
@sharidas please link to the PRs where you cleant up the tech debt mentioned above, then close.

**Comment by sharidas** [comment]
The PR which addresses issue referred https://github.com/owncloud/core/issues/27427#issuecomment-320682630 is here  https://github.com/owncloud/core/pull/28774 . This is another PR which got addressed https://github.com/owncloud/core/pull/28820 and merged.
