### ISSUE TITLE
Sabre/dav maintainer is abandoning project

### ISSUE THREAD

**Issue by hogarthj** [owncloud/core#27422]
Hi,

The sabre/dav developer recently blogged that he's marking the project EOL and no longer going to work on it.

What are you plans to handle this, especially given the nature of the project and the prospect of vulnerabilities?

https://evertpot.com/sabredav-eol/

**Comment by kdslkdsaldsal** [comment]
> The sabre/dav developer recently blogged that he's marking the project EOL and no longer going to work on it.

For now its not EOL, the developer is currently looking for new maintainers. Only if this is not successful the project is marked as "unmaintained" as stated in the linked blogpost:

> If I don’t find new maintainers within a month or so, I will advertise these projects as being ‘unmaintained’ and unsubscribe from any notifications.

**Comment by hodyroff** [comment]
We are in discussions with fruux and other ecosystem and community participants and confident that some solution can be found. It is always a challenge when a grreat Open Source maintainer decides to switch focus. In any case ownCloud has people on staff who have submitted and merged patches before, so we have the capability to fix things as needed. Of course we hope that a continues development community will find together. Hope this answers things for now.

**Comment by kdslkdsaldsal** [comment]
Just a short update on this topic from evert:

https://evertpot.com/sabredav-maintenance-update/

**Comment by kdslkdsaldsal** [comment]
And a follow up from #28341 

> At least from today on, more people will be able to merge and make releases: sabre-io/dav#1007
