### ISSUE TITLE
Split encryption master-key into its own app

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27438]
Currently the master key mode is bundled by the default encryption module app.

Since they work differently and master key enables much more functionality to work as expected, we should move its code into a separate app.

Well, extract the code because it's intertwined with the default encryption code...

**Comment by PVince81** [comment]
Note: migration could be an issue here as one would need to migrate from the old app to the new one.

**Comment by PVince81** [comment]
This will be more tricky than I thought: the id of the encryption module is stored within every encrypted file's header. This means that in the current OC even master key mode will store the id of "default encryption module". So once we split the master key to be its own separate module, the id will be different so the code will not recognize this any more.

We need to have either some fallback code that still somehow makes the default module contact the master key module to make it continue working, but it's ugly.

Or need a migration path that adjusts the header of ALL files at update time (or per OCC command), which is likely to run forever for big installs...

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
