### ISSUE TITLE
Can’t share files with new users and groups

### ISSUE THREAD

**Issue by HirnIT** [owncloud/core#27435]
Hello,

I recently got some problems with new users.
I can add/create users and groups without any problems, the users can log in and use ownCloud.

But if I try to share folers with the new users or groups owncloud tells me that the user/group can't be found.
This happens in the webinterface aswell as with the client
### Steps to reproduce
1. Create new user oder group with the webinterface.
2. Open Files -> click on share
3. See error message that the user can't be found

### Expected behaviour
All users and groups created with 9.1.4 can't be added to shared folders, old ones are working just fine.

### Actual behaviour
error message that the user can't be found

### Server configuration
Operating system: Linux Debian jessie
Web server: Apache 2.4.10
Database: MySQL 5.0.11
PHP version: 5.6.30
ownCloud version 9.1.4:
Updated from an older ownCloud or fresh install: Update from 9.1.2 or 3
Special configuration (external storage, external authentication, reverse proxy, server-side-encryption):
server-side-encryption is on

**Where did you install ownCloud from:**
deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.7
  - encryption: 1.3.0
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1

**The content of config/config.php:**

"updatechecker": false,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.domain.tld"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/oc.domain.tld",
        "dbtype": "mysql",
        "version": "9.1.4.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "ocsskar7o1xa",
        "mail_from_address": "monitor",
        "mail_smtpmode": "smtp",
        "mail_domain": "domain.tld",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "sslout.domain.tld",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### ownCloud log (data/owncloud.log)
Error 	files 	Backends provided no user object for test 	2017-03-20T11:08:09+00:00

**Comment by HirnIT** [comment]
It's the default mysql db.
The users are listed in the table and are able to login.

**Comment by PVince81** [comment]
Can you post the log ?
Don't copy paste the error from the web UI but really open owncloud.log and copy paste the error with the stack trace in here.

Try setting loglevel to 0 and enabling the xdebug module to make sure a stack trace is logged.

**Comment by HirnIT** [comment]
The only error related to the users is this:
Error 	files 	Backends provided no user object for test3 

I tried 9.1.5 rc2 1.1, get the same error

**Comment by cormite** [comment]
I see the same error in version 10.0.1.5

{"reqId":"WSr-ehOw45aRnphgfF3BAgAAAAk","level":3,"time":"2017-05-28T16:48:59+00:00","remoteAddr":"192.168.111.20","user":"--","app":"index","method":"GET","url":"\/index.php\/s\/lehcLS0sLg3mxK4","message":"Exception: {\"Exception\":\"OC\\\\User\\\\NoUserException\",\"Message\":\"Backends provided no user object for aaaa@aaaa.aaa\",\"Code\":0,\"Trace\":\"#0 [internal function]: OC\\\\Files\\\\Node\\\\Root->getUserFolder('aaaa@aaaa.aa...')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(66): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/LazyRoot.php(283): OC\\\\Files\\\\Node\\\\LazyRoot->__call('getUserFolder', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Share20\\\/Share.php(159): OC\\\\Files\\\\Node\\\\LazyRoot->getUserFolder('aaaa@aaaa.aa...')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/Controllers\\\/ShareController.php(245): OC\\\\Share20\\\\Share->getNode()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/Controllers\\\/ShareController.php(274): OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController->validateShare(Object(OC\\\\Share20\\\\Share))\\n#6 [internal function]: OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController->showShare('lehcLS0sLg3mxK4', '')\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController), 'showShare')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Sharing\\\\Controllers\\\\ShareController), 'showShare')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/App.php(135): OC\\\\AppFramework\\\\App::main('ShareController', 'showShare', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer))\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/core\\\/routes.php(94): OCP\\\\AppFramework\\\\App->dispatch('ShareController', 'showShare')\\n#12 [internal function]: OC\\\\Route\\\\Router->{closure}(Array)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(Closure), Array)\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(918): OC\\\\Route\\\\Router->match('\\\/s\\\/lehcLS0sLg3m...')\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php\",\"Line\":343}"}

**Comment by olpons** [comment]
Hi,

got same issue with Owncloud 10.0.2.1 stable.
I create a new user.
Go to "Files" items and click share button.
Then, I enter the new user created before and get "User not found".
If y return to users list, I can see this user.

Any update will be appreciate.

Regards

Olivier

**Comment by sbeu** [comment]
Hello, exact same problem here. 
Any update?

**Comment by zrogers911** [comment]
I thought I was having the same issue. Then I went to admin settings and unchecked "Restrict users to only share with users in their groups"....or just add yourself to the group that you want to share the files in.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
