### ISSUE TITLE
Trusted Server Info in Settings/Admin/Share behaves not according the documentation

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#27445]
### Steps to reproduce
1. Clone 2x core from git and set them up
2. Create a federated share relationship

Note, cron is setup and runs successfully

### Expected behaviour
- The text "Add server automatically once..." in Admin/Settings should appear as described in the documentation
- The trusted owncloud server should appear

### Actual behaviour
- The text has the wrong style and there is no checkbox
- No trusted servers appear, even after a 2h

**This is how it should appear: (from documentation)**
![image](https://cloud.githubusercontent.com/assets/3321281/24161309/52785d7c-0e64-11e7-9849-1a89b05e2308.png)

**This is how it appears:**
![image](https://cloud.githubusercontent.com/assets/3321281/24161219/1c8bff5c-0e64-11e7-9bfe-d35b0ba5bbc2.png)

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.0.3

**Updated from an older ownCloud or fresh install:** git clone

**Where did you install ownCloud from:** git

**The content of config/config.php:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oclf"
        ],
        "datadirectory": "\/var\/www\/owncloud\/core\/data",
        "overwrite.cli.url": "http:\/\/oclf",
        "dbtype": "mysql",
        "version": "10.0.0.3",
        "dbname": "ocld",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "filesystem_check_changes": 1,
        "cachedirectory": "\/var\/www\/owncloud\/core\/data\/cache",
        "cache_path": "",
        "quota_include_external_storage": false,
        "logfile": "\/var\/www\/owncloud\/core\/data\/logtest",
        "logdateformat": "u",
        "preview_max_x": 756,
        "preview_max_y": 756,
        "preview_max_scale_factor": 2,
        "enabledPreviewProviders": [
            "OC\\Preview\\JPEG",
            "OC\\Preview\\PNG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Postscript"
        ],
        "instanceid": "xxxx",
        "defaultapp": "",
        "share_folder": "",
        "trashbin_retention_obligation": 30,
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera

**Operating system:** Ubuntu 16.04

**Comment by DeepDiver1975** [comment]
@mmattel this is intended - this automated adding of trusted server has to be enabled via config - maybe something we need to add for the oc10 docs @settermjd

**Comment by mmattel** [comment]
@DeepDiver1975 
Pls also have a look to core, because 
- the text "Add server automatically once..." behaves like a link without target (mouse over changes the mouse appearance)
- the text has an expression to do something, but no actioncan be taken 
- does not show the current state
- has a different style
- there is no hint text pointing to the documentation like we do on other items
- why don´t we have the parameter in config.php set when the instance is setup and set to default "true" to behave like before
- can´t find a parameter in config.sample.php which correlates. Searching for "trusted" only responds for domains, but not for servers and not as a true/false item. Searching for "servers" is the same.
- having a existing instance and updating to 10, how is the transition from the current checkmark setting at the admin page to the new behaviour with a config.php parameter?

@settermjd 
Yes, a documentation update is necessary to correlate to the new behaviour including new screenshots.

**Comment by DeepDiver1975** [comment]
> why don´t we have the parameter in config.php set when the instance is setup and set to default "true" to behave like before

because we wanted the default behavior to be different. I'll comment on the rest later

**Comment by DeepDiver1975** [comment]
ah - now I see the issue :facepalm:

**Comment by DeepDiver1975** [comment]
@tomneedham please have a look - maybe something went wrong while migrating the settings - thx

**Comment by davitol** [comment]
> No trusted servers appear, even after a 2h

![screen shot 2017-03-23 at 08 18 01](https://cloud.githubusercontent.com/assets/10596560/24236321/ab804202-0fa1-11e7-9f46-aececa53a871.png)

@tomneedham @mmattel Not sure what not trusted server appears. The current behaviour is shown in the screenshot.

**Comment by davitol** [comment]
![screen shot 2017-03-23 at 08 15 49](https://cloud.githubusercontent.com/assets/10596560/24236390/e5eb666a-0fa1-11e7-8b3d-00ee85f5108a.png)
![screen shot 2017-03-23 at 08 15 30](https://cloud.githubusercontent.com/assets/10596560/24236391/e5f050da-0fa1-11e7-9bfb-a89e0148ac83.png)


Should we change these kind of error messages to a more specific ones? Maybe out of the scope of this ticket and better open a new one?

**Comment by mmattel** [comment]
Imho, open a seperate one
Agreed, should be changed/fixed

**Comment by davitol** [comment]
> Should we change these kind of error messages to a more specific ones? Maybe out of the scope of this ticket and better open a new one?

https://github.com/owncloud/core/issues/27464

**Comment by tomneedham** [comment]
Can we close this @davitol ?

**Comment by davitol** [comment]
@tomneedham Yes, closed
