### ISSUE TITLE
[Feature Request] Disable reset password link

### ISSUE THREAD

**Issue by BornToBeRoot** [owncloud/core#27440]
We have a ownCloud instance which is reachable from intern & extern with a an LDAP backend.

When a user enters wrong credentials, the "wrong password" box appears, with a link to reset the password.

I know that i can change the password reset link in the config.php with:
`'lost_password_link' => 'https://example.org/link/to/password/reset',`

But i don't want to host an external site with an information, how my users can reset their password or who to contact.

It would be great if there would be an option in the config.php like: 
`'disable_password_link' => true,` 
to disable  the reset link completely.

There should only be the information for the user, that the credential which they have entered are wrong.
Example message "Wrong Credentails! Try again."

**Comment by DeepDiver1975** [comment]
sounds reasonable to me - THX for suggesting.

**Comment by imujjwal96** [comment]
@DeepDiver1975 would like to work on it

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 I would like to work on it

your are more then welcome - go for it 😉

**Comment by pmaier1** [comment]
Is there some progress here? @imujjwal96

**Comment by imujjwal96** [comment]
Forgot to push the code. Sorry for the delay.

**Comment by PVince81** [comment]
PR merged, thanks a lot!
