### ISSUE TITLE
Impossible to connect 

### ISSUE THREAD

**Issue by tvillanova** [owncloud/core#27450]
Hi, 
I have installed owncloud on my raspberry (as a server). 
I have a problem when i want to log on the main page. 
When i input my login nothing happens. 
So i went to the console and i have these errors : 
` Jquery is not definded` i know it's a problem with this library. 
How can i do ? Jquery was installed, i don't understand... 

thanks

**Comment by DeepDiver1975** [comment]
> I have installed owncloud on my raspberry (as a server).

how did you install?

Please head over to the forums for help https://central.owncloud.org/
