### ISSUE TITLE
Cannot configure GoogleDrive as external Storage

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27456]
I guess GoogleDrive needs unique URLs to be configured and does not handle  with the query parameters 

```http://myserver.com/index.php/settings/admin?sectionid=storage```

Configure the Google Drive oauth and click on grant access
![screen shot 2017-03-22 at 17 41 58](https://cloud.githubusercontent.com/assets/10596560/24209631/17b7904a-0f27-11e7-81ac-9a078bfc5094.png)

Click on Allow
![screen shot 2017-03-22 at 17 42 10](https://cloud.githubusercontent.com/assets/10596560/24210093/543cab6c-0f28-11e7-842f-976184c1090f.png)

You are redirected with taking into account the query parameters sectionid=storage
```
http://myserver.com/index.php/settings/admin?code=4/4bo6L3S52hippSDvfutPCPaTsg0SzrZo15L8uMQK3I#
```
![screen shot 2017-03-22 at 17 44 09](https://cloud.githubusercontent.com/assets/10596560/24209670/370e5334-0f27-11e7-864a-338584da6e26.png)

@tomneedham

**Comment by tomneedham** [comment]
I believe we need to tweak https://github.com/owncloud/core/blob/master/apps/files_external/js/oauth2.js#L40 and https://github.com/owncloud/core/blob/master/apps/files_external/ajax/oauth2.php#L42

**Comment by PVince81** [comment]
Setting to critical as this is a loss of functionality and there is no workaround.

**Comment by PVince81** [comment]
@davitol fixed ?

**Comment by davitol** [comment]
@tomneedham Works for me. Let's close this ticket

**Comment by PVince81** [comment]
doesn't work for me, also documentation is not up to date it seems: https://doc.owncloud.org/server/10.0/admin_manual/configuration_files/external_storage/google.html?highlight=google%20drive

I set these callback URLs:
![gdrive-redirect-url](https://cloud.githubusercontent.com/assets/277525/26731110/4745c0ba-47b3-11e7-92ca-fc70ea6e353d.png)

I still get the "redirect_uri_mismatch" 400 error when clicking "Grant access".

@davitol how did you test it ?

**Comment by PVince81** [comment]
never mind, seems to work fine on master with these settings. I was testing the guzzle update branch https://github.com/owncloud/core/pull/28063
