### ISSUE TITLE
Add ability to register storage backends through info.xml

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27469]
Currently storage backends and auth mechanisms for external storage need to be registered with code, like https://github.com/owncloud/files_external_ftp/blob/master/lib/AppInfo/Application.php#L40

It would be useful to move that to info.xml to make it easier for app developers.

Tagging as junior job. Slightly challenging but should be ok as we have some examples with Sabre plugins registration with info.xml and Background jobs. So it's mostly a matter of using a similar approach.

@DeepDiver1975 @jvillafanez @Xenopathic

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
I still want this.

Unless we can get https://central.owncloud.org/t/service-based-app-imlpementation-to-solve-inter-app-dependencies/1615 in which case it would be a "providesStorageBackend" service.
