### ISSUE TITLE
Feature Request: info symbol at settings/admin/sharing/federation to see detailed status info

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#27479]
To have on each ok/pending Trusted Server a info symbol where you can click on to see the servers status.php info. A small window should appear on the right and the details are shown. Clicking outside the window, the window should close.

![image](https://cloud.githubusercontent.com/assets/3321281/24290347/ebe6771a-1084-11e7-9c83-de3638c501cf.png)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
