### ISSUE TITLE
Lost shares when using external storage and LDAP Backend 

### ISSUE THREAD

**Issue by juaalo** [owncloud/core#27471]
### Steps to reproduce
1. Create CIFS external Storage; connect with AD user; Give permission to LDAP user
2. Log in with LDAP user; share a folder with an AD Group, share another folder with public link
3. Break connection to LDAP server (stop LDAP server)
4. Execute.  /usr/bin/php /var/www/html/owncloud/occ files:scan LDAPuser
5. Start LDAP Server
6. Log in with LDAPuser

### Expected behaviour
You have all your shares there

### Actual behaviour
You have lost all your shares...

### Server configuration
**Operating system**: CenOS 7

**Web server:** Apache

**Database:** mysql

**PHP version:** PHP 5.4.16

**ownCloud version:** 9.1.4

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_ldap: 0.9.0
Disabled:
  - encryption
  - external
  - files_antivirus
  - user_external


**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocaa34qdd6kc",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.4.18",
            "bgbox.nnttr.com"
        ],
        "datadirectory": "\/app1\/data\/owncloud",
        "overwrite.cli.url": "http:\/\/192.168.4.18\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.4.2",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Madrid",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "mail_smtpmode": "smtp",
        "mail_from_address": "sistemas",
        "mail_domain": "nnttr.com",
        "mail_smtphost": "mail.nnttr.com",
        "mail_smtpport": "25",
        "appstore.experimental.enabled": false,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "maintenance": false,
        "loglevel": 2,
        "ldapUserCleanupInterval": 30,
        "log_type": "owncloud"
    }
}


**Are you using external storage,YES smb/

**Are you using encryption:** no

**Are you using an external user-backend,YES: ActiveDirectory/

#### LDAP configuration (delete this part if not used)


+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                                   |
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                 |
| hasPagedResultSupport         |                                                                                                                                                   |
| homeFolderNamingRule          | attr:samaccountname                                                                                                                               |
| lastJpegPhotoLookup           | 0                                                                                                                                                 |
| ldapAgentName                 | cn=bgbox,cn=users,dc=ad,dc=begar,dc=es                                                                                                            |
| ldapAgentPassword             | ***                                                                                                                                               |
| ldapAttributesForGroupSearch  |                                                                                                                                                   |
| ldapAttributesForUserSearch   |                                                                                                                                                   |
| ldapBackupHost                | 192.168.2.21                                                                                                                                      |
| ldapBackupPort                | 389                                                                                                                                               |
| ldapBase                      | DC=ad,DC=begar,DC=es                                                                                                                              |
| ldapBaseGroups                | ou=owncloud,ou=usuarios,DC=ad,DC=begar,DC=es                                                                                                      |
| ldapBaseUsers                 | ou=usuarios,DC=ad,DC=begar,DC=es                                                                                                                  |
| ldapCacheTTL                  | 600                                                                                                                                               |
| ldapConfigurationActive       | 1                                                                                                                                                 |
| ldapDynamicGroupMemberURL     |                                                                                                                                                   |
| ldapEmailAttribute            | mail                                                                                                                                              |
| ldapExperiencedAdmin          | 0                                                                                                                                                 |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                   |
| ldapExpertUUIDUserAttr        | samaccountname                                                                                                                                    |
| ldapExpertUsernameAttr        |                                                                                                                                                   |
| ldapGroupDisplayName          | samaccountname                                                                                                                                    |
| ldapGroupFilter               | (&(|(objectclass=group)))                                                                                                                         |
| ldapGroupFilterGroups         |                                                                                                                                                   |
| ldapGroupFilterMode           | 0                                                                                                                                                 |
| ldapGroupFilterObjectclass    | group                                                                                                                                             |
| ldapGroupMemberAssocAttr      | member                                                                                                                                            |
| ldapHost                      | 192.168.3.45                                                                                                                                      |
| ldapIgnoreNamingRules         |                                                                                                                                                   |
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(|(memberof=CN=owncloud,OU=OWNCLOUD,OU=Usuarios,DC=ad,DC=begar,DC=es)(primaryGroupID=56619))))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                                                   |
| ldapLoginFilterEmail          | 0                                                                                                                                                 |
| ldapLoginFilterMode           | 0                                                                                                                                                 |
| ldapLoginFilterUsername       | 1                                                                                                                                                 |
| ldapNestedGroups              | 0                                                                                                                                                 |
| ldapOverrideMainServer        |                                                                                                                                                   |
| ldapPagingSize                | 0                                                                                                                                                 |
| ldapPort                      | 389                                                                                                                                               |
| ldapQuotaAttribute            |                                                                                                                                                   |
| ldapQuotaDefault              |                                                                                                                                                   |
| ldapTLS                       | 0                                                                                                                                                 |
| ldapUserDisplayName           | samaccountname                                                                                                                                    |
| ldapUserDisplayName2          |                                                                                                                                                   |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=owncloud,OU=OWNCLOUD,OU=Usuarios,DC=ad,DC=begar,DC=es)(primaryGroupID=56619))))                         |
| ldapUserFilterGroups          | owncloud                                                                                                                                          |
| ldapUserFilterMode            | 0                                                                                                                                                 |
| ldapUserFilterObjectclass     | person                                                                                                                                            |
| ldapUuidGroupAttribute        | auto                                                                                                                                              |
| ldapUuidUserAttribute         | auto                                                                                                                                              |
| turnOffCertCheck              | 0                                                                                                                                                 |
| useMemberOfToDetectMembership | 1                                                                                                                                                 |
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------+


### Client configuration
**Browser:** Firefox

**Operating system:** Windows 7

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"WNOVNBrgsL5Az8y08M9UzwAAABI","remoteAddr":"88.4.99.175","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 OC\\\\ServerNotAvailableException: Lost connection to LDAP server.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(69): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(167): handleException(Object(OC\\\\ServerNotAvailableException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php\",\"Line\":67,\"User\":\"ARABOX-COLORINES\"}","level":4,"time":"2017-03-23T10:28:21+01:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"ARABOX-COLORINES"}
{"reqId":"WNOVN715RkVHytvuMjg4FwAAAAM","remoteAddr":"81.172.92.61","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 OC\\\\ServerNotAvailableException: Lost connection to LDAP server.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(69): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(167): handleException(Object(OC\\\\ServerNotAvailableException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php\",\"Line\":67,\"User\":\"jacalvo\"}","level":4,"time":"2017-03-23T10:28:23+01:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"jacalvo"}
{"reqId":"WNOVOPXAt0K5K3M1cqDBYgAAAAQ","remoteAddr":"79.109.8.78","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 OC\\\\ServerNotAvailableException: Lost connection to LDAP server.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(69): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(167): handleException(Object(OC\\\\ServerNotAvailableException))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php\",\"Line\":67,\"User\":\"JMoldes\"}","level":4,"time":"2017-03-23T10:28:24+01:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"JMoldes"}

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by hodyroff** [comment]
Currently a not working LDAP server is a very bad idea for ownCloud. The system is essentially at a hold right then. Why does that occur? 
Executing your command under 4: in this case is interesting. This is likely not solveable before 10.0 - recommend to setup your LDAP as HA, or not execute occ-filescan without the LDAP present.
Basically what happens is that the file scan finds nothing - all stuff gone. Then the file-scan at login finds the external storage folders again and recreates them ...
In 10.0 we do some magic to fix it, more with the Beta ...

**Comment by juaalo** [comment]
Many thanks for your explanation hodyroff!
I have configured an ldapBackupHost and I have commented all scan jobs I had in crontab... this will avoid problems I hope... 
Is there any way to recover shares having a backup of oc_shares table?

**Comment by hodyroff** [comment]
You will need file scan for updates on the network share ... but if you check that LDAP is up first it should work.
Recovering shares from the database would be experimental, never done before. We try to avoid it in our support/consulting.

**Comment by juaalo** [comment]
Sorry hodyroff for opening this thread again, but I would like to explain this case of use:
- owncloud server in DMZ
- AD LDAP Server in internal network
- CIFS Server in internal network
- somohow, there is a communication problem between DMZ and internal Network (Firewall)
- External users still have access to owncloud server through internet
- External users browse their account, accessing External Storage Folder. Is not possible to browse
- Owncloud server: updates the cache? (it is a supposition, I suppose OC server updates the cache the same occ file:scan does...)
- As there is no access to External Storage, shares are dropped.
Is it this correct? If there are possibilities to lose shares with external stoage may be we prefer to know it and prevent our users, or may be is better using internal storage...

Best regards and thanks in advance....
JJ.-

**Comment by hodyroff** [comment]
In such a case we recommend a proxy server inside the DMZ.
The ownCloud Server would not update the cache in your case above.
As far as I understood it from my architect It's only triggered if a mount point is empty which was forced here by running the scan without LDAP access.
Hope you will help testing 10.0 Beta as this will have a user table which makes the LDAP request not needed in your case and will greatly reduce LDAP requests overall.

**Comment by juaalo** [comment]
many thanks hodyroff! I will try helping with v10 Beta. It sounds great to reduce LDAP requests, if I understood well, oc server will have a cache of LDAP users. This is OK, you will have to take into account refresh periods for not making new users wait a lot for first logging, or try LDAP if user is not found in cache...
