### ISSUE TITLE
No more automatic login after running web UI setup

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27478]
### Steps

1. Run setup on master + this patch https://github.com/owncloud/core/issues/27475
1. Setup with any DB in the web UI

### Expected result
Either the user must be logged in automatically as it was in past versions like v9.1.4, or at least display a message "Setup complete".
Optionally also redirect to the settings general page to see the security checks and warnings.

### Actual result
Login page appears without any message, admin must reenter credentials to log in.

### Versions
daily master 2017-03-24 + patch

I suspect that this new behavior was introduced with the user account table which required modifications to the session handling. So it is possible that the admin user does not get logged in automatically at setup time.

What do you think ?
Minor UX regression.

@DeepDiver1975 @butonic @VicDeo @IljaN @phisch @sharidas @pmaier1 @owncloud/qa @felixheidecke

**Comment by felixheidecke** [comment]
I don't really know how this used to look, but does a session start once the admin credentials have been set?

**Comment by PVince81** [comment]
It used to in 9.1.4, but no more on master / 10.0.

**Comment by felixheidecke** [comment]
From a UX perspective, it is not bad to redirect to the login screen so the user gets to know the login procedure. A "setup complete" message might help clarify. This would even work towards a reward-based tutorial in the future.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
No one complained so far and I personally got used to this. Good thing to practice entering the admin password anyway.
