### ISSUE TITLE
Cannot remove link password

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27481]
### Steps

1. Go to sidebar
1. Create a new public link
1. Set a password in the dialog
1. Save
1. Edit the public link again
1. Try deleting the password in the dialog

### Expected result
Password can be deleted

### Actual result
Stars are only the placeholder, no way to clear the password

### Versions
ownCloud 10.0 daily master

This is because the checkbox for adding/removing the password has been removed in the popup.
We need a new mechanism to be able to clear the password.
Currently the code does not resend the "password" attribute to leave the password unchanged, especially because we do not have the password in edit mode (not returned by the server).
So the new mechanism to clear the password, when activated, must set the "password" attribute to an empty string when saving.

@felixheidecke can you take care of this ?

Should this be a clear button that, when clicked, also clears the placeholder ?
Or back to checkboxes ?

**Comment by felixheidecke** [comment]
I'm on it

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/issues/27559
