### ISSUE TITLE
Inherit permission of uploaded folders

### ISSUE THREAD

**Issue by adamwozniak** [owncloud/core#27484]
Hello.
I have latest version of owncloud on ubuntu server and still 2nd and 3rd level folders are not inherit permission from its own root folder.

**Comment by PVince81** [comment]
Hello, please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

Need steps to reproduce and also a clarification about what you exactly mean with "inherit" (put this under "expected result")

**Comment by adamwozniak** [comment]
folder1 (full permission for admin group)
-folder2 (can't add/edit/remove)
--folder3(can't add/edit/remove)

Folders 2 & 3 are uploaded by admin user. It should inherit permission from folder1. Even in Ubuntu was something wrong.
I used ls -l command and folder 2 & 3 had "nogroup:nobody" tag. I've changed it to "www-data" but still I can do nothing in folders 2 & 3.
Same here:
https://github.com/owncloud/core/issues/9148

**Comment by PVince81** [comment]
You still haven't told us about what ownCloud version you use: https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

This looks like an environment/configuration issue, not an ownCloud bug.
Can't reproduce this issue with 9.1.4.

Make sure that your web server user is using the correct uid/gid, like "www-data". If the uploaded files appear as "nobody:nogroup" then something is wrong in your web server configuration.

If you need more detailed help to look at your setup, you can ask on https://central.owncloud.org/.

If after verifying all your settings and you still think it's a bug, please use the issue template and reopen. Thanks.
