### ISSUE TITLE
Email confirmation link can be manipulated

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27506]
### Steps

1. Go to personal page
1. Set email to "mycorrectemail@domain.tld"
1. Open mail client
1. Copy link
1. Edit link URL and change the email to "someoneelse@domain.tld"

### Expected result
No email address in the URL, just the token.

### Actual result
The email address from the URL is used.
Even worse, you can change the email address to an invalid one, it seems there is no validation.

@imujjwal96 sorry for not catching this earlier... Can you have a look ?

**Comment by PVince81** [comment]
I suggest to use a separate field in oc_preferences "pendingEmail" or something.
Then either copy it to the real field or delete it in case of token expiration.

**Comment by PVince81** [comment]
That is, unless this is common practice ? I just find it strange to have the email address directly there.

@Peter-Prochaska can you confirm that is it wrong ?

**Comment by PVince81** [comment]
Yeah it is indeed wrong. The whole purpose of email confirmation is to confirm that this one email is the correct one. If with the link I can set it to someone else's email, then the confirmation logic is useless because then I've set it to an unconfirmed email address.

**Comment by imujjwal96** [comment]
pendingEmail => <timestamp>:email@address.com

if the mailId in url matches the mail id in the table, then confirm it otherwise log an error.
Right?

**Comment by PVince81** [comment]
you don't need a mail id, you already have the token

**Comment by PVince81** [comment]
Basically remove the email from the URL completely. You have the token + user name which is enough information to resolve whatever you need from oc_preferences to change the email.

If the token is valid then the pending email from that token is validated.
If the token changes, pendingEmail must change too. (in case a re-reset is done)

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/issues/27509
