### ISSUE TITLE
FR: Make an app to to provide something similar to fail2ban

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#27507]
An app to block brute-force login attempts similar to fail2ban would be nice to have. Not as part of core but as an separate app.
 
Closing https://github.com/owncloud/core/issues/1580  in favor of this to to be able to follow up.

**Comment by ThomasDieckmann** [comment]
I'd like to have this. F2B is not really useful, but it's better than doing nothing. Now it's time for a final and charming solution. But block the account for a while, not the IP. You're blocking maybe many users, coming in via NAT. I guess, we're having problems with this....

**Comment by DeepDiver1975** [comment]
fixed in https://github.com/owncloud/security

**Comment by ThomasDieckmann** [comment]
How will this work? I don't just want to block an IP, but blocking a combination user/IP would make sense. So you can't simply make a DOS for a specific account. (Sorry for opening again....)

**Comment by karakayasemi** [comment]
It blocks an IP after certain failed login attempts.
You can configure;
Ban after how many failed login attempts?
Ban for how many seconds?

If you have any suggestion to improve the app, you are welcome. You can open an issue on the application github page.
