### ISSUE TITLE
[UX] Show error in case email confirmation mail not send due to recent send

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27505]
@imujjwal96 when trying to set an email address recently and putting the wrong one, I wanted to set the correct one afterwards. I was confused when it said "Email sent" because the log says it didn't send.

I think in this one specific situation it is ok to tell the user "No email was sent because you already sent one recently, please try again later". Because else the user might wait a long time but will never receive the email.

It's more of a user experience problem.

Can you adjust it ?

Thanks

**Comment by PVince81** [comment]
@imujjwal96 can you adjust it ? Or let us know so someone else can fix this

**Comment by imujjwal96** [comment]
Oh! Forgot about this issue. My apologies.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/issues/27586
