### ISSUE TITLE
Federation trusted ownClouds does not work with php5.5.9 and Ubuntu 14.04

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27515]
### Steps to reproduce

1. Set two oC servers with PHP 5.5.9 and Ubuntu 14.04
2. In each server add 'overwrite.cli.url' => parameter in config.php
3. Go to Admin -> Federation menu
4. Add the url of the other server

### Expected behaviour

Server appears as trusted server

### Actual behaviour

An error is shown

Note: It works with Ubuntu 16.04 and php 7.0

### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**

"9.1.4.2","versionstring":"9.1.4"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
trusted-servers","user":"admin"}
{"reqId":"sN+wiuTvyK5oHeawMs6h","remoteAddr":"82.159.139.58","app":"federation","message":"cURL error 60: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2017-03-28T09:14:27+00:00","method":"POST","url":"\/index.php\/apps\/federation\/trusted-servers","user":"admin"}
```

### Client configuration

**browser**

 Mozilla
![screen shot 2017-03-28 at 11 14 41](https://cloud.githubusercontent.com/assets/10596560/24399925/cd7d8732-13ae-11e7-9a69-a52545f900e5.png)

**Comment by DeepDiver1975** [comment]
did you test this with updated certificates as suggested by @tboerger ?

**Comment by davitol** [comment]
@DeepDiver1975 My certificates are updated.

![screen shot 2017-03-28 at 15 52 45](https://cloud.githubusercontent.com/assets/10596560/24408902/3bd4f484-13cf-11e7-8662-c16c69c50c76.png)

I use Let's encrypt certificates and I have already added to my docker containers. I think what @tboerger said was related to using the docker images he provides.

**Comment by DeepDiver1975** [comment]
no - @tboerger is talking about the certs as they are part of the system living in /etc/ssl/certs/ca-certificates.crt of the 'client' machine.

if those are outdated you can do nothing on the 'server' side.

**Comment by tboerger** [comment]
> I use Let's encrypt certificates and I have already added to my docker containers. I think what @tboerger  said was related to using the docker images he provides.

My suggestion is a general approach to use the ca certificates of the host system within any docker container.

**Comment by DeepDiver1975** [comment]
but even for an non-docker setup: update your certs ;-)

**Comment by davitol** [comment]
Finally the problem was solved and it was a due to my configuration. Let's Encrypt certs weren't validated by Ubuntu. Running the following script solved my problem:

```
#!/bin/bash
sudo curl https://letsencrypt.org/certs/isrgrootx1.pem.txt -o /usr/local/share/ca-certificates/isrgrootx1.crt
sudo curl https://letsencrypt.org/certs/letsencryptauthorityx1.pem.txt -o /usr/local/share/ca-certificates/letsencryptauthorityx1.crt
sudo curl https://letsencrypt.org/certs/letsencryptauthorityx2.pem.txt -o /usr/local/share/ca-certificates/letsencryptauthorityx2.crt
sudo curl https://letsencrypt.org/certs/lets-encrypt-x1-cross-signed.pem.txt -o /usr/local/share/ca-certificates/letsencryptx1.crt
sudo curl https://letsencrypt.org/certs/lets-encrypt-x2-cross-signed.pem.txt -o /usr/local/share/ca-certificates/letsencryptx2.crt
sudo curl https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem.txt -o /usr/local/share/ca-certificates/letsencryptx3.crt
sudo curl https://letsencrypt.org/certs/lets-encrypt-x4-cross-signed.pem.txt -o /usr/local/share/ca-certificates/letsencryptx4.crt
sudo dpkg-reconfigure ca-certificates
```

Thanks for your replies and sorry for the noise.

**Comment by tboerger** [comment]
That's why I suggested to use the certificates from the host system :)
