### ISSUE TITLE
Huge transaction in CLI scanner

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27516]
https://github.com/owncloud/core/blob/v9.1.4/lib/private/Files/Utils/Scanner.php#L216

If a user has lots of entries in their home storage, all of these will be put into a single huge transaction and only committed at the end.

Both the Propagator and the Database transaction (in redis locking mode) will have lots of data which risk running out of memory.

**Comment by PVince81** [comment]
One idea would be to make the scanner commit the DB transaction and the propagation batch every 10k or so entries.

For the DB transaction, the entries can be counted using the scanner events.
For the propagator, I suggest adding a method `setAutocommitAfter($entriesCount)` which will make the propagator instance automatically commit the batches after the given number of batched entries.

**Comment by PVince81** [comment]
@jvillafanez @DeepDiver1975 @butonic @mrow4a

**Comment by jvillafanez** [comment]
I don't know the code details, but we should analyze several things:
* Is it safe to commit in several batches? What could happend if something crash after commiting the first batch, can the system recover and avoid rescan everything?
* If the previous point is fine, what are the reasons to not commit each entry one by one? I guess it should perform worse but maybe we should verify.
* If we commit per batch of X entries, should we hardcode that number or make it configurable? is it worthy to make it configurable?
* What could happen if several scans are run at the same time? Is it worthy to take this into account (maybe the full scan could run faster)?
* Will committing per batch reduce the memory usage by itself? Is there any additional change needed?
* Will this also help scanning external storages?

**Comment by PVince81** [comment]
Great questions!

> Is it safe to commit in several batches? What could happend if something crash after commiting the first batch, can the system recover and avoid rescan everything?

From my understanding I think it should be safe. It's like scanning and the interrupting. Whatever was scanned so far is already stored in oc_filecache, the rest will be scanned afterwards because the scanner will recognize that the existing elements haven't changed.

> If the previous point is fine, what are the reasons to not commit each entry one by one? I guess it should perform worse but maybe we should verify.

I read somewhere that Mysql is much faster if you do batch inserts in a transaction instead of one by one.

> If we commit per batch of X entries, should we hardcode that number or make it configurable? is it worthy to make it configurable?

I'd say hardcode for now a sensible value that works well with 512mb ram (the htaccess default).

> What could happen if several scans are run at the same time? Is it worthy to take this into account (maybe the full scan could run faster)?

There is a special lock for the scanner in the locking code so I think it should prevent a scanner to scan a folder being scanned by another scanner concurrently. This is regardless of transactions.

On the point of transactions, please note that if "database locking" is used it will not use transactions at all and commit every insert directly. Only with redis it will use transactions. Not sure if this was a workaround for something.

> Will committing per batch reduce the memory usage by itself? Is there any additional change needed?

I think additional changes will be needed. Some reports were made about memory issues in 8.2 which got worse in 9.1. The "worse" part I suspect is due to the `Propagator` bit that was added after 8.2.
So once we solve the `Propagator` issue we'll likely bump against the other issues that existed already in 8.2.
I'm not convinced that committing DB transactions in batches will improve PHP memory usage, but it's worth a try.

> Will this also help scanning external storages?

I don't think it's relevant with external storages.

**Comment by PVince81** [comment]
One thing I also observed is that in 9.1 the scanner seems to be doing depth first scanning, probably an optimization for the propagator, while 8.2 does a breadth-first search.

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/core/pull/27527
