### ISSUE TITLE
Shared link's name is overwritten on edit if the same name is not provided on the body of the request

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/core#27517]
This is a follow-up of https://github.com/owncloud/client/issues/5658, reproduction steps with the Desktop client can be found there, as well as the reason behind this issue. 

### Server version: 
ownCloud version: 10.0 beta1 

### Steps to reproduce
```
curl -H 'Ocs-APIREQUEST:true' 
   -H 'Content-Type:application/x-www-form-urlencoded' 
   -H 'Authorization:Basic [...]' 
   -H 'User-Agent:Mozilla/5.0 (Macintosh) mirall/2.3.2-nightly20170328 (build 4154) (testpilotcloud)'
   -H 'Accept:*/*' 
   -H 'Cookie:oc_sessionPassphrase=[...]' 
   -H 'Content-Length:21' 
   -H 'Connection:Keep-Alive' 
   -H 'Accept-Encoding:gzip, deflate' 
   -H 'Accept-Language:en-US,*' 
   -H 'Host:server.tld' 
   -X PUT 'http://server.tld/ocs/v1.php/apps/files_sharing/api/v1/shares/1?format=json' 
   --data-binary 'expireDate=2017-04-13'
```

### Expected behavior
If the field `name` is not provided in the body of the request, it should not change. 

### Actual behavior
The default shared link's name is restored. 

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/24401615/59c7712a-13b5-11e7-9bd9-f43d296a84d7.gif"/>
</p>

**Comment by PVince81** [comment]
Ah yeah... pseudo-REST which is most a PATCH then a PUT.

I'll have a look, maybe the backend is reading "null" instead of skipping the field.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/27529
