### ISSUE TITLE
Move bundled apps to market

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27542]
The following apps are currently bundled in the ownCloud server community release.
Some apps come from the core repo, some from their own.

|app name|description|current repo|action|done?|
|---|---|---|---|---|
|activity|Activity app|separate|publish in market| ✔️  |
|comments|Comments GUI|core|publish in market?||
|configreport|Config Report|separate|keep||
|dav|DAV architecture|core|keep||
|encryption|Default encryption module + master key|core|publish in market|
|example-theme|Example theme|core||removed|
|external|External sites|separate|publish in market||
|federatedfilesharing|Federated file sharing|core|keep bundled, core depends on it and is always enabled||
|federation|Federation engine|core|removable, not sure||
|files|Files GUI|core|keep in core||
|files_antivirus|Antivirus|separate|publish in market|✔️|
|files_external|External storage backend + config GUI|core|keep for now, backends to be moved to separate repos/apps||
|files_pdfviewer|PDF viewer|separate|publish in market| ✔️ |
|files_sharing|Files sharing|core|keep in core, tightly coupled with core. New frontend from https://github.com/owncloud/files_sharing_fe will progressively replace old one||
|files_texteditor|Text editor|separate|publish in market| ✔️ |
|files_trashbin|Trashbin/Deleted files|core|?||
|files_versions|Versions|core|?||
|files_videoplayer|Video player|separate|?||
|firstrunwizard|First run popup|separate|publish in market||
|gallery|Gallery|separate|publish in market| ✔️ |
|notifications|Notification provider + indicator|separate|publish in market|  |
|provisioning_api|Provisioning API|core|keep||
|systemtags|System tags GUI|core|publish in market?||
|templateeditor|Email template editor|separate|publish in market|✔️|
|updatenotification|Web update notification|core|?||
|user_external|External user backends IMAP, SMB, CAS|separate|publish in market||
|user_ldap|LDAP user backend|separate|publish in market| ✔️ |

**Comment by PVince81** [comment]
To be "Done" an item must:
- be removed from the release script
- have a market entry
- have an initial released version in the market which is visible from inside ownCloud

**Comment by PVince81** [comment]
Trashbin and versions have some cross-dependencies between each other and also some core code depends on them. They can be disabled and OC might work fine though.
Not sure if that's a good enough reason to move these to the market.

**Comment by PVince81** [comment]
The files_sharing app can be disabled too, even removed. But some code pointing to the sharing app is hard-coded in core.

**Comment by DeepDiver1975** [comment]
i would suggest to keep core apps in the release - just because of simplicity reasons. just my 2 :cents:

**Comment by PVince81** [comment]
Ok, I did a local test on master and I removed ALL app code except the always_enabled ones:
- dav
- files
- federatedfilesharing

Surprisingly the platform still boots up 😄 

However I suspect that one might encounter small issues here and there for the apps that are referenced directly by core. It should be possible to quickly find these references and make them conditional to be able to have such minimal platform.

**Comment by PVince81** [comment]
@DeepDiver1975 so all apps that are already in the "core" repository stay bundled, and apps that are in separate repos go to the market ?

**Comment by DeepDiver1975** [comment]
yes - plus that we can ship apps from separate repos as well - e.g. market app

**Comment by VicDeo** [comment]
@PVince81 will unbundled apps still be marked as `shipped` in appinfo?

**Comment by PVince81** [comment]
I'd remove them from `shipped`. But if needed we could add a new temporary section to mark apps for transition.
The temp section could then be removed at the next major release once everybody migrated.

**Comment by PVince81** [comment]
user_ldap has already been moved out of the release due to issues. It's next release will be in the marketplace.

**Comment by PVince81** [comment]
@IljaN Any update ? What's the status ? (checkboxes...)

**Comment by PVince81** [comment]
Idea for moving out files and files_sharing: merge both apps into a single app "files".
Sharing backend / API is anyway already in core (OCS Share API).

To disable sharing, one can always use the existing checkbox in the admin page.

When moving the "files" app to the marketplace, it would then also contain the sharing UI stuff. This would solve the dependency that files_sharing has on files.

**Comment by PVince81** [comment]
It turns out files_sharing is doing too much:
- provides Storage instance for federated shares
- provides OCS Share API endpoints
- JS code for UI

One idea from @DeepDiver1975 is that we keep files_sharing in core as a pure backend app with no dependencies on the "files" app. Currently the only dependency I see is on the JS side, for example when buildling download URLs based on the files app routes. So we should only move this sharing related JS code to the "files" app.

**Comment by PVince81** [comment]
Any more apps to move out for 10.0.3 ?

I suggest we stop now and continue this for 10.0.4, moving to "planned"

**Comment by PVince81** [comment]
@IljaN @DeepDiver1975 we should continue this now

**Comment by PVince81** [comment]
the next I think would be good to look at, in order:
- notifications
- files_antivirus
- files_videoplayer
- templateeditor
- firstrunwizard

**Comment by PVince81** [comment]
- [ ] skeleton logic as app ? https://github.com/owncloud/core/issues/10728

**Comment by VicDeo** [comment]
**templateeditor** needs market release https://github.com/owncloud/templateeditor/issues/53
**notifications** needs market release https://github.com/owncloud/notifications/issues/112

**Comment by PVince81** [comment]
- [ ] move theme-example to the market as well

**Comment by PVince81** [comment]
or instead of https://github.com/owncloud/core/issues/27542#issuecomment-316318189 we could move the JS code from the files_sharing app into another app files_sharing_ui. This would make it possible to extend sharing UI through a marketplace app as much as the APIs allow.

**Comment by PVince81** [comment]
@VicDeo can you continue to prepare the unbundling of apps ? then we can queue them into the QA pipeline for later

**Comment by VicDeo** [comment]
@PVince81 we are unbundling templateeditor for over 3 months so far. Notifications are ready for the process as well.

**Comment by PVince81** [comment]
first run wizard, video player ?

**Comment by VicDeo** [comment]
firstrunwizard https://github.com/owncloud/firstrunwizard/pull/72

**Comment by PVince81** [comment]
@VicDeo yes, done by @patrickjahns so it will be removed in the 10.0.8 RC

**Comment by patrickjahns** [comment]
@VicDeo 
done with https://github.com/owncloud/administration-internal/pull/98

**Comment by PVince81** [comment]
moving to backlog. let's schedule explicitly what apps to process next

**Comment by PVince81** [comment]
The files_sharing app contains both frontend and backend components currently.
As part of the task in https://github.com/owncloud/core/issues/30779 we're rewriting the sharing frontend for phoenix (mostly share panel currently) and make it embeddable. This means that eventually the current "files_sharing" app will become a pure backend app while the frontend will like in a new app https://github.com/owncloud/files_sharing_fe

**Comment by jvillafanez** [comment]
I'm not sure about the responsabilities of each component then. Core is just acting as a hub of sharing providers? What will be the responsability of the files_sharing app?

Currently, I think the files_sharing app is providing a frontend for the sharing, as well as the sharing API. The shared storage is also provided by the app... but the default share provider is in core... This is really confusing.

One proposal could be:
* Share provider -> files_sharing
* API -> core
* Share provider hub -> core
* Shared storage -> ?? - I guess it will depend on the architecture. If it will be only one, I think it should be handled by core. The other option is that it handled by each app.
* Frontend -> sharing_frontend (or whatever you want to call it) that will use the API.

The problem in this case is that the frontend app will depend on another app.

I feel that, unless we come to an agreement about what components will be involved in sharing, how they will interact with each other, and where each component will be placed, it will become even more messy than what we have right now: both apps and core will need each other, so there is no real decoupling, and we'll also need to handle 2 apps and core, not just one app and core

**Comment by PVince81** [comment]
In the case of Phoenix which will be a separate frontend, we had a chat and I think we agreed that so far some apps will need to have two components: a backend app to install on the PHP server and a frontend app to install on the frontend. It is not clear yet how the dependency will be enforced.

**Comment by PVince81** [comment]
Next apps to address:
- encryption
- user_management

both already have a separate repo but aren't unbundled in stable10.

from what I heard user_management isn't ready yet as it causes regressions when removed from a core: https://github.com/owncloud/core/issues/31739
