### ISSUE TITLE
FYI: Wiki Page about Apps was deleted

### ISSUE THREAD

**Issue by kdslkdsaldsal** [owncloud/core#27545]
There was a nice wiki page about apps available here at the core wiki:

https://github.com/owncloud/core/wiki/Apps

Today i wondered why this page is gone and re-created that page. Now we can see, that this page got deleted by @github0809 for unknown reasons:

https://github.com/owncloud/core/wiki/Apps/_history

It seems this can happen at any time without any traces to the page.

**Comment by kdslkdsaldsal** [comment]
Just also reported an abuse about that user. Seems to be an spambot or similar.

But the main issue here is, that wiki pages can be just deleted even without contributor rights. That doesn't look good to me...

**Comment by DeepDiver1975** [comment]
Thanks for recreating it @kdslkdsaldsal - I changed the wiki rights - only people with push rights can edit the wiki from now on.

**Comment by kdslkdsaldsal** [comment]
> I changed the wiki rights - only people with push rights can edit the wiki from now on.

So github doesn't allow more fine granular permissions like allowing edit permissions but not deleting it?

And is there any other history in the backend of the wiki settings to see if any other page got deleted? This was just one i had in mind but maybe even more where deleted.
