### ISSUE TITLE
Failed upgrade from 8.2.10 to 9.0.8

### ISSUE THREAD

**Issue by hakatri** [owncloud/core#27552]
Hello all,

i am new here.

This is my first problem an owncloud told me to post the error here. If i am not right here, please  move. Thank you.

While upgrading my owncloud server manually from 8.2.10 to 9.0.8 i have got this error on the website below. Before i upgraded from 8.1.12 to 8.2.10 and there was no error. Everything was fine.

federation: An exception occurred while executing 'CREATE TABLE `oc_trusted_servers` (`id` INT AUTO_INCREMENT NOT NULL, `url` VARCHAR(512) NOT NULL COMMENT 'Url of trusted server', `url_hash` VARCHAR(255) DEFAULT '' NOT NULL COMMENT 'sha1 hash of the url without the protocol', `token` VARCHAR(128) DEFAULT NULL COMMENT 'token used to exchange the shared secret', `shared_secret` VARCHAR(256) DEFAULT NULL COMMENT 'shared secret used to authenticate', `status` INT DEFAULT 2 NOT NULL COMMENT 'current status of the connection', `sync_token` VARCHAR(512) DEFAULT NULL COMMENT 'cardDav sync token', UNIQUE INDEX url_hash (`url_hash`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_trusted_servers' already exists

--> 
### Steps to reproduce
1. stop webserver and maintenance mode in oc
2. move old owncloud dir
3. unpack owncloud dir to /owncloud
4. copy config.php (data is not in my owncloud file)
5. change ownership to www-data
6. start webserver and maintenace off
7. open the website to upgrade and got the error

### Expected behaviour
like the first upgrade i expected to see the login page

### Actual behaviour
while updating got the error above

### Server configuration
**Operating system**: Raspbian 8 jessie

**Web server:** Apache2

**Database:** mysql

**PHP version:** php 5.6

**ownCloud version:** 8.2.10.2

**Updated from an older ownCloud or fresh install:** Update from 8.2.10.2 to 9.0.8

**Where did you install ownCloud from:** https://download.owncloud.org/community/owncloud-9.0.8.tar.bz2

**Signing status (ownCloud 9.0 and above):**

**List of activated apps:**

Enabled:
  - comments: 0.2
  - configreport: 0.1.1
  - dav: true
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - activity
  - calendar
  - contacts
  - encryption
  - external
  - federation
  - files_antivirus
  - files_external
  - notifications
  - user_external
  - user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "53b67c23c3a02",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/media\/usb-hdd\/owncloud\/data",
        "dbtype": "mysql",
        "version": "8.2.10.2",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "192.168.1.9",
        ],
        "loglevel": 0,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": false,
        "trashbin_retention_obligation": "auto"
    },
    "apps": {
        "activity": {
            "enabled": "no",
            "installed_version": "1.1.23",
            "ocsid": "166038",
            "types": "filesystem"
        },
        "admin_migrate": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "3"
        },
        "bookmarks": {
            "enabled": "no",
            "installed_version": "0.4",
            "ocsid": "168710",
            "types": ""
        },
        "calendar": {
            "enabled": "no",
            "installed_version": "1.4.1",
            "ocsid": "168707",
            "signed": "true",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "configreport": {
            "enabled": "yes",
            "installed_version": "0.1.1",
            "types": "filesystem"
        },
        "contacts": {
            "enabled": "no",
            "installed_version": "1.5.1",
            "ocsid": "168708",
            "signed": "true",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "backgroundjobs_step": "queued_tasks",
            "backgroundjobs_task": "OC_Cache_FileGlobal-gc",
            "global_cache_gc_lastrun": "1490905862",
            "installedat": "1404468497.4743",
            "lastcron": "1490905983",
            "lastupdateResult": "{\"version\":\"9.0.8\",\"versionstring\":\"ownCloud 9.0.8\",\"url\":\"https:\\\/\\\/download.owncloud.org\\\/community\\\/owncloud-9.0.8.zip\",\"web\":\"https:\\\/\\\/doc.owncloud.org\\\/server\\\/9.0\\\/admin_manual\\\/maintenance\\\/upgrade.html\"}",
            "lastupdatedat": "0",
            "oc.integritycheck.checker": "[]",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "files_sharing\/publicwebdav.php",
            "remote_ampache": "media\/remote.php",
            "remote_caldav": "calendar\/appinfo\/remote.php",
            "remote_calendar": "calendar\/appinfo\/remote.php",
            "remote_carddav": "contacts\/appinfo\/remote.php",
            "remote_contacts": "contacts\/appinfo\/remote.php",
            "remote_contactthumbnail": "contacts\/thumbnail.php",
            "remote_core.css": "\/core\/minimizer.php",
            "remote_core.js": "\/core\/minimizer.php",
            "remote_files": "files\/appinfo\/remote.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_mozilla_sync": "mozilla_sync\/appinfo\/remote.php",
            "remote_webdav": "files\/appinfo\/remote.php",
            "repairlegacystoragesdone": "yes"
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0.10.2",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "files": {
            "backgroundwatcher_previous_file": "211",
            "backgroundwatcher_previous_folder": "208",
            "default_quota": "2 GB",
            "enabled": "yes",
            "installed_version": "1.4.4",
            "types": "filesystem"
        },
        "files_external": {
            "\/Dropbox": "1420310252",
            "\/FTP Marl": "1420664015",
            "\/FTP Minden": "1420664016",
            "\/FTP1": "1420658612",
            "\/FTPS Minden": "1420658775",
            "allow_user_mounting": "yes",
            "enabled": "no",
            "installed_version": "0.2.2",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "\\OC\\Files\\Storage\\FTP,\\OC\\Files\\Storage\\OwnCloud,\\OC\\Files\\Storage\\SFTP,\\OC\\Files\\Storage\\DAV"
        },
        "files_imageviewer": {
            "enabled": "no",
            "installed_version": "1.0",
            "types": ""
        },
        "files_odfviewer": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "14.5.0",
            "types": ""
        },
        "media": {
            "enabled": "no",
            "installed_version": "0.4.3",
            "types": ""
        },
        "mozilla_sync": {
            "enabled": "no",
            "installed_version": "1.4",
            "types": ""
        },
        "ojsxc": {
            "enabled": "no",
            "installed_version": "0.8.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction"
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.5.3",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "updater": {
            "bcd4cf4150b611f7a5d84fe7aa8e7600": "1",
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "user_migrate": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "168512": {
            "enabled": "no"
        }
    }
}

**Are you using external storage, if yes which one:** local usb-stick 64 gb sandisk ultrafit

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mozilla Firefox 52.0.2

**Operating system:** Win 10 Professional

#### Web server error log
```
[Sat Apr 01 18:01:16.802454 2017] [:error] [pid 1399] [client 192.168.1.37:59393] script '/var/www/owncloud/phpinfo.php' not found or unable to stat
[Sat Apr 01 18:11:08.248314 2017] [mpm_prefork:notice] [pid 1277] AH00169: caught SIGTERM, shutting down
[Sat Apr 01 18:20:00.149813 2017] [ssl:warn] [pid 2589] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Sat Apr 01 18:20:00.309982 2017] [ssl:warn] [pid 2590] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Sat Apr 01 18:20:00.321905 2017] [mpm_prefork:notice] [pid 2590] AH00163: Apache/2.4.10 (Raspbian) OpenSSL/1.0.1t configured -- resuming normal operations
[Sat Apr 01 18:20:00.322031 2017] [core:notice] [pid 2590] AH00094: Command line: '/usr/sbin/apache2'
[Sat Apr 01 18:33:50.336563 2017] [mpm_prefork:notice] [pid 2590] AH00169: caught SIGTERM, shutting down
[Sat Apr 01 18:40:27.549565 2017] [ssl:warn] [pid 2854] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Sat Apr 01 18:40:27.713134 2017] [ssl:warn] [pid 2855] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Sat Apr 01 18:40:27.725641 2017] [mpm_prefork:notice] [pid 2855] AH00163: Apache/2.4.10 (Raspbian) OpenSSL/1.0.1t configured -- resuming normal operations
[Sat Apr 01 18:40:27.725780 2017] [core:notice] [pid 2855] AH00094: Command line: '/usr/sbin/apache2'
[Sat Apr 01 18:54:58.817153 2017] [mpm_prefork:notice] [pid 2855] AH00169: caught SIGTERM, shutting down
[Sat Apr 01 19:00:17.107972 2017] [ssl:warn] [pid 3151] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Sat Apr 01 19:00:17.272299 2017] [ssl:warn] [pid 3152] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name
[Sat Apr 01 19:00:17.284755 2017] [mpm_prefork:notice] [pid 3152] AH00163: Apache/2.4.10 (Raspbian) OpenSSL/1.0.1t configured -- resuming normal operations
[Sat Apr 01 19:00:17.284895 2017] [core:notice] [pid 3152] AH00094: Command line: '/usr/sbin/apache2'

```

#### ownCloud log (data/owncloud.log)
```
cannot open this file
```

Thanks

**Comment by kdslkdsaldsal** [comment]
Looks like a duplicate of https://github.com/owncloud/core/issues/23867

**Comment by hakatri** [comment]
Thank you. I solved the problem by droping duplicated tables.
