### ISSUE TITLE
unvalid email alias possible

### ISSUE THREAD

**Issue by weberan96934** [owncloud/core#27551]
{"installed":true,"maintenance":false,"version":"9.1.4.2","versionstring":"9.1.4","edition":""}

In personal settings: Its possible to save an email like t@t.

**Comment by kdslkdsaldsal** [comment]
> In personal settings: Its possible to save an email like t@t.

Which is absolutely valid. There is no requirement in e-mail addresses that they need to contain a Top-Level-Domain. Those are e.g. complete valid e-mail addresses:

- admin@localhost
- admin@mailserver1

and your t@t complies with that as well.

**Comment by PVince81** [comment]
Starting with 10.0 email addresses need to be verified, so a token will be sent to the address.
