### ISSUE TITLE
Passing extra file metadata from storage implementation to UI

### ISSUE THREAD

**Issue by labkode** [owncloud/core#27569]
Hi,

in OC9 I see that basic file operations are handled by WebDAV calls.
The PROPFIND done to list directory contents ask for a particular set of properties.

What is the recommend way without patching the core to pass extra metadata from the storage implementation to the WebDAV endpoint so it can be used from the UI?

Cheers,
Hugo

**Comment by PVince81** [comment]
Write a Sabre plugin that populates the properties when requested: https://github.com/owncloud/core/blob/master/apps/dav/lib/Connector/Sabre/CommentPropertiesPlugin.php#L91
Register the Sabre plugin in info.xml (only supported in OC 10.0): https://github.com/owncloud/core/blob/master/apps/comments/appinfo/info.xml#L19
Write a JS side plugin to inject the property into the request, if needed: https://github.com/owncloud/core/blob/master/apps/comments/js/filesplugin.js#L63
