### ISSUE TITLE
Apps elements should not be affected by strings length.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#27564]
### Steps to reproduce:
1. Go to apps in settings section. 

### Expected behaviour:
All elements of the grid have the same space and are organised in the same way.

### Actual behaviour
Each element places its parts differently, depending on it's strings length.

![screen shot 2017-04-04 at 17 00 19](https://cloud.githubusercontent.com/assets/9048796/24663808/4722be4a-1959-11e7-82a3-4ad36af76536.png)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
Current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.0.3","versionstring":"10.0.0 alpha","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```


```
### Client configuration

Chrome

**Comment by felixheidecke** [comment]
This will be deprecated soon. See https://github.com/owncloud/market

**Comment by Dave-Melia** [comment]
I could tackle this with a bit of css if you want?

**Comment by PVince81** [comment]
No it won't. The apps page is still useful for offline instances that have no access to market.
That is, unless the market app allows you to manage local non-market apps...

moved to general design / UX / styling issues group ticket: https://github.com/owncloud/core/issues/27578
