### ISSUE TITLE
Make the UI complain if unsupported php_sapi_name is used

### ISSUE THREAD

**Issue by guruz** [owncloud/core#27560]
We know that fastcgi leads to problems, so complain about it in config UI.

https://doc.owncloud.com/server/9.1/admin_manual/installation/system_requirements.html#supported-platforms

**Comment by kdslkdsaldsal** [comment]
> We know that fastcgi leads to problems

This is a draft overview over the possible php_sapi_name return values:

> Although not exhaustive, the possible return values include aolserver, apache, apache2filter, apache2handler, caudium, cgi (until PHP 5.3), cgi-fcgi, cli, cli-server, continuity, embed, fpm-fcgi, isapi, litespeed, milter, nsapi, phttpd, pi3web, roxen, thttpd, tux, and webjames. 

-> https://secure.php.net/manual/en/function.php-sapi-name.php

Especially apache2filter might be checked here as well as this is known to block e.g. WebDAV methods needed for ownCloud (see https://github.com/owncloud/core/issues/23015).

**Comment by kdslkdsaldsal** [comment]
This could also warn people that stuff like https://github.com/owncloud/core/pull/27748 might happen at any time as long as no test for those other PHP module variants are done.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
