### ISSUE TITLE
Wrong PHP docs in getQueryBuilder() ->delete ?

### ISSUE THREAD

**Issue by ghost** [owncloud/core#27566]
Coming from https://github.com/Yetangitu/owncloud-apps/issues/43 we can see that the PHP docs at:

https://github.com/owncloud/core/blob/f10d105ea2f2d0822693313ddcd6f9b2eaac6ebe/lib/private/DB/QueryBuilder/QueryBuilder.php#L401

has a semicolon between the ``where`` and ``setParameter`` example code:

```
	 * <code>
	 *     $qb = $conn->getQueryBuilder()
	 *         ->delete('users', 'u')
	 *         ->where('u.id = :user_id');
	 *         ->setParameter(':user_id', 1);
	 * </code>
```

This shouldn't be there, right?

**Comment by DeepDiver1975** [comment]
> This shouldn't be there, right?

yes - this has to be killed - with :fire:

**Comment by kdslkdsaldsal** [comment]
But the example there is correct, only the semicolon shouldn't be there? I'm just asking because we're struggling to find the reasons why https://github.com/Yetangitu/owncloud-apps/issues/43 is working on PostgreSQL but not on MySQL.

**Comment by PVince81** [comment]
So, should remove the alias and the semicolon from the example code ?

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
