### ISSUE TITLE
Namespaced file operations

### ISSUE THREAD

**Issue by labkode** [owncloud/core#27572]
Currently in OC in the *All my files* tab both user owned files/folders are merged with shared resources from other users/groups at any level in the virtual tree.

When the number of shares is high the performance of the system degrades drastically to the fact of waiting several seconds to list a folder. The hack used in CERNBox to avoid mounting shared resources when they are not needed is to guess based on the URL and its parameters if the shared mounts must be mounted or not.

For such purpose, our user/group shares file target names are suffixed with a unique id that indicates that this mount point is a shared folder. 

In the hack, based on query parameters like ?path, ?file, ?dir etc... we decide to mount or not the shared file system. The hack can be found [here](https://github.com/cernbox/core/blob/cernbox-prod-8.2.2/apps/files_sharing/lib/mountprovider.php#L78)

We would like to have the possibility to scope user files and shared files based on the path.
Nowadays, owncloud uses the *files/* prefix for all files.
We would like to have something like *myfiles/* and *shared/* namespaces for mapping directly to a mount point without having to guess based on dirty hacks we have in place.

**Comment by PVince81** [comment]
talk with @mrow4a 

It sucks that OC needs to mount ALL mount points for any file operation even unrelated.
Needs a good rewrite of the FS layer especially the mount provider/manager part.

Potential approach here: https://github.com/owncloud/core/issues/26190.

**Comment by mrow4a** [comment]
@labkode Yep, this is exactly what I wanted to achieve recently, but it is a bit more complicated then for EOS, and to do it properly it might need some rewrite, but for OC10 it is already too late, so we just plaster bleeding wounds. Thanks for pointing the potential workaround!

**Comment by labkode** [comment]
@PVince81 @mrow4a  Great to know that we are aligned on this issue. Looking forward to see the advancements of this area.

I really like the idea of using a fstab-like approach.
For static mounts (system wide), this could be defined in the *config.php* file (ala */etc/fstab*)

For dynamic mounts (user created mounts, external storage) these could be created on the fly in the DB ( ala *mount -t ext4 -o ro  /dev/sda1 /mnt/myusb*).

Finally, these two mount specification files would merge into one central place, like *oc_mounts*, basically the way *nix does it with the */etc/mtab or /proc/mounts files*.

``` 
# in config.php
mounts => array(
  '/home' => array(
    'filesystemspec' = > '\OC\Storage\EosHomeStorage',
    'options' => 'rw'
  ),
  '/shared' => array(
    'filesystemspec' => '\OC\Storage\EosSharedStorage',
    'options' => 'rw'
  ),
  '/thumbnails' => array(
    'filesystemspec' => '\OC\Storage\LocalStorage',
    'options' => 'rw'
  ),
  ...
)
```

**Comment by PVince81** [comment]
No, we already had a mount.json file and it was a nightmare to manage, especially that the config is not searchable with DB queries.

All mounts to be stored in the DB and be managed by OCC commands like the external storage config ones. In this case one could still write a script if they fancy having their mounts in separate files...

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
Leaving closed in favor of https://github.com/owncloud/core/issues/26190. We need a proper mechanism to not mount stuff that is not in the current view/folder.

Another proposed approach was to have a cached view which would remove the need to resolve mount points every single time. @DeepDiver1975 was there any ticket about your view ideas ?
