### ISSUE TITLE
PHP 7.1 not supported error

### ISSUE THREAD

**Issue by stkjj** [owncloud/core#27570]
### Steps to reproduce
1. download fresh copy of owncloud 9.1.4 from owncloud.org
2. unzip and upload via FTP to server
3. point (sub)domain to uploaded folder, PHP 7.1.2 configured
4. start install by calling (sub)domain in browser

### Expected behaviour
First run screen to be expected, asking for admin-user credentials, DB-connect and Data-path

### Actual behaviour
see screenshot:
![bildschirmfoto 2017-04-05 um 14 46 07](https://cloud.githubusercontent.com/assets/832642/24706464/07cec27c-1a10-11e7-89e9-02aac3cb8d7f.jpg)

### Server configuration
unknown - shared hosting, debian 7 supposed

**Web server:**
unknown - shared hosting, apache2 supposed

**Database:**
MySQL 5.5.54-0

**PHP version:**
7.1.2

**ownCloud version:** (see ownCloud admin page)
9.1.4

**Updated from an older ownCloud or fresh install:**
fresh

**Where did you install ownCloud from:**
owncloud.org

**Comment by kdslkdsaldsal** [comment]
@stkjj Only ownCloud 10.0 is supporting PHP 7.1 as stated in the message, this is absolutely correct.

Or do i missing something here and whats the reason of your report?

**Comment by PVince81** [comment]
Works as designed.

cc @DeepDiver1975 if you want to emphasize

**Comment by stkjj** [comment]
I'm not running 7.1.3 but 9.1.4 the error message is wrong.

**Comment by PVince81** [comment]
I don't think it's worth spending time on this minor thing... but setting as junior job if anyone from the community wants to step up. Pretty sure the version must be read from PHP directly so not sure why PHP would report the wrong version...

**Comment by jvillafanez** [comment]
The wording might be confusing. The "You're currently running 7.1.3" message refers to the PHP version not ownCloud version. @stkjj please suggest a better wording.

This should be just changing the wording, nothing else.

**Comment by PVince81** [comment]
No, @stkjj says that his PHP version is 7.1.2, not 7.1.3. But the UI somehow detects 7.1.3.
Not sure why.

**Comment by kdslkdsaldsal** [comment]
@PVince81 I don't think that this is about PHP 7.1.2 vs. 7.1.3. The code is using the PHP_VERSION constant:

https://github.com/owncloud/core/blob/v9.1.4/index.php#L39

so that version can't be wrong (probably the hoster has updated from 7.1.2 to 7.1.3 or havn't updated the text in the admin backend).

This is more about that one might assume that the following text:

> You're currently running 7.1.3

refers to the ownCloud version and not the PHP version.

@stkjj Might be able to clarify.

**Comment by Lutacon** [comment]
I just try this bug with a docker image of php7.1.2 and it says:

> You are currently running 7.1.2. Please use at least ownCloud 10.0.0.

Like @kdslkdsaldsal  says it sound like your hosting update your php version. Could you check your installed PHP version?

**Comment by danger89** [comment]
Why is ownCloud server v10 not yet packaged? This should solve the problem. I created a new ticket for that: #28980.

**Comment by PVince81** [comment]
The previous message says "PHP 7.1" so reading both lines together does connect together.

Any volunteer to adjust the message ?

**Comment by Lutacon** [comment]
I will adjust the message to say "PHP" before the version number.
