### ISSUE TITLE
Core Errors concerning LDAP (bug?)

### ISSUE THREAD

**Issue by IngoEF** [owncloud/core#27582]
There are errors complaining missing UIDs of LDAP (AD) users but the users are not trying to authenticate. E.g. "reddoxx maildepot" shown in the owncloud-log is a contact object in our active directory.
Such sort of objects shouldn't have any relevance for authentication at all.
Even after deleting or moving the object from AD the error remains the same. Where is the wrong information pulled from?

How can I debug requests/responses in this case?

### Steps to reproduce
1. LDAP on / user authentication against active directory working
2. Errors like shown
3. as a side effect IOS clients claim "server in maintenance mode"

### Expected behaviour
no error messages

### Actual behaviour
Core Errors like:
Error while running background job (class: OCA\User_LDAP\Jobs\CleanUp, arguments: ): {"Exception":"InvalidArgumentException","Message":"uid for 'cn=reddoxx maildepot,cn=users,dc=vnwnr,dc=de' must not be an empty string!","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/User\/Manager.php(120): OCA\\User_LDAP\\User\\User->__construct('', 'cn=reddoxx mail...', Object(OCA\\User_LDAP\\Access), Object(OC\\AllConfig), Object(OCA\\User_LDAP\\FilesystemHelper), Object(OCP\\Image), Object(OCA\\User_LDAP\\LogWrapper), Object(OC\\AvatarManager), Object(OC\\User\\Manager))\n#1 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/User\/Manager.php(211): OCA\\User_LDAP\\User\\Manager->createAndCache('cn=reddoxx mail...', '')\n#2 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/User\/Manager.php(237): OCA\\User_LDAP\\User\\Manager->createInstancyByUserName('')\n#3 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/User_LDAP.php(211): OCA\\User_LDAP\\User\\Manager->get('')\n#4 [internal function]: OCA\\User_LDAP\\User_LDAP->userExistsOnLDAP('')\n#5 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/User_Proxy.php(67): call_user_func_array(Array, Array)\n#6 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/Proxy.php(139): OCA\\User_LDAP\\User_Proxy->walkBackends('', 'userExistsOnLDA...', Array)\n#7 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/User_Proxy.php(170): OCA\\User_LDAP\\Proxy->handleRequest('', 'userExistsOnLDA...', Array)\n#8 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/Jobs\/CleanUp.php(197): OCA\\User_LDAP\\User_Proxy->userExistsOnLDAP('')\n#9 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/Jobs\/CleanUp.php(188): OCA\\User_LDAP\\Jobs\\CleanUp->checkUser(Array)\n#10 \/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/Jobs\/CleanUp.php(142): OCA\\User_LDAP\\Jobs\\CleanUp->checkUsers(Array)\n#11 \/var\/www\/html\/owncloud\/lib\/private\/BackgroundJob\/Job.php(52): OCA\\User_LDAP\\Jobs\\CleanUp->run(NULL)\n#12 \/var\/www\/html\/owncloud\/lib\/private\/BackgroundJob\/TimedJob.php(53): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#13 \/var\/www\/html\/owncloud\/cron.php(122): OC\\BackgroundJob\\TimedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#14 {main}","File":"\/var\/www\/html\/owncloud\/apps\/user_ldap\/lib\/User\/User.php","Line":117}

And info messages like:
user_ldap	No or empty name for cn=replikator,cn=users,dc=vnwnr,dc=de.

### Server configuration
**Web server: Apache 2.4.6
**Database:mariadb 5.5.52
**PHP version:7.0.16
**ownCloud version:9.1.4.2
**Storage backend (external storage): SMB/CIFS
**Updated from an older ownCloud or fresh install: Fresh

**Where did you install ownCloud from: release depository

**Signing status (ownCloud 9.0 and above): 

No errors have been found.

**List of activated apps:
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - shareslist: 0.1
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_ldap: 0.9.0
Disabled:
  - calendar
  - contacts
  - disablerememberlogin
  - documents
  - encryption
  - external
  - files_antivirus
  - ownnote
  - pdflintview
  - richdocuments
  - user_external

**The content of config/config.php:**
{
    "system": {
        "updatechecker": false,
        "upgrade.disable-web": true,
        "instanceid": "oct50jc0rkfb",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.32",
            "cloud.vnw.de",
            "srv-owncloud.vnwnr.de"
        ],
        "datadirectory": "\/data\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.1.32",
        "dbtype": "mysql",
        "version": "9.1.4.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "CET",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",
        "mail_domain": "vnw.de",
        "mail_smtpport": "25",
        "theme": "vnw",
        "loglevel": 1,
        "log_rotate_size": "104857600",
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "ldapIgnoreNamingRules": false,
        "mail_smtphost": "srv-exchange.vnwnr.de",
        "appstore.experimental.enabled": true
    }
}

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** yno

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                  |
| hasPagedResultSupport         |                                                                                                                                    |
| homeFolderNamingRule          |                                                                                                                                    |
| lastJpegPhotoLookup           | 0                                                                                                                                  |
| ldapAgentName                 | CN=Read LDAP,OU=Spezielle_User,OU=VNW-Users,OU=VNW,DC=vnwnr,DC=de                                                                  |
| ldapAgentPassword             | ***                                                                                                                                |
| ldapAttributesForGroupSearch  |                                                                                                                                    |
| ldapAttributesForUserSearch   |                                                                                                                                    |
| ldapBackupHost                |                                                                                                                                    |
| ldapBackupPort                |                                                                                                                                    |
| ldapBase                      | DC=vnwnr,DC=de                                                                                                                     |
| ldapBaseGroups                | DC=vnwnr,DC=de                                                                                                                     |
| ldapBaseUsers                 | DC=vnwnr,DC=de                                                                                                                     |
| ldapCacheTTL                  | 600                                                                                                                                |
| ldapConfigurationActive       | 1                                                                                                                                  |
| ldapDynamicGroupMemberURL     |                                                                                                                                    |
| ldapEmailAttribute            |                                                                                                                                    |
| ldapExperiencedAdmin          | 0                                                                                                                                  |
| ldapExpertUUIDGroupAttr       |                                                                                                                                    |
| ldapExpertUUIDUserAttr        |                                                                                                                                    |
| ldapExpertUsernameAttr        | samAccountname                                                                                                                     |
| ldapGroupDisplayName          | cn                                                                                                                                 |
| ldapGroupFilter               | (|(cn=V1_Allgemein)(cn=AL_Allgemein))                                                                                              |
| ldapGroupFilterGroups         | V1_Allgemein;AL_Allgemein                                                                                                          |
| ldapGroupFilterMode           | 0                                                                                                                                  |
| ldapGroupFilterObjectclass    |                                                                                                                                    |
| ldapGroupMemberAssocAttr      | member                                                                                                                             |
| ldapHost                      | srv-daten.vnwnr.de                                                                                                                 |
| ldapIgnoreNamingRules         |                                                                                                                                    |
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(|(memberof=CN=Domänen-Benutzer,CN=Users,DC=vnwnr,DC=de)(primaryGroupID=513))))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                                    |
| ldapLoginFilterEmail          | 0                                                                                                                                  |
| ldapLoginFilterMode           | 0                                                                                                                                  |
| ldapLoginFilterUsername       | 1                                                                                                                                  |
| ldapNestedGroups              | 0                                                                                                                                  |
| ldapOverrideMainServer        |                                                                                                                                    |
| ldapPagingSize                | 500                                                                                                                                |
| ldapPort                      | 389                                                                                                                                |
| ldapQuotaAttribute            |                                                                                                                                    |
| ldapQuotaDefault              |                                                                                                                                    |
| ldapTLS                       | 0                                                                                                                                  |
| ldapUserDisplayName           | displayName                                                                                                                        |
| ldapUserDisplayName2          |                                                                                                                                    |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=Domänen-Benutzer,CN=Users,DC=vnwnr,DC=de)(primaryGroupID=513))))                         |
| ldapUserFilterGroups          | Domänen-Benutzer                                                                                                                   |
| ldapUserFilterMode            | 0                                                                                                                                  |
| ldapUserFilterObjectclass     | person                                                                                                                             |
| ldapUuidGroupAttribute        | auto                                                                                                                               |
| ldapUuidUserAttribute         | auto                                                                                                                               |
| turnOffCertCheck              | 0                                                                                                                                  |
| useMemberOfToDetectMembership | 1                                                                                                                                  |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------+

### Client configuration
**Browser: IE, Firefox

Windows 10

#### Web server error log
[Sun Apr 02 08:35:26.997888 2017] [cgi:error] [pid 23061] [client 51.15.141.187:49616] script not found or unable to stat: /var/www/cgi-bin/user
[Mon Apr 03 00:28:03.401922 2017] [cgi:error] [pid 23070] [client 191.96.249.97:59753] script not found or unable to stat: /var/www/cgi-bin/php
[Mon Apr 03 20:43:43.653791 2017] [cgi:error] [pid 480] [client 185.58.193.210:60295] script not found or unable to stat: /var/www/cgi-bin/php
[Mon Apr 03 20:43:45.702071 2017] [cgi:error] [pid 471] [client 185.58.193.210:61391] script not found or unable to stat: /var/www/cgi-bin/php5
[Mon Apr 03 20:44:29.165658 2017] [:error] [pid 471] [client 185.58.193.210:50372] script '/var/www/html/owncloud/wp-login.php' not found or unable to stat
[Tue Apr 04 16:46:28.154871 2017] [:error] [pid 1308] [client 179.210.133.189:36566] script '/var/www/html/owncloud/command.php' not found or unable to stat
[Wed Apr 05 14:13:13.876498 2017] [cgi:error] [pid 1308] [client 191.96.249.97:59008] script not found or unable to stat: /var/www/cgi-bin/php

#### ownCloud log (data/owncloud.log)
{"reqId":"WOYz4QC1qIm0EpHSFyOwuAAAAAE","remoteAddr":"62.112.34.74","app":"files_external","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"Invalid login\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php(279): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->getFileInfo('\\\/')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(436): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->stat('')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php(616): OC\\\\Files\\\\Storage\\\\Common->test()\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(231): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->test(false, true)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(253): OC_Mount_Config::getBackendStatus('\\\\\\\\OCA\\\\\\\\Files_Exte...', Array, false, true)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(303): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_External\\\\Lib\\\\StorageConfig), true)\\n#6 [internal function]: OCA\\\\Files_External\\\\Controller\\\\StoragesController->show(4, true)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'show')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Files_Exter...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php\",\"Line\":172}","level":3,"time":"2017-04-06T13:26:09+01:00","method":"GET","url":"\/index.php\/apps\/files_external\/globalstorages\/4?testOnly=true","user":"ocadmin"}
{"reqId":"WOYz4thJh-9zo1ZVPMZTAwAAAAk","remoteAddr":"62.112.34.74","app":"files_external","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"Invalid login\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php(279): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->getFileInfo('\\\/')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(436): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->stat('')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php(616): OC\\\\Files\\\\Storage\\\\Common->test()\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(231): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->test(false, true)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(253): OC_Mount_Config::getBackendStatus('\\\\\\\\OCA\\\\\\\\Files_Exte...', Array, false, true)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/GlobalStoragesController.php(177): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_External\\\\Lib\\\\StorageConfig), true)\\n#6 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->update(4, 'Referate', 'smb', 'password::sessi...', Array, Array, Array, Array, 100, true)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Files_Exter...', 'update', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php\",\"Line\":172}","level":3,"time":"2017-04-06T13:26:11+01:00","method":"PUT","url":"\/index.php\/apps\/files_external\/globalstorages\/4","user":"ocadmin"}
{"reqId":"WOYz43rlkRCKF1PC86GjEQAAAAg","remoteAddr":"62.112.34.74","app":"files_external","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"Invalid login\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php(279): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->getFileInfo('\\\/')\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(436): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->stat('')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php(616): OC\\\\Files\\\\Storage\\\\Common->test()\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/config.php(231): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\SMB->test(false, true)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(253): OC_Mount_Config::getBackendStatus('\\\\\\\\OCA\\\\\\\\Files_Exte...', Array, false, true)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/GlobalStoragesController.php(177): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_External\\\\Lib\\\\StorageConfig), true)\\n#6 [internal function]: OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController->update(5, 'Allgemein', 'smb', 'password::sessi...', Array, Array, Array, Array, 100, true)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\GlobalStoragesController), 'update')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Files_Exter...', 'update', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#11 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#15 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/SMB.php\",\"Line\":172}","level":3,"time":"2017-04-06T13:26:11+01:00","method":"PUT","url":"\/index.php\/apps\/files_external\/globalstorages\/5","user":"ocadmin"}
{"reqId":"6HSanMO6ooXpa6+jFVhd","remoteAddr":"","app":"user_ldap","message":"Looking for cookie L\/O 500\/0","level":1,"time":"2017-04-06T13:30:16+01:00","method":"--","url":"--","user":"--"}
{"reqId":"6HSanMO6ooXpa6+jFVhd","remoteAddr":"","app":"user_ldap","message":"No paged search for us, Cpt., Limit 500 Offset 500","level":1,"time":"2017-04-06T13:30:16+01:00","method":"--","url":"--","user":"--"}
{"reqId":"6HSanMO6ooXpa6+jFVhd","remoteAddr":"","app":"user_ldap","message":"Paged search was not available","level":1,"time":"2017-04-06T13:30:17+01:00","method":"--","url":"--","user":"--"}
{"reqId":"6HSanMO6ooXpa6+jFVhd","remoteAddr":"","app":"no app in context","message":"Invalidating tokens older than 2017-04-05T12:30:22+00:00","level":1,"time":"2017-04-06T13:30:22+01:00","method":"--","url":"--","user":"--"}
{"reqId":"6HSanMO6ooXpa6+jFVhd","remoteAddr":"","app":"user_ldap","message":"No or empty name for cn=replikator,cn=users,dc=vnwnr,dc=de.","level":1,"time":"2017-04-06T13:30:22+01:00","method":"--","url":"--","user":"--"}

#### Browser log
n/a

**Comment by PVince81** [comment]
@jvillafanez please evaluate

**Comment by jvillafanez** [comment]
> "reddoxx maildepot" shown in the owncloud-log is a contact object in our active directory.

It is being pulled from the LDAP filters. If it's a person and it's in your target group, it will appear. Maybe you should refine the filter and use *(objectClass=user)* or something similar.

**Comment by IngoEF** [comment]
thanks for the answer.

You mean something like:
![administration-cloud](https://cloud.githubusercontent.com/assets/26598336/24801070/f99d3ba4-1ba2-11e7-9f48-c4c0f951e0d4.png)

?

**Comment by IngoEF** [comment]
I've changed the filters (occ ldap:show-config):

[ldapconfig.txt](https://github.com/owncloud/core/files/905822/ldapconfig.txt)

But the error remains.

**Comment by jvillafanez** [comment]
Could you verify the LDAP information about the "reddoxx maildepot"?

I guess ownCloud could be trying to access to the information about that user in order to check if it has been deleted (or can be considered as deleted, if the user isn't in the filters any longer) from the LDAP, and since the LDAP information might be incomplete, it crashes.

I think the easiest and less intrusive thing we can do for now is to fill the information we need for the user in the LDAP server.

**Comment by IngoEF** [comment]
"reddoxx maildepot" is a contact object in the active directory. Normally such objects have no UID.
Even after temporarily deleting from AD the error remains.

Any other ideas?

**Comment by IngoEF** [comment]
How can I simulate an owncloud LDAP-request and see the answer for debugging?

**Comment by jvillafanez** [comment]
If the "reddoxx maildepot" user isn't in LDAP any longer, remove it from the ldap_user_mapping table and update the groups the user belonged to.

**Comment by IngoEF** [comment]
In AD the object is not member of objectclasses "user" or "person". You find it when asking for objectclass="contact".
In owncloud the user is not listed in any group including "Everyone".

Using 
~]> occ ldap:check-user "reddoxx maildepot" 
results in
"The given user is not a recognized LDAP user"

Why is owncloud complaining this object?

How can I debug?

**Comment by jvillafanez** [comment]
ownCloud has data stored about that AD user. In order to check if that AD user still exists or has been removed, ownCloud needs to create a PHP object and use that object to connect to AD and fetch whatever it needs.
The problem is that the data stored in ownCloud is damaged / broken / incomplete, and the PHP object can't be created, and is crashing.

I don't know how that AD user reached ownCloud, but you can check it's there in the ownCloud's DB.

**Comment by IngoEF** [comment]
Thanks for your advice.
Taking a look at the two relevant error messages I still don't understand the issue because none of them has anything to do with user authentication against actice directory.
I think, after building the LDAP configuration a third time with resetting users and groups the first message stopped.
The second message was the info messages like:
user_ldap No or empty name for cn=replikator,cn=users,dc=vnwnr,dc=de.
Watching the owncloud-log it appeared every time when the GUI displayed all goup members belonging to one of the group filters. The user object mentioned in the info message was dectivated.
You won't believe: after deleting this object from the concerned group all errors disappeared.
Even IOS-Clients discontinued their "server in maintenace mode" message and can use this owncloud instance as they should.
For me the LDAP module still seems buggy because
1. it doesn't use given filters the right way (neither objectclasses nor group memberships)
2. it seems to run in errors or crashes when it finds deactivated users in active directory groups

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
Please reopen in [user_ldap app repo](https://github.com/owncloud/user_ldap/issues) if the problem persists with 10.0.4 and the latest user_ldap app.
