### ISSUE TITLE
Feature Request / Question - Show (live) user activity

### ISSUE THREAD

**Issue by BornToBeRoot** [owncloud/core#27589]
Is it possible to show user activity?

- How many users are currently logged in
- Traffic? (Download/Upload)
- Maybe statistic for the last 7 days

I currently look into the ssl_access_log to determine if there is any activity.

**Comment by PVince81** [comment]
There is no such feature currently. Tagging as enhancement.

Someone could write an app that uses the hooks and APIs to gather this information.

**Comment by BornToBeRoot** [comment]
How about this?

https://github.com/nextcloud/serverinfo

**Comment by cdamken** [comment]
https://apps.owncloud.com/content/show.php/Server+info?content=174795

**Comment by BornToBeRoot** [comment]
Thanks, i found it a while ago while updating to NC11. I know there are not all features yet available, but it is a start.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
@pmaier1
