### ISSUE TITLE
mimetype:update-db changes a folder to "audio/*"

### ISSUE THREAD

**Issue by Rello** [owncloud/core#27585]
### Steps to reproduce
1. create a folder "WAV"
2. check filecache: mimetype 1 (unix directory)
3. execute `occ  maintenance:mimetype:update-db --repair-filecache`
4. check filecache: mimetype "audio/wav"

### Expected behaviour
nothing bad

### Actual behaviour
a folder becomes an audio file

### Server configuration
**Operating system**:
Debian
**Web server:**
nginx
**Database:**
mariadb
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
9.1.4

**Comment by PVince81** [comment]
I guess the mimetype code needs to first verify whether the target is actually a file.

@Rello do you have time to dig into this ?

**Comment by Rello** [comment]
@PVince81 I think I this is the related part
https://github.com/owncloud/core/blob/f10d105ea2f2d0822693313ddcd6f9b2eaac6ebe/lib/private/Files/Type/Loader.php#L160-L169

it does a plain find by `like LOWER(`name`)` and there, even a folder /WAV will be changed.
how to approach this?
by excluding folders in general you don´t have the possibility to change the global folder-mime-type anymore. but compared to this issue, this should be neglected.

do you agree?

the simplest solution would be to exclude the mimetype completely from processing
`"httpd/unix-directory": "dir",`

**Comment by PVince81** [comment]
Excluding the directory mimetype in that query sounds like a good plan.

**Comment by Rello** [comment]
I will create a pull

**Comment by PVince81** [comment]
thanks a lot!

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
this was fixed through https://github.com/owncloud/core/pull/27668
