### ISSUE TITLE
Single login endpoint

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27588]
Not sure if we had this ticket before.

We need to have a single location for logging in instead of having every possible endpoint being able to authenticate. One exception is Webdav because some clients need to be able to send basic auth, so fine.

But external apps that use REST APIs or so need to use a main endpoint.
That endpoint at some point might also be an OAuth2 one.

Goal here is to remove all the other code paths that allowed to send basic auth to private APIs, OCS Share API, etc.

Thoughts ?

@DeepDiver1975 @butonic @phisch @guruz @davivel

**Comment by davivel** [comment]
@PVince81 , mobile apps always start session from WebDAV. As long as a session cookie got there keeps being valid in all the endpoints, this would be total transparent for us. 

I understand that I would make life for server devs much easier, so: go for it.

**Comment by guruz** [comment]
> mobile apps always start session from WebDAV 

not from capabilities?

**Comment by PVince81** [comment]
@DeepDiver1975 is this still a target we're looking at ?

Now we likely already have the oauth endpoint and we'll soon have a nonce endpoint.
