### ISSUE TITLE
Understanding Pending state

### ISSUE THREAD

**Issue by glannes31** [owncloud/core#27592]
Hello  everybody ,

I want to understand why  ,on the Web UI , Pending is displayed instead of the folder's size.

What are the criteria of this  display?

FYI : External shares is not enabled on our server.

Thanks

**Comment by kdslkdsaldsal** [comment]
@glannes31 Please note that this is a bugtracker for ownCloud. If you have specific questions to the functionality of ownCloud please use https://central.owncloud.org/ for these.

**Comment by glannes31** [comment]
@kdslkdsaldsal  Sorry for this . Issue closed
