### ISSUE TITLE
Change name of 'local/permanent link' to 'private link'

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#27593]
To enhance usability and ease-of-use we decided to change the name of the feature to 'private link' as it reflects better that you need access, doesn't necessarily exclude other users and fits with public links.

- [ ] Change the name as discussed
- [ ] Maybe display some hint: e.g. "Private link: Only people who have access to the file/folder can use it. Use it as a permanent link for yourself or to point others to files or folders within shares"

@PVince81

**Comment by PVince81** [comment]
sounds good. need to find a good location for the hint

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/27594
