### ISSUE TITLE
Wrong quota displayed in user management

### ISSUE THREAD

**Issue by Gomez** [owncloud/core#27608]
### Steps to reproduce
1. Create several user / groups (https://gist.github.com/Gomez/b6f9418c09c025ece317a0d53876bb0f)
2. Open IE11 and switch to user mgmt. In "Everyone" change the 3 first user quotas to 5 GB
3. Jump to the first group - Every user has 5 GB quota now
4. Jump back to "Everyone" - Every user has 5 GB quota now
5. A hard reload fixes the behaviour

### Expected behaviour
**It worked in ownCloud 8.2.x**
**Works in Firefox / Chrome ...**
Freely jump between groups, the quota should shown correctly 

### Server configuration
**Operating system**: Debian Linux

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** ownCloud 10 Beta & 9.0.9 RC1

**Updated from an older ownCloud or fresh install:** Fresh

**Comment by PVince81** [comment]
I noticed another issue:
1. Create users and let quota set to "Unlimited"
1. Set a default quota on the bottom left to "5 MB"
1. Refresh the page: now everyone has 5 MB displayed.
1. Change default quota to 10MB, refresh
1. Now everyone has 10 MB displayed.

This is wrong.

Issue 1: I'd expect that only users who have the value "Default" selected, not "Unlimited" to have their quota influenced by the default value. If someone has the value "Unlimited" then it's not a default and they should have unlimited (overrules default value).

Issue 2: I'd expect all users to have the quota set to "Default" when created

cc @pmaier1 for the conceptual part

**Comment by PVince81** [comment]
possibly related https://github.com/owncloud/core/issues/27803

cc @davitol

**Comment by PVince81** [comment]
check if this PR fixes the issue https://github.com/owncloud/core/pull/27895

**Comment by PVince81** [comment]
please retry with 10.0.1 RC1
