### ISSUE TITLE
Can not access web interface - Error 500

### ISSUE THREAD

**Issue by mpmario** [owncloud/core#27600]
I can not load the web interface. The client ios-app can not connect to the server. I can not use the maintenance tool from owncloud. Every time the same error: 
PHP Fatal error:  Class 'OC\Cache\CappedMemoryCache' not found in /var/www/owncloud/lib/private/AllConfig.php on line 70
Since the last update I changed nothing at the system. Suddenly the error happens.
Has anyone an idea?
Thank you!

### Steps to reproduce
1. go to the website: mydomain.com/owncloud

### Expected behaviour
The normal web interface should appear

### Actual behaviour
HTTP ERROR 500

### Server configuration
Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

**Web server:**
Apache/2.4.10 (Raspbian)

**Database:**
mysql

**PHP version:**
PHP Version 5.6.29-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
9.1.4.2

**Updated from an older ownCloud or fresh install:**
update from 9.1 (?)

**Where did you install ownCloud from:**
repository

**Signing status (ownCloud 9.0 and above):**
unknown

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
not possible
```

**List of activated apps:**
calender, contacts, ownbackup

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder

PHP Fatal error:  Class 'OC\Cache\CappedMemoryCache' not found in /var/www/owncloud/lib/private/AllConfig.php on line 70
```

**The content of config/config.php:**
  'updatechecker' => false,
  'instanceid' => 'XXXXX',
  'passwordsalt' => 'XXXXX',
  'secret' => 'XXXX',
  'trusted_domains' =>
  array (
    0 => 'raspberrypi',
    1 => 'mydomain.com',
  ),
  'datadirectory' => '/media/ownclouddrive/',
  'overwrite.cli.url' => 'https://mydomain.com/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.4.2',
  'dbname' => 'clouddata',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'XXXX',
  'logtimezone' => 'Europe/Berlin',
  'installed' => true,
  'mail_from_address' => 'mp',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'XXXX',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'XXXX',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'XXXX',
  'mail_smtppassword' => 'XXXX',
  'mail_smtpsecure' => 'tls',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'logfile' => '/var/log/owncloud.log',
  'log_rotate_size' => 104857600,
  'debug' => false,
);

**Are you using external storage, if yes which one:**
No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:** chrome or firefox, same behaviour

#### Web server error log
```
[Fri Apr 07 14:55:37.277904 2017] [:error] [pid 1969] [client 137.226.66.4:40525] PHP Fatal error:  Class 'OC\\Cache\\CappedMemoryCache' not found in /var/www/owncloud/lib/private/AllConfig.php on line 70
```

#### ownCloud log (data/owncloud.log) (Not relevant)
```
{"reqId":"jrp63ix25PvcPdN\/d57\/","remoteAddr":"77.181.245.45","app":"core","message":"Login failed: '(null)' (Remote IP: '77.181.245.45')","level":2,"time":"2017-03-28T08:58:33+02:00","method":"GET","url":"\/owncloud\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/shares","user":"--"}
```

**Comment by PVince81** [comment]
how did you update ?
try clearing the APCu cache if you have one.

it looks like the source code was not replaced correctly during the update or PHP still has a partially cached version of the old source.

**Comment by mpmario** [comment]
Thank you for your answer!
I updated via repository "apt-get update && apt-get upgrade"
But directy after that, it works. A few weeks later, i mentioned this problem.

I cleared the cache via 
```
php -r "apc_clear_cache();"
php -r "apc_clear_cache('user');"
service apache2 restart
```
No other behavior.

**Comment by PVince81** [comment]
Did you ask on https://central.owncloud.org/ ? This is likely a problem related to your environment, not a bug in ownCloud.

**Comment by kdslkdsaldsal** [comment]
@PVince81 Most likely the same caching issue as seen in e.g. https://github.com/owncloud/core/issues/27600

**Comment by mpmario** [comment]
Unfortunately I still can not access my server, although I cleared the APCu-Cache.
Is it save to do a
```
$ sudo apt-get purge owncloud
$ sudo apt-get purge owncloud-*
$ sudo apt-get autoremove
$ sudo apt-get install owncloud
```
? Can I do something else?
