### ISSUE TITLE
OC10: regression with custom sharing provider

### ISSUE THREAD

**Issue by labkode** [owncloud/core#27617]
When using our custom sharing manager factory:
```
'sharing.managerFactory' => 'OC\\CernBox\\Share\\ProviderFactory',
```
 ownCloud returns 500 error with following log line message:

```
{"reqId":"WOyOsv@Wx9-EDjb9ySZFSgAAAAo","remoteAddr":"128.141.150.68","app":"no app in context","message":"CSRF check failed","level":0,"time":"2017-04-11T08:07:14+00:00","method":"GET","url":"\/index.php\/apps\/files_sharing\/api\/externalShares","user":"gonzalhu"}
```

**Comment by PVince81** [comment]
CSRF check failed? Sometimes that message happens due to infinite recursions.

Can you debug the the code and provide more info ? So far that's not enough info to be able to provide help.

**Comment by PVince81** [comment]
another option is bisecting to find out what commit broke it

**Comment by PVince81** [comment]
closing, not enough info.

**Comment by labkode** [comment]
Hello,

we don't have time now for debugging these kind of regressions.

Please leave the issue open so we do not forget about it.

**Comment by moscicki** [comment]
@PVince81: how do you actually test "pluggability" with your interfaces such as sharing.managerFactory? You must surely have a simple mockup class for testing which proves that something else than a default, legacy implementation can be plugged in? 

We have seen before (https://github.com/owncloud/core/issues/26607) that your system is not properly separated into independent components and you have implicit dependencies which violate the interfaces.

**Comment by PVince81** [comment]
As far as I know there are currently no proper tests for pluggability.

Ideal would probably be to have a test instance with a custom sharing manager / storage implementations that runs in a separate test suite.

Most of the refactored Sharing v2 components should already be decoupled as much as possible. The remaining code that was discovered is from Sharing v1 and is mostly unused. Needs clean up.

Note that Sharing and FS need to be implemented together, these two components cannot be separated. This means that the current sharing code can use filecache and if someone reimplements the filecache logic they also need to reimplement that matching sharing part.

@DeepDiver1975

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
