### ISSUE TITLE
Cannot create any external storage without local flag

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27619]
### Steps

1. Setup OC from scratch
1. Setup a SFTP storage as admin

### Expected
Storage can be setup.

### Actual
403 forbidden exception.

### Version
ownCloud 10.0 beta2

It only works if `files_external_allow_create_new_local` is set to `true` in the config.

This flag is only supposed to prevent creation of **Local** storages.

@noveens do you have time to fix this critical regression ?

**Comment by noveens** [comment]
@PVince81 , on it.
