### ISSUE TITLE
Password forgotten usability issues

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27612]
1) Password forgotten page must automatically log out. If you were logged in as another user it would redirect you to that other user's account, which is confusing.
2) Field must auto-focus when opening password forgotten page
3) Hitting enter must save without having to click (might work already)
4) Redirect to login page with prefilled login ?

**Comment by imujjwal96** [comment]
Hey @PVince81 I am working on this issue and got stuck at a place. the function that sets user's password (`/core/Controller/LostController.php->setPassword()`) returns  `$this->success()`

How does this redirect the user to the login page?

**Comment by DeepDiver1975** [comment]
> How does this redirect the user to the login page?

did you have a look at the frontend code? maybe the redirect happens in the js code

**Comment by imujjwal96** [comment]
Oh! Found it. Thanks a lot
