### ISSUE TITLE
How to allow local php/html file accessing image files in owncloud directory

### ISSUE THREAD

**Issue by Alf21** [owncloud/core#27614]
### Steps to reproduce
1. I created a php script that scans a dir and its subduers for image files
2. all these image files are includes in the php file and extracted into a generated html file

i thought about adding my php file to the dir in .htaccess of owncloud dir. Could it work?
```
<IfModule mod_rewrite.c>
  RewriteEngine on
  RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
  RewriteRule ^\.well-known/host-meta /public.php?service=host-meta [QSA,L]
  RewriteRule ^\.well-known/host-meta\.json /public.php?service=host-meta-json $
  RewriteRule ^\.well-known/carddav /remote.php/dav/ [R=301,L]
  RewriteRule ^\.well-known/caldav /remote.php/dav/ [R=301,L]
  RewriteRule ^remote/(.*) remote.php [QSA,L]
  RewriteRule ^(?:build|tests|config|lib|3rdparty|templates)/.* - [R=404,L]
  RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge/.*
  RewriteRule ^(?:\.|autotest|occ|issue|indie|db_|console).* - [R=404,L]
</IfModule>
<IfModule mod_mime.c>
  AddType image/svg+xml svg svgz
  AddEncoding gzip svgz
</IfModule>
<IfModule mod_dir.c>
  DirectoryIndex index.php index.html
</IfModule>
```

### Expected behavior
The images should be displayed

### Actual behavior
The images can't be found or displayed because i don't have the permissions to access these files

### Server configuration
**Operating system**:
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie

**Web server:**
Server version: Apache/2.4.10 (Debian)
Server built:   Feb 24 2017 18:40:28

**Database:**
mysql 5.5.54

**PHP version:**
PHP > 5.6.30

**ownCloud version:** (see ownCloud admin page)
https://download.owncloud.org/community/owncloud-9.1.4.zip -> 9.1.4

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
From owncloud.org

**Signing status (ownCloud 9.0 and above):**
? (no errors)

**List of activated apps:**
? (not important)

**The content of config/config.php:**
? (again not relevant)

**Are you using external storage, if yes which one:** local/smb/sftp/...
...
**Are you using encryption:** yes/no
...
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
...
#### LDAP configuration (delete this part if not used)
...
### Client configuration
**Browser:**
...
**Operating system:**
...
#### Web server error log
...

#### ownCloud log (data/owncloud.log)
...

#### Browser log
...

**Comment by kdslkdsaldsal** [comment]
@Alf21 Please note that this is a bugtracker of ownCloud. Questions on how to develop stuff for ownCloud and similar needs to go to https://central.owncloud.org/c/development (you can login with your github account there).

**Comment by PVince81** [comment]
likely not an ownCloud bug, please ask on central for help with development
