### ISSUE TITLE
Add capability indicating support of multiple link shares

### ISSUE THREAD

**Issue by ckamm** [owncloud/core#27622]
I'm working on adding support for multiple link shares to the client (owncloud/client#5655). I want to make the new UI show only for servers that support it without depending on a server version number. A capability would be nice, but don't see one for this feature yet.

Concrete suggestion: Add capability `capabilities/files_sharing/public/multiple` to 10.0.

**Comment by ckamm** [comment]
Note that maybe the server always technically supported multiple link shares per path and it was just not exposed to the user - and what's actually new here is the ui and the ability to name these. In that case the capability should be named differently.

**Comment by PVince81** [comment]
a ping would have been nice, I'm only seeing this now...

@michaelstingl was this discussed in the context of clients support ?

**Comment by PVince81** [comment]
```
"files_sharing": {
          "api_enabled": true,
          "public": {
            "enabled": true,
            "password": {
              "enforced": false
            },
            "expire_date": {
              "enabled": false
            },
            "send_mail": false,
            "upload": true,
            "multiple": true
          },
```

see "multiple". Only present if public link sharing is enabled.

@davivel @ckamm @SamuAlfageme @michaelstingl 

PR here, please review it: https://github.com/owncloud/core/pull/27709

**Comment by michaelstingl** [comment]
@PVince81 Awesome, Thanks!

**Comment by PVince81** [comment]
It's in 10.0.0 RC2, please test

**Comment by davivel** [comment]
@PVince81, thanks, we'll do.

**Comment by davivel** [comment]
For the record: it's in master now, but not in 10.0.0RC2, not in the tag at least (https://github.com/owncloud/core/releases/tag/v10.0.0RC2 ).

**Comment by PVince81** [comment]
how come ? I merged it before releasing

**Comment by davivel** [comment]
Don't know, but history of master shows the commit after.

**Comment by davivel** [comment]
And the daily build doesn't include it either; I patched it to test.

BTW, works for us :) , thank you.

**Comment by PVince81** [comment]
Indeed: https://github.com/owncloud/core/blob/v10.0.0RC2/apps/files_sharing/lib/Capabilities.php#L70

Ok... my mistake... I saw the thumbs up and thought it was merged and didn't verify...

**Comment by ckamm** [comment]
@PVince81 Great! I'll update the client to make use of it! :)

**Comment by SamuAlfageme** [comment]
Tested with client's master and oC EE 10.0.0 RC2 (daily) Build:2017-04-24 and works like expected 😎
