### ISSUE TITLE
LDAP issues with owncloud server

### ISSUE THREAD

**Issue by davidgubler** [owncloud/core#27636]
We have an owncloud installation with various issues. I can't pin it down to a single problem yet, but here's what we see:

* PHP processes handling owncloud requests sometimes run for a long time (minutes) and finally crash with an out of memory condition: 
* [12-Apr-2017 17:14:23] WARNING: [pool owncloud] child 5795 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/owncloud/apps/user_ldap/lib/Access.php on line 1075"
* It may crash in other places in the code, but the above is the most common
* Increasing PHP memory does not help (tested 1.5 GB)
* limiting the number of requests until a PHP worker is discarded does not help
* owncloud does a lot of LDAP queries on the local LDAP server (slapd). sometimes over 5000 per second! 
* Query: [12/Apr/2017:17:54:45 +0200] conn=35207 op=81474 SRCH base="uid=owncloudadmin,ou=people,dc=company,dc=redacted" scope=0 filter="(objectClass=*)" attrs="cn"
* Result: [12/Apr/2017:17:54:45 +0200] conn=35207 op=81478 RESULT err=0 tag=101 nentries=1 etime=0 notes=P
* same query for "uid" and "nsUniqueId"
* in the users table, there is no uid "owncloudadmin". However, there is a uid "owncloudadmin_8060".
* If I dump the database and grep for owncloudadmin, I find 414000 rows containing "owncloudadmin_8060", 23 rows containing "owncloudadmin", 1376 rows containing owncloudadmin_someothernumber. 
* An external engineer who set up the ldap connection says that owncloud somehow magically renamed the owncloudadmin user, which he tried to revert, then it broke completely, then he rewerted it back.

So it looks like this database is severely messed up, and I guess that's the reason for owncloud misbehaving in terms of memory usage.

Do you have any ideas how this could happen, and perhaps ideas on how we could fix this?

### Server configuration
**Operating system**: 
Ubuntu 14.04

**Web server:**
nginx, PHP-FPM

**Database:**
MariaDB 5.5.54-1ubuntu0.14.04.1

**PHP version:**
7.0.17-3+deb.sury.org~trusty+1

**ownCloud version:**
9.1.4-1.1

**Updated from an older ownCloud or fresh install:**
Fresh install, but migrated existing database and data directory from other server

**Where did you install ownCloud from:**
Ubuntu package

**Signing status (ownCloud 9.0 and above):**

```
I can't log in to this owncloud instance.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.7
  - documents: true
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_ldap: 0.9.0
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'oc8u033t5o6i',
  'passwordsalt' => 'redacted',
  'secret' => 'redacted',
  'trusted_domains' => 
  array (
    0 => 'redacted.ch',
    1 => 'owncloud.redacted.net',
    2 => 'owncloud3.redacted.net',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://redacted.ch',
  'dbtype' => 'mysql',
  'version' => '9.1.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => '',
  'dbuser' => 'owncloud',
  'dbpassword' => 'redacted',
  'logtimezone' => 'UTC',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => '6379',
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'theme' => '',
  'loglevel' => 1,
  'maintenance' => false,
  'htaccess.RewriteBase' => '/',
);
```

**Are you using external storage, if yes which one:**
No.

**Are you using encryption:**
Yes.

**Are you using an external user-backend, if yes which one:**
LDAP, local copy on the server.
389-ds-base 1.3.2.16-0ubuntu1

#### LDAP configuration

```
+-------------------------------+----------------------------------------------------------------------------------------+
| Configuration                 | s04                                                                                    |
+-------------------------------+----------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                      |
| hasPagedResultSupport         |                                                                                        |
| homeFolderNamingRule          |                                                                                        |
| lastJpegPhotoLookup           | 0                                                                                      |
| ldapAgentName                 |                                                                                        |
| ldapAgentPassword             | ***                                                                                    |
| ldapAttributesForGroupSearch  |                                                                                        |
| ldapAttributesForUserSearch   |                                                                                        |
| ldapBackupHost                |                                                                                        |
| ldapBackupPort                |                                                                                        |
| ldapBase                      | ou=People,dc=redacted,dc=redacted                                                             |
| ldapBaseGroups                | ou=groups,dc=redacted,dc=redacted                                                             |
| ldapBaseUsers                 | ou=People,dc=redacted,dc=redacted                                                             |
| ldapCacheTTL                  | 1200                                                                                   |
| ldapConfigurationActive       | 1                                                                                      |
| ldapDynamicGroupMemberURL     |                                                                                        |
| ldapEmailAttribute            | mail                                                                                   |
| ldapExperiencedAdmin          | 1                                                                                      |
| ldapExpertUUIDGroupAttr       |                                                                                        |
| ldapExpertUUIDUserAttr        |                                                                                        |
| ldapExpertUsernameAttr        | uid                                                                                    |
| ldapGroupDisplayName          | cn                                                                                     |
| ldapGroupFilter               | (&(objectClass=posixGroup)(cn=smb_*))                                                  |
| ldapGroupFilterGroups         |                                                                                        |
| ldapGroupFilterMode           | 0                                                                                      |
| ldapGroupFilterObjectclass    |                                                                                        |
| ldapGroupMemberAssocAttr      | memberUid                                                                              |
| ldapHost                      | localhost                                                                              |
| ldapIgnoreNamingRules         |                                                                                        |
| ldapLoginFilter               | (uid=%uid)                                                                             |
| ldapLoginFilterAttributes     |                                                                                        |
| ldapLoginFilterEmail          | 0                                                                                      |
| ldapLoginFilterMode           | 0                                                                                      |
| ldapLoginFilterUsername       | 1                                                                                      |
| ldapNestedGroups              | 0                                                                                      |
| ldapOverrideMainServer        |                                                                                        |
| ldapPagingSize                | 500                                                                                    |
| ldapPort                      | 389                                                                                    |
| ldapQuotaAttribute            |                                                                                        |
| ldapQuotaDefault              |                                                                                        |
| ldapTLS                       | 0                                                                                      |
| ldapUserDisplayName           | cn                                                                                     |
| ldapUserDisplayName2          |                                                                                        |
| ldapUserFilter                | (|(objectclass=inetOrgPerson)(objectclass=sambaSamAccount)(objectclass=shadowAccount)) |
| ldapUserFilterGroups          |                                                                                        |
| ldapUserFilterMode            | 0                                                                                      |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                          |
| ldapUuidGroupAttribute        | auto                                                                                   |
| ldapUuidUserAttribute         | auto                                                                                   |
| turnOffCertCheck              | 0                                                                                      |
| useMemberOfToDetectMembership | 1                                                                                      |
+-------------------------------+----------------------------------------------------------------------------------------+
```

### Client configuration
**Browser:**
Mostly mirall/2.3.0 and 2.3.1

**Operating system:**
Linux and Mac

#### Web server error log
Way to large to add the entire log file. Will gladly add log output if I know what to look for.

#### ownCloud log (data/owncloud.log)
Way to large to add the entire log file. Will gladly add log output if I know what to look for.

#### Browser log
n/a

**Comment by PVince81** [comment]
@owncloud/ldap 

in general it shouldn't run out of memory.

how many users, groups and shares do you have on your instance ?

**Comment by davidgubler** [comment]
We have less than 100 users in LDAP and only about 10 users actively use OwnCloud.

After trying to reconstruct the events that lead to this situation I think that at some point OwnCloud was connected to an LDAP server that returned bad data, which somehow messed up the OwnCloud database. We're currently looking into options how we can completely rebuild the database.

**Comment by jvillafanez** [comment]
Some recommendations:
* ldapBase (including user and group bases) should be in lowercase. I've seen some duplications on some DB entries with the mix of uppercase and lowercase.
* uid in the ldapExpertUsernameAttr and loginFilter -> this could lead to an infinite loop if there are duplicated uids. Using the default username attribute doesn't show this issue.
* memberUid as ldapGroupMemberAssocAttr isn't as tested as the usual "member" attribute, and it consumes more memory. I don't know if this is causing your issue or not, but I'd recommend to switch to "member" if possible (note that you'll have to change your LDAP)
* the loginFilter should be a subset of the userFilter: for your particular case I'd recommend `(&(|(objectclass=inetOrgPerson)(objectclass=sambaSamAccount)(objectclass=shadowAccount))(uid=%uid))` as loginFilter.

Taking into account that your LDAP is small, I don't know if it's possible for you to send us the dump of your LDAP **removing passwords and any confidential information**, or using fake data. The goal is to reproduce your environment and check what is happening.

**Comment by PVince81** [comment]
closing due to lack of feedback
