### ISSUE TITLE
Loading error of some files

### ISSUE THREAD

**Issue by riccardopirani** [owncloud/core#27644]
### Steps to reproduce
1. Upload files or image from Client Software or Website
2. Error Upload 
3. Don't Sync Client Software

### Server configuration
**Ubuntu Server 16.04.2**:

**Web Server: Apache**

**Database: MariaDB**

**PHP version: PHP 7.0.15**

**Version Owncloud: ownCloud 9.1.4 (stable)** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install: Updated from an older **

**Where did you install ownCloud from: I have install owncloud from owncloud.org**

**List of activated apps: **

Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.1
  - dav: 0.2.7
  - external: 1.2
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_external: 0.4
Disabled:
  - encryption
  - files_antivirus
  - notes
  - ojsxc
  - ownbackup
  - ownnote
  - qownnotesapi
  - richdocuments
  - spreedme
  - tasks
  - user_ldap

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => ‘—‘,
  'passwordsalt' => ‘—/—‘,
  'secret' => ‘—‘,
  'trusted_domains' => 
  array (
    0 => ‘myip’,
    1 => ‘myip’,
    2 => ‘mulino’,
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => ‘————/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => ‘——‘,
  'dbpassword' => ‘——‘,
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => ‘——‘,
  'mail_smtpauth' => 1,
  'mail_smtphost' => ‘——‘,
  'mail_smtpport' => '25',
  'mail_smtpname' => ‘——‘,
  'mail_smtppassword' => ‘———‘,
  'loglevel' => 0,
  'appstore.experimental.enabled' => true,
  'trashbin_retention_obligation' => 'auto',
  'updatechecker' => true,
  'htaccess.RewriteBase' => '/owncloud',
  'ldapIgnoreNamingRules' => false,
  'updater.secret' => ‘—‘,
);

?>

**Are you using encryption:** yes HTTPS

### Client configuration
**Browser: Safari and Chrome**

_**owncloud.log error:**_

Fatal 
webdav 
Exception: {"Message":"HTTP\/1.1 423 \"Copie progetti EIB\/ETS 5\/Menu\" is locked","Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\FileLocked","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(640): OCA\\DAV\\Connector\\Sabre\\ObjectTree->move('Copie progetti ...', 'Copie progetti ...')\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpMove(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:MOVE', Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(57): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/owncloud\/remote.php(164): require_once('\/var\/www\/ownclo...')\n#7 {main}","File":"\/var\/www\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/ObjectTree.php","Line":252,"User":"paolo"}

**Comment by kdslkdsaldsal** [comment]
@riccardopirani The following part of the filled out issue template is completely missing. Without any errors its impossible to help here:

```
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
```

**Comment by riccardopirani** [comment]
my owncloud.log is 8GB

**Comment by riccardopirani** [comment]
I have upload error log !

**Comment by kdslkdsaldsal** [comment]
@riccardopirani Yes, that looks good. At central you will find a FAQ how to unlock such files and how to configure your environment to prevent that files got stuck in such a locked state:

https://central.owncloud.org/t/file-is-locked-how-to-unlock/985

**Comment by riccardopirani** [comment]
@kdslkdsaldsal  everything works perfectly thanks a lot

**Comment by kdslkdsaldsal** [comment]
@riccardopirani Feel free to close here then.
