### ISSUE TITLE
Never ending loading wheel; Sync stopped working.

### ISSUE THREAD

**Issue by zitrusblau** [owncloud/core#27641]
### Steps to reproduce
1. Open Web Client
2. Create new Folder
3. Open new Folder
3. Copy file to new folder
4. Go somewhere else
5. Try to open newly created folder again
6. Watch never ending loading wheel

### Expected behaviour
Web client should show the contents of the folder.

### Actual behaviour
Web client shows never ending loading wheel; 
Also: Sync of parent folder with Desktop Client STOPPED WORKING because of the child folder which produces the never ending loading wheel in the Web Client (checked the logs of the desktop client). 

### Server configuration
**Operating system**:
Debian 3.16.39-1+deb8u2

**Web server:**
Apache/2.4.10 (Debian)

**Database:**
mySQL 5.5.54

**PHP version:**
PHP 7.0.17

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.8 (stable)

**Updated from an older ownCloud or fresh install:**
Updated from an oder ownCloud (8.x I guess)

**Where did you install ownCloud from:**
Downloaded the package and did the web install once. Then used the updater regularly.

**Signing status (ownCloud 9.0 and above):**

"No errors have been found."

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - configreport: 0.1.1
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - announcementcenter
  - encryption
  - external
  - files_antivirus
  - files_trashbin
  - files_videoviewer
  - ocusagecharts
  - updater
  - user_external
  - user_ldap

**The content of config/config.php:**

{
    "system": {
        "instanceid": "oc2rkbjlm71q",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "zitrusblau.de",
            "www.zitrusblau.de"
        ],
        "datadirectory": "\/usr\/www\/users\/zitruszb\/cloud\/data",
        "overwrite.cli.url": "https:\/\/www.zitrusblau.de\/cloud",
        "dbtype": "mysql",
        "version": "9.0.8.2",
        "dbname": "owncloud",
        "dbhost": "dedi2269.your-server.de",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbdriveroptions": {
            "1002": "SET wait_timeout = 28800"
        },
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "smtp.mandrillapp.com",
        "mail_smtpport": "587",
        "mail_from_address": "info",
        "mail_smtpauth": 1,
        "mail_domain": "zitrusblau.de",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "theme": "",
        "loglevel": 3,
        "maintenance": false,
        "trashbin_retention_obligation": "auto, D"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration
**Browser:**

Chrome 57.0.2987.133 (64-bit)

**Operating system:**

OsX 10.11.6

#### Web server error log

Nothing happened there.

#### ownCloud log (data/owncloud.log)

Every few seconds, something like this appears in the log:

{"reqId":"6YczYVMlt5kBgtXpR\/Kd","remoteAddr":"87.138.111.31","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"File with id \\\"7905\\\" has not been found.\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/www\\\/users\\\/zitruszb\\\/cloud\\\/apps\\\/files_sharing\\\/lib\\\/sharedstorage.php(90): OC\\\\Files\\\\View->getPath(7905, false)\\n#1 \\\/usr\\\/www\\\/users\\\/zitruszb\\\/cloud\\\/apps\\\/files_sharing\\\/lib\\\/sharedstorage.php(581): OC\\\\Files\\\\Storage\\\\Shared->init()\\n#2 \\\/usr\\\/www\\\/users\\\/zitruszb\\\/cloud\\\/lib\\\/private\\\/files\\\/view.php(1343): OC\\\\Files\\\\Storage\\\\Shared->getCache('')\\n#3 \\\/usr\\\/www\\\/users\\\/zitruszb\\\/cloud\\\/lib\\\/private\\\/files\\\/node\\\/root.php(179): OC\\\\Files\\\\View->getFileInfo('\\\/mbeil')\\n#4 \\\/usr\\\/www\\\/users\\\/zitruszb\\\/cloud\\\/lib\\\/private\\\/files\\\/node\\\/root.php(341): OC\\\\Files\\\\Node\\\\Root->get('\\\/mbeil')\\n#5 \\\/usr\\\/www\\\/users\\\/zitruszb\\\/cloud\\\/lib\\\/private\\\/server.php(746): OC\\\\Files\\\\Node\\\\Root->getUserFolder('mbeil')\\n#6 \\\/usr\\\/www\\\/users\\\/zitruszb\\\/cloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/serverfactory.php(125): OC\\\\Server->getUserFolder()\\n#7 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ServerFactory->OCA\\\\DAV\\\\Connector\\\\Sabre\\\\{closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/usr\\\/www\\\/users\\\/zitruszb\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#9 \\\/usr\\\/www\\\/users\\\/zitruszb\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#10 \\\/usr\\\/www\\\/users\\\/zitruszb\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/usr\\\/www\\\/users\\\/zitruszb\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/usr\\\/www\\\/users\\\/zitruszb\\\/cloud\\\/remote.php(138): require_once('\\\/usr\\\/www\\\/users\\\/...')\\n#13 {main}\",\"File\":\"\\\/usr\\\/www\\\/users\\\/zitruszb\\\/cloud\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1686}","level":3,"time":"2017-04-13T11:52:45+00:00","method":"PROPFIND","url":"\/cloud\/remote.php\/webdav\/","user":"mbeil"}

#### Browser log

Uncaught (in promise) TypeError: Cannot read property 'substr' of undefined
    at Client._parseFileInfo (client.js?v=a0008e6…:239)
    at client.js?v=a0008e6…:347
    at Function._.map._.collect (underscore.js?v=a0008e6…:172)
    at Client._parseResult (client.js?v=a0008e6…:346)
    at client.js?v=a0008e6…:408

**Comment by kdslkdsaldsal** [comment]
> File with id \"7905\" has not been found.

Looks similar to https://github.com/owncloud/core/issues/27567 where you will find quite a lot of info how to mitigate this

**Comment by zitrusblau** [comment]
This error message is produced by the client:
```

OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot(int, const QString &) 5 "Unbekannter Fehler"
04-18 10:20:01:809 28975 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x7fbfab5629e0) FLUECHTLINGSPATEN/VERWALTUNG/C_Verein Docs/Mitglieder- : Versammlung ...Returned from main thread
04-18 10:20:01:809 28975 OCC::DiscoveryJob::remote_vio_opendir_hook: 5 when opening FLUECHTLINGSPATEN/VERWALTUNG/C_Verein Docs/Mitglieder- : Versammlung msg= "Unbekannter Fehler"
04-18 10:20:01:809 0x7fbfab50a9d8 csync_ftw: opendir failed for FLUECHTLINGSPATEN/VERWALTUNG/C_Verein Docs/Mitglieder- : Versammlung - errno 5
04-18 10:20:01:809 28975 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t *, void *) OCC::DiscoveryJob(0x7fbfab5629e0) "/FLUECHTLINGSPATEN/VERWALTUNG/C_Verein Docs"
04-18 10:20:01:809 28975 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t *, void *) OCC::DiscoveryJob(0x7fbfab5629e0) "/FLUECHTLINGSPATEN/VERWALTUNG"
04-18 10:20:01:809 28975 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t *, void *) OCC::DiscoveryJob(0x7fbfab5629e0) "/FLUECHTLINGSPATEN"
04-18 10:20:01:809 28975 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t *, void *) OCC::DiscoveryJob(0x7fbfab5629e0) ""
04-18 10:20:01:809 0x7fbfab50a9d8 csync_statedb_close: sqlite3_close=0
```

Maybe owncloud can't handle certain folder names? Seems quite odd.

**Comment by zitrusblau** [comment]
OK. I found out that folder containing **", "** (semincolon plus white space) or **": "** (colon plus white space) don't sync. I just moved those folders and did a new files:scan. 

But this is really uncomfortable. I can't control if users create such folders. Any ideas how to solve that?

**Comment by PVince81** [comment]
the error message has "Mitglieder- : Versammlung" but no comma in it, so maybe it's colons only ?

Are you able to create a test user and narrow it down to the smallest possible name that breaks ?

In general this shoulud work, but in the past there were bugs in the Sabre library related to colons followed by a number in URLs which required patching. This is fixed already, but maybe you discovered another case...

**Comment by zitrusblau** [comment]
It's not only the colons. Also other combinations of **white space** and **special characters**.

A commonly problematic filename (I'm now have to rename a whole directory full of them :-( ) is this: **"string string string, 1.Seite.pdf"**.

Also, the web client produces URLs for that kind of files which AUTOMATICLY route to the TLD-Root (e.g. https://www.example.com) of the cloud service. Other files (even in the same folder) download perfectly.

**Comment by PVince81** [comment]
I tried this exact string "string string string, 1.Seite.pdf" on my 9.1.5 RC1 instance and the file syncs properly.

It is likely that somewhere in your environment something might be mangling the URLs and preventing them to reach OC properly.

**Comment by zitrusblau** [comment]
New finding:

Uploading of "string string string, 1.Seite.pdf" succeeds, but downloading of the same file results in 

```

(403)Forbidden

You don't have permission to access ... on this server
```

Again, only for files looking like "string string string, 1.Seite.pdf".

**Comment by zitrusblau** [comment]
Problem solved.

Unfortunately, in the parent folder of the owncloud installation, 6G (or some other security framework) misconfigured the .htaccess and denied some URLs for security reasons.

Thanks for your time.
