### ISSUE TITLE
Switching to favorites and back again breaks favorites

### ISSUE THREAD

**Issue by butonic** [owncloud/core#27657]
### Steps to reproduce
1. As a new user mark a folder as favorite
2. Switch to Favorites in the Filelist
3. Switch back to Files
4. Switch to Favorites again

### Expected behaviour
You should see the favorite

### Actual behaviour
The list is filelist empty, but it shows that one file is in the list:
![favorites bug](https://cloud.githubusercontent.com/assets/956847/25131670/e1cc888e-2446-11e7-86f6-a863a7241ff6.PNG)

No error in the js log (after adding `"debug"=>true` in config.php)

**Comment by PVince81** [comment]
Duplicate of https://github.com/owncloud/core/issues/27697
