### ISSUE TITLE
Wrong subtab selected when accessing share details of a public link

### ISSUE THREAD

**Issue by butonic** [owncloud/core#27656]
### Steps to reproduce
1. Share a folder via Link
2. Make sure it is not shared internally
3. reload the page (closing and reopening the sidebar does not trigger the bug)
4. open the sharing tab

### Expected behaviour
Since it is not shared to internal users the 'public links' tab should be preselected

### Actual behaviour
The 'users and groups' tab is selected ... and of course empty. Users need an additional click to access the public links.

**Comment by butonic** [comment]
I don't know if we should consider this a bug or a feature ...

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
