### ISSUE TITLE
Exceptions raise when changing user password and no email was configured

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#27654]
### Steps to reproduce

1. As a regular user go to settings and to personal/general.
2. Try to change password.

### Expected behaviour
You change the password and the ui says it has been changed correctly.

### Actual behaviour
It changes the password, but feels like blocked. Checking dev tools we can see a 500 error.

### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.0.6","versionstring":"10.0.0 beta2","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"JHtaxm7gq3AjGhPSQyXs","level":3,"time":"2017-04-18T12:05:30+00:00","remoteAddr":"HIDDEN_IP","user":"grant","app":"PHP","method":"POST","url":"\/index.php\/settings\/personal\/changepassword","message":"Undefined offset: 1 at \/opt\/owncloud\/lib\/private\/Mail\/Message.php#59"}
{"reqId":"JHtaxm7gq3AjGhPSQyXs","level":3,"time":"2017-04-18T12:05:30+00:00","remoteAddr":"HIDDEN_IP","user":"grant","app":"index","method":"POST","url":"\/index.php\/settings\/personal\/changepassword","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Couldn't send reset email. Please contact your administrator.\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/owncloud\\\/settings\\\/ChangePassword\\\/Controller.php(58): OC\\\\Settings\\\\ChangePassword\\\\Controller::sendNotificationMail('grant')\\n#1 [internal function]: OC\\\\Settings\\\\ChangePassword\\\\Controller::changePersonalPassword(Array)\\n#2 \\\/opt\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Array, Array)\\n#3 \\\/opt\\\/owncloud\\\/lib\\\/base.php(910): OC\\\\Route\\\\Router->match('\\\/settings\\\/perso...')\\n#4 \\\/opt\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#5 {main}\",\"File\":\"\\\/opt\\\/owncloud\\\/settings\\\/ChangePassword\\\/Controller.php\",\"Line\":193}"}
```
### Client configuration

**Browser**
Chrome

**Logs**
```
jquery.js:8630 POST http://HIDDEN_HOST/index.php/settings/personal/changepassword 500 (Internal Server Error)
send	@	jquery.js:8630
ajax	@	jquery.js:8166
n.(anonymous function)	@	jquery.js:8311
(anonymous)	@	profile.js?v=9949793…:178
dispatch	@	jquery.js:4435
r.handle	@	jquery.js:4121
```

**Comment by PVince81** [comment]
Works for me when email is configured.

It's only when no email is set.

@imujjwal96 can you add a check and don't send password notification when no email is set ?

**Comment by imujjwal96** [comment]
Hello @PVince81 
I will not be able to work on this issue before the weekend. I hope it is not urgent.

**Comment by PVince81** [comment]
Also affects admins who then can't change the user's password.
Workaround is to set an email address first as admin.

I'll take care of this, this looks bad.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/27694
