### ISSUE TITLE
Automatically accept federated incoming shared files/folders invites/notifications

### ISSUE THREAD

**Issue by avatar-lavventura** [owncloud/core#27653]
[owncloud][1] :

> Sharing files across ownCloud servers is as easy as sending an email
> from a Gmail address to a Yahoo account! Instead of an email address,
> you use a Federated Cloud ID.
> 
> In order to share a file/folder, enter the Federated Cloud ID in the
> 'share' dialog. A notification will pop up on the ownCloud server of
> the recipient.

For example `userA` shares a folder to `userB`, `userB` sees a notification message. When `userB` accepts the shared folder, he/she could see shared folder under his files.

Example of notification:
    You received <folderName> as a remote share from John John
(Decline) (Accept).
[![enter image description here][2]][2]

**[Q1]** Accepting shared folders force user to use graphical user interface to accept the shared file/folder. Is there any way to accept it without using gui and using script or curl? I just would like to make this operation automised independent from user's act on the gui. If this is possible, also how could I unshare a folder with a script, again instead of using gui?

[![enter image description here][3]][3]

**[Q2]** Could a user accept automatically any file shared with him? 

Thank you for your valuable time and help.

  [1]: https://owncloud.org/federation/
  [2]: https://i.stack.imgur.com/6GlMm.png
  [3]: https://i.stack.imgur.com/zRv3w.png

**Comment by PVince81** [comment]
Automatically accepting could pose a security risk.

It might be acceptable to allow auto-accepting when shares come from trusted federated instances, the goal being to make sharing as seamless as user shares.

@pmaier1 thoughts ?

**Comment by PVince81** [comment]
Estimate 2md

- add new checkbox option to auto-accept federated shares
- if option is set and a federated share is incoming, mark it automatically as accept
- if the other option "automatically pair with server" is set (insecure), never automatically accept a federated share (the option must be greyed out and considered as false regardless)
