### ISSUE TITLE
Upgrade 8.2.9 to 9.0.8

### ISSUE THREAD

**Issue by IngoBelka** [owncloud/core#27651]
### Steps to reproduce
1. following https://download.owncloud.org/download/repositories/9.0/owncloud/
2. running sudo -u www-data php occ upgrade
3. repairing oc_appconfig values
"core","public_webdav","dav/appinfo/v1/publicwebdav.php"
"core","remote_caldav","dav/appinfo/v1/caldav.php"
"core","remote_calendar","dav/appinfo/v1/caldav.php"
"core","remote_carddav","dav/appinfo/v1/carddav.php"
"core","remote_contacts","dav/appinfo/v1/carddav.php"
"core","remote_files","dav/appinfo/v1/webdav.php"
"core","remote_webdav","dav/appinfo/v1/webdav.php"

### Expected behaviour
calendar and contacts should work

### Actual behaviour
no calendars and contacts 

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache 2.4

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 9.0.8

**Updated from an older ownCloud:** 8.2.10

**Where did you install ownCloud from:** https://download.owncloud.org/download/repositories/9.0/ownclou

**Signing status (ownCloud 9.0 and above):**

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - calendar: 1.4.1
  - comments: 0.2
  - configreport: 0.1.1
  - contacts: 1.5.1
  - dav: true
  - direct_menu: 0.9.2
  - documents: 0.12.1
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc18vhyigxi1",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "147.61.10.7",
            "intracloud"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/ip\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.8.2",
        "dbname": "ocmaster",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "mail_from_address": "info",
        "mail_smtpmode": "smtp",
        "mail_domain": "grimmen.de",
        "mail_smtphost": "ip",
        "updatechecker": false
    }
}

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Thunderbird

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 7

#### ownCloud log (data/owncloud.log)

What else can I do to get access to our calendars and contacts? What did I overlooked?

Any help is appreciated!

**Comment by IngoBelka** [comment]
Ok as i found now, the migration of the contacts and calendars where broken. I migrated these data manually.

ocmaster@intracloud:/var/www/owncloud$ sudo -u www-data php occ dav:migrate-addressbook
Start migration of all known users ...
   21 [============================]
ocmaster@intracloud:/var/www/owncloud$ sudo -u www-data php occ dav:migrate-calendars
Start migration of all known users ...
   21 [============================]

Only one calendar left incomplete. How can I migrate this calendar once more again?
The other users can access their data via Thunderbird without problems.

Access via owncloud app calendar and contacts still does not work. What is my mistake?

**Comment by kdslkdsaldsal** [comment]
@IngoBelka This blogpost might help you with a few infos:

http://morrisjobke.de/2016/03/07/ownCloud-9.0-calendar-migration-analysis/

You could also revert to your backup and wait for the next releases 8.2.11 and 9.0.9: https://github.com/owncloud/owncloud.org/pull/1171

Especially it might help to go to 8.2.11 first (you had skipped 8.2.10 before going to 9.0.8 which is not recommended) before continuing to 9.0.9

**Comment by IngoBelka** [comment]
@kdslkdsaldsal Thanks for pointing me on the site of MorrisJobke. I did the migration and I did migrate a calendar once more again. But much more interesting is, that after this migration the owncloud apps also do their work as expected.
