### ISSUE TITLE
status.php outputs empty version attribute when disabled

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27669]
### Steps
1. Set "version.hide" to true in config.php
1. Invoke status.php

### Expected
No "version" attributes, no "productname" attribute.

### Actual
"version" attributes appear but are empty.

`{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"","versionstring":"","edition":"","productname":""}`

This makes it look broken as if it was a bug.

@mmattel I also noticed that your new section in the admin page also doesn't display the version.
If the intent of that section was to show exactly the output of status.php then it's fine.

**Comment by guruz** [comment]
This is what we need to legacy desktop clients afaik.
FYI @ckamm

**Comment by mmattel** [comment]
@PVince81 refs PR https://github.com/owncloud/core/pull/27238/files)

What I did was just creating a method in util.php and move the code that was former in status.php there.
Contentwise it is the same. The benefit is, that by this step you can now call the method to get the values from anywhere in php and not only by calling status.php which was locked to browser access. This made it possible to have the outpu also in the General section.

If there is the need of selectively "hide" particular values, my proposal would be to handover \OCP\Util::getStatusInfo() a parameter (defaulting eg to false or a number) and let the function decide what to be returned based on the parameter.

**Comment by PVince81** [comment]
If this is by design then we can close this...

**Comment by mmattel** [comment]
Just looked into the code at util.php.
There is a PR implemented I guess by @DeepDiver1975 which exactly does what I said above.

https://github.com/owncloud/core/blob/54150e7f64250d4c5774ec80714e3ff4e73c1fe6/lib/public/Util.php#L714
https://github.com/owncloud/core/blob/54150e7f64250d4c5774ec80714e3ff4e73c1fe6/config/config.sample.php#L83

To be decided if you want to:
- show the values and the parameter (as it was in the past)
- hide the values but show the parameter (current, default)
- or hide both (based on a/the parameter).

**Comment by PVince81** [comment]
I suggest to keep it as it is now.
