### ISSUE TITLE
Maximum upload size is ignored.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#27672]
### Steps to reproduce

1. As an admin go to settings admin/storage.
2. In file handling, set maximum upload size to 2MB.
3. As a regular user go to files view and upload a file bigger than 2MB.

### Expected behaviour
The upload is forbidden.

### Actual behaviour
File is upload, nothing is checked.

### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.0.6","versionstring":"10.0.0 beta2","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

### Client configuration

**Browser**
Chrome

**Logs**
```
```

Working fine in version 9.1.4.

**Comment by PVince81** [comment]
There is no more max upload in 10.0 because web UI uses Webdav PUT.

We should probably remove that setting...

**Comment by PVince81** [comment]
PR to remove the section: https://github.com/owncloud/core/pull/27929
