### ISSUE TITLE
Broken link in help and tips: advanced monitoring.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#27677]
### Steps to reproduce

1. As an admin user go to settings and to admin/Help & tips.
2. Click on advanced monitoring.

![screen shot 2017-04-19 at 12 48 44](https://cloud.githubusercontent.com/assets/9048796/25177123/06d8263c-2501-11e7-9045-683647827d4b.png)

### Expected behaviour
Opens documentation page.

### Actual behaviour
Not found. Broken link.

### Server configuration

**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.0.6","versionstring":"10.0.0 beta2","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

### Client configuration

**Browser**
Chrome

**Logs**
```
```

cc @settermjd

**Comment by kdslkdsaldsal** [comment]
Was removed in https://github.com/owncloud/core/pull/28416 and https://github.com/owncloud/core/pull/28417 so closing here.
