### ISSUE TITLE
File lists do not properly reload when switching

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27697]
### Steps

1. Go to "Deleted files" to preinitialize the list
1. Go to "All files"
1. Delete a file
1. Go to "Deleted files"
1. Refresh the page

### Expected
When going back to "Deleted files", that list needs to refresh with new values, so the deleted file is visible.

### Actual
List not refreshed.

The same happens if you restore a file from trash after coming from "all files", then going back there doesn't make the file appear.

### Versions
ownCloud 10.0.0 RC1

Not sure if regression, I have the feeling that this did work before.

There were some changes regarding reload the list by @noveens, not sure if related.

Needs research.

**Comment by PVince81** [comment]
Ok, I just tried 9.1.5 and it works correctly there, so it's a regression.

A git bisect should reveal when this was broken.

@noveens do you have time to have a look ?

**Comment by PVince81** [comment]
Another case, even worse result:

1. Share a file with someone else
1. Switch to "Shared with others"
1. Switch to "Shared with you"
1. Switch back to "Shared with others"

The list is not rendered any more, but the summary still says "1 file".
Likely related to this refresh issue here.

**Comment by PVince81** [comment]
Regression introduced through https://github.com/owncloud/core/pull/27282.

The problem here is that the directory doesn't actually change when switching views, but we still need a way to force a refresh there.

**Comment by PVince81** [comment]
Or maybe we should destroy the list completely when switching away. So when switching back it would recreate it from scratch.

**Comment by PVince81** [comment]
I found a simple way: https://github.com/owncloud/core/pull/27703

**Comment by noveens** [comment]
Will test more regarding the issue after 4-5 days.
Currently having exams at my university.
