### ISSUE TITLE
occ command to migrate a single user's home folder

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27692]
In 10.0 the home folder absolute path is hard-coded in the oc_accounts table.

Need an occ command to move it physically + adjusting the DB.

**Comment by PVince81** [comment]
@DeepDiver1975 @butonic @pmaier1 something to consider soon

**Comment by PVince81** [comment]
need updating docs otherwise https://github.com/owncloud/documentation/issues/3194

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
