### ISSUE TITLE
Versions not copied to receipient trash on delete and wrong restore path

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27698]
### Steps

1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create a folder "test/versions"
1. Share "test" with "user2"
1. Login as "user2"
1. Create a file "test/versions/test.txt", save multiple times to create versions
1. Check versions tab: versions exist
1. Delete "/test"
1. Check trash
1. Restore "versions" folder
1. Check "versions/test.txt" version tab

### Expected
Versions are still there.
Folder is restored to "/test/versions".

### Actual
Versions are lost.
Folder is restored to the root "/versions".

Note that if you check the trash of "user1" instead of "user2", you'll find the owner copy of the folder. When restoring that one, the versions are still there.

### Version
ownCloud 10.0.0 RC1

Regression from 9.1.5.

The code related to copying stuff for shared users in trash has been touched recently for https://github.com/owncloud/core/issues/24053, it is likely that it broke this one case.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
Could not reproduce this on master
