### ISSUE TITLE
oc_ldap_user_mapping only contains some LDAP users 

### ISSUE THREAD

**Issue by sif77** [owncloud/core#27701]
In the table oc_ldap_user_mapping i can only see some LDAP users not all users.

I would like to automaticaly create groups based on LDAP queries but i need to know the internal name of my LDAP users. How can i do ?

Thanks

**Comment by jvillafanez** [comment]
> In the table oc_ldap_user_mapping i can only see some LDAP users not all users.

The table is populated as soon as users are scanned. It's very likely the rest of the users haven't been scanned yet. This is not a problem for the LDAP app. **DO NOT MODIFY THE TABLE ON YOUR OWN**

The LDAP app can also map LDAP groups from the LDAP server. Please use this functionality instead. (There should be documentation about how to do this)

**Comment by sif77** [comment]
Unfortunatly, i don't have groups in LDAP server. With others applications, we use LDAP requests to create groups.

How to force all users to be scanned ?

**Comment by sif77** [comment]
Nobody can help me ?

**Comment by PVince81** [comment]
> Nobody can help me ?

https://owncloud.org/support

https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

**Comment by PVince81** [comment]
closing due to not enough info. See above links
