### ISSUE TITLE
[10.0] Provide an option to delete users that aren't in the backend any longer during user:sync

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#27702]
### Steps to reproduce
1. set up a LDAP and connect it to ownCloud
2. sync the users
3. delete some users in the backend
4. sync the users again

### Expected behaviour
The user:sync command provides an option to delete the users that are no longer in the backend (LDAP in this case). The deletion will include all the user data and shares.

It's fine if the users aren't deleted by default (keeping the current behaviour)

Some other not-so-intrusive options can be added, such as delete the account but keep the data.

### Actual behaviour
There is no such option. The users won't be deleted.

We need to take into account other commands such as the file transfer ownership and check what role can play in all of this. For example, remove the account but keep the data could be useful if we want to transfer the files to another account.

Some examples:
```
occ user:sync --delete-action disable-user
occ user:sync --delete-action remove-account-keep-files
occ user:sync --delete-action remove-all
```

@DeepDiver1975

**Comment by tomneedham** [comment]
implemented with https://github.com/owncloud/core/pull/27798
