### ISSUE TITLE
occ command Files_external:applicable id --remove-all does not work

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27704]
### Steps to reproduce

1. Mount a WebDAV external Storage Mountpoint
2. Run via CLI ```sudo -u www-data ./occ files_external:applicable 21 --add-user admin```
3. Run via CLI ```sudo -u www-data ./occ files_external:applicable 21 --remove-all```

### Expected behaviour

Available for should be empty for the mountpoint

### Actual behaviour

Available for is not cleared, even when the occ command returns it ihas been cleared (check via webUI or rerunning applicable command)

```
sudo -u www-data ./occ files_external:applicable 21 --remove-all
  - users:
  - groups:
```

**Note:** Tested in oC 9.1.4 with the same webDAV backend an it works fine. 

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.0"

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
WebDAV

**Are you using encryption:** 
No

**Logs**

Server Logs

```
```

### Client configuration

**Browser**

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
