### ISSUE TITLE
Incorrect "From" field in the "Share Link" notification

### ISSUE THREAD

**Issue by sysfixrap** [owncloud/core#27710]
### Steps to reproduce
1. Log in as ("X Y" x.y@domain.org)
2. Create a share link
3. Write z@domain2.org in "Email link to person" and click to send

### Expected behaviour
A mail from "X Y" x.y@domain.org should be sent to z@domain2.org in order to inform the remote user that the share has been created.

### Actual behaviour
A mail from "X Y" owncloud@domain.org is sent to z@domain2.org, where owncloud=mail_from_address and domain.org=mail_domain in config.php. 
It doesn't matter which mail config I use: sendmail, php, smtp - same behaviour

### Server configuration
**Operating system**:
Ubuntu 16.04.2 LTS
**Web server:**
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2016-07-14T12:32:26
**Database:**

**PHP version:**
"PHP Version": "7.0.15-0ubuntu0.16.04.4"
**ownCloud version:** (see ownCloud admin page)
ownCloud 9.1.5 (stable)
**Updated from an older ownCloud or fresh install:**
It didn't work on fresh install and update to ownCloud 9.1.5 (stable) 
**Where did you install ownCloud from:**
https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04 

```
No errors have been found.
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'xxxxxx',
  'passwordsalt' => 'xxxxxx',
  'secret' => 'xxxxxx',
  'trusted_domains' =>
  array (
    0 => 'xxx',
    1 => 'xxx',
    2 => 'xxx',
  ),
  'datadirectory' => '/var/www/owncloud_data',
  'overwrite.cli.url' => 'http://192.168.178.12/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.5.2',
  'dbname' => 'owncloud9DB',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'db_admin',
  'dbpassword' => 'xxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'mail_smtpmode' => 'sendmail',
  'mail_smtphost' => 'exchange.domain.org',
  'mail_smtpport' => '25',
  'mail_from_address' => 'owncloud',
  'mail_domain' => 'domain.org',
  'maintenance' => false,
  'loglevel' => 2,
);
```

**List of activated apps:**

```
Plain Install no Apps
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
LDAP access to AD with mail attribute correctly set - works perfect
```

**Comment by kdslkdsaldsal** [comment]
> A mail from "X Y" owncloud@domain.org is sent to z@domain2.org, where owncloud=mail_from_address and domain.org=mail_domain in config.php

This is the expected and absolute correct behavior for the reasons explained in: https://github.com/owncloud/core/issues/25470

> the owncloud server cannot access the users mail account (smtp server to be precise).
Owncloud can only send a email via the configured smtp account and this might hold rules which denies sending emails for somebody else.

If your user doing the sharing has set an e-mail address in his personal settings the "reply-to" mail header has that e-mail address added which is the correct way to handle this.

**Comment by sysfixrap** [comment]
Ok, thank you for your quick answer.
I was not aware of the reply address and it worked fine in older owncloud versions.
It is also possible to configure MS exchange to allow sending mails with any sender address.
Nevertheless ist fine as it is.

Best Regards


On 21.04.2017, at 19:23, kdslkdsaldsal <notifications@github.com<mailto:notifications@github.com>> wrote:


A mail from "X Y" owncloud@domain.org<mailto:owncloud@domain.org> is sent to z@domain2.org<mailto:z@domain2.org>, where owncloud=mail_from_address and domain.org<http://domain.org>=mail_domain in config.php

This is the expected and absolute correct behavior for the reasons explained in: #25470<https://github.com/owncloud/core/issues/25470>

the owncloud server cannot access the users mail account (smtp server to be precise).
Owncloud can only send a email via the configured smtp account and this might hold rules which denies sending emails for somebody else.

If your user doing the sharing has set an e-mail address in his personal settings the "reply-to" mail header has that e-mail address added which is the correct way to handle this.
