### ISSUE TITLE
Cannot upload new version file via webUI

### ISSUE THREAD

**Issue by dmitrkov** [owncloud/core#27727]
### Steps to reproduce
1. upload file via webUI
2. upload new version file via webUI

### Expected behaviour
The new version file should be uploaded

### Actual behaviour
Nothing happens

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.1.5 (stable)

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
https://owncloud.org/install/

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**The content of config/config.php:**
https://gist.github.com/dmitrkov/16c0342cb748ddc8e50d48765e34237f

**List of activated apps:**
If you have access to your command line run e.g.:
Enabled:
  - activity: 2.3.2
  - bookmarks: 0.9.0
  - calendar: 1.4.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.1
  - dav: 0.2.7
  - documents: 0.13.1
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.4
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_external: 0.4
Disabled:
  - encryption
  - external
  - files_antivirus
  - user_ldap

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb ftp

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome, Opera, Firefox

**Operating system:**
Windows 10 x64

#### Browser log
12:20:30.175 File.lastModifiedDate is deprecated. should be used File.lastModified. 1 oc-dialogs.js:457

12:22:20.800 TypeError: original is null 1 oc-dialogs.js:453:4
	addConflict http://owncloud.nks.com.ua/core/js/oc-dialogs.js:453:4
	fileexists http://owncloud.nks.com.ua/core/js/oc-dialogs.js:531:4
	checkExistingFiles http://owncloud.nks.com.ua/apps/files/js/file-upload.js:228:4
	add http://owncloud.nks.com.ua/apps/files/js/file-upload.js:443:7
	_trigger http://owncloud.nks.com.ua/core/vendor/jquery-ui/ui/jquery-ui.custom.js:789:4
	_onAdd/< http://owncloud.nks.com.ua/apps/files/js/jquery.fileupload.js:935:26
	each http://owncloud.nks.com.ua/core/vendor/jquery/dist/jquery.min.js:2:2880
	_onAdd http://owncloud.nks.com.ua/apps/files/js/jquery.fileupload.js:928:13
	$.widget/</proxiedPrototype[prop]</< http://owncloud.nks.com.ua/core/vendor/jquery-ui/ui/jquery-ui.custom.js:405:19
	_onChange/< http://owncloud.nks.com.ua/apps/files/js/jquery.fileupload.js:1105:21
	j http://owncloud.nks.com.ua/core/vendor/jquery/dist/jquery.min.js:2:26920
	add http://owncloud.nks.com.ua/core/vendor/jquery/dist/jquery.min.js:2:27234
	always http://owncloud.nks.com.ua/core/vendor/jquery/dist/jquery.min.js:2:28108
	_onChange http://owncloud.nks.com.ua/apps/files/js/jquery.fileupload.js:1099:13
	$.widget/</proxiedPrototype[prop]</< http://owncloud.nks.com.ua/core/vendor/jquery-ui/ui/jquery-ui.custom.js:405:19
	handlerProxy http://owncloud.nks.com.ua/core/vendor/jquery-ui/ui/jquery-ui.custom.js:705:14
	dispatch http://owncloud.nks.com.ua/core/vendor/jquery/dist/jquery.min.js:3:6414
	add/r.handle http://owncloud.nks.com.ua/core/vendor/jquery/dist/jquery.min.js:3:3224

**Comment by hodyroff** [comment]
Just checked in demo.owncloud.com and works perfectly. Can you try there, too? Tried with Firefox on Linux. Popup Blocker?!

**Comment by dmitrkov** [comment]
Reinstall from webinstaller. Works in Microsoft Edge, Chrome and Tor. 
Don't work in Firefox 51.0.1, Opera  44

**Comment by dmitrkov** [comment]
Install **HTTPS**. All works perfectly.

**Comment by PVince81** [comment]
Strange... Works for me with HTTP. Anyway, https is the way to go.
