### ISSUE TITLE
yum managed owncloud upgrade 9.1.4 to 9.1.5 fails

### ISSUE THREAD

**Issue by happiness-now** [owncloud/core#27725]
Hi Folks,

We have an owncloud instance that is yum package managed and the latest 9.1.4 to 9.1.5 update has thrown the error below.

After restoring from a backup to recover from the error below, we tried the solutions in
https://github.com/owncloud/core/issues/26297  to no avail.

Any help would be appreciated.

### Steps to reproduce
1. update owncloud from 9.1.4 to 9.1.5 on centos 7.  Both yum update packages and manual install produce same result.
2. sudo -u apache php occ upgrade

### Expected behaviour
work

### Actual behaviour
During database stage, this error was thrown.

[root@localhost owncloud]# sudo -u apache php occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
 Done                                     
 24/24 [============================] 100%
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
An unhandled exception has been thrown:
Error: Class 'OCA\FederatedFileSharing\DiscoveryManager' not found in /var/www/html/owncloud/apps/files_sharing/lib/AppInfo/Application.php:83
Stack trace:
#0 /var/www/html/owncloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OCA\Files_Sharing\AppInfo\Application->OCA\Files_Sharing\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#1 /var/www/html/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(102): Pimple\Container->offsetGet('ExternalManager')
#2 /var/www/html/owncloud/apps/files_sharing/lib/AppInfo/Application.php(129): OC\AppFramework\Utility\SimpleContainer->query('ExternalManager')
#3 /var/www/html/owncloud/apps/files_sharing/lib/External/MountProvider.php(53): OCA\Files_Sharing\AppInfo\Application->OCA\Files_Sharing\AppInfo\{closure}()
#4 /var/www/html/owncloud/apps/files_sharing/lib/External/MountProvider.php(72): OCA\Files_Sharing\External\MountProvider->getMount(Object(OC\User\User), Array, Object(OC\Files\Storage\StorageFactory))
#5 /var/www/html/owncloud/lib/private/Files/Config/MountProviderCollection.php(76): OCA\Files_Sharing\External\MountProvider->getMountsForUser(Object(OC\User\User), Object(OC\Files\Storage\StorageFactory))
#6 [internal function]: OC\Files\Config\MountProviderCollection->OC\Files\Config\{closure}(Object(OCA\Files_Sharing\External\MountProvider))
#7 /var/www/html/owncloud/lib/private/Files/Config/MountProviderCollection.php(77): array_map(Object(Closure), Array)
#8 /var/www/html/owncloud/lib/private/Files/Filesystem.php(443): OC\Files\Config\MountProviderCollection->getMountsForUser(Object(OC\User\User))
#9 /var/www/html/owncloud/apps/files_sharing/lib/sharedstorage.php(100): OC\Files\Filesystem::initMountPoints('ef')
#10 /var/www/html/owncloud/apps/files_sharing/lib/sharedstorage.php(453): OC\Files\Storage\Shared->init()
#11 /var/www/html/owncloud/lib/private/Files/Storage/Wrapper/Wrapper.php(485): OC\Files\Storage\Shared->getWrapperStorage()
#12 /var/www/html/owncloud/apps/files_sharing/lib/sharedstorage.php(127): OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage('\\OC\\Files\\Stora...')
#13 /var/www/html/owncloud/lib/private/legacy/util.php(153): OC\Files\Storage\Shared->instanceOfStorage('\\OC\\Files\\Stora...')
#14 /var/www/html/owncloud/lib/private/Files/Storage/StorageFactory.php(100): OC_Util::{closure}('/"***REMOVED SENSITIVE VALUE***"/files/...', Object(OC\Files\Storage\Shared), Object(OCA\Files_Sharing\SharedMount))
#15 /var/www/html/owncloud/lib/private/Files/Storage/StorageFactory.php(82): OC\Files\Storage\StorageFactory->wrap(Object(OCA\Files_Sharing\SharedMount), Object(OC\Files\Storage\Shared))
#16 /var/www/html/owncloud/lib/private/Files/Mount/MountPoint.php(137): OC\Files\Storage\StorageFactory->getInstance(Object(OCA\Files_Sharing\SharedMount), '\\OC\\Files\\Stora...', Array)
#17 /var/www/html/owncloud/lib/private/Files/Mount/MountPoint.php(160): OC\Files\Mount\MountPoint->createStorage()
#18 /var/www/html/owncloud/lib/private/Files/View.php(1362): OC\Files\Mount\MountPoint->getStorage()
#19 /var/www/html/owncloud/lib/private/Files/Node/Root.php(180): OC\Files\View->getFileInfo('/"***REMOVED SENSITIVE VALUE***"')
#20 /var/www/html/owncloud/lib/private/AvatarManager.php(97): OC\Files\Node\Root->get('/"***REMOVED SENSITIVE VALUE***"')
#21 /var/www/html/owncloud/lib/private/User/User.php(386): OC\AvatarManager->getAvatar('"***REMOVED SENSITIVE VALUE***"')
#22 /var/www/html/owncloud/apps/dav/lib/CardDAV/Converter.php(165): OC\User\User->getAvatarImage(96)
#23 /var/www/html/owncloud/apps/dav/lib/CardDAV/Converter.php(75): OCA\DAV\CardDAV\Converter->getAvatarImage(Object(OC\User\User))
#24 /var/www/html/owncloud/apps/dav/lib/CardDAV/SyncService.php(228): OCA\DAV\CardDAV\Converter->updateCard(Object(Sabre\VObject\Component\VCard), Object(OC\User\User))
#25 /var/www/html/owncloud/apps/dav/lib/HookManager.php(99): OCA\DAV\CardDAV\SyncService->updateUser(Object(OC\User\User))
#26 /var/www/html/owncloud/lib/private/legacy/hook.php(105): OCA\DAV\HookManager->changeUser(Array)
#27 /var/www/html/owncloud/lib/private/Server.php(279): OC_Hook::emit('OC_User', 'changeUser', Array)
#28 [internal function]: OC\Server->OC\{closure}(Object(OC\User\User), 'quota', 'default')
#29 /var/www/html/owncloud/lib/private/Hooks/EmitterTrait.php(98): call_user_func_array(Object(Closure), Array)
#30 /var/www/html/owncloud/lib/private/Hooks/PublicEmitter.php(32): OC\Hooks\BasicEmitter->emit('\\OC\\User', 'changeUser', Array)
#31 /var/www/html/owncloud/lib/private/User/User.php(423): OC\Hooks\PublicEmitter->emit('\\OC\\User', 'changeUser', Array)
#32 /var/www/html/owncloud/lib/private/User/User.php(370): OC\User\User->triggerChange('quota', 'default')
#33 /var/www/html/owncloud/apps/user_ldap/lib/User/User.php(516): OC\User\User->setQuota('default')
#34 /var/www/html/owncloud/apps/user_ldap/lib/User/User.php(146): OCA\User_LDAP\User\User->updateQuota()
#35 /var/www/html/owncloud/apps/user_ldap/lib/User_LDAP.php(277): OCA\User_LDAP\User\User->update()
#36 /var/www/html/owncloud/lib/private/User/Manager.php(139): OCA\User_LDAP\User_LDAP->userExists('"***REMOVED SENSITIVE VALUE***"')
#37 /var/www/html/owncloud/apps/user_ldap/lib/User/User.php(446): OC\User\Manager->get('"***REMOVED SENSITIVE VALUE***"')
#38 /var/www/html/owncloud/apps/user_ldap/lib/User/User.php(145): OCA\User_LDAP\User\User->updateEmail()
#39 /var/www/html/owncloud/apps/user_ldap/lib/User_LDAP.php(277): OCA\User_LDAP\User\User->update()
#40 /var/www/html/owncloud/lib/private/User/Manager.php(139): OCA\User_LDAP\User_LDAP->userExists('"***REMOVED SENSITIVE VALUE***"')
#41 /var/www/html/owncloud/lib/private/User/Manager.php(183): OC\User\Manager->get('"***REMOVED SENSITIVE VALUE***"')
#42 /var/www/html/owncloud/lib/private/Repair/CleanTags.php(99): OC\User\Manager->userExists('"***REMOVED SENSITIVE VALUE***"')
#43 /var/www/html/owncloud/lib/private/Repair/CleanTags.php(78): OC\Repair\CleanTags->checkTags(0)
#44 /var/www/html/owncloud/lib/private/Repair/CleanTags.php(67): OC\Repair\CleanTags->deleteOrphanTags(Object(OC\Repair))
#45 /var/www/html/owncloud/lib/private/Repair.php(87): OC\Repair\CleanTags->run(Object(OC\Repair))
#46 /var/www/html/owncloud/lib/private/Updater.php(267): OC\Repair->run()
#47 /var/www/html/owncloud/lib/private/Updater.php(150): OC\Updater->doUpgrade('9.1.5.2', '9.1.4.2')
#48 /var/www/html/owncloud/core/Command/Upgrade.php(290): OC\Updater->upgrade()
#49 /var/www/html/owncloud/3rdparty/symfony/console/Command/Command.php(259): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#50 /var/www/html/owncloud/3rdparty/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#51 /var/www/html/owncloud/3rdparty/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#52 /var/www/html/owncloud/3rdparty/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#53 /var/www/html/owncloud/lib/private/Console/Application.php(146): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#54 /var/www/html/owncloud/console.php(102): OC\Console\Application->run()
#55 /var/www/html/owncloud/occ(11): require_once('/var/www/html/o...')
#56 {main}[root@localhost owncloud]# exit

### Server configuration
**Operating system**:
CentOS Linux release 7.3.1611 (Core)

**Web server:**
Apache/2.4.6 (CentOS)

**Database:**
mysql  Ver 15.1 Distrib 5.5.52-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP Version => 7.0.17

**ownCloud version:** (see ownCloud admin page)
9.1.4

**Updated from an older ownCloud or fresh install:**
updated from older owncloud using yum update. Entire life of owncloud has 
been package managed via yum.

**Where did you install ownCloud from:**
yum update

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
can't login

**The content of config/config.php:**
[root@localhost owncloud]# sudo -u apache php occ config:list
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "0": [
            "localhost"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/synology\/data",
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "forcessl": true,
        "check_for_working_htaccess": false,
        "logtimezone": "America\/New_York",
        "theme": "",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trusted_domains": "***REMOVED SENSITIVE VALUE***",
        ],
        "version": "9.1.4.2",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 3,
        "mail_from_address": "cloud",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "htaccess.RewriteBase": "\/owncloud"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.3.2",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "27734"
        },
        "calendar": {
            "enabled": "no",
            "installed_version": "0.6.4",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "configreport": {
            "enabled": "yes",
            "installed_version": "0.1.1",
            "types": "filesystem"
        },
        "contacts": {
            "enabled": "no",
            "installed_version": "0.3.0.18",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "global_cache_gc_lastrun": "1436304853",
            "installedat": "1410548462.0067",
            "lastcron": "1492836973",
            "lastupdateResult": "[]",
            "lastupdatedat": "0",
            "oc.integritycheck.checker": "{\"core\":{\"EXTRA_FILE\":{\"core\\\/js\\\/js.js.orig\":{\"expected\":\"\",\"current\":\".htaccess.orig\":{\"expected\":\"\",\"current\":\"\"}}}}",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_links": "yes",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "shareapi_allow_public_upload": "yes",
            "shareapi_enforce_links_password": "no"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.2.7",
            "types": "filesystem"
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0.8.2",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.5.1",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "0.10.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.9.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "15.0.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": "prevent_group_restriction"
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.5.3",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.2.1",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.4",
            "ocsid": "166059",
            "types": ""
        },
        "user_ldap": {
            "cleanUpJobOffset": "100",
            "enabled": "yes",
            "enforce_home_folder_naming_rule": "",
            "installed_version": "0.9.0",
            "s01has_memberof_filter_support": "",
            "s01home_folder_naming_rule": "",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_attributes_for_group_search": "",
            "s01ldap_attributes_for_user_search": "",
            "s01ldap_backup_host": "",
            "s01ldap_backup_port": "",
            "s01ldap_base": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_base_groups": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_base_users": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_cache_ttl": "600",
            "s01ldap_configuration_active": "1",
            "s01ldap_display_name": "uid",
            "s01ldap_dn": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_dynamic_group_member_url": "",
            "s01ldap_email_attr": "mail",
            "s01ldap_experienced_admin": "0",
            "s01ldap_expert_username_attr": "uid",
            "s01ldap_expert_uuid_group_attr": "",
            "s01ldap_expert_uuid_user_attr": "",
            "s01ldap_group_display_name": "cn",
            "s01ldap_group_filter": "(&(|(objectclass=posixGroup)))",
            "s01ldap_group_filter_mode": "1",
            "s01ldap_group_member_assoc_attribute": "memberUid",
            "s01ldap_groupfilter_groups": "",
            "s01ldap_groupfilter_objectclass": "posixGroup",
            "s01ldap_host": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_login_filter": "uid=%uid",
            "s01ldap_login_filter_mode": "1",
            "s01ldap_loginfilter_attributes": "",
            "s01ldap_loginfilter_email": "0",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_nested_groups": "0",
            "s01ldap_override_main_server": "0",
            "s01ldap_paging_size": "500",
            "s01ldap_port": "636",
            "s01ldap_quota_attr": "",
            "s01ldap_quota_def": "",
            "s01ldap_tls": "",
            "s01ldap_turn_off_cert_check": "0",
            "s01ldap_user_display_name_2": "",
            "s01ldap_user_filter_mode": "1",
            "s01ldap_userfilter_groups": "",
            "s01ldap_userfilter_objectclass": "",
            "s01ldap_userlist_filter": "(objectclass=*)",
            "s01use_memberof_to_detect_membership": "1",
            "types": "authentication"
        }
    }
}

```


**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
yes


```

**Comment by kdslkdsaldsal** [comment]
@happiness-now  This is a duplicate of your already found https://github.com/owncloud/core/issues/26297 which is still open and unresolved. Please close here as it won't solve / help if multiple issues about the same issue are open.

**Comment by happiness-now** [comment]
This is similar but not duplicate.

**Comment by happiness-now** [comment]
The solutions near the bottom that worked in https://github.com/owncloud/core/issues/26297  do not solve our problem.  Therefore they are not identical.  

After doing a mainenance:repair as mentioned in above thread, our users receive access denied and CSRF errors.

**Comment by kdslkdsaldsal** [comment]
It is the same, no matter what you think. https://github.com/owncloud/core/issues/26297 is still open and unresolved so again: Please close here and follow https://github.com/owncloud/core/issues/26297.

If you can provide any additional info please do this there.

**Comment by happiness-now** [comment]
we agree to disagree. Enjoy.

**Comment by kdslkdsaldsal** [comment]
I don't know why you insist on it this way. You're just wasting time of people helping here and spreading the efforts pinpointing the issue and informations about the issue at several places.

If everyone thinks like this the issue tracker here would be flooded by ten thousands of issues and nothing would be fixed.
