### ISSUE TITLE
Update from 8.2.11 to 9.0.9 fails

### ISSUE THREAD

**Issue by rw71** [owncloud/core#27726]
### Steps to reproduce
1. Install 8.2.11
2. Copy new files 9.0.9 to the web space
3. Open in browser and start update

### Expected behaviour
Update to version 9.0.9

### Actual behaviour
Updating ownCloud to version 9.0.9, this may take a while.

Preparing update
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
Checked database schema update
Checking updates of apps
Checking whether the database schema for activity can be updated (this can take a long time depending on the database size)
Checking whether the database schema for files_external can be updated (this can take a long time depending on the database size)
Checking whether the database schema for files_sharing can be updated (this can take a long time depending on the database size)
Checking whether the database schema for files_trashbin can be updated (this can take a long time depending on the database size)
Checking whether the database schema for notifications can be updated (this can take a long time depending on the database size)
Checked database schema update for apps
Updating database schema
Updated database
Updated "files_pdfviewer" to 0.8.1
Updated "files_texteditor" to 2.1
Updated "files" to 1.4.4
Updated "activity" to 2.2.1
Updated "encryption" to 1.2.0
Updated "files_external" to 0.5.2
Updated "files_sharing" to 0.9.1
Updated "files_trashbin" to 0.8.0
Updated "files_versions" to 1.2.0
Updated "notifications" to 0.2.3
Updated "provisioning_api" to 0.4.1
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
The update was unsuccessful. Please report this issue to the ownCloud community.

### Server configuration
**Operating system**:
Linux 2.6.32-673.26.1.lve1.4.20.el6.x86_64

**Web server:**
Apache (version unknown)

**Database:**
mysql 5.5.54

**PHP version:**
PHP Version 7.0.16

**ownCloud version:** (see ownCloud admin page)
9.0.9

**Updated from an older ownCloud or fresh install:**
update from 8.2.11

**Where did you install ownCloud from:**
owncloud.org

**Signing status (ownCloud 9.0 and above):**
No admin login possible

**The content of config/config.php:**
No admin login possible

**List of activated apps:**
Default Apps + Encryption

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** yes/no
YES

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
**Browser:**
Safari 10.1

**Operating system:**
macOS Sierra 10.12.4

#### Web server error log
no logs available

#### ownCloud log (data/owncloud.log)
{"reqId":"Blb+FO\/GzlvHDxQGxZnv","remoteAddr":"178.165.130.234","app":"core","message":"starting upgrade from 8.2.11.1 to 9.0.9.1","level":0,"time":"2017-04-22T07:42:18+00:00","method":"GET","url":"\/cloudtest\/core\/ajax\/update.php?requesttoken=BwIyNjB1SiIlMx5qZCYWIWQqYxdrfSQuZTcvTlMg%3A7LCQFB0IbwZ%2BKhQb5z5uZ0IeRSExkf3tNg2MC8Ca","user":"--"}
{"reqId":"Blb+FO\/GzlvHDxQGxZnv","remoteAddr":"178.165.130.234","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/home\/.sites\/60\/site9274171\/web\/cloudtest\/lib\/private\/eventsource.php:111) at \/home\/.sites\/60\/site9274171\/web\/cloudtest\/lib\/private\/user\/session.php#309","level":3,"time":"2017-04-22T07:42:20+00:00","method":"GET","url":"\/cloudtest\/core\/ajax\/update.php?requesttoken=BwIyNjB1SiIlMx5qZCYWIWQqYxdrfSQuZTcvTlMg%3A7LCQFB0IbwZ%2BKhQb5z5uZ0IeRSExkf3tNg2MC8Ca","user":"--"}
{"reqId":"Blb+FO\/GzlvHDxQGxZnv","remoteAddr":"178.165.130.234","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/home\/.sites\/60\/site9274171\/web\/cloudtest\/lib\/private\/eventsource.php:111) at \/home\/.sites\/60\/site9274171\/web\/cloudtest\/lib\/private\/user\/session.php#310","level":3,"time":"2017-04-22T07:42:20+00:00","method":"GET","url":"\/cloudtest\/core\/ajax\/update.php?requesttoken=BwIyNjB1SiIlMx5qZCYWIWQqYxdrfSQuZTcvTlMg%3A7LCQFB0IbwZ%2BKhQb5z5uZ0IeRSExkf3tNg2MC8Ca","user":"--"}
{"reqId":"Blb+FO\/GzlvHDxQGxZnv","remoteAddr":"178.165.130.234","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/home\/.sites\/60\/site9274171\/web\/cloudtest\/lib\/private\/eventsource.php:111) at \/home\/.sites\/60\/site9274171\/web\/cloudtest\/lib\/private\/user\/session.php#311","level":3,"time":"2017-04-22T07:42:20+00:00","method":"GET","url":"\/cloudtest\/core\/ajax\/update.php?requesttoken=BwIyNjB1SiIlMx5qZCYWIWQqYxdrfSQuZTcvTlMg%3A7LCQFB0IbwZ%2BKhQb5z5uZ0IeRSExkf3tNg2MC8Ca","user":"--"}
{"reqId":"Blb+FO\/GzlvHDxQGxZnv","remoteAddr":"178.165.130.234","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/home\/.sites\/60\/site9274171\/web\/cloudtest\/lib\/private\/eventsource.php:111) at \/home\/.sites\/60\/site9274171\/web\/cloudtest\/lib\/private\/user\/session.php#314","level":3,"time":"2017-04-22T07:42:20+00:00","method":"GET","url":"\/cloudtest\/core\/ajax\/update.php?requesttoken=BwIyNjB1SiIlMx5qZCYWIWQqYxdrfSQuZTcvTlMg%3A7LCQFB0IbwZ%2BKhQb5z5uZ0IeRSExkf3tNg2MC8Ca","user":"--"}
{"reqId":"Blb+FO\/GzlvHDxQGxZnv","remoteAddr":"178.165.130.234","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/home\/.sites\/60\/site9274171\/web\/cloudtest\/lib\/private\/eventsource.php:111) at \/home\/.sites\/60\/site9274171\/web\/cloudtest\/lib\/private\/user\/session.php#315","level":3,"time":"2017-04-22T07:42:20+00:00","method":"GET","url":"\/cloudtest\/core\/ajax\/update.php?requesttoken=BwIyNjB1SiIlMx5qZCYWIWQqYxdrfSQuZTcvTlMg%3A7LCQFB0IbwZ%2BKhQb5z5uZ0IeRSExkf3tNg2MC8Ca","user":"--"}
{"reqId":"Blb+FO\/GzlvHDxQGxZnv","remoteAddr":"178.165.130.234","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/home\/.sites\/60\/site9274171\/web\/cloudtest\/lib\/private\/eventsource.php:111) at \/home\/.sites\/60\/site9274171\/web\/cloudtest\/lib\/private\/user\/session.php#316","level":3,"time":"2017-04-22T07:42:20+00:00","method":"GET","url":"\/cloudtest\/core\/ajax\/update.php?requesttoken=BwIyNjB1SiIlMx5qZCYWIWQqYxdrfSQuZTcvTlMg%3A7LCQFB0IbwZ%2BKhQb5z5uZ0IeRSExkf3tNg2MC8Ca","user":"--"}
{"reqId":"Blb+FO\/GzlvHDxQGxZnv","remoteAddr":"178.165.130.234","app":"core","message":"No update found at the ownCloud appstore for app 166054","level":0,"time":"2017-04-22T07:42:25+00:00","method":"GET","url":"\/cloudtest\/core\/ajax\/update.php?requesttoken=BwIyNjB1SiIlMx5qZCYWIWQqYxdrfSQuZTcvTlMg%3A7LCQFB0IbwZ%2BKhQb5z5uZ0IeRSExkf3tNg2MC8Ca","user":"--"}
{"reqId":"Blb+FO\/GzlvHDxQGxZnv","remoteAddr":"178.165.130.234","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/.sites\\\/60\\\/site9274171\\\/web\\\/cloudtest\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/home\\\/.sites\\\/60\\\/site9274171\\\/web\\\/cloudtest\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(945): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'CREATE TABLE `o...')\\n#2 \\\/home\\\/.sites\\\/60\\\/site9274171\\\/web\\\/cloudtest\\\/lib\\\/private\\\/db\\\/mdb2schemamanager.php(167): Doctrine\\\\DBAL\\\\Connection->query('CREATE TABLE `o...')\\n#3 \\\/home\\\/.sites\\\/60\\\/site9274171\\\/web\\\/cloudtest\\\/lib\\\/private\\\/db\\\/mdb2schemamanager.php(70): OC\\\\DB\\\\MDB2SchemaManager->executeSchemaChange(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema))\\n#4 \\\/home\\\/.sites\\\/60\\\/site9274171\\\/web\\\/cloudtest\\\/lib\\\/private\\\/db.php(172): OC\\\\DB\\\\MDB2SchemaManager->createDbFromStructure('\\\/home\\\/.sites\\\/60...')\\n#5 \\\/home\\\/.sites\\\/60\\\/site9274171\\\/web\\\/cloudtest\\\/lib\\\/private\\\/installer.php(586): OC_DB::createDbFromStructure('\\\/home\\\/.sites\\\/60...')\\n#6 \\\/home\\\/.sites\\\/60\\\/site9274171\\\/web\\\/cloudtest\\\/lib\\\/private\\\/installer.php(556): OC_Installer::installShippedApp('dav')\\n#7 \\\/home\\\/.sites\\\/60\\\/site9274171\\\/web\\\/cloudtest\\\/lib\\\/private\\\/updater.php(334): OC_Installer::installShippedApps(true)\\n#8 \\\/home\\\/.sites\\\/60\\\/site9274171\\\/web\\\/cloudtest\\\/lib\\\/private\\\/updater.php(212): OC\\\\Updater->doUpgrade('9.0.9.1', '8.2.11.1')\\n#9 \\\/home\\\/.sites\\\/60\\\/site9274171\\\/web\\\/cloudtest\\\/core\\\/ajax\\\/update.php(120): OC\\\\Updater->upgrade()\\n#10 {main}\",\"File\":\"\\\/home\\\/.sites\\\/60\\\/site9274171\\\/web\\\/cloudtest\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}","level":3,"time":"2017-04-22T07:42:25+00:00","method":"GET","url":"\/cloudtest\/core\/ajax\/update.php?requesttoken=BwIyNjB1SiIlMx5qZCYWIWQqYxdrfSQuZTcvTlMg%3A7LCQFB0IbwZ%2BKhQb5z5uZ0IeRSExkf3tNg2MC8Ca","user":"--"}

**Comment by kdslkdsaldsal** [comment]
>  Specified key was too long; max key length is 1000 bytes

Putting this into the search of the repository here:

https://github.com/owncloud/core/search?q=Specified+key+was+too+long%3B+max+key+length+is+1000+bytes&state=open&type=Issues&utf8=%E2%9C%93

is showing: https://github.com/owncloud/core/issues/23988 which is still open and unresolved

Please close here and follow the linked issue above.

**Comment by PVince81** [comment]
> Copy new files 9.0.9 to the web space

You need to delete the old source files first else there will be a mix of old files with new ones.
