### ISSUE TITLE
Sharing autocomplete user box  does not complete if avatar are disabled 

### ISSUE THREAD

**Issue by ppaysant** [owncloud/core#27734]
### Steps to reproduce
1. Have some users, sharing allowed
2. Disable avatar in conf ( `'enable_avatars' => false`)
3. Click on share icon on a flie or dir, begin typing a user uid in user box

### Expected behaviour
The autocomplete displays all uid beginning with what you typed

### Actual behaviour
Nothing appears
"avatar.avatar is not a function" appears in JS console

### Server configuration

**ownCloud version:** (see ownCloud admin page)
master branch from github (up on commit 60bbf53b48664dad99db79dbea23f8683c9955a4)

**Updated from an older ownCloud:**
```
php ./occ status
  - installed: true
  - version: 10.0.0.8
  - versionstring: 10.0.0 RC2
  - edition: Community
```

**The content of config/config.php:**
`'enable_avatars' => false,`

### Client configuration
**Firefox 52**

#### Browser log
```
TypeError: avatar.avatar is not a function[En savoir plus]  sharedialogview.js:303:5
```

**Comment by PVince81** [comment]
I suspect that when avatars are disabled, the library about avatars isn't loaded.

But some code might still be using this function.

Two possible fixes, either:

1) Always load the avatar jquery plugins
or
2) Fix the code to not assume it's always there

**Comment by ppaysant** [comment]
Commenting these lines (https://github.com/owncloud/core/blob/master/core/js/sharedialogview.js#L301-L306) solves the problem. But it sure is not the correct solution :smile:

**Comment by ppaysant** [comment]
I like best the second solution (fix the code) !! OC already loads a ton of js libs...
