### ISSUE TITLE
Fix app manager to properly run migration when enabling

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27736]
The app manager and legacy app code is a mess.

An app can have many states:
1) no code
2) code is there but not marked as installed (needs an "installed_version" field in DB)
3) code exists, app is marked installed but not enabled
4) code exists, app marked enabled
5) code exists, app marked disabled
6) app marked enabled/disabled/installed but code is missing
7) ...

Apparently when transitioning from 2) to 3) some code paths will trigger the app's migration while others don't.

This needs to be simplified and uniformized.
But first I'd suggest getting rid of the old legacy/app.php and put more of the logic into the app manager.

@DeepDiver1975 @butonic

**Comment by VicDeo** [comment]
yep, this part AppManager, Installer, OC_App needs to be carefully redesigned.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
