### ISSUE TITLE
High CPU usage >70%

### ISSUE THREAD

**Issue by Daniel-Esser** [owncloud/core#27738]
![image](https://cloud.githubusercontent.com/assets/7695350/25375538/4d9fd048-29a1-11e7-9313-bf42d634e3c8.png)

### Expected behaviour
Normal cpu usage.

### Actual behaviour
permanent CPU usage > 70% up to 90% 

### Server configuration
**Operating system**:
Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-72-generic x86_64)

**Web server:**
Package: apache2
Status: install ok installed
Priority: optional
Section: httpd
Installed-Size: 488
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 2.4.18-2ubuntu3.1

**Database:**

**PHP version:**
Section: php
Installed-Size: 11
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Source: php-defaults (35ubuntu6)
Version: 1:7.0+35ubuntu6
Depends: php7.0

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.1.4 (stable)

**Updated from an older ownCloud or fresh install:**
Fresh

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

**http://example.com/index.php/settings/integrity/failed **
https://gist.github.com/Daniel-Esser/444db2c47fbd49dc225c8765ac7995bd

**'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'**
https://gist.github.com/Daniel-Esser/57b38f233f23767b0fd8b19939b0b81c

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Operating system:**
Windows 10

**OwnCloud Client Version:**
2.3.1 6824

**Comment by kdslkdsaldsal** [comment]
> permanent CPU usage > 70% up to 90%

You might need to explain where you're seeing this permanent CPU usage. On the server or on the client?

If its on the client then you might need to reopen this in https://github.com/owncloud/client/issues

**Comment by Daniel-Esser** [comment]
You're right. Its a client issue. Please close this. Thank you!

**Comment by kdslkdsaldsal** [comment]
@Daniel-Esser You can close this on your own with the close button below the comment field.
