### ISSUE TITLE
SUBJECT_SHARED_LINK_SELF has no parameter, username or email address

### ISSUE THREAD

**Issue by phpweb** [owncloud/core#27745]
Version: 9.1.4
Defined at: apps/files_sharing/lib/Activity.php
Line: 287
Text: 'Shared via public link'
`$l->t('Shared via public link');`

No parameter like the other activity messages like **Shared via link by %2$s**
Here it is impossible to personalize the activity message with username or email address when someone shares his file with somebody else. For example for other messages there is at least a parameter to personalize the message: 

`$l->t('Shared via link by %2$s', $params)` 

In Backend you can see this message informative: Shared via link by **User**

Please add paramater possibility to the activity message in case of _SUBJECT_SHARED_LINK_SELF_

Thanks in advance.

**Comment by PVince81** [comment]
Mind submitting a PR ?
