### ISSUE TITLE
(disable) Update dialog for version not available in GitHub or manual download

### ISSUE THREAD

**Issue by liamdennehy** [owncloud/core#27741]
### Expected behaviour
App Update prompt can be disabled
*or*
App Update should track GitHub versions/releases

### Actual behaviour
Prompt to upgrade an app to a version not available in GitHub. No option to skip since source is unavailable.

### Steps to reproduce
1. This is timely, so will likely fail once a the specific release below is tagged in GitHub
2. Check git repository for latest release version:
```
server1 calendar-github # git fetch
server1 calendar-github # git tag
v1.0
---snip---
v1.3.3
v1.4.0
```
2. Install (e.g.) calendar app v1.4.0 to a local folder, which is symlinked to 'calendar':
```
server1 calendar-github # cd ../calendar-1.4.0  
server1 calendar-1.4.0 # git --work-tree=. --git-dir=../calendar-github/.git checkout -b v1.4.0 v1.4.0
--many many files snipped--
D       timezones/PACIFIC-YAP.ics
Switched to a new branch 'v1.4.0'
```
3. Enable calendar app
4. Use owncloud, and cannot go past the App Upgrade required, which expects v1.4.1, not available in GitHub.
5. Since the app files are not owned by httpd user they cannot be upgraded, so not worth starting.

### Server configuration  
- Operating system: Gentoo  
- Web server: Apache-2.4
- Database: MariaDB 10
- PHP version: 5.22
- ownCloud version: 9.1.5
- Storage backend (external storage): -

**Comment by kdslkdsaldsal** [comment]
Its probably just a matter of re-claim https://apps.owncloud.com/content/show.php/Calendar?content=168707 where currently https://github.com/nextcloud/calendar/issues and not https://github.com/owncloud/calendar/issues is published.

cc @felixheidecke as calendar maintainer and @DeepDiver1975
