### ISSUE TITLE
Let admin disable apps in update UI

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27747]
Since 10.0.0 `occ upgrade` will not start updating if any app has missing code, is not compatible and cannot be repaired by fetching it from the marketplace.

This works fine on the CLI as the admin can disable the apps manually.
However for setups that don't have CLI access, they can't disable the app in the web UI.

This ticket is for providing a way to disable apps in the web UI.

Problems: web UI is visible for **every** user, not only the admin. It is not safe to allow people to disable apps.

The web UI could first run the update and if apps need to be disabled, have a button to rerun the upgrade but this time disabling the problematic apps automatically. This could simply reload the page with an extra argument.

@VicDeo

**Comment by DeepDiver1975** [comment]
alternative: kill web update

**Comment by noveens** [comment]
@PVince81 ,
Show the non-admin users to ask their sys-admin to first upgrade their OC instance?
Then we don't even need a web-update. Ideas?

**Comment by PVince81** [comment]
the web update page is mostly for users who installed OC on hosters that don't provide CLI access (like simple PHP web page hosters). In these cases you usually can't ask their admins to run your CLI command for you, that's not part of their "simple PHP web page" service.

**Comment by noveens** [comment]
Hmm.. Makes sense. Then the solution you described in the bug description seems the most viable. I'll try to send a PR.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
