### ISSUE TITLE
Upgrade from 9.1.5 to 10.0.0 fails if user has no avatar.jpg

### ISSUE THREAD

**Issue by CRCinAU** [owncloud/core#27757]
If a user does not have an avatar in $datadirectory/$username/avatar.jpg, upgrading via 'occ upgrade' will fail.

```
2017-04-28T01:16:57+10:00 Repair step: Move user avatars outside the homes to the new location
2017-04-28T01:16:57+10:00 Move user avatars outside the homes to the new location
                                                    2017-04-28T01:16:58+10:00  Starting ...
 2/3 [==================>]  66%2017-04-28T01:16:58+10:00 OCP\Files\NotPermittedException: Could not move /<account>/avatar.jpg to /avatars/f6/42/5e5324e3828ba56f77b6dd561aa5/avatar.jpg
2017-04-28T01:16:58+10:00 Update failed
```

A workaround is to:
```
$ touch data/<account>/avatar.jpg
$ chown apache.apache data/<account>/avatar.jpg
```

Then run the upgrade again.

**Comment by davitol** [comment]
@CRCinAU Can you please fill the issue template in order to give us more feedback?
BTW I have upgraded from 9.1.5 to 10.0.0 without avatars set and no problems were found. Thanks in advanced.

**Comment by PVince81** [comment]
closing due to lack of feedback

**Comment by euphi** [comment]
I ran into the same problem.

Maybe the cause is that I had an avatar set, but it was not stored at `data/<user>/avatar.jpg` ? (I don't know where it was stored, but not there...)


> root@cubietruck:/var/www/owncloud# sudo -u www-data php ./occ upgrade              
> ownCloud or one of the apps require upgrade - only a limited number of commands are available
> You may use your browser or the occ upgrade command to do the upgrade
> Set log level to debug
> Updating database schema
> Updated database
> Updating <dav> ...
> Updated <dav> to 0.2.9
> Updating <files_external> ...
> Updated <files_external> to 0.7.0
> Drop old database tables
> 
>  Done
>  28/28 [============================] 100%
> Fix permissions so avatars can be stored again
>  Done
>  2/2 [============================] 100%
> Move user avatars outside the homes to the new location
>  Starting ...
>  3/5 [================>-----------]  60%OCP\Files\NotPermittedException: Could not move /ian/avatar.jpg to /avatars/a7/1a/448d3d8474653e831749b8e71fcc/avatar.jpg
> Update failed
> Maintenance mode is kept active
> Reset log level

[...]

> root@cubietruck:/var/www/owncloud# mkdir data/ian
> root@cubietruck:/var/www/owncloud# touch data/ian/avatar.jpg
> root@cubietruck:/var/www/owncloud# chown -R www-data data/ian/
> root@cubietruck:/var/www/owncloud# sudo -u www-data php ./occ upgrade
> ownCloud or one of the apps require upgrade - only a limited number of commands are available
> You may use your browser or the occ upgrade command to do the upgrade
> Set log level to debug
> Updating database schema
> Updated database
> Drop old database tables
> 
>  Done
>  28/28 [============================] 100%
> Fix permissions so avatars can be stored again
>  Done
>  2/2 [============================] 100%
> Move user avatars outside the homes to the new location
>  Done
>  5/5 [============================] 100%
> Starting code integrity check...
> Finished code integrity check
> Update successful
> Maintenance mode is kept active
> Reset log level

**Comment by euphi** [comment]
Oh.. and my avatar is broken now... (quite obvious, when the upgrade process copies an empty file..).

**Comment by juergensachs** [comment]
Does the update really wants to move to avatar to "/avatars/..." (subdirectory of "root")? This cannot work on WEB hosters...

**Comment by PVince81** [comment]
Not, it should be the subdirectory of "data". The printed path is likely the relative path.

**Comment by CristianCardosoA** [comment]
@CRCinAU 

$ touch data/<account>/avatar.jpg
$ chown apache.apache data/<account>/avatar.jpg

This workaround doesn't work for me.

**Comment by ltning** [comment]
This one hit me upgrading from 10.0.9 to 10.0.10 today. I have *no* idea why this fails for this user. There isn't even an avatar.jpg in the <username> folder, but there is one in the avatars/..../ folder.

All files are correctly owned by the www/owncloud user.

**Comment by ltning** [comment]
Also - it seems to apply to all users. I copied the avatars/.../avatar.jpg file to the <username>/ folder, made sure it's owned by the correct user, and then occ upgrade successfully handled that user but failed on the next one. We have hundreds of users, and mapping from user ID to username is .. not something I'd like to have to do for each.

**Comment by PVince81** [comment]
@ltning mind posting more details ? The "move user avatars outside the homes..." job should not even run any more when upgrading from 10.0.9 to 10.0.10.

So either you found a bug and it does run. Or you bumped into another completely different issue.

Please post logs, etc.

**Comment by PVince81** [comment]
if it behaved differently after restoring from backup, it is likely that you missed restoring some bits (database + old OC source code + old data directory), which might or might be have caused it to be confused about the current version state.

Was there any errors in the owncloud.log from the time of the avatar issue ?
