### ISSUE TITLE
Missing user_ldap after Upgrade to 10

### ISSUE THREAD

**Issue by cvantum** [owncloud/core#27768]
### Steps to reproduce
1. Installed new Update from Repository
2. Did ```sudo -u www-data php occ upgrade```
3. Received Error for App "user_ldap" which should be disabled
4. Disabled "user_ldap" with ```sudo -u www-data php occ app:disable user_ldap```
5. Continued Upgrade and deactivated maintenance mode

### Actual behaviour

After Upgrade it wasn't possible enable "user_ldap" again

```
sudo -u www-data php occ app:enable user_ldap
user_ldap not found
```
Also i didn't found any files in ```/var/www/owncloud/apps```. The config-Setting in mysql are still available.

At the moment it is not possible to login as a LDAP-User

### Server configuration
**Operating system**: Debian Jessie 

**Web server:** 
```
dpkg -l apache2
ii  apache2   2.4.10-10+deb8u8   amd64   Apache HTTP Server
```

**Database:**
```
dpkg -l mysql-server
ii  mysql-server  5.5.55-0+deb8u1  all  MySQL database server
```

**PHP version:**
```
dpkg -l php5
ii  php5  5.6.30+dfsg-0+deb8u1  all  server-side, HTML-embedded scripting language (metapackage)
```

**ownCloud version:** 10.0

**Updated from an older ownCloud or fresh install:** Update from 9.2

**Where did you install ownCloud from:**
```
deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /
```

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```
**List of activated apps:**

```
sudo -u www-data php occ app:list
Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.8
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - activity
  - encryption
  - example-theme
  - external
  - files_antivirus
  - files_texteditor
  - firstrunwizard
  - templateeditor
  - user_external
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

**Comment by DeepDiver1975** [comment]
user_ldap will arrive in the next days via the marketplace - this was communicated via the release notes

**Comment by ScottyTM** [comment]
Maybe I'm looking at the wrong release notes (https://doc.owncloud.org/server/10.0/admin_manual/release_notes.html), but there's no mention of this there! Why the hell was something with such a major regression pushed to the stable package repository?

**Comment by kdslkdsaldsal** [comment]
> this was communicated via the release notes

Which seems didn't worked out as the release notes where updated correctly 3 days ago with https://github.com/owncloud/documentation/pull/3024 but it never got published as shown above.
