### ISSUE TITLE
Updating to 10.0.0 from 9.1.4 - update coudn't finish and now owncloud is crashed - please help

### ISSUE THREAD

**Issue by FKBOX** [owncloud/core#27769]
### Steps to reproduce
1. Sudo apt-get update, sudo apt-get upgrade
2. owncloud stucks in maintenance mode - manual change and update
3.

### Expected behaviour
Tell us what should happen
Updating to 10.0.0

### Actual behaviour
Tell us what happens instead
Error:

Updating to 10.0.0

OC\RepairException: Upgrade is not possible
Repair warning: You have incompatible or missing apps enabled.
Repair warning: please install app manually with tarball or disable them occ app:disable calendar occ app:disable contacts occ app:disable documents occ app:disable ownnote occ app:disable tasks

Detailed logs
Preparing update
Set log level to debug
Turned on maintenance mode
Repair warning: You have incompatible or missing apps enabled.
Repair warning: please install app manually with tarball or disable them occ app:disable calendar occ app:disable contacts occ app:disable documents occ app:disable ownnote occ app:disable tasks
OC\RepairException: Upgrade is not possible
The update was unsuccessful. Please report this issue to the ownCloud community.
### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache2 web server

**Database:** Mysql 
+-------------------------+-------------------------+
| Variable_name           | Value                   |
+-------------------------+-------------------------+
| innodb_version          | 5.7.18                  |
| protocol_version        | 10                      |
| slave_type_conversions  |                         |
| tls_version             | TLSv1,TLSv1.1           |
| version                 | 5.7.18-0ubuntu0.16.04.1 |
| version_comment         | (Ubuntu)                |
| version_compile_machine | x86_64                  |
| version_compile_os      | Linux                   |
+-------------------------+-------------------------+

**PHP version:**
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
**ownCloud version:** (see ownCloud admin page)
9.1.4.2
**Updated from an older ownCloud or fresh install:**
9.1.2
**Where did you install ownCloud from:**
sh -c "echo 'deb http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ /' > /etc/apt/sources.list.d/owncloud.list"
apt-get update
apt-get install owncloud
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
Can't login, because owncloud didn't finish and is in an intermediate state

**The content of config/config.php:**
<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'wuyk',
  'passwordsalt' => 'X/VZRJ',
  'secret' => 'oRdWInUaUmXO',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'xxbox',
    2 => 'xxbox.dyndns.org',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://localhost/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'cloudadmin',
  'dbpassword' => 'xxxxxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => true,
  'theme' => '',
  'loglevel' => 2,
  'mail_from_address' => 'xx',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'bruehl-west.de',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'bruehl-west.de',
  'mail_smtpport' => '465',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'xxx@bruehl-west.de',
  'mail_smtppassword' => 'drülf72',
);
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.1
  - dav: 0.2.7
  - documents: 0.13.1
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: 0.9.0.0
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - ownbackup: 16.11.0
  - ownnote: 1.08
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.4
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - bookmarks
  - encryption
  - example-theme
  - external
  - market
  - richdocuments
  - user_external

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder
 [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace.     

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
firefox
**Operating system:**
windows7
#### Web server error log
same as above on the ubuntu server itself
```
Insert your webserver log here
[Thu Apr 27 22:38:43.264825 2017] [:error] [pid 4986] [client 78.94.90.42:49896] PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /var/www/owncloud/lib/private/DB/Connection.php:58\nStack trace:\n#0 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/owncloud/lib/private/DB/Connection.php(141): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doc in /var/www/owncloud/lib/private/DB/Connection.php on line 58

Insert your ownCloud log here
#### ownCloud log (data/owncloud.log)
{"reqId":"JrcIOYMXTy2PWW7eBkbc","level":0,"time":"2017-04-27T21:19:44+00:00","remoteAddr":"78.94.90.42","user":"--","app":"core","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=BgU1IQY9SiRBOi8WCB0gXRsiIAcyKzIGFg0CQDxgIF4%3D%3AuvzonIyj7JGoMDd4toJHSLTwpwjxuYwu7kJBwZlYupQ%3D","message":"starting upgrade from 9.1.4.2 to 10.0.0.12"}
{"reqId":"JrcIOYMXTy2PWW7eBkbc","level":3,"time":"2017-04-27T21:19:44+00:00","remoteAddr":"78.94.90.42","user":"--","app":"core","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=BgU1IQY9SiRBOi8WCB0gXRsiIAcyKzIGFg0CQDxgIF4%3D%3AuvzonIyj7JGoMDd4toJHSLTwpwjxuYwu7kJBwZlYupQ%3D","message":"Exception: {\"Exception\":\"OC\\\\RepairException\",\"Message\":\"Upgrade is not possible\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Repair.php(89): OC\\\\Repair\\\\Apps->run(Object(OC\\\\Repair))\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(212): OC\\\\Repair->run()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Updater.php(108): OC\\\\Updater->doUpgrade('10.0.0.12', '9.1.4.2')\\n#3 \\\/var\\\/www\\\/owncloud\\\/core\\\/ajax\\\/update.php(190): OC\\\\Updater->upgrade()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Repair\\\/Apps.php\",\"Line\":131}"}
{"reqId":"n6PC1s36fXcuD8dxfzGl","level":0,"time":"2017-04-27T21:36:31+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"starting upgrade from 9.1.4.2 to 10.0.0.12"}

#### Browser log
no error logs on that date
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by VicDeo** [comment]
@FKBOX it's not a crash, just
```
 please install app manually with tarball or disable them 
occ app:disable calendar
occ app:disable contacts 
occ app:disable documents 
occ app:disable ownnote 
occ app:disable tasks
```

**Comment by VicDeo** [comment]
Just to clarify: we are not disabling not compatible apps on update any more as asked by community.
Instead of disabling apps are updated automatically from marketplace now.

Basically you have two options at that point:
1. You can disable these apps on your own via cli or db as described https://central.owncloud.org/t/how-to-disable-an-app-without-access-to-the-gui/832

2. You can download app packages from marketplace on your own and replace current apps with compatible versions:
calendar https://marketplace.owncloud.com/apps/calendar
contacts https://marketplace.owncloud.com/apps/contacts
in this case you should disable `documents`, `ownnote`  and `tasks` anyway because they have no versions compatible with ownCloud X yet.

**Comment by FKBOX** [comment]
there is no information in the link how to disable the apps in that link??? Autoupdate means first ask and then disable apps or do not update, but I wasn't asked. I never heard about tarball, what is it?
What is the right syntax to disable apps? Where can I disable them in the database? In intermediate state occ commands are limited!

**Comment by FKBOX** [comment]
occ app:disable calendar
occ app:disable contacts 
occ app:disable documents 
occ app:disable ownnote 
occ app:disable tasks
do not work
/var/www/owncloud$ sudo -u www-data php occ app:disable calendar
ownCloud or one of the apps require upgrade - only a limited number of commands are available

**Comment by FKBOX** [comment]
/var/www/owncloud$ sudo -u www-data /var/www/owncloud/occ app:disable calendar
This command worked. I got same message 'ownCloud or one of the apps require upgrade - only a limited number of commands are available', but it disabled the app checked that with phpmyadmin in the database.
Then I could update and cloud is working fine. New calender app 1.4.2 for owncloud X is not working in any browser and Iphone can't read data!? In Firefox the loading icon rotates for ever!
Anyone who can solve that?

**Comment by kdslkdsaldsal** [comment]
@FKBOX Then you can close this issue. For the calendar problem see the following thread:

https://central.owncloud.org/t/owncloud-x-10-0-x-known-issues-faq-and-upgrade-problems/7258/4
