### ISSUE TITLE
Users can be locked out if the account is disabled while they're logged in

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#27767]
### Steps to reproduce
1. Log in with a user
2. Access the server and run occ command to disable the same user
3. Navigate through ownCloud with the logged in user

### Expected behaviour
User is kicked out to the login screen. The user could be able to login with another account.

### Actual behaviour
Only "User is disabled" message appears. The user can't do anything (not even login with any other account). The problem might be the autologin feature, trying to login automatically with a disabled account. As said, the user can't do anything.

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** apache

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.0

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** tarball

**Signing status (ownCloud 9.0 and above):**

Setting as sev4 since the behaviour is expected. The user should only have one account, so even if the user is kicked out to the logging screen he shouldn't be able to access ownCloud.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
