### ISSUE TITLE
Package dependencies for ownCloud 10.0.0 are incorrect for Ubuntu 14.04

### ISSUE THREAD

**Issue by gbkersey** [owncloud/core#27761]
### Steps to reproduce
upgrade owncloud packages
1. apt-get update && apt-get -y upgrade 
Upgrades owncloud from 9.1.5-1.1 to 10.0.0-1.1
2. sudo -u www-data php /var/www/owncloud/occ maintenance:mode --off

### Expected behaviour
The package upgrade should not proceed if the dependencies for the software are not met.

### Actual behaviour
The package upgrade completes, but occ upgrade does not work because the PHP version is not high enough....

This version of ownCloud requires at least PHP 5.6.0
You are currently running 5.5.9-1ubuntu4.21. Please update your PHP version.

### Server configuration
**Operating system**:
Ubuntu 14.04.5 LTS

**Web server:**
apache 2.4.7-1ubuntu4.13

**Database:**
mariadb 5.5.54-1ubuntu0.14.04.1

**PHP version:**
php5 5.5.9+dfsg-1ubuntu4.21

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.1.5 (stable)

**Updated from an older ownCloud or fresh install:**
upgraded several times from older versions

**Where did you install ownCloud from:**
http://download.owncloud.org/download/repositories/stable/Ubuntu_14.04/

**Signing status (ownCloud 9.0 and above):**
passed

**Suggested fix:
owncloud-deps-php5 should depend on php5 (>= 5.6.0)

```
--- owncloud-10.0.0/debian/control.orig	2017-04-27 15:37:57.000000000 -0500
+++ owncloud-10.0.0/debian/control	2017-04-27 16:07:52.839586806 -0500
@@ -32,7 +32,7 @@
 Provides: owncloud-deps
 # https://github.com/owncloud/core/issues/21342
 # https://github.com/owncloud/core/issues/23878
-Depends: ${misc:Depends}, php5 (>= 5.4.0), 
+Depends: ${misc:Depends}, php5 (>= 5.6.0), 
 	php5-common, php5-gd, php-xml-parser, php5-intl, php5-mcrypt, php5-curl, php5-json, 
 	php5-mysqlnd | php5-mysql, php5-sqlite, php5-pgsql, 
 	php5-cgi | php5-fpm | libapache2-mod-php5,
```

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
