### ISSUE TITLE
Aktualisierung auf 10.0.0

### ISSUE THREAD

**Issue by ruesack** [owncloud/core#27763]
OC\RepairException: Upgrade is not possible

        Reparaturwarnung:You have incompatible or missing apps enabled.
        Reparaturwarnung:please install app manually with tarball or disable them occ app:disable calendar occ app:disable contacts

Detaillierte Fehlermeldungen
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturwarnung:You have incompatible or missing apps enabled.
Reparaturwarnung:please install app manually with tarball or disable them occ app:disable calendar occ app:disable contacts
OC\RepairException: Upgrade is not possible

**Comment by sergeycccv** [comment]
In the terminal, you need to disable Calendar and Contacts:
```
sudo -u www-data php occ app:disable calendar
sudo -u www-data php occ app:disable contacts
```

**Comment by ruesack** [comment]
Thanks,
after disabling the calendar and contacts the update works fine. But after updating and enabling the calendars, no calendar will be displayed. contacts are fine.

any idea?

**Comment by butonic** [comment]
@ruesack likely https://github.com/owncloud/core/issues/27754 ?

**Comment by ruesack** [comment]
YES! Thats were the reason!
!!!THANKS!!! to sergeycccv and butonic for the good hints

Everything work fine now...
