### ISSUE TITLE
Update Scripts: Incorrect use of double quotes in SQL Statement

### ISSUE THREAD

**Issue by manngo** [owncloud/core#27773]
The Update scripts contain a minor technical error with the MySQL Statements used.

On two occasions,

	lib/private/Repair/InnoDB.php
	lib/private/Repair/Collation.php

 the following SQL fragment appears:

	TABLE_NAME LIKE \"*PREFIX*%\"

This presupposes that MySQL will treat double quotes in its normal non-standard way as string delimiters.

I have set my own database to run in ANSI mode, so this fails.

It is easily fixed:

	TABLE_NAME LIKE '*PREFIX*%'

The irony is:

- elsewhere, single quotes are used for strings
- in this case, inside a double quoted string, single quotes are more convenient anyway.

**Comment by PVince81** [comment]
@DeepDiver1975 is this related to migrations ?

**Comment by DeepDiver1975** [comment]
> is this related to migrations ?

no - related to people trying to write mysql specific sql .... and fail ...

**Comment by PVince81** [comment]
@DeepDiver1975 can you have a look ? If not please let me know
