### ISSUE TITLE
Upgrade from 9.1.4 to 9.1.5, ldap quota lost

### ISSUE THREAD

**Issue by jftempo** [owncloud/core#27771]
### Steps to reproduce
1. from version 9.1.4, users stored in ldap, ldap Quota Field is empty, users have custom quota values
2. Upgrade to 9.1.5
3. Users quota are reset to 100 MB, if I change a user quota the value is not saved

### Expected behaviour
1. do not reset custom user quota after upgrade
2. change of user quota not stored in ldap should be saved

### Actual behaviour
I change a user quota in the user manager. New quota value is not applied, if I reload the user manager, the old quota (100 MB ) is displayed.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** PostgreSQL

**PHP version:** PHP 7.0.15-0ubuntu0.16.04.4

**ownCloud version:** 9.1.5

**Updated from an older ownCloud or fresh install:** from 9.1.4 to 9.1.5

#### LDAP configuration (delete this part if not used)
| ldapQuotaAttribute            |                                                                              |
| ldapQuotaDefault              | 102400                                                                       |

**Comment by DeepDiver1975** [comment]
Please reopen in the repo user_ldap. Thx
