### ISSUE TITLE
Calendar extension bug

### ISSUE THREAD

**Issue by tvillanova** [owncloud/core#27772]
### Steps to reproduce
1. calendar extension
2.
3.

### Expected behaviour
Display my calendar

### Actual behaviour
Calendar load icon, and don't appear

### Server configuration
**Operating system**:
linux debian raspbian
**Web server:**
apache2
**Database:**
mysql

i've this error it seems to be in my database

`Exception: {"Message":"An exception occurred while executing 'SELECT * FROM `oc_properties` WHERE `userid` = ? AND `propertypath` = ? AND `propertyname` in (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"mafioporto\", \"calendars\\\/mafioporto\", \"{DAV:}displayname\", \"{urn:ietf:params:xml:ns:caldav}calendar-description\", \"{urn:ietf:params:xml:ns:caldav}calendar-timezone\", \"{http:\\\/\\\/apple.com\\\/ns\\\/ical\\\/}calendar-order\", \"{http:\\\/\\\/apple.com\\\/ns\\\/ical\\\/}calendar-color\", \"{urn:ietf:params:xml:ns:caldav}supported-calendar-component-set\", \"{http:\\\/\\\/calendarserver.org\\\/ns\\\/}publish-url\", \"{http:\\\/\\\/calendarserver.org\\\/ns\\\/}allowed-sharing-modes\", \"{http:\\\/\\\/owncloud.org\\\/ns}calendar-enabled\", \"{http:\\\/\\\/owncloud.org\\\/ns}invite\", \"{http:\\\/\\\/calendarserver.org\\\/ns\\\/}source\"]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'userid' in 'where clause'","Exception":"Doctrine\\DBAL\\Exception\\InvalidFieldNameException","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(836): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT * FROM `...', Array)\n#2 \/var\/www\/owncloud\/lib\/private\/DB\/Connection.php(188): Doctrine\\DBAL\\Connection->executeQuery('SELECT * FROM `...', Array, Array, NULL)\n#3 \/var\/www\/owncloud\/apps\/dav\/lib\/Files\/CustomPropertiesBackend.php(191): OC\\DB\\Connection->executeQuery('SELECT * FROM `...', Array, Array)\n#4 \/var\/www\/owncloud\/apps\/dav\/lib\/Files\/CustomPropertiesBackend.php(107): OCA\\DAV\\Files\\CustomPropertiesBackend->getProperties('calen`

thank you

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/core/pull/27756
