### ISSUE TITLE
Owncloud 9 to 10 upgrade is a shame.

### ISSUE THREAD

**Issue by devmarxx** [owncloud/core#27774]
Issues:

The GUI says "Apps" instead of "Files" in the corner up left.

Calendar not working.

Documents not working.
Mail not working.

Market is complicated and confusing.

I'm back to Owncloud 9.

What a mess, what a shame, what a pitty ...

**Comment by tflidd** [comment]
> The GUI says "Apps" instead of "Files" in the corner up left.

Can you share a bit more about your setup, log files, browser logs?



> Calendar not working.

for calendar, there are known issues (https://github.com/owncloud/core/issues/27754), like this it's not possible to say if you have the same problem as well.



> Documents not working.
> Mail not working.
> 
> Market is complicated and confusing.

It's too unspecific to help you.



> I'm back to Owncloud 9.

Good idea. Wait at least for the first release, then also check if all required apps are already available for OC 10.

**Comment by Bill-MI** [comment]
It appears the stable repository had OC10 for several days as an upgrade.

I can't speak for all distros so specifically it had to have been here:
http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/

I believe in was an unfortunate error.  It's no longer there and if one did upgrade 9.1.5 to 10.0.0, as I did not knowing it wasn't final, it will report itself as "ownCloud 10.0.0 (stable)".

**Comment by devmarxx** [comment]
You can download OC X highly official at owncloud.org as upgrade version. No word about beta.

**Comment by Bill-MI** [comment]
Things are dynamically changing as we speak.  However, the stable repository remains at 9.1.5 after several days at 10.0.0.  Probably a transient as it rolls out.
