### ISSUE TITLE
Minor wording of comments in config.sample.php

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#27787]
### Steps to reproduce
Review config.sample.php

### Expected behaviour
The comments should be correct - grammar and content

### Actual behaviour
There are a few minor errors

### Server configuration
N/A

**Comment by PVince81** [comment]
@phil-davis can you submit a PR ?

**Comment by phil-davis** [comment]
@DeepDiver1975 @PVince81 - remaining comment review changes are in the reference PR #27788 above.

**Comment by DeepDiver1975** [comment]
oh - sorry - I mixed up your prs :confused:

**Comment by phil-davis** [comment]
No problem - I made 2 PRs against this issue. The first one was a "functional" change to an actual word. The others were just spelling/grammar. So it seemed good to have them in 2 commits. Doing it online in GutHub it is easy to make 2 PRs also - but these days it is also possible to go to the online branch and make more edits/commits, I didn't think about that at the time.

**Comment by PVince81** [comment]
your PRs were merged ? close ?

**Comment by phil-davis** [comment]
Yep, all were merged.
