### ISSUE TITLE
Hide Upgrade screen from unauthenticated users

### ISSUE THREAD

**Issue by liamdennehy** [owncloud/core#27782]
### Steps to reproduce
1. While an app upgrade is pending, open Owncloud in a browser

### Expected behaviour
 - If an admin user, get presented with the upgrade/admin page
 - If a non-admin user, get presented with the normal site and functionality. Maybe a notification bar to pester the admin to perform an upgrade, but really the admin should be looking at this problem, not regular users.
 - if a non-user, get presented with nothing at all apart from a login screen, and especially not a big button to start the upgrade.

### Actual behaviour
 - Authenticated, non-admin users are presented with the big upgrade button.
 - Unauthenticated users can click the big upgrade button? Note below: client is not sending any cookies (so is not authenticated), but has this response:
![owncloud allows unauthenticated users to start upgrades](https://cloud.githubusercontent.com/assets/4996358/25582775/38359632-2e8f-11e7-8077-af8a3228025e.PNG)

**Comment by kdslkdsaldsal** [comment]
@liamdennehy Most likely a duplicate of https://github.com/owncloud/core/issues/14229

**Comment by liamdennehy** [comment]
Issue #14229:
 - Is two years old, so doubtless referencing this issue will make that one proceed
 - Is more focused on non-admin *users*, I am alarmed that *absolutely anyone* can trigger this upgrade even if they are not users.
 - is considered a proposal for enhancement.

Consider the following scenario:
 - Admin is on holiday
 - App releases new version which could break stuff and OC detects the new version is available.
 - Anyone who can visit the site (e.g. someone who was sent a file share link) visits the site, doesn't need to sign in, and clicks the big upgrade button, breaking stuff.
 - At the very least, the admin can't control when an upgrade happens, even if the upgrade is not dangerous, and any random person who stumbles across the site can take it offline for hours as an upgrade is kicked off.

This is not an enhancement request, this is resolution of a security issue. Checking for admin status is a large part of the discussion - and delay - on the other ticket. Checking if the user simply exists shouldn't be too bad, but is much more serious.

**Comment by kdslkdsaldsal** [comment]
> Is two years old, so doubtless referencing this issue will make that one proceed

Having two issues about the same doesn't make things going faster

> Is more focused on non-admin users, I am alarmed that absolutely anyone can trigger this upgrade even if they are not users.

IMHO its absolutely the same. The "user" in https://github.com/owncloud/core/issues/14229 is anyone, not only "non-admin" users.

> is considered a proposal for enhancement.

Which is absolutely correct.

**Comment by kdslkdsaldsal** [comment]
IMHO your scenario has more then one weakness:

> Admin is on holiday

If the admin is on holiday why is the instance updated then?

> App releases new version which could break stuff and OC detects the new version is available.

Apps are not automatically updated

> Anyone who can visit the site (e.g. someone who was sent a file share link) visits the site, doesn't need to sign in, and clicks the big upgrade button, breaking stuff.

Which is exactly what https://github.com/owncloud/core/issues/14229 is about

> At the very least, the admin can't control when an upgrade happens

Admins have full control when and how an upgrade is happening

**Comment by liamdennehy** [comment]
nm
