### ISSUE TITLE
Fallback implementation of intl extension

### ISSUE THREAD

**Issue by rmbleeker** [owncloud/core#27780]
### Steps to reproduce
1. Upgrade OwnCloud 9 to 10

### Expected behaviour
No errors in the log on log level 3, as I had while running OwnCloud 9

### Actual behaviour
Log is being flooded with the following error: `You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead.`

### Server configuration
**Operating system:** CentOS 7

**Web server:** Apache 2.4.6

**Database:** MariaDB 5.5.52

**PHP version:** 7.0.10

**ownCloud version:** 10.0.0.12

**Updated from an older ownCloud or fresh install:** Update

**Where did you install ownCloud from:** https://download.owncloud.org/download/repositories/10.0/owncloud/

So does anyone know how to resolve this error? I've already installed the package rh-php70-php-intl as suggested elsewhere.

**Comment by kdslkdsaldsal** [comment]
Did you verified via a phpinfo if the module was correctly installed / enabled?

> I've already installed the package rh-php70-php-intl as suggested elsewhere.

Most likely this is not enough for your environment.

**Comment by rmbleeker** [comment]
I found those 2 issues as well, but didn't really derive a solution from them. Anyway, next time I should just use my head and restart Apache after installing new modules ;-)

Turns out I had installed `rh-php70-php-intl` before, but for some reason it was removed from the system again shortly after that. Now that I've reinstalled it and restarted Apache the error is gone.

**Comment by voinageo** [comment]
Patchwork library has an incompatibility with php 7.1 
On Fedora 27 , Owncloud 10.0.0.7 , php-intl installed and loaded the issue persists. 
First login of a user works then if we try to login again or do anything we get the same message:
You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead.

Issue still not fixed.
