### ISSUE TITLE
ownCloud unusable after 9.1.5 -> 10.0.0 via yum update

### ISSUE THREAD

**Issue by apircalabu** [owncloud/core#27784]
CentOS 7.3

### Steps to reproduce
yum update owncloud-files

### Actual behaviour
[Tue May 02 08:50:45.712180 2017] [:error] [pid 28138] [client 175.45.125.14:51250] PHP Warning:  require(/var/www/html/owncloud/lib/composer/composer/../sabre/uri/lib/functions.php): failed to open stream: No such file or directory in /var/www/html/owncloud/lib/composer/composer/autoload_real.php on line 70
[Tue May 02 08:50:45.712241 2017] [:error] [pid 28138] [client 175.45.125.14:51250] PHP Fatal error:  require(): Failed opening required '/var/www/html/owncloud/lib/composer/composer/../sabre/uri/lib/functions.php' (include_path='/var/www/html/owncloud/lib/composer/pear/pear_exception:/var/www/html/owncloud/lib/composer/pear/console_getopt:/var/www/html/owncloud/lib/composer/pear/pear-core-minimal/src:/var/www/html/owncloud/lib/composer/pear/archive_tar:.:/opt/remi/php56/root/usr/share/pear:/opt/remi/php56/root/usr/share/php:/usr/share/pear:/usr/share/php') in /var/www/html/owncloud/lib/composer/composer/autoload_real.php on line 70
[Tue May 02 08:50:45.720147 2017] [:error] [pid 23154] [client 175.45.125.14:51350] PHP Warning:  require(/var/www/html/owncloud/lib/composer/composer/../sabre/uri/lib/functions.php): failed to open stream: No such file or directory in /var/www/html/owncloud/lib/composer/composer/autoload_real.php on line 70

### Server configuration
**Operating system**: CentOS 7.3

**Web server:** Apache 

**Database:** 10.1.22-MariaDB

**PHP version:** php -v
PHP 5.6.30 (cli) (built: Jan 19 2017 07:08:58) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**ownCloud version:** owncloud-files-10.0.0-1.1.noarch

**Updated from an older ownCloud or fresh install:** upgraded from 9.1.5

**Where did you install ownCloud from:** ce_stable repo

**Comment by DeepDiver1975** [comment]
Please report this to the CentOS packager.
