### ISSUE TITLE
OC RepairException: Upgrade is not possible (ver 10)

### ISSUE THREAD

**Issue by virgulesystems** [owncloud/core#27789]
### Steps to reproduce
1. Update from 9.1.4 to 10.0 using softaculous
2. Click on the update link once preparation steps are completed
3. Update fails with error message:
Repair warning: You have incompatible or missing apps enabled.
Repair warning: please install app manually with tarball or disable them occ app:disable calendar
The update was unsuccessful. Please report this issue to the ownCloud community.

Detailed log as seen on updating screen ( I do not have any calendar app that I'm aware of):
Preparing update
Set log level to debug
Turned on maintenance mode
Repair warning: You have incompatible or missing apps enabled.
Repair warning: please install app manually with tarball or disable them occ app:disable calendar
OC\RepairException: Upgrade is not possible

### Expected behaviour
Update to 10.0 :-)

### Actual behaviour
I can't login or do anything useful, stuck on the updating page

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** Owncloud user interface is not functional  so I cannot check exactly. Softaculous reports Version 10 - but the update is not completed. 

**Updated from an older ownCloud or fresh install:** Update from 9.1.4

**Where did you install ownCloud from:** Softaculous

**Signing status (ownCloud 9.0 and above):** Can't sign in (stuck on update page)

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and put the link here.
```
The URL https://mydomain/owncloud/index.php/settings/integrity/failed loops pack to update page
The URL https://mydomain/index.php/settings/integrity/failed gives a missing page error (website)

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'a random strong goes here',
  'passwordsalt' => 'a long numerical value goes here',
  'secret' => 'a very long string goes here, probably not a good idea to publish here',
  'trusted_domains' => 
  array (
    0 => 'my.domain.name',
  ),
  'datadirectory' => '/home/adminuser/ownclouddata',
  'overwrite.cli.url' => 'https://domain.name/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.4.2',
  'dbname' => 'admin_name_ownc490',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'admin_ownc490',
  'dbpassword' => 'a system generated pwd goes here',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'my.name',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'my.domain',
  'mail_smtphost' => 'mail.domain.host',
  'mail_smtpport' => '21',
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto, 20',
  'versions_retention_obligation' => 'auto, 10',
  'check_for_working_htaccess' => true,
  'log_rotate_size' => 10000000,
  'enable_previews' => false,
  'filelocking.enabled' => true,
  'filelocking.ttl' => 600,
);
```

Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.
=> I cannot login to webpage

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
=> I'm on a hosted system, cannot access command line and don't know how to do this

```

**List of activated apps:**
```
I'm not using any apps that I'm aware of. This is just a file sharing setup for 4 users with no fancy functions
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```
No access to command line

**Are you using external storage, if yes which one:** 
No
**Are you using encryption:** 
No
**Are you using an external user-backend, if yes which one:** 
No

#### LDAP configuration (delete this part if not used)
```
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';
=> MySQL returned an empty result set (i.e. zero rows). (Query took 0.0006 sec)
```

### Client configuration
**Browser:** 
Chrome (updated)
**Operating system:** 
Win7/64

#### Web server error log
```
Not sure where to find this, I'm not a sysadmin, just a power user. No apparent webserver problem
```

#### ownCloud log (data/owncloud.log)
The last few entries, below normal usage entries :
```
{"reqId":"WQg68-TC4oEfCS6NSqoKNAAAAUI","level":3,"time":"2017-05-02T07:53:23+00:00","remoteAddr":"X.X.X.X","user":"--","app":"index","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=f1f8a8c3e56bcb600479081e95f6c3c2","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(120): OC_App::loadApp('activity')\\n#1 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(145): OC_App::loadApps(Array)\\n#2 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/base.php(908): OC_Util::setupFS()\\n#3 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":161}"}
{"reqId":"WQg7AYQ-AF1Hoe6EDKh1SQAAAEw","level":0,"time":"2017-05-02T07:53:37+00:00","remoteAddr":"X.X.X.X","user":"--","app":"core","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=WCoDWn8QWXUzeyQON14EGBYeOThlNxcxJWAWHEQqFmE%3D%3AoH577y3Fu1JagnpmRdiJ3dcwk8sUsIOWP9icFIycq%2BY%3D","message":"starting upgrade from 9.1.4.2 to 10.0.0.12"}
{"reqId":"WQg7AYQ-AF1Hoe6EDKh1SQAAAEw","level":3,"time":"2017-05-02T07:53:37+00:00","remoteAddr":"X.X.X.X","user":"--","app":"core","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=WCoDWn8QWXUzeyQON14EGBYeOThlNxcxJWAWHEQqFmE%3D%3AoH577y3Fu1JagnpmRdiJ3dcwk8sUsIOWP9icFIycq%2BY%3D","message":"Exception: {\"Exception\":\"OC\\\\RepairException\",\"Message\":\"Upgrade is not possible\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/Repair.php(89): OC\\\\Repair\\\\Apps->run(Object(OC\\\\Repair))\\n#1 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/Updater.php(212): OC\\\\Repair->run()\\n#2 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/Updater.php(108): OC\\\\Updater->doUpgrade('10.0.0.12', '9.1.4.2')\\n#3 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/core\\\/ajax\\\/update.php(190): OC\\\\Updater->upgrade()\\n#4 {main}\",\"File\":\"\\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/Repair\\\/Apps.php\",\"Line\":131}"}
{"reqId":"WQg8@4Q-AF1Hoe6EDKh5gwAAAEE","level":3,"time":"2017-05-02T08:02:03+00:00","remoteAddr":"X.X.X.X","user":"--","app":"index","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=f1f8a8c3e56bcb600479081e95f6c3c2","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(120): OC_App::loadApp('activity')\\n#1 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(145): OC_App::loadApps(Array)\\n#2 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/base.php(908): OC_Util::setupFS()\\n#3 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":161}"}
{"reqId":"WQg9BPTC4oEfCS6NSqoOsAAAAVc","level":0,"time":"2017-05-02T08:02:12+00:00","remoteAddr":"X.X.X.X","user":"--","app":"core","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=QFMCDCFbOFErORoVNAc8WiA5GTMsZi42LDxSOwZSNwA%3D%3Aw14ai2Rbmstzd7H%2FdCIAz5Zpbd7r11n64PcTWbrVAHk%3D","message":"starting upgrade from 9.1.4.2 to 10.0.0.12"}
{"reqId":"WQg9BPTC4oEfCS6NSqoOsAAAAVc","level":3,"time":"2017-05-02T08:02:12+00:00","remoteAddr":"X.X.X.X","user":"--","app":"core","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=QFMCDCFbOFErORoVNAc8WiA5GTMsZi42LDxSOwZSNwA%3D%3Aw14ai2Rbmstzd7H%2FdCIAz5Zpbd7r11n64PcTWbrVAHk%3D","message":"Exception: {\"Exception\":\"OC\\\\RepairException\",\"Message\":\"Upgrade is not possible\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/Repair.php(89): OC\\\\Repair\\\\Apps->run(Object(OC\\\\Repair))\\n#1 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/Updater.php(212): OC\\\\Repair->run()\\n#2 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/Updater.php(108): OC\\\\Updater->doUpgrade('10.0.0.12', '9.1.4.2')\\n#3 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/core\\\/ajax\\\/update.php(190): OC\\\\Updater->upgrade()\\n#4 {main}\",\"File\":\"\\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/Repair\\\/Apps.php\",\"Line\":131}"}
{"reqId":"WQg9Chi9y0wKrbOhiwR-zQAAANU","level":3,"time":"2017-05-02T08:02:18+00:00","remoteAddr":"X.X.X.X","user":"--","app":"index","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=f1f8a8c3e56bcb600479081e95f6c3c2","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(120): OC_App::loadApp('activity')\\n#1 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(145): OC_App::loadApps(Array)\\n#2 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/base.php(908): OC_Util::setupFS()\\n#3 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":161}"}
{"reqId":"WQg98fTC4oEfCS6NSqoQiAAAAUk","level":3,"time":"2017-05-02T08:06:09+00:00","remoteAddr":"X.X.X.X","user":"--","app":"index","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=f1f8a8c3e56bcb600479081e95f6c3c2","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(120): OC_App::loadApp('activity')\\n#1 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(145): OC_App::loadApps(Array)\\n#2 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/base.php(908): OC_Util::setupFS()\\n#3 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":161}"}
{"reqId":"WQg9@G6Mx7jAYAHNaSw9UQAAAZI","level":3,"time":"2017-05-02T08:06:16+00:00","remoteAddr":"X.X.X.X","user":"--","app":"index","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=f1f8a8c3e56bcb600479081e95f6c3c2","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(120): OC_App::loadApp('activity')\\n#1 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(145): OC_App::loadApps(Array)\\n#2 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/base.php(908): OC_Util::setupFS()\\n#3 \\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/home\\\/ADMIN_NAME\\\/public_html\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":161}"}
```

#### Browser log
```
No apparent browser problem at this stage
```

**Comment by DeepDiver1975** [comment]
> Repair warning: please install app manually with tarball or disable them occ app:disable calendar

it tells you what to do - where is the problem?

**Comment by virgulesystems** [comment]
Well, I respect the developers who create OC and the ver 10 installation tools that I see in Softaculous when I wake up in the morning.

I'm an amateur, and I know that I don't know much about sysadmin, beyond the document admin role and following step-by-step instruction in softaculous. 

So the problem is: I find it extremely unlikely that I would perform better than all these developers, by doing something myself "manually" where their install program failed. 

My normal starting point is Softaculous, and that is not working in this case. The odds of me breaking the hosted server are about 95%  if I don't have step-by-step instructions for a hosted environment. I don't have console access, so I have no idea how I would run the occ app:disable calendar command, and even less ideas on how to check that it actually worked. 

The last part of the Softaculous error message was :" Please report this issue to the ownCloud community", which I am doing here.

**Comment by mwstowe** [comment]
What the message is telling you is that the "calendar" extension needs to be disabled.  That can be done without command line access (or access to the UI) through mysql.

The appropriate mysql statement is:
`mysql> update oc_appconfig set configvalue='no' where configkey = 'enabled' and appid = 'calendar';`

**Comment by virgulesystems** [comment]
I was able to complete the upgrade using this info and the hosting admins. 
System is up & syncing. Thank you for the tip and patience with amateurs...

**Comment by urmatej** [comment]
Hello,
I'm stuck exactly at the same point and I have no idea how to "install app manually with tarball or disable them occ app:disable audioplayer occ app:disable notes"

I host, I have access to files through ftp. How do I disable those apps.

BTW, It is kind of strange, that the latest release can not do what all previous were able to. In this case disabling manually added apps.

Thanks for your help ...

**Comment by virgulesystems** [comment]
@urmatej matej

Go to cpanel and run the MySQL admin tool. Execute the SQL command listed above to disable the apps.
Normally this is enough to let the default installation script do it's job without further errors
Make sure to do a backup before playing with MySQL.

Note: I am not admin or developer. I am only sharing what I have done to fix my issue.

**Comment by urmatej** [comment]
Ufff, is there a long "howto" somewhere on the net?

I have no "cpanel" or I do not see or recognise one, have only "MySQL Management" option, which has no "execute a command" ...

I'm accessing this throught directAdmin site ...

Thanks

**Comment by virgulesystems** [comment]
MySQL management sounds like a good place to start. If you have zero experience with MySQL, I suggest you do not try on a live system that you care about. Ask the system admin in your hosting company, or a friend who knows a little about SQL. Very little knowledge is needed, only enough to to understand what the command syntax is, and what happens / what to expect when you run it. But don't try this at home without adult supervision if you have serious data stored in OC.
There are a millions of SQL How-To on the net, but they will be quite thick if you want to dive into this topic. Try anything that looks like "SQL for dummies". You do no need more knowledge in order to run the above command.

**Comment by virgulesystems** [comment]
`update oc_appconfig set configvalue='no' where configkey = 'enabled' and appid = 'calendar';`

**Comment by urmatej** [comment]
Thank you, virgulesystems, for your help.

My problem is still "where" do I execute the command.
I checked every option of it and there is only, Repair, Check, Optimize and Delete. None of them do anything useful, only outputing statuses ...

I am searchind DirectAdmin forums, but no luck!

**Comment by urmatej** [comment]
AAAAAHA, this is under phpMyAdmin!!!!

For others:
Login to phpMyAdmin -> Select "Your" Database -> Select SQL -> copy the code and of course replace the appid with your problematic apps, and hit GO.

Got it, simple, thank you!

**Comment by virgulesystems** [comment]
Yes. You are on the right track :-) 
PS; I'm not familiar with Github; I don't think this is an SQL end-user support site. You might get better advice on a MySQL support group. Our conversation is probably annoying OC admins...

**Comment by urmatej** [comment]
Ok, Guys, please help me with a command to "enable apps". I can not figure it out!

After installing OC 10, there were only problems. 4 days ago, I disabled 3 apps, today, after optimistically believing the fixes for those arrived, I needed to disable another 4 (among which gallery!, pdf! text editor!!!!) and am left now presented with an error:

> Repair warning: Market app is unavailable for updating of apps. Enable with: occ app:enable market

I host, so I have access to ftp and all bells and whistles of phpMyAdmin. So, how do I enable this Market, or better disable it completely, since it is obviously not doing its job.

I hope I do not need to consider going back to 9.2.

Thanks,

**Comment by virgulesystems** [comment]
I am not a developer and not a qualified sysadmin, so take my advice with a pinch of salt. Since you are hosting, you should have access to, and know how to check SQL tables. Look at the update command above. Check the table, field and value, then manually go in SQL and look for the said table. It's not long. Find the row that matches "Market App". Edit the field that says "configvalue = no" and switch it to "yes".
Now run the OC upgrade script. This worked for me when my last upgrade generated another error, as I didn't have time/patience to read an entire admin manual. 
If you are not experienced and reading this: unlike before (above), where all the apps had to be disabled for the upgrade to work, I found to my great despair that disabling all the apps before upgrading...failed the most recent upgrade a few days before the present post :-( 
=> One app at least must remain enabled: "Market App". Everything is easy after that.
PS; if would be nice if someone competent could post the correct SQL command to do what I did manually, to avoid terrible mistakes.

**Comment by urmatej** [comment]
Virgulsistems, thank you, it worked!
Now I will never ever update owncloud again ;)
