### ISSUE TITLE
Auto delete files older than 1 day

### ISSUE THREAD

**Issue by shakesnet** [owncloud/core#27799]
In the community version doesn't found a function that automatically delete files older than 1 day, i'm doing that with the follow steps in 1 script:

#!/bin/bash

#Erase files older than 1 day in my data directory and mantain folders:
/usr/bin/find /var/www/owncloud/files/* -mtime +1 -exec rm {} \;

#rescan filesystem:
/usr/bin/sudo -u www-data php /var/www/owncloud/occ files:scan "--all" 

I hope it works for you

**Comment by PVince81** [comment]
duplicate of https://github.com/owncloud/core/issues/26940
