### ISSUE TITLE
Messages on upgrade with apt

### ISSUE THREAD

**Issue by jochenwezel** [owncloud/core#27794]
Currently, messages output on update is as follows:
![image](https://cloud.githubusercontent.com/assets/3033827/25616476/4bbf53ec-2f3d-11e7-88d7-4df554f69ee6.png)

On attempt to upgrade with 
```bash
./occ upgrade
```
there is a break with a message to sudo this command --> perfect! :-)

After every upgrade, I'm always searching for the next required command to switch off maintenance mode.
It would be great to see there an additional message e.g. like following:
```bash
Try running 'sudo -u www-data /var/www/owncloud/occ maintenance:mode --off' to switch from maintenance mode to production mode.
```

**Comment by DeepDiver1975** [comment]
Agreed - pull request welcome ;-)

**Comment by jochenwezel** [comment]
Linux scripting is not a strength of mine...hopefully there are some guys who can change this in 2 minutes - for me, it would take hours or days ;-)
