### ISSUE TITLE
want to join Chinese(China) translate team, but seems no one would approve me.

### ISSUE THREAD

**Issue by steve3d** [owncloud/core#27797]
### Steps to reproduce
1. non important 

### Expected behaviour
some one should approve or reject.

### Actual behaviour
nothing happend after almost a month.

**Comment by DeepDiver1975** [comment]
whats your account on transifex?

**Comment by steve3d** [comment]
sorry for the delay, my account name is _steve3d_ on transifex.

**Comment by DeepDiver1975** [comment]
done - thx for your support!
