### ISSUE TITLE
Transactional File Locking

### ISSUE THREAD

**Issue by raphson93** [owncloud/core#27800]
### Steps to reproduce
1. Enable Transaction File Locking in ownCloud 10
2.
3.

### Expected behaviour
The warning message will disappear

### Actual behaviour
Warning message disappeared, but failed to access external storage

### Server configuration
**Operating system**: Centos 7

**Web server:** Apache

**Database:** mysql

**PHP version:** php5.6

**ownCloud version:** 10.0.0.12

**Updated from an older ownCloud or fresh install:** Updated from 9.1.5

**Where did you install ownCloud from:** owncloud.org

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
https://gist.github.com/raphson93/1d8fed8bfb8c4d950b06047ea61c63f6


**The content of config/config.php:**
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocms0hhs4uvk",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "126.32.3.199",
            "owncloud.htasia.com:7342",
            "owncloud.htasia.com:80"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/tmp\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "dbtype": "mysql",
        "version": "10.0.0.12",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Asia\/Kuala_Lumpur",
        "installed": true,
        "maintenance": false,
        "loglevel": 0,
        "theme": ""
    }
}


**List of activated apps:**

Enabled:
  - activity: 2.3.3
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.8
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - market: 0.1.0
  - notifications: 0.3.0
  - onlyoffice: 1.0.3
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - twofactor_totp: true
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - example-theme
  - external
  - files_antivirus
  - onlyoffice_bak
  - user_external

**Are you using external storage, if yes which one:** smb.

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No


```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** firefox

**Operating system:** windows 10

#### ownCloud log (data/owncloud.log)
03T08:50:38+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/core\/preview.png?file=%2FTraining+Docs%2FModule+11+-+SE+-+TDDexample.txt&c=5901696378922&x=32&y=32&forceIcon=0","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpXr0q5nwqIv4Mex6uBQAAAAc","level":3,"time":"2017-05-03T08:50:38+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FTraining%20Docs","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpX70q5nwqIv4Mex6uBgAAAAc","level":3,"time":"2017-05-03T08:50:39+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/core\/preview.png?file=%2FTraining+Docs%2FModule+11+-+SE+-+TDDexample++part+2.txt&c=5901696379619&x=32&y=32&forceIcon=0","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpYb0q5nwqIv4Mex6uBwAAAAc","level":3,"time":"2017-05-03T08:50:41+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpYYxeOmi2t5IXj1gtOQAAAAw","level":3,"time":"2017-05-03T08:50:41+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/apps\/files_external\/userglobalstorages\/7?testOnly=false","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpYb0q5nwqIv4Mex6uCAAAAAc","level":3,"time":"2017-05-03T08:50:41+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2F","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpYd3qhV-PtEDZ-AjRWwAAAAI","level":3,"time":"2017-05-03T08:50:41+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/apps\/files_external\/userglobalstorages\/7?testOnly=false","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpYr0q5nwqIv4Mex6uCQAAAAc","level":3,"time":"2017-05-03T08:50:42+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"PROPFIND","url":"\/remote.php\/webdav\/ryan","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpYr0q5nwqIv4Mex6uCQAAAAc","level":4,"time":"2017-05-03T08:50:42+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/ryan","message":"Exception: {\"Message\":\"Redis server went away\",\"Exception\":\"RedisException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Memcache\\\/Redis.php(113): Redis->incrBy('9fcae6b69a3daae...', 1)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Lock\\\/MemcacheLockingProvider.php(76): OC\\\\Memcache\\\\Redis->inc('files\\\/59c21d574...')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(653): OC\\\\Lock\\\\MemcacheLockingProvider->acquireLock('files\\\/59c21d574...', 1)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(589): OC\\\\Files\\\\Storage\\\\Common->acquireLock('', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(589): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(589): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(589): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(589): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1905): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(2007): OC\\\\Files\\\\View->lockPath('ryan', 1, false)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1306): OC\\\\Files\\\\View->lockFile('ryan', 1)\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1343): OC\\\\Files\\\\View->getCacheEntry(Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Checksum), '', 'ryan')\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php(169): OC\\\\Files\\\\View->getFileInfo('ryan')\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(966): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('ryan')\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1665): Sabre\\\\DAV\\\\Server::getPropertiesIteratorForPath('ryan', Array, 1)\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#16 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#18 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#19 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#20 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#21 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Memcache\\\/Redis.php\",\"Line\":113,\"User\":\"vincent\"}"}
{"reqId":"WQkpYoxeOmi2t5IXj1gtOgAAAAw","level":3,"time":"2017-05-03T08:50:42+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpYt3qhV-PtEDZ-AjRXAAAAAI","level":3,"time":"2017-05-03T08:50:42+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/apps\/files_external\/userglobalstorages\/8?testOnly=false","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpY4xeOmi2t5IXj1gtOwAAAAw","level":3,"time":"2017-05-03T08:50:43+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2F","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpYwZN445GBjOoVRrSRQAAAAY","level":3,"time":"2017-05-03T08:50:43+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/apps\/files_external\/userglobalstorages\/8?testOnly=false","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpbzKZwuhZvl2dbJMmdAAAAAA","level":3,"time":"2017-05-03T08:50:55+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/settings\/personal","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpcDKZwuhZvl2dbJMmdQAAAAA","level":3,"time":"2017-05-03T08:50:56+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=40fdaa92ffaf95009cd6edce8f414dfb","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpcTKZwuhZvl2dbJMmdgAAAAA","level":3,"time":"2017-05-03T08:50:57+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/avatar\/vincent\/32","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpcZujilutt6npl9deEAAAAAs","level":3,"time":"2017-05-03T08:50:57+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpcaSdDd-5pclxmOj@AQAAAAE","level":3,"time":"2017-05-03T08:50:57+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/avatar\/vincent\/1","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpcaSdDd-5pclxmOj@AQAAAAE","level":3,"time":"2017-05-03T08:50:57+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/avatar\/vincent\/1","message":"PHP Startup: smbclient: Unable to initialize module\nModule compiled with module API=20100525\nPHP    compiled with module API=20131226\nThese options need to match\n at Unknown#0"}
{"reqId":"WQkpcX6XUngGjKeUwNBHYgAAAAM","level":3,"time":"2017-05-03T08:50:57+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/avatar\/vincent\/145","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpcTKZwuhZvl2dbJMmdwAAAAA","level":3,"time":"2017-05-03T08:50:57+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/avatar\/vincent\/145","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpczKZwuhZvl2dbJMmeAAAAAA","level":3,"time":"2017-05-03T08:50:59+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/settings\/admin?sectionid=general","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpczKZwuhZvl2dbJMmeQAAAAA","level":3,"time":"2017-05-03T08:50:59+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=40fdaa92ffaf95009cd6edce8f414dfb","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpdDKZwuhZvl2dbJMmegAAAAA","level":3,"time":"2017-05-03T08:51:00+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/avatar\/vincent\/32","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpdJujilutt6npl9deEQAAAAs","level":3,"time":"2017-05-03T08:51:00+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/settings\/ajax\/checksetup","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpdKSdDd-5pclxmOj@AgAAAAE","level":3,"time":"2017-05-03T08:51:00+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"PROPFIND","url":"\/remote.php\/webdav","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpdNGEdeYkRrIkhdoUdwAAAAU","level":3,"time":"2017-05-03T08:51:00+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/heartbeat","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpdH6XUngGjKeUwNBHYwAAAAM","level":3,"time":"2017-05-03T08:51:00+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"WQkpdjKZwuhZvl2dbJMmewAAAAA","level":3,"time":"2017-05-03T08:51:02+08:00","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/settings\/admin\/log\/download","message":"Redis::connect(): connect() failed: No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/RedisFactory.php#83"}

**Comment by kdslkdsaldsal** [comment]
That the access to the external SMB storage doesn't work is more likely related to this message:

> Startup: smbclient: Unable to initialize module\nModule compiled with module API=20100525\nPHP    compiled with module API=20131226\nThese options need to match\n at Unknown#0"}

which shows that you have some issues with the https://github.com/eduardok/libsmbclient-php installation. Fix this first and try again.

**Comment by raphson93** [comment]
@kdslkdsaldsal 

Hi, previously there is no problem to access the external storage even thou I have this issue
Startup: smbclient: Unable to initialize module\nModule compiled with module API=20100525\nPHP compiled with module API=20131226\nThese options need to match\n at Unknown#0"}

So I dont think it is the root cause of the issue I face now : )

**Comment by kdslkdsaldsal** [comment]
You need the libsmbclient for a working (and reliable working) SMB external storage. So please fix this as already advised before digging any deeper into this.

**Comment by raphson93** [comment]
@kdslkdsaldsal 

Let's said i upgraded my php from 5.4 to 5.6.
I need to recompile the libsmbclient-php module again ?

**Comment by kdslkdsaldsal** [comment]
Yes. If you have upgraded PHP from 5.4 to 5.6 during the upgrade of your oC instance from 9.1.5 to 10.0.0 it explains why you're seeing this issue now.

**Comment by raphson93** [comment]
@kdslkdsaldsal 

I recompile the module but I still having the same issue.

inside php.ini, I set the extension to "/usr/lib64/php/modules/smbclient.so"

**Comment by raphson93** [comment]
Finally fix the smbclient issue.
When I type "php -v" no longer see the error message.
But inside the owncloud.log I can still see the error message:

> {"reqId":"WQqMVUtHSmL4CLeDkGRr2gAAAAk","level":3,"time":"May 04, 2017 10:05:09","remoteAddr":"175.143.72.221","user":"vincent","app":"PHP","method":"GET","url":"\/index.php\/apps\/templateeditor\/settings\/mailtemplate?theme=&template=core%2Ftemplates%2Fmail.php","message":"PHP Startup: smbclient: Unable to initialize module\nModule compiled with module API=20100525\nPHP    compiled with module API=20131226\nThese options need to match\n at Unknown#0"}
{"reqId":"WQqMMWvA4xbmwhV5AuTv3gAAAAM","level":3,"time":"May 04, 2017 10:05:59","remoteAddr":"175.143.72.221","user":"vincent","app":"index","method":"GET","url":"\/index.php\/settings\/ajax\/checksetup","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ConnectException\",\"Message\":\"cURL error 7: Failed to connect to 2a01:4f8:130:806f::5: Network is unreachable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(104): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\ConnectException))\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(135): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(135): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(136): GuzzleHttp\\\\Client->get('https:\\\/\\\/www.own...', Array)\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/settings\\\/Controller\\\/CheckSetupController.php(195): OC\\\\Http\\\\Client\\\\Client->get('https:\\\/\\\/www.own...')\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/settings\\\/Controller\\\/CheckSetupController.php(336): OC\\\\Settings\\\\Controller\\\\CheckSetupController->isUsedTlsLibOutdated()\\n#16 [internal function]: OC\\\\Settings\\\\Controller\\\\CheckSetupController->check()\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#18 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\CheckSetupController), 'check')\\n#19 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\CheckSetupController), 'check')\\n#20 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('CheckSetupContr...', 'check', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#21 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#22 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#23 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/settings\\\/ajax\\\/...')\\n#24 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#25 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":49}"}

**Comment by kdslkdsaldsal** [comment]
@raphson93  Please note that this is a bugtracker of ownCloud. If you need further support with the libsmbclient issue ask such support at https://secure.php.net/support.php

**Comment by brainode** [comment]
Have the same errors on php 7.1.6, but i don't use external storage.
`{"reqId":"a65NCG6i2jKh5NtxHZux","level":3,"time":"2017-07-17T20:34:24+00:00","remoteAddr":"192.168.47.1","user":"rusbaron","app":"PHP","method":"GET","url":"\/data\/htaccesstest.txt?t=1500323662910","message":"Redis::connect(): connect() failed: No such file or directory at \/srv\/www\/cloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"BehCHp5SvXczjrYib4wZ","level":3,"time":"2017-07-17T20:34:29+00:00","remoteAddr":"192.168.47.1","user":"rusbaron","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/files\/rusbaron\/","message":"Redis::connect(): connect() failed: No such file or directory at \/srv\/www\/cloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"4RqPs0CxD3pGoCpKSt9w","level":3,"time":"2017-07-17T20:34:29+00:00","remoteAddr":"192.168.47.1","user":"rusbaron","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"Redis::connect(): connect() failed: No such file or directory at \/srv\/www\/cloud\/lib\/private\/RedisFactory.php#83"}
{"reqId":"5le8jhS17Q8HM4PtSFX1","level":3,"time":"2017-07-17T20:34:31+00:00","remoteAddr":"192.168.47.1","user":"rusbaron","app":"PHP","method":"GET","url":"\/settings\/admin\/log\/download","message":"Redis::connect(): connect() failed: No such file or directory at \/srv\/www\/cloud\/lib\/private\/RedisFactory.php#83"}
`

**Comment by kdslkdsaldsal** [comment]
@raphson93 
> Redis::connect(): connect() failed: No such file or directory

This is most likely a mis-configuration of either the config.php pointing to a wrong redis socket or redis not listening on a socket at all.

Please jump over to https://central.owncloud.org/ (you can login with your github login there) to get support for such configuration problems.
