### ISSUE TITLE
OC 10 upgrade: Double slashes in paths break web app

### ISSUE THREAD

**Issue by seb-dataworks** [owncloud/core#27805]
Hi, I am running Owncloud on a Ubuntu 16.04 on Apache. I tried PHP 5.6 as well as 7.0.  I have updated from 9.1 to 10.0 via the web updater. Since then *most* of the paths in the web app start with a double slash (not all). I can open the login page but essentially nothing else is possible - since the browser can't reach the references. So I cannot login etc.

File sync with the desktop or mobile apps, however, still work completely fine.

**Steps to reproduce**
No idea.

**Actual behaviour**

So my index.php source code right now looks like this..

    <link rel="stylesheet" href="/apps/firstrunwizard/css/colorbox.css?v=bfd00bcae1c391824a4f344d69725e20">
	<link rel="stylesheet" href="/apps/firstrunwizard/css/firstrunwizard.css?v=bfd00bcae1c391824a4f344d69725e20">
	<link rel="stylesheet" href="/core/css/jquery.ocdialog.css?v=bfd00bcae1c391824a4f344d69725e20">
	<link rel="stylesheet" href="//core/css/styles.css?v=bfd00bcae1c391824a4f344d69725e20">
    ...
    <link rel="stylesheet" href="//apps/firstrunwizard/css/firstrunwizard.css?v=bfd00bcae1c391824a4f344d69725e20">
    ...
    <link rel="stylesheet" href="//core/css/jquery.ocdialog.css?v=bfd00bcae1c391824a4f344d69725e20">
	<script src="/index.php/core/js/oc.js?v=bfd00bcae1c391824a4f344d69725e20"></script>

**Server configuration**

Operating system: Ubuntu 16.04

Web server: Apache

Database: MySql

PHP version: 5.6 (also tried 7.0)

ownCloud version: 10.0.07

Updated from an older ownCloud or fresh install: Updated from 9.1

Where did you install ownCloud from: Update through web updater

Notice, how some references start with a single slash, others incorrectly with double slashes.
Any help is highly appreciated! Not really sure, what more info you would need, just let me know and I'll provide it!

**Comment by karsten-eger** [comment]
Check this out in the meantime, worked for me:
https://github.com/owncloud/core/commit/6aa0c61c4312919d71e69926b5ed6b29bad797e0

**Comment by kdslkdsaldsal** [comment]
@karsten-eger @seb-dataworks Are you sure that you're using the latest final version of ownCloud and not some beta/release candidates?

This fix is already included in the final release of ownCloud.

@seb-dataworks 
> Update through web updater

-> There is no final release of oC 10.0.0 available via the webupdater so you're mostly have switched to the "testing" release? This would also explain:

> ownCloud version: 10.0.07

because the "final" release of oC 10 has the internal version number:

> 10.0.0.12

**Comment by karsten-eger** [comment]
@kdslkdsaldsal indeed. I was poked at upgrading all the time via web and now in the client so I did the update and it went wrong.

Used the manual download and upgrade now, 10.0.12 and it seems to work as well.

**Comment by kdslkdsaldsal** [comment]
@karsten-eger Thanks for the background info. So i think @seb-dataworks can close this once the correct / final version is used.

**Comment by seb-dataworks** [comment]
@karsten-eger Thanks, that helped at least for now! I'm able to log in again.

Should the updater show me the final version (10.0.12) so that I can update automatically or how should I proceed to get to the released version?

**Comment by kdslkdsaldsal** [comment]
@seb-dataworks Nope, the updater app will never push the first version of a new major release out to the users. In the past it took one or two maintenance releases (e.g. 10.0.1 or 10.0.2) until the major release was available via that updater app.

**Comment by kdslkdsaldsal** [comment]
But as this issue is solved for you please close here. If you have further questions please jump over to https://central.owncloud.org/ where questions are answered.

**Comment by seb-dataworks** [comment]
@kdslkdsaldsal alright thanks!
