### ISSUE TITLE
Client error response [url] https://apps.owncloud.com/CONTENT/content-files/174834-jj%3Cimg%20src= [status code] 404 [reason phrase] Not Found

### ISSUE THREAD

**Issue by abusayeedn** [owncloud/core#27804]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
sorry - can you please provide a bite more information? reopening once we have more input ...

**Comment by topas-rec** [comment]
Hello,

I have the same error message when I run the plain owncloud/server image in DOcker and try to activate the tasks app (the approved one).

**Comment by jnweiger** [comment]
@topas-rec I believe https://github.com/owncloud/core/issues/17456 is properly solved. All the bad URLs mentioned there work fine for me now.

**Comment by topas-rec** [comment]
Yeah might be. I think I found the solution to this. I haven't tested it, bit I think that the tasks app simply didn't migrated to oc10 yet.
On https://apps.owncloud.com/content/show.php/Tasks?content=164356 in the comment section look for comment "Error 400 
 by pandka on: Oct 14 2016 "
This comment shows the error and the following comments show the solution.

See Re: Version for OC10 
 by MaRies on: May 5 2017  

It seems just a max version of oc has to be changed in the task app.

**Comment by DeepDiver1975** [comment]
> Can this be related to #17456 ?

is a super old ticket - not related to the current issues at all

**Comment by terrytibbles** [comment]
Are there any plans to get this resolved? I believe I have the same problem, and it is documented on [ownCloud central](https://central.owncloud.org/t/upgrade-9-1-4-to-9-1-5-bookmarks-app-has-gone/7497/18).

As the original poster hasn't actually included a problem description, this is as follows:

It's currently not possible to use the Bookmarks app (version 0.9.0) or the Tasks app (version 0.9.4) on version 9.1.5 of ownCloud. At the moment, the solution seems to be to upgrade to ownCloud 10, but this does not fix the problem, and it does not provide a solution to people running ownCloud 9.1.5 in the production environment, who need the Bookmarks app and the Tasks app to work. Downloading and installing the apps from Githib also does not provide any version control and requires extra work, when the solution could be to fix the problem with the Apps page.

**Comment by terrytibbles** [comment]
@DeepDiver1975 Any chance of this being re-opened?

**Comment by terrytibbles** [comment]
These two apps are both unavailable in version 10.0.2 of ownCloud, which would go some way in explaining why they are unavailable in version 9.1.5.
