### ISSUE TITLE
Need the ability to list users

### ISSUE THREAD

**Issue by settermjd** [owncloud/core#27813]
### Steps to reproduce
1. Run `occ` as the installation's web server user, and there is no command in the `user` group to list users. There are commands to add, delete, disable, & enable them, etc. But there are none to list them. Here's an example:

```console
 user
  user:add                            adds a user
  user:delete                         deletes the specified user
  user:disable                        disables the specified user
  user:enable                         enables the specified user
  user:lastseen                       shows when the user was logged in last time
  user:report                         shows how many users have access
  user:resetpassword                  Resets the password of the named user
  user:setting                        Read and modify user settings
  user:sync                           synchronize users from a given backend to the accounts table
```

The reason that I'm seeking this information is that firstly, it seems strange that it's not there, and secondly, it would help to have a command like this so that it's easier to do research as I'm working with the docs. I'd assume that the command would print out, in a tabular fashion, the username, first and last name, and a bit of other information. What exactly, I'm not too sure. 

### Server configuration
**Operating system:** Ubuntu 16.04.2 LTS

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:** 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )

**ownCloud version:** 10.0.0 RC5

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** The official Docker repository

**List of activated apps:**

- activity: 2.3.3
- comments: 0.3.0
- configreport: 0.1.1
- dav: 0.2.8
- federatedfilesharing: 0.3.0
- federation: 0.1.0
- files: 1.5.1
- files_external: 0.7.0
- files_pdfviewer: 0.8.1
- files_sharing: 0.10.0
- files_texteditor: 2.1
- files_trashbin: 0.9.0
- files_versions: 1.3.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- gallery: 15.0.0
- market: 0.1.0
- notifications: 0.3.0
- provisioning_api: 0.5.0
- systemtags: 0.3.0
- templateeditor: 0.1
- updatenotification: 0.2.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** 

### Client configuration

**Browser:** Safari on macOS

**Operating system:** macOS Sierra

**Comment by mmattel** [comment]
See also: 

[Feature Request] occ command to list users like ./occ user:list [--admin] [options to filter] https://github.com/owncloud/core/issues/27425
[Feature Request] ./occ user:logonlist https://github.com/owncloud/core/issues/25708

**Comment by individual-it** [comment]
This is implemented by https://github.com/owncloud/core/pull/28312
closing or is any work left to be done?

**Comment by phil-davis** [comment]
@settermjd at the moment it works like:
```
phil@phil-VirtualBox:~/core$ php occ user:add --display-name "Phil Davis" --email "phil@example.com" --group admin phil-davis
Enter password: 
Confirm password: 
The user "phil-davis" was created successfully
Display name set to "Phil Davis"
Email address set to "phil@example.com"
User "phil-davis" added to group "admin"
phil@phil-VirtualBox:~/core$ php occ user:list
  - admin: admin
  - phil-davis: Phil Davis
phil@phil-VirtualBox:~/core$ php occ user:list-groups phil-davis
  - admin
phil@phil-VirtualBox:~/core$ php occ group:list-members admin
  - admin: admin
  - phil-davis: Phil Davis
```
The ``user:list`` does not show the email address, but does show display name.

**Comment by settermjd** [comment]
Thanks. Closing.
