### ISSUE TITLE
 reinstalling 10.0.0.x (fresh) after an uninstall failed - Ubuntu 16.04.2 LTS Server

### ISSUE THREAD

**Issue by robertcates** [owncloud/core#27811]
My Ubuntu 16.04.2 LTS Server can no longer reach/download/install ownCloud 10.0.0.x

### Steps to reproduce
This all occurred in the same evening (a few days ago) and continues to be a problem

1. Had 9.1.5 installed and running fine
2. Upgraded to 10.0.0.x and it seemed to be fine, but for some reason I uninstalled 
3. Tried to reinstall the packages but get 404 errors
4. Managed to download the individual packages, but they also will not install

### Expected behaviour
aptitude or apt-get does not matter, it should reach the repository, download and install, as it does with other Ubuntu package upgrades (what I'm saying is during the same run, aptitude reaches the Ubuntu repositories, downloads and installs).

### Actual behaviour
aptitude install owncloud owncloud-deps-php7.0 owncloud-files
The following NEW packages will be installed:
  owncloud owncloud-deps-php7.0 owncloud-files 
0 packages upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.8 MB of archives. After unpacking 116 MB will be used.
Err http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  owncloud-files 10.0.0-1.1
  404  Not Found [IP: 144.76.105.220 80]
Err http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  owncloud-deps-php7.0 10.0.0-1.1
  404  Not Found [IP: 144.76.105.220 80]
Err http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  owncloud 10.0.0-1.1
  404  Not Found [IP: 144.76.105.220 80]
0% [Working]E: **Failed to fetch** http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/./all/owncloud-files_10.0.0-1.1_all.deb: 404  Not Found [IP: 144.76.105.220 80]

I noticed during my repeated attempts, 3 or 4 different IP addresses. My assumption is that the new 10.0.0.x version is not in the repository as expected, but that's only my guess.

### Server configuration
**Operating system**: 
Ubuntu 16.04.2 LTS Server

**Web server:** 
Apache 2.4.18

**Database:** 
sqlite3

**PHP version:** 
7.0.15

**ownCloud version:** (see ownCloud admin page) 
10.0.0.x 

**Updated from an older ownCloud or fresh install:** 
9.1.5 to 10.0.0.x seemed to go fine, but then reinstalling 10.0.0.x (fresh) after an uninstall failed

**Where did you install ownCloud from:** 
/etc/apt/sources.list.d/owncloud.list
deb http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ /

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
After my uninstall of 10.0.0.x I completed deleted the /var/www/owncloud directory structure (because I wanted a fresh install of 10.0.0.x
```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No (storage was the default /vat/www/owncloud/data/ )

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
**The rest of this is irrelevant in my case.** 

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by kdslkdsaldsal** [comment]
@robertcates This is known and already reported in https://github.com/owncloud/core/issues/27775 so you can close this one.

**Comment by kdslkdsaldsal** [comment]
Side-note: If this system is not a testing system wait for 10.0.1 or 10.0.2 before upgrading. Until then the repositories are probably fixed as well.
