### ISSUE TITLE
Problem with OwnCloud Debian 8 Repo?

### ISSUE THREAD

**Issue by takenek** [owncloud/core#27814]
Calculating upgrade... Done
The following packages will be upgraded:
  libtiff5 owncloud owncloud-deps-php5 owncloud-files
4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 27.3 MB of archives.
After this operation, 14.5 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://security.debian.org/ jessie/updates/main libtiff5 amd64 4.0.3-12.3+deb8u3 [219 kB]
Err http://download.owncloud.org/download/repositories/stable/Debian_8.0/  owncloud 10.0.0-1.1
  404  Not Found [IP: 213.239.207.26 80]
Err http://download.owncloud.org/download/repositories/stable/Debian_8.0/  owncloud-files 10.0.0-1.1
  404  Not Found [IP: 213.239.207.26 80]
Err http://download.owncloud.org/download/repositories/stable/Debian_8.0/  owncloud-deps-php5 10.0.0-1.1
  404  Not Found [IP: 213.239.207.26 80]
Fetched 219 kB in 0s (1367 kB/s)
E: Failed to fetch http://download.owncloud.org/download/repositories/stable/Debian_8.0/./all/owncloud_10.0.0-1.1_all.deb  404  Not Found [IP: 213.239.207.26 80]

E: Failed to fetch http://download.owncloud.org/download/repositories/stable/Debian_8.0/./all/owncloud-files_10.0.0-1.1_all.deb  404  Not Found [IP: 213.239.207.26 80]

E: Failed to fetch http://download.owncloud.org/download/repositories/stable/Debian_8.0/./all/owncloud-deps-php5_10.0.0-1.1_all.deb  404  Not Found [IP: 213.239.207.26 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

**Comment by kdslkdsaldsal** [comment]
@takenek This is known so you can close this directly: https://github.com/owncloud/core/issues/27811, https://github.com/owncloud/core/issues/27775 and a few threads on central.

**Comment by kdslkdsaldsal** [comment]
Side-note: If this system is not a testing system wait for 10.0.1 or 10.0.2 before upgrading. Until then the repositories are probably fixed as well.
