### ISSUE TITLE
Enhancement: Control user access to app settings

### ISSUE THREAD

**Issue by andrewjones216** [owncloud/core#27812]
### Server configuration
**Operating system**: CentOS 7-3.1611
**Web server:** httpd version 2.4.6
**Database:** MySQL
**ownCloud version:** 9.1.4
**Updated from an older ownCloud or fresh install:** Fresh
**Are you using external storage, if yes which one:** GlusterFS
**Are you using encryption:** Yes
**Are you using an external user-backend, if yes which one:** OpenLDAP

Issue:
Currently all users can browse to their 'Personal' page within OC and change and modify settings for TOTP, Sessions, App Passwords, Activity and Encryption. Our user base are 'basic' users with little or no knowledge of what any of these apps do. 
We initially setup a user with TOTP enabled, encryption password recovery enabled and basic email activity settings. We also allow any user devices at the time of setup using the one time app passwords. 
My concern is that a user can willingly or unwillingly change any one of these settings potentially causing lose of data. 

Solution:
Allow administrators to enable or disable which apps the users view in the 'Personal' page.

**Comment by PVince81** [comment]
Note that you can disable some apps for users using the "Enable for groups" feature, but it is not possible for all app types.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
