### ISSUE TITLE
Extend OCP\Settings\ISettings to have enabled status

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#27825]
Some apps decide on run time if they should present a settings panel. If we can call a separate `isEnabled` or similar method that returns a boolean value, this will help us when rendering the settings sections list as we can hide sections with no settings panels.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
