### ISSUE TITLE
Updating to 10.0.0 from 9.1 failure.

### ISSUE THREAD

**Issue by bigsatdaddy** [owncloud/core#27822]
### Steps to reproduce
1. Go to domain
2. Click "Start Update"
3. Wait...
4. Get Error

### Expected behaviour
It should finalize the update and allow access to the update version of the software.

### Actual behaviour
It keeps erroring out:
files_external: An exception occurred while executing 'CREATE TABLE `oc_external_mounts` (`mount_id` BIGINT AUTO_INCREMENT NOT NULL, `mount_point` VARCHAR(128) NOT NULL, `storage_backend` VARCHAR(64) NOT NULL, `auth_backend` VARCHAR(64) NOT NULL, `priority` INT DEFAULT 100 NOT NULL, `type` INT NOT NULL, PRIMARY KEY(`mount_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_external_mounts' already exists

Detailed Logs:
Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
files_external: An exception occurred while executing 'CREATE TABLE `oc_external_mounts` (`mount_id` BIGINT AUTO_INCREMENT NOT NULL, `mount_point` VARCHAR(128) NOT NULL, `storage_backend` VARCHAR(64) NOT NULL, `auth_backend` VARCHAR(64) NOT NULL, `priority` INT DEFAULT 100 NOT NULL, `type` INT NOT NULL, PRIMARY KEY(`mount_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_external_mounts' already exists

### Server configuration
Operating system: linux

Database: 10.0.29-MariaDB-cll-lve

PHP version: 5.6.17

Updated from an older ownCloud or fresh install: Update

Where did you install ownCloud from: owncloud.org

The content of config/config.php: Can't access to determine.

List of activated apps:**Can't access to determine.

Are you using external storage, if yes which one: No

Are you using encryption: No

**Comment by PVince81** [comment]
Please make sure you properly deleted all the old source code before replacing with the code from 10.0.

You can check if the file "apps/files_external/appinfo/database.xml" exists. If it does exist, it means you didn't properly delete. This file was removed.

**Comment by PVince81** [comment]
please reopen if you can confirm that you properly deleted the code and the issue still happens

**Comment by fredbcode** [comment]
I'm upgrading manually (so with a totally fresh owncloud install directory) and I have the same issue 

files_external: An exception occurred while executing 'CREATE TABLE "oc_external_mounts" ("mount_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "mount_point" VARCHAR(128) NOT NULL, "storage_backend" VARCHAR(64) NOT NULL, "auth_backend" VARCHAR(64) NOT NULL, "priority" INTEGER DEFAULT 100 NOT NULL, "type" INTEGER NOT NULL)': SQLSTATE[HY000]: General error: 1 table "oc_external_mounts" already exists

9.14 -> to 10.0 lighttpd + sqlite

**Comment by PVince81** [comment]
@fredbcode https://github.com/owncloud/core/issues/27822#issuecomment-301094156

**Comment by fredbcode** [comment]
Yes I'm sure as I said my owncloud directory is new, I just saved my config.php and my database

**Comment by fredbcode** [comment]
I can open a new ticket if needed (I can't reopen here)

**Comment by PVince81** [comment]
@fredbcode ok then raise a new ticket and use the issue template. the error alone isn't enough to be able to debug or reproduce the issue
