### ISSUE TITLE
Missing data in JSON response from requests to the Recipients (Sharee) API

### ISSUE THREAD

**Issue by settermjd** [owncloud/core#27820]
### Steps to reproduce

1. Make a request to the recipients API `/ocs/v1.php/apps/files_sharing/api/v1/sharees?format=json&itemType=file&shareType=0&perPage=1`

### Expected behaviour

Here's an example response that I received:

```json
{
    "ocs": {
        "meta": {
            "status": "ok",
            "statuscode": 100,
            "message": "OK",
            "totalitems": "",
            "itemsperpage": ""
        },
        "data": {
            "exact": {
                "users": [],
                "groups": [],
                "remotes": []
            },
            "users": [
                {
                    "label": "admin",
                    "value": {
                        "shareType": 0,
                        "shareWith": "admin"
                    }
                }
            ],
            "groups": [],
            "remotes": []
        }
    }
}
```

I have filtered down by user and have one record available, for the admin user. However, the meta fields: `itemsperpage` and `totalitems` are both empty/null. I would have expected them to be set to 1.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:** 7.1

**ownCloud version:** 10.0.0 RC5

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** The official Docker repository

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
