### ISSUE TITLE
Sessions of Desktop, iOS and Android clients should be shown

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27845]
### Steps to reproduce

1. Log in oC server with a oC Client (Desktop, iOS, Android)
2. Browse to Admin --> Settings--> Personal --> Security

### Expected behaviour

The User agents from the sessions of Desktop, iOS and Android clients should be shown

### Actual behaviour

The User agents from Desktop, iOS and Android clients are not been shown 
### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.1" daily master

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```

```

### Client configuration

**browser**

Desktop Client, iOS, Android

It is shown only the ones related to browsers.

![screen shot 2017-05-09 at 17 44 29](https://cloud.githubusercontent.com/assets/10596560/25859884/23477b76-34e0-11e7-8d1e-dfe667b70bb6.png)

**Comment by mmattel** [comment]
:+1:

**Comment by davitol** [comment]
@PVince81 FYI

**Comment by PVince81** [comment]
I'm using an app specific password for mobile so the "most recent activity" is updated correctly under that session. I don't see any additional entries for this in the first section.

Interestingly I also see that the first section header says "Browser". Was it designed to only detect browsers and not mobile clients ? Not sure.

Does it work differently in 9.1 ? (might be able to bisect)

**Comment by davitol** [comment]
> Interestingly I also see that the first section header says "Browser". Was it designed to only detect browsers and not mobile clients ? Not sure.
> 
> Does it work differently in 9.1 ? (might be able to bisect)

![screen shot 2017-06-01 at 10 04 33](https://cloud.githubusercontent.com/assets/10596560/26670656/c9de2e56-46b2-11e7-83f6-2e5718b7b99b.png)


For example in 9.1.6 iOS session appears but not in oCX

About the header "browser" it was comment long time ago but it was not changed, I could not find the comment related to change browser as header in GH

**Comment by PVince81** [comment]
auth / token stuff, @phisch can you have a look ? If not, let me know

**Comment by PVince81** [comment]
bisect might be possible if this worked in 9.1

**Comment by SamuAlfageme** [comment]
@PVince81 I can confirm listing the sessions used to work in 9.1 (tested in 9.1.3 and I used to get even cURL logins in the sessions table) - not revoking them though, maybe on a previous version the "Disconnect" button also worked for that. 

I'd say increase severity here. There's some implications, specially in terms of revoking those sessions now that we're trying to get OAuth2 out of the oven and this might be important to get fixed.

This is also one of the causes behind @28553.

**Comment by PVince81** [comment]
@IljaN please bisect this and fix if possible

**Comment by IljaN** [comment]
d552f5fb03a2dc97d5b562623c3fff783ae7e246 introduces the bug

**Comment by IljaN** [comment]
There was a bug in my bisect script new potential candidate is f1dc2d9d3b2039d0bfc3528e57b11df2e4c93564, need to analyze

**Comment by IljaN** [comment]
Confirmed that f1dc2d9 is the offending commit by reintroducing the removed line

**Comment by PVince81** [comment]
fixed through https://github.com/owncloud/core/pull/28879
