### ISSUE TITLE
Add a sharing option to restrict autocompletion for users in different groups

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#27849]
As an admin I want to restrict my users to only find other users that share group membership of at least one group in the sharing dialog. Users should still be able to share with users that they don't share group membership with if they know the exact username / mail address.

Basically we need to copy the sharing restriction 'Restrict users to only share with users in their groups' and enable sharing.

Please make it a suboption of 'Allow username autocompletion in share dialog. If this is disabled the full username needs to be entered.'
- Restrict username autocompletion to group membership

**Comment by pmaier1** [comment]
@felixboehm @PVince81

**Comment by PVince81** [comment]
With a bit of hope the methods that @tomneedham added recently might be reusable for this. Might need to extend them to also have an option `$restrictToGroupMemberships` when seraching

**Comment by PVince81** [comment]
The way I understand it we need to extend the ShareesController to check for the new option.

If the new option is set "Restrict autocomplete to group memberships", just use `findUsersInGroup` for autocomplete instead of `find` when searching, but still allow full input.

This + unit tests I think 1md might be enough.

**Comment by PVince81** [comment]
What about group name autocompletion ? I assume the new option will also only display autocomplete results for groups the user is a member of. And entering a full group name still allows sharing.

**Comment by PVince81** [comment]
Implementation: 10 minutes. Writing tests, one full day ;-)

PR here https://github.com/owncloud/core/pull/27869 (tests still to be written)

**Comment by felixboehm** [comment]
Let's do it

**Comment by PVince81** [comment]
there are only 4 test cases, all added a unit tests and integration tests: https://github.com/owncloud/core/issues/27869

however there might be other things to test, find out like what happens when you combine the new option with any of the old options...
