### ISSUE TITLE
Update to 7.0.4 - UNIQUE constraint failed: oc_filecache.fileid

### ISSUE THREAD

**Issue by mcech** [owncloud/core#27840]
### Steps to reproduce
1. apt-get update
2. apt-get upgrade
3. Visit owncloud URL with browser
4. owncloud wants to update (no option to skip)
5. Click on "Update"

### Expected behaviour
no idea. owncloud should update?

### Actual behaviour
error message

### Server configuration
raspbian wheezy:

**Web server:**
apache2

**Database:**
sqlite3

**PHP version:**
5.6.30

**ownCloud version:** (see ownCloud admin page)
unable to visit owncloud

**Updated from an older ownCloud or fresh install:**
fresh install wants to update

**Where did you install ownCloud from:**
apt-get

**The content of config/config.php:**
unable to see this

**List of activated apps:**
files

**Are you using external storage
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend,
no

**Comment by kdslkdsaldsal** [comment]
@mceh ownCloud 7.0.4 is outdated and end-of-life since a longer time. How and why did you choose to upgrade to this version?

**Comment by mcech** [comment]
I did not choose it. Owncloud wants to update and there is no option to skip.

**Comment by kdslkdsaldsal** [comment]
If this is a fresh installation you definitely shouldn't use 7.0.4 (this version was releases 2 1/2 years ago). As written there won't be any support for bugfixes for this version.

Please close here and install a fresh 9.1.5 instead. This won't show such issues. If you need support for this installation please jump over to https://central.owncloud.org/
