### ISSUE TITLE
Automated UI Tests 

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#27858]
### Deficiency
UI tests in https://github.com/owncloud/QA/blob/master/Server/Test_Plan_WebDav_Interface_WebUI.md (among others that could be run) have to be run manually.

### Enhancement
Provide automated UI testing.

**Comment by DeepDiver1975** [comment]
We have to come up with a plan regarding the execution time - currently one build on travis is now 1h.

![bildschirmfoto von 2017-05-12 15-54-38](https://cloud.githubusercontent.com/assets/1005065/26001809/dc454ea6-372d-11e7-9393-506829cb52b5.png)

**Comment by phil-davis** [comment]
1) Yes, probably just 1 of the browser/platform combinations should be run automatically. And sort out a way that some regular job (nightly at a time when most contributors are asleep in their time zone...) can trigger to run the full set.

2) Put that 1 selenium job at the top of the list, so it starts first. Then the other shorter things run in the other slots. Minimizes elapsed time.

3) Look in some detail at how the timing of simulated browser interaction happens. When I was watching a job on Travis the other day it seemed tediously slow to get through each scenario step. A lot of times the code has to wait looking for when the page has come back with a response. Just need to make sure that we are really knowing that the response has come as soon as we can (e.g. not accidentally waiting to the end of any of the 10-second max timers)

3) As we get more of these end-to-end tests, even 1 serial run is going to have a long elapsed time. So look at splitting into Behat test suites or... that can run different parts of the test set as completely separate Travis matrix entries. Then they will run together when Travis fires up about 5 jobs at a time.
SauceLabs Open Source account "provides unlimited testing minutes on up to five parallel VMs" https://saucelabs.com/open-source - so we can run a few things at once, and we already see the 4 selenium jobs above actually run in parallel.

**Comment by phil-davis** [comment]
@individual-it for thought/ideas

**Comment by phil-davis** [comment]
I just ran a test in a forked repo, and watched the time. It is not a bad as it "sounds". That "Total time 59 mins 10 sec" in the screen shot above is the sum of the elapsed tie of each job in the list. The elapsed time is much less, because up to 5 jobs run in parallel. The job here took 13 min 44 sec.
![owncloudtravisruntime](https://cloud.githubusercontent.com/assets/1535615/26005164/f90bc36a-3757-11e7-82a7-7bec48f80591.png)
Even so, we will need to keep aware of the time and look at the various optimization items above.

**Comment by PVince81** [comment]
what's missing ? close ?

**Comment by phil-davis** [comment]
The infrastructure is all there that supports the tests so far done. Work is ongoing to cover each of the items  in https://github.com/owncloud/QA/blob/master/Server/Test_Plan_WebDav_Interface_WebUI.md with automated tests. And @individual-it has done some more stuff to make the tests more robust (handling various "weird" things that happen in real time in the selenium-mink-webdriver and with some browser combinations.
@individual-it will submit a PR for that soon. Perhaps at that point we close this, as being the issue that calls for the working infrastructure. Then we raise issues for sub-sections of the test plan that need to be addressed.

**Comment by phil-davis** [comment]
When #28190 is reviewed and decided, then I think we have enough architecture/infrastructure here in core and can close this issue and then just make issues for particular areas of UI functionality from test plans that will be good to automate. Those can be given some priority order etc.

**Comment by phil-davis** [comment]
We have the general infrastructure in place now - UI test suites containing features containing scenarios that run automatically in combinations of Travis jobs, and can be run in a local dev environment. How to setup and run them is documented in https://github.com/owncloud/documentation/blob/master/developer_manual/core/unit-testing.rst
Various core code can and is being made use of by app UI tests.
So I think enough infrastructure is here. Closing this and smaller issues can be raised for example:
- how to move forward with sharing test infrastructure between the existing integration (API...) and UI tests
- what directions to go first in expanding coverage of the web pages and elements of core UI tests
...
