### ISSUE TITLE
Multiple Public Links: "Copy" option gets always the same link

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#27851]
### Steps to reproduce
1. Create several public links over the same file or folder
2. Use the "Copy" option to get each of them

### Expected behaviour
Each copied link is different 

### Current behaviour
Copied links are all the same (the first of the list)

### Server configuration
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.0.12","versionstring":"10.0.0","edition":"Enterprise","productname":"ownCloud"}

**Comment by SergioBertolinSG** [comment]
cc @felixheidecke 
cc @felixboehm sev-2 as this is an expected feature for 10.0.1.

**Comment by PVince81** [comment]
I guess maybe the clipboard plugin isn't properly wired up to the correct elements.

@felixheidecke please have a look.

I'm setting this to 10.0.1 because the feature is broken/useless otherwise

**Comment by PVince81** [comment]
@pmaier1 FYI ^

**Comment by pmaier1** [comment]
Yes, this should work for 10.0.1. Please fix.

**Comment by PVince81** [comment]
fixed in https://github.com/owncloud/core/issues/27863
