### ISSUE TITLE
Add option to allow / disallow middle searches for user accounts

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#27866]
Include an option for the search to match only the beginning of the string instead of matching anywhere. By default, the option should keep the current behaviour.

The goal is to optimize the usage of DB indexes and improve the overall behaviour in big installations. By setting this option, the performance should increase at a cost of functionality.

**Comment by PVince81** [comment]
wasn't this obsoleted now with the account table and search terms ? @butonic

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/28032 ?

**Comment by butonic** [comment]
yes, implemented and unified for all backends with https://github.com/owncloud/core/pull/28032 
medial search is enabled by default, can be disabled by setting `'accounts.enable_medial_search' => false,` in config.php
