### ISSUE TITLE
file error tooltip not updated correctly

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#27864]
### Steps to reproduce
1. login to the web UI
2. create 2 files
3. start renaming one file
4. delete the name completely (Error shown: 'File name cannot be empty.')
5. type the name of the other file

### Expected behaviour
Error should be updated to: 'xxxxx already exists'

### Actual behaviour
Error shown: 'File name cannot be empty.'
Same problem the other way around, if you first make a conflicting name & then empty it, the conflicting error message will stay

### Server configuration
**Operating system**:
Debian
**Web server:**
Apache 2.2
**Database:**
sqlite
**PHP version:**
PHP 7.0.7-5
**ownCloud version:** (see ownCloud admin page)
10.0.0.12
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc150y5qiolb",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-core",
        "dbtype": "sqlite3",
        "version": "10.0.0.12",
        "logtimezone": "UTC",
        "skeletondirectory": "\/tmp\/data",
        "installed": true
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.2.9
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - testing
  - theme-example
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox
**Operating system:**
Debian

**Comment by phil-davis** [comment]
The error tip never updates from whatever is the first error that you get.
e.g. delete the file name and file type, leaving just a dot "." and you get the error pop up "," is an invalid file name. Enter stuff in the field that is wrong for other reasons, and it keeps telling you that first reason.
I will ave a look...

**Comment by phil-davis** [comment]
Those 2 PRs cover the places I could find where the text of a tooltip is rewritten on-the-fly and needs to be fixed up.
