### ISSUE TITLE
Update to 9.1.5

### ISSUE THREAD

**Issue by reaphil** [owncloud/core#27877]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'DROP INDEX activity_time': SQLSTATE[HY000]: General error: 5 database is locked

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'DROP INDEX activity_time': SQLSTATE[HY000]: General error: 5 database is locked

**Comment by kdslkdsaldsal** [comment]
@reaphil Not directly the answer you're probably looking for but anyway:

You're using SQLite which you shouldn't use on a productive system at all. A sane thing you should do is to migrate to a real DBMS like MySQL/MariaDB or PostgreSQL before doing the update to 9.1.5:

https://doc.owncloud.org/server/latest/admin_manual/configuration_database/db_conversion.html

**Comment by PVince81** [comment]
can't help without issue template https://raw.github.com/owncloud/core/master/.github/issue_template.md, likely an env issue
