### ISSUE TITLE
Problem with Integrity check - files not found

### ISSUE THREAD

**Issue by Wernfried** [owncloud/core#27876]
When I open my owcloud page I get a warning for failed integrity check:

`
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- updater/.travis.yml
		- updater/src/Utils/Locator.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [updater/.travis.yml] => Array
                        (
                            [expected] => 864555a5554f0a09d628a63d088dbe041e2acc7a414603a7070d7a4992391b90f97435164a29179e14dbb55b682d4922a57f6c7a957034251839966c6d5adbf3
                            [current] => e692491c6a85a5fad5c1c9f9bb1809d4fa279d4d0a371e7859e0b30a5b24685cb49f309f12d47d388ce17a4d651d02cadd4aa562fa68ef59e84680e4f7835512
                        )
                    [updater/src/Utils/Locator.php] => Array
                        (
                            [expected] => 8c3ef11c951855de8071c74f6a15b75f194ebca6ad42b3895d64ffe36d74c9637b2d60183d6ac85f0b862d6a0f6854b69b7fe9fdd79ce76e0f96faf6510e454b
                            [current] => a65b19916ffcb0713507e149e73890e2f73f25c2a8fbfef73407baee2a0db960dab93f12e746ff9121b2064a6ef3da242f52031b874b8b26e3d3f8d2bc6c20fd
                        )
                )
        )
)
`

My first idea to fix it was download the two files from here and copy them to my server. However, in source code I don't find any files for `updater/.travis.yml` or `updater/src/Utils/Locator.php`

How does owncloud check files which are not existing in source code?

My owncloud version is 9.1.5

Best Regards
Wernfried

**Comment by kdslkdsaldsal** [comment]
@Wernfried Please note that this is a bugtracker for ownCloud. Support questions like these needs to go to https://central.owncloud.org/.

Side-note: "core" in that list is not the "core" folder within the ownCloud installation path (e.g. /var/www/owncloud/core but the main installation path (e.g. /var/www/owncloud). Those files exists there.

**Comment by PVince81** [comment]
@VicDeo did .travis.yml make it into the release ? 😮

**Comment by kdslkdsaldsal** [comment]
@PVince81 Yes, that file made it into the release. But the OP used https://github.com/owncloud/core/archive/v9.1.5.zip which doesn't included the updater folder at all.

**Comment by PVince81** [comment]
Don't use github releases which is really just a tarball of the source code, we don't publish official tarballs there.

Please download from the official locations: https://owncloud.org/install/#edition

**Comment by Kawohl** [comment]
from IRC, saint_: Kajoka i did not install from github. i installed from the source a long time ago, and used the UPDATER in the admin menu .

**Comment by VicDeo** [comment]
what happens after clicking "Rescan" ?
> Some files have not passed the integrity check. Further information on how to resolve this issue can be found in our documentation. (List of invalid files… / Rescan…)

**Comment by PVince81** [comment]
> installed from the source 

what source exactly ? git clone ? github source download ? (as I said it cannot work properly from source here https://github.com/owncloud/core/issues/27876#issuecomment-301398628)

**Comment by PVince81** [comment]
Not an OC bug, env bug or used wrong source -> close.

If you need further help to fix your env, go to http://central.owncloud.org/

**Comment by VicDeo** [comment]
@Wernfried according to the changelog this is a known issue  https://owncloud.org/changelog/
It should be fixed in OC 9.1.5 (when updating from 9.1.5 to versions higher than 9.1.5)
You can find these files in the 9.1.5 package at the  changelog page and then click `trigger rescan`
