### ISSUE TITLE
Rename ".part" extension to something more oc specific

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#27878]
Drop the file extension of ".part" files and use a suffix like '_octemp' to hide partially uploaded files.

This would make it possible to upload legitimate ".part" files.

- [ ] replace extension in many locations (just grep the code!)
- [ ] Beware: might need a repair step on upgrade to remove stray part files that might still be around on user's filesystems. Not doing so would have people suddenly see a little invasion of old part files.
- [ ] adjust clients to un-blacklist ".part" files ?

@butonic @pmaier1

**Comment by michaelstingl** [comment]
If this don't get fixed in the near future, perhaps https://github.com/owncloud/core/issues/28092 could be a workaround.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by phil-davis** [comment]
seems a useful thing to do some day
