### ISSUE TITLE
Update 10.0 install packages ASAP...

### ISSUE THREAD

**Issue by creopard** [owncloud/core#27892]
Due to the fact that there is an installation error in 10.0 with the .htaccess-file, since most webhosted installations might run PHP with mod_fcgid, the fix from https://github.com/owncloud/core/pull/27748
is not yet included in the download packages:

https://download.owncloud.org/community/owncloud-10.0.0.zip
https://download.owncloud.org/community/owncloud-10.0.0.tar.bz2

I guess not every user will search the github repository for this fix...

**Comment by kdslkdsaldsal** [comment]
The fix will be shipped with the upcoming 10.0.1 (see https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule) so there is no need to create an issue for this.

**Comment by creopard** [comment]
I see your point, but please also take into account that this (IMHO major) installation issue frustates users with shared webhosting infrastructures for at least a wohle month(!) so they might directly migrate to NC...

**Comment by DeepDiver1975** [comment]
will be fixed with 10.0.1
