### ISSUE TITLE
PHP error message appear after switching cron job from "AJAX"(default) to "Cron"

### ISSUE THREAD

**Issue by creopard** [owncloud/core#27902]
These kind of error messages appear in the log after(!) switching from an AJAX cron job to a "real" cron job executing every 15 minutes!

### Steps to reproduce
1. Login to nextcloud to admin area
2. Set Cron from AJAX(default) to "Cron"
3. Setup a cron job in webhost admin panel executing every 15 minutes
4. Check logfile

### Expected behaviour
no errors should show up

### Actual behaviour
> message":"Undefined index: REQUEST_METHOD at \/home\/public_html\/owncloud\/lib\/private\/Route\/Router.php#79"}
> message":"Undefined index: REQUEST_URI at \/home\/public_html\/owncloud\/lib\/base.php#180"}

### Server configuration

**Operating system**:
RedHat
**Web server:**
Apache 2.4
**Database:**
10.1.22-MariaDB
**PHP version:**
7.0.18
**Owncloud version:** 
10.0.0.12
**Updated from an older ownCloud or fresh install:**
fresh install
**Where did you install ownCloud from:**
ownCloud homepage
**Signing status:**
```
- core
	- INVALID_HASH
		- .htaccess
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

BTW, Nextcloud 11 got the same issue
https://github.com/nextcloud/server/issues/4553
which is fixed in the meantime:
https://github.com/nextcloud/server/pull/4873

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
