### ISSUE TITLE
Click on favourite button triggers folder download

### ISSUE THREAD

**Issue by labkode** [owncloud/core#27901]
* Go to shared with me
* Open the details menu of a shared folder
* Click on the star favorite button

The expected behavior would be to have the folder marks as favorite but instead it is downloaded.

Happens at least from version 8 to latest

**Comment by SergioBertolinSG** [comment]
Cannot reproduce with 10.0.0:
 {"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.0.12","versionstring":"10.0.0","edition":"Enterprise","productname":"ownCloud"}

Please fill the template issue.

**Comment by PVince81** [comment]
Also make sure to disable third party apps, just in case they are interfering with the links

**Comment by labkode** [comment]
Hi, I forgot that latest (10) was released days ago.

I can reproduce the problem from official docker image in versions 9.1.4 and 8.2.11.
In version 10* it does not occur.

**Comment by labkode** [comment]
No extra apps enabled, just clean docker run

**Comment by PVince81** [comment]
detailed steps... browser JS logs ?

**Comment by labkode** [comment]
Hi @PVince81 ,

no errors in JS browser log.
The detailed steps are the ones I posted before

**Comment by PVince81** [comment]
Mind providing the URL of the docker you used and the exact commands you typed for setting it up ?

**Comment by labkode** [comment]
```
docker run -d -p 80:80 owncloud:8
```

and 

```
docker run -d -p 80:80 owncloud:9
```

Urls:

```
[root@playground ~]# docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
docker.io/owncloud        8                   5150e7fc20c9        9 days ago          562.4 MB
docker.io/owncloud        9                   fb388c121e47        8 weeks ago         545.2 MB
```

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
