### ISSUE TITLE
LDAP Issues finding all users

### ISSUE THREAD

**Issue by LogAU** [owncloud/core#27912]
### Steps to reproduce
1.Setup LDAP Server
2.Apply user and person under "user" tab and create ldap filter
3. Check LDAP/AD Username and LDAP filter 

### Expected behaviour
Pull all users from LDAP ~400

### Actual behaviour
Only sees ~30 users

### Server configuration
**Operating system**:
centOS 7
**Web server:**
Apache/2.4.6
**Database:**
sqlite-3.7.17
**PHP version:**
PHP 5.4.16
**ownCloud version:** (see ownCloud admin page)
9.1.5
**Updated from an older ownCloud or fresh install:**
fresh install
**Where did you install ownCloud from:**
https://download.owncloud.org/download/repositories/stable/owncloud/
**Signing status (ownCloud 9.0 and above):**
Not sure what this is
```
ldap config
https://gist.github.com/LogAU/2ffcee5562ae09de1acada8d589b7ba2

logs
https://gist.github.com/LogAU/6cf417b1ac666ca9369e2ee98bafd693

**Comment by PVince81** [comment]
possible duplicate https://github.com/owncloud/core/issues/27701

**Comment by LogAU** [comment]
Yeah, saw that and decided to add more info from my setup.

**Comment by LogAU** [comment]
The user account we were trying to use was not able to see all the members of that group it seems.
