### ISSUE TITLE
Can't test Email server settings, but can't set personal email address either

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/core#27916]
### Steps to reproduce
1. Clean install OC 10.0.x
2. Go to personal setting, try to set email address.
3. The form tells me, that a confirmation mail has been sent. Woops, I didn't expect that and I didn't receive an email since I didn't configure Email server ahead of time because I knew that for me to test my SMTP settings, I would need to have my email address set wich I tried just now.
4. Goto Admin-settings and try to setup SMTP Server (hoping my input is correct)
5. Click "test" but it won't test since I don't have my email address set in personal
6. Go back to personal settings trying to send confirmation mail again.
7. The script tells me to come back / try later since an email has already been sent.

(I tried again "later" to resend mail. Retuned _"Could not send email address change confirmation mail"_. I still can't test since I don't have an email address set)

### Expected behavior
Not sure.

### Actual behavior
See above.

### Server configuration
Won't matter in this case.

**ownCloud version:** (see ownCloud admin page)
10.0.1 RC1

**Updated from an older ownCloud or fresh install:**
fresh

**Comment by DeepDiver1975** [comment]
I recognized this issue as well today. 🐔 🥚

**Comment by felixheidecke** [comment]
Here might be a solution:

1. Don't set a default mail method.
2. Append a separate input field for a test address below the Email server settings.

**Comment by PVince81** [comment]
or set your own email address in the users page where no verification is needed.

Other possibility: disable email verification for OC admins.

**Comment by pmaier1** [comment]
My input on this can be found [here](https://github.com/owncloud/core/pull/27586#issuecomment-299457565). Thanks for opening the issue. IMO we should disable mail verification for admins as @PVince81 suggested.

**Comment by PVince81** [comment]
I'll take care

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/27921
