### ISSUE TITLE
Can't save any settings in OC 10

### ISSUE THREAD

**Issue by Traule** [owncloud/core#27917]
### Steps to reproduce
1.Mark any settings Box
2. 
3.

### Expected behaviour
I want eg. to enable some settings in the sharingapi but it won't save the changes

### Actual behaviour
It should save the changes

### Server configuration
**Operating system**:Debian

**Web server:** Apache

**Database:** MySQL

**PHP version:**

**ownCloud version:** 10.00

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:** from the archive

**Signing status (ownCloud 9.0 and above):**

https://gist.github.com/Traule/c21ab54b7e5d3996be1098cfd11496d8.js

**The content of config/config.php:**

[config_report_20170517.txt](https://github.com/owncloud/core/files/1008048/config_report_20170517.txt)

**List of activated apps:**
![app_list](https://cloud.githubusercontent.com/assets/28758889/26159502/05382898-3b1f-11e7-9249-6224a88e6dc3.png)

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by PVince81** [comment]
You seem to have some code integrity issues. If the wrong code is loaded, anything can happen (or break).

Check the Javascript console after ticking the checkboxes, it could contain clues.

**Comment by PVince81** [comment]
Please resolve the integrity issues (you can check http://central.owncloud.org/ as it's a common problem people have when not properly replacing source code on updates).

If the problem persists with zero integrity issues, feel free to reopen. Thanks.

**Comment by Traule** [comment]
Hello, 
thanks for your fast feedback. I solved all integrity issues. The problem is still there. Here a screenshot of the Javascript console.
![oc_js](https://cloud.githubusercontent.com/assets/28758889/26188693/f0670966-3ba0-11e7-8654-d8619f24f145.png)
I hope you have any suggestions for me.

**Comment by PVince81** [comment]
Check the network console for errors. It is likely that your setup somehow blocks access to the file "core/oc.js" which prevents loading the config. Or maybe other JS files are blocked.

**Comment by Traule** [comment]
This is the output from the network console when i ticked an checkbox. 

 Uncaught TypeError: Cannot read property 'setValue' of undefined admin.js?v=414c9d9…:87 
    at HTMLInputElement.<anonymous> (admin.js?v=414c9d9…:87)
    at HTMLInputElement.dispatch (jquery.js:4435)
    at HTMLInputElement.r.handle (jquery.js:4121)

How can I fix the blocked oc.js file?

**Comment by PVince81** [comment]
check the network console for error, when loading the page, before the action

**Comment by Traule** [comment]
It look like there is an problem with the config.js

![network_when_page_loading](https://cloud.githubusercontent.com/assets/28758889/26191972/4c0d3c0e-3bb0-11e7-8de9-5d318f2800ce.png)

**Comment by PVince81** [comment]
yes, I suggest you search or ask on http://central.owncloud.org/ to get help to solve this.

This is very likely an environment configuration problem, not an ownCloud bug.
