### ISSUE TITLE
Home folder unavailable after upgrade til version 10

### ISSUE THREAD

**Issue by shade73** [owncloud/core#27920]
After upgrading to owncloud 10 (Ups.. update server via Ubuntu Landscape service) I have a single (know of) user that cannot access his home folder. Have other users that work fine.
strong text

occ files:scan username find alot of files'.
Starting scan for user 1 out of 1 (username)

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 568     | 4125  | 00:00:08     |
+---------+-------+--------------+
Steps to reproduce
1. Open owncloud web URL.
2. Logon with user.
3. No files are shown, and the error message "This folder is unavailable, please check the logs or contact the administrator" is shown. By clicking files shared with others, some folder can be shown anyway.

Expected behaviour
Show all files in home folder.

Actual behaviour
Empty folder are shown.

Server configuration
Operating system: Ubuntu 16.04 LTS
Web server: Nginx 1.12.0
Database: Percona (Mysql) 5.7.17-13-1.xenial
PHP version: 7.1.4
ownCloud version (see ownCloud admin page): 10.0.0.12
Updated from an older ownCloud or fresh install: 9.1.5
Special configuration (external storage): CIFS

ownCloud configuration

{
    "system": {
        "updatechecker": false,
        "instanceid": "oc242d6bc4is",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.dom.lan"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/owncloud.dom.lan",
        "dbtype": "mysql",
        "version": "10.0.0.12",
        "dbname": "euccloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 0,
        "mail_from_address": "owncloud",
        "mail_smtpmode": "smtp",
        "mail_domain": "dom.lan",
        "mail_smtphost": "exchange01.dom.lan",
        "mail_smtpport": "25",
        "maintenance": false
    }
}
ownCloud log (data/owncloud.log)

{"reqId":"1NWNaCYmrOngnaOhMQYE","level":3,"time":"2017-05-03T22:13:29+00:00","remoteAddr":"127.127.127.127","user":"username","app":"remote","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function getPermissions() on array\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(272): OC\\\\Files\\\\View->getDirectoryContent('\\\/')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/SharesPlugin.php(169): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChildren()\\n#2 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\SharesPlugin->handleGetProperties(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1058): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(980): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1665): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('', Array, 1)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#8 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#13 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php\",\"Line\":1458}"}
{"reqId":"pQ6xEiLC2kYMbm0vctJs","level":3,"time":"2017-05-03T22:13:29+00:00","remoteAddr":"127.127.127.127","user":"username","app":"remote","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function getPermissions() on array\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(272): OC\\\\Files\\\\View->getDirectoryContent('\\\/')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/SharesPlugin.php(169): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChildren()\\n#2 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\SharesPlugin->handleGetProperties(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1058): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(980): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1665): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('', Array, 1)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#8 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#13 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php\",\"Line\":1458}"}
{"reqId":"CPrV2Y63SrQoqqeA3YM1","level":0,"time":"2017-05-03T22:13:34+00:00","remoteAddr":"127.127.127.127","user":"username","app":"core","method":"REPORT","url":"\/remote.php\/webdav\/","message":"OC\\Tags::getFavorites, exception: Could not find category \"_$!<Favorite>!$_\""}
{"reqId":"dMUlc6mimnUzD8KqRgVJ","level":0,"time":"2017-05-03T22:13:45+00:00","remoteAddr":"127.127.127.127","user":"username","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/Hjemmemappe","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name Hjemmemappe could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(966): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Hjemmemappe')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1665): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('Hjemmemappe', Array, 1)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":182,\"User\":\"username\"}"}
{"reqId":"rQZPQn2TP3thR8o5riKR","level":3,"time":"2017-05-03T22:13:45+00:00","remoteAddr":"127.127.127.127","user":"username","app":"remote","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function getPermissions() on array\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(272): OC\\\\Files\\\\View->getDirectoryContent('\\\/')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/SharesPlugin.php(169): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChildren()\\n#2 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\SharesPlugin->handleGetProperties(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1058): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(980): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1665): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('', Array, 1)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#8 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#13 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php\",\"Line\":1458}"}
{"reqId":"ZKP08Drxen1t2PqSAkRf","level":0,"time":"2017-05-03T22:13:49+00:00","remoteAddr":"127.127.127.127","user":"username","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/Hjemmemappe","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name Hjemmemappe could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(966): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Hjemmemappe')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1665): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('Hjemmemappe', Array, 1)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":182,\"User\":\"username\"}"}
{"reqId":"cb1iL1XZlvvvPd48a27x","level":3,"time":"2017-05-03T22:13:49+00:00","remoteAddr":"127.127.127.127","user":"username","app":"remote","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function getPermissions() on array\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(272): OC\\\\Files\\\\View->getDirectoryContent('\\\/')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/SharesPlugin.php(169): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChildren()\\n#2 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\SharesPlugin->handleGetProperties(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1058): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(980): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1665): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('', Array, 1)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#8 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#13 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php\",\"Line\":1458}"}
{"reqId":"4uujbeJg7eBSpevgcZVj","level":1,"time":"2017-05-03T22:15:01+00:00","remoteAddr":"","user":"--","app":"cli","method":"--","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for local cache"}
{"reqId":"4uujbeJg7eBSpevgcZVj","level":1,"time":"2017-05-03T22:15:01+00:00","remoteAddr":"","user":"--","app":"cli","method":"--","url":"--","message":"Memcache \\OC\\Memcache\\APCu not available for distributed cache"}
{"reqId":"4uujbeJg7eBSpevgcZVj","level":0,"time":"2017-05-03T22:15:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"--","url":"--","message":"Started background job of class : OCA\\Files\\BackgroundJob\\ScanFiles with arguments : "}

Integrity status for oC9+

No errors have been found.

**Comment by terrytibbles** [comment]
Is their folder in the data directory? What are the permissions on it?

**Comment by shade73** [comment]
Yes, it is in the data directory.

Permissions are:

drwxr-xr-x  7 www-data www-data

the same as the other users have.

**Comment by PVince81** [comment]
Find the user's home path in `oc_accounts` table, is it correct ?
Then `select * from oc_storages where id like '%the_user_id%` (replace "the_user_id" if the user id)

**Comment by shade73** [comment]
The home path in oc_accounts is correct.

The result of the SQL is:

+--------------------------------------------------+------------+-----------+--------------+
| id                                               | numeric_id | available | last_checked |
+--------------------------------------------------+------------+-----------+--------------+
| smb::manager@hera.fmts.lan//ansatte$//tors0331/  |        148 |         1 |         NULL |
| home::tors0331                                   |        149 |         1 |         NULL |
| smb::tors0331@hera.fmts.lan//ansatte$//tors0331/ |        469 |         1 |   1493849629 |
| smb::tors0331@hera.fmts.lan//ansatte$//clau4803/ |        538 |         1 |         NULL |
| smb::clau4803@hera.fmts.lan//ansatte$//tors0331/ |        539 |         1 |         NULL |
| smb::tors0331@hera.fmts.lan//ansatte$//benn0709/ |        542 |         1 |         NULL |
| smb::tors0331@hera.fmts.lan//ansatte$//jens153a/ |        543 |         1 |         NULL |
| smb::benn0709@hera.fmts.lan//ansatte$//tors0331/ |        544 |         1 |         NULL |
| smb::tors0331@hera.fmts.lan//ansatte$//ulfx0205/ |        646 |         1 |         NULL |
| smb::tors0331@hera.fmts.lan//ansatte$//fred119q/ |        647 |         1 |         NULL |
| smb::clau4803@hera//ansatte$//tors0331/          |        649 |         1 |         NULL |
+--------------------------------------------------+------------+-----------+--------------+

**Comment by shade73** [comment]
Problem still exists 10.0.2

**Comment by shade73** [comment]
Anything new on this issue?

**Comment by Huaba** [comment]
I've had exactly the same issue. Some users won't work. New users always work. 

- paths correct
- permissions correct

**Comment by Huaba** [comment]
Found my problem: i've had activated external storage. One external storage had bad permissions. After remove this storage, the local storage load for this users...

**Comment by shade73** [comment]
If I deactivate external storage then the user can access his local files again, as I activate external storage again he loses access to the local files yet again, so it seems like the same problem.

The external storage is needed, so I cannot keep it deactivated, how do I fix the problem, remove the entries in oc_accounts?

**Comment by PVince81** [comment]
What external storages did you use and where did you mount them ?

You could provide a snippet of the oc_mounts* tables

**Comment by shade73** [comment]
I have solved the problem, or worked around it.

I copied all the users files out of the server, then deleted the user, created the user again and synced all the files back with the client.

Problem is now gone.
