### ISSUE TITLE
Unexpected error creating public link in absence of "publicUpload" parameter

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#27922]
### Steps to reproduce
1. In sharing dashboard of admin web UI, disable `Allow public uploads`
2. Client requests a new public link to a folder. (if the `Allow public uploads` capability is disabled in admin UI dashboard, in clients it is not displayed). The option is not included in the request, so it is optional:

![screen shot 2017-05-17 at 17 14 25](https://cloud.githubusercontent.com/assets/14894746/26163722/bebf64ce-3b2a-11e7-8a9c-e98e5f0789ea.png)

### Expected behaviour
New public link is created.

### Current behaviour
Server returns an error:

![screen shot 2017-05-17 at 16 59 03](https://cloud.githubusercontent.com/assets/14894746/26163872/3c8d90d8-3b2b-11e7-8106-8261753178d4.png)

### Server configuration

Version 10.0.1RC1
This behaviour does not happen in 10.0.0

This curl command can be useful:

```
curl -k \
    -H 'Host:xxxxxx' \
    -H 'Content-Type:application/x-www-form-urlencoded' \
    -H 'Accept:*/*' \
    -H 'User-Agent:Mozilla/5.0 (iOS) ownCloud-iOS/3.5.3' \
     [...]
    -H 'Authorization:Basic YWRtaW46UGFzc3dvcmQ=' \
    -H 'OCS-APIREQUEST:true' \
    -X POST 'https://xxxxxxxxxxx/ocs/v1.php/apps/files_sharing/api/v1/shares' \
    --data-binary 'path=/Photos/&shareType=3&name=Photoslink'
```

**Comment by SamuAlfageme** [comment]
I can reproduce in the Desktop client. Can be fixed appending `permissions=1` in the share request, in the same fashion the webUI does:

```
-X POST 'https://<server_url>/ocs/v1.php/apps/files_sharing/api/v1/shares' \ 
--data-binary 'path=/Photos&shareType=3&name=Photoslink&permissions=1'
```

But, of course, permission-handling should be transparent to clients.

**Comment by davivel** [comment]
> I can reproduce in the Desktop client. Can be fixed appending permissions=1 in the share request.

That's not a proper solution, IMHO.

Both ```permissions``` and ```publicUploads```  are optional parameters. A ```POST``` request not including them should default to a new resource with valid values for them, not to a version that is forbidden by the current server configuration.

cc @PVince81 @felixheidecke

**Comment by PVince81** [comment]
Ok that's a bug. I fixed an issue recently there and remember the code is supposed to default to 1 if no "permissions" is set. I'll have a look...

**Comment by PVince81** [comment]
Wrote two integration tests, could not reproduce the issue... permissions default to 1 on master.

Will try with curl...

**Comment by PVince81** [comment]
on master:
```
% curl -u admin:admin -H 'Content-Type:application/x-www-form-urlencoded' -H 'OCS-APIREQUEST:true' -X POST 'http://localhost/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares' --data-binary 'path=/welcome.txt&shareType=3&name=Photoslink'
```

I get a proper XML response.

Now let's check 10.0.1RC1...

**Comment by PVince81** [comment]
ah, oh course... it needs to be a folder, not a file... retrying...

**Comment by nasli** [comment]
If you give more than 1 for permissions on create it is not allowed, we need the publicUpload to give more permissions

**Comment by PVince81** [comment]
It needs to work the same like it did in 9.1

**Comment by PVince81** [comment]
ok, then maybe it's the files_drop bit that changed behavior slightly...

**Comment by PVince81** [comment]
this commit: b621ea2d2d9e2d7470e8d5fc7bcd22ef08276bb5

I'll try and fix this...

**Comment by PVince81** [comment]
seems it was a wrongly written condition, PR here https://github.com/owncloud/core/pull/27927 please review

**Comment by jesmrec** [comment]
Reviewed:

- [X] iOS
- [X] Android

any check related with desktop client @SamuAlfageme?

@PVince81

**Comment by SamuAlfageme** [comment]
LGTM 👍
