### ISSUE TITLE
"ocdev" package missing from python package manager "PIP"

### ISSUE THREAD

**Issue by ghafoors** [owncloud/core#27928]
### Steps to reproduce
Ran the command. "sudo pip3 install ocdev"

### Expected behaviour
Ideally it should install the python package ocdev

### Actual behaviour
returned an error:
Collecting ocdev
  Could not find a version that satisfies the requirement ocdev (from versions: )
No matching distribution found for ocdev

verbose:
Collecting ocdev
  1 location(s) to search for versions of ocdev:
  * https://pypi.python.org/simple/ocdev/
  Getting page https://pypi.python.org/simple/ocdev/
  Looking up "https://pypi.python.org/simple/ocdev/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/ocdev/ HTTP/1.1" 404 28063
  Status code 404 not in [200, 203, 300, 301]
  Could not fetch URL https://pypi.python.org/simple/ocdev/: 404 Client Error: Not Found for url: https://pypi.python.org/simple/ocdev/ - skipping
  Could not find a version that satisfies the requirement ocdev (from versions: )

### Server configuration
Operating system: UBUNTU 16.04

Web server: Apache

Database: MYSQL

PHP version: 7.0

ownCloud version: 10.0.1 RC1 (git)

**Updated from an older ownCloud or fresh install: Fresh

**Where did you install ownCloud from: GIT

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
ocdev is discontinued ....

**Comment by kdslkdsaldsal** [comment]
> ocdev is discontinued ....

Looks like this is not really documented as there are still quite a lot references to that in the documentation: https://github.com/owncloud/documentation/issues/2672
