### ISSUE TITLE
 Updating to 10.0.0 from 9.1 failure.

### ISSUE THREAD

**Issue by fredbcode** [owncloud/core#27939]
**Steps to reproduce**

Follow the documentation about manual upgrade, my owncloud directory is completely new except my database and config.php

The web server is started and I just click to upgrade

**Expected behaviour**

It should finalize the update and allow access to the update version of the software.
Actual behaviour

files_external: An exception occurred while executing 'CREATE TABLE "oc_external_mounts" ("mount_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, "mount_point" VARCHAR(128) NOT NULL, "storage_backend" VARCHAR(64) NOT NULL, "auth_backend" VARCHAR(64) NOT NULL, "priority" INTEGER DEFAULT 100 NOT NULL, "type" INTEGER NOT NULL)': SQLSTATE[HY000]: General error: 1 table "oc_external_mounts" already exists

**Operating system:** linux Debian jessie 8

Database:  sqlite 

**PHP version:** 5.6.30

**Updated from an older ownCloud or fresh install:** Update

**Where did you install ownCloud from:** owncloud.org

**The content of config/config.php: !! private value changed !!**

```
<?php
$CONFIG = array (
  'instanceid' => 'ocutdpn',
  'passwordsalt' => 'wWPxxxxxxxEThsj7FZ',
  'secret' => 'kPzvLxxxxxxWC7gMLpBg',
  'trusted_domains' => 
  array (
    0 => 'ksksks.com',
    1 => '192.168.x.xx',
  ),
  'enable_certificate_management' => true,
  'datadirectory' => '/disk3/cloud',
  'overwrite.cli.url' => 'https://ksksks.com:8081/owncloud',
  'dbtype' => 'sqlite3',
  'version' => '9.1.4.2',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'xxxx',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'free.fr',
  'mail_smtphost' => 'smtp.free.fr',
  'mail_smtpport' => '25',
  'loglevel' => 0,
  'logfile' => '/var/log/owncloud.log',
  'session_lifetime' => 3600,
  'cache_path' => '/tmp/',
  'sqlite.journal_mode' => 'WAL',
  'filesystem_check_changes' => 0,
  'theme' => '',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
  'updater.secret' => '$2yxxxxxxxxdy53KC.e98AQM6cgvXFZfqKdKrj8G',
  'htaccess.RewriteBase' => '/owncloud',
);

```
**List of activated apps:*** Can't access to determine.

**Are you using external storage, if yes which one**: No

**Are you using encryption:**  Yes auto generated certificate

**Comment by PVince81** [comment]
can you paste the contents of the "apps/files_external/appinfo" folder ?

**Comment by fredbcode** [comment]
ls apps/files_external/appinfo/
app.php  database.xml  info.xml  register_command.php  routes.php  signature.json  update.php

**Comment by PVince81** [comment]
where does this database.xml file come from ? it's not in the 10.0.0 tarballs

**Comment by PVince81** [comment]
please make sure to first delete the old source code before extracting the new tarballs to avoid having old stuff lying around and causing issues

**Comment by felixboehm** [comment]
Please do not copy new code over the old code, as this leads to remaining old code files.
Can you retry by following the steps in detail:
```
4. Rename your current ownCloud directory, for example owncloud-old.

5. Unpacking the new archive creates a new owncloud directory populated 
with your new server files. Copy this directory and its contents to the original 
location of your old server, for example /var/www/, so that once again you 
have /var/www/owncloud.
```
Source: https://doc.owncloud.org/server/10.0/admin_manual/maintenance/manual_upgrade.html

**Comment by kdslkdsaldsal** [comment]
FWIW in the comment above steps 6. and 7. are also quite important so its better do skip the quote and follow the link at "Source" directly.
