### ISSUE TITLE
Thumbnails are not shown in the trashbin section

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27932]
### Steps to reproduce

1. Delete a image file in Files menu
2. Go to Deleted files menu

### Expected behaviour

The thumbnails are shown in the Trashbin

### Actual behaviour

The thumbnails are not shown as it was done in previous oC versions

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.1" daily master

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"JrD5olQ5RXw4LDRvLxAv","level":3,"time":"2017-05-18T11:54:45+00:00","remoteAddr":"82.159.139.58","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/core\/preview.png?file=%2FScreen+Shot+2017-05-18+at+08.51.43.png&x=538&y=303&a=1&mode=cover&c=1a97eafbd76cbd600faf271bb719fd5e&forceIcon=0","message":"fopen(\/opt\/owncloud\/data\/admin\/thumbnails\/24\/118-214-max-cover.png): failed to open stream: No such file or directory at \/opt\/owncloud\/lib\/private\/Files\/Storage\/Local.php#276"}
```

### Client configuration

**browser**

Mozilla

![screen shot 2017-05-18 at 13 23 03](https://cloud.githubusercontent.com/assets/10596560/26201191/19866306-3bd2-11e7-87d3-105af8e0a4e3.png)

**Comment by PVince81** [comment]
Broken through https://github.com/owncloud/core/pull/27558

Might need extra work from the PR to also work correctly with trashbin.

@VicDeo
