### ISSUE TITLE
Delete wiki/Reviews-tutorials-and-videos-of-ownCloud

### ISSUE THREAD

**Issue by lefherz** [owncloud/core#27936]
At https://github.com/owncloud/core/wiki/Reviews-tutorials-and-videos-of-ownCloud there is an outdated list from 2015 about ownCloud installation guides. It is currently linked to from https://owncloud.org/faq/ .

Am I right that no one wants to maintain this? You should consider deleting the list.

**Comment by PVince81** [comment]
If all of them are outdated then I'd be fine removing them... We could start a new list somewhere else like the main web page. I'm not even sure how people are supposed to find this wiki page in the first place.

**Comment by PVince81** [comment]
@lefherz I'll leave the decision up to you :-)

**Comment by lefherz** [comment]
Apparently I already took down the link in the FAQ.

The information is totally outdated, and I don't think we need such a page. can you delete it? I can't find the button to edit or delete anything.

**Comment by DeepDiver1975** [comment]
killed with 🔥
