### ISSUE TITLE
[10.0.1RC3] after upgrade downloaded apps have version 'false'

### ISSUE THREAD

**Issue by butonic** [owncloud/core#27949]
### Steps to reproduce
1. intall oc 9.1.x
2. upgrade to 10.0.1RC3
3. run x sudo -u www-data php /var/www/oc/owncloud-9.1-10x/occ app:list

### Expected behaviour
get a list of installed apps with the version

### Actual behaviour
version for apps downloaded from the market is true:

Enabled:
  - activity: true
  - admin_audit: 0.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.9
  - enterprise_key: 0.1.0
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: true
  - files_sharing: 0.10.0
  - files_texteditor: true
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firewall: 2.4.0
  - firstrunwizard: 1.1
  - gallery: true
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - systemtags_management: 0.2.0
  - templateeditor: 0.1
  - theme-enterprise: 1.0.0
  - updatenotification: 0.2.1
  - user_ldap: true
  - windows_network_drive: 0.6.0
  - workflow: 0.2.3
Disabled:
  - announcementcenter
  - encryption
  - external
  - files_antivirus
  - files_ldap_home
  - objectstore
  - password_policy
  - sharepoint
  - theme-example
  - user_external
  - user_shibboleth

cc @DeepDiver1975 @IljaN

**Comment by PVince81** [comment]
confirmed... arghh....

**Comment by PVince81** [comment]
```
| files_texteditor      | enabled                              | yes                                         |
| files_texteditor      | installed_version                    | 0                                           |
| files_texteditor      | ocsid                                | 166051                                      |
| files_texteditor      | signed                               | true                                        |
| files_texteditor      | types                                |                                             |
```

critical...
