### ISSUE TITLE
oC 10.0.1 RC1: Display Issue When config dir is missing

### ISSUE THREAD

**Issue by dragotin** [owncloud/core#27942]
### Steps to reproduce
1. Unpack the owncloud-10 rc1 tarball
2. Point an Apache to the directory without fixing permissions

### Expected behaviour
A hint to fix permissions should be displayed properly

### Actual behaviour
The hint has encoding issues, see screenshot: It does not show `Can't` but `Can&#039;t`

![oc10_config_not_writeable](https://cloud.githubusercontent.com/assets/1070214/26221561/4306dd56-3c17-11e7-9940-60b89fc84747.png)

**Comment by dragotin** [comment]
Note that RC2 seems to behave differently: #27943

**Comment by singhabhinav81** [comment]
the same problem arises because the folder "data"  not created by the composer.
