### ISSUE TITLE
Left menu doesn't shrink space left

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#27954]
### Steps to reproduce

1. Open upper left menu.

### Expected behaviour

When having only two elements It should had only space for two elements not three.

### Observed behaviour

Space for three.

![screen shot 2017-05-19 at 12 21 42](https://cloud.githubusercontent.com/assets/9048796/26243942/06c8cdfa-3c8e-11e7-98d2-66a155efb0cb.png)

**ownCloud version:**
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.0.12","versionstring":"10.0.0","edition":"Enterprise","productname":"ownCloud"}

**Browser:**
Chrome

cc @felixheidecke

**Comment by PVince81** [comment]
regression ?

**Comment by SergioBertolinSG** [comment]
Well in previous versions there were more elements so it wasn't a problem then:

![screen shot 2017-05-19 at 14 01 17](https://cloud.githubusercontent.com/assets/9048796/26246922/d12075aa-3c9b-11e7-974b-d6b88e93dd33.png)

**Comment by SergioBertolinSG** [comment]
Not a regression, it happens also in 9.1.5:

![screen shot 2017-05-19 at 14 04 04](https://cloud.githubusercontent.com/assets/9048796/26246977/151722ae-3c9c-11e7-9556-6c75e3e9ec99.png)

**Comment by PVince81** [comment]
backlog

**Comment by PVince81** [comment]
if we ever want to polish design a bit we can always searhc for all the "design" tickets

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
cc @felixheidecke please reopen if you think this is important enough
