### ISSUE TITLE
Extend ContentSecurityPolicy to support currrent list of CSP

### ISSUE THREAD

**Issue by cortho** [owncloud/core#27955]
According to MDN[1] there are several CSP directives such as worker-src and sandbox which are not currently supported by ownCloud.

From browsing the issues I found out, that frame-ancestor is being implemented in https://github.com/owncloud/core/pull/24845

[1] https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy

**Comment by felixboehm** [comment]
@Peter-Prochaska Please coordinate with @cortho, he would volunteer to implement this.

**Comment by Peter-Prochaska** [comment]
@cortho can you write a email to pprochaska@owncloud.com, what you want to implement?

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
