### ISSUE TITLE
The additional panel for admin and personal shows different behaviour 

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#27959]
### Steps to reproduce
1. As an admin, go to the settings page
2. Check the additional panel in the personal section
3. Check the additional panel in the admin section

### Expected behaviour
Either both panels dont show up if they're empty, or a message appear telling the panel is empty.

### Actual behaviour
The personal panel show a message: "Error No panels for this section." The admin one shows a blank panel without any message. This is quite confusing since the admin doesn't know if there is a failure.

There is no error in the log file.

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.1RC3

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** tarball

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/27919 ?

**Comment by jvillafanez** [comment]
Yep, closing this as duplicated.
