### ISSUE TITLE
Remove files menu for regular users

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27968]
![screen shot 2017-05-22 at 09 50 57](https://cloud.githubusercontent.com/assets/10596560/26297682/393b2c04-3ed4-11e7-9154-b649ffbc6cd6.png)

If a regular user can only access to files, then it is useless this menu

@felixheidecke

**Comment by hodyroff** [comment]
Activity will be used by most, but good point. We will have to consider for 10.0.2 how to handle this situation. No regression as it was possible to deactivate those apps with the same behaviour.

**Comment by PVince81** [comment]
cc @pmaier1 polishing item

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
