### ISSUE TITLE
No working PUT User-Provisioning API 

### ISSUE THREAD

**Issue by ChristopheHvd** [owncloud/core#27976]
Hi,
Using Owncloud 9.1.5, I'm having trouble using the PUT on the User-Provisionning API, to edit user's attribute.
I try to launch the request from two different ways :  
- the owncloud-sharp C# library
- Postman.
Every time, I receive the exact same response as [ #14283](https://github.com/owncloud/core/issues/14283) and [#20212](https://github.com/owncloud/core/issues/20212)

I tried to debug the server-side, in the Users.php file, the editUser(...) function, and see what's going on.
It seems like the $parameters['_put'] is a resource (good news) but the code is unable to read from it (as it looks for the $parameters['_put']['key'].

Any help on this?

**Comment by PVince81** [comment]
we need the full request, best would be in curl form

**Comment by SergioBertolinSG** [comment]
I have written a test to cover this. It is working fine. https://github.com/owncloud/core/pull/28090

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
