### ISSUE TITLE
Cannot uninstall / shipped apps in oC 10.0.1 using market app

### ISSUE THREAD

**Issue by davitol** [owncloud/core#27983]
### Steps to reproduce

1. Go to market app
2. Try to uninstall an app e.g. LDAP

### Expected behaviour

The app should be uninstalled

### Actual behaviour

The market throws an error and the app is not uninstalled

**Workaround: Disable the app and remove it with rm command**
### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:**

"version":"10.0.0.1" 

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**

```
```

### Client configuration

**browser**

Mozilla

![screen shot 2017-05-23 at 10 46 10](https://cloud.githubusercontent.com/assets/10596560/26347142/cde4b5da-3fa8-11e7-997b-0facb28e840a.png)

@PVince81 FYI

**Comment by PVince81** [comment]
need to remove some or most apps from shipped.json for this

**Comment by PVince81** [comment]
fixed in 10.0.2
