### ISSUE TITLE
Update error when duplicate sub-shares exist

### ISSUE THREAD

**Issue by lukovas** [owncloud/core#27990]
There was an error updating. Please, help!

OC\Share20\Exception\ProviderException: Parent of share should be unique

Detailed logs:

Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updated "activity" to 2.3.4
[1 / 28]: Drop old database table: calendar_calendars
[2 / 28]: Drop old database table: calendar_objects
[3 / 28]: Drop old database table: calendar_share_calendar
[4 / 28]: Drop old database table: calendar_share_event
[5 / 28]: Drop old database table: file_map
[6 / 28]: Drop old database table: foldersize
[7 / 28]: Drop old database table: fscache
[8 / 28]: Drop old database table: gallery_sharing
[9 / 28]: Drop old database table: locks
[10 / 28]: Drop old database table: log
[11 / 28]: Drop old database table: media_albums
[12 / 28]: Drop old database table: media_artists
[13 / 28]: Drop old database table: media_sessions
[14 / 28]: Drop old database table: media_songs
[15 / 28]: Drop old database table: media_users
[16 / 28]: Drop old database table: permissions
[17 / 28]: Drop old database table: pictures_images_cache
[18 / 28]: Drop old database table: principalgroups
[19 / 28]: Drop old database table: principals
[20 / 28]: Drop old database table: queuedtasks
[21 / 28]: Drop old database table: sharing
[22 / 28]: Drop old database table: clndr_calendars
[23 / 28]: Drop old database table: clndr_objects
[24 / 28]: Drop old database table: clndr_share_event
[25 / 28]: Drop old database table: clndr_share_calendar
[26 / 28]: Drop old database table: clndr_repeat
[27 / 28]: Drop old database table: contacts_addressbooks
[28 / 28]: Drop old database table: contacts_cards
[28 / 28]: Drop old database tables
[1 / 4]: Remove old (< 9.0) calendar/contact shares
[2 / 4]: Remove old (< 9.0) calendar/contact shares
[3 / 4]: Remove old (< 9.0) calendar/contact shares
[4 / 4]: Remove old (< 9.0) calendar/contact shares
[4 / 4]: Remove old (< 9.0) calendar/contact shares
[1 / 2]: Fix permissions so avatars can be stored again
[1 / 1]: Fix permissions so avatars can be stored again
[1 / 44]: Move user avatars outside the homes to the new location
[2 / 44]: Move user avatars outside the homes to the new location
[3 / 44]: Move user avatars outside the homes to the new location
OC\Share20\Exception\ProviderException: Parent of share should be unique

**Comment by PVince81** [comment]
Seems some of your shares are in an inconsistent state.

I suggest you check `select * from oc_share where share_type=2 order by id`.
These are sub-entries for each recipients. The parent share is the one where the "parent" column points to the parent share id. (`select * from oc_share where id=$parent`, replace $parent with the value from the column)

In your database, for some unknown reason, one of these sub-entries isn't pointing to the same parent like the others. Normally they all point to the same parent when it's the same share.

If you manage to find the matching broken share, please post the select result here so we can examine it (and tell you how to manually fix it)

**Comment by lars-sh** [comment]
I ran into just the same problem and checked the database based on your information. All seemed to be just fine, so I checked the exception in owncloud.log and finally the code. It seems there's an obvious mistake while performing "Ensure uniquenes of parents".

**Comment by 88fingerslukee** [comment]
I'm having a very similar issue except that the update succeeded.  The problem is that two of my users (the only ones who actually have shared anything) cannot login due these errors. Here is the select result as asked:
[owncloud issue.txt](https://github.com/owncloud/core/files/1062570/owncloud.issue.txt)

What do I do?

**Comment by lars-sh** [comment]
May you verify if https://github.com/owncloud/core/pull/28080/files helps?

**Comment by 88fingerslukee** [comment]
Yes, that did work! It allowed me to sign in but another user was still having trouble. I had to reset that user and now everything is good.

**Comment by PVince81** [comment]
From my understanding of that code is that it was designed to throw an exception if a subshare has more than one parent, which should never happen and means the data structure in the DB is corrupted (maybe through a bug).

On the other hand, failing hard like this isn't user friendly so maybe your fix is alright but would need to at least log something, maybe a warning, so that an administrator can spot that there is something wrong with the data structure.

**Comment by lars-sh** [comment]
@PVince81 that's absolutely right, though I'm not an ownCloud developer nor aware of its Framework, so that's just a first fix.

**Comment by socrat3000** [comment]
Hi Guys,
I think I am having the same issue after upgrading from 9.0.11 to 10.0.4

This is the error I receive when running occ scan:

https://gist.github.com/socrat3000/e9ada76a85c03d6f8f0637c141d43106

and when I run the query by @PVince81 , I get the following result:

https://gist.github.com/socrat3000/94682f120b485a8466872ef378b9e172

Any ideas how I can fix this?

**Comment by socrat3000** [comment]
And this fix: https://github.com/owncloud/core/pull/28080/files is already there, but not resolving the issue.

**Comment by PVince81** [comment]
@socrat3000 I don't see anything wrong with the result yet. Can you also do a `select * from oc_share where id=(...)` and put all the parents from the last result in there ?

**Comment by socrat3000** [comment]
There you go:

https://gist.github.com/socrat3000/3b461b5616ea12e5ce4bff9346559f72

**Comment by socrat3000** [comment]
By the way, the account with the problem is **8D0D8BA8-DF3B-44FC-BEEA-25C605E57F88**

**Comment by PVince81** [comment]
Ok I see, so this user has two sub-entries instead of one. You could simply delete the oc_share entry with id 334.

I'll reopen this ticket so we can provide a repair step that detects this scenario and automatically deletes duplicates.

**Comment by socrat3000** [comment]
334? I don't get it

**Comment by PVince81** [comment]
```
| 333 |          2 | 8D0D8BA8-DF3B-44FC-BEEA-25C605E57F88 | 835D426E-3E43-43FA-AE3C-BF79CBC65AB2 |    332 | folder    | 69188       | NULL        |       69188 | /Templates (2)                                        |          31 | 1506601448 |        0 | NULL       | NULL  |         0 | NULL          | NULL       |
| 334 |          2 | 8D0D8BA8-DF3B-44FC-BEEA-25C605E57F88 | 835D426E-3E43-43FA-AE3C-BF79CBC65AB2 |    332 | folder    | 69188       | NULL        |       69188 | /Templates (2)                                        |          31 | 1506601448 |        0 | NULL       | NULL  |         0 | NULL          | NULL       |
```

These two rows are identical except for the share id. This is the problem, so delete the second one with id 334.

**Comment by socrat3000** [comment]
ah I get it.

So, you mean I should run this statement?

delete from oc_share where id=334

**Comment by PVince81** [comment]
Yes.

Now the reason why you have duplicates remains a mystery and is likely not reproducible easily.
Possible cause could be a race condition where two code paths inserted the same entry from two different places at the same time. I'd expect the DB transaction to prevent that though.

**Comment by socrat3000** [comment]
It's now working, thanks a lot.

Will ask the user to try to login again, because this issue was preventing him from logging in.

Will update you with the result.

**Comment by socrat3000** [comment]
User was able to login, thanks a million.

**Comment by p-thurner** [comment]
I am experiencing the same problem after upgrading to

```
www-data@cloud:~/owncloud$ php occ --version
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
ownCloud 10.0.4
```

I tried `repair` but its failing here:

```
www-data@cloud:~/owncloud$ php occ maintenance:repair --include-expensive
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
 - Repair mime types
 - Detect file cache entries with path that does not match parent-child relationships
     - WARNING: The file cache contains entries where the parent id does not point to any existing entry for the following storage numeric ids: 4
     - WARNING: Please run `occ files:scan --all --repair` to repair all affected storages
 - Generate ETags for file where no ETag is present.
     - ETags have been fixed for 0 files/folders.
 - Clean tags and favorites
     - 0 tags of deleted users have been removed.
     - 0 tags for delete files have been removed.
     - 0 tag entries for deleted tags have been removed.
     - 0 tags with no entries have been removed.
 - Drop old database tables
 28/28 [============================] 100%
 - Drop old background jobs
 - Remove getetag entries in properties table
     - Removed 0 unneeded "{DAV:}getetag" entries from properties table.
 - Repair outdated OCS IDs
 - Repair invalid shares
 - Remove old share propagation app entries
 - Move user avatars outside the homes to the new location
  52/253 [=====>----------------------]  20%
                                            
  [OC\Share20\Exception\ProviderException]  
  Parent of share should be unique          
                                            

maintenance:repair [--include-expensive]
```

Sadly the gists above expired, making it harder to follow this thread. Also I don't fully understand what @PVince81  means with "I suggest you check select * from oc_share where share_type=2 order by id.
These are sub-entries for each recipients. The parent share is the one where the "parent" column points to the parent share id. (select * from oc_share where id=$parent, replace $parent with the value from the column)". Can you elaborate on that? I'm somewhat new to owncloud.

**Comment by p-thurner** [comment]
As recommended by IRC I opened an issue here too: https://central.owncloud.org/t/upgrade-to-10-0-4-creates-error-providerexception-parent-of-share-should-be-unique/11321

**Comment by PVince81** [comment]
@p-thurner run the queries on your database:
- `select * from oc_share where share_type=2 order by id`
- `select * from oc_share where id=$parent,` and replace $parent with the value from the "parent" column from the previous query results

**Comment by p-thurner** [comment]
Thanks for your fast reply! The first statement outputs some 100s of lines, each line with a different `parent` id. How do I determine which parent ID I'm looking for @PVince81 ?

**Comment by p-thurner** [comment]
No, I dont know which recipient is affected (also I didn't know I was looking for that from the info I got so far from the error messages / logs). How would I determine which recipient is affected?

**Comment by PVince81** [comment]
You're right, sorry. I didn't read your report properly.

I tried to reproduce the case locally by manually creating a duplicate in the database. The error happens whenever there are two sub-share-entries for the same recipient when only one should exist.

Can you try running this query:
`select parent, count(*) from oc_share where share_type=2 group by parent, share_with having count(*) > 1;`

This should give you a list of possible duplicates. The "parent" column is the share id of the broken shares.

Once we have a value from there, plug it here: `select * from oc_shares where parent=$shareId order by share_with` and replace $shareId with the share id from above. You should then see two rows with the same recipient.

**Comment by p-thurner** [comment]
Returns this:

```
MariaDB [owncloud]> select parent, count(*) from oc_share where share_type=2 group by parent, share_with having count(*) > 1;
+--------+----------+
| parent | count(*) |
+--------+----------+
|   4887 |        2 |
|   5450 |        3 |
|   6726 |        2 |
|   6969 |        2 |
|   7126 |        2 |
|   7297 |        2 |
|   7297 |        2 |
+--------+----------+
7 rows in set (0.00 sec)
```

I should then run sth like this? (note oc_share, not oc_shareS) This gives me:
```
MariaDB [owncloud]> select * from oc_share where parent=4887 order by share_with;
+------+------------+------------+-----------+--------+-----------+-------------+----------------+-------------+----------------------------------------+-------------+------------+----------+------------+-------+-----------+---------------+------------+
| id   | share_type | share_with | uid_owner | parent | item_type | item_source | item_target    | file_source | file_target                            | permissions | stime      | accepted | expiration | token | mail_send | uid_initiator | share_name |
+------+------------+------------+-----------+--------+-----------+-------------+----------------+-------------+----------------------------------------+-------------+------------+----------+------------+-------+-----------+---------------+------------+
| 5563 |          2 | Oudjtiov   | MrFoobar |   4887 | file      | 204168      | /Shared/204168 |      204168 | /Shared/Kidoxmatik und Dutimik (2).pptx |          19 | 1478250020 |        0 | NULL       | NULL  |         0 | NULL          | NULL       |
| 6452 |          2 | Adfsafsaff | MrFoobar |   4887 | file      | 204168      | NULL           |      204168 | /Shared/Kidoxmatik und Dutimik (2).pptx |          19 | 1478250020 |        0 | NULL       | NULL  |         0 | MrFoobar     | NULL       |
| 6424 |          2 | Kudutiisdf | MrFoobar |   4887 | file      | 204168      | NULL           |      204168 | /Shared/Kidoxmatik und Dutimik (2).pptx |          19 | 1478250020 |        0 | NULL       | NULL  |         0 | MrFoobar     | NULL       |
| 6429 |          2 | Kditpx     | MrFoobar |   4887 | file      | 204168      | NULL           |      204168 | /Kidoxmatik und Dutimik (2).pptx        |          19 | 1478250020 |        0 | NULL       | NULL  |         0 | MrFoobar     | NULL       |
| 5562 |          2 | Kdut       | MrFoobar |   4887 | file      | 204168      | /Shared/204168 |      204168 | /Shared/Kidoxmatik und Dutimik (2).pptx |          19 | 1478250020 |        0 | NULL       | NULL  |         0 | NULL          | NULL       |
| 5560 |          2 | Blafo      | MrFoobar |   4887 | file      | 204168      | /Shared/204168 |      204168 | /Shared/Kidoxmatik und Dutimik (2).pptx |          19 | 1478250020 |        0 | NULL       | NULL  |         0 | NULL          | NULL       |
| 5561 |          2 | Blafo      | MrFoobar |   4887 | file      | 204168      | /Shared/204168 |      204168 | /Shared/Kidoxmatik und Dutimik (2).pptx |          19 | 1478250020 |        0 | NULL       | NULL  |         0 | NULL          | NULL       |
| 6498 |          2 | Fooba      | MrFoobar |   4887 | file      | 204168      | NULL           |      204168 | /Shared/Kidoxmatik und Dutimik (2).pptx |          19 | 1478250020 |        0 | NULL       | NULL  |         0 | MrFoobar     | NULL       |
+------+------------+------------+-----------+--------+-----------+-------------+----------------+-------------+----------------------------------------+-------------+------------+----------+------------+-------+-----------+---------------+------------+
8 rows in set (0.00 sec)
```

**Comment by PVince81** [comment]
Yes. See how the last result has "Blafo" twice. Delete *one* of both entries.

You'll need to repeat the process for every of the 7 results above. This is to get you unstuck.

Now seeing that more and more people are having this problem, I think we should work on writing a repair step that will clean this up before an upgrade.

**Comment by p-thurner** [comment]
So sth like this for my example?

```
DELETE FROM oc_share where id='5561';
```

**Comment by PVince81** [comment]
@p-thurner yes. Make sure you have a backup of the database first.

**Comment by p-thurner** [comment]
@PVince81  thanks again! :) That did the trick. I can now run a
```
www-data@cloud:~/owncloud$ php occ maintenance:repair
www-data@cloud:~/owncloud$ php occ upgrade
www-data@cloud:~/owncloud$ php occ maintenance:repair
www-data@cloud:~/owncloud$ php occ maintenance:mode --off
```

And the WebUI / everything else is working again. Thumbs up for  good support from the developers :) :1st_place_medal:

**Comment by PVince81** [comment]
Thanks for confirming!

**Comment by felixboehm** [comment]
Thanks @PVince81 for rising priority.

**Comment by PVince81** [comment]
Steps to reproduce manually and also illustrate the sub-share feature:

1. Create three users user1, user2, user3
1. Add all three to a group "group1"
1. Login as admin
1. Create a folder "test"
1. Share "test" with "group1"
1. Login as "user1"
1. Delete the received "test" (unshare from self)
1. Login as "user2"
1. Rename "test" to "test_mine"
1. Login as "user3"
1. Rename "test" to "test_mine"
1. Look at `oc_share` contents: you should see one main share to "group1" and three subshares: user1 has a subshare with permission 0 (opted-out), and both user2 and user3 have a subshare with the target folder.
1. Now rename "user3" to "user2" in the subshare entry's "share_with" column. This will make the third subshare a duplicate of the one from "user2"
1. Try listing the files over web UI or Webdav

You'll get an entry in the log with "OC\Share20\Exception\ProviderException: Parent of share should be unique".

To fix this, the goal is to implement a repair step that will select such entries. See https://github.com/owncloud/core/issues/27990#issuecomment-357683303 for some query ideas, beware as they might be expensive. Then if duplicates were found, delete them and keep the entry with the smallest share id from the duplicates.

Add a unit test that inserts such entries, runs the repair step, then checks that the duplicates are gone.

@sharidas let me know if you have further questions

**Comment by PVince81** [comment]
repair step implemented, closing
