### ISSUE TITLE
User backends can't prevent data deletion

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#28012]
### Steps to reproduce
1. Install user_ldap and setup a LDAP connection
2. Try to delete an existing LDAP user

### Expected behaviour
The user can't be deleted and the data remains. An error is thrown.

### Actual behaviour
The data for the user is deleted (the user itself isn't removed from LDAP because is considered a read-only system). This is a different behaviour we had for previous versions.

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.2RC1

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** tarball

@DeepDiver1975 please confirm the expected behaviour.

**Comment by jvillafanez** [comment]
related to https://github.com/owncloud/core/pull/28008

**Comment by PVince81** [comment]
severity?

**Comment by DeepDiver1975** [comment]
the behavior did change in many aspects with the introduction of the accounts table.
yes - a ldap user is the same as a saml user as a user in the database as a ftp user ......

If you delete a user ACCOUNT - it is gone

yes - this is a regression compared to the nightmare of ldap handing we did have in the past
no - nothing to fix from - it is good to have consistent behavior all over the place

**Comment by PVince81** [comment]
@DeepDiver1975 @jvillafanez close, then ?

**Comment by jvillafanez** [comment]
Vote for close then. Nothing to do if we're going to keep the new behaviour.
