### ISSUE TITLE
Using Microsoft.DBforMySQL/servers on Azure (new Mysql PaaS from Microsoft)

### ISSUE THREAD

**Issue by przemas75** [owncloud/core#28010]
### Steps to reproduce
1. Installation process, for simplicity SSL enforcing on Azure was disabled.
2.
3.

### Expected behaviour
Installation completed

### Actual behaviour
During manual installation, connection string probably is not supported by Azure. They say it should be something like:
`$con=mysqli_init(); mysqli_ssl_set($con, NULL, NULL, {ca-cert filename}, NULL, NULL); mysqli_real_connect($con, "yourserver.mysql.database.azure.com", "mysqladmin@yourserver", {your_password}, {your_database}, 3306);`
The error i got:

```
sudo -u www-data php -e /var/www/html/occ maintenance:install --database "mysql" --database-name "owncloud" --database-host "yourserver.mysql.database.azure.com" --database-user "mysqladmin@yourserver"  --database-table-prefix "ocvm_" --admin-user "ocadmin" --admin-pass "mypass" --data-dir "/var/owncloud_files" --no-interaction --database-pass "mysqlpass"
ownCloud is not installed - only a limited number of commands are available
Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2001] The connection string may not be right. Please visit portal for references.
 ->
```

Interesting thing is, when  i manually import a database, owncloud works fine.

### Server configuration
**Operating system**:
Ubuntu 16.04 on Azure
**Web server:**
2.4.18-2ubuntu3.2
**Database:**
Microsoft.DBforMySQL/servers  PaaS from Microsoft
**PHP version:**
v7.0.15-0ubuntu0.16.04.4
**ownCloud version:** (see ownCloud admin page)
9.1.4-1.1
**Updated from an older ownCloud or fresh install:**
No, fresh install
**Where did you install ownCloud from:**
deb http://download.owncloud.org/download/repositories/9.1.4/Ubuntu_16.04/ /

**Comment by przemas75** [comment]
Hello,
I think I found the root cause of this problem. This is not connection string issue I thought initially.
The problem is with some privileges not set (we can do this with user root on local machine, but once i have used different used with similar settings/privileges like i have at Azure it failed).
Having the “cause” it was easier to search for a fix.
https://github.com/owncloud/core/pull/25485

I have manually edited MySQL.php (not so many changes) and:

root@vmazure:/var/www/html/lib/private/Setup# sudo -u www-data php  /var/www/html/occ maintenance:install --database "mysql" --database-name="owncloud" --database-host="mysqlserverowc.mysql.database.azure.com" --database-user="mysqladmin@mysqlserverowc" --database-pass="xxxxx"  --admin-user="someuser" --admin-pass="somepass" --data-dir="/var/oc"
ownCloud is not installed - only a limited number of commands are available
ownCloud was successfully installed
root@testnyj:/var/www/html/lib/private/Setup#

Appreciate if it would be in 9.1 version.... (i have tried 9.1.4 and 9.1.6)

**Comment by przemas75** [comment]
I guess, i was too happy when it worked, but finally i found it needs initial config/config.php before installation step, that looks like:
`<?php
$CONFIG = array (
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbhost' => 'ourmysqlserver.mysql.database.azure.com',
  'dbuser' => 'mysqladmin@ourmysqlserver',
);`
dbhost and dbuser is taken from the mysql endpoint in azure portal (settings -> connections strings).

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/28138 was already merged
