### ISSUE TITLE
updates.owncloud.com SSL cert has expired

### ISSUE THREAD

**Issue by Micdu70** [owncloud/core#28024]
Issue for updating via "Updater" app:

"https://updates.owncloud.com/" => SSL certificate problem: certificate has expired.

SSL Labs link: https://dev.ssllabs.com/ssltest/analyze.html?d=updates.owncloud.com&latest

**Comment by DeepDiver1975** [comment]
@tboerger

**Comment by mrlinux1** [comment]
@DeepDiver1975 :

Fixed.
