### ISSUE TITLE
Updating 10.0.0 to 10.0.1

### ISSUE THREAD

**Issue by Compstuff** [owncloud/core#28027]
```
OC\RepairException: Upgrade is not possible

        Repair warning: Exception
        Repair warning: Signature could not get checked. Please contact the app developer and check your admin screen.
        Repair warning: GuzzleHttp\Exception\RequestException
        Repair warning: cURL error 23: Failed writing body (0 != 5)
        Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
        Repair warning: please install app manually with tarball or disable them with: occ app:disable files_texteditor occ app:disable gallery

Preparing update
Set log level to debug
Turned on maintenance mode
Repair warning: Exception
Repair warning: Signature could not get checked. Please contact the app developer and check your admin screen.
Repair warning: GuzzleHttp\Exception\RequestException
Repair warning: cURL error 23: Failed writing body (0 != 5)
Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Repair warning: please install app manually with tarball or disable them with: occ app:disable files_texteditor occ app:disable gallery
OC\RepairException: Upgrade is not possible
```

### Steps to reproduce
1. 1st upgrade attempt

### Expected behaviour
Should have upgraded with no erors

### Actual behaviour
Failed to upgrade

### Server configuration
**Operating system**:

**Web server:**
Web server

    cpsrvd 11.64.0.24
    Database client version: libmysql - 5.1.73
    PHP extension: mysqli curl mbstring
    PHP version: 5.6.30

**Database:**
Database server

    Server: Localhost via UNIX socket
    Server type: MariaDB
    Server version: 10.1.23-MariaDB - MariaDB Server
    Protocol version: 10
    Server charset: UTF-8 Unicode (utf8)

**PHP version:**
phpMyAdmin
Version information: 4.6.6 
Current PHP version: 7.1.5

**ownCloud version:** (see ownCloud admin page)
10.0.0 to 10.0.1
**Updated from an older ownCloud or fresh install:**
10.0.0 to 10.0.1
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
<script src="https://gist.github.com/Compstuff/d7bca4c07b93ae9bc4bc40670456fb7f.js"></script>

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.
CANT FIND THIS
or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by Compstuff** [comment]
I did an entire error post... now I don't see any text here

**Comment by kdslkdsaldsal** [comment]
@Compstuff You probably need to re-do it as i don't think that it will appear again automatically. Make also sure that you're filling out the issue template shown when creating a new issue.

**Comment by PVince81** [comment]
here you go, the report reappears: you forgot to remove the initial `<!--`

**Comment by PVince81** [comment]
seems your instance have trouble connecting to the marketplace, not sure why... Guzzle errors.

Any clues ? @DeepDiver1975 @tomneedham @IljaN @VicDeo

**Comment by VicDeo** [comment]
```
CURLE_WRITE_ERROR (23)
An error occurred when writing received data to a local file, or an error was returned to libcurl from a write callback.
```


There are several reasons for that. Most common is a lack of space on a partition with `/tmp` or wherever curl stores it's temporary data.

In some cases it might also be related to encoding of the response body (it's not supported by the target system).

IIRC it happens between php-curl and libcurl

**Comment by PVince81** [comment]
So, environment issue not OC bug ?

**Comment by Compstuff** [comment]
All,

I apologize for me extremely delayed response on this but a personal issue came up which took precedence. I believe the problem was definitely caused by a lack of space during the upgrade and I have since increased the size to prevent this. We did a full restore on the entire system, increased the space and then did the update with complete success. Thank You

**Comment by PVince81** [comment]
Thanks for the info
