### ISSUE TITLE
contact import creates duplicates instead of updating existing contacts

### ISSUE THREAD

**Issue by cboltz** [owncloud/core#28026]
When I import a contact (vcard) in the web interface, owncloud always creates new contacts instead of updating the existing contact with the same UID.

An easy way to test this is to export a contact as vcard, and then import exactly that file again

### Steps to reproduce
1. login to the web interface
2. go to the "contacts" section
3. click "settings" in the bottom-left
4. click the "download contacts" button and save the vcf file
5. click the "import" button and upload the vcf file you downloaded in step 4

### Expected behaviour
The existing contacts should be updated (or, with the above reproducer, not updated because there were no changes). The definition of "existing contact" is probably "same UID in the vcf file"

### Actual behaviour
Duplicate contacts get created

### Server configuration
* owncloud 9.1.4
* fresh install from tarball
* skipping the other details which are likely irrelevant - if you really need them, please ask ;-)

CC @ccboltz

**Comment by kdslkdsaldsal** [comment]
Ref: https://github.com/owncloud/contacts/issues/588

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
