### ISSUE TITLE
Group Admins can not save Mailadresses after upgrade OC9->OC10

### ISSUE THREAD

**Issue by bkluszynski** [owncloud/core#28035]
### Steps to reproduce
1. Create A Group e.g. testgroup
2. Create A Testuser e.g. testuser
3. Assign the user to the group and make him/her :) GroupAdmin
4. Login with the new user "testuser"
5. Create a new User within the group and try to setup the e-mail address

### Expected behaviour
E-Mail-Adress should be saved.

### Actual behaviour
It shows the "loading-circle". (I already tried to wait for an hour. Its not working)

![e-mail-loading](https://cloud.githubusercontent.com/assets/29060045/26578486/59b9ad68-4530-11e7-9162-d67e38caf3dd.png)

### Server configuration
Debian 8 -> All Updates

**Web server:**
Apache 2.4

**Database:**
MySQL 5.5

**PHP version:**
PHP5 (newest version)

**ownCloud version:** (see ownCloud admin page)

![version](https://cloud.githubusercontent.com/assets/29060045/26578481/53b3c66a-4530-11e7-9945-933396aebabf.png)

**Updated from an older ownCloud or fresh install:**

9.1.5

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

{
    "system": {
        "updatechecker": false,
        "instanceid": "oc46p7ps7t6j",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "kerncloud.e-kern.com",
            "192.168.0.86"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/kerncloud.e-kern.com\/owncloud",
        "dbtype": "mysql",
        "version": "10.0.0.12",
        "dbname": "didmP1984",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "kerncloud",
        "mail_smtpmode": "smtp",
        "mail_domain": "e-kern.com",
        "mail_smtphost": "kernexchange",
        "mail_smtpport": "25",
        "trashbin_retention_obligation": "auto, 2",
        "loglevel": 3,
        "maintenance": false
    }
}

**List of activated apps:**
Enabled:
  - activity: 2.3.3
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.8
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - example-theme
  - external
  - files_antivirus
  - user_external

#### LDAP configuration (delete this part if not used)
No LDAP

### Client configuration
**Browser:**
All

**Operating system:**
Windows

**Comment by bkluszynski** [comment]
ah.. one more Fact.

With Administrator rights it works well. but not with the "group-Admin" rights.

**Comment by kdslkdsaldsal** [comment]
> "version": "10.0.0.12",

Please update to the latest stable version first before reporting any issues: https://owncloud.org/changelog/#latest10.0

**Comment by PVince81** [comment]
Confirmed bug on 10.0.2.
Getting a 403 in the network console.

**Comment by PVince81** [comment]
works fine on stable9.1, so this is a regression

**Comment by PVince81** [comment]
Regression introduced through 8880ea3a31f453c4c2eb008e91965f0b08a21aab in PR https://github.com/owncloud/core/pull/27277.

@imujjwal96 mind having a look ? Seems you older PR missed to add a check to allow group admins to change any of the member's email address directly. (no confirmation)

**Comment by PVince81** [comment]
@sharidas can you take over ?
