### ISSUE TITLE
error updating 9.1.5 to 10.0.1

### ISSUE THREAD

**Issue by stephengraf** [owncloud/core#28041]
I was testing the update on my production test system and to my surprise, the manual procedure that I have used so many times failed. I then set up a minimal test system to diagnose as there was little info to go on.

### Steps to reproduce
1. Loaded a minimal 9.1.4 system.
2. Updated successfully to 9.1.5.
3. Tried to update to 10.0.1 and failed.

### Expected behaviour
Expected the update to 10.0.1 to be successful as was the update to 9.1.5.

### Actual behaviour
When the update was started on the web, the page indicated that only dav was going to be updated.  Note that the logs showed that the php script for this page did not finish properly. When I clicked on start update, a few seconds transpired and an error message was presented.  When I clicked to see the detailed logs all that was presented is "An error occurred."  There were no additional entires in any logs.

### Server configuration
OpenBSD 6.1

httpd in chroot

sqlite3

php 5.6

Started with fresh install of 9.1.4.
Updated successfully to 9.1.5.
Failed update to 10.0.1. 

Downloaded all versions from owncloud.org.

Going back to working 9.1.5 the integriy check reported:
No errors have been found.

[config_report_20170530.txt](https://github.com/owncloud/core/files/1039724/config_report_20170530.txt)

Only the apps on the basic install were included.

### Client configuration
Opera

Windows 10

### Logs
[test console log.txt](https://github.com/owncloud/core/files/1039732/test.console.log.txt)
![after detailed logs](https://cloud.githubusercontent.com/assets/9615360/26605515/397a768c-4543-11e7-9add-454f9624193f.JPG)
![start 10 0 1](https://cloud.githubusercontent.com/assets/9615360/26605518/40522036-4543-11e7-9664-537fd319a9c9.JPG)

#### ownCloud log (data/owncloud.log)
```
In test_console log.txt.
```

There was nothing reported in the web server error log or the php log.

**Comment by andreaphsz** [comment]
same for me :-(

**Comment by PVince81** [comment]
The screenshot displays the Nextcloud logo. Did you update from a Nextcloud instance ?

How did you upgrade ? Did you properly delete all the old source code ?

**Comment by webgobe** [comment]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_account_terms (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, account_id BIGINT UNSIGNED NOT NULL, term VARCHAR(256) NOT NULL, INDEX account_id_index (account_id), INDEX term_index (term), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by DeepDiver1975** [comment]
> Similar setup, upgrade failed with this error message:
> Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_account_terms (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, account_id BIGINT UNSIGNED NOT NULL, term VARCHAR(256) NOT NULL, INDEX account_id_index (account_id), INDEX term_index (term), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

we are working on a fix https://github.com/owncloud/core/pull/28019

**Comment by stephengraf** [comment]
Sorry about the screen shots. I was doing the same tests with nextcloud with the same results.  I also tested going from 10,0,0 to 10.0.1. The 10.0.0 install when fine but the upgrade failed with the same error conditions.
The upgrade procedure is detailed in the console log attached to the original submission.  I did a mv from owncloud to owncloud-whatever to get rid of the old code.  Then I did a cp of the config.php file and data directory.
When I did the original attempt on my production test system, the environment was mariadb and nginx. The described testing was sqlite and httpd for simplicity.

**Comment by stephengraf** [comment]
The am not sure how I got nextcloud logos on owncloud pages.  The screen shots were from testing a while ago and I should have recaptured them for this submission.  To be sure I redid the test updating from 9.1.5 to 10.0.1 and the pages are correct with the owncloud logos.

I do not understand what the error message in the log is trying to point out.  Does anyone have any suggestions as to where to look for more clues?

**Comment by andreaphsz** [comment]
owncloud.log says:
<code>
{"reqId":"WS@-8SwJdm42TT8Rl-Ug-gAAAAA","level":0,"time":"2017-06-01T09:19:13+02:00","remoteAddr":"xxx.xxx.xxx.xx","user":"--","app":"core","method":"GET","url":"\/test\/owncloud\/core\/ajax\/update.php?requesttoken=NFsbGQNXHhsxcE5OBHVXFzAdHS8EVktiBCknJQ0wJTI%3D%3An6NkB95UzB6xJD88ynqGP9s%2FEcHmOysEgCLNc8Hm5gI%3D","message":"starting upgrade from 10.0.0.12 to 10.0.2.1"}
</code>

for server log see attachment.

![bildschirmfoto 2017-06-01 um 09 22 09](https://cloud.githubusercontent.com/assets/3206936/26668975/58128d22-46ac-11e7-9d68-da26a8b922a3.png)

**Comment by DavidMarec** [comment]
Already reported here: https://central.owncloud.org/t/failed-to-upgrade-to-oc-10-0-1/7915

As I understand the issue, the 'term' field stores too many bytes
- VARCHAR(256) * 3  > 767   : as mysql uses 3 bytes to store utf8 chars -
to be used as a key index !?

(255 seems to be ok ) 

the table definition to be found into  'core/Migrations/Version20170516100103.php'

**Comment by andreaphsz** [comment]
my error seems not to be related to #28019. my error is not a "too many bytes" issue.

**Comment by andreaphsz** [comment]
neither owncloud.log nor the server log gives me more information about the error. is there a way to debug the code in an easy way?

**Comment by stephengraf** [comment]
@PVince81 

I am not sure that the error I am looking at is connected to the term database problem.

I redid the testing starting with base 9.1.5, updated successfully to 9.1.6.  I did the update to 10.0.2 with the term patch in place, but encountered the same error as reported previously.  See the attached file that has a console log and owncloud and web server logs.

[test update with patch.txt](https://github.com/owncloud/core/files/1048674/test.update.with.patch.txt)

Note that the owncloud error occurs after starting ownclould on the web and before clicking on "Start update".

There are no php or sql errors reported as it would seem owncloud is objecting to something and bails out.  The owncloud error message is below. Is it possible to shed some light on what owncloud is objecting to?

``{"reqId":"UsabuwbXWEcRWEZsZsz6","level":3,"time":"2017-06-02T11:22:16-07:00","remoteAddr":"50.92.162.251","user":"--","app":"index","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=abb2a004101a24f9a0049f95250752c7","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(121): OC_App::loadApp('dav')\\n#1 \\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(145): OC_App::loadApps(Array)\\n#2 \\\/owncloud\\\/lib\\\/base.php(917): OC_Util::setupFS()\\n#3 \\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":162}"}
