### ISSUE TITLE
Files app: Files of unknown filenamesuffix/ mimetype are tried to open instead of downloading them

### ISSUE THREAD

**Issue by TDannhauer** [owncloud/core#28048]
### Steps to reproduce
1. Create a random binary file with an unkown file suffix called "testfile.unknownsuffix"
2. Upload it to OC via the Web interface
3. Try to download the file by clicking on the displayed filename

### Expected behaviour
Browser should open the download dialog to save the file.
Any file having a mimetype/filename sussix without a known corresponding display app should be downloadable by clicking on the filename.

### Actual behaviour

OC tries to open the file instead of opening the file-save dialog of the browser. As it fails for custom binary formats, OC shows a message dialog with the following error message:
"An error occurred!

This file is too big to be opened. Please download the file instead."

After confirming the error message, the size of the 10MB file is displayed as "< 1KB" and the last modification date is replaced by a single question mark.

### Server configuration
**Operating system**:

**Web server:**
Apache 2.4.25

**Database:**
PSQL 9.6

**PHP version:**
7.0.19

**ownCloud version:** (see ownCloud admin page)
10.0.1.5

**Updated from an older ownCloud or fresh install:**
latest 9.x.y release

**Where did you install ownCloud from:**
Server package from the OC website

**Signing status (ownCloud 9.0 and above):**

```
"No errors have been found."
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc87896c1670",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "1": "owncloud.trusted.domain.tld"
        },
        "datadirectory": "\/extradata\/owncloud",
        "dbtype": "pgsql",
        "version": "10.0.1.5",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": 4,
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",
        "mail_domain": "mail.trusted.domain.tld",
        "mail_smtphost": "smtp.trusted.domain.tld",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "PLAIN",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "overwritehost": "owncloud.trusted.domain.tld",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "mail_smtpsecure": "tls",
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "asset-pipeline.enabled": true
    }
}

```

**List of activated apps:**

```
  - activity: 2.3.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.9
  - external: true
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.0
  - files_texteditor: 2.2
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.1.0
  - notifications: 0.3.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - files_antivirus
  - provisioning_api
  - theme-example
  - user_external

```

**Are you using external storage, if yes which one:** None

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:**
Current Firefox release

**Operating system:**
Win 10 (up to date)

#### Web server error log
```
None
```

#### ownCloud log (data/owncloud.log)
```
None
```

#### Browser log
```
None
```

**Comment by TDannhauer** [comment]
I registered my custom files as mimetypes with according filetype-images and the behaviour is fine again: OC does not longer try to open the clicked file in the editor but provides it as a download.

However, it is not a good idea to establish a default behaviour of opening files in the Webeditor for unkown file endings or MIME types.  

Instead, only well known endings should be opend by teh correct OC app aND all unkown files should be handled as downloads.

**Comment by PVince81** [comment]
Works for me on 10.0.2.

Did you refresh the browser page after replacing the suffix ? There is a bug that the mimetype detection isn't redone on the JS side whenever a file extension is renamed. So the old handler (if the old file was ".txt") is still called.

**Comment by TDannhauer** [comment]
I did not rename a file at all.

1. Create a file called testfile.unknownsuffix on your desktop.
2. Upload it into OC
3. Try to download it by clicking in the name.

Expected behaviour: File will be downloaded
Actual behaviour: OC tries to open the file with the OC text editor -> This makes no sense in binary files. Only .txt files should be opened by the text editor.

**Comment by PVince81** [comment]
@TDannhauer can you inspect the "tr" element in the browser console and check the value of "data-mime" for the file in question ? I'd expect it to be "application/octet-stream" which shouldn't trigger the text editor.

**Comment by TDannhauer** [comment]
@PVince81 The tr is defined as this:

<tr class="appear" data-id="758653" data-type="file" data-file="testfile.unkownsuffix" data-mime="application/octet-stream" data-mtime="0" data-etag="758653" data-permissions="27" data-path="/SUBFOLDER" data-tags="" data-share-permissions="19">

**Comment by PVince81** [comment]
Uh oh: https://github.com/owncloud/files_texteditor/blob/master/js/editor.js#L250

@tomneedham do you know why "application/octet-stream" is in the list of mime types for the text editor ?

I seem to remember people complaining that they couldn't open their "text files without extension", which might be why. ownCloud detects mime type only based on file extension so it's not possible to find whether a file without extension is really a text file or not.

**Comment by TDannhauer** [comment]
@PVince Ah that explains everything and is also a nice quick fix. 

I agree that 'application/octet-stream' is not aproriate for a text editor :)

**Comment by tomneedham** [comment]
> @tomneedham do you know why "application/octet-stream" is in the list of mime types for the text editor ?

seems it went in here: https://github.com/owncloud/files_texteditor/pull/190

**Comment by TDannhauer** [comment]
What is the status of this bug? is it fixed in 10.0.2 ?

Thanks, Torben

**Comment by PVince81** [comment]
I suggest reverting it. While having application/octet-stream might help making htaccess editable, it breaks a lot more stuff. A better solution would be to have htaccess have its own mime type...

**Comment by TDannhauer** [comment]
@PVince81 I agree but currently I do not have spare time to do it. can you revert it?

Thanks,
Torben

**Comment by PVince81** [comment]
PR here by @tomneedham https://github.com/owncloud/files_texteditor/pull/200

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
I've submit the revert PR here https://github.com/owncloud/files_texteditor/pull/219

**Comment by PVince81** [comment]
from what I see the mime type is already gone
