### ISSUE TITLE
New Background image for 10.0.3

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#28045]
Hey Folks, 
its time to do some theming changes: We need a new login-page background image. 

Currently we have this:
https://github.com/owncloud/core/blob/master/core/img/background.jpg

Any suggestions?

**Comment by Kawohl** [comment]
https://central.owncloud.org/t/new-background-image-your-call/7927

**Comment by PVince81** [comment]
from what I see the image is already there ons table10, closing
