### ISSUE TITLE
New share link forgets "Allow editing" permissions

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#28057]
![screenflow](https://cloud.githubusercontent.com/assets/214010/26673908/d0d0fe80-46be-11e7-9c11-38f8ddc9c9f6.gif)

### Steps to reproduce
1. create a share link with edit permission, password and expiration date
2. open the new link again, and it has lost his edit permission
3. set edit permission again, then it's permanent

### Expected behaviour
"Allow editing" permissions should be permanent for new created share link

### Actual behaviour
New share link forgets "Allow editing" permissions

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7

**ownCloud version:** (see ownCloud admin page)
10.0.2

**Updated from an older ownCloud or fresh install:**
fresh install

### Client configuration
**Browser:**
Chrome 58

**Operating system:**
macOS 10.12.5 (Sierra)

**Comment by SamuAlfageme** [comment]
No password and expiration date in step 1 needed to reproduce. 

```
curl 'https://<server>/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json' 
 -H 'Content-Type: application/json' 
 -H 'OCS-APIREQUEST: true' 
 -H 'Content-Length: 76' 
[...]
```
With the following params:
```
{
   "expireDate":"",
   "permissions":15,
   "name":"3 link",
   "shareType":3,
   "path":"/3"
}
```
... is replied: 
```
{
   "ocs":{
      "meta":{
         "status":"ok",
         "statuscode":200,
         "message":null
      },
      "data":{
         "id":"9",
         "share_type":3,
         "uid_owner":"admin",
         "displayname_owner":"admin",
         "permissions":1,
         [...]
```

**Note the `"permissions":1`**

**Comment by PVince81** [comment]
Indeed, was able to reproduce this with only the permissions.

Seems to be a server side API issue.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/28060

**Comment by SamuAlfageme** [comment]
Tested the PR fix w/ different permission combinations and all requests were coherent with the response 👍
