### ISSUE TITLE
Add cli command to know the account status

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#28056]
The command will show all accounts (with offset + limit), or only one specified by the uid of the user. An option can be added to show only disabled accounts or provide other kind fo filters (to be decided)

It will show several account information, specially the last time the user logged in and if the account is disabled or not.

Note that the command will handle accounts, not users.

Follow up of https://github.com/owncloud/user_ldap/issues/97

**Comment by haukman** [comment]
@jvillafanez any update on this?

From my point of view this is very important for large installation (+1000 users) - just imagine you run the user:sync and choose to disable the users that are removed from the owncloud AD group. You will end up with a bunch of disabled users and over time and you don´t have an options to get a list of them to write a script or do some other automation to migrate their data or finally delete their accounts. 

In the past we could do some automation with the information stored in the user-remnants table, but this command was removed from occ (at least this is my understanding)?!

Please comment: @hodyroff @pmaier1 
fyi: @cdamken

**Comment by DeepDiver1975** [comment]
> @jvillafanez any update on this?

not scheduled - nobody is working on this - needs pm decision @hodyroff @pmaier1

**Comment by pmaier1** [comment]
Also needed for the guests app cleanup https://github.com/owncloud/guests/issues/110. We should schedule this in one of the next core versions. @PVince81

**Comment by PVince81** [comment]
I think @butonic worked on something related for disabled users: https://github.com/owncloud/core/pull/31115
