### ISSUE TITLE
Standlone app signing tool

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#28058]
Because currently app developers need to have a valid ownCloud instance just to be able to run "occ integrity:sign-app". This doesn't integrate well with automated tools.

cc @DeepDiver1975

**Comment by DeepDiver1975** [comment]
starting point: https://github.com/DeepDiver1975/oc-signature

**Comment by bud-mo** [comment]
Follow

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
