### ISSUE TITLE
Internal server error after rename config.sample.php to sample.config.php

### ISSUE THREAD

**Issue by rmbleeker** [owncloud/core#28069]
### Steps to reproduce
1. Rename config.sample.php to sample.config.php
2. Open the owncloud page
3. Get internal server error page

### Expected behaviour
OwnCloud login page to show normally

### Actual behaviour
<img width="974" alt="screen shot 2017-06-02 at 14 02 19" src="https://cloud.githubusercontent.com/assets/4312801/26724954/3777d91e-479c-11e7-8ac2-83dd6c587e1a.png">

### Server configuration
**Operating system:** CentOS 7

**Web server:** Apache 2.4.18

**Database:** MariaDB 5.5.52

**PHP version:** 7.0.10

**ownCloud version:** 10.0.2.1

**Updated from an older ownCloud or fresh install:** update from older 10.0 version

**Where did you install ownCloud from:** https://download.owncloud.org/download/repositories/10.0/owncloud/

**Signing status (ownCloud 9.0 and above):** Unable to check

**The content of config/config.php:** Unable to generate a sanitized version, but the config hasn't changed in a month so I don't believe it's the issue here

**List of activated apps:** besides the default apps, user_ldap and twofactor_totp

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

**LDAP configuration:** has worked before on OwnCloud 9, was tested and working before this error occured

#### Web server error log
```
[Fri Jun 02 13:49:50.973021 2017] [:error] [pid 3524] [client 10.91.5.254:33068] {"reqId":"WTFQ3r1xcGZL4hTGrL7pzQAAAAI","level":3,"time":"June 02, 2017 13:49:50","remoteAddr":"xx.xx.xx.xx","user":"--","app":"index","method":"GET","url":"\\/store\\/apps\\/files\\/?dir=\\/&fileid=468","message":"Exception: {\\"Exception\\":\\"Error\\",\\"Message\\":\\"Call to a member function getUser() on null\\",\\"Code\\":0,\\"Trace\\":\\"#0 \\\\\\/var\\\\\\/www\\\\\\/html\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/Log.php(170): OC\\\\\\\\Log->log(3, 'session_name():...', Array)\\\\n#1 \\\\\\/var\\\\\\/www\\\\\\/html\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/Log\\\\\\/ErrorHandler.php(89): OC\\\\\\\\Log->error('session_name():...', Array)\\\\n#2 [internal function]: OC\\\\\\\\Log\\\\\\\\ErrorHandler::onError(2, 'session_name():...', '\\\\\\/var\\\\\\/www\\\\\\/html\\\\\\/o...', 45, Array)\\\\n#3 \\\\\\/var\\\\\\/www\\\\\\/html\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/Session\\\\\\/Internal.php(45): session_name('')\\\\n#4 \\\\\\/var\\\\\\/www\\\\\\/html\\\\\\/owncloud\\\\\\/lib\\\\\\/base.php(426): OC\\\\\\\\Session\\\\\\\\Internal->__construct('')\\\\n#5 \\\\\\/var\\\\\\/www\\\\\\/html\\\\\\/owncloud\\\\\\/lib\\\\\\/base.php(581): OC::initSession()\\\\n#6 \\\\\\/var\\\\\\/www\\\\\\/html\\\\\\/owncloud\\\\\\/lib\\\\\\/base.php(1003): OC::init()\\\\n#7 \\\\\\/var\\\\\\/www\\\\\\/html\\\\\\/owncloud\\\\\\/index.php(47): require_once('\\\\\\/var\\\\\\/www\\\\\\/html\\\\\\/o...')\\\\n#8 {main}\\",\\"File\\":\\"\\\\\\/var\\\\\\/www\\\\\\/html\\\\\\/owncloud\\\\\\/lib\\\\\\/private\\\\\\/Log.php\\",\\"Line\\":296}"}
[Fri Jun 02 13:49:50.978335 2017] [:error] [pid 3524] [client 10.91.5.254:33068] {"reqId":"WTFQ3r1xcGZL4hTGrL7pzQAAAAI","level":3,"time":"June 02, 2017 13:49:50","remoteAddr":"xx.xx.xx.xx","user":"--","app":"PHP","method":"GET","url":"\\/store\\/apps\\/files\\/?dir=\\/&fileid=468","message":"hash_equals(): Expected user_string to be a string, null given at \\/var\\/www\\/html\\/owncloud\\/lib\\/private\\/Log.php#288"}
```

#### occ command output
```
{"reqId":"D2sboCUR27IabIC6K1M8","level":3,"time":"June 02, 2017 14:17:25","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"hash_equals(): Expected user_string to be a string, null given at \/var\/www\/html\/owncloud\/lib\/private\/Log.php#288"}
An unhandled exception has been thrown:
Error: Call to a member function getUser() on null in /var/www/html/owncloud/lib/private/Log.php:296
Stack trace:
#0 /var/www/html/owncloud/lib/public/Util.php(157): OC\Log->log(3, 'User backend OC...', Array)
#1 /var/www/html/owncloud/lib/private/legacy/user.php(153): OCP\Util::writeLog('core', 'User backend OC...', 3)
#2 /var/www/html/owncloud/lib/base.php(655): OC_User::setupBackends()
#3 /var/www/html/owncloud/lib/base.php(1003): OC::init()
#4 /var/www/html/owncloud/console.php(57): require_once('/var/www/html/o...')
#5 /var/www/html/owncloud/occ(11): require_once('/var/www/html/o...')
#6 {main}{"reqId":"D2sboCUR27IabIC6K1M8","level":3,"time":"June 02, 2017 14:17:25","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"chmod(): No such file or directory at \/var\/www\/html\/owncloud\/lib\/private\/Log\/Owncloud.php#122"}
```

**ownCloud log:** Last entry is from before the error occured

**Comment by rmbleeker** [comment]
I had typed up this whole bug report when I realized the only change I had made was renaming the `config.sample.php` file. I tried a few variations and it seems as if OwnCloud throws an internal server error whenever the config file is renamed to `*.config.php`. Is there a specific reason for this?

**Comment by kdslkdsaldsal** [comment]
@rmbleeker Most likely related to:

> OwnCloud has a mechanism by which you can drop in extra configuration files alongside config.php. Any file whose name ends in config.php in the OC config dir will be used as a config file. This is implemented in readData() in lib/private/config.php.

-> https://github.com/owncloud/core/issues/10040

This is an older issue put that functionality still exists in current oC versions: https://github.com/owncloud/core/blob/v10.0.2/lib/private/Config.php#L186

**Comment by rmbleeker** [comment]
I'm not entirely sure why you would want to split your oC configuration into multiple files, but it sounds like it's by design and not a bug. Closing.

**Comment by kdslkdsaldsal** [comment]
I'm also wondering what the purpose of this functionality is, especially as it seems that it isn't documented at https://doc.owncloud.org
