### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by Pok-Pok** [owncloud/core#28079]
Failure to finalize update:
### Steps to reproduce
1. Execute upgrade from latest 9 to 10.0.2
2. Open the URL that I used before: https://server.fqdn/owncloud/
3. Get the message: 
--------------------------------------------------------------------------------

> ownCloud will be updated to version 10.0.2
> These apps will be updated:
> 
>     WebDAV (dav)
> 
> Please make sure that the database, the config folder and the data folder have been backed up before proceeding.
> To avoid timeouts with larger installations, you can instead run the following command from your installation directory:
> 
> ./occ upgrade

--------------------------------------------------------------------------------
4. Press the „Start update” button.

### Expected behaviour
Upgrade to be finalized

### Actual behaviour
The following result/log is produced: 

OC\RepairException: Upgrade is not possible

        Repair warning: Exception
        Repair warning: Archives of type application/octet-stream are not supported
        Repair warning: Exception
        Repair warning: Archives of type application/octet-stream are not supported
        Repair warning: Exception
        Repair warning: Archives of type application/octet-stream are not supported
        Repair warning: Exception
        Repair warning: Archives of type application/octet-stream are not supported
        Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
        Repair warning: please install app manually with tarball or disable them with: occ app:disable activity occ app:disable files_pdfviewer occ app:disable files_texteditor occ app:disable gallery

### Server configuration
Linux, Apache, MySQL, PHP 5.6, ownCloud 10.0.2, updated from an older ownCloud using Softaculous.

config/config.php:
```
<?php
$CONFIG = array (
  'instanceid' => '******',
  'passwordsalt' => '******',
  'secret' => '******',
  'trusted_domains' => 
  array (
    0 => '******',
  ),
  'datadirectory' => '******/ownclouddata',
  'overwrite.cli.url' => 'http://******/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.5.2',
  'dbname' => '******',
  'dbhost' => '******',
  'dbtableprefix' => 'oc_',
  'dbuser' => '******',
  'dbpassword' => '******',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
);
```

The problem is I do not have console access (this being a shared server in a hosting center) and whatever URL I access I just get the prompt to do the upgrade. Is there an easy way out of this?

**Comment by Pok-Pok** [comment]
The issue has been solved by „manually” (directly in the database) disabling the apps generating the fault.

**Comment by bartmans** [comment]
I also encountered this error. Manually set the offending apps to not enabled.

OC finished the upgrade, I can login to the market. Installing apps or updating the Market app leads to this erro in the webinterface: Archiefbestanden van type application/octet-stream niet ondersteund (
Archives of type application/octet-stream are not supported).

Now what?

**Comment by patrickjahns** [comment]
@bartmans 

Can you provide a list with the offending applications?

**Comment by bartmans** [comment]
I eventually solved this in cPanel 66.0.23 / Installatron. I looked at the PHP settings in cPanel and ticked the box for the extension 'intl'. 

This solved the issue. My hosting provider said they would give feedback to cPanel/Installatron that this dependency should be checked before upgrading to latest Owncloud. No idea if he did that.

Does that asnwer your question?

**Comment by kdslkdsaldsal** [comment]
Mhhh, the ``intl`` extension is only listed as "optional" at:

https://doc.owncloud.org/server/latest/admin_manual/installation/source_installation.html#optional

Looks like this is required then.

**Comment by bartmans** [comment]
Well n=1 (me) at the moment, but just tested it again. Without intl extension I can't install apps from the marketplace. With it, I can. So for upgrading/installing it looks like required IF you're using apps.

**Comment by kdslkdsaldsal** [comment]
@bartmans Created https://github.com/owncloud/core/issues/29247 for this to track if this extension should be a hard requirement.
