### ISSUE TITLE
Upgrade from 10.0.1 to 10.0.2 very slow

### ISSUE THREAD

**Issue by ekgermann** [owncloud/core#28075]
### Steps to reproduce
1.  Run occ upgrade
2.
3.

### Expected behaviour

Upgrade completes

### Actual behaviour

Apps are unknown after approximately 75 sec pause connecting to marketplace

[nginx@c7-owncloud1 owncloud-10.0.2]$ /usr/local/bin/php occ -vvv upgrade
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2017-06-02T15:51:51+00:00 Set log level to debug
2017-06-02T15:51:51+00:00 Repair step: Repair MySQL database engine
2017-06-02T15:51:51+00:00 Repair step: Repair MySQL collation
2017-06-02T15:51:51+00:00 Repair info: All tables already have the correct collation -> nothing to do
2017-06-02T15:51:51+00:00 Repair step: Repair SQLite autoincrement
2017-06-02T15:51:51+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2017-06-02T15:51:51+00:00 Repair info: lucene_status table does not exist -> nothing to do
2017-06-02T15:51:51+00:00 Repair step: Upgrade app code from the marketplace
2017-06-02T15:51:51+00:00 Repair info: Using market to update existing apps
2017-06-02T15:51:51+00:00 Repair info: Attempting to update the following existing compatible apps from market:
2017-06-02T15:51:51+00:00 Repair info: Fetching app from market: calendar
2017-06-02T15:53:08+00:00 Repair info:
2017-06-02T15:53:08+00:00 Repair info: Fetching app from market: comments
2017-06-02T15:54:23+00:00 Repair info: App (comments) is not known at the marketplace.
2017-06-02T15:54:23+00:00 Repair info: Fetching app from market: configreport
2017-06-02T15:55:39+00:00 Repair info: App (configreport) is not known at the marketplace.
2017-06-02T15:55:39+00:00 Repair info: Fetching app from market: dav
2017-06-02T15:56:55+00:00 Repair info: App (dav) is not known at the marketplace.
2017-06-02T15:56:55+00:00 Repair info: Fetching app from market: federatedfilesharing

I can ping marketplace so I don't believe it's a connectivity issue.  Consistent ~ 75sec pause for app then it isn't known.

ping marketplace.owncloud.com
PING pearl.owncloud.com (5.9.68.237) 56(84) bytes of data.
64 bytes from pearl.owncloud.com (5.9.68.237): icmp_seq=1 ttl=52 time=141 ms
^C
--- pearl.owncloud.com ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 141.498/141.498/141.498/0.000 ms

### Server configuration
**Operating system**:

Centos 7 (fully patched)

**Web server:**

nginx 1.13.0

**Database:**

mysql 5.7.18

**PHP version:**

7.1.5

**ownCloud version:** (see ownCloud admin page)

10.0.2.1

**Updated from an older ownCloud or fresh install:**

attempting to upgrade 10.0.1 install from source

**Where did you install ownCloud from:**

Source

**Signing status (ownCloud 9.0 and above):**

Signed.

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**
Enabled:
  - calendar: 1.4.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.9
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_external_ftp: 0.2.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.0
  - files_texteditor: 2.2
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - files_volatile: true
  - firstrunwizard: 1.1
  - market: 0.1.0
  - notes: 2.0.2
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.3
  - templateeditor: 0.1
  - twofactor_totp: 0.4.3
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - theme-example
  - user_external

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Maybe your network connection from the server to the marketplace is slow, or the marketplace server was slow at this moment...

But I also remember seeing some code paths that seemed to fetch the same data multiple times, so this needs to be double checked to make sure no time is wasted.

@VicDeo

**Comment by ekgermann** [comment]
I could buy that except for the following reasons:

1.  It's a 10M link and lightly used.  Downloading via browser from the store was fine.

2.  It's way too consistent at 75secs +/- 1 sec for every fetch it tries to make

If you need more info or tests, please let me know.  Happy to chase it down from this side if I can.

**Comment by VicDeo** [comment]
Juest a guess: Could it be SSL-related?

**Comment by VicDeo** [comment]
@PVince81 It looks like marketplace.owncloud.com has an IPv6 address  address assigned that doesn't respond:

https://www.ssllabs.com/ssltest/analyze.html?d=marketplace.owncloud.com

<table>
<tr> <th>	Server</th>	<th>Test time</th><th>	Grade</th>
</tr>
<tr>
<td>
1	5.9.68.237 pearl.owncloud.com  Ready </td> <td> Tue, 20 Jun 2017 15:37:20 UTC Duration: 95.585 sec</td>	<td>A</td>
</tr>
<tr>
<td>2	2a01:4f8:161:73ec:0:0:0:2 Unable to connect to the server </td>
<td> Tue, 20 Jun 2017 15:38:55 UTC Duration: 15.15 sec	</td><td>-</td></tr>
</table>
<b>Warning</b>: Inconsistent server configuration

**Comment by VicDeo** [comment]
In addition: This is what I have while connecting from CLI:
```
deo@jah-mobile:~> openssl s_client  -connect  marketplace.owncloud.com:443          
CONNECTED(00000003)
depth=0 CN = TRAEFIK DEFAULT CERT
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = TRAEFIK DEFAULT CERT
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN=TRAEFIK DEFAULT CERT
   i:/CN=TRAEFIK DEFAULT CERT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIDRzCCAi+gAwIBAgIRAIHiegP3DVDARNIaCkQROa4wDQYJKoZIhvcNAQELBQAw
HzEdMBsGA1UEAxMUVFJBRUZJSyBERUZBVUxUIENFUlQwHhcNMTcwNTIyMTMzMjM5
WhcNMTcwNTIyMTMzMjM5WjAfMR0wGwYDVQQDExRUUkFFRklLIERFRkFVTFQgQ0VS
VDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKTVN1ofeL5CIslA2Y7t
C7VnQslHgjUavpVmLBE6kSN92IPu0yPhPPUTefAtev1jVukyDKRqEK9mJE6IRAus
FWvq3pqfguLlUa2aF6IX1hpZN1RoqNSd1chWj+oJ0i/oVPvD5hGYV6XQbi8Nzrg2
a4WCraJHMQjU7reJcCaMK5jrhXK0XCkuK1CeSyHfg89gsk5mHRanbozaYNzm2EDX
ythl/TUfzYbmNMEji78gOIe8gMkwnaMgvg8rHqSgXdcYPws1HKWqlI1v7+y6WkPk
7cGeP9nqI1xw3fW58Nf5x6RX5ubv/0os2IHkgZqRcsF7HtvMCXN/KHM5W0CuJxD9
9ksCAwEAAaN+MHwwDgYDVR0PAQH/BAQDAgUgMAwGA1UdEwEB/wQCMAAwXAYDVR0R
BFUwU4JRMTM4NzA2MjgxMTUzNWQ4NmI4Y2JjMjM0NjdkYjM4Y2EuZmIyZDhiMGZk
MmM3OTBlNjNjMDY2YmIwOWFlYWFkYjAudHJhZWZpay5kZWZhdWx0MA0GCSqGSIb3
DQEBCwUAA4IBAQCIAaBggRHdv/mouuQ40wq82cGgF9mbU/W2QyTzbhBhify6Rvti
mBoDuztdj/uDEbcnpLGjAyi1ymrM4AgVX1ncYZULJsrI5HArC7JkR/PMujFCoD4e
FlvZ39xKFgl5CfZ6vgBoNPuXLx+DLOETisP8Llpa0apVYCHVKWB8SFxRZHSvGMLc
1FjaryVZa+JeITACfwGBq0/Ygxzd14sDo5WiUYCd/my0kSaeS2vipMGqOXlT/5cO
0bMkFiwlRqDIr1bZO1bLOPCnmjDqD9Puqft/mTS5uqn2WnbjvfM/z/4Vkbsslez3
VZFP7Up4/7bAxBBO3D4evHc2bOK0E1Z9kqEj
-----END CERTIFICATE-----
subject=/CN=TRAEFIK DEFAULT CERT
issuer=/CN=TRAEFIK DEFAULT CERT
---
No client certificate CA names sent
Peer signing digest: SHA384
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 1449 bytes and written 419 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: B2220E02C0C3857E693D8E7C587D4967F4D2B799DDF64911592C2A2B12B66BE9
    Session-ID-ctx: 
    Master-Key: 8EBDFE56D6BB81845220F6B3DC49673C00009436B5A4205370BBCEF64578C09DA40A7ABA06E0174444EEBC6C97F28160
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket:
    0000 - f3 85 09 8d 45 02 94 d4-d5 3a 1a 7c 7c cd 2f 42   ....E....:.||./B
    0010 - 50 b9 a1 25 f6 2b 8d 48-75 8f 76 7b 01 7d bb 05   P..%.+.Hu.v{.}..
    0020 - 80 77 b6 26 28 0a 0b 8e-1c 32 4b f9 90 e2 df 5a   .w.&(....2K....Z
    0030 - 6d a6 a0 24 89 e6 bc d2-4c af 8b 39 93 12 f8 49   m..$....L..9...I
    0040 - 19 57 6f 6a 8a 0f 00 79-70 67 14 9e a9 82 c8 ce   .Woj...ypg......
    0050 - f1 89 22 02 38 01 e3 d9-f3 ea ee 27 02 c2 6d fd   ..".8......'..m.
    0060 - 52 4f d0 c7 15 4c d6 db-8d 1e 0b d6 21 c8 56 fd   RO...L......!.V.
    0070 - 37 00 29 c4 0c ae de 25-                          7.)....%

    Start Time: 1497973894
    Timeout   : 300 (sec)
    Verify return code: 21 (unable to verify the first certificate)
---

```

It seems to be related to the fact that this server has two cert paths. The first is valid and the second is not
https://www.ssllabs.com/ssltest/analyze.html?d=marketplace.owncloud.com&s=5.9.68.237

**Comment by ekgermann** [comment]
That could very well be it. I'm V6 enabled. 

EKG

**Comment by ekgermann** [comment]
Hangs the same way with openssl s_client because of IPv6 so I suppose that's it.

I would either fix the IPv6 listener or pull the AAAA record.

EKG

**Comment by PVince81** [comment]
Closing as this is old. Please post to https://github.com/owncloud/marketplace-issues if the IPv6 error happens again.
