### ISSUE TITLE
EXCEPTION after update

### ISSUE THREAD

**Issue by DominicWrege** [owncloud/core#28076]
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- calendar
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate has been revoked.

Raw output
==========
Array
(
    [calendar] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate has been revoked.
                )

        )

)

### Steps to reproduce
1. just update with apt to the current newest version.(02.06 2017)

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
ubuntu 16.04 LTS
**Web server:**
Apache/2.4.18
**Database:**
mysql
**PHP version:**
php7
**ownCloud version:** (see ownCloud admin page)
9.1.6.2'
**Updated from an older ownCloud or fresh install:**
from 9.1.4-2.1
**Where did you install ownCloud from:**
own server at home
**Signing status (ownCloud 9.0 and above):**
ownCloud 9.0 and above
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**
* Calendar
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Vivaldi, Chrome, Safari
**Operating system:**
Windows10, Windows 7 (clients)
#### Web server error log
```
Insert your webserver log here
```
Error	PHP	Cannot modify header information - headers already sent at /var/www/owncloud/lib/private/User/Session.php#820

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
{"reqId":"cXOIR1LVZ+VKvjBRJYb9","remoteAddr":"71.6.202.204","app":"core","message":"Trusted domain error. \"71.6.202.204\" tried to access using \"80.139.39.210\" as host.","level":2,"time":"2017-06-02T04:08:07+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"zOWTzxsdLtCA3cIA5Bbw","remoteAddr":"216.218.206.69","app":"core","message":"Trusted domain error. \"216.218.206.69\" tried to access using \"80.139.39.210\" as host.","level":2,"time":"2017-06-02T10:34:41+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"XrCibKuIa1+cGfqwocy6","remoteAddr":"93.239.57.37","app":"core","message":"starting upgrade from 9.1.6-1.1 to 9.1.6.2","level":0,"time":"2017-06-02T17:06:12+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=dasudhuasduhue781ze8dsad","user":"--"}
{"reqId":"XrCibKuIa1+cGfqwocy6","remoteAddr":"93.239.57.37","app":"PHP","message":"Cannot modify header information - headers already sent at \/var\/www\/owncloud\/lib\/private\/User\/Session.php#813","level":3,"time":"2017-06-02T17:06:36+00:00","method":"GET","url":"\/core\/ajax\/update.php?bladjihsdiuheuhdusahudusahhdushaud","user":"--"}
{"reqId":"XrCibKuIa1+cGfqwocy6","remoteAddr":"93.239.57.37","app":"PHP","message":"Cannot modify header information - headers already sent at \/var\/www\/owncloud\/lib\/private\/User\/Session.php#814","level":3,"time":"2017-06-02T17:06:36+00:00","method":"GET","url":"\/core\/ajax\/update.php?bladjihsdiuheuhdusahudusahhdushaud","user":"--"}
{"reqId":"XrCibKuIa1+cGfqwocy6","remoteAddr":"93.239.57.37","app":"PHP","message":"Cannot modify header information - headers already sent at \/var\/www\/owncloud\/lib\/private\/User\/Session.php#815","level":3,"time":"2017-06-02T17:06:36+00:00","method":"GET","url":"\/core\/ajax\/update.php?bladjihsdiuheuhdusahudusahhdushaud","user":"--"}
{"reqId":"XrCibKuIa1+cGfqwocy6","remoteAddr":"93.239.57.37","app":"PHP","message":"Cannot modify header information - headers already sent at \/var\/www\/owncloud\/lib\/private\/User\/Session.php#818","level":3,"time":"2017-06-02T17:06:36+00:00","method":"GET","url":"\/core\/ajax\/update.php?bladjihsdiuheuhdusahudusahhdushaud","user":"--"}
{"reqId":"XrCibKuIa1+cGfqwocy6","remoteAddr":"93.239.57.37","app":"PHP","message":"Cannot modify header information - headers already sent at \/var\/www\/owncloud\/lib\/private\/User\/Session.php#819","level":3,"time":"2017-06-02T17:06:36+00:00","method":"GET","url":"\/core\/ajax\/update.php?bladjihsdiuheuhdusahudusahhdushaud","user":"--"}
{"reqId":"XrCibKuIa1+cGfqwocy6","remoteAddr":"93.239.57.37","app":"PHP","message":"Cannot modify header information - headers already sent at \/var\/www\/owncloud\/lib\/private\/User\/Session.php#820","level":3,"time":"2017-06-02T17:06:36+00:00","method":"GET","url":"\/core\/ajax\/update.php?bladjihsdiuheuhdusahudusahhdushaud","user":"--"}
{"reqId":"IEUaZsQl5XWAOOz01D26","remoteAddr":"","app":"core","message":"starting upgrade from 9.1.6 to 9.1.6.2","level":0,"time":"2017-06-02T17:34:53+00:00","method":"--","url":"--","user":"--"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

console error:
Failed to load resource: the server responded with a status of 403 (Forbidden) 
/data/htaccesstest.txt?t=1496426219660 Failed to load resource: the server responded with a status of 403 (Forbidden)

```

a) The javascript console log
b) The network log 
c) ...

**Comment by kdslkdsaldsal** [comment]
@DominicWrege See https://github.com/owncloud/calendar/issues/800
