### ISSUE TITLE
Unable to sync calendars to local clients (Evolution, Android), but able to create new events from clients

### ISSUE THREAD

**Issue by jeppebundsgaard** [owncloud/core#28078]
### Steps to reproduce
1. Update calendar at local device (or create new calendar and sync with owncloud)

### Expected behaviour
Events are synced to local device (Evolution, Android calendar)

### Actual behaviour
No event are synced TO device. 
But able to create event at local device, and it is synced to the server. But when updating calendar at local device, event is gone...

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.18 

**Database:** Mysql  5.0.12

**PHP version:** 7.0.18

**ownCloud version:** (see ownCloud admin page) 9.1.6

**Updated from an older ownCloud or fresh install:** 9.1.5 
(problem existed there as well. Think it came when updating to 9.1.5).

**Where did you install ownCloud from:** Ubuntu apt

**Signing status (ownCloud 9.0 and above):** 
https://gist.github.com/jeppebundsgaard/4999cd4e6d7bdf415aeed26709446942 
NOTE: This has nothing to do with the error - the error was there before this signing problem (see https://github.com/owncloud/calendar/issues/800).

**The content of config/config.php:**

"config": {
        "instanceid": "oc61s6qh8f84",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "sky.bundsgaard.net"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/sky.bundsgaard.net",
        "dbtype": "mysql",
        "version": "9.1.6.2",
        "dbname": "owncloud8",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "jeppe",
        "mail_domain": "bundsgaard.net",
        "theme": "",
        "maintenance": false,
        "forcessl": true,
        "forceSSLforSubdomains": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.bundsgaard.net",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    },
    

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.1
  - dav: true
  - documents: 0.13.1
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - audioplayer
  - encryption
  - external
  - files_antivirus
  - files_external
  - mail
  - music
  - notes
  - user_external
  - user_ldap

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration
**Browser:**
N/A
**Operating system:**
Ubuntu 17.04, Android 7.0

#### Web server error log
[Sat Jun 03 18:48:40.767577 2017] [authz_core:error] [pid 13686] [client 107.217.190.157:54350] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Sat Jun 03 19:18:10.296531 2017] [authz_core:error] [pid 15283] [client 107.217.190.157:53590] 

#### ownCloud log (data/owncloud.log)
Debug 	webdav 	Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(61): Sabre\\DAV\\Server->exec()\n#5 \/var\/www\/owncloud\/remote.php(164): require_once('\/var\/www\/ownclo...')\n#6 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false} 	2017-06-03T19:17:46+00:00 
#### Browser log
N/A

**Comment by kdslkdsaldsal** [comment]
@jeppebundsgaard From my experience such issues are mostly caused by server mis-configurations / issues unrelated to ownCloud itself.

For now i suggest to close here and work your way through the following resources:

https://central.owncloud.org/t/no-basic-authentication-headers-were-found-message/819
https://central.owncloud.org/t/how-to-fix-caldav-carddav-webdav-problems/852

If you need further support with that you can also create a new thread at central (you can login with your github account there). Only if its clear that this is a bug in ownCloud (which i highly doubt) the issue here can be re-opened.

**Comment by jeppebundsgaard** [comment]
I had looked into those, and they don't seem to fit my problem. I will create a thread at central. Thanks.
