### ISSUE TITLE
'trusted_domains'

### ISSUE THREAD

**Issue by mehdi-song** [owncloud/core#28077]
Hi 
i install owncloud 10.0.2 today but in vmware.
server ip : 172.16.30.29 and every things were good since forward port 6060 to external ip  192.64.1x.xxx:6060 .

but i see : 
You are accessing the server from an untrusted domain.

Please contact your administrator. If you are an administrator of this instance, configure the "trusted_domains" setting in config/config.php. An example configuration is provided in config/config.sample.php.
Depending on your configuration, as an administrator you might also be able to use the button below to trust this domain.

Add "192.64.1x.xxx:6060" as trusted domain 

after i add ip to  trusted domain and again i try http://192.64.1x.xxx:6060 ,
i see previous message .

is it a BUG ? 

**Operating system**:
Centos 6.8 x64
**Web server:**
Server version: Apache/2.2.15 (Unix)
**Database:**
mysql 5.4
**PHP version:**
5.6
**ownCloud version:** (see ownCloud admin page)
10.0.2
**Updated from an older ownCloud or fresh install:**
Fresh install
**Where did you install ownCloud from:**
https://owncloud.org/install/#edition

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'xxxxx',
  'passwordsalt' => 'xxxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => '172.16.30.29',
    1 => '192.64.1x.xxx:6060',
  ),
  'datadirectory' => '/var/www/html/owncloud/data',
  'overwrite.cli.url' => 'http://172.16.30.29/owncloud',
  'dbtype' => 'mysql',
  'version' => '10.0.2.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost:5432',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_administrator',
  'dbpassword' => 'xxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
FireFox 53.0.3 (32bit)
**Operating system:**
Windows 7 Sp1 (32bit

#### Web server error log
[error_log.txt](https://github.com/owncloud/core/files/1049254/error_log.txt)

Insert your webserver log here
[access_log.txt](https://github.com/owncloud/core/files/1049255/access_log.txt)

#### ownCloud log (data/owncloud.log)

Insert your ownCloud log here
[owncloud_log.txt](https://github.com/owncloud/core/files/1049258/owncloud_log.txt)

**Comment by kdslkdsaldsal** [comment]
Have you tried using ``192.64.1x.xxx`` instead of ``192.64.1x.xxx:6060`` in the trusted_domains setting?

**Comment by mehdi-song** [comment]
Hi
Thanks for your reply. 
I use but not changed and I received trust domain error.

**Comment by Murilo-BR** [comment]
Hi 
I have a similar behavior: owncloud 9 asked to add a client IP (not Server IP as usual) as a trusted domain.

Although the site has a Geo Trust CA, I verified that oc.js was not transferred as https, and the transfer-encoding (Headers) was not chunked. Weird: sometimes OC9 was responding without errors.

I changed the trigger of cron.php from **ajax** to webcron  and it starts to work automagically. IMHO a cron task is a better solution than webcron - if your (shared) host allows. 

I am still testing, but perhaps this helps you. 
Regards
Murilo

**Comment by PVince81** [comment]
No, you need to add the server's own domain as trusted domain. Never add a client IP.

If for example your server is accessible under "https://myserver1.tld", "https://myserver2.tld" you need to add "myserver1.tld" and "myserver2.tld" in the trusted domains.
