### ISSUE TITLE
Feature Request: Have data that does not belong to a single user

### ISSUE THREAD

**Issue by cornelinux** [owncloud/core#28083]
### Steps to reproduce
0. Use ownCloud 10.0.2
1. A user uploads data to his folders
2. The administrator deletes the user
3. The user is deleted without questions asked and **all his data is deleted**.

### Expected behaviour
It would be nice, if the data could somehow be kept.

### Actual behaviour
The data is deleted when the data owner is deleted.

### Ideas
Imagine this is no personal data but the data from a company, a project the user is working on...

So maybe I would like to have data, that does not belong to a user, but to a project or the company.
This data must stay intact, even if the last project member was removed.

Obviously there needs to be done some design on this topic.

So how would this be covered, that we have persistent data which belongs to the system and users are only using this data but not owning it?

**Comment by jvillafanez** [comment]
You can disable the account. After that you can do what you want (transfer the ownership of the files to another account for example), and finally delete it.

I don't think there is any action to be taken here.

> So maybe I would like to have data, that does not belong to a user, but to a project or the company.
This data must stay intact, even if the last project member was removed.

You can create an specific account just to hold those files. This could be a short term solution.

Or you can mount an external storage (with the limitations it has) where admins access with an account with read-write access, but the rest with a different account with read-only access.

**Comment by phil-davis** [comment]
Thee way I have achieved this is administrative. Create a user that is not a real person, but is, for example, the department concerned - e.g. "HR" "Finance" etc. Give it a quota that is enough for the common files of the whole department. Give the login details to someone in that department who manages the department folder/file layout. Make a group "HR" also (and other groups "HRreadonly" or... that might want different file access privs). Share folder(s) from the "HR" user to "HR", "HRreadonly" etc with the desired access privs.

This "HR" user never needs to be deleted. And there is effectively a single disk quota for all the department shared files.

**Comment by cornelinux** [comment]
@phil-davis thanks for the suggestions.
Still sounds a bit like overhead to me. I wonder if there might be nice ways to integrate such kind of behaviour directly in ownCloud.

I will change the topic.

**Comment by PVince81** [comment]
something like project rooms ?

cc @pmaier1

**Comment by PVince81** [comment]
I'm pretty sure there is an older ticket about this because this is requested quite often. But I'm not able to find it right now.

**Comment by jelinj8** [comment]
What about "group folders"? They aren't owned by any user, or are they?
