### ISSUE TITLE
Webdavs on Windows not working anymore after upgrade

### ISSUE THREAD

**Issue by wforumw** [owncloud/core#28089]
After upgrade our owncloud sever to version 10.0.0-1.1 (in Debian Jessie) we have a problem with webdavs on windows 7.
When I try to copy a file to the webdavs share I always get this error
Can't read from the source file or disk
When I cancel the error the file is there but empty (0KB)
I can read and delete files but no write
On another owncloud server with version 9.1.6-1.1 (also Debian Jessie) we don't have this issue.
Any ideas?
TXS

### Steps to reproduce
1. Add webdavs share in Windows Explorer
2. Try to copy a file into it

### Expected behaviour
Copy the file with no error

### Actual behaviour
Can't read from the source file or disk

### Server configuration
**Operating system**:
Debian Jessie
**Web server:**
Apache 2.4.10
**Database:**
mysql 5.5
**PHP version:**
php 5.6
**ownCloud version:** (see ownCloud admin page)
10.0.0
**Updated from an older ownCloud or fresh install:**
updated from 9.1.5

**Comment by kdslkdsaldsal** [comment]
Hi,

> version 10.0.0-1.1

from the issue template you have filled out:

> Before reporting any issues please make sure that you're using the latest available version for your major branch (e.g. 9.0.x), see https://owncloud.org/changelog/

10.0.0 was the first release and there are already two newer version 10.0.1 and 10.0.2 available.

**Comment by wforumw** [comment]
hi,
i have installed the latest version 10.0.2-1.1 but the problem still exist.

**Comment by nonschef** [comment]
hi,
i have an similar problem. Since 9.1.5 i can not connect to webdav via Windows 7.
Other OS (ubuntu) or webdav clients (3rd party) have no problems.

**Comment by kdslkdsaldsal** [comment]
@nonschef If you had 9.0.x before then guess this is a different issue and was discussed thoroughly here: https://github.com/owncloud/core/issues/26350

**Comment by PVince81** [comment]
Which URL are you using when connecting with Windows ?

**Comment by wforumw** [comment]
`https://owncloudserver/remote.php/webdav`

I can see/read everything but if I copy files I get the error

**Comment by PVince81** [comment]
and is there any log entry in owncloud.log matching the error ?

**Comment by glannes31** [comment]
Hello, I have the same problem with OC 10.0.2  . {"reqId":"WYQeNQpFlDQAAAKbRnEAAAAG","level":4,"time":"2017-08-04T07:11:49+00:00","remoteAddr":"10.32.101.193","user":"test","app":"webdav","method":"LOCK","url":"\/remote.php\/webdav\/BS_P1_MD_Fiche-Suivi-Prestation-Constat-Client%20-guillaume%20lacrouts%20.docx","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 No subsystem set a valid HTTP status code. Something must have interrupted the request without providing further detail.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Code\":0,\"Trace\":\"#0 \\\/cnywq00\\\/prd\\\/web\\\/html\\\/mycore\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/cnywq00\\\/prd\\\/web\\\/html\\\/mycore\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#2 \\\/cnywq00\\\/prd\\\/web\\\/html\\\/mycore\\\/remote.php(165): require_once('\\\/cnywq00\\\/prd\\\/we...')\\n#3 {main}\",\"File\":\"\\\/cnywq00\\\/prd\\\/web\\\/html\\\/mycore\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":495,\"User\":\"test\"}"}

**Comment by kdslkdsaldsal** [comment]
@glannes31 This will be fixed with the upcoming 10.0.3: https://github.com/owncloud/core/pull/28204 / https://github.com/owncloud/core/pull/28243

**Comment by glannes31** [comment]
Okay , thanks for the information . Could i have the changelog for the version 10.0.3  ?

**Comment by phil-davis** [comment]
10.0.3 is not released yet, so there is no changelog written yet.
You can look through the commits in stable10 since 10.0.2 release and that is what is heading for 10.0.3 so far.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
