### ISSUE TITLE
GIT - upgrade not installed market, stuck in maintenance mode

### ISSUE THREAD

**Issue by smarek** [owncloud/core#28087]
```
$ ./occ status
  - installed: true
  - version: 10.0.2.1
  - versionstring: 10.0.2
  - edition: Community
```

Upgrading from 9.1 to 10.0.2 via git

- After upgrade i've ran `make` which succeeded
- `./occ upgrade` reported missing market app and did not upgrade
- I've manually installed market via git `git clone https://github.com/owncloud/market.git app/market`
- Compile market `cd app/market ; make`
- `make clean && make `
- Deleted old `3rdparty` folder
- ownCloud is running successfully

What is imho missing is some migration step, that should either install market app or `occ upgrade` should not require the market app to be available.

Specific error shown by `occ upgrade` was `Exception: "market can't be enabled since it is not installed"`

**Comment by PVince81** [comment]
Upgrading through git is not officially supported for productive environments.
So probably more something for the docs or FAQ.

**Comment by macdabby** [comment]
I just ran into this problem upgrading from 9.1.6 to 10.0.7. Cloning the market app worked for me, but i think this ticket should still be considered open and the installer should manage to install without failure there.
