### ISSUE TITLE
Encryption for Owncloud 10

### ISSUE THREAD

**Issue by UnMenorqui** [owncloud/core#28088]
Hi guys!

I've been setting up Owncloud 9 and 10 for my office, and realised a few things you might know, but i'm wondering if there's any possibility to do improve it/solve it.

So, when i'm enabling the encryption, this one it's enabled by default for every user, is there any chance to encrypt only a few users?

Actually another thing that i realised, is that via Occ comand line, it doesn't work properly the decryption of an user if him has lost his password. When trying to decrypt his home, sometimes said it was successfully completed, and other it said that it couldn't do it. 

The las thing, is that when disabling the encryption from the occ comand line, files are still encrypted on the server, but you can access them normally from de web-browser. Should the files seen from de server be decrypted?

Thank you so much!

**Comment by kdslkdsaldsal** [comment]
@UnMenorqui Please note this is a bugtracker of ownCloud.

Please close here and use https://central.owncloud.org/ for your questions (you can login with your github account there).
