### ISSUE TITLE
Password Change Required Every 90 Days in owncloud

### ISSUE THREAD

**Issue by takenek** [owncloud/core#28081]
Hello Guys
There is any way to force users to change password every 90 days in OwnCloud?
I try find this in documentation but i can`t find :(

Best Regards
TaKeN

**Comment by PVince81** [comment]
there is currently no such feature

cc @pmaier1

**Comment by takenek** [comment]
so bad.... :-(

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by DeepDiver1975** [comment]
will be implemented over here - https://github.com/owncloud/password_policy/issues/2
