### ISSUE TITLE
Send error message to clients at upload of .part files

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#28092]
### Steps to reproduce

1. create file or folder with ".part" at the end in any client/app

**iOS 3.5.4 (oC 9.1.5)**

New folder: testfolder.part ==> Error: Folder could not be created
New test file: testfile.part ==> No file gets created, no error message

**client 2.3.2rc1 (oC 9.1.5)**

<img width="502" alt="test_and__9_0_5__large_file_is_disappeared_after_upload_ _issue__1644_ _owncloud_enterprise" src="https://cloud.githubusercontent.com/assets/214010/25800393/73b8f1d6-33e9-11e7-8e58-bb9de766e726.png">

==> No errors in the Account tab, no errors in the Activity tab.

### Expected behaviour

Desktop client and mobile apps should receive an error message sent by oC server, same as ~~at the upload of files to a folders where I have no upload permissions~~ [if I try to share, but don't have share permission](https://github.com/owncloud/core/search?l=PHP&q=%22You+are+not+allowed+to+share%22&type=Code&utf8=%E2%9C%93).

### Actual behaviour

No useful feedback for the user.

**Related:**

- https://github.com/owncloud/core/issues/27878
- https://github.com/owncloud/enterprise/issues/1644
- https://github.com/owncloud/platform/issues/72#issuecomment-299922334

@tomneedham

**Comment by butonic** [comment]
@tomneedham just collect a mitmproxy dump to see what is sent to the clients. might be that we already sen a message. The desktop client at least does show one. So the mobile apps should be able to detect that a file upload was forbidden. this is all webdav ...

**Comment by michaelstingl** [comment]
I had to remove "`*.part`" from [client/sync-exclude.lst](https://github.com/owncloud/client/blob/master/sync-exclude.lst#L26) for my test, then I captured the request with mitmproxy:

![mitmproxy1](https://user-images.githubusercontent.com/214010/27234309-d8d5368c-52bc-11e7-9162-b6989f70deae.png)
![mitmproxy2](https://user-images.githubusercontent.com/214010/27234310-d8dae67c-52bc-11e7-9896-a72deadaa1cb.png)
![mitmproxy3](https://user-images.githubusercontent.com/214010/27234311-d8ea3dca-52bc-11e7-8c7b-6cbe166bd922.png)

If the oC server don't like a file for any reason, or an app blocks the upload, I would prefer to get a proper error message to reduce error handling efforts in all client platforms.

**Comment by PVince81** [comment]
In general I agree, the message can then also be used in the web UI since the web UI uses Webdav as well.

**Comment by PVince81** [comment]
Retested with 10.0.3RC1
![spectacle xf1463](https://user-images.githubusercontent.com/277525/30183669-9a1237f6-941b-11e7-9760-9fb2f2968a6e.png)
