### ISSUE TITLE
Source tar for litmus canot be retrieved from www.webdav.org

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#28104]
### Steps to reproduce
1. Make a change in a PR that triggers the litmus job on Travis
2. Watch it fail because www.webdav.org does not resolve

### Expected behaviour
The litmus tests should start, and even pass.

### Actual behaviour
The litmus tar fails to download because www.webdav.org does not resolve

Not sure when this started to be a problem, but certainly for the last few hours:

```
C:\Users\phil.davis>nslookup www.webdav.org 8.8.8.8
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

*** google-public-dns-a.google.com can't find www.webdav.org: Non-existent domain

C:\Users\phil.davis>nslookup webdav.org 8.8.8.8
Server:  google-public-dns-a.google.com
Address:  8.8.8.8

Non-authoritative answer:
Name:    webdav.org
Address:  140.211.166.111
```
The necessary litmus tar is found fine just through webdav.org and that resolves. So might as well use the shorter URL all the time, whether the problem with www.webdav.org is permanent or only transient.

**Comment by SergioBertolinSG** [comment]
Fixed in https://github.com/owncloud/core/pull/28103.

**Comment by phil-davis** [comment]
Note: as of now, www.webdav.org is resolving again. I guess it broke for some time last week. In any case it seems safer to use webdav.org - that works more often.
