### ISSUE TITLE
 Allow public page access to apps with group restrictions on

### ISSUE THREAD

**Issue by pranavk** [owncloud/core#28108]
Currently, when group restrictions are on, it is not possible to have a controller method declared as public page because the security middleware checks if the app is enabled for the user unconditionally.

See: https://github.com/owncloud/core/blob/master/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php#L151

Although, when group restrictions are disabled, then \OC_App::isEnabled($this->appName) returns true making it possible to access a public controller method.

However, an app might need to make a method public even when group restrictions are on. My use case is owncloud/richdocuments where the document editing service requires to download the document from owncloud to be able to edit it. Since it has no user context, it downloads the file (and does some other stuff too) via a public controller method, which fails when group restrictions are on.

I think we may need to introduce a new annotation here and then guard the security middleware method there with it.

**Comment by dercorn** [comment]
@pranavk please describe what exactly you need for this to work.

**Comment by pranavk** [comment]
@dercorn Guarding this[1] with some annotation check should do.

Maybe we can reuse the PublicPage annotation. Moving this[1] block up to the if(!isPublicPage) condition should do. This is so that whether the app is enabled or not is checked only in case the controller method is not a PublicPage.

When a controller method is declared as Public, of course the developer want the method to be accessible publicly without any user login. Checking for enabled app for current user, in this case, doesn't make much sense I guess.

Can do a PR if core devs are happy with the above approach.

[1] https://github.com/owncloud/core/blob/master/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php#L151

**Comment by PVince81** [comment]
Likely duplicate of https://github.com/owncloud/core/issues/20304

Please check this ticket. From what I remember the fix is not that easy.

cc @tomneedham

**Comment by tomneedham** [comment]
The problem is in deciding the logic for the three use cases that you land on the page:

 - user logged in + in group the app is enabled for
 - user logged in + not in the group the app is enabled for
 - not logged in user

PR was here https://github.com/owncloud/core/pull/20310

**Comment by dercorn** [comment]
@pmaier1 @tomneedham @PVince81 any suggestions on how to proceed here?

**Comment by DeepDiver1975** [comment]
The issue was solved within the scope of the richdocuments app: https://github.com/owncloud/richdocuments/pull/192

Generally speaking: if an app provides public routes/code it has to be enabled for all users.

The big picture solution for collabora is to split the apps in frontend and backend part.

I'm closing this therefore
