### ISSUE TITLE
Copying public links is not possible using safari.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#28105]
### Steps to reproduce

0. Using safari browser do:
1. Upload a file.
2. Share it by link. (Create a public link for it).
3. Try to copy the public link. 

### Expected behaviour
You can copy the link without problems.

### Actual behaviour
The copy button doesn't works on safari suggesting to use cmd+c command, but there is no field showing the actual link url. So not possible to be selected to be copied.

![copying_public_links_safari](https://user-images.githubusercontent.com/9048796/26916930-817df432-4c2c-11e7-9312-1ab89c16412f.gif)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.2.1","versionstring":"10.0.2.1","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No

**Logs**

### Client configuration

**Browser**
Safari v9

**Logs**
```
```

cc @felixheidecke

**Comment by SergioBertolinSG** [comment]
OK, it is possible to copy the link, when the tooltip appears if you hit cmd+c as it says, the link is copied. But it is a bad UX anyway as the tooltip info seems to mean that you'll have to select and copy the link from somewhere (the behaviour in <=9.1). Also you have to click cmd+c in that precise moment.

**Comment by PVince81** [comment]
moving to triage as no one is assigned to work on this

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
to be retested with latest Safari and 10.0.4

**Comment by felixboehm** [comment]
Retested in safari 9.1.1 and 9.1.3
Public link hardly usable in safari.

**Comment by davitol** [comment]
Tested with Safari Version 11.1  and works for me
