### ISSUE TITLE
"execution_duration" column from `jobs` database missing in schema, breaks occ `db:convert-type`

### ISSUE THREAD

**Issue by gBokiau** [owncloud/core#28100]
### Steps to reproduce
1. Update from OC 9 to 10
2. Use OCC `db:convert-type` command

### Expected behaviour
Database converts

### Actual behaviour
Conversion breaks once it starts copying the jobs database, with the following error:
```
…
 4/4 [============================] 100%preferences
 17/17 [============================] 100%jobs
  1/15 [=>--------------------------]   6%
[Doctrine\DBAL\Exception\InvalidFieldNameException]                                                                                                      
  An exception occurred while executing 'INSERT INTO "jobs" ("id", "class", "argument", "last_run", "last_checked", "reserved_at", "execution_duration")   
  VALUES(?, ?, ?, ?, ?, ?, ?)' with params ["1", "OCA\\Activity\\BackgroundJob\\EmailNotification", "null", "1496869202", "1496870102", "0", "0"]:         
  SQLSTATE[42703]: Undefined column: 7 ERROR:  column "execution_duration" of relation "jobs" does not exist                                               
  LINE 1: ...ment", "last_run", "last_checked", "reserved_at", "execution...
```

### Server configuration
**ownCloud version:** 10.0.2
**Updated from an older ownCloud or fresh install:** Sure did

Trouble seems to be with commit: 4a4fbb5d5cb17291e62f9a2d2a57be3e4ae7671e. The schema and the db no longer match.

**Comment by kdslkdsaldsal** [comment]
db:convert-type currently doesn't work at all since oC 10: https://github.com/owncloud/core/issues/27075

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/issues/27075
