### ISSUE TITLE
Thumbnails are not shown in the version section

### ISSUE THREAD

**Issue by davitol** [owncloud/core#28115]
Steps to reproduce

   1. Create a text file document, edit it and save
   2. Edit the document another time in order to create a version
   3. Browse to details --> version menu

Expected behaviour

The thumbnails should be shown in the version menu

Actual behaviour

The thumbnails are not shown as it was done in previous oC versions

Server configuration

Operating system:
Ubuntu 16.04

Web server:
Apache

Database:
MySQL

PHP version:
7.0

ownCloud version:

"version":"10.0.0.1" daily master

Updated from an older ownCloud or fresh install:
Fresh

Are you using external storage, if yes which one: local/smb/sftp/...
No

Are you using encryption:
No

Logs

Client configuration

browser

Mozilla

![screen shot 2017-06-12 at 08 34 36](https://user-images.githubusercontent.com/10596560/27021788-f0b5d36c-4f4a-11e7-9a0d-859313dafb18.png)

@VicDeo

**Comment by VicDeo** [comment]
hmm. It works for me on the fresh master@859eade9cb2fb962f322c4959a3c3bb2d8d699f0

>"10.0.0.1" daily master

is kinda old, will check with 10.0.2

**Comment by VicDeo** [comment]
@davitol Could it be a kind of Addblock browser extension blocking a version preview?

**Comment by davitol** [comment]
@VicDeo I have checked in FireFox and in Chrome for OSX, and it doesn't WFM in any of them

**Comment by VicDeo** [comment]
mmm. This is what I have in Firefox on master:
![versions](https://user-images.githubusercontent.com/991300/27044313-ce392c5c-4fa5-11e7-840e-9490b9afc6fd.png)

**Comment by davitol** [comment]
Checking in the wrong section. It works in master so let's close the ticket. Sorry for the noise @VicDeo
