### ISSUE TITLE
OCA\DAV\CardDAV\SyncService syncInstance() runs for very long time

### ISSUE THREAD

**Issue by priittoobla** [owncloud/core#28116]
### Problem in a nutshell: 
OCA\DAV\CardDAV SyncJob cron job runs for very very very long time if instance has tens of thousands of users.

 
### Steps to reproduce
1. Have a lot of users. Try with 17000 users.
2. Wait for the OCA\DAV\CardDAV SyncJob cron job to run (happens once in 24h)
3.

### Expected behaviour
Job should run quickly

### Actual behaviour
It runs for hours. In hours I mean like 10 or more. It tries to parse all users and principal/system/system addressbook cards in one pass

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** Mysql 5.6.22

**PHP version:** 7.0.19

**ownCloud version:** (see ownCloud admin page) 9.1.6

**Updated from an older ownCloud or fresh install:** updated from 9.1.5

**Where did you install ownCloud from:** zip downloaded from owncloud.org

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**The content of config/config.php:**

```
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
{
    "system": {
        "instanceid": "oc36130885d4",
        "apps_paths": [
            {
                "path": "\/srvdata\/owncloud\/htdocs\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "customclient_android": "https:\/\/doesnotmatter.eu/download",
        "customclient_ios": "https:\/\/doesnotmatter.eu/download",
        "datadirectory": "\/srvdata\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.1.6.2",
        "dbtableprefix": "oc_",
        "installed": true,
        "loglevel": "0",
        "forcessl": false,
        "maxZipInputSize": 524288000,
        "allowZipDownload": true,
        "defaultapp": "files",
        "knowledgebaseenabled": "true",
        "knowledgebaseurl": "https:\/\/doesnotmatter.eu",
        "appstoreenabled": false,
        "appcodechecker": "true",
        "mail_domain": "doesnotmatter.eu",
        "allow_user_to_change_display_name": "false",
        "updatechecker": false,
        "default_language": "en",
        "theme": "default",
        "mail_smtpmode": "php",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": 25,
        "mail_smtptimeout": 10,
        "mail_smtpsecure": "",
        "mail_smtpauth": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "log_type": "syslog",
        "logfile": "",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "dbname": "doesnotmatter",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "trusted_domains": [
            "doesnotmatter.eu",
        ],
        "has_internet_connection": false,
        "supportedDatabases": [
            "mysql",
            "pgsql",
            "oci"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src 'self';",
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "127.0.0.1",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 2
        }
    }
}

```

**List of activated apps:**

Enabled:
  - activity: 2.3.2
  - admin_audit: 0.7
  - calendar: 1.4.1
  - comments: 0.3.0
  - contacts: 1.5.1
  - dav: 0.2.7
  - direct_menu: 0.9.2
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firewall: 2.4.0
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - rainloop: 5.0.0
  - systemtags: 0.3.0
  - systemtags_management: 0.2.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - windows_network_drive: 0.2.33
  - workflow: 0.2.3

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
(does not matter, because CLI, but Chrome Version 58.0.3029.110 (64-bit)

**Operating system:**
Linux

#### Web server error log
No errors

#### ownCloud log (data/owncloud.log)
Only one relevant line in log
02:50:02 (2017-06-12) xxx.doesnotmatter.eu [user.debug] ownCloud[11609]: {cron} Started background job of class : OCA\DAV\CardDAV\SyncJob with arguments :

#### Browser log
CLI/server side issue, browser logs not relevant

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
