### ISSUE TITLE
After OwnCloud 8.2.11 to 9.0.10 upgrade, Contacts and Calendars hang.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [owncloud/core#28136]
I've been working on this for some time with my partner. 

I managed to get it to work where: Documents, Tasks, Notes  Gallery, Files, and Activity seem to work fine. After a bunch of manual  MySQL editing. File Sync works.

The Contact and Calendar apps semi-hang when being accessed. The page can be navigated away from. Thunderbird displays OwnCloud Contacts over CalDAV/CardDav. Somehow that still works. Calendars do not to the best of my knowledge. 

apps installed are as followed.

php occ app:list
PHP Warning:  can't find symbol in Unknown on line 0
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.1
  - dav: 0.2.7
  - documents: 0.13.1
  - encryption: 1.3.0
  - external: 1.2
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: 0.9.0.0
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_external: 0.4
  - user_ldap: 0.9.0
Disabled:
  - bookmarks

I have two systems in roughly the same configuration. On the working system, attempting to navigate to the dav share results in:

This is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client.

on the non-working system:

I get the OwnCloud Wallpaper and: App not installed: 
No app is specified.
# cat /var/lib/owncloud/owncloud.log 
{"app":"PHP","message":"Class 'OC_Appconfig' not found at \/usr\/share\/owncloud\/lib\/private\/app.php#145","level":3,"time":"2014-12-16T15:44:22+00:00"}

Both machines have run the same OS and have identicle PHP and Apache versions

**Comment by kdslkdsaldsal** [comment]
``
{"app":"PHP","message":"Class 'OC_Appconfig' not found at /usr/share/owncloud/lib/private/app.php#145","level":3,"time":"2014-12-16T15:44:22+00:00"}
``

Nothing else in the logs as this entry is from 2014?

Some hints what could be wrong here:

1. You're using Internet Explorer / Edge which are not supported by both apps
2. You have some broken calendar and contacts entries in your database -> https://central.owncloud.org/t/calendar-could-not-be-synced-or-exported/850
3. Your WebDAV interface is broken on the not working instance -> https://central.owncloud.org/t/how-to-fix-caldav-carddav-webdav-problems/852

**Comment by Zombie-Ryushu** [comment]
1. I am not using internet explorer or Edge on Windows (all Linux)
2. the oc_celendarobjects table is completely devoid of any entries, its an empty table.
3. I think webdav is in some at least partially functional state.

**Comment by Zombie-Ryushu** [comment]
$ php occ dav:migrate-calendars
PHP Warning:  can't find symbol in Unknown on line 0
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
                                            
  [OCA\Dav\Migration\NothingToDoException]  
  Calendar tables are missing

**Comment by kdslkdsaldsal** [comment]
http://morrisjobke.de/2016/03/07/ownCloud-9.0-calendar-migration-analysis/ might give you some help

**Comment by Zombie-Ryushu** [comment]
Sorry this took so long for me to close. 
public_webdav 	dav/appinfo/v1/publicwebdav.php
remote_webdav 	dav/appinfo/v1/webdav.php
being missing turned out to be the problem. After adding those entries, ownCloud functions as intended.

**Comment by kdslkdsaldsal** [comment]
@Zombie-Ryushu Mhhh, the question is still why you're missing those. IIRC there was a similar report somehwere in here but i currently can't find it. :-/

**Comment by Zombie-Ryushu** [comment]
I can't answer that question, I just know that this issue affected only one of my two syetems.
