### ISSUE TITLE
After upgrade to 10.0, only apps from marketplace show up, and after Web Update to 10.0.0.2, NONE of the apps show up and it lists all the app files as extras.  Don't like the direction this is taking at all.

### ISSUE THREAD

**Issue by 4nanook** [owncloud/core#28137]
### Steps to reproduce
1. Upgrade to 10.0, I did by saving data and config and replacing everything else with tar file.
2. Now only marketplace apps are visible.
3. Update via the Web Update, then NO apps are visible and all app files are extra.

### Expected behaviour
Tell us what should happen

Apps that are compatible should remain visible.
No valid app files should be shown as "extra".

### Actual behaviour
Tell us what happens instead

No Apps show up.
Lists file corrupt with all the app files being "extra".

### Server configuration
**Operating system**:
Ubuntu 17.04

**Web server:**
apache 2.4.25

**Database:**
MySQL Community 5.7

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
10.0.0.2

**Updated from an older ownCloud or fresh install:**
Fresh install of 10.0, upgrade to 10.0.0.2 via web upgrade

**Where did you install ownCloud from:**
owncloud.org

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

Would not allow me to paste.
**The content of config/config.php:**

Not putting my information in the public.
```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by kdslkdsaldsal** [comment]
Could be related to the bug in the updater app here? https://github.com/owncloud/updater/pull/430

**Comment by kdslkdsaldsal** [comment]
Ah, and the market app (which shows the apps in ownCloud) has an own repository where you might need to re-open this issue about the "app files as extra" : https://github.com/owncloud/market/issues

**Comment by VicDeo** [comment]
@4nanook could you please clarify `it lists all the app files as extras`?

**Comment by 4nanook** [comment]
Yes, all list as extras.

-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Eskimo North Linux Friendly Internet Access, Shell Accounts, and Hosting.
    Knowledgeable human assistance, not telephone trees or script readers.
  See our web site: http://www.eskimo.com/ (206) 812-0051 or (800) 246-6874.

**Comment by PVince81** [comment]
Can you post a screenshot ?

**Comment by PVince81** [comment]
closing due to lack of feedback.

You might want to try again with 10.0.3.
