### ISSUE TITLE
Update sabre-http to 4.2.3 to workaround download issues on 32bit systems

### ISSUE THREAD

**Issue by ghost** [owncloud/core#28133]
This is a follow-up of https://github.com/owncloud/core/issues/23788 and https://github.com/owncloud/core/issues/27395 which shows download issues on 32bit linux systems (like the PI) when downloading files larger then 2GB.

https://github.com/fruux/sabre-http/issues/77 which lead to a workaround in https://github.com/fruux/sabre-http/issues/74 is now included / released in sabre-http 4.2.3.

**Comment by kdslkdsaldsal** [comment]
It looks that ownCloud 10.0.2 has currently sabre-http 4.2.1:

https://github.com/owncloud/3rdparty/blob/v10.0.2/sabre/http/CHANGELOG.md

There was one additional fix in 4.2.2:

https://github.com/fruux/sabre-http/blob/4.2/CHANGELOG.md
https://github.com/fruux/sabre-http/issues/72

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
