### ISSUE TITLE
Why do you always put on updates that NEVER work?

### ISSUE THREAD

**Issue by Sequential-circuits** [owncloud/core#28130]
I have been using owncloud for the past 2 or 3 years and NEVER any update worked: I always ended up having to do a clean reinstall and pulling back all the data from the clients

Honestly guys, put on some work on that, at this rate I will go to the competitor!

Updating to 10.0.2

OC\RepairException: Upgrade is not possible

        Repair warning: Exception
        Repair warning: App directory already exists
        Repair warning: Exception
        Repair warning: App directory already exists
        Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
        Repair warning: please install app manually with tarball or disable them with: occ app:disable activity occ app:disable gallery

Detailed logs
Preparing update
Set log level to debug
Turned on maintenance mode
Repair warning: Exception
Repair warning: App directory already exists
Repair warning: Exception
Repair warning: App directory already exists
Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Repair warning: please install app manually with tarball or disable them with: occ app:disable activity occ app:disable gallery
OC\RepairException: Upgrade is not possible
The update was unsuccessful. Please report this issue to the ownCloud community.

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by tomneedham** [comment]
@Sequential-circuits Sorry to hear about your issues with updates. The best thing you can do is help test the updates and feedback on github, and produce useful issue reports, like this one! Thanks :)

Looking at your specific output from the upgrade, it actually looks like it performed as intended here. Upon upgrade we check if all of the apps that you have installed are compatible with the new version, try to update any via the app store, but stop the upgrade if they are not updatable.

The interesting thing here is why gallery and activity are listed as incompatible, since they are both available on the marketplace. Did you allow the marketplace to update apps during the install? If not, then you will need to manually update these by disabling them, updating owncloud and then downloading the from the marketplace.

**Comment by tomneedham** [comment]
Please could you also show us the related owncloud.log entries.

**Comment by kdslkdsaldsal** [comment]
> Repair warning: Exception
> Repair warning: App directory already exists
> Repair warning: Exception
> Repair warning: App directory already exists

Looks more like a not correctly done upgrade by just copying over the old files over the new ones without deleting the old content first.

If all previous upgrades where done with that it might explain why every previous upgrade was failing for you.

**Comment by PVince81** [comment]
For the record, updates have been tested here https://github.com/owncloud/administration/pull/132 so it is likely a problem specific to your environment or the way you did the upgrade which is not following the documentation.

**Comment by DeepDiver1975** [comment]
https://owncloud.org/community/code-of-conduct/ -> close
