### ISSUE TITLE
Add warning in admin page about running with debug flag

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#28157]
Running with "debug" flag on can lead to issues like:
- files served over remote.php/webdav are served without content-disposition attachment to make debugging easier (not sure why though, chromium can handle it fine)
- QueryLogger is going to eat up a lot of memory

@butonic @DeepDiver1975

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/core/pull/29910
