### ISSUE TITLE
"Allow editing" in public shares, is not saved as enabled

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#28154]
### Steps to reproduce
1. On a folder: Sharing -> Public Links -> Create Public Link
2. Enable "Allow Editing" 
3. Save the Public Link
4. Open the Public Link (edit icon)

### Expected behaviour
"Allow editing" is enabled

### Current behaviour
"Allow editing" is not enabled

### Server configuration
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.2.1","versionstring":"10.0.2","edition":"Enterprise","productname":"ownCloud"}

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/core/issues/28057 ?

**Comment by jesmrec** [comment]
yes, it is the same. I only filtered by opened issues. So, it's fixed in daily. 

closing...
