### ISSUE TITLE
disable UI while link-creation

### ISSUE THREAD

**Issue by moritzha** [owncloud/core#28163]
### Steps to reproduce
1. Search for large encrypted folder
2. Create Link with password
3. Wait...

### Expected behaviour
Instant link creation or some kind of sign for work in progress.
Maybe the ui should be greyd/ disabled until the content is encrypted
and the action is completed.

### Actual behaviour
After clicking save nothing changes in the ui. It feels like the server isn't responding
or broken. With clicking cancel the ui is usable again, but you'll not get notified if the action is completed.

**Comment by PVince81** [comment]
Indeed, link creation for encryption takes longer because it needs to create share keys for every file inside.

So in general a spinner would make sense there. @felixheidecke

**Comment by felixheidecke** [comment]
I will take it over.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
