### ISSUE TITLE
theming l10n translation

### ISSUE THREAD

**Issue by felixboehm** [owncloud/core#28167]
tried to customize a translation via theme

### Steps to reproduce
1. mkdir -p themes/myTheme/core/l10n
2. cp core/l10n/en_GB.js* themes/myTheme/core/l10n/
3. vim themes/myTheme/core/l10n/en_GB.js # change some 
4. configure theme in config.php
5. load page and filter network for en_GB files
6. switch to the correct language in personal settings

### Expected behaviour
Custom strings are used.
The en_GB.js file for "core" should come from theme

### Actual behaviour
Custom strings are not used

Two en_GB.js files for "core" are loaded
- http://localhost/core/l10n/en_GB.js?v=9ab0ff1745e8dcd07cefb190b7891a57
- http://localhost/themes/myth//core/l10n/en_GB.js?v=9ab0ff1745e8dcd07cefb190b7891a57

Note double slash in second

### Other
ownCloud 10.0.3
No log entries

**Comment by felixboehm** [comment]
Please recheck and consider writing acceptance tests for this. @SergioBertolinSG 
If you find the same behavior, let's fix this.

**Comment by felixboehm** [comment]
theming apps doesn't work anymore either??

**Comment by DeepDiver1975** [comment]
> theming apps doesn't work anymore either??

cannot reproduce.

just enabled a theme and it loads just fine.

will have a look at translations ....

**Comment by DeepDiver1975** [comment]
> will have a look at translations ....

the new app based theming is not respected in loading themed translations .... needs a deeper look.

furthermore translations are loaded even before the theme app is loaded

**Comment by DeepDiver1975** [comment]
on loading of the js translation files theme path is completly ignores ....

**Comment by DeepDiver1975** [comment]
according to @phisch fixed with #27746

**Comment by felixboehm** [comment]
thanks

**Comment by PVince81** [comment]
and https://github.com/owncloud/core/pull/27746 is still open

**Comment by DeepDiver1975** [comment]
> according to @phisch fixed with #27746

just tested this and this is not fixed ...

**Comment by PVince81** [comment]
p3, moving to "planned" for now

**Comment by glannes31** [comment]
Hello, any idea for the fix date ?

**Comment by tomneedham** [comment]
Breaks branding which is important for big installations upgrading to 10

**Comment by VicDeo** [comment]
js part works fine with l10n from themes.
the bug in php translation only.

**Comment by VicDeo** [comment]
...and now I'm facing that apps with type `theme` should be loaded before any other kind of apps

another solution is to lazy-load active app-themes inside `\OC\L10N\Factory` but it's a hacky way to go.

**Comment by VicDeo** [comment]
@felixboehm I see two issues from your description.
> vim themes/myTheme/core/l10n/en_GB.js # change some

`en_GB.js` is a **frontend** translation file. It's not enough to translate this file only, as it has a **backend** companion `en_GB.json`. Both files should be translated.

**Comment by VicDeo** [comment]
Fix will be released with 10.0.5
