### ISSUE TITLE
No connection to marketplace: Bad Gateway

### ISSUE THREAD

**Issue by jzuijlek** [owncloud/core#28162]
When starting the upgrade I get:

`Repair warning: No connection to marketplace: GuzzleHttp\Exception\ServerException: Server error response [url] https://storage.marketplace.owncloud.com/apps/activity-2.3.4.tar.gz?X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=8BXV1F3LCCSC9Z946NYU%2F20170620%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170620T062046Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1200&X-Amz-Signature=fccd1752ac76847fb0c7438b404d33bf93aa0a3704e39ae69997438f782d0618 [status code] 502 [reason phrase] Bad Gateway in /var/www/owncloud/lib/composer/guzzlehttp/guzzle/src/Exception/RequestException.php:89 Stack trace: #0 /var/www/owncloud/lib/composer/guzzlehttp/guzzle/src/Subscriber/HttpError.php(32): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Message\Response)) #1 /var/www/owncloud/lib/composer/guzzlehttp/guzzle/src/Event/Emitter.php(108): GuzzleHttp\Subscriber\HttpError->onComplete(Object(GuzzleHttp\Event\CompleteEvent), 'complete') #2 /var/www/owncloud/lib/composer/guzzlehttp/guzzle/src/RequestFsm.php(91): GuzzleHttp\Event\Emitter->emit('complete', Object(GuzzleHttp\Event\CompleteEvent)) #3 /var/www/owncloud/lib/composer/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction)) #4 /var/www/owncloud/lib/composer/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array) #5 /var/www/owncloud/lib/composer/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL) #6 /var/www/owncloud/lib/composer/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL) #7 /var/www/owncloud/lib/composer/guzzlehttp/guzzle/src/RequestFsm.php(134): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure)) #8 /var/www/owncloud/lib/composer/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction)) #9 /var/www/owncloud/lib/composer/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array) #10 /var/www/owncloud/lib/composer/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL) #11 /var/www/owncloud/lib/composer/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL) #12 /var/www/owncloud/lib/composer/guzzlehttp/guzzle/src/RequestFsm.php(134): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure)) #13 /var/www/owncloud/lib/composer/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction)) #14 /var/www/owncloud/lib/composer/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array) #15 /var/www/owncloud/lib/composer/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL) #16 /var/www/owncloud/lib/composer/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL) #17 /var/www/owncloud/lib/composer/guzzlehttp/guzzle/src/RequestFsm.php(134): GuzzleHttp\Message\FutureResponse::proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure)) #18 /var/www/owncloud/lib/composer/guzzlehttp/guzzle/src/Client.php(165): GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction)) #19 /var/www/owncloud/lib/composer/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request)) #20 /var/www/owncloud/lib/private/Http/Client/Client.php(136): GuzzleHttp\Client->get('http://marketpl...', Array) #21 /var/www/owncloud/apps/market/lib/MarketService.php(380): OC\Http\Client\Client->get('http://marketpl...', Array) #22 /var/www/owncloud/apps/market/lib/MarketService.php(145): OCA\Market\MarketService->httpGet('http://marketpl...', Array) #23 /var/www/owncloud/apps/market/lib/MarketService.php(88): OCA\Market\MarketService->downloadPackage('activity') #24 /var/www/owncloud/apps/market/lib/Listener.php(46): OCA\Market\MarketService->installApp('activity', true) #25 /var/www/owncloud/apps/market/lib/Application.php(54): OCA\Market\Listener->reinstallAppStoreApp('activity') #26 [internal function]: OCA\Market\Application->OCA\Market\{closure}(Object(Symfony\Component\EventDispatcher\GenericEvent), 'OCP\\Migration\\I...', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #27 /var/www/owncloud/lib/composer/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Object(Closure), Object(Symfony\Component\EventDispatcher\GenericEvent), 'OCP\\Migration\\I...', Object(Symfony\Component\EventDispatcher\EventDispatcher)) #28 /var/www/owncloud/lib/composer/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'OCP\\Migration\\I...', Object(Symfony\Component\EventDispatcher\GenericEvent)) #29 /var/www/owncloud/lib/private/Repair/Apps.php(203): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('OCP\\Migration\\I...', Object(Symfony\Component\EventDispatcher\GenericEvent)) #30 /var/www/owncloud/lib/private/Repair/Apps.php(144): OC\Repair\Apps->getAppsFromMarket(Object(OC\Repair), Array, 'reinstallAppSto...') #31 /var/www/owncloud/lib/private/Repair.php(88): OC\Repair\Apps->run(Object(OC\Repair)) #32 /var/www/owncloud/lib/private/Updater.php(221): OC\Repair->run() #33 /var/www/owncloud/lib/private/Updater.php(108): OC\Updater->doUpgrade('10.0.2.1', '10.0.0.12') #34 /var/www/owncloud/core/ajax/update.php(190): OC\Updater->upgrade() #35 {main}
Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Repair warning: please install app manually with tarball or disable them with: occ app:disable activity occ app:disable files_pdfviewer occ app:disable files_texteditor occ app:disable gallery`

**Comment by DeepDiver1975** [comment]
known issue - we are working on this - see https://github.com/owncloud/marketplace-issues/issues/6
