### ISSUE TITLE
Update output of the occ command to be more context-aware.

### ISSUE THREAD

**Issue by settermjd** [owncloud/core#28176]
### Steps to reproduce

Download the latest copy of ownCloud (10), uncompress the archive, and `cd` to the directory.
Run `sudo -u apache php occ maintenance:install`.

### Actual behaviour

```console
sudo -u apache php occ maintenance:install
ownCloud is not installed - only a limited number of commands are available
What is the password you like to use for the admin account <admin>?
```
### Expected behaviour

I'd expect that, as you're installing ownCloud for the first time, that: `ownCloud is not installed - only a limited number of commands are available` would not be output. At this point you know ownCloud's not installed — because you're installing it :-D

### Server configuration

**Operating system**: RedHat 7

**Web server:** Apache 2.4

**Database:** (none installed at the time)

**PHP version:** 7.0.10

**ownCloud version:** 10.0.2

**Updated from an older ownCloud or fresh install:** performing a fresh install

**Where did you install ownCloud from:** n/a

### Client configuration
**Browser:** n/a

**Operating system:** macOS (host)

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/28945
