### ISSUE TITLE
Allow sending public share emails via OCS API

### ISSUE THREAD

**Issue by MaggiWuerze** [owncloud/core#28170]
Will you add the capability to trigger a notification email with the link to the share via the OCS API in OwnCloud v10?
Currently i can create a new share and the response even tells me if a notification mail has been send but i can't trigger it like i can with the GUI.

**Comment by PVince81** [comment]
No, no plans.

If you need it feel free to submit a PR for this.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
