### ISSUE TITLE
SMBv1 Protocol for SMB/CIFS

### ISSUE THREAD

**Issue by raphson93** [owncloud/core#28184]
Hi, windows 10 is going to remove smbv1 protocol for the next update and I'm sure it will definitely affect the SMB/CIFS features on windows platform.
Any idea for this ?

**Comment by kdslkdsaldsal** [comment]
I think this question better belongs to https://github.com/eduardok/libsmbclient-php/issues, which is the library used by ownCloud.

There you can e.g. also find https://github.com/eduardok/libsmbclient-php/issues/53 which is about disabling SMBv1

**Comment by raphson93** [comment]
Thanks @kdslkdsaldsal 
I set it based on the settings provided and it is working perfectly.
