### ISSUE TITLE
Update to 10.0.2

### ISSUE THREAD

**Issue by mfonhof** [owncloud/core#28205]
Hello,

I think i need to report this error here. But i am not sure.

I tried to update to 10.0.2 and i got an "Base table or view already exists: 1050 Table 'oc_external_mounts' already exists".
An existing table. Not uncommon in a update.

Log: (Ignore the Dutch)
Update voorbereiden
Logniveau instellen op debug
Onderhoudsmodus ingeschakeld
Database schema aan het updaten
Database bijgewerkt
Bijgewerkt "files_pdfviewer" naar 0.8.2
Bijgewerkt "files_texteditor" naar 2.2
Bijgewerkt "gallery" naar 16.0.2
Bijgewerkt "activity" naar 2.3.4
Bijgewerkt "dav" naar 0.2.9
files_external: An exception occurred while executing 'CREATE TABLE `oc_external_mounts` (`mount_id` BIGINT AUTO_INCREMENT NOT NULL, `mount_point` VARCHAR(128) NOT NULL, `storage_backend` VARCHAR(64) NOT NULL, `auth_backend` VARCHAR(64) NOT NULL, `priority` INT DEFAULT 100 NOT NULL, `type` INT NOT NULL, PRIMARY KEY(`mount_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_external_mounts' already exists

**Comment by kdslkdsaldsal** [comment]
@mfonhof https://github.com/owncloud/core/issues/27939 and https://github.com/owncloud/core/issues/27822 are existing issues about this which all lead to a not correctly done upgrade by copying the old code over the new one without deleting the old code fist.

**Comment by mfonhof** [comment]
Ok. Sorry and thanx.

No, i did not provided the steps. I was not aware of these issue numbers.

**Comment by kdslkdsaldsal** [comment]
Ok, so this should be simple fixable by:

1. Deleting all files and folders except /data and /config
2. Extract the owncloud 10.0.2 archive into your installation folder
3. Re-run the upgrade

You can have a look at https://doc.owncloud.org/server/10.0/admin_manual/maintenance/manual_upgrade.html for further / more details.
