### ISSUE TITLE
Disallow old chunking on new endpoint

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#28200]
With old chunking we mean the ugly file names like "data1.dat-chunking-3886638851-13-1".

Whenever a client sends "OC-Chunking" header, deny access to the new endpoint "remote.php/dav/files/$user".

@DeepDiver1975 as discussed

This would help reducing test cases.

**Comment by guruz** [comment]
Please only after new enough clients are in the wild e.g. for https://github.com/owncloud/client/issues/5855

;)

**Comment by PVince81** [comment]
Depends... it is likely that old clients cannot work anyway due to this bug https://github.com/owncloud/core/issues/28197. So either we invest time in fixing old chunking with new dav (that if-match thing) or block it right away.

That is, unless we find scenarios where it does work correctly still.

**Comment by mrow4a** [comment]
@PVince81 should I write a PR with what you need on the server? I will also include smashbox test verifying all these issues.

**Comment by mrow4a** [comment]
Ok, I think forbiding new endpoint for old chunking is "must have"... it is probably better then investigating how to write a test how to play with aborded chunking and overwriting in crazy scenarious in smashbox.. will take care of it.

**Comment by PVince81** [comment]
Possible technical approaches:

1. one size fits all: write a plugin that denies any request on the new DAV endpoint if OC-Chunking is set

or

2. go through every possible code path that have "OC-Chunking" set and add a check whether we're coming from the new dav endpoint. Might require adding a flag in the plugin that the instantiator tells in which endpoint we are.

**Comment by mrow4a** [comment]
I like number 1 :+1:

**Comment by mrow4a** [comment]
https://github.com/owncloud/core/pull/28263

**Comment by mrow4a** [comment]
@PVince81 close?
