### ISSUE TITLE
owcCloud 9.1.6: problem with gallery

### ISSUE THREAD

**Issue by FeliceMente** [owncloud/core#28201]
I'm testing ownClod 9.1.6 using the official owncloud/server:9.1.6 docker images.

I noticed a problem when going to the galley app and immediately clicking, from the root, on the home icon: the icon start spinng and then when page seems to hang (the plus icon no longer works, and so on...).

This doesn't happen if I go to the gallery, click on an image, then on home and then on home again.

**Comment by PVince81** [comment]
https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

**Comment by PVince81** [comment]
please use the issue template and raise in https://github.com/owncloud/gallery
