### ISSUE TITLE
Draw.io diagramm opened with text editor when the file is set as favorite

### ISSUE THREAD

**Issue by DiGGeR2** [owncloud/core#28211]
### Steps to reproduce
1. Create a new diagramm (with Draw.io app instaled)
2. Make the saved diagram as favorit document
3. Open this diagram in the favorit folder... It's open with XML viewer :(

### Expected behaviour
The XML should open with the Draw.io app like it is when document is not in favorit folder

### Actual behaviour
The XML document is opened with the integrated text editor

### Server configuration

**ownCloud version: 12.0.0

**Updated from an older ownCloud or fresh install: fresh install

**Comment by kdslkdsaldsal** [comment]
> **ownCloud version: 12.0.0

Sure that you're using ownCloud? There is no 12.0.0 version for ownCloud as well as no Draw.io app available for oC.

**Comment by DiGGeR2** [comment]
Woooop sorry... wrong github project :)
