### ISSUE TITLE
"Activity notification" email should contain link

### ISSUE THREAD

**Issue by spaceone** [owncloud/core#28227]
I received an email with subject "Activity notification" containing the information:
```
Hello XYZ,
You are receiving this email because the following things happened at /

* Foo Bar shared Shared/foobar.png with you - Today at 9:14:02 AM
```

This doesn't help me as long as there is no link to the owncloud site where I can reach this file.

**Comment by PVince81** [comment]
raised in https://github.com/owncloud/activity/issues/580
