### ISSUE TITLE
Owncloud Update problem

### ISSUE THREAD

**Issue by first0nt0p** [owncloud/core#28228]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
Using the built in update method the following was what was seen_

===================================================================

Updating ownCloud to version 8.1.12, this may take a while.

Set log level to debug - current level: "Warning"
Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "files_pdfviewer" to 0.7.1
Updated "files_sharing" to 0.6.3
Exception: App can't be installed because it is not compatible with this version of ownCloud
===================================================================
Sitting now without access to my site...

**Comment by kdslkdsaldsal** [comment]
Can you provide the steps you have done to do this update/upgrade?

**Comment by first0nt0p** [comment]
Yes - I went to the Admin area of my Cloud site.
I then selected the automatic update.
I believe it carried out a system backup.
It then started the update.
It did not run for long before it reported back with a problem.
The problem is that now, I can not get entry to my cloud site as it is now showing an error page - attached as an image.
![image](https://user-images.githubusercontent.com/29730231/27587306-cb325eec-5b3b-11e7-9c41-476efdc10caf.png)
If I try and gain entry to the system, at any point, I see the same page.
Thanks.

**Comment by kdslkdsaldsal** [comment]
I think the usage of the old updater app (prior to 9.0.x) is highly discouraged as that app is seriously broken in such older releases.

The best way to fix your instance is to:

1. Remove all files and folders except /data/ and /config/ from your installation folder
2. Upload the latest point release of your current installed oC version (e.g. 8.0.16 if you had 8.0.x, 8.1.12 if you had 8.1.x installed) to your installation folder
3. Run the update/upgrade routine from your webbrowser / via occ upgrade shown in your screenshot

Repeat those steps for each major release, e.g.:

8.0.x -> latest 8.0.x -> latest 8.1.x -> latest 8.2.x -> latest 9.0.x -> latest 9.1.x (i wouldn't go for 10.x currently and wait for at least 10.0.3)

**Comment by PVince81** [comment]
for further assistance, see https://owncloud.org/support/
