### ISSUE TITLE
tests/lib is really unit tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#28233]
The code in core tests/lib are actual "unit" tests (some might technically be called integration tests where they test interworkings of multiple classes).

It would be handy to have the folder name tests/lib available to put common test infrastructure code to be shared by various tests across the system (e.g. shared by API and UI style acceptance tests...)

As a first step to doing that, rename tests/lib to tests/unit - then the purpose of that folder will be clearer, as well as making the tests/lib name available for re-use.

**Comment by PVince81** [comment]
close ?

**Comment by phil-davis** [comment]
Yes, this is no longer relevant.
