### ISSUE TITLE
Add functionality to set global credentials via CLI.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#28231]
Currently files_external can only get global credentials from the web ui. I suggest to include an option to add this type of credentials via command line (occ).

![screen shot 2017-06-27 at 16 49 37](https://user-images.githubusercontent.com/9048796/27593911-b99be2d0-5b58-11e7-8bb0-801401780067.png)

cc @pmaier1

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
