### ISSUE TITLE
Calendar integrity check failed when upgrading from 9.0 to 9.1.6

### ISSUE THREAD

**Issue by siick** [owncloud/core#28247]
### Steps to reproduce
1. Updating Owncloud to version 9.1

### Expected behaviour
Calendar should work in the same way as before

### Actual behaviour
Code integrity check failed, a warning with that message came up.
Click on 'list invalid files' shows Exception for calendar.

### Server configuration
**Operating system**: 
Ubuntu 16.04
**Web server:**
Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g
**Database:**
mysql  Ver 14.14 Distrib 5.7.18, for Linux (x86_64) using  EditLine wrapper
**PHP version:**
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
**ownCloud version:** (see ownCloud admin page)
ownCloud 9.1.6 (stable)
**Updated from an older ownCloud or fresh install:**
Owncloud 9.0
**Where did you install ownCloud from:**
Your repository
**Signing status (ownCloud 9.0 and above):**

```
Results
=======
- calendar
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate has been revoked.

Raw output
==========
Array
(
    [calendar] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate has been revoked.
                )

        )

)
```
In your documentation (https://doc.owncloud.org/server/9.1/admin_manual/issues/code_signing.html#fixing-invalid-code-integrity-messages) you mention  "Contact the developer of the application. A new version of the app containing a valid signature file needs to be released."
Someone does it here -> https://github.com/nextcloud/calendar/issues/498
But the developer seems to say it's YOUR problem and not HIS problem.... this is his comment -> https://github.com/nextcloud/calendar/issues/498#issuecomment-306311302

So what can i do now? I don't want to disable integrity check to make it work again

**Comment by kdslkdsaldsal** [comment]
@siick This is known and an issue with the calendar app. You can close here and jump over to https://github.com/owncloud/calendar/issues/800 to see all existing info.
