### ISSUE TITLE
Users List is not showing all the LDAP users.

### ISSUE THREAD

**Issue by UnMenorqui** [owncloud/core#28244]
### Steps to reproduce
1. Connect LDAP to Owncloud
2. Once the Users LDAP query is done
3. Go to Users List with admin account
4. Only the users that have accessed the service are listed. 

Actually on the previous version of Owncloud, the user's list was shown with all the users of the LDAP query. But actually only the ones that accessed the server are displayed. Is this on purpose?

I need to see all the others users to configure things properly, and there is no way to pre-create an user. It just duplicates it locally.

Thank you in advance,

### Server configuration
**Operating system:** Ubuntu 16.04.2 LTS

**Web server:** Apache/2.4.18 (Ubuntu)

**Database:** Mysql  Ver 15.1 Distrib 10.0.29-MariaDB, for debian-linux-gnu (x86_64)

**PHP version:** PHP 5.6

**ownCloud version:** Owncloud 10.0.1

**Updated from an older ownCloud or fresh install:** Updated from an older installation, Owncloud 9.1.4

**Where did you install ownCloud from:** Manually installed Owncloud using the owncloud.zip given at the Owncloud page, and also manually updated the server succesfully without errors.

**The content of config/config.php(With config credentials omited due to security):**
```
<?php
$CONFIG = array (
  'instanceid' => '***********************************',
  'passwordsalt' => '************************************',
  'secret' => '***********************************',
  'trusted_domains' =>
  array (
    0 => 'nuvol.fib.upc.edu',
    1 => 'nuvol.fib.upc.es',
    2 => 'owncloud.fib.upc.edu',
  ),
  'datadirectory' => '/dadesOwnCloud',
  'overwrite.cli.url' => 'https://nuvol.fib.upc.edu',
  'dbtype' => 'mysql',
  'version' => '10.0.1.5',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '***********************************',
  'dbpassword' => '***********************************',
  'logtimezone' => 'UTC',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'appstore.experimental.enabled' => true,
  'mail_from_address' => 'noreply',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'fib.upc.edu',
  'maintenance' => false,
  'lost_password_link' => 'https://identitatdigital.upc.edu/gcredencials/init/',
  'loglevel' => 0,
  'log_type' => 'syslog',
  'syslog_tag' => 'owncloud',
  'logdateformat' => 'F d, Y H:i:s',
  'log_query' => false,
  'cron_log' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'trashbin_retention_obligation' => 'auto',
  "default_language" => "en_GB",
);
```

**Comment by butonic** [comment]
you can use occ user:sync to sync all users from ldap to owncloud.

**Comment by butonic** [comment]
also see https://doc.owncloud.org/server/10.0/admin_manual/configuration_server/occ_command.html?highlight=sync#ldap and https://doc.owncloud.org/server/10.0/admin_manual/release_notes.html#known-issues under 5.:
```
5. Existing LDAP users will only show up in the user management page and in the share dialog after they have been synced. The account table introduced in ownCloud 10.0.0 significantly reduces LDAP communication overhead. Password checks are yet to be accounted for. LDAP user metadata in the account table will be updated when users log in or when the administrator runs occ user:sync "OCA\User_LDAP\User_Proxy". We recommend `setting up a nightly Cron job`_ to keep metadata of users not actively logging in up to date.
```

**Comment by UnMenorqui** [comment]
Thank you so much!

Best Regards,
