### ISSUE TITLE
Documentation latest file not found [developer manual]

### ISSUE THREAD

**Issue by thoresuenert** [owncloud/core#28240]
Hi,
the documentation link for developer is not working:
[https://doc.owncloud.org/server/latest/developer_manual/](https://doc.owncloud.org/server/latest/developer_manual/) 
[https://doc.owncloud.org/server/latest/ownCloudDeveloperManual.pdf](https://doc.owncloud.org/server/latest/ownCloudDeveloperManual.pdf)
both give 404

**Comment by PVince81** [comment]
@settermjd likely duplicate of known infrastructure issue ?

**Comment by cortho** [comment]
This has been fixed with https://github.com/owncloud/documentation/issues/3185

**Comment by kdslkdsaldsal** [comment]
So closing as this is solved.
