### ISSUE TITLE
OC 10.0.1: No "Remeber Me"-Checkbox on loginpage (encryption and ext storage DISABLED)

### ISSUE THREAD

**Issue by Commifreak** [owncloud/core#28258]
### Steps to reproduce
1. Logout (if logged in)
2. Open Login page

### Expected behaviour
Remember Me-Checkbox should be visible

### Actual behaviour
The Remember-Me Checkbox is not visible.

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache 2.4

**Database:** MySQL

**PHP version:** 5.5

**ownCloud version:** 10.0.1

**Updated from an older ownCloud or fresh install:** Updated from older

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 


No errors have been found.
```

**The content of config/config.php:**

```
https://gist.github.com/Commifreak/2254e12b06aa6d3e50cb44e41c37abe3
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 55

**Operating system:** Windows 10

The default apps are enabled - but the RememberMe Hceckbox is still not visible - whats causing this?

![grafik](https://user-images.githubusercontent.com/87267/27680178-357fc0ac-5cbb-11e7-916a-67eb569b5529.png)

**Comment by kdslkdsaldsal** [comment]
Stay logged in box is currently not working at all: https://github.com/owncloud/core/issues/26027

Reason why the box is not shown: https://github.com/owncloud/core/issues/26027#issuecomment-310674880, https://github.com/owncloud/core/pull/27051#issuecomment-308677115
