### ISSUE TITLE
LDAP user mapping broken / cannot login with new users

### ISSUE THREAD

**Issue by mwichern** [owncloud/core#28267]
Hello,

i've migrated our owncloud instance from old debian jessie release with php 5.6 to a new base system based on debian 9 stretch with apache 2.4 and php 7.0.
for the migration of owncloud i followed the steps described in the official manual.
our problem is by login new created user. we're using active directory backend auth.
before i've migrated owncloud to the new server, i only had to set the user member of a specified active directory group (owncloud-benutzer). than the user can login.
on the new system the user cannot login. after some time of researching i found, that the column 'owncloud_name' in table oc_ldap_user_mapping is not set. when i copy the id from 'directory_uuid' to the 'owncloud_name' column the user can login.

is this a configuration mistake or a bug?

### Server configuration
**Operating system**:
Debian 9.0

**Web server:**
Server version: Apache/2.4.25 (Debian)
Server built:   2017-01-25T22:59:26

**Database:**
mysql-server                       5.1.66-0+squeeze1

**PHP version:**
PHP 7.0.20-1~dotdeb+8.1 (cli) ( NTS )

**ownCloud version:** (see ownCloud admin page)
version: 10.0.2.1

**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**
tar-ball

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**The content of config/config.php:**
{
    "system": {
        "instanceid": "5253e4ad52c23",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/owncloud\/data",
        "share_folder": "\/Shared",
        "dbtype": "mysql",
        "version": "10.0.2.1",
        "dbname": "owncloud",
        "dbhost": "10.1.0.1xx",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "loglevel": 4,
        "maxZipInputSize": 536870912,
        "allowZipDownload": true,
        "overwriteprotocol": "",
        "overwritecondaddr": "",
        "overwritewebroot": "",
        "theme": "",
        "log_authfailip": "true",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpport": "25",
        "trusted_domains": [
            "cloud.domain.tld",
            "some-ip"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "mail_from_address": "cloud",
        "mail_domain": "smtp-domain",
        "mail_smtphost": "10.1.0.1xx",
        "mail_smtpauthtype": "PLAIN",
        "logtimezone": "Europe\/Berlin"
    }
}

**List of activated apps:**
Enabled:
  - activity: 2.3.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.9
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.0
  - files_texteditor: 2.2
  - files_trashbin: 0.9.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_ldap: 0.9.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_versions
  - theme-example
  - user_external

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory

#### LDAP configuration (delete this part if not used)
+-------------------------------+------------------------------------------------------------+
| Configuration                 |                                                            |
+-------------------------------+------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                          |
| hasPagedResultSupport         |                                                            |
| homeFolderNamingRule          |                                                            |
| lastJpegPhotoLookup           | 0                                                          |
| ldapAgentName                 | CN=ownclouduser,DC=xxx-dom,DC=local 						 |
| ldapAgentPassword             | ***                                                        |
| ldapAttributesForGroupSearch  |                                                            |
| ldapAttributesForUserSearch   |                                                            |
| ldapBackupHost                | backupip		                                             |
| ldapBackupPort                | 389                                                        |
| ldapBase                      | DC=xxx-DOM,DC=LOCAL        	                             |
| ldapBaseGroups                | DC=xxx-DOM,DC=LOCAL       	                             |
| ldapBaseUsers                 | DC=xxx-DOM,DC=LOCAL      	                                 |
| ldapCacheTTL                  | 300                                                        |
| ldapConfigurationActive       | 1                                                          |
| ldapDynamicGroupMemberURL     |                                                            |
| ldapEmailAttribute            | mail                                                       |
| ldapExperiencedAdmin          | 0                                                          |
| ldapExpertUUIDGroupAttr       |                                                            |
| ldapExpertUUIDUserAttr        |                                                            |
| ldapExpertUsernameAttr        | uid                                                        |
| ldapGroupDisplayName          | displayname                                                |
| ldapGroupFilter               | objectClass=posixGroup                                     |
| ldapGroupFilterGroups         |                                                            |
| ldapGroupFilterMode           | 1                                                          |
| ldapGroupFilterObjectclass    |                                                            |
| ldapGroupMemberAssocAttr      | member                                                     |
| ldapHost                      | dcip                                                 |
| ldapIgnoreNamingRules         |                                                            |
| ldapLoginFilter               | (&(|(objectclass=user))(samaccountname=%uid))              |
| ldapLoginFilterAttributes     |                                                            |
| ldapLoginFilterEmail          | 0                                                          |
| ldapLoginFilterMode           | 0                                                          |
| ldapLoginFilterUsername       | 1                                                          |
| ldapNestedGroups              | 0                                                          |
| ldapOverrideMainServer        |                                                            |
| ldapPagingSize                | 500                                                        |
| ldapPort                      | 389                                                        |
| ldapQuotaAttribute            |                                                            |
| ldapQuotaDefault              |                                                            |
| ldapTLS                       |                                                            |
| ldapUserDisplayName           | displayName                                                |
| ldapUserDisplayName2          |                                                            |
| ldapUserFilter                | (|(objectclass=user))                                      |
| ldapUserFilterGroups          | Owncloud-Benutzer                                          |
| ldapUserFilterMode            | 1                                                          |
| ldapUserFilterObjectclass     | user                                                       |
| ldapUuidGroupAttribute        | auto                                                       |
| ldapUuidUserAttribute         | auto                                                       |
| turnOffCertCheck              | 1                                                          |
| useMemberOfToDetectMembership | 1                                                          |
+-------------------------------+------------------------------------------------------------+

### Client configuration
**Browser:**
Firefox, iOS App

**Operating system:**
Windows/Apple iOS

**Comment by PVince81** [comment]
@jvillafanez

**Comment by CaptionF** [comment]
@mwichern Please ensure that you perform occ command user:sync in a cron job.
This is due to changes in the LDAP Wizard.
https://doc.owncloud.com/server/10.0/admin_manual/configuration_server/occ_command.html?highlight=sync#syncing-user-accounts

**Comment by PVince81** [comment]
please reopen if you already followed the documentation in the previous comment and it still didn't work
