### ISSUE TITLE
when Ctrl-C ing occ files:scan unlock the files

### ISSUE THREAD

**Issue by butonic** [owncloud/core#28266]
1. start scanning a user with `occ files:scan username`
2. Ctrl-C because yo forgot verbose
3. restart scanning with `occ files:scan username -v` 

## what should happen
scan should show you the files it is scanning

## what happens
locked exception

you have to wait for the lock to expire or wipe it manually in redis / the db ... takes an hour

then scan works as expected

**Comment by PVince81** [comment]
Good luck with that. Would require catching the `InterruptedException` in many places inside the scanner.

Or even better, use `try {} finally {}`. Seems it might be available since PHP 5..5.

Isn't it ? @DeepDiver1975 @phisch

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
