### ISSUE TITLE
iOS client misbehaving after server upgrade to 10.0.2.1

### ISSUE THREAD

**Issue by UnitedMarsupials** [owncloud/core#28280]
### Steps to reproduce
1. Upgrade from 9.1.4 to 10.0.2.1
2. Fire up the iOS client and attempt to upload media files

### Expected behaviour
Uploads should proceed as before

### Actual behaviour
Upon starting up the client claims -- several times -- that the server "is not available" or even that it is "in maintenance mode". Picking the "Uploads" tab would should pending uploads "Waiting for server connection", except _sometimes_ an occasional file would get uploaded -- and then the upload queue would stall again.

Things appear fine (if slow) in the browser.

### Server configuration
FreeBSD-10.3

**Web server:**
Apache-2.4.26

**Database:**
PostgreSQL-9.3

**PHP version:**
7.0.20

**ownCloud version:** (see ownCloud admin page)
10.0.2.1

**Updated from an older ownCloud or fresh install:**
Upgraded from 9.1.4 (?)

**Where did you install ownCloud from:**
[FreeBSD port](https://www.freshports.org/www/owncloud/)

**Signing status (ownCloud 9.0 and above):**

```
https://gist.github.com/UnitedMarsupials/f60a9de7d04786fcbba230d8932bf729
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "*** REMOVED SENSITIVE VALUE BY HAND ***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.example.net"
        ],
        "datadirectory": "\/obfuscated\/ownCloud",
        "overwrite.cli.url": "http:\/\/oc.example.net",
        "dbtype": "pgsql",
        "version": "10.0.2.1",
        "dbname": "oc",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "config_is_read_only": true
    }
}

```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.9
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - theme-example
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Only local, I think...

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
The latest available iOS-client. Things work fine in Firefox.

#### ownCloud log (data/owncloud.log)

Judging by the IP-address, the entries in the log are all from the browser-access (Firefox) -- nothing from the iPhone's IP is recorded today. The [browser-generated log-entries are nasty and ugly](https://gist.github.com/UnitedMarsupials/207a2ad38b23f799ea565c9e29e8ca4b), but do not appear to break anything.

**Comment by UnitedMarsupials** [comment]
FWIW, I just a reinstall of all the files (the DB was already updated to 10.0.2.1). The iOS client simply crashes (disappears) on start-up -- no error-messages...

**Comment by kdslkdsaldsal** [comment]
Looks like you have some wrong permissions on your filesystem (there are some entries in your posted logfiles about "Permission denied").

**Comment by kdslkdsaldsal** [comment]
Might be also the known issue / limitation in the IOS app where an issue exists here: https://github.com/owncloud/ios/issues/785

**Comment by UnitedMarsupials** [comment]
Thanks, I fixed the permissions under `avatars/`, but the iOS client is still crashing on startup.

Using `tcpdump` on the FPM port 9000 on the server, I see the following request (edited):
```
HTTP_AUTHORIZATIONBasic XXXXX..HTTPSon..SSL_TLS_SNIoc.example.net..PATH/opt/bin:/bin:/usr/bin..HOME/opt/www/owncloud      .HTTP_HOME/opt/www/owncloud..modHeadersAvailabletrue..proxy-nokeepalive1        .HTTP_HOSToc.example.net:8443.!CONTENT_TYPEapplication/x-www-form-urlencoded..HTTP_ACCEPT*/*.
HTTP_ACCEPT_ENCODINGgzip, deflate.$HTTP_USER_AGENTMozilla/5.0 (iOS) ownCloud-iOS/3.6.2.#HTTP_ACCEPT_LANGUAGEuk-US;q=1, en-US;q=0.9, ru-US;q=0.8..HTTP_OCS_APIREQUESTtrue..LD_LIBRARY_PATH/opt/lib:/opt/lib..SERVER_SIGNATURE.\SERVER_SOFTWAREApache/2.4.26 (FreeBSD) mod_fastcgi.DOCUMENT_ROOT/opt/www/owncloud..REQUEST_SCHEMEhttps..CONTEXT_PREFIX..CONTEXT_DOCUMENT_ROOT/opt/www/owncloud..SERVER_ADMINyou@example.com.7SCRIPT_FILENAMEproxy:fcgi://127.0.0.1:9000/opt/www/owncloud/ocs/v1.php..REMOTE_PORT54136..GATEWAY_INTERFACECGI/1.1..SERVER_PROTOCOLHTTP/1.1..REQUEST_METHODGET..QUERY_STRINGformat=json.*REQUEST_URI/ocs/v1.php/cloud/capabilities?format=json..SCRIPT_NAME/v1.php   .PATH_INFO/cloud/capabilities.$PATH_TRANSLATED/opt/www/owncloud/cloud/capabilities
```
response from the server is:
```
X-Powered-By: PHP/7.0.20
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=Cc- EDITED -E; path=/; secure; HttpOnly
Content-Security-Policy:default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
Set-Cookie: ocmt7icmf3et=u5 - EDITED -eh25; path=/; secure; HttpOnly
Set-Cookie: cookie_test=test; expires=Sun, 02-Jul-2017 18:35:34 GMT; Max-Age=3600
Content-Type: application/json; charset=utf-8

{"ocs":{"meta":{"status":"failure","statuscode":999,"message":"Invalid query, please check the syntax. API specifications are here: http:\/\/www.freedesktop.org\/wiki\/Specifications\/open-collaboration-services. DEBUG OUTPUT:\n"},"data":[]}}
```
It is a good bet, the error (code 999??) is what's causing the iOS client to die. Why is it being generated?..

**Comment by kdslkdsaldsal** [comment]
@UnitedMarsupials Please post any crashes of the clients to the correct bugtrackers of these. For the iOS client that would be https://github.com/owncloud/ios/issues

**Comment by UnitedMarsupials** [comment]
But I haven't changed anything about the client -- I only upgraded the server. So now the client folks will be trying to push me back into core -- and they'll be right :)

**Comment by kdslkdsaldsal** [comment]
A client crash is something which needs to be handled by the client folks :-)

Ah, btw. As you're running FreeBSD you probably also running php-fpm? If yes you probably also have upgraded Apache to 2.4.26 while upgrading oC to 10.0?

https://mail-archives.apache.org/mod_mbox/httpd-users/201706.mbox/%3C18166d8c-d58b-6c25-e90d-0a9f1f23cb35@gmail.com%3E

**Comment by UnitedMarsupials** [comment]
Now _that_ was awesome! Indeed, after adding the `ProxyFCGIBackendType GENERIC` to the relevant Apache config, things seem to work better (something is still wrong about thumbnails, which used to work, but that I should be able to figure out)... Thanks!

**Comment by kdslkdsaldsal** [comment]
No problem. It would be still great if you could raise a new issue about the iOS client crash at the issue tracker of the client at https://github.com/owncloud/ios/issues Thanks
