### ISSUE TITLE
Have a specific command to enable files external via occ

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#28286]
Currently we have to set an app config key:

```
./occ config:app:set core enable_external_storage --value=yes
```

But you have to know it previously because the occ help doesn't tell you anything about this.

I suggest to have a command to enable it directly, not even showing the core app config key.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
