### ISSUE TITLE
Firefox: deleting users in GUI does not work 

### ISSUE THREAD

**Issue by tobias-weiss** [owncloud/core#28289]
When using Firefox deleting users in GUI does not work. Using IE 11 and Chrome 59 does work properly.

### Steps to reproduce
0. use Firefox and login into ownCloud
1. create some users
2. pick one and delete a user
3. refresh user list or look at database, user will still remain

### Expected behaviour
User should be deleted also if Firefox used

### Actual behaviour
User remains

### Server configuration
CentOS 7 

**Web server:**
Apache 2.4 (from SCL)

**Database:**
MariaDB 5.5.52

**PHP version:**
7.0 (from SCL)

**ownCloud version:** (see ownCloud admin page)
10.0.2.1

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
package download (bz2) from ownCloud directly

**Signing status (ownCloud 9.0 and above):**
error due use of theme app without signature, aside from that all OK

Technical information
=====================

attached app list, config.php and intetgry check as ocl_req_files.txt
[ocl_req_files.txt](https://github.com/owncloud/core/files/1119913/ocl_req_files.txt)

**Are you using external storage, if yes which one:** local/smb/sftp/...
local, seperate partition, mounted outside ownCloud's directrory

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:** 
!!! Firefox 54.0.1 (PortableEdition, 64bit), and Firefox ESR 52.2.0 32bit BOTH DO NOT WORK
Google Chrome 59.0.3071.10 works fine
Intnernet Explorer 11.09600.18449 works fine

**Operating system:**
Windows 7, Windows Server 2008

#### Web server error log
nothing relevant to this issue

#### ownCloud log (data/owncloud.log)
nothing relevant to this issue

#### Browser log
Show the attemp to delete a user (look for 'USER.NAME')

**Comment by PVince81** [comment]
Would you mind extracting the response for the DELETE operation from the log ? This is too verbose and I can't seem to find it.

**Comment by tobias-weiss** [comment]
I took the log only for a few seconds, but it grew very fast. Maybe I'd have closed the other tabs for this action. I am sorry. The DELETE operation starts in line 883. As I am not an web develeoper I do not know what the result should look like and thus not able to identify it.

**Comment by tobias-weiss** [comment]
I recreated the issue and forund this:

 
> 2017-07-06 11:41:55.776000 UTC - [Socket Thread]: I/nsHttp http response [
**> 2017-07-06 11:41:55.776000 UTC - [Socket Thread]: I/nsHttp   HTTP/1.1 204 No Content**
> 2017-07-06 11:41:55.776000 UTC - [Socket Thread]: I/nsHttp   Date: Thu, 06 Jul 2017 11:41:55 GMT
> 2017-07-06 11:41:55.776000 UTC - [Socket Thread]: I/nsHttp   Server: Apache/2.4.25 (Red Hat) OpenSSL/1.0.1e-fips PHP/7.0.10
> 2017-07-06 11:41:55.777000 UTC - [Socket Thread]: I/nsHttp   X-Powered-By: PHP/7.0.10
> 2017-07-06 11:41:55.777000 UTC - [Socket Thread]: I/nsHttp   Expires: Thu, 19 Nov 1981 08:52:00 GMT
> 2017-07-06 11:41:55.777000 UTC - [Socket Thread]: I/nsHttp   Cache-Control: no-cache, must-revalidate
> 2017-07-06 11:41:55.777000 UTC - [Socket Thread]: I/nsHttp   Pragma: no-cache
> 2017-07-06 11:41:55.778000 UTC - [Socket Thread]: I/nsHttp   Content-Security-Policy: default-src 'none';manifest-src 'self';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self'
> 2017-07-06 11:41:55.778000 UTC - [Socket Thread]: I/nsHttp   x-xss-protection: 1; mode=block
> 2017-07-06 11:41:55.778000 UTC - [Socket Thread]: I/nsHttp   X-Content-Type-Options: nosniff
> 2017-07-06 11:41:55.778000 UTC - [Socket Thread]: I/nsHttp   X-Frame-Options: SAMEORIGIN
> 2017-07-06 11:41:55.778000 UTC - [Socket Thread]: I/nsHttp   X-Robots-Tag: none
> 2017-07-06 11:41:55.779000 UTC - [Socket Thread]: I/nsHttp   X-Download-Options: noopen
> 2017-07-06 11:41:55.779000 UTC - [Socket Thread]: I/nsHttp   X-Permitted-Cross-Domain-Policies: none
> 2017-07-06 11:41:55.779000 UTC - [Socket Thread]: I/nsHttp   Keep-Alive: timeout=5, max=100
> 2017-07-06 11:41:55.779000 UTC - [Socket Thread]: I/nsHttp   Connection: Keep-Alive
> 2017-07-06 11:41:55.779000 UTC - [Socket Thread]: I/nsHttp   Content-Type: application/json; charset=utf-8
> 2017-07-06 11:41:55.780000 UTC - [Socket Thread]: I/nsHttp     OriginalHeaders
> 2017-07-06 11:41:55.780000 UTC - [Socket Thread]: I/nsHttp   Date: Thu, 06 Jul 2017 11:41:55 GMT
> 2017-07-06 11:41:55.780000 UTC - [Socket Thread]: I/nsHttp   Server: Apache/2.4.25 (Red Hat) OpenSSL/1.0.1e-fips PHP/7.0.10
> 2017-07-06 11:41:55.780000 UTC - [Socket Thread]: I/nsHttp   X-Powered-By: PHP/7.0.10
> 2017-07-06 11:41:55.781000 UTC - [Socket Thread]: I/nsHttp   Expires: Thu, 19 Nov 1981 08:52:00 GMT
> 2017-07-06 11:41:55.781000 UTC - [Socket Thread]: I/nsHttp   Cache-Control: no-cache, must-revalidate
> 2017-07-06 11:41:55.781000 UTC - [Socket Thread]: I/nsHttp   Pragma: no-cache
> 2017-07-06 11:41:55.781000 UTC - [Socket Thread]: I/nsHttp   Content-Security-Policy: default-src 'none';manifest-src 'self';script-src 'self' 'unsafe-eval';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self';connect-src 'self';media-src 'self'
> 2017-07-06 11:41:55.781000 UTC - [Socket Thread]: I/nsHttp   x-xss-protection: 1; mode=block
> 2017-07-06 11:41:55.782000 UTC - [Socket Thread]: I/nsHttp   X-Content-Type-Options: nosniff
> 2017-07-06 11:41:55.782000 UTC - [Socket Thread]: I/nsHttp   X-Frame-Options: SAMEORIGIN
> 2017-07-06 11:41:55.782000 UTC - [Socket Thread]: I/nsHttp   X-Robots-Tag: none
> 2017-07-06 11:41:55.782000 UTC - [Socket Thread]: I/nsHttp   X-Download-Options: noopen
> 2017-07-06 11:41:55.782000 UTC - [Socket Thread]: I/nsHttp   X-Permitted-Cross-Domain-Policies: none
> 2017-07-06 11:41:55.783000 UTC - [Socket Thread]: I/nsHttp   Keep-Alive: timeout=5, max=100
> 2017-07-06 11:41:55.783000 UTC - [Socket Thread]: I/nsHttp   Connection: Keep-Alive
> 2017-07-06 11:41:55.783000 UTC - [Socket Thread]: I/nsHttp   Content-Type: application/json; charset=utf-8
> 2017-07-06 11:41:55.784000 UTC - [Socket Thread]: I/nsHttp ]

The browser however shows "User xyz deleted".

**Comment by maxdwit** [comment]
Can't delete any user that comes from ldap.
If I create a local stored user, the user deletion works fine.

**Comment by tobias-weiss** [comment]
We use local backend with MySQL as database.

**Comment by maxdwit** [comment]
still not fixed.

**Comment by PVince81** [comment]
AFAIK you cannot delete LDAP users from the users page, the user needs to be deleted in LDAP directly.

@jvillafanez ^

**Comment by jvillafanez** [comment]
ownCloud won't delete any LDAP user.

ownCloud 10.0 can delete the user's account and the data associated to it, but the LDAP server will remain untouched, which means that the user will still have access to the a new account when he logs in or the backends are synced.
In order to effectively delete the LDAP user you need to delete it from the LDAP server first and then delete the ownCloud account. Alternatively, you can disable the user from ownCloud so he can't access any longer.

This is a "won't fix" for LDAP users. Other user backends (such as the DB / local one) might have other behaviours.

**Comment by maxdwit** [comment]
Understood your argumentation.
Have here:
User X, connected with his LDAP Account.
User X should no longer use this Instance of ownCloud
User X is removed (delete) from this instance and still pops up

So, If I understood you correct: We should disable the User in the User
Interface of Owncloud.
So he is stil visible ( annoying ) but can no longer access this server.
Right?

2017-10-11 10:41 GMT+02:00 Juan Pablo Villafañez <notifications@github.com>:

**Comment by jvillafanez** [comment]
@maxdwit you have several options:
* Disable the account in ownCloud. Quite easy and non-intrusive. Everything you've said above is correct.
* Remove the user from the LDAP server and resync. This will affect to other systems connected to the LDAP server
* Refine the LDAP filter in the configuration of the LDAP app to exclude specific users, probably using an attribute. For example, you can exclude users that ends with an underscore or which have an "accountStatus=disabled" as attribute. You should do this in the LDAP user and login filters. You'll need to resync the users afterwards.

**Comment by PVince81** [comment]
Related ticket about bad UX when deleting LDAP user: https://github.com/owncloud/core/issues/14465

But this ticket here was about a bug not being able to delete only in Firefox. As I'm not able to reproduce this myself with Firefox and no one else reported the exact same issue, I suspect it's an issue related to @tobias-weiss' environment. Maybe a Firefox update would help ?
