### ISSUE TITLE
Consider update of AWS PHP library

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#28282]
We last updated it 3 years ago https://github.com/owncloud/core/commit/e0056c4a0dc5be96cefe34461498350ac7d907a1 and there have been numerous fixes since. Can we also import it with composer? I just had to add a hack to fix signature creation for the London region for the files_external app.

**Comment by kdslkdsaldsal** [comment]
Might also solve https://github.com/owncloud/core/issues/14893 or am i wrong?

**Comment by tomneedham** [comment]
Yes quite possibly. Amazon has some funky logic with their signature requirements - adding it as a parameter would get around this but doing it automatically is also cool

**Comment by tomneedham** [comment]
@pmaier1 @PVince81 We should add some prio here as this is hurting us more as/when Amazon are depreciating V3 signature and we don't have updated defaults for the regions. Either we update the lib or have to code in the default signature logic like I have done once already.

**Comment by PVince81** [comment]
Is there a timeline for the deprecation ?

I think we should move out the Amazon S3 into a separate app anyway and tackle this at the same time.

**Comment by DeepDiver1975** [comment]
files_external_s3 and files_primary_s3

**Comment by tomneedham** [comment]
Actually they moved all regions to supporting v4 - so we made core default to v4 now so this is less important.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
move to composer once we move this to an app
