### ISSUE TITLE
Deleted images still listed, but no longer accessible

### ISSUE THREAD

**Issue by UnitedMarsupials** [owncloud/core#28290]
See #28280 for configuration details.

### Steps to reproduce
1. Delete an image through the iOS client -- telling to "Delete both local and on the server".

### Expected behaviour
The deleted image disappears.

### Actual behaviour
Although duly removed from the filesystem, the image is still listed (without thumbnail) -- and shown in Firefox. Trying to access it results in: "Service Unavailable" (with request-ID). The two lines in the `ownCloud.log` containing the quoted request-ID are:
```
{"reqId":"K3uu6oAVuZqqt30UPMQi","level":3,"time":"2017-07-03T14:26:15+00:00","remoteAddr":"192.168.1.10","user":"mi","app":"PHP","method":"GET","url":"\/remote.php\/webdav\/Photo-2017-04-18-17-24-24_A6B6F0AF-13C2-4EDF-844F-2266AA1A2A2B.JPG","message":"fopen(\/fuji\/ownCloud\/mi\/files\/Photo-2017-04-18-17-24-24_A6B6F0AF-13C2-4EDF-844F-2266AA1A2A2B.JPG): failed to open stream: No such file or directory at \/opt\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#276"}
{"reqId":"K3uu6oAVuZqqt30UPMQi","level":4,"time":"2017-07-03T14:26:15+00:00","remoteAddr":"192.168.1.10","user":"mi","app":"webdav","method":"GET","url":"\/remote.php\/webdav\/Photo-2017-04-18-17-24-24_A6B6F0AF-13C2-4EDF-844F-2266AA1A2A2B.JPG","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Could not open file\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(85): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/opt\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/opt\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/opt\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/opt\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/opt\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/opt\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/opt\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":319,\"User\":\"mi\"}"}
```

Other [`owncloud.log` entries](https://gist.github.com/UnitedMarsupials/e692111841134fece2ffdd39e11e7979) nearby in the file show attempts to access an alarming path: `/fuji/ownCloud/mi/files/opt/www/owncloud` -- alarming because `/fuji/ownCloud` is my data-directory, whereas `/opt/www/owncloud` is where the PHP-code is installed. They should never be concatenated together.

**Comment by PVince81** [comment]
would be good to see your config.php and the value of "datadirectory", assuming you used an absolute value

**Comment by UnitedMarsupials** [comment]
```
{
    "system": {
        "instanceid": "ocmXXX3et",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.example.net"
        ],
        "datadirectory": "\/fuji\/ownCloud",
        "overwrite.cli.url": "http:\/\/oc.example.net",
        "dbtype": "pgsql",
        "version": "10.0.2.1",
        "dbname": "oc",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "config_is_read_only": true
    }
```
> assuming you used an absolute value

Of course I did! Images (_data_) are on a filesystem completely different from the one used for _code_.

**Comment by PVince81** [comment]
ok, need to try this locally... the path concatenation indeed looks fishy

**Comment by PVince81** [comment]
you mean this one ? 
`file_get_contents(\/fuji\/ownCloud\/mi\/files\/opt\/www\/owncloud\/core\/img\/filetypes\/image.svg)`

It looks like it's trying to find the icon image for the "image" file type. Could be a resource locator bug.

@phisch

**Comment by UnitedMarsupials** [comment]
Yes, that is, what I meant -- and it is "fishy".

But I don't think, it is related to the bug I actually reported here -- that the deleted image is still listed in the directory, that used to contain it and that attempts to access it result in "Service Unavailable".

For that, I suspect, the problem is elsewhere (I suspect the code responsible for removing the deleted files from database is broken in case of PostgreSQL).

**Comment by PVince81** [comment]
Is this repeatable ? Does it happen for any image you delete ? How about regular files ?
Are the affected files shared with you or are you the owner ?

**Comment by UnitedMarsupials** [comment]
I do not delete very often. It did happen to the two files I deleted. They were "regular" files and I have not shared them. I am the owner -- indeed, the sole user...

**Comment by PVince81** [comment]
Were you on an unstable network connection ? was the operation aborted somehow ?

Sometimes inconsistent DB state is due to the PHP process being killed too early by eager web servers whenever the network connection is closed early.

You can likely make the error disappear by running `occ files:scan --all`.

**Comment by UnitedMarsupials** [comment]
> You can likely make the error disappear by running occ files:scan --all.

Yes, this helped get rid of the removed files for good. Perhaps, it should not be necessary? That is, if the files are listed in the database _at all_ (itself a strange requirement), a failure to find one on the filesystem should result in it quietly getting removed from there -- and a 404 or some other suitable error.

Because it is -- and should be -- possible to remove files from the filesystem by hand...

**Comment by PVince81** [comment]
> a failure to find one on the filesystem should result in it quietly getting removed from there

Code was added to do just that, looks like it's broken...

**Comment by PVince81** [comment]
ref https://github.com/owncloud/core/issues/24499

**Comment by mmattel** [comment]
https://github.com/owncloud/core/issues/24499#issuecomment-224203432 -> if this is fixed, can we close this issue?

**Comment by PVince81** [comment]
@mmattel well, it was fixed in the past but the report above seems to show otherwise. Unless maybe there yet another code path for deletion that is not covered by the PR... needs further research

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
