### ISSUE TITLE
Display age in birthday events

### ISSUE THREAD

**Issue by mueller-ma** [owncloud/core#28297]
### Steps to reproduce
1. Create a contact with birth date
2. Go to calendar

### Expected behaviour
I would like to see:  "117 foo bar (*1900)"

### Actual behaviour
I see an entry with: "foo bar (*1900)"

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache/2.4.10 (Debian)

**ownCloud version:** ownCloud 9.1.6 (stable)

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.1
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - federation
  - files_antivirus
  - files_external
  - firstrunwizard
  - templateeditor
  - user_external
  - user_ldap
```

**Comment by DeepDiver1975** [comment]
This is technically not possible. Birthdays are modelled as recurring events.
A recurring event has a fixed summary text which is displayed on all events.

**Comment by mueller-ma** [comment]
What about creating single events instead?

**Comment by DeepDiver1975** [comment]
> What about creating single events instead?

Technically doable but has side effects as well:
- start year is clear - but when does it end?
- each single event has to be deleted on its own
- recurring events are designed for cases like this ;-)

**Comment by mueller-ma** [comment]
- Maybe for the next five years?
- If someone doesn't want to see a birthday event, he can remove the birthday from the contact or doesn't use the entire birthday calendar

**Comment by DeepDiver1975** [comment]
> Maybe for the next five years?

not really reasonable - my daughter doesn't disappear after she got 6 years old ;-)

**Comment by mueller-ma** [comment]
* For the next five years. and the cronjob creates new entries.
Or just generate 120 entries.

**Comment by DeepDiver1975** [comment]
> For the next five years. and the cronjob creates new entries.

see - it starts to get complicated ;-) this is why I did choose the recurring event

**Comment by mueller-ma** [comment]
Complicated, but not impossible

**Comment by DeepDiver1975** [comment]
I prefer: keep it simple!
