### ISSUE TITLE
Check "Helps & Tips" that point to the right documentation URL

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#28296]
[00007865](https://na56.salesforce.com/5000Z00000pW4kr?srPos=0&srKp=500)

The "helps and tips" part:
https://github.com/owncloud/core/blob/v10.0.2/settings/templates/panels/admin/tips.php#L11-L16
shows some links to the documentation that doesn't exist anymore

As example: https://github.com/owncloud/documentation/issues/3192

@PVince81 @tomneedham @owncloud/qa We need someone that verify the links and point them to the right documentation page

**Comment by felixboehm** [comment]
milestone development, as solved with https://github.com/owncloud/core/pull/28416 (merged)
