### ISSUE TITLE
WebDav: User Quota on external Shares

### ISSUE THREAD

**Issue by htwsaaraub** [owncloud/core#28305]
### Steps to reproduce
1. Set the User Quota to 0
2. Connect to a Owncloud WebDav Share useing Windows. 
3. Try to Change or Upload a File to a Owncloud Folder that is a External SMB Share

### Expected behaviour
The File Should be changed or Uploaded to the external Share
The Quota should not be considered on External SMB Shares.

### Actual behaviour
File could not be Uploaded with WebDav. Owncloud Log gives an Exception: Insufficent Storage

File Upload in WebUI didn't consider the Quota of the User on External Share and Upload the File Correct. 

### Server configuration
**Operating system**: Linux 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64

**Web server:** Apache/2.4.25 (Debian)

**Database:**  Ver 15.1 Distrib 10.1.23-MariaDB

**PHP version:** 5.6.30-0+deb8u1

**ownCloud version:** 10.0.2 (stable)

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** Debian Packages

**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration

**Browser:** Google Chrome Version 59.0.3071.115 (Offizieller Build) (64-Bit)

**Operating system:** Windows 10, 1703

#### ownCloud log (data/owncloud.log)
The Original Username is replaced by "Username"

```
{"reqId":"BzyhzpmRNMWCoN8qqvRG","level":4,"time":"2017-07-05T10:42:10+00:00","remoteAddr":"X.X.X.X","user":"Username","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/files\/Username\/Share\/Folder\File.pdf","message":"Exception: {\"Message\":\"HTTP\\\/1.1 507 Insufficient Storage\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\InsufficientStorage\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\QuotaPlugin->checkQuota('files\\\/Username...', Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File), Resource id #62, false)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1127): Sabre\\\\Event\\\\EventEmitter->emit('beforeWriteCont...', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('files\\\/Username...', Resource id #62, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(229): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/QuotaPlugin.php\",\"Line\":111,\"User\":\"Username\"}"}
```

**Comment by PVince81** [comment]
Hmmm, are you uploading with Chrome as specified or is the quota check only failing with desktop client 2.3.2 ?

Asking because of https://github.com/owncloud/core/pull/28261.
This issue shouldn't affect the web UI

**Comment by htwsaaraub** [comment]
I'm Uploading with Chrome using the WebUI as specified. 

No Desktop Client ist installed. Client access is only used with WebDAV in Windows Explorer.

**Comment by PVince81** [comment]
Can you try again with 10.0.3 RC1 ?

**Comment by PVince81** [comment]
If you used the path "remote.php/dav/files/$userId/" to mount on Windows, then this is the new DAV endpoint and there was a bug with quota and external storage. That bug is fixed in 10.0.3 RC1.

However if you used "remote.php/webdav" this might be a different issue... Would still be good if you could test again with 10.0.3 RC1 to confirm.

**Comment by htwsaaraub** [comment]
Works in 10.0.3 but for me there is still another not considered Error.
Webdav: Could not rename part file to final file due to Quota limit #29103

**Comment by PVince81** [comment]
ok, closing, I'll check the linked report
