### ISSUE TITLE
Internal Server Error caused by data/.htaccess

### ISSUE THREAD

**Issue by ksingvo** [owncloud/core#28307]
curl http://server.com/owncloud/data/owncloud.log

### Actual behaviour
"Internal Server Error"

/var/log/apache2/error.log shows:
[date+time] [core:alert] [pid 1] [client adress] /var/www/owncloud/data/.htaccess: Invalid command 'IndexIgnore', perhaps misspelled or defined by a module not included in the server configuration

### Server configuration
**Operating system**: Debian Jessie 8.8 (armbian)

**Web server:** Apache 2.4.10-10+deb8u9

**Database:** postgresql 9.4+165+deb8u2

**PHP version:** 5.6.30+dfsg-0+deb8u1

**ownCloud version:** 10.0.2-1.1

**Updated from an older ownCloud or fresh install:** updated from 10.0.0, and updated from 9.x

**Where did you install ownCloud from:** repo is http://download.owncloud.org/download/repositories/10.0/Debian_8.0/

**Signing status (ownCloud 9.0 and above):** No errors have been found.

**The content of config/config.php:**

{
    "system": {
        "updatechecker": false,
        "instanceid": "ocu5wbf7bmzv",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "somedomain",
            "somehost"
        ],
        "datadirectory": "\/download\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/host.somedomain\/owncloud",
        "dbtype": "pgsql",
        "version": "10.0.2.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 2,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        }
    }
}

**List of activated apps:**
Enabled:
  - activity: 2.3.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.9
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.0
  - files_texteditor: 2.2
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - theme-example
  - user_external

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** not aware of any

#### Web server error log
[date+time] [core:alert] [pid xxx] [client ipv6-address] /var/www/owncloud/data/.htaccess: Invalid command 'IndexIgnore', perhaps misspelled or defined by a module not included in the server configuration

#### ownCloud log (data/owncloud.log)
no related entry avail

### Hints
The IndexIgnore directive with apache2.4 needs the module autoindex enabled.

See: https://httpd.apache.org/docs/current/mod/mod_autoindex.html#indexignore

This module isn't enabled by default.

Please add an ifModule directive, and provide an alternative if not enabled.

**Comment by kdslkdsaldsal** [comment]
> Please add an ifModule directive,

Done in https://github.com/owncloud/core/issues/28343, thanks.

> and provide an alternative if not enabled.

Not required as this IndexIgnore is disabling the auto index generation of mod_autoindex once it is enabled.
