### ISSUE TITLE
Provide occ commands to list users and groups

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#28311]
The occ command currently provides the ability to add/delete/modify users. It was recently enhanced to provide the ability to add  and delete groups and to add and remove members from a group.

This is all well and good for automated testing etc, But for real sysadmins, or to be able to script user/group management it would be useful to be able to:

- list users on the system (then a script or human could potentially delete users that should not be there)
- list the groups that a particular user is in
- list groups on the system (then a script or human could potentially delete groups that should not be there)
- list the users in a particular group (then a script or human could potentially delete users from the group)

It is easy to add users/groups/group membership without knowing the current "state of the system". But to cleanup users/groups/group membership you really need to be able to see the current state in order to know what cleanup actions to take.

Suggestion here:
https://github.com/owncloud/core/pull/28190#issuecomment-313041599

**Comment by individual-it** [comment]
Is this solved in #28312 ?

**Comment by phil-davis** [comment]
Doc issue complete:
https://github.com/owncloud/documentation/issues/3203
By doc PR:
https://github.com/owncloud/documentation/pull/3208
all finished.
