### ISSUE TITLE
Inconsistency between OAuth2 access token and session cookie expirations

### ISSUE THREAD

**Issue by davigonz** [owncloud/core#28336]
Session cookie is not being expired when OAuth access token expires, allowing us to perform successful operations when they should be unauthorized.

I have tried to reproduce the opposite case, revoking a session and seeing if the access token is also expired, but after installing OAuth2 in a 10 server and going to Settings/Security options, where all the sessions should appear, I get an Internal Server Error. See https://github.com/owncloud/oauth2/issues/51

### Steps to reproduce
1. Complete OAuth2 login flow.
2. Expires access token manually from the server database. Restart the server just in case. 
3. Try to do a request, for example, listing a directory:

**Curl command to list a directory:**

`curl -X PROPFIND -H "Content-Type: text/xml" -H "User-Agent: Mozilla/5.0 (Android) ownCloud-android/2.4.0" -H "Authorization: Bearer accessToken" -d "<?xml version='1.0' encoding='utf-8' ?><D:propfind xmlns:D='DAV:'><D:allprop/></D:propfind>" url:port/remote.php/webdav -H "Cookie: oc_sessionPassphrase=whatEver" | xmllint --format -
`
### Expected behaviour
Server should response with an error related to not authentication or bearer token incorrect.

**Expected curl result:** 
```xml
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, Bearer token was incorrect</s:message>
</d:error>
```

### Actual behaviour
Server response is successful, includes a multiresponse with info about the directory.

**Actual curl result:** 
```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/remote.php/webdav/</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Thu, 06 Jul 2017 10:40:57 GMT</d:getlastmodified>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:quota-used-bytes>6767385</d:quota-used-bytes>
        <d:quota-available-bytes>-3</d:quota-available-bytes>
        <d:getetag>"595e13b90e40a"</d:getetag>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/webdav/Documents/</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Thu, 06 Jul 2017 10:39:52 GMT</d:getlastmodified>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:quota-used-bytes>45207</d:quota-used-bytes>
        <d:quota-available-bytes>-3</d:quota-available-bytes>
        <d:getetag>"595e1378d2612"</d:getetag>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/webdav/Photos/</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Thu, 06 Jul 2017 07:57:45 GMT</d:getlastmodified>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:quota-used-bytes>678556</d:quota-used-bytes>
        <d:quota-available-bytes>-3</d:quota-available-bytes>
        <d:getetag>"595ded79c3800"</d:getetag>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

### Server configuration
**Web server:** Apache 2.4.18

**Database:** MySQL

**PHP version:** php7.0.18

**ownCloud version:** 10.0.2 (stable)

**Comment by DeepDiver1975** [comment]
@davigonz please test owncloud/oauth2#53

**Comment by davigonz** [comment]
> please test owncloud/oauth2#53 @DeepDiver1975

Yeah, I'm getting an unauthorized HTTP response as expected.

:+1:
