### ISSUE TITLE
Wrong Quote Text in personal settings

### ISSUE THREAD

**Issue by Bobgermany** [owncloud/core#28339]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen
The memory display should show the correct value. (https://xxx/owncloud/index.php/settings/personal?sectionid=general)
### Actual behaviour
Tell us what happens instead
The memory display show 0 B, but i have uploaded some files.
### Server configuration
**Operating system**:
Raspbian GNU/Linux 8 (jessie)
**Web server:**
Apache/2.4.10 (Raspbian)
**Database:**
MySQL Server
**PHP version:**
PHP 5.6.30-0+deb8u1
**ownCloud version:** (see ownCloud admin page)
10.0.2.1
**Updated from an older ownCloud or fresh install:**
fresh install
**Where did you install ownCloud from:**
Raspberry Pi 2 Model B
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No errors have been found.

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Mozilla Firefox
**Operating system:**
Windows 10
### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by kdslkdsaldsal** [comment]
> Are you using external storage, if yes which one: local/smb/sftp/...
> local

So you're using the external storage app with a local mounted directory? If yes have you uploaded files to that storage ?

IIRC external storages (even local mounted) doesn't count against your quota.

**Comment by kdslkdsaldsal** [comment]
ping @Bobgermany

**Comment by Bobgermany** [comment]
No, I don´t use an external storage app and my data directory is on the system sd-card since i have installed my OwnCloud.

For another account, 0B displayed.

My plan is in the near future the data directory to an external hard drive to move. But I don´t have change any settings for this moment.

**Comment by kdslkdsaldsal** [comment]
@Bobgermany 

1. Have you moved the datadir after the installation?
2. How are you "uploading" the files?

**Comment by Bobgermany** [comment]
1. No
2. Yes all files in /var/www/html/owncloud are on my SD
3. All of the files in the data directory are uploaded over the Web GUI

**Comment by Bobgermany** [comment]
I moved the data directory to an external hard disk.
But the i can´t see a difference

**Comment by PVince81** [comment]
`select * from oc_filecache where path = 'files'` then check the value of the "size" column. If there are files there, the value should be non-zero.

If it is zero, `select * from oc_filecache where path like 'files%' order by path` and see whether there are entries there.

`occ files:scan --all` might help

**Comment by PVince81** [comment]
Please run the above queries and also add log statements like here https://github.com/owncloud/core/issues/27924#issuecomment-352036553 to check your storage behavior.

**Comment by PVince81** [comment]
and reopen once you have further information
