### ISSUE TITLE
Use Cloudflare SSL?

### ISSUE THREAD

**Issue by BetaStacks** [owncloud/core#28346]
I am using Cloudflare to manage my DNS. Can I use my cloud flare SSL instead of the self signed one? I would like to eliminate the browsers warning for new users.

**Comment by kdslkdsaldsal** [comment]
Please note this is a bugtracker of ownCloud. Questions like this belongs to https://central.owncloud.org/

Nevertheless a short hint:

ownCloud is just a web application written in PHP. It doesn't care about SSL/TLS certificates at all (as long as no external storages are in use).

Its the job of your webserver to serve a valid (trusted CA, non-deprecated signature,...) certificate to your clients.
