### ISSUE TITLE
Getting 'timed out error' while installing owncloud client software on client side.

### ISSUE THREAD

**Issue by R-yogesh** [owncloud/core#28361]
Hi,
We are getting 'timed out' while installing Own Cloud agent / client software on client side. after giving Own Cloud server hostname / Ip address in Server address bar it should navigate to login page but it is showing timed out error.

Then it is resolved only after restarting web server, and we are now supposed to restart the web server several times. Please provide us correct solution for this issue.

### Steps to reproduce
1.install client
2.Give Ip / hostname address in server address bar
3.press enter, now its showing timed out error

### Expected behaviour
After giving ip / hostname address in server address bar it should navigate to login page which asks username and password.

### Actual behaviour
Instead it is showing timed out error

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** mysql

**PHP version:**7.0

**ownCloud version:** 9.1.4

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
https://gist.github.com/R-yogesh/ab0865e1f6b0a607605606026f0b67e1
```

![image](https://user-images.githubusercontent.com/29791112/28055497-cb4d2afa-6636-11e7-8bdd-4fa8f18e9bd9.png)

**Comment by kdslkdsaldsal** [comment]
Please note this is a bugtracker for ownCloud so closing here for now. Support can be given at https://central.owncloud.org/ where such issues should be posted first (you can login with your github account there).

Once it is sure that this is really a bug in oC you can re-open here. 

An additional hint to this:

> ownCloud version: 9.1.4

Please always use a recent version of ownCloud before posting an issue here or at centra: https://owncloud.org/changelog/#latest9.1
