### ISSUE TITLE
Repair waring - wrong output

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#28369]
1. Run occ upgrade
2. get this message:
`Repair warning: Market app is unavailable for updating of apps. Enable with: occ:app:enable market`
3. Try to run `occ:app:enable market`

expected - `market enabled`

behaviour - `bash: occ:app:enable: command not found`

correction - `occ app:enable market`

a space between occ and app, instead of a colon

**Comment by kdslkdsaldsal** [comment]
This was fixed in https://github.com/owncloud/core/pull/28029 and should be already in 10.0.2

**Comment by voroyam** [comment]
Oh, I am either on 9.1 or 10.0.1
