### ISSUE TITLE
Accepting files from a remote server with self-signed certificate causes the current user do die

### ISSUE THREAD

**Issue by wioxjk** [owncloud/core#28368]
### Steps to reproduce
1. Set up two owncloud servers, one with a validated certificate and one with a self-signed certificate
2. From the server with a valid certificate, add the server with a self-signed cert in federated cloud
3. From the server with a self-signed certificate, share any file to the user@server-with-a-real-cert,
4. Accept the file on the server-with-real-certificate
5. User is dead

### Expected behaviour
The server should accept or reject, the file, even if the remote server has a self signed certificate

### Actual behaviour
Your user is dead, it tries to download the file but instead a 500 error appears.

### Server configuration
**Operating system**:
Debian 8
**Web server:**
Apache2.4
**Database:**
mySQL
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
10.0.0.12
**Updated from an older ownCloud or fresh install:**
Updated from 9.x
**Where did you install ownCloud from:**
repository
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
SFTP
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
Nothing

#### ownCloud log (data/owncloud.log)

```
{"reqId":"HSaSC5MYEy7luAIk2PrX","level":3,"time":"2017-07-11T11:13:56+00:00","remoteAddr":"81.235.28.244","user":"jonathan","app":"core","method":"GET","url":"\/index.php\/apps\/files\/undefined\/img\/notifications.svg","message":"cURL error 60: SSL certificate problem: self signed certificate"}
{"reqId":"HSaSC5MYEy7luAIk2PrX","level":3,"time":"2017-07-11T11:13:56+00:00","remoteAddr":"81.235.28.244","user":"jonathan","app":"index","method":"GET","url":"\/index.php\/apps\/files\/undefined\/img\/notifications.svg","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function getCache() on null\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/UserMountCache.php(92): OC\\\\Files\\\\Mount\\\\MountPoint->getStorageRootId()\\n#1 [internal function]: OC\\\\Files\\\\Config\\\\UserMountCache->OC\\\\Files\\\\Config\\\\{closure}(Object(OCA\\\\Files_Sharing\\\\External\\\\Mount))\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/UserMountCache.php(97): array_map(Object(Closure), Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(134): OC\\\\Files\\\\Config\\\\UserMountCache->registerMounts(Object(OC\\\\User\\\\User), Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(448): OC\\\\Files\\\\Config\\\\MountProviderCollection->registerMounts(Object(OC\\\\User\\\\User), Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(375): OC\\\\Files\\\\Filesystem::initMountPoints('jonathan')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(297): OC\\\\Files\\\\Filesystem::init('jonathan', '\\\/jonathan\\\/files')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(908): OC_Util::setupFS()\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(49): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Mount\\\/MountPoint.php\",\"Line\":251}"}
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by wioxjk** [comment]
Turning off the server with a self-signed-certificate solves the problem where the user generates a 500-error. But the webGUI is really slow. I needed to add the remote server in /etc/hosts in order to avoid the timeouts and then remove the "bad" server.

adding "--no-check-certificate" to the curl request should avoid this problem, or atleast make it possible to ignore if the server has a self signed cert

**Comment by PVince81** [comment]
`/index.php/apps/files/undefined/img/notifications.svg` "undefined" in path ??

@wioxjk can you clarify what "user is dead" means in technical terms ?

@Peter-Prochaska @DeepDiver1975

**Comment by wioxjk** [comment]
@PVince81 
"user is dead" - I cant login to the server - getting 500. When trying to login as the user that has accepted the file. Other users works.

I accidently pasted the "/index.php/apps/files/undefined/img/notifications.svg "undefined" in path ??" 
The first two rows is interesting, also thoose futher down

**Comment by PVince81** [comment]
please try again with 10.0.4 on the receiving server, error handling due to bad certs has been improved
