### ISSUE TITLE
The occ user:inactive command doesn't work as indicated

### ISSUE THREAD

**Issue by settermjd** [owncloud/core#28377]
### Steps to reproduce

1. Call the command, passing a valid integer value, i.e., 

```console
sudo -u www-data ./occ user:inactive --output json 1
```

### Expected behaviour

I would have thought that the command would work as indicated, and "_reported users who are known to owncloud, but have not logged in for a certain number of days_"

### Actual behaviour

The following exception is thrown:

```console
[Symfony\Component\Console\Exception\InvalidArgumentException]  
Days must be integer and above zero 
```

### Server configuration

**Operating system:** Ubuntu Trusty 64.

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:** 7.1.6-2

**ownCloud version:** 10.0.2

**Updated from an older ownCloud or fresh install:** Updated (`git pull`) from a fresh install

**Where did you install ownCloud from:** A clone of the core repository

**Comment by phil-davis** [comment]
@tomneedham that is simple to fix - I was doing stuff in occ anyway, so 5 minutes to fix...

**Comment by settermjd** [comment]
Thanks for the PRs and comment @phil-davis. I'll update and start again.

**Comment by phil-davis** [comment]
and backport to stable10 in PR #28389 
@settermjd you can close this issue when it works for you

**Comment by settermjd** [comment]
Shall do. Just have to make some minor adjustments to my testing vm.

**Comment by tomneedham** [comment]
Fixed with above PRs
