### ISSUE TITLE
OC10 "Help & Tips" not updated with correct links

### ISSUE THREAD

**Issue by Emil-G** [owncloud/core#28375]
### Steps to reproduce
1. Go to page https://_YOUR OWNCLOUD SERVER_/index.php/settings/admin?sectionid=help
2. All links are pointing to 9.1 in the Tips & tricks section. See example: 

**Tips & tricks**
[How to do backups](https://doc.owncloud.com/server/9.1/go.php?to=admin-backup) ↗
[Advanced monitoring](https://doc.owncloud.com/server/9.1/go.php?to=admin-monitoring) ↗
...

### Expected behaviour
Links should point to OC10 manual, not OC9

### Actual behaviour
All links to documentation is pointing to 9.1 when running OC10. 

### Server configuration

**ownCloud version:** (see ownCloud admin page)
10.0.2.1 (enterprise)
**Updated from an older ownCloud or fresh install:**
updated
**Where did you install ownCloud from:**
Enterprise tarball
**Signing status (ownCloud 9.0 and above):**
OK

**The content of config/config.php:**
Not relevant

### Logs
n/a

**Comment by phil-davis** [comment]
Better to raise this in the documentation repo:
https://github.com/owncloud/documentation
and it is already under discussion there.

Parts may be fixed by:
https://github.com/owncloud/documentation/pull/3213
and similar discussion here:
https://github.com/owncloud/documentation/issues/3209

**Comment by Emil-G** [comment]
@phil-davis well, I dit not see why to post it in the documentation repo, when the issue is on the OC server code and not on the owncloud documentation code.

**Comment by phil-davis** [comment]
Apologies, I did not look closely enough at the detail!
My test system based on current master links correctly. It also looks like the version.php in stable10 https://github.com/owncloud/core/blob/stable10/version.php has the correct version, and that should be in the 10.0.2 release.
So what happened?

**Comment by kdslkdsaldsal** [comment]
> I would guess that this file loads a 9.1 parameter from somewhere.

I guess this would be either:

1. a custom theme which has overwritten the defaults.php -> https://github.com/owncloud/core/blob/v10.0.2/lib/private/URLGenerator.php#L244
2. The enterprise theme not using a correct version

**Comment by kdslkdsaldsal** [comment]
And in the case of 1. this is the example:

https://github.com/owncloud/core/blob/v9.1.6/themes/example/defaults.php#L141-L143

So if there is a defaults.php linking to 9.1 instead of 10.0 then the URLs within ownCloud will be generated wrongly.

**Comment by Emil-G** [comment]
@kdslkdsaldsal - Yes, it was the Theme that was pointing to 9.1. Sorry about that! 
Cheers,
Emil
