### ISSUE TITLE
Theme reverted to default after upgrade

### ISSUE THREAD

**Issue by iget-master** [owncloud/core#28386]
### Steps to reproduce
1. Create a custom theme under `/themes/YourThemeName`
2. Define theme under `/config/config.php`
2. Upgrade Owncloud server
3. The theme under `/config/config.php` will be reverted to `''`

### Expected behaviour
It should just keep the theme as I set previously. If any breaking changes was released, it should WARN me and confirm, but never change my config without ask.

### Actual behaviour
It just changes the config to default theme, without asking or warning.

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Nginx 1.10.3
**Database:**
MySQL 5.7
**PHP version:**
7.0.18
**ownCloud version:** (see ownCloud admin page)
9.1.6
**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "och514zeyrtp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domain.com.br"
        ],
        "datadirectory": "\/mnt\/owncloud-data",
        "overwrite.cli.url": "https:\/\/cloud.domain.com.br",
        "dbtype": "mysql",
        "version": "9.1.6.2",
        "dbname": "***",
        "dbhost": "***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "mail_smtpmode": "smtp",
        "mail_from_address": "cloud",
        "mail_domain": "domain.com.br",
        "mail_smtphost": "smtp.domain.com",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "theme": "iget",
        "loglevel": 2,
        "maintenance": false,
        "trashbin_retention_obligation": "auto, 3",
        "versions_retention_obligation": "auto, 3"
    }
}

```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by kdslkdsaldsal** [comment]
That should be already solved with the new theming in oC X/10.0 where themes are now apps:

https://doc.owncloud.org/server/latest/developer_manual/core/theming.html

I guess this can be closed then as the old theming probably won't be touched.

**Comment by iget-master** [comment]
I disagree that this should be closed, 9.x still supported...

**Comment by kdslkdsaldsal** [comment]
Supported doesn't mean that stuff which works as designed (see e.g. https://github.com/owncloud/core/issues/17221#issuecomment-116551216) will get new functionality or changed.

Such things is only happening on major upgrades (like e.g. done for oC 10) where this is already fixed.

**Comment by PVince81** [comment]
Auto-disabling theme in 9.x works as designed. This was to avoid broken themes to break the upgrade process. See https://github.com/owncloud/core/issues/19271.

Please try with ownCloud 10 with "theme as app". Such apps are not disabled any more during upgrades.
