### ISSUE TITLE
Display server name in admin page

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#28382]
From https://github.com/owncloud/core/pull/27238#issuecomment-314748410

**Comment by mmattel** [comment]
Possibly to be added here:

https://github.com/owncloud/core/blob/54150e7f64250d4c5774ec80714e3ff4e73c1fe6/lib/public/Util.php#L730
``'productname' => ''];`` to be changed to ``'productname' => '';``
``'hostname' => "];``

https://github.com/owncloud/core/blob/54150e7f64250d4c5774ec80714e3ff4e73c1fe6/lib/public/Util.php#L736
``$values['hostname'] = gethostname();``

(sorry no time to do it, dev server is down)
