### ISSUE TITLE
phpredis rediscluster del instead of redis delete

### ISSUE THREAD

**Issue by felixboehm** [owncloud/core#28393]
When using distributed caching with redis.cluster config, throws error "method RedisCluster::Delete not found"

For redis a delete method is called here:
- https://github.com/owncloud/core/blob/master/lib/private/Memcache/Redis.php#L72
- https://github.com/owncloud/core/blob/master/lib/private/Memcache/Redis.php#L84

This calls phpredis::Delete (https://github.com/phpredis/phpredis/blob/develop/php_redis.h#L48)

But if used with Rediscluster, this method does not exist.
RedisCluster:del exists instead: https://github.com/phpredis/phpredis/blob/develop/redis_cluster.h#L134

@PVince81

**Comment by PVince81** [comment]
how urgent is this ? would assign @butonic here but he's away

**Comment by DeepDiver1975** [comment]
I know the code base as well - self assigned

**Comment by felixboehm** [comment]
RedisCluster just does not work at all. Might also affect transactional file locking in other code pathes.

**Comment by DeepDiver1975** [comment]
I'll use del() on both Redis and RedisCluster - see https://github.com/phpredis/phpredis/blob/develop/redis.c#L835

**Comment by felixboehm** [comment]
Another delete, see L82
https://github.com/owncloud/core/blob/51cb355bdfe1159efd57bf5750539c53fab82dbf/lib/private/Memcache/Redis.php#L82
