### ISSUE TITLE
Problem with duplicate documents and photos folder after upgrade to oc10

### ISSUE THREAD

**Issue by mario7770** [owncloud/core#28402]
All users in OC 9.1.6 which have folders documents and photos with first small letter after upgrade to OC 10 folders documents and photos duplicate with folders Documents and Photos (without content)
 
### Steps to reproduce
1. Update 9.1.6 to 10.0.2
2. open oc in any browser or client
3. duplicate documents and photos

### Expected behaviour
Tell us what should happen
I want to see only one documents and photos folder

### Actual behaviour
Tell us what happens instead
oc create Documents and Photos folder even I have documents and photos

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** MySQL 5.7.18

**PHP version:** PHP 7.0.15

**ownCloud version:** 9.1.6
**Updated from an older ownCloud or fresh install:**updated

**Where did you install ownCloud from:** from OC web page

**Comment by PVince81** [comment]
Please try running the SQL queries listed in the first post of https://github.com/owncloud/core/pull/28253#issue-239230434

If any of these is giving you results, it means that your filecache is corrupted for some reason.

**Comment by mario7770** [comment]
Thanks for your answer.
I try all four queries.
Only on second I have result, but all records are from one user.
My problem is with all users with small letter d and p (documents and photos)
Users with capital letter d and p don't have problem.
Once more, thank you.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
