### ISSUE TITLE
occ user:add can add invalid email address

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#28425]
### Steps to reproduce
1. php occ user:add --email abc userxyz
2. login as userxyz and go to Settings, Personal, General
3. change Email to abd
4. press "Change email"

### Expected behaviour
The email "abc" provided at step 1 should have resulted in an error message.
The rest of the steps should not be possible because the user would not have been created at step 1.

### Actual behaviour
The user is created with a known-invalid email.

### Server configuration
Current master 10.0.2+

The UI is doing validation, presumably calling setMailAddress in UsersController, which calls validateMailAddress.

occ command does not go through any path that tries to validate the supplied email address.

**Comment by phil-davis** [comment]
@tomneedham is this easy to fix?
ref: PR #28122

**Comment by tomneedham** [comment]
@phil-davis What do we do when an invalid email is supplied? Not create the user, or create but dont add the email? And if so, what return code.

**Comment by tomneedham** [comment]
Easy fix once we know what to do

**Comment by phil-davis** [comment]
Indeed, my imaginary use cases are:
As an oC admin
I want to add a new user from the command line and supply user attributes like display name and email address
In order to make my life easier
(in this case, probably the interactive command line admin should be told about the invalid email, and the user not be created. Then they can fix the typo in the command)

As an oC admin
I want to script adding new users from the command line and supply user attributes like display name and email address
In order to allow me to load a number of users at once, whose data comes in a file from some other place
(in this case, maybe the invalid email should be reported, but the user still be created. Then after the script is run someone can look at the invalid email addresses and fix them up in the webGUI, or maybe the user should not be created???)

**Comment by phil-davis** [comment]
@tomneedham I think this is complete. The code that you did fails the whole user:add if the email address is invalid, which was the solution agreed in the discussion of PR #28426 and looks good.

Closing
