### ISSUE TITLE
Improvements to user avatar interface / provisioning

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#28428]
See: https://github.com/owncloud/user_ldap/issues/106

Quote @butonic:

>caused by updating quota or email properties, which trigger an update of the addressbook cards by the card dav backend, which triggers fatching avatars, which triggers fs initialization, which takes ages ... several PRs incoming, but still needs

  - [ ] a new interface for avatar provisioning and probably -> https://github.com/owncloud/core/issues/20973
  - [ ] Performance -> https://github.com/owncloud/core/issues/26585
    - [ ] a better fs for avatars 
    - [ ] no longer initialize the fs for every user because the avatars now reside in data/avatars instead of user homes

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by SamuAlfageme** [comment]
Linking some "Avatar" issues that caught my eye as related in the original comment.
