### ISSUE TITLE
Review usage of integers for potential overflow

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#28429]
Recently we've seen several cases of columns of type `integer` reach their maximum of `2,147,483,647` ( 🎉  for some awesome big instances running OC!). We should take a moment to ensure we are future proofed for other fields where this may become a problem.

![screen shot 2017-07-18 at 11 31 02](https://user-images.githubusercontent.com/660805/28312884-a0d45516-6bac-11e7-9a25-3bdda8642b52.png)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by phil-davis** [comment]
This kind of thing needs to be looked at to maintain quality for the future.
Maybe the bot could be disabled for issues that are tagged with particular labels - e.g. "technical debt" here. If someone has bothered to look at the issue and label it as (for example) "technical debt" then it has been decided to be "worthwhile" (even if not priority).
