### ISSUE TITLE
Create link share dialog out of focus

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#28427]
### Steps to reproduce
OC 10.0.3 git

1. Safari 10.1.1 click the share button on a file row
2. Click create public link

### Expected behaviour
Should be a nice dialog

### Actual behaviour
Dialog appears slightly out of focus / fuzzy / makes me feel dizzy.

![screen shot 2017-07-18 at 10 57 01](https://user-images.githubusercontent.com/660805/28311575-ff5f329a-6ba7-11e7-99fd-9100c1eddcb6.png)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
