### ISSUE TITLE
Additional Folder/File Right: Selective Client Sync

### ISSUE THREAD

**Issue by Omnimercador** [owncloud/core#28433]
This is an enhancement request, rather than an issue report. @hodyroff advised to post it here, rather than at central.owncloud.org.

We use Owncloud Community edition in a small office environment, where we also retain strict Chinese walls. We cater for this use by having a single Server Admin User who shares new project folders to the specific project team members - all project-specific content is then created in that folder, with access limited to the project team.

When projects end, the server admin does not cancel shares, as staff at times need to refer back to old work. However, this is suboptimal from a DLP perspective, as client sensitive (old) data is sitting on a whole lot of laptops (never mind that it also clogs up SSD drive space)

### Expected behaviour

It'd be great if the sharer of a folder/document could also set a right to determine whether a folder/document is available for client sharing or not. In effect, new / ongoing projects would allow for client sharing (and also accessible via the web interface), all old projects would only be available for web checking (and deleted off the client machines when the right is set).

The application here is different to what is currently available that allows users to selectively sync, and switches that power to the folder/document admin.

### Actual behaviour
Currently only the user can choose what to sync in the client, not the admin.

**Comment by PVince81** [comment]
The admin can use the firewall app to block client access for folders tagged with a specific tag. The folders in question can be tagged by users/sharers using system tags (sidebar on the right in the web UI).

**Comment by Omnimercador** [comment]
great approach - thanks for that. 

Will the change of tags also trigger a removal of the files that have previously been synced? I imagine not...

**Comment by PVince81** [comment]
Setting the tags will only block access, so the clients will get 403.

Not sure how the clients will behave if the folder was accessible before and now isn't. It is likely that the local files will be kept to prevent data loss.

**Comment by PVince81** [comment]
I'll close this in favor of https://github.com/owncloud/core/issues/26311 which proposes another technical approach..
