### ISSUE TITLE
Validate email before sending out public link from dialog

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#28451]
### Steps

1. Create a public Link
1. Enter a wrong Mail Address (e.g. without @)
1. Click save

### Expected

Link not saved, error message, dialog still there.

### Actual

Dialog reappears four times.

### Version
10.0.1

@felixheidecke can you have a look ?

**Comment by SergioBertolinSG** [comment]
The approach used to fix this issue doesn't tell the user what is the problem with the email.
It is not possible to turn red this text field when it is not valid?

![screen shot 2017-11-28 at 15 26 43](https://user-images.githubusercontent.com/9048796/33324711-ad14856e-d450-11e7-940b-89f62260decd.png)

Or change the text here and say the email introduced is not valid?

![screen shot 2017-11-28 at 14 08 15](https://user-images.githubusercontent.com/9048796/33324803-edf31b36-d450-11e7-8341-26780c2e1447.png)

**Comment by PVince81** [comment]
Seems the PR only fixes the issue about the four duplicated dialogs but doesn't fix the UX.

I see the ticket is already set to 10.0.3 as it was a 10.0.3 fix. @SergioBertolinSG please reopen a separate ticket and set to QA to have it fixed for 10.0.4. Thanks

**Comment by SergioBertolinSG** [comment]
New ticket for 10.0.4 here: https://github.com/owncloud/core/issues/29703
