### ISSUE TITLE
Groups problems

### ISSUE THREAD

**Issue by pfuentes1402** [owncloud/core#28454]
Hello, I am using owncloud 10 and I want create groups with only N users restrictions and limit storage. It is posible in this version? Can I resolve this??

For example: I want as super admin, create a group with his group admin. And i want the group admin creates only 10 users and no more. Every user has only 2gb of storage and no more.

**Comment by kdslkdsaldsal** [comment]
@pfuentes1402 Please note this is a bugtracker. Questions for ownCloud usage (like whats possible or not) needs to go to http://central.owncloud.org/

The group admin feature is more or less basic and doesn't provide what you're looking for. There are various different open feature request to enhance the possibilities:

https://github.com/owncloud/core/issues/1347, https://github.com/owncloud/core/issues/3362, https://github.com/owncloud/core/issues/19165
