### ISSUE TITLE
[files_app] Right-click > Copy Link should work as "private link"

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#28465]
ownCloud has a "private links" feature. In the web UI, you can copy them from the details view of every file or folder. But you can also use the link copied from the browser address bar as a private link.

Other people are used to right-click on a element, and if it's a link, browsers show a "Copy Link" feature in the context menu. Sadly, this link don't work as a private link.

Can this link be tweaked or modified with some JS magic to make it work as a private link?

**Right-click on a file:**
![cursor_and_hacker-songs_-_files_-_owncloud_and_issues_ _owncloud_core](https://user-images.githubusercontent.com/214010/28469112-7cef3a22-6e35-11e7-9fa4-211262bae73f.png)

**Right-click on a folder:**
![cursor_and_hacker-songs_-_files_-_owncloud](https://user-images.githubusercontent.com/214010/28469113-7cf1cb02-6e35-11e7-8327-514188f600cf.png)

### Steps to reproduce
1. Right-click on a folder and copy link
2. Send copied link to another user
3. Other user has different folder structure, so copied link don't open the right folder

### Expected behaviour
Links should contain an identifier (fileid) to make it work as "private link"

### Actual behaviour
Copied link don't open the right folder

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache 2.4.18

**Database:**
5.7.19

**PHP version:**
7.0.15

**ownCloud version:** (see ownCloud admin page)
10.0.2

**Updated from an older ownCloud or fresh install:**
Updated manually

**Where did you install ownCloud from:**
???

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "10.0.2.1",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "admin",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - customgroups: 0.3.1
  - dav: 0.2.9
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.0
  - files_texteditor: 2.2
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - guests: 0.4.1
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - theme-example
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome 59

**Operating system:**
macOS Sierra 10.12.5

**Comment by PVince81** [comment]
The problem is that if we modify the href of this link to be the private link, then doing a middle click (open in new tab) would open that one link instead of downloading.

**Comment by michaelstingl** [comment]
In Chrome 61 on macOS Sierra 10.12.6, I click with "option/alt" key to trigger the immediate download of a link. I would expect open it in a new tab if I "middle click".

**Comment by PVince81** [comment]
Whatever the action is on any platform, there can only be a single `href` value for the link.
Everything else is a huge hack and not necessarily possible.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
Won't fix, unless there are better ideas
