### ISSUE TITLE
Renaming into subfolders or parent folders

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#28475]
### Steps to reproduce
1. Create foldera and folderb in the webUI at the top level of a user account files
2. Rename folderb, putting in foldera/folderb

### Expected behaviour
This is a relative folder path. folderb should end up in foldera,
and folderb should not be listed in the top (original) folder.

### Actual behaviour
A folder is shown in the original (top) folder, called foldera/folderb
Note: if you click on that, it takes you to the "correct" place - listing folderb inside of foldera - so nothing explodes. And if you click on the real foldera, you see that folderb is indeed listed there.

On refreshing the page, or navigating down and up the folder tree, the "odd" "foldera/folderb" entry foes away. So it is just a UI artifact, probably from the fact that the move-rename succeeds and so the UI decides to display the resulting "file" in the current folder.

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
php dev
**Database:**
mySQL
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
current master as at now

**Comment by phil-davis** [comment]
And there are plenty of variations on this theme:
1. with folderb inside foldera, rename folderb to "../folderb"
A "weird" "../folderb" is shown in the foldera list.
Click on it and an "Invalid path" error is displayed - but you do get taken up a level and are shown the parent folder that now contains foldera and folderb

2. rename a file using a relative path, e.g. rename x.txt to foldera/x.txt
the file is moved into foldera, but a listing is left showing called "foldera/x.txt"
and the same kind of thing if you use "../" to rename a file upwards.

If you do not refresh the current page, actually you can open the details/sharing panel or even delete the file/folder from the "ghost" entry. Which is all technically "correct" because it is working with some file id that is in foldera/x.txt or whatever.

**Comment by phil-davis** [comment]
1. should it be allowed to enter relative paths in the rename text box?
(it works now)
If yes, then the resulting behavior of the "ghost" entries needs cleaning up.
If no, then ban entry of such relative paths and so there is no possibility to get the "ghost" entries.

**Comment by PVince81** [comment]
Uh oh... slashes should not be allowed in the rename box. Bug.

**Comment by phil-davis** [comment]
For techie nerds it works nicely - the file does actually get moved to the specified path. It is just the leftover that the UI leaves behind until the next refresh.
But I guess techie nerds can go without this accidental relative pathing rename "feature".

**Comment by PVince81** [comment]
The reason why the UI is broken is because this is not a feature, so the UI code doesn't take this case into account. I'd rather block this instead of having further code paths in the already messy code.

**Comment by phil-davis** [comment]
That is easy to fix, and I was in and around that code recently anyway.
PR #28483

**Comment by individual-it** [comment]
I would have declared this bug to be a feature, soo sad

**Comment by phil-davis** [comment]
If it was kept as a feature there would be lots of edge cases to find and fix/handle. But yes, for techie nerds who understand it, it can be handy.

**Comment by phil-davis** [comment]
Backport to stable10 PR #28490

**Comment by phil-davis** [comment]
master and stable10 backport merged.
