### ISSUE TITLE
Improvements to whole data decryption process

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#28471]
We should consider some improvements to our decryption process.

 - [ ] Better logging on the decryption
 - [ ] Proper return codes to permit scripting
 - [ ] Accept input via arguments and/or environment to permit scripting
 - [ ] Parallel decrypt command to reduce decryption time (testing has shown storage seek times can be the limiting factor and parallel execution can greatly speed up the overall decryption)
 - [ ] Improved documentation
  -[ ] Better handling of errors so as to not block / exit long running scripts which require constant monitoring by the admin

For reference: ~200 users /  1.3TB (post-encryption disk size) is taking ~90 hours (in maintenance mode) due to required manual operation of the commands and lack of parallelisation/ automation. 

Needs triage to evaluate which are necessary / priority of this.

**Comment by tomneedham** [comment]
Heavy database usage reported, working on getting performance_schema data to analyse query statistics

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
