### ISSUE TITLE
Questions to custom GroupBackend/virtual groups

### ISSUE THREAD

**Issue by cortho** [owncloud/core#28473]
With the guests virtual group I crossed some issues or question regarding GroupBackends and virtual groups in general. Help from experienced developers is highly welcome.

* **Trashbin icon for deleting groups should not be visible**
virtual groups cannot be deleted. Is this something, core provides a functionality for, or is this better handled in the app (e.g. jquery remove)
see https://github.com/owncloud/guests/issues/121
*  **Misleading actions in Users panel**
In the admin frontend virtual groups a normal group. So it is possible to make an admin out of a guest and vice versa even when the backend does not support this.
see https://github.com/owncloud/guests/issues/91

There is the _isVisibleForScope_ in GroupBackend class (see https://github.com/owncloud/core/blob/master/lib/private/Group/Backend.php#L133), which looks to me, as if this could do some magic. After some search and grep I only found the two scopes _sharing_ and _management_. The latter goes in the desired direction, but when I remove this scope, all management functionality is lost, so the possibility to display this group (and their users) in the side tab is lost as well.

Is there any documentation, I didn't find? Which scopes are currently existing? (probably we should make constants out of this) 

Which parts should be handled by the backend and which by core?

Feel free to close this issue, when this is not the correct place, but please point out, where I should ask this question.

Edit: added link to code

**Comment by felixboehm** [comment]
@PVince81 can you help here

**Comment by PVince81** [comment]
I don't remember what the decision was about the guest groups. I'd think the guest group isn't supposed to appear in the users page.

But if it does, the group backend should not return the `deleteGroup` action as supported when the function `getSupportedActions()` is called. If you did that and the trash icon didn't disappear, then it's likely a bug.

In general I think we never had virtual groups before in OC < 10.0 and this concept was added recently with the customgroups and guests app. It is likely that some fixing is needed in core to properly adjust the UI based on group backend capabilities.
