### ISSUE TITLE
Duplicated mount configuration after going back during oauth2 flow

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#28479]
### Steps to reproduce
1. Go to the admin settings and configure a gdrive mount
2. Setup the client id and secret, and click on "grant access"
3. During the oauth2 flow in the browser, go back with the browser navigation

### Expected behaviour
Admin settings page should show without the previous mount being configured. Showing a wrong state might be acceptable as long as access can be granted later.

### Actual behaviour
Duplicated configuration of the previous mount is shown.

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** stable10 (10.0.2 at July, 25th)

**Updated from an older ownCloud or fresh install:** fresh install

**Browser:** firefox 50.1.0

**Comment by jvillafanez** [comment]
This happened twice in a row after a fresh installation, both in admin and personal settings, but I couldn't reproduce it afterwards following the same steps.

**Comment by PVince81** [comment]
Yeah I remember seeing this before too, thanks for reporting

**Comment by davitol** [comment]
![screen shot 2017-09-14 at 13 43 22](https://user-images.githubusercontent.com/10596560/30428740-0127aafa-9955-11e7-9ba6-5bcbaee2d099.png)

Also reproduced with oC 10.0.3.RC1 version. Something to be fixed in the future

**Comment by PVince81** [comment]
setting to p2-high and "planned", this seems to happen more often than I thought

**Comment by PVince81** [comment]
@jvillafanez can you have a look ?

**Comment by jvillafanez** [comment]
Looks like the click-back messes might mess with the "natural" oauth1/2 flow and it's causing this issue. Still under investigation.

**Comment by jvillafanez** [comment]
<img width="961" alt="screen shot 2017-10-04 at 11 11 15" src="https://user-images.githubusercontent.com/1477829/31168226-e3bb96d4-a8f4-11e7-8129-4f196637c0cc.png">

Looks like the duplication might be "valid" in the sense that those mounts are saved in the DB.

Reproduced by crazy-clicking the "grant access" button over a new mount point. Multiple queries are sent to the server to save that mount point which causes the duplication.

**Comment by jvillafanez** [comment]
Looks like this has been broken from the beginning since it's always sending duplicate requests just clicking once in the button. The fact that usually only one storage appears is likely because the rest of the duplicate requests don't trigger or reach the server before the browser changes the page.

<img width="961" alt="screen shot 2017-10-04 at 14 32 42" src="https://user-images.githubusercontent.com/1477829/31175961-6f1a604a-a911-11e7-993c-3c078f666b3d.png">

I've constantly reproduced the error adding a debugger and breaking the js code (to prevent the browser to change the page) near the window.location around line 1455 of the settings.js file. There are always several requests to an oauth endpoint. The number of requests increases according to the mounts that are set.

**Comment by jvillafanez** [comment]
Ongoing fix in https://github.com/owncloud/core/pull/29145

**Comment by jvillafanez** [comment]
Fix merged and expected in 10.0.4
