### ISSUE TITLE
Admin General Settings: Links lead to 404 Not Found

### ISSUE THREAD

**Issue by CoderFX** [owncloud/core#28498]
Tried to follow
"To migrate to another database use the command line tool: 'occ db:convert-type', or see the documentation ↗."

Result:
404 Not Found at 
https://doc.owncloud.org/server/10.0/admin_manual/configuration_database/db_conversion.html

**Comment by cortho** [comment]
To clarify: These are _Security & setup warnings_ links from Admin General Settings.
Another 404: https://doc.owncloud.org/server/10.0/admin_manual/configuration_files/files_locking_transactional.html

**Comment by cortho** [comment]
will be fixed in owncloud/documentation so closing here.
