### ISSUE TITLE
UI tests on Travis running near time limit

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#28503]
The UI tests on Travis are taking around 40 minutes nowadays. Travis kills jobs after 50 minutes. Sometimes if there are longer delays between SauceLabs and Travis the tests overrun the time limit and get killed by Travis.

* [x] Design an infrastructure for putting sub-sections of UI tests into logical suites.
* [x] Sort out Travis to run the suites as separate (shorter) jobs.
* [x] Document how to run a single suite or all suites on a development system

**Comment by DeepDiver1975** [comment]
@tboerger move to drone? Once we are done with the rest.

**Comment by phil-davis** [comment]
Yes, that is definitely an option. Then we can split into whatever jobs (by browser type like now and logical grouping of tests into suites...) that suit a balance of:

- timely elapsed-time completion of CI for feedback to real people (i.e. do as much in parallel as "possible")
- capacity of the underlying hardware (i.e. there will be some limit of parallel things that kills the hardware/memory/OS and some softer limit of parallel things where there is no effective elapsed-time gains because raw IO limits or... are reached)

and jobs are not going to get killed if they do take a bit longer than usual elapsed time.

**Comment by phil-davis** [comment]
@DeepDiver1975 @PVince81 please have a look at PR #28528 - that splits into 2 suites and gets the "infrastructure" in place (actually there was not much needed - it was reasonably easy)

Any future move of these CI jobs to Drone or... will benefit from having the choice of doing multiple parts in parallel. And for now, this prevent the job running for 50 minutes and getting killed.

**Comment by phil-davis** [comment]
Code merged to master in #28528 
Backported to stable10 in #28531

**Comment by individual-it** [comment]
code was merged to master and stable10. closing?

**Comment by phil-davis** [comment]
Documented in https://github.com/owncloud/documentation/pull/3250

**Comment by phil-davis** [comment]
Drone move is another future issue. Closing here.
