### ISSUE TITLE
Composer autoloader not found, unable to continue. Check the folder "3rdparty"

### ISSUE THREAD

**Issue by RBGaming** [owncloud/core#28522]
when i go to http://localhost/owncloud/   it says "Composer autoloader not found, unable to continue. Check the folder "3rdparty"."﻿

**Comment by kdslkdsaldsal** [comment]
@RBGaming Please fill out the issue template shown when creating a new issue:

https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

This is shown for a reason and is asking you various things which are currently completely missing.

**Comment by RBGaming** [comment]
theirs no point i'm using 8.0.8 because i'm on window 10 and i'm following this tutorial to a point https://www.youtube.com/watch?v=C6y_g5v6CKc

**Comment by kdslkdsaldsal** [comment]
Unfortunately windows is an unuspported platform for ownCloud 8+ for the resons explained here:

https://owncloud.org/blog/owncloud-server-8-1-will-not-support-windows-as-server-platform-natively/

Please move on to a linux based operating system.
