### ISSUE TITLE
No error message at wrong cron settings

### ISSUE THREAD

**Issue by matthias882** [owncloud/core#28533]
### Steps to reproduce
1. Set your cron in owncloud administration page to "cron" but you are using a Webcron service
2. Configure your Webcron service to call the page cron.php every 15 minutes
3.

### Expected behaviour
You should get an error message that your config is wrong

### Actual behaviour
Admin-page says the cron runs correct

### Server configuration

**ownCloud version: 9.xx**

My solution: 
The cron php generates a JSON-error-message, but if the caller is a webcron-service nobody can see this error. (cron.php line 138)
```
...
if ($appMode == 'cron') {
// Cron is cron :-P
OC_JSON::error(['data' => ['message' => 'Backgroundjobs are using system cron!']]);
}
...
```
In this "If" you should also generate an message for the log-file
```
...
if ($appMode == 'cron') {
// Cron is cron :-P
OC_JSON::error(['data' => ['message' => 'Backgroundjobs are using system cron!']]);
\OCP\Util::writeLog('cron', 'cron is called by a website but settings are CLI!', \OCP\Util::DEBUG);
}
...
```

It took me one day to find out why my background jobs are not working. Log and the last cron execution on the admin page said "everything is okay, cron is working fine"
(I looked in the oc10 cron.php, there is the same problem.)

Matthias882

**Comment by DeepDiver1975** [comment]
Pull request welcome - THX

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
