### ISSUE TITLE
Scheduling Sync in OWNCLOUD

### ISSUE THREAD

**Issue by R-yogesh** [owncloud/core#28535]
Hi,

I need to know, whether it is possible to schedule sync for every 5 minutes for each user, consider we have more than 100 users, we need to schedule sync by allocating 5 minutes per user. please help.

**Comment by kdslkdsaldsal** [comment]
@R-yogesh Please note this is a bugtracker for ownCloud. Questions like this needs to go to https://central.owncloud.org/
