### ISSUE TITLE
Wrong Browser in personal Security settings

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/core#28557]
### Steps to reproduce
1. Login with a iPad
2.
3.

### Expected behaviour
Tell us what should happen
Show Safari is the used browser, if i login with an iPad

### Actual behaviour
Tell us what happens instead
Show this for a Safari browser: "Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1"
### Server configuration
**Operating system**:
Raspbian
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
PHP5
**ownCloud version:** (see ownCloud admin page)
10.0.2
**Updated from an older ownCloud or fresh install:**
fresh install
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by kdslkdsaldsal** [comment]
> Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1

Which is exactly the user-agent of the browser on your iPad and contains "Safari/602.1" which is Safari.

What are you expecting to see instead?

**Comment by Bobgermany** [comment]
First you read mozilla and this is a little confusing.

But the Browser Info Form an other website show the same text. I think this is not very user-friendly.
I don't have a problem with this, but I thought it would be a mistake.

**Comment by Bobgermany** [comment]
Why do we write this "Firefox / Windows 10" for a Firefox browser of Windows 10 and "Safari / iOS 10.3.3" for an iPad? This is much more user-friendly and the user understands this much easier than the current text.

**Comment by kdslkdsaldsal** [comment]
The text is directly reported by your browser (see e.g. http://www.whoishostingthis.com/tools/user-agent/).

I guess this is by design to have some sort of uniqueness in the overview, as you can't distinguish if the session is from the same system or from different ones.

But maybe @PVince81 can tell you more

**Comment by PVince81** [comment]
I'd see this ticket as an enhancement request to interpret the user agents to display a more user-friendly text instead. Not sure if this can be done reliably.

If we do, we still need to have a tooltip/button to be able to switch back to the technical user-agent.

cc @pmaier1 in case this is of interest

**Comment by kdslkdsaldsal** [comment]
In the scope of this it might help to add an additional column containing the IP of that session to the list as if e.g.:

Firefox / Windows 10
Firefox / Windows 10

is shown twice you can't tell which session belongs to which device.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by pmaier1** [comment]
> cc @pmaier1 in case this is of interest

Interpreting the user agents and just listing e.g. "Firefox 57 on Ubuntu" (like e.g. Dropbox does) would be a cool enhancement for users, right.
