### ISSUE TITLE
sharing-v1.feature fails in master

### ISSUE THREAD

**Issue by guruz** [owncloud/core#28558]
```
18:37:09 --- Failed scenarios:
18:37:09 
18:37:09     /var/lib/jenkins/workspace/owncloud-core_core_master-34LTVSCLINVJJ27NGKSEQIHMECTKVSQK3BNUXCMTIMC23OPFL6GA/tests/integration/features/sharing-v1.feature:914
```
(seen this when looking for something else)

https://jenkins.owncloud.org/job/owncloud-core/job/core/job/master/910/console

**Comment by SergioBertolinSG** [comment]
Yes, that case fails randomly. There was an improvement to avoid this, but didn't work. @PVince81

**Comment by guruz** [comment]
Yup again in [912](https://jenkins.owncloud.org/view/pipeline/job/owncloud-core/job/core/job/master/912/console)

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/issues/28950
