### ISSUE TITLE
Receiver of a share from a external mount point cannot see the shared files

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#28564]
### Steps to reproduce
1. Setup an admin mount point with a specific configuration, only for the admin. Make sure sharing is enabled for the mount point
2. Setup **the same** mount point as personal for the admin. The mount point configuration must be the same as the admin one. Sharing must be disabled for this mount
3. Share a file from the mount point to another user
4. Login with the other user's account

### Expected behaviour
Shared file should show up

### Actual behaviour
Shared file is missing. The user account can't access to the shared file.

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** master (Aug, 2th 721b36d0aefd673e9cd418e18ee21a4fd16874fd)

**Updated from an older ownCloud or fresh install:** fresh install

**Are you using external storage, if yes which one:** reproducible with any external storage

**Are you using encryption:** no

As a workaround, you'll need to enabled / disable sharing for both mounts.

@DeepDiver1975 @PVince81

**Comment by PVince81** [comment]
Hmm, could it be related to the fact that they both share the same storage string id ? But they should be different mount entries in the mount config tables.

**Comment by hodyroff** [comment]
One mount point should only be possible for one owner/user one time. For me, for now its sufficient to document that, if easy or when this is hit by users/customers we maybe need to forbid it. Or is there a good user story why somebody would want to do that?

**Comment by PVince81** [comment]
@hodyroff currently system-wide mount points can be assigned to multiple users/groups (field "applicable") by an admin. Such mount points can only be created by admins. So this is a supported case.

Now with the case above, I think the proper way would be that the admin adds the user in the "applicable" field to give the user access to that share instead of letting the user add a new mount for themselves.

**Comment by jvillafanez** [comment]
It seems the admin configuration is overlapped with the personal one, so what is used is whatever the personal configuration has. Since the personal configuration had the sharing disabled that would explain why the shared files are missing.
If we switch the sharing configuration so the personal mount has sharing enabled but the admin mount has it disabled, the personal mount will take precedence, so sharing will be enabled and the shared files will appear.

I think this mount overlapping has been discussed already. This seems another issue caused by that mount overlapping.

**Comment by PVince81** [comment]
Ah, it wasn't clear to me that both mounts use the exact same mount point name... This is not good practice... and also an unsolvable bug (unsolvable without tearing up a hole in this messy mount system): https://github.com/owncloud/core/issues/10511

I'd close this in favor of https://github.com/owncloud/core/issues/10511 then...

**Comment by jvillafanez** [comment]
> Ah, it wasn't clear to me that both mounts use the exact same mount point name...

The mount point name is different, but the configuration is the same in both.

**Comment by PVince81** [comment]
Ok then it's a different issue. The end user should see both mount points, one with sharing enabled and one without

**Comment by davitol** [comment]
Due to it is not a very common configuration let's set a lower priority

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
