### ISSUE TITLE
Allow files:scan in maintenance mode

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#28561]
Because sometimes it can take a long time and sometimes the admin might want to make sure no one is using the storages when doing a scan: occ files:scan should be available in maintenance mode.

Also, would make it possible to run the repair switch from https://github.com/owncloud/core/pull/28253 in maintenance mode.

**Comment by PVince81** [comment]
I suspect that for this we'll need to move the command from "apps/files" to "core".

It would likely make sense to move the other oc_filecache related commands to core.

**Comment by PVince81** [comment]
Actually it works in single user mode, so maybe no changes needed...

**Comment by cdamken** [comment]
Probably, to be sure that nothing else happens we can force to a Repair page adding in 
```
'overwritehost' => '',
'overwrite.cli.url' => '',
```
until its repaired

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
People already reported being confused after occ upgrade that the "files" namespace was not avaible because they were still in maintenance mode.

We should move the scan command to the core namespace (and add an alias/placeholder in "files" for backwards compatibility)

**Comment by theclem54** [comment]
singleuser mode, whilst protecting files from operations during a scan, is no good for user communication, whereas maintenance mode provides a useful notification on the landing page (homepage?).

Not sure if this should be a new feature request for better communication to users attempting to use the service when it is in singleuser mode?
