### ISSUE TITLE
Assign a Tag to a File  (documentations error)

### ISSUE THREAD

**Issue by lazarohcm** [owncloud/core#28567]
So, I was following the [documentation](https://doc.owncloud.org/server/10.0/developer_manual/webdav_api/tags.html#assign-a-tag-to-a-file) to assign a tag to a file and found out that the parameter order is wrong in there. It shows the tagid as first parameter, but I could only assign when I used the fileid as first.
I think that instead of:  `remote.php/dav/systemtags-relations/files/<tagid>/<fileid>`
It should be: `remote.php/dav/systemtags-relations/files/<fileid>/<tagid>`

Can someone confirm it for me?

(sorry if I'm addressing the doc error on the wrong place)

**Comment by PVince81** [comment]
@lazarohcm please send to https://github.com/owncloud/documentation

cc @settermjd

**Comment by phil-davis** [comment]
What you say is correct, e.g. the integration and UI tests access tags:
https://github.com/owncloud/core/blob/master/tests/TestHelpers/TagsHelper.php#L60
```
$path = '/systemtags-relations/files/' . $fileID . '/' . $tagID;
```
I will make a doc PR...
