### ISSUE TITLE
Use "latest" in the name the latest tarball and zip archives instead of the version number

### ISSUE THREAD

**Issue by settermjd** [owncloud/core#28571]
I appreciate that this might be counter-intuitive, but I'm suggesting it anyway. That "latest" is used instead of the current release's version number in the downloadable tarball or zip archive. For example, instead of https://download.owncloud.org/community/owncloud-10.0.2.tar.bz2 name it: https://download.owncloud.org/community/owncloud-latest.tar.bz2.

The reason I'm seeking this change is that this would make it easy to universally refer to them throughout the documentation and not have to update the link with every release. 

As an example, I'm currently working on https://github.com/owncloud/enterprise/issues/2082 and as part of the documentation for that issue, one of the steps is: "grab the server release tarball". To make it easiest for the user, I'm directly linking sections of that bullet point to the tarball and zip archive of the latest release. 

Unfortunately, these links will have to change with each release of the documentation. I've checked through the documentation and found that while [substitutions](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#substitution-references) are available, they don't work when creating links. 

FWIW, I've asked in the Slack & IRC channel but haven't had any advice as to a solution.

Given that, can the link name be changed?

**Comment by kdslkdsaldsal** [comment]
@settermjd There is already https://download.owncloud.org/community/owncloud-latest.tar.bz2 as well as https://download.owncloud.org/community/owncloud-latest.zip which is currently providing 10.0.2.

**Comment by tboerger** [comment]
@settermjd as @kdslkdsaldsal already said, these links already exist.
