### ISSUE TITLE
[stable9 & stable9.1] unit test are failing

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#28574]
![bildschirmfoto von 2017-08-03 13-28-27](https://user-images.githubusercontent.com/1005065/28919873-b3882192-784f-11e7-8581-31c55737dbc3.png)

![bildschirmfoto von 2017-08-03 13-30-48](https://user-images.githubusercontent.com/1005065/28919952-022e0f82-7850-11e7-88ce-3ccd895e132c.png)

**Comment by PVince81** [comment]
these look like some of the random failures that used to happen...

**Comment by DeepDiver1975** [comment]
> these look like some of the random failures that used to happen...

no - consistent failing every time

**Comment by PVince81** [comment]
@felixboehm depending when we want to release the maintenance branches, we'll need to look into this.

Setting to p1 for said releases

**Comment by PVince81** [comment]
stable9.1 randomly successful build now: https://jenkins.owncloud.org/job/owncloud-core/job/core/job/stable9.1/

**Comment by PVince81** [comment]
this one https://jenkins.owncloud.org/job/owncloud-core/job/core/job/stable9.1/89/

**Comment by PVince81** [comment]
green again on both branches... mysteries...

I do remember seeing these errors happening randomly... Let's hope it doesn't come back...

Not reproducible locally either.
