### ISSUE TITLE
Who directory is for my own theme?

### ISSUE THREAD

**Issue by Bobgermany** [owncloud/core#28583]
I have one theme directory in "apps/" with a subdirectory "theme-example" and i have a second theme directory in the main directory with the name "themes". In this directory is a README file for themes.

**Comment by DeepDiver1975** [comment]
Starting oc10 - themes shall be implemented as apps - the readme in the themes folder is legacy. https://github.com/owncloud/core/blob/master/themes/README
We might better remove it ... @PVince81 @phisch

**Comment by Bobgermany** [comment]
Yes, this is a good idea.
Thank you
