### ISSUE TITLE
ChunkingNG: Check free hd space before assembling file

### ISSUE THREAD

**Issue by guruz** [owncloud/core#28585]
Disclaimer: I have no idea how the server works and I don't have linux quotas or oC user quotas or anything configured. I see the code calls disk_free_space but I don't see anything disallowing uploads.

Scenario: My server's drive ran full and I got a "The computed checksum does not match the one received from the client." on the final MOVE of ChunkingNG.
So I checked using md5sum the chunks manually from ```uploads``` directory and they had the correct checksum. (compared to my local hd)

So my conclusion is that somehow the finished file did not get assembled fully but it was still attempted to create a checksum and see the file as finished.

(or something else was wrong...)

**Comment by PVince81** [comment]
Likely fixed in upcoming 10.0.3: the QuotaPlugin wasn't checking the headers on the final MOVE: https://github.com/owncloud/core/pull/28160

**Comment by guruz** [comment]
@PVince81 is your statement valid even if

> and I don't have linux quotas or oC user quotas or anything configured

?

**Comment by PVince81** [comment]
The quota plugin is always applied even if no quota is set. It calls `$this->view->free_space()` which either checks the free space on disk or the quota if one is set.

**Comment by PVince81** [comment]
Linux FS quota will likely not work and never worked before because PHP's `disk_free_space()` function doesn't return the FS quota value
