### ISSUE TITLE
Remove xcache and apc ....

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#28597]
# apc is unmaintained 

http://php.net/manual/en/intro.apc.php

# xcache is only available for php 5.6

last release 2014 - https://xcache.lighttpd.net/#News

Lets kill those as soon as we go for php7+ only

**Comment by DeepDiver1975** [comment]
> Lets kill those as soon as we go for php7+ only

target for 10.1 -> reopening

**Comment by patrickjahns** [comment]
What about APCu ? Besides locking, do we make use of it anywhere else?

**Comment by DeepDiver1975** [comment]
> What about APCu ? Besides locking, do we make use of it anywhere else?

yes - there are some code paths which use caches- Search for ICacheFactory
