### ISSUE TITLE
Skeleton dir for integration and UI tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#28602]
### Steps to reproduce
1. Set skeletondirectory in config.php ready to run UI tests, like:
```
'skeletondirectory' => '/home/phil/core/tests/ui/skeleton'
```
2. Run some UI tests - good
3. Now run some integration tests

### Expected behaviour
skeletondirectory should not be messed up by integration or UI tests

### Actual behaviour
1. integration tests set skeletondirectory to the value needed, but do not put back the previous value on the way out
2. UI tests expect the developer/tester to manually set the value of skeletondirectory before running the tests - that is also annoying

### Server configuration
test VM with current master as of 2017-08-07 (now)

**Comment by individual-it** [comment]
should be fixed by #28603 
and backported to stable10  #28610

closing?
