### ISSUE TITLE
Webdav API to access files by fileid

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#28615]
Have "remote.php/fileids/$fileid" redirect to "remote.php/dav/files/$userid/path/to/file"

It is likely that writing a Sabre plugin for this should be enough, not sure if we need a collection.
If we do write a collection for "fileids", the list of file ids **must not** be listable as it is global and not by user.

If the file id is not accessible for the current user, return 404 error.

This might be required for some automated tests.

@individual-it @michaelstingl @butonic @DeepDiver1975

**Comment by PVince81** [comment]
https://www.ietf.org/rfc/rfc4437.txt

**Comment by PVince81** [comment]
never mind, that looks more like symlinks.

We should do a simple redirect, always, from the proposed endpoint.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
still needed, reopening

**Comment by PVince81** [comment]
Alternative PR, see "Motivation" section for why it is a better approach: https://github.com/owncloud/core/pull/30383

**Comment by PVince81** [comment]
Not sure whether we should keep this PR here now that we have https://github.com/owncloud/core/pull/30383 which solves the original problem.

I could imagine situations in which someone has a file id (not a private link) and would want to search for the matching file in Webdav. Hmmm search?
