### ISSUE TITLE
Incomplete version update now showing "Internal Server Error"

### ISSUE THREAD

**Issue by olletsoc** [owncloud/core#28621]
### Steps to reproduce
1. used the internal updater
2. went through the stages ok till updating core
3. returned a server error now my OC is broken and returning 
"Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log."

### Expected behaviour
It should have updated to the current stable version

### Actual behaviour
It broke my app and now I can't see my files

### Server configuration
MACOS Sierra 10.12.6 (16G29)

**Web server:**
Linux

**Database:**
MySQL

**PHP version:**
5.6.21

**ownCloud version:** (see ownCloud admin page)
9

**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**
MediaTemple.net hosting

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** 

**Are you using encryption:** no?

**Are you using an external user-backend, if yes which one:** Webdav/...

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by kdslkdsaldsal** [comment]
@olletsoc Please:

1. Fill out the complete issue template (especially logfiles and exact version of ownCloud)
2. Clarify if "MACOS Sierra 10.12.6 (16G29)" is the OS of your server or the one of your desktop. I'm asking this because you have "Linux" stated at Webserver which is not a webserver but an operating system.

**Comment by DeepDiver1975** [comment]
no feedback -> close
