### ISSUE TITLE
Makefile:161: recipe for target 'core/vendor' failed make: 

### ISSUE THREAD

**Issue by singhabhinav81** [owncloud/core#28644]
During installing from ownCloud from git:
after giving the command "make" there is an issue for making "data" folder inside the "core".

Makefile:161: recipe for target 'core/vendor' failed
make: *** [core/vendor] Error 1

**Comment by DeepDiver1975** [comment]
are your permissions properly setup ?

please try to catch us on irc or central.owncloud.org to seek out for help - THX

**Comment by singhabhinav81** [comment]
what to do with this error?
Can&#039;t write into config directory!
This can usually be fixed by &lt;a href=&quot;https://doc.owncloud.org/server/10.0/go.php?to=admin-dir_permissions&quot; target=&quot;_blank&quot; rel=&quot;noreferrer&quot;&gt;giving the webserver write access to the config directory&lt;/a&gt;.

**Comment by DeepDiver1975** [comment]
Looks like you want to deploy a production server - not do this from git

please follow the docs - https://doc.owncloud.org/server/latest/admin_manual/installation/index.html

**Comment by singhabhinav81** [comment]
yes, I am installing it from git.  I want to contribute to owncloud.org
for that how can I contribute?

**Comment by DeepDiver1975** [comment]
for development I suggest to install owncloud somewhere in your home directory and use the php built-in web server which you can start in a shell - see http://php.net/manual/en/features.commandline.webserver.php

**Comment by singhabhinav81** [comment]
thank you

**Comment by phil-davis** [comment]
and some convenience scripts like ``tests/travis/start_php_dev_server.sh`` mentioned at:
https://github.com/owncloud/documentation/blob/master/developer_manual/core/ui-testing.rst

and look through the developer manual doc pages.

**Comment by singhabhinav81** [comment]
how can I understand codebase?

**Comment by singhabhinav81** [comment]
I am using testing with selenium and phpunit.

**Comment by sharidas** [comment]
@singhabhinav81 To understand codebase, there is no hard and fast rule. I would suggest to pick any task first and while implementing/fixing it you can explore the code base. I hope this helps.

**Comment by singhabhinav81** [comment]
thank you.
