### ISSUE TITLE
Review and adjust FS layer classes that have mandatory methods missing on interfaces

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#28656]
The following methods are expected to exist within the implementation of the filesystem layers but are actually missing on the interface:

- [ ] StorageFactory::wrap() is missing on IStorageFactory but used in the MountPoint class (see https://github.com/owncloud/core/pull/28646#discussion_r132656089)

@DeepDiver1975 @jvillafanez

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
