### ISSUE TITLE
change default slogan

### ISSUE THREAD

**Issue by felixboehm** [owncloud/core#28663]
In Standard (default) and EE Theme, change default slogan.

Related:
https://github.com/owncloud/core/blob/master/lib/private/legacy/defaults.php#L66

Suggestions:
- "store.share.work" (en, de?)
- "A safe home for all your data" (en), "Ein sicherer Ort für all Deine Daten" (de)

@felixheidecke

**Comment by felixheidecke** [comment]
Well … what does the corporate identity allow here? The website says **"A safe home for all your data"** so that's apparently what marketing wants to convey.
