### ISSUE TITLE
Win8.1 IE11 app menu title wraps

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#28687]
ownCloud 10.0.3beta on Win8.2 IE11 VM from modern.ie:

![win8 1-ie11-apps-menu](https://user-images.githubusercontent.com/277525/29311563-b92bac38-81b2-11e7-8a3c-8b5f041c8397.png)

@felixheidecke

**Comment by felixheidecke** [comment]
Funny … should have been fixed with https://github.com/owncloud/core/commit/ef52de136d4cf3c6a656accafded20d412b950a6#diff-3a70ba67d699e0a007eb8b22b7f878b6

I'm on it.
