### ISSUE TITLE
500 Connection Error

### ISSUE THREAD

**Issue by kleeman7** [owncloud/core#28699]
### Steps to reproduce
1. Try to access owncloud web interface. Getting error 500. 

### Server configuration
**Operating system**:
 Ubuntu Server 16.04

**Web server:**
 Apache2
**Database:**
 mysql
**PHP version:**
 Current
**ownCloud version:** (see ownCloud admin page)
current
**Updated from an older ownCloud or fresh install:**
Fresh install
**Where did you install ownCloud from:**
deb https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ 

**Are you using external storage, if yes which one:** local/smb/sftp/...
 No
**Are you using encryption:** yes/no
 No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
 No

### Client configuration
**Browser:**
Chrome
**Operating system:**
Win 10 Home

I installed the server was able to log into the server, but did not set the correct location for my files to be saved. followed a guide to change the location now I am getting an error 500, tried following a bunch of how to fix 500 error, and nothing helps.

I have uninstalled everything and reinstalled multiple times. I have no data saved into oncloud, and would love to just start fresh, but my config files still seem to be saved even when purging data, and I must be missing a few when i try to remove them manually.

**Comment by kdslkdsaldsal** [comment]
@kleeman7 Please note this is a bugtracker of ownCloud. Support questions like this needs to go to https://central.owncloud.org/

Nevertheless a few short hints:

1. Reasons for a 500 error should be logged to your data/owncloud.log (as pointed out in the filled out issue template)
2. You might have missed a step in https://doc.owncloud.org/server/latest/admin_manual/maintenance/manually-moving-data-folders.html
3. To start from scratch you need to at least delete your config/config.php

I'm closing this now, if you need further help please jump over to central (you can login with your github credentials there).
