### ISSUE TITLE
10.0.2 should have $OC_VersionCanBeUpgradedFrom = [[9,0,9],[9,1],[10,0]];

### ISSUE THREAD

**Issue by chriseqipe** [owncloud/core#28712]
On my logic current OC Version 10.0.2 should have 
$OC_VersionCanBeUpgradedFrom = [[9,0,9],[9,1],[10,0]];
in version.php.

**Comment by kdslkdsaldsal** [comment]
Hi,

just to clarify:

An "upgrade" is e.g. going from 9.0.9 to 10.0.2 -> That path must be allowed in the "$OC_VersionCanBeUpgradedFrom" to avoid that some one is trying to e.g. upgrade from 8.1.0 directly to 10.0.2

An "update" is something like e.g. going from 10.0.0 to 10.0.2 -> No need to add this to the $OC_VersionCanBeUpgradedFrom as this is no "Upgrade".
