### ISSUE TITLE
Error message not clear when trying to enable an enterprise app without key

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#28726]
### Steps to reproduce
1. Put an enterprise app (e.g. firewall) into an install (without adding an enterprise key yet)
2. Go to Settings, Apps, show disabled apps
3. Click to enable the app

### Expected behaviour
Some nice message telling you that the enterprise key is missing/invalid...

### Actual behaviour
Error: this app cannot be enabled because it makes the server unstable

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
PHP dev server
**Database:**
mySQL
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
10.0.3

owncloud.log has a clue:
```
{"reqId":"2DY8F7CbG0PoPIcBRfQQ","level":3,"time":"2017-08-17T10:20:08+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"index","method":"GET","url":"\/index.php\/apps\/files","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"enterprise_key can't be enabled since it is not installed.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/phil\\\/core\\\/apps\\\/firewall\\\/appinfo\\\/application.php(155): OC\\\\App\\\\AppManager->enableApp('enterprise_key')\\n#1 \\\/home\\\/phil\\\/core\\\/apps\\\/firewall\\\/appinfo\\\/app.php(20): OCA\\\\Firewall\\\\AppInfo\\\\Application->init()\\n#2 \\\/home\\\/phil\\\/core\\\/lib\\\/private\\\/legacy\\\/app.php(213): require_once('\\\/home\\\/phil\\\/core...')\\n#3 \\\/home\\\/phil\\\/core\\\/lib\\\/private\\\/legacy\\\/app.php(164): OC_App::requireAppFile(Object(OCA\\\\Firewall\\\\AppInfo\\\\Application))\\n#4 \\\/home\\\/phil\\\/core\\\/lib\\\/private\\\/legacy\\\/app.php(121): OC_App::loadApp('firewall')\\n#5 \\\/home\\\/phil\\\/core\\\/lib\\\/base.php(912): OC_App::loadApps()\\n#6 \\\/home\\\/phil\\\/core\\\/index.php(56): OC::handleRequest()\\n#7 {main}\",\"File\":\"\\\/home\\\/phil\\\/core\\\/lib\\\/private\\\/App\\\/AppManager.php\",\"Line\":212}"}
```

Maybe it is difficult for marketplace users to get to this point, because they need an enterprise key to download enterprise apps or?

**Comment by PVince81** [comment]
we need to rework the way how enterprise apps check license key: closing in favor of https://github.com/owncloud/enterprise_key/issues/70
