### ISSUE TITLE
config.sample.php: Better explain "'updatechecker' => false," don't work for marketplace app updates

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#28727]
In the [current core/config.sample.php](https://github.com/owncloud/core/blob/master/config/config.sample.php#L529-L533) it's not clear, that the settings only work for the server core.

```
/**
 * Check if ownCloud is up-to-date and shows a notification if a new version is
 * available.
 */
'updatechecker' => true,
```

@pmaier1 Description could be more precise.

**Comment by pmaier1** [comment]
@PVince81 
Just add a quick hint, please, that this option does not apply on app updates but only core/server.
Thanks!

**Comment by PVince81** [comment]
@pmaier1 looking forward to your PR :smile:

**Comment by PVince81** [comment]
@pmaier1 any update on the PR ?

**Comment by PVince81** [comment]
@sharidas can you take care of this little update ?

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/28867
