### ISSUE TITLE
user menu very picky about click position when using avatar

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#28725]
### Steps to reproduce
1. upload an avatar
2. try to open the user menu by clicking between your avatar and the small triangle

### Expected behaviour
the user menu opens, similar to when you are not using an avatar

### Actual behaviour
the menu only opens when you click exactly on the avatar or exactly on the small triangle

clickable area (green) avatar vs. username
![image](https://user-images.githubusercontent.com/2425577/29406527-0f57d67c-8361-11e7-8b73-720fbb85e21c.png)
![image](https://user-images.githubusercontent.com/2425577/29406629-4c6b51e2-8361-11e7-844d-2e8d05f91174.png)

### Server configuration
**Operating system**:
debian
**Web server:**
apache
**Database:**
sqlite
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
10.0.3 beta (git) 
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc9xsmdtnlru",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-core",
        "dbtype": "sqlite3",
        "version": "10.0.3.0",
        "logtimezone": "UTC",
        "installed": true,
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "default_language": "en",
        "csrf.disabled": "true",
        "skeletondirectory": "\/home\/artur\/www\/owncloud-core\/tests\/ui\/skeleton",
        "files_external_allow_create_new_local": "true",
        "theme": "",
        "loglevel": 4,
        "maintenance": false,
        "firewall.debug": 1,
        "log_type": "owncloud",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "debug": true
    }
}
```

**List of activated apps:**

```
  - comments: 0.3.0
  - dav: 0.3.0
  - diagnostics: 0.1.0
  - enterprise_key: 0.1.3
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firewall: 2.4.1
  - gallery: 16.0.2
  - market: 0.2.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - customgroups
  - multidirtest
  - password_policy
  - testing
  - theme-example
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
FF 55.0.1
**Operating system:**
Debian

**Comment by PVince81** [comment]
duplicate of https://github.com/owncloud/core/issues/28690
