### ISSUE TITLE
support new linux distributions with server packaging

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#28739]
In the current beta test builds
https://download.owncloud.org/download/repositories/testing/owncloud/
the following distrubutions are missing

Fedora_26, openSUSE_Leap_42.3, Debian_9, Ubuntu_17.04

@PVince81 Please also review elsewhere to keep the list in sync. 
@pmaier1 check in sync with our support policy.

**Comment by crrodriguez** [comment]
Debian 7 "wheezy" has been disabled.. only has php 5.4

Added Fedora_26, openSUSE_Leap_42.3, Debian_9, Ubuntu_17.04, once built, it will be published.
