### ISSUE TITLE
ldap:show-remnants missing on 10.0.2

### ISSUE THREAD

**Issue by bluikko** [owncloud/core#28743]
### Steps to reproduce
1. Run: php occ ldap:show-remnants

### Expected behaviour
User cleanup should run.

### Actual behaviour
Error happens, ldap:show-remnants is not a valid command:
```
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "ldap:show-remnants" is not defined.
  Did you mean one of these?
      ldap:search
      ldap:check-user
      ldap:update-group
      ldap:delete-config
      ldap:create-empty-config
      ldap:set-config
      ldap:test-config
      ldap:show-config
```

I see there is now some option called --missing-account-action for user:sync, is this some "improvement" that has taken over ldap:show-remnants? I do not want to delete/disable the users, I want to list them so that they can be dealt with (decide what to do with data etc.). And I definitely would not want to "sync" all users that might do whatever in order to disable/delete the old users.

As a separate cosmetic issue,, the "Admin documentation" for LDAP app in web interface gives a 404:
https://doc.owncloud.org/server/10.0/admin_manual/configuration_user/user_auth_ldap.html

### Server configuration
EL 7.3

**Web server:** Apache 2.4

**Database:** MySQL 5.6

**PHP version:** PHP 5.6.30

**ownCloud version:** 10.0.2

**Updated from an older ownCloud or fresh install:** Updated several times since 6.x or 7.x

**Where did you install ownCloud from:** Source

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
"No errors have been found."

**Comment by kdslkdsaldsal** [comment]
Hi,

looks like this command was removed in https://github.com/owncloud/user_ldap/pull/85 / ownCloud 10 so this is the expected.

Could you state where you got the info to run ``occ ldap:show-remnants`` and where you see the note about the "admin documentation"?

**Comment by bluikko** [comment]
I used occ ldap:show-remnants in previous version to manage users that were deleted from LDAP. It was used in a simple process to decide what to do with data and shares of deleted users. Since the users are deleted by different team from OwnCloud data administrators, it was a convenient way.

I did read the release notes and I do not remember anything about this function being removed.

404 in: Owncloud admin interface -> Apps -> expand information for the LDAP add, click "Admin documentation" link.

**Comment by kdslkdsaldsal** [comment]
If you're missing any information about the removal and alternatives to that removed function please open a new issue at https://github.com/owncloud/documentation/issues where issues with the documentation are handled.

The 404 seems to be an issue in the documentation as well. I'm closing this here and have created a new issue about that in https://github.com/owncloud/documentation/issues/3319

Thanks for your report.

**Comment by kdslkdsaldsal** [comment]
Refs to the PR where the documentation was removed: https://github.com/owncloud/core/issues/28743 as well as a new issue https://github.com/owncloud/documentation/issues/3322 and PR https://github.com/owncloud/documentation/pull/3323

@bluikko Is the https://github.com/owncloud/documentation/pull/3323 providing the needed info for you?

**Comment by bluikko** [comment]
Yes, the documentation is now clear. And the new `user:sync` is much better than what was there before.
