### ISSUE TITLE
webui of ownCloud core is useless when enterprise trial expires. 

### ISSUE THREAD

**Issue by Kawohl** [owncloud/core#28753]
When the time of your enterprise trial expires the webui remains useless. 
Imho this will create a lot of unwanted trouble. 
https://github.com/owncloud/marketplace-issues/issues/12

![screen shot 2017-08-21 at 11 36 33](https://user-images.githubusercontent.com/12275313/29515411-979d9540-866c-11e7-843b-3867039cbc48.png)

**Comment by PVince81** [comment]
define "uselessness" ?

**Comment by PVince81** [comment]
please use the issue template and at least fill out "expected result" as this report is not clear about its expectations

**Comment by Kawohl** [comment]
Excuse me..

### Steps to reproduce
1. Install enterprise trial from market. 
2. Wait for thirty days. 


### Expected behaviour
You should still be able to login into your ownCloud with ce functionality. 

### Actual behaviour
You get a borked mailto: link to contact sales.

**Comment by DeepDiver1975** [comment]
this does not belong in here -> close

**Comment by Kawohl** [comment]
Tell me where it belogs it will make instances useless.

**Comment by PVince81** [comment]
@Kawohl enterprise-key repo please
