### ISSUE TITLE
file/foldernames with multiple spaces cannot be used in UI tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#28754]
### Steps to reproduce
1. try to create a UI tests that searches for a file/foldername that contains multiple space char. e.g. (`file     name`)

### Expected behaviour
findFileRowByName() find the file

### Actual behaviour
file is not found even its correctly shown in the UI
seems like `getText()` returns only one space and not multiple

**Comment by phil-davis** [comment]
Backport stable10 #28782

**Comment by phil-davis** [comment]
Note: solution also allows testing a filename with a mix of single and double quotes.
