### ISSUE TITLE
OCP\Settings\Section should allow non-hardcoded / core icons

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#28751]
Currently `OC\Settings\Section` takes in a string which is used to find hardcoded / core icons. We should extend this to allow apps to supply their own icons here - and core provides the necessary styling.

**Comment by pmaier1** [comment]
Thanks for opening the issue. Would this also be something for you to assign? Moving to 'planned' for 10.0.4.

**Comment by tomneedham** [comment]
@PVince81 can assign as necessary - I need to focus with support :)

**Comment by PVince81** [comment]
@sharidas can you have a look ?

**Comment by sharidas** [comment]
sure
