### ISSUE TITLE
PHP Fatal error: Class 'OCA\DAV\Connector\Sabre\ExceptionLoggerPlugin' not found in /data/www/owncloud/remote.php on line 54

### ISSUE THREAD

**Issue by hdijkema** [owncloud/core#28777]
I've got this issue when I enable 'memcache.local'. Version 9.1.6.2.
It's a manual installation of owncloud, upgraded from 7 to 9.1 (in several steps). DB Backend: Pgsql 9.4.
I tried maintenance:repair.
Don't know what to do now.

PHP Fatal error: Class 'OCA\DAV\Connector\Sabre\ExceptionLoggerPlugin' not found in /data/www/owncloud/remote.php on line 54

### Steps to reproduce
1. Add #'memcache.local' => '\OC\Memcache\APCu',  to config.php
2. go to the owncloud web page
3. 

### Expected behaviour
I'd expect memcache working

### Actual behaviour
I get the fatal php error about the Sabre ExceptionLoggerPlugin.

### Server configuration
**Operating system**: 
raspbian, debian version 9.1

**Web server:**
apache 2.4

**Database:**
PostgreSQL v9.4

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
9.1.6.2

**Updated from an older ownCloud or fresh install:**
7.0 -> 8.0 -> 8.1 -> 8.2 -> 9.0 -> 9.1 (upgrading to 10.0 failed)

**Where did you install ownCloud from:**
manual -> from the owncloud website

**Signing status (ownCloud 9.0 and above):**
eehh???

```
https://gist.github.com/hdijkema/b4f591fbe647a343297be016ccc530c9
```

**The content of config/config.php:**

```
https://gist.github.com/hdijkema/a5f1f6c3feafec5ad0c0662031e78410
```

**List of activated apps:**

```
https://gist.github.com/hdijkema/4265d3e0fab08ae03f073ac4f4aa296d
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

#### LDAP configuration (delete this part if not used)

```
```

### Client configuration
**Browser:**
Google Chrome

**Operating system:**
Windows

#### Web server error log
```
https://gist.github.com/hdijkema/c1790fc9e52160819879c12f3b2a9314
```

#### ownCloud log (data/owncloud.log)
```
https://gist.github.com/hdijkema/198a2a5dc8a92d9ce51efba16d51c157
```

#### Browser log
Not the problem. It's server side
```
```

**Comment by kdslkdsaldsal** [comment]
Probably the same as also suggested by @PVince81 in https://github.com/owncloud/core/issues/26217#issuecomment-249843496

> Maybe APC caching issue ? Does restarting the web server solve it ?

Restarting the webserver is documented in the upgrading manual https://doc.owncloud.org/server/latest/admin_manual/maintenance/manual_upgrade.html as is most likely solving such issues where there are stuff Cached which doesn't exist anymore.

**Comment by hdijkema** [comment]
No, that doen's resolve the issue. I restarted apache serveral times, using the command:

`service apache2 restart`

**Comment by hdijkema** [comment]
This is what my directory contents look like.

```
www-data@raspberrypi:~/owncloud$ ls
3rdparty  config        core              index.html  lib  ocs-provider  resources   status.php  version.php
apps      console.php   cron.php          index.php   occ  public.php    robots.txt  themes
AUTHORS   COPYING-AGPL  db_structure.xml  l10n        ocs  remote.php    settings    updater

www-data@raspberrypi:~/owncloud$ ls apps
activity      encryption            files            files_sharing     files_videoplayer  provisioning_api    user_external
comments      external              files_antivirus  files_texteditor  firstrunwizard     systemtags          user_ldap
configreport  federatedfilesharing  files_external   files_trashbin    gallery            templateeditor
dav           federation            files_pdfviewer  files_versions    notifications      updatenotification

www-data@raspberrypi:~/owncloud$ ls 3rdparty/
autoload.php  composer.json  doctrine    icewind     jeremeamia     LICENSE INFO  natxet     patches.txt  phpseclib  rackspace  sabre
bantu         composer.lock  guzzle      interfasys  kriswallsmith  lukasreschke  nikic      patchwork    pimple     react      swiftmailer
composer      deepdiver1975  guzzlehttp  ircmaxell   league         mcnetic       paragonie  pear         punic      README.md  symfony

www-data@raspberrypi:~/owncloud$ vi config/config.php
www-data@raspberrypi:~/owncloud$
```

**Comment by hdijkema** [comment]
Autoload.php's are here:

```
root@raspberrypi:<wwwdir>/owncloud# find . -name "autoload.php"
./updater/vendor/autoload.php
./3rdparty/autoload.php
./apps/gallery/vendor/autoload.php
./apps/files_external/3rdparty/autoload.php
./apps/files_external/3rdparty/Dropbox/autoload.php
./apps/files_external/3rdparty/google-api-php-client/src/Google/autoload.php
./lib/composer/autoload.php
root@raspberrypi:/data/www/owncloud#
```

**Comment by hdijkema** [comment]
I fixed the problem. 
My apache2 server ran on php5 and my php cli was on php7. 
I purged the complete apache2 / php5 /php7-cli installation, and reinstalled apache2 with php7.
This helped.
