### ISSUE TITLE
Remaining JS unit test warnings

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#28773]
- [ ] tipsy: grep for "tipsy" and replace these instances with `.tooltip()` and retest (the arguments are NOT the same!)
- [ ] OC.Notification.hide: grep for "notifier.hide(" in the settings folder

**Comment by PVince81** [comment]
the warnings in question:
```
WARN: 'Deprecation warning: tipsy is deprecated. Use tooltip instead.'
```
and
```
WARN: 'Missing argument $row in OC.Notification.hide() call, caller needs to be adjusted to only dismiss its own notification'
```

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
ah well, some day maybe when I'm bugged about these warnings again...
