### ISSUE TITLE
Trashbin icon for removing groups missing in safari.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#28771]
### Steps to reproduce

1. Go to the user management.
2. Create some groups
3. Try to remove them.

### Expected behaviour
There is a trashbin icon in the left sidebar.

Firefox screenshot:

![screen shot 2017-08-22 at 13 42 26](https://user-images.githubusercontent.com/9048796/29563877-cbf2aa6e-873f-11e7-80d2-21ad2eb2e208.png)

### Actual behaviour
Using safari the trashbin icon doesn't appear.

Safari screenshot:

![screen shot 2017-08-22 at 13 39 03](https://user-images.githubusercontent.com/9048796/29563864-b7361264-873f-11e7-99f3-9c4093458128.png)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
10.0.3beta1
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.3.0","versionstring":"10.0.3 beta","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```
```

### Client configuration

**Browser**
Safari. Version 9.0 (11601.1.56)

cc @felixheidecke

**Comment by davitol** [comment]
In Safari Version 10.0.3 (12602.4.8) WFM

**Comment by felixheidecke** [comment]
Can not confirm using **Safari Version 10.1.2 (12603.3.8)**
![bildschirmfoto 2017-09-04 um 16 47 21](https://user-images.githubusercontent.com/12717530/30031206-cd9c3fc8-9190-11e7-9a8c-e4594c898864.png)

**Comment by felixboehm** [comment]
Anyway: I kind of dislike that hidden elements, not very intuitive UI.

A Safari should have at least version as stated here: https://github.com/owncloud/core/issues/28016

Won't fix for Safari 9.0. But maybe a good learning about our UI.
