### ISSUE TITLE
ThemeService can't handle Themes in separate app directories

### ISSUE THREAD

**Issue by phisch** [owncloud/core#28778]
### Steps to reproduce
1. install a fresh oc instance
2. configure an external app directory
3. put a theme in this external app directory

### Expected behaviour
Theme can be enabled on the admin->apps page and works as expected

### Actual behaviour
Theme doesn't work

Related: https://github.com/owncloud/theme-enterprise/issues/5

**Comment by DeepDiver1975** [comment]
> configure an external app directory

important here is to note that the folder has to be outside the oc root

e.g.

			array (
				'path' => /tmp/apps2',
				'url' => '/apps2',
				'writable' => true,
			),

and /tmp/apps2 is sym linked into oc root as apps2

**Comment by PVince81** [comment]
@pmaier1 any progress ? Please document your research even if you haven't reached a conclusion yet.

**Comment by michaelstingl** [comment]
@PVince81 @pmaier1 According to @tboerger , https://github.com/owncloud-docker/base/pull/7 should be enough for 10.0.3 (Docker and Appliance). Lower priority for this?

**Comment by PVince81** [comment]
the original ticket is https://github.com/owncloud/theme-enterprise/issues/5 so let's lower the priority there

**Comment by tboerger** [comment]
The original ticket had been closed, was just reopened via https://github.com/owncloud/theme-enterprise/issues/5#issuecomment-325310308

**Comment by PVince81** [comment]
@phisch any update ? what's the status ?

**Comment by phisch** [comment]
There is no quick fix in the code for this. I would like to write a component that handles asset paths (images, styles, templates, translations). This would be more easy to test and understand.

Besides that, i figured out a weird behavior to get themes in external directorys to work out of the box:

I have a structure like this:
 - /usr/local/apache2/htdocs/core <- contains owncloud
 - /usr/local/apache2/htdocs/core/apps <- contains its main apps
 - /usr/local/apache2/htdocs/foo <- contains other apps/themes

With a configuration like this:

```
'apps_paths' =>
        array (
            array (
                'path' => '/usr/local/apache2/htdocs/core/apps',
                'url' => '/apps',
                'writable' => true,
            ),
            array (
                'path' => '/usr/local/apache2/htdocs/foo',
                'url' => '/foo',
                'writable' => true,
            )
        ),
```
While configuring `/foo` to point to `/usr/local/apache2/htdocs/foo`.

You would expect this to work, but it doesn't (as we know, because this is what this ticket is for.

But changing the `path` of the external apps directory from `/usr/local/apache2/htdocs/foo` to `/usr/local/apache2/htdocs/core/../foo` somehow makes it work.

As long as @tboerger's solution inside the docker image works, i would rather not hotfix this, because there are so many different scenarios for this paths, that hotfixing it right now feels like running in circles, you fix one part, and another one breaks. That's why i want a separate component that handles this.

**Comment by VicDeo** [comment]
If I got it correct I need to setup the second app directory above OC webroot but still under the server webroot.
IMHO weird configurations when the second app dir is not below the server  webroot should not be supported. (or we need to write own webserver aka ownServer for that :tongue: )

**Comment by VicDeo** [comment]
@PVince81 To make it work I need turn `ITheme::getDirectory` `ITheme::setDirectory` from relative into absolute. 
It will touch ResourceLocators/L10N/URLGenerator 

Such a fun :-/

**Comment by PVince81** [comment]
Pfff... I wonder if we could just have the theme mounted in ownCloud's VFS then it wouldn't matter where it's physically located... Probably not a good idea though...

@VicDeo how about adding another variable `setBaseDirectory" and `getBaseDirectory` that both default to null, meaning relative ? And when set, prepend this to the value of `getDirectory` ? Assuming this logic can be added somewhere in between
