### ISSUE TITLE
public shares become invalid after ~90 days ?

### ISSUE THREAD

**Issue by IngoEF** [owncloud/core#28789]
### Steps to reproduce
1. create a public share with unchecked expiration
2. wait ~90 days
3. link isn't valid anymore 

### Expected behaviour
link should stay valid forever without expiration date set

### Actual behaviour
link becomes invalid after ~90 days

### Server configuration
**Operating system**: 
CentOS Linux release 7.2.1511 (Core)

**Web server:**
Apache/2.4.6 

**Database:**
mysql  Ver 15.1 Distrib 5.5.52-MariaDB

**PHP version:**
PHP 5.4.16 

**ownCloud version:** (see ownCloud admin page)
9.1.4.2

**Updated from an older ownCloud or fresh install:**
from older Version

**Where did you install ownCloud from:**
 ce:9.1.repo

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc14ec93473b",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
        ],
        "datadirectory": "\/data\/owncloud\/data",
        "dbtype": "mysql",
        "version": "9.1.4.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "updatechecker": false,
        "has_internet_connection": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "nn.mm.ooo.ppp",
        "mail_smtpauth": true,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "support",
        "mail_domain": "xxxxxxx.yy",
        "mail_smtpport": "25",
        "mail_smtpsecure": "tls",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": "3",
        "trashbin_retention_obligation": "auto"
    }
}
**List of activated apps:**

Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: true
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:** 
any

**Operating system:**
any

### Logs
not needed

**Comment by hodyroff** [comment]
Sorry, this sounds weird. Are you sure that you can reproduce this with 9.1.6 or 10.0.2? It sounds rather like something happened which maybe did lead to a loss of a specific or all public shares?

**Comment by IngoEF** [comment]
I didn't see public shares disappear, our customer complains about seeing his share but people who where informed about them (including a password) cannot reach them anymore after this ~90 days. Owncloud then refuses access and informes about an unvalid password.
Is there a default password validity in OC?

**Comment by hodyroff** [comment]
No. What does exist is a "set default expiration date" https://doc.owncloud.org/server/latest/admin_manual/configuration/files/file_sharing_configuration.html
And the end user might have set himself an expiration date which you as an admin would not be able to see - not sure if this ends up in any log file other then the database. The error message would IMO be the same as for a non-existent link. If this is what it comes down to, we would need to add something for the admin to figure this out and let the end user know.

**Comment by IngoEF** [comment]
I do not ask for changes before seeing this behaviour myself.
Can you confirm no changes from 9.1 to 10.0 concerning this issue?
Do you have an idea, how one might get more internal information about public shares? Maybe there ist something to find in the storage place.

**Comment by hodyroff** [comment]
The database saves all information about public shares including any expiry dates.
Sounds like we can close this for now?

**Comment by IngoEF** [comment]
I would appreciate some more info questioning those expiries

**Comment by hodyroff** [comment]
This should help https://doc.owncloud.org/server/10.0/developer_manual/core/ocs-share-api.html

**Comment by hodyroff** [comment]
Closing till it can be reproduced.
