### ISSUE TITLE
OwnCloud not in Debian 9 repo

### ISSUE THREAD

**Issue by lszyba1** [owncloud/core#28808]
Hello,
Could one of the developers package ownclould to be auto installed in debian 9.
Thank you.
Lucas

See note here:
https://www.phoronix.com/scan.php?page=news_item&px=Debian-Stretch-OwnCloud

### Steps to reproduce
1.apt-get install ownclould

package not found

### Expected behavior
Tell us what should happen:
OwnClould should be packaged in Debian 9, and readme should possibly included instructions for upgrading to enterprise edition.

### Actual behavior
Package no longer found.
Upgrade from Debian 8 to 9 makes the project unusable.

### Server configuration
**Operating system**:
Debian 9
**Web server:**
Apach2
**Database:**
Mysql
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
latest
**Updated from an older ownCloud or fresh install:**
Upgrade from Debian 8
**Where did you install ownCloud from:**
Debian 8
**Signing status (ownCloud 9.0 and above):**

### Client configuration
Android app + Iphone Apps + example.com/owncloud
**Operating system:**

**Comment by DeepDiver1975** [comment]
Recommended Installation is from tar ball. 
If you stIll prefer packages see
https://doc.owncloud.org/server/latest/admin_manual/installation/linux_installation.html
