### ISSUE TITLE
OC\RepairException: Upgrade is not possible

### ISSUE THREAD

**Issue by pascal06** [owncloud/core#28806]
Hello everyone,
I tried to upgrade my Owncloud from version 9.1.6 to 10.0.2 by following "Manual ownCloud Upgrade" step by step.
I uninstalled two third party application (Calendar and Contacts).
After clicking "Start Update", it fails (sorry it's the french version):
![image](https://user-images.githubusercontent.com/6444824/29726918-0b7d3430-89d2-11e7-83c2-4defd681fe33.png)
![image](https://user-images.githubusercontent.com/6444824/29727001-5a868fcc-89d2-11e7-943c-2396d634f604.png)

> 
> 
> OC\RepairException:
> Upgrade is not possible
> Avertissement de réparation :Exception
> Avertissement de réparation :La signature n'a pas pu être vérifiée. Merci de contacter le développeur de l'application et de vérifier votre page d'administration.
> Avertissement de réparation :You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
> Avertissement de réparation :please install app manually with tarball or disable them with: occ app:disable activity
> Journaux détaillés
> Préparation de la mise à jour
> Réglage du niveau de journalisation à "déboguage"
> Mode de maintenance activé
> Avertissement de réparation :Exception
> Avertissement de réparation :La signature n'a pas pu être vérifiée. Merci de contacter le développeur de > l'application et de vérifier votre page d'administration.
> Avertissement de réparation :You have incompatible or missing apps enabled that could not be found > or updated via the marketplace.
> Avertissement de réparation :please install app manually with tarball or disable them with: occ > app:disable activity
> OC\RepairException: Upgrade is not possible
> La mise à jour a échoué. Veuillez signaler ce problème à la communauté ownCloud.

My Owncloud is hosted by a french provider (LWS):

>     Database server
>     Server: Localhost via UNIX socket
>     Server type: MariaDB
>     Server version: 10.1.25-MariaDB-1~jessie - mariadb.org binary distribution
>     Protocol version: 10
>     User: xxxxx@localhost
>     Server charset: UTF-8 Unicode (utf8)
> 
> Web server
> 
>     Apache/2.4.10 (Debian)
>     Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
>     PHP extension: mysqliDocumentation mbstringDocumentation
>     PHP version: 5.6.30-0+deb8u1

Anybody can help me ?

Thanks in advance,

Pascal

**Comment by kdslkdsaldsal** [comment]
@pascal06 Please note this is a bugtracker of ownCloud. Support questions like this belongs to https://central.owncloud.org/.

Nevertheless a few hints:

- The posted messages gives you quite a lot guidance (e.g. disable activity app ) which can help you to run your update
- There is a discussion on how to improve those messages / info you get during an upgrade ongoing in https://github.com/owncloud/core/issues/28734. Feel free to jump into that discussion if you have any additional notes to this
- If the messages won't help you with your issue please post a new thread at https://central.owncloud.org/c/server/help (you can login with your github account there).
