### ISSUE TITLE
Restoration of elements in trashbin to an external storage confuses the breadcrumbs of the files view.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#28800]
### Steps to reproduce

0. Set up an external storage. For example SFTP.
1. In oC files view create three or more folders and upload files inside them.
2. Select three of the created folders and try to delete them.
3. Restore the folders.
4. Go to the files view.

### Expected behaviour
After restoration, going to the files view opens root folder.

### Actual behaviour
After restoration, going to the files view opens external storage folder as if it were the root folder.

![trashbin_doesnt_comeback_properly](https://user-images.githubusercontent.com/9048796/29711400-ddb0ecb4-8994-11e7-9452-1109c06e9c95.gif)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**Cache**
Redis.

**ownCloud version:** (see ownCloud admin page)
(stable10)
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.3.0","versionstring":"10.0.3 beta","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes. SFTP

**Are you using encryption:** 
No.

**Logs**
```
```

### Client configuration

**Browser**
Chrome

**Comment by PVince81** [comment]
@SergioBertolinSG can you retest with https://github.com/owncloud/core/pull/28804 ? It is very likely that this is related

**Comment by SergioBertolinSG** [comment]
Works using https://github.com/owncloud/core/pull/28804
