### ISSUE TITLE
Webdav not working, keep getting the error: script '/var/www/html/remote.php' not found or unable to stat

### ISSUE THREAD

**Issue by bitking** [owncloud/core#28821]
Hi there,

Since i upgraded from Owncloud 9.0.10 to 9.1.6 i cant get webdav to work.

When i check the apache2 error log i see.

script '/var/www/html/remote.php' not found or unable to stat <- this is correct because there is no owncloud installation here.

I dont have any rewrite rules on my apache2 setup so i am baffled as to where this error suddenly comes from.

### Steps to reproduce
1. Upgrade from 9.0.10 to 9.1.6
2. Call for the webdav URL in windows exlorer with map drive -> https://<url>/remote.php/webdav' 
3. Check apache2 error log for -> script '/var/www/html/remote.php' not found or unable to stat

### Expected behaviour
Show the files

### Actual behaviour
Gives error upon connecting to webdav drive

### Server configuration
**Operating system**:
Ubuntu Server16.04.3

**Web server:**

Apache/2.4.18 (Ubuntu)

**Database:**

Ver 14.14 Distrib 5.7.19

**PHP version:**

PHP 7.0.22-0ubuntu0.16.04.1

**ownCloud version:** (see ownCloud admin page)

Owncloud 9.1.6

**Updated from an older ownCloud or fresh install:**

Upgraded from 9.0.10.

**Where did you install ownCloud from:**

Ubuntu Repository

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by kdslkdsaldsal** [comment]
@bitking Please note this is a bugtracker of ownCloud. Support questions like this belongs to https://central.owncloud.org/. Please post a new thread at https://central.owncloud.org/c/server/help (you can login with your github account there).

I'm closing this as the ``script '/var/www/html/remote.php' not found or unable to stat`` is a server webserver misconfiguration where some rewrites or similar are pointing to a wrong location or are not working as expected.
