### ISSUE TITLE
Retry failed web UI uploads

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#28829]
There are several levels on which to retry a Webdav PUT upload:

- non-chunked file upload: just retry the same file
- chunked file upload:
    - retry chunk (PUT)
    - retry chunk assembly (MOVE)

A retry should happen in the case of a timeout error or 423 Locked error and be limited to a small number like 5.

**Comment by PVince81** [comment]
It might not be safe to retry the final MOVE as the server might still be processing the previous request despite the closed connection. We need to find a solution for this: if the MOVE is retried, maybe it should get 423 Locked.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
we addressed this on chunk level, should hopefully be enough to cover most cases: https://github.com/owncloud/core/issues/30770
