### ISSUE TITLE
PHP array warning in response.php

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#28832]
### Steps to reproduce
1. run limituploadbasedonsize.feature firewall test against current master
2. examine data/owncloud.log

### Expected behaviour
No PHP messages

### Actual behaviour
This:
```
{"reqId":"Jwtuaff38pjoU0rHVRR5","level":3,"time":"2017-08-29T11:23:10+00:00","remoteAddr":"::1","user":"admin","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/files\/admin\/","message":"in_array() expects parameter 2 to be array, null given at \/home\/phil\/core\/lib\/private\/legacy\/response.php#294"}
```
### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
PHP dev server
**Database:**
MySQL
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
current master from git

seems to be the new code added in CORS stuff:
https://github.com/owncloud/core/commit/e3564e6c53bceb2dbe23dd1fbfec8b4696f7454d
https://github.com/owncloud/core/pull/28457

**Comment by phil-davis** [comment]
Awaiting backport of #28833 which needs to happen with or after backport of #28457

**Comment by DeepDiver1975** [comment]
fixed with the above PRs

**Comment by phil-davis** [comment]
@SergioBertolinSG I restested this against ``stable10`` (as you asked about) and all is good.
