### ISSUE TITLE
filenames are wrongly positioned in public link list

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#28869]
### Steps to reproduce
1. create a public link with file listing
2. view that public link

### Expected behaviour
![image](https://user-images.githubusercontent.com/2425577/29917631-428d8878-8e62-11e7-843d-086739b0d9f1.png)

### Actual behaviour
![image](https://user-images.githubusercontent.com/2425577/29917521-f2fe795c-8e61-11e7-8315-9cd9a71575ca.png)

### Server configuration
**Operating system**:
Debian
**Web server:**
Apache2
**Database:**
sqlite
**PHP version:**
php 7.1
**ownCloud version:** (see ownCloud admin page)
10.0.3 beta - git master (stable10 branch is fine)

### Client configuration
**Browser:**
FF 55 & Chrome 60
**Operating system:**
Debian

**Comment by SergioBertolinSG** [comment]
I see it correct using 10.0.3beta2 tarball.

I think this PR has fixed also this issue: https://github.com/owncloud/core/pull/28862

**Comment by SergioBertolinSG** [comment]
@individual-it please retest with beta2, I think this can be closed.

**Comment by individual-it** [comment]
10.0.3.beta2 tarball is fine and also stable10 branch, the problem is in the master branch

**Comment by SergioBertolinSG** [comment]
Ah right, reproduced on master.

**Comment by SergioBertolinSG** [comment]
cc @felixheidecke

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by individual-it** [comment]
I cannot reproduce that problem any more on the current master

**Comment by phil-davis** [comment]
Then this can be closed for real.
