### ISSUE TITLE
Restore from trash is broken with external storage when encryption enabled

### ISSUE THREAD

**Issue by sharidas** [owncloud/core#28868]
### Steps to reproduce
1. Enable encryption with masterkey enabled
2. Create external storage (SFTP)
3. Try to upload a file to SFTP folder
4. Delete the file from SFTP folder
5. Restore the file from trash to external storage

### Expected behaviour
The restore should happen successfully

### Actual behaviour
The restore doesn't happen. While debugging it's found that bad signature is hit during the file read operation.

### Server configuration
**Operating system**:
Linux Mint 18.2 Sonya

**Web server:**
Apache

**Database:**
Sqlite

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
master branch

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
git

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
@sharidas please remove "regression" label if you find out that this issue existed in 10.0.2 and 9.1.x

**Comment by sharidas** [comment]
Below are the steps done for testing under different version of oC.

**Version: 9.1.6**
------------------------
### Enable encryption
------------------------------

1. Create external storage with SFTP
2. Upload a file to the SFTP folder
3. The version number of the file ( under encrypted row of oc_filecache ) is 1.
4. Delete the file from SFTP folder
5. The version of the file in the trashbin remains 1
6. Restore happens successfully. 
7. The version still remains 1.

**Comment by sharidas** [comment]
This PR: https://github.com/owncloud/core/pull/28820 resolves the issue. 
While doing testing by editing the files in SFTP storage multiple times before deletion. I got this exception


`{"reqId":"tNpdfYuwSTrDiFkjDV7m","level":3,"time":"2017-08-31T14:23:26+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"no app in context","method":"DELETE","url":"\/enterprise\/remote.php\/dav\/files\/admin\/SFTP\/foo.txt","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you."}
{"reqId":"tNpdfYuwSTrDiFkjDV7m","level":3,"time":"2017-08-31T14:23:33+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"no app in context","method":"DELETE","url":"\/enterprise\/remote.php\/dav\/files\/admin\/SFTP\/foo.txt","message":"Couldn't re-calculate unencrypted size for files_versions\/SFTP\/foo.txt.v1504189306"}
{"reqId":"tNpdfYuwSTrDiFkjDV7m","level":3,"time":"2017-08-31T14:23:33+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"no app in context","method":"DELETE","url":"\/enterprise\/remote.php\/dav\/files\/admin\/SFTP\/foo.txt","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(599): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt(*** sensitive parameters replaced ***)\\n#1 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(518): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fixUnencryptedSize('files_versions\\\/...', 116, 8308)\\n#2 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(166): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->verifyUnencryptedSize('files_versions\\\/...', 8308)\\n#3 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(149): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->filesize('files_versions\\\/...')\\n#4 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(149): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->filesize('files_versions\\\/...')\\n#5 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/View.php(1124): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->filesize('files_versions\\\/...')\\n#6 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/View.php(415): OC\\\\Files\\\\View->basicOperation('filesize', 'files_versions\\\/...')\\n#7 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/files_versions\\\/lib\\\/Storage.php(463): OC\\\\Files\\\\View->filesize('\\\/files_versions...')\\n#8 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(347): OCA\\\\Files_Versions\\\\Storage::getVersions('admin', 'foo.txt')\\n#9 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(307): OCA\\\\Files_Trashbin\\\\Trashbin::retainVersions('foo.txt', 'admin', 'SFTP\\\/foo.txt', 1504189369)\\n#10 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(185): OCA\\\\Files_Trashbin\\\\Trashbin::move2trash('SFTP\\\/foo.txt')\\n#11 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(120): OCA\\\\Files_Trashbin\\\\Storage->doDelete('foo.txt', 'unlink')\\n#12 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/View.php(1124): OCA\\\\Files_Trashbin\\\\Storage->unlink('foo.txt')\\n#13 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/View.php(694): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/SFTP\\\/foo.txt', Array)\\n#14 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(354): OC\\\\Files\\\\View->unlink('\\\/SFTP\\\/foo.txt')\\n#15 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n#16 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('files\\\/admin\\\/SFT...')\\n#17 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#18 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#19 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#20 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#21 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/dav\\\/lib\\\/Server.php(236): Sabre\\\\DAV\\\\Server->exec()\\n#22 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#23 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/remote.php(175): require_once('\\\/home\\\/sujith\\\/te...')\\n#24 {main}\",\"File\":\"\\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php\",\"Line\":367}"}`


So tried to switch back to the working 10.0.2 version of oC. This exception is available in that version too.


`{"reqId":"ARmne1eqY9XCqvJH2MaK","level":3,"time":"2017-08-31T14:41:19+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"no app in context","method":"DELETE","url":"\/enterprise\/remote.php\/webdav\/SFTP\/foo.txt","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you."}
{"reqId":"ARmne1eqY9XCqvJH2MaK","level":3,"time":"2017-08-31T14:41:19+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"no app in context","method":"DELETE","url":"\/enterprise\/remote.php\/webdav\/SFTP\/foo.txt","message":"Couldn't re-calculate unencrypted size for files_versions\/SFTP\/foo.txt.v1504190445"}
{"reqId":"ARmne1eqY9XCqvJH2MaK","level":3,"time":"2017-08-31T14:41:19+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"no app in context","method":"DELETE","url":"\/enterprise\/remote.php\/webdav\/SFTP\/foo.txt","message":"Exception: {\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(573): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt(*** sensitive parameters replaced ***)\\n#1 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(492): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fixUnencryptedSize('files_versions\\\/...', 116, 8308)\\n#2 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(161): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->verifyUnencryptedSize('files_versions\\\/...', 8308)\\n#3 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(149): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->filesize('files_versions\\\/...')\\n#4 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(149): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->filesize('files_versions\\\/...')\\n#5 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/View.php(1123): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->filesize('files_versions\\\/...')\\n#6 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/View.php(414): OC\\\\Files\\\\View->basicOperation('filesize', 'files_versions\\\/...')\\n#7 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/files_versions\\\/lib\\\/Storage.php(463): OC\\\\Files\\\\View->filesize('\\\/files_versions...')\\n#8 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(342): OCA\\\\Files_Versions\\\\Storage::getVersions('admin', 'foo.txt')\\n#9 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(302): OCA\\\\Files_Trashbin\\\\Trashbin::retainVersions('foo.txt', 'admin', 'SFTP\\\/foo.txt', 1504190479)\\n#10 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(185): OCA\\\\Files_Trashbin\\\\Trashbin::move2trash('SFTP\\\/foo.txt')\\n#11 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/files_trashbin\\\/lib\\\/Storage.php(120): OCA\\\\Files_Trashbin\\\\Storage->doDelete('foo.txt', 'unlink')\\n#12 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/View.php(1123): OCA\\\\Files_Trashbin\\\\Storage->unlink('foo.txt')\\n#13 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/private\\\/Files\\\/View.php(693): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/SFTP\\\/foo.txt', Array)\\n#14 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(346): OC\\\\Files\\\\View->unlink('\\\/SFTP\\\/foo.txt')\\n#15 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n#16 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('SFTP\\\/foo.txt')\\n#17 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#18 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#19 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#20 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#21 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#22 \\\/home\\\/sujith\\\/test\\\/enterprise\\\/remote.php(165): require_once('\\\/home\\\/sujith\\\/te...')\\n#23 {main}\",\"File\":\"\\\/home\\\/sujith\\\/test\\\/enterprise\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php\",\"Line\":360}"}
`

**Comment by PVince81** [comment]
@sharidas didn't you have a fix already for this ? I see no linked ticket, please always properly link tickets and PRs. Usually if you add "Fixes #XYZ" in the PR, it will automatically close the matching ticket on merge.

**Comment by sharidas** [comment]
PR: https://github.com/owncloud/core/pull/28880
