### ISSUE TITLE
Typo in link for `files_locking_transactional.html`

### ISSUE THREAD

**Issue by yoniy0** [owncloud/core#28878]
### Steps to reproduce
1. Use db-based file locking.
2. Go into Admin panel > General

A warning appears at the top of the page:

> Transactional file locking should be configured to use memory-based locking, not the default slow database-based locking. See the [documentation ↗](https://doc.owncloud.org/server/10.0/go.php?to=admin-transactional-locking) for more information. 

3. Click on the link.

### Expected behaviour
One expects to be redirected to `https://doc.owncloud.org/server/<instance-version>/admin_manual/configuration/files/files_locking_transactional.html` (or conceivably `latest` instead of `<instance-version>`)

### Actual behaviour
One is redirected to `https://doc.owncloud.org/server/10.0/admin_manual/configuration_files/files_locking_transactional.html`. Note in particular the underscore `_` in `configuration_files`, where a slash `/` is expected.

I suspect the issue is contained to the re-director at `https://doc.owncloud.org/server/10.0/go.php?to=admin-transactional-locking`, but I'll provide *some* of the information suggested by the template:

### Server configuration
**Operating system**: Ubuntu 16.04.3

**Web server:** Apache/2.4.18 (Ubuntu)

**Database:** mysql  Ver 14.14 Distrib 5.7.19

**PHP version:** PHP 7.0.22-0ubuntu0.16.04.1

**ownCloud version:** (see ownCloud admin page) 10.0.2.1

**Updated from an older ownCloud or fresh install:** Updated from 9.1.6

**Where did you install ownCloud from:** PPA on `http://download.owncloud.org/download/repositories/10.0/Ubuntu_16.04/`

**Signing status (ownCloud 9.0 and above):** `No errors have been found.`

### Client configuration
**Browser:** `Firefox 55.0.2 (64-bit)` and `Chrome Version 60.0.3112.113 (Official Build) (64-bit)`

**Operating system:** Ubuntu Desktop 16.04

**Comment by kdslkdsaldsal** [comment]
Hi,

thanks for your report. This is indeed an issue in the go.php which lives in https://github.com/owncloud/documentation. Seems some one reported this there a few days ago in https://github.com/owncloud/documentation/issues/3357 so i'm closing this here for now.

Thanks again.
