### ISSUE TITLE
Session can remove itself and does not really invalidate the session for all endpoints

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/core#28881]
### Steps to reproduce
1. With a valid `$SESSION` (after login) - list all current sessions:
```
$ curl 'https://<server>/index.php/settings/personal/authtokens' \
    -H 'OCS-APIREQUEST: true' \
    -H 'Cookie: $SESSION'

[
   {
      "id":1,
      "name":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.113 Safari\/537.36",
      "lastActivity":"1504262361",
      "type":"0",
      "canDelete":false
   }
]
```
2. Remove itself (shouldn't be allowed - note the `"canDelete":false`)
```
$ curl 'https://<server>/index.php/settings/personal/authtokens/1' -X DELETE 
    -H 'OCS-APIREQUEST: true' \
    -H 'Cookie: $SESSION'
```
3. Query any endpoint to check how the `$SESSION` is still valid
4. Hit the first endpoint again:
```
$ curl -I 'https://<server>/index.php/settings/personal/authtokens' \
    -H 'OCS-APIREQUEST: true' \
    -H 'Cookie: $SESSION'

HTTP/1.1 503 Service Unavailable
[...]
```

### Expected behavior
1. If `"canDelete":false`, removing that session should be forbidden.
2. The `$SESSION` should be invalidated for all endpoints and querying `https://<server>/index.php/settings/personal/authtokens` shouldn't cause a server error

### Actual behavior
Described in repro steps. 

### Server configuration
* **ownCloud version:** 10.0.3 beta2 - after https://github.com/owncloud/core/pull/28879

**Comment by PVince81** [comment]
Is this a regression ?

**Comment by SamuAlfageme** [comment]
@PVince81 not sure. Will check with 9.1.X - Related though: https://github.com/owncloud/core/issues/24911

**Comment by SamuAlfageme** [comment]
The "does not really invalidate the session for all endpoints" it's indeed a regression - working in 9.1.1

**Comment by IljaN** [comment]
Should i change the status to 401 Unauthorized? 503 is clearly wrong here

**Comment by SamuAlfageme** [comment]
@IljaN I'd expect the request in 2. to be replied with an 403: Forbidden (after https://github.com/owncloud/core/pull/25276) since the user cannot remove his own session in this manner. And yup, any requests after removing a session **from a different one** should be replied with 401: Unauthorized. (i.e. invalidate the session)

**Comment by SamuAlfageme** [comment]
Fixed with @IljaN's https://github.com/owncloud/core/pull/28879/commits/2ceecd27f63ffa618838c2274ff77a8ffca2bf6d 

On a side-note, I've also noticed `<sessionID>`s in `https://<server>/index.php/settings/personal/authtokens/<sessionID>` receive no existence check - i.e. when deleting a non-existent session id, server replies with a 200.

**Comment by IljaN** [comment]
Yeah the there are a lot of edgecases handling missing, but this was also the case before the regression, I suggest that we improve this in a seperate task after realease (unless it is critical)
