### ISSUE TITLE
How can i convert my owncloud local file system to S3 file system

### ISSUE THREAD

**Issue by R-yogesh** [owncloud/core#28909]
--> 
### Steps to reproduce
1.backed up owncloud which is in local and and restored it in aws
2.Now configured owncloud to S3
3.But when configuring S3 as a external storage it only creates a fresh folder to sync with S3, but not syncing the backed up data files to S3

### Expected behaviour
all data and files should sync with S3

### Actual behaviour
Its not syncing with S3

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** Apache

**Database:** Mysql

**PHP version:**7.0

**ownCloud version:** (see ownCloud admin page)
9.1.6
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
followed digital ocean setup 
**Signing status (ownCloud 9.0 and above):**

```

**Comment by kdslkdsaldsal** [comment]
Please note that this is a bugtracker of ownCloud. Questions like this needs to go to http://central.owncloud.org/. Thanks
