### ISSUE TITLE
Use separate Sabre servers/trees for each first level DAV path

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#28913]
This is a proposal we had a while ago which I'd like to revive.

Some issues with the current approach:

- we're registering all possible plugins every time: for example, the Caldav plugins are registered even when we access the "files" endpoint. This can cause unneeded performance issues, see https://github.com/owncloud/core/pull/28853 (DAVACL plugin that needed to be excluded)
- it is not possible to use an optimized `getNodeForPath` like in the path because this method only exists in the root tree: https://github.com/owncloud/core/pull/28853#issuecomment-327161225. If we wanted to have it on subtrees and also specialized, we'd need to have special nodes that extend `Tree` and also implement `ICollection`, and also have a root `Tree` which logic properly detects if a node is a Tree and then call `getNodeForPath`.

If we had separate Sabre servers for each first level DAV path "/files", "/comments", "/calendars", etc:
- each server would only register the plugins relevant to this endpoint
- there could be a list of base plugins to be always registered, like the maintenance mode plugin
- each server has its own optimized Tree which uses a different approach based on the implementation (files would do like the old ObjectTree::getNodeForPath() which uses the view as shortcut instead of iterating over every node)

@DeepDiver1975 @butonic @jvillafanez thoughts ?

**Comment by jvillafanez** [comment]
I think that, in general, we should adapt ourselves to what Sabre expects us to do. I'm leaving some questions:
* I think Sabre has its base Dav, CALDav, and other implementations. Is it expected that each of these service are run in their own server? Maybe we're pushing too much joining everything into the same server.
* What are the extension points proposed by Sabre? I've seen several backend implementations, so I guess those are expected, but I've also seen custom implementations for nodes and object trees, which might not be expected (I'm not sure)

    If custom node implementations aren't expected, we should limit these customizations as much as possible.

* Are plugins expected to be active for the whole server? If so, as it seems, that's another reason to split into different servers. Adding hackery to enable / disable / register / unregister plugins doesn't seem a good choice.

My point is that if we're going to use Sabre we'll have to adjust ourselves to what Sabre offers. If we have to hack our way through Sabre to get what we need, then we should make our own implementation of the whole service.
I'm fine if we need to add some optimizations, but these changes should be clearly justified, with minimum changes and very limited. If we need to hack the code too much, maybe the library isn't fit for us in the first place.

**Comment by guruz** [comment]
@PVince81 This sounds like a great idea!
Brainfart:
To improve performance one could go further even and register certain plugins only when a certain verb is requested (e.g. don't even register virus scan hook on GET but on PUT). But maybe this only improves performance if the hooks are specified before the actual app loading (via xml and then cached in DB?) is done (e.g. avoid loading the app at all)

**Comment by DeepDiver1975** [comment]
One issue I see with separate trees/servers: cross copy and move operations will no longer work.

example:
COPY dav/calendars/user1/cal/event.ics dav/files/user1/event.ics
