### ISSUE TITLE
Clean up DAV layer's filesystem parts

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#28912]
- [ ] use node API: https://github.com/owncloud/core/pull/26548 (to be redone)
- [ ] get rid of `cacheNode()` and see if there is a better way, ref https://github.com/owncloud/core/pull/28853#issuecomment-326917620
    - [ ] if we do keep `cacheNode()`, also cache `false` when needed, ex: `Directory::getChild()`

@jvillafanez add stuff here if you had more in mind

cc @DeepDiver1975

**Comment by PVince81** [comment]
- [ ] get rid of ObjectTree ?
- [ ] get rid of old DAV endpoint / remap/redirect it to the new one: https://github.com/owncloud/core/issues/26063 (requires killing old chunking)

**Comment by jvillafanez** [comment]
* [ ] https://github.com/owncloud/core/blob/master/apps/dav/lib/Connector/Sabre/Server.php it seems we can remove that class. The properties should be able to be set in the original implementation.
* [ ] https://github.com/owncloud/core/blob/master/apps/dav/lib/Connector/Sabre/Node.php check possibilities to remove the injection of the ShareManager, which is out of place.
* [ ] tidy https://github.com/owncloud/core/tree/master/apps/dav/lib/Connector/Sabre : move custom plugins to other folder and namespace, the same for backends and other custom things.

**Comment by PVince81** [comment]
- [ ] remove injection of `MountManager` in the old `ObjectTree` as it seems to be completely unused

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
