### ISSUE TITLE
File row sometimes not visible in UI tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#28916]
### Steps to reproduce
1. Run the automated UI tests (specially those that rename/share/delete files)
2. Make the browser window height smaller, or just be unlucky

### Expected behaviour
The tests should paqss

### Actual behaviour
When finding a file in the list of files on the files page, the code checks for the file. If it is not there then it scrolls down to the bottom, which will cause the web UI to request and load more files in the list. This process might load more files than fit in a single scroll window. In that case the desired file might be found in the list, but is not actually visible in the window.

Subsequent code does stuff like try to click on the file row element. That fails if the element does not happen to be visible in the window.

### Server configuration
core master or stable10 running tests in a dev environment, or in Travis+SauceLabs

**Comment by phil-davis** [comment]
@individual-it I think this is fixed with some better scrolling of the files list that you did?

**Comment by individual-it** [comment]
should be fixed by https://github.com/owncloud/core/pull/29124
