### ISSUE TITLE
Integration tests: CommandLine::findLines returns false positives

### ISSUE THREAD

**Issue by cortho** [owncloud/core#28919]
I'm currently writing integration tests where I received false positives for _the command output contains the text_.
The reason is the comparison operator https://github.com/owncloud/core/blob/d4261ca0ca4075c3428dfbe52fcccbe00b98987a/tests/integration/features/bootstrap/CommandLine.php#L99 which most likely should read
`if (strpos($line, $text) !== false) {`
Since I'm quite occupied atm and it is likely, that some tests fail after changing this, I din't create a PR right now.

Edit: typo

**Comment by phil-davis** [comment]
That sounds reasonable. I have set off a run of CI in #28922 so we will see how that goes.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by phil-davis** [comment]
This was fixed by PR #28922
