### ISSUE TITLE
External Storage Three Major Problems

### ISSUE THREAD

**Issue by przemo1109** [owncloud/core#28923]
Hello, I have installed owncloud version 10.2 on Synology DSM 6.1.3, I am happy with this software but I have three problems that are very troublesome for me:

1) When using SMB as External Storage there is always an error: Storage not available, why?

![1](https://user-images.githubusercontent.com/31694164/30109859-3ae58ecc-9308-11e7-85a1-944d8625a84b.png)

2) When using LOCAL as External Storage I can not choose Authentication, when I choose NONE by default, http user is used, is it possible to add a username and password authentication like in SMB?

![2](https://user-images.githubusercontent.com/31694164/30109869-434eea2c-9308-11e7-9160-4bf439b88d02.png)

3) If a user want to download a folder (large size) then it pops up a 504 error. I fixed this problem with the proper configuration of the appache server but still I'm not happy with it because zipping large size folder takes a long time, I read that ZipStreamer can help but after 2 days trying to use it I failed to start it. Could someone write a simple guide, how to step by step activate zipstreamer in owncloud?

**Comment by kdslkdsaldsal** [comment]
Hi,

please note that this is a bugtracker of ownCloud. Questions like this needs to go to https://central.owncloud.org/ . Thanks.
