### ISSUE TITLE
information button in Federated Cloud Sharing section is not right located.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#28936]
Using oC 10.0.3 RC1 version and Firefox and Chrome as browsers

![screen shot 2017-09-07 at 10 30 00](https://user-images.githubusercontent.com/10596560/30154202-70afa5f4-93b9-11e7-9f89-3ffcb0edf633.png)

**Comment by phil-davis** [comment]
Also backport to stable10 in #28972 
This should be fixed for 10.0.4

**Comment by SergioBertolinSG** [comment]
Fixed in 10.0.4RC1
