### ISSUE TITLE
[Feature Request] Centralise thumbnail store and make the location configurable

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#28939]
Thumbnails are currently created and stored for each user
This has some negative impacts like:
- very high space consumption due to duplicates 
- deleting a mount creates orphan thumbs and database entries

Example 20k pictures can create up to 3GB of thumbs.
Sharing the picture store with 100 people creates 300GB of space consumption
If you remove the picture mount, you have 300GB filespace as file and database orphans 
 
This FR is about to centralize the thumbnail store and make the location configurable

Existing issues/Feature Requests I found related were:

https://github.com/owncloud/core/issues/25770 [Feature Request] adding column "ref_storage" in table oc_filecache
https://github.com/owncloud/core/issues/25213 make thumbnail, trashbin and version paths configurable
https://github.com/owncloud/core/issues/22058#issue-130490959 Primary storage - object store and encryption

Note: could be done in steps. 
- Step one is deleting all existing user thumbs including db cleanup to eliminate existing orphans and go eg with idea #25770 what would eliminate the orphan topic generally. 
- Step two is centralisation with an "repair" procedure deleting all post created user thumbs and setup the central thumb store

**Comment by PVince81** [comment]
Had a discussion with @butonic for adding a new "target_fileid" column in oc_filecache for future symlink support and maybe pointing directly to target storages for mounts. If we had such column, it could also be used to achieve the purpose of the "ref_storage" you suggested.

For encryption, I think currently thumbnails aren't encrypted. If one day we encrypt them, then they'd need to be encrypted with the same keys like the original file, share keys, etc, so everyone who has access to the original file also has access to the thumbnail. It might need additional hook listeners in the thumbnail code.

**Comment by PVince81** [comment]
@butonic @DeepDiver1975

**Comment by mmattel** [comment]
Another use case beside thumbs for pictures would be thumbs for/from audio/video files (eg cover or album art)

**Comment by PVince81** [comment]
There was an older ticket about this feature request: https://github.com/owncloud/core/issues/17186

**Comment by PVince81** [comment]
linking another ticket with more discussions https://github.com/owncloud/core/issues/10808

**Comment by PVince81** [comment]
another one. https://github.com/owncloud/core/issues/17186

**Comment by PVince81** [comment]
Linking to duplicate: https://github.com/owncloud/core/issues/19548

**Comment by mmattel** [comment]
As user_x which has admin status, I had historically all my private mounts under admin and not under personal settings. I corrected this today by removing all mounts affected from admin and readded them under personal. Because I also have many pitures, I was wondering about the quantity of items rescanned.
```
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 14117   | 93859 | 00:08:16     |
+---------+-------+--------------+
```
Remembering about this issue here, I deleted manually the orphaned thumbs for user_x and rerun scanning...
```
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 3792    | 66132 | 00:05:36     |
+---------+-------+--------------+
```
**The difference was 4.2G in:**
```
+----------+-------+
| Folders  | Files |
+----------+-------+
| 10325    | 27727 |
+----------+-------+
```

Thumbnail orphans is really an issue !
