### ISSUE TITLE
[Feature Request] Access logging of public share links 

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#28930]
When creating a public share link, it would be great to have the ability to set a checkmark to log the access (timestamp) and if possible from which IP address this was made. Could be eg restricted to admins.

Like: ``Info, Share Link Access, <url> and share name, time stamp, IP``
(just as an idea of tags...)

Than this can be filtered by log readers based on ``Share Link Access`` and the ``url`` to monitor activity

**Comment by kdslkdsaldsal** [comment]
Somehow related to https://github.com/owncloud/core/issues/17495

**Comment by PVince81** [comment]
Define "access".

A share link can be accessed through multiple means:
- opening the link share in the web browser
- accessing public.php/webdav with the share token + share password with a Webdav client
- same as previous one but for federated shares, as they use this

If this is about restriction, then it's likely topic for the firewall app.

@pmaier1

**Comment by mmattel** [comment]
It is not about to restrict access... so no firewall intention...

The basic idea is that if I share a file/folder/mount, I would like to see if/when it has been accessed and if possible from which IP. Based on the Ip address I could use a free service like ``https://geoiptool.com/en/?IP=xx.xx.xx.x`` to identify the location.

I am only interested in web browser access, so no client or federation.
Something like a browser accessed history which is easy to see from the one who creates the share.
Classical logging could be one possibility, but also other methods are fine.

Thinking about this during writing, having that view directly at the share window respectively in the view of my shares with a clickable IP address opening a new window showing me the location would be great. Than we would need a config.php parameter for the (free) geo service like above. Even often not accurate, it would give me an idea...

**Comment by PVince81** [comment]
There were similar requests but where the downloads should be tracked, which is more complicated because rendering the thumbnail/preview also counts as a download by the browser: https://github.com/owncloud/core/issues/14446 https://github.com/owncloud/core/issues/13158

Logging access based on the web page should be easier.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
