### ISSUE TITLE
add quota view in the user management

### ISSUE THREAD

**Issue by Bobgermany** [owncloud/core#28943]
Every admin or group admin can see the quota from the users. If there is no free space on the system, the administrator can write an e-mail to the users with the most used memory so that they can delete files.

I'm not sure, where the right place to publish this idea.

**Comment by kdslkdsaldsal** [comment]
Hi,

seems this is something which is already discussed in https://github.com/owncloud/core/issues/1344 with some details how this should be implemented in https://github.com/owncloud/core/issues/1344#issuecomment-268736099.

I'm closing this for now, feel free to ping me if the linked issue is not what you're looking for.
