### ISSUE TITLE
Upgrade path from 8.1.12 to X on Fedora 26

### ISSUE THREAD

**Issue by imp1sh** [owncloud/core#28942]
### Steps to reproduce
1. Run OwnCloud 8 on Fedora 24
2. Upgrade Fedora to 26
3. Try to upgrade OwnCloud to 9

### Expected behaviour
let me upgrade

### Actual behaviour
 This version of ownCloud is not compatible with PHP 7.1.
 
### Server configuration
**Operating system**:
Fedora 26
**Web server:**
httpd 2.4.27-2.fc26.x86_64
**Database:**
mariadb-server-10.1.26-2.fc26.x86_64
**PHP version:**
php-7.1.8-1.fc26.x86_64
**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.11
**Updated from an older ownCloud or fresh install:**
Updated
**Where did you install ownCloud from:**
from tar.bz2
**Signing status (ownCloud 9.0 and above):**
-
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
redirects me to my files

**The content of config/config.php:**
<?php
$CONFIG = array (
  'passwordsalt' => 'wonttell',
  'datadirectory' => '/var/www/html/cloud/data',
  'dbtype' => 'mysql',
  'version' => '8.2.10.2',
  'dbname' => 'woelkchen',
  'dbhost' => 'wonttell',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'wolke',
  'dbpassword' => 'wonttell',
  'installed' => true,
  'instanceid' => '50a03927a796b',
  'ldapIgnoreNamingRules' => false,
  'loglevel' => '3',
  'maintenance' => false,
  'forcessl' => true,
  'theme' => '',
  'trusted_domains' =>
  array (
    0 => 'cloud.gosix.net',
  ),
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'jochen',
  'mail_smtppassword' => 'wontttell',
  'secret' => 'wonttell',
);
```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```
there is no such thing
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by kdslkdsaldsal** [comment]
Hi,

please note this is a bugtracker of ownCloud. Support questions like this needs to go to https://central.owncloud.org/

Nevertheless a short hint:

As the message is telling you your running ownCloud version is not compatible with PHP 7.1. The first version of ownCloud which is compatible with PHP 7.1 is 10.0: https://doc.owncloud.org/server/10.0/admin_manual/installation/system_requirements.html 

If you do upgrades of the OS and you have manually installed software always make sure that those are compatible with your new OS variant. If you're unsure people are always happy to answer such questions at https://central.owncloud.org which could have told you that you need to upgrade to a newer ownCloud version before upgrading to FC26
