### ISSUE TITLE
Integration test trashbin-old-endpoint.feature last scenario fails

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#28956]
### Steps to reproduce
1. In a dev environment, run the integration test feature:
```
./run.sh features/trashbin-old-endpoint.feature
```

### Expected behaviour
The test passes

### Actual behaviour
The last scenario fails:
```
  Scenario: Deleting an updated file into external storage moves it to the trashbin and can be restored                   # /home/phil/core/tests/integration/features/trashbin-old-endpoint.feature:142
    Given invoking occ with "files:scan --all"                                                                            # CommandLineContext::invokingTheCommand()
    And user "user0" exists                                                                                               # FeatureContext::assureUserExists()
    And user "user0" created a folder "/local_storage/tmp"                                                                # FeatureContext::userCreatedAFolder()
      Client error response [url] http://localhost:8080/remote.php/webdav/local_storage/tmp [status code] 405 [reason phrase] Method Not Allowed (GuzzleHttp\Exception\ClientException)
    And user "user0" moved file "/textfile0.txt" to "/local_storage/tmp/textfile0.txt"                                    # FeatureContext::userMovedFile()
    And user "user0" uploads chunk file "1" of "1" with "AA" to "/local_storage/tmp/textfile0.txt"                        # FeatureContext::userUploadsChunkedFile()
    And user "user0" deletes file "/local_storage/tmp/textfile0.txt"                                                      # FeatureContext::userDeletesFile()
    And as "user0" the folder with original path "/local_storage/tmp/textfile0.txt" exists in trash                       # FeatureContext::elementIsInTrashCheckingOriginalPath()
    And logging in using web as "user0"                                                                                   # FeatureContext::loggingInUsingWebAs()
    When as "user0" the folder with original path "/local_storage/tmp/textfile0.txt" is restored                          # FeatureContext::elementInTrashIsRestored()
    Then as "user0" the folder with original path "/local_storage/tmp/textfile0.txt" does not exist in trash              # FeatureContext::elementIsNotInTrashCheckingOriginalPath()
    And downloaded content when downloading file "/local_storage/tmp/textfile0.txt" with range "bytes=0-1" should be "AA" # FeatureContext::downloadedContentWhenDownloadindShouldBe()

--- Failed scenarios:

    /home/phil/core/tests/integration/features/trashbin-old-endpoint.feature:142

12 scenarios (11 passed, 1 failed)
138 steps (129 passed, 1 failed, 8 skipped)
1m15.18s (20.79Mb)
```
If I run the last scenario by itself, then it passes.

### Server configuration
Development environment with current core master or stable10.

**Comment by PVince81** [comment]
@phil-davis tests passed for me locally on stable10. Maybe you have some additional enabled apps that might interfere ?

**Comment by phil-davis** [comment]
The problem turned out to be that my "admin" account had no ``files`` folder (nothing at all actually) in ``data/admin`` - and so ``files:scan --all`` got an error processing the admin account. Since there were no other accounts at that point, it never happened to have the local storage in view, and so the local storage never got scanned.

Now I have no idea how that happened. I have tried various ways to delete all files for "admin" - that always leaves an empty ``files`` folder. Then I tried deleting the ``admin`` account, and any attempt at that fails correctly.

So I have run something from somewhere that managed to delete all the folders under ``data/admin`` - next time it happens I will recognize it more quickly and maybe can then track down the offending script/process.

**Comment by PVince81** [comment]
There used to be a bug in the trashbin, might have been OC 6 or OC 7, where you were able to delete the "files" folder by sending two DELETE operations in parallel (ex: double click on trash icon in UI, back then it was possible as it was not in a dropdown). The race condition led the code to get the `$path` of the folder to delete. But since it was already deleted by the concurrent operation, the `$path` was an empty string, which resolved to the "files" folder, so the second DELETE would just delete the "files" folder.

I really hope you didn't accidentally find another such bug...

**Comment by PVince81** [comment]
Ref: https://github.com/owncloud/core/issues/11183

**Comment by PVince81** [comment]
In general one always must reset the OC instance before running integration tests. Don't run them with existing and potentially broken users.

Close ?

**Comment by phil-davis** [comment]
I guess close. I was just trying to get to the bottom of what happened, and if reasonable, provide some fix that helps be nice to developers when "hacking" around in a dev environment - running a few unit tests, a few integration tests, a few UI tests... 

If the test runs do (as much as reasonable) work regardless of the state they found the system in, and leave the system in a nice state at the end, then that is friendly to devs.

But in this case, my admin account was actually really broken! I guess we can't expect a test run to always get around that.
