### ISSUE TITLE
OwnCloud Desktop Folder Icon

### ISSUE THREAD

**Issue by JochenHWezel** [owncloud/core#28963]
To be more visible on the local system as owncloud folder, windows provides possibility to setup a folder with its own folder icon.

![image](https://user-images.githubusercontent.com/14078625/30249246-b8e3e6ce-9638-11e7-815f-ea3534401d53.png)

To enable such folder icon, Microsoft has published the article at https://msdn.microsoft.com/en-us/library/windows/desktop/cc144102(v=vs.85).aspx

## For windows systems, it's pretty simple
1. Provide a folder icon (as .ico, .exe or .bmp)
2. Provide a desktop.ini (recommended with file encoding UTF-8 or UTF-16 + system flag + hidden flag); IconFile and IconIndex are required, all other entries might be senseful
```ini
[.ShellClassInfo]
ConfirmFileOp=1
NoSharing=1
IconFile=C:\Program Files (x86)\ownCloud\owncloud.exe
IconIndex=0
InfoTip=OwnCloud sync folder
```

3. Add the system attribute to the OwnCloud sync folder 
```cmd
attrib +s {folderpath}
```

## Especially when syncing several owncloud targets, this feature might be very useful to find the right folder more fast
![image](https://user-images.githubusercontent.com/14078625/30249372-a1692222-963b-11e7-8bf2-8af31963f4df.png)

## For our OwnCloud solution, I'd suggest the following
1. OwnCloud sync client automatically provides a folder icon by default by auto-adding a desktop.ini file to new sync folder setups (for existing installations: add the missing desktop.ini file) + adding the system attribute to all the target file sync folders
2. OwnCloud server admin can provide a default folder icon (desktop.ini file + referenced .ico file should not be set to hidden automatically because the sync client doesn't sync hidden files)
2.1. by adding an .ico file + desktop.ini file to the template folder for new users or
2.2. by sharing an .ico file + desktop.ini file from his root folder to all users
3. User can setup his own icon (for his individual, local machine only) by opening a search icon file dialog in the owncloud client at position (1)
![image](https://user-images.githubusercontent.com/14078625/30249537-9e2576c6-963e-11e7-8133-fc159c2ba2ec.png)
4. At position (2), the folder icon will be displayed as configured by steps 1 to 3

### Additional notes
* Another option might be to use the registry to setup a folder with an icon.
* The owncloud sync client might be installed to alternative paths, that's why it might be required to use an environment variable targetting the path to owncloud.exe or to use the registry option mentioned above to configure the folder icon - but I haven't verified yet, that customization of the folder icon would still be possible. If no, then the sync client should update the folder icon in registry on every launch and watch out for a foldericon.ico in every sync folder; if the file is there, use that file as folder icon, else use the owncloud sync client's default icon

### What needs to be done at minimum? / Expected efforts
* Minimum: To allow point 2 from above immediately, the owncloud sync client just had to configure the folder as system folder (attrib +s folder).
* Point 1 might require a little bit more coding (but should be little)
* Point 3 inclusive button at (1) and icon displaying at (2) might require the most development since it requires GUI development.

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/client/issues/5295

**Comment by jturcotte** [comment]
Mostly fixed by https://github.com/owncloud/client/pull/5955 (will use the icon of owncloud.exe).

**Comment by JochenHWezel** [comment]
The folder icon should also be shown at this place in systray context menu:
![image](https://user-images.githubusercontent.com/14078625/30784268-948deb56-a152-11e7-9109-579749130925.png)

**Comment by JochenHWezel** [comment]
Maybe it is useful for some guys looking for a workaround meanwhile:

I've created a desktop.init file (which is a desktop.ini file but points to my favorite .ico file; see also my sample a few messages above in this thread), my favorite .ico file and a .cmd (batch) file which can be started on every client which I use. All 3 files will be synced to all my several devices.

At every device, start the .cmd file and it will copy the desktop.init file into a desktop.ini file, make it hidden plus make the folder a system folder.
![image](https://user-images.githubusercontent.com/14078625/30784322-80b4cdb0-a153-11e7-96e9-5a8e12be82cd.png)

The .cmd file has got following content:
```cmd
@echo off
if exist desktop.ini del /a desktop.ini
echo Writing desktop.ini with folder icon reference . . .
copy desktop.init desktop.ini
echo.
echo Hiding desktop.ini file to match the MS Windows standards . . .
attrib +h desktop.ini
echo Setting up current folder as system folder to activate folder icon setting . . .
attrib +s .
echo.
echo FINISHED! Please review above output for any errors
pause
```
