### ISSUE TITLE
Encryption 9.1.6 > 10.0.2 default module enabled

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#28985]
### Steps to reproduce
1. Install ownCloud 9.1.6 
2. enable default encryption module
3. Upgrade to 10.0.2

### Expected behaviour
User specific key enabled, no drop down menu to choose master key encryption

### Actual behaviour
Drop down menu, for users to choose the different encryption modes.

**Comment by PVince81** [comment]
@sharidas please have a look. If any of the modes was already active when upgrading, the oc_appconfig keys need to be set appropriately to make sure the UI doesn't appear any more.

**Comment by PVince81** [comment]
@davitol can you test that the workaround works: basically the admin should select whatever mode they already selected in the past. We'll add an entry in the release notes.

**Comment by davitol** [comment]
Scenario 1 - Upgrade to 10.0.2 and do not select any option in the dropdown: Encrypted files are still available.
Scenario 2 - Upgrade to 10.0.2 and  select user-key option in the dropdown (same as before): Encrypted files are still available.

Scenario 2 - Upgrade to 10.0.2 and  select master key option in the dropdown: Encrypted files are no longer available. (see screenshot)

![screen shot 2017-09-13 at 17 49 52](https://user-images.githubusercontent.com/10596560/30387326-67e35248-98ac-11e7-9a4d-c771df2666c3.png)

**Comment by sharidas** [comment]
Both the changes for:
- [x] stable 10 branch : https://github.com/owncloud/core/pull/29049
- [x] master branch encryption: https://github.com/owncloud/encryption/pull/15 
are merged.

**Comment by PVince81** [comment]
@sharidas close ?

**Comment by sharidas** [comment]
Closing this issue as the changes are merged.
