### ISSUE TITLE
Package ownCloud 10 for Debian/Linux

### ISSUE THREAD

**Issue by danger89** [owncloud/core#28980]
### Steps to reproduce
1. Install PHP 7.1 (FPM) together with your apache/nginx webserver
2. Try to [upgrade owncloud package](https://download.owncloud.org/download/repositories/stable/owncloud/). 
3. You will see that the latest version provided is only: _Debian_8.0 owncloud-9.1.6-1._

### Expected behaviour
ownCloud 10 is production ready. Why is v10 not yet packaged, so I can switch to PHP 7.1. It's advised to run PHP 7.1, only ownCloud blocks me currently.

### Actual behaviour
I get an error message:

> This version of ownCloud is not compatible with PHP 7.1.

Related issue: #27570 

### Server configuration
**Operating system**: Debian Jessie (8.0)
**Web server:** Nginx
**Database:** MySQLi
**PHP version:** 7.1.9
**ownCloud version:** 9.1.6 (**I can't upgrade to 10!**)
**Where did you install ownCloud from:** ownCloud server repository (package + dependencies)

**Comment by PVince81** [comment]
There are already packages for OC 10 but they're not in the stable channel.

I had a look at https://owncloud.org/install#edition under "Packages" but can't seem to find the link to the matching repos and the "testing" links only has betas/RC1.

https://download.owncloud.org/download/repositories/testing/owncloud/ has 10.0.3RC1 but I'd also expect to find a link to the repo that provides 10.0.2.

@crrodriguez do you have it ?

**Comment by PVince81** [comment]
@danger89 found one here: https://download.owncloud.org/download/repositories/10.0/Debian_8.0/

**Comment by danger89** [comment]
@PVince81 
Thanks. Shouldn't [this webpage](https://download.owncloud.org/download/repositories/nightly/owncloud/) be updated accordantly? 

And how to use this new repository 10.0? Currently my owncloud.list looks like:
```
deb http://download.owncloud.org/download/repositories/stable/Debian_8.0/ /
```

Is it also safe to just upgrade from 9 to 10, via apt upgrade mechanism? Is that tested?

**Comment by hodyroff** [comment]
10.0.3 is in preperation and has 500+ issues fixed and added to the code base. This will be declared stable and then available in the described ways. Should be done before the ownCloud Conference which starts September 20th. Recommend to wait for that.

**Comment by danger89** [comment]
@hodyroff Thanks for the extra info. Maybe I should wait, but you didn't answer my questions.

**Comment by hodyroff** [comment]
Yes, would recommend waiting, but happy to give some additional answers:
1. this will be done with 10.0.3
2. yes, looks correct
3. yes and then continue with occ upgrade as your ownCloud will be in maintenance mode. And you always need to do a backup prior to starting any upgrade operations.
