### ISSUE TITLE
Add oc:privatelink PROPFIND property for files on old and new dav endpoints

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#28984]
Define a new property "oc:privatelink" that returns the private link as generated in the share panel.
- Use the IURLGenerator and the proper route and pass in the file id.
- Most of the code should live in the FILES_PLUGIN.
- The property must be protected (read-only).

**Comment by michaelstingl** [comment]
Related:
- https://github.com/owncloud/client/issues/6020
- https://github.com/owncloud/android/issues/2032
- https://github.com/owncloud/ios/issues/938

**Comment by PVince81** [comment]
Also add a capabilitiy:

- [ ] add oc:privatelink property in FilesPlugin + unit tests
- [ ] add capability

**Comment by michaelstingl** [comment]
Just to be sure: Link generated with new method will be used in web UI too?

**Comment by PVince81** [comment]
The web UI could be rewired to use this property, yes. Not sure if needed though.

**Comment by michaelstingl** [comment]
It would be cool, if private link from web UI also would respect settings from `config.php`, like `'overwritehost'` etc…

**Comment by PVince81** [comment]
@michaelstingl I think it should already as it should be using the URL generator from JS.

Let's double check this anyway:

- [ ] make sure web UI uses the same / a similar mechanism to make sure overwritehost is taken into account

@michaelstingl did you observe any cases where said link did not ? That would be a bug...

**Comment by michaelstingl** [comment]
> did you observe any cases where said link did not

Never tested - I only found links generated in clients showed different behaviour.

**Comment by IljaN** [comment]
I can only find a "Public-Link" in the Ui is it the same?

**Comment by PVince81** [comment]
looks like you found it 😄 

can you also extend the capabilities to say something like "privateLinks => true" ?

**Comment by PVince81** [comment]
and add a unit test...

**Comment by IljaN** [comment]
Request:
PROPFIND http://localhost:8000/remote.php/dav/files/admin/foo/zubulski.txt 
```xml
<?xml version='1.0' encoding='utf-8'?>
<propfind xmlns="DAV:">
  <prop>
    <privatelink xmlns="http://owncloud.org/ns"/>
  </prop>
</propfind>
```
Response:
```xml
<?xml version='1.0' encoding='utf-8'?>
<propfind xmlns="DAV:">
  <prop>
    <privatelink xmlns="http://owncloud.org/ns"/>
  </prop>
</propfind>
```
@michaelstingl, @PVince81: Could you get someone from client team to review the request response format? (I am webdav noob)

**Comment by michaelstingl** [comment]
@ckamm @SamuAlfageme @davivel @jesmrec Could you provide a quick feedback if @IljaN 's approach works for you?

**Comment by jesmrec** [comment]
works for me

**Comment by ckamm** [comment]
works for me as well

**Comment by felixboehm** [comment]
@michaelstingl works for you and all three clients?
Otherwise reopen please.

**Comment by michaelstingl** [comment]
@felixboehm If it works for @jesmrec and @ckamm , it works for me too 😄
