### ISSUE TITLE
10.0 in stable repo for debian

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#28994]
### Steps to reproduce
1. open stable repo for debian https://download.owncloud.org/download/repositories/stable/Debian_8.0/
2. see that 10.0 is missing
3. write issue

### Expected behaviour
10.0 is there

### Actual behaviour
10.0 is not there, but should be there, right?

**Comment by michaelstingl** [comment]
I found https://owncloud.org/release-channels/

May repo channels could be aligned with updater channels?

**Comment by kdslkdsaldsal** [comment]
Nope, 10.0.2 and below shouldn't be in stable according to @hodyroff in https://github.com/owncloud/core/issues/28980#issuecomment-328748246

Only 10.0.3+ will end-up there.

**Comment by voroyam** [comment]
@kdslkdsaldsal how would you answer the question on why any of the 10.0 versions are not in the stable channel without saying that the other versions are not stable?

Some people on central wonder why they are still on 9.1.6 and can't update to 10.0.2 although is was released. And some try a manual upgrade and fail.

**Comment by PVince81** [comment]
The problem currently is that different channels seem to have a different concept of "stable".
The tarballs "stable" usually come earlier than distro packages "stable" and web updater "stable".

**Comment by kdslkdsaldsal** [comment]
@voroyam That is a long running issue since years and is up to you guys to communicate transparently to the end-user. :-)

**Comment by voroyam** [comment]
@kdslkdsaldsal worth a try ;)

**Comment by PVince81** [comment]
from what I see 10.0.3 is now in the stable distro repos, closing
