### ISSUE TITLE
Email link will not redirect you to the folder

### ISSUE THREAD

**Issue by raphson93** [owncloud/core#28993]
### Steps to reproduce
1. Shared a folder by assigning to a group instead of individuals under sharing tab

### Expected behaviour
The file sharing link in email should redirect you to the folder.

### Actual behaviour
It did not redirect you to the folder.

### Server configuration
**Operating system**: Centos 7

**Web server:** apache

**Database:** mysql

**PHP version:** 5.6

**ownCloud version:** (see ownCloud admin page) 10.0.2 stable version

**Updated from an older ownCloud or fresh install:** Updated from older owncloud

**Where did you install ownCloud from:** from yum repository

**Signing status (ownCloud 9.0 and above):**
https://gist.github.com/raphson93/e6a9d310fc25c44e0ad0ce542677c532
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
https://gist.github.com/raphson93/3ad304b012f02d002de7efff4e82e82d
```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**
Enabled:
  - activity: 2.3.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.9
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.0
  - files_texteditor: 2.2
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.1.0
  - notifications: 0.3.0
  - onlyoffice: 1.1.3
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - twofactor_totp: 0.4.3
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - onlyoffice_bak
  - theme-example
  - twofactor_privacyidea
  - user_external

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** chrome

**Operating system:** Windows 10

#### ownCloud log (data/owncloud.log)
```
https://gist.github.com/raphson93/b9ab15e16e86664c8b5d46762ce730c1
```

**Comment by PVince81** [comment]
Does the sharing link you mean look like "index.php/f/12345" ? If yes, please try with 10.0.3RC1. There was a bug with the file list loading.

**Comment by raphson93** [comment]
@PVince81 
Yes the link looks exactly like what you described.
But I didn't see any update when I run the yum update command.

**Comment by PVince81** [comment]
no distro update yet, see https://github.com/owncloud/core/issues/28994. I suggest you wait for 10.0.3 to be out then upgrade with https://download.owncloud.org/download/repositories/10.0/

**Comment by PVince81** [comment]
please try upgrading to 10.0.3, it should be in the stable distro repo now.

If the problem persists, please reopen
