### ISSUE TITLE
Favorite star of the sidebar does not get lighted when we favorite a file using IE11 as browser

### ISSUE THREAD

**Issue by davitol** [owncloud/core#29009]
![screen shot 2017-09-14 at 10 58 17](https://user-images.githubusercontent.com/10596560/30425732-5b951d34-994a-11e7-961e-70686e06017d.png)

**Comment by PVince81** [comment]
I heard of this before... did you search for older tickets ?

**Comment by davitol** [comment]
> I heard of this before... did you search for older tickets ?

Yes and I did not found an open ticket for that. In the past there was a kind of similar issue but I think it was not exactly the same

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
