### ISSUE TITLE
App icons are missed in settings section using IE11 as browser

### ISSUE THREAD

**Issue by davitol** [owncloud/core#29004]
oC version "10.0.3 RC1"

Internet Explorer 11:
![screen shot 2017-09-14 at 08 58 24](https://user-images.githubusercontent.com/10596560/30416049-ed346756-992a-11e7-81d7-68112228b229.png)

Other Browsers:

![screen shot 2017-09-14 at 09 00 36](https://user-images.githubusercontent.com/10596560/30416110-323f4c1c-992b-11e7-9348-1af7f5747507.png)

**Comment by PVince81** [comment]
I seem to remember a browser bug where IE would not properly render SVG files when said files did not have a view box set. Not sure if it's the same issue with IE11.

**Comment by PVince81** [comment]
It is even likely that at that time we added a fix to prevent icons to appear with IE. If that one is still in place we can try removing it.

**Comment by PVince81** [comment]
@pmaier1 thougths on priority ?

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
