### ISSUE TITLE
Icons from First time Wizard are not shown properly using IE11 as browser

### ISSUE THREAD

**Issue by davitol** [owncloud/core#29005]
oC version "10.0.3 RC1"

Internet Explorer 11
![screen shot 2017-09-14 at 09 06 08](https://user-images.githubusercontent.com/10596560/30416602-160bf192-992d-11e7-8042-79907c0c1f99.png)

Other browsers:

![screen shot 2017-09-14 at 09 06 38](https://user-images.githubusercontent.com/10596560/30416633-2ce8d222-992d-11e7-8289-f0661624f935.png)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
