### ISSUE TITLE
Consolidate DAV, VFS, storage layers

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29006]
Currently every layer has its own format for paths.

On the DAV level we have:
- remote.php/dav/files/$userId/path/to/file
- and we'll likely have more paths for trashbin, versions, etc (see https://github.com/owncloud/core/issues/15646#issuecomment-100941735,  https://github.com/owncloud/core/issues/10571)
- nothing yet for metadata like avatars, previews, etc

On the ownCloud filesystem level we have:
- root storage entries: data/avatar/...
- data/$userId/files
- data/$userId/files_encryption
- data/$userId/files_trashbin
- data/$userId/files_versions
- mount points like ext storage or received shares attached on the VFS under "data/$userId/files/ext_storage_mountpoint"

On the real FS level:
Same as above but without the mount points.

It would be good to find a way to consolidate these different virtual filesystems to have ideally only one way of addressing everything. It doesn't necessarily need to match whatever is on the FS level (and FS level can be an object store) but rather whatever is visible inside of ownCloud and accessible through the Webdav APIs.

@DeepDiver1975 @butonic @jvillafanez

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
