### ISSUE TITLE
Duplicated window when sharing via link and it is set a wrong mail for notificate

### ISSUE THREAD

**Issue by davitol** [owncloud/core#29001]
![shareado](https://user-images.githubusercontent.com/10596560/30388394-e4d643fc-98af-11e7-9cc0-72540887d1e3.gif)

**Comment by davitol** [comment]
@PVince81 Dupe of https://github.com/owncloud/core/issues/28451   ?

**Comment by PVince81** [comment]
@davitol not exactly a dupe. The ticket you linked to was the original issue. That one was fixed, but the fix is not "strong" enough. So now a second dialog appears very briefly then disappears. Is less worse than having 4 dialogs appear and stay.

**Comment by PVince81** [comment]
@davitol is this still happening on stable10 ?

cc @felixheidecke

**Comment by PVince81** [comment]
setting to p2 high as it looks broken visually and might put off some people

**Comment by davitol** [comment]
> @davitol is this still happening on stable10 ?

It is no longer happening neither in master or stable 10 branch.

After clicking send button, it is kept showing the create link share window

![screen shot 2017-10-10 at 11 01 02](https://user-images.githubusercontent.com/10596560/31378140-96022006-adaa-11e7-91de-c624ac56bc49.png)

should we close the ticket?

**Comment by PVince81** [comment]
BLAM
