### ISSUE TITLE
Social share tooltips in Sidebar do not disappear using IE11 as browser

### ISSUE THREAD

**Issue by davitol** [owncloud/core#29008]
![screen shot 2017-09-14 at 11 56 15](https://user-images.githubusercontent.com/10596560/30425283-f8af2ed6-9948-11e7-88a7-88ee3a763d56.png)

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
