### ISSUE TITLE
Second share dialog appears quickly with email error

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29043]
### Steps

1. Go to settings page, sharing, and allow people to send email notification for public links
2. Open link share dialog for any file/folder
3. Type in an invalid email address
4. Click "Save"

### Expected result
Simple error popup

### Actual result
A second share dialog appears for a very short time then disappears before the popup appears.

### Version
stable10

**Comment by PVince81** [comment]
![mail-dialog-error](https://user-images.githubusercontent.com/277525/30537479-14e37246-9c6a-11e7-94a2-c9788f3eb5bf.gif)

**Comment by felixheidecke** [comment]
Should be fixed with https://github.com/owncloud/core/pull/29133
