### ISSUE TITLE
Public link shared folders: File list stays blank

### ISSUE THREAD

**Issue by cnmicha** [owncloud/core#29044]
### Steps to reproduce
1. Open a public shared folder link, it does not matter how old it is

### Expected behaviour
A list of all files inside the shared folder is displayed

### Actual behaviour
The file list stays blank
![screenshot](https://user-images.githubusercontent.com/10116544/30537766-59c258fe-9c6b-11e7-8eba-2552e80f78b3.jpg)

### Server configuration
**Operating system**: Ubuntu 14.04.5 LTS

**Web server:** NGINX for serving static files and Apache2 for PHP, set up by Plesk Onyx 17.5.3

**Database:** mysql  Ver 14.14 Distrib 5.5.57, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:** 7.1.9

**ownCloud version:** 10.0.2.1

**Updated from an older ownCloud or fresh install:** Updated from 9.x

**Where did you install ownCloud from:** Archive file from owncloud.org

**Signing status (ownCloud 9.0 and above):** https://gist.github.com/cnmicha/97941a89a98f810ebf596d4252c8d684

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "<removed>",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "<removed>"
        ],
        "datadirectory": "<removed>",
        "overwrite.cli.url": "<removed>",
        "dbtype": "mysql",
        "version": "10.0.2.1",
        "dbname": "<removed>",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "php",
        "mail_from_address": "noreply",
        "mail_domain": "<removed>",
        "mail_smtphost": "<removed>",
        "appstore.experimental.enabled": true,
        "mail_smtpport": "25",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "theme": "",
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "singleuser": false
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.4
  - announcementcenter: 1.2.0
  - calendar: 1.4.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: true
  - dav: 0.2.9
  - external: 1.2
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_clipboard: 0.6.2
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.0
  - files_texteditor: 2.2
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - guests: 0.4.1
  - market: 0.2.1
  - music: 0.5.1
  - notifications: 0.3.0
  - passman: 2.1.4
  - provisioning_api: 0.5.0
  - sharerenamer: 1.1
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - theme-xyz: 1.0.0
  - updatenotification: 0.2.1
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Google Chrome 61.0.3163.79, Firefox

**Operating system:** Windows 10 64 bit

#### Web server error log
No warnings/errors

#### ownCloud log (data/owncloud.log)
```
{"reqId":"ECjtvZwO8Svqh2drvnq2","level":3,"time":"2017-09-18T10:13:17+00:00","remoteAddr":"79.247.xxx.xx","user":"--","app":"PHP","method":"GET","url":"\/apps\/gallery\/config.public?extramediatypes=1&token=aDCsAhfW9BppNn3","message":"PHP Startup: Unable to load dynamic library '\/opt\/plesk\/php\/7.1\/lib\/php\/modules\/apc.so' - \/opt\/plesk\/php\/7.1\/lib\/php\/modules\/apc.so: cannot open shared object file: No such file or directory at Unknown#0"}
```

#### Browser log
```
jquery-migrate.min.js?v=4d4e13018c22e9aadb0c380d85b41ab0:2 JQMIGRATE: Migrate is installed, version 1.4.0
soundmanager2-jsmin.js?v=4d4e13018c22e9aadb0c380d85b41ab0:1 SoundManager 2: No Flash detected. Trying HTML5-only mode.
soundmanager2-jsmin.js?v=4d4e13018c22e9aadb0c380d85b41ab0:1 SoundManager V2.97a.20170601 (HTML5-only mode)
soundmanager2-jsmin.js?v=4d4e13018c22e9aadb0c380d85b41ab0:1 SoundManager 2 HTML5 support: mp3 = true, mp4 = true, ogg = true, opus = true, wav = true, flac = true
soundmanager2-jsmin.js?v=4d4e13018c22e9aadb0c380d85b41ab0:1 SoundManager 2: Ready. ✓
public.js?v=4d4e13018c22e9aadb0c380d85b41ab0:14 Uncaught TypeError: Cannot read property 'on' of undefined
    at Object.initialize (public.js?v=4d4e13018c22e9aadb0c380d85b41ab0:14)
    at public.js?v=4d4e13018c22e9aadb0c380d85b41ab0:20
    at underscore.js?v=4d4e13018c22e9aadb0c380d85b41ab0:41
DevTools failed to parse SourceMap: https://<removed>.com/core/vendor/jquery/dist/jquery.min.map
```

**Comment by cnmicha** [comment]
The issue even occurs with the following apps enabled:
```
Enabled:
  - dav: 0.2.9
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_sharing: 0.10.0
  - templateeditor: 0.1
```

**Comment by PVince81** [comment]
`select * from oc_share where token='$token'`. Replace $token with the token from the URL.

Then look at the value of "file_source" and run `select * from oc_filecache where fileid=$fileSource`, replace accordingly. Look at the value of "storage".

Then `select * from oc_storages where numeric_id=$storage`, replace accordingly.

Post the results (and anonymize if needed)

**Comment by PVince81** [comment]
closing due to lack of feedback.

it is also likely that this is an environment issue. check your network console in the link share and see why maybe the calls aren't getting through.

If you still think it's a bug, please reopen.
If you need help debugging your env, please post on https://github.com/owncloud/core/issues/29362
