### ISSUE TITLE
[regression] dav properties on non-files are not stored/retrieved properly

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#29047]
## description
regression was introduced in https://github.com/owncloud/core/pull/27005

symptom: dav properties on calendars cannot be set https://github.com/owncloud/calendar/issues/812

## action
- bring back the property path value
- if no fileid can be retrieved: use the property path
- kill OC\Connector\Sabre\CustomPropertiesBackend

**Comment by VicDeo** [comment]
@DeepDiver1975 the main idea  brhind this changecwas to reduce table size. 
Should we make the property path shorter than before?

**Comment by DeepDiver1975** [comment]
The table should remain small if we only Save the path in cases where we dont have the fileid like for calendars

**Comment by VicDeo** [comment]
@DeepDiver1975 it should be also taken into account that migration from propertypath to fileid drops all property values with unresolvable propertypath

**Comment by VicDeo** [comment]
@DeepDiver1975 I need your input on the following approach:

- table `oc_properties` referenced by `userid` and `path` 
- table  `oc_file_properties` referenced by `fileid` 
- Lazy migration to `fileid` where possible while accessing the properties.

And I haven't found the class `OC\Connector\Sabre\CustomPropertiesBackend` anywhere.
Did you mean one of those:
```
apps/dav/lib/Files/CustomPropertiesBackend.php:class CustomPropertiesBackend implements BackendInterface {
apps/dav/lib/Connector/Sabre/CustomPropertiesBackend.php:class CustomPropertiesBackend implements BackendInterface {
```

**Comment by DeepDiver1975** [comment]
> And I haven't found the class OC\Connector\Sabre\CustomPropertiesBackend anywhere.
> Did you mean one of those:

yes

**Comment by DeepDiver1975** [comment]
> propertypath makes no sense without an owner

this is true for webdav v1. But in webdav v2 we have the user in the path
remote.php/webdav/welcome.txt vs remote.php/dav/files/viktar/welcome.txt

We might want to add a table for all properties of non files dav resources oc_dav_properties
oc_properties can remain the way they are.

**Comment by VicDeo** [comment]
@DeepDiver1975 `apps/dav/lib/Connector/Sabre/CustomPropertiesBackend.php` is used in `OCA\DAV\Connector\Sabre\ServerFactory` with 'webdav' endpoint aka  webdav v1

while `apps/dav/lib/Files/CustomPropertiesBackend.php` is used in `OCA\DAV\Server` with 'dav' endpoint aka webdav v2

**Comment by DeepDiver1975** [comment]
I know - this needs to be cleanup. Properties set via dav need to be retrievable via webdav as well. And vis-versa. I suspect this can all be done in one backend - no need for two.

**Comment by VicDeo** [comment]
@DeepDiver1975 they looks pretty the same in general, but `apps/dav/lib/Connector/Sabre/CustomPropertiesBackend.php`  has more code 
namely
- soft fail for missing files and storages
https://github.com/owncloud/core/pull/14994
https://github.com/owncloud/core/pull/15126

and depth support for directories
https://github.com/owncloud/core/commit/9f6dcb9d3e2f43f336dafeb739e04ba9614d9b5f#diff-ee47f0ce20207c0c51ddd0481e47c580R112

I'm not sure whether the latter is used anywhere.

**Comment by VicDeo** [comment]
master: https://github.com/owncloud/core/pull/29136
stable10: https://github.com/owncloud/core/pull/29273
