### ISSUE TITLE
"Deprecated api access" warning by files_sharing after upgrading to OC v10.0.3

### ISSUE THREAD

**Issue by bcutter** [owncloud/core#29053]
### Steps to reproduce
1. Have a federated share with an OC v10.0.2.1
2. Update to OC v10.0.3

### Expected behaviour
Log is normal

### Actual behaviour
owncloud.log is flooded with warning messages (every minute)

I see those for all servers connected (with yellow status). One of them is still running OC v10.0.2.1 (talking **a lot** with my OC), another is on NC v12.0.0.29 (quite silent, only few log entries within 3 hours so far).

```
Level | App | Message | Time
Warning | files_sharing | Deprecated api access from xxx.xxx.xxx.xxx. Ask remote to upgrade. | a minute ago
Warning | files_sharing | Deprecated api access from xxx.xxx.xxx.xxx. Ask remote to upgrade. | 2 minutes ago
Warning | files_sharing | Deprecated api access from xxx.xxx.xxx.xxx. Ask remote to upgrade. | 3 minutes ago
Warning | files_sharing | Deprecated api access from yyy.yyy.yyy.yyy. Ask remote to upgrade. | 3 minutes ago
Warning | files_sharing | Deprecated api access from xxx.xxx.xxx.xxx. Ask remote to upgrade. | 4 minutes ago
```

Version of files_sharing on my OwnCloud server: 0.10.1

**Comment by bcutter** [comment]
Maybe similiar to https://github.com/nextcloud/server/pull/4418/files? Is it possible to "mute" these warnings or do I really NEED to be informed about this?

**Comment by bcutter** [comment]
... *bale of hay rolls through the picture* ...

**Comment by bcutter** [comment]
GUYS???

**Comment by DeepDiver1975** [comment]
> GUYS???

YES!

**Comment by bcutter** [comment]
So... I mean, honestly, I provided information and even referenced to a possible similar solution (muting the warnings).

What else do you expect from normal users besides being patient for more than 10 days? Is it because of missing man power? Anyway, ist just a bit frustrating. Thrilled to see if you could help me on this issue. Back to topic...

**Comment by DeepDiver1975** [comment]
> What else do you expect from normal users besides being patient for more than 10 days?

nothing more - but things are getting taken care of as time and resource permits.

**Comment by DeepDiver1975** [comment]
and yes the solution as done by nextcloud looks reasonable - feel free to submit a pull request to adjust things the same way.

**Comment by bcutter** [comment]
I´m not a developer and I have no idea how to submit pull requests. I´m "just" a technical user who mostly ends on GitHub when starting on central.owncloud.org with issues.

**Comment by DeepDiver1975** [comment]
> my owncloud.log is truely flooded.

which is not nice - but not an issue on the other hand. We will take care ....

**Comment by PVince81** [comment]
> do I really NEED to be informed about this?

@butonic ^

**Comment by PVince81** [comment]
see https://github.com/owncloud/core/pull/28059/files#r119588227

**Comment by bcutter** [comment]
Thank you @PVince81. That´s the root "cause". As mentioned there:

> I strongly vote for **reverting** those 4 lines (34-37). It´s annoying and - guess what - really helps NOTHING, especially when all the remote servers are hosted instances without admin access or even when they run Nextcloud.

For my current server i replaced those 4 lines with 4 nice ones:
```
/** REMOVED THAT SHITTY PART OF D*** F****** CODE RESPONSIBLE FOR FLOODING MY OWNCLOUD-LOG !!! **/
/** REMOVED THAT SHITTY PART OF D*** F****** CODE RESPONSIBLE FOR FLOODING MY OWNCLOUD-LOG !!! **/
/** REMOVED THAT SHITTY PART OF D*** F****** CODE RESPONSIBLE FOR FLOODING MY OWNCLOUD-LOG !!! **/
/** REMOVED THAT SHITTY PART OF D*** F****** CODE RESPONSIBLE FOR FLOODING MY OWNCLOUD-LOG !!! **/
```
And guess what? Silence. Now I sort out the huge owncloud.log by walking through with a sed regex and pray for having this "change" reverted in next OC version. So much annoyance because of one $%"§$* idea and 4 lines of code.

**Comment by PVince81** [comment]
@DeepDiver1975 have a minute for some row killing ?

If not I'll take care... heard enough complains about this and am not convinced either of its usefulness.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/29363
