### ISSUE TITLE
10.0.3: Shipped apps are marked as "approved" instead of "official"

### ISSUE THREAD

**Issue by ghost** [owncloud/core#29060]
### Steps to reproduce
1. Browse to app page in oC (e.g. https://example.com/settings/admin?sectionid=apps)
2. See that apps which are shipped in the official release (owncloud-10.0.3.tar.bz2) are sometimes Marked as "official" and others are marked as "approved".

### Expected behaviour
I would expect that e.g. "Notifications" is marked as "Official" as it is shipped in the owncloud-10.0.3.tar.bz2 archive.

### Actual behaviour
See step 2.

This can be seen on https://demo.owncloud.org/settings/admin?sectionid=apps as well. 

### Server configuration
**ownCloud version:** 10.0.3

**Comment by PVince81** [comment]
I think we removed the "Official" label and there's only "Approved" now.

In the end all these apps, including "notifications", etc, will be moved to the marketplace anyway as per https://github.com/owncloud/core/issues/27542

@DeepDiver1975 is that correct ?

**Comment by DeepDiver1975** [comment]
Absolutly - there is no difference anymore between official and approved.

we basically opened up the system - why should an app by the owncloud company be labeled different then an app by anybody else?

there are ideas to add additional labels to the apps on the marketplace which give more indication about the stability, quality and security status of an app.

**Comment by DeepDiver1975** [comment]
From my pov this can be closed

**Comment by kdslkdsaldsal** [comment]
> From my pov this can be closed

I guess the overview should be still fixed or am i wrong? Because you still get the different labels "Official" and "Approved" shown on https://demo.owncloud.org/settings/admin?sectionid=apps

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
