### ISSUE TITLE
status.php no does not respects productname in app theme

### ISSUE THREAD

**Issue by Emil-G** [owncloud/core#29066]
### Steps to reproduce
1. Use application theme

### Expected behaviour
status.php shows the defined productname in the theme.

### Actual behaviour
It now only shows "owncloud". 

It is correctly sat in settings/admin?sectionid=general . 

### Server configuration
**Operating system**:
Redhat
**Web server:**
Apache
**Database:**
Oracle
**PHP version:**
PHP 7.0.10 
**ownCloud version:** (see ownCloud admin page)
10.0.3
**Updated from an older ownCloud or fresh install:**
updated
**Where did you install ownCloud from:**
Enterprise tarball
**Signing status (ownCloud 9.0 and above):**
not relevant

**The content of config/config.php:**
not relevant

**List of activated apps:**
not relevant

**Are you using external storage, if yes which one:** local/smb/sftp/...
not relevant
**Are you using encryption:** yes/no
not relevant
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
not relevant

### Client configuration
**Browser:**
not relevant
**Operating system:**
not relevant
#### Web server error log
not relevant
#### ownCloud log (data/owncloud.log)
not relevant

**Comment by PVince81** [comment]
hmmm @mmattel any idea ?

**Comment by PVince81** [comment]
@Emil-G is your theme in the "themes" folder or did you make an app out of it ?

@phisch

**Comment by Emil-G** [comment]
@PVince81 Because of recent issues with the themes folder (Company icon is now midt centered, and the wording "owncloud" has been added to the center of the header with no way of removing it), I have made an app out of it. The defaults.php enterprise example theme contains the exact same information and variables, so I am not sure why the change is not picket up by the app theme.

**Comment by michaelstingl** [comment]
What I just got:

> Status.php is correct when using the themes folder, however when using it as an app, the status.php does not show the same as the admin page. Sorry about the confusion.

@phisch Please check

**Comment by VicDeo** [comment]
@Emil-G please check https://github.com/owncloud/core/pull/29647

**Comment by VicDeo** [comment]
Fixed in 10.0.4RC2
