### ISSUE TITLE
Restrict to share only to users/groups within group membership

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29075]
Currently there's an option called "Restrict users to only share with users in their groups".

This option is limited to restricting with "users" but not "membership groups".

The option should be split into two:
- "Restrict users to only share with users in their groups"
- "Restrict users to only share with groups they are member of"

Estimate: 1-2md.

The change itself should be easy. Adjusting/writing tests might take most of the time.

@pmaier1

**Comment by PVince81** [comment]
@jvillafanez any update on this ?

**Comment by jvillafanez** [comment]
I think this can be closed because the PR and the backport have been merged.
