### ISSUE TITLE
fail to rename a file on the web UI

### ISSUE THREAD

**Issue by splusz** [owncloud/core#29078]
### Steps to reproduce
Try to rename a file on the web UI.

### Expected behaviour
The file is renamed.

### Actual behaviour
Failed to rename the file. A flash error message occurred and the page was reload after a few seconds.

### Server configuration
**Operating system**:
Ubuntu 16.04.1 LTS

**Web server:**
Apache 2.4

**Database:**
MySQL 5.7

**PHP version:**
PHP 7,0
**ownCloud version:** (see ownCloud admin page)
10.0.2

**Updated from an older ownCloud or fresh install:**
Updated from 9.1.2, but the problem exists with 9.1.2, upgrading doesn't fix this.

**Where did you install ownCloud from:**
manually installed from official site

**List of activated apps:**
Enabled:
  - activity: 2.3.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.9
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.0
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.1.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1

Disabled:
  - encryption
  - external
  - files_antivirus
  - theme-example
  - user_external

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
chrome Version 60.0.3112.101 (Official Build) (64-bit)
**Operating system:**
Windows 7

**Comment by phil-davis** [comment]
What is the original filename and the name you are trying to rename it to?
Is there anything in the ownCloud log?
Can you post a screenshot or recording so we can see what is the reported message in the UI?

**Comment by kdslkdsaldsal** [comment]
It might also worth to update to the latest 10.0.3 release before reporting any issues. 😄

**Comment by splusz** [comment]
@phil-davis @kdslkdsaldsal  Thanks for helping. I have updated my owncloud to the latest 10.0.3 release.
Still have this problem. It did not add any thing to owncloud.log.  I tried to rename test.txt to test2.txt. The reported message was at the top of the page with a yellow back-ground, written in Chinese, saying that there was a problem or error while loading the page, and the page would be reloaded in 5 seconds.
Other operations like delete/add/modify files are fine.

**Comment by phil-davis** [comment]
I checked in my Ubuntu 16.04.3 LTS VM with PHP 7.0.22 and ownCloud 10.0.3. Using Firefox 55.0.2 I changed my language to Chinese and logout/login and create then rename files like test.txt and it works fine. So it is not a language thing.

**Comment by splusz** [comment]
I copied the owncloud files and database to my PC(the server configs are the same) and restored this new owncloud-server. I did not copy the data files (too many...) . On both of the  servers,  I created a new user and did the renaming test. It worked fine on the copied local server,  but failed on the other.

**Comment by kdslkdsaldsal** [comment]
@splusz You might want to run litmus against your live server to see if this server environment / setup is configured correctly and provides all needed HTTP verbs like MOVE (used for the renaming operation), REPORT, PROPFIND and so on.

https://central.owncloud.org/t/how-to-compile-and-run-litmus-on-debian-for-webdav-tests/839

I guess this is most likely just a server misconfiguration.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
