### ISSUE TITLE
a Error

### ISSUE THREAD

**Issue by KuzeHibiki** [owncloud/core#29082]
I Copy all core file in my website, He Say:Composer autoloader not found, unable to continue. Please run "make".

**Comment by kdslkdsaldsal** [comment]
@KuzeHibiki Please note this is a bugtracker for ownCloud. Support questions like this needs to go to http://central.owncloud.org/ where you can login with your github account.

IMPORTANT: If posting there please make sure that you provide more details about your environment. Currently nearly every info is missing and it is not possible to help there as well.
