### ISSUE TITLE
Specific file "intercept.js" will not upload through web interface ("Upload timeout")

### ISSUE THREAD

**Issue by CharlieEcho2** [owncloud/core#29089]
In two words: a file called "intercept.js" does not upload through the web interface.

### Steps to reproduce
1.Create a file called "intercept.js". The content does not really matter.
2. Drag-and-drop it through the web interface wherever you want.
3. You directly get the error message "upload timeout for file intercept.js"
4. The same file with a different name can be uploaded without any problem.

### Expected behaviour
The file should be uploaded like all others of the same directory.

### Actual behaviour
I get the error "upload timeout"

### Server configuration
**Operating system**: 
Linux  4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-06-26T11:58:04

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

Installed | true
maintenance | false
needsDbUpgrade | false
version | 10.0.3.3
versionstring | 10.0.3
edition | Community
productname | ownCloud

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
Download latest build

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No errors have been found.

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => 'ocyp224whohu',
  'passwordsalt' => 'r10voswYRqjl1WkaF5TO6PDQ',
  'secret' => 'DdbVY2KtusV3ScVIdREPsgyMC8mY71BULN7nrs',
  'trusted_domains' =>
  array (
    0 => 'MY_IP_ADDRESS',
  ),
  'datadirectory' => 'what it should be',
  'overwrite.cli.url' => 'https://IP address',
  'dbtype' => 'mysql',
  'version' => '10.0.3.3',
  'dbname' => 'oc_as',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc',
  'dbpassword' => 'TtelGORRAZPPr2WPFP',
  'logtimezone' => 'UTC',
  'installed' => true,
);

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```
Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.2
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - theme-example
  - user_external

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** yes/no
NO
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
**Browser:**
Firefow 55.0.3 (32 bits)

**Operating system:**
Win10 

#### Web server error log
```
NO specific error log.

Insert your webserver log here
```
[23/Sep/2017:23:52:42 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 1092 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0"
#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
{"reqId":"nMknAuyu7q4BUVcV3OGi","level":3,"time":"2017-09-23T21:50:54+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php\/20151012\/php_intl.dll' - \/usr\/lib\/php\/20151012\/php_intl.dll: cannot open shared object file: No such file or directory at Unknown#0"}

#### Browser log
```
Insert your browser log here, this could for example include:

Deprecation warning: tipsy is deprecated. Use tooltip instead.

a) The javascript console log
b) The network log 
c) ...
```

**Comment by phil-davis** [comment]
Upload works fine for me on 10.0.3 with that file name ``intercept.js``
This is the place for reporting confirmed bugs.
Please first ask for help at https://central.owncloud.org/

**Comment by PVince81** [comment]
Please check if your hosting environment has a firewall that prevents uploading files with such names.
Unlikely to be an OC bug as there is no name based filtering in place, closing.
