### ISSUE TITLE
Files metadata endpoint

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29087]
@DeepDiver1975 @butonic as discussed at the conference:

"/meta/$fileid" DAV and View endpoints to access versions, etc.

![img_20170922_120725](https://user-images.githubusercontent.com/277525/30776882-d74c108e-a0ae-11e7-937d-b04db9014712.jpg)

**Comment by DeepDiver1975** [comment]
DAV @sharidas :
- [ ] create MetaData collection in dav app - name 'meta'
- [ ] second path is the file id (uuid encoded bigint)
- [ ] create subfolder v for versions
- [ ] create subfolder p for previews

Filesystem @deepdiver1975:
- [ ] create mount 'meta' and corresponding storage implementation
- [ ] define storage interfaces for versions etc

Frontend:
- [ ] use v dav endpoint in versions sidebar
- [ ] use p dav endpoint to generate previews

**Comment by DeepDiver1975** [comment]
Test Scenarios:
- [ ] restore version of read only shared file -> shall not be allowed

**Comment by PVince81** [comment]
@DeepDiver1975 are we done ?

**Comment by DeepDiver1975** [comment]
once preview is done - yes
