### ISSUE TITLE
owncloud shows empty directory after usb reconnect

### ISSUE THREAD

**Issue by meiti** [owncloud/core#29085]
Hi

I have mounted an usb drive on orangepizero and have created a local external storage. It works, and I can view its content.

But after disconnecting usb drive and connecting it again, owncloud does not load the list of files/folders.
I can resolve this problem by deleting local external storage and creating it again.

What is the problem, could anybody help me?

owncloud version: 10.0.3
BOARD=orangepizero
BOARD_NAME="Orange Pi Zero"
VERSION=5.25
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"

Thanks

**Comment by PVince81** [comment]
was OC in maintenance mode when you unplugged the USB drive ?

**Comment by PVince81** [comment]
you can check the `oc_filecache` table to see if it still contains the file entries

**Comment by meiti** [comment]
Hi

was OC in maintenance mode when you unplugged the USB drive ? 
No

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
