### ISSUE TITLE
not allow to add content on local folder

### ISSUE THREAD

**Issue by fantapereira** [owncloud/core#29101]
hello all:
              I'm looking for a solution that prohibite the creation of a folder, upload files, etc, on the local Owncloud storage. For security and backup reasons we must have all the content located on SMB folders (those folders are being created at the same time the user is created). But some users still uploading content and creating foldesrs on the local storage.

Is there a way to disable the creation of folders and files locally?

**Comment by kdslkdsaldsal** [comment]
@fantapereira Please note that this is a bugtracker of ownCloud. Questions like this needs to go to https://central.owncloud.org/ (you can login with your github account there).

Nevertheless a short hint:

You can set the quota of your users to 0 (zero) bytes and then they are able to only upload to the external storages. They still can create files with 0 bytes and folders on the internal storage but thats another topic which is tracked in https://github.com/owncloud/core/issues/10455
