### ISSUE TITLE
Files view: Freeze top bar

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#29118]
**Freeze top bar (red)**
If you have many items in the file view you have to scroll. Currently the top bar (with column names) vanishes when scrolling down. We should freeze it for that it stays and column names are always visible.

Please ignore the blue stuff on the image below.

![top_bar](https://cloud.githubusercontent.com/assets/21193500/22109378/c77eebbe-de57-11e6-8a85-3597df9b941a.png)

@PVince81 @felixheidecke Please assign.

**Comment by felixboehm** [comment]
The path "breadcrumb" above is fixed already. Needs designer input.
@michaelstingl @felixheidecke

**Comment by michaelstingl** [comment]
should just stay on the top, same as breadcrumb navigation

**Comment by fredbcode** [comment]
I have something close (but not similar) 
After some days without problem, now the files are not showed

Version 10.0.2.1

The shares still work, and windows client also works well
- I made a rescan 
- Nothing in log 
- I removed owncloud directory and reinstall it (just save config and owncloud.sql)

But still there is no column name and + 

Perhaps I should open an another bug report, if you think it's not related

![capture](https://user-images.githubusercontent.com/5287473/31334381-6b149c32-acee-11e7-9928-49a7ea86e99e.PNG)
 ?

**Comment by pmaier1** [comment]
> Perhaps I should open an another bug report, if you think it's not related

@fredbcode As this ticket is about a UI change of the files view your report has nothing to do with it. Please file a separate bug report with more information and log files. You can also ask for help on central.owncloud.com.

**Comment by felixheidecke** [comment]
Please see: https://github.com/owncloud/core/pull/29440

**Comment by michaelstingl** [comment]
Well done 👍

**Comment by PVince81** [comment]
solution needs more work, moving to "planned"

**Comment by PVince81** [comment]
backlog for rescheduling
