### ISSUE TITLE
No updates seen when inviting people to calandar entries

### ISSUE THREAD

**Issue by schachtnerth-zz** [owncloud/core#29114]
Hi there,

I'm using owncloud for quite some time now and I'm still fascinated!
Main purpose for using ownCloud is the calendar which is really awsome. Up to now, I only used standard calendar entries like appointments, recurring events such as birthdays and so on and multiple calendars.

Yesterday I wanted to add participients to the calendar entry. This also seems to work pretty fine, as all the attendees receive meeting invitations.
However, when they answer them, I get a mail into my Inbox, but the OwnCloud calendar is not updated accordingly.
It would be great to have some overview which attendees have accepted and which ones have not...
But maybe this involves having a separate E-Mail-Adress for OwnCloud calendar, right?
But maybe there's another approach... (Or does this already work and I just didn't realize it?)

Best regards,
Tom

**Comment by DeepDiver1975** [comment]
Thanks a lot for your feedback - I need to dig into the specifications to see what needs to be implemented to get this to work

**Comment by PeterPablo** [comment]
What is the technical state on this topic? Can the issue be reopened, if this is not yet implemented?

**Comment by DeepDiver1975** [comment]
But reopening alone will help nothing .... someone needs time to look into this and take care ....
