### ISSUE TITLE
 Improve public link sharing permissions for folders

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#29116]
Currently the meaning of the option "Allow editing" (Download/Upload/Rename/Delete/Move) essentially changes to "Allow upload" (Upload only) when the second option "Show file listing" is unticked. This is inconsistent and can be very confusing for users. Moreover we thought a lot about how to make the file drop feature better understandable. See below the suggestion. IMHO this provides the best UX we can get. Feel free to come up with another idea, of course.

Instead of offering checkboxes with different combinations we should switch to radio buttons that are single choice and deliver a clear understanding of their functionality:

- Download/View only
- Download/View, Upload and Edit
- Upload only (drop folder) -> Tooltip (mouse-over; only for WebUI): "Use this option to receive files from externals without revealing actual contents of the folder."

This needs to be changed in the WebUI, desktop client and mobile clients as well.

**Comment by PVince81** [comment]
@felixheidecke please take care

**Comment by felixheidecke** [comment]
@pmaier1 I agree with changing the labeling. It's confusing right now.
I regard to the wording, I suggest sticking to the common lingo as well as a little description:

- **Read only**
Users can view and download files.
- **Read & Write**
Users can view, download, edit and upload files.
- **Upload (filesdrop)**
Receive files from others without revealing the contents of the folder.

This caters to those who already understand read, write permission style. Others are helped by a short description which is always visible below the function itself. I advise against tooltips where possible to have a more coherent UX across devices.

**Comment by pmaier1** [comment]
@felixheidecke looks great so far!

I was expecting the advice regarding tooltips :) you're right, ok! Just checked with @haukman.
Some little changes, please:
---

- [ ] **Read only**
Users can view and download contents.
- [ ] **Read & Write**
Users can view, download, edit and upload contents.
- [ ] **Upload only (File Drop)**
Receive files from others without revealing the contents of the folder.

**Comment by michaelstingl** [comment]
Client issues here:

- https://github.com/owncloud/client/issues/6192
- https://github.com/owncloud/android/issues/2066
- https://github.com/owncloud/ios/issues/967
