### ISSUE TITLE
No marketplace connection: Client error response

### ISSUE THREAD

**Issue by Eric-Sparks** [owncloud/core#29127]
### Steps to reproduce
1. Performed upgrade from 9.x to 10.0.3
2. Received an error stating "OC\RepairException: Upgrade is not possible"

### Expected behaviour
The file should be at the location.

### Actual behaviour
        Repair warning: No marketplace connection: Client error response [url] https://marketplace.owncloud.com/api/v0/api/v1/platform/10.0.3/apps.json [status code] 404 [reason phrase] Not Found
        Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
        Repair warning: Please install or update the following apps manually or disable them with: occ app:disable activity occ app:disable files_pdfviewer occ app:disable files_texteditor occ app:disable gallery
        Repair warning: For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps

# wget https://marketplace.owncloud.com/api/v0/api/v1/platform/10.0.3/apps.json 
--2017-09-29 17:24:31--  https://marketplace.owncloud.com/api/v0/api/v1/platform/10.0.3/apps.json
Resolving marketplace.owncloud.com (marketplace.owncloud.com)... 2a01:4f8:161:73ec::2, 5.9.68.237
Connecting to marketplace.owncloud.com (marketplace.owncloud.com)|2a01:4f8:161:73ec::2|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-09-29 17:24:35 ERROR 404: Not Found.

### Server configuration
**Operating system**: CentOS 7

**Web server:** httpd

**Database:** mysql

**PHP version:** php 56

**ownCloud version:** 10.0.3

**Updated from an older ownCloud or fresh install:** update

**Where did you install ownCloud from:** downloaded via updater

**Signing status (ownCloud 9.0 and above):** ?

**The content of config/config.php:**

{
    "system": {
        "instanceid": "oc9v9ebqhszn",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.christensenplace.us",
            "christensenplace.us"
        ],
        "datadirectory": "\/data",
        "overwrite.cli.url": "https:\/\/www.christensenplace.us\/own",
        "dbtype": "mysql",
        "version": "9.1.6.2",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "nobody",
        "mail_domain": "christensenplace.us",
        "maintenance": false,
        "dbname": "own",
        "dbhost": "localhost:3306",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "enabled_previews": false,
        "loglevel": 2,
        "log_type": "owncloud",
        "logfile": "\/data\/owncloud.log",
        "logdateformat": "F d, Y H:i:s",
        "check_for_working_webdav": false,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "trashbin_retention_obligation": "31",
        "appstoreurl": "https:\/\/marketplace.owncloud.com\/api\/v0",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**List of activated apps:**

Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.7
  - encryption: 1.3.0
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_sharing: 0.10.0
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: true
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - external
  - files_antivirus
  - theme-example
  - user_external

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 52.3.0 (64-bit)

**Operating system:** RHEL 7

**Comment by kdslkdsaldsal** [comment]
Removing the following from your config.php should do the trick:

``"appstoreurl": "https://marketplace.owncloud.com/api/v0",``

**Comment by Eric-Sparks** [comment]
Yep, this worked.  Why wouldn't the upgrade script fix this?
