### ISSUE TITLE
Integration Tests: missing check in WebDav trait

### ISSUE THREAD

**Issue by cortho** [owncloud/core#29139]
When I have an exception in _listFolder_ (see https://github.com/owncloud/core/blob/master/tests/integration/features/bootstrap/WebDav.php#L487)
Then _array_keys() expects parameter 1 to be array, object given_ in https://github.com/owncloud/core/blob/master/tests/integration/features/bootstrap/WebDav.php#L1081
because _$elementList_ was not checked to be an array.

**Comment by SergioBertolinSG** [comment]
Hi @cortho , in which situation you need this step 

```gherkin
When /^user "([^"]*)" deletes everything from folder "([^"]*)"$/
```

to not fail when the listFolder function cannot list the elements?

**Comment by cortho** [comment]
@phil-davis was faster, this is his PR: https://github.com/owncloud/core/pull/29157

**Comment by phil-davis** [comment]
I never noticed this issue - I was looking at test logs today and saw the problem. @cortho is using this method in an AfterScenario to do a general cleanup of "rubbish" that [has been|might have been] uploaded during a scenario. For scenarios that do not upload anything, the folder is already empty.

The AfterScenario could be changed to do different cleanup (e.g. probably should delete the user that was created - then the user's files will be gone and the skeleton will come back when a user is created again in the next scenario)

But in any case, this ``deletes everything from folder`` should be fixed up to work with an empty folder anyway.

**Comment by SergioBertolinSG** [comment]
OK, lets merge that then.

**Comment by cortho** [comment]
Working as expected now, thanks. Merged, backported -> closing
