### ISSUE TITLE
Share dialog of Folder not fit within windows size for low desktop resolution (below 1366x768)

### ISSUE THREAD

**Issue by NothingCtrl** [owncloud/core#29137]
### Steps to reproduce
1. Desktop resolution is 1366 x 768
2. In Admin panel, tab Sharing, tick: "Allow users to send mail notification for shared files" 
3. Select a **folder**, click Share, in Sharing tab, click "Create public link"

### Expected behaviour
Popup share dialog should in center and fit within windows

### Actual behaviour
Popup share dialog does not fit within windows, some buttons cannot see clearly.
![screenshot from 2017-10-03 09-32-32](https://user-images.githubusercontent.com/5380820/31107782-1c32c4c8-a81f-11e7-989a-ecfbe184ca82.png)

### Server configuration
**Operating system**: Ubuntu Xenial

**Web server:** Nginx / Apache

**Database:** Marial DB

**PHP version:** 7

**ownCloud version:** 10.0.3

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

**Comment by DeepDiver1975** [comment]
@felixheidecke

**Comment by felixheidecke** [comment]
@NothingCtrl … hmm, can't reproduce with Chrome Version 61.0.3163.100 on Ubuntu based dist.
Can you pls. supply Browser and Version?

**Comment by felixheidecke** [comment]
Was fixed, unfortunately, wasn't backported to stable10 :-|
