### ISSUE TITLE
[FR] Sender should be able to get a notification if the reciever of a direct share accessed it

### ISSUE THREAD

**Issue by haukman** [owncloud/core#29146]
Use Case:

User A shared a folder with User B and wants to get a Notification (email) when the User B accessed a file inside the folder that was shared with him. 

@hodyroff already explained to me that we can only track the start of a download and can´t monitor the completion of a download.

Related to this https://github.com/owncloud/enterprise/issues/2112#issuecomment-334382437

**Comment by haukman** [comment]
@hodyroff @pmaier1

**Comment by hodyroff** [comment]
Oh, really Folder? File might be way easier.

**Comment by haukman** [comment]
From my understanding, a user will always download a file. Even if he downloads a complete folder, oC will zip the content to a single file. Or does this make a difference?

**Comment by kdslkdsaldsal** [comment]
Looks similar / the same like https://github.com/owncloud/core/issues/13158

Another ref: https://github.com/owncloud/core/issues/18923

**Comment by mmattel** [comment]
Similar to #28930

**Comment by PVince81** [comment]
In general, define "access".

What's a "direct share" ? If it's a private link in the form "/f/12345" then we're talking about something else. In the case of private link we could detect that said link was opened once before it gets redirected to the actual file/folder in the web UI.

**Comment by PVince81** [comment]
@haukman see last comment

**Comment by haukman** [comment]
@PVince81 No, I´m not referring to a private link. This case is related to a "normal" share that User A can create for User B with permissions XY.

**Comment by PVince81** [comment]
Okay, so this would be mostly about adding a "accessed" or "downloaded" activity to the list.
Activities can already send out emails.

**Comment by PVince81** [comment]
Note that if we go with "accepting user shares" https://github.com/owncloud/core/issues/19153, we'd generate an activity which itself would be able to send emails. Would that cover their use case ?

Basically not about access, but accepting a share. We can assume that if a user accepted a share they'll anyway intend to access it / sync it actively.

**Comment by PVince81** [comment]
My point is mostly about clarifying the use case. If the use case is "as a user, I want to know whether the other person actually received my share" then the accept notification would do nicely.

If it's really about "receiving the share is not enough, I want to know that the user actually downloaded whatever important file is in there", then it's not enough.

**Comment by haukman** [comment]
The use case behind it is to see if someone accessed a file I shared with them - I know that we can´t track if the download was completed, but we at least we see if he tried to access it at all.  

Nevertheless, I also like the idea to have an entry in my activity mail that shows if someone accepted my share :)

**Comment by PVince81** [comment]
not sure what approach to use it, maybe wait for "accept share" task to be done.

moving to triage with p3 as this is old and inactive
