### ISSUE TITLE
Redis not available for local cache - Opensuse 42.3 Owncloud 10.0.3 PHP7.0.7

### ISSUE THREAD

**Issue by cezarylee** [owncloud/core#29141]
### Steps to reproduce

1.    install owncloud 10.0.3
2.    install redis-server, redis-client and php7-redis
3.    configure memcache in owncloud config (like I understood the documentation..)

### Expected behaviour
Tell us what should happen

### Actual behaviour
First: transactional file locking should be configured to use memory-based locking, not the default slow database-based locking

After doing tips from manual to setup redis... ->

memcache \OC\Memcache\Redis not available for local cache. Is the matching php module installed and enabled

### Server configuration
**Operating system**:

Operating system: OpenSuse Leap 42.3

Web server: Apache2

Database: Mysql mysqlnd 5.0.12-dev

PHP version: 7.0.7

ownCloud version: 10.0.3 (newest)

```
**The content of config/config.php:**

```
'filelocking.enabled' => true,
'memcache.locking' => '\OC\Memcache\Redis',
'redis' => [
     'host' => 'localhost',
     'port' => 6379,
     'timeout' => 0.0,

```
**Are you using external storage, if yes which one:** local/smb/sftp/...no

**Are you using encryption:** yes/no



#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
{"reqId":"htUEv24HhzcibcnDQiQM","level":3,"time":"2017-09-29T00:02:16+00:00","remoteAddr":"127.0.0.1","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/index.php","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/srv\/www\/htdocs\/owncloud\/lib\/composer\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18"}
{"reqId":"CKxVyghNTCoZxQNbf4bF","level":3,"time":"2017-09-29T00:07:55+00:00","remoteAddr":"127.0.0.1","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/index.php","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/srv\/www\/htdocs\/owncloud\/lib\/composer\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18"}
{"reqId":"431oaPnbuqhL5i5KK69A","level":3,"time":"2017-09-29T00:17:39+00:00","remoteAddr":"127.0.0.1","user":"--","app":"PHP","method":"POST","url":"\/owncloud\/index.php","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/srv\/www\/htdocs\/owncloud\/lib\/composer\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18"}
{"reqId":"fv8rIByaEFWqnz66yQpV","level":3,"time":"2017-09-29T00:21:21+00:00","remoteAddr":"127.0.0.1","user":"--","app":"PHP","method":"POST","url":"\/owncloud\/index.php","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/srv\/www\/htdocs\/owncloud\/lib\/composer\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18"}


```
The goal is to enable redis service. I also did that:

1. Installed Redis by:

 wget http://download.redis.io/releases/redis-4.0.2.tar.gz
 tar xzf redis-4.0.2.tar.gz
 cd redis-4.0.2
 make
 make install

ealier add php7-redis

2. Copy config file of redis from tar package
    sudo cp /tmp/redis-stable/redis.conf /etc/redis 
and changed in file:

**/etc/redis/redis.conf**

They do not enable continuous liveness pings back to your supervisor.
_supervised systemd_
and
Note that you must specify a directory here, not a file name.
_dir /var/lib/redis_

Then I created a file:
**/etc/systemd/system/redis.service**

[Unit]
Description=Redis In-Memory Data Store
After=network.target

[Service]
User=redis
Group=redis
ExecStart=/usr/local/bin/redis-server /etc/redis/redis.conf
ExecStop=/usr/local/bin/redis-cli shutdown
Restart=always

[Install]
WantedBy=multi-user.target

sudo mkdir /var/lib/redis
sudo chown redis:redis /var/lib/redis
sudo chmod 770 /var/lib/redis

then, after run
sudo systemctl start redis

I have an error:

sudo systemctl status redis
● redis.service
   Loaded: loaded (/etc/systemd/system/redis.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since wto 2017-10-03 19:36:02 CEST; 3h 5min ago
  Process: 25274 ExecStop=/usr/local/bin/redis-cli shutdown (code=exited, status=1/FAILURE)
  Process: 25272 ExecStart=/usr/local/bin/redis-server /etc/redis/redis.conf (code=exited, status=1/FAILURE)
 Main PID: 25272 (code=exited, status=1/FAILURE)

paź 03 19:36:02 linux-kye3 systemd[1]: Stopped redis.service.
paź 03 19:36:02 linux-kye3 systemd[1]: Started redis.service.
paź 03 19:36:02 linux-kye3 redis-server[25272]: 25272:C 03 Oct 19:36:02.311 # Fatal error, can't open con...onf'
paź 03 19:36:02 linux-kye3 systemd[1]: redis.service: Main process exited, code=exited, status=1/FAILURE
paź 03 19:36:02 linux-kye3 redis-cli[25274]: Could not connect to Redis at 127.0.0.1:6379: Connection refused
paź 03 19:36:02 linux-kye3 systemd[1]: redis.service: Control process exited, code=exited status=1
paź 03 19:36:02 linux-kye3 systemd[1]: redis.service: Unit entered failed state.
paź 03 19:36:02 linux-kye3 systemd[1]: redis.service: Failed with result 'exit-code'.
paź 03 19:36:14 linux-kye3 systemd[1]: Stopped redis.service.
Warning: redis.service changed on disk. Run 'systemctl daemon-reload' to reload units.
Hint: Some lines were ellipsized, use -l to show in full.

3. Also I did an entry in php.ini 
extension=redis.so

Still owncloud site is blank with error message: 
memcache \OC\Memcache\Redis not available for local cache. Is the matching php module installed and enabled

Also no entry in phpinfo() about redis function.

Please help...

**Comment by kdslkdsaldsal** [comment]
Please note this is a bugtracker of ownCloud. Support requests like this needs to go to https://central.owncloud.org (you can login with your github account there).

Note: The exit code issue of redis-server should go to a support channel of your distro.

Nevertheless a short hint:

> Also no entry in phpinfo() about redis function.

As long as you don't get the PHP redis module / extension showing up there redis support won't work within ownCloud.

**Comment by cezarylee** [comment]
OK, thanks, I will create a new topic there.
