### ISSUE TITLE
Restore issue: unable to restore files containing text 'business case' from 'deleted files' from webbased server

### ISSUE THREAD

**Issue by Bluefiedl** [owncloud/core#29159]
Dear support, 

Somehow, while change the directory, the following files disappeared from owncloud, both desktop and webbased UI. 

They're still findable via the finder search index, but no longer in the owncloud directory. I tried restoring them via the owncloud web UI, but still no trace. 

I added screenshots of the files. 

Could you please do some digging on the filename and possibly restore the files or e-mail them to jeroen@bluefieldagency.com? 

It would be a real lifesaver. 

A million thanks. 

### Steps to reproduce
1. Restore deleted files 
2. 
3.

### Expected behaviour
All files should be restored

### Actual behaviour
Files are not restored, just a directory. Not the contents of directory '07 MBC'

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** 
**2.3.3**

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

![schermafbeelding 2017-10-06 om 10 48 20](https://user-images.githubusercontent.com/32566022/31270497-e8b87026-aa84-11e7-9b60-ea6ca2cbb474.png)
![schermafbeelding 2017-10-06 om 10 48 14](https://user-images.githubusercontent.com/32566022/31270495-e89b5cf2-aa84-11e7-80ac-f6de552f4b34.png)

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by kdslkdsaldsal** [comment]
> Could you please do some digging on the filename and possibly restore the files or e-mail them to 

ownCloud is a self-hosted software. Only you or your hoster/server admin has access to that file.

Besides that most info in the provided in the issue template like ownCloud version (MANDATORY!!!) or logfiles are missing. This makes it impossible to help here.

**Comment by hodyroff** [comment]
Will reopen when more information is provided.
