### ISSUE TITLE
Use theme variables instead of hard-coded ownCloud

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29172]
See https://github.com/owncloud/core/commit/afcb4a070dc149c4f30b4876dae7af8aad62ef1b#diff-8be54a6d336a8809304ef06b951698a9R44

This must use the theme variables like the old theme did.

@felixheidecke please fix. I suggest going through your changes from the related PR to find all changes that would hard-code the product name or other theme related things. You can check the old theme to find out what PHP code to use to access theme variables.

cc @michaelstingl

**Comment by PVince81** [comment]
@michaelstingl @felixheidecke were we done with this ? If yes please close

**Comment by felixheidecke** [comment]
Yes, this has been addressed (and fixed) in https://github.com/owncloud/core/pull/29161
