### ISSUE TITLE
Calendar Events are not Privat from IOS to Outlook

### ISSUE THREAD

**Issue by Gexxinator** [owncloud/core#29170]
Hi,

i use Owncloud 10 on a Iphone 5, Ipad 4 and 2 Windows PC with Office 2016.
Only 1 Windows PC shouldn´t see the private or busy events from the boss (he is using all the other devices).
When i set a event as busy on Iphone or Ipad, the event is coming up on Outlook as a Event with a visible event description, but it should be private. 
I set up the Outlook CalDav sync privacy settings (ticked all on) but it doesn´t work.

Pls help me. TY

**Comment by kdslkdsaldsal** [comment]
Thanks for your report. I'm closing this as a duplicate of https://github.com/owncloud/core/issues/26161
