### ISSUE TITLE
Travis UI Testing gets behind

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#29199]
On a "normal"  working day there are quite a lot of PRs submitted, then people push an extra commit or 2 as they fix up issues from code reviews or CI results or...

When a PR is merged, then Travis-CI runs again on the "new" commit that has arrived on ``master`` branch.

Then most PRs have a backport to ``stable10`` - another run of CI, then a merge and another run of CI in ``stable10``.

So Travis gets behind (and gradually catches up in European night time).

We run the UI tests on both `chrome and firefox for all of the above. Tests for IE11 (and for future browsers we would like to test) run as a Travis Cron job on the main branches once each day.

Maybe we should move firefox back to the daily Travis cron job, and just test on chrome for each PR?

That would help the Travis backlog a lot.

Opinions please.

**Comment by phil-davis** [comment]
@PVince81 @DeepDiver1975 @individual-it @SergioBertolinSG @davitol annd anyone else...

**Comment by phil-davis** [comment]
See #29285 for a PR that gets UI tests running on current Firefox.
With that in place, we could get rid of Firefox 47 UI tests - because we really do not care about Firefox 47. The downside of doing that is that the new version Firefox UI tests do not yet run automatically on Travis+SauceLabs, they have to be run on a local machine of somebody for now.

In any case, we could move firefox 47 UI tests back to the daily Travis cron job.

**Comment by individual-it** [comment]
we could run the tests in FF56+ locally on every new release till saucelabs let us run them in CI

**Comment by phil-davis** [comment]
Addressed by #29288 - we now run a full set of UI tests on chrome for each PR. UI tests on Firefox47 and IE are run on master and stable10 in the daily Travis cron job. UI tests for the latest Firefox need to be run "manually" as needed. Edge testing is coming...
