### ISSUE TITLE
Network drive is not working

### ISSUE THREAD

**Issue by ryankkim** [owncloud/core#29194]
We deployed owncloud 10.0.3

and made Network drive Z: location is http://demo-ni.cloudrim.co.kr/remote.php/webdav/

and then.. we start web brower IE11 to download an attachment via email system.

When we download some file directly into Network drive Z. After complete downloading.
 We can see that file detail attribute size is 0 KB with right clicking. So we can not open that file with any application.

We can open the correct file though Web interface. but We cannot open that file though Network drive.
After rebooting laptop computer. I can open that file though Network drive.
 Without rebooting, Can I fix this problem? please help me

**Comment by kdslkdsaldsal** [comment]
@ryankkim Please fill out the shown issue template when creating a new issue:

https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

Currently all required infos about your environment, logfiles etc. are missing.

**Comment by ryankkim** [comment]
### Steps to reproduce
I am downloading a file from the browser to the webdav-network-drive
And then when you check the properties of the file it says "0 bytes"

### Expected behaviour
the properties of the file should be Not 0 bytes

### Actual behaviour
Tell us what happens instead

the properties of the file is 0 bytes

### Server configuration
**Operating system**:
/etc/centos-release:CentOS release 6.8 (Final)
/etc/redhat-release:CentOS release 6.8 (Final)
/etc/system-release:CentOS release 6.8 (Final)


**Web server:**
apache-2.4.16

**Database:**
mysql-5.7.18

**PHP version:**
php-5.6.11

**ownCloud version:** (see ownCloud admin page)
owncloud-10.0.3.tar.bz2

**Updated from an older ownCloud or fresh install:**
no
**Where did you install ownCloud from:**
owncloud.org

**Signing status (ownCloud 9.0 and above):**
above
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
attachment

**The content of config/config.php:**
attachment
```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.
[config_report_20171010.txt](https://github.com/owncloud/core/files/1377189/config_report_20171010.txt)
[owncloud.log](https://github.com/owncloud/core/files/1377190/owncloud.log)

**Comment by ryankkim** [comment]
[config_report_20171010.txt](https://github.com/owncloud/core/files/1377192/config_report_20171010.txt)

**Comment by ryankkim** [comment]
[owncloud.log](https://github.com/owncloud/core/files/1377194/owncloud.log)

**Comment by ryankkim** [comment]
If the directory name or file name of the network drive is English, it will be processed normally. However, when either of them is Korean, it is treated abnormally 0KB.

**Comment by PVince81** [comment]
> {"reqId":"Htm9GhB5ptOjOmLGHbTf","level":3,"time":"2017-10-11T08:08:16+00:00","remoteAddr":"1.223.145.117","user":"--","app":"PHP","method":"GET","url":"\/cron.php","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/home\/rimdrive\/docroot\/owncloud\/lib\/composer\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18"}

@ryankkim please install the PHP intl module and restart the web server. That should hopefully fix it.

**Comment by ryankkim** [comment]
@PVince81 We installed the PHP intl mdule and restart the web server. But The problem is still exist.
This is Log file. Can you please give other suggestion?
[owncloud1015.log](https://github.com/owncloud/core/files/1385254/owncloud1015.log)

**Comment by ryankkim** [comment]
![capture](https://user-images.githubusercontent.com/32667638/31584549-5db81102-b1eb-11e7-9872-aec412f97621.jpg)

**Comment by PVince81** [comment]
@ryankkim are you saying that the Windows Explorer file list displays the correct size but not the properties page ? Could this be a bug in Windows Explorer with Webdav ?

Can you use another Webdav client like "cadaver" (command line) or do a `curl -u username:password -X PROPFIND https://yourserver/remote.php/webdav` and see if the property "getcontentlength" has the correct size ?

Then do the same PROPFIND call directly on the file.

**Comment by ryankkim** [comment]
@PVince81 Yap, not the properties page.
This could be a bug in Windows Explorer.
I done your suggestion. “getcontentlength” has the correct size. but not the properties page.

**Comment by PVince81** [comment]
This is a bug in Windows Explorer then, you might want to update Windows or check its knowledge based for known issues with Webdav.

In this case there is nothing that can be done from the ownCloud side, sorry.
