### ISSUE TITLE
FR: defaultapp on per user/group base

### ISSUE THREAD

**Issue by stkjj** [owncloud/core#29218]
config.php knows 

`  'defaultapp' => '',`

for a global setting to present chosen app after login.

Enhancement would be to have this setting configured on a per user or per group base. If possible within a separate app

**Comment by PVince81** [comment]
@pmaier1

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
