### ISSUE TITLE
Can not add any remote sharing.

### ISSUE THREAD

**Issue by achih** [owncloud/core#29222]
### Steps to reproduce
1. Login a version 10.0.3.3 owncloud.
2. Have a public link generate by another owncloud server(any version).
3. Use the link , and use "add to my owncloud" button.
4. Input the 10.0.3.3 owncloud server's URL.
5. It will show up a dialog window. Of course press Yes.

### Expected behaviour
It should be have a remote folder in root path.

### Actual behaviour
Nothing happen.

### Server configuration
**Operating system**: 
Docker image: owncloud:latest
(from http://hub.docker.com)

**Database:** MariaDB 5.5

**ownCloud version:** 10.0.3.3

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** http://hub.docker.com

**Signing status (ownCloud 9.0 and above):** no problems

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => ' Sensitive data ',
  'passwordsalt' => ' Sensitive data ',
  'secret' => ' Sensitive data ',
  'trusted_domains' => 
  array (
    0 => '192.168.1.33:8097',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'http://192.168.1.33:8097',
  'dbtype' => 'mysql',
  'version' => '10.0.3.3',
  'dbname' => 'owncloud_test',
  'dbhost' => '192.168.1.31',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => ' Sensitive data ',
  'logtimezone' => 'UTC',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
);

**List of activated apps:**
Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.2
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_ldap: 0.9.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - theme-example
  - user_external

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox x64 / Chrome x64

**Operating system:** win10 x64

#### ownCloud log (data/owncloud.log)
{"reqId":"Sensitive Data","level":3,"time":"2017-10-12T12:52:43+00:00","remoteAddr":"192.168.123.123","user":"admin","app":"index","method":"POST","url":"\/index.php\/apps\/files_sharing\/external","message":"Exception: {\"Exception\":\"TypeError\",\"Message\":\"Argument 4 passed to OCA\\\\Files_Sharing\\\\External\\\\Manager::__construct() must implement interface OCP\\\\Notification\\\\IManager, instance of OC\\\\HTTPHelper given, called in \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/ajax\\\/external.php on line 75\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/ajax\\\/external.php(75): OCA\\\\Files_Sharing\\\\External\\\\Manager->__construct(Object(OC\\\\DB\\\\Connection), Object(OC\\\\Files\\\\Mount\\\\Manager), Object(OC\\\\Files\\\\Storage\\\\StorageFactory), Object(OC\\\\HTTPHelper), Object(OC\\\\Notification\\\\Manager), Object(OCA\\\\FederatedFileSharing\\\\DiscoveryManager), 'admin')\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Route.php(155) : runtime-created function(1): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#2 [internal function]: __lambda_func(NULL)\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Route\\\/Router.php(307): call_user_func('\\\\x00lambda_151', Array)\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(928): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_sha...')\\n#5 \\\/var\\\/www\\\/html\\\/index.php(56): OC::handleRequest()\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/apps\\\/files_sharing\\\/lib\\\/External\\\/Manager.php\",\"Line\":80}"}

**Comment by PVince81** [comment]
@achih is the target server from the public link using invalid or self-signed certificates ?

**Comment by achih** [comment]
@PVince81 Both servers are http:// .

Thank you for the reply.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
