### ISSUE TITLE
Change in status.php from 9.1.x to 10.x

### ISSUE THREAD

**Issue by pako81** [owncloud/core#29228]
### Steps to reproduce
1. Upgrade from 9.1.x to 10.x
2. Check status.php

### Expected behaviour

Values `true`/`false` are now double-quoted. It was on 9.1.x: `"installed":true,"maintenance":true,` but on 10.x is: `"installed":"true","maintenance":"false",`

### Actual behaviour

For consistency reasons this should not have changed. It could indeed create issues with Load Balancers expecting a well given string

### Server configuration
**Operating system**:

Ubuntu 16.04

**Web server:**

Apache 2.4

**Database:**

MariaDB 10

**PHP version:**

7.0.x

**ownCloud version:** (see ownCloud admin page)

10.0.3

**Updated from an older ownCloud or fresh install:**

Updated from 9.1.x

Probably this is the commit introducing the change: https://github.com/owncloud/core/commit/a7173150d6b077d90d31a6123e3e3e1b68238dcc

@mmattel I don't think this change is intented so it could be a potential regression. Could you comment please ?

**Comment by PVince81** [comment]
@mmattel can you clarify whether the change from boolean to strings was intentional ?

This would need updating the release notes and documentation as some people use scripts to parse these values. I know you're the kind of person who always request docs additions and as far as I remember you didn't here, so maybe the change was not intentional ? 😄 

If not intentional, we should add this to the "known issues" in the release notes.

**Comment by mmattel** [comment]
It was not intentional to change the type of the output - I am in sorry for that :anguished:
How to proceed...?

**Comment by PVince81** [comment]
@mmattel thanks for confirming. Can you make a PR to adjust it and another one to the release notes page in the documentation to mention that it's a known issue ?

**Comment by PVince81** [comment]
(don't be alarmed by the word "urgent", it basically just means it's a showstopper for the next release)

**Comment by PVince81** [comment]
@SergioBertolinSG can we have an integration test that simply checks the output of status.php in a way that the data type is asserted as well ?

**Comment by SergioBertolinSG** [comment]
@PVince81 sure.

**Comment by mmattel** [comment]
PR is here: https://github.com/owncloud/core/pull/29261
