### ISSUE TITLE
Perf regression for fed share PROPFIND on new dav endpoint

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29226]
### Steps

1. Setup two ownClouds OC_A and OC_B
1. Share a folder "Photos" from OC_B to admin@OC_A
1. Login as admin@OC_A
1. Accept the share
1. Refresh the web UI file list or PROPFIND "/Photos" and check access log

### Expected result
Only a single Depth:1 PROPFIND on the "/Photos" folder on OC_B

### Actual result
A PROPFIND not only on "/Photos" but also on all entries, including files.
This is not efficient.

### Versions
ownCloud v10.0.3 for both instances

In my setup OC_A is "localhost/owncloud" and OC_B is "localhost/owncloudtest".
When doing a PROPFIND on OC_A's "Photos" folder, we can see a PROPFIND on all sub-entries on OC_B:

```
127.0.0.1 - - [12/Oct/2017:16:29:19 +0200] "GET /owncloudtest//ocs-provider/ HTTP/1.1" 200 602 "-" "ownCloud Server Crawler"
127.0.0.1 - Fi8O7MQHAFYR5eR [12/Oct/2017:16:29:19 +0200] "PROPFIND /owncloudtest/public.php/webdav/ HTTP/1.1" 207 715 "-" "sabre-dav/3.2.2 (http://sabre.io/)"
127.0.0.1 - Fi8O7MQHAFYR5eR [12/Oct/2017:16:29:19 +0200] "PROPFIND /owncloudtest/public.php/webdav/Paris.jpg HTTP/1.1" 207 680 "-" "sabre-dav/3.2.2 (http://sabre.io/)"
127.0.0.1 - Fi8O7MQHAFYR5eR [12/Oct/2017:16:29:19 +0200] "PROPFIND /owncloudtest/public.php/webdav/San%20Francisco.jpg HTTP/1.1" 207 690 "-" "sabre-dav/3.2.2 (http://sabre.io/)"
127.0.0.1 - Fi8O7MQHAFYR5eR [12/Oct/2017:16:29:20 +0200] "PROPFIND /owncloudtest/public.php/webdav/Squirrel.jpg HTTP/1.1" 207 683 "-" "sabre-dav/3.2.2 (http://sabre.io/)"
127.0.0.1 - Fi8O7MQHAFYR5eR [12/Oct/2017:16:29:20 +0200] "PROPFIND /owncloudtest/public.php/webdav/data1.dat HTTP/1.1" 207 697 "-" "sabre-dav/3.2.2 (http://sabre.io/)"
127.0.0.1 - Fi8O7MQHAFYR5eR [12/Oct/2017:16:29:20 +0200] "PROPFIND /owncloudtest/public.php/webdav/data2.dat HTTP/1.1" 207 697 "-" "sabre-dav/3.2.2 (http://sabre.io/)"
127.0.0.1 - admin [12/Oct/2017:16:29:18 +0200] "PROPFIND /owncloud/remote.php/dav/files/admin/Photos/ HTTP/1.1" 207 3139 "-" "cadaver/0.23.3 neon/0.30.2"
```

**Comment by PVince81** [comment]
Note that this is when doing a PROPFIND on the **new** dav endpoint.

The **old** dav endpoint doesn't go that deep.

A quick debug showed that the new DAV endpoint is triggering a "multiple PROPFIND" algorithm in Sabre DAV, which is likely asking the DAV storage to retrieve the data for each sub-node.

Apparently https://github.com/owncloud/core/pull/28853 does not fix it. I thought it maybe bypassed node caching in Sabre. Doesn't seem so.

The other possible fix would be to have the DAV plugin do a Depth:1 propfind for the hasUpdated call and automatically also cache the subnodes. But could be unefficient when we're not interested in the sub-nodes anyway.

Needs more debugging and comparing between old endpoint stack trace and new endpoint stack trace... It seems some older optimization is missing here.

cc @DeepDiver1975

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by PVince81** [comment]
I'll need to retry this at some point. Closing for now as the PR was merged
