### ISSUE TITLE
error pages are not themed

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#29242]
I am adding an extra / in the middle of the URL to provoke an error:

https://demo.owncloud.com//status.php

The demo.owncloud.com instance should respond with an error message on light blue background as our enterprise theme is installed there. 
Instead it responds with an error message on dark blue background
![err1](https://user-images.githubusercontent.com/1108546/31546609-52809b4c-b024-11e7-9a1f-43515c05b314.png)

FYI: @michaelstingl

**Comment by jnweiger** [comment]
BTW: Is it okay to produce an error at all in this case? I'd say yes it is technically okay (although a bit unfriendly), as per RFC2396 (3.3.) path segments are 'separated by a single slash "/" character.'

**Comment by michaelstingl** [comment]
@phisch has this been already fixed? The reported oC instance is a `10.0.2` version:

```
$ curl https://demo.owncloud.com/status.php
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.2.1","versionstring":"10.0.2","edition":"Enterprise","productname":"ownCloud"}
```

**Comment by kdslkdsaldsal** [comment]
Maybe with 10.0.3 with https://github.com/owncloud/core/pull/28622 ?

**Comment by PVince81** [comment]
Note that the "add trusted domain" page has been removed in 10.0.3 also... So this bug will likely be obsolete anyway with 10.0.3.

@jnweiger please try again with 10.0.3 and reopen if you find another similar issue if there's another error page.

**Comment by michaelstingl** [comment]
@tboerger please update https://demo.owncloud.com/

**Comment by tboerger** [comment]
@mstingl done, running 10.0.3 now

**Comment by tboerger** [comment]
Ah, but it's still not themed. And beside that it's pretty strange that we get the trusted domain error, the docker image got a hack to accept all domains.

**Comment by DeepDiver1975** [comment]
It is the job of each theme to take care of the error pages -> close
