### ISSUE TITLE
TBD: Hard-requirement for php-intl

### ISSUE THREAD

**Issue by kdslkdsaldsal** [owncloud/core#29247]
Concerning the following log-entries:

``
{"reqId":"Htm9GhB5ptOjOmLGHbTf","level":3,"time":"2017-10-11T08:08:16+00:00","remoteAddr":"1.2.3.4","user":"--","app":"PHP","method":"GET","url":"/cron.php","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at /var/www/owncloud/lib/composer/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php#18"}
``

https://github.com/owncloud/core/issues/28079 -> Issue with app installation (``Archives of type application/octet-stream are not supported`` during app upgrade/installation) fixed by installing/enabling php-intl according to @bartmans in https://github.com/owncloud/core/issues/28079#issuecomment-333485833 and https://github.com/owncloud/core/issues/28079#issuecomment-333597384

https://github.com/owncloud/core/issues/29194 -> Issue with e.g. Korean chars on external storages. Suggestion by @PVince81 in https://github.com/owncloud/core/issues/29194#issuecomment-336439679 to install the php-intl module

IIRC there where also other issues fixed after installing php-intl but its currently only an "optional" extension listed at https://doc.owncloud.org/server/latest/admin_manual/installation/source_installation.html#optional

If installing this extension is fixing such issues shouldn't it be a hard requirement?

**Comment by DeepDiver1975** [comment]
I'm all in to make it a hard requirement. 👍

**Comment by kdslkdsaldsal** [comment]
Some refs for older discussions about that: https://github.com/owncloud/core/issues/20065 / https://github.com/owncloud/3rdparty/pull/249 / https://github.com/owncloud/core/issues/22324 / https://github.com/owncloud/core/pull/22446

When reading those correctly there might even more to use / suggest / require or am i wrong:

https://github.com/owncloud/3rdparty/pull/249/files#diff-d6d06ec90186a854079e1165c473b6f3L1245

**Comment by PVince81** [comment]
I'd put this on the same level like php-gd and others. If the module is not enabled, OC refuses to work.

Once this is done, make sure this is mentioned on the release notes.

**Comment by DeepDiver1975** [comment]
In addition we shall see if we still need the patchwork library - it is used to get add intl implementations on php level.

**Comment by PVince81** [comment]
@jvillafanez can you take care of this ?

**Comment by jvillafanez** [comment]
PR in https://github.com/owncloud/core/pull/29500

**Comment by kdslkdsaldsal** [comment]
All PRs merged, closing.
