### ISSUE TITLE
Upgrade to 10.0.3 impossible

### ISSUE THREAD

**Issue by chpeller** [owncloud/core#29252]
Hi Everybody,

This morning when i wanted to connect to my Onecloud server, i had a message to upgrade it to the 10.0.3 version, without any possible to delay this upgrade and to connect to my profile.
Then i pushed the "Upgrade" boutton and after a few minutes i had this message : " OC\RepairException: Upgrade is not possible

        Avertissement de réparation :Exception
        Avertissement de réparation :L'application ne peut être installée car elle contient du code non-autorisé
        Avertissement de réparation :You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
        Avertissement de réparation :Please install or update the following apps manually or disable them with: occ app:disable documents occ app:disable mail occ app:disable gallery
        Avertissement de réparation :For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps"

Sorry the message is partialy in french but i think the basics are in english.

I need to connect as soon as possible and some users too.
If you have any suggestion to fix this problem i should be very happy to be advised.

Thanks by advance

Regards

**Comment by kdslkdsaldsal** [comment]
@chpeller Please note this is a bugtracker of ownCloud. Support questions like this needs to go https://central.owncloud.org/ (you can login with your github account there).

Nevertheless a short hint:

Your posted message is already give you the needed info what to do to continue with the upgrade:

> Please install or update the following apps manually or disable them with: occ app:disable documents occ app:disable mail occ app:disable gallery
