### ISSUE TITLE
UI tests - waitTillPageIsLoaded does not work correctly for trashbin

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#29264]
### Steps to reproduce
1. run trashbin UI tests
2. watch selenium output during check if files are in trashbin

### Expected behaviour
test should check if the files are listed in the trashbin after the page is loaded

### Actual behaviour
the tests cycles in `waitTillPageIsLoaded()` till end of timeout even the page get loaded correctly

in selenium output log many rounds of this is shown:
```
10:19:19.785 INFO - Executing: [find elements: By.xpath: //html/.//*[./@id = 'fileList']])
10:19:19.792 INFO - Done: [find elements: By.xpath: //html/.//*[./@id = 'fileList']]
10:19:19.793 INFO - Executing: [find elements: By.xpath: (//html/.//*[./@id = 'fileList'])[1]//a])
10:19:19.799 INFO - Done: [find elements: By.xpath: (//html/.//*[./@id = 'fileList'])[1]//a]
10:19:19.801 INFO - Executing: [find elements: By.xpath: //html/.//*[@id='emptycontent']])
10:19:19.812 INFO - Done: [find elements: By.xpath: //html/.//*[@id='emptycontent']]
10:19:19.814 INFO - Executing: [find element: By.xpath: (//html/.//*[@id='emptycontent'])[1]])
10:19:19.820 INFO - Done: [find element: By.xpath: (//html/.//*[@id='emptycontent'])[1]]
10:19:19.821 INFO - Executing: [execute script: return arguments[0].getAttribute("class"), [[[ChromeDriver: chrome on LINUX (0ea2f3d5a4207f369db8d31e6ed6a80e)] -> xpath: //html/.//*[@id='emptycontent']]]])
```

### Server configuration
**Operating system**:
Debian
**Web server:**
Apache
**Database:**
SQLite
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
10.0.3
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**Comment by phil-davis** [comment]
@individual-it please check with latest master and see if the trashbin stuff works better for you.
#29343 has been merged and should help/fix this issue.

**Comment by phil-davis** [comment]
@individual-it ping - please check if this is now fixed in master.

**Comment by individual-it** [comment]
confirming that this issue is fixed
