### ISSUE TITLE
log in with email address

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#2927]
If you put an email address in your personal profile, it should also be possible to log in with that instead of your username. This is good since people tend to forget which username they had, but rarely forget their email address. No UI change needed for now, just backend handling.

Anyone want to work on that?

**Comment by jancborchardt** [comment]
This would still be a nice feature. Anyone up for implementing it? :)

**Comment by jancborchardt** [comment]
I regularly get feedback from friends, or people I meet where their university runs ownCloud:

> Yeah, we use it, but I forgot my log in details.

This is exactly what we want to avoid and a big barrier that drives people away from using it regularly. Log in, remembering passwords, remembering usernames – no one wants to worry about that.

Your email address though you probably remember. That’s why Facebook and other major players also enable log in with email address. So we should do that to, if an address is given. And also encourage people to supply an email address because that enables password reset – and as everyone knows, people forget their passwords all the time.

cc @MTRichards @karlitschek @DeepDiver1975 requesting consideration of this for 9.1 finally.

**Comment by MTRichards** [comment]
Isn't this just a configuration issue when it is set up?

I don't understand what is missing, and what you want here.
Of course I do understand raising the priority of the email entry in the personal tab, got it.

So what are you asking for? Are you saying both a username and an email login?

**Comment by DeepDiver1975** [comment]
> Are you saying both a username and an email login should be allowed?

yes - this is the call.

**Comment by MightyCreak** [comment]
Exactly like Github is doing too ;)

![2016-01-15 14_14_42-sign in to github github](https://cloud.githubusercontent.com/assets/6382548/12362648/7beb7340-bb92-11e5-9ff2-04ba3c0120d4.png)

**Comment by PVince81** [comment]
This is done in 9.1, closing.

**Comment by MightyCreak** [comment]
\o/ Thanks!
