### ISSUE TITLE
Personal settings: CORS should not be translated

### ISSUE THREAD

**Issue by cortho** [owncloud/core#29298]
With current master when I enter Personal Settings -> Security _CORS_ is translated, see screenshot:

![oc-security-settings](https://user-images.githubusercontent.com/28009362/31770275-565be23c-b4d7-11e7-9b05-55eeff14be8c.png)

I'm not sure if this needs to be translated at all, at least the german KERNE is definitely wrong.
Additionally at least the german translation reads a little stangely

I hope this is the right repo for this issue, feel free to move, if there is a better place.

**Comment by DeepDiver1975** [comment]
Oh my god! Weiße Liste is also a bad translation for white list ....

**Comment by kraigh** [comment]
I made the small change above ^. Is this all that is necessary? First time contributor so please let me know if that is not a sufficient fix!

**Comment by mmattel** [comment]
Remembers me ages ago when ``stackpointer`` was translated to ``keller speicher zeiger`` ... 😄
