### ISSUE TITLE
stable10 integration tests taking too long

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29293]
On stable10, the last 30+ runs the integration tests are taking almost 3 hours and the timeout is set at 2 hours. However on master, the test runs usually take around one hour.

We should first investigate the diff between the stable10 tests and master to find out what and why it is taking longer. If there is no solution and if it's a test env issue, then we can increase the timeout in the Jenkinsfile.

@SergioBertolinSG do you have time to have a look ? I suggest diffing the tests/scenarios and checking the build log timestamps. Or maybe diff the logs somehow.

This is a blocker for 10.0.4 as we need to have positive test results before releasing.

**Comment by SergioBertolinSG** [comment]
The reason is this PR wasn't backported https://github.com/owncloud/core/pull/28566

It is running the whole suite three times checking encryption also.

Do we want to backport it?

With stable10 having encryption still unbundled those tests should pass, but they need time.

**Comment by PVince81** [comment]
Oh I see... forgot that... That makes sense indeed.

One worry about the seperate encryption tests is that when we do important core changes, we should rerun the CI in the encryption app to make sure everything still works. Or schedule daily builds there.

This will become relevant once we enable stable10 in the encryption repo and remove it from stable10, which is part of the unbundling task.

@DeepDiver1975 thoughts ?

**Comment by PVince81** [comment]
@SergioBertolinSG can you increase the timeout in the Jenkinsfile in the meantime ? Maybe limit this increased timeout only to the integration tests, if easily possible.

**Comment by SergioBertolinSG** [comment]
Opened this PR to address it: https://github.com/owncloud/core/pull/29294

**Comment by PVince81** [comment]
@SergioBertolinSG your PR was merged but I still see failures. Let's check again next week.

**Comment by PVince81** [comment]
@SergioBertolinSG problem still exists. I suggest splitting into three blocks:
- integration tests with no encryption
- integration tests with user-key
- integration test with master key

each would have the default timeout value and appear as three boxes in the results.

**Comment by SergioBertolinSG** [comment]
OK, I'll prepare a PR.

**Comment by SergioBertolinSG** [comment]
PR here https://github.com/owncloud/core/pull/29372
