### ISSUE TITLE
Email invitation for events should come from the user's email address, not server's [$20]

### ISSUE THREAD

**Issue by amnesiemaniac** [owncloud/core#29291]
Please reopen #25470
---------
I don't think that this is an enhancement, its a bug.
OC < v9 did not mail event invites themself and behaviour changed without notice or possibility to configure old behaviour.

**Comment by kdslkdsaldsal** [comment]
https://github.com/owncloud/core/issues/25470 is still open -> closing here

**Comment by amnesiemaniac** [comment]
yes it's open but taged as enhancement.

**Comment by kdslkdsaldsal** [comment]
@amnesiemaniac If you don't agree with the labeling of the issue https://github.com/owncloud/core/issues/25470 you can ping the one who did the labeling (github shows that with a "added the xyz label") there and explain why you think the issue should be labeled differently.

Just having another issue open about the same topic won't make things going faster or differently.

**Comment by amnesiemaniac** [comment]
I didn't know how change labeling, so I thought a Ticket would be a good idea. 
thanks
