### ISSUE TITLE
Cant disable Encryption Owncloud 10

### ISSUE THREAD

**Issue by DominicWrege** [owncloud/core#29297]
I simple cant disable the encryption. 
 
### Steps to reproduce   

```
sudo -u www-data php /var/www/owncloud/occ encryption:disable
Encryption is already disabled

But!
myuser@server:~$ sudo -u www-data php /var/www/owncloud/occ encryption:status
  - enabled: true
  - defaultModule: OC_DEFAULT_MODULE
```
<img width="561" alt="screen shot 2017-10-19 at 14 06 00" src="https://user-images.githubusercontent.com/7389000/31770228-1ec6080c-b4d7-11e7-90fd-f6bcb1dda1dd.png">

Sometimes my clients are getting this error:
```
Module with id : OC_DEFAULT_MODULE does not exist
```

### Expected behaviour
encryption should be disabled
 
### Actual behaviour
Tell us what happens instead
encryption is still enabled
### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache/2.4.18
**Database:**
postgres 9.5
**PHP version:**
php7
**ownCloud version:** (see ownCloud admin page)
version: 10.0.3.3
**Updated from an older ownCloud or fresh install:**
from 9
**Where did you install ownCloud from:**
installed with apt

**Comment by PVince81** [comment]
@sharidas can you have a look ?

**Comment by DominicWrege** [comment]
I switched to NextCloud =)

**Comment by crackhd** [comment]
To decrypt all files, you should do this:

1. Disable user access temporary, stop server ,uploads, etc.
2. Open console to your server
3. `occ maintenance:singleuser || true`
4. `occ encryption:decrypt-all [username]` for EVERY user on site
5. `occ encryption:disable` to disable encryption in Settings
