### ISSUE TITLE
[Meta] Github labels

### ISSUE THREAD

**Issue by felixboehm** [owncloud/core#29301]
Collection of labels and descriptions for ownCloud core and apps.

# Labels for all repos
- orga, organizational ticket with checklists, link collections, meta tasks, ...
- help wanted, Issue with missing know-how, contribution or time. Searching for help.
- good first issue, easy task for beginners (was junior job)

# Labels for core only
-
-

# Labels for apps only
-
-

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
