### ISSUE TITLE
Uploading a file to an external storage reports insufficient quota (new dav endpoint + OC 10.0.2)

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#29315]
### Steps to reproduce
1. Set up a user with a quota limit
2. Set up an external storage that is accessible to that user
3. Upload a file whose size is bigger than the quota set for the user to the external storage (*)

(*) Use the new dav endpoint -> http://server/remote.php/dav/files/USERNAME/

### Expected behaviour
File is uploaded to the external storage without problems. The same behaviour than the old webdav endpoint.

### Actual behaviour
Server fails with a "insufficient quota" exception

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** apache 2.4

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.2 **(to be checked with 10.0.3)**

**Updated from an older ownCloud or fresh install:** fresh install

@owncloud/qa could you check the behaviour in 10.0.3? Not sure if there has been changes regarding this. Note that the old endpoint works as expected.

**Comment by jvillafanez** [comment]
Recheked with 10.0.3. Other than an "indefined index: size" poping around, files are uploaded. Closing as fixed.

**Comment by PVince81** [comment]
@jvillafanez undefined size like this issue: https://github.com/owncloud/core/issues/29246
