### ISSUE TITLE
Group Deletion does not work and you can add users to deleted groups

### ISSUE THREAD

**Issue by Digioso** [owncloud/core#29326]
### Steps to reproduce
1. Create a new group in whatever way you like
2. Select group and delete it by clicking on the trash icon. The group vanishes from the sidebar.
3. Select a user and click on groups. The deleted group is still shown and you can add the user to this deleted group.

### Expected behaviour
A group should be completely removed and it should not be possible to add users to deleted groups.

### Actual behaviour
Users can be added to deleted groups.

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache 2
**Database:**
MariaDB
**PHP version:**
7
**ownCloud version:** (see ownCloud admin page)
10.0.3
**Updated from an older ownCloud or fresh install:**
Fresh install 10.0.2, then update to 10.0.3
**Where did you install ownCloud from:**
https://download.owncloud.org/download/repositories/10.0.3/xUbuntu_16.04/

### Client configuration
**Browser:**
Firefox 56.0.1
**Operating system:**
Windows 10 x64

**Comment by phil-davis** [comment]
Something like #29057 ?

**Comment by Digioso** [comment]
Ah, thanks. Yes, that's the same issue.
