### ISSUE TITLE
[FR] Add a switch to enable/disable token authentication enforcement

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/core#29324]
Following the discussion in https://github.com/owncloud/core/issues/29300#issuecomment-337935504 ...

> I think a switch to enable/disable this config in the Admin > User Authentication pane when OAuth2 / U2F apps are enabled would be desirable (additionally to the obscure `occ config:system:set token_auth_enforced --type boolean --value true`)

**Comment by mmattel** [comment]
@SamuAlfageme is this ticket still valid?
just asking because of the documentation ...

**Comment by SamuAlfageme** [comment]
@mmattel yup! This was all about a UI-component for the "User Authentication" settings pane to make the option more "prominent" (since many admins will not realize basic auth is still possible on clients after enabling OAuth e.g.)
