### ISSUE TITLE
Bug: Frontend for public links is "slightly off"

### ISSUE THREAD

**Issue by dercorn** [owncloud/core#29320]
When I try to get the public link for a file in oc9.1 and I click directly on the icon, I actually hit the "x" to close the side panel. In order to to get the link, I need to click below the icon, which is not very user friendly.

Please fix.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.
