### ISSUE TITLE
Trait dependencies in bootstrap

### ISSUE THREAD

**Issue by cortho** [owncloud/core#29331]
Although I have the feeling that the Behat structure is under heavy progress I'd like to add this one:

Maybe this is affecting other traits as well, I'll illustrate with Provisioning:

When I look at the Provisioning trait it is using class members that are only available in the BasicStructure trait. See currentUser https://github.com/owncloud/core/blob/fe7802e91054203fd1d3afe0fc6a5e0b9d5535a3/tests/integration/features/bootstrap/Provisioning.php#L28 which only has a declaration at https://github.com/owncloud/core/blob/fe7802e91054203fd1d3afe0fc6a5e0b9d5535a3/tests/integration/features/bootstrap/BasicStructure.php#L25

So it is not possible to use the Provisioning trait w/o using the entire BasicStructure.

Is this a bug or are there some thoughts behind?

Edit: @phil-davis @SergioBertolinSG

**Comment by phil-davis** [comment]
It's a feature ;)
When I refactored a month or so ago, I removed a loop of "use in use in use..." that actually had a circular loop of "use" (which somehow PHP had managed to cope with). I got rid of that by making a flat structure with BasicStructure at the top and all (most maybe) of the other traits being included (use) by BasicStructure. At that time I made no effort to try and remove inter-dependencies of vars/methods... between the traits.

I does need another look to see what depends on what. For now, I suspect the easiest thing to do is ``use BasicStructure`` which gives you the whole known universe. If you do not actually make use of all of it, then no big loss.

**Comment by cortho** [comment]
Thank you. I'll go on with BasicStructure then. Feel free to close this issue, if your comment doesn't imply that there will be fixes.

**Comment by phil-davis** [comment]
I have put this into backlog, technical debt. It should be looked at some day. The things that could be done are:

- [ ] make sure that each individual trait can be ``use``d by itself and will function OK independently, allowing classes to just include the traits that they want.
- [ ] look for a place to put the things currently in BasicStructure, and make an independent trait out of those.
- [ ] leave BasicStructure as a "shell" that just includes all the other traits - a way to easily get the whole lot in one go (and thus keeping compatibility with app integration tests that currently get "the lot" by using BaasicStructure.

**Comment by individual-it** [comment]
or be more radical and refactor it in a way that we don't need any traits at all

**Comment by phil-davis** [comment]
This is still current. We are in the process of removing direct ``use BasicStructure`` by app context classes. Then it will only be included by core ``FeatureContext``. At that point we can decide if we get rid of the traits completely.

**Comment by DeepDiver1975** [comment]
looks like taken care of -> close
