### ISSUE TITLE
Use POST for logout

### ISSUE THREAD

**Issue by butonic** [owncloud/core#29330]
Otherwise browsers / proxies prefetching URLs might lock users out.

see https://stackoverflow.com/a/14587231

**Comment by PVince81** [comment]
I wonder if this could also help with CSRF issues: #25927

**Comment by PVince81** [comment]
I've set this as "junior job". Please remove if you think this is more complicated due to SSO and other scenarios.

**Comment by butonic** [comment]
sso ties in because it allows to replace the content of the a tag. so ... no junior job.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `status/STALE` is set and there were no updates for 7 days. Feel free to reopen this issue if you deem it appropriate.

**Comment by DeepDiver1975** [comment]
@Peter-Prochaska this reminds me of a discussion we had - shall we change logout to POST?
If yes - please open and submit a pull request - THX
