### ISSUE TITLE
Code Integrity Check

### ISSUE THREAD

**Issue by R-yogesh** [owncloud/core#29339]
Hi,

I have disabled code integrity check by adding the following parameter in config.php 'integrity.check.disabled' => true, code integrity is successfully disabled.

Now i need to enable it again, but when i remove this line 'integrity.check.disabled' => true,
 from config.php its not enabled. How can i re-enable it.

Owncloud version - 10.0.3
web server - apache
Database - Mysql5.7
Php7.0

Please help

**Comment by kdslkdsaldsal** [comment]
@R-yogesh Please note this is a bugtracker of ownCloud. Support questions like this needs to go to https://central.owncloud.org/

Nevertheless a short hint:

The integrity check is running only once during e.g. the installation of an app or an update/upgrade so removing that line enables it again for those actions.
