### ISSUE TITLE
\OCP\Files\File->delete() without trashbin on background

### ISSUE THREAD

**Issue by pomu0326** [owncloud/core#29335]
### Steps to reproduce
1. MyAPP calls "\OCP\Files\File->delete()" on background
2. I access trashbin folder from Web UI
3. Trashbin folder does not have deleted files

### Actual behaviour
Deleted files are kept in trashbin

### Server configuration
**Operating system**:  Ubuntu 16.04

**Web server:**: Apache 2.4.10

**Database:**: MariaDB 15.1

**PHP version:**: PHP 7.0.8

**ownCloud version:** 9.0.3

**Updated from an older ownCloud or fresh install:**: No

**Where did you install ownCloud from:**: 

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

### Examples

```php
<?php
class MyApp {
  private $userManager;
  private $userSession;
  private $rootFolder;

  public function __construct(
    $userManager,
    $userSession,
    $rootFolder
  ) {
    $this->userManager = $userManager;
    $this->userSession = $userSession;
    $this->rootFolder= $rootFolder;
  }

  public function run() {
    $users = $this->userManager->search();
    foreach ($users as $user) {
      $uid - $user->getUID();
      $userFolder = $this->rootFolder->getUserFolder($uid);
      $deleteFileNode = $userFolder->get('my/delete/file/path');
      $deleteFileNode->delete();
    }
  }
}
```

**Comment by PVince81** [comment]
Likely a bug. I'd expect the owner of the file to receive it in trashbin.

**Comment by PVince81** [comment]
wait a minute, you have ownCloud 9.0.3 ? Please upgrade to at least the latest of the 9.0 series or better to 10.0.3.

**Comment by PVince81** [comment]
please reopen if still happening in 10.0.4
