### ISSUE TITLE
Add buton to clear log file

### ISSUE THREAD

**Issue by EdisAganovic** [owncloud/core#29355]
After while LOG file is huge... just add button to Clear log file. 
I don't want to waste my time to go to Cpanel/SFTP to delete log file.

**Comment by DeepDiver1975** [comment]
> After while LOG file is huge...

Please use proper log rotation settings - see https://doc.owncloud.org/server/latest/admin_manual/configuration/server/config_sample_php_parameters.html?highlight=log_rotate_size#logging

This way you can make sure that a maximum log file size is no exceeded.

I personally doubt that we will add a log delete button. We recommend ssh for sysadmin tasks.

**Comment by kdslkdsaldsal** [comment]
There is already a ``log_rotate_size`` available to rotate such logfiles and keep them smaller:

https://doc.owncloud.org/server/latest/admin_manual/configuration/server/config_sample_php_parameters.html#logging

If the logfiles are huge the reason why you get that much logging should be solved as you won't get much logging on a "normal" working production system.
