### ISSUE TITLE
Problem getting S3 primary storage to work with multibuckets

### ISSUE THREAD

**Issue by SURFsara-e-infra** [owncloud/core#29362]
### Steps to reproduce
1.Configure a multibucket S3 primary storage for openstack swift S3 endpoint
2.
3.
ps. Using the SWIFT S3 as external storage works fine. Using SWIFT S3 as primary storage in single bucket-mode works fine as well using the CEPH method.

### Expected behaviour
S3 primary storage should just work

### Actual behaviour
Get internal server error

### Server configuration
**Operating system**:
CentOS7

**Web server:**
Apache2.4.6

**Database:**
MariaDB10

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
10.0.3 enterprise

**Updated from an older ownCloud or fresh install:**
Fresh install 

**Where did you install ownCloud from:**
tar ball

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```
{
    "system": {
        "instanceid": "oco1leooohkc",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "test.data.surfsara.nl"
        ],
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/test.data.surfsara.nl",
        "logfile": "\/var\/www\/owncloud10\/data\/owncloud.log",
        "dbtype": "mysql",
        "version": "10.0.3.3",
        "dbname": "owncloud10",
        "dbhost": "145.100.5.230",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "objectstore_multibucket": {
            "class": "OCA\\ObjectStore\\S3",
            "arguments": {
                "autocreate": true,
                "options": {
                    "version": "2006-03-01",
                    "region": "",
                    "credentials": {
                        "key": "blablabla the config:list command should also put REMOVED SENSITIVE VALUE here",
                        "secret": "blablabla the config:list command should also put REMOVED SENSITIVE VALUE here"
                    },
                    "endpoint": "https:\/\/proxy.swift.surfsara.nl:443",
                    "command.params": {
                        "PathStyle": true
                    }
                }
            }
        },
    }
}
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```
Enabled:
  - admin_audit: 0.8.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.0
  - enterprise_key: 0.1.3
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firewall: 2.4.2
  - firstrunwizard: 1.1
  - market: 0.2.2
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - systemtags_management: 0.2.0
  - templateeditor: 0.1
  - theme-enterprise: 2.0.0
  - updatenotification: 0.2.1
  - windows_network_drive: 0.6.1
  - workflow: 0.2.5
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_ldap_home
  - objectstore
  - password_policy
  - sharepoint
  - theme-example
  - user_external
  - user_shibboleth
**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
firefox and chrome
**Operating system:**
ubuntu 17.10

#### Web server error log
```
Insert your webserver log here
```
No errors

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

{"reqId":"WfHKN5xCYJIoA9z@ABrzhAAAAAc","level":3,"time":"2017-10-26T11:42:48+00:00","remoteAddr":"145.100.5.231","user":"admin","app":"index","method":"GET","url":"\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/owncloud10\\\/apps\\\/objectstore\\\/lib\\\/s3.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud10\\\/lib\\\/autoloader.php(157): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/ownclo...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\ObjectStore...')\\n#2 \\\/var\\\/www\\\/owncloud10\\\/apps\\\/firewall\\\/3rdparty\\\/hoa\\\/core\\\/Consistency.php(288): spl_autoload_call('OCA\\\\\\\\ObjectStore...')\\n#3 \\\/var\\\/www\\\/owncloud10\\\/apps\\\/firewall\\\/3rdparty\\\/hoa\\\/core\\\/Consistency.php(332): Hoa\\\\Core\\\\Consistency\\\\Consistency->_import('OCA.ObjectStore...', true)\\n#4 [internal function]: Hoa\\\\Core\\\\Consistency\\\\Consistency::autoload('OCA\\\\\\\\ObjectStore...')\\n#5 \\\/var\\\/www\\\/owncloud10\\\/lib\\\/private\\\/Files\\\/Mount\\\/ObjectHomeMountProvider.php(131): spl_autoload_call('OCA\\\\\\\\ObjectStore...')\\n#6 \\\/var\\\/www\\\/owncloud10\\\/lib\\\/private\\\/Files\\\/Mount\\\/ObjectHomeMountProvider.php(57): OC\\\\Files\\\\Mount\\\\ObjectHomeMountProvider->getMultiBucketObjectStoreConfig(Object(OC\\\\User\\\\User))\\n#7 \\\/var\\\/www\\\/owncloud10\\\/lib\\\/private\\\/Files\\\/Config\\\/MountProviderCollection.php(98): OC\\\\Files\\\\Mount\\\\ObjectHomeMountProvider->getHomeMountForUser(Object(OC\\\\User\\\\User), Object(OC\\\\Files\\\\Storage\\\\StorageFactory))\\n#8 \\\/var\\\/www\\\/owncloud10\\\/lib\\\/private\\\/Files\\\/Filesystem.php(437): OC\\\\Files\\\\Config\\\\MountProviderCollection->getHomeMountForUser(Object(OC\\\\User\\\\User))\\n#9 \\\/var\\\/www\\\/owncloud10\\\/lib\\\/private\\\/Files\\\/Filesystem.php(375): OC\\\\Files\\\\Filesystem::initMountPoints('admin')\\n#10 \\\/var\\\/www\\\/owncloud10\\\/lib\\\/private\\\/legacy\\\/util.php(297): OC\\\\Files\\\\Filesystem::init('admin', '\\\/admin\\\/files')\\n#11 \\\/var\\\/www\\\/owncloud10\\\/lib\\\/base.php(927): OC_Util::setupFS()\\n#12 \\\/var\\\/www\\\/owncloud10\\\/index.php(56): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud10\\\/lib\\\/autoloader.php\",\"Line\":133}"}
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
@butonic @DeepDiver1975

**Comment by DeepDiver1975** [comment]
App objectstore is enabled?
