### ISSUE TITLE
Error upgrading from 9.1.4 to 10.0.3

### ISSUE THREAD

**Issue by martiinezz** [owncloud/core#29421]
Preparing update
Set log level to debug
Turned on maintenance mode
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_migrations` CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;': SQLSTATE[HY000]: General error: 7 Error on rename of './owncloud/oc_migrations.frm' to './owncloud/#sql2-13d5-1e83a2.frm' (Errcode: 13)

Installation via repo:
owncloud-files-9.1.4-1.1.noarch
other packages:
httpd-2.4.6-67.0.1.el7_4.6.x86_64
mod_php70u-7.0.24-1.ius.el7.x86_64
mariadb-5.5.56-2.el7.x86_64
CentOS7

**Comment by kdslkdsaldsal** [comment]
> Error on rename of './owncloud/oc_migrations.frm' to './owncloud/#sql2-13d5-1e83a2.frm' (Errcode: 13)

See https://dev.mysql.com/doc/refman/5.7/en/perror.html

When using an perror for the Errcode: 13 we can see the following:

```
perror 13
OS error code  13:  Permission denied
```

so closing here for now. The following link has some info where to get help with such issues:

https://dev.mysql.com/support/
