### ISSUE TITLE
Sabre\DAV\Exception\MethodNotAllowed: The resource you tried to create already exists

### ISSUE THREAD

**Issue by fdeitelhoff** [owncloud/core#29448]
As the title says there's many errors in my log file (see attached). As far as I can read the logs the Windows 10 or iOS Apps try to create a directory (Photos) that already exists.

The problem is, that I can see no way in resolving this. If I want to access the file list via browser I get a "connection lost" message. The Windows 10 or iOS apps are not connecting, too. I deleted the folder on the server and locally but without a connection there's no way to solve this.

What can I do on the command line for example? I deleted the file locks, trash bins, re-scanned all files and stuff like that with no effect.

Maybe someone has a hint.

[nextcloud.zip](https://github.com/owncloud/core/files/1443186/nextcloud.zip)

**Comment by kdslkdsaldsal** [comment]
> nextcloud.zip / nextcloud.log

Closing here as this is the issue tracker of ownCloud.
