### ISSUE TITLE
Use $("#id").find("class") jQuery selector instead of $("#id class")

### ISSUE THREAD

**Issue by GTT8** [owncloud/core#29451]
## Description
Selectors start with IDs ``` (# id) ```, this is a good practice: jQuery will select elements via ``` document.getElementById () ``` , which is the most efficient selector. However, selections placed after the ID should be placed in the ``` find() ``` method.

## Motivation and Context
Improvement in the jQuery code.

## Documentation
https://jsperf.com/selector-id-class-vs-class-id-vs-id-find-class
http://learn.jquery.com/performance/optimize-selectors/

## Incompatibility issues
IE8 and below=> Owncloud system requirements IE11+ (so is not a problem)

## Pull request
Currently closed until it has been correctly discussed.
#29450

**Comment by PVince81** [comment]
In general, the only cases worth optimizing are when dealing with a lot of data, for example a lot of files in the file list. I don't think we're using the wrong selectors there but would require checking.

For elements that appear only once on the page, fixing it is likely not worth the effort. (consider time to submit PR, review, backport, regression testing, etc).

**Comment by GTT8** [comment]
As far as I know this is only happening in the line I changed in the #29450 (so it's already changed, we should "only" test it.

And @PVince81 you are right, the line I changed it's not very used probably since it's a "reset password". but some of the work is already been done, so we could try it.
