### ISSUE TITLE
Conflict dialog does not close properly any more

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29459]
### Steps

1. Check out stable10 (b42b3a14cdbbc79d4466385241b9d2f0b73bab77)
1. Upload a file, wait for upload
1. Upload the same file
1. In the conflict dialog, select "New files" and confirm

### Expected result
Dialog disappears properly

### Actual result
Dialog is partially still there.

Regression introduced likely through https://github.com/owncloud/core/pull/28134

@felixheidecke please have a look, release blocker

**Comment by PVince81** [comment]
![screenshot_20171106_120239](https://user-images.githubusercontent.com/277525/32438336-63e13094-c2ea-11e7-9b5e-3a74bddde8c1.png)

**Comment by PVince81** [comment]
@phil-davis can we have a UI test for this case ?

**Comment by phil-davis** [comment]
@PVince81 - @individual-it tried to make automated file upload tests for another little app of his without joy. Currently we do not have any file upload tests - that is a missing piece of automation of the smoke tests https://github.com/owncloud/QA/blob/master/Server/Test_Plan_Simplified_Smoke_Test.md

We will try again "some time soon" (tm) but this needs to be fixed quicker than we can sort out the infrastructure for such tests.

**Comment by individual-it** [comment]
I'm currently working on tests for public link shares, but if tests for uploads are currently more important assign me and I will do them first.

**Comment by felixheidecke** [comment]
An here is the fix https://github.com/owncloud/core/pull/28134

**Comment by PVince81** [comment]
you mean here https://github.com/owncloud/core/pull/29465

**Comment by individual-it** [comment]
UI tests in #29579
