### ISSUE TITLE
Integrate with OpenCloudMesh

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29466]
https://rawgit.com/GEANT/OCM-API/v1/docs.html#

@butonic @hodyroff @pmaier1 @DeepDiver1975

**Comment by PVince81** [comment]
and @felixboehm

**Comment by butonic** [comment]
cc @tomneedham

**Comment by tomneedham** [comment]
V1 assumptions (from spec: https://github.com/GEANT/OCM-API#scope-and-assumptions )
> Authentication between services is already established. T
>Provider knows the consumer (both endpoint and user) when it creates a share with the consumer 
>Consumer doesn't have to accept a share, the resource will be available to the consumer immediately
>Dealing with incoming shares is a vendor specific implementation. 
>Reverting access to outgoing shares is a vendor specific implementation. 
>The actual file sync isn't a part of this specification.

**Comment by tomneedham** [comment]
OCM compatibility could be added here as an app and wired up to our existing sharing APIs. This way the app can be advanced as the specs change and reach maturity.

**Comment by tomneedham** [comment]
Main API routes:
 - GET /shares/{id}
 - GET /shares
 - POST /shares
 - GET /notifications/{id}
 - GET /notifications
 - POST /notifcations

**Comment by michielbdejong** [comment]
I'm looking into this now. What I see so far, is OCM from ownCloud to anything works if you use the "share with flow" (click 'sharing -> users and groups' from the context of a file).

But using what I call the "public link flow", it does not seem to work:
* create a public link, something like http://oc1.pdsinterop.net:8080/s/XZLUoeka49SgFss
* from there, the receiving user clicks 'Add to my ownCloud'
* as the button text already says, this only works if the receiving user runs ownCloud.
* it retrieves `//ocs-provider/` on the receiving server, checks the 'FEDERATED_SHARING' service there, and ends up redirecting to something like 
http://oc2.pdsinterop.net/index.php/apps/files#remote=http%3A%2F%2Foc1.pdsinterop.net%3A8080&token=XZLUoeka49SgFss&owner=admin&ownerDisplayName=admin&name=ownCloud%20Manual.pdf&protected=0
* if it can't find /ocs-provider/ then it reports 'Invalid ownCloud url // No ownCloud installation (7 or higher) found at oc2.pdsinterop.net/'
* instead, it could fall back to fetching /ocm-provider/ and continuing from there like in the "share with flow", maybe?
