### ISSUE TITLE
Error upgrading from debian package to version 7 (source)

### ISSUE THREAD

**Issue by baba75** [owncloud/core#29496]
### Steps to reproduce
1. upgrading debian to last realease will eventually uninstall package owncloud 
2. download the latest version 7 (7.0.15)
3. lauch the upgrade process

### Actual behaviour
OC\DB\MigrationException: An exception occurred while executing 'ALTER TABLE oc_oc_appconfig_d076d2707a7de ADD "appid" VARCHAR(32) DEFAULT '' NOT NULL': SQLSTATE[42701]: Duplicate column: 7 ERROR: column "appid" of relation "oc_oc_appconfig_d076d2707a7de" already exists

### Server configuration
**Operating system**: 
Debian 9.2
**Web server:**
Apache 2
**Database:**
Postgres psql (10.0, server 9.5.9)
**PHP version:**
PHP 7.0.19-1
**ownCloud version:** (see ownCloud admin page)
7.0.4.2
**Updated from an older ownCloud or fresh install:**
updating
**The content of config/config.php:**
$CONFIG = array (
  'instanceid' => 'oc69361d094b',
  'passwordsalt' => '*******',
  'secret' => '*****',
  'trusted_domains' => 
  array (
    0 => 'furia.ecobeton.it',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://furia.ecobeton.it/owncloud',
  'dbtype' => 'pgsql',
  'version' => '7.0.4.2',
  'appstoreenabled' => false,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '*********',
  'installed' => true,
  'maintenance' => false,
  'loglevel' => 2,
  'theme' => '',
);

**List of activated apps:**
Enabled:
 - activity
 - calendar
 - contacts
 - documents
 - files
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - gallery
 - search_lucene
 - templateeditor
Disabled:
 - bookmarks
 - external
 - files_encryption
 - files_external
 - updater
 - user_external
 - user_ldap
 - user_webdavauth
**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### ownCloud log (data/owncloud.log)
```
{"app":"PHP","message":"Methods with the same name as their class will not be constructors in a future version of PHP; PasswordHash has a deprecated constructor at \/var\/www\/owncloud\/3rdparty\/phpass\/PasswordHash.php#27","level":3,"time":"2017-11-07T14:30:12+00:00"}
{"app":"PHP","message":"Undefined variable: self at \/var\/www\/owncloud\/core\/command\/upgrade.php#92","level":3,"time":"2017-11-07T14:30:12+00:00"}
{"reqId":"5a01c37485a3c","app":"core","message":"Simulated database structure update failed (OC\\DB\\MigrationException: An exception occurred while executing 'ALTER TABLE oc_oc_appconfig_e2eec85cb9b7e ADD \"appid\" VARCHAR(32) DEFAULT '' NOT NULL':\n\nSQLSTATE[42701]: Duplicate column: 7 ERROR:  column \"appid\" of relation \"oc_oc_appconfig_e2eec85cb9b7e\" already exists in \/var\/www\/owncloud\/lib\/private\/db\/migrator.php:117\nStack trace:\n#0 \/var\/www\/owncloud\/lib\/private\/db\/migrator.php(75): OC\\DB\\Migrator->checkTableMigrate(Object(Doctrine\\DBAL\\Schema\\Table))\n#1 \/var\/www\/owncloud\/lib\/private\/db\/mdb2schemamanager.php(114): OC\\DB\\Migrator->checkMigrate(Object(Doctrine\\DBAL\\Schema\\Schema))\n#2 \/var\/www\/owncloud\/lib\/private\/db.php(343): OC\\DB\\MDB2SchemaManager->simulateUpdateDbFromStructure('\/var\/www\/ownclo...')\n#3 \/var\/www\/owncloud\/lib\/private\/updater.php(270): OC_DB::simulateUpdateDbFromStructure('\/var\/www\/ownclo...')\n#4 \/var\/www\/owncloud\/lib\/private\/updater.php(232): OC\\Updater->checkCoreUpgrade()\n#5 \/var\/www\/owncloud\/lib\/private\/updater.php(154): OC\\Updater->doUpgrade('7.0.15.2', '7.0.4.2')\n#6 \/var\/www\/owncloud\/core\/command\/upgrade.php(123): OC\\Updater->upgrade()\n#7 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Command\/Command.php(244): OC\\Core\\Command\\Upgrade->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#8 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Application.php(897): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#9 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Application.php(191): Symfony\\Component\\Console\\Application->doRunCommand(Object(OC\\Core\\Command\\Upgrade), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#10 \/var\/www\/owncloud\/3rdparty\/symfony\/console\/Symfony\/Component\/Console\/Application.php(121): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#11 \/var\/www\/owncloud\/console.php(46): Symfony\\Component\\Console\\Application->run()\n#12 \/var\/www\/owncloud\/occ(11): require_once('\/var\/www\/ownclo...')\n#13 {main})","level":4,"time":"2017-11-07T14:30:12+00:00","method":"--","url":"--"}
{"reqId":"5a01c37485a3c","app":"update","message":"OC\\DB\\MigrationException: An exception occurred while executing 'ALTER TABLE oc_oc_appconfig_e2eec85cb9b7e ADD \"appid\" VARCHAR(32) DEFAULT '' NOT NULL':\n\nSQLSTATE[42701]: Duplicate column: 7 ERROR:  column \"appid\" of relation \"oc_oc_appconfig_e2eec85cb9b7e\" already exists","level":4,"time":"2017-11-07T14:30:12+00:00","method":"--","url":"--"}

**Comment by kdslkdsaldsal** [comment]
Seems something similar was reported few years ago in https://github.com/owncloud/core/issues/10019

As 7.0 is [EOL](https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule) since quite some time and won't receive any bugfixes / updates you're probably on your own with this.

A sane thing you could do is:

1. Doing a backup of your data on client side (Calendar, Contacts, Files)
2. Trash your 7.0.x installation
3. Do a fresh installation of 10.0.x
4. Upload / sync the backed up data to the fresh installation from the clients

**Comment by PVince81** [comment]
or you can use the tarballs of each version: 8.0, 8.1, 8.2 and upgrade to each one by one. Once you reach 8.2.11 you can directly jump to 10.0.3.

**Comment by kdslkdsaldsal** [comment]
@PVince81 From what i understand the issue happens while manually update 7.0.4 to 7.0.15 so using each version won't work at all.
