### ISSUE TITLE
Split "Enforce password protection" option for file drop and public links

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#29526]
To fulfill the requirement of enforcing password protection for public links while not enforcing them for file drop links I suggest to split the "Enforce password protection" option into two:
a) Enforce password protection for regular public links
b) Enforce password protection for File Drop public links

Wording might not yet be perfect.

Another thing we need to take into account is the UI behavior when only one of the options is true:

Example: 
- User creates a file drop public link without password and changes permissions to a regular public link where password protection is enforced. At that point saving needs to be blocked unless a (policy-matching) password is entered. This of course needs to work the other way round as well
- What if I have a password protection enforced public link and change permissions to a not password protection enforced file drop public link? Password will be kept but can be removed by the user!?

I hope there are no implications I might have missed.

@PVince81

**Comment by pmaier1** [comment]
Actually I don't really see a need for password-protecting File Drop links so we could also just exclude them in order not to clutter config options even more. I would make it dependent on effort.

**Comment by PVince81** [comment]
@pmaier1 some people might feel safer if there is a password to File Drop links in case the link gets leaked and people would spam the folder. This, assuming that the password was shared using different channels. Probably a rare case...

**Comment by felixboehm** [comment]
@jvillafanez please contact @felixheidecke if any frontend help needed.

**Comment by PVince81** [comment]
I think currently we trigger an event when password policy check needs to apply. We might want to add a "scope" or "context" attribute there to let password policy apps find out in what context the password will be used.

**Comment by jvillafanez** [comment]
I'll need some clarifications...

![screen shot 2018-01-12 at 15 34 44](https://user-images.githubusercontent.com/1477829/34879647-35a48d72-f7ae-11e7-91f1-f49b67043040.png)

That sharing part, is it controlled by the files_sharing app or by core? If it's controlled by the files_sharing app, we should clarify that the password protection there is just for the files_sharing app and not for any other.

I expect the files_drop app has a similar checkbox in its own configuration panel.

My point is that core doesn't enforce anything, it's each app which does it, and each app has different ways to enforce password protection. If this is true, we can just adjust the text there for the files_sharing and duplicate the functionality (more or less) for files_drop.

**Comment by PVince81** [comment]
@jvillafanez files_drop app is dead. When we talk about it we mostly mean its replacement: go to the link share creation dialog and choose "upload only" mode. In upload only mode, one should be able to disable password enforcement as often times passwords for upload only don't make much sense as there is no data you can access.

**Comment by PVince81** [comment]
so all this is either in core or files_sharing, depending where the current code actually lives

**Comment by pmaier1** [comment]
> Shouldn't we add a switch per permissions mode (read-only, read & write, write only)?

Not necessary, I think.

Should be perfectly fine if we display another checkbox below (default: true) when "Enforce password protection" is enabled: "Exclude Upload only (File Drop) links"

**Comment by felixheidecke** [comment]
To complete the whole thing why don't we do this instead:

- [ ] Enforce password for read-only
- [ ] Enforce password for read & write
- [ ] Enforce password for File drop

**Comment by pmaier1** [comment]
> To complete the whole thing why don't we do this instead:

@jvillafanez suggested the same above. It's a trade-off between configurability vs. cluttering settings / losing overview. I don't think this granularity is necessary but would leave it up to you to decide on proper design/UX. The basic request is only this: Enforce password protection for public links but not for File Drop.

**Comment by pmaier1** [comment]
Thanks for explanation @jvillafanez. Let's work in iterative MVP-style and keep effort low.

**Comment by felixheidecke** [comment]
Maybe this granularity isn't needed. So we can just do regular and drop links. Fine with me :-)

**Comment by PVince81** [comment]
10.0.6 is a hotfix release for 10.0.5. This is scheduled for 10.0.7, so blocker for 10.0.7... it's already p1

**Comment by jvillafanez** [comment]
PR in https://github.com/owncloud/core/pull/30168 in case someone missed it

**Comment by pmaier1** [comment]
Nice job! I'll close here then.

**Comment by PVince81** [comment]
@jvillafanez please adjust to only show "regular" and "drop" checkboxes

cc @pmaier1 please correct if misunderstood

**Comment by pmaier1** [comment]
![split_enforce_pw_prot](https://user-images.githubusercontent.com/21193500/37352787-50a1a4ca-26de-11e8-8a6c-d6760ae77bf4.png)

Hmm, I thought about it again and think it's not bad to have three options though I don't really see a use case in differentiating between "read only" and "read & write". But we should stay consistent in wording. In public link share dialog the last one is called "Upload only (File Drop)".

I suggest the following:

Enforce password protection for _Read only_ links
Enforce password protection for _Read & Write_ links
Enforce password protection for _Upload only (File Drop)_ links

**Comment by jvillafanez** [comment]
Wording change in https://github.com/owncloud/core/pull/30773
Backport to stable10 in https://github.com/owncloud/core/pull/30774
