### ISSUE TITLE
adding Script code to direct download

### ISSUE THREAD

**Issue by jazuly** [owncloud/core#29528]
hi, how if i want to add a script like this to direct download page

<script type="text/javascript" src="https://cdn.rawgit.com/jazuly/aidorama/eb5f9904/safelink-3-multi.js"></script>
<script type="text/javascript">
protected_links = ""; 
auto_safelink();
</script>

i want co convert original direct download to base64 encode

**Comment by kdslkdsaldsal** [comment]
Please note that this is a bugtracker for ownCloud. Support / development specific questions needs to go to https://central.owncloud.org/
