### ISSUE TITLE
Create folder for each upload session

### ISSUE THREAD

**Issue by Gallenkamp** [owncloud/core#29537]
Feature request, not a bug

### Steps to reproduce
1. Create a folder
2. Share this folder to the public, include write permissions
3. Upload some files in different sessions

### Expected behaviour
If an anonymous uploads data to the server via provided writable folder (to public), a file from a new session shouls create a new folder. So each files fro different upload sessions are stored separated.

### Actual behaviour
All files are stored into the same folder

### Server configuration

**ownCloud version:** (see ownCloud admin page)
10.0.3.3

**Updated from an older ownCloud or fresh install:**
Upgraded from 10.0.1

**Comment by Gallenkamp** [comment]
Why this?

I am organising the members magazine for my sports club. Reports on races (running) come via email (or 5 in a row to 5 recipients) in various versions. I'd like to make it easier for everyone to send photos and reports.

Easiest way to separate the different uploads is by their browser session.

**Comment by kdslkdsaldsal** [comment]
Looks like a very special / edge use case which could perfectly fit into an app. 

You can find some documentation on how to write such an app at e.g. https://doc.owncloud.org/server/latest/developer_manual/app/

**Comment by PVince81** [comment]
@Gallenkamp there is a way you could achieve a similar result, depending about the recipients:

- share folder "uploads" with link, read-only, with everyone
- for each recipient, create a folder "uploads/recipient_name" and share that folder with only one of the recipient with read-write permissions

Basically you create a link share for each recipient where they can upload their files.
The master share "uploads" is only if they want to be able to also access files from other uploaders.

Would that work for you ?

cc @pmaier1

**Comment by Gallenkamp** [comment]
@PVince81 This is a different approach.
I dont know how many upload sessions I will get. This is dependant on how many people write articles for our members magazine.

**Comment by PVince81** [comment]
Special use case which will likely not be implemented as part of core sharing => to be implemented by someone as an app.

If any APIs are missing to achieve, tickets can be opened to add such in core.

cc @pmaier1
