### ISSUE TITLE
Updater does not check for compatible PHP version

### ISSUE THREAD

**Issue by Herbstlaub** [owncloud/core#29538]
### Steps to reproduce
1. Use the Updater to update from OC 9.1.6  to 10.0.3 given that PHP 5.4.45-0+deb7u11 is installed

### Expected behaviour

The updater should not update if dependencies are not met. 

### Actual behaviour

Update results in "finishing update" -> "undefined" 

Installation is broken: "This version of ownCloud requires at least PHP 5.6.0
You are currently running 5.4.45-0+deb7u11. Please update your PHP version."

### Server configuration
**Operating system**:

Linux xxx 3.2.0-4-amd64 #1 SMP Debian 3.2.89-2 x86_64 GNU/Linux

**Web server:**

Server version: Apache/2.2.22 (Debian)
Server built:   Jul 29 2017 16:41:02

**Database:**

mysql  Ver 14.14 Distrib 5.5.57, for debian-linux-gnu (x86_64) 

**PHP version:**

5.4.45-0+deb7u11

**ownCloud version:** (see ownCloud admin page)

update from OC 9.1.6  to 10.0.3

**Updated from an older ownCloud or fresh install:**

Updater failed

**Where did you install ownCloud from:**

Oringinally from the web page

**Signing status (ownCloud 9.0 and above):**

Owncloud is broken, no admin page anymore. :(

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'someid',
  'passwordsalt' => 'somesalt',
  'secret' => 'somesectre',
  'trusted_domains' => 
  array (
    0 => 'mydomain.de',
    1 => 'www.mydomain.de',
  ),
  'datadirectory' => '/data/dir',
  'overwrite.cli.url' => 'http://mydomain.de/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.6.2',
  'dbname' => 'db_name,
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'user_owncloud',
  'dbpassword' => 'mypassword',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'updater.secret' => 'somesecret',
);

**List of activated apps:**

Owncloud is broken, no admin page anymore. :(

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

### Client configuration
**Browser:**

Problen is not related to browser.

**Operating system:**

Problen is not related to browser.

#### Web server error log

no access, at the  moment

#### ownCloud log (data/owncloud.log)

Last entry long before update.

**Comment by kdslkdsaldsal** [comment]
The repository / issue tracker of the Updater app lives in https://github.com/owncloud/updater/issues where you can find an open issue about that at https://github.com/owncloud/updater/issues/356

If you need some support how to recover your instance you can jump over to http://central.owncloud.org/ (you can login with your github account there).
