### ISSUE TITLE
Ability for admins to terminate other user's sessions

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29548]
Requires https://github.com/owncloud/core/pull/24675.

Then add an occ command and maybe web UI where the user can search for users and their sessions for termination.

From what I see, this was the phase 2 of pluggable auth but the ticket got closed.

See https://github.com/owncloud/core/issues/23458#issuecomment-219954679 for details.

@pmaier1 @DeepDiver1975 @butonic @sharidas

**Comment by mmattel** [comment]
Just FYI: https://github.com/owncloud/ios/issues/956 (Basic auth cookie handling)
