### ISSUE TITLE
[FR] OCC command to trigger a password reset email

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#29542]
Something like `occ user:resetpassword --via-email <uid>` which would use the lost password feature to email a link to the user to reset their account. Account access is blocked until this is used. 

Useful for onboarding / provisioning accounts where you do not want to send the password over email.

**Comment by PVince81** [comment]
Additionally, should also output the URL on the CLI.

- [ ] add `--via-email` argument and send link for password reset and output the link on the CLI
- [ ] add `--via-link` argument and output the link on the CLI
- [ ] if no arg provided, default to the current behavior which asks a password on the CLI

@pmaier1 @tomneedham @sharidas

**Comment by sharidas** [comment]
Fixes https://github.com/owncloud/core/pull/32345
