### ISSUE TITLE
sanity check for user sync

### ISSUE THREAD

**Issue by butonic** [owncloud/core#29547]
During user sync
> Is there a sanity check prohibiting that all users
are deleted, if they all vanished from LDAP? Experiences from identity
management say that there should be a check if more than 10% or so
should be deleted. If yes, stop the whole operation.

**Comment by pmaier1** [comment]
Important point, yes! Is this really a core issue or should it be tracked in user_ldap?
Invoking @PVince81

**Comment by butonic** [comment]
sync is part of core
