### ISSUE TITLE
Upgrade 8.2.11 fail (via web updater) / Can use ./occ (permission denied)

### ISSUE THREAD

**Issue by Alf34** [owncloud/core#29541]
Hi all,

First time here, please be kind :-)

Try to update Owncloud to 8.2.11 but crash : 
OVH hosted
PHP 5.6
MySQL 5.5

First try with update app on web admin. No luck
Try to ./occ via ssh but now i'm in "permission denied" (maybe rw_r__r__ is not good - date changed today)

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_oc_filecache_mf58u3ozli1vd` SELECT * FROM `oc_filecache`': SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query

Thanks a lot for help !

**Comment by kdslkdsaldsal** [comment]
Please note this is a bugtracker for ownCloud. The permission and MySQL errors are support-questions which belongs to e.g. https://central.owncloud.org/ (you can login with your github account there).

Nevertheless two short hints:

1. Yes, rw r r is not good as the script needs to be executable (x)
2. Search on your favorite search engine for the "Lost connection to MySQL server during query" and pass this issue to the support of your hoster
