### ISSUE TITLE
PHP Parse error in cron.php on line 79

### ISSUE THREAD

**Issue by sp1ne** [owncloud/core#29588]
PHP Parse error:  syntax error, unexpected '[', expecting ')' in /owncloud/cron.php on line 79

Line 79:
OC_JSON::error(['data' => ['message' => 'Background jobs disabled!']]);

PHP 7.1

**Comment by DeepDiver1975** [comment]
this error is generated if using php 5.3

please make sure php 5.6 at least is used

proof:

http://sandbox.onlinephpfunctions.com/code/f24227b74dd00916a98c89bb199b4d474a7f9ef7

![bildschirmfoto von 2017-11-15 16-47-04](https://user-images.githubusercontent.com/1005065/32845315-b7b6b63a-ca24-11e7-92f2-4c984b1af122.png)
