### ISSUE TITLE
Log message not properly interpolated

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#29591]
### Steps to reproduce
Followed steps described in https://github.com/owncloud/core/issues/26357

### Expected behaviour
Error message is properly shown

### Actual behaviour
```
{"reqId":"1BrFFMI2ShXoZoZB4Iw3","level":2,"time":"2017-11-15T17:27:41+00:00","remoteAddr":"10.0.2.4","user":"user2","app":"dav","method":"MOVE","url":"\/remote.php\/webdav\/sub","message":"Could not get node for path: \"sub\" : {$message}"}
```
Note the "$message"

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.4RC1

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** tarball

**Comment by tomneedham** [comment]
fixed with https://github.com/owncloud/core/commit/3284e6dd72528f16b1a6e45f13e310ff4ff2de2e
