### ISSUE TITLE
Setup check for non-default / incompatible CSP (blank file page / files app)

### ISSUE THREAD

**Issue by ghost** [owncloud/core#29596]
As shown in https://github.com/owncloud/core/issues/29589 the files page / files app stays blank if e.g. unsafe-eval is disallowed (probably on webserver level behind ownClouds back?) within the CSP.

It could make sense to introduce a setup check for such an non-default / incompatible CSP.

**Comment by PVince81** [comment]
I'm starting to get a feeling that this setup check is becoming a project on its own. Seems so much can go wrong in some envs.

**Comment by kdslkdsaldsal** [comment]
Yes, unfortunately there are so many ways to break ownCloud with non-default settings / configurations within an environment / webserver but still many are just pointing at ownCloud to be broken.
