### ISSUE TITLE
Dropbox Storage: Configuring OAuth1 fails

### ISSUE THREAD

**Issue by frantsch** [owncloud/core#29595]
### Steps to reproduce
1. Create a Dropbox-App giving me App Key and App Secret for OAuth1
2. Calling Owncloud Settings - External Storage
3. Try to add storage type Dropbox and enter Name, App Key and App Secret for OAuth1, and User
3. Obtaining an _Error configuring OAuth: Call of Request-Token failed._

### Expected behaviour
Integration of Dropbox Storage is established

### Actual behaviour
Integration fo Dropbox Storage fails, although I am sure to use the correct Key and Secret

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache

**Database:**
SQLute

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
10.0.3.3

**Updated from an older ownCloud or fresh install:**
fresh

**Where did you install ownCloud from:**
Download from owncloud.org

**Comment by PVince81** [comment]
Dropbox itself doesn't support OAuth1 any more, see https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

Please use the new app that uses the new APIs: https://marketplace.owncloud.com/apps/files_external_dropbox

The old Dropbox code will be removed in 10.0.5 so people won't bump into this issue any more.

**Comment by frantsch** [comment]
Sorry, PVince81, I did use the new app https://marketplace.owncloud.com/apps/files_external_dropbox
I experience that this app does use OAuth2, however it is not able to connect!

**Comment by PVince81** [comment]
please report in the app repo then and make sure you are using the latest version of everything (OC 10.0.3 and latest dropbox app version), thanks

**Comment by frantsch** [comment]
"please report in the app repo...": which is?

**Comment by PVince81** [comment]
Ah yes, sorry. The link I gave you was marketplace.

The repo is here https://github.com/owncloud/files_external_dropbox/

**Comment by kdslkdsaldsal** [comment]
Ref: https://github.com/owncloud/files_external_dropbox/issues/18
