### ISSUE TITLE
Add fileid to file related hook params

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29604]
Add fileid to all hook formats related to file id where usually a path is given.

Will be useful for app developers because sometimes having the fileid is quicker and doesn't require one to re-resolve the fileid from the path which can be expensive. Since the hook trigger already has it, it can simply pass it.

Even better would be the FileInfo if we have it.

@sharidas I'll let you have a look at all file related hooks and evaluate whether FileInfo or just fileid is better, considering that we want consistency across hooks.

**Comment by sharidas** [comment]
From first glance, i am getting a feel that we can have FileInfo: https://github.com/owncloud/core/pull/29510/files#diff-be504dc886734275f06114e4306fa215R308

**Comment by PVince81** [comment]
IFileInfo is the best we can have since it contains a lot of info and is future proof. Go for it 😄

**Comment by PVince81** [comment]
Note that we've attempted to do so in the PR (@sharidas link please) and found out that it would be more expensive to resolve the file id or file info before every hook trigger. So we settled on still passing the path as before and letting the listener resolve the file id on-demand.

**Comment by sharidas** [comment]
> Note that we've attempted to do so in the PR (@sharidas link please) and found out that it would be more 

PR: https://github.com/owncloud/core/pull/29651

**Comment by sharidas** [comment]
PR's which helped us to accomplish the task: 
- https://github.com/owncloud/core/pull/29651
