### ISSUE TITLE
Transfer ownership trashbin

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29608]
Currently transfer ownership doesn't transfer trashbin files.

When transferring, we should create a subfolder in the target user's trashbin using the same naming scheme. Then put all trashed files there.

This only applies when not using the `--path` option.

Some challenges: as we know, the trashbin has background jobs to automatically discard older entries when space is getting low. (less than 50% of the storage space). So when transferring the trashbin of one user to another, it could reach such threshold and cause files to be cleared more quickly in some situations. Retention rules could also affect such files to some extent.

I currently don't see a way around this, so this should at most be a documented limitation. An admin could make sure that there is enough storage space before doing the transfer.

@pmaier1 @DeepDiver1975 @sharidas

**Comment by PVince81** [comment]
From what I see we'd also need to process the "oc_files_trash" Table:
```
MariaDB [owncloud]> select * from oc_files_trash;
+---------+-------------+-------+------------+----------+------+------+
| auto_id | id          | user  | timestamp  | location | type | mime |
+---------+-------------+-------+------------+----------+------+------+
|       1 | welcome.txt | admin | 1510916649 | sub      | NULL | NULL |
+---------+-------------+-------+------------+----------+------+------+
```

From what I see it doesn't contain any file id. From what I remember it might map to oc_filecache by concatenating the id with the timestamp. In the example above the file to restore would be "welcome.txt.d1510916649". So if the user "admin" restores a file called that, it will look into this table to check the "location" where to restore. If the location doesn't exist, it will restore to the root folder of the user's storage.

Transferring this could become tricky. The reason is that the location might be called differently in a scenario where a file was deleted from a received share and transferred to another user who has the same share but with a different name (you can rename received shares) or maybe the transfer receiver doesn't even have access to the same folder.

As a shortcut, the transfer code could simply delete these entries. This would cause any restore operation of said files to go to the root of the owner.

Or another alternative, have these be restored into the "/transferred from XYZ" folder in a matching subfolder. However if the subfolder was a received one, it isn't transferred (we don't transfer received shares), so it would go to the root.

In general, if there isn't much benefit to restoration accuracy, we should go with the simplest solution and discard the restore information.

**Comment by DeepDiver1975** [comment]
I suggest to wait for the public api for trashbin as well
