### ISSUE TITLE
Unable to upload 6GB file to Owncloud with S3/Swift primary storage backend

### ISSUE THREAD

**Issue by SURFsara-e-infra** [owncloud/core#29618]
### Steps to reproduce
1. Just install OC using S3 (on Openstack Swift) as primary storage backend
2. Upload a 6GB file using curl via WebDAV
3.

### Expected behaviour
File should be uploaded

### Actual behaviour
Sabredav returns the error message "Your proposed upload exceeds the maximum allowed object size."
Like other object storage systems, SWIFT has an object upload limit of 5GB. For obects larger than this limit, the object has to be uploaded in a multipart upload where the object is uploaded in chunks. 
I think that this is not implemented yet.

### Server configuration
**Operating system**:
CentOS 7.3.1611
**Web server:**
apache 2.4.6
**Database:**
mariadb-5.5
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
10.0.3 enterprise
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
tarball
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No errors have been found.

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```
{
    "system": {
        "instanceid": "oco1leooohkc",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "test.data.surfsara.nl"
        ],
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/test.data.surfsara.nl",
        "overwritehost": "test.data.surfsara.nl",
        "overwriteprotocol": "https",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR",
            "HTTP_FORWARDED_FOR"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "145.100.5.230",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "filelocking.enabled": "true",
        "trusted_proxies": [
            "145.100.5.230"
        ],
        "logfile": "\/var\/www\/owncloud10\/data\/owncloud.log",
        "dbtype": "mysql",
        "version": "10.0.3.3",
        "dbname": "owncloud10",
        "dbhost": "145.100.5.230",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "objectstore_multibucket": {
            "class": "OCA\\ObjectStore\\S3",
            "arguments": {
                "autocreate": true,
                "options": {
                    "version": "2006-03-01",
                    "region": "",
                    "credentials": {
                        "key": "***REMOVED SENSITIVE VALUE***",
                        "secret": "***REMOVED SENSITIVE VALUE***"
                    },
                    "endpoint": "https:\/\/proxy.swift.surfsara.nl:443",
                    "command.params": {
                        "PathStyle": true
                    }
                }
            }
        }
    }
}

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```
Enabled:
  - admin_audit: 0.8.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.0
  - enterprise_key: 0.1.3
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firewall: 2.4.2
  - firstrunwizard: 1.1
  - market: 0.2.2
  - notifications: 0.3.1
  - objectstore: 0.4
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - systemtags_management: 0.2.0
  - templateeditor: 0.1
  - theme-enterprise: 2.0.0
  - updatenotification: 0.2.1
  - windows_network_drive: 0.6.1
  - workflow: 0.2.5
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_ldap_home
  - guests
  - password_policy
  - sharepoint
  - theme-example
  - user_external
  - user_shibboleth
**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
firefox
**Operating system:**
centos7
#### Web server error log
```
Insert your webserver log here
```
Nothing relevant
#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
Exception: {\"Message\":\"HTTP\\\/1.1 500 Your proposed upload exceeds the maximum allowed object size.\",\"Exception\
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
@DeepDiver1975 @butonic

**Comment by DeepDiver1975** [comment]
We are working on a new s3 implementation which will not suffer from this limitation
https://github.com/owncloud/files_primary_s3

**Comment by PVince81** [comment]
and from what I heard will come with many improvements like the ability to upload the OC chunks with multipart to the object store ?

**Comment by PVince81** [comment]
@DeepDiver1975 link so we can close ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 link so we can close ?

yes

**Comment by SURFsara-e-infra** [comment]
Hi Thomas,

When will the fix be available?

Cheers,

Ron

**Comment by DeepDiver1975** [comment]
For 9.1 the next (and last release will hold these changes - currently being in QA).
For 10.0 we have the app in QA as well in parallel and it should arrive in the marketplace right afterwards.

@patrickjahns FYI

**Comment by patrickjahns** [comment]
👍
