### ISSUE TITLE
owncloaud update to 10

### ISSUE THREAD

**Issue by bart886** [owncloud/core#29624]
Hello. 
Debian 9.
I uninstall owncloud 9. 
Update repositories.
Install owncloud 10 "aptitude install  owncloud-files"
If i go to https://myip/owncloud i see 404 not found.
Help.

**Comment by kdslkdsaldsal** [comment]
@bart886 Please note this is a bugtracker of ownCloud. Support questions like this needs to go to https://central.owncloud.org/ (you can login with your github account there).

Nevertheless a short hint:

You probably are missing the Apache vhost configuration as pointed out here: https://doc.owncloud.org/server/latest/admin_manual/installation/source_installation.html#configure-apache-web-server

**Comment by bart886** [comment]
Ok thanks
