### ISSUE TITLE
Template resource locator troubles when app code exists twice

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29628]
### Steps

1. Setup ownCloud with two apps folders "apps" and "apps2"
1. Install "customgroups" app version 0.3.1 into "apps"
1. Install "customgroups" app version 0.3.5 into "apps2"
1. `occ app:enable customgroups`
1. Go to the "Custom groups" sections in the settings page
1. Inspect the customgroups "section" element

### Expected result
Section element looks like this: `<div id="customgroups" class="section" data-cancreategroups="true">`

### Actual result
Section element looks like this: `<div id="customgroups" class="section">`.

If you check the template file "customgroups/templates/index.php" you can see that the additional bit `data-cancreategroups` exists in the 0.3.5 template but not 0.3.1.
It looks like ownCloud is running the 0.3.5 version app but loads the template from 0.3.1. And who knows if it's not loading other resources from there, to be checked!

You can also run the unit tests with `make test-php` inside the 0.3.5 version, the output shows the same problem:
```
1) OCA\CustomGroups\Tests\unit\SettingsPanelTest::testGetPanel
Failed asserting that '
<div id="customgroups" class="section"></div>
' contains "<div id="customgroups" class="section" data-cancreategroups="true"></div>".

/srv/www/htdocs/owncloud/apps3/customgroups/tests/unit/SettingsPanelTest.php:50
/srv/www/htdocs/owncloud/apps3/customgroups/lib/composer/phpunit/phpunit/src/TextUI/Command.php:188
/srv/www/htdocs/owncloud/apps3/customgroups/lib/composer/phpunit/phpunit/src/TextUI/Command.php:118

2) OCA\CustomGroups\Tests\unit\SettingsPanelTest::testGetPanelNoCreatePerm
Failed asserting that '
<div id="customgroups" class="section"></div>
' contains "<div id="customgroups" class="section" data-cancreategroups="false"></div>".
```

**Comment by VicDeo** [comment]
@PVince81 https://github.com/owncloud/core/pull/29747 partially fixes that (for templates)

**Comment by VicDeo** [comment]
hm. I can see `<div id="customgroups" class="section" data-cancreategroups="true">` in WebUI  but CLI test still fails
