### ISSUE TITLE
Clients seem to be constantly "Checking for changes" on MacOS

### ISSUE THREAD

**Issue by stevenmcastano** [owncloud/core#29623]
I've got a few computers, 2 windows machines, 1 Windows 2008 server, the other Windows 10 Enterprise, and 2 Macs, a Macbook Pro and a Mac Pro both running Sierra and all of my clients seem to almost constantly be "Checking for changes".

Even when no files have change, nor should any be changing, it seems to check for changes, almost once every few seconds, maybe 2 or 3. All of my clients are almost always in this state:

![screen shot 2017-11-19 at 6 49 37 pm](https://user-images.githubusercontent.com/6171444/32997272-7f3a29c4-cd5b-11e7-887e-c1708e14fb57.png)

Then it seems in the logs, at times I get the following 2 errors frequently:

 > {"reqId":"18PaYi9h9sLs5eR9JqpE","level":3,"time":"2017-11-19T23:49:05+00:00","remoteAddr":"","user":"--","app":"files","method":"--","url":"--","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `oc_filecache` SET `mtime` = ?, `etag` = ?, `storage_mtime` = ?, `permissions` = ?, `checksum`=? WHERE (`mtime` <> ? OR `etag` <> ? OR `storage_mtime` <> ? OR `permissions` <> ? OR `checksum` <> ? OR `mtime` IS NULL OR `etag` IS NULL OR `storage_mtime` IS NULL OR `permissions` IS NULL OR `checksum` IS NULL) AND `fileid` = ? ' with params [1511125294, \\\"5a12183ed11a5\\\", 1511125294, 31, \\\"\\\", 1511125294, \\\"5a12183ed11a5\\\", 1511125294, 31, \\\"\\\", 397015]:\\n\\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `oc_file...', Array)\\n#2 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(190): Doctrine\\\\DBAL\\\\Connection->executeQuery('UPDATE `oc_file...', Array, Array, NULL)\\n#3 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Cache.php(312): OC\\\\DB\\\\Connection->executeQuery('UPDATE `oc_file...', Array)\\n#4 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Wrapper\\\/CacheWrapper.php(134): OC\\\\Files\\\\Cache\\\\Cache->update(397015, Array)\\n#5 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(268): OC\\\\Files\\\\Cache\\\\Wrapper\\\\CacheWrapper->update(397015, Array)\\n#6 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(211): OC\\\\Files\\\\Cache\\\\Scanner->addToCache('FamilyScanProje...', Array, 397015)\\n#7 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(314): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('FamilyScanProje...', 3, '396659', Object(OC\\\\Files\\\\Cache\\\\CacheEntry), true)\\n#8 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(489): OC\\\\Files\\\\Cache\\\\Scanner->scan('FamilyScanProje...', 2, 3)\\n#9 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(500): OC\\\\Files\\\\Cache\\\\Scanner->OC\\\\Files\\\\Cache\\\\{closure}()\\n#10 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(490): OC\\\\Files\\\\Cache\\\\Scanner->runBackgroundScanJob(Object(Closure), 'FamilyScanProje...')\\n#11 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(173): OC\\\\Files\\\\Cache\\\\Scanner->backgroundScan()\\n#12 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#13 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#14 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(57): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#15 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#16 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/cron.php(121): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#17 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}"}

and

> {"reqId":"dZvPuekyRzlqSisCX4Qq","level":4,"time":"2017-11-19T23:56:06+00:00","remoteAddr":"96.241.22.33","user":"steve","app":"webdav","method":"PROPFIND","url":"\/remote.php\/dav\/files\/steve\/lightroomcatalogs\/FamilyScanProject\/LRCatalog%20Previews.lrdata\/0\/0000","message":"Exception: {\"Message\":\"An exception occurred while executing 'UPDATE `oc_filecache` SET `size`=? WHERE (`size` <> ? OR `size` IS NULL) AND `fileid` = ? ' with params [1141744, 1141744, \\\"396661\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `oc_file...', Array)\\n#2 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(190): Doctrine\\\\DBAL\\\\Connection->executeQuery('UPDATE `oc_file...', Array, Array, NULL)\\n#3 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Cache.php(312): OC\\\\DB\\\\Connection->executeQuery('UPDATE `oc_file...', Array)\\n#4 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Wrapper\\\/CacheWrapper.php(134): OC\\\\Files\\\\Cache\\\\Cache->update('396661', Array)\\n#5 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(393): OC\\\\Files\\\\Cache\\\\Wrapper\\\\CacheWrapper->update('396661', Array)\\n#6 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(316): OC\\\\Files\\\\Cache\\\\Scanner->scanChildren('FamilyScanProje...', false, 3, '396661', true)\\n#7 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Watcher.php(104): OC\\\\Files\\\\Cache\\\\Scanner->scan('FamilyScanProje...', false)\\n#8 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1307): OC\\\\Files\\\\Cache\\\\Watcher->update('FamilyScanProje...', Object(OC\\\\Files\\\\Cache\\\\CacheEntry))\\n#9 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1403): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\Files_Trashbin\\\\Storage), 'FamilyScanProje...', '\\\/lightroomcatal...')\\n#10 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(276): OC\\\\Files\\\\View->getDirectoryContent('\\\/lightroomcatal...')\\n#11 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(195): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->getChildren()\\n#12 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(896): Sabre\\\\DAV\\\\Tree->getChildren('files\\\/steve\\\/lig...')\\n#13 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(977): Sabre\\\\DAV\\\\Server->generatePathNodes(Object(Sabre\\\\DAV\\\\PropFind), Array)\\n#14 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1665): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('files\\\/steve\\\/lig...', Array, 1)\\n#15 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#16 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#18 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#19 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#20 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(234): Sabre\\\\DAV\\\\Server->exec()\\n#21 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#22 \\\/usr\\\/share\\\/nginx\\\/owncloud\\\/remote.php(165): require_once('\\\/usr\\\/share\\\/ngin...')\\n#23 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115,\"User\":\"steve\"}"}

### Expected behaviour
I would think the clients might check into the server and only do this full scan when something has changed, or something unknown has happened. I don't remember the server behaving this way in the past and I'm working if something got broken during and upgrade or server rebuild.

### Server configuration
The server is running on  running OwnCloud 10.0.3.3 with php7.0-fpm behind nginx 1.12.1 as a reverse proxy with SSL.

**Operating system**: Ubuntu 16.04.3 on an Amazon EC2 t2.medium instance
**Web server**: Nginx 1.12.1 with SSL
**Database**: Amazon RDS running MariaDB 10.1.z
**PHP version**: 7.0.25 (php7.0-fpm)
**ownCloud version**: 10.0.3.3
**Updated from an older ownCloud or fresh install**: Updated multiple times from much older versions, then rebuilt and moved to a new server for the OwnCloud X release
**Where did you install ownCloud from**: owncloud.org
**Signing status (ownCloud 9.0 and above)**:

```
OwnCloud setting integrity test:
No errors have been found.
```

**Comment by kdslkdsaldsal** [comment]
Have you tried searching on the net for those messages:

``General error: 1205 Lock wait timeout exceeded; try restarting transaction``

Might be possible that the MySQL database on the new host are using different / too low limits then your old host.

**Comment by ownclouders** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 14 days. Feel free to reopen this issue if you deem it appropriate.
