### ISSUE TITLE
Test Results for Smoke test 9.1.7.RC1

### ISSUE THREAD

**Issue by davitol** [owncloud/core#29633]
# Smoke test

## Previous requirements

Prepare two servers with ssl activated and trusted certificates.

Enable LDAP and external storage apps.

Have a LDAP server ready to be used with owncloud.

Have ready two external storages of your choice SMB, SFTP, Dropbox, Google Drive, FTP, S3, ownCloud, local.

## Testing setup

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Enable encryption app and encryption default module | Encryption is enabled correctly | ✅   |
2 | Populate owncloud server with users and groups | Users and groups are correctly created | ✅   |
3 | Share a folder remotely using federated sharing with admin user of the other server. | folder can be opened in recipient server without problems | ✅   |
4 | Set up LDAP, as admin check users. log in with a LDAP user, if possible one with an avatar. | Users are loaded. LDAP user logs in without problems. Avatar is shown if it exists.  | ✅   |
5 | Set up two external storages different, disable encryption in one of them.| No errors in this process | ✅   |

## Testing functionality

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Share a file using federated sharing from an external unencrypted external storage in server #1 using a LDAP user to the admin user in server #2. | Admin user in server #2 can see the file. | ✅   | 
2 | Open internet explorer or edge and upload a new avatar for a regular user not LDAP | Interface can be used, avatar is uploaded, check that personal page has a scroll bar and scrolls fine. | ✅   | 
3 | Upload several files and folders inside external storages, open some. | No problems uploading, files can be downloaded and opened. | ✅   |
4 | Delete files inside both external storages. Recover some after from the trashbin. |  Files are correctly deleted and restored. | ✅   | 
5 | Using webdav upload a 100MiB file.| No errors in this process | ✅  |
6 | Upload 100MiB file with web UI (new dav chunking) | No errors in this process | ✅   | tested in both Firefox and IE11

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @PVince81, and @ownclouders.

A possibly duplicate or related issue is #29627: Smoke Test results for 9.0.11 RC1.
