### ISSUE TITLE
Internal Server Error when fresh install

### ISSUE THREAD

**Issue by Geraldf** [owncloud/core#29655]
I tried a fresh install with mysql, and I do get the "Internal Server Error" 

the message is:

> Interner Serverfehler
> 
> Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.
> Bitte wenden Sie sich an den Serveradministrator, wenn dieser Fehler mehrfach auftritt, geben Sie bitte die, unten stehenden, technischen Details in Ihrem Bericht mit an.
> Weitere Details können im Serverprotokoll gefunden werden.
> 
> Technische Details
> 
> Entfernte Adresse: 172.17.0.1
> Anfragekennung: SdDGrAfzmj6f2Mdm1ovi

the Log file contains only 3 lines.
`{"reqId":"SdDGrAfzmj6f2Mdm1ovi","level":3,"time":"2017-11-22T19:08:47+00:00","remoteAddr":"172.17.0.1","user":"--","app":"no app in context","method":"POST","url":"\/index.php","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/html\\\/apps\\\/files\\\/lib\\\/app.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/autoloader.php(157): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/html\\\/a...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Files\\\\\\\\App')\\n#2 [internal function]: spl_autoload_call('OCA\\\\\\\\Files\\\\\\\\App')\\n#3 \\\/var\\\/www\\\/html\\\/apps\\\/files_trashbin\\\/appinfo\\\/app.php(31): class_exists('OCA\\\\\\\\Files\\\\\\\\App')\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/app.php(213): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/app.php(164): OC_App::requireAppFile('files_trashbin')\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/DB\\\/MigrationService.php(89): OC_App::loadApp('files_trashbin', false)\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Installer.php(512): OC\\\\DB\\\\MigrationService->__construct('files_trashbin', Object(OC\\\\DB\\\\Connection))\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Installer.php(482): OC\\\\Installer::installShippedApp('files_trashbin')\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Setup.php(364): OC\\\\Installer::installShippedApps()\\n#10 \\\/var\\\/www\\\/html\\\/core\\\/Controller\\\/SetupController.php(64): OC\\\\Setup->install(Array)\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(865): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#12 \\\/var\\\/www\\\/html\\\/index.php(56): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/autoloader.php\",\"Line\":133}"}
{"reqId":"SdDGrAfzmj6f2Mdm1ovi","level":2,"time":"2017-11-22T19:08:47+00:00","remoteAddr":"172.17.0.1","user":"--","app":"core","method":"POST","url":"\/index.php","message":"Could not load app \"files_trashbin\", it will be disabled"}
{"reqId":"SdDGrAfzmj6f2Mdm1ovi","level":3,"time":"2017-11-22T19:08:47+00:00","remoteAddr":"172.17.0.1","user":"--","app":"index","method":"POST","url":"\/index.php","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/html\\\/apps\\\/files\\\/lib\\\/app.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/autoloader.php(157): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/html\\\/a...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Files\\\\\\\\App')\\n#2 [internal function]: spl_autoload_call('OCA\\\\\\\\Files\\\\\\\\App')\\n#3 \\\/var\\\/www\\\/html\\\/apps\\\/files_trashbin\\\/appinfo\\\/app.php(31): class_exists('OCA\\\\\\\\Files\\\\\\\\App')\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/app.php(213): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/legacy\\\/app.php(164): OC_App::requireAppFile('files_trashbin')\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/DB\\\/MigrationService.php(89): OC_App::loadApp('files_trashbin', false)\\n#7 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Installer.php(512): OC\\\\DB\\\\MigrationService->__construct('files_trashbin', Object(OC\\\\DB\\\\Connection))\\n#8 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Installer.php(482): OC\\\\Installer::installShippedApp('files_trashbin')\\n#9 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Setup.php(364): OC\\\\Installer::installShippedApps()\\n#10 \\\/var\\\/www\\\/html\\\/core\\\/Controller\\\/SetupController.php(64): OC\\\\Setup->install(Array)\\n#11 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(865): OC\\\\Core\\\\Controller\\\\SetupController->run(Array)\\n#12 \\\/var\\\/www\\\/html\\\/index.php(56): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/autoloader.php\",\"Line\":133}"}
`

not sure how to fix this. 

Gerald

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by kdslkdsaldsal** [comment]
Might be a duplicate of https://github.com/owncloud/core/issues/25536
