### ISSUE TITLE
Keep version in version history on restore

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#29666]
### Steps to reproduce
1. have some versions for a file V1 -> V2 -> V3
2. restor V2 

### Expected behaviour
history shall look like V1 -> V2 -> V3 ->V4

### Actual behaviour
history shall look like V1 -> V3 -> V2

### Additional requirements:
- fileid should remain unchanged on restoration

**Comment by PVince81** [comment]
:warning: Expected: file id of the top/current/latest version must stay unchanged.

I sense potential troubles with encryption, make sure to properly retest in that scenario.

**Comment by PVince81** [comment]
moving to planned

**Comment by PVince81** [comment]
moving to "triage"
