### ISSUE TITLE
Public link share UI cleanup

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#29694]
- [x] Adapt password and expiration date fields to a reasonable length
Currently these fields use the whole width of the modal. Just give them a reasonable length to make it look better (e.g. the date field always has the same width). For consistency I suggest to make the length of the two fields equal.

- [x] Rename the "Save" button to "Share"
This is to better reflect that the share and notifications effectively are created when the button is used.

- [x] Rename error message when invalid mail addresses are entered
=> "Could not send mail to the following **recipient(s)**"
This is to better differentiate between external recipients and internal **users**

- [x] Show "Sending"/"E-Mail sent" indicator longer and maybe turn green upon success
Currently the modal disappears in, say, 0,1 seconds after clicking the button so users have a hard time to see if the action was successful or not (I guess there is no "unsuccessful" but users should be able to take note of the success). Please increase the time the modal is shown after success to a reasonable value, e.g. 1-2 sec.

@felixheidecke @PVince81

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by felixheidecke** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Public link share UI cleanup · Issue #29694 · owncloud/core](https://trello.com/c/haWP25ck/2-public-link-share-ui-cleanup-issue-29694-owncloud-core)

**Comment by pmaier1** [comment]
Please provide a patch when this is merged. Thanks!

**Comment by felixheidecke** [comment]
https://patch-diff.githubusercontent.com/raw/owncloud/core/pull/29721.patch

**Comment by pmaier1** [comment]
All points above covered? Please tick the checkboxes :) @felixheidecke

**Comment by PVince81** [comment]
reopening until clarified

**Comment by pmaier1** [comment]
Last point about showing the "mail sent" indicator still to be done.

**Comment by PVince81** [comment]
@felixheidecke does https://github.com/owncloud/core/issues/29695 also fix this ?

**Comment by felixheidecke** [comment]
It does

**Comment by felixheidecke** [comment]
I am sorry that I had to remove the long(er) showing message upon sending the link since it broke tests and I couldn't figure out the problem aaaand I wanted to get this done ASAP so I will open a separate PR for this.

**Comment by felixheidecke** [comment]
Lets close this for now. *Show "Sending"/"E-Mail sent" indicator longer and maybe turn green upon success* Is also part of this issue: https://github.com/owncloud/core/issues/29703

**Comment by PVince81** [comment]
@felixboehm according to @felixheidecke here it should be done as part of https://github.com/owncloud/core/issues/29694#issuecomment-376806594. @felixheidecke did you just forget to tick the checkbox ?

**Comment by PVince81** [comment]
hmmm I tried this on stable10 and the modal still disappears too quickly... I'll have a look...

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/31057
