### ISSUE TITLE
Public links: Add personal note and option to receive a copy

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#29696]
**Add a message field to provide a personal note in the mail notification**

As a user I want to add a personal note when sharing with externals via public link to reference a previous conversations or just provide some hints to externals that never used ownCloud before.

The mail notification should be just like the default, but inserting a paragraph with my personal note after the introduction text.

**Add a checkbox "Receive a copy" to set yourself in CC of the mail notification**

As a user I want to be able to receive a copy (put me on CC) of the mail notifications I send out when sharing public links for that I can see what the recipients see and to be able to use that mail notification afterwards in my mail client (forward to others, reference the notification, etc.).

A mockup would be great!

@felixheidecke @PVince81

**Comment by felixheidecke** [comment]
We could have a separate section below. The Textarea expands on putting text in as in this example:

![public_share_message](https://user-images.githubusercontent.com/12717530/33428910-165ec7f2-d5cb-11e7-99f9-68918fc0846e.gif)

**Comment by pmaier1** [comment]
Yes, looks nice! Maybe we can make it expandable/collapsible to save some space. Recipient field requirements are here.

What about backend for inserting the message to the mail notification? Is this something easy? @PVince81

**Comment by pmaier1** [comment]
Lol, just saw the German translation for "File Drop" in the mockup. This is bad and should be called "File Drop" as well. Can we make this a non-translatable string?

**Comment by felixheidecke** [comment]
> Can we make this a non-translatable string?

Sure can :-D

**Comment by felixheidecke** [comment]
As I recall, there is a greater rework of the sharing due. Can we postpone changes until then?

**Comment by PVince81** [comment]
It might be possible to use the given message when sending emails, but the custom message will not be saved anywhere.

**Comment by PVince81** [comment]
custom message as displayed in UI must use some template as preset

**Comment by pmaier1** [comment]
> It might be possible to use the given message when sending emails, but the custom message will not be saved anywhere.

I don't think it needs to be saved somewhere.

> As I recall, there is a greater rework of the sharing due. Can we postpone changes until then?

This is not that much related to the other stuff except that we want to come away from the modal and integrate in the sharing sidebar.

Just thinking loud: When tackling this maybe we could enable editing the whole template to cover other use cases where people are unhappy with the templates as well. Generally inserting a note to the template would be preferable though, IMO. Editing templates should happen in the template editor.

**Comment by PVince81** [comment]
@felixheidecke please ping @jvillafanez for backend work when needed

**Comment by PVince81** [comment]
- [ ] public API + exposing email template: https://github.com/owncloud/core/issues/29937

**Comment by PVince81** [comment]
maybe at first we just go with sending whatever message is there without the public API as the latter might be more tricky as it seems to violate some semantics

**Comment by felixheidecke** [comment]
Has been addressed in https://github.com/owncloud/core/pull/29935

**Comment by pmaier1** [comment]
Some further feedback:
- The flow is fine as it is. No need to be able to edit the whole template. We should stay with injecting the personal note. :heavy_check_mark: 
- Currently the personal note does not respect custom mail templates. Instead it overrides and injects the message in the default template. This needs to be addressed :x:

**Comment by pmaier1** [comment]
I assume that the functionality is currently not available via API, right? We should schedule this for a later iteration to make it available in the clients as well at some point. @PVince81

**Comment by PVince81** [comment]
@pmaier1 the current code should use the custom mail template only if no personal note is given, else override it fully with whatever is written in the personal note.

Are you saying that it should use the custom mail template internally and inject the personal note in the middle of it ?

**Comment by pmaier1** [comment]
> Are you saying that it should use the custom mail template internally and inject the personal note in the middle of it ?

Yes, I think that this is the expectation.

**Comment by PVince81** [comment]
Ok, assigning self, need to modify the backend

**Comment by PVince81** [comment]
@pmaier1 the email template doesn't have space for a personal note: https://github.com/owncloud/core/blob/master/core/templates/mail.php#L15
 
Considering that people might customize this file or already did so, they'd need to also adjust accordingly.

What we can do is add an additional variable containing the personal note in the default template, as an additional sentence.

For example if a personal note is set, then it could add a block: "Personal note from the sender: %s".

So it could look like this:
```
Hey there,

just letting you know that Vincent shared something with you.

Personal note from sender: hey Patrick, look at this thing!

View it!

```

**Comment by jvillafanez** [comment]
That template won't work for the email notifications neither. You might receive the update notification via email, and it's impossible to fit it in that template.
We need to figure out something more generic.

**Comment by PVince81** [comment]
@jvillafanez this mechanism will never be using email notifications. This is because the email in question will always be sent to users who are **outside** of ownCloud. Our notifications app can only notify users who have accounts on ownCloud.

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/core/pull/30789

Note that this adds an optional section in the email if personal note is set.
Any custom template will need manual adjustments accordingly.
