### ISSUE TITLE
Improve public link share mail address input field

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#29695]
The current mail address input field for public link shares is too small and does not work well when entering more than one address. It would be great to have it similar to the following screenshot:

![link_addresses](https://user-images.githubusercontent.com/21193500/33278324-7b0f7fc0-d39b-11e7-9319-532afea95462.png)

**Requirements**
- input field is adaptive (auto-scale)
- mail addresses become "fixed" by hitting space as in the screenshot
- mail addresses can be "unfixed"/deleted letter-wise with backspace and have a "x" to delete them at once

A mockup would be great!

@felixheidecke @PVince81

**Comment by PVince81** [comment]
@felixheidecke was this done with https://github.com/owncloud/core/pull/29935 ?

**Comment by felixheidecke** [comment]
> @felixheidecke was this done with #29935 ?

Nope, this was not done so far. @pmaier1 are we sure this is necessary? Can we move this to the backlog? Other things seem more urgent.

**Comment by pmaier1** [comment]
> Nope, this was not done so far. @pmaier1 are we sure this is necessary? Can we move this to the backlog? Other things seem more urgent.

Yes, it's important. This is a p1 item in the milestone for the next release. Also it's a prereq for https://github.com/owncloud/core/issues/29938. Let's speak if there are concerns.

**Comment by PVince81** [comment]
let's use select2 which is already included with ownCloud core, see http://select2.github.io/select2/ and search for "Tagging Support" as agreed when discussing with @felixheidecke

**Comment by felixheidecke** [comment]
select2 is not suitable for this matter. If we really want to implement this behavior, we do need jet another external library.

**Comment by PVince81** [comment]
also needs to support autocomplete, see https://github.com/owncloud/core/pull/30645#issuecomment-369860841

**Comment by felixheidecke** [comment]
[PR](https://github.com/owncloud/core/pull/30645) is ready to review

**Comment by felixheidecke** [comment]
Merged
