### ISSUE TITLE
show a list of users that have not yet agreed to the recovery key

### ISSUE THREAD

**Issue by butonic** [owncloud/core#29704]
before trying a decrypt-all the admin should be able to see which users have not yet agreed to the recovery key.

```sql
SELECT DISTINCT `userid`
FROM `oc_preferences`
WHERE `userid` NOT IN (
  SELECT `userid`
  FROM `oc_preferences`
  WHERE `appid` = 'encryption'
    AND `configkey` = 'recoveryEnabled'
    AND `configvalue` = '1'
)
```

- [ ] occ command
- [ ] check button in the admin settings encryption section, maybe with a 'send reminder' button
- [ ] occ command to check if all files have been correctly reencrypted.

cc @tomneedham

**Comment by PVince81** [comment]
what happens if you decrypt-all anyway? does it skip these users or brutally aborts when meeting one of them ?
