### ISSUE TITLE
"file exists" step is ineffective

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#29700]
### Steps to reproduce
1. Change an integration test step of the form:
```
Then as "alice" the file "/file.txt" exists
```
to mention a file that really does not exist:
```
Then as "alice" the file "/file-that-does-not-exist.txt" exists
```
2. Run the test scenario

### Expected behaviour
The test step should fail.

### Actual behaviour
The test step passes, and happily moves along to the next step.

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
PHP dev server

**Database:**
mySQL

**PHP version:**
5.6.31

**ownCloud version:** (see ownCloud admin page)
10.0.4 current from git

**Comment by PVince81** [comment]
I'd see this as high priority because if other tests are using this they might give false positives...

**Comment by phil-davis** [comment]
Fix merged and backported to stable10.
