### ISSUE TITLE
Possible to create an app password without a name

### ISSUE THREAD

**Issue by mdusher** [owncloud/core#29709]
### Steps to reproduce
1. Go to Settings -> Security
2. Click "Create new app password" without filling in the name

### Expected behaviour
The user should be requested to enter a name for the app password

### Actual behaviour
The app password is created without a name.

Screenshot:
![image](https://user-images.githubusercontent.com/3529874/33353112-3c83d74a-d500-11e7-86fa-7ed5d5095775.png)

### Server configuration
**Operating system**: Redhat 7

**Web server:** Apache 2.2.15

**Database:** MariaDB 10.0.27 with Galera 25.3.18

**PHP version:** 7.0.23

**ownCloud version:** 10.0.3

**Updated from an older ownCloud or fresh install:** Updated from 8.2.11

**Where did you install ownCloud from:** https://owncloud.org/install/#edition

**Comment by hodyroff** [comment]
Thanks for your feedback. Why do you think a name should be mandatory? It seems in the discretion of the user to set one or not - its a self-service after all and follows the frictionless design criteria. Would be interested in your thoughts.

**Comment by PVince81** [comment]
Maybe it looks just ugly and less useful if one decides to not specify a name.

I believe it's also possible to set the same name to separate tokens.

Maybe we should at least allow renaming them.

**Comment by mdusher** [comment]
The reasoning is entirely UX related. Functionally it's fine without them - but when it comes to users, the only thing they can use to identify the token would be when it was last used. Which if they have multiple tokens which they are constantly using (eg. multiple sync clients that are constantly running) and one becomes compromised, they would end up having to revoke all of them, if they chose not to name any of their tokens.

While I understand this would be a choice made by the user, sometimes it's better to not give them the option.

And as @PVince81, when it's blank - it is a bit ugly. We've had ownCloud 10.0.3 deployed for less than a week and already had a user question why the name was blank after not realising that they did not set a name for the token.

**Comment by PVince81** [comment]
fixed with https://github.com/owncloud/core/pull/29096
