### ISSUE TITLE
Files doesnt appear on the filesystem

### ISSUE THREAD

**Issue by CristianCardosoA** [owncloud/core#29707]
ownCloud 10.0.3
I upgrade owncloud with this command: sudo -u apache php occ upgrade
### Steps to reproduce
1. Add new directory via web
2. Add multiples files to the new directory
3. Go to your terminal and list your files under data/user/files/

### Expected behaviour
Tell us what should happen
Should appear the new directory and files on the terminal with the command 'ls -l'
### Actual behaviour
Tell us what happens instead
Doesn't appear the new files.
### Server configuration
**Operating system**:

**Web server:**
CentOS Linux release 7.4.1708 (Core)
**Database:**
Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64)
**PHP version:**
PHP 7.0.23
**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**
I don't know what version was before the upgrade.
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE",
            "192.168.1.2"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/mysite.com\/owncloud",
        "dbtype": "mysql",
        "version": "10.0.3.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "smtp-relay.gmail.com",
        "mail_smtpport": "587",
        "mail_from_address": "***REMOVED SENSITIVE VALUE",
        "mail_domain": "***REMOVED SENSITIVE VALUE",
        "mail_smtpauthtype": "LOGIN",
        "memcache.local": "\\OC\\Memcache\\APC",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updatechecker": false,
        "loglevel": 2,
        "default_language": "es"
    }
}

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**
Enabled:
  - activity: 2.3.6
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.2
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - theme-example
  - user_external

```
**Are you using encryption:** yes/no
NO

### Client configuration
**Browser:**
Mozilla Firefox 56.0 64btis
**Operating system:**
Fedora 26

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @kdslkdsaldsal.

**Comment by kdslkdsaldsal** [comment]
> Add multiples files to the new directory

Added via the Web GUI or via the terminal?

**Comment by CristianCardosoA** [comment]
@kdslkdsaldsal Added via web GUI.

**Comment by kdslkdsaldsal** [comment]
Please add as asked in the issue template:

- logfile output (data/owncloud.log)
  - Clear the data/owncloud.log and then re-upload new files to get only relevant logs
- result of the integrity check

**Comment by CristianCardosoA** [comment]
[owncloud.log](https://github.com/owncloud/core/files/1511642/owncloud.log)

Result of the integrity check: No errors have been found.

**Comment by CristianCardosoA** [comment]
Also I created a new user via web GUI, and if I go to the terminal and search under data directory the new user directory is not on the filesystem.

**Comment by CristianCardosoA** [comment]
Also after that I run this command

`sudo -u apache php occ files:scan myuser`

The new files that I created via web GUI disappear.

**Comment by CristianCardosoA** [comment]
Message: Unexpected server response (503) while retrieving PDF "https://mysite.com.mx/owncloud/remote.php/webdav/0210043.pdf".
For some reason I cannot see the file, this time I tried the inverse, upload the files via ssh terminal and then run the command 
`sudo -u apache php occ files:scan myuser`

I can see the directory but I cant access to it or event download it.

**Comment by kdslkdsaldsal** [comment]
This really looks like some sort of server / environmental issues. I suggest the following:

1. Fix the PHP issue of your owncloud.log within the PHP configuration
2. Run litmus against the WebDAV interface of ownCloud

Instructions for 2. can be found at https://central.owncloud.org/t/how-to-compile-and-run-litmus-on-debian-for-webdav-tests/839 once it is available again.

**Comment by PVince81** [comment]
likely not an ownCloud server bug, please carry on seeking help on [central](http://central.owncloud.org/)
