### ISSUE TITLE
Ext storage password reentry, send notification

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29715]
Whenever a user password that was used for an external storage is invalid, usually the user needs to go to the web UI and see the mount point highlighted in red. Then the user needs to click on the row and gets a popup to enter the storage's password.

We should find a way to move this to user notifications instead: whenever the system detects that a point is not available any more due to credential issue, it would send a user notification with a link to the setting page to reenter the password there.

How to detect such thing is a different story. Maybe not a background job. It could detect this on the fly: whenever the folder is accessed, if a `StorageNotAvailableException` was thrown somewhere and is related to wrong password, take note into a table (oc_storages ?). Later on, a process will send out the notification **once**.

@jvillafanez @pmaier1

**Comment by jvillafanez** [comment]
Questions:
* Which component will be responsible of sending the notification? each storage implementation? any specific core component?
* If core will be the one sending the notification, I guess the storage will report it via a `PasswordChangedException` (probably inheriting from the `StorageNotAvailableException`)
* Each storage will likely detect the problem more than once, and maybe too frequently if this happens. Which component will deduplicate the notifications? core? whatever component consuming the notifications?

Note that we have plans for the notification system, so this case should also be included.

**Comment by PVince81** [comment]
Maybe something like `StorageAuthenticationFailedException`. 

Yes, we need a way to debounce this. The `oc_storages` table already has a column `available` that is set to false with a 10 minutes delay. So within these 10 minutes it doesn't bother rechecking and returns the same exception. The moment where we set this flag could be the opportunity to trigger the notification from within core (the `FailedStorage` ?). Then we might need to set the "available" flag to another value that tells "don't bother rechecking or notifying, the user needs to act".
