### ISSUE TITLE
need to extend testing app to make it possible to run tests against remote instances

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#29710]
currently the UI and API (integration) tests can only run locally on the same machine where owncloud is installed. It would be nice to be able to run the tests against remote instances e.g. inside a docker container.
For the UI tests the main limitations currently are: 
- enabling and disabling apps
- set/remove/change settings in `config.php`
this is needed in the setup phase and is currently done by the `occ` command.

I propose to:
1. make new functions in https://github.com/owncloud/core/blob/master/apps/testing/lib/Config.php to set/remove/change settings in `config.php`
2. create an API endpoint to be able to run arbitrary `occ` commands through the testing app

@patrickjahns @SergioBertolinSG @davitol @PVince81 @phil-davis

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @phil-davis, and @PVince81.

**Comment by phil-davis** [comment]
Thoughts/notes about the testing app and security:
- testing app is not bundled for normal distribution (so it cannot be accidentally enabled on a production system)
- testing app already can change various "system settings"
- extending to it enable/disable other apps and run general occ commands gives it more power to be destructive (which is what is needed in testing - to add/change/revert(delete) things for test setup/teardown and execution)
- but API calls to the testing app need to be authenticated as an admin (I hope this is true), so an accidentally-installed-enabled testing app can only be used if admin credentials are already known (this mitigates the accidental exposure, if you already know oC admin credentials then you can already do many of the things via the webUI)

**Comment by SergioBertolinSG** [comment]
@individual-it what is the benefit in running occ commands from the testing app instead of using [CommandLine trait] (https://github.com/owncloud/core/blob/master/tests/integration/features/bootstrap/CommandLine.php) ?

**Comment by phil-davis** [comment]
@SergioBertolinSG CommandLine trait starts a child process of the process that is running the Behat test suite, and runs ``occ`` in that. If the oC server under test is a separate [computer|VM|docker image] then running ``occ`` from outside that image will not work.
We want to work towards the test scripts being able to run completely outside the oC install under test, which means they need to do everything via some API, webUI or other interface of the oC install under test.

**Comment by SergioBertolinSG** [comment]
OK, that might be interesting. But with the current owncloud-docker containers you can run integration tests (with some [tweaks](https://github.com/SergioBertolinSG/server) ) and tests using occ didn't fail.
```docker exec -t server_owncloud_1 /bin/sh -c "cd tests/integration && sudo -u www-data ./run.sh"```

**Comment by individual-it** [comment]
@SergioBertolinSG that still runs the tests inside the container. That works already also for UI tests, but for it to work the whole tests infrastructure must be installed in that container. The goal is to tests an instance from the outside

**Comment by SergioBertolinSG** [comment]
> The goal is to tests an instance from the outside

OK, didn't know this. So integration tests will require more changes I'm afraid.

**Comment by patrickjahns** [comment]
@SergioBertolinSG 

Please clarify what you mean with 'integration tests"

**Comment by SergioBertolinSG** [comment]
Tests living in the integration folder, or using the new name: Acceptance tests on the webdav level.

**Comment by patrickjahns** [comment]
So basically here: https://github.com/owncloud/core/tree/master/tests/integration

I see some setup being done in https://github.com/owncloud/core/blob/master/tests/integration/run.sh

Here we need to differentiate between:
- setup of owncloud (have a owncloud with masterkey encryption, have a owncloud with user encryption etc)
- setup of infrastructure related parts (i.e. running php internal webserver )

Basic idea with the nightly setup is:
- combine "server" (core) with certain applications ("artifact")
- put this artifact in a infrastructure environment (i.e. apache-phpX + mysql + redis + X)
- configure owncloud in a certain way (i.e. use encryption, have X, have Y) 
- run specific tests against it

**Comment by patrickjahns** [comment]
>make new functions in https://github.com/owncloud/core/blob/master/apps/testing/lib/Config.php to set/remove/change settings in config.php

Is this really needed or a nice to have feature? Can't we change settings via `occ config:set` ?

> create an API endpoint to be able to run arbitrary occ commands through the testing app

Shall this be done via executing arbitrary shell commands? 
Or shall we have a wrapper around the symfony console commands and all them? 
Similar to https://symfony.com/doc/current/console/calling_commands.html

**Comment by individual-it** [comment]
> Is this really needed or a nice to have feature?
nice to have if we can run any `occ` commands

> Shall this be done via executing arbitrary shell commands?
arbitrary shell commands will be more flexible, then we are talking about a shell endpoint and probable even easier to implement. But it would open even a bigger door if the testing app is antecedently enabled.
Currently I don't see the need for arbitrary shell commands so I would suggest a wrapper

**Comment by phil-davis** [comment]
The wrapper can just take a string that is the ``occ`` command to be executed then exec/run ``occ $command`` - it would not need to bother sorting out how to internally call the symfony console commands.

**Comment by individual-it** [comment]
@phil-davis yes you are right, played around with symphony stuff but the way occ commands are run is that they always expect ARGV input. So I ended up more or less coping `runOcc` from `TestHelpers\SetupHelper`

PR here: #29727

**Comment by individual-it** [comment]
closed by #29727
