### ISSUE TITLE
encryption:recreate-master-key does not encrypt a file if we have run before encryption:decrypt-all command

### ISSUE THREAD

**Issue by davitol** [owncloud/core#29726]
### Steps

1. As Admin Setup encryption with master key on the ownCloud Server via webUI
2. Logout and Log in as admin to initialize keys
3. Create a file.txt and save it
4. Check the file is encrypted
5. run ```sudo -u www-data ./occ encryption:decrypt-all```
6. Check that file.txt is decrypted
7. Create a file2.txt and save it
8. Check the file is encrypted
9. run ```sudo -u www-data ./occ encryption:recreate-master-key```

### Expected result
file2.txt should be kept encrypted

### Actual result
file2.txt is no longer encrypted

### Version
ownCloud 10.0.4RC1 for both instances

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by sharidas** [comment]
I am able to reproduce it. I am working on the same.

**Comment by sharidas** [comment]
The changes are merged for this issue. Hence closing this issue.
