### ISSUE TITLE
[FR] List of storages should be homogenious listed

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#29732]
### Steps to reproduce
1. Goto admin page / Storage
2. Click Add Storage
3. Compare the list order from "Add Storage" to "Allow users to mount external storage"

### Expected behaviour
List should be identical sorted

### Actual behaviour
![image](https://user-images.githubusercontent.com/3321281/33446795-81c6abfa-d601-11e7-9e39-bc13b01d7a33.png)

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7

**ownCloud version:** 10.0.4 RC1

**Updated from an older ownCloud or fresh install:** git

**Where did you install ownCloud from:** git

**Comment by kdslkdsaldsal** [comment]
PR for this seems to be already merged: https://github.com/owncloud/core/pull/29733

**Comment by mmattel** [comment]
All merged, closing, thanks
