### ISSUE TITLE
[Feature Request] Check if file names restrictions apply for a given mount (filesystem)

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#29759]
**Problem:**
If you copy/move files from one storage type to another, it might be possible that file name restrictions apply. This can happen when you copy/move files originating in a *unix derivate to a smb mount. Because the mount is a folder, you can not see the underlaying filesystem and its restrictions. The same when you create a new file via the browser with restricted patterns. Currently you just get a deny or a strange not related error message/behaviour but without a explaining reason.

**Example1:**
``mount_unix:`` ``LPT1.txt`` copy to ``mount_smb:``
``LPT1.txt`` is a valid filename in *unix but not in Windows.

**Example2:**
``mount_windows:`` ``a&b.txt`` copy to ``mount_unix:``
``a&b.txt`` is a valid filename in Windows but you will get problems in *unix as it is not escaped.

**Impact:**
Because you do not know the reason for not beeing able to copy/move/create, and assume the the user has not the deep knowledge about the different restrictions of filesystems file namings, this can become very annoying and confusing.

**Proposal:**
Add an identifyer to the mount settings where you can preset different types of file name restrictions, like Windows, *unix ect (extendable if a finer granularity is needed)
Having this identifyer, a file create/copy/move action passes the file name restriction part and tells the calling function respectively user about if it found a restriction match.
On the http response type, a possibility would be to use code 422 (Unprocessable Entity) see https://www.bennadel.com/blog/2434-http-status-codes-for-invalid-data-400-vs-422.htm
The identifyer should be part of the webdav propery so the client can use this info.
With the proper http code, core and apps can differntiate responses like reject, rename, ect and include a reason why.

The client side is a different issue and is addressed in https://github.com/owncloud/client/issues/6202

**what-characters-are-forbidden-in-windows-and-linux-directory-names**
https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names

1.) The forbidden printable ASCII characters are:
- Linux/Unix: ``/ (forward slash)`` 
- Windows: ``< (less than)`` ``> (greater than)`` ``: (colon - sometimes works, but is actually NTFS Alternate Data Streams)`` ``" (double quote)`` ``/ (forward slash)`` ``\ (backslash)`` ``| (vertical bar or pipe)`` ``? (question mark)`` ``* (asterisk)`` 

2.) Non-printable characters. If your data comes from a source that would permit non-printable characters then there is more to check for.
- Linux/Unix: ``0 (NULL byte)``
- Windows: ``0-31 (ASCII control characters)`` Note: While it is legal under Linux/Unix file systems to create files with control characters in the filename, it might be a nightmare for the users to deal with such files.

3.) Reserved file names. The following filenames are reserved:
- Windows: ``CON, PRN, AUX, NUL  COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9 LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, LPT9`` 

4.) Other rules
- Windows: ``Filenames cannot end in a space or dot``

@PVince81 

Update:
An implementation would require a new webdav property. Suggestion: ``isFsType`` [W,L]

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by mmattel** [comment]
@PVince81 
Do you have any comment on that?

**Comment by PVince81** [comment]
That's likely an extension of the ongoing discussion about forbidden chars and case insensitiveness.

@michaelstingl @jvillafanez

**Comment by michaelstingl** [comment]
@pmaier1 for help…

I started to at least document such stuff:
https://github.com/owncloud/documentation/issues/2832

**Comment by mmattel** [comment]
This is a small table on what a proposed ``isFsType`` may return based on the mount source.

* Auto = y means, that there is no manually entrance of the type in mount settings necessary. The type is defined implicitly by the mount type
* Auto = n means, that the mount UI needs a code change and the user/admin has to check
* Default: a predefinition is made but the user/admin can change it, restricted to possible values

With deeper analysis, more or less types may be needed

Mount Type | Auto | Possible Values | isFsType Default | Note
------------ | ------------- | ------------- | -------------  | -------------
Amazon S3 | y | A | A | http://www.ezs3.com/public/232.cfm
Dropbox | y | D | D | https://www.dropbox.com/help/syncing-uploads/files-not-syncing
FTP (Fly)  | **n** | WL | L | Must be manually entered in the mount settings
Google Drive  | y | L | L 
Openstack-Objektspeicher   | y | O | O
ownCloud   | **n** | ADLOSW | L | Must be manually entered in the mount settings
sFTP   | **n** | WL | L | Must be manually entered in the mount settings
SMB/CIFS   | y | W | W
WebDav   | **n** | WL | W | Must be manually entered in the mount settings
OneDrive  | y | W | W | https://support.office.com/en-us/article/invalid-file-names-and-file-types-in-onedrive-onedrive-for-business-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa
Sharepoint | y | S | S | https://support.microsoft.com/en-us/help/905231/information-about-the-characters-that-you-cannot-use-in-site-names--fo

**Comment by PVince81** [comment]
Thanks for the research!

**Comment by mmattel** [comment]
Extension of the idea of having a webdav property ``isFsType``...

**Bonus:** mainenance in core, core & client use the same ruleset

Webdav property | Example | Comment
------------ | ------------- | -------------
``isFsType`` | ``W`` | generic info about the filesystem type, see table above
``forbiddenChars``  | ``~*<>#{}/\?:"`` | needs a way how ASCII control characters 0-31 can be implemented (see Windows) or done generic because of knowledge of ``isFsType`` or excluded generally
``reservedNames`` | ``LPT1`` ``NUL`` ``..`` | Must not contain somewhere
``forbiddenStart`` | ``.``  `` `` |
``forbiddenEnd`` | ``.``   ``.files`` ``_elemei``  `` ``   | eg Sharepoint

This would also make error reporting and solution suggestion easier based on where the issue raised.

**Comment by jvillafanez** [comment]
This seems a lot of work for a little gain.

The ownCloud FS should be treated transparently. Users don't need to know where the files are stored, nor any possible restriction while the file is being uploaded anywhere.

There are 2 problems we're trying to solve here:
* Error reporting to the user, specifically invalid filenames. This can be "easily" solved by forwarding the error from the storage to the user.  The problems here is that the storage needs to detect the error (some backends might swallow it and don't report anything) and core needs to properly propagate the error to the client.
* Detecting the error in advance in order to prevent uploading a 20GB file and reject the file because the filename isn't valid. This can be done at storage level by adding a new `isValidFilename($path)` function to the storage interface. Core can use this function to reject the upload with the corresponding error message. Note that this will be a breaking change because we'll need to change the storage interface to add that method.

So far, the filename restrictions are only known by the storage implementation. Core doesn't really know the restrictions, it just ask the storage if the target filename can be used ot not.

The expected changes in this case are only inside core. The changes for the clients are limited to handling the new error code to show a more meaningful message to the user

Going further than that implies good will for the clients (that they'll implement those restrictions properly), as well as extra work for all the parties involved (core and all the clients) to keep those restrictions up-to-date.

**Comment by mmattel** [comment]
> This seems a lot of work for a little gain

The view we have to take here is not the one of an experienced and knowledged person but an ordinary user who has no clue about all these limitations. As reference, see  https://github.com/owncloud/client/issues/6202

Working in the browser is one thing. Preventing uploads early because of naming mismatches is as you describe an important topic.

The other thing is the client, see link above. Here we get into a deeper issue which is quite hard to understand from a user side. This issue report here addresses this from the core side and prepares the fix down to the client side. There is also no break (as far I see it). Empty or non existant webdav properties just have no change on the current behaviour.

The error reporting I mentioned is just a valuable side effect.

> extra work for all the parties involved (core and all the clients) to keep those restrictions up-to-date

Only on core, as core delivers the rulset via the properties. Naming restrictions are exremely static...

**Comment by jvillafanez** [comment]
The error generated by the storage connector MUST have enough information for the average user. It doesn't matter where that error will end, whether a log file or shown to a mobile user. "Invalid filename: the name is reserved" or "Invalid filename: the filename contains forbidden chars" is a good message to be shown to both the users (in the clients) and the admin (in the log file) that can be generated in the storage connector, obviously with an error code so clients can "prettify" the message as well as translate it.
This is why I'd rather focus on the error handling.

**Comment by mmattel** [comment]
> This is why I'd rather focus on the error handling.

Fully agree. This is this issue about. The fundament for doing this is to get the proper cause **both** on core and on client. MUST is the expectation, SHOULDis what we think but REALTY is different. Can´t repeat it more often - also on the client side. Please see the issue report.

**Comment by jvillafanez** [comment]
1. Core needs to properly handle a new "FilenameInvalid" exception that might come from the storages. To be decided what exact methods are allowed and expected to be thrown that exception, as well as if there is a need to provide an hierarchy ("ReservedFilename", "ForbiddenChars", "FilenameTooLong", etc)
2. Any storage is allowed to throw that exception (with a refined message) under the expected conditions by the methods specified above. Throwing the exception from other methods won't be properly handled by core and will cause malfunctions (basically whatever is happening now if a storage throws a random exception)
3. Core will convert those exceptions to webdav exceptions.

This should cover most of the problem. In addition:

4. Core will include an `isValidPath($path)` method in the storage interface in order to check if the storage can handle that specific **full** path.
5. That new function will be used as early as possible by core. Note that webdav won't likely have direct access to the storages (I think the ownCloud's VFS is in the middle).

These ones will depend on the current implementation. Worst case should be that the 10GB file is uploaded to ownCloud but it won't reach the external storage.

**Comment by mmattel** [comment]
**ad 1)** might = needs to be checked on each possible storage type if there is a usable return value telling about the reason. TBH this is where I have doubts on that this exist in the granularity needed on all storage types we currently support (see table above). If I am right, how to handle the missing cases after we have identified them?

**ad 3)** just to make it clear, this means that a problem described in the client issue could be covered by a webdav exception?

> worst case...

as the check is „late“ - after the instance got the upload data - the error will **always** be generated at the point when the data gets written to the storage, which is size independent.

**Comment by jnweiger** [comment]
I suggest to break this issue down into smaller components. Maybye like this:
1) Generate a few FStype tables in machine readable (JSON?) format. 
2) Tag backend storages with FStypeIds. Now the server has all the info researched here. 
3) Make the server forward FStype tables to clients for the storages they access.
4) Now clients have all the info and can start implement policies. Like e.g. more dynamic blacklists, file browser integration of other hooks to control file names before even attempting an upload.

Other possible benefits:
* Admins can define FStype tables, to implement interoperability between multiple storages and or client types.
* file firewall could also define policies. after reaching 2).

**Comment by jnweiger** [comment]
What is the definition if the letter codes used in https://github.com/owncloud/core/issues/29759#issuecomment-356652033 ?

A file 'a&b.txt' is perfectly legal in unix. If escaping is missing somewhere, please open a ticket.

**Comment by mmattel** [comment]
You are looking at it as developer but not as end user. Please re-read my introduction.
* An end user does not care and mostly not know about the underlaying differences
* ownCloud makes, that the underlaying mount type is not visible to the user
* Moving files from mount A to mount B can cause issues, just because of file name restrictions - and those are currently not covered. The end user has no clue why things fail or even worse, vanish.
* This includes the situation of instance = Linux, endu user client = Windows

**Comment by jnweiger** [comment]
Sorry, I probably misunderstood the tables, and I have too many hats:

As an end user, I don't want to consider different restrictions of different mountpoints within the owncloud server. (Full ack, that is a general goal)
As an end user, I want to sync a file named 'a&b.txt' between windows, mac or Linux using desktop clients connected to a server or the web ui. (I believe we are safe with that filename, actually)

As a developer, I know that '&' is a command separator in e.g. /bin/sh (Reading "it is not escaped" in your introduction example 2 rings an alarm bell)
As a QA tester, I want to investigate any hints for a shell being involved in back end storage code. (I don't even want to fix it :-) )

**Comment by mmattel** [comment]
I came up this thing when I identified that my doughter, which runs a macbooc, syncs with the client to an smb mount and wondered why a) some "crazy" non green signs are at the filename and b) she was not able to access data via the browser at school - which was quite embarrasing for her as it was an important multidocument homwork...
