### ISSUE TITLE
Share parent folder from inside

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#29753]
It would be nice to provide the possibility to share a folder even when having navigated inside of it. With the approach on the image you don't need to go one folder up but just click on the sharing icon, sharing dialog opens and you can share.

![share_parent_from_inside](https://user-images.githubusercontent.com/21193500/33562719-425b86f8-d916-11e7-95f4-a264e2238595.png)

I could imagine there's another ticket on this. Didn't find anything having a quick look.

@PVince81 @felixheidecke

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by PVince81** [comment]
@pmaier1 this one https://github.com/owncloud/core/issues/4333

Close ?

**Comment by hodyroff** [comment]
Yes, but lets get it done ;)
