### ISSUE TITLE
Add a webdav property telling if a given folder has sub-folder

### ISSUE THREAD

**Issue by ogoffart** [owncloud/core#29758]
For https://github.com/owncloud/client/issues/4232
We would need a webdav property that tells if a given folder has subfolders. (to know if we should show the expend symbol for it)

**Comment by PVince81** [comment]
I think something similar was asked by mobile devs (@davigonz ?) to know the number of sub-entries.
Maybe there could be a property `oc:total-folders` and `oc:total-files` so one could use this to provide a summary or expand arrow behavior.
