### ISSUE TITLE
Create Exception Hierarchy

### ISSUE THREAD

**Issue by butonic** [owncloud/core#29757]
Carrently Exceptions are springkled all over the place. If we want to use them we need to rework them properly.

While in general apps will be disabled when they throw an exception to protect core from broken apps during upgrades, there are cases where oc actually handles them differently, eg. the `HintException` as well as `OutOfBoundsException` during user sync.

I think we should come up with a small hirarchy of exceptions, at least differentiate between exceptions that disable apps and those that don't.

Furthermore, there are exceptions that carry a message for the user vs exceptions that carry messages for admins.

Probably more. Ideas?

These Exceptions then need to be provided under OCP if appropriate and documented.

cc @tomneedham @PVince81 @DeepDiver1975

**Comment by DeepDiver1975** [comment]
> These Exceptions then need to be provided under OCP if appropriate and documented.

existing exception in OCP need to stay unchanged since they are part of the api

**Comment by butonic** [comment]
Existing OCP exceptions can still be made to extend whatever hierarchy we will come up with
