### ISSUE TITLE
[Feature Request] Deliver mail templates/settings to clients 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/core#29769]
Following up the discussion during NUE-hackweek, one interesting use-case for delivering client settings on the fly would be to transmit email-templates for e.g. public link shares. See related: https://github.com/owncloud/client/issues/6196

**Comment by PVince81** [comment]
Not the template itself but the fully rendered HTML / plain text so the clients can just paste this into the email. This makes it possible to define the email template in the server (one location).
