### ISSUE TITLE
[FR] Add creation date to user listing

### ISSUE THREAD

**Issue by hodyroff** [owncloud/core#29772]
https://demo.owncloud.org/settings/users

Add to the settings:
"Show user creation date"

Get date from the activity for the user.
Idea: SELECT timestamp FROM oc_activity WHERE file LIKE '%ownCloud Manual.pdf%' AND user=myuser

Add a coloumn which shows the date not the since.

**Comment by PVince81** [comment]
What qualifies as user creation ?

The query above (hacky) implies it's the time of the first login, whenever the skeleton was copied. This would be the same date like the last login which is already available in the settings page. (see bottom-left options to display hidden columns)

It could also mean:
- the date the user was imported to oc_accounts table through user:sync (ex: LDAP), which is the date where the user got known to OC, not necessarily the date the user was added to the LDAP server
- the date the user was created over the settings/users page using manual creation

Any specific use-case, reason ?

**Comment by PVince81** [comment]
Had a chat with @hodyroff and it turns out I mixed up "first login" with "last login".

Proposal:

- add a new column `oc_accounts.first_login`
- populate that column at the same time where we copy the skeleton in the code (first time login)
- at update time, find that information for already existing users from another location (to be defined)
- display that value as a regular date (no "since") in the settings/users page

@pmaier1 @DeepDiver1975

**Comment by PVince81** [comment]
Now to find when the formerly existing users logged in the first time:
- use oc_activity query proposed in OP, however this will not work if activity app is disabled
- we looked at the timestamp of the folder "data/$userId/" but it seems it only has mtime, no creation time (at least not on my BTFS)
- other ideas ?

**Comment by guruz** [comment]
Can't this be a separate app? ;-)

**Comment by PVince81** [comment]
also expose over provisioning API as read-only field

**Comment by freakynl** [comment]
Hi,
no progress on this?

Our customer wants insights in whether or not created users (in the local database, no AD/LDAP connections) in say the last 2-3 months actually signed in once.

Now I can check the last logon date of course, but that doesn't tell him when they were created at all.

Don't know all the existing queries against the database, but adding a timestamp field to oc_users, for example as: created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, would probably fix this easily.
