### ISSUE TITLE
Allow addition of exact dates in addition to relative dates

### ISSUE THREAD

**Issue by hodyroff** [owncloud/core#29775]
https://demo.owncloud.org/settings/users

Could we add a button in the settings on the left which would allow the addition of a coloumn of exact dates in addition to the relative dates currently used? (6 minutes ago ... instead the date and time which right now is in the hover only).

**Comment by DeepDiver1975** [comment]
@felixheidecke design question - THX

**Comment by felixheidecke** [comment]
What problem does this solve?
