### ISSUE TITLE
Session handling: api and webdav requests with basic auth or oauth2 tokens shall not start a session

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#29779]
Reasoning:
- sessions are only usefull in web ui
- webdav by itself does not specify the use of sessions - only basic auth
- plain dav requests (e.g. caldav and carddav) are stateless and have no sessions - thousands of new sessions are generated - totally pointless https://github.com/owncloud/core/issues/5383

What to do:
- sessions are only started when an explicit login via the webui is initiated
- information currently being stored in the session needs to be store in a different location
- analyse the information which is stored in the session and review the storage location
- ISession and IUserSession are part of the public api - we need to continue to support this

**Comment by PVince81** [comment]
What about web UI?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by DeepDiver1975** [comment]
> sessions are only started when an explicit login via the webui is initiated

**Comment by PVince81** [comment]
moving to planned

**Comment by DeepDiver1975** [comment]
We will not touch these parts anymore -> close
