### ISSUE TITLE
Provide route / URL for displaying files search results page

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29784]
Desktop client will provide a search field but not fetch or display results directly.
It would just open the browser to a specific URL in the default system browser containing the search terms and this will display the search results there.

The current search feature in the files web UI only overlays on top of the file list but doesn't have a specific URL. We should provide one.

cc @pmaier1 @michaelstingl @ogoffart @guruz

**Comment by guruz** [comment]
...and announce the URL pattern as capability.
Ideally make it extensible so that later parameters could be added.
