### ISSUE TITLE
Bad idea: remove users automatically without undo

### ISSUE THREAD

**Issue by dercorn** [owncloud/core#29796]
### Steps to reproduce
1. occ user:sync
2. select remove option
3. ownCloud will erase any user's files which it deems unknown
4. there is no possibility for review and no undo

### Expected behaviour
The admin should get an overview of the users to be deleted and should have an opportunity to acknowledge that seperately.

### Actual behaviour
Users and their files are deleted without any feedback and no way of undoing the deletion.

### Possible solution
The best way would be to remove the "remove" option entirely. Disabling users is enough. This is even more true, since admins need to setup a cron job to sync users from AD on a regular basis. With "remove", this equals a regular opportunity for disaster.

@hodyroff @tomneedham please chime in

**Comment by tomneedham** [comment]
Works as designed in my opinion. Yes disabling makes much more sense, and we should provide the tools to manage (delete, renable) disabled users so that admins can use this workflow.

**Comment by dercorn** [comment]
What's more, is this: In installations with more than one AD/LDAP server, user:sync marks all users from the second AD/LDAP as unknown while querying the first one and probably vice versa.
At least, that is the impression I got from several test runs with multiple AD/LDAP connections.

**Comment by tomneedham** [comment]
This would be a separate bug. Checked out the coed quickly and this is not what it should do. It will call userExists on all of the users in owncloud. This will trigger the LDAP proxy to check on all of the ldap servers for the user, or use a cached user exists value.
