### ISSUE TITLE
Update for "Market" app is offered but does not install

### ISSUE THREAD

**Issue by sagamusix** [owncloud/core#29805]
### Expected behaviour
ownCloud tells me that Market 0.2.3 is available. Clicking the install button should update it.

### Actual behaviour
I get notified that the installation was successful, but afterwards, version 0.2.2 is still installed. I would think that this is possibly due to the fact that the plugin comes pre-installed from the package repository, but then it should not notify me about an available update. ownCloud still passes the integrity check before and after the update.

### Server configuration
**Operating system**: Bananian (Debian Jessie)

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** 10.0.3.3

**Updated from an older ownCloud or fresh install:** Update

**Where did you install ownCloud from:** ownCloud package repository

**Comment by DeepDiver1975** [comment]
this is a known issue which is resolved with market 0.2.3 - please allow write access to the apps folder. see https://central.owncloud.org/t/market-update-from-version-0-2-2-to-version-0-2-3-not-successful/10425/5

**Comment by sagamusix** [comment]
Completely independent from the solution, but shouldn't ownCloud warn when it cannot write its files instead of claiming it was successful?

**Comment by DeepDiver1975** [comment]
Exactly this was Added in 0.2.3
