### ISSUE TITLE
Cannot occ scan repair for a particular user

### ISSUE THREAD

**Issue by socrat3000** [owncloud/core#29812]
### Steps to reproduce
1. sudo -u www-data php occ files:scan 8D0D8BA8-DF3B-44FC-BEEA-25C605E57F88

### Expected behaviour
Complete without errors

### Actual behaviour
Exception during scan: OC\Share20\Exception\ProviderException: Parent of share should be unique
#0 /var/www/owncloud/lib/private/Share20/DefaultShareProvider.php(927): OC\Share20\DefaultShareProvider->resolveGroupShares(Array, '8D0D8BA8-DF3B-4...')
#1 /var/www/owncloud/lib/private/Share20/Manager.php(1036): OC\Share20\DefaultShareProvider->getAllSharedWith('8D0D8BA8-DF3B-4...', NULL)
#2 /var/www/owncloud/apps/files_sharing/lib/MountProvider.php(72): OC\Share20\Manager->getAllSharedWith('8D0D8BA8-DF3B-4...', Array, NULL)
#3 /var/www/owncloud/lib/private/Files/Config/MountProviderCollection.php(77): OCA\Files_Sharing\MountProvider->getMountsForUser(Object(OC\User\User), Object(OC\Files\Storage\StorageFactory))
#4 [internal function]: OC\Files\Config\MountProviderCollection->OC\Files\Config\{closure}(Object(OCA\Files_Sharing\MountProvider))
#5 /var/www/owncloud/lib/private/Files/Config/MountProviderCollection.php(78): array_map(Object(Closure), Array)
#6 /var/www/owncloud/lib/private/Files/Filesystem.php(445): OC\Files\Config\MountProviderCollection->getMountsForUser(Object(OC\User\User))
#7 /var/www/owncloud/lib/private/Files/Filesystem.php(375): OC\Files\Filesystem::initMountPoints('8D0D8BA8-DF3B-4...')
#8 /var/www/owncloud/lib/private/legacy/util.php(297): OC\Files\Filesystem::init('8D0D8BA8-DF3B-4...', '/8D0D8BA8-DF3B-...')
#9 /var/www/owncloud/lib/private/Files/Utils/Scanner.php(101): OC_Util::setupFS('8D0D8BA8-DF3B-4...')
#10 /var/www/owncloud/lib/private/Files/Utils/Scanner.php(186): OC\Files\Utils\Scanner->getMounts('/8D0D8BA8-DF3B-...')
#11 /var/www/owncloud/apps/files/lib/Command/Scan.php(224): OC\Files\Utils\Scanner->scan('/8D0D8BA8-DF3B-...', false)
#12 /var/www/owncloud/apps/files/lib/Command/Scan.php(310): OCA\Files\Command\Scan->scanFiles('8D0D8BA8-DF3B-4...', '/8D0D8BA8-DF3B-...', false, Object(Symfony\Component\Console\Output\ConsoleOutput), false, false)
#13 /var/www/owncloud/lib/composer/symfony/console/Command/Command.php(262): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/owncloud/core/Command/Base.php(159): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/owncloud/lib/composer/symfony/console/Application.php(826): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/owncloud/lib/composer/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/owncloud/lib/composer/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/owncloud/lib/private/Console/Application.php(162): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/owncloud/console.php(106): OC\Console\Application->run()
#20 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#21 {main}

### Server configuration
Ubuntu 16.04.3 64-bit

**Web server:**
Apache 2.4.18

**Database:**
MySQL 5.7.20

**PHP version:**
7.0.22
**ownCloud version:** (see ownCloud admin page)
10.0.4
**Updated from an older ownCloud or fresh install:**
Updated from an older ownCloud
**Where did you install ownCloud from:**
https://download.owncloud.org/download/repositories/stable/owncloud/
**Signing status (ownCloud 9.0 and above):**
No signing errors
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No errors have been found.

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocugm0s1yexg',
  'passwordsalt' => '***********',
  'secret' => '*******************',
  'trusted_domains' =>
  array (
    0 => '********',
    1 => '********',
  ),
  'datadirectory' => '/export/owncloud/data',
  'overwritehost' => '****************',
  'overwrite.cli.url' => '**************',
  'dbtype' => 'mysql',
  'version' => '10.0.4.4',
  'dbname' => 'owncloud',
  'dbhost' => '*********',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '*****************',
  'logtimezone' => 'Asia/Qatar',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'mail_from_address' => '*************',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => '****************',
  'theme' => 'qwerty_theme',
  'loglevel' => 1,
  'updatechecker' => false,
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'appstore.experimental.enabled' => false,
  'htaccess.RewriteBase' => '/',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '**********',
  'mail_smtpport' => '**************',
  'mail_smtpname' => '****************',
  'mail_smtppassword' => '*************',
  'singleuser' => false,
);

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

https://gist.github.com/socrat3000/19d441bf173837a0778068b63a896fb1
or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

https://gist.github.com/socrat3000/e308a81a616617ed69e1d792322b5e34

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox/Chrome
**Operating system:**
Ubuntu 16.04 Gnome
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

A possibly related issue is #25755: home storage not writable.

**Comment by PVince81** [comment]
Likely related to https://github.com/owncloud/core/issues/27990.

Closing.
