### ISSUE TITLE
[Feature Request] send notification to client in case of mount issues

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#29818]
Referencing: https://github.com/owncloud/client/issues/6227 (Show server sided mounts problems in client)

When a mount has a issue (eg. connection problems) the client should be notified via the notification process.

Background: if you work in the majority via the client (not with the browser) and a mount has a issue, you never see that there is a problem and you think all things are fine ...

@SamuAlfageme @PVince81

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by PVince81** [comment]
Slightly related https://github.com/owncloud/core/issues/29715

**Comment by SamuAlfageme** [comment]
@mmattel only in case the user is admin or it's his personal mountpoint? (i.e. if he has access to the mountpoint settings so issues can be solved or the storage disabled) otherwise I guess users will receive notifications they cannot fix or they can simply dismiss.

**Comment by mmattel** [comment]
Independent if the user is admin of the mount in question or not, at the current stage he does not recognize any problems related with the access as the client does not give any hints.

The biggest problem is, that because the user is not aware of an issue, he thinks that any change on the mount source source side will get synced to him - which is not ! He may be out of sync for a long time without any recognition of !!

Now in case of a problem highlighted, he can at least look at if the mount is self serviced and fix it or he  contacts the admin (mount owner) for support.

I have an actual usecase of this which made me digging into this situation deeper, resulting in filing this issue. The user is an ordinary user with absoutley no admin or background skills. If there is a warning - great. If there is none things must be fine. But if things are out of sync (by comparing to colleagues data) and there is no warning - the product becomes a bad mark...
