### ISSUE TITLE
Owncloud crashes most of the time

### ISSUE THREAD

**Issue by andriusign** [owncloud/core#29823]
### Steps to reproduce
1. Upload files.
2. OwnCloud crashes.

### Expected behaviour
File should be uploaded. File list reloaded.

### Actual behaviour
Huge error.

### Server configuration
**Operating system**: Ubuntu 17.04

**Web server:**
Apache2

**Database:**
MySQL

**PHP version:**
7

**ownCloud version:** (see ownCloud admin page)
10.0.3

**Updated from an older ownCloud or fresh install:**
Updated.

**Where did you install ownCloud from:**
Official source

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
Exception occurred while logging exception: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory
#0 /dirtomycloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /dirtomycloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /dirtomycloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /dirtomycloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /dirtomycloud/lib/private/DB/Connection.php(146): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /dirtomycloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /dirtomycloud/lib/private/DB/ConnectionFactory.php(140): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /dirtomycloud/lib/private/Server.php(472): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /dirtomycloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /dirtomycloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /dirtomycloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /dirtomycloud/lib/private/Server.php(1121): OC\ServerContainer->query('DatabaseConnect...')
#12 /dirtomycloud/lib/private/Server.php(233): OC\Server->getDatabaseConnection()
#13 /dirtomycloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#14 /dirtomycloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('AccountMapper')
#15 /dirtomycloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AccountMapper')
#16 /dirtomycloud/lib/private/Server.php(973): OC\ServerContainer->query('AccountMapper')
#17 /dirtomycloud/lib/private/Server.php(238): OC\Server->getAccountMapper()
#18 /dirtomycloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#19 /dirtomycloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('UserManager')
#20 /dirtomycloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('UserManager')
#21 /dirtomycloud/lib/private/Server.php(966): OC\ServerContainer->query('UserManager')
#22 /dirtomycloud/lib/private/Server.php(278): OC\Server->getUserManager()
#23 /dirtomycloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#24 /dirtomycloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('UserSession')
#25 /dirtomycloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
#26 /dirtomycloud/lib/private/Server.php(990): OC\ServerContainer->query('UserSession')
#27 /dirtomycloud/lib/private/Server.php(518): OC\Server->getUserSession()
#28 /dirtomycloud/lib/composer/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#29 /dirtomycloud/lib/private/AppFramework/Utility/SimpleContainer.php(111): Pimple\Container->offsetGet('AppManager')
#30 /dirtomycloud/lib/private/ServerContainer.php(87): OC\AppFramework\Utility\SimpleContainer->query('AppManager')
#31 /dirtomycloud/lib/private/Server.php(1311): OC\ServerContainer->query('AppManager')
#32 /dirtomycloud/lib/private/legacy/app.php(313): OC\Server->getAppManager()
#33 /dirtomycloud/lib/private/legacy/app.php(107): OC_App::getEnabledApps()
#34 /dirtomycloud/lib/base.php(579): OC_App::loadApps(Array)
#35 /dirtomycloud/lib/base.php(1013): OC::init()
#36 /dirtomycloud/index.php(54): require_once('/var/www/eweb.l...')
#37 {main}
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by VicDeo** [comment]
@andriusign `config.php` matters. Does your instance connect to MySQL via socket?

**Comment by PVince81** [comment]
Likely an environment issue. The error shows that the database server is not reachable for some reason.

Please ask on [central](http://central.owncloud.org/) for help
