### ISSUE TITLE
Long public share name hides share options and deforms icon

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#29821]
master @ fc4873385330fd7c9182c7c05913fed3421f46ee

1. create a folder
2. click share icon
3. go to public link
4. create public link with a long name

expected: everything looks pretty
actual: weird squished link icon see screenshot

<img width="462" alt="screen shot 2017-12-12 at 10 46 09" src="https://user-images.githubusercontent.com/660805/33880569-f13a33f4-df29-11e7-938f-b69d3d6d33af.png">

**Comment by tomneedham** [comment]
ok even worse, i cant even delete these now because i cant access the delete icons....

**Comment by PVince81** [comment]
@felixheidecke can you have a look ?

**Comment by tomneedham** [comment]
and even worse, you can't actually click the copy to clipboard link, despite the hover animation working, nothing actually gets copied

**Comment by felixheidecke** [comment]
I'm on it.

**Comment by PVince81** [comment]
not fully fixed, the icons are still squished and if white space is missing the action icons will disappear still : https://github.com/owncloud/core/issues/31158
