### ISSUE TITLE
TBD: Hard-requirement for php-fileinfo

### ISSUE THREAD

**Issue by ghost** [owncloud/core#29829]
Just stumbled over https://github.com/owncloud/documentation/issues/3622 which looks similar to https://github.com/owncloud/core/issues/29247

The php-fileinfo functions seems to be used in the following code-part:

https://github.com/owncloud/core/blob/v10.0.4/lib/private/Files/Type/Detection.php#L190-L233

This means we're in trouble if the following applies:

1. php-fileinfo is not installed / loaded (only listed as "optional" in the documentation)
2. open_basedir is configured which doesn't include the path to the "file" binary and/or popen or any other functions are disabled

which might lead to such issues like seen in the documentation issue linked above.

**Comment by PVince81** [comment]
Hmm I thought we got rid of this when switching to extension based detection with `detectPath()`

Seems `detect()` is still used in some locations:
```
apps/files_external/lib/Lib/Storage/AmazonS3.php|616| 'ContentType' => \OC::$server->getMimeTypeDetector()->detect($tmpFile),
lib/private/Archive/Archive.php|42| $mime = \OC::$server->getMimeTypeDetector()->detect($path);
lib/private/Files/ObjectStore/ObjectStoreStorage.php|391| $stat['mimetype'] = \OC::$server->getMimeTypeDetector()->detect($tmpFile);
lib/private/Files/Type/Detection.php|250| $mime = $this->detect($tmpFile);
lib/private/Installer.php|279| $mime = \OC::$server->getMimeTypeDetector()->detect($path);
lib/public/Files.php|64| return \OC::$server->getMimeTypeDetector()->detect($path);
```

The reason we switched is that we can't always access the file content directly especially on external storage or if the file is encrypted, so would need to first download the file which would be slow...

I'd vote for getting rid of this type of detection completely and also get rid of the php-fileinfo requirement.

Thoughts ? @DeepDiver1975 @butonic

**Comment by PVince81** [comment]
also it was reported that flysystem also requires this module here: https://github.com/thephpleague/flysystem/issues/968
