### ISSUE TITLE
Internal Server Error - Please Help

### ISSUE THREAD

**Issue by davidpalmer0205** [owncloud/core#29837]
### Steps to reproduce
1. Visited URL cloud.********.com
2. Log on using user credentials
3. Error Appears

### Expected behaviour
Tell us what should happen
Proceed to owncloud user dashboard/front screen after login

### Actual behaviour
Tell us what happens instead

Error and below details;

Internal Server Error
The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.

More details can be found in the server log.

Technical details
Remote Address: 62.69.33.128
Request ID: WjE9amF0xhTKOTuPMHhDcQAAAEo
Type: OCP\Files\NotFoundException
Code: 0
Message:
File: /var/www/vhosts/********.com/cloud.********.com/lib/private/legacy/helper.php
Line: 570

Trace
#0 /var/www/vhosts/********.com/cloud.********.com/apps/files/lib/Controller/ViewController.php(132): OC_Helper::getStorageInfo('/', false)
#1 /var/www/vhosts/********.com/cloud.********.com/apps/files/lib/Controller/ViewController.php(203): OCA\Files\Controller\ViewController->getStorageInfo()
#2 [internal function]: OCA\Files\Controller\ViewController->index('', '', NULL)
#3 /var/www/vhosts/********.com/cloud.********.com/lib/private/AppFramework/Http/Dispatcher.php(159): call_user_func_array(Array, Array)
#4 /var/www/vhosts/********.com/cloud.********.com/lib/private/AppFramework/Http/Dispatcher.php(89): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files\Controller\ViewController), 'index')
#5 /var/www/vhosts/********.com/cloud.********.com/lib/private/AppFramework/App.php(98): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files\Controller\ViewController), 'index')
#6 /var/www/vhosts/********.com/cloud.********.com/lib/private/AppFramework/Routing/RouteActionHandler.php(46): OC\AppFramework\App::main('ViewController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#7 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#8 /var/www/vhosts/********.com/cloud.********.com/lib/private/Route/Router.php(342): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#9 /var/www/vhosts/********.com/cloud.********.com/lib/base.php(929): OC\Route\Router->match('/apps/files/')
#10 /var/www/vhosts/********.com/cloud.********.com/index.php(56): OC::handleRequest()
#11 {main}

It also won't allow me to create any new folders or upload any documents. 

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page) 
Version: 10.0.4 (stable)

**Updated from an older ownCloud or fresh install:** 
Fresh Install

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- .well-known/acme-challenge/cYGuVocgCHWKj7soIUg0RcQTU8qN0uVtVaa5zyRzYeM
		- .well-known/acme-challenge/.htaccess
		- .well-known/acme-challenge/SXSprj5MkDnXcVLfPhLPIYo_Og1D8h6_iK0L74wPRFo
		- .well-known/acme-challenge/2aRy5QAu0toESdka09bidKl3RKd2oyXLbEl7tHWMNOo

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.well-known/acme-challenge/cYGuVocgCHWKj7soIUg0RcQTU8qN0uVtVaa5zyRzYeM] => Array
                        (
                            [expected] => 
                            [current] => 8e49986341f97d183ffb4b1360ba32dca00a575671bd845e08186a22d27f6413eae60805ae476e51406001cd869ef763908a60aacb7a430cf929af0c892723ae
                        )

                    [.well-known/acme-challenge/.htaccess] => Array
                        (
                            [expected] => 
                            [current] => cfa5b683614129d23a3b4619abab08163e70d527e605c9d167627bd87c8fde29fe6ce39c11fa3fe4c6ed97f4d7a883cc3bd90af299ce6e597db891b1a4d60bc3
                        )

                    [.well-known/acme-challenge/SXSprj5MkDnXcVLfPhLPIYo_Og1D8h6_iK0L74wPRFo] => Array
                        (
                            [expected] => 
                            [current] => 1be201efeae5705239f686a552b0e3c82184825c718a0b4a69d31bee6de228944aed4b527b07a9951693e5cf35284ac7f963ea8be899d57fbe49a8fa22834639
                        )

                    [.well-known/acme-challenge/2aRy5QAu0toESdka09bidKl3RKd2oyXLbEl7tHWMNOo] => Array
                        (
                            [expected] => 
                            [current] => c5493935d2a08c3cdd223d554a40148301af95a5f3cf63812e99a025925c027f135c7b6ddaee433d9d43edb17a0752aa5875e61b1961ca493a6855ee552f9256
                        )

                )

        )

)

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '********',
  'passwordsalt' => '********',
  'secret' => '********',

/* Trusted Domain URLs */
  'trusted_domains' => 
  array (
    0 => 'cloud.********.com',
  ),
  'datadirectory' => '/var/www/vhosts/********.com/cloud.********.com/data',
  'overwrite.cli.url' => 'http://cloud.********.com/',
  'dbtype' => 'mysql',
  'version' => '10.0.4.4',
  'dbname' => '********',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '********',
  'dbpassword' => '********',
  'logtimezone' => 'UTC',
  'installed' => true,
  'knowledgebaseenabled' => true,
  'debug' => true,
  'mail_from_address' => 'noreply',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'cloud.********.com',
  
/* Transactional File Locking 	*/
  'filelocking.enabled' => true,
  'memcache.locking' => '\OC\Memcache\Redis',
  'redis' => array(
     'host' => 'localhost',
     'port' => 6379,
     'timeout' => 0.0,
     'password' => '', // Optional, if not defined no password will be used.
      ),
);

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.




**List of activated apps:**

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
```

### Client configuration
**Browser:** Opera

**Operating system:** Windows 10

**Comment by kdslkdsaldsal** [comment]
@davidpalmer0205 Please fill out the full issue template (OS, PHP etc. are missing) as well as the full log output of the owncloud.log (seems to be stripped).

**Comment by PVince81** [comment]
This is not a support / help platform but a bug tracker. For support see http://owncloud.org/support
