### ISSUE TITLE
Auto disabling apps on exceptions can break instances

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#29850]
During initialisation, owncloud loads apps. This involves 'requiring' the app.php file which is wrapped in a try catch block, and if an exception is caught, the app will be disabled (with exception of shipped: alwaysEnabled app).

This is especially damaging when encryption or authentication apps are disabled as this can render the instance unusable for all users when the problem may have been intermittent -> and you would only see the exception once.

Proposal: never disable 'authentication' or 'filesystem' type apps.

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/core/pull/29853
