### ISSUE TITLE
Configure galera cluster with CI

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#29855]
@SergioBertolinSG We should add this to drone in the db matrix. Working on documenting a nice setup. But essentially we need the following containers:
 - 3x mariadb containers with an injected config
 - 1x maxscale container with an injected config

we then install owncloud and point it at the maxscale db port. Maxscale must have a network connection to the other three nodes.

In testing I have been playing with https://github.com/toughIQ/docker-mariadb-cluster for the db containers and https://github.com/toughIQ/docker-maxscale for maxscale. I then mounted in `./conf:/etc/mysql/conf.d` to provide my own mariadb conf. At the moment I was using the default maxscale configuration. We can hardcode the hostnames of the db servers if they are always created in a network and can resolve each other. Likewise, username and password and db name is passed in to the database container (both maxscale and maraidb need this)

**Comment by PVince81** [comment]
moved to "planned".

please move to "backlog" if not in direct focus
