### ISSUE TITLE
[Feature Request] Mark mount as read only in the mount settings

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#29873]
If you mount a storage, it could be that the user has no write rights.
It is not when we do sharing where we can already set a read only flag which we further do/could use (see later).

It targets those mounts where the accessing user with his credentials has no rights to write to. This is handled by the accessed storage and not by owncloud.
I am only talking on full mounts and not about possible different subfolder permissions !

Because we do not see this write disability, a user might try to write into and gets a error message that does not give him the proper cause. If I remember correctly, if we have a shared read only mount, the error message is correct and helpful.

Thinking further, this is also true for the user at the client who has no clue why he can´t write to a mount - and if he does he can do into the client´s filesystem but the data never gets synced.

I do not know if a read only marker for a read only mount gets currently already propagated to the client. If not this should be done and if yes this FR is only an extension if set on the mount. But anyways this is a part of core to do so and a part of the client to take an action which is to be determined.

**Proposal:**
Adding the ability to mark a storage as read only.

@PVince81 @SamuAlfageme

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by PVince81** [comment]
Adding a read-only checkbox might actually be a good idea.

The way I see it is that we'd apply the permissions mask storage wrapper on top of that storage to return read-only permissions. So only `isReadable()` would return true but `isCreatable()`, and `isUpdateable()` would return false. I expect the other layers of ownCloud to be able to adjust accordingly and hide write perms everywhere, just like for read-only shares.

**Comment by mmattel** [comment]
Based on #29999, if implemented: 
1. If a mount is setup, test if you have write access.
2. If not, propose to set the ready only switch automatically.

**Comment by PVince81** [comment]
Sounds good.

For the technical implementation, whenever the mount has been flagged as "read-only", use the "PermissionsMask" storage wrapper and apply it on this storage.

Some example on how to apply a storage wrapper based on mount config can be found here where we do it for NFD compatibility: https://github.com/owncloud/core/blob/v10.0.3/lib/private/legacy/util.php#L194.

So the tasks would be as follows:

- [ ] add new setting in the advanced dropdown options in the external storage config UI
- [ ] when setting is set, apply the `PermissionsMask` storage wrapper following the example from https://github.com/owncloud/core/blob/v10.0.3/lib/private/legacy/util.php#L194 and make it so that the permissions are read-only
- [ ] add some auto-detection for write access when saving a storage as per https://github.com/owncloud/core/issues/29873#issuecomment-354601270: details needs to be discussed as some storages might require writing an actual file for detection while others just need reading this info from somewhere

**Comment by mmattel** [comment]
For your item 3, when I did the test with **ftp** (see: https://github.com/owncloud/core/issues/29999#issuecomment-356313876) you can set permissions for files and directories seperated. Knowing this, a test should check both and if one fails, autodetection should go for read only...

**Comment by mmattel** [comment]
@PVince81 any update on this?

**Comment by mmattel** [comment]
@PVince81 any update on this?

**Comment by PVince81** [comment]
not scheduled yet

**Comment by TJHeeringa** [comment]
@PVince81 any update on this?

**Comment by PVince81** [comment]
This is currently not a proirity and we haven't received any contribution with that feature.

If anyone feels like implementing it, I've put some hints above.

**Comment by TJHeeringa** [comment]
I have completed the first two tasks, but I have not figured out how to write tests yet. I did find some documentation, but hints, like for the second task, would be appreciated.

I want to push my branch, so you can see whether I need to do more, but I get a permission denied. Who do I need to ask to grant me permission to do so?

**Comment by phil-davis** [comment]
I do not have the jedi powers to grant you branch create access in the owncloud repo. @PVince81 or @DeepDiver1975 can do that.

But you can contribute from your own fork, and make PRs from there - CI will run fine. The process is like:

- press the "Fork" button on GitHub to make a fork of core repo.
- clone the forked repo:
```
git clone https://github.com/my-name/core.git
```
- make a "remote" name that points to the original repo, for future convenience:
```
git remote add upstream https://github.com/owncloud/core.git
git remote -v
```
- make your code changes in some branch off master:
```
git checkout master
git checkout -b stuff
```
- make the changes, commit... and ``git push`` which will go up to you fork by default
- go to GitHub and it will suggest making a PR to the original repo

**Comment by mmattel** [comment]
@TJHeeringa may I ping you again ?

**Comment by mmattel** [comment]
:sound: Ping
