### ISSUE TITLE
Description text in integrity.excluded.files in config.php.sample is wrong

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#29880]
Referencing, both merged:
https://github.com/owncloud/core/pull/29126 (Move excluded files to config array)
https://github.com/owncloud/core/pull/29460 ([stable10] Move excluded files to config array)

```
/**
 * Exclude directories from the integrity checker command
 */
'integrity.excluded.files' =>
```
Descriptiont text should be ``Exclude files from the integrity checker command`` (directories -> files)

@PVince81 @sharidas

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by sharidas** [comment]
@mmattel This change is available: https://github.com/owncloud/core/pull/29570 and backport to stable10 https://github.com/owncloud/core/pull/29572

**Comment by phil-davis** [comment]
PR https://github.com/owncloud/core/pull/29570 and
backport https://github.com/owncloud/core/pull/29572

Is the description text somewhere else also?

**Comment by mmattel** [comment]
THX 😄 
Can we close because both PR´s have been merged?
