### ISSUE TITLE
FTPs won't mount

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#29886]
Ref https://github.com/owncloud/core/issues/9630

I tried to mount a ftps via ftp connector in ownCloud and failed.

I can connect to the mount via nautilus "connect to server" ftps

![ftp2](https://user-images.githubusercontent.com/24212810/34122567-35766f76-e42d-11e7-80a9-feab9bb4dd9f.png)

I can connect from the system ownCloud is running on via ftp-ssl

![ftp3](https://user-images.githubusercontent.com/24212810/34122641-72e586b2-e42d-11e7-928e-a7caba1d085d.png)

But I can't mount it in the web UI. The Flag is Red no matter what I do.

![ftp](https://user-images.githubusercontent.com/24212810/34122558-272a6c6a-e42d-11e7-9085-180ad7afa038.png)

I tried to import the certificate and it was successful.

![certs](https://user-images.githubusercontent.com/24212810/34122869-18fb5bb2-e42e-11e7-9caa-9461c9b137ad.png)

**Comment by Albanosdes** [comment]
I have the same issue. I opened two topics on the owncloud forums about that.
[Topic 1](https://central.owncloud.org/t/ftp-external-storage-issue-no-logs/9997)
[Topic 2](https://central.owncloud.org/t/ftp-external-storage-not-working/10852)

**Comment by patrickjahns** [comment]
This is probably related to https://github.com/owncloud/files_external_ftp/issues/17 

Can you guys test if using a subdirectory works for you?

**Comment by Albanosdes** [comment]
It does. Slow as hell, but it does work. Thanks for the tip.

**Comment by patrickjahns** [comment]
closing here - further discussion should be in owncloud/files_external_ftp#17
