### ISSUE TITLE
[Feature Request] Retype admin password before setting it

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#29901]
There should be a "retype your password" field when setting the administrator password for owncloud.

The possibility that you can get a typo twice is low.

**Comment by PVince81** [comment]
since we already have a PR, set to "planned" for 10.0.9

**Comment by phil-davis** [comment]
Merged to master 2019-02-14. Backport to stable10 in progress 2019-02-15. So this should be in the next release after 10.1 (whatever release number it gets)

**Comment by phil-davis** [comment]
Also note related issue https://github.com/owncloud/user_management/issues/147 in user_management for the case when the admin creates a new user with just an email address, and the new user sets their first password.
