### ISSUE TITLE
Move from bower to yarn

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#29906]
Bower is dead - long live yarn

**Comment by PVince81** [comment]
seems yarn also uses package.json https://bower.io/blog/2017/how-to-migrate-away-from-bower
 
How to migrate away from Bower? · Bower blog
last line says "But initially, the only change required in code is to change any reference to bower_components with node_modules/@bower_components (though you can link it somewhere else in postinstall script)."
our bower_components is core/vendor
if symlinking is ok we could symlink the folder to there

**Comment by PVince81** [comment]
adding @felixheidecke for a second opinion

**Comment by PVince81** [comment]
PR https://github.com/owncloud/core/pull/29908

**Comment by PVince81** [comment]
lets also do it for stable10: https://github.com/owncloud/core/issues/33651
