### ISSUE TITLE
[Feature Request] config report: star out some mail settings

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#29912]
This FR is about that some mail settings in the **config report** gets starred out automatically.

**Example:**

```
"mail_smtpmode": "smtp",
        "mail_from_address": "****",
        "mail_smtpsecure": "tls",
        "mail_domain": "****",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "****",
        "mail_smtpport": "587",
```
**Affected settings:**
``mail_from_address`` 
``mail_domain`` 
``mail_smtphost``

@PVince81

**Comment by PVince81** [comment]
=> https://github.com/owncloud/configreport

PRs welcome.

**Comment by mmattel** [comment]
Recreated in configreport, closing here.

**Comment by mmattel** [comment]
I reopen this, because from that what I have seen, configreport has an automation in https://github.com/owncloud/configreport/blob/master/lib/ReportDataCollector.php#L263 for starring out values, based on data coming from core.

The change in core is to be applied in: 
``core/lib/private/SystemConfig.php`` ``class SystemConfig`` ``protected $sensitiveValues``

**Comment by PVince81** [comment]
Makes sense. Can you submit a PR that adds the fields in question ?

**Comment by mmattel** [comment]
Closing, PR´s merged
