### ISSUE TITLE
App icons break when apps are moved to a custom app directory.

### ISSUE THREAD

**Issue by settermjd** [owncloud/core#29917]
Currently, you can create multiple app directories, in addition to ownCloud's core app directory (`app`), and move apps between them. However, when apps are moved, the app icons disappear, as the app directory's location doesn't update to match the new directory. 

In the following screenshots, you can see that the icons for Gallery and Email are broken, as they're prefixed with `gallery/` instead of `apps2`: 

<img width="279" alt="top-nav-menu-missing-app-icons" src="https://user-images.githubusercontent.com/196801/34163296-a6d38cc2-e4d6-11e7-82c5-b129256df382.png">

<img width="475" alt="hardcoded-app-icon-directory" src="https://user-images.githubusercontent.com/196801/34163295-a6b31398-e4d6-11e7-8d67-f3d2a9c9fa49.png">

### Steps to reproduce

1. Enable maintenance mode
2. Disable the apps that you want to move
3. Move the apps from the old to a new apps directory
4. Add a new app directory in `config/config.php`
5. Enable the apps
6. Disable maintenance mode

### Expected behaviour

The icon links should not point to the new location.

### Actual behaviour

The icon links break as they stay pointed to the original location.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:** 7.0

**ownCloud version:** 10.0.3.3

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** git clone

**The content of config/config.php:**

```
{
    "system": {
        "data_directory": "\/mnt\/data\/files",
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/custom",
                "url": "\/custom",
                "writable": true
            },
            {
                "path": "\/var\/www\/owncloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "dbtype": "mysql",
        "dbhost": "db:3306",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "trusted_domains": [
            "localhost"
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/mnt\/data\/files",
        "overwrite.cli.url": "http:\/\/localhost\/",
        "version": "10.0.3.3",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "ocawseccehch",
        "redis": {
            "host": "redis",
            "port": 6379
        },
        "filelocking.enabled": "false",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": "0",
        "default_language": "en",
        "htaccess.RewriteBase": "\/",
        "ldapIgnoreNamingRules": false,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis"
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.6
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.0
  - encryption: 1.3.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.2
  - notifications: 0.3.1
  - oauth2: 0.2.0
  - provisioning_api: 0.5.0
  - rainloop: 5.0.5
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
  - user_ldap: 0.9.1
Disabled:
  - external
  - files_antivirus
  - theme-example
  - user_external
```

**Are you using external storage, if yes which one:**

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**

**Comment by VicDeo** [comment]
@settermjd Could you try flushing the redis cache?

**Comment by settermjd** [comment]
Shall do.

**Comment by mmattel** [comment]
I am also using redis. Just rebootet my server due to updates, Gappery and Music has bee moved to apps2.
![image](https://user-images.githubusercontent.com/3321281/34719078-86d7efd0-f539-11e7-883c-8140de69142e.png)
Icons are still missing.

**Comment by settermjd** [comment]
I tried it on a system without a cache and didn't have the same problem. Thanks for suggesting the cache as a possible solution @VicDeo.

**Comment by settermjd** [comment]
Using [the official ownCloud Docker build](https://doc.owncloud.org/server/latest/admin_manual/installation/docker/), I just created a new app directory, moved one of the installed apps there, then restarted the Redis container and the links were updated properly.

**Comment by VicDeo** [comment]
This is probably is not possible with our docker image, but in general  Redis cache could be flushed from CLI with redis-cli tool:
SELECT **dbIndex**
FLUSHDB

Where **dbIndex** - number of Redis database where cache is stored, zero by default according to https://github.com/owncloud/core/blob/master/config/config.sample.php#L964


https://redis.io/commands/select
https://redis.io/commands/flushdb
