### ISSUE TITLE
UI tests - waiting time after folder creation is too short

### ISSUE THREAD

**Issue by shresthamoheet** [owncloud/core#29926]
### Steps to reproduce
1. 	Try to run UI test createFolders.feature:23

### Expected behaviour
A folder with the name "top-folder" should be created and UI should open the folder "top-folder"
### Actual behaviour
A folder with the name "top-folder" is created but UI is unable to open the folder "top-folder" due to too short time

**Comment by individual-it** [comment]
fixed by #29978
