### ISSUE TITLE
Unable to unshare a federated share when the other federated Owncloud server is gone.

### ISSUE THREAD

**Issue by rontrompert** [owncloud/core#29924]
### Steps to reproduce
1. A user on server B shares a file with a user on server A using federated sharing
2. Server B is decommissioned. Data is not thrown away but the server is just turned off. 
3. The user on server A is not able to throw the file away or unshare the file. Both actions result in the error message "Error deleting file ...."

### Expected behaviour
You should be able to recover from this on the user side by just unsharing the file regardless of whether server B is available or not. 

### Actual behaviour
The user on server A is not able to other throw the file away or unshare the file. Both actions result in the error message "Error deleting file ....". The sync client also stops syncing. 

### Server configuration
**Operating system**:
CentOS7
**Web server:**
apache 2.4.6

**Database:**
Galera MariaDB 25.3.20

**PHP version:**
7.1 

**ownCloud version:** (see ownCloud admin page)
10.0.3

**Updated from an older ownCloud or fresh install:**
Updated from older version

**Where did you install ownCloud from:**
rpm

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```
{
    "system": {
        "instanceid": "ocff17e49795",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "surfdrive.surf.nl"
        ],
        "datadirectory": "\/ring\/fs\/surfdrive\/data\/",
        "dbtype": "mysql",
        "version": "10.0.3.3",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1:6033",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "session_lifetime": 7776000,
        "session_keepalive": true,
        "enable_previews": true,
        "maintenance": false,
        "overwritehost": "surfdrive.surf.nl",
        "overwriteprotocol": "https",
        "mail_domain": "surfdrive.surf.nl",
        "cache_path": "\/ring\/fs\/surfdrive\/cache\/",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 14",
        "activity_expire_days": "14",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "192.168.120.3",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "filelocking.enabled": "true",
        "trusted_proxies": [
            "192.168.120.1"
        ],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR",
            "HTTP_FORWARDED_FOR"
        ],
        "minimum.supported.desktop.version": "2.3.0",
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "preview_max_filesize_image": 100,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap"
        ],
        "log_type": "syslog",
        "log.syslog.format": "{%app%} %message% [%reqId%]",
        "loglevel": "1",
        "logtimezone": "Europe\/Amsterdam",
        "log_authfailip": "true",
        "cron_log": true,
        "installed": true,
        "customclient_desktop": "https:\/\/www.surfdrive.nl",
        "customclient_android": "https:\/\/www.surfdrive.nl",
        "customclient_ios": "https:\/\/www.surfdrive.nl",
        "blacklisted_files": [
            ".htaccess"
        ],
        "appstoreenabled": false,
        "has_internet_connection": false,
        "supportedDatabases": [
            "mysql",
            "pgsql",
            "oci"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "filesystem_check_changes": 0,
        "asset-pipeline.enabled": true
    }
}

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```
Enabled:
  - activity: 2.3.6
  - admin_audit: 0.8.1
  - announcementcenter: 1.2.0
  - audioplayer: 2.2.1
  - configreport: 0.1.1
  - customgroups: 0.3.5
  - dav: 0.3.0
  - diagnostics: 0.1.2
  - enterprise_key: 0.1.3
  - external: 1.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_clipboard: 0.6.2
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 16.0.2
  - music: 0.5.4
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - theme-surfdrive: 1.0.0
  - user_shibboleth: 3.1.1
Disabled:
  - comments
  - encryption
  - files_antivirus
  - files_external_ftp
  - files_ldap_home
  - firewall
  - firstrunwizard
  - guests
  - impersonate
  - market
  - objectstore
  - password_policy
  - richdocuments
  - sharepoint
  - systemtags
  - systemtags_management
  - templateeditor
  - twofactor_totp
  - updatenotification
  - user_external
  - user_ldap
  - windows_network_drive
  - workflow

**Are you using external storage, if yes which one:** local/smb/sftp/...
Nope 

**Are you using encryption:** yes/no
Nope 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Nope

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox

**Operating system:**
Ubuntu 16.04 LTS
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by hodyroff** [comment]
could you check it out with 10.0.4 as well, please?

**Comment by rontrompert** [comment]
Hi. I have just tested 10.0.4. It works fine now!!! Thanks!
