### ISSUE TITLE
Grouped link share

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29938]
New design for public link shares:

- a link share is a set of permissions (permissions, expiration, password, etc) represented by a single oc_share entry
- a link share can have one or multiple recipients
    - each recipient receives a separate token: allows revocation of specific recipients
    - new table to map tokens to oc_share entries
- UI allows entering multiple email addresses but internally creates multiple tokens
- UI must display the grouped share as an expandable entry:
    - when collapsed, only show the grouped share name
    - when expanded, show every recipient by email
    - when no email, let the user specify an arbitrary name (stored along with token in DB)
- recipients can be added later, and receive email notification
    - personal note can be added when adding recipients (not sure if we should store this one to be able to view it again)

This makes it possible to manage the permissions of a given link share and for example set the expiration date to a later point for delayed projects, doing so in a single location. No need to manually send multiple link shares and set expiration individually.

Ref: personal note ticket https://github.com/owncloud/core/pull/29935 https://github.com/owncloud/core/issues/29937

@felixheidecke @pmaier1 let me know if I forgot anything

**Comment by PVince81** [comment]
- [ ] technical concept
    - [ ] UI changes
    - [ ] examine API endpoint changes
    - [ ] DB changes: new table, mapping, classes

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @rullzer.

**Comment by pmaier1** [comment]
Ref: Requirements for public link share mail input field https://github.com/owncloud/core/issues/29695
