### ISSUE TITLE
Expose link share email template through APIs

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#29937]
Provide a way for clients to retrieve the email template through public APIs.

1) Public API endpoint to retrieve preformatted email template with filename, expiration date as input

2) Public API endpoint to send out email with body (tech debt from ajax/share.php which needs to be moved anyway, see https://github.com/owncloud/core/issues/22209)

This is a follow up of https://github.com/owncloud/core/pull/29935.

I suggest providing a new OCS Share API endpoint for that.

Note that only plain text messages are supported. Not sure if we should support HTML emails as it would require clients and web UI to provide basic formatting.

@michaelstingl @felixheidecke @pmaier1

**Comment by PVince81** [comment]
Also not discussed so far: email subject ?

**Comment by PVince81** [comment]
The email endpoint could potentially be abused to send non-share-related emails to anyone... I don't like this. We could force it to have at least the share id, but still...

**Comment by PVince81** [comment]
No, this feature is not really about sending invitation emails.
It's about adding email recipients to an existing link share (see "grouped tickets" concept https://github.com/owncloud/core/issues/29938). So the API endpoint would simply be the same like the one that allows you to add more recipients to the link share, with the option of specifying a personal note. The endpoint will then send an email.

**Comment by michaelstingl** [comment]
> Also not discussed so far: email subject ?

For "**1. Public API endpoint to retrieve…**" subject should be retrieved from oC server too. If I share a link with my mobile mail client, subject will be used. If I share a link with a messaging application, only the body will be used.

**Comment by PVince81** [comment]
@michaelstingl good point. Indeed mobile will use the local mail client, so the subject should be available too.

- [ ] include subject in template response

**Comment by SamuAlfageme** [comment]
Could be used to solve https://github.com/owncloud/client/issues/6196

**Comment by SamuAlfageme** [comment]
Duplicates Hackweek's https://github.com/owncloud/core/issues/29769 maybe?

**Comment by pmaier1** [comment]
For https://github.com/owncloud/core/pull/29935 I would also be happy with just "injecting" a note to the notification mail. Not 100% sure if users want to edit the whole template there or if oC should just provide an option to insert a personal note to an existing template (and templates can be edited elsewhere, e.g. templateeditor).

**Comment by PVince81** [comment]
moving to planned

**Comment by pmaier1** [comment]
We don't need to make the full template editable but the API should be capable of injecting a personal note as in the WebUI https://github.com/owncloud/core/issues/29696.

**Comment by PVince81** [comment]
moving to triage. personal note is implemented in 10.0.8
