### ISSUE TITLE
 Due to Dependabot, Travis queue waiting time increased 

### ISSUE THREAD

**Issue by karakayasemi** [owncloud/core#29947]
Dependabot is creating so much PR these days, and a job arriving at Travis's queue results in almost 1 day. This situation slows down the development quite a bit. 
@DeepDiver1975, @PVince81 what are your thoughts?

**Comment by phil-davis** [comment]
Make dependabot run only on weekends, Christmas and NewYear's Day?

Actually weekends would be good - e.g. if it just looked for versions to bump at 1am every Saturday.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by PVince81** [comment]
Sounds like a good idea. I don't think there is much value running the bot every day.

Maybe even once a month would be fine if we can reach a point where we do a minor release every month. Then the bot would need to run at the end of a release and beginning of a new one so we can merge dep updates right away.

**Comment by karakayasemi** [comment]
@DeepDiver1975 are we going to do something about this?

**Comment by DeepDiver1975** [comment]
Already set from daily to weekly
