### ISSUE TITLE
[Feature Request] enable the notification app for command line access

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#29965]
This Feature Request is about to enable the notifications app to be accessed via commadn line.

**Idea behind:**
We could send notifications to users or groups.

**Examples:**
``./occ notification:send user_1 user_2 „Notification Text“``
``./occ notification:send group_1 „Notification Text“`` 
``./occ notification:send  --json-import-file:/path/userlist.json „Notification Text“``
``./occ notification:send  --json-import-file:/path/userlist.json --textfile:/path/textfile``

**Benefit:**
This is especially useful when you plan maintenance tasks
See also https://github.com/owncloud/core/issues/29960 ([Feature Request] extend ./occ user to list logged on users)
Having that, this could be scripted. First you identify possible browser logged on users, then you send them a notificatiopn about an upcoming maintenance.
Because these kind of notifications can only occur when an OS admin has command line access, we can be sure that here is no „accidentially misuse“...

**Comment by hodyroff** [comment]
Sounds like a good tool for SysAdmins indeed. We should take it into account when we further build out the role concepts.

**Comment by mmattel** [comment]
Closing, because there is a occ notification command available but was not documented.
Fixed in the 10.0.8 documentation.
