### ISSUE TITLE
Username migration

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#29993]
Implementation discussion to solve issues necessary to achieve: https://github.com/owncloud/core/issues/29503

I would like to limit the scope of this ticket to what is necessary for altering the username of a user. Conceptual / architectural changes should be in #29503.

Tables would need to be updated to alter the username:
 - addressbooks.principaluri
 - authtoken.uid & .login_name
 - calendarchanges.uri
 - calendars.principaluri
 - calendarsubscriptions.principaluri & .uri
 - cards.uri & carddata (BLOB)
 - cards_propers.value
 - comments.actor_id
 - comments_read_markers.user_id
 - dav_shares.principaluri
 - group_admin.uid
 - share.uid_owner
 - share.uid_initiator
 - share.share_with && share_type = 0
 - share_external.user
 - share_external.owner
 - ldap_user_mapping.owncloud_name
 - more.....!!

Should we also unify the column names: `uid` ?? Would require some code changes to map to the new column names.

Open questions:
 - What happens with synchronised federated address-books that contain the userid?
 - What happens to federated shares that rely on the userid in the instance?
 - We need to fix userid in the system addressbook vcard data

Code-wide, we should implement this as its own service that can be tested thoroughly. We can call this service via an occ command to run the migration manually, or maybe at some stage migrate all the int account.ids using an upgrade migration. Need to consider the upgrade time required here for instances with >100k users.

**Comment by tomneedham** [comment]
We should still keep the login name in the accounts table which is used for mapping purposes but we should define the use of this carefully.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by TheCellMC** [comment]
Is this still being worked on?
