### ISSUE TITLE
Include an html body in the 403 'unsupported client version' error

### ISSUE THREAD

**Issue by ckamm** [owncloud/core#30019]
From owncloud/client#6262.

The suggestion is that the user should be told the minimum required version, as well as - potentially - the download links. This is information that could come from the server.

The most straightforward way from the client's point of view would be to send a text/html body along with the error reply, similar to the "ip needs to be added as trusted domain" error. The client will show this message to the user.

**Comment by PVince81** [comment]
It is possible that the client version error is thrown "too hard" and doesn't reach the code path that embeds the error into a page. To be investigated.
