### ISSUE TITLE
GET user details does not show free, used and total under quota tag

### ISSUE THREAD

**Issue by tummimadhu** [owncloud/core#30023]
GET user details does not show free, used and total under quota tag

commands used

 curl -u aticara:test123 -X GET "http://ip_address/ocs/v1.php/cloud/users/user3" -H "OCS-APIRequest: true"	 
 curl -u aticara:test123 -X GET  'http://ip_address/ocs/v1.php/cloud/users/aticara' -H "OCS-APIRequest: true"

The Data is shown only for Admin user under quota tag i.e

![image](https://user-images.githubusercontent.com/6253033/34638677-fda14322-f2f6-11e7-901a-f343e73e71fe.png)

But for user it does not show fields under quota,
![image](https://user-images.githubusercontent.com/6253033/34638683-18e7973a-f2f7-11e7-8c3c-e448a16e9cc6.png)

Any Idea how to get these fields for quota in user as well???

Used the link for testing with Curl
https://docs.nextcloud.com/server/11/admin_manual/configuration_user/user_provisioning_api.html

Thanks in Advance.

**Comment by PVince81** [comment]
Can you confirm that the user in question has already logged in ? I heard some while ago that the API might only return values for users who already log in.

**Comment by tummimadhu** [comment]
yes it works when user is already logged in and has added some files to his account.

You can close this issue.

Thanks
Madhu
