### ISSUE TITLE
trusted_domain problem

### ISSUE THREAD

**Issue by kisnoge** [owncloud/core#30025]
Hello, i tried many way but not working with client pc
1. I'm sure my ip is correct setup in config.php, and log file on owncloud server also record my ipaddress connected.

2.my config.php is stored in /var/www/owncloud/config, is the dir correct ?

3. my client os is windows10 with chrome and ie

how to fix the problem?

**Comment by DeepDiver1975** [comment]
Please move over to https://central.owncloud.org/ for general questions on how to setup owncloud. THX
