### ISSUE TITLE
Add "mod_headers" as required Apache module (instead of recommended)

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/core#30042]
Since Apache removes "WWW-Authentication: Bearer" headers by default (see https://github.com/owncloud/oauth2/issues/49#issue-235526402) - the Apache `mod_headers` together with some rules (like https://github.com/owncloud/core/blob/master/.htaccess#L65) need to be in place for OAuth2 to work. 

The docs state Headers as an "Additional recommended modules" while it should be present as "Required for ownCloud to work correctly" in https://doc.owncloud.com/server/10.0/admin_manual/installation/source_installation.html#additional-apache-configurations

cc/ @DeepDiver1975 @PVince81

**Comment by DeepDiver1975** [comment]
In case you don't want to use oauth there is no need in having a hard requirement on this.

**Comment by PVince81** [comment]
Are there any setups out there where one would purposefully want to get rid of mod_headers maybe for security reasons ?
