### ISSUE TITLE
OC 10.0.4 - Error while trying to create shared mount

### ISSUE THREAD

**Issue by pgr-sikkin** [owncloud/core#30063]
**### Steps to reproduce**
1. Start the OwnCloud client
2. Look at the OwnCloud server log
3.

**### Expected behaviour**
Empty log

**### Actual behaviour**
See below (install)

### Server configuration
**Operating system**:
Debian GNU/Linux 9.3 (stretch)

**Web server:**
Server version: Apache/2.4.25 (Debian)
Server built:   2017-09-19T18:58:57

**Database:**
Server version: 5.7.20 MySQL Community Server (GPL)

**PHP version:**
PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )

**ownCloud version:** (see ownCloud admin page)
version: 10.0.4.4

**Updated from an older ownCloud or fresh install:**
Manual restore (application and db) after crash disks (lost of data folders) 
Data are restored by -sequential - clients upload

**Where did you install ownCloud from:**
wget --no-verbose https://download.owncloud.org/community/owncloud-x.x.x

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**The content of config/config.php:**
{
    "system": {
        "instanceid": "occ4f1f16ebf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.xxxx.com",
            "cloud.xxxx.com"
        ],
        "datadirectory": "DATA_DIR\/cloud\/data",
        "logfile": "WWW_DIR\/cloud\/cloud.log",
        "dbtype": "mysql",
        "version": "10.0.4.4",
        "dbname": "cloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "loglevel": 3,
        "installed": true,
        "theme": "xxxxxxxx",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_domain": "xxxx.com",
        "mail_smtphost": "mail.xxxx.com",
        "mail_smtpsecure": "xxxx",
        "mail_smtpport": "xxxx",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "xxxxxxxxx",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "enable_avatars": true,
        "filelocking.enabled": true,
        "operation.mode": "clustered-instance",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0
        },
        "mail_smtpauth": 1
    }
}
**List of activated apps:**

Enabled:
  - calendar: 1.5.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.3
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.3
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - activity
  - encryption
  - external
  - theme-example
  - user_external

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No (LDAP setup has been deleted as not working during the restore part)

### Client configuration
**Browser:**
No relevant

**Operating system:**

#### Web server error log
xxx.yyy.zzz -xxxx.yyyy [09/Jan/2018:09:49:19 +0000] "PROPFIND /remote.php/dav/files/xxxx.yyyy/ HTTP/1.1" 207 1563 "-" "Mozilla/5.0 (Macintosh) mirall/2.4.0 (build 8836)"

#### ownCloud log (data/owncloud.log)
{"reqId":"e5a7d9d4-8cb5-4ab8-be2f-46e31ef2b349","level":3,"time":"2018-01-09T09:49:19+00:00","remoteAddr":"xxx.yyy.zzz.23","user":"xxxx.yyyy","app":"no app in context","method":"PROPFIND","url":"\/remote.php\/dav\/files\/xxxx.yyyy\/","message":"Error while trying to create shared mount"}

#### Browser log
No relevant

**Comment by PVince81** [comment]
1) Get the user id of the affected user
2) Get the list of groups the user is in
3) `select * from oc_share where share_with=$userId`
4) `select * from oc_share where share_with in ($group1, $group2, ...)`

See if there is something suspicious, you might see the "xxxx.yyyy" entry from the message. Maybe something is broken somewhere.

**Comment by pgr-sikkin** [comment]
Hi Vince (?),

Thank you for your answer and the insights.
I have to clean up the `oc_share` as the way to rebuild the data folders is not exactly the historical structure to build it.
I am also looking the `uid_initiator` field which contains the historical information and need to be updated or cleaned.

**Comment by PVince81** [comment]
What do you mean with cleaning ? If you have inconsistent data or if you manipulated data entries then it is likely that it will break something

**Comment by pgr-sikkin** [comment]
Yes, you are right for a general assumption.
I have searched thru Google and didn't found any suitable answer to restore the data folders when you have application and db.
As I have to rebuild the data folders, I have cleaned some tables (`oc_files`) to start with an empty db except for the users (their password and groups). 
Until now, I find few inconsistencies like 
  - as I didn't backup the `oc_activity` table, due to its size, I was not able to rebuild it (I don't how to use the `database.xml` file only), so activity app has been disabled
  - `oc-jobs` table is missing `last_checked` column, and I cannot figure out why?
I solve manually (and slowly) the issues case by case.

**Comment by pgr-sikkin** [comment]
It appears that the different upgrade (from OC 6.x to 10.0.4) didn't migrate correctly the DB (mysql).
At least, the `oc_jobs` didn't have the right number of columns (`last_checked`, `reserved_at`, `execution_duration`) or with wrong size (255 instead of 4000) of `argument`.  

I am restarting from a full clean version 10.0.4.4 ...
