### ISSUE TITLE
Owncloud 10.0.4 on opensuse installs even if dependicies is not fullfilled

### ISSUE THREAD

**Issue by tcjtomas** [owncloud/core#30069]
### Steps to reproduce
1. update owncloud 9.* to 10.0.4 on opensuse LEAP 42.3
2.
3.

### Expected behaviour
owncloud should not update as php 5.6.0 is needed. OpenSuSE is currently installed with php 5.5.14.

### Actual behaviour
owncloud is updated but unable to run as php 5.6.0 is needed.
--snip--
This version of ownCloud requires at least PHP 5.6.0
You are currently running 5.5.14. Please update your PHP version.
--end snip--

### Server configuration
**Operating system**:
OpenSuSE LEAP 42.3
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
php 5.5.14
**ownCloud version:** (see ownCloud admin page)
owncloud 10.0.4
**Updated from an older ownCloud or fresh install:**
Update from 9.?
**Where did you install ownCloud from:**
http://download.owncloud.org/download/repositories/10.0/openSUSE_Leap_42.3/ce:10.0.repo
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
Can't login as descriped above.

**Comment by PVince81** [comment]
@crrodriguez please have a look

**Comment by crrodriguez** [comment]
duplicate. leap does not have the needed PHP versions to work at all. one can however workaround this problem by installing php7 from backports.

zypper ar -f -r http://download.opensuse.org/repositories/devel:/languages:/php/openSUSE_Leap_42.3/devel:languages:php.repo
zypper ref
zypper dup -r devel_languages_php

**Comment by crrodriguez** [comment]
that said.. leap 42.3 includes php7.. though and oldish version.. if you wish you could install that and it should work. 

**_Closed: reason, manual should be read before update, operator error. there is no PHP dependencies in place for owncloud 10, as the -deps-php were dropped _**

**Comment by tcjtomas** [comment]
I Will remove owncloud from my repo till PHP is up to date in Leap.Den 15. jan. 2018 20.32 skrev Cristian Rodríguez <notifications@github.com>:that said.. leap 42.3 includes php7.. though and oldish version.. if you wish you could install that and it should work.
_Closed: reason, manual should be read before update, operator error. there is no PHP dependencies in place for owncloud 10, as the -deps-php were dropped _
