### ISSUE TITLE
Deprecate old /avatar/<user>/<size> endpoint for newer WebDAV API

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/core#30062]
I was tracking down an issue on the client (https://github.com/owncloud/client/issues/6279#issuecomment-356225419) when I found out the webUI is still using the old `/avatar/<user>/<size>` everywhere:

- "Settings > General" panel
-  Page Header
- Private (internal) shares

This is a proposal to deprecate that old API in favor of the newer (>10.0) WebDAV API https://github.com/owncloud/core/pull/26872 for the sake of keeping just one resource for avatars core-wide. 

cc/ @DeepDiver1975

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by PVince81** [comment]
@DeepDiver1975 kill in OC 11 ?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 kill in OC 11 ?

yes
