### ISSUE TITLE
[Feature Request] Propagate mount write/update permissions to the client

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#30070]
Realted to:
https://github.com/owncloud/core/issues/29873 ([Feature Request] Mark mount as read only in the mount settings)
https://github.com/owncloud/client/issues/6252 ([Feature Request] Define actions on read only mounts)

We should let the client proactively know which rights the mount has to properly define actions on.
Especially that the client can not write back (is_creatable, is_updatable).
We already have mounts where you can read only (ro-share).

Without propagating this, the client thinks he can write back and fails.
The user is confused as he has no clue or forgotten why this is the case.

An implementation would enable the client to define actions based on this info.

@PVince81 @SamuAlfageme

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by SamuAlfageme** [comment]
One more use-case to WebSockets -> https://github.com/owncloud/client/pull/6195

**Comment by PVince81** [comment]
Most is already in place: there's an `oc:permissions` Webdav attribute that clients likely already use when dealing with received shares and read-only status. What we need to do however is find a way for storages to provide said read-only information when technically possible. And as a fallback, allow the admin to tag a mount as read-only as per https://github.com/owncloud/core/issues/29873. Doing so would simply return read-only permissions through all the APIs and also through `oc:permissions`.

I'd vote for closing this ticket in favor of https://github.com/owncloud/core/issues/29873 as we don't need any extra attributes or APIs.

**Comment by mmattel** [comment]
Question, just don´t know it:
The ``oc:permissions`` Webdav attribute is already handed over to the client as part of the mount info?
If this is the case, we can close this issue, because then it is just upon the client to use the attribute.

**Comment by PVince81** [comment]
@mmattel "oc:permissions" is fetched and used by the client in general, not only for mounts.

**Comment by mmattel** [comment]
@PVince81 Thanks for clarification 
From my POV, we can close this ticket as suggested and continue in #29873.

**Comment by SamuAlfageme** [comment]
@mmattel yup, like @PVince81 said `oc:permissions` are requested as part of the client's `PROPFIND`

```xml
  <d:response>
    <d:href>/remote.php/dav/files/admin/ownCloud/</d:href>
    <d:propstat>
      <d:prop>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <oc:size>678556</oc:size>
        <oc:permissions>RMCK</oc:permissions>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
```

You can check all the values the permissions mask can have in https://doc.owncloud.org/desktop/2.4/architecture.html#server-side-permissions (and the Sabre connector equivalent in https://github.com/owncloud/core/blob/master/apps/dav/lib/Connector/Sabre/Node.php#L317-L347)

An example on how the client uses these would be how the `M` (the "mount" one actually) value to trigger confirmation for received mountpoints; see: https://github.com/owncloud/client/pull/5340

![mount](https://user-images.githubusercontent.com/2644445/34763187-86bca05c-f5ea-11e7-8ddc-b55b9a65d595.png)
