### ISSUE TITLE
FR: Hide CORS settings in User settings tab

### ISSUE THREAD

**Issue by haukman** [owncloud/core#30087]
### Steps to reproduce
1. Log in to ownCloud as a regular user
2. Go to Settings -> Security

### Expected behaviour
CORS setting should not be displayed for a regular user (maybe only an Admin option?)

### Actual behaviour
Every User can configure it:

![grafik](https://user-images.githubusercontent.com/25486818/34767581-bed499aa-f5f8-11e7-8b8f-f36e9adef5aa.png)

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
10.0.4

@pmaier @PVince81 
Fyi: @michaelstingl

**Comment by DeepDiver1975** [comment]
> CORS setting should not be displayed for a regular user (maybe only an Admin option?)

no - this is a user setting

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mmattel.

**Comment by michaelstingl** [comment]
Option to hide such stuff? Make it an app? I can imagine scenarios where none of the users will ever use this setting.

**Comment by DeepDiver1975** [comment]
> Option to hide such stuff?

nothing I could imagine - maybe chat with someone who is more UX-ish as I am



> Make it an app?

it's an integratal core component 



> I can imagine scenarios where none of the users will ever use this setting.

sure - maybe move it down to the end as last item?

**Comment by SamuAlfageme** [comment]
Only display the title and allow to unroll? - using a [`<details>`](https://www.w3schools.com/tags/tag_details.asp) element maybe:

 <details>
  <summary><b>CORS</b>.</summary>
  <ul>
  <li>CORS things</li>
  <li>More CORS things</li>
  </ul>
</details> 

<br>
Not supported on MS browsers tho: https://caniuse.com/#search=details

**Comment by PVince81** [comment]
I suggest to make an admin setting called "disallow users to allow external websites to access their ownCloud accounts through CORS". This setting should not only hide the setting but also block the feature completely in case something was configured already.

**Comment by PVince81** [comment]
cc @noveens, not sure if you have time to have a look at this

**Comment by mmattel** [comment]
maybe to enable for specific users/groups only instead of general y/n ?

**Comment by PVince81** [comment]
that would be fine too

**Comment by pmaier1** [comment]
> I suggest to make an admin setting called "disallow users to allow external websites to access their ownCloud accounts through CORS". This setting should not only hide the setting but also block the feature completely in case something was configured already.

Yep, as discussed this is the way we should go. The setting should also be disabled by default, I think. In the user section we should also add a brief hint what the feature is meant to do as regular users will not at all understand what it does.

> maybe to enable for specific users/groups only instead of general y/n ?

Would be a nice addition but not necessary at this early stage with just few people making use of CORS.

@PVince81 Please schedule this change in one of the next milestones. Adding P3 as the change is a nice-to-have addition to reduce confusion of end users.

**Comment by PVince81** [comment]
Would rather have a config setting to hide arbitrary sections

**Comment by mmattel** [comment]
@PVince81 the config option is a good idea and could be an array of not shown pages.
Where we need to think about to give each page a proper identifier and make that documented.

**Comment by PVince81** [comment]
at least the sections already have identifiers.

one limitation is that it would only visually hide the section but not prevent API access on those settings, which might be fine for the use case

**Comment by mmattel** [comment]
👍 an ordinary office user does not use API...
We just need to take care that the section might be renamed, so a fixed identifyer is needed.

**Comment by PVince81** [comment]
![image](https://user-images.githubusercontent.com/277525/39173046-d30c0a5a-47a3-11e8-832f-920e39cd677d.png)

there are already ids, those class names
