### ISSUE TITLE
Fresh install of 10.0.4 fails with apps issue on shared server with no sudo

### ISSUE THREAD

**Issue by jfou** [owncloud/core#30094]
### Steps to reproduce
1. Use owncloud-setup.php (or unpack on server)
2. Using browser on mydomain.org, setup admin credentials, connect to msql DB
3. When prompted "App update required" for WebDAV (dav), Federated File Sharing (federatedfilesharing), Share Files (files_sharing), Deleted files (files_trashbin), Notifications (notifications), select "Start Update"

### Expected behaviour
Install should complete, as it has in previous versions (9.x.x)

### Actual behaviour
**OC\RepairException: Upgrade is not possible**

```
Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Repair warning: Please install or update the following apps manually or disable them with: occ app:disable activity occ app:disable files_pdfviewer occ app:disable files_texteditor occ app:disable gallery
Repair warning: For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps
```
Note: I tried to go the marketplace to manually install the missing apps, but since they are core (I'm guessing), I could not do so.

 **Since this is a shared server, I can not use sudo or change permissions.**

### Server configuration
**Operating system**:
Debian

**Web server:**

**Database:**
mySQL

**PHP version:**
Tried using 5.6, 7.0, and 7.1 on the site - same behavior

**ownCloud version:** (see ownCloud admin page)
10.0.4

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
owncloud's servers

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
Not able to access this page - redirects to update page

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => '[something]',
  'passwordsalt' => '[something]',
  'secret' => '[something]',
  'trusted_domains' => 
  array (
    0 => 'mydomain.org',
  ),
  'datadirectory' => '/home/[mysqlUser]/mydomain.org/owncloud/data',
  'overwrite.cli.url' => 'http://mydomain.org/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.2.5',
  'dbname' => '[mysql_dbname]',
  'dbhost' => 'mysql.mydomain.org',
  'dbtableprefix' => 'oc_',
  'dbuser' => '[mysqlUser]',
  'dbpassword' => '[something]',
  'logtimezone' => 'UTC',
  'installed' => true,
  'updater.secret' => '[something]',
);

```

**List of activated apps:**
I have not completed installation. No apps have been installed.

**Are you using external storage** No

**Are you using encryption:** yes/no  HTTPS is enabled for the domain, but encryption is not enabled in owncloud yet since installation is not completed.

** ownCloud log here**
```

{"reqId":"WlY3uq3smIYAAAyxf2gAAAAB","level":3,"time":"2018-01-10T15:56:42+00:00","remoteAddr":"68.50.102.113","user":"--","app":"index","method":"GET","url":"\/owncloud\/index.php\/core\/js\/oc.js?v=2c523db90a67e163d8bdd31b96f96cd4","message":"Exception: {\"Exception\":\"owncloud\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/mysqlUser\\\/mydomain.org\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php(128): owncloud_App::loadApp('dav')\\n#1 \\\/home\\\/mysqlUser\\\/mydomain.org\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(145): owncloud_App::loadApps(Array)\\n#2 \\\/home\\\/mysqlUser\\\/mydomain.org\\\/owncloud\\\/lib\\\/base.php(928): owncloud_Util::setupFS()\\n#3 \\\/home\\\/mysqlUser\\\/mydomain.org\\\/owncloud\\\/index.php(56): owncloud::handleRequest()\\n#4 {main}\",\"File\":\"\\\/home\\\/mysqlUser\\\/mydomain.org\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":192}"}
{"reqId":"WlY3vK3smIYAAGTHFRcAAAAF","level":0,"time":"2018-01-10T15:56:44+00:00","remoteAddr":"68.50.102.113","user":"--","app":"core","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?fallback=true&fallback_id=0&requesttoken=XRk9N00SUglTMEY%2BQhVMA1tvJR0dHglNGAAaPHYmXhc%3D%3A9SKd5g7H9Sqv%2FY5Q76b2oGNxWdux8H8AQ%2FhSAFzleWc%3D","message":"starting upgrade from 10.0.4.4 to 10.0.4.4"}
{"reqId":"WlY3vK3smIYAAGTHFRcAAAAF","level":3,"time":"2018-01-10T15:56:44+00:00","remoteAddr":"68.50.102.113","user":"--","app":"core","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?fallback=true&fallback_id=0&requesttoken=XRk9N00SUglTMEY%2BQhVMA1tvJR0dHglNGAAaPHYmXhc%3D%3A9SKd5g7H9Sqv%2FY5Q76b2oGNxWdux8H8AQ%2FhSAFzleWc%3D","message":"Exception: {\"Exception\":\"owncloud\\\\RepairException\",\"Message\":\"Upgrade is not possible\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/mysqlUser\\\/mydomain.org\\\/owncloud\\\/lib\\\/private\\\/Repair.php(88): owncloud\\\\Repair\\\\Apps->run(Object(owncloud\\\\Repair))\\n#1 \\\/home\\\/mysqlUser\\\/mydomain.org\\\/owncloud\\\/lib\\\/private\\\/Updater.php(221): owncloud\\\\Repair->run()\\n#2 \\\/home\\\/mysqlUser\\\/mydomain.org\\\/owncloud\\\/lib\\\/private\\\/Updater.php(108): owncloud\\\\Updater->doUpgrade('10.0.4.4', '10.0.4.4')\\n#3 \\\/home\\\/mysqlUser\\\/mydomain.org\\\/owncloud\\\/core\\\/ajax\\\/update.php(190): owncloud\\\\Updater->upgrade()\\n#4 {main}\",\"File\":\"\\\/home\\\/mysqlUser\\\/mydomain.org\\\/owncloud\\\/lib\\\/private\\\/Repair\\\/Apps.php\",\"Line\":196}"}
```

Including this for completeness: Earlier owncloud log showed fallback intl was used Running `php -m` shows that intl was not loaded, but `phpinfo() `shows that it is (version 1.1.0). Just to be sure, I added `extension=intl.so` to the phprc file, which addressed that issue.

**Comment by PVince81** [comment]
hmm why is your config.php saying OC 9.1 when you are freshly installing OC 10 ?

is the folder you are using completely clean and also the database ?

**Comment by jfou** [comment]
@PVince81 Thanks for your response. 

That's a good question. The folder is indeed clean and empty. I will check the database  - I assume you mean the site mySQL database. Again, thank you.

**Comment by jfou** [comment]
@PVince81 I have no explanation for that config file. I suspect I posted an old version. My mistake. I'm sorry.

After deleting all OC folders and the mySQL database and starting completely fresh with the setup-owncloud.php file, the config file is nearly empty. I've updated the contents in my post above.
