### ISSUE TITLE
OC 10.0.4.4 - Issue with Installing and Managing Apps

### ISSUE THREAD

**Issue by pgr-sikkin** [owncloud/core#30098]
### Steps to reproduce
0. Read the documentation `https://doc.owncloud.org/server/10.0/admin_manual/installation/apps_management_installation.html`
1. Update config.php to allow several `apps_paths` for non core applications (e.g.: calendar)
  'apps_paths' => [
     [
        'path' => '/OC/apps',
        'url' => '/apps',
        'writable' => false,
     ],
     [
         'path' => '/SRC/exts',
         'url' => '/exts',
         'writable' => true,
     ],
   ],

2. Get Owncloud application (e.g.: `git clone https://github.com/owncloud/calendar.git`)
3. Enable the application `occ app:enable calendar` and OC is down
4. Get an exception: `Exception\":\"RuntimeException\",\"Message\":\"image not found:`
5. Copy `cp -R /SRC/exts/calendar /OC/apps`
6. OC is running

### Expected behaviour
Design as documented `https://doc.owncloud.org/server/10.0/admin_manual/installation/apps_management_installation.html`

### Server configuration
**Operating system**:
Debian GNU/Linux 9.3 (stretch)

**Web server:**
Server version: Apache/2.4.25 (Debian)
Server built: 2017-09-19T18:58:57

**Database:**
Server version: 5.7.20 MySQL Community Server (GPL)

**PHP version:**
PHP 7.0.27-0+deb9u1 (cli) (built: Jan 5 2018 13:51:52) ( NTS )

**ownCloud version:** (see ownCloud admin page)
version: 10.0.4.4

**Updated from an older ownCloud or fresh install:**
Fresh Install

**Where did you install ownCloud from:**
wget --no-verbose https://download.owncloud.org/community/owncloud-10.0.4

**Signing status (ownCloud 9.0 and above):**
  - installed: true
  - version: 10.0.4.4
  - versionstring: 10.0.4
  - edition: Community

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocg7t3ehan2b",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.xxxx.yyy"
        ],
        "datadirectory": "\/DATA\/data",
        "logfile": "\/LOGS\/cloud.log",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "10.0.4.4",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "forcessl": true,
        "loglevel": 3,
        "theme": "custom",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_domain": "xxxx.yyy",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "xxxx.yyy",
        "enable_avatars": true,
        "filelocking.enabled": true,
        "operation.mode": "clustered-instance",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0
        },
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.xxxx.yyy",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "apps_paths": [
            {
                "path": "\/OC\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/SRC\/exts",
                "url": "\/exts",
                "writable": true
            }
        ]
    }
}

**List of activated apps:**
Enabled:
  - calendar: 1.5.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.3
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_versions
  - theme-example
  - user_external

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
No Relevant

**Operating system:**
#### Web server error log
None

#### ownCloud log (data/owncloud.log)
{
"reqId":"PyHNDT0UzMRdg5kJUkDw",
"level":3,
"time":"2018-01-11T10:28:13+00:00",
"remoteAddr":"xxx.yyy.zzz.23",
"user":"www.vvvvv",
"app":"index",
"method":"GET",
"url":"\/index.php\/apps\/files\/",
"message":"Exception: {
   \"Exception\":\"RuntimeException\",
   \"Message\":\"image not found: image:calendar.svg webroot: serverroot:\\\OC\",\"Code\":0,\"Trace\":\"
   #0 \\\/SRC/exts\\\/calendar\\\/appinfo\\\/application.php(103):
OC\\\\URLGenerator->imagePath('calendar', 'calendar.svg')

#### Browser log
No relevant

**Comment by PVince81** [comment]
@pgr-sikkin please run `make` in the calendar app's repo. Note that installing apps from git is not supported on productive instances.

If the problem persists, please reopen.

I have multiple apps folders on my dev env and can confirm that apps work in such env.

**Comment by pgr-sikkin** [comment]
it seems that the repo folders are not updaated correctly

```
xxxx@yyyy030:/SRC/exts/calendar$ make
make yarn
make[1]: Entering directory '/SRC/exts/calendar'
cd js &&  run build
/bin/sh: run: command not found
Makefile:93: recipe for target 'yarn' failed
make[1]: *** [yarn] Error 127
make[1]: Leaving directory '/SRC/exts/calendar'
Makefile:88: recipe for target 'build' failed
make: *** [build] Error 2

```

**Comment by PVince81** [comment]
@pgr-sikkin please make sure you have yarn installed: `npm -g install yarn`

**Comment by pgr-sikkin** [comment]
I have installed `yarn` (in fact cmdtest which includes yarn on Debian) 

```
xxxx@yyyy030:/SRC/exts/calendar$ make
make yarn
make[1]: Entering directory '/SRC/exts/calendar'
cd js && /usr/bin/yarn run build
ERROR: [Errno 2] No such file or directory: 'run'
Makefile:93: recipe for target 'yarn' failed
make[1]: *** [yarn] Error 1
make[1]: Leaving directory '/SRC/exts/calendar'
Makefile:88: recipe for target 'build' failed
make: *** [build] Error 2
```
It seems that yarn was missing but the content of the folder is still not complete ...
Could you suggest some - easy to access - documentation where the technical installation process is -fully - described?
