### ISSUE TITLE
Unable to download a file to local system using NextCloud API

### ISSUE THREAD

**Issue by tummimadhu** [owncloud/core#30100]
Hi All,

I am trying to download a file from a user account in NextCloud, using NextCloud API's with Curl command.

For small files it executes with out error but when I do 'ls' on the current folder it does not show the file.

1. command used  
curl -u user3:user3@123 -X GET 'http://x.x.x.x/remote.php/dav/files/user3/push.sh'

2. file location in UI
![image](https://user-images.githubusercontent.com/6253033/34824746-be57bbee-f6f5-11e7-871f-4bb3b4aa7c16.png)
3. ls on local system ip masked intentionally
![image](https://user-images.githubusercontent.com/6253033/34824821-0504dee6-f6f6-11e7-9fbc-6989997a1bcc.png)
4. uploading a bigger  file throws binary data on the console

ex: curl -u user3:user3@123 -X GET 'http://x.x.x/remote.php/dav/files/user3/VXLAN_Scaling_Data_Center_Designs.pdf'

![image](https://user-images.githubusercontent.com/6253033/34824891-597229f2-f6f6-11e7-9dce-1efd067a2c59.png)

Please let me know what I am doing wrong.

I am also providing log output for large file 
[largeFile.log](https://github.com/owncloud/core/files/1622457/largeFile.log)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by PVince81** [comment]
this is the ownCloud bug tracker. Please report in https://github.com/nextcloud/server

**Comment by tummimadhu** [comment]
Hi @PVince81 , where to report an issue in the nextcloud/server, i did not find any link to report a bug, please guide me.

Thanks
madhu

**Comment by PVince81** [comment]
https://github.com/nextcloud/server/issues/new

**Comment by tummimadhu** [comment]
Hi Vincent,

Can you please guide me where to raise this issue under nextcloud github
shared earlier.

Thanks
Madhu


"Success is never a destination... it's a journey."

**Comment by sharidas** [comment]
@tummimadhu guess you haven't opened the link shared by @PVince81 . Kindly do it.

**Comment by tummimadhu** [comment]
Hi @sharidas , I opened earlier link whic took me to the code base, I created the new issue @https://github.com/nextcloud/server/issues/7880
But not seen any suggestion for the same. :) till now!
Thanks
Madhu

**Comment by sharidas** [comment]
@tummimadhu With all due respect, now nextcloud team may respond to your issue. And if you face any issues with owncloud, feel free to open here :)

**Comment by tummimadhu** [comment]
@sharidas, further update: Using the command curl -u user3:user3@123 -X GET 'http://x.x.x/remote.php/dav/files/user3/config.txt, I am getting the contents of the file printed on the console, So my understanding is GET is used to get the content of a file. However I need a REST API to download the file from a user account. Can any one help out with the API's.??

**Comment by sharidas** [comment]
Kindly read comment again https://github.com/owncloud/core/issues/30100#issuecomment-358228621.

**Comment by tummimadhu** [comment]
Hey,

I just signed the petition "National Highway Authority Of India : save over
300 Banyan trees Hyd-Chevella Road widening India" and wanted to see if you
could help by adding your name.

Our goal is to reach 2,500 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/Qdv5fCJ4Nr

Thanks!
Madhu
