### ISSUE TITLE
App not found message is shown when installing an app via tarball and CLI

### ISSUE THREAD

**Issue by davitol** [owncloud/core#30112]
### Steps to reproduce
1. Install customgroups version 0.1.0 from tarball with ```occ market:install --local customgroups.tar.bz2```

### Expected behaviour
The app installed and CLI command shows a message it has been installed succesfully

### Actual behaviour
The app gets installed but the following message is shown

![screen shot 2018-01-12 at 09 20 35](https://user-images.githubusercontent.com/10596560/34866220-1ae719aa-f77c-11e7-98f4-7e625bc9b9f0.png)

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.5RC3 and Master

**Updated from an older ownCloud or fresh install:** fresh install

**Are you using external storage, if yes which one:** no

**Are you using encryption:**  no

**Comment by PVince81** [comment]
Setting to QA. Please investigate.

Unsure yet whether we need another RC. We'll see how many other issues are found.
