### ISSUE TITLE
[FR] Disable iOS app suggestion with theming parameter

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#30127]
Special `<meta>` element in HTML header triggers the recommendation of the official iOS app in iOS Safari:

![reflector_recording1](https://user-images.githubusercontent.com/214010/34895854-bad08c2e-f7e7-11e7-817d-db8bb0989784.png)

```

<!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" >
	<head data-requesttoken="UXogDDshDSMZPjkVQHNSFxkKGAsUaC8OHz4Hc3UFAAQ=:9BsJzyWIxOvq184MqGU3a1nFgHoGCl32H6pAH+Zu4R0=">
		<meta charset="utf-8">
		<title>
		ownCloud		</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="referrer" content="never">
		<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
		<meta name="apple-itunes-app" content="app-id=543672169">
```

There is a theming option in `apps/theme-custom/defaults.php` that can change this suggestion:

```
	/**
	 * Returns the AppId for the App Store for the iOS Client
	 * @return string AppId
	 */
	public function getiTunesAppId() {
		return '343200656';
	}
```

![reflector_recording2](https://user-images.githubusercontent.com/214010/34895990-52341040-f7e8-11e7-9cdd-bb46ddc46a1f.png)

I found no way to disable this recommendation. Even if I enter a invalid value, the iOS Safari still shows this element for a short time:

![reflector recording3](https://user-images.githubusercontent.com/214010/34896169-0936c99a-f7e9-11e7-8dc0-12ee2925b615.gif)

My proposal would be, to disable the full line in `core/templates/layout.user.php` and `core/templates/layout.guest.php` if the theming parameter is `return '';` or `return '0';`

Otherwise you have to copy the full `core/templates/layout.user.php` and `core/templates/layout.guest.php` file to your theme which could make maintenance harder in future updates…

@PVince81 @VicDeo What do you think?

**Comment by ChrisEdS** [comment]
Good work!

**Comment by michaelstingl** [comment]
Fixed with https://github.com/owncloud/core/pull/31372
