### ISSUE TITLE
Adapt Forbidden Exception's "s:message" on blacklisted files

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/core#30136]
When trying to upload `.htaccess` files; which the server does not support (since they're part of `blacklisted_files` in the capabilities https://github.com/owncloud/core/blob/v10.0.4/apps/files/lib/Capabilities.php#L62). 

Client version 2.4 removed `.htaccess` from its fixed exclusion list (https://github.com/owncloud/client/pull/5748); users might still manually add those there (and maybe client should have different exclusion lists for each capabilities' `blacklisted_files` **from the servers it is connected to**). 

But still, server should not reply 507 "Insufficient Storage" upon `blacklisted_files` upload. A 4XX error with a more user-friendly message (https://github.com/owncloud/core/issues/29948) would be handy.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by mmattel** [comment]
Not tested but maybe related, could be the same behaviour if you try with ``exluded_dirctories``.
Both blacklisted and excluded should return imho either 403 - Forbidden or maybe 420 - Policy Not Fulfilled

**Comment by SamuAlfageme** [comment]
As @ckamm points out in https://github.com/owncloud/client/issues/6302#issuecomment-360426265 `507` happens in the context of 9.X - therefore adjusting the label. 

Also leaving this open in the context of improving the error message/sub-code (https://github.com/owncloud/core/issues/29948) for better troubleshooting and UX in the clients:

![screenshot_2018-01-25_11_58_03](https://user-images.githubusercontent.com/2644445/35385107-964daf8c-01c7-11e8-9be6-5b92cc5a2421.png)

**Comment by SamuAlfageme** [comment]
(Removing backport-request as 9.1 is EOL and 10.X returns 403 for blacklisted files) - the exception's `s:message` could be adapted to something like:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
  <s:message>The file matches a pattern in the server's blacklist and therefore cannot be uploaded.</s:message>
</d:error>
```
