### ISSUE TITLE
[theme-example] CSS needs to be adjusted for changes in 10.0.3 and 10.0.4

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#30139]
@felixheidecke I remember you had to adjust the ownBrander generated themes (https://github.com/owncloud/core/pull/29161) for changes in 10.0.3 and 10.0.4. Please check if the `theme-example` app also needs changes.

@chriseds tested the `theme-example` in a 10.0.4 and the name was cut:

![custom](https://user-images.githubusercontent.com/214010/34942356-aadee59c-f9f7-11e7-85b0-9f98c235d478.jpeg)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.
