### ISSUE TITLE
Renaming config.sample.php causes fatal error in index.php

### ISSUE THREAD

**Issue by arpadox** [owncloud/core#30148]
### Server configuration
**Operating system**:
Raspbian GNU/Linux 9.

**Web server:**
Apache/2.4.25

**Database:**
10.1.23-MariaDB-9+deb9u1 Raspbian 9.0

**PHP version:**
PHP 7.0.19-1

**ownCloud version:** (see ownCloud admin page)
Freshly installed 10.0.4 build 2017-12-05T16:16:34+00:00 56b43bf1eeef330b163108c149bbc5c9dfcbf9d7

**Where did you install ownCloud from:**
Using the 'Web Installer' method
Integrity: no errors have been found.

```
<?php
$CONFIG = array (
  'instanceid' => 'ocq2cktgbi3s',
  'passwordsalt' => 'XXXXXXXXXX',
  'secret' => 'XXXXXXXXXX',
  'trusted_domains' => 
  array (
    0 => 'www.XXXX.XXX',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://www.XXXX.XX/owncloud',
  'dbtype' => 'mysql',
  'version' => '10.0.4.4',
  'dbname' => 'ocloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_XXXX',
  'dbpassword' => 'XXXXXX',
  'logtimezone' => 'UTC',
  'installed' => true,
  'enable_previews' => false,
  'default_language' => 'it',
  'enable_avatars' => false,
  'asset-pipeline.enabled' => true,
  'loglevel' => 3,
);
```

Config report: https://gist.github.com/arpadox/9cb48a212014accd153b5f053256503e

**List of activated apps:**
```
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - files: 1.5.1
  - files_external: 0.7.1
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.3
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - updatenotification: 0.2.1
```

**Are you using external storage?**
See detailed report below

**Are you using encryption:** 
Yes

**Are you using an external user-backend, if yes which one:**
No

**Client configuration**
**Logs**
**Web server error log**
See error below

**ownCloud log (data/owncloud.log)**
Nothing relevant.

I have a CIFS-mounted folder (fstab entry follows)
`//192.168.1.254/disk_1/STORAGE/sub2/  /var/www/owncloud/data/adminuser/files/     cifs    guest,iocharset=utf8,uid=33,gid=33,rw,file_mode=0750,dir_mode=0750,actimeo=60,noperm 0 0`
Where uid 33 is www-data. Said folder sits on an NTFS-formatted USB HDD.

Filesystem details:
```
root@owncloud:/var/www/owncloud# df -h
Filesystem                                     Size  Used Avail Use% Mounted on
/dev/root                                       15G  1.6G   13G  12% /
devtmpfs                                       484M     0  484M   0% /dev
tmpfs                                          489M     0  489M   0% /dev/shm
tmpfs                                          489M   13M  476M   3% /run
tmpfs                                          5.0M     0  5.0M   0% /run/lock
tmpfs                                          489M     0  489M   0% /sys/fs/cgroup
/dev/mmcblk0p1                                  41M   21M   21M  51% /boot
//192.168.1.120/disk_1/STORAGE/sub2/  932G  332G  600G  36% /var/www/owncloud/data/adminuser/files
tmpfs                                           98M     0   98M   0% /run/user/1000
```

Error:
I wanted to 
`mv config/config.sample.php config/sample.config.php` 

to speed up bash autocompletion but this **consistently** causes

`Fatal error: Uncaught Error: Call to a member function getLogger() on null in /var/www/owncloud/index.php:95 Stack trace: #0 {main} thrown in /var/www/owncloud/index.php on line 95`

For some obscure reason. This is horrible. A 'sample' file is supposed to be removable. Luckily i didn't!

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks a possibly related issue is #30128: Spurious "Storage space almost full" warning..

**Comment by DeepDiver1975** [comment]
> mv config/config.sample.php config/sample.config.php

just dont do this. anything which matches *.config.php will be merged into config.php and is used as the real config.

**Comment by arpadox** [comment]
So it's not a sample file.

**Comment by phil-davis** [comment]
``config.sample.php`` is a sample, ``*.config.php`` is not a sample - so if you create files called ``sample.config.php`` ``temp.config.php`` ``test.config.php`` ``notforproduction.config.php`` they are going to get used "for real" even though (in English) the file name looks like it is not to be used "for real".

**Comment by DeepDiver1975** [comment]
> So it's not a sample file. Oh well. So much for POLA.

https://github.com/owncloud/core/blob/955cc32bbbd9d82aebcd05a60fb328be730fcea6/config/config.sample.php#L3-L21

What about the 'principle of reading before breaking it'?
