### ISSUE TITLE
Add sortable column for original path in trashbin view

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30191]
### Steps

1. Delete a lot of files from different locations
1. Have a folder "test/pics/whatever" with a lot of pictures from a camera, all called IMG something or P something.
1. Delete some of said pictures individually by selecting them with the checkbox
1. Delete more of other files
1. Go to "Delete files"
1. Try and find the pictures that were deleted in "test/pics/whatever" and restore them

### Actual result
Searching is not easy. Sort by deletion time and scroll down until the pictures are to be seen.
But what was their names ? No idea.
Hover on the name of every picture in the list to see if the tooltip shows "test/pics/whatever".
Once the range of pictures was identified, can select them and restore at once.

### Expected result
Have a sortable column containing the original path. Sort by path and find the block saying "test/pics/whatever" and quickly find the pictures to restore.

Note: having an extra column could lead to issues due to column width and ellipsis. I suggest to have it so that only the parent part of the name (here "test/pics") can be ellipsized and the actual last part is always visible (here "whatever"). An alternative would be to only show the last part inside that column and have the full path in a tooltip. While not ideal, it would still help for most scenarios where people use different folder names.

### Version
ownCloud 10.0.5 RC3

Thoughts on this proposed UX ? @pmaier1 @felixheidecke 

Estimate for adding only the name as column: 0.25-0.5md
If we want the ellipsis logic on full path, add 0.5md as ellipsizing properly on multiple screen factors can be hard...

**Comment by pmaier1** [comment]
Agree, that would be a handy improvement. :+1: 

> I suggest to have it so that only the parent part of the name (here "test/pics") can be ellipsized and the actual last part is always visible (here "whatever")

Sounds good, I think. We should anyway try to get away from tooltips where possible as they are bad for mobile and kind of old-fashioned.
