### ISSUE TITLE
External Storage - (NAS) Don't work for me!

### ISSUE THREAD

**Issue by antoniomuniz** [owncloud/core#30201]
I have installed "External user support" and configure it correctly. But, when i put the directory: /media/cloud/NASCLOUD (Its a NAS conected with USB 3.0) not work. The check box is red :(

Any help?

**Comment by oldspace** [comment]
In newer owncloud versions local external storage was disabled by default. To allow this option you have to add
`'files_external_allow_create_new_local' => 'true',`
into the owncloud config.php.
For more information see: https://doc.owncloud.org/server/10.0/admin_manual/configuration/files/external_storage/local.html

**Comment by PVince81** [comment]
for support, please see owncloud.org/support or ask in http://central.owncloud.org/ for help

This is likely an environment issue. If you think this is bug, please fill out the [issue template](https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md)
