### ISSUE TITLE
Estimated log size is way off

### ISSUE THREAD

**Issue by sagamusix** [owncloud/core#30227]
### Steps to reproduce
1. Go to administration settings
2. Download log
3. Observe that the estimated size is way off.

### Expected behaviour
ownCloud should estimate the log size somewhat accurately.

### Actual behaviour
ownCloud tells me that the log is 1.9GB and thus "might take a while to download". The downloaded log file is actually **5.9GB** in size. That suspiciously looks like a 32-bit wraparound to me.
Doesn't ownCloud ever clear its log after a while?

### Server configuration
**Operating system**: Bananian (Debian Jessie)

**Web server:** Apache 2.4

**Database:** MySQL 5.5

**PHP version:** 5.6

**ownCloud version:** 10.0.3

**Updated from an older ownCloud or fresh install:** Update

**Where did you install ownCloud from:** ownCloud package for Debian

**Signing status (ownCloud 9.0 and above):** OK

**Comment by DeepDiver1975** [comment]
@sagamusix feel free to test this patch - https://github.com/owncloud/core/pull/30230
