### ISSUE TITLE
Upgrading to 10.0.4 failed LDAP login

### ISSUE THREAD

**Issue by croniserb** [owncloud/core#30239]
After upgrading to 10.0.4 all LDAP users are unable to login.  All of the users except one admin account are all LDAP users.  

The fix for this is really pretty easy.  When doing an upgrade of the server can you please check to see the status of the LDAP user and group backend.  If it is enabled keep it this way.  For whatever reason, the upgrade to 10.0.4 returned this to disabled.

For those finding this in a search, here is the fix to get you running again:

Login with local admin account.
Go to Settings -> Apps

Apps Management on the main window
Click show disabled apps button

Enable the LDAP user and group backend.

**Comment by PVince81** [comment]
what version did you upgrade from ?

here's the issue template, please fill it out: https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

**Comment by croniserb** [comment]
It was an yum update on CentOS 6.9 from 10.0.3 to 10.0.4

**Comment by michaelmaw** [comment]
I've been experiencing this issue every time I reboot my OwnCloud server - it disables the LDAP app, and I have to login with a local account to re-enabled as mentioned above. Happens every time. Very strange.

I'm running OwnCloud 10.0.4.4 on Ubuntu 16.04.3 LTS

**Comment by PVince81** [comment]
Please upgrade to 10.0.6 (it will be announced this week). It contains a protection now to prevent apps like LDAP to get disabled in case of error.

Regarding the LDAP error in question, please check your logs and post to https://github.com/owncloud/user_ldap
