### ISSUE TITLE
PluralizationRules missing on settings / admin page

### ISSUE THREAD

**Issue by MathiasMoog** [owncloud/core#30246]
I use owncloud on an Raspberry PI running Rasbian jessie.

After an upgrade from 10.0.4 to 10.0.5 the settings/admin page does not show up. Only the word "Cron" appears. The html code of the page is:

> <div class="section" id="backgroundjobs">
> 	<h2 class="app-name has-documentation">Cron</h2>
> 		<p class="cronlog inlineblock">
> 

The log file shows the message:

{"reqId":"touaQ5FK8x2brrR52Z85","level":3,"time":"2018-01-23T21:42:29+00:00","remoteAddr":"2003:c7:93e0:1400:f5dd:bd23:9ad5:66d7","user":"admin","app":"PHP","method":"GET","url":"\/owncloud\/index.php\/settings\/admin","message":"Class 'Symfony\\Component\\Translation\\PluralizationRules' not found at \/var\/www\/owncloud\/lib\/private\/L10N\/L10N.php#204"}

I did not find any PluralizationRules.php file unter /var/www/owncloud. There are some Symfony folders, but not a complete installation.

The upgrade message in the log file was:

{"reqId":"XUEeXLMJ5lu13qmUhNB9","level":0,"time":"2018-01-23T21:18:02+00:00","remoteAddr":"2003:c7:93e0:1400:f5dd:bd23:9ad5:66d7","user":"--","app":"core","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=dDguAi4SCmIEYzZaGXcRV0gAJTwJFzsbG2oFFB46cyU%3D%3AFuoiBBSSi0SbQXW5%2B%2FbsxbL%2BI2LLIy6W7Efohe15XIY%3D","message":"starting upgrade from 10.0.4.4 to 10.0.5.4"}

There was no further error message during the upgrade process.

The integrity check with the occ command runs successfull.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by sahsanu** [comment]
I've the same problem, I updated successfully owncloud from 10.0.4 to 10.0.5 (official owncloud repo) on Debian Stretch and I get the same result accessing Settings but it only happens on Settings->Admin->General and only there, I also get a blank page with the word Cron... this is the source of the page:

```
<div class="section" id="backgroundjobs">
	<h2 class="app-name has-documentation">Cron</h2>
		<p class="cronlog inlineblock">
```

and this is the logged error:

`{"reqId":"AmoobLSZEiHw82aRIiqS","level":3,"time":"2018-01-23T23:50:05+00:00","remoteAddr":"60.57.51.166","user":"sahsanu","app":"PHP","method":"GET","url":"\/settings\/admin?sectionid=general","message":"Method OC_L10N_String::__toString() must not throw an exception, caught Error: Class 'Symfony\\Component\\Translation\\PluralizationRules' not found at \/var\/www\/owncloud\/lib\/private\/L10N\/L10N.php#0"`

This error only happens if user's language is other than English, if English language is selected there is no error.

**Comment by DeepDiver1975** [comment]
@MathiasMoog did you install via packages as well?

**Comment by DeepDiver1975** [comment]
The linux packages - at least for debian - are broken @crrodriguez please have a look

![bildschirmfoto von 2018-01-24 08-26-18](https://user-images.githubusercontent.com/1005065/35319498-5cad7894-00e0-11e8-974e-4bee1335e452.png)

**Comment by DeepDiver1975** [comment]
as far as I can tell only debian 9 is affected - http://download.owncloud.org/download/repositories/production/Debian_9.0/all/

**Comment by LiloBzH** [comment]
I confirm too.
Admin broken since owncloud 1.0.5 - Debian APT

**Comment by ssirio** [comment]
I have the same problem, Italian language.
This string in /var/www/owncloud/lib/private/L10N/L10N.php:
`Use Symfony\Component\Translation\PluralizationRules;`
refers to a file?

I don't have found a file "PluralizationRules" in any package, deb or rpm.

**Comment by jnweiger** [comment]
reverted stable and production to 10.0.4, fresh remains at 10.0.5

**Comment by FabienLab** [comment]
Same for me with a (french) raspbian 9. Update with apt this morning from 10.0.4.

**Comment by DeepDiver1975** [comment]
we have a fix for this in qa now ....

**Comment by andreaslink-de** [comment]
_JFYI:_ Ubuntu is also affected, I'm wonder how this can happen that packages are not deployed to the repository servers but announcing new files to be there? Or is this some kind of an incorrect listing update?

    http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/./all/owncloud-files_10.0.5-1.1_all.deb  404  Not Found [IP: 138.201.139.178 80]

**Comment by DeepDiver1975** [comment]
> , I'm wonder how this can happen that packages are not deployed to the repository servers but announcing new files to be there? Or is this some kind of an incorrect listing update?

we rolled back to 10.0.4 - but if you already got 10.0.5 apt will not downgrade.
we all wait eagerly for 10.0.6 .....

**Comment by andreaslink-de** [comment]
Just read it, the apt/repository issue can be solved with this solution:
https://github.com/owncloud/core/issues/27775#issuecomment-302306800

**Comment by PVince81** [comment]
Please help testing with 10.0.6 RC1 from the testing repository, it's the same as 10.0.5 + the hot fix.

@crrodriguez can you post the convenient OBS download page link here ?

**Comment by crrodriguez** [comment]
testing packages are here : https://download.owncloud.org/download/repositories/10.0.6:/testing/

**Comment by sahsanu** [comment]
@PVince81, @crrodriguez I've just installed version [10.0.6](https://download.owncloud.org/download/repositories/10.0.6:/testing/Debian_9.0/all/) (Debian 9) over the faulty 10.0.5 version and it is working pretty fine, no more errors ;)

Thank you very much.

**Comment by FabienLab** [comment]
I've also installed the new 10.0.6 RC version (Raspbian 9), it works well, I have access to the admin settings, thnak you very much :)
