### ISSUE TITLE
Fresh New 12.04 install

### ISSUE THREAD

**Issue by bryantjopplin** [owncloud/core#30247]
### Steps to reproduce
1.Install Fresh using Web Installer
2.See banner on top
3.

### Expected behaviour
Fresh install, no errors

### Actual behaviour
fresh install, one error

### Server configuration
**Operating system**:

**Web server:**

**Database:**
sqllite
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
12.04
**Updated from an older ownCloud or fresh install:**
no
**Where did you install ownCloud from:**
web installer
**Signing status (ownCloud 9.0 and above):**

```
https://gist.github.com/bryantjopplin/29e4f2663d70f3104e0765df0ffeae07
```
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.








Results
=======
- core
	- EXTRA_FILE
		- error_log

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [error_log] => Array
                        (
                            [expected] => 
                            [current] => 7e1abf07d94a2bb69bf56aeead21146aecb002d7f4f404798b1ff1a69cc2877c2e6451849517b8a64153df4593f3141f1a8990d6035edb16f3ed6f56b83782e0
                        )

                )

        )

)
```

**Comment by phil-davis** [comment]
ownCloud is at version 10.0.* - there is no ownCloud version 12.04
Maybe you have reported this in the wrong repo?

**Comment by bryantjopplin** [comment]
Oops sorry I did

**Comment by bryantjopplin** [comment]
Crap
