### ISSUE TITLE
Upgrade 10.0.3 to 10.0.4 fails

### ISSUE THREAD

**Issue by Farbauti** [owncloud/core#30264]
I ran the automated upgrade via `index.php/settings/admin?sectionid=general`

For 1h the page said "his ownCloud instance is currently in maintenance mode, which may take a while."
I checked the update.log and the last entry (1h old) says:
```
[info] Execution of upgrade:checkSystem command started
[info] Execution of upgrade:checkSystem command stopped. Exit code is 0
[info] Execution of upgrade:checkpoint command started
[info] Execution of upgrade:checkpoint command stopped. Exit code is 0
[info] Execution of upgrade:detect command started
[info] ownCloud 10.0.3.3 found
[info] Execution of upgrade:detect command stopped. Exit code is 0
[info] Execution of upgrade:executeCoreUpgradeScripts command started
[debug] Replacing 3rdparty
[debug] Replacing config
[debug] Replacing core
[debug] Replacing l10n
[debug] Replacing lib
[debug] Replacing ocs
[debug] Replacing ocs-provider
[debug] Replacing resources
[debug] Replacing settings
[debug] Replacing .htaccess
[debug] Replacing .mailmap
[debug] Replacing .tag
[debug] Replacing .user.ini
[debug] Replacing AUTHORS
[debug] Replacing CHANGELOG.md
[debug] Replacing console.php
[debug] Replacing COPYING
[debug] Replacing cron.php
[debug] Replacing db_structure.xml
[debug] Replacing index.html
[debug] Replacing index.php
[debug] Replacing indie.json
[debug] Replacing occ
[debug] Replacing public.php
[debug] Replacing remote.php
[debug] Replacing robots.txt
[debug] Replacing status.php
[debug] Replacing version.php
[info] Execution of upgrade:executeCoreUpgradeScripts command stopped. Exit code is 0
[info] Execution of upgrade:executeCoreUpgradeScripts command started
[debug] Replacing 3rdparty
[debug] Replacing config
[debug] Replacing core
[debug] Replacing l10n
[debug] Replacing lib
[debug] Replacing ocs
[debug] Replacing ocs-provider
[debug] Replacing resources
[debug] Replacing settings
[debug] Replacing .htaccess
[debug] Replacing .mailmap
[debug] Replacing .tag
[debug] Replacing .user.ini
[debug] Replacing AUTHORS
[debug] Replacing CHANGELOG.md
[debug] Replacing console.php
[debug] Replacing COPYING
[debug] Replacing cron.php
[debug] Replacing db_structure.xml
[debug] Replacing index.html
[debug] Replacing index.php
[debug] Replacing indie.json
[debug] Replacing occ
[debug] Replacing public.php
[debug] Replacing remote.php
[debug] Replacing robots.txt
[debug] Replacing status.php
[debug] Replacing version.php
[info] Execution of upgrade:executeCoreUpgradeScripts command stopped. Exit code is 0
[info] Execution of upgrade:restartWebServer command started
[info] Execution of upgrade:restartWebServer command stopped. Exit code is 0
[info] Execution of upgrade:postUpgradeCleanup command started
[debug] Moving updater/app
[debug] Moving updater/application.php
[debug] Moving updater/box.json
[debug] Moving updater/composer.json
[debug] Moving updater/composer.lock
[debug] Moving updater/CONTRIBUTING.md
[debug] Moving updater/COPYING-AGPL
[debug] Moving updater/index.php
[debug] Moving updater/pub
[debug] Moving updater/src
[debug] Moving updater/vendor
[debug] Moving updater/README.md
[debug] Moving updater/.travis.yml
[debug] Moving updater/.scrutinizer.yml
[debug] Moving updater/nbproject
[info] Execution of upgrade:postUpgradeCleanup command stopped. Exit code is 0
```

The config.php says `'maintenance' => true` and when I switch it back to false, the website says:

`Updating to 10.0.4

OC\RepairException: Upgrade is not possible

        Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
        Repair warning: Please install or update the following apps manually or disable them with: occ app:disable theme-HWeV
        Repair warning: For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps

Detailed logs
Preparing update
Set log level to debug
Turned on maintenance mode
Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Repair warning: Please install or update the following apps manually or disable them with: occ app:disable theme-HWeV
Repair warning: For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps
OC\RepairException: Upgrade is not possible
The update was unsuccessful. Please report this issue to the ownCloud community.`

How can I proceed?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

A possibly related issue is #25546: Error: Class 'OCA\\Files_Sharing\\API\\Server2Server and apps folder empty after upgrading to 9.0.4.1 .

**Comment by Farbauti** [comment]
Ok, found the symptom - but not the cause.

Symptom: I'm using a custom theme (theme-HWeV) and this app was deleted during the update.

Resolution: I uploaded the theme again, and restarted the upgrade. Then it finished without further errors.

Cause: It seems OC-upgrader is not disabling apps before it erases it. I'd consider this a flaw.

What's your opinion?

**Comment by PVince81** [comment]
@VicDeo is the updater app deleting existing apps ?

**Comment by VicDeo** [comment]
@PVince81 yes. seems to be removed by updater.

**Comment by bombastic1981** [comment]
Can anyone help me about this issue? thanks.. 

![2018-02-15_9-45-10](https://user-images.githubusercontent.com/36492796/36237139-20d41a10-1235-11e8-912f-5ac2d368c8d3.jpg)

**Comment by bombastic1981** [comment]
i figure out i just over right the apps folder on the new version of owncloud from my backup apps folder but another issues popup again,,
![2018-02-15_10-07-47](https://user-images.githubusercontent.com/36492796/36237648-1dcefff8-1238-11e8-9336-109954df8ed4.jpg)

**Comment by PVince81** [comment]
@bombastic1981 did you check the documentation and adjust your config.php accordingly ?

**Comment by PVince81** [comment]
closing due to lack of feedback

feel free to reopen if this issue still exists in 10.0.10
