### ISSUE TITLE
owncloud-files 10.0.5-1.1 missing from Repository

### ISSUE THREAD

**Issue by FatalMerlin** [owncloud/core#30272]
### Steps to reproduce
1. Have owncloud-files 10.0.4-1.1 installed
2. Issue an upgrade using your favorite package manager
3. Run into the 404

### Expected behaviour
The package should upgrade to 10.0.5-1.1.

### Actual behaviour
I get a 404 Error with apt.
```
$ apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  owncloud-files
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 35,0 MB of archives.
After this operation, 460 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Err:1 https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  owncloud-files 10.0.5-1.1
  404  Not Found
E: Failed to fetch https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/./all/owncloud-files_10.0.5-1.1_all.deb  404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

### Server configuration
**Operating system**:
Ubuntu 16.04.3 LTS

**Web server:**
apache2

**Database:**
mariadb

**PHP version:**
7.0.22-0ubuntu0.16.04.1

**ownCloud version:** (see ownCloud admin page)
10.0.4.4

**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**
Official Repository

**Important:**
I checked the Repository, the files at http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/all/
are actually missing.

**Comment by DeepDiver1975** [comment]
> I checked the Repository, the files at http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/all/
> are actually missing.

this is the desktop repo - this cannot hold the server

> Err:1 https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04 owncloud-files 10.0.5-1.1 404 Not Found

this location hold now 10.0.4 again - please run apt-get update - hopefully this helps .....

**Comment by FatalMerlin** [comment]
Already did 5 times, no change. Still pointing to 10.0.5-1.1

**Comment by DeepDiver1975** [comment]
I fear you have to wait for 10.0.6 - sorry for that

**Comment by ctrlbru** [comment]
Same thing for production/Debian_9.0

**Comment by martbrooks** [comment]
Hi

Can you not revert the change?   This makes it slightly less than trivial for systems to be updated with packages from other repos.  An "apt-get update; apt-get dist-upgrade" will block on your missing package.

i.e.

```
martin@molly:~$ sudo apt-get update
Hit:1 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]                 
Get:3 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]                                                                          
Get:4 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]                                               
Hit:5 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease                                                   
Ign:6 http://download.owncloud.org/download/repositories/production/Ubuntu_16.04  InRelease                              
Hit:7 http://download.owncloud.org/download/repositories/production/Ubuntu_16.04  Release
Get:8 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [709 kB]
Get:9 http://eu-west-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [580 kB]
Fetched 1,595 kB in 0s (2,580 kB/s)                                               
Reading package lists... Done
martin@molly:~$ sudo apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  gcc-5-base libstdc++6 owncloud-files
3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 35.0 MB/35.4 MB of archives.
After this operation, 461 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Err:1 http://download.owncloud.org/download/repositories/production/Ubuntu_16.04  owncloud-files 10.0.5-1.1
  404  Not Found [IP: 46.4.80.187 80]
E: Failed to fetch http://download.owncloud.org/download/repositories/production/Ubuntu_16.04/./all/owncloud-files_10.0.5-1.1_all.deb  404  Not Found [IP: 46.4.80.187 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
martin@molly:~$ sudo apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  gcc-5-base libstdc++6 owncloud-files
3 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 35.0 MB/35.4 MB of archives.
After this operation, 461 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Err:1 http://download.owncloud.org/download/repositories/production/Ubuntu_16.04  owncloud-files 10.0.5-1.1
  404  Not Found [IP: 46.4.80.187 80]
E: Failed to fetch http://download.owncloud.org/download/repositories/production/Ubuntu_16.04/./all/owncloud-files_10.0.5-1.1_all.deb  404  Not Found [IP: 46.4.80.187 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
martin@molly:~$
```
If you can't upload the package, you should revert the repo metadata to the currently available package version.

Mart.

**Comment by stoeff42** [comment]
Even when reverting the repo metadata, it breaks all installations that actually updated to that version. You cannot withdraw a version you have already published to the repo. If at all, update the version if it absolutely needs a fix. Even if it means to re-publish the new version with the contents of the old version.
My owncloud installation is currently down because I cannot reinstall the owncloud-files package...

**Comment by jaroslawhartman** [comment]
Hi,

Workaround I found to enable upgrades of other packages:

**Symptoms**

```
jhartman@wieloryb:~$ sudo apt update
Hit:1 http://pl.archive.ubuntu.com/ubuntu artful InRelease
Get:2 http://pl.archive.ubuntu.com/ubuntu artful-updates InRelease [78.6 kB]
Ign:3 http://download.owncloud.org/download/repositories/production/Ubuntu_17.04  InRelease
Get:4 http://security.ubuntu.com/ubuntu artful-security InRelease [78.6 kB]
Get:5 http://pl.archive.ubuntu.com/ubuntu artful-backports InRelease [72.2 kB]
Hit:6 http://download.owncloud.org/download/repositories/production/Ubuntu_17.04  Release
Get:7 http://pl.archive.ubuntu.com/ubuntu artful-updates/main amd64 Packages [170 kB]
Get:9 http://pl.archive.ubuntu.com/ubuntu artful-updates/main i386 Packages [168 kB]
Get:10 http://pl.archive.ubuntu.com/ubuntu artful-updates/universe amd64 Packages [68.0 kB]
Get:11 http://pl.archive.ubuntu.com/ubuntu artful-updates/universe i386 Packages [67.5 kB]
Fetched 703 kB in 0s (1,503 kB/s)
Reading package lists... Done
Building dependency tree
E: Failed to fetch http://download.owncloud.org/download/repositories/production/Ubuntu_17.04/./all/owncloud-files_10.0.5-1.1_all.deb  404  Not Found [IP: 46.4.80.187 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Workaround**

1. Disable owncloud repo

```
root@wieloryb:/etc/apt/sources.list.d# mv owncloud.list owncloud.list.bak
root@wieloryb:/etc/apt/sources.list.d# apt update
```

2. Upgrade

```
root@wieloryb:/etc/apt/sources.list.d# apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  python3-distupgrade python3-update-manager ubuntu-release-upgrader-core update-manager-core
4 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/168 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
```

3. Revert owncloud repo

```
root@wieloryb:/etc/apt/sources.list.d# mv owncloud.list.bak owncloud.list
root@wieloryb:/etc/apt/sources.list.d# apt update
```

4. Run upgrade (for sanity check)

```
root@wieloryb:/etc/apt/sources.list.d# apt upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Surprisingly, no more complains for missing OC version 10.0.5.

I hope it will help,
Jarek

**Comment by FatalMerlin** [comment]
@jaroslawhartman even simpler:

Use:

sudo apt-mark hold owncloud-files

Then you can upgrade without issue.
After this has been fixed, you can remove the package from hold by using:

sudo apt-mark unhold owncloud-files

Hope it helps!
Sorry for the formatting, I'm on mobile.

**Comment by FatalMerlin** [comment]
@jaroslawhartman btw you didn't get another error regarding owncloud-files because you only issued apt upgrade without a prior apt update, so the reactivated repo didn't get querried.

**Comment by jaroslawhartman** [comment]
Hi, 

Not really, you could see _apt update_ in steps (1) and (3).

_apt-mark_ with _hold_ option is much more elegant though, thanks for sharing.

Best regards,
Jarek

**Comment by FatalMerlin** [comment]
@jaroslawhartman Right, totally overlooked that! Apologies.

Glad it helps, though!

**Comment by FatalMerlin** [comment]
@DeepDiver1975 Any news on when this will be resolved?

**Comment by Munk3y** [comment]
Beyond this issue, I'm wondering why the repo hasn't been updated with 10.0.6 yet? The last update to this repo appears to be back in December. If anyone has a time frame on this, I think several people would appreciate it.

Repo Link: https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/

**Comment by PVince81** [comment]
@crrodriguez

**Comment by Tasit** [comment]
Whats going on with the repo? Version 10.0.7 is out now and the repo is still at 10.0.5? Can you please fix it.

**Comment by PVince81** [comment]
this will be added to the documentation to clarify: https://github.com/owncloud/documentation/issues/3811

considering that 10.0.7 was announced two weeks ago and no major issues were found I think we can move forward and update the stable repo @crrodriguez

**Comment by benjaoming** [comment]
Am wondering about the cause: Did this happen because a new release was published in the repository, but then repo maintainers wanted to withdraw the release and did this by just deleting the .deb files in the repo?

**Comment by wolfen351** [comment]
If i use this workaround: 

`sudo apt-mark hold owncloud-files`

How will i know if this has been fixed?

**Comment by FatalMerlin** [comment]
@wolfen351:
`apt update` will show `1 package can be upgraded.`
and
`apt upgrade` will show `The following packages have been kept back: owncloud-files`.
While this will serve as a reminder for the ongoing issue, you can check for the current version in the repository using
`apt-cache policy owncloud-files`.
This command will print output similar to:
```
owncloud-files:
  Installed: 10.0.4-1.1
  Candidate: 10.0.5-1.1
  Version table:
     10.0.5-1.1 500
        500 https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  Packages
 *** 10.0.4-1.1 100
        100 /var/lib/dpkg/status
```

Hope it helps while we wait for the update.

**Comment by kanebrands** [comment]
Is this not priority to fix? Seems like it would be fairly easy to fix the repo... would love to update my installation.

**Comment by PVince81** [comment]
@crrodriguez please update the stable repos

**Comment by FatalMerlin** [comment]
@PVince81 @crrodriguez Update seems to be deployed, updated to 10.0.7-1.1 without further problems, thanks.
