### ISSUE TITLE
Webdav: only check CSRF for POST

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30279]
See https://github.com/owncloud/core/blob/v10.0.4/apps/dav/lib/Connector/Sabre/Auth.php#L187.

Some code paths can lead to checking CSRF for PROPFIND or other methods.

This should be changed to only ever check CSRF for POST requests.

This could then avoid strange errors like https://github.com/owncloud/android/issues/1964#issuecomment-360484533

@DeepDiver1975 @settermjd

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/core/blob/56b43bf1eeef330b163108c149bbc5c9dfcbf9d7/apps/dav/lib/Connector/Sabre/Auth.php#L166-L198

maybe just return here if the request is POST or not?

**Comment by kartik-25** [comment]
HI @PVince81 would like to work on this issue

**Comment by PVince81** [comment]
@kartik-25 great to hear. Please submit your work as a pull request.

**Comment by kartik-25** [comment]
@PVince81 are the setup instructions available for core?

**Comment by phil-davis** [comment]
@kartik-25 I guess you got a core dev environment working already (since a PR is there)?

**Comment by kartik-25** [comment]
Yes
