### ISSUE TITLE
Smoke Test results for 10.0.6

### ISSUE THREAD

**Issue by davitol** [owncloud/core#30300]
# Smoke test

## Previous requirements

Prepare two servers with ssl activated and trusted certificates.

Enable LDAP and external storage apps.

Have a LDAP server ready to be used with owncloud.

Have ready two external storages of your choice SMB, SFTP, Dropbox, Google Drive, FTP, S3, ownCloud, local.

## Testing setup

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Enable encryption app and encryption default module | Encryption is enabled correctly | ✅         | https://github.com/owncloud/core/issues/30280
2 | Populate owncloud server with users and groups | Users and groups are correctly created | ✅        |
3 | Share a folder remotely using federated sharing with admin user of the other server. | folder can be opened in recipient server without problems | ✅       |
4 | Set up LDAP, as admin check users. log in with a LDAP user, if possible one with an avatar. | Users are loaded. LDAP user logs in without problems. Avatar is shown if it exists.  | ✅       |
5 | Set up two external storages different (one Global, one Personal) , disable encryption in one of them.| No errors in this process | ✅   | Tested with SFTP and Windows Network Drive  
6 | Swith ownCloud to a different language| WebUI is translated without problems and works fine | ✅        |  Swithed to spanish and made an exploratory test of settings view.

## Testing functionality

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Share a file using federated sharing from an external unencrypted external storage in server #1 using a LDAP user to the admin user in server #2. | Admin user in server #2 can see the file. | ✅       | 
2 | Open internet explorer or edge and upload a new avatar for a regular user not LDAP | Interface can be used, avatar is uploaded, check that personal page has a scroll bar and scrolls fine. | ✅     | Tested on Windows 10. https://github.com/owncloud/core/issues/27685
3 | Upload several files and folders inside external storages, open some. | No problems uploading, files can be downloaded and opened. | ✅    | 
4 | Delete files inside both external storages. Recover some after from the trashbin. |  Files are correctly deleted and restored. | ✅      | 
5 | Using webdav upload a 100MiB file.| No errors in this process | ✅     |
6 | Upload 100MiB file with web UI (new dav chunking) | No errors in this process | ✅       | https://github.com/owncloud/core/issues/29659
7 | Set a file/folder as favorite | Check that the file/folder appears as favorite in Favorites section | ✅       | 

## Testing Clients

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Using iOS Client, log in and upload a file| No problems found | ✅ | android 2.5.0
2 | Using Android Client, log in and upload a file| No problems found | ✅ |  iOS 3.7.2
3 | Using Desktop Client, log in and upload a file| No problems found | ✅ |  OSX 2.3.0

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are #29633 (Test Results for Smoke test 9.1.7.RC1), #30219 (Smoke Test results for 10.0.5 RC4), #29627 (Smoke Test results for 9.0.11 RC1), and #29649 (Smoke Test results for 10.0.4 RC1).
