### ISSUE TITLE
validatePassword events do not supply user as an argument

### ISSUE THREAD

**Issue by karakayasemi** [owncloud/core#30303]
I am working on https://github.com/owncloud/password_policy/issues/3. To achieve the goal, we need to determine password belongs to which user. But, validatePassword events do not supply user as an argument, @DeepDiver1975 and I thought that, we should add the user as an event argument. As far as I can see, we have 4 validatePassword event emitting calls in the core and it is not possible to add the user object to event arguments in the all of them.

https://github.com/owncloud/core/blob/92b658a60e6c28ef9dd7594384180e0d73e96660/lib/private/User/User.php#L253 we can add here, also maybe only adding here can be sufficient for our purpose.

https://github.com/owncloud/core/blob/92b658a60e6c28ef9dd7594384180e0d73e96660/lib/private/User/Manager.php#L333 since there is no user yet, we can add the only uid in here, but since it is user creation event, we don't need to apply password history to the newly created user.

Also, in sharing case, should we apply password history rule? If yes, we should use the creator of share in the validatePassword event.
https://github.com/owncloud/core/blob/92b658a60e6c28ef9dd7594384180e0d73e96660/lib/private/Share20/Manager.php#L174
https://github.com/owncloud/core/blob/92b658a60e6c28ef9dd7594384180e0d73e96660/lib/private/Share/Share.php#L2867

@DeepDiver1975 @PVince81 what are your thoughts? IMHO, to ensure compatibility with all events, somehow we can add the only uid string in the validatePassword events. If you agree that, I can create a PR in the core for that.

### Expected behaviour
To apply password history rules to passwords, validatePassword events should supply user information.
### Actual behaviour
validatePassword events only supplying a password as the event argument. 
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

**Comment by karakayasemi** [comment]
solved with #30326
