### ISSUE TITLE
Configurable minimum characters before autocomplete user searches

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#30313]
Motivation:

For large user lists searching for the first two characters can be very slow to return.

**Comment by PVince81** [comment]
custom groups also has such autocomplete...

Here's a possible approach:

1) Create a new oc_appconfig setting that sets the minimum chars for any user or group related autocomplete
2) Config value is exposed over capabilities API
3) Add setting in UI somewhere or keep it internal but documented ?
4) Frontend code must read capability value (accessing through `OC.getCapabilities()`) and adjust autocomplete threshold accordingly (needs change in sharing code and customgroups)
5) Backend code `UserManager` and `GroupManager` refuse to work if the search pattern given to any `find*` and `search*` methods is shorter than the minimum. This saves us for modifying backend for any other endpoints.

One concern with 5 is that some code paths might call the search functions with empty string. Maybe we should still allow empty string. But then need to check that the autocomplete backend code doesn't allow for empty string either (it already shouldn't).

**Comment by tomneedham** [comment]
> call the search functions with empty string

Hmm why would they do that... to list all users. We have other methods for that.

**Comment by PVince81** [comment]
I don't know... legacy stuff...

**Comment by PVince81** [comment]
as discussed in chat, the approach above is what we want to do

**Comment by PVince81** [comment]
- [ ] also apply the limit to ajax/share.php's "getShareWithEmail" that is used by the link share email field (see https://github.com/owncloud/core/issues/30670 for steps)

**Comment by VicDeo** [comment]
https://github.com/owncloud/core/pull/30798 and https://github.com/owncloud/core/pull/30994 were merged -> close.
