### ISSUE TITLE
Inconsistent German localisation for "Log in"

### ISSUE THREAD

**Issue by christianmondabon** [owncloud/core#30327]
### Steps to reproduce
None

### Expected behaviour
The German localisation in core/core/l10n/de_DE.js and core/core/l10n/de.js is inconsistent. Both should be the same, either "Einloggen" or "Anmelden", both would be correct.

### Actual behaviour
The German localisation for "Log in" in core/core/l10n/de_DE.js is "Einloggen".
The German localisation for "Log in" in core/core/l10n/de.js is "Anmelden".

### Server configuration
**ownCloud version:** current HEAD

**Comment by PVince81** [comment]
translation is done by third parties here: https://www.transifex.com/owncloud-org/owncloud/

@DeepDiver1975 can external people report issue there or do they need an account ?

**Comment by mmattel** [comment]
I just corrected on Transifex in ``de_DE.js`` ``Einloggen`` -> ``Anmelden``
Both are now the same.
Can be closed.
