### ISSUE TITLE
Keeweb - OwnCloud, HTTP Status 500 ?! Issue in lib/public/Util.php file

### ISSUE THREAD

**Issue by LiloBzH** [owncloud/core#30330]
Hi

Keeweb can't send update of file in owncloud with WebDav:

version	10.0.6.1
versionstring	10.0.6
edition	Community
productname	ownCloud

Keeweb 1.6.3 Windows 10

no problem with my Synology in Webdav ! 

Log :

`{"reqId":"PNxKInIc0GRaAtBrPuYg","level":3,"time":"2018-01-31T17:58:01+00:00","remoteAddr":"123.123.123.123","user":"Tom","app":"remote","method":"PUT","url":"\/remote.php\/dav\/files\/tom\/Keepass\/.tom.kdbx.1517421479927","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"Invalid url \\\"file:\\\/\\\/\\\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/Util.php(805): OCP\\\\Util::getFullDomain('file:\\\/\\\/')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/CorsPlugin.php(71): OCP\\\\Util::isSameDomain('file:\\\/\\\/', 'https:\\\/\\\/cloud.d...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(407): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\CorsPlugin->initialize(Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Server))\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(93): Sabre\\\\DAV\\\\Server->addPlugin(Object(OCA\\\\DAV\\\\Connector\\\\Sabre\\\\CorsPlugin))\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->__construct(Object(OC\\\\AppFramework\\\\Http\\\\Request), '\\\/remote.php\\\/dav...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/Util.php\",\"Line\":768}"}`

An idea ?!

Thank's :)

**Comment by LiloBzH** [comment]
```
	 * @param string $url full url
	 * @return string protocol, domain and port as string
	 * **@since 10.0.5**
	 */
	public static function getFullDomain($url) {
	 * @param string $url full url
	 * @return string protocol, domain and port as string
	 * @since 10.0.5
	 */
	public static function getFullDomain($url) {
```

**Comment by LiloBzH** [comment]
```
		if ($parts === false) {
			throw new \InvalidArgumentException('Invalid url "' . $url . '"');
		}
		if (!isset($parts['scheme']) || !isset($parts['host'])) {
			throw new \InvalidArgumentException('Invalid url "' . $url . '"');
		}
```

$url is empty !

**Comment by LiloBzH** [comment]
Same thing with

> version | 10.0.7.2
> versionstring | 10.0.7

Same patch

In /var/www/owncloud/lib/public/Util.php
Line 765 in function public static function getFullDomain($url) {

add  $url = 'https://owncloud.domain_of_cloud.com';

**Comment by PVince81** [comment]
@LiloBzH do you mind sending your change as a pull request ? Ideal would be to also add matching unit test case because it seems you have found a case that wasn't covered properly by the function. The unit test is here: https://github.com/owncloud/core/blob/master/tests/lib/UtilTest.php#L570.
You can run it with `make test-php TEST_PHP_SUITE=tests/lib/UtilTest.php`

**Comment by LiloBzH** [comment]
i'm sorry. i never use this test environnement. 
i tried with this doc : https://doc.owncloud.org/server/10.0/developer_manual/core/unit-testing.html but it doesn't work

**Comment by PVince81** [comment]
you need ownCloud from git / github for the make command to work, not the tarball

**Comment by LiloBzH** [comment]
i install with APT so that's why !

I parse code with debug and error is : 

$url = file://

**Comment by PVince81** [comment]
Ok, there is something strange with your environment. Just now I saw that your URL starts with "file://". This is not supported / not possible. The URL should always start with "http://" or "https://".

Can you check your config.php ? Did you properly set "overwrite.cli.url" to set the correct http URL ?

**Comment by LiloBzH** [comment]
my conf is ok

overwrite.cli.url = 'cloud.blop.com' and it's only in HTTPS. (HTTP is redirect in HTTPS)

Maybe a bug of keeweb ? ( Keeweb windows with webdav)

**Comment by LiloBzH** [comment]
i test GIT  but "This version of ownCloud requires at least PHP 7.1.0"

so ..

if someone have same problem. Keeweb Windows + owncloud 10.0.7.2

**Comment by PVince81** [comment]
@LiloBzH please add "https://" in front of "overwrite.cli.url": `overwrite.cli.url = 'https://cloud.blop.com'`

maybe that will solve the problem ?

**Comment by LiloBzH** [comment]
no. With https:// of not, same error.

I dont understant. I dont know if it's Keeweb who send "file://" or a bug of owncloud

I test with my synology and no problem. I test with an old version of keeweb and same problem.

**Comment by PVince81** [comment]
This part of your log `OCP\\\\Util::isSameDomain('file:\\\/\\\/', 'https:\\\/\\\/cloud.d...')` seems to show that Keeweb is sending the "Origin" header with a "file://" URL. Not sure why it does that. Normally this header would only be used for cross-domain requests and instead of "file://" it should set the URL of the location where Keeweb is hosted. (is it a webapp?)

**Comment by LiloBzH** [comment]
it's windows app : https://keeweb.info/

I'll open a ticket to ask

**Comment by LiloBzH** [comment]
@PVince81 He said it's Owncloud problem ?...

https://github.com/keeweb/keeweb/issues/877
