### ISSUE TITLE
10.0.6: possible issue with encryption, syncs fail with "503 Encryption not ready: Private Key missing for user"

### ISSUE THREAD

**Issue by thommierother** [owncloud/core#30360]
(for server data reference see #30341)

After upgrade from production 10.0.4 to 10.0.6 (tarball) I see 503 sync errors appearing for some but not all files on a newly created user with server-side encryption on. On the sync client (2.4.0 (build 8911)):
"server sends 503 service unavailable"

owncloud.log:
{"reqId":"1f1c026a-96e6-47e0-a592-8f777be73ba3","level":4,"time":"February 04, 2018 11:14:00","remoteAddr":"79.241.73.200","user":"thommie3","app":"webdav","method":"PUT","url":"\/owncloud\/remote.php\/dav\/files\/thommie3\/Lesen\/33%20Regeln%20von%20Microsoft%20und%20Markus%20Albers.pdf","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Encryption not ready: Private Key missing for user: please try to log-out and log-in again\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(183): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(OCA\\\\Encryption\\\\Exceptions\\\\PrivateKeyMissingException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(171): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #143)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('33 Regeln von M...', Resource id #143)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('files\\\/thommie3\\\/...', Resource id #143, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(256): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":620,\"User\":\"thommie3\"}"}
root@www:/var/www/owncloud# 

"sudo -u www-data php occ files:scan --repair " was done for this user, but no changes
The sync is globally blocked after apperarance of this error, also for other files.
The files are still accessible on the web interface though.

503 errors never appeared before on this instance, the server side config (Webserver, REDIS, database etc.) are unchanged between 10.0.4 and 10.0.6. encryption app is 1.3.1 (latest) as shipped with 10.0.6

Is there some interference with OAuth2?

**Comment by thommierother** [comment]
closed again, the problem is that the sync client uses oauth2 and transfer only tokens but not the correct decryption key

**Comment by PVince81** [comment]
@SamuAlfageme @DeepDiver1975 @sharidas

**Comment by sharidas** [comment]
Did a simple test by upgrading from 10.0.4 -> 10.0.7 ( no desktop client involved ) and then created new user after upgrade. Tried to add new files and folder. This didn't result in 503 error. 

Another investigation shows that 10.0.7 doesn't have https://github.com/owncloud/core/commit/2ddad253004010bfdb0b1c81232a403697eef25b

**Comment by thommierother** [comment]
Re-tested with 10.0.8.RC1, looks as this is fixed
