### ISSUE TITLE
As a user i want be able to re-share a shared file

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/core#30371]
### Steps to reproduce
1. Create user "Carlos", "Pasquale" and "Michael" in demo.owncloud.org
2. As "Carlos" share /Documents/Example.odt with "Pasquale" - turn options "can share" on, and "can edit" off

![documents - files - owncloud 2018-02-05 15-57-15](https://user-images.githubusercontent.com/33026403/35813689-867d9eb6-0a94-11e8-8142-3a5c56c37622.png)

3. Under Windows use right click on the shared file - then click on ownCloud -> Share

![msedge - win10 installed chrome running 2018-02-05 15-58-08](https://user-images.githubusercontent.com/33026403/35813723-9bbf563e-0a94-11e8-9b69-76c6900d7a98.png)

4. Try to share with "Michael"

![msedge - win10 installed chrome running 2018-02-05 16-47-17](https://user-images.githubusercontent.com/33026403/35813737-a4006e5a-0a94-11e8-80ff-57740fd5ef27.png)

### Expected behaviour
Sharing with Michael should be possible

### Actual behaviour
Sharing not possible - Error message "Cannot increase permission of ..."

### Server configuration
**ownCloud version:** (see ownCloud admin page)
10.0.3
### Client configuration
**Client:**
2.4.0
**Operating system:**
Windows 10

**Comment by phil-davis** [comment]
The complication here is that Pasquale is only given read access to the shared file. So when he on-shares it to Michael, he can only give Micheal read access.

The webUI does this correctly, and does not even show the "Can edit" checkbox when Pasquale is sharing the file onwards.

I guess that the Windows client integration is (not yet) smart enough to understand the received access privileges on the file, and to only use those when initiating on-share of the file.

Should this therefore be logged in the client repo?

**Comment by ChrisEdS** [comment]
Ok, make sense. As you explain it, it's actually more of a case for the client repo.

**Comment by ChrisEdS** [comment]
Issue moved to [owncloud/client #6346](https://github.com/owncloud/client/issues/6346) via [**ZenHub**](https://www.zenhub.com/)
