### ISSUE TITLE
8.2 linux packages repo is empty

### ISSUE THREAD

**Issue by WhilelM** [owncloud/core#30372]
There is no package in https://download.owncloud.org/download/repositories/8.2/owncloud 
please fix.

**Comment by DeepDiver1975** [comment]
@jnweiger @crrodriguez

**Comment by mrlinux1** [comment]
Hi WhileIM !

I fixed this. All files which are no longer on our download mirrors should be redirected to our
attic server. 
I tested it with the reported URL and it works now.

Kind regards,
Thomas

**Comment by jnweiger** [comment]
Looks much better now. Thanks @mrlinux1

**Comment by crrodriguez** [comment]
@mrlinux1 thanks, this helped to deal with other issues too.
