### ISSUE TITLE
Allign WebDAV's <oc:permissions> with ocs permissions

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/core#30382]
See for reference & discussion https://github.com/owncloud/client/issues/6346#issuecomment-363355206

The `oc:permissions` of a "shared with me; cannot edit but can reshare" :

```xml
<oc:permissions>SRDNVW</oc:permissions>
``` 

... this is returned in both WebDAV endpoints (old & new). Based on client mappings:

https://github.com/owncloud/client/blob/cedf72825bc0db8e3c147958a9382ee5b411d9ea/src/common/remotepermissions.h#L42-L54

This is not consistent with the semantics of "_Shared with me; can reshare but nothing else_". 

For everything to be sound with the files backend behavior, the permissions should be:

```xml
<oc:permissions>SRDV</oc:permissions>
``` 

... since Rename and Delete operations are also allowed for this file. And to be aligned with the response of of `http://localhost/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json&path=/test&shared_with_me=true`:

```json
{
   "ocs":{
      "meta":{
         "status":"ok",
         "statuscode":200,
         "message":null
      },
      "data":[
         {
            "id":"2",
            "share_type":0,
            "uid_owner":"demo",
            "displayname_owner":"demo",
            "permissions":17,
```

**Comment by SamuAlfageme** [comment]
Linking @PVince81's "suspected similar" issue: https://github.com/owncloud/core/pull/20685

**Comment by PVince81** [comment]
Likely duplicate of https://github.com/owncloud/core/issues/20426

**Comment by SamuAlfageme** [comment]
@PVince81 closing in favor of that one. Will update its title tho.
