### ISSUE TITLE
mount public link does not work with IE 11

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#30392]
### Steps to reproduce
1. create a public link of a folder
2. visit the new public link
3. add the folder to an other owncloud by using the "Add to your ownCloud" button

### Expected behaviour
after login a dialogue should ask to accept the new link and after accepting a new folder should be listed

### Actual behaviour
after login only the old files and folders are listed

### Server configuration
**Operating system**:
Ubuntu 17.10
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
7.1.13
**ownCloud version:** (see ownCloud admin page)
10.0.6 (git)
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc9xsmdtnlru",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.56.1",
            "192.168.0.106"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-core\/data",
        "overwrite.cli.url": "http:\/\/192.168.56.1\/owncloud-core",
        "dbtype": "mysql",
        "logtimezone": "UTC",
        "installed": true,
        "default_language": "en",
        "theme": "",
        "loglevel": "0",
        "maintenance": false,
        "log_type": "owncloud",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "debug": false,
        "version": "10.0.6.1",
        "csrf.disabled": true,
        "files_external_allow_create_new_local": "true",
        "singleuser": false,
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "csrf.disabled=false": "",
        "skeletondirectory": "\/home\/artur\/www\/owncloud-core\/tests\/ui\/skeleton",
        "mysql.utf8mb4": true,
        "ldapIgnoreNamingRules": false,
        "filelocking.enabled": "true"
    }
}

```Enabled:
  - comments: 0.3.0
  - dav: 0.3.2
  - diagnostics: 0.1.0
  - enterprise_key: 0.1.3
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_texteditor: 2.2
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firewall: 2.4.2
  - gallery: 16.0.2
  - market: 0.2.3
  - notifications: 0.3.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - customgroups
  - files_antivirus
  - multidirtest
  - password_policy
  - security
  - testing
  - theme-example
  - user_ldap


```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
IE 11
**Operating system:**
Windows 7

#### Web server error log
nothing

#### ownCloud log (data/owncloud.log)
nothing

#### Browser log
nothing

**Comment by patrickjahns** [comment]
Is it a regression?

**Comment by individual-it** [comment]
went back till 10.0.0 and could not make it work. So maybe it never worked

**Comment by individual-it** [comment]
skipped the tests for now  #30439

**Comment by individual-it** [comment]
ToDo:
- [ ] after fixing unskip tests in ` tests/ui/features/sharingExternalOther/shareByPublicLink.feature` marked with `@skipOnINTERNETEXPLORER @issue_30392`

**Comment by PVince81** [comment]
try again but make sure you are already logged in

I think this is the bug where IE strips out the hash part of the URL.

**Comment by individual-it** [comment]
@PVince81 yes it works when I'm logged in

**Comment by PVince81** [comment]
Hmmm, back then the issue was mostly for Safari and IE < 9, see https://github.com/owncloud/core/issues/20681#issuecomment-164692487

I had the feeling that it must have worked back then in IE10 and IE11. Or maybe the behavior about stripping the hash was added back in IE11... Not sure if worth fixing considering that there is a workaround and it's IE...

**Comment by phil-davis** [comment]
Seems to also be failing on Edge - I will look at the Travis SauceLabs video tomorrow and see what happens...

**Comment by PVince81** [comment]
It seems we'll likely need to redesign how the "add to ownCloud" link is constructed and avoid using hash query as the hash is discarded by IE apparently during a redirect.

Considering that this has an easy workaround (be logged in), reducing priority.

**Comment by PVince81** [comment]
A possible fix would be to modify the URL to use a query parameter instead of anchor. Need to be careful to not break the existing flow nor browser history.

Estimate: 0.5-1md
