### ISSUE TITLE
Share too Group or User option expiration date is missing

### ISSUE THREAD

**Issue by ITTRI4710** [owncloud/core#30396]
A user has reported since the update to 10.0.3 (stable) when he shares a document with another user no longer specify an expiration date.

Unfortunately, nothing has been found so far.

Best,
Roland

**Comment by PVince81** [comment]
Expiration date was never supported for regular user or group shares, so not sure in what version you saw the feature working before... If you're talking about link shares then it's something different.

Please use the issue template https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md and provide the required info (updated from what version, steps to reproduce, screenshot, etc)

**Comment by ITTRI4710** [comment]
In version 8.1.9 it worked. But unfortunately can not do any more pictures.

Unfortunately, I do not have direct access to the server but can provide the following information.
I can give this information because we had a calendar problem and are from the other case.


Initial Idea was an OC Upgrade vom 8.1 -> 10 AND Migration to 64bit System
Starting at:
openSUSE 13.1 i586 (32bit)
ownCloud 8.1.9
Calendar 0.7.4

Did the following:
openSuSE 13.1 to 13.2 (32bit) regarding OC 10 dependencies
System is on
Apache2: 2.4.10-31.1
MySQL: 5.6.34-2.23.1
PHP: 5.6.1-89.1

Update ownCloud 8.1.x -> 8.2.x
Update ownCloud 8.2.x -> 9.0.x
ran into this issue: #800
solved it like this:
go to lib/private/integritycheck/checker.php and just returning false in function isCodeCheckEnforced

ownCloud Update 9.0 -> 9.1 ... using:
sudo -u wwwrun php occ dav:migrate-calenders
sudo -u wwwrun php occ dav:migrate-addressbooks
ran into the same error -> see "calender issue" above ... fixed it the same way
next error - if I try to activate the calender app - "App Folder already exists", so I did:
rename Foldername to Foldername.old (in app Subdirectory)
Installed the App from Webgui again

ownCloud Update 9.1 -> 10.x ... next error during "sudo -u wwwrun php occ upgrade"
Repair warning: Please install or update the following apps manually or disable them with ... did it:
occ app:disable activity
occ app:disable calendar
occ app:disable filespdfviewer_
occ app:disable filestexteditor_
occ app:disable gallery
updated all apps using webgui

next step should be the migration from 32bit to 64bit system...
...but at first I've to fix the calender issue!
Calender worked till "9.1 -> 10.x"

**Comment by ITTRI4710** [comment]
https://github.com/owncloud/calendar/issues/836

**Comment by PVince81** [comment]
did we have expiration for local user shares in calendar app in 8.1 ? @butonic @DeepDiver1975

**Comment by PVince81** [comment]
in any case, we're planning to bring this feature to core for files here: https://github.com/owncloud/core/issues/11642

not sure about calendar

**Comment by ittrend4710** [comment]
Calendar Issues are already processed here:
1) Shared calendar permission #882
2) Users are unable to create / modify events on the shared calendar #836
...so it shoudn't affect it!

This case is only for "Share too Group or User option" regarding FILES!

Best,
Mike

**Comment by ITTRI4710** [comment]
Hi!
...any news about that?
best,
Roland

**Comment by PVince81** [comment]
closed in favor of https://github.com/owncloud/core/issues/11642
