### ISSUE TITLE
Theme command description in config.sample.php is wrong

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/core#30407]
Wrong description in config.sample.php for the theme command.

/**
 * If you are applying a theme to ownCloud, enter the name of the theme here.
 * The default location for themes is 'owncloud/themes/'.
 */
'theme' => '',

**Comment by VicDeo** [comment]
@prsnbrg what's exactly wrong here?

**Comment by VicDeo** [comment]
this is a  legacy config option 
removed in master/stable10 with https://github.com/owncloud/core/pull/30350
