### ISSUE TITLE
Error on installing OwnCloud 10.0.6

### ISSUE THREAD

**Issue by Mephysto666** [owncloud/core#30416]
### Steps to reproduce
1. Go to Owncloud homepage

### Expected behaviour
Showing admin user creation screen

### Actual behaviour
![cattura](https://user-images.githubusercontent.com/3337127/35963590-81d651f0-0cb5-11e8-8f1d-355beafa2a17.PNG)

### Server configuration
**Operating system**: Debian 9.1

**Web server:** Same behavior both with Apache 2.4 and Nginx 1.10.3

**Database:** Postgres

**PHP version:** 7.0.27-0+deb9u1

**ownCloud version:** 10.0.6

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** Manual installation

**Signing status (ownCloud 9.0 and above):** 

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
I can't produce config, I get this error:
```
Error: Call to a member function getUser() on null in /var/www/html/lib/private/Log.php:295
Stack trace:
#0 /var/www/html/lib/public/Util.php(157): OC\Log->log(3, 'User backend OC...', Array)
#1 /var/www/html/lib/private/legacy/user.php(153): OCP\Util::writeLog('core', 'User backend OC...', 3)
#2 /var/www/html/lib/base.php(657): OC_User::setupBackends()
#3 /var/www/html/lib/base.php(998): OC::init()
#4 /var/www/html/console.php(64): require_once('/var/www/html/l...')
#5 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

**List of activated apps:** I can't produce it.
```

**Are you using external storage, if yes which one:**  nfs

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

#### LDAP configuration (delete this part if not used)
Not configured yet

### Client configuration
**Browser:** Firefox 58

**Operating system:** Windows 10

### Logs
#### Web server error log
```
2018/02/08 09:21:48 [error] 2071#2071: *47 FastCGI sent in stderr: "PHP message: PHP Warning:  hash_equals(): Expected user_string to be a string, null given in /var/www/html/lib/private/Log.php on line 287
PHP message: {"reqId":"ALy7R2TQii6lmIJXRLoS","level":3,"time":"February 08, 2018 09:21:48","remoteAddr":"10.39.0.77","user":"--","app":"index","method":"GET","url":"\/index.php","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function getUser() on null\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Log.php(169): OC\\\\Log->log(3, 'session_name():...', Array)\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Log\\\/ErrorHandler.php(89): OC\\\\Log->error('session_name():...', Array)\\n#2 [internal function]: OC\\\\Log\\\\ErrorHandler::onError(2, 'session_name():...', '\\\/var\\\/www\\\/html\\\/l...', 45, Array)\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Session\\\/Internal.php(45): session_name('')\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(426): OC\\\\Session\\\\Internal->__construct('')\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(582): OC::initSession()\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(998): OC::init()\\n#7 \\\/var\\\/www\\\/" while reading response header from upstream, client: 10.39.0.77, server: _, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "10.39.0.222", referrer: "http://10.39.0.222/"
2018/02/08 09:21:48 [error] 2071#2071: *47 FastCGI sent in stderr: "PHP message: {"reqId":"ALy7R2TQii6lmIJXRLoS","level":3,"time":"February 08, 2018 09:21:48","remoteAddr":"10.39.0.77","user":"--","app":"PHP","method":"GET","url":"\/index.php","message":"hash_equals(): Expected user_string to be a string, null given at \/var\/www\/html\/lib\/private\/Log.php#287"}" while reading upstream, client: 10.39.0.77, server: _, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "10.39.0.222", referrer: "http://10.39.0.222/"
2018/02/08 09:38:09 [error] 8929#8929: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  hash_equals(): Expected user_string to be a string, null given in /var/www/html/lib/private/Log.php on line 287" while reading response header from upstream, client: 10.39.0.77, server: _, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "10.39.0.222"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"6rJMyma4TOKNickeBMbB","level":3,"time":"February 08, 2018 10:00:34","remoteAddr":"10.39.0.77","user":"--","app":"index","method":"GET","url":"\/index.php","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function getUser() on null\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Log.php(169): OC\\\\Log->log(3, 'session_name():...', Array)\\n#1 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Log\\\/ErrorHandler.php(89): OC\\\\Log->error('session_name():...', Array)\\n#2 [internal function]: OC\\\\Log\\\\ErrorHandler::onError(2, 'session_name():...', '\\\/var\\\/www\\\/html\\\/l...', 45, Array)\\n#3 \\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Session\\\/Internal.php(45): session_name('')\\n#4 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(426): OC\\\\Session\\\\Internal->__construct('')\\n#5 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(582): OC::initSession()\\n#6 \\\/var\\\/www\\\/html\\\/lib\\\/base.php(998): OC::init()\\n#7 \\\/var\\\/www\\\/html\\\/index.php(54): require_once('\\\/var\\\/www\\\/html\\\/l...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/lib\\\/private\\\/Log.php\",\"Line\":295}"}
{"reqId":"6rJMyma4TOKNickeBMbB","level":3,"time":"February 08, 2018 10:00:34","remoteAddr":"10.39.0.77","user":"--","app":"PHP","method":"GET","url":"\/index.php","message":"hash_equals(): Expected user_string to be a string, null given at \/var\/www\/html\/lib\/private\/Log.php#287"}
```

#### Browser log
```
Error: Call to a member function getUser() on null in /var/www/html/lib/private/Log.php:295 Stack trace: #0 /var/www/html/lib/private/Log.php(169): OC\Log->log(3, 'session_name():...', Array) #1 /var/www/html/lib/private/Log/ErrorHandler.php(89): OC\Log->error('session_name():...', Array) #2 [internal function]: OC\Log\ErrorHandler::onError(2, 'session_name():...', '/var/www/html/l...', 45, Array) #3 /var/www/html/lib/private/Session/Internal.php(45): session_name('') #4 /var/www/html/lib/base.php(426): OC\Session\Internal->__construct('') #5 /var/www/html/lib/base.php(582): OC::initSession() #6 /var/www/html/lib/base.php(998): OC::init() #7 /var/www/html/index.php(54): require_once('/var/www/html/l...') #8 {main}
```


Can you help me please?

Meph

**Comment by PVince81** [comment]
Thanks for your report.

Closing in favor of https://github.com/owncloud/core/issues/30335 which apparently has the same cause

**Comment by PVince81** [comment]
seems to be slightly different code.

@sharidas please have a look

**Comment by PVince81** [comment]
@Mephysto666 did you set any conditional log settings in config.php or was this a plain unmodified install ?

**Comment by Mephysto666** [comment]
HI @PVince81,
no, I did not touch no log settings.

Bye.

Meph

**Comment by VicDeo** [comment]
@Mephysto666 
according to the log it can't find or load a file with a class that is responsible for user management.

Could you please
1. Double check ownership/permissions
2 .share an output for  `php occ integrity:check-core`

**Comment by Mephysto666** [comment]
Hi @VicDeo,
all files and directories belong to www-data, user and group. Same user and group as nginx and php-fpm processes.

The output of command you suggested is this:

```
www-data@ftp:~/html$ php occ integrity:check-core
An unhandled exception has been thrown:
Error: Call to a member function getUser() on null in /var/www/html/lib/private/Log.php:295
Stack trace:
#0 /var/www/html/lib/public/Util.php(157): OC\Log->log(3, 'User backend OC...', Array)
#1 /var/www/html/lib/private/legacy/user.php(153): OCP\Util::writeLog('core', 'User backend OC...', 3)
#2 /var/www/html/lib/base.php(657): OC_User::setupBackends()
#3 /var/www/html/lib/base.php(998): OC::init()
#4 /var/www/html/console.php(64): require_once('/var/www/html/l...')
#5 /var/www/html/occ(11): require_once('/var/www/html/c...')
#6 {main}
```

Same error as before.

Many thanks.

Meph

**Comment by VicDeo** [comment]
@Mephysto666 could you check what will happen when you replace 
`/var/www/html/lib/private/Log.php` with 
https://github.com/owncloud/core/raw/2c449a1dce649da1a4d22cbfbcfbc0c2118cad8b/lib/private/Log.php ?

I suspect there is something wrong with PHP session configuration so logger fails to get a user.
Your `owncloud.log` might have a clue inside after this patch

**Comment by PVince81** [comment]
@Mephysto666 please try with OC 10.0.7 RC2: https://download.owncloud.org/community/testing/owncloud-10.0.7RC2.tar.bz2

**Comment by Mephysto666** [comment]
I can't test it now, but the problem is in config.php of downloaded version of Owncloud.

I used web installation that has a more simple config.php and it had been installed without problems. When I tried to use config.php I used in preceding installation, I econuntered same error.

I hope this is useful for you.

Best regards.

Meph

**Comment by VicDeo** [comment]
The reason can only be guessed in that case.
I'd suppose that something is wrong with cache setup (Redis or whatever) on your environment.

**Comment by PVince81** [comment]
please reopen if problem persists with 10.0.7 which contains a fix for null errors
