### ISSUE TITLE
making the signature version for S3 external storages configurable?

### ISSUE THREAD

**Issue by pako81** [owncloud/core#30417]
v4 signature seems currently hardcoded here: https://github.com/owncloud/core/blob/master/apps/files_external/lib/Lib/Storage/AmazonS3.php#L576

Would it make sense to have this as a configurable option?

Also, it depends if the new lib version supports v2, if not then we cannot support both.

@PVince81 @DeepDiver1975 @tomneedham @butonic as discussed.

**Comment by isaackcr** [comment]
I work at a University that hosts a Ceph server for all of campus S3 storage, it only supports V2 signatures so this option is essential for us. Please add this back to ownCloud.

**Comment by DeepDiver1975** [comment]
Secondary s3 storage integration just got move over to https://github.com/owncloud/files_external_s3.

Unfortunately GitHub does not allow to move issues. Please reopen the issue at https://github.com/owncloud/files_external_s3/issues
