### ISSUE TITLE
Supported Linux Distribution for Server

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#30423]
Linux Distribution Support Policy as stated in:

https://doc.owncloud.com/server/10.0/admin_manual/installation/system_requirements.html

> For Linux distributions, we support, if technically feasible, the latest 2 versions per platform and the previous LTS.

-------------------------

I have looked up the current releases for Ubuntu, Suse Linux Enterprise, open Suse, fedora, Debian and centos.

Here are my results:

---------------------

**Ubuntu**

Last 2: 17.10, 16.04

LTS: 16.04.03

we have currently: 

Ubuntu_17.04 is EOL

Ubuntu_16.10 is EOL

Ubuntu_16.04 

----------------

**Suse Linux Enterprise**

Latest 2: 12 SP3, 12 SP2
LTS: 12

on the download site of owncloud:

SLE_12_SP2, SLE_12_SP1, SLE_12 

so SP3 is missing.

-------------

**open Suse**

Latest 2: openSUSE Tumbleweed, openSUSE Leap
LTS: openSUSE Leap

on the download site of owncloud:

openSUSE_Tumbleweed, openSUSE_Leap_42.3, openSUSE_Leap_42.2

openSUSE_Leap_42.1 is EOL

---------------------------

**fedora**

Latest 2: 27, 26 

on the download site of owncloud:

Fedora_26

Fedora_25 is EOL

Fedora_24  is EOL

-------------------------

**Debian**

Last 2: Debian 9 ("Stretch"), Debian 8 ("Jessie") 
Still supported, maybe LTS? Debian 7 “Wheezy”

on the download site of owncloud:

Debian_9.0, Debian_8.0, Debian_7.0

------------------------

**CentOS**

Last 2: 7.4, 7.3
Still supported, maybe LTS? 6.9

on the download site of owncloud:

CentOS_7, CentOS_6

**Comment by PVince81** [comment]
@voroyam what are you trying to say ? Should we remove packages from the EOL distributions ? Should we update the documentation ?

**Comment by voroyam** [comment]
many questions @PVince81  :)

I was told to research based on our own policy regarding the distributions what the newest and current Linux distributions were and what we had on our site. 

This is the result of my research.

I am suggesting, following our own policy, that we should offer the correct versions of the distributions or update our policy regarding them.

**Comment by PVince81** [comment]
@hodyroff @crrodriguez

**Comment by voroyam** [comment]
Well it's a bit complicated.

For example for Ubuntu the last 2 are 17.10 and 16.04 which is also the LTS version.

So according to our policy we would only offer those two as the other ones we currently offer are EOL.

I am not quite sure if I am doing this right. If on the release website of Ubuntu the version if EOL do we still offer it or not? Same goes for other distribution.

If I am correct, we need to offer ownCloud in the correct Linux distributions. In some cases it means dropping some old ones or adding new ones. Detailed informations could be taken from my original post. I am here to clarify if needed.

**Comment by crrodriguez** [comment]
In my opinion only EOL distributions have to be removed from the list and those old ones where it is known it oc server doesn't work if any.

**Comment by pmaier1** [comment]
It's easy: Last two and/or LTS
- If there are two non-LTS versions that are not EOL, then we support those
- If there is a third version that is LTS, then we support that one as well
- If there's less versions that are not EOL then we only support those.

In the case of Ubuntu this currently is 16.04 (LTS) and 17.10.
In two months, when 18.04 is released it will be three supported versions unless one of the others reach EOL until then.

This is purely a documentation thing and not necessarily related to the packages we provide. Please follow up in the documentation ticket (https://github.com/owncloud/documentation/issues/3785) therefore and update the docs accordingly @voroyam and @settermjd.
