### ISSUE TITLE
everytime INVALID_HASH / integrity check after installing 10.0.6

### ISSUE THREAD

**Issue by htom84** [owncloud/core#30420]
### Steps to reproduce
1. download https://download.owncloud.org/community/owncloud-10.0.6.tar.bz2 or https://download.owncloud.org/community/owncloud-10.0.6.zip
2. extract all files to new folder on server
3. generate new db
4. install (everything fine)
5. login

### Expected behaviour
fresh install without this error

### Actual behaviour
PROMPT about DATA Integrity fail

- Tried to replace the files again and again, from .tar, from .zip, error keeps there
- Also 3 complete new installs (other folder, other database) changes nothing

### Server configuration
**Operating system**: Linux

**Web server:** 

**Database:** mySQL

**PHP version:** 7.0

**ownCloud version:** 10.0.6.1

**Updated from an older ownCloud or fresh install:** NO

**Where did you install ownCloud from:** SEE ABOVE

**Signing status (ownCloud 9.0 and above):** https://gist.github.com/htom84/7d1e4406c46a8ff1e0404e9f76869b9e

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => 'XXXXXXXXXXXXXXXXXXXX',
  'passwordsalt' => 'XXXXXXXXXXXXXXXXXXXX',
  'secret' => 'G+XXXXXXXXXXXXXXXXXXXX',
  'trusted_domains' => 
  array (
    0 => 'XXXXXXXXXXXXXXXXXXXX',
  ),
  'datadirectory' => 'XXXXXXXXXXXXXXXXXXXX',
  'overwrite.cli.url' => 'XXXXXXXXXXXXXXXXXXXX',
  'dbtype' => 'mysql',
  'version' => '10.0.6.1',
  'dbname' => 'XXXXXXXXXXXXXXXXXXXX',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXXXXXXXXXXXXXXXXXXX',
  'dbpassword' => 'XXXXXXXXXXXXXXXXXXXX',
  'logtimezone' => 'UTC',
  'installed' => true,
);

**List of activated apps:** NO APPS INSTALLED

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** yes/no
SSL / HTTPS

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
**Browser:** FIREFOX and Chrome

**Operating system:** Win 10 pro

#### ownCloud log (data/owncloud.log)
EMPTY

**Comment by PVince81** [comment]
which files fail integrity check ?

**Comment by VicDeo** [comment]
seems to be the same with https://github.com/owncloud/core/issues/30332

**Comment by htom84** [comment]
@PVince81 these are the files:

- core/doc/admin/_static/img/note_pencil.svg
- core/doc/admin/_static/img/warning.svg
- core/fonts/LICENSE.txt
- core/vendor/clipboard/dist/clipboard.js
- core/vendor/jsTimezoneDetect/jstz.js
- core/vendor/showdown/dist/showdown.js
- core/vendor/showdown/dist/showdown.min.js

**Comment by PVince81** [comment]
Did you click "rescan" after replacing the files ?

**Comment by htom84** [comment]
@PVince81 Yes, I tried everything:

- Just replace
- Delete the old files and upload the files new
- Download and extract the zip again
- Complete fresh install

The error is allways the same

**Comment by PVince81** [comment]
The tarballs in question work correctly for many people here.

So either there is some weird code caching in place or the signature code has trouble in your environment for some unknown reason.

**Comment by VicDeo** [comment]
I suspect it was broken on extraction. Let's validate md5
```
oc1006> md5sum core/doc/admin/_static/img/note_pencil.svg
73f5294a3a569585b6bd45e88698d8e9  core/doc/admin/_static/img/note_pencil.svg
oc1006> md5sum core/doc/admin/_static/img/warning.svg
0a6b0d8c58c01ef144768de6a7b16612  core/doc/admin/_static/img/warning.svg
oc1006> md5sum core/fonts/LICENSE.txt
d273d63619c9aeaf15cdaf76422c4f87  core/fonts/LICENSE.txt
oc1006> md5sum core/vendor/clipboard/dist/clipboard.js
ad43f0df30d963a35e274c5cc35a8528  core/vendor/clipboard/dist/clipboard.js
oc1006> md5sum core/vendor/jsTimezoneDetect/jstz.js
a5299c9d2ddcd11f25018680c3662c0f  core/vendor/jsTimezoneDetect/jstz.js
oc1006> md5sum core/vendor/showdown/dist/showdown.js
9021b7c15a50e066ef3424e2a3550a59  core/vendor/showdown/dist/showdown.js
oc1006> md5sum core/vendor/showdown/dist/showdown.min.js
db406d2515b75834e2524d313e82c374  core/vendor/showdown/dist/showdown.min.js
```

**Comment by htom84** [comment]
@VicDeo thats interesting, the md5 seems to be legit:

73f5294a3a569585b6bd45e88698d8e9	note_pencil.svg
0a6b0d8c58c01ef144768de6a7b16612	warning.svg
(...)
a5299c9d2ddcd11f25018680c3662c0f	jstz.js

and so on. 

But on server it looks like a problem (maybe with htaccess):
Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => c00197d1a4d7a1db5bf43849acd10d2d7813705463ba02fe540b5d05328dcf078456e55dcd0450bb884a85bf25c66a596cdcf9108d26ba44d2287a35de26d72b
                            [current] => 13854cb255c24a3b4f7196ff298ce5eaa2173b96e607c10b5ef39f7e1107b4e099b6edf75df6a35230e52f15cce231bb814320758ec94e987693d090080206b1
                        )

                    [core/doc/admin/_static/img/note_pencil.svg] => Array
                        (
                            [expected] => 78b9df57afe9468145e6e375cd1f61274b269b9c3019726a99e043ae952367acf53cf471cbc5b3dcca2e68367c2c4422d4a9f9a9fdbb11f9b962845ac77857de
                            [current] => 97117ce2827cc1b742678b52fc100de1e7d3fdb1adeea04a301c012e7f95b66e10a369c6a83ba89a707c4232b5e31fba3d5e58b0e0d970f22031d0704eebb5a9
                        )

                    [core/doc/admin/_static/img/warning.svg] => Array
                        (
                            [expected] => e8647b47ef1531b8c2fcdd51f76996fe85476467fc694540f3dcf8ce7e7da489e99edae5a158742da71c07dc09ccfaf721f01c1c4bda3f5bae9b711981b71a1b
                            [current] => 85687f19cf204716e9b1c608682aa22c045b6f8284a3496db07f13200952491bfea54deee7ef11115c0dedfd87443c7022ef05792892a8a984866752c8ec5726
                        )

... and so on

**Comment by htom84** [comment]
After having the same Problem with the older Version 9, I decided to try it via a ssh install instead of ftp. Now it works fine. 

So: If you have problems with file integrity and ssh access, better try it with ssh.
