### ISSUE TITLE
On the Gallery page, uploading the same file with a completely different prompt box, choosing to keep the new and old files, the Continue button is not available.

### ISSUE THREAD

**Issue by supermanlinux** [owncloud/core#30469]
### Steps to reproduce
1.Open the Gallery application and upload an image
2.Upload the same image file again, a dialog box will pop up for file differences
3.Choose to keep new files and old files, click the Continue button below does not reflect
![image](https://user-images.githubusercontent.com/34739130/36139966-8add0644-10da-11e8-937f-1155f0f43b1e.png)

### Expected behaviour
Click the continue button  upload same files, as the list of files upload difference file.

### Actual behaviour
The continue button can't click, can't upload the same files.

### Server configuration
**Database:**10.0.31-MariaDB-0ubuntu0.16.04.2 Ubuntu 16.04
**PHP version:**PHP 7.0.22
**ownCloud version:10.0.6.1
**Where did you install ownCloud from:owncloud-10.0.6.tar.bz2

**Comment by supermanlinux** [comment]
@DeepDiver1975 @PVince81 I have no ideas,what happened,the log is noting help me.Thanks.

**Comment by PVince81** [comment]
does the conflict dialog work correctly for you in the "Files" view ? (not gallery).

If this happens only in the gallery app then the bug is in that app: https://github.com/owncloud/gallery

**Comment by supermanlinux** [comment]
@PVince81 Yes,the conflict dialog work correctly in the "Files" view,only in gallery it doesn't work.You can move this question to https://github.com/owncloud/gallery,or I add this question to there once more?

**Comment by PVince81** [comment]
please resubmit your post in the gallery repository, then close here after linking there.
thanks
