### ISSUE TITLE
performance on user lookup

### ISSUE THREAD

**Issue by felixboehm** [owncloud/core#30474]
With large user bases the performance seems to be not very good on the endpoint for user lookups.

By using search terms in the endpoint /files/index.php/core/ajax/share.php, we see that the response time increases rapidly and temporarily makes our user account unusable.

@tomneedham

**Comment by DeepDiver1975** [comment]
@felixboehm which version of owncloud? ldap in place? how is the ldap configured? size of the address books of the involved user ? federated sharing in place?

**Comment by tomneedham** [comment]
Need more info about the request to `/files/index.php/core/ajax/share.php`. Do you instead mean sharee lookup? That URL is `apps/files_sharing/ajax/sharee.php`.

**Comment by PVince81** [comment]
I don't see any "sharee.php", what you mean is likely the OCS Share API ?

As far as I remember the autocomplete code is using OCS Sharee endpoint

**Comment by tomneedham** [comment]
This is most likely this https://github.com/owncloud/core/pull/30195
