### ISSUE TITLE
Provide PHP library dependency info in info.xml

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30472]
The problem: if two apps are loading a composer library with different incompatible versions, bad things could happen. Depending on the code path taken, one library might be loaded before the other and cause unpredictable/untested behavior. One known example is Guzzle v5 version Guzzle v6 where the API changed and is known to break apps using the other version.

To make this more predictable, I suggest to store these versions in info.xml so they are also available for the marketplace and also for the app installation code.

This would require the following:
1) define specific section in info.xml for required/bundled libraries and their versions
2) provide script/command to automatically parse composer.lock files and inject said information in info.xml when building an app, before the signing step
3) adjust app installer to verify that we're not installing an app that bundled Guzzle v6 when core provides Guzzle v5. and other conflict detection.

Well, in theory if core already provides a lib, an app wouldn't need it. But currently it is not possible to have consolidated composer files as composer doesn't support this use case...

So the only benefit from the above I'd say is to avoid version clash for things like Guzzle versions, external storage SDK versions, etc.

We might want to limit this to specific library names, not every possible PHP library as there will likely be lots of clashes... To be discussed.

@butonic @jvillafanez @DeepDiver1975 @VicDeo

**Comment by jvillafanez** [comment]
I'm not sure if we should go this way.
The main problem I see is that I have no idea how we can effectively detect incompatibilities between library versions. Assuming that a library version 7 will be incompatible with the previous version might not be true. A similar problem could happen if we assume that the 7.0.9 will be compatible with 7.0.8. We don't have a 100% guarantee.

There is also the problem with a possible de-sync between the composer file and the info.xml one. People might forget to update one or another even if we give them the tools. Assuming that the info.xml file will contain the real info might not be a good idea.

We also need to discuss how are we going to detect conflicts. Maybe in a similar way that the ownCloud's version checks works? Exact version match might not happen.

My main point here is that I don't think this will work flawlessly. It might be fine as a safety mechanism or warning message, but this implies we'll likely need something to bypass the check during the app installation if the admin wants that.

**Comment by PVince81** [comment]
Right. Maybe we should just hand-pick a few libraries we do know are incompatible like Guzzle v5 vs Guzzle v6 and only have these listed there. I agree that it's a complex topic and might not work out.

**Comment by IljaN** [comment]
Maybe we can somehow alias namespaces of two clashing packages with some auto loading trickery. :-1: on rebuilding composer within info.xml. ;)

**Comment by PVince81** [comment]
thanks for the input and confirming that it's not a good idea, closing
