### ISSUE TITLE
Do not pool /notifications when the topbar is not visible 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/core#30482]
Dumping the contents of https://github.com/owncloud/core/issues/30385#issuecomment-365537174 

> I noticed that regular pooling to the /notifications endpoint is also happening under the hood on an open OAuth's "authorize" screen.

> As a rule of thumb, I'd say when the top bar (where the notification container is located) is hidden, we should simply not pool this endpoint for events. I'll create an issue.

**Comment by DeepDiver1975** [comment]
should go into https://github.com/owncloud/notifications

**Comment by SamuAlfageme** [comment]
https://github.com/owncloud/notifications/issues/138
