### ISSUE TITLE
Files conflict dialog is not prepared to deal with case-sensitive storages.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#30502]
### Steps to reproduce

0. Enable a case-sensitive storage app (WND, files_external_dropbox, others).
1. Set up a mount point, granting access if needed.
2. Using oC web ui, upload a file "file.jpg" to the case-sensitive storage.
3. Using oC web ui, upload a file "FILE.jpg" to the case-sensitive storage.

### Expected behaviour
A conflict dialog appears as both files should be considered the same in this kind of storage.

### Actual behaviour
The file conflict dialog appears, but the right section doesn't show anything useful.

Dropbox dialog:

![screen shot 2018-01-10 at 18 06 48](https://user-images.githubusercontent.com/9048796/36307127-f10d2b78-131a-11e8-95d0-6e6540de59b2.png)

WND dialog:
![screen shot 2018-02-16 at 13 03 08](https://user-images.githubusercontent.com/9048796/36307047-9c93bc60-131a-11e8-8775-f7ec71fa58e6.png)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**Cache**
DB

**ownCloud version:** (see ownCloud admin page)
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.0.6.1","versionstring":"10.0.6","edition":"Enterprise","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, tested using WND and dropbox.

**Are you using encryption:** 
No.

**Logs**
Nothing appears in the logs as warnings or errors.

### Client configuration

**Browser**
Chrome

**Comment by PVince81** [comment]
I'm starting to have the feeling that we need to start a new big project: make ownCloud work with case sensitive storages on all levels... which might or might not require rewriting some bigger bits of the filesystem code
