### ISSUE TITLE
Preview seems to not properly unlock files

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30506]
Observed many times when running selenium tests:
```
{"reqId":"tw5k1PGffGkswoDsxK13","level":0,"time":"2018-02-16T10:27:06+00:00","remoteAddr":"172.18.0.3","user":"user1","app":"core","method":"GET","url":"\/remote.php\/dav\/files\/user1\/simple-folder\/lorem.txt?c=1478997b23797c954f7ee8ea250c4c99&x=32&y=32&forceIcon=0&preview=1","message":"Generating preview for \"\/user1\/files\/simple-folder\/lorem.txt\" with \"OC\\Preview\\TXT\""}
{"reqId":"evWmtS6qlZ3OLkHVeCOM","level":4,"time":"2018-02-16T10:27:07+00:00","remoteAddr":"172.18.0.3","user":"user1","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/files\/user1\/simple-folder\/lorem.txt","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"simple-folder\\\/lorem.txt\\\" is locked\",\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/drone\\\/src\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->OCA\\\\DAV\\\\Connector\\\\Sabre\\\\{closure}()\\n#1 \\\/drone\\\/src\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(258): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->emittingCall(Object(Closure), Array, 'file', 'create')\\n#2 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1129): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #53)\\n#3 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('files\\\/user1\\\/sim...', Resource id #53, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/drone\\\/src\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/drone\\\/src\\\/apps\\\/dav\\\/lib\\\/Server.php(279): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/drone\\\/src\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/drone\\\/src\\\/remote.php(175): require_once('\\\/drone\\\/src\\\/apps...')\\n#11 {main}\",\"File\":\"\\\/drone\\\/src\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":206,\"User\":\"user1\"}"}
```

I also observed once on my ownCloud server that when many people requested a preview after posting a public link to a big pic to a chat room, the file was locked for many hours. It is likely that the preview generation code is not properly freeing the locks. Maybe it's missing a `fclose()` ? 

Note that when `fclose()` is missing the locks are likely to be cleant anyway through garbage collection, but I remember observing with PHP 7 that sometimes the garbage collection happens much later, sometimes even within a subsequent PHP call...

Best would be to verify that the preview code path properly closes the file after streaming it.

@DeepDiver1975 @phil-davis

**Comment by PVince81** [comment]
@phil-davis if you find more log snippets from preview-related failures, please post them here

**Comment by PVince81** [comment]
Note that my own reproduced case was on ownCloud 10.0.6 which has the old preview code.

The above log lines came from a CI run and seem to be based on the new preview endpoint/format.

Both likely still point at the same preview generation code.

**Comment by PVince81** [comment]
setting this to p1 as it could potentially solve a lot of the repeated frustration due to randomly failing selenium tests...

@DeepDiver1975 can you look into this ?

**Comment by PVince81** [comment]
@VicDeo I think I remember you being familiar with the preview code too ? Can you debug this ?

**Comment by phil-davis** [comment]
The scenario that most often fails is:
```
  Scenario: overwrite an existing file in a sub-folder                         # /drone/src/tests/ui/features/upload/upload.feature:69
    When I open the folder "simple-folder"                                     # FilesContext::iOpenTheFolderNamed()
    When I upload the file "lorem.txt"                                         # FilesContext::iUploadTheFile()
    And I choose to keep the new files                                         # FilesContext::choiceInUploadConflict()
    And I click the "Continue" button                                          # FilesContext::iClickTheButton()
    Then the file "lorem.txt" should be listed                                 # FilesContext::theFileFolderShouldBeListed()
    And the content of "lorem.txt" should be the same as the local "lorem.txt" # FilesContext::theContentOfShouldBeTheSameAsTheLocal()
      Failed asserting that two strings are identical.
      --- Expected
      +++ Actual
      @@ @@
      -Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,
      -totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae
      -dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit,
      -sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est
      -qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora
      -incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum
      -exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?
      +This is lorem text in the simple-folder.
      +
      +Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      +Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      +Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
      +Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

--- Failed scenarios:

/drone/src/tests/ui/features/upload/upload.feature:69
```
On the webUI it looks like the file should be overwritten, but in actual practice on the server it does not get overwritten. So the test step that checks the file content fails.

In this situation we have just navigated into ``simple-folder`` for the first time. The JS on the page will have sent off a bunch of requests for the previews of the files, and the server will be working hard on generating them. We go and immediately upload another ``lorem.txt``

It is a possible but rather unlikely sequence for a real user to be able to achieve!

I will have a look at how we can wait better for the page to finish loading everything before we start clicking upload. Because maybe there is no ongoing lock left behind - just the transient one that we get unlucky with.

**Comment by phil-davis** [comment]
PR #30513 enhances the UI test(s) that do file uploads which overwrite an existing file. Those upload cases can get a "file locked" returned - and that is a "genuine" part of "the system". In this case, the user may have just navigated to the folder and the thumbnail preview of the existing file is being generate. In other "real life" cases, some other client might be in the process of syncing-uploading a new version of the file, or...

What a "real user" would do if that happens is, they would see the "file locked" notification at the top of the UI, they would think (maybe:), wait a bit, then try the upload again. So I have made the UI test do that (up to 5 times).

It works, and in the test output I can see where it reports detecting the notification text in the UI. When I tries the upload again, it works (because by then the preview thumbnail for the old file has finished being generated.

**Comment by PVince81** [comment]
did we notice any more failures since the merge ? do we need more research ?

**Comment by phil-davis** [comment]
I don't see this happening in UI tests as a failure. The file comes "unlocked" on the next try. So for me, during the thumbnail generation time the file is locked against modification (expected). The lock is freed by the time the upload tries again. I have not seen cases where the lock is "stuck" "left behind".
