### ISSUE TITLE
Password Email wont Set

### ISSUE THREAD

**Issue by wasolu18** [owncloud/core#30511]
Steps to reproduce
1.	Created an test site 
2.	call login page, enter an existing user name but a wrong password
3.	Click on "Forgot password?", received message: Could not send reset email because there is no email address for this username. Please contact your administrator.
4.	Logged back in using user name and password.
5.	Under settings/user keyed in email address – would not save
Expected behaviour
Email address should save
Actual behaviour
Nothing. Email would not save, keep getting notification to add your profile information.
Server configuration
Linux 2.6.32
Web server:
Apache 2.4.18
Web server: Apache 2.4.10
Database: MySQL 5.5.58
PHP version: 5.6.30
ownCloud version: (see ownCloud admin page)
13.0.0 - 13.0.0.14
Updated from an older ownCloud or fresh install:
Fresh install
Where did you install ownCloud from:
Signing status (ownCloud 9.0 and above):
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
List of activated apps:
None trying to work out bug
Nextcloud configuration:
Are you using external storage, if yes which one: no
Are you using encryption: no
Are you using an external user-backend, if yes which one: no
Client configuration
Browser: Firefox 57 / Chrome 63
Operating system: W10
Logs
Web server error log: No entry while doing password reset.
Nextcloud log (data/nextcloud.log): No entry while doing password reset.
Browser log: seems not relevant, is it?

**Comment by PVince81** [comment]
This is the bug tracker of ownCloud, not Nextcloud.

Please reopen there.
