### ISSUE TITLE
Top right "Download" button in shared public folder gives me "pagecurl.tar" as filename in Chrome

### ISSUE THREAD

**Issue by guruz** [owncloud/core#30519]
The file expands nicely on macOS but there should be a nicer filename 
(the folder is NOT called "pagecurl" on the cloud..)

server 10.0.6.1

**Comment by guruz** [comment]
OK @ogoffart just told me the folder he shared to me is called "pagecurl".
I thought pagecurl is some CSS thing that oC server is using.
OK, is that not an accidental information disclosure then? Since this title is not shown anywhere else on the page.

**Comment by PVince81** [comment]
You're right,  maybe it needs to be visible somewhere in the UI.

I think the name also appears in the email sent for public link when an email address was given.

If we'd decide to not use this name, then the question would be what name to use, maybe a boring "download.tar" ?

**Comment by PVince81** [comment]
cc @pmaier1
