### ISSUE TITLE
SSL Certificate " Must be ASCII-pem encoded"

### ISSUE THREAD

**Issue by leeryanrs** [owncloud/core#30531]
Hi there,

I've just freshly installed a new Owncloud server, running Ubuntu 16.04 LTS. 

Owncloud version 10.0.6
All the latest php etc.

I've edited the config.php to allow SSL certificate imports, however whenever I choose my .PEM certificate, I get the error "Please upload an ASCII-encoded PEM certificate."

When i'm quite certain the certificate is indeed that. 

What steps could i follow to debug/resolve?

There's also no errors relating to this upload in the owncloud log.

**Comment by PVince81** [comment]
closing as this issue is rather old

see http://central.owncloud.org to get help as this is likely related to your environment

feel free to reopen if you think this is a bug and still happens in 10.0.10
