### ISSUE TITLE
incorrect installation_wizard.html formating on v10 doc

### ISSUE THREAD

**Issue by rschitz** [owncloud/core#30549]
the version 10 of the install wizard page formating is wrong os it's not possible to copy/paste the strong permission script as it is in the version 9 of the page

v9 (good): https://doc.owncloud.org/server/9.0/admin_manual/installation/installation_wizard.html
<img width="801" alt="screen shot 2018-02-20 at 13 00 11" src="https://user-images.githubusercontent.com/8385646/36422862-17f6e262-163e-11e8-88f8-c75f21f756cc.png">

v10 (bad): https://doc.owncloud.org/server/10.0/admin_manual/installation/installation_wizard.html
<img width="810" alt="screen shot 2018-02-20 at 12 59 49" src="https://user-images.githubusercontent.com/8385646/36422888-2a5dabd4-163e-11e8-9c89-be1049c382a5.png">

**Comment by DeepDiver1975** [comment]
THX - can you please reopen this in our doc repository: https://githhub.com/owncloud/documentation - THX
