### ISSUE TITLE
OwnCloud falsely reports issues with Headers

### ISSUE THREAD

**Issue by margeson** [owncloud/core#30576]
### Steps to reproduce
1. Install LEMP stack (Nginx, not apache)
2. Install 10.0.6
3. Set nginx config as recommended by owncloud
4. Upgrade to 10.0.7
5. Access Admin --> General page and you'll notice the header issues

### Expected behavior
Headers are intact, it's reporting an issue when there isn't one

### Actual behaviour
Report issues with headers
https://i.imgur.com/j35lWcP.png

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
nginx

**Database:**
mariadb

**PHP version:**
php fpm 7.1

**ownCloud version:** (see ownCloud admin page)
10.0.7.2

**Updated from an older ownCloud or fresh install:**
Fresh install of 10.0.6 earlier this week and then patched to 10.0.72 today

**Where did you install ownCloud from:**
apt repo http://download.owncloud.org/download/repositories/10.0/Ubuntu_16.04/

**Signing status (ownCloud 9.0 and above):**
No signing issues reported

```
No errors have been found.
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocpekkq32wgj",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "10.0.7.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.3
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.2
  - theme-example: 1.0.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome

**Operating system:**
Win 10

For security purposes, I cannot supply the log files as it exposes our domain - we cannot have that.

However, see this screenshot. You can see that Chrome reports the headers.
https://i.imgur.com/zboh55U.png

**Comment by 128432b4117** [comment]
@margeson To me it looks like your server is falsely sending the headers multiple times and thus you're getting such a message. This is a deployment issue you need to handle within your webserver.
