### ISSUE TITLE
[Server filesystem] maintenance/data cleanup best practices

### ISSUE THREAD

**Issue by sonaro** [owncloud/core#30583]
Hello,

What is the best practices methodology for performing batch operations on the Owncloud data directory?

Here are some examples of issues to address.  Some of these actions are read-only, and some are preferably batch read-write.

**Batch Operations:**
- legacy import issues (misc temp files scattered, such as .DS_Store files)
- verify file extensions exist for common file types (if a user creates a PDF and deletes ".pdf")
- verify file header / magic number matches file extension for common file types (if a user incorrectly creates/renames a jpeg as png)
- detect/move/archive/delete/warn stale lockfiles
- detect/move/archive/delete/warn large files
- detect/move/archive/delete/warn file path exceeds 250 chars
- files verified by checksum against oc edit log (to detect fs/disk/backup issues for sensitive data)

There appears to be two options to perform these actions.  (Aside from programming another interface to OC)

**Option 1:**
> [mount owncloud using davfs2]
> [perform changes to data directory]
> [unmount davfs2]

Issues:
- Cannot view, and therefore modify/delete, files for other users (unless logged in as every user)
- DAV is extremely slow vs direct fs access ( search:  1,003x slower, delete:  1,032x slower; this does not account for the required occ san  )

**Option 2:**
> occ maintenance:mode --on
> [perform changes to data directory]
> [scan for changes]
>    occ files:scan --all
>    occ files:scan --all --repair
> occ maintenance:mode --off

Issues:
- In all of the documentation it explicitly states to **not** do this
- The documentation of the "--repair" argument is minimal.  Could this be run nightly?
- These changes on the server may not be pushed to the client, resulting in the client re-uploading these files (this may be incorrect, based on legacy functionality)
- The scan changes the OC-reported last modified time for all files, including files not modified or deleted (this may be incorrect, based on legacy functionality)

The goal is to have this run as part of the nightly backup job.  Please weigh in on the pros and cons or any other options that might be available.

Thanks for reviewing this issue in advance.

**Comment by PVince81** [comment]
for any kind of file operations you should do this either through the Webdav API or if you do this within an app that you wrote, the PHP APIs. This is important as it affects the way ownCloud indexes files.

Any operation done directly on the data folder is not supported as ownCloud cannot know or detect when files were moved somewhere else and metadata will get lost. Metadata is linked by file id based on the file id in the oc_filecache table (the index).

When operating on PHP level, there are some functions available for search for files by mime type from inside the index, so those could be used within an app to perform some of the above operations.

In general, maybe writing an app would be the best approach. You'd also have the benefit to be able to register to hooks/events and catch some of the cases you want to clean up before they even happen. (assuming you're not using external storage)

**Comment by PVince81** [comment]
for general help: go to http://central.owncloud.org/

if some part is missing in the documentation write a ticket or pull request to https://github.com/owncloud/documentation
