### ISSUE TITLE
[Feature Request] extend ./occ files:scan for mount points

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#30596]
### Steps to reproduce
1. Having local folders
2. Having mounts (eg a Federation, SMB ect) which are represented as folders
3. ``./occ files:scan --path="user_name/files/foldername_of_mount"``

### Expected behaviour
The mount should be scanned

### Actual behaviour
The mount can´t be scanned because a mount does not create a local folder like:
`` user_name/folder/mount_name``
This means, that a mount cannot be scanned via the occ command

### Feature Request
- Adding a files:scan option to show which (root) folders and mounts the user has
- Adding an option to scan mounts ``./occ files:scan --mount="user_name/mount/foldername_of_mount"``
or
Extending the ``--path="user_name/files/folder"`` functionality to accept mounts

**Examples**
```
./occ files:scan --show=user_name
user_name: folders
  folder1
  folder2
  ...
user_name: mounts
  foldername_of_mount1
  foldername_of_mount2
  ...
```

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** (see ownCloud admin page) 10.0.7

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar

@PVince81

**Comment by mmattel** [comment]
Update:
You cannot initiate scanning of any mount shared (share reciever) which includes federated shares.
So you share a mount, on the target user side it tells "Ausstehend", but scanning manually eg by user_name, by --path does not use the mount point parameter - is this intended or did I miss something?

I also seems that it never does this scanning in background as "Ausstehend" never goes away except you manually enter the folder(s) in the browser.

**Comment by PVince81** [comment]
@mmattel does it not also update when using desktop client ? does it only update when entering the folder in the browser ?

Normally federated shares do not really require scanning because we can get the etag, oc:size and tree information directly through Webdav

**Comment by mmattel** [comment]
**Situation 1:**
Recieving a fed share let´s name it "test", resharing is allowed.
Creating a group that will have access to this fed share, name it testgroup.
Having a desktop client syncing the full fed share test. All fine.
Using the browser, I see a lot of "Ausstehend". This NEVER goes away except when clicking thru all the folders having this status.
Granting another user via testgroup access to test.
The user accesses via browser the reshare (named test), but it is empty (not tried with the client)
Trying to fix content/Ausstehend with ./occ files:scan --path="username/files/test - does not scan.

**Scenario 2:**
user_1 mounts a smb share (scan is made, no Ausstehend), name it smb_mount and reshares it with user_2.
user_2 sees the new folder but all is Ausstehend.
Same as in scenario 1, ./occ files:scan --path="username/files/smb_mount - does not scan.

**Scenario 3:**
user_1 mounts a smb share (scan is made, no Ausstehend)
Force a scan ./occ files:scan --path="username/files/smb_mount - scans without problems

**Conclusio:**
For me it looks like scanning of shared folders on the reciever side does not work (anymore?).

**Comment by mmattel** [comment]
This drives me nuts... 
Just tested scenario 2 again, the "Ausstehend" problem is not longer present.
It is not consistent.
Scenario 1 is unchaged, maybe a different issue?

As a first result I see a potential improvement in the documentation of the files:scan command mentioning that shares recieved including fed shares recieved are not included in scanning.
But this leads me to the poropsal on top about a option showing what is able to be scanned.

**Comment by mmattel** [comment]
I am closing this one and separate the feature request and the issue in different cases
Feature Request: https://github.com/owncloud/core/issues/30641
"Ausstehend" on fed shares: https://github.com/owncloud/core/issues/30642
