### ISSUE TITLE
Disconnect session in personal settings is not valid for ios and Android.

### ISSUE THREAD

**Issue by supermanlinux** [owncloud/core#30603]
Disconnect  conversations in personal settings is not valid for ios and Android.
### Steps to reproduce
1.Click settings
2.Click on personal->Security Manage
3.Clicking the revoke(disconnect) button for android or ios conversation is not valid

### Expected behaviour
Android and ios can cancel the login operation

### Actual behaviour
Android and ios can't cancel the login operation,the web disconnect is works.

### Server configuration
**Database:**10.0.31-MariaDB-0ubuntu0.16.04.2 Ubuntu 16.04
**PHP version:**PHP 7.0.22
**ownCloud version:10.0.6.1
**Where did you install ownCloud from:owncloud-10.0.6.tar.bz2

Thanks for help.

**Comment by PVince81** [comment]
I think what is meant here is that disconnecting sessions for iOS and Android does not seem to actually disconnect them. I remember observing this before, so might be a bug.

@SergioBertolinSG are you able to reproduce this ?

**Comment by SamuAlfageme** [comment]
I believe this would be a duplicate of https://github.com/owncloud/core/issues/28553. Feel free to close if you also find it related.
