### ISSUE TITLE
Ability to disable "Add to ownCloud" button in public link page

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30614]
Currently the settings page allows an admin to prevent users to directly share to remote servers using the share panel autocomplete field, and also prevent users to receive remote shares.

However the setting doesn't disable the "Add to ownCloud" button from the public link page.

There are two options here:

Option 1: whenever outgoing federated sharing is disabled, also disable that button

Option 2: add yet another checkbox to allow disabling this button

In the spirit of "keep it simple" maybe option 1 is the best one.

@pmaier1 thoughts ?

**Comment by inavuk** [comment]
I could take this if it's up for grabs. I'm fairly new, so any tips of where to start are appreciated!

**Comment by pmaier1** [comment]
> In the spirit of "keep it simple" maybe option 1 is the best one.

Agreed. This step would provide consistency (fed sharing is disabled; mounting a public link is disabled as well). Sooner or later someone might want to have fed sharing enabled and still wants to hide the button but this could then also be realized with theming, I think.

**Comment by pako81** [comment]
> Sooner or later someone might want to have fed sharing enabled and still wants to hide the button but this could then also be realized with theming, I think.

Yes, adding to styles.css in theme: 
```
#body-public .header-right button#save-button { 
display: none; 
} 
```
should do the job. Just FYI.

**Comment by inavuk** [comment]
I removed the button as per your instructions by adding the css code to styles.css within core/css. I installed ownCloud and tested that it works. If that sounds right, I'll go ahead with a pull request. Thanks!

**Comment by PVince81** [comment]
CSS is not the correct solution. We need the button to be removed conditionally from the template based on the configuration setting for disabling "outgoing federated shares" in the share settings.

**Comment by Lilus** [comment]
Hi is anybody working on this issue? If not can I start working on it? Thank you

**Comment by inavuk** [comment]
Please do, I haven’t had time to work on it more.

**Comment by Zechro** [comment]
Id like to take a crack at this if its still open.

**Comment by pmaier1** [comment]
FYI - since 10.5 the feature will be hidden when an instance has outgoing federated shares disabled. Ref: https://doc.owncloud.com/server/admin_manual/release_notes.html#other-notable-changes

From my POV this is sufficient for now.
