### ISSUE TITLE
Client: Proxy should automatically deactivate when directly connected to internet

### ISSUE THREAD

**Issue by skillzdev** [owncloud/core#3063]
Client version: 1.2.1

Client: Proxy should automatically deactivate when directly connected to internet (if connection via proxy fails).

And automatically reconnect when back behind proxy (if direct connection fails)

![image](https://f.cloud.github.com/assets/4223343/408607/67aaa90c-ab35-11e2-84ff-6956a223a68d.png)

**Comment by PVince81** [comment]
please raise in https://github.com/owncloud/client if still happening
