### ISSUE TITLE
Users cannot add domains under CORS settings

### ISSUE THREAD

**Issue by pako81** [owncloud/core#30647]
In 10.0.7 under "Personal Settings->Security" options for CORS are shown. 

![image](https://user-images.githubusercontent.com/12248713/36785035-c78fdf32-1c81-11e8-9636-46646111fe50.png)

However, if a normal user attempts to add a domain the following error is displayed:
```
Access forbidden
Logged in user must be an admin
```
 
we should fix it.

@Emil-G @PVince81

**Comment by PVince81** [comment]
I have the feeling this was mostly only tested as admin. The controller methods are missing the clause for allowing non-admins.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/30648

**Comment by Emil-G** [comment]
Cool, please make sure transifex is updated. I could not find translation for this panel.
