### ISSUE TITLE
Regression: share link to contact email does not work any more

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30669]
### Steps

1. Enable the contacts app
2. In the sharing settings, allow users to send email for link shares
3. Create a contact "Max Mustermann" with email address "max@example.com"
4. Create a folder "test"
5. Create link share for "test"
6. In the email field, type "max" and wait

### Expected result
Dropdown opens with "Max Mustermann" as entry

### Actual result
No dropdown / autocomplete, no server request.

### Version
stable10
Regression from 10.0.7.

To find the problem, grep for "getShareWithEmail" on 10.0.7 and stable10: on 10.0.7 the code in question still exists in core/js/sharedialogmailview.js but in stable10 it's completely goen.

@felixheidecke did you remove this on purpose when working on the personal note ?

**Comment by PVince81** [comment]
I also see that we might have some more complications when we switch to the tag-like view from https://github.com/owncloud/core/issues/29695.

Basically we'll need to wire up select2's autocomplete code to the endpoint mentioned in this ticket. So instead of bringing back the old code I suggest to focus on bringing the autcomplete back as part of https://github.com/owncloud/core/pull/30645

**Comment by DeepDiver1975** [comment]
killed in here - https://github.com/owncloud/core/commit/1916d25a00072d45baa31d3583cc06f9120ec80c#diff-99ea0d0c9aa0d63172b459efb8c4cb42L133

**Comment by felixheidecke** [comment]
Japp … I killed it in a misunderstanding. Bringing it back.
