### ISSUE TITLE
Link share dialog email must not list local users

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30670]
### Steps

1. Create a new user "user1" and set the email address to "user1@example.com"
1. Enable contacts app
1. Create a new contact with email address "userx@example.com"
1. In the sharing settings, allow users to send email for link shares
1. Create a folder "test"
1. Share "test" with link
1. In the email field in the dialog, type "user" and wait

### Expected
Only "userx@example.com" appears

### Actual
Both users including the local user "user1@example.com" appear.

### Version
ownCloud 10.0.7
(note: broken completely on stable10, don't try there: https://github.com/owncloud/core/issues/30669)

The code in question users the ContactsManager and has no knowledge where the users come from.
Not sure if there is an easy way to prevent it to search through local users.

I suspect that it might also look through the system address book or federated address book so could also find other users.

@pmaier1 maybe to be discussed what to do with this feature. Maybe we should just limit this to contacts from the contacts app ?

**Comment by DeepDiver1975** [comment]
> I suspect that it might also look through the system address book or federated address book so could also find other users.

yes and this was added back then on purpose

**Comment by DeepDiver1975** [comment]
> Maybe we should just limit this to contacts from the contacts app ?

no - searching  federated addressbooks was an explicit requirement

**Comment by PVince81** [comment]
ok, so just remove the local users part ?

**Comment by PVince81** [comment]
> searching federated addressbooks was an explicit requirement

I do wonder why... People are supposed to share using direct federated shares, no link shares. Maybe this was added before we had the "direct federated share" feature ?

**Comment by PVince81** [comment]
@DeepDiver1975 do you remember where the requirement was specified ? Maybe it is obsolete now, need to see the details to find out.

**Comment by PVince81** [comment]
I see there's a key in the result `isLocalSystemBook` which is set to true for local users but is not set for contacts.

Do you know if federated users also have false ? If yes we could use that value to filter out local users from the results.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 do you remember where the requirement was specified ?

not really - this was 2+ years back ....

**Comment by DeepDiver1975** [comment]
> I see there's a key in the result isLocalSystemBook which is set to true for local users but is not set for contacts.
> 
> Do you know if federated users also have false ? If yes we could use that value to filter out local users from the results.

I'd need to debug this ....

**Comment by PVince81** [comment]
I managed to also have federated users included after federated server pairing. If a remote user has an email address configured, it will be able to be completed here.

**Comment by PVince81** [comment]
Observation: the remote user doesn't have `isLocalSystemBook` set.

So to identify users to exclude:
- exclude if `isLocalSystemBook` is set
- exclude if "CLOUD" is set ??

**Comment by pmaier1** [comment]
Can someone find a scenario where this is actually helpful? If not, I would 

a) Remove it completely and make the autocomplete configurable in the context of Contacts app (applying to all locations where Contacts autocomplete can be used).

or

b) Make it configurable (autocomplete on/off) and only display suggestions coming from the Contacts app

**Comment by pmaier1** [comment]
Talked to @hodyroff and we conclude that either removing completely or adding a config switch to core (and only display contacts!) would both be ok. Making it configurable in the contacts app probably doesn't fit well as you can have contacts in the DB without having contacts app enabled.

Would be good to get this into 10.0.8 together with https://github.com/owncloud/core/pull/30645.

**Comment by PVince81** [comment]
@DeepDiver1975 any objection to removing the email autocomplete completely ? The loss of feature would be for contacts search mostly.

**Comment by PVince81** [comment]
ok so after https://github.com/owncloud/core/pull/30645 is merged and backported, I'll remove the autocomplete endpoint and also the frontend code that calls it. Let's not do this directly in https://github.com/owncloud/core/pull/30645 as I want this to be a separate PR for historic purposes.

**Comment by PVince81** [comment]
@DeepDiver1975 can you take care of this ? this is mostly about backend code removal

**Comment by cdamken** [comment]
![1220563019346_f](https://user-images.githubusercontent.com/7264495/38116208-7076cf7c-33af-11e8-9511-63924a44be53.jpg)

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 any objection to removing the email autocomplete completely ? The loss of feature would be for contacts search mostly.

YES - for sure a lot of objections!

We can fix the search to limit this to real addressbooks only - but killing this feature is a no go.

@felixheidecke please gimme back the autocomplete - I take care of the backend search capabilities

**Comment by PVince81** [comment]
this PR https://github.com/owncloud/core/pull/30987 brings back autocomplete but removes local and federated users. so it's limited to user address book which is populated by the contacts app

**Comment by PVince81** [comment]
will be in 10.0.8
