### ISSUE TITLE
Deleting a user does not clear user-created external mounts

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/core#30694]
When re-creating a user, external mounts stay persistent (which leads to a potential data leak)

### Steps to reproduce
1. As admin, create a user (i.e. `testuser` )
2. Login as the newly created user (`testuser`)
3. As testuser mount an external storage (`My Storage`) - check that external storage is successfully mounted
4. Logout as testuser
5. Switch back to admin user -> delete the user `testuser` (& verify that the user does not exist anylonger)
6. Re-create the user `testuser`
7. Login as `testuser` 
8. See that the previously created external storage is still present

### Expected behaviour
When deleting a user, I expect that all external storages the user has created, are deleted with it.
When re-creating the user -> the external storages are no longer present in that users files folder

### Actual behaviour
After re-creating - the user has access to the previously created external storages 

### Server configuration
**Operating system**:
Docker `owncloud/server`

**ownCloud version:** (see ownCloud admin page)
10.0.4 & 10.0.7 

**Where did you install ownCloud from:**
docker

### Logs

No error in the logs

**Comment by sharidas** [comment]
Not sure about the complexity of the problem. I assigning this issue to myself.

**Comment by PVince81** [comment]
to be rescheduled
