### ISSUE TITLE
Security->Sessions uses "ownCloud" instead of branded name

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/core#30699]
Hardcoded "ownCloud" here:
  
https://github.com/owncloud/core/blob/cc7944da16c78472c659d67b1eb83b8766fff1ef/settings/templates/panels/personal/tokens.php#L9
  
  
## Actual behavior:
It seems that this line: "These are the web, desktop and mobile clients currently logged in to your ownCloud." does not reflect the theme enterprise name. 
  
![owncloud](https://user-images.githubusercontent.com/33026403/36981655-040cddc4-208e-11e8-8bb8-6e58f4f25afc.png)

## Expected behavior:
I would expect that name to also be "branded".
  
00009089

**Comment by PVince81** [comment]
@VicDeo quick one ?
