### ISSUE TITLE
[bug]Can not to upload avatar after upload one picture right now ,must reload the page first

### ISSUE THREAD

**Issue by supermanlinux** [owncloud/core#30692]
Can not to upload avatar after upload one picture right now ,must reload the page first.
### Steps to reproduce
1.go to personal settings page
2.click the upload button and select an image
3.after the image is complete
4.if you want to change avatar,if you don't reload page first,you can't upload image,the upload buttoon is disabled.If you click the delete button,then you click the upload button,it's the same.

### Expected behaviour
If I want to change avatra after I upload one image right now,it can upload.

### Actual behaviour
The upload button is disabled.

### Server configuration
**Database:**10.0.31-MariaDB-0ubuntu0.16.04.2 Ubuntu 16.04
**PHP version:**PHP 7.0.22
**ownCloud version:10.0.6.1
**Where did you install ownCloud from:owncloud-10.0.6.tar.bz2

**Comment by phil-davis** [comment]
Which browser?

It works for me in Firefox 58
