### ISSUE TITLE
download.owncloud.org is down?

### ISSUE THREAD

**Issue by andybowser** [owncloud/core#30708]
### Steps to reproduce
1. tried to download updates from download.owncloud.org, but fails.
2. https://isitdownorjust.me/download-owncloud-org/

### Expected behaviour
Downloads work.

### Actual behaviour
404 not found when doing apt-get
Timeout in browser when going to page. Also, timeout from the https://download.owncloud.org/download/repositories/stable/owncloud/index.html page on the main downloads page on website.

**Comment by phil-davis** [comment]
At the moment for me, it comes up with "Page moved." and redirects back to the home page.

**Comment by andybowser** [comment]
I'm just getting a connection timeout. And any updates through apt-get is coming back with a 404 error. https://download.owncloud.org/download/repositories/stable/owncloud/index.html from the main downloads page times out as well.

**Comment by VicDeo** [comment]
seems to be back again

**Comment by andybowser** [comment]
Yep. The url for the apt repo seems to have changed from stable to production. All working though.
