### ISSUE TITLE
integrity checker explodes when result set is too large

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#30711]
If the integrity checker runs, and the result is too large then it cannot be stored in the database since the maximum value size is 4000 chars. See screenshots.

![image002](https://user-images.githubusercontent.com/660805/37033676-a5963ab8-213e-11e8-85ed-2c020c57350b.png)
![image001](https://user-images.githubusercontent.com/660805/37033695-b64b292c-213e-11e8-8c3b-0aa55976e6bb.png)

**Comment by tomneedham** [comment]
Although this happens on oracle in the screenshots I believe it also happens on other databases because there is still a length limit on the result set

**Comment by PVince81** [comment]
Yeah, I saw this happening on Mysql when once I had a full "owncloud" subfolder after mis-extracting.

Maybe we should only store the first 20 entries in the database or find another way...

**Comment by tomneedham** [comment]
> Maybe we should only store the first 20 entries in the database or find another way...

I think storing whatever fits is fine - by that point the user clearly has an issue and needs to dig into it.
