### ISSUE TITLE
Appliance 10.0.3 upgrade to 10.0.7

### ISSUE THREAD

**Issue by expander19** [owncloud/core#30729]
hie

with appliance esx juste new installed

when i execute upgrade i have :

Initializing
Current version is 10.0.3.3
Online version is 10.0.7 [stable]
Checking system
Creating a checkpoint
Downloading
Updating core
Extracting source into /var/lib/univention-appcenter/apps/owncloud/data/files/updater-data/_oc_upgrade/10.0.7

Copying the application comments
Copying the application configreport
Copying the application dav
Copying the application encryption
Copying the application external
Copying the application federatedfilesharing
Copying the application federation
Copying the application files
Copying the application files_external
Copying the application files_sharing
Copying the application files_trashbin
Copying the application files_versions
Copying the application files_videoplayer
Copying the application firstrunwizard
Copying the application market
Copying the application notifications
Copying the application provisioning_api
Copying the application systemtags
Copying the application templateeditor
Copying the application theme-example
Copying the application updatenotification
Copying the application user_external

 
 [GuzzleHttp\Exception\ServerException] 
 Server error response [url] https://localhost/owncloud/index.php/occ/upgrade [status code] 500 [reason phrase] Internal Server Error 
 

upgrade:executeCoreUpgradeScripts

best regard
Gilles

**Comment by patrickjahns** [comment]
@voroyam 
can you have a look here

**Comment by voroyam** [comment]
Yes? 

Web updater breaks the appliance.

Update only via app.

**Comment by voroyam** [comment]
https://doc.owncloud.org/server/latest/admin_manual/appliance/howto-update-owncloud.html

**Comment by PVince81** [comment]
didn't we disable the web updater in the appliance ?

**Comment by voroyam** [comment]
we ( @tboerger  ) did.

But this is the appliance with preinstalled 10.0.3 app.

We disabled the updated in the appliance with 10.0.4 app.

**Comment by patrickjahns** [comment]
Closing as this is related to the appliance - for updating the appliance please use the official update process from Univention
