### ISSUE TITLE
oc_appconfig installed_version empty causes issues with app upgrades

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#30724]
I was testing some upgrades between 9.1.7 (tarball) and 10.0.7 (tarball) and noticed some strange behaviour. Some old apps use a `version` file instead of a `<version>` tag in the info.xml - which causes them to have an empty value stored in `oc_appconfig:$appid:installed_version`.

On upgrade to an ownCloud 10 version (I was testing 10.0.7 tarballs) this value is compared with the version in the apps folder supplied by the tarball, and is somehow deemed to not need an upgrade. For example, 9.1.7 the shibboleth app is 2.0.0 and in 10.0.7 the version is 3.1.2 and there is a migration that must run - which does not happen.

If, before the upgrade, I manually insert the version into the database - on upgrade, the versions are correctly compared and the upgrade is performed on the app.

Version comparison is done here: https://github.com/owncloud/core/blob/master/lib/private/legacy/app.php#L921

@PVince81 @VicDeo

**Comment by PVince81** [comment]
@VicDeo can you have a look ?

**Comment by tomneedham** [comment]
You can verify that an upgrade on an app is not performed, if it has migrations, and they do not appear in oc_migrations after the upgrade.

**Comment by tomneedham** [comment]
It seems this is also the cause of `occ app:list` to show version as 'true'. The correct version is not stored in the db. The owncloud version is upgraded, and the new app code is used but the correct upgrade procedure is not executed so migrations / repair steps are not run.

**Comment by VicDeo** [comment]
tricky one...  there is no chance to repair the version in `oc_appconfig` if  a new code is in the app dir already

**Comment by VicDeo** [comment]
@tomneedham @PVince81 so... feel the difference
https://github.com/owncloud/core/blob/stable10/lib/private/App/AppManager.php#L361-L370
https://github.com/owncloud/core/blob/stable10/lib/private/legacy/app.php#L622-L624

**Comment by VicDeo** [comment]
ok... 
According to the commit history 9.1.x does **NOT** support `version` file, see https://github.com/owncloud/core/pull/22264
so any app that is claimed compatible with 9.1 should have version in `appinfo.xml`

**Comment by VicDeo** [comment]
as for the solution, I'd suggest to 
- disable any app that has no version  in appinfo.xml on upgrade
- update all app versions not fitting into `/\d+\.\d+.*$/` pattern to be `0.0.1`  within a preupgrade repair step.

@PVince81 @tomneedham what do you think of this approach?

**Comment by VicDeo** [comment]
ah, wait since https://github.com/owncloud/core/pull/30188 doesn't touch `getAppVersions` so I won't mess with this PR.
In this case I can validate versions after they are fetched from DB in the same manner.

**Comment by PVince81** [comment]
I like the idea of replacing with version 0.0.1 dynamically to make it work. If that covers properly all code paths then it's great.

**Comment by VicDeo** [comment]
it's more tricky that I thought initially... I think it is worth to move the code from InfoChecker with InfoParser.
Because appinfo.xml is not validated against required fields on install and C&Ping `isset($data['version'])` here and there is suboptimal.

**Comment by VicDeo** [comment]
damn... this is the thing that is intended to filter `null` entries. And it does it for a reason https://github.com/owncloud/core/blob/master/lib/private/AppConfig.php#L279

so the target is `AppConfig::loadConfigValues` somewhere above this line https://github.com/owncloud/core/blob/master/lib/private/AppConfig.php#L305

But a decent appinfo.xml validation when the app is enabled/updated is a still nice-to-have.
