### ISSUE TITLE
The view "users of group" crashes, if a user has a number as user_id.

### ISSUE THREAD

**Issue by weber-ebusiness** [owncloud/core#30727]
Steps to reproduce:
1. Create a user with "42" as username and assign it to a group.
2. Click on the appropriate group in the left column of the user management tool to get a list of its users.

Result: The loading animation won't disappear, because the ajax request, which should load the user list, got a 500 error.

The error occurs in `settings/Controller/UsersController.php:227`, because `userManager->get` checks, if `$uid` is a string. If `$uid` is not a string, it returns `null`.

This will crash the function call to `formatUserForIndex` (`settings/Controller/UsersController.php:301`), because its argument is of type `IUser`, but it got `null`.

**Comment by phil-davis** [comment]
Confirmed on current master. These days the username has to be a minimum of 3 chars, so create a user ``123`` and put them in a group. Then try to display the group in the users page.

**Comment by phil-davis** [comment]
PR #30732

**Comment by karakayasemi** [comment]
Looks like already fixed with #30732. Feel free to open if needs anything more.
