### ISSUE TITLE
modifiying the path from the log does not change the oc_jobs log rotate configuration.

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#30746]
I had `/mnt/owncoud/data/owncloud.log`

and I moved the log in the config.php to `/home/www-data/owcloud.log`

I saw in the oc_jobs table:

```
|   17 | OC\Log\Rotate                                     | "\/mnt\/owncloud\/data\/owncloud.log" |......
```

I had to change it manually

---

I have not the log rotate installed, but if I make changes in the structure, IMO should follow the changes.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/24544 (Changing own password logs you out), https://github.com/owncloud/core/issues/10519 (WebDav access under Linux doesn't work after update without changing the configuration), https://github.com/owncloud/core/issues/8782 (More log entry does not work), https://github.com/owncloud/core/issues/276 (fullsize images does not rotate), and https://github.com/owncloud/core/issues/8756 (Cursor does not change when hovered on icons).

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/issues/25970
