### ISSUE TITLE
acessing server from "untrusted domain"

### ISSUE THREAD

**Issue by ChainChomp** [owncloud/core#30749]
Hey guys, I recently changed my router and could no longer access my personal owncloud server. it states that. You are accessing the server from an untrusted domain.

Please contact your administrator. If you are an administrator of this instance, configure the "trusted_domains" setting in config/config.php. An example configuration is provided in config/config.sample.php or at the documentation. 

I was wondering if anyone could walk me through how to get it to give me access again.

thank you for your time.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/11912 (Support separate domains for untrusted user-content), https://github.com/owncloud/core/issues/29688 (Link to documentation for untrusted domains setting), https://github.com/owncloud/core/issues/25839 (Warning: Trusted domain error - Netcraft SSL Server Survey), https://github.com/owncloud/core/issues/9637 (6.0.3 untrusted domain), and https://github.com/owncloud/core/issues/12004 (Untrusted Domain Wizard works not with non-default port).

**Comment by PVince81** [comment]
please ask for help in http://central.owncloud.org/

also see http://owncloud.org/support

basically check your config.php's trusted domain settings and make sure it matches your new domain/IP
