### ISSUE TITLE
Folder name not display properly in bread crumb  in mobile device width 320 * 480

### ISSUE THREAD

**Issue by kapilnadiyapara** [owncloud/core#30759]
### Steps to reproduce
1. Login to owncloud in mobile device has width 320 * 480 
2. Goto nested folder in owncloud files
3. You can found that in bread crumb the folder name display as .... (dots) instead of fullname

### Expected behaviour
In mobile device it should be display some character of folder name instead of ...(dots)

### Actual behaviour
Currently in mobile device folder name is displaying ... (dots) in bread crumb

### Server configuration
**Operating system**:
Ubuntu 16.04 LTS 64x

**ownCloud version:** (see ownCloud admin page)
10.0.4 (Stable)

See the attached file of that issue . You can found that in bread crumb you can found ... (dots) while actual folder name is Test12345

![bread_crumb](https://user-images.githubusercontent.com/3987679/37329304-5325c57a-26c3-11e8-9802-0072fbe86f95.png)

After dig in the problem found that this line https://github.com/owncloud/core/blob/master/apps/files/js/breadcrumb.js#L230 create problem. Instead of display ... it should be display some character of folder name.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/143 (Folder names with & in them are not properly handled), https://github.com/owncloud/core/issues/9107 (Identical folder names not displayed in External Storage Admin area), https://github.com/owncloud/core/issues/2374 (Problem with folders when Login-Name != Display-Name), https://github.com/owncloud/core/issues/1336 (“Ü” in Folder names), and https://github.com/owncloud/core/issues/12371 (Folder name cannot start with - [).
