### ISSUE TITLE
no load admin page nginx 504 Gateway Time-out

### ISSUE THREAD

**Issue by ValTer25** [owncloud/core#30758]
Server configuration

Operating system:
Centos 7
Web server:
nginx 1.12.2
Database:
5.5.56-MariaDB
PHP version:
7.0.27
ownCloud version: (see ownCloud admin page)
9.0.10.2
Updated from an older ownCloud or fresh install:
from 9.0

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.

**The content of config/config.php:**

{
    "system": {
        "instanceid": "octf8h0oes9h",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "REMOVED SENSITIVE VALUE",
            "REMOVED SENSITIVE VALUE",
            "REMOVED SENSITIVE VALUE",
            "REMOVED SENSITIVE VALUE",
            "REMOVED SENSITIVE VALUE"
        ],
        "datadirectory": "\/data",
        "overwrite.cli.url": "https:\/\/REMOVED SENSITIVE VALUE\/",
        "dbtype": "mysql",
        "version": "9.0.11.2",
        "dbname": "owncloud_db",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 4,
        "theme": "",
        "maintenance": false,
          }
}

**List of activated apps:**

Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - configreport: 0.1.1
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - federation
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
firefox 56
**Operating system:**
windows 10
#### Web server error log
no

#### ownCloud log (data/owncloud.log)
no

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/19962 (504 Gateway Time-out), https://github.com/owncloud/core/issues/9625 (Admin interface 504 Gateway Time-out), https://github.com/owncloud/core/issues/22723 (504 Gateway Time-out  nginx (when using Hubic Storage)), https://github.com/owncloud/core/issues/17970 ((Only) Admin Settings Page not showing/loading in OC 8.1), and https://github.com/owncloud/core/issues/22960 (Admin page down after update to 9.0).

**Comment by ValTer25** [comment]
not work for me

**Comment by ValTer25** [comment]
update to 10
