### ISSUE TITLE
Replace share panel with the one provided by Phoenix

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30779]
The goal is to have an app that contains the frontend for the sharing app.
Currently the files_sharing app and some pieces of core contain the following components:

1) Sharing sidebar
2) Sharing file lists "Shared with others", "Shared with you" and "Shared with link"

Considering that we're already reworking the UI of the sharing sidebar as part of the [Phoenix](https://github.com/owncloud/phoenix) project, we'd like to provide a way to reuse said effort and make it available in 10.0 as well.

To do so, we need to move the components in question into a separate app which will be based partly on the existing [Phoenix](https://github.com/owncloud/phoenix) sharing mock ups and part of the old code to wire it up to the backend.

Having this as an app is important to be able to update this independently from the OC platform.

## Plan

1) Phoenix sharing sidebar panel must become an own app: https://github.com/owncloud/phoenix/issues/37. The app will register its own "Sharing" sidebar tab.

2) Make sure that UIKit doesn't conflict with the current CSS: https://github.com/owncloud/core/issues/30778. This is important because without this the UIKit CSS from the new sharing frontend will look broken.

3) Remove the sidebar panel code in files_sharing / core to make sure there is only one "Sharing" tab. One alternative would be to have the core code detect if there is already another tab registered and skip it. If the app is not installed it could fall back to the old code. (to be discussed!)

**Comment by PVince81** [comment]
This brings many benefits:

- the ability to use the future sharing frontend with 10.0 and bring in some of its improved UX
- much cleaner code for the sharing frontend

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/30394 (Display original share owner in share panel), https://github.com/owncloud/core/issues/30741 (Share options missing from web admin panel), https://github.com/owncloud/core/issues/7263 (Provide Feedback when Sending Email on Share), https://github.com/owncloud/core/issues/8359 (Provide a super user for sharing folders of all users), and https://github.com/owncloud/core/issues/17444 (shared folder synchronization fails because of one file).

**Comment by PVince81** [comment]
as I understand this was supposed to be part of sharing 3.0 for 10.0 as we talked about how to port the new share panel to work with 10.0. (seeing that this has the v11 label for 11 only)

@pmaier1

**Comment by PVince81** [comment]
@felixheidecke sounds good, thanks

**Comment by PVince81** [comment]
should we call is files_sharing_ui or files_sharing_frontend ? @DeepDiver1975 

at first it will contain the code inherited from Phoenix and later we can move over the rest of the frontend code (if anything remains after Phoenixification/Vueification)

**Comment by felixheidecke** [comment]
This is the repo: https://github.com/owncloud/files_sharing_fe

**Comment by PVince81** [comment]
@felixheidecke please provide a more detailed plan of tasks in this ticket
