### ISSUE TITLE
Clean up CSS to make room for UI Kit

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30778]
When using UIKit in apps, some of UIKit's styles are broken because OC core has too strong overrides.

We need to clean this up to make room for UIKit to work.

Some work has started here: https://github.com/owncloud/core/pull/30166

**Comment by PVince81** [comment]
Required for https://github.com/owncloud/core/issues/30779

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/29138 (Make UI Tests run on Edge browser), https://github.com/owncloud/core/issues/29284 (Make UI tests run in current Firefox browser), https://github.com/owncloud/core/issues/27560 (Make the UI complain if unsupported php_sapi_name is used), https://github.com/owncloud/core/issues/21643 (Make web UI use the dav v2 endpoint), and https://github.com/owncloud/core/issues/11496 (Make .htaccess cache JS and CSS by default).

**Comment by PVince81** [comment]
obsolete, no UIKit in 10.0, only in Phoenix
