### ISSUE TITLE
API tests don't take into account that the user has already files/folders from skeleton

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#30782]
Take this test: 
```
Scenario: Share of folder and sub-folder to same user - core#20645
		Given user "user0" has been created
		And user "user1" has been created
		And group "group0" has been created
		And user "user1" has been added to group "group0"
		When user "user0" shares file "/PARENT" with user "user1" using the API
		And user "user0" shares file "/PARENT/CHILD" with group "group0" using the API
		Then user "user1" should see the following elements
			| /FOLDER/           |
			| /PARENT/           |
			| /CHILD/            |
			| /PARENT/parent.txt |
			| /CHILD/child.txt   |
                And the HTTP status code should be "200"
```
from https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiMain/sharing-v1.feature#L480-L493

the user receives a shared folder called `PARENT` but has already a folder with the same name from the skeleton folder. So this test will pass also without the line `When user "user0" shares file "/PARENT" with user "user1" using the API`
This test does **not** test the sharing of a folder to a user. For this example the list in the `Then` step needs to be enhanced to: 
```
			| /FOLDER/                 |
			| /PARENT/                 |
			| /PARENT/parent.txt       |
			| /PARENT%20(2)/           |
			| /PARENT%20(2)/parent.txt |
			| /CHILD/                  |
			| /CHILD/child.txt         |
```
There are more examples like that, so there are a lot of tests that do not really test the intended behaviour.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/23949 (Cannot download a skeleton file that has been moved into another folder), https://github.com/owncloud/core/pull/30496 (Add API tests for restoring a file deleted from a folder), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), and https://github.com/owncloud/core/issues/10728 (localized skeleton folders).
