### ISSUE TITLE
Some Images not loaded

### ISSUE THREAD

**Issue by Harry-89** [owncloud/core#30799]
Hello,

I have installed a brand new Owncloud on Ubuntu Server 17.10 with Apache2 and php7

All Owncloud Files are in the folder /var/www/owncloud.

I have created a vhost with the following settings

<VirtualHost *:443>
     DocumentRoot /var/www/owncloud/
     ServerName NAME
     ServerAlias NAME

     SSLEngine on
     SSLCertificateFile      /etc/ssl/certs/certpem
     SSLCertificateKeyFile /etc/ssl/private/cert.key

     ErrorLog ${APACHE_LOG_DIR}/error.log
     CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>

But when I open a browser and go into settings, some images aren't loading.
![image](https://user-images.githubusercontent.com/6565913/37513402-50a79a5a-2905-11e8-9e6c-bca2ad73cc94.png)

Where is my mistake?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/13710 (Users view doesn't load), https://github.com/owncloud/core/issues/18463 (Image app loads forever - client sent too long header name or value), https://github.com/owncloud/core/issues/27790 (files_sharing load problem), https://github.com/owncloud/core/issues/1167 (Can't share images for real), and https://github.com/owncloud/core/issues/276 (fullsize images does not rotate).

**Comment by PVince81** [comment]
This is a bug tracker not a support platform.

Please see owncloud.org/support and ask your question on http://central.owncloud.org/ where someone might be able to help find environment issues
