### ISSUE TITLE
proper CSS coding guidelines

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#308]
Once I get to it, I’ll rework the CSS guidelines and also check all the files. Thoughts for now:

No damn discussions about using Sass / SCSS / Compass. Doesn’t solve any of our problems and will only introduce new ones, plus a barrier to entry.

Generally speaking, we follow [Google’s CSS coding guidelines](http://google-styleguide.googlecode.com/svn/trunk/htmlcssguide.xml).

No single-line. Every rule gets a line. It’s not sorted alphabetically though but by relation:
* position and metrics
* font and color
* effects like box-shadow and border-radius

Use tabs everywhere for indentation of course, no spaces (as per the [global coding guidelines](http://owncloud.org/dev/contribute/))
Indent blocks depending on the DOM structure so it’s easier to see 
As soon as 2 apps use the same CSS, move it into core.
No inline styles, ever.
No leading zeros for decimal values.
No unit when value is 0.
No _underscores, instead use -dashes.
Use only single 'quotes'. 
We should look into using [prefixfree](http://leaverou.github.com/prefixfree/), also see #201.
Instead of using !important, look into fixing the underlying CSS specificity issue.

Also, I guess we have to say something about ids and classes. What’s the latest reason to not use ids in CSS apart from that you _might_ use the same style again for another element (which is moot in our case of using it for »list« [ex leftcontent] and »detail« [ex rightcontent]).

cc @Raydiation

**Comment by Xenopathic** [comment]
@jancborchardt Do you want to merge this with the coding guidelines in the documentation?

**Comment by jancborchardt** [comment]
@Xenopathic yes, this and https://github.com/owncloud/documentation/issues/160 as well should just be merged with the current stuff in the documentation as they are now. I didn’t come around to it yet – any help is appreciated.

**Comment by Volker-E** [comment]
This seems like a collection of various CSS topics, not only guideline related. @jancborchardt it should definitely be merged with the coding guidelines/standards issue. Is there a coding-guidline.md or similar, where we could add our thoughts, issues and possible topics to address around?

I've found that [WordPress Coding Standards](http://codex.wordpress.org/WordPress_Coding_Standards) have increased in quality recently. A good one-document example is http://sass-guidelin.es/ - I think it should also feature some nice project inherit styling itself to be appealing to new project contributers.

Best outcome IMHO would be a document that uses core's CSS and could be exported to an md file as well?!

**Comment by jancborchardt** [comment]
@Volker-E so there are 2 pages on the website regarding that:

One is the design page: https://owncloud.org/contribute/design/
Source: https://github.com/owncloud/owncloud.org/blob/master/page-design.php

The coding guidelines in the documentation: https://doc.owncloud.org/server/8.0/developer_manual/general/codingguidelines.html#user-interface
https://github.com/owncloud/documentation/blob/master/developer_manual/general/codingguidelines.rst#user-interface
There’s also a part about CSS which can be pretty much removed: https://github.com/owncloud/documentation/blob/master/developer_manual/general/codingguidelines.rst#css

I would prefer to have it all the stuff regarding design in one place. Preferably on the design subpage. Or we just keep the design subpage to resources and the team, and all guidelines go into a separate »design guidelines« document in the docs.
What do you think @Raydiation @owncloud/designers @Volker-E?

**Comment by Raydiation** [comment]
CSS coding guidelines belong into the coding guidelines, app design guidelines (HIG) belong into a separate section.

**Comment by Volker-E** [comment]
From my experience from other diverse (also open source projects) all those should go into one place and live as subpages, where different core contributers or teams can work on. Like a handbook. If they are living in different places, finding a bigger picture is in my experience much harder. 

Also there are times when for example back-end specialists want or will have to write frontend code and providing them with one address to go to definitely helps. And there's the momentum of contributors wanting to learn and to participate in other sections of the application, so a strict separation doesn't seem to have advantages to me.

**Comment by jancborchardt** [comment]
Yeah, so I would say it might be better to split up the different languages for the coding guidelines. Otherwise it’s one really long document you quickly lose overview of.
