### ISSUE TITLE
sharer not displayed correctly when resharing 

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#30809]
### Steps to reproduce
1. share from "uu1" to "uu2"
2. share form "uu2" to "uu3"
3. as "uu3" compare "All files" page and the "Shared with you page"

### Expected behaviour
in both cases the same user should be displayed as the one who shared the file/folder

### Actual behaviour
In "All files" the owner is displayed

![image](https://user-images.githubusercontent.com/2425577/37585837-8c3021b2-2b82-11e8-893d-bc332002ad94.png)

In "Shared with you" the initiator is displayed
![image](https://user-images.githubusercontent.com/2425577/37585874-9e66f77a-2b82-11e8-8b47-565d0f1045d4.png)

### Server configuration
**Operating system**:
Ubuntu 17.10
**Web server:**
Apache2
**Database:**
Sqlite
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
10.1 prealpha
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/2569 (New group dialogue not correctly displayed IE9), https://github.com/owncloud/core/issues/17569 (Share Link upload activity is not correctly displayed in the Activity Feed), https://github.com/owncloud/core/issues/10072 (File display is not correctly), https://github.com/owncloud/core/issues/16409 (Web Interface does not display correctly in IE9), and https://github.com/owncloud/core/issues/20751 (Resharing is not allowed).

**Comment by PVince81** [comment]
I think we should show the initiator in the file list indicator, for both "All files" and "Shared with You".

The bug is likely because this information is retrieved through completely different APIs (Webdav for "All files" and OCS Share for "Shared with you").

**Comment by PVince81** [comment]
set to p3 unless @pmaier1 thinks it's more important, then p2

**Comment by jvillafanez** [comment]
The easy solution would be to use the file owner in the "shared with you" view. This is quite easy and won't require API changes.
In addition, I think we can show the owner and the initiator in the "shared with you" view and leave the "all files" view as it is. The idea is to have the "shared with you" view (and other views) as an specialized view with extra information, in this case for shares.

In any case, I'd rather wait until https://github.com/owncloud/core/pull/30106 is merged to prevent conflicts.

**Comment by PVince81** [comment]
let's use resharer everywhere, cc @pmaier1

**Comment by jvillafanez** [comment]
I think it makes more sense to leave the files view as it is, showing the owner of the share, and use the "shared with you" (and maybe others) as specialized views. In this case, the "shared with you" can show both the owner and the resharer, and maybe some other interesting things for shares.

I'm not sure if webdav (and so the files view) have access to the resharer at the moment. We might need additional changes otherwise.

**Comment by PVince81** [comment]
deferred
