### ISSUE TITLE
[feature request] Reverse search for system tags (Not in) 

### ISSUE THREAD

**Issue by zb2oby** [owncloud/core#30803]
It could be very usefull to be able to search items by a tag they have not. 
Exemple 
I assign a tag named "printed" on some pictures. 
I want to find and see all my non-printed pictures  
Thanks

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/12530 (Feature Request), https://github.com/owncloud/core/issues/8569 (Feature requests), https://github.com/owncloud/core/issues/2012 (Feature request: Status indicator for cron-system), https://github.com/owncloud/core/issues/1749 (Feature request: security reports), and https://github.com/owncloud/core/issues/26723 (feature requests - Supervisor Role).
