### ISSUE TITLE
Switch to local view from public link

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30802]
### Steps

1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create a folder "share/1/2/3/4/work"
1. Share "share" with "user2"
1. Share "work" with public link and send it by email to many people including "user2" (for example it could be some project to work on)
1. Login as "user2"
1. Open the public link and see the folder
1. As a member of the project, realize that this is a folder you've already seen before and is somewhere in your workspace already, but you don't remember where
1. ???
1. Open the folder locally

### Expected
To facilitate reaching the local folder, a mechanism should exist to allow a logged in user to switch to the local folder from the public view. Could be a new button "Switch to local view"

### Actual
To achieve this, I either need to find one of the folder contents and use the search feature to hopefully find it.
Or if I feel like a hacker, open the DOM inspector and find the "data-id" of the first element in the public link folder, then plug it into a manually crafted private link: "/f/$fileId" and open it.
Opening the private link will bring you to the same folder but in the regular "All files" view.

### Version
ownCloud 10.0.7

Another approach would be to merge the concept of public and private link.

@pmaier1

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/25795 (Cannot view videos online inside shared links), https://github.com/owncloud/core/issues/8218 (Direct link in public sharing view is broken), https://github.com/owncloud/core/issues/5689 (Moving folder changes public share link), https://github.com/owncloud/core/issues/5565 (Implement easier public link sharing feature), and https://github.com/owncloud/core/issues/27593 (Change name of 'local/permanent link' to 'private link').
