### ISSUE TITLE
HTTP500 when syncing lots of files

### ISSUE THREAD

**Issue by fcmildef** [owncloud/core#30838]
### Steps to reproduce
1. connect a new desktop client to user with lots of files
2. after a while random get requests start giving 500 errors

### Expected behaviour
Properly syncing

### Actual behaviour
Not all files sync, client complains about 500 errors, synchronization stops.

### Server configuration
**Operating system**:
Ubuntu 16.04.4 LTS 
Linux owncloud 4.4.0-116-generic 

**Web server:**
apache2 2.4.18-2ubuntu3.5

**Database:**
mysql-server 5.7.21-0ubuntu0.16.04.1

**PHP version:**
php 7

**ownCloud version:** (see ownCloud admin page)
9.1.5.2

**The content of config/config.php:**
https://gist.github.com/fcmildef/6063d963b74fc69bee8cb03554bcc14b

### Client configuration
**Operating system:**
ubuntu 16.04

#### Web server error log
10.1.1.247 - alice [20/Mar/2018:10:11:37 +0100] "GET /remote.php/webdav/Documents/OUD%20archief/Directie%20en%20MT/Archief/2002%20en%20eerder/Oud_archief/Algemeen/Organisatiebrede%20zaken/verslagen%20OPSenWD/OPS2002/020226prioriteittweedehelft02.doc HTTP/1.1" 500 1207 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"

#### ownCloud log (data/owncloud.log)
{"reqId":"iiz9ZeZJ51V\/9nXVo8+W","remoteAddr":"10.1.1.247","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\\\"files\\\\\\\/8aa201695f8f1e4e5361fe682a76af5e\\\", 1, 1521540697, \\\"files\\\\\\\/8aa201695f8f1e4e5361fe682a76af5e\\\"]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\\\/8aa201695f8f1e4e5361fe682a76af5e' for key 'lock_key_index'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\UniqueConstraintViolationException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(209): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#3 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Adapter.php(113): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `oc...', Array)\\n#4 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(247): OC\\\\DB\\\\Adapter->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\\n#5 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(117): OC\\\\DB\\\\Connection->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\\n#6 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/Lock\\\/DBLockingProvider.php(162): OC\\\\Lock\\\\DBLockingProvider->initLockField('files\\\/8aa201695...', 1)\\n#7 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(668): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/8aa201695...', 1)\\n#8 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(584): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/Documents...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#9 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(584): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/Documents...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#10 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(584): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/Documents...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#11 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1921): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/Documents...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#12 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(2028): OC\\\\Files\\\\View->lockPath('\\\/Documents\\\/OUD ...', 1)\\n#13 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1109): OC\\\\Files\\\\View->lockFile('\\\/Documents\\\/OUD ...', 1)\\n#14 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(966): OC\\\\Files\\\\View->basicOperation('fopen', '\\\/Documents\\\/OUD ...', Array, 'rb')\\n#15 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(304): OC\\\\Files\\\\View->fopen('Documents\\\/OUD a...', 'rb')\\n#16 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#17 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#18 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#19 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#20 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#21 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#22 \\\/var\\\/www\\\/vhosts\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/vhosts...')\\n#23 {main}\",\"File\":\"\\\/var\\\/www\\\/vhosts\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":66,\"User\":\"37c457b8-148a-1032-823f-f98fb755d299\"}","level":4,"time":"2018-03-20T09:11:38+00:00","method":"GET","url":"\/remote.php\/webdav\/Documents\/OUD%20archief\/Directie%20en%20MT\/Archief\/2002%20en%20eerder\/Oud_archief\/Algemeen\/Organisatiebrede%20zaken\/verslagen%20OPSenWD\/OPS2002\/020226prioriteittweedehelft02.doc","user":"37c457b8-148a-1032-823f-f98fb755d299"}

**Comment by DeepDiver1975** [comment]
please follow the docs and use redis for locking. The database locking mechanism is only advised for small installations/usage. THX

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/279 (Data Loss while File Sync), https://github.com/owncloud/core/issues/3187 (Sync problem with over-limit-size files), https://github.com/owncloud/core/issues/2744 (Desktop Client Sync Larger Files Fails), https://github.com/owncloud/core/issues/21734 (Problems with syncing a file), and https://github.com/owncloud/core/issues/5546 (Sync-client messing up file permissions).
