### ISSUE TITLE
German translation in public link sharing dialogue is incomplete

### ISSUE THREAD

**Issue by dercorn** [owncloud/core#30844]
In 10.0.7 the public link sharing dialogue shows English text for both German translations:

<img width="430" alt="screen shot 2018-03-20 at 17 18 58" src="https://user-images.githubusercontent.com/1788382/37672701-cfebb5d2-2c6e-11e8-8a81-5f76daf5a9da.png">

The translations should be completed before 5 months, but Transifex shows warning signs next to some translations: https://www.transifex.com/owncloud-org/owncloud/viewstrings/#de_DE/core/125978737

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/962 (Mistake in german translation), https://github.com/owncloud/core/issues/2954 (Wrong german translation), https://github.com/owncloud/core/issues/1319 (German translation of 'Clients' is wrong ....), https://github.com/owncloud/core/issues/25412 (Wrong German translation: "authentifizieren"), and https://github.com/owncloud/core/issues/19070 (8.1.3 german translation incomplete).

**Comment by PVince81** [comment]
we'll likely need to backport all master translations to stable10 before 10.0.8 as translations are only done on master

**Comment by dercorn** [comment]
@PVince81 what about the warning sign on Transifex next to some of the wrong translations?

**Comment by DeepDiver1975** [comment]
> what about the warning sign on Transifex next to some of the wrong translations?

![screenshot from 2018-03-23 12-01-03](https://user-images.githubusercontent.com/1005065/37825952-ef416448-2e91-11e8-8382-937172f4f0e1.png)

**Comment by DeepDiver1975** [comment]
to be iignored

**Comment by DeepDiver1975** [comment]
as of today we have no real working way to backport translations.

this is by backport of features is critical .... told you so ....

**Comment by DeepDiver1975** [comment]
Yes. 10.0.8 should hold all translations

**Comment by patrickjahns** [comment]
@dercorn - 10.0.8 is solved - please verify and close

**Comment by DeepDiver1975** [comment]
I'm closing this now - please reopen if not fixed
