### ISSUE TITLE
A log is shown when we create a regular user

### ISSUE THREAD

**Issue by davitol** [owncloud/core#30853]
### Steps to reproduce
1. As admin User go to Users Page
2. Create a user
3. Check owncloud.log file

### Expected behaviour

No logs should be shown

### Actual behaviour

A log is shown in owncloud.log when creating a user

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1.15

**ownCloud version:""10.1.0 prealpha" using owncloud-daily-master.tar.bz2 from 20 March 2018

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
{"reqId":"HuAr8DBNhaIvOEfiHlGA","level":3,"time":"2018-03-21T08:02:10+00:00","remoteAddr":"85.57.168.79","user":"admin","app":"no app in context","method":"POST","url":"\/index.php\/settings\/users\/users","message":"User backend OC\\User\\Database is returning home: \/opt\/owncloud\/data\/pepe for user: pepe which differs from existing value: "}
```

Content of the account table:

```
select * from accounts;
+----+-------+---------+---------------+--------------+-------+------------+------------------+--------------------------+-------+
| id | email | user_id | lower_user_id | display_name | quota | last_login | backend          | home                     | state |
+----+-------+---------+---------------+--------------+-------+------------+------------------+--------------------------+-------+
|  1 | NULL  | admin   | admin         | admin        | NULL  | 1521619576 | OC\User\Database | /opt/owncloud/data/admin |     1 |
|  2 | NULL  | pepe    | pepe          | pepe         | NULL  | 1521619458 | OC\User\Database | /opt/owncloud/data/pepe  |     1 |
+----+-------+---------+---------------+--------------+-------+------------+------------------+--------------------------+-------+
```
### Client configuration

**browser**

Firefox

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/24082 (No "Personal" calendar created for installing user), https://github.com/owncloud/core/issues/6966 (Get logged in status for any user), https://github.com/owncloud/core/issues/5161 ([admin] Show warning when creating user which home dir already exists), https://github.com/owncloud/core/issues/23317 (Calendars from other Users show private appointments), and https://github.com/owncloud/core/issues/12251 (Can´t see when the users logged in anymore).

**Comment by dhniels** [comment]
I get a similar log with an existing user (username replaced for privacy reasons). I believe it started appearing when i upgraded to owncloud 10.1:

```
{"reqId":"ajTlFsTMYoVI40bS746e","level":3,"time":"2019-03-05T22:33:40+00:00","remoteAddr":"216.241.207.66","user":"jsmith","app":"no app in context","method":"PROPFIND","url":"\/remote.php\/dav\/files\/jsmith\/","message":"User backend OC\\User\\Database is returning home: \/data\/\/jsmith for user: jsmith which differs from existing value: \/data\/jsmith"}
```
