### ISSUE TITLE
Use of baseURL in acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#30879]
The API acceptance tests are passed the base URL of the server-under-test in a format like:
```
http://localhost:8080/ocs/
http://localhost:8080/cloudfolder/ocs/
```
when they want to access some API endpoint that does not start with ``ocs/`` then they take the ``ocs/`` off and then add the required string for the URL.

The webUI acceptance tests are passed the base URL of the server-under-test in a format like:
```
http://localhost:8080/
http://localhost:8080/cloudfolder/
```
and they add the ``ocs/`` or other endpoint URL as needed to access API endpoints.

Also it is not currently consistent if the passed-in base URL always has a ``/`` at the end or not.

This all makes a bit of a muddle for different methods that are in "API acceptance" classes and "webUI acceptance" classes.

To discuss/decide:

- [ ] common standard format for storing ``baseURL``
- [ ] whether to require a ``\`` at the end, or not, or be flexible parsing the passed-in value

@individual-it @SergioBertolinSG @davitol

**Comment by phil-davis** [comment]
My suggestions:

- pass in and store just the "really base" part like ``http://localhost:8080`` or ``http://localhost:8080/cloudfolder``
- cope with the passed-in ``baseURL`` parameter having a ``/`` at the end (easy to be flexible when parsing the passed-in value)
- store the ``baseURL`` only in 1 place in an API acceptance test context class (e.g. ``FeatureContext``). The webUI acceptance test context classes can get it from there if they need it.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/pull/30863 (Cleanup double-slash URLs in acceptance tests), https://github.com/owncloud/core/pull/30493 (Rename integration API tests to acceptance), and https://github.com/owncloud/core/pull/30833 (Refactor acceptance tests to use common user-group-server).

**Comment by SergioBertolinSG** [comment]
@phil-davis I fully agree with changing this. But be aware that it involves changes in many functions, as many of them to create the request url starts using baseUrl, for example:

```
$fullUrl = $this->baseUrl . "v2.php/cloud/users/$user/groups";
```

It will affect also acceptance tests of apps also (customgroups, guests, etc).

**Comment by phil-davis** [comment]
Yes, it will need careful examination of everything that uses, passes... ``baseURL`` !

**Comment by phil-davis** [comment]
PRs merged. webUI acceptance tests now use the "API test" view of ``baseUrl`` to know where to browse etc.
