### ISSUE TITLE
Hiding version in status.php prevents setting up trust relationship 

### ISSUE THREAD

**Issue by butonic** [owncloud/core#30888]
https://github.com/owncloud/core/blob/master/apps/federation/lib/TrustedServers.php#L218-L232

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/14407 (php version ), https://github.com/owncloud/core/issues/8342 (status.php response is empty), https://github.com/owncloud/core/issues/23957 (Hide security and settings warning), https://github.com/owncloud/core/issues/15924 (PHP Notice versions), and https://github.com/owncloud/core/issues/1349 (PHP version not supported by host).
