### ISSUE TITLE
[theme-example] Enable only for specific groups ???

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#30887]
<img width="1262" alt="settings_-_custom_cloud" src="https://user-images.githubusercontent.com/214010/37834412-ed5a1014-2ead-11e8-83fc-995820c3312f.png">

@VicDeo Why do we have the checkbox `[ ] Enable only for specific groups` for themes? I don't remember this in previous versions? Is this useful for themes? Can I have different theme for different groups? What theme is shown on the login page or in public share link? (when no user is logged in)

Or is this a bug? /cc @ChrisEdS 

oC 10.0.7

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/3209 (Theming), https://github.com/owncloud/core/issues/20304 (Allow public routes for group specific enabled apps), https://github.com/owncloud/core/issues/1111 (Enable apps only for specific users/groups), https://github.com/owncloud/core/issues/27995 (Conflict between app type filesystem and app setting Enable only for specific groups), and https://github.com/owncloud/core/issues/3267 (Which groups am I in?).

**Comment by VicDeo** [comment]
@michaelstingl 
> Why do we have the checkbox [ ] Enable only for specific groups for themes 

Because app type `theme` is not listed as 'protected' here https://github.com/owncloud/core/blob/master/lib/private/App/AppManager.php#L49-L59

> I don't remember this in previous versions

But it doesn't mean that it was not possible with previous versions :smile_cat: 

> Can I have different theme for different groups?

Nope. Enabling two different themes at once was blocked since 10.0.6 or 10.0.6

**Comment by michaelstingl** [comment]
@VicDeo Thanks for your explanation!

@PVince81 @pmaier1 I'd vote for adding `theme` type to the list?

**Comment by DeepDiver1975** [comment]
> @PVince81 @pmaier1 I'd vote for adding theme type to the list?

:+1:

**Comment by pmaier1** [comment]
:+1:

**Comment by VicDeo** [comment]
`[ ] Enable only for specific groups` will disappear for themes  since 10.0.8
