### ISSUE TITLE
Themes getHTMLName not used for layout.*.php

### ISSUE THREAD

**Issue by butonic** [owncloud/core#30881]
Admins want to add a link to the name that is shown next to the logo. Currently the themes getName is used (also for the basic auth realm) but we actually already have a getHTMLName that should be used in the layout.guest.php and layout.user.php files.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/3209 (Theming), https://github.com/owncloud/core/issues/6263 (layout.user.php code is not valid markup), https://github.com/owncloud/core/issues/23762 (remote.php/dav is not working when using cURL), https://github.com/owncloud/core/issues/19794 (Themed logo-wide.svg not used), and https://github.com/owncloud/core/issues/16845 (Use a custom layout ?).
