### ISSUE TITLE
interface & interaction guidelines / design guidelines

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#309]
Now that we have more apps and a better vision of what they need to look like, we should establish some interface & interaction design guidelines. General ones like those in the [Contribution Guidelines](http://owncloud.org/dev/contribute/) but also more specific ones. First thoughts:

#app-navigation (ex-leftcontent) is used for lists of contacts, feeds, categories, folders etc. (the general style for that needs to be moved out of the News app into core)

#app-content (ex-rightcontent) is used for the proper content like mails, articles, contact details, etc. (the general style for that also needs to be moved out of the News app into core)

The top action bar will be deprecated, except for Files and Pictures at the moment, because they use the breadcrumbs.

I’m still not sure about the bar at the bottom, because it seems like the add actions of the News app for instance might be better as first item in the list. Only a thought.

In general, we have to steadily review apps and decide on a case-by-case basis deciding what’s best for the app rather than strictly following guidelines.

(Related a bit to the #308 CSS coding guidelines.)

cc @Raydiation

**Comment by oparoz** [comment]
Comment from #19186 

There are lots of design changes happening in 8.2, but developers are left in the dark.

We need:
* Walk-through of the [design language](https://en.wikipedia.org/wiki/Design_language)
* Full design specifications
* Mock ups of **all** UI elements
* Links between each element and the CSS or JS class developers can use

I realise this is a lot of work, but the changes did not come out of thin air. There must be a solid basis for such drastic changes and it would be good if it could be shared with all. I'm sure designers interested in the project could help put the finishing touch.

This is to help apps be in line with core and get answers to some questions:
* Why is the font so thin?
* Why so little contrast?
* Which background colour to pick for this or that element?
* When is a shadow applied and when is it not allowed?
* How much transparency? Where?
* Where should we add borders?
* Which icon do I use?
* Which style for disabled checkboxes? https://github.com/owncloud/core/issues/19191

**Comment by jancborchardt** [comment]
Btw the start of this is at https://doc.owncloud.org/server/8.2/developer_manual/app/css.html – pull requests to the documentation are always welcome.

@oparoz as I said in the other issue: Great specific questions, and I’ll address them when I’m done with 8.2 bugfixing and back from vacation. @owncloud/designers @MorrisJobke @Henni can also chime in of course so it’s not me as bottleneck.

**Comment by oparoz** [comment]
Cool :+1: Enjoy the time off!

**Comment by cmonteroluque** [comment]
@jancborchardt ping? :)

**Comment by DeepDiver1975** [comment]
one day somebody will write some ......
