### ISSUE TITLE
Disable scanner commands and background jobs for unscannable storages

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30909]
In the case of non-scannable storages like primary object store, we need to disable automatically:
- background jobs related to background scanning
- occ commands

Maybe the jobs/commands in question can still be listed but should not do anything when run.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/20435 (Customize scanner for root storage to disable scanning.), https://github.com/owncloud/core/issues/23277 (disable external storages), https://github.com/owncloud/core/issues/22887 (non-ending background job), https://github.com/owncloud/core/issues/26760 (InfoParser not properly parsing single background-job, single command, etc), and https://github.com/owncloud/core/issues/16826 (Debounce expiration background jobs).
