### ISSUE TITLE
Android logo is missing in 1st time wizard and Logos are shifted in settings menu in oC stable10

### ISSUE THREAD

**Issue by davitol** [owncloud/core#30914]
**First Run Wizard**

![screen shot 2018-03-26 at 13 17 45](https://user-images.githubusercontent.com/10596560/37903615-d3725182-30f8-11e8-9278-f9d8d08ed816.png)

**Admin settings menu**

![screen shot 2018-03-26 at 13 23 43](https://user-images.githubusercontent.com/10596560/37903655-fb16ab0c-30f8-11e8-9263-c9f3a8a404af.png)

ownCloud 10.0.8 alpha (daily) Build:2018-03-26T03:32:08+00:00 2f55fb1707f2e575e33c5c7deeac619c4374cf16

**Comment by davitol** [comment]
@felixheidecke maybe?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/29617 ([stable10] Minimize wasted time setting up users), https://github.com/owncloud/core/pull/29741 ([stable10] Add missing CorsController in settings's Application), https://github.com/owncloud/core/issues/15807 (changing the LDAP host in the wizard to a missing one takes a long time before the wizard set it as invalid configuration), https://github.com/owncloud/core/issues/18657 (First run wizard does not load the first time we log in OC), and https://github.com/owncloud/core/issues/19238 (Checkboxes missing in LDAP wizard).

**Comment by davitol** [comment]
PR is not merged yet https://github.com/owncloud/core/pull/30988

**Comment by felixheidecke** [comment]
It is now :-*
