### ISSUE TITLE
Option to limit sharing to only folders and not files

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30910]
Add config option for admins to allow only sharing of folders, not files, for local and federated sharing.

The exception is for link shares in which case we could still allow file sharing.

@pmaier1 @labkode

**Comment by PVince81** [comment]
the option would need to be exposed as capability to allow clients to also disable the matching UI elements

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/11433 ([Sharing] Not possible to share after having shared a folder), https://github.com/owncloud/core/issues/8348 (Can't upload files to Shared folder), https://github.com/owncloud/core/issues/8349 (Can't upload files to Shared folder), https://github.com/owncloud/core/issues/16191 (It is not possible to share a file/folder just after renaming it from the WEB), and https://github.com/owncloud/core/issues/14647 (Lost share-keys for some (but not all) files).
