### ISSUE TITLE
Support for multiple roles in info.xml

### ISSUE THREAD

**Issue by sharidas** [owncloud/core#30922]
It would be nice if core supports multiple roles in info.xml. Currently only one role can be specified. An example would be user_management app when enabled in core master would not help group admins to view or navigate through users page.

 
### Steps to reproduce
1. Enable user_management app in core ( master branch of core )
2. Create group admin(s)
3. Login as group admin
4. Try to navigate or view the users page

### Expected behaviour
Only group admins and admins should be able to navigate to users page

### Actual behaviour
Any user would be able to navigate or view users page. This is after considering https://github.com/owncloud/user_management/blob/master/appinfo/info.xml#L15. Previously we had role="admin". This would not make group admins to view/navigate the users page.

### Server configuration
**Operating system**: Linux mint 18.3

**Web server:**
Apache

**Database:**
Sqlite3

**PHP version:**
7.2

**ownCloud version:** (see ownCloud admin page)
git master branch

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
git

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/2239 (Broken XML in appinfo/info.xml), https://github.com/owncloud/core/issues/5856 (Info.xml enhancement), https://github.com/owncloud/core/pull/30188 (only parse info.xml once), https://github.com/owncloud/core/issues/28265 (Hi,), and https://github.com/owncloud/core/issues/29158 (Dear Support, ).
