### ISSUE TITLE
Clicking link for row doesn't open folder or file 10.0.7.2

### ISSUE THREAD

**Issue by broco2002** [owncloud/core#30935]
### Owncloud Version
10.0.7.2

### Steps to reproduce
1. Click the row of a folder or file (not the name or the share or "..." options)

### Expected behaviour
The folder/file should open.

### Actual behaviour
The share options open.

### Client configuration
**Browser:** Mozilla Firefox, Microsoft Edge

**Operating system:**
Ubuntu 16.04 and Windows 7/10

### Additional Info:

- In older versions folders and files would always open if you clicked anywhere on the row  (the a class="name" link) except if you clicked on specific options
- clicking the a class="name" tag should do this except when you click the specific links for the options (inside span class="fileactions")

**Comment by SergioBertolinSG** [comment]
This is not a bug, the behaviour was changed in 8.0 if I recall correctly, on purpose.

**Comment by broco2002** [comment]
Yes, but why? It's completely impractical and unintuitive. Can I reverse it?

**Comment by SergioBertolinSG** [comment]
cc @pmaier1, you can check oc 7.0 behaviour if you want to comment about this.

**Comment by broco2002** [comment]
Sry I'm kinda new to the github forum, how do I cc him?

But I guess I'll just edit the css and turn off code checking.
Still, that is really unintuitive.
I'll check tomorrow or later. Shall I upload it somewhere if someone else wants to edit this function?

**Comment by SergioBertolinSG** [comment]
> Sry I'm kinda new to the github forum, how do I cc him?

Haha, no need to do anything I just used that email notation to ping him.

**Comment by broco2002** [comment]
Oh, thank you then and sorry :)
I'll take a look at the CSS and see if I can fix it myself tomorrow, will post solution here.

Oh and btw, you're right, we had 7.x before I recenty upgraded to 10.0.7.2, the old behaviour was just like I expected it to be now and my coworkers were pretty mad about the change.
