### ISSUE TITLE
Delete thumbnails after file cache entry removal by scanner

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30944]
When dealing with external storages, there's the topic about remote update detection which is adressed partly by the scanner checking for new oc_filecache entries and discarding old ones.

Currently, when a file is deleted on an external storage outside of ownCloud, the scanner will later on find out about this deletion and delete the oc_filecache entry directly. In this situation, any thumbnail that was associated with this fileid still stays on-disk.

We should make sure that any associated file gets deleted automatically.

For previews, the preview system should listen to the scanner hook about deletion and then delete the matching thumbnails.

Optional addition: occ command to clear thumbnails.

Failing to do so can result in many gigabytes of orphaned thumbnails that need manual deletion.

Related:
- triggering hooks for remote changes: https://github.com/owncloud/core/issues/26656
- centralized thumbnails proposal: https://github.com/owncloud/core/issues/28939

@DeepDiver1975 @pmaier1 @jvillafanez @butonic

**Comment by PVince81** [comment]
cc @mmattel

**Comment by PVince81** [comment]
additionally, once this is implemented we'll need a migration to clear the old orphaned thumbnails from before the system was in place (or just clear all)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/27274 (delete), https://github.com/owncloud/core/issues/5802 (Thumbnails should be deleted after file deletion), https://github.com/owncloud/core/issues/205 (Files: thumbnails), https://github.com/owncloud/core/issues/14671 (Thumbnail cache gets deleted after upload from smartphone), and https://github.com/owncloud/core/issues/13824 (Delete File).
