### ISSUE TITLE
[Feature Request] Group Sorting

### ISSUE THREAD

**Issue by TJHeeringa** [owncloud/core#30946]
### Steps to reproduce
1. Signin as Admin
2. Press dropdown menu
3. Open Users
4. Observe the order of Groups 

### Expected behaviour
Groups are shown in alphabetical order.

### Actual behaviour
~~Groups are shown order of creation.~~
Groups are shown in reverse-size order(sorted descending on number of members).

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Nginx
**Database:**
MySql
**PHP version:**
7.1.2
**ownCloud version:** (see ownCloud admin page)
10.7
**Updated from an older ownCloud or fresh install:**
Updated
**Where did you install ownCloud from:**
ownCloud repo
**Signing status (ownCloud 9.0 and above):**
Admin

### Client configuration
**Browser:**
Firefox Quantum
**Operating system:**
Windows 10

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/26890 (feature request: gpg key support), https://github.com/owncloud/core/issues/12530 (Feature Request), https://github.com/owncloud/core/issues/8569 (Feature requests), https://github.com/owncloud/core/issues/2572 (Feature: Meta-Group "all"), and https://github.com/owncloud/core/issues/6551 (Feature request: Support GPG/PGP (for E-Mail)).

**Comment by TJHeeringa** [comment]
None of the above mention the issues truly. They are related, since they concern user sorting and one of them links to an issue that deals with sorting groups on the number of people. 

This issue is concerned with that list of groups is not shown properly. See included screenshot.
![capture](https://user-images.githubusercontent.com/16029718/38020537-ccf96bb4-327a-11e8-80c5-a0726b8a1aca.PNG)

**Comment by phil-davis** [comment]
From what I can see, the ordering is working like:
1) When the page first draws up:
- Everyone
- Admins
- groups with members, most to least members (then alphabetical starting with uppercase, alphabetical starting with lowercase)
- empty groups (alphabetical starting with uppercase, alphabetical starting with lowercase)

2) When you create a new group on-the-fly then the list gets sorted:
- Everyone
- Admins
- groups with members, most to least members  (alphabetical not case-sensitive)
- empty groups (alphabetical not case-sensitive)

The Groups dropdown for a user lists the groups like in (2) (with groups the user is a member of at the top)

So your example has groups in reverse order of size.

The difference between (1) and (2) - case-sensitivity of ordering - is a UI inconsistency that could be fixed.

**Comment by phil-davis** [comment]
I guess this FR is thus asking for an option to sort groups alphabetically rather than in reverse size order.

**Comment by TJHeeringa** [comment]
@phil-davis That is exactly the request.

**Comment by phil-davis** [comment]
Note: in ``master`` the Users Page was recently moved to the https://github.com/owncloud/user_management repo. So if this FR happens, it needs to be done there, and if applied to the 10.0.* release series, then also done in ``core`` ``stable10``

**Comment by TJHeeringa** [comment]
@phil-davis Should I thus open the ticket at that repository?

**Comment by phil-davis** [comment]
Yes please.

@DeepDiver1975 I suppose tickets should go in the newer app repos, as we split stuff out of core. And then after implementing some FR in the new repo, a decision can be made about if it is backported - and the backport might end up having to be done into ``core``

**Comment by phil-davis** [comment]
See issue now raied in user_management repo:
https://github.com/owncloud/user_management/issues/14
