### ISSUE TITLE
occ command to adjust filecache checksum

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30951]
In some special cases (not reproducible) it can happen that the checksum in oc_filecache doesn't match the data on disk. This causes the desktop client to refuse working with said file.

If an admin can confirm that the data on disk is correct, they need a way to reset the checksums.

For this we should provide an occ command that scans through all files and detects wrong checksums. This could likely take a very long time as it needs to open all files to recompute the checksums ! I suggest to add a `--path` parameter so an admin can provide a more focussed scan (see `--path` argument like for occ files:scan) when they know in what folder most broken checksums are located.

Another alternative would be to only delete the wrong checksums and let the server recompute during the next download.

@IljaN @jnweiger @felixboehm

**Comment by PVince81** [comment]
Note: when user-key encryption is enabled the command can only work if a recovery key is specified. Else there is no way for the occ command to decrypt the files to compute the checksums to verify them. (see how decrypt-all).

For the version iteration I suggest ignoring user-key encryption.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/24494 (occ command to clear all locks), https://github.com/owncloud/core/pull/30177 (Kill occ command maintenance:createjs), https://github.com/owncloud/core/issues/25970 (occ command to migrate data folder), https://github.com/owncloud/core/issues/28940 (add occ command to flush distributed cache), and https://github.com/owncloud/core/issues/23380 (Occ command not working).

**Comment by IljaN** [comment]
- [ ] Should also work with ObjectStore

**Comment by IljaN** [comment]
Could not test with objectstore because of: https://github.com/owncloud/objectstore/issues/88

**Comment by PVince81** [comment]
where is the PR ? please link

**Comment by PVince81** [comment]
found it, PR here: https://github.com/owncloud/core/pull/31008

**Comment by IljaN** [comment]
Forward Port: https://github.com/owncloud/core/pull/31082
