### ISSUE TITLE
CSR not work with Safari mac/ios

### ISSUE THREAD

**Issue by willouuu** [owncloud/core#30969]
### Steps to reproduce
1. Navigate to browser Safari ( Mac or Iphone )

### Expected behaviour
Display page

### Actual behaviour
Safari can't open a page ( Connection broken by server )
In inspector : Unrecognized Content-Security-Policy directive 'manifest-src'.

### Server configuration
**Operating system**:
Centos

**Web server:**
Nginx

**Database:**
Mariadb

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
10.0.3 on production, 10.0.7 on test

**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**The content of config/config.php:**

```
    "config": {
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "allow_user_to_change_display_name": false,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "default_language": "fr",
        "enable_avatars": true,
        "forcessl": true,
        "instanceid": "oc5766a60c0c",
        "installed": true,
        "knowledgebaseenabled": true,
        "knowledgebaseurl": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/owncloud\/owncloud.log",
        "loglevel": 0,
        "log_authfailip": true,
        "logtimezone": "Europe\/Paris",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "skeletondirectory": "***REMOVED SENSITIVE VALUE***",
        "singleuser": false,
        "trashbin_retention_obligation": "30, auto",
        "updatechecker": false,
        "version": "10.0.7.2",
        "versions_retention_obligation": "auto"
    },

```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.6
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - market: 0.2.3
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.2
  - updatenotification: 0.2.1
  - user_ldap: 0.10.0

```

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** iOs/Safari

**Operating system:**
All versions

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
nothing 
```

#### Browser log
```
a) The javascript console log
Unrecognized Content-Security-Policy directive 'manifest-src'

```

Hi 

Impossible to open a page with Safari, even by disabled CRSF in config.php

No test to delete "manifest-src" in https://github.com/owncloud/core/blob/v10.0.7/lib/public/AppFramework/Http/EmptyContentSecurityPolicy.php 

Thanks you in advance

**Comment by willouuu** [comment]
No same issues

**Comment by 128432b4117** [comment]
You could first verify if this is not just a deployment issue. I guess if you disable the CSP in the config.php then the message about 'manifest-src' is not relevant.

**Comment by PVince81** [comment]
It is likely a deployment issue as we often test with Safari and OC works fine with it.

**Comment by willouuu** [comment]
Hi, 
Yes when disable http2, it work
The problem is'nt Owncloud but Ningx 1.12.2, I will test to upgrade in Nginx 1.13
I'm sorry

**Comment by willouuu** [comment]
Yes, if I find a solution, I would write it here
