### ISSUE TITLE
Improve page auto-reload in case of errors

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#30966]
Whenever an error of certain type occurs within a XHR call (cross-domain error 0 or auth error), the current OC will display a notification that the page will be reloaded in 5 seconds, then it reloads.

I suggest adding another step in-between: whenever such error is detected, we do yet another XHR call to an authenticated endpoint that we know is supposed to work (ex: heartbeat) and if that one also fails with an error, we reload the page.

This would help prevent reloading the page for some random/temporary issue or issues specific to some endpoints. In the latter case, we need to display proper messages for debugging.

@butonic @DeepDiver1975

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/28840 (-Error-), https://github.com/owncloud/core/issues/3420 (Token Expired. Please Reload Page), https://github.com/owncloud/core/issues/1663 (After login page is always reloading), and https://github.com/owncloud/core/issues/11095 (Token expired. Please reload page error when logging in from another website).
