### ISSUE TITLE
Remove duplicate Jenkins core testing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#30990]
Jenkins is still running some tests in parallel with what has been migrated to drone.
e.g. "normal" API acceptance tests

Look through what remains on Jenkins for both ``master`` and ``stable10`` in core. Remove stuff that is already on drone.

Do it around [the end of this week|after an RC for 10.0.8 has been made] (just so we have both versions of test results for a few more days)

**Comment by phil-davis** [comment]
Assigned to me so I do not forget.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/240 (--- Removed ---), https://github.com/owncloud/core/issues/3260 (- Removed -), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), and https://github.com/owncloud/core/issues/15094 (Jenkins timezone tests fail).
