### ISSUE TITLE
https://api.owncloud.com down?

### ISSUE THREAD

**Issue by andirapandi** [owncloud/core#30997]
### Steps to reproduce
1. I upgraded OC 8.21 to 9.0.11
2. Lost both calendar and contacts apps (they are still on old version that reports incompatibiltiy)
3. Tried to update the apps, but cannot see any online apps, update or install apps
4. Have "Could not get application: cURL error 7: Failed to connect to api.owncloud.com port 443: No route to host" in the logs, and guess it is related. Also, from other computers I cannot access https://api.owncloud.com

### Expected behaviour
Upgrade should have worked without a hassle..
but right now I think that I would have to be able to reach api.owncloud.com for accessing apps/marketplace.

### Actual behaviour
"Could not get application: cURL error 7: Failed to connect to api.owncloud.com port 443: No route to host" in the logs

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** mysql

**PHP version:** 7

**ownCloud version:** 9.0.11

**Updated from an older ownCloud or fresh install:** from 8.2.1

**Where did you install ownCloud from:** official docs

I assume the rest is not that relevant..

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/4250 (api owncloud), https://github.com/owncloud/core/issues/26921 (https://demo.owncloud.org DOWN), https://github.com/owncloud/core/issues/20651 (https://github.com/owncloud/core/issues/18755 is still an issue), https://github.com/owncloud/core/issues/18664 (Malware injected in https://apps.owncloud.com/kb), and https://github.com/owncloud/core/issues/12054 (Owncloud http requests).

**Comment by PVince81** [comment]
The old app store has been discontinued and replaced with the marketplace: https://owncloud.org/news/welcome-marketplace/

Please upgrade to 10.0.7 directly from 8.2.11. Since OC 10.0 you can skip major releases.

**Comment by PVince81** [comment]
you can also upgrade from 9.0.10 to 10.0.7.

Please note that all ownCloud versions prior to 10 are already EOL: https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

**Comment by andirapandi** [comment]
Thank you!
From the upgrade instructions at https://doc.owncloud.org/server/9.1/admin_manual/release_notes.html,
"After upgrading to ownCloud 9.0 and before continuing to upgrade to 9.1 make sure that all of your and your users Calendars and Addressbooks are migrated correctly. Especially when using the IMAP user backend (other user backends might be also affected) you need to manually run the mentioned occ migration commands described above."
How can I make sure the migration was successful if the apps are not working or updatable anymore? Can I manually overwrite the app folders with more current versions or is there some other way?

**Comment by PVince81** [comment]
@DeepDiver1975 do you know ? ^
