### ISSUE TITLE
Authentication NFC OwnCloud

### ISSUE THREAD

**Issue by ghost** [owncloud/core#31018]
Hello everyone,

Ive recently installed OwnCloud on my local NAS server. Its works correctly. Good!
Now I want to create an authentication with an NFC tag. For the moment I've just write an URL on my NFC tag like this:
"http://xx.xx.xx.xx/owncloud/index.php/login?user=admin&pass=1234"
But the storage of the variables on the URL via GET doesn't works. on my form Only the username field is filled with "admin". The field password is blank. Maybe it is possible to make an authentication with POST request and how? please? Or other solutions?

Thank you for your helps.

**Comment by salimbenfarhat** [comment]
For read/write on NFC I use the ACS ACR122U NFC Reader and the GoToTags Window App on Windows 10.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/28088 (Encryption for Owncloud 10), https://github.com/owncloud/core/issues/12153 (unable to set two-factor-authentication-for-owncloud-using-one-time-passwords-otp), https://github.com/owncloud/core/issues/24291 (Support absolute dates in ownCloud), https://github.com/owncloud/core/issues/6369 (OwnCloud 6 OpenLDAP authentication problem), and https://github.com/owncloud/core/issues/14552 (OwnCloud 8: Problem with LDAP Authentication ).

**Comment by PVince81** [comment]
It would be a security issue to allow passing the password in the URL (cross-site scripting)

There is probably a better approach for this but I'm not familiar enough with this topic.
This might need to develop a separate app which frontend is able to read from the NFC tag and then submit this as authentication to ownCloud.

**Comment by 128432b4117** [comment]
A cross-site scripting flaw probably would be the least of the security problems you need to worry.

When transmitting the password as a GET request it is saved/stored in various log files of e.g. the web server and even in possible proxies between the server and the client.

**Comment by PVince81** [comment]
won't fix, out of scope for core, needs to be a separate app
