### ISSUE TITLE
subadmin should be able to remove users from the group

### ISSUE THREAD

**Issue by davitol** [owncloud/core#31016]
### Steps to reproduce

You can configure it like the screenshots below this ticket

1 - As admin user create a subadmin for a group (ana) and another user that belongs to the group (luis)
2 - Log in as subadmin (ana) 
3- Try to uncheck group checkbox for luis

### Expected behaviour

The user can be removed from the group by the subadmin

### Actual behaviour

The user is NOT removed from the group by the subadmin

**Note**: We have this acceptance test for checking that:

https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiProvisioning/provisioning-v1.feature#L489-L499

So the provisioning api is allowing the remove, but the request is not being made in the webUI.
**API and UI should be consistent**

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1.15

**ownCloud version:**

ownCloud Stable10 from 5th April  2018 
**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
No logs in owncloud.log
```

![screen shot 2018-04-05 at 18 06 44](https://user-images.githubusercontent.com/10596560/38377795-2b5d5bde-38fc-11e8-8371-80eb1e2b783f.png)

**Comment by davitol** [comment]
It has been also reproduce in oC 9.1.8. so it is not a regression. It probably have failed since the beginning

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/issues/31280 which was fixed already
