### ISSUE TITLE
email address is not and cannot be set for external auth users (e.g. IMAP)

### ISSUE THREAD

**Issue by jeredfloyd** [owncloud/core#31042]
### Steps to reproduce
1. Configure with an external auth type, for example OC_User_IMAP
2. Note lack of email under Personal Settings.  Attempt to set Email.
3. Note success message but 'email' field of oc_accounts table is not set.

### Expected behaviour
1. User should be autocreated with appropriate email address.
2. "Change email" button should work correctly (or be disabled).

### Actual behaviour
1. Email is not set for autocreated users.
2. Email cannot be changed.

### Server configuration
**Operating system**: Debian 9.4

**Web server:** Apache 2.4.25

**Database:** MariaDB 10.1.26

**PHP version:** PHP 7.0.27

**ownCloud version:** (see ownCloud admin page) 10.0.7

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** OwnCloud official repo

**Signing status (ownCloud 9.0 and above):** Yes.

**The content of config/config.php:**
{
    "system": {
        "updatechecker": false,
        "instanceid": "oc52k4tfllz4",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "files.merrimackdesign.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/files.merrimackdesign.com",
        "dbtype": "mysql",
        "version": "10.0.7.2",
        "dbname": "ocdb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "trusted_proxies": [
            "172.16.0.6"
        ],
        "asset-pipeline.enabled": true,
        "loglevel": 1,
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{imap.convivian.com:993\/imap\/ssl}",
                    ""
                ]
            }
        ],
        "lost_password_link": "https:\/\/passwd.merrimackdesign.com\/",
        "appstore.experimental.enabled": true,
        "logtimezone": "America\/New_York",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "theme": ""
    }
}

**List of activated apps:**

Enabled:
  - activity: 2.3.6
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: 0.12.0
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.2.3
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.2
  - theme-merrimack: 1.0.0
  - updatenotification: 0.2.1
  - user_external: 0.4
Disabled:
  - encryption
  - external
  - theme-example

**Are you using external storage, if yes which one:** No.

**Are you using encryption:** yno

**Are you using an external user-backend, if yes which one:** IMAP

### Client configuration
**Browser:** n/a

**Operating system:** n/a

#### Web server error log
n/a

#### ownCloud log (data/owncloud.log)
n/a

#### Browser log
n/a

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/18335 (Email address can't be set or changed for external user ), https://github.com/owncloud/core/issues/27546 (Cannot set e-mail address), https://github.com/owncloud/core/issues/27667 (Users cannot set email address on personal settings), https://github.com/owncloud/core/issues/10005 (Setting email not possible for external users (when password change is not allowed)), and https://github.com/owncloud/core/issues/10592 (User cannot add a Email-Address when using IMAP-Authentication).

**Comment by jeredfloyd** [comment]
Wow, how cool! 

#18335 - sorta related, but the IMAP backend is part of Core now so it should be fixed. Also it appears to be a regression that attempting to set an email now returns success.
#27546 - Not related; that was a charset issue
#27667 - Not related; different bug
#10005 - This is the the same issue, and could be merged. (Note that the "success" error is separate.  I should have opened two bugs.)
#10592 - Duplicate as with #10005.

**Comment by PVince81** [comment]
Can you try if https://github.com/owncloud/core/pull/30319 helps a bit ? This will be released in 10.0.8.
