### ISSUE TITLE
Core offers no way for IApacheBackends to discover and sync users during request auth

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#31052]
We used to rely on `handleLogin` which tries apache auth first allowing sync. https://github.com/owncloud/core/blob/master/lib/base.php#L959

However, we now use $session->verifyAuthHeaders which does not check apacheAuth: https://github.com/owncloud/core/blob/master/lib/base.php#L892

Where should we use `OC\User\Session->verifyAuthHeaders()` and where should we use `OC::handleLogin`. 

Currently we rely on `IApacheBackends` to do their own user discovery and account creation in their app.php which we want to avoid because it is expensive and should not happen during app loading. We want an explicit code path that can be tested and better controlled by core.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @PVince81, and @butonic.

Possibly related issues are https://github.com/owncloud/core/issues/6017 (Offer one way sync), https://github.com/owncloud/core/pull/30638 (Core controlled user metadata sync), https://github.com/owncloud/core/pull/31029 (Discover new users in single user sync), https://github.com/owncloud/core/issues/1292 (Coordinate n-way sync with multiple clients/users), and https://github.com/owncloud/core/pull/31032 ([stable10] Discover new users in single user sync).

**Comment by PVince81** [comment]
@tomneedham close ?

**Comment by tomneedham** [comment]
Yep, solved with #31054
