### ISSUE TITLE
Comment restrictions

### ISSUE THREAD

**Issue by balduin-kowalski** [owncloud/core#31089]
At the moment every user can add comments if the Comments-App is active. Is there a way to limit the ability to add/answer comments only to specific users or groups?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22367 (Security Check: Comments), https://github.com/owncloud/core/issues/24445 (User mentioning in Comments), https://github.com/owncloud/core/issues/24638 (Ctrl-Enter to submit comment), https://github.com/owncloud/core/issues/25879 (Comments & Details pane interaction ), and https://github.com/owncloud/core/issues/20264 (File Comments DAV Resource).
