### ISSUE TITLE
An alert to upgrade an app uses the wrong instance domain (marketplace is ok)

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#31081]
### Steps to reproduce
1. Have more than one domain names pointing to the instance, trusted_domains is properly setup
2. An upgrade alert symbol shows up, click on it
3. The first domain name in trusted_domains is taken and you are redirected to it first than you can continue

### Expected behaviour
Stay in the domain you are logged on

### Actual behaviour
trusted_domains = domain1, domain2, domain3
You log on in domain2, click the alert symbol, click the app upgrade, you are now redirected to domain1 where you have to logon first, then click alert, click upgrade and then the screen of the marketplace with the app to upgrade opens.

The user logged on MUST NOT know about the other domains used to access the instance

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.7

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oct7bkicorxf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain1",
            "domain2",
            "domain3"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/domain1",
        "dbtype": "mysql",
        "version": "10.0.7.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "filesystem_check_changes": 1,
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "maintenance": false,
        "theme": "",
        "preview_max_scale_factor": 1,
        "excluded_directories": [
            ".snapshot",
            "~snapshot"
        ],
        "upgrade.automatic-app-update": true,
        "quota_include_external_storage": false,
        "singleuser": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ]
    }
}

```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.6
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_clipboard: 0.7.1
  - files_external: 0.7.1
  - files_external_dropbox: 1.0.1
  - files_external_ftp: 0.2.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - guests: 0.5.0
  - market: 0.2.3
  - music: 0.5.6
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.2
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - theme-example
  - user_external
```

**Are you using external storage, if yes which one:** smb/ftp/db

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** Opera

**Operating system:** W10x64

#### Web server error log
```
not relevant
```

#### ownCloud log (data/owncloud.log)
```
not relevant
```

#### Browser log
```
not relevant
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/17528 (Prevent closing upgrade page while upgrade in progress), https://github.com/owncloud/core/issues/11842 (Can not Upgrade my OwnCloud Instance), https://github.com/owncloud/core/issues/18861 (RouteNotFoundException during upgrade of an app), and https://github.com/owncloud/core/issues/30642 (Federated shares keep the status "Ausstehend", manually walking thru folders necessary).

**Comment by patrickjahns** [comment]
This however seems to be expected behavior as you have set `overwrite.cli.url` 
> Use this configuration parameter to specify the base URL for any URLs which are generated within ownCloud using any kind of command line tools (cron or occ). The value should contain the full base URL: https://www.example.com/owncloud

[see documentation](https://doc.owncloud.org/server/10.0/admin_manual/configuration/server/config_sample_php_parameters.html)

**Comment by mmattel** [comment]
Hmmm, I thought that this could be a cause, but ...

the behaviour to be redirected to another instance url when upgrading an app is strange to me.

Why not when changing an app like from files to gallery?
Or if I open the marketplace app ?

For me, therer is no diffrence between opening the marketplace app versus upgrading an app from marketplace. The first one stays in the url, the latter not ?

**Comment by DeepDiver1975** [comment]
URL which are generated from the web frontend are using the domain from the current request.
In this situation all requests stay in the same domain - easy game - easy live.

For any urls which are generated in the backend like any occ command of any background/cron job there is not current request and then overwrite.cli.url is used.

There is no real other way how to do this ....

**Comment by mmattel** [comment]
1. This is an important info and understandable !
2. This also implies that clicking on the alarmbell and further in the app to be upgraded, an occ command is triggered

ad1.) this is a documentation issue and needs to be added - will do.
ad2.) I do not believe that we run an occ command when clicking alarmbell/app-to-be-upgraded

**Comment by DeepDiver1975** [comment]
> This also implies that clicking on the alarmbell and further in the app to be upgraded, an occ command is triggered

there is no occ command involved when clicking the alert button.
But the notification is generated by a background job which has no understanding of the domain.

The only solution would be to generate the links without domain information and add a placeholder which can be replace when delivering the notification to the client.
But this would not work for desktop and mobile clients - they expect a full url including domain.

**Comment by mmattel** [comment]
thanks, gives more clearance, just improving config.sample.php. 
will add you as reviewer 😃

**Comment by PVince81** [comment]
somehow seems connected to the discussion in https://github.com/owncloud/market/issues/315

**Comment by mmattel** [comment]
Maybe a stupid question...
The notification is created by a background process, so ``overwrite.cli.url`` is used - ok.

For the browser:
The alarm bell is clicked by the user logged on, so it is identifyable from which domain the click is coming from.

From an external system like the client or the IOS/Android apps:
The origin url comes from the background process, but isn´t it identifyable which user and url the client logges in?

What I want to say is, there is a presentation thing and there is a click thing and both may have different URL. But the action comes from the click. Currently we do not have a occ command upgrading an app... And in the latter case (when such a command would be gernerated, it does not matter anyways).
