### ISSUE TITLE
checkPassword should update the session last_check_timeout

### ISSUE THREAD

**Issue by butonic** [owncloud/core#31080]
see https://github.com/owncloud/core/pull/31076#issuecomment-380207717

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/20661 (Update), https://github.com/owncloud/core/issues/21366 (Update), https://github.com/owncloud/core/issues/955 (csync update failed - Session error string 501), https://github.com/owncloud/core/issues/27313 (Auth - Session), and https://github.com/owncloud/core/pull/29344 (Update .htaccess).

**Comment by PVince81** [comment]
as I understand this is p4-low, moved to triage
