### ISSUE TITLE
[Feature Request] adding good icons for apps developed by ownCloud

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#31097]
Checked with release 10.0.7
There are a bunch of apps maintained by owncloud which have no or no meaningful app-icon (standard: gear). You can see this in settings/apps (example: Collaborative tags, Comments)
![image](https://user-images.githubusercontent.com/3321281/38665627-27e432de-3e3d-11e8-886a-5fd7e3e698da.png)

It would look much more professional adding a good icon for those apps.

The one I have identified without beeing complete:
- Admin Config Report
- Federation
- Provisioning API
- Update notification
- Collaborative tags
- Comments
- External Storage: Dropbox
- First run wizard
- FTP storage support
- Guests
- Mail Template Editor

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/12530 (Feature Request), https://github.com/owncloud/core/issues/8569 (Feature requests), https://github.com/owncloud/core/issues/20519 (OwnCloud Feature Request), https://github.com/owncloud/core/issues/14784 (Owncloud Calendar Feature Request), and https://github.com/owncloud/core/issues/17664 ("Feature" request: Owncloud-Server for Android).

**Comment by mmattel** [comment]
@PVince81 any comment on that?

**Comment by hurradieweltgehtunter** [comment]
Thanks @mmattel for bringing this to my attention. I just talked to our designer today to come up with a rough design guideline for app images (also marketplace). We should use a consistent design for apps wherever being used: App overview (as mentioned above), marketplace, market app, blog posts, press releases etc. 
Is there a way to use the images provided by the marketplace in the above mentioned app overview?
@PVince81 @DeepDiver1975

**Comment by DeepDiver1975** [comment]
> Is there a way to use the images provided by the marketplace in the above mentioned app overview?
> @PVince81 @DeepDiver1975

this is the app icon as supplied by each and every app. as example: https://github.com/owncloud/core/blob/master/apps/files_versions/img/app.svg for the icon of the versions app
