### ISSUE TITLE
10.0.8RC1 - FINAL smoke test results

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/core#31096]
# Smoke test

## Previous requirements

Prepare two servers with ssl activated and trusted certificates.

Enable LDAP and external storage apps.

Have a LDAP server ready to be used with owncloud.

Have ready two external storages of your choice SMB, SFTP, Dropbox, Google Drive, FTP, S3, ownCloud, local.

## Testing setup

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Enable encryption app and encryption default module | Encryption is enabled correctly | ✅ |
2 | Populate owncloud server with users and groups | Users and groups are correctly created | ✅ |
3 | Share a folder remotely using federated sharing with admin user of the other server. | folder can be opened in recipient server without problems | ✅ |
4 | Set up LDAP, as admin check users. log in with a LDAP user, if possible one with an avatar. | Users are loaded. LDAP user logs in without problems. Avatar is shown if it exists.  | ✅ |
5 | Set up two external storages different, disable encryption in one of them.| No errors in this process | ✅ |

## Testing functionality

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Share a file using federated sharing from an external unencrypted external storage in server #1 using a LDAP user to the admin user in server #2. | Admin user in server #2 can see the file. | ✅ |
2 | Open internet explorer or edge and upload a new avatar for a regular user not LDAP | Interface can be used, avatar is uploaded, check that personal page has a scroll bar and scrolls fine. | ✅ |
3 | Upload several files and folders inside external storages, open some. | No problems uploading, files can be downloaded and opened. | ✅ |
4 | Delete files inside both external storages. Recover some after from the trashbin. |  Files are correctly deleted and restored. | :construction: |
5 | Using webdav upload a 100MiB file.| No errors in this process | ✅ |

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/pull/29842 (skip known to fail tests on 10.0.3), https://github.com/owncloud/core/issues/30300 (Smoke Test results for 10.0.6), and https://github.com/owncloud/core/pull/29848 ([stable10] skip known to fail tests on 10.0.3).

**Comment by patrickjahns** [comment]
@phil-davis @individual-it 
Last nights automated smoke tests had errors: https://travis-ci.org/owncloud/core/builds/365222767?utm_source=email&utm_medium=notification

Please check and comment here if these issues persist - or are "false" positives

**Comment by jesmrec** [comment]
# Smoke test iOS  [WIP]

Device & iOS version: iPhone 6SPlus v11<br>
Server version: 10.0.8RC1 <br>
OAuth2 version: 0.2.2

### Login

Test Case | Expected Result | Result | Related Comment
| :------- | :---------------: | :------ | :-----------------: | 
Login with one account (HTTPS)  | It is possible to access | :white_check_mark: |
Login with one account (HTTP)  | It is possible to access  | :white_check_mark: |
Login with one account (SHIB Autoprovisioned user)|  It is possible to access|  |
Login with one account (SHIB SSO user )  | It is posible to access |:white_check_mark: |


### Folder

TestID | Test Case | Steps | Expected Result | Result | Related Comment
------------ | ------------- | ----------- | -------------- | ----- | ------
1 | Create a new folder  | 1. Tap on create a new folder |The folder is created| :white_check_mark: OAuth<br>:white_check_mark: basic<br> |
2 | Create a folder with special character | 1. Tap on create a new folder <br> 2. Use a name with special characters (e.g $%&¨)| The folder is created with special character  | :white_check_mark: OAuth<br>:white_check_mark: basic<br> |
3 | Rename a folder | 1. Create a new folder<br> 2. Rename the folder|  Folder is renamed| :white_check_mark: OAuth<br>:white_check_mark: basic<br>
4 | Move a folder | 1. Create a new folder <br> 2. Move the folder| Folder is moved to the specifield location | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
5 | Upload a file into a folder | 1. Create a new folder <br> 2. Upload a file| File is uploaded into the folder | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
6 | Delete a folder  | 1. Access to a folder, the folder has deep structure inside <br> 2. Download some files <br>3. Select delete that folder  | 2. The files are downloaded<br>3. The folder is removed| :white_check_mark: OAuth<br>:white_check_mark: basic<br>
7| Copy Folder | 1. Long press to copy a folder <br> 2. Select a location to paste | The folder and all its content is copied in the location, and remains too in the original| NA
8 | Share the folder by link | 1. Create a new folder <br>2. Long press to share the folder by link <br>  | The link is generated and works| :white_check_mark: OAuth<br>:white_check_mark: basic<br>
9 | Share the folder by link with pass| 1. Create a new folder <br>2. Long press to share the folder by link <br> 3. Enable the password protection and set a password | The link is generated and only works if the correct password is typed|:white_check_mark: OAuth<br>:white_check_mark: basic<br>
10| Unshare the folder by link | 1. Unshare the folder of previous test cases| The link is no more available |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
11 | Share the folder with users or groups| 1. Create a new folder <br> 2. Long press to share with users/groups <br> 3. Type one user/group to share with |  The user/group can access to the folder | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
12| Unshare the folder with users or groups| 1. Unshare the folder in the previous test case | The folder is not more available for the sharees | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
 

### File

TestID | Test Case | Steps | Expected Result | Result | Related Comment
------------ | ------------- | ------------- | -------------- | ----- | ------
1 | Upload a new file  | 1. Upload a new file | The file is uploaded | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
2 | Upload a file with special character | 1. Upload a new file (e.g f%&¨)| The file is uploaded | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
3 | Rename a file | 1. Create a new file <br> 2. Rename the file | The file is renamed |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
4 | Move a file | 1. Create a new file <br> 2. Move the file | The file is renamed |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
5 | Copy a file  | 1. Create a new file <br> 2. Copy the file | The file is copied to the selected location | NA
6 | Delete a file  | 1. Create a new file <br> 2. Delete the file | The file is deleted |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
7 | Share the file by link | 1. Create a file<br> 2. Long press to share the file by link | The link is generated and works|:white_check_mark: OAuth<br>:white_check_mark: basic<br>
8 | Share the file by link with pass| 1. Create a file<br> 2. Long press to share the file by link <br> 3. Set a password| The link is generated and works when the correct pass is typed|:white_check_mark: OAuth<br>:white_check_mark: basic<br>
9 | Unshare the file by link | 1. Unshare the file of previous test cases |  The link is no more available|:white_check_mark: OAuth<br>:white_check_mark: basic<br>
10 | Share the file with users or groups| 1. Create a new file <br> 2. Long press to share with users/groups <br> 3. Type one user/group to share with |  The user/group can access to the file | :white_check_mark: OAuth<br>:white_check_mark: OAuth<br>:white_check_mark: basic<br>
11| Unshare the file with users or groups| 1. Unshare the file in the previous test case | The file is not more available for the sharees | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
12| Download a file| 1. Tap to download a file | The file is downloaded and marked with green tick|:white_check_mark: OAuth<br>:white_check_mark: basic<br>
13| Av Offline file | 1. Long press to set as av offline a file | The file is downloaded and set as av off with the yellow arrow |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
14| Av Offline file | 1. Long press to set as no av offline a file | The file has no more the yellow arrow | :white_check_mark: OAuth<br>:white_check_mark: basic<br>

**Comment by jesmrec** [comment]
# Smoke test Android [WIP]

Device & Android version: Nexus 6 V6<br>
Server version: 10.0.8RC1
OAuth2 version: 0.2.2


### Login

Test Case | Expected Result | Result | Related Comment
| :------- | :---------------: | :------ | :-----------------: | 
Login with one account (HTTPS)  | It is possible to access | :white_check_mark: |
Login with one account (HTTP)  | It is possible to access  | :white_check_mark: |
Login with one account (SHIB Autoprovisioned user)|  It is possible to access|  |
Login with one account OAuth2 |  It is possible to access|  :white_check_mark:|



### Folder

TestID | Test Case | Steps | Expected Result | Result | Related Comment
------------ | ------------- | ----------- | -------------- | ----- | ------
1 | Create a new folder  | 1. Tap on create a new folder |The folder is created| :white_check_mark: basic<br>:white_check_mark: OAuth2  |
2 | Create a folder with special character | 1. Tap on create a new folder <br> 2. Use a name with special characters (e.g $%&¨)| The folder is created with special character  | :white_check_mark: basic<br>:white_check_mark: OAuth2 |
3 | Rename a folder | 1. Create a new folder<br> 2. Rename the folder|  Folder is renamed|:white_check_mark: basic<br>:white_check_mark: OAuth2
4 | Move a folder | 1. Create a new folder <br> 2. Move the folder| Folder is moved to the specifield location |:white_check_mark: basic<br>:white_check_mark: OAuth2
5 | Upload a file into a folder | 1. Create a new folder <br> 2. Upload a file| File is uploaded into the folder |:white_check_mark: basic<br>:white_check_mark: OAuth2
6 | Delete a folder  | 1. Access to a folder, the folder has deep structure inside <br> 2. Download some files <br>3. Select delete that folder  | 2. The files are downloaded<br>3. The folder is removed|:white_check_mark: basic<br>:white_check_mark: OAuth2
7| Copy Folder | 1. Long press to copy a folder <br> 2. Select a location to paste | The folder and all its content is copied in the location, and remains too in the original|:white_check_mark: basic<br>:white_check_mark: OAuth2
8 | Share the folder by link | 1. Create a new folder <br>2. Long press to share the folder by link <br>  | The link is generated and works|:white_check_mark: basic<br>:white_check_mark: OAuth2
9 | Share the folder by link with pass| 1. Create a new folder <br>2. Long press to share the folder by link <br> 3. Enable the password protection and set a password | The link is generated and only works if the correct password is typed|:white_check_mark: basic<br>:white_check_mark: OAuth2
10| Unshare the folder by link | 1. Unshare the folder of previous test cases| The link is no more available |:white_check_mark: basic<br>:white_check_mark: OAuth2
11 | Share the folder with users or groups| 1. Create a new folder <br> 2. Long press to share with users/groups <br> 3. Type one user/group to share with |  The user/group can access to the folder|:white_check_mark: basic<br>:white_check_mark: OAuth2
12| Unshare the folder with users or groups| 1. Unshare the folder in the previous test case | The folder is not more available for the sharees |:white_check_mark: basic<br>:white_check_mark: OAuth2
13| Sync a folder| 1. Create a folder <br> 2. In web app, upload some files in the folder <br> 3. Long press to sync the folder  | The folder is sync with the content on server|:white_check_mark: basic<br>:white_check_mark: OAuth2
 


### File

TestID | Test Case | Steps | Expected Result | Result | Related Comment
------------ | ------------- | ------------- | -------------- | ----- | ------
1 | Upload a new file  | 1. Upload a new file | The file is uploaded | :white_check_mark: basic<br>:white_check_mark: OAuth2
2 | Upload a file with special character | 1. Upload a new file (e.g f%&¨)| The file is uploaded |:white_check_mark: basic<br>:white_check_mark: basic<br>:white_check_mark: OAuth2
3 | Rename a file | 1. Create a new file <br> 2. Rename the file | The file is renamed |:white_check_mark: basic<br>:white_check_mark: OAuth2
4 | Move a file | 1. Create a new file <br> 2. Move the file | The file is renamed |:white_check_mark: basic<br>:white_check_mark: OAuth2
5 | Copy a file  | 1. Create a new file <br> 2. Copy the file | The file is copied to the selected location |:white_check_mark: basic<br>:white_check_mark: OAuth2
6 | Delete a file  | 1. Create a new file <br> 2. Delete the file | The file is deleted |:white_check_mark: basic<br>:white_check_mark: OAuth2
7 | Share the file by link | 1. Create a file<br> 2. Long press to share the file by link | The link is generated and works|:white_check_mark: basic<br>:white_check_mark: OAuth2
8 | Share the file by link with pass| 1. Create a file<br> 2. Long press to share the file by link <br> 3. Set a password| The link is generated and works when the correct pass is typed|:white_check_mark: basic<br>:white_check_mark: OAuth2
9 | Unshare the file by link | 1. Unshare the file of previous test cases |  The link is no more available|:white_check_mark: basic<br>:white_check_mark: OAuth2
10 | Share the file with users or groups| 1. Create a new file <br> 2. Long press to share with users/groups <br> 3. Type one user/group to share with |  The user/group can access to the file|:white_check_mark: basic<br>:white_check_mark: OAuth2
11| Unshare the file with users or groups| 1. Unshare the file in the previous test case | The file is not more available for the sharees |:white_check_mark: basic<br>:white_check_mark: OAuth2
12| Download a file| 1. Tap to download a file | The file is downloaded and marked with green arrow|:white_check_mark: basic<br>:white_check_mark: OAuth2
13| Av Offline file | 1. Long press to set as Av Offline a file | The file is downloaded and set as Av Offline with the yellow arrow |:white_check_mark: basic<br>:white_check_mark: OAuth2
14| Av Offline file | 1. Long press to unset an Av Offline a Av Offline file | The file has no more the yellow arrow |:white_check_mark: basic<br>:white_check_mark: OAuth2

**Comment by phil-davis** [comment]
> Last nights automated smoke tests had errors: https://travis-ci.org/owncloud/core/builds/365222767?utm_source=email&utm_medium=notification

All good - they all pass after restarts. "the usual" mix of Travis-SauceLabs intermittent hassles and webdriver timeouts on IE11...

**Comment by patrickjahns** [comment]
# Smoke test - FINAL

## Previous requirements

Prepare two servers with ssl activated and trusted certificates.

Enable LDAP and external storage apps.

Have a LDAP server ready to be used with owncloud.

Have ready two external storages of your choice SMB, SFTP, Dropbox, Google Drive, FTP, S3, ownCloud, local.

## Testing setup


TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Enable encryption app and encryption default module | Encryption is enabled correctly | <ul><li> - [ ] </li></ul> |
2 | Populate owncloud server with users and groups | Users and groups are correctly created | <ul><li> - [ ] </li></ul> |
3 | Share a folder remotely using federated sharing with admin user of the other server. | folder can be opened in recipient server without problems | <ul><li> - [ ] </li></ul> |
4 | Set up LDAP, as admin check users. log in with a LDAP user, if possible one with an avatar. | Users are loaded. LDAP user logs in without problems. Avatar is shown if it exists.  | <ul><li> - [ ] </li></ul> |
5 | Set up two external storages different, disable encryption in one of them.| No errors in this process | <ul><li> - [ ] </li></ul> |

## Testing functionality

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Share a file using federated sharing from an external unencrypted external storage in server #1 using a LDAP user to the admin user in server #2. | Admin user in server #2 can see the file. | <ul><li> - [ ] </li></ul> |
2 | Open internet explorer or edge and upload a new avatar for a regular user not LDAP | Interface can be used, avatar is uploaded, check that personal page has a scroll bar and scrolls fine. | <ul><li> - [ ] </li></ul> |
3 | Upload several files and folders inside external storages, open some. | No problems uploading, files can be downloaded and opened. | <ul><li> - [ ] </li></ul> |
4 | Delete files inside both external storages. Recover some after from the trashbin. |  Files are correctly deleted and restored. | :construction: |
5 | Using webdav upload a 100MiB file.| No errors in this process | <ul><li> - [ ] </li></ul> |

**Comment by PVince81** [comment]
- [x] Tested expiration fix that made it post RC4: https://github.com/owncloud/core/pull/31212 @PVince81 works

**Comment by patrickjahns** [comment]
[  ]  "Using webdav upload a 100MiB file." tested via webui, syncclient and macosxfinder

**Comment by individual-it** [comment]
## automated UI tests on 10.0.8 final tarball

1. install 10.0.8 final
2. copy testing app from git
3. enable testing app
4. from inside a git clone of stable10 branch run tests against 10.0.8 final (we need the git clone because the tests live there and we don't want to copy them into the tarball installation)

suites:
- [x] webUIFavorites - 6 scenarios (6 passed)
- [ ] webUIFiles
- [ ] webUIManageQuota
- [ ] webUIManageUsersGroups
- [ ] webUIMoveFilesFolders
- [ ] webUIPersonalSettings
- [ ] webUIRenameFiles
- [ ] webUIRenameFolders
- [ ] webUIRestrictSharing
- [ ] webUISharingExternal
- [ ] webUISharingInternalGroups
- [ ] webUISharingInternalUsers
- [ ] webUITrashbin
- [ ] webUIUpload

**Comment by patrickjahns** [comment]
Smoke tests completed for final - 🎉
