### ISSUE TITLE
[Feature Request] sort order of apps listed in settings/apps

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#31099]
Checked with 10.0.7
If you look in settings/apps it looks like there is no sort order of the apps listed. See screenshot below.
![image](https://user-images.githubusercontent.com/3321281/38666145-917db2f0-3e3e-11e8-9850-978f9b391e3e.png)

It would look much more professional if the apps are listed in eg alphabetical order.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/12530 (Feature Request), https://github.com/owncloud/core/issues/8569 (Feature requests), https://github.com/owncloud/core/issues/4943 (Apps management sorting in settings), https://github.com/owncloud/core/issues/6250 (New feature request), and https://github.com/owncloud/core/issues/20519 (OwnCloud Feature Request).

**Comment by mmattel** [comment]
@PVince81 any comment on that?

**Comment by phil-davis** [comment]
Yes, I have always thought it odd that you have to just "randomly" scan the displayed apps to see if the one you are looking for is there.
