### ISSUE TITLE
Change Order of the Right Sidebar-Tabs

### ISSUE THREAD

**Issue by balduin-kowalski** [owncloud/core#31090]
I would like to hide Tabs from the right Pop-Up Sidebar (Activity/Comments/Share/Versions) or at least change the Order of them. By default the Activity-Tab is opened first.
Is there a way to only show the Comment-Tab and hide all other Tabs or at least show the Comments-Tab first?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/18164 (Activity/event list for files in right sidebar), https://github.com/owncloud/core/issues/10788 (Remember changes to sort order), https://github.com/owncloud/core/issues/18527 (Right sidebar issues with sharing overviews), https://github.com/owncloud/core/issues/18383 (Right sidebar pushes icons over file names), and https://github.com/owncloud/core/issues/6668 (As a user i want to be able to change the width of the sidebar).
