### ISSUE TITLE
Command files:checksums:verify doesn't print that the verification went well when showing output.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#31133]
### Steps to reproduce

1. Having a fresh server installation run files:checksums:verify command.

### Expected behavior
The output is:
"This operation might take very long."
it does the actual processing, and informs that everything went well.

### Actual behavior
The output is:
"This operation might take very long."
it does the actual processing and nothing is informed.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1

**Cache**
DB

**ownCloud version:** (see ownCloud admin page)
**{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.0.8.1","versionstring":"10.0.8 RC1","edition":"Enterprise","productname":"ownCloud"}**

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
Nothing logged in that operation.

### Client configuration

**Browser**
Chrome.

**Comment by pmaier1** [comment]
Good finding. Considered as nice-to-have from my POV.

**Comment by PVince81** [comment]
moving to 10.0.9
