### ISSUE TITLE
Theming broken after trying to enabling a second theme

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/core#31134]
After trying to activity another theme - ownCloud behaves strange

**IMPORTANT NOTE** this only broken when templateeditor is enabled

#### Pre-Conidtion:
Have templateeditor 0.3 installed + enabled

#### First scenario - broken general section
1. Take ownCloud 10.0.8RC1 with enterprise theme 
2. Go to Apps -> try to enable `theme-example` -> (Error Message `theme-example can't be enabled until theme-enterprise is disabled.` should be shown )
3. Go browse to general section and see it blank:
![image](https://user-images.githubusercontent.com/6403243/38800629-122354b0-4168-11e8-82c4-432382de9994.png)

#### second scenario - "split theme brain"
1. Take ownCloud 10.0.8RC1 with enterprise theme 
2. Go to Apps -> try to enable `theme-example` -> (Error Message `theme-example can't be enabled until theme-enterprise is disabled.` should be shown )
3. Disable `theme-enterprise` 
4. browse to general section and see `theme-example` being used
![image](https://user-images.githubusercontent.com/6403243/38800775-6b7e3f7a-4168-11e8-8c47-42a00fa9b608.png)

### Expected behaviour
General section works as before trying to enable the theme. 

#### broken general section
![image](https://user-images.githubusercontent.com/6403243/38800638-1557c134-4168-11e8-9e94-200a4edcc2df.png)

#### split theme 
![image](https://user-images.githubusercontent.com/6403243/38800775-6b7e3f7a-4168-11e8-8c47-42a00fa9b608.png)

#### ownCloud log (data/owncloud.log)
```
{"reqId":"42azotaIYRMVldUbjbTm","level":3,"time":"2018-04-16T09:10:30+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"core","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","message":"theme-example can't be enabled until theme-enterprise is disabled."}
{"reqId":"NsCi0SJGdiOh1fccNUTJ","level":3,"time":"2018-04-16T09:10:38+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"PHP","method":"GET","url":"\/settings\/admin?sectionid=general","message":"Cannot declare class OC_Theme, because the name is already in use at \/var\/www\/owncloud\/apps\/theme-example\/defaults.php#21"}
{"reqId":"TYevcho3daWp4Axqdu9C","level":3,"time":"2018-04-16T09:10:42+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"PHP","method":"GET","url":"\/settings\/admin?sectionid=general","message":"Cannot declare class OC_Theme, because the name is already in use at \/var\/www\/owncloud\/apps\/theme-example\/defaults.php#21"}
{"reqId":"QqRiDA4QclY51j3tJReh","level":3,"time":"2018-04-16T09:11:13+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"PHP","method":"GET","url":"\/settings\/admin?sectionid=general","message":"Cannot declare class OC_Theme, because the name is already in use at \/var\/www\/owncloud\/apps\/theme-example\/defaults.php#21"}
{"reqId":"tVkTCLg9u4BRGGd7msPx","level":3,"time":"2018-04-16T09:14:20+00:00","remoteAddr":"172.18.0.1","user":"admin","app":"PHP","method":"GET","url":"\/settings\/admin?sectionid=general","message":"Cannot declare class OC_Theme, because the name is already in use at \/var\/www\/owncloud\/apps\/theme-example\/defaults.php#21"}
```

**Comment by pmaier1** [comment]
This should be fixed for 10.0.8 final.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/13402 (... broken), https://github.com/owncloud/core/issues/3209 (Theming), https://github.com/owncloud/core/issues/30887 ([theme-example] Enable only for specific groups ???), https://github.com/owncloud/core/pull/30948 ([Stable10] Protect themes against enabling for groups), and https://github.com/owncloud/core/issues/3645 (Theme Backup).

**Comment by tomneedham** [comment]
@VicDeo ?

**Comment by VicDeo** [comment]
@patrickjahns is any kind of cache enabled?

**Comment by VicDeo** [comment]
https://github.com/owncloud/core/pull/31151

**Comment by PVince81** [comment]
Is there a workaround like letting the admin disable second theme on the CLI ?

**Comment by PVince81** [comment]
@pmaier1 @felixboehm let's move this to 10.0.9, there's a workaround and the PR isn't ready for merge

**Comment by pmaier1** [comment]
Yes, ok :+1:

**Comment by pmaier1** [comment]
workaround not working
active theme is not applied on settings - admin - general page

**Comment by PVince81** [comment]
@pmaier1 can you disable and re-enable the main theme app and confirm you're testing on 10.0.8 RC3 ?

**Comment by PVince81** [comment]
or disable the template editor

need to make sure that even if disabled, that there is only one theme app existing in the apps folder

**Comment by PVince81** [comment]
there's a workaround -> p3

**Comment by PVince81** [comment]
PR was merged, closing. (backport required)
