### ISSUE TITLE
allow searching backend with user:list and group:list

### ISSUE THREAD

**Issue by butonic** [owncloud/core#31149]
currently user:list queries the account table. we should add a `backend` as well as `limit` and `offset` options. This would allow us to get rid of the additional ldap:search command and it would implement the functionality for other user backends.

Same for group:list.

related: https://github.com/owncloud/core/issues/26972 which mentioned this already.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/30003 (Allow user or group exists tests to fail), https://github.com/owncloud/core/issues/29382 (While opening or searching for users within admin user listing, all groups are fetched), https://github.com/owncloud/core/issues/10713 (Everyone Group User Number), https://github.com/owncloud/core/issues/17404 (About search), and https://github.com/owncloud/core/pull/30005 ([stable10] Allow user or group exists tests to fail).
