### ISSUE TITLE
[Feature Request] Better naming for "App-Password" in settings/personal

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#31140]
### Steps to reproduce
1. Goto settings/personal at the bottom to App-Passwords

### Expected behaviour
The term ``App-Password`` has room for improvement.
Even it is a kind of password, it´s correct terminology would be token.
Because we already use password, I propose to write: ``App-Password (Token)`` instead (text change only)
Please see also https://github.com/owncloud/core/pull/31101 (Improving token_auth_enforced description text in config.sample.php)
The location of change is in (L23 and L36): https://github.com/owncloud/core/blob/6f1cd04aef0589f606178d5c24d343dcd762f118/settings/templates/panels/personal/tokens.php#L23

### Actual behaviour
![image](https://user-images.githubusercontent.com/3321281/38814193-3a238682-4191-11e8-9fff-62225e776b95.png)

### Server configuration

**ownCloud version:** (see ownCloud admin page) 10.0.7

@phil-davis @SamuAlfageme

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/8569 (Feature requests), https://github.com/owncloud/core/issues/12530 (Feature Request), https://github.com/owncloud/core/issues/4451 (feature request: increase user password strength), https://github.com/owncloud/core/issues/5167 (Add "Repeat Password" field in personal settings), and https://github.com/owncloud/core/issues/7341 ([FEATURE REQUEST] Force users to password protect shares as link).

**Comment by mmattel** [comment]
I just want to highlight, that the password as "string" is once related to the term password and once with the term "token". Both are valid. Some apps will have the one, some the other term. I want to "link" these terms for all parties out here reducing confusion.
BTW, we have in config.sampe.php (see refrenced issue) also the term token...

**Comment by mmattel** [comment]
Closing, PR got merged
