### ISSUE TITLE
Lost share when transferring files to recipient

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31150]
### Steps

1. Create two users "user1" and "user2"
1. Login as "user1"
1. Create folder "foo/test"
1. Share "foo" with "user2"
1. Login as "user2"
1. Share the received "foo/test" with link
1. Log out
1. On the CLI: `occ files:transfer-ownership user1 user2`
1. Login as "user2"
1. Find the "test" folder in the "transferred from" folder
1. Check link share

### Expected result
Link share preserved

### Actual result
Link share completely lost, even removed from oc_share table.

### Version
10.0.8 RC1

Discovered while testing https://github.com/owncloud/core/pull/30161

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/13671 (Versions lost when moving file into shared folder as recipient), https://github.com/owncloud/core/issues/22594 (Meta data lost when recipient restores a file), https://github.com/owncloud/core/issues/13307 (Move shared file into shared folder as recipient, moved share info lost), https://github.com/owncloud/core/issues/16225 (Files_texteditor gets frozen when a user tries to open a shared file as recipient which was deleted), and https://github.com/owncloud/core/issues/15468 (Files stop being shared after a recipient restores them to previous versions).

**Comment by PVince81** [comment]
talked with @felixboehm and we're going to revert the original fix as the effect is less critical

then move ticket to 10.0.9 for a proper full fix

**Comment by PVince81** [comment]
The revert doesn't solve the issue.

@sharidas will try to find a solution. I expect it to be non-intrusive and should not affect QA testing efforts. If a solution is found in time we can consider putting it in RC3 if a RC3 is deemed necessary.

@pmaier1 @felixboehm FYI

**Comment by PVince81** [comment]
Investigated with @sharidas: the public link has a "parent" field pointing to the regular share.
When we delete the regular share, the link share is deleted as well as the parent is gone.
The reason we delete the regular share from "user1" to "user2" is because "user2" becomes the owner, so the share in question isn't necessary any more.

@sharidas is investigating if there is a good way to deparent the reshare so it can continue to exist, with a solution within the boundaries of the current sharing API.

**Comment by PVince81** [comment]
to be rescheduled

**Comment by PVince81** [comment]
I misunderstood, this was close to completion and just got finished. Closing

**Comment by sharidas** [comment]
In the above scenario, the deletion of share at https://github.com/owncloud/core/blob/stable10/lib/private/Share20/Manager.php#L730.
Which internally calls deletion of children at https://github.com/owncloud/core/blob/stable10/lib/private/Share20/Manager.php#L978.

I was having a thought of processing public links first. But this code path suggests that it doesn't give any upper edge if we process public links first and the remaining shares at the last.

**Comment by sharidas** [comment]
Manual testing of scenario https://github.com/owncloud/core/issues/31150#issue-314806286 still fails when the git HEAD is pointed to commit ( git reset ) representing this pr https://github.com/owncloud/core/pull/31176

**Comment by sharidas** [comment]
Would it be a bad solution if the `deleteShare()` (here -> https://github.com/owncloud/core/blob/stable10/lib/private/Share20/Manager.php#L962 ) is allowed to exclude some of its children? May be pass the types of children that we want to exclude. And the same argument to be passed to `deleteChildren()` https://github.com/owncloud/core/blob/stable10/lib/private/Share20/Manager.php#L913
And then in the deleteChildren loop just ignore the type and continue.

If the exclude list is empty the behaviour of `deleteShare()` or `deleteChildren()` would be same as we have now.

**Comment by sharidas** [comment]
> Not sure if it would be a good idea, because it means you'd have orphaned entries in the DB where the "parent" value points nowhere. If we had foreign key contraints it would be stricly forbidden by the DB.

Yes the orphaned entries in the DB was pulling me back from this idea.

> How about gathering the list of children before doing any deletion ? Then transfer the children. Once the transfer is done, proceed with deletion.

didn't quite get by 'transfer the children'

**Comment by sharidas** [comment]
> How about gathering the list of children before doing any deletion ? Then transfer the children. Once the transfer is done, proceed with deletion.

Ok so if I understood correctly for 'transfer the children' -> Create new share from the child share. And then proceed with the deletion.

**Comment by PVince81** [comment]
or just update the child share to not have a parent value any more ? whatever you already did in the current code, but do it earlier ?

**Comment by sharidas** [comment]
Created a WIP PR -> https://github.com/owncloud/core/pull/31924.
