### ISSUE TITLE
Public link share name length check is inaccurate

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31157]
### Steps

1. Create a public link share
1. Type in 64 characters and make sure there are special unicode characters like "ü"
1. Save share

### Expected
Share name is accepted

### Actual
Share name rejected
![image](https://user-images.githubusercontent.com/277525/38857760-50a80592-422a-11e8-9193-71acd2f79237.png)

### Version
10.0.8 RC1

It seems the limit is 64 ASCII characters and when using unicode it would use more bytes in the database. Not sure what to do in this case as we cannot predict accurately how many characters would be allowed if all of them were unicode.

Maybe the PHP function used for the check needs to account for unicode characters as well, but if it does, will the database (all DB types) accept them despite the fact that a unicode character will use more bytes ? Something to try.

This issue is likely to happen for other columns as well.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/1074 (Public sharing and pretty URL), https://github.com/owncloud/core/issues/15022 (Share link hangs), https://github.com/owncloud/core/issues/18737 (share link problem), https://github.com/owncloud/core/issues/20442 (Share link hidden), and https://github.com/owncloud/core/issues/5689 (Moving folder changes public share link).
