### ISSUE TITLE
Public link icons squished

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31158]
### Steps

1. Create link share and enter a long name, with some white spaces
1. Create another link share and enter a long name without white spaces
1. Save

### Expected
Proper wrapper, no squished icons

### Actual
![image](https://user-images.githubusercontent.com/277525/38858000-f15fba5c-422a-11e8-85a6-d549cace7531.png)

### Version
ownCloud 10.0.8 RC1

@felixheidecke FYI

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/9707 (More understandable icon for public links), https://github.com/owncloud/core/issues/30802 (Switch to local view from public link), https://github.com/owncloud/core/issues/5689 (Moving folder changes public share link), https://github.com/owncloud/core/issues/1620 (public share link: home icon missing in IE8), and https://github.com/owncloud/core/issues/66 (Icons missing).

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/core/pull/31163

Somehow the code of the original fix got killed through a rebase
