### ISSUE TITLE
Group-administrators can not activate/deactivate users

### ISSUE THREAD

**Issue by balduin-kowalski** [owncloud/core#31169]
I think this feature would be helpful. At the moment only administrators can activate/deactivate users.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/12349 ([7.0.3] Group administrator can't add users to the goup), https://github.com/owncloud/core/issues/600 (Groups cannot be assigned with more than 30 users), https://github.com/owncloud/core/issues/4174 (Unable to add new user group), https://github.com/owncloud/core/issues/5024 (Can't edit user groups and group admins), and https://github.com/owncloud/core/issues/8993 (Cannot remove the groups in new user management).

**Comment by PVince81** [comment]
seems this feature exists but was broken, closing in favor of https://github.com/owncloud/core/issues/31280
