### ISSUE TITLE
remove duplicated storages while checking the filecache corruption

### ISSUE THREAD

**Issue by cdamken** [owncloud/core#31165]
![repair-error](https://user-images.githubusercontent.com/7264495/38865195-68cb4ea0-423d-11e8-8493-f48b52014ffe.png)

The error is confusing for administrators that storage appears many times.

Can we just have unique values?

@tomneedham @butonic @PVince81

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/3260 (- Removed -), https://github.com/owncloud/core/issues/240 (--- Removed ---), https://github.com/owncloud/core/issues/3864 (storage and filecache corruption?), https://github.com/owncloud/core/issues/26325 (Remove local:: storage fallback), and https://github.com/owncloud/core/issues/23256 (Feature: Disable filecache for certain external storages).

**Comment by PVince81** [comment]
@tomneedham I think you had a fix for this but somehow this didn't make it in the backports ?

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/33468
