### ISSUE TITLE
many files (mostly >100kb) have been corrupted when I migrated to a new server

### ISSUE THREAD

**Issue by andrewjob** [owncloud/core#31167]
### Steps to reproduce
1. Installed and set-up owncloud X on a new server, with only one user
2. Copied files from data under old server to new server using rsync for the new user
3. ran php occ files:scan --all
4. In the browser all files are shown, however, some files will not download or open, mostly large files

### Expected behaviour
All the files should be accessible, however, many files come up with an error.

### Actual behaviour
comes up with error:
Service unavailable

### Server configuration
**Operating system**:
CentOS 7, with Apache, MySQL

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/11818 (Migrate encrypted Files to new Server), https://github.com/owncloud/core/issues/16676 (Renaming Files Corrupts Them), https://github.com/owncloud/core/issues/1049 (corrupted files after sync), https://github.com/owncloud/core/issues/16425 (several owncloud file corrupted), and https://github.com/owncloud/core/issues/9542 (Ignore files on server side).

**Comment by PVince81** [comment]
You need to migrate the database. Don't just copy the files over as you'll lose all metadata.

Unlikely to be a bug as this is not a supported scenario. Please ask on http://central.owncloud.org/ if you need assistance
