### ISSUE TITLE
Enabled theme app outside of OC folder doesn't work

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31170]
### Steps

1. Install OC 10.0.8 RC2 from tarball inside "/srv/www/htdocs/owncloudtest"
2. Create a folder "/srv/www/htdocs/temp" and give web server permissions
3. Move the example theme from "/srv/www/htdocs/owncloudtest/apps/theme-example" to "/srv/www/htdocs/temp/theme-example"
4. Adjust config.php: 
```
 'apps_paths' => 
    array (
      0 => 
      array (
        'path' => '/srv/www/htdocs/owncloudtest/apps',
        'url' => '/apps',
        'writable' => 'false',
      ),
      1 => 
      array (
        'path' => '/srv/www/htdocs/temp',
        'url' => '/apps-temp',
        'writable' => 'true',
      ),
    ),
```
5. Open the web UI as admin
6. Go to settings and enable the theme-example app
7. Refresh the page / log out then log in again

### Expected result
Example theme applied

### Actual result
Default theme still visible

### Logs
Nothing

### Version
ownCloud 10.0.8 RC2

@VicDeo please have a look, this is supposed to work after https://github.com/owncloud/core/pull/30477

**Comment by VicDeo** [comment]
@PVince81 `'url'` should be relative to OC webroot
 'url' => '../apps-temp',

**Comment by VicDeo** [comment]
... and for
```
 'path' => '/srv/www/htdocs/temp',
```

it should be 
```
1 => 
      array (
        'path' => '/srv/www/htdocs/temp',
        'url' => '.../temp',
        'writable' => 'true',
      ),
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/3209 (Theming), https://github.com/owncloud/core/issues/9154 (Enable app for group only does not work.), https://github.com/owncloud/core/issues/391 (Sharing doesn't work when picture App is enabled), https://github.com/owncloud/core/issues/550 (folders in Pictures don't work), and https://github.com/owncloud/core/issues/3758 (Drag & Drop folder does not work).

**Comment by PVince81** [comment]
Doesn't work with either of these:
- "../apps-temp"
- ".../apps-temp"
- "../temp"
- ".../temp"

I checked that the app is enabled and force refresh the browser, no luck.

Also I settled on "../temp" and reenabled the app, also doesn't work.

A relative URL sounds like it's looking for trouble...

**Comment by PVince81** [comment]
More info, something wrong with URL building:
![image](https://user-images.githubusercontent.com/277525/38873984-4f50074e-4257-11e8-9301-e263fe588cd2.png)

Full config.php in case it's useful:
```
<?php
$CONFIG = array (
  'instanceid' => 'ocz6lm568ewo',
  'passwordsalt' => 'HT5rttNF6DqMLyd6c2sBzH7jr8iXqW',
  'secret' => 'QFvxBlphP3aV4WgZxMw33USPw56m+o8JbCNlhgZtDk41pLRI',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/srv/www/htdocs/owncloudtest/data',
  'overwrite.cli.url' => 'http://localhost/owncloudtest',
  'dbtype' => 'mysql',
  'version' => '10.0.8.2',
  'dbname' => 'owncloudtest',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'owncloud',
  'dbpassword' => 'owncloud42',
  'logtimezone' => 'UTC',
  'installed' => true,
 'apps_paths' => [[
        'path' => '/srv/www/htdocs/owncloudtest/apps',
        'url' => '/apps',
        'writable' => 'false',
        ], [
        'path' => '/srv/www/htdocs/temp',
        'url' => '../temp',
        'writable' => 'true',
]],
);
```

**Comment by VicDeo** [comment]
@PVince81 sorry, there should be two dots, not three. We don't process assets in core so they are handled by a web-server.

ok, I'm testing with `http://localhost/owncloudtest` base url.

**Comment by PVince81** [comment]
My guess is that since the PR was merged maybe some other PR added some URL sanitization of some sorts and might discard dots.

In any case I'd have hoped for a solution that doesn't involve such hacky-looking URL prefix. Do we have this in the documentation ?

**Comment by tboerger** [comment]
That's why the docker container adds a symlink to the custom apps folder within the document root.

**Comment by VicDeo** [comment]
> In any case I'd have hoped for a solution that doesn't involve such hacky-looking URL prefix. Do we have this in the documentation ?

@PVince81 AFAIK this exact case in not documented. While url in apps_paths  has the following description https://github.com/owncloud/core/blob/master/config/config.sample.php#L728

**Comment by VicDeo** [comment]
aargh. it works for `http://localhost/something/owncloudtest` and not for `http://localhost/owncloudtest`...

**Comment by VicDeo** [comment]
yep, there is a bug in `OC\App\AppManager::getAppWebPath` exactly for this case.  It builds the URLs  with double leading slash and due to this hostname is not added `http://temp//theme-example/apps/files/js/files.js?v=3db57c92729c1551555f489fbdab281d`

**Comment by PVince81** [comment]
@VicDeo what about if the theme is in a completely different folder like "/tmp/apps" ? what would the matching URL be in that case ?
