### ISSUE TITLE
Could disable app be half-automated during upgrade process?

### ISSUE THREAD

**Issue by hodyroff** [owncloud/core#31180]
10.0.7 upgrade to 10.0.8RC
Getting this message:
"2018-04-18T06:43:08+00:00 Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
2018-04-18T06:43:08+00:00 Repair warning: Please install or update the following apps manually or disable them with:
occ app:disable logreader
2018-04-18T06:43:08+00:00 OC\RepairException: Upgrade is not possible
2018-04-18T06:43:08+00:00 Update failed
"

So far, so good. Could the process ask next: "Do you want to disable blabla app not y/n" so its clearer what has to be done and even somewhat guided?

**Comment by DeepDiver1975** [comment]
possible in console upgrade - not in the web updater

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/19891 (Upgrade disabled apps listed twice), https://github.com/owncloud/core/issues/14820 (Couldn't install any app), https://github.com/owncloud/core/issues/16904 (Don't disable encryption app on upgrades), https://github.com/owncloud/core/issues/14754 (Only disable third party apps for major upgrades), and https://github.com/owncloud/core/issues/26226 ([master] LDAP app not loaded during upgrade).
