### ISSUE TITLE
10.0.7 doesn't work with php7.2

### ISSUE THREAD

**Issue by wom-bat** [owncloud/core#31191]
I tried to switch from php7.1 to php7.2.  To check dependencies I did:
```
sudo -u www-data php7.2 ./occ check
```
I expect this to work even if some of the dependencies are missing.
The output is a stack backtrace:
```
An unhandled exception has been thrown:
Error: Call to undefined function OC\App\simplexml_load_file() in /var/www/owncloud/lib/private/App/InfoParser.php:41
Stack trace:
#0 /var/www/owncloud/lib/private/legacy/app.php(641): OC\App\InfoParser->parse('/var/www/ownclo...')
#1 /var/www/owncloud/lib/private/legacy/app.php(614): OC_App::getAppInfo('/var/www/ownclo...', true)
#2 /var/www/owncloud/lib/private/App/AppManager.php(599): OC_App::getAppVersionByPath('/var/www/ownclo...')
#3 /var/www/owncloud/lib/private/App/AppManager.php(557): OC\App\AppManager->getAppVersionByPath('/var/www/ownclo...')
#4 /var/www/owncloud/lib/private/App/AppManager.php(509): OC\App\AppManager->findAppInDirectories('files')
#5 /var/www/owncloud/lib/private/legacy/app.php(566): OC\App\AppManager->getAppPath('files')
#6 /var/www/owncloud/lib/private/legacy/app.php(117): OC_App::getAppPath('files')
#7 /var/www/owncloud/lib/base.php(579): OC_App::loadApps(Array)
#8 /var/www/owncloud/lib/base.php(998): OC::init()
#9 /var/www/owncloud/console.php(64): require_once('/var/www/ownclo...')
#10 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#11 {main}
```

**Comment by wom-bat** [comment]
If I install php7.2-xml things seem to work as expected.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/10741 (OC 7.0.2 Sharing apps with only certain groups don't work.), https://github.com/owncloud/core/issues/10824 (LDAP Backend not working in 7.0.2), https://github.com/owncloud/core/issues/30935 (Clicking link for row doesn't open folder or file 10.0.7.2), https://github.com/owncloud/core/issues/9998 ([7.0.2] Preview of pictures not working in the home folder), and https://github.com/owncloud/core/issues/9146 (7.0 alpha 2 - [RC2] sharing doesn't work).
