### ISSUE TITLE
Federated share http fallback switch not working

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31194]
See https://github.com/owncloud/core/pull/30198

### Steps
1. Disable "http" fallback
TODO

### Expected
No http fallback

### Actual
http fallback seems to be in place

### Version
ownCloud 10.0.8 RC3

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/19477 (Federated Cloud Sharing without Resharing), https://github.com/owncloud/core/issues/17551 (Sharing from server A daily (https) to server B (http) federated sharing does not work), https://github.com/owncloud/core/issues/20216 (Use HTTPS for federated cloud share when another share already uses HTTPS), https://github.com/owncloud/core/issues/20329 (Federated shared subfolder not syncing.), and https://github.com/owncloud/core/issues/22721 (Federated shares accepted and not displayed).
