### ISSUE TITLE
Legacy theme issue with web root

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31205]
See https://github.com/owncloud/core/pull/31203 for some context

@VicDeo can you have a look ? Also need to check other code paths to make sure they also don't need adjusting

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/3209 (Theming), https://github.com/owncloud/core/issues/21767 (issue), https://github.com/owncloud/core/issues/3662 (Issues with themes), https://github.com/owncloud/core/issues/22237 (Theming issues), and https://github.com/owncloud/core/pull/31204 ([stable10] Fix legacy theme urls).

**Comment by VicDeo** [comment]
I think it is worth trying to refactor `\OC\URLGenerator::imagePath` into `ImageResourceLocator` class like  `CSSResourceLocator` and `JSResourceLocator` etc.

**Comment by PVince81** [comment]
@VicDeo as you like, if that makes for better and more testable code

**Comment by PVince81** [comment]
to be rescheduled. workaround: implement theme as app

**Comment by PVince81** [comment]
I'd be ok with refactoring, am mostly worried about implied QA workload to retest theming

**Comment by PVince81** [comment]
@VicDeo do you have an estimate for refactoring + implementing proper unit tests ?
Then separate estimate for the actual fix

**Comment by VicDeo** [comment]
can't reproduce with master@b161b208d3420a71a86c91e802cb6ef2eb8f3ba9

## Steps:
### Test 1
0. setup oc in `/srv/www/htdocs/owncloud` 
1. `mkdir -p themes/skull`
2. copy some css from core
themes/skull/core/css/header.css
themes/skull/core/css/share.css
themes/skull/core/css/icons.css
themes/skull/core/css/styles.css
3. Put the same non-default image into 
themes/skull/core/img/breadcrumb.svg
themes/skull/core/img/actions/add.svg
themes/skull/core/img/logo-icon.svg
4. set theme to `skull` in config.php
#### Expected & Actual:
<img width="863" alt="case1" src="https://user-images.githubusercontent.com/991300/42908207-f7ba51a8-8ae8-11e8-8e37-d66348f37a05.png">

### Test 2
0. use the prev environment
1. add 
```
<img src="<?php p(\OC::$server->getURLGenerator()->getAbsoluteURL(image_path('core', 'actions/add.svg'))) ?>" />
```
into settings/templates/panels/personal/profile.php

2. browse into the personal settings
#### Expected & Actual:
<img width="660" alt="case2" src="https://user-images.githubusercontent.com/991300/42908395-80f185a4-8ae9-11e8-94d0-b61f7eccc348.png">

**Comment by PVince81** [comment]
hmmm, and https://github.com/owncloud/core/pull/31203/files#r182761409 doesn't provide a clue what could possibly go wrong ?

**Comment by VicDeo** [comment]
@PVince81 it's too generic and doesn't specify what exactly is broken. Like "his head is aching let's cut it off"
At least `image_path` in templates and CSS resource locator are not broken.

**Comment by PVince81** [comment]
ok, closing then if not reproducible
