### ISSUE TITLE
new repo for theme-example

### ISSUE THREAD

**Issue by felixboehm** [owncloud/core#31206]
Can we cut out the example theme to an own repo?
https://github.com/owncloud/core/tree/stable10/apps/theme-example

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/3209 (Theming), https://github.com/owncloud/core/issues/3662 (Issues with themes), https://github.com/owncloud/core/issues/22237 (Theming issues), https://github.com/owncloud/core/issues/4605 (Theme problem), and https://github.com/owncloud/core/issues/3645 (Theme Backup).

**Comment by DeepDiver1975** [comment]
here we go: https://github.com/owncloud/theme-example

**Comment by DeepDiver1975** [comment]
and here https://github.com/owncloud/core/pull/31208

**Comment by PVince81** [comment]
should it be pulled from marketplace then ? or should the build script just fetch the separate repo ?

reopening until we have a resolution

**Comment by DeepDiver1975** [comment]
or non of them - people who want to develop an example theme can go to that repo and have a look.

There is no need to install it from the marketplace of ship it - nobody will productivly run this theme

**Comment by patrickjahns** [comment]
I think this needs some adjustments for documentation - (add the link where to find it) and people can be happy

**Comment by DeepDiver1975** [comment]
> I think this needs some adjustments for documentation - (add the link where to find it) and people can be happy

@settermjd

**Comment by DeepDiver1975** [comment]
so we close this as soon as docs have been updated/doc issue is created
