### ISSUE TITLE
Confusing behaviour with single user syncing if the user doesn't exists

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#31207]
### Steps to reproduce
1. Setup user_ldap with one server
2. Sync all the users
3. Sync only a missing user with the `user:sync -u` option. The user must not exists neither as ownCloud account nor in the backend

### Expected behaviour
Error about the missing user is shown

### Actual behaviour
It follows the standard process as if the user / account exists
```
root@3b450a98bad4:/opt/owncloud# sudo -u www-data ./occ user:sync -u miimi "OC\User\Database"
If unknown users are found, what do you want to do with their accounts? (removing the account will also remove its data)
  [0] disable
  [1] remove
  [2] ask later
 > 2
Syncing miimi ...
These accounts that are no longer available in the backend:
miimi, ,  (no longer exists in the backend)
What do you want to do with their accounts? (removing the account will also remove its data)
  [0] disable
  [1] remove
 > 0
Disabling accounts
miimi, ,  (no longer exists in the backend)
```

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** apache 2.4

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** ownCloud 10.0.8RC3

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
@tomneedham mind having a look ?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/30485 (Introduce single user and seen users sync), https://github.com/owncloud/core/issues/31028 (Allow single user sync of new users), https://github.com/owncloud/core/issues/23838 (Allow disabling of a single user), https://github.com/owncloud/core/issues/21931 (SFTP: Sync over single connection), and https://github.com/owncloud/core/pull/31025 (Stable10 seen single sync).
