### ISSUE TITLE
Missing conditional logging target logfile for users

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/core#31200]
### Steps to reproduce

1. Create a user called "user1".
2. In config.php add log condition for user1:
```
'log.conditions' => [
                'users' => ['user1'],
                'logfile' => '/opt/owncloud/data/user1.log'
],
 ```
3. Put logging level to DEBUG.
4. Login as user1, do some file operations as him.

### Expected behavior
A file called /opt/owncloud/data/user1.log appears and start to log everything related

### Actual behavior
No new log file is created for user1.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1

**Cache**
DB

**ownCloud version:** (see ownCloud admin page)
**{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.0.8.3","versionstring":"10.0.8 RC3","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```
```

### Client configuration

**Browser**
Chrome.  
  

@mmattel if the steps are wrong, please comment and we'll discuss to close this issue.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/11582 ("Local" missing from user configurable external storage ), https://github.com/owncloud/core/issues/6966 (Get logged in status for any user), https://github.com/owncloud/core/issues/17845 (Make conditional logging work with exclusions), https://github.com/owncloud/core/issues/30853 (A log is shown when we create a regular user), and https://github.com/owncloud/core/issues/23795 (OwnCloud 9 logging into wrong user profile).

**Comment by sharidas** [comment]
@SergioBertolinSG on stable10 branch below are the steps executed by me:
- created users `admin` and `user1`.
- update the config.php as
```
'log.conditions' => [
        [
                'users' => ['user1'],
                'logfile' => '/home/sujith/test/owncloud/data/user1.log'
        ],
],
```
- Now login as `user1`
- Able to locate the file `/home/sujith/test/owncloud/data/user1.log`
- Content of the file:
```
{"reqId":"bIWqkSwr1KCEsIbGu5v1","level":0,"time":"2018-04-19T11:36:22+00:00","remoteAddr":"127.0.0.1","user":"user1","app":"files_skeleton","method":"POST","url":"\/testing\/index.php\/login","message":"copying skeleton for user1 from \/home\/sujith\/test\/owncloud\/core\/skeleton to \/user1\/files\/"}
{"reqId":"0fhPRIok2LeE0REQKKxi","level":0,"time":"2018-04-19T11:36:24+00:00","remoteAddr":"127.0.0.1","user":"user1","app":"core","method":"GET","url":"\/testing\/index.php\/core\/preview.png?file=%2Fwelcome.txt&c=712cbc348e0cf97e1ceb49302329c945&x=32&y=32&forceIcon=0","message":"Generating preview for \"\/welcome.txt\" with \"OC\\Preview\\TXT\""}
```
Note: No loglevel is either added in the config.php nor updated anything in the UI.

**Comment by PVince81** [comment]
@SergioBertolinSG is this a regression ?

**Comment by SergioBertolinSG** [comment]
> 'log.conditions' => [
>         [
>                 'users' => ['user1'],
>                 'logfile' => '/home/sujith/test/owncloud/data/user1.log'
>         ],
> ],

Using @sharidas config it has worked fine. (missing square brackets).



> @SergioBertolinSG is this a regression ?

It not a bug, closing.

**Comment by mmattel** [comment]
is there a documentation issue?
