### ISSUE TITLE
Cannot use / in url params

### ISSUE THREAD

**Issue by butonic** [owncloud/core#31223]
### Steps to reproduce
1. register a route with a param, eg `/resource/{id}`
2. try to use an id with a `/`. it should be urlencoded, so the url in a request will look like `/resource/id%2Fwith%2Fslashes`

### Expected behaviour
The controller should get `id/with/slashes` as a parameter.

### Actual behaviour
The controller is never called because the url never matches.
1. make sure apache does not auto decode slashes by adding `AllowEncodedSlashes On` to the virtualhosts section. Otherwise you [get an immediate 404 without php ever seeing the request](https://github.com/owncloud/user_management/pull/20#issuecomment-383037854)
2. Even with `AllowEncodedSlashes On` the url gets decoded in Symphonys URLMatcher. In the worst case this [might cause calling the wrong route](https://stackoverflow.com/questions/47973132/symfony-3-4-routing-urlencoded-in-the-parameter-value-cause-not-matching-th#comment82932678_47973462).

### Related
https://github.com/owncloud/user_management/pull/20#issuecomment-383037854

**Comment by butonic** [comment]
It turns out symphony has a way to configure the regex used to match a parameter: https://symfony.com/doc/current/routing/slash_in_parameter.html

**Comment by butonic** [comment]
That means our resource urls are generated without this.

**Comment by phil-davis** [comment]
Are there any cases where ``{id}`` is followed by more parameters or URL parts?
e.g.
```
/ocs/v1.php/settings/users/admin/displayName
```
and if you create a user called ``admin/displayName`` then there could be trouble.
It depends how long the ``%2F`` stays around. The client is going to access:
```
/ocs/v1.php/settings/users/admin%2FdisplayName
```
to try and find out about that nasty-named user.
And to find/set their ``displayName``
```
/ocs/v1.php/settings/users/admin%2FdisplayName/displayName
```

**Comment by butonic** [comment]
@paurakhsharma please try with https://github.com/owncloud/core/pull/31224
