### ISSUE TITLE
Log failed accesses using a generic Fail2ban pattern

### ISSUE THREAD

**Issue by benrubson** [owncloud/core#31234]
Hi,

When a login attempt fails, following error message is triggered :
`[owncloud][core][2] Login failed: 'admin' (Remote IP: '1.2.3.4')`

Would be nice if error messages could follow the "generic" Fail2Ban patterns.

At least when `'log_type' => 'errorlog'` is used.

Thank you very much 👍 

Ben

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/5554 (Logs for webdav access), https://github.com/owncloud/core/issues/14305 (App access to certain groups fails), https://github.com/owncloud/core/issues/20182 (Failed login Log entry format), https://github.com/owncloud/core/issues/24727 ('Login failed' log entries when using token auth), and https://github.com/owncloud/core/issues/20659 (Missing singlequote for login failed log entry).
