### ISSUE TITLE
robots.txt missing from owncloud-10 archive

### ISSUE THREAD

**Issue by benrubson** [owncloud/core#31237]
Hi,

`robots.txt` file is in the archives we can download from here :
https://github.com/owncloud/core/releases
But missing from the owncloud-10.*.(tar.bz2|zip) archives we can download from here :
https://owncloud.org/download/
However it is in owncloud-9 archives.

Any issue with the building process ?

Thank you 👍 

Ben

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/12903 (robots.txt missing from ZIP), https://github.com/owncloud/core/issues/29297 (Cant disable Encryption Owncloud 10), https://github.com/owncloud/core/issues/12357 (Owncloud 7 - missing files), https://github.com/owncloud/core/issues/27768 (Missing user_ldap after Upgrade to 10), and https://github.com/owncloud/core/issues/20314 (Owncloud 8.2 missing dependences).

**Comment by PVince81** [comment]
Thanks for spotting.

In OC 10 we moved to a Makefile process which selectively copies files from the source instead of copying all + deleting.

Seems we missed robots.txt there.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/31248

**Comment by benrubson** [comment]
Nice, thank you Vincent 👍

**Comment by DeepDiver1975** [comment]
All prs are merged -> close
