### ISSUE TITLE
Files locked although Redis and APCu are in place

### ISSUE THREAD

**Issue by loonyinfo** [owncloud/core#31243]
Hello everyone,

as suggested here: [https://central.owncloud.org/t/files-locked-although-redis-and-apcu-are-in-place/13133](url) I open this case here, too.

I use Owncloud 10.0.8 and I'm the only user on the system. but as soon as I set 'filelocking.enabled' => true,in the config.php I get almost always the error message that a file is locked although I haven't touched it for hours.
I already configured Redis and APCu for the system and I use a system cron that runs every 15 min. but all those steps heven't helped. 
Does anyone have the same problem and may help me.?
I ask because at the moment 'filelocking.enabled' => false is set to make the system useable, But then I get a warning in Settings->General for the Admin that Transactional file locking is disabled.

Many thanks in advance for your help.

Remark:
My installation uses the 30 day Enterprise trial at the moment, which is availabe for everyone. That's why it says "ownCloud edition": "Enterprise",. But as long as you have not paid for the license there is no Enterprise support for the installation. 
### Steps to reproduce
Setup a system like mine and log in as the only user on the system.
Set Apache as owner of all files of the installation and set the recommended file rights.
Try to upload more than one file or try to touch a file. You get a locked message.

### Expected behaviour
No files locked due to the fact that only one user with one session is using the system..

### Actual behaviour
Files I haven't touched for hours are locked and I'm not able to upload or download things. The system is almost unuseable.

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache 2.4.18 (Ubuntu)

**Database:**
MariaDB 10.2.12

**PHP version:**
7.0.28 (Ubuntu)

**Redis version**
Redis: 3.2.10

**ownCloud version:** (see ownCloud admin page)
10.0.8

**Updated from an older ownCloud or fresh install:**
Updated from 10.0.7 but the behaviour was the same on 10.0.7

**Where did you install ownCloud from:**
Installed Owncloud repository for Ubuntu 16.04.and then run apt-get install owncloud-files

**The content of config/config.php:**
{
    "basic": {
        "license key": "***REMOVED SENSITIVE VALUE***",
        "date": "Mon, 23 Apr 2018 01:58:54 +0000",
        "ownCloud version": "10.0.8.5",
        "ownCloud version string": "10.0.8",
        "ownCloud edition": "Enterprise",
        "server OS": "Linux",
        "server OS version": "Linux ip-172-31-172-43 4.4.0-1054-aws #63-Ubuntu SMP Wed Mar 28 19:42:42 UTC 2018 x86_64",
        "server SAPI": "apache2handler",
        "webserver version": "Apache\/2.4.18 (Ubuntu)",
        "hostname": "loony.info",
        "user count": 2,
        "user directories": 2,
        "logged-in user": "***REMOVED SENSITIVE VALUE***"
    },
    "config": {
        "updatechecker": false,
        "updater.server.url": "https:\/\/updates.owncloud.com\/server\/",
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_wellknown_setup": true,
        "check_for_working_htaccess": true,
        "operation.mode": "single-instance",
        "instanceid": "ocgxrv4lh7zr",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "loony.info"
        ],
        "datadirectory": "\/mnt\/efs\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/loony.info",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "10.0.8.5",
        "dbname": "ownclouddb",
        "dbhost": "loonyinfo.cgjmc5efrkph.eu-west-1.rds.amazonaws.com",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": false,
        "filelocking.ttl": 60,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "loonyredis.wq1zqa.clustercfg.euw1.cache.amazonaws.com",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 3,
        "singleuser": false,
        "maintenance": false,
        "upgrade.automatic-app-update": true
    },
    "integritychecker": {
        "passing": true,
        "enabled": true,
        "result": []
    },
    "core": {
        "allow_user_mount_sharing": "yes",
        "backgroundjobs_mode": "cron",
        "default_encryption_module": "OC_DEFAULT_MODULE",
        "enable_external_storage": "yes",
        "encryption_enabled": "yes",
        "installedat": "1520676864.3005",
        "lastcron": "1524447907",
        "lastupdateResult": "[]",
        "lastupdatedat": "1524448690",
        "public_files": "files_sharing\/public.php",
        "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
        "remote_nonshib-webdav": "user_shibboleth\/appinfo\/remote.php",
        "shareapi_allow_public_notification": "yes",
        "umgmt_send_email": "true",
        "umgmt_show_backend": "true",
        "umgmt_show_email": "true",
        "umgmt_show_is_enabled": "true",
        "umgmt_show_last_login": "true",
        "umgmt_show_storage_location": "true",
        "vendor": "owncloud"
    },
    The rest I deleted due to size limitations.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/26838 (File locking), https://github.com/owncloud/core/issues/24737 (File Locked), https://github.com/owncloud/core/issues/28991 (file is locked), https://github.com/owncloud/core/issues/16966 (File locking TTL), and https://github.com/owncloud/core/issues/21881 (File Permanently Locked).

**Comment by loonyinfo** [comment]
I reenabled filelocking and here is the log I get,:
{"reqId":"06vgqIa3vZtDANzuouZH","level":4,"time":"2018-04-23T10:50:08+00:00","remoteAddr":"172.31.27.40","user":"loonyadmin","app":"webdav","method":"GET","url":"\/remote.php\/webdav\/ILS\/Hinweise_Fernlernen.pdf","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"ILS\\\/Hinweise_Fernlernen.pdf\\\" is locked\",\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/efs\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(85): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/mnt\\\/efs\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/mnt\\\/efs\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/mnt\\\/efs\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/mnt\\\/efs\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/mnt\\\/efs\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/mnt\\\/efs\\\/www\\\/ow...')\\n#7 {main}\",\"File\":\"\\\/mnt\\\/efs\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":386,\"User\":\"loonyadmin\"}"}
{"reqId":"9XSIooAuhkWkegnoZ2BL","level":4,"time":"2018-04-23T10:50:42+00:00","remoteAddr":"172.31.27.40","user":"loonyadmin","app":"webdav","method":"GET","url":"\/remote.php\/webdav\/Photos\/San%20Francisco.jpg?downloadStartSecret=efzn2fvjk2","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"Photos\\\/San Francisco.jpg\\\" is locked\",\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/efs\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(85): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/mnt\\\/efs\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/mnt\\\/efs\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/mnt\\\/efs\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/mnt\\\/efs\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/mnt\\\/efs\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/mnt\\\/efs\\\/www\\\/ow...')\\n#7 {main}\",\"File\":\"\\\/mnt\\\/efs\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":386,\"User\":\"loonyadmin\"}"}

**Comment by loonyinfo** [comment]
Problem solved:
"timeout": 0,
"password": "REMOVED SENSITIVE VALUE"
Those two lines in the redis array in the config.php for owncloud were the problem. I close this issue.
