### ISSUE TITLE
Settings: Hide sections that have no panels to display

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#31246]
Users are confused when they see sections in the settings that have no panels (because apps that would insert panels are disabled). Anyway, it would be a lot more elegant to hide such sections instead of displaying "Error: No panels for this section.".

![hide_unused_settings](https://user-images.githubusercontent.com/21193500/39124506-00dc6ad6-46fc-11e8-9cbd-5c7cece22cef.png)

I know that @tomneedham started with this when reworking the settings page for ownCloud 10.

@PVince81

**Comment by phil-davis** [comment]
Yes, at least for the first cut at it, remove the "Error" in big letters :)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/1329 (sharing folder: no "create" setting displayed initially), https://github.com/owncloud/core/issues/9098 (Display remote shares in "Shared with you" section), https://github.com/owncloud/core/issues/27518 (Avoid the error when there're no panels to show under one section on settings ), https://github.com/owncloud/core/issues/965 (No settings dialogue for Pictures section), and https://github.com/owncloud/core/issues/30394 (Display original share owner in share panel).

**Comment by pmaier1** [comment]
> Yes, at least for the first cut at it, remove the "Error" in big letters :)

Yes, a better message to not confuse users with "errors" would be a first step in the right direction. Depending on effort for the proper solution this would be the quick fix.

In general I would really favor the approach to hide sections that have no content. Just checked quickly: For "Additional" admin/user sections this applies, too, and potentially to others as well.

**Comment by SamuAlfageme** [comment]
@pmaier1 dupe of https://github.com/owncloud/core/issues/27518 - close one of 'em

**Comment by PVince81** [comment]
there is some tricky API issue here as we only know at render time, might need a clever hack.

estimate: 1-3md depending on how hacky/clean it is. hopefully not breaking the panels API

cc @tomneedham

**Comment by tomneedham** [comment]
I wanted to allow panels to respond if they are hidden or not - allowing for a more efficient code stack rather than rendering them all and generating the section list. Baby step: nicer message: 2 min job. Real fix: extend the api and implement this in all panels.

**Comment by pmaier1** [comment]
https://github.com/owncloud/core/pull/36775

**Comment by youssefskhiri** [comment]
> Users are confused when they see sections in the settings that have no panels (because apps that would insert panels are disabled). Anyway, it would be a lot more elegant to hide such sections instead of displaying "Error: No panels for this section.".
> 
> ![hide_unused_settings](https://user-images.githubusercontent.com/21193500/39124506-00dc6ad6-46fc-11e8-9cbd-5c7cece22cef.png)
> 
> I know that @tomneedham started with this when reworking the settings page for ownCloud 10.
> 
> @PVince81

Im facing this problem, I've installed owncloud on a container and I want to inegrate collabora with it
According to official documentation its in additional section which is in my case with the same error  (  Error: No panels for this section. ) 

I would be glad if I get a solution from you :)

**Comment by iasdeoupxe** [comment]
AFAICT what you are describing is completely irrelevant / unrelated to this issue:

IIUC this feature request was about hiding the "No panels for this section" if there is NOTHING to show, NOT about that there is something to show but is isn't showing up (what you seems to think).

Your issue sounds more like a support request for https://central.owncloud.org/
