### ISSUE TITLE
Upgrade command returns code 3 if up to date

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#31257]

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/29252 (Upgrade to 10.0.3 impossible), https://github.com/owncloud/core/issues/25589 (After Upgrade Code integrity check fails), https://github.com/owncloud/core/issues/16361 (upgrading to 8.0.3), https://github.com/owncloud/core/issues/19184 (After Upgrade to 8.1.3), and https://github.com/owncloud/core/issues/26907 (Upgrade from 9.1.3 to master :bomb:).

**Comment by PVince81** [comment]
well it can be used in scripting, but you need another if condition.

I believe this was on purpose @DeepDiver1975 @VicDeo

**Comment by DeepDiver1975** [comment]
> I believe this was on purpose @DeepDiver1975 @VicDeo

yes this was on purpose - we shall not change this behaviour - this is documented and used already out there.

closing as won't fix
