### ISSUE TITLE
173 Requests when files app is loaded

### ISSUE THREAD

**Issue by Henning1984HH** [owncloud/core#31251]
### Steps to reproduce
1. Log in to your owncloud
2. Open the Files app via the menu
3. Hit F12 in Chrome or FF and switch over to Network Tab.
4. Hit the record button inside the Network analysis and refresh the page to see what resources get loaded.

### Expected behaviour
1. Minified versions or the possibility to enable minification of js, css and html
2. Reduced number of requests
3. With caching enabled in the network tab I get a load time of 1.7 - 2.5 sec
4. Expected gain is a faster and more responsive UI.

### Actual behaviour
I see 173 requests for various resources (js, css, svg, html) etc. by opening just the files app. No script is minified nor loaded in a hand full of request but each gets loaded separately.

The Files app took 967kb to fully load.

### Server configuration
**Operating system**: Raspian 

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7

**ownCloud version:** 10.0.8.5

**Updated from an older ownCloud or fresh install:** Updated from 10.0.7 (But the behavior was the same in 10.0.7

**Where did you install ownCloud from:** owncloud.org

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**The content of config/config.php:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "10.0.8.5",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 0,
        "maintenance": false,
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": ***REMOVED SENSITIVE VALUE***
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php"
    }
}

**List of activated apps:**

Enabled:
  - configreport: 0.1.1
  - dav: 0.3.2
  - encryption: 1.3.1
  - external: 1.2
  - federatedfilesharing: 0.3.1
  - files: 1.5.1
  - files_clipboard: 0.7.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - gallery: 16.0.2
  - market: 0.2.4
  - provisioning_api: 0.5.0
  - qownnotesapi: 17.7.0
  - security: 0.0.2
  - twofactor_backup_codes: 0.0.4
  - twofactor_totp: 0.4.4
  - updatenotification: 0.2.1
Disabled:
  - comments
  - federation
  - files_videoplayer
  - firstrunwizard
  - notifications
  - systemtags
  - theme-example
  - user_external

**Are you using external storage, if yes which one:** No

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:**  Firefox 59.0.2 64 Bit

**Operating system:** Windows 10 64 Bit

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/17245 (Prevent version app operations when file is locked), https://github.com/owncloud/core/issues/6945 (When refreshing an app page after some time, Files app gets loaded instead), https://github.com/owncloud/core/issues/27890 (File list loaded twice), https://github.com/owncloud/core/issues/26226 ([master] LDAP app not loaded during upgrade), and https://github.com/owncloud/core/issues/9770 (Disable "Share files" breaks files app).

**Comment by DeepDiver1975** [comment]
This is a known issue. Given the current Code base this is hard to address.
We will relauch the webui in the scope of https://GitHub.com/owncloud/phoenix
