### ISSUE TITLE
Symfony events for user preference changes

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31264]
We already trigger symfony events before and after system config and app config changes.

We should also do so for user preference changes.

@tomneedham @sharidas

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/30996 (Throw symfony events on group actions), https://github.com/owncloud/core/pull/30054 ([stable10] Bump symfony/event-dispatcher from 3.2.4 to 3.2.14), https://github.com/owncloud/core/pull/30930 (Add symfony events for delete share), https://github.com/owncloud/core/pull/29885 (Adding new Symfony events), and https://github.com/owncloud/core/pull/30570 ([WIP] Adding symfony events for shares).

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/core/pull/31266
