### ISSUE TITLE
ownCloud 10.0.7 integrity check error for bundled templateeditor

### ISSUE THREAD

**Issue by andreysaksonov** [owncloud/core#31262]
### Steps to reproduce
1. Follow instructions on https://download.owncloud.org/download/repositories/stable/owncloud/index.html for Ubuntu 16.04
2. apt install owncloud-files

### Expected behaviour
Integrity Check - OK.

### Actual behaviour
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- templateeditor
	- FILE_MISSING
		- l10n/mk.js
		- l10n/mk.json
	- EXTRA_FILE
		- l10n/mk.php
		- Makefile

Raw output
==========
Array
(
    [templateeditor] => Array
        (
            [FILE_MISSING] => Array
                (
                    [l10n/mk.js] => Array
                        (
                            [expected] => 59c1253859c1af4541b303152a95e3ae7dee3bcc3f4b4e03ae399ac7a7f20fd83219c6d654cd2f49817ddfdec1e96abe402cacfba497e6a5f6106b16ce3fa1b5
                            [current] => 
                        )

                    [l10n/mk.json] => Array
                        (
                            [expected] => f558578603f20f0b4585b37cb2d163806b5fe0bfdbe3ee333412c012f6ddcc0163932ad55f56e8917281e7342883f487bad57805991a72eae86446faf7a0090a
                            [current] => 
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [l10n/mk.php] => Array
                        (
                            [expected] => 
                            [current] => ce1715a6789d5e6f63dd804edcddbc7b6ca942d886e0a5fb29496cf5f822e4b2661167dcebeb94b6ab6f09ca91ec7f25c2020454ab516a1997f328a76f6358e3
                        )

                    [Makefile] => Array
                        (
                            [expected] => 
                            [current] => 8ac57be439422bb259461e99361e86392395c91efeb0525b1a36b5f081334e9c8993c46e664d8ac1b31473052701420d8a3513e7a5270148b68afd7938cfa069
                        )

                )

        )

)
```

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** lighttpd 1.4.35

**Database:** PostgreSQL 9.5

**PHP version:** PHP 7.0.28

**ownCloud version:** 10.0.7

**Comment by andreysaksonov** [comment]
I checked package content in https://download.owncloud.org/download/repositories/production/Ubuntu_16.04/ (owncloud-files_10.0.7.orig.tar.gz) and found that those extra files are present in archive (Makefile and l10n/mk.php) and l10n js files are missed for Macedonian language (l10n/mk.js, l10n/mk.json). Another thing is that those files are not generated (I think it should) with:
```
root@host:/var/www/owncloud# sudo -u www-data php occ l10n:createjs templateeditor
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/18040 (owncloud 7.0.7 broken), https://github.com/owncloud/core/issues/28840 (-Error-), https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/30225 (integrity check issue), and https://github.com/owncloud/core/issues/3261 (Owncloud errors).

**Comment by PVince81** [comment]
@crrodriguez please verify. I don't see how the Makefile could be present as it isn't present in the release tarball https://download.owncloud.org/community/owncloud-10.0.7.tar.bz2

**Comment by andreysaksonov** [comment]
Today owncloud-files package got updated to 10.0.8 and issue gone
