### ISSUE TITLE
Cannot see members of a group having special characters(@,/,&) in its name

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/core#31279]
### Steps to reproduce
1. Create a group with name containing special character (@,/,&) eg. admin&management, admin/intern
2. Assign users to the group
3. See that only the number of members in a group is listes but not the list of members 

### Expected behaviour
Either admin should not be able to create a group with name having special characters in it.
Or if you can create such groups, it should function like a group with normal name

### Actual behaviour
Unable to see the list of members in a group

### Server configuration
**Operating system**: Ubuntu 17.10

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.1

**ownCloud version:** (see ownCloud admin page) 10.0.8.5

**Where did you install ownCloud from:** git

#### Browser log
```
Request URL: http://localhost/core/index.php/settings/users/users?offset=0&limit=200&gid=people%2523me&pattern=
Request Method: GET
Status Code: 200 OK
```
### Screenshot
![image](https://user-images.githubusercontent.com/20378877/39291179-db9a31d8-4951-11e8-8597-4503ed18e573.png)

**Comment by PVince81** [comment]
@phil-davis was that what https://github.com/owncloud/user_management/pull/20 was intended to fix ?

**Comment by phil-davis** [comment]
Yes, see https://github.com/owncloud/user_management/pull/20 for the WIP fix that will need to be "back-ported" to ``core`` ``master``

And see https://github.com/owncloud/user_management/issues/19 for the issue that group names containing space do not list the members.

**Comment by butonic** [comment]
duplicate of https://github.com/owncloud/core/issues/31223
