### ISSUE TITLE
Redesign and move settings:admin:sharing APIs away from Ajax

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/core#31309]
One starting point for our latest API-documentation efforts was to observe and map the XHR traffic from the webUI in order to get an idea of which public interfaces (surface) a client should use to interact with the server. 

Normally, clients don't require APIs to interact with core settings - unless we're speaking about **reading said settings** to adjust their behavior to server's (e.g. disabling some sharing options, setting a chunking algorithm...)

Now that we want to look at [Phoenix](https://github.com/owncloud/phoenix) as an advanced, modern client that **must have to interact in detail with some of the admin settings**,  we should also uncouple and get rid of some of the old Ajax APIs that do the job on the webUI. And while doing so, untangle some of ownCloud's most complicated and ambiguous settings: sharing: 

![screenshot 2018-04-30 13 11 34](https://user-images.githubusercontent.com/2644445/39424687-1a01b292-4c78-11e8-8f48-2d7059574006.png)

I thought it would be a good idea for this use-case to **integrate these with the capabilities into a higher-level, extensible, first class citizen "Capabilities API"**. 

This issue might be seen as part of a bigger picture (e.g. https://github.com/owncloud/core/issues/4774) - feel free to close if a coarse-grained approach (to track in larger issues/PRs) is preferred.

cc/ @patrickjahns as part of the API power-users team. @DeepDiver1975 to get architectural insights on the last.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/18199 (Add more Options to Admin-Settings.), https://github.com/owncloud/core/issues/11648 ([Ask Feature] A sharing setting), https://github.com/owncloud/core/issues/17863 (Admin-Page: Sharing-settings are available when sharing app is disabled), https://github.com/owncloud/core/issues/12970 (Redesign / revamp folder share permissions), and https://github.com/owncloud/core/issues/11288 (Shared link expires before set date by user and admin).
