### ISSUE TITLE
`user:sync --quiet` should log errors to the console

### ISSUE THREAD

**Issue by butonic** [owncloud/core#31310]
When syncing 100k users from ldap on the CLI the admin should see some feedback when a user property could not be mapped (eg the email could not be determined). Currently we only log this to the logfile.

It should also produce output on the CLI so that running the sync command with `--quiet` in a cron job can be used to notify the admin via email when there is a problem. Cron won't send an email if the output wis empty, which is why `--quiet` is important to work correctly.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/28840 (-Error-), https://github.com/owncloud/core/issues/29082 (a Error), https://github.com/owncloud/core/issues/11622 (Calendar Sync in Thunderbird Errors), and https://github.com/owncloud/core/issues/12143 (owncloud.log flooded with errors).

**Comment by mmattel** [comment]
If there will be a PR filed for this, a documentation note is necessary, just as a reminder :smile:
