### ISSUE TITLE
Upgrade to 10.0.8 on PostgreSQL 10.x

### ISSUE THREAD

**Issue by mbalmer** [owncloud/core#31320]
The update to Version 10.0.8 on PostgreSQL 10.x fails with the following error message:

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_account_terms_id_seq"': SQLSTATE[42703]: Undefined column: 7 FEHLER: Spalte »min_value« existiert nicht LINE 1: SELECT min_value, increment_by FROM "oc_account_terms_id_seq... ^

### Steps to reproduce
1. Go to you ownCloud installation with the browser
2. Click on "Update" Button
3. Wait for a few seconds

### Expected behaviour
ownCloud should update the database to the 10.0.8 scheme

### Actual behaviour
It shows above error message

### Server configuration
**Operating system**:

Ubuntu 16.04 x86_64

**Web server:**

nginx

**Database:**

PostgreSQL 10.3

### Notes: ###

As of PostgreSQL 10, it is no longer possible to query the minimum value and increment directly from a sequence, as was the case in PostgreSQL 10.  To get these values the query "select min_value, increment_by from pg_catalog.pg_sequences where sequencename = 'oc_account_terms_id_seq';" can be used.

select

**Comment by phil-davis** [comment]
"As of PostgreSQL 10,..., as was the case in PostgreSQL 10" ???

I guess that you mean to mention different versions in the 2 places in this sentence?

**Comment by mbalmer** [comment]
Yes, it worked in version 9, does not in version 10.


the file ./lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php

must use the following code ti get the values:


 $data = $this->_conn->fetchAll('SELECT min_value, increment_by FROM pg_catalog.pg_sequences where sequencename = \'' . $sequenceName . '\'');

**Comment by DeepDiver1975** [comment]
We do  not yet support postgres 10 .... should be in the docs ...

**Comment by DeepDiver1975** [comment]
duplicate of #29997

**Comment by ho4ho** [comment]
> https://github.com/owncloud/core/issues/31320#issuecomment-385896511
> .... should be in the docs ...

Why not create issue then? :smiley: Done by https://github.com/owncloud/docs/issues/490
