### ISSUE TITLE
Send mail notification for shared files breaks if Collaborative Tags-App is disabled

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/core#31338]
### Steps to reproduce
1. Disable _Collaborative tags_ in the apps section
2. Enable _"Allow users to send mail notification for shared files"_ in sharing settings
3. Create a public link share

### Expected behaviour
Modal should should show sharing-form

### Actual behaviour
Empty modal opens

### Server configuration
**Operating system**:
any 
**Web server:**
any
**Database:**
any
**PHP version:**
any
**ownCloud version:** (see ownCloud admin page)
10.0.8

### Problem

select2 lib is provided by the Collaborative Tags-App and used in the mail notification process.

#### Javascript console log

`this.$el.find(...).select2 is not a function`

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/9770 (Disable "Share files" breaks files app), https://github.com/owncloud/core/issues/4499 (Shared File Notifications), https://github.com/owncloud/core/issues/12608 (Shared file notifications), https://github.com/owncloud/core/issues/3465 (Sharing files), and https://github.com/owncloud/core/issues/17829 (Disabling and re-enabling file sharing breaks files app).

**Comment by felixboehm** [comment]
Please add a test to ensure we will not have regressions.

**Comment by individual-it** [comment]
@phil-davis opened an issue for this kind of tests https://github.com/owncloud/QA/issues/561

**Comment by PVince81** [comment]
This was already reported to us here https://github.com/owncloud/core/issues/31454 and also more people told me directly.

Increasing to p2 as release blocker for next release.

**Comment by PVince81** [comment]
leaving open until backport is done

**Comment by PVince81** [comment]
will be released in 10.0.9 (next release)
