### ISSUE TITLE
Error 12 interacting with memcached : CONNECTION DATA EXISTS

### ISSUE THREAD

**Issue by kwisatz** [owncloud/core#31350]
### Steps to reproduce
1. Install memcached
2. Set up memcached for file locking
3. 

### Expected behaviour

Use memcached successfully for file locking, do not throw exceptions

### Actual behaviour

Getting exceptions in the log for any file operation:

```
{
"reqId":"0b3b441c-08dd-4b05-b7ce-40f050660431",
"level":3,
"time":"2018-05-04T07:23:38+00:00",
"remoteAddr":"195.218.30.41",
"user":"********************",
"app":"no app in context",
"method":"DELETE",
"url":"/remote.php/dav/files/********************/********************/Formulaire********************.docx",
"message":"Exception: {"Exception":"Exception","Message":"Error 12 interacting with memcached : CONNECTION DATA EXISTS","Code":0,"Trace":"#0 
```

Full log entry below.

### Server configuration
**Operating system**: Debian 8.10

**Web server:** Apache 2.4

**Database:** Mysql 5.5

**PHP version:** 5.6.33

**ownCloud version:**  10.0.8.5

**Updated from an older ownCloud or fresh install:** Updated from 9.1.6.2

**Where did you install ownCloud from:** package manager

**The content of config/config.php:**
```
{
    "system": {
        "debug": false,
        "updatechecker": false,
        "instanceid": "ocn9d23yezta",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.domain.tld"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/my.domain.tld",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "10.0.8.5",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/owncloud\/owncloud.log",
        "logtimezone": "UTC",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": ""
    }
}
```
**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

#### ownCloud log (data/owncloud.log)
```
{"reqId":"0b3b441c-08dd-4b05-b7ce-40f050660431","level":3,"time":"2018-05-04T07:23:38+00:00","remoteAddr":"*************","user":"***********","app":"no app in context","method":"DELETE","url":"\/remote.php\/dav\/files\/***********\/Horaires\/Formulaire%20de%20cong%C3%A9_Kevin.docx","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Error 12 interacting with memcached : CONNECTION DATA EXISTS\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Memcache\\\/Memcached.php(170): OC\\\\Memcache\\\\Memcached->verifyReturnCode()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Memcache\\\/Memcached.php(183): OC\\\\Memcache\\\\Memcached->add('files\\\/ac34ff928...', 0)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Lock\\\/MemcacheLockingProvider.php(79): OC\\\\Memcache\\\\Memcached->inc('files\\\/ac34ff928...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(653): OC\\\\Lock\\\\MemcacheLockingProvider->acquireLock('files\\\/ac34ff928...', 1)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(589): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/Horaires\\\/...', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(589): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/Horaires\\\/...', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(589): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/Horaires\\\/...', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1973): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/Horaires\\\/...', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(2075): OC\\\\Files\\\\View->lockPath('\\\/Horaires\\\/Formu...', 1, false)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1356): OC\\\\Files\\\\View->lockFile('\\\/Horaires\\\/Formu...', 1)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1403): OC\\\\Files\\\\View->getCacheEntry(Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Checksum), 'files\\\/Horaires\\\/...', '\\\/Horaires\\\/Formu...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/HookConnector.php(143): OC\\\\Files\\\\View->getFileInfo('\\\/Horaires\\\/Formu...')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/HookConnector.php(103): OC\\\\Files\\\\Node\\\\HookConnector->getNodeForPath('\\\/Horaires\\\/Formu...')\\n#13 [internal function]: OC\\\\Files\\\\Node\\\\HookConnector->postDelete(Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): call_user_func(Array, Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1298): OC_Hook::emit('OC_Filesystem', 'post_delete', Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1224): OC\\\\Files\\\\View->runHooks(Array, '\\\/Horaires\\\/Formu...', true)\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(737): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/Horaires\\\/Formu...', Array)\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(Array)\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(747): OC\\\\Files\\\\View->emittingCall(Object(Closure), Array, 'file', 'delete')\\n#20 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(402): OC\\\\Files\\\\View->unlink('\\\/Horaires\\\/Formu...')\\n#21 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n#22 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('files\\\/******...')\\n#23 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#24 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#25 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#26 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#27 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(278): Sabre\\\\DAV\\\\Server->exec()\\n#28 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#29 \\\/var\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/ownclo...')\\n#30 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Memcache\\\/Memcached.php\",\"Line\":223}"}
```

**Comment by IljaN** [comment]
Have you tried to upgrade php to 7.1? 5.6 is not supported with 10.0.8, see https://doc.owncloud.org/server/latest/admin_manual/release_notes.html#changes-in-10-0-8

**Comment by kwisatz** [comment]
It actually states here that 5.6 will only be deprecated starting with 10.1.


https://doc.owncloud.com/server/latest/admin_manual/installation/system_requirements.html#officially-recommended-supported-options


And the package didn't have any such dependencies. I'd expect it to have
those.

**Comment by phil-davis** [comment]
Yes, PHP ``5.6.33`` is supported and also works with ownCloud ``10.0.8``

So the issue here "must" be some interaction with ``memcached``

**Comment by IljaN** [comment]
Sorry for the noise :)

**Comment by SmartOPZ** [comment]
Same issue here with a fresh 10.8.5 install.
Same with previous 10.0.7.2.


```
   'memcache.local' => '\\OC\\Memcache\\Memcached',
   'memcache.locking' => '\\OC\\Memcache\\Memcached',
   'memcached_servers' => array(
        array('localhost', 11211),
   ),
```

Debian 9 environment :
- PHP 7.0.27-0+deb9u1
- memcached 1.4.33-1

Any clue on how to solve this issue ?
Thx 👍

**Comment by patrickjahns** [comment]
@SmartOPZ @kwisatz 

It would be great if you could provide the full stack trace of the error message

**Comment by SmartOPZ** [comment]
I reproduced the issus to get the full stacktrace, here it is :
`{"reqId":"aZ7PVQfLD8YXPPDZyLii",`
`"level":3,"time":"2018-05-18T06:44:45+00:00",`
`"remoteAddr":"192.168.10.120",`
`"user":"admin",`
`"app":"no app in context",`
`"method":"DELETE",`
`"url":"\/remote.php\/webdav\/ownCloud%20Manual.pdf",`
`"message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Error 12 interacting with memcached : CONNECTION DATA EXISTS\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Memcache\\\/Memcached.php(170): OC\\\\Memcache\\\\Memcached->verifyReturnCode()\\n#1 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Memcache\\\/Memcached.php(183): OC\\\\Memcache\\\\Memcached->add('files\\\/22b849c6d...', 0)\\n#2 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Lock\\\/MemcacheLockingProvider.php(79): OC\\\\Memcache\\\\Memcached->inc('files\\\/22b849c6d...')\\n#3 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(653): OC\\\\Lock\\\\MemcacheLockingProvider->acquireLock('files\\\/22b849c6d...', 1)\\n#4 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(589): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/ownCloud ...', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#5 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(589): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/ownCloud ...', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#6 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(589): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/ownCloud ...', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#7 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Files\\\/View.php(1972): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/ownCloud ...', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#8 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Files\\\/View.php(2075): OC\\\\Files\\\\View->lockPath('\\\/ownCloud Manua...', 1, false)\\n#9 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Files\\\/View.php(1356): OC\\\\Files\\\\View->lockFile('\\\/ownCloud Manua...', 1)\\n#10 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Files\\\/View.php(1403): OC\\\\Files\\\\View->getCacheEntry(Object(OCA\\\\Files_Trashbin\\\\Storage), 'files\\\/ownCloud ...', '\\\/ownCloud Manua...')\\n#11 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Files\\\/Node\\\/HookConnector.php(143): OC\\\\Files\\\\View->getFileInfo('\\\/admin\\\/files\\\/ow...')\\n#12 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Files\\\/Node\\\/HookConnector.php(103): OC\\\\Files\\\\Node\\\\HookConnector->getNodeForPath('\\\/ownCloud Manua...')\\n#13 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OC\\\\Files\\\\Node\\\\HookConnector->postDelete(Array)\\n#14 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Files\\\/View.php(1296): OC_Hook::emit('OC_Filesystem', 'post_delete', Array)\\n#15 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Files\\\/View.php(1224): OC\\\\Files\\\\View->runHooks(Array, '\\\/ownCloud Manua...', true)\\n#16 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Files\\\/View.php(737): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/ownCloud Manua...', Array)\\n#17 \\\/var\\\/www\\\/\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(Array)\\n#18 \\\/var\\\/www\\\/\\\/lib\\\/private\\\/Files\\\/View.php(747): OC\\\\Files\\\\View->emittingCall(Object(Closure), Array, 'file', 'delete')\\n#19 \\\/var\\\/www\\\/\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(402): OC\\\\Files\\\\View->unlink('\\\/ownCloud Manua...')\\n#20 \\\/var\\\/www\\\/\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n#21 \\\/var\\\/www\\\/\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('ownCloud Manual...')\\n#22 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#23 \\\/var\\\/www\\\/\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#24 \\\/var\\\/www\\\/\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#25 \\\/var\\\/www\\\/\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#26 \\\/var\\\/www\\\/\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#27 \\\/var\\\/www\\\/\\\/remote.php(165): require_once('\\\/home\\\/client.rl...')\\n#28 {main}\",\"File\":\"\\\/var\\\/www\\\/\\\/lib\\\/private\\\/Memcache\\\/Memcached.php\",\"Line\":223}"}`

**Comment by elonmir** [comment]
Same thing here.

**Comment by jawrat** [comment]
I was getting the same error and found that by removing memcache.locking from my config, it fixed the issue and file synchronization is now working as expected.

**Comment by madpsy** [comment]
@jawrat That 'solution' worked for me (just comment 'memcache.locking' out in config.php) . Unsure of any negative side affects with disabling locking but sure I'll find out over time.

**Comment by paraqles** [comment]
Same problem here.
Disabling locking for now helps -> maybe decrease in performance

**Comment by benrubson** [comment]
Same issue here with version 10.0.10.
@patrickjahns, @phil-davis some news on this perhaps ?
Thank you very much 👍

```
{"reqId":"M8rhULN83VVM9wamQlXC",
"level":3,"time":"2019-01-03T07:43:53+00:00",
"remoteAddr":"109.210.55.124",
"user":"admin",
"app":"no app in context",
"method":"DELETE",
"url":"\/remote.php\/webdav\/FileShot201.txt","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Error 12 interacting with memcached : CONNECTION DATA EXISTS\",\"Code\":0,\"Trace\":\"#0 \\\/owncloud\\\/lib\\\/private\\\/Memcache\\\/Memcached.php(170): OC\\\\Memcache\\\\Memcached->verifyReturnCode()\\n#1 \\\/owncloud\\\/lib\\\/private\\\/Memcache\\\/Memcached.php(183): OC\\\\Memcache\\\\Memcached->add('files\\\/6dd80b2c4...', 0)\\n#2 \\\/owncloud\\\/lib\\\/private\\\/Lock\\\/MemcacheLockingProvider.php(79): OC\\\\Memcache\\\\Memcached->inc('files\\\/6dd80b2c4...')\\n#3 \\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(657): OC\\\\Lock\\\\MemcacheLockingProvider->acquireLock('files\\\/6dd80b2c4...', 1)\\n#4 \\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/FileSh...', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#5 \\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(588): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/FileSh...', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#6 \\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1975): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/FileSh...', 1, Object(OC\\\\Lock\\\\MemcacheLockingProvider))\\n#7 \\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(2078): OC\\\\Files\\\\View->lockPath('\\\/FileShot20...', 1, false)\\n#8 \\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1361): OC\\\\Files\\\\View->lockFile('\\\/FileShot20...', 1)\\n#9 \\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1408): OC\\\\Files\\\\View->getCacheEntry(Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Checksum), 'files\\\/FileSh...', '\\\/FileShot20...')\\n#10 \\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/HookConnector.php(143): OC\\\\Files\\\\View->getFileInfo('\\\/admin\\\/files\\\/File...')\\n#11 \\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/HookConnector.php(103): OC\\\\Files\\\\Node\\\\HookConnector->getNodeForPath('\\\/FileShot20...')\\n#12 \\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OC\\\\Files\\\\Node\\\\HookConnector->postDelete(Array)\\n#13 \\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1301): OC_Hook::emit('OC_Filesystem', 'post_delete', Array)\\n#14 \\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1226): OC\\\\Files\\\\View->runHooks(Array, '\\\/FileShot20...', true)\\n#15 \\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(739): OC\\\\Files\\\\View->basicOperation('unlink', '\\\/FileShot20...', Array)\\n#16 \\\/owncloud\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(Array)\\n#17 \\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(749): OC\\\\Files\\\\View->emittingCall(Object(Closure), Array, 'file', 'delete')\\n#18 \\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(422): OC\\\\Files\\\\View->unlink('\\\/FileShot20...')\\n#19 \\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(179): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->delete()\\n#20 \\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(287): Sabre\\\\DAV\\\\Tree->delete('FileShot201...')\\n#21 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#22 \\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#23 \\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#24 \\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#25 \\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#26 \\\/owncloud\\\/remote.php(165): require_once('\\\/owncloud...')\\n#27 {main}\",\"File\":\"\\\/owncloud\\\/lib\\\/private\\\/Memcache\\\/Memcached.php\",\"Line\":223}"}
```

**Comment by Shucach** [comment]
Sometimes i have the same error. 
witch version 10.0.10 php-7.0

**Comment by Shucach** [comment]
> I was getting the same error and found that by removing memcache.locking from my config, it fixed the issue and file synchronization is now working as expected.

I did the same and it's really helped me.

**Comment by Nikolo** [comment]
Same issue here with version 10.0.10.4
OS: FreeBSD 11.2-RELEASE-p5
PHP: PHP 7.1.24 (cli) (built: Nov 29 2018 01:24:22) ( NTS )

**Comment by V1pr** [comment]
Same issue here, disabling locking solved the issue.
OC: 10.0.10
OS: Debian 9.7
PHP: 7.0.33-0+deb9u1

**Comment by mrsamirmh** [comment]
Still getting the same error. 
````"Exception: Error 12 interacting with memcached : CONNECTION DATA EXISTS````

Upload going successfully after trying a couple of minutes of failure.
Any quick fix ?

**Comment by mrodriguezmad** [comment]
Same error with:
Owncloud: 10.2.0.5
Memcached: 1.4.33
PHP: 7.0.33 (via FPM)

Config:
  'memcache.locking' => '\\OC\\Memcache\\Memcached',
  'memcache.local' => '\\OC\\Memcache\\Memcached',
  'memcache.distributed' => '\\OC\\Memcache\\Memcached',
  'memcached_servers' => 
  array (
    0 => 
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),

**Comment by benrubson** [comment]
Still facing this with 10.3.0 version.
Could it be possible to have a look at it please ?
Thank you very much 👍

**Comment by Lord-Y** [comment]
Same issue here

**Comment by ho4ho** [comment]
> 'memcache.locking' => '\OC\Memcache\Memcached',

https://doc.owncloud.com/server/10.3/admin_manual/configuration/server/caching_configuration.html#memcached reads by:

> it is not suitable to use with Transactional File Locking

Correctly use Redis insted? https://doc.owncloud.com/server/10.3/admin_manual/configuration/server/caching_configuration.html#configuring-transactional-file-locking

**Comment by kwisatz** [comment]
> > 'memcache.locking' => '\OC\Memcache\Memcached',
> 
> https://doc.owncloud.com/server/10.3/admin_manual/configuration/server/caching_configuration.html#memcached reads by:
> 
> > it is not suitable to use with Transactional File Locking

Ha, we must all be blind…

**Comment by benrubson** [comment]
> Ha, we must all be blind…

Not sure, more than a recommendation not to use it (related to how Memcache works), it should at least work, and not raise this exception, IMO.

**Comment by ho4ho** [comment]
> it should at least work

If not suitable not implemented by ownCloud?

> and not raise this exception, IMO.

Same, create new issue for ownCloud?

**Comment by ho4ho** [comment]
Not good in coding but maybe help by #36484
