### ISSUE TITLE
Public link over file permission, not switchable

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#31366]
### Steps to reproduce
1. Create a public link over a file

### Actual behaviour

![39624866-2d5cd4c2-4f9b-11e8-88c2-277c69f78497](https://user-images.githubusercontent.com/14894746/39692918-9c7aad5e-51e2-11e8-8b1d-c3bba1c275d3.gif)

### Expected behaviour

Option should be "switchable"

Core
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.0.8.5","versionstring":"10.0.8","edition":"Enterprise","productname":"ownCloud"}

Related: https://github.com/owncloud/android/issues/2066

**Comment by PVince81** [comment]
It was never a feature to have read-write public link file shares.

Either we need to remove this permissions block to match the current feature set or allow for read-write public link file share.

Note that writable public link file share only makes sense when the file is mounted with "Add to ownCloud" as the web UI does not allow for uploading+overwriting a single file share. So if we want the latter, more work will be needed to provide this functionality.

For the short term I suggest removing the permissions box for single file shares.

@felixheidecke @pmaier1

**Comment by pmaier1** [comment]
> For the short term I suggest removing the permissions box for single file shares.

Agreed (although I find it not that bad that you see a radio button there, it's just that other options are missing). Need concept for more permissions at some point.
