### ISSUE TITLE
Server-side Encryption HELP

### ISSUE THREAD

**Issue by Yoshimanly** [owncloud/core#31362]
I need help, I enabled encryption being the dummy I am, and didn't think I would have any problem disabling it. I can't run occ commands, it always tell me "Could not open input file: occ".

I have been trying to go to the owncloud file and doing it from there and it doesn't throw that error but nothing happens. Which btw the directory is as follows: /var/lib/univention-appcenter/apps/owncloud

I'm running a Vmware UCS 4.2 with owncloud server 10.0.3, downloaded directly from the website.
I'm getting a bit scared at this point, I have to a bit to much to backup on various accounts.

**Comment by patrickjahns** [comment]
This is the ownCloud issue tracker - for assistance please go to https://central.owncloud.org/ and ask the community to help.

As you are requesting assistance and not reporting an issue, I will close this for now.
