### ISSUE TITLE
OCS/cloud/users/ quota differs from WebDAV's 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/core#31376]
@davigonz discovered just now that #owncloud/android is using the `{{server}}/ocs/v1.php/cloud/users/{{user}}` endpoint to query quota information from the server (ref. [`GetRemoteUserQuotaOperation:RemoteOperationResult()`](https://github.com/owncloud/android-library/blob/22893587753e528f168d15c49366f3e552108ef5/src/com/owncloud/android/lib/resources/users/GetRemoteUserQuotaOperation.java#L79)) - we noticed some unexpected behavior as for: 

## Result from `GET /ocs/v1.php/cloud/users/{{user}}`

```
curl -u 'admin:admin' -X GET 'https://demo.owncloud.com/ocs/v1.php/cloud/users/admin?format=json' -H 'OCS-APIREQUEST: true'
```

```json
{
    "ocs": {
        "meta": {
            "status": "ok",
            "statuscode": 100,
            "message": null
        },
        "data": {
            "enabled": "true",
            "quota": {
                "free": 56690487296,
                "used": 5812174,
                "total": 56696299470,
                "relative": 0.01
            },
            "email": null,
            "displayname": "admin",
            "home": "/mnt/data/files/admin",
            "two_factor_auth_enabled": "false"
        }
    }
}
```

## ... while the `PROPFIND` returns:

```
curl -u 'admin:admin' -H 'Depth:0' -H 'Content-Type:text/xml; charset=utf-8' -X PROPFIND 'https://demo.owncloud.com/remote.php/webdav/' --data-binary '<?xml version="1.0" ?>
<d:propfind xmlns:d="DAV:">
  <d:prop>
    <d:quota-available-bytes />
    <d:quota-used-bytes />
  </d:prop>
</d:propfind>
'
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:s="http://sabredav.org/ns">
   <d:response>
      <d:href>/remote.php/webdav/</d:href>
      <d:propstat>
         <d:prop>
            <d:quota-available-bytes>-3</d:quota-available-bytes>
            <d:quota-used-bytes>5731916</d:quota-used-bytes>
         </d:prop>
         <d:status>HTTP/1.1 200 OK</d:status>
      </d:propstat>
   </d:response>
</d:multistatus>
```

--- 

**Not only `data.quota.used` and `d:quota-used-bytes` differ, but also the special, negative value for `d:quota-available-bytes` does not appear on the OCS reply** - ref. https://github.com/owncloud/client/issues/3940: 

> When quota information is requested for such a storage oC will return `-2` for unknown free space and `-3` for unlimited free space (`-1` is for not computed).

cc/ @DeepDiver1975 and @paurakhsharma since I've seen you creating some API tests for OCS' User Provisioning API on https://github.com/owncloud/core/commit/698ad8b33c9bffd1513c85c723071ab207cfda83

**Comment by paurakhsharma** [comment]
Yeah I found the same issue in mine.
What I noticed is if someone shares some files with other user ( in this case `admin`).  The `propfind` command shows the storage used adding that new shared file, which is not the expected behaviour.
But provisioning API `GET` command shows the right value without adding that shared file.

**Comment by phil-davis** [comment]
And we noticed that, in your example, the propfind returns less than the Provisioning API. So I guess you have some other interesting storage combination - maybe some local storage, or federated shares coming in/out, or?

The easiest way to sort this out would be to look in the code and see what the 2 endpoints are doing differently to add up the quota used. (And some day we could make 100 test scenarios that have all sorts of different file system and sharing setups and check that both endpoints return correct and consistent quota values).

**Comment by SamuAlfageme** [comment]
@phil-davis about: 

> So I guess you have some other interesting storage combination 

I think not; used the vanilla`demo.owncloud.com` (deployed via docker) instance in the cURLs.

**Comment by michaelstingl** [comment]
@DeepDiver1975 Are there plans to improve here?

@SamuAlfageme @davigonz What is the urgency? Do we need extra effort to work around this in desktop and mobile clients? How “nasty” is this?

**Comment by SamuAlfageme** [comment]
Relates to recent fixes: https://github.com/owncloud/core/issues/19810 and https://github.com/owncloud/core/pull/30756

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Are there plans to improve here?

current plans that we are working on right now? no
if this is a bug - we shall fix it.

the root cause for this is for sure the great variety of mixture of various apis and implementation.
quota is mostly legazy code.
