### ISSUE TITLE
Calendar cannot be shared to group (10.0.8)

### ISSUE THREAD

**Issue by alejandrofcarrera** [owncloud/core#31402]
The issue #23699 appeared again few days ago, i have time today to attach all the info.

#### Steps to reproduce
* login as fst and share Meetings calendar to Developers group containing user2
* refresh website after did the share, the change is not visible
* login as user2 to review if the share was done
#### Expected behaviour
* Meetings calendar should be visible for user2
#### Actual behaviour
* calendar is not visible for user2, but it is visible if shared directly.
#### Server configuration
* CentOS 7 running latest Docker image of owncloud/server (Tag ID: 2e73a4f3de8c)
* MariaDB latest Docker image (Tag ID: cb0d69450b8e)
* ownCloud version: (see ownCloud admin page) - 10.0.8.5 (stable)
* Calendar version: (see ownCloud apps page) - 1.5.7
* The content of config/config.php:
```
<?php
$CONFIG = array (
  'datadirectory' => '/mnt/data/files',
  'updatechecker' => 'false',
  'upgrade.disable-web' => 'true',
  'skipUpdateCheck' => true,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/owncloud/custom',
      'url' => '/custom',
      'writable' => true,
    ),
  ),
  'dbtype' => 'mysql',
  'dbhost' => 'ownsql:3306',
  'dbname' => 'owncloud',
  'dbuser' => 'root',
  'dbpassword' => '****************',
  'dbtableprefix' => 'oc_',
  'trusted_domains' =>
  array (
    0 => 'localhost',
  ),
  'passwordsalt' => '****************',
  'secret' => '****************',
  'overwrite.cli.url' => '****************',
  'version' => '10.0.8.5',
  'mysql.utf8mb4' => true,
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => '****************',
  'redis' => array('host' => 'redis', 'port' => 6379),
  'filelocking.enabled' => 'true',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'loglevel' => '2',
  'default_language' => 'en',
  'htaccess.RewriteBase' => '/',
  'maintenance' => false,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
);
```
#### Client configuration
* Browser: Chrome
* Operating system: Mac OS 10.13.4
#### Logs
``` **.**.**.*** - - [09/May/2018:10:04:10 +0000] "POST /remote.php/dav/calendars/fst/meetings/ HTTP/1.1" 200 647 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36" ```
#### Owncloud logs
```{"reqId":"WLQsk2rM7p2nbjKzmE4h","level":3,"time":"2018-05-09T10:17:25+00:00","remoteAddr":"**.**.**.***","user":"fst","app":"OCP\\Share","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=deve&perPage=200&itemType=principals","message":"Sharing backend for principals not found"}```
#### Browser logs (payload sent)
```https://**********/remote.php/dav/calendars/fst/meetings/```
```<o:share xmlns:o="http://owncloud.org/ns"><o:set><d:href xmlns:d="DAV:">principal:principals/groups/Developers</d:href><o:summary>Meetings shared by fst</o:summary></o:set></o:share>```

**Comment by DeepDiver1975** [comment]
Reproduced ... strange ..... researching ...

**Comment by DeepDiver1975** [comment]
@phil-davis @davitol @individual-it we shall add this to the acceptance test scenarios

**Comment by DeepDiver1975** [comment]
@alejandrofcarrera looks like the issues is with the uppercase group name :man_facepalming:

**Comment by DeepDiver1975** [comment]
no - groups are in general not working .... :face_with_head_bandage:

**Comment by phil-davis** [comment]
I made issue #31403 earlier today. That could be the place to keep the overview of where we are going with expanding API acceptance test coverage. Then, when someone is working on a particular section, they can make an issue for that section and assign themselves... so we know what is being worked.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 @patrickjahns @phil-davis @davitol do we have somewhere a list of things (with priorities) that need tests?

I'm not aware of any such list - all I can come up with are scenarios as bug reports arise ...
