### ISSUE TITLE
Drag'n'Drop shadow is not on top when navigation is hidden

### ISSUE THREAD

**Issue by butonic** [owncloud/core#31404]
In the files app try dragging a file into a folder.
When the navigation bar is visible you should see a translucent drag shadow with the preview icons and the names of the selected files.
Shrink the window until the navigation bar hides
Try dragging again.
No drop shadow :-(

At least in firefox

**Comment by tomneedham** [comment]
same in chrome  66.0.3359.139 on osx

**Comment by tomneedham** [comment]
Possibly a conflict with the drag out navigation stuff - can we just disable that on desktop?
