### ISSUE TITLE
Sharing with LDAP group still does not work

### ISSUE THREAD

**Issue by flypenguin** [owncloud/core#31419]
Same as #19040 - regression maybe.

### Steps to reproduce
1. use LDAP to sync users
2. share something with an LDAP-based group

### Expected behaviour
group members should see the share

### Actual behaviour
they dont.

### Server configuration
* Ubuntu 16.04
* Docker version 1.12.6, build 78d1802

**Web server:**
N/A

**Database:**
Postgres

**PHP version:**
From Docker image

**ownCloud version:** (see ownCloud admin page)
9.1.0

**Updated from an older ownCloud or fresh install:**
Fresh

**Where did you install ownCloud from:**
Docker hub

**Signing status (ownCloud 9.0 and above):**
?

```
No errors have been found.
```

**The content of config/config.php:**
[see this gist](https://gist.github.com/flypenguin/5bf956c5b99360ce39b821e22624842a)

**List of activated apps:**
[see this gist](https://gist.github.com/flypenguin/5bf956c5b99360ce39b821e22624842a)

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:**
LDAP

#### LDAP configuration (delete this part if not used)
[see this gist](https://gist.github.com/flypenguin/5bf956c5b99360ce39b821e22624842a)

### Client configuration
**Browser:**
Firefox & Chromium

**Operating system:**
Linux

#### Web server error log
N/A

#### ownCloud log (data/owncloud.log)
[see this gist](https://gist.github.com/flypenguin/5bf956c5b99360ce39b821e22624842a)

#### Browser log
N/A

**Comment by 128432b4117** [comment]
> 9.1.0

Most likely the source of your problem. For the 9.1 branch version 9.1.8 was the recent one but the support already ended a few months ago. Current is 10.0.8 which you could try.

**Comment by PVince81** [comment]
please reopen if still happening with OC 10.0.8 and the latest version of the user_ldap app
