### ISSUE TITLE
Preview cleanup uses too much memory on large folder delete

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#31421]
### Steps to reproduce
1. Make a folder with many files underneath
2. Try to delete it

### Expected behaviour
Less 💥  more 🗑 

### Actual behaviour
💥 

```json
{
   "reqId":"1QHjRdEALSkzaYYOH2pf",
   "level":3,
   "time":"2018-05-10T21:13:21+00:00",
 "remoteAddr":"172.19.0.3",
"user":"Tom",
"app":"PHP",
"method":"DELETE",
"url":"\/remote.php\/webdav\/Projects",
"message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 16777224 bytes) at \/var\/www\/owncloud\/lib\/private\/Preview.php#1307"
}
```

Official 10.0.8 docker server.

**Comment by tomneedham** [comment]
Looks like this comes from: 

`OC_Hook::connect('OC_Filesystem', 'delete', 'OC\Preview', 'prepare_delete_files');`

which ultimately uses the method `getAllChildren($view, $path)` to figure out which files it must cleanup. Even the IDE think this is resource hungry:

<img width="664" alt="screen shot 2018-05-10 at 22 51 55" src="https://user-images.githubusercontent.com/660805/39896108-c176e946-54a4-11e8-8fc1-f16d90a05748.png">

**Comment by tomneedham** [comment]
So it looks like it grabs all of the filecache rows under the tree that is being deleted, in the pre_delete hook, then after the delete it cleans them up (since they wont be in the filecache any longer).

**Comment by PVince81** [comment]
does this leave the file cache in a broken state ? or does it just doesn't delete anything ?

need to know for criticality

**Comment by PVince81** [comment]
@cdamken FYI
