### ISSUE TITLE
Update to 10.0.8 was unsuccessful - column "min_value" does not exist

### ISSUE THREAD

**Issue by marekbedy** [owncloud/core#31424]
Hello,

seems there is a problem during the upgrade process to 10.0.8 in the database update, i got this output:

Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_account_terms_id_seq"': SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist LINE 1: SELECT min_value, increment_by FROM "oc_account_terms_id_seq... ^

![image](https://user-images.githubusercontent.com/5310638/39922188-329f9e82-551e-11e8-8510-25b1a15abe74.png)

**Comment by marekbedy** [comment]
I am running Postgresql 10.3.

**Comment by marekbedy** [comment]
I have resolved my issue by changing the file:
lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php

The solution is discussed here:
https://github.com/doctrine/dbal/issues/2868

**Comment by DeepDiver1975** [comment]
duplicate #31334 - oc 10.0.x currently cannot yet support postgres 10 - oc11 (living on the master branch does)
