### ISSUE TITLE
[stable10][master] Session is not validated

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#31455]
Caused by https://github.com/owncloud/core/pull/31343

Does not affect 10.0.8.

Caused because $userSession->validateSession() is no longer called: https://github.com/owncloud/core/pull/31343/files#diff-3a7450cd4a63696420772086fff201aaL139

cc @butonic

**Comment by tomneedham** [comment]
Reproduce:

1. Login
2. Delete your authtoken
3. Refresh the page

Should: logout
Actual: no change - page loads fine

**Comment by phil-davis** [comment]
```
2. Delete your authtoken
```
When I delete the cookie(s) on the browser side, then I get logged out when I do anything in the webUI.
I guess you mean deleting the authtoken server side?

**Comment by tomneedham** [comment]
> I guess you mean deleting the authtoken server side?

Yes - delete the row, or make `last_activity` 0 (making it larger that now()- `session_lifetime` (default 24 hours))

**Comment by tomneedham** [comment]
Once the token is invalid, or not found, your session should be invalid and you should be logged out.

**Comment by phil-davis** [comment]
Assigned myself so I do not forget this. Anyone else also feel free to self-assign ;)

**Comment by PVince81** [comment]
if no one is working on this actively I'll put this to backlog.

once we start thinking about releasing master / OC 11, we'll need to consider all p2 for master only
