### ISSUE TITLE
Syncing .vcf files produces errors

### ISSUE THREAD

**Issue by iwayagdh** [owncloud/core#31457]
### Steps to reproduce
1. syncing a *.vcf file from the client to the server via windows owncloud-client  

### Expected behaviour
the file to be synced without any errors.

### Actual behaviour
The file is synced and also everything else but the client reports an error like:
Server hat "500 Internal Server Error" auf "GET https://"***REMOVED SENSITIVE VALUE***/remote.php/dav/files"***REMOVED SENSITIVE VALUE***/filename.vcf" geantwortet

This lets the client symbol appear red instead of the "all is fine"-green.

It seems to me that owncloud tries to parse the file for contact-issue, but there is no contact- or calendar app installed, so I expect owncloud to just sync the file and let it be.

### Server configuration
**Operating system**: Debian 9

**Web server:** nginx

**Database:** MariaDB

**PHP version:** PHP 7.0

**ownCloud version:** 10.0.7

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar from owncloud.org

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**The content of config/config.php:**
"system": {
        "instanceid": "oc338s0d1i80",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"",
            "***REMOVED SENSITIVE VALUE***""
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***"",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***"",
        "dbtype": "mysql",
        "version": "10.0.7.2",
        "dbname": "***REMOVED SENSITIVE VALUE***"",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": ""***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "php",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "theme": "***REMOVED SENSITIVE VALUE***"",
        "loglevel": 4,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "activity_expire_days": 93,
        "log_rotate_size": "524288000",
        "mail_smtpport": "25",
        "skeletondirectory": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": false,
        "singleuser": false
    }

**List of activated apps:**
Enabled:
  - activity: 2.3.6
  - configreport: 0.1.1
  - dav: 0.3.2
  - encryption: 1.3.1
  - federatedfilesharing: 0.3.1
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - gallery: 16.0.2
  - market: 0.2.4
  - notifications: 0.3.2
  - templateeditor: 0.3
  - updatenotification: 0.2.1
Disabled:
  - comments
  - external
  - federation
  - files_videoplayer
  - firstrunwizard
  - provisioning_api
  - systemtags
  - theme-example
  - user_external

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
***REMOVED SENSITIVE VALUE*** - ***REMOVED SENSITIVE VALUE*** [15/May/2018:15:48:14 +0200] "GET /remote.php/dav/files/***REMOVED SENSITIVE VALUE***/***REMOVED SENSITIVE VALUE***/***REMOVED SENSITIVE VALUE***.vcf HTTP/1.1" 500 880 "-" "Mozilla/5.0 (Windows) mirall/2.4.1 (build 9270)" 0.303 

#### ownCloud log (data/owncloud.log)
{"reqId":"96e0b301-4494-4500-8e87-7a74a4a1b106","level":4,"time":"2018-05-15T15:48:14+02:00","remoteAddr":""***REMOVED SENSITIVE VALUE***","user":""***REMOVED SENSITIVE VALUE***","app":"webdav","method":"GET","url":"\/remote.php\/dav\/files\/"***REMOVED SENSITIVE VALUE***\/"***REMOVED SENSITIVE VALUE***\/"***REMOVED SENSITIVE VALUE***.vcf","message":"Exception: {\"Message\":\"Invalid Mimedir file. Line starting at 8 did not follow iCalendar\\\/vCard conventions\",\"Exception\":\"Sabre\\\\VObject\\\\ParseException\",\"Code\":0,\"Trace\":\"#0 \\\/webhome\\\/"***REMOVED SENSITIVE VALUE***\\\/share\\\/lib\\\/composer\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(234): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readProperty('1227 Carouges')\\n#1 \\\/webhome\\\/"***REMOVED SENSITIVE VALUE***\\\/share\\\/lib\\\/composer\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(181): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('1227 Carouges')\\n#2 \\\/webhome\\\/"***REMOVED SENSITIVE VALUE***\\\/share\\\/lib\\\/composer\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(89): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#3 \\\/webhome\\\/"***REMOVED SENSITIVE VALUE***\\\/share\\\/lib\\\/composer\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(46): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCARD\\\\r\\\\nVE...', 0)\\n#4 \\\/webhome\\\/"***REMOVED SENSITIVE VALUE***\\\/share\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(857): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCARD\\\\r\\\\nVE...')\\n#5 \\\/webhome\\\/"***REMOVED SENSITIVE VALUE***\\\/share\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(782): Sabre\\\\CardDAV\\\\Plugin->convertVCard('BEGIN:VCARD\\\\r\\\\nVE...', 'vcard3')\\n#6 [internal function]: Sabre\\\\CardDAV\\\\Plugin->httpAfterGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/webhome\\\/"***REMOVED SENSITIVE VALUE***\\\/share\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#8 \\\/webhome\\\/"***REMOVED SENSITIVE VALUE***\\\/share\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(491): Sabre\\\\Event\\\\EventEmitter->emit('afterMethod:GET', Array)\\n#9 \\\/webhome\\\/"***REMOVED SENSITIVE VALUE***\\\/share\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/webhome\\\/"***REMOVED SENSITIVE VALUE***\\\/share\\\/apps\\\/dav\\\/lib\\\/Server.php(263): Sabre\\\\DAV\\\\Server->exec()\\n#11 \\\/webhome\\\/"***REMOVED SENSITIVE VALUE***\\\/share\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#12 \\\/webhome\\\/"***REMOVED SENSITIVE VALUE***\\\/share\\\/remote.php(165): require_once('\\\/webhome\\\/"***REMOVED SENSITIVE VALUE***')\\n#13 {main}\",\"File\":\"\\\/webhome\\\/"***REMOVED SENSITIVE VALUE***\\\/share\\\/lib\\\/composer\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":434,\"User\":\""***REMOVED SENSITIVE VALUE***\"}"}

**Comment by DeepDiver1975** [comment]
Please upgrade to 10.0.8 - this was fixed in that release
