### ISSUE TITLE
WebDAV path not user-friendly for LDAP users

### ISSUE THREAD

**Issue by AshJRI** [owncloud/core#31461]
### Background
Your boss decides, that it is much more secure to has an ownCloud instead of uploading all (maybe also confidential) data to apple, google or microsoft. He instructs your BOFH to install a ownCloud for the company. The BOFH doesn't have the time to read a long documentation and installs an ownCloud with (almost) default settings. After that he activates automatic updates and configure the LDAP authentication, because your boss wants to login with his normal user name and password from AD (Active Directory). Now your boss is happy, while the BOFH leans back and never touch the cloud again.
Some day, your boss comes to you and instructs you to update the proprietary company management software (CMS) to load and save documents to the company cloud.

Sounds kind of familiar, doesn't it?

### The Problem(s)
1. Your colleagues and your boss use the domain user credentials to login to the cloud (the LDAP users)
2. The WebDAV path of ownCloud contains a user name ("/remote.hpp/dav/files/USERNAME"). BUT this USERNAME needs to be the UUID, because the BOFH didn't activate the UUID detection override.
3. The BOFH rejects all your change requests, because the cloud works and he never touch a working system.
4. Your colleagues and your boss don't know any UUID.
5. The BOFH would kill you, if you add a required field to the CMS and let all users input the UUID in addition to the user name and password.

### The workaround
You read all the documentation the BOFH should have read ... for new and old ownCloud versions.
And you decide to try the obsolete WebDAV path for ownCloud 8 and older: "remote.php/webdav"
And it works! **... But for how long?**

### The problem with the workaround
You have a hugh problem, if somebody in your community decides in the (near) future to remove the support of the obsolete WebDAV path,

# My Question:
Obviously, there is an internal mapping of LDAP user names and UUIDs implemented somewhere in ownCloud. Otherwise, it won't be possible to login with the normal AD user name.

Why you didn't add this mapping to the WebDAV module and support real AD user names in the WebDAV path?

**Comment by DeepDiver1975** [comment]
> Why you didn't add this mapping to the WebDAV module and support real AD user names in the WebDAV path?

there is no such mapping. the credentials are sent to ldap and ldap is logging you in as per configuration. This could mean to check multiple attributes of a user to find out which user this is (samaccount name, email addresses and what ever there is) after sucessfull login ldap returns us one unique(hopefully) identifier - which in best case is the uuid of the user in ldap.

remote.php/webdav will continue to live for quite some time - you can savly use it - as long as you are not interested in any new features ...

**Comment by PVince81** [comment]
The Webdav path can be copied directly from the web UI, so no need to understand whatever it contains. Not sure why users would need to know what a UUID is. They should just copy paste the link and use it when mounting/accessing Webdav.

**Comment by AshJRI** [comment]
Thanks for your answers.

The WebDAV path in the web UI is somewhat hidden. If you want me to explain my boss and all colleagues where to find the WebDAV path on the web UI, I'd rather use the old remote.php/webdav path as long as possible and hope that I got another job until then ;)

I'm not familiar with LDAP. But you say you send the credentials of the request to LDAP and if the user is valid, LDAP tells you the UUID of the user (which you use as a kind of unique "ownCloud user identifier").

Now lets say that the requested webdav path is: remote.php/dav/files/user1
And the credentials sent with this request contains the same user name (user1).
And now lets say that LDAP tells you that user1 with the given password is valid and the UUID you get  from LDAP is the same that you have in the ownCloud database. You still cannot accept this webdav path?

And even if there are strong reasons to require the UUID in the webdav path, from other cloud services I know concepts to ask a server for a user specific path.
So lets say I send a first request to: remote.php/dav/auth (or another common path) with the user credentials. You check the credentials and (if it is a valid user) you return the "ownCloud user identifier", which is the UUID for LDAP users or the user name for local users.
Would that be a possible concept?

**Comment by PVince81** [comment]
> So lets say I send a first request to: remote.php/dav/auth (or another common path) with the user credentials.

This might not work with all Webdav clients as it would require a redirect of some sorts.

It seems that this is mostly a usability issue, where we should make the Webdav path easier to find for regular users.

@pmaier1
