### ISSUE TITLE
File cache repair step detection should not run on every upgrade

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#31464]
Because it can take a long time even just for the detection. If it has run before it should not run again. 

We can add a version check, if start upgrade version >= 10.0.4 (I think?) then we dont need to run the repair step detection during the upgrade.

Should be in 10.0.9 because this can significantly increase upgrade time.

**Comment by PVince81** [comment]
can't be in "development" without assignment. moving to "planned" for assignment

**Comment by PVince81** [comment]
Estimate: 0.25md

Add a flag in the DB like we do for other repair steps to find out whether it ran already.

@tomneedham if there is no objection ^

**Comment by sharidas** [comment]
Created PR: https://github.com/owncloud/core/pull/31795 ( master branch )
