### ISSUE TITLE
Missing symfony event and share id for public share link access

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#31462]
https://github.com/owncloud/core/blob/6b36c56180eee3ce796b1a69709431f1d38da627/apps/files_sharing/lib/Controllers/ShareController.php#L218

And this is also missing the share ID which is very helpful when listening to this event.

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/31467

**Comment by PVince81** [comment]
done
