### ISSUE TITLE
WebUpdater: Show a warning of apps that could prevent an upgrade

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#31476]
If one clicks on the Update button on the webUI there should be an check for apps that later need to be disabled in order to complete the upgrade.

Otherwise the less experienced users are left with error messages and confusion that could lead in to frustration and changing the product.

## Actual Behavior

User clicks on upgrade
Maintenance mode is kept active
user disables maintenance mode by editing config php
User upgrades again on webUI
has to disable some apps
update runs finally through

## Expected Behavior

User clicks on upgrade
User gets a warning with the link to the apps section
warning something like "Warning, please disable those apps in order to perform this upgrade, after the upgrade you can enable them again"
The second part of this sentence is important. If I have a calendar app and disable the calendar app. Are my entries still there?
@VicDeo

**Comment by RichardEb** [comment]
I agree with him and support this request. There should be also an option to continue the upgrade Without manually disabling maintenance mode.

Or at least there should be a meaningfull message explaining what to do.

**Comment by PVince81** [comment]
enhancement for the updater component

@pmaier1

**Comment by RichardEb** [comment]
Why do you close this issue? It annoys me every time. I'll switch to nextcloud. Much better software.

**Comment by voroyam** [comment]
Because there is no fix in sight and if your mind is made up just because of one "enhancement" - there is little we can do about it.

**Comment by RichardEb** [comment]
enhancement?

EVERY time I try to update the owncloud installation it fails because of a very stupid reason. (Mostly because of plugins) I have to spent at least ONE hour of my time for EVERY SMALL update.

**Comment by voroyam** [comment]
Why don't you just use the manual update?

**Comment by RichardEb** [comment]
I'm using owncloud on a Webserver and I don't want to waste my time manually overwriting files and modifying the database.

**Comment by voroyam** [comment]
The only thing you have to do is execute "occ upgrade" and if you have custom apps then disable those by copy pasting the suggested commands on your screen in to the terminal. Effort of 2 minutes for a private cloud.

You can always use ownCloud docker container- where you don't have to update ownCloud, as you just throw away the old container and get the new one, while your files and database remain.

**Comment by RichardEb** [comment]
How am I supposed to do this on a webspace? Hack the hoster?

**Comment by voroyam** [comment]
Get a server with shell access :)

**Comment by RichardEb** [comment]
You pay?
