### ISSUE TITLE
Sharing settings exclude groups calls appconfig.php ajax without key

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#31474]
### Steps to reproduce
1. Got to admin settings as admin, navigate to sharing settings
2. Type in a group id in to the search box
3. Click on the words 'Searching...'

### Expected behaviour
Nothing

### Actual behaviour
![screen shot 2018-05-18 at 14 14 04](https://user-images.githubusercontent.com/660805/40234097-c19fb70c-5aa5-11e8-8f99-a8e834f832fb.png)

![screen shot 2018-05-18 at 14 14 21](https://user-images.githubusercontent.com/660805/40234102-c6790ae4-5aa5-11e8-8b35-2e6c75ef7a3d.png)

HEAD @ 6b36c56180eee3ce796b1a69709431f1d38da627

**Comment by DeepDiver1975** [comment]
oh - this setting panel uses the endpoint of the user management .... we need to change this ....

**Comment by PVince81** [comment]
so is this a regression in the user management app on master ?

**Comment by PVince81** [comment]
I'm putting this to backlog
