### ISSUE TITLE
Capability "Enforce Password" with incorrect value 

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#31492]
The capability `Enforce password` was splitted up in three different capabilities in 10.0.8

<img width="434" alt="screen shot 2018-05-22 at 10 24 22" src="https://user-images.githubusercontent.com/14894746/40350514-55648150-5daa-11e8-8a22-b4f25bbae144.png">

But the capabilities retrieved to clients through `/ocs/v1.php/cloud/capabilities` in json returns always

> "password": {
              "enforced": false
     }, 

Therefore:

- The client is being retrieved only one capability, when there are three different ones supported
- The value in such capability is always `false` regardless the checkboxes selected in admin bashboard

Core: `{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.0.8.5","versionstring":"10.0.8","edition":"Enterprise","productname":"ownCloud"}`

**Comment by phil-davis** [comment]
Yes, that is all missing. I was just running the API acceptance tests for capabilities, so I will have a look...

**Comment by jvillafanez** [comment]
@phil-davis I guess we have duplicated the efforts.... Check my PR, make the adjusments in yours and close mine.

**Comment by phil-davis** [comment]
Not much duplicated effort - the actual code changes are 5 minutes. And we each worked on tests in a different part of the test pyramid. It will merge nicely.

**Comment by phil-davis** [comment]
@jesmrec core PR has been merged and backported some time ago. It should be in a core release these days.
Close?

**Comment by jesmrec** [comment]
Close
