### ISSUE TITLE
loginWithPassword emits wrong symphony events

### ISSUE THREAD

**Issue by butonic** [owncloud/core#31509]
https://github.com/owncloud/core/blob/5f0af496626b957aff38730b5771ec0a33effe31/lib/private/User/Session.php#L490-L516

1. The `user.beforelogin` event has a `uid` that contains the login string (might be an email or a username). Key should be called `login`
2. The `user.afterlogin` event has a `uid` that still contains the login. Should be the userid of the logged in user which wes resolved with checkPassword.
3. `&` is unnecessary in`$this->emittingCall(function () use (&$uid, &$password)`

**Comment by butonic** [comment]
cc @PVince81 @sharidas

**Comment by sharidas** [comment]
Created PR: https://github.com/owncloud/core/pull/31515.

**Comment by sharidas** [comment]
- [x] https://github.com/owncloud/core/pull/31515 merged to master branch
- [x] https://github.com/owncloud/core/pull/31605 merged to stable10

**Comment by sharidas** [comment]
Closing this issue as the changes got merged to stable10 branch and master branch as mentioned in https://github.com/owncloud/core/issues/31509#issuecomment-394603919
