### ISSUE TITLE
Lowercase on collaborative tags

### ISSUE THREAD

**Issue by georgeoftown** [owncloud/core#31508]
### Steps to reproduce
1. Create new folder or file
2. Add new Collaborative tag Text
3. Add new Collavorative tag tExt

### Expected behaviour
Each label should appear as it was written

### Actual behaviour
All the labels are converted to lowercase so they cannot be differentiated, you can see in the attached photo [example capture](https://drive.upm.es/index.php/s/hG4NUebhLeDGnjM)

### Server configuration
**Operating system**:
Debian 9.4
**Web server:**
Apache/2.4.25
**Database:**
mysql  Ver 15.1 Distrib 10.1.26-MariaDB
**PHP version:**
PHP 7.0.27
**ownCloud version:** (see ownCloud admin page)
10.0.8
**Updated from an older ownCloud or fresh install:**
4.5
**Where did you install ownCloud from:**
Repo
**Signing status (ownCloud 9.0 and above):**
Disabled

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/13168 (Ability to share by tag), https://github.com/owncloud/core/issues/24443 (OCR to Tags), https://github.com/owncloud/core/issues/11384 (Document Tags.), https://github.com/owncloud/core/issues/5268 (Tagging files or folders), and https://github.com/owncloud/core/issues/8467 (Error E-Tag).

**Comment by PVince81** [comment]
From what I see the tag is still stored with proper casing in the database.

The issue seems to be how the field displays the tags.
![image](https://user-images.githubusercontent.com/277525/41091338-9631bd94-6a46-11e8-81cd-a22b498ba67e.png)

**Comment by husar** [comment]
Hello, i would like to work on this issue if it is still open. Can you give me more information about this issue?
