### ISSUE TITLE
Same folder showing up in two places

### ISSUE THREAD

**Issue by robnagler** [owncloud/core#31503]
### Steps to reproduce

I have no idea how to reproduce this. We ran the scan repair, but still an issue.

We recently migrated from 9.x to 10.x. We had this issue with one user (me) before the migration so we ignored it. However, it now started showing up for another user.

### Expected behaviour

Folder should appear in only one place.

### Actual behaviour

Folders are showing up in the root and as subfolders for some a few users. These folders are pointed to identical files. It seems the database is corrupt.

### Server configuration
**Operating system**:

* CentOS Linux release 7.4.1708 (Core)
* Linux fnl2b.bivio.biz 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**

* proxy: nginx version: nginx/1.12.2
* docker owncloud/server:10.0.7
```json
             "Labels": {
                "maintainer": "ownCloud DevOps <devops@owncloud.com>",
                "org.label-schema.build-date": "2018-04-13T13:27:41Z",
                "org.label-schema.name": "ownCloud Server",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-ref": "32dc2d6",
                "org.label-schema.vcs-url": "https://github.com/owncloud-docker/base.git",
                "org.label-schema.vendor": "ownCloud GmbH",
                "org.label-schema.version": "latest"
            }
```

**Database:**

* docker mariadb:10.2.14 
* MARIADB_VERSION=10.2.14+maria~jessie"
* 

**PHP version:**

* inside docker container

**ownCloud version:** (see ownCloud admin page)

10.0.7.2

**Updated from an older ownCloud or fresh install:**

Updated from 9.1.6-fpm

**Where did you install ownCloud from:**

docker

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**The content of config/config.php:**

The config contains way too much information to post and it is sensitive (numbers of users) so I'd rather not post publicly. Please ask for specifics.

**List of activated apps:**

Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.3
  - notifications: 0.3.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.2
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - theme-example
  - user_external
  - user_ldap

**Are you using external storage, if yes which one:** 

local

**Are you using encryption:**

no

**Are you using an external user-backend, if yes which one:** 

no

### Client configuration

Shows up in all clients.

**Operating system:**

#### Web server error log

N/A

#### ownCloud log (data/owncloud.log)

N/A

#### Browser log

N/A

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/8907 (Group folders; folders for two or more people), https://github.com/owncloud/core/issues/24997 (Shared from you view shows wrong folder names), https://github.com/owncloud/core/issues/457 (renaming folders), https://github.com/owncloud/core/issues/2455 (show number of files in a folder), and https://github.com/owncloud/core/issues/3348 (folder permissons).

**Comment by PVince81** [comment]
Normally I'd expect `occ files:scan --repair` to repair these, but you said you ran that already.

Need to look at `select * from oc_filecache where path like '%the_broken_path%'` for the redundant entry and also look at all the parent relationships and see if something is broken there. A filecache entry's "parent" field points to the "fileid" of its parent.

**Comment by robnagler** [comment]
Thanks @PVince81 for the quick response.

No duplicates are showing up with that query, just one entry for "files/Foo/bar" and another "files_versions/Foo/bar". Nothing matching "bar" at the top level.

I figured out that the root is "40", and the top level directories for `select * from oc_filecache where parent = 40;` are correct and match the file system.

The "bar" folder doesn't show up at the top level for everybody, just a couple of people.

There's another path showing up at the top level for me, let's call it XYZ. When poking around, XYZ isn't showing up at all in the oc_filecache, that is, `select * from oc_filecache where path like '%XYZ%'` returns nothing. Where is the data for the top level coming from? 

Is there a unicode issue with searching? XYZ is a normal English name so I wouldn't think so, just not sure how it would be showing up if that phrase does not appear in oc_filecache's path (or name) column.

**Comment by PVince81** [comment]
maybe these are received shares, try `select * from oc_share where file_target like '%XYZ%'`

**Comment by robnagler** [comment]
Thanks! That appears to be it. I don't know ownCloud well.

What I suppose happened is that a file was /XYZ and then got moved to /SomeDir/XYZ, but the share didn't update? Is that a bug or a feature?

**Comment by PVince81** [comment]
could be a bug, but without clear steps to reproduce it it will be impossible to analyse.

maybe some PHP timeout happened and the DB entries didn't get all updated

**Comment by robnagler** [comment]
It's not a bug. It was a problem with received shares, which I didn't understand properly. Thanks!
