### ISSUE TITLE
occ decrypt-all aborted without error message

### ISSUE THREAD

**Issue by technikamateur** [owncloud/core#31501]
Hey guys,
I'm trying to decrypt my files with the _occ decrypt-all_ command. But if I do so, I get the following output:
```
Disable server side encryption... done.

You are about to start to decrypt all files stored in Norman's account.

It will depend on the encryption module and your setup if this is possible.
Depending on the number and size of your files this can take some time
Please make sure that no user access his files during this process!

Enable server side encryption... done.
aborted 
```
What does this mean? Why is there no error message?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/28840 (-Error-), https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/20969 (Admin account creation failed without any error/info messages), https://github.com/owncloud/core/issues/13087 (Error messages), and https://github.com/owncloud/core/issues/19327 (Running occ encryption:decrypt-all without a username doesn't stop and warn the user.).

**Comment by PVince81** [comment]
please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

**Comment by technikamateur** [comment]
Okay. Here are some informations I can provide:
webserver: apache
PHP version: 7.1.11
MySQL version: 5.6.38
Owncloud version: 9.0 (existing installation since 8.0)
channel: stable
encryption enabled, no external storage.
Log does not show any errors.

**Comment by PVince81** [comment]
ownCloud 9.0 is EOL since a long time, see: https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

I suggest you upgrade to 10.0.8 and try and decrypt there. Many bugfixes exist for encryption in recent versions.

**Comment by PVince81** [comment]
Please reopen if the issue persists on 10.0.8.

Note that you don't need to upgrade through every major version, you can upgrade directly to 10.0.8.
