### ISSUE TITLE
Ability to skip max-version check in core for testing beta apps

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31518]
### Use case
To make sure that an app will work correctly OC version X+1, QA needs to test it while the app is still in beta phase and not yet market as compatible with the latest X+1.

### Problem
When testing a beta app or PR that still has max-version=X instead of max-version X+1, the X+1 version of OC will refuse to enable the app.
So a QA person would need to manually hack info.xml to increase the version temporarily just to make tests run.
In a CI environment this hack would need to be automated.

### Proposed solution
Introduce a new environment variable `CI_IGNORE_APP_VERSION_REQUIREMENTS=1` which will skip any min/max version checks when enabling or installing apps.

### Open questions
- [ ] should this also apply to the market app or only enabling an already installed app ?

@owncloud/qa

**Comment by patrickjahns** [comment]
The other idea was to introduce a (hidden) config option. 

There are pro's con's to both approaches 
Environment:
- needs more documentation / clarification for people to be aware of ("why is this working in ci but not here" 

Config option
- more prone to abuse by people who see it

Regarding the naming" `CI_IGNORE_APP_VERSION_REQUIREMENTS` - I would drop `CI` at least - as this is not only relevant for CI, but also for setting up test environments

Generally speaking, a major use-case is, when already setting up testing for *master* branches - which would have a version number higher than anything we currently release. 
We want to know early on if that app will work with *master* or the *next release* - but not bump the max/min version requirements yet

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/pull/29824 (skip tests tagged with the current oC version), https://github.com/owncloud/core/pull/30437 (skip moving test on Firefox), and https://github.com/owncloud/core/issues/4146 (Fix skipped encryption app test).

**Comment by jvillafanez** [comment]
> more prone to abuse by people who see it

We have to assume that people WILL abuse it.
For this particular case, I think it's quite harmless on our side as it won't enable anything new or something that shouldn't be accessible. It's more like a "do it on your own risk". Assuming that people will use this option, I'd like to easily know if this option is active or not, so when a report comes we can double check the app versions.

**Comment by PVince81** [comment]
To reduce the probability of abuse I suggest to use an env variable which is more tricky to setup for a server + CLI, while setting a config.php option is too easy.

**Comment by patrickjahns** [comment]
`MYSECRETVAR=true php occ` - not that hard though ;-)

**Comment by PVince81** [comment]
@DeepDiver1975 any objection to using this approach for beta testing ?

**Comment by PVince81** [comment]
Alternative that we're going to try:
- if OC channel is either "git" or "daily", we skip max-version check in core

Doesn't require adding or removing flags in various apps.
