### ISSUE TITLE
PHP 7.2.5 ini_set(): A session is active

### ISSUE THREAD

**Issue by marmaro** [owncloud/core#31524]
Everything seems working fine but if I check the owncloud log I see a lot of this errors:
"message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/htdocs\/owncloud\/lib\/base.php#596"}

I recently upgraded PHP from version 5.5 to 7.2.5.
I already checked openssl module, it is installed and configured.

### Steps to reproduce
1. check the owncloud log file
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
Opensuse 42.3

**Web server:**
Apache 2.4.23

**Database:**
MariaDB

**PHP version:**
7.2.5

**ownCloud version:** (see ownCloud admin page)
10.0.8.5
**Updated from an older ownCloud or fresh install:**
Updated
**Where did you install ownCloud from:**
Manual
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.

No errors have been found.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
{"reqId":"700f019b-b6db-4c93-8f03-0c2f6ad62563","level":3,"time":"2018-05-24T12:24:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/marma\/","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/htdocs\/owncloud\/lib\/base.php#596"}
{"reqId":"q3fAF87ySupiF9aQaY29","level":3,"time":"2018-05-24T12:24:44+00:00","remoteAddr":"","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/htdocs\/owncloud\/lib\/base.php#596"}
{"reqId":"78f27b57-ddd1-4f30-b695-b0d5259b2d69","level":3,"time":"2018-05-24T12:24:48+00:00","remoteAddr":"","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/marma\/","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/htdocs\/owncloud\/lib\/base.php#596"}
{"reqId":"U6Cs1ADV8C0jmS4rB6gy","level":3,"time":"2018-05-24T12:24:59+00:00","remoteAddr":"","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/index.php\/settings\/integrity\/failed","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/htdocs\/owncloud\/lib\/base.php#596"}
{"reqId":"88c28a7b-f12e-4477-9ff2-92aa6ae91f81","level":3,"time":"2018-05-24T12:25:16+00:00","remoteAddr":"","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/htdocs\/owncloud\/lib\/base.php#596"}
{"reqId":"1bbe77be-3c3c-4131-9d45-5364b910a10b","level":3,"time":"2018-05-24T12:25:18+00:00","remoteAddr":"","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/marma\/","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/htdocs\/owncloud\/lib\/base.php#596"}
{"reqId":"f3ce1561-0936-484f-8adc-22f85c1937ea","level":3,"time":"2018-05-24T12:25:48+00:00","remoteAddr":"","user":"--","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/marma\/","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/htdocs\/owncloud\/lib\/base.php#596"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/23220 (Owncloud 8.2.2, 9.0.0 Login problem on php 7 with Memcache session storage), https://github.com/owncloud/core/issues/2175 (v4.5.7 PHP errors), https://github.com/owncloud/core/issues/1840 (v4.5.7 PHP errors), https://github.com/owncloud/core/issues/13261 (PHP session files), and https://github.com/owncloud/core/issues/18791 (Stable 7 broken on php 5.3).

**Comment by pilere** [comment]
Hi,
this doesn't seem to impact the production running, but it increase A LOT the log file that fullfill the partition ... and thus generate downtime ... 
please help

**Comment by whiteonion** [comment]
Hi, I am experiencing a simmilar problem with ownCloud clinet - constantly on Waiting, and doing PROPFIND of QUrl xxx . It is really slow, and my server logs theese 

045","level":3,"time":"2018-07-07T08:37:57+00:00","remoteAddr":"xxxxxxxxxxxxxxxxxxx","user":"--","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/files\/xxxxxxxxxxxxxxxxxxx\/","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/home\/admin\/web\/xxxxxxxxxxxxxxxxxxx\/public_html\/lib\/base.php#596"}

I am using CentOS7 minimal + VestaCP + PHP 7 + MariaDB10 + OC10
Just OC on the machine.


so, my problem is that it works VERY slow, with big files (it's a fresh install and I am tweaking it for the last couple days, fixed a lot of errors, but this persists). Right now I am uploading a set of around 30 files varying size form 100, 200, 300 to 1500, 1700 megs. So big files.

OC generally works like the wind with most files, but it seems stuck now on theese 1GB and larger files.

**Comment by whiteonion** [comment]
@pilere you can set `"loglevel" => "2",` in the OC config file, that will stop it from loging theese issues.

[https://doc.owncloud.org/server/latest/admin_manual/configuration/server/logging_configuration.html]

**Comment by ajuntament** [comment]
In my case, this solution has not worked:
![imagen](https://user-images.githubusercontent.com/5476171/43894016-286a2910-9bd1-11e8-8140-5f74f21896db.png)
It works with the value: "loglevel" => "4",

Centos 7 + Apache 2.4.6 + Owncloud 10.0.9.5

**Comment by miqrogroove** [comment]
I'm seeing the same problem with a brand new Ubuntu server.

**Comment by DeepDiver1975** [comment]
Feel free to Test the linked pull request above
