### ISSUE TITLE
Session login() emits wrong symphony events

### ISSUE THREAD

**Issue by butonic** [owncloud/core#31520]
https://github.com/owncloud/core/blob/5f0af496626b957aff38730b5771ec0a33effe31/lib/private/User/Session.php#L849-L876

1. The `\OC\User preLogin` hook uses the `$user` Object but it should contain the uid (actually it should contain the login, as in `Session loginWithPassword`) but we have no access to it here, so stick with the uid? the existing code expects the hooks to use these parameters
https://github.com/owncloud/core/blob/5f0af496626b957aff38730b5771ec0a33effe31/lib/private/User/Session.php#L77-L79

2. The `user.beforelogin` event has a `uid` that contains the user object. Value should be `$user->getUID()`. Also add an entry `'user' => $user`
3. The `user.afterlogin` event has a `uid` that still contains the user object. Should be the userid of the logged in user which can be obtained from the `$user` object. Again, add an entry `'user' => $user`
4. & is unnecessary in `return $this->emittingCall(function () use (&$user, &$password) {`

Related: https://github.com/owncloud/core/issues/31509

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/31509 (loginWithPassword emits wrong symphony events), https://github.com/owncloud/core/issues/31465 (Missing symfony event for failed login attempt), https://github.com/owncloud/core/issues/7356 (Redirect after login breaks when wrong password entered after session timeout), https://github.com/owncloud/core/issues/24697 (Can't login LDAP users. 'Wrong password' returned), and https://github.com/owncloud/core/issues/12739 ([Login] Not possible to login after filling wrong the credentials twice).
