### ISSUE TITLE
Attempt to create a read-write public share of a file

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#31538]
### Steps to reproduce
1. Run acceptance test ``tests/acceptance/features/apiSharing-v1/createShare.feature:75``
2. It passes

### Expected behaviour
Maybe an attempt to make a public share of a file with read and write permissions should fail with some ``4nn`` HTTP status?

### Actual behaviour
The test scenario makes a public share of file ``welcome.txt`` with all permissions (read, write, reshare...). The public share creation succeeds  and the public share actually just has read permission.

### Server configuration
drone CI or local dev environment

See PR #31495 where the test scenario was added.

**Comment by phil-davis** [comment]
@PVince81 @patrickjahns or anybody, does the current behavior seem OK?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/3949 (File sharing), https://github.com/owncloud/core/issues/3273 (Sharing a single file), https://github.com/owncloud/core/issues/3465 (Sharing files), https://github.com/owncloud/core/issues/5417 (Ghosted shared file), and https://github.com/owncloud/core/issues/20839 (Sharing a file allows you to set create permissions).

**Comment by PVince81** [comment]
Considering that we don't support creating public links for files with read-write permissions as we haven't tested the implications in public link page, we should likely block it on API level for now.
