### ISSUE TITLE
"SQLSTATE[HY000]: General error: 10 disk I/O error" after upgrading to 10.0.8

### ISSUE THREAD

**Issue by derjensen** [owncloud/core#31548]
Hi,

sorry - here comes an Owncloud-Noob :/ 

### Expected behaviour
Updating from 10.0.4.4 to next version 10.0.8

### Actual behaviour
I wanted to update my owncloud from 10.0.4 to 10.0.8. Copying the new files (using automatic upgrade in the admin panel) was unobtrusively. Unfortunetaly the final click ("Updating to 10.0.8"), after browsing in the root, fails. 

ERROR MESSAGE:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'DROP INDEX account_id_index': SQLSTATE[HY000]: General error: 10 disk I/O error Please report this problem to the community. 

### Server configuration
Webhosting/Shared Server
Apache
MySQL-Client-Version: 5.5.60
PHP 5.6

**ownCloud version:** 
10.0.8 (from 10.0.4.4 by using automatic upgrade function)

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc0themhnbpp',
  'passwordsalt' => '********************************',
  'secret' => '**************************************',
  'trusted_domains' => 
  array (
    0 => 'cloud.*****************.com',
  ),
  'datadirectory' => '/is/*********************************/www/owncloud/data',
  'overwrite.cli.url' => 'http://cloud.***********.com',
  'dbtype' => 'sqlite3',
  'version' => '10.0.4.4',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'updater.secret' => '****************************************',
);

Thank you!

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @kdslkdsaldsal.

Possibly related issues are https://github.com/owncloud/core/issues/14714 (Errors after upgrade to 8), https://github.com/owncloud/core/issues/14139 (Unexpected error: 0 error after successfull upgrade to 8.0), https://github.com/owncloud/core/issues/29143 (failed upgrade to 8.0.16), https://github.com/owncloud/core/issues/15016 (Error Upgrading to OC 8.0), and https://github.com/owncloud/core/issues/20125 (Error Messages after upgrade from OC to 8.2.0).

**Comment by PVince81** [comment]
Please contact your hoster, it looks like the filesystem might have problems.

This issue unlikely to be related to ownCloud but rather related to environment issues.
