### ISSUE TITLE
[Feature Request] occ command to manage user app passcodes

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#31540]
This Feature Request is about to extend the ./occ user command to manage app passcodes

``user:app-passcode <user> --list``
``user:app-passcode <user> --create <app-name>``
``user:app-passcode <user> --delete <app-name>``

Intention:
Automation for rollouts especially in enterprises.

@patrickjahns @PVince81 @pmaier1 @hodyroff

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/8569 (Feature requests), https://github.com/owncloud/core/issues/12530 (Feature Request), https://github.com/owncloud/core/issues/22635 (Feature Request: OCC Change Password Using Hash), https://github.com/owncloud/core/issues/29960 ([Feature Request] extend ./occ user to list logged on users), and https://github.com/owncloud/core/issues/14252 (feature request : Occ need new commands).

**Comment by hodyroff** [comment]
Hm, oAuth2 with proper management for admins is not sufficient? Why? There might be a good reason, please let me know.

**Comment by PVince81** [comment]
or would it be enough to revoke all the tokens of the user in case the account is compromised ?

**Comment by mmattel** [comment]
maybe only a device got lost and you want to revoke access to that particular device only.
revoke all is possible but maybe too much

**Comment by pmaier1** [comment]
Actually OAuth2 is the way to go to provide such functionality in a proper, automated and standardized way. I'm aware that we need some enhancements to the OAuth2 implementation like an admin management interface (including occ commands) and also more granular options in the UI (e.g. ability to distinguish between particular clients). Considering the benefits of OAuth2 I'm very hesitant to invest in app passwords.

**Comment by patrickjahns** [comment]
@pmaier1 
that is very short sighted - consider that webdav clients do not necessarily speak oauth. 
having `app-passwords` means to be able to use ownCloud as an storage integration that can be talked to by any webdav client without exposing your users password

**Comment by pmaier1** [comment]
> consider that webdav clients do not necessarily speak oauth.

I'm fully aware.

> that is very short sighted

I consider our focus to be on the native clients which have OAuth2 support and would like to cover the mentioned requirements there first.
