### ISSUE TITLE
Problems with accents and symbols when server is Linux and client is Mac

### ISSUE THREAD

**Issue by izaera** [owncloud/core#31544]
### Steps to reproduce
1. Create a file containing an accent in a Mac client. For example: "Sólo.txt"
2. Let it sync
3. Empty database
4. Run `occ files:scan --all`

### Expected behaviour
The "Sólo.txt" file should appear again.

### Actual behaviour
The "Sólo.txt" file is not scanned because `occ` fails to `stat()` it. Investigating the issue I've found that the problem is that Macs prefer representing accents in file names by using a combining accent unicode character (that is: `o` + `´`), while linux prefers the o with accent unicode character (that is: `ó`).

So, when `occ` is scanning the files it tries to `stat()` the file `Sólo.txt` with `ó`, but it has been written as `o` + `´` and, thus, the scan fails.

### Server configuration
Linux Fedora 25

**Web server:**
Nginx

**Database:**
MariaDB

**PHP version:**
7.0.25

**ownCloud version:** (see ownCloud admin page)
9.1.5

**Updated from an older ownCloud or fresh install:**
Fresh

**Where did you install ownCloud from:**
Fedora repo

**The content of config/config.php:**
```
{
    "system": {
        "log_type": "syslog",
        "datadirectory": "\/var\/lib\/owncloud\/data",
        "updatechecker": false,
        "check_for_working_htaccess": false,
        "asset-pipeline.enabled": false,
        "assetdirectory": "\/var\/lib\/owncloud",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "apps_paths": [
            {
                "path": "\/usr\/share\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/owncloud\/apps",
                "url": "\/apps-appstore",
                "writable": true
            }
        ],
        "instanceid": "oc0gev6rk2ol",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "zeus"
        ],
        "overwrite.cli.url": "http:\/\/zeus\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.5.2",
        "dbname": "ownclouddb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}
```

**List of activated apps:**
```
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by izaera** [comment]
Here's some more info regarding the character representation on Mac vs Linux: https://nedbatchelder.com/blog/201106/filenames_with_accents.html

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/7944 (Linux client always syncing), https://github.com/owncloud/core/issues/846 ( Syncing problems on Mac), https://github.com/owncloud/core/issues/20634 (Problem with sync client.), https://github.com/owncloud/core/issues/2981 (Linux Ubuntu 12.10 client crashes), and https://github.com/owncloud/core/issues/11005 (OwnCloud MAC Server Unicode-problem).

**Comment by patrickjahns** [comment]
ownCloud 9.1.x is end-of-life - does this problem also occur for you on ownCloud 10?

**Comment by izaera** [comment]
Hi there. I'm not sure if I will be able to test it with owncloud 10, because I would need to install it from outside of Fedora package manager and it may take quite a long time :-(.

Regarding the client, I'm using `Version 2.4.1 (build 9367)` with `Git Revision cd60c2 Mar 1 2018, 16:37:22 compiled using Qt 5.6.2, OpenSSL 1.0.2n 7 Dec 2017`

I detected the error by running `strace` but haven't seen the real PHP code because I don't have expierence with PHP. My hypothesis is that someone (don't know if owncloud, PHP, or even Linux system calls) does some conversion from the "Mac name in unicode" to the "Canonical linux name in unicode" and then tries to open the file and it fails.

In pseudocode, something like this:

```
files = list_all_files() // files contains file names in Mac format 
for(file in files) {
  file = canonicalize_file_name(file) // file name is now in Linux format
  fd = open(file) // this fails because the file is really stored in Mac format in FS
}
```

**Comment by PVince81** [comment]
Can you confirm that you did not store the file manually inside the "data" folder and really had it be stored by ownCloud ? ownCloud normalizes file names to NFC before storing them to disk.

Your symptoms seem to imply that the normalization was bypassed.

In general please avoid clearing oc_filecache for whatever reason as it will lose all your metadata.

**Comment by izaera** [comment]
Mmmm, that's I good point. I cannot certify that I did not copy them from outside. As far as I remember, I did a huge reorganization of all my music folder in the Mac FS and it god badly synced to the Linux box, but maybe I did something more from outside...

I'll try to reproduce the failure again and report the results. 

Thanks :-)

**Comment by PVince81** [comment]
I'm going to close this then as I'm pretty sure that OC normalizes the file names.

The only way to trigger the error you describe would be by putting files with the NFD names directly into the data folder and bypass OC. As a workaround, have a look at the tool `convmv` to manually convert a list of NFD file names to NFC in your data directory.
