### ISSUE TITLE
CapabilitiesTest unit tests pass regardless

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#31588]
``testEnabledSharingAPI`` and ``testDisabledSharingAPI`` unit tests pass pretty-much regardless of what the capabilities response happens to contain.

PR #31586  demonstrates.

**Comment by phil-davis** [comment]
Fixed by PR #31587

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/19244 (Unit tests on OCI fail randomly), and https://github.com/owncloud/core/issues/24663 ([stable8] unit test failing).

**Comment by phil-davis** [comment]
Backport PR #31591 was merged a long time ago.
