### ISSUE TITLE
ICacheFactory should include createLocal()

### ISSUE THREAD

**Issue by butonic** [owncloud/core#31604]
Currently, there is no way to get a local cache from the server container, because the `ICacheFactory` does not include `createLocal()`

found when working on 
https://github.com/owncloud/core/pull/30188/files#diff-8fa91b147fc76360cb3cfca41a1db57dR116

cc @DeepDiver1975

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/1274 (not included in the user after installation), https://github.com/owncloud/core/pull/31442 (include owncloud coding standard), https://github.com/owncloud/core/issues/3450 (more stable theming by using includes), https://github.com/owncloud/core/issues/21120 (Feature request: Include a presentation feature), and https://github.com/owncloud/core/issues/13240 (search results -  should include full directory and be sorted ).
