### ISSUE TITLE
It should be possible to restore 2 files named in the same way in the trashbin at the same time

### ISSUE THREAD

**Issue by davitol** [owncloud/core#31629]
![screen shot 2018-06-04 at 12 43 34](https://user-images.githubusercontent.com/10596560/40913652-8b310146-67f5-11e8-86e1-fb9424494b90.png)

Now it is needed to restore them one by one

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/30426 (Trashbin restore to folder), https://github.com/owncloud/core/pull/30490 (Trashbin restore to folder), https://github.com/owncloud/core/issues/4275 (Possible to restore virus from deleted files), https://github.com/owncloud/core/issues/11036 (Restored shared file is shared when it shouldn't be), and https://github.com/owncloud/core/issues/11472 (Trashbin checks wrong permissions when restoring files).

**Comment by sharidas** [comment]
Yes this looks it has to do with https://github.com/owncloud/core/issues/30942. Because when user selects all, and then later selects individual file is causing the problem. If the files are selected individually, it's working.
