### ISSUE TITLE
Direct Download

### ISSUE THREAD

**Issue by ri-ees** [owncloud/core#31649]
Hi,

dmitry from owncloud community suggested me to open an issue here about this (original post here): https://central.owncloud.org/t/direct-download/13877/4

So, I’m trying to do something on owncloud.

When a file is shared using a public URL (using the site interface), there is a button to copy the URL to the clipboard which gives you something like this when you paste it: https://your-owncloud.com/index.php/s/2CZ23SZNDa5esXO

Only when you visit the page, there is another button to the direct URL which adds /download to the end of that URL: https://your-owncloud.com/index.php/s/2CZ23SZNDa5esXO/download

I have searched for solutions to avoid that unnecessary step and to get that Direct URL when clicking at the clipboard button. Or to avoid adding it manually.

So, I have been searching the code and found out that <?php p($_['downloadURL']); ?> does this (giving you the direct URL to download the file). I’m not sure if it’s that simple. I suppose it would just be a matter of replacing whatever the clipboard is using.

If it’s that simple, does anyone know where do I find this code to replace?

If it’s not that simple, any suggestions? Sharing a folder with a bunch of files it’s not a solution at all for this particular use case. :)

I would appreciate a lot if anyone could help me on this.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/12286 (Direct Download Link for Up- and Download - Was "Broker"), https://github.com/owncloud/core/issues/15622 (Feature request: Share direct-download links), https://github.com/owncloud/core/pull/28250 (Redirect a download to the direct download url if provided), https://github.com/owncloud/core/issues/8310 (Send direct download link no longer possible), and https://github.com/owncloud/core/issues/29528 (adding Script code to direct download).

**Comment by PVince81** [comment]
Have a look at "sharedialoglinklistview.js" and append "/download" to the link generated by the clipboard button.

In general the question is whether we want to include a second icon there to provide a download.
Or default to direct download for file shares but indirect for folders.

@pmaier1 @felixheidecke

**Comment by pmaier1** [comment]
> In general the question is whether we want to include a second icon there to provide a download.
Or default to direct download for file shares but indirect for folders.

Basically I like the idea but not as a replacement of the regular public link. A second icon or other kind of UI approach would fit better, IMO. @felixheidecke

**Comment by felixheidecke** [comment]
I know that Dropbox also has a URL parameter to do that. We cloud implement a button that I guess would also need explanation. I'm keeping it in mind for Phoenix.
