### ISSUE TITLE
Updating to 10.0.8 - OC\RepairException: Upgrade is not possible

### ISSUE THREAD

**Issue by horphi0815** [owncloud/core#31652]

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @VicDeo, and @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/31345 (update to 10.0.0.8 failed), https://github.com/owncloud/core/issues/29143 (failed upgrade to 8.0.16), https://github.com/owncloud/core/issues/28013 (OC\RepairException: Upgrade is not possible. Unsuccessful upgrade from 10.0.0 to 10.0.1), https://github.com/owncloud/core/issues/30264 (Upgrade 10.0.3 to 10.0.4 fails), and https://github.com/owncloud/core/issues/25546 (Error: Class 'OCA\\Files_Sharing\\API\\Server2Server and apps folder empty after upgrading to 9.0.4.1 ).
