### ISSUE TITLE
Preview generation destroys MP3 files!

### ISSUE THREAD

**Issue by paulijar** [owncloud/core#31655]
On ownCloud master branch (10.1.0 prealpha), opening a folder containing MP3 files will permanently delete all those files from the filesystem. The files remain visible in ownCloud but they are lost from the disk, as can be noticed when you try to download one of the files.

The culprit commit seems to be 95e0e0ce0a and the bug is on this line: https://github.com/owncloud/core/blob/master/lib/private/Preview/MP3.php#L57. There, `$absPath` may point either to a temporary copy or the original file, but the file is deleted regardless!

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/7593 (No download share link and previews file), https://github.com/owncloud/core/issues/14106 (previews broken for non-supported file types), https://github.com/owncloud/core/issues/5176 (Preview for avi files), https://github.com/owncloud/core/issues/8010 (Sharing: Text file preview), and https://github.com/owncloud/core/issues/6587 (disable file preview for specific files).

**Comment by patrickjahns** [comment]
@paulijar 
could you try https://github.com/owncloud/core/pull/31050 and see if on that PR you encounter the same behavior?

**Comment by DeepDiver1975** [comment]
> could you try stable10 with #31050 and see if on that PR you encounter the same behavior?

the code is the same in the backport - will fix asap and add to #31050

**Comment by DeepDiver1975** [comment]
fix is ready to be tested ^ @paulijar

**Comment by patrickjahns** [comment]
> the code is the same in the backport - will fix asap and add to #31050

hence asking to test on stable10 with this PR - if there are other changes involved that might have caused the regression to occur

**Comment by DeepDiver1975** [comment]
master pr is merged - commit is cherry-picked to #31050  @patrickjahns  FYI

**Comment by paulijar** [comment]
I pulled the core master branch and it seems to work fine now.
