### ISSUE TITLE
Link share dialog must block during creation

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31654]
### Steps

1. Enable encryption (this is to cause longer delays during share creation)
1. Create a big folder with lots of files
1. Share said folder with link
1. In the dialog, click "Save"

### Expected result
During saving, which takes longer, the dialog must be disabled and a spinner must be displayed to tell me it's working.

### Actual result
No spinner appears, I can still click inside the dialog fields as if I didn't properly click "Save".
If I click "Save" again, two links are created.

### Version
ownCloud 10.0.8

**Comment by PVince81** [comment]
@pmaier1 @felixheidecke FYI

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/6110 (in Share dialog), https://github.com/owncloud/core/issues/6109 (in Share dialog), https://github.com/owncloud/core/issues/28427 (Create link share dialog out of focus), https://github.com/owncloud/core/pull/31129 (Add missing public link share dialog features), and https://github.com/owncloud/core/pull/31065 (Share link close delay).

**Comment by labkode** [comment]
@PVince81 Same for updating the public link share

**Comment by pmaier1** [comment]
Yep, definitely needs fixing.
