### ISSUE TITLE
Updating to 10.0.8 - OC\RepairException: Upgrade is not possible

### ISSUE THREAD

**Issue by horphi0815** [owncloud/core#31653]
### Steps to reproduce
1. started update over administration mode
2.
3.

### Expected behaviour
update of owncloud

### Actual behaviour
        Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
        Repair warning: Please install or update the following apps manually or disable them with: occ app:disable bookmarks
        Repair warning: For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps

### Server configuration
**Operating system**:
All-Inkl
**Web server:**
All-Inkl
**Database:**
MYSQL
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
10.0.7.2
**Updated from an older ownCloud or fresh install:**
older
**Where did you install ownCloud from:**
All-Inkl
**Signing status (ownCloud 9.0 and above):**

```
LOGIN NOT POSSIBLE due to update
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => 'Kd50fTk9tRuJVIlzPwYnDSZAaJTp8EZbzZgiPrh99BITaTj',
  'trusted_domains' => 
  array (
    0 => '.de',
    1 => 'www..de',
  ),
  'datadirectory' => '/www/owncloud_9/data',
  'overwrite.cli.url' => 'http://owncloud_9',
  'dbtype' => 'mysql',
  'version' => '10.0.7.2',
  'dbname' => '',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'TtoyV_',
  'dbuser' => '',
  'dbpassword' => '',
  'logtimezone' => 'Europe/Berlin',
  'installed' => true,
  'tempdirectory' => '/www/htdocs/owncloud_9/tmp/',
  'integrity.check.disabled' => false,
  'loglevel' => 2,
  'maintenance' => false,
  'enable_certificate_management' => true,
  'theme' => '',
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => '',
  'updater.secret' => '$2y10$3rbAgE3BQfe4LTsLPwScGeMhLy5NMpVxdMDNocC.oaD1fODenKFZy',
```

**List of activated apps:**

```

appid |  
-- | --
activity
audioplayer
backgroundjob
bookmarks
calendar
comments
configreport
contacts
core
dav
documents
federatedfilesharing
federation
files
files_clipboard
files_external
files_pdfviewer
files_reader
files_sharing
files_texteditor
files_trashbin
files_versions
files_videoplayer
firstrunwizard
gallery


```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** FireFox

**Operating system:** Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by patrickjahns** [comment]
@horphi0815 
This is not a bug with ownCloud itself and actually be suited to be discussed/answered in our community forums https://central.owncloud.org/

As the *warning* clearly states - you previously enabled the `bookmarks` app - `bookmarks` app is a community (3rd party) application. The original author of this application has removed the application from the marketplace (ref: https://marketplace.owncloud.com/apps/bookmarks ) - this leaves you now with the choice to either 
a) disable the app (`occ app:disable bookmarks`) as the warning suggested
b) assuming bookmarks app is still compatible with ownCloud 10.0.8 - copy over the app ( as [suggested in the documentation](https://doc.owncloud.org/server/latest/admin_manual/maintenance/manual_upgrade.html?highlight=upgrade#copy-old-apps) 

...  and then re-do the upgrade

As this is not a bug in ownCloud itself, should you require further assistance, please visit the forums https://central.owncloud.org/

**Comment by horphi0815** [comment]
Thx for your reply. I deactivated the App and it works!. :-)
