### ISSUE TITLE
Public links with "Upload only" permission are saved as "Download / View / Upload"

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#31676]
### Steps to reproduce
In android client, create a public link over a folder with permission `Upload only` (permissions=4)

`curl -k -H 'Content-Type:application/x-www-form-urlencoded; charset=utf-8' -H 'OCS-APIREQUEST:true' -H 'Authorization:Basic xxxxxx' -H 'User-Agent:Mozilla/5.0 (Android) ownCloud-android/2.8.0-beta.1' -H 'Host:xxxxx' -H 'Content-Length:138' -X POST 'xxxxx/ocs/v1.php/apps/files_sharing/api/v1/shares' --data-binary 'path=%2FDocuments%2F&shareType=3&shareWith=&name=Documents+link+%284%29&expireDate=2018-06-27&publicUpload=true&password=a&permissions=4'`

### Actual behaviour

in the response:

`<permissions>15</permissions>`

### Expected behaviour
in the response:

`<permissions>4</permissions>`

In the PUT request to update the public link permissions works properly

### Server configuration
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.0.8.5","versionstring":"10.0.8","edition":"Enterprise","productname":"ownCloud"}

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/14352 (Permission to upload), https://github.com/owncloud/core/issues/14291 (Public upload and existing files), https://github.com/owncloud/core/issues/17218 (Public sharing download function), https://github.com/owncloud/core/issues/8161 ([Public Upload] Force password-protect public-uploads), and https://github.com/owncloud/core/issues/5571 (Uploaded files are downloaded again on same system).

**Comment by PVince81** [comment]
Strange, with the web UI it works. The web UI can create an upload-only public link and send permissions 4 in the POST request:
```
curl 'http://localhost/owncloud/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json' -H 'Cookie: oc_sessionPassphrase=MLY3OYWph%2BMl6bSl7pfjXb9gygl7utzlXVnAX4WC0MQP8XnxhblA4HT66ZzU4Yvt2XsgkaDq4mWdZG%2BjB%2FyeFRGW8wihgjj9lf847tcWldBdi14GUpkjY5WW%2FC5HfagS; ockbfur1449k=i1cobqljajruj40gbg07gn6gc9' -H 'requesttoken: PkxGLEA0LCcUNTsefAomRycCJiEpOgFpH0ANen4MBms=:SzunqqyNEvwm5DeujWACqTnFsxjL6xT3IuCVb1KL/lo=' -H 'Origin: http://localhost' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.9,de;q=0.8' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36' -H 'OCS-APIREQUEST: true' -H 'Content-Type: application/json' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' --data-binary '{"expireDate":"","permissions":4,"name":"test link","shareType":3,"path":"/test"}' --compressed
```

The response also contains "4".

This is with v10.0.8 from git.

@jesmrec did you maybe change the default share permissions or any sharing settings ?
I have the defaults from a new install.

**Comment by PVince81** [comment]
@jesmrec please remove `publicUpload` from the request payload and only pass permissions.

**Comment by jesmrec** [comment]
right, client have to remove `publicUpload` from the request. Thanks. Closing.
