### ISSUE TITLE
[UI] "Menu Burger" hides content in low resolution (width <= 768px)

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/core#31684]
### Steps to reproduce
1. In your account go to settings
2. Reduce the browser window width under 768px (menu on the left disappears and a "Menu Burger" appears)

### Actual behaviour
The headline and content are covered by the "Menu Burger".

![image](https://user-images.githubusercontent.com/33026403/41117002-22eb2d7a-6a8c-11e8-855a-8dd5afc2e97c.png)

![image](https://user-images.githubusercontent.com/33026403/41117050-3f9813fc-6a8c-11e8-8b54-b17831a31deb.png)

### Expected behaviour
The headlines and content are not covered by the "Menu Burger". 
In the files view section everything looks good.

![image](https://user-images.githubusercontent.com/33026403/41116964-0ec05d20-6a8c-11e8-95c4-132b66349517.png)

### Server configuration
**ownCloud version:** (see ownCloud admin page)
Tested in 10.0.6 - 10.0.8

### Client configuration
**Browser:**
Chrome Version 66.0.3359
**Operating system:**
MacOS 10.13.4

**Comment by ChrisEdS** [comment]
@felixheidecke - Easy one?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @felixheidecke.

Possibly related issues are https://github.com/owncloud/core/issues/3536 (Navigation and "hidden" menus), https://github.com/owncloud/core/issues/12986 (Right menu hidden on mobile), https://github.com/owncloud/core/issues/23691 (Add responsive design to the apps menu when using on low resolution displays), https://github.com/owncloud/core/issues/8642 (Share menu hidden by files sidebar), and https://github.com/owncloud/core/pull/30594 (UI tests for showing hidden files).
