### ISSUE TITLE
File cache update() cannot set empty string on Oracle

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31692]
### Steps

1. Set a checksum (maybe upload a file)
1. Reset the checksum to empty string using the Node API: `$file1->getStorage()->getCache()->update($file1->getId(), ['checksum' => '']);`
1. Check database

### Expected result
Checksum cleared to empty string on all DBs.

### Actual result
Checksum not cleared on Oracle, other DBs are fine.

Even more worrying is that if you set it to "null" in the update() function it doesn't work for **all DBs**.

### Versions
OC 10.0.8

Discovered on https://github.com/owncloud/core/pull/31430

### Tech concept for the fix

- [x] add unit test for `OC\File\Cache::update()` to reproduce the issue and prove it's broken on Oracle
- [x] Modify `OC\File\Cache` to detect Oracle. If Oracle and the parameter to update is an empty string, convert it to NULL and adjust the query if necessary.
- [ ] check if other parts of file cache might be affected
- [ ] raise separate ticket for NULL issue

Please note that the update query contains a `WHERE` statement to avoid updating values that are already set to the same value in the DB. This needs special handling for nulls, etc.

At this point to avoid potential regressions for other DBs, I suggest ignoring the "setting NULL" issue and focus on Oracle only.

### Estimate
- Dev time including unit tests: 1-2md

@butonic @DeepDiver1975 @tomneedham

**Comment by PVince81** [comment]
This could potentially be critical because some code paths will clear values like the checksum, mostly in external storage update detection cases. If the value cannot be cleared, invalid checksums could still stay in the DB for Oracle.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/17027 (Cannot create empty file on SFTP), https://github.com/owncloud/core/issues/21366 (Update), https://github.com/owncloud/core/issues/20661 (Update), https://github.com/owncloud/core/issues/10078 (cache updater updates etag too often), and https://github.com/owncloud/core/issues/23284 (GoogleDrive folder appears empty after file update).

**Comment by PVince81** [comment]
@tomneedham @butonic do we agree on the proposed approach ? only fix for Oracle and only for when setting empty strings ?

**Comment by IljaN** [comment]
It looks like the update only works if the mtime changes

**Comment by PVince81** [comment]
yes, this is because of detection of changes on external storages.

**Comment by IljaN** [comment]
But we shouldn`t mess with the mtime when resetting the checksum right?

**Comment by PVince81** [comment]
@IljaN when restting the checksum manually from a specific command, we don't touch the mtime.

What you observed is likely the normal behavior of the scanner: whenever the mtime of a file on disk is different than the one in the file cache, it is interpreted as "the file on disk was modified" so the scanner will update the file's metadata and clear the checksum. As a side effect of course the mtime would also be adjusted to whatever is now on disk.

**Comment by PVince81** [comment]
@IljaN link to PR ? I thought you had something already based on our discussions

**Comment by IljaN** [comment]
Backport: https://github.com/owncloud/core/pull/31996
