### ISSUE TITLE
Use new DAV endpoint in web UI for download URL

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31706]
In apps/files/js/files.js in the getDownloadUrl method, it still uses the old "remote.php/webdav/$path" endpoint.

This needs to be changed to use the new endpoint "remote.php/files/$user/$path".
Best is to get the base URL from the default `OC.Files.Client` instance or the one from inside the FileList.

cc @labkode

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/28874 (Use new DAV endpoint in web UI), https://github.com/owncloud/core/issues/21643 (Make web UI use the dav v2 endpoint), https://github.com/owncloud/core/issues/23269 (Consider new DAV endpoint for public shares), https://github.com/owncloud/core/issues/17014 (Webdav endpoint for zip download), and https://github.com/owncloud/core/issues/24776 (Cannot move files using new dav endpoint ).
