### ISSUE TITLE
Updating to 9.1.8 on a Synology NAS does not work

### ISSUE THREAD

**Issue by suterma** [owncloud/core#31705]
### Steps to reproduce
I followed the manual upgrade according to https://doc.owncloud.org/server/9.1/admin_manual/maintenance/manual_upgrade.html but used a few shortcut. Too many probably?

1. Made a data and DB backup, so data is safe
2. I did not initially enable the maintenance mode
3. I just copied over the new 9.1.8 content
4. Browsed to the web page and initiated the upgrade process
5. Got the message about "not writable config folder" message
6. Via Synology UI, gave ownership of all owncloud to http user
7. Re-Run from 4, but still receiving the "not writable config folder" message

### Expected behaviour
Successful upgrade to 9.1.8

### Actual behaviour
Stuck with the "not writable config folder" message

### Server configuration
This owncloud instance runs on a Synology NAS, originally installed using the "shared hosting" method.

**As from the UI error "console" in the browser: **

Updating to 9.1.8
OC\HintException: Can't write into config directory!

Detailed logs 
Preparing update
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
[1 / 24]: Checking table oc_appconfig
[2 / 24]: Checking table oc_storages
[3 / 24]: Checking table oc_mounts
[4 / 24]: Checking table oc_mimetypes
[5 / 24]: Checking table oc_filecache
[6 / 24]: Checking table oc_group_user
[7 / 24]: Checking table oc_group_admin
[8 / 24]: Checking table oc_groups
[9 / 24]: Checking table oc_preferences
[10 / 24]: Checking table oc_properties
[11 / 24]: Checking table oc_share
[12 / 24]: Checking table oc_jobs
[13 / 24]: Checking table oc_users
[14 / 24]: Checking table oc_authtoken
[15 / 24]: Checking table oc_vcategory
[16 / 24]: Checking table oc_vcategory_to_object
[17 / 24]: Checking table oc_systemtag
[18 / 24]: Checking table oc_systemtag_object_mapping
[19 / 24]: Checking table oc_systemtag_group
[20 / 24]: Checking table oc_privatedata
[21 / 24]: Checking table oc_file_locks
[22 / 24]: Checking table oc_comments
[23 / 24]: Checking table oc_comments_read_markers
[24 / 24]: Checking table oc_credentials
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
[1 / 28]: Drop old database table: calendar_calendars
[2 / 28]: Drop old database table: calendar_objects
[3 / 28]: Drop old database table: calendar_share_calendar
[4 / 28]: Drop old database table: calendar_share_event
[5 / 28]: Drop old database table: file_map
[6 / 28]: Drop old database table: foldersize
[7 / 28]: Drop old database table: fscache
[8 / 28]: Drop old database table: gallery_sharing
[9 / 28]: Drop old database table: locks
[10 / 28]: Drop old database table: log
[11 / 28]: Drop old database table: media_albums
[12 / 28]: Drop old database table: media_artists
[13 / 28]: Drop old database table: media_sessions
[14 / 28]: Drop old database table: media_songs
[15 / 28]: Drop old database table: media_users
[16 / 28]: Drop old database table: permissions
[17 / 28]: Drop old database table: pictures_images_cache
[18 / 28]: Drop old database table: principalgroups
[19 / 28]: Drop old database table: principals
[20 / 28]: Drop old database table: queuedtasks
[21 / 28]: Drop old database table: sharing
[22 / 28]: Drop old database table: clndr_calendars
[23 / 28]: Drop old database table: clndr_objects
[24 / 28]: Drop old database table: clndr_share_event
[25 / 28]: Drop old database table: clndr_share_calendar
[26 / 28]: Drop old database table: clndr_repeat
[27 / 28]: Drop old database table: contacts_addressbooks
[28 / 28]: Drop old database table: contacts_cards
[28 / 28]: Drop old database tables
[1 / 4]: Remove old (< 9.0) calendar/contact shares
[2 / 4]: Remove old (< 9.0) calendar/contact shares
[3 / 4]: Remove old (< 9.0) calendar/contact shares
[4 / 4]: Remove old (< 9.0) calendar/contact shares
[4 / 4]: Remove old (< 9.0) calendar/contact shares
[1 / 2]: Fix permissions so avatars can be stored again
[1 / 1]: Fix permissions so avatars can be stored again
Starting code integrity check
Finished code integrity check
OC\HintException: Can't write into config directory!
The update was unsuccessful. Please report this issue to the ownCloud community.
```
Note: http://example.com/index.php/settings/integrity/failed is not accessible. No such directory exists on the server
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxx/Sktb1',
  'trusted_domains' => 
  array (
    0 => 'xxxxxxxxxxxx.xxxxxxxxxxxx.xxxxxxxxxxxx',
  ),
  'datadirectory' => '/volume1/web/owncloud/data',
  'overwrite.cli.url' => 'https://xxxxxxxxxxxx.xxxxxxxxxxxx.xxxxxxxxxxxx/owncloud',
  'dbtype' => 'mysql',
  'version' => '9.1.7.2',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1:3307',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxxxxxxxxxxx',
  'installed' => true,
  'forceSSLforSubdomains' => true,
  'theme' => '',
  'maintenance' => true,
  'forcessl' => true,
  'loglevel' => 0,
  'enable_previews' => true,
  'trashbin_retention_obligation' => 'auto',
  'updater.secret' => 'xxxxxxxxxxxx',
);

```

**List of activated apps:**

Only the preinstalled ones.

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Google Chrome**

**Operating system:**
Ubuntu OS

### Logs
#### Web server error log
I did not find this log. Is it really relevant anyway here?

#### ownCloud log (data/owncloud.log)
...
{"reqId":"av4aajAy8c1\/4EE1jgbS","remoteAddr":"192.168.77.50","app":"PHP","message":"chmod(): Operation not permitted at \/volume1\/web\/owncloud\/lib\/private\/Config.php#242","level":3,"time":"2018-06-08T21:45:19+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=PDtfTRY1HQBXJTxEdA13dyYyXH8yAThyZTJqCwQzMV0%3D%3AoY58TRhZfqiw1J9NKs%2F4htn4JuZXFGp5wexH9x6yiIQ%3D","user":"--"}
{"reqId":"av4aajAy8c1\/4EE1jgbS","remoteAddr":"192.168.77.50","app":"core","message":"starting upgrade from 9.1.7.2 to 9.1.8.2","level":0,"time":"2018-06-08T21:45:19+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=PDtfTRY1HQBXJTxEdA13dyYyXH8yAThyZTJqCwQzMV0%3D%3AoY58TRhZfqiw1J9NKs%2F4htn4JuZXFGp5wexH9x6yiIQ%3D","user":"--"}
{"reqId":"av4aajAy8c1\/4EE1jgbS","remoteAddr":"192.168.77.50","app":"PHP","message":"chmod(): Operation not permitted at \/volume1\/web\/owncloud\/lib\/private\/Log\/Owncloud.php#114","level":3,"time":"2018-06-08T21:47:11+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=PDtfTRY1HQBXJTxEdA13dyYyXH8yAThyZTJqCwQzMV0%3D%3AoY58TRhZfqiw1J9NKs%2F4htn4JuZXFGp5wexH9x6yiIQ%3D","user":"--"}
{"reqId":"RYk4wNbO9wqV4J3uO6\/B","remoteAddr":"192.168.77.50","app":"PHP","message":"chmod(): Operation not permitted at \/volume1\/web\/owncloud\/lib\/private\/Config.php#242","level":3,"time":"2018-06-08T21:49:16+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=ZBgrOQUAHzdSMDhaARAiAQQPJTNjFi5wdQ1aYyZFGz8%3D%3A7zALGgjmcdmiDWl8iNVx9cx6ZJj0d1ZWNr%2FFn4ze7oo%3D","user":"--"}
{"reqId":"RYk4wNbO9wqV4J3uO6\/B","remoteAddr":"192.168.77.50","app":"core","message":"starting upgrade from 9.1.7.2 to 9.1.8.2","level":0,"time":"2018-06-08T21:49:16+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=ZBgrOQUAHzdSMDhaARAiAQQPJTNjFi5wdQ1aYyZFGz8%3D%3A7zALGgjmcdmiDWl8iNVx9cx6ZJj0d1ZWNr%2FFn4ze7oo%3D","user":"--"}
{"reqId":"RYk4wNbO9wqV4J3uO6\/B","remoteAddr":"192.168.77.50","app":"PHP","message":"chmod(): Operation not permitted at \/volume1\/web\/owncloud\/lib\/private\/Log\/Owncloud.php#114","level":3,"time":"2018-06-08T21:51:05+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=ZBgrOQUAHzdSMDhaARAiAQQPJTNjFi5wdQ1aYyZFGz8%3D%3A7zALGgjmcdmiDWl8iNVx9cx6ZJj0d1ZWNr%2FFn4ze7oo%3D","user":"--"}
{"reqId":"yArzJ+OcP28Yn5tctgDy","remoteAddr":"192.168.77.50","app":"core","message":"starting upgrade from 9.1.7.2 to 9.1.8.2","level":0,"time":"2018-06-10T19:25:39+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=YVokHz89Hi5jNx0HAzE1E1EkYgBgLggNRwVRDiBQMBA%3D%3A59GfSTnFSTm56bGX6bSsXLmf3thCy6Yav9T9wEdrmvQ%3D","user":"--"}

**Comment by suterma** [comment]
This is probably just a permission problem. The owncloud docs from https://doc.owncloud.org/server/9.1/admin_manual/maintenance/update.html#set-updating-permissions-label seem clear to me.
However, since I am working on a Synology NAS, using their Web UI, things look different, and I am not 100% sure, whether I put everything right. Probably the docs could be improved with instructions/hints for a Synology NAS specifically?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/25647 (WEBDav Error on 9.1 Synology NAS), https://github.com/owncloud/core/issues/18419 (Update to 8.1.1), https://github.com/owncloud/core/issues/18479 (Update to 8.1.1), https://github.com/owncloud/core/issues/28052 (Problem updating to 10.0.2 RC1 with the Market app), and https://github.com/owncloud/core/issues/28348 (Upgrade from 10.0.0.12 to 10.0.2 end in mysql server error).

**Comment by suterma** [comment]
A closer look to the config.php file with the Synology Web UI shows it as owned by admin AFTER the failed update. Also the http user has the write permission removed. I explicitly have set it as owned and read/writeable by http BEFORE the upgrade.

**How/Why does the updater process (started from the web browser) manage to change the OWNER of the config.php file?** Or, could something other interfere with the update?

**Comment by suterma** [comment]
@ownclouders: 
#18419 is about DB rights, which are no problem for me. The "detailed logs" reports the DB update as working fine.
#18479 seems to be about updating with the updater app. I had this error earlier, but now went the "manual update" route with does not have these problems.
#25647 is about WEBDav and does not apply
#28052 is about a market App which I do not use
 #28348 is about DB server problems. DB is fine.

**I still believe this a permission problem is one form or another. What about the OWNER change, described above?**

**Comment by PVince81** [comment]
can you `ls -l` your ownCloud folder so we see the config folder permissions ? is the config/config.php file writable ?

**Comment by PVince81** [comment]
note, for help please ask on http://central.owncloud.org/

Github is for actual bugs and you seem to be having an environment issue. I'm closing this, please ask for help in http://central.owncloud.org/

If it turns out to be a bug, we can reopen here.

**Comment by suterma** [comment]
SOLVED! **Synology users, please note: setting permissions from the Synology Web Interface does not work for ownCloud updates!**
The solution was to ssh into the Synology NAS using admin credentials, then executing the script from https://doc.owncloud.org/server/9.1/admin_manual/maintenance/update.html#set-updating-permissions-label on the terminal.
Upgrade went flawlessly from that point on.
