### ISSUE TITLE
Harmonize printout: background:queue/execute commands

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#31727]
This is a reminder to harmonize the printout of:

Merged: https://github.com/owncloud/core/pull/31630 (Adding background:queue commands: status and delete)
and 
Open: https://github.com/owncloud/core/pull/31617 (Add background:execute occ command for running cron jobs manually)

Please see the suggestions in #31630

If we leave it as it is it looks really unprofessional and confusing.

Documentation relevant

@DeepDiver1975 @tomneedham

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/pull/31617 (Add background:execute occ command for running cron jobs manually), https://github.com/owncloud/core/pull/31630 (Adding background:queue commands: status and delete), https://github.com/owncloud/core/issues/26760 (InfoParser not properly parsing single background-job, single command, etc), https://github.com/owncloud/core/issues/30909 (Disable scanner commands and background jobs for unscannable storages), and https://github.com/owncloud/core/pull/30281 ([stable10] When executing the data-fingerprint command a log entry is…).

**Comment by DeepDiver1975** [comment]
THX!

**Comment by tomneedham** [comment]
Just provide feedback on the PR

**Comment by mmattel** [comment]
Disagree @tomneedham 
Two PR´s from different creators, one merged, one open
On the merged one it is explizit stated to do the alignment post merging
Text content needs to be aligned on both
So where to put that that it will not be forgotten?
@DeepDiver1975 your pov ?

**Comment by DeepDiver1975** [comment]
I guess @tomneedham point is that we - as he proposed in my PR - sync the printout in his pr which finalizes the set of commands in this area.

**Comment by mmattel** [comment]
If @tomneedham adds the changes also on the parts you added I am fine with. The thing is to be in sync (and having professional looking headlines)

**Comment by tomneedham** [comment]
Yes, the idea is that @DeepDiver1975 fixed his PR, we discussed and decided the output. Now my PR must be rebased and fixed. No need for a new ticket && a PR
