### ISSUE TITLE
"Exclude groups from sharing" checkbox broken on master branch

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#31739]
### Steps to reproduce
1. Install ownCloud from github, master branch (https://github.com/owncloud/core/commit/9edd97a8646a76af7834fd967a8b71aa37829c91)
2. Create several groups
3. Go to the settings page, sharing section
4. Mark "exclude groups form sharing" checkbox
5. Try to exclude an specific group

### Expected behaviour
Groups can be selected

### Actual behaviour
The selection loads forever

![screen shot 2018-06-12 at 18 02 09](https://user-images.githubusercontent.com/1477829/41302464-cc763d08-6e6a-11e8-917f-41d483f28d36.png)

It works fine on stable10

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** apache 2.4

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** master

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** github

**Comment by PVince81** [comment]
@jvillafanez as discussed, please have a look if you can fix this as you're already in the topic.

Estimate: 0.5md

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/10307 (Exclude Groups from Sharing), https://github.com/owncloud/core/issues/12824 (CI broken on master), https://github.com/owncloud/core/issues/13402 (... broken), https://github.com/owncloud/core/issues/7272 (Exclude subfolder from sharing), and https://github.com/owncloud/core/issues/18512 (Master broken).

**Comment by phil-davis** [comment]
I  thought I had seen this problem a little while ago. Maybe there is another issue raised, but I can't see it.
Sharing autocomplete does queries like:
```
/ocs/v1.php/apps/files_sharing/api/v1/sharees?format=json&search=longname&perPage=200&itemType=file
```
The settings box uses:
```
/index.php/settings/users/groups?pattern=longname&filterGroups=1
```
In ``stable10`` the query returns status 200 with happy data.
In ``master`` the query returns 302 - redirect ???
The problem is there with user_management app enable or disabled.

**Comment by jvillafanez** [comment]
Confirmed the problem: the target route has been moved to the user_management app. It should be `/apps/user_management/groups` instead of `/settings/users/groups`.

Quick fix would need to install the user_management app and modify the "settings/js/settings.js" file so the ajax request goes to the new url.

We'll need to schedule time for a proper solution as this would create a dependency between 2 apps.

**Comment by PVince81** [comment]
@jvillafanez thanks for the research, let's stop here for now.

@DeepDiver1975 seems we'd need to either move back the endpoint or add a second one.

**Comment by PVince81** [comment]
this could be a blocker for moving out user_management as we cannot assume the app will always be enabled

**Comment by PVince81** [comment]
setting to p2 as I think we should not release OC 11 without fixing this regression

**Comment by sharidas** [comment]
A rough though that I have is:
- Move lib/MetaData.php of user_management to core. 
- Also move the GroupsController from user_management to core, and adjust the routes.

**Comment by sharidas** [comment]
Created PRs
- https://github.com/owncloud/core/pull/33442
- https://github.com/owncloud/user_management/pull/96
