### ISSUE TITLE
Regressions in apps possibly related to object store backport

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31747]
- [x] firewall: https://github.com/owncloud/firewall/issues/493, fix PR https://github.com/owncloud/core/pull/31748
- [x] user_ldap  - PR #31750 and backport #31751 - I wrote tests in ``core`` that were "too tricky" for the test environment in ``user_ldap`` (see details in PR). And ``user_lddap```  itself had a test scenario that was not completely setup properly to know the users and groups it could autocomplete  against - fix in https://github.com/owncloud/user_ldap/pull/249

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/31050 ([stable10] Backport all objectstore related changes), https://github.com/owncloud/core/issues/22058 (Primary storage - object store and encryption), https://github.com/owncloud/core/issues/14624 (Should "object store support" be listed as an app?), https://github.com/owncloud/core/issues/22540 (App Store shows no Apps), and https://github.com/owncloud/core/pull/31285 (The Great Fix of object store acceptance tests ....).

**Comment by phil-davis** [comment]
``user_ldap`` - I made the checks done by some core auto-completion acceptance tests more rigorous. I suspect that some fails of ``user_ldap`` autocomplete test scenarios are because the test scenario is not quite right, and now the test code is being tougher on the pass/fail criteria.
Looking at it...

**Comment by phil-davis** [comment]
PR #31755 and backport #31756 just make the core acceptance test code more robust, so it better survives being asked for the display name of a user that it does not know about. I noticed it because I broke it from tests in ``user_ldap``

**Comment by PVince81** [comment]
firewall PR merged, let's wait for CI to recheck before ticking the checkbox

**Comment by phil-davis** [comment]
I checked the box now - ``user_ldap`` CI passed this morning.

**Comment by PVince81** [comment]
firewall CI issue solved by core fix
