### ISSUE TITLE
Adding command  background:queue:add

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#31743]
**Referencing:**
https://github.com/owncloud/core/pull/31630 (Adding background:queue commands: status and delete)

You can now get the job list, delete a job, but you can´t add a job (eg after accidentially deleting it)

**Proposal:**
Adding a command to add a job to the job list

We will add the current output for having a refernce of the ``background:queue:status`` command to the documentation, see https://github.com/owncloud/documentation/issues/4198#issuecomment-396844687 

@DeepDiver1975  @tomneedham

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/31630 (Adding background:queue commands: status and delete), https://github.com/owncloud/core/pull/31617 (Add background:execute occ command for running cron jobs manually), https://github.com/owncloud/core/issues/31727 (Harmonize printout: background:queue/execute commands), https://github.com/owncloud/core/pull/29635 (Add basic tests for files:scan command), and https://github.com/owncloud/core/pull/29583 (add test for user commands).

**Comment by tomneedham** [comment]
IMO, it is not in the design of ownCloud for the admin to manually add jobs. Execute is useful for debugging / forcing jobs to run. Status is required to get the ID and check times. Delete is useful for cleanup. But adding `add` IMO just gives more tools to admins to break things.

**Comment by mmattel** [comment]
@tomneedham disagree, we **have** the delete command. Therefore we **need** the add command too. Else an admin can never bring back a job he has deleted. An add job command can be restricted to those jobs which are enabled by default, this would eliminate misuse.
