### ISSUE TITLE
Could Not create file/folder

### ISSUE THREAD

**Issue by qtechsandesh** [owncloud/core#31754]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
When i click on plus icon and create a file with any name then it should create the file with the name

### Actual behaviour
when I click on plus icon on web interface and trying to create the file or folder it gives me an error "Could not create file"

### Server configuration
**Operating system**: Ubuntu 16.04 LTS

**Web server:** Apache2

**Database:** MySql

**PHP version:** PHP 7.1

**ownCloud version:** (see ownCloud admin page)
10.0.4
**Updated from an older ownCloud or fresh install:**
Yes Updated from 10.0.3 to 10.0.4 but It was working fine properly when I upgraded last year.
**Where did you install ownCloud from:**
/home/user/owncloud
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_sharing
	- EXTRA_FILE
		- appinfo/Migrations/Version20171215103657.php
		- appinfo/Migrations/Version20171115154900.php
- files
	- EXTRA_FILE
		- lib/Command/VerifyChecksums.php
- files_trashbin
	- EXTRA_FILE
		- lib/Quota.php
- dav
	- EXTRA_FILE
		- lib/Repair/RemoveInvalidShares.php
		- lib/Tree.php
- notifications
	- EXTRA_FILE
		- appinfo/Migrations/Version20180119080933.php
		- templates/mail/htmlmail.php
		- templates/mail/plaintextmail.php
		- templates/panels/personal/notifications.php
		- lib/Controller/NotificationOptionsController.php
		- lib/Mailer/NotificationMailerAdapter.php
		- lib/Mailer/NotificationMailer.php
		- lib/Panels/Personal/NotificationsPanel.php
		- lib/Configuration/OptionsStorage.php
		- js/personal_settings.js
- theme-example
	- INVALID_HASH
		- appinfo/info.xml
		- core/css/styles.css
		- defaults.php

Raw output
==========
Array
(
    [files_sharing] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [appinfo/Migrations/Version20171215103657.php] => Array
                        (
                            [expected] => 
                            [current] => adb2efec4235fad3aa2b55465b292bea656f69722c14a1022720a862bd4f0bce571bcb68f8ea912cab70a7b30c5b4441e24aaa73e6aaf35339d6f483017d1e40
                        )

                    [appinfo/Migrations/Version20171115154900.php] => Array
                        (
                            [expected] => 
                            [current] => 85fd488f0c342920d35fa6872f49727925c2b5114d9bdcda551568abb63a8e78cfc3a3438fdbc141dacee3948c008a26516424ebe0b66baffd968bd07737c964
                        )

                )

        )

    [files] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [lib/Command/VerifyChecksums.php] => Array
                        (
                            [expected] => 
                            [current] => 598a2cf8d76a0f75e4e68e10ab1d79d8e5bf7e472ae0aa3bf23be82fdb9a1467dbe1257b076cc941de709ea89ddb342136726fd3bf47b5b5ff527eb13c641088
                        )

                )

        )

    [files_trashbin] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [lib/Quota.php] => Array
                        (
                            [expected] => 
                            [current] => 2df2879c4f720039f986bfa02ee54530bc87689269cbe82e0a9528d63f0c96b58042040b15b74ec1ce8a3887b70cf66649a8a31494bc480310bc9483a062c3bc
                        )

                )

        )

    [dav] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [lib/Repair/RemoveInvalidShares.php] => Array
                        (
                            [expected] => 
                            [current] => 7554347c7232819eb078db981528a5d1fbfd7e2a3fc2850f13556aa9e2f40983c9a13906d1cc34210280f648f919614c76f5aa0ec7dd927e5278caf21173a5a8
                        )

                    [lib/Tree.php] => Array
                        (
                            [expected] => 
                            [current] => a4fd3e7c6b9f4515440e31a850479f138b01a47112cfdeb962e9c62e4d8f8e10dbb3d39c5772b65e3a399b54bad2feaabfbcb9ad916dd02961d888dd30320983
                        )

                )

        )

    [notifications] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [appinfo/Migrations/Version20180119080933.php] => Array
                        (
                            [expected] => 
                            [current] => f3804b4978a11534e46389ccb61de343b567bb72b632eb440365f5c8ed61e14dda3e88fab5a00ec322147b1d7048e744f8c82c8bb15355943b70ffae6be6a53e
                        )

                    [templates/mail/htmlmail.php] => Array
                        (
                            [expected] => 
                            [current] => 2ec54fcd88533951d3b2dae68bb700239f25cebfdc0db2d694471690f8385c7dd9e03df41b6d6f474ecb786c26256b6b651f40d8fbe201893fb3717d43520a57
                        )

                    [templates/mail/plaintextmail.php] => Array
                        (
                            [expected] => 
                            [current] => 46c51f685fe133a091888d3860edf2d21c438165fb6d6ec030f18f72343fd92adaf86726742dc30457bd81dabebc5f4d86f4be97945ca3d30f7af38af7ba3bc2
                        )

                    [templates/panels/personal/notifications.php] => Array
                        (
                            [expected] => 
                            [current] => 6248879dabca6e4518d4049d070d63b8e43f12af0a9f8f74ec7b6cf2e599a253e4e75752a9f7f9b967c2843b7d2504e996aa5a81937350b9d2672d5eb90a2879
                        )

                    [lib/Controller/NotificationOptionsController.php] => Array
                        (
                            [expected] => 
                            [current] => 659dcea0df0495e0359b4085a975dd8b2f70e7a2bdbbcfce87b6dfa3ea7adc9b5dc9002b066d88e65ba182ab90065dc87c6b204dbd3a364854d5842f31cafdf2
                        )

                    [lib/Mailer/NotificationMailerAdapter.php] => Array
                        (
                            [expected] => 
                            [current] => c9581e4deb6a8148e08f2e535f97c8ad16d0b7381c32adb5297434ab25da3acdfda8c782fbddaecbbe1a46b67596a8620207f3cd99d0e63ad9f71046f3d99eab
                        )

                    [lib/Mailer/NotificationMailer.php] => Array
                        (
                            [expected] => 
                            [current] => 1c6c762397f5a42a68e98bc10220b88a7f018fd480a45ca1e1481878d863f7819c372463c39d82123b84d75ab4585cda8c27920d5e758413e3de938cd9a23660
                        )

                    [lib/Panels/Personal/NotificationsPanel.php] => Array
                        (
                            [expected] => 
                            [current] => 7f97d21ed39a51e42e8a77a701a0cf532ae81629c74b4ce4fd597ee82be6e72dcb09e31eb54d709e77387e047e6cd86a49e7066e2477d952ceb065fc5c9909a8
                        )

                    [lib/Configuration/OptionsStorage.php] => Array
                        (
                            [expected] => 
                            [current] => c456f99dd95d78c84161454bf3c7a77a7a3c62264f632783dd61ae65f9a5255b5ab61cab1bc2619d5a9a733c548ba6c91a6b9d5cea3e8630279ed3d7adfa01c1
                        )

                    [js/personal_settings.js] => Array
                        (
                            [expected] => 
                            [current] => 2549d2d87454a3f0997376e919c020eedc22eb67af6a6089eed44e6bf55f839a20992791119a5bec318d664c3778190fd1e8888cdbdfcc5c4d52664c33675a47
                        )

                )

        )

    [theme-example] => Array
        (
            [INVALID_HASH] => Array
                (
                    [appinfo/info.xml] => Array
                        (
                            [expected] => 74828fca6b4b3459c6a2e2db9b1011bec5692828e7987f3896a86d3d622dded453d0ecc8bd1291181b138512f0a3b2efce992adae004f2748596301aa90089d1
                            [current] => 42e4ff2e7dac207234ff19fc7f7ac2acbee391de365fccf74970c6e146bd19482b0138261d14322d724e2752389789468489e20586fd885ecacd2063b2c5f480
                        )

                    [core/css/styles.css] => Array
                        (
                            [expected] => 7cf53b4a99f280427376280c0fdb925a52e64e84fe70c83f5988a08a332bd99eab0d4824598b9882671bc2f06076f589b276e2c40ddc424a8a3a613c4d7920ad
                            [current] => 04db95c73c59d0127178f1c576aad64d37ffe1ebdfa83a4522d3656224428d38774fb35793ecb273112ecb20338e097740911dcac6e443884045d78bcae13908
                        )

                    [defaults.php] => Array
                        (
                            [expected] => 580ff0ccb3b36ffed0d65ec6913d2e8db516b0824cb1764b62b94cc59f9e577be2cc6a641d7976e9f5a370bb911a37932374f300245c8e86ac09ad8776ec8831
                            [current] => 858f422f90b4349e1bb4364e03315493a277d99ec861684e87dad810300342eb8bc3ce3a1b122d767a17171da815dba424af33ce3588490e86d17ada7e0ea13b
                        )

                )

        )

)

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ock0w523fppa",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "SOMETHING.COM",
            "SOMETHING.COM"
        ],
        "datadirectory": "\/home\/USER\/DIR\/DIR\/data",
        "overwrite.cli.url": "http:\/\/SOMETHING",
        "dbtype": "mysql",
        "version": "10.0.8.5",
        "dbname": "SOMETHING",
        "dbhost": "SOMETHING",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "2525",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 3,
        "theme": "",
        "debug": true,
        "ldapIgnoreNamingRules": false,
        "maintenance": false
    }
}

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well-sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
YES i have added external hdd in server /media/sda1
**Are you using encryption:** yes/no
NO
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** firefox 60.0.2 (64-bit)

**Operating system:**
Any
#### Web server error log
```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
[owncloud.log](https://github.com/owncloud/core/files/2098044/owncloud.log)
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/8697 (Cannot create new text or folders and cannot upload files), https://github.com/owncloud/core/issues/26486 (Can't delete folder or files and can't create new folder but can upload files from web), https://github.com/owncloud/core/issues/1775 (Not possible to create folders on IE9), https://github.com/owncloud/core/issues/7699 (Upload failed. Could not get file info.), and https://github.com/owncloud/core/issues/12145 (Users cannot delete folders or files they create ).

**Comment by PVince81** [comment]
please first delete the source code and extract the tarball again.

the integrity check tells that many source code files do not have the correct version, this is very likely what is causing this bad behavior.

Not an ownCloud bug. If problem still happening after solving the integrity check errors with the correct source code, please reopen.

You can also seek help on http://central.owncloud.org/
