### ISSUE TITLE
10.0.9Beta Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/core#31769]
Error message appears during / after installation

### Steps to reproduce
1. download 10.0.9 beta and install via docker containers with mysql

### Expected behaviour
no error message

### Actual behaviour
```
owncloud_1  | {"reqId":"rXR3DD5KnhfQCccjeQfl","level":3,"time":"2018-06-13T16:52:13+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Invalid argument supplied for foreach() at \/var\/www\/owncloud\/lib\/private\/DB\/MigrationService.php#395"}
```

### Server configuration
`owncloud/base` docker images

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/9745 ([RC3] Invalid argument supplied for foreach() at /var/www/owncloud/settings/ajax/createuser.php#39), https://github.com/owncloud/core/issues/18849 (Memcached broken, invalid argument supplied for foreach()), https://github.com/owncloud/core/issues/9829 (php invalid argument supplied error in ldap module), https://github.com/owncloud/core/pull/30535 (Merge Hotfix 10.0.7 back to stable10), and https://github.com/owncloud/core/issues/29915 (OwnCloud 10.0.4 Upgrade Failure).
