### ISSUE TITLE
Disable 'Enable previews' option do not stop showing the thumbnails for an external storage mountpoint

### ISSUE THREAD

**Issue by davitol** [owncloud/core#31763]
### Steps to reproduce

1 - Via webUI create a mountpoint e.g. a SMB one
2 - Browse to the Files view --> mountpoint and check the content (thumbnails are available)
3 - Browse back to the configuration and Unmark 'Enable previews' option
4 - Browse to the Files view --> mountpoint and check the content.
5 - Upload an image from your computer
6 - Using text editor create a file and edit it.

### Expected behaviour

The thumbnails should not be available

### Actual behaviour

The thumbnails are shown

![screen shot 2018-06-13 at 16 58 28](https://user-images.githubusercontent.com/10596560/41362486-cde54022-6f31-11e8-992b-378de1cab075.png)

![screen shot 2018-06-13 at 17 47 33](https://user-images.githubusercontent.com/10596560/41362637-278a04b4-6f32-11e8-8af0-58f4beaf48e7.png)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1

**ownCloud version:**

ownCloud stable10 from 13 june 2018

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
No logs in owncloud.log
```

### Client configuration

**browser**

Firefox

**Comment by patrickjahns** [comment]
Looking at the picture - I see that for "alonso.txt" no preview was generated - which of the txt files was created after you have changed it?

**Comment by davitol** [comment]
alonso.txt has no content. That's why it has no preview.
Claseburgos.jpeg was uploaded from local
caca.txt was the new file.txt

**Comment by patrickjahns** [comment]
@davitol 

tested on 10.0.8 - steps done - behavior observed
1) create a mount ( local ) - enabled preview generation (mounted `/tmp` folder)
2) navigate to tmp 
3) upload "krieg-der-welten.jpg" -> see preview being generated
4) navigato to admin mounts - disable preview generation
5) navigate to tmp folder
6) upload file "jenkins.png" -> no preview generated - nut preview of "krieg-der-welten" is still available 

Needs testing with beta release to confirm if the regression was introduced recently

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/23277 (disable external storages), https://github.com/owncloud/core/issues/21646 (Using an external storage mountpoint, unchecking previews checkbox should disable the file previews), https://github.com/owncloud/core/issues/9052 (Do not show delete icon for global external storage mounts), https://github.com/owncloud/core/issues/12216 (config option for external storage), and https://github.com/owncloud/core/issues/10198 (External Only Storage).

**Comment by davitol** [comment]
> Tested on 10.0.8 - steps done - behavior observed

Just tested in 10.0.8 and cannot reproduce it too, so probably a regression introduced recently

**Comment by patrickjahns** [comment]
@PVince81 - moving to QA - as this is a regression introduced from 10.0.8 to 10.0.9beta

**Comment by davitol** [comment]
@PVince81 ```'enable_previews' => false,``` works fine

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/core/pull/31785
