### ISSUE TITLE
Favorite files are not shown after editing one and refreshing

### ISSUE THREAD

**Issue by davitol** [owncloud/core#31780]
### Steps to reproduce

1 - Create a file.txt
2 - Favorite it
3 - Go to favorite section
4 - Refresh the browser.

### Expected behaviour

Favorites files should be shown.

### Actual behaviour

Favorites are no longer listed. You have to go back to files view in order to 'normalize' the view

![corefav](https://user-images.githubusercontent.com/10596560/41407090-b01b878e-6fce-11e8-8d33-f79a2a438dba.gif)

(no need to edit it)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1

**ownCloud version:**

ownCloud 10.0.9.Beta. Also checked in 10.0.6 and also happens.

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
No logs in owncloud.log
```

### Client configuration

**browser**

Firefox

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/13883 (Files External: Available For not showing after refresh), https://github.com/owncloud/core/issues/15167 (File disappears from search results after having been edited), https://github.com/owncloud/core/issues/5126 (Sharing: Shared *file* can not be edited.), https://github.com/owncloud/core/issues/16389 (Files In Folders Got Deleted After refresh .), and https://github.com/owncloud/core/issues/1845 (Not possible to edit a txt file after creating it).

**Comment by phil-davis** [comment]
If I am logged out and try to browse directly to the favorites URL:
```
http://172.17.0.1:8080/index.php/apps/files/?dir=/&view=favorites
```
then it correctly redirects to the login page, I login, it redirects to the favorites page, and the favorites are listed.

Then if I refresh the page, the favorites list is empty (like @davitol describes).

Might be a clue there for someone de-bugging this?

I tested with current core ``master`` - so the problem is not magically fixed in core ``master``
