### ISSUE TITLE
togglegroups.php ajax controller does not error if not added to group

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#31787]
If no group supports adding to a group, then it is just assumed it was added anyway: https://github.com/owncloud/core/blob/master/lib/private/Group/Group.php#L169

This breaks the user management which has no idea if it was sucessful or not.
https://github.com/owncloud/user_management/blob/master/ajax/togglegroups.php#L79-L83

Breaks the add member command as well: https://github.com/owncloud/core/blob/master/core/Command/Group/AddMember.php#L86

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @butonic, and @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/28840 (-Error-), https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/17420 (Adding a user to a group does not manipulate the user count), https://github.com/owncloud/core/issues/5841 ([OC6Beta4] Add new user with group -- group menu doesn't recover), and https://github.com/owncloud/core/issues/29082 (a Error).
