### ISSUE TITLE
WebDav COPY to shared folder successful, but should not (share permissions) 

### ISSUE THREAD

**Issue by mrow4a** [owncloud/core#31789]
Smashbox fails in the test `lib/oc-tests/test_sharePermissions.py -t 6` https://github.com/owncloud/smashbox/blob/master/lib/oc-tests/test_sharePermissions.py#L169

The use case is that shared folder is create with permissions `OCS_PERMISSION_READ | OCS_PERMISSION_UPDATE` and thus allowed operations are `upload_overwrite` and `rename`

However, operation ` 'copy_in_overwrite' -   # copy a file from outside the shared folder and overwrite a file inside the shared folder (note: SabreDAV automatically deletes the target file first before copying, so requires DELETE permission too)` is successful. 

### How did I test?

- v10.0.7 **works**
- v.10.08 **works**
- master **test fails**

@patrickjahns @PVince81

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/9399 ([webdav]It is possible to rename, move a shared file/folder when the user doesn’t have permission), https://github.com/owncloud/core/issues/11284 (WebDAV Permissions report wrong Sharing permissions), https://github.com/owncloud/core/issues/21379 (OSX Webdav share, still no upload, folder add, etc), https://github.com/owncloud/core/issues/181 (Writing to WebDAV shared folder is not working), and https://github.com/owncloud/core/issues/11433 ([Sharing] Not possible to share after having shared a folder).

**Comment by patrickjahns** [comment]
Why master and not stable10? Please test on stable10

**Comment by mrow4a** [comment]
I started debugging the issue, I found out that this copy gets called via block 

```
{"type":"EVENT","reqId":"WR3EnirXV7tPCb8ynMpS","diagnostics":{"eventDescription":"store-versions-copy","eventDurationmsec":1529006092538.938,"eventTimestamp":0}}
{"type":"EVENT","reqId":"WR3EnirXV7tPCb8ynMpS","diagnostics":{"eventDescription":"view-copy","eventDurationmsec":1529006092539.071,"eventTimestamp":0}}
{"type":"SUMMARY","reqId":"WR3EnirXV7tPCb8ynMpS","time":"2018-06-14T19:54:52+00:00","remoteAddr":"::1","user":"test_sharePermissions2","method":"COPY","url":"\/octest\/remote.php\/webdav\/overwrite_this_through_copy_in.dat","diagnostics":{"totalSQLQueries":88,"totalSQLDurationmsec":26.666879653930664,"totalSQLParams":207,"totalEvents":19,"totalEventsDurationmsec":4587018277664.492}}
```

View ->copy() -https://github.com/owncloud/core/blob/4702ff202124b6d7021d84c587738da5ba3cb278/lib/private/Files/View.php#L893 - gets called from FilesVersions ->store() - https://github.com/owncloud/core/blob/57d7f9a54f7729f38666e4b26e4a912e035b496e/apps/files_versions/lib/Storage.php#L204

This in turn is triggered by write_hook (https://github.com/owncloud/core/blob/5f0af496626b957aff38730b5771ec0a33effe31/apps/files_versions/lib/Hooks.php#L55)

**Comment by mrow4a** [comment]
Ok.. this calls just normal PUT.. in File.php

**Comment by mrow4a** [comment]
I pleased some debugging in the httpCopy (https://github.com/owncloud/core/blame/a6056dca796e5e352c957592396f87f19aab867c/apps/dav/lib/DAV/CopyPlugin.php#L67)
```
	public function httpCopy(RequestInterface $request, ResponseInterface $response) {
		try {
			$path = $request->getPath();

			\OC::$server->getEventLogger()->log(rand(), 'http-copy-prepare', 0, 0);

			$copyInfo = $this->server->getCopyAndMoveInfo($request);
			$sourceNode = $this->server->tree->getNodeForPath($path);
			$destinationNode = $copyInfo['destinationNode'];
			if (!$copyInfo['destinationExists'] || !$destinationNode instanceof File || !$sourceNode instanceof IFile) {
				return true;
			}

			if (!$this->server->emit('beforeBind', [$copyInfo['destination']])) {
				return false;
			}

			\OC::$server->getEventLogger()->log(rand(), 'http-copy-start', 0, 0);
			$copySuccess = false;
			\OC::$server->getEventLogger()->log(rand(), 'http-copy-node-'.get_class($sourceNode), 0, 0);
			if ($sourceNode instanceof ICopySource) {
				\OC::$server->getEventLogger()->log(rand(), 'http-copy-copy', 0, 0);
				$copySuccess = $sourceNode->copy($destinationNode->getFileInfo()->getPath());
			}
			if (!$copySuccess) {
				\OC::$server->getEventLogger()->log(rand(), 'http-copy-put', 0, 0);
				$destinationNode->acquireLock(ILockingProvider::LOCK_SHARED);
				$destinationNode->put($sourceNode->get());
				$destinationNode->releaseLock(ILockingProvider::LOCK_SHARED);
			}

			\OC::$server->getEventLogger()->log(rand(), 'http-copy-finish', 0, 0);
			$this->server->emit('afterBind', [$copyInfo['destination']]);

			$response->setHeader('Content-Length', '0');
			$response->setStatus(204);

			// Sending back false will interrupt the event chain and tell the server
			// we've handled this method.
			return false;
		} catch (ForbiddenException $ex) {
			throw new Forbidden($ex->getMessage(), $ex->getRetry());
		}
	}
```

The timeline is:
```
http-copy-prepare
http-copy-start
http-copy-node-OCA\\DAV\\Connector\\Sabre\\File
http-copy-put
```

It means, that COPY does not get executed, and PUT is done instead! @PVince81 @DeepDiver1975 @patrickjahns 

Regression introduced by this PR (https://github.com/owncloud/core/commit/630b0a07cb5cb388c174aa8f1774aba0dd9ce556)

**Comment by mrow4a** [comment]
CorePlugin in 10.0.8
```
    function httpCopy(RequestInterface $request, ResponseInterface $response) {

        $path = $request->getPath();

        $copyInfo = $this->server->getCopyAndMoveInfo($request);

        if (!$this->server->emit('beforeBind', [$copyInfo['destination']])) return false;
        if ($copyInfo['destinationExists']) {
            if (!$this->server->emit('beforeUnbind', [$copyInfo['destination']])) return false;
            $this->server->tree->delete($copyInfo['destination']);
        }

        $this->server->tree->copy($path, $copyInfo['destination']);
        $this->server->emit('afterBind', [$copyInfo['destination']]);

        // If a resource was overwritten we should send a 204, otherwise a 201
        $response->setHeader('Content-Length', '0');
        $response->setStatus($copyInfo['destinationExists'] ? 204 : 201);

        // Sending back false will interrupt the event chain and tell the server
        // we've handled this method.
        return false;
    }
```

CorePlugin in 10.0.9:
```
	public function httpCopy(RequestInterface $request, ResponseInterface $response) {
		try {
			$path = $request->getPath();

			$copyInfo = $this->server->getCopyAndMoveInfo($request);
			$sourceNode = $this->server->tree->getNodeForPath($path);
			$destinationNode = $copyInfo['destinationNode'];
			if (!$copyInfo['destinationExists'] || !$destinationNode instanceof File || !$sourceNode instanceof IFile) {
				return true;
			}

			if (!$this->server->emit('beforeBind', [$copyInfo['destination']])) {
				return false;
			}

			$copySuccess = false;
			if ($sourceNode instanceof ICopySource) {
				$copySuccess = $sourceNode->copy($destinationNode->getFileInfo()->getPath());
			}
			if (!$copySuccess) {
				$destinationNode->acquireLock(ILockingProvider::LOCK_SHARED);
				$destinationNode->put($sourceNode->get());
				$destinationNode->releaseLock(ILockingProvider::LOCK_SHARED);
			}

			$this->server->emit('afterBind', [$copyInfo['destination']]);

			$response->setHeader('Content-Length', '0');
			$response->setStatus(204);

			// Sending back false will interrupt the event chain and tell the server
			// we've handled this method.
			return false;
		} catch (ForbiddenException $ex) {
			throw new Forbidden($ex->getMessage(), $ex->getRetry());
		}
	}
```

**Comment by mrow4a** [comment]
According to protocol defined in smashbox, we should first delete if destination exists (10.0.8), and then copy. In 10.0.9 we do overwrite, and because of that explode the smashbox test

We need to decide whether we want to expect on COPY delete rights, or update are enought (in 10.0.8 COPY expected delete rights, as well as update)

How to fix? Add delete to implementation, or change the protocol check in smashbox

@PVince81 @patrickjahns @DeepDiver1975

**Comment by patrickjahns** [comment]
@PVince81 - raised priority to being a release blocker for now - if we have more feedback we can decrease again

**Comment by PVince81** [comment]
@mrow4a assuming we're talking about the new DAV endpoint ?

I remember finding some issues there a while ago: https://github.com/owncloud/core/issues/29561 and https://github.com/owncloud/core/issues/29224, likely unrelated.

**Comment by PVince81** [comment]
Hmmm, this https://github.com/owncloud/core/issues/25387 was the opposite behavior. So something got rid of the implicit delete.

I seem to remember we added code to skip implicit because it broke something.

I'll bisect this to find out about said reason.

**Comment by PVince81** [comment]
note: we should at some point port these tests to acceptance test (back then there were no acceptance tests at all when I wrote this): https://github.com/owncloud/QA/issues/278

**Comment by PVince81** [comment]
Breaking commit, indeed related to COPY: 745a3fff7a0ecbd403668402b3cc6d408310a41b from https://github.com/owncloud/core/pull/31050 and originally from https://github.com/owncloud/core/pull/29257/commits

At this point I'd vote for no change in permissions behavior so we might need to add a check for delete permissions there.

**Comment by PVince81** [comment]
Note: many of these permissions logic were taken by me from existing code without trying to make them make sense. At some point we can think about revisiting permissions and making them more consistent with the actions.

**Comment by PVince81** [comment]
- [ ] to clarify: does restoring a version also require "delete" permissions ?

**Comment by PVince81** [comment]
PR here: https://github.com/owncloud/core/pull/31796

**Comment by PVince81** [comment]
Testing restore:

1. create two users "user1" and "user2"
1. login as "user1"
1. create a folder "test"
1. create a file "test/file.txt" and edit several times to create versions
1. share "test" with "user2" and remove "delete" permission
1. login as "user2"
1. restore a former version of "test/file.txt"

Works on v10.0.8 and stable10, so no change of behavior there.

On my PR the behavior is the same.

Nothing to do here for version restoration.

**Comment by PVince81** [comment]
A better fix here that will likely break even less things: https://github.com/owncloud/core/pull/31805
