### ISSUE TITLE
syntax error in CalDavBackend.php and CardDavBackend.php

### ISSUE THREAD

**Issue by cscheiber** [owncloud/core#31786]
OwnCloud 10.0.8.5, Community Edition
Calendar App 1.5.7
Contacts App 1.5.4
Hosted at 1&1, PHP version 7.2 (same issue for 7.1 and 7.0)
Jobs are executed via Cron-Job

PHP.INI from 1&1:
- PHP 7.2
- Zend Framework v3.2.0

After the upgrade the cron job started to fail and to report the following PHP syntax error (without any code modification of course):

"message":"syntax error, unexpected '.' at  ..... oc\/apps\/dav\/lib\/CardDAV\/CardDavBackend.php#498"}
later (after a manual fix) also this
"message":"syntax error, unexpected '.' at ...... oc\/apps\/dav\/lib\/CalDAV\/CalDavBackend.php#806"}

In both cases the last line of public function `getMultipleCards` and `getMultipleCalendarObjects`

```bash
public function getMultipleCards($addressBookId, array $uris) {

    return \array_merge(...$results);
}
```

I am not a PHP expert, but I replaced the line in both cases like shown here

```bash
public function getMultipleCards($addressBookId, array $uris) {

    return call_user_func_array('array_merge', $results);
}
```

Now it works, but ... probably I did not hit these lines as the data volume is smaller than the allowed chunk size 998 (?)

I thought it would be important enough to bring it directly up as issue here.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @DeepDiver1975.

Possibly related issues are https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/28840 (-Error-), https://github.com/owncloud/core/issues/29082 (a Error), https://github.com/owncloud/core/issues/20506 (Error PHP (appframework)), and https://github.com/owncloud/core/issues/3699 (Fatal PHP Error).

**Comment by phil-davis** [comment]
That change happened in https://github.com/owncloud/core/commit/b06fe9e7909f3445a0f6f45c1befee6717bad893#diff-ded00a57c79a474ac4c4b43c620d6050R806

What is that ``(...$x)`` syntax?

**Comment by DeepDiver1975** [comment]
> What is that (...$x) syntax?

splat operator - part of the syntax since 5.6 - http://php.net/manual/en/migration56.new-features.php

**Comment by cscheiber** [comment]
Knowing this, I contacted 1&1 support. And it turns out, even if in the WebSpace PHP 7.2.5 is used (and recommended) all cron jobs still run with PHP 5.4 in the environment! They are working on that.

Might be a problem for each OC instance at 1&1 Web-Hosting using cron.
