### ISSUE TITLE
Version thumbnails don't appear any more

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31797]
### Steps

1. Login as "admin"
1. Create a file "test.txt" and edit several times to create versions
1. Open the "Versions" tab in the sidebar
1. Look at preview thumbnails

### Expected results
Thumbnails match

### Actual result
Thumbnail shows broken image, Internal server error.

### Version
stable10, happens after https://github.com/owncloud/core/pull/31785

### Log
```
{"reqId":"Uub58ileGe1ug8H1VAoT","level":4,"time":"2018-06-15T10:22:40+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"webdav","method":"GET","url":"\/owncloud\/remote.php\/dav\/meta\/15\/v\/1529057520?preview","message":"Exception: : {\"Exception\":\"OCP\\\\Files\\\\NotPermittedException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"
#0 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/PreviewManager.php(207): OC\\\\Files\\\\Node\\\\AbstractNode->getMountPoint()\\n
#1 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Files\\\/PreviewPlugin.php(111): OC\\\\PreviewManager->isAvailable(Object(OC\\\\Files\\\\Meta\\\\MetaFileVersionNode))\\n
#2 [internal function]: OCA\\\\DAV\\\\Files\\\\PreviewPlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#3 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n
#4 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n
#5 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n
#6 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(281): Sabre\\\\DAV\\\\Server->exec()\\n
#7 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n
#8 \\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/remote.php(165): require_once('\\\/srv\\\/www\\\/htdocs...')\\n
#9 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/AbstractNode.php\",\"Line\":84}"}
```

**Comment by PVince81** [comment]
Since https://github.com/owncloud/core/pull/31785 we're checking if the file node mount point is stored on an external storage.

In the versions case it's a `MetaFileVersionNode` which throws `NotPermittedException`, so we currently cannot check if the original file is on a mount point.

Two possible approaches:
- Approach 1: make PreviewManager somehow resolve back to the original node of the real file (not the version)
- Approach 2: make PreviewPlugin go back to the real file and call `isAvailable` on that

cc @DeepDiver1975

**Comment by PVince81** [comment]
- Approach 3: make the MetaFileVersionNode->getMountPoint() return the mount point of the original file. This implies that in the future we don't consider storing versions on different mount points, storages

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/28115 (Thumbnails are not shown in the version section), https://github.com/owncloud/core/issues/10559 (Thumbnails not regenerated when reverting to an earlier version of a file), https://github.com/owncloud/core/issues/18340 (No ldap user appears), https://github.com/owncloud/core/issues/4694 (there are no thumbnails for SVG files), and https://github.com/owncloud/core/issues/205 (Files: thumbnails).
