### ISSUE TITLE
ugly copy-paste required for themed footers

### ISSUE THREAD

**Issue by VicDeo** [owncloud/core#31806]
The current implementation doesnot allow anything better than 
https://github.com/owncloud/theme-example/pull/2

Possible improvements:
- a separate public utility class with getPrivacyPolicyUrl and getImprintUrl
- a public base class that provides these methods and all themes that need this feature should extend it
- ?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/3209 (Theming), https://github.com/owncloud/core/issues/27411 (Bug with creating folder when copy-pasting the name), https://github.com/owncloud/core/issues/22237 (Theming issues), https://github.com/owncloud/core/issues/3662 (Issues with themes), and https://github.com/owncloud/core/issues/4605 (Theme problem).
