### ISSUE TITLE
"mountConfigLoaded" event triggered twice in the personal page

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#31814]
### Steps to reproduce
1. Modify the file "apps/files_external/js/settings.js" to include something like around line 1430
    ```
    $("#body-settings").on("mountConfigLoaded", function(ev){
      console.log('config loaded');
      console.log(ev);
    })
    ```
2. Make sure you have at least one mount point configured by the admin and another personal
3. Go to the personal settings page
4. Check the console logs.

### Expected behaviour
Only one event should be reported. The event should be triggered when both personal and admin mount points are loaded

### Actual behaviour
Two events are triggered

![screen shot 2018-06-18 at 09 31 27](https://user-images.githubusercontent.com/1477829/41523496-7a3d6c22-72da-11e8-9585-35cdc97a7298.png)

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** apache 2.4

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** master code (10.1 prealpha) at 9edd97a, very likely in 10.0.x too

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/19711 (scanFile event gets triggered on directories), https://github.com/owncloud/core/issues/6398 (Provide Admin more control over personal page), https://github.com/owncloud/core/issues/20455 (Full name is not shown just after modifying it in the Personal Page), https://github.com/owncloud/core/pull/31033 (Remove "Unlimited" from quota report in personal page), and https://github.com/owncloud/core/issues/17528 (Prevent closing upgrade page while upgrade in progress).

**Comment by davitol** [comment]
@pmaier1 JFYI. We should decide if we must fix this stuff for next oC 10.0.10 version. After talking with @jvillafanez his opinion is that it will be worthy to dedicate time for this fix for the next release.

**Comment by PVince81** [comment]
@jvillafanez how much time needed for this issue + unit test ?

**Comment by PVince81** [comment]
this could potentially have an impact on external storages that use OAuth and rely on this event, so might need to retest GDrive and Dropbox at least

**Comment by jvillafanez** [comment]
I'd say around 3md for both dev and unittest, QA not included. Between 3-4md including some basic test for GDrive and Dropbox.

**Comment by PVince81** [comment]
@jvillafanez that's a lot more than I expected. Any risks you have in mind that I'm not aware of ?

**Comment by jvillafanez** [comment]
Since there are apps depending on this event to work properly, we should make sure it works flawlessly. The extra time is to verify this thoroughly.
Anyway, I'm fine with 2-3md instead of 3-4md
