### ISSUE TITLE
[Feature Request] folder labels/readme

### ISSUE THREAD

**Issue by lefherz** [owncloud/core#31815]
If you have shared folders, where multiple users collaborate on, usually chaos emerges. There tend to be some unwritten rules for folders, a useful structure, classification levels etc.

If you could give such folders labels, which would be shown in the web interface, you could bring some order into them. GitHub has a similar mechanism with README.md - if you view a directory and there is a file named README.md, it is used as a display/explanation of the project/directory.

This would make collaboration on shared folders much easier and would be an advantage to other File Sync & Share software, too.

@pmaier1 what do you think?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/12530 (Feature Request), https://github.com/owncloud/core/issues/8569 (Feature requests), https://github.com/owncloud/core/issues/10089 ([feature request] WLAN folder/all auto-sync), https://github.com/owncloud/core/issues/7181 ([FEATURE REQUEST]: Provide admin ability to configure initial display folder), and https://github.com/owncloud/core/issues/249 (Etherpad support - Feature request).
