### ISSUE TITLE
Group administration views not working with space char in group name

### ISSUE THREAD

**Issue by jochenwezel** [owncloud/core#31812]
I've created some groups. Group views work if they don't contain a space character in the group name.
![image](https://user-images.githubusercontent.com/3033827/41419377-2628ea66-6ff2-11e8-8f51-a8aa3ffd04d5.png)

### Expected behaviour
The group "CM Staff" in screenshot above should contain 6 users and show them in the list.

### Actual behaviour
As soon as I've got a space char in the group name, the group view doesn't list any users any more.
The group "CM Staff" in screenshot above should contain 6 users, but the list is empty.
Other groups without space chars in group name work as expected.

### Server configuration
Operating system: Ubuntu

Web server: Apache

Database:

PHP version:

ownCloud version: 10.0.8

Storage backend (external storage):

### Client configuration
Client version: Google Chrome Browser

Operating system: Windows

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/6657 (can't sync calendar with special char in calendar name), https://github.com/owncloud/core/issues/29279 (cannot share with a user that has the same name as a group), https://github.com/owncloud/core/issues/3267 (Which groups am I in?), https://github.com/owncloud/core/issues/22845 (space in the directory name), and https://github.com/owncloud/core/issues/5010 (LDAP groups mapping not working ).

**Comment by phil-davis** [comment]
Thanks gitmate, a genius suggestion, since I already gave you a clue by commenting :)
AI exceeds [all|no] expectations.

**Comment by va1entin** [comment]
Still an issue with Owncloud 10.0.9

It seems OCC can't handle spaces either, even with correct escaping:
<pre>
root@owncl-66241678: /var/www/owncloud # occ group:list
  - Test Gruppe
  - admin
  - Domain Admins
  - Domain Users

root@owncl-66241678: /var/www/owncloud # occ group:list-members admin        
  - Administrator: Administrator
  - owncloud: owncloud

root@owncl-66241678: /var/www/owncloud # occ group:list-members "Domain Users"

                                                             
  Too many arguments, expected arguments "command" "group".  
                                                             

group:list-members [--output [OUTPUT]] [--] <group>


root@owncl-66241678: /var/www/owncloud # occ group:list-members Domain\ Users 

                                                             
  Too many arguments, expected arguments "command" "group".  
                                                             

group:list-members [--output [OUTPUT]] [--] <group>


root@owncl-66241678: /var/www/owncloud # occ group:list-members 'Domain Users'

                                                             
  Too many arguments, expected arguments "command" "group".  
                                                             

group:list-members [--output [OUTPUT]] [--] <group>

</pre>

**Comment by karakayasemi** [comment]
Everything is working as expected in 10.3.0. I tested with group name having 2 spaces in both occ and web UI.
