### ISSUE TITLE
Update the Policy for SwiftMailer

### ISSUE THREAD

**Issue by mdisrail2468** [owncloud/core#31821]
Hello Team,

During my regular testing, I take a look to the composer.json file and from that, I got to know you are using Swiftmailer and the command line which you are using there is "swiftmailer/swiftmailer": "^5.4".

Where the ^ operator behaves as ^5.4 is equivalent to >=5.4 <6.0, agree?

But the issue over here is you are using PHP 7.1 and this particular land version is compatible with php: >=5.3.3. The latest version of swiftmailer is version 6.0.2 which comes with a bunch of fixes, updates and changes.

Here you are creating a scene of ambiguity by these. In a nutshell, you are blocking the users to use the latest version of swiftmailer.

Reference: https://github.com/swiftmailer/swiftmailer/blob/master/CHANGES
https://swiftmailer.symfony.com/

Please investigate, whether this can be fixed in the upcoming release. 

Thanks & Regards,
Mohammed Israil

**Comment by DeepDiver1975** [comment]
We are pinning swiftmailer to version 5.4.9 which fulfills all necessary requirements.
https://github.com/owncloud/core/blob/c8784f7eaa82ca1a7be61bb95161860e3083054e/composer.lock#L2464

**Comment by mdisrail2468** [comment]
Thanks for the quick response.

Anyways, using the latest version which is more compatible with the code is not a bad idea.
