### ISSUE TITLE
Exclude group from sharing behavior adjustment doesn't apply everywhere

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31820]
Following https://github.com/owncloud/core/pull/31490 the behavior was changed.

However not all code paths were adjusted.

This PR adjusts it: https://github.com/owncloud/core/pull/31819

- [ ] find reproduction tests for acceptance tests

### Steps
TODO

### Expected
TODO

### Actual
TODO

### Version
ownCloud Server 10.0.9 beta

@phil-davis FYI

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/10307 (Exclude Groups from Sharing), https://github.com/owncloud/core/pull/31490 (Exclude users from sharing if they are a member of any excluded group), https://github.com/owncloud/core/issues/7272 (Exclude subfolder from sharing), https://github.com/owncloud/core/issues/17346 (Exclude group from sharing after a share was created), and https://github.com/owncloud/core/issues/25320 ('Exclude groups from sharing'  doesn't work if user belongs to more groups).
