### ISSUE TITLE
Exact match when sharing is only on UID

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#31831]
### Steps to reproduce
1. Set in ``config.php``
```
'user.search_min_length' => '4',
```

2. Create user ``new`` with display name "Jim" and email address ``a@b``
3. Try to share a file, type in ``new`` - the user ``Jim`` is shown as an exact match suggestion - good
4. Type in "Jim" or "jim" - no match is shown - not good
5. Type in "a@b" - no match is shown - theoretically not good, in practice email addresses are never this short.

If you set:
```
'user.search_min_length' => '2',
```
and type "jim" or "a@b" in the sharing box, then it happily shows "Jim" as a match - so when such strings are greater than search_min_length, then the backend is providing matches on display name and email address.

### Expected behaviour
An exact match lookup should return an exact match on display name or email address, as well as on UID.

### Actual behaviour
An exact match for a short string is only returning an exact match on UID.

### Server configuration
**Operating system**:
Ubuntu 18.04

**Web server:**
PHP dev server

**Database:**
mySQL

**PHP version:**
v7.2.5 (problem is no different than on PHP 7.1 etc)

**ownCloud version:** (see ownCloud admin page)
10.0.9RC1
10.0.8.5
(same behavior on both versions)

**Updated from an older ownCloud or fresh install:**
Fresh

**Where did you install ownCloud from:**
tarball

**Comment by phil-davis** [comment]
This only becomes a problem if the sysadmin sets ``user.search_min_length`` to a "large" value and there are users on the system with shorter display name and/or email address. It becomes difficult to share with those users.

**Comment by phil-davis** [comment]
See #31117 for a slightly different way this impacts ``occ user:list``

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/765 (Sharing error), https://github.com/owncloud/core/issues/9918 (Calendar share), https://github.com/owncloud/core/issues/7380 (Contact sharing), https://github.com/owncloud/core/issues/5401 (Sharing completion), and https://github.com/owncloud/core/issues/3465 (Sharing files).

**Comment by PVince81** [comment]
Good point. It is possible that with LDAP you can specify the LDAP search string to make it exact match whatever you want.

Like you said we should consider to also exact match display name and email. I'm not sure if this is a bug or enhancement. Tagging as bug for now.

@pmaier1

**Comment by phil-davis** [comment]
> I'm not sure if this is a bug or enhancement

or feature ;)
