### ISSUE TITLE
Group names containing vertical bar cannot be used in "exclude groups from sharing"

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#31836]
### Steps to reproduce
1. create a group named ``vertical|bar``
2. put some users in it (just for fun)
3. admin, settings, sharing, enable "Exclude groups from sharing"
4. In the box, type the group ``vertical|bar`` and then exxit the box (to save)
5. refresh the page

### Expected behaviour
Group ``vertical|bar`` should be shown in the list of excluded groups.

Also note: on the user management page, the users in group ``vertical|bar`` do not show.

### Actual behaviour
Groups ``vertical`` and ``bar`` are shown as separate group names.

### Server configuration
Current core ``stable10``

Note: because of issue #31739 the whole "exclude groups from sharing" UI is broken in core ``master``
So you currently have to use ``stable10`` to see the issue reported here.

**Comment by phil-davis** [comment]
How many of these "special character in group name" problems are there?
Would anyone ever actually use a vertical bar in a group name?
Should we ban the vertical bar as a character in a group name?
But maybe such group names are valid in LDAP, and so they could come from an LDAP server anyway.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/10307 (Exclude Groups from Sharing), https://github.com/owncloud/core/issues/20473 (If a user belongs to a group that has not been set in the excluded groups from sharing, he can share files), https://github.com/owncloud/core/issues/25320 ('Exclude groups from sharing'  doesn't work if user belongs to more groups), https://github.com/owncloud/core/issues/17346 (Exclude group from sharing after a share was created), and https://github.com/owncloud/core/issues/10983 (Exclude with groups cannot work with groups containing commas).

**Comment by phil-davis** [comment]
Implode with vertical bar separator here:
https://github.com/owncloud/core/blob/master/settings/Panels/Admin/FileSharing.php#L71

**Comment by phil-davis** [comment]
PR https://github.com/owncloud/core/pull/10968 introduced the vertical bar implode code, which is better than the previous comma separator.

The answer to my questions https://github.com/owncloud/core/issues/31836#issuecomment-398613766 will determine the way forward.

**Comment by PVince81** [comment]
From what I heard, all kinds of weird characters can come from various flavors of LDAP servers.

We still do have the option to say "yes, maybe, but OC doesn't support that".

Now with the latest discussions related to special chars in groups, let's include @tomneedham @butonic in the discussion...

**Comment by PVince81** [comment]
the question could also be rephrased: is there any safe character that is guaranteed to never appear in a LDAP group name ? such char could then be used as separator

**Comment by VicDeo** [comment]
use a regex to split the value
For backend it's trivial. For frontend https://stackoverflow.com/a/14334054

groups with `\|` are rarer than with an ordinary pipe

**Comment by phil-davis** [comment]
And when there is a group with `\` then escape that. So 4 groups `group1` `back\slash` `vertical|bar` and `oh\|heck` becomes:
`group1|back\\slash||vertical\bar|oh\\\|heck`
or some similar escaping scheme.
