### ISSUE TITLE
10.0.9RC1 - FINAL smoke test results

### ISSUE THREAD

**Issue by davitol** [owncloud/core#31830]
# Smoke test

**Tester assigned: @davitol** 

## Previous requirements

Prepare two servers with ssl activated and trusted certificates.

Enable LDAP and external storage apps.

Have a LDAP server ready to be used with owncloud.

Have ready two external storages of your choice SMB, SFTP, Dropbox, Google Drive, FTP, S3, ownCloud, local.

## Testing setup

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Enable encryption app and encryption default module | Encryption is enabled correctly |  :ballot_box_with_check: |
2 | Populate owncloud server with users and groups | Users and groups are correctly created |  :ballot_box_with_check: |
3 | Share a folder remotely using federated sharing with admin user of the other server. | folder can be opened in recipient server without problems |  :ballot_box_with_check: |
4 | Set up LDAP, as admin check users. log in with a LDAP user, if possible one with an avatar. | Users are loaded. LDAP user logs in without problems. Avatar is shown if it exists.  |  :ballot_box_with_check: |
5 | Set up two external storages different, disable encryption in one of them.| No errors in this process |  :ballot_box_with_check: |

## Testing functionality

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Share a file using federated sharing from an external unencrypted external storage in server #1 using a LDAP user to the admin user in server #2. | Admin user in server #2 can see the file. |  :ballot_box_with_check: |
2 | Open internet explorer or edge and upload a new avatar for a regular user not LDAP | Interface can be used, avatar is uploaded, check that personal page has a scroll bar and scrolls fine. |  :ballot_box_with_check: |
3 | Upload several files and folders inside external storages, open some. | No problems uploading, files can be downloaded and opened. |  :ballot_box_with_check: |
4 | Delete files inside both external storages. Recover some after from the trashbin. |  Files are correctly deleted and restored. | :ballot_box_with_check: |
5 | Using webdav upload a 100MiB file.| No errors in this process |  :ballot_box_with_check: |

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/29633 (Test Results for Smoke test 9.1.7.RC1), and https://github.com/owncloud/core/issues/29649 (Smoke Test results for 10.0.4 RC1).

**Comment by jesmrec** [comment]
# Smoke test iOS  [DONE]

Device & iOS version: iPhone 6SPlus v11.3
iOS app version: 3.7.5
Server version: 10.0.9RC1
OAuth2 version: 0.2.2
user_shibboleth version: 3.2.0

### Login

Test Case | Expected Result | Result | Related Comment
| :------- | :---------------: | :------ | :-----------------: | 
Login with one account (HTTPS)  | It is possible to access | :white_check_mark: |
Login with one account (HTTP)  | It is possible to access  | :white_check_mark: |
Login with one account (SHIB Autoprovisioned user)|  It is possible to access| :white_check_mark:  |
Login with one account (SHIB SSO user )  | It is posible to access |:white_check_mark: |


### Folder

TestID | Test Case | Steps | Expected Result | Result | Related Comment
------------ | ------------- | ----------- | -------------- | ----- | ------
1 | Create a new folder  | 1. Tap on create a new folder |The folder is created| :white_check_mark: OAuth<br>:white_check_mark: basic<br> |
2 | Create a folder with special character | 1. Tap on create a new folder <br> 2. Use a name with special characters (e.g $%&¨)| The folder is created with special character  | :white_check_mark: OAuth<br>:white_check_mark: basic<br> |
3 | Rename a folder | 1. Create a new folder<br> 2. Rename the folder|  Folder is renamed| :white_check_mark: OAuth<br>:white_check_mark: basic<br>
4 | Move a folder | 1. Create a new folder <br> 2. Move the folder| Folder is moved to the specifield location | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
5 | Upload a file into a folder | 1. Create a new folder <br> 2. Upload a file| File is uploaded into the folder | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
6 | Delete a folder  | 1. Access to a folder, the folder has deep structure inside <br> 2. Download some files <br>3. Select delete that folder  | 2. The files are downloaded<br>3. The folder is removed| :white_check_mark: OAuth<br>:white_check_mark: basic<br>
7| Copy Folder | 1. Long press to copy a folder <br> 2. Select a location to paste | The folder and all its content is copied in the location, and remains too in the original| NA
8 | Share the folder by link | 1. Create a new folder <br>2. Long press to share the folder by link <br>  | The link is generated and works| :white_check_mark: OAuth<br>:white_check_mark: basic<br>
9 | Share the folder by link with pass| 1. Create a new folder <br>2. Long press to share the folder by link <br> 3. Enable the password protection and set a password | The link is generated and only works if the correct password is typed|:white_check_mark: OAuth<br>:white_check_mark: basic<br>
10| Unshare the folder by link | 1. Unshare the folder of previous test cases| The link is no more available |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
11 | Share the folder with users or groups| 1. Create a new folder <br> 2. Long press to share with users/groups <br> 3. Type one user/group to share with |  The user/group can access to the folder | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
12| Unshare the folder with users or groups| 1. Unshare the folder in the previous test case | The folder is not more available for the sharees | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
 

### File

TestID | Test Case | Steps | Expected Result | Result | Related Comment
------------ | ------------- | ------------- | -------------- | ----- | ------
1 | Upload a new file  | 1. Upload a new file | The file is uploaded | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
2 | Upload a file with special character | 1. Upload a new file (e.g f%&¨)| The file is uploaded | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
3 | Rename a file | 1. Create a new file <br> 2. Rename the file | The file is renamed |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
4 | Move a file | 1. Create a new file <br> 2. Move the file | The file is renamed |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
5 | Copy a file  | 1. Create a new file <br> 2. Copy the file | The file is copied to the selected location | NA
6 | Delete a file  | 1. Create a new file <br> 2. Delete the file | The file is deleted |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
7 | Share the file by link | 1. Create a file<br> 2. Long press to share the file by link | The link is generated and works|:white_check_mark: OAuth<br>:white_check_mark: basic<br>
8 | Share the file by link with pass| 1. Create a file<br> 2. Long press to share the file by link <br> 3. Set a password| The link is generated and works when the correct pass is typed|:white_check_mark: OAuth<br>:white_check_mark: basic<br>
9 | Unshare the file by link | 1. Unshare the file of previous test cases |  The link is no more available|:white_check_mark: OAuth<br>:white_check_mark: basic<br>
10 | Share the file with users or groups| 1. Create a new file <br> 2. Long press to share with users/groups <br> 3. Type one user/group to share with |  The user/group can access to the file | :white_check_mark: OAuth<br>:white_check_mark: OAuth<br>:white_check_mark: basic<br>
11| Unshare the file with users or groups| 1. Unshare the file in the previous test case | The file is not more available for the sharees | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
12| Download a file| 1. Tap to download a file | The file is downloaded and marked with green tick|:white_check_mark: OAuth<br>:white_check_mark: basic<br>
13| Av Offline file | 1. Long press to set as av offline a file | The file is downloaded and set as av off with the yellow arrow |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
14| Av Offline file | 1. Long press to set as no av offline a file | The file has no more the yellow arrow | :white_check_mark: OAuth<br>:white_check_mark: basic<br>

**Comment by phil-davis** [comment]
## App password tests

using 10.0.9RC1

### Requirements
- An Android device with a current ownCloud android app installed - ``2.7.0`` was used
- An iOS device with a current ownCloud iOS app installed - ``3.7.5`` was used
- On both devices, have some files available to upload (e.g. take photos)
- ownCloud server running on a (local) network (not just on localhost)

### Common Test Setup
1. Create an ordinary user "test123" with some password "abc123"
2. Create other users and groups so sharing can be done. Make the names >=4 chars to avoid hassle with min search matching.
2. In ``config.php`` set ``'token_auth_enforced' => false,`` (or remove it completely)
3. In a browser, login as user "test123", go to Settings, Personal, Security. Scroll down to App Passwords
4. Enter "my-android" in App name and press "Create new app password". Record the generated app password.
5. Enter "my-ios" in App name and press "Create new app password". Record the generated app password.
6. On the Android device, open the ownCloud app. Connect to the address of the server.
7. For username, enter "test123", for password enter the "my-android" app password.
8. On the iOS device, open the ownCloud app. Connect to the address of the server.
9. For username, enter "test123", for password enter the "my-ios" app password.

### Test App Passwords with token_auth_enforced false
Ensure that ``token_auth_enforced`` is off.
Perform the tests on both Android and iOS apps and the browser as user "test123".

| Test Case | Expected Result | Android Result | iOS Result | Related Comment |
| --------- | --------------- | -------------- | ---------- | --------------- |
| **General Client Functionality** | | | | |
| Login to a browser session              | Browser-based webUI access works | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| View files                              | The skeleton files are displayed on the client | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Download welcome.txt                    | The "Welcome to your ownCloud account!"... text is displayed | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Upload a file                           | The uploaded file can be seen in the browser | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Create a folder and upload a file in it | The file can be seen in the folder in the browser | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Receive a new folder and file           | In the browser, create a new folder with a file in it. The file can be viewed in the client | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Delete a file in the client             | The file is deleted from the browser | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Delete a file in the browser            | The file is gone on the client | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Share a folder on the client            | Look in the browser, the sharing settings are the same as entered in the client | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Create a public link for a folder on the client | Look in the browser, view and copy the public link, browse to the link and confirm it works | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Share a file on the client              | Look in the browser, the sharing settings are the same as entered in the client | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Rename a file on the client             | The file is renamed in the browser | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |

### Test App Passwords with token_auth_enforced true
Logout from the browser
Change ``token_auth_enforced`` to ``true`` in ``config.php``
Perform the tests on both Android and iOS apps and the browser as user "test123".

| Test Case | Expected Result | Android Result | iOS Result | Related Comment |
| --------- | --------------- | -------------- | ---------- | --------------- |
| **General Client Functionality** | | | | |
| Login to a browser session              | Browser-based webUI access works | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| View files                              | The skeleton files are displayed on the client | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Download welcome.txt                    | The "Welcome to your ownCloud account!"... text is displayed | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Upload a file                           | The uploaded file can be seen in the browser | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Create a folder and upload a file in it | The file can be seen in the folder in the browser | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Receive a new folder and file           | In the browser, create a new folder with a file in it. The file can be viewed in the client | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Delete a file in the client             | The file is deleted from the browser | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Delete a file in the browser            | The file is gone on the client | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Share a folder on the client            | Look in the browser, the sharing settings are the same as entered in the client | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Create a public link for a folder on the client | Look in the browser, view and copy the public link, browse to the link and confirm it works | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Share a file on the client              | Look in the browser, the sharing settings are the same as entered in the client | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Rename a file on the client             | The file is renamed in the browser | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |


### Test Using Regular Password with token_auth_enforced true then false
Ensure ``token_auth_enforced`` is ``true`` in ``config.php``
Remove the account in both Android and iOS apps
Perform the tests on both Android and iOS apps and the browser as user "test123".

| Test Case | Expected Result | Android Result | iOS Result | Related Comment |
| --------- | --------------- | -------------- | ---------- | --------------- |
| **General Client Functionality** | | | | |
| Login to a browser session              | Browser-based webUI access works | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Connect to the server using the username and password | Cannot connect | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Change ``token_auth_enforced`` to ``false`` in ``config.php`` |  | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Connect to the server using the username and password | Connect succeeds | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| View files                              | The skeleton files are displayed on the client | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |

### Test Deleting App Passwords
Have the account set up using the app passwords in both Android and iOS apps, and in use.
Perform the tests on both Android and iOS apps and the browser as user "test123".

| Test Case | Expected Result | Android Result | iOS Result | Related Comment |
| --------- | --------------- | -------------- | ---------- | --------------- |
| **Deleting App Passwords** | | | | |
| Login to a browser session and go to settings, personal, security | Check that the app password "most recent activity" is within the last few minutes | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Delete the app password for the client | The App password is no longer listed | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Delete any listed sessions for the clients | Sessions are gone | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| Leave the clients for about 10 minutes | It seems to take some time for memory of valid session cookies... to go away |  |  | |
| On the client, try to upload a file | Upload fails, client goes back to asking for password | <ul><li> - [ ] </li></ul> | <ul><li> - [x] </li></ul> | |
| On the browser, upload a new file | Refresh the client, the new file is not seen | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |

**Comment by phil-davis** [comment]
## Two-factor TOTP tests

using 10.0.9RC1

### Requirements
- An Android device with a current ownCloud android app installed - ``2.7.0`` was used
- An iOS device with a current ownCloud iOS app installed - ``3.7.3`` was used
- On both devices, have some files available to upload (e.g. take photos)
- Install Google Authenticator app on the Android device
- ownCloud server running on a (local) network (not just on localhost)
- twofactor_totp app installed and enabled

### Common Test Setup
1. Create an ordinary user "test123" with some password "abc123"
3. In a browser, login as user "test123", go to Settings, Personal, Security. Scroll down to App Passwords
4. Enter "my-android" in App name and press "Create new app password". Record the generated app password.
5. Enter "my-ios" in App name and press "Create new app password". Record the generated app password.
7. On the Android device, open the ownCloud app. Connect to the address of the server.
8. Enter username "test123" and ordinary password "abc123".
10. On the iOS device, open the ownCloud app. Setup the same account.
11. On both devices, browse the files, upload a file, confirm that they are operational

### Tests
Ensure that ``token_auth_enforced`` is ``false`` or removed from ``config.php``.

| Test Case | Expected Result | Browser or Android Result | iOS Result | Related Comment |
| --------- | --------------- | -------------------------- | ---------- | --------------- |
| Login to a browser session as "test123" | Browser-based webUI access works | <ul><li> - [x] </li></ul> |  | |
| In Settings, Personal, Security activate TOTP | The key and QR code are displayed | <ul><li> - [x] </li></ul> |  | |
| In Google Authenticator, scan the QRcode or enter the key | The app starts showing you 6-digit codes | <ul><li> - [x] </li></ul> |  | |
| In the browser, enter the 6-digit code in "Authentication code" and press "Verify" | The code is successfully verified | <ul><li> - [x] </li></ul> |  | |
| Logout and login again | You are asked for a Time-based One-time Password | <ul><li> - [x] </li></ul> |  | |
| Enter the 6-digit code from Google Authenticator | Login succeeds | <ul><li> - [x] </li></ul> |  | |
| Upload, download some files on the browser | It works | <ul><li> - [x] </li></ul> |  | |
| Remove the account from the devices | Account is removed | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| On the devices, try to setup the account "test123" again using the ordinary password | Password is not valid | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |
| On the devices, setup the account "test123" again using the app password | Can now browse, download, upload files | <ul><li> - [x] </li></ul> | <ul><li> - [x] </li></ul> | |

**Comment by phil-davis** [comment]
## Other Browser Smoke Tests
using 10.0.9RC1

### Edge
Microsoft Edge 42.17134.1.0
Microsoft EdgeHTML 17.17134
Windows 10 

- [x] Create folders, text files
- [x] Upload 1 file, multiple files
- [x] Download file or folder
- [x] Share file/folder and receive share
- [x] Add tags
- [x] Add comments
- [x] Favorite items
- [x] Delete and restore files
- [x] Restore versions

No obvious regressions in Edge webUI behavior.

### IE11

**Comment by phil-davis** [comment]
I hate to admit it, but I also have a Windows10 laptop, that my wife uses. So that makes it easy to do real Edge and IE11  smoke-testing.

**Comment by davitol** [comment]
Smoke Test results, thanks to @thommierother


**Test results for 10.0.9 RC1**

_Server config - OS: Ubuntu 16.04 LTS, Apache 2.4.x, MariaDB, REDIS, PHP 7.x_

_Server config - Apps: Standard, active encryption, TOTP, OAuth2, Calendar/Contacts/Tasks, Polls, Custom Groups, Guests, Impersonate_

_Client: a) OpenSUSE Leap 15 b) Windows 10 Prof. LTSB
Browser: FF 60.0.2 c) Android 7.x_

_CardDAV/CalDAV Client: a) DAVDroid (Android), b) KDE/Akonadi Framework, c) MS Outlook 2016 with CalDav Synchronizer_

Login Type | Login Setting | Result | Comment
-- | -- | -- | --
Cadaver shell login | App password | ✅ |
Browser Login | standard | ✅ |
Browser Login | TOTP & OAuth2 activated | ✅ |
Client Upload | TOTP & OAuth2 activated | ✅| Linux Client 2.4.1 GIT-Rev. cd60c2  Qt 5.9.4  |
Client Upload | TOTP & OAuth2 activated | ✅| Windows Client 2.4.1
Mobile Client Upload | TOTP & OAuth2 activated | ✅ | Android Client 2.8.0. beta 1
CalDAV Client | TOTP & OAuth2 activated | ✅ | with App Password
CardDAV  Client | TOTP & OAuth2 activated | ✅ | with App Password

**OVERALL RESULT**
No regressions from 10.0.8
