### ISSUE TITLE
webUI error dialog when can't send public link share mail has no recipients

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#31845]
### Steps to reproduce
0. do not start any mail server (or do something else to make mail sending fail in general)
1. In admin, settings, sharing, enable "Allow users to send mail notification for shared files"
2. Login as an ordinary user
3. Share a file or folder as a public link
4. Enter some email address/es in "Send link via email"
5. Click "Share"

### Expected behaviour
Error dialog is displayed saying:
  An error occurred while sending email
  Couldn't send mail to following recipient(s):
    mail1@example.com
    mail2@example.com

### Actual behaviour
Error dialog is displayed saying:
  An error occurred while sending email
  Couldn't send mail to following recipient(s):

but no recipients are mentioned.

### Server configuration
10.0.9RC1 or current stable10

**Comment by phil-davis** [comment]
Noticed while testing #31227 but is unrelated to that fix.

Seems to be because actually all the recipients are sent in a single email as BCC. That email has no "To" recipients. If that single email attempt fails, the code in ``lib/private/Share/MailNotifications.php`` ``sendLinkShareMailFromBody`` returns the ``To`` recipient if the email send fails. So the BCC (and CC) recipients are not in the array of failed recipients.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @felixheidecke, @pmaier1, and @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/7687 (Do not close Share Dialog on error), https://github.com/owncloud/core/issues/7783 (File sharing dialog does not notify user if recipient has no email), https://github.com/owncloud/core/issues/28840 (-Error-), https://github.com/owncloud/core/issues/26902 (error), and https://github.com/owncloud/core/issues/10331 (Selecting "No people found" in share with dialog gives error).

**Comment by phil-davis** [comment]
Also the error logged in ``owncloud.log`` does not mention any email address(es):
```
Can't send mail with public link to : Connection could not be established with host 127.0.0.1 [Connection refused #111]
```

**Comment by phil-davis** [comment]
PR #31847 has an attempt at a fix.

**Comment by phil-davis** [comment]
Backport PR #31935 is waiting for merge after 10.0.9 code freeze.
