### ISSUE TITLE
Thumbnail not regenerated as file changes

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#31849]
### Steps part 1

1. Login as "someuser"
1. Create a file "test.txt" and edit several times to create versions
1. Open the "Versions" tab in the sidebar
1. Restore some previous version
1. Close the "Versions" panel, even refresh the whole files page
1. Look at the thumbnail preview

### Expected results
Thumbnail shows content from the restored version.

### Actual result
Thumbnail shows unchanged content.

### Version
10.0.9RC1

### Steps part 2
There is no thumbnail update when doing upload-overwrite:
1. Upload some x.png file - observe the thumbnail looks like a small version of the file content
1. Locally edit/replace the x.png file with some other graphics content
1. Upload x.png and choose to keep the new file
1. Download x.png - check that is does have the new content

### Expected results
Thumbnail displays updated content

### Actual result
Thumbnail shows unchanged content.

### Steps part 3
There is no thumbnail update when editing and existing text file:
1. Create a new text file with some content - observe that the thumbnail shows the early content
1. Edit the text file in the webUI, changing some content early on line 1 (to make sure it should be part of the thumbnail)

### Expected results
Thumbnail displays updated content

### Actual result
Thumbnail shows unchanged content.

**Comment by phil-davis** [comment]
Works in 10.0.8

**Comment by phil-davis** [comment]
@davitol please try to reproduce this, to make sure I am not imagining.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/19219 (Thumbnail is not updated, when restoring a file), https://github.com/owncloud/core/issues/10559 (Thumbnails not regenerated when reverting to an earlier version of a file), https://github.com/owncloud/core/issues/28115 (Thumbnails are not shown in the version section), https://github.com/owncloud/core/issues/205 (Files: thumbnails), and https://github.com/owncloud/core/pull/31659 (don't delete the source files when generating thumbnails).

**Comment by davitol** [comment]
![versionthumb](https://user-images.githubusercontent.com/10596560/41702118-3273c664-752f-11e8-9b56-327190227011.gif)
It seems it works for me. Are you using regular storage or an external one?

**Comment by phil-davis** [comment]
In your screen capture, the thumbnail of the file keeps showing "asfda" - but it should change as you restore different versions.

**Comment by davitol** [comment]
> In your screen capture, the thumbnail of the file keeps showing "asdfa" - but it should change as you restore different versions.

Yes I misunderstood the title. It happens for me justonly editing the file, no need of restoring a version

**Comment by phil-davis** [comment]
As discussed in chat, thumbnail update is working while editing a new file. But if I edit an existing file, then the content changes OK, but the thumbnail is not updated.

**Comment by phil-davis** [comment]
Also there is no thumbnail update when doing upload-overwrite:
1) Upload some x.png file - observe the thumbnail looks like a small version of the file content
2) Locally edit/replace the x.png file with some other graphics content
3) Upload x.png and choose to keep the new file
4) Download x.png - check that is does have the new content

But observe the webUI files list - the thumbnail has not updated.

**Comment by PVince81** [comment]
@DeepDiver1975 are you able to have a look ? are we missing some hook triggers to tell the preview system to reset the preview after restore ?
