### ISSUE TITLE
Chrome autocompletion for "users" field causes "Password protect" to activate

### ISSUE THREAD

**Issue by Narcolessico** [owncloud/core#31848]
I can reproduce the issue only sometimes, only with Chrome 67.0.3396.87 on Windows (same version on Ubuntu seems not to be affected). ownCloud version is 9.1.

1. Click on the "share" icon of a file
2. Enable "Share link"
3. Chrome automatically completes the field for the usernames and the password field; this somehow enables "Password protect", even if it was not clicked by the user.
4. Click on "Password protect" to disable it
5. Chrome detects the change in the user field and tries to autocomplete, causing the field to be enabled again

Expected behavior: step 3 should not happen at all; password protection should be enabled only if the user clicks on the correspondent checkbox.

I can't reproduce it consistently, but when it happens it makes the sharing completely unusable and I have to temporarily switch to another browser where no credentials are stored.

I am not sure whether this is a Chrome issue or ownCloud one, but I can't recall any other interface where this happens.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/5469 (Missing password confirmation field), https://github.com/owncloud/core/issues/10092 (User Password Reset), https://github.com/owncloud/core/issues/7304 (Password eye out of field), https://github.com/owncloud/core/issues/21383 (LDAP users / password changing ), and https://github.com/owncloud/core/issues/7341 ([FEATURE REQUEST] Force users to password protect shares as link).

**Comment by PVince81** [comment]
I think I heard you guys talk about this @cdamken ?
