### ISSUE TITLE
Group excluded from sharing - difficult to find comments panel

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#31840]
### Steps to reproduce
1. create a group ``noshare`` and put ``user1`` in the group
2. admin, settings, sharing - check exclude groups from sharing, and enter group ``noshare``
3. login as ``user1``
4. feel the urge to add a comment or tag to a file

### Expected behaviour
There is a button somewhere on each file row that would open the "tags/comments" panel (that also used to do sharing)

### Actual behaviour
There is no button icon visible.
But if you click blindly in the empty space of the file row, the panel opens for you to add tags/comments.

### Server configuration
10.0.9RC1
or current stable10

**Comment by phil-davis** [comment]
The usual "sharing" icon is not correct any more, because the user cannot share. But some icon other than "empty space" would be nice.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/10307 (Exclude Groups from Sharing), https://github.com/owncloud/core/issues/7272 (Exclude subfolder from sharing), https://github.com/owncloud/core/issues/17346 (Exclude group from sharing after a share was created), https://github.com/owncloud/core/pull/31490 (Exclude users from sharing if they are a member of any excluded group), and https://github.com/owncloud/core/issues/29938 (Grouped link share).
