### ISSUE TITLE
Group excluded from sharing - Resharing is not allowed

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#31841]
### Steps to reproduce
1. create a group ``noshare`` and put ``user1`` in the group
2. admin, settings, sharing - check exclude groups from sharing, and enter group ``noshare``
3. login as ``user1``
4. click the white-space of a file row of one of the user's own files, to open the tags/comments/sharing panel
5. Click the "Sharing" tab

### Expected behaviour
Message says:
Sharing is not allowed
or the tab is not there at all.

### Actual behaviour
Message says:
Resharing is not allowed
(actually this is a file belonging to the current user, so they would not be "resharing" it, just  "sharing" it.

### Server configuration
10.0.9RC1
or current stable10

**Comment by phil-davis** [comment]
This is a very minor text wording issue in the UI.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/10307 (Exclude Groups from Sharing), https://github.com/owncloud/core/issues/898 ("Resharing is not allowed" for Shared folder), https://github.com/owncloud/core/issues/26892 (Resharing is not allowed), https://github.com/owncloud/core/issues/20751 (Resharing is not allowed), and https://github.com/owncloud/core/issues/2041 (Resharing is not allowed on Share button).

**Comment by PVince81** [comment]
This message also appears when sharing is allowed in general, but the current user clicked a received folder which had "can share" disabled. In this case "Resharing is not allowed" is the correct text.

Maybe we need to rather adjust the text based on whether the current user is also the owner or whether it's a received file.

So "very minor" becomes "minor" ;-)

**Comment by pmaier1** [comment]
Has been changed for 10.0.10 to "Sharing is not allowed" (https://github.com/owncloud/core/pull/32403) which fits both cases. Closing.
