### ISSUE TITLE
Previews-thumbnails get out-of-sync when edited by sharer and sharee

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#31855]
### Steps to reproduce
1. as "user1" create folder "test" and in it put  "testfile.txt" with content "owner" - thumbnail says "owner" - good
2. share folder "test" with "user2"
3. as "user2", edit "testfile.txt" and put content "user2 text"

- thumbnail displayed to "user2" is not updated, it still says "owner"

4. login as "user1" - the thumbnail displays "user2 text" - good
5. login as  "user2" again - look at the thumbnail of the file

- thumbnail displayed to "user2" is not updated, it still says "owner"

6. login as "user1" again, edit the file and put content  "user1 text" - thumbnail is updated - good
7. login as  "user2" again - look at the thumbnail of the file

- thumbnail displayed to "user2" is not updated, it still says "owner"

### Expected behaviour
The share receiver "user2" should always see a preview-thumbnail that is in sync with the file content.

### Actual behaviour
The share receiver "user2" gets "stuck" with the preview-thumbnail that was generated at the time they first received/looked at the file.

### Server configuration
10.0.9RC1 plus PR #31853 (which fixes missing hooks for thumbnail generation in 10.0.9RC1)

10.0.8 as symptoms similar to this, but might be a bit different.

**Comment by phil-davis** [comment]
Ideally the thumbnail of a file would be stored only once, in the "file system" of the file owner. Just like the file itself is stored only once, in the "file system" of the file owner.

If the share receiver "user2" is able to write back new content to the file owned by "user1" (even when encryption is happening) the "user2"  should be able to also write back new content to the thumbnail owned by "user1" - and actually that seems to be happening because "user1"  is seeing the correct updated thumbnail.

Maybe all that is needed is to stop writing a "duplicate"  thumbnail in user2's file system?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/19054 (If thumbnail then large preview in sidebar), https://github.com/owncloud/core/issues/997 (possibility preview and edit docx), https://github.com/owncloud/core/issues/16471 (Can not sync edited remote share file), https://github.com/owncloud/core/issues/7020 (Contact photos only in preview when edited on a client), and https://github.com/owncloud/core/issues/14671 (Thumbnail cache gets deleted after upload from smartphone).

**Comment by PVince81** [comment]
Estimate: 0.5-1md

**Comment by DeepDiver1975** [comment]
Concept:
- store thumbnails by file id in an user independent storage data/thumbnails
- old thumbnail folders are to be deleted using a repair step/migration step
- OPTIONAL: new thumbnails can be batch recreated using an occ command

**Comment by phpweb** [comment]
Thank you @phil-davis 

When approximately can we have this feature?

**Comment by phil-davis** [comment]
It is a bug to be fixed. It depends on scheduling of the dev team, which is not my area.
