### ISSUE TITLE
Wiki-page Apps needs some updates...

### ISSUE THREAD

**Issue by DJCrashdummy** [owncloud/core#31859]
hopefully this is the correct place to report this...!? anyway https://github.com/owncloud/core/wiki/Apps needs some updates:

1. Contacts (CardDAV) & Calendar (CalDAV) & Tasks (CalDAV)
    - [ ] `Outlook DAV Client (Windows), proprietary` isn't available anymore.

1. Contacts (CardDAV)
    - [ ] `SOGo Connector` is still available (btw your [`manual`](http://doc.owncloud.org/server/6.0/user_manual/pim/sync_thunderbird.html)-link results in a 404)...
    - [ ] but the Thunderbird-Addon [CardBook](https://gitlab.com/CardBook/CardBook) (works much smother) should be added.

1. Bookmarks (API?)
    - [ ]  `ownCloud Bookmarks (Android) – unfortunately closed source as of now` (cz.nethar.owncloudbookmarks) isn't available anymore...
    - [ ] but there is a replacement: [ownCloud Bookmarks](https://gitlab.com/derSchabi/OCBookmarks) (org.schabi.nxbookmarks.owncloud)
    - [ ] there is also a desktop-client for Firefox & Chromium: [Floccus](https://github.com/marcelklehr/floccus) (i know, it is made for Nextcloud, but should work though)

1. Other
    - [ ] ` Cloudii (Android) (proprietary) is also a file manager for multiple cloud services` isn't available anymore.
    - [ ] maybe it is worth mentioning [MiXplorer](https://labs.xda-developers.com/store/app/com.mixplorer) since it is one of the best file manager for android.

--- 

btw: i would call this page more precisely "Apps and Clients". :wink:

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/21366 (Update), https://github.com/owncloud/core/issues/20661 (Update), https://github.com/owncloud/core/issues/26284 (Update of "Overview Maintenance and Release Schedule" wiki page needed), https://github.com/owncloud/core/issues/27545 (FYI: Wiki Page about Apps was deleted), and https://github.com/owncloud/core/issues/14520 (Priorise apps with update).

**Comment by PVince81** [comment]
in general I wonder if we should keep this page at all

many apps should be visible on the marketplace already https://marketplace.owncloud.com/ so this would leave only the known clients there

@JKawohl @eMerzh @pmaier1 thoughts ?

**Comment by DJCrashdummy** [comment]
IMHO this page is pretty awesome and important!
i love the fact that all possible clients for the main apps are visible at one sight... so it helps me to easily decide which app is worth considering to install/use since it may fit my workflow.
