### ISSUE TITLE
inject EnvironmentHelper where possible

### ISSUE THREAD

**Issue by VicDeo** [owncloud/core#31864]
consider  EnvironmentHelper injection

1. instead of direct `OC::$SERVERROOT` usage in
```
lib/private/App/AppManager.php
lib/private/URLGenerator.php
lib/private/IntegrityCheck/Helpers/EnvironmentHelper.php
lib/private/IntegrityCheck/Checker.php
lib/private/Setup/AbstractDatabase.php
lib/private/Log/Owncloud.php
lib/private/legacy/template.php
lib/private/legacy/user.php
lib/private/legacy/util.php
lib/private/legacy/defaults.php
lib/private/Files/External/LegacyUtil.php
lib/private/DB/ConnectionFactory.php
lib/private/DB/MigrationService.php
lib/private/Updater.php
lib/private/Preview/MP3.php
lib/private/Setup.php
lib/private/Http/Client/Client.php
lib/private/User/Database.php
lib/private/User/SyncService.php
lib/private/Security/CertificateManager.php
lib/private/Preview.php
lib/private/Server.php
lib/private/TemplateLayout.php
```

2. Instead of  direct OC::$APPSROOTS usage in
```
lib/private/App/AppManager.php
lib/private/IntegrityCheck/Iterator/ExcludeFoldersByPathFilterIterator.php
lib/private/legacy/app.php
lib/private/Installer.php
```

3. Instead of  direct OC::$WEBROOT usage
```
lib/private/Session/Internal.php
lib/private/Session/CryptoWrapper.php
lib/private/App/AppManager.php
lib/private/URLGenerator.php
lib/private/Route/Router.php
lib/private/legacy/app.php
lib/private/Setup.php
lib/private/User/Session.php
lib/private/Preview.php
lib/private/TemplateLayout.php
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/18047 (r), https://github.com/owncloud/core/issues/17528 (Prevent closing upgrade page while upgrade in progress), https://github.com/owncloud/core/issues/4230 (i), and https://github.com/owncloud/core/issues/13597 (Votre dossier de données et vos fichiers sont probablement accessibles depuis internet. Le fichier .htaccess ne fonctionne pas. Nous vous recommandons vivement de configurer votre serveur web de façon à ce que ce dossier de données ne soit plus accessible, ou bien de le déplacer à l'extérieur de la racine du serveur web. ).

**Comment by PVince81** [comment]
I guess this will make a lot of these classes better unit testable ?

Sounds like a big undertaking, maybe split it in smaller pieces ?

Estimate for the whole and pieces ?

**Comment by VicDeo** [comment]
@PVince81 I'd better not estimate all these classes as a whole.

**Comment by PVince81** [comment]
indeed...
