### ISSUE TITLE
Internal share Notification adjustments

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31876]
Some parts that were missed and need adjustment:
- [ ] adjust notification framework:
    - [ ] "From" mail field needs to use the format "<User> (via <product name>) (<no-reply@example.com>)".
    - [x] Add missing "Hello," in the default mail notification templates
- [x] adjust internal share notification contents as in https://github.com/owncloud/platform/blob/master/docs/server/product%20design/notifications.md#notification-specific-information
    - [x] internal share invitation message
    - [x] federated share invitation message

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/31764 (Different button order between the internal share and remote share notifications), https://github.com/owncloud/core/issues/27710 (Incorrect "From" field in the "Share Link" notification), https://github.com/owncloud/core/pull/31775 (Reorder the buttons for the internal share notification), https://github.com/owncloud/core/issues/7380 (Contact sharing), and https://github.com/owncloud/core/issues/12608 (Shared file notifications).

**Comment by jvillafanez** [comment]
Sharing and federated sharing notification messages adjusted in https://github.com/owncloud/core/pull/31881 . That should cover the "adjust internal share notification contents" part

**Comment by jvillafanez** [comment]
"Hello" added in the templates in https://github.com/owncloud/notifications/pull/208 PR

Regarding the "from" field changes, I don't think it's possible to do it the way we want:
* Currently, the "from" field is automatically set by ownCloud using the ownCloud's mail settings and not by the notifications app. The notifications app doesn't set the "from" field.
* The notifications app can manually set the "from" field if needed, although it might not be homogeneous regarding other mails sending from ownCloud:
    * The possible options are, either set only the email, or set the email with an additional kind of displayname. You can check below how it is shown with "notifier Mail" as displayname
    ![screen shot 2018-06-26 at 12 28 08](https://user-images.githubusercontent.com/1477829/41905777-71145e72-793c-11e8-976a-9606d1893ff4.png)
* There is a "via" header we can include, but it won't appear the way we want. In addition, it feels kind of hacky because we'll need access to the swiftMessage which is wrapped by the ownCloud's mail message.
    * According to the RFC (https://tools.ietf.org/html/rfc7230#section-5.7.1) the "via" header is intended for intermediate proxies that could be between the origin and the destination. This kind of invalidate our use case.
    * I've checked with mailhog and gmail to check how they show this header:
        * mailhog can show all the headers, but the "via" header will be shown separately (see below)
            ![screen shot 2018-06-26 at 12 38 56](https://user-images.githubusercontent.com/1477829/41906354-f3d3be74-793d-11e8-8cb7-b6a8f5739496.png)
        * gmail won't show the header (at least I don't know how)

**Comment by PVince81** [comment]
@jvillafanez also the notification app cannot accurately know who the initiator is so it couldn't set that user id in the "From" field. We'd need to extend the notification API to allow setting either the "From" field or the name of the action initiator to be used. It would require the creator of the notification to also specify the from field.

It seems we need to invest more concept work to have a proper "From" field for notification emails, and maybe even more. At this point it is too late to add new APIs.

@pmaier1 are you ok with deferring the "From" field work to later ?

**Comment by jvillafanez** [comment]
We might want to recheck how the notification looks like in the web:
![screen shot 2018-06-26 at 13 07 19](https://user-images.githubusercontent.com/1477829/41907683-ea6cf50e-7941-11e8-9e42-ae4aca351750.png)

It seems to have duplicated information... not sure what we want to do with this:
* Leave it as it is
* Hide the notification message and show just the subject
* Change the notification content (in each app)

**Comment by PVince81** [comment]
Damn. For the notification inside the web UI it doesn't make much sense to say "on ownCloud" as the user is already in. In the desktop client I wonder if we should also show this message.

It almost looks like we'd need different messages for a notification in mail and in app.

Another alternative would be to remove "on ownCloud" and add this "on $productName" only in the mail footer where the link would become "See $link for more information on $productName".

@pmaier1 thoughts on my comment and on the subject duplication ?

**Comment by pmaier1** [comment]
Please remove the quotation marks around the user name.

**Comment by PVince81** [comment]
Thanks, please adjust accordingly @jvillafanez 
- [ ] remove quotation marks around user name
- [ ] move "on $productName" to the line containing the link as per https://github.com/owncloud/core/issues/31876#issuecomment-400302085

**Comment by PVince81** [comment]
@jvillafanez I've updated the latter steps to reflect our discussions

**Comment by jvillafanez** [comment]
I'd prefer not to assume that the displaynames will be always nice and fit correctly. You might have a "user shared" or "account shared" as displayname, which would display `user shared shared "whatever" with you`, or even something more common such as "Harrison, Joe" would display `Harrison, Joe shared "whatever" with you`. In both cases the text can be confusing.

**Comment by jvillafanez** [comment]
yes, it might be confusing on some scenarios

**Comment by jvillafanez** [comment]
The specific notification changes are in https://github.com/owncloud/core/pull/31923. Note that the double quotes are still present.

I'm not sure if the "extra field" for sharing has been taken into account too:
![screen shot 2018-06-27 at 13 37 20](https://user-images.githubusercontent.com/1477829/41971625-648cd52a-7a0f-11e8-9896-695a03ea9022.png)

**Comment by PVince81** [comment]
> You might have a "user shared" or "account shared" as displayname

probably not a real world use case though ?

**Comment by PVince81** [comment]
@jvillafanez please raise another ticket for the "From" changes and post about your research so far

**Comment by PVince81** [comment]
I've raised https://github.com/owncloud/core/issues/31876#issuecomment-401386556 for the double quote topic
