### ISSUE TITLE
Implement async file upload in web UI upload

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31880]
Based on https://github.com/owncloud/core/pull/31851.

@butonic @DeepDiver1975 what exactly do we need ?
Update the progress bar and consider the upload as unfinished despite closed connection ?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/13755 (Use part files for web UI upload), https://github.com/owncloud/core/issues/4767 (File upload in browser), https://github.com/owncloud/core/issues/24509 (Async file operations), https://github.com/owncloud/core/issues/29654 (Uploading files  to SMB storage using web UI stops when there is a hidden file in the uploaded files), and https://github.com/owncloud/core/issues/6083 (Upload File API).

**Comment by PVince81** [comment]
this is already on https://github.com/owncloud/core/pull/31851
