### ISSUE TITLE
Updating to 10.1.0 - OC\RepairException: Upgrade is not possible (disable files_videoplayer)

### ISSUE THREAD

**Issue by Sven88090** [owncloud/core#31885]
### Steps to reproduce
1. Update from 10.0.8 to 10.1.0
2. start the update
3.

### Expected behaviour
Update to 10.1.0

### Actual behaviour
OC\RepairException: Upgrade is not possible

Reparaturwarnung:Market app is unavailable for updating of apps. Please update manually, see https://doc.owncloud.org/server/10.1/go.php?to=admin-marketplace-apps
Reparaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Reparaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable files_videoplayer
Reparaturwarnung:For manually updating, see https://doc.owncloud.org/server/10.1/go.php?to=admin-marketplace-apps

**List of activated apps:**
comments
configreport
dav
encryption
external
federatedfilesharing
federation
files
files_external
files_sharing
files_trashbin
files_versions
firstrunwizard
market
notifications
provisioning_api
systemtags
testing
updatenotification
user_external

### Description
I have deleted the app (folder - owncloud/files_videoplayer) but still get the error after starting the upgrade.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/28806 (OC\RepairException: Upgrade is not possible), https://github.com/owncloud/core/issues/28013 (OC\RepairException: Upgrade is not possible. Unsuccessful upgrade from 10.0.0 to 10.0.1), https://github.com/owncloud/core/issues/28027 (Updating 10.0.0 to 10.0.1), https://github.com/owncloud/core/issues/6957 (Update Failed : 5.0.10 - 6.0.1 ), and https://github.com/owncloud/core/issues/28370 (OC\Repair Exception: Upgrade is not possible).

**Comment by Sven88090** [comment]
Disabled the app in the database and now everything is ok,
Thx a lot.
