### ISSUE TITLE
Deprecate OCPChecker and migrate as Extension for common static code analyzers

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/core#31929]
The [CodeChecker](https://github.com/owncloud/core/tree/master/lib/private/App/CodeChecker) in ownCloud has been a great idea. However - there are plenty of great static code analyzer tools out there. It is more feasible to use a tool that is designed for static code analysis and provide ownCloud specific rules/extensions. 

ref:

https://github.com/owncloud/core/pull/31926#issuecomment-400781790

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/13119 (files_sharing used deprecated code), https://github.com/owncloud/core/issues/13597 (Votre dossier de données et vos fichiers sont probablement accessibles depuis internet. Le fichier .htaccess ne fonctionne pas. Nous vous recommandons vivement de configurer votre serveur web de façon à ce que ce dossier de données ne soit plus accessible, ou bien de le déplacer à l'extérieur de la racine du serveur web. ), https://github.com/owncloud/core/issues/31920 (Code style + static analysis), https://github.com/owncloud/core/pull/30026 (Migrate to yarn), and https://github.com/owncloud/core/pull/29908 (Migrate to yarn).
