### ISSUE TITLE
Code style + static analysis

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31920]
After 10.0.9 is out, we should focus on first merging all tasks related to php-cs-fixer to stable10 and also enable php stan

- [x] php-cs-fixer on stable10: https://github.com/owncloud/core/pull/32116
- [ ] pre-commit hook for php-cs-fixer: https://github.com/owncloud/core/pull/31837
- [x] phan on stable10: backport https://github.com/owncloud/core/pull/31807

Additions:
- [ ] deprecate OCPCodeChecker and make it an extension: https://github.com/owncloud/core/issues/31929

Anything else ? @phil-davis @DeepDiver1975 @patrickjahns

**Comment by PVince81** [comment]
- [ ] remove dead code https://github.com/owncloud/core/pull/31889

**Comment by PVince81** [comment]
- [ ] code style checker not working for PVince81 due to https://github.com/owncloud/core/issues/31863

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/31726 (Acceptance test code style), https://github.com/owncloud/core/pull/31728 ([stable10] Acceptance test code style), https://github.com/owncloud/core/issues/11889 (Code not reachable), https://github.com/owncloud/core/pull/31837 (Provide a pre-commit hooks which disallows commit if the code style f…), and https://github.com/owncloud/core/issues/20313 (Owncloud + Hooks).

**Comment by patrickjahns** [comment]
I am moving forward with using phpstan for core - also evaluating [psalm](https://github.com/vimeo/psalm)

Also note - I want to get the dev dependencies for these tools into a separate way of installing. I don't like that a makefile fetches them. 

Evaluating:
 - https://github.com/bamarni/composer-bin-plugin 
    install similar to composer - but in `vendor-bin`
 - https://github.com/tommy-muehle/tooly-composer-script
    install phar files - similar to how our Makefile does it

**Comment by PVince81** [comment]
The makefile already fetches composer.

If the makefile should not fetch anything, we'll need to make sure the developer has all these tools upfront installed on their local machine. Currently we already expect PHP and Node to be installed. If we add more to this list we might want to provide a script to fetch these only once, outside of the OC work tree.

**Comment by PVince81** [comment]
Should phpunit also be installed separately maybe ? I see the value in not having any dev deps in the main composer file.

**Comment by phil-davis** [comment]
Just a note. On Monday I was setting up a new system and had to:
```
sudo npm install -g yarn
````
To make ``make`` happy in ``core`` it wanted ``yarn`` to already be installed on the system.
I  also installed all the PHP bits (php, php-intl,... long list), mySQL, node manually. So I think that is about what is expected to already exist. And the current ``make`` and ``composer`` sucks in verything else it wants.

**Comment by patrickjahns** [comment]
> If the makefile should not fetch anything, we'll need to make sure the developer has all these tools upfront installed on their local machine. Currently we already expect PHP and Node to be installed. If we add more to this list we might want to provide a script to fetch these only once, outside of the OC work tree.

For many projects that is already common - their `README.md` very often show on "how to get started" developing.

>  If we add more to this list we might want to provide a script to fetch these only once, outside of the OC work tree.

Right now we expect `composer`,`node`,`npm`,`yarn` - which should anyway be global right? at least composer any developer should have ( and personally I was confused the first time when running make, that it was fetched).

> Should phpunit also be installed separately maybe ? I see the value in not having any dev deps in the main composer file.

phpunit would have been one of the few tools I actually would add to dev-dependencies. As the testing classes tightly couple with code classes. But we can evaluate moving it out.

Yet for `php-cs-fixer`, `behat` etc. I imagine them to be separately installed. [composer-bin-plugin](https://github.com/bamarni/composer-bin-plugin) would be better suited here, as we could include other extensions with the tools in the composer.json 

Needs further evaluation - a simple approach was done in https://github.com/patrickjahns/cli-phar-experiments - each "namespace" has its own `composer.json` - example https://github.com/patrickjahns/cli-phar-experiments/blob/master/vendor-bin/php-cs-fixer/composer.json 


> And the current make and composer sucks in verything else it wants.  
@phil-davis  - can you elaborate here - don't quite understand it

**Comment by phil-davis** [comment]
> And the current make and composer sucks in everything else it wants.

Maybe it is just a misunderstanding of my English usage. I don't mean "it sucks!", I mean "composer fetches everything else automatically" - that whatever other utilities... are needed for "development and testing joy" come automatically, without the developer needing to do anything special.

**Comment by phil-davis** [comment]
I find it convenient that there are only a few "big ticket" items like PHP itself that need to be installed "for real" on my development  Ubuntu machine. Then ``composer`` fetches whatever pile of weird tools are needed for doing development inside the repo (flavor-of-the-month code-style checker, correct behat version that goes with the acceptance test code of the current branch, correct phpunit that  goes with the unit tests of the current branch...)

So I guess tools whose version needs to be in sync with the test files... in the current branch, those tools need to be in the "make+composer" system somewhere so they switch version easily for developers.

Other tools that are not so version-dependent can be assumed to pre-exist.

**Comment by patrickjahns** [comment]
> Then composer fetches whatever pile of weird tools are needed for doing development inside the repo (flavor-of-the-month code-style checker, correct behat version that goes with the acceptance test code of the current branch, correct phpunit that goes with the unit tests of the current branch...)

see above - `composer-bin-plugin` or `tooly-composer-script` at least will cover this for php parts. I see composer here as the right tool for the job to fetch tools/dependencies related to php development. Thus would like to move `phpstan`/`phan`/`php-cs-fixer` into one of these tools.

They provide:
- standard easy way of installing things
- versioning - as in the tool will always be in a pre-defined state and changing the tool-chain is an update to that configuration ( that passes through ci )

> Other tools that are not so version-dependent can be assumed to pre-exist.

Do you have a list?

For me this is:
- composer
- npm / yarn / bower (?)

**Comment by PVince81** [comment]
added https://github.com/owncloud/core/issues/31929 to top post

this ticket is becoming the list of things/tools we want to have in place for code quality

**Comment by PVince81** [comment]
### Apps
- https://github.com/search?q=org%3Aowncloud+php-cs-fixer&type=Issues
- [ ] finish and merge existing PRs for php-cs-fixer
- [ ] phan / ...
- [ ] add more apps here

**Comment by patrickjahns** [comment]
Phan on stable10 has been backported

So we are still pursuing a version bump on phan here #32493 
And looking into  introducing phpstan as well #31810

**Comment by JanAckermann** [comment]
@phil-davis is this done?

**Comment by phil-davis** [comment]
We never committed a git hook to the repo. But that would be the same for every oC10 core and app repo - they all have `make test-php-style` - any developer can create their own local git pre-commit hook if they want to.
