### ISSUE TITLE
[10.0.8] LDAP Group - User view empty / Sharing not fully functional

### ISSUE THREAD

**Issue by itsul** [owncloud/core#31949]
### Steps to reproduce
1. Configure LDAP Backend (user + group filter)
2. Test LDAP connection and count users/groups => OK
3. Go to User management, click on the existing (LDAP) group => First problem: No users available in the view
4. Second problem while creating a sharing link the user search is only working for LDAP users which has logged in once. LDAP Users which are assigned to the LDAP group and never logged in before are not shown in the search field (creating a share / share link).

### Expected behaviour
All users from the LDAP group should be visible in the group view. Furthermore the user search for creating (or editing) a share should show all available users independent if the user has logged in before. 

### Actual behaviour
LDAP Group is shown in the left menu bar but the detail view (user list view) is empty.
Create a share: Search for a user which is in a assigned LDAP group but has never logged in before => User could not be found 

### Server configuration
**Operating system**:
Debian 9

**Web server:**
Apache
**Database:**
MariaDB

**PHP version:**
7

**ownCloud version:** (see ownCloud admin page)
10.0.8

**Updated from an older ownCloud or fresh install:**
Fresh Install

**Where did you install ownCloud from:**
Repository from Owncloud itself

**Signing status (ownCloud 9.0 and above):**

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP Backend

#### LDAP configuration (delete this part if not used)
Is working overall, user count function is functional, LDAP login is possible.

#### ownCloud log (data/owncloud.log)
Already tried a tail while testing but there are no entries in the logfile

Could someone verify the problem to exclude a misconfiguration?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @jvillafanez, and @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/31402 (Calendar cannot be shared to group (10.0.8)), https://github.com/owncloud/core/issues/24521 (Shared by me - empty with ldap users), https://github.com/owncloud/core/issues/11394 ([LDAP] no users or groups found), https://github.com/owncloud/core/issues/14384 (ownCloud 8 LDAP/AD groups and share not fully operational), and https://github.com/owncloud/core/issues/18340 (No ldap user appears).

**Comment by PVince81** [comment]
please check https://doc.owncloud.org/server/latest/admin_manual/configuration/server/occ_command.html#syncing-user-accounts, you need to run the new command "user:sync"

**Comment by itsul** [comment]
@PVince81 Thanks for the quick reply. It is working now, we miss this part of the documentation for the new version
