### ISSUE TITLE
Need to have unit tests for transfer ownership

### ISSUE THREAD

**Issue by sharidas** [owncloud/core#31954]
We need to have unit tests for the change in tranfer ownership command. This does affect the code coverage result.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/13355 (Transfer share ownership to other user), https://github.com/owncloud/core/issues/29608 (Transfer ownership trashbin), https://github.com/owncloud/core/issues/29540 (Transfer-ownership keep versions), https://github.com/owncloud/core/issues/26523 (Transfer ownership path already shared), and https://github.com/owncloud/core/issues/9879 (Need info about backgroundjob.php).

**Comment by karakayasemi** [comment]
Some tests are added with https://github.com/owncloud/core/pull/36222. 
According to https://codecov.io/gh/owncloud/core/src/27d4865685bc7e76997f3f50e444ff54f86d3d5d/apps/files/lib/Command/TransferOwnership.php coverage is around 81%. I guess we can close this.
