### ISSUE TITLE
When disk space is full, users cannot log-in anymore (to delete files)

### ISSUE THREAD

**Issue by kerner1000** [owncloud/core#31950]
### Steps to reproduce
1. Fill up all diskspace and try to log-in

### Expected behaviour
It should still be possible to log-in. Owncloud should reserve some space to maintain accessibility.

### Actual behaviour
Not accessible anymore, not via web nor via desktop client

### Server configuration
**Operating system**:
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```
**Web server:**
```
$ apache2 -version
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02
```
**Database:**
```
$ mysql -V      
mysql  Ver 14.14 Distrib 5.7.20, for Linux (x86_64) using  EditLine wrapper
```
**PHP version:**
```
$ php -v
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
```
**ownCloud version:** (see ownCloud admin page)
10.0.7

**Updated from an older ownCloud or fresh install:**
Upgrade from ??

**Where did you install ownCloud from:**
https://download.owncloud.org/community/owncloud-10.0.7.tar.bz2

**Signing status (ownCloud 9.0 and above):**
No errors have been found.`

**The content of config/config.php:**

```
sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "ocs9vyuvehvx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.lablicate.com"
        ],
        "datadirectory": "\/var\/data\/owncloud-intern",
        "overwrite.cli.url": "https:\/\/owncloud.lablicate.com",
        "dbtype": "mysql",
        "version": "10.0.7.2",
        "dbname": "owncloud-intern",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2
    }
}

```

**List of activated apps:**

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:**
Current Firefox.

**Operating system:**

#### ownCloud log (data/owncloud.log)
```
{"reqId":"c6056b05-85e6-4045-983f-fbca9445ef70","level":3,"time":"2018-06-29T04:17:51+00:00","remoteAddr":"84.133.175.106","user":"user","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/files\/user\/","message":"session_write_close(): write failed: No space left on device (28) at \/var\/www\/owncloud-extern\/lib\/private\/Session\/Internal.php#104"}
{"reqId":"c6056b05-85e6-4045-983f-fbca9445ef70","level":3,"time":"2018-06-29T04:17:51+00:00","remoteAddr":"84.133.175.106","user":"user","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/files\/user\/","message":"session_write_close(): Failed to write session data (files). Please verify that the current setting of session.save_path is correct (\/var\/lib\/php\/sessions) at \/var\/www\/owncloud-extern\/lib\/private\/Session\/Internal.php#104"}
```

**Comment by kerner1000** [comment]
I see. But if I could tell owncloud to keep always a minimum amount of free space, then it would not fill the whole disk and take away disk space that is needed for example by php.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/10564 (Deleted user can log in ), https://github.com/owncloud/core/issues/10453 (Can't delete user.), https://github.com/owncloud/core/issues/5201 (Cannot delete file), https://github.com/owncloud/core/issues/2716 (Cannot permanently delete deleted files), and https://github.com/owncloud/core/issues/27274 (delete).

**Comment by PVince81** [comment]
You can see quotas for your users. Normally the trashbin and versions will automatically expire and delete old files based on how much free space there is.

Please clean up your disk space and upgrade to 10.0.8 to get this bug fix https://github.com/owncloud/core/pull/30163 if you're not using quota. This fixes trashbin auto-expire when no quota is set.

**Comment by patrickjahns** [comment]
> I see. But if I could tell owncloud to keep always a minimum amount of free space, then it would not fill the whole disk and take away disk space that is needed for example by php.

Again - this depends on your infrastructure configuration. 

If ownCloud's data folder resides on the same partition where the sessions are stored - this might mitigate your infrastructure issue. But as it is an infrastructure issue - I highly recommend solving this on the infrastructure itself by:
- setting a system quota on the data folder of ownCloud 
- monitoring the server that provides the storage 

For further tipps/help I suggest to visit our community forums ( https://central.owncloud.org/ ) - people will be able to help you setup this :-)
