### ISSUE TITLE
Add symfony events for more login hooks

### ISSUE THREAD

**Issue by sharidas** [owncloud/core#31956]
As of now the symfony login events are present in 
- https://github.com/owncloud/core/blob/master/lib/private/User/Session.php#L872

There are places like encryption or may be more where we need to have similar events to be added.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @PVince81, and @butonic.

Possibly related issues are https://github.com/owncloud/core/pull/31467 (Symfony events added for login failed and public link accessed), https://github.com/owncloud/core/pull/30268 ([WIP] Adding new symfony events to replace old hooks), https://github.com/owncloud/core/issues/31465 (Missing symfony event for failed login attempt), https://github.com/owncloud/core/pull/30996 (Throw symfony events on group actions), and https://github.com/owncloud/core/issues/29174 (Provide symfony event dispatcher events for all older hook types).

**Comment by PVince81** [comment]
as requested by @DeepDiver1975 

as discussed, to be worked on in this sprint

**Comment by PVince81** [comment]
Estimate: 0.5md

**Comment by sharidas** [comment]
The symfony events added for login were for the following methods in https://github.com/owncloud/core/blob/master/lib/private/User/Session.php:

- `login()` covers the symfony events for `loginWithToken()` and `loginWithPassword()`.
- `loginWithPassword()` has  before and after symfony events.
- `loginWithToken()` has before and after symfony events.
- `loginWithApache()` has before and after symfony events.
- `loginUser()` has before and after symfony events.

For encryption it is taken care by the `post_login` event, which happens via `postLogin` event. Meaning we don't have to do anything there.

I think we have covered the login hooks, due to which this issue was raised.

**Comment by PVince81** [comment]
please close if there is nothing left to do

**Comment by sharidas** [comment]
Closing this PR as the login hooks were added mentioned as per https://github.com/owncloud/core/issues/31956#issuecomment-415504041
