### ISSUE TITLE
Bad install UI

### ISSUE THREAD

**Issue by EddieOne** [owncloud/core#31966]
Hello,

It's very easy to install owncloud using sqlite which seems fine until you hit the file limit and destroy the installation. The UI should be improved to find mysql or maybe mysql should be the default since sqlite is more for demonstration or very light usage. A button would even work. See attachment

![image](https://user-images.githubusercontent.com/1835156/42193786-ee231994-7e2d-11e8-8e00-ae844c31b226.png)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/8788 (Mobile UI issue), https://github.com/owncloud/core/issues/1599 ( inconsistent setting ui:), https://github.com/owncloud/core/issues/1896 (Bad stats), https://github.com/owncloud/core/issues/27858 (Automated UI Tests ), and https://github.com/owncloud/core/issues/1161 (Calendar scrolling and UI).

**Comment by DeepDiver1975** [comment]
@felixheidecke on UX - THX

**Comment by phil-davis** [comment]
I thought there was discussion about this somewhere already - about making the installer default different, or making the database choice more obvious and advising against SQLite...

But I don't immediately see another similar issue.

**Comment by DeepDiver1975** [comment]
personal POV: kill web based installation - use cli only .....

**Comment by patrickjahns** [comment]
> personal POV: kill web based installation - use cli only .....

Here we should also require a double-opt-in if the user selects this. From my pov - just to make it less easy for users to shoot themself in the foot

**Comment by felixheidecke** [comment]
If we simply switch to the other default (MySQL?!), users will have to manually select sqlite if they so desire. A warning about the disadvantages should suffice. Should I sketch out a solution?
