### ISSUE TITLE
WebDav Upload endpoint returning 403

### ISSUE THREAD

**Issue by michaelsharpe** [owncloud/core#31964]
Not sure how to reproduce, but I am having problems using the MKCOL method on the webdav endpoint /remote.php/dav/uploads to create a new upload folder.  It is telling me permission denied with a 403.  I am using a remote file storage via SMB as well as LDAP for user authentication.

I have been trying out the webdav troubleshooting link that floats around but still have no luck.  I can't locate where the permission error is, or how to give the proper permissions to allow me to create the upload.

I am new to Owncloud and have been using it on an existing project for a client trying to extend functionality of a customer client, in this case working on chunked uploads.

I will post more details asked for shortly, I have to run out but wanted to get this question asked because this feature is time sensitive.

Thanks for the great product!

### Expected behaviour
Should let me create a new upload in the upload folder

### Actual behaviour
I get a Permission denied to create directory message.

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
9.0.1

**Updated from an older ownCloud or fresh install:**
upgrade

**Where did you install ownCloud from:**
- not sure.  Didnt set it up initially.

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.

```

**Are you using external storage, if yes which one:** local/smb/sftp/...

SMB

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

LDAP

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/25112 (webdav endpoints), https://github.com/owncloud/core/issues/11218 ([stable7] SFTP upload over webdav broken), https://github.com/owncloud/core/issues/3243 (HTTP error 403 when trying to upload with the OSX client or via webDav (CLI)), https://github.com/owncloud/core/issues/31843 (423 locked when retrying uploads with new endpoint), and https://github.com/owncloud/core/issues/29561 (Webdav COPY on new endpoint must trigger copy hooks).

**Comment by DeepDiver1975** [comment]
> MKCOL method on the webdav endpoint /remote.php/dav/uploads to create a new upload folder.

what is the exact request?
please keep in mind that the user id has to be part of the url you upload to
/remote.php/dav/uploads/$user/

$user being the user id of the user who is uploading

**Comment by michaelsharpe** [comment]
@DeepDiver1975 OMG!  Thank you so much! I have been trying to figure this out for a couple of days now.  There is not much documentation for how to utilize the upload endpoint other than the linked article at https://dragotin.wordpress.com/2015/06/22/owncloud-chunking-ng/.

This definitely seems to have fixed this part of my problem.  Hopefully I can get on now with successfully completing a flow for large file chunked uploading.

My sincere appreciation!

**Comment by phil-davis** [comment]
Also, as I'm sure you are aware, the ownCloud, PHP and Ubuntu versions quoted are all EOL.
