### ISSUE TITLE
MOVE on chunked upload

### ISSUE THREAD

**Issue by michaelsharpe** [owncloud/core#31973]
I posted an issue yesterday trying to solve an issue I was having with chunked upload.  I hit another seeming wall with the process.  As there is not much documentation for this process, i thought I would ask again, and perhaps @DeepDiver1975 might be able to help.

Currently, I am now uplloading each chunk to the endpoint /owncloud/remote.php/dav/uploads/admin/:uploadid/:chunknumber.  I increment the chunk number for each new chunk.  I wind up with a file with a bunch of numbered files in it.

Once all chunks are completed, I then call a MOVE command on /owncloud/remote.php/dav/uploads/admin/:uploadid with the location to move the file to.  The file moved successfully, but it is just the same folder with all the numbered files in it. The chunks were not assembled on the move.

What am I doing wrong?  I have scoured the internet to find info on this without much luck,

Thanks in advance!

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/11106 (Parallel upload of chunks), https://github.com/owncloud/core/issues/15647 (Work directly on storage in chunk upload mode), https://github.com/owncloud/core/issues/16278 (Problems with Chunked upload), https://github.com/owncloud/core/issues/8955 (Web Based File Upload Chunking), and https://github.com/owncloud/core/issues/17066 (Upload movie fail : chunking loop).

**Comment by phil-davis** [comment]
It depends if you are doing the "old" or "new" chunking. Sounds like "new" chunking. Have a look in:
https://github.com/owncloud/core/blob/master/tests/acceptance/features/bootstrap/WebDav.php
The clues are in:
``userUploadsChunksUsingNewChunking()``
which does:
``userCreatesANewChunkingUploadWithId()``
then upload each of the chunks:
``userUploadsNewChunkFileOfWithToId()``
then do the move to put the file together in place:
``userMovesNewChunkFileWithIdToMychunkedfile()``

https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdav/webdav-related-new-endpoint.feature
has test scenarios that call the above stuff, and do small multi-chuck uploads.

**Comment by DeepDiver1975** [comment]
see here: https://github.com/owncloud/core/blob/fe5aef885b58dc8adb8b553d2fcdef8d1587f7c0/apps/dav/bin/chunkperf.php#L74

**Comment by michaelsharpe** [comment]
Thanks for the response!

I am using the new chunking method.  I have looked over the linked resource, and I think I see what is going on (I am not a PHP dev, so some of the syntax is a little new for me).

I still can't quite locate where my code is going wrong however... I will share the two major places that are executing the calls:

```javascript


```

uploadUrl is: `http://myowncloudinstance/owncloud/remote.php/dav/uploads/${username}/${uploadId}`

**Comment by phil-davis** [comment]
In ``WebDav.php`` ``moveNewDavChunkToFinalFile`` it sets up:
```
$source = '/uploads/' . $user . '/' . $id . '/.file';
```
That finds its way through to the URL for the MOVE.
I think you need a "magic" ``/.file`` on the end of ``/uploads/username/uploadid`` - and that will trigger the endpoint code that re-assembles the file.

**Comment by michaelsharpe** [comment]
omg!  It worked!  Thank you again so much.

I will put together some documentation for getting chunked upload working with the API for anyone else like me that might have to interact with it.  The /.file part wasn't documented anywhere, so thank you for pointing that out to me.

You guys rock.

**Comment by michaelsharpe** [comment]
Another question, if I may.  Do you know if there is anything I need to look out for, like the chunked files being compressed or anything like that?

It is working now, but after doing a test, any dmg file uploaded this way and then download seems to be seen as invalid.  Are there limitations on file types it might work with, or any thing I need to do to prevent possible file corruption?

**Comment by phil-davis** [comment]
Hmmm - acceptance tests are the new "documentation" ;)
