### ISSUE TITLE
UI Tests for Settings page

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#31983]
Add UI acceptance tests for the Settings page, to check that various options can be switched on/off etc successfully in the UI.

- [x] Admin Sharing settings (lots of checkboxes there)
- [x] Selecting a language for public link notification email (coming in PR #31869 )
- [x] Admin General - see what UI elements there are useful to auto-test
- [x] Personal General - name, email...
- [x] Personal Security - App Passwords create/delete

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/29991 (UI test for creating a folder with existing name), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), and https://github.com/owncloud/core/pull/31225 ([stable10] UI tests for reset password).
