### ISSUE TITLE
About mails sent by the ownCloud server and the "From" mail header

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#31982]
Emails sent by ownCloud has a specific "From" header that can be set in the general settings for the admin (email server section). You can specify the email address ownCloud will use to send emails.

Email servers usually allow to include a displayname (probably more user-friendly) along with the email address. This is usually displayed in the email server as `My friendly name <gg@gibberish.gib>` instead of `<gg@gibberish.gib>`.
I guess this displayname should be associated with the email, although I don't know how the email servers will behave if multiple displaynames are used with the same email.

From a technical perspective, the ownCloud mailing component automatically set the "From" header with the one set in the configuration only if that header hasn't been set in the email. In this case, the "From" header will just use the email address set in the configuration.
If we want to include a displayname, there are a couple of things to be considered:
* Should the displayname be part of the email configuration? Should this be used as part of the default email address?
* Do we want to include specific support in some parts of ownCloud (notifications, for example) to use a different displayname and / or email address other than the default?

In addition, while custom email headers can be added, we'll likely need to rely on the underlying library used by the ownCloud's email component, or add support on ownCloud. Note that these headers might not be visible to the user in whatever email client he might use.

Some additional research is in https://github.com/owncloud/core/issues/31876#issuecomment-400263017

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @PVince81, and @pmaier1.

Possibly related issues are https://github.com/owncloud/core/issues/14909 ("Duplicate headers received from server" error), https://github.com/owncloud/core/issues/30576 (OwnCloud falsely reports issues with Headers), https://github.com/owncloud/core/issues/27636 (LDAP issues with owncloud server), https://github.com/owncloud/core/issues/16813 (Use GnuPG to encrypt mails send by ownCloud), and https://github.com/owncloud/core/issues/11005 (OwnCloud MAC Server Unicode-problem).
