### ISSUE TITLE
Cannot upload SSL certificate

### ISSUE THREAD

**Issue by nlighteneddesign** [owncloud/core#31991]
### Steps to reproduce
1. Launch new docker service
2. Update config.php to have 
3. 'enable_certificate_management' => true,
4. Generate key: `openssl req -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem`
5. Upload the certificate ( I also tried the key with the same results)

### Expected behaviour
Tell us what should happen:
You can now access the site with SSL

### Actual behaviour
Tell us what happens instead:
I get a message at the top of the screen and nothing in the logs.
`An error occurred. Please upload an ASCII-encoded PEM certificate.`

### Server configuration
**Operating system**: docker.

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
10.0.8 Stable

**Updated from an older ownCloud or fresh install:**
Fresh

**Where did you install ownCloud from:**
docker

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
```
No errors have been found.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/15608 (SSL root certificates should be automatically converted on upload), https://github.com/owncloud/core/issues/15409 (Can't create or upload files), https://github.com/owncloud/core/issues/13618 (can not upload file), https://github.com/owncloud/core/issues/583 (Can't upload files), and https://github.com/owncloud/core/issues/2055 (WebDAV check fails when SSL client certificate is used).

**Comment by nlighteneddesign** [comment]
None of these are related.
