### ISSUE TITLE
config option to enable fallback to HTTP for federated shares does not work.

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#31999]
In the release notes:

https://doc.owncloud.org/server/10.0/admin_manual/release_notes.html#new-config-option-to-enable-fallback-to-http-for-federated-shares

> For security reasons federated sharing (sharing between different ownCloud instances) strictly requires HTTPS (SSL/TLS). When this behavior is undesired the insecure fallback to HTTP needs to be enabled explicitly by setting 'sharing.federation.allowHttpFallback' => false, to true in config.php.

But when I enable this option in both of my servers, I get this error when trying to share something with a user in the other server:

`"Failed to notify remote server of federated share, removing share (cURL error 60: SSL certificate problem: self signed certificate in certificate chain)`

oC 10.0.8

Sharing between user1@172.42.16.191/owncloud and user2@172.42.16.224/owncloud

I know I should edit the hosts file and give the server a name, but it has to work with IP too, right?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/31194 (Federated share http fallback switch not working), https://github.com/owncloud/core/pull/30198 (Default HTTPS for fed sharing & config option for allowing fallback), https://github.com/owncloud/core/issues/17952 (Sharing doesn't work), https://github.com/owncloud/core/pull/30646 ([stable10] Flag to enable http fallback when creating fed shares), and https://github.com/owncloud/core/issues/22215 (Federated share doesn't produce status icon any more).

**Comment by patrickjahns** [comment]
@voroyam 

Can you double check, that the servers do not send a 301 to redirect from http to https ? 
Seems more like an infrastructure issue

**Comment by voroyam** [comment]
I do not know how to check that
