### ISSUE TITLE
Extend maintenance:repair to allow runtime repairs.

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#31995]
~Right now repair steps can be executed whilst in production with `occ maintenance:repair` and relies on the individual repair step to protect itself from maintenance mode etc.~

We could extend the `maintenance:repair` command to have a `--runtime` or `--production` command to run only those that can run in production without maintenance mode, and protect all others with a maintenance mode check.

cc @PVince81

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/13281 (Repair step to clean up oc_properties), https://github.com/owncloud/core/issues/14109 (apache should run without mod_dav), https://github.com/owncloud/core/issues/25164 (Allow user specific maintenance mode), https://github.com/owncloud/core/issues/31464 (File cache repair step detection should not run on every upgrade), and https://github.com/owncloud/core/pull/30989 (Remove pagination from the repair step).

**Comment by tomneedham** [comment]
My bad, maintenance mode is enabeld by this command: https://github.com/owncloud/core/blob/6b521b468ce3b197492d785c4c2d7466007b374e/core/Command/Maintenance/Repair.php#L101

**Comment by PVince81** [comment]
Hmm, but this also means that the repair step will induce a maintenance mode and might surprise admins. We could either add a confirmation prompt or refuse to run if not in maintenance mode ?

**Comment by tomneedham** [comment]
Added initial stuff here - got hung up adding tests around \OC\Repair which doesn't use DI and has static stuff. https://github.com/owncloud/core/commit/25921a0b4f1471e1c5fda9d4bff5b99fae893ed1

**Comment by tomneedham** [comment]
> We could either add a confirmation prompt or refuse to run if not in maintenance mode ?

I agree, prefer to fail if maintenance mode is no enabled and prompt. Right now it just does it.
