### ISSUE TITLE
Extend Webdav files search API on REPORT

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#31993]
- https://github.com/owncloud/core/issues/25373#issuecomment-231043363
- https://github.com/owncloud/core/issues/25373#issuecomment-398474054
- pagination?

Some topics could be relevant for the Gallery app to be able to search by albums

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/31873 (Search API based on webDAV report), https://github.com/owncloud/core/issues/11340 (zero file size on webdav), https://github.com/owncloud/core/issues/16756 (Prevent WebDAV delete of user's files folder), https://github.com/owncloud/core/issues/11284 (WebDAV Permissions report wrong Sharing permissions), and https://github.com/owncloud/core/issues/28615 (Webdav API to access files by fileid).
