### ISSUE TITLE
[Feature Request] occ config:app:list, config:system:list

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#32006]
We currently have (as of 10.0.8):
```
      config:app:delete
      config:app:get
      config:app:set
```
```
      config:system:delete
      config:system:get
      config:system:set
```
But there is no ``config:app:list`` command (for a given app name provided).
This FR would list all config names available for a particular app.
If not possible for all apps, this can be done eg for core and be documented

True in the same way also for ``config:system``, ``config:system:list``

How does an admin know which names are available in eg the core app or in system?
This also would relieve documentation needs

@PVince81 @VicDeo

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/12530 (Feature Request), https://github.com/owncloud/core/issues/8569 (Feature requests), https://github.com/owncloud/core/issues/15789 (request for occ ldap:list-config command), https://github.com/owncloud/core/issues/3173 (  feature request: confirmation for admin), and https://github.com/owncloud/core/issues/25708 ([Feature Request] ./occ user:logonlist).

**Comment by phil-davis** [comment]
Note that there is:
```
config:list
```
which lists everything in the "system" config (``config.php``) and the "app" config - key-value pairs that are set for each of the apps. And it takes the app name or ``system`` as a parameter, which shows just the relevant section. So I think viewing the actual currently set values is covered.

But when you enable an app, then it will be using defaults for values that have not been set. e.g. my test system ``files_sharing`` happens to currently have:
```
./occ config:list files_sharing
{
    "apps": {
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "0.10.1",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        }
    }
}
```
But there are lots of ``files_sharing`` options that can be set.

A command that lists all the possible settings, including those that are currently taking a default value, would be useful. The challenge will be exactly how to "query" an app and have it tell you, or have "registered", all the settings keys and defaults that it uses.

**Comment by PVince81** [comment]
@mmattel occ app:list gives you the list of installed apps. The keys used in the configs are the app ids, assuming apps aren't cheating. Documenting this in the occ command help could be enough.

**Comment by mmattel** [comment]
This issue is two fold.

The original intend of having a occ command listing app and system data is available with config:list. Did not recognized that. But the config:xxx commands are documented very basic and therefore I created a doc issue as a reminder.

On the other hand side, when you want to change a setting, you might use config:list to get infos about but again you struggle because it is not clear which keys are present and changable and what values are allowed/default. Pls see the doc issue and the comment from @phil-davis above for more details.
