### ISSUE TITLE
[Feature Request] Add UI for switching email language when user is generated

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#32005]
### Steps to reproduce
1. As admin, create a new user
2. Have "sent eMail to user when created" enabled
3. eMail is sent in the language the admin has set in his **personal** settings

### Expected behaviour
Default language should be definable, see similar merged PR:
https://github.com/owncloud/core/pull/31869 (Add UI for switching public mail notification language)

### Actual behaviour
eMail is sent in the language the admin has set in his **personal** settings.
This can be very challenging in international situations and does not look professional.

The admin might have language A in his personal settings but eMails must be send out in language B because of internationality

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.8

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar

@PVince81 @VicDeo

**Comment by mmattel** [comment]
Great idea, I like it.
There should be a default for ease of handling

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/8569 (Feature requests), https://github.com/owncloud/core/issues/12530 (Feature Request), https://github.com/owncloud/core/issues/14599 (Add "login as user" feature), https://github.com/owncloud/core/issues/26170 ([UI] User management: Sorting feature), and https://github.com/owncloud/core/issues/2696 (Feature Request: Disabling file uploads for specific users).

**Comment by pmaier1** [comment]
In general the request does not fit with keeping things simple and it does not make much sense to me to let the admin choose the user's language upon creation in oC webUI as larger installations anyway use LDAP for user management and there are other ways to create users as well (OCC, Provisioning API). A generalized setting for the admin to choose the language (default = English) for all unknown recipients at once would be preferable from my POV.

**Comment by mmattel** [comment]
... which would mean, that the language definition should be part of the user creation process (gui, occ)

**Comment by plastikschnitzer** [comment]
Still a highly appreciated enhancement!
