### ISSUE TITLE
Personal language selection broken in core master

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32012]
### Steps to reproduce
1. Login as some user
2. Go to Settings, Personal
3. Choose a language

### Expected behaviour
Language names are shown in the dropdown

### Actual behaviour
Language codes  are shown in the dropdown
![screenshot_2018-07-09 - owncloud 1](https://user-images.githubusercontent.com/1535615/42435919-ec0b9272-8377-11e8-8e09-b7e5c6df5da1.png)

### Server configuration
Current core master development

Looks like broken by transifex auto-commit https://github.com/owncloud/core/commit/8958b66a37b12245b3a62127d2f4caa87394b250

webUI acceptance test now fails:
https://drone.owncloud.com/owncloud/core/8510/390

```
--- Failed scenarios:

    /drone/src/tests/acceptance/features/webUIPersonalSettings/personalGeneralSettings.feature:7
```
The test tries to switch language to Russian.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/31048 (Backport of languages from master), https://github.com/owncloud/core/issues/11608 (master build broken), https://github.com/owncloud/core/issues/12176 (master build broken), https://github.com/owncloud/core/issues/18512 (Master broken), and https://github.com/owncloud/core/issues/15913 (Public sharing broken on master).

**Comment by phil-davis** [comment]
See also issue #35970 where this happened again.
