### ISSUE TITLE
Set argument value as mandatory for occ config:app:set command

### ISSUE THREAD

**Issue by davitol** [owncloud/core#32046]
![screen shot 2018-07-13 at 13 07 14](https://user-images.githubusercontent.com/10596560/42688761-e7f707c4-869d-11e8-98ca-adfd80ffb836.png)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/15789 (request for occ ldap:list-config command), https://github.com/owncloud/core/issues/14027 (No error message is thrown after setting a random key with the occ ldap:set-config command), https://github.com/owncloud/core/issues/22131 (OCC Setting an array Configuration Value fails), https://github.com/owncloud/core/issues/27428 (Lost 'secret' config value), and https://github.com/owncloud/core/pull/29727 (run occ command through the testing app).

**Comment by PVince81** [comment]
@davitol quick PR ?
