### ISSUE TITLE
Add ownCloud 'motto' to the footer of the ownCloud password changed successfully Confirmation email

### ISSUE THREAD

**Issue by davitol** [owncloud/core#32042]
**Mail of ownCloud Password Reset** ✅ 

![screen shot 2018-07-13 at 11 50 12](https://user-images.githubusercontent.com/10596560/42685332-f680f5ee-8692-11e8-89e9-8d19fbfa186d.png)

**ownCloud password changed successfully** ❌ 

![screen shot 2018-07-13 at 10 01 20](https://user-images.githubusercontent.com/10596560/42685504-68b814e4-8693-11e8-96e2-f3b5bcf11aa0.png)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @felixheidecke.

Possibly related issues are https://github.com/owncloud/core/issues/8826 ("Wrong Password" when successfully changing password), https://github.com/owncloud/core/issues/18784 (Change password flow), https://github.com/owncloud/core/issues/5469 (Missing password confirmation field), https://github.com/owncloud/core/issues/27654 (Exceptions raise when changing user password and no email was configured), and https://github.com/owncloud/core/issues/3746 (Can not change the password on OwnCloud-5.0.7).

**Comment by imujjwal96** [comment]
I'd like to work on this!
