### ISSUE TITLE
Extend occ to have a command to clear the general cache

### ISSUE THREAD

**Issue by settermjd** [owncloud/core#32045]
While researching https://github.com/owncloud/documentation/issues/4273, I had to delete the general cache several times and found that there is no occ command to manage this. Having it would be a genuine timesaver. 

I'm not exactly sure how it would be implemented. I'm thinking that the command would need to check the configuration to find out how the cache is stored and then use an accompanying command to clear it, based on the storage mechanism.

I assume the occ command help would look like the mockup below:

```console
cache
  cache:clear                      Clears ownCloud's general cache
```

**Comment by PVince81** [comment]
what's the "general cache" ?
