### ISSUE TITLE
Federation acceptance tests should really have different servers

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32053]
The federation acceptance tests in ``tests/acceptance/features/apiFederation`` ``tests/acceptance/features/webUISharingExternal`` currently run in a environment where 2 servers are started on 2 different ports. But the 2 servers are using the same database and data directory in the backend. So, for example, when a test scenario creates ``user1`` on the "local" server, then ``user1`` appears also "magically" on the "remote" server. This is:

- confusing when writing tests
- does not resemble a real-world supported environment
- means you cannot create really distinct ``user1`` with a different password etc. on "local" and "remote" so as to test sharing between users with the same UID on different servers
- lots of other testing hassles like the above

Make the test environment startup a really distinct "remote" server that has its own data directory and database...

**Comment by PVince81** [comment]
From my understand this moves us a little bit higher on the layers and bring us closer to "black box testing", where tests live on their own and have code that bootstrap 1-N instances of OC and test stuff on them.

Were there already any plans about moving to that level ?

@patrickjahns

**Comment by phil-davis** [comment]
@individual-it I think we have done this now in #32149 - closing.

**Comment by patrickjahns** [comment]
It's the first iteration - as discussed previously - it would be great to get it towards using our official `owncloud/server` container. 

Reason: 
We now assume the same version of federated servers works together. But we do not know if 10.0.1 and 10.0.9 can work together with the latest stable10 ...

**Comment by phil-davis** [comment]
Related issue in QA repo (which is also closed now) https://github.com/owncloud/QA/issues/538
@patrickjahns maybe you can write a new issue in the QA repo outlining the next steps/direction?
