### ISSUE TITLE
Account module infinite redirect with two factor challenge page

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#32059]
### Steps

1. Enable password_policy app
1. Enable twofactor_email app (the dummy challenge is "passme")
1. Login as admin
1. Create a user "user1"
1. Login as that user (challenge is "passme")
1. Log out
1. Expire the user's password with `occ user:expire-password user1`
1. Login as "user1"

### Expected result
Challenge page appears, after entering challenge the password expiry page appears.

### Actual result
Infinite redirect cancelled by browser.

### Version
ownCloud 10.0.9 + password_policy 2.0.0 + twofactor_email 0.0.1 (git)

There is a conflict between both pages wanting to appear after login.
A proposed solution is in PR #32058 to whitelist the two factor challenge page within the account module middleware.

@butonic

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/31547 (Introduce account modules), https://github.com/owncloud/core/issues/10630 (two-factor authentication), https://github.com/owncloud/core/pull/32058 ([stable10] Skip two factor challenge in account module middleware), https://github.com/owncloud/core/issues/25626 (Two factor authentication: Remove the challenge selection step when only one second factor method is available), and https://github.com/owncloud/core/issues/4720 (Feature request: two-factor authentication).

**Comment by DeepDiver1975** [comment]
fixed
