### ISSUE TITLE
Admin cannot change user password in Firefox

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32055]
### Steps to reproduce
1. Login as an admin and go to the Users page
2. Click the "pencil"  to change a user password

### Expected behaviour
The password field is displayed ready to enter a new password for the user.

### Actual behaviour
Nothing happens - cannot change a user password.

Do it in Chrome, it works fine.

### Server configuration
**Operating system**:
Ubuntu 18.04

**Web server:**
Apache or PHP dev server

**Database:**
mySQL

**PHP version:**
7.1.19

**ownCloud version:** (see ownCloud admin page)
10.0.9RC4
10.0.8

I think this is a Firefox "fug" = feature/bug. And I thought I had raised an issue about it before, but can't find it. This should be mentioned somewhere so admins realize not to use Firefox for this.

**Comment by PVince81** [comment]
Works for me on stable10 and Firefox 61.0.1 (64-bit) on openSUSE Tumbleweed

**Comment by phil-davis** [comment]
Not working for me on Firefox 61.0.1 (64-bit) on Ubuntu 18.04 with either of core ``stable10`` and/or ``master`` plus user_management app.

And works fine on Version 68.0.3440.75 (Official Build) (64-bit) on Ubuntu 18.04

Hmmm???

**Comment by PVince81** [comment]
can you try from Firefox from another machine connecting to the same server ?
then use your local Firefox against another server.

This will tell us where the issue might lie

**Comment by phil-davis** [comment]
Now I am home, so I fired up a local server and Firefox 61.0.1 (64 bit) on my Ubuntu 16.04 laptop.
It works fine! 
I struggle to believe that this problem is just for the Firefox 61.0.1+Ubuntu 18.04 combination.
I will try on Monday crossing over between laptop and desktop... and see if I can track down where the problem is.
