### ISSUE TITLE
Federation acceptance tests should test incoming and outgoing separately

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32066]
Federation acceptance tests should test permutations like:

- [ ] Incoming only - incoming stuff is accepted, outgoing is not allowed
- [ ] Outgoing only - outgoing stuff is accepted, incoming is not allowed
- [ ] Incoming and outgoing - it all works
- [ ] Neither - no federation shares are allowed

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/32040 (fix acceptance tests), and https://github.com/owncloud/core/issues/32053 (Federation acceptance tests should really have different servers).
