### ISSUE TITLE
DAVdroid can't sync to OwnCloud

### ISSUE THREAD

**Issue by joshbowyer** [owncloud/core#32076]
DAVdroid can't sync contacts or calendars to OwnCloud (it creates the calendar name but it is empty). Looking at an old ticket, I tried to run ## mysql> select * from oc_appconfig where configkey like 'remote_%'; ## which returned nothing.
### Steps to reproduce
1. Install and configure DAVdroid
2. Attempt to sync calendar and contacts

### Expected behaviour
They should be synced

### Actual behaviour
Nothing happens, DAVdroid log dump says 0 records to be synced, server log shows nothing even on debug

### Server configuration
Ubuntu 14.04

**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
5.5.9
**ownCloud version:** (see ownCloud admin page)
Owncloud 9.1.8
**Updated from an older ownCloud or fresh install:**
fresh install
**Where did you install ownCloud from:**
Ubuntu repo
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
404 Not Found

**The content of config/config.php:**

    <?php
    $CONFIG = array (
      'updatechecker' => false,
      'instanceid' => 'ocs10ct7dorv',
      'passwordsalt' => '**redacted**',
      'secret' => '**redacted**',
      'trusted_domains' =>
      array (
        0 => '**redacted**',
      ),
      'datadirectory' => '/mnt/owncloud_storage/owncloud_data',
      'overwrite.cli.url' => '**redacted**',
      'dbtype' => 'mysql',
      'version' => '9.1.8.2',
      'logtimezone' => 'UTC',
      'installed' => 1,
      'dbname' => 'ownCloud',
      'dbhost' => 'localhost',
      'dbtableprefix' => 'oc_',
      'dbuser' => 'ownCloud',
      'dbpassword' => '**redacted**',
      'loglevel' => 0,
      'appstore.experimental.enabled' => true,
      'check_for_working_webdav' => true,
      'check_for_working_wellknown_setup' => true,
      'check_for_working_htaccess' => true,
    );

Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

Enabled:
  - activity: 2.3.2
  - calendar: 1.5.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.4
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_antivirus: 0.9.0.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
SSL
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Trying to use WebDAV for calendar/contacts

### Client configuration
**Browser:**
firefox 63
**Operating system:**
Linux Mint 19
### Logs
#### Web server error log
```
Insert your webserver log here
```
nothing at all pertaining to this
#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
nothing at all pertaining to this
#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/13163 (I am not able to sync from owncloud Andriod app, please help), https://github.com/owncloud/core/issues/5312 (ownCloud hangs on sync), https://github.com/owncloud/core/issues/24324 (Owncloud not restore), https://github.com/owncloud/core/issues/23715 (ownCloud not syncing with KOrganizer), and https://github.com/owncloud/core/issues/8804 (Calendar not syncing from WebDAV Collaborator to OwnCloud).

**Comment by joshbowyer** [comment]
Finally figured it out, it was a stupid DAVdroid setting
