### ISSUE TITLE
Search API might return more results than the limit

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#32080]
### Steps to reproduce
1. Install and configure search_lucene app (or another search provider except search_elastic)
2. Upload several files
3. Use the search API with a limit so all the search providers returns results.

### Expected behaviour
If the limit set is 5, the seach API returns a maximum of 5 results

### Actual behaviour
If the limit set is 5, the search API return a maximum of 5*number_of_providers. This isn't what the user ask for.

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** apache 2.4

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.9

**Updated from an older ownCloud or fresh install:** fresh install

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/16548 (View->search() returns empty results), https://github.com/owncloud/core/issues/21065 (Search in Share API should not return the user that are making the request), https://github.com/owncloud/core/issues/13292 (sort search results), https://github.com/owncloud/core/issues/8899 (Share: Number of results limited before the search pattern has been applied), and https://github.com/owncloud/core/issues/10526 (Paged Results search operation not properly cancelled ).

**Comment by PVince81** [comment]
@jvillafanez assigning you as you might be quick and already know where to look.

Hopefully not more than 0.25md ?
