### ISSUE TITLE
upgrade 10.0.0.8 > ...0.9, failed integrity checks

### ISSUE THREAD

**Issue by thommierother** [owncloud/core#32088]
Upgrade from last RC3 and upgrade for files_antivirus:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- core/doc/admin/_images/encryption15.png
		- core/doc/admin/_images/encryption1.png
		- core/doc/admin/_images/encryption3.png
		- core/doc/admin/_images/encryption14.png
- files_antivirus
	- EXTRA_FILE
		- controller/settingscontroller.php
		- controller/rulecontroller.php
		- lib/db/rule.php
		- lib/db/itemmapper.php
		- lib/db/item.php
		- lib/db/rulemapper.php
		- lib/scanner/local.php
		- lib/scanner/external.php
		- lib/adminpanel.php
		- lib/status.php
		- lib/scanner.php
		- lib/appconfig.php
		- lib/notification.php
		- lib/item.php
		- lib/avirwrapper.php
		- lib/activity.php
		- lib/backgroundscanner.php
		- lib/iscannable.php
		- lib/cron/task.php
		- lib/scannerfactory.php
		- lib/content.php

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [core/doc/admin/_images/encryption15.png] => Array
                        (
                            [expected] => 
                            [current] => cdad88ad43f077efa6165c4bef82e74f1ce61c0a69d99d6ced8e1d5f073cceb936c5787e879f2c7a8bdb6b64e552d135a8f814c562da8efb1ff667be94e7a09d
                        )

                    [core/doc/admin/_images/encryption1.png] => Array
                        (
                            [expected] => 
                            [current] => 0fd40edbca9def5c0dd30e76e4445668e4981ad7f0c84fed7d4932b639d6e0ef6f20ab7ca8b1b13bad44bb21e7ec4bc2489cf68c66ac51eaefb82e6d3e47f976
                        )

                    [core/doc/admin/_images/encryption3.png] => Array
                        (
                            [expected] => 
                            [current] => af9dfc34ea8cf9a641a8f3f1751f50ca1e1bfdbd28a7140066da372c995ffd1d67b40a4a198ab5432f3f88d1ec2e869c2d2178078d1ed8b2169a0b62dbcce00e
                        )

                    [core/doc/admin/_images/encryption14.png] => Array
                        (
                            [expected] => 
                            [current] => 194f81031ae900f331f1d2cb24ec5fa24b5eeda4b277955d93b1d4aae4bc1f5e9a5416accea474107619f1101821f48181279a68f9a1038460fb296267db2526
                        )

                )

        )

    [files_antivirus] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [controller/settingscontroller.php] => Array
                        (
                            [expected] => 
                            [current] => b25925eba303a9c6f66120e88181663b3039297355491e7684143f4e313ba3fbb0d4a07895776e9d6193953a4ef3f135776a595b462e757feb05958894157050
                        )

                    [controller/rulecontroller.php] => Array
                        (
                            [expected] => 
                            [current] => e766dcbd08f053b427e423c29f76f1fcd59fe44d9ec826903784e0f95a02aefa3841c99718b05861c387a050a319f4ae935b35d0748f339231af59b521a75912
                        )

                    [lib/db/rule.php] => Array
                        (
                            [expected] => 
                            [current] => 7f865d67c299350efce7479be129c83785dcde27588bd626babfbfc8822423118da51910cb5e46c799e3223d1c4b02cdb91de67215de62dd1d11b58ca36def39
                        )

                    [lib/db/itemmapper.php] => Array
                        (
                            [expected] => 
                            [current] => 7fa8f7d930424a01878c221cc28ec976b9692bf737819aeac7965c5365140d1989f625b86f5825bd4a4489261d104062f82767b0a7623055361b7183bc53d793
                        )

                    [lib/db/item.php] => Array
                        (
                            [expected] => 
                            [current] => 4b4647f37c02dfe8fe0c2ad1f9dcc13feaf5d3f71e49842331a129d7542e8b4eddeb517ca0cf7db7f550bb49f6af89b74d3189dd9da444f41539caea6127cd5b
                        )

                    [lib/db/rulemapper.php] => Array
                        (
                            [expected] => 
                            [current] => 9af4fdcc7ccd742a88344cee5da684ffd76aef9e3ca453faade3b63247c3af194fa42c9975c81f62c7815cd75eaefa94fd7104a789919ade0475f00727346789
                        )

                    [lib/scanner/local.php] => Array
                        (
                            [expected] => 
                            [current] => f61de47f319c0e387df5a0d25db79ee040470e05157322a259becb2bd885263ae8689d6ee5892b7becef03e2bdfa2fbd36a0c46b38c7d3dc25c0295f2e6b99bb
                        )

                    [lib/scanner/external.php] => Array
                        (
                            [expected] => 
                            [current] => 61232c94e761b2e625ca7f3118a913f6d05c451e217081303342dcc6c798e424e16419ee7d0d373f39458075c325d8d282e38846ba3a7f0481f0251e5070e4d0
                        )

                    [lib/adminpanel.php] => Array
                        (
                            [expected] => 
                            [current] => de6903f41ab532189caf1069e12b582b3bedf1fce76a444dd3b9d5b132b06a6148d331a4213d507d2a3d72582c29b90d82662c232502ca4070d1025315b69f89
                        )

                    [lib/status.php] => Array
                        (
                            [expected] => 
                            [current] => ec43512e3fcd353ee7ada6aa555425d966f88f9ec58ff5237ec7a7a6e856eea215d0d4c0d6cd63d24db2ef9aef6b809e1831fbc03ab6814bec719e14eaf28d0c
                        )

                    [lib/scanner.php] => Array
                        (
                            [expected] => 
                            [current] => 9a463e7ea1c5d3650e71418c511834fa28320e8224c4d501d794b762d7046b0a18d77db72e35dbbccd45e21f12ae1e665ff7643f4dca3b6d541e5dfd338a1126
                        )

                    [lib/appconfig.php] => Array
                        (
                            [expected] => 
                            [current] => fa596159d83e7ebdc7105d4557a4076f6ec909d4e4527921e9e79173aa895bff8a55f426dbce312365348c9a0c3ffe0d4202aa82f9713d08becb5b976ed8551b
                        )

                    [lib/notification.php] => Array
                        (
                            [expected] => 
                            [current] => 5e449d3cb87f85995a13df92df6649f105e1e2beacfe1ae80beec2c97eaaaba55106d9cc48ff8d918a5fe0b4f513d491c95ce3f2f3b9632ff778de9ff113b3a1
                        )

                    [lib/item.php] => Array
                        (
                            [expected] => 
                            [current] => e444e5654b354b960479aa92aaefe6b6ba8cd25f396c24aaacd4367c26fd0655c6503b48b39430cfb6712ef11151611395afae89b172712d5abe0ec88927cdbd
                        )

                    [lib/avirwrapper.php] => Array
                        (
                            [expected] => 
                            [current] => ca56166f24811107ad5c99d104894e86841221017500bbb5ee48d18bebdcc605ee70d07182ec28247c2ea0380687dd2cf39034eda6394211da1bf6cc5b774eca
                        )

                    [lib/activity.php] => Array
                        (
                            [expected] => 
                            [current] => 165046882a972165dd8cf245e25c48276c3303c678ed0969554c94bc51dea56ec12c13e344d9e97ef4dd46beaa301311785109f96e05bdb3a78c3cafbfa4b8a6
                        )

                    [lib/backgroundscanner.php] => Array
                        (
                            [expected] => 
                            [current] => f3ef05203ecfb6b05d5bad6120c610fa9a109fbdb4eb0082df8d49074b4575945b0ca1d959acceb5f0d67b4b1eec4e6fd7ace42e04eb311046e69a9fd123bd22
                        )

                    [lib/iscannable.php] => Array
                        (
                            [expected] => 
                            [current] => b58811381fd28f331fa0c45369f202791cc539b5ed072f73db784129adf1f86fe1d4a4fb68bdaa06d90fa0d4750465577c54f568a035b58a025c5418b80e94c4
                        )

                    [lib/cron/task.php] => Array
                        (
                            [expected] => 
                            [current] => 77a740d11f8d7bf78cd2daf0c115eb2324d4d972142875f029cfb968f3650889c0488bcf1335db3b32218cc80fba87d662c3be6e0a2b5edfa117aeed00fbb722
                        )

                    [lib/scannerfactory.php] => Array
                        (
                            [expected] => 
                            [current] => 16bec47b1727db8b37bb31483bccbc34313eedefafc09efe829c9dde9156f0291ea6e258abbff46a9d013abf896414c72a347ef372c3a4c179bffdb73244a277
                        )

                    [lib/content.php] => Array
                        (
                            [expected] => 
                            [current] => 073ff20c9174dafaf31a098f51189aebb88fa817e92452d7a4cf7f2bd220a809ae544e73e358d8420124b277b88d1294595775a987828b6758de5061c1c36eb4
                        )

                )

        )

)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/28236 (Upgrade failed), https://github.com/owncloud/core/issues/29143 (failed upgrade to 8.0.16), https://github.com/owncloud/core/issues/23769 (Integrity check always fails), and https://github.com/owncloud/core/issues/23926 (Integrity check failed with a lot of [EXTRA_FILE]).
