### ISSUE TITLE
[Feature Request] Improve files_external:list to show a short list of mounts for a given user

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#32084]
Referencing 10.0.9

If you to run eg  ``sudo -uwww-data ./occ files_external:list user_id``
you get a list of mounts and its long details, not that good to read.

**Feature Request**
add an option to have a short listing of the mounts showing only
- Mount ID
- Mount Point
- Type

**Benefit**
If you run the command ``sudo -uwww-data ./occ files:scan --path="user_id/files/mount_point"``
You need to know which mounts are available to scan for the user.
Highlighting basic information much better from the command files_external:list.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/8569 (Feature requests), https://github.com/owncloud/core/issues/12530 (Feature Request), https://github.com/owncloud/core/issues/27589 (Feature Request / Question - Show (live) user activity), https://github.com/owncloud/core/issues/30641 ([Feature Request] extend ./occ files:scan to list scannable mounts for a given user), and https://github.com/owncloud/core/issues/4451 (feature request: increase user password strength).

**Comment by mmattel** [comment]
https://github.com/owncloud/docs/issues/419 (New option in occ command files_external:list `--short`)
