### ISSUE TITLE
Password reset form error message not readable for a user

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#32154]
### Steps to reproduce
1. Request password reset email
2. Click on link, enter password, click reset

### Expected behaviour
Works, or error message

### Actual behaviour
Very not helpful message for a user....
<img width="468" alt="screen shot 2018-07-25 at 14 39 05" src="https://user-images.githubusercontent.com/660805/43204425-ac2b474e-9018-11e8-8801-afe8de6470d1.png">

10.0.9

Checking owncloud.log...

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/8591 (Error Message Not Readable), https://github.com/owncloud/core/issues/8715 (Warning for password reset is not readable), https://github.com/owncloud/core/issues/10092 (User Password Reset), https://github.com/owncloud/core/issues/13087 (Error messages), and https://github.com/owncloud/core/issues/32038 (App password error after password reset).

**Comment by PVince81** [comment]
where did that response code come from ? mail server ?
