### ISSUE TITLE
Problem print preview files JPG Format

### ISSUE THREAD

**Issue by ribascr** [owncloud/core#32187]
### Steps to reproduce
1. Upload a file jpg in (A4 Format)
2. Click in file to open preview
3. Press Ctrl+P for print this JPG
4. Check a espace on left and JPG File are deconfigured to print

### Expected behaviour

The print preview should only show the JPG

### Actual behaviour

A left margin appears, preventing correct printing

### Server configuration
Linux Ubuntu 16.04

**Web server:**
 apache2                             2.4.18

**Database:**
 mysql-server-5.7                    5.7.22

**PHP version:**
 libapache2-mod-php7.0               7.0.30

**ownCloud version:** (see ownCloud admin page)
version":"9.1.8.2

**Updated from an older ownCloud or fresh install:**
No

**Where did you install ownCloud from:**
apt repos

{
    "system": {
        "updatechecker": false,
        "instanceid": "ocsxeexzuime",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.0.0.82",
            "192.168.1.115",
            "192.168.1.249",
            "localizasjrp.ddns.net"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/10.0.0.82\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.8.2",
        "dbname": "ownCloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

**Are you using external storage, if yes which one:** local/smb/sftp/...
Only local Storage in two disks

**Are you using encryption:** yes/no
IN access https (letsEncrypted)

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Dont use

### Client configuration
Google Chrome Versão 67.0.3396.99 (Versão oficial) 64 bits

**Operating system:**
Windows 10 Professional 1803

#### Web server error log
No errors in log about this problem

#### ownCloud log (data/owncloud.log)
No errors in log about this problem

#### Browser log
No errors in log about this problem

Ps: I did not find this fix in change version logs

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/26807 (Unable to generate a preview for JPG and JPEG files only.), https://github.com/owncloud/core/issues/29017 (Preview errors in log when accessing .jpg files), https://github.com/owncloud/core/issues/3325 (Problem to synchronize files), https://github.com/owncloud/core/issues/597 (Problem with overlapping files), and https://github.com/owncloud/core/issues/26478 (Photoshop file preview issue).

**Comment by PVince81** [comment]
opening the preview with one click is likely not enough, you need to right click on the image in the slideshow and open the image URL in a new tab, then ctrl+P.

there might be a technical solution where the slideshow preview must could provide different CSS when printing.
