### ISSUE TITLE
Make proper GitHub releases

### ISSUE THREAD

**Issue by benrubson** [owncloud/core#32186]
Hi,

Could it be possible to make proper [GitHub releases](https://github.com/owncloud/core/releases),
so that the following URL correctly returns the latest release please ?
`https://api.github.com/repos/owncloud/core/releases/latest`

As [here](https://github.com/owncloud/client/releases) : `https://api.github.com/repos/owncloud/client/releases/latest`

We would then be able to easily schedule release checks, from monitoring tools etc...

Thank you very much 👍 

Ben

**Comment by PVince81** [comment]
I guess we could. There is one little difference that the "core" repo only contains the platform code, but the release itself contains more app. If that semantic difference isn't of importance then we could consider that.

It would mean uploading the tarball to Github's released section.

@pmaier1 @hodyroff @jnweiger @patrickjahns thoughts ?

This would be an additional item on the release checklist.

**Comment by patrickjahns** [comment]
To be considered when publishing of releases is automated. Github could be a target in that process. 

I am against having another manual step to be done for a release

**Comment by patrickjahns** [comment]
> Can't it be simply done by editing what already exists in the releases section so that the entries are correctly seen as releases, without having to re-upload files etc... ?

ownCloud as it is provided via our official mirrors, consist of ownCloud ` core` (this repository) as well as other apps. So a ownCloud release (as in "package") - so the final artifact of being an installable ownCloud differs a lot from what github provides by default. 

As said - this can be considered *after* the publishing steps have been automated.

**Comment by benrubson** [comment]
_Closing this for now, feel free to reopen if needed / finally possible._
