### ISSUE TITLE
Storage wrapper in testing app to simulate upload timeout

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#32183]
To test cases like https://github.com/owncloud/core/pull/32170, one currently needs to patch the OC code to simulate timeouts.

One idea would be to add an extension for the "testing" app to enable random or controlled failures during uploads:
- have oc_appconfig setting for the "testing" app to enable chunk failures
- oc_appconfig setting to specify what chunk indices will have a timeout failure (ex: 1, 5, 8 or none for random)
- the testing app will install a storage wrapper which will, when configured, introduce a timeout in file operations like "fopen" and "file_put_contents"

@DeepDiver1975 @phil-davis @patrickjahns @davitol @butonic

**Comment by PVince81** [comment]
this could be used to generate deterministic failures in web UI acceptance tests (chunked upload) by setting expected failures on specific chunk ids

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/11729 (owncloud app upload issue), and https://github.com/owncloud/core/issues/5163 (No uploads possible - Insufficient storage).

**Comment by PVince81** [comment]
in general it depends whether you want deterministic or non-deterministic tests

in the case of deterministic you'll get exactly the failure you expect
non-deterministic, sometimes tests will pass, sometimes they might not... not ideal for CI

**Comment by patrickjahns** [comment]
@PVince81 
Please consider, that any behavior the testing app can/should change, is doable remotely. 

It's about keeping ownCloud as a "blackbox" which we can fortunately alter it's behavior inside to achieve deterministic outcomes. We are moving towards a `server <----> client` approach. Thus we will need to be able to provide "a client" with a implementation of the server api that can be altered. 

@individual-it 
`netem` as simulation is fine for using explorative (manual) testing - or additional explorative testing before/during/after a release. But as vincent said, for certain parts we require deterministic behavior to write stable test suites
