### ISSUE TITLE
Manual upgrade fails on shared server - Doctrine\DBAL\Schema\SchemaException

### ISSUE THREAD

**Issue by jfou** [owncloud/core#32194]
Many thanks for any assistance, Owncloud community!

### Steps to reproduce

1. Follow manual installation steps for upgrade to 10.0.9 with one exception (since install is on shared server w/o root or shell):  Disabling Core Apps was not possible.

> 
> Before the upgrade can run, several apps need to be disabled, if they’re enabled, before the upgrade can succeed. These are: activity, files_pdfviewer, files_texteditor, and gallery. The following command provides an example of how to do so.
> 
> sudo -u www-data php occ app:disable activity
> sudo -u www-data php occ app:disable files_pdfviewer
> sudo -u www-data php occ app:disable files_texteditor
> sudo -u www-data php occ app:disable gallery

2.  Browse to public web location of owncloud, on which is displayed upgrade option.

### Expected behaviour
Upgrade completes

### Actual behaviour
Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Doctrine\DBAL\Schema\SchemaException: The column 'execution_duration' on table 'oc_jobs' already exists.

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version: 7.2

**ownCloud version:** (see ownCloud admin page) 10.0.6

**Updated from an older ownCloud or fresh install: Update

**Where did you install ownCloud from: Downloaded zip from Owncloud

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:
$CONFIG = array (
  'instanceid' => 'ocdkr1p6cecx',
  'passwordsalt' => '[something]',
  'secret' => '[something]',
  'trusted_domains' => 
  array (
    0 => 'mydomain.org',
  ),
  'datadirectory' => '/home/[admin user]/mydomain.org/owncloud/data',
  'overwrite.cli.url' => 'http://mydomain.org/owncloud',
  'dbtype' => 'mysql',
  'version' => '10.0.6.1',
  'dbname' => 'cfb_owncloud',
  'dbhost' => 'db.mydomain.org',
  'dbtableprefix' => 'oc_',
  'dbuser' => '[admin user]',
  'dbpassword' => '[something]',
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'updater.secret' => '[something]',
);

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**No.

```
With access to your command line run e.g.: No access

```

### Client configuration
**Browser:** FF 61.0.1

**Operating system:** Win10 64

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
07-30T15:24:37+00:00","remoteAddr":"[my ip]","user":"--","app":"core","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=GAxbMg8yC0UJCyBsdnobOwAEDCoqeFcXAgthJHNfalU%3D%3AnVoUIVe71lP937XOilKrE3xBDmNnEoEe2tMvBTd76is%3D","message":"starting upgrade from 10.0.6.1 to 10.0.9.5"}
{"reqId":"W18tta3smIYAADofd9gAAAAD","level":3,"time":"2018-07-30T15:24:59+00:00","remoteAddr":"[my ip]","user":"--","app":"core","method":"GET","url":"\/owncloud\/core\/ajax\/update.php?requesttoken=GAxbMg8yC0UJCyBsdnobOwAEDCoqeFcXAgthJHNfalU%3D%3AnVoUIVe71lP937XOilKrE3xBDmNnEoEe2tMvBTd76is%3D","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Schema\\\\SchemaException\",\"Message\":\"The column 'execution_duration' on table 'oc_jobs' already exists.\",\"Code\":40,\"Trace\":\"#0 \\\/home\\\/cfbsiteadmin\\\/mydomain.org\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/Table.php(480): Doctrine\\\\DBAL\\\\Schema\\\\SchemaException::columnAlreadyExists('oc_jobs', 'execution_durat...')\\n#1 \\\/home\\\/cfbsiteadmin\\\/mydomain.org\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/Table.php(323): Doctrine\\\\DBAL\\\\Schema\\\\Table->_addColumn(Object(Doctrine\\\\DBAL\\\\Schema\\\\Column))\\n#2 \\\/home\\\/siteadmin\\\/mydomain.org\\\/owncloud\\\/core\\\/Migrations\\\/Version20170213215145.php(19): Doctrine\\\\DBAL\\\\Schema\\\\Table->addColumn('execution_durat...', 'integer', Array)\\n#3 \\\/home\\\/siteadmin\\\/mydomain.org\\\/owncloud\\\/lib\\\/private\\\/DB\\\/MigrationService.php(403): OC\\\\Migrations\\\\Version20170213215145->changeSchema(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema), Array)\\n#4 \\\/home\\\/siteadmin\\\/mydomain.org\\\/owncloud\\\/lib\\\/private\\\/DB\\\/MigrationService.php(358): OC\\\\DB\\\\MigrationService->executeStep(20170213215145)\\n#5 \\\/home\\\/siteadmin\\\/mydomain.org\\\/owncloud\\\/lib\\\/private\\\/Updater.php(269): OC\\\\DB\\\\MigrationService->migrate()\\n#6 \\\/home\\\/siteadmin\\\/mydomain.org\\\/owncloud\\\/lib\\\/private\\\/Updater.php(223): OC\\\\Updater->doCoreUpgrade()\\n#7 \\\/home\\\/siteadmin\\\/mydomain.org\\\/owncloud\\\/lib\\\/private\\\/Updater.php(108): OC\\\\Updater->doUpgrade('10.0.9.5', '10.0.6.1')\\n#8 \\\/home\\\/siteadmin\\\/mydomain.org\\\/owncloud\\\/core\\\/ajax\\\/update.php(190): OC\\\\Updater->upgrade()\\n#9 {main}\",\"File\":\"\\\/home\\\/siteadmin\\\/mydomain.org\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/SchemaException.php\",\"Line\":120}"}
{"reqId":"W18wHa3smIYAAEJEeu4AAAAA","level":0,"time":"2018-
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/28236 (Upgrade failed), https://github.com/owncloud/core/issues/15493 (Manual upgrade ), https://github.com/owncloud/core/issues/26677 (occ upgrade fails with Sabre\VObject\Recur\NoInstancesException), https://github.com/owncloud/core/issues/5003 (upgrade script ignores failing ), and https://github.com/owncloud/core/issues/10349 (Debian testing upgrade fails).

**Comment by PVince81** [comment]
have you already run the update once before ? the error message looks like a former upgrade has been attempted and maybe failed

before reattempting an update, one needs to restore the backup of the database and data folder from before the update

**Comment by jfou** [comment]
Hello @PVince81 and thank you for the reply.

Yes, I attempted it from the updater app within OC, and it threw an error (cURL error 7: Failed to connect to localhost port 443). I went straight to manual install - incorrectly, it seems - without restoring the backup database.

I attempted to restore the database from a non-root terminal (since I'm on a shared server) using mySQL section from [OwnCloud documentation](https://doc.owncloud.com/server/10.0/admin_manual/maintenance/restore.html), but I received the "no such file" error for the default name of the backup ("owncloud-dbbackup.bak"). Looking at myphpadmin, I couldn't find anything that resembled a backup. 

Maybe I'm not doing the restore process right or misunderstanding from the OwnCloud documentation. If so, I apologize.

**Comment by PVince81** [comment]
As this is not an OC bug I'll close this ticket.

Please refer to http://central.owncloud.org/ (forums) for further help

**Comment by thalesmaoa** [comment]
OK, my problem is quite similar. Sorry to post in a closed issue. Maybe it can be reopened.
I had owncloud installed by ubuntu repository. By mistake I did remove owncloud-files package and all files in the folder were removed except data and config.

I just downloaded owncloud zip folder (10.0.9.7), extracted and it insist for an upgrade. When I try it, I get this same error reported.
