### ISSUE TITLE
"403 Forbidden" to "Move"

### ISSUE THREAD

**Issue by ankitpsaraogi** [owncloud/core#32207]
### Steps to reproduce
1. Create an excel file and let it sync via desktop client
2. Open the excel file, make some changes and save
3. Let it try syncing and you get this error

### Expected behaviour
It should have synced

### Actual behaviour
Instead I see a red cross on the file and the file doesn't get synced even after restart

### Server configuration
**Operating system**:
linux
**Web server:**

**Database:**

**PHP version:**
7.2
**ownCloud version:** (see ownCloud admin page)
NextCloud 13.0.5
**Updated from an older ownCloud or fresh install:**
Updated from 13.0.4
**Where did you install ownCloud from:**
Softaculous
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No errors have been found.

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ankitpsaraogi** [comment]
![image](https://user-images.githubusercontent.com/41514916/43506328-605b90fc-9587-11e8-9936-2f8a9bc30aba.png)
![image](https://user-images.githubusercontent.com/41514916/43506385-86be0e6e-9587-11e8-9159-a145007d7b9c.png)

**Comment by ankitpsaraogi** [comment]
Hi @ownclouders 
I tried the solution provided in  #10084 (403 Forbidden error and .htaccess patch to resolve) but it is not working even after editing the .htaccess file

**Comment by individual-it** [comment]
> NextCloud 13.0.5

@ankitpsaraogi This is the repo of ownCloud, you are using the nextcloud fork so you have to ask for the solution at NextCloud.
Or feel free to install ownCloud from https://owncloud.org/download/
Probably the easiest way to test is to use docker https://owncloud.org/news/how-to-set-up-an-owncloud-in-3-minutes/

**Comment by hodyroff** [comment]
Tested with oC 10.0.9 and oC Desktop Client 2.4.2. works perfectly. Please try with ownCloud and welcome to our community!
