### ISSUE TITLE
Details dialog JPG image is repeated

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32201]
### Steps to reproduce
1. Disable previews - in ``config.php`` set:
```
  'enable_previews' => false,
```
2. upload a JPG file
3. open the details panel

### Expected behaviour
The "sun and mountains" default thumbnail SVG should display once,
and the filename can appear to the right of it, like for other file types such as txt or pdf.

### Actual behaviour
The "sun and mountains" default thumbnail SVG repeats across the width of the details panel.

![screenshot_2018-07-31 files - owncloud](https://user-images.githubusercontent.com/1535615/43442038-7c089f28-94bc-11e8-9f90-0b778caffdf9.png)

### Server configuration
Current git master or any.

**Comment by phil-davis** [comment]
For this case, the HTML has ``width: 100%`` specified. But for PDF, TXT etc that is not specified.
``width: 100%`` works more nicely in the case when previews are enabled. In that case a single "large" preview of the actual image is generated which covers the screen width. 

So it just needs an extra ``if`` somewhere to only add that ``width: 100%`` for images when previews are enabled.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/18910 (Share Dialog Problems repeating user list), https://github.com/owncloud/core/issues/2080 (Sharing App : Share Image repeating.), https://github.com/owncloud/core/issues/18449 (iPhone direct image uploads always named image.jpg), https://github.com/owncloud/core/issues/4543 (Images not shown), and https://github.com/owncloud/core/issues/6110 (in Share dialog).
