### ISSUE TITLE
Change the file locking for chunked uploads

### ISSUE THREAD

**Issue by micbar** [owncloud/core#32217]
### Steps to reproduce (difficult in this case)
1. Upload large file via desktop client.
2. Slow down the final assembly process of the chunked file.
3. Let the client run into timeout.
4. Client resends the last PUT, starts a second assembly process.
5. Second assembly process crashes the first one
6. This repeats over and over
7. Finally, one process assembles the file
8. Client shown multiple error messages (Timeout)
9. Client somehow follows up and gets in sync again.

### Expected behaviour
Second assembly process should fail, because of proper file locking.

### Actual behaviour
The repeating requests from the client interfere the assembly process

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
10.0.9

### Logfiles
Logfiles are at the corresponding enterprise issue.

## Possible Solution
Try to get an exclusive lock on the destination file before we start the assembly process in https://github.com/owncloud/core/blob/eda2a55adfdecbe6af0f9e8ad589f878b64c1912/apps/dav/lib/Connector/Sabre/File.php#L191

I tried to move this up
https://github.com/owncloud/core/blob/eda2a55adfdecbe6af0f9e8ad589f878b64c1912/apps/dav/lib/Connector/Sabre/File.php#L234-L241

This improves the behaivour by letting the first process succeed.

**Comment by micbar** [comment]
@PVince81 I tried this according to our planned approach.
I will test this further and post my findings back.

@DeepDiver1975 thanks for the tip. The destination file gets a shared lock. I think we need an exclusive lock to prevent other processes interfering with the first one.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/24737 (File Locked), https://github.com/owncloud/core/issues/26838 (File locking), https://github.com/owncloud/core/issues/28991 (file is locked), https://github.com/owncloud/core/issues/17066 (Upload movie fail : chunking loop), and https://github.com/owncloud/core/issues/2947 (Big file chunking: Last chunk upload takes too long).
