### ISSUE TITLE
Extend API of  IConfig to query all oc_preferences of an user

### ISSUE THREAD

**Issue by IljaN** [owncloud/core#32211]
Currently some foreach gymnastics with IConfig and IAppConfig are required to get all values for all apps of a user:
```php
$appList = $this->appConfig->getApps();
foreach ($appList as $app) {
	$userKeys = $this->config->getUserKeys($userId, $app);
	   foreach ($userKeys as $key) {
				....
	    }
}
```
Proposed additions to IConfig:
```getUserKeyValues($userid, $app)``` which returns an array of the stored key
```getAllUserKeyValues($userid)```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/7533 (Encryption Query), https://github.com/owncloud/core/issues/18388 (Extend provisioning api getUsers to return more user infos), https://github.com/owncloud/core/issues/31993 (Extend Webdav files search API on REPORT), https://github.com/owncloud/core/issues/19958 (Streaming API?), and https://github.com/owncloud/core/issues/4250 (api owncloud).
