### ISSUE TITLE
[Feature Request] Improve files:scan to scan admin mounts

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#32216]
10.0.9
An admin creates an admin mount and shares it to users/groups
The admin is not the owner of the mount, it is a non personal = admin mount therefore no owning user.
By design, the current implementation of files:scan requires a user or a group to a mount to be scanned.

**Enhancement:**
Add a functionality to scan admin mounts.
The identification could be ``--amount=mount_id`` as we get it from ``files_external:list``
(in case we merge the PR for shortening the output via --short, a nice short easy to handle list, else a longer list, also usable)

@PVince81

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/3196 (Admin file system scan), https://github.com/owncloud/core/issues/7697 (Add admin button to re-scan the file system for changed files), https://github.com/owncloud/core/issues/19706 (improved the way we handle part-files), https://github.com/owncloud/core/pull/30020 (Add group option to files:scan command), and https://github.com/owncloud/core/issues/481 (moving files).
