### ISSUE TITLE
occ commands containing --group, issue where group contains a comma 

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#32219]
10.0.9

**Issue:** when a group contains a comma, the current mechanism will not work.
**Solution:** use a new implementation of --group to allow groups with comma.
**Implementation Reference:** https://github.com/owncloud/core/pull/31719 and issue https://github.com/owncloud/core/issues/32215

These are the occ commands which contain as option ``--group``
https://github.com/owncloud/documentation/blob/master/admin_manual/configuration/server/occ_command.rst

- ``sudo -u www-data php occ files:scan`` in progress with PR https://github.com/owncloud/core/pull/31719
- ``sudo -u www-data php occ ldap:search [--group] [--offset="..."] [--limit="..."] search``
- ``notifications:generate [-u|--user USER] [-g|--group GROUP] [-l|--link <linktext>] [--] <subject> [<message>]``
- ``user:add [--password-from-env] [--display-name [DISPLAY-NAME]] [--email [EMAIL]] [-g|--group [GROUP]] [--] <uid>``

pls note, each command mentioned above has usually more than one place in the command reference where this enhancement needs to be described.
There are possible more occurrences which are currently not in the text due to bad doc quality, needs checking.

@phil-davis, @PVince81

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/21767 (issue), https://github.com/owncloud/core/issues/20629 (Commands for managing groups with occ.), https://github.com/owncloud/core/issues/15842 (LDAP Group Issues), https://github.com/owncloud/core/issues/10983 (Exclude with groups cannot work with groups containing commas), and https://github.com/owncloud/core/issues/20663 (command line occ add user group issue).
