### ISSUE TITLE
ownCloud Big Files Upload issue

### ISSUE THREAD

**Issue by josephnik02** [owncloud/core#32220]
Dear Community,

I have been experiencing problems with my ownCloud Server when trying to upload large files via WebDAV (>2GB). The upload starts completely normal, but after a while it interrupts, i get the finder error-code 36 (The Finder can’t complete the operation because some data in “FileName” can’t be read or written. (Error code -36). 
After i get this message, the server disconnects and i have to reconnect to ownCloud again. 

When i look into the owncloud-log i found the following:

{"reqId":"np8gZrImcMfdrKkJAEHE","level":2,"time":"2018-08-01T19:44:04+00:00","remoteAddr":"192.168.0.1","user":"MyCloud","app":"dav","method":"DELETE","url":"\/remote.php\/dav\/files\/MyCloud\/._2018-06-22%20Stellen%20Sie%20sich%20vor","message":"Could not get node for path: \"files\/MyCloud\/._2018-06-22 Stellen Sie sich vor\" : File with name ._2018-06-22 Stellen Sie sich vor could not be located"}

### Expected behaviour
Files shows be uploaded to owncloud via webDav

### Actual behaviour
Upload starts normal, Burt after a while the server disconnects and the upload aborts.

### Server configuration
**Operating system**: Raspberry pi 3 with Debian 9 (Stretch)

**Web server**: Apache 2

**Database**: MySQL

**PHP version**: 7.0

**ownCloud version**: 10.0.8

**Updated from an older ownCloud or fresh install**: fresh install

**owncloud Config:**

{
    "basic": {
        "license key": "***REMOVED SENSITIVE VALUE***",
        "date": "Wed, 01 Aug 2018 20:14:56 +0000",
        "ownCloud version": "10.0.8.5",
        "ownCloud version string": "10.0.8",
        "ownCloud edition": "Community",
        "server OS": "Linux",
        "server OS version": "Linux raspberrypi 4.14.52-v7+ #1123 SMP Wed Jun 27 17:35:49 BST 2018 armv7l",
        "server SAPI": "apache2handler",
        "webserver version": "Apache\/2.4.25 (Raspbian)",
        "hostname": "josephsraspberry.ddns.net",
        "user count": 1,
        "user directories": 1,
        "logged-in user": "MyCloud"
    },
    "config": {
        "instanceid": "ockh2254n7qe",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.105",
            "DynDNS",
            "localhost"
        ],
        "datadirectory": "\/media\/ownclouddrive",
        "overwrite.cli.url": "http:\/\/josephsraspberry.ddns.net",
        "dbtype": "mysql",
        "version": "10.0.8.5",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "loglevel": 2
    },
    "integritychecker": {
        "passing": true,
        "enabled": true,
        "result": []
    },
    "core": {
        "backgroundjobs_mode": "cron",
        "installedat": "1531836025.6798",
        "lastcron": "1533154442",
        "lastupdateResult": "{\"version\":\"10.0.9\",\"versionstring\":\"ownCloud 10.0.9\",\"url\":\"https:\\\/\\\/download.owncloud.org\\\/community\\\/owncloud-10.0.9.zip\",\"web\":\"https:\\\/\\\/doc.owncloud.org\\\/server\\\/10.0\\\/admin_manual\\\/maintenance\\\/upgrade.html\"}",
        "lastupdatedat": "1533154473",
        "public_files": "files_sharing\/public.php",
        "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php"
    },

**List of activated apps:** 
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.4
  - notifications: 0.3.3
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - theme-example
  - user_external

**Are you using external storage, if yes which one**: no

**Are you using encryption**: ssl

**Are you using an external user-backend, if yes which one**: webDav

### Client configuration
**Browser**: Safari 11.1.1

**Operating system**: Mac OS 10.13.5

#### ownCloud log (data/owncloud.log)

{"reqId":"np8gZrImcMfdrKkJAEHE","level":2,"time":"2018-08-01T19:44:04+00:00","remoteAddr":"192.168.0.1","user":"MyCloud","app":"dav","method":"DELETE","url":"\/remote.php\/dav\/files\/MyCloud\/._2018-06-22%20Stellen%20Sie%20sich%20vor","message":"Could not get node for path: \"files\/MyCloud\/._2018-06-22 Stellen Sie sich vor\" : File with name ._2018-06-22 Stellen Sie sich vor could not be located"}

{"reqId":"0lRo2ZCFGjnm5gt6Sa6j","level":2,"time":"2018-08-01T19:46:07+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"xxx.xxx.xxx.xxx\" tried to access using \"yyy.yyy.yyy.yyy:80\" as host."}

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/11729 (owncloud app upload issue), https://github.com/owncloud/core/issues/1373 (Uploading files issue), https://github.com/owncloud/core/issues/2010 (ownCloud WebDav Finder issue), https://github.com/owncloud/core/issues/28161 (Owncloud file preview issue), and https://github.com/owncloud/core/issues/18216 (Owncloud fails on downloading or uploading large files).
