### ISSUE TITLE
Unassigned admin mounts show up in the client

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#32223]
### Steps to reproduce
1. Create a admin mount point but do not assign it to any user or group, leave it unassigned
2. Correct: this mount point does not show up in the browser on any user logged on
3. Incorrect: the mount point is propagated to the client for all users

### Expected behaviour
The unassigned admin mount point must not show up on any user in the client
(webdav propagation must not contain this asset)

### Actual behaviour
The unassigned admin mount point shows up for any user in the client

### Server configuration
**Operating system**: Ubutu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.1

**ownCloud version:** 10.0.9

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oct7bkicorxf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxx",
            "yyyy",
            "zzzz"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xxxx",
        "dbtype": "mysql",
        "version": "10.0.9.5",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "filesystem_check_changes": 1,
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "maintenance": false,
        "theme": "",
        "preview_max_scale_factor": 1,
        "excluded_directories": [
            ".snapshot",
            "~snapshot"
        ],
        "upgrade.automatic-app-update": true,
        "quota_include_external_storage": false,
        "singleuser": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ]
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_clipboard: 0.7.1
  - files_external: 0.7.1
  - files_external_dropbox: 1.0.1
  - files_external_ftp: 0.2.0
  - files_pdfviewer: 0.9.0
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.1.0
  - guests: 0.5.0
  - market: 0.2.5
  - music: 0.8.0
  - notifications: 0.3.4
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.3.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external
```

**Are you using external storage, if yes which one:** /smb /ftp /dropbox

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera

**Operating system:** W10x64

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
no relevant data
```

#### Browser log
```
no relevant data
```

@PVince81

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/6137 (S3 mount kills admin page), https://github.com/owncloud/core/issues/1814 (Shared Folder not showing in Sync Client), https://github.com/owncloud/core/issues/14141 (Admin - Last Login not showing correct), and https://github.com/owncloud/core/issues/30642 (Federated shares keep the status "Ausstehend", manually walking thru folders necessary).

**Comment by PVince81** [comment]
"unassigned" means "assigned to all users"

**Comment by PVince81** [comment]
the placeholder says so: "Available for: All users"

![image](https://user-images.githubusercontent.com/277525/43701998-9346c0fc-9958-11e8-9375-c33dda95edf8.png)

Please note that this was always the behavior before: the default is "all users".

Closing as "expected behavior".

Please refer to https://github.com/owncloud/core/issues/22479#issuecomment-232421423 for the addition of a "Save" button and discussion whether having "All users" by default makes sense...
