### ISSUE TITLE
maintenance:update:htaccess does not show any error when writing of .htaccess fails

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#32227]
### Steps to reproduce
1. install owncloud in an sub-folder of an apache directory
2. run `sudo -u www-data ./occ config:system:set htaccess.RewriteBase --value /owncloud-core/`
3. make sure in config.php `'htaccess.RewriteBase' => '/owncloud-core/',` is set
4. make sure www-data can**not**  write the .htaccess file
5. run `sudo -u www-data ./occ maintenance:update:htaccess`

### Expected behaviour
Error shown saying that `.htaccess` file could not be updated

### Actual behaviour
output `.htaccess has been updated`

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache
**Database:**
Sqlite
**PHP version:**
7.2
**ownCloud version:** (see ownCloud admin page)
10.1
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git
**The content of config/config.php:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-core",
        "dbtype": "sqlite3",
        "version": "10.1.0.1",
        "logtimezone": "UTC",
        "instanceid": "oc2fs70i9byd",
        "loglevel": "0",
        "csrf.disabled": true,
        "enable_previews": false,
        "sharing.federation.allowHttpFallback": true,
        "datadirectory": "\/home\/artur\/www\/owncloud-core\/data",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "htaccess.RewriteBase": "\/owncloud-core\/",
        "files_external_allow_create_new_local": "true"
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - testing: 0.1.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - enterprise_key
  - files_antivirus
  - files_primary_s3
  - firewall
  - guests
  - multidirtest
  - user_management
  - user_ldap
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Logs
no log output

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/29344 (Update .htaccess), https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/28840 (-Error-), https://github.com/owncloud/core/issues/20593 (Update failed), and https://github.com/owncloud/core/issues/18826 (update fail).
