### ISSUE TITLE
Arbitrary setting of file mode on owncloud.log

### ISSUE THREAD

**Issue by davidjericho** [owncloud/core#32221]
### Steps to reproduce
1. chmod owncloud.log file to a mode other than 0640.
2. Cause an event, of any kind, that is logged.
3. See owncloud.log file chmod'ed back to 0640.

### Expected behaviour
It isn't ownCloud's job, when logrotation is disabled, to manage the file permissions. I am managing it via logrotate and other methods, as we use filebeats to take the json log and feed it into elasticsearch.  I'm not keen to add filebeat to the php user group, as that would mean I'm expanding the footprint of possible users that can write to data in certain scenarios.

I would suggest that the chmod only be performed upon file rotation when managed by ownCloud itself. 

### Actual behaviour
ownCloud keeps reverting the log file permissions to 0640, as per https://github.com/owncloud/core/blob/master/lib/private/Log/Owncloud.php#L132

Not to mention the ownCloud instance is performing needless busy work on every log event.

### Server configuration
**Operating system**: RHEL 7.5
**Web server:** Apache 2.4.6
**Database:** MariaDB 10.0 w/Galera
**PHP version:** 7.0 from the Remi repo
**ownCloud version:** 10.0.9
**Updated from an older ownCloud or fresh install:** Not relevant
**Where did you install ownCloud from:** Git

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/20015 (Owncloud log file), https://github.com/owncloud/core/issues/4366 (owncloud log file permissions), https://github.com/owncloud/core/issues/4503 (owncloud losing files!), https://github.com/owncloud/core/issues/24488 (Owncloud.log goes crazy.), and https://github.com/owncloud/core/issues/7391 (Lost files in owncloud).

**Comment by mdusher** [comment]
Since rotating just calls `\OCP\Util::writeLog()` to handle the file creation on a rotate, it'd probably still have to be done in the actual Owncloud logger.

Maybe only perform the chmod on the creation of the log file, rather than every write? Something like this might work (it's untested as I was just sketching out the idea):
https://github.com/mdusher/core/commit/7792eafda0c98364f94b285a6bbbcaa632eaddb2

**Comment by DeepDiver1975** [comment]
Feel free to submit this as pull request. Im Happy to review this. THX

**Comment by mdusher** [comment]
@DeepDiver1975 done.
