### ISSUE TITLE
Translation Issue during public link creation

### ISSUE THREAD

**Issue by haukman** [owncloud/core#32228]
### Steps to reproduce
1. Configure password policy app like this:
![grafik](https://user-images.githubusercontent.com/25486818/43629780-7fb547ea-96fe-11e8-8492-245211e14f67.png)
2. Set englisch as your default language
3. Create a public link

### Expected behaviour
The error message that appears if I´m not compliant with the password policy apps ruleset should be in englisch.

### Actual behaviour
![grafik](https://user-images.githubusercontent.com/25486818/43629897-ee72fcea-96fe-11e8-9129-d2849ce8083f.png)

### Server configuration

**ownCloud version:** 10.0.8

**Updated from an older ownCloud or fresh install: Fresh

**Where did you install ownCloud from: Docker

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @felixheidecke.

Possibly related issues are https://github.com/owncloud/core/issues/21767 (issue), https://github.com/owncloud/core/issues/1450 (directory creation issue), https://github.com/owncloud/core/issues/30802 (Switch to local view from public link), https://github.com/owncloud/core/issues/5982 (Thumbnail generation fails for re-shared public links), and https://github.com/owncloud/core/issues/17486 (Allow folder creation in public share).

**Comment by PVince81** [comment]
Weird. Is your OC server locale set to en_US.UTF-8 or is it set to German ?
Strange that server-generated messages would get translated despite the configured language.

cc @DeepDiver1975
