### ISSUE TITLE
Drag and drop empty folder not working

### ISSUE THREAD

**Issue by smrecko** [owncloud/core#32235]
### Steps to reproduce
1. Drag and drop empty folder from desktop or any other location into ownCloud over web browser
2. I tested on multiple ownCloud servers (test environment and production), multiple browsers, multiple OS, multiple machines, multiple networks. On ownCloud 10.0.3 there was no problem. I upgraded to 10.0.8 and then later to 10.0.9 - on both version there was an error.
3.

### Expected behaviour
Empty folder should have been uploaded to ownCloud

### Actual behaviour
Empty folder is not being uploaded. If I insert jut an empty text file into this folder then it is uploaded correctly.

### Server configuration
Ubuntu 16.04 LTS

**Web server:**
apache

**Database:**
MySQL

**PHP version:**
PHP 7.0.30-0ubuntu0.16.04.1

**ownCloud version:** (see ownCloud admin page)
10.0.9 (error also in 10.0.8). In version 10.0.3 it worked correctly.

**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**
http://download.owncloud.org/download/repositories/stable/xUbuntu_16.04/

**Signing status (ownCloud 9.0 and above):**
no errors 

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.

No errors have been found.


**The content of config/config.php:**
{
    "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "192.168.1.250"
        ],
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "datadirectory": "\/var\/owncloud_data",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "10.0.8.5",
        "dbname": "oc",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "loglevel": 2,
        "maintenance": false
    }
}

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**
  - activity: 2.3.6
  - audioplayer: 2.3.0
  - calendar: 1.5.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - impersonate: 0.2.0
  - market: 0.2.4
  - notifications: 0.3.3
  - onlyoffice: 1.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.3
  - twofactor_totp: 0.4.4
  - updatenotification: 0.2.1
  - user_ldap: 0.11.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Tested on multiple ownCloud servers (only internal users and LDAP) - not working on either

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Tested on Chrome, Firefox, IE (all latest version)

**Operating system:**
Windows 10

### Logs
#### Web server error log
```
[Tue Jul 24 06:25:07.240106 2018] [ssl:warn] [pid 61598] AH01909: ownCloud:443:0 server certificate does NOT include an ID which matches the server name
[Tue Jul 24 06:25:07.240225 2018] [mpm_prefork:notice] [pid 61598] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Tue Jul 24 06:25:07.240231 2018] [core:notice] [pid 61598] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jul 26 19:50:48.714821 2018] [ssl:warn] [pid 1258] AH01909: ownCloud:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 26 19:50:54.111031 2018] [ssl:warn] [pid 1270] AH01909: ownCloud:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 26 19:50:54.113263 2018] [mpm_prefork:notice] [pid 1270] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Thu Jul 26 19:50:54.113291 2018] [core:notice] [pid 1270] AH00094: Command line: '/usr/sbin/apache2'
[Thu Jul 26 20:17:19.938640 2018] [mpm_prefork:notice] [pid 1270] AH00169: caught SIGTERM, shutting down
[Thu Jul 26 20:18:35.426179 2018] [ssl:warn] [pid 2256] AH01909: ownCloud:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 26 20:18:35.452573 2018] [ssl:warn] [pid 2257] AH01909: ownCloud:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 26 20:18:35.454473 2018] [mpm_prefork:notice] [pid 2257] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Thu Jul 26 20:18:35.454493 2018] [core:notice] [pid 2257] AH00094: Command line: '/usr/sbin/apache2'

```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
No log recorded for the time of testing (log set to warning, errors and fatal issues)

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
![empty folder](https://user-images.githubusercontent.com/42122110/43689882-e7af4d38-9900-11e8-8a06-a73ee0612b9e.jpg)
![not empty folder](https://user-images.githubusercontent.com/42122110/43689896-2bbf6daa-9901-11e8-94e9-fb483ca84d27.jpg)


```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/3758 (Drag & Drop folder does not work), https://github.com/owncloud/core/issues/14375 (Drag and drop doesn't work on dropbox external storage folders.), https://github.com/owncloud/core/issues/13199 (Drag-and-Drop upload in master is not working over empty space), https://github.com/owncloud/core/issues/2259 (Drag and drop not working), and https://github.com/owncloud/core/issues/8660 (Drag&drop is not working to upload files in an empty folder).

**Comment by smrecko** [comment]
All related issues are 3 to 5 years old from ownCloud version 8.x or even older. Like I said, drag and drop worked fine on version 10.0.3 (tested on multiple computer and ownCloud servers, production and test environments). I upgraded ownCloud from 10.0.3 to 10.0.8 and the issue appeared (also tested on multiple servers, computers,...). After upgrade from 10.0.8 to 10.0.9 issue remains. Can no one replicate this issue? 
I've been using windows machines and multiple browsers, ownCloud is installed on ubuntu 16.04 (test and production environment).

Thanks!

**Comment by phil-davis** [comment]
I can't make empty-folder-drag-and-drop work on any 10.0.* version. I have Ubuntu 18.04 with Firefox 61.0.1 and Google Chrome 68.0.3440.84 - I tries 10.0.1 10.0.2 10.0.3 and current stable10 (= 10.0.9 plus)

**Comment by richardp97** [comment]
Yes, I have the same thing.

Running the 10.0.8 version as a Docker. Using Safari give me the same problems as the others reported.

**Comment by neironus** [comment]
We have the same problem. OwnCloud 10.0.8 - Docker.

**Comment by cloudenv** [comment]
> I can't make empty-folder-drag-and-drop work on any 10.0.* version. I have Ubuntu 18.04 with **Firefox** 61.0.1 and Google Chrome 68.0.3440.84 - I tried 10.0.1 10.0.2 10.0.3 and current stable10 (= 10.0.9 plus)
Do not use Firefox. Ever. Its shit.

Same issue with empty folder. I dont care.
Moving out of ownCloud after being its user ever since. Sory ownCloud

**Comment by PVince81** [comment]
I believe this never worked before. 

Last I checked a few years ago the browsers did not seem to send the folder names because they only expose the file list.

Now seeing this https://stackoverflow.com/questions/42129928/how-to-detect-when-an-empty-directory-is-being-uploaded-in-chrome 

As ownCloud is using jquery.fileupload for uploads and the library doesn't seem to use this approach, might need to either tweak the lib or find a way to bypass it.

I'll leave this open to do more research and see if this has indeed become possible with newer browers / APIs.

**Comment by PVince81** [comment]
@smrecko for profiles you could rather use the "core/skeleton" folder and put the initial files there. Every user who logs in the first time will see these files.

**Comment by haukman** [comment]
tested again with latest chrome: Version 72.0.3626.81 (Official Build) (64-bit)
ownCloud Version 10.0.10 (docker)

Created the following empty folder structure:

Level1 -> Level2 -> Level3

Used WebUI to drag&drop the folder(s), with the following result:

<img width="823" alt="grafik" src="https://user-images.githubusercontent.com/25486818/52057947-ac5a4600-2566-11e9-838a-606c0bc17a2d.png">

Only level1 and level2 get copied. Level 3 is missing
