### ISSUE TITLE
Design forward: Sharing dialog

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#3224]
Some thoughts on how to improve sharing which @MTRichards and I discussed. @MTGap what do you think? We should collaborate on that soon to make sharing more awesome.

Share dialog in general
* input field should have suggestions directly, maybe use Chosen.js
* more padding, bigger in general, better grouping (I’ll do that ;)
* show name, »can edit« and »can share« and x directly (edit & share default on)
* line up detail CRUD dropdown as list with »can edit«, default all selected
* in the future user images on the left of each row

![img_1609](https://f.cloud.github.com/assets/925062/844356/ef8669f4-f3d0-11e2-83d9-c919e3ed9b7f.JPG)

Share via email
* currently goes through share with link, too cumbersome
* should be integrated in the one field on top: »Share with user or email«
* show email in list like username matt@example.com, only action is x
* future: generate unique link per email address so revocation on a per-person basis is possible

![img_1610](https://f.cloud.github.com/assets/925062/844357/efa489e8-f3d0-11e2-95e0-8d2124f0af8f.JPG)
-- separation here --

Share link
* rename from »share public link«
* input box next to label
* »password protect« slightly indented maybe, or group it somehow

-- separation here --
![img_1611](https://f.cloud.github.com/assets/925062/844358/efb79eb6-f3d0-11e2-8fb0-654addfa7e2f.JPG)

Expiration date
* ability to set date _and_ time (only granular to hours)
* make impossible to choose date in past, minimum 1 hour in future
* show countdown as feedback (only granular to hours)
* admin ability to set default expiration time (default: expiration completely disabled)

More thoughts?

**Comment by MorrisJobke** [comment]
This will also fix #3224

**Comment by PVince81** [comment]
The first mock up looks strangely very close to what we already have.
Also many of the defaults that have been discussed have been implemented already, and also the expiration date selection limits.

This ticket should probably be reformulated to only include what is left to implement.
- permissions dropdown
- set expiration time ?
- countdown
- default sharing permissions
- dropdown for suggestions ?

**Comment by PVince81** [comment]
Ticket for moving the share dialog into the sidebar: https://github.com/owncloud/core/issues/17665

**Comment by jancborchardt** [comment]
Pretty much everything in the spec has been implemented. Except the integration of sharing with email addresses. But as discussed with @karlitschek in the past this could lead to confusion with federated sharing.

At least this giant issue should be closed. ;)

**Comment by Rocco83** [comment]
Hi,

"future: generate unique link per email address so revocation on a per-person basis is possible"
In which issue is addressed? for what i have checked is still not a merged feature.
I have got that it is waiting on #22327, is this correct?

@jancborchardt any comment?
