### ISSUE TITLE
config.sample.php does not mention activity_expire_days 

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#32268]
Enhancement Idea:
Shouldn't our config example mention this setting?
config.sample.php in 10.0.9 does not mention activity_expire_days

References:
* https://doc.owncloud.com/server/10.0/admin_manual/configuration/server/activity_configuration.html#configuring-your-owncloud-for-the-activity-app
* https://doc.owncloud.com/server/10.0/admin_manual/configuration/server/config_sample_php_parameters.html#app-config-options

**Comment by DeepDiver1975** [comment]
Its a setting which is tied to the activity app - nothing related to the pure server config.

We could generate a combined dictionary of all apps within our docs - but not in config.sample.php of core.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/24789 ('lost_password_link' from config.php don't work as expected), https://github.com/owncloud/core/issues/6126 (config/autoconfig.php is not respected), https://github.com/owncloud/core/issues/12785 (config.php is reset), https://github.com/owncloud/core/issues/18404 (Missing parameter from config.sample.php, section end?), and https://github.com/owncloud/core/pull/29509 (config.sample.php: instanceid documentation).

**Comment by mmattel** [comment]
@DeepDiver1975 @PVince81 @settermjd 

In general I agree that we should discuss having for owncloud shipped apps a own, maybe commonly used ``apps.config.sample.php``.

But this is currently not the case and due to the workload we have in documentation nothing we see in the near future. Except it is decided to focus on such an ``apps.config.sample.php`` document. I am not raising the word over @settermjd opinion, but from that what I know I believe in his agreement. 

I propose therefore to continue adding these settings, but start to mark them for which app they are related. This will then ease migrating all config samples into their own documentation.

Side note: please keep in mind, that the app activity is part of the tar shipment and does not stand for its own.

**Comment by PVince81** [comment]
the activity app isn't shipped any more since many releases when it was moved to marketplace, see 10.0.9 tarball

maybe we should rather move all these config.php settings to the database like suggested in https://github.com/owncloud/core/issues/11843

**Comment by mmattel** [comment]
Just to document the current situation:
1. we have keys for core
2. we have keys for apps shipped by tar, developed by owncloud
3. we have keys for apps which are not included in tar but on marketplace, developed by owncloud
4. we wave only one place of documentation ``config.sample.php``

As long we do not have an additional documentation location for 3.  I vote for adding them to 4. and mark them accordingly. Whatever we do after that, not that important, but it is at least documented.

If we do not do that, we miss all those efforts made in coding and functionalities created for the admins. Forgotten knowledge is the worst case.

**Proposal:**
Document all keys in ``config.sample.php`` up to the point of an existing alternative.

**Comment by settermjd** [comment]
On thinking about it, and reading through (most of) the related link, it makes sense to keep config.sample.php as clean and core-focused as possible. However, not having settings for ownCloud apps (whether on Marketplace or wherever) doesn't make sense and is likely to cause confusion to the user. So there needs to be a compromise. 

The question is, how? If app configuration settings are stored in a file such as `apps.config.sample.php`, and that file is auto-generated, then: 

- What is it generated from?
- Who or what generates that file? 
- and Will it truly include all the configuration options that people need, or result in them still wondering where configuration setting "X" is?

Owing to my reduced level of understanding of the codebase, I could be missing something. But this is my 2c worth.

**Comment by settermjd** [comment]
Should each app have a config sample file generated or included as part of its documentation?
