### ISSUE TITLE
Official 10 repo for Centos 6 ?

### ISSUE THREAD

**Issue by christianlx** [owncloud/core#32264]
Hi,
I create this post for information. I have an Owncloud 9.1 production server on centos 6. I’ve always used ce repo until now. I’d like to upgrade to 10. On the Web site, only Centos 7 seems to be supported but on this URL the 10.0.0 is OK :
http://download.owncloud.org/download/repositories/10.0.0/CentOS_6/
The problem is that for updates or latest production/stable version (10.0.9 for example), there is no Centos6 folder. So what is the official policy about Centos distribution ? Is it safe to use the Centos 7 ou should I now use the tar archive manually ?
Thanks,
Christian.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/pull/30329 ([stable10] hotfix 10.0.6 commits), https://github.com/owncloud/core/issues/2643 (RPM postinstall script has problems on CENTOS 6), https://github.com/owncloud/core/issues/26857 (owncloud 9.0.7 - Centos 6 - files missing in repo), https://github.com/owncloud/core/issues/2674 (ownCloud at CentOS 6.4), and https://github.com/owncloud/core/issues/23188 (Missing Centos 6 repositories for 9.X.X).

**Comment by jnweiger** [comment]
10.0.7 had CentOS6, 10.0.8 and up no more. @crrodriguez is that correct?

**Comment by crrodriguez** [comment]
El 07-08-2018 8:10 a.m., Jürgen Weigert <notifications@github.com> escribió:10.0.7 had CentOS6, 10.0.8 and up no more. @crrodriguez is that correct?Correct, it is too old for owncloud X.

**Comment by PVince81** [comment]
closing then, please upgrade CentOS
