### ISSUE TITLE
Update failure from 10.0.7 to 10.0.9 - occ command

### ISSUE THREAD

**Issue by roger-luescher** [owncloud/core#32265]
Dear Owncloud community

I tried the update my properly working owncloud from version 10.0.7 to 10.0.9. I used the regular update assistant in owncloud and received the following error message:

"OC\RepairException: Upgrade is not possible
        Reparaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
        Reparaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable templateeditor
        Reparaturwarnung:For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps

"Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Reparaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable templateeditor
Reparaturwarnung:For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps
OC\RepairException: Upgrade is not possible"

I understood to put the following occ command with the http-user to solve the problem:
"$ sudo -u www-data php occ app:disable templateeditor"

To put this occ commands to the webser is new for me. Which tool i have to use? I use a windows user as client. Owncloud is installed on a webspace by hostpoint.ch. Database mysql. URL: https://www.rogeronline.ch/owncloud/

Could someone help me out how to put the acc command? Or any other idea how to end the update process?

Many thanks!
Roger

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/issues/32388, other people reported something similar. might be a bug in the web updater (the update assistant)

**Comment by MohammedAlrozzi** [comment]
did you resolve this issue. I have the same problem and my experience in using occ is zero. please help
