### ISSUE TITLE
[Feature Request] Admin mount points should not have a default user or group assigned when ceated

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#32267]
10.0.9

**Issue:**
When you create an admin mount point, all admins get this mount point assigned by default what means, it appears in the web-ui and is propagated to the client.

**Feature Request:**
The admin mount point is created in the same way, but no user or group even not the admins get the default assignment. It is unassigned. This means, that this admin mount point does not appear on any users web-ui or client. This changes if the admin assigns this mount point to users or groups, then it behaves like usual. When removing all users or groups, this mount point becomes unassigned again.

**Benefit:**
Admins can prepare mount points in advance without unintentionally showing that mount point on any web-ui or client.

**Note:**
There is imho no change on the web-ui necessary, only on the backend. One possible exception, the current assignment text for admin mount points must change from ``All users`` to ``Unassigned``.

@PVince81 @DeepDiver1975

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/12530 (Feature Request), https://github.com/owncloud/core/issues/8569 (Feature requests), https://github.com/owncloud/core/issues/15818 (admin should not be able to select ldap groups for users), https://github.com/owncloud/core/issues/7117 ([Feature Request] - In Admin user page), and https://github.com/owncloud/core/issues/7118 ([Feature Request] Admin User page).
