### ISSUE TITLE
Allow BackBlaze support for owncloud

### ISSUE THREAD

**Issue by YoussefV** [owncloud/core#32302]
There have been issues opened in relation to this before, but it would be great to allow backblaze integration for OwnCloud as backblaze is the cheapest cloud storage solution out there at the moment. They are also no longer in beta so it would great to have that option!

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/24291 (Support absolute dates in ownCloud), https://github.com/owncloud/core/issues/10222 (owncloud security), https://github.com/owncloud/core/issues/10400 (OAuth 2.0 support for ownCloud [$5]), https://github.com/owncloud/core/issues/21925 (Owncloud 8.2.2.2 breaks support for OneNote 2013), and https://github.com/owncloud/core/issues/10128 (Add single user support to demo.owncloud.org).

**Comment by hodyroff** [comment]
Agree that it would be interesting for external storage. An app based on flysystem should be possible, but somebody would need to step up to start that ownCloud app and external storage integration. As primary storage we have just settled on S3 only for object storage and like to optimize that one quite a bit more before considering any new additions. S3 is an open standard and supported by many and tough enough to support "right".
