### ISSUE TITLE
Improve README.md with regards to the translation link

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#32300]
**Current**
For more detailed information about translations: https://doc.owncloud.org/server/10.0/developer_manual/core/translation.html

**Future**
For more detailed information about translations: https://doc.owncloud.org/server/latest/developer_manual/core/translation.html

10.0 --> latest

@settermjd

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/19792 (Nice new README.md), https://github.com/owncloud/core/issues/55 (Missing translation), https://github.com/owncloud/core/issues/32228 (Translation Issue during public link creation), https://github.com/owncloud/core/issues/29116 ( Improve public link sharing permissions for folders), and https://github.com/owncloud/core/pull/30250 (Improve assertions).
