### ISSUE TITLE
no mimetype image for file versions when previews are disabled

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#32310]
### Steps to reproduce
1. in `config.php` set `'enable_previews' => false,`
2. create some versions of a file
3. open versions panell

### Expected behaviour
the preview in the versions tab should be the same as in the file list

### Actual behaviour
the versions tab still tries to load the previews and receives a 404 error
![image](https://user-images.githubusercontent.com/2425577/44022622-db066b18-9f07-11e8-9bf4-29042445181c.png)

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache 2
**Database:**
SQlite
**PHP version:**
7.2
**ownCloud version:** (see ownCloud admin page)
10.1.0.1
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git
**The content of config/config.php:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "dbtype": "sqlite3",
        "version": "10.1.0.1",
        "logtimezone": "UTC",
        "instanceid": "oc2fs70i9byd",
        "loglevel": 2,
        "csrf.disabled": true,
        "datadirectory": "\/home\/artur\/www\/owncloud-core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-core",
        "htaccess.RewriteBase": "\/owncloud-core\/",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "1025",
        "enable_previews": false,
        "ldapIgnoreNamingRules": false,
        "theme": "",
        "maintenance": false,
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}

```

**List of activated apps:**

```
  - comments: 0.3.0
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - notifications: 0.3.4
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - testing: 0.1.0
  - updatenotification: 0.2.1
  - user_management: 0.0.1
Disabled:
  - enterprise_key
  - files_antivirus
  - files_primary_s3
  - firewall
  - guests
  - multidirtest
  - oauth2
  - user_ldap

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
FF
**Operating system:**
Ubuntu 18.04

#### Browser log
![image](https://user-images.githubusercontent.com/2425577/44022785-5ebe603c-9f08-11e8-9871-89a8f1a0a636.png)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/12571 (Disabled previews, but logging 'No preview providers'), https://github.com/owncloud/core/issues/11958 (Disable MS office previews), https://github.com/owncloud/core/issues/6909 (Versions preview image (for images) not created if encryption is enabled), https://github.com/owncloud/core/issues/10716 (File versions), and https://github.com/owncloud/core/issues/6587 (disable file preview for specific files).
