### ISSUE TITLE
Owncloud 10.0.9 Not upgrading - All installations for more than 10users stopped.

### ISSUE THREAD

**Issue by vaibhavtiger** [owncloud/core#32338]
### Steps to reproduce
1. Run the Upgrade Package of 10.0.9
2.Then open the Owncloud Installation package and click Start Upgrade
3.Get the Fialed Crash Report as below : 

Updating to 10.0.9

OC\RepairException: Upgrade is not possible
Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Repair warning: Please install or update the following apps manually or disable them with: occ app:disable calendar occ app:disable duo occ app:disable templateeditor
Repair warning: For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps
Detailed logs 
Preparing update
Set log level to debug
Turned on maintenance mode
Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Repair warning: Please install or update the following apps manually or disable them with: occ app:disable calendar occ app:disable duo occ app:disable templateeditor
Repair warning: For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps
OC\RepairException: Upgrade is not possible
The update was unsuccessful. Please report this issue to the ownCloud community.

Once it allowed me the login to the Server - in the browser and some SEVVER.TXT file integrity check was filed. 
And then boom, it crashed on me - I am running a protected server, with the latest.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/23596 (Owncloud 9.0.0 not working after upgrade), https://github.com/owncloud/core/issues/25700 (ownCloud 9.0.0), https://github.com/owncloud/core/issues/18305 (Owncloud not upgrading), https://github.com/owncloud/core/issues/24767 (Owncloud 9.0.2 Storage not available exception), and https://github.com/owncloud/core/issues/24267 (Upgrade failure to 9.0.1 owncloud).

**Comment by vaibhavtiger** [comment]
none of the above - has to be something with a bug -  want  Owncloud to Fix this. I m horrified.

**Comment by kinimodmeyer** [comment]
> or disable them with: occ app:disable calendar occ app:disable duo occ app:disable templateeditor

did you do what the error said to you?
did you login via ssh and then execute the commands to disable the named apps via php-cli?

**Comment by PVince81** [comment]
you could disable the apps, run the upgrade, then enable the apps again afterwards before disabling maintenance mode

**Comment by PVince81** [comment]
is this an offline instance that have no access to the internet ? see https://github.com/owncloud/core/issues/32388#issuecomment-415696306

**Comment by PVince81** [comment]
if you are able to revert data and DB from backup, you could try rerunning the upgrade on the CLI with `occ upgrade` which will likely output more useful messages.

in general it is recommended to run upgrades on the CLI with `occ upgrade`, not with the web UI as the latter could run into timeouts with bigger setups (unrelated to this issue I think)

**Comment by PVince81** [comment]
did you guys actually use the web updater to upgrade (especially if you have no CLI acess) ? this could have other side effects.

the web updater aka [updater app](https://doc.owncloud.org/server/10.0/admin_manual/maintenance/update.html#upgrading-owncloud-with-the-updater-app) is located in the settings page of the admin in a running instance.

the original post mentions "Upgrade Package" but it is not clear whether it's the updater function in admin or Linux distribution packages.

**Comment by VicDeo** [comment]
At least OC version before upgrade and the enabled apps list are missing in the report

**Comment by VicDeo** [comment]
No need to revert to the backup at this stage, as this is a preupgrade step and DB upgrade is still pending.
If these apps are missing/incompatible you can just download them from marketplace, extract into the  `apps`  dir and refresh the page.

**Comment by PVince81** [comment]
I'm mostly wondering why apps like "activity" are mentioned here. Normally the market app should update them.

I wonder whether this somehow is similar to https://github.com/owncloud/update-testing/issues/5#issuecomment-415755540, except that we don't see the attempt to enable the market app in the logs above. Still, if the market app doesn't manage to enable itself (in case of an upgrade from OC < 10, the report is missing the source version), it wouldn't be able to automatically download either.

**Comment by vaibhavtiger** [comment]
> No need to revert to the backup at this stage, as this is a preupgrade step and DB upgrade is still pending.
> If these apps are missing/incompatible you can just download them from marketplace, extract into the `apps` dir and refresh the page.

I have done what is recommended and It still gives me the same error as before. Now I am stuck. I dont know how to use the SSH on the Server Terminal but definitely understand if the steps can be told - I am novice but daily clued on when it comes to understanding. 

In the market place it is available here : https://github.com/elie195/duo_provider I have downloaded and uploaded the module but it aint resolving the issue.

**Comment by VicDeo** [comment]
the lastest version here is compatible with 10.0.9 https://marketplace.owncloud.com/apps/duo

**Comment by vaibhavtiger** [comment]
Thanks for your Quick Reply : 

1. There is no Apps Directory - and the one path I see has no apps in it. I had disabled the apps when I upgraded from 9-10 last time. 
2. The Above Links have no files for download, so how to download the files ?

**Comment by VicDeo** [comment]
1. Default apps directory is `apps`:
https://github.com/owncloud/core/tree/master/apps
custom apps directory is set via config:
https://github.com/owncloud/core/blob/master/config/config.sample.php#L721-L750

2. There is a **Choose release** dropdown at the marketplace. Once release is chosen "Download" button below this dropdopwn is switchedin the enabled state.

**Comment by vaibhavtiger** [comment]
It is not downloadable.

**Comment by ho4ho** [comment]
https://github.com/owncloud/core/issues/33673 same?

**Comment by vaibhavtiger** [comment]
Yes Not Just that it is not compatible with the 10.10 But I think - If anyone can tell me how to Re-Install the 10.0.9 version that I was already running - I think this should do the trick without disturbing the apple cart. 

Secondly, Is there a TEMP folder in my OC installation that can be deleted. 
Thirdly, Is there a method / File that can be tweaked to Disable the apps from the PHP files? So then I can disable the DUO and the Calendar etc. - That shud do the trick. 

I am very worried.

**Comment by ho4ho** [comment]
Bugtracker not good for questions? Try https://central.owncloud.org/?

**Comment by VicDeo** [comment]
>If anyone can tell me how to Re-Install the 10.0.9 version that I was already running

Basically you need to do a manual update but use 10.0.9 package instead of the latest.
You need disregard this advice ~Don’t keep the apps directory~ in the docs
**replace apps with same ids instead**
https://doc.owncloud.org/server/10.0/admin_manual/maintenance/manual_upgrade.html
please note that just copying files from 10.0.9 over your current instance is **NOT** recommended.

>Secondly, Is there a TEMP folder in my OC installation that can be deleted.

What is the purpose of that action? 
If you want it in the sake of  cleaning cache - just clean the cache. the exact way of doing it depends on the cache engine (redis/memcached/etc).

>Thirdly, Is there a method / File that can be tweaked to Disable the apps from the PHP files?

https://central.owncloud.org/t/how-to-disable-an-app-without-access-to-the-gui/832

**Comment by vaibhavtiger** [comment]
Thanks for your reply. Infact in my Apps folder, there is not thing - No APPS. Look at the Screen shot. 
So What I disablee or Delete. Infact I have Deleted the Entire “Market” folder which basically it is asking me to upgrade. 

So Basically I fee that we shud be able to see “SOME FILE NAME” where from we can disable to integration of DUO security (Which is access Security) on the Application and allow all the users to upgrade. So it is not the Upgrade of DUO APP Issue - this is a access issue - before the update engine can re-write the files and update the database, it needs DUO permission - which is kind of logical as Access Token will be enabled. 

Now I need to know where to disable it from ?

**Comment by VicDeo** [comment]
Duo compatible with 10.1 was released on Jan. 11th 2019 https://marketplace.owncloud.com/apps/duo

Unfortunately there were only 2 options for you: disable Duo or do not upgrade OC because we block incompatible apps on upgrade

Three ways to disable apps without GUI are listed here
https://central.owncloud.org/t/how-to-disable-an-app-without-access-to-the-gui/832

The third way (by deleteing app folder) is discouraged nowadays  so it needs to be done either via CLI or via database.

**Comment by VicDeo** [comment]
Anyone reading this thread please follow these instructions https://central.owncloud.org/t/upgrade-impossoble/14850/2?u=alfredb

I'm closing this issue feel free to reopen if it still persists
