### ISSUE TITLE
Failed update to 10.0.9

### ISSUE THREAD

**Issue by pichtj** [owncloud/core#32388]
When updating from 10.8.5 to 10.0.9, the system stayed in maintenance mode. After manually leaving maintenance mode and starting the update with the button "Aktualisierung starten", I received the following error message:

OC\RepairException: Upgrade is not possible
Reperaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Reperaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable activity occ app:disable files_pdfviewer occ app:disable files_texteditor occ app:disable gallery occ app:disable templateeditor
Reperaturwarnung:For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps

And detailed error message:

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet 
Reperaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Reperaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable activity occ app:disable files_pdfviewer occ app:disable files_texteditor occ app:disable gallery occ app:disable templateeditor
Reperaturwarnung:For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps
OC\RepairException: Upgrade is not possible

Side note to the translator: "Reperaturwarnung" is a spelling error and should be "Reparaturwarnung".

### Server configuration
**Operating system**:
Linux dd8102 3.13.0-153-generic #203-Ubuntu SMP Thu Jun 14 08:52:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
Apache

**Database:**
mysql

**PHP version:**
7.1

**Where did you install ownCloud from:**
hoster provided version, then many upgrades

**Signing status (ownCloud 9.0 and above):**
I fixed the signing status errors before the upgrade.

**The content of config/config.php:**
  'dbtype' => 'mysql',
  'version' => '10.0.9.5',
  'logtimezone' => 'Europe/Berlin',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'mail_smtpmode' => 'php',

**Comment by pichtj** [comment]
BTW this instance is also hosted at all-inkl.com. Still would be good to understand the root cause.

**Comment by Schladihps** [comment]
Dear pichtj, guess what i have exactly the same issue after upgrade like you described. But i have no idea about coding. I tried to check the ticket numbers above but no result. Would you please so kind and explain in small steps how you did "manually disabling the modules via db"
thanks in advance

**Comment by pichtj** [comment]
1. From your config/config.php, find your <dbtableprefix> and your connection details
2. Connect to your database
3. Run the following SQL statements, e.g. from phpMyAdmin (on all-inkl.com, phpMyAdmin is reachable via KAS):
`UPDATE <dbtableprefix>_appconfig SET configvalue = 'no' WHERE configkey = 'enabled' AND appid IN ('activity', 'files_pdfviewer', 'files_texteditor', 'gallery', 'templateeditor');`

**Comment by Schladihps** [comment]
Yes, very cool ! I had to replace dbtableprefix_appconfig with oc_appconfig and the upgrade finished.
Want touch it anymore. You safed my day. Thanks.

**Comment by PVince81** [comment]
Are your OC instances able to connect to the Internet ?

Normally when you run the upgrade, OC will connect to the marketplace and will download a recent version of all the listed apps, like activity, etc.

In case your OC instances are offline, in an intranet or for some reason they are not allowed to connect to outside servers, then you'd need to go through the manual update procedure as described in https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps

**Comment by PVince81** [comment]
Are there more messages before the one ?
There should be some additional messages about why it cannot update, some marketplace checks, etc

**Comment by Schladihps** [comment]
Dear PVince81, to be honest i trust in the craft of the programer who does prepare the upgrade script. But to answer your question yes the page is in the internet reachable. And the message was OC\RepairException: Upgrade is not possible
Reperaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Reperaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable activity occ app:disable files_pdfviewer occ app:disable files_texteditor occ app:disable gallery occ app:disable templateeditor
So i oppened my provider access and went to the db there i could open myphpadmin. Then i entered the SQL statement from pichtj. And over ftp i changed the maintenance value to false. So the upgrade could finish.
I'm a System Engineer / Network Tech with no deep programing skills.
But after the upgrade finished i was able to update the marketplace over the apps gui from 2.x to somethng new.
I would suggest to do a wireshark session to find out whether the gui / upgrade script or the db direct needs internet connectivity.
I hope you can digest my writing and it would give you a hint.

**Comment by PVince81** [comment]
occ upgrade works fine on our local environments, so not sure what is different in yours

Hmm, it is possible that the useful debug messages actually appear if you run the update with `occ upgrade` on the CLI. It is possible that the messages I was expecting are not propagated when updating in the web UI.

**Comment by pichtj** [comment]
Unfortunately, my web hoster does not allow me to run occ from the command line, so I must rely on the web interface. Any idea where I could look for the log messages?

**Comment by PVince81** [comment]
now thinking, did you guys actually use the web updater to upgrade (especially if you have no CLI acess) ? this could have other side effects.

the web updater aka [updater app](https://doc.owncloud.org/server/10.0/admin_manual/maintenance/update.html#upgrading-owncloud-with-the-updater-app) is located in the settings page of the admin in a running instance.

**Comment by pichtj** [comment]
Yes, I updated through the settings page, logged in as the admin user.

**Comment by PVince81** [comment]
@VicDeo ^

**Comment by nibbsification** [comment]
Hi everyone. Is there a similar way for an SQlite database? 
phpliteadmin finds the owncloud.db, but tells me `No table in database`.

**Comment by nibbsification** [comment]
It worked with phpliteadmin too. Same command as @pichtj wrote:
`UPDATE oc_appconfig SET configvalue = 'no' WHERE configkey = 'enabled' AND appid IN ('activity', 'calendar', 'files_pdfviewer', 'files_texteditor', 'gallery', 'templateeditor', 'tasks');`
Thank you sooooo much.
