### ISSUE TITLE
LIKE ESCAPE and QueryBuilder::createNamedParameter

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#32382]
### Steps to reproduce
1. use like() and createNamedParameter() with a pattern which holds a wildcard (e.g. _) and escapeLikeParameter
2. run query on a data set which matches the pattern

### Expected behaviour
the record shall be within the result set

### Actual behaviour
the record is not in the result set

### Server configuration
**Database:**
all

**ownCloud version:** (see ownCloud admin page)
10.0.x and master are affected

**Comment by DeepDiver1975** [comment]
## Analysis

Queries which use ? as placeholder are working because the necessary ESCAPE key word is added in the adapters: https://github.com/owncloud/core/blob/6b36c56180eee3ce796b1a69709431f1d38da627/lib/private/DB/AdapterSqlite.php#L42

The regex does not match in case of queries which have been built using createNamesParameter() because :dcValue is used as placeholder.

**Comment by DeepDiver1975** [comment]
With dbal 2.8.0 the escape char can be specified in the like() method - potential fix approach for master: https://github.com/owncloud/core/pull/32372

stable10 uses a different dbal version - we cannot yet update because of php version requirements

**Comment by DeepDiver1975** [comment]
for stable10 we could add ESCAPE within the expression builder like manually

**Comment by DeepDiver1975** [comment]
never the less the tricky part is to make sure the queries which do not use the querybuilder get the proper ESCAPE added

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/32372 (Add escape character to like query), https://github.com/owncloud/core/issues/16580 (LIKE queries do not properly escape special characters), https://github.com/owncloud/core/issues/17862 (Prefix QueryBuilder stuff with *PREFIX*), https://github.com/owncloud/core/issues/3494 (Property Serializer Escaping Issue), and https://github.com/owncloud/core/issues/9046 (escape t() variables by default).

**Comment by DeepDiver1975** [comment]
seems like the easiest fix is to convert all createNamedParameter() into createPositionalParameter()
