### ISSUE TITLE
Conditionally hash share link passwords

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#32383]
Passwords are always hashed even though they have been hashed before. This makes impossible to move the hashed password around in order to reuse the same password because the password hash will be hashed again.

The proposal is to avoid rehashing the password.

For the specific case of password-protected share links, the list of changes is as follows (there might be more changes involved):
* Add a `isHashed` method in the `IHasher` and in the implementation. The method will return true if the message is already hashed or false otherwise. For the core implementation, we can use http://php.net/manual/es/function.password-get-info.php for this purpose.
* The ShareManager can conditionally hash the password based on the result of the above function before creating / updating the password-protected share.

Note that we assume that the system has the same password salt. In case the password salt is different, the old password won't work as its hashed value will likely be different.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/19950 (changing expiration date of shared link breaks password), https://github.com/owncloud/core/issues/5719 (sending share email link fails), https://github.com/owncloud/core/issues/21466 (lost password hash expire), https://github.com/owncloud/core/issues/15812 (Share dialog password field hidden when enabled), and https://github.com/owncloud/core/issues/9116 (Shared a link with password protected but can't access it.).

**Comment by PVince81** [comment]
@jvillafanez hmmm... what if the user typed a password that actually looks like a hash ? likely improbable but still. I don't like this kind of auto-detection in general.

How about adding an optional argument to the password setter to tell it to "take it as is instead of hashing" ?

**Comment by jvillafanez** [comment]
I did consider that, but the amount of changes we'll need to do seems quite large: in addition to the changes in the ShareManager to conditionally hash the password, we might need additional changes in all the providers in order to store this new property, as well as retrieve the property correctly.

I wonder if we can consider that property as transient or similar so there is no need to store it. If so, the changes might be similar to the initial proposal.

**Comment by PVince81** [comment]
it might be ok to expect only the default share provider to understand the "clear" vs "hashed" passwords, but we need a good mechanism to make sure that the non-default ones don't fail

The bad part here is mostly that we're using the same field for password and that it can contain either hashed or unhashed password. Ideally these should be in separate properties.

If we had an attribute to tell whether the share is a new one or old one when passed to `createShare()`, the code could decide whether to hash the password or no.t

**Comment by jvillafanez** [comment]
We could try to include a `shouldHash` method returning `true` by default in the Share model. This would mean that the password should be hashed in any case (the current behaviour). When we create or update a share, we can set it to false to indicate that the password shouldn't be hashed by the ShareManager, which is where the hashing is taking place. This property will be set outside of the ShareManager, and the ShareManager will just read the property to decide whether hash the password or not.

Ideally, there shouldn't be further changes, and we wouldn't need to bother the providers.

**Comment by PVince81** [comment]
@jvillafanez last proposal sounds good, yes

**Comment by PVince81** [comment]
this ticket is only about having this ability on PHP API level, not HTTP/OCS.
