### ISSUE TITLE
Trusted domain not working 

### ISSUE THREAD

**Issue by soydepr** [owncloud/core#32394]
I have added to config.php 
'trusted_domains' => 
array (
0 => '192.168.1.9',
1 => '192.168.1.20',
2 => 'Xxx.xxx.x.x,  my external ip  also my hope vpn 
3=> ‘office ip‘
)

Yet i cant connect from the outside   Getting error  trusted domain 
![0a889195-e8a2-499e-9fd0-ab215ce12735](https://user-images.githubusercontent.com/546367/44393900-df060a00-a503-11e8-97fa-e8a328ef110e.jpeg)

**Comment by DeepDiver1975** [comment]
did you add the domain name as well?

**Comment by soydepr** [comment]
Yes i did the domain of my isp. Yes

**Comment by soydepr** [comment]
When i type ip of machine it works but not when i try vías url

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/12241 (Trusted Domain Wizard link doesn't work when using a specific port), https://github.com/owncloud/core/issues/14320 ("Add trusted domains" button doesn't work), https://github.com/owncloud/core/issues/7663 (trusted domain upgrade is not correctly working with occ), https://github.com/owncloud/core/issues/23202 (Trusted domains are not recognized), and https://github.com/owncloud/core/issues/7074 (Internet connection not working).

**Comment by soydepr** [comment]
I dont get the option to add up in browser so I did it in config file. Where do I need to specify port?

**Comment by DeepDiver1975** [comment]
> Yes i did the domain of my isp. Yes

I don't see any domain name in the config.php you posted above.

The domain you enter in the browser e.g. cloud.example.net has to be entered into the config.php as well

**Comment by soydepr** [comment]
Ok that works from home .  I did a quick test and connected to my office vpn and was not able will try later but thanks for the tip I thought trusted domains was for where I am connecting from ..ll will update once at office

**Comment by soydepr** [comment]
So definitely from the outside does not work 
Not sure where too look

**Comment by DeepDiver1975** [comment]
> So definitely from the outside does not work

but this is the something beyond the config of the trusted domains.
Is there a proxy or ssl termination in place? So that the request once on owncloud level are not longer for the domain you have setup to be used from outside?

I suggest you start a discussion on https://central.owncloud.org - this is where the community helps on such issues.

I'm closing this for the time being.
