### ISSUE TITLE
sync stable10 & master tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#32392]
- [x] backport of https://github.com/owncloud/core/pull/32378
- [x] backport tests of https://github.com/owncloud/core/pull/30920
- [x] skip tests in master that are affected by https://github.com/owncloud/core/issues/32385

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/31691 ([stable10] update user-sync help description), https://github.com/owncloud/core/pull/31450 ([stable10] Add caldav test to drone), https://github.com/owncloud/core/pull/31025 (Stable10 seen single sync), https://github.com/owncloud/core/issues/22485 (test), and https://github.com/owncloud/core/issues/31579 (test).

**Comment by individual-it** [comment]
fixed by #32433 and #32390
