### ISSUE TITLE
[9672] - Doloremque rerum voluptatibus error qui corporis ullam laboriosam odio sequi iusto laudantium culpa minima.

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#32400]
126

**Comment by tomneedham** [comment]
🙈 testing - wrong repo.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/28840 (-Error-), https://github.com/owncloud/core/issues/29082 (a Error), https://github.com/owncloud/core/issues/13597 (Votre dossier de données et vos fichiers sont probablement accessibles depuis internet. Le fichier .htaccess ne fonctionne pas. Nous vous recommandons vivement de configurer votre serveur web de façon à ce que ce dossier de données ne soit plus accessible, ou bien de le déplacer à l'extérieur de la racine du serveur web. ), and https://github.com/owncloud/core/issues/7466 (Suspicious errors).
