### ISSUE TITLE
Confusing log message when creating a user (via occ)

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#32438]
### Steps to reproduce
1. sudo -uwww-data ./occ user:add --email="whoever@me.bu" --display-name="User Name" user_x

### Expected behaviour
A message which either tells success or fail + reason

### Actual behaviour
```
{"reqId":"aAKMnFQRmek08dZ2U7Wf","level":3,"time":"2018-08-25T18:36:00+02:00","remoteAddr":"",
"user":"--","app":"no app in context","method":"--","url":"--","message":
"User backend OC\\User\\Database is returning home: \/var\/www\/owncloud\/data\/user_x 
for user: user_x which differs from existing value: "}
```
### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7,1

**ownCloud version:** 10.0.9

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**The content of config/config.php:**

```
```

**List of activated apps:**

```
```

**Are you using external storage, if yes which one:** local/smb/ftp/dropbox...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### ownCloud log (data/owncloud.log)
see above

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/30853 (A log is shown when we create a regular user), https://github.com/owncloud/core/issues/18932 (Confusing behaviour when disabling encryption app via occ), https://github.com/owncloud/core/issues/17374 (occ should be able  to create new user), https://github.com/owncloud/core/issues/16101 (Encryption log messages), and https://github.com/owncloud/core/issues/739 (Can't create user).

**Comment by mmattel** [comment]
Duplicate of https://github.com/owncloud/core/issues/30853 (A log is shown when we create a regular user)

**Comment by phil-davis** [comment]
Is this happening in a "real" install, or just in a git clone development environment?

I know there is something related to ``enable_alt_user_backend`` and the ``testing`` app that gets set in acceptance tests and causes? this log message.

**Comment by mmattel** [comment]
It is in my production environment, which is sourced from tar

**Comment by mmattel** [comment]
I think the root cause can be found in the log text:
```
"User backend OC\\User\\Database is returning home: \/var\/www\/owncloud\/data\/user_x 
for user: user_x which differs from existing value: "
```
When ``user_x`` is created, he has of course no existing home.
This creates a difference in ``home_now`` and ``home_before``. 
``home_before`` is naturally empty.

Without reading the code, a solution could be to define in case a user gets created, that ``home_before`` is set to the ``home_now``...

**Comment by voroyam** [comment]
@PVince81 can you evaluate this? 

A customer has asked about this error message in his log file.

**Comment by PVince81** [comment]
remember that one @tomneedham ?

would it be safe to discard the warning if the home folder "existing value" is empty ?
