### ISSUE TITLE
Acceptance tests should run OK  not as www-data

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32459]
In  theory, the acceptance tests are "black box". They should not need to run as the web server user name (e.g. ``www-data``). They should be just accessing the API and webUI. When they want to do setup, run/test an ``occ`` command then they use the testing app API to do that.

We should be able to remove ``su-exec www-data`` from our ``run.sh`` acceptance test commands.

**Comment by phil-davis** [comment]
PR #32458 demonstrates the current situation. Most tests pass. Some fail (e.g. some local/external storage tests). https://drone.owncloud.com/owncloud/core/9789

Need to look into these and see what they are doing that should/could be done in a more "black box" way.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @individual-it.

Possibly related issues are https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/30855 ([Stable10] Acceptance tests not being able to run from daily-stable10-qa tarball), and https://github.com/owncloud/core/issues/32040 (fix acceptance tests).

**Comment by phil-davis** [comment]
core and testing PRs reference above make this work in core.
Other PRs in apps have also successfully removed ``su-exec www-data`` from before ``run.sh``
The test runner code is another step more independent from the server-under-test.
