### ISSUE TITLE
Deleted Files Broken When Quota != Unlimited

### ISSUE THREAD

**Issue by miqrogroove** [owncloud/core#32465]
### Steps to reproduce
1.  Create a new user with 1 GB file quota.
2.  Enable external storage.
3.  Log in as the new user.
4.  Go to Settings > Storage and add an SMB folder that contains more than 1 GB of files already.
5.  Return to the Files app.
5.  Browse and/or wait until the size of the new folder is displayed.
6.  Return to All Files.
7.  Create or upload a new file here in the local storage.  This seems to work normally.
8.  Delete the newly created file.
9.  Go to Deleted files and confirm the file appears there.
10.  Wait, then attempt to verify the deleted file is still in the trashbin after some time.

### Expected behaviour
The deleted file should remain in the trashbin for 180 days.

### Actual behaviour
The deleted file always disappears after approximately one minute, which I assume is related to the cron timing.

I've also observed that this problem is resolved instantly upon setting this user's quota to Unlimited.

### Server configuration
**Operating system**: Ubuntu 18.04.1

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2

**ownCloud version:** 10.0.9 (stable)

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** https://download.owncloud.org/community/owncloud-10.0.9.zip

**Signing status (ownCloud 9.0 and above):** No errors have been found.

**The content of config/config.php:**

I can attempt to upload this report separately if needed.  I have already confirmed that the quota_include_external_storage does not appear anywhere in the report or in my config.php file.

According to the manual, the external storage is NOT included in quotas by default.  https://doc.owncloud.org/server/10.0/admin_manual/configuration/user/user_configuration.html

**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome 68

**Operating system:** Windows 10

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/5509 (quota completely broken), https://github.com/owncloud/core/issues/13824 (Delete File), https://github.com/owncloud/core/issues/27274 (delete), https://github.com/owncloud/core/issues/13402 (... broken), and https://github.com/owncloud/core/issues/2472 (Delete Multiple files.).

**Comment by miqrogroove** [comment]
I also found some messages in owncloud.log that look like this:

{"reqId":"b8fJJJcIod2xzpbRRjAh","level":3,"time":"2018-08-27T16:47:01+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"--","url":"--","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/files_trashbin\\\/files\\\/republic.png.d1535388395 not found while trying to get owner\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Filesystem.php(960): OC\\\\Files\\\\View->getOwner('\\\/files_trashbin...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Preview.php(1315): OC\\\\Files\\\\Filesystem::getOwner('\\\/files_trashbin...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OC\\\\Preview::post_delete(Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(635): OC_Hook::emit('\\\\\\\\OCP\\\\\\\\Trashbin', 'delete', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(668): OCA\\\\Files_Trashbin\\\\Trashbin::emitTrashbinPostDelete('\\\/files_trashbin...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(803): OCA\\\\Files_Trashbin\\\\Trashbin::delete('republic.png', 'miqrogroove', '1535388395')\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Trashbin.php(763): OCA\\\\Files_Trashbin\\\\Trashbin::deleteFiles(Array, 'miqrogroove', -26056040536)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_trashbin\\\/lib\\\/Command\\\/Expire.php(56): OCA\\\\Files_Trashbin\\\\Trashbin::expire('miqrogroove')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Command\\\/CommandJob.php(34): OCA\\\\Files_Trashbin\\\\Command\\\\Expire->handle()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(57): OC\\\\Command\\\\CommandJob->run('O:33:\\\"OCA\\\\\\\\Files...')\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/QueuedJob.php(42): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#11 \\\/var\\\/www\\\/owncloud\\\/cron.php(121): OC\\\\BackgroundJob\\\\QueuedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php\",\"Line\":1718}"}

**Comment by PVince81** [comment]
hmm, trashbin cleanup should not take external storage contents into account.

sounds like a bug.

**Comment by VicDeo** [comment]
in general it depends on trashbin retention policy that was not provided in the report.
https://doc.owncloud.org/server/10.0/admin_manual/configuration/server/config_sample_php_parameters.html#deleted-items-trash-bin
Basing on 180 days expectation I assume that it is set either  to `180, auto` or `180, D` where D>180?

**Comment by miqrogroove** [comment]
No, 180 days is specified in one of the ownCloud manuals I found while researching why the files were gone within minutes.

**Comment by VicDeo** [comment]
@miqrogroove it is 30 days by default https://github.com/owncloud/core/blob/master/apps/files_trashbin/lib/Expiration.php#L31
but this is internal value that is not guaranteed when there is no minimal retention set.

I admit that y default purging should not be started before reaching 50% of quota anyway https://github.com/owncloud/core/blob/master/config/config.sample.php#L517

**Comment by stkjj** [comment]
Problem is - as described here: https://central.owncloud.org/t/deleted-files-from-external-storage-get-stored-on-internal-space/28875 - that the deleted files end up in files_trashbin on the local storage. The correct way to handle would be to retain the trashed files on the external storage in a separate files_trashbin folder there. Same applies to files_versions.

Similar happens when the quota on owncloud is unlimited, but the diskspace as such is limited either by disk-quota or just by disksize.

**Comment by miqrogroove** [comment]
Was this ever resolved, or is it still broken?
