### ISSUE TITLE
jQuery UI Upgrade (+ Apps)

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/core#32476]
Upgrading from jQuery 1.10 to -> 1.11. -> 1.12.

Hint: Apps that are ~~stricken thru~~ do not use jquery-ui

- [x] open `jquery-ui-migration` [branch in core](https://github.com/owncloud/core/issues/32484)
- [x] open `jquery-ui-migration` issue & branch in corresponding app repos
   - [x] [activity](https://github.com/owncloud/activity/issues/643)
   - [ ] ~~announcementcenter~~
   - [ ] ~~configreport~~
   - [x] [customgroups](https://github.com/owncloud/customgroups/issues/163)
   - [ ] ~~davclient~~
   - [ ] ~~encryption~~
   - [ ] ~~enterprise_key~~
   - [x] [files_antivirus](https://github.com/owncloud/files_antivirus/issues/255)
   - [ ] ~~files_external_dropbox~~
   - [x] [files_pdfviewer](https://github.com/owncloud/files_pdfviewer/issues/158)
   - [x] [files_texteditor](https://github.com/owncloud/files_texteditor/issues/244)
   - [ ] ~~files_videoplayer~~
   - [ ] ~~firewall~~
   - [x] [firstrunwizard](https://github.com/owncloud/firstrunwizard/issues/81)
   - [ ] gallery
   - [ ] ~~impersonate~~
   - [ ] ~~market~~
   - [ ] ~~notifications~~
   - [x] [oauth2](https://github.com/owncloud/oauth2/issues/157)
   - [ ] ~~password_policy~~
   - [ ] ~~ransomware_protection~~
   - [x] [sharepoint](https://github.com/owncloud/sharepoint/issues/288)
   - [ ] ~~systemtags_management~~
   - [ ] ~~templateeditor~~
   - [ ] ~~twofactor_totp~~
   - [x] [user_ldap](https://github.com/owncloud/user_ldap/issues/277)
   - [ ] ~~user_shibboleth~~
   - [ ] ~~windows_network_drive~~
   - [ ] ~~workflow~~

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/18739 (Get rid of jquery UI), https://github.com/owncloud/core/issues/3501 (Update JQuery ...), https://github.com/owncloud/core/issues/15267 (UPGRADE ISSUE), https://github.com/owncloud/core/issues/25640 (Upgrade Issue), and https://github.com/owncloud/core/issues/12506 (Upgrade Prob).

**Comment by PVince81** [comment]
hmm I thought `.focus()` was already adressed through the jquery update ? or is it when calling `.focus()` on jquery ui widgets specifically ?

**Comment by PVince81** [comment]
it should be possible to use the old branch jquery-2-migration as we already had the jquery ui update in it ?

**Comment by PVince81** [comment]
we also need to check core, did you check it ? I see it's ticked...

on jquery-2-migration I see errors related to `$.widget` on the login page

**Comment by felixheidecke** [comment]
> hmm I thought .focus() was already addressed through the jquery update?

It's explicitly mentioned in the upgrade guide so I put it on the list. It used to take an integer param but doesn't anymore. So the depreciation is about the parameter. Let's see how UI'ish that is ;-)

**Comment by felixheidecke** [comment]
The core ticket is linked on the very top.

**Comment by PVince81** [comment]
seems we're done ?

**Comment by felixheidecke** [comment]
We're done!
