### ISSUE TITLE
jQuery UI Upgrade

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/core#32484]
See the full [upgrade 1.11. guide](https://jqueryui.com/upgrade-guide/1.11/)
See the full [upgrade 1.12. guide](https://jqueryui.com/upgrade-guide/1.12/)

Corresponding PR: https://github.com/owncloud/core/pull/32060

---

# Core

## [1.11] (Core) Deprecated multiple

`.focus()`

- [x] core/js/jquery.ocdialog.js
- [x] core/js/js.js
- [x] core/js/multiselect.js
- [x] core/js/sharedialoglinkshareview.js
- [x] core/js/sharedialogview.js
- [x] core/js/singleselect.js
- [x] core/js/systemtags/systemtagsinputfield.js
- [x] core/search/js/search.js

## [1.11] (Position) position offset removed

`.position()`

- [x] core/js/multiselect.js
- [x] core/search/js/search.js

## [1.11] (Widget) multiple changes

`.widget()`

- [x] core/js/jquery.ocdialog.js

## [1.12] (Core) Removed multiple

`.focus()`

- [x] core/js/jquery.ocdialog.js
- [x] core/js/js.js
- [x] core/js/multiselect.js
- [x] core/js/sharedialoglinkshareview.js
- [x] core/js/sharedialogview.js
- [x] core/js/singleselect.js
- [x] core/js/systemtags/systemtagsinputfield.js
- [x] core/search/js/search.js

## [1.12] (Button) Deprecated options

`.button()`

- [x] core/js/setup.js

## [1.12] (Buttonset) Deprecated methodname

`.buttonset()`

- [x] core/js/setup.js

## [1.12] (tooltip) CSS class changes

`.tooltip()`

- [x] core/js/js.js
- [x] core/js/sharedialogexpirationview.js
- [x] core/js/sharedialoglinklistview.js
- [x] core/js/sharedialoglinksocialview.js
- [x] core/js/sharedialogshareelistview.js
- [x] core/js/sharedialogview.js
- [x] core/js/systemtags/systemtagsinputfield.js

---

# Vendor Libs

## [1.11] (Core) Deprecated multiple

`.focus()`

- [x] backbone/examples/todos/todos.js
- [x] bootstrap/dist/js/bootstrap.js _not related to jQuery UI_
- [x] bootstrap/dist/js/bootstrap.min.js
- [x] bootstrap/docs/assets/js/customize.min.js
- [x] bootstrap/docs/assets/js/docs.min.js
- [x] bootstrap/docs/assets/js/raw-files.min.js
- [x] bootstrap/docs/assets/js/vendor/ZeroClipboard.min.js
- [x] bootstrap/docs/assets/js/vendor/jquery.min.js
- [x] bootstrap/docs/dist/js/bootstrap.js
- [x] bootstrap/docs/dist/js/bootstrap.min.js
- [x] bootstrap/js/modal.js
- [x] bootstrap/js/tests/vendor/jquery.min.js
- [x] clipboard/dist/clipboard.js
- [x] clipboard/dist/clipboard.min.js
- [x] clipboard/src/clipboard-action.js
- [x] jcrop/js/Jcrop.js
- [x] jcrop/js/Jcrop.min.js
- [x] jcrop/js/jquery.Jcrop.js
- [x] jcrop/js/jquery.Jcrop.min.js
- [x] jcrop/js/jquery.min.js
- [x] jcrop/src/api.js
- [x] jcrop/src/component/DragState.js
- [x] jcrop/src/component/Selection.js
- [x] jcrop/src/component/StageDrag.js
- [x] select2/select2.js
- [x] select2/select2.min.js

## [1.11] (Position) position offset removed

`.position()`

- [x] backbone/test/vendor/jquery.js
- [x] bootstrap/docs/assets/js/vendor/jquery.min.js
- [x] bootstrap/js/tests/unit/affix.js
- [x] bootstrap/js/tests/unit/scrollspy.js
- [x] bootstrap/js/tests/unit/tooltip.js
- [x] bootstrap/js/tests/vendor/jquery.min.js
- [x] jcrop/js/Jcrop.js
- [x] jcrop/js/Jcrop.min.js
- [x] jcrop/js/jquery.min.js
- [x] jcrop/src/component/DragState.js
- [x] jcrop/src/component/Selection.js
- [x] jquery/dist/jquery.js
- [x] jquery/dist/jquery.min.js
- [x] jquery/src/offset.js
- [x] zxcvbn/demo/jquery.js

## [1.11] (Widget) multiple changes

`.widget()`

## [1.12] (Core) Removed multiple

`.focus()`

- [x] backbone/examples/todos/todos.js
- [x] bootstrap/dist/js/bootstrap.js
- [x] bootstrap/dist/js/bootstrap.min.js
- [x] bootstrap/docs/assets/js/customize.min.js
- [x] bootstrap/docs/assets/js/docs.min.js
- [x] bootstrap/docs/assets/js/raw-files.min.js
- [x] bootstrap/docs/assets/js/vendor/ZeroClipboard.min.js
- [x] bootstrap/docs/assets/js/vendor/jquery.min.js
- [x] bootstrap/docs/dist/js/bootstrap.js
- [x] bootstrap/docs/dist/js/bootstrap.min.js
- [x] bootstrap/js/modal.js
- [x] bootstrap/js/tests/vendor/jquery.min.js
- [x] clipboard/dist/clipboard.js
- [x] clipboard/dist/clipboard.min.js
- [x] clipboard/src/clipboard-action.js
- [x] jcrop/js/Jcrop.js
- [x] jcrop/js/Jcrop.min.js
- [x] jcrop/js/jquery.Jcrop.js
- [x] jcrop/js/jquery.Jcrop.min.js
- [x] jcrop/js/jquery.min.js
- [x] jcrop/src/api.js
- [x] jcrop/src/component/DragState.js
- [x] jcrop/src/component/Selection.js
- [x] jcrop/src/component/StageDrag.js
- [x] jquery/dist/jquery.js
- [x] jquery/dist/jquery.min.js
- [x] jquery/src/event.js
- [x] select2/select2.js
- [x] select2/select2.min.js

`.button()`

- [x] bootstrap/docs/assets/js/docs.min.js
- [x] bootstrap/docs/assets/js/src/application.js

## [1.12] (Mouse) multiple changes

`.resizable()`

- [x] bootstrap/docs/assets/js/customize.min.js
- [x] bootstrap/docs/assets/js/raw-files.min.js

## [1.12] (tooltip) CSS class changes

`.tooltip()`

- [x] bootstrap/docs/assets/js/docs.min.js
- [x] bootstrap/docs/assets/js/src/application.js
- [x] bootstrap/docs/examples/tooltip-viewport/tooltip-viewport.js
- [x] bootstrap/js/tests/unit/tooltip.js
- [x] strengthify/jquery.strengthify.js

**Comment by felixheidecke** [comment]
@PVince81 looks like `core/js/multiselect.js` and it's `multiselect()` method is not used in core. So can't test. Lets see if it comes up in apps.

**Comment by PVince81** [comment]
might be used in user_management app (users page)

**Comment by felixheidecke** [comment]
> might be used in user_management app (users page)

Found it in user_ldap and it still works ;-) 👍

**Comment by PVince81** [comment]
@felixheidecke is this done ? I see unticked checkboxes

**Comment by felixheidecke** [comment]
Done.

**Comment by PVince81** [comment]
we need to backport this as it got lost during the branching model change @micbar

**Comment by PVince81** [comment]
also need to backport the jquery upgrade: https://github.com/owncloud/core/pull/32060

**Comment by phil-davis** [comment]
@felixheidecke @PVince81 what happened about this?
Did it ever get into the `stable10` -> new `master` ?

https://github.com/owncloud/core/pull/32060#issuecomment-480874274
"no backport. we'll use master in the future for releases" - ha ha
