### ISSUE TITLE
Guest users creating on flight from client app

### ISSUE THREAD

**Issue by macz71** [owncloud/core#32481]
Expected behaviour

Hi,
I’m missing an option to easy share files/folders with guest type users creating them on fly when typing email address into share field. It’s possible in web interface but I’m missing it from desktop client level.
Actual behaviour

Currently can’t put unknown email address and create guest user on fly from desktop client.
Steps to reproduce

    Try to share file from desktop client
    In share field type new email address
    There should be information like in web interface “Add email@address”

**Comment by PVince81** [comment]
known issue: https://github.com/owncloud/guests/issues/180

**Comment by PVince81** [comment]
@pmaier1 @michaelstingl raise client ticket for guest creation ?

there will be some challenges for implementing this, see owncloud/guests#180

**Comment by michaelstingl** [comment]
> @pmaier1 @michaelstingl raise client ticket for guest creation ?

Can this be made transparent for the clients? Maybe server can put it in the `shareWithAdditionalInfo` field? (https://github.com/owncloud/client/issues/6749, https://github.com/owncloud/android/issues/2284, https://github.com/owncloud/ios-app/issues/83)
