### ISSUE TITLE
See user name and email when sharing on web GUI and desktop app

### ISSUE THREAD

**Issue by macz71** [owncloud/core#32480]
Expected behaviour

Hi,
We are using owncloud with 2 AD domains and have same name users on both domains but different email addresses. As users are synced to owc from LDAP you see them the same when don’t see their email address so it’s hard to share to them from desktop app.
Actual behaviour

Share file to person and start typing name. Two or more the same names will popup (auto fill) without possibility to distinguish between them not seeing their details like email or so.
Steps to reproduce

    Create two the same users with same names and different email addresses
    Try to share file with user name: two or more users will be seen on desktop client or web GUI
    Try to pick the correct one

Client configuration

Client version: 2.4.3 (build 10347)

Operating system: Mac OS X, Windows 10, Windows 7

OS language: English

**Comment by phil-davis** [comment]
Login as an admin. Go to Settings, Sharing. In ``Extra field to display in autocomplete results`` select ``Email address`` from the dropdown. That is implemented in the browser-based webUI.

I am not sure when the behavior will come to the desktop client. You could look in the client repo and see if there is an issue already.

**Comment by macz71** [comment]
Hi,
It almost works from web GUI.
If you have long name surname and email address then displaying it is worthless right now as you can see only name and surname if you are lucky with short names.
It should always display it complete not cut, maybe hint-like style.
If you have had it in two lines displayed then it would be more helpful as you could always see email address no matter how long name and surname is.
Just user perspective :)
Thanks,

**Comment by PVince81** [comment]
@michaelstingl we discussed this recently. Clients need to implement the additional field as returned by the autocomplete APIs

**Comment by michaelstingl** [comment]
I opened issues for desktop and mobile apps:

- owncloud/client#6749
- owncloud/android#2284
- owncloud/ios-app#83
