### ISSUE TITLE
eliminate unneeded $requestBody variable in TestHelpers\WebDavHelper::makeDavRequest

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#32509]
```
		if ($requestBody !== null) {
			$options['body'] = $requestBody;
		}
```

```
		if ($body !== null) {
			$request->setBody($body);
		}
```
do we need both options? isn't that the same?

**Comment by phil-davis** [comment]
And trait ```WebDav.php`` has ``makeDavRequest()`` with those 2 parameters in a different order in its parameter list.
And deep down in the Guzzle implementation there is code that loops through the options, and for ``options['body']`` it does 
```
$request->setBody(Stream::factory($value));
```

They look the same to me. I guess this is a piece of history.

**Comment by phil-davis** [comment]
I made this p2 because it is good to clean up "little" bits of crud in test code.
