### ISSUE TITLE
fix API acceptance test steps, so that they really use old/new webdav path

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#32510]
this steps only use the old webdav and not obeying what is said in `Given using <dav_version> DAV path`
- [x] `@When /^the public downloads the last public shared file with range "([^"]*)" using the old WebDAV API$/`
- [x] `@When /^the public downloads file "([^"]*)" from inside the last public shared folder with range "([^"]*)" using the old WebDAV API$/`
- [x] `	@When /^the public downloads file "([^"]*)" from inside the last public shared folder with password "([^"]*)" with range "([^"]*)" using the old WebDAV API$/`
- [x] `@Then /^the public should be able to download the range "([^"]*)" of file "([^"]*)" from inside the last public shared folder with password "([^"]*)" and the content should be "([^"]*)"$/` -> it uses `publicDownloadsTheFileInsideThePublicSharedFolderWithPassword()`

**Comment by paurakhsharma** [comment]
@individual-it, should we close this now?

**Comment by individual-it** [comment]
fixed by #33297
