### ISSUE TITLE
apt key expired for Debian 8

### ISSUE THREAD

**Issue by dcaillibaud** [owncloud/core#32521]
### Steps to reproduce
with the repo (in /etc/apt/sources.list.d/owncloud.list)

```
deb http://download.owncloud.org/download/repositories/9.1/Debian_8.0/ /
```

`apt-key list`  show
```
pub   2048R/479BC94B 2013-08-26 [expired: 2018-08-25]
uid                  ownCloud build service <obsrun@localhost>
```
then
```
apt-key del 479BC94B
apt-get update
```
=>
```
W: GPG error: http://download.owncloud.org  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 47AE7F72479BC94B
```

`apt-key adv --keyserver pgpkeys.mit.edu --recv 47AE7F72479BC94B`
=> 
```
gpg: requesting key 479BC94B from hkp server pgpkeys.mit.edu
gpg: key 479BC94B: public key "ownCloud build service <obsrun@localhost>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
```
and `apt-get update` =>
```
W: GPG error: http://download.owncloud.org  Release: The following signatures were invalid: KEYEXPIRED 1535163442 KEYEXPIRED 1535163442 KEYEXPIRED 1535163442 KEYEXPIRED 1535163644 KEYEXPIRED 1535163442 KEYEXPIRED 1535163442 KEYEXPIRED 1535163442 KEYEXPIRED 1535163442 KEYEXPIRED 1535163644
```

### Expected behaviour
apt-get update should update

### Actual behaviour
see above

### Server configuration
**Operating system**:
debian8

**ownCloud version:** (see ownCloud admin page)
9.1

**Comment by heyho1** [comment]
From https://github.com/owncloud/core/issues/32436#issuecomment-416941710:

> Have you used the apt-key add command from https://download.owncloud.org/download/repositories/stable/owncloud/index.html (→ Debian) to update the key in your apt key database?
>
> wget -nv https://download.owncloud.org/download/repositories/production/Debian_9.0/Release.key -O Release.key
> apt-key add - < Release.key

**Comment by dcaillibaud** [comment]
Thanks for this workaround, it solves the pb, but copying the valid key in each repo would be a good idea ;-)

**Comment by heyho1** [comment]
According to https://github.com/owncloud/core/issues/32436#issuecomment-416129020 each repo has already a valid key since at least 8 days.

**Comment by PVince81** [comment]
@crrodriguez

**Comment by dcaillibaud** [comment]
@heyho1 But according to this issue, on august 30th it wasn't (http://download.owncloud.org/download/repositories/9.1/Debian_8.0/Release.key was expired)

And today it is still the case

```
apt-key del 479BC94B
wget http://download.owncloud.org/download/repositories/9.1/Debian_8.0/Release.key -O Release.key
apt-key add Release.key
apt-key list |grep 479BC94B
```
=> `pub   2048R/479BC94B 2013-08-26 [expired: 2018-08-25]`

To get the correct key you need to get the one of another repo
```
wget https://download.owncloud.org/download/repositories/production/Debian_9.0/Release.key -O Release.key
apt-key add Release.key
apt-key list |grep 479BC94B
```

**Comment by crrodriguez** [comment]
OBS master key expired a week ago..supported repositories were fixed accordingly.. 9.x repositories are permanently frozen and locked..nothing there will be fixed, rebuilt or otherwise change.. you have to use the workaround suggested as this won't be fixed, you really have to upgrade to 10.x branch.
Cheers.
