### ISSUE TITLE
GPG apt key expired for Ubuntu 16.04

### ISSUE THREAD

**Issue by kanebrands** [owncloud/core#32543]
### Steps to reproduce
1. Using the following source:
`deb http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ /`

2. Running:
`apt-get update`

3. Produces:
`Ign:8 https://attic.owncloud.com/org/download/repositories/stable/Ubuntu_16.04  InRelease
Get:12 http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  Release [989 B]
Get:13 http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  Release.gpg [481 B]
Err:13 http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  Release.gpg
  The following signatures were invalid: KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163644  KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163644  KEYEXPIRED 1535163442
Fetched 108 kB in 1s (71.8 kB/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  Release: The following signatures were invalid: KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163644  KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163644  KEYEXPIRED 1535163442
W: Failed to fetch http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/Release.gpg  The following signatures were invalid: KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163644  KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163644  KEYEXPIRED 1535163442
W: Some index files failed to download. They have been ignored, or old ones used instead.`

### Expected behaviour
Expected apt to check for updates on repository.

### Actual behaviour
Update displayed key expired errors and did not update.

### Server configuration
**Operating system**: Ubuntu 16.04

**Comment by phil-davis** [comment]
I am getting similar on my Ubuntu 16.04 laptop:
```
Ign:7 https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  InRelease                                        
Get:8 https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  Release [989 B]                                  
Get:9 https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  Release.gpg [481 B]                              
Err:9 https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  Release.gpg                                      
  The following signatures were invalid: KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163644  KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163442  KEYEXPIRED 1535163644  KEYEXPIRED 1535163442
```

**Comment by heyho1** [comment]
From https://github.com/owncloud/core/issues/32436#issuecomment-416941710:

> Have you used the apt-key add command from https://download.owncloud.org/download/repositories/stable/owncloud/index.html (→ Debian) to update the key in your apt key database?
>
> wget -nv https://download.owncloud.org/download/repositories/production/Debian_9.0/Release.key -O Release.key
> apt-key add - < Release.key

**Comment by phil-davis** [comment]
That fixed it.

**Comment by PVince81** [comment]
note: from what I heard repo keys have been renewed recently, so might need to reimport on some systems.

@crrodriguez

**Comment by heyho1** [comment]
@PVince81 According to https://github.com/owncloud/core/issues/32436#issuecomment-416129020 each repo (including Ubuntu 16.04) has already a valid key since around two weeks.

**Comment by colidyre** [comment]
> From [#32436 (comment)](https://github.com/owncloud/core/issues/32436#issuecomment-416941710):
> 
> > Have you used the apt-key add command from https://download.owncloud.org/download/repositories/stable/owncloud/index.html (→ Debian) to update the key in your apt key database?
> > wget -nv https://download.owncloud.org/download/repositories/production/Debian_9.0/Release.key -O Release.key
> > apt-key add - < Release.key

This doesn't work for me on Linux Mint Sarah (based on Ubuntu 16.04):

```bash
user@host:~$ wget -nv https://download.owncloud.org/download/repositories/production/Ubuntu_16.04/Release.key -O Release.key
user@host:~$ sudo apt-key add - < Release.key
```
Still had KEYEXPIRED message after that action. I had to fetch the key from [keys.gnupg.net][1]:

```bash
user@host:~$ sudo apt-key list | grep -a1 "expired:"

pub   2048R/557BEFF9 2016-09-25 [expired: 2020-01-18]
uid                  isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>

user@host:~$ sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 557BEFF9
```

Then `apt update` works as expected, i.e. without KEYEXPIRED message:

```bash
user@host:~$ sudo sudo apt-key list | grep -a1 "557BEFF9"

pub   2048R/557BEFF9 2016-09-25 [expires: 2022-04-02]
uid                  isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>
```

[1]: http://keys.gnupg.net/
