### ISSUE TITLE
\/owncloud\/remote.phpdf) is out of base uri \/owncloud\/remote.php\/webdav\/

### ISSUE THREAD

**Issue by gronkern** [owncloud/core#32548]
### Steps to reproduce
1. Install owncloud
2. Set config option 'overwritewebroot' to string 'owncloud'
3. Try to download sample file 'ownCloud Manual.pdf'

### Expected behaviour
Download link appears

### Actual behaviour
error message:
ownCloud
Internal Server Error

Technical details

    Remote Address: xxxxxxxxxxxx
    Request ID: xxxxxxxxxxxxxx

ownCloud – A safe home for all your data

log message:
"method":"GET","url":"\/owncloud\/remote.phpdf","message":"Exception: Requested uri (\/owncloud\/remote.phpdf) is out of base uri (\/owncloud\/remote.php\/webdav\/)

### Server configuration
**Operating system**:
CentOS Linux release 7.5.1804 (Core)

**Web server:**
Server version: Apache/2.4.6 (CentOS)
Server built:   Jun 27 2018 13:48:59

**Database:**
mysql  Ver 15.1 Distrib 10.1.35-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP 7.0.27 (cli) (built: Apr  4 2018 13:48:44) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

**ownCloud version:** (see ownCloud admin page)
  - installed: true
  - version: 10.0.9.5
  - versionstring: 10.0.9
  - edition: Community

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
repo http://download.owncloud.org/download/repositories/10.0/CentOS_7

**Signing status (ownCloud 9.0 and above):**
gpgkey http://download.owncloud.org/download/repositories/10.0/CentOS_7/repodata/repomd.xml.key
unsigned otherwise
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
File not found. 

**The content of config/config.php:**
$CONFIG = array (
  'updatechecker' => false,
  'passwordsalt' => 'xx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xx',
    1 => 'xx',
    2 => 'xx',
    3 => 'xx',
  ),
  'datadirectory' => 'xx',
  'overwrite.cli.url' => 'http://localhost',
  'dbtype' => 'mysql',
  'version' => '10.0.9.5',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => 'xx',
  'maintenance' => false,
  'singleuser' => false,
  'overwritewebroot' => 'owncloud',
  'overwritecondaddr' => 'owncloud',
  'data-fingerprint' => 'xx',
);
```

**List of activated apps:**
Enabled:
  - calendar: 1.5.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.4
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.5
  - notifications: 0.3.4
  - provisioning_api: 0.5.0
  - security: 0.0.2
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
61.0

**Operating system:**

### Logs
#### Web server error log
```
 - - [03/Sep/2018:08:35:50 +0200] "GET /owncloud/index.php/avatar/admin/28 HTTP/1.1" 200 32 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
 - - [03/Sep/2018:08:35:50 +0200] "GET /owncloud/index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 189 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
- - [03/Sep/2018:08:35:51 +0200] "GET /owncloud/core/img/actions/checkbox.svg HTTP/1.1" 200 479 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
 - - [03/Sep/2018:08:35:51 +0200] "GET /owncloud/core/img/actions/star.svg HTTP/1.1" 200 554 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
 - - [03/Sep/2018:08:36:20 +0200] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 108 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
 - - [03/Sep/2018:08:36:36 +0200] "REPORT /owncloud/remote.php/dav/comments/files/7143/ HTTP/1.1" 207 121 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
 - - [03/Sep/2018:08:36:36 +0200] "GET /owncloud/index.php/avatar/admin/28 HTTP/1.1" 200 32 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
 - - [03/Sep/2018:08:36:36 +0200] "PROPFIND /owncloud/remote.php/dav/systemtags-relations/files/7143 HTTP/1.1" 207 400 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
- - [03/Sep/2018:08:36:36 +0200] "GET /owncloud/remote.php/webdav/ownCloud%20Manual.pdf HTTP/1.1" 500 8504 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"W4zTB93rbynvTqu1-MokVgAAAAc","level":4,"time":"2018-09-03T06:21:59+00:00","remoteAddr":"91.65.172.148","user":"arno","app":"webdav","method":"GET","url":"\/owncloud\/remote.phpcs","message":"Exception: Requested uri (\/owncloud\/remote.phpcs) is out of base uri (\/owncloud\/remote.php\/webdav\/): {\"Exception\":\"LogicException\",\"Message\":\"Requested uri (\\\/owncloud\\\/remote.phpcs) is out of base uri (\\\/owncloud\\\/remote.php\\\/webdav\\\/)\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1295): Sabre\\\\HTTP\\\\Request->getPath()\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(474): Sabre\\\\DAV\\\\Server->checkPreconditions(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#5 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Request.php\",\"Line\":213}"}
{"reqId":"W4zVoMKsgYfW-pFgx8QQwwAAAAQ","level":4,"time":"2018-09-03T06:33:04+00:00","remoteAddr":"91.65.172.148","user":"admin","app":"webdav","method":"GET","url":"\/owncloud\/remote.phpdf","message":"Exception: Requested uri (\/owncloud\/remote.phpdf) is out of base uri (\/owncloud\/remote.php\/webdav\/): {\"Exception\":\"LogicException\",\"Message\":\"Requested uri (\\\/owncloud\\\/remote.phpdf) is out of base uri (\\\/owncloud\\\/remote.php\\\/webdav\\\/)\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1295): Sabre\\\\HTTP\\\\Request->getPath()\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(474): Sabre\\\\DAV\\\\Server->checkPreconditions(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#5 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Request.php\",\"Line\":213}"}
{"reqId":"W4zWdNrDvRcwtmwz6XUuDgAAAAM","level":4,"time":"2018-09-03T06:36:37+00:00","remoteAddr":"91.65.172.148","user":"admin","app":"webdav","method":"GET","url":"\/owncloud\/remote.phpdf","message":"Exception: Requested uri (\/owncloud\/remote.phpdf) is out of base uri (\/owncloud\/remote.php\/webdav\/): {\"Exception\":\"LogicException\",\"Message\":\"Requested uri (\\\/owncloud\\\/remote.phpdf) is out of base uri (\\\/owncloud\\\/remote.php\\\/webdav\\\/)\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1295): Sabre\\\\HTTP\\\\Request->getPath()\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(474): Sabre\\\\DAV\\\\Server->checkPreconditions(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#5 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/http\\\/lib\\\/Request.php\",\"Line\":213}"}
```

#### Browser log
```
{
  "log": {
    "version": "1.1",
    "creator": {
      "name": "Firefox",
      "version": "61.0"
    },
    "browser": {
      "name": "Firefox",
      "version": "61.0"
    },
    "pages": [
      {
        "startedDateTime": "2018-09-03T08:52:50.234+02:00",
        "id": "page_1",
        "title": "ownCloud",
        "pageTimings": {
          "onContentLoad": 360,
          "onLoad": 382
        }
      }
    ],
    "entries": [
      {
        "pageref": "page_1",
        "startedDateTime": "2018-09-03T08:52:50.234+02:00",
        "request": {
          "bodySize": 0,
          "method": "GET",
          "url": "https://xx/owncloud/remote.php/webdav/ownCloud%20Manual.pdf",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "xx"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0"
            },
            {
              "name": "Accept",
              "value": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "Cookie",
              "value": "xx"
            },
            {
              "name": "DNT",
              "value": "1"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            }
          ],
          "cookies": [
            {
              "name": "xx",
              "value": "xx"
            },
            {
              "name": "oc_sessionPassphrase",
              "value": "xx"
            }
          ],
          "queryString": [],
          "headersSize": 584
        },
        "response": {
          "status": 500,
          "statusText": "Internal Server Error",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Mon, 03 Sep 2018 06:53:24 GMT"
            },
            {
              "name": "Server",
              "value": "Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips"
            },
            {
              "name": "X-Powered-By",
              "value": "PHP/7.0.27"
            },
            {
              "name": "Expires",
              "value": "Thu, 19 Nov 1981 08:52:00 GMT"
            },
            {
              "name": "Cache-Control",
              "value": "no-store, no-cache, must-revalidate"
            },
            {
              "name": "Pragma",
              "value": "no-cache"
            },
            {
              "name": "X-XSS-Protection",
              "value": "1; mode=block"
            },
            {
              "name": "X-Content-Type-Options",
              "value": "nosniff"
            },
            {
              "name": "X-Frame-Options",
              "value": "SAMEORIGIN"
            },
            {
              "name": "X-Robots-Tag",
              "value": "none"
            },
            {
              "name": "X-Download-Options",
              "value": "noopen"
            },
            {
              "name": "X-Permitted-Cross-Domain-Policies",
              "value": "none"
            },
            {
              "name": "Content-Security-Policy",
              "value": "default-src 'none';"
            },
            {
              "name": "Strict-Transport-Security",
              "value": "max-age=15552000; includeSubDomains"
            },
            {
              "name": "Connection",
              "value": "close"
            },
            {
              "name": "Transfer-Encoding",
              "value": "chunked"
            },
            {
              "name": "Content-Type",
              "value": "text/html; charset=UTF-8"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/html; charset=UTF-8",
            "size": 8504,
            "text": "<!DOCTYPE html>\n<html class=\"ng-csp\" data-placeholder-focus=\"false\" lang=\"en\" >\n\t<head data-requesttoken=\"AB12JhM0H3BhPkwzODNAOExRRCAWZi9TPDAfOgcfagI=:EVCHcZEE4qzahg9p930ycSK8dBzQMSSLMiQjVn6frTk=\">\n\t\t<meta charset=\"utf-8\">\n\t\t<title>\n\t\townCloud\t\t</title>\n\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n\t\t<meta name=\"referrer\" content=\"never\">\n\t\t<meta name=\"viewport\" content=\"width=device-width, minimum-scale=1.0, maximum-scale=1.0\">\n\t\t\t\t\t<meta name=\"apple-itunes-app\" content=\"app-id=543672169\">\n\t\t\t\t<meta name=\"theme-color\" content=\"#1d2d44\">\n\t\t<link rel=\"icon\" href=\"/owncloud/core/img/favicon.ico\">\n\t\t<link rel=\"apple-touch-icon-precomposed\" href=\"/owncloud/core/img/favicon-touch.png\">\n\t\t<link rel=\"mask-icon\" sizes=\"any\" href=\"/owncloud/core/img/favicon-mask.svg\" color=\"#1d2d44\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/vendor/select2/select2.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/css/styles.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/css/inputs.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/css/header.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/css/icons.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/css/fonts.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/css/apps.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/css/global.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/css/fixes.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/css/multiselect.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/css/mobile.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/vendor/jquery-ui/themes/base/jquery-ui.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/css/jquery-ui-fixes.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/css/tooltip.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/css/share.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/apps/files_versions/css/versions.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t<link rel=\"stylesheet\" href=\"/owncloud/core/css/jquery.ocdialog.css?v=80001afb7647276a177ceba2189a5e50\">\n\t\t\t\t\t\t\t\t\t<script src=\"/owncloud/index.php/core/js/oc.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/vendor/jquery/dist/jquery.min.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/vendor/jquery-migrate/jquery-migrate.min.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/vendor/underscore/underscore.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/vendor/moment/min/moment-with-locales.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/vendor/handlebars/handlebars.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/vendor/blueimp-md5/js/md5.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/vendor/bootstrap/js/tooltip.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/vendor/backbone/backbone.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/vendor/es6-promise/dist/es6-promise.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/vendor/davclient.js/lib/client.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/vendor/clipboard/dist/clipboard.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/vendor/bowser/src/bowser.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/jquery.ocdialog.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/oc-dialogs.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/js.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/l10n.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/octemplate.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/eventsource.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/config.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/search/js/search.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/oc-requesttoken.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/apps.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/mimetype.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/mimetypelist.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/vendor/snapjs/dist/latest/snap.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/vendor/select2/select2.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/oc-backbone.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/placeholder.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/jquery.avatar.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/shareconfigmodel.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/sharemodel.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/sharescollection.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/shareitemmodel.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/sharedialogresharerinfoview.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/sharedialoglinklistview.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/sharedialoglinkshareview.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/sharedialogmailview.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/sharedialoglinksocialview.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/sharedialogexpirationview.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/sharedialogshareelistview.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/sharedialogview.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/share.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/files/fileinfo.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t<script src=\"/owncloud/core/js/files/client.js?v=80001afb7647276a177ceba2189a5e50\"></script>\n\t\t\t\t\t</head>\n\t<body id=\"body-login\">\n\t\t<noscript>\n\t<div id=\"nojavascript\">\n\t\t<div>\n\t\t\tThis application requires JavaScript for correct operation. Please <a href=\"http://enable-javascript.com/\" target=\"_blank\" rel=\"noreferrer\">enable JavaScript</a> and reload the page.\t\t</div>\n\t</div>\n</noscript>\n\t\t<div class=\"wrapper\">\n\t\t\t<div class=\"v-align\">\n\t\t\t\t\t\t\t\t\t<header role=\"banner\">\n\t\t\t\t\t\t<div id=\"header\">\n\t\t\t\t\t\t\t<div class=\"logo\">\n\t\t\t\t\t\t\t\t<h1 class=\"hidden-visually\">\n\t\t\t\t\t\t\t\t\townCloud\t\t\t\t\t\t\t\t</h1>\n\t\t\t\t\t\t\t</div>\n\t\t\t\t\t\t\t<div id=\"logo-claim\" style=\"display:none;\"></div>\n\t\t\t\t\t\t</div>\n\t\t\t\t\t</header>\n\t\t\t\t\t\t\t\t<span class=\"error error-wide\">\n\t<h2><strong>Internal Server Error</strong></h2>\n\t<br>\n\n\t<h2><strong>Technical details</strong></h2>\n\t<ul>\n\t\t<li>Remote Address: 91.65.172.148</li>\n\t\t<li>Request ID: W4zaZHEHRlpb8Lw7mFqPNgAAAAo</li>\n\t</ul>\n</span>\n\t\t\t\t<div class=\"push\"></div>\n\t\t\t</div>\n\t\t</div>\n\t\t<footer role=\"contentinfo\">\n\t\t\t<p class=\"info\">\n\t\t\t\t<a href=\"https://owncloud.org\" target=\"_blank\" rel=\"noreferrer\">ownCloud</a> &ndash; A safe home for all your data\t\t\t</p>\n\t\t</footer>\n\t</body>\n</html>\n"
          },
          "redirectURL": "",
          "headersSize": 643,
          "bodySize": 9147
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 0,
          "ssl": 0,
          "send": 0,
          "wait": 123,
          "receive": 1
        },
        "time": 124,
        "_securityState": "secure",
        "serverIPAddress": "xx",
        "connection": "443"
      }
    ]
  }
}
```

**Comment by PVince81** [comment]
please add the missing slash at the beginning of the setting, this is likely the problem
