### ISSUE TITLE
Columns that used to be bigint are int in some setup scenarios

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#32555]
Looking at oc_addressbooks:

- setup v10.0.9 from scratch: no BIGINT :no_entry_sign: 
- upgrade from stable8.2 to v10.0.9: no BIGINT :no_entry_sign: 
- upgrade from stable9 to v10.0.9: you get BIGINT :white_check_mark: 
- upgrade from stable9.1 to v10.0.9: you get BIGINT :white_check_mark: 
- upgrade from v10.0.1 to v10.0.9: no BIGINT :no_entry_sign: 

The reason is that since the introduction of the migrations in the dav app in https://github.com/owncloud/core/pull/27157 we create the table differently, and we create it with **INT**.

From what I see when checking out a few commits before https://github.com/owncloud/core/pull/27157 (like 31a2084fa6), setting up OC will create oc_addressbooks.id as a BIGINT.
The verification that was done in https://github.com/owncloud/core/pull/27157#issuecomment-280063994 claims that the MDB2 table had an INT. So either the verification was based on the wrong schema dump, or something else is making modern databases and MDB2 decide to create as BIGINT instead of INT from back then.

- [x] ~~investigate / dig into MDB2 code to confirm that it was always creating as BIGINT, not only recently with recent DB~~
- [ ] write additional migrations to migrate those columns to BIGINT based on a new diff

cc @VicDeo

**Comment by PVince81** [comment]
I had a look at the diff of the tables comparing the DB schema from a "9.1.8->10.0.10" upgrade to a "10.0.10" new install.

Here is a list of fields that need to be switched to bigint:
- oc_addressbookchanges.id
- oc_addressbooks.id
- oc_calendarchanges.id
- oc_calendarobjects.id
- oc_calendars.id
- oc_calendarsubscriptions.id
- oc_cards.id
- oc_card_properties.id
- oc_dav_shares.id
- oc_schedulingobjects.id
- 

Other missing parts:
- oc_calendarobjects.classification has an additional comment: `  `classification` int(11) DEFAULT 0 COMMENT '0 - public, 1 - private, 2 - confidential',`
- oc_share_external.remote has a different comment with fixed typo
- oc_notifications have indices with missing names:
```
  KEY `IDX_16B80748C96E70CF` (`app`),
  KEY `IDX_16B807488D93D649` (`user`),
  KEY `IDX_16B80748A5D6E63E` (`timestamp`),
  KEY `IDX_16B8074811CB6B3A232D562B` (`object_type`,`object_id`)
```
should be
```
  KEY `oc_notifications_app` (`app`),
  KEY `oc_notifications_user` (`user`),
  KEY `oc_notifications_timestamp` (`timestamp`),
  KEY `oc_notifications_object` (`object_type`,`object_id`)
``` 

I guess the easiest now is to write a migration file that will conditionally convert to bigint when necessary.

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/core/pull/33545#issuecomment-439792267

**Comment by DeepDiver1975** [comment]
close once backport is done and closed

**Comment by PVince81** [comment]
backport is here: https://github.com/owncloud/core/pull/33603
