### ISSUE TITLE
Part-completed v2 chunked upload

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32567]
The following unusual sequence works:
- set a firewall rule that limits upload size
- start a collection with MKCOL
- upload a few chunks within the upload limit
- upload a chunk that makes the total exceed the firewall file size limit - a 403 is returned
- assemble your collection into a real file (success 200)

You get a real file that is smaller than the firewall upload size limit, and is a truncated version of the file that you were trying to upload.

This might happen when you are out of quota, or any other reason that the file is going to be "too big".

Is this OK, bad or just weird?

**Comment by phil-davis** [comment]
If the client gives up after getting the 403 onn one of the chunks, and does not actively go back and remove the chunks uploaded so far then those chunks get left "hanging around" on the server.

If the client carries on regardless, it ends up with a truncated file.

I guess if the client provides a checksum then the final move is going to fail. So that might clean out the pending chunks?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/16278 (Problems with Chunked upload), https://github.com/owncloud/core/issues/31973 (MOVE on chunked upload), https://github.com/owncloud/core/issues/5326 (web dav chunked upload tasks), https://github.com/owncloud/core/issues/17066 (Upload movie fail : chunking loop), and https://github.com/owncloud/core/issues/19433 (WebGUI upload never completes).

**Comment by patrickjahns** [comment]
> If the client gives up after getting the 403 on one of the chunks, and does not actively go back and remove the chunks uploaded so far then those chunks get left "hanging around" on the server.

 `dav:cleanup-chunks` command takes care of the dangling parts. AFAIK this also runs as a background job

**Comment by phil-davis** [comment]
Yes, and whatever happens there is also anyway the problem if the client just "goes away" after uploading a few chunks. For that case there is no chunk that has a "403" returned. The chunks uploaded so far "just sit" on the server, and the server has no easy way to know if the client is on the train in a tunnel and about to come out, or is gone for good.

So that cleanup job is needed anyway.

**Comment by patrickjahns** [comment]
So to summarize - the only Problem is, when the client doesn't send a checksum and a chunk is missed.

How should ownCloud react in this scenario? cc @PVince81 @DeepDiver1975

**Comment by PVince81** [comment]
Normally when you assemble your collection you send a header "OC-Total-Length" to specify the expected length. If the server finds that it doesn't match it will fail with 400 Bad request or similar.

**Comment by PVince81** [comment]
other than that the server has no chance to know what the expected size is and if no checksum is sent no verification can be done.

in the future we could also decide to refuse to assemble if neither checksum nor total size was sent...
