### ISSUE TITLE
SmokeTest Results 10.0.10RC2

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/core#32565]
Some scenarios to consider:
- [x] OAuth2 and sync + mobile clients ( can be deployed remotely ) Tested with mobile clients(see above)
- [x] LDAP https://github.com/owncloud/core/issues/32565#issuecomment-420903823
- [x] Shibboleth ( + LDAP ) https://github.com/owncloud/core/issues/32565#issuecomment-420600735
- [x] Windows Network Drive ( please also use it as sync target ) https://github.com/owncloud/core/issues/32565#issuecomment-420990863
- [x] Guests https://github.com/owncloud/core/issues/32565#issuecomment-421310760
- [x] Impersonate https://github.com/owncloud/core/issues/32565#issuecomment-421320113

# Smoke test

**Tester assigned: @davitol** 

## Previous requirements

Prepare two servers with ssl activated and trusted certificates.

Enable LDAP and external storage apps.

Have a LDAP server ready to be used with owncloud.

Have ready two external storages of your choice SMB, SFTP, Dropbox, Google Drive, FTP, S3, ownCloud, local.

## Testing setup

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Enable encryption app and encryption default module | Encryption is enabled correctly |  :ballot_box_with_check: |
2 | Populate owncloud server with users and groups | Users and groups are correctly created |  :ballot_box_with_check: |
3 | Share a folder remotely using federated sharing with admin user of the other server. | folder can be opened in recipient server without problems |  :ballot_box_with_check: |
4 | Set up LDAP, as admin check users. log in with a LDAP user, if possible one with an avatar. | Users are loaded. LDAP user logs in without problems. Avatar is shown if it exists.  |  :ballot_box_with_check: |
5 | Set up two external storages different, disable encryption in one of them.| No errors in this process |  :ballot_box_with_check: |

## Testing functionality

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Share a file using federated sharing from an external unencrypted external storage in server #1 using a LDAP user to the admin user in server #2. | Admin user in server #2 can see the file. |  :ballot_box_with_check: |
2 | Open internet explorer or edge and upload a new avatar for a regular user not LDAP | Interface can be used, avatar is uploaded, check that personal page has a scroll bar and scrolls fine. |  :ballot_box_with_check: |
3 | Upload several files and folders inside external storages, open some. | No problems uploading, files can be downloaded and opened. |  :ballot_box_with_check: |
4 | Delete files inside both external storages. Recover some after from the trashbin. |  Files are correctly deleted and restored. | :ballot_box_with_check: |
5 | Using webdav upload a 100MiB file.| No errors in this process |  :ballot_box_with_check: |

**Comment by individual-it** [comment]
## Shibboleth smoke tests

**Comment by individual-it** [comment]
## LDAP smoke tests
WIP

**Comment by jesmrec** [comment]
# Smoke test Android [DONE]

Device & Android version: Nexus 5X v8.1.0
Android app version: 2.8.0 stable
Server version: 10.0.10RC2
OAuth2 version: 0.2.3


### Login

Test Case | Expected Result | Result | Related Comment
| :------- | :---------------: | :------ | :-----------------: | 
Login with one account (HTTPS)  | It is possible to access | :white_check_mark: |
Login with one account (HTTP)  | It is possible to access  | :white_check_mark: |
Login with one account OAuth2 |  It is possible to access|  :white_check_mark:|

### Folder

TestID | Test Case | Steps | Expected Result | Result | Related Comment
------------ | ------------- | ----------- | -------------- | ----- | ------
1 | Create a new folder  | 1. Tap on create a new folder |The folder is created| :white_check_mark: basic<br>:white_check_mark: OAuth2  |
2 | Create a folder with special character | 1. Tap on create a new folder <br> 2. Use a name with special characters (e.g $%&¨)| The folder is created with special character  | :white_check_mark: basic<br>:white_check_mark: OAuth2 |
3 | Rename a folder | 1. Create a new folder<br> 2. Rename the folder|  Folder is renamed|:white_check_mark: basic<br>:white_check_mark: OAuth2
4 | Move a folder | 1. Create a new folder <br> 2. Move the folder| Folder is moved to the specifield location |:white_check_mark: basic<br>:white_check_mark: OAuth2
5 | Upload a file into a folder | 1. Create a new folder <br> 2. Upload a file| File is uploaded into the folder |:white_check_mark: basic<br>:white_check_mark: OAuth2
6 | Delete a folder  | 1. Access to a folder, the folder has deep structure inside <br> 2. Download some files <br>3. Select delete that folder  | 2. The files are downloaded<br>3. The folder is removed|:white_check_mark: basic<br>:white_check_mark: OAuth2
7| Copy Folder | 1. Long press to copy a folder <br> 2. Select a location to paste | The folder and all its content is copied in the location, and remains too in the original|:white_check_mark: basic<br>:white_check_mark: OAuth2
8 | Share the folder by link | 1. Create a new folder <br>2. Long press to share the folder by link <br>  | The link is generated and works|:white_check_mark: basic<br>:white_check_mark: OAuth2
9 | Share the folder by link with pass| 1. Create a new folder <br>2. Long press to share the folder by link <br> 3. Enable the password protection and set a password | The link is generated and only works if the correct password is typed|:white_check_mark: basic<br>:white_check_mark: OAuth2
10| Unshare the folder by link | 1. Unshare the folder of previous test cases| The link is no more available |:white_check_mark: basic<br>:white_check_mark: OAuth2
11 | Share the folder with users or groups| 1. Create a new folder <br> 2. Long press to share with users/groups <br> 3. Type one user/group to share with |  The user/group can access to the folder|:white_check_mark: basic<br>:white_check_mark: OAuth2
12| Unshare the folder with users or groups| 1. Unshare the folder in the previous test case | The folder is not more available for the sharees |:white_check_mark: basic<br>:white_check_mark: OAuth2
13| Sync a folder| 1. Create a folder <br> 2. In web app, upload some files in the folder <br> 3. Long press to sync the folder  | The folder is sync with the content on server|:white_check_mark: basic<br>:white_check_mark: OAuth2
 


### File

TestID | Test Case | Steps | Expected Result | Result | Related Comment
------------ | ------------- | ------------- | -------------- | ----- | ------
1 | Upload a new file  | 1. Upload a new file | The file is uploaded | :white_check_mark: basic<br>:white_check_mark: OAuth2
2 | Upload a file with special character | 1. Upload a new file (e.g f%&¨)| The file is uploaded |:white_check_mark: basic<br>:white_check_mark: basic<br>:white_check_mark: OAuth2
3 | Rename a file | 1. Create a new file <br> 2. Rename the file | The file is renamed |:white_check_mark: basic<br>:white_check_mark: OAuth2
4 | Move a file | 1. Create a new file <br> 2. Move the file | The file is renamed |:white_check_mark: basic<br>:white_check_mark: OAuth2
5 | Copy a file  | 1. Create a new file <br> 2. Copy the file | The file is copied to the selected location |:white_check_mark: basic<br>:white_check_mark: OAuth2
6 | Delete a file  | 1. Create a new file <br> 2. Delete the file | The file is deleted |:white_check_mark: basic<br>:white_check_mark: OAuth2
7 | Share the file by link | 1. Create a file<br> 2. Long press to share the file by link | The link is generated and works|:white_check_mark: basic<br>:white_check_mark: OAuth2
8 | Share the file by link with pass| 1. Create a file<br> 2. Long press to share the file by link <br> 3. Set a password| The link is generated and works when the correct pass is typed|:white_check_mark: basic<br>:white_check_mark: OAuth2
9 | Unshare the file by link | 1. Unshare the file of previous test cases |  The link is no more available|:white_check_mark: basic<br>:white_check_mark: OAuth2
10 | Share the file with users or groups| 1. Create a new file <br> 2. Long press to share with users/groups <br> 3. Type one user/group to share with |  The user/group can access to the file|:white_check_mark: basic<br>:white_check_mark: OAuth2
11| Unshare the file with users or groups| 1. Unshare the file in the previous test case | The file is not more available for the sharees |:white_check_mark: basic<br>:white_check_mark: OAuth2
12| Download a file| 1. Tap to download a file | The file is downloaded and marked with green arrow|:white_check_mark: basic<br>:white_check_mark: OAuth2
13| Av Offline file | 1. Long press to set as Av Offline a file | The file is downloaded and set as Av Offline with the yellow arrow |:white_check_mark: basic<br>:white_check_mark: OAuth2
14| Av Offline file | 1. Long press to unset an Av Offline a Av Offline file | The file has no more the yellow arrow |:white_check_mark: basic<br>:white_check_mark: OAuth2

**Comment by jesmrec** [comment]
# Smoke test iOS  [DONE]

Device & iOS version: iPhone 6SPlus v11
iOS app version: 3.8.0
Server version: 10.0.10RC2
OAuth2 version: 0.2.3

### Login

Test Case | Expected Result | Result | Related Comment
| :------- | :---------------: | :------ | :-----------------: | 
Login with one account (HTTPS)  | It is possible to access | :white_check_mark: |
Login with one account (HTTP)  | It is possible to access  | :white_check_mark: |


### Folder

TestID | Test Case | Steps | Expected Result | Result | Related Comment
------------ | ------------- | ----------- | -------------- | ----- | ------
1 | Create a new folder  | 1. Tap on create a new folder |The folder is created| :white_check_mark: OAuth<br>:white_check_mark: basic<br> |
2 | Create a folder with special character | 1. Tap on create a new folder <br> 2. Use a name with special characters (e.g $%&¨)| The folder is created with special character  | :white_check_mark: OAuth<br>:white_check_mark: basic<br> |
3 | Rename a folder | 1. Create a new folder<br> 2. Rename the folder|  Folder is renamed| :white_check_mark: OAuth<br>:white_check_mark: basic<br>
4 | Move a folder | 1. Create a new folder <br> 2. Move the folder| Folder is moved to the specifield location | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
5 | Upload a file into a folder | 1. Create a new folder <br> 2. Upload a file| File is uploaded into the folder | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
6 | Delete a folder  | 1. Access to a folder, the folder has deep structure inside <br> 2. Download some files <br>3. Select delete that folder  | 2. The files are downloaded<br>3. The folder is removed| :white_check_mark: OAuth<br>:white_check_mark: basic<br>
7| Copy Folder | 1. Long press to copy a folder <br> 2. Select a location to paste | The folder and all its content is copied in the location, and remains too in the original| NA
8 | Share the folder by link | 1. Create a new folder <br>2. Long press to share the folder by link <br>  | The link is generated and works| :white_check_mark: OAuth<br>:white_check_mark: basic<br>
9 | Share the folder by link with pass| 1. Create a new folder <br>2. Long press to share the folder by link <br> 3. Enable the password protection and set a password | The link is generated and only works if the correct password is typed|:white_check_mark: OAuth<br>:white_check_mark: basic<br>
10| Unshare the folder by link | 1. Unshare the folder of previous test cases| The link is no more available |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
11 | Share the folder with users or groups| 1. Create a new folder <br> 2. Long press to share with users/groups <br> 3. Type one user/group to share with |  The user/group can access to the folder | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
12| Unshare the folder with users or groups| 1. Unshare the folder in the previous test case | The folder is not more available for the sharees | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
 

### File

TestID | Test Case | Steps | Expected Result | Result | Related Comment
------------ | ------------- | ------------- | -------------- | ----- | ------
1 | Upload a new file  | 1. Upload a new file | The file is uploaded | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
2 | Upload a file with special character | 1. Upload a new file (e.g f%&¨)| The file is uploaded | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
3 | Rename a file | 1. Create a new file <br> 2. Rename the file | The file is renamed |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
4 | Move a file | 1. Create a new file <br> 2. Move the file | The file is renamed |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
5 | Copy a file  | 1. Create a new file <br> 2. Copy the file | The file is copied to the selected location | NA
6 | Delete a file  | 1. Create a new file <br> 2. Delete the file | The file is deleted |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
7 | Share the file by link | 1. Create a file<br> 2. Long press to share the file by link | The link is generated and works|:white_check_mark: OAuth<br>:white_check_mark: basic<br>
8 | Share the file by link with pass| 1. Create a file<br> 2. Long press to share the file by link <br> 3. Set a password| The link is generated and works when the correct pass is typed|:white_check_mark: OAuth<br>:white_check_mark: basic<br>
9 | Unshare the file by link | 1. Unshare the file of previous test cases |  The link is no more available|:white_check_mark: OAuth<br>:white_check_mark: basic<br>
10 | Share the file with users or groups| 1. Create a new file <br> 2. Long press to share with users/groups <br> 3. Type one user/group to share with |  The user/group can access to the file | :white_check_mark: OAuth<br>:white_check_mark: OAuth<br>:white_check_mark: basic<br>
11| Unshare the file with users or groups| 1. Unshare the file in the previous test case | The file is not more available for the sharees | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
12| Download a file| 1. Tap to download a file | The file is downloaded and marked with green tick|:white_check_mark: OAuth<br>:white_check_mark: basic<br>
13| Av Offline file | 1. Long press to set as av offline a file | The file is downloaded and set as av off with the yellow arrow |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
14| Av Offline file | 1. Long press to set as no av offline a file | The file has no more the yellow arrow | :white_check_mark: OAuth<br>:white_check_mark: basic<br>

**Comment by davitol** [comment]
# Test Plan wnd:listen and process-queue

## Previous requirements

Have a WND mountPoint configured


## Testing functionality

| Test Case                                | Expected Result                          | Result | Related Comment |
| ---------------------------------------- | ---------------------------------------- | ------ | --------------- |
| Run WND:listen command against a WND mountpoint with Log-in Credentials, save in session | The command should run OK and start listening | ✅      |                 |
| Run WND:listen command against a WND mountpoint with Log-in Credentials, save in database | The command should run OK and start listening | ✅     |                 |
| Run WND:listen command against a WND mountpoint with user entered, store in database | The command should run OK and start listening | ✅     |                 |
| Run WND:listen command against a WND mountpoint with Global Credentials | The command should run OK and start listening | ✅     |                 |
| Run WND:listen command against a WND mountpoint with username and password credentials | The command should run OK and start listening | ✅     |                 |
| Run wnd:process-queue command against a WND mountpoint with Log-in Credentials, save in session | An error should be thrown.              | ✅     |                 |
| Run wnd:process-queue command against a WND mountpoint with Log-in Credentials, save in database | The command should run OK and start processing the queue | ✅     |                 |
| Run wnd:process-queue command against a WND mountpoint with user entered, store in database | The command should run OK and start processing the queue | ✅      |                 |
| Run wnd:process-queue command against a WND mountpoint with Global Credentials | The command should run OK and start start processing the queue | ✅      |                 |
| Run wnd:process-queue command against a WND mountpoint with username and password credentials | The command should run OK and start processing the queue | ✅      |                 |
| Upload a file from the Desktop Client to a WND mountpoint | The file should not be downloaded again  | ✅      |                 |
| Modify a file/folder in the WND backend  | The file should change in ownCloud and in the Desktop Client folder | ✅      |                 |
| Rename a file/folder in the WND backend  | The file should change in ownCloud and in the Desktop Client folder | ✅      |                 |
| Delete a file/folder in the WND backend  | The file should change in ownCloud and in the Desktop Client folder | ✅      |                 |
| Change the permissions of a file in the WND backend | The file should change in ownCloud and in the Desktop Client folder | ✅      |                 |

**Comment by davitol** [comment]
## Impersonate Test Plan

| Test Case                                | Expected Result                          | Result         | Related Comment |
| ---------------------------------------- | ---------------------------------------- | -------------- | --------------- |
| Enable the app.                          | No problems found.                       | ✅     |            |
| As admin create a group 'group1' add three members 'user1', 'user2', 'user3'. Make 'user1' group admin of 'group1'. Login as 'user1', go to the users view. Impersonate 'user2'. | 'user1' can impersonate 'user2'. See his files. Behave like him. Like if he were logged in. | ✅               |                 |
| Check that a user who is not group admin cannot impersonate anyone. |                                          | ✅              |                 |
| As admin create a group 'group1' add four members 'user1', 'user2', 'user3' and 'admin' being admin user of the server. Make 'user1' group admin of 'group1'. Login as 'user1', go to the users view. Impersonate 'admin'. | Super admin cannot be impersonated.      | ✅              |                 |
| When impersonating a user, a warning appears adverting that you have logged as another user. | a warning appears. | ✅               |               |
| Check that impersonate options appears in the correct settings panel. |                                          | ✅              |                |
| **Interaction with other Apps**          |                                          |                |                 |
| Having ldap set up, enable impersonation for an ldap group. Make a user group admin. Using that user impersonate one of the other members of the ldap group. | Users can be impersonated without problems. | ✅             |                |
| A guest user cannot impersonate other users. |                                          | ✅              |                 |
| A guest user can be impersonated / can logout | | ✅   |    |
 |As admin, log in using a app password and impersonate a user | | ✅   |    |
| **Browsers**                             |                                          |                |                 |
| Check that all the UI elements are usable when browsing with safari. |                                          | ✅   |                 |
| Check that all the UI elements are usable when browsing with chrome. |                                          | ✅  |                 |
| Check that all the UI elements are usable when browsing with firefox. |                                          | ✅ |                 |

**Comment by davitol** [comment]
No blocker issue was found so let's close this ticket and build RC4
