### ISSUE TITLE
Streaming *.mov files does not work

### ISSUE THREAD

**Issue by luuthanhhieu** [owncloud/core#32571]
same steps I found in previous ticket [27161 ](https://github.com/owncloud/core/issues/27161) & [7](https://github.com/owncloud/files_videoplayer/issues/7)
### Steps to reproduce
1. Upload *.mov file to ownCloud
2. Share folder containing the *.mov file with a public link
3. Open the public link and try to open the *.mov file in the browser

### Expected behaviour
The video should be played within the browser.
I have tried on onedrive and can play move files in the same browser.

### Actual behaviour
ownClouds shows the following error:
"Video could not be opened because the type is not supported"

### Server configuration
**Operating system**: Ubuntu Server 18.04 LTS

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.2

**ownCloud version:** 10.0.9

**Updated from an older ownCloud or fresh install:** Fresh installation

**Where did you install ownCloud from:** owncloud home page

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Tested on IE, Chrome, Edge

**Operating system:** Win10

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @kdslkdsaldsal.

Possibly related issues are https://github.com/owncloud/core/issues/27161 (Streaming *.mov files does not work), https://github.com/owncloud/core/issues/23182 (File Search not working), https://github.com/owncloud/core/issues/7746 (Search for files doesn't work), https://github.com/owncloud/core/issues/11933 (Quota Field does not work ), and https://github.com/owncloud/core/issues/7661 (Logout does not work).

**Comment by PVince81** [comment]
the video player can currently only play formats supported by HTML5 video tag.

as far as I remember, MOV files are not supported natively by browsers.

I usually convert my video files to webm to make them playable there.

Please raise your request in https://github.com/owncloud/files_videoplayer in case there is browser support in the future, or if there is a library that transcodes videos on the fly...
