### ISSUE TITLE
Automated webUI tests for languages

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32583]
## Problem
We do not know, in an automated way, if alternate languages work in the UI.

## Solution
Add some range of UI tests that switch language and do basic smoke tests.

Some of the challenges here:
- most of the automated tests are clicking buttons by ``id`` ``name`` or some other HTML attributes. So the actual text of the button/field does not come into it. 
- when you make a test that specifically looks for particular text in a page element, e.g. "Shared with you" in Nepali, then if the translators decide to improve the translation then the test will suddenly start to fail when the translation change arrives automagically from Transifex.
- anyway, how do you know that the umlaut, Devanagari script,... is actually rendered and readable in the browser.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/17797 (Please test allow_url_fopen), and https://github.com/owncloud/core/issues/13713 (Language question - Transifex).

**Comment by individual-it** [comment]
> how do you know that the umlaut, Devanagari script,... is actually rendered and readable in the browser.
you don't e.g. in the current selenium docker container UTF is set-up and all is fine, except there are no Devanagari fonts installed. So our tests pass but if you watch the browser you will not see Nepali letters

**Comment by phil-davis** [comment]
For now, this is enough. We already had a simple test that switched to Russian. Now we have a test that switches to Hindi and checks a couple of the "easy strings that should not need to be changed again by the translators" (famous last words). So this at least confirms that something of the back-end translation infrastructure is functioning.
