### ISSUE TITLE
Docker-Container not starting after fsck

### ISSUE THREAD

**Issue by ssch91** [owncloud/core#32588]
I had some trouble with my VM hosting an OwnCloud-instance. I managed to get it up again, eventually had to go through a fsck though. The Univention-Portal is running, however, I cannot start the Owncloud at all.

The base I used is the KVM-template, so it is Debian 9 with OwnCloud running as a docker container.

Here is what I get from the Apache when trying to reach myserver/owncloud:
> Service Unavailable
>The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Trying to update OwnCloud from the Univention Portal (current version is 10.0.9) gets me the following (translated, original was German):
>An Error has occured: Could not start the app container. It needs to be running to be upgraded!
Find further information in the logfile on the corresponding system:
/var/log/univention/appcenter.log

This is the output in said logfile (appcenter.log):
>  39961 actions.start                    18-09-05 09:54:59 [   DEBUG]: Calling /etc/init.d/docker-app-owncloud start
 40023 cache                            18-09-05 09:55:00 [   DEBUG]: Cache outdated. Need to rebuild
 40023 cache                            18-09-05 09:55:00 [   DEBUG]: Loaded 88 apps from cache
 40023 cache                            18-09-05 09:55:00 [   DEBUG]: Cache outdated. Need to rebuild
 40023 cache                            18-09-05 09:55:00 [   DEBUG]: Loaded 197 apps from cache
 40023 cache                            18-09-05 09:55:00 [   DEBUG]: Cache outdated. Need to rebuild
 40023 cache                            18-09-05 09:55:00 [   DEBUG]: Loaded 381 apps from cache
 40023 actions.get                      18-09-05 09:55:00 [   DEBUG]: Calling get
 40023 actions.get.progress             18-09-05 09:55:00 [   DEBUG]: 0
 40023 actions.get                      18-09-05 09:55:00 [    INFO]: appcenter/apps/owncloud/container
 40023 actions.get.progress             18-09-05 09:55:00 [   DEBUG]: 100
 39961 actions.start                    18-09-05 09:55:00 [ WARNING]: Job for docker-app-owncloud.service failed because the control process exited with error code.
 39961 actions.start                    18-09-05 09:55:00 [ WARNING]: See "systemctl status docker-app-owncloud.service" and "journalctl -xe" for details.
 39961 actions.start                    18-09-05 09:55:00 [    INFO]: Starting docker-app-owncloud (via systemctl): docker-app-owncloud.service failed!
 39961 actions.start                    18-09-05 09:55:00 [   DEBUG]: /etc/init.d/docker-app-owncloud returned with 1
 39961 actions.start.progress           18-09-05 09:55:00 [   DEBUG]: 100
 39961 packages                         18-09-05 09:55:00 [   DEBUG]: Releasing LOCK
 39961 actions.upgrade                  18-09-05 09:55:00 [CRITICAL]: Could not start the app container. It needs to be running to be upgraded!
 39961 actions.upgrade                  18-09-05 09:55:00 [ WARNING]: Aborting...
 39961 actions.start                    18-09-05 09:55:00 [   DEBUG]: Calling start
 39961 actions.start.progress           18-09-05 09:55:00 [   DEBUG]: 0
 39961 actions.start                    18-09-05 09:55:00 [   DEBUG]: Calling /etc/init.d/docker-app-owncloud start
 40065 cache                            18-09-05 09:55:01 [   DEBUG]: Cache outdated. Need to rebuild
 40065 cache                            18-09-05 09:55:01 [   DEBUG]: Loaded 88 apps from cache
 40065 cache                            18-09-05 09:55:01 [   DEBUG]: Cache outdated. Need to rebuild
 40065 cache                            18-09-05 09:55:01 [   DEBUG]: Loaded 197 apps from cache
 40065 cache                            18-09-05 09:55:01 [   DEBUG]: Cache outdated. Need to rebuild
 40065 cache                            18-09-05 09:55:01 [   DEBUG]: Loaded 381 apps from cache
 40065 actions.get                      18-09-05 09:55:01 [   DEBUG]: Calling get
 40065 actions.get.progress             18-09-05 09:55:01 [   DEBUG]: 0
 40065 actions.get                      18-09-05 09:55:01 [    INFO]: appcenter/apps/owncloud/container
 40065 actions.get.progress             18-09-05 09:55:01 [   DEBUG]: 100
 39961 actions.start                    18-09-05 09:55:01 [ WARNING]: Job for docker-app-owncloud.service failed because the control process exited with error code.
 39961 actions.start                    18-09-05 09:55:01 [ WARNING]: See "systemctl status docker-app-owncloud.service" and "journalctl -xe" for details.
 39961 actions.start                    18-09-05 09:55:01 [    INFO]: Starting docker-app-owncloud (via systemctl): docker-app-owncloud.service failed!
 39961 actions.start                    18-09-05 09:55:01 [   DEBUG]: /etc/init.d/docker-app-owncloud returned with 1
 39961 actions.start.progress           18-09-05 09:55:01 [   DEBUG]: 100
 39961 utils                            18-09-05 09:55:01 [   DEBUG]: send_information: action=upgrade app=owncloud value=None status=429
 39961 utils                            18-09-05 09:55:01 [   DEBUG]: tracking information: {'status': 429, 'uuid': 'ce711d28-7fa8-4412-80f8-23baebccc618', 'app': u'owncloud', 'version': u'10.0.9-20180720', 'role': 'domaincontroller_master', 'action': 'upgrade', 'system-uuid': '280b9db8-5886-4bfc-a086-e5eadb699b9c'}

The key here I think is:

>  39961 actions.start                    18-09-05 09:55:00 [ WARNING]: Job for docker-app-owncloud.service failed because the control process exited with error code.

So from this point I am uncertain, whether docker really cannot start the app or does not find the container.

systemctl status docker-app-owncloud.service gives me this - it says no such object:
> ● docker-app-owncloud.service - LSB: Start the Container for owncloud
   Loaded: loaded (/etc/init.d/docker-app-owncloud; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2018-09-05 09:55:01 CEST; 6min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 40055 ExecStart=/etc/init.d/docker-app-owncloud start (code=exited, status=1/FAILURE)
      CPU: 741ms
Sep 05 09:55:00 ucs-3763 systemd[1]: Starting LSB: Start the Container for owncloud...
Sep 05 09:55:01 ucs-3763 docker-app-owncloud[40055]: Error: No such object: 760eeedaad4dc36672786fedf10bd420d904bd1c50fca1233116dee3990e105d
Sep 05 09:55:01 ucs-3763 docker-app-owncloud[40055]: Failed to determine container state. Probably it doesn't exist.
Sep 05 09:55:01 ucs-3763 docker-app-owncloud[40055]: This script cannot create a container from an image.
Sep 05 09:55:01 ucs-3763 docker-app-owncloud[40055]: It can just stop/restart existing containers.
Sep 05 09:55:01 ucs-3763 systemd[1]: docker-app-owncloud.service: Control process exited, code=exited status=1
Sep 05 09:55:01 ucs-3763 systemd[1]: Failed to start LSB: Start the Container for owncloud.
Sep 05 09:55:01 ucs-3763 systemd[1]: docker-app-owncloud.service: Unit entered failed state.
Sep 05 09:55:01 ucs-3763 systemd[1]: docker-app-owncloud.service: Failed with result 'exit-code'.

So probably I have to just reattach the docker container? I feel somehow confirmed, because docker  container ls -a outputs this, an empty table:

> CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@ucs-3763:~#

The docker container definitely exists, though, and it is not empty:
>root@ucs-3763:/var/lib/docker/containers# ls
760eeedaad4dc36672786fedf10bd420d904bd1c50fca1233116dee3990e105d

Any thoughts on that? How can I possibly convince docker to acknowledge the container again? Is my train of thoughs maybe completely derailed?
Thanks in advance.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/22588 ([master] swift docker is not starting up properly), https://github.com/owncloud/core/issues/12829 (Container DRY), https://github.com/owncloud/core/issues/10615 (Feature/Service Request: Provide an offical ownCloud docker container), https://github.com/owncloud/core/issues/12371 (Folder name cannot start with - [), and https://github.com/owncloud/core/issues/14817 (docker based autotest).

**Comment by ssch91** [comment]
Meanwhile I was able to discover that the config.v2.json in the container is broken, as well as the hostnameconfig. Is there a way to replace them with a default one?

**Comment by PVince81** [comment]
It looks like something is messed up in your environment, probably due to the event you had to recover from. This is not a bug in ownCloud, please go to http://owncloud.org/support for help
