### ISSUE TITLE
job-status endpoint for async upload has extra quotes in etag response

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#32593]
### Steps to reproduce
1. enable async upload `occ config:system:set dav.enable.async --type boolean --value=true`
2. move a file with `OC-LazyOps: true` header set `curl -X MOVE  http://localhost/owncloud-core/remote.php/dav/files/admin/welcome.txt -uadmin:admin -H 'OC-LazyOps: true' -H 'Destination: http://localhost/owncloud-core/remote.php/dav/files/admin/welcome2.txt' -v`
3. query OC-JobStatus-Location `curl -uadmin:admin localhost/owncloud-core/remote.php/dav/job-status/admin/5a7c5838-56cb-47b8-ac0e-4fb1e6d21316`

### Expected behaviour
result should be `{"status":"finished","fileId":"00000004ocjsvlzs93hf","ETag":"cb0b9cc1fe57dc71e3384b3cdf2e0d9e"}`

### Actual behaviour
ETag value has some extra quotes
`{"status":"finished","fileId":"00000004ocjsvlzs93hf","ETag":"\"cb0b9cc1fe57dc71e3384b3cdf2e0d9e\""}`

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache2
**Database:**
mySQL
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
10.0.9.5
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/18776 (An endpoint for fast etag retrieval.), https://github.com/owncloud/core/issues/10750 (Upload Status in Settings Dialog), https://github.com/owncloud/core/issues/31964 (WebDav Upload endpoint returning 403), https://github.com/owncloud/core/issues/25112 (webdav endpoints), and https://github.com/owncloud/core/issues/32580 (API/Acceptance tests for Async Upload).

**Comment by PVince81** [comment]
I think we always had extra double quotes all these years when returning an etag in a header. Not sure why they exist though.

Since here we're returning JSON we could decide to remove them unless we want to stay consistent with header contents.

**Comment by DeepDiver1975** [comment]
> ETag value has some extra quotes
> {"status":"finished","fileId":"00000004ocjsvlzs93hf","ETag":"\"cb0b9cc1fe57dc71e3384b3cdf2e0d9e\""}

this is correct - etag has to have quotes

**Comment by DeepDiver1975** [comment]
see - https://de.wikipedia.org/wiki/HTTP_ETag - etag is a quoted string
