### ISSUE TITLE
creating/touching encryption keys, eating up php-fpm processes, resulting in "Bad Gateway"

### ISSUE THREAD

**Issue by iwayagdh** [owncloud/core#32591]
Hi and thanks in advance for participate.

### Steps to reproduce
1. Share a big folder with another user or group
2. Unshare a big folder with another user or group

### Expected behaviour
No impact for the users to access the cloud.

### Actual behaviour
After some time the cloud gets unavailable for the users, givin the error "Bad Gateway".

Monitoring the operation I can see that owncloud touches every user-encryption-key from every file while adding or removing a user/group from a folder. With big folders (meaning: many files and subfolders) the operation takes very long and uses up all the php-fpm processes until no further process is available and from there all future access terminates in the "Bad Gateway" error. Waiting long enough (up to hours) the operation finishes and releases the php-fpm processes and users can access the cloud again. 
I dont understand why this operation is eating up all php-fpm processes.
Also problematic is that the user who starts the operation (adding/removing share) does not get any feedback when the operation is completed, regardless if the server hits the "Bad Gateway" state or not.

### Server configuration
**Operating system:** Debian 4.9

**Web server:** nginx/1.13.3

**Database:** MariaDB 10.1.26

**PHP version:** PHP 7.1

**ownCloud version:** 10.0.9

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** command line, source downloaded from owncloud.org

**Signing status (ownCloud 9.0 and above):** No errors have been found.

**The content of config/config.php:**
```
"system": {
        "instanceid": "oc338s0d1i80",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "10.0.9.5",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "***REMOVED SENSITIVE VALUE***h",
        "installed": true,
        "mail_smtpmode": "php",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "theme": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "activity_expire_days": 93,
        "log_rotate_size": "524288000",
        "mail_smtpport": "25",
        "skeletondirectory": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": false,
        "singleuser": false
    }
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.7
  - configreport: 0.1.1
  - dav: 0.3.2
  - encryption: 1.3.1
  - federatedfilesharing: 0.3.1
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.9.0
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - gallery: 16.1.0
  - market: 0.2.5
  - notifications: 0.3.4
  - templateeditor: 0.3.1
  - updatenotification: 0.2.1
Disabled:
  - comments
  - external
  - federation
  - files_videoplayer
  - firstrunwizard
  - provisioning_api
  - systemtags
  - user_external
```

**Are you using external storage, if yes which one:** nfs

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

#### Web server error log
repeatedly: [error] 22352#22352: *207156300 upstream timed out (110: Connection timed out) while reading response header from upstream, client: ***REMOVED SENSITIVE VALUE***, server: ***REMOVED SENSITIVE VALUE***, request: "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/***REMOVED SENSITIVE VALUE***.sock", host: "***REMOVED SENSITIVE VALUE***"

#### ownCloud log (data/owncloud.log)
no log entries concerning this action

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/7744 (Encryption app can't create public key for users), https://github.com/owncloud/core/issues/14187 (nginx + php5-fpm results in random 502 Bad Gateway), https://github.com/owncloud/core/issues/14360 (reopen nginx + php5-fpm results in random 502 Bad Gateway #14187), https://github.com/owncloud/core/issues/9032 (Share keys not created with new nested directories - encryption), and https://github.com/owncloud/core/issues/26942 (Link share encryption key not created for running uploads).

**Comment by PVince81** [comment]
It is by design that keys of every file need to be touched. When using user-key encryption, every file has a key. When sharing, the encryption app needs to create a share key for the newly added user so that they can get access to the file in question.

This operation can indeed take a long time. While it is known that its slowness can leave users wondering, it shouldn't crash your server.
