### ISSUE TITLE
Acceptance tests for webDAV Report search API

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/core#32602]
With https://github.com/owncloud/core/pull/31873 and  https://github.com/owncloud/core/pull/31946 we added an API method to search. As we are exposing with this another public API, that API should be covered by acceptance tests

**Comment by paurakhsharma** [comment]
With #33512 merged. Should we close this?

**Comment by individual-it** [comment]
closing, if more tests are needed please open a new ticket
