### ISSUE TITLE
LoginName is not a valid attribute

### ISSUE THREAD

**Issue by raphson93** [owncloud/core#32604]
Hi, I was enable to login because it said took long time to login.
So I decided to do a fresh installation.
After restore all the database and retry the login, now the log files said 

> LoginName is not a valid attribute

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/18680 (en@pirate is not a valid locale), https://github.com/owncloud/core/issues/10247 (WebDAV permission attribute wrong), https://github.com/owncloud/core/issues/25292 (560 is not a valid Directory resource), https://github.com/owncloud/core/issues/476 (Requested attribute member not found), and https://github.com/owncloud/core/issues/4462 (Encryption: "Your private key is not valid!").
