### ISSUE TITLE
 job-status endpoint for async move can be queried by any user

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#32617]
### Steps to reproduce
1. as user1 MOVE a file using the async operation
2. as user2 query the job status that was send by `OC-JobStatus-Location`

### Expected behaviour
queering the job-status of an other user should not be possible

### Actual behaviour
every user can query the job-status of every job

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/32597 (job-status endpoint for async upload does not have any error message with 403 code), https://github.com/owncloud/core/issues/32593 (job-status endpoint for async upload has extra quotes in etag response), https://github.com/owncloud/core/issues/6966 (Get logged in status for any user), https://github.com/owncloud/core/issues/28556 (LDAP user query - General error), and https://github.com/owncloud/core/issues/15977 (Add occ encryption:status to allow users to query if it's enabled or not).

**Comment by DeepDiver1975** [comment]
How would a Potential attacker know the Job ID?
What information is leaked even If?

I See this as pretty Low risk - even not existing risk.

Proof me wrong 🤗

**Comment by DeepDiver1975** [comment]
@PVince81 @individual-it see my comment above - I'd close this.
