### ISSUE TITLE
Switch between email and password in user creation form issue

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#32619]
### Steps

1. Setup OC
1. Go to the users page
1. Type "user1"
1. In the email field type "test", believing that this was the password field. Leave the value in the field.
1. Click on the cog icon at the bottom left
1. Click "Set password for user", this toggles the email field to be a password field
1. Type in "test" as password
1. Click "create"

### Expected result
User created.

### Actual result
Error message about invalid email address.
This is because the email field is just hidden and still has its value.

Solution is to either:
1. clear the field automatically when toggling
or
2. ignore the hidden field when gathering form values

### Version
ownCloud 10.0.1 RC1

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/27612 (Password forgotten usability issues), https://github.com/owncloud/core/issues/4491 (Design issues with password change), https://github.com/owncloud/core/issues/30511 (Password Email wont Set), https://github.com/owncloud/core/issues/4538 (Some issue with password), and https://github.com/owncloud/core/issues/16442 (How to disable user password reset?).

**Comment by davitol** [comment]
@PVince81 Maybe this exception thrown is related?

```
ErrorException: Undefined index: add_password
  File "/var/www/owncloud/settings/templates/users/main.php", line 85, in handleError
    class="checkbox" <?php if ($_['add_password'] === 'true') {
  File "/var/www/owncloud/settings/templates/users/main.php", line 85, in include
    class="checkbox" <?php if ($_['add_password'] === 'true') {
  File "/var/www/owncloud/lib/private/Template/Base.php", line 219, in load
    include $file;
  File "/var/www/owncloud/lib/private/Template/Base.php", line 194, in fetchPage
    return $this->load($this->template, $additionalParams);
  File "/var/www/owncloud/lib/private/legacy/template.php", line 236, in fetchPage
    $data = parent::fetchPage($additionalParams);
...
(6 additional frame(s) were not displayed)
```

**Comment by PVince81** [comment]
the exception is handled in https://github.com/owncloud/core/issues/32621

this ticket here is not critical, moving to backlog for next release

**Comment by phil-davis** [comment]
PR #39306 fixes this. I have tested manually.
