### ISSUE TITLE
Add url parameter which open a specific details tab right away  also available for Folders

### ISSUE THREAD

**Issue by davitol** [owncloud/core#32629]
LIke it was deployed for files in https://github.com/owncloud/core/pull/32152

## Description
This adds a url parameter to the files app which will open the details view and a specified tab for the given file in the scrollto parameter

## Motivation and Context
We need to open the share tab via url directly. Needed by the office online integration

It would be great if we can implement it for folders. For folders it enters it. Once you're inside a folder there is no sidebar for the current folder

@DeepDiver1975 FYI

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/pull/32152 ([master] Add url parameter which open a specific details tab right away), https://github.com/owncloud/core/pull/32202 ([stable10] Add url parameter which open a specific details tab right …), https://github.com/owncloud/core/issues/9243 (Folder specific views), https://github.com/owncloud/core/issues/16308 (ownCloud Right Side File / Folder Details), and https://github.com/owncloud/core/issues/1356 (Sharing Details are not available.).
