### ISSUE TITLE
ownclound not running after update to ubuntu 18.04

### ISSUE THREAD

**Issue by hschraep** [owncloud/core#32622]
### Steps to reproduce
1. install ubuntu 18.04
2.
3.

### Expected behaviour
Can't run owncloud with the browser.

### Actual behaviour
I have upgrade from ubuntu 16.04 to 18.04. After that owncloud did not work anymore. First i think it was the PHP version 7.2 but i installed also 7.0 and 7.1 via ppa. but they get the same error if i enable
the php module within apache. a2enmod php7.0 until 7.2.

I get this message within the apache2 errorlog:
[Thu Sep 06 15:33:47.533703 2018] [:error] [pid 8298] [client myip:50953] PHP Warning:  flock() expects parameter 1 to be resource, boolean given in /var/www/mydomain.de/owncloud/lib/private/config.php on line 178
[Thu Sep 06 15:33:47.536860 2018] [:error] [pid 8298] [client myip:50953] PHP Fatal error:  Uncaught Error: Call to a member function getValue() on null in /var/www/mydomain.de/owncloud/lib/private/legacy/config.php:46\nStack trace:\n#0 /var/www/mydomain.de/owncloud/lib/private/log.php(33): OC_Config::getValue('log_type', 'owncloud')\n#1 /var/www/mydomain.de/owncloud/lib/private/legacy/log.php(16): OC\\Log->__construct()\n#2 /var/www/mydomain.de/owncloud/lib/autoloader.php(114): require_once('/var/www/mydomain.m...')\n#3 [internal function]: OC\\Autoloader->load('OC_LOG')\n#4 /var/www/mydomain.de/owncloud/lib/public/util.php(82): spl_autoload_call('OC_LOG')\n#5 /var/www/mydomain.de/owncloud/lib/public/util.php(99): OCP\\Util::writeLog('index', 'Exception: {"Me...', 4)\n#6 /var/www/mydomain.de/owncloud/index.php(48): OCP\\Util::logException('index', Object(Exception))\n#7 {main}\n  thrown in /var/www/mydomain.de/owncloud/lib/private/legacy/config.php on line 46

### Server configuration
**Operating system**:
ubuntu 18.04 LTS

**Web server:**
Apache/2.4.29

**Database:**
mysql  Ver 14.14 Distrib 5.7.23

**PHP version:**
php7.0 php7.1 php7.2

**ownCloud version:** (see ownCloud admin page)
sudo -u www-data php7.0 occ status
  - installed: true
  - version: 10.0.9.5
  - versionstring: 10.0.9
  - edition: Community

**Updated from an older ownCloud or fresh install:**
update

**Where did you install ownCloud from:**
use the repositorys from onwcloud.org

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
sudo -u www-data php7.0 occ config:list
{
    "system": {
        "instanceid": "ocef1xwd58uh",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.5",
            "eisi.my-wan.de"
        ],
        "datadirectory": "\/home\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.1.5\/owncloud",
        "dbtype": "mysql",
        "version": "10.0.9.5",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 0,
        "mail_smtpmode": "php",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "theme": "",
        "maintenance": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "updatechecker": false,
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/owncloud",
        "memcache.local": "\\OC\\Memcache\\APCu"
    },

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**
Enabled:
  - activity: 2.3.7
  - calendar: 1.5.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.4
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.9.0
  - files_sharing: 0.10.1
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.1.0
  - market: 0.2.4
  - notifications: 0.3.4
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.3.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no



### Client configuration
**Browser:**
Mozimma firefox 62.0

**Operating system:**
windowns 10

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/14386 (HowTo update Ubuntu 14.04 / php5-apcu to a owncloud supported version), https://github.com/owncloud/core/issues/26999 (Installation of OwnClound 9.1 fails on Ubuntu 16.04 due to wrong dependencies), https://github.com/owncloud/core/issues/27762 (Owncloud update from 9x to 10. fails ubuntu 14.04), https://github.com/owncloud/core/issues/21366 (Update), and https://github.com/owncloud/core/issues/20661 (Update).

**Comment by hschraep** [comment]
I think i have all nessessary modules installed. If i start occ over the comandline i get no information that some php modules are missing.
$ php -m
[PHP Modules]
apcu
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imagick
imap
intl
json
ldap
libsmbclient
libxml
mbstring
memcache
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
smbclient
sockets
sodium
SPL
ssh2
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

$ php -m |grep xml
libxml
xml
xmlreader
xmlwriter
$ php -v
PHP 7.2.9-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Aug 19 2018 07:16:54) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.9-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

**Comment by biwerr** [comment]
> PHP Warning: flock() expects parameter 1 to be resource, boolean given in /var/www/mydomain.de/owncloud/lib/private/config.php on line 178
/var/www/mydomain.de/owncloud/lib/private/log.php(33): OC_Config::getValue('log_type', 'owncloud')\n#1 

Seems like an File opening issue, have you checked the permission? Which user runs the PHP in your Apache? Did you use php-fpm?
