### ISSUE TITLE
[10.0.10RC1] Undefined index: add_password

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/core#32621]
### Steps to reproduce
1. Go to User Page

### Expected behaviour
No Error logged

### Actual behaviour
Error logged as below

### Server configuration

**ownCloud version:** (see ownCloud admin page)
10.0.10.0 (RC1)

#### ownCloud log (data/owncloud.log)
```
ErrorException: Undefined index: add_password
#9 /var/www/owncloud/settings/templates/users/main.php(85): include
#8 /var/www/owncloud/lib/private/Template/Base.php(219): load
#7 /var/www/owncloud/lib/private/Template/Base.php(194): fetchPage
#6 /var/www/owncloud/lib/private/legacy/template.php(236): fetchPage
#5 /var/www/owncloud/lib/private/Template/Base.php(176): printPage
#4 /var/www/owncloud/settings/users.php(129): require_once
#3 /var/www/owncloud/lib/private/Route/Route.php(155): OC\Route\{closure}
#2 /var/www/owncloud/lib/private/Route/Router.php(342): match
#1 /var/www/owncloud/lib/base.php(909): handleRequest
#0 /var/www/owncloud/index.php(54): null
```

![image](https://user-images.githubusercontent.com/6403243/45163588-f8d86a00-b1f0-11e8-90dd-7daa21a2e2ec.png)

Sentry: https://sentry.owncloud.com/owncloud/owncloud-release-testing/issues/82

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/16096 (Undefinex index), https://github.com/owncloud/core/issues/12266 (Undefined index), https://github.com/owncloud/core/issues/4492 (Undefined plural_forms), https://github.com/owncloud/core/issues/652 (Undefined array indices if upload large files using fastCGI), and https://github.com/owncloud/core/issues/30291 (Problem with “occ files:scan –all –repair”: undefined index).

**Comment by PVince81** [comment]
backport was merged https://github.com/owncloud/core/pull/32636
