### ISSUE TITLE
CSRF check failed with centos 6.10

### ISSUE THREAD

**Issue by atmcommunicaction** [owncloud/core#32641]
When i try access to web interface, insert the login password....
Show me cat CSRF check failed...

I see my php.ini and it's all ok... 
owncloud 10.0.4
php 7.1.21
db mysql.

tnx all.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/25927 (CSRF check failed), https://github.com/owncloud/core/issues/28920 (Occasional unexpected CSRF check failed), https://github.com/owncloud/core/issues/23769 (Integrity check always fails), https://github.com/owncloud/core/issues/14558 (6 to 7 to 8 upgrade fails ), and https://github.com/owncloud/core/issues/6336 (Upgrade to 6.0 fails).
