### ISSUE TITLE
Unsharing not visible for sharer

### ISSUE THREAD

**Issue by MadriSX** [owncloud/core#32649]
### Steps to reproduce
1. User 1 share a folder to user 2.
2. User 2 unshare the folder.
3. Folder is still shared in user 1 but user 2 don´t see the shared folder.

### Expected behaviour
If user 2 unshare the folder, user 1 should see the same action reflected.

### Server configuration
**Operating system**:
3.16.0-6-amd64 #1 SMP Debian 3.16.57-2 (2018-07-14) x86_64 GNU/Linux

**Web server:**
Apache 2.4.10

**Database:**
MySQL 5.5.60

**PHP version:**
7.0.31 and 5.6.36

**ownCloud version:** (see ownCloud admin page)
10.0.9

**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**
Activity, PDF viewer, text editor and default apps.

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Several, this is not related to browser issues.

**Operating system:**
Not relevant.

**Comment by MadriSX** [comment]
This issue (or feature, there is a discussion) is related to this topic:
[https://central.owncloud.org/t/unsharing-not-visible-for-sharer/15440](url)

**Comment by MadriSX** [comment]
I consider if user1 one share a folder to user2 (with automatically acceptance) and user2 unshare the folder because he finished the work with that folder, user 1 should see the folder unshared or at least get some notification for accepting the unshare. 

I think I am not the only one using share/unsharing as way to know the other user finished the task.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/12964 (Reshare inner folder, recipients not visible by original sharer), https://github.com/owncloud/core/issues/14971 (Re-share not visible to original owner), https://github.com/owncloud/core/issues/19550 (Error when unsharing link ), https://github.com/owncloud/core/issues/6591 (Load only visible previews), and https://github.com/owncloud/core/issues/23316 (Invisible buttons should be visible).

**Comment by PVince81** [comment]
Currently this is by design to allow user2 to re-accept the share if needed.

@pmaier1 thoughts on the use case above ?

**Comment by MadriSX** [comment]
> Currently this is by design to allow user2 to re-accept the share if needed.
> 
> @pmaier1 thoughts on the use case above ?

Are you considering a unsharing option like if user 2 doesn´t re-accept in X hours (can be configured in settings) the share is definitively erased?
