### ISSUE TITLE
new-user password token can be deleted by anybody

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#32651]
### Steps to reproduce
1. create a new user providing username and email
2. call `settings/users/setpassword/form/thisisaninvalidtoken/<username>`
3. try to set the password with the correct token

real live example:
1. admin creates user with name "ceo" and email "cto@company.com"
2. admin deletes user "ceo" because of typo in the email address
3. admin created user "ceo" again with correct email "ceo@company.com"
3. owner of "cto@company.com" clicks on the received link
4. owner of "ceo@company.com" clicks on the received link, but cannot set password

### Expected behaviour
the user should be able to set the password with the correct token

### Actual behaviour
token got deleted, user cannot use the correct token to set password

CC @sharidas

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/27274 (delete), https://github.com/owncloud/core/pull/30981 (Add confirm password after new password), https://github.com/owncloud/core/issues/22991 (Send password to new users), https://github.com/owncloud/core/issues/16442 (How to disable user password reset?), and https://github.com/owncloud/core/issues/10092 (User Password Reset).

**Comment by PVince81** [comment]
p2 as discussed today

PR here: https://github.com/owncloud/core/pull/32672
