### ISSUE TITLE
make a new method to get/set/delete config.php settings in acceptance tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#32666]
currently `SetupHelper::runOcc()` is used everywhere directly to get/set/delete settings in `config.php` 
DRY it up and make a couple of methods

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/31347 (Acceptance tests to cover different config.php settings), https://github.com/owncloud/core/issues/751 (Updater deletes config.php), https://github.com/owncloud/core/issues/27274 (delete), https://github.com/owncloud/core/pull/32448 (Helper methods for deleting app config settings), and https://github.com/owncloud/core/pull/32379 (Make more acceptance test methods public).

**Comment by phil-davis** [comment]
PR #33095 implements this refactoring.
