### ISSUE TITLE
[v10.0.10RC1] Disabled comments hides notification icon

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/core#32678]
Again (https://github.com/owncloud/core/issues/31338, https://github.com/owncloud/core/issues/32117), my specific combination of enabled/disabled apps causes a tiny glitch…

```
root@9ce7f0799f51: /var/www/owncloud # occ app:list
Enabled:
  - announcementcenter: 1.2.0
  - configreport: 0.1.1
  - dav: 0.4.0
  - enterprise_key: 0.1.4
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.5
  - notifications: 0.3.5
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - theme-enterprise: 2.0.2
  - updatenotification: 0.2.1
Disabled:
  - comments
  - encryption
  - external
  - user_external
  - user_ldap
```

### Steps to reproduce
1. Fire up v10.0.10RC1 with `docker-compose`
2. Create 2nd user to check notification icon
3. `occ market:install announcementcenter`
4. `occ app:disable comments` ==> 2nd user doesn't get notification icon for new notifications created with `announcementcenter` (I think `market` update notifications too)
4. `occ app:enable comments` ==> 2nd user gets notification icon for new notifications created with `announcementcenter`

### Expected behaviour
Disabling `comments` shouldn't break features/UI

### Actual behaviour
Disabling `comments` hides notification icon

### Server configuration
Default installation with [`docker-compose`](https://github.com/owncloud-docker/server#launch-with-docker-compose)

### Client configuration
**Browser:**
Chrome 69

**Operating system:**
macOS 10.13.6

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/11987 (hide / disable sidebar), https://github.com/owncloud/core/issues/32117 ([10.0.9] Disabling comments breaks files_versions), https://github.com/owncloud/core/issues/5104 (Disable / hide unused file action buttons), https://github.com/owncloud/core/issues/21796 (New option to disable file icons), and https://github.com/owncloud/core/issues/7429 ([6.0.1RC2] Disable then re-enable encryption).

**Comment by PVince81** [comment]
Pfff, maybe another one of these "assuming that library X is loaded when it's not".

I'd say not critical, adding to future sprint.

**Comment by PVince81** [comment]
Works for me: when using announcement center, you must run cron for the notification entries to be created in "oc_notifications". The app doesn't generate them synchronously because it could be expensive with lots of users.

It is likely that when you tested and refreshed the page in one test case, the ajax cron ran and you thought it worked.

**Comment by PVince81** [comment]
Reopening for closer inspection with the docker-compose environment, in case it's reproducible there due to more subtle things.

**Comment by michaelstingl** [comment]
```
git clone https://github.com/owncloud-docker/server.git
cd server
sed -i -e 's/10.0.8/10.0.10rc1/g' .env
docker-compose up -d
```

**Comment by michaelstingl** [comment]
can't reproduce - sorry for the noise
