### ISSUE TITLE
Move sharing blacklist to regular sharing settings panel

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#32705]
Please move it to the regular sharing settings panel on top:

![sharing_blacklist](https://user-images.githubusercontent.com/21193500/45538002-1c5d6f00-b806-11e8-86ff-0f40d0e0e456.png)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/11648 ([Ask Feature] A sharing setting), https://github.com/owncloud/core/issues/30394 (Display original share owner in share panel), https://github.com/owncloud/core/issues/22674 (Sharing settings need to be revisited), https://github.com/owncloud/core/issues/30741 (Share options missing from web admin panel), and https://github.com/owncloud/core/issues/10306 (Setting Permissions on the share).

**Comment by PVince81** [comment]
Sounds good. @jvillafanez can you make it happen ?

See the "Federation" entry for styling and markup of headline and sub-headline
