### ISSUE TITLE
Renaming folders on a system with a lot of data takes a long time

### ISSUE THREAD

**Issue by esohlberg** [owncloud/core#32714]
### Steps to reproduce

1. Rename any folder.

2. Look at the SQL query that is executed by using 'show processlist' or 'show full processlist'- it should show something like SELECT `path`, `fileid` FROM `oc_filecache` WHERE `storage` = '1' AND `path` LIKE 'files/IIIF\\_Files/mvol/0004/1911/0111/TIFF/%'

3. Upload files to owncloud (we have 32Tb) to see system performance slow down as oc_filecache gets more and more records.

### Expected behaviour

The folder should be renamed almost instantly.

### Actual behaviour

The interface displays a spinner, and the renaming process takes about 30 minutes to complete on our system.

### Server configuration

**Operating system**:
FreeBSD

**Web server:**
Apache
**Database:**
mysql

**PHP version:**
5.6.36

**ownCloud version:** (see ownCloud admin page)
10.0.9.5

**Updated from an older ownCloud or fresh install:**
Updated from 10.0.3

**Where did you install ownCloud from:**
Installed via FreeBSD "pkg".

**Signing status (ownCloud 9.0 and above):**
https://gist.github.com/esohlberg/0bc614f26c1a28cf94189d88fb5bfb17

**The content of config/config.php:**
{
    "system": {
        "logtimezone": "America\/Chicago",
        "instanceid": "ock0y9nu39tl",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "\/tmp",
        "maintenance": false,
        "trusted_domains": [
            "ocdev.lib.uchicago.edu"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "asset-pipeline.enabled": true,
        "appcodechecker": false,
        "datadirectory": "\/data\/voldemort\/digital_collections\/data",
        "overwrite.cli.url": "https:\/\/ocdev.lib.uchicago.edu\/owncloud",
        "dbtype": "mysql",
        "version": "10.0.9.5",
        "dbname": "ocdb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "session_lifetime": 86400,
        "ldapIgnoreNamingRules": false,
        "enable_previews": true,
        "preview_max_scale_factor": 1,
        "has_internet_connection": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\PDF"
        ],

        "loglevel": 2,
        "theme": ""
    }
}
**List of activated apps:**
Enabled:
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - files: 1.5.1
  - files_external: 0.7.1

**Are you using external storage, if yes which one:** local/smb/sftp/...
No admin mounts configured.

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Google Chrome Version 69.0.3497.92

**Operating system:**
Windows 10 Enterprise 1803

#### Web server error log
n/a

#### ownCloud log (data/owncloud.log)
n/a

#### Browser log
n/a

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/457 (renaming folders), https://github.com/owncloud/core/issues/5349 (Rename folder "Shared" leads to unexpected data move), https://github.com/owncloud/core/issues/13391 (Data loss on rename of a 49 GB folder), https://github.com/owncloud/core/issues/14279 (Upgrade taking a long time), and https://github.com/owncloud/core/issues/2170 (By renaming a shared folder is not shared any more).
