### ISSUE TITLE
configuration step RC3

### ISSUE THREAD

**Issue by soydepr** [owncloud/core#32716]
before i proceed i want to clarify one question .

Do i need to set up the config.php first as i dont see a way in the UI install to switch to mariadb
![config](https://user-images.githubusercontent.com/546367/45588183-8c3f2880-b8de-11e8-8b76-0905cb50a951.png)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/10159 (Openldap SSL/TLS Configuration), https://github.com/owncloud/core/issues/20977 (Two-step Authentication Needed), https://github.com/owncloud/core/pull/30635 (Integration step definitions for when given), https://github.com/owncloud/core/pull/32361 (delete encryption related steps), and https://github.com/owncloud/core/pull/31525 (proper session configuration).

**Comment by soydepr** [comment]
solved by  installing  php-mysql  and restart webserver
