### ISSUE TITLE
rc3 install

### ISSUE THREAD

**Issue by soydepr** [owncloud/core#32717]
Sweet install RC  
perhaps email should be required when setting up admin account i had forgotten my password so i redid the install 

Big thanks. cant believe been some many years without this  gem 
hope the update from 10.9 to .10 as smooth  as well

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/32716 (configuration step RC3), https://github.com/owncloud/core/issues/2938 (How to set up a development install?), https://github.com/owncloud/core/issues/23107 (New Install Problems (9.0.0)), https://github.com/owncloud/core/issues/20200 (Easy way to install themes), and https://github.com/owncloud/core/issues/2203 (Can't install Owncloud 5 RC1 - RC3: 500 Internal Server Error).

**Comment by DeepDiver1975** [comment]
Glad to see you happy @soydepr :rocket:
