### ISSUE TITLE
Owncloud Error: blank Page with the text "Acces Denied."

### ISSUE THREAD

**Issue by OjunbamO** [owncloud/core#32729]
### Steps to reproduce
1. Installed CentOS 7 on Virtual Machine
2. Installing PHP
3. Installing Nginx
4. Installing MariaDB
5. Installing Owncloud

### Expected behaviour
The Installer from Owncloud should be opened.

### Actual behaviour
The Website just says "Acces denied." with a blank page.

### Server configuration
**Operating system**:
CentOS 7 (VirtualBox)

**Web server:**
Nginx

**Database:**
MariaDB

**PHP version:**
PhP 7.1.22

**ownCloud version:** (see ownCloud admin page)
Newest

**Updated from an older ownCloud or fresh install.**
Fresh Install 

**Where did you install ownCloud from:**
Official Page downloaded

**Signing status (ownCloud 9.0 and above):**

Acces Denied.

**The content of config/config.php:**

{
    "system": {
        "instanceid": "ocdns0a3e4j9",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.71"
        ],
        "datadirectory": "\/usr\/share\/nginx\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.1.71\/owncloud",
        "dbtype": "mysql",
        "version": "10.0.9.5",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}

**List of activated apps:**

Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.4
  - notifications: 0.3.4
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external

**Are you using encryption:**  no

### Client configuration
**Browser:**
Google Chrome

**Operating system:**
Mac OSX High Sierra

**Directory: /etc/nginx/nginx.conf**
`user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/nginx/README.dynamic.
`include` /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 2048;

    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

# Changed ~ \.php$ to ~ \.php(?:$|/)

        location ~ \.php(?:$|/) {
                include /etc/nginx/fastcgi_params;
                fastcgi_pass  127.0.0.1:9000;
                fastcgi_index index.php;
                fastcgi_param  SCRIPT_FILENAME  /home/ashfame/www/domain.in/public_html$fastcgi_script_name;
                include fastcgi.conf;

        }

        error_page 404 /404.html;
            location = /40x.html {
        }

        error_page 500 502 503 504 /50x.html;
            location = /50x.html {

        }
    }

}`
****

**Comment by patrickjahns** [comment]
Please note, this is a BUG Tracker for ownCloud related bugs. For assistance with setting up infrastructure around ownCloud ( server configuration, php, apache or nginx  ) please have a look at our community http://central.owncloud.org
