### ISSUE TITLE
acceptance tests that check upload overwriting with checksums

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#32724]
make sure problems like mentioned here are tested
https://github.com/owncloud/files_primary_s3/issues/128#issuecomment-421952808

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/pull/32723 (check file existence after upload with wrong checksums), and https://github.com/owncloud/core/pull/32559 (acceptance tests - stop uploading when receiving an error).
