### ISSUE TITLE
Group Sharing Blacklist does not block the shares for the users

### ISSUE THREAD

**Issue by davitol** [owncloud/core#32722]
### Steps to reproduce

1 - Create user Alice that belongs to group1
2 - Create user Bob that belongs to group2
3 - Go to sharing section-> Group Sharing Blacklist
4 - Add group1 and group2 to the Group Sharing Blacklist
5 - Bob shares a file with Alice

### Expected behaviour

File should not be shared due to Group Sharing Blacklist

### Actual behaviour

File is shared

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1

**ownCloud version:**

ownCloud 10.0.10.RC4. 

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
No logs in owncloud.log
```

### Client configuration

**browser**

Firefox

![screen shot 2018-09-17 at 11 17 42](https://user-images.githubusercontent.com/10596560/45614958-6f842b80-ba6b-11e8-8388-48c82e56c49c.png)
![screen shot 2018-09-17 at 11 18 26](https://user-images.githubusercontent.com/10596560/45614964-73b04900-ba6b-11e8-9680-da428c3473a3.png)

**Comment by davitol** [comment]
It was a misunderstanding from me about how the feature works. Groups do not appear so it works as designed. Closed

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/pull/31740 ([stable10] Sharing blacklist groups stable10), https://github.com/owncloud/core/issues/5016 (Share: cannot find users when sharing mode is groups only), https://github.com/owncloud/core/issues/20473 (If a user belongs to a group that has not been set in the excluded groups from sharing, he can share files), https://github.com/owncloud/core/issues/20022 (Cannot share with groups), and https://github.com/owncloud/core/issues/29279 (cannot share with a user that has the same name as a group).
