### ISSUE TITLE
"Workflows" app: tag manager doesn't work

### ISSUE THREAD

**Issue by va1entin** [owncloud/core#32728]
The tag manager that is supposed to be included in the Workflows app according to the [docs](https://doc.owncloud.org/server/latest/admin_manual/enterprise/file_management/files_tagging.html?highlight=workflow) is not visible/doesn't work on my Owncloud 10.0.9

### Steps to reproduce
1. Install Workflows app on OC 10.0.9
2. Go to settings -> Workflows & Tags
3. No tag manager, just a broken drop down

### Expected behaviour
Tag manager to add tags

### Actual behaviour
No tag manager, just a broken drop down

![owncloud-workflow-bug1](https://user-images.githubusercontent.com/31535155/45621045-3ce42e00-ba7f-11e8-996c-4929caad3f96.png)
Clicking on "add new workflow" opens the workflow form, still no possibility to add tags
![owncloud-workflow-bug2](https://user-images.githubusercontent.com/31535155/45621039-3950a700-ba7f-11e8-8a4b-af0fda383f4a.png)
### Server configuration
**Operating system**: Ubuntu 16.04.4 LTS (Owncloud Docker container)

**Web server:** Apache 2.4.18-2ubuntu3.8

**Database:**

**PHP version:** 7.0.30-0ubuntu0.16.04.1

**ownCloud version:** 10.0.9.5

**Updated from an older ownCloud or fresh install:** Fresh

**Where did you install ownCloud from:** Univention App Center

**Signing status (ownCloud 9.0 and above):**

```
"No errors have been found."
```

**The content of config/config.php:**

```
{
    "system": {
        "datadirectory": "\/var\/lib\/univention-appcenter\/apps\/owncloud\/data\/files",
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/custom",
                "url": "\/custom",
                "writable": true
            }
        ],
        "dbtype": "mysql",
        "dbhost": "172.17.42.1:3306",
        "dbname": "owncloud",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "trusted_domains": [
            "localhost"
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud",
        "version": "10.0.9.5",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "ocysgtsv056s",
        "ldapIgnoreNamingRules": false,
        "updatechecker": "false",
        "upgrade.disable-web": "true",
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "loglevel": "2",
        "default_language": "en",
        "htaccess.RewriteBase": "\/owncloud",
        "log_rotate_size": 104857600,
        "onlyoffice": {
            "verify_peer_off": true
        }
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - enterprise_key: 0.1.4
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.4
  - notifications: 0.3.4
  - provisioning_api: 0.5.0
  - ransomware_protection: 1.0.3
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
  - user_ldap: 0.11.0
  - workflow: 0.2.6
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
Shouldn't be relevant, will gladly supply it if required.

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Firefox 62, Chromium 69.0.3497.81

**Operating system:** Linux Mint 19

#### Web server error log
```
Doesn't log anything when I open the page.
```

#### ownCloud log (data/owncloud.log)
```
Doesn't log anything when I open the page.
```

#### Browser log
```
JQMIGRATE: Migrate is installed, version 1.4.0
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/17952 (Sharing doesn't work), https://github.com/owncloud/core/issues/1199 (DAV locking doesn't work.), https://github.com/owncloud/core/issues/7661 (Logout does not work), https://github.com/owncloud/core/issues/11933 (Quota Field does not work ), and https://github.com/owncloud/core/issues/4688 (Upload/Delete doesn't work properly).

**Comment by va1entin** [comment]
Could this already be verified? This enterprise app is basically unusable at the moment.

**Comment by va1entin** [comment]
My bad, just found that one has to install the "Collaborative Tags Management" app as well, to be able to create tags. The UI of the Workflows is still confusing in that regard I think. The "Add Tags" dropdown should only be visible in the workflow creation form I believe.

Also couldn't find anything about the Workflows app in the 10.0 docs. The docs for 9.x say that tags must be created in the Workflows app itself. That's where my question initially stems from.

https://doc.owncloud.org/server/9.0/admin_manual/enterprise_file_management/files_tagging.html
