### ISSUE TITLE
Broken link to admin docs in ransomware protection app

### ISSUE THREAD

**Issue by va1entin** [owncloud/core#32730]
The link to the admin docs for the ransomware protection app is broken. It can be found in the last line of the app's description.
Not including my OS, php version etc. because the issue can be observed on the public marketplace website as well: https://marketplace.owncloud.com/apps/ransomware_protection

### Expected behaviour
The link points to https://doc.owncloud.org/server/latest/admin_manual/enterprise/ransomware-protection/?highlight=ransomware

### Actual behaviour
The link leads to a 404 and points to https://doc.owncloud.com/server/latest/admin_manual/configuration/server/security/ransomware-protection.html

**Comment by patrickjahns** [comment]
Thank yo for raising this - we currently have an open ticket here https://github.com/owncloud/marketplace-issues/issues/24

Would like to track it in one location only
