### ISSUE TITLE
occ doesn't support an internal batched mode

### ISSUE THREAD

**Issue by robert-scheck** [owncloud/core#32752]
The greater picture of #32751 is to have an internal batched mode rather a long list of single `occ` calls (even they maybe support multiple apps to be enabled/disabled at once). Such an internal batched mode could look like this:

```
$ ./occ config:batch /tmp/commands.txt
market disabled
market enabled
No such app enabled: not_existing
.htaccess has been updated
Set mode for background jobs to 'cron'
Maintenance mode already disabled
$ 
```

```
$ cat /tmp/commands.txt
app:disable market
app:enable market
app:disable not_existing
maintenance:update:htaccess
background:cron
maintenance:mode --off
$ 
```

Note that `config:batch` is *not* intended as dumb shell script-like functionality that calls `occ` per line, but one single `occ` call where all commands are handled internally one after each other without having the need to re-load the PHP interpreter and the ownCloud classes. I expect a nice speedup of `occ` using such a functionality.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/32751 (occ doesn't support enabling/disabling multiple apps at once), https://github.com/owncloud/core/issues/24449 (occ doesn't seem to lock during upgrade operation?), https://github.com/owncloud/core/issues/20939 (occ fails hard if instance is in maintenance mode), https://github.com/owncloud/core/issues/6326 (OC 6 doesn't support spdy), and https://github.com/owncloud/core/issues/15599 (OC_EventSource does not support multiple streams on IE8).
