### ISSUE TITLE
occ doesn't support enabling/disabling multiple apps at once

### ISSUE THREAD

**Issue by robert-scheck** [owncloud/core#32751]
It would be great to be able to specify multiple apps to be enabled or disabled at once rather multiple `occ` calls given `occ` is not really fast due to PHP interpreter and the ownCloud classes as well being loaded each time.

Currently:

```
$ ./occ --no-interaction app:enable richdocuments 
$ ./occ --no-interaction app:enable market 
```

Expected:

```
$ ./occ --no-interaction app:enable richdocuments market
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/16092 (Apps disabled but cannot enable), https://github.com/owncloud/core/issues/15599 (OC_EventSource does not support multiple streams on IE8), https://github.com/owncloud/core/issues/29512 (Don’t allow multiple theme apps ), https://github.com/owncloud/core/issues/1805 (Migration disable all apps ), and https://github.com/owncloud/core/issues/884 (Cannot enable/disable apps with Internet Explorer).

**Comment by robert-scheck** [comment]
Ping?
