### ISSUE TITLE
User groups with spaces or special characters are empty (only on web interface)

### ISSUE THREAD

**Issue by smrecko** [owncloud/core#32759]
### Steps to reproduce
1. On web interface create user grup with space or special character in (for example "Test group" or "TestGroupČŽŠ"
2. Assign any user to that group
3. Click on newly created group so all the users inside this group are listed

### Expected behaviour
All users belonging to that group should have been listed in web interface.

### Actual behaviour
Group is empty if I look it up over web interface. If I list users over terminal, all users are listed correctly.

### Server configuration
**Operating system**:
Ubuntu 16.04 LTS

**Web server:**
apache

**Database:**
MySQL

**PHP version:**
PHP 7.0.30-0ubuntu0.16.04.1

**ownCloud version:** (see ownCloud admin page)
10.0.9 (error also in 10.0.8).
**Updated from an older ownCloud or fresh install:**
Updated

**Where did you install ownCloud from:**
http://download.owncloud.org/download/repositories/stable/xUbuntu_16.04/

**Signing status (ownCloud 9.0 and above):**
no errors

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No errors have been found.

**The content of config/config.php:**
{
    "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "192.168.1.250"
        ],
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "datadirectory": "\/var\/owncloud_data",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "10.0.8.5",
        "dbname": "oc",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "loglevel": 2,
        "maintenance": false
    }
}

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```
**List of activated apps:**
  - activity: 2.3.6
  - audioplayer: 2.3.0
  - calendar: 1.5.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.3.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - impersonate: 0.2.0
  - market: 0.2.4
  - notifications: 0.3.3
  - onlyoffice: 1.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.3
  - twofactor_totp: 0.4.4
  - updatenotification: 0.2.1
  - user_ldap: 0.11.0

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Tested on multiple ownCloud servers (only internal users and LDAP) - not working on either

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Tested on Chrome, Firefox, IE (all latest version)

**Operating system:**
Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
No log recorded for the time of testing (log set to warning, errors and fatal issues)
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/9764 (special characters), https://github.com/owncloud/core/issues/25690 (Empty web interface), https://github.com/owncloud/core/issues/11454 (groups disappear in the Web interface), https://github.com/owncloud/core/issues/28265 (Hi,), and https://github.com/owncloud/core/issues/29158 (Dear Support, ).

**Comment by karakayasemi** [comment]
Everything is working as expected in 10.3.0. I tested with group name having 2 spaces in both occ and web UI.
