### ISSUE TITLE
create UI tests that check public links with long link names & filenames

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#32760]
we need tests that check if long link names are correctly refused and also some that check if long filenames/foldernames can be used for public links

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/pull/29991 (UI test for creating a folder with existing name), and https://github.com/owncloud/core/pull/32726 (UI test for public share with password).

**Comment by phil-davis** [comment]
We can also add API tests for the sharing API. Should we have a separate issue for that?
