### ISSUE TITLE
Create API acceptance tests that check creating public and other shares with names that are short and long

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32763]
Similar to the webUI tests created for issue #32760

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/31531 (Expand sharing API acceptance tests), https://github.com/owncloud/core/issues/31403 (Expand API acceptance tests), https://github.com/owncloud/core/pull/32734 (Acceptance test steps for public link share), https://github.com/owncloud/core/pull/32740 (Acceptance test steps for public link share), and https://github.com/owncloud/core/pull/31495 (Add API test for creating a public read-write share of a file).
