### ISSUE TITLE
UX usability problem with link share dialog

### ISSUE THREAD

**Issue by moscicki** [owncloud/core#32774]
We discussed it in part with @michaelstingl @labkode yesterday and decided to create a ticket here.

Since we moved to OC10 we started getting complains from users about usability problem with link share. Users are very much confused where to look for the generated URL and the entire process seems very unintuitive. The little clipboard icon is often overlooked and it seems to confuse many people.

![image](https://user-images.githubusercontent.com/621965/45807438-bff5c600-bcc3-11e8-807b-9d18d36bf448.png)

![image](https://user-images.githubusercontent.com/621965/45807551-fd5a5380-bcc3-11e8-95d2-255437794c80.png)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/18737 (share link problem), https://github.com/owncloud/core/issues/10531 (Problem with shared folders), https://github.com/owncloud/core/issues/18910 (Share Dialog Problems repeating user list), https://github.com/owncloud/core/issues/31454 (Problems with public shares), and https://github.com/owncloud/core/issues/19887 (formatTimeSpan usability problem - enhancement).

**Comment by PVince81** [comment]
I agree. Some proposal was to still have the link displayed somewhere or have a click on the link name issue a copy operation. Or have the public link name be a clickable link (anchor tag) with the actual URL inside.

cc @pmaier1 @felixheidecke

**Comment by pmaier1** [comment]
Solved in ownCloud Web.
