### ISSUE TITLE
Manual Upgrade Instructions

### ISSUE THREAD

**Issue by miqrogroove** [owncloud/core#32783]
There are a few problems that can be fixed in these instructions

https://doc.owncloud.org/server/10.0/admin_manual/maintenance/manual_upgrade.html

Under "Enable Maintenance Mode", the admin is instructed to stop the cron service.  At no point in the page is the admin instructed when or how to restart the cron service, leaving cron totally disabled.

Under "The Power User Upgrade", the file extraction step is so vague that it never mentions file ownership or permissions.  If the admin has extracted or copied the files as any user other than www-data, the remaining instructions on this page will cause file access errors.  A good improvement here would be a link to https://doc.owncloud.org/server/10.0/admin_manual/maintenance/update.html#set-updating-permissions-label

Under "Copy Old Apps", the instructions are unnecessarily vague about "3rd party applications".  Which apps are 3rd party?  Which are not?  For example, an earlier section explicitly shows how to disable the activity, files_pdfviewer, files_texteditor, and gallery apps.  However, following all the instructions on the page results in a new /owncloud/ directory where these apps are missing, and it is not clear why these apps should be manually copied from /owncloud-old/.  I think this just needs to be explained better.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/15493 (Manual upgrade ), https://github.com/owncloud/core/issues/25348 (Owncloud non-functional with "illegal instruction" errors, post-upgrade), https://github.com/owncloud/core/issues/18864 (Support/Upgrade timeline), https://github.com/owncloud/core/issues/28236 (Upgrade failed), and https://github.com/owncloud/core/issues/21407 (occ upgrade from console).

**Comment by mmattel** [comment]
@miqrogroove This is a documentation issue not a core issue.
Please open this issue in the ``docs``repro, many Thanks

@voroyam @settermjd
