### ISSUE TITLE
Issue upgrading from 9.1.8 to 10.0.10

### ISSUE THREAD

**Issue by gert28** [owncloud/core#32801]
### Steps to reproduce
1. Running instance of oc v 9.1.8
2. download and unzip code for 10.0.10
3. put the oc instance to maint mode
4. Running the upgrade process (sudo -u www-data ./occ upgrade)
   The upgrade process is not throwing any errors
5. taking it out of mainetance

### Expected behaviour
All info about shared folders should still be there

### Actual behaviour
Own folders are visible but folders that are shared with you (by someone else) are not visible anymore. Folders that you share with someone are not shown as shared.

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache 2.4.10

**Database:** MySQL 5.5

**PHP version:** php 7.1

**ownCloud version:** (see ownCloud admin page) 9.1.8

**Updated from an older ownCloud or fresh install:** updated from older/existing

**Where did you install ownCloud from:** the tarball from the website

**Signing status (ownCloud 9.0 and above):** ?

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No errors have been found.

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocy4jhat047j",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/localhost\/owncloud",
        "dbtype": "mysql",
        "version": "10.0.10.4",
        "dbname": "OwnCloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Paris",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "installed": true,
        "skeletondirectory": "\/homelocal\/adm\/OA_owncloud\/skeleton",
        "enable_previews": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "NTLM",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "default_language": "en",
        "enable_avatars": true,
        "allow_user_to_change_display_name": false,
        "session_lifetime": 3600,
        "theme": "",
        "loglevel": 3,
        "trashbin_retention_obligation": "auto",
        "singleuser": false
    }

config report attached

**List of activated apps:**
Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.5
  - notifications: 0.3.5
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:** Chrome and Edge

**Operating system:** Windows 7 and Windows 10

#### Web server error log
not showing any errors
#### ownCloud log (data/owncloud.log)

Periodically message like these.

{"reqId":"NkFU5YsgTKXZc8A7kw9T","level":3,"time":"2018-09-22T08:11:23+02:00","remoteAddr":"10.0.21.101","user":"--","app":"files","method":"GET","url":"\/owncloud\/cron.php","message":"Exception: {\"Exception\":\"OC\\\\ForbiddenException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud-10.0.10\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(139): OC\\\\Files\\\\Utils\\\\Scanner->shouldScan(Object(OC\\\\Files\\\\Mount\\\\MountPoint))\\n#1 \\\/var\\\/www\\\/owncloud-10.0.10\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/var\\\/www\\\/owncloud-10.0.10\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/var\\\/www\\\/owncloud-10.0.10\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(57): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/var\\\/www\\\/owncloud-10.0.10\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/var\\\/www\\\/owncloud-10.0.10\\\/cron.php(142): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud-10.0.10\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php\",\"Line\":192}"}
{"reqId":"NkFU5YsgTKXZc8A7kw9T","level":3,"time":"2018-09-22T08:11:23+02:00","remoteAddr":"10.0.21.101","user":"--","app":"files","method":"GET","url":"\/owncloud\/cron.php","message":"Exception: {\"Exception\":\"OC\\\\ForbiddenException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud-10.0.10\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(139): OC\\\\Files\\\\Utils\\\\Scanner->shouldScan(Object(OC\\\\Files\\\\Mount\\\\MountPoint))\\n#1 \\\/var\\\/www\\\/owncloud-10.0.10\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/var\\\/www\\\/owncloud-10.0.10\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/var\\\/www\\\/owncloud-10.0.10\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(57): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/var\\\/www\\\/owncloud-10.0.10\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/var\\\/www\\\/owncloud-10.0.10\\\/cron.php(142): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud-10.0.10\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php\",\"Line\":192}"}
{"reqId":"NkFU5YsgTKXZc8A7kw9T","level":3,"time":"2018-09-22T08:11:23+02:00","remoteAddr":"10.0.21.101","user":"--","app":"files","method":"GET","url":"\/owncloud\/cron.php","message":"Exception: {\"Exception\":\"OC\\\\ForbiddenException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud-10.0.10\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php(139): OC\\\\Files\\\\Utils\\\\Scanner->shouldScan(Object(OC\\\\Files\\\\Mount\\\\MountPoint))\\n#1 \\\/var\\\/www\\\/owncloud-10.0.10\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(87): OC\\\\Files\\\\Utils\\\\Scanner->backgroundScan('')\\n#2 \\\/var\\\/www\\\/owncloud-10.0.10\\\/apps\\\/files\\\/lib\\\/BackgroundJob\\\/ScanFiles.php(111): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->runScanner(Object(OC\\\\User\\\\User))\\n#3 \\\/var\\\/www\\\/owncloud-10.0.10\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(57): OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles->run(NULL)\\n#4 \\\/var\\\/www\\\/owncloud-10.0.10\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#5 \\\/var\\\/www\\\/owncloud-10.0.10\\\/cron.php(142): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud-10.0.10\\\/lib\\\/private\\\/Files\\\/Utils\\\/Scanner.php\",\"Line\":192}"}

#### Browser log
not applicable here

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/25096 (upgrade on Ubuntu 16.04 from 8.1 to 8.2 to 9.0 breaks oC with redirect loop, reinstall solves the problem), https://github.com/owncloud/core/issues/27778 (caldav/carddav syncing problem after upgrade to 10.0.0), https://github.com/owncloud/core/issues/21767 (issue), https://github.com/owncloud/core/issues/18162 (Encryption problem after upgrade from 8.0.x to 8.1), and https://github.com/owncloud/core/issues/23988 (upgrading from 8.1 to 9.0.1).

**Comment by gert28** [comment]
No, it was never solved. We had to redo the share info manually.

**Comment by mosesjohann** [comment]
Just made Update from 9.1.8 to 10.0.10 - all my share links stayed and working.
