### ISSUE TITLE
Problems with local storage with relative path

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32809]
### Steps to reproduce
1. create a folder inside the owncloud installation e.g. ``site/local_storage``
2. add the folder as external storage
```
php occ files_external:create local_storage local null::null -c datadir=site/local_storage
php occ files_external:option 179 enable_sharing true
```
(replace ``179`` with the storage id that you get in the first command)

3. make sure the files_trashbin app is enabled
4. create ``user1`` and login to the webUI as ``user``
5. try to drag-and-drop (move) a top-level file into the ``local_storage`` folder
### Expected behaviour
The file is moved into the ``local_storage`` folder,
### Actual behaviour
Message is displayed:
```
Could not move "textfile0.txt":
```
The file stays in the top-level folder.

### Steps to reproduce
6. on the webUI, navigate into the ``local_storage`` folder
7. create a text file, or upload a file
8. delete the file
9. click on "Deleted files"

### Expected behaviour
The file is in the trashbin
### Actual behaviour
The trashbin is empty

### Steps to reproduce
10. on the webUI, navigate into the ``local_storage`` folder
11. create a folder ``tmp``
12. create a text file, or upload a file, in the ``tmp`` folder
13. navigate up, and delete the ``tmp`` folder.
14. click on "Deleted files"

### Expected behaviour
The ``tmp`` folder is in the trashbin
### Actual behaviour
Message is displayed:
```
Error deleting file "tmp".
```
The folder is gone after refreshing the page (it has actually been deleted)

The trashbin is empty

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
PHP dev server
**Database:**
mySQL
**PHP version:**
7.2
**ownCloud version:** (see ownCloud admin page)
current git master

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/6653 (change data path from absolute to relative), https://github.com/owncloud/core/issues/10337 (Access local storage, respecting individual user access rights), https://github.com/owncloud/core/issues/6592 (Insufficient storage - different problem), https://github.com/owncloud/core/issues/26943 ([enhancement] Support user authentication for local storage), and https://github.com/owncloud/core/issues/25701 (Local Storage share).
