### ISSUE TITLE
OwnCloud Upgrade Issues 10.0.10

### ISSUE THREAD

**Issue by bchangia** [owncloud/core#32810]
### Steps to reproduce
1. https://mavpl.in/icloud
2. I did the update process and after it done it said to go to admin process and progress on the update but getting the error
3.

### Expected behaviour
It should update and give me login page

### Actual behaviour
its listing an error, which I"m totally unaware of

### Server configuration
Linux-litespeed

**Web server:**

**Database:** 
MySQL

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**
Update from older OwnCloud

**Where did you install ownCloud from:**
Softaculus

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => ''SENSETIVE'',
  'passwordsalt' => '17084767882670381897153376868820',
  'secret' => ''SENSETIVE'',
  'trusted_domains' => 
  array (
    0 => 'mavpl.in',
  ),
  'datadirectory' => ''SENSETIVE'
  'overwrite.cli.url' => 'https://mavpl.in/icloud',
  'dbtype' => 'mysql',
  'version' => '10.0.8.5',
  'dbname' => ''SENSETIVE'',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => ''SENSETIVE'8',
  'dbpassword' => ''SENSETIVE',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'info',
  'mail_domain' => ''SENSETIVE'',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => ''SENSETIVE'',
  'mail_smtpname' => ''SENSETIVE'',
  'mail_smtppassword' => ''SENSETIVE',
  'filelocking.enabled' => false,
  'mail_smtpport' => '587',
  'theme' => '',
  'loglevel' => 0,
  'maintenance' => false,
  'debug' => true,
  'updater.secret' => 'SENSETIVE',
);

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO
**Are you using encryption:** yes/no
NO
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'': SQLSTATE[HY000]: General error: 2006 MySQL server has gone away,

PLEASE HELP URGRENT

Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @kdslkdsaldsal.

Possibly related issues are https://github.com/owncloud/core/issues/21767 (issue), https://github.com/owncloud/core/issues/29761 (File download issue after upgrade to ownCloud 10.0.3 (stable)), https://github.com/owncloud/core/issues/15267 (UPGRADE ISSUE), https://github.com/owncloud/core/issues/28265 (Hi,), and https://github.com/owncloud/core/issues/29158 (Dear Support, ).

**Comment by bchangia** [comment]
ownclouder thank you for the feed back but the problem is 1 I'm not so technical person 2) I am on shared hosting have no command line access

**Comment by heyho1** [comment]
> General error: 2006 MySQL server has gone away,

Tried to throw this into google which should give plenty of hits? If you have a shared hosting then just open a ticket for the hosting support asking them to fix the MySQL configuration to allow continue operating ownCloud.

**Comment by bchangia** [comment]
so you mean is it like

> > General error: 2006 MySQL server has gone away,
> 
> Tried to throw this into google which should give plenty of hits? If you have a shared hosting then just open a ticket for the hosting support asking them to fix the MySQL configuration to allow continue operating ownCloud.

So is it like a timeout issue on MySQL configuration?

**Comment by heyho1** [comment]
One of the first hits on google as advised:

> The most common reason for the MySQL server has gone away error is that the server timed out and closed the connection. 
>
> https://dev.mysql.com/doc/refman/8.0/en/gone-away.html

**Comment by soydepr** [comment]
i recommend you block it from the outside world ASAP until you sort this out

**Comment by godzone** [comment]
Update failed against a Postgresql database.
2018-09-24T00:27:27+00:00 Updating database schema
2018-09-24T00:27:27+00:00 Updated database
2018-09-24T00:27:27+00:00 Updating <dav> ...
2018-09-24T00:27:27+00:00 Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_account_terms_id_seq"':

SQLSTATE[42703]: Undefined column: 7 ERROR:  column "min_value" does not exist
LINE 1: SELECT min_value, increment_by FROM "oc_account_terms_id_seq...
               ^
2018-09-24T00:27:27+00:00 Update failed
2018-09-24T00:27:27+00:00 Maintenance mode is kept active

**Comment by bchangia** [comment]
> Update failed against a Postgresql database.
> 2018-09-24T00:27:27+00:00 Updating database schema
> 2018-09-24T00:27:27+00:00 Updated database
> 2018-09-24T00:27:27+00:00 Updating ...
> 2018-09-24T00:27:27+00:00 Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT min_value, increment_by FROM "oc_account_terms_id_seq"':
> 
> SQLSTATE[42703]: Undefined column: 7 ERROR: column "min_value" does not exist
> LINE 1: SELECT min_value, increment_by FROM "oc_account_terms_id_seq...
> ^
> 2018-09-24T00:27:27+00:00 Update failed
> 2018-09-24T00:27:27+00:00 Maintenance mode is kept active

How did you get this information ?

**Comment by heyho1** [comment]
@godzone @bchangia Completely unrelated to the initial issue of @bchangia

@godzone Use the search function in this repository, you can't use PostgreSQL 10 with ownCloud: https://github.com/owncloud/core/issues/31424#issuecomment-388351691

**Comment by bchangia** [comment]
Owncloud, Through Softaculas or direct updates never work, sick and tired of it now. Even Manul update has the information about the command line not for shared hosting.

**Comment by godzone** [comment]
@mbalmers suggested fix to the query worked for me, the update has now completed anc OC is usable again.

**Comment by bchangia** [comment]
> @mbalmers suggested fix to the query worked for me, the update has now completed anc OC is usable again.

godzone if you see the message our both problems are different so don't mix the issues here please, i'm already very much confused right now deciding , something worng i've done , or its owncloud problem or server problem

**Comment by bchangia** [comment]
CAn someone help me where can update the followings?

**OWNCLOUD_CHUNK_SIZE** 

> is this in ownCloud Setup files or somewhere else?

**'dbdriveroptions' => array(PDO::MYSQL_ATTR_INIT_COMMAND => 'SET wait_timeout = 28800'),** 

> Where can this be updated? MySql INI or elsewhere?

**Comment by bchangia** [comment]
This is aboscored... horrible effort for a simple change which could have been instructed properly by the developers which is very bad in this community.

People on threads posted like owncloud.cfg file needs to be updated, where is this file?

Just a suggestion, please keep things simple so that everybody can understand and not only experts.

**I fixed it with simple code below on config.php file** 

```
  array (
    1012 => '/file/path/to/ca_cert.pem',
    1002 => 'SET wait_timeout = 88800',
  ),
```

**Comment by heyho1** [comment]
@bchangia Reading / browsing through the ownCloud documentation could help as well:

https://doc.owncloud.org/server/latest/admin_manual/configuration/database/linux_database_configuration.html#how-to-workaround-general-error-2006-mysql-server-has-gone-away

**Comment by bchangia** [comment]
Yes but the documentations all related to Server setup and MySQL db Setup, and Command line details. And me being on shared network all those information were useless for me.

**Comment by heyho1** [comment]
@bchangia Have you tried to click on this link? Your used solution to edit the config.php is exactly explained in there without even mention command line details and similar.

**Comment by godzone** [comment]
@bchangia: Sorry, didn't mean to pollute this thread.  I misread the title as 'issues' i.e. a collect-all for things going wrong with 10.0.0.10 upgrade not your specific problem.
