### ISSUE TITLE
Conflict file dialog let mark both options

### ISSUE THREAD

**Issue by davitol** [owncloud/core#32817]
Checked with oC 10.0.10

![dialogo](https://user-images.githubusercontent.com/10596560/45950468-36663100-c000-11e8-99e4-5ec60087ae55.gif)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/8056 (Conflicting Files), https://github.com/owncloud/core/issues/7961 (Conflict dialog is confusing), https://github.com/owncloud/core/issues/5094 (Conflict dialog layout), https://github.com/owncloud/core/issues/5764 (file upload conflict dialog - "Continue" without selecting any action), and https://github.com/owncloud/core/issues/29459 (Conflict dialog does not close properly any more).

**Comment by JammingBen** [comment]
Both options means the file will be appended with a number, as stated in the dialog window -> works as expected.
