### ISSUE TITLE
webUI scenario shareByPublicLink.feature:153 fails sometimes

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32823]
```
tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature:153
```
That scenario seems to fail sometimes. I guess there is some timing problem with the public link dialog. It needs looking into.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/28558 (sharing-v1.feature fails in master), https://github.com/owncloud/core/issues/28114 (Exporting Calendars sometimes failing), https://github.com/owncloud/core/issues/28956 (Integration test trashbin-old-endpoint.feature last scenario fails), https://github.com/owncloud/core/issues/28950 (Integration test sharing-v1.feature:962 fails), and https://github.com/owncloud/core/issues/30897 (webUI test suite webUISharingExternal failing on Travis).

**Comment by paurakhsharma** [comment]
I am reopening this because the drone again failed in this test scenario.
