### ISSUE TITLE
New "Username + Email" Feature causes trouble

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#32838]
In the central forum a few users opened tickets because they can't figure out why they can't create new users.

They get an "Invalid Mail Address" error.

I think what they are supposed to do is to configure their email server. But a new ownCloud user does not know that. All he can see is the Error Message without explanation. And his mail address is valid.

I made an afford and created a post explaining the situation.

https://central.owncloud.org/t/invalid-mail-address/15803/6

The placement and size of the gear wheel is no help to the issue.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/25684 (Email password recovery: Case-sensitive username), https://github.com/owncloud/core/issues/6250 (New feature request), https://github.com/owncloud/core/issues/4616 (typing username wrong creates new user), https://github.com/owncloud/core/issues/2725 (Feature proposal: Sharing via email-link + password: Add “wrong credentials” message ), and https://github.com/owncloud/core/issues/6348 ([New Feature] Notification Center).

**Comment by patrickjahns** [comment]
🤷‍♂️ - not sure what else to do besides writing announcements and release notes https://doc.owncloud.org/server/10.0/admin_manual/release_notes.html#new-local-user-creation-flow

Well maybe a quick youtube video showcasing the new feature would help to clarify

**Comment by heyho1** [comment]
>  not sure what else to do

Showing a meaningful message like "SMTP configuration invalid or missing" including a link to the documentation on how to configure the SMTP server instead of the current "Error Creating User: Invalid mail address" could improve the situation / workflow quite a lot.

**Comment by IljaN** [comment]
Disable the feature as long as SMTP is not configured?
