### ISSUE TITLE
webUI tests for "shared with you" and "shared with others"

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32846]
Add webUI tests that share some files/folders and then check that:

- [x] the files/folders are listed in "shared with you" for the share recipients
- [x] the files/folders are listed in "shared with others" for the user that shares the files/folders
- [ ] the actions menu items (details, rename, download, delete/unshare...) work

Note: there are already some tests for accepting shares, that mention ``in the shared-with-you page on the webUI``, so look at those as a starting point.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/pull/32772 (webUI search tests), and https://github.com/owncloud/core/issues/32845 (webUI tests for editing a public link share).

**Comment by phil-davis** [comment]
Closing - more webUI coverage is not happening
