### ISSUE TITLE
webUI test opening file and folder details

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32840]
Add webUI tests for opening the file/folder details panel with the "Details" file row menu selection:
- [x] On  the files page
- [x] On the favourites page

and check that basic items on the details panel are visible.

**Comment by phil-davis** [comment]
Note: we already have steps for checking, like:
```
		Then the thumbnail should be visible in the details panel
		And the "comments" details panel should be visible
```
so they will be useful.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/pull/32772 (webUI search tests), and https://github.com/owncloud/core/issues/32583 (Automated webUI tests for languages).
