### ISSUE TITLE
webUI test comments

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32842]
Add webUI tests for comments on files and folders:

- [x] adding a comment
- [x] viewing comments of yourself and other users
- [x] deleting comments

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/32643 (Review upload conflict webUI tests), and https://github.com/owncloud/core/pull/31718 (Improve webUI autocompletion acceptance tests).

**Comment by individual-it** [comment]
is this finished? closing?

**Comment by phil-davis** [comment]
I think so, but I am not in a place to look closely at the range of tests created.
@dpakach please check what tests were created and see if @individual-it is happy.

**Comment by dpakach** [comment]
@phil-davis @individual-it I think this issue has been covered in #32927
