### ISSUE TITLE
webUI tests for restricted collaborative tags

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32844]
Add webUI tests for "system" tags that are created by the admin and cannot be deleted/modified by users:

Test that:
- [ ] the tags can be added to files/folders
- [ ] the tags can be removed from files/folders
- [ ] the tags cannot be renamed
- [ ] the tags cannot be deleted completely from the system (by an ordinary user)

**Comment by phil-davis** [comment]
Note: probably the ``systemtags_management`` app is needed in order to create these type of tags.

So it needs investigation if these tests need to go in a test suite for that app, rather than in core.

**Comment by PVince81** [comment]
renamed to be more accurate

**Comment by phil-davis** [comment]
Closing - webUI tests are not being expanded.
