### ISSUE TITLE
webUI tests for tags search

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32848]
Add webUI tests that create some tags and tag some files, then check the "tags search":

- [ ] searching for a single tag shows the expected files
- [ ] searching for multiple tags show only the files that have all the tags

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/32843 (webUI test tags), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), and https://github.com/owncloud/core/pull/32772 (webUI search tests).
