### ISSUE TITLE
webUI test collaborative tags

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32843]
Add webUI tests for tags on files and folders:

- [x] add a new tag that does not exist
- [x] select and add a tag that already exists
- [ ] share the file/folder and verify that other users can see/edit the tags
- [x] delete tags #33032

**Comment by phil-davis** [comment]
ToDo: check if there are enough tests covering all the items.
@dpakach @skshetry ?

**Comment by PVince81** [comment]
renamed to be more accurate

**Comment by phil-davis** [comment]
Closing - webUI tests are not being expanded.
