### ISSUE TITLE
webUI  tests for "shared by link"

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32847]
Add webUI tests that public link share some files/folders and then check that:

- [x] the public link shares are listed in "shared by link"
- [ ] action menu items work (details, rename, download, delete)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/32845 (webUI tests for editing a public link share), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), and https://github.com/owncloud/core/pull/32772 (webUI search tests).

**Comment by phil-davis** [comment]
closing - not a priority to add more webUI tests
