### ISSUE TITLE
tests for external storage

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32849]
Add API tests that confirm that external storage is listed in the "All files" list and the "External storage" section for ordinary users.

- [x] files can be uploaded, downloaded, deleted, moved in/out of external storage
- [ ] the "External storage" section shows a filtered view with just the external storage folders

Note: this will need some thought about creating external storage within a scenario, and removing it at the end. Probably for the ordinary user tests, that is best done with the similar before/after scenario code that the API tests use.

**Comment by PVince81** [comment]
I don't think there is much value in testing file operations in the UI. Or maybe just test one like upload, just to make sure it actually lets you browse there.

Agreed on the second checkbox related to the section.

**Comment by skshetry** [comment]
As per https://github.com/owncloud/core/issues/32849#issuecomment-469260187, renaming `webUI` to `api`.
