### ISSUE TITLE
webUI tests for editing a public link share

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32845]
There are already tests for creating a public link share.
Add tests for editing a public link share.

- [x] changing link name
- [x] changing permissions (Download/View, Download/View/Upload, Upload only (File Drop) radio buttons)
- [x] changing password
- [x] changing expiration date (#34298 uses api to check expiration date)
- [x] make changes on the edit dialog, press cancel, the changes should not happen (#33590)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/32583 (Automated webUI tests for languages), and https://github.com/owncloud/core/pull/32772 (webUI search tests).

**Comment by skshetry** [comment]
Note: #34298 added check for expiration date through `api`. To travel forward and backward in time will be hard(as the server could be in remote and even database could be in different machines, so controlling time would be difficult). 

If we are happy with the current tests, we can close this issue.

**Comment by individual-it** [comment]
there are new permissions in public shares see https://github.com/owncloud/core/pull/34983
need to add tests for that

**Comment by skshetry** [comment]
@dpakach @phil-davis Close this?
