### ISSUE TITLE
webUI tests for admin general settings page

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32851]
Add webUI tests that check basic functionality of the admin general settings page, e.g.:

- [x] email server settings
- [x] imprint and privacy policy URLs
- [x] updater settings
- [x] cron selection
- [x] log level selection
- [x] system status information display

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/32583 (Automated webUI tests for languages), and https://github.com/owncloud/core/issues/32850 (webUI tests for personal general settings).

**Comment by paurakhsharma** [comment]
@phil-davis, It looks like we have checked most of the features here. So we close this now or do you think we can add more to this.
