### ISSUE TITLE
OC\RepairException: Upgrade is not possible 

### ISSUE THREAD

**Issue by woz2506** [owncloud/core#32854]
Advertencia de reparación:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Advertencia de reparación:Please install or update the following apps manually or disable them with: occ app:disable activity occ app:disable files_pdfviewer occ app:disable files_texteditor occ app:disable gallery occ app:disable templateeditor
Advertencia de reparación:For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps

Preparando la actualización
Establecer el nivel de registro a depuración
Modo mantenimiento activado
Advertencia de reparación:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Advertencia de reparación:Please install or update the following apps manually or disable them with: occ app:disable activity occ app:disable files_pdfviewer occ app:disable files_texteditor occ app:disable gallery occ app:disable templateeditor
Advertencia de reparación:For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps
OC\RepairException: Upgrade is not possible

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/27789 (OC RepairException: Upgrade is not possible (ver 10)), https://github.com/owncloud/core/issues/28370 (OC\Repair Exception: Upgrade is not possible), https://github.com/owncloud/core/issues/28806 (OC\RepairException: Upgrade is not possible), and https://github.com/owncloud/core/issues/29915 (OwnCloud 10.0.4 Upgrade Failure).

**Comment by heyho1** [comment]
@maofrancisco Isn't this message already telling you what to do including a link to the documentation with further info?

```
Advertencia de reparación:Please install or update the following apps manually or disable them with: occ app:disable activity occ app:disable files_pdfviewer occ app:disable files_texteditor occ app:disable gallery occ app:disable templateeditor
Advertencia de reparación:For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps
```

**Comment by woz2506** [comment]
Gracias Comunidad ya solvente el problema, la solución que le di fue crear una nueva base de datos desde cero, y con la nueva actualización ya tengo en el servicio funcionando.
