### ISSUE TITLE
tag acceptance test features/scenarios that require the files_sharing_app

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32865]
We want to be able to run acceptance tests against a system that has the files_sharing app disabled.

Tag the features/scenarios that require the files_sharing app, so we can easily include or exclude them.
```
files_sharing-app-required
```

See PR https://github.com/owncloud/core/pull/32864#issuecomment-424661927

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/pull/31516 (Acceptance test coding standard changes), and https://github.com/owncloud/core/pull/32351 (Standardize acceptance test skip tags).
