### ISSUE TITLE
GPG apt key expired for Ubuntu 14.04

### ISSUE THREAD

**Issue by mvl22** [owncloud/core#32870]
### Steps to reproduce
1. Using the following source:
`deb http://download.owncloud.org/download/repositories/9.0/Ubuntu_14.04/`

as documented on
https://download.owncloud.org/download/repositories/9.0/owncloud/

2. Running:
`apt-get update`

3. Produces:
`W: GPG error: http://download.owncloud.org  Release: The following signatures were invalid: KEYEXPIRED 1535163442 KEYEXPIRED 1535163442 KEYEXPIRED 1535163644 KEYEXPIRED 1535163442 KEYEXPIRED 1535163442 KEYEXPIRED 1535163442 KEYEXPIRED 1535163442 KEYEXPIRED 1535163644 KEYEXPIRED 1535163442`

### Expected behaviour
Expected apt to check for updates on repository.

### Actual behaviour
Update displayed key expired errors and did not update.

### Server configuration
**Operating system**: Ubuntu 14.04

**Comment by mvl22** [comment]
Workaround for now seems to be:

```
wget -nv https://download.owncloud.org/download/repositories/production/Debian_9.0/Release.key -O Release.key
apt-key add - < Release.key
apt-get update
```

as on https://github.com/owncloud/core/issues/32436#issuecomment-416941710

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/32543 (GPG apt key expired for Ubuntu 16.04), https://github.com/owncloud/core/issues/21531 (apt-get install owncloud fails on Ubuntu 14.04), https://github.com/owncloud/core/issues/27894 (apt-get package missing for latest Ubuntu 17.04 (Zesty)), https://github.com/owncloud/core/issues/21327 (ubuntu 14.04 server package missing /ocs-provider/), and https://github.com/owncloud/core/issues/20087 ([8.2][Ubuntu][14.04] Available?).

**Comment by heyho1** [comment]
@mvl22 Could be valid here for unsupported OS like Ubuntu 14.04 as well:

> https://github.com/owncloud/core/issues/32521#issuecomment-418362442
> @crrodriguez 
> OBS master key expired a week ago..supported repositories were fixed accordingly.. 9.x repositories are permanently frozen and locked..nothing there will be fixed, rebuilt or otherwise change.. you have to use the workaround suggested as this won't be fixed, you really have to upgrade to 10.x branch.
Cheers.

**Comment by mvl22** [comment]
How are people supposed to upgrade to 9.x or 10.x if they can't upgrade away from 8.0 or 8.1 to 8.2 to start with?

**Comment by heyho1** [comment]
@mvl22 I see two possibilities:

1. using the workaround you already found.

2. planning and doing the migration of a Software / OS before one or both components are reaching its EOL and not afterwards.

Could be possible that some one of the ownCloud people have a different opinion on this.
