### ISSUE TITLE
Make acceptance tests more flexible when testing a themed system

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32872]
Some acceptance tests are looking for particular values that are typical on the default image that we use in drone. e.g.

``status.feature`` - checks edition "Community" and product name "ownCloud"
``refuseAccess.feature`` - checks Basic realm="ownCloud"

re-factor these tests to make them more flexible, so they can "pass with best effort" when run on a themed system, or enterprise-licensed system.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/3209 (Theming), and https://github.com/owncloud/core/pull/32379 (Make more acceptance test methods public).

**Comment by phil-davis** [comment]
PR #33020 implements the tests learning the "product name" and expecting that, rather than hard-coded string "ownCloud".

**Comment by phil-davis** [comment]
To do:
- [ ] teach the tests to know if the system-under-test is "Community" or "Enterprise" edition, and use that as the expectation in the relevant capabilities and admin general settings... tests.
- [ ] sort out ``apiWebdavOperations/refuseAccess.feature`` where it expects header ``WWW-Authenticate`` containing ``Basic realm="ownCloud"`` - a literal ``ownCloud`` there might be trouble.

@patrickjahns please add any other items that you notice related to testing a system that has different theme/installation settings.

**Comment by phil-davis** [comment]
Done in:
master
https://github.com/owncloud/core/pull/33036

stable10 
https://github.com/owncloud/core/pull/33037
https://github.com/owncloud/core/pull/33049
