### ISSUE TITLE
Allow public link share default password to be passed to acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32871]
Currently the password used in public link share tests is hard-coded in each test scenario. We want to be able to run the tests against a system-under-test (SUT) that might have some password policy settings in place. We already made it possible to pass the admin password and user passwords in env variables to the acceptance tests. That allows the flexibility to pass password(s) that will work on the SUT.

Do similar for the password used for public link shares.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/31116 (Acceptance tests for lost password email), https://github.com/owncloud/core/pull/32740 (Acceptance test steps for public link share), https://github.com/owncloud/core/pull/32734 (Acceptance test steps for public link share), https://github.com/owncloud/core/issues/5840 (sharing link with password), and https://github.com/owncloud/core/issues/19632 (Forgotten Share Link Password).

**Comment by phil-davis** [comment]
PR #32873 implements this.
