### ISSUE TITLE
Lost password e-mail has invalid link when trying to login with e-mail address

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32889]
### Steps to reproduce
1. Try to login with your email address and a wrong password
2. Click on the lost password link.
3. An email is sent to you
4. Follow the link in the email to reset your password

### Expected behaviour
You are shown a page where you can successfully enter a new password.

### Actual behaviour
The link is invalid.

### Server configuration
**Operating system**:
Ubuntu 18.04

**Web server:**
Apache

**Database:**
mySQL

**PHP version:**
7.2

**ownCloud version:** (see ownCloud admin page)
Current git master or stable10 or 10.0.10

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/32868 (Lost password e-mail not sent when trying to login with e-mail address), https://github.com/owncloud/core/issues/16431 (Recover login password), https://github.com/owncloud/core/issues/25715 (E-mail login fails when two users have the same e-mail address), https://github.com/owncloud/core/issues/927 (Invalid default (& lost password) email sender address), and https://github.com/owncloud/core/issues/15509 (Feature Request - E-Mail with shared link should include set password).

**Comment by patrickjahns** [comment]
closed via https://github.com/owncloud/core/pull/35595
