### ISSUE TITLE
[FR] Stop reading file from disk if user cancelled download

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#32887]
A user in central raised an issue:

https://central.owncloud.org/t/owncloud-continues-reading-file-after-i-cancel-download/15842/5

# In summery 

Currently the code simply continues because it needs to clean up at the end after reading the file. A shortcut could be added to make it go directly to the cleanup code. (ex: cleanup of locks)

# Steps to reproduce

1. Install fresh owncloud
2. Upload a big file or map any unit with data inside the data file user folder
Try download
3. Cancel it at any point

# Expected behaviour
When you cancel a download at any point, server should stop reading the file, first of all because if you cancel the download of a 100G file for example, only when 1GB is downloaded, there is no need for the server to read the 99G left, and if you have a NFS storage as a external device or FTP or whatever, apart from giving disk io loads you are giving the server also network interface load, which makes no sense

# Actual behaviour
Once I cancelled a download at any point the server continues reading the files until it finishes

**Comment by DeepDiver1975** [comment]
We cannot detect if an upload was canceled. Detecting a download cancel can be possible if the client properly closes the connection. Technically possible. Effort to be estimated. Benefit to be estimated as well.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/29772 ([FR] Add creation date to user listing), https://github.com/owncloud/core/issues/11296 (cleanup sharing code, next round), https://github.com/owncloud/core/pull/28841 ([stable10] added better description for files:cleanup), https://github.com/owncloud/core/issues/11274 (More languages to cleanup), and https://github.com/owncloud/core/pull/30728 ([Stable10] cleanup drone).

**Comment by jvillafanez** [comment]
I think this requires changes in the sabreDAV library. As far as I know, ownClouds just gives an opened resource to the library, and it's the library the one copying the contents to the client.

I guess the easiest solution should be detect the disconnection in the sabreDAV library and close the opened resource, so the rest of the processing can keep going normally.
It should be around https://github.com/sabre-io/http/blob/master/lib/Sapi.php#L87-L109

**Comment by yevon** [comment]
How did this get fixed? Nextcloud has same problem and makes server to die.

**Comment by phil-davis** [comment]
I don't know if it did get fixed!
Now we have PR #40849 - that bumps `sabre/http` to https://github.com/sabre-io/http/releases/tag/5.1.7 which implement the fix done in PR https://github.com/sabre-io/http/pull/207

That should help/fix this issue.
