### ISSUE TITLE
[bug] Moving virtual filesystem file on desktop

### ISSUE THREAD

**Issue by greyskymedia** [owncloud/core#32899]
I demo'd ownCloud for a new client for whom we just set up a server. He asked an interesting question, can we move a virtual file system file to another folder, through the desktop app (windows, in this case). We tried it, it would put the file in the target directory, but once we cleared focus on the file it would disappear.

Is this a known bug and is this on the roadmap so the functionality will work in the future?

**Comment by heyho1** [comment]
AFAIK if you're looking for reporting an issue within the desktop sync client https://github.com/owncloud/client/issues should be a better place to report this.
