### ISSUE TITLE
Acceptance test TagsHelper assumes the password of sharer and sharee are the same

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#32912]
In ``tags.feature`` create ``user0`` and ``user1`` with different passwords.

Scenarios fail that receive a share from ``user0`` and try to add a tag to the shared file as ``user1``.

There is nothing wrong with ownCloud itself, just ``TagsHelper::tag`` uses the wrong user-password combination at one point.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/pull/32755 (Acceptance test steps that specify the password to be used), and https://github.com/owncloud/core/issues/31116 (Acceptance tests for lost password email).
