### ISSUE TITLE
WebDAV: Documents become folders on iOS Client

### ISSUE THREAD

**Issue by cruiseflight** [owncloud/core#32935]
This was reported first as https://central.owncloud.org/t/webdav-folder-sync-ios-readdle-documents-6-issue/10789.

My workaround was to keep using 9.1, which used to work just fine with all clients.

However, the [Desktop Client 2.5.0](https://owncloud.org/news/desktop-client-2-5-0-release-virtual-file-system/) now forces you to upgrade the server to 10.0, as it flags all older versions as unsupported and automatically pauses synchronization.

**The issue:** When synchronizing a folder on an iOS device with the Readdle Documents WebDAV client, all folders and files show up. In the first level of the synced folder, files are fine. But files in any sub-folder show up as empty folders, not documents. The document contents can never be accessed.

Say you sync this folder structure:
```
MyDocs/
image1.jpg
sub/
image2.jpg
```

Then `image1.jpg` would be ok, but `image2.jpg` would show up as an empty folder the name `image2.jpg`.

All other features, including owncloud desktop client sync, works fine. The same iOS device syncs files and folders from an 8.1.5 or 9.1.8 just fine.

### Steps to reproduce
1. Create a folder structure with subfolders.
2. Sync to Readdle Documents on iOS.
3. Check any document in a subfolder.

### Expected behaviour
Documents should be documents.

### Actual behaviour
Documents show up as empty folders.

### Server configuration
**Operating system**:
Ubuntu 16.04.5 LTS

**Web server:**
Apache 2.4.18-2ubuntu3.9

**Database:**
MariaDB 10.0.36-0ubuntu0.16.04.1

**PHP version:**
PHP 7.0.32-0ubuntu0.16.04.1

**ownCloud version:** (see ownCloud admin page)
ownCloud 10.0.10 (stable)

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
http://download.owncloud.org/download/repositories/production/Ubuntu_16.04/

**Signing status (ownCloud 9.0 and above):**
```No errors have been found.```

**The content of config/config.php:**
https://gist.github.com/cruiseflight/b767b09691931325f378ae8135c52c70

**List of activated apps:**

```
  - activity: 2.3.8
  - calendar: 1.6.0
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.4
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.9.0
  - files_sharing: 0.11.0
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.1.0
  - market: 0.2.5
  - notifications: 0.3.5
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.3.1
  - updatenotification: 0.2.1
  - user_ldap: 0.11.0
Disabled:
  - encryption
  - external
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
LUKS

### Browser Client configuration
**Browser:**
69.0.3497.81 (Official Build) Built on Ubuntu

**Operating system:**
Ubuntu 18.04

### iOS Client configuration
**Client:**
[Readdle Documents](https://readdle.com/documents) 6.6.1.562

**Operating system:**
iOS 11.4

#### Web server error log
no errors were logged when syncing the folder

#### ownCloud log (data/owncloud.log)
no entries were logged when syncing the folder

#### Browser log
no issue with the browser

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/3008 (Problems with iFile iOS webdav client), https://github.com/owncloud/core/issues/8322 (WebDAV permission attributes for desktop client), https://github.com/owncloud/core/issues/3379 (FEATURE:  Move Files in IOS client), https://github.com/owncloud/core/issues/4463 (Webdav display issue / possible client resync / encryption issue?), and https://github.com/owncloud/core/issues/16756 (Prevent WebDAV delete of user's files folder).
