### ISSUE TITLE
API test where user sends HTTP method with body doesn't work as expected

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/core#32955]
# Description
In the API provisioning tests. Where the statement that say: 
`When /^user "([^"]*)" sends HTTP method "([^"]*)" to OCS API endpoint "([^"]*)" with body`
Dosen't seem to be sending the whole body of the `TableNode` but only the last `key` `value` pairs. 

For e.g. in https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiProvisioning-v1/editUser.feature `feature 11`, its function defination only sends email key value paris. But neglates the quota key value pair.

**Comment by paurakhsharma** [comment]
@phil-davis @individual-it. Please have a look

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/pull/31387 ([Stable10] api test get user), and https://github.com/owncloud/core/issues/26201 (Session_lifetime not working as expected).

**Comment by phil-davis** [comment]
Now we are doing ``curl`` commands to the API endpoint and struggling to work out how to actually make changes to multiple user attributes in a single call. I feel like I have looked at this before - deja vu.

Maybe the API does not support it?

**Comment by paurakhsharma** [comment]
> Maybe the API does not support it?

Yes it seems that way. May be we can look into the routes of Provisioning Api.

**Comment by phil-davis** [comment]
@PVince81 @DeepDiver1975 

``apps/provisioning_api/lib/User.php`` ``editUser($parameters)`` - the code seems to only support sending a single key ``display``, ``quota``, ``email``,... in a single call.

But there are provisioning API  tests that look like they might have tried (without success) to change multiple user attributes in a single API call.

What is the requirement supposed to be?

**Comment by PVince81** [comment]
@phil-davis the provisioning API is rather old and not REST-y... so wouldn't be surprised if the expectation is that only a single key can be changed per call...

**Comment by phil-davis** [comment]
@paurakhsharma please have a look for any remaining acceptance tests that give the appearance of trying to change multiple keys in a single test step, and change them to be written as multiple separate test steps. That will avoid future misunderstanding.

Then we can close this. Provsioning API supports changing only 1 key-value pair per call.
