### ISSUE TITLE
New Password field not properly aligned

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/core#32969]
### Steps to reproduce
1.  create a new user
2. visit password setpage
3.

### Expected behaviour
Fields should look aligned - similar to the password reset field 

![image](https://user-images.githubusercontent.com/6403243/46349731-229b7a00-c653-11e8-948f-9e7278ea59f7.png)

### Actual behaviour
Fields do not look aligned

![image](https://user-images.githubusercontent.com/6403243/46349741-27602e00-c653-11e8-88ef-cfcb2b6477be.png)

### Server configuration
Docker `owncloud/server:10.0.10`

### Client configuration
**Browser:**
Chrome

**Operating system:**
MacOSX

### Logs
- not applicable

**Comment by paulandroshchuk** [comment]
reserved :)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/3609 (Can't focus password field when password field is visible), https://github.com/owncloud/core/pull/30981 (Add confirm password after new password), https://github.com/owncloud/core/issues/5469 (Missing password confirmation field), https://github.com/owncloud/core/issues/2051 (not able to paste with right click into password fields), and https://github.com/owncloud/core/pull/32590 ([stable10] Autocomplete off for password fields).

**Comment by sebastiaanspeck** [comment]
I’ll take a look today

**Comment by JanAckermann** [comment]
Fixed with #38506
