### ISSUE TITLE
Alfresco share mounted via webDAV as External Storage hides files in each new OCC Files:Scan

### ISSUE THREAD

**Issue by Leantricity** [owncloud/core#32974]
<!--
### Steps to reproduce
1. Add an Alfresco server as WebDAV (with username and password or session credentials I see the same issue)
2. Load some files in ownCloud and / or
3. Load some files in Alfresco in the shared space that is visible in ownCloud
4. Refresh ownCloud's page for the WebDAV to see content

### Expected behaviour
Files should show up in both places

### Actual behaviour
Files show up in Alfresco and ownCloud (if uploads are made from anyone of them) but as soon as a refresh is made in ownCloud, they only appear in Alfresco, and are gone from ownCloud. If I do an OCC files:scan --all -vv the count of files remain the same (it is not detecting the real files added to the webDAV share).

Files are correctly managed in Alfresco, they upload and stay there, but seem invisible for ownCloud-

### Server configuration
**Operating system**: 
Ubuntu 18.0.4 TLS

**Web server:** 
Apache/2.4.29 (Ubuntu) Server

**Database:** 
MySQL

**PHP version:** 
7.2

**ownCloud version:** 
version	10.0.10.4
versionstring	10.0.10
edition	Community

**Updated from an older ownCloud or fresh install:**
Fresh

**Where did you install ownCloud from:**
ownCloud downloads page in .tar format

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 

It says "No errors have been found" ¿Should I create a file? I think not, please tell me if am I wrong


**The content of config/config.php:**

https://gist.github.com/Leantricity/d3e5d2e7351ed9df67eac82f3126aecc#file-gistfile1-txt

**List of activated apps:**

They are in the Config report gist
**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
WebDAV


### Client configuration
**Browser:**
Safari or Chrome
**Operating system:**
Mac OS X
### Logs
#### Web server error log
```
[error.log](https://github.com/owncloud/core/files/2438755/error.log)

Insert your webserver log here

```
[access.log](https://github.com/owncloud/core/files/2438761/access.log)

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
[owncloud-20.log](https://github.com/owncloud/core/files/2438776/owncloud-20.log)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @PVince81, and @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/22595 (occ files:scan --all doesn't scan external storages), https://github.com/owncloud/core/issues/11522 (SMB External Storage - Newly Created Files And/or Folders Require OCC File Scan), https://github.com/owncloud/core/issues/16947 (Sharing files via link not working when sharing external storage files), https://github.com/owncloud/core/issues/4901 (share file as link on external storage fails), and https://github.com/owncloud/core/issues/3949 (File sharing).

**Comment by Leantricity** [comment]
I think the issues are more related to something about my configuration of ownCloud as I'm not an expert and just need to try Alfresco usage in ownCloud, or an Alfresco bug. I saw this related to Litmus not passing all the tests.

https://issues.alfresco.com/jira/browse/MNT-9939

Sorry if this is only something I'm doing wrong with ownCloud but I've installed it twice, and also found the same problems with an online OC instance that works flawlessly and was NOT installed by me :-)

**Comment by PVince81** [comment]
please use the issue template: https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

in general this should work with any Webdav compliant storage and we have automated tests that test against Apache mod_dav. so if Alfresco isn't compliant it is likely that it cannot be supported.
