### ISSUE TITLE
Missing translation for new function in useradministration

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/core#32999]
### Expected behaviour
Tell us what should happen
See all of the text in german on the useradminpage.
### Actual behaviour
Tell us what happens instead
I see all text in german except the new text with the new password in cog function.

### Server configuration
**ownCloud version:** (see ownCloud admin page)
10.0.10
**Updated from an older ownCloud or fresh install:**
updated from 10.0.9
**Where did you install ownCloud from:**
owncloud.org (zip)
**Signing status (ownCloud 9.0 and above):**

**Comment by phil-davis** [comment]
@DeepDiver1975 this might be related to the split out of user_management app from core master.
Maybe the translations are happening in the user_management app now, but need to be "backported" somehow to core stable10.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/55 (Missing translation), https://github.com/owncloud/core/issues/16690 (Missing 'New' button in shared folders), https://github.com/owncloud/core/issues/32224 (Missing DisplayName when creating new user), https://github.com/owncloud/core/issues/18992 (Missing shadow on "new" dropdown on all of Microsoft's browsers), and https://github.com/owncloud/core/issues/14730 (Translation of "share" in Webif missinG?).

**Comment by DeepDiver1975** [comment]
Still happening? Please reopen if so - THX
