### ISSUE TITLE
remove OC\Core\Command\Db\Migrations\GenerateCommand from release

### ISSUE THREAD

**Issue by butonic** [owncloud/core#33016]
OC\Core\Command\Db\Migrations\GenerateCommand can be removed from the tarball. Only used for development. Move it to a development app?

security scanners may be hiccuping on user provided input. just leaving it out saves us some hassle...

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/3260 (- Removed -), https://github.com/owncloud/core/issues/240 (--- Removed ---), https://github.com/owncloud/core/issues/15315 (  Problem of remove folder), https://github.com/owncloud/core/pull/32233 (remove broken symlink), and https://github.com/owncloud/core/pull/31888 (removed dead code).
