### ISSUE TITLE
Instance server eMail address issue

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#33018]
### Steps to reproduce
1. Setup a new instance from scratch, but do not set the admin-user eMail address
2. Define the servers eMail settings including sender address
3. Press ``Send eMail``

Server and admin-user eMail settings see screenshots below.

### Expected behaviour
The server eMail settings with the senders address set are sufficient and the server can send(test) eMails generated. 

### Actual behaviour
You need to define a user (admin) eMail address.
This is wired and makes no sense to define a users eMail address for sending an instance eMail ?
You also should NOT send an instance eMail with the admin-user eMail address as sender as this is/can be a security breach...
And, the instance sender eMail address can be totally different from the admin-user address.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.10.4 (stable)

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

![image](https://user-images.githubusercontent.com/3321281/46473513-b51d5400-c7e0-11e8-8f2a-68c70f9da435.png)

![image](https://user-images.githubusercontent.com/3321281/46473545-d8e09a00-c7e0-11e8-8169-597e58221a04.png)

**Comment by phil-davis** [comment]
The "From" address should be fixed if it is wrong.

What should be the "To" address for such a test email?
The system might have no users that have an email address defined.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/21767 (issue), https://github.com/owncloud/core/issues/5593 (Possibility to add email address in user management), https://github.com/owncloud/core/issues/927 (Invalid default (& lost password) email sender address), https://github.com/owncloud/core/issues/28436 (Admin Settings: Email From address takes any value), and https://github.com/owncloud/core/issues/6303 (lostpassword and email sharing address issue).

**Comment by mmattel** [comment]
This might explain it.

The from address is correct.
Regarding the To address, it seems that core "assumes" to send it to one in the users list without having that explicitly defined.

A question raises - if you have more than one user (or admins) defined - to whom does it send the testmail to?

To fix that, we need a test eMail recipient which should be defined before the test button.
In no case, a test eMail should be sent to one of the users automatically as it does right now.

**Comment by mmattel** [comment]
If the last admin is deleted, like raised in #33097, no test email can be sent as the recipients address is currently linked (without notice) to an admin.

**Comment by JanAckermann** [comment]
@pmaier1 Do you know why the admin's email must be set?
