### ISSUE TITLE
Group Sharing Blacklist doesn't load on master

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/core#33030]
### Steps to reproduce
1. Install ownCloud from github, master branch
2. Create several groups
3. Go to the admin settings page, sharing section
4. Click on Group Sharing Blacklist
5. And see the selection loads forever

![image](https://user-images.githubusercontent.com/20378877/46530232-c8035780-c8b8-11e8-978e-5fc4294ab156.png)

### Expected behaviour
You should be able to see the list of created groups

### Actual behaviour
The selection loads forever

## Server configuration
Operating system: ubuntu 16.04

Web server: Apache/2.4.29

Database: mysql

PHP version: 7.0

ownCloud version: master

Updated from an older ownCloud or fresh install: fresh install

Where did you install ownCloud from: github

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @jvillafanez.

Possibly related issues are https://github.com/owncloud/core/issues/14094 (Tipsy does not close on shared folder), https://github.com/owncloud/core/issues/32722 (Group Sharing Blacklist does not block the shares for the users), https://github.com/owncloud/core/issues/16507 (Sharing to remote groups is not allowed), https://github.com/owncloud/core/issues/20022 (Cannot share with groups), and https://github.com/owncloud/core/issues/11295 (Sharing via group does not work in all cases).

**Comment by paurakhsharma** [comment]
This is similar to #31739. And yes it does work on stable10 #33029

**Comment by phil-davis** [comment]
Now that stable10 has been moved to be master, this is no longer an issue. Whatever was the problem in master is gone into oblivion in archive-master
