### ISSUE TITLE
Change user display name via provisioning API is inconsistent

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33039]
### Steps to reproduce
1. create user ``zzz``
2. retrieve  the information about user ``zzz`` using the provisioning API
```
curl http://admin:admin@172.17.0.1:8080/ocs/v1.php/cloud/users/zzz
```
A data item comes back called ``displayname``
3. try to modify the ``displayname``
```
curl -X PUT http://admin:admin@172.17.0.1:8080/ocs/v1.php/cloud/users/zzz -d key="displayname" -d value="Me"
```

### Expected behaviour
Success

### Actual behaviour
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message/>
 </meta>
 <data/>
</ocs>
```

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
development
**Database:**
mySQL
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
git master

**Comment by phil-davis** [comment]
The actual ``curl``` command that works is:
```
curl -X PUT http://admin:admin@172.17.0.1:8080/ocs/v1.php/cloud/users/zzz -d key="display" -d value="Me"
```

The key is called ``display``, not ``displayname``

The User Provisioning API documentation https://doc.owncloud.org/server/10.0/admin_manual/configuration/user/user_provisioning_api.html under "Edit User" mentions ``displayname``

I suggest that this be made consistent by adding the ability to specify the display name by using the ``displayname`` key or the ``display`` key.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/32960 (edit user settings change statements on Api provisioning), https://github.com/owncloud/core/issues/13139 (Provisioning api uses uniqid()), https://github.com/owncloud/core/issues/15242 (Add quota and display to the default creation of users in the provisioning API), https://github.com/owncloud/core/issues/27976 (No working PUT User-Provisioning API ), and https://github.com/owncloud/core/issues/20817 (UTF-8 support different on User Provisioning API function calls).
