### ISSUE TITLE
occ provisioning command acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33052]
Add acceptance tests to check that the various ``occ`` provisioning commands work:

- [x] user commands
  - [x] add #33053 
  - [x] delete
  - [x] disable
  - [x] enable
  - [ ] inactive (moved to issue #33293 )
  - [x] lastseen
  - [x] list
  - [x] list-groups
  - [x] modify
  - [x] report
  - [x] resetpassword
  - [x] setting
  - [ ] sync (moved to issue #33293 )

- [x] group commands
  - [x] add #33058 
  - [x] add-member #33058 
  - [x] delete #33078 
  - [x] list
  - [x] list-members
  - [x] remove-member

Part of main issue #33051

**Comment by paurakhsharma** [comment]
@phil-davis, I think the commands that are testable for now are tested here.
Because to test `inactive` we need to sort out how we should test timing related stuff.
And for `sync` we need external storages? I not sure about this.

**Comment by phil-davis** [comment]
Closing here.
See issue #33293 ffor the remaining small parts which are now in backlog.
