### ISSUE TITLE
occ app management command acceptance tests 

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33054]
Add acceptance tests to check that the various ``occ`` app management commands work:

- [x] app:check-code (#33600) To be Deprecated
- [x] app:disable
- [x] app:enable
- [x] app:getpath (#33614)
- [x] app:list

Part of main issue #33051

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/33051 (cli occ command acceptance tests), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), and https://github.com/owncloud/core/issues/33052 (occ provisioning command acceptance tests).

**Comment by skshetry** [comment]
Closing as most of it has been tested except `app:check-code` as it's going to be deprecated.
