### ISSUE TITLE
OCC command missing an option to make an user the subadmin of a group.

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/core#33064]
# Description
There is no option to make a user the subadmin of a group through `occ` command. Similarly, there is no command to remove subadmin from a group. 

We can use Provisioning API or webUI for this but, It would be handy to have this command in `occ`

**Comment by paurakhsharma** [comment]
@phil-davis

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/13709 ([provisioning_api] POSTing a request to make a user a subadmin of the same group fails), https://github.com/owncloud/core/issues/28311 (Provide occ commands to list users and groups), https://github.com/owncloud/core/issues/20629 (Commands for managing groups with occ.), https://github.com/owncloud/core/issues/31016 (subadmin should be able to remove users from the group), and https://github.com/owncloud/core/issues/20663 (command line occ add user group issue).
