### ISSUE TITLE
You can disable the last/only-one administrator using an occ command

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/core#33097]
# Description 
The last `administrator` or only-one `administrator` remaining in an ownCloud server can be disabled using an `occ` command.

Is this an expected behavior?
Actually, `administrato`r of the `system` has access to do whatever they like to do with the ownCloud server but should we allow them to disable themselves?
@phil-davis @individual-it

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/28085 (can't disable app with occ command), https://github.com/owncloud/core/issues/24494 (occ command to clear all locks), https://github.com/owncloud/core/issues/14229 (Ability to disable the upgrade page, forcing use of occ), https://github.com/owncloud/core/issues/23380 (Occ command not working), and https://github.com/owncloud/core/issues/22142 (occ upgrade notification before use of any occ command if the instance requires that).

**Comment by phil-davis** [comment]
@PVince81 @DeepDiver1975 If the system administrator disables the last ``admin`` user via the ``occ`` command, should that be prohibited?

Or I guess the system administrator might even want to do this. They can provision users and groups... from LDAP or with the ``occ`` commands. Maybe there is a use case where no ``admin`` account is needed.

**Comment by PVince81** [comment]
yeah, this could be a legitimate use case.

we often talk about separate roles for "system administrator" and "ownCloud administrator".

if the system administrator is taking care of provisioning using occ commands and/or LDAP, it might make sense to let them delete the "admin" group.

cc @pmaier1

**Comment by phil-davis** [comment]
> it might make sense to let them delete the "admin" group

well, at least let them delete the last user that is in the admin group, or remove all users from the admin group - which is the behaviour observed here.
