### ISSUE TITLE
Missing OCC command to set the quota of a user

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/core#33093]
# Description
OCC command is missing an command to set the quota of a user.

We can change the email, displayname of a user but there is no option to change the quota of a user.

**Comment by paurakhsharma** [comment]
@phil-davis

**Comment by phil-davis** [comment]
@DeepDiver1975 or anyone, can you give an example ``occ`` command?
Something like:
```
php occ user:modify quota 42MB
```

**Comment by phil-davis** [comment]
Duplicate - closing here.
