### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by vegagiancarlo** [owncloud/core#33113]
### Steps to reproduce
1. Install latest version on a Centos Server with cPanel and PHP v 7.0
2.Try to login

### Expected behaviour
Should be able to access the OwnCloud System

### Actual behaviour
Wont let you click or press on the icon to login 

### Server configuration
**Operating system**: CentOS

**Web server:** YES

**Database:** MySQL

**PHP version:** 7.0

**ownCloud version: 10.0.10

**Updated from an older ownCloud or fresh install:** Fresh Install

**Where did you install ownCloud from:** CentOS Server

**Signing status (ownCloud 9.0 and above):** Unable to pull

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '-',
  'passwordsalt' => '-',
  'secret' => '-',
  'trusted_domains' => 
  array (
    0 => '-',
  ),
  'datadirectory' => '/home/-/cloud/',
  'overwrite.cli.url' => 'https://t-/cloud',
  'dbtype' => 'mysql',
  'version' => '10.0.10.4',
  'dbname' => 'cloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'cloud',
  'dbpassword' => '-',
  'logtimezone' => 'UTC',
  'installed' => true,
);

**Are you using encryption:** yes/no

### Client configuration
**Browser:** CHROME/Firefox / EDGE

**Operating system:**  Win 10, Ubuntu

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/25588 (Unable to login using LDAP Credentials), https://github.com/owncloud/core/issues/17270 (Active Directory Users are unable to login and/or reset password), https://github.com/owncloud/core/issues/23123 (Unable to login via LDAP, exception OCP\PreConditionNotMetException), https://github.com/owncloud/core/issues/1782 (User with "." in there user name unable to login using LDAP), and https://github.com/owncloud/core/issues/24364 (Unable to login anyhow after update to v9).

**Comment by davitol** [comment]
@vegagiancarlo Did you were able to fix the issue? Do have more logs to provide as feedback? Thanks for reporting
