### ISSUE TITLE
Adding new subscribed calendar (with long url) in mac calendar gives error

### ISSUE THREAD

**Issue by mjollnir** [owncloud/core#33124]
### Steps to reproduce
1. Open latest version of Apple's calendar program
2. File -> New Calendar Subscription -> Paste URL -> click subscribe
3.  On the next popup, under "Location" choose the Caldav account -> hit ok.

### Expected behaviour
The new calendar subscription should be proliferated to the server

### Actual behaviour
The Server responded with an error:
The request for account “[[url redacted]]/remote.php/dav/principals/users/[[username redacted]]/” failed.

The server responded with
“500”
to operation CalDAVAddSubscriptionCalendarQueueableOperation.

### Server configuration
**Operating system**: Debian Stretch 9.4

**Web server:** Apache 2.4.25-3+deb9u4

**Database:** Postgres 9.6+181+deb9u1

**PHP version:** php7 7.0.27-0+deb9u1

**ownCloud version:** 10.0.10-1+1.1

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** deb http://download.owncloud.org/download/repositories/production/Debian_9.0/ /

**Signing status (ownCloud 9.0 and above):**

Just says "No errors have been found."

**The content of config/config.php:**
{
    "system": {
        "instanceid": "52e7a06400225",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "pgsql",
        "version": "10.0.10.4",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": "2",
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "fog.mjollnir.org"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": false,
        "trashbin_retention_obligation": "auto"
    }
}

**List of activated apps:**

Enabled:
  - calendar: 1.5.7
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.4
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.5
  - notes: 2.0.3
  - notifications: 0.3.5
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external

**Are you using external storage, if yes which one:** Just local disk

**Are you using encryption:** no (other than SSL?)

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Apple Calendar: 10.0 (2195.4.3).

**Operating system:**  Mac OS 10.13.6 

#### Web server error log

Nothing in apache's error log. But in access log, the following is generated:

2406:1e00:b410:100:f52e:b5b2:534c:8f4e - penny [10/Oct/2018:09:56:44 +0200] "MKCALENDAR /owncloud/remote.php/dav/calendars/penny/3B89407A-C7B0-4DE6-A9CD-2AA740069FBE/ HTTP/1.1" 500 2177 "-" "Mac+OS+X/10.13.6 (17G65) CalendarAgent/399.2.2"

#### ownCloud log (data/owncloud.log)
https://gist.github.com/mjollnir/2feb2a6c0660b98a6fa0415ee75447c4

#### Browser log
Just the error above in Apple's calendar.

NOTE: During the process of doing this, I see the error is that the subscription url is too long for the field in the db. And it's a blackbaud redirect anyway. So I followed the redirect and got the real url and added that as a subscription. That bit works. However, even having deleting the error-causing subscription from Apple Calendar, I'm still getting the error, presumably because it's queued somewhere.  I will continue to investigate.

However, I don't think 255 is long enough for subscription calendars, these things can be really long.

**Comment by mjollnir** [comment]
I managed to make the error going away by clearing the calendar cache. The shorter url has fixed it.  I would consider expanding the length of this db field in an upcoming release though. Thanks!

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/393 (Calendar sharing error), https://github.com/owncloud/core/issues/704 (Calendar sharing error), https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/28840 (-Error-), and https://github.com/owncloud/core/issues/24511 (After add a new Trusted DNS when I log in Give me error).

**Comment by PVince81** [comment]
@DeepDiver1975 FYI
