### ISSUE TITLE
occ log commands acceptance tests

### ISSUE THREAD

**Issue by davitol** [owncloud/core#33136]
Add acceptance tests to check that the various ``occ`` log commands work:

- [x] log commands
  - [x] manage https://github.com/owncloud/core/pull/33184 and  https://github.com/owncloud/core/pull/33156

  - [x] owncloud https://github.com/owncloud/core/pull/33208

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/33051 (cli occ command acceptance tests), https://github.com/owncloud/core/issues/24494 (occ command to clear all locks), https://github.com/owncloud/core/issues/33052 (occ provisioning command acceptance tests), https://github.com/owncloud/core/issues/22492 (test), and https://github.com/owncloud/core/issues/31579 (test).
