### ISSUE TITLE
Hook that triggers after upload has finished but before the file is visible to the user

### ISSUE THREAD

**Issue by IljaN** [owncloud/core#33143]
### Synopsis
Various apps need to do pre-checks on a uploaded file before it is available to the user and be able to either modify or read the file or prevent the final rename or move operation based on some condition.
### Problem
This functionality is currently achieved by different means in every app, sometimes in a very brittle way by regexing every request url and detect that a MOVE or PUT is done to a specific url (web-uploads/, uploads). This couples the implementation to the different upload routes. Other apps create their own dav-plugin which puts business logic in to the dav-layer.
### Solution
Provide a hook which is triggered before the file is visible to the user. The consuming event handler should:
- Have access to the uploaded file to read or modify it (Node, FileInfo)
- Be able to abort the operation with an HTTP-Statuscode
- Be able to to detect the final path
- The event should be typed (not GenericEvent) but still provide array access for backwards compatibility, maybe inherit from GenericEvent.

**Comment by IljaN** [comment]
As there are different upload-methods and routes (chunks, assembly, zsync) the best point to trigger this would be before the .part file is renamed. This however might be too late for some apps and needs further discussion.

Thoughts? @PVince81, @tomneedham, @VicDeo , @sharidas, @butonic

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/11778 (Bad Request AFTER any file finished uploading), https://github.com/owncloud/core/issues/6189 (Blacklisted and ignored files fail to upload with no explanation to the user about why), https://github.com/owncloud/core/issues/1373 (Uploading files issue), https://github.com/owncloud/core/issues/12928 ([Hook] add hooks about sharing files), and https://github.com/owncloud/core/issues/5328 (Public upload: After upload the delete action is visible).

**Comment by PVince81** [comment]
Would be good to analyze the current apps we know of and see for which this would be fitting and for which it would be too late and why.

Another challenge is finding a good name for the hook that clearly indicates that we're in the final stage but also that you can affect the behavior.

Regarding reading files: it would be expensive to re-read the full part file (ex: antivirus) as we already streamed through it in streamCopy so in cases where the full file needs to be read one could advise using a storage wrapper.

**Comment by PVince81** [comment]
also cc @jvillafanez
