### ISSUE TITLE
Folder/File with name "0" does not show up in SFTP

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#33155]
### Steps to reproduce
1. Connect to SFTP storage with ownCloud 10.0.10
2. Create a directory or file on storage level or in the web UI with the name "0"

### Expected behavior

new file/folder with name "0" shows up in the web UI

### Actual behavior

on the storage level the new file/folder gets created but does not show up in the web UI.

on the webUI the file/folder shows up, but disappears on refresh. 

Tried with WND: Folder with name "0" shows up in webUI, but when I try to create a file with just "0" an error message occurs telling me that the path is wrong. But the file get's created anyway.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22768 (FIles/folders with # in name don't sync over External Storage - SFTP (at least on Mac)), https://github.com/owncloud/core/issues/3400 (user name with . create file not folder!), https://github.com/owncloud/core/issues/28132 (Uploading same file twice to a public shared folder without listing doesn't show its real name.), https://github.com/owncloud/core/issues/24679 (Google Drive Folder doesn't show up after setting up external storage), and https://github.com/owncloud/core/issues/10269 ([7.0.1] Share folder -- files inside folder don't show as shared).
