### ISSUE TITLE
Confusing help message in occ command for default output format

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/core#33168]
# Description
The help message in occ commands has hardcoded text as `default is plain` for all occ command output which is not always the case. Also, there is an actual default output format right after this message which is  the actual command output format. 

![image](https://user-images.githubusercontent.com/20378877/46851272-b40aa900-ce16-11e8-8097-6a87d70cfb09.png)

So, the `default is plain` text is missleading and should be removed?

**Comment by paurakhsharma** [comment]
@phil-davis. We can remove the miss leading text from the help message?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/29959 (Update occ command help output), https://github.com/owncloud/core/issues/32438 (Confusing log message when creating a user (via occ)), https://github.com/owncloud/core/pull/29581 (Update the help output for the occ files:scan command), https://github.com/owncloud/core/issues/29580 (The help output for the occ files:scan command is inconsistent), and https://github.com/owncloud/core/issues/19593 (./occ command feature request - stat output on scanning).

**Comment by phil-davis** [comment]
Yes, I think so.
@PVince81 see PR #33169 - please review.
