### ISSUE TITLE
Wikipedia update

### ISSUE THREAD

**Issue by dilyanpalauzov** [owncloud/core#33164]
* Update the ownCloud line at https://en.wikipedia.org/wiki/Comparison_of_CalDAV_and_CardDAV_implementations#Server_implementations
* Create a list of supported protocols, like https://www.cyrusimap.org/imap/rfc-support.html

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/373 (Calendar To update), https://github.com/owncloud/core/issues/22362 (Problem instaling updates), https://github.com/owncloud/core/issues/19608 (Owncloud update issue), https://github.com/owncloud/core/issues/21366 (Update), and https://github.com/owncloud/core/issues/20661 (Update).

**Comment by PVince81** [comment]
indeed. from a recent PR I saw that we even support iTip ?

@DeepDiver1975

**Comment by dilyanpalauzov** [comment]
The tables can be extended significantly, like adding WWW-Authenticate: Negotiate for Kerberos 5 and spliting the precision to a part of a RFC.  I prefer if the current structure gets filled first, you can at your discretion extend the table yoirself.

To my understanding  iTIP/iMIP is handled in clients to convert an IMAP/SMTP/MIME message to a HTTP PUT request.

Please clarify, if you mean with server-side iTIP support something different.
