### ISSUE TITLE
"File Drop" Public Link Cancelling is Buggy

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#33177]
### Steps to reproduce
1. Create a **file drop public link** in oC 10.0.10
2. Upload files

### Expected behaviour

1."uploading" text at the top of the page should **disappear** after the process is finished.
2. hitting the "x" to cancel the upload has to **cancel the upload**

### Actual behaviour

1."uploading" text at the top of the page **stays** after the process is finished.
2. hitting the "x" to cancel the upload has **no effect**.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/20699 (Only allow creation of new files/folders on public link shares), https://github.com/owncloud/core/issues/3278 (files sharing link is sometimes wrong), https://github.com/owncloud/core/issues/29526 (Split "Enforce password protection" option for file drop and public links), https://github.com/owncloud/core/issues/22718 ('Files Drop' over PUT), and https://github.com/owncloud/core/pull/32773 (Test for accessing single file shared through public link).

**Comment by PVince81** [comment]
would be nice to post logs as required by the issue template https://raw.githubusercontent.com/owncloud/core/master/.github/issue_template.md

in this one case the JS browser logs.

most of the time when "nothing happens" in the web UI there is a red line in the browser log, either due to a request error or JS error

**Comment by andreasoc** [comment]
with chrome console i received this warning: 

**Deprecation warning: tipsy is deprecated. Use tooltip instead.**

**Comment by voroyam** [comment]
Same here, no futher info:

![image](https://user-images.githubusercontent.com/24212810/47852549-6f05e100-dddc-11e8-9152-a3dc3df276d3.png)

**Comment by labkode** [comment]
@PVince81 same here, with ownCloud 10.0.10.

You can reproduce it on demo.owncloud.org just uploading a file, the "Uploading..." text stays after upload has finished.
