### ISSUE TITLE
Review occ provisioning step text

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33174]
Some of the new acceptance tests for the ``occ`` provisioning commands (``user:add`` ``group:add`` etc) had step text copied over from the provisioning API tests, but not fully modified.

e.g.

```
When the administrator sends a group creation request for group "<group_id>" using the occ command
```

can be said better like:
```
When the administrator creates group "<group_id>" using the occ command
```

Review the gherkin step text.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/33081 (Occ test cli provisioning delete user), https://github.com/owncloud/core/pull/33101 (Occ test cli provisioning enable user), https://github.com/owncloud/core/pull/33094 (Occ test cli provisioning edit user), https://github.com/owncloud/core/pull/33116 (Occ test cli provisioning get apps), and https://github.com/owncloud/core/pull/33148 ([stable10] occ test cli provisioning get users).

**Comment by phil-davis** [comment]
Done in PR #33476
