### ISSUE TITLE
Postgres 10 support

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33187]
From https://github.com/owncloud/core/issues/29997.

- [ ] update to dbal v2.8 on master
- [ ] setup Drone target for Postgres 10
- [ ] fix all found issues, if any

**Comment by PVince81** [comment]
we already have the drone target https://github.com/owncloud/core/blob/master/.drone.yml#L622, closing

**Comment by gramakri** [comment]
@PVince81 Will Postgres 10 be supported in oc 10.1.0 or just oc 11? When can we expect oc 11 (I don't see a beta even).

**Comment by phil-davis** [comment]
Note: https://github.com/doctrine/dbal/releases/tag/v2.6.0
"PHP 7.1.0 is the minimum supported PHP version"

core `stable10` is dropping PHP 5.6 support, but for now keeps support for PHP 7.0. So `composer` in `stable10` finds `doctrine/dbal` `v2.5.13` - it can't yet use `doctrine/dbal` `v2.6.0` or above.

In particular, we can't get to `doctrine/dbal` `v2.8.0` in `stable10` just yet :(

**Comment by phil-davis** [comment]
Note: PR #31059 was also an essential part of Postgres 10 support.

**Comment by phil-davis** [comment]
Now that core `master` is the old core `stable10` we no longer have the PostgreSQL 10 support code sitting in core `master`. It is now waiting in PR #35962

PostgreSQL 10 needs minimum PHP 7.1. So getting this into a release is blocked until we can drop PHP  7.0.

Reopening the issue so it gains visibility again.

**Comment by phil-davis** [comment]
Code for this is in the commits waiting in #36289

**Comment by phil-davis** [comment]
PR #36498 runs the full test suite with postgres:10.3 as the database and passes.

**Comment by phil-davis** [comment]
PR #36290 was merged. This is now in master for release in 10.4
