### ISSUE TITLE
Command line undelete required for trashbin

### ISSUE THREAD

**Issue by xflowXen** [owncloud/core#33182]
Currently the trashbin command line only supports permanently deleting files via the trashbin:cleanup and trashbin:expire commands. In the event that an administrator wishes to restore files - it would be good to have a trashbin:restore option with the ability to restore files within some date range.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/12271 (OCS capabilities returns "undelete" even when trashbin is disabled), https://github.com/owncloud/core/issues/2588 (Undelete folder), https://github.com/owncloud/core/issues/22056 (command line only sync daemon), https://github.com/owncloud/core/issues/20663 (command line occ add user group issue), and https://github.com/owncloud/core/issues/21453 (occ failure during command line installation).

**Comment by xyGZen** [comment]
Nope - none of those issues are for this new functionality.

**Comment by PVince81** [comment]
what's the use case ? is this for users who do not know how to access the trashbin web UI ?

another possible approach is to use the [impersonate app](https://github.com/owncloud/impersonate) to login as such user and do the restoration from the web UI as that user

**Comment by PVince81** [comment]
cc @pmaier1

**Comment by xyGZen** [comment]
That could work - but then the web app would need to have the ability to choose a date range to restore. This would make it easier to restore a large number of deleted files - without having to select them all in the web interface.

**Comment by PVince81** [comment]
@xyGZen what's your use case ? in what situation do you need to restore files by date range as an admin ? is it because users do not understand the web UI enough, which might hint at UX problems in the web UI ? Is this something an admin does only once or needs to do in a regular manner ?

Understanding your exact use case could help thinking of a solution that better fits.

**Comment by PVince81** [comment]
makes sense, thanks a lot for clarifying

**Comment by PVince81** [comment]
the idea way I'd see a feature for restoring by date range would be if the search app could accept a query like "is:deleted dateMin:2018-10-01 dateMax:2018-10-31" and then let the user select all results and click "Restore". The query building part would also need to be user friendly.

**Comment by mmattel** [comment]
In case of a PR, docs relevant :smile:
