### ISSUE TITLE
Also log previous exception when given

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33204]
- [ ] add the previous exception in https://github.com/owncloud/core/blob/v10.0.10/remote.php#L68 and other locations in remote.php
- [ ] extend Log::logException to also log the first level of recursion of $exception->getPrevious(), also with sanitized args

This could help debugging errors that happen early in the initialization process related to DAV.
Normally I'd expect the exceptions to happen much later and have a better stack trace.

@DeepDiver1975 @butonic @tomneedham as discussed

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/32148 ([stable10] throw exception when json_decode of log fails), https://github.com/owncloud/core/pull/32147 (throw exception when json_decode of log fails), https://github.com/owncloud/core/pull/32623 (Log exception when background job class not found), https://github.com/owncloud/core/issues/17825 (Log errors (and/or throw Exceptions) when activity usage was wrong), and https://github.com/owncloud/core/issues/12586 (Properly log exceptions when using DAV storage).
