### ISSUE TITLE
[Virtual Filesystem] Add option on folder level for downloading and deleting files

### ISSUE THREAD

**Issue by DangerSchwob** [owncloud/core#33203]
Please add a option how the client handle files in different folders. 

The default currently is, download the file if the user download it and from than update the file also.

Please also add 2 other options that can be set on folder level:
1.) Always download files in this folder
2.) Temporary files, if the file is not used for X days or it is updated on the server, replace file with virtual file

**Comment by DangerSchwob** [comment]
Sorry, selected wrong repository. Should be in owncloud/client

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/27274 (delete), https://github.com/owncloud/core/issues/13824 (Delete File), https://github.com/owncloud/core/issues/23679 (Can't Delete Some Files and Folders), https://github.com/owncloud/core/issues/8932 (Syncs new local folder; deletes it, downloads it and then deletes it again), and https://github.com/owncloud/core/pull/30496 (Add API tests for restoring a file deleted from a folder).
