### ISSUE TITLE
Set master version to OC 11

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33205]
Currently the OC version on master is still 10.1.

Since we intend to switch stable10 to semver and use 10.1 there, we should switch master to OC 11 first.

Once we do, to get stable again with CI etc we need to, in order:
- [ ] allow CI to ignore max-version: https://github.com/owncloud/core/issues/31518
- [ ] adjust CI everywhere to ignore max-version
- [ ] set core master version to "OC 11.0.0"
- [ ] do a release of all apps with "max-version=11" and increase their minor version component at least (or major if needed)

Any concerns ? @owncloud/qa

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/9318 (Upgrade issue to current master (=OC7) from any previous OC version on postgres), https://github.com/owncloud/core/issues/27917 (Can't save any settings in OC 10), https://github.com/owncloud/core/issues/20819 (OC broken on master: Autoload not allowed), https://github.com/owncloud/core/pull/29824 (skip tests tagged with the current oC version), and https://github.com/owncloud/core/issues/14183 (OC 8.0: versions/restore issues).
