### ISSUE TITLE
Deleting Calendar Sharing

### ISSUE THREAD

**Issue by georgeoftown** [owncloud/core#33216]
### Steps to reproduce
1. Create a Group
2. Create a Calendar
3. Share calendar to a group
4. Update Owncloud (you need to update the dav app as well)

### Expected behaviour
Calendar still be shared
```
MariaDB [ownCloud]> select * from oc_dav_shares;
+----+-------------------------------+----------+--------+------------+-----------+
| id | principaluri                  | type     | access | resourceid | publicuri |
+----+-------------------------------+----------+--------+------------+-----------+
|  2 | principals/users/name.surname | calendar |      2 |      12397 | NULL      |
|  6 | principals/groups/group.prueba     | calendar |      2 |      12398 | NULL      |
+----+-------------------------------+----------+--------+------------+-----------+
```

### Actual behaviour
Delete calendar sharing 
```
MariaDB [ownCloud]> select * from oc_dav_shares;
+----+-------------------------------+----------+--------+------------+-----------+
| id | principaluri                  | type     | access | resourceid | publicuri |
+----+-------------------------------+----------+--------+------------+-----------+
|  2 | principals/users/name.surname | calendar |      2 |      12397 | NULL      |
+----+-------------------------------+----------+--------+------------+-----------+
```

### Server configuration
**Operating system:** 
Debian 9.5
**Web server:**
Apache/2.4.25
**Database:**
mysql  Ver 15.1 Distrib 10.1.26-MariaDB
**PHP version:**
PHP 7.0.30-0+deb9u1 
**ownCloud version:** (see ownCloud admin page)
10.0.10
**Updated from an older ownCloud or fresh install:**
4.5
**Where did you install ownCloud from:**
Repo
**Signing status (ownCloud 9.0 and above):**
Disabled

**Log of update (second line is problem)**

```
2018-10-17T01:22:23+00:00 Repair step: Remove invalid calendar and addressbook shares
2018-10-17T01:22:23+00:00 Repair info:  ... for principal 'principals/groups/group.prueba'
2018-10-17T01:22:23+00:00 Repair info:  ... for principal 'principals/users/XXX YYYY ZZZZZ'
2018-10-17T01:22:23+00:00 Repair info:  ... for principal 'principals/users/AAA BBBB CCCCCCC DDDD'
2018-10-17T01:22:23+00:00 Repair info:  ... for principal 'principals/users/GGGGG HHHHH IIIIII'
2018-10-17T01:22:23+00:00 Updated <dav> to 0.4.0
```

**Function that causes the problem**

file:  https://github.com/owncloud/core/blob/b71cc1c68969d20c1f6cfacf553a4e4d34c03d1e/apps/dav/lib/Repair/RemoveInvalidShares.php#L81

**Quick Patch**
add new line 81  

```
73     public function run(IOutput $output) {
74         $query = $this->connection->getQueryBuilder();
75         $result = $query->selectDistinct('principaluri')
76             ->from('dav_shares')
77             ->execute();
78
79         while ($row = $result->fetch()) {
80             $principaluri = $row['principaluri'];
81             if (!strncmp($principaluri,"principals/groups",17)) continue;
82             $p = $this->principalBackend->getPrincipalByPath($principaluri);
83             if ($p === null) {
84                 $output->info(" ... for principal '$principaluri'");
85                 $this->deleteSharesForPrincipal($principaluri);
86             }
87         }
88
89         $result->closeCursor();
90     }
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/165 (Delete or update share calendar ), https://github.com/owncloud/core/issues/27274 (delete), https://github.com/owncloud/core/issues/13813 (User can delete shared calendar), https://github.com/owncloud/core/issues/16877 (Shared calendar can be deleted also by shared user), and https://github.com/owncloud/core/issues/8561 (restoring deleted shares).

**Comment by DeepDiver1975** [comment]
Does the group exist? 

> principals/groups/group.prueba

**Comment by georgeoftown** [comment]
> Does the group exist?
> 
> > principals/groups/group.prueba

Yes, the group exist, and the calendar too(before and after), "only" delete the sharing

**Comment by DeepDiver1975** [comment]
Here is the fix: https://github.com/owncloud/core/pull/33245

**Comment by DeepDiver1975** [comment]
Will Close after backport

**Comment by DeepDiver1975** [comment]
Issue has been fixed - will be shipped with the next release.
