### ISSUE TITLE
Can't create directories on AWS S3 remote storage with AmazonS3FullAccess policy

### ISSUE THREAD

**Issue by gionn** [owncloud/core#33243]
### Steps to reproduce
1. Configure an S3 remote storage with credentials of a IAM user with AmazonS3FullAccess policy
2. Upload a file (works)
3. Create directory (won't work)

### Expected behaviour
Able to create directories after being able to create files

### Actual behaviour
401 response on MKCOL request, but if I switch to a root access key (insecure) directory creations works.

[Documentation](https://doc.owncloud.org/server/latest/admin_manual/configuration/files/external_storage/amazons3.html) don't state any requirements about required permissions.

### Server configuration
**Operating system**: Docker image
**ownCloud version**: 10.0.10

Thanks!

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/10803 (Cannot create data directory), https://github.com/owncloud/core/issues/30761 (OCC does not see S3 directory when created via AWS CLI), https://github.com/owncloud/core/issues/8326 (Can not delete folders which have been created on an external storage using S3), https://github.com/owncloud/core/issues/5945 (WebDAV ext storage creates weird "." directory), and https://github.com/owncloud/core/issues/15040 (can't create external storage (ftp)).

**Comment by mgaidia** [comment]
I have the same issue.
On the same owncloud instance, different buckets configured similarly bahe differently. 
Here is the log for a failed directory creation:
`{"reqId":"1FmlqZAHnKjz3T0tr7dO","level":3,"time":"2019-02-26T11:00:13+00:00","remoteAddr":"x.x.x.x","user":"xxxx","app":"files_external","method":"MKCOL","url":"\/remote.php\/webdav\/bucketname\/test-dir","message":"Exception: {\"Exception\":\"Aws\\\\S3\\\\Exception\\\\NotImplementedException\",\"Message\":\"A header you provided implies functionality that is not implemented\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Exception\\\/NamespaceExceptionFactory.php(76): Aws\\\\Common\\\\Exception\\\\NamespaceExceptionFactory->createException('Aws\\\\\\\\S3\\\\\\\\Exceptio...', Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest), Object(Guzzle\\\\Http\\\\Message\\\\Response), Array)\\n#1 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Exception\\\/ExceptionListener.php(55): Aws\\\\Common\\\\Exception\\\\NamespaceExceptionFactory->fromResponse(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest), Object(Guzzle\\\\Http\\\\Message\\\\Response))\\n#2 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(212): Aws\\\\Common\\\\Exception\\\\ExceptionListener->onRequestError(Object(Guzzle\\\\Common\\\\Event), 'request.error', Object(Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher))\\n#3 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(44): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->doDispatch(Array, 'request.error', Object(Guzzle\\\\Common\\\\Event))\\n#4 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(589): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->dispatch('request.error', Object(Guzzle\\\\Common\\\\Event))\\n#5 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(378): Guzzle\\\\Http\\\\Message\\\\Request->processResponse(Array)\\n#6 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/EntityEnclosingRequest.php(49): Guzzle\\\\Http\\\\Message\\\\Request->setState('complete', Array)\\n#7 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(286): Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest->setState('complete', Array)\\n#8 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(244): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->processResponse(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest), Object(Guzzle\\\\Http\\\\Curl\\\\CurlHandle), Array)\\n#9 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(227): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->processMessages()\\n#10 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(211): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->executeHandles()\\n#11 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(105): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->perform()\\n#12 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMultiProxy.php(91): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->send()\\n#13 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Client.php(282): Guzzle\\\\Http\\\\Curl\\\\CurlMultiProxy->send()\\n#14 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Client\\\/AbstractClient.php(262): Guzzle\\\\Http\\\\Client->send(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest))\\n#15 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(198): Aws\\\\Common\\\\Client\\\\AbstractClient->send(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest))\\n#16 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/RedirectPlugin.php(221): Guzzle\\\\Http\\\\Message\\\\Request->send()\\n#17 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/RedirectPlugin.php(82): Guzzle\\\\Http\\\\RedirectPlugin->sendRedirectRequest(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest), Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest), Object(Guzzle\\\\Http\\\\Message\\\\Response))\\n#18 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(212): Guzzle\\\\Http\\\\RedirectPlugin->onRequestSent(Object(Guzzle\\\\Common\\\\Event), 'request.sent', Object(Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher))\\n#19 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(44): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->doDispatch(Array, 'request.sent', Object(Guzzle\\\\Common\\\\Event))\\n#20 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(536): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->dispatch('request.sent', Object(Guzzle\\\\Common\\\\Event))\\n#21 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(577): Guzzle\\\\Http\\\\Message\\\\Request->dispatch('request.sent', Array)\\n#22 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/Request.php(378): Guzzle\\\\Http\\\\Message\\\\Request->processResponse(Array)\\n#23 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Message\\\/EntityEnclosingRequest.php(49): Guzzle\\\\Http\\\\Message\\\\Request->setState('complete', Array)\\n#24 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(286): Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest->setState('complete', Array)\\n#25 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(244): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->processResponse(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest), Object(Guzzle\\\\Http\\\\Curl\\\\CurlHandle), Array)\\n#26 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(227): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->processMessages()\\n#27 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(211): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->executeHandles()\\n#28 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMulti.php(105): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->perform()\\n#29 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Curl\\\/CurlMultiProxy.php(91): Guzzle\\\\Http\\\\Curl\\\\CurlMulti->send()\\n#30 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/guzzle\\\/http\\\/Guzzle\\\/Http\\\/Client.php(282): Guzzle\\\\Http\\\\Curl\\\\CurlMultiProxy->send()\\n#31 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Client\\\/AbstractClient.php(262): Guzzle\\\\Http\\\\Client->send(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest))\\n#32 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Client.php(136): Aws\\\\Common\\\\Client\\\\AbstractClient->send(Object(Guzzle\\\\Http\\\\Message\\\\EntityEnclosingRequest))\\n#33 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Command\\\/AbstractCommand.php(153): Guzzle\\\\Service\\\\Client->execute(Object(Aws\\\\S3\\\\Command\\\\S3Command))\\n#34 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Command\\\/AbstractCommand.php(189): Guzzle\\\\Service\\\\Command\\\\AbstractCommand->execute()\\n#35 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Guzzle\\\/Service\\\/Client.php(76): Guzzle\\\\Service\\\\Command\\\\AbstractCommand->getResult()\\n#36 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Client\\\/AbstractClient.php(107): Guzzle\\\\Service\\\\Client->__call('PutObject', Array)\\n#37 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/AmazonS3.php(192): Aws\\\\Common\\\\Client\\\\AbstractClient->__call('putObject', Array)\\n#38 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(77): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\AmazonS3->mkdir('test-dir')\\n#39 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/PermissionsMask.php(99): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->mkdir('test-dir')\\n#40 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(77): OC\\\\Files\\\\Storage\\\\Wrapper\\\\PermissionsMask->mkdir('test-dir')\\n#41 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(83): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->mkdir('test-dir')\\n#42 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(77): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->mkdir('test-dir')\\n#43 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(77): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->mkdir('test-dir')\\n#44 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(77): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->mkdir('test-dir')\\n#45 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/Files\\\/View.php(1185): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->mkdir('test-dir')\\n#46 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/Files\\\/View.php(274): OC\\\\Files\\\\View->basicOperation('mkdir', '\\\/bucketname...', Array)\\n#47 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(Array)\\n#48 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/private\\\/Files\\\/View.php(276): OC\\\\Files\\\\View->emittingCall(Object(Closure), Array, 'file', 'create')\\n#49 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(216): OC\\\\Files\\\\View->mkdir('\\\/bucketname...')\\n#50 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1209): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createDirectory('test-dir')\\n#51 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('bucketname...', Object(Sabre\\\\DAV\\\\MkCol))\\n#52 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#53 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#54 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#55 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#56 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#57 \\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/remote.php(165): require_once('\\\/opt\\\/bitnami\\\/ap...')\\n#58 {main}\",\"File\":\"\\\/opt\\\/bitnami\\\/apps\\\/owncloud\\\/htdocs\\\/apps\\\/files_external\\\/3rdparty\\\/aws-sdk-php\\\/Aws\\\/Common\\\/Exception\\\/NamespaceExceptionFactory.php\",\"Line\":91}"}`

The exact same operation works on another bucket in the same AWS region, configured similarly.
I tried with and without bucket encryption and it made no difference.
