### ISSUE TITLE
occ command to delete orphaned previews

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33240]
There are scenarios in which previews aren't deleted correctly:
- deleting an external storage under certain conditions: https://github.com/owncloud/core/issues/25033
- former bugs which did not properly clean previews, like https://github.com/owncloud/core/issues/32346

The command would clean up:
- orphaned previews for which the fileid doesn't exist any more
- version previews (stored in $fileId/$timestamp) for which there is no matching versions file
- gallery previews ?
- or delete all previews inconditionally

The command could ideally look as follows:
- `occ previews:cleanup --all`: cleans orphaned previews for all users
- `occ previews:cleanup $user`: cleans orphaned previews for user
- `occ previews:cleanup --delete-all`: cleans all previews inconditionally for all users

Note that in the future the previews could be deleted automatically using another mechanism https://github.com/owncloud/core/issues/25770.

Still, even after the introduction of said mechanism, the admin would still need to run such command at least once after migration to remove all older previews that had no links.

cc @DeepDiver1975 @mmattel @butonic

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/27274 (delete), https://github.com/owncloud/core/issues/24494 (occ command to clear all locks), https://github.com/owncloud/core/issues/16500 (mkdir is calling code that deletes previews), https://github.com/owncloud/core/pull/33081 (Occ test cli provisioning delete user), and https://github.com/owncloud/core/issues/20368 (Add occ command to add/change/delete ext storage configs).

**Comment by mmattel** [comment]
First of all 😄 👍  !

To make things more clear:

1. a preview which has a relationship to it´s origin set
2. a preview which does not have a relationship to it´s origin set (eg by current design)

I would like to know if condition 1 is implemented, and if yes where.
Condition 2. has as example "Gallery". Thumbs which are "free flying" without any relationship.

Depending on the answer the command cleaning up can be implemented.

For the long run, this would be a two step process, as deleting previews is a necessary step before implementing a fixed origin - preview relationship (however done).
