### ISSUE TITLE
Listing apps in settings is extremely slow

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#33248]
### Steps to reproduce
1. goto <url>settings/admin?sectionid=apps
2. wait, wait, wait
3. more or less the same on page reload

### Expected behaviour
Page should show results quickly

### Actual behaviour
It takes a (felt) unnatural long time to present the results.
Server is not under load more or less idle
(Issue was also present in the past, but now I getting annoyed from)

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.10 stable

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oct7bkicorxf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "abc",
            "def",
            "gih"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/abc",
        "dbtype": "mysql",
        "version": "10.0.10.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "filesystem_check_changes": 1,
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "maintenance": false,
        "theme": "",
        "preview_max_scale_factor": 1,
        "excluded_directories": [
            ".snapshot",
            "~snapshot"
        ],
        "upgrade.automatic-app-update": true,
        "quota_include_external_storage": false,
        "singleuser": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ]
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.8
  - audioplayer: 2.4.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_clipboard: 0.7.1
  - files_external: 0.7.1
  - files_external_dropbox: 1.0.1
  - files_external_ftp: 0.2.0
  - files_pdfviewer: 0.9.0
  - files_sharing: 0.11.0
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.1.0
  - guests: 0.5.0
  - market: 0.2.5
  - notifications: 0.3.5
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.3.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/sftp/dropbox

**Are you using encryption:** no

### Client configuration
**Browser:** Opera

**Operating system:** W10x64

#### Web server error log
```
Nothing relevant
```

#### ownCloud log (data/owncloud.log)
```
Nothing relevant
```

#### Browser log
The only thing I get is a couple of times:
```
Deprecation warning: tipsy is deprecated. Use tooltip instead.
```

**Comment by ChrisEdS** [comment]
I see this behavior also very often. @PVince81 any chance to find out what is the problem here?
Please give me a note when I can do some research.

**Comment by PVince81** [comment]
I wonder whether this page is still doing some queries to the marketplace / app store to find out whether apps have updates. In the past we used to have the "Install" button converted to "Update" whenever an app had an update. This feature already exists in the market app.

I can't think of other reasons why displaying the app list would be that slow.

You can try setting "has_internet_connection" to false in config.php and see if it's faster. If yes, this would partly confirm that the issue is related to network access.

**Comment by DeepDiver1975** [comment]
The app settings are only operating on locally installed apps.

In order to speed this up: use a memcache system - acpu is enough

**Comment by mmattel** [comment]
hmm, as you can see in my config, I am using REDIS already. Or do you mean something different ?

**Comment by PVince81** [comment]
Reproducible with 10.0.10 enterprise bundle (it has lots of apps) without cache.

I don't think it's ever been that slow before, could be a regression.

**Comment by sharidas** [comment]
I will update my observations in this comment. Below is my research/observation regarding the issue:

### Observation ###

The core problem behind delay or slowness is due to the integrity check at https://github.com/owncloud/core/blob/v10.0.10/lib/private/legacy/app.php#L845. 
- When this line is commented the apps are listed almost quickly. Just like how we navigate to other pages in the settings.

**Comment by PVince81** [comment]
@sharidas can you verify whether there is any kind of caching for the integrity check ?

**Comment by PVince81** [comment]
@sharidas please note that there is already a cache for the app list itself which only works with memcache or redis is configured: https://github.com/owncloud/core/blob/stable10/lib/private/App/AppManager.php#L107

maybe we could store the integrity check result, or rather the "approved" "level" in there as well ?

I do wonder where this memcachefactory is used as I didn't find any useful occurrences in the above class...

**Comment by PVince81** [comment]
@sharidas if there is already a mechanism with memcache I'd prefer we reuse that instead of adding yet another mechanism with oc_appconfig.

I wonder if that memcache thing still works considering that `memcacheFactory` seems to be unused in the AppManager ??

**Comment by sharidas** [comment]
@PVince81 For a moment I moved with oc_appconfig. Though I was not convinced myself. I will scrap my idea of introducing new mechanism. Will explore more with memcache and update my observations regarding the same.

**Comment by sharidas** [comment]
> 
> I wonder if that memcache thing still works considering that `memcacheFactory` seems to be unused in the AppManager ??

Even the memcache in https://github.com/owncloud/core/blob/stable10/lib/private/App/AppManager.php#L336 triggered lets say while enabling the app is traced to https://github.com/owncloud/core/blob/master/lib/private/Memcache/NullCache.php#L66
methods in NullCache are either returning true/false/null. I am not able to get what are we gaining here. Or is there a big picture that I am missing? Continuing my investigation...

**Comment by PVince81** [comment]
@sharidas you need to configure an actual cache, see https://doc.owncloud.org/server/10.0/admin_manual/configuration/server/caching_configuration.html#redis-label

Then it will instantiate `Memcache/Redis` instead of NullCache.

**Comment by sharidas** [comment]
@PVince81 Thanks for the pointer. 

We need to do something like :
- in the IntegrityChecker/Checker::verifyAppSignature() method
  - At the beginning of the method 
```
		$cacheVal = $this->cache->get($appId);
		if ($cacheVal !== null) {
			return $cacheVal;
		}
```
- in the `storeResults()` of Checker.php
   - If we add `$this->cache->set($scope, \json_encode($resultArray));`. Then during the first iteration when the apps are checked for their signature, the keys are stored. Later in the subsequent call to check the signature of the apps, its skipped. Because the keys are already stored.

For testing this I have appended changes to my config.php:
```
'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0.0,
    'dbindex' => 0,
  ),
  'memcached_servers' => [
          ['localhost', 11211],
  ],
```

**Comment by sharidas** [comment]
Created a PR here https://github.com/owncloud/core/pull/33936.

**Comment by sharidas** [comment]
I would like a review for https://github.com/owncloud/core/pull/33936 . There is also a query in the PR https://github.com/owncloud/core/pull/33936#issuecomment-448894730. @PVince81

**Comment by sharidas** [comment]
Original PR : https://github.com/owncloud/core/pull/33936
Backport PR: https://github.com/owncloud/core/pull/34584
