### ISSUE TITLE
Disallow enabling apps without min-version requirement

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33241]
Remember this:
![image](https://user-images.githubusercontent.com/277525/47253459-50563080-d453-11e8-884e-0effd650e01e.png)

It's time to implement it in OC 11.

@DeepDiver1975 @VicDeo

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/28070 (enable apps failed), https://github.com/owncloud/core/issues/12197 (Exception after enabling apps), https://github.com/owncloud/core/issues/591 (enable apps by default without option to disable), https://github.com/owncloud/core/issues/16092 (Apps disabled but cannot enable), and https://github.com/owncloud/core/issues/884 (Cannot enable/disable apps with Internet Explorer).

**Comment by PVince81** [comment]
we should reject apps that have no value for min-verison.

we could also do so for max-version.

@IljaN @DeepDiver1975 does the marketplace already reject such apps right now ?

**Comment by IljaN** [comment]
Yes it does
