### ISSUE TITLE
research if https://github.com/composer/ca-bundle can help us to keep the shipped ca bundle up to date ..

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#33254]
https://github.com/composer/ca-bundle

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/2 (ca), https://github.com/owncloud/core/issues/18862 (CA bundle chaos), https://github.com/owncloud/core/issues/27304 (Update shipped resources/config/ca-bundle.crt), https://github.com/owncloud/core/pull/31712 (Updating ca-bundle.crt), and https://github.com/owncloud/core/issues/20651 (https://github.com/owncloud/core/issues/18755 is still an issue).
