### ISSUE TITLE
occ provisioning command background commands

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/core#33261]
Add acceptance tests to check that the various ``occ`` background commands work:

- [x] background commands #33263 

Part of main issue #33051

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/pull/31617 (Add background:execute occ command for running cron jobs manually), https://github.com/owncloud/core/pull/33101 (Occ test cli provisioning enable user), https://github.com/owncloud/core/pull/24551 (occ commands to manage the job list), https://github.com/owncloud/core/issues/24494 (occ command to clear all locks), and https://github.com/owncloud/core/pull/33094 (Occ test cli provisioning edit user).

**Comment by phil-davis** [comment]
@paurakhsharma the PR to master is merged. Close this issue?
