### ISSUE TITLE
Reconsider transifex setup - at least for core repo

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#33273]
As of today translations are only synced between transifex and the core repo on master branch.

Since we are having a high change rate on stable10 branch and backporting translations is suboptimal, we should reconsider the setup:
1. Either sync master and stable10 branches with transifex (needs analysis how to organize this on transifex)
2. only sync stable10

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/14249 (modify and add translations to core without transifex), https://github.com/owncloud/core/issues/2490 (IIS Setup), https://github.com/owncloud/core/issues/5919 (Setup Error), https://github.com/owncloud/core/issues/9889 (Setup for Postgres), and https://github.com/owncloud/core/issues/25587 (Owncloud Core).

**Comment by DeepDiver1975** [comment]
master branch is used for releases since a long time now -> close
