### ISSUE TITLE
Cannot find image of installed apps resulting in an exception

### ISSUE THREAD

**Issue by mnivoliez** [owncloud/core#33270]
### Steps to reproduce
1. Open market
2. Install any app
3. Go back to "files" section

### Expected behaviour
Tell us what should happen
We should be able to see files and use apps installed through market.

### Actual behaviour
Tell us what happens instead
The page failed to load. It seems that, according to logs, owncloud cannot find the app image.
Tested with calendar and task app.

![Page failed to load](https://i.gyazo.com/68780c0a4edef45093254a5fe52caed4.jpg)

### Server configuration
**Operating system**:
Debian 8
**Web server:**
Nginx 1.14

**Database:**
mysql  Ver 14.14 Distrib 5.5.60, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 7.0.32-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.32-1~dotdeb+8.1, Copyright (c) 1999-2017, by Zend Technologies

**ownCloud version:** (see ownCloud admin page)
10.0.10.4

**Updated from an older ownCloud or fresh install:**
Update

**Where did you install ownCloud from:**
Debian package manager in accordance to the doc.

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No errors have been found.

**The content of config/config.php:**
[Config](https://gist.github.com/mnivoliez/ed2975d15dac97b906c212407ea3d66e#file-config_report-json)

**List of activated apps:**
None currently, I removed all since I can't access my files with any app activated

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome, Firefox
**Operating system:**
Windows, Linux
#### ownCloud log (data/owncloud.log)
[ownCloud log](https://gist.github.com/mnivoliez/ed2975d15dac97b906c212407ea3d66e#file-owncloud-log)

**Comment by DeepDiver1975** [comment]
@VicDeo we had some bugfix in the image locator in one of the last patch releases - right? Could that be related? THX

**Comment by mnivoliez** [comment]
Something interesting to note, I change apps and apps-external, along side with data, paths to /home/owncloud. Does the locator search from WebRoot? If yes, is webroot /var/www/owncloud?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/20568 (Files not installed?), https://github.com/owncloud/core/issues/4728 (OC6 prevent apps from being installed), https://github.com/owncloud/core/issues/14004 (App installer does not reflect installed apps.), https://github.com/owncloud/core/issues/5745 (avconv not found), and https://github.com/owncloud/core/issues/4256 (Images can't be downloaded).

**Comment by VicDeo** [comment]
ownCloud has no built-in proxy facilities, app directories  should be below web server root directory
`/home/owncloud/apps-external` doesn't look like a sibling of  `/var/www/owncloud`

**Comment by VicDeo** [comment]
@mnivoliez  Did you flush opcode cache / memcached after changing the configuration?

**Comment by VicDeo** [comment]
> Does the locator search from WebRoot? If yes, is webroot /var/www/owncloud?

In order not to be confused with terminology - OCWebroot is a directory where index.php is located.
by default  it is assumed that app directories are below OCWebroot. 


The following case:
1. Web server root is `/var/www`
2. OC webroot is `/var/www/owncloud`
3. appdir is in `/var/www/apps-external`
Is also supported, but needs a relative syntax for the 'url' key:
```
1 => 
      array (
        'path' => '/var/www/apps-external',
        'url' => '../apps-external',
        'writable' => 'true',
      ),
```

As for your case I think it's just a caching issue
