### ISSUE TITLE
occ provisioning command remaining acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33293]
Add acceptance tests to check that the various ``occ`` provisioning commands work:

- [x] user commands
  - [x] inactive https://github.com/owncloud/core/pull/36777
  - [x] sync https://github.com/owncloud/user_ldap/pull/497 https://github.com/owncloud/user_ldap/pull/506 https://github.com/owncloud/user_ldap/pull/508

Part of main issue #33051 

The other provisioning command tests are already done in issue #33052

**Comment by phil-davis** [comment]
Added to sprint backlog (which should get moved into the new sprint).
This should be easy enough to finish.

**Comment by phil-davis** [comment]
@HariBhandari07 did some user:sync tests, so I am closing this.

Also see issue #36597 - @kiranparajuli589 will look there to see what other tests are needed

**Comment by kiranparajuli589** [comment]
Different types of `user:sync` and `user:inactive` tests are added, so moving to TODO for now,
@phil-davis please check the log if we can close this!

**Comment by phil-davis** [comment]
Looks done to me.
