### ISSUE TITLE
Avatar change does not trigger client update

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#33304]
### Steps to reproduce
1. change the avatar
2. watch the client

### Expected behaviour
The client should change the avatar automatically

### Actual behaviour
The client must be ended and restarted so that the avatar change gets recognized

See also https://github.com/owncloud/client/issues/6795

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.0

**ownCloud version:** 10.0.10 (stable)

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/25993 (Avatar image resolving doesn't support case change in uid.), https://github.com/owncloud/core/issues/11420 (Can't change default avatar), https://github.com/owncloud/core/issues/20661 (Update), https://github.com/owncloud/core/issues/21366 (Update), and https://github.com/owncloud/core/issues/30415 (Disabling avatars doesn't stop looking for avatar folder).
