### ISSUE TITLE
Image Preview broken on public links, when not authed

### ISSUE THREAD

**Issue by madsi1m** [owncloud/core#33307]
### Steps to reproduce

Hi all, we are on 10.0.3 and noticed a little strangeness, not sure if it is us, or a bug, or a feature. ;)

When a user shares an image file via public link. The public link page shows the image and a download button below it, only if the user opening the public link is logged into owncloud.

Non-users do not get the image but do get the download button.

Looking at the html output both users are seeing the same html, it is just that the `/index.php/apps/files_sharing/ajax/publicpreview.php?x=2535&y=1154&a=true&file=IMG_9480.jpg&t=nVyWLwHVBv7r6CW&scalingup=0` doesn't generate an image. In fact doing a curl on the url shows a redirect to our login page.

Any ideas?

### Expected behaviour
Image preview to display on un-authed public link.

### Actual behaviour
Image preview url seems to be a redirect url to login screen, thus invalid image src for the <img> tag.

**Comment by ho4ho** [comment]
> 10.0.3

The issue template currently says the following:

> Before reporting any issues please make sure that you're using the latest available version for your major branch (e.g. 9.0.x), see https://owncloud.org/changelog/

which you could follow.

**Comment by madsi1m** [comment]
@davitol says this is fixed in 10.0.10
