### ISSUE TITLE
webUI Trashbin tests have intermittent timing issues

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33300]
Sometimes test scenarios in ``tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature`` fail because they do not yet see the file/s in the trashbin on the webUI.

Anyway, we also would like to check that a file/s deleted on the webUI do appear in the trashbin API (as well as on the trashbin page in the webUI.

Add extra steps to check that the files exist in the trashbin API.

Note: test fails happen more often with encryption enabled. There seems to be some more delay in the file/s becoming visible in the trashbin in this case - which is to be expected. This has been noticed in recent encryption app test runs.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/21767 (issue), and https://github.com/owncloud/core/pull/33257 (webUi test user setting language).

**Comment by phil-davis** [comment]
First PR merged. Leaving this open a few days to see if the nightly encryption CI test runs improve.

**Comment by individual-it** [comment]
@phil-davis does this still happen outside of the encryption app? If not we should close this, the encryption app has a separate issue https://github.com/owncloud/core/issues/33325

**Comment by phil-davis** [comment]
I have not seen this in core test runs for a while. Closing here.
