### ISSUE TITLE
Add version suffix support in core

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33315]
Required for Semver.

We need the ability to add a parseable string "dev1", "beta1", etc.

We currently have `$Version` (array) and `$VersionString` (string) in version.php. I think we should consolidate these into an actual version string and not an array.

Then in the version parsing code we extract it as array and cache it. (there was a cache somewhere).

- [ ] core version
    - [ ] consolidate version string in version.php
    - [ ] adjust release scripts
    - [ ] communicate this change, I'm pretty sure there are many scripts out there relying on this
    - [ ] need backport to stable10 and be careful that all works fine on upgrade
- [ ] app manager
    - [ ] make sure app manager properly parses and understands app versions, min-version, max-version containing suffixes

@DeepDiver1975 @VicDeo @phil-davis

**Comment by DeepDiver1975** [comment]
> We currently have `$Version` (array) and `$VersionString` (string) in version.php. I think we should consolidate these into an actual version string and not an array.

:+1:

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/79 (Add SVG support ), https://github.com/owncloud/core/issues/25373 (Add search support on the REPORT method), https://github.com/owncloud/core/issues/16309 (Add native support  for One time password [OTP]), https://github.com/owncloud/core/pull/30093 (Add support heic), and https://github.com/owncloud/core/issues/31622 (Add keeweb support).

**Comment by PVince81** [comment]
First attempt by @DeepDiver1975 in https://github.com/owncloud/core/pull/33361 shows that it would require many API changes as clients are requesting the ownCloud version and receive an array.

This means we can't backport suffix support to OC 10 as it would break APIs.

We need to evaluate whether we can still provide API additions and keep backward compatible in OC 10 without breaking the semantics. Not sure if possible as if the version is 10.2.3beta and the suffix is ignored by clients it would be evaluated as 10.2.3 stable.

**Comment by phil-davis** [comment]
I think we are stuck with a 4 part numeric for v10 like 10.0.10.4 10.1.0.5 etc. We can continue putting alpha beta rc in version string to indicate the release status, and that is no officially parsed anywhere for the purpose of triggering db migrations or app compatibility etc.

**Comment by PVince81** [comment]
let's do the suffix thing only for OC 11.

OC 10 will be Semver-ish with at least the minor/patch component differentiation without breaking APIs.

**Comment by PVince81** [comment]
- [ ] also add git-sha field ? (for app dailies)
