### ISSUE TITLE
In updateShare.feature check if actually intended action was done instead of only checking the status code

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/core#33323]
in tests/acceptance/features/apiSharing/updateShare.feature not only check the return codes but also if something useful happened (e.g. share is accessible)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/20528 (Add status code 200 to succeeded() check of OCS?), https://github.com/owncloud/core/issues/29340 (Code Integrity check), https://github.com/owncloud/core/issues/29339 (Code Integrity Check), https://github.com/owncloud/core/issues/19036 (Code Integrity Check), and https://github.com/owncloud/core/issues/25589 (After Upgrade Code integrity check fails).
