### ISSUE TITLE
a half-broken LDAP-configuration should give a meaningful error-message

### ISSUE THREAD

**Issue by EmilObermayr** [owncloud/core#33339]
### Steps to reproduce
1. use the app "LDAP Integration"
2. have two configurations
3. change one and forget to change the other one

### Expected behaviour
A meaningful error message about the broken part of the configuration

### Actual behaviour
just an "internal server error" when users try to connect

**List of activated apps:**

LDAP Integration 0.11.0

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/28840 (-Error-), https://github.com/owncloud/core/issues/13402 (... broken), https://github.com/owncloud/core/issues/13087 (Error messages), and https://github.com/owncloud/core/issues/29082 (a Error).
