### ISSUE TITLE
Unrelated step in updateShare.feature scenario

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/core#33332]
in tests/acceptance/features/apiSharing/updateShare.feature Increasing permissions is allowed for owner. why is the test scenario making that user a sub-admin?

**Comment by paurakhsharma** [comment]
After the inspection, that step is found to be unrelated to the given scenario.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/32823 (webUI scenario shareByPublicLink.feature:153 fails sometimes), https://github.com/owncloud/core/issues/28956 (Integration test trashbin-old-endpoint.feature last scenario fails), https://github.com/owncloud/core/issues/32865 (tag acceptance test features/scenarios that require the files_sharing_app), https://github.com/owncloud/core/issues/1744 (Feature: Send It), and https://github.com/owncloud/core/issues/12530 (Feature Request).
