### ISSUE TITLE
Merge sharees acceptance test files into single

### ISSUE THREAD

**Issue by dpakach** [owncloud/core#33350]
join tests/acceptance/features/apiSharees/sharees_provisioningapiv2.feature and tests/acceptance/features/apiSharees/sharees.feature

from master issue #32040

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/3273 (Sharing a single file), and https://github.com/owncloud/core/pull/32740 (Acceptance test steps for public link share).

**Comment by dpakach** [comment]
Stable10 backport on #33353
