### ISSUE TITLE
Merge feature files in api Trashbin acceptance test

### ISSUE THREAD

**Issue by dpakach** [owncloud/core#33354]
merge both features files in https://github.com/owncloud/core/tree/master/tests/acceptance/features/apiTrashbin into one file with Examples tables

Master issue  #32040

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/33336 (Merge trashbin api test files), https://github.com/owncloud/core/issues/32606 (Creating local_storage folder in API acceptance tests drone CI), https://github.com/owncloud/core/pull/30493 (Rename integration API tests to acceptance), https://github.com/owncloud/core/issues/31403 (Expand API acceptance tests), and https://github.com/owncloud/core/pull/30659 (Move acceptance test feature files to different folder structure).
