### ISSUE TITLE
UI tests for webdav locking frontend

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#33359]
need UI tests for  #32250

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/pull/32250 (Feature/webdav locking frontend), and https://github.com/owncloud/core/issues/29139 (Integration Tests: missing check in WebDav trait).

**Comment by individual-it** [comment]
tests added to https://github.com/owncloud/core/pull/32250
