### ISSUE TITLE
Split apiTrashbin features into multiple feature files

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33363]
Part of issue #32040 

- [x] split the ``trashbin.feature`` file in the ``apiTrashbin``  suite into multiple features, similar to the split already done in the ``webUITrashbin`` suite
- [x] write the "requirement" section for each feature ("As a user...")
- [x] put more steps into the background section, where possible

see PR #33365

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/33335 (merge both features files in apiTrashbin), https://github.com/owncloud/core/pull/32365 (Split webdav feature), https://github.com/owncloud/core/issues/11663 (Feature Request: allow sharing of multiple files/folders), https://github.com/owncloud/core/issues/6091 (Feature request: multiple accounts), and https://github.com/owncloud/core/pull/32367 ([stable10] Split webdav feature).
