### ISSUE TITLE
owncloud page error loading issue

### ISSUE THREAD

**Issue by iam9850810463** [owncloud/core#33362]
i have own hosting plan. i setup owncloud database with version 10.0.10 with php version 7.2. when i log in after name and password, every time it shows error "problem loading page, reloading in 5 seconds". i am sick of this error. every time it shows this error. another issue is i am new user. hence coding is diffcult for me. it shows security tips (screenshot 2.) is there any online remote support who solve or correct this ? If owncloud give support, plz inform me.
![screenshot 1](https://user-images.githubusercontent.com/44620570/47746115-69f54480-dcab-11e8-85f3-b748f44814f6.jpg)
![screenshot 2](https://user-images.githubusercontent.com/44620570/47746151-90b37b00-dcab-11e8-8ce9-91cc383597a9.jpg)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/28840 (-Error-), https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/31043 (Error load owncloud), https://github.com/owncloud/core/issues/6735 (Error while installing owncloud), and https://github.com/owncloud/core/issues/3261 (Owncloud errors).

**Comment by IljaN** [comment]
Please ask support questions here https://central.owncloud.org/ as this is a bugtracker and don't provide more detailed information such as logs and your install method. (Issue template)
