### ISSUE TITLE
Impossible saving option: sharing on user-mounted external storages

### ISSUE THREAD

**Issue by DurandRemi** [owncloud/core#33368]
I have local external storages on my owncloud.
I can rename and access to the files / repertories. But I can't sharing files with a public link, message: "Sharing is not allowed". The issue isn't here.

The problem is:
**Owncloud doesn't save "Allow sharing on user-mounted external storages"** 's option in the admin panel.

### Steps to reproduce
1. Connect to your web owncloud with a admin account
2. Go to Admin Storage
3. Clic on "Allow sharing on user-mounted external storages"
4. See green "saved" message
![image](https://user-images.githubusercontent.com/15911631/47783641-88872a00-dd03-11e8-836a-0fdce251e208.png)

5. Clic on Admin Security 
6. Go back to Admin Storage
7. Notice the issue: option disabled
![image](https://user-images.githubusercontent.com/15911631/47783744-d3a13d00-dd03-11e8-8a07-ac530bbe3fc9.png)

### Expected behaviour
Owncloud shows a success message & saves the option.

### Actual behaviour
Owncloud shows a success message.

### Server configuration
**Operating system**:
Debian 8 Jessie

**Web server:**
Nginx

**Database:**
MariaDB

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
10.0.10.4

**Updated from an older ownCloud or fresh install:**
Manual migration

### Client configuration
**Browser:**
Firefox 63.0

**Operating system:**
Windows 10

**Comment by DurandRemi** [comment]
Yes it's that, sorry for duplicate post.

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/issues/33878
