### ISSUE TITLE
Review acceptance test "sends HTTP method" steps

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33364]
In a lot of places in the acceptance tests there are steps that use the general form:
```
When user "userxyz" sends HTTP method "POST" to OCS API endpoint "/endpoint/something" with body
```

For example:
```
When user "brand-new-user" sends HTTP method "POST" to OCS API endpoint "/cloud/groups" with body
      | groupid | new-group |
```

In this example, the knowledge about the ``/cloud/groups`` endpoint is repeated in lots of test scenarios.

Replace these with specific functional steps, like:
``` 
When user "userxyz" creates group "new-group"
```

and let the functional step have the knowledge about the gory detail of the endpoint and how to access it.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/pull/32379 (Make more acceptance test methods public), and https://github.com/owncloud/core/pull/31516 (Acceptance test coding standard changes).

**Comment by phil-davis** [comment]
``master`` PR approved and merged. Needs backport.

**Comment by phil-davis** [comment]
Backport #33721 done and merged
