### ISSUE TITLE
Make combined steps in places where acceptance tests are "forced" to have repeated when-then-when-then sections

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33374]
In acceptance tests we do real actions that are the proper ``When`` steps for the test scenario. Then we check routine stuff like the HTTP status code and OCS status code.

Then we often want to check the "real" effect of the ``When`` actions - i.e. do not just believe the status codes. For that we want to be able to do things like:
- download a file and make verify its content
- upload a file and verify that "it works"
- query some status endpoint about the system, user, group, file... and verify it has some value(s)

In many cases we already have steps that do this kind of thing in a single ``Then`` step, in the style of:
```
Then user "user0" should be able to upload file "abc.txt"
Then for user "user0" file "abc.txt" should have content "qwerty"
Then group "grp1" should have the following members:
  | phil |
  | jim  |
```

But here is an example from an app where we got "forced" to write another separate ``When`` step:
```
    ...
    When user "user0" updates the last share using the sharing API with
      | expireDate | +60 days |
    Then the HTTP status code should be "<http-status>"
    And the OCS status code should be "<ocs-status>"
    When user "user0" gets the info of the last share using the sharing API
    Then the share fields of the last share should include
```

The last 2 steps could be combined into a single step like:
```
    Then the current share fields of the last share should include
```
which would retrieve the current share info and then check the field values.

- [ ] look for these sort of "missing" ``Then`` steps and implement them in core
- [ ] use them appropriately both in core and app acceptance tests

**Comment by phil-davis** [comment]
@individual-it thoughts? comments?

**Comment by paurakhsharma** [comment]
@phil-davis, This sounds like a good thing to do.
