### ISSUE TITLE
webDAV creates new file when trying to lock a non-existing file

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#33380]
### Steps to reproduce
1. create a lock on a non-existing file/folder e.g. `curl -u admin:admin -X LOCK http://localhost/owncloud-core/remote.php/dav/files/admin/not-existing -d '<?xml version="1.0" encoding="UTF-8"?> <d:lockinfo xmlns:d="DAV:"> <d:lockscope><d:shared/></d:lockscope></d:lockinfo>'`

### Expected behaviour
message replied that the file does not exists and cannot be locked

### Actual behaviour
new file with 0 bytes is created

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache2
**Database:**
SQLite
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
11.0.0 prealpha (git) 
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc4h10g96s3a",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-core",
        "dbtype": "sqlite3",
        "version": "11.0.0.0",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "htaccess.RewriteBase": "\/owncloud-core\/",
        "sharing.federation.allowHttpFallback": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "1025",
        "files_external_allow_create_new_local": "true",
        "skeletondirectory": "\/home\/artur\/www\/owncloud-core\/tests\/acceptance\/..\/..\/apps\/testing\/data\/webUISkeleton",
        "trusted_proxies": {
            "1": "127.0.0.1",
            "2": "192.168.0.104",
            "3": "172.17.0.1"
        },
        "csrf.disabled": true,
        "enable_previews": false,
        "installed": true
    }
}

```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - dav: 0.4.0
  - diagnostics: 0.1.3
  - enterprise_key: 0.1.4
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firewall: 2.6.0
  - notifications: 0.3.4
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - systemtags_management: 0.2.0
  - updatenotification: 0.2.1
Disabled:
  - brute_force_protection
  - files_antivirus
  - files_classifier
  - files_primary_s3
  - guests
  - multidirtest
  - oauth2
  - password_policy
  - search_elastic
  - testing
  - twofactor_totp
  - user_ldap
  - user_management
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
FF
**Operating system:**
Ubuntu
#### ownCloud log (data/owncloud.log)
```
{"reqId":"lN6GqyLKCDIyA90cWsQD","level":4,"time":"2018-11-01T04:34:59+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"LOCK","url":"\/owncloud-core\/remote.php\/dav\/files\/admin\/not-existing","message":""}
```

**Comment by individual-it** [comment]
CC @DeepDiver1975

**Comment by PVince81** [comment]
not too happy about this but it's in the spec... https://tools.ietf.org/html/rfc4918#section-9.10.4

> A successful LOCK method MUST result in the creation of an empty
   resource that is locked (and that is not a collection) when a
   resource did not previously exist at that URL.  Later on, the lock
   may go away but the empty resource remains.  Empty resources MUST
   then appear in PROPFIND responses including that URL in the response
   scope.  A server MUST respond successfully to a GET request to an
   empty resource, either by using a 204 No Content response, or by
   using 200 OK with a Content-Length header indicating zero length
