### ISSUE TITLE
Password reset confirmation email is not sent on occ command user:resetpassword

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/core#33384]
# Description
When the `administrator` resets the password of a user using the occ command with environment variable `OC_PASS` and set `--sent-email`. 
`sudo -E -u www-data ./occ user:resetpassword newuser --send-email --password-from-env`
As expected the password of the user is changed but the email is not sent to the user saying his/her email has been changed. 

Is this the expected behavior? 
@phil-davis, @individual-it

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/17869 (Can't reset password), https://github.com/owncloud/core/issues/10092 (User Password Reset), https://github.com/owncloud/core/pull/32569 (Expand occ user reset password email validation), https://github.com/owncloud/core/issues/21561 (Password reset is not sending emails), and https://github.com/owncloud/core/issues/9728 (Sending password reset eMail doesn't work).

**Comment by phil-davis** [comment]
@PVince81 I guess this is a bug?

@paurakhsharma do you already have an acceptance test scenario to demonstrate this?

**Comment by phil-davis** [comment]
Let's make an acceptance test scenario for this.

It is strange that if the sysadmin sets the password by typing it in, then the email is sent, but if the command gets it from the env variable then the email is not sent. I guess there will be some slightly different place in the code path that reads the env variable.
