### ISSUE TITLE
Language of internal sharing email notification should be in recipient language

### ISSUE THREAD

**Issue by plastikschnitzer** [owncloud/core#33397]
### Steps to reproduce
1. Share folder/file to another internal ownCloud user
2. Notify user by email

### Expected behaviour
The ownCloud user should get the notification email in his language

### Actual behaviour
The email is sent in the language from the user who shared the folder, but this not necessarily the language of the email recipient.

### Server configuration
**ownCloud version:** 10.0.10

**Updated from an older ownCloud or fresh install:** updated

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/7417 (Email Notification in Language), https://github.com/owncloud/core/issues/12608 (Shared file notifications), https://github.com/owncloud/core/issues/4499 (Shared File Notifications), https://github.com/owncloud/core/issues/5593 (Possibility to add email address in user management), and https://github.com/owncloud/core/issues/5719 (sending share email link fails).

**Comment by ho4ho** [comment]
Already possible since 10.0.10?

https://doc.owncloud.org/server/latest/admin_manual/release_notes.html#new-option-to-configure-the-language-of-mail-notifications-for-public-links

**Comment by plastikschnitzer** [comment]
The new feature in ownCloud 10.0.10 is for external shares, not for shares to an internal ownCloud user. 

If you share files/directories with an internal ownCloud user and send an email notification as mentioned above in my bug report, the email language is in the language of the owner, not the recipient.

**Comment by plastikschnitzer** [comment]
The release notes from 10.0.10 states that my desired behavior is the case for internal shares, but this is not the case, its broken. Please test my setup!

Maybe it was even broken with this new "set language for guest shares" feature because it sets the sharing email language by default to the owner language – for guest shares. Not sure if this causes the problem for internal shares, its just an idea how it could have happened.

**Comment by ho4ho** [comment]
Update the bug report to clarify this is about internal users?

**Comment by PVince81** [comment]
also observed recently as @mrow4a clicked "notify by mail" and I received the email in Polish while my user is set to English.

**Comment by pmaier1** [comment]
In contrast to external shares oC knows the language of internal share recipients. For other notifications (e.g. Pending Shares) the configured language of the recipient is used. That should be made consistent here.
