### ISSUE TITLE
Activity email notification German formal language not working

### ISSUE THREAD

**Issue by plastikschnitzer** [owncloud/core#33398]
### Steps to reproduce
1. Make personal settings send you emails about ownCloud activities (file shares, changes …)
2. Set ownCloud language to German formal

### Expected behaviour
The email being sent should be in German formal language ("Sie")

### Actual behaviour
The email being sent is in German informal language ("Du"). In some environments, this is _very_ unpolite.

I tested some other email notifications from ownCloud and they are correct, but not the activity email.

### Server configuration

**ownCloud version:** 10.0.10.4

**Updated from an older ownCloud or fresh install:** updated

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/19639 (Endless notification - Activity), https://github.com/owncloud/core/issues/20962 (No email notification), https://github.com/owncloud/core/issues/12255 (OC 7.0.3 Activity notification - mail notification does not work anymore), https://github.com/owncloud/core/issues/198 (Enhancement - Email notifications), and https://github.com/owncloud/core/pull/30613 (Email notifications stable10).

**Comment by plastikschnitzer** [comment]
Sorry for posting the issue in the wrong repo, should have been here: https://github.com/owncloud/activity
And its fixed in activity version 2.3.8 – thank you!
