### ISSUE TITLE
acceptance test step 'Given these users have been created'  always set a email address & display name

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#33396]
when not giving any email address or display name to the step `Given these users have been created:` and using one of the preconfigured users, they will still have an email address and display name.
That is confusing, because to create a user without an email address we need to know what are the default usernames and choose a username that is not one of them

**Comment by phil-davis** [comment]
Note: while fixing this, we need to make sure that:
```
Given user "user0" has been created
```
does still create ``user0`` with our internal default password, display name and email address.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/pull/32973 ([stable10] Add create user with email address to smoke test), and https://github.com/owncloud/core/pull/32667 (tests to create users by supplying and email address an no password - test infrastructure).

**Comment by individual-it** [comment]
- [ ]  rename `Given user "user0" has been created` to `Given user "user0" has been created with default attributes` - that step will create a user setting all default attributes. If the username is not in the magic users table - use the display name of `regularuser` and email address <username>@owncloud.org
- [ ]  rename `Given following users have been created` to `Given following users have been created with default attributes` - that step will create a user setting all default attributes. If the username is not in the magic users table - use the display name of `regularuser` and email address <username>@owncloud.org
- [ ]  create a new step `Given following users have been created` - this step does not set any setting that is not in the table

**Comment by skshetry** [comment]
Work in progress in #33551

**Comment by individual-it** [comment]
reopening again as the issue is not fixed. The problem is that `$displayName = $this->getDisplayNameForUser($user);` does return an displayName for any user that is in the magic table in `BasicStructure.php`  so then `$displayName` will not be `null` in https://github.com/owncloud/core/pull/33551/files#diff-ada499b0ff2965f80c91eeeaca2a85c4R1100
