### ISSUE TITLE
GDrive slow, when "Check for changes" is set to "Once every direct access"

### ISSUE THREAD

**Issue by micrie** [owncloud/core#33405]
Hello,
i've installed Owncloud 10.0.10 and enabled the GDrive Integration for using GDrive as backend.

Everything works fine and fast when the setting "Check for changes" is set to "Never". But then newly added files in GDrive don't appear in Owncloud. This happens a few days after installation. Absolutely nothing has changed.

If i change the setting to "Once every direct access", every access to GDrive in Owncloud is extremely slow and it took a few minutes until one folder opens in owncloud.

The linux server has nothing to do and memory is enough available.

I don't know, how to fix this problem.

Greetings,
Michael

Edit: What i tried or figured out:
1. The Drive API quota from google is not the problem.
2. Tried to "occ files:scan". Took about 1h but performance isn't getting better

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/24746 (Direct file access over url), https://github.com/owncloud/core/issues/5346 (Quota can be set to every string), https://github.com/owncloud/core/issues/3164 (Very slow access to shared folders), https://github.com/owncloud/core/pull/31367 (Do not set the password again if it hasn't changed), and https://github.com/owncloud/core/pull/32150 (Move "no-change" result below all the checks).
