### ISSUE TITLE
Seems like ownCloud tries to select from a database table before creating it

### ISSUE THREAD

**Issue by Julian1998** [owncloud/core#33408]
### Steps to reproduce
1. git clone core (master)
2. make
3. in my case: start php built-in webserver

### Expected behaviour
Webserver should start and owncloud UI should appear with install guide.

### Actual behaviour
[Sun Nov  4 15:59:21 2018] Exception: {"Exception":"Doctrine\\DBAL\\Exception\\TableNotFoundException","Message":"An exception occurred while executing 'SELECT * FROM \"oc_appconfig\"':\n\nSQLSTATE[HY000]: General error: 1 no such table: oc_appconfig","Code":0,"Trace":"#0 \/home\/julian\/dev\/php\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(184): Doctrine\\DBAL\\Driver\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/home\/julian\/dev\/php\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(158): Doctrine\\DBAL\\DBALException::wrapException(Object(Doctrine\\DBAL\\Driver\\PDOSqlite\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'An exception oc...')\n#2 \/home\/julian\/dev\/php\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(943): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOSqlite\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT * FROM \"...', Array)\n#3 \/home\/julian\/dev\/php\/core\/lib\/private\/DB\/Connection.php(187): Doctrine\\DBAL\\Connection->executeQuery('SELECT * FROM \"...', Array, Array, NULL)\n#4 \/home\/julian\/dev\/php\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php(219): OC\\DB\\Connection->executeQuery('SELECT * FROM \"...', Array, Array)\n#5 \/home\/julian\/dev\/php\/core\/lib\/private\/DB\/QueryBuilder\/QueryBuilder.php(141): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#6 \/home\/julian\/dev\/php\/core\/lib\/private\/AppConfig.php(301): OC\\DB\\QueryBuilder\\QueryBuilder->execute()\n#7 \/home\/julian\/dev\/php\/core\/lib\/private\/AppConfig.php(122): OC\\AppConfig->loadConfigValues()\n#8 \/home\/julian\/dev\/php\/core\/lib\/private\/Share\/Share.php(84): OC\\AppConfig->getValue('core', 'shareapi_enable...', 'yes')\n#9 \/home\/julian\/dev\/php\/core\/lib\/public\/Share.php(61): OC\\Share\\Share::isEnabled()\n#10 \/home\/julian\/dev\/php\/core\/lib\/private\/legacy\/template.php(159): OCP\\Share::isEnabled()\n#11 \/home\/julian\/dev\/php\/core\/lib\/private\/legacy\/template.php(83): OC_Template::initTemplateEngine('guest')\n#12 \/home\/julian\/dev\/php\/core\/lib\/private\/legacy\/template.php(349): OC_Template->__construct('', 'installation', 'guest')\n#13 \/home\/julian\/dev\/php\/core\/core\/Controller\/SetupController.php(95): OC_Template::printGuestPage('', 'installation', Array)\n#14 \/home\/julian\/dev\/php\/core\/core\/Controller\/SetupController.php(75): OC\\Core\\Controller\\SetupController->display(Array)\n#15 \/home\/julian\/dev\/php\/core\/lib\/base.php(844): OC\\Core\\Controller\\SetupController->run(Array)\n#16 \/home\/julian\/dev\/php\/core\/index.php(54): OC::handleRequest()\n#17 {main}","File":"\/home\/julian\/dev\/php\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractSQLiteDriver.php","Line":63}

[Sun Nov  4 15:59:21 2018] Exception: {"Exception":"Doctrine\\DBAL\\Exception\\TableNotFoundException","Message":"An exception occurred while executing 'SELECT * FROM \"oc_appconfig\"':\n\nSQLSTATE[HY000]: General error: 1 no such table: oc_appconfig","Code":0,"Trace":"#0 \/home\/julian\/dev\/php\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(184): Doctrine\\DBAL\\Driver\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/home\/julian\/dev\/php\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(158): Doctrine\\DBAL\\DBALException::wrapException(Object(Doctrine\\DBAL\\Driver\\PDOSqlite\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'An exception oc...')\n#2 \/home\/julian\/dev\/php\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(943): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOSqlite\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT * FROM \"...', Array)\n#3 \/home\/julian\/dev\/php\/core\/lib\/private\/DB\/Connection.php(187): Doctrine\\DBAL\\Connection->executeQuery('SELECT * FROM \"...', Array, Array, NULL)\n#4 \/home\/julian\/dev\/php\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php(219): OC\\DB\\Connection->executeQuery('SELECT * FROM \"...', Array, Array)\n#5 \/home\/julian\/dev\/php\/core\/lib\/private\/DB\/QueryBuilder\/QueryBuilder.php(141): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#6 \/home\/julian\/dev\/php\/core\/lib\/private\/AppConfig.php(301): OC\\DB\\QueryBuilder\\QueryBuilder->execute()\n#7 \/home\/julian\/dev\/php\/core\/lib\/private\/AppConfig.php(122): OC\\AppConfig->loadConfigValues()\n#8 \/home\/julian\/dev\/php\/core\/lib\/private\/Share\/Share.php(84): OC\\AppConfig->getValue('core', 'shareapi_enable...', 'yes')\n#9 \/home\/julian\/dev\/php\/core\/lib\/public\/Share.php(61): OC\\Share\\Share::isEnabled()\n#10 \/home\/julian\/dev\/php\/core\/lib\/private\/legacy\/template.php(159): OCP\\Share::isEnabled()\n#11 \/home\/julian\/dev\/php\/core\/lib\/private\/legacy\/template.php(83): OC_Template::initTemplateEngine('guest')\n#12 \/home\/julian\/dev\/php\/core\/lib\/private\/legacy\/template.php(349): OC_Template->__construct('', 'installation', 'guest')\n#13 \/home\/julian\/dev\/php\/core\/core\/Controller\/SetupController.php(95): OC_Template::printGuestPage('', 'installation', Array)\n#14 \/home\/julian\/dev\/php\/core\/core\/Controller\/SetupController.php(75): OC\\Core\\Controller\\SetupController->display(Array)\n#15 \/home\/julian\/dev\/php\/core\/lib\/base.php(844): OC\\Core\\Controller\\SetupController->run(Array)\n#16 \/home\/julian\/dev\/php\/core\/index.php(54): OC::handleRequest()\n#17 {main}","File":"\/home\/julian\/dev\/php\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractSQLiteDriver.php","Line":63}

[Sun Nov  4 15:59:21 2018] Exception: {"Exception":"Doctrine\\DBAL\\Exception\\TableNotFoundException","Message":"An exception occurred while executing 'SELECT * FROM \"oc_appconfig\"':\n\nSQLSTATE[HY000]: General error: 1 no such table: oc_appconfig","Code":0,"Trace":"#0 \/home\/julian\/dev\/php\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(184): Doctrine\\DBAL\\Driver\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/home\/julian\/dev\/php\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(158): Doctrine\\DBAL\\DBALException::wrapException(Object(Doctrine\\DBAL\\Driver\\PDOSqlite\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'An exception oc...')\n#2 \/home\/julian\/dev\/php\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(943): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOSqlite\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT * FROM \"...', Array)\n#3 \/home\/julian\/dev\/php\/core\/lib\/private\/DB\/Connection.php(187): Doctrine\\DBAL\\Connection->executeQuery('SELECT * FROM \"...', Array, Array, NULL)\n#4 \/home\/julian\/dev\/php\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Query\/QueryBuilder.php(219): OC\\DB\\Connection->executeQuery('SELECT * FROM \"...', Array, Array)\n#5 \/home\/julian\/dev\/php\/core\/lib\/private\/DB\/QueryBuilder\/QueryBuilder.php(141): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#6 \/home\/julian\/dev\/php\/core\/lib\/private\/AppConfig.php(301): OC\\DB\\QueryBuilder\\QueryBuilder->execute()\n#7 \/home\/julian\/dev\/php\/core\/lib\/private\/AppConfig.php(122): OC\\AppConfig->loadConfigValues()\n#8 \/home\/julian\/dev\/php\/core\/lib\/private\/Share\/Share.php(84): OC\\AppConfig->getValue('core', 'shareapi_enable...', 'yes')\n#9 \/home\/julian\/dev\/php\/core\/lib\/public\/Share.php(61): OC\\Share\\Share::isEnabled()\n#10 \/home\/julian\/dev\/php\/core\/lib\/private\/legacy\/template.php(159): OCP\\Share::isEnabled()\n#11 \/home\/julian\/dev\/php\/core\/lib\/private\/legacy\/template.php(83): OC_Template::initTemplateEngine('error')\n#12 \/home\/julian\/dev\/php\/core\/lib\/private\/legacy\/template.php(397): OC_Template->__construct('', 'exception', 'error', false)\n#13 \/home\/julian\/dev\/php\/core\/index.php(76): OC_Template::printExceptionErrorPage(Object(Doctrine\\DBAL\\Exception\\TableNotFoundException))\n#14 {main}","File":"\/home\/julian\/dev\/php\/core\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractSQLiteDriver.php","Line":63}

### Server configuration
**Operating system**:
Debian 9 (64 Bit)

**Web server:**
php built-in server

**Database:**
Sqlite3 (But not selected yet)

**PHP version:**
7.1.23

**ownCloud version:** 
master branch

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
git

**Comment by DeepDiver1975** [comment]
Template tries to Access db . Related to sharing changes in core

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @DeepDiver1975.

Possibly related issues are https://github.com/owncloud/core/issues/16454 (ownCloud Database issue), https://github.com/owncloud/core/issues/1239 (Errors during creating database connection put ownCloud into an infinite loop.), https://github.com/owncloud/core/issues/4232 (Access the database of owncloud), https://github.com/owncloud/core/issues/4226 (Access the database of owncloud), and https://github.com/owncloud/core/issues/1242 (no such table: metadata - on query SELECT md5 FROM metadata).
