### ISSUE TITLE
Error 403 when I try to upload a file in Images folder

### ISSUE THREAD

**Issue by piercarlo62** [owncloud/core#33407]
### Steps to reproduce
1. Create a folder named "Images"
2. Upload a file

### Expected behaviour
The uploading of the file

### Actual behaviour
The uploading procedure start and finish with an error 'Unknown error "error" uploading file "HartmannThomas.jpg"'
This behavioue happen only with the folder named Images. On other folder all working fine.

### Server configuration
Hosting Package | Yearly Ultimate
Server Name | sv76
cPanel Version | 74.0 (build 9)
Apache Version | 2.2.29
PHP Version | 5.3.29
MySQL Version | 5.6.41-cll-lve
Architecture | x86_64
Operating System | linux
Path to Sendmail | /usr/sbin/sendmail
Path to Perl | /usr/bin/perl
Perl Version | 5.10.1
Kernel Version | 2.6.32-896.16.1.lve1.4.51.el6.x86_64

**ownCloud version:** (see ownCloud admin page)
10.0.10 (stable)
**Updated from an older ownCloud or fresh install:**
Fresh Install
**Where did you install ownCloud from:**
Softacolous

**The content of config/config.php:**
link: https://cloud.fidatek.cf/index.php/s/9adnum9Upuoejq3
```
**The config report content**
```
link: https://cloud.fidatek.cf/index.php/s/Rx3u3Vjmfk4rFvr

**List of activated apps:**

1. Admin COnfig Report
2. Delete Files
3. Federation
4. Provisioning Api
5. Share Files
6. Update Notification
7. Versions
8. Activity
9. Calendar
10. Collaborative Tags
11. Comments
12. Contacts
13. Drawio
14. First Run Wizzard
15. Gallery
16. Mail Template Editor
17. Market
18. Notifications
19. PDF Viewer
20. Tasks
21. Video Player

```
**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
```
**SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';**
I´m getting empty result 'No data from the query'
```
### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10 pro
### Logs
#### Web server error log
```
link: https://cloud.fidatek.cf/index.php/s/V6RUogClOWfWf5s
```
#### ownCloud log (data/owncloud.log)
```
link: https://cloud.fidatek.cf/index.php/s/hBELp7Vox6ceBtX
```
#### Browser log
```
a) The javascript console log
link: https://cloud.fidatek.cf/index.php/s/OLh8Z383U8jLlz7
b) The network log 
link: https://cloud.fidatek.cf/index.php/s/MaKciAk52uByvg4

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/5265 (An 403 error should be shown when you try to upload a big file in a shared folder with the update permission), https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/28840 (-Error-), https://github.com/owncloud/core/issues/10120 ("stat failed" error in log when i upload a file or i create a folder), and https://github.com/owncloud/core/issues/3243 (HTTP error 403 when trying to upload with the OSX client or via webDav (CLI)).

**Comment by piercarlo62** [comment]
I checked the possibly related issues bur no one fit on my problem.

**Comment by ho4ho** [comment]
Works on https://demo.owncloud.org, something wrong in webserver / cpanel?

**Comment by phil-davis** [comment]
I tried this on a localdevelopment system on current core master and it all worked OK.

**Comment by piercarlo62** [comment]
dear ho4ho yes the server response is 403 and the server is on share host with cpanel.
I share the link of console log but I cannot understand where is the error and why happen only with images named folder with other folders the all is ok.

**Comment by PVince81** [comment]
not an ownCloud bug, related to the deployment environment

you can ask for help in http://central.owncloud.org/
