### ISSUE TITLE
Unexpected error code with chunk upload of files to folders with no edit permissions

### ISSUE THREAD

**Issue by davigonz** [owncloud/core#33416]
### Steps to reproduce
1. **User A** shares a folder with **user B**, with no edit permissions
2. **User B** uploads a file to the shared folder

### Expected behaviour
After uploading all the file chunks, the `MOVE` operation responsible for moving the file to the final destination should retrieve a `403` error instead of `500` internal server error. 

We expect that the final `MOVE` tells us whether the operation can be done or not. 

### Actual behaviour
Final `MOVE` operation retrieves `500` internal error. 

### Server configuration

**Web server:** Apache/2.4.25 (Debian)

**Database:** MySQL

**PHP version:** php 7.2.11

**ownCloud version:** 10.0.10 stable

**Updated from an older ownCloud or fresh install:** fresh install

### Video with the step 2 described above

![chunks_upload](https://user-images.githubusercontent.com/15261363/47989243-bb0a9b80-e0e4-11e8-970f-f27936bded41.gif)

### Related issues

https://github.com/owncloud/android/issues/2070#issuecomment-435377083
https://github.com/owncloud/android/issues/2291#issuecomment-434760233

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/11681 (Errors when uploading to public folder), https://github.com/owncloud/core/issues/12730 (Permissions error on some folders), https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/28840 (-Error-), and https://github.com/owncloud/core/issues/14352 (Permission to upload).

**Comment by PVince81** [comment]
yes, it's a bug.

**Comment by IljaN** [comment]
Forward port here: https://github.com/owncloud/core/pull/33734
