### ISSUE TITLE
avoid "ui-state-active" jumpiness

### ISSUE THREAD

**Issue by felixheidecke** [owncloud/core#33441]
Item's in the share dropdown jump 1px vertically on hovering above them … best seen when there are multiple selections.

 
### Steps to reproduce
1. create users _maximilian_ and _maximum_
2. type _max_ into the share select box
3. hover over the selection

### Expected behaviour
Item should remain static

### Actual behaviour
Items slightly jump up and down

---

Can be solved using CSS only

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/31966 (Bad install UI), https://github.com/owncloud/core/issues/5491 ([Sharing] Avoid loop shares), https://github.com/owncloud/core/issues/6765 (avoid world writable folder), https://github.com/owncloud/core/issues/8788 (Mobile UI issue), and https://github.com/owncloud/core/issues/27592 (Understanding Pending state).

**Comment by JammingBen** [comment]
Has been fixed meanwhile.
