### ISSUE TITLE
Soft refresh trashbin file list in Firefox does not work

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33445]
### Steps

1. Create some folders
1. Delete them
1. Go to trashbin view
1. Refresh the page (F5 or click on Reload button)
1. Check the list
1. Refresh the page again with Shift+F5 or Shift+Reload button (hard refresh)

### Expected result
In both cases the list refreshes properly

### Actual result
In Firefox the list does not refresh properly when not using shift (hard refresh).
In Chromium it works fine.

### Version
OC 10.0.10

The reason is likely due to the hidden "dir" input field which contains the current directory.
I've observed that Firefox tends to cache this value and set it back when doing a soft refresh, which messes up with the logic.

The reason why this input field exists is due to old legacies. Removing it might affect and break all related file lists.

cc @tomneedham as you observed this as well

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/16141 (Files aren't removed from the trashbin list when restored.), https://github.com/owncloud/core/issues/24060 (File list doesn't refresh until I do a scan), https://github.com/owncloud/core/issues/30189 (Previews in trashbin do not work), https://github.com/owncloud/core/issues/18516 (Previews of text files not working in trashbin), and https://github.com/owncloud/core/issues/2160 (Resharing files doesn't work).

**Comment by JanAckermann** [comment]
The error does not exist with FF 92.0 (64-bit) anymore.
