### ISSUE TITLE
Acceptance tests static tags

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33443]
For https://github.com/owncloud/core/pull/33118

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/pull/33024 (Test adding already existing tag), and https://github.com/owncloud/core/pull/33043 (Test adding an already existing tag).

**Comment by sharidas** [comment]
PR here for master branch https://github.com/owncloud/core/pull/33517
