### ISSUE TITLE
Set password via link, no error message for password policy violation

### ISSUE THREAD

**Issue by MSP-Stev** [owncloud/core#33457]
### Steps to reproduce
1. install a new owncloud 10.0.10 instance (mysql)
2. add the App "Password Policy" from owncloud
3. configure the app
minimum characters = 8
4. add a new local user
5. open the set password link from the mail
6. enter password "123"
7. nothing happen

error log owncloud:

`{"reqId":"W@QL9GIKhXcc4gkiU-vzuwAAAAY","level":3,"time":"November 08, 2018 10:12:04","remoteAddr":"****","user":"---","app":"index","method":"POST","url":"\/index.php\/setpassword\/274145020967403135423\/test.user","message":"Exception: {\"Exception\":\"OCA\\\\PasswordPolicy\\\\Rules\\\\PolicyException\",\"Message\":\"The password is too short. At least 8 characters are required.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/password_policy\\\/lib\\\/Engine.php(121): OCA\\\\PasswordPolicy\\\\Rules\\\\Length->verify('asd', 8)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/password_policy\\\/lib\\\/HooksHandler.php(170): OCA\\\\PasswordPolicy\\\\Engine->verifyPassword('asd', 'test.user', 'user')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/password_policy\\\/lib\\\/HooksHandler.php(147): OCA\\\\PasswordPolicy\\\\HooksHandler->verifyPassword(Object(Symfony\\\\Component\\\\EventDispatcher\\\\GenericEvent), 'user')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(212): OCA\\\\PasswordPolicy\\\\HooksHandler->verifyUserPassword(Object(Symfony\\\\Component\\\\EventDispatcher\\\\GenericEvent), 'OCP\\\\\\\\User::valid...', Object(Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher))\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/event-dispatcher\\\/EventDispatcher.php(44): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->doDispatch(Array, 'OCP\\\\\\\\User::valid...', Object(Symfony\\\\Component\\\\EventDispatcher\\\\GenericEvent))\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/User.php(302): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->dispatch('OCP\\\\\\\\User::valid...', Object(Symfony\\\\Component\\\\EventDispatcher\\\\GenericEvent))\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\User\\\\User->OC\\\\User\\\\{closure}(Array)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/User\\\/User.php(322): OC\\\\User\\\\User->emittingCall(Object(Closure), Array, 'user', 'setpassword')\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/settings\\\/Controller\\\/UsersController.php(659): OC\\\\User\\\\User->setPassword('asd')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OC\\\\Settings\\\\Controller\\\\UsersController->setPassword('274145020967403...', 'test.user', 'asd')\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\UsersController), 'setPassword')\\n#11 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\UsersController), 'setPassword')\\n#12 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('UsersController', 'setPassword', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#13 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/setpassword\\\/27...')\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/password_policy\\\/lib\\\/Rules\\\/Length.php\",\"Line\":33}"}`

### Expected behaviour
Information box should show the password policy.

### Actual behaviour
No error or information box to present the password policy violation.

### Server configuration
**Operating system**:
CentOS 7 (3.10.0-862.14.4.el7.x86_64)

**Web server:**
Server version: Apache/2.4.6 (CentOS)
Server built:   Jun 27 2018 13:48:59

**Database:**
Server version: 5.5.60-MariaDB MariaDB Server

**PHP version:**
7.0.32

**ownCloud version:** (see ownCloud admin page)
version	10.0.10.4
versionstring	10.0.10
edition	Community
productname	ownCloud

**Updated from an older ownCloud or fresh install:**
New Installation (also same problem with updated installations)

**Where did you install ownCloud from:**
https://owncloud.org/download/

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/4446 (Sharing via link with password, no error on incorrect password), https://github.com/owncloud/core/issues/13087 (Error messages), https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/28840 (-Error-), and https://github.com/owncloud/core/issues/15822 ([enc2] No error message for wrong recovery password in users page).

**Comment by phil-davis** [comment]
Should be fixed by https://github.com/owncloud/core/pull/33453

**Comment by PVince81** [comment]
yes  ^
