### ISSUE TITLE
Backport user_management translations to settings folder

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33454]
@DeepDiver1975 see title.

We usually miss these translations when backporting the core ones.

Is it a lot of work to manually sync them ?
If yes we might then rather accelerate the appification of user management...

But first, before backporting, fixing this:
```
apps3/side/user_management/l10n/de.js:81:    "Please set your password" : "Bitte erstellen erstellen Dein Passwort",
apps3/side/user_management/l10n/de.json:79:    "Please set your password" : "Bitte erstellen erstellen Dein Passwort",
apps3/side/user_management/l10n/de_DE.js:81:    "Please set your password" : "Bitte setze dein Passwort",
apps3/side/user_management/l10n/de_DE.json:79:    "Please set your password" : "Bitte setze dein Passwort",
```

- [x] fix repeated words in translation
- [x] fix de_DE translation to be "förmlich"

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/30936 (Backport of translations from master), https://github.com/owncloud/core/issues/22916 (Backport federation translations to 9.0.1), https://github.com/owncloud/core/issues/17533 (subscription Folders), https://github.com/owncloud/core/issues/55 (Missing translation), and https://github.com/owncloud/core/issues/11410 (S3 folder).

**Comment by PVince81** [comment]
@DeepDiver1975 I need your advice here: is this possible somehow by tweaking your scripts ?

**Comment by DeepDiver1975** [comment]
Our existing tooling on backporting translations cannot be used for cross repo operations because the tools are based on git log and diffs of the files.

One possibility could be to work on the po files where the po files of user-management are merged into the po files of core/settings. After that our js and json files could be regenerated.

But this needs careful testing and is really time consuming. We better manually copy the necessary strings and use the user_management repo with the next minor release - 10.2

**Comment by PVince81** [comment]
I wrote a new magic script... result here: https://github.com/owncloud/core/pull/34234

will post the script later, it only copies over keys but does not track deletion

**Comment by PVince81** [comment]
there is a mix up of förmlich / persönlich in the user_management repo on transifex: https://www.transifex.com/owncloud-org/owncloud/translate/#de_DE/user_management/158458024
this will need manual checking and fixing before backporting again

**Comment by PVince81** [comment]
I've fixed the translations to be aligned to förmlich or persönlich:
- https://www.transifex.com/owncloud-org/owncloud/translate/#de/user_management/136222790
- https://www.transifex.com/owncloud-org/owncloud/translate/#de_DE/user_management/137438559

will wait for sync

**Comment by PVince81** [comment]
sync has happened, PR needs review: https://github.com/owncloud/core/pull/34261
