### ISSUE TITLE
Improve new password field for new user

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33455]
When creating a new user, the user receives an email and is prompted to set a password.

The current form looks a bit too simple.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/277525/48133875-83445500-e298-11e8-8cbd-bea53ad7760b.png">

Possible improvements:
- Change button text to "Set password" or "Save"
- Add a message on the top that says "Please choose a password"

@pmaier1 let's discuss design improvements here

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/30981 (Add confirm password after new password), https://github.com/owncloud/core/issues/22991 (Send password to new users), https://github.com/owncloud/core/issues/21383 (LDAP users / password changing ), https://github.com/owncloud/core/issues/16442 (How to disable user password reset?), and https://github.com/owncloud/core/issues/10092 (User Password Reset).

**Comment by pmaier1** [comment]
Yep. I'd say:

- [ ] Change button text to "Save"
- [ ] Add a message on the top that says "Please choose a password."

**Comment by phil-davis** [comment]
That initial set password screen now looks like this:

![Set-password-ownCloud](https://user-images.githubusercontent.com/1535615/133962741-c3ce19b7-810b-4701-b1ce-39ecdd52b379.png)

Is it obvious enough that the user has to click the "big blue button" that says "Please set your password"?

@pmaier1 close or?

**Comment by pmaier1** [comment]
> @pmaier1 close or?

Well, the button text is still bad :upside_down_face: I'd change it to "Set password" and close then.
