### ISSUE TITLE
Issues setting lastmodified date of an item via PROPPATCH

### ISSUE THREAD

**Issue by felix-schwarz** [owncloud/core#33502]
### Steps to reproduce
1. Send PROPPATCH request with `D:lastmodifed` to a past date.
```
<?xml version="1.0" encoding="UTF-8"?>
<D:propertyupdate xmlns:D="DAV:">
<D:set>
<D:prop>
<D:lastmodified>Tue, 06 Nov 2018 11:07:03 GMT</D:lastmodified>
</D:prop>
</D:set>
</D:propertyupdate>
```

2. Receive valid-looking response:
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
<d:response>
    <d:href>/remote.php/dav/files/admin/ownCloud%20Manual.pdf</d:href>
    <d:propstat>
        <d:prop>
            <d:lastmodified/>
        </d:prop>
        <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
</d:response>
</d:multistatus>
```

3.  Verify that attribute has been set by sending a `PROPFIND`.

### Expected behaviour
The meta data for the item returned by the PROPFIND shows the date submitted in step 1.

### Actual behaviour
The meta data now reports `getlastmodified`  as `404 Not Found`:

`PROPFIND` excerpt:
```
<response>
    <href>/remote.php/dav/files/admin/ownCloud%20Manual.pdf</href>
    <propstat>
        <prop>
            <resourcetype/>
            <getcontentlength>4916139</getcontentlength>
            <getcontenttype>application/pdf</getcontenttype>
            <getetag>"35b1e0d790edd1174d35869534d308af"</getetag>
            <size>4916139</size>
            <id>00000016oc96i4hbc83a</id>
            <permissions>RDNVW</permissions>
            <favorite>1</favorite>
        </prop>
        <status>HTTP/1.1 200 OK</status>
    </propstat>
    <propstat>
        <prop>
            <getlastmodified/>
            <quota-available-bytes/>
            <quota-used-bytes/>
        </prop>
        <status>HTTP/1.1 404 Not Found</status>
    </propstat>
</response>
```

### Additional information:

@DeepDiver1975 suggested I should send `getlastmodified` instead. Request and response for that case:

```
<?xml version="1.0" encoding="UTF-8"?>
<D:propertyupdate xmlns:D="DAV:">
<D:set>
<D:prop>
<D:getlastmodified>Tue, 06 Nov 2018 11:07:03 GMT</D:getlastmodified>
</D:prop>
</D:set>
</D:propertyupdate>
```

```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
<d:response>
    <d:href>/remote.php/dav/files/admin/ownCloud%20Manual.pdf</d:href>
    <d:propstat>
        <d:prop>
            <d:getlastmodified/>
        </d:prop>
        <d:status>HTTP/1.1 403 Forbidden</d:status>
    </d:propstat>
</d:response>
</d:multistatus>
```

Before implementing this, I read a couple of issues on `lastmodifed` and `getlastmodified`, which - at least how I read them - in summary said that `lastmodified` was the way to go:
- https://github.com/owncloud/core/issues/15850
- https://github.com/owncloud/core/issues/19737

### Server configuration
**ownCloud version:** ownCloud 10.0.10 (stable)

**Everything else:** whatever runs demo.owncloud.org

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/21767 (issue), https://github.com/owncloud/core/issues/19737 (proppatch lastmodified instead of getlastmodified), https://github.com/owncloud/core/issues/22499 (Announce support for setting the lastmodified in DAV header), https://github.com/owncloud/core/issues/5234 (personal settings - styling issue), and https://github.com/owncloud/core/issues/10877 (Wrong date in calendar when I create a new item).

**Comment by michaelstingl** [comment]
@DeepDiver1975 explained, there's a custom oc-property that can be used there…

**Comment by DeepDiver1975** [comment]
X-OC-MTime is the http header which can be used in the PUT request. Value is an int based unix timestamp

**Comment by felix-schwarz** [comment]
Thanks!

As far as uploads in the ios-sdk are concerned, https://github.com/owncloud/ios-sdk/pull/35/commits/b4db58aa8375880d8019387a10a506206fa404bf successfully uses that header field to set the lastModified time during upload.

**Comment by dansoftware** [comment]
The problem still exists in current stable version 10.2.1. I used technique with curl described here https://github.com/owncloud/core/issues/19737#issuecomment-147679148 to reproduce the issue. I have got a positive response from the server:

```
# curl -X PROPPATCH -H "Content-Type: text/xml" --data-binary "@proppatch.txt" https://xxx:xxx@xxx.xxx/owncloud/remote.php/dav/files/xxx/2CD.GIF | xmllint --format -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   552  100   314  100   238   2514   1905 --:--:-- --:--:-- --:--:--  2532
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/owncloud/remote.php/dav/files/xxx/2CD.GIF</d:href>
    <d:propstat>
      <d:prop>
        <d:lastmodified/>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

But mtime of the file is not changed. Is there any hope that the problem is solved in the future? It breaks functionality of the third party syncing software that uses mtime to find changes.

**Comment by DeepDiver1975** [comment]
> lastmodified

the correct name is getlastmodified - see https://tools.ietf.org/html/rfc4918#section-15.7

regarding PROPPATCH - the property is protected as per specs -> it cannot be PROPPATCH'ed

**Comment by dansoftware** [comment]
Fine. I don't understand. There is no way to change mtime in WebDAV except proprietary "X-OC-MTime", is'nt it? If I use PROPPATCH+lastmodified ownCloud responses "HTTP/1.1 200 OK" but mtime is not changed actually. If I use PROPPATCH+getlastmodified ownCloud responses "HTTP/1.1 403 Forbidden". That's very strange situation.

**Comment by dansoftware** [comment]
Here is how the problem is solved in another WebDAV software: https://support.southrivertech.com/support/solutions/articles/9000144573-webdav-server-timestamps
