### ISSUE TITLE
Add function for making local files of varying size to use for upload tests.

### ISSUE THREAD

**Issue by davitol** [owncloud/core#33505]
We should include in core repo this function in order to have this kind of step in the core "API" steps so that it is easily used by any test that needs to make local files of varying size to use for upload tests.

This will make that this function can be accessed easily from any app acceptance tests

@owncloud/qa

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/2225 (Upload Size Issue), https://github.com/owncloud/core/issues/1373 (Uploading files issue), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), and https://github.com/owncloud/core/issues/31579 (test).

**Comment by individual-it** [comment]
I think we have steps to acchieve that:
`@Given user :user has added file :destination of :bytes bytes` : `WebDav::userAddsAFileTo(string $user, string $destination, string $bytes)`
`@Given a file with the size of :size bytes and the name :name has been created locally` : `WebUIGeneralContext::aFileWithSizeAndNameHasBeenCreatedLocally(int $size, string $name) `

maybe the job is to find the differences between those methods and create one that is available and used everywhere

**Comment by phil-davis** [comment]
And some of those are, for example, in ``webUI`` contexts. They do not actually do ``webUI`` stuff, so they can be moved into ``BasicStructure`` or similar, making them available more easily everywhere.
