### ISSUE TITLE
File versioning does not work within shared folder

### ISSUE THREAD

**Issue by bornakke** [owncloud/core#33507]
### Steps to reproduce
1. File in shared folder owned by current user is updated.
2. Update is saved to server through Owncloud Client 

### Expected behaviour
A new version of the file should appear under 'Versions'  

### Actual behaviour
Under activity one can see that the file has been updated. However under versions there remain 'No other versions available'. This works when updating a file in a non-shared folder. 

### Server configuration
**Operating system**:
Ubuntu 16.04.5

**Web server:**
Apache 2.4.18

**Database:**
MySql 5.7.24

**PHP version:**
PHP 7.0.32

**ownCloud version:** (see ownCloud admin page)
10.0.10

**Updated from an older ownCloud or fresh install:**
Updated from 10.0

**Where did you install ownCloud from:**
package

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**The content of config/config.php:**
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "updatechecker": true,
        "instanceid": "oc7fx28hcdls",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "10.0.10.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "theme": "",
        "loglevel": 3,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "singleuser": false
    }
}

**List of activated apps:**

Enabled:
  - activity: 2.4.0
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.9.0
  - files_sharing: 0.11.0
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.1.0
  - market: 0.2.5
  - notifications: 0.3.5
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.3.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome Version 70.0.3538.77

**Operating system:**
MacOSx 10.14.1

#### Web server error log
Nothing showing up 

#### ownCloud log (data/owncloud.log)
Nothing showing up 

#### Browser log
Nothing in console nor i network log

**Comment by agross** [comment]
I ran into the same problem. I'm not using ownCloud to store git repos. Versioning works outside of shared directories.

**Comment by patrickjahns** [comment]
@owncloud/qa do we currently have a scenario that checks versioning in shared folders, so that sharee and sharer both see a version if either of them changes a file?

**Comment by patrickjahns** [comment]
Double checked the scenarios myself - we have quite extensive suite coverage sharer and sharee scenarios with restoring versions here:

https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiMain/fileVersions.feature#L115-L252

@agross @bornakke can you double check these scenarios and compare with what you are doing? 
Please describe exactly in your scenario, what the difference might be, so we can reproduce this issue.

**Comment by agross** [comment]
@patrickjahns The only difference I can spot is that I share with a group.

I am also not restoring "using the WebDAV API", but using the web UI. The issue might be that I'm just not able to display the versions, hence there is no way to click the restore button which might trigger "the WebDAV API".

**Comment by bornakke** [comment]
Firstly, I managed to identify one shared folder for which versioning works. So it seem to be something more than simply sharing that breaks versioning. It should be noted that the group of people participating in this folder is smaller (only 5 members) and the entire folder have only recently been created. 

Secondly, I followed @agross suggestions and found that we only seem to be dealing with a display problem. Looking into the respective files_versioning folders for the owner of the problematic shared folders I can see that versions are created when a nev version is saved.

**Comment by agross** [comment]
Perhaps the tests can be extended to check whether the WebDAV API returns file versions in those cases before restoring using the API is performed.

My browser requests this when opening the Versions tab for a file:

```
PROPFIND https://owncloud.example.com/remote.php/dav/meta/225637/v

<?xml version="1.0"?>
<d:propfind  xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns">
  <d:prop>
  </d:prop>
</d:propfind>
```

which yields:
```
HTTP/207 
DAV: 1, 3, extended-mkcol, access-control, calendarserver-principal-property-search

<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/remote.php/dav/meta/225637/v/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
```

This looks like an empty response, which might be the reason for an empty version list.

**Comment by agross** [comment]
This is the response of a file with versions in an unshared directory:

```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/remote.php/dav/meta/229439/v/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response><d:response><d:href>/remote.php/dav/meta/229439/v/1544395891</d:href><d:propstat><d:prop><d:getlastmodified>Sun, 09 Dec 2018 22:51:31 GMT</d:getlastmodified><d:getcontentlength>4</d:getcontentlength><d:resourcetype/><d:getetag>788979ca952d3818ad4227350a514b5a</d:getetag><d:getcontenttype>text/plain</d:getcontenttype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
```

**Comment by individual-it** [comment]
> Perhaps the tests can be extended to check whether the WebDAV API returns file versions in those cases before restoring using the API is performed.

hmm there are a couple of tests doing that see https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiMain/fileVersions.feature
also there are UI tests for versioning https://github.com/owncloud/core/blob/master/tests/acceptance/features/webUIFiles/versions.feature

Any new interesting tests cases are most welcome

**Comment by agross** [comment]
> Any new interesting tests cases are most welcome

I have no idea how to isolate this bug further. But the empty response should not be returned by the server.

Is there some way to to get a detailed debug log from the server in case the code querying versions logs some debug information?

**Comment by agross** [comment]
> I have no idea how to isolate this bug further.

I had an idea ;-)

1. I created a new share directory and shared it with a group (default permissions)
1. Created a text file in that directory (web UI)
1. Entered some text, closed the edior (web UI)
1. Opened the file again, changed text, closed the editor (web UI)
1. The old version shows up with a Restore icon next to it

Given that there are older shared folders where this does not work (as tested yesterday) the question is what is special about the newly created folder that makes versions available.

**Comment by agross** [comment]
> what is special about the newly created folder

Some more experiments:

1. I shared the same directory with a **group** (in addition to the user)
1. Created another new file, changed it, changed it again like above
1. No versions for the new file!
1. *Also* no versions for the file I created above!
1. Removed the group share
1. Versions for *both* files show show up!

So I think we can conclude that this is related to sharing with groups.

**Comment by Fattoresaimon** [comment]
I have the same problem!
Here my case:
Shared folder between two user A and B
User A create a file test.txt and later modify the file.
User B: can see and download the versioned file
User A: no file version

On the User A for the non shared folder the versioning works
On the owncloud log nothing.
I have also cleared with occ the files version and nothing change.

**Comment by paurakhsharma** [comment]
@Fattoresaimon 
> User A create a file test.txt

Here when User A first creates a file does he input something in the file or leave it empty?
Because if he creates an empty file and then later modifies it and add something in it, I don't think you are suppose to see the pervious version(i.e empty file).

But, if User A creates a file with some content in it. And then later modifies it he should be able to see previous version.

**Comment by phil-davis** [comment]
> Because if he creates an empty file and then later modifies it and add something in it, I don't think you are suppose to see the pervious version(i.e empty file).

I raised issue #33891 to discuss that.

**Comment by butonic** [comment]
https://github.com/owncloud/core/pull/33302 touches the related code.
it changes the MetaVersion implementation https://github.com/owncloud/core/pull/33302/files#diff-f2c26f71448a52d9824cea7815573a3aL72

a lot of chinges, but a backport to oc 10 is in https://github.com/owncloud/core/pull/33859

@bornakke @agross can you try to confir that patch fixes this issue as well?

**Comment by agross** [comment]
I use ownCloud from docker (library/owncloud). Any hints on how to apply
that patch?

**Comment by Fattoresaimon** [comment]
> @Fattoresaimon
> 
> > User A create a file test.txt
> 
> Here when User A first creates a file does he input something in the file or leave it empty?
> Because if he creates an empty file and then later modifies it and add something in it, I don't think you are suppose to see the pervious version(i.e empty file).
> 
> But, if User A creates a file with some content in it. And then later modifies it he should be able to see previous version.

In my case User A create a non-empty file.
And also after some other modification the User A can't see the versioning.

**Comment by bornakke** [comment]
I'm in the same situation as Angross (installing through apt repository). Is there an easy way to install the patch?

**Comment by cjw77** [comment]
Same problem with shared folder versions.  @Fattoresaimon we ran with your example.  

> Shared folder between two user A and B
> User A create a file test.txt and later modify the file.
> User B: can see and download the versioned file
> User A: no file version
> 
> On the User A for the non shared folder the versioning works
> On the owncloud log nothing.
> I have also cleared with occ the files version and nothing change.

User A removes sharing from the folder.
User A can then see versions of the file.

**Comment by marcquark** [comment]
are there any news on this issue? has anyone installed the patches provided by butonic and did it resolve the issue?
we have similar issues where folders have been shared with groups, and group members can see file versions but get an error when trying to download or restore them. the owner can access the versions just fine though

**Comment by agross** [comment]
@marcquark I haven't tested it. I've migrated away to Nextcloud, the versions feature works there for shared directories.

**Comment by PVince81** [comment]
please upgrade to 10.1.0.

there was a bug in the code that generates the version list for viewing.
the versions do exist on disk, it's just that the API did not return them.

this is the PR that fixes it indirectly https://github.com/owncloud/core/pull/33302
