### ISSUE TITLE
move xpath to variable in DetailsDialog::getCommentXpath()

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#33527]
see https://github.com/owncloud/core/blob/master/tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php#L116

```
	/**
	 * find the xpath of comment with given content
	 *
	 * @param string $content
	 *
	 * @return string
	 */
	private function getCommentXpath($content) {
		return "//ul[@class='comments']//div[@class='message' and contains(., '" . $content . "')]";
	}
```

that xpath should be in a private variable like every other
@dpakach you have implemented that in #32927

**Comment by individual-it** [comment]
same in `getTagsDropDownResultsXpath()`
```
	/**
	 * Returns xpath of the tag results dropdown
	 *
	 * @return string
	 */
	public function getTagsDropDownResultsXpath() {
		return "//div[contains(@class, 'systemtags-select2-dropdown')]" .
			"//ul[@class='select2-results']" .
			"//span[@class='label']";
	}

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/30748 ([stable10] move linting from travis to drone), https://github.com/owncloud/core/issues/481 (moving files), https://github.com/owncloud/core/issues/8103 (Move File), https://github.com/owncloud/core/pull/30747 (move linting from travis to drone), and https://github.com/owncloud/core/pull/28376 ([stable10] move SetupHelper).

**Comment by individual-it** [comment]
same in `changeDetailsTab()`
`$tabSwitchXpath = "//li[@data-tabid='" . $tabId . "']";`
