### ISSUE TITLE
occ trashbin and versions commands do "all" by default

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33538]
```
occ trashbin:cleanup
occ trashbin:expire
occ versions:cleanup
occ versions:expire
```
These commands do the job for "all" by default.

Other ``occ`` comands (e.g. ``files:scan``) insist on the admin providing ``--all`` on the command line if they really want to do the action for all users.

Should the ``--all`` option be added to the above commands, and without it just display the help?

That would make the command line more consistent, and might avoid "disasters" for admins who really just intended to see some help output.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/9652 (trashbin/version cleanup occ command), https://github.com/owncloud/core/issues/24494 (occ command to clear all locks), https://github.com/owncloud/core/issues/33536 (create acceptance tests for occ trashbin commands), https://github.com/owncloud/core/issues/25970 (occ command to migrate data folder), and https://github.com/owncloud/core/issues/23380 (Occ command not working).

**Comment by PVince81** [comment]
makes sense. maybe some day

**Comment by phil-davis** [comment]
Do we do this sort of "easy" `occ` command standardization? Or will it cause enough backward-compatibility-break to annoy sysadmins who would have to start putting `--all` on these commands?

@pmaier1 ?

**Comment by phil-davis** [comment]
This would be an easy change to make, but should we?

**Comment by pmaier1** [comment]
While I fully agree with your intentions to standardize this and to make it less error-prone, I'm afraid I can't make that change without backwards-compatibility (which in turn would make the change pointless :) ). 

Our docs explicitly mention the command without `--all` and people have this in their crontabs (https://doc.owncloud.com/server/next/admin_manual/configuration/files/trashbin_options.html). Changing this will lead to many instances having not expiring trash bins and versions which I would like to avoid.
