### ISSUE TITLE
create acceptance tests for occ trashbin commands

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/core#33536]
# Description 
Add cli tests for files trashbin

Part of main issue #33051

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/33386 ( create acceptance tests for occ config commands (app set, system set, list...)), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), and https://github.com/owncloud/core/issues/33136 (occ log commands acceptance tests).

**Comment by paurakhsharma** [comment]
PR #33538 should solve it.
