### ISSUE TITLE
ShareLinks Protection

### ISSUE THREAD

**Issue by RavenousCtulhu** [owncloud/core#33542]
Is it possible when I share a Link with someone, that has some feature with a captcha or even some brute force protection, so unwanted users are not trying to guess the passwords randomly...

Thanks

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/4026 (Anonymous Upload - no upload with password protection), https://github.com/owncloud/core/issues/921 (oc-1581  -  CSRF protection issue), https://github.com/owncloud/core/issues/9192 (Owncloud needs logfile bloat protection), https://github.com/owncloud/core/issues/17528 (Prevent closing upgrade page while upgrade in progress), and https://github.com/owncloud/core/issues/13493 (The Preview class needs better protection against breakage).

**Comment by karakayasemi** [comment]
I quickly checked, we can aware of failed share access attempts in an app by using share.linkaccess event. Instead of core, it is possible to implement a proper protection policy for this purpose in Brute Force Protection app.

**Comment by PVince81** [comment]
raised https://github.com/owncloud/brute_force_protection/issues/57 in the brute force protection app
