### ISSUE TITLE
Blobify oc_properties.propertyvalue

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33554]
Currently oc_properties.propertyvalue is a varchar(255).

Considering future usage, we should make this column bigger to accommodate arbitrary content sizes.

Bonus: if we're touching the DB structure, maybe address https://github.com/owncloud/core/issues/32670 as we need to distinguish pure strings from complex XML values.

@DeepDiver1975

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/11996 (oc_properties, still needed ?), https://github.com/owncloud/core/issues/27358 (Normalize oc_properties), https://github.com/owncloud/core/issues/13281 (Repair step to clean up oc_properties), https://github.com/owncloud/core/issues/2186 (Missing Index on oc_properties), and https://github.com/owncloud/core/issues/17633 (s).
