### ISSUE TITLE
display version number for disabled apps with occ app:list

### ISSUE THREAD

**Issue by dercorn** [owncloud/core#33555]
All operating systems, all oc versions.

occ app:list shows version numbers only for enabled apps. Please make version numbers also visible for disabled apps.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/28085 (can't disable app with occ command), https://github.com/owncloud/core/issues/1805 (Migration disable all apps ), https://github.com/owncloud/core/issues/18690 ("Enable only for specific groups" of App shows it disabled in occ app:list), https://github.com/owncloud/core/issues/14661 (Provide app version in occ app:list), and https://github.com/owncloud/core/issues/16806 (Update disables apps).

**Comment by VicDeo** [comment]
Tricky questions:
1. If the app was enabled a while ago, disabled and update there are two versions: the version in DB  and the version from appinfo.xml. When these versions differ app upgrade will triggered after enabling the app. Which one is expected to be listed when they differ?

2. The app was deleted by admin without disabling it, has a version in DB but appinfo.xml is missing. What  is expected to be listed?

**Comment by pmaier1** [comment]
> Please make version numbers also visible for disabled apps.

Is there a specific reason for this?!

> Which one is expected to be listed when they differ?

I'd say the database state as this is the state oC "actually knows".

> What is expected to be listed?

Same, the database state.

Is there a reason why this differs between enabled and disabled in the first place?

**Comment by pako81** [comment]
Should the `app:list` command get the version for disabled apps from DB (means apps that have been once enabled and then disabled) or rather get this information for disabled apps (which have been never enabled) from info.xml? Since in the latter case, there is no `installed_version` in oc_appconfig.

**Comment by pako81** [comment]
To be more clear: do we need to also consider the case of apps which have been never enabled? If not, the change would be quite easy to implement.

**Comment by phil-davis** [comment]
And the 2 versions might be different. e.g. an app was enabled, v1.0. The sysadmin has disabled the app. An updated app has been put into the apps folder, but not yet enabled.

And the app might be in multiple folders in `apps_paths` and have different versions (not recommended, but can happen).

I guess stage 1 would be to display the version of the app that would be active if you enabled the app "right now".

**Comment by pako81** [comment]
@phil-davis yes, absolutely valid points. But I guess we should only gather this information from the DB regardless if filesystem contains different app versions in info.xml. Because DB is the "source of truth", means that is the app version known to oC at that point in time.

Is this what you mean with "I guess stage 1 would be to display the version of the app that would be active if you enabled the app "right now"?

**Comment by phil-davis** [comment]
> Is this what you mean with "I guess stage 1 would be to display the version of the app that would be active if you enabled the app "right now"?

I suspect that if you have a new version of the app code in `apps_paths` somewhere, then when you enable the app, the version recorded in the database will be automagically updated. If that is true, then the DB is only the "source of truth" about the version that was in use the last time the app was enabled.

Take your pick for what to display - it depends what question the sysadmin wants answered!

**Comment by pako81** [comment]
> I suspect that if you have a new version of the app code in apps_paths somewhere, then when you enable the app, the version recorded in the database will be automagically updated.

Correct. But not automagically. You are required to run `occ upgrade`.

**Comment by pako81** [comment]
Very straightforward approach proposed at https://github.com/owncloud/core/pull/36165
