### ISSUE TITLE
2 users - one Ldap one on Database can't connect to database ?

### ISSUE THREAD

**Issue by gamersalpha** [owncloud/core#33559]
Hello there, i have a probléme on my ownlcoud 10.10.10

i have the same user with account on database an an other on the ldap,  : 

![image](https://user-images.githubusercontent.com/32466950/48672193-f076a680-eb32-11e8-9340-10fe5bbd8849.png)

so now my problem is, 
i can only connect with user from ldap, 

how change the username from the first user ?

how i can fusion the two user ?

thanks

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/10052 (LDAP-Connect), https://github.com/owncloud/core/issues/24929 (LDAP user with blank userid overwriting database user settings, cannot remove user), https://github.com/owncloud/core/issues/12641 (Can't share files to LDAP users), https://github.com/owncloud/core/issues/8155 (Only one ldap user can login), and https://github.com/owncloud/core/issues/18340 (No ldap user appears).

**Comment by gamersalpha** [comment]
Hello there, 

please help, i m stuck with owncloud now

**Comment by ho4ho** [comment]
@gamersalpha Maybe bug tracker not good for questions?

**Comment by PVince81** [comment]
for support, see https://owncloud.org/help/
