### ISSUE TITLE
Neither file sharing section nor sharing permissions show up anymore

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#33579]
### Steps to reproduce
1. Log in as admin 
2. Click on top right icon to enter settings
3. You do not see the sharing section under the admin page anymore as expected per documentation under https://doc.owncloud.org/server/10.0/admin_manual/configuration/files/file_sharing_configuration.html

Another way to reproduce:
1. Click on an existing share, i.E. a directory I have shared with another user
2. You do not see the the options anymore to tell whether the user can edit or delete it (sharing permissions)

### Expected behaviour
I still can see the sharing section under the admin page and still can adjust sharing permissions of any shared folder.

### Actual behaviour
Sharing section under admin page is seen and sharing permissions of shared folders as well.

### Server configuration
**Operating system**:
Ubuntu 18.04

**Web server:**
nginx/1.14.1

**Database:**
mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper

**PHP version:**
PHP 7.2.12-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Nov 12 2018 09:55:44) ( NTS )

**ownCloud version:** (see ownCloud admin page)
10.0.10.4

**Updated from an older ownCloud or fresh install:**
Updated from an older.

**Where did you install ownCloud from:**
apt-get install

**Signing status (ownCloud 9.0 and above):**
https://gist.github.com/binarykitchen/d49c324b4b36d4904686e31925106acd

**The content of config/config.php:**
https://gist.github.com/binarykitchen/47d4ffac21383b41a13d60666990de3a

**List of activated apps:**

```
Enabled:
  - activity: 2.4.0
  - audioplayer: 2.4.1
  - bookmarks: 0.10.4
  - calendar: 1.6.0
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.4
  - dav: 0.4.0
  - encryption: 1.3.1
  - external: 1.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.9.0
  - files_sharing: 0.11.0
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 16.1.0
  - market: 0.2.5
  - music: 0.9.2
  - notes: 2.0.4
  - notifications: 0.3.5
  - onlyoffice: 2.0.3
  - provisioning_api: 0.5.0
  - security: 0.0.2
  - systemtags: 0.3.0
  - tasks: 0.9.6
  - updatenotification: 0.2.1
  - wallpaper: 0.1
Disabled:
  - firstrunwizard
  - user_external
```

**Are you using external storage, if yes which one:**
None, local only

**Are you using encryption:**
Yes

**Are you using an external user-backend, if yes which one:**
No

### Client configuration
**Browser:**
Latest Chrome

**Operating system:**
Mac OS High Sierra 10.13.6

#### Web server error log
Empty, nothing in the nginx error log for this domain.

#### ownCloud log (data/owncloud.log)
Nothing relevant, only plenty of 403s re invalid sync token for addressbook.

#### Browser log
No errors there.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/13032 (Sharing options do not show up ), https://github.com/owncloud/core/issues/3949 (File sharing), https://github.com/owncloud/core/issues/11035 (Files not marked as "shared"), https://github.com/owncloud/core/issues/1863 (shared icons don’t show anymore), and https://github.com/owncloud/core/issues/22894 (Link share does not show all files).

**Comment by ho4ho** [comment]
@binarykitchen Ad/sharing blocker in browser enable?

**Comment by binarykitchen** [comment]
Aaarrghh yes, that was it!!!

Wish there is code to detect and to print a warning. I bet this can happen to everyone sooner or later.

**Comment by ho4ho** [comment]
@binarykitchen 
> Wish there is code to detect and to print a warning.

Create new feature request?

**Comment by binarykitchen** [comment]
Ok, here the new feature request https://github.com/owncloud/core/issues/33642
