### ISSUE TITLE
Block access of contents folder

### ISSUE THREAD

**Issue by vdvas** [owncloud/core#33586]
There is an installed owncloud, in the form of a Univention Corporate Server which was deployed from a vmware appliance, the docker image - owncloud works in it.
It is necessary to prohibit listing of files in the owncloud directory, files should be opened only by direct links, and there should be write access to this directory.
I think that this is configured via .htaccess or the VirtualHost configuration file.
Version ownCloud	10.0.9 (stable)
apache 2.4

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/9157 ([Shared with you] Not possible to access to a folder content), https://github.com/owncloud/core/issues/25695 (Users with shared link access cant create folders), https://github.com/owncloud/core/issues/6249 (Block folder creation when user has reached the quota), https://github.com/owncloud/core/issues/17057 (Token giving access to one file gives access to whole folder), and https://github.com/owncloud/core/issues/3164 (Very slow access to shared folders).

**Comment by ho4ho** [comment]
@vdvas Bug tracker not good for questions.
