### ISSUE TITLE
Test that making changes on the edit dialog and pressing cancel should not change anything

### ISSUE THREAD

**Issue by skshetry** [owncloud/core#33590]
Test that making changes on the edit dialog and pressing cancel should not change anything

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22150 (Editing a comment without changing anything should not send a request to the server), and https://github.com/owncloud/core/pull/32965 ([stable10] a pi test edit user change statements).
