### ISSUE TITLE
CLI Acceptance tests to verify setting a password to valid and invalid values

### ISSUE THREAD

**Issue by dpakach** [owncloud/core#33598]
main issue #33570

Test adding and editing users with a set of valid and invalid password strings and verify that users are created or not created depending in the validity of password.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/33570 (Acceptance tests to verify setting a password to valid and invalid values), https://github.com/owncloud/core/pull/32755 (Acceptance test steps that specify the password to be used), https://github.com/owncloud/core/issues/31116 (Acceptance tests for lost password email), https://github.com/owncloud/core/issues/31579 (test), and https://github.com/owncloud/core/issues/22492 (test).
