### ISSUE TITLE
PROPFIND to get list of files doesn't properly encode @ character 

### ISSUE THREAD

**Issue by davigonz** [owncloud/core#33594]
We've been facing some issues with usernames containing 'At' character (@) in mobile apps so I had a deep look into it and noticed a weird behaviour. It seems that the **`PROPFIND` to get the files for a specific user is not properly retrieving the encoded path for files when using @.**

### Steps to reproduce

**Curl command to list a directory:**

Being `%40` the `@` character encoded, therefore username `user@whatever` is `user%40whatever`

`curl -X PROPFIND -H "Content-Type: text/xml" -H 'User-Agent:Mozilla/5.0 (Android) ownCloud-android/2.9.2' -H 'Authorization:Basic base64Credentials' -d "<?xml version='1.0' encoding='utf-8' ?><D:propfind xmlns:D='DAV:'><D:allprop/></D:propfind>" 'url:port/remote.php/dav/files/user%40name/'  | xmllint --format -
`

### Expected behaviour
Server should include the path for every file properly encoded, i.e. `/remote.php/dav/files/user%40name/whatever`

**Expected curl result:** 
```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/remote.php/dav/files/user%40name/</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Tue, 20 Nov 2018 11:03:14 GMT</d:getlastmodified>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:quota-used-bytes>5630922</d:quota-used-bytes>
        <d:quota-available-bytes>-3</d:quota-available-bytes>
        <d:getetag>"5bf3e9f264d46"</d:getetag>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/dav/files/user%40name/Documents/</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Tue, 20 Nov 2018 11:03:14 GMT</d:getlastmodified>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:quota-used-bytes>36227</d:quota-used-bytes>
        <d:quota-available-bytes>-3</d:quota-available-bytes>
        <d:getetag>"5bf3e9f240a04"</d:getetag>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/dav/files/user%40name/Photos/</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Tue, 20 Nov 2018 11:03:14 GMT</d:getlastmodified>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:quota-used-bytes>678556</d:quota-used-bytes>
        <d:quota-available-bytes>-3</d:quota-available-bytes>
        <d:getetag>"5bf3e9f264d46"</d:getetag>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/dav/files/user%40name/ownCloud%20Manual.pdf</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Tue, 20 Nov 2018 11:03:14 GMT</d:getlastmodified>
        <d:getcontentlength>4916139</d:getcontentlength>
        <d:resourcetype/>
        <d:getetag>"ae4602f56f897e638ad678c57e5404ca"</d:getetag>
        <d:getcontenttype>application/pdf</d:getcontenttype>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

### Actual behaviour
Server includes `@` instead of `%40`, e.g. `/remote.php/dav/files/user@name/whatever`

**Actual curl result:** 
```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/remote.php/dav/files/user@name/</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Tue, 20 Nov 2018 11:03:14 GMT</d:getlastmodified>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:quota-used-bytes>5630922</d:quota-used-bytes>
        <d:quota-available-bytes>-3</d:quota-available-bytes>
        <d:getetag>"5bf3e9f264d46"</d:getetag>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/dav/files/user@name/Documents/</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Tue, 20 Nov 2018 11:03:14 GMT</d:getlastmodified>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:quota-used-bytes>36227</d:quota-used-bytes>
        <d:quota-available-bytes>-3</d:quota-available-bytes>
        <d:getetag>"5bf3e9f240a04"</d:getetag>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/dav/files/user@name/Photos/</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Tue, 20 Nov 2018 11:03:14 GMT</d:getlastmodified>
        <d:resourcetype>
          <d:collection/>
        </d:resourcetype>
        <d:quota-used-bytes>678556</d:quota-used-bytes>
        <d:quota-available-bytes>-3</d:quota-available-bytes>
        <d:getetag>"5bf3e9f264d46"</d:getetag>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
  <d:response>
    <d:href>/remote.php/dav/files/user@name/ownCloud%20Manual.pdf</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Tue, 20 Nov 2018 11:03:14 GMT</d:getlastmodified>
        <d:getcontentlength>4916139</d:getcontentlength>
        <d:resourcetype/>
        <d:getetag>"ae4602f56f897e638ad678c57e5404ca"</d:getetag>
        <d:getcontenttype>application/pdf</d:getcontenttype>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>
```

### Server configuration
**Web server:** Apache 2.4.25

**Database:** MySQL

**PHP version:** php7.2.12

**ownCloud version:** 10.0.10 (stable)

CC / @michaelstingl @DeepDiver1975 @PVince81

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22326 (PROPFIND answer doesn't include encoding.), https://github.com/owncloud/core/issues/12112 (ownCloud File Mapper Not Encoding UTF-8 Properly), https://github.com/owncloud/core/issues/11724 (filename with bad encoding not listed), and https://github.com/owncloud/core/issues/27089 (Server >9.0 is not responding with 403 Forbidden when some firewall rules are enabled).

**Comment by phil-davis** [comment]
I made issue #33596 to consider adding a more general variety of acceptance tests for user IDs.

**Comment by phil-davis** [comment]
I am surprised that "space" in a user  ID works at all. I didn't think that user IDs containing the "space" char could be created in the first place.

**Comment by davigonz** [comment]
>  I didn't think that user IDs containing the "space" char could be created in the first place.

I thought the same the first time I saw it 😄

**Comment by jesmrec** [comment]
![screen shot 2018-11-20 at 16 14 30](https://user-images.githubusercontent.com/14894746/48782874-66b80c00-ecdf-11e8-9cef-4ae84e8cd205.png)

**Comment by DeepDiver1975** [comment]
I could not find any detailed specs in the RFC regarding what to decode and what not.

Tests with default Apache+mod_dav show the same behavior:

I created a folder at@user and a folder "a b" and this is the propfind response:

![screenshot from 2018-11-21 10-50-57](https://user-images.githubusercontent.com/1005065/48833311-5eadaa00-ed7b-11e8-8c9d-d1f83e79a076.png)
![screenshot from 2018-11-21 10-51-04](https://user-images.githubusercontent.com/1005065/48833310-5eadaa00-ed7b-11e8-8f07-00ccd5f96628.png)

**Comment by DeepDiver1975** [comment]
See this test - only spaces need to be decoded in href https://github.com/sabre-io/dav/pull/719 https://github.com/sabre-io/http/blob/4bfb3834209de0a4c658e0dbe69bda794bf42e3a/lib/functions.php#L385

**Comment by davigonz** [comment]
Thanks @DeepDiver1975 for having a look into this. I am going to give you more context about what is done in the Android app after performing a `PROPFIND` operation to get all the files from a specific folder.

Once we get the `PROPFIND` response, we try to create a list of `RemoteFile` objects so we can save them into the database. This `RemoteFile` objects should contain the relative remote path, e.g. `/Documents/text1`, being the whole remote path `/remote.php/dav/files/username/Documents/text1`.

How is this relative remote path built? By comparing two paths:
- `/remote.php/dav/files/username/` composed of `/remote.php/dav/files/` stored in an app constant and `username` retrieved in a previous `GET` user info operation, properly encoded and saved.
- `/remote.php/dav/files/username/Documents/text1` read from `href` in `PROPFIND` response.
- **Relative remote path:** `/Documents/text1`

What happens when the username contains `space`? Which paths are being compared? 
- `/remote.php/dav/files/user%20name/` composed of `/remote.php/dav/files/` constant and the `user%20name` properly encoded.
- `/remote.php/dav/files/user%20name/Documents/text1` read from `href` in `PROPFIND` response. 
- **Relative remote path:** `/Documents/text1` because both paths are the same before this relative path. 

What happens when the username contains `@`? Which paths are being compared?
- `/remote.php/dav/files/user%40name/` composed of `/remote.php/dav/files/` constant and the `user%20name` properly encoded.
- `/remote.php/dav/files/user@name/Documents/text1` read from `href` in `PROPFIND` response. 
- **Current relative remote path:** `/remote.php/dav/files/user@name/Documents/text1` because both paths are the same before this relative path. 
- **Expected relative remote path:** `/Documents/text1`

**Comment by DeepDiver1975** [comment]
The files app work almost identical - with one exception:
- path comparison is done on the decoded paths and user names

![screenshot from 2018-11-21 12-43-47](https://user-images.githubusercontent.com/1005065/48839250-1c8c6480-ed8b-11e8-9a97-0d545f8cfa91.png)

**Comment by davigonz** [comment]
Good news, applying the decoding approach seems to work:

Comparing next paths:

- Username with @
    - `/remote.php/dav/files/user@name/` composed of `/remote.php/dav/files/` constant and `user@name`, obtained from a previous `GET` user info operation, with no modification since is already retrieved as decoded. 
    - `/remote.php/dav/files/user@name/Documents/text1` read from href in PROPFIND response, decoded would the same.
    - **Relative remote path**: `/Documents/text1` because both paths are the same before this relative path.

- Username with space
    - `/remote.php/dav/files/user name/` composed of `/remote.php/dav/files/` constant and `user name`, obtained from a previous `GET` user info operation, with no modification since is already retrieved as decoded. 
    - `/remote.php/dav/files/user%20name/Documents/text1` read from href in PROPFIND response, decoded would be `/remote.php/dav/files/user name/Documents/text1`
    - **Relative remote path**: `/Documents/text1` because both paths are the same before this relative path.

Thanks for your help @DeepDiver1975 😉

Anyway, I was expecting to receive the `@` character encoded because I read the next paragraph in [RFC 1738](http://www.rfc-editor.org/rfc/rfc1738.txt)

![screenshot 2018-11-21 at 13 53 46](https://user-images.githubusercontent.com/15261363/48842565-e227c500-ed94-11e8-8d64-5770b5349d10.png)

After reading this, I understand that `@` character should be encoded, not sure why sabre dav is not doing it.

**Comment by DeepDiver1975** [comment]
Just for the sake of completness ... http://sabre.io/dav/character-encoding/

**Comment by PVince81** [comment]
I think I observed similar issues before when working on having the UI use the new DAV endpoint. See https://github.com/owncloud/core/pull/28769/commits/c99f5b49b7d4140d451472b1f6f52ba9c095906a

I didn't know back then that it might be a Sabre problem and simply adjusted the JS side to send whatever works.

**Comment by DeepDiver1975** [comment]
@PVince81 this was fixed in andoid - we can close this from my pov
