### ISSUE TITLE
Test for creating users with various passwords using webUI

### ISSUE THREAD

**Issue by dpakach** [owncloud/core#33602]
Main issue #33570

Add tests for creating users with passwords containing special characters and invalid characters using the webUI

**Comment by dpakach** [comment]
This Issue must be in User management app

**Comment by phil-davis** [comment]
And the user_management test code will need to be backported to core stable10 - but that is just an "administrative" thing. True - the primary code starts in user_management.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/pull/33257 (webUi test user setting language), and https://github.com/owncloud/core/issues/32583 (Automated webUI tests for languages).

**Comment by dpakach** [comment]
moved to new issue [here](https://github.com/owncloud/user_management/issues/107)
