### ISSUE TITLE
Test app:getpath

### ISSUE THREAD

**Issue by skshetry** [owncloud/core#33614]
Test that `app:getpath` returns correct path for the app.
Part of the #33054

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/pull/33114 (Add tests for getting app info), and https://github.com/owncloud/core/issues/28889 (UI test "create new app password" fails sometimes).
