### ISSUE TITLE
Error sharing a file/folder from towncloud 10.0.10 to owncloud 10.0.7. [Solved]

### ISSUE THREAD

**Issue by pollopolea** [owncloud/core#33616]
I noticed an error when sharing a file from the owncloud 10.0.10 to an owncloud 10.0.7.

This is the error in owncloud 10.0.10 

{"reqId":"W-VRv9aPbVU9OQEn3OPvtwAAAAM","level":3,"time":"2018-11-21T12:38:24+00:00","remoteAddr":"*********","user":"******","app":"no app in context","method":"POST","url":"\/owncloud\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json","message":"Failed to notify remote server of federated share, removing share (Server error response [url] https:\/\/*************\/ocs\/v2.php\/cloud\/shares?format=json [status code] 500 [reason phrase] Internal Server Error)"}

This is the error in 10.0.7:

{"reqId":"W-VRumZKQy5WfEyS9sXspwAAAAI","level":3,"time":"2018-11-21T13:38:19+01:00","remoteAddr":"1*****","user":"--","app":"files_sharing","method":"POST","url":"\/ocs\/v2.php\/cloud\/shares?format=json","message":"server can not add remote share, An exception occurred while executing 'INSERT INTO \"oc_notifications\" (\"app\", \"user\", \"timestamp\", \"object_type\", \"object_id\", \"subject\", \"subject_parameters\", \"message\", \"message_parameters\", \"link\", \"icon\", \"actions\") VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"files_sharing\", \"*****\", 1542803899, \"remote_share\", \"21\", \"remote_share\", \"[\\\"******@http:\\\\\\\/\\\\\\\/******\\\\\\\/owncloud\\\\\\\/\\\",\\\"*******@http:\\\\\\\/\\\\\\\/*********\\\\\\\/owncloud\\\\\\\/\\\",\\\"FOLDER\\\"]\", \"\", \"[]\", \"\", \"\", \"[{\\\"label\\\":\\\"decline\\\",\\\"link\\\":\\\"https:\\\\\\\/\\\\\\\/*********\\\\\\\/ocs\\\\\\\/v1.php\\\\\\\/apps\\\\\\\/files_sharing\\\\\\\/api\\\\\\\/v1\\\\\\\/remote_shares\\\\\\\/pending\\\\\\\/21\\\",\\\"type\\\":\\\"DELETE\\\",\\\"primary\\\":false},{\\\"label\\\":\\\"accept\\\",\\\"link\\\":\\\"https:\\\\\\\/\\\\\\\/*********\\\\\\\/ocs\\\\\\\/v1.php\\\\\\\/apps\\\\\\\/files_sharing\\\\\\\/api\\\\\\\/v1\\\\\\\/remote_shares\\\\\\\/pending\\\\\\\/21\\\",\\\"type\\\":\\\"POST\\\",\\\"primary\\\":false}]\"]:\n\nORA-01400: cannot insert NULL into (\"OWNCLOUD\".\"oc_notifications\".\"message\")"}

the error is related to the table oc_notifications in owncloud 10.0.7.

SOLUTION:
In version 10.0.7 you have some additional "not null checks" in the columns "message" and "link". 
These checks do not exist in version 10.0.10, so if you use version 10.0.7 you should disable them.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @PVince81, and @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/834 (Owncloud down after clic shared folder 4.0.7), https://github.com/owncloud/core/issues/28015 (Failed upgrade from Owncloud 10.0.0.1 to Owncloud 10.0.1), https://github.com/owncloud/core/issues/13908 ("Error while sharing - error" when trying to share a file or directory on owncloud 7.0.4), https://github.com/owncloud/core/issues/12740 (owncloud 7.0.3 adding "(2)" to every file/folder shared), and https://github.com/owncloud/core/issues/10676 (Downgrade owncloud 7 to owncloud 6.0.3 error).
