### ISSUE TITLE
using the latest version (11.0.0 prealpha (git)), the links in "Help and tips" page do not work.

### ISSUE THREAD

**Issue by dpakach** [owncloud/core#33634]
### Steps to reproduce
1. Install latest version of owncloud (`11.0.0 prealpha (git)`)
2. Go to 'help and tips' page
3. Click on any of the help links

### Expected behaviour
User should be redirected to documentation pages

### Actual behaviour
404 not found error shows in the browser

**Comment by phil-davis** [comment]
@dpakach is core ``stable10`` OK or broken?

**Comment by dpakach** [comment]
@phil-davis  the links on `stable-10` work fine

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/3013 (carddav sync on KDE/Android doesn't work with latest version from git), https://github.com/owncloud/core/issues/4626 ([5.0.11RC1] Versions don't work properly), https://github.com/owncloud/core/issues/1911 (after newest update all linked storage pages don't work anymore), https://github.com/owncloud/core/issues/1834 (Versions not working properly ), and https://github.com/owncloud/core/issues/2111 (5.0 RC2 : app version not working).

**Comment by phil-davis** [comment]
The "problem" here is that the links go to version 11.0 URLs, e.g.:
```
https://doc.owncloud.org/server/11.0/go.php?to=admin-backup
```
and those do not work in real life until version 11 is actually close to release and the documentation is put online.

IMO this is not a real error.

**Comment by davitol** [comment]
Not a bug, IMHO. Let's close the ticket
