### ISSUE TITLE
Print a warning when ad-blockers are breaking sharing functions?

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/core#33642]
Look at https://github.com/owncloud/core/issues/33579 for motivation.

In short: for days I was investigating where the sharing functionalities have gone. They disappeared out of a sudden. Until I realised my ad-blocker (uBlock Origin) was the cause.

In this ticket I suggest to implement an ad-block detection and to print a warning. That would have saved me lots of hours and will for others too in future.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/13402 (... broken), https://github.com/owncloud/core/issues/7116 (Gallery sharing broken with encryption), https://github.com/owncloud/core/issues/12096 (OC\Share\Share::shareItem( .. ) Break on re-sharing), https://github.com/owncloud/core/issues/16651 (Unclear quota warning for shared contend), and https://github.com/owncloud/core/issues/262 (Warnings are shown when using lostpassword function).

**Comment by ho4ho** [comment]
Contacts: https://github.com/owncloud/contacts/pull/663
Activity: https://github.com/owncloud/activity/issues/727
