### ISSUE TITLE
Prevent Market App from interfering the occ upgrade process

### ISSUE THREAD

**Issue by micbar** [owncloud/core#33648]
### Steps to reproduce
1. Setup a multi Server instance
2. Set the config parameter 'operation-mode' => 'clustered-instance'
3. Enable market app
4. Install an outdated Enterprise app, eg. user_ldap 0.11.0
5. Replace the user_ldap app with the latest one
6. Run occ upgrade.

### Expected behaviour
The upgrade process should do its job

### Actual behaviour
The upgrade process is unsuccessful due to the market app repair step

```occ upgrade -v
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2018-11-26T09:49:20+01:00 Set log level to debug
2018-11-26T09:49:20+01:00 Repair step: Repair MySQL database engine
2018-11-26T09:49:20+01:00 Repair step: Repair MySQL collation
2018-11-26T09:49:20+01:00 Repair info: All tables already have the correct collation -> nothing to do
2018-11-26T09:49:20+01:00 Repair step: Repair SQLite autoincrement
2018-11-26T09:49:20+01:00 Repair step: Repair orphaned reshare
2018-11-26T09:49:20+01:00 Repair step: Repair duplicate entries in oc_lucene_status
2018-11-26T09:49:20+01:00 Repair info: lucene_status table does not exist -> nothing to do
2018-11-26T09:49:20+01:00 Repair step: Upgrade app code from the marketplace
2018-11-26T09:49:20+01:00 Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
2018-11-26T09:49:20+01:00 Repair warning: Please install or update the following apps manually or disable them with:
occ app:disable user_ldap
2018-11-26T09:49:20+01:00 Repair warning: For manually updating, see https://doc.owncloud.org/server/10.0/go.php?to=admin-marketplace-apps
2018-11-26T09:49:20+01:00 OC\RepairException: Upgrade is not possible
2018-11-26T09:49:20+01:00 Update failed
2018-11-26T09:49:20+01:00 Maintenance mode is kept active
2018-11-26T09:49:20+01:00 Reset log level
```

### Server configuration
**Operating system**:
Ubuntu

**Web server:**
Apache

**Database:**
MySql

**PHP version:**
7.2

**ownCloud version:** (see ownCloud admin page)
10.0.9

# Background
Thes usage of the market app is generation many support requests. 
We ship it by default with our enterprise tarballs. The admins enable it, even if they are in a clustered setup. 

We already introduced the config parameter `operation.mode` to block the UI Buttons for "Install" and "upgrade" in the market app, if we are not on a single server instance.

It would be consistend, to prevent the interference from the market app to the cli upgrade process too.

# Proposed change

- we should not call the market app repair step if we are in clustered mode

I opened this issue for discussion. We had a lot of discussion on this topic in the support team

**Comment by micbar** [comment]
@DeepDiver1975 @PVince81

**Comment by DeepDiver1975** [comment]
Possible solution: add additional condition here 

https://github.com/owncloud/core/blob/94541035511af788053c32216d49b9dddf896313/lib/private/Repair/Apps.php#L155

**Comment by DeepDiver1975** [comment]
@PVince81 let's chat about the impact ... THX

**Comment by micbar** [comment]
@DeepDiver1975 Thank you for this quick response.

As I see, we already have a config switch to prevent this?

Correct me, if I'm wrong, but
I think we have a kind of overlapping features or a naming issue.
- 'upgrade.automatic-app-update' => false disables automatic updates on the cli
- 'operation.mode' => 'clustered-instance' disables the "Install" and "Update" buttons in the UI

Right?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/21407 (occ upgrade from console), https://github.com/owncloud/core/issues/17528 (Prevent closing upgrade page while upgrade in progress), https://github.com/owncloud/core/issues/26677 (occ upgrade fails with Sabre\VObject\Recur\NoInstancesException), https://github.com/owncloud/core/issues/11165 (occ upgrade is not catching errors), and https://github.com/owncloud/core/issues/12506 (Upgrade Prob).

**Comment by pmaier1** [comment]
In the [Release Notes](https://doc.owncloud.com/server/10.0/admin_manual/release_notes.html#added-mode-of-operations-to-differentiate-between-single-instance-or-clustered-setup) we explicitly state that there's no harm with the Market app when using `clustered-instance`. 

> It would be consistend, to prevent the interference from the market app to the cli upgrade process too.

I thought this would be the main point why we added the setting in the first place oO

Please sort this out.

**Comment by DeepDiver1975** [comment]
>  there's no harm with the Market app

there is no harm in the sense of nobody will be hurt .... :man_shrugging:

**Comment by micbar** [comment]
In this case, it has been the incompatibility of the user_ldap 0.12.0 app with oC 10.0.9.
