### ISSUE TITLE
Move stable10 to yarn

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33651]
Like https://github.com/owncloud/core/issues/29906 but keep the same lib versions we had in bower.json.

Since OC 10 is LTS and bower.json is EOL, we should move to yarn on stable10 as well.

@DeepDiver1975 FYI

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/30748 ([stable10] move linting from travis to drone), https://github.com/owncloud/core/pull/30728 ([Stable10] cleanup drone), https://github.com/owncloud/core/pull/29517 ([Stable10] Moving Posgres job from Jenkins to Drone), https://github.com/owncloud/core/pull/29908 (Migrate to yarn), and https://github.com/owncloud/core/pull/30026 (Migrate to yarn).

**Comment by DeepDiver1975** [comment]
> why we decided to revert

- all libs got auto updated
- release bundle contained to much unneeded files
