### ISSUE TITLE
Refactor command line related tests into multiple files

### ISSUE THREAD

**Issue by skshetry** [owncloud/core#33668]
Currently, there are two files related to `occ` or `commandline` related contexts. But, they are expected to grow. So, it would be better if we could refactor them into multiple files/contexts as we do currently on `api` or `webui` tests.  

At present, `CommandLine.php` has ~600 LOC and `OccContext` clocks at ~1000.

### Ways we could refactor:
1. Based on commands
2. ...

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/pull/33050 (Refactor tags feature files to multiple files), and https://github.com/owncloud/core/pull/33089 (Refactor api test for favorite files).

**Comment by phil-davis** [comment]
#34127 moved the remaining acceptance test step code out of ``CommandLine`` and into ``OccContext`` and ``TransferOwnershipContext``. This makes ``CommandLine`` trait be just the place that provides convenience wrapper methods for running commands, remembers the last command output and status, and provides methods for getting those.

Next step is to look at ``OccContext`` and see if it makes sense to split it into multiple contexts.
