### ISSUE TITLE
External Storage S3 - Very high Request

### ISSUE THREAD

**Issue by mmajer** [owncloud/core#33678]
Hi,
External Storage - S3 - has very high requests
2 Million every day!

I have an S3 bucket mounted on my Owncloud server with about 10 files in it. 
I do not do file activity, they are just archived.
The S3 folder is shared on clients but nobody uses it in this test phase

Owncloud Server 10.0.10

Database: MySQL

What it should be at?

Error in configuration?
Do clients force a rescan of all the folders?

<img width="1323" alt="schermata 2018-11-28 alle 11 57 24" src="https://user-images.githubusercontent.com/474668/49147516-37b82080-f305-11e8-94e3-5335cd1d59e0.png">
<img width="1425" alt="schermata 2018-11-28 alle 11 57 46" src="https://user-images.githubusercontent.com/474668/49147517-37b82080-f305-11e8-9767-18d190e01d46.png">

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/13147 (External Storage S3 Very High Requests), https://github.com/owncloud/core/issues/14371 (Issue adding S3 External Storage), https://github.com/owncloud/core/issues/10198 (External Only Storage), https://github.com/owncloud/core/issues/11156 (wrong Quota working with S3 Storage Backend (external)), and https://github.com/owncloud/core/issues/12666 (S3 external storage --- Could not resolve host).

**Comment by DeepDiver1975** [comment]
> The S3 folder is shared on clients but nobody uses it in this test phase

The clients are calling home for update detection. In case of s3 this results in a request to amazon to detect changes over there. This can result in quite some requests.

Still this amount is damn high. 

Please reopen this issue in https://github.com/owncloud/files_external_s3/issues - THX
