### ISSUE TITLE
Test with multiple local storages set up

### ISSUE THREAD

**Issue by skshetry** [owncloud/core#33679]
At present, we are only testing with a single storage set up. There are some Occ commands and scenarios that needs multiple local storages (eg: `files:scan` for specific users). 

Maybe, we could setup multiple local storages in the `BeforeScenario` or create specific steps for it.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/26943 ([enhancement] Support user authentication for local storage), and https://github.com/owncloud/core/pull/33257 (webUi test user setting language).

**Comment by phil-davis** [comment]
Creating steps for setting up a new local storage will be useful, I expect.
I guess that can be done with ``occ`` commands, so we can make those step(s) and first use them to test those ``occ`` commands.
Then they will be available for setting up storages to be used by other tests, like ``files:scan``

**Comment by phil-davis** [comment]
Local storage can also be set up in the webUI. Making webUI tests for that is already a separate issue #32852

**Comment by paurakhsharma** [comment]
Done in #33702 and #33738. Closing now.
