### ISSUE TITLE
review acceptance tests using "* with all mechanisms"

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#33689]
e.g. tests like `When user "user0" uploads file "filesForUpload/textfile.txt" to "/testquota.txt" with all mechanisms using the WebDAV API` do not need to run with both dav path, because the step already implicates that all dav/chunking possibilities get tested

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/pull/31516 (Acceptance test coding standard changes), and https://github.com/owncloud/core/pull/32559 (acceptance tests - stop uploading when receiving an error).
