### ISSUE TITLE
Files are being deleted from server side, without user request, with Version 10.0.10 

### ISSUE THREAD

**Issue by ricardoauada** [owncloud/core#33708]
Steps to reproduce
1.Mostly document files (xls, doc, ods…) simply disappear from the server repository. For owncloud it shows the files exist. But, uppon clicking over the file on the web, a not found message popup. Checking inside the server, the file does not exist.
2.After doing a files:scan, owncloud realizes the missing files and the desktop client synchronizes and deletes the local files.
3.At first we thought that it could be a antivirus bug. But we removed the antivirus app and it kept happining.

Expected behaviour
Files should not disappear

Actual behaviour
Files are disappering

Server configuration
Operating system: Debian 9.4

Web server: Apache/2.4.25 (Debian)

Database: Ver 10.1.26-MariaDB-0+deb9u1

PHP version: php7.0

ownCloud version: (see ownCloud admin page) 10.0.10.4

Updated from an older ownCloud or fresh install: updated from version 9

Where did you install ownCloud from: Owncloud site

Signing status (ownCloud 9.0 and above):

https://gist.github.com/ricardoauada/a103f917479fff5dcbc081a4354b6fe9
{
“system”: {
“instanceid”: “ockex6yv9ndr”,
“passwordsalt”: “REMOVED SENSITIVE VALUE”,
“secret”: “REMOVED SENSITIVE VALUE”,
“trusted_domains”: [
“drive.webcenter.com.br”
],
“datadirectory”: “/var/www/html/drive.webcenter.com.br/public_html/data”,
“overwrite.cli.url”: “http://drive.webcenter.com.br”,
“dbtype”: “mysql”,
“version”: “10.0.10.4”,
“dbname”: “webcenter”,
“dbhost”: “localhost”,
“dbtableprefix”: “oc_”,
“dbuser”: “REMOVED SENSITIVE VALUE”,
“dbpassword”: “REMOVED SENSITIVE VALUE”,
“logtimezone”: “America/Sao_Paulo”,
“installed”: true,
“default_language”: “pt_BR”,
“defaultapp”: “files”,
“preview_libreoffice_path”: “/usr/bin/libreoffice”,
“collabora”: “https://collabora.webcenter.com.br”,
“preview_office_cl_parameters”: " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
“knowledgebaseenabled”: false,
“enable_avatars”: true,
“allow_user_to_change_display_name”: true,
“user_backends”: [
{
“class”: “OC_User_IMAP”,
“arguments”: [
“{imap.webcenter.com.br:143/imap/notls}”
]
}
],
“memcache.local”: “\OC\Memcache\Redis”,
“filelocking.enabled”: “true”,
“memcache.locking”: “\OC\Memcache\Redis”,
“redis”: {
“host”: “localhost”,
“port”: 6379,
“timeout”: 0,
“password”: “REMOVED SENSITIVE VALUE”
},
“updatechecker”: false,
“loglevel”: 0,
“mail_from_address”: “REMOVED SENSITIVE VALUE”,
“mail_smtpmode”: “smtp”,
“mail_domain”: “REMOVED SENSITIVE VALUE”,
“tempdirectory”: “/tmp”,
“trashbin_retention_obligation”: 15,
“0”: 30,
“versions_retention_obligation”: 30,
“1”: “auto”,
“minimum.supported.desktop.version”: “1.7.0”,
“activity_expire_days”: 365,
“enabledPreviewProviders”: [
“OC\Preview\PNG”,
“OC\Preview\JPEG”,
“OC\Preview\GIF”,
“OC\Preview\BMP”,
“OC\Preview\XBitmap”,
“OC\Preview\MP3”,
“OC\Preview\TXT”,
“OC\Preview\MarkDown”,
“OC\Preview\Illustrator”,
“OC\Preview\Movie”,
“OC\Preview\MSOffice2003”,
“OC\Preview\MSOffice2007”,
“OC\Preview\MSOfficeDoc”,
“OC\Preview\OpenDocument”,
“OC\Preview\PDF”,
“OC\Preview\Photoshop”,
“OC\Preview\Postscript”,
“OC\Preview\StarOffice”,
“OC\Preview\SVG”,
“OC\Preview\TIFF”,
“OC\Preview\Font”
],
“maintenance”: false,
“appstore.experimental.enabled”: true,
“mail_smtphost”: “REMOVED SENSITIVE VALUE”,
“mail_smtpport”: “25”,
“theme”: “”,
“singleuser”: false
}
}

**List of activated apps:**

Enabled:
  - activity: 2.4.0
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.4.0
  - external: 1.2
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.1.0
  - market: 0.2.5
  - notifications: 0.3.5
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.3.1
  - updatenotification: 0.2.1
  - user_external: 0.4
Disabled:
  - encryption

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/20668 (Files are deleted from the server suddenly), https://github.com/owncloud/core/pull/29764 (Set version to 10.0.4), https://github.com/owncloud/core/issues/27274 (delete), https://github.com/owncloud/core/issues/10716 (File versions), and https://github.com/owncloud/core/issues/13824 (Delete File).

**Comment by davitol** [comment]
@ricardoauada Does the problem persists? This behavior was not spotted by other users, so it can be probably a server configuration issue, not related to ownCloud
