### ISSUE TITLE
Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes)

### ISSUE THREAD

**Issue by JedatKinports** [owncloud/core#33700]
### Expected behaviour
All directories should get synced.

### Actual behaviour
One directory (which has 10000+ files in the same directory) doesn't get synced.

### Steps to reproduce
1. I execute this command: owncloudcmd -u username -p password --trust --non-interactive /var/www/something/ https://myowncloudserver.domain.com

2. Then I get this error: 

```
11-29 09:25:17:163 [ info sync.csync.csync ]:   ## Starting remote discovery ##
11-29 09:25:17:163 [ info sync.accessmanager ]: 6 "PROPFIND" "https://cloud.mydomain.com/remote.php/dav/files/filesync/" has X-Request-ID "eecbc783-e450-4204-8510-117ced4e574a"
11-29 09:25:17:164 [ info sync.networkjob ]:    OCC::LsColJob created for "https://cloud.mydomain.com" + "" "OCC::DiscoverySingleDirectoryJob"
11-29 09:25:17:239 [ info sync.networkjob.lscol ]:      LSCOL of QUrl("https://cloud.mydomain.com/remote.php/dav/files/filesync/") FINISHED WITH STATUS "OK"
11-29 09:25:17:240 [ info sync.csync.updater ]: Checking for rename based on fileid 00227869ocpw2kdzfkgx
11-29 09:25:17:241 [ info sync.csync.updater ]: file: images, instruction: INSTRUCTION_NEW <<=
11-29 09:25:17:241 [ info sync.accessmanager ]: 6 "PROPFIND" "https://cloud.mydomain.com/remote.php/dav/files/filesync/images" has X-Request-ID "23660c82-4d0a-4e05-a319-5325dcab11a9"
11-29 09:25:17:241 [ info sync.networkjob ]:    OCC::LsColJob created for "https://cloud.mydomain.com" + "/images" "OCC::DiscoverySingleDirectoryJob"
11-29 09:30:17:321 [ warning sync.networkjob ]: Network job timeout QUrl("https://cloud.mydomain.com/remote.php/dav/files/filesync/images")
11-29 09:30:17:321 [ warning sync.networkjob ]: QNetworkReply::NetworkError(OperationCanceledError) "Connection timed out" QVariant(Invalid)
11-29 09:30:17:321 [ info sync.networkjob.lscol ]:      LSCOL of QUrl("https://cloud.mydomain.com/remote.php/dav/files/filesync/images") FINISHED WITH STATUS "OperationCanceledError Connection timed out"
11-29 09:30:17:321 [ warning sync.discovery ]:  LSCOL job error "Operation canceled" 0 QNetworkReply::NetworkError(OperationCanceledError)
11-29 09:30:17:321 [ warning sync.csync.updater ]:      opendir failed for images - errno 5
11-29 09:30:17:321 [ warning sync.engine ]:     ERROR during  csync_update :  "An error occurred while opening a folder images: Operation canceled"
11-29 09:30:17:326 [ info sync.database ]:      Closing DB "/var/www/path/uploads/._sync_e3c4d804bfac.db"
11-29 09:30:17:327 [ info sync.engine ]:        CSync run took  302200 ms
11-29 09:30:17:329 [ info sync.database ]:      Closing DB "/var/www/path/uploads/._sync_e3c4d804bfac.db"
```

### Server configuration

Operating system: 

Distributor ID: Debian
Description:    Debian GNU/Linux 9.4 (stretch)
Release:        9.4
Codename:       stretch

Web server: 

Server version: Apache/2.4.25 (Debian)
Server built:   2018-03-31T08:47:16

Database:

mysql  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

PHP version:

PHP 7.0.27-0+deb9u1 (cli) (built: Jan  5 2018 13:51:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.27-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies

ownCloud version:

10.0.8

### Client configuration

Client version:

`owncloudcmd -v`
ownCloud version 2.5.1 (build 10450)

Operating system:

Debian GNU/Linux 9 (stretch)

OS language:

English

Qt version used by client package (Linux only, see also Settings dialog):

Using Qt 5.10.1, built against Qt 5.10.1

Client package (From ownCloud or distro) (Linux only):

owncloud-client

Installation path of client:

/usr/bin/owncloudcmd

### Logs

Server log:

`{"reqId":"f1881c1c-c343-4d2d-bf36-7252a72a2167","level":3,"time":"2018-11-29T02:13:31+00:00","remoteAddr":"client_ip","user":"my_username","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/files\/filesync\/images","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) at \/var\/www\/owncloud\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#142"}`

We have increased the memory on our server from 2 GB to 12 GB and set the `memory_limit` to `-1` which is unlimited in the php.ini file. Rebooted the server, tried again and we still get the same message. There is almost 11 GB of unused memory on the server at the moment.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/8513 (Allowed memory size exhausted ), https://github.com/owncloud/core/issues/5428 (PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 40 bytes) in /home/httpd/html/owncloud/lib/db.php on line 1204), https://github.com/owncloud/core/issues/15876 (Allowed memory size of ... bytes exhausted), https://github.com/owncloud/core/issues/18051 (Memory exhausted), and https://github.com/owncloud/core/issues/19393 (Allowed memory size of 262144 bytes exhausted).

**Comment by JedatKinports** [comment]
@ownclouders thank you. I checked all the links you posted. Non of them was resolved or is different to my issue.

**Comment by PVince81** [comment]
Hmmm PDOStatement... I suspect it's from when the PROPFIND will read the directory from the oc_filecache (index) and stores the full list in memory. Strange that increasing PHP memory did not help.

**Comment by MU7L3Y** [comment]
I have just upgraded from 10.1.0 to 10.1.1 and now have a similar issue to this I think. I have tried increasing the PHP memory limit but it hasn't helped. I have changed it in my master, in htaccess and in user.ini but nothing works. I am unable to even load owncloud at this point. 10.1.0 worked just fine before. I am using client 2.5.4. If you want me to create my own issue I will....just thought I could add to this one though..

`{"reqId":"a64623fc-dfcd-4908-bdeb-6d3cfc288b92","level":3,"time":"2019-04-05T10:28:47+11:00","remoteAddr":"00000000","user":"xxxxx","app":"PHP","method":"PROPFIND","url":"\/cloud\/remote.php\/webdav\/","message":"Out of memory (allocated 10485760) (tried to allocate 729088 bytes) at \/home\/steelcad\/public_html\/cloud\/lib\/composer\/composer\/ClassLoader.php#444"}`

**Comment by PVince81** [comment]
the change in 10.1.1 was minimal and shouldn't affect any memory usage.

**Comment by MU7L3Y** [comment]
@PVince81 What can I look into then regarding the error?

**Comment by VicDeo** [comment]
@JedatKinports  did you increase the limit via apache/php.ini?
One of these blocks still might have precedence:
https://github.com/owncloud/core/blob/stable10/.htaccess#L42
https://github.com/owncloud/core/blob/stable10/.htaccess#L54

**Comment by VicDeo** [comment]
@MU7L3Y you have a different issue. In the original report the PHP script tried to allocate more RAM that it is allowed for scripts by the **memory_limit** config option. 
In your case `Out of memory` means that other processes ate all RAM and script didn't exceed the limit, but there is no spare  RAM on server to allocate. 
In common case it means that you should **decrease** memory limit. But I'd suggest to inspect the running processes for the memory leak.
