### ISSUE TITLE
setting of shared folder was lost.

### ISSUE THREAD

**Issue by YTS85205107** [owncloud/core#33710]
**Expected behaviour**

I enabled external storage plugin on owncloud, and I shared a folder to user.
After restarting the server, it should not affect the settings of the folder. (ex: shared folder to who)

**Actual behaviour**

After server maintenance and restart, owncloud is normal, but setting of folder all lost.

**Steps to reproduce**

1. Mapping external storage that use sftp type.
![2018-11-30_16h18_03](https://user-images.githubusercontent.com/32276008/49277130-90c9b500-f4bb-11e8-886f-bccab0e19509.png)

2. After found folder from external storage , I shared it to user.
![2018-11-30_16h20_11](https://user-images.githubusercontent.com/32276008/49278633-51519780-f4c0-11e8-8379-c5d4dba56694.png)

3. Server restart.

4. Although user can find this folder, but folder setting was lost, so when user upload document to this folder, he still can't see document from external storage.
![2018-11-30_16h23_17](https://user-images.githubusercontent.com/32276008/49278643-59a9d280-f4c0-11e8-993f-75c73e3e76f9.png)

**Server configuration**

Ubuntu 16.04
Owncloud 10.0.10

**Client configuration**

Owncloud client 2.5.1

**Other comments:**
It has happened fourth times, include server maintenance restart and abnormal restart, although owncloud can restart and work fine, but setting of shared folder was lost.

Last time , Server doesn't restart , then setting of shared folder still lost.

Thanks in advance.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @ownclouders, and @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/8357 (Restored Files Lose All Shared Info), https://github.com/owncloud/core/issues/11433 ([Sharing] Not possible to share after having shared a folder), https://github.com/owncloud/core/issues/10892 (Any possiblity to share a folder permanent ?), https://github.com/owncloud/core/issues/16871 (Force share a folder), and https://github.com/owncloud/core/issues/8636 (some data lost).

**Comment by YTS85205107** [comment]
Who can help ? I still encountered this issue.

**Comment by PVince81** [comment]
after step 1, did you click the cog icon and enabled "can share" ?

after step 2, if you refresh the page, is the share still there ?

the shares are stored in the oc_share table, can you search for it and observe what happens after restarting the server ? you can do  `select * from oc_share where file_target like '%test%'` to find the entry.

normally, a server restart should never affect anything. well, the only things that might be affected is data stored in memcache/redis, but the share information is not stored there so not sure how to explain this behavior

**Comment by YTS85205107** [comment]
Hi , @PVince81 

Thanks your reply.

After step 1 , I shared the folder to someone , and he can use it.
But sometimes , after server restart , the setting was loss.

Step 2 , if setting exist and after I refresh the page , the setting still exist.

This is oc_share table list , please check.
![2019-01-08_10h35_04](https://user-images.githubusercontent.com/32276008/50806316-12212c80-1331-11e9-9f93-6c970902327f.png)
