### ISSUE TITLE
when a user that is excluded from sharing tries to share something a success status is returned

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33733]
but actually the sharing does not happen (good)

### Steps to reproduce
1. create a user and put them in a group that is excluded from sharing
2. as the user, try to share a file or folder with another user or group

See the scenarios in PR #33732

### Expected behaviour
- the attempt to create the share should return an error status (e.g. 403 forbidden)
- the share should not be created

### Actual behaviour
- success status is returned (e.g. OCS status 100 and HTTP status 200)
- the share is not created (a good thing!)

### Server configuration
**Operating system**:
Ubuntu 18.04

**Web server:**
local PHP dev server

**Database:**
mySQL

**PHP version:**
7.1

**ownCloud version:** (see ownCloud admin page)
current master

The return statuses give the impression that the share has been created, when it should not have been created.

But the share creation is actually not done - which is "a good thing" - the server just seems to lie in the return status.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/10307 (Exclude Groups from Sharing), https://github.com/owncloud/core/issues/7272 (Exclude subfolder from sharing), https://github.com/owncloud/core/issues/31696 (Acceptance tests for exclude users from sharing changes), https://github.com/owncloud/core/pull/31490 (Exclude users from sharing if they are a member of any excluded group), and https://github.com/owncloud/core/issues/17346 (Exclude group from sharing after a share was created).

**Comment by phil-davis** [comment]
Looks like it is an acceptance test code problem. Found while refactoring some re-sharing scenarios in PR #35551

**Comment by phil-davis** [comment]
Fixed by fixing the acceptance test code - PR #35551
