### ISSUE TITLE
API/Acceptance test for chunked upload for file_versioning

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#33739]
see if chunking upload works correctly with file_versioning

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/31616 (Make more convenient chunking upload API acceptance test steps), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), and https://github.com/owncloud/core/pull/31620 (Provide summarized acceptance test chunking upload steps).
