### ISSUE TITLE
Test files:cleanup occ command

### ISSUE THREAD

**Issue by skshetry** [owncloud/core#33741]
Part of #33613 

This adds a test for `files:cleanup` occ command

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/33740 ([WIP] Test files:cleanup occ command), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), and https://github.com/owncloud/core/issues/33617 (Test files:scan occ command).

**Comment by skshetry** [comment]
Cannot be done as it requires DB for scenarios to be set.
