### ISSUE TITLE
Still a bug on isInternetConnectionWorking() SettingsController

### ISSUE THREAD

**Issue by StefanAtUeber** [owncloud/core#33762]
As already discussed two years ago in #19509 the https domain check in CheckSetupController->isInternetConnectionWorking() needs to be fixed. 

It has nothing to do with old packages: the https check on www.owncloud.org is invalid and will fail on every OS. There is no certificate anymore.

### Steps to reproduce
1. on every installation if config _has_internet_connection_ is not set. 

### Expected behaviour
No warning

### Actual behaviour
 The message appear "This server has no working Internet connection"

### Server configuration
**Operating system**:
Ubuntu 16.04 LTS & Ubuntu 18.04 LTS and more

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/19509 (bug on isInternetConnectionWorking()), https://github.com/owncloud/core/issues/14854 (some bugs), https://github.com/owncloud/core/issues/6806 (IE bugs), https://github.com/owncloud/core/issues/191 (Folder duplication bug still exists in 4.5.1a), and https://github.com/owncloud/core/issues/2393 (Bug in Calendar).

**Comment by StefanAtUeber** [comment]
Owncloud admins fixed the issue with those domains. www.owncloud.org has a valid certificate now.

**Comment by dingo35** [comment]
ping www.owncloud.org gives:
Name or service not known

Probably DNS configuration error ....
