### ISSUE TITLE
fileVersion failure in apiMain on master and stable10

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33792]
On master and stable10 I get this error:
```
  @smokeTest @skipOnStorage:ceph @files_primary_s3-issue-161
  Scenario Outline: Uploading a chunked file does create the correct version that can be restored                    # /srv/www/htdocs/owncloud/tests/acceptance/features/apiMain/fileVersions.feature:66                                                                                                                                                                                 
    Given using <dav-path> DAV path                                                                                  # FeatureContext::usingOldOrNewDavPath()
    When user "user0" uploads file "filesForUpload/davtest.txt" to "/textfile0.txt" in 2 chunks using the WebDAV API # FeatureContext::userUploadsAFileToWithChunks()
    And user "user0" uploads file "filesForUpload/lorem.txt" to "/textfile0.txt" in 3 chunks using the WebDAV API    # FeatureContext::userUploadsAFileToWithChunks()
    Then the version folder of file "/textfile0.txt" for user "user0" should contain "2" elements                    # FilesVersionsContext::theVersionFolderOfFileShouldContainElements()
    When user "user0" restores version index "1" of file "/textfile0.txt" using the WebDAV API                       # FilesVersionsContext::userRestoresVersionIndexOfFile()
    Then the content of file "/textfile0.txt" for user "user0" should be "Dav-Test"                                  # FeatureContext::contentOfFileForUserShouldBe()

    Examples:
      | dav-path |
      | old      |
        Failed asserting that 1 matches expected '2'.

--- Failed scenarios:

    /srv/www/htdocs/owncloud/tests/acceptance/features/apiMain/fileVersions.feature:76
```

this also happens on the commit that introduced this test from https://github.com/owncloud/core/pull/33743

strange that we didn't noticed this before.

this is blocking stable10/master PR including 10.1 related ones.

once fixed in both master and stable10 please rebase https://github.com/owncloud/core/pull/33302 and https://github.com/owncloud/core/pull/33785

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/31155 ([stable10] Backport of languages from master), https://github.com/owncloud/core/pull/32033 ([stable10] Backport of languages from master), https://github.com/owncloud/core/pull/32687 ([stable10] Backport of languages from master), https://github.com/owncloud/core/pull/32557 ([stable10] Backport of languages from master), and https://github.com/owncloud/core/issues/26488 (Fix 7.1.0RC4 test failures on master).

**Comment by phil-davis** [comment]
PRs #33793 and #33794 demonstrate 50% failure rate

**Comment by individual-it** [comment]
reopening because it happened again in https://drone.owncloud.com/owncloud/core/13305

**Comment by individual-it** [comment]
and in https://drone.owncloud.com/owncloud/core/13305

**Comment by phil-davis** [comment]
and in the merge commit drone run https://drone.owncloud.com/owncloud/core/13302/255
