### ISSUE TITLE
[master] Cannot upgrade from stable10 to master due to max-version

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33819]
As agreed in https://github.com/owncloud/core/pull/33360, we skip max-version check for the git and daily channel on install.

We should also do so when running `occ upgrade` and any related operations.

Currently upgrading from stable10 to master gives errors:
```
2018-12-07T14:19:21+00:00 Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.                                                                                                                               
2018-12-07T14:19:21+00:00 Repair warning: Please install or update the following apps manually or disable them with:
occ app:disable activity                                                                                                               
occ app:disable files_texteditor                                                                                                       
occ app:disable files_videoplayer                                                                                                      
occ app:disable market                                                                                                                 
occ app:disable notifications                                                                                                          
2018-12-07T14:19:21+00:00 Repair warning: For manually updating, see https://doc.owncloud.org/server/11.0/go.php?to=admin-marketplace-apps                                                                                                                                    
2018-12-07T14:19:21+00:00 OC\RepairException: Upgrade is not possible
2018-12-07T14:19:21+00:00 Update failed
```

@DeepDiver1975 FYI

**Comment by PVince81** [comment]
@phil-davis FYI, I think you observed this as well in CI

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @VicDeo.

Possibly related issues are https://github.com/owncloud/core/issues/1520 (Upgrade from stable45 to master broken), https://github.com/owncloud/core/issues/8973 (Lost permissions after upgrade from stable6 to master), https://github.com/owncloud/core/issues/31455 ([stable10][master] Session is not validated), https://github.com/owncloud/core/pull/32687 ([stable10] Backport of languages from master), and https://github.com/owncloud/core/pull/31155 ([stable10] Backport of languages from master).

**Comment by VicDeo** [comment]
https://github.com/owncloud/core/blob/master/lib/private/Updater.php#L111

**Comment by PVince81** [comment]
@VicDeo if quick fix, feel free to take over.

**Comment by PVince81** [comment]
Expected behavior is that if version.php contains "git" or "daily" as channel, we skip max-version check when installing or upgrading apps

**Comment by VicDeo** [comment]
@PVince81 >skip max-version check when installing or upgrading **apps**

we skip it currently.  `occ upgrade` is about upgrading core, not apps. 
Is it enough to adjust the repair step 
https://github.com/owncloud/core/blob/master/lib/private/Repair/Apps.php#L210

```
if ($hasBlockingIncompatibleApps || $hasBlockingMissingApps) {
			// fail
```

as follows ($channelDailyOrGit is a pseudocode):
```
if ($channelDailyOrGit 
	&&($hasBlockingIncompatibleApps || $hasBlockingMissingApps)
) {
			// fail
```

**Comment by PVince81** [comment]
@VicDeo that should do, yeah. only skip blocking incompatible apps. missing apps should still block
