### ISSUE TITLE
CardDAV REPORT /{addressbook} UID malformed

### ISSUE THREAD

**Issue by kurbar** [owncloud/core#33828]
### Steps to reproduce
1. Enable Contacts
2. Create a contact via Owncloud web interface in your addressbook
3. Try to download all contacts from the given addressbook via CardDAV REPORT

### Expected behaviour
I'm able to download correct VCARD objects.

### Actual behaviour
UID field in VCARD object is malformed

```
REPORT /remote.php/carddav/addressbooks/admin/contacts/5e478a41-c819-476a-b383-e15fa7b68482.vcf
...
BEGIN:VCARD
VERSION:3.0
FN:Ivan Smetchejov
UI5e478a41-c819-476a-b383-e15fa7b68482
TEL;TYPE=HOME,VOICE:56123123
REV:20181207T131456Z
ENVCARD
```

### Server configuration
**Operating system:** Docker

**Web server:** Docker

**Database:** Mysql

**PHP version:** 7.2

**ownCloud version:** 10.0.10.4

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** DockerHub

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
https://gist.github.com/kurbar/32d21ecc714bc1313c0b471bebf1480a

**The content of config/config.php:**
https://gist.github.com/kurbar/da7bcaf31c8b3402b334efe9738cc3df

**Comment by kurbar** [comment]
Moved issue to owncloud/contacts

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/9011 (Carddav error), https://github.com/owncloud/core/issues/5366 (addressbook selection), https://github.com/owncloud/core/issues/2688 (Addressbook Carddav Link is broken), https://github.com/owncloud/core/issues/23460 (Connection Report), and https://github.com/owncloud/core/issues/23375 (Addressbook sharing model).
