### ISSUE TITLE
fix uploads file with all mechanisms related snakeoil tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#33833]
running `When user "user0" uploads file "filesForUpload/textfile.txt" to "/testquota.txt" with all mechanisms using the WebDAV API`
and then checking with `And as "user0" file "/testquota.txt" should not exist` does not make sense because upload **with all mechanisms** created different files, see https://github.com/owncloud/core/blob/master/tests/acceptance/features/bootstrap/WebDav.php#L2007

**Comment by phil-davis** [comment]
``When...with all mechanisms`` steps have the implementation detail "hidden" in the test code underneath. But currently to test if the resulting files exist or not, the test scenario steps have to have knowledge of that implementation detail, and check for the correct set of file extensions that the ``When`` tries to upload.

IMO we need a step something like:
```
Then as "user0" all files like "/testquota.txt" that were uploaded with all mechanisms should [not|] exist
```
And maybe adjust the ``When`` step:
```
When user "user0" uploads file "filesForUpload/textfile.txt" to files named like "/testquota.txt" with all mechanisms using the WebDAV API
```

**Comment by individual-it** [comment]
> `When user "user0" uploads file "filesForUpload/textfile.txt" to files named like "/testquota.txt" with all mechanisms using the WebDAV API`

should we mention the appendix there?

**Comment by phil-davis** [comment]
It is not going to be "reasonable" to try and mention all the things that get added to the file name.
Maybe we could say:
```
When user "user0" uploads file "filesForUpload/textfile.txt" to file names based on "/testquota.txt" with all mechanisms using the WebDAV API
Then as "user0" all file names based on "/testquota.txt" that were uploaded with all mechanisms should [not|] exist
```
?
