### ISSUE TITLE
REPORT request with <oc:filter-files> cannot be limited in subfolder

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#33835]
### Steps to reproduce
1. favourite several files inside a folder 
2. run REPORT with `oc:filter-files` for `oc:favorite` on that subfolder and use `<oc:limit>` e.g.  `curl -u admin:admin -X REPORT http://localhost/owncloud-core/remote.php/dav/files/admin/simple-folder -d '<?xml version="1.0" encoding="UTF-8"?> <oc:filter-files xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns">   <a:prop><oc:favorite/></a:prop>  <oc:filter-rules>         <oc:favorite>1</oc:favorite>     </oc:filter-rules> <oc:search><oc:limit>2</oc:limit> </oc:search></oc:filter-files>' | xmllint --format - `

### Expected behaviour
one of following:
1. only 2 files are reported
2. message returned saying that search report is only available in the root folder of the user

### Actual behaviour
empty xml returned:
`<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"/>`

### Variations
doing a search REPORT on a subfolder: `curl -u admin:admin -X REPORT http://localhost/owncloud-core/remote.php/dav/files/admin/simple-folder -d '<?xml version="1.0" encoding="UTF-8"?> <oc:search-files xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns"> <oc:search> <oc:pattern>lorem</oc:pattern> </oc:search> </oc:search-files>' | xmllint --format -`
says: `<s:message>Search report only available in the root folder of the user</s:message>` :+1: 

having no limit set works fine ` curl -u admin:admin -X REPORT http://localhost/owncloud-core/remote.php/dav/files/admin/simple-folder -d '<?xml version="1.0" encoding="UTF-8"?> <oc:filter-files xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns">   <a:prop><oc:favorite/></a:prop>  <oc:filter-rules>         <oc:favorite>1</oc:favorite>     </oc:filter-rules> <oc:search> </oc:search></oc:filter-files>' | xmllint --format -` :+1: 

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache2
**Database:**
MySQL
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
11.0
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**Comment by individual-it** [comment]
btw. there are tests trying to test exactly this behaviour, but there are :snake: - :oil_drum: because `WebDav::checkFavoritedElementsPaginated` in `WebDav.php` does not pass `$limit` and `$offset` to `WebDav::reportFolder` nor does the check looks if to many entries get reported

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/21344 ([Feature Request] limit bandwidth), https://github.com/owncloud/core/issues/1749 (Feature request: security reports), https://github.com/owncloud/core/issues/3515 (Feature Request: Allow different permissions for Subfolder), https://github.com/owncloud/core/issues/7680 ([FEATURE REQUEST] Limit client accessibility), and https://github.com/owncloud/core/issues/29169 (Federation: Upload reports insufficient storage but we are far from any limit).

**Comment by individual-it** [comment]
closing, real reason seems to be  #33840
