### ISSUE TITLE
Persistent lock timeout value must be remaining time

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33846]
See https://github.com/owncloud/core/issues/33778

When querying the lock discovery, the timeout value should be the remaining time, not absolute time.

@DeepDiver1975 FYI as discussed

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/33778 (Persistent lock timeout value is "Second-" when not specified.), https://github.com/owncloud/core/pull/31651 (Adding persistent lock types to ILockingProvider), https://github.com/owncloud/core/issues/4564 (owncloud.log wrong time value for timezone), https://github.com/owncloud/core/issues/7903 (LDAP authentification problem after cache-time-to-live timeout), and https://github.com/owncloud/core/issues/9176 (Must disable locking with davfs2 when using owncloud).

**Comment by PVince81** [comment]
PR here, there were more issues than expected: https://github.com/owncloud/core/pull/34100
