### ISSUE TITLE
Multiple LDAP Failed Login Attempts for one failure

### ISSUE THREAD

**Issue by servomekanism** [owncloud/core#33853]
### Steps to reproduce
1. Setup two primary domain controllers (as with the usual best practices)
2. Configure OwnCloud to use ldap for both servers (using backup replica host for the second)
3. Attempt to do a failed login from the Web Interface
4. Monitor the login failures at the windows DC event viewer
5. You will notice 4 failed login attempts, instead of just one. Two failed logins for each DC

### Expected behaviour
One failed login attempt

### Actual behaviour
If for example, the domain policy is to have an account locked out after 3 failed login attempts, the account gets locked out immediately since 4 attempts are made.

### Server configuration
**Operating system**:
Debian 9 stable

**Web server:**
Apache

**Database:**
Mariadb

**PHP version:**
Latest 

**ownCloud version:** (see ownCloud admin page)
10.0.8 (stable)

**Updated from an older ownCloud or fresh install:**
No

**Where did you install ownCloud from:**
Download from the upstream from the sources.lst provided by owncloud

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/7803 (LDAP login produces multiple bind failed messages), https://github.com/owncloud/core/issues/31465 (Missing symfony event for failed login attempt), https://github.com/owncloud/core/issues/18014 (Failed to login), https://github.com/owncloud/core/issues/24743 (Failing login with LDAP users.), and https://github.com/owncloud/core/issues/8054 (LDAP login failes when number of search results is limited).

**Comment by servomekanism** [comment]
These issues aren't the same as the one reported here.
