### ISSUE TITLE
Update from 10.0.7 to 10.0.10 => OCP / OCA error

### ISSUE THREAD

**Issue by sccevents** [owncloud/core#33869]
I tried updating our server appliance with the web-based updater. That went through without any errors, at least I didn't see any. Afterwards the maintenance mode was still on and wouldn't turn itself off. I used putty to log in and turn off the maintenance mode. Afterwards I clicked the upgrade button shown on the login page. This resulted in the following error:

OCP\AppFramework\QueryException: Could not resolve OCA\Files_Sharing\Service\NotificationPublisher! Class OCA\Files_Sharing\Service\NotificationPublisher does not exist

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/10175 ([OC7.0.1] Update from 7.0.0 to 7.0.1 -> image preview), https://github.com/owncloud/core/issues/31425 (Updating from 10.0.7.2 to 10.0.8 failed), https://github.com/owncloud/core/issues/9799 (Update to 7.0 failed), https://github.com/owncloud/core/issues/28205 (Update to 10.0.2), and https://github.com/owncloud/core/issues/3700 (Error updating  to 5.0.7).

**Comment by sccevents** [comment]
I have managed to complete the upgrade, but only by disabling the files_:sharing app via console. Now I can log on again via browser. In the apps section, after switching to disabled apps, I find the File Sharing app with an activate button. Afterwards is prompts for an update of the app, which fails with the error message posted above/earlier.
Further, my files are not being shown in the browser, it shows only the loading icon turning and turning.
Using the console, I can find them in the directory .../owncloud/data/...

**Comment by sccevents** [comment]
[config_report_20181212.zip](https://github.com/owncloud/core/files/2671983/config_report_20181212.zip)

**Comment by PVince81** [comment]
maybe web updater ran into some timeout and didn't fully extract the new sources

please try downloading the 10.0.10 tarball from https://download.owncloud.org/community/owncloud-10.0.10.tar.bz2, backup the sources, then delete the old code (but keep "data" and "config" folders), then extract the tarbal.

cc @VicDeo

**Comment by sccevents** [comment]
That did the trick! Thanks for the help, very much appreciated!

**Comment by davitol** [comment]
Close as solved
