### ISSUE TITLE
webUIGeneralContext getProductName is gone

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33871]
but it is called by webUILoginContext getLoginSuccessPageTitle and getLoginFailedPageTitle

These are used in user_ldap test scenarios, which are failing.

The methods were removed in PR #33797

**Comment by phil-davis** [comment]
@individual-it ???

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/24488 (Owncloud.log goes crazy.), https://github.com/owncloud/core/issues/21266 (Redis server went away), https://github.com/owncloud/core/issues/16216 (Redis Server Went Away), https://github.com/owncloud/core/issues/16530 (The scrollbar is lost and you can't go down), and https://github.com/owncloud/core/issues/6470 (ampache gone in v6.0.0).
