### ISSUE TITLE
Allow admins to remove persistent locks

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#33886]
Currently persistent locks can only be removed by the lock owners.

It would be nice to also allow admins to remove such locks (aka "breaking the lock").
Prerequisite would be that admins also have access to the file through sharing.

Should subadmins also be able to unlock ?

@DeepDiver1975 @pmaier1

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/3260 (- Removed -), https://github.com/owncloud/core/issues/240 (--- Removed ---), https://github.com/owncloud/core/issues/5195 (Please allow Admins to masquerade as other users), https://github.com/owncloud/core/pull/31651 (Adding persistent lock types to ILockingProvider), and https://github.com/owncloud/core/issues/25307 (Allow admins to revoke authentication tokens).

**Comment by pmaier1** [comment]
I'm not sure whether this is needed. I would find it way more important to enable the file owners to unlock them as
a) it's their file and
b) they decide intentionally to unlock it.

**Comment by PVince81** [comment]
this only works for regular storages

for system-wide external storages there is no concept of file owner, so this would need to default to either everyone or just the admin.

**Comment by phil-davis** [comment]
This is "effectively" coming in 10.9.
https://github.com/owncloud/enterprise/issues/4328

https://github.com/owncloud/core/pull/38222

https://github.com/owncloud/docs/issues/3962

Any user(s) can be put into the "lock breakers" group and can unlock files of other users that they can "see" (have received a share for)

@pmaier1 is that enough? or should admins get a right to unlock any file, if they need to?

**Comment by pmaier1** [comment]
> @pmaier1 is that enough? or should admins get a right to unlock any file, if they need to?

Yes, nothing else planned. Coming with 10.9. Closing therefore.
