### ISSUE TITLE
[FR] Dont show disabled users in sharee user search

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#33882]
- When searching for sharees, I dont want to see disabled users

**Comment by phil-davis** [comment]
I think we have all the steps for enable/disable user and to check matching potential sharee lists in the API and webUI. So it should be quite easy to write a set of acceptance test features-scenarios to define and test this.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/1108 (Disable User / User inacitve), https://github.com/owncloud/core/issues/11121 (Disabled AD LDAP users show up in list of oC users), https://github.com/owncloud/core/issues/809 (Lock or disable users), https://github.com/owncloud/core/issues/5155 (Sharing dialog doesn't search for users), and https://github.com/owncloud/core/issues/23838 (Allow disabling of a single user).

**Comment by PVince81** [comment]
well well... it depends on expectation.

you could have a temporarily disabled user (holiday/sabbatical) but still want people to be able to share with them for when they're back.

users can also be temporarily disabled in case of security event, for example when their password was stolen and whenever the admin want to temporarily lock their account

@pmaier1

**Comment by phil-davis** [comment]
@pmaier1 feature to design, or close?

**Comment by pmaier1** [comment]
This works as designed currently as disabling users has more a temporary use case and should not be mixed up with user deprovisioning. Though, there might come a feature soon to hide disabled users for creating shares.
