### ISSUE TITLE
Memcache factory on CLI spams logs with info level 

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#33881]
### Steps to reproduce
1. Use memcache 
2. Use CLI / OCC
3.

### Expected behaviour
Not spamming logs with info level

### Actual behaviour
Lots of info level messages from https://github.com/owncloud/core/blob/master/lib/private/Memcache/Factory.php#L102 each time you run a command

owncloud 10

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mmattel.

Possibly related issues are https://github.com/owncloud/core/issues/17329 (Missing memcache class on CLI upgrade), https://github.com/owncloud/core/issues/16036 (DeleteOrphanedSharesJob spams log), https://github.com/owncloud/core/issues/25210 ([occ commands] Cannot set log level to minimum through occ command (CLI)), https://github.com/owncloud/core/issues/24829 ([occ commands] Cannot set log level to minimum through occ command (CLI)), and https://github.com/owncloud/core/issues/3401 (files_antivirus spams log in Daemon mode).

**Comment by pako81** [comment]
PR for moving the message to debug log level: https://github.com/owncloud/core/pull/34263
