### ISSUE TITLE
Direct link to Amazon S3 storage

### ISSUE THREAD

**Issue by Hubaxis7** [owncloud/core#33890]
I use the External storage module with Amazon S3. When I download or view (video mp4) a large file through the owncloud interface, I do not get a direct link to AWS S3, but have to wait a long time to start downloading/playing.

### Steps to reproduce
1. Connect AWS S3 through the External storage module.
2. To upload a large (1GB) file in Amazon S3.
3. To play a file in the owncloud folder from Amazon S3

### Expected behaviour
When you play and download files from Amazon S3, provide a direct link or route to the S3 bucket files.

### Actual behaviour
I assume that owncloud downloads files from AWS S3 to the cache before playing them.

### Server configuration
**Operating system**: Ubuntu Linux 16.04.1
**Web server:** Apache 2.4.37
**Database:**MariaDB
**PHP version:** 7.0.32-0ubuntu0.16.04.1
**ownCloud version:** 10.0.10 (stable)

**Updated from an older ownCloud or fresh install:** Updated

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**The content of config/config.php:**

```

```

**List of activated apps:**

```
Enabled:
  - activity: 2.4.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_clipboard: 0.7.1
  - files_external: 0.7.1
  - files_external_ftp: 0.2.0
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.2.5
  - notifications: 0.3.5
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_primary_s3
  - files_versions
  - user_external
```

**Using external storage:** local/Amazon S3/WebDAV/

**Are you using encryption:** no

### Client configuration
**Browser:** Chrome (latest)

**Operating system:** Windows 10 LTSB

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by PVince81** [comment]
There is some capability in the server to generate direct links as far as I remember, but is currently not used by the web UI. It would require the web UI to use the Webdav "downloadURL" property instead of the Webdav path.

Also this would not work for systems where the OC server is in an intranet where OC itself has access to Amazon but not the intranet users. Might need a config switch then.

**Comment by Hubaxis7** [comment]
> There is some capability in the server to generate direct links as far as I remember, but is currently not used by the web UI. It would require the web UI to use the Webdav "downloadURL" property instead of the Webdav path.

I 'll be pleased if you give me, more detailed information how to  configurate the server Ubuntu
+Owncloud to work with storage Amazon S3.

**Comment by PVince81** [comment]
For support or help with setup, see https://owncloud.org/help/

I'll keep this ticket open only as feature request for adding direct link support in the web UI.
