### ISSUE TITLE
Fedora 29 package repository missing

### ISSUE THREAD

**Issue by svde** [owncloud/core#33898]
On http://download.owncloud.org/download/repositories/10.0/owncloud/ the latest Fedora version supported is 28, while 29 has been released on 2018-10-30.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/24887 (APT repository broken. Missing package applianceruntime-se), https://github.com/owncloud/core/issues/20932 (Fedora 23 packages), https://github.com/owncloud/core/issues/23188 (Missing Centos 6 repositories for 9.X.X), https://github.com/owncloud/core/issues/21327 (ubuntu 14.04 server package missing /ocs-provider/), and https://github.com/owncloud/core/issues/14667 (wrong repository).

**Comment by PVince81** [comment]
@crrodriguez can you check ?

**Comment by crrodriguez** [comment]
> On http://download.owncloud.org/download/repositories/10.0/owncloud/ the latest Fedora version supported is 28, while 29 has been released on 2018-10-30.

Correct, Fedora 29 repos will be added on the next release/rebuild.

**Comment by svde** [comment]
Thanks for the explanation. Shall we keep this issue open until the next release / rebuild?
