### ISSUE TITLE
phan and phpstan used in core are out-of-date

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33902]
core ``Makefile`` mentions hard-coded ```phan``` and ``phpstan`` code analysis versions:
```
$(PHAN_BIN):
	cd build && curl -s -L https://github.com/phan/phan/releases/download/0.12.10/phan.phar -o phan.phar;

$(PHPSTAN_BIN):
	cd build && curl -s -L https://github.com/phpstan/phpstan/releases/download/0.10.3/phpstan.phar -o phpstan.phar;
```

These are out-of-date. This was noticed with #33851 (a ``doctrine/dbal`` minor version bump) where ``phpstan`` gets an "internal error": https://drone.owncloud.com/owncloud/core/13464/102
```
+ make test-php-phpstan
cd build && curl -s -L https://github.com/phpstan/phpstan/releases/download/0.10.3/phpstan.phar -o phpstan.phar;
php build/phpstan.phar analyse --memory-limit=2G --configuration=./phpstan.neon --level=0 apps core settings lib/private lib/public ocs ocs-provider
    0/1308 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%
  130/1308 [▓▓░░░░░░░░░░░░░░░░░░░░░░░░░░]   9%
  260/1308 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  19%
  390/1308 [▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░]  29%
  520/1308 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  39%
  650/1308 [▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░]  49%
  780/1308 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]  59%
  910/1308 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░]  69%
 1040/1308 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]  79%
 1170/1308 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░]  89%


 1300/1308 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░]  99%
 ------ -------------------------------------------------------------- 
  Line   apps/testing/lib/BigFileID.php                                
 ------ -------------------------------------------------------------- 
         Internal error: Call to undefined method                      
         PhpParser\Node\Scalar\String_::parseDocString()               
         Run PHPStan with --debug option and post the stack trace to:  
         https://github.com/phpstan/phpstan/issues/new                 
 ------ -------------------------------------------------------------- 

 [ERROR] Found 1 error                                                          

 1308/1308 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%make: *** [test-php-phpstan] Error 1
Makefile:221: recipe for target 'test-php-phpstan' failed 
```
The "internal error" goes away in a later version of ``phpstan``

- [ ] Bump the version of ``phan`` up to something current
- [x] Bump the versions of ``phpstan`` up to something current #33903
- [ ] sort out the dependencies stuff so that these analysis tools have their version control in a less-hardcoded place #33908

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/4774 (architecture: core apps should use OCP), https://github.com/owncloud/core/issues/20897 (OBS packages out of date), https://github.com/owncloud/core/issues/25587 (Owncloud Core), https://github.com/owncloud/core/pull/29778 (Unused use), and https://github.com/owncloud/core/issues/11703 ([master] Use MomentJS for expiration date calculations / locale).

**Comment by phil-davis** [comment]
These were moved in `vendor-bin` a long time ago and have proper `composer.json` files to control their versions.
