### ISSUE TITLE
Move behat and related acceptance test dependencies into vendor-bin

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33914]
PR #33908 creates the ``vendor-bin`` folder with various code style and code analysis utilities in it.

Move acceptance-test framework utilities to ``vendor-bin`` (Behat and whatever is associated with it)

That will reduce the amount of crud mixed in the main ``composer.json`` and that ends up in ``lib/composer``

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/33422 (Extend federation acceptance tests), and https://github.com/owncloud/core/pull/33506 (Adding more federation acceptance tests).

**Comment by phil-davis** [comment]
done
