### ISSUE TITLE
Add webUI test scenarios for trying to (re)share when user is in a group excluded from sharing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33918]
Issue #33824 added test scenarios for resharing when a user is in a group excluded from sharing. Those scenarios used APIs. But there seems to be some issue when attempting to do this on the webUI, and on the "Shared with You" page. That page gives the impression that you can reshare the received share.

Ref: https://github.com/owncloud/enterprise/issues/3037

- investigate manually to see what happens (e.g. can the sharing actually be done, or is it just that the webUI is showing misleading information)
- make webUI test scenarios to demonstrate the problem

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/33745 (Add tests for excluding group from receiving share), https://github.com/owncloud/core/issues/10307 (Exclude Groups from Sharing), https://github.com/owncloud/core/issues/17346 (Exclude group from sharing after a share was created), https://github.com/owncloud/core/pull/31490 (Exclude users from sharing if they are a member of any excluded group), and https://github.com/owncloud/core/issues/16346 (Exclude groups from sharing stops working when user is a member of multiple groups).

**Comment by phil-davis** [comment]
Note: this might be just an issue when guest users are involved (guest app installed/enabled)
But anyway, it would be useful to have some webUI resharing test scenarios.

**Comment by paurakhsharma** [comment]
> * investigate manually to see what happens (e.g. can the sharing actually be done, or is it just that the webUI is showing misleading information)

Only the share field is shoud but it is not possible to share. When the sharee name is typed no suggestion is shown.
