### ISSUE TITLE
SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('oc_db_user'@'%') does not exist`

### ISSUE THREAD

**Issue by WhistleMaster** [owncloud/core#33931]
### Steps to reproduce
1. Log to OwnCloud instance.
2. Create folder.
3. Share folder with a user.

### Expected behaviour
The folder should be shared with the user.

### Actual behaviour
`An exception occurred while executing 'INSERT INTO `oc_share` (`share_type`, `share_with`, `accepted`, `item_type`, `item_source`, `file_source`, `permissions`, `uid_initiator`, `uid_owner`, `file_target`, `stime`) VALUES(?, ?, 0, ?, ?, ?, ?, ?, ?, ?, ?)' with params [0, "my_test_user", "folder", 52022, 52022, 31, "admin", "admin", "\/CPM", 1545143465]: SQLSTATE[HY000]: General error: 1449 The user specified as a definer ('oc_db_user'@'%') does not exist`

### Server configuration
**Operating system**: Linux
**Web server:** Apache
**Database:** mysql
**PHP version:** 5.6.39
**ownCloud version:** 10.0.10.4
**Updated from an older ownCloud or fresh install:** from an older install
**Where did you install ownCloud from:** ftp
**Signing status (ownCloud 9.0 and above):** `No errors have been found.`

**The content of config/config.php:**
[config_report_20181218.txt](https://github.com/owncloud/core/files/2691009/config_report_20181218.txt)

**List of activated apps:** see above.
**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 64.0
**Operating system:** OS 10.14.2

#### Web server error log
N/A

#### ownCloud log (data/owncloud.log)
[owncloud.log](https://github.com/owncloud/core/files/2691050/owncloud.log)

#### Browser log
N/A

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @ownclouders, and @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/28840 (-Error-), https://github.com/owncloud/core/issues/15711 (SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress), https://github.com/owncloud/core/issues/14911 (SQLSTATE[HY000]: General error: 5 cannot rollback transaction - SQL statements in progress), and https://github.com/owncloud/core/issues/20697 (PDOException: SQLSTATE[HY000]: General error: 1 cannot commit transaction - SQL statements in progress).

**Comment by WhistleMaster** [comment]
The issue was related to a trigger in the DB. Fixed.
