### ISSUE TITLE
[10.1.0 Beta] SchemaException during upgrade to 10.1.0 beta

### ISSUE THREAD

**Issue by thommierother** [owncloud/core#33963]
### Steps to reproduce
1. Upgrading from 10.0.10 to 10.1.0 beta
2. cli upgrade with occ

### Expected behaviour
no schema exception

### Actual behaviour
Doctrine\DBAL\Schema\SchemaException

### Server configuration
Ubuntu 18.0.4. LTS

**Web server:**
Apache 2.4.x

**Database:**
MariaDB

**PHP version:**
7.2

**Where did you install ownCloud from:**
https://download.owncloud.org/community/testing/owncloud-10.1.0beta.tar.bz2

**Signing status (ownCloud 9.0 and above):**
signed

root@www:/var/www/dev/owncloud# sudo -u www-data php occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
2018-12-21T21:12:04+00:00 Set log level to debug
2018-12-21T21:12:04+00:00 Repair step: Upgrade app code from the marketplace
2018-12-21T21:12:04+00:00 Repair warning: Market app is unavailable for updating of apps. Please update manually, see https://doc.owncloud.org/server/10.1/go.php?to=admin-marketplace-apps
2018-12-21T21:12:04+00:00 Repair step: Repair MySQL database engine
2018-12-21T21:12:04+00:00 Repair step: Repair MySQL collation
2018-12-21T21:12:04+00:00 Repair info: All tables already have the correct collation -> nothing to do
2018-12-21T21:12:04+00:00 Repair step: Repair SQLite autoincrement
2018-12-21T21:12:04+00:00 Repair step: Repair orphaned reshare
2018-12-21T21:12:04+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2018-12-21T21:12:04+00:00 Repair info: removing duplicate entries from lucene_status
2018-12-21T21:12:04+00:00 Updating database schema
**2018-12-21T21:12:05+00:00 Doctrine\DBAL\Schema\SchemaException: The table with name 'owncloud_dev.oc_persistent_locks' already exists.**
2018-12-21T21:12:05+00:00 Update failed
2018-12-21T21:12:05+00:00 Maintenance mode is kept active
2018-12-21T21:12:05+00:00 Reset log level

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/28027 (Updating 10.0.0 to 10.0.1), https://github.com/owncloud/core/issues/9794 (Upgrade from 6.0.1), https://github.com/owncloud/core/issues/28331 (DB issues after upgrade from 9.1.5 to 10.0.2), https://github.com/owncloud/core/issues/18314 (Upgrade from 8.1.0 to 8.1.1), and https://github.com/owncloud/core/issues/28015 (Failed upgrade from Owncloud 10.0.0.1 to Owncloud 10.0.1).

**Comment by thommierother** [comment]
Correction: Upgrade was from **10.0.10.4**

**Comment by PVince81** [comment]
weird... that error message would mean that the migration for creating the persistent lock table runs twice ??

or did you downgrade the instance to 10.0.10 without restoring the DB backup ?

**Comment by davitol** [comment]
I have not been able to reproduce this issue, upgrade went fine for me and no Exceptions where shown during the upgrade

**Comment by thommierother** [comment]
If it is unreproducible, where can I read the structure/schema of the database how it was before the upgrade 10.0.10.4 >> 10.1 started. Just that I can re-create it manually and test it again...

**Comment by thommierother** [comment]
unreproducible, closed

**Comment by PVince81** [comment]
@thommierother can you please check the owncloud.log from back then if you still have it and see if you had any errors related to the foreign key ? I'm asking because of similar reports like https://github.com/owncloud/core/issues/34598

**Comment by thommierother** [comment]
ok, I'll take a look, but no guarantee that the issue from Dec/Jan is still in the logs as they are rotated ...

**Comment by PVince81** [comment]
unless they are rotated to trash I guess you could still unpack the old one ? :wink:

**Comment by thommierother** [comment]
@PVince81 I have the logs as a tar.gz here, where can I share them with you? I don't want to upload it to public github...

**Comment by PVince81** [comment]
you can send to pvince81 at owncloud dot com

**Comment by thommierother** [comment]
@PVince81 , during upgrade for the apps impersonate and guests on a test instance I saw the SchemaException again:

```
root@ruru:/var/www/owncloud2# sudo -u www-data php occ upgrade
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{"reqId":"W8vwUWmuAE4tK771xFdE","level":3,"time":"2019-03-06T15:07:30+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined variable: self at \/var\/www\/owncloud2\/core\/Command\/Upgrade.php#245"}
2019-03-06T15:07:30+00:00 Set log level to debug
2019-03-06T15:07:30+00:00 Turned on maintenance mode
{"reqId":"W8vwUWmuAE4tK771xFdE","level":0,"time":"2019-03-06T15:07:30+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"starting upgrade from 10.1.0.4 to 10.1.0.4"}
2019-03-06T15:07:30+00:00 Repair step: Upgrade app code from the marketplace
2019-03-06T15:07:30+00:00 Repair step: Repair MySQL database engine
2019-03-06T15:07:31+00:00 Repair step: Repair MySQL collation
2019-03-06T15:07:31+00:00 Repair info: All tables already have the correct collation -> nothing to do
2019-03-06T15:07:31+00:00 Repair step: Repair SQLite autoincrement
2019-03-06T15:07:31+00:00 Repair step: Repair orphaned reshare
2019-03-06T15:07:31+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2019-03-06T15:07:31+00:00 Repair info: lucene_status table does not exist -> nothing to do
2019-03-06T15:07:31+00:00 Updating database schema
{"reqId":"W8vwUWmuAE4tK771xFdE","level":0,"time":"2019-03-06T15:07:31+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: starting 20170101010100 from app core"}
{"reqId":"W8vwUWmuAE4tK771xFdE","level":0,"time":"2019-03-06T15:07:31+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: completed 20170101010100 from app core"}
{"reqId":"W8vwUWmuAE4tK771xFdE","level":0,"time":"2019-03-06T15:07:31+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: starting 20170101215145 from app core"}
{"reqId":"W8vwUWmuAE4tK771xFdE","level":0,"time":"2019-03-06T15:07:31+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: completed 20170101215145 from app core"}
{"reqId":"W8vwUWmuAE4tK771xFdE","level":0,"time":"2019-03-06T15:07:31+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: starting 20170111103310 from app core"}
{"reqId":"W8vwUWmuAE4tK771xFdE","level":0,"time":"2019-03-06T15:07:31+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: completed 20170111103310 from app core"}
{"reqId":"W8vwUWmuAE4tK771xFdE","level":0,"time":"2019-03-06T15:07:31+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: starting 20170213215145 from app core"}
{"reqId":"W8vwUWmuAE4tK771xFdE","level":0,"time":"2019-03-06T15:07:32+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: completed 20170213215145 from app core"}
{"reqId":"W8vwUWmuAE4tK771xFdE","level":0,"time":"2019-03-06T15:07:32+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: starting 20170214112458 from app core"}
{"reqId":"W8vwUWmuAE4tK771xFdE","level":3,"time":"2019-03-06T15:07:32+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Schema\\\\SchemaException\",\"Message\":\"The table with name 'owncloud2.oc_accounts' already exists.\",\"Code\":20,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/Schema.php(132): Doctrine\\\\DBAL\\\\Schema\\\\SchemaException::tableAlreadyExists('owncloud2.oc_ac...')\\n#1 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/Schema.php(340): Doctrine\\\\DBAL\\\\Schema\\\\Schema->_addTable(Object(Doctrine\\\\DBAL\\\\Schema\\\\Table))\\n#2 \\\/var\\\/www\\\/owncloud2\\\/core\\\/Migrations\\\/Version20170214112458.php(11): Doctrine\\\\DBAL\\\\Schema\\\\Schema->createTable('oc_accounts')\\n#3 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/DB\\\/MigrationService.php(411): OC\\\\Migrations\\\\Version20170214112458->changeSchema(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema), Array)\\n#4 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/DB\\\/MigrationService.php(366): OC\\\\DB\\\\MigrationService->executeStep(20170214112458)\\n#5 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/Updater.php(301): OC\\\\DB\\\\MigrationService->migrate()\\n#6 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/Updater.php(255): OC\\\\Updater->doCoreUpgrade()\\n#7 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/Updater.php(112): OC\\\\Updater->doUpgrade('10.1.0.4', '10.1.0.4')\\n#8 \\\/var\\\/www\\\/owncloud2\\\/core\\\/Command\\\/Upgrade.php(261): OC\\\\Updater->upgrade()\\n#9 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/composer\\\/symfony\\\/console\\\/Command\\\/Command.php(255): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(953): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(248): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#12 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(148): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#13 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/Console\\\/Application.php(161): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#14 \\\/var\\\/www\\\/owncloud2\\\/console.php(106): OC\\\\Console\\\\Application->run()\\n#15 \\\/var\\\/www\\\/owncloud2\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud2\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/SchemaException.php\",\"Line\":109}"}
2019-03-06T15:07:32+00:00 Doctrine\DBAL\Schema\SchemaException: The table with name 'owncloud2.oc_accounts' already exists.
2019-03-06T15:07:32+00:00 Update failed
2019-03-06T15:07:32+00:00 Maintenance mode is kept active
```

**Comment by PVince81** [comment]
the error about oc_persistent_locks seemed to be more common.

really weird that it would try to re-run core migrations when just upgrading apps ?!

@thommierother can you post the contents of the oc_migrations table ?

**Comment by thommierother** [comment]
-- phpMyAdmin SQL Dump
-- version 4.8.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Erstellungszeit: 06. Mrz 2019 um 16:21
-- Server-Version: 5.7.25-0ubuntu0.18.04.2
-- PHP-Version: 7.2.15-0ubuntu0.18.04.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Datenbank: `owncloud2`
--

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `oc_migrations`
--

CREATE TABLE `oc_migrations` (
  `app` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `version` varchar(255) COLLATE utf8mb4_bin NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED;

--
-- Daten für Tabelle `oc_migrations`
--

INSERT INTO `oc_migrations` (`app`, `version`) VALUES
('core', '13000Date20170705121758'),
('core', '13000Date20170718121200'),
('core', '13000Date20170814074715'),
('core', '20170101010100'),
('core', '20170101215145'),
('core', '20170111103310'),
('core', '20170213215145'),
('oauth2', '20161122085340'),
('oauth2', '20170329194544'),
('oauth2', '20170724162518');

--
-- Indizes der exportierten Tabellen
--

--
-- Indizes für die Tabelle `oc_migrations`
--
ALTER TABLE `oc_migrations`
  ADD PRIMARY KEY (`app`,`version`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by PVince81** [comment]
huh, what are these ? `13000Date20170705121758`

**Comment by thommierother** [comment]
... no idea ...

**Comment by PVince81** [comment]
looks like some kind of formatting fail... this could be the reason for your issues: maybe during setup time, it used a wrong format when writing the migration timestamps into the DB. now during the upgrade, it used the correct format and saw that the migration entries were missing, so it runs them again...

**Comment by thommierother** [comment]
10.04 > 10.1 was the first upgrade on this database as far as I remember

**Comment by PVince81** [comment]
I guess for you a workaround would be to manually strip the prefix "13000Date" from those entries.

Is that all the entries ?

Normally there are way more.
This is my instance with 10.1.0:
```
+----------------------+----------------+
| app                  | version        |
+----------------------+----------------+
| activity             | 20161122085340 |
| activity             | 20161122092159 |
| activity             | 20170131134507 |
| activity             | 20170724182159 |
| activity             | 20181019151118 |
| activity             | 20181022150134 |
| core                 | 20170101010100 |
| core                 | 20170101215145 |
| core                 | 20170111103310 |
| core                 | 20170213215145 |
| core                 | 20170214112458 |
| core                 | 20170221114437 |
| core                 | 20170221121536 |
| core                 | 20170315173825 |
| core                 | 20170320173955 |
| core                 | 20170418154659 |
| core                 | 20170516100103 |
| core                 | 20170526104128 |
| core                 | 20170605143658 |
| core                 | 20170711191432 |
| core                 | 20170804201253 |
| core                 | 20170928120000 |
| core                 | 20171026130750 |
| core                 | 20180123131835 |
| core                 | 20180302155233 |
| core                 | 20180319102121 |
| core                 | 20180607072706 |
| core                 | 20181017105216 |
| core                 | 20181017120818 |
| core                 | 20181113071753 |
| dav                  | 20170116150538 |
| dav                  | 20170116170538 |
| dav                  | 20170202213905 |
| dav                  | 20170202220512 |
| dav                  | 20170427182800 |
| dav                  | 20170519091921 |
| dav                  | 20170526100342 |
| dav                  | 20170711193427 |
| dav                  | 20170927201245 |
| dav                  | 20180622095921 |
| encryption           | 20170913113840 |
| federatedfilesharing | 20170804201125 |
| federatedfilesharing | 20170804201253 |
| files_external       | 20170814051424 |
| files_sharing        | 20170804201125 |
| files_sharing        | 20170804201253 |
| files_sharing        | 20170830112305 |
| files_sharing        | 20171115154900 |
| files_sharing        | 20171215103657 |
| files_trashbin       | 20170804201125 |
| files_trashbin       | 20170804201253 |
+----------------------+----------------+
```

**Comment by thommierother** [comment]
owncloud2 is is only a devel system with not much practical use and no active sync clients. On the productive system I have similar entries as in your db

**Comment by thommierother** [comment]
even without th Date prefixes, Still

```
019-03-06T15:32:40+00:00 Repair step: Repair orphaned reshare
2019-03-06T15:32:40+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2019-03-06T15:32:40+00:00 Repair info: lucene_status table does not exist -> nothing to do
2019-03-06T15:32:40+00:00 Updating database schema
2019-03-06T15:32:40+00:00 Doctrine\DBAL\Schema\SchemaException: The table with name 'owncloud2.oc_accounts' already exists.
2019-03-06T15:32:40+00:00 Update failed
2019-03-06T15:32:40+00:00 Maintenance mode is kept active
2019-03-06T15:32:40+00:00 Reset log level
```
But why the complaint about oc_accounts?

**Comment by PVince81** [comment]
the accounts table is created in this migration https://github.com/owncloud/core/blob/stable10/core/Migrations/Version20170214112458.php#L11

I don't see in your oc_migrations table, so OC believes that this migration has not run yet and runs it. This is how the logic works.

What I don't understand is how you managed to have that many missing migrations. The oc_accounts table first appeared around OC 10.0beta2.

**Comment by thommierother** [comment]
I don't remember exactly which build first created this owncloud2 database. My productive system started around OC 8, the devel systems around 9 and 10.0.x (owncloud2), maybe a beta.

**Comment by PVince81** [comment]
strange thing, there are no migrations with the timestamps from:
```
('core', '13000Date20170705121758'),
('core', '13000Date20170718121200'),
('core', '13000Date20170814074715'),
```

not even in apps

**Comment by thommierother** [comment]
stale, no longer relevant, closed
