### ISSUE TITLE
[10.1.0 Beta] Translation missing in new user mail

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/core#33962]
### Steps to reproduce
1. Set the default langauge to Deutsch (Persönlich) or Deutsch (Förmlich: Sie)
2. Create a new user with Name and email address
3. Open the email

### Expected behaviour
The text is translated to german

### Actual behaviour
The mail text is not fully translated

<img width="639" alt="translation_issue" src="https://user-images.githubusercontent.com/33026403/50356480-5dc29080-0552-11e9-8802-26403ec96bae.png">

### Server configuration
**ownCloud version:**
10.1.0 Beta

**Comment by ChrisEdS** [comment]
This string is not in Transifex?https://github.com/owncloud/core/blob/7f5a9d841b69fc2603091bb12d89e86da80ecb7f/settings/templates/email.new_user.php#L15

**Comment by PVince81** [comment]
we need to backport the translations, see https://github.com/owncloud/core/issues/33454

it's not straightforward as master is using a separate repo for user management UI

**Comment by ChrisEdS** [comment]
Tested. Fixed!

Thank you.
