### ISSUE TITLE
acceptance test share expiry date test fails

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#33975]
When an acceptance test scenario creates a share, the share expiry date might be set automatically (e.g. by a rule in some app like files_classifier that sets the expiry date some number of days into the future relative to the current server date) or might be specified with a relative date (e.g. ``+42 days``). When the server time is close to midnight, and/or when the local time for the test runner script is enough different to the time on the server-under-test, or... then the test runner script cannot assume that its local date is the date that the server used when creating the share and calculating the share expiry date.

This results in intermittent test fails, particularly in nightly automated test runs. e.g. the scenario creates the share at 23:59:59 seconds, the share is created with an expiry date that is +60 days, the scenario step that later checks the share information happens at 00:00:01 on the "next day" and sees that the share expiry is only +59 days in the future.

Do something to help with this - perhaps somehow remember the share creation date?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/pull/32701 (Add test steps to create a public share with an expiry date), and https://github.com/owncloud/core/pull/32699 (Add test steps to create a public share with an expiry date).

**Comment by phil-davis** [comment]
This should be fixed by PR #33978 It is a rare event anyway. Closing here, if we see it again then open another issue.
