### ISSUE TITLE
[10.1.0 Beta] files_clipboard not compatible, is app still needed at all?

### ISSUE THREAD

**Issue by thommierother** [owncloud/core#33973]
### Steps to reproduce
1. upgrade from 10.0.10 through occ
2. error message

```
In app.php line 1170:                                                                                                                                       
  App "Files clipboard" cannot be installed because the following dependencies are not fulfilled: ownCloud 10.0 or lower is required.
```
Question: This apps repo has not seen any activity since april 2018 (see https://github.com/leizh/owncloud-files_clipboard). Is it still needed or is the functionality already included elsewhere in the core apps? As far as I can guess, the metadata seem to be outdated too ...

### Expected behaviour
upgrade successful

### Actual behaviour
error message, files_clipboard has to be disabled to perform upgrade

### Server configuration
Ubuntu 18.04 LTS

**Web server:**
Apache 2.4.x

**Database:**
MariaDB

**PHP version:**
7.2

**ownCloud version:** (see ownCloud admin page)
10.1.0 beta

**Updated from an older ownCloud or fresh install:**
updated fro 10.0.10

**Application**
https://marketplace.owncloud.com/apps/files_clipboard
https://github.com/leizh/owncloud-files_clipboard/issues

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/1861 ([5.0 beta 1] can't enable or disable apps), https://github.com/owncloud/core/issues/33962 ([10.1.0 Beta] Translation missing in new user mail), https://github.com/owncloud/core/issues/11996 (oc_properties, still needed ?), https://github.com/owncloud/core/issues/1853 ([5.0 beta 1] Music icon messed up), and https://github.com/owncloud/core/issues/1852 ([5.0 beta 1] Installing external apps fails).

**Comment by phil-davis** [comment]
I don't know if the app is still useful to you or anyone, but I see that it claims to work with core ``10.0`` - if that is true then because of semver it should work with any ``10.*`` release. I made PR https://github.com/leizh/owncloud-files_clipboard/pull/41 to fixup the ``max-version``.

**Comment by patrickjahns** [comment]
This app is not maintained in the owncloud github organization ( https://github.com/owncloud ) - please open issues with the author/maintainer:
https://github.com/leizh/owncloud-files_clipboard/issues

For more information on the versioning schema please see https://central.owncloud.org/t/owncloud-core-switching-to-semver-apps-need-re-release/17054
