### ISSUE TITLE
Disable updates and checks completely

### ISSUE THREAD

**Issue by AndreFabris** [owncloud/core#33974]
### Steps to reproduce
1. Setup owncloud on the local host on local machine and install some apps
2. Upload that to the production server and migrate database
3. Start owncloud

### Expected behaviour
Tell us what should happen - I would expect to be able to login and get to the home screen

### Actual behaviour
Tell us what happens instead
When I try to login, I get the following screen:
ownCloud will be updated to version 10.0.10
These apps will be updated:

WebDAV (dav)
Federated File Sharing (federatedfilesharing)
External storage support (files_external)
PDF Viewer (files_pdfviewer)
Share Files (files_sharing)
Deleted files (files_trashbin)
Gallery (gallery)
Market (market)
Music (music)
Notifications (notifications)
Collabora Online (richdocuments)

Please make sure that the database, the config folder and the data folder have been backed up before proceeding.

If I do update, it fails for unknown reason.

Now this is strange as on my development local machine this does not appear. But when I upload this to the server I have this problem.

I want to completely disable all checks and this screen too. Just ignore all new versions. The documentation shows various things that actually do not work:

// ‘updatechecker’ => true,
// ‘has_internet_connection’ => false,
// ‘upgrade.disable-web’ => true,
// ‘updater.server.url’ => ‘http://localhost’,
// ‘upgrade.automatic-app-update’ => false,
// ‘appstoreenabled’ => false,

I guess I need to skip this in code. Any ideas how and where to look?

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** mySQL

**PHP version:** 7.1

**ownCloud version:** (see ownCloud admin page) 10.4

**Updated from an older ownCloud or fresh install:** Fresh

**Where did you install ownCloud from:** Downloaded from official site

**Signing status (ownCloud 9.0 and above):** No idea what is this

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
I cannot log in due to issue described

**The content of config/config.php:**
Unchanged default settings - I am not coping my database credentials here
```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**
See the description above, all the apps that are to beupdated
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
any browser - Chrome Firefox
**Operating system:**
irrelevant to issue
#### Web server error log
```
Insert your webserver log here
```
There is nothing logged in. It reports error when I try to update, however that error is not displayed or logged

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...

No logs on the console

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/14073 (Add ability to disable HSTS completely), https://github.com/owncloud/core/issues/21366 (Update), https://github.com/owncloud/core/issues/20661 (Update), https://github.com/owncloud/core/issues/28265 (Hi,), and https://github.com/owncloud/core/issues/29158 (Dear Support, ).

**Comment by AndreFabris** [comment]
Just a few lines in logs:
{"reqId":"o3gDlm6zDTzKG6mw0urg","level":3,"time":"2018-12-26T14:58:38+00:00","remoteAddr":"217.101.24.91","user":"--","app":"index","method":"GET","url":"\/myfiles\/index.php\/core\/js\/oc.js?v=7e063d1840d924df284ea6b94f01f2a6","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/app.php(127): OC_App::loadApp('dav')\\n#1 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/util.php(147): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/base.php(908): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/html\\\/myfiles\\\/index.php(54): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":191}"}
{"reqId":"G2uu9gdxwawaHf0arFm9","level":3,"time":"2018-12-26T14:58:50+00:00","remoteAddr":"217.101.24.91","user":"--","app":"index","method":"GET","url":"\/myfiles\/index.php\/core\/js\/oc.js?v=7e063d1840d924df284ea6b94f01f2a6","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/app.php(127): OC_App::loadApp('dav')\\n#1 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/util.php(147): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/base.php(908): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/html\\\/myfiles\\\/index.php(54): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":191}"}
{"reqId":"xjXFeJLQBPynhaNawH67","level":3,"time":"2018-12-26T15:10:05+00:00","remoteAddr":"217.101.24.91","user":"--","app":"index","method":"GET","url":"\/myfiles\/index.php\/core\/js\/oc.js?v=7e063d1840d924df284ea6b94f01f2a6","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/app.php(127): OC_App::loadApp('dav')\\n#1 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/util.php(147): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/base.php(908): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/html\\\/myfiles\\\/index.php(54): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":191}"}
{"reqId":"BkA4sctjLCoStEGaRsB5","level":3,"time":"2018-12-26T15:15:57+00:00","remoteAddr":"217.101.24.91","user":"--","app":"index","method":"GET","url":"\/myfiles\/index.php\/core\/js\/oc.js?v=7e063d1840d924df284ea6b94f01f2a6","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/app.php(127): OC_App::loadApp('dav')\\n#1 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/util.php(147): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/base.php(908): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/html\\\/myfiles\\\/index.php(54): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":191}"}
{"reqId":"r8I7UncjROsBI23Wmf1y","level":3,"time":"2018-12-26T15:15:58+00:00","remoteAddr":"217.101.24.91","user":"--","app":"index","method":"GET","url":"\/myfiles\/index.php\/core\/js\/oc.js?v=7e063d1840d924df284ea6b94f01f2a6","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/app.php(127): OC_App::loadApp('dav')\\n#1 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/util.php(147): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/base.php(908): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/html\\\/myfiles\\\/index.php(54): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":191}"}
{"reqId":"wHLD2u71f1rySvAEdzhr","level":3,"time":"2018-12-26T15:24:15+00:00","remoteAddr":"217.101.24.91","user":"--","app":"index","method":"GET","url":"\/myfiles\/index.php\/core\/js\/oc.js?v=7e063d1840d924df284ea6b94f01f2a6","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/app.php(127): OC_App::loadApp('dav')\\n#1 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/util.php(147): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/base.php(908): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/html\\\/myfiles\\\/index.php(54): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":191}"}
{"reqId":"fLxksIGZnS0ZtceFqNu1","level":3,"time":"2018-12-26T18:05:21+00:00","remoteAddr":"217.101.24.91","user":"--","app":"index","method":"GET","url":"\/myfiles\/index.php\/core\/js\/oc.js?v=7e063d1840d924df284ea6b94f01f2a6","message":"Exception: {\"Exception\":\"OC\\\\NeedsUpdateException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/app.php(127): OC_App::loadApp('dav')\\n#1 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/util.php(147): OC_App::loadApps(Array)\\n#2 \\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/base.php(908): OC_Util::setupFS()\\n#3 \\\/var\\\/www\\\/html\\\/myfiles\\\/index.php(54): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/myfiles\\\/lib\\\/private\\\/legacy\\\/app.php\",\"Line\":191}"}

**Comment by PVince81** [comment]
@AndreFabris can you try `occ upgrade` on the command line, I hope it will provide more useful information.

In general if you disabled all checks and updated from OC 10.0.x to 10.0.10, it should work fine as all apps should be compatible. What version are you upgrading from ?

Also make sure the source code of OC core is properly replaced (the old source code must be deleted, don't just extract the new tarball on top)

**Comment by davitol** [comment]
Close due to lack of info. @AndreFabris feel free to reopen if you can provide more info. Thanks for reproting

**Comment by AndreFabris** [comment]
@PVince81 I do not want to do any upgrades. I would like to keep the version and plugins exactly as I set them up. However the issue is that as admin user I am prevented from using owncloud if I do not do upgrades. I would like to completely ignore this and be able to use the app

**Comment by AndreFabris** [comment]
@davitol I am not sure what more info I can provide here.

**Comment by PVince81** [comment]
if you never do upgrades your system will eventually be vulnerable as OC and its dependencies solve them as they are found in future versions.

it is not recommended to stay on the same version forever

**Comment by AndreFabris** [comment]
I agree with you. However for the security and privacy reasons, we need to be in control when we update the software, and what updates do we implement. Forcing us to update is not good for us.
