### ISSUE TITLE
move acceptance tests for public upload/download into own context

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#33997]
part of #33690

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/pull/32740 (Acceptance test steps for public link share), https://github.com/owncloud/core/pull/32734 (Acceptance test steps for public link share), https://github.com/owncloud/core/pull/32559 (acceptance tests - stop uploading when receiving an error), https://github.com/owncloud/core/issues/22492 (test), and https://github.com/owncloud/core/issues/22485 (test).
