### ISSUE TITLE
move acceptance tests response xml parser to helper

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#33990]
`parseResponseIntoXml` in `WebDav.php` can go into a helper.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/33690 (cleanup acceptance tests WebDav trait), and https://github.com/owncloud/core/issues/24371 (XML parser error).
