### ISSUE TITLE
remove sabre from acceptance tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34000]
currently we are using sabre client and Guzzle in the acceptance tests, that makes it confusing and increases the complexity.
Mostly Guzzle is used, so we should only use Guzzle everywhere

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/240 (--- Removed ---), https://github.com/owncloud/core/issues/3260 (- Removed -), https://github.com/owncloud/core/pull/32769 (Make targets for acceptance tests), https://github.com/owncloud/core/pull/32347 (Add getters for private vars of acceptance test traits), and https://github.com/owncloud/core/pull/32559 (acceptance tests - stop uploading when receiving an error).
