### ISSUE TITLE
Build docker image owncloud 10.0.8 from sources

### ISSUE THREAD

**Issue by eorlovsky** [owncloud/core#34008]
Could you please help us identify correct Dockerfile to build docker image from sources? In particular, we look for v 10.0.8 but I think it should be generic for all 10.0 versions.  

Can we rely on a docker file available here
https://github.com/docker-library/owncloud/commits/master/10.0/apache/Dockerfile
?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/20647 (Problems installing ownCloud 8.0.X), https://github.com/owncloud/core/issues/32810 (OwnCloud Upgrade Issues 10.0.10), https://github.com/owncloud/core/issues/18209 (Upgrade to Owncloud 8.0.5), https://github.com/owncloud/core/issues/23183 (owncloud upgrade from 8.2.2 to 9.0.0 fails), and https://github.com/owncloud/core/issues/12620 (User Management - ownCloud 8.0).

**Comment by PVince81** [comment]
maybe check https://github.com/owncloud-docker/ or ask on central for advice
