### ISSUE TITLE
Static tags are shown in the searchbox "Select tags to filter by" even when they do not belong to the user's group

### ISSUE THREAD

**Issue by davitol** [owncloud/core#34002]
### Steps to reproduce

1. Create admin user followed by users user1, user2, user3 and user4.
2. Create 2 groups group1 and group2. user1 and user2 belong to group1. And user3 belong to group2. user4 belongs to group1 and group2.
3. Now create 4 tags
    - visibleTag of type Visible  
    - restrictedTag of type Restricted and add group1 to it  
    - staticTag of type Static and add group2 to it  
    - invisibleTag of type Invisible  

4. Login to user1

### Expected behaviour

The users will see restrictedTag and visibleTag.
The static tag should not be visible for users of group1

### Actual behaviour

The static tag is shown in the search box

<img width="1278" alt="screen shot 2019-01-02 at 10 31 48" src="https://user-images.githubusercontent.com/10596560/50586713-0fc75a00-0e7b-11e9-8178-1b2f5c881d4d.png">

**Note:** The behavior is fine in the sidebar for assigning tags to a file. The static tag is not shown there.

<img width="387" alt="screen shot 2019-01-02 at 10 38 47" src="https://user-images.githubusercontent.com/10596560/50586741-36859080-0e7b-11e9-8d60-422ad48c9c87.png">

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1

**ownCloud version:**

ownCloud 10.1. beta version

```
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.1.0.1","versionstring":"10.1.0 beta","edition":"Enterprise","productname":"ownCloud"}
```

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No
**Logs**

```
```

### Client configuration

**browser**

Firefox

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/15818 (admin should not be able to select ldap groups for users), https://github.com/owncloud/core/issues/9332 (Searching causes all groups to disappear even when users are present.), https://github.com/owncloud/core/issues/11446 (User can't see all selected groups  when configuring LDAP Group filter tab), https://github.com/owncloud/core/issues/20470 (A yellow warning should be shown when creating a user/group that already exists), and https://github.com/owncloud/core/issues/22175 (LDAP users belonging to group sometimes not showing OC 8.2.2).

**Comment by davitol** [comment]
cc @sharidas JFYI

**Comment by sharidas** [comment]
It tries to get the list from request `remote.php/dav/systemtags`. I think it would be better to fix it in the `apps/systemtags/js/systemtagsfilelist.js`.

**Comment by sharidas** [comment]
Created PR : https://github.com/owncloud/core/pull/34007
- [ ] JS unit test
