### ISSUE TITLE
[Feature Request] button to force mount rescan in GUI

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#34010]
If you have an external (personal) mount, it would be great to have the possibiliy to manually force a rescan of the current mount or mount/current_folder with an additional entry in the action list below.

![image](https://user-images.githubusercontent.com/3321281/50607580-fc8fab00-0ec9-11e9-869b-b0f7db2514af.png)

 It should behave in the same way like you run the command (example):
`sudo -uwww-data ./occ files:scan --path="user_x/files/external_mount_name/folder_name"`

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/12530 (Feature Request), https://github.com/owncloud/core/issues/8569 (Feature requests), https://github.com/owncloud/core/issues/20661 (Update), https://github.com/owncloud/core/issues/21366 (Update), and https://github.com/owncloud/core/issues/29873 ([Feature Request] Mark mount as read only in the mount settings).

**Comment by PVince81** [comment]
this would need to trigger a background job for rescanning
also means not compatible with "save credentials in session" mode as the bkg job wouldn't be able to connect, so the menu item should only be visible when it makes sense

**Comment by mmattel** [comment]
Questions:
- The current occ documentation about files:scan does not mention any limitation for scanning regarding „save credentials in session“. Do we need to adopt the content to reflect that?
- In case yes, it would be good to also reflect that somehow in occ files_external:list for easy identification if a mount point has fixed or session credentials as the latter would not be scannable by occ.
- For my better understanding, is or would there be a difference in between the occ command and a backgroundjob?

**Comment by PVince81** [comment]
the doc in question should already be in https://github.com/owncloud/documentation/pull/4283

**Comment by PVince81** [comment]
also, no difference between bkg job and cron. The point is that there is no user session active in any of these two, so whatever credentials stored in "whatever session" is not accessible.

**Comment by mmattel** [comment]
Thanks, I will check and see if we add a link in the occ files:scan descriptoin to the known limitations you referenced, might be helpful.
