### ISSUE TITLE
oC10: Unallow install on PostgreSQL 10+

### ISSUE THREAD

**Issue by ho4ho** [owncloud/core#34026]
Check this while installation?

> The fix for doctrine/dbal is released with v2.7.0 that requires PHP 7.1+
> Unfortunately we need keep ownCloud 10.0.x PHP 5.6 compatible
> Thus we can't update doctrine/dbal library to support Postgres 10 for ownCloud 10.0.x.
> https://github.com/owncloud/core/issues/29342#issuecomment-444644391

See:

https://github.com/owncloud/core/issues/29342#issuecomment-387388589, https://github.com/owncloud/core/issues/29342#issuecomment-444644391, https://github.com/owncloud/core/issues/31320#issuecomment-385896511, https://github.com/owncloud/core/issues/31424#issuecomment-388351691, https://github.com/owncloud/core/issues/31334, https://github.com/owncloud/core/issues/31320, https://github.com/owncloud/core/issues/29997, https://github.com/owncloud/docs/issues/490

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/12518 (IIS + postgresql install issue), https://github.com/owncloud/core/issues/29787 (OC 10.0.4 & Postgresql 10), https://github.com/owncloud/core/issues/29088 (Can't install), https://github.com/owncloud/core/issues/31320 (Upgrade to 10.0.8 on PostgreSQL 10.x), and https://github.com/owncloud/core/issues/13541 (Install wizard - no predefined database/user possible (postgresql)).

**Comment by PVince81** [comment]
what happens if postgres gets updated in an existing install ?

seems we'd need to check this in other code paths as well

**Comment by flat1701** [comment]
PG10 changes pseudo columns for sequences.

/var/www/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php

            $sequenceName = $sequence['relname'];
        }

- $data = $this->_conn->fetchAll('SELECT min_value, increment_by FROM ' . $this->_platform->quoteIdentifier($sequenceName));
+ $data = $this->_conn->fetchAll("SELECT min_value, increment_by FROM pg_sequences WHERE sequencename = '" . $sequenceName . "'");

        return new Sequence($sequenceName, $data[0]['increment_by'], $data[0]['min_value']);

**Comment by VicDeo** [comment]
Postgre 10 is supported since owncloud 10.4.0
Closing
