### ISSUE TITLE
OC 10.0.10 SMB & SFTP does not work at all

### ISSUE THREAD

**Issue by uptown1** [owncloud/core#34037]
We definitely know that this is a problem with the OC server 10.0.10 code concerning SMB & SFTP because it works flawlessly with nextcloud (v15) on the same server. Our OC clients (web, mobile & desktop) connect fine with nextcloud but not with OC 10.0.10. Please test this functionality for yourself, we've spent 2 weeks before giving up and I see other forum threads reporting the same.

## Steps to reproduce
1. Just setting up external storage for either SFTP or SMB, Guaranteed not to work

### Expected behaviour
It to communicate

### Actual behaviour
No communications at all for SFTP 
False green light for SMB, get a green light even when putting in bogus credentials to try to get a red light.

### Server configuration
CentOS7 & Debian

**Web server:**
Apache

**Database:**
MariaDB 

**PHP version:**
PHP 5.4, 5.6, 6 & 7.2.13

**ownCloud version:** (see ownCloud admin page)
10.0.10

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
owncloud.org & bitnami

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/2308 (OC 5.0.0: Some foldernames do not work), https://github.com/owncloud/core/issues/5111 (SMB backend does not work), https://github.com/owncloud/core/issues/17480 (SMB-with OC-login not working in 8.10), https://github.com/owncloud/core/issues/2300 (OC 5.0: Update does not work.), and https://github.com/owncloud/core/issues/23748 ([OC 9.0.0] Changing upload size does not work).

**Comment by uptown1** [comment]
These other cases are related but do not actually address this issue. The issue where putting in bogus credentials or a fake path for SMB and we still get a green light makes absolutely no sense.

**Comment by PVince81** [comment]
@davitol can you reproduce this in 10.0.10 or 10.1 beta ?

**Comment by davitol** [comment]
@PVince81 @uptown1 It works fine for me with oC 10.0.10 and with 10.1 beta version.

For example using this public SFTP (read-only) https://www.sftp.net/public-online-sftp-servers, works for you @uptown1 

If there any spefic/different configuration in your SFTP?

**Comment by uptown1** [comment]
Weird, it did work for public SFTP server but not communicating at all with any internal SFTP servers. Logs on internal SFTP does not even show an attempt from OC server. What about SMB though? Any workaround there?

**Comment by davitol** [comment]
> What about SMB though? Any workaround there?

Also tested with SMB and works for me. Also I have asked to other users and works, so the probably it is not an ownCloud issue. If you can provide futher info, feel free to reopen the ticket. Thanks for reporting
