### ISSUE TITLE
OC5.0.6 - External Storage - FTP - unable to mount share

### ISSUE THREAD

**Issue by j-ed** [owncloud/core#3408]
## Expected behaviour

If you've created a FTP mount configuration the share should automatically be mounted.
## Actual behaviour

The configured FTP share is not being mounted if I select the share `BilderHome` from the files tab and the message "Cloud not found, i //BilderHome" is shown instead. It might be important to mention that the mount point `BilderHome`is displayed as a file and not as a folder.
## Steps to reproduce

1) I've installed a local FTP-Server and tested access to it by using a standard ftp client. The server is reachable from the local server as from the local LAN and a login is also possible without any problems.

2.1) At first I've created the following `mount.php` file to test access to the server:

``` php
   <?php
    return array(
      'user' => array(
        'jed' => array(
          '/$user/files/BilderHome'=>array('class'=>'OC_Filestorage_FTP','options'=>array('host'=>'ftp.privat.lan','user'=>'jed','password'=>'test','root'=>'/',' secure'=>false)),
        ),
      ),
    );
```

2.2) In addition I've also tried to create the same ftp mount using the GUI to access the server. As a result the following `mount.json` file was created:

``` php
{"user":{"jed":{"\/$user\/files\/BilderHome":{"class":"\\OC\\Files\\Storage\\FTP","options":{"host":"ftp.privat.lan","user":"jed","password":"test","root":"","secure":"false"}}}}
```

3) If I select the displayed share `BilderHome`, which is not displayed as folder but as a file, the message "Cloud not found, i //BilderHome" is displayed.

4) If I select the Administrator menu, the following PHP error is shown on the screen for a short moment:

``` php
    `Warning: stat():  stat failed for ftp://jed:test@ftp.privat.lan/ in .../owncloud/apps/files_external/lib/streamwrapper.php on line 81`
```
#### Server Configuration

OS: Linux 2.6.24-24
Web server: Apache/ 2.2.22
Database: MySQL
PHP version: 5.3.13
Pure-FTPd v1.0.36
ownCloud version: 5.0.6
#### Client Configuration

Browser: Firefox 21.0
Operating system: Windows 7

**Comment by PVince81** [comment]
I remember that you were using a custom-built Linux distro. Did you check whether PHP was setup/installed properly there (maybe compare the config/libs with other distros) ?

**Comment by j-ed** [comment]
@PVince81 As a first step I verified all setting etc. but couldn't find a reason for that problem. I also did some research on the Internet concerning the `stat failed for` error and found several occurrences where users had reported similar problems with some of the standard functions accessing ftp files.

**Comment by PVince81** [comment]
@icewind1991 has been working on a new implementation here: https://github.com/owncloud/core/pull/14551

**Comment by PVince81** [comment]
@j-ed still having this problem with newer PHP versions ?

**Comment by j-ed** [comment]
@PVince81 I've justed tested it in the following environment, but the problem still persists.

#### Server Configuration
OS: Linux 3.2.67
Web server: Apache/ 2.4.12
Database version: MySQL 5.1.73
PHP version: 5.4.42
Pure-FTPd v1.0.36
ownCloud version: 8.0.6

#### Client Configuration
Browser: Firefox 40.0.2
Operating system: Windows 7

**Comment by PVince81** [comment]
@j-ed can you try with https://github.com/owncloud/core/pull/23101 ?

**Comment by hodyroff** [comment]
No information. Please comment again if the issue continues on new ownCloud versions.
