### ISSUE TITLE
[10.1.0] App patch version update not updating oc_appconfig

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#34090]
### Steps

1. Install an app version 1.0.0 using occ market:install or occ app:enable
1. Update the app to version 1.0.1 by replacing the tarball (or increase the version in info.xml). Don't use occ.
1. Run `occ upgrade`
1. Check "oc_appconfig" for the app version

### Expected result
App version increased to 1.0.1 in oc_appconfig.

### Actual result
Message that everything is up to date and oc_appconfig still says 1.0.0

### Version
stable10 / ownCloud 10.1.0 beta

This happens because of the change with Semver where we said that patch versions of apps will not trigger migrations. See https://github.com/owncloud/core/pull/31103

The problem is that the oc_appconfig increase is usually happening during occ upgrade.
The other case where the increase might happen is when upgrading with occ market:update, however such command isn't always used. When dealing with offline instances, admins might need to manually update the code of apps by replacing the tarballs.

One idea would be to have `occ upgrade` still run but not enable maintenance mode, and just execute the routine for the apps. This is likely a risky change. Also it wouldn't affect web UI access, as web UI would usually show a page that requires an update, so this proposal is not a good solution.

Another idea would be to have new commands, for example "app:update" that would run app updates only. It could also cover the migrations part if needed and trigger maintenance mode.

So far I don't see a good quick fix.

@DeepDiver1975 @tomneedham

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/28027 (Updating 10.0.0 to 10.0.1), https://github.com/owncloud/core/issues/28007 (can't   update   Or  install     ownCloud  in version  10.0.1), https://github.com/owncloud/core/issues/20661 (Update), https://github.com/owncloud/core/issues/21366 (Update), and https://github.com/owncloud/core/issues/6957 (Update Failed : 5.0.10 - 6.0.1 ).

**Comment by tomneedham** [comment]
> Another idea would be to have new commands, for example "app:update" that would run app updates only. It could also cover the migrations part if needed and trigger maintenance mode.

Would rather try to avoid this - more fragmentation in occ commands, more to document, more to forget to run etc.

**Comment by tomneedham** [comment]
With the patch level changes do we still emit `OC\Updater::appUpgradeStarted` and  `OC\Updater::appUpgrade` ? Maybe other potential events that are now skipped?

**Comment by tomneedham** [comment]
Impact of missing correct values in oc_appconfig include:
 - occ app:list shows wrong value
 - config report shows wrong values - used for debugging issues with installations

**Comment by DeepDiver1975** [comment]
Nothing will be trigger on patch level - if you need to perform any action: update the minor version.

to solve the version missmatch in appconfig: we can update the version in here: https://github.com/owncloud/core/pull/31103/files#diff-3a7450cd4a63696420772086fff201aaR868

**Comment by PVince81** [comment]
> With the patch level changes do we still emit `OC\Updater::appUpgradeStarted` and `OC\Updater::appUpgrade` ? Maybe other potential events that are now skipped?

@tomneedham the PR of https://github.com/owncloud/core/pull/34133 will only set the appconfig value but will not trigger any of the events you metionned in
