### ISSUE TITLE
Fresh Install 10.0.10 Error: Syntax error or access violation: 1118 Row size too large.

### ISSUE THREAD

**Issue by realsushie** [owncloud/core#34096]
I have an error on a fresh installation (owncloud-10.0.10.tar.bz2) via installation wizard:

> Exception: {"Exception":"Doctrine\DBAL\Exception\DriverException","Message":"An exception occurred while executing 'CREATE TABLE oc_activity (activity_id INT AUTO_INCREMENT NOT NULL, timestamp INT DEFAULT 0 NOT NULL, priority INT DEFAULT 0 NOT NULL, type VARCHAR(255) DEFAULT NULL, user VARCHAR(64) DEFAULT NULL, affecteduser VARCHAR(64) NOT NULL, app VARCHAR(255) NOT NULL, subject VARCHAR(255) NOT NULL, subjectparams VARCHAR(4000) NOT NULL, message VARCHAR(255) DEFAULT NULL, messageparams VARCHAR(4000) DEFAULT NULL, file VARCHAR(4000) DEFAULT NULL, link VARCHAR(4000) DEFAULT NULL, object_type VARCHAR(255) DEFAULT NULL, object_id INT DEFAULT 0 NOT NULL, INDEX activity_time (timestamp), INDEX activity_user_time (affecteduser, timestamp), INDEX activity_filter_by (affecteduser, user, timestamp), INDEX activity_filter_app (affecteduser, app, timestamp), INDEX activity_object (object_type, object_id), PRIMARY KEY(activity_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed':\n\nSQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs" ...

Our System (at our Provider):
- FreeBSD 11.2
- Apache 2.4
- PHP 7.2.12
- 10.1-MariaDB

To reproduce:
- Upload and extract owncloud-10.0.10.tar.bz2 to webroot
- Create Database and User, set filepermissions 
- Browse to folder owncloud
- Define Adminuser, Datafolder, DB-Settings in Wizard
- Run Wizard
= ERROR

There are quite similar issues here https://github.com/owncloud/core/issues/27755 and owncloud/activity#652 but since i am not a coder nor an sysadmin, i cannot follow the instructions there... 

Any help for a "dummy-installer" ?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/27755 (Updating to 10.0.0 - Syntax error or access violation: 1118 Row size too large), https://github.com/owncloud/core/issues/29472 (Updating to 10.0.3 - Syntax error or access violation: 1118 Row size too large), https://github.com/owncloud/core/issues/9813 (OC 6.04 -> 7.0.0 upgrade fails with "Syntax error or access violation"), https://github.com/owncloud/core/issues/26902 (error), and https://github.com/owncloud/core/issues/28840 (-Error-).

**Comment by PVince81** [comment]
From what I see the official owncloud-10.0.10 tarball does not contain the activity app.

Did you miss a reproduction step that tells to install the activity app somehow ?

**Comment by crossan007** [comment]
This comment has helped me get past this upgrade error: https://github.com/owncloud/core/issues/27755#issuecomment-358678585
