### ISSUE TITLE
push aka ActiveSync

### ISSUE THREAD

**Issue by Sineos** [owncloud/core#3410]
IMHO having an ActiveSync functionality is key for an application like owncloud. We are researching the possibility to deploy owncloud in our small business but it would be used mainly with mobile devices. 
Amongst others the energy (battery) saving aspect of push would be important for us. To keep halfway updated with calendar or task lists, a "pull interval" of min 30 minutes would have to be used, that means every 30 mins the device needs to wake up, establish a connection and check for changes. First test have shown that this a considerable battery hog.
Please consider picking up the (unfortunately) abandoned oczpush. Many thanks

**Comment by LukasReschke** [comment]
Please reopen in the calendar or contacts repository. Nothing for core from my PoV. Also very unlikely to get implemented,  sorry.
