### ISSUE TITLE
External shares: access to the share or token owner is missing

### ISSUE THREAD

**Issue by VicDeo** [owncloud/core#34104]
When a remote DAV storage is modified it is accessed by token in incognito mode.
It would be handy to resolve this token into the user with some kind of core API call. 
At least obtain a share object that was used for authorization to call `getSharedWith` on it.

Currently it is possible for dav V1 endpoints only with such an ugly approach 
https://github.com/owncloud/activity/pull/672

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/17799 (Recording share access), https://github.com/owncloud/core/issues/20741 (Sharing tokens should be unique), https://github.com/owncloud/core/issues/11076 (Concurential access on a share), https://github.com/owncloud/core/issues/30156 (Federation sharing options missing), and https://github.com/owncloud/core/issues/3853 (request token is missing on upgrade).
