### ISSUE TITLE
Enable share calendar in iCal on macOS Mojave

### ISSUE THREAD

**Issue by Inseeker** [owncloud/core#34119]
### Steps to reproduce
1.  set ownCloud account with iCal on macOS Mojave using the following URL:https://example.com/remote.php/dav/principals/users/USERNAME/
2. create a calendar, and share it (read/write) with user B
3. iCal alter an error message

### The iCal error message
The server responded with an error.
The request for account “ownCloud-fanping” failed.

The server responded with
“501”
to operation CalDAVUpdateShareesQueuableOperation.

### The ownCloud log
{
  "reqId": "DvvXBWE6rGeodUjfZVlX",
  "level": 4,
  "time": "2019-01-11T07:58:45+00:00",
  "remoteAddr": "118.144.139.212",
  "user": "fanping",
  "app": "webdav",
  "method": "POST",
  "url": "/remote.php/dav/calendars/fanping/0A123189-F58B-49B4-B45D-83A30FC0E228/",
  "message": "Exception: {'Message':'HTTP/1.1 501 There was no plugin in the system that was willing to handle this POST method.",
  "Exception": "SabreDAVExceptionNotImplemented",
  "Code": 0,
  "Trace": "#0 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(254): SabreDAVServer->invokeMethod(Object(SabreHTTPRequest), Object(SabreHTTPResponse))n #1 /var/www/owncloud/apps/dav/lib/Server.php(278): SabreDAVServer->exec()n #2 /var/www/owncloud/apps/dav/appinfo/v2/remote.php(31): OCADAVServer->exec()n#3 /var/www/owncloud/remote.php(165): require_once('/var/www/ownclo...')n#4 {main}",
  "File": "/var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php",
  "Line": 487,
  "User": "fanping"
}

### Server configuration
**Operating system**:
macOS Mojave version10.14.2
 
**Calendar Client:**
macOs Calendar Version 11.0 

**ownCloud version:** 
ownCloud 10.0.10 (stable)

### Additional Information
When i use the Calendar app of ownCloud market ;
I can share calendar normally

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/9918 (Calendar share), https://github.com/owncloud/core/issues/2425 (Issues on Shared Calendars), https://github.com/owncloud/core/issues/393 (Calendar sharing error), https://github.com/owncloud/core/issues/704 (Calendar sharing error), and https://github.com/owncloud/core/issues/33216 (Deleting Calendar Sharing).

**Comment by Inseeker** [comment]
> [GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.
> 
> Possibly related issues are #9918 (Calendar share), #2425 (Issues on Shared Calendars), #393 (Calendar sharing error), #704 (Calendar sharing error), and #33216 (Deleting Calendar Sharing).

This  issues can't be solved with these related issues.

**Comment by DeepDiver1975** [comment]
Can you find Out What the request body of that post looks like? Thx
