### ISSUE TITLE
OC 10.0.10 Ubuntu package missing files for Market app disabling it

### ISSUE THREAD

**Issue by sorenweber** [owncloud/core#34121]
I run Ubuntu server 16.04 and recently upgrade owncloud from
`deb https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ /`
and the Market app has problems that disables it. This is the output from the failed integrity check:

    Technical information
    =====================
    The following list covers which files have failed the integrity check. Please read
    the previous linked documentation to learn more about the errors and how to fix
    them.

    Results
    =======
    - market
    	- FILE_MISSING
    		- README.md
    		- lib/HttpService.php
    		- lib/VersionHelper.php

    Raw output
    ==========
    Array
    (
        [market] => Array
            (
                [FILE_MISSING] => Array
                    (
                        [README.md] => Array
                            (
                                [expected] => b53ebb407cb90a5cf9e28463013f38e6aec3d39b4281187366e02b5fd014be144216a088fc50851635acc50cb71c92ad2407b21e8a4f3433b0f73a32ea066c97
                                [current] => 
                            )

                        [lib/HttpService.php] => Array
                            (
                                [expected] => f8803c93bcd45a0bda2eee8c33c510064d2524e531de991e94cf65bffefc5f2caba061070478a28a44a3d7bc2a8699cbd1f7ac949c972b5426374811a5ee8c7d
                                [current] => 
                            )

                        [lib/VersionHelper.php] => Array
                            (
                                [expected] => fa454a12d5f050c2f8d396aa39c52e736bcb4110cf2ff3c55215a09b1754ba568baef1cd810aa1ad060125f616e8fe6885f6820592408e8964186d683ef167c2
                                [current] => 
                            )

                    )

            )

    )

I tried to
`apt-get --reinstall  install owncloud-files`
without success. Then I downloaded and unpacked `owncloud-files` and did also not see the files owncloud reports as missing, so I guess they're truly missing. On top of this I regularly have debsums checking the md5sums of all installed packages and comparing them to those listed in the deb-files and it lists mismatch for the following files:

    /var/www/owncloud/apps/market/appinfo/info.xml
    /var/www/owncloud/apps/market/appinfo/signature.json
    /var/www/owncloud/apps/market/js/market.bundle.js
    /var/www/owncloud/apps/market/lib/Application.php
    /var/www/owncloud/apps/market/lib/CheckUpdateBackgroundJob.php
    /var/www/owncloud/apps/market/lib/Command/InstallApp.php
    /var/www/owncloud/apps/market/lib/Command/UpgradeApp.php
    /var/www/owncloud/apps/market/lib/Controller/MarketController.php
    /var/www/owncloud/apps/market/lib/Listener.php
    /var/www/owncloud/apps/market/lib/MarketService.php
    /var/www/owncloud/apps/market/vendor/autoload.php
    /var/www/owncloud/apps/market/vendor/composer/ClassLoader.php
    /var/www/owncloud/apps/market/vendor/composer/autoload_real.php
    /var/www/owncloud/apps/market/vendor/composer/autoload_static.php

This is my package info:

    # apt show owncloud-files
    Package: owncloud-files
    Version: 10.0.10-1+1.1
    Priority: optional
    Section: devel
    Maintainer: Juergen Weigert <jw@owncloud.com>
    Installed-Size: 129 MB
    Conflicts: owncloud (<= 9.01.99), owncloud-config-apache (<= 9.01.99), owncloud-server (<= 9.01.99)
    Replaces: owncloud (<= 9.01.99), owncloud-config-apache (<= 9.01.99), owncloud-server (<= 9.01.99)
    Download-Size: 40,1 MB
    APT-Manual-Installed: no
    APT-Sources: https://download.owncloud.org/download/repositories/stable/Ubuntu_16.04  Packages
    Description: ownCloud - Server
     The owncloud-files package installs the codebase.
     Admins are advised to check for missing dependencies
     and configuration settings using owncloud online documentation and the occ tool.
     .
     .
     At the same time, ownCloud provides employees and end users anywhere,
     anytime access to the files they need to get the job done - via mobile apps,
     desktop sync clients, WebDAV clients and the web. With ownCloud, employees
     can easily view and share documents and information critical to the
     business, in a secure, flexible and controlled architecture - one that is
     consistent with IT policies, procedures and regulatory requirements.
     .
     For more information, visit www.owncloud.com

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/21327 (ubuntu 14.04 server package missing /ocs-provider/), https://github.com/owncloud/core/issues/23196 (Ubuntu 12.04, 14.04 and 15.10 missing oC 8.2.3 packages), https://github.com/owncloud/core/issues/4527 (Media app won't sync new files OC 5.0.10), https://github.com/owncloud/core/issues/2312 (OC 5.0 Unable to upload any file), and https://github.com/owncloud/core/issues/4763 (Ubuntu repositories for owncloud-client are broken: empty Packages file after 1.4.0 release).

**Comment by PVince81** [comment]
@crrodriguez please have a look

**Comment by PVince81** [comment]
@crrodriguez any update ?

**Comment by sorenweber** [comment]
New packages `Version: 10.1.0-1+1.1` has been uploaded, and when I upgraded just now, I could from the command line enable the Market.

So, from my point of view it is working now. Thank you @PVince81 and @crrodriguez.
