### ISSUE TITLE
Test Results for operations that fail without lock token but succeed when lock token is passed

### ISSUE THREAD

**Issue by davitol** [owncloud/core#34157]
Permissions masks:
- **READ** = 1
- **UPDATE** = 2 ("can update" in web UI)
- **CREATE** = 4 ("can create" in web UI)
- **DELETE** = 8 ("can delete" in web UI)
- **SHARE** = 16 ("can reshare" in web UI)

File operations shorthand for the later table:
- [x] **download**: download/read/get a locked file.
- [x] **upload**: a new file can NOT be uploaded/created in a locked folder
- [x] **upload_overwrite**: a file can NOT be overwrite an existing locked one
- [x] **rename**: rename file to new name, all within the shared folder. NOT possible
- [x] **move_in**: move a file from outside the shared folder into the shared folder. NOT possible
- [x] **move_in_overwrite**: move a file from outside the shared folder and overwrite a file inside the shared folder (note: SabreDAV automatically deletes the target file first before moving, so requires DELETE permission too). NOT possible
- [x] **move_in_subdir**: move a file already in the shared folder into a subdir within the shared folder. NOT possible
- [x] **move_in_subdir_overwrite**: move a file already in the shared folder into a subdir within the shared folder and overwrite an existing file there. NOT possible.
- [x] **move_out**: move a file to outside of the shared folder. NOT possible.
- [x] **move_out_subdir**: move a file out of a subdir of the shared folder into the locked shared folder. NOT possible.
- [x] **copy_in**: copy a file from outside the shared folder into the locked shared folder. NOT possible.
- [x] **copy_in_overwrite**: copy a file from outside the shared folder and overwrite a file inside the locked shared folder (note: SabreDAV automatically deletes the target file first before copying, so requires DELETE permission too)
- [x] **delete**: delete a file inside the locked shared folder. NOT possible.
- [x] **mkdir**: create folder inside the locked shared folder. NOT possible.
- [x] **rmdir**: delete folder inside the locked shared folder. NOT possible.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/17243 (Lock sharing operations when file is locked), and https://github.com/owncloud/core/issues/16794 (csync tests fail with file locking enabled).

**Comment by davitol** [comment]
- [ ] lock webdav root of user
- [ ] lock public webdav root
- [ ] propfind lock info on public webdav endpoint while any of the parents from the link share is locked
- [ ] Test locking for Windows

**Comment by davitol** [comment]
## Tests with Public Link

- [ ] TEST: set lock on "/public", query locks on "public.php/webdav/sub" returns lock root "public.php/webdav/"
- [ ] TEST: set lock on "/public/share", query locks on "public.php/webdav/sub" returns lock root "public.php/webdav/"
- [ ] TEST: set lock on "/public/share/sub", query locks on "public.php/webdav/sub" returns lock root "public.php/webdav/sub"
- [ ]TEST: set lock on "/public", set another lock on "public.php/webdav/sub" returns empty lock root ""
- [ ] TEST: set lock on "/public/share/sub", set another lock on "public.php/webdav/sub" returns lock root "/sub"

**Comment by davitol** [comment]
## Test unlock with Public Link

- [ ] Unlock as owner using the lock token
- [ ] Unlock as recipient using the lock token
- [ ] Unlock as public user using the lock token

**Comment by davitol** [comment]
# Test unlock with Share with user

- [x] Unlock as owner using the lock token
- [ ]  Try to unlock as recipient and check it is not possible.
- [x] Try to unlock as public user using the lock token and check it is not possible.

**Comment by davitol** [comment]
## Test unlock a folder/subfolder with Share with user 

![screen shot 2019-01-28 at 14 27 15](https://user-images.githubusercontent.com/10596560/51839448-884df900-2309-11e9-8636-dbcb0ad85e67.png)

**Comment by davitol** [comment]
## Test WOPI + Office online

- [ ] Try to edit a locked file

**Comment by davitol** [comment]
How Has This Been Tested?

Unit tests

With "/public/share" being the link share:
- [ ] TEST: set lock on "/public", query locks on "public.php/webdav/sub" returns lock root "public.php/webdav/"
- [ ] TEST: set lock on "/public/share", query locks on "public.php/webdav/sub" returns lock root "public.php/webdav/"
- [ ] TEST: set lock on "/public/share/sub", query locks on "public.php/webdav/sub" returns lock root "public.php/webdav/sub"
- [ ] TEST: set lock on "/public", set another lock on "public.php/webdav/sub" returns empty lock root ""

- [ ] TEST: set lock on "/public/share/sub", set another lock on "public.php/webdav/sub" returns lock root "/sub"

**Comment by davitol** [comment]
### Test Lock/Unlocking files with guest users [WIP]

**Comment by davitol** [comment]
### Locking with Federated Shares [WIP]

**Comment by davitol** [comment]
### Test Locks in External Storage WND

- [ ] Lock / Unlock a file
- [ ] Move a locked file into a folder using the token.
```
curl -k -H 'If: (<opaquelocktoken:cd9598b0-7619-46b2-a839-a1366b580269>)' -H 'Destination:http://10.40.40.222:9681/remote.php/webdav/WindowsNetworkDrive/User/Videos/Nuevos.txt' -H 'Overwrite:F' -H 'Authorization:Basic YWRtaW46YWRtaW4=' -H 'User-Agent:Mozilla/5.0 (Android) ownCloud-android/2.7.0' -H 'Host:10.40.40.222:9681' -X MOVE 'http://10.40.40.222:9681/remote.php/webdav/WindowsNetworkDrive/User/Nuevos.txt'
```

**Comment by davitol** [comment]
Pending issues will be fixed in the following versions after ownCloud 10.1.

**Comment by individual-it** [comment]
### tests with multiple clients davfs2, LibreOffice, GnomeFiles
davfs locks files, but only before PUT
LibreOffice locks files for the time when it has the file open and refreshes the lock (180s)
GnomeFiles does not know about locks

1. create 3 users
1. mount user1 with davfs2 `sudo mount -t davfs http://localhost/owncloud-10.1.0/owncloud/remote.php/dav/files/user1/ /mnt/ -o rw,uid=artur`
1. mount user2 with GnomeFiles/Nautilus: Other Locations -> Connect to Server `dav://localhost/owncloud-10.1.0/owncloud/remote.php/dav/files/user2`
1. setup LibreOffice to access files of user3 by Open Remote function
- [x] open a file with davfs, change and save it - changing and saving should work
- [ ] open a file with GnomeFiles, change and save it - changing and saving should work
- [ ] open a file with LibreOffice, change and save it, in WebUI check if file is marked as locked - changing and saving should work
- [ ] share a folder from user1 to user2 and same from user2 to user3 - folder and content should be visible by all clients
- [ ] create a textfile by davfs, open and edit it with LibreOffice (Remote Open) close LibreOffice, edit the same file with GnomeFiles - edit is possible, changes propagate
- [ ]  open a file with LibreOffice (Remote Open) leave it open and try to edit it with GnomeFiles and davfs - changing the file should not be possible
- [ ]  open a file with LibreOffice (Remote Open) leave it open and try to delete/move it with GnomeFiles and davfs - deleting/moving the file should not be possible
- [ ]  place a file in a subfolder of the share. open that file with LibreOffice (Remote Open) leave it open and try to delete/move the parent folder with GnomeFiles and davfs - deleting the folder should not be possible
- [ ] open the same file twice using LibreOffice first with Remote Open and second through davfs - second opening should show that the file is locked and open only read-only

**Comment by PVince81** [comment]
should we close or are there pending tasks we want to continue tracking for future scheduling ?

**Comment by davitol** [comment]
Let's close the ticket. issues found now has its own tickets
