### ISSUE TITLE
Problem with ca & login crash

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/core#34151]
Owncloud login crash

apache2 error log:

> [Tue Jan 15 15:15:16.682038 2019] [autoindex:error] [pid 15549] [client 79.249.250.195:50660] AH01276: Cannot serve directory /var/www/html/owncloud: No matching DirectoryIndex (none) found, and s$
[Tue Jan 15 15:17:20.532004 2019] [mpm_prefork:notice] [pid 6614] AH00169: caught SIGTERM, shutting down
[Tue Jan 15 15:17:20.994587 2019] [ssl:warn] [pid 24125] AH01906: 127.0.1.1:443:0 server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
[Tue Jan 15 15:17:20.994968 2019] [ssl:warn] [pid 24125] AH01909: 127.0.1.1:443:0 server certificate does NOT include an ID which matches the server name

after restart apache and restart browser the problem is solve

I have oC 10.0.10.4 installed on Raspbian with PHP7.0

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/2 (ca), https://github.com/owncloud/core/issues/20028 (ca-bundle problem with openBSD 5.8), https://github.com/owncloud/core/issues/18862 (CA bundle chaos), https://github.com/owncloud/core/issues/7810 (Charset Problem Umlaut), and https://github.com/owncloud/core/issues/19887 (formatTimeSpan usability problem - enhancement).

**Comment by ho4ho** [comment]
@prsnbrg Bugtracker no good for question with Apache?

**Comment by individual-it** [comment]
@prsnbrg please fill the complete issue template

**Comment by PVince81** [comment]
closing due to lack of feedback.

for help please refer to http://owncloud.org/help/
