### ISSUE TITLE
Expand webUISharingExternal acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#34150]
Current webUISharingExternal acceptance tests check just basic cases of upload, overwrite, rename, delete in the top folder of the received share.

- [x] do some file operations in sub-folders of the received share
- [x] look through the apiFederation acceptance test scope in issue #34149 and design a moderate set of test scenarios for the webUI to at least cover "the basics" of those scenarios.

Keep in mind that webUI tests are slow! But the current webUI uses various "private" APIs that could behave differently to the public APIs used by the apiFederation acceptance test suite. Because of this, it is good to cover a good mix of scenarios in the webUI.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/33690 (cleanup acceptance tests WebDav trait), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), and https://github.com/owncloud/core/pull/31516 (Acceptance test coding standard changes).

**Comment by paurakhsharma** [comment]
@phil-davis, Should we close this?
