### ISSUE TITLE
Single User Sync thinks uid should be the Lastname and/or something else

### ISSUE THREAD

**Issue by hollowdew** [owncloud/core#34162]
Introduction

Hello,

I try to sync a single account with the new option -u=UID [–uid=UID].
I think the UID is either the username or the uuid-string e.g. dc3254d2-fecd-1037-99a3-83ba3acsd455
I tried all Attributes but nothing will work. And also the output looks like:

!! I am using a Samba 4.8.2 Active Directory Domain Controller (Primary) and connected it with owncloud. !!
The Bug

sudo -u apache php occ user:sync -v ‘OCA\User_LDAP\User_Proxy’ --uid=maske28
–> maske28 is the sAMAccountName or uid.
The Output looks like:

If unknown users are found, what do you want to do with their accounts? (removing the account will also remove its data)
[0] disable
[1] remove
[2] ask later

    2 (i selected 2, ask later )
    Syncing maske28 …
    These accounts that are no longer available in the backend:
    maske28, , (no longer exists in the backend)
    What do you want to do with their accounts? (removing the account will also remove its data)
    [0] disable
    [1] remove

I think it is not normal that i get maske28, , <-- 2 spaces seperated with commas.
What does the command try to do?

If i use the lastname of the user maske28 which is maske, the sync is successfull, but only if the lastname is unique in LDAP-Backend.
Server configuration

CentOS 7:

httpd Apache/2.4.6

**Database: Ver 14.14 Distrib 5.6.42 **

PHP version: 5.6.39

ownCloud version: 10.0.10 (stable) (see ownCloud admin page)

**Updated from an older ownCloud or fresh install: Yes **

**Where did you install ownCloud from: Official CentOS Repo **

Signing status (ownCloud 9.0 and above): No errors have been found.

The content of config/config.php:
{
“system”: {
“instanceid”: “oc298yszf40o”,
“passwordsalt”: “REMOVED SENSITIVE VALUE”,
“secret”: “REMOVED SENSITIVE VALUE”,
“trusted_domains”: [
“my.domain.com”
],
“datadirectory”: “/var/www/html/owncloud/data”,
“overwrite.cli.url”: “http://my.domain.com”,
“dbtype”: “mysql”,
“version”: “10.0.10.4”,
“dbname”: “ownclouddb”,
“dbhost”: “localhost”,
“dbtableprefix”: “oc_”,
“dbuser”: “REMOVED SENSITIVE VALUE”,
“dbpassword”: “REMOVED SENSITIVE VALUE”,
“logtimezone”: “UTC”,
“installed”: true,
“filelocking.enabled”: “true”,
“memcache.locking”: “\OC\Memcache\Redis”,
“redis”: {
“host”: “localhost”,
“port”: 6379,
“timeout”: 0
},
“memcache.local”: “\OC\Memcache\Redis”,
“theme”: “owntheme”,
“mail_smtpmode”: “smtp”,
“mail_from_address”: “REMOVED SENSITIVE VALUE”,
“mail_domain”: “REMOVED SENSITIVE VALUE”,
“mail_smtphost”: “REMOVED SENSITIVE VALUE”,
“updatechecker”: false,
“ldapIgnoreNamingRules”: false,
“loglevel”: 3,
“maintenance”: false,
“preview_libreoffice_path”: “/usr/bin/libreoffice”,
“singleuser”: false
}
}

List of activated apps:
Enabled:

    activity: 2.4.1
    calendar: 1.6.1
    comments: 0.3.0
    configreport: 0.1.1
    contacts: 1.5.5
    dav: 0.4.0
    federatedfilesharing: 0.3.1
    federation: 0.1.0
    files: 1.5.1
    files_external: 0.7.1
    files_pdfviewer: 0.10.0
    files_sharing: 0.11.0
    files_texteditor: 2.3.0
    files_trashbin: 0.9.1
    files_versions: 1.3.0
    files_videoplayer: 0.9.8
    firstrunwizard: 1.1
    gallery: 16.1.1
    market: 0.3.0
    notifications: 0.3.5
    provisioning_api: 0.5.0
    systemtags: 0.3.0
    templateeditor: 0.4.0
    updatenotification: 0.2.1
    user_ldap: 0.13.0
    Disabled:
    encryption
    external
    user_external

**Are you using external storage, if yes which one: No **

Are you using encryption: no

Are you using an external user-backend, if yes which one: LDAP
LDAP configuration (delete this part if not used)

±------------------------------±----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration | |
±------------------------------±----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport | 1 |
| hasPagedResultSupport | |
| homeFolderNamingRule | |
| lastJpegPhotoLookup | 0 |
| ldapAgentName | CN=ldap,CN=Users,dc=my,dc=domain,dc=com |
| ldapAgentPassword | *** |
| ldapAttributesForGroupSearch | |
| ldapAttributesForUserSearch | |
| ldapBackupHost | |
| ldapBackupPort | |
| ldapBase | dc=my,dc=domain,dc=com |
| ldapBaseGroups | dc=my,dc=domain,dc=com |
| ldapBaseUsers | dc=my,dc=domain,dc=com |
| ldapCacheTTL | 600 |
| ldapConfigurationActive | 1 |
| ldapDynamicGroupMemberURL | |
| ldapEmailAttribute | mail |
| ldapExperiencedAdmin | 0 |
| ldapExpertUUIDGroupAttr | |
| ldapExpertUUIDUserAttr | entryuuid |
| ldapExpertUsernameAttr | |
| ldapGroupDisplayName | cn |
| ldapGroupFilter | (&(|(objectclass=group))(|(cn=owncloud))) |
| ldapGroupFilterGroups | owncloud |
| ldapGroupFilterMode | 1 |
| ldapGroupFilterObjectclass | groupOfNames |
| ldapGroupMemberAssocAttr | memberUid |
| ldapHost | ldap://IP.IP.IP.IP |
| ldapIgnoreNamingRules | |
| ldapLoginFilter | (&(&(|(objectclass=organizationalPerson))(|(memberof=cn=owncloud,ou=Groups,dc=my,dc=domain,dc=com)))(|(sAMAccountName=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes | |
| ldapLoginFilterEmail | 1 |
| ldapLoginFilterMode | 1 |
| ldapLoginFilterUsername | 1 |
| ldapNestedGroups | 0 |
| ldapOverrideMainServer | |
| ldapPagingSize | 500 |
| ldapPort | 389 |
| ldapQuotaAttribute | postOfficeBox |
| ldapQuotaDefault | 2000000000 |
| ldapTLS | 0 |
| ldapUserDisplayName | cn |
| ldapUserDisplayName2 | |
| ldapUserFilter | (&(|(objectclass=organizationalPerson))) |
| ldapUserFilterGroups | |
| ldapUserFilterMode | 0 |
| ldapUserFilterObjectclass | organizationalPerson |
| ldapUserName | samaccountname |
| ldapUuidGroupAttribute | auto |
| ldapUuidUserAttribute | auto |
| turnOffCertCheck | 0 |
| useMemberOfToDetectMembership | 1 |
±------------------------------±----------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Thanks in advanced!

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/31691 ([stable10] update user-sync help description), https://github.com/owncloud/core/issues/31375 (Add diff events from user sync service), https://github.com/owncloud/core/issues/16808 (Sync problem), https://github.com/owncloud/core/issues/29547 (sanity check for user sync), and https://github.com/owncloud/core/issues/31207 (Confusing behaviour with single user syncing if the user doesn't exists).

**Comment by PVince81** [comment]
I believe the uid that you need to pass is the one that was configured in LDAP to be synced as user id.

To check, you could do a `select * from oc_accounts` and see what user ids are visible there to get an idea what field you need to use from LDAP. (there might be a way also in the LDAP wizard but I'm not familiar enough with this part)

cc @tomneedham

**Comment by hollowdew** [comment]
Thank you for your answer PVince81.
I checked it, my user_id is the ldap attribute 'entryUUID'
But if I use the entryuuid e.g. 'cfc6bf1d-a6b0-20d0-30a7-14bd6defc24c' as parameter for the option -u (--uid) the answer from occ is:


Syncing cfc6bf1d-a6b0-20d0-30a7-14bd6defc24c ...                                                                                                                                   
These accounts that are no longer available in the backend:                                                                                                                        
cfc6bf1d-a6b0-20d0-30a7-14bd6defc24c, ,  (no longer exists in the backend)                                                                                                         
What do you want to do with their accounts? (removing the account will also remove its data)                                                                                       
  [0] disable                                                                                                                                                                      
  [1] remove                                                                                                                                                                       


So the same result will come if i use the username e.g. 'hollow1'
I configured owncloud to use the ldap attribute entryUUID as unique identifier for users. 
And sAMAccountName and mail attribute to login.

The only way the sync with --uid work is to use the lastname from the user to sync to.
And this will only work if the lastname is not already in the oc-db.

Thanks in advanced!
--hollowdew

**Comment by hollowdew** [comment]
Hello Community,

is there anything done now or will this get fixed in the next version?

Best regards
Hollowdew
