### ISSUE TITLE
do not use magic numbers for permissions in sharing steps

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34176]
after https://github.com/owncloud/core/pull/34175 we can use human readable permissions in sharing steps, so we should refactor existing steps to make them more readable

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/3742 (You don't have write permission here in Shared Folder.), https://github.com/owncloud/core/issues/4120 (Permission issues in shared folder), https://github.com/owncloud/core/issues/10111 (cannot edit group permission when sharing a folder), https://github.com/owncloud/core/issues/2838 (Shared Permissions not with PC Client), and https://github.com/owncloud/core/issues/22737 (Sharees don't have access to the permissions given to them by sharers).
