### ISSUE TITLE
App of type theme cannot have app.php - breaks on version upgrade

### ISSUE THREAD

**Issue by tomneedham** [owncloud/core#34183]
### Steps to reproduce
1. owncloud 10.0.10 with a customer theme installed, containing an app.php
2. deploy a new version of the theme, with a higher version number

### Expected behaviour
upgrade required, run occ ugrade and all is shiny

### Actual behaviour

occ an occ upgrade throw this. 

```
OC\NeedsUpdateException in /Users/tomneedham/Projects/cloud/lib/private/legacy/app.php:191
Stack trace:
#0 /Users/tomneedham/Projects/cloud/lib/private/legacy/app.php(127): OC_App::loadApp('theme-mytheme...')
#1 /Users/tomneedham/Projects/cloud/lib/base.php(577): OC_App::loadApps(Array)
#2 /Users/tomneedham/Projects/cloud/lib/base.php(994): OC::init()
#3 /Users/tomneedham/Projects/cloud/console.php(64): require_once('/Users/tomneedh...')
#4 /Users/tomneedham/Projects/cloud/occ(11): require_once('/Users/tomneedh...')
#5 {main}%
```

Blocked here: https://github.com/owncloud/core/blob/dc35e8068cae8d0416b41c655cdbf28badd7dc9a/lib/private/legacy/app.php#L191

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @PVince81, and @VicDeo.

Possibly related issues are https://github.com/owncloud/core/issues/14407 (php version ), https://github.com/owncloud/core/issues/3209 (Theming), https://github.com/owncloud/core/issues/13402 (... broken), https://github.com/owncloud/core/issues/15924 (PHP Notice versions), and https://github.com/owncloud/core/issues/20332 (cron.php breaks).
