### ISSUE TITLE
Integrity constraint violation [PRODUCTION CRASH]

### ISSUE THREAD

**Issue by janswist** [owncloud/core#34185]
### Expected behaviour
Files should save normally.

### Actual behaviour
`{"reqId":"bGmnEgiBllUPD56w+vaH","remoteAddr":"188.147.1.236","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\\\"files\\\\\\\/c4e59638cf0c03cc44b904b464c4ac32\\\", 1, 1546939350, \\\"files\\\\\\\/c4e59638cf0c03cc44b904b464c4ac32\\\"]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\\\/c4e59638cf0c03cc44b904b464c4ac32' for key 'lock_key_index'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\UniqueConstraintViolationException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(205): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/adapter.php(93): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `*P...', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(243): OC\\\\DB\\\\Adapter->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/lock\\\/dblockingprovider.php(113): OC\\\\DB\\\\Connection->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/lock\\\/dblockingprovider.php(158): OC\\\\Lock\\\\DBLockingProvider->initLockField('files\\\/c4e59638c...', 1)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(663): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/c4e59638c...', 1)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(577): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/cashba...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(577): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/cashba...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#10 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_sharing\\\/lib\\\/sharedstorage.php(685): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/cashba...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(577): OC\\\\Files\\\\Storage\\\\Shared->acquireLock('Deals\\\/Zwolinska...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1854): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('Deals\\\/Zwolinska...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1960): OC\\\\Files\\\\View->lockPath('\\\/cashback\\\/De...', 1)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1049): OC\\\\Files\\\\View->lockFile('\\\/cashback\\\/De...', 1)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(909): OC\\\\Files\\\\View->basicOperation('fopen', 'cashback\\\/Dea...', Array, 'rb')\\n#16 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(304): OC\\\\Files\\\\View->fopen('cashback\\\/Dea...', 'rb')\\n#17 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#18 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#19 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#20 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#21 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#22 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#23 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#24 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":66,\"User\":\"davidjan\"}","level":4,"time":"2019-01-08T08:22:30+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/cashback\/Deals\/Zwol%20Aleksandra%20-%208125\/Z%20formularza\/62824-akt-urodzenia-2.jpg","user":"davidjan"}`

### Server configuration
**Operating system**: Linux

**Web server:** Apache/2.4.7 (Ubuntu)

**Database:** Ver 14.14 Distrib 5.6.30, for debian-linux-gnu (x86_64) using  EditLine wrapper

**PHP version:** 5.5.9-1ubuntu4.16

**ownCloud version:** 9.0.1 (stable)

**Updated from an older ownCloud or fresh install:** no data

**Where did you install ownCloud from:** I didn't, someone else did

**Signing status (ownCloud 9.0 and above):** not sure what that means

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
Waiting for admin access to that part. To be updated.

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/26192 (SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: oc_filecache.storage, oc_filecache.path_hash), https://github.com/owncloud/core/issues/28981 (Integrity violation during parallel DELETE), https://github.com/owncloud/core/issues/12592 (Mapper::copy() can cause Integrity constraint violation), https://github.com/owncloud/core/issues/23532 (403 Forbidden when DELETE file), and https://github.com/owncloud/core/issues/24882 (Duplicate entry for key lock_key_index - UniqueConstraintViolationException).

**Comment by ho4ho** [comment]
> ownCloud version: 9.0.1 (stable)

Bugtracker no good for support in [2+ year old version](https://github.com/owncloud/core/releases/tag/v9.0.1)? Concider other option on https://owncloud.org/help/ ?

**Comment by davitol** [comment]
Please contact with https://owncloud.org/help/ (cc @cdamken )

Due to 9.0.1 is EOL we can close the ticket
