### ISSUE TITLE
Investigate apiShareManagment mergeShare.feature skipOnLDAP

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#34202]
The above feature has some scenarios that are ``skipOnLDAP`` and one of them refers to ``user_ldap-issue-274`` https://github.com/owncloud/user_ldap/issues/274 

That LDAP issue is closed and says that it is fixed.

1) Sort this out. If the test scenario(s) does work with LDAP, then remove the ``skipOnLDAP`` tag.

2) Review other ``skipOnLDAP`` tags to see how many we could remove.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/24683 (Investigate ActivityPub), https://github.com/owncloud/core/issues/8569 (Feature requests), https://github.com/owncloud/core/issues/12530 (Feature Request), https://github.com/owncloud/core/issues/1744 (Feature: Send It), and https://github.com/owncloud/core/issues/12658 (Upload-only feature).
