### ISSUE TITLE
occ files_external:list .Mounts from all users are listed even if we specify a user when using --all option

### ISSUE THREAD

**Issue by davitol** [owncloud/core#34221]
### Motivation and Context

Behavior found while testing https://github.com/owncloud/core/pull/32178#issuecomment-451386297 and https://github.com/owncloud/core/pull/32178

### Steps to reproduce

1. As admin create 2 users, ```user1``` ```user2```
2. Create mount points with all availability and with ```user1``` ```user2``` (see screenshot below)
3. Log in as user2 and create a personal mount (see screenshot below)
4. Run occ command: ```occ files_external:list --short user2 --all``` and ``occ files_external:list --short user1 --all``` and check results

### Expected behaviour

Only the mounts related to the user set in the CLI command should be shown

### Actual behaviour

Due to --all option (Show mounts for all users. All has precedence over user_id) , mount from all users are shown even if we specify a user:

![1mount](https://user-images.githubusercontent.com/10596560/51547872-6a931680-1e67-11e9-9b87-07d595e68ce4.png)

User2 personal storage

![2mount](https://user-images.githubusercontent.com/10596560/51547881-6f57ca80-1e67-11e9-99dd-ca5f8b451e6d.png)

For user2:

![3mount](https://user-images.githubusercontent.com/10596560/51547885-72eb5180-1e67-11e9-83da-b1ce8eb037d4.png)

For user1:
![4mount](https://user-images.githubusercontent.com/10596560/51547896-75e64200-1e67-11e9-9a9a-c25082a338fa.png)

### Server configuration
Ubuntu 16.0.4. LTS

**Web server:**
Apache 2.4.x

**Database:**
MariaDB

**PHP version:**
7.1

**Where did you install ownCloud from:**
https://download.owncloud.org/community/testing/owncloud-10.1.0beta.tar.bz2

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @mmattel, and @PVince81.

Possibly related issues are https://github.com/owncloud/core/pull/34033 (Improve code occ files_external:list --short), https://github.com/owncloud/core/issues/32084 ([Feature Request] Improve files_external:list to show a short list of mounts for a given user), https://github.com/owncloud/core/pull/32178 (show a short list of mount infos: files_external:list --short), https://github.com/owncloud/core/issues/25345 (files_external:create with --user switch not creating mounts), and https://github.com/owncloud/core/issues/30641 ([Feature Request] extend ./occ files:scan to list scannable mounts for a given user).

**Comment by mmattel** [comment]
Pls also see: https://github.com/owncloud/core/pull/34033#issuecomment-455092635 where this PR claryfies the --all option (Show mounts for all users. All has precedence over user_id)
