### ISSUE TITLE
Share to group, receiver rename, share to user sometimes reverts the rename

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#34235]
``mergeShare.feature:82`` is failing intermittently in drone. I noticed a few yesterday. The scenario was enabled recently by PR #34200 after having been skipped for some time. Issue #29016 originally reported the intermittent failure, and the scenario was skipped in PR #29018

An example from last night:

https://drone.owncloud.com/owncloud/core/14522/398
```
  Scenario: Merging shares for recipient when shared from outside with group then user and recipient renames in between                                                     # /drone/src/tests/acceptance/features/apiShareManagement/mergeShare.feature:82
    Given user "user0" has created folder "/merge-test-outside-groups-renamebeforesecondshare"                                                                              # FeatureContext::userCreatesFolder()
    When user "user0" shares folder "/merge-test-outside-groups-renamebeforesecondshare" with group "grp1" using the sharing API                                            # FeatureContext::userSharesFileWithGroupUsingTheSharingApi()
    And user "user1" moves folder "/merge-test-outside-groups-renamebeforesecondshare" to "/merge-test-outside-groups-renamebeforesecondshare-renamed" using the WebDAV API # FeatureContext::userMovesFileUsingTheAPI()
    And user "user0" shares folder "/merge-test-outside-groups-renamebeforesecondshare" with user "user1" using the sharing API                                             # FeatureContext::userSharesFileWithUserUsingTheSharingApi()
    Then as user "user1" folder "/merge-test-outside-groups-renamebeforesecondshare-renamed" should contain a property "oc:permissions" with value "SRDNVCK"                # WebDavPropertiesContext::asUserFolderShouldContainAPropertyWithValue()
      Cannot find property "oc:permissions"
      Failed asserting that false is true.
And as "user1" folder "/merge-test-outside-groups-renamebeforesecondshare" should not exist # FeatureContext::asFileOrFolderShouldNotExist()
...

--- Failed scenarios:

    /drone/src/tests/acceptance/features/apiShareManagement/mergeShare.feature:82

176 scenarios (175 passed, 1 failed)
2023 steps (2021 passed, 1 failed, 1 skipped)
18m27.84s (16.31Mb)
runsh: Exit code of main run: 1
Makefile:193: recipe for target 'test-acceptance-api' failed
make: *** [test-acceptance-api] Error 1
```

To Do:
- [x] adjust existing test scenario to stop intermittent fails mergeShare.feature:82 #34242
- [ ] fix the bug
- [ ] adjust the test scenario to test properly/fully again

**Comment by phil-davis** [comment]
@PVince81 I got annoyed because this scenario was failing intermittently and being a pain for CI.
Dug around a bit and managed to have it happening intermittently locally as well as on drone.
The adjusted scenario in PR #34242 will now pass whether the bug happens or not - that will make CI reliable.

I chatted with @individual-it and we think this is a real-intermittent oC bug.

Your opinion? And schedule some lucky developer to look into it some day.

**Comment by PVince81** [comment]
so far I always thought it was due to the "share time" which can be more or less simultaneous when tests run fast. the order of the shares are based on share time.

I did add sorting also by share id in case the time is the same, but maybe some databases might also shuffle the ids ??

**Comment by phil-davis** [comment]
I will try in the morning with some sleep between each of the sharing and renaming steps, and see if that can make it more or less confused.
