### ISSUE TITLE
CAS and LDAP backend not working together anymore

### ISSUE THREAD

**Issue by cyworks** [owncloud/core#34233]
Hi,
Since the beginning of the year the CAS and LDAP backend not working together anymore.
In the database when OCA\UserCAS\User\Backend is set for a user only CAS working not the client or Owncloud form. When OCA\User_LDAP\User_Proxy is set only client or Owncloud form working.
We don't know where is the problem, we have this error on the log :
User <xxxxx> already provided by another backend(OCA\\User_LDAP\\User_Proxy !== OCA\\UserCAS\\User\\Backend), skipping."}
Returned account has different backend to the requested backend for sync

Thank you for your help

**Comment by PVince81** [comment]
when did it start happening ? were you using OC 9.1 and upgraded to OC 10.0 ?

the message you see exists since OC 10.0.0 due to changes in how user accounts are handled

**Comment by PVince81** [comment]
please use the issue template: https://github.com/owncloud/core/blob/master/.github/issue_template.md
