### ISSUE TITLE
split slow acceptance tests suites

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34264]
- [x] split the slowest acceptance tests into multiple suites, so that every job takes only around 20min #34330 
- [x] add new suites to LDAP tests https://github.com/owncloud/user_ldap/pull/367

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/pull/32369 (Split api acceptance suites), and https://github.com/owncloud/core/issues/33690 (cleanup acceptance tests WebDav trait).

**Comment by phil-davis** [comment]
A sample of "long-running" acceptance test suites (>20 minutes):
```
23 apiMain
22 apiShareManagement
31 apiWebdavOperations
26 apiWebdavProperties
32 webUIFiles
39 webUISharingExternal
36 webUISharingInternalUsers
32 webUIWebdavLocks
```
(Oracle phpunit is about 25 minutes)

**Comment by individual-it** [comment]
is this finished? closing?
