### ISSUE TITLE
Confusing notice about used space and limit

### ISSUE THREAD

**Issue by muirdok** [owncloud/core#34281]
Seems it's not a bug but it's confusing with not clear notice about usage space and limits when host has small volume. Especially when "unlimited" shows only used space.

### Steps to reproduce
1. Go to admin page and set limit more than 10GB for user 
2. Login via user
3. Go to "/settings/personal" and check limit status

### Expected behaviour
It shows current Limit and status. Like:
```You are using 4.7 MB of 512 GB (0.01 %)``` 
or
```You are using 4.7 MB of 9.3 GB (0.05 %) with limit 512 GB```

### Actual behaviour
```You are using 4.7 MB of 9.3 GB (0.05 %)```
### Server configuration
Centos 7 x64 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux with docker setup: 

```
[root@hub ~]# df -h
Filesystem               Size  Used Avail Use% Mounted on
/dev/mapper/centos-root   14G  4.2G  9.3G  31% /
devtmpfs                 3.9G     0  3.9G   0% /dev
tmpfs                    3.9G     0  3.9G   0% /dev/shm
tmpfs                    3.9G  9.0M  3.9G   1% /run
tmpfs                    3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/sda1               1014M  189M  826M  19% /boot
tmpfs                    783M     0  783M   0% /run/user/1000
overlay                   14G  4.2G  9.3G  31% /var/lib/docker/overlay2/b0f1969bdf4595991db7161ea3102f285b7822001fc243afb44853e1c98c948c/merged
shm                       64M     0   64M   0% /var/lib/docker/containers/05eec62587c6c2a4a4d435d254259a813d75b8f93d20a010d66eeb52b1e736bd/mounts/shm
overlay                   14G  4.2G  9.3G  31% /var/lib/docker/overlay2/cb662a46dbb5ad90fb477d5010aaa36800f6a66f241c78736e7fe0614dcd6536/merged
shm                       64M     0   64M   0% /var/lib/docker/containers/983cf36f4cfbe58f912d2c0d1543abe99c1945642d77a1f3ae219ac4c16f0998/mounts/shm
overlay                   14G  4.2G  9.3G  31% /var/lib/docker/overlay2/a585fb7e977f2632b4622426fd6818675637398e1894bd28937c97c6e7683c76/merged
shm                       64M     0   64M   0% /var/lib/docker/containers/50409461076c903b246be71cfd4c5554acab55ea998b4d7e96bd7226560f27ec/mounts/shm
[root@hub ~]# docker ps
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS                    NAMES
50409461076c        owncloud/server:10.0       "/usr/bin/entrypoint…"   2 hours ago         Up 2 hours          0.0.0.0:8080->8080/tcp   owncloud
983cf36f4cfb        webhippie/mariadb:latest   "/usr/bin/entrypoint…"   3 hours ago         Up 3 hours          3306/tcp                 mariadb
05eec62587c6        webhippie/redis:latest     "/usr/bin/entrypoint…"   3 hours ago         Up 3 hours          6379/tcp                 redis
[root@hub ~]#
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/2011 (Unable to set maximum Uploadsize), https://github.com/owncloud/core/issues/26581 (can not set speed limit for files from owncloud), https://github.com/owncloud/core/issues/18092 (Unable to set sub-shared folder's permission correctly), https://github.com/owncloud/core/issues/3615 (Can't have more than 10Gb of free space !), and https://github.com/owncloud/core/issues/6740 (setting upload speed limit has no effect).

**Comment by davitol** [comment]
@muirdok Following your tests steps:

![screen shot 2019-02-08 at 12 48 51](https://user-images.githubusercontent.com/10596560/52476803-1c3c8200-2ba0-11e9-81a8-ebd9d4c8f87e.png)
![screen shot 2019-02-08 at 12 48 12](https://user-images.githubusercontent.com/10596560/52476804-1c3c8200-2ba0-11e9-84ff-5c2272cdc54b.png)


I see the behaviour is fine:

 If you want to be able to see with a regular user the total space of the server, it is intended to not leak that info. So if it is the purpose of the ticket, let's close it.

Thanks for posting and reporting!
