### ISSUE TITLE
progress of automated acceptance tests for locks

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34292]
As we discovered that litmus does not test enough of the WebDAV locking this issue tracks the progress of automated acceptance tests for locks

## Lock symbol appears correctly in the webUI
0.5md to finish but IMO it would be over-engineering 

| things to check| user without email address | user with email address set | user with display-name set | lockscope | depth|
|----|----|----|----|----| --- |
| user locks own file/folder| :robot: | :robot: | :robot: | :robot: |
| user locks own folder, lock propagates into subfolders| :robot: | | | |  :robot: |
| owner locks shared file/folder|  | :robot: | :robot: | :robot: | 
| share receiver locks file/folder|  | :robot: | :robot: | :robot: | 
| share receiver re-shares file/folder|  | :robot: | :robot: | :robot: | 
| ~~public locks a file/folder~~ | :robot: | N/A | N/A| |
| multiple locks are set by various users| | :robot: | :robot: | N/A|
| unlocking by DAV removes the symbol |:robot: | 
| deleting the lock removes the symbol & lock of locked item |:robot: |||:robot: |
| deleting the lock removes the symbol & lock of locked sub items |:robot: |||:robot: |

## Locks can be deleted from the webUI
0.25md to finish

| things to check| exclusive | shared | 
|-----|---|--|
| owner deletes lock that was set by herself| :robot: | :robot: |
| share receiver deletes lock that was by herself |
| owner deletes lock that was set by share receiver |:robot: | :robot: |
| owner deletes lock that was set by the public|
| share receiver deletes lock that was set by owner|
| delete lock from a sub-element |

## operation on locked files/folders
1.5md to finish

owner locked - owner tries the operation: ol-oo
owner locked - share receiver tries the operation: ol-ro
share receiver locked - owner tries the operation: rl-oo
share receiver locked - share receiver tries the operation: rl-ro
~~owner locked - public tries the operation: ol-po~~
~~public locked - owner tries the operation: pl-oo~~
~~public locked - public tries the operation: pl-po~~

|operation|UI - ol-oo|UI - ol-ro|UI - rl-oo|UI - rl-ro|UI - ol-po|UI - pl-oo|UI - pl-po|DAV - ol-oo|DAV - ol-ro|DAV - rl-oo|DAV - rl-ro|DAV - ol-po|DAV - pl-oo|DAV - pl-po|
|----|-----|-----|-----|-----|-----|------|-----|-----|------------|------------|------------|------------|------------|------------|
|download|
|upload in locked folder|:robot:| | | | | | | :robot: |:robot: #34327 |:robot: #34327 |:robot: #34327 | :robot: |:robot: #34327|
|upload overwrite in locked folder|:robot:| | | | :robot: |:robot: #34327 | | | | | | :robot: |
|upload overwrite locked file |:robot:|
|rename|:robot:| | | | :robot: |
|move_locked|:robot:| | | | :robot: |
|move_in|:robot:|
|move_in_overwrite|:robot:|
|move_in_subdir|
|move_in_subdir_overwrite|
|move_out| | | | | | | |:robot: #34370|
|move_out_subdir|
|copy_in|
|copy_in_overwrite|
|delete|:robot:| | | | :robot: |
|mkdir| | | | | | | | :robot: | | | |  |
|rmdir|
|share| | | | | N/A| | | | | | | N/A| | N/A|
|unshare| | :robot: | | | N/A | | | | | | | N/A | | N/A|
|unlock|:robot: | | :robot: | | | | | :robot: #34303 |  :robot: #34303 |  :robot: #34303 |  :robot: #34303 |  :robot: #34303 |  :robot: #34303 |  :robot: #34303 | 
|lock exclusively locked| | | | | | | | | | | :robot: |
|accept share|N/A| | | | N/A | N/A|N/A|N/A| | | | N/A | N/A| N/A|
|decline share|N/A| :robot: | | | N/A |N/A| N/A|N/A| | | | N/A | N/A| N/A|
|accept declined share|N/A| :robot: | | | N/A |N/A| N/A|N/A| | | | N/A | N/A| N/A|
|decline accepted share|N/A| :robot: | | | N/A |N/A| N/A|N/A| | | | N/A | N/A| N/A|

more variations:
- with own token :robot: 
- with token of an other user but own username/password :robot: 
- reshared shares
- lockscope shared/exclusive
- ~~locks set in levels above the public link~~
- depth 0/infinity

## LOCKDISCOVERY
0.5md to finish

|  | lockroot | locktoken | timeout #33846 | owner | count of locks |
| ---- |  ---- |  ---- |  ---- |  ---- |  ---- |
| owner locked - owner tries discovery | | | :robot: #34320 | | :robot: |
| owner locked - share receiver tries discovery |  | | :robot: #34320 |
| share receiver locked - owner tries discovery | | |:robot: #34320 | | :robot: |
| share receiver locked -  share receiver tries discovery  | | | | | :robot: |
| owner locked - public tries discovery | :robot: | :robot: |:robot: #34320|
| ~~public locked - owner tries discovery~~ | | | :robot: #34320 |
| ~~public locked - public tries discovery~~ | :robot: | :robot: |

more variations:
- lockscope shared/exclusive
- discovery of various levels
- locks on various levels
- set timeouts
- refresh lock

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/32782 (Add automated phpcs checks in drone for acceptance test code), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), and https://github.com/owncloud/core/pull/31718 (Improve webUI autocompletion acceptance tests).

**Comment by PVince81** [comment]
as discussed, @individual-it @davitol please decide what items make sense to cover.

I guess some items might cover multiple cases so we don't need to cover the whole matrix

**Comment by individual-it** [comment]
I'm suggesting to close this for now, we have a couple of issues raised and can improve test coverage as the issues are fixed and functionality expanded
@PVince81 @davitol feel free to reopen the ticket if you feel its needed
