### ISSUE TITLE
public cannot unlock locks set by the public

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34302]
### Steps to reproduce
1. create a public link
2. as public set a LOCK on that link: `curl -u UKOyyBsCCgB0uV1: -X LOCK http://localhost/owncloud-core/public.php/webdav -d "<?xml version='1.0' encoding='UTF-8'?><d:lockinfo xmlns:d='DAV:'> <d:lockscope><d:shared/></d:lockscope></d:lockinfo>"`
3. remember the opaquelocktoken
4. use the opaquelocktoken to unlock: `curl -u UKOyyBsCCgB0uV1: -X UNLOCK http://localhost/owncloud-core/public.php/webdav/test -H "Lock-Token: opaquelocktoken:98f26b1e-7f56-464f-8e07-ef8d6cdfe22d"`

### Expected behaviour
Lock is cleared

### Actual behaviour
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\LockTokenMatchesRequestUri</s:exception>
  <s:message>The locktoken supplied does not match any locks on this entity</s:message>
  <d:lock-token-matches-request-uri/>
</d:error>
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/32779 (Cannot set up ), https://github.com/owncloud/core/issues/34300 (empty lock-token when unlocking public link results in an exception), https://github.com/owncloud/core/pull/34268 (Hide lock token in public webdav responses), https://github.com/owncloud/core/issues/8279 (Logger not public?), and https://github.com/owncloud/core/issues/26838 (File locking).

**Comment by PVince81** [comment]
known issue for now... I wonder if we should prevent locking in public in the first place as it feels useless like this.

cc @pmaier1

**Comment by PVince81** [comment]
obsoleted by https://github.com/owncloud/core/pull/34351
