### ISSUE TITLE
public cannot upload files in locks set by the public

### ISSUE THREAD

**Issue by davitol** [owncloud/core#34304]
### Steps to reproduce
1. create a public link and remember the link token.
2. as public set a LOCK on that link: `curl -u 5M5N2dEXhsgDuNW: -X LOCK http://http://10.40.40.222:9681/public.php/webdav -d "<?xml version='1.0' encoding='UTF-8'?><d:lockinfo xmlns:d='DAV:'> <d:lockscope><d:shared/></d:lockscope></d:lockinfo>"`
3. remember the opaquelocktoken
4. use the opaquelocktoken to re-upload the file: `curl -v -u 5M5N2dEXhsgDuNW: -H 'Lock-Token: <opaquelocktoken:57b7661b-5635-4b1e-a1ee-f56bd9e89e2e>' -H 'User-Agent:Mozilla/5.0 (Android) ownCloud-android/2.7.0' -H 'Host:10.40.40.222:9681' -X PUT 'http://10.40.40.222:9681/public.php/webdav/simio.txt'`

### Expected behaviour
The file is uploaded

### Actual behaviour

```
curl -v -u 5M5N2dEXhsgDuNW: -H 'Lock-Token: <opaquelocktoken:57b7661b-5635-4b1e-a1ee-f56bd9e89e2e>' -H 'User-Agent:Mozilla/5.0 (Android) ownCloud-android/2.7.0' -H 'Host:10.40.40.222:9681' -X PUT 'http://10.40.40.222:9681/public.php/webdav/simio.txt'
*   Trying 10.40.40.222...
* TCP_NODELAY set
* Connected to 10.40.40.222 (10.40.40.222) port 9681 (#0)
* Server auth using Basic with user '5M5N2dEXhsgDuNW'
> PUT /public.php/webdav/simio.txt HTTP/1.1
> Host:10.40.40.222:9681
> Authorization: Basic NU01TjJkRVhoc2dEdU5XOg==
> Accept: */*
> Lock-Token: <opaquelocktoken:57b7661b-5635-4b1e-a1ee-f56bd9e89e2e>
> User-Agent:Mozilla/5.0 (Android) ownCloud-android/2.7.0
>
< HTTP/1.1 423 Locked
< Date: Tue, 29 Jan 2019 11:42:37 GMT
< Server: Apache
< Strict-Transport-Security: max-age=15768000; preload
< Set-Cookie: oc60ut66c69v=7143cgl2g7aqc1aldkl9fcnfv2; path=/; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=2rbx3XKWe8vM9kBKc%2BPsC%2BtSim8I9KUtk%2FKZYoEESsDPvLHwPoRBvdt36MYZ%2B4hlto10JI8rPkFwr6iyhvV5zK%2FJkxqaH8%2B3%2Fra4hycbjTwB0uXfTzlGR4j2pddpd9ai; path=/; HttpOnly
< Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Robots-Tag: none
< X-Frame-Options: SAMEORIGIN
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Content-Length: 265
< Content-Type: application/xml; charset=utf-8
<
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Locked</s:exception>
  <s:message/>
  <d:lock-token-submitted>
    <d:href>simio.txt</d:href>
  </d:lock-token-submitted>
</d:error>
* Connection #0 to host 10.40.40.222 left intact
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/583 (Can't upload files), https://github.com/owncloud/core/issues/13618 (can not upload file), https://github.com/owncloud/core/issues/34302 (public cannot unlock locks set by the public), https://github.com/owncloud/core/issues/28991 (file is locked), and https://github.com/owncloud/core/issues/24737 (File Locked).

**Comment by PVince81** [comment]
known issue for now... I wonder if we should prevent locking in public in the first place as it feels useless like this.

cc @pmaier1

**Comment by PVince81** [comment]
obsoleted by https://github.com/owncloud/core/pull/34351
