### ISSUE TITLE
Changing user display name does not change lock owner name

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#34315]
1. login as some user ``Alice`` with display name set to ``Original Name``
2. lock a file or folder
3. change your display name to ``New name``
4. view the locks tab of the file/folder details

## Expected result
Lock owner is displayed as ``New Name``

## Actual result
Lock owner is displayed as ``Original Name``

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/3101 (Admin user can't change the Display Name of other Users), https://github.com/owncloud/core/issues/809 (Lock or disable users), https://github.com/owncloud/core/issues/1503 (Changing user password doesn't trigger hook listeners), https://github.com/owncloud/core/issues/1371 (Display name not editable by user), and https://github.com/owncloud/core/issues/9544 (Can't Change Full Name for Users).

**Comment by phil-davis** [comment]
The ``oc_persistent_locks`` table has stuff like:

```
mysql> select * from oc_persistent_locks;
+----+------------+------------------+---------------+---------+------------+--------------------------------------+----------------------------------+-------+-------+
| id | file_id    | owner_account_id | owner         | timeout | created_at | token                                | token_hash                       | scope | depth |
+----+------------+------------------+---------------+---------+------------+--------------------------------------+----------------------------------+-------+-------+
|  9 | 2147492032 |               57 | My fancy name |    1800 | 1548833262 | 9b86317e-6f3f-4d6b-91f3-2bd78029573a | dd2eb08e480e12c4277a178e96475572 |     2 |    -1 |
| 10 | 2147492031 |               57 | My fancy name |    1800 | 1548833262 | 458ee95b-a353-4876-abda-d331c3d9e537 | 8cbfb6821e0649a5afec948a325ea5f2 |     1 |    -1 |
+----+------------+------------------+---------------+---------+------------+--------------------------------------+----------------------------------+-------+-------+
2 rows in set (0.00 sec)
```
So I guess that ``owner`` field becomes stale.

Maybe the ``owner`` should be the username, and the current display name should be looked up on-the-fly.

**Comment by phil-davis** [comment]
Removed the QA-team label because this has a test to cover the behavior.
