### ISSUE TITLE
acceptance tests for timeout section in LOCKDISCOVERY

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34314]
see https://github.com/owncloud/core/issues/34292

for issues see:
#33846
#33778
#34100

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/33975 (acceptance test share expiry date test fails), and https://github.com/owncloud/core/issues/33690 (cleanup acceptance tests WebDav trait).
