### ISSUE TITLE
acceptance tests for locks on reshared shares

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34322]
does the lock propagate correctly if a file/folder is shared multiple times and locked on various places
also check behaviour is case of renaming after sharing

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/pull/32734 (Acceptance test steps for public link share), and https://github.com/owncloud/core/pull/32559 (acceptance tests - stop uploading when receiving an error).
