### ISSUE TITLE
[Fed Sharing] Shared Folder appears splitted in a Folder + File locked if we lock the folder in the receiver server before accepting it

### ISSUE THREAD

**Issue by davitol** [owncloud/core#34346]
### Steps to reproduce

1. From server A  share folder to server B
2. Via CLI, Lock the folder in server B
`curl -u admin:admin -X LOCK http://10.40.40.198:20680/remote.php/webdav/App -d "<?xml version='1.0' encoding='UTF-8'?><d:lockinfo xmlns:d='DAV:'> <d:lockscope><d:exclusive/></d:lockscope></d:lockinfo>"`
3. Accept the shared folder in server B

### Expected behaviour

Folder should appear in serverB locked. 

### Actual behaviour
Folder appears splitted in a Folder + File locked

![screen shot 2019-01-31 at 14 20 18](https://user-images.githubusercontent.com/10596560/52057279-ed515b00-2564-11e9-8497-50e2a089f7bb.png)

Note: I think it is low priority because it is difficult to happen in a real scenario due to the receiver cannot lock a file before it is accepted due to it does not appear in the webUI. Same steps but lockiing in server A works fine

(cc @PVince81 jfyi)

**Comment by PVince81** [comment]
@davitol since you did not accept the folder yet at step 2, the LOCK command will create a new resource as per the spec. So when accepting the folder it will deduplicate and see that there is already such resource. This is expected behavior.

**Comment by davitol** [comment]
Agree with your comment @PVince81 let's close the ticket

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/19434 (Fed. sharing via HTTPS, the files shared do not appear in server B), https://github.com/owncloud/core/issues/24737 (File Locked), https://github.com/owncloud/core/issues/26838 (File locking), https://github.com/owncloud/core/issues/34338 (share receiver can rename a file in a locked folder by using the loktocken of the owner), and https://github.com/owncloud/core/issues/34343 (items in received fed shares that are locked by receiver do not show lock icon).
