### ISSUE TITLE
extra "/" in DAV URL makes server return "500 Internal Server Error"

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34365]
### Steps to reproduce
1. access webDAV endpoint with an extra `/` before `remote.php` e.g `curl -u admin:admin  "http://localhost/owncloud-core//remote.php/dav/files/admin/welcome.txt"  -v`

### Expected behaviour
nice error with some 4xx code returned

### Actual behaviour
500 Internal Server Error

### Server configuration
**Operating system**:
Ubuntu
**Web server:**
Apache2
**Database:**
SQLite
**PHP version:**
7.1.26
**ownCloud version:** (see ownCloud admin page)
11.0.0 prealpha (git) 
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oce1t8r2vis9",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "172.17.0.1"
        ],
        "datadirectory": "\/home\/artur\/www\/owncloud-core\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud-core",
        "dbtype": "sqlite3",
        "version": "11.0.0.0",
        "logtimezone": "UTC",
        "htaccess.RewriteBase": "\/owncloud-core\/",
        "ldapIgnoreNamingRules": false,
        "enable_previews": false,
        "csrf.disabled": true,
        "loglevel": 0,
        "theme": "",
        "license-key": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "1025",
        "sharing.federation.allowHttpFallback": true,
        "files_external_allow_create_new_local": "true",
        "skeletondirectory": "\/home\/artur\/www\/owncloud-core\/tests\/acceptance\/..\/..\/apps\/testing\/data\/apiSkeleton",
        "log_type": "owncloud",
        "firewall.debug": 1,
        "maintenance": false,
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "dav.enable.async": true
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity: 2.4.1
  - comments: 0.3.0
  - dav: 0.4.0
  - diagnostics: 0.1.3
  - enterprise_key: 0.1.4
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_texteditor: 2.2.1
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firewall: 2.7.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - systemtags_management: 0.3.1
  - testing: 0.1.0
  - user_management: 0.0.1
  - windows_network_drive: 0.7.2
  - workflow: 0.3.0
Disabled:
  - brute_force_protection
  - files_antivirus
  - files_classifier
  - files_primary_s3
  - guests
  - multidirtest
  - notifications
  - oauth2
  - password_policy
  - ransomware_protection
  - search_elastic
  - twofactor_totp
  - updatenotification
  - user_ldap

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### ownCloud log (data/owncloud.log)
```{"reqId":"rIW2E7vfRsC5tszMac8O","level":3,"time":"2019-02-04T07:40:28+00:00","remoteAddr":"127.0.0.1","user":"--","app":"remote","method":"GET","url":"\/owncloud-core\/\/remote.php\/dav\/files\/admin\/welcome.txt","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Forbidden\",\"Message\":\"Requested uri (\\\/owncloud-core\\\/remote.php\\\/dav\\\/files\\\/admin\\\/welcome.txt) is out of base uri (\\\/owncloud-core\\\/\\\/remote.php\\\/dav\\\/)\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(534): Sabre\\\\DAV\\\\Server->calculateUri('\\\/owncloud-core\\\/...')\\n#1 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/Server.php(309): Sabre\\\\DAV\\\\Server->getRequestUri()\\n#2 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/lib\\\/Server.php(148): OCA\\\\DAV\\\\Server->isRequestForSubtree(Array)\\n#3 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->__construct(Object(OC\\\\AppFramework\\\\Http\\\\Request), '\\\/owncloud-core\\\/...')\\n#4 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/remote.php(175): require_once('\\\/home\\\/artur\\\/www...')\\n#5 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":568}"}
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/8414 (Internal Server error 500), https://github.com/owncloud/core/issues/1153 (Internal Server Error 500), https://github.com/owncloud/core/issues/24525 (Internal server error), https://github.com/owncloud/core/issues/26089 (Internal Server Error), and https://github.com/owncloud/core/issues/9324 ("Internal Server Error").

**Comment by wnabrud** [comment]
@PVince81 this bug was already solved in some other place, since can not reproduce.

**Comment by individual-it** [comment]
ToDo QA-team: 
- [ ] try to reproduce on current master
- [ ] bisect when it was fixed
- [ ] add API tests that fail before and pass after the fix

**Comment by dpakach** [comment]
@individual-it the issue dosn't exist in current master
I tryed to do git bisect i cannot build core on the old version, with error
```
Building core

Note: You can type 'make help' for more targets

php build/composer.phar install --dev

                                                                                                                       
  [RuntimeException]                                                                                                   
  require.icewind/Streams is invalid, it should not contain uppercase characters. Please use icewind/streams instead.  
                                                                                                                       

make: *** [Makefile:134: lib/composer/phpunit] Error 1
```

I'll try adding test for this so we dont get regressions later

**Comment by phil-davis** [comment]
Older versions of core will need `composer` 1.* and the current core master needs `composer` 2.*. So it is now more difficult to checkout old core tags and just do `make`... That is annoying. With some effort you could try to install `composer` 1.* on your local system.

**Comment by wnabrud** [comment]
> 
> 
> @individual-it the issue dosn't exist in current master
> I tryed to do git bisect i cannot build core on the old version, with error
> 
> ```
> Building core
> 
> Note: You can type 'make help' for more targets
> 
> php build/composer.phar install --dev
> 
>                                                                                                                        
>   [RuntimeException]                                                                                                   
>   require.icewind/Streams is invalid, it should not contain uppercase characters. Please use icewind/streams instead.  
>                                                                                                                        
> 
> make: *** [Makefile:134: lib/composer/phpunit] Error 1
> ```
> 
> I'll try adding test for this so we dont get regressions later

How did you test this, since in the bug says is version 11.0.0 alpha, with php 7.1 and first, I can not find version 11 and php 7.1 is not supported anymore in version 10.5

**Comment by phil-davis** [comment]
Note: ownCloud version `11.0.0 prealpha (git)` would have been in the days when `master` branch was bumped to major version 11, and there was a `stable10` branch that we backported everything to... That all changed "a long time ago" and that `master` branch was "removed" and the `stable10` branch became `master` ... And PHP 7.1 was in use back then (we had not removed support for it back in early 2019)

I am not sure about the Operating System: `Ubuntu 10.04` - that seems too old, but no way to really know now.

**Comment by phil-davis** [comment]
@dpakach maybe we just add a few test scenarios that insert extra `//` in URLs at various points and check that "something reasonable" happens. And then close this issue. (It looks like it will be difficult to find the version of code where this used to happen)

**Comment by dpakach** [comment]
Tests added in https://github.com/owncloud/core/pull/38369

**Comment by individual-it** [comment]
I'm pretty sure `Ubuntu 10.04` was a typo of mine I've changed it to `Ubuntu`. Looking at the date it must have been `18.04` or more likely a pre-release of `19.04`

**Comment by wnabrud** [comment]
> 
> 
> Tests added in #38369

Hi @dpakach , I checked you test, and is awesome the work you put in that, but is not testing the double slash that is reported here, since is reporting a double slash before the remote.php, not after as in the test. Am I right?

**Comment by dpakach** [comment]
> > Tests added in #38369
> 
> Hi @dpakach , I checked you test, and is awesome the work you put in that, but is not testing the double slash that is reported here, since is reporting a double slash before the remote.php, not after as in the test. Am I right?

@wnabrud you're right, thanks for noticing, I've updated the tests so now they check the `//` on different parts of the URL

**Comment by dpakach** [comment]
seems like it works when owncloud is hosted in the root then we cannot have 2 slashes immediately after that.
for eg if owncloud is hosted in `http://localhost`,
then making request `http://localhost//remote.php/dav/files/admin/welcome.txt` will give 500 response

But if owncloud is hosted in subfolder, then it works
for eg if owncloud is hosted in `http://localhost/owncloud-core`
then we can make request to `http://localhost/owncloud-core//remote.php/dav/files/admin/welcome.txt`, will work

since the example given in the issue description is the later one, so this particular issue seems to be fixed. 
But this may not be the problem with owncloud but rather with the webserver used.(I'm using apache)

Since we run our owncloud server on `http://owncloud` for the tests in CI, the tests added in #38369 all failed. 
cc @phil-davis @individual-it @wnabrud

**Comment by individual-it** [comment]
@dpakach if you feel the bug is an other one, then feel free to close this issue and open a new one, also convert the tests to bug-demonstration tests
If you feel enthusiastic you can try to dig in and find out if its a setup issue with apache or an owncloud issues (routes?)

**Comment by wnabrud** [comment]
Will try to reproduce the error and find a fix for the scenario you described @dpakach

**Comment by wnabrud** [comment]
I could find the error, but not sure what will be a good fix. The error originate in file core/lib/private/AppFramework/Http/Request.php in method getRequestUri(). The error happens because is using wrongly the method parse_url to parse a URI. The double slash at the beginning confuse the function to detect the //remote.php as host and not as path.
My proposal will be to do a  preg_replace('/^\/\/+/','/',$var); to remove all the / from the beginning. 
I am testing 10.0.9 but the error is present in all versions.
A good test also here will help.

**Comment by individual-it** [comment]
this URL seems to give also a 500 error with `MKCOL`  `http://localhost/owncloud-core////remote.php/dav/files/admin//testFolder`

**Comment by phil-davis** [comment]
Tests were added in #38369
Those test scenarios are in https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiAuthWebDav/webDavMultiSlashOC10Issue34365.feature

There are still combinations that give a `500` response. So this issue should still be open.
