### ISSUE TITLE
Permission checking

### ISSUE THREAD

**Issue by WisseHesNL** [owncloud/core#34397]
### Steps to reproduce
1. make a folder
2. use plex or something and point it to the folder in the data folder
3. you see it is empty or a message "you do not have permission to view this" or something like that

### Expected behaviour
I expected it to not reset the permissions of the data folder

### Actual behaviour
it resets the permissions of the data folder everytime i set it to 0774

### Server configuration
**Operating system**:
DietPi
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
PHP 7.0.33-0+deb9u1 (cli) (built: Dec  7 2018 11:36:49) ( NTS )
**ownCloud version:** (see ownCloud admin page)
10.0.10
**Where did you install ownCloud from:**
the DietPi-software command
**Signing status (ownCloud 9.0 and above):**
i don't know what this is 
```
there were no errors found
```
```
<?php
$CONFIG = array (
  'instanceid' => 'ocz78rryn3q5',
  'passwordsalt' => '****',
  'secret' => '****',
  'trusted_domains' => 
  array (
    0 => '****',
    1 => '****',
    2 => '****',
    3 => '****',
  ),
  'datadirectory' => '/datastore',
  'overwrite.cli.url' => 'https://****/owncloud',
  'dbtype' => 'mysql',
  'version' => '10.0.10.4',
  'dbname' => 'owncloud2',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '***',
  'dbpassword' => '***',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_domain' => '***',
  'mail_from_address' => 'mail',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => '****',
  'mail_smtpport' => '2025',
  'mail_smtpauth' => 1,
  'mail_smtpname' => '****',
  'mail_smtppassword' => '****',
);
```

okay, so i just wanted plex to use a folder inside the data folder to load al the music and movies and stuff but i have to set the permissions to 0774, and a minute or so later it doesn't work anymore. How do i turn permission checking off?
thanks for your help.
![afbeelding](https://user-images.githubusercontent.com/31771656/52370214-9fe85880-2a52-11e9-9bb8-01e4b38ed3cd.png)
(i'm Dutch so if the text on the image isn't clear please use Google Translate or something)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/11472 (Trashbin checks wrong permissions when restoring files), https://github.com/owncloud/core/pull/26684 (Make share permission check work correctly from share manager), https://github.com/owncloud/core/issues/30225 (integrity check issue), https://github.com/owncloud/core/issues/25927 (CSRF check failed), and https://github.com/owncloud/core/issues/23769 (Integrity check always fails).

**Comment by ho4ho** [comment]
@WisseHesNL Bugtracker no good for support questions?

**Comment by PVince81** [comment]
@WisseHesNL please don't let any external software mess with the "data" folder. It is intended to be used exclusively by ownCloud.

See if said external software has Webdav support and let it talk to ownCloud using APIs.

This isn't an ownCloud bug, closing.
