### ISSUE TITLE
stderr: PHP message: PHP Notice:  Undefined index: path in /var/webroot/a01/lib/private/AppFramework/Http/Request.php on line 618

### ISSUE THREAD

**Issue by kerins** [owncloud/core#34392]
https://github.com/owncloud/core/blob/ea04a429a4538ab888f607e0d6b252a405089468/lib/private/AppFramework/Http/Request.php#L618

Should this line be moved down line 625 to avoid the error I pasted

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/12266 (Undefined index), https://github.com/owncloud/core/issues/24919 (PHP Error: Undefined index: path), https://github.com/owncloud/core/issues/11875 (PHP Notice:  Undefined index: activity in /home/deepdiver/Development/ownCloud/core/lib/private/app.php on line 994), https://github.com/owncloud/core/issues/8817 (Undefined index in lib/public/share.php on line 743), and https://github.com/owncloud/core/issues/12514 (HTTP-request to WebRoot).

**Comment by VicDeo** [comment]
I don't think so, moving the line 618 to 625 makes no sense to me.
if `$components['path']` is undefined in line 618 - it is undefined everywhere.
It could be a PHP bug but the proposed  solution does not look legit.

I'd suggest to replace L618 with 
`$uri = isset($components['path']) ? $components['path'] : '';` 
instead

**Comment by Gordon01** [comment]
I still have this issue on 10.3.2
