### ISSUE TITLE
[stable10] Update links for documentation to 10.1 version

### ISSUE THREAD

**Issue by davitol** [owncloud/core#34396]
**Bug 1**

Using oC 10.1 tarball. Documentation links from the screenshots are pointing to 10.0.X documentation.

<img width="460" alt="screen shot 2019-02-06 at 18 13 11" src="https://user-images.githubusercontent.com/10596560/52401415-e032ef80-2ac1-11e9-823f-2e92b026261f.png">

<img width="209" alt="screen shot 2019-02-06 at 18 03 35" src="https://user-images.githubusercontent.com/10596560/52366879-11240d80-2a4b-11e9-957e-44df30416371.png">
<img width="914" alt="screen shot 2019-02-06 at 18 00 50" src="https://user-images.githubusercontent.com/10596560/52366880-11240d80-2a4b-11e9-8e0c-a73833dc91de.png">

Those links send you to https://doc.owncloud.com/server/10.0/user_manual?to=user-manual

**Bug 2**

Click on the text of the screenshot in files view:
<img width="102" alt="screen shot 2019-02-07 at 10 17 21" src="https://user-images.githubusercontent.com/10596560/52401317-abbf3380-2ac1-11e9-8e27-e378d21de5cc.png">

It seems the 10.1 documentation misses some pages. e.g. webdav

<img width="988" alt="screen shot 2019-02-06 at 20 10 37" src="https://user-images.githubusercontent.com/10596560/52367015-58120300-2a4b-11e9-8d9a-a2fd7012d037.png">

Tested with owncloud 10.1 tarball

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/21366 (Update), https://github.com/owncloud/core/issues/20661 (Update), https://github.com/owncloud/core/pull/33242 ([stable10] Set versions to 10.1 for semver), https://github.com/owncloud/core/pull/33958 ([stable10] Update changelog for 10.1 beta), and https://github.com/owncloud/core/pull/34373 ([stable10] Update changelog before 10.1.0 RC2).

**Comment by ho4ho** [comment]
404 caused of https://github.com/owncloud/docs/issues/564 ?

**Comment by PVince81** [comment]
from what I see we still use the first two digits: https://github.com/owncloud/core/blob/stable10/lib/private/legacy/defaults.php#L72

we need to sort out the URL model @settermjd @tboerger

**Comment by settermjd** [comment]
Currently, the latest version doesn't have a version number in the URL. Only prior versions.

**Comment by phil-davis** [comment]
For me on ``stable10`` the "Help & Tips" links point to ``10.1`` URLs - which is what I expect to happen, and documentation will appear there in due course.

**Comment by davitol** [comment]
From 10.0.10 it was probably my error while testing sorry for the noise

The doc links from 10.1.0 will point to the 10.1 docs which is currently a 404 URL.
The docs team will make sure there is a proper redirect in the coming days.
So let's close this ticket as dupe of https://github.com/owncloud/docs/issues/564

**Comment by settermjd** [comment]
Just created https://github.com/owncloud/docs/pull/589 to update the docs for version 10.1 and https://github.com/owncloud/docs/pull/587 to correct version 10.0.
