### ISSUE TITLE
Tests for emojis in comments

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#34419]
Review and create a reasonable set of acceptance tests for emojis in comments.

See PR #27332 for an old attempt and discussion.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/21397 (Multiple conflicts with emojis), and https://github.com/owncloud/core/issues/22367 (Security Check: Comments).
