### ISSUE TITLE
Update to 10.0.10 failed, hints to uninstall apps won't help

### ISSUE THREAD

**Issue by chst77** [owncloud/core#34425]
### Steps to reproduce
1. Press "Update" in admin area (to update the owncloud version)
2. Gone to maintenance mode for more then one week

### Expected behaviour
I wanted to have a fresh 10.0.10 version running

### Actual behaviour
The maintainance mode was turned on forever. Then I tried to get going again by this:

`su -u www-data php occ maintenance:mode --off`

then I tried the whole "suite":

`su -u www-data php occ maintenance:mode --on`
`su service cron stop`
`su service apache2 stop`
`su service apache2 start`
`su service cron start`
`su -u www-data php occ maintenance:mode --off`

I had no feedback or status from console any time.

But after that I saw the maintenance page in the browser. Update seemed possible. But hitting "Aktualisierung starten" always got me this:

You have incompatible or missing apps enabled that could not be 
found or updated via the marketplace.
Reperaturwarnung:Please install or update the following apps 
manually or disable them with: occ app:disable calendar 
occ app:disable contacts occ app:disable gallery occ app:disable 
impersonate occ app:disable templateeditor

So I did this:

`su -u www-data php occ maintenance:mode --on`
`su service cron stop`
`su service apache2 stop`
`su -u www-data php occ app:disable calendar`
`su -u www-data php occ app:disable contacts`
`su -u www-data php occ app:disable gallery`
`su -u www-data php occ app:disable impersonate`
`su -u www-data php occ app:disable templateeditor`
`su -u www-data php occ maintenance:mode --off`
`su service apache2 start`
`su service cron start`

Without any reaction. Service has stopped and left me without any idea.

### Server configuration
**Operating system**:
debian
**Web server:**
apache2
**Database:**
mysql
**PHP version:**
5.2
**ownCloud version:** (see ownCloud admin page)
10.0.10
**Updated from an older ownCloud or fresh install:**
updated from 10.0.3?
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/31345 (update to 10.0.0.8 failed), https://github.com/owncloud/core/issues/28205 (Update to 10.0.2), https://github.com/owncloud/core/issues/32388 (Failed update to 10.0.9), https://github.com/owncloud/core/issues/23244 (Update to 9.0.0 failed), and https://github.com/owncloud/core/issues/3041 (Update to 5.0.5 failing).

**Comment by ho4ho** [comment]
Miss?

```
su -u www-data php occ maintenance:mode --on
su -u www-data php occ upgrade
su -u www-data php occ maintenance:mode --off
```

**Comment by davitol** [comment]
@chst77 did you try the steps posted by @ho4ho ?
Those are the ones that will let you make the upgrade. Any more feedback about the current status of your server?

**Comment by VicDeo** [comment]
I'm closing this issue due to the lack of feedback. Feel free to reopen if the problem still persists.
