### ISSUE TITLE
make CI cache more reliable

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34435]
https://github.com/owncloud/core/pull/34333 bumped [bowser](https://github.com/ded/bowser) to a version that introduced a problem in oC (sharing not possible)
CI did not catch the issue because the old bowser version came from the cache. See https://github.com/owncloud/core/pull/34433, that PR fails (correctly) because it disables the cache.
So currently we are not sure what versions of libs we are testing. The bug surfaced only after the QA tarball was build (I guess using none or an other cache than the CI) and was used in other tests for federation sharing (sharing from the federation server does not work).
Two things need to be done to improve the situation and help to test what we fly and fly what we test:

1. we need to move away from caching the final dirs - to caching the package manager cache
example is here: https://github.com/owncloud/files_primary_s3/blob/master/.drone.yml#L75-L79
2. automatically run all smoke tests after every tar ball build.  E.g. we could have a nightly job that downloads the current tarballs and runs all smoke tests on it. Or the build of the tarball itself can happen on drone. Drone builds the tarball, unpacks it again, runs all smoke tests and if all is fine uploads the tarball.

CC @PVince81 @patrickjahns @phil-davis

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/23455 (Make chunk cache ttl configurable), https://github.com/owncloud/core/issues/23506 (ceph ci issues), https://github.com/owncloud/core/pull/33329 (Make then steps more specific), https://github.com/owncloud/core/pull/28166 (Cache in filecache), and https://github.com/owncloud/core/issues/12873 (Make installer deletable).

**Comment by patrickjahns** [comment]
> 2\. automatically run all smoke tests after every tar ball build.  E.g. we could have a nightly job that downloads the current tarballs and runs all smoke tests on it. Or the build of the tarball itself can happen on drone. Drone builds the tarball, unpacks it again, runs all smoke tests and if all is fine uploads the tarball.

You can start with a nightly test repository (similar to litmus / smashbox ) and do the following:
- fetch the nightly "release" tarball similar to it is done in smashbox/litmus
- clone the stable10 branch and execute the tests from that repository ( or use the nightly-qa-tarball as tests folder )

**Comment by PVince81** [comment]
PR here https://github.com/owncloud/core/pull/34700

@patrickjahns can you confirm that this is the same thing ? if yes please close
