### ISSUE TITLE
Tests for emojis in various places

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#34437]
Issue #34419 provided acceptance tests for emojis embedded in comments, and creating folders with names containing emojis via the API.

Here are a few more places that people could conceivably use emojis:

Using the API:
- [x] embedded in a group named like "🚴 cycling" (and be able to share with such a group)
- [x] embedded in a tag name
- [x] embedded in a user full name (yes, users can do this themselves)
- [x] passwords with emojis
- [x] search for file names that contain emojis

Using the webUI:
similar list to API?

Make acceptance tests to verify the above are working.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/pull/27914 (Test calendar object with various characters), and https://github.com/owncloud/core/pull/30567 ([stable10] Test calendar object with various characters).

**Comment by individual-it** [comment]
one problem we did face today trying to do that is that its difficult to have emojis in XPATH

**Comment by individual-it** [comment]
API groupnames with emojis tests in #35247

**Comment by davitol** [comment]
>     * embedded in a tag name

@phil-davis Do you refer to this already created test? https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiTags/createTags.feature#L25

If so, let's mark the checkbox of the open post

**Comment by individual-it** [comment]
@bhawanaprasain please list the PRs you have done for that issue here

**Comment by bhawanaprasain** [comment]
@individual-it these are the PRs related to emojis  #35247  #35286 #35300 #35315 #35317

**Comment by phil-davis** [comment]
I updated the list in the first post.
Remaining item is using emojis in a user full name.

**Comment by phil-davis** [comment]
Emojis acceptance tests have been done for the above areas using the API.

In the webUI you have to find trickier ways to "type" emojis into fields. See `fillFieldWithCharacters()` added in PR #34420

@individual-it do we leave this open and try to get emojis working in more parts of the webUI?

**Comment by individual-it** [comment]
yes, lets leave it open
@bhawanaprasain please link your new PRs to this issue

**Comment by Talank** [comment]
@sakshamgurung is working on this

**Comment by individual-it** [comment]
more emoji tests were added in #39033 :rocket: 
I think we can close this :boom:
