### ISSUE TITLE
Acceptance tests for dots in path

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#34442]
See https://github.com/owncloud/core/pull/26143#issuecomment-461831159

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/33345 (Use new webDAV path in upload to share acceptance test), and https://github.com/owncloud/core/pull/32347 (Add getters for private vars of acceptance test traits).

**Comment by phil-davis** [comment]
Looking at that linked comment and PR, we should cover upload/download/rename/delete for folder/file combinations like:

- [ ] folder and/or file ends with a dot `/folder./file.`
- [ ] folder has dot in the name `/folder.1/file.txt`
- [ ] folder and/or file has multiple dots `/folder..1../file..name..`
- [ ] folder and/or file is actually all dots (3 or more) `/.../...`
- [ ] folder and or file starts with dot (hidden files - we might already have those cases?)
- [ ] folder and or file starts with 2 dots `/..folder/..file`

And other unusual combinations that you think might cause trouble ;)
