### ISSUE TITLE
Disable PHP cache control

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#34441]
Do this in base.php.

See https://github.com/owncloud/core/pull/30178 for context.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @butonic.

Possibly related issues are https://github.com/owncloud/core/pull/30178 (disable php cache control), https://github.com/owncloud/core/issues/2990 (owncloud sets bad HTTP cache-control headers), https://github.com/owncloud/core/issues/596 (lib/cache/xcache.php), https://github.com/owncloud/core/pull/29706 (View.php - Trigger cache if size is not set), and https://github.com/owncloud/core/issues/681 (Missing options due disabled PHP option "allow_url_fopen").
