### ISSUE TITLE
Support for PHP 7.3

### ISSUE THREAD

**Issue by csware** [owncloud/core#34464]
For ownCloud 10.0.10 support for PHP 7.2 was introduced and officially announced.

What about PHP 7.3?

I saw a commit aaf8c033ccddaf4a37d47f9b41ef86a1cc8bbc32 which seems to enable PHP 7.3, what about an official statement (e.g., on https://doc.owncloud.org/server/10.1/administration_manual/installation/system_requirements.html)?

Also requested here: https://central.owncloud.org/t/this-version-of-owncloud-is-not-compatible-with-php-7-3/17531

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/18791 (Stable 7 broken on php 5.3), https://github.com/owncloud/core/issues/17783 (Prepare for PHP 7), https://github.com/owncloud/core/issues/12606 ([master] Dropping PHP 5.3 support), https://github.com/owncloud/core/issues/27570 (PHP 7.1 not supported error), and https://github.com/owncloud/core/issues/12205 (PHP fatal error after upgrade to 7.0.3).

**Comment by DeepDiver1975** [comment]
PM decision @pmaier1

**Comment by MacroMan** [comment]
Ubuntu 18.04 has started upgrading to php 7.3 as of today. New installs will also be 7.3.
If the new version of owncloud isn't going to be released very soon, you may wish to issue guidance on how to run with php 7.2 manually.

**Comment by scrobbleme** [comment]
Still not compatible...

**Comment by DeepDiver1975** [comment]
php 7,3 support is in master - but not production ready. We require a release of sabre/dav 4.0.0 which did not happen up to now .... blame the sabre maintainers .....

**Comment by DeepDiver1975** [comment]
> blame the sabre maintainers .....

which is me - so just drop our complains in here :rofl:

**Comment by patrickjahns** [comment]
@MacroMan 
I don't see Ubuntu 18.04 pushing for 7.3 packages yet ( https://packages.ubuntu.com/search?keywords=php&searchon=names&suite=bionic&section=all ). Where do you base your information on?

@scrobbleme 
Would be great to have you onboard and push this topic forward :-) - I believe sabre maintainers need some help with testing. And we would need also some help with testing :-)

**Comment by MacroMan** [comment]
@patrickjahns I got my info from my server when apt upgraded PHP to 7.3

**Comment by patrickjahns** [comment]
@MacroMan 
I don't see any official php7.3 packages in 18.04 LTS ( note I am only using stable/security repositories )

**Comment by MacroMan** [comment]
My bad. I'm using the popular ondrej PPA: https://launchpad.net/~ondrej/+archive/ubuntu/php

**Comment by voinageo** [comment]
Fedora 30 was released last week. PHP 7.3 is the default and featured as one of the upgrades brought by Fedora 30. 
Latest OwnCloud no longer works after upgrade to Fedora 30.

**Comment by patrickjahns** [comment]
@voinageo 
For supported distributions, please refer to our documentation https://doc.owncloud.com/server/admin_manual/installation/system_requirements.html

**Comment by voinageo** [comment]
Sadly a downgrade of Fedora 30 is not an option. The fast workaround was to apply by hand commit https://github.com/owncloud/core/commit/aaf8c033ccddaf4a37d47f9b41ef86a1cc8bbc32 
It is just a hard check in console.php and index.php. For the stuff I use OwnCloud it seems OK, no issues using PHP 7.3

**Comment by mapkyca** [comment]
For the record, I just removed the upper version check in index.php. YMMV, and there's probably going to be something that fails, but seems to work fine for sync

**Comment by DeepDiver1975** [comment]
> YMMV, and there's probably going to be something that fails, but seems to work fine for sync

Good luck in killing your data. Seriously - we have such version checks there for a reason

**Comment by svde** [comment]
It would have been nice to include the version dependency in the OwnCloud rpm, which would prevent a Fedora system allowing the upgrade to an OS version with an incompatible php version.

It actually gets worse. a FC30 owncloud yum repo was created (see: https://download.owncloud.org/download/repositories/stable/owncloud/index.html) while the packages in that repo don't work with FC30.

**Comment by DeepDiver1975** [comment]
@crrodriguez can you comment on these package requirements? Doable? THX

**Comment by robin13** [comment]
+1 on this.  Just did `apt upgrade` on Debian 10 and got stuck with the default 7.3 PHP install which is not compatible with Owncloud 10.2.0.5 which was installed.  It would be great if the .deb/.rpm packages would also have the dependency so that they cannot upgrade to a broken state.

**Comment by LinuxUser3** [comment]
+1 on this. I've installed OwnCloud and WordPress on same machine. And WordPress is alerting me to upgrade to PHP 7.3, but OwnCloud is blocking...

**Comment by fabrice-regnier** [comment]
@DeepDiver1975 please, tell us what could be done to help you to release OC with php7.3 or sabre or whatever.
regards,
f.

**Comment by DeepDiver1975** [comment]
owncloud 10.3 will support php 7.3

**Comment by fabrice-regnier** [comment]
you @DeepDiver1975 rocks! thank you ;)

**Comment by DeepDiver1975** [comment]
> you @DeepDiver1975 rocks! thank you ;)

THX ... but it was a team effort ... I'll forward the greetings ;-)

**Comment by svde** [comment]
I'm so happy that you're cheering.

But... for the moment the "official" OwnCloud Fedora 30 repository remains BROKEN and UNTESTED. The RPM package still doesn't contain dependency information. People that upgrade to FC30 now still end up breaking OwnCloud.

Anyway, I've moved on (no longer using Owncloud).

**Comment by nomeata** [comment]
Darn, should have seen this before upgrading my server to Debian buster :-(
