### ISSUE TITLE
Wiki is outdated

### ISSUE THREAD

**Issue by csware** [owncloud/core#34463]
This is not a real owncloud bug, but a documentation issue.

The GitHub Wiki is kinda outdated:
* https://github.com/owncloud/core/wiki (10.1 missing, Maintainers link is dead)
* https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule (10.1 missing, version schema)

Not so important as the version numer is noted, but still outdated:
* https://github.com/owncloud/core/wiki/Apps-in-the-release
* https://github.com/owncloud/core/wiki/Project-ideas

If you don't update it, please add a note or better a link where to find the current information now.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/6314 (Shipped DBAL is outdated), https://github.com/owncloud/core/issues/24756 (3rd party guzzle is outdated), https://github.com/owncloud/core/issues/8367 (Debian Repository Key outdated), https://github.com/owncloud/core/issues/31859 (Wiki-page Apps needs some updates...), and https://github.com/owncloud/core/issues/27545 (FYI: Wiki Page about Apps was deleted).

**Comment by DeepDiver1975** [comment]
shall we disable wiki? all relevant information should be in the docs from my understanding ...

@PVince81

**Comment by PVince81** [comment]
I'll fix the 10.x related stuff and the schedule page.

For the remaining items, we need to examine what we still need then migrate to the docs as ticket/PR.

**Comment by PVince81** [comment]
https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule now updated.

there is info about OC 8 and old release cycle which we'll need to update as well or remove @pmaier1

**Comment by pmaier1** [comment]
> https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule now updated.

Thx for taking care, I forgot. 

> there is info about OC 8 and old release cycle which we'll need to update as well or remove @pmaier1

I don't really have the time to do it which is why I added the disclaimer headline some time ago :) Just delete outdated content?

**Comment by PVince81** [comment]
@pmaier1 I've now removed everything below the Semver paragraph. It felt like everything is outdated now, considering OC 10 as LTS.

Once we consider the next iteration we should update again to explain how the EOL is being determined.

**Comment by PVince81** [comment]
schedule page updated. the rest has lower priority, moving to backlog for later cleanup
