### ISSUE TITLE
Can't setup with non-writable htaccess

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#34471]
As far as I remember, some setups are configured fully read-only, or some admins don't want to let the web server write anything in the PHP tree, so they disable it.

We should allow non-writable htaccess.

This PR https://github.com/owncloud/core/pull/32230 makes it throw an exception.

We should soften it and output a warning on the console when it happens.

@individual-it

**Comment by PVince81** [comment]
reading https://doc.owncloud.org/server/10.0/admin_manual/configuration/server/index_php_less_urls.html?highlight=htaccess#prerequisites seems to imply that having htaccess non-writable is also ok. you only need to make it writable if you want this extra thing.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/32230 (throw exception when .htaccess file is not writable), https://github.com/owncloud/core/pull/34461 ([stable10] throw exception when .htaccess file is not writable), https://github.com/owncloud/core/issues/18260 (Cannot setup stable8), https://github.com/owncloud/core/issues/23207 (.htaccess RewriteRule brakes non-standard alias), and https://github.com/owncloud/core/issues/25755 (home storage not writable).

**Comment by individual-it** [comment]
exception should not be thrown on installation or update but only on `occ maintenance:update:htaccess`
whoever does that clearly wants to update the htaccess file and if that fails an exception should be thrown

**Comment by individual-it** [comment]
PR here https://github.com/owncloud/core/pull/34478
