### ISSUE TITLE
skeleton dir is wrongly guessed when running tests on remote systems

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34483]
`run.sh` does guess the place of the skeleton folder by searching for it on the system that runs the tests, that information might not be correct on the SUT if that is a truly remote system

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/28602 (Skeleton dir for integration and UI tests), and https://github.com/owncloud/core/pull/29768 (use skeleton dir from env. for UI tests).
