### ISSUE TITLE
Phoenix integration ....

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#34484]
## Background
We want phoenix to replace the old web frontend in oc10.
This results into a bunch of topics/requirements:
1. when opening the root owncloud installation the phoenix ui shall popup
2. any link to frontend elements which are generated in the backend need to point to phoenix oages
3. any elements which are not yet implemented in phoenix shall be integrated to work on the old frontend

## How to get there
1. We need a htaccess rule to redirect / to apps/phoenix/index.html
For non apache installations this requires documentation
2. backends url generator needs a config option to point urls to phoenix
This needs a concept which works for any links we are generating as of today and in the future.
Nobody is interested in maintaining a list of links with different patterns.
TODO: needs thinking
3. Phoenix can already define menu entries which point to pure urls and these are opened in a new browser tab
We can add menu entries for personal and admin settings which are simply pointing to the old settings pages

**Comment by DeepDiver1975** [comment]
@PVince81 as discussed

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/25498 (Integration of Lepton), https://github.com/owncloud/core/issues/11579 (OnlyOffice integration), https://github.com/owncloud/core/issues/8066 (Spotify integration possible?), https://github.com/owncloud/core/issues/33952 (Owncloud and Keycloak OpenID integration), and https://github.com/owncloud/core/pull/30635 (Integration step definitions for when given).

**Comment by DeepDiver1975** [comment]
afaik all implemented already ->close
