### ISSUE TITLE
Bump copyright year to 2019

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#34509]
PR #34480 has a single bump

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/14181 (Bump password_compat), https://github.com/owncloud/core/issues/21426 (Begin of year prayers), https://github.com/owncloud/core/pull/31685 (Bump small stuff), https://github.com/owncloud/core/issues/18763 (Bump some libraries such as Doctrine), and https://github.com/owncloud/core/pull/32236 (Composer bumps as at 20180806).

**Comment by phil-davis** [comment]
This does not need to be open. Someone who cares can bump the copyright year any time - for example at the start of 2022?
