### ISSUE TITLE
run federation acceptance tests against more different server versions

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34500]
Currently we run stable10-QA tarball as federated server that only tests that the current PR works correctly with the code base of yesterday. To make sure that the current PR also works correctly with released versions of federation sharing we should:
1. run the federation server from the current PR
1. run the federation server from all currently supported and released tarballs (currently 10.0.10 & 10.1.0)

@PVince81 @davitol @phil-davis comments? priority?

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/pull/33506 (Adding more federation acceptance tests), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), and https://github.com/owncloud/core/issues/32053 (Federation acceptance tests should really have different servers).

**Comment by phil-davis** [comment]
Thanks GitMate! If I help with this then I will explode the test matrix so we new the whole Earth for computing test results. But the Earth is currently computing the answer to "the meaning of life, the universe and everything" ;)

**Comment by phil-davis** [comment]
I added this to the sprint. It would be great to know that federated sharing works between the latest code and older serves. That will add confidence that as people upgrade individual servers in their "federated cloud"  that their federated shares will keep working OK.

**Comment by individual-it** [comment]
fixed by #36047
