### ISSUE TITLE
Schedule ext storage tests

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#34522]
We have external storage related tests already in core, but these do not run any more on every PR.

We should schedule running those in Drone every day or so.

See https://github.com/owncloud/core/pull/34284#issuecomment-463658492 for details.

@phil-davis @individual-it FYI

From my understanding this requires Drone to be updated to 1.0 first

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/11263 ([ext storage] Consider moving to Flysystem), and https://github.com/owncloud/core/issues/16681 (Webdav ext storage lighttpd issue).

**Comment by phil-davis** [comment]
See issue #34735 
We are making them work and CI, and they will easily run on every PR.
