### ISSUE TITLE
 integrity  check after upgrade to 10.1.0

### ISSUE THREAD

**Issue by marcorighi** [owncloud/core#34536]
I have the same problem in two servers.

**Server A**
Distributor ID: Debian
Description:    Debian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch
Linux fileserver 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64 GNU/Linux
owncloud-files/unknown,now 10.1.0-1+1.2 all [installed]

**Server B**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
Linux ipazia 3.10.106-151 #1 SMP PREEMPT Wed Jan 3 02:56:52 UTC 2018 armv7l armv7l armv7l GNU/Linux
owncloud-files/unknown,now 10.1.0-1+1.1 all [installed]

### steps to reproduce the error
The error occurs after upgrade from previous release (10.0.1 - I have not details) to  version 10.1.0-1+1.2

### Expected behaviour
no errors

### Actual behaviour
Error appears in admin consolle: "Some files have not passed the integrity check. Further information on how to resolve this issue can be found in our documentation. (List of invalid files… / Rescan…)"

**Server A**
Command 716 of 17 #sudo -u www-data php occ integrity:check-core
  - market:
    - EXTRA_FILE:
      - README.md:
        - expected: 
        - current: b53ebb407cb90a5cf9e28463013f38e6aec3d39b4281187366e02b5fd014be144216a088fc50851635acc50cb71c92ad2407b21e8a4f3433b0f73a32ea066c97

**Server B**
Command 1768 of 52 #sudo -u www-data php occ integrity:check-core                    
- market:
    - EXTRA_FILE:
      - README.md:
        - expected: 
        - current: b53ebb407cb90a5cf9e28463013f38e6aec3d39b4281187366e02b5fd014be144216a088fc50851635acc50cb71c92ad2407b21e8a4f3433b0f73a32ea066c97

### Server configuration
**Operating system**:
Linux
**Web server:**
Server A: apache2/stable,now 2.4.25-3+deb9u6 amd64 [installed,automatic]
Server B: apache2/xenial-updates,now 2.4.18-2ubuntu3.9 armhf [installed]
**Database:**
Server A: postgresql/stable,now 9.6+181+deb9u2 all [installed]
Server B: mysql-server/xenial-updates,xenial-security,now 5.7.25-0ubuntu0.16.04.2 all [installed]
**PHP version:**
Server A: php/stable,now 1:7.0+49 all [installed]
Server B: php/xenial-updates,now 1:7.0+35ubuntu6.1 all [installed]
**ownCloud version:** (see ownCloud admin page)
Server A: owncloud-files/unknown,now 10.1.0-1+1.1 all [installed]
Server B: owncloud-files/unknown,now 10.1.0-1+1.2 all [installed]
**Updated from an older ownCloud or fresh install:**
Server A: as described, update from version 10.0.1 to 10.1.0
Server B: as described, update from version 10.0.1 to 10.1.0
**Where did you install ownCloud from:**
Server A: deb http://download.owncloud.org/download/repositories/production/Debian_9.0/ /
Server B: deb http://download.owncloud.org/download/repositories/production/Ubuntu_16.04/ /
**Signing status (ownCloud 9.0 and above):**
Server A: error as previously described 
Server B: error as previously described 
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
Server A:
Command 724 of 25 #sudo -u www-data php occ config:list system
{
    "system": {
        "updatechecker": false,
        "instanceid": "oc0g9j9vkih7",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "servera"
        ],
        "datadirectory": "\/media\/data\/sites\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/servera\/owncloud",
        "dbtype": "pgsql",
        "version": "10.1.0.4",
        "dbname": "ocdb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "theme": "",
        "loglevel": 2,
        "mail_smtpsecure": "ssl"
    }
}

Server B:
Command 1784 of 68 #sudo -u www-data php occ config:list system
{
    "system": {
        "updatechecker": false,
        "instanceid": "oce6ey3dt06m",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "serverb:443"
        ],
        "datadirectory": "\/media\/db_www_data\/sites\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/serverb:15443\/owncloud",
        "dbtype": "mysql",
        "version": "10.1.0.4",
        "dbname": "oc",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpsecure": "ssl"
    }
}

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/18032 (massive/strange db updates after upgrade to 8.1.0), https://github.com/owncloud/core/issues/10234 (CSS Problem after Upgrading to  ownCloud 7.0.1 (stable) ), https://github.com/owncloud/core/issues/27768 (Missing user_ldap after Upgrade to 10), https://github.com/owncloud/core/issues/18162 (Encryption problem after upgrade from 8.0.x to 8.1), and https://github.com/owncloud/core/issues/23853 (Contacts and calendar apps disabled after upgrade to 9.0.1).

**Comment by PVince81** [comment]
so this is a distro package update ?

I didn't see any integrity check issues with the openSUSE 10.1 package.

maybe the Debian and Ubuntu ones have an extra file ? @crrodriguez

**Comment by joltcan** [comment]
Same issue here for Debian (9.8) and owncloud-files 10.1.0-1+1.2
