### ISSUE TITLE
Error found in log when reciever of fed share deletes the file with encryption enabled

### ISSUE THREAD

**Issue by sharidas** [owncloud/core#34530]
### Steps to reproduce
1. Have 2 instance of oC. Say oC1 and oC2 ( initiator of fed share )
2. oC1 is encrypted. It does not matter if it is masterkey encrypted or user-keys. Pick any one among the two. oC2 is not encrypted.
2. oC2 tries to share a folder ( which has a file inside it. i.e, `simple-folder/data.zip` ) say test to oC1 user using fed share.
3. The reciever of the oC1 say `user1` accepts the share.
4. Now `user1` of oC1 when tries to delete `data.zip`. 
5. Check the log

### Expected behaviour
The logs should not throw error when the file is deleted from oC1 user to its trashbin storage.

### Actual behaviour
Error logged
```
{"reqId":"sYQwyRxMsCCpreehDEFr","level":3,"time":"2019-02-18T07:52:58+00:00","remoteAddr":"::1","user":"user1","app":"PHP","method":"DELETE","url":"\/testing3\/remote.php\/dav\/files\/user1\/simple-folder\/data.zip","message":"call_user_func_array() expects parameter 1 to be a valid callback, class 'OCA\\Files_Sharing\\External\\Storage' does not have a method 'copyKeys' at \/home\/sujith\/test\/owncloud3\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php#502"}
```

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** MySQL

**PHP version:**

**ownCloud version:** (see ownCloud admin page) stabl10 branch

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/1369 (Share file with enable file encryption), https://github.com/owncloud/core/issues/26902 (error), https://github.com/owncloud/core/issues/28840 (-Error-), https://github.com/owncloud/core/issues/28265 (Hi,), and https://github.com/owncloud/core/issues/29158 (Dear Support, ).
