### ISSUE TITLE
[API Acceptance Tests] Test exceptional case in all ocs routes

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#34566]
# Background
When migrating from legacy OCS Api implementations to OCSController we are breaking behavior in exceptional cases. Instead of proper OCS response with proper xml/json body a pure JSON response is returned. PR to fix this will follow.

# Actions
Add api acceptance tests for ALL ocs routes (needed because of the migration path to make sure we hit everything properly).
Test following exceptional scenarios:
- wrong user credentials
- no admin access to admin only routes
- _TO BE ANALYSED_ accessing routes of a disabled app

All scenarios need to be executed as CORS requests and non CORS requests (analyse CORS requests with wrong origin header as well)

# Test Targets
- master
- stable10

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/32040 (fix API acceptance tests), and https://github.com/owncloud/core/issues/31403 (Expand API acceptance tests).

**Comment by individual-it** [comment]
List of endpoints (including endpoints added by bundled apps) and checks what response is checked

| Path                                                               | GET | POST   |  PUT | DELETE |
|-----------------------------------------------------------| ----- | ---------- | ------ | ----------- |
| /apps/files_external/api/v1/mounts                    | json </br> xml  | NA | NA | NA |
| /apps/files_sharing/api/v1/remote_shares          | json </br> xml :robot: :-1: (only OCS code)  | NA | NA | NA |
| /apps/files_sharing/api/v1/remote_shares/pending      |  json </br> xml :robot:  | NA | NA | NA |
| /apps/files_sharing/api/v1/remote_shares/pending/{id} | NA | json </br> xml | NA | json </br> xml |
| /apps/files_sharing/api/v1/remote_shares/{id}         | json </br> xml  | NA | NA | json </br> xml |
| /apps/files_sharing/api/v1/shares                     | json </br> xml :robot: :-1: (few tests & indirect tests) | json </br> xml :robot: | NA | NA |
| /apps/files_sharing/api/v1/shares/pending/{id}        | NA | json </br> xml  | NA | json </br> xml |
| /apps/files_sharing/api/v1/shares/{id}                | json </br> xml :robot:  | NA | json </br> xml :robot:  | json </br> xml :robot: :-1: (only OCS code) |
| /cloud/apps                                           | json </br> xml  | NA | NA | NA |
| /cloud/apps/{appid}                                   | json </br> xml  | json </br> xml  | NA | json </br> xml |
| /cloud/groups                                         | json </br> xml :robot: | json </br> xml :robot: :-1: (only OCS code) | NA | NA |
| /cloud/groups/{groupid}                               | json </br> xml  | NA  | NA | json </br> xml |
| /cloud/groups/{groupid}/subadmins                     | json </br> xml  | NA | NA | NA |
| /cloud/users                                          | json </br> xml  | json </br> xml  | NA | NA |
| /cloud/users/{userid}                                 | json </br> xml  | NA  | json </br> xml | json </br> xml |
| /cloud/users/{userid}/disable                         | NA  | NA | json </br> xml | NA |
| /cloud/users/{userid}/enable                          | NA  | NA | json </br> xml | NA |
| /cloud/users/{userid}/groups                          | json </br> xml  | json </br> xml  | NA | json </br> xml |
| /cloud/users/{userid}/subadmins                       | json </br> xml  | json </br> xml  | NA | json </br> xml |
| /config                                               | json </br> xml  | NA | NA | NA |
| /person/check                                        | NA  | json </br> xml | NA | NA |
| /privatedata/deleteattribute/{app}/{key}              | NA  | json </br> xml | NA | NA |
| /privatedata/getattribute                             | json </br> xml  | NA | NA | NA |
| /privatedata/getattribute/{app}                       | json </br> xml  | NA | NA | NA |
| /privatedata/getattribute/{app}/{key}                 | json </br> xml  | NA | NA | NA |
| /privatedata/setattribute/{app}/{key}                 | NA  | json </br> xml | NA | NA |

**Comment by individual-it** [comment]
I've started to looks through what is tested (list above is not finished yet)
so far:
- there are no tests that use the json response
- some tests check only the ocs code of the response (e.g. tests in auth suite)

**Comment by patrickjahns** [comment]
It would be great to have a API specification first and issue contract based testing in order to ensure the contracts ( and the error cases ) are done properly :-)

**Comment by individual-it** [comment]
the second table shows the progress of testing ocs endpoints for correct / incorrect authentications

**Comment by individual-it** [comment]
CORS tests https://github.com/owncloud/core/pull/34665

**Comment by individual-it** [comment]
a couple of more CORS tests https://github.com/owncloud/core/pull/34697

**Comment by individual-it** [comment]
I think we have covered most of the important cases, closing this issue. Feel free to reopen if more cases need to be covered

**Comment by DeepDiver1975** [comment]
> It would be great to have a API specification first and issue contract based testing in order to ensure the contracts ( and the error cases ) are done properly :-)

did you say specification? https://www.freedesktop.org/wiki/Specifications/open-collaboration-services/
