### ISSUE TITLE
Creating a new user sends a link without domain name if you access owncloud without domain name

### ISSUE THREAD

**Issue by frajico** [owncloud/core#34576]
### Steps to reproduce

1. Install and configure an owncloud 10.0.10 instante with mysql and publish it on internet as https://owncloudservername.exampledomain.com
2. Access owncloud server with http://owncloudservername from internal network
3. Create a new user. Owncloud send a link to set password withouth the domain name like

https://owncloudservername/index.php/settings/users/setpasswords/form/........

Instead of:

https://owncloudservername.exampledomain.com/index.php/settings/users/setpasswords/form/........

4. If you access the owncloud server with FQDN, and create a new user

https://owncloudservername.exampledomain.com

The sent link is OK

### Expected behaviour

Regardless the way you access the owncloud server, the set password link sent on emails should incluide domain name

https://owncloudservername.exampledomain.com/index.php/settings/users/setpasswords/form/........

### Actual behaviour

Create a new user. Owncloud send a link to set password withouth the domain name like

https://owncloudservername/index.php/settings/users/setpasswords/form/........

Users from internet can not access owncloud server to set password cause there is not domain name included on the link.

### Server configuration

**Operating system**:

Linux Ubuntu 16.04

**Web server:**

Apache/2.4.18 (Ubuntu)

**Database:**

mysql  Ver 15.1 Distrib 10.0.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**

PHP 7.0.33-0ubuntu0.16.04.1 (cli) ( NTS )

**ownCloud version:** (see ownCloud admin page)

10.0.10

**Updated from an older ownCloud or fresh install:**

Updated from 9.1

**Where did you install ownCloud from:**

tar file

**Signing status (ownCloud 9.0 and above):**

No errors have been found.

**The content of config/config.php:**

[config_report_20190221.zip](https://github.com/owncloud/core/files/2889411/config_report_20190221.zip)

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/11891 (OwnCloud: New User issues), https://github.com/owncloud/core/issues/222 (Creating new users not possible), https://github.com/owncloud/core/pull/32770 (Check that user cannot create public link without entering password w…), https://github.com/owncloud/core/issues/475 (Could not create unique ownCloud name for), and https://github.com/owncloud/core/issues/18070 (Unable to create new user).

**Comment by PVince81** [comment]
please fix "overwrite.cli.url" in config.php to match the domain name you want to use for creating links.

see https://doc.owncloud.org/server/10.0/admin_manual/installation/changing_the_web_route.html

this is not a bug in ownCloud
