### ISSUE TITLE
db:generate-change-script is unreliable

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#34571]
This command causes confusion as it does not check for the migration steps.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/29795 (db:generate-change-script does not consider ISchemaMigrations), https://github.com/owncloud/core/issues/9526 (Enhance question in DB migration script), https://github.com/owncloud/core/issues/5259 (DB sanity check script), https://github.com/owncloud/core/issues/7378 ([6.0.1] console.php db:generate-change-script error), and https://github.com/owncloud/core/issues/27585 (mimetype:update-db changes a folder to "audio/*").
