### ISSUE TITLE
New user - Internal server error - Disk full

### ISSUE THREAD

**Issue by cognixmarc** [owncloud/core#34591]
Hello,

We recently encountered the following error:

```
Internal Server Error
The server encountered an internal error and was unable to complete your request. 
Please contact the server administrator if this error appears multiple times, please include the technical details below in your report. 
More details can be found in the server log. 
```

The error apparead on login page after the creation of a new user, when the disk is nearly full. OwnCloud was unable to create the files directories of the user.

How can we avoid this problem in the future?

Thanks for your help.

Regards, 

### Server configuration
*Operating system*: Debian 8.11
*Web server:* nginx/1.14.2
*Database:* mysql 5.5.62
*PHP version:* PHP 7.0.33
*ownCloud version:* (see ownCloud admin page)  10.0.10
*Updated from an older ownCloud or fresh install:* fresh install
*Where did you install ownCloud from:* 
Directly from a tar.gz on https://owncloud.org/
*Signing status (ownCloud 9.0 and above):
# occ encryption:status
  - enabled: false
  - defaultModule:

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/26089 (Internal Server Error), https://github.com/owncloud/core/issues/9324 ("Internal Server Error"), https://github.com/owncloud/core/issues/24525 (Internal server error), https://github.com/owncloud/core/issues/28840 (-Error-), and https://github.com/owncloud/core/issues/26902 (error).

**Comment by patrickjahns** [comment]
@cognixmarc 
This is not a bug with ownCloud itself - as you've mentioned your storage was full.

For any help on administrating ownCloud or questions you have, please check https://central.owncloud.org/

**Comment by cognixmarc** [comment]
@patrickjahns thanks, ownCloud shouldn't check that there is enough space on the disk before authorizing the creation of a user that he can't do entirely ?
