### ISSUE TITLE
cron task smbclient 100% CPU usage and hanging

### ISSUE THREAD

**Issue by nfck** [owncloud/core#34597]
<! Please excuse any mistakes, this is my first bug report.>

### Steps to reproduce
1. In External storage, connect to a Samba share that includes the owncloud folder in its folder structure 
Example:
/Share
/Share/Data
/Share/WebRoot where /Share/WebRoot is Symlinked-from-/var/www
/Share/WebRoot/owncloud

2. Run the cron.php job or wait for job to start on schedule

### Expected behaviour
The cron.php job should do it's maintenance work and exit.

### Actual behaviour
A process will start, running smbclient at approx. 100% single core CPU usage. 
The process will not stop with SIGTERM. 
The process will stop if you stop the Samba Service. 

### Server configuration
**Operating system**:
Ubuntu Linux 16.04.4
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
PHP 7.0.33-0ubuntu0.16.04.1
**ownCloud version:** (see ownCloud admin page)
10.1.0.4
**Updated from an older ownCloud or fresh install:**
update from previous
**Where did you install ownCloud from:**
repository
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No errors have been found.

**The content of config/config.php:**

https://gist.github.com/nfck/77f2f163107800af9154f1efdcff48d1
```

**List of activated apps:**

Enabled:
  - audioplayer: 2.6.0
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - market: 0.3.0
  - notifications: 0.4.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external


**Are you using external storage, if yes which one:** local/smb/sftp/...
smb
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Logs
#### Web server error log
Not relevant.

#### ownCloud log (data/owncloud.log)
```
Typical log entry, repeating:
{"reqId":"J6A5vKBMJyRrybVh9SEC","level":3,"time":"2019-02-21T21:29:53+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Error while running background job (class: OCA\\Files\\BackgroundJob\\ScanFiles, arguments: ): {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE `oc_jobs` SET `execution_duration` = ? WHERE `id` = ?' with params [41331, \\\"1\\\"]:\\n\\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away\",\"Code\":0,\"Trace\":\"#0 \\\/HadesPool\\\/WebRoot\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/HadesPool\\\/WebRoot\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1015): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE `oc_jobs...', Array)\\n#2 \\\/HadesPool\\\/WebRoot\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(207): Doctrine\\\\DBAL\\\\Connection->executeUpdate('UPDATE `oc_jobs...', Array, Array)\\n#3 \\\/HadesPool\\\/WebRoot\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `oc_jobs...', Array, Array)\\n#4 \\\/HadesPool\\\/WebRoot\\\/www\\\/owncloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/HadesPool\\\/WebRoot\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/JobList.php(325): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/HadesPool\\\/WebRoot\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(66): OC\\\\BackgroundJob\\\\JobList->setExecutionTime(Object(OCA\\\\Files\\\\BackgroundJob\\\\ScanFiles), 41331)\\n#7 \\\/HadesPool\\\/WebRoot\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#8 \\\/HadesPool\\\/WebRoot\\\/www\\\/owncloud\\\/cron.php(120): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#9 {main}\",\"File\":\"\\\/HadesPool\\\/WebRoot\\\/www\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":115}"}
```

#### Browser log
not relevant

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/6559 (soffice.bin uses 100% CPU), https://github.com/owncloud/core/issues/6940 (Sync loop, 100% CPU-usage), https://github.com/owncloud/core/issues/10379 (ownCloud 7.0.1 - LDAP configuration causing 100% CPU usage), https://github.com/owncloud/core/issues/8814 (ownCloud OS X Client: 100% CPU usage), and https://github.com/owncloud/core/issues/4831 (User first logon causes 100% CPU Usage on IIS).

**Comment by nfck** [comment]
Possible. However, if the SMB storage does not include the Owncloud folder, the issue does not appear. Also, the issue is not sync related but rather maintenance (cron) task related.

**Comment by PVince81** [comment]
you should not include OC in an external storage as this will likely cause some kind of infinite loop in scanning, which might explain why smbclient is running forever.

the external storage (SMB) should only contain external files to be used inside of OC. don't do inception!

closing as external storage is not meant to be used that way
