### ISSUE TITLE
Update is not possible

### ISSUE THREAD

**Issue by achmet9948** [owncloud/core#34601]
Hello everybody, 
when I try to update my owncloud from 10.0.10-1+1.1 to 10.1.0-1+1.2 I get following error: 

```
root@mail:/var/www/owncloud# apt upgrade -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  owncloud-files
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/16.8 MB of archives.
After this operation, 26.1 MB disk space will be freed.
apt-listchanges: Reading changelogs...
(Reading database ... 57400 files and directories currently installed.)
Preparing to unpack .../owncloud-files_10.1.0-1+1.2_all.deb ...
Unpacking owncloud-files (10.1.0-1+1.2) over (10.0.10-1+1.1) ...
dpkg: error processing archive /var/cache/apt/archives/owncloud-files_10.1.0-1+1.2_all.deb (--unpack):
 unable to open '/var/www/owncloud/apps/files_external/3rdparty/google-api-php-client/src/Google/Service/Partners.php.dpkg-new': Operation not permitted
Errors were encountered while processing:
 /var/cache/apt/archives/owncloud-files_10.1.0-1+1.2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I set the maintenance mode on and stopped my webserver.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/21366 (Update), https://github.com/owncloud/core/issues/20661 (Update), https://github.com/owncloud/core/issues/32092 (Repository not updated), https://github.com/owncloud/core/issues/34428 (Repository not updated), and https://github.com/owncloud/core/issues/32786 (Repository not updated).

**Comment by PVince81** [comment]
somehow looks like your package manager isn't able to unpack the deb package due to permission issues, despite you being root. do you have any mount points there mounted read-only ?

in any case this doesn't look like an ownCloud bug, please refer to https://owncloud.org/help/ to get support.

cc @crrodriguez
