### ISSUE TITLE
Please add this new useful feature

### ISSUE THREAD

**Issue by louanbastos** [owncloud/core#34606]
Having the ability to add external files via remote upload url.

Example: I have other website, the file is big and will take long time to upload, i want to take the file from my other website or other website which not my own (example.com/file.zip - 2GB) and put on my owncloud server.

This feature is so useful and will help a lot of people. Thanks <3

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/pull/30981 (Add confirm password after new password), https://github.com/owncloud/core/issues/6250 (New feature request), https://github.com/owncloud/core/issues/9591 ([contacts] Please add anniversary field), https://github.com/owncloud/core/pull/33053 (Add tests for addUser feature), and https://github.com/owncloud/core/issues/18988 (feature: add global quota for whole installation).

**Comment by PVince81** [comment]
this feature used to exist and was removed for security reasons, see https://github.com/owncloud/core/issues/13326
