### ISSUE TITLE
Prevent resuming upgrade

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#34628]
Often times after `occ upgrade` failed, administrators try to run them again.

However the system could be in an unpredictable and non-resumable state and we always urge admins to restore from the backup before trying again.

Resuming an upgrade could cause the system to go into an unknown state.

I suggest we put a check in place that whenever an update has already started, it sets a flag in the database that prevents resuming. When the flag is set, any run of "occ upgrade" asks the admin to restore from backup.

One exception is about errors related to incompatible apps. These should be resumable after disabling or manually fixing these apps.

Thoughts ? @DeepDiver1975 @cdamken @pako81 @micbar @hodyroff @pmaier1 

The other alternative would be investing time into making updates resumable, which need more research to be able to guarantee atomicity / reversibility of migrations (which we currently don't have)

**Comment by PVince81** [comment]
Optionally we could add a message at the beginning "please make sure you have backups of the code, data folder and database before proceeding" with a confirmation y/n (overridable with `-y`)

**Comment by micbar** [comment]
> Optionally we could add a message at the beginning of `occ upgrade` that shows "please make sure you have backups of the code, data folder and database before proceeding" with a confirmation y/n (overridable with `-y`).
This would be a great improvement IMHO!

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/17528 (Prevent closing upgrade page while upgrade in progress), https://github.com/owncloud/core/issues/18192 (Prevent downgrades), https://github.com/owncloud/core/issues/10550 (Shares lost after upgrade), https://github.com/owncloud/core/issues/31476 (WebUpdater: Show a warning of apps that could prevent an upgrade), and https://github.com/owncloud/core/issues/10202 (Maleware Detect after Upgrade).
