### ISSUE TITLE
Update to 10.1.0 not offered from 10.0.10.4

### ISSUE THREAD

**Issue by fr00x** [owncloud/core#34625]
### Steps to reproduce
1. Go to the settings page
2. See if there is a new update
3. 10.1.0 is not offered

### Expected behaviour
10.1.0 is offered

### Actual behaviour
My 10.0.10.4 instance is listed as current.

### Server configuration
**Operating system**: CloudLinux

**Web server:** LightSpeed

**Database:** MySql

**PHP version:** 7.2

**ownCloud version:** (see ownCloud admin page) 10.0.10.4

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/27769 (Updating to 10.0.0 from 9.1.4 - update coudn't finish and now owncloud is crashed - please help), https://github.com/owncloud/core/issues/27760 (owncloud upgrade from 9.1.4 to 10.0.0 fails), https://github.com/owncloud/core/issues/34565 (After upgrade to 10.1.0.4 unable to log in; oc_bfp_failed_logins table missing), https://github.com/owncloud/core/issues/28015 (Failed upgrade from Owncloud 10.0.0.1 to Owncloud 10.0.1), and https://github.com/owncloud/core/issues/18322 (Update failure from 8.0.4.2 to 8.1.1).

**Comment by ho4ho** [comment]
> Note that releases don’t show up in the updater app right away. We usually stagger releases to watch the impact and hold off in case very serious problems pop up. In practice, most bugfix releases are available within a week, major releases within a week for the production channel and a week after the first bugfix release (for example, 9.0.1) for the Production channel.

https://owncloud.org/release-channels/

**Comment by VicDeo** [comment]
Unfortunately web update to 10.1 needs manual creation of `/ocm-provider/index.php` https://github.com/owncloud/updater/issues/495
That's why we haven't published it yet.

**Comment by fr00x** [comment]
Thanks @ho4ho for the info. @VicDeo that would imply that lots of admins would need to re-install from .tar.gz such as myself.

**Comment by pjb304** [comment]
Hi,

Have there been any progress on this now that 10.1.1 has been released?  Thanks.

**Comment by VicDeo** [comment]
we are going to offer 10.1.1/10.2 via beta channel soon

**Comment by fr00x** [comment]
Why not in the production channel at this time? Is 10.1.1/10.2 not a stable production relase?

**Comment by VicDeo** [comment]
@fr00x  
>Is 10.1.1/10.2 not a stable production release?

it is. Stable for updating with packages or manually.

**Comment by fr00x** [comment]
Cool, thank you. Looking forward to having the built-in updater working again :)

**Comment by VicDeo** [comment]
Update: Right now 10.2.0 is available on the beta channel only, we are preparing 10.2.1 bugfix release.

**Comment by VicDeo** [comment]
10.2.1 has been unlocked everywhere. Beware that you'll need PHP 7.0-7.2
