### ISSUE TITLE
OCM failing to create a file in a share

### ISSUE THREAD

**Issue by diocas** [owncloud/core#34635]
Hi @VicDeo,
When I share from OC to CBox, I am able to list and open files. I can even create directories, as the write permissions are all set. But it fails when I try to create a file whit "no permissions" error.
The exact same behaviour happens if I mount the webdav endpoint in MacOS.
Diogo

**Comment by hodyroff** [comment]
@VicDeo do we allow "no permissions" at all? What does the spec say?

**Comment by phil-davis** [comment]
I made PR https://github.com/owncloud/core/pull/36400
That demonstrates that a request to the sharing API asking for zero permissions fails with a `400` "bad request" status, and the share does not happen. (Somehow I don't think we already had a scenario to demonstrate that behaviour, so it will be useful to have)

But IMO the comment about `"no permissions" error` is that the create (upload) request fails with "no permission" - not that the share has zero permissions.
