### ISSUE TITLE
apps/files_sharing/api/v1/remote_shares/{id} returns empty content for not accepted shares

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34636]
### Steps to reproduce
1. from server1 share a folder to server2
2. on server2 do **not** accept the share
3. on server2 find the share-id `curl -u admin:admin http://localhost/owncloud-core/ocs/v1.php/apps/files_sharing/api/v1/remote_shares/pending`
4. try to get information about that share `curl -u admin:admin http://localhost/owncloud-core/ocs/v1.php/apps/files_sharing/api/v1/remote_shares/22 -v`

### Expected behaviour
Error saying that the share is not accepted
OR
information of the share shown

### Actual behaviour
HTTP code 200 but empty content

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache2
**Database:**
SQLite
**PHP version:**
7.2
**ownCloud version:** (see ownCloud admin page)
11.0.0
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git

**Comment by individual-it** [comment]
possible related to #34566

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/issues/34626 (accesing /ocs/v1.php/apps/files_sharing/api/v1/shares with invalid credentials gives an empty reply), https://github.com/owncloud/core/issues/18530 (apps/files_sharing/api/externalShares 404 (Not Found)), https://github.com/owncloud/core/issues/15508 (Empty content notice does not show for shared links), https://github.com/owncloud/core/issues/4435 (Accept incoming shares), and https://github.com/owncloud/core/pull/31423 ([Stable10] api test api sharing v1).

**Comment by DeepDiver1975** [comment]
@individual-it can you glue all these tests into some api acceptance tests? THX

**Comment by individual-it** [comment]
@DeepDiver1975 just doing it, trying to fill the gaps in https://github.com/owncloud/core/issues/34566#issuecomment-467425598 
first part was https://github.com/owncloud/core/pull/34627 , more will follow

**Comment by individual-it** [comment]
log output 
```
{"reqId":"jEUc6cUnaiVutribdDtn","level":3,"time":"2019-03-05T04:33:09+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"GET","url":"\/owncloud-core\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/remote_shares\/52","message":"Call to a member function getMimetype() on boolean at \/home\/artur\/www\/owncloud-core\/apps\/files_sharing\/lib\/API\/Remote.php#110"}
```

**Comment by individual-it** [comment]
with PHP 5.6 and stable10 that issue results in a `HTTP/1.0 500 Internal Server Error`

**Comment by VicDeo** [comment]
still reproducible:
```
{"reqId":"jeeKxCEMNmITSnccyKE4","level":3,"time":"2020-04-06T10:12:08+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/remote_shares\/32","message":"Error: Call to a member function getMimetype() on boolean at \/apps\/files_sharing\/lib\/Controller\/RemoteOcsController.php#213"}
```

we shouldn't try to read FileInfo for pending shares.
