### ISSUE TITLE
OCM http(s):// as part as the owner

### ISSUE THREAD

**Issue by diocas** [owncloud/core#34633]
@VicDeo should we accept this? Again, from the examples of the OCM API, I was expecting things differently. Should we clarify the API?
Diogo

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/27283 (file owner), https://github.com/owncloud/core/issues/12054 (Owncloud http requests), https://github.com/owncloud/core/issues/14819 (Support HTTP proxy), https://github.com/owncloud/core/issues/3500 (HTTP header requesttoken), and https://github.com/owncloud/core/pull/34321 (Send OCM requests as JSON).

**Comment by VicDeo** [comment]
@diocas The proto part should not affect the functionality. 
I don't think this issue to be critical if it works without the proto in the same manner as with it.
