### ISSUE TITLE
OCM share not appearing

### ISSUE THREAD

**Issue by diocas** [owncloud/core#34634]
@VicDeo As I told you, the last time I tried to share something from CBox to OC, the share was added but nothing appeared in the interface. Can you give me your email so that you can debug it? I will send the json I POST with a valid webdav endpoint + secret.
Diogo

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/11433 ([Sharing] Not possible to share after having shared a folder), https://github.com/owncloud/core/issues/3360 (Shared folder disappear ), https://github.com/owncloud/core/issues/22739 (Sharing permission issue), https://github.com/owncloud/core/issues/1167 (Can't share images for real), and https://github.com/owncloud/core/issues/13569 (Not all remote shares removed).

**Comment by moscicki** [comment]
@PVince81: some help please?

**Comment by PVince81** [comment]
assuming OC version 10.0.10 and CBox is equivalent to 9.1.x ?

**Comment by VicDeo** [comment]
if "a valid webdav endpoint" assumes an absolute WebDav URL it won't work without patching apps/files_sharing/lib/External/Storage.php like this
https://github.com/owncloud/core/pull/34260/files#diff-dc34ca6e9b0f6e43d61d664c004c0968

**Comment by diocas** [comment]
I just said that I have a webdav endpoint and a JSON message, equivalent to a real POST that CERNBox would have posted... So, you simulate my POST and try to see why is not showing.
I did no other consideration about what a "valid webdav endpoint" is.

**Comment by VicDeo** [comment]
Probably related to the `accepted` db field in the `oc_share_external` table
a recipient is notified about incoming share and should explicitly accept it in UI
then `accepted` is set to 1 and the share becomes visible
in case the recipient refuses to accept the share unsharing happens.

**Comment by hodyroff** [comment]
@diocas can you answer to the assumption by @VicDeo ?
