### ISSUE TITLE
Page files doesn't work

### ISSUE THREAD

**Issue by mzeminian** [owncloud/core#34646]
### Expected behaviour
I have to see files

### Actual behaviour
I didn't see files when I log in my cloud

### Server configuration
**Operating system**: Linux

**PHP version:**

**ownCloud version:** 10.1.0

**<?php
$CONFIG = array (
  'instanceid' => 'ocjr0qe7s59w',
  'passwordsalt' => 'L07WXuMh8gBoPBrOFdYh94xH9C6Q7I',
  'secret' => 'JzL+/49PUGQqlCa2HYcGiXu/Wg8MpDRrW3pklD4z6b3N9Qnc',
  'trusted_domains' => 
  array (
    0 => 'www.dmztechnology.it',
  ),
  'datadirectory' => '/web/htdocs/www.dmztechnology.it/home/cloud/data',
  'overwrite.cli.url' => 'https://www.dmztechnology.it/cloud',
  'dbtype' => 'mysql',
  'version' => '10.1.0.4',
  'dbname' => 'Sql1298923_5',
  'dbhost' => '89.46.111.81',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '*****',
  'dbpassword' => '****',
  'logtimezone' => 'UTC',
  'installed' => true,
);
**

### Client configuration
**Browser:** Google Chrome

**Operating system:** MacOS

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/23182 (File Search not working), https://github.com/owncloud/core/issues/7746 (Search for files doesn't work), https://github.com/owncloud/core/issues/3751 (Already Exists it does not work when we try to upload a file whose name already exists), https://github.com/owncloud/core/issues/3728 (Cancel it does not work when we try to upload a file whose name already exists), and https://github.com/owncloud/core/issues/3758 (Drag & Drop folder does not work).

**Comment by ho4ho** [comment]
Better support for https://central.owncloud.org/ ?
