### ISSUE TITLE
cron and console are not reading config

### ISSUE THREAD

**Issue by tflori** [owncloud/core#34648]
### Steps to reproduce
1. setup a docker container running owncloud:10.0
2. change the config file to use a table prefix
3. execute cron.php inside the container with user www-data

### Expected behaviour
it should read the appconfig from the prefixed table

### Actual behaviour
it throws an error that it can't read from the database:
```
An exception occurred while executing 'SELECT * FROM `appconfig`':\\n\\nSQLSTATE[42S02]: Base table or view not found: 1146 Table 'owncloud.appconfig' doesn't exist
```

### Server configuration
**Operating system**:
```
uname -a; lsb_release -a
Linux w00tserver 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
```
**Web server:**
the one that is installed in your docker image
**Database:**
mariadb:10
**PHP version:**
the one that is installed in your docker image
**ownCloud version:** (see ownCloud admin page)
latest owncloud:10.0 image (10.0.10.4)
**Updated from an older ownCloud or fresh install:**
more or less a fresh install since the upgrade process didn't go well
**Where did you install ownCloud from:**
official docker repo (`image: owncloud/server:10.0`)
**Signing status (ownCloud 9.0 and above):**

no errors detected

**The content of config/config.php:**

suggested command does not work - here is the config (sensitive data removed):
```php
<?php
$CONFIG = array (
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/owncloud/custom',
      'url' => '/custom',
      'writable' => true,
    ),
  ),
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/mnt/data/files',
  'dbtype' => 'mysql',
  'dbhost' => 'mariadb:3306',
  'dbname' => 'owncloud',
  'dbuser' => 'owncloud',
  'dbtableprefix' => 'oc_',
  'log_type' => 'owncloud',
  'supportedDatabases' => 
  array (
    0 => 'sqlite',
    1 => 'mysql',
    2 => 'pgsql',
  ),
  'upgrade.disable-web' => true,
  'default_language' => 'en',
  'overwrite.cli.url' => 'http://owncloud.../',
  'htaccess.RewriteBase' => '/',
  'logfile' => '/mnt/data/files/owncloud.log',
  'loglevel' => 2,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mysql.utf8mb4' => 'true',
  'filelocking.enabled' => true,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'redis',
    'port' => '6379',
  ),
  'version' => '10.0.10.4',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => 'oc8hw7272c09',
);
```

...to many irrelevant questions and no time sorry. i'm a php dev so maybe just tell me where it tries to read the config but doesn't. the thing is it either tries to access the database before reading the config or it is not reading the config at all or the queries for appconfig don't use the prefix.

 btw. the config in `/mnt/data/config/config.php` and `/var/www/owncloud/config/config.php` are the same but only one of them is at the mount point (`/mnt/data`) and in my opinion `/var/www/owncloud/config/config.php` should then be just a symlink but it isn't.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @mmattel.

Possibly related issues are https://github.com/owncloud/core/issues/4148 (Config file reading), https://github.com/owncloud/core/issues/14455 (Support for read-only config dir), https://github.com/owncloud/core/issues/8422 (Cron is not working), https://github.com/owncloud/core/issues/2124 ([carddav] - Contacts are read only), and https://github.com/owncloud/core/issues/2116 (Cron Service Fails).

**Comment by VicDeo** [comment]
I guess the reason is one of those
```
'memcache.local' => '\\OC\\Memcache\\APCu',
 'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'redis',
    'port' => '6379',
  ),
```

Did you try to flush cache?

**Comment by tflori** [comment]
I tried now using the environment variable and that worked. the config is overwritten and there are at least two errors in the `config/overwrite.config.php`:

1. https://github.com/owncloud-docker/base#available-environment-variables describes the default for `OWNCLOUD_DB_PREFIX` is `oc_` but it isnt. The default config also has `oc_` but the overwrite config does not use a default if the env is not available: `'dbtableprefix' => getenv('OWNCLOUD_DB_PREFIX'),`
2.  https://github.com/owncloud-docker/base#available-environment-variables describes 5 `OWNCLOUD_VOLUME_*` variables but in overwrite there is only one that does not have a default:  `'datadirectory' => getenv('OWNCLOUD_VOLUME_FILES'),`

Because `getenv()` returns false if the variable does not exist the value is just false and that does not work. Also this document does not state out that you need to define this environment variable: https://doc.owncloud.com/server/10.4/admin_manual/installation/docker/

I suggest you update the documentation and implement default values in the `overwrite.config.php`

**Comment by tflori** [comment]
btw. the cronjob is still not working in 10.0:

```console
www-data@2405f06f2aa9: ~/owncloud # /usr/bin/cronjob
/etc/entrypoint.d/98-overwrite.sh: line 12: /etc/environment: Permission denied
```

it tries to write an environment file as user www-data:
```console
www-data@2405f06f2aa9: ~/owncloud # cat /etc/cron.d/owncloud 
*/1  *  *  *  * www-data /usr/bin/cronjob
```

Is there a good reason to pass the environment variables over a system configuration file?
