### ISSUE TITLE
Cannot send email via SMTP

### ISSUE THREAD

**Issue by aario** [owncloud/core#34658]
Hi,
I cannot setup SMTP.
The error is:
```
A problem occurred while sending the email. Please revise your settings. (Error: Connection could not be established with host mail [ #0])
```
Now I now that because the standard form you set for all bug reports is not filled here, you might ignore this bug report. I estimated it takes around 2 hours to answer all the questions and read through that 2000 lines General Configuration Report to make sure no sensitive data is in it.

So here is what happens:
I installed owncloud using docker container:
https://hub.docker.com/_/owncloud?tab=description
I can go to container terminal and type:
telnet mail-server 465
I see connection can be established. So whatever happens might be a bug from the source code or PHP libraries. The problem is I cannot see any stacktrace in any log file. Nothing. Just the error message above.

Here is my advice:
When developing a code which is showing an error message, Please also use log file. There's no harm in writing something, just something in some log file. I see no single log file is affected when this error happens. So I have to grep through all the source code in hope to figure where the error is coming from!

Also bug report form is huge! I mean seriously huge! I find it easier to setup my development environment and start developing owncloud myself and fix the bug than to fill that form.

Thanks by the way.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @PVince81.

Possibly related issues are https://github.com/owncloud/core/issues/18226 (Server does not send email notifications via smtp when set to AJAX), https://github.com/owncloud/core/issues/27554 (Cannot send test email), https://github.com/owncloud/core/issues/13826 (Can not sent Calendar events by email), https://github.com/owncloud/core/issues/10717 (SMTP config not deleted when another email method is selected), and https://github.com/owncloud/core/issues/16790 (Feedback of failure after sending test email is poor).

**Comment by ho4ho** [comment]
Tryed:

https://doc.owncloud.org/server/admin_manual/configuration/server/logging_configuration.html

https://doc.owncloud.org/server/admin_manual/configuration/server/email_configuration.html#troubleshooting

**Comment by aario** [comment]
> Tryed:
> 
> https://doc.owncloud.org/server/admin_manual/configuration/server/logging_configuration.html
> 
> https://doc.owncloud.org/server/admin_manual/configuration/server/email_configuration.html#troubleshooting

Thanks for reply. Did it.
Added:
```
'loglevel' => 0,
```
And:
```
'mail_smtpdebug' => true,
```
Into config/config.php.
Nothing change. No new line in log file data/owncloud.log. No new message in the settings page.

**Comment by aario** [comment]
More insight:
Added this:
```
                $transport->setStreamOptions(['ssl'=>['allow_self_signed'=>true, 'verify_peer_name'=>false,]]); 
```
In:
```
lib/private/Mail/Mailer.php:215
```
Makes the send mail work. So the problem is:
**How can I make OwnCloud work with a postfix with self signed certificate?**

**Comment by ho4ho** [comment]
Problem by PHP not arriving owncloud logs?

Look PHP 5.6 not liking self-signed certificates: https://github.com/modxcms/revolution/issues/12763, https://github.com/passbolt/passbolt_docker/issues/116, https://forum.photo.gallery/viewtopic.php?t=9317

**Comment by PVince81** [comment]
PHP 5.6 support will be removed in the next OC release which is 10.2.0.

its deprecation was already announced ealier: https://doc.owncloud.com/server/administration_manual/release_notes.html#php-5-6-deprecation

**Comment by ho4ho** [comment]
@PVince81 Not think that @aario running PHP 5.6 or it 5.6 related.

**Comment by aario** [comment]
Claiming that the user has a out dated system and then simply closing the issue is not the solution. This doesn't fix a possible bug and let it remain. So more users will face the same issue. Ask for PHP version and I tell you. And don't ask millions of possible questions in the issue subscription form, just in case. Because people are just like yourself and don't have much time.
My PHP is 7.2. Now what?

**Comment by aario** [comment]
For the time being, as a work around, I will stop using owncloud and will try other solutions like nextcloud.
