### ISSUE TITLE
ocs config endpoint does not return CORS headers

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34664]
### Steps to reproduce
1. set `http://owncloud.org` CORS domain
2. `curl -u admin:admin http://localhost/owncloud-core/ocs/v1.php/config -H "Origin: http://owncloud.org" -v`

### Expected behaviour
CORS headers returned

### Actual behaviour
no CORS headers but 
```
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/9143 (Nginx Config Does Not Work), https://github.com/owncloud/core/issues/14482 (Nginx config does not work), https://github.com/owncloud/core/issues/34631 (OCM Returned endpoint relative), https://github.com/owncloud/core/issues/30253 (old preview endpoint returns a 500 Error), and https://github.com/owncloud/core/issues/27384 (config/ subdirectory does not need to be writeable).

**Comment by DeepDiver1975** [comment]
@individual-it can you please test with this PR https://github.com/owncloud/core/pull/34622 - THX a lot!

**Comment by individual-it** [comment]
@DeepDiver1975 same issue in that branch
