### ISSUE TITLE
"element not interactable" exception in webUI tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#34689]
e.g. https://drone.owncloud.com/owncloud/core/15759/787

```
        Exception: element not interactable
          (Session info: chrome=72.0.3626.119)
          (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-142-generic x86_64) in /drone/src/vendor-bin/behat/vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:144
```

It seems to be intermittent but happening when testing the user management page of the UI.

Most of the time each test scenario passes on a 2nd run. Sometimes the 2nd try fails and so we notice a I fail result.

Needs investigation.

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/22492 (test), https://github.com/owncloud/core/issues/31579 (test), https://github.com/owncloud/core/issues/22485 (test), https://github.com/owncloud/core/issues/24121 (Clean/Fix exceptions when running integration tests), and https://github.com/owncloud/core/issues/32842 (webUI test comments).

**Comment by phil-davis** [comment]
@PVince81 I added this to the next sprint, because it is happening quite a lot.

**Comment by phil-davis** [comment]
- [x] Phase 1: waiting for settings menu to animate open on user management page
https://github.com/owncloud/user_management/pull/158
https://github.com/owncloud/core/pull/34720
- [ ] monitor drone runs to see what else is failing
- [ ] write some smarter Jquery to loop and wait until the settings menu has finished animating (maybe?)

**Comment by individual-it** [comment]
looks like its working stable now.
to get rid of the `sleep(1)` we could check the style of the box.
when its hidden it is: `display: none`
![image](https://user-images.githubusercontent.com/2425577/54516347-bb664d80-4986-11e9-81b9-e40f3f909eba.png)

During the transition is has a lot of other settings:
![image](https://user-images.githubusercontent.com/2425577/54516321-a38ec980-4986-11e9-94fc-674a612c1355.png)

and when finished it only has `display: block;`
![image](https://user-images.githubusercontent.com/2425577/54516285-8b1eaf00-4986-11e9-844a-ae084eb1889d.png)

is it worth the effort?

**Comment by phil-davis** [comment]
Having detailed knowledge of the "workflow" of styles, DOM elements,... baked into test code will make the tests more brittle when people adjust the styles of stuff. So maybe that will be just as annoying as having `sleep(1)`?

**Comment by individual-it** [comment]
one could argue that its knowledge of how jQuery does the animation. But I agree, in this case a `sleep(1)` might be alright.
deleting the ToDo in the code with reference to this issue and closing the issue?

**Comment by phil-davis** [comment]
https://github.com/owncloud/user_management/pull/170 removes the "ToDo"
