### ISSUE TITLE
user has to disable and enable share autoaccept setting to override disabled admin setting

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34708]
### Steps to reproduce
1. create a new user
1. as admin disable "Automatically accept new incoming local user shares" 
1. check the user-based setting for auto-accepting shares

### Expected behaviour
setting should be disabled (the user never touched them)

### Actual behaviour
setting is enabled
but shares are not auto-accepted
to really enable them user has to disable and re-enable the setting

**Comment by phil-davis** [comment]
There was some discussion that the user could/should see 3 setting options:
- automatically accept
- do not automatically accept
- use system/admin setting (and display what that setting currently is?)

Then new users would always first see "use system/admin setting". Then they can choose and "override" selection for themselves. And if they like in future they can go back to taking the "system/admin setting"

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks possibly related issues are https://github.com/owncloud/core/issues/17863 (Admin-Page: Sharing-settings are available when sharing app is disabled), https://github.com/owncloud/core/issues/4636 (Let Admin temporarily disable user logins), https://github.com/owncloud/core/pull/32043 (Add methods to disable or enable sharing settings), https://github.com/owncloud/core/issues/7904 (LDAP user and group backend: Quota Default overrides admin settings), and https://github.com/owncloud/core/issues/11510 (Unable to share files as a non admin user).

**Comment by karakayasemi** [comment]
We can fix the issue by adding admin's choice as default in this line :https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/Panels/Personal/PersonalPanel.php#L53

>There was some discussion that the user could/should see 3 setting options:
>- automatically accept
>- do not automatically accept
>- use system/admin setting (and display what that setting currently is?)

I was not aware of the discussion. Last option makes sense to me also. At least showing current admin preference to a user. If we decide in this way. I would like to take care of.
