### ISSUE TITLE
split apiAuth behat suite

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34704]
on user_ldap apiAuth sometimes takes more than 2h
we need to split that suite into smaller chunks

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @phil-davis.

Possibly related issues are https://github.com/owncloud/core/pull/32369 (Split api acceptance suites), https://github.com/owncloud/core/issues/34264 (split slow acceptance tests suites), https://github.com/owncloud/core/pull/30584 ( Split UI test suites into smaller pieces), https://github.com/owncloud/core/pull/30587 ([stable10] Split UI test suites into smaller pieces), and https://github.com/owncloud/core/pull/32370 ([stable10] split api acceptance suites).

**Comment by individual-it** [comment]
this is not an issue any more because we are using splitting by `numberOfParts` in user_ldap now
