### ISSUE TITLE
user-based autoaccepting is off but shares are auto accepted when shared with group

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#34705]
### Steps to reproduce
1. create user1 and put the user into group1
1. as user1 disable "Automatically accept new incoming local user shares"
1. share a folder with group1

### Expected behaviour
user1 should not automatically receive the share

### Actual behaviour
user1 received the share

### Client configuration
**Browser:**

**Operating system:**

#### ownCloud log (data/owncloud.log)
```
{"reqId":"MNZ2NNCqWxgYDbg9wRaL","level":3,"time":"2019-03-07T10:52:20+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"GET","url":"\/owncloud-core\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/sharees?format=json&search=g1&perPage=200&itemType=folder","message":"Invalid argument supplied for foreach() at \/home\/artur\/www\/owncloud-core\/apps\/files_sharing\/lib\/SharingBlacklist.php#96"}
{"reqId":"EXA9df4mDerSVuIDeiod","level":3,"time":"2019-03-07T10:52:27+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"POST","url":"\/owncloud-core\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json","message":"Invalid argument supplied for foreach() at \/home\/artur\/www\/owncloud-core\/apps\/files_sharing\/lib\/SharingBlacklist.php#96"}
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributor most likely able to help you is @ownclouders.

Possibly related issues are https://github.com/owncloud/core/issues/6167 (Sharing with a group), https://github.com/owncloud/core/issues/8565 (Hidden "Share with user or group …"), https://github.com/owncloud/core/issues/19153 (User Can Accept Shares from Other Users), https://github.com/owncloud/core/issues/4435 (Accept incoming shares), and https://github.com/owncloud/core/pull/31613 ([stable10] Accept user share stable10).

**Comment by individual-it** [comment]
the reverse user setting on & admin setting off does not work correctly with groups

**Comment by PVince81** [comment]
making that p2 as we don't want to ship a broken new feature

**Comment by karakayasemi** [comment]
I investigated the issue. As far as I see, there is no explicit share state definition for the per user in group shares. Somehow, we need to add state definition for the per user in the group shares to fix this issue.
I could not find a quick fix with the current architecture.

**Comment by PVince81** [comment]
@karakayasemi there is a share state definition, we call this "sub-shares" and has the share type 2.

please chat with @sharidas who's currently rediscovering the concept
