### ISSUE TITLE
Run files_external tests in Drone

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#34735]
Currently files_external tests are not run on Drone with the exception of the SMB suite and maybe another one.

We should run the tests there to make sure we can catch errors especially during library updates.
For example, when upgrading phpseclib we need to make sure that the SFTP suite still works. (@phil-davis remembers)

Here is a PR that attempts to enable Webdav with OC and lists the failures: https://github.com/owncloud/core/pull/30733

List of storages to cover:
- [x] smb_samba
- [x] webdav_apache
- [x] webdav_owncloud #36857 
- [x] swift
- [x] SFTP #36292 
- [x] Amazon S3 - testing with scality
- Dropbox => currently not possible, see https://github.com/owncloud/files_external_dropbox/pull/17
- GDrive => moved to separate repo on master

**Comment by phil-davis** [comment]
Added this to the current sprint so we review it and finish whatever is possible here.

**Comment by kiranparajuli589** [comment]
@phil-davis is something yet to be done here??

**Comment by phil-davis** [comment]
yes, this was actually about running phpunit tests. core `.drone.star` has this is the `phpunit` section:
```
		'external-other' : {
			'phpVersions': [
				'7.1',
			],
			'databases': [
				'sqlite',
			],
			'externalTypes': [
				'webdav',
				'sftp',
				'scality'
			],
			'coverage': True
		},
```
and there is another section for `externalTypes` of `samba` and `windows`.

In theory there [might|should] be a way to setup a full "federated webDAV ownCloud server" and have it connected as the "backend storage" for the whole front-end ownCloud-under-test, and let the unit tests run with the storage backend like that.

I need to research if that is even a possible way to setup a pair of ownCloud servers.

**Comment by kiranparajuli589** [comment]
> yes, this was actually about running phpunit tests. core `.drone.star` has this is the `phpunit` section:
> 
> ```
> 		'external-other' : {
> 			'phpVersions': [
> 				'7.1',
> 			],
> 			'databases': [
> 				'sqlite',
> 			],
> 			'externalTypes': [
> 				'webdav',
> 				'sftp',
> 				'scality'
> 			],
> 			'coverage': True
> 		},
> ```
> 
> and there is another section for `externalTypes` of `samba` and `windows`.
> 
> In theory there [might|should] be a way to setup a full "federated webDAV ownCloud server" and have it connected as the "backend storage" for the whole front-end ownCloud-under-test, and let the unit tests run with the storage backend like that.
> 
> I need to research if that is even a possible way to setup a pair of ownCloud servers.
> 
> Note to self: see `.drone.star` `webdavService()` `sambaService()` sftpService()` for the storage backends that are already defined.

@phil-davis That's interesting, you can ping me while moving on with this, I've only worked with `acceptance tests`, but I also want to see `phpunit tests` :)
