### ISSUE TITLE
QuotaPlugin fails, user space usage returned as SPACE_NOT_COMPUTED

### ISSUE THREAD

**Issue by kristjanvalur** [owncloud/core#34757]
I've been having issues uploading files beyond a certain size.  Turns out that my root file system is almost full, but the actual data file system is not.  I've done rudimentary debugging of the issue, and here is what I think is happening:

If the physical storage disk is accessed via symlinks through a different filesystem, the QuotaStorage mechanism (QuotaPlugin.php), specifically Files/Storage/Local.php, does not expand the file path symbolic links before calling disk_free_space()

An example of this is having the data folder /var/www/owncloud/data a symbolic link to, e.g. /mnt/largedisk/owncloud_data/

There are good reasons for using symbolic links for the data directory, chief among them not having to change the database when migrating storage, adding extra storate for certain users, etc.

### Steps to reproduce
1.  Setup data directory to /var/www/owncloud/data
2.  Point /var/www/owncloud/data -> /mnt/largedisk/data
3.  Leave little space in the /var filesystem
4.  Upload a file larger than the free space in /var

### Expected behaviour
File is uploaded

### Actual behaviour
We get "not enough free space" error when the upload is done (for the finale MOVE webdav operation.)

### Server configuration
Centos 7

**Web server:**
Apache

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
10.0.10.4
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "ocd9j6yjl7vp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "ec2-34-254-17-73.eu-west-1.compute.amazonaws.com",
            "owncloud.rvx.is",
            "cloud.rvx.is"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/ec2-54-154-212-211.eu-west-1.compute.amazonaws.com",
        "dbtype": "mysql",
        "version": "10.0.10.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "theme": "",
        "loglevel": 0,
        "log_rotate_size": 10000000,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "htaccess.RewriteBase": "\/"
    }
}
```

**List of activated apps:**
```
Enabled:
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.10.0
  - files_primary_s3: 1.0.2
  - files_sharing: 0.11.0
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.1.1
  - impersonate: 0.4.0
  - market: 0.2.5
  - notifications: 0.3.5
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10

#### ownCloud log (data/owncloud.log)
```
{"reqId":"XIj0M2tfai418vBoYI-BXgAAAAQ","level":0,"time":"2019-03-13T12:14:44+00:00","remoteAddr":"178.19.51.186","user":"kristjan","app":"webdav","method":"MOVE","url":"\/remote.php\/dav\/uploads\/kristjan\/web-file-upload-d0129e9c5c63b73c7446684b443bde0e-1552478208587\/.file","message":"Exception: HTTP\/1.1 507 Insufficient Storage: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\InsufficientStorage\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/oc_install\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/QuotaPlugin.php(103): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\QuotaPlugin->checkQuota('\\\/', 6843665999)\\n#1 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\QuotaPlugin->handleBeforeMove('uploads\\\/kristja...', 'files\\\/kristjan\\\/...')\\n#2 \\\/mnt\\\/oc_install\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/mnt\\\/oc_install\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(633): Sabre\\\\Event\\\\EventEmitter->emit('beforeMove', Array)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/mnt\\\/oc_install\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/mnt\\\/oc_install\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#7 \\\/mnt\\\/oc_install\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/mnt\\\/oc_install\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(298): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/mnt\\\/oc_install\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/mnt\\\/oc_install\\\/owncloud\\\/remote.php(165): require_once('\\\/mnt\\\/oc_install...')\\n#11 {main}\",\"File\":\"\\\/mnt\\\/oc_install\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/QuotaPlugin.php\",\"Line\":168}"}
```

**Comment by patrickjahns** [comment]
@kristjanvalur 
One of the reasons for ownCloud not trying to expand symlinks is, that a symlink can not be trusted to be properly set end expandable. With symlinks you are able to create loops which are hard to catch and needlessly makes the scenario more complex.

Example would be:
`/data ----> /mnt/mount/data --- >/data`

Instead of symlinks - the other option would be to consider bind mounts

**Comment by kristjanvalur** [comment]
Well, such a symlink would be broken.  It would not just fail when computing free space, it would fail when trying to do anything with it.  The install would already be hopelessly broken.

In this case, moving the user data folder using a symlink works perfectly.  It is in fact also one of the recommended ways of setting things up: https://doc.owncloud.com/server/admin_manual/maintenance/manually-moving-data-folders.html

Anyway, my diagnosis of the problem might be in error.  It would appear that php's disk_free_space() works correctly, since it presumably using the statvfs syscall:
```
[root@ip-172-31-45-134 ~]# php -r "print(disk_free_space(\"/var/www/owncloud\")); print(\"\n\");"
317308928
[root@ip-172-31-45-134 ~]# php -r "print(disk_free_space(\"/var/www/owncloud/data\")); print(\"\n\");"
544580800512
```

Python does this the same:
```
 python -c 'import os; print os.statvfs("/var/www/owncloud/data")'
posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=262142976, f_bfree=133108929, f_bavail=132954297, f_files=0, f_ffree=0, f_favail=0, f_flag=4096, f_namemax=255)
[root@ip-172-31-45-134 ~]# python -c 'import os; print os.statvfs("/var/www/owncloud/")'
posix.statvfs_result(f_bsize=4096, f_frsize=4096, f_blocks=261120, f_bfree=88236, f_bavail=77468, f_files=0, f_ffree=0, f_favail=0, f_flag=4096, f_namemax=255)
```

When completing an upload, a bunch of 10MB files in the users's "upload/foo/" folder need to be coalesced and put in place.  Is it possible that they are being put in the /tmp file system or somewhere else like that?  The logging of this error is very poor.  I could put in some extra diagnostic code where the QuotaPlugin is failing.

**Comment by ho4ho** [comment]
Look PHP uploading at /tmp https://github.com/owncloud/core/issues/22011

**Comment by kristjanvalur** [comment]
Ok, I added extra message information to the InsufficientStorate exception being raised in QuotaPlugin.php.  
` throw new InsufficientStorage(sprintf("needed:%d free:%d path:'%s'", $length, $freeSpace, $path));`
This is at the end of upload.  We get:
```
{"reqId":"XIolLQCpgyV8i9af@mIW7wAAAAk","level":0,"time":"2019-03-14T09:55:57+00:00","remoteAddr":"178.19.51.186","user":"kristjan","app":"webdav","method":"MOVE","url":"\/remote.php\/dav\/uploads\/kristjan\/web-file-upload-d0129e9c5c63b73c7446684b443bde0e-1552556575328\/.file","message":"Exception: HTTP\/1.1 507 free:6843665999 needed:-1 path:'\/': {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\InsufficientStorage\",\"Message\":\"needed:6843665999 free:-1 path:'\\\/'\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/oc_install\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/QuotaPlugin.php(103): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\QuotaPlugin->checkQuota('\\\/', 6843665999)\\n#1 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\QuotaPlugin->handleBeforeMove('uploads\\\/kristja...', 'files\\\/kristjan\\\/...')\\n#2 \\\/mnt\\\/oc_install\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/mnt\\\/oc_install\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(633): Sabre\\\\Event\\\\EventEmitter->emit('beforeMove', Array)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMove(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/mnt\\\/oc_install\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/mnt\\\/oc_install\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MOVE', Array)\\n#7 \\\/mnt\\\/oc_install\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/mnt\\\/oc_install\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(298): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/mnt\\\/oc_install\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/mnt\\\/oc_install\\\/owncloud\\\/remote.php(165): require_once('\\\/mnt\\\/oc_install...')\\n#11 {main}\",\"File\":\"\\\/mnt\\\/oc_install\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/QuotaPlugin.php\",\"Line\":168}"}
```

Two things:
 - path is '/'. This fits, since it is being uploaded to the root of my space.
 - freeSpace is reported as -1, which is FileInfo::SPACE_NOT_COMPUTED

I´m adding more logging to the code to figure out where it goes wrong.

**Comment by kristjanvalur** [comment]
Ok, I've spent most of today digging through php sources.  Here is what's happening

1. The MOVE command causes the QuotaPlugin to call free_space('') in lib/private/Files/View.php
2. This then calls free_storage() on a Files_Trashbin/Storage object, defined in the class Wrapper from /Files/Storage/Wrapper/Wrapper.in apps/files_trashbin/lib/Quota.php, with argument "files"
3. Wrapper then calls a OC\\Files\\Storage\\Wrapper\\Quota instance's free_storage('files')

Long story short, we end up looking at the user's quota and its free space.
Addint copious amount of log calls, I found that this function here:
```/**
         * @param string $path
         * @param \OC\Files\Storage\Storage $storage
         */
        protected function getSize($path, $storage = null) {
                if ($storage === null) {
                        $cache = $this->getCache();
                } else {
                        $cache = $storage->getCache();
                }
                $data = $cache->get($path);
                        Util::writeLog('core', sprintf('quota.getsize(%s) %s \'%s\' %s', $path, $cache, $data, $data['size']), Util::DEBUG);
                if ($data instanceof ICacheEntry and isset($data['size'])) {
                        return $data['size'];
                } else {
                        return \OCP\Files\FileInfo::SPACE_NOT_COMPUTED;
                }
        }
```
yields the output:
```
"quota.getsize(files)  '' -1"}
```
In other words, it would appear that the cached usage for this user is -1.  This results in a SPACE_NOT_COMPUTED return value which continues all the way up.

Quota.php checkQuota() function can't cope with this value and Raises InsufficientStorage exception.

I was misled earlier when I thought this applied only to large files. This user cannot upload anything at all, not because his quota is exceeded, but because the space used by hasn't been computed for whatever reason, and the Quota plugin can't cope with that.

Is this an error, a bug, a config thing, what?
