### ISSUE TITLE
Incorrect filename unescape in dav endpoints

### ISSUE THREAD

**Issue by dos1** [owncloud/core#34760]
### Steps to reproduce
1. Upload/create a file with name like `Various - 04 - Jacek Krolik i Ryszard Sygitowicz %2F Crosstown Traffic.flac` (note the `%2F` - it's the actual part of the name)
2. Try to modify the file and sync it with the desktop client.

### Expected behaviour
File should get uploaded and updated server-side.

### Actual behaviour
`Server replied "404 Not Found" to "MOVE https://(...)/owncloud/remote.php/dav/uploads/dos/860430607/.file" (File with name Muzyka/FLAC/Hey Jimi - Polskie gitary grają Hendrixa/Various - 04 - Jacek Krolik i Ryszard Sygitowicz / Crosstown Traffic.flac could not be located)`

Note the `%2F` becoming `/` in the error message, even though the `Destination` header is correctly set and escaped by the desktop client:
`Destination: /owncloud/remote.php/dav/files/dos/Muzyka/FLAC/Hey%20Jimi%20-%20Polskie%20gitary%20graj%C4%85%20Hendrixa/Various%20-%2004%20-%20Jacek%20Krolik%20i%20Ryszard%20Sygitowicz%20%252F%20Crosstown%20Traffic.flac`

The issue doesn't happen when uploading the changed file in browser.

### Server configuration
**Operating system**: Debian jessie

**Web server:** Apache 2.4.10

**Database:** MySQL 5.6.30

**PHP version:** 5.6.40

**ownCloud version:** (see ownCloud admin page) 10.1.0.4

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** ownCloud deb packages

**Signing status (ownCloud 9.0 and above):**

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- market
	- EXTRA_FILE
		- README.md

Raw output
==========
Array
(
    [market] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => b53ebb407cb90a5cf9e28463013f38e6aec3d39b4281187366e02b5fd014be144216a088fc50851635acc50cb71c92ad2407b21e8a4f3433b0f73a32ea066c97
                        )

                )

        )

)
```
(this looks like a separate bug actually :D)

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "10.1.0.4",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity: 2.4.2
  - audioplayer: 2.6.0
  - comments: 0.3.0
  - configreport: 0.1.1
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.10.0
  - files_sharing: 0.11.0
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.1.1
  - market: 0.3.0
  - notifications: 0.4.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.4.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by dos1** [comment]
BTW. I have checked now with a new small text file and couldn't reproduce; then replaced it with ~30MB file and could. It seems to affect the MOVE requests, so it likely happens only when the upload is chunked.

**Comment by PVince81** [comment]
@individual-it can add a test case for this ?

**Comment by individual-it** [comment]
should be possible to create a test for that, but didn't we had that kind of problem a while ago an @phil-davis fixed it?

**Comment by individual-it** [comment]
having problems to reproduce it on master
a simple request works fine
`curl -v -X MOVE http://localhost/owncloud-core/remote.php/dav/files/admin/aaaa.txt -u admin:admin -H "Destination: http://localhost/owncloud-core/remote.php/dav/files/admin/Various%20-%2004%20-%20Jacek%20Krolik%20i%20Ryszard%20Sygitowicz%20%252F%20Crosstown%20Traffic.flac"`

also a chunked upload:
`curl  -X MKCOL -u admin:admin http://localhost/owncloud-core/remote.php/dav/uploads/admin/12345`
`curl -X PUT -u admin:admin http://localhost/owncloud-core/remote.php/dav/uploads/admin/12345/0 -d "aaaa"`
`curl -X PUT -u admin:admin http://localhost/owncloud-core/remote.php/dav/uploads/admin/12345/1 -d "bbbb"`
`curl -v -X MOVE http://localhost/owncloud-core/remote.php/dav/uploads/admin/12345/.file -u admin:admin -H "Destination: http://localhost/owncloud-core/remote.php/dav/files/admin/Various%20-%2004%20-%20Jacek%20Krolik%20i%20Ryszard%20Sygitowicz%20%252F%20Crosstown%20Traffic.flac"`

next will try it on the specific oC version

**Comment by dos1** [comment]
You should first create a file with this name and then try to overwrite it without changing its name. AFAIR what you just described already worked fine for me, it was the sync after file modification that was failing.

**Comment by individual-it** [comment]
@dos1 thank you for the hint.
The problem is the extra `If` Header the client sends when overwriting the file. Here the complete request
```
MOVE /owncloud-core/remote.php/dav/uploads/admin/3564657344/.file HTTP/1.1
Destination: /owncloud-core/remote.php/dav/files/admin/aa-%252F-aa.txt
Content-Type: application/octet-stream
If: </owncloud-core/remote.php/dav/files/admin/aa-%2F-aa.txt> (["b48e2c9c9b3fedce55c1ddcb600862a9"])
OC-Async: 1
OC-Checksum: SHA1:79c1b3c982ade8fce97edbed7f413a8277debba7
OC-Total-Length: 64746744
X-OC-Mtime: 1555993201
Authorization: Basic YWRtaW46YWRtaW4=
User-Agent: Mozilla/5.0 (Linux) mirall/2.4.1
Accept: */*
X-Request-ID: e989f47a-0ebd-4296-aa30-70e0f306a03d
Cookie: oc_sessionPassphrase=rrPALlI%2FwYho3xQTV6gmGoQ%2FUUsVCdGjZbOxUz50yBW5mdZkU9%2F3qpw44G%2B%2B3jvyRTpxjcaKJ9ewFJ7DFL03OoHK1tWlbiITXi19UZQuVmWbKdna4pSXHIJj1fSqGBrG; oc4kyqahfanl=f0667i1cv21tusrj54jauskgva
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: en-US,*
Host: localhost
```

see how the destination is correct `aa-%252F-aa.txt` but in the `If` Header the path is `aa-%2F-aa.txt`

I suspect that is a client issue

CC @owncloud/desktop-core-developers @ckamm

**Comment by ckamm** [comment]
@individual-it That does indeed sound likely. Will create a client issue.
