### ISSUE TITLE
InvalidArgumentException not translated in DefaultShareProvider.php

### ISSUE THREAD

**Issue by socket-es** [owncloud/core#34778]
### Steps to reproduce
1. Folder name with more than 64 characters.
2. Public link with the name of Folder name.
3. throw new \InvalidArgumentException('Share name cannot be more than 64 characters'); **Line 1239**
4.- File lib/private/Share20/DefaultShareProvider.php

Is necesary to add to translation system this Exception.

**Comment by patrickjahns** [comment]
@socket-es - would you be able to provide a pull request addressing this issue?
