### ISSUE TITLE
Sharing links with https:// not http://

### ISSUE THREAD

**Issue by crackhd** [owncloud/core#34781]
When i share links, they are `http://`. This is because i often browse ownCloud via address like `http://192.168.0.1`, but i have a public reverse proxy with domain and TLS termination

How to force `https://` and custom domain in shared links?

**Comment by crackhd** [comment]
I have tried: exec into container, find file /var/www/html/config/config.php and there options:

- `'overwritehost' => 'owncloud.domain.tld'`
- `'overwriteprotocol' => 'https'`

This did not work.

**Comment by ho4ho** [comment]
Bug tracker not good for questions. Use https://central.owncloud.org/ ?

**Comment by DeepDiver1975** [comment]
Have a look at the docs. There is a section on proxy setup

**Comment by crackhd** [comment]
Sure i did this.
And reverted.
If i follow set `overwritehost` and `overwriteprotocol`, i cannot access my site at say `http://192.16.0.1:9999`, it is forced to redirect to the real frontend address.
