### ISSUE TITLE
Lost password JS applies to wrong field

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#34797]
### Steps

1. Check out git master
1. Open browser console
1. Open login page
1. Enter user name
1. Start typing password

### Expected
No JS errors.

### Actual
![image](https://user-images.githubusercontent.com/277525/54546831-cfb94300-49a4-11e9-8c6e-9cc3c6aa1135.png)

### Version
git master f0de0d3f572d518326b2b70d4f7cc7de1c216007

Not happening in OC 10.1.0.

Need to check stable10 in case we backported this bug...

@sharidas @phil-davis

**Comment by PVince81** [comment]
also happens on stable10

**Comment by sharidas** [comment]
- [x] Happens in stable10
- [x] Not found in oC 10.1.0

**Comment by sharidas** [comment]
Created PR: 
- [x] master branch https://github.com/owncloud/core/pull/34816
