### ISSUE TITLE
Two factor auth message

### ISSUE THREAD

**Issue by Mipronimo** [owncloud/core#34848]
I have insalled privacyIDEA as a 2FA provider. On the 2FA screen, the message "Please authenticate using the selected factor." appears with the title privacyIDEA.
This is configured in this template file: https://github.com/owncloud/core/blob/master/core/templates/twofactorshowchallenge.php

Is it possible, that a 2FA provider replaces this message with another one?
If yes, please tell me how. If no, can you change it?
It would be enough, if the fieldset would have an id, cause then we could replace the content.

Kind regards
Micha Preußer

**Comment by PVince81** [comment]
you could use theming to replace this template with your own.

else if you like you can provide a PR that adds an id on this field
