### ISSUE TITLE
Inconsistent schema when migrating from 10.0.10 to 10.1.0

### ISSUE THREAD

**Issue by kaklakariada** [owncloud/core#34885]
### Steps to reproduce
1. Install rpm package owncloud-files-10.0.3-1.1.noarch
1. Using `yum update` perform upgrades to
   * owncloud-files-10.0.4-1.1.noarch
   * owncloud-files-10.0.7-1.1.noarch
   * owncloud-files-10.0.8-1.1.noarch
   * owncloud-files-10.0.9-1.1.noarch
   * owncloud-files-10.0.9-1.2.noarch
   * owncloud-files-10.0.10-1.1.noarch
   * owncloud-files-10.1.0-1.1.noarch
1. Edit and save a text file using the text file plugin

### Expected behaviour
Managing files works after upgrading to 10.1.0 (e.g. editing a text file using the Text file plugin)

### Actual behaviour
* Web frontend displays and error message when trying to edit a text file using the text file plugin
* Log contains message
```
DB upsert failed after 5 attempts. UpdateQuery: UPDATE `*PREFIX*filecache` SET `encrypted` = :encrypted, `mimepart` = :mimepart, `mimetype` = :mimetype, `mtime` = :mtime, `size` = :size, `etag` = :etag, `storage_mtime` = :storage_mtime, `permissions` = :permissions, `checksum` = :checksum, `parent` = :parent, `path_hash` = :path_hash, `path` = :path, `name` = :name, `storage` = :storage WHERE (`storage` = '3') AND (`path_hash` = '926aa6228016e4cb2d79db07c2d44714') InsertQuery: INSERT INTO `*PREFIX*filecache` (`encrypted`, `mimepart`, `mimetype`, `mtime`, `size`, `etag`, `storage_mtime`, `permissions`, `checksum`, `parent`, `path_hash`, `path`, `name`, `storage`) VALUES(:encrypted, :mimepart, :mimetype, :mtime, :size, :etag, :storage_mtime, :permissions, :checksum, :parent, :path_hash, :path, :name, :storage)
```

### Server configuration
**Operating system**: Amazon Linux

**Web server:** httpd24-2.4.38-1.86.amzn1.x86_64

**Database:** mysql56-server-5.6.42-1.31.amzn1.x86_64

**PHP version:** php71-7.1.25-1.35.amzn1.x86_64

**ownCloud version:** 10.1.0 (stable) 

**Updated from an older ownCloud or fresh install:** Updated from 10.0.10

**Where did you install ownCloud from:** RPM/Yum repo http://download.owncloud.org/download/repositories/production/CentOS_7

**Signing status (ownCloud 9.0 and above):** ?

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and put the link here.

-> "No errors have been found."
```

**The content of config/config.php:**

Problem already fixed, did not create a report with the invalid schema.
See dump of invalid schema: [Dump_owncloud_before_fix.txt](https://github.com/owncloud/core/files/3000261/Dump_owncloud_before_fix.txt)

**List of activated apps:** Not relevant, only files app affected

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 66

**Operating system:** Windows 10

#### Web server error log
Not relevant

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VCkCOw56zrwfx8nUoJVJ","level":3,"time":"2019-03-10T10:53:28+00:00","remoteAddr":"<ip>","user":"<user>","app":"no app in context","method":"PUT","url":"\/inde
x.php\/apps\/files_texteditor\/ajax\/savefile","message":"Exception: {\"Exception\":\"RuntimeException\",\"Message\":\"DB upsert failed after 5 attempts. UpdateQuery: UPDATE `*
PREFIX*filecache` SET `encrypted` = :encrypted, `mimepart` = :mimepart, `mimetype` = :mimetype, `mtime` = :mtime, `size` = :size, `etag` = :etag, `storage_mtime` = :storage_mti
me, `permissions` = :permissions, `checksum` = :checksum, `parent` = :parent, `path_hash` = :path_hash, `path` = :path, `name` = :name, `storage` = :storage WHERE (`storage` =
'3') AND (`path_hash` = '926aa6228016e4cb2d79db07c2d44714') InsertQuery: INSERT INTO `*PREFIX*filecache` (`encrypted`, `mimepart`, `mimetype`, `mtime`, `size`, `etag`, `storage
_mtime`, `permissions`, `checksum`, `parent`, `path_hash`, `path`, `name`, `storage`) VALUES(:encrypted, :mimepart, :mimetype, :mtime, :size, :etag, :storage_mtime, :permission
s, :checksum, :parent, :path_hash, :path, :name, :storage)\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(260): OC\\\\
DB\\\\Adapter->upsert('*PREFIX*filecac...', Array, Array)\\n#1 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Cache.php(277): OC\\\\DB\\\\Connection-
>upsert('*PREFIX*filecac...', Array, Array)\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Cache.php(230): OC\\\\Files\\\\Cache\\\\Cache->insert
('files_versions\\\/...', Array)\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(281): OC\\\\Files\\\\Cache\\\\Cache->put('files_vers
ions\\\/...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(218): OC\\\\Files\\\\Cache\\\\Scanner->addToCache('files_version
s\\\/...', Array, -1)\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Scanner.php(326): OC\\\\Files\\\\Cache\\\\Scanner->scanFile('files_versions
\\\/...', 3, '205232', Array, false)\\n#6 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Cache\\\/Updater.php(124): OC\\\\Files\\\\Cache\\\\Scanner->scan('fil
es_versions\\\/...', false, 3, false)\\n#7 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(328): OC\\\\Files\\\\Cache\\\\Updater->update('files_versio
ns\\\/...', 1552215208)\\n#8 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(955): OC\\\\Files\\\\View->writeUpdate(Object(OCA\\\\Files_Trashbin\\\\St
orage), 'files_versions\\\/...')\\n#9 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(
Array)\\n#10 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(991): OC\\\\Files\\\\View->emittingCall(Object(Closure), Array, 'file', 'copy')\\n#11 \\\
/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_versions\\\/lib\\\/Storage.php(203): OC\\\\Files\\\\View->copy('files\\\/Documents...', 'files_versions\\\/...')\\n#12 \\\/var\
\\/www\\\/html\\\/owncloud\\\/apps\\\/files_versions\\\/lib\\\/Hooks.php(58): OCA\\\\Files_Versions\\\\Storage::store('Documents\\\/Suime...')\\n#13 \\\/var\\\/www\\\/html\\\/o
wncloud\\\/lib\\\/private\\\/legacy\\\/hook.php(105): OCA\\\\Files_Versions\\\\Hooks::write_hook(Array)\\n#14 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/V
iew.php(1301): OC_Hook::emit('OC_Filesystem', 'write', Array)\\n#15 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1174): OC\\\\Files\\\\View->runHooks(Array, '\\\/Suimei & Chris...')\\n#16 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(715): OC\\\\Files\\\\View->basicOperation('file_put_conten...', '\\\/Suimei & Chris...', Array, 'TODO Hochzeit\\\\n=...')\\n#17 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\Files\\\\View->OC\\\\Files\\\\{closure}(Array)\\n#18 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(717): OC\\\\Files\\\\View->emittingCall(Object(Closure), Array, 'file', 'update')\\n#19 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files_texteditor\\\/controller\\\/filehandlingcontroller.php(154): OC\\\\Files\\\\View->file_put_contents('\\\/Suimei & Chris...', 'TODO Hochzeit\\\\n=...')\\n#20 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(153): OCA\\\\Files_Texteditor\\\\Controller\\\\FileHandlingController->save('\\\/Suimei & Chris...', 'TODO Hochzeit\\\\n=...', 1552215199)\\n#21 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(85): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_Texteditor\\\\Controller\\\\FileHandlingController), 'save')\\n#22 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(100): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_Texteditor\\\\Controller\\\\FileHandlingController), 'save')\\n#23 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('FileHandlingCon...', 'save', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#24 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#25 \\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/base.php(909): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_tex...')\\n#26 \\\/var\\\/www\\\/html\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#27 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Adapter.php\",\"Line\":214}"}
```

#### Browser log
Not relevant

**Comment by kaklakariada** [comment]
Please note that the initial DB migration failed because of inconsistent column types. I fixed this by modifying a column to `bigint(20)` (don't remember which column)

I fixed the file management issues by comparing the schema (see [Dump_owncloud_before_fix.txt](https://github.com/owncloud/core/files/3000261/Dump_owncloud_before_fix.txt)) with a fresh installation and ran the following commands:

* Changes for the `filecache` table:
```sql
alter table owncloud.oc_filecache modify parent bigint(20) NOT NULL DEFAULT '0';
alter table owncloud.oc_filecache modify fileid bigint(20) NOT NULL AUTO_INCREMENT;
```
* Other changes (maybe unrelated to the problem):
```sql
alter table owncloud.oc_calendarsubscriptions modify lastmodified int(10) unsigned NOT NULL;
alter table owncloud.oc_cards add KEY `addressbookid_uri_index` (`addressbookid`,`uri`);
alter table owncloud.oc_federated_reshares modify share_id bigint(20) NOT NULL, modify remote_id bigint(20) NOT NULL;
alter table owncloud.oc_files_trash modify auto_id bigint(20) NOT NULL AUTO_INCREMENT;
alter table owncloud.oc_mounts modify root_id bigint(20) NOT NULL;
alter table owncloud.oc_properties modify id bigint(20) NOT NULL AUTO_INCREMENT, modify fileid bigint(20) unsigned DEFAULT NULL;
alter table owncloud.oc_share modify file_source bigint(20) DEFAULT NULL;
alter table owncloud.oc_share  add KEY `share_with_index` (`share_with`);
alter table owncloud.oc_share_external modify id bigint(20) NOT NULL AUTO_INCREMENT, modify remote_id bigint(20) NOT NULL DEFAULT '-1';
alter table owncloud.oc_systemtag modify assignable smallint(6) NOT NULL DEFAULT '1';
alter table owncloud.oc_vcategory_to_object modify objid bigint(20) unsigned NOT NULL DEFAULT '0';
```

Please adapt the migration scripts to perform these changes, so that other users won't have the same problems.

**Comment by ho4ho** [comment]
Wrong seq by used? Tryied 10.0.3 to 10.1.0 direct?

**Comment by kaklakariada** [comment]
No. As stated in the ticket I upgraded step-by-step. I verified this with `cat /var/log/yum.log* | grep owncloud`.

**Comment by ho4ho** [comment]
Why? Upgrade should done 10.0.3 to 10.1.0 directly.

**Comment by kaklakariada** [comment]
Sorry, now I understand what you mean. This is an older installation and over time I always installed the patch releases listed above. Until 10.1.0 this worked quite well.

**Comment by ho4ho** [comment]
Sorry, thinked you done step by step today.

**Comment by kaklakariada** [comment]
Any update on this?

**Comment by VicDeo** [comment]
@kaklakariada 
this is a known thing - if the prev update attempt was unsuccessful one should revert the DB before 
running `occ upgrade` once again.

>Please note that the initial DB migration failed because of inconsistent column types. I fixed this by modifying a column to bigint(20) (don't remember which column)

Tells me that you hit exactly the same issue and had skipped migrations.
https://github.com/owncloud/core/issues/34598#issuecomment-532702709

as long as 10.1.0 is already published I don't how we can fix it...

**Comment by kaklakariada** [comment]
@VicDeo 
I did not skip migrations, I extracted the list of version upgrades above from the rpm log to make sure I did not skip a version.
You are right, you can't fix this now. From my point of view you can close this issue. I just wanted to help improve the project.

But maybe you could make sure during testing that migrations always lead to a consistent state, e.g.:

1. Do a fresh installation of the latest version, extract schema
2. Install an older version, perform migrations for all versions until latest version and extract schema

Then compare both extracted schema, they should be equal.

**Comment by VicDeo** [comment]
@kaklakariada well, as far as I remember we advise to migrate directly to the last digit release skipping everything inbetween, e.g 10.0.4 to 10.0.10
In addition it is possible to skip directly to the most recent release e.g. 10.0.4 to 10.3.2

I don't consider to to be a `wont fix` issue but the testing is too time consuming


>I did not skip migrations, 

you didn't but your owncloud did ;)
As I wrote above "initial DB migration failed because of inconsistent column types" indicates that it could potentially happen just like was reported in https://github.com/owncloud/core/issues/34598#issuecomment-532702709

**Comment by kaklakariada** [comment]
No progress, I will close this.
