### ISSUE TITLE
Problem loading page reloading in 5 seconds

### ISSUE THREAD

**Issue by TinusS123** [owncloud/core#34935]
### Steps to reproduce
1. Create Folder in webinterface, share this folder. 
2. Create Subfolders.
3.Open the folder link, sort folders on date
4. Error message pops up on top of the screen, saying "Problem loading page, reloading in 5 seconds".

### Expected behaviour
The folders to be sorted based on date, however after the page reloads its hasn't sorted the folders based on date.

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:
Centos 6.10 
**Web server:**
Nginx 1.6.3. 
**Database:**
mysql 5.5.54
**PHP version:**
5.6.40

**ownCloud version:** (see ownCloud admin page)
9.1
**Updated from an older ownCloud or fresh install:**
Updated
**Where did you install ownCloud from:**

### Client configuration
**Browser:**
Firefox/Edge/Chrome
**Operating system:**
Windows 10

**Comment by VicDeo** [comment]
@TinusS123 I'm sorry, 9.1 reached EOL and does not receive fixes for 22 months so far https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

Feel free to reopen if this issue is still reproducible with ownCloud 10.
