### ISSUE TITLE
Collaborative Editing & Federation

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#34950]
# OnlyOffice + Federation

Current state:
- When editing a document shared via federation between two oC instances that connect to the same OnlyOffice instance every user gets their own session => collaborative editing does not work, simultaneous editing overwrites changes from others by the last user closing OnlyOffice
- When editing a document shared via federation between two oC instances that do not connect to the same OnlyOffice instance or use another collaborative editing solution => same issue as above but different case in terms of finding a solution

## Approach 1: All federated instances connect to one OnlyOffice instance

=> Unique shared file identifier

- Issue 1: Only solves the scenario when federated instances are connected to the same OnlyOffice instance
- Issue 2: Does not cover other collaborative editing solutions

## Approach 2: Generalized approach
- Find a solution that works for all collaborative editing solutions (Collabora Online / Office Online)
- Find a solution that works when federated instances use different instances of the same collaborative editing solution
- Find a solution that works when federated instances use different collaborative editing solutions

=> Use co-editing solution of the owner's oC instance?

# Importing Public Links as federated shares from the same instance they originate from
## Approach 1: Convert to user share
- How to handle permissions?
- How to handle links with expiration date/password?
- Will the public link be removed after conversion?
- Do we need to ask the owner for permission before conversion?
- Old ticket about the case https://github.com/owncloud/core/issues/9090

**Comment by pmaier1** [comment]
@DeepDiver1975 
@PVince81 FYI

**Comment by PVince81** [comment]
in general, for most operations in OC we try to always go to the owner's instance or storage instead of driving it remotely. so in the case of collaborative editing, the UI could maybe redirect to the URL of the editor on the owner's instance instead of trying to do remote magic.

**Comment by PVince81** [comment]
also what happens with restrictions, for example user A is generally not allowed to share with user B locally due to "can only share with same group members" or similar. Should the share import fail ?

**Comment by PVince81** [comment]
if using the share manager API it is possible that the restriction check will also be in place
