### ISSUE TITLE
Error when loading image

### ISSUE THREAD

**Issue by medooch** [owncloud/core#34962]
### Context :
```
I duplicate an existing owncloud project on my server that is perfectly executed, I have no problem the source project.

The goal is to clone the source project by applying some changes to make the new image management tool only.

The new project works perfectly on my local environment (Mac os x, apache2, php5.6), but when I deployed, I encountered this problem when loading images.
```

### Steps to reproduce
1. Upload an image
2. Try to preview the image

### Expected behaviour
Picture will be loaded

### Actual behaviour
<div class="notification" style="display: block;"><strong>Error!</strong> Could not generate a preview of this file.<br>Please go to the next slide while we remove this image from the slideshow</div>

### Server configuration
**Operating system**: Ubuntu 16.04 LTS (GNU/Linux 4.4.0-98-generic x86_64)

**Web server:** Apache2

**Database:** Mysql

**PHP version:** 5.6

**ownCloud version:** 9.0.2

```
Integrity checker has been disabled. Integrity cannot be verified.
```

**The content of config/config.php:**

```
$CONFIG = array(
    'instanceid' => '#',
    'passwordsalt' => '#',
    'secret' => '#',
    'trusted_domains' =>
        array(
            0 => 'myproject',
        ),
    'datadirectory' => '/project/data',
    'overwrite.cli.url' => 'http://myproject/',
    'dbtype' => 'mysql',
    'version' => '9.0.2.2',
    'dbname' => '#',
    'dbhost' => '#',
    'dbtableprefix' => 'oc_',
    'dbuser' => '#',
    'dbpassword' => '#',
    'logtimezone' => 'UTC',
    'installed' => true,
    'theme' => 'myTheme',
    'default_language' => 'fr',
    'knowledgebaseenabled' => false,
    'allow_user_to_change_display_name' => false,
    'loglevel' => 3,
    'apps_paths' =>
        array(
            0 =>
                array(
                    'path' => '/project/apps',
                    'url' => '/apps',
                    'writable' => true,
                ),
            1 =>
                array(
                    'path' => '/project/mobelite',
                    'url' => '/mobelite',
                    'writable' => true,
                ),
        ),
    'mail_smtpmode' => 'smtp',
    'mail_smtphost' => '#',
    'mail_from_address' => #',
    'mail_domain' => '#,
    'mail_smtpport' => '#',
    'mail_smtpauth' => 1,
    'mail_smtpname' => '#',
    'mail_smtppassword' => '#',
    'mail_smtpauthtype' => '#',
    'environnement' => 'preprod',
);
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - intranet_auth: 1.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - announcementcenter
  - bookmarks
  - encryption
  - external
  - galleryplus
  - user_external
  - user_ldap
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:**no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome Version 73.0.3683.86

**Operating system:** Mac os x 10.14.3

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
{"reqId":"99OnA69JrvW5TyFtM\/k+","remoteAddr":"","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/vhosts\/preprod.banque.cdp.fr\/config\/config.php:1) at \/var\/www\/vhosts\/preprod.banque.cdp.fr\/lib\/private\/response.php#254","level":3,"time":"2019-04-04T09:53:43+00:00","method":"--","url":"--","user":"--"}
{"reqId":"99OnA69JrvW5TyFtM\/k+","remoteAddr":"","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/vhosts\/preprod.banque.cdp.fr\/config\/config.php:1) at \/var\/www\/vhosts\/preprod.banque.cdp.fr\/lib\/private\/response.php#259","level":3,"time":"2019-04-04T09:53:43+00:00","method":"--","url":"--","user":"--"}
{"reqId":"99OnA69JrvW5TyFtM\/k+","remoteAddr":"","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/vhosts\/preprod.banque.cdp.fr\/config\/config.php:1) at \/var\/www\/vhosts\/preprod.banque.cdp.fr\/lib\/private\/response.php#260","level":3,"time":"2019-04-04T09:53:43+00:00","method":"--","url":"--","user":"--"}
{"reqId":"99OnA69JrvW5TyFtM\/k+","remoteAddr":"","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/vhosts\/preprod.banque.cdp.fr\/config\/config.php:1) at \/var\/www\/vhosts\/preprod.banque.cdp.fr\/lib\/private\/response.php#261","level":3,"time":"2019-04-04T09:53:43+00:00","method":"--","url":"--","user":"--"}
{"reqId":"99OnA69JrvW5TyFtM\/k+","remoteAddr":"","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/vhosts\/preprod.banque.cdp.fr\/config\/config.php:1) at \/var\/www\/vhosts\/preprod.banque.cdp.fr\/lib\/private\/response.php#262","level":3,"time":"2019-04-04T09:53:43+00:00","method":"--","url":"--","user":"--"}
{"reqId":"99OnA69JrvW5TyFtM\/k+","remoteAddr":"","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/vhosts\/preprod.banque.cdp.fr\/config\/config.php:1) at \/var\/www\/vhosts\/preprod.banque.cdp.fr\/lib\/private\/response.php#263","level":3,"time":"2019-04-04T09:53:43+00:00","method":"--","url":"--","user":"--"}
{"reqId":"99OnA69JrvW5TyFtM\/k+","remoteAddr":"","app":"PHP","message":"Cannot modify header information - headers already sent by (output started at \/var\/www\/vhosts\/preprod.banque.cdp.fr\/config\/config.php:1) at \/var\/www\/vhosts\/preprod.banque.cdp.fr\/lib\/private\/response.php#264","level":3,"time":"2019-04-04T09:53:43+00:00","method":"--","url":"--","user":"--"}

#### Browser log
```

a) The javascript console log
Failed to load resource: the server responded with a status of 404 (Not Found)
OpenSans-Semibold.woff:1 Failed to load resource: the server responded with a status of 404 (Not Found)
loading-dark.gif:1 Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by patrickjahns** [comment]
Please try to reproduce this issue on a recent ownCloud version (> 10 ) - as any version lower than 10 is end-of-life
