### ISSUE TITLE
Jquery-migrate-1.2.1.min.js has vulnerable Jscript error (high) in VAPT scan

### ISSUE THREAD

**Issue by AppHelpdesk** [owncloud/core#34963]
Hi Team,

During VAPT scan, I encountered High issue with jquery-migrate-1.2.1.min.js 
Below is the detail for the scan:

Vulnerable Javascript library
Classification
Base Score: 6.4
- Access Vector: Network
- Access Complexity: Low
- Authentication: None
- Confidentiality Impact: Partial
- Integrity Impact: Partial
- Availability Impact: None
CVSS
CWE CWE-16

Can someone please look into this and provide a solution urgently. I have seen lot of similar posts where it is written that this is medium issue but i am getting it as high issue in VAPT scan and i am stuck as it can't be released to client without fixing this issue. I even tried its latest versions but its the same issue.

**Comment by ho4ho** [comment]
False positive?

view-source:https://demo.owncloud.org/core/vendor/jquery-migrate/jquery-migrate.min.js?v=43cb37bd6467ff68d23900646453b604

**Comment by AppHelpdesk** [comment]
I am not sure if i understood it completely but did you mean that i should use version 1.4.0 to get the fix of issue? Please confirm

**Comment by ho4ho** [comment]
Mean ownCloud not using Jquery-migrate-1.2.1.min.js but juery-migrate 1.4.0

**Comment by cortho** [comment]
@AppHelpdesk, which ownCloud version are you referring to?
ownCloud >= 10 is using jquery-migrate.min.js 1.4.0
ownCloud < 10 is end of life, thus not supported any longer, see https://github.com/owncloud/core/wiki/maintenance-and-release-schedule
Suggestion: close

**Comment by VicDeo** [comment]
Closing as we indeed have jquery-migrate 1.4.0 for a long time

https://snyk.io/vuln/npm:jquery-migrate:20130419

Master: 
https://github.com/owncloud/core/blob/3e0bff712f3dcbd36273093ff10f4598c5816dce/build/yarn.lock#L60

<img width="600" alt="Screenshot_20200402_172232" src="https://user-images.githubusercontent.com/991300/78260407-99465b80-7506-11ea-9bee-9e2471a2f19e.png">
