### ISSUE TITLE
Improve error handling for incoming shares poll command

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#34981]
Steps to reproduce are not clear yet but might be guessable.

When running `occ incoming-shares:poll` there are multiple issues appearing:

1) Ghost users in oc_share_external where the user id doesn't exist on the current instance any more. This throws an unhandled exception. We should skip such entries. They'll likely get cleant up by some background jobs. (if not we need to raise as it would mean we're missing a cleanup job for these)

2) Unauthorized issues, possibly when the remote isn't accessible any more. Maybe the token expired or the remote share was deleted but somehow the local instance did not get notified. Or it's one of the "add to ownCloud" shares. `Sabre\HTTP\ClientHttpException: Unauthorized`. Need to skip these issues.

3) "Unable to parse malformed url: https:///ocm-provider/". Skip invalid URLs.

4) Other potential error cases ?

Maybe we should log those though with the id of the oc_share_external entry so an admin could decide to clean these up ?

**Comment by PVince81** [comment]
Extras:
- [ ] find out whether / why user is not cleared on deletion, I believe I heard @phil-davis or @individual-it mentionning this. we should add a "user delete" listener that clears the entries (separate ticket, if really missing)

**Comment by individual-it** [comment]
There are various places that are not cleaned up after user deletion.
e.g. avatar https://github.com/owncloud/core/issues/33875 or locks see this PR where we manually delete locks after test runs https://github.com/owncloud/core/pull/30538

**Comment by VicDeo** [comment]
share_external entries are cleared on user deletion. Moreover, it decline all pending shares first.

https://github.com/owncloud/core/blob/master/apps/files_sharing/appinfo/app.php#L30
https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/Helper.php#L43
https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/Hooks.php#L95-L105
https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/External/Manager.php#L377-L399
