### ISSUE TITLE
External Storage DFSR

### ISSUE THREAD

**Issue by VamPikmin** [owncloud/core#35006]
### Steps to reproduce
1. Add a SMB DFSR share
2. Try to browse the folders and download files
3. Certain files can't be downloaded 

### Expected behaviour
File should open or download instead I get a problem loading page

### Actual behaviour
Problem loading page

and apache segfaults [Fri Apr 12 08:50:02.457656 2019] [core:notice] [pid 8749] AH00051: child pid 8895 exit signal Segmentation fault (11), possible coredump in /etc/apache2

php-smbclient:
  Installed: 0.8.0~rc1-2build1
  Candidate: 0.8.0~rc1-2build1
  Version table:
 *** 0.8.0~rc1-2build1 500
        500 http://au.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     0.8.0~rc1-2 500
        500 http://au.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages

If I use a test.php with the following contents I get the same error

php

// Create new state:
$state = smbclient_state_new();

// Initialize the state with workgroup, username and password:
smbclient_state_init($state, null, 'n2022', 'pass');

// Open a file for reading:
//$file = smbclient_open($state, 'smb://spfps/Student Share/1 to 1 Files/temp.txt', 'r');
$file = smbclient_open($state, 'smb://spfps/Student Share/1 to 1 Files/Program Installs/Crocodile Clips/Crocodile Physics 605/product/Readme/ReadMe.html', 'r');

// Read the file incrementally, dump contents to output:
while (true) {
        $data = smbclient_read($state, $file, 100000);
        if ($data === false || strlen($data) === 0) {
                break;
        }
        echo $data;
}
// Close the file handle:
smbclient_close($state, $file);

// Free the state:
smbclient_state_free($state);

So it doesn't appear to be a permission issue

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache
**Database:**
mariadb
**PHP version:**
7.0
**ownCloud version:** (see ownCloud admin page)
10.1.0
**Updated from an older ownCloud or fresh install:**
Update
**Where did you install ownCloud from:**
tar.gz from the owncloud website
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
no issues found

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ho4ho** [comment]
Already reported by https://github.com/eduardok/libsmbclient-php/issues/67 where belongs?

**Comment by VamPikmin** [comment]
Thanks, I wasn't sure if it was php-smbclient or owncloud core issue

**Comment by ho4ho** [comment]
Segmentation fault always problem by apache or php.

**Comment by VamPikmin** [comment]
I've decided to upgrade and the Seg fault is gone however I can't see any files.

Server configuration

Operating system:
Ubuntu 18.04
Web server:
Apache
Database:
mariadb
PHP version:
7.2
ownCloud version: (see ownCloud admin page)
10.1.1
Updated from an older ownCloud or fresh install:
Update
Where did you install ownCloud from:
tar.gz from the owncloud website

```

root@cloud18:/# sudo -u www-data php /var/www/html/owncloud/occ files_external:list user -vvv
+----------+----------------+------------+-----------------------+------------------------------------------------------------------------------------------------------+---------+
| Mount ID | Mount Point    | Storage    | Authentication Type   | Configuration                                                                                        | Options |
+----------+----------------+------------+-----------------------+------------------------------------------------------------------------------------------------------+---------+
| 16       | /student share | SMB / CIFS | Username and password | host: "spfps", share: "Student Share", root: "", domain: "ecmelb", user: "user", password: "***"     |         |
+----------+----------------+------------+-----------------------+------------------------------------------------------------------------------------------------------+---------+

root@cloud18:/# sudo -u www-data php /var/www/html/owncloud/occ files_external:verify 16
  - status: ok
  - code: 0
  - message



root@cloud18:/# sudo -u www-data php /var/www/html/owncloud/occ files:scan --path /user/

Scanning files for 1 users
Starting scan for user 1 out of 1 (user)
Couldn't resolve \DfsrPrivate

+---------+-------+--------------+------------------+
| Folders | Files | Elapsed time | Items per second |
+---------+-------+--------------+------------------+
| 34      | 52    | 00:00:00     | 148              |
+---------+-------+--------------+------------------+
```
Only Domain Admins can access this share as they have access to DfsrPrivate, when I add storage as a student or staff no folders or files show up, since the scan cannot finish.

If I instead mount with a remote subfolder the files show up fine, as DfsrPrivate is not being scanned.

Is there a way to exclude the folder from being scanned? Excluded files and folders directive in config.php doesn't work

**Comment by VamPikmin** [comment]
This resolves the problem,
Will try on a second server just to be sure
https://github.com/owncloud/core/pull/36242/commits/621de702c688b216c068c1efb324dace6ded3e38

**Comment by DeepDiver1975** [comment]
can we close this now? THX
