### ISSUE TITLE
spaces at the end and the beginning of a filename are trimmed away for display

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#35017]
### Steps to reproduce
1. have a files called `   my file.txt    ` (spaces at the beginning and the end of the name)

### Expected behaviour
spaces are displayed in the UI

### Actual behaviour
spaces are trimmed 

![image](https://user-images.githubusercontent.com/2425577/56110340-d1f6c900-5f73-11e9-8add-694498e812e8.png)

`data-file` in the `tr` has the correct name but the content of `<span class="nametext">` has the trimmed name

so we can end up with same looking file names in the folder
![image](https://user-images.githubusercontent.com/2425577/56110453-3e71c800-5f74-11e9-9554-743452b34095.png)

CC @phil-davis we have tests that do renames to names with trailing and leading spaces, they all pass nicely because we only check the `data-file` attribute of `tr` not the human readable name

**Comment by phil-davis** [comment]
If `innernametext` has correct spaces before/after, then 
1) does the browser actually display any differently?
(I suspect that the browser is not going to display "true" white space anyway)
2) do the file names sort into "correct" order?
(file names starting with spaces come first before those starting with a digit or letter)
3) what is the display requirement when people put spaces at the start of a file name?
4) white space at the end of a file name is not going to be visible anyway (unless there is an option to right-justify file names in the column), and does not effect sort order
