### ISSUE TITLE
10.2.RC1 - smoke test results

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#35019]
# Smoke test

## Previous requirements

Prepare two servers with ssl activated and trusted certificates.

Enable LDAP and external storage apps.

Have a LDAP server ready to be used with owncloud.

Have ready two external storages of your choice SMB, SFTP, Dropbox, Google Drive, FTP, S3, ownCloud, local.

Scenarios to consider:
- [x] OAuth2 and sync + mobile clients ( can be deployed remotely )
- [x] LDAP 
- [x] Shibboleth
- [ ] Windows Network Drive (also use it as sync target ) 
- [ ] Guests
- [x] Impersonate
- [x] Login with App Token Login
- [x] TOTP

## Testing setup

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Enable encryption app and encryption default module | Encryption is enabled correctly |  :heavy_check_mark:  |
2 | Populate owncloud server with users and groups | Users and groups are correctly created | :heavy_check_mark:    |
3 | Share a folder remotely using federated sharing with admin user of the other server. | folder can be opened in recipient server without problems | :heavy_check_mark:    | issue (no regression) #35042
4 | Set up LDAP, as admin check users. log in with a LDAP user, if possible one with an avatar. | Users are loaded. LDAP user logs in without problems. Avatar is shown if it exists.  | :heavy_check_mark:   |
5 | Set up two external storages different, disable encryption in one of them.| No errors in this process | :heavy_check_mark:   |

## Testing functionality

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Share a file using federated sharing from an external unencrypted external storage in server #1 using a LDAP user to the admin user in server #2. | Admin user in server #2 can see the file. | :heavy_check_mark: |
2 | Open internet explorer or edge and upload a new avatar for a regular user not LDAP | Interface can be used, avatar is uploaded, check that personal page has a scroll bar and scrolls fine. | :heavy_check_mark:  |
3 | Upload several files and folders inside external storages, open some. | No problems uploading, files can be downloaded and opened. | :heavy_check_mark:  |
4 | Delete files inside both external storages. Recover some after from the trashbin. |  Files are correctly deleted and restored. |:heavy_check_mark:   |
5 | Using webdav upload a 100MiB file.| No errors in this process |:heavy_check_mark: |

**Comment by davitol** [comment]
10.2. oC version is out. Let's close the ticket
