### ISSUE TITLE
10.2 - Changelog Test Results

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#35020]
# Changelog

All notable changes to this project will be documented in this file.

Items based on https://github.com/owncloud/core/blob/stable10/CHANGELOG.md

### Added
#35051

### Changed
#35052

### Removed
#35053

### Fixed
 #35054

**Comment by PVince81** [comment]
Apps-external folder appears after install, but despite "apps" being non-writable in config.php, it still puts app updates there. Raised https://github.com/owncloud/core/issues/35031

**Comment by phil-davis** [comment]
Bump README.md doc links to 10.1 - #34403 - the link is invalid, issue #35035
It looks like it has been invalid at least since the docs conversion, and has been pointing into an odd place for a long time. PR #35036 to master.

**Comment by individual-it** [comment]
As multiple people working on that long list now, I've split it to reduce the risk of overwriting each-others results

**Comment by individual-it** [comment]
Things that could have been tested by acceptance tests

| Change | PR | issue found while testing | estimated effort to write tests | comment | 
|-----------|-----|-----|----|-- |
| Adding background:queue commands: status and delete | #34783 | | 0.25md|
| Added new permissions option for public link | #34983 | #35056 & #35057 | added by fix |  tests did exist, but not for the exact scenario |
| Support for automatically accepting incoming federated shares from trusted servers | #34206 | #35067 | 0.25md | tests do exist, but not for the exact scenario |
| User option to opt-out autocomplete in share dialog | #34942 | | 1md ||
| Extend repair command to be able to list repair steps and run them individually | #34499 | | 0.25md (just checking the output) ||
|  Command for first run wizard to reset for all users | firstrunwizard/#83 | | 0.25md | |
| Inform admin about the need to login again after changing the master encryption key | #34596 |  | 0.25md ||
| Added checkboxes to hide quota and password | #34479 | | 0.25md ||
| By default the "apps-external" directory is included in config.php during installation | #34656 #34902 | #35031 | 1md | |
| Allow admins to enable medial search on group and user | #34779 | #35066 (known issue with LDAP) | 0.5md | |
| Add occ command to poll incoming federated shares for updates | #34933 #34959 #34993 | | 1md | |
| Log exception when background job class not found | #34723  || ? |
| Fix public link share default expiration behavior | #34971 | | 1md ||
| Don't expose hashed password in OCS api | #34691 | | 0.25md | | 
| Fix chunking infinite loop in some environment related issues | #34558 | | ?  | might be complicated to corrupt the chunk |
| Properly hide share fields in "Shared with You" section when permissions are restricted | #34473 | | 1md | |
| Fix cancel upload and hide 'uploading' message for files_drop shared folders | #34097 | | ? | |

**Comment by PVince81** [comment]
> Tidy up code for notification by email

for this one, simply add acceptance tests for the "Notify by email" button in the share panel, both for users and groups

**Comment by PVince81** [comment]
> Extend repair command to be able to list repair steps and run them individually

already covered by unit test which checks the output, so probably not worth it

**Comment by PVince81** [comment]
> Log exception when background job class not found

ignore

> Fix chunking infinite loop in some environment related issues

ignore

> Fix cancel upload and hide 'uploading' message for files_drop shared folders

Would be nice to cover these upload scenarios as the frontend upload code is a bit twisted and fragile...

**Comment by individual-it** [comment]
- [x] some simple update tests from 10.1.1 with occ and webupdater :heavy_check_mark: 
- [ ]  installation of .deb package 
`dpkg -i ...` created `/var/www/owncloud` but not `/var/www/owncloud/apps-external` when installing (If I remember @pvince81 correctly that is what should happen)
but then when starting the web-installer it says `Can't create or write into the apps-external directory /var/www/owncloud/apps-external`
Or should it create that folder on install but not on update?

**Comment by individual-it** [comment]
I think we are done here for now
list for tests to be automated here https://github.com/owncloud/core/issues/35207
