### ISSUE TITLE
Etag for previews / thumbnails

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#35029]
I wonder if we should use etags for our thumbnails. this would let the browser query whether there's a new preview.

The endpoint would need to check the etag against the file's etag and return 304 not modified if there is no change instead of attempting to read the existing thumbnail from disk

For that we can simply use the file's etag from oc_filecache early on

It might not be much for the small thumbsnails but would save more traffic for files_mediaviewer when accessing bigger previews.

Maybe the preview size needs to be computed into the etag

I wonder if it would work as well with video previews...

Need to research whether browsers store Etags based only the URL resource part or whether it also covers URL parameters. Depending on this we might or might not need to change the way how the URLs are constructed, which we'll likely not want to change yet again.

If it can work with the current URL scheme it could be worth a try.

**Comment by DeepDiver1975** [comment]
The new preview endpoint does not send the etag header in the response - the browser in return has no chance to cache anything.

This was different in the old endpoint .... too bad.

We should consider this a bug/regression.

**Comment by PVince81** [comment]
I think we never sent etags before, even in the old endpoint.
We do return cache headers: https://github.com/owncloud/core/blob/stable10/apps/dav/lib/Files/PreviewPlugin.php#L134

**Comment by DeepDiver1975** [comment]
> I think we never sent etags before, even in the old endpoint.

hmmm .... did I mix this up with avatars ....

anyway - as soon as we return etags the situation should get much better ....
