### ISSUE TITLE
Missing WebDav authentication

### ISSUE THREAD

**Issue by Glamdring** [owncloud/core#35030]
### Steps to reproduce
1. Open the admin storage settings
2. add a new WebDAV storage
3. select username & password authentication and fill in the connection details, including username and password for basic authentication

### Expected behaviour
ownCloud should send an Authorization header to the WebDAV server and the indicator at the beginning of the row should go green

### Actual behaviour
ownCloud does not send any Authorization header and so the indicator at the beginning of the row goes red

### Server configuration
**ownCloud version:** 
10.1.1

**Updated from an older ownCloud or fresh install:**
fresh

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

Webdav

#### ownCloud log (data/owncloud.log)
It just says Unauthorized, which is expected, as it doesn't send an Authorization header

#### How I fixed it

I edited lib/private/Files/Storage/DAV.php and explicitly set ``$this->authType = 1;``. That resulted in a properly set Authorization header, the indicator went green and everything worked.

**Comment by PVince81** [comment]
what Webdav server are you using ?

I'm a bit surprised because we have automated tests that test against Apache Webdav and they pass.

The proposed fix seems to imply that the authType is set to 0 instead of AUTH_BASIC by default, not sure why.

A proper quickfix for this would be to check if `$params['authType']` is set and if not, fallback to AUTH_BASIC.

**Comment by Glamdring** [comment]
I'm using a custom WebDav server, but that's what allowed me to debug it and see that no Authorization header is passed. 

I agree that your quickfix is better; mine just got my usecase working.
