### ISSUE TITLE
10.2 RC1: upgrade script fails, database scheme error

### ISSUE THREAD

**Issue by thommierother** [owncloud/core#35058]
While cli upgrading from 10.1.0 to 10.2 RC1 I get on on an upgrade system:

...
2019-04-18T06:30:34+00:00 Repair step: Repair MySQL database engine
2019-04-18T06:30:37+00:00 Repair step: Repair MySQL collation
2019-04-18T06:30:38+00:00 Repair info: All tables already have the correct collation -> nothing to do
2019-04-18T06:30:38+00:00 Repair step: Repair SQLite autoincrement
2019-04-18T06:30:38+00:00 Repair step: Repair orphaned reshare
2019-04-18T06:30:38+00:00 Repair step: Repair duplicate entries in oc_lucene_status
2019-04-18T06:30:38+00:00 Repair info: lucene_status table does not exist -> nothing to do
2019-04-18T06:30:38+00:00 Updating database schema
2019-04-18T06:30:41+00:00 Doctrine\DBAL\Schema\SchemaException: The table with name 'owncloud2.oc_accounts' already exists.
2019-04-18T06:30:41+00:00 Update failed
2019-04-18T06:30:41+00:00 Maintenance mode is kept active
2019-04-18T06:30:41+00:00 Reset log level
...

**Comment by PVince81** [comment]
is it the same server where you had the issue with "oc_persistent_locks" from https://github.com/owncloud/core/issues/33963 ?

still unsure why migrations that already ran would be missing in "oc_migrations" table.

**Comment by thommierother** [comment]
Its the same server, yes. I don't understand it either. I re-created the whole database from a 10.1 backup and did the migration again without issues. Enclosed is the oc_migrations table, just for info.

**Comment by thommierother** [comment]
CREATE TABLE `oc_migrations` (
  `app` varchar(177) COLLATE utf8_unicode_ci NOT NULL,
  `version` varchar(14) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Daten für Tabelle `oc_migrations`
--

INSERT INTO `oc_migrations` (`app`, `version`) VALUES
('activity', '20161122085340'),
('activity', '20161122092159'),
('activity', '20170131134507'),
('activity', '20170724182159'),
('activity', '20181019151118'),
('activity', '20181022150134'),
('core', '20170101010100'),
('core', '20170101215145'),
('core', '20170111103310'),
('core', '20170213215145'),
('core', '20170214112458'),
('core', '20170221114437'),
('core', '20170221121536'),
('core', '20170315173825'),
('core', '20170320173955'),
('core', '20170418154659'),
('core', '20170516100103'),
('core', '20170526104128'),
('core', '20170605143658'),
('core', '20170711191432'),
('core', '20170804201253'),
('core', '20170928120000'),
('core', '20171026130750'),
('core', '20180123131835'),
('core', '20180302155233');

ALTER TABLE `oc_migrations`
  ADD PRIMARY KEY (`app`,`version`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;

**Comment by patrickjahns** [comment]
@thommierother 
could you double check what the `owncloud.log` mentions about migrations to be run? 

Example:
```
{"reqId":"D2HXLQ5odOHwxdUgdNQx","level":0,"time":"2019-04-26T10:05:32+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"starting upgrade from 10.0.10.4 to 10.1.0.4"}
{"reqId":"D2HXLQ5odOHwxdUgdNQx","level":0,"time":"2019-04-26T10:05:33+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: starting 20180607072706 from app core"}
{"reqId":"D2HXLQ5odOHwxdUgdNQx","level":0,"time":"2019-04-26T10:05:33+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: completed 20180607072706 from app core"}
{"reqId":"D2HXLQ5odOHwxdUgdNQx","level":0,"time":"2019-04-26T10:05:33+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: starting 20181017105216 from app core"}
{"reqId":"D2HXLQ5odOHwxdUgdNQx","level":0,"time":"2019-04-26T10:05:33+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: completed 20181017105216 from app core"}
{"reqId":"D2HXLQ5odOHwxdUgdNQx","level":0,"time":"2019-04-26T10:05:33+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: starting 20181017120818 from app core"}
{"reqId":"D2HXLQ5odOHwxdUgdNQx","level":0,"time":"2019-04-26T10:05:33+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: completed 20181017120818 from app core"}
{"reqId":"D2HXLQ5odOHwxdUgdNQx","level":0,"time":"2019-04-26T10:05:33+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: starting 20181113071753 from app core"}
{"reqId":"D2HXLQ5odOHwxdUgdNQx","level":0,"time":"2019-04-26T10:05:33+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: completed 20181113071753 from app core"}
```

Would like to double check which migration was triggered

**Comment by patrickjahns** [comment]
@thommierother - any update/progress here?

**Comment by thommierother** [comment]
First grep for Migrations:
find . -name \*.gz -print0 | xargs -0 zgrep "Migrations:"
./owncloud2.log.4.gz:{"reqId":"6zoh8nZjJt82ZQQRvD1n","level":0,"time":"2019-04-18T06:30:39+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: starting 20170214112458 from app core"}

And a bigger one for "Migrations" showing the exceptions:

find . -name \*.gz -print0 | xargs -0 zgrep "Migrations"
./owncloud2.log.4.gz:{"reqId":"6zoh8nZjJt82ZQQRvD1n","level":0,"time":"2019-04-18T06:30:39+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: starting 20170214112458 from app core"}
./owncloud2.log.4.gz:{"reqId":"6zoh8nZjJt82ZQQRvD1n","level":3,"time":"2019-04-18T06:30:41+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Schema\\\\SchemaException\",\"Message\":\"The table with name 'owncloud2.oc_accounts' already exists.\",\"Code\":20,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/Schema.php(132): Doctrine\\\\DBAL\\\\Schema\\\\SchemaException::tableAlreadyExists('owncloud2.oc_ac...')\\n#1 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/Schema.php(340): Doctrine\\\\DBAL\\\\Schema\\\\Schema->_addTable(Object(Doctrine\\\\DBAL\\\\Schema\\\\Table))\\n#2 \\\/var\\\/www\\\/owncloud2\\\/core\\\/Migrations\\\/Version20170214112458.php(11): Doctrine\\\\DBAL\\\\Schema\\\\Schema->createTable('oc_accounts')\\n#3 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/DB\\\/MigrationService.php(411): OC\\\\Migrations\\\\Version20170214112458->changeSchema(Object(Doctrine\\\\DBAL\\\\Schema\\\\Schema), Array)\\n#4 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/DB\\\/MigrationService.php(366): OC\\\\DB\\\\MigrationService->executeStep(20170214112458)\\n#5 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/Updater.php(307): OC\\\\DB\\\\MigrationService->migrate()\\n#6 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/Updater.php(261): OC\\\\Updater->doCoreUpgrade()\\n#7 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/Updater.php(112): OC\\\\Updater->doUpgrade('10.2.0.1', '10.1.0.4')\\n#8 \\\/var\\\/www\\\/owncloud2\\\/core\\\/Command\\\/Upgrade.php(261): OC\\\\Updater->upgrade()\\n#9 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/composer\\\/symfony\\\/console\\\/Command\\\/Command.php(255): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#10 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(960): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#11 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(255): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#12 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(148): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#13 \\\/var\\\/www\\\/owncloud2\\\/lib\\\/private\\\/Console\\\/Application.php(161): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#14 \\\/var\\\/www\\\/owncloud2\\\/console.php(106): OC\\\\Console\\\\Application->run()\\n#15 \\\/var\\\/www\\\/owncloud2\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud2\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Schema\\\/SchemaException.php\",\"Line\":109}"}

SOrry if it is not helpful any more, maybe some events are older than the logs ...

**Comment by GrendelWWU** [comment]
Did you make an _occ db:generate-change-script_ before to make some db changes directly?

**Comment by thommierother** [comment]
no, I never used this occ command

**Comment by GrendelWWU** [comment]
Some versions ago, we were advised doing so, before updating... The output is a collection of SQL commands that represent database changes. From 10.0.10 to 10.1.0 it was

> DROP INDEX tag_ident ON oc_systemtag;
> ALTER TABLE oc_systemtag ADD `assignable` SMALLINT DEFAULT 1 NOT NULL;
> CREATE UNIQUE INDEX tag_ident ON oc_systemtag (`name`, `visibility`, `editable`, `assignable`);

So you can do most of he important db changes before running _occ upgrade_.

**Comment by GrendelWWU** [comment]
Ok, I just heard, this command is no longer availale. Sorry for confusing....

**Comment by GrendelWWU** [comment]
Is there any news? Can this error (oc_accounts) be reproduced?

**Comment by thommierother** [comment]
I could not reproduce it here in my development environment and the original databases are no longer there, at least not with a "clean history" of all occ upgrade changes. Therefore I will close the issue.
