### ISSUE TITLE
Adblock admin sharing settings hiding

### ISSUE THREAD

**Issue by ho4ho** [owncloud/core#35070]
### Steps to reproduce
1. Enabled Adblock
2. Check admin settings
3. Disabled Adblock
4. Check again addmin settings

### Expected behaviour
Warning on Adblock shown or sharing icon shown.

Maybe use idea by https://github.com/sualko/cloud_piwik/pull/65 or by https://github.com/nextcloud/server/pull/4337?

### Actual behaviour
With Adblock no sharing icon

![admin_adblock](https://user-images.githubusercontent.com/42564859/56422940-35516580-62aa-11e9-83b0-d7baa423dc97.png)

Without Adblock sharing icon

![admin_noadblock](https://user-images.githubusercontent.com/42564859/56422953-44381800-62aa-11e9-8ed0-7198a106db8d.png)

### Server configuration
**ownCloud version:** 10.1.1

### Client configuration
**Browser:** Firefox 66.0.3 + Adblock +

Adblock Warning Removal List
Fanboy's Social Blocking List
ABP filters
EasyList
Allow nonintrusive advertising without third-party tracking

**Comment by ho4ho** [comment]
Similar issue by past: https://github.com/owncloud/core/issues/24190, https://github.com/owncloud/core/issues/17581, https://github.com/owncloud/core/issues/2711, https://github.com/owncloud/core/issues/17053, https://github.com/owncloud/core/issues/8360, https://github.com/owncloud/core/issues/6913

**Comment by PVince81** [comment]
so it seems that renaming "share-*" to "shared-*" would solve the issue.

however if the icon file name needs to be renamed, it could have an impact on some themes that might use this name, so would consider this a breaking change that needs mentioning in release notes.

cc @pmaier1

**Comment by pmaier1** [comment]
Thanks for reporting this issue. Just a side note: ABP is not the best adblock solution as you can whitelist addresses if you put in some coins. Better use 'uBlock'. The described issue does not occur with this one ;)

**Comment by ho4ho** [comment]
> Better use 'uBlock'. The described issue does not occur with this one ;)

Happen also: https://github.com/owncloud/core/issues/33642

**Comment by ho4ho** [comment]
Contacts: https://github.com/owncloud/contacts/pull/663
Activity: https://github.com/owncloud/activity/issues/727
