### ISSUE TITLE
Notify by email on group share can be done multiple times

### ISSUE THREAD

**Issue by dpakach** [owncloud/core#35089]
### Steps to reproduce
1. Log in as admin, enable share notifications by email
2. create a group with multiple users in it
3. Share a file with the group and click notify by email button
4. reload the page.

### Expected behaviour
according to https://github.com/owncloud/core/pull/33180 the `notify by email` button should disappear after sending the email once.

### Actual behaviour
The notify by email button reappears and the sharer can send email to all users on the group again.

**Comment by PVince81** [comment]
can you check if this happens on 10.1.1 also ? just to know whether it's a regression

**Comment by patrickjahns** [comment]
IF not a regression - we'll talk with product management about desired behaviour and document it via an acceptance test

**Comment by dpakach** [comment]
@PVince81 @patrickjahns The problem doesnot exist in 10.1.1, Seems like it was introduced by https://github.com/owncloud/core/pull/33180/files

**Comment by PVince81** [comment]
ok, it's a regression then. thanks

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/33180 is the backport of @VicDeo's code cleanup.

@VicDeo do you have any clue whether this would be an easy fix or should we revert ?

**Comment by PVince81** [comment]
@dpakach can we cover this with a UI test maybe ?

the cause of the issue was related to some code cleanup of old APIs, now we'll revert partly. there is a risk that a future backport of another related cleanup would bring this issue back in some form, so it might be worth covering this with acceptance tests then

**Comment by PVince81** [comment]
this also means that the feature is broken currently on master

**Comment by patrickjahns** [comment]
> there is a risk that a future backport of another related cleanup would bring this issue back in some form, so it might be worth covering this with acceptance tests then

@PVince81 @phil-davis - do we have a ticket to track acceptance tests for this issue yet?

**Comment by phil-davis** [comment]
@dpakach are there tests anywhere for this? Or an issue for making tests?

**Comment by dpakach** [comment]
@phil-davis There are no tests or issues for this scenario.
I will make a issue for this now.

**Comment by dpakach** [comment]
Issue raised at #35195
