### ISSUE TITLE
File upload on files_drop does not abort  if tried to cancel after waiting for few seconds

### ISSUE THREAD

**Issue by skshetry** [owncloud/core#35086]
Regarding #34097:

Canceling upload in files_drop did not work correctly if it is canceled after waiting for a few sec. But, this does work if it is canceled immediately (which didn't work on `v10.1.1`).  The uploading message does disappear after the file is uploaded.

See test video here: https://cloud.owncloud.com/index.php/s/1psr6GzChn3u83L

_Originally posted by @skshetry in https://github.com/owncloud/core/issues/35054#issuecomment-486070762_

### Steps to reproduce
1. Share a public link for files_drop.
2.  Upload a file (upload a large file so you have a larger window to cancel upload).
3. Wait for a few seconds (but not too much that the time you cancel, it's already uploaded).
4. Cancel upload

### Expected behavior
`Uploading...` message disappears and the file uploading is canceled. 

### Actual behavior
`Uploading...` doesn't disappear. The file gets uploaded and the message(`Uploading...`) disappears.

### Server configuration
**Operating system**: Ubuntu 18.04.2

**Web server:** Apache/2.4.29 (Ubuntu)

**Database:** mysql  Ver 14.14 Distrib 5.7.25, for Linux (x86_64)

**PHP version:** PHP 7.2.17-1+ubuntu18.04.1+deb.sury.org+3 (cli) (built: Apr 10 2019 10:50:57) ( NTS )

**ownCloud version:** (see ownCloud admin page) ownCloud 10.2.0 RC1 (stable) 

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** Tarball

**Are you using external storage, if yes which one:** local/sftp

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 66.0.3 (64-bit)/ Chrome 73

**Operating system:** Ubuntu 18.04.2

**Comment by skshetry** [comment]
@PVince81, looks like the bug was when we try to cancel upload after already canceling upload once in the first try. 
So, if you:
1. Create a files_drop link.
2. Open the share link.
3. Try to upload a file and then cancel it.
4. Try to again re-upload and cancel it.

Then, the file upload does not cancel. It works if we reload the tab and retry.

**Comment by PVince81** [comment]
ok thanks, so it's a different bug

**Comment by PVince81** [comment]
@sharidas can you debug this ?

**Comment by sharidas** [comment]
While looking into the issue, its been found that when the page is refreshed manually the `Upload cancelled` appears when the upload is cancelled every time. When the page is not refreshed the `Upload cancelled` appears for the first time when the upload is cancelled and later on it doesn't appears. 

Will add more findings here.
