### ISSUE TITLE
File versioning does not work within shared file

### ISSUE THREAD

**Issue by kamleshahuja** [owncloud/core#35088]
### Steps to reproduce
1. Files update in shared folder by any user is not show in Version 
2. update any file shared 
3. loggin to owncloud web check the file details versions

### Expected behaviour
A new version of the file should appear under 'Versions'

### Actual behaviour
Under activity one can see that the file has been updated. However under versions there remain 'No  versions are available.

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

10.0.10

**Updated from an older ownCloud or fresh install:**
Fresh Install 

**Where did you install ownCloud from:**
Univention-App-owncloud-ESX.ova

**Signing status (ownCloud 9.0 and above):**
no
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'datadirectory' => '/var/lib/univention-appcenter/apps/owncloud/data/files',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/owncloud/custom',
      'url' => '/custom',
      'writable' => true,
    ),
  ),
  'dbtype' => 'mysql',
  'dbhost' => 'REMOVED SENSITIVE VALUE"
  'dbname' => 'REMOVED SENSITIVE VALUE",
  'dbuser' => 'REMOVED SENSITIVE VALUE",
  'dbpassword' => 'REMOVED SENSITIVE VALUE",
  'dbtableprefix' => 'oc_',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'passwordsalt' => 'REMOVED SENSITIVE VALUE",
  'secret' => 'REMOVED SENSITIVE VALUE",
  'overwrite.cli.url' => 'http://localhost/owncloud',
  'version' => '10.0.10.4',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => 'oc7t7ka333kf',
  'ldapIgnoreNamingRules' => false,
  'updatechecker' => 'false',
  'upgrade.disable-web' => true,
  'filelocking.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'maintenance' => false,
  'loglevel' => '3',
  'default_language' => 'en',
  'htaccess.RewriteBase' => '/owncloud',
  'log_rotate_size' => 104857600,
  'versions_retention_obligation' => 'auto',
  'activity_expire_days' => 365,
  'onlyoffice' => 
  array (
    'verify_peer_off' => true,
  ),
  'log_type' => 'owncloud',
  'supportedDatabases' => 
  array (
    0 => 'sqlite',
    1 => 'mysql',
    2 => 'pgsql',
  ),
  'logfile' => '/var/lib/univention-appcenter/apps/owncloud/data/files/owncloud.log',
  'log_rotate_size' => 104857600,
  'onlyoffice' => array ('verify_peer_off' => TRUE),
);

**List of activated apps:**

APP | VERSION | INFO
-- | -- | --
Auditing | 1.0.2 |  
LDAP Home   Connector | 0.4.1 |  
ownCloud X   Enterprise Theme | 2.1.1 |  
File Firewall | 2.8.0 |  
Object Storage   Support | 0.5.1 |  
External   Storage: SharePoint | 0.3.0 |  
Collaborative   Tags Management | 0.3.1 |  
External   Storage: Windows Network Drives | 0.7.4 |  
Enterprise   License Key | 0.2.0 |  
SAML/SSO   Integration | 3.3.0 |  
Workflows | 0.3.0 |  
Ransomware   Protection | 1.1.0 |  
Document   Classification | 1.0.3 |  
  |   |  

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory

### Client configuration
**Browser:**
Google Chrome 
Version 74.0.3729.108 

**Operating system:**
windows 10 pro
Version 1809
#### Web server error log
Nothing showing up
``

#### ownCloud log (data/owncloud.log)
Nothing showing up

Browser log
Nothing in console nor i network log

**Comment by ho4ho** [comment]
Duplicate by https://github.com/owncloud/core/issues/33507 ?

**Comment by phil-davis** [comment]
And try with version `10.1.1` - it is likely fixed there. If so, then close this issue. If not, then give a more detailed scenario that fails in `10.1.1`

**Comment by kamleshahuja** [comment]
> And try with version `10.1.1` - it is likely fixed there. If so, then close this issue. If not, then give a more detailed scenario that fails in `10.1.1`

how can we upgrade to 10.1.1 without losing data.

**Comment by ho4ho** [comment]
Try update help for https://doc.owncloud.org/server/admin_manual/maintenance/upgrade.html and https://central.owncloud.org/c/server

**Comment by kamleshahuja** [comment]
> Try update help for https://doc.owncloud.org/server/admin_manual/maintenance/upgrade.html and https://central.owncloud.org/c/server

Its for Docket and manually installed own cloud. but not for Appliance ESX Image

**Comment by ho4ho** [comment]
Same by appliance: https://doc.owncloud.org/server/admin_manual/appliance/howto-update-owncloud.html

If no update need wait for one.

**Comment by kamleshahuja** [comment]
> Same by appliance: https://doc.owncloud.org/server/admin_manual/appliance/howto-update-owncloud.html
> 
> If no update need wait for one.

i tried the said option but update available.

root@owncloud:~# univention-app info
UCS: 4.4-0 errata59
Installed: adconnector=12.0 samba-memberserver=4.7 4.3/owncloud=10.0.10-2019-02-18
Upgradable:
root@owncloud:~#

**Comment by ho4ho** [comment]
Then:

> If no update need wait for one.

**Comment by kamleshahuja** [comment]
> Then:
> 
> > If no update need wait for one.

I have found the fix for Own Cloud file versioning.

It has a bug, when root account (in our case root account was owncloud default account) is used with client application it clears the version of the files. Work around that bug is we have created the user “root” and main root folder created by user “root” via web and not to used own cloud client. 

we observed the folder behavior for 2 weeks and file versioning is working with this work around.

Version issue is with user creating the folder for sharing and using same user in own cloud client for backup or any other purpose.

Thanks for your help.

**Comment by kamleshahuja** [comment]
> > Then:
> > > If no update need wait for one.
> 
> I have found the fix for Own Cloud file versioning.
> 
> It has a bug, when root account (in our case root account was owncloud default account) is used with client application it clears the version of the files. Work around that bug is we have created the user “root” and main root folder created by user “root” via web and not to used own cloud client.
> 
> we observed the folder behavior for 2 weeks and file versioning is working with this work around.
> 
> Version issue is with user creating the folder for sharing and using same user in own cloud client for backup or any other purpose.
> 
> Thanks for your help.

have already tried updated the config file for that as per below link   but that too didn’t worked
https://doc.owncloud.com/server/admin_manual/configuration/files/file_versioning.html
