### ISSUE TITLE
File size changes to less than 1KB while trying to open large text file

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/core#35080]
### Steps to reproduce
1. Install `files_texteditor` app
2. Upload text file with size larger than 6MB
3. Try to open the file
4. You get the error dialog with the text 'This file is too big to be opened. Please download the file instead.'
5. Then the file size changes to `<1KB` and last modified changes to `?` (unable to determine the data)

### Expected behavior
File size and last modified should not be changed.

### Actual behavior
File size and last modified changes.
![image](https://user-images.githubusercontent.com/20378877/56566779-30a2ef00-65d3-11e9-97c7-75a8ed0d6fa0.png)

![image](https://user-images.githubusercontent.com/20378877/56566823-49130980-65d3-11e9-9f9b-500e66919bcf.png)

Note: After refreshing the page everything goes to normal.

c.c @individual-it @phil-davis @PVince81 @DeepDiver1975

**Comment by individual-it** [comment]
Not a regression, also happens with oC 10.1.1

**Comment by PVince81** [comment]
thanks for the regression check, moving to backlog

**Comment by DeepDiver1975** [comment]
pure texteditor issue -> closing in here
