### ISSUE TITLE
header set twice in 4xx responses

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#35093]
### Steps to reproduce
I'm testing the backport of https://github.com/owncloud/core/pull/31231 for 10.2.0RC1
and it looks to me that the change made it worse, but also I might have a setup issue

1. enable apache `headers` module
1.  in apache config add 
    ```
    <IfModule mod_headers.c>
    Header set X-Content-Type-Options "bloedsin"
    </IfModule>
    ```
1. make sure the header is set for oC unrelated requests
1. update htaccess `sudo -u www-data ./occ  maintenance:update:htaccess` (maybe not needed)
1. force a 404 or 401 response e.g `curl -v http://localhost/owncloud-10.2.0/rc1_a/remote.php/dav/files/admin/file.txt`

### Expected behaviour
`X-Content-Type-Options` header set once

### Actual behaviour
in 10.2.0RC1 the header is set twice
```
< HTTP/1.1 401 Unauthorized
< Date: Wed, 24 Apr 2019 12:04:12 GMT
< Server: Apache/2.4.39 (Ubuntu)
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Robots-Tag: none
< X-Frame-Options: SAMEORIGIN
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Set-Cookie: oc1fqx9gxt25=87i4aopfu3m27a2pcfnrfpt50l; path=/owncloud-10.2.0/rc1_a; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=MPQ1wpbNO8gu312ik3Sr2WPO6fWNo3DXYA83MKgdfMEA3LWxDrs6uRCiDeesfCwp1YFMpeaRU4LW0vst4nh9hbNZtuvdfZZEO8BhrJMiOxTeFnWa%2B3ydxp1rVn1gX8PU; path=/owncloud-10.2.0/rc1_a; HttpOnly
< Content-Security-Policy: default-src 'none';
< WWW-Authenticate: Basic realm="ownCloud", charset="UTF-8"
< X-Content-Type-Options: bloedsin
< Content-Length: 448
< Content-Type: application/xml; charset=utf-8
```

in 10.1.1 it is set once
```
< HTTP/1.1 401 Unauthorized
< Date: Wed, 24 Apr 2019 12:06:02 GMT
< Server: Apache/2.4.39 (Ubuntu)
< Set-Cookie: ocehgs8bzhbd=594e3992ghfn72uc1rlacp56qi; path=/owncloud-10.1.1/owncloud; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Set-Cookie: oc_sessionPassphrase=09fMzDqgTBeDvA00CurXkjs2CWcEudDn4Y6s%2BAnL1uDyf7YyE5%2B47g9M07EmSMtCBgZIJqO9JoBqKls5vCk2RMD9FczD3MC8irW7nNeN2itJcvciywZ3h59JEOGaEqYF; path=/owncloud-10.1.1/owncloud; HttpOnly
< Content-Security-Policy: default-src 'none';
< WWW-Authenticate: Basic realm="ownCloud", charset="UTF-8"
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Robots-Tag: none
< X-Frame-Options: SAMEORIGIN
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Content-Length: 448
< Content-Type: application/xml; charset=utf-8
```

changing 
`Header always set X-Content-Type-Options "nosniff"` to `Header set X-Content-Type-Options "nosniff"` fixes it also in 10.2.0RC1

@mmattel @PVince81 @DeepDiver1975 @benrubson is that a regression or is my setup not what the change was about?

**Comment by benrubson** [comment]
Hi @individual-it,

This behavior is expected, some more info why here :
https://httpd.apache.org/docs/2.4/en/mod/mod_headers.html#header

You should then rather use the following in your Apache configuration :
`Header always set X-Content-Type-Options "bloedsin"`
or :
`Header set X-Content-Type-Options "bloedsin" "expr=-z %{resp:X-Content-Type-Options}"`
or even better from my point of view, the combination of both :
`Header always set X-Content-Type-Options "bloedsin" "expr=-z %{resp:X-Content-Type-Options}"`

Feel free if needed 👍

**Comment by benrubson** [comment]
Another solution would be to prefix every `Header` rule in the `.htaccess` file by the following :
`Header unset <header>`
For example :
`Header unset X-Content-Type-Options`
`Header always set X-Content-Type-Options "nosniff"`

The first one would remove the header from `onsuccess` table, which could have potentially been set in the Apache server configuration.
The second one would force the header in `always` table, whether it already exists (already set in the Apache server configuration) or not.

**Comment by individual-it** [comment]
@benrubson thank you for the explanation
I was just surprised that the "problem" did not occur before your change in https://github.com/owncloud/core/pull/31231
can you explain which exact situation you tried to fix with that change, so I can test it for the QA of 10.2.0

**Comment by mmattel** [comment]
Do we need a documentation improvement?

**Comment by benrubson** [comment]
> I was just surprised that the "problem" did not occur before your change in #31231

Well, it occurred if Apache configuration itself used `Header always set`.
Now that `.htaccess` uses `Header always set`, it occurs if Apache configuration uses `Header set`...

Anyway, I think that `Header always set` is better in `.htaccess` file, in order to be sure to set headers even in some error situations they could not be set with simple `Header set`.

> can you explain which exact situation you tried to fix with that change, so I can test it for the QA of 10.2.0

Goal was to avoid headers set twice, when Apache configuration already uses `Header always set` with same headers, for security reasons for example.
Of course as you mentioned headers can popup twice if ever Apache configuration uses the more simple form `Header set`.
But as explained above, from my point of view, the PR is worth it.

> Do we need a documentation improvement?

I'm not sure no, I think we should rather push an additional PR with solution given in my https://github.com/owncloud/core/issues/35093#issuecomment-486422488 above.
See PR #35099 I just pushed for this 👍

**Comment by benrubson** [comment]
And see #35118 for backport to the "release-10.2.0" branch.
