### ISSUE TITLE
Less clear error message when running check-code occ command on the app with invalid appinfo.xml

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/core#35092]
### Steps to reproduce
1) Change appinfo.xml to an invalid XML
2) Run the command ./occ app:check-code <app_name>
3) See an InvalidArgumentException\ thrown in owncloud.log with message Could not convert XML to array (which is expected)

4) But error message on occ command is not clear as it only says `No app with given id <app_name> known. `

### Expected behaviour
Better error message `$appId has invalid XML in appinfo.xml` 

### Actual behaviour
Less clear error message `No app with given id <app_name> known. `

**Note** There is already a code for it https://github.com/owncloud/core/blob/6f1e2bbd93db9430dbb41572eec01559c0dedeab/core/Command/App/CheckCode.php#L128

But the command explodes while checking the app code so info.xml check is never started.

c.c @individual-it @phil-davis @PVince81 @VicDeo

**Comment by PVince81** [comment]
won't fix, the code checker will be replaced at some point and shouldn't be used any more...
