### ISSUE TITLE
10.2 RC1 Share with "federation" text is cut off

### ISSUE THREAD

**Issue by thommierother** [owncloud/core#35098]
- Version 10.2 RC1
- Federating folder with a productive 10.1 instance 
- Entering federation ID for 10.1 instance

Federation is not possible, error message about invalid email
![Screenshot_20190425_203625](https://user-images.githubusercontent.com/6594120/56760641-f0429d00-679b-11e9-90f9-42ef65c8a60a.png)

**Comment by PVince81** [comment]
any special chars in the email address ? international chars ? international domain ?

**Comment by PVince81** [comment]
hmm wait, there shouldn't be any email validation for federation.

did you click on the federation entry or the guest entry ? (if you have guest enabled).

would be good to have more info, logs, etc, like rquested in the [issue template](https://github.com/owncloud/core/blob/master/.github/issue_template.md)

**Comment by PVince81** [comment]
@individual-it do we have acceptance tests that create federated shares over the UI ?

we do have some on the API level and they work through CI

**Comment by phil-davis** [comment]
https://github.com/owncloud/core/blob/master/tests/acceptance/features/webUISharingExternal/federationSharing.feature#L15 uses the webUI to do a federated share.

CI runs with the federated server having last night's stable10 QA tarball. We don't (currently) run federated tests against released versions (e.g. it would be good to know that federated sharing from an upcoming 10.2 system will work fine to another system still running 10.0.10, 10.1.0 or 10.1.1)

**Comment by thommierother** [comment]
I used Sharing, "user and groups" tab and entered the fed ID in the input field. Then the "Add to ..." filed. But I see now that the problem is different: the "(federated)" string is cut off in the widget, i used the Add ... (guest) entry, the mail validation error appears only when adding to the guests group. Mail adresses used are "normal" (admin@netzwissen.de is the sender, t.rother@netzwissen.de is the receiver). 

But I think this is a) more an UI issue (info of selectedentry for "federation" or "add as guest" should always be visible, not cut off) and b) the validation error appears in conjunction with the guest group, not the federation.

logs/issue template: I have the logfile on level 0, but no logs entry connected to this event, only token validations ...

**Comment by PVince81** [comment]
@thommierother if easy to recreate, mind posting a screenshot ? it will illustrate the bug well.

I've rename the subject to be about the UI

**Comment by thommierother** [comment]
![Screenshot_20190502_221751](https://user-images.githubusercontent.com/6594120/57104363-6c069180-6d28-11e9-8ec1-39f5a5420efa.png)

**Comment by PVince81** [comment]
we also had reports of users who mistakenly clicked the federrated share link instead of the regular one, maybe could also be related to length.

**Comment by karakayasemi** [comment]
I read discussions on https://github.com/owncloud/enterprise/issues/2344 and https://github.com/owncloud/core/issues/30151. As far as I see, currently there is no proposol agreed by everyone. Also they can be considered as out scope of this ticket. 

If I only consider this ticket I would do some css tricks to show all text whatever its length. IMHO, at least for this ticket it is fastest solution. @pmaier1 , @PVince81, @micbar Do you have any other suggestion for this ticket?

**Comment by karakayasemi** [comment]
What about giving informations like groups, federated etc. as a prefix instead of suffix like below?
![image](https://user-images.githubusercontent.com/14157973/57868441-aa617d80-780b-11e9-976c-e006e491de08.png)

**Comment by thommierother** [comment]
good idea!

**Comment by PVince81** [comment]
@pmaier1 ^

**Comment by pmaier1** [comment]
> What about giving informations like groups, federated etc. as a prefix instead of suffix like below?

Hmm, yeah, the root problem is that the suggestion entries can be longer than what the dropdown is able to display. For regular user shares you could also have a long user/display name and even add the user's mail address in parentheses via the config option "Extra field to display in autocomplete results" in admin sharing settings. 

Also, I don't know how this relates to 10.2 RC1. To my knowledge this is a general issue which prevails for a longer time.

If we change to prefix we would also need to change what the guests app shows. Not sure whether I'm happy with that. Other ideas?

In the new frontend (Phoenix) we'll definitely find a solution that will tackle the issue once for all.

**Comment by pmaier1** [comment]
Is there a quick way to distribute the information vertically instead of limiting to one line?
Something like:
- Display name / user name / email address
- Type
- Additional attributes like email
