### ISSUE TITLE
Checkbox missing in Google Chrome 74

### ISSUE THREAD

**Issue by HarDX** [owncloud/core#35096]
### Steps to reproduce
1. Open Google Chrome
2. Open URL owncloud
3. Any checkbox miss

### Expected behaviour
Checkbox must be visible

### Actual behaviour
Checkbox not visible in old owncloud 10.0.. and after upgrade to 10.1 too, but present in source and visible in IE/Firefox

### Server configuration
**Operating system**: Centos 6

**Web server:** apache 2.2.15

**Database:** mariadb 10.1.38

**PHP version:** 5.6.40

**ownCloud version:** version | 10.1.1.1 versionstring | 10.1.1

**Updated from an older ownCloud or fresh install:** update

**Where did you install ownCloud from:** Centos 7 repo

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found in integrity check
```

### Client configuration
**Browser:** Google Chrome 74.0.3729.108 (64 bit)

**Operating system:** Windows 10

#### Browser log
```
<input type="checkbox" id="select_all_files" class="select-all checkbox">
<label for="select_all_files">
<span class="hidden-visually">Select all</span>
</label>
```

**Comment by PVince81** [comment]
works for me
<img width="493" alt="image" src="https://user-images.githubusercontent.com/277525/56738353-ba39f480-676c-11e9-9c8b-34f6fc11e25c.png">

this is OC 10.2.0 RC1 with google-chrome-stable-74.0.3729.108-1.x86_64 on openSUSE Tumbleweed.

Please verify whether you have any addons that might interefere with the page.

**Comment by HarDX** [comment]
![2019-04-25-182103](https://user-images.githubusercontent.com/5231223/56738871-fbd79900-6786-11e9-8dfd-4bf8191771da.png)

**Comment by HarDX** [comment]
i try in incognito mode and other (checkbox near - Имя (Name))

**Comment by HarDX** [comment]
In IE11
![2019-04-25-182437](https://user-images.githubusercontent.com/5231223/56739110-6a1c5b80-6787-11e9-8b92-ae5e438617b1.png)

**Comment by PVince81** [comment]
also works for me, I tried Russian language just in case:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/277525/56739291-a0011600-676e-11e9-9d49-b702e08be82e.png">

**Comment by PVince81** [comment]
are the DOM elements rendered ? if yes you could check if there is any CSS rule preventing them to appear.

in my setup this is a freshly installed Chrome with no extra extensions

**Comment by HarDX** [comment]
I try - clean profile on Chrome - all works, i try find in old profile what happen

**Comment by HarDX** [comment]
Cann't find. I clear profile and resync all things - plugins and etc. all works fine...

**Comment by PVince81** [comment]
probably some caching issue then, closing.
