### ISSUE TITLE
Can´t change email address

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/core#35103]
### Steps to reproduce
1. Login as normal user (no admin and no groupadmin)
2. open the personal setting page
3. 

### Expected behaviour
Tell us what should happen
I can´t change my display name, but I can change my email address.

### Actual behaviour
Tell us what happens instead
I can´t change my display name and my email address.

### Server configuration
**Operating system**:

**Web server:**
Server version: Apache/2.4.25 (Raspbian)
**Database:**

**PHP version:**
PHP 7.0.33-0+deb9u3
**ownCloud version:** (see ownCloud admin page)
10.0.10
**Updated from an older ownCloud or fresh install:**
updated
**Where did you install ownCloud from:**
tarball
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocoq89hwbqzx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nas",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/media\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***\/owncloud",
        "htaccess.RewriteBase": "\/owncloud",
        "dbtype": "mysql",
        "version": "10.0.10.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "mail_smtpmode": "smtp",
        "default_language": "de",
        "trashbin_retention_obligation": "auto, 30",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "defaultapp": "files",
        "overwriteprotocol": "https",
        "updatechecker": false,
        "blacklisted_files": [
            ".htaccess"
        ],
        "enable_avatars": true,
        "asset-pipeline.enabled": true,
        "activity_expire_days": 365,
        "quota_include_external_storage": false,
        "versions_retention_obligation": "auto, 7",
        "allow_user_to_change_display_name": false,
        "knowledgebaseenabled": false,
        "session_lifetime": 86400,
        "check_for_working_htaccess": true,
        "maintenance": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "log_rotate_size": 104857600,
        "session_keepalive": true,
        "mail_smtpsecure": "ssl",
        "mail_smtpdebug": true,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "integrity.ignore.missing.app.signature": [
            "theme-***REMOVED SENSITIVE VALUE***"
        ]
    }
}
```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ho4ho** [comment]
"Can't" very less detailed in posting. :disappointed:

**Comment by prsnbrg** [comment]
Sry,
what I mean with "Can't" is that I don't have an input field. The Name and the email address show as normal text and not as value in an input field. So I can't change anything.

I have the same error on oC 10.1.1

![missing input field email](https://user-images.githubusercontent.com/29964525/56811310-bb385800-6838-11e9-9ab5-30c0eaf01133.JPG)

**Comment by davitol** [comment]
Is that user an LDAP user or a user provided from an "user backend"? In that case I think users cannot edit the FUll name or the email

**Comment by prsnbrg** [comment]
The user was created and administrated from the owncloud instance.

I have set the configuration option, no user can change their display name, baut I think it should be possible to change the email address without contact to the admin (me).

**Comment by davitol** [comment]
OK, i think now I got it. ```'allow_user_to_change_display_name' => false,``` option is set in config.php. But this affects to the mail too. @pmaier1  to triage if we consider it as a bug


![Screen Shot 2019-05-15 at 13 07 33](https://user-images.githubusercontent.com/10596560/57771342-b9183980-7712-11e9-92c0-8e23748b750f.png)

**Comment by ho4ho** [comment]
Similar of https://github.com/owncloud/core/pull/29132, https://github.com/owncloud/core/issues/27442 ?

**Comment by davitol** [comment]
> Similar of #29132, #27442 ?

IMHO no, here we are talking about that the email is not editable after setting 'allow_user_to_change_display_name' => false, in the config.php

**Comment by JanAckermann** [comment]
Note: Chanig full name works -> green message first..
But the request gets fired twice and the next message is -> can't change full name

**Comment by JanAckermann** [comment]
With 'allow_user_to_change_display_name' => false the error message for full name is also bad 

![image](https://user-images.githubusercontent.com/26169327/134771562-98b619e6-d241-4cd6-87b0-41310f00f88a.png)
