### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/core#35102]
On the admin setting page "sharing" we have some missing translation:

Create  Change  Delete  Share are only in english but not in german.
Also some lines below: Group Sharing Blacklist.

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
10.1.1
**Updated from an older ownCloud or fresh install:**
older
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

**Comment by phil-davis** [comment]
Currently the missing translation that I see on the admin sharing settings page are:
"Set default expiration date for federated shares" - there are translations for PT and SQ.
"Automatically accept federated shares from trusted servers"  - there are translations for PT and SQ.

Someone needs to add these translations (and any others that are waiting to be translated) in Transifex. If nobody does the translations in Transifex then they can never come across to ownCloud.
