### ISSUE TITLE
An execption occurres while executing UPDATE .... MySQL server has gone away

### ISSUE THREAD

**Issue by patingg** [owncloud/core#35112]
![owncloud_error](https://user-images.githubusercontent.com/50079574/56866362-85ca7080-69d8-11e9-9ec1-a08d096fd9f6.JPG)

**Comment by ho4ho** [comment]
Unlikely bug for bugtracker, more config problem question to https://central.owncloud.org/

https://doc.owncloud.com/server/10.0/admin_manual/configuration/database/linux_database_configuration.html#how-to-workaround-general-error-2006-mysql-server-has-gone-away

**Comment by VicDeo** [comment]
Closing as not related to the owncloud itself. 
'MySQL server has gone away' means that mysql server closed the connection with no response to the php part. 

The most popular reason for this is a low value for  `max_allowed_packed` MySQL config parameter.
But it could be related to almost anything e.g. to the mysql server segfault.

General advice is to check MySQL server logs - the reason of disconnection should be there.
