### ISSUE TITLE
ownCloud migration (Ubuntu 18.04, MySQL 5.7)

### ISSUE THREAD

**Issue by llorban** [owncloud/core#35125]
Just attempting to complete migrating an ownCloud instance. Running occ upgrade fails with the following message: 

```
Doctrine\DBAL\Schema\SchemaException: The table with name 'owncloud.oc_persistent_locks' already exists.
Update failed
```

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache2

**Database:** MySQL 5.7

**PHP version:** 7.2

**ownCloud version:** 10.0.0.4 on the old server, 10.1.0 on the new one

**Updated from an older ownCloud or fresh install:** Fresh install on new server

**Where did you install ownCloud from:** owncloud.org

**Signing status (ownCloud 9.0 and above):**

Cannot log into ownCloud because it requires running the manual occ upgrade

**The content of config/config.php:**

```
{
    "system": {
        "maintenance": false,
        "instanceid": "och1qm5vkscl",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "externalcortex.com"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data\/",
        "overwrite.cli.url": "http:\/\/35.203.118.88",
        "dbtype": "mysql",
        "version": "10.1.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "loglevel": 2
    }
}

```

**List of activated apps:**

```
apps folder deleted
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari

**Operating system:** macOS Mojave

**Comment by ho4ho** [comment]
Duplicate https://github.com/owncloud/core/issues/34598 + https://github.com/owncloud/core/issues/33963
