### ISSUE TITLE
Cannot change public link share permission to Download/View/Upload

### ISSUE THREAD

**Issue by dpakach** [owncloud/core#35155]
### Steps to reproduce
1. Create a public link share with permission `Download /View/Edit`
2. Change the share permission to `Download/View/Upload`

### Expected behaviour
- The new permission of the public link share should be `Download/View/Upload`

### Actual behaviour
- The permission of the public link share is still `Download/View/Edit`

**Comment by individual-it** [comment]
CC @sharidas

**Comment by sharidas** [comment]
Created PR: https://github.com/owncloud/core/pull/35157

**Comment by PVince81** [comment]
fix was merged.
still need https://github.com/owncloud/core/pull/35166
