### ISSUE TITLE
Using S3 as external storage does not work

### ISSUE THREAD

**Issue by ljanyst** [owncloud/core#35150]
### Steps to reproduce
1. Go to Settings > Storage
2. Add an S3 bucket and map it to a directory in the directory tree
3. The red square appears indicating that the whole thing was a fiasco

### Expected behaviour
The S3 bucket should be added to the file tree of the user.

### Actual behaviour
```
Exception: {"Exception":"Error","Message":"Undefined class constant 'COMMAND_PARAMS'","Code":0,
[cut useless bunch of backslashes]
"File":"/var/www/owncloud/apps/files_external/lib/Lib/Storage/AmazonS3.php","Line":574}"}
```
Apparently AWS has changed some APIs recently related to the path style lookups and the SDK you use seems to be unable to cope anymore. I should note that using a different bucket as a primary object store works just fine. However, it would appear that `files_primary_s3` and `files_external` import different versions of the S3 SDK.

### Server configuration
**Operating system**: Ubuntu 18.03
**Web server:** Apache
**Database:** MySQL
**PHP version:** 7.2
**ownCloud version:** (see ownCloud admin page)
**Updated from an older ownCloud or fresh install:** Fresh install
**Where did you install ownCloud from:** Downloaded tarball from the website
**Signing status (ownCloud 9.0 and above):**

**Comment by PVince81** [comment]
the current goal is to do a first release of the files_external_s3 app and remove it from core.
the app files_external_s3 will have an updated AWS SDK.

see https://github.com/owncloud/files_external_s3/issues/158

**Comment by ljanyst** [comment]
Thank you for the update! It looks like it may take some time though and, in the mean time, things are broken. Would it be possible to have a quick fix for the current setup?

**Comment by PVince81** [comment]
quick fix would be to manually update the S3 library in the files_external folder.
would likely not be as quick as it still requires some QA to make sure it works

you might be better off using the files_external_s3 app from git as it was already reported working... we're only putting the finishing touches and doing QA

**Comment by ljanyst** [comment]
I will give it a try. Thanks!

**Comment by PVince81** [comment]
if you find issues with it please report in that repository, thanks!
