### ISSUE TITLE
Bug in renaming files/folders in shared with pages 

### ISSUE THREAD

**Issue by bhawanaprasain** [owncloud/core#35174]
### Steps to reproduce
1. create folder `nf1/newfolder`  `test`
2. share folder `nf1/newfolder` `test` by public link or with any users 
3.  browse to `shared  with others`/`shared by link` page based on the type of share 
4. try renaming `test` to `newfolder` 

### Expected behaviour
Folder `test` should be renamed  to `newfolder` as `test` and `newfolder` are in different path

### Actual behaviour
`test` folder cannot be renamed as `newfolder`

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:**Mysql

**PHP version:**7.2

**ownCloud version:** (see ownCloud admin page) 11.0.0 prealpha (git)

**Updated from an older ownCloud or fresh install:**Fresh

**Where did you install ownCloud from:**git 

### Client configuration
**Browser:**  Version 73.0.3683.103 (Official Build) (64-bit)

**Operating system:**Ubuntu 18.04

**Comment by bhawanaprasain** [comment]
![sr](https://user-images.githubusercontent.com/40640347/57355438-c4f18200-718d-11e9-956f-a7df7340c837.gif)

**Comment by phil-davis** [comment]
Good find! 
There are probably a few of these sort of bugs on the pages that display a list of files together that come from different source folders.

**Comment by individual-it** [comment]
@bhawanaprasain please make acceptance tests that demonstrate the bug, similar to what you have done in #35185

**Comment by JanAckermann** [comment]
Related to #20722
