### ISSUE TITLE
default expiration date for public sharing links

### ISSUE THREAD

**Issue by janholubek** [owncloud/core#35187]
### Steps to reproduce
1. set default expiration date for public sharing links to 14 days, but not enforced
2. create public sharing link and remove preset expiration date

### Expected behaviour
public sharing link doesn't expire automatically

### Actual behaviour
public sharing link expired after 14 days
settings (of other publis links) show that the expiration date is set again after initial creation, removing the expiration date again and saving works

### Server configuration
**Operating system**: CentOS Linux release 7.6.1810 (Core)
**Web server**: Apache (on Managed Cloud Service)
**Database**: MySQL
**PHP version**: 7.1.28
**ownCloud version**: 10.0.10.4
**Updated from an older ownCloud or fresh install**: updated
**Where did you install ownCloud from**: not sure, was before my time here
**Signing status (ownCloud 9.0 and above)**:
```
No errors have been found.
```
**ownCloud config report:**
https://gist.github.com/janholubek/e694aa200e2cc47f447a50dcf0479387

**Are you using external storage, if yes which one:** no
**Are you using encryption:** yes, Master Key
**Are you using an external user-backend, if yes which one:** Webdav

### Client configuration
**Browser:** Chrome
**Operating system:** Windows 10 Pro

#### Web server error log
hosted external, will ask for it, if necessary

#### ownCloud log (data/owncloud.log)
some errors with decryption and ONLYOFFICE, see #35142

**Comment by karakayasemi** [comment]
I believe this problem fixed with https://github.com/owncloud/core/pull/34960 . It will be on next release. If you want to try, you can use RC2 tarball: https://central.owncloud.org/t/owncloud-server-10-2-0rc2-is-available/19892 or git master branch.

**Comment by janholubek** [comment]
great, thank you!
