### ISSUE TITLE
.deb package of 10.2.0RC2 does not create a apps-external folder

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#35189]
installation of .deb package `dpkg -i ...` creats `/var/www/owncloud` but not `/var/www/owncloud/apps-external` 
when starting the web-installer it says `Can't create or write into the apps-external directory /var/www/owncloud/apps-external`
packages themselves are already shipping an empty "data" folder. so we need to do the same for the "apps-external"

**Comment by crrodriguez** [comment]
Allright, A new set of rc2 packages are building now.

**Comment by crrodriguez** [comment]
New set published.

**Comment by PVince81** [comment]
@crrodriguez please confirm that setups that already have the folder will not get affected (no deletion)

**Comment by PVince81** [comment]
I've tested the new RC2 on openSUSE Leap 15.0 on my personal server on which "apps-external" is a symlink. The upgrade of the "owncloud-files" package did not touch the folder in question.

Does Debian / apt behave the same ?

**Comment by individual-it** [comment]
tested it on Ubuntu:
1. for fresh installation the `apps-external` folder is created
2. when updating and  `apps-external`  does not exist it will be created
3. when updating and  `apps-external`  does exist it will not be touched
