### ISSUE TITLE
Reorganise createTags.feature

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#35182]
` tests/acceptance/features/webUITags/createTags.feature` has scenarios that test creating, removing ("untagging" a file but leaving the tag still existing in the system) and deleting tags.

- [x] Split it into 3 different feature files. (or more if there are other distinct things being tested) #35184
- [x] Add more combinations of scenarios (there are not many tested) #35241

**Comment by HariBhandari07** [comment]
@phil-davis I have made a pull request #35184 addressing this issue. I think I will add more tests regarding creating, removing and deleting tags after this pr is merged.

**Comment by individual-it** [comment]
@phil-davis  @HariBhandari07 close this issue?

**Comment by HariBhandari07** [comment]
@phil-davis I have already added some extra scenarios in #35241 for tag removal, deletion and renaming. I think it's time to close this issue.
