### ISSUE TITLE
add acceptance tests for notify-by-email feature in acceptance tests

### ISSUE THREAD

**Issue by dpakach** [owncloud/core#35195]
### Add acceptance test for notify by email feature in the webUI.

When the users are allowed to send notification for the shares, they can click the notify-by-share button in the sharing dialog in the UI to send email notification to the share notifications. Currently there is no test for this feature. 
Add following tests for this feature.
- [x] webUI #35215

**Comment by paurakhsharma** [comment]
Added tests in #35215
