### ISSUE TITLE
Changes required for public link Download View Upload as it does not work as expected

### ISSUE THREAD

**Issue by sharidas** [owncloud/core#35192]
After discussion with PM here is the summary:
- Remove the Update permission for the `Download / View / Upload` link.
- User should be able to create file or folder with the link.
- User cannot update or modify the file with the same name. Say for example if there is a file `a.txt` in the public link with permission `Download / View / Upload` link, then user cannot upload file with same name.
- User cannot create folder with same name in the public link. That is if there is a folder with name `foo` in the public link. Then user cannot create another folder with the same name `foo`.
- When the user clicks the 3 dots in the public link only download option should be available.
- There should not be any delete reference in the UI. That is from the public link user should not be able to delete a file or folder.
- There should not be any reference to rename in UI ( in the current UI rename option is available ).

@pmaier1

**Comment by pmaier1** [comment]
Yes, that's basically it :+1: 

Adding to this: 
The "Download / View / Edit" permission gives you full access => You can execute all available operations with the link. Also described here https://github.com/owncloud/docs/pull/967#discussion_r282404917.

**Comment by individual-it** [comment]
the webdav API should work the same
