### ISSUE TITLE
Secure View download error page not displaying properly

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#35208]
### Steps

1. Add simulated error https://github.com/owncloud/core/pull/33992/files#r252450718
1. Download "welcome.txt"

or

1. Share a document in secure view mode with forbidden download
1. As recipient, try and download it

### Expected result
Proper error page.

### Actual result
Incomplete HTML code or XML response containing the exception.

### Version
ownCloud 10.2.0 RC3

@pmaier1 @mrow4a

**Comment by DeepDiver1975** [comment]
@PVince81 debug set to true in config.php?

**Comment by PVince81** [comment]
cannot reproduce locally.

this was reported on a demo server, will need to check its setup.
