### ISSUE TITLE
browsing directly to details does not work for files far down the list

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#35200]
### Steps to reproduce
1. have a long list of file e.g. from https://github.com/owncloud/testing/tree/master/data/webUISkeleton
2. try to navigate directly to the sharing tab of last file e.g. `localhost/owncloud-core/index.php/apps/files/?dir=/&scrollto=zzzz-must-be-last-file-in-folder.txt&details=shareTabView`

### Expected behaviour
Sharing tab of the file should open

### Actual behaviour
![image](https://user-images.githubusercontent.com/2425577/57512892-ac6b9e00-732c-11e9-8291-af7e5a0ddbcc.png)

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache2
**Database:**
SQLite
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
11.0.0
10.1.1
**Updated from an older ownCloud or fresh install:**
fresh

seems not to be a regression
bayernbox has a similar issue https://github.com/owncloud/enterprise/issues/3310#issuecomment-490865700

CC @patrickjahns

**Comment by PVince81** [comment]
so it does scroll to the item but doesn't open the panel, right ?

the logic needs to scroll down and wait for rendering of all pages, and only when the item is rendered it can open the sidebar. maybe it's opening too early.

need to be scheduled for fixing.

**Comment by sharidas** [comment]
PRs created
- [x] master branch https://github.com/owncloud/core/pull/35283
- [x] stable10 branch https://github.com/owncloud/core/pull/35306
