### ISSUE TITLE
Add acceptance tests for new changes/fixes in v10.2.0

### ISSUE THREAD

**Issue by skshetry** [owncloud/core#35207]
Things that could have been tested by acceptance tests

| Change | PR | issue found while testing | estimated effort to write tests | comment | 
|-----------|-----|-----|----|-- |
| Adding background:queue commands: status and delete | #34783 | | 0.25md| #35229 |
| Added new permissions option for public link | #34983 | #35056 & #35057 | added by fix |  tests exists |
| Support for automatically accepting incoming federated shares from trusted servers | #34206 | #35067 | 0.25md | tests exists |
| User option to opt-out autocomplete in share dialog | #34942 | | 1md | done in #35153 |
| Extend repair command to be able to list repair steps and run them individually | #34499 | | 0.25md (just checking the output) | #35257 Some tests require maintenance mode to be set on | 
|  Command for first run wizard to reset for all users | firstrunwizard/#83 | | 0.25md | done in https://github.com/owncloud/firstrunwizard/pull/104 |
| Inform admin about the need to login again after changing the master encryption key | #34596 |  | 0.25md |  https://github.com/owncloud/encryption/pull/124 |
| By default the "apps-external" directory is included in config.php during installation | #34656 #34902 | #35031 | 1md |#31347|
| Allow admins to enable medial search on group and user | #34779 | #35066 (known issue with LDAP) | 0.5md | first set of tests done in  #35133 <br> more variations needed e.g. disabling `groups.enable_medial_search` |
| Add occ command to poll incoming federated shares for updates | #34933 #34959 | | 1md | https://github.com/owncloud/core/pull/35314 |
| Log exception when background job class not found | #34723  || ? |
| Fix public link share default expiration behavior | #34971 | | 1md | #35175 |
| Don't expose hashed password in OCS api | #34691 | | 0.25md |  #35233 | 
| Fix chunking infinite loop in some environment related issues | #34558 | | ?  | might be complicated to corrupt the chunk |
| Properly hide share fields in "Shared with You" section when permissions are restricted | #34473 | | 1md | The specific issue has been tested |
| Fix cancel upload and hide 'uploading' message for files_drop shared folders | #34097 | | ? | hard because need to get the timing correct |
| Tidy up code for notification by email | #34786 |#35089 | ? | #35215 |
| Directly honour robots.txt if htaccess.RewriteBase is set | #34949 | | 0.25md | #35284  |

_Originally posted by @individual-it in https://github.com/owncloud/core/issues/35020#issuecomment-486058984_

**Comment by individual-it** [comment]
@skshetry @dpakach @HariBhandari07 @paurakhsharma your have added a couple of tests in the last week please mark things that are already tested here

**Comment by individual-it** [comment]
I think we have done whatever is possible and sensible here, closing
