### ISSUE TITLE
Error thrown when running occ background:queue:status

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/core#35222]
# Description
I am getting
`A cell must be a TableCell, a scalar or an object implementing __toString, array given.`
error when running occ command `background:queue:status`

This is produced if there is job in the background queue whose arguments is an array
Some of the job class which has an array as an argument are  `OCA\Federation\BackgroundJob\RequestSharedSecret` and `OCA\FederatedFileSharing\BackgroundJob\RetryJob`

# Steps to reproduce:
1) Setup two servers eg: `core` and `core-fed`
2) Add `'sharing.federation.allowHttpFallback' => false,` in config.php both servers
3) Login as admin in server `core` and add `http://localhost/core-fed` on Federation Trusted Server
Step 3 creates a background job with class `OCA\Federation\BackgroundJob\RequestSharedSecret`
4) On server `core` run occ command `background:queue:status`

# Expected Behaviour
You get the table with the information of jobs in a background queue

# Actual Job
You get error `A cell must be a TableCell, a scalar or an object implementing __toString, array given.`

This can be reproduced in latest master, 10.2 RC 2, 10.2 RC 3

cc @individual-it @phil-davis @PVince81 @micbar @DeepDiver1975

**Comment by paurakhsharma** [comment]
Related PR #34783

**Comment by individual-it** [comment]
please test with `background:queue:execute` and `background:queue:delete`

**Comment by paurakhsharma** [comment]
> please test with `background:queue:execute` and `background:queue:delete`

I was able to run `background:queue:execute` and `background:queue:delete` on such Jobs

**Comment by patrickjahns** [comment]
Fix in https://github.com/owncloud/core/pull/35224
