### ISSUE TITLE
Public link permissions in the WebUI are confusing [10.2.0 RC3]

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#35223]
With 10.2.0 users can choose from 4 permission settings for public links:

![grafik](https://user-images.githubusercontent.com/1108546/57695664-2367a600-764f-11e9-9996-fbbe07739c5c.png)

"Download/View/Edit" is new in 10.2.0

all this is only available when sharing a folder.

On a file, there seems to be a choice of two settings, but in reality there is none:
![grafik](https://user-images.githubusercontent.com/1108546/57695628-0c28b880-764f-11e9-91a5-2cfc11190e3d.png)
But the second one cannot be used. It causes an error message as shown above.

1) Please consider removing choice, if it cannot be used.
2) Please change the text of the error message. Upload and Edit are two different things. These terms should not be confused. The chosen setting was "Download/View/Edit", the error message speaks about "Upload". It should say "Public Edit is not possible" instead. 
3) Why is editing (eg. with the text-editor app) not available for files?

**Comment by jnweiger** [comment]
In 10.1.1 the public share dialog for files only had one setting:

![grafik](https://user-images.githubusercontent.com/1108546/57697978-c242d100-7654-11e9-834e-d7e8952cef15.png)

It seem the broken choice is new in 10.2.0

**Comment by sharidas** [comment]
Created PR: 
- master branch https://github.com/owncloud/core/pull/35226
