### ISSUE TITLE
Special Characters not allowed?

### ISSUE THREAD

**Issue by Harryjholmes** [owncloud/core#35227]
Hi,
I am trying to name a file in owncloud with a tilde (~) in it. Every time I do it changes to an underscore or dash. I was just wondering if there was anyway to get pass this>
Thanks

**Comment by phil-davis** [comment]
I tried renaming in the webUI with Chrome. It works fine for me. Please give more detail (fill in the issue template) - ownCloud version, where are you doing the name/rename? In the webUI? On a client system? Give a specific example of steps to reproduce.

**Comment by Harryjholmes** [comment]
Version: 10.0.10(stable)
I'm renaming a PDF file in web UI inside of a folder. When using a ~ in the file name it changes instantly to a dash or underscore. I'm running owncloud on an ubuntu SFF PC.
For example:
Pdf file called: 010000-13.5.2019.pdf
Changed to : 010000~13.5.2019.pdf
Then instantaneously back to either: 010000-13.5.2019.pdf or 010000_13.5.2019.pdf
Thanks in Advance

**Comment by Harryjholmes** [comment]
It is also saved in the database as an underscore rather than a tilde. Maybe a file character restriction?

**Comment by davitol** [comment]
Works for me too. @Harryjholmes is the file hosted in an external storage? Can you try to rename the file directly in the storage and check if you can have the ~ in the filesname there?

**Comment by Harryjholmes** [comment]
Yes same problem if I rename in storage. It isn't hosted externally. @davitol

**Comment by davitol** [comment]
Then it is not an ownCloud issue. It happens due to the storage

**Comment by Harryjholmes** [comment]
I'm only using Ubuntu Linux to run owncloud so I don't see what the problem is?

**Comment by Harryjholmes** [comment]
I apologise but I was wrong. I can rename in my file system and the tilde stays just not from own cloud Web UI. @davitol

**Comment by Harryjholmes** [comment]
It physically doesn't let me type one in the Web UI

**Comment by Harryjholmes** [comment]
It doesn't work on the demo either if you check.

**Comment by Harryjholmes** [comment]
It is perhaps a limitation with google chrome as it seems OK with Firefox.

**Comment by phil-davis** [comment]
I tried with Google Chrome 74.0.3729.169 on Ubuntu 18.04 an renaming with a `~` works.
