### ISSUE TITLE
User email addresses can be duplicate

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/core#35236]
Server version: 10.1.1.

Steps to recreate:

1) Create a user with an email address in the web ui
2) Create another user with the same email address

Actual result: Users can have duplicate addresses. This stops users from being able to use email address to login.
Expected result: Users cannot have duplicate email addresses.

**Comment by ho4ho** [comment]
Duplicate https://github.com/owncloud/core/issues/31171 ?

**Comment by HanaGemela** [comment]
> #31171

Yeah, seems similar. The difference is that in the previous issue it was agreed duplicate email addresses are a valid scenario. Which is OK with me. The problem is that this email address then can't be used to login. In this case there should be some warning when creating such user stating that user will not be able to log in with this email and also the user should be informed that only their username will be valid when trying to log in. We can label this es enhancement if it is agreed that duplicate email addresses are OK
