### ISSUE TITLE
update 10.01 to 10.1.1

### ISSUE THREAD

**Issue by Adylitto** [owncloud/core#35234]
cannot update due to app installed but not accessible for deactivation

**Comment by Adylitto** [comment]
as in parameters and marketplace unaccessible without update!!!

**Comment by Adylitto** [comment]
OC\RepairException: Upgrade is not possible
Préparation de la mise à jour
Réglage du niveau de journalisation à "déboguage"
Mode de maintenance activé
Avertissement de réparation :You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Avertissement de réparation :Please install or update the following apps manually or disable them with: occ app:disable files_clipboard occ app:disable files_reader
Avertissement de réparation :For manually updating, see https://doc.owncloud.org/server/10.1/go.php?to=admin-marketplace-apps
OC\RepairException: Upgrade is not possible

**Comment by PVince81** [comment]
did you try following the instructions, run the following:
- occ app:disable files_clipboard
- occ app:disable files_reader

then `occ upgrade` again

**Comment by Adylitto** [comment]
how do you do that ???

**Comment by ho4ho** [comment]
https://doc.owncloud.com/server/10.1/admin_manual/configuration/server/occ_command.html

**Comment by Adylitto** [comment]
Thank you but I don’t know how to input command yet

I will find out
