### ISSUE TITLE
Error deleting when unsharing a file

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/core#35237]
Similar to #25593

macOS 10.14.4
Client 2.6.0-daily20190513 (build 11776)
File was shared from server: 10.2.0. RC3
File was shared to server: 10.1.1.

Steps to recreate:

1. Create a public link of a file in the context menu on your file system
2. Open the link in an incognito window
3. Add the file to your ownCloud in the top right corner (different user on different server)
4. Unshare the file from your ownCloud

Expected result: No error
Actual result: Error

![image](https://user-images.githubusercontent.com/49001702/57775844-44e39300-771e-11e9-93dd-4fe82e7216e0.png)

**Comment by PVince81** [comment]
could be a regression from an earlier version. as far as I remember this used to work.

**Comment by VicDeo** [comment]
can't reproduce, could it be a connectivity issue?

**Comment by VicDeo** [comment]
@HanaGemela is my test sequence the same with yours? https://cloud.owncloud.com/index.php/s/YA2DO6inwzCk8Ne

**Comment by HanaGemela** [comment]
@VicDeo You are using newer version of the server so it seems it has been fixed already

**Comment by VicDeo** [comment]
@micbar not confirmed for  10.2.0 release. Close?

**Comment by micbar** [comment]
Close
