### ISSUE TITLE
Hashing is not there for Password

### ISSUE THREAD

**Issue by GruLab** [owncloud/core#35277]
### Steps to reproduce
1. Open Firefox >> Set Proxy as Manual >> IP: 127.0.0.1 & Port: 8080
2. Open Burp-suite  >> Set the ownCloud IP in scope >> Proxy intercept is on by default
3. Using valid credentials login into ownCloud instance >> Open HTTP history in Burp-suite

### Expected behaviour
User Password should be hashed

### Actual behaviour
User Password is in plain text

### Server configuration
**Operating system**: CentOS 7 (64 bit)

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.1.28

**ownCloud version:** (see ownCloud admin page) 10.1.1

**Updated from an older ownCloud or fresh install:** Fresh

**Where did you install ownCloud from:** Bitnami Stack

**Signing status (ownCloud 9.0 and above):** Valid

![burp](https://user-images.githubusercontent.com/8300079/58067814-6fb16980-7bac-11e9-8188-fd4245184fc3.jpg)

**Comment by GruLab** [comment]
User Password should be salted hash

**Comment by cortho** [comment]
Your screenshot clearly says you are posting your password via https. Basically any web service is doing the same. Passwords are not hashed client side.

Recommendation: close

**Comment by davitol** [comment]
> Your screenshot clearly says you are posting your password via https. Basically any web service is doing the same. Passwords are not hashed client side.

We can close the ticket. Thanks you two for posting and for answering
