### ISSUE TITLE
Issue in Session Handling

### ISSUE THREAD

**Issue by DevSec-Ops** [owncloud/core#35272]
### Steps to reproduce
1. Login into the ownCloud instance
2. Open any file >> Logout the session
3. Click the Back button repeatedly

### Expected behaviour
Login Page should be displayed

### Actual behaviour
Previously used login instance is being shown

### Server configuration
**Operating system**: CentOS 7 (64 bit)

**Web server:**: Apache

**Database:**: MySQL

**PHP version:**: 7.1.28

**ownCloud version:** (see ownCloud admin page) 10.1.1

**Updated from an older ownCloud or fresh install:** Fresh

**Where did you install ownCloud from:** Bitnami Stack

**Signing status (ownCloud 9.0 and above):** Valid

![20190520_162658](https://user-images.githubusercontent.com/8300079/58020014-92983b00-7b24-11e9-99e3-c02c4b73308a.gif)

**Comment by cortho** [comment]
Tested this out of curiosity on Ubuntu 18.04.2 with Firefox 66.04 and Chromium 73.0.3683.86 and on Windows 10 with Edge 38.14393.0.0, Firefox 66.0.5 and Chrome 74.0.3729.157.

For me, this did not occur with any of these browsers. 
Tested with the above example (files_pdfviewer enabled)
Not sure, if this is real.

@GruLab When filing a client issue, why didn't you at least fill in the Client template.

**Comment by GruLab** [comment]
@cortho Forgot to add actually

### Client configuration
**Browser:** Firefox Quantum 66.0.5 (64-bit) [**Open it in Private Mode**]

**Operating system:** Windows 10 Pro (64-bit)

![20190522_111024](https://user-images.githubusercontent.com/8300079/58150218-92fb1800-7c83-11e9-824a-5820775b65cb.gif)
