### ISSUE TITLE
issue in 10.2.0 Upgrade

### ISSUE THREAD

**Issue by GaneshKandu** [owncloud/core#35282]
Hi,

I have upgraded old install of Owncloud from 10.1.1 to 10.2.0 and installed fresh Owncloud  10.2.0

1. I am getting integrity check error after upgrade in ```apps``` folder

2. seems new version of ```Owncloud``` have 'apps_paths' configured in config.php file but after upgrade from old Owncloud only ```version``` is get updated  in config.php there is no ```apps_paths``` configured after upgrade

### Server configuration
**Operating system**: Linux localhost 2.6.32-358.0.1.el6.x86_64 1 SMP Wed Feb 27 06:06:45 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

**Web server:** Apache 2.4

**Database:** Mysql 5.5.60 

**PHP version:** 7.0.31

**ownCloud version:** 10.2.0

**Updated from an older ownCloud or fresh install:** Both

**Where did you install ownCloud from:** [https://owncloud.org/download/](https://owncloud.org/download/)

**Integrity check**
[https://gist.github.com/GaneshKandu/7777ead7bed90caf1734e708c8e17352](https://gist.github.com/GaneshKandu/7777ead7bed90caf1734e708c8e17352)

**The content of config/config.php after upgrade to 10.2.0:**

```php
<?php
$CONFIG = array (
  'instanceid' => '[[instanceid]]',
  'passwordsalt' => '[[passwordsalt]]',
  'secret' => '[[secret]]',
  'trusted_domains' => 
  array (
    0 => '{{domains}}',
  ),
  'datadirectory' => '[[datadirectory]]',
  'overwrite.cli.url' => '[[url]]',
  'dbtype' => 'mysql',
  'version' => '10.2.0.5',
  'dbname' => '[[dbname]]',
  'dbhost' => '[[dbhost]]',
  'dbtableprefix' => 'oc_',
  'dbuser' => '[[dbuser]]',
  'dbpassword' => '[[dbpassword]]',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
);

```

**Comment by davitol** [comment]
@GaneshKandu Tested and it seems to WFM. I have made an upgrade an 'apps_paths' is still there in 10.2.0.
Looking into your Integrity Check info, it is strange for me why it appears things like 'files_sharing' due to that apps are included in core version.

**Comment by VicDeo** [comment]
`lib/API/OCSShareWrapper.php` and  `lib/API/Share20OCS.php` existed in 10.1.1 but were removed from files_sharing app in 10.2.0.

@GaneshKandu did you remove existing OC files before copying or just copied a new version on top of  old one?

**Comment by GaneshKandu** [comment]
>  did you remove existing OC files before copying or just copied a new version on top of old one?
just copied a new version on top of old one

**Comment by VicDeo** [comment]
@GaneshKandu 
copying on top is discouraged
https://doc.owncloud.com/server/admin_manual/maintenance/manual_upgrade.html#extract-the-new-source-2

>Rename your current ownCloud directory, for example, from owncloud to owncloud-old-version-number. Extract the unpacked ownCloud server directory and its contents to the location of your original ownCloud installation.

I've checked: all these files had been shipped with 10.1 but  they were removed in 10.2 probably due to release script unification across all repos. Feel free to delete them.

**Comment by GaneshKandu** [comment]
> Feel free to delete them.

all extra file were deleted by compairing only 'config', 'data', 'apps-external' folder left as it is

isn't a integrity check problem

install 10.1 and add some apps into this then upgrade to 10.2
you will get same issue

**Comment by GaneshKandu** [comment]
because new version is checking integrity check in apps folder also what if i have added same extra apps

should i move this extra 'apps' to 'apps-external' folder and delete apps folder before upgrade ?

**Comment by VicDeo** [comment]
I checked your list https://gist.github.com/GaneshKandu/7777ead7bed90caf1734e708c8e17352
all these files exist in 10.1 package but don't exist in 10.2. Which means that they should be deleted manually during the manual upgrade.

Integrity check just reported that you have extra files that are not known to 10.2. It looks correct to me.

**Comment by VicDeo** [comment]
> what if i have added same extra apps

any apps that are not part of distribution package have their own signature.json and their integrity validated against it

**Comment by VicDeo** [comment]
> should i move this extra 'apps' to 'apps-external' folder and delete apps folder before upgrade ?

 not exactly. According to the docs you need to 
0. create DB and data backup
1. extract new version, 
2. copy **config/*.php** from your current instance into the new version **config** dir
3. in case **data** dir is under owncloud root dir, copy it to **data** dir of the new version, skip otherwise
4. Disable all apps that you don't need any more
5. copy all extra apps except from 4.  into the new version
6. rename your current instance directory into **owncloud-x.y.z**
7. rename new version into **owncloud**
8. restart webserver and browse to OC page

it's just a short summary from https://doc.owncloud.com/server/admin_manual/maintenance/manual_upgrade.html#extract-the-new-source-2
that explains the process in details

**Comment by VicDeo** [comment]
6 and 7 are needed to recover after unsuccessful upgrade, what you need to do in this case - just
1. restore DB from backup, 
2. rename **owncloud-x.y.z** back into **owncloud** 
3. restart webserver

**Comment by GaneshKandu** [comment]
@VicDeo thanks!  i'll do
