### ISSUE TITLE
10.2: Remove user from a group results in an error

### ISSUE THREAD

**Issue by cortho** [owncloud/core#35289]
### Steps to reproduce
1. In the Users page add any user to any group
2. Remove the group for this user
3. The togglegroups.php AJAX call results with status: error
4. In the JS console you will read response.data is undefined
5. The user count in the group list at the left side is not reduced

### Expected behaviour
No errors, the group list ist correctly updated

### Actual behaviour
The AJAX call results in a status error breaking functionality in users.js when there is no response

### Server configuration
**Operating system**:
Ubuntu 18.04.2 LTS

**Web server:**
apache2-2.4.29-1ubuntu4.6

**Database:**
mariadb-server-10.1 10.1.38-0ubuntu0.18.04.2

**PHP version:**
7.2.17-0ubuntu0.18.04.1

**ownCloud version:** (see ownCloud admin page)
10.2.0.5

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
owncloud.org download page

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 66.0.4

**Operating system:**
Ubuntu 18.04.2 LTS

#### Web server error log
no errors

#### ownCloud log (data/owncloud.log)
no errors

#### Browser log
see attached Screenshot

![Selection_731](https://user-images.githubusercontent.com/28009362/58091152-2ae7fb80-7bc9-11e9-8e77-1ce1582e8441.png)

**Comment by davitol** [comment]
Tested in 10.2 an it is reproducible. Not reproducible in 10.1 so it is a regression

@cortho Refreshing the browser the group count shows the right number of users, does it happen to you too?

**Comment by cortho** [comment]
@davitol Yes, by refreshing the browser the correct count is shown.

I found this issue because one of our apps hooks in this functionality and is expecting a non-erroneous response from the ajax, when there was no error.

**Comment by micbar** [comment]
@pmaier1 Regression found. No breaking anything directly, but need reloading the page.

**Comment by pmaier1** [comment]
Yes, please plan fixing @micbar.

**Comment by micbar** [comment]
Fix in https://github.com/owncloud/user_management/pull/188

**Comment by micbar** [comment]
Introduced in https://github.com/owncloud/enterprise/issues/2598

**Comment by sharidas** [comment]
PR's created against branches:
- [x] master branch https://github.com/owncloud/user_management/pull/188
- [x] core release-10.2.1 branch https://github.com/owncloud/core/pull/35570
