### ISSUE TITLE
Tagging issues with GitHub API

### ISSUE THREAD

**Issue by Jekotia** [owncloud/core#35307]
Refer to https://api.github.com/repos/owncloud/core/tags and look at the first tag. That first item consistently appears as the latest tag, but is a very old release (January 2017). This makes it impossible for a conventional API scraper to detect ownCloud Core updates without implementing workarounds specific to this abnormality.

Our API scraper has been monitoring ownCloud/core for about a year and has yet to notify us of any releases, so I suspect that it's an issue with the tag (perhaps that extra leading v in the name field?).

I realise this is likely more of a GitHub support type of thing, but I didn't know how else this issue should be raised, given that it would be kind of surprising for them to fix YOUR repository at MY entirely unaffiliated behest.

**Comment by phil-davis** [comment]
@PVince81 @micbar 
There is a tag called `vv9.1.4RC1`
I doubt that anybody cares about an old RC1 tag. If so, then the tag could be deleted.
Otherwise we could make a new tag `v9.1.4RC1` on the same commit and delete the one with the double `v`
