### ISSUE TITLE
Installing ownCloud 10.2 apps-external directory

### ISSUE THREAD

**Issue by cs35-owncloud** [owncloud/core#35304]
Hello,

since ownCloud 10.2's release there is an automatic creation of a directory for external apps when installing which is a good thing to avoid bugs with upgrades and mostly keep it clean (as described in [other notable changes](https://doc.owncloud.org/server/10.0/admin_manual/release_notes.html#changes-in-10-2-0)).

I install ownCloud by copying first a config.php of my own that sets a few features SMTP, trashbin, MySQL driver options (SSL) ... and also several apps directories:

```
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/owncloud/apps_orig',
      'url' => '/apps_orig',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    2 =>
    array (
      'path' => '/var/owncloud/theme',
      'url' => '/theme',
      'writable' => false,
    ),
  ),
```
I set to true or false the **writable** flag with some scripts when I need to install apps but it doesn't matter to my problem.

So once I copy that config.php I use occ to install ownCloud **occ maintenance:install ...**

The problem occurs at this moment because occ creates the directory **apps-external** and doesn't add it to the config.php. In this case, since I defined already my directories it shouldn't create at all the **apps-external** directory or should add it to the config.php to make sense. I guess it's hard coded but I suggest to read first the **apps_paths** to check if the user already set its own directories for apps.

Is it possible ?

Thanks.

**Comment by VicDeo** [comment]
@cs35-owncloud valid point, as for me `maintenance:install` should respect pre-filled app directories and do not  create `apps-external` if it isn't used.

>  I guess it's hard coded
true, in **lib/private/Setup.php**

@micbar please triage

**Comment by cs35-owncloud** [comment]
Hello @VicDeo 

Thanks for your concern and your answer about this problem.
By the way even if you create the directory for apps-external, but won't use it, ownCloud tries to write in it (or maybe only checks with is_writable or whatever) so it must be writable else it fails. So I made a hotfix for my production servers using a 1MB tmpfs mount because I run my ownClouds mainly read only.
I can't wait for a correct fix to unpatch my dirty one :)
Thanks again.

**Comment by VicDeo** [comment]
@cs35-owncloud according to the config below your use case is too specific.
```
 'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/owncloud/apps_orig',
      'url' => '/apps_orig',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    2 =>
    array (
      'path' => '/var/owncloud/theme',
      'url' => '/theme',
      'writable' => false,
    ),
  ),
```
It looks to me that **apps_orig** in your config holds default OC apps.
But we always assume that **apps** directory exists as it's a part of the distribution.  And this behavior won't change.

**Comment by cs35-owncloud** [comment]
Hello @VicDeo 

thanks for your answer.

> It looks to me that apps_orig in your config holds default OC apps.

Indeed it holds the default OC apps.

I guess I have a very specific configuration I'll try to explain it though.

* **/var/owncloud/apps_orig** is a read only mount of an ISO that would be share accross several ownClouds. The goal is to update only one ISO of apps for many instances. It can't be writable at any time.

* **/var/owncloud/apps** is a simple apps directory for each ownCloud instances shipping their own apps. I have an occ wrapper that set the writable to true when I want and install the specific apps if allowed.

* **/var/owncloud/theme** is a simple apps directory for each ownCloud instances shipping only themes. It works just like **/var/owncloud/apps** but only deals with the themes we have.

> But we always assume that **apps** directory exists as it's a part of the distribution. And this behavior won't change.

Alright, maybe I misunderstood but I do have an **apps** directory; even the **url** part is fine. Actually that configuration worked fine in ownCloud 10.1. Maybe it's because I set it to false for the writable ?

According to the documentation it looked fine to me to do this kind of configuration but maybe I misunderstood.

All I can say is that it worked fine as is before and that now, when I install with this configuration it tells me it requires an **apps-external** directory, exactly this name. This directory must also have correct permissions to be writable on the system side (for example **apps_orig** is an RO ISO and cannot be modified at all). Once I do that, then ownCloud installs and never the **apps-external** gets used.

Sorry for this long answer nevertheless I thought I might give more details so maybe we better understand each other.

Anyway the bottom line to me is that the installer shouldn't force to have **apps-external** since I already have an apps directory named **apps**.

Thanks.

**Comment by VicDeo** [comment]
This scheme makes sense for you, but from the dev standpoint `apps` is pre-created and shipped with OC.

**Comment by VicDeo** [comment]
So, the plan is both for web installer and **maintenance:install**:
1. Drop **autoconfig.php** support https://github.com/owncloud/core/issues/31073
2. Search for db type and credentials in **config.php** instead - allow pre-created config.php.
3. the same for the default app directories - they are created except  **apps** that already exists

**Comment by cs35-owncloud** [comment]
@VicDeo You're very right about the integrity check for apps, I hadn't thought of that. Actually I use the apps of ownCloud that I ship in an ISO, so no integrity check problems, but it could happen in the future.

1. It seems like a good idea
2. Same here, moreover having your own config.php would also allow to install an ownCloud with already an SSL configuration for MySQL like that:

```
  'dbdriveroptions' => array(
    PDO::MYSQL_ATTR_SSL_KEY =>'xxx',
    PDO::MYSQL_ATTR_SSL_CERT =>'xxx',
    PDO::MYSQL_ATTR_SSL_CA => 'xxx',
    PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
  ),
```
3./4. seems perfect to me !

Thanks for your help.
