### ISSUE TITLE
Marketplace Offline (https://marketplace.owncloud.com/)

### ISSUE THREAD

**Issue by wefixit-AT** [owncloud/core#35308]
Today I upgraded to ownCloud 10.2, many addons can't be upgraded because https://marketplace.owncloud.com/ is not reachable (offline)

Is there a new URL for the marketplace available?

**Comment by jordanhillis** [comment]
Same issue here. Awaiting a fix for this.

**Comment by tboerger** [comment]
Thanks for the report, our monitoring was ringing, but nobody had been awake to fix it. Issues are resolved.
