### ISSUE TITLE
Delete tooltip remains visible after deleting tags 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/core#35318]
Server: 10.2.0
Browser: Safari 12.1

Steps to recreate:
1) Click on a Share icon against a file in Web UI
2) Add a collaborative tag
3) Edit -> Delete tag

Actual result: Delete tooltip is shown underneath the tag list so it is not visible and after the bin icon has been clicked, tooltip remains shown

Expected result: Tooltip is visible until user clicks the bin icon and then disappears 

![image](https://user-images.githubusercontent.com/49001702/58251058-10e22080-7d63-11e9-82c8-8870d5fdefb1.png)

**Comment by davitol** [comment]
Dupe of https://github.com/owncloud/core/issues/23639 ?

That were moved to General ticket https://github.com/owncloud/core/issues/27578
