### ISSUE TITLE
Acceptance tests for mixed case user and group names

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#35354]
User names (uid) are not case-sensitive - e.g. `user0` `Usser0` and `USER0` are all the same user.

Group names are case-sensitive - e.g. `group1` `Group1` and `GROUP1` are 3 different groups that can have different members and access to different shares.

Add acceptance tests that document and test that behaviour, so that we know if there are regressions.

PR #35342
- [x] adding and deleting... users with the provisioning API
- [x] adding and deleting... users with `occ` commands
- [x] adding and deleting... groups with the provisioning API
- [x] adding and deleting... groups with `occ` commands
- [x] managing group membership with the provisioning API
- [x] managing group membership with `occ` commands

Other:
- [x] adding and deleting... users with the webUI (https://github.com/owncloud/user_management/pull/191)
- [x] adding and deleting... groups with the webUI (PR https://github.com/owncloud/user_management/pull/183)
- [x] managing group membership with the webUI

- [x] sharing with users with the sharing API (PR #35309 )
- [x] sharing with groups with the sharing API (https://github.com/owncloud/core/pull/35647)
- [x] sharing with users with the webUI (https://github.com/owncloud/core/pull/35630)
- [x] sharing with groups with the webUI (https://github.com/owncloud/core/pull/35630)

**Comment by phil-davis** [comment]
@HariBhandari07 see above items that can be tested.
Generally we want to test combinations covering:
- specifying the user name in lower/mixed/upper case works and the action on the same user
- specifying the group name in lower/mixed/upper case takes the action on the appropriate group and other 2 groups are not effected
- specifying some lower/mixed/upper case group name that does not exist results in an appropriate error (404, CLI exit status etc) and none of the actual groups are effected - e.g. `group1` `Group1` and `GROUP1` exist and then we try to share with `grouP1`, which should fail.

**Comment by HariBhandari07** [comment]
@phil-davis I think it's time to close this issue. Have a look.

**Comment by phil-davis** [comment]
Agree - closing
