### ISSUE TITLE
Public Link "edit" menu shows "Remove password" even though there's none

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#35419]
10.2.0 deployed with official docker containers

### Steps to reproduce
1. Create a public link without password on a single file or a folder via WebUI
2. Click on the cog wheel to edit the public link

### Expected behaviour
- Password field is empty like upon creation
- There's no "remove password" button shown

### Actual behaviour
- It looks like a password has been set even though there's none effectively
- A user can click on "remove password" but it has no effect

![Screenshot from 2019-06-04 11-54-28](https://user-images.githubusercontent.com/21193500/58869985-92b93e80-86bf-11e9-8c87-6ed54e8bacc7.png)

Edit:

It also seems with the client that by default password-protection is ticked and I can close the window without actually entering a password.

![Screenshot from 2019-06-04 11-58-28](https://user-images.githubusercontent.com/21193500/58870311-46223300-86c0-11e9-89f0-4474c6ce9a70.png)

**Comment by davitol** [comment]
Remove password button is not shown in oC 10.1.1, so the issue is a regression

**Comment by ckamm** [comment]
The desktop client uses the `share_with` field to determine whether a link share has a password. Newer servers just send `"share_with":"***redacted***"` in both cases.

**Comment by sharidas** [comment]
I am suspecting https://github.com/owncloud/core/commit/31b47dc973ddf48bb9d5a9fd7ff30db89e33c164. The reason for this suspect is after I checkout this commit:
- created public link and tried to click the button to edit the link and here is how its viewed: 
![pub_link](https://user-images.githubusercontent.com/3600427/58886164-10516e80-8701-11e9-8e80-b2a4d26ee8b3.png)

**Comment by micbar** [comment]
related to https://github.com/owncloud/core/issues/35541

**Comment by micbar** [comment]
Fix in https://github.com/owncloud/core/pull/35544
