### ISSUE TITLE
[IE11-QA] Password reset email should fail if there is no email-address

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#35440]
Username: demo
Email: No email has been set up

Log out, enter wrong password
Click on 'Wrong Password. Reset It?'

This text appears:
![grafik](https://user-images.githubusercontent.com/1108546/58941950-1dac3e80-877d-11e9-8c56-600a76442f1d.png)

It claims to have successfully sent an email. That cannot be true, as there is no email configured.

**Comment by davitol** [comment]
IMHO the current behavior is OK. If we show a different message if a user has a mail set or not, it will turn into a security issue, due to people will we able to guess if the username really exists in the oC instance. (cc @pmaier for feedback)

**Comment by phil-davis** [comment]
You could write more text, e.g.:
```
The link to reset your password has been sent to your email, if your username has an email address set.
If you do not receive it...folders.
If it is not there or your username does not have an email address set then ask your local administrator for assistance.
