### ISSUE TITLE
remote shares from trusted servers is not automatically accepted when autoAddServers of app federation is set to 1 (one)

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/core#35446]
### Steps to reproduce
set up two owncloud servers ( for e.g. local_server and remote_server)
1. For remote_server

- set  ```autoAddServers``` of app ```federation``` to "1"
- set ```auto_accept_trusted``` of  app ```federatedfilesharing``` to "yes"

![screen](https://user-images.githubusercontent.com/34328907/59022973-7f000a80-886e-11e9-95fc-fb13f58a7bf5.png)

2. From local_server share some file or folder  
3. Login into remote_server and accept the share. Now the ```local_server``` should be listed as trusted owncloud server for ```remote_server```
4. Again share some file/folder from ```local_sever``` to ```remote_server```
5. Here even though ```local_server``` is trusted server for ```remote_server```, we have to accept the share i.e. remote share from trusted server is not automatically accepted
6. Now set  ```autoAddServers``` of app ```federation``` to "0"
![screen2](https://user-images.githubusercontent.com/34328907/59023939-8aeccc00-8870-11e9-8357-bc0c7f29643b.png)
7. Again share some file/folder from ```local_server``` to ```remote_server```. This time it's automatically accepted.
### Expected behaviour
Remote share from trusted server should be automatically accepted when ```autoAddServers``` and ```auto_accept_trusted``` of federation are set to ```1/yes```

### Actual behaviour
After a server(eg ```local_server```) has been identified as trusted server for ```remote_server```, remote share is automatically accepted only when ```autoAddServers``` of app ```federation``` is set to ```0```
### Server configuration
**Operating system**:
Ubuntu 18.04.2 LTS
**Web server:**
Apache
**Database:**
SQLite
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
11.0.0.0
**Updated from an older ownCloud or fresh install:**
fresh install
**Where did you install ownCloud from:**
git

**Comment by VicDeo** [comment]
by design, **autoAddServers** option blocks **auto_accept_trusted**

**Comment by VicDeo** [comment]
And this is documented 
 https://doc.owncloud.com/server/admin_manual/configuration/files/federated_cloud_sharing_configuration.html#automatically-accept-remote-shares-from-trusted-servers

![important](https://user-images.githubusercontent.com/991300/59935066-9dacf680-9455-11e9-81cc-70f9d3056169.png)
