### ISSUE TITLE
File type icon is not displayed in "shared with you"

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#35458]
### Steps to reproduce
1. "Automatically accept new incoming local user shares" is off
2. Anne shares `lorem.txt` with Bob
3. Anne shares `desktopapp.svg` with Bob
4. Bob accepts and then declines the received share of `desktopapp.svg`

### Expected behaviour
The files in the "Shared with you" panel should show the appropriate icons that go with the file type.

### Actual behaviour
The files have folder icons. 
The shared file `lorem.txt` that has never been accepted shows a  folder icon with a clock in it.
The shared file `desktopapp.svg` that has been accepted then declined shows an ordinary folder icon.
![Screenshot from 2019-06-07 17-12-21](https://user-images.githubusercontent.com/1535615/59101340-6c5a0400-8948-11e9-95cd-c5eef7c63cf6.png)

### Server configuration
**Operating system**:
Ubuntu 18.04

**Web server:**
PHP dev server

**Database:**
MySQL

**PHP version:**
7.1

**ownCloud version:** (see ownCloud admin page)
current core master

**Comment by davitol** [comment]
AFAIK when you decline the file, it gets unaccesible, so it is not possible to know if it is a file or a folder. So that it the reason why it is shown an ordinary folder icon
