### ISSUE TITLE
sharing via API and changing the cases in the username does not work correctly

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#35484]
### Steps to reproduce
1. create a user called `user1`
2. share a file via API with `USER1`
3. as `user1` check if you received the file

similar to https://github.com/owncloud/enterprise/issues/3241
related to https://github.com/owncloud/core/pull/35084 (was reverted because of  #35382)

tests for this case were :snake: :oil_drum: 

### Expected behaviour
sender should see the file as shared
receive should receive the file

### Actual behaviour
API replies to the sender that everything is fine
sender sees the file as shared
receiver cannot access the file

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache2
**Database:**
SQlite
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
11.0 (prealpha)
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
git
#### curl
```
curl -u admin:admin http://localhost/ocs/v1.php/apps/files_sharing/api/v1/shares -d "path=%2Florem.txt&shareType=0&shareWith=USER1"
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data>
  <id>7</id>
  <share_type>0</share_type>
  <uid_owner>admin</uid_owner>
  <displayname_owner>admin</displayname_owner>
  <permissions>19</permissions>
  <stime>1560254506</stime>
  <parent/>
  <expiration/>
  <token/>
  <uid_file_owner>admin</uid_file_owner>
  <displayname_file_owner>admin</displayname_file_owner>
  <path>/lorem.txt</path>
  <item_type>file</item_type>
  <mimetype>text/plain</mimetype>
  <storage_id>home::admin</storage_id>
  <storage>1</storage>
  <item_source>11</item_source>
  <file_source>11</file_source>
  <file_parent>5</file_parent>
  <file_target>/lorem.txt</file_target>
  <share_with>USER1</share_with>
  <share_with_displayname>user1</share_with_displayname>
  <share_with_additional_info/>
  <mail_send>0</mail_send>
  <attributes/>
 </data>
</ocs>

```

**Comment by individual-it** [comment]
not a regression, same issue in 10.1.1

**Comment by micbar** [comment]
@individual-it Could you post the content of `oc_share`

**Comment by individual-it** [comment]
```
+----+------------+------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+------------+------------+
| id | share_type | share_with | uid_owner | uid_initiator | parent | item_type | item_source | item_target | file_source | file_target | permissions | stime      | accepted | expiration | token | mail_send | share_name | attributes |
+----+------------+------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+------------+------------+
| 13 |          0 | USER1      | admin     | admin         |   NULL | file      | 81          | NULL        |          81 | /lorem.txt  |          19 | 1560257125 |        0 | NULL       | NULL  |         0 | NULL       | NULL       |
+----+------------+------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+-------------+-------------+------------+----------+------------+-------+-----------+------------+------------+

**Comment by micbar** [comment]
@individual-it This works as designed.

If you share via API with `USER1` this would be another user.

How should a user run into this scenario?

**Comment by individual-it** [comment]
@micbar then the API should tell the client that  `USER1` does not exist

> How should a user run into this scenario?

admin creates user `UseR1` a 3rd party client shares with `user1`

**Comment by micbar** [comment]
> @micbar then the API should tell the client that USER1 does not exist

That is correct.

**Comment by micbar** [comment]
This seems like somewhere, some weird magic is happening, which treats `USER1` and `user1` as the same. If I try to create both users in parallel, the webUi doesn't allow it.

**Comment by phil-davis** [comment]
IMO `user` `User` and `USER1` are all the same user throughout the system.
You can create a user using any of these as the UID (in webUI, Provisioning API or by occ command)
Then the user can login to the webUI with any case in the UID.
And the user (user's client typically) can send authentication to API endpoints putting any mixed case of the UID and the API will authenticate and work.

That os the theory, and I believe it mostly works like that. But there will be various cases to be found that do not work quite like that.

**Comment by phil-davis** [comment]
Note: the acceptance test that demonstrates this problem has been adjusted in PR #37502 so that it "understands" that the problem only occurs when the username has alphabetic characters - e.g. "BRIAN" "Brian" "brian" can be confused. But for a username like "007" there is no confusion (upper and lower case are the same)
