### ISSUE TITLE
Cannot share with user and group having same name

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#35488]
### Steps to reproduce
1. create user `abcdef`  and group `abcdef`
2. as another user, create a folder
3. using the webUI, share the folder with group `abcdef`
4. now also share the folder with user `abcdef`

### Expected behaviour
Both shares should be created.

### Actual behaviour
When sharing at step 4, webUI says "Path already shared with this user"

Similarly, if I share with the user first, then try to share with the group, webUI says "Path already shared with this group"

Note: this happens with `v10.1.0`, `v10.2.0`, current `stable10` and with PR #35397 - so it is nothing new.

### Server configuration
**Operating system**:
Ubuntu 18.04

**Web server:**
PHP dev server

**Database:**
MySQL

**PHP version:**
7.2

**ownCloud version:** (see ownCloud admin page)
Current `stable10`

**Comment by phil-davis** [comment]
Note: this happens if the group name and the user name are identical.

e.g. create group `AbcDef` and user `abcdef` or `ABCDEF` and everything is OK
but create group `AbcDef` and user `AbcDef` and there is a problem.

I expect that this is webUI-specific. But I will make some test scenarios for the sharing API to see if it is also broken.

**Comment by phil-davis** [comment]
See also issue #36069 - @HanaGemela reports that this bad behaviour is also noticed from the desktop client. So I guess that there is some real problem in the server API.

**Comment by phil-davis** [comment]
I added the `QA-team` label to remind us to make some API tests.
It would be good to really verify if there is an API problem, or if the problem is only in the UI.

**Comment by dpakach** [comment]
Acceptance tests demonstrating the bug in #36283

**Comment by phil-davis** [comment]
Removed QA-team label - tests have been added to demonstrate the bug in the sharing API.
Over to devs to prioritize and schedule a fix...
@micbar

**Comment by micbar** [comment]
Fixed.
