### ISSUE TITLE
App or feature that can zip or unzip files

### ISSUE THREAD

**Issue by rodude123** [owncloud/core#35546]
I wouldn't really call this an issue I just don't know where else to ask this. Well.saying that it is sort of an issue. The title says it all. Is there any way to zoo or unzip on owncloud it self without needing to upload the files individually or download them individually. I can see Nextcloud has an app in their store called `extract`.
This has probably been asked before but its 2019 so thought it needed some new light on the matter

**Comment by prsnbrg** [comment]
Hey,
in my cloud i use extract, this is an app developed for nextcloud.
[https://github.com/PaulLereverend/NextcloudExtract](https://github.com/PaulLereverend/NextcloudExtract)

In the appinfo/info.xml the requirements of ownCloud have to be inserted as already seen in the master branch.
It should work if you download the master branch and unpack it in your app directory.

Follow the installation instructions in the README.md file.

The installation didn't work for me, but the app also works with p7zip and p7zip-full.
`sudo apt-get install p7zip p7zip-full`

Activate app
`sudo -u www-data php occ app:enable extract`

**Comment by rodude123** [comment]
Thanks very much I will try this asap, I really need this feature

**Comment by hurradieweltgehtunter** [comment]
@prsnbrg very nice app. Would you be interested to publish your app also on owncloud marketplace?

**Comment by prsnbrg** [comment]
I ask the author of this app, but he isn't interested to publish and maintained for owncloud.
[https://github.com/PaulLereverend/NextcloudExtract/issues/22](https://github.com/PaulLereverend/NextcloudExtract/issues/22)

But maybe you can write him and ask if we help him with the support for owncloud, he will publish it for oc.

**Comment by lefherz** [comment]
@prsnbrg a shame that he doesn't want to maintain it... would you step up? I mean, publishing on the Marketplace is really not a big deal, the Bookmarks app is maintained similarly: https://owncloud.org/news/bookmarks-app-of-the-week/

You wrote in the other issue that you think the publishing process is a lot to do, is there something we can help you with?

**Comment by prsnbrg** [comment]
Now the app is available on [https://marketplace.owncloud.com/apps/extract](https://marketplace.owncloud.com/apps/extract).

**Comment by rodude123** [comment]
brilliant
