### ISSUE TITLE
Public link share creation no longer automatically sets expiration date

### ISSUE THREAD

**Issue by ckamm** [owncloud/core#35550]
Probably relates to https://github.com/owncloud/core/pull/34971

Previously on creation of a public link share, if "Set default expiration date" was enabled and no expire data parameter was set on the share creation API request, the server would automatically set the default expiration date on share creation.

Now, it does not do that anymore and instead replies "Expiration date is enforced".

This breaks how the desktop client used the API. In particular it will make it impossible to create any public link shares on desktop clients before 2.6.0 if "Enforce expiration date" is also enabled.

See https://github.com/owncloud/client/issues/7245

Possibly the link share creation API could distinguish between
- requesting "no expiry" (to resolve the problem PR #34971 was addressing)
- requesting "expire at that date"
- not having the "expireDate" parameter at all (restoring the previous behavior for this case)

**Comment by karakayasemi** [comment]
@ckamm PR for fixing regression in here: https://github.com/owncloud/core/pull/35564

**Comment by micbar** [comment]
@ckamm please test thorughly, we have to avoid fixin stuff in all projects simultanously :-)

**Comment by individual-it** [comment]
- [ ] ToDo QA-Team: create acceptance tests for that

**Comment by skshetry** [comment]
Assigned myself to work on acceptance tests.

**Comment by phil-davis** [comment]
@skshetry is going to create some acceptance test scenarios so that this will not regress again in future.
