### ISSUE TITLE
Expire token (link email) change time

### ISSUE THREAD

**Issue by Henk1060** [owncloud/core#35596]
1. add a new user
2. user gets an e-mail  with create password link
3. link already expires after 12 hours

how or where can I change the time?
To change the expiration time of a link.

I think currently after 12 hours a link is no longer valid.
e.g. create password at first registration

thanks a lot

**Comment by davitol** [comment]
Answered in Central: https://central.owncloud.org/t/expire-token-link-email-change-time/20568/6

Thanks for reporting
