### ISSUE TITLE
Drag+drop into trashcan drops file elsewhere

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#35608]
* log into demo.owncloud.org
* download 'ownCloud Manual.pdf' to your desktop.
* navigate into the Photos folder, create another subfolder Empty
* navigate into that folder.
* click 'deleted files'
* open a file browser on your desktop
* drag and drop the file 'ownCloud Manual.pdf' into the trashcan

The file is not added to the trashcan. No error message either.
The file now is in /Photos/Empty. (It seems to remember the last folder before entering trashbin.)

Expected behaviour: No drag and drop allowed, or really drop into the transhbin.

Suggested fix: disable drag and drop in the trashcan

**Comment by cdamken** [comment]
@micbar  FYI

**Comment by PVince81** [comment]
the original idea, a long time ago, was to allow dropping on trashbin and have it actually delete.

for now would be best to disable dropping there

**Comment by JanAckermann** [comment]
>Suggested fix: disable drag and drop in the trashcan
Seems to be done already
