### ISSUE TITLE
Cannot overwrite public share template

### ISSUE THREAD

**Issue by lippoliv** [owncloud/core#35623]
### Steps to reproduce
1. Create an own theme
2. Register it to your ownCloud
3. Try to overwrite/style the template for public file sharing (app "files_sharing")

### Expected behaviour
It should be possible for an theme developer to overwrite themes of APPs, like it was in older ownCloud versions.

### Actual behaviour
I did not find a way to overwrite `files_sharing/templates/public.php`. My closest approach was using `layout.base.php` to check if the header is in the content and regex-replace it (dirty, I know). But this doesn't work as of the template variables aren't available at this moment (`canDownload`).

### Server configuration
**docker-compose.yml**:

```
version: '3'

services:
  owncloud:
    image: owncloud:10.0.10-apache
```

**Updated from an older ownCloud or fresh install:**

Fresh on each boot (dev docker environment)

**Where did you install ownCloud from:**

Official docker container.

**Signing status (ownCloud 9.0 and above):**

https://gist.github.com/lippoliv/47c6610ce48209de4e578543c1502803

**The content of config/config.php:**

https://gist.github.com/lippoliv/be36bb0f36066d33c3199a6361fb8e61

**Are you using external storage, if yes which one:** 

No

**Are you using encryption:**

No

**Are you using an external user-backend, if yes which one:** 

No

### Client configuration
**Browser:**

Chrome

**Operating system:**

WIN10

**Comment by VicDeo** [comment]
@lippoliv  works for me:
```
mkdir -p apps/your-theme-app/apps/files_sharing/templates/
cp apps/files_sharing/templates/public.php  apps/your-theme-app/apps/files_sharing/templates/
```
Edit **apps/your-theme-app/apps/files_sharing/templates/public.php**

```
> grep works  apps/theme-hey/apps/files_sharing/templates/public.php 
<h1> It works!</h1>
```

Result:
![publicShare](https://user-images.githubusercontent.com/991300/59953964-2c883600-948b-11e9-98c9-8f5abb4bdd04.png)

If you already tried this, please check ownership/permissions for the files/directories in your theme

**Comment by lippoliv** [comment]
@VicDeo thanks for the quick help, works :)

Question: Is there any hint on this in the docs? I did not saw it. I hoped that exactly this can be done, but I did not read about it?
