### ISSUE TITLE
File sharing to the already shared user gives wrong error message

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/core#35626]
### Steps to reproduce
1. Create a user (for eg. ```some_user```)
2. Share a file (eg. ```abc.txt```) to ```some_user``` using webui
3. Again try to share the same file (```abc.txt```) to the same user (```some_user```) using webui
Here you get error message as:
```No users or groups found for some_user```

### Expected behaviour
You should get more sensible error message like:
```File already shared with some_user```
### Actual behaviour
Error message doesn't make any sense as the user already exists and you previously shared the same file to the same user.
### Server configuration
**Operating system**:
Ubuntu 18.04.2 LTS
**Web server:**
Apache
**Database:**
SQLite
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
11.0.0.0
10.2.0
10.1.0
**Where did you install ownCloud from:**
11.0.0.0   from git
10.2.0     from tarball
10.1.0     from tarball

**List of activated apps:**
  - comments: 0.3.0
  - dav: 0.4.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_sharing: 0.12.0
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - guests: 0.8.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - testing: 0.1.0
  - updatenotification: 0.2.1
  - user_management: 0.0.1

**Comment by phil-davis** [comment]
Using the webUI or the sharing API or?

**Comment by HariBhandari07** [comment]
@phil-davis using webui

**Comment by davitol** [comment]
![Screen Shot 2019-06-25 at 09 12 48](https://user-images.githubusercontent.com/10596560/60077099-77bf7480-9729-11e9-90a3-60576f3a9ea1.png)
@HariBhandari07 Thanks for reporting. AFAIK it is not a bug and it is designed it this way if there are no users to share. 

(cc @pmaier1 feel free to provide more feedback or close the ticket if you consider the behavior is OK)

**Comment by phil-davis** [comment]
The reported issue suggests that the message could be improved. Maybe somewhere in the JavaScript (or the text of that message might be coming back from the serve?) the code could understand that the real reason that nothing is found is because "File/folder is already shared with this user"
