### ISSUE TITLE
Public link share with no password works with password

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#35635]
### Steps to reproduce
1. create a default read-only public link share with no password
2. access it without specifying a password - works, good
3. access it and provide some string as a password

### Expected behaviour
Who knows?

I guess this is fine, the resource has no password and so either no password or "any old password" is fine.

### Actual behaviour
It works - the file/folder can be read.

### Discussion

I am just raising this to get an opinion and have the agreed behavior document somewhere (here)

Feature?

**Comment by davitol** [comment]
> access it and provide some string as a password

@phil-davis How can you provide a password in a public link share with no password? I guess you are not refering to the webUI but the API.

**Comment by phil-davis** [comment]
Yes, using the API.
If you browse to the public link in a browser then you already get directly shown the folder/file.
