### ISSUE TITLE
After updating an app, the ownCloud instance is loading old app's js file

### ISSUE THREAD

**Issue by davitol** [owncloud/core#35640]
When you install an app using the CLI (occ market:install), the new version of market app is installing under apps-external folder which folder is the writable one in the config.php and the old version is still remaining under apps folder. That is the expected behavior due to 'writable' => false means "nobody can change anything in this app directory". 
See the expectations in owncloud/core#35031

After the installation the ownCloud instance is somehow loading old app's js file. If you remove the old app from apps folder, the problem is solved

**Comment by VicDeo** [comment]
The false positive is here:
https://github.com/owncloud/core/blob/master/lib/private/Template/JSResourceLocator.php#L55-L59

**Comment by VicDeo** [comment]
Only God knows how I want to rewrite that part from scratch :no_bicycles:

**Comment by VicDeo** [comment]
@davitol FYI https://github.com/owncloud/core/pull/35698
