### ISSUE TITLE
Federation sharing to local user should create local share

### ISSUE THREAD

**Issue by skshetry** [owncloud/core#35650]
### Steps to reproduce
1. Create two users: `user0` and `user1`.
2. Login as `user0`.
3. Share a file with local user via federation sharing (eg: if your domain is `server-https`, share with `user1` using `user1@server-https`).

### Expected behaviour
`user1` should get local share instead of federation sharing.

### Actual behaviour
`user1` gets a federation share.

**Comment by skshetry** [comment]
I have added `app:federation` and `feature:sharing` labels.

**Comment by michaelstingl** [comment]
@pmaier1 What about existing federated shares to local users? Out of scope?

**Comment by pmaier1** [comment]
> user1 gets a pending share. Needs to approve the share to access the file.

That does not grasp the actual issue. It's not about pending or not, that's configurable. It's about the share type. A fed share does only make sense between different installations. Between users on the same installation, federated shares should not be possible as it does not make sense. It should anyhow be possible to find a local user via their federation ID.

> @pmaier1 What about existing federated shares to local users? Out of scope?

Yeah, needs some thinking, I guess. But would be nice to get a repair step to clean this up
