### ISSUE TITLE
Maximum expiration date does not work on desktop client when not enforced

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/core#35661]
Server: 10.2.1.RC1(testing)
Client: macOS 2.5.4 (build 11456)
macOS: 10.14.5

Steps to recreate:
1. On the server go to Settings -> Admin -> Sharing
2. Tick 'Set default expiration date'
3. Set Expire after e.g. 3 days
4. Do not tick Enforce expiration date
5. Create a new public link on the desktop client

Actual result: The suggested date for 'Set expiration date' is tomorrow. Also the date can be set to whatever date, even later than 3 days in the future
Expected result: The suggested date for 'Set expiration date' is 3 days in the future. Also the expiration date cannot be set later than in 3 days

**Comment by davitol** [comment]
Works in WebUI view, so it affects the creation of Public Links in Desktop Client:

![Screen Shot 2019-06-25 at 18 08 35](https://user-images.githubusercontent.com/10596560/60114645-84b58580-9774-11e9-9740-fa4a95a69ac4.png)

![Screen Shot 2019-06-25 at 18 11 44](https://user-images.githubusercontent.com/10596560/60114739-bb8b9b80-9774-11e9-9339-fbb2b4012057.png)

@jesmrec Can you please check the behavior in a mobile client? Thanks

**Comment by jesmrec** [comment]
If expiration is set (f.ex) in 12 days, mobile clients fetch the value from the capabilities request. Then, expiration date is set by adding the amount of days to today's date.

**Comment by micbar** [comment]
> If expiration is set (f.ex) in 12 days, mobile clients fetch the value from the capabilities request. Then, expiration date is set by adding the amount of days to today's date.

Yes, this is correct for some clients. But the Desktop Client < 2.6 expects the Server to set a default expiration date.
@ckamm

**Comment by phil-davis** [comment]
> > If expiration is set (f.ex) in 12 days, mobile clients fetch the value from the capabilities request. Then, expiration date is set by adding the amount of days to today's date.
> 
> Yes, this is correct for some clients. But the Desktop Client < 2.6 expects the Server to set a default expiration date.
> @ckamm

See my comment https://github.com/owncloud/core/pull/35676#issuecomment-505826135

If "set default expiration date" is set, and not enforced, then a request should still be able to create a public link share that has no expiration date (true?). If so, then how does a client make such a request?

**Comment by micbar** [comment]
@phil-davis It is possible to create a share without a expiration date. BUT: You cannot do this on initial creation
1) Create it
2) Edit it and remove the expiration date.

If we change this behaviour, we would break all Desktop Clients < 2.6

**Comment by phil-davis** [comment]
We could, some time in the future, add some way to send a request that specifically specifies "no expiration date". That would be a future enhancement to the API, which should be backward-compatible (not break any current usage/workflow)

**Comment by micbar** [comment]
Difference between Desktop Clients

## v2.5.4
```
POST http://cloud.local/ocs/v1.php/apps/files_sharing/api/v1/shares?format=json

POST VARS:
reshares:  true
path:      /welcome.txt
shareType: 3
name:      Öffentlicher Link 2
```

## v2.6.0
```
POST http://cloud.local/ocs/v1.php/apps/files_sharing/api/v1/shares?format=json
POST VARS:
reshares:    true
path:        /welcome.txt
shareType:   3
name:        Öffentlicher Link 2
expireDate:  2019-06-29
permissions: 1
```

**Comment by michaelstingl** [comment]
@ckamm @HanaGemela @micbar backport the 2.6 behavior and release a 2.5.5 ? Please also check behavior with `password_policy` …

**Comment by micbar** [comment]
@michaelstingl I agree.

We should backport the 2.6 Desktop Client behavior to 2.5.5 and keep the api as it is.

This way we could keep the possibility to set an empty value if not enforced.

**Comment by ckamm** [comment]
Seems to make sense to me. I'll create an issue about it in the client repo and close here.

**Comment by ckamm** [comment]
@HanaGemela @micbar Actually, I don't understand. In the server settings "set default expiration date" is on and "enforce expiration date" is off. The problematic action in the issue description is that it's allowed to set an expiration date that is later than what's set under "default expiration date".

But... users are allowed to unset the expiration date. Why does enforcing a maximum make sense when they can disable expiry altogether?

**Comment by HanaGemela** [comment]
@ckamm The problem is that the default date is not suggested. When creating a new public link the 'Set expiration date' checkbox should be activated and the date should be the default date which is set on the server. When this is not enforced, user can change it

**Comment by HanaGemela** [comment]
@ckamm Currently waiting for @pmaier1 to adjust https://github.com/owncloud/enterprise/blob/master/product/oc10/collaborators.md

**Comment by phil-davis** [comment]
If "enforce expiration date" is off, then users should be suggested the calculated default expiration date, but users can change it to any date, or no date at all.

If "enforce expiration date" is on, then users should be suggested the calculated default expiration date, but users can change it to any earlier date. But they must choose a date ("no date" is not valid/possible)

**Comment by ckamm** [comment]
@HanaGemela @phil-davis All clear then.

**Comment by ckamm** [comment]
Change to client is tracked in owncloud/client#7276
