### ISSUE TITLE
Acceptance tests when users are restricted to only share with groups they are member of

### ISSUE THREAD

**Issue by skshetry** [owncloud/core#35673]
Write api and webui tests when users are restricted to only share with groups they are member of.

There's the capability: `shareapi_only_share_with_membership_groups` and settings in `Admin Sharing` that needs to be tested with. Test for possible scenarios and if completed, please:

- [x] Tick boxes owncloud/QA#353 and owncloud/core#31531

**Comment by paurakhsharma** [comment]
@skshetry  I think we can close this now

**Comment by paurakhsharma** [comment]
PR #35733 and #35736 should cover this.
