### ISSUE TITLE
Fix capabilites on acceptance test code

### ISSUE THREAD

**Issue by skshetry** [owncloud/core#35677]
Currently, the test code can check for capabilities on the server multiple times. The part of the test code keeps the changes to rollback in some variable and manage that themselves. This is error-prone. If they need same capabilities to be changed, as we query for this each time, that might create collision as we might have already changed the capability. 

## TODO:
1. Only get the capabilities of the server when we start the tests which will be used to rollback.

Or, 2. Use this to capabilities response to check for rollback, or just send whatever was saved before to rollback.

**Comment by phil-davis** [comment]
@skshetry it will be good to clean this up. We want the API test infrastructure "good and clean".
But not a super-high priority - do as a background task when release testing is blocked.

**Comment by skshetry** [comment]
@phil-davis, this is not much of a problem at the moment, but if we change capabilities from multiple places in the future, it will be. We need to design a good API and solution that can keep track of capabilities. And, first, I need to understand the flow of capabilities. So, I'll work on this passively, in the background as you suggested (with not an immediate PR in mind).

**Comment by dpakach** [comment]
@phil-davis, do we really need to remember and restore the capabilities?

It doesn't seem like there is a direct way to change capabilities. they are changed by changing various system and app configs. The acceptance tests already remember all the system/app configs and restore them to the state they were before running the tests.

**Comment by skshetry** [comment]
@dpakach, the problem that this issue mention was fixed by https://github.com/owncloud/core/pull/35422. In that, what was happening was:
1. CapabilitiesContext (IIRC) was keeping a copy of capabilities.
2. Some contexts were changing the capabilities.
3. WebUISharing then comes and tries to keep its own copy of capabilities (which now includes some updates from acceptance tests).

During the rollback, the order would probably get different. While writing this issue, I was thinking of a `CapabilitiesStore` that'd keep a single state rather than keeping on each context, and they would go through it when saving/modifying/restoring the capabilities. I hope that helps. (also I am not aware of the current state, so maybe the issue is stale now 😄).

**Comment by dpakach** [comment]
Thanks a lot for the info @skshetry, I'll talk with @phil-davis and we can probably close this issue.
