### ISSUE TITLE
Expiry after x days defaults to 1 instead of 7

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/core#35687]
In the Sharing settings when I delete the value from 'Expire after x days', the placeholder suggest the number of days should be 7. When I click somewhere else on the page, number of days is changed to 1. 
Server: 10.2.1. RC1

Steps to recreate:
1) Go to Settings -> Admin -> Sharing 
2) Check 'Set default expiration date' checkbox
3) Delete the number from 'Expire after x days'
4) Click somewhere else

Expected result: Number 7 is pre-populated as default
Actual result: Number 1 is pre-populated as default

**Comment by phil-davis** [comment]
My attempt is in PR #35688 
It seemed easy to fix. But someone familiar with the UI elements will be able to tell me what else/different needs to happen.

**Comment by patrickjahns** [comment]
Moving to backlog to be considered for the next release

**Comment by phil-davis** [comment]
Fixed by PR #35776
