### ISSUE TITLE
phan failing on PHP 7.2 and 7.3

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#35697]
PHP patch releases were applied today to the docker images used in drone CI.
`7.1.30`
`7.2.19`
`7.3.6`

after that, `phan` started to fail on PHP 7.2 and 7.3 - e.g. https://drone.owncloud.com/owncloud/core/18990/98

```
ReflectionException: Method Closure::__invoke() does not exist in /drone/src/vendor-bin/phan/vendor/phan/phan/src/Phan/Language/Element/FunctionFactory.php:96
Stack trace:
#0 /drone/src/vendor-bin/phan/vendor/phan/phan/src/Phan/Language/Element/FunctionFactory.php(96): ReflectionMethod->__construct('Closure', '__invoke')
#1 /drone/src/vendor-bin/phan/vendor/phan/phan/src/Phan/Language/Element/Clazz.php(311): Phan\Language\Element\FunctionFactory::methodListFromReflectionClassAndMethod(Object(Phan\Language\Context), Object(ReflectionClass), Object(ReflectionMethod))
#2 /drone/src/vendor-bin/phan/vendor/phan/phan/src/Phan/CodeBase.php(811): Phan\Language\Element\Clazz::fromReflectionClass(Object(Phan\CodeBase), Object(ReflectionClass))
#3 /drone/src/vendor-bin/phan/vendor/phan/phan/src/Phan/CodeBase.php(800): Phan\CodeBase->loadPHPInternalClassWithFQSEN(Object(Phan\Language\FQSEN\FullyQualifiedClassName), Object(ReflectionClass))
#4 /drone/src/vendor-bin/phan/vendor/phan/phan/src/Phan/CodeBase.php(788): Phan\CodeBase->lazyLoadPHPInternalClassWithFQSEN(Object(Phan\Language\FQSEN\FullyQualifiedClassName))
#5 /drone/src/vendor-bin/phan/vendor/phan/phan/src/Phan/Analysis/PropertyTypesAnalyzer.php(64): Phan\CodeBase->hasClassWithFQSEN(Object(Phan\Language\FQSEN\FullyQualifiedClassName))
#6 /drone/src/vendor-bin/phan/vendor/phan/phan/src/Phan/Language/Element/Clazz.php(2575): Phan\Analysis\PropertyTypesAnalyzer::analyzePropertyTypes(Object(Phan\CodeBase), Object(Phan\Language\Element\Clazz))
#7 /drone/src/vendor-bin/phan/vendor/phan/phan/src/Phan/Analysis.php(403): Phan\Language\Element\Clazz->analyze(Object(Phan\CodeBase))
#8 /drone/src/vendor-bin/phan/vendor/phan/phan/src/Phan/Phan.php(275): Phan\Analysis::analyzeClasses(Object(Phan\CodeBase), NULL)
#9 /drone/src/vendor-bin/phan/vendor/phan/phan/src/Phan/Phan.php(225): Phan\Phan::finishAnalyzingRemainingStatements(Object(Phan\CodeBase), NULL, Array, Array)
#10 /drone/src/vendor-bin/phan/vendor/phan/phan/src/phan.php(41): Phan\Phan::analyzeFileList(Object(Phan\CodeBase), Object(Closure))
#11 /drone/src/vendor-bin/phan/vendor/phan/phan/phan(2): require_once('/drone/src/vend...')
#12 {main}

make: *** [test-php-phan] Error 1
Makefile:222: recipe for target 'test-php-phan' failed 
```

For now, PR #35693 disables the `phan` step for PHP 7.2 and 7.3 - it still runs and passes on PHP 7.1

- [ ] sort out what is wrong
- [ ] find a suitable version of `phan`
- [ ] enable it again on 7.2 and 7.3

**Comment by phil-davis** [comment]
@micbar @patrickjahns this needs to be sorted out some time. You can decide the priority.

Note: the version of `phan` can be increased and the error goes away. But the newer version(s) of `phan` report lots more code "issues". So work would be needed to sort out how to setup `phan` correctly, or correct the code, or suppress messages as appropriate.

**Comment by patrickjahns** [comment]
A shot was to get the dependencies resolved to the proper php version https://github.com/owncloud/core/pull/35704 - didn't have the desired effect :(

**Comment by patrickjahns** [comment]
Suggestion:
- we bump phan to a later version, but we just ignore the issues found on top of current issues?

**Comment by phil-davis** [comment]
Agree - any issue that is not "obvious" to fix, we can suppress it.

**Comment by micbar** [comment]
@patrickjahns @phil-davis Next steps?

**Comment by phil-davis** [comment]
@micbar @patrickjahns I am waiting for reviews of 
https://github.com/owncloud/core/pull/35817
https://github.com/owncloud/core/pull/35818

IMO those are ready. Unless somebody responds to the items that are sitting "ready for review" in the sprint, there is nothing that I can do.

**Comment by phil-davis** [comment]
See #36092 for follow-up issue
