### ISSUE TITLE
fix path encoding problems in tests steps

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#35741]
some steps like like `Then user "user1" should see the following elements` need the path to be encoded in the step definition e.g. `%20` for a space
```
    Then user "user1" should see the following elements
      | /PARENT%20(2)/           |
      | /PARENT%20(2)/parent.txt |
```

Other steps don't need that e.g. `Then as "user1" folder "/merge-test-inside-twogroups-perms (2)" should not exist`

This is particular bad when checking for something that does not exist
```
    Then user "user1" should see the following elements
      | /PARENT (2)/           |
```
would always pass but be :snake: :oil_drum: 

We need to make it uniform

**Comment by saw-jan** [comment]
Done in PR https://github.com/owncloud/core/pull/38734
Closing the issue for now
