### ISSUE TITLE
Missing error message when user is created without password 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/core#35743]
Server: 10.2.1 RC3

Steps to recreate:
1) Install Password policy app from Marketplace
2) Go to Settings -> Admin -> Security 
3) Set some requirements in 'Minimum password requirements for user accounts and public links' (so that password is mandatory) 
4) Go to Users 
5) Create a new user specifying only Username and E-Mail

Actual result: Nothing after clicking Create button 
Expected result: Error message that password is required

**Comment by phil-davis** [comment]
IMO the requirement here is that the new user will receive an email with a link for setting their password. Then they follow the link, and when setting their password they should be forced to comply with the password policy.

So for me, "expected result" is that the new user does receive an email. Does that happen?

**Comment by HanaGemela** [comment]
As the user has not been created I don't expected them to get an email . So you think the user should be shown in the list of users once they have a password and not earlier?

**Comment by phil-davis** [comment]
Oh, if the user is not shown at all then something is going wrong at that first stage. That needs to be investigated and fixed. Then follow along the workflow to see what breaks next!

Likely similar problem to https://github.com/owncloud/password_policy/issues/228

**Comment by sharidas** [comment]
I am not able to reproduce this issue.

Steps done:
- checked out commit `7a3d8674a0` from core so that it points to 10.2.1
- password_policy app is pointing to updated master branch ( version 2.0.2)
- Enabled all check boxes under `Minimum password requirements for user accounts and public links:`
- Also made sure the smtp configurations are set in the config.php
- Created a new user `user1` with an email id
- Verified that email is arrived in the inbox with subject: `Your ownCloud account was created`

**Comment by HanaGemela** [comment]
I double checked my setting and this is my password policy app setting 

![image](https://user-images.githubusercontent.com/49001702/60672756-7521f500-9e76-11e9-91d3-fdf03aea0b38.png)

**Comment by HanaGemela** [comment]
'Restrict to these special characters' field being empty is causing this issue
When I enter some special character into 'Restrict to these special characters', I can create a user

**Comment by phil-davis** [comment]
When 'special characters' is checked and 'Restrict to these special characters' field is empty, then the "special characters" set is supposed to be "all non-alphanumeric characters" (probably that will work best when people do not try to type emojis etc - that is another issue!).

If a password is sent on user creation, then all is fine. Password policy `verifyPassword()` does the right thing and checks that the password contains some non-alphanumerics.

If the user is created with email address, then a password is not sent. The backend code calls `generatePassword()` to generate an initial "random" password (that nobody will ever know). That code crashes the above settings.

See https://github.com/owncloud/password_policy/pull/233 for a fix.

**Comment by phil-davis** [comment]
Another challenge when I was testing this was that my browser was filling in the hidden password field with one of my saved passwords. That got sent to the server along with the new username and email address. In that case the server tried to validate the password (that the browser filled in for me in a hidden field). The password did not meet the policy, and so I got password validation errors back.

That is issue https://github.com/owncloud/password_policy/issues/228

It really messes things up when trying to test, and it would be very annoying for a real administrator also.

**Comment by sharidas** [comment]
Created PR
- [x] master branch https://github.com/owncloud/password_policy/pull/234 ( merged )

**Comment by micbar** [comment]
Closed, fix done. Will be in next release.
