### ISSUE TITLE
Any plans for passman for ownCloud 10.1.1 ?

### ISSUE THREAD

**Issue by TomaszWaszczyk** [owncloud/core#35745]
Any plans for passman for ownCloud 10.1.1 ?

**Comment by DeepDiver1975** [comment]
I suggest you get in touch with the developer https://github.com/brantje - but I guess his primary focus is nextcloud.

Maybe someone can help out .....

**Comment by TomaszWaszczyk** [comment]
@brantje Are You able to help?

**Comment by ho4ho** [comment]
https://github.com/nextcloud/passman/issues/559 ?

**Comment by VicDeo** [comment]
@TomaszWaszczyk  please submit a pull request changing https://github.com/nextcloud/passman/blob/master/appinfo/info.xml#L46
into `<owncloud min-version="10" max-version="10"/>`
That should be enough.

**Comment by TomaszWaszczyk** [comment]
Hmmmmm but of coruse I was doing it on my machine and does not help ;/

**Comment by plastikschnitzer** [comment]
I changed the max-version to 11 and its working in ownCloud 10.2.1 after performing the upgrade from 10.0.10 – but for sure it would be nice if the app development would be continued … I use the app every day :-/

**Comment by VicDeo** [comment]
@pandeykartikey we can't continue it as we didn't even start it. It's a third-party app.
If the passman developers would like  to have any kind of tech assistance from ownCoud community we are glad to help.

**Comment by pandeykartikey** [comment]
I think you meant @plastikschnitzer @vicdeo

**Comment by VicDeo** [comment]
@pandeykartikey exactly. pease excuse me.

**Comment by plastikschnitzer** [comment]
@VicDeo I do not expect ownCloud to take over, I would like to get the answer from the developer about his plans, I also asked him in the forum. 
(Not) fun fact: OwnCloud wrote about the extension and promoted it [on their website](https://owncloud.org/news/best-secure-password-manager-owncloud/) at a time where it was already not compatible to the current ownCloud Version (10.1. at that time) any more. 3rd party extensions at its best … 
As I am a regular user with several instances and testing server(s) I can help with testing the app for sure. It would be sad not to have the app any more.

**Comment by PVince81** [comment]
this should have been a post on central instead of a bug report

anyway, please submit a PR upstream and clarify with the maintainer of the app about OC support
