### ISSUE TITLE
Tests for public + chunked uploads

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#35761]
Need tests for chunked uploads through the "public.php/webdav" (and "public.php/dav" ?) endpoint.

Note that there might be an issue:
```
{"reqId":"HZ2HgUR2BLdVvnmFHxo0","level":3,"time":"2019-07-04T07:02:25+00:00","re
moteAddr":"172.18.0.1","user":"--","app":"core","method":"PUT","url":"\/public.p
hp\/webdav\/fofofo.txt-chunking-1562223745-34-0","message":"Can't get cache stor
age, user not logged in"}
{"reqId":"HZ2HgUR2BLdVvnmFHxo0","level":4,"time":"2019-07-04T07:02:25+00:00","re
moteAddr":"172.18.0.1","user":"--","app":"webdav","method":"PUT","url":"\/public
.php\/webdav\/fofofo.txt-chunking-1562223745-34-0","message":"Exception: Can\\t 
get cache storage, user not logged in: {\"Exception\":\"OC\\\\ForbiddenException
\",\"Message\":\"Can\\\\t get cache storage, user not logged in\",\"Code\":0,\"T
race\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Cache\\\/File.php(12
8): OC\\\\Cache\\\\File->getStorage()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/
private\\\/Cache\\\/File.php(86): OC\\\\Cache\\\\File->hasKey('fofofo.txt-chun..
.')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/filechunking.....
```

**Comment by skshetry** [comment]
Chunking is not implemented on public WebDAV endpoints. Close this? @phil-davis @individual-it

**Comment by jvillafanez** [comment]
I think I checked with https://github.com/owncloud/pyocclient and modifying the endpoint to point to the public webdav endpoint (it needs some hacking in the library code).
As far as I remember, the upload went fine without chunking, but when I told the library to use chunking it threw that error in the logs.

Outside of that, I guess the problem is that there is no easy way to upload the chunked file to the public endpoint; either the library chunks the file more or less automatically in order to upload the file normally through the usual webdav endpoint, or you need to make the chunks yourself and upload them one by one through the public endpoint.
I don't have a php code snipet for this.

**Comment by skshetry** [comment]
@jvillafanez, public webdav (old and new) endpoint does not support chunking file upload as per @DeepDiver1975.

**Comment by skshetry** [comment]
Closing as chunking is not supported for public uploads.
