### ISSUE TITLE
LDAP admin group mapping

### ISSUE THREAD

**Issue by jekader** [owncloud/core#3577]
I've connected OwnCloud to our LDAP with a few thousand users, and to assign admin rights I need to manually add each user to the "admin" group. 

How can I make all members of a given LDAP group automatically become OwnCloud admins?

**Comment by nebulade** [comment]
The mapping of an ldap group named 'admin', as @ajpaul25 suggested, does not seem to work with OC8. Is there any update on this issue, or some other workaround for now?

**Comment by Wardrop** [comment]
Just installed OwnCloud and am surprised I can't make an LDAP group an administrator. In fact, I'm surprised there's no "permissions" at all. Can't make groups or users read-only or anything. Super surprised.

**Comment by PVince81** [comment]
@MTRichards @cmonteroluque defer this feature to 9.0 ?

**Comment by MTRichards** [comment]
Yes.

**Comment by alexklaeser** [comment]
+1

This is also something we at Univention would love to see for ownCloud in combination with Univention Corporate Server (UCS). The current [ownCloud Appliance with UCS](https://www.univention.com/products/univention-app-center/app-catalog/owncloud81/) by default creates the user *Administrator* as domain wide admin and member of the LDAP group *Domain Admins*. From a usability perspective, it is not easy to understand that *Administrator* is not allowed to administrate ownCloud, as well, but instead one needs to login with a special admin user.

**Comment by PVince81** [comment]
We're past feature freeze, move this enhancement to 9.1 ? @MTRichards @cmonteroluque @blizzz

**Comment by blizzz** [comment]
I'd say so.

**Comment by MTRichards** [comment]
It's what I see now too.

**Comment by cmonteroluque** [comment]
ok

**Comment by mrow4a** [comment]
@cdamken

**Comment by jnweiger** [comment]
:+1:

**Comment by michaelstingl** [comment]
@pmaier1 @hodyroff This is a requirement for the UCS appliance. Plz check again with @s85t and @felixboehm for milestone.

@mrow4a @jvillafanez How would you estimate the effort to solve this issue.

**Comment by cdamken** [comment]
IMHO doesn't look that complicated, while  running the occ:  ldap:update-group  can be added/removed the new admin users that belongs in LDAP in the oc_group_user as admin.

just have to be defined which is the default admin group in the LDAP configuration.

**Comment by S85T** [comment]
I totally agree, this feature would improve the usage and usability of the new UCS based appliance a lot, because the workaround described by alexklaeser above is not very intuitive.

**Comment by pmaier1** [comment]
Regarding the benefits in UX and intuitive use of the UCS appliance this definitely needs to be done. We need an effort estimation and assignment. If this really is a junior job we might be able to do it for the next release.

**Comment by pmaier1** [comment]
I had a chat with @felixboehm about this, thought about it again and have to revert my last comment:
- With the suggested approach oC can become dependent on AD. If AD breaks for some reason you are unable to login to oC using the LDAP admin group.
- Using the Provisioning API you can automatically add certain AD users/groups to the oC admin group which should be sufficient for the appliance.
- The most generalized solution would be to be able to assign admin rights to groups in oC. With that you could simply provide admin rights to groups imported from AD.

**Comment by pmaier1** [comment]
Concluding notes having talked to @DeepDiver1975 :
- The requested functionality currently is not provided by OCC.
- Provisioning API has the drawback (in this case) that it needs admin credentials. **However, it is the recommended way to solve the issue for now.**
- Assignment of admin rights to arbitrary groups is a feature that fits with our vision and will be taken into account in a future concept for improving rights management.

**Comment by felixboehm** [comment]
I strongly recommend to use the provisioning api to add the AD Administrator to the ownCloud admin group. That is what the API is for. No need to work out a second way to achieve the same.

https://doc.owncloud.org/server/9.1/admin_manual/configuration_user/user_provisioning_api.html#users-addtogroup

**Comment by hirnschmalz** [comment]
I don't think that this is a solution for a real life environment. If I add a user to an administrative group in my AD I don't want to call the API in a separate step to make it an ownCloud admin as well.

**Comment by felixboehm** [comment]
In a real world scenario there are different admins for services like ownCloud and AD.
If you want to setup ownCloud and privilige the System / AD admin, mostly called "Administrator", then add this configuration to your ansible or setup scripts, right after the ldap config section:

`
curl -u admin:admin-password $OWNCLOUD_HOST/ocs/v1.php/cloud/users/Administrator/groups -d groupid="admin"
`

**Comment by cdamken** [comment]
@settermjd can you please add this to the documentation
