### ISSUE TITLE
Change branching model for core ...

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#35777]
## Background

We use [OneFlow](https://www.endoflineblog.com/oneflow-a-git-branching-model-and-workflow) successfully for our apps for quite some time.
It is about time to use OneFlow for core as well!

## Steps to take
- [x] move current master branch to [archive/master](https://github.com/owncloud/core/tree/archive/master) - just for the sake of not loosing anything
- [x] move stable10 to master - this will be our main branch to release any future ownCloud 10.x.x
- [x] review all drone and remaining travis configurations and test with daily-master-qa only - done by @phil-davis 2019-08-01
- [x] transifex will operate on master
- [x] update nightly scripts to build only nightly for `master` ( which is then stable10 ) - https://github.com/owncloud/administration-internal/pull/149
- [x] build only containers for nightly master
- [x] smashbox && update-testing only for master
- [x] app acceptance tests no longer against core `stable10` - just against "new" core `master` and latest core release (see long list of linked PRs below)
- [x] keep user_management in core for now - app can be split again later - if necessary
- [ ] remove encryption app - https://github.com/owncloud/core/pull/35949

## Benefits
- no waste of time with backporting master -> stable10
- no more translation backports
- far less jobs on drone

**Comment by patrickjahns** [comment]
Some aspect to add:
- [ ] update nightly scripts to build only nightly for `master` ( which is then stable10 )
- [ ] build only containers for nightly master
- [ ] smashbox && update-testing only for master

**Comment by phil-davis** [comment]
"move current master branch to master-old - just for the sake of not loosing anything"
good - because I keep finding "goodies" in the current core `master` that are useful to have and still should be back-ported (e.g. after "drop PHP 7.0")

**Comment by phil-davis** [comment]
Apps that were separated from `core` in the "old core master", but never got into a release like that:
- [ ] `user_management`
- [ ] `encryption`

what to do about those app repos?

**Comment by DeepDiver1975** [comment]
for the sake of keep it simple and be safe: just keep the apps in core and archive these two repos - in a later stage we can still continue to split them off .... objections?

**Comment by phil-davis** [comment]
How to remove deprecated code/interfaces/stuff in the future?
e.g. https://github.com/owncloud/core/pull/32051#issuecomment-509196336 
#32051 is in `master` only awaiting "`v11`"

**Comment by DeepDiver1975** [comment]
v11 will not happen - so no removing of deprecated constructs

**Comment by patrickjahns** [comment]
@DeepDiver1975 
Regarding `encryption` we currently have the majority of test run for owncloud+encryption in the encryption repository - I would vouch for removing encryption from stable10. 

For a release we can bundle the encryption app again - ( I believe we are doing that currently for master-qa tarballs already )

**Comment by DeepDiver1975** [comment]
> - I would vouch for removing encryption from stable10.

agreed - please update description on top accordingly - THX

**Comment by phil-davis** [comment]
https://github.com/owncloud/core/pull/32060#issuecomment-480874274
@PVince81 wrote only back in April:
```
no backport. we'll use master in the future for releases
```
how life changes ;)

**Comment by phil-davis** [comment]
Note: there was some problem with JS tests in master yesterday - issue #35860 - and it was not immediately obvious what happened in drone. The JS tests job has been disabled in drone - PR #35861 
If we do not archive core `master` then we will need to follow-up that issue and spend time to sort out what happened.

**Comment by DeepDiver1975** [comment]
Oh - we shall bring changes like this into stable10 then for 10.3 ... https://github.com/owncloud/core/pull/32060

**Comment by DeepDiver1975** [comment]
All tasks done -> close.

Awesome! THX @phil-davis @patrickjahns and all others involved! :beers:
