### ISSUE TITLE
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.owncloud.org/download/repositories/production/Debian_9.0

### ISSUE THREAD

**Issue by icerootsvw** [owncloud/core#35772]
### Steps to reproduce
wget -nv https://download.owncloud.org/download/repositories/production/Debian_9.0/Release.key -O Release.key
apt-key add - < Release.key
echo 'deb http://download.owncloud.org/download/repositories/production/Debian_9.0/ /' > /etc/apt/sources.list.d/owncloud.list
apt-get update

### Expected behaviour
getting the newest Repo information

### Actual behaviour
apt-get update
...
...

Err:8 http://download.owncloud.org/download/repositories/production/Debian_9.0  Release.gpg
  The following signatures were invalid: DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B
Fetched 1086 B in 0s (3070 B/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.owncloud.org/download/repositories/production/Debian_9.0  Release: The following signatures were invalid: DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B
W: Failed to fetch http://download.owncloud.org/download/repositories/production/Debian_9.0/Release.gpg  The following signatures were invalid: DDA2C105C4B73A6649AD2BBD47AE7F72479BC94B
W: Some index files failed to download. They have been ignored, or old ones used instead.

### Server configuration
Debian 9 (latest Updates)

**Comment by flyingstar16** [comment]
Same problem here

**Comment by icerootsvw** [comment]
seems to be fixed

root@bbclnx-oc:/home/mbasse# export LC_ALL=C
root@bbclnx-oc:/home/mbasse# apt-get update && apt-get dist-upgrade 
Ign:2 http://ftp2.de.debian.org/debian stretch InRelease                                                                             
Hit:3 http://cdn-fastly.deb.debian.org/debian-security stretch/updates InRelease                                                     
Hit:4 http://ftp2.de.debian.org/debian stretch-updates InRelease                             
Hit:5 http://ftp2.de.debian.org/debian stretch Release                   
Hit:6 http://ftp.de.debian.org/debian stretch-backports InRelease
Ign:1 https://attic.owncloud.com/org/download/repositories/production/Debian_9.0  InRelease
Hit:7 http://download.owncloud.org/download/repositories/production/Debian_9.0  Release
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  linux-image-4.9.0-7-amd64
Use 'apt autoremove' to remove it.
The following packages will be upgraded:
  owncloud-files
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/16.6 MB of archives.
After this operation, 16.4 kB disk space will be freed.
Do you want to continue? [Y/n]

**Comment by jnweiger** [comment]
Fixed by @crrodriguez 
Test install owncloud-files 10.2.1 on a debian 9.9 works fine for me again.
