### ISSUE TITLE
Gifs are not reproduced

### ISSUE THREAD

**Issue by davitol** [owncloud/core#35771]
Upload a GIF file and open it. Gifs appears static and does not move. It was shown with movement with old media app

(cc @felixheidecke )

**Comment by davitol** [comment]
JFYI 

1 - occ app:disable files_mediaviewer
2 - occ app:enable gallery
3 - Open again the gif file

**Test Result** GIF is animated

**Comment by davitol** [comment]
**using inspector tool, checked from which URL gif file is loaded opening the file from **Files view**:

### - Files mediaviewer

```
<img src="/remote.php/dav/files/admin/giphy.gif?c=3ca62927041bac723ef158bbee77df3a&amp;x=1920&amp;y=1920&amp;a=1&amp;preview=1" alt="giphy.gif" class="viewer__media viewer__media--image">
```

### - Gallery app

```
<img src="/apps/gallery/preview/148?width=2000&amp;height=2000&amp;c=3ca62927041bac723ef158bbee77df3a&amp;requesttoken=XDIbUS8%2FEy52DTFVLidyBh4CAX0bVz88cwBAEABZBlA%3D%3AoEh4DPvv2DigbAYWXxLNo4KQ6MvS50a9tkGDhqHeKx0%3D" alt="giphy.gif" style="position: absolute; background-color: rgb(255, 255, 255); background-size: 300px 225px; top: 87px; height: 225px; left: 810px; width: 300px; background-position: 0px 0px; transform: rotate(0deg); transform-origin: 50% 50% 0px;">
```

**Comment by DeepDiver1975** [comment]
The gallery added some special handling of gif and svg: https://github.com/owncloud/gallery/blob/e78614a29c096152b6168c0b68f1da656bcf4aa2/service/previewservice.php#L66
