### ISSUE TITLE
misleading javascript error, when client violates trusted domain setting

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#35800]
Server version 10.2.1RC2 and Win10 desktop client 2.6.0daily20190702.

The server host changed its ip address, the trusted domains setting in config.php was not updated. Now the client tries to connect to the new ip address and is greeted with a 
wrong error message about javascript:
![image](https://user-images.githubusercontent.com/1108546/61008895-29d57e00-a371-11e9-80be-cce699e24483.png)

The javascript error should not appear. The client is not a web browser.

(The wording of the actual trusted domains error is also misleading. Saying "from" may lead to the conclusion that the client ip address is at fault, which it is not.)

**Comment by ho4ho** [comment]
> The client is not a web browser.

https://github.com/owncloud/client/issues ?

**Comment by jnweiger** [comment]
Client only forwards a message misleading message generated by the server.
