### ISSUE TITLE
updatenotification app should consider upgrade.disable-web config value

### ISSUE THREAD

**Issue by cortho** [owncloud/core#35810]
User cs35 found out at https://central.owncloud.org/t/owncloud-upgrade-disable-web-working/20912 that when **upgrade.disable-web** is set to true in `config.php` the app still offers an update via web in the admin settings.

My guts say when an admin configures this value, no web updater should be active.

**Comment by phil-davis** [comment]
"when upgrade.disable-web is set to false"
don't you mean:
"when upgrade.disable-web is set to true" ?

**Comment by cs35-owncloud** [comment]
@phil-davis Hello indeed you're right, when you set upgrade.disable-web to true it displays the updater and should not.

**Comment by cortho** [comment]
Yes, I mixed it up. "when upgrade.disable-web is set to true" - fixed it in the issue.

**Comment by VicDeo** [comment]
Technically it's not.
1. update notification shows a section in admin area with a link to a standalone updater.
2. Standalone updater responsibility is to download a new OC package and replace the current sources with new sources.
3. Then core Upgrade is triggered, it could be done from Web UI or CLI

Initially `upgrade.disable-web` was added to prevent triggering upgrade process from Web UI at the 3rd step.

But it doesn't mean that we can't reconsider this switch...

**Comment by VicDeo** [comment]
<table>
<tr>
<th>
   Internal core upgrade
</th>
<th>
    Update notification app
</th>
</tr>
<tr>
<td>
New files are already in place <b>on this server</b>
</td>
<td>
New files are somewhere <b>on an update server</b> in a galaxy far, far away.
</td>
</tr>
<tr>
<td>
 OC <b>is not operable</b> as it presents an "Upgrade needed" page as a reply to any request
</td>
<td>
 OC <b>is fully operable</b> but shows "Open Updater" in admin area once these files are detected
</td></tr>
<tr>
<td>
`upgrade.disable-web` hides "Upgrade" button on this page 
  and suggests to use CLI instead
</td>
<td>
`upgrade.disable-web` is absolutely <b>irrelevant</b>
</td>
</tr>
</table>

**Comment by VicDeo** [comment]
ok. This was changed in https://github.com/owncloud/core/pull/39185

Now we have a different behavior for instances with 50+ users and instances with `upgrade.disable-web` set to `true`.
The former hides 'Upgrade' button on the core upgrade page 
While the latter hides both 'Upgrade' button on the core upgrade page and the 'Open Updater' button in the admin area.
