### ISSUE TITLE
Translation issue in 10.2.1 Public links Password enforcement

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#35816]
https://www.transifex.com/owncloud-org/owncloud/translate/#de/settings-1/137456632?q=text%3Aenforce

In languages de and de_DE

`enforce` should be translated to `erzwingen`

![image](https://user-images.githubusercontent.com/24212810/61114751-4a94f500-a491-11e9-8285-9e7ee3be1c86.png)

![image](https://user-images.githubusercontent.com/24212810/61114778-584a7a80-a491-11e9-9524-20cb35f97638.png)

**Comment by DeepDiver1975** [comment]
![Screenshot from 2019-07-12 10-52-00](https://user-images.githubusercontent.com/1005065/61115611-20443700-a493-11e9-8379-f406f832e7b8.png)
