### ISSUE TITLE
Implement missing step definitions related to sharing permission checkboxes

### ISSUE THREAD

**Issue by skshetry** [owncloud/core#35846]
Implement steps that:
1. Given permission checkboxes are enabled/disabled at the moment for a given share. 
2. Also, make it able to check permissions before sharing (i.e when sharing), because, some permissions get set by default.
3. Check if checkboxes are interactable/clickable. (some permissions can be disabled). And, even if they are not clickable, what are the checkboxes set with?

**Comment by phil-davis** [comment]
Added to backlog for planning in current sprint, because we are wanting to improve sharing tests anyway. So it will be good to improve the webUI sharing test functionality when time/resources permit.
