### ISSUE TITLE
Port essential steps to core from richdocuments

### ISSUE THREAD

**Issue by skshetry** [owncloud/core#35845]
Some of the new steps in richdocuments (eg: https://github.com/owncloud/richdocuments/blob/757a1d93d50e4eb9b1ad2474cce6fa6c652125e7/tests/acceptance/features/bootstrap/SecureViewContext.php#L187 and https://github.com/owncloud/richdocuments/blob/757a1d93d50e4eb9b1ad2474cce6fa6c652125e7/tests/acceptance/features/bootstrap/SecureViewContext.php#L233) might be essential to have in core as well.

## Things to do
- [x] Port it to core (PR: https://github.com/owncloud/core/pull/35890 )
- [x] Remove them from `richdocuments` (PR: https://github.com/owncloud/richdocuments/pull/267)

**Comment by phil-davis** [comment]
@HariBhandari07 please have a look this week.
It will be good to have useful common acceptance test step code in core so that anything can use it.
