### ISSUE TITLE
DB conversion errors

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#35856]
### Steps to reproduce
1. run occ `db:convert-mysql-charset` 

### Expected behaviour
The right site would be this: https://doc.owncloud.com/server/admin_manual/configuration/database/linux_database_configuration.html

### Actual behaviour
 get redirected to this site for help https://doc.owncloud.org/server/10.1/go.php?to=admin-db-conversion
### Server configuration
**ownCloud version:** (see ownCloud admin page)
10.2.1

**Comment by DeepDiver1975** [comment]
why was this moved to core? it is the job of the php script in the documentation to redirect to the correct place.
We don't want to change explicit doc link in the code base over and over again - that's why we have this redirect script in place.

Or do I missunderstand the reason for this issue?

**Comment by voroyam** [comment]
In the docs issue it was told to me that this issue belongs to core.

> it is the job of the php script in the documentation to redirect to the correct place.

can you point me to that script where the change has to be made?

**Comment by DeepDiver1975** [comment]
Before the doc rewrite this was in the doc repo

**Comment by voroyam** [comment]
@settermjd do you know where it is?

**Comment by tboerger** [comment]
It's part of the documentation deployment in gitea.

**Comment by voroyam** [comment]
So it's not in GitHub in the docs repo?

@tboerger if you know where it is, can you point me to it so I can change it? Basically it's just a link change, from the one to another, as described in my original post. Don't know why it's so hard to do.

**Comment by VicDeo** [comment]
https://github.com/owncloud/core/blob/master/core/Command/Db/ConvertMysqlToMB4.php#L70
https://github.com/owncloud/core/blob/a5c3115c5a1b870204c214e67e60d4b8743d5ecd/lib/private/legacy/defaults.php#L286-L291

**Comment by VicDeo** [comment]
ah,  sorry, it's rather doc server relevant.

**Comment by tboerger** [comment]
https://gitea.owncloud.services/devops/websites/src/branch/master/ansible/roles/docs/templates/config.j2#L519-L1899

**Comment by VicDeo** [comment]
https://doc.owncloud.org/server/{VERSION}/go.php?to=admin-db-conversion
redirects to 
https://doc.owncloud.org/server/{VERSION}/admin_manual/configuration/database/db_conversion.html
now. closing.
