### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by lexo-mfleuti** [owncloud/core#35913]
When goup sharing is disabled and someone tries to group share something the error message is shown:

`Group sharing is now allowed`

The message should be instead:

`Group sharing is **not** allowed`

![group sharing now allowed](https://user-images.githubusercontent.com/8611779/61773593-553a7d00-adf5-11e9-98c1-0a0f8873b99e.png)

What would also be nice would be a message like this:

**Group sharing is currently now allowed. If you like to change this [click](index.php/settings/admin?sectionid=sharing) here and enable the option "Allow sharing with groups".**

**Comment by DeepDiver1975** [comment]
🙈

**Comment by lexo-mfleuti** [comment]
Hehe, I know, you're gonna hate me for that :)

**Comment by phil-davis** [comment]
Typo was introduced in PR #23398 3 years ago

**Comment by phil-davis** [comment]
@lexo-mfleuti how do you get that error dialog to appear?

We have acceptance tests for when "Allow sharing with groups" is off, and the webUI does not display any group names when you type in the sharing panel box. So I could not purposely try to share with a group in the webUI.

**Comment by lexo-mfleuti** [comment]
Oh, seems to be more complicated after all. I thought it's very simple. This happens like this:

1. Group sharing allowed in settings
2. A folder is being shared to a group with certain permissions (e.g. all permissions except DELETE)
3. Group sharing is being disabled (so that noone can destroy the shared folders structure for security reasons
4. Administrator wants to change the permissions of the group, to which the folder has been shared already => This error message appears.

**Comment by phil-davis** [comment]
Thanks, that displays the dialog box.
When "Allow sharing with groups" is off, then existing shares continue to work. But you cannot make new shares with groups and you cannot edit the permissions of existing shares. You can completely delete an existing group share.
That sounds like a reasonable behaviour, so we just need to fix the typo (can do now) and add some tests (I will make an issue for that...)

**Comment by lexo-mfleuti** [comment]
Correct ;)
The behaviour is as expected. Basically just a typo and my recommendation to set the link to the settings-page in the dialog directly so that the user does not need to search for it.
