### ISSUE TITLE
Problem after update 

### ISSUE THREAD

**Issue by borgrat** [owncloud/core#35911]
### Steps to reproduce
1. go to my site cloud.in-edv.de
2. see the exception
3.

### Expected behaviour
Tell us what should happen

Update vom 10.1 to the actual Version

### Actual behaviour
Tell us what happens instead

Error ... the maintenance info was shown all the time

OC\RepairException: Upgrade is not possible
Reperaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Reperaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable wallpaper
Reperaturwarnung:For manually updating, see https://doc.owncloud.org/server/10.2/go.php?to=admin-marketplace-apps
Detaillierte Fehlermeldungen 
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet 
Reperaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Reperaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable wallpaper
Reperaturwarnung:For manually updating, see https://doc.owncloud.org/server/10.2/go.php?to=admin-marketplace-apps
OC\RepairException: Upgrade is not possible

### Server configuration
**Operating system**:
Ubuntu 14 lts

**Web server:**
apache

**Database:**
mysql

**PHP version:**
7.2.18

**ownCloud version:** (see ownCloud admin page)
cant login

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => 'ocf0grb868kz',
  'passwordsalt' => 'j1nwGaHGG6P8CkH+Ibx8nS1tQ2UW+l',
  'secret' => 'EL7SyRnEazA2LjtvejQlszVqltYnA0Y06DnV1eUMFRYZHlTJ',
  'trusted_domains' =>
  array (
    0 => 'cloud.in-edv.de',
  ),
  'datadirectory' => '/var/www/vhosts/in-edv.de/cloud.in-edv.de/data',
  'overwrite.cli.url' => 'https://cloud.in-edv.de',
  'dbtype' => 'mysql',
  'version' => '10.1.1.1',
  'dbname' => 'cloudinedv',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'cloudinedvserver',
  'dbpassword' => '$92Bake0~zbl2Q96Cflz_241',
  'logtimezone' => 'UTC',
  'installed' => true,
  'updater.secret' => '$2y$10$F6ZvJtfnRq248vKfEmdvDO132d9Hv3S6vYivMuy/FZvsxJQsbKgYK',
  'loglevel' => 2,
  'maintenance' => false,
  'theme' => '',
);

Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ho4ho** [comment]
Duplicate https://github.com/owncloud/core/issues/35858

**Comment by ho4ho** [comment]
Also see https://github.com/owncloud/docs/pull/1549, https://doc.owncloud.org/server/admin_manual/maintenance/manual_upgrade.html#review-third-party-apps, https://doc.owncloud.com/server/admin_manual/configuration/general_topics/general_troubleshooting.html#disable-3rdparty-non-shipped-apps
