### ISSUE TITLE
ownCloud 10.2.0 Does not allow to view files with spaces in the file name

### ISSUE THREAD

**Issue by rovjorge** [owncloud/core#35920]
### Steps to reproduce
1. Login to webUI
2. All your files with spaces in the filename are visible
3. Try to view pdf, txt or renaming that files with in webUI fails with an exception about URI not in base uri (the filename in the URI is lost!).

Function getRequestUri in lib/private/AppFramework/Http/Request.php is malforming Uri when the file has spaces in the name. Commenting line 610 solved the issue for me.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: FreeBSD

**Web server:** Apache 2.4

**Database:** mysql

**PHP version:** 7.2.20

**ownCloud version:** 10.2.0

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** binary packages

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by rovjorge** [comment]
#Signing status (ownCloud 9.0 and above):



Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- lib/private/AppFramework/Http/Request.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/private/AppFramework/Http/Request.php] => Array
                        (
                            [expected] => d563cc11da689aa6f27ade394da95f51ed02b4cd8549e7f61b9ae85a68dbd236953835688cc40af58c9cf8e337efd47ffc0b0e86c83b9ca9657a6bd709f9eff3
                            [current] => 06955bcfc6d34f9e4c2d2c17d7263304e071f9ba4c51a90353539f96afe3911469cda3666f36fd6d7a10a5db447446a34915b3068713e370f43a172720e15d8e
                        )

                )

        )

)

**Comment by phil-davis** [comment]
Please fill in the top of the issue template. Specially "steps to reproduce" - how exactly are you trying to view the file (e.g. downloading it on the webUI, getting it with some client and opening it, using some app like gallery or PDF viewer to display it in the browser or...)?

**Comment by davitol** [comment]
Works fine for me. Files with spaces in the file name are shown OK and can be renamed in 10.2.0 version. @rovjorge were you able to solve your issue? I think it is probably related to the server and not to ownCloud

**Comment by rovjorge** [comment]
To work for me. I had to comment out line 610 from the Function "getRequestUri" in lib/private/AppFramework/Http/Request.php

**Comment by rovjorge** [comment]
If you type in browser:
https://example.com/owncloud/remote.php/webdav/ownCloud%20Manual.pdf

$server['REQUEST_URI'] is "/owncloud/remote.php/webdav/ownCloud%20Manual.pdf"
$server['SCRIPT_NAME'] is "/owncloud/remote.php/webdav/ownCloud Manual.pdf"

the function $this->getScriptName() is "/owncloud/remote.php"

Two issues around here:
1. SCRIPT_NAME is not urlencoded.
2. the \substr() part removes webdav/owncloud%20Manual.p from $uri variable.

Which variable is wrong at this point?

**Comment by rovjorge** [comment]
@davitol, you are right the issue was caused by the server configuration, I am using php-fpm as php handler and the configuration that worked for me was explained in 
https://daemon-notes.com/articles/web/apache/php-fpm
and also following the documentation about authentication issues in 
https://central.owncloud.org/t/no-basic-authentication-headers-were-found-message/819
Thank you.
