### ISSUE TITLE
No upgrade 10.0.6 to 10.2.1 possible

### ISSUE THREAD

**Issue by hhaeb** [owncloud/core#35963]
### Steps to reproduce
1. Download unpack and symlink 10.2.1
2. sudo -u www-data php occ maintenance:mode --off
3. sudo -u www-data php occ upgrade

### Expected behaviour
Upgrade should run successfully

### Actual behaviour
Error: Upgrade is not possible
You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Reparaturwarnung:Please install or update the following apps manually or disable them with:
[a list of many apps including dav, federatedfilesharing, files, files_external]

### What i have tried:
sudo -u www-data php occ app:disable [list of many apps]
But some were not disabled:
sudo -u www-data php occ app:disable [dav, federatedfilesharing, files, files_external]
[dav, federatedfilesharing, files, files_external] can't be disabled

### What i have tried then:
edit info.xml of these apps
set max-version="10" to max-version="11"

### Actual state
same as at the beginning 
Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Repair warning: Please install or update the following apps manually or disable them with:
occ app:disable dav
occ app:disable federatedfilesharing
occ app:disable files
occ app:disable files_external

### Server configuration
**Operating system**: Ubuntu  16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.2

**ownCloud version:** 10.2.1

**Updated from an older ownCloud** 10.0.6

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "ocnx26nrsp2m",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "zweiflingen.de",
            "www.zweiflingen.de",
            "5.9.191.7"
        ],
        "datadirectory": "\/home\/zweiflingen2017\/oc",
        "dbtype": "mysql",
        "version": "10.0.10.4",
        "dbname": "oc_zweiflingen",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": true,
        "overwrite.cli.url": "https:\/\/www.zweiflingen.de\/oc_zweiflingen",
        "has_internet_connection": true,
        "htaccess.RewriteBase": "\/oc_zweiflingen",
        "appstore.experimental.enabled": true,
        "theme": "",
        "loglevel": 2,
        "files_external_allow_create_new_local": "true",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "0": "\/tmp\/redis.sock",
            "port": 6379,
            "timeout": 0
        },
        "apps_paths": [
            {
                "path": "\/home\/zweiflingen2017\/owncloud-10.0.6\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/home\/zweiflingen2017\/owncloud-10.0.6\/owncloud\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "integrity.ignore.missing.app.signature": [
            "theme-example",
            "theme-zw-de"
        ]
    }
}

**List of activated apps:**

ownCloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - activity: 2.5.0
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - files: 1.5.1
  - files_external: 0.7.1
  - files_pdfviewer: 0.11.0
  - files_texteditor: 2.3.0
  - gallery: 16.1.1
  - market: 0.5.0
  - templateeditor: 0.4.0
  - theme-zw-de: 1.0.0
Disabled:
  - calendar
  - comments
  - configreport
  - encryption
  - external
  - federation
  - files_sharing
  - files_trashbin
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - notifications
  - provisioning_api
  - systemtags
  - theme-example
  - updatenotification
  - user_external

```

**Are you using encryption:** no

**Comment by DeepDiver1975** [comment]
> Reparaturwarnung:Please install or update the following apps manually or disable them with:
> [a list of many apps including dav, federatedfilesharing, files, files_external]
> ###

there is something wrong - these apps shall never be listed. 

I suspect that the apps did not properly get updated.

Please let us know if the issue still persists -> closing for now
