### ISSUE TITLE
Changing user/pwd on a SMB mount let the client redownoad all

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#35985]
### Steps to reproduce
1. Create an SMB mount with user/pwd
2. Let the client sync this mount locally
3. Change user/pwd of the SMB mount

### Expected behaviour
No resyncing of the client should happen, only if a change was recognized after rescanning.

### Actual behaviour
Full resync of the client of this SMB mount = redownloading all.
Core did not do a rescan of the SMB share.

The old user/pwd was full read/write while the new user/pwd had read only.

Note: it is not a client issue as core tells what to sync or not.

### Server configuration
**Operating system**: Ubuntu 18.04
**Web server:** nginx
**Database:** mariadb 10.4.7
**PHP version:** 7.2
**ownCloud version:** 10.2.1.4
**Updated from an older ownCloud or fresh install:** updated
**Where did you install ownCloud from:** tar
**Signing status (ownCloud 9.0 and above):** No errors have been found.

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oct7bkicorxf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxx",
            "xxxx",
            "xxxx"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/xxxx",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "10.2.1.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Vienna",
        "installed": true,
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "filesystem_check_changes": 1,
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "maintenance": false,
        "theme": "",
        "preview_max_scale_factor": 1,
        "excluded_directories": [
            ".snapshot",
            "~snapshot"
        ],
        "upgrade.automatic-app-update": true,
        "quota_include_external_storage": false,
        "singleuser": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "show_server_hostname": false
    }
}
```

**List of activated apps:**

```
Enabled:
  - activity: 2.5.0
  - audioplayer: 2.7.1
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.4.0
  - federatedfilesharing: 0.4.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_external_dropbox: 1.1.0
  - files_external_ftp: 0.2.1
  - files_mediaviewer: 1.0.0
  - files_pdfviewer: 0.11.0
  - files_sharing: 0.11.0
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - files_videoplayer: 0.10.1
  - firstrunwizard: 1.2.0
  - guests: 0.8.1
  - market: 0.5.0
  - notifications: 0.5.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.4.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_clipboard
  - user_external
  - user_ldap
```

**Are you using external storage, if yes which one:** local/smb/sftp/dropbox/googledrive
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera
**Operating system:** W10x64

#### Web server error log
```
no relevant entries
```

#### ownCloud log (data/owncloud.log)
```
no relevant entries
```

#### Browser log
```
no relevant entries
```

**Comment by DeepDiver1975** [comment]
because changing the user can have an impact on the access of folder this is seen as a full change of the whole file structure.

I understand that this feel unnecessary but adding more logic here is our of scope in the current state of the product. There are no plans to extend functionalities at the moment. Sorry

Closing this therefore :wave:

**Comment by mmattel** [comment]
Totally agree, but then it should invalidate (remove) all files mounted AND rescan it.
Currently it invalidates only which could result in strange behaviour when not rescanned!
