### ISSUE TITLE
Share Notifications API

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#35983]
## Background
In Phoenix shared links shall be send via email. Therfore an api is missing.

There is a notify route already:

https://github.com/owncloud/core/blob/5ee2ac506181a52192889b511fe0f2be71bb3780/apps/files_sharing/appinfo/routes.php#L91

But it only handles emails to internal users (which is no longer needed?) @pmaier1 

oc10 uses the old ajax endpoint for sending emails

https://github.com/owncloud/core/blob/5ee2ac506181a52192889b511fe0f2be71bb3780/core/ajax/share.php#L81

## Actions
- Move logic from share.php over to a new ocs controller which handles email notifications (share20ocscontroller is already pretty hugh)
- decide if we still need the internal email notification mechanism
- add unit tests
- add acceptance tests
- add sdk api -> https://github.com/owncloud/owncloud-sdk/
- adjust oc10 web frontend to use the new api
- kill code in share.php

## Stretch Goal
- analyse if the fetch operation can be replaced with a call to the sharee api
https://github.com/owncloud/core/blob/5ee2ac506181a52192889b511fe0f2be71bb3780/core/ajax/share.php#L232

**Comment by pmaier1** [comment]
> But it only handles emails to internal users (which is no longer needed?) @pmaier1

Emails to internal users does not make much sense, yes, as you should rather use user shares for those.

**Comment by DeepDiver1975** [comment]
shall we kill the server side code for internal email delivery? if unused code shall be killed @pmaier1

**Comment by pmaier1** [comment]
> shall we kill the server side code for internal email delivery? if unused code shall be killed @pmaier1

I don't know whether this is needed somewhere. Would need more background / grasp the whole picture.

**Comment by DeepDiver1975** [comment]
The question is: shall we kill this feature
![Screenshot from 2019-08-14 16-31-26](https://user-images.githubusercontent.com/1005065/63029534-08583c80-beb1-11e9-984f-8daa186a7a70.png)
![Screenshot from 2019-08-14 16-31-06](https://user-images.githubusercontent.com/1005065/63029535-08583c80-beb1-11e9-9c63-dcd5645d14d3.png)

**Comment by pmaier1** [comment]
Ahh, I didn't get that one. I thought this issue is about public links and their "send via mail" functionality?!

The above one is still needed for the following reason:
We don't have proper share notifications. Users only get a notification via mail if Pending Shares is enabled. If Pending Shares is disabled, the above is the only way for users to notify others via mail.

Please keep it until we have regular notifications for sharing.

**Comment by karakayasemi** [comment]
Raised a ticket for last missing action on owncloud-sdk repo: https://github.com/owncloud/core/issues/35983
