### ISSUE TITLE
Changing the DAV:displayname of the “calendar-proxy-read|-write” WebDAV resources

### ISSUE THREAD

**Issue by dilyanpalauzov** [owncloud/core#35981]
OwnCloud/CardDAV operates with a “calendar-proxy-read|-write” WebDAV resources.

WebDAV resources have address/URL and a [DAV:displayname property](https://tools.ietf.org/html/rfc4918#section-15.2).

Does the handling of this property depend any on the display name?  What will happen, if a CUA changes the display name property?  Will the server reject this change or might some client break?

**Comment by DeepDiver1975** [comment]
the displayname shall not be considered as any identifier. the uri itself is enough to identify a principal. in owncloud the principal url never changes

**Comment by dilyanpalauzov** [comment]
Do ownCloud Notes depend on the DAV:displayname property?

**Comment by dilyanpalauzov** [comment]
According to https://gitlab.gnome.org/GNOME/evolution/merge_requests/38#note_572704 the “Notes” shall not be localized or changed.  The general question is, can WebDAV software always change the DAV:displayname property?  In my understanding it can.

**Comment by DeepDiver1975** [comment]
I'm missing the link between notes and webdav ...

**Comment by DeepDiver1975** [comment]
general question - not a bug - further discussion shall happen on https://central.owncloud.org
