### ISSUE TITLE
Mi

### ISSUE THREAD

**Issue by aiuen** [owncloud/core#35992]
Hello everybody

I have a problem downloading latest Zip/Tar file with ownCloud.

Steps to reproduce
1. Go to https://owncloud.org/download/
2. Try to download:
https://download.owncloud.org/community/owncloud-10.2.1.tar.bz2
or
https://download.owncloud.org/community/owncloud-10.2.1.zip

### Expected behaviour
File download

### Actual behaviour
ERR_CONNECTION_TIMED_OUT

**Comment by phil-davis** [comment]
It is working for me now. There were some problems with one of the download mirrors a few hours ago - you might have been unlucky. Please try again.
