### ISSUE TITLE
Quiet the lockbot

### ISSUE THREAD

**Issue by evert** [owncloud/core#35994]
Is there a way to silence the lockbot? I tried blocking the user, but it's not really doing anything. I get an average of 2-3 messages per day now, and it's a little annoying. I can also fully mute the owncloud project but it felt a little drastic.

**Comment by DeepDiver1975** [comment]
I was looking for such an option my self already - I receive hundreds of notifications ... :see_no_evil:

**Comment by DeepDiver1975** [comment]
One option can be to add no comment .... see

https://github.com/dessant/lock-threads/issues/6
https://github.com/vuetifyjs/vuetify/commit/b3bd35be307691586b5a7991143b973648f0d2c1

**Comment by phil-davis** [comment]
I was trying Octobox and raised this issue: https://github.com/octobox/octobox/issues/1971

Although Octobot is not yet smart enough to have a view of which user/bot made the comment that caused the notification, it can filter on notifications from locked issues. See their suggestion https://github.com/octobox/octobox/issues/1971#issuecomment-519205192

So you can filter to show all those locked-issue notifications and then mark all as read, or delete all. Or you can filter on "not locked" to see notifications that you might care about.

![Screenshot_2019-08-08 Octobox](https://user-images.githubusercontent.com/1535615/62668511-e3913000-b9ab-11e9-8cef-126e8cc56b01.png)

**Comment by JohnRoesler** [comment]
Does the bot have a github username it authenticates with? It looks like you could block notifications from a specific user on github, but I can't seem to find the bot as `lock`.
