### ISSUE TITLE
core/js/oc.js no browser cache

### ISSUE THREAD

**Issue by cs35-owncloud** [owncloud/core#35993]
Hello,

I've noticed that the expires header was wrong and would never be cached on the browser side for the **core/js/oc.js**. You can check it on the [demo](https://demo.owncloud.org/core/js/oc.js?v=76ba50c7814f7bc1da4559dc09f86d95). It seems it's hard coded in **core/js/config.php** at **line 45/46**. Is it possible to remove the no caching or at least set an expires that is useful at some point (or an other mechanism to invalidate the cache)  ? It would also be great to minify the js but this point would be great for all the ressources, for example [underscore.js](https://demo.owncloud.org/core/vendor/underscore/underscore.js?v=76ba50c7814f7bc1da4559dc09f86d95).

Thanks.

**Comment by DeepDiver1975** [comment]
This js File holds dynamic Data as well as user specific data. It shall never be cached.

**Comment by cs35-owncloud** [comment]
Yes I agree also the content changes only when you login/logout, change your personal/admin settings. For a lambda user simply browsing files, uploading, it seems there is no modification. But agreed it seems like a chore to deal with a cache for a little improvement. Nevertheless minification would really be a plus.

Thanks.

**Comment by DeepDiver1975** [comment]
> Nevertheless minification would really be a plus.

The owncloud frontend is based on really old techniques - we will not add any major changes here.
The new frontend (codename phoenix) will take care of such stuff.

**Comment by cs35-owncloud** [comment]
Understood, thanks for your answer and your time !
