### ISSUE TITLE
scality fails to start in new drone

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36002]
Since the updated drone last night, the phpunit+scality matrix job always fails.
The scality server gets errors starting: https://drone.owncloud.com/owncloud/core/20030/24/2
```
Host name has been modified to scality
Note: In your /etc/hosts file on Linux, OS X, or Unix with root permissions, make sure to associate 127.0.0.1 with scality
> s3@7.4.0 start /usr/src/app
> npm-run-all --parallel start_dmd start_s3server
> s3@7.4.0 start_dmd /usr/src/app
> npm-run-all --parallel start_mdserver start_dataserver
> s3@7.4.0 start_s3server /usr/src/app
> node index.js
> s3@7.4.0 start_dataserver /usr/src/app
> node dataserver.js
> s3@7.4.0 start_mdserver /usr/src/app
> node mdserver.js
assert.js:84
throw new assert.AssertionError({
^
AssertionError: bad location constriant: "gcpbackend" serviceCredentials keyFilename and/or both serviceEmail and serviceKey must be set in locationConfig or environment variable
at gcpLocationConstraintAssert (/usr/src/app/lib/Config.js:98:12)
at Object.keys.forEach.l (/usr/src/app/lib/Config.js:243:13)
at Array.forEach (native)
at locationConstraintAssert (/usr/src/app/lib/Config.js:163:38)
at Config._getLocationConfig (/usr/src/app/lib/Config.js:301:9)
at new Config (/usr/src/app/lib/Config.js:284:14)
at Object.<anonymous> (/usr/src/app/lib/Config.js:1017:13)
at Module._compile (module.js:577:32)
at Object.Module._extensions..js (module.js:586:10)
at Module.load (module.js:494:32)
at tryModuleLoad (module.js:453:12)
at Function.Module._load (module.js:445:3)
at Module.require (module.js:504:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/usr/src/app/lib/utilities/logger.js:3:40)
at Module._compile (module.js:577:32)
npm ERR! Linux 4.15.0-54-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "run" "start_s3server"
npm ERR! node v6.14.2
npm ERR! npm v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! s3@7.4.0 start_s3server: `node index.js`
npm ERR! Exit status 1 
```

We are trying to track down what is different in the new drone environment, but no joy yet.

I suggest that we take out this matrix entry for now, so that CI can pass. And investigate tomorrow...

**Comment by phil-davis** [comment]
ToDo when resolving this issue:

- [ ] put back core scality test matrix (reverse commit from #35999 )
- [ ] put back firewall scality test matrix (reverse https://github.com/owncloud/firewall/pull/583 )

**Comment by patrickjahns** [comment]
I highly doubt this has something to do with the container itself - however we could try to use one of the recent upstream containers at https://hub.docker.com/r/zenko/cloudserver/

( scality/s3server has been renamed/rebranded to zenko/cloudserver )

**Comment by phil-davis** [comment]
I agree - there "must" be some difference in the drone environment. It is expecting `"gcpbackend" serviceCredentials ` which it never did before. Somehow it is deducing something different about its run-time environment.

**Comment by patrickjahns** [comment]
So the problem is, that with drone 1.0 additional env variabels are populated in the containers.

So is the variable `CI=true` - apparently that is something that scality server does not like

**Comment by patrickjahns** [comment]
New image at https://hub.docker.com/r/owncloudci/scality-s3server should resolve all issues - please confirm

**Comment by phil-davis** [comment]
Fixed
