### ISSUE TITLE
activity app loading forever when affected group was deleted

### ISSUE THREAD

**Issue by 3dmedium** [owncloud/core#36010]
First of all, this is a duplicate of:
#29964

The issue still persists with newer versions.
Should be simple to fix for someone who knows the code.

Steps to reproduce
Share File with group
Delete Group
View Activity

Expected behaviour
Should load activities

Actual behaviour
There is a loading circle forever

Server configuration
Operating system: Linux Ubuntu 18.04 LTS

Web server: Apache/2.4.18 (Ubuntu)

Database: MySQL

PHP version: PHP v7.2.19-0ubuntu0.18.04.1

ownCloud version: 10.2.0 (stable)

Updated from an older ownCloud or fresh install: updated

Where did you install ownCloud from: owncloud official download

Signing status (ownCloud 9.0 and above): no problems
No errors have been found.

The content of config/config.php:

{
"system": {
"instanceid": "REMOVED SENSITIVE VALUE",
"passwordsalt": "REMOVED SENSITIVE VALUE",
"secret": "REMOVED SENSITIVE VALUE",
"trusted_domains": [
"REMOVED SENSITIVE VALUE"
],
"datadirectory": "/var/www/owncloud/data",
"overwrite.cli.url": "REMOVED SENSITIVE VALUE",
"dbtype": "mysql",
"version": "10.2.0",
"dbname": "REMOVED SENSITIVE VALUE",
"dbhost": "localhost",
"dbtableprefix": "REMOVED SENSITIVE VALUE",
"dbuser": "REMOVED SENSITIVE VALUE",
"dbpassword": "REMOVED SENSITIVE VALUE",
"logtimezone": "UTC",
"installed": true,
"loglevel": 0,
"log.condition": {
"apps": [
"files"
]
},
"filelocking.enabled": true,
"memcache.local": "\OC\Memcache\APCu",
"memcache.locking": "\OC\Memcache\APCu",
"activity_expire_days": 3650,
"maintenance": false
}
}

Client configuration
Opera, Chrome, IE, Edge

Operating system:
Win / Mac

Logs
Web server error log
{"reqId":"5YLGesgOqpL3WCdWLaC2","level":3,"time":"2017-12-22T10:47:17+00:00","remoteAddr":"XXXXXXXXX","user":"XXXXXXXXX","app":"index","method":"GET","url":"\/index.php\/apps\/activity\/api\/v2\/activity\/all?format=json&previews=true&since=0","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function getDisplayName() on null\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/Parameter\\\/Parameter.php(82): OCA\\\\Activity\\\\Formatter\\\\GroupFormatter->format(Object(OC\\\\Activity\\\\Event), 'GROUP NAME....')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/DataHelper.php(87): OCA\\\\Activity\\\\Parameter\\\\Parameter->format()\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/DataHelper.php(129): OCA\\\\Activity\\\\DataHelper->translation('files_sharing', 'shared_group_se...', Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/GroupHelper.php(207): OCA\\\\Activity\\\\DataHelper->formatStrings(Array, 'subject')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/Data.php(287): OCA\\\\Activity\\\\GroupHelper->getActivities()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/Controller\\\/OCSEndPoint.php(209): OCA\\\\Activity\\\\Data->get(Object(OCA\\\\Activity\\\\GroupHelper), Object(OCA\\\\Activity\\\\UserSettings), 'XXXXXXXXX', 0, 0, 'desc', 'all', '', 0)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/Controller\\\/OCSEndPoint.php(181): OCA\\\\Activity\\\\Controller\\\\OCSEndPoint->get(Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/Controller\\\/EndPoint.php(68): OCA\\\\Activity\\\\Controller\\\\OCSEndPoint->getFilter(Array)\\n#8 [internal function]: OCA\\\\Activity\\\\Controller\\\\EndPoint->getFilter('all')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Activity\\\\Controller\\\\EndPoint), 'getFilter')\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(98): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Activity\\\\Controller\\\\EndPoint), 'getFilter')\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('EndPointControl...', 'getFilter', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#13 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(307): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(928): OC\\\\Route\\\\Router->match('\\\/apps\\\/activity\\\/...')\\n#16 \\\/var\\\/www\\\/owncloud\\\/index.php(56): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/Formatter\\\/GroupFormatter.php\",\"Line\":44}"}

**Comment by 3dmedium** [comment]
I was able to fix this by modiieing the file:
apps/activity/lib/Formatter/GroupFormatter.php

` public function format(IEvent $event, $parameter) {
                $group = $this->groupManager->get($parameter);

                 // fix for  https://github.com/owncloud/core/issues/36010
                // if there was no Group with name $parameter in Database, return the name and mark as deleted Group.  
                if($group === null){
                         return '<parameter>Deleted Group: ' .  Util::sanitizeHTML($parameter)  . '</parameter>';
                }

                $displayName = $group->getDisplayName();
                return '<parameter>' . Util::sanitizeHTML($displayName) . '</parameter>';
        }
}
`

**Comment by 3dmedium** [comment]
seems to be fixed by:
https://github.com/owncloud/activity/commit/e997aaac5f9d0a2acb55e13a09127db20f4e7abc#diff-09b9bc49ede06fc506b36b40e1f94ece

but not yet available with updates

**Comment by ho4ho** [comment]
> seems to be fixed by:
> owncloud/activity@e997aaa#diff-09b9bc49ede06fc506b36b40e1f94ece

Close as not problem by ownCloud but by activity app in different issue tracker?

**Comment by individual-it** [comment]
@3dmedium please report issue here https://github.com/owncloud/activity/issues and also your fix as PR
