### ISSUE TITLE
Federated share discovery manager always prioritize https even if http was explicitly requested

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#36035]
### Steps to reproduce
Happened while running acceptance tests in an http environment:
```
TEST_SERVER_URL=http://server BEHAT_SUITE=apiFederation TEST_EXTERNAL_USER_BACKENDS=false make test-acceptance-api TESTING_REMOTE_SYSTEM=false
```
1.
2.
3.

### Expected behaviour
Tests pass, no problems found

### Actual behaviour
The discovery manager fails to fetch the appropiate endpoint due to an invalid https certificate in the remote server.
```
Could not share file/folder! message: "cURL error 60: SSL certificate problem: self signed certificate"
```
Note that http was requested, so there shouldn't be a request made through https. Although the request is attempted through https, there is no retry through http.

The problem seems to be in https://github.com/owncloud/core/blob/master/apps/federatedfilesharing/lib/Notifications.php#L334 where the request fails with an ssl exception that isn't catched.

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:** apache 2.4.7

**Database:** mysql

**PHP version:** 7.1

**ownCloud version:** 10.3.0 pre alpha (098ea19bde5ff718d3d412a657fed76e3aa22bdf)

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by VicDeo** [comment]
@jvillafanez this is by design.

**Comment by jvillafanez** [comment]
Can we have a switch at least? This will be a pain to test if we need valid ssl certificates. For me it's easier to test everything through http, so if everything is going through http except one piece, I don't want to spend half a day figuring out why I'm getting an invalid ssl certificate.

BTW, I think the fallback was active, but since the error happened during discovery, that code path doesn't use the fallback.

**Comment by VicDeo** [comment]
@jvillafanez 
> This will be a pain to test if we need valid ssl certificates

We don't need valid certs. OC has it's own cert storage and our acceptance tests use self-signed certs successfully.
`occ security:certificates:import` on both instances to trust each other should do the trick

> error happened during discovery, that code path doesn't use the fallback.

it looks like real issue to me.
