### ISSUE TITLE
removing and recreating a user causes internal server error when the user is still active

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#36045]
Server 10.2.1, firefox browser.

When a user is removed from the system, he should be told so, when he tries to acess the system. Instead he may see an internal error.

Steps to reproduce:

* admin creates user Alice
* user Alice logs in on the web gui and sees her skeleton files.
* user Alice shortens the URL to the owncloud base URL and hits enter. She is returned to her folder view.
* admin deletes user Alice
* Alice clicks on folder 'Documents' and waits 10 seconds. She gets logged out and sees a login prompt on her web browser.
* admin creates user Alice without setting a password.
* (immediately within 10 seconds) user Alice shortens the URL to the owncloud base URL and hits enter. She gets an internal server error.

![image](https://user-images.githubusercontent.com/1108546/63104809-f1cce680-bf7f-11e9-9eaa-3ded41d528a9.png)

**Comment by DeepDiver1975** [comment]
I prefer to mark this as wont-fix. This is a super rare scenario. The underlying issue is that we require the explicit login of the user to boot strap the user's data folder.

The data folder was killed by removing the user

**Comment by jnweiger** [comment]
I agree that this is extremely rare in real live. But it happens when testing. To reset to clean scenario preconditions, it seemed a natural thing to delete and recreate the involved users. We'll ignore orworkaround these errors then...
