### ISSUE TITLE
new public webdav API returns "201" when uploading to a user that is over quota but saves an empty file

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#36056]
### Steps to reproduce
1. create a public link with upload permissions of a folder from a user that is already over quota
2. use the new public link webdav API to upload a file to that folder e.g. `curl -X PUT http://localhost/owncloud-core/remote.php/dav/public-files/0M2kxLVbYuIOSPZ/12348.txt -d "my data" -v`

### Expected behaviour
`HTTP/1.1 507 Insufficient Storage`

### Actual behaviour
`HTTP/1.1 201 Created`
an empty file is created

**Comment by DeepDiver1975** [comment]
1. quotaPlugin is not loaded - needs refactoring :see_no_evil: 
2. a failing write operation is not handled
