### ISSUE TITLE
Users and groups are mixed when sharing a resource 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/core#36069]
Windows 10
Client: 2.6.0daily20190820 (build 12286)
Server: 10.3.0 alpha

Preconditions:
1) Create a user called test
2) Create a user called bob
3) Put bob into a group called test

Steps to recreate:
1) Right click on a file in Windows Explorer
2) Select ownCloud submenu
3) Select Share
4) Type 'test' and select the user called test
5) Type 'test' and select the group called test

Actual result: Path already shared with this group
Expected result: Resource has been shared with the group 

Client log:
08-20 13:51:00:596 [ warning gui.sharing.ocs ]:	Reply to "POST" QUrl("http://10.42.16.185:8080/ocs/v1.php/apps/files_sharing/api/v1/shares") (QPair("reshares","true"), QPair("path","/New shared file 1 - Copy.txt"), QPair("shareType","1"), QPair("shareWith","hana"), QPair("permissions","19")) has unexpected status code: 403 "{\"ocs\":{\"meta\":{\"status\":\"failure\",\"statuscode\":403,\"message\":\"Path already shared with this group\",\"totalitems\":\"\",\"itemsperpage\":\"\"},\"data\":[]}}"
08-20 13:51:00:596 [ warning gui.sharing ]:	Sharing error from server 403 "Path already shared with this group"

**Comment by individual-it** [comment]
@HanaGemela thank you for reporting the issue, it looks to me like a client issue.
Would you mind reporting it again in https://github.com/owncloud/client ?

**Comment by HanaGemela** [comment]
@individual-it it also happens in webUI

**Comment by phil-davis** [comment]
IMO this is a duplicate of #35488 ?
I added comment https://github.com/owncloud/core/issues/35488#issuecomment-523783063

**Comment by HanaGemela** [comment]
Yeah, it is duplicate
