### ISSUE TITLE
new public link webdav API does not obey "OC-Autorename" header

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#36065]
### Steps to reproduce
1. create a public link of a folder with "Download / View / Edit" or "Download / View / Upload" permissions
2. upload a file with an existing name to that folder via new public link webdav API and set the `OC-Autorename: 1` header

### Expected behaviour
a new file with attached `(2)` should have been created

### Actual behaviour
in case of "Download / View / Edit" permissions, the original file gets overwritten
in case of "Download / View / Upload" permissions the upload is not possible:
```
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Node with name '123.txt' could not be found</s:message>
</d:error>
```

CC @DeepDiver1975

**Comment by DeepDiver1975** [comment]
>     2\. he `OC-Autorename: 1` header

Is not supported on the new endpoint - auto renaming is handled on files drop folders implicitly

**Comment by individual-it** [comment]
so it works as expected?
closing this issue?

**Comment by individual-it** [comment]
now I know why the automated tests were failing, there is an off-by-one error https://github.com/owncloud/core/issues/36067
