### ISSUE TITLE
Is the CORS white listing working for simple request?

### ISSUE THREAD

**Issue by frlanxpertiz** [owncloud/core#36070]
### Steps to reproduce
1. configure owncloud to have "cors.allowed-domains": "https:\/\/example.com"
2. configure a page to include an iframe with src="owncloud.example.com/s/zhdavdjaz"
3. load the page

### Expected behaviour
the return header should include Access-Control-Allow-Origin: https://example.com  

### Actual behaviour
without the header the browser refuse to load the content

If I understand correctly from this [link](https://www.moesif.com/blog/technical/cors/Authoritative-Guide-to-CORS-Cross-Origin-Resource-Sharing-for-REST-APIs/#) for a simple request the only thing missing is the header part. However it looks like [here](https://github.com/owncloud/core/blob/2de709ee929ff8ffd480019c82e09929134ad41d/lib/public/AppFramework/ApiController.php#L85) that owncloud only send this header for a preflighted request. Is there something that i'm missing in the owncloud configuration?
______________________________________________________________________________________
### Server configuration
**Operating system**:
Linux
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.2.17-0ubuntu0.18.04.1
**ownCloud version:** (see ownCloud admin page)
10.2.1.4
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
docker
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

https://gist.github.com/frlanxpertiz/6ecf0fde85e3ea033755b277b2b8a7e5

**List of activated apps:**

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
chrome
**Operating system:**
windows 10

**Comment by DeepDiver1975** [comment]
>     2\. configure a page to include an iframe with src="owncloud.example.com/s/zhdavdjaz"

iframeing is disallowed by our CSP setup - this is unrelated to CORS

Please note that we only track real issues/bugs/feature requests in here.
For support questions please use https://central.owncloud.org

THX

**Comment by frlanxpertiz** [comment]
Ok thanks for the info, I will create a thread on central.owncloud. Just a head up though, the CSP header i receive when going on my owncloud instance doesn't include the frame-ancestors parameter so that mean that including owncloud in a iframe on another website shouldn't be blocked, at least by the CSP policy, see [this](https://www.w3.org/TR/CSP2/#directive-frame-ancestors)
