### ISSUE TITLE
[new public webdav] public can download file from upload-only folder if filename is known

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#36076]
### Steps to reproduce
1. share a folder as "Upload Only" as public link
2. download a file from that folder using the new webdav public link api

### Expected behaviour
download should not be possible

### Actual behaviour
download is possible

**Comment by VicDeo** [comment]
@individual-it this is what I have when I try to follow :
```
curl --silent http://localhost/~deo/oc-tmp/remote.php/dav/public-files/1HRNgzXAvVOr07C -H 'X-Requested-With:XMLHttpRequest' -H "Range:bytes=0-150" -X GET
This is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client.
```
What I am missing here?
