### ISSUE TITLE
work through the trashbin tests and see which ones need tests for both webdav versions

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#36108]
the trashbin API only works on the "new" webdav path
Check the current tests and eliminate those that do not really need be run on both old/new webdav API path

**Comment by phil-davis** [comment]
@dpakach did we review these trashbin API combinations already in another issue?

**Comment by dpakach** [comment]
> @dpakach did we review these trashbin API combinations already in another issue?

@phil-davis I'm currently working on it. The issue is #36302. I think we can close this one.
