### ISSUE TITLE
Config switch to disable tech preview APIs

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#36118]
The following beta APIs must be disabled by default:
- Webdav Trashbin API
- New Public Webdav endpoint

These APIs are not ready to use in production so they should not be exposed.

For Phoenix development, the switch should be enabled, so we need to update the README.

**Comment by PVince81** [comment]
Might need to also adjust acceptance tests to enable said switch in their setup.

**Comment by phil-davis** [comment]
And add some acceptance tests that confirm the APIs do not respond when the switches are off.

**Comment by PVince81** [comment]
I consider this a release blocker for 10.3 as we don't want to expose those beta APIs

**Comment by PVince81** [comment]
as discussed with @hodyroff, it should be called "tech preview", not "beta".
