### ISSUE TITLE
sortout "uploadwriteonly" permission in acceptance tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#36114]
the "uploadwriteonly" permission seems not to be set correctly by the tests in
tests/acceptance/features/bootstrap/Sharing.php:111 it is defined as read and create

in tests/acceptance/features/bootstrap/Sharing.php:175 it claims to be 7 = read, create, update

in tests/TestHelpers/SharingHelper.php:68 it claims to be 5 = create & read

and shouldn't it be just 4 = create ?

**Comment by skshetry** [comment]
`uploadwriteonly` is something we created for only providing `read` and `create` but no `update` permissions. So, `read(1) + create(4) = uploadwriteonly(5)`.

The following scenario makes it clearer.
```feature
    Given the administrator has enabled DAV tech_preview
    And as user "user0"
    And the user has created a public link share with settings
      | path        | FOLDER          |
      | permissions | uploadwriteonly |
    When the public uploads file "test.txt" with content "test" using the <public-webdav-api-version> public WebDAV API
    Then the HTTP status code should be "201"
    And the following headers should match these regular expressions
      | ETag | /^"[a-f0-9]{1,32}"$/ |
    When the public uploads file "test.txt" with content "test2" using the <public-webdav-api-version> public WebDAV API
    Then the HTTP status code should be "403"
    And the content of file "/FOLDER/test.txt" for user "user0" should be "test"
```
Notice the `403` when trying to update.

Also, `Sharing.php:175` does not support derived permissions as far as I remember. So, the annotations/comments is lying. I'll create a PR shortly.
