### ISSUE TITLE
webinstaller does not work with 10.3.0alpha2

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#36149]
### Steps to reproduce
1. unpack 10.3.0alpha2 or clone from git current master
2. try to install oC by using the web-installer

### Expected behaviour
oC should be installed

### Actual behaviour
- Internal Server Error message shown
- if data directory does not exist yet, its not created (so the admin is not able to check the the log-file)

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache2
**Database:**
NAN
**PHP version:**
7.1
**ownCloud version:** (see ownCloud admin page)
10.3.0alpha2

#### ownCloud log (data/owncloud.log)
```
{"reqId":"CUaknxOpwvxVEZGVj6Fu","level":3,"time":"2019-09-04T07:10:04+00:00","remoteAddr":"127.0.0.1","user":"--","app":"index","method":"GET","url":"\/owncloud-core\/","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to a member function invalidateSessionToken() on null\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/base.php(584): OC::initSession()\\n#1 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/base.php(1002): OC::init()\\n#2 \\\/home\\\/artur\\\/www\\\/owncloud-core\\\/index.php(53): require_once('\\\/home\\\/artur\\\/www...')\\n#3 {main}\",\"File\":\"\\\/home\\\/artur\\\/www\\\/owncloud-core\\\/lib\\\/base.php\",\"Line\":448}"}
```

**Comment by individual-it** [comment]
occ installer does work

reverting all commits from  #35888 does fix the issue

**Comment by jvillafanez** [comment]
https://github.com/owncloud/core/pull/36153 should fix the problem

**Comment by phil-davis** [comment]
PR fixes the issue
