### ISSUE TITLE
10.3. - smoke test results

### ISSUE THREAD

**Issue by davitol** [owncloud/core#36143]
# Smoke test with 10.3. RC1 version

## Previous requirements

Prepare two servers with ssl activated and trusted certificates.

Enable LDAP and external storage apps.

Have a LDAP server ready to be used with owncloud.

Have ready two external storages of your choice SMB, SFTP, Dropbox, Google Drive, FTP, S3, ownCloud, local.

Scenarios to consider:
- [x] OAuth2 and sync + mobile clients ( can be deployed remotely ) @davitol 
- [x] LDAP @davitol 
- [x] Shibboleth @davitol
- [ ] Windows Network Drive (also use it as sync target ) 
- [x] Guests @davitol  
- [x] Impersonate @davitol 
- [x] Login with App Token Login @davitol
- [x] TOTP @davitol 

## Testing setup

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Enable encryption app and encryption default module | Encryption is enabled correctly |  ✔️    |
2 | Populate owncloud server with users and groups | Users and groups are correctly created | ✔️   |
3 | Share a folder remotely using federated sharing with admin user of the other server. | folder can be opened in recipient server without problems | ✔️   | issue (no regression) #35042
4 | Set up LDAP, as admin check users. log in with a LDAP user, if possible one with an avatar. | Users are loaded. LDAP user logs in without problems. Avatar is shown if it exists.  | ✔️ |
5 | Set up two external storages different, disable encryption in one of them.| No errors in this process | ✔️   |

## Testing functionality

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Share a file using federated sharing from an external unencrypted external storage in server #1 using a LDAP user to the admin user in server #2. | Admin user in server #2 can see the file. | ✔️ |
2 | Open internet explorer or edge and upload a new avatar for a regular user not LDAP | Interface can be used, avatar is uploaded, check that personal page has a scroll bar and scrolls fine. | ✔️ |
3 | Upload several files and folders inside external storages, open some. | No problems uploading, files can be downloaded and opened. | ✔️  | To be investigated. WebDAV storage seems to not work https://github.com/owncloud/core/issues/35660
4 | Delete files inside both external storages. Recover some after from the trashbin. |  Files are correctly deleted and restored. |✔️  |
5 | Using webdav upload a 100MiB file.| No errors in this process |✔️ |

**Comment by davitol** [comment]
### Issues found while testing 10.3 alpha2 tarball

- [WIP]

**Comment by jesmrec** [comment]
## Mobile tests

Sharing feature was deeply tested in  10.3alpha. You can check here the results:

https://github.com/owncloud/QA/blob/master/Mobile/GenericTPs/Sharing.md

Regarding alpha2:

- Checking different authentication situations, including SAML (only Android), redirections.
- Smoke test over the main features
- Sanity tests over Sharing.

Only was detected an issue in Android client when uploading files in guest app, but not a regression.

Here you have the tests performed:

# Smoke test iOS 

**Device & iOS version:** iPhoneXR v12.2
**iOS app version: 1.0.4** (latest stable)
**Server version:** 10.3alpha24
**OAuth2 version**: 0.4.1


### Login

Test Case | Expected Result | Result | Related Comment
| :------- | :--------------- | :------ | :-----------------: | 
| Login basic | It is possible to access  | :white_check_mark: |
| Login basic wrong credentials | Correct error  | :white_check_mark: |
| Login OAuth2 | It is possible to access  | :white_check_mark: |
| OAuth2 revoked token| redirected to login | :white_check_mark: |
| Redirection 301 | It is possible to access  | :white_check_mark: |
| Redirection 302 | It is possible to access  | :white_check_mark: |
| Login Guest | It is possible to access  | :white_check_mark: |
| Login App Password | It is possible to access  | :white_check_mark: |
| SAML | It is possible to access  | :x: | SAML not available in iOS anymore
| Issue #35888 | No exception in core logs when creating OAuth2 session  | :white_check_mark: |


### Folder

TestID | Test Case | Steps | Expected Result | Result | Related Comment
| :------------ | ------------- | ----------- | -------------- | ----- | ------
| Create a new folder  | 1. Tap on create a new folder |The folder is created| :white_check_mark: OAuth<br>:white_check_mark: basic<br> |
| Create a folder with special character | 1. Tap on create a new folder <br> 2. Use a name with special characters (e.g $%&¨)| The folder is created with special character  | :white_check_mark: OAuth<br>:white_check_mark: basic<br> |
| Rename a folder | 1. Create a new folder<br> 2. Rename the folder|  Folder is renamed| :white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Move a folder | 1. Create a new folder <br> 2. Move the folder| Folder is moved to the specifield location | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Upload a file into a folder | 1. Create a new folder <br> 2. Upload a file| File is uploaded into the folder | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Delete a folder  | 1. Access to a folder, the folder has deep structure inside <br> 2. Download some files <br>3. Select delete that folder  | 2. The files are downloaded<br>3. The folder is removed| :white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Copy Folder | 1. Long press to copy a folder <br> 2. Select a location to paste | The folder and all its content is copied in the location, and remains too in the original| :white_check_mark: OAuth<br>:white_check_mark: basic<br>

 
 
### File

| Test Case | Steps | Expected Result | Result | Related Comment
| :-------- | :---- | :-------------- | :-------: | ------- 
| Upload a new file  | 1. Upload a new file | The file is uploaded | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Upload many files | 1. Upload many files at the time| Files are uploaded |:white_check_mark: basic<br>:white_check_mark: basic<br>:white_check_mark: OAuth2
| Rename a file | 1. Create a new file <br> 2. Rename the file | The file is renamed |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Duplicate a file | 1. Create a new file <br> 2. Duplicate the file | The file is duplicated |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Move a file | 1. Create a new file <br> 2. Move the file | The file is renamed |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Copy a file  | 1. Create a new file <br> 2. Copy the file | The file is copied to the selected location | :white_check_mark: OAuth<br>:white_check_mark: basic
| Delete a file  | 1. Create a new file <br> 2. Delete the file | The file is deleted |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Download a file| 1. Tap to download a large file | The file is downloaded and marked with green tick|:white_check_mark: OAuth<br>:white_check_mark: basic<br>


### Sharing (OAuth2)

| Test Case | Result | Related Comment
| :------------ | :------------: | :------------- |
| Share file with a user | :white_check_mark: |  |  |  |
| Share folder with a user | :white_check_mark: |  |  |  |
| Share with a group | :white_check_mark: |  |  |  |
| Share file with only edit | :white_check_mark: ||  |  |
| Share file with only share | :white_check_mark: |  |  |  |
| Share file with no permissions | :white_check_mark: |  |  |  |
| Edit share permissions file | :white_check_mark: |  |  |  |
| Remove share| :white_check_mark: | |  |  |
| Resharing |  :white_check_mark: |  |  |  |
| Resharing no permissions | :white_check_mark: |  |  |  |
| Name | :white_check_mark: |  |  |  |
| Down / view perm | :white_check_mark: ||  |  |
| Down / view / edit perm |  :white_check_mark:||  |  |
| upload only perm | :white_check_mark: | |  |  |
| Password | :white_check_mark:  | |  |  |
| Expiration date | :white_check_mark:  | |  |  |
| Password enforced | :white_check_mark:  |  |  |  |
| Expiration date default | :white_check_mark:  |  |  |  |
| Expiration date enforced | :white_check_mark:  | |  |  |
| Passw & Expiration date enforced | :white_check_mark:  |  |  |  |
| Remove public link | :white_check_mark: | |  |  |

**Comment by micbar** [comment]
@davitol @HanaGemela 
https://github.com/owncloud/core/pull/36193 will be in RC.

Issue: https://github.com/owncloud/core/issues/36107

## Needs testing:

- Server: Resharing permissions
- Server: Transfer ownership (occ command)
- Desktop: Resharing permissions

**Comment by davitol** [comment]
## Mobile tests

### Login

Test Case | Expected Result | Result | Related Comment
| :------- | :--------------- | :------ | :-----------------: | 
| Login basic | It is possible to access  | :white_check_mark: |
| Login basic wrong credentials | Correct error  | :white_check_mark: |
| Login OAuth2 | It is possible to access  | :white_check_mark: |
| OAuth2 revoked token| redirected to login | :white_check_mark: |
| Redirection 301 | It is possible to access  | :white_check_mark: |
| Redirection 302 | It is possible to access  | :white_check_mark: |
| Login Guest | It is possible to access  | :white_check_mark: |
| Login App Password | It is possible to access  | :white_check_mark: |

### Folder

TestID | Test Case | Steps | Expected Result | Result | Related Comment
| :------------ | ------------- | ----------- | -------------- | ----- | ------
| Create a new folder  | 1. Tap on create a new folder |The folder is created| :white_check_mark: OAuth<br>:white_check_mark: basic<br> |
| Create a folder with special character | 1. Tap on create a new folder <br> 2. Use a name with special characters (e.g $%&¨)| The folder is created with special character  | :white_check_mark: OAuth<br>:white_check_mark: basic<br> |
| Rename a folder | 1. Create a new folder<br> 2. Rename the folder|  Folder is renamed| :white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Move a folder | 1. Create a new folder <br> 2. Move the folder| Folder is moved to the specifield location | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Upload a file into a folder | 1. Create a new folder <br> 2. Upload a file| File is uploaded into the folder | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Delete a folder  | 1. Access to a folder, the folder has deep structure inside <br> 2. Download some files <br>3. Select delete that folder  | 2. The files are downloaded<br>3. The folder is removed| :white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Copy Folder | 1. Long press to copy a folder <br> 2. Select a location to paste | The folder and all its content is copied in the location, and remains too in the original| :white_check_mark: OAuth<br>:white_check_mark: basic<br>

 
 
### File

| Test Case | Steps | Expected Result | Result | Related Comment
| :-------- | :---- | :-------------- | :-------: | ------- 
| Upload a new file  | 1. Upload a new file | The file is uploaded | :white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Upload many files | 1. Upload many files at the time| Files are uploaded |:white_check_mark: basic<br>:white_check_mark: basic<br>:white_check_mark: OAuth2
| Rename a file | 1. Create a new file <br> 2. Rename the file | The file is renamed |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Duplicate a file | 1. Create a new file <br> 2. Duplicate the file | The file is duplicated |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Move a file | 1. Create a new file <br> 2. Move the file | The file is renamed |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Copy a file  | 1. Create a new file <br> 2. Copy the file | The file is copied to the selected location | :white_check_mark: OAuth<br>:white_check_mark: basic
| Delete a file  | 1. Create a new file <br> 2. Delete the file | The file is deleted |:white_check_mark: OAuth<br>:white_check_mark: basic<br>
| Download a file| 1. Tap to download a large file | The file is downloaded and marked with green tick|:white_check_mark: OAuth<br>:white_check_mark: basic<br>


### Sharing (OAuth2)

| Test Case | Result | Related Comment
| :------------ | :------------: | :------------- |
| Share file with a user | :white_check_mark: |  |  |  |
| Share folder with a user | :white_check_mark: |  |  |  |
| Share with a group | :white_check_mark: |  |  |  |
| Share file with only edit | :white_check_mark: ||  |  |
| Share file with only share | :white_check_mark: |  |  |  |
| Share file with no permissions | :white_check_mark: |  |  |  |
| Edit share permissions file | :white_check_mark: |  |  |  |
| Remove share| :white_check_mark: | |  |  |
| Resharing |  :white_check_mark: |  |  |  |
| Resharing no permissions | :white_check_mark: |  |  |  |
| Name | :white_check_mark: |  |  |  |
| Down / view perm | :white_check_mark: ||  |  |
| Down / view / edit perm |  :white_check_mark:||  |  |
| upload only perm | :white_check_mark: | |  |  |
| Password | :white_check_mark:  | |  |  |
| Expiration date | :white_check_mark:  | |  |  |
| Password enforced | :white_check_mark:  |  |  |  |
| Expiration date default | :white_check_mark:  |  |  |  |
| Expiration date enforced | :white_check_mark:  | |  |  |
| Passw & Expiration date enforced | :white_check_mark:  |  |  |  |
| Remove public link | :white_check_mark: | |  |  |


# Smoke test Android 

**Device & Android version**: Xiaomi MI A2
**Android app version**: 2.12
**Server version:** 10.3.0 EE final version
**OAuth2 version:** 0.4.1


### Login

Test Case | Expected Result | Result | Related Comment
| :------- | :------------- | :----- | :------------- | 
| Login basic | It is possible to access  | :white_check_mark: |
| Login basic wrong credentials | Correct error  | :white_check_mark: |
| Login OAuth2 | It is possible to access  | :white_check_mark: |
| OAuth2 revoked token| redirected to login | :white_check_mark: |
| Redirection 301 | It is possible to access  | :white_check_mark: |
| Redirection 302 | It is possible to access  | :white_check_mark: |
| Login Guest | It is possible to access  | :white_check_mark: | login OK, but uploads... https://github.com/owncloud/android/issues/2653
| Login App Password | It is possible to access  | :white_check_mark: |
| Login SAML  | It is possible to access  | :white_check_mark: | LDAP server 
Issue #35888 | No exception in core logs when creating OAuth2 session  | :white_check_mark: |


### Folder

Test Case | Steps | Expected Result | Result | Related Comment
| :------ | :---- | --------------- | ------ | ---------
| Create a new folder  | 1. Tap on create a new folder |The folder is created| :white_check_mark: basic<br>:white_check_mark: OAuth2  |
| Create a folder with special character | 1. Tap on create a new folder <br> 2. Use a name with special characters (e.g $%&¨)| The folder is created with special character  | :white_check_mark: basic<br>:white_check_mark: OAuth2 |
| Rename a folder | 1. Create a new folder<br> 2. Rename the folder|  Folder is renamed|:white_check_mark: basic<br>:white_check_mark: OAuth2
| Move a folder | 1. Create a new folder <br> 2. Move the folder| Folder is moved to the specifield location |:white_check_mark: basic<br>:white_check_mark: OAuth2
| Upload a file into a folder | 1. Create a new folder <br> 2. Upload a file| File is uploaded into the folder |:white_check_mark: basic<br>:white_check_mark: OAuth2
| Delete a folder  | 1. Access to a folder, the folder has deep structure inside <br> 2. Download some files <br>3. Select delete that folder  | 2. The files are downloaded<br>3. The folder is removed|:white_check_mark: basic<br>:white_check_mark: OAuth2
| Copy Folder | 1. Long press to copy a folder <br> 2. Select a location to paste | The folder and all its content is copied in the location, and remains too in the original|:white_check_mark: basic<br>:white_check_mark: OAuth2
| Sync a folder| 1. Create a folder <br> 2. In web app, upload some files in the folder <br> 3. Long press to sync the folder  | The folder is sync with the content on server|:white_check_mark: basic<br>:white_check_mark: OAuth2


### File

Test Case | Steps | Expected Result | Result | Related Comment
| :------- | ----- | --------------- | ------ | ------
| Upload a new file  | 1. Upload a new file | The file is uploaded | :white_check_mark: basic<br>:white_check_mark: OAuth2
| Upload many files | 1. Upload many files at the time| Files are uploaded |:white_check_mark: basic<br>:white_check_mark: basic<br>:white_check_mark: OAuth2
| Rename a file | 1. Create a new file <br> 2. Rename the file | The file is renamed |:white_check_mark: basic<br>:white_check_mark: OAuth2
Move a file | 1. Create a new file <br> 2. Move the file | The file is renamed |:white_check_mark: basic<br>:white_check_mark: OAuth2
| Copy a file  | 1. Create a new file <br> 2. Copy the file | The file is copied to the selected location |:white_check_mark: basic<br>:white_check_mark: OAuth2
| Delete a file  | 1. Create a new file <br> 2. Delete the file | The file is deleted |:white_check_mark: basic<br>:white_check_mark: OAuth2
| Download a file| 1. Tap to download a file | The file is downloaded and marked with green arrow|:white_check_mark: basic<br>:white_check_mark: OAuth2
| Av Offline file | 1. Long press to set as Av Offline a file | The file is downloaded and set as Av Offline with the yellow arrow |:white_check_mark: basic<br>:white_check_mark: OAuth2
| Av Offline file | 1. Long press to unset an Av Offline a Av Offline file | The file has no more the yellow arrow |:white_check_mark: basic<br>:white_check_mark: OAuth2

### Sharing (OAuth2)

| Test Case | Result | Related Comment
| :------------ | :------------: | :------------- |
| Share file with a user | :white_check_mark: |  | 
| Share folder with a user | :white_check_mark: |  |
| Share with a group | :white_check_mark: |  | 
| Share file with only edit | :white_check_mark: ||  
| Share file with only share | :white_check_mark: |  
| Share file with no permissions | :white_check_mark: |
| Edit share permissions file | :white_check_mark: | 
| Remove share| :white_check_mark: | | 
| Resharing |  :white_check_mark: |  
| Resharing no permissions | :white_check_mark: | 
| Name | :white_check_mark: | 
| Down / view perm | :white_check_mark: || 
| Down / view / edit perm |  :white_check_mark:||  
| upload only perm | :white_check_mark: |
| Password | :white_check_mark:  | 
| Expiration date | :white_check_mark:  | 
| Password enforced | :white_check_mark:  |  
| Expiration date default | :white_check_mark:  | 
| Expiration date enforced | :white_check_mark:  |
| Passw & Expiration date enforced | :white_check_mark:  |
| Remove public link | :white_check_mark: |

**Comment by HanaGemela** [comment]
10.3.0 EE server smoke test has passed on the desktop sync client 2.5.4, macOS 10.15 and in iOS app 1.1.1, iOS 13.1.2, iPhone XS

Shibboleth testing is blocked by missing docker images with new Ubuntu

[10.3.0 server smoke test via iOS app.pdf](https://github.com/owncloud/core/files/3733399/10.3.0.server.smoke.test.via.iOS.app.pdf)
[10.3.0 server smoke test via desktop clinet 2.5.4.pdf](https://github.com/owncloud/core/files/3733400/10.3.0.server.smoke.test.via.desktop.clinet.2.5.4.pdf)

**Comment by davitol** [comment]
> Shibboleth testing is blocked by missing docker images with new Ubuntu

Tested with Shibboleth and Autoprovision Mode and works with Desktop 2.5.4 in Ubuntu and MacOSX using oC 10.3.0 EE Tarball.



Also checked that Shibboleth is no longer supported in Desktop Client 2.6.0 (as intended and documented in the changelog) but maybe we should consider a nicest warning (@michaelstingl jfyi)
![Screen Shot 2019-10-16 at 13 19 11](https://user-images.githubusercontent.com/10596560/66915427-4391fb80-f019-11e9-8ca2-4fb37db50f97.png)
