### ISSUE TITLE
api for public link share email notification does not obey `Allow users to send mail notification for shared files`

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#36156]
### Steps to reproduce
1. disable `Allow users to send mail notification for shared files`
2. send an email notification by using `ocs/v1.php/apps/files_sharing/api/v1/notification/notify-public-link-by-email` (CSRF needs to be disabled when using basic auth - that is a different issue)

### Expected behaviour
Email should not be send

### Actual behaviour
Email is send

CC @karakayasemi

**Comment by karakayasemi** [comment]
Internal Share Mail API also does not obey `shareapi_allow_mail_notification` config and it is not a regression. We need to fix it also.

If configs are disabled, thanks to capabilities, UI not shows any user interface for sending e-mail, but API allows to send if a request comes.
