### ISSUE TITLE
Translation issue: E2EE File Sharing app 

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#36164]
# German
Ende-zu-Ende-Verschlüsselung
Die Lizenz ist für diese Domain ungültig!
Die Guests App ist nicht **aktiert**. E2ee Share kann also nur mit ownCloud-Benutzern verschlüsselt teilen.

# English
E2EE Share
Your license is not valid for this domain!
Guests App is not enabled. E2ee Share will only share with ownCloud accounts.

**Comment by cortho** [comment]
@voroyam Thank you for the information. It will be fixed in the next release. Since this is custom development and not a core issue I am closing this one
