### ISSUE TITLE
Cannot delete other folders that match part of share_folder

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36169]
PR #35998 add code to prevent a user from deleting the folder define by `share_folder` in the config.

### Steps to reproduce
1. in `config.php`  set `share_folder => '/Company/Files/Shared'`
2. share a folder `stuff` from user1  to user2
3. login as user2
4. you see a folder called `Company/Files/Shared` and that has `stuff` inside it - good
5. create top-level folders called `Com` `File` `Files` `Share` and `Shared`
6. create folder `Shared` inside `Files`
7. try to delete any of those folders that you just created

### Expected behaviour
Each folder can be deleted.

### Actual behaviour
There is an error message and `Error deleting...`

### Server configuration
Current core master

**Comment by phil-davis** [comment]
The code that does a `strpos()` to find out if the path to be deleted is in the `share_folder` path is not quite smart enough. Maybe it would be better to check if the proposed folder to delete is `share_folder` or a parent of `share_folder`

@sharidas @PVince81 @micbar

**Comment by jvillafanez** [comment]
trimming and / or normalizing both path should fix the problem.

**Comment by phil-davis** [comment]
> trimming and / or normalizing both path should fix the problem.

Yes, I was thinking that also - #36170 

This path stuff always looks untidy. You have to keep protecting yourself against paths that do and do not have `/` at the start and/or end.
