### ISSUE TITLE
Update error from 8.2 to 9.0

### ISSUE THREAD

**Issue by Robby-live** [owncloud/core#36160]
Update error from 8.2 to 9.0
Offered version, will be canceled with the error.
Could someone help me?
`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes`

**Comment by ho4ho** [comment]
No need from 8.2 to 9.0, just 8.2.11 to 10.2.1: https://github.com/owncloud/docs/issues/1751

Also duplicate https://github.com/owncloud/core/issues/23988 + more many.

**Comment by davitol** [comment]
> Also duplicate #23988 + more many.

Let's close the ticket. thanks for reporting
