### ISSUE TITLE
/cron endpoint does not exist

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#36176]
### Steps to reproduce
1. try to access the `/cron` endpoint `curl http://localhost/owncloud-10.3.0/alpha2/cron`

### Expected behaviour
as I read the changelog it should do the same line `cron.php`

### Actual behaviour
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /owncloud-10.3.0/alpha2/cron was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
<hr>
<address>Apache/2.4.29 (Ubuntu) Server at localhost Port 80</address>
</body></html>
```

**Comment by micbar** [comment]
@individual-it 
The Url is
`http://cloud.local/index.php/cron`

**Comment by DeepDiver1975** [comment]
... in case where index.php is removed from the url via the rewrite rules it will work using /cron as well :wink:
