### ISSUE TITLE
Wrong share ID message is not shown properly

### ISSUE THREAD

**Issue by davitol** [owncloud/core#36181]
### Steps to reproduce
1. user Alice shares a file with Bob
2. as user Bob browse to page shared with you
3. user Alice deletes the share
4. user Bob tries to decline the share

### Expected behaviour
Error message should be shown properly 

### Actual behaviour

![Screen Shot 2019-09-10 at 11 17 14](https://user-images.githubusercontent.com/10596560/64601714-bb875900-d3bd-11e9-847f-953641f3fde8.png)

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache 2
**Database:**
MySQL
**PHP version:**
7.2
**ownCloud version:** (see ownCloud admin page)
10.3.0alpha2
**Updated from an older ownCloud or fresh install:**
fresh

### Client configuration
**Browser:**
FF
**Operating system:**
Ubuntu 18.04

**Comment by davitol** [comment]
> @davitol Did you compare with 10.2 ?
> Is this a regression?

I checked in 10.2.1 happens so it is not a regression

**Comment by JanAckermann** [comment]
Finding so far, the problem is behind our javascript translate `t` function in combination with vars

Example:
console.log(t('files_sharing', '{message}', {message: "does' not"}));

Renders:
`does&#039; not`

**Comment by jnweiger** [comment]
Confirmed fixed in 10.9.0 RC2

![image](https://user-images.githubusercontent.com/1108546/146300600-2a64b1fe-5009-4199-b589-7d9c6edc7c16.png)
