### ISSUE TITLE
Thumbnail gets shifted when mousing over the 3 dots menu options using Chrome as browser

### ISSUE THREAD

**Issue by davitol** [owncloud/core#36183]
### Steps to reproduce
 
1. Using Chrome as browser, click on 3 dots menu and mouse over the options.

### Expected behaviour

Thumbnail should not move when mousing over the menu

### Actual behaviour

![Screen Shot 2019-09-11 at 08 37 44](https://user-images.githubusercontent.com/10596560/64674300-c7802300-d470-11e9-9812-684ab88fbcf0.png)

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache 2
**Database:**
MySQL
**PHP version:**
7.2
**ownCloud version:** (see ownCloud admin page)
10.3.0 alpha2
**Updated from an older ownCloud or fresh install:**
fresh

### Client configuration
**Browser:**
Chrome for Mac Version 76.0.3809.132
**Operating system:**
Ubuntu 18.04

**Comment by davitol** [comment]
Same behaviour in oC 10.1.1

**Comment by phil-davis** [comment]
confirmed - it does not happen in Firefox (I have Firefox 69.0) but it does happen in Chrome (I have chrome 76.0)

**Comment by sharidas** [comment]
I am using chrome version `77.0`. I am not able to reproduce this issue.

**Comment by davitol** [comment]
Reproduced with Version 76.0.3809.132 (Official Build) (64-bit) for MacOS.

**Comment by davitol** [comment]
Updated to 77 and works. So let's close the ticket.
