### ISSUE TITLE
If LDAP display name is missing nexcloud silently ignores the user. Instead a warning of some kind or somehting in the log should be issued so admin can take action.

### ISSUE THREAD

**Issue by crobarcro** [owncloud/core#36205]
Just as the title says, if the LDAP display name is missing for an LDAP user nexcloud silently ignores the user. Instead a warning of some kind or something in the log should be issued so admin can take action. This was first encountered in https://github.com/owncloud/core/issues/9712#issuecomment-50316208_

**Comment by DeepDiver1975** [comment]
Wrong repo. Open in https://github.com/nextcloud/server
