### ISSUE TITLE
Files mediaviewer is not able to open files in oC 10.3.0 alpha2

### ISSUE THREAD

**Issue by davitol** [owncloud/core#36204]
Files mediaviewer is not able to reproduce videos or open photos when our ownCloud Server is configured with ~~Files Primary S3~~ happens with regular storage. Files are downloaded but not reproduced. Tested with oC 10.3 and files_mediaviewer: 1.0.0 ~~and files_primary_s3: 1.0.4 with Scality~~

**Comment by micbar** [comment]
@davitol @individual-it 
I could not reproduce it

- OC 10.3.0alpha2
- Files Mediaviewer 1.0.0 (github checkout)
- Jpg and png files are working

![Screenshot_2019-09-19 Dateien - ownCloud Customer Portal](https://user-images.githubusercontent.com/4378513/65222021-81edd680-dabe-11e9-9cdc-e7c059158470.jpg)

**Comment by davitol** [comment]
@mbarz please check with owncloud daily tarball (it is also labeled as alpha2) sorry for the missunderstanding
Please tell us if it is reproducible for you too with that version

**Comment by micbar** [comment]
@davitol 
Checked OC 10.3.0alpha2 (Docker) with Mediaviewer 1.0.0 from Marketplace.

Works fine.

Now we need to look into the differences of our enviroments.

**Comment by VicDeo** [comment]
works for me in the following env:
OC master@e98fec80a6fcd08b77120ed6001e24bb707e5c24
files_mediaviewer master@e98fec80a6fcd08b77120ed6001e24bb707e5c24
files_primary_s3@31836f9d588f97cc5c61f5882d4c5f24719613e2

@davitol could you send me a link to the tarball that is failing for you?

**Comment by davitol** [comment]
@VicDeo Fails for me with this Tarball: https://download.owncloud.org/community/daily/owncloud-daily-master-qa.tar.bz2

**Comment by VicDeo** [comment]
@davitol  @micbar unrelated to files_primary_s3, files_mediaviewer is not built properly:
```
deo@reborn:~/public_html/oc-103rc> ls -l apps/files_mediaviewer/
total 252
drwxr-xr-x 2 deo users   4096 Sep 22 23:02 appinfo
-rw-r--r-- 1 deo users    295 Sep 22 23:01 CHANGELOG.md
-rw-r--r-- 1 deo users  18092 Sep 22 23:01 LICENSE
-rw-r--r-- 1 deo users   1073 Sep 22 23:01 package.json
-rw-r--r-- 1 deo users   1081 Sep 22 23:01 README.md
drwxr-xr-x 4 deo users   4096 Sep 22 23:01 src
drwxr-xr-x 2 deo users   4096 Sep 22 23:01 templates
-rw-r--r-- 1 deo users    898 Sep 22 23:01 webpack.config.js
-rw-r--r-- 1 deo users 208696 Sep 22 23:01 yarn.lock

deo@reborn:~/public_html/oc-103rc> ls -l ../oc-master/apps/files_mediaviewer/
total 524
drwxr-xr-x   2 deo users   4096 Sep 20 15:40 appinfo
-rw-r--r--   1 deo users    295 Sep 20 15:40 CHANGELOG.md
drwxr-xr-x   2 deo users   4096 Sep 20 15:41 js
-rw-r--r--   1 deo users  18092 Sep 20 15:40 LICENSE
-rw-r--r--   1 deo users   1925 Sep 20 15:40 Makefile
drwxr-xr-x 490 deo users  20480 Sep 20 15:41 node_modules
-rw-r--r--   1 deo users   1073 Sep 20 15:40 package.json
-rw-r--r--   1 deo users 247575 Sep 20 15:41 package-lock.json
-rw-r--r--   1 deo users   1081 Sep 20 15:40 README.md
drwxr-xr-x   4 deo users   4096 Sep 20 15:40 src
drwxr-xr-x   2 deo users   4096 Sep 20 15:40 templates
-rw-r--r--   1 deo users    898 Sep 20 15:40 webpack.config.js
-rw-r--r--   1 deo users 208696 Sep 20 15:40 yarn.lock
```

itls obvious, release should have `js` directory instead of `src`

**Comment by VicDeo** [comment]
so. if I got meaning of `build` correct, it should be `true` here https://github.com/owncloud/administration-internal/blob/master/release-scripts/config/owncloud-daily-master-qa.json#L112

**Comment by VicDeo** [comment]
I checked the  tarball built on 09/23/2019 09:00:06 PM and `owncloud/apps/files_mediaviewer/js` directory is still missing there

**Comment by VicDeo** [comment]
The PR above DO fix the ussue, probably it needs deploying to the release server.
Here is what I have when I run the script locally:
```
~> php release.php make config/owncloud-daily-master-qa.json
...
~> ls -l temp-releases/owncloud/apps/files_mediaviewer/
total 40
drwxr-xr-x 2 deo users  4096 Sep 24 11:48 appinfo
-rw-r--r-- 1 deo users   295 Sep 24 11:48 CHANGELOG.md
drwxr-xr-x 2 deo users  4096 Sep 24 11:48 js
-rw-r--r-- 1 deo users 18092 Sep 24 11:48 LICENSE
-rw-r--r-- 1 deo users  1081 Sep 24 11:48 README.md
drwxr-xr-x 2 deo users  4096 Sep 24 11:48 templates


```

**Comment by davitol** [comment]
> I checked the tarball built on 09/23/2019 09:00:06 PM and `owncloud/apps/files_mediaviewer/js` directory is still missing there

I had checked also with today's daily tarball and yes, it is still missing

**Comment by davitol** [comment]
Who can take care of the deployment in the release server? @tboerger maybe?

**Comment by tboerger** [comment]
I'm not in charge of that.

**Comment by VicDeo** [comment]
@davitol the files_mediaviewer app is built in dailies now. 
Could you please retest if the issue is not reproducible anymore?

**Comment by davitol** [comment]
Works fine in ```$OC_Build = '2019-09-25T20:00:31+00:00 31ea320a69be5fa9f4c92eb3f25ed816ba810a5d';```Let's close the ticket @VicDeo
