### ISSUE TITLE
Automatic Session-out isn't working

### ISSUE THREAD

**Issue by DevSec-Ops** [owncloud/core#36217]
**Steps to reproduce**
1. Login into the ownCloud instance
2. Do nothing on the opened tab, for 5 minutes

**Expected Behaviour**
1. Auto session-out should be done
2. Login Page should be displayed

**Actual behaviour**
No auto session-out is there after 5 minutes

**Server configuration**
Operating system: CentOS 7 (64 bit)
Web server:: Apache
Database:: MySQL
PHP version:: 7.1.28
ownCloud version: (see ownCloud admin page) 10.1.1
Updated from an older ownCloud or fresh install: Fresh
Where did you install ownCloud from: Bitnami Stack
Signing status (ownCloud 9.0 and above): Valid

**Client configuration**
Browser: Firefox Quantum 69.0.1 (64-bit)
Operating system: Windows 10 Pro (64-bit)

**I've configured following in "/htdocs/config/config.php":**
 'remember_login_cookie_lifetime' => 300, 'session_lifetime' => 300, 'session_keepalive' => false,

**Comment by GruLab** [comment]
Same issue exists on Chrome 77.0.3865.90, but it works on Microsoft Edge 44.18362.329.0; if browser minimized.

**Comment by DeepDiver1975** [comment]
THX for your report @GruLab 

While you disabled the session keep alive feature there are other apps (e.g. notifications) which are issuing requests to the server periodically which keeps the session alive even with the keep alive disabled.

This is know but we did not yet address this. To some extend it is questionable if such an feature (keep alive) is reasonable at all these days.

**Comment by karakayasemi** [comment]
In a few days, we will have a new RC release for 10.3.  Server v10.30 has several session improvements, I guess it may resolve this issue also. Here is the related PR: #35888

If you would like to help us, please test your scenario in the current master branch or 10.3 RC and report to results. Thanks.

**Comment by GruLab** [comment]
@DeepDiver1975 thnx for the information, but setting should behave on system/product level.
@karakayasemi definitely i will check the RC release, let you know issues on session handling.

**Comment by karakayasemi** [comment]
@GruLab 10.3.0 RC is released: https://central.owncloud.org/t/owncloud-server-10-3-0-rc1-is-available/22056 and currently, there is no known release blocker for it. Session fixes also passed from smoke tests: https://github.com/owncloud/core/issues/36130. 
Please, test your issue and let us know if you catch a problem.

**Comment by GruLab** [comment]
@karakayasemi Thnx for the update, I tested above issue; still exists.

**Comment by DeepDiver1975** [comment]
Yes. Because as explained above notifications App keeps the Session alive.
