### ISSUE TITLE
Owncloud 10.2.1/10.3.0(/2) invalid email address error

### ISSUE THREAD

**Issue by TNCS-git** [owncloud/core#36223]
### Steps to reproduce
1. Issue is presistant

### Expected behaviour
Initial setup of owncloud 10.2.1 with PHP7.2.17, setup was fine and busy setup e-mail server under Admin, General. And this is where the problem occur.

### Actual behaviour
It constantly give me the error ‘Invalid email address’, even if I throw in something as simple as user@live.com

![f9c52ae69392c0a81354aa4647bfc2e3dd123a49](https://user-images.githubusercontent.com/55931455/65823111-de888880-e258-11e9-8612-338b0ca67223.png)

### Server configuration
**Operating system**: Entware

**Web server:** lighthttpd/FastCGI

**Database:** SQLite3

**PHP version:** 7.2.17

**ownCloud version:** (see ownCloud admin page) 10.2.1

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** tar.bz

**Signing status (ownCloud 9.0 and above):** 

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.4.0
  - federatedfilesharing: 0.4.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.2.0
  - market: 0.5.0
  - notifications: 0.5.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_videoplayer
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/sftp/... No

**Are you using encryption:** yes/no No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... No

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Chrome/IE

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by TNCS-git** [comment]
Following has changed, and error still persist:
Web server: nginx/PHP-FPM
Database: MariaDB
PHP version: 7.2.22
ownCloud version: (see ownCloud admin page) 10.3.2

**Comment by ho4ho** [comment]
Works by own installation 10.3.2:

![mail](https://user-images.githubusercontent.com/42564859/71031544-dd5a4f80-2113-11ea-9bdd-3f5815d896b7.png)

Problem by web server / PHP not by ownCloud? Checks logs not filled out?

**Comment by TNCS-git** [comment]
As you can see my update, I've changed the platform which the error persist. I've checked nginx, PHP-FPM and ownCloud logs numerous times, no error. If you have other ways to dig deep, please share.

**Comment by ho4ho** [comment]
Checking browser (addons?) or browser logs? Something between browser + ownCloud (firewall, proxy, cloudflare, ...)?

**Comment by TNCS-git** [comment]
I've tried Chrom, Edge, IE11 with/without firewall. The only thing I can think of now is maybe the php-mod-intl package by Entware, which is related e-mail verification method INTL_IDNA_VARIANT_UTS46 used by ownCloud. But I honestly don't see the chance of that happening, as it should be a very mature and straightforward package.

**Comment by lukaszdrukasz** [comment]
Hi!

I had the exact same issue while trying to run owncloud in openwrt on Raspberry Pi. I resolved it by building my image from source while setting "Add dependency to full ICU data" to true. This in turn in addition to libicu built the file icudt65l.dat and installed it in /usr/share/icu/65.1

I hope this helps!

**Comment by TNCS-git** [comment]
> Hi!
> 
> I had the exact same issue while trying to run owncloud in openwrt on Raspberry Pi. I resolved it by building my image from source while setting "Add dependency to full ICU data" for php7-mod-intl to true. This in turn in addition to libicu built the file icudt65l.dat and installed it in /usr/share/icu/65.1
> 
> I hope this helps!
> 
> EDIT: clarified that the changed setting conerned php-mod-intl

Thanks, don't think I'll build my own, but at least now I know I'm not crazy!

**Comment by VicDeo** [comment]
Seems to be env issue or an upstream bug https://github.com/egulias/EmailValidator

**Comment by davitol** [comment]
Closing the issue due to:


> Nothing to fix for owncloud as it seems to be env issue or an upstream bug https://github.com/egulias/EmailValidator
> EDIT: ah. also could be a bug in `idn_to_ascii` implementation
