### ISSUE TITLE
Versions downloaded of shared files are named with a number instead of the filename

### ISSUE THREAD

**Issue by davitol** [owncloud/core#36228]
### Steps to reproduce
1. create a file (e.g docx)
2. Edit it and create a version
3. Share the file with userB
4. Login with userB
5. Browse to the SideBar and download a file version

### Expected behaviour
File's  name should be preserved

### Actual behaviour
Files is downloaded named as a number

**Database:**
MySQL

**ownCloud version:** (see ownCloud admin page)

oC 10 10.3.0RC1

**Comment by phil-davis** [comment]
This is still an issue. As receiver of the shared file, I get an old version downloaded with a name like `1624854121.txt`

The UI is sending a request to something like:
http://172.17.0.1:8080/remote.php/dav/meta/2147484945/v/1624854120

@dpakach someone should first check that there are API tests that cover this - I see that `FilesVersionsContext.php` has references to path `/meta/$fileId/v` - there need to be API tests that cover the share receiver downloading previous versions of a received file. (and downloading previous versions of a file that is in a received folder)

And once we have API tests that we know are passing, then it might be a UI problem, and we can make a UI test that demonstrates this.

**Comment by individual-it** [comment]
I think the issue is the `Content-Disposition` Header
downloading a n older version of an own file gives: ` attachment; filename*=UTF-8''block-aligned.txt; filename="block-aligned.txt"`
but in a shared case: `attachment; filename*=UTF-8''; filename=""`

**Comment by individual-it** [comment]
I don't think we have any API tests trying to download old versions

**Comment by individual-it** [comment]
tests added in  #38921

**Comment by JanAckermann** [comment]
@JammingBen Still exists, should be name like in users file list (keep in mind, that the user can rename a shared file)
