### ISSUE TITLE
Rename file option appears in Shared with you section when file was not shared with edit permissions [Only Visual Bug] 

### ISSUE THREAD

**Issue by davitol** [owncloud/core#36229]
### Steps to reproduce
1. create a file 
2. Share the file with userB without 'can edit' option
3. Login with userB
4. Browse to the Share with You menu
5. Check the rename option does not appear in the 3 dots menu
6. Open the sidebar
7. Check again if the rename option does not appear in the 3 dots menu

### Expected behaviour

Rename file option should not appear.

### Actual behaviour

Rename file option appears in the menu

Note: It is only a VISUAL bug. Renaming is not posible

**Database:**
MySQL

**ownCloud version:** (see ownCloud admin page)

oC 10 10.3.0RC1

**1st step**
![Screen Shot 2019-10-01 at 13 18 59](https://user-images.githubusercontent.com/10596560/65958644-26253500-e450-11e9-9d57-26ad9ee7c110.png)

**2nd step**
![Screen Shot 2019-10-01 at 13 22 04](https://user-images.githubusercontent.com/10596560/65958668-39380500-e450-11e9-89e9-65f05073c9d7.png)

**3rd step**
![Screen Shot 2019-10-01 at 13 26 24](https://user-images.githubusercontent.com/10596560/65958684-42c16d00-e450-11e9-91f9-094017ae7bb4.png)

**Comment by phil-davis** [comment]
The UI should be consistent. But what is the requirement?
`A user should be able to rename a received shared file, without having edit permission for the file`
(The rename will be a local rename of the file for the receiving user. The owner will still see the original name)
True or false?

**Comment by JanAckermann** [comment]
Note: This behavior has been changed in the meantime, renaming is now possible and does not affect the shared file.
