### ISSUE TITLE
Group with special characters in the name is not blacklisted

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/core#36230]
Server 10.3.0.RC1

Steps to recreate:
1) Create a group called ±!@#$%^&*()_+}{|":?><~§-=][\';/.,
2) Select that group in `Group Sharing Blacklist` in Settings -> Admin -> Sharing (First suspicious thing is that this group can be selected multiple times)
3) Share a file to that group 

Actual result: File has been shared
Expected result: Group has not been available for sharing

Found while testing https://github.com/owncloud/core/pull/36038

**Comment by phil-davis** [comment]
See issue #31836 
IMO it is the vertical bar `|` character that is the problem.
Try the weird group name, but without the vertical bar and confirm it is OK.

**Comment by HanaGemela** [comment]
Duplicate of  #31836
