### ISSUE TITLE
Update outdated components

### ISSUE THREAD

**Issue by cs35-owncloud** [owncloud/core#36237]
Hello,

after running a vulnerability [scan](https://www.immuniweb.com/websec/?id=ueEWi4Hi) on the  [ownCloud demo](https://demo.owncloud.org/login) I noticed that some components where outdated here's a non exhaustive list:

* JQuery 2.1.4
* jQuery Migrate 1.4.0
* Handlebars.js 4.1.1
* Sunset-watch 1.0.3
* Select2 3.5.4

It seems it's all listed [here](https://github.com/owncloud/core/blob/dbb0ee442964ce0fab199eba794f52f536b8d7a8/build/package.json). Is it possible to update them for the upcoming 10.0.3 ?
Thanks.

**Comment by micbar** [comment]
@cs35-owncloud See the output of your security scanner regarding libraries here:
![Screenshot_2019-10-04 Website Security Test of demo owncloud org](https://user-images.githubusercontent.com/4378513/66196705-4a278700-e699-11e9-88ea-08cf87acf929.png)

This tool and our other checks say that we don't have a security issue here.
We will not upgrade these libs in the 10.3.0 but in the next release.

**Comment by cs35-owncloud** [comment]
Hi @micbar 
thanks for your fast answer, it's true that on the demo it seems there is no detected vulnerabilities yet.
When I run it on one of my instance which is a 10.2.1 I have the JQuery 2.1.4 that shows up which has [vulnerabilities](https://www.immuniweb.com/websec/?id=xvVspQu2). I don't know why it doesn't show up on your official demo, maybe it comes from some apps using it ?
Anyway as I stated previously, in the [core](https://github.com/owncloud/core/blob/dbb0ee442964ce0fab199eba794f52f536b8d7a8/build/package.json), the required JQuery is the one with vulnerabilities.
It seems fair to wait the next minor release to update all the components since RC1 is already good looking but I'm a bit concerned about security.
Thanks.

**Comment by ho4ho** [comment]
> It is not that easy unfortunately. Just udating jquery will create a lot of issues.
> This would be a major change across the whole platform including all the apps.

https://github.com/owncloud/core/issues/37463#issuecomment-650787297

**Comment by AdminValida** [comment]
Hi!

Any updates on https://github.com/owncloud/core/pull/38479 ?

Regards
