### ISSUE TITLE
When will you stop supporting webspaces?

### ISSUE THREAD

**Issue by gitUser643543** [owncloud/core#36232]
I have read that you plan to switch your programming language so owncloud will not work on normale webspaces (php, mysql, no root) anymore. Can you give me some details? When will you make this change?

**Comment by DeepDiver1975** [comment]
The next generation if owncloud will be called 'ownCloud Infinite Scale' and will focus on pure file sync and share. The architecture will be microservice based and will rely on the Go Language.

This new architecture has impact on the deployment model and a deployment on a php webspace is out of scope. 

We are in the very initial phase of this project and the classic ownCloud project will be alive for a few years.

Please find more info about ocis in e.g. https://github.com/owncloud/ocis

I hope this answers your question - please raise further questions on https://central.owncloud.org
