### ISSUE TITLE
share_folder can be shared

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/core#36241]
Server: 10.3.0RC1

Steps to recreate:
1) Add `share_folder` into `config.php`
2) User1 shares a file with User2
3) User2 deletes the file from their account
4) User2 shares `share_folder` 

Actual result: `share_folder` can be shared. Any new files which are added to that folder as newly received shares are not shared to the collaborators. But new files can be added via public links. This is confusing

Expected result: Sharing of `share_folder` is not allowed

**Comment by phil-davis** [comment]
I expect that users have been able to do this sort of thing in all core versions (since whenever `share_folder` was introduced)

So IMO this is not a regression, but it is a good idea to prevent users sharing the special folder `share_folder`

**Comment by karakayasemi** [comment]
share permission is removed for share_folder and its parent folders by #36337.
