### ISSUE TITLE
Deleted folder is not restored when deletion is not allowed

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/core#36252]
Server: 10.3.0 RC1
Client: 2.6.0 RC1 

Steps to recreate:
1) Add the below line into `config.php` on the server (From now on the incoming shares will be shown in that folder)
`'share_folder' => '/ReceivedShares'`
2) User1 shares a resource to User2
3) User2 deletes `ReceivedShares` folder on the client

Actual result: 403 Forbidden reply from the server but the folder has been deleted on the client
Expected result: Folder has been restored on the client 

<img width="925" alt="Screenshot 2019-10-01 at 14 34 23" src="https://user-images.githubusercontent.com/49001702/65962443-f890b980-e458-11e9-89f2-c1123aab9ece.png">

Similar logic as in https://github.com/owncloud/client/issues/7490 When server forbids something, the action on the client should be reverted 

Workaround available in 2.5 client (not working in 2.6 anymore)
1) Unselect that folder in selective sync list
2) Apply 
3) Select it again
4) Apply

**Comment by karakayasemi** [comment]
Delete permission is removed for share_folder and its parent folders by #36337. Now, clients will see correct permissions of share_folder.
