### ISSUE TITLE
bigger thumbnails in web interface (feature request)

### ISSUE THREAD

**Issue by robertboyl** [owncloud/core#36268]
Hello, friends!

Just wondering, any chance to have bigger thumbnails in the web interface?

I shared an album of photos with friends, but thumbnails are so small... 

See how they appear

![image](https://user-images.githubusercontent.com/13451604/66651706-148b1c80-ec0a-11e9-8666-434f66ec82e3.png)

Thanks!

**Comment by VicDeo** [comment]
Unfortunately it is possible only by writing an own theme

**Comment by robertboyl** [comment]
Thanks a lot for answer, Vic!

I see. But cant it be a good feature request? I simply love ownCloud, its really the only thing that I dislike.

If I share a folder with pictures inside, the thumbnails are very small, so its visually hard for someone to see the pictures clearly.

Seems it might not be so hard to adjust that somehow? I just want bigger thumbnails :)) Dont you think this would be good for all other users?

I tried to Google it and found these links that seem to be related to this.

https://central.owncloud.org/t/changing-thumbnail-sizes-in-files-list/19304/3
https://doc.owncloud.org/server/9.0/user_manual/files/gallery_app.html
https://forum.owncloud.org/viewtopic.php?t=24526
https://doc.owncloud.org/server/9.0/admin_manual/configuration_files/previews_configuration.html

Thanks!

**Comment by DeepDiver1975** [comment]
Please note that the owncloud frontend is rewritten - https://github.com/owncloud/phoenix

Feel free to raise this feature request there.

**Comment by robertboyl** [comment]
> 
> 
> Please note that the owncloud frontend is rewritten - https://github.com/owncloud/phoenix
> 
> Feel free to raise this feature request there.

Thanks a lot, DeepDiver! Will do!

Is there a place I can see a public demo to check how thumbnails are in that frontend?

Tks!

**Comment by robertboyl** [comment]
https://github.com/owncloud/phoenix/issues/2341

**Comment by LukasHirt** [comment]
> Is there a place I can see a public demo to check how thumbnails are in that frontend?

Thumbnails are not yet implemented in the current state of Phoenix. Currently, there are "only" icons.

![image](https://user-images.githubusercontent.com/25989331/68211857-a94e2380-ffd8-11e9-8927-b7c30d143643.png)

**Comment by robertboyl** [comment]
Thanks for reply, Lukas! You think theres a good chance of having thumbnails as I want?

Any ideas when more or less?

Thanks!

**Comment by robertboyl** [comment]
Just a note. What I wanted, Nextcloud has. I prefer ownCloud. No way really to edit source code or something and add this feature?

See the video, notice how you can make thumbnails appear larger: https://www.screenpresso.com/=qMQjg

Thanks!
