### ISSUE TITLE
PR template link to changelog README is not working

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36262]
### Steps to reproduce
1. make a PR
2. click "Changelog item, see TEMPLATE"

### Expected behaviour
The changelog template or readme is displayed.

### Actual behaviour
"Not found"

@micbar https://github.com/owncloud/core/blob/master/changelog/README.md works

**Comment by micbar** [comment]
Fixed, thx

**Comment by phil-davis** [comment]
See commit https://github.com/owncloud/core/commit/b5f2457a78e7afd14ba23c4476e5dd62387832b2
