### ISSUE TITLE
Deleting groups not propagated to drop-down for creating users

### ISSUE THREAD

**Issue by sr258** [owncloud/core#36273]
### Steps to reproduce
1. Open user management screen.
2. Delete existing group.
3. Open drop-down that is used to add new (not yet created) users to a group

### Expected behaviour
The deleted group is not listed in the drop-down.

### Actual behaviour
The group is still there.

### Server configuration
**ownCloud version:** ownCloud Enterprise Edition 10.2.1 (stable)

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** Docker Hub

**Comment by phil-davis** [comment]
I deleted a group called "finance" and then clicked on "Everyone" on the admin user management page. Then open the "groups" dropdown for a user. The "finance" group still appears in the list of groups, but can't be selected. It looks a bit odd:

![Deleted-group-in-dropdown](https://user-images.githubusercontent.com/1535615/134150562-85c626c5-3476-4a60-a5c1-fa76ac5d0422.png)

@JanAckermann Maybe this is easy to fix in the JavaScript?
