### ISSUE TITLE
To many active connections with DAVx⁵

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/core#36270]
### Steps to reproduce
1. Install DAVx⁵ from F-Droid (latest-version)
2. Create a new sync with an owncloud server
3. Wait and see after a day a lot of "active" connections in the personal security settings.

### Expected behaviour
Tell us what should happen
Only active connections to the owncloud are shown.
And all inactive connections over Webdav delete after e.g. 30min.

### Actual behaviour
Tell us what happens instead
I see a lot of connections of the last days and if i sync every 30 min or every hour this is a lot.

### Server configuration
**Operating system**:

**Web server:**
Apache2
**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
10.2.1
**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
Android 9 with DAVx⁵ 2.5.5-ose

Some of the connections from the settings:
`DAVx5/2.5.5-ose (2019/09/28; dav4jvm; okhttp/3.12.5) Android/9	vor einem Tag	
DAVx5/2.5.5-ose (2019/09/28; dav4jvm; okhttp/3.12.5) Android/9	vor einem Tag	
DAVx5/2.5.5-ose (2019/09/28; dav4jvm; okhttp/3.12.5) Android/9	vor einem Tag	
DAVx5/2.5.5-ose (2019/09/28; dav4jvm; okhttp/3.12.5) Android/9	vor einem Tag	
DAVx5/2.5.5-ose (2019/09/28; dav4jvm; okhttp/3.12.5) Android/9	vor einem Tag	
DAVx5/2.5.5-ose (2019/09/28; dav4jvm; okhttp/3.12.5) Android/9	vor einem Tag	
DAVx5/2.5.5-ose (2019/09/28; dav4jvm; okhttp/3.12.5) Android/9	vor einem Tag	
DAVx5/2.5.5-ose (2019/09/28; dav4jvm; okhttp/3.12.5) Android/9	vor einem Tag	
DAVx5/2.5.5-ose (2019/09/28; dav4jvm; okhttp/3.12.5) Android/9	vor einem Tag	
DAVx5/2.5.5-ose (2019/09/28; dav4jvm; okhttp/3.12.5) Android/9	vor einem Tag	
DAVx5/2.5.5-ose (2019/09/28; dav4jvm; okhttp/3.12.5) Android/9	vor einem Tag	
DAVx5/2.5.5-ose (2019/09/28; dav4jvm; okhttp/3.12.5) Android/9	vor einem Tag	
DAVx5/2.5.5-ose (2019/09/28; dav4jvm; okhttp/3.12.5) Android/9	vor einem Tag`

Reference issue at DAVx⁵ [https://forums.bitfire.at/topic/2144/missing-logout-after-sync](https://forums.bitfire.at/topic/2144/missing-logout-after-sync)

**Comment by ho4ho** [comment]
Duplicate by https://github.com/owncloud/core/issues/32746 ?
