### ISSUE TITLE
OC 10.3.0, 500 error at Carddav: Exception: explode() expects parameter 2 to be string, null given:

### ISSUE THREAD

**Issue by Rumbelstilzchen** [owncloud/core#36299]
1. Try with any client to sync to Caldav/Carddav

### Expected behaviour
Sync should happen

### Actual behaviour
Error 500 is thrown.

Error message of client:
2019.10.19 11:59:38:916 : Konakte : debug mode : response text : (new String("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<d:error xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\">\n  <s:exception>TypeError</s:exception>\n  <s:message>explode() expects parameter 2 to be string, null given</s:message>\n</d:error>\n"))
2019.10.19 11:59:38:917 : Konakte : debug mode : response code : (new Number(500))
2019.10.19 11:59:38:918 : Konakte: Synchronisation fehlgeschlagen (Schritt: serverSyncCards, URL: https://****/remote.php/dav/addressbooks/users/***/contacts/, Status: 500)

### Server configuration
**Operating system**:

**Web server:**
apache 2.4
**Database:**
mariadb 10
**PHP version:**
7.2.20
**ownCloud version:** (see ownCloud admin page)
10.3.0.4
**Updated from an older ownCloud or fresh install:**
10.2.1
**Where did you install ownCloud from:**
https://download.owncloud.org/community/owncloud-10.3.0.tar.bz2
**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**The content of config/config.php:**
  "config": {
        "instanceid": "5251718f85dbf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.petrosilius.de",
            "192.168.2.56"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "10.3.0.4",
        "dbtype": "mysql",
        "dbhost": "127.0.0.1:3307",
        "dbname": "owncloud91",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "default_language": "de",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": 465,
        "mail_smtptimeout": 30,
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "log_query": false,
        "log_rotate_size": 1048576,
        "logfile": "***REMOVED SENSITIVE VALUE***/data\/owncloud.log",
        "cron_log": false,
        "log_authfailip": true,
        "allowZipDownload": true,
        "maxZipInputSize": 5368709120,
        "maintenance": false,
        "forcessl": true,
        "share_folder": "\/Shared",
        "remember_login_cookie_lifetime": 86400,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "blacklisted_files": [
            ".htaccess"
        ],
        "excluded_directories": [
            "@eaDir"
        ],
        "trashbin_retention_obligation": "auto,30",
        "htaccess.RewriteBase": "\/",
        "filelocking.enabled": true,
        "appstore.experimental.enabled": false,
        "activity_expire_days": 21,
        "mysql.utf8mb4": true,
        "singleuser": false,
        "has_rebuilt_cache": true
    },

**List of activated apps:**
Enabled:
  - activity: 2.5.0
  - bookmarks: 0.10.6
  - brute_force_protection: 1.0.1
  - calendar: 1.6.3
  - configreport: 0.2.0
  - contacts: 1.5.5
  - dav: 0.5.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_mediaviewer: 1.0.0
  - files_sharing: 0.12.0
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - market: 0.5.0
  - notifications: 0.5.0
  - password_policy: 2.0.2
  - provisioning_api: 0.5.0
  - twofactor_totp: 0.6.0
  - updatenotification: 0.2.1
Disabled:
  - comments
  - encryption
  - external
  - firstrunwizard
  - systemtags
  - user_external

**Are you using external storage, if yes which one:**
No
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** 
no
#### Web server error log
No input
#### ownCloud log (data/owncloud.log)
`
{"reqId":"ZVQSyZMNKP6ij5YxoehY","level":4,"time":"2019-10-19T11:59:44+02:00","remoteAddr":"192.168.2.15","user":"Username","app":"webdav","method":"PROPFIND","url":"\/remote.php\/dav\/addressbooks\/users\/Username\/contacts\/","message":"Exception: explode() expects parameter 2 to be string, null given: {\"Exception\":\"TypeError\",\"Message\":\"explode() expects parameter 2 to be string, null given\",\"Code\":0,\"Trace\":\"#0 \\\/PATH_TOcloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php(689): explode(';', NULL)\\n#1 \\\/PATH_TOcloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): Sabre\\\\CardDAV\\\\Plugin->propFindLate(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\CardDAV\\\\AddressBook))\\n#2 \\\/PATH_TOcloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): Sabre\\\\DAV\\\\Server->emit('propFind', Array)\\n#3 \\\/PATH_TOcloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(979): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\CardDAV\\\\AddressBook))\\n#4 \\\/PATH_TOcloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1649): Sabre\\\\DAV\\\\Server->getPropertiesIteratorForPath('addressbooks\\\/us...', Array, 1)\\n#5 \\\/PATH_TOcloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(363): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#6 \\\/PATH_TOcloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(96): Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/PATH_TOcloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(464): Sabre\\\\DAV\\\\Server->emit('method:PROPFIND', Array)\\n#8 \\\/PATH_TOcloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(241): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/PATH_TOcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(326): Sabre\\\\DAV\\\\Server->start()\\n#10 \\\/PATH_TOcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/PATH_TOcloud\\\/remote.php(165): require_once('\\\/PATH_TOcloud...')\\n#12 {main}\",\"File\":\"\\\/PATH_TOcloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/CardDAV\\\/Plugin.php\",\"Line\":689}"}`
#### Browser log
n.a.

**Comment by Rumbelstilzchen** [comment]
I digged a little bit into it:
[https://www.bountysource.com/issues/78488845-default-addressbookserver-php-not-working-in-sabre-4](url) pinned me to CloudSite\lib\composer\sabre\dav\lib\CardDAV\Plugin.php within this file line 685 is making the trouble. If I replace "Thunderbird" by "dummy_string" everything works again as expected. I think this was made for the SoGo-Connector which I'm currently not using for Thunderbird.

**Comment by DeepDiver1975** [comment]
We need to update the sabre/dav dependency.

**Comment by thommierother** [comment]
I also have this issue right now when connecting 10.3 to Thunderbird with CardBook 43. The sabre/dav lib still seems to be in the old version:

{
    "name": "sabre/dav",
    "type": "library",
    "description": "WebDAV Framework for PHP",
    "keywords": ["Framework", "WebDAV", "CalDAV", "CardDAV", "iCalendar"],
    "homepage": "http://sabre.io/",
    "license" : "BSD-3-Clause",
    "authors": [
        {
            "name": "Evert Pot",
            "email": "me@evertpot.com",
            "homepage" : "http://evertpot.com/",
            "role" : "Developer"
        }
    ],
    "require": {
        "php": ">=7.0.0",
        "sabre/vobject": "^4.2.0-alpha1",
        "sabre/event" : "^5.0",
        "sabre/xml"  : "^2.0.1",
        "sabre/http" : "^5.0",
        "sabre/uri" : "^2.0",
        "ext-dom": "*",
        "ext-pcre": "*",
        "ext-spl": "*",

 ??
