### ISSUE TITLE
Review trashbin API acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36302]
The new trashbin API endpoint is currently in `tech_preview`

- [x] review the acceptance tests that we have
- [x] add more acceptance tests as appropriate
- [ ] allow the endpoint to be removed from `tech_preview`

**Comment by phil-davis** [comment]
@dpakach are there enough test scenarios now?

It will be a separate decision to actually remove this API from tech-preview.

**Comment by dpakach** [comment]
@phil-davis Yes I think we can close this now. There are enough tests for the trashbin API IMO
