### ISSUE TITLE
Review public webDAV API acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36301]
The new public webDAV API endpoint is currently in `tech_preview`

- [x] review the acceptance tests that we have
- [ ] add more acceptance tests as appropriate
- [ ] allow the endpoint to be removed from `tech_preview`

**Comment by phil-davis** [comment]
@dpakach do we have enough test scenarios now?
If so, then we can close this. There will need to be a separate decision about when to remove from tech-preview.

**Comment by dpakach** [comment]
@phil-davis Yes, I think I have added enough tests, So we may now close this.
