### ISSUE TITLE
Cron job fails with "sh: 1: ./occ: not found"

### ISSUE THREAD

**Issue by RalfJung** [owncloud/core#36317]
### Steps to reproduce
1. Set up cron job as [described in the docs](https://doc.owncloud.com/server/10.3/admin_manual/configuration/server/background_jobs_configuration.html#cron)

### Expected behaviour
The cron job should work.

### Actual behaviour
The cron job fails with this error:
```
Please use ./occ system:cron
sh: 1: ./occ: not found
```
The first line indicates to me that the docs recommend something outdated.
And the second line says that the "new way" doesn't actually work. And indeed, why does the script assume as `occ` is in the working directory? That seems like an unfounded assumption.

### Server configuration
**Operating system**: Debian Buster

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3.9-1~deb10u1

**ownCloud version:** (see ownCloud admin page) 10.3

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** Your apt repos

**Comment by RalfJung** [comment]
Seems like the proper way to set up the cron job is `php -f /var/www/owncloud/occ system:cron`. But the docs are still wrong and the current behavior of `cron.php` breaks upgraded installations.

Also, to make things worse, that cronjob has output:
```
   13 [------------->--------------]
```
So now I get an email every minute with that output. Great. I can of course send that to `/dev/null` but then I will miss actual errors that might happen.

**Comment by DeepDiver1975** [comment]
> Seems like the proper way to set up the cron job is `php -f /var/www/owncloud/occ system:cron`. But the docs are still wrong and the current behavior of `cron.php` breaks upgraded installations.

@settermjd can you please change the docs to reflect this - THX

@RalfJung the output issue has already been fixed and will be released in 10.3.1 - THX

**Comment by ho4ho** [comment]
> But the docs are still wrong

Documentation by https://github.com/owncloud/docs/pull/1234 updated?

**Comment by RalfJung** [comment]
This is still wrong though:

https://github.com/owncloud/core/blob/547ae805c6b1cbe30c381becdce19b7bb5a9d510/cron.php#L43

When calling `cron.php` as `/path/to/cron.php`, this will search in the wrong directory.
In a shell I'd do `"$(dirname "$0")/occ`; no idea what to do in PHP.

**Comment by olenoerby** [comment]
Hi, although I run my cron jobs every 1 minute my crontab -e looks like this:

`*/1  *  *  *  * php /var/www/owncloud/occ system:cron > /dev/null 2>&1`

And it works perfectly fine.

**Comment by tapmeppe** [comment]
Hello there,
I'm experiencing the same problem: ... 13 [------------->--------------].
Any solution so far?

Server configuration
Operating system: ‪Ubuntu 14.04.6 LTS‬
Web server: Apache
Database: MySQL
PHP version: 7.3.5
ownCloud version: (see ownCloud admin page) 10.3.1
Updated from an older ownCloud or fresh install: Updated
Where did you install ownCloud from: Your apt repos

**Comment by DeepDiver1975** [comment]
> ownCloud version: (see ownCloud admin page) 10.3.1

upgrade to 10.3.2
