### ISSUE TITLE
Problem with update 10.3.0

### ISSUE THREAD

**Issue by Fabikant** [owncloud/core#36339]
Hi,

I am not able to update my owncloud because the app "wallpaper" is incompatible or missing. I have already tried to delete the app by going into the apps folder via FTP. But the app is not listed there. How am I able to delete or deactivate the app? 

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Reparaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable wallpaper
Reparaturwarnung:For manually updating, see https://doc.owncloud.org/server/10.3/go.php?to=admin-marketplace-apps
OC\RepairException: Upgrade is not possible

Thanks for your help!

**Comment by prsnbrg** [comment]
You can disable this app with an occ command:
`occ app:disable wallpaper`

**Comment by Fabikant** [comment]
Thanks for the quick support. Sorry if it is a stupid question but how do I access the occ command on windows?

**Comment by phil-davis** [comment]
You need to run the `occ` command on the ownCloud server. ownCloud server is not supported on Windows. Your ownCloud server will be running somewhere on a *nix system. You have to get a (remote) command line on that system.

**Comment by VicDeo** [comment]
@Fabikant 
https://central.owncloud.org/t/how-to-disable-an-app-without-access-to-the-gui/832

The third way is discouraged nowadays.
