### ISSUE TITLE
Code integrity check error

### ISSUE THREAD

**Issue by magicmisi0** [owncloud/core#36332]
hi
i installed owncloud but it says there are problems with code integrity test.
This is the error:
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- README.md

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => f670106582d841b69eb05009a94f80cb4636e851fbe9b040d82ac9e8a7f62c5a7a3116cfeec71cec89634ca8ebe18b48668332c323d5a4d6fe836a29f54d2e30
                            [current] => 4886c8d58c46aba30f8577efaa04719ff315cb72d68d27374c3649ca9578baef18da9cd7165579c4425a0094d5359804c49600235cccd51737a2c9db613d69b5
                        )

                )

        )

)

What could I do? I moved this file to my files but then it says this file is missing.

**Comment by ho4ho** [comment]
Read documentation shown by link in message could help

https://doc.owncloud.com/server/10.3/admin_manual/configuration/general_topics/code_signing.html#fixing-invalid-code-integrity-messages

**Comment by VicDeo** [comment]
@magicmisi0 
1. download zip or tar package with your current ownCloud version
2. extract `README.md` from the package
3. put `README.md` into your installed ownCloud instance overwriting the existing `README.md`
4. recheck integrity.
That's all.

**Comment by HanSolo80** [comment]
@VicDeo @ho4ho  I am getting this problem every time I update the owncloud instance via the Updater inside the web GUI. It seems there is an issue with the update process, skipping the files README.md and updater/CHANGELOG.md on every update triggered in the web GUI.

**Comment by VicDeo** [comment]
@HanSolo80 yes, this is a known issue of Updater 1.0.0 https://github.com/owncloud/updater/issues/517

Updater 1.0.1 was bundled into ownCloud 10.3.2  so update **from** 10.3.2 shouldn't have this issue (for both mentioned files)

**Comment by HanSolo80** [comment]
@VicDeo Ah, thanks for the info.
