### ISSUE TITLE
Package for Debian 8 doesn't respect PHP 7 dependency

### ISSUE THREAD

**Issue by es-ka** [owncloud/core#36330]
### Steps to reproduce
1. Debian 8 running with OC package repository: http://download.owncloud.org/download/repositories/production/Debian_8.0/
2. Package update using `apt-get update && apt-get upgrade`
3. OC is updated from 10.1.1 to 10.3.0
4. OC does't work because of missing PHP 7
5. downgrade OC to make it work again using http://download.owncloud.org/download/repositories/10.1.1/Debian_8.0/

### Expected behaviour
`apt-get upgrade` should respect the missing dependency for PHP 7 (and refuse to update the OC package) when running Debian oldoldstable with PHP 5.6

### Actual behaviour
The OC package is updated to 10.3.0 while PHP 5.6 is installed only.
(OC 10.2 drops support for PHP 5.6)

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache 2.4

**Database:** MySQL 5

**PHP version:** 5.6

**ownCloud version:** 10.3.0

**Updated from an older ownCloud or fresh install:** updated from 10.1.1

**Where did you install ownCloud from:** official ownCloud repository

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

**Comment by coudot** [comment]
I had the same issue.

Here is how i downgraded:
```
wget https://attic.owncloud.org/download/repositories/10.1.1/Debian_8.0/all/owncloud-files_10.1.1-1+1.1_all.deb
dpkg -i owncloud-files_10.1.1-1+1.1_all.deb
sudo -u www-data /var/www/owncloud/occ upgrade
```

**Comment by ho4ho** [comment]
Found by https://github.com/owncloud/docs/issues/2631:

> 4. To be aware that you'll have to manage the PHP installation independently
