### ISSUE TITLE
Upgrade OwnCloud from 10.2.1-1+1.3 to 10.3.0-1+2.1) - Debian 9

### ISSUE THREAD

**Issue by takenek** [owncloud/core#36341]
After upgrade from 10.2 to 10.3 on Debian 9 and try on maintenance i get:

root@owncloud:~# sudo -u www-data php /var/www/owncloud/occ maintenance:mode --on
An unhandled exception has been thrown:
Error: Class '\OC\Memcache\APC' not found in /var/www/owncloud/lib/private/Memcache/Factory.php:84
Stack trace:
#0 /var/www/owncloud/lib/private/Server.php(447): OC\Memcache\Factory->__construct('58d27460c877d56...', Object(OC\Log), '\\OC\\Memcache\\AP...', '\\OC\\Memcache\\AP...', '\\OC\\Memcache\\Re...')
#1 /var/www/owncloud/lib/composer/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#2 /var/www/owncloud/lib/private/AppFramework/Utility/SimpleContainer.php(108): Pimple\Container->offsetGet('MemCacheFactory')
#3 /var/www/owncloud/lib/private/ServerContainer.php(86): OC\AppFramework\Utility\SimpleContainer->query('MemCacheFactory')
#4 /var/www/owncloud/lib/private/Server.php(1202): OC\ServerContainer->query('MemCacheFactory')
#5 /var/www/owncloud/lib/base.php(831): OC\Server->getMemCacheFactory()
#6 /var/www/owncloud/lib/base.php(566): OC::registerAutoloaderCache()
#7 /var/www/owncloud/lib/base.php(1005): OC::init()
#8 /var/www/owncloud/console.php(64): require_once('/var/www/ownclo...')
#9 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')

ofc i disable in config \OC\Memcache\APC and it`s working but....
2019-10-27T08:28:56+00:00 Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
2019-10-27T08:28:56+00:00 Repair warning: Please install or update the following apps manually or disable them with:
occ app:disable files_videoplayer
2019-10-27T08:28:56+00:00 Repair warning: For manually updating, see https://doc.owncloud.org/server/10.3/go.php?to=admin-marketplace-apps
2019-10-27T08:28:56+00:00 OC\RepairException: Upgrade is not possible
2019-10-27T08:28:56+00:00 Update failed

But link not working :-)
https://doc.owncloud.org/server/10.3/go.php?to=admin-marketplace-apps
Error 404...

Best Regards
TaKeN

**Comment by cwh42** [comment]
As the error message explains:
disable the incompatible app using the command `occ app:disable files_videoplayer`

That worked for me when I just run into that problem.

**Comment by VicDeo** [comment]
1.
>An unhandled exception has been thrown:
Error: Class '\OC\Memcache\APC' not found in /var/www/owncloud/lib/private/Memcache/Factory.php:84

https://owncloud.org/changelog/server/
### 10.3.0 
#### Removed

Dropped APC and XCache support #35782

2. 
>2019-10-27T08:28:56+00:00 Repair warning: Please install or update the following apps manually or disable them with:
occ app:disable files_videoplayer

Please install or update the following apps manually or disable them with:
`occ app:disable files_videoplayer`


3.
>But link not working :-)
https://doc.owncloud.org/server/10.3/go.php?to=admin-marketplace-apps

Works and does a redirect:
```
> curl -I https://doc.owncloud.org/server/10.3/go.php?to=admin-marketplace-apps
HTTP/2 302 
content-type: text/html; charset=utf-8
date: Thu, 05 Dec 2019 11:22:53 GMT
location: /server/10.3/admin_manual/upgrading/marketplace_apps.html
referrer-policy: strict-origin-when-cross-origin
server: Caddy
strict-transport-security: max-age=315360000; preload
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
```
