### ISSUE TITLE
occ app:enable should exit with proper error message if enterprise key is invalid

### ISSUE THREAD

**Issue by xoxys** [owncloud/core#36351]
### Steps to reproduce
1. Disable an enterprise app
2. Set an invalid Enterprise Key
3. Try to enable an enterprise app

### Expected behaviour
The `occ app:enable example-ee-app` command should exit with a proper error message and notify the user that the app will not be enabled due to an invalid license key.

### Actual behaviour
The `occ app:enable example-ee-app` command exited with a success message while the app is still disabled. Only if you look into the owncloud.log you will see an error message about the invalid license key.

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2

**ownCloud version:** 10.3

**Comment by pako81** [comment]
Proposed fix in https://github.com/owncloud/core/pull/36399
