### ISSUE TITLE
[ownCloud v10.3.0.4] Address in mailbox given [@] does not comply with RFC 2822, 3.6.2.

### ISSUE THREAD

**Issue by IBH-55** [owncloud/core#36366]
### Steps to reproduce
1. login with ldap account (local accounts are working fine)
2. create file on built-in storage (where "owncloudmanual.pdf" and 2 folders are located at by default) using the web browser (firefox, in my case)
3. share the file, create a public link and try to send an email 

### Expected behaviour
email should be sent

### Actual behaviour
an error occurs, details from the log file:

`{"reqId":"0wZ3oLC3piANLQKMJpNB","level":3,"time":"2019-11-04T12:59:31+00:00","remoteAddr":"x.x.x.x","user":"ldap.account","app":"PHP","method":"POST","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/notification\/notify-public-link-by-email","message":"Undefined offset: 1 at \/var\/www\/owncloud\/lib\/private\/Mail\/Message.php#67"}
{"reqId":"0wZ3oLC3piANLQKMJpNB","level":3,"time":"2019-11-04T12:59:31+00:00","remoteAddr":"x.x.x.x","user":"ldap.account","app":"sharing","method":"POST","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/notification\/notify-public-link-by-email","message":"Can't send mail with public link to user@domain.com: Address in mailbox given [@] does not comply with RFC 2822, 3.6.2."}`

I have already seen issue #32961, but on owncloud 10.3 there seems nothing to do regarding modifying those two files. also, this is not a general error, it only affects ldap-users.

### Server configuration
**Operating system**: linux ubuntu 16.04 lts

**Web server:** apache 2

**Database:** mysql

**PHP version:** 7.2

**ownCloud version:** (see ownCloud admin page) 10.3.0.4

**Updated from an older ownCloud or fresh install:** updated from 9.0.3 to 9.0.9, then os update ubuntu 14.04 lts to 16.04 lts and owncloud update to 10.3.0.4

**Where did you install ownCloud from:** official installer on owncloud.org

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
no errors have been found.

**Comment by Simon4711** [comment]
Same here. Problem exists for LDAP Users only. Local Users have no errors sending share link by mail.
