### ISSUE TITLE
CI often stucks somewhere without having a code error found

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#36395]
After filing some PR´s using latest master as base, I identify that CI often stucks somewhere in the process. It either gets red or stays at yellow without having a checking error found. It seems that if there are more concurrent PR´s to be processed, the probability of getting stuck is MUCH higher than when you run either late at night or early morning. When it turns green, no code changes have been applied, only rebase and push. Sometimes quite often consecutive... There are no patterns where it will stuck, but it is often at some place where setting up internal settings/environments kill the process. Could it be a physical resource problem?

Here is an example error referenced from #36389
```
apiProxySmoke-3-1-mariadb10.2-php7.1: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
apiProxySmoke-3-1-mariadb10.2-php7.1 – proxy: Failure
```
@phil-davis, @PVince81  you may know more about or can redirect to someonewho might help. It is really annoying 😟

**Comment by phil-davis** [comment]
"stuff happens" I certainly have no control over this. The problems could be:
- in the datacentre where the agents are
- docker.io being down or overloaded
- github having a service interruption
- packagist being down
- any of these have mirror sync problems (packagist has had a few of those)
- network issues anywhere in the path from the drone agent to the needed resources
- drone agents starting on dodgy hardware
- planets out of alignment

@tboerger any comment?

**Comment by tboerger** [comment]
Nothing to add

**Comment by phil-davis** [comment]
We monitor this and do what we can. Closing here, as there nothing we can directly "fix" for this issue.

**Comment by mmattel** [comment]
Sunday ~14:00
https://drone.owncloud.com/owncloud/core/21255/27/9
```
phpunit-php7.1-sqlite-scality — setup-scality 01:03
+ wait-for-it -t 60 scality:8000
services aren't ready in 1m0s
```
👎

**Comment by phil-davis** [comment]
The scality docker image sometimes crashes on startup. And so there is no `scality` !!!
I will make an issue for that, because it would be nice to have a `scality` docker image that is reliable.

**Comment by tboerger** [comment]
@mmattel if you are blaming a tool than you should make sure that it's really the fault of the tool.
