### ISSUE TITLE
GPG apt key expired and/or wrong for 9.0 Release Debian 8.0

### ISSUE THREAD

**Issue by yellowtrolley** [owncloud/core#36396]
### Steps to reproduce
1. wget -nv https://download.owncloud.org/download/repositories/9.0/Debian_8.0/Release.key -O Release.key
2. apt-key add - < Release.key
3. sh -c "echo 'deb http://download.owncloud.org/download/repositories/9.0/Debian_8.0/ /' > /etc/apt/sources.list.d/owncloud.list"
4. sudo apt-get update

### Expected behaviour
apt should update packages

### Actual behaviour
W: Size of file /var/lib/apt/lists/partial/download.owncloud.org_download_repositories_9.0_Debian%5f8.0_Release.gpg is not what the server reported 481 110
W: Size of file /var/lib/apt/lists/partial/download.owncloud.org_download_repositories_9.0_Debian%5f8.0_Release is not what the server reported 976 106
W: GPG error: http://download.owncloud.org  Release: The following signatures were invalid: KEYEXPIRED 1535163442 KEYEXPIRED 1535163442 KEYEXPIRED 1535163644 KEYEXPIRED 1535163442 KEYEXPIRED 1535163442 KEYEXPIRED 1535163442 KEYEXPIRED 1535163442 KEYEXPIRED 1535163644 KEYEXPIRED 1535163442
W: Size of file /var/lib/apt/lists/partial/download.owncloud.org_download_repositories_9.0_Debian%5f8.0_Packages.gz is not what the server reported 1898 110

### Server configuration
**Operating system**: Debian 8

**ownCloud version:** 9.0

**Comment by ho4ho** [comment]
Duplicate by https://github.com/owncloud/core/issues/32521 ?

> OBS master key expired a week ago..supported repositories were fixed accordingly.. 9.x repositories are permanently frozen and locked..nothing there will be fixed, rebuilt or otherwise change.. you have to use the workaround suggested as this won't be fixed, you really have to upgrade to 10.x branch.
>
> https://github.com/owncloud/core/issues/32521#issuecomment-418362442

**Comment by yellowtrolley** [comment]
Thanks, I didn't know that 9.x repositories are permanently frozen and locked.
Upgrading to 10.x is not an option for me right now. I will try the workaround.
