### ISSUE TITLE
Nextcloud string with is.json/is.js translaton

### ISSUE THREAD

**Issue by ho4ho** [owncloud/core#36415]
Translaton has "Nextcloud" within:

https://github.com/owncloud/core/blob/v10.3.1/core/l10n/is.json#L137
https://github.com/owncloud/core/blob/v10.3.1/core/l10n/is.js#L139
https://github.com/owncloud/core/blob/v10.3.1/lib/l10n/is.js#L19-L20
https://github.com/owncloud/core/blob/v10.3.1/lib/l10n/is.json#L17-L18

**Comment by mmattel** [comment]
@ChrisEdS 
I have contacted the location owner of iceland on transifex to either fix this or give me write acces so I can do it. But till today there is no response nore a change. Are you able to fix this?

**Comment by ChrisEdS** [comment]
I'll have a look.

**Comment by ChrisEdS** [comment]
Done. Fixed with the next sync from Transifex. Thank you for reporting @ho4ho and for taking care @mmattel
