### ISSUE TITLE
Review API and webUI tests for special characters

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36430]
Ref: https://github.com/owncloud/files_mediaviewer/issues/148#issuecomment-554290888

We have quite a few tests that have "strange" characters in file and folder names.

Review what we have. Cover any missing parts for file operations (upload, download, rename, with/without chunking, as a received share...) in the API and basics for webUI (slower tests). Specially test with characters in file and folders names that are special in URLs - e.g. `#` `?` and space.

**Comment by dpakach** [comment]
@HariBhandari07 @phil-davis What's the status of this PR, Can we close this?

**Comment by HariBhandari07** [comment]
I think we have added enough tests for file/folders with special characters. So this issue is closed.
