### ISSUE TITLE
when "Allow public uploads" is disabled API responds with different messages, depending on the permissions

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#36443]
### Steps to reproduce
1. disable "Allow public uploads"
2. try to create public shares with different permissions
3. try to update existing shares with different permissions

### Expected behaviour
same message in every case

### Actual behaviour
create share with permission 5: message: `Public upload not allowed` statusCode: 403
create share with permission 7: share is created with permission 1 see #36442
create share with permission 4: message `Public upload disabled by the administrator` statusCode: 403
update existing public share setting permission to 5: message: `Public upload not allowed` statusCode: 400
update existing public share setting permission to 4,7,15: message: `Public upload disabled by the administrator` statusCode: 403

This issue results in different error messages in Phoenix, depending on the selected permission
![image](https://user-images.githubusercontent.com/2425577/69119751-a450a000-0abf-11ea-9b37-c26e024e2e99.png)

![image](https://user-images.githubusercontent.com/2425577/69119767-b0d4f880-0abf-11ea-91a2-8e8d9b7497bc.png)

**Comment by phil-davis** [comment]
We should cover this with core API acceptance test scenarios. Then a developer can easily use and adjust the tests while fixing.

**Comment by skshetry** [comment]
Removing QA-team level, as acceptance has been written in #36463.
