### ISSUE TITLE
When 'Allow public uploads' is disabled cannot create share with permission 5 but creating share with permission 7 works (fallback to permission 1)

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#36442]
### Steps to reproduce
1. disable "Allow public uploads"
2. create a public link with permission 5 ` curl 'http://172.17.0.1/owncloud-core/ocs/v2.php/apps/files_sharing/api/v1/shares' -X POST -u admin:admin --data 'permissions=5&name=Public+link&shareType=3&path=/ssss`
3. do the same with permission 7

### Expected behaviour
both cases should behave the same

### Actual behaviour
with permission 5: 
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>403</statuscode>
  <message>Public upload not allowed</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>
```

with permission 7 the link is created but the permission defaults to 1

**Comment by phil-davis** [comment]
what is the requirement?

When I disable "Allow public uploads", then when someone uses the sharing API to try and create a public link share with at least read and upload (create) in the permissions:
a) the request should be rejected with a `4nn` status code, no share is created
b) the request should be processed with the not-allowed permissions masked out (e.g. create the share with just read permissions) and return a success `2nn` status

There is probably a general requirement to know - if a permissions request has something "not allowed" in the request, do we reject the request straight away, or "downgrade" the request and grant whatever lesser permissions are OK?

@pmaier1 @micbar ?

**Comment by phil-davis** [comment]
This is now a bug report for someone to decide the action. Example automated test scenarios have been added by PR #36458
