### ISSUE TITLE
Tidy-Up invalid Cal-Objects missing END-Tags

### ISSUE THREAD

**Issue by typoworx-de** [owncloud/core#36447]
### Steps to reproduce
I'm experiencing a lot of problems with Calendar-Events received from external contacts (most of them using Office 365 Service).

Today I were receiving 'VObject: Document ended prematurely' several times with several contacts and situations.

Two of them were Calendar-Invitations received from M$-Users with Calendar-Events.
I also got this issue by converting two E-Mails into a task (in Thunderbird+Lightning).

Each time the calendar involved was damaged by the last attached VObjects which completly destroyed synchronisation between Thunderbird and OwnCloud.

I had to manually delete/tidy-up the given events in MySQL.

### Expected behaviour
OwnCloud should try to use some kind of 'tidy' processing trying to avoid this. Of course this is not an issue by OwnCloud, but external VObjects should not destroy the whole fuctionality in OwnCloud as it's bypassing such VObjects in invalid state.

In most cases there simply were missing VObject tags like:
```
END:VTODO
END:VCALENDAR
```
I think it should be easy to check all BEGIN-Tags and check if they're having an END-Tag. If there is a missing tag OwnCloud could try to resolve this by close the (missing Tags) at the end of VObject.

### Actual behaviour
OwnCloud still shows all Events. But neither download in OwnCloud nor Subscription does work anymore (throwing exception).

### Server configuration
**Operating system**:

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
PHP 7

**ownCloud version:** (see ownCloud admin page)
8.1.1 (currently ...)

**Updated from an older ownCloud or fresh install:**
Not yet

May be related to:
#3124, #14659

**Comment by DeepDiver1975** [comment]
> **ownCloud version:** (see ownCloud admin page)
> 8.1.1 (currently ...)

please upgrade 8.1 is long gone.

More recent versions of owncloud have a validator before events are inserted into the database and are rejected.

**Comment by typoworx-de** [comment]
Sounds great - thank you.
