### ISSUE TITLE
Issue with update: "OC\RepairException: Upgrade is not possible"

### ISSUE THREAD

**Issue by B4K4ribuu** [owncloud/core#36472]
Hello everyone !

First, excuse me for my bad english, I'll do my best.

So, we had ownCloud installed on a site web, accessible with an URL like "https://oldsite.com/partage".

Last thuesday (19 november), we changed the site web's directory. I had to reinstall ownCloud.

Unfortunately, I was sick 2 days after the reinstallation. So I made the reinstallation Friday (22 november).

Naturally, I saved our database, our data's directory and the configuration of ownCloud (config/config.php). I reinstalled exactly the same version of ownCloud (10.1.1.1).
After imported all of the data (Database, user's data and config) and setup the password salt and the secret data in the config.php to match with our old database, I could connect myself with the admin user.

Today (Monday 25 november), when I open the login's page, it say "An update is necessary". Okay, why not. When I try to install the update, by hiting the update's button, an error appear:

**OC\RepairException: Upgrade is not possible**

**Avertissement de réparation :You have incompatible or missing apps enabled that could not be found or updated via the marketplace. Avertissement de réparation :Please install or update the following apps manually or disable them with: occ app:disable activity occ app:disable files_pdfviewer occ app:disable files_texteditor occ app:disable gallery occ app:disable templateeditor Avertissement de réparation :For manually updating, see https://doc.owncloud.org/server/10.1/go.php?to=admin-marketplace-apps.**

Hum okay. I understood that I need to install, update or disable the following parts:
- activity
- files_pdfviewer
- files_texteditor
- gallery
- templateeditor
With the commande **occ app:disable _theNameOfTheParts_**

**But, our site web is on an hosted server which isn't allow CLI command.**

How can I fixe it ? Does someone have an idea ?

Thank you.

**Comment by ho4ho** [comment]
> Thanks for reporting issues back to ownCloud! This is the issue tracker of ownCloud, if you have any support question please check out https://owncloud.org/support

**Comment by karakayasemi** [comment]
As @ho4ho stated, here is an issue tracker. You can find several similar support questions at https://central.owncloud.org/. As far as I see, the following answer covers your question: https://central.owncloud.org/t/upgrade-impossoble/14850/2?u=alfredb . Since nothing to be developed about this issue, I am closing it. Thank you.
