### ISSUE TITLE
Review acceptance test steps that process tables

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36518]
Steps that have the form: `Then stuff in the following table should be so (or not so)` are easy to accidentally pass when the table data and/or header row is missing. Or when the header of columns is misspelt or...

e.g. see #36517

If there are effectively no table rows correctly written, then the step code can loop around zero times, checking nothing. So it has no chance to fail.

- [x] review these type of step definitions
- [x] add code so they will fail if the table does not exist/is wrongly written
- [x] fix any broken/missing tables in steps of scenarios

**Comment by dpakach** [comment]
@phil-davis I think we covered all. can we close this now?

**Comment by phil-davis** [comment]
Yes, CI was good on Saturday and Sunday night, so any broken steps in app repos have also been fixed.
