### ISSUE TITLE
no alert is given to second User that the same file is already in use (no locking)

### ISSUE THREAD

**Issue by tyeeel** [owncloud/core#36522]
no alert is given to second User that the same file is already in use.

### Steps to reproduce
1. Alice opens word_file, does some changes
2. Bob opens same synchronized word_file
3. no alert is given to Bob, that the same file is already in use

### Expected behaviour
alert should be given to Bob, that the same file is already in use

### Actual behaviour
no alert is given to Bob, that the same file is already in use

### Server configuration
**ownCloud version:** (see ownCloud admin page)
Owncloud 10

**Updated from an older ownCloud or fresh install:**
new installation

**Where did you install ownCloud from:**
installed on QNAP

### Client configuration
**Browser:**
CHrome 
**Operating system:**
windows 10

**Comment by ho4ho** [comment]
Duplicate by #20983
