### ISSUE TITLE
CalDAV send invitation mail with user email address instead of with the server address as sender.

### ISSUE THREAD

**Issue by magicWF** [owncloud/core#36536]
Hello,

CalDAV send invitation mail with user email address instead of with the server address as sender.

 If I create an appointment and invite another participant to it, then OC sends a mail to this person with an ICS invitation. For this mail the Calender App or OC uses the mail address of the user (mine) and not the no-reply address of the OC server. This is to be problematic for mail delivery, since the server now sends mails (with sender, e.g. icloud .com, gmail .com, …) for which it is not actually responsible.
Mails directly from Owncloud (password reset or activity) are sent correctly with the sender no-reply@ oc.server configured in OC. This works. Only with the Calender App this does not work.
Steps to reproduce

    create a new appointment
    invite another person to this apointment

Expected behaviour

Mail from owncloud has as from-addresse the mail address of the server e.g. no-reply@ server.address
Actual behaviour

Mail from owncloud has asfrom-addresse the mail address of the current user
Server configuration

Operating system: Linux Ubuntu Server 18.04.3 LTS

Web server: Apache/2.4.41 (Ubuntu)

**Database:**mysql Ver 14.14 Distrib 5.7.28, for Linux (x86_64)

PHP version: PHP Version => 7.2.24-0ubuntu0.18.04.1

ownCloud version: (see ownCloud admin page) 10.3.1.1

Updated from an older ownCloud or fresh install: Update from 10.0.10

Where did you install ownCloud from: manual from download from owncloud . org

Signing status (ownCloud 9.0 and above):

No errors have been found.

The content of config/config.php:
```

`<?php
$CONFIG = array (
  'instanceid' => '****',
  'passwordsalt' => '****',
  'secret' => '*******',
  'trusted_domains' => 
  array (
    0 => 'owncloud. domain. local',
    1 => '1.1.1.1',
    2 => 'owncloud.domain',
  ),
  'datadirectory' => '/srv/www/owncloud/data',
  'overwrite.cli.url' => 'h t t p: / / owncloud. domain',
  'dbtype' => 'mysql',
  'version' => '10.3.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '*******',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 2,
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'theme' => '',
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'domain',
  'integrity.check.disabled' => false,
  'files_external_allow_create_new_local' => 'true',
  'appstoreenabled' => 'true',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'mail.domain',
  'mail_smtpport' => '465',
  'mail_smtpname' => 'owncloud @ domain',
  'mail_smtppassword' => '********',
  'mail_smtpsecure' => 'ssl',
  "mail_smtpdebug" => false,
);

```
List of activated apps:

```
Enabled:
  - activity: 2.5.1
  - calendar: 1.6.3
  - comments: 0.3.0
  - configreport: 0.2.0
  - contacts: 1.5.5
  - dav: 0.5.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_mediaviewer: 1.0.1
  - files_sharing: 0.12.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.2.0
  - gallery: 16.1.1
  - market: 0.5.0
  - notifications: 0.5.0
  - provisioning_api: 0.5.0
  - registration: 0.4.3
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external
```

Are you using external storage, if yes which one: local/smb/

**Are you using encryption:**no

Are you using an external user-backend, if yes which one: no
Client configuration

Browser: Thunderbird Ligthning

Operating system: Xbuntu 18.04.3 LTS
Logs
Web server error log
Mail server error log:

Dec 1 21:33:53 dagobert postfix/smtpd[28263]: NOQUEUE: reject: RCPT from mail.domain.local[1xx.1xx.xxx.xxx]: 553 5.7.1 <owncloud@domain. local>: Sender address rejected: not owned by user owncloud@domain. local; from=<owncloud@domain. local> to=user.mail@address proto=ESMTP helo=<owncloud.domain. local>

Thanks for help!

best regards
Maik

**Comment by ho4ho** [comment]
Duplicate by #35953 wanted by #25470

**Comment by magicWF** [comment]
Thanks ho4ho,

this patch is the problem:
https://github.com/owncloud/core/pull/34899

This correction causes problems when sending mails when the  OC-Server tries to send mails with foreign senders (domains for which  the OC MTA is not responsible). In the worst case, my server should send  a mail to Apple or Google that actually comes from them. In order to  reduce the amount of SPAM, the easiest method is not to accept mail from  your own domain if it comes from other servers. This is done using  techniques like DMARC (RFC5322), SPF, DKIM. Therefore, this patch should not be published in this way!

**Comment by ho4ho** [comment]
Better close and discuss with developers in https://github.com/owncloud/core/issues/35953 ? Not good have two issues with same problem?

**Comment by magicWF** [comment]
Sorry, you are right. I was only on #3499, but this was closed.
