### ISSUE TITLE
Test: the fields of the last response should not include does not work with 'expiration' field

### ISSUE THREAD

**Issue by skshetry** [owncloud/core#36545]
The following step does not work if we try to check for `ANY_VALUE`:
```feature
Then the fields of the last response should not include
  | expiration | ANY_VALUE |
```

### Analysis:
[This is due to how `strtotime()` works](https://www.php.net/manual/en/function.strtotime.php#refsect1-function.strtotime-returnvalues). This needs to be handled somewhere here:
https://github.com/owncloud/core/blob/f37a6dc2774d54c16b3fe9b9cff30138bc4a23d7/tests/acceptance/features/bootstrap/Sharing.php#L662-L671

strtotime is passed `ANY_VALUE` which when fails returns `FALSE`. That, when passed to `date()` 
returns the Unix epoch (i.e. 1st January 1970), and the content to assert is no longer `ANY_VALUE`.

This when passed to `doesFieldValueMatchExpectedContent()` then returns false even though the field is still there.

https://github.com/owncloud/core/blob/f37a6dc2774d54c16b3fe9b9cff30138bc4a23d7/tests/acceptance/features/bootstrap/Sharing.php#L629-L645

**Comment by phil-davis** [comment]
@skshetry do you need this for your current user-group-expiration date work?
Are you going to repair it right away, or is it difficult?

**Comment by phil-davis** [comment]
@skshetry done?

**Comment by skshetry** [comment]
@phil-davis, it's not in master, yet. I'll close as soon as it gets into master.
