### ISSUE TITLE
Behaviour for expiry date of user and group shares

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36550]
We have some questions about the required behaviour of the expiry date option for user and group shares (and the same principles should probably apply for public link shares)

1)  When the "expiry date" options are not enabled at all, and the sharing API is used to create or modify a share and specifies an expiry date, what should happen?
a) respond with a 4nn status code and do not do the action
~b) respond with a 2nn status code, create or modify the share using the other parameters provided, and just ignore the expiry date in the request~
~c) respond with a 2nn status code, create or modify the share including setting an expiry date on the share - but the expiry date will be ineffective (because later processing will never check the expiry date~
~d) or ???~
Note: public links seem to do (c) at the moment - so we can consider if their behaviour should be adjusted to (a)
See issue #36568 

2) When the "expiry date" options are enabled, and there is a default expiry date, and a sharing API request comes without explicit mention of an expiry date then:
~a) the default expiry date should be calculated and set, and the response will include an expiry date attribute (that was not in the request)~
b) do not set an expiry date (unless it is enforced)

3) When the "expiry date" options have been enabled for a while, and there are share in the system with expiry dates. Then the admin disables the expiry date options:
a) any expiry dates on existing shares continue to be enforced (but are not displayed in the UI, or in API requests for share info)
b) any expiry dates on existing shares continue to be displayed and enforced
~c) expiry dates on existing shares "hang around" in the database but are not displayed or enforced any more (they "hang around" so that if the admin clicks the "expiry date" option on again in 10 minutes, then the existing expiry will not all be lost)~
~d) expiry dates on existing shares are all removed permanently (so they do not come back when the "expiry date" option is enabled again~

4) When admin reduces the enforced maximum expiry date:
a) existing shares with expiry dates beyond the new maximum stay as they are
~b) existing shares with expiry dates beyond the new maximum get their expiry date reduced~

5) If the admin sets the default expiry date to 0 days (and they could enforce that also):
~a) it means shares created today will expire at the end of the day~
b) 0 is not allowed - see issue #36569 
~c) ???~

**Comment by phil-davis** [comment]
@pmaier1 @micbar or anyone.

We are producing the sharing API acceptance tests and would like to be able to decide which test results are the required behaviour, and which are "not quite correct"

**Comment by pmaier1** [comment]
The expiration date feature can be turned on/off? I didn't know.

Generally, we always followed the policy that we do not change things retroactively when configuration changes. We only use the new configuration for actions that are conducted after the change.

1. I guess a) @micbar 
2. b) do not set an expiry date (unless it is enforced)
3. a) is ok, b) would be better
4. a)
5. b)

**Comment by micbar** [comment]
> The expiration date feature can be turned on/off? I didn't know.
@pmaier1 This is indeed strange.

My observation is the same as @phil-davis in https://github.com/owncloud/core/pull/36531#issuecomment-562915128

IMO that makes no sense.

Either we need 3 options:
1) Enable / disable
2) Set Default
3) Enforce

Currently 1 and 2 are combined in "Set default expiration date".

or we need to rename 1)

@pmaier1 do you agree with our understanding?

**Comment by pmaier1** [comment]
> @pmaier1 do you agree with our understanding?

I think so, yes.

So the behavior is different than with public links? For public links you can't turn the feature itself off. You can just set a default and enforce that. That's what I would have expected for user/group shares as well. As it's a new feature some users would maybe be happy about a on/off switch, though.

**Comment by phil-davis** [comment]
> As it's a new feature some users would maybe be happy about an on/off switch, though.

True, otherwise when sites upgrade they  would suddenly have the new user-group-share expiration date appear and no way to get back to the old behaviour.

**Comment by phil-davis** [comment]
For existing installations that upgrade, these new user-group-share-expiration options will all be off.

For new installations, do we want to have any of this enabled by default?

**Comment by pmaier1** [comment]
For new installations it could be enabled by default, yes. We did the same for pending shares in order to not confuse existing installations but to directly show features to new installations.

**Comment by phil-davis** [comment]
1. After discussion we have ended up that the options are for "enable default expiration date". So the new expiry date field in the UI will always appear and be available to users. If "enable default expiration date" is off, then the expiry date field will be empty and so the system defaults to the current behaviour - a new share does not expire.
So item 1 is not relevant any more.

2. (b) happens - sharing API requests that do not mention `expireDate` do not get the default applied

3. not relevant any more - there is no longer the concept of "Then the admin disables the expiry date options".

4. works

5. (a) happens, we are allowing default expiration days to be zero. See issue #36569

**Comment by phil-davis** [comment]
One result of all this is that an existing installation will "suddenly" have users being able to see a new expire date field when they click on the share details (i.e. where they currently can click to change the detailed share permissions, when that opens they will also see an expire date field). For existing systems, that expire date field will be empty.

IMO this is OK. But I am just pointing it out, in case there is a policy of new features being "totally" backward-compatible/optional.

**Comment by phil-davis** [comment]
ToDo:
- [ ] check what we have done so far in automated tests for UI and API about default expiry date (IMO we have tests that cover default expiry date set/not set)
- [ ] check what tests we have that check that the share expiry only has effect at the end of the day (e.g. share expires 2021-05-20, the share should work at 2021-05-20:23:59 and then stop working when the date/time gets to 2021-05-21:00:00)
- [ ] add any general test coverage that is needed
- [ ] add any coverage for the end-of-day expiry that is needed

This applies to user, group, federated and public link shares.

**Comment by kiranparajuli589** [comment]
### Acceptance tests coverage for default expiry date in shares
- API
  -  `Scenario Outline:` sharing with default expiration date enabled but not enforced for users, user shares without specifying expireDate
  -  `Scenario Outline:` sharing with default expiration date enabled but not enforced for users, user shares with expiration date
  -  `Scenario Outline:` sharing with default expiration date not enabled, user shares with expiration date set
  -  `Scenario Outline:` sharing with default expiration date enabled but not enforced for users, user shares with expiration date and then disables
  -  `Scenario Outline:` sharing with default expiration date enabled and enforced for users, user shares with expiration date and then disables
  -  `Scenario Outline:` sharing with default expiration date enabled but not enforced for groups, user shares without specifying expireDate
  -  `Scenario Outline:` sharing with default expiration date enabled but not enforced for groups, user shares with expiration date
  -  `Scenario Outline:` sharing with default expiration date not enabled for groups, user shares with expiration date set
  -  `Scenario Outline:` sharing with default expiration date enabled but not enforced for groups, user shares with expiration date and then disables
  -  `Scenario Outline:` sharing with default expiration date enabled and enforced for groups, user shares with expiration date and then disables
  -  `Scenario Outline:` sharing with default expiration date enabled and enforced for users, user shares without setting expiration date
  -  `Scenario Outline:` sharing with default expiration date enabled and enforced for users, user shares with expiration date more than the default
  -  `Scenario Outline:` sharing with default expiration date enabled and enforced for users/max expire date is set, user shares without setting expiration date
  -  `Scenario Outline:` sharing with default expiration date enabled and enforced for users/max expire date set, user shares with expiration date more than the max expire date
  -  `Scenario Outline:` sharing with default expiration date enabled and enforced for users/max expire date is set, user shares and changes the max expire date greater than the previous one
  -  `Scenario Outline:` sharing with default expiration date enabled for users/max expire date is set, user shares and changes max expire date less than the previous one
  -  `Scenario Outline:` sharing with default expiration date enabled and enforced for groups, user shares without setting expiration date
  -  `Scenario Outline:` sharing with default expiration date enabled and enforced for groups, user shares with expiration date more than the default
  -  `Scenario Outline:` sharing with default expiration date enabled and enforced for groups/max expire date is set, user shares without setting expiration date
  -  `Scenario Outline:` sharing with default expiration date enabled and enforced for groups/max expire date set, user shares with expiration date more than the max expire date
  -  `Scenario Outline:` sharing with default expiration date enabled for groups/max expire date is set, user shares and changes the max expire date greater than the previous one
  -  `Scenario Outline:` sharing with default expiration date enabled for groups/max expire date is set, user shares and changes max expire date less than the previous one
  -  `Scenario Outline:` sharing with default expiration date enforced for users, user shares to a group without setting an expiration date
  -  `Scenario Outline:` sharing with default expiration date enforced for groups, user shares to another user
  -  `Scenario Outline:` sharing with default expiration date enforced for users, user shares with invalid expiration date set
  -  `Scenario Outline:` sharing with default expiration date enforced for users, user shares with different time format
  -  `Scenario Outline:` user shares with humanized expiration date format
  -  `Scenario Outline:` user shares with humanized expiration date format in past
  -  `Scenario Outline:` user shares with invalid humanized expiration date
  -  `Scenario Outline:` sharing with default expiration date enforced for users, user shares with past expiration date set
  -  `Scenario Outline:` sharing with default expiration date enforced for users, max expire date is 0, user shares without specifying expiration date
  -  `Scenario Outline:` sharing with default expiration date enforced for users, max expire date is 1, user shares without specifying expiration date
  - `Scenario Outline:` Create a public link with default expiration date set and max expiration date enforced

- webUI
  // tests/acceptance/features/webUISharingExternal2/createFederationSharing.feature
  - Scenario: expiration date is disabled for federation sharing, sharer checks the expiration date of a federation share
  - Scenario: expiration date is enabled for federation sharing, sharer checks the expiration date of a federation share
  - Scenario Outline: expiration date is enforced for federation sharing, user shares file
  - Scenario: expiration date is enforced for federation sharing, user shares and tries to change expiration date more than allowed
  - Scenario: expiration date is enforced for federated sharing, user receives a share with expiration date and reshares with expiration date less than the original with a local user
  - Scenario: expiration date is enforced for federated sharing, user receives a share with expiration date and reshares with expiration date less than the original with another federated user
  - Scenario: expiration date is enforced for federated remote sharer, local receiver reshares received file with another local user
  - Scenario: expiration date is enforced for federated remote sharer, local receiver reshares received file with another federated user
// tests/acceptance/features/webUISharingInternalGroups2/shareWithGroupUsingExpirationDate.feature
  - `Scenario:` expiration date is disabled for sharing with groups, user shares with a group
  - `Scenario:` expiration date is disabled for sharing with groups but enabled for sharing with users, user shares with a group
  - `Scenario:` expiration date is enabled for sharing with groups, user shares a file with a group
  - `Scenario Outline:` expiration date is enforced for group, user shares a file
  - `Scenario:` expiration date is enforced for group, user shares and tries to change expiration date more than allowed
  - `Scenario:` expiration date is enforced for group, user reshares received file with the group
  - `Scenario:` expiration date is enabled but not enforced for group, user reshares received file with group
  - `Scenario:` expiration date is enabled but not enforced for group, user reshares received file with group, but removes default expiration date
  - `Scenario:` expiration date is enabled but not enforced for group, user reshares received file with user, but changes expiration date
  - `Scenario:` expiration date is enabled but not enforced for group, user shares to group through api and checks the expiration date on webUI
  - `Scenario:` expiration date is enabled but not enforced for group, user receives a share with expiration date and reshares with expiration date less than the original
  - `Scenario:` expiration date is enabled but not enforced for group, user receives a share with expiration date and reshares with expiration date in future than the original
  - `Scenario:` expiration date is enabled and enforced for group, user receives a share with expiration date and tries to reshare with expiration date less than the original
  - `Scenario:` expiration date is enabled and enforced for group, user receives a share with expiration date and tries to reshare with expiration date further in future than the original
  - `Scenario:` expiration date is enabled and enforced for group, user receives a folder from a group share with expiration date and shares sub-folder with group
  - `Scenario Outline:` expiration date is disabled for sharing with group, user shares file with group and sets expiration date

**Comment by phil-davis** [comment]
@kiranparajuli589 did you notice anywhere if the tests are able to check that a share expires at the end of the specified day?

**Comment by phil-davis** [comment]
Note: #38775 should fix a problem with the expire-shares background job.

But it would still be useful to think of a way to automate end-to-end tests that confirm that shares expire at the end of the specified expiry date.

**Comment by phil-davis** [comment]
@kiranparajuli589 that confirms that the expiration date can be set to today.
But we also want to know that the share is actually accessible up to the end of "today". (It might stop working part way through the day?) The challenge is to effectively move forward in time to 23:59 and test that the share works. And do similar for a share that expires tomorrow - "move forward in time" to tomorrow:23:59 and test that the share works, then move forward another minute and see that the share disappears.

**Comment by phil-davis** [comment]
@kiranparajuli589 the ability to set a share to expire in the past has been added to the testing app now https://github.com/owncloud/testing/pull/173
You should be able to use it in core tests.

**Comment by kiranparajuli589** [comment]
TODO:
- [ ] for each type of share(user, group, and link), set expiration to some future date, and expire it finally make sure the share does not exist

**Comment by phil-davis** [comment]
The behavior for each type of share now has tests that confirm that shares that expire in the past are correctly automatically removed, and shares that expire "today" are not removed. Closing this issue.

The behavior is that all shares keep working until the end of the day on which they expire.
