### ISSUE TITLE
expireDate can be specified in any date-time format

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36558]
When using the sharing API and sending `expireDate` in a request to create/modify a share, the documentation https://doc.owncloud.com/server/developer_manual/core/apis/ocs-share-api.html#create-a-new-share says:
```
An expire date for public link shares. This argument expects a date string in the following format 'YYYY-MM-DD'
```

But if you send the `expireDate` in any format that https://www.php.net/manual/en/function.strtotime.php understands, then that also works - e.g. `+3 days` or `01/02/2020`

We are adding a feature to have expiry dates for user and group shares. The feature PR also behaves like this, allowing an extensive range of ways to send `expireDate`

Is it OK that this extended behaviour works?

**Comment by phil-davis** [comment]
I am asking this because, if we keep allowing the extended behaviour to work, then there might be some clients that (maybe unintentionally) use it - send `+7 days` instead of calculating the actual date 7 days in the future and sending that.

Once clients are using the flexibility, then we will need to retain it on other server implementations (e.g. OCIS)

@micbar @PVince81 @DeepDiver1975 or whoever should have an opinion.

**Comment by phil-davis** [comment]
I added this to 10.4.0 project so we discuss it along with the user-group-share-expiry review.

**Comment by micbar** [comment]
@pmaier1 @phil-davis @felixheidecke @jvillafanez Let us sit together.

**Comment by jvillafanez** [comment]
From my point of view, "YYYY-MM-DD" is the one that is officially supported. The rest isn't officially supported (unless @pmaier1 says otherwise) and they're in a "use it at your own risk if it works" state, so if something breaks, you've been warned.

**Comment by phil-davis** [comment]
Any more opinions?
Otherwise I will close this and the behaviour can be left as it is - specifying expiry dates in various date formats works but is not officially supported and might break/change any time.

**Comment by jvillafanez** [comment]
We can leave the ticket open. It's something to discuss if we want to enforce an specific format or not, but I don't think it's a priority at the moment.

**Comment by phil-davis** [comment]
I remved from the 10.4 project, because this is now a discussion issue and not to be "finished" for 10.4
