### ISSUE TITLE
Owncloud update failure

### ISSUE THREAD

**Issue by Theater-im-Pariser-Hof** [owncloud/core#36564]
I did press the button UPDATE in our owncloud version 10
Now the cloud can not be reached any more. It says it is in maintanance...
This is the error:
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet 
Reperaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Reperaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable files_clipboard
Reperaturwarnung:For manually updating, see https://doc.owncloud.org/server/10.1/go.php?to=admin-marketplace-apps
OC\RepairException: Upgrade is not possible

**Comment by VicDeo** [comment]
@Theater-im-Pariser-Hof you have `files_clipboard` app that is not compatible with a new OC version.

please follow these instructions https://central.owncloud.org/t/upgrade-impossoble/14850/2?u=alfredb

**Comment by Theater-im-Pariser-Hof** [comment]
Hi Viktar, thanks you soooo much, now the cloud is back and working. I appreaciated your help very much. 

Just wonder, if in general the updater should not be used? Are there often problems?
Because the cloud now says (after login) --> ownCloud 10.3.2 is available. 
Should I again try the updater?

**Comment by Theater-im-Pariser-Hof** [comment]
This is the version we do run
version 10.1.1.1 
versionstring 10.1.1

**Comment by VicDeo** [comment]
@Theater-im-Pariser-Hof 
> if in general the updater should not be used? Are there often problems?

I had nothing except incompatible apps and minor integrity check error. https://github.com/owncloud/core/issues/36332
Incompatible/missing apps is not an web updater issue, manual upgrade will cause the same result as this is a sanity check done by core before the database upgrade process is started.

>Should I again try the updater?

Beware that 10.1.1 is the last  available version with PHP 5.6 support
You can migrate further to 10.3.2 if your sever has PHP 7.0+

**Comment by Theater-im-Pariser-Hof** [comment]
Thanks a lot for the help. The updater now did work and update to 10.3.2
Beside the integrity checks all fine.
