### ISSUE TITLE
Recovery way if harddisk fail [suggestion]

### ISSUE THREAD

**Issue by scorninpc** [owncloud/core#36574]
### Steps to reproduce
1. Burn server external disk
2.Add new external disk
3.Go to all clients copying files to the new hard disk

### Expected behaviour
I think if server detect missing physical files, it could ask to client something to download the files from client again

### Actual behaviour
404 forbiden. I need to copy all client files to another folder. remove ownclould folder. When client try to remove files, it show an error. Restart client and it's ok. So, I copy files back to the owncloud folder. Client upload fresh files

### Server configuration
Raspberry as server, Debian Mate and Windows 7 as client

**Web server:**
Apache

**Database:**
Postgresql  9.2

**PHP version:**
7.2

**ownCloud version:** (see ownCloud admin page)
10.3.0

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Comment by esackbauer** [comment]
https://doc.owncloud.org/server/10.3/admin_manual/maintenance/backup.html

**Comment by scorninpc** [comment]
I cannot be more clean then I was. Sorry, but thank you

**Comment by ho4ho** [comment]
Already possible by https://doc.owncloud.com/server/10.3/admin_manual/configuration/server/occ_command.html#maintenance-commands by:

> maintenance:data-fingerprint        Update the systems data-fingerprint after a backup is restored
