### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by Theater-im-Pariser-Hof** [owncloud/core#36575]
After updater I have missing files (listed after integrity check)

- core
	- FILE_MISSING
		- README.md
		- ocm-provider/index.php
		- updater/CHANGELOG.md

I read some threads here, how to fix. 
I am still not sure, where do I get those files? Where can I download files or tar?

Thanks

**Comment by Theater-im-Pariser-Hof** [comment]
Now running Version 10.3.2

**Comment by phil-davis** [comment]
I just checked and all those files are in the tarball https://download.owncloud.org/community/owncloud-10.3.2.tar.bz2
Not sure how you lost them.

**Comment by Theater-im-Pariser-Hof** [comment]
Thanks a lot, I got it fixed now.
