### ISSUE TITLE
Owncloud installation on NTFS (mixed/docker/partition/etc)

### ISSUE THREAD

**Issue by TNCS-git** [owncloud/core#36589]
This is a long overdue issue that needs to be addressed even at the latest v10.3.2, if the data folder is being pointed on to a NTFS partition which will be granted by a screen with the following message:

Your Data directory is readable by other users
Please change the permissions to 0770 so that the directory cannot be listed by other users.

Some of the many historical workaround:
https://forum.owncloud.org/viewtopic.php?t=25043
https://forum.owncloud.org/viewtopic.php?t=34924

Where Nextcloud acknowledged and fixed the issue:
https://github.com/nextcloud/server/issues/3245
By a string added to the config.php
'check_data_directory_permissions' => true, (https://docs.nextcloud.com/server/12.0/admin_manual/configuration_server/config_sample_php_parameters.html)

Fix is still valid by manually modify the util.php under owncloud/lib/private/legacy/

**Comment by ho4ho** [comment]
By https://central.owncloud.org/search?q=ntfs%20readable%20order%3Alatest found by @pmaier1 

> NTFS does not support Linux file permissions and ownCloud server does not support NTFS as primary storage. Please use a Linux file system.

and

> Well, the docs say that implicitly. Only Linux is supported as a server operating system (https://doc.owncloud.org/server/10.0/admin_manual/installation/system_requirements.html#server). As you can't install Linux on a NTFS partition you can't use ownCloud with it either. In the end it does not make sense to list all "supported/unsupported" file systems in the docs. You can only use ownCloud Server on Linux so you can only use the file systems that Linux runs on as a primary storage (apart from storages you connect via S3 but that's another story).

**Comment by TNCS-git** [comment]
There are many instance that this can happen, which is why NextCloud support disabling the check. One popular instance is to install owncloud under Linux Docker environment with Windows Host.

With my instance, while ownCloud is under Linux on ext partition, I've decided to mount the data and point onto NTFS partition, due to - I have largely Windows based workstation, if the system crap out, I can restore/move the data easily among any Window workstation by removing the drive without the need of a person being very technical.

**Comment by ho4ho** [comment]
What if NTFS partiton / filesystem problematic cause data loss on server?

> We tried to work around some shortcomings like file system limitations by implementing an abstraction purely for Windows.

https://owncloud.org/news/owncloud-server-8-1-will-not-support-windows-as-server-platform-natively/

**Comment by TNCS-git** [comment]
I hear where you coming from, even I don't expect development work to be done incorporating NTFS (as least not in the short term?) file system. But, if you look carefully, all the NextCloud team did was to include a function to bypass the file system check as a workaround. If data loss is a concern, I think ownCloud could implement the function, and don't even include the string by default installation, so people who want to use the option to bypass files system check need to acknowledge the risk by simply indicate at the manual and input the string manually? I think that a pretty sound 'workaround'.
