### ISSUE TITLE
RFE: make document editors functional with external links

### ISSUE THREAD

**Issue by herrdeh** [owncloud/core#36598]
At the moment, I can only online edit files, when I am logged into my owncloud, or someone else is. Often, I do cooperate with people from outside my company, who do not have access to my owncloud.

I'd like to send them public links to the file in question. When creating the link, I'd like to have a checkbox "make file editable". With this box checked, the receiver of the link is offered to edit the file with those editors I've installed at my owncloud, let it be text, OpenDoc files or whatever.

Normally, I'll send these links to one single person, so consistency or versioning is no real problem.

**Comment by ho4ho** [comment]
Already possible by ownCloud?

https://owncloud.org/news/edit-document-collabora-directly-public-link/
