### ISSUE TITLE
logout failed after using nginx https reverse proxy

### ISSUE THREAD

**Issue by wolf-joe** [owncloud/core#36595]
# Steps to reproduce
1. run ownCloud in port 7005
2. config Nginx HTTPS reverse proxy in port 8005
3. login ownCloud in brower, "admin" -> "Log Out" button link to "http://domain:8005/logout?xxx"
4. click "Log Out" button, 400 error occurred
4. change url in address bar to "https://domain:8005/logout?xxx", logout success

### Expected behaviour
"admin" -> "Log Out" button link to "https://domain:8005/logout?xxx"

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Nginx

**ownCloud version:** 10.3.2 (stable)

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** [Installing with Docker
](https://doc.owncloud.com/server/latest/admin_manual/installation/docker/)

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**Comment by ho4ho** [comment]
Duplicate by https://github.com/owncloud/core/issues/30097 cause by wrong configuring:

https://doc.owncloud.com/server/10.3/admin_manual/configuration/server/reverse_proxy_configuration.html

**Comment by wolf-joe** [comment]
> Duplicate by #30097 cause by wrong configuring:
> 
> https://doc.owncloud.com/server/10.3/admin_manual/configuration/server/reverse_proxy_configuration.html

that issue is cause by HOST configure, but this issue is cause by HTTP Protocol.
PS: [my Nginx configure](https://yooo.ltd/2019/12/16/Docker%E5%BF%AB%E9%80%9F%E9%83%A8%E7%BD%B2ownCloud%E5%B9%B6%E9%85%8D%E7%BD%AEHTTPS/#%E9%85%8D%E7%BD%AENginx%E8%BD%AC%E5%8F%91-HTTPS)

**Comment by ho4ho** [comment]
Still checked config.php and ask for support by https://central.owncloud.org/ ?

**Comment by megafetis** [comment]
Same error with IIS reverse proxy.

**Comment by NinjaTycoon** [comment]
> Duplicate by #30097 cause by wrong configuring?
> 
> https://doc.owncloud.com/server/10.3/admin_manual/configuration/server/reverse_proxy_configuration.html

The fix on 30097 is a terrible hack as that host becomes the ONLY way in.  I need for the INTERNAL as well as multiple public hosts working.  

Ironically, the host name isn't even an issue.  The ONLY part of the URL that is incorrect is the HTTP scheme.  Sometimes it does a 302 redirect with the Location header set with "http".  Some links are direct, such as logout or the links in Activity.  Some things work just fine once logged in, likely just using relative paths.  

I've tried everything I can to override this in the Apache HTTPD doing the reverse proxy to no avail.  Rewrite not invoked on 400 error.  Can't find a way to change the "Location" header intelligently.  

Someone suggested he got it working via nginx with header changes in this discussion:

https://central.owncloud.org/t/issue-with-redirect-from-https-to-http/30247/9

But, I could not get it to work using this in Apache:

Header set X-Forwarded-Port 444
Header set X-Forwarded-Proto https

Am I missing something?  Setting headers is the perfect solution though if owncloud looks for them as it will allow owncloud to maintain any backward compatibility it requires outside of the reverse proxy setup.  If it just used "https" every time X-Forwarded-Proto was set to "https" in the request, I believe the problem would be solved.

**Comment by ho4ho** [comment]
ownCloud + nginx reverse proxy working by me like:

nginx config:
```
  location / {
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass https://internalsystem.local;
  }
```

owncloud config.php:
```
  'overwriteprotocol' => 'https',
```

Not problem having like this.

**Comment by NinjaTycoon** [comment]
@ho4ho Thanks!  What I needed was 

```
  'overwriteprotocol' => 'https',
```

That allowed everything to work except LOCAL_IP:8080 from a PC browser, which wasn't critical since the reverse proxy is on the same machine allowing local LAN access without having to use any public IP/DNS.  Ironically, LOCAL_IP:8080 did still work from mobile. 

Was also able to accomplish this in the docker-compose.yml with:

```
  - OWNCLOUD_OVERWRITE_PROTOCOL=https
```

But, setting it in the .env didn't to take effect.
