### ISSUE TITLE
Acceptance tests for occ user:sync command

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36597]
Add acceptance tests for the `occ user:sync` command covering:

- [x] a full default sync -- https://github.com/owncloud/user_ldap/pull/497
- [x] sync a specific user -- https://github.com/owncloud/user_ldap/pull/497
- [x] sync a user that is a substring of some other LDAP user (e.g. sync `user1` when there is also a `user11` existing) - to cover code fix in PR #36576 -- https://github.com/owncloud/user_ldap/pull/508
- [x] sync a user that is a substring and superstring of some local user -- https://github.com/owncloud/user_ldap/pull/508
- [x] sync a local user (probably should exit with success and be a NOOP) -- https://github.com/owncloud/user_ldap/pull/506

The tests will probably be easiest to put in the `user_ldap` app.

**Comment by phil-davis** [comment]
@kiranparajuli589 please also test some "error" cases, e.g. trying to sync a user that does not exist at all...

See issue https://github.com/owncloud/user_ldap/issues/515

**Comment by kiranparajuli589** [comment]
@phil-davis different acceptance tests scenarios for `user:sync` was added..
so, closing...
