### ISSUE TITLE
Refactor UI acceptance tests to not rely on the remote federated server UI

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36607]
Some acceptance test scenarios login to the remote federated server and "test" the UI there. Actually the federated server can be running `daily-master-qa` or `latest` (not the code of the current PR under test). So the test is not really useful, and also the test might fail if the current PR has UI features/changes that change the UI. The test code in the current PR will not be the right code to drive the "old" UI on the federated server.

Refactor the test scenarios so that we never need to login to the remote federated server webUI. Usually the refactoring will be one of:

- turn the scenario around so that the UI actions are done on the local server, and setup (Given) or result checks (Then) are done on the remote server
- split the scenario into 2 scenarios (when it is logging in to both the local and remote server UI), so that whatever 2 (local and remote) things are being checked are done separately

**Comment by dpakach** [comment]
I think we still need to clear up the unnecessary step.
