### ISSUE TITLE
can't add a local storage.

### ISSUE THREAD

**Issue by WuG978** [owncloud/core#36623]
### Steps to reproduce
I installed owncloud with docker follow the official document. I wanna mount a mobile disk for saving owncloud files. According to Admin Manual, enabled local storageh in my owncloud installation's `config/config.php`, add the follow configuration: `'files_external_allow_create_new_local' => 'true',`
then mount my disk in /mnt/owncloud_1T. After that run the follow command:
`docker run -it -v /mnt/owncloud_1T :/mnt/owncloud _1T` owncloud/server:10.3 /bin/bash`
`chmod -R www-data:root /mnt/owncloud_1T`
All done, open https://owncloudIP:port, and sign by admin. In the setting of storage, add /mnt/owncloud. but it is not available.

I dont kown why, can you help me?

**Comment by WuG978** [comment]
![image](https://user-images.githubusercontent.com/38772075/71311852-d35f8600-245e-11ea-9991-d92dccec03f3.png)

**Comment by ho4ho** [comment]
> I dont kown why, can you help me?

Ask for support by https://central.owncloud.org/ ?

**Comment by WuG978** [comment]
> > I dont kown why, can you help me?
> 
> Ask for support by https://central.owncloud.org/ ?

Thanks for your reply, I have already deal with the problem.

**Comment by CleanMachine1** [comment]
For anyone who may find this, one solution is to use webDAV on the server.
