### ISSUE TITLE
Can´t open oC generated tar files with MacOS Catalina

### ISSUE THREAD

**Issue by haukman** [owncloud/core#36721]
### Steps to reproduce
1. Create a folder and upload some files to it
2. Mark the folder and click on "download"
3. Try to open tar-archive

### Expected behaviour
MacOS should be able to open the archive

### Actual behaviour
Error:

<img width="376" alt="grafik" src="https://user-images.githubusercontent.com/25486818/71991636-1ed2ac00-3235-11ea-9e64-a6ec2b8ed6d9.png">

### Server configuration

**ownCloud version:** (see ownCloud admin page) 10.3.2

MacOS version:

<img width="577" alt="grafik" src="https://user-images.githubusercontent.com/25486818/71992142-3f026b00-3235-11ea-8a49-bd8d817388a0.png">

**Comment by DeepDiver1975** [comment]
TarStreamer has an issue - https://github.com/owncloud/TarStreamer/issues/10 - might be related ....

**Comment by pako81** [comment]
Confirmed that https://packagist.org/packages/owncloud/tarstreamer#2.0.0 solves the issue. Since PR https://github.com/owncloud/core/pull/36722 which bumps tarstreamer to v2.2.0 has been recently merged, 10.4.0 will include the fix.

**Comment by phil-davis** [comment]
To get into 10.4.0 it needs to end up in the core `release-10.4.0` branch.
That is PR https://github.com/owncloud/core/pull/36728
@micbar what is the decision about this - add to 10.4.0 (so will come in 10.4.0RC2) or wait until 10.4.1?

**Comment by pako81** [comment]
@phil-davis sorry, my bad. You are totally right. Let's wait for a decision then.

**Comment by mmattel** [comment]
#36728 (Dependency bumps for 10.4 20200109) see above, got merged, ready to close this PR?

**Comment by VicDeo** [comment]
Closing as 10.4.0 has been released.
