### ISSUE TITLE
Webdav public files API issue with file and folder sizes

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#36741]
### Steps to reproduce

1. Setup [Phoenix](https://github.com/owncloud/phoenix) which uses said API
1. Inside of Phoenix
1. Create a folder "test"
1. Open the link share panel on "test"
1. Create a public link with "Editor" role (which will allow viewing and uploading)
1. Open public link in Phoenix
1. Create a folder "sub"
1. Enter the "sub" folder
1. Upload a few files with non-zero size
1. Refresh the page and check the size column
1. Go back to the parent folder and check the size of the "sub" folder

### Expected result
Correct size for the uploaded files.
Correct combined size for the "sub" folder.
In the Webdav response:
- folder size must be in "oc:size"
- file size must be in "dav:getcontentlength"

### Actual result
Folder size is correct but all files appear with 0 bytes size.
In the Webdav response:
- folder **and** file size is returned in "oc:size"
- "dav:getcontentlength" is always zero

See:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/277525/72143997-029b5000-3398-11ea-9dbb-a2e86b7e7881.png">

I had a quick look at the Sabre plugin but didn't find any obvious issue there. The problem is likely hidden in some implicit bits of Sabre DAV.

@DeepDiver1975

**Comment by C0rby** [comment]
After a long debugging session I found out that the `FileCustomPropertiesPlugin` is not getting added in `core/apps/dav/lib/Server.php:265` because of the condition in line _243_. The user in from the user session is null.

**Comment by C0rby** [comment]
Further investigation showed that this is not the source of the issue.
Will debug more.
