### ISSUE TITLE
Update to sabre/dav 4.0.3

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36742]
https://github.com/sabre-io/dav/releases/tag/4.0.3

TBD - I will write some reasons...

**Comment by DeepDiver1975** [comment]
#36743 from dependabot ;-)

**Comment by phil-davis** [comment]
I am used to dependabot only running once a week in core - every Monday night.
I guess it has changed to check much more regularly.

**Comment by DeepDiver1975** [comment]
> I guess it has changed to check much more regularly.

I triggered is manually ;-)
