### ISSUE TITLE
Cannot reshare a file when Secure view is enabled

### ISSUE THREAD

**Issue by davitol** [owncloud/core#36751]
### Steps to reproduce
1. Having oC server 10.4.0. RC1 and richdocuments: 2.2.0 and Secure View enabled
2. Admin user shares a file with user1 with can share permission granted
3. user1 tries to reshare with user2 the previous file

### Expected behaviour
The file is reshared

### Actual behaviour

An error is shown in Files View ```Cannot set the requested share attributes```. No logs are spotted in owncloud.log
![Screen Shot 2020-01-13 at 12 01 28](https://user-images.githubusercontent.com/10596560/72253451-e13d9c80-3601-11ea-979d-e8acdbba8cec.png)

![Screen Shot 2020-01-13 at 12 06 24](https://user-images.githubusercontent.com/10596560/72253483-f1557c00-3601-11ea-84db-f22d94617482.png)

**Note** Disabling Secure View the reshare works fine

### Server configuration
ownCloud 10.4.0. RC1 and richdocuments: 2.2.0

@pmaier1 the error message needs to be more user friendly
@mrow4a maybe for verifying the behavior It looks like a regression. Works in oC 10.3.2. Maybe related to https://github.com/owncloud/core/pull/36265 ?

**Comment by pmaier1** [comment]
For shares with Secure View permissions, disabled resharing is expected. To allow resharing there needs to be some more logic in place to prevent privilege escalations. For regular shares, resharing should be possible, though.

**Comment by phil-davis** [comment]
What error text should be displayed?
It could give more reason why the reshare could not be done. But that will require more code in core (or the hooks in rich documents) that can "decode" the various "error" paths and insert suitable text.

**Comment by phil-davis** [comment]
It is a bit unfortunate that the webUI by default attempts to reshare with all the permssions of the received share. If the webUI "understood" what are the maximum available resharing permissions in this context, then it could request only those by default. That would avoid the user getting this error message, and then having to understand and manually reduce the permission of the reshare attempt.

@davitol after getting the error message, can you then open the sharing settings, reduce the resharing permissions, and get a successful reshare? Or d you get stuck?

**Comment by davitol** [comment]
> For shares with Secure View permissions, disabled resharing is expected. To allow resharing there needs to be some more logic in place to prevent privilege escalations. For regular shares, resharing should be possible, though.

Then I think we have to avoid user can mark 'Can share' textbox in Sharing menu when Secure View is enabled

![Screen Shot 2020-01-13 at 13 50 42](https://user-images.githubusercontent.com/10596560/72257629-62019600-360c-11ea-8be8-3a57995ee36b.png)

**Comment by davitol** [comment]
> @davitol after getting the error message, can you then open the sharing settings, reduce the resharing permissions, and get a successful reshare? Or d you get stuck?

![Screen Shot 2020-01-13 at 12 01 28](https://user-images.githubusercontent.com/10596560/72257758-b0169980-360c-11ea-863f-0a0a0952d803.png)


@phil-davis Due to share is not deployed it is not possible to reduce the resharing permissions. If I reduce the permission in user1 then I get 'Sharing is not allowed' (expercted behaviour and no issue)

**Comment by mrow4a** [comment]
@davitol I am not sure how it was possible, but generally "can share" should not be visible when "Secure View" is enabled. Can you give steps to reproduce showing "can share" with "secure view" ? what richdocuments version you have installed?

**Comment by davitol** [comment]
> what richdocuments version you have installed?



ownCloud 10.4.0. RC1 and richdocuments: 2.2.0


Steps just the ones mentioned on the ticket. Anyway I will try again from scratch

**Comment by davitol** [comment]
> Steps just the ones mentioned on the ticket. Anyway I will try again from scratch

Retested from scratch  and reproduced again with ownCloud 10.4.0. RC1 and richdocuments: 2.2.0

![Screen Shot 2020-01-13 at 14 58 20](https://user-images.githubusercontent.com/10596560/72261491-3b942880-3615-11ea-914a-eb03c49238b4.png)

**Comment by mrow4a** [comment]
@davitol what happens when you click on "can share" ? Isn't "secure view" disabled?

**Comment by micbar** [comment]
@felixheidecke Could you check, if we can change the field order with secure view enabled?

**Comment by davitol** [comment]
> @davitol what happens when you click on "can share" ? Isn't "secure view" disabled? I think we have have acceptance test for this

![SecureVPt](https://user-images.githubusercontent.com/10596560/72328210-cd05a800-36b2-11ea-96c9-b972fe9c795a.gif)


In the following gif it is shown what happens when clicking on "can share" with Secure View enabled. Also it shows how are ordered the secure view checkboxes

**Comment by mrow4a** [comment]
@davitol I start wonder how the acceptance tests in core and in richdocuments  (https://drone.owncloud.com/owncloud/richdocuments/645) are passing, if this is possible. Something has been changed that broke the logic of adding share attributes (maybe while doing expiration, dunno). I will have a look.

**Comment by mrow4a** [comment]
@pmaier1 @micbar I will have a look today/tomorrow

**Comment by mrow4a** [comment]
@davitol @pmaier1 this commit https://github.com/owncloud/core/commit/4319548e48b497276fb76505b1c09aa0b60df4e9 broke advanced share attributes code. The "js code" we promised to onlyoffice and collabora guys we wont brake (we had build intensive acceptance tests). But that commit managed to circumvent it, and thus this issue.

**Comment by mrow4a** [comment]
fix https://github.com/owncloud/core/pull/36766
