### ISSUE TITLE
Missing CHANGELOG.md after running updater to 10.3.2.2.

### ISSUE THREAD

**Issue by l0ckm4** [owncloud/core#36764]
Hi - ran the updater today going from 10.1 to 10.3.2.2.  Verything is fine except i was missing two files.  README.md and updater/CHANGELOG.md.  I managed to get the README.md from a tar ball i downloaded from here but that tar file does not have the updater directory.  The CHANGELOG.md from teh root of the tar ball fails validation.  Where can i get the tar ball for 10.3.2.2 that has the updater directory?  The version on the website seems to be just 10.3.2.

```
Results
=======
- core
	- INVALID_HASH
		- updater/CHANGELOG.md

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [updater/CHANGELOG.md] => Array
                        (
                            [expected] => 93fe2d99ef3d3b677791b1ca705882cd6e4646ddc23507b8a5b08533159f35126756afd64292b0db2c4f8c56e20a7240a1a925be1ddf7cb5a42f656473ec1603
                            [current] => fd31553d5e2a9ab034dc08c84a7b3c8a826c60c4735c977dce07cd40d563b16cda536793a559bbef6967428d3fc1ec964424e0589ed9e379152f0c57f753331e
                        )

                )

        )

)
```

**Comment by ho4ho** [comment]
Duplicate by https://github.com/owncloud/updater/issues/517

**Comment by davitol** [comment]
Closing due to it is a duplicated issue
