### ISSUE TITLE
owncloud can get really confused about the data directory

### ISSUE THREAD

**Issue by Duoxilian** [owncloud/core#36782]
### Steps to reproduce

Originally, this was a report about the occ files:scan command not picking up changes to the data directory.

However, I found that something different was going on, so this entry is edited.

During installation ended up with two copies of owncloud installed, one in
`/var/www/owncloud` and one in `/var/www/html/owncloud`. I created the former when owncloud complained about the data directory being inside the html root.

Now the interesting thing is that, by oversight, I had the apache `owncloud.conf` file pointing to `/var/www/owncloud`, but the owncloud data directory in the `config.php` file pointing to `/var/www/html/owncloud`. 

Everything seemed to work fine: I was able to upload files and synch from a client. 

Then I tried to move some old files directly into the data directory and then scan the directory using occ. That did not work.

It took me quite a while to detect that misconfiguration of the data directory as most things seemed to work. When I put the data directory where the php configuration said, the file scan worked.

I found another weired problem: I then corrected the the data directory path in the `config.php` file, and moved the files to the new location. Now the scan stopped working again. It appears that there is somewhere in the system a memory of the old configuration that gets in the way.

So here is my problem report:

1. It appears that there are some system functions which rely on the data directory as configured in the `config.php` file, and some system functions that do not.
2. It appears that there is somewhere in the system (maybe the database) a shadow copy of the directory path as originally set which is not changed when the `config.php` file changes and then interferes with system behavior.
 
### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.2.26-1+ubuntu16.04.1+deb.sury.org+1

**ownCloud version:** 10.3.2.2

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** http://download.owncloud.org/download/repositories/production/Ubuntu_16.04

**Signing status (ownCloud 9.0 and above):** 

```
All it says is

No errors have been found.
```

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocx17f97lmmh",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "10.3.2.2",
        "dbname": "ownclouddb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "singleuser": false,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "logfile": "\/var\/log\/owncloud.log",
        "log_rotate_size": 10485760,
        "filesystem_check_changes": 1,
        "trashbin_retention_obligation": "auto, 90",
        "default_language": "en_GB",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "session_keepalive": true,
        "login.alternatives": [],
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "cache_path": "",
        "cache_chunk_gc_ttl": 86400,
        "installed": true
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.5.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_mediaviewer: 1.0.1
  - files_sharing: 0.12.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.2.0
  - market: 0.5.0
  - notifications: 0.5.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - user_external
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome

**Operating system:** Ubuntu 18.04

#### Web server error log
```
No errors
```

#### ownCloud log (data/owncloud.log)
```
No relevant output
```

#### Browser log
```
N/A
```

**Comment by ho4ho** [comment]
Miss documentation?

https://doc.owncloud.org/server/10.4/admin_manual/maintenance/manually-moving-data-folders.html#fix-hardcoded-database-path-variables

**Comment by VicDeo** [comment]
Feel free to reopen if you followed the official documentation intact while moving your data folder 
https://doc.owncloud.com/server/admin_manual/maintenance/manually-moving-data-folders.html#fix-hard-coded-database-path-variables
