### ISSUE TITLE
[OC-8] Problems setting sharing permissions in the webUI when user and group have same name

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36813]
### Steps to reproduce
1. create user "finance" and group "finance"
2. using the webUI, share a file or folder with both the user and then the group "finance"
3. open the sharing permissions of both in the webUI
4. change the sharing permissions of the group "finance"

### Expected behaviour
The sharing permissions of the group change.
The sharing permissions of the user do not change.

### Actual behaviour
The sharing permissions of the user change.
The sharing permissions of the group do not change.

### Server configuration
current master

**Comment by phil-davis** [comment]
PR #36793 demonstrates that the sharing API is OK when there is a user and group with the same name. So this is "just" a UI bug.

**Comment by phil-davis** [comment]
Note: #36766 finishes the user/group share expiration date code.
That adds an expiration date field. That field ends up having the same issue as here, when sharing with a user and a group with the same name.

**Comment by micbar** [comment]
@pmaier1 THis is a real annoying bug and IMO a release blocker.

@phil-davis is it a regression?

**Comment by pmaier1** [comment]
> @pmaier1 THis is a real annoying bug and IMO a release blocker.

Yes, I agree. Apparently it was also the case in earlier versions.

**Comment by phil-davis** [comment]
> @phil-davis is it a regression?

No, it is not a regression. IMO it has been there "a long time" (TM). If you want the answer to "a long time" then maybe @davitol will have some clue, or can easily go back some releases and reproduce it.

It only happens if you have a group name that is the same as a user name, and you share some resource with both the group and the user. So that is a quite rare thing to do.

**Comment by pmaier1** [comment]
> So that is a quite rare thing to do.

Yeah. So not necessarily a release blocker. Could also be fixed in another patch release afterwards, IMO. Decision @micbar.

**Comment by phil-davis** [comment]
Fix is in PR #36766
