### ISSUE TITLE
Add PROPFIND acceptance test coverage

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36821]
e.g. #36741 reported a problem with the new public-files API not reporting the file size (`getcontentlength`) in a `PROPFIND`

Expand API acceptance test coverage to do `PROPFIND` of various files/folders as file owner, share receiver, public... and check lots of properties are returned correctly.

**Comment by phil-davis** [comment]
Note: see the code added in #36778 - that could be refactored to make it more general...

**Comment by kiranparajuli589** [comment]
@phil-davis is this issue fixed by #36778?

**Comment by phil-davis** [comment]
> @phil-davis is this issue fixed by #36778?

No, that PR added some specific code to check the file size `getcontentlength` returned in the PROPFIND.

We need to see what `PROPFIND` acceptance tests we already have, and then:

- design some more general acceptance test `When` steps that will let us make different `PROPFIND` requests on files/folders (might use tables)
- design `Then` steps that can check for a set of expected responses (might use tables)
- write useful test scenarios

**Comment by phil-davis** [comment]
Also see #36920 - there is a bug in some special `PROPFIND` requests.
The bug needs to be reproduced with acceptance tests.

**Comment by kiranparajuli589** [comment]
> Also see #36920 - there is a bug in some special `PROPFIND` requests.
> The bug needs to be reproduced with acceptance tests.

@phil-davis #36941 covers bug-reproduce code for issue #36920, please review!

**Comment by kiranparajuli589** [comment]
@phil-davis https://github.com/owncloud/core/pull/36778#issuecomment-586802616

**Comment by phil-davis** [comment]
@kiranparajuli589 here is a docs comment that has a list of propfind properties that we should be able to get and test:
https://github.com/owncloud/docs/issues/276#issuecomment-563239719

**Comment by kiranparajuli589** [comment]
@phil-davis tests for the propfind properties mentioned on https://github.com/owncloud/docs/issues/276#issuecomment-563239719 are now added!

**Comment by individual-it** [comment]
closing this for now, feel free to open if needed again
