### ISSUE TITLE
provisioning API does not return infos of user when user auth with uppercase username but sends lowercase in the URL

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#36822]
### Steps to reproduce
have a user `uu1`

| user in the auth | user in the URL | command | result |
|---| --- | --- | --- |
| user LC | LC | `curl -u uu1:uu1 'http://localhost/owncloud-core/ocs/v1.php/cloud/users/uu1'`  | :heavy_check_mark:  |
| user UC | LC | `curl -u UU1:uu1 'http://localhost/owncloud-core/ocs/v1.php/cloud/users/uu1'`  | :heavy_check_mark:  |
| user LC | UC |`curl -u uu1:uu1 'http://localhost/owncloud-core/ocs/v1.php/cloud/users/UU1'` | :x: |
| admin LC | UC |`curl -u admin:admin 'http://localhost/owncloud-core/ocs/v1.php/cloud/users/UU1'` | :heavy_check_mark: |
| admin LC | LC |`curl -u admin:admin 'http://localhost/owncloud-core/ocs/v1.php/cloud/users/UU1'` | :heavy_check_mark: |
| admin UC | UC |`curl -u admin:admin 'http://localhost/owncloud-core/ocs/v1.php/cloud/users/UU1'` | :heavy_check_mark: |
| admin UC | LC |`curl -u admin:admin 'http://localhost/owncloud-core/ocs/v1.php/cloud/users/UU1'` | :heavy_check_mark: |

**Comment by phil-davis** [comment]
Assigned myself and added QA-team label. I will write an acceptance test scenario to demonstrate this.

**Comment by phil-davis** [comment]
Fix is in PR #36878
