### ISSUE TITLE
Password submit arrow is in the middle of the password field

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36845]
PR #36807 adjusted the "login-submit" CSS.

After that PR, the login page "Password" field has the "submit arrow" in the middle of the Password field.

![Screenshot_2020-01-28 ownCloud](https://user-images.githubusercontent.com/1535615/73262759-14358200-41f7-11ea-86c1-91ee53d15dff.png)

Reversing the code change makes the "submit arrow" go back to the right-side of the Password field.

**Comment by phil-davis** [comment]
@micbar @ChrisEdS 
Is there an easy way to get the "submit arrow" across to the right?
Or do we need to revert that PR?

**Comment by ChrisEdS** [comment]
I will take care. Thank you for reporting this bug @phil-davis

**Comment by phil-davis** [comment]
@ChrisEdS any update?
CC: @micbar 

We have the chance to fix this in `master` today, before we again make a `release-10.4.0` branch.

**Comment by ChrisEdS** [comment]
I'll deliver a fix today. @phil-davis
