### ISSUE TITLE
Impossible to login with a new user credentials

### ISSUE THREAD

**Issue by notna1109** [owncloud/core#36863]
Hi all, 

I quite new to owncloud and doscker but here is the thing. I have set up my owncloud server via docker-compose and address persistent volumes "outside" the container. I have created a new user in the web platform of owncloud with my admin account. But when i want to get connected with this new user credentials it does not work. Owncloud ask me to send an email to renew the password. I did that but never received no email. Could you tell me or help me with that? thanks

**Comment by ho4ho** [comment]
> Thanks for reporting issues back to ownCloud! This is the issue tracker of ownCloud, if you have any support question please check out https://owncloud.org/support

Ask for support by https://central.owncloud.org/ ?
