### ISSUE TITLE
Upgrade from 10.2.1 to 10.3.2 failed

### ISSUE THREAD

**Issue by chewiesGit** [owncloud/core#36871]
Hi, I am very new to owncloud and tried to upgrade owncloud using occ command on a shared webserver for the first time. However, the upgrade fails giving the error message below. I cannot find anything about it on the net... I would appreciate any help. 

### Steps to reproduce
1.  download and extract stable version of owncloud 10.3.2
2. move / copy data and config.php from old owncloud folder to the extracted new folder
3. run upgrade using occ upgrade

### Expected behaviour
Upgrade to version 10.3.2

### Actual behaviour
Upgrade failed giving the following error message: 

An unhandled exception has been thrown:
Error: Class 'OC_Mount_Config' not found in /home/webpages/lima-city/jd/owncloud-2020-02-02-757f9e/apps/files_external/appinfo/app.php:34
Stack trace:
#0 /home/webpages/lima-city/jd/owncloud_10-3-2/lib/private/legacy/app.php(239): require_once()
#1 /home/webpages/lima-city/jd/owncloud_10-3-2/lib/private/legacy/app.php(190): OC_App::requireAppFile('files_external')
#2 /home/webpages/lima-city/jd/owncloud_10-3-2/lib/private/Updater.php(352): OC_App::loadApp('files_external', false)
#3 /home/webpages/lima-city/jd/owncloud_10-3-2/lib/private/Updater.php(271): OC\Updater->doAppUpgrade()
#4 /home/webpages/lima-city/jd/owncloud_10-3-2/lib/private/Updater.php(112): OC\Updater->doUpgrade('10.3.2.2', '10.2.1.4')
#5 /home/webpages/lima-city/jd/owncloud_10-3-2/core/Command/Upgrade.php(261): OC\Updater->upgrade()
#6 /home/webpages/lima-city/jd/owncloud_10-3-2/lib/composer/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/webpages/lima-city/jd/owncloud_10-3-2/lib/composer/symfony/console/Application.php(982): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/webpages/lima-city/jd/owncloud_10-3-2/lib/composer/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/webpages/lima-city/jd/owncloud_10-3-2/lib/composer/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/webpages/lima-city/jd/owncloud_10-3-2/lib/private/Console/Application.php(165): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/webpages/lima-city/jd/owncloud_10-3-2/console.php(106): OC\Console\Application->run()
#12 /home/webpages/lima-city/jd/owncloud_10-3-2/occ(11): require_once('/home/webpages/...')
#13 {main}

### Server configuration
**Operating system**:
Ubuntu 16.04.6 LTS

**Web server:**
Apache 2.4

**Database:**
SQLite 3

**PHP version:**
7.2.27

**ownCloud version:** (see ownCloud admin page)
10.2.1

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
software installation offered by webhoster

**Signing status (ownCloud 9.0 and above):**
No errors have been found.
```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**
https://gist.github.com/chewiesGit/7ad4857e986899451355987a3b798c54#file-gistfile1-txt

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**
Enabled:
  - configreport: 0.2.0
  - dav: 0.4.0
  - federatedfilesharing: 0.4.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_sharing: 0.11.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - market: 0.5.0
  - notifications: 0.5.0
  - provisioning_api: 0.5.0
  - twofactor_totp: 0.6.1
  - updatenotification: 0.2.1
Disabled:
  - comments
  - encryption
  - external
  - files_videoplayer
  - firstrunwizard
  - systemtags
  - user_external

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Safari 13.04

**Operating system:**
MacOS 10.15

**Comment by DeepDiver1975** [comment]
> An unhandled exception has been thrown:
> Error: Class 'OC_Mount_Config' not found in /home/webpages/lima-city/jd/owncloud-2020-02-02-757f9e/apps/files_external/appinfo/app.php:34
> Stack trace:
> #0 /home/webpages/lima-city/jd/owncloud_10-3-2/lib/private/legacy/app.php(239): require_once()

there is something wrong with your setup - recognize the different paths.
