### ISSUE TITLE
files:transfer-ownership error is confusing

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#36877]
# Steps to reproduce
1. execute `occ files:transfer-ownership`
2. get error: `Not enough arguments (missing: "source-user, destination-user").`
3. enter `occ files:transfer-ownership "user1, user2"` as described in the error message

### Expected behaviour
command is executed correctly

### Actual behaviour
another error `Not enough arguments (missing: "destination-user").`

### Server configuration
oC 10.3.2

---

What the error should say is `Not enough arguments (missing: "source-user" "destination-user").` imho

**Comment by phil-davis** [comment]
IMO that "red error output" is built-in to the Symfony Command framework. The detail of the message is not created by ownCloud code.

**Comment by voroyam** [comment]
Okay, this might make the issue harder to fix

**Comment by phil-davis** [comment]
> IMO that "red error output" is built-in to the Symfony Command framework. The detail of the message is not created by ownCloud code.

Anyone else feel free to correct me if I am wrong.

**Comment by voroyam** [comment]
We just had a look with @pako81 and we could not find it in the file of the command, so you are correct.
