### ISSUE TITLE
Misaligned indirect share entries

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#36891]
aka inherited shares, aka parent share entries

### Steps

1. Create three users "Alice" and "Bob" and "Charlie"
1. Login as Alice
1. Create a folder "test"
1. Share "test" with "Bob"
1. Create a subfolder "test/sub"
1. Share "test/sub" with "Charlie"
1. Open sharing panel for "test/sub"

### Expected result
See entries for the indirect Bob share via "Test" and the direct share to Charlie.
Both must be aligned.

### Actual result
Both visible but visually misaligned.

![image](https://user-images.githubusercontent.com/277525/73826138-8ca2d100-47fd-11ea-9ce0-eeef21098d68.png)

Note: for the same scenario involving public links the alignment looks fine.

### Version
php7.4-20200101 branch, which should be close to 10.4 RC. (I can't test with PHP 7.3 due to OS restrictions)

@pmaier1 @micbar @phil-davis

**Comment by phil-davis** [comment]
The alignment looks OK for me in current core master, PHP 7.3, chrome Version 80.0.3987.87 and Firefox 72.0.2, Ubuntu 18.04
![Screenshot_2020-02-05 z101 - Files - ownCloud](https://user-images.githubusercontent.com/1535615/73831151-f044f280-482d-11ea-86a7-0ad089c2da28.png)

**Comment by PVince81** [comment]
Hmm, then there is something mysterious on that php7.4 branch as it's the second time we see discrepancies in the UI.

Mine was with Chromium 79 on openSUSE Tumbleweed.

Maybe that will become another checkbox for the PHP 7.4 PR ?

**Comment by phil-davis** [comment]
@davitol please be aware of this sort of thing when testing 10.4RC2...
The automated acceptance tests only check the existence and "clickability" of "stuff" in the webUI, not the detail of the layout/visual.

**Comment by phil-davis** [comment]
> Maybe that will become another checkbox for the PHP 7.4 PR ?

I did the PHP 7.4 PR "just for fun" to see what explodes. A lot of unit tests fail. So it needs a fair bit of effort to get all that sorted out. ("someone" will need to allocate resources "someday")

But maybe the ownCloud API and webUI actually work fine? And it is just unit test compatibility crud that does not effect the real application?

**Comment by PVince81** [comment]
So far I don't even understand why a different PHP version on the backend could even cause this kind of UI issues... it doesn't make sense. Unless there are hidden bugs in the UI that are triggered by some hidden new error conditions triggered by PHP 7.4.

**Comment by davitol** [comment]
Tested with PHP 7.2.16-1+ubuntu16.04.1+deb.sury.org+1 using oC 10.4.0 RC2

I think it is not PHP related but CSS styles . One user has class avatar and the other shared-tree. Both classes have different styles:

![Screen Shot 2020-02-12 at 11 09 17](https://user-images.githubusercontent.com/10596560/74328718-b2e0e780-4d8e-11ea-9d1f-78089d73a6f8.png)

![Screen Shot 2020-02-12 at 11 12 42](https://user-images.githubusercontent.com/10596560/74328829-e9b6fd80-4d8e-11ea-8bbf-aecd38456cd3.png)
![Screen Shot 2020-02-12 at 11 12 25](https://user-images.githubusercontent.com/10596560/74328831-ea4f9400-4d8e-11ea-89d7-1f67c4911cbf.png)
