### ISSUE TITLE
Security Breach

### ISSUE THREAD

**Issue by ijazm123** [owncloud/core#36906]
### Steps to reproduce
1.Send a request to get a public URL for a specific file. The requested URL will contain the path of the file that needs to be shared

### Expected behaviour
A public URL needs to be generated

### Actual behaviour
Got 404 status code and message Wrong path, file/folder doesn't exist

--------------------------------------------------------------------------------------------------------------Second case
### Steps to reproduce

Send a request to get a public URL for all files under a folder without Authorization token in the header.

### Expected behaviour
As the request doesn't have Authorization in the header, it should be denied.

### Actual behaviour
Got the public URL for all the files.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** Mysql 5.7

**PHP version:**
PHP 7.0.33-0ubuntu0.16.04.5
**ownCloud version:** (see ownCloud admin page)
10.2.1
**Updated from an older ownCloud or fresh install:**
Fresh

**Where did you install ownCloud from:**
Github

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
Results
passman
EXCEPTION
OC\IntegrityCheck\Exceptions\MissingSignatureException
Signature data not found.
Raw output
Array
(
[passman] => Array
(
[EXCEPTION] => Array
(
[class] => OC\IntegrityCheck\Exceptions\MissingSignatureException
[message] => Signature data not found.
)

    )
)
![WithPathIntheRequest](https://user-images.githubusercontent.com/40889706/74009710-d4665b80-49a9-11ea-80d9-0b7b886a887f.jpg)
![Withoutauthorisation](https://user-images.githubusercontent.com/40889706/74009712-d6301f00-49a9-11ea-83b9-9b188a69f0e6.jpg)

**Comment by karakayasemi** [comment]
As far as I understand from your first screenshot, you supply auth token and requesting for a path. As a result, you got 404 not found response as expected for the wrong path.

For the second screenshot, when I made the same request without any auth header, I got 997 unauthorized response. I could not understand how you get the list of shares.

Can you reproduce these scenarios with curl and give us the exact curl command?

**Comment by ijazm123** [comment]
@karakayasemi 
curl --request POST https://cloud.gnrgy.com/ocs/v1.php/apps/files_sharing/api/v1/shares?path=/Portal/1InifinityAPI.txt&shareType=3&permissions=31

**Comment by phil-davis** [comment]
When I do that sort of `curl` command I get the expected:
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message>Unauthorised</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>
```
That "old" `ocs` v1 gives HTTP status 200 (which is sort of weird, but that's what it does)
It does not create a share.

If I add `-u Phil:Phil` then it works and I find that I have made a public link share.
(local test system, you won't find a public account of mine with password `Phil` ;)

**Comment by ijazm123** [comment]
curl -X POST URL will give below output
 <?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message>Unauthorised</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>


And with the header, the output is

<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>404</statuscode>
  <message>Wrong path, file/folder doesn't exist</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>

**Comment by ijazm123** [comment]
> As far as I understand from your first screenshot, you supply auth token and requesting for a path. As a result, you got 404 not found response as expected for the wrong path.
> 
> For the second screenshot, when I made the same request without any auth header, I got 997 unauthorized response. I could not understand how you get the list of shares.
> 
> Can you reproduce these scenarios with curl and give us the exact curl command?

How do I get the value for authorization header? 
The value which we are currently using for authorization is from mobile SDK.
So we want to know how we can do the Curl with authorization header value. 
What must be the value of authorization?

**Comment by ijazm123** [comment]
How do I get the value for the authorization header?
The value which we are currently using for authorization is from mobile SDK.
So we want to know how we can do the Curl with authorization header value.
What must be the value of authorization?

**Comment by DeepDiver1975** [comment]
We consider this an invalid issue - closing.
