### ISSUE TITLE
SSL Root Certificate disappears magically

### ISSUE THREAD

**Issue by new0ne** [owncloud/core#36940]
### Steps to reproduce
1. Install Root CA cert (with Chain): Site-wide 
(Settings-> General -> SSL Root Certificates)
2. One can see it in the Administration ( See first screenshot)
3. Close Browser window
4. Navigate back to the admin panel and check for the root ca certificate: its gone. (See second screenshot. I can only add a new one.)

### Expected behaviour
The Root CA Certificate should stay in the truststore, where ever that might be.

### Actual behaviour
The previously installed Root CA Certificate is gone. (At least they are not visible in the webinterface any more)

### Server configuration
**Operating system**: Ubuntu LTS 18.04.4

**Web server:** Apache/2.4.29

**Database:** mysql  Ver 14.14 Distrib 5.7.25,

**PHP version:** v7.3.14-6+ubuntu18.04.1+deb.sury.org+1

**ownCloud version:** 10.3.2

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** Downloaded latest stable tarball from website

**Signing status (ownCloud 9.0 and above):** No idea what that is

**config:** see attached 
[config_report_20200211.txt](https://github.com/owncloud/core/files/4185818/config_report_20200211.txt)

Root-CA installed and visible in the Admin Interface:
![SSL_Cert_Present](https://user-images.githubusercontent.com/9295014/74240959-448f1d00-4cdb-11ea-92db-39ab37177fab.png)

Root-CA gone:
![SSL_Cert_gone](https://user-images.githubusercontent.com/9295014/74241035-77391580-4cdb-11ea-906b-096f26a93318.png)

**Comment by DeepDiver1975** [comment]
>     1. Install Root CA cert (with Chain)

In the browser? In ownCloud(where?)? In your web server?

**Comment by new0ne** [comment]
I installed it through the webinterface of owncloud.
I followed:
https://doc.owncloud.org/server/10.3/admin_manual/configuration/server/import_ssl_cert.html
Attached a bunch of screenshots in addition.

**Comment by DeepDiver1975** [comment]
I see - thx for clarification

**Comment by new0ne** [comment]
I can further add: its not being used for STARTTLS when one tries to SMTP relay.
(Even though its still displayed: I just didn't close and reopen the settings page.)
Extract from wireshark:
![Installed_Cert_gets_Ignored](https://user-images.githubusercontent.com/9295014/74242051-81f4aa00-4cdd-11ea-8115-9fb4104aa7d0.png)

**Comment by new0ne** [comment]
figured something new: 
When using the occ security:certificates command it lists the cert of my root ca. The question is: why is it not displayed and why is it ignored.
