### ISSUE TITLE
Graffino/Browser-Update v2.0.2 not found

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#36976]
Trying to `make clean && make` today gives:
```
cd build && /home/phil/.yarn/bin/yarn install
yarn install v1.22.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error An unexpected error occurred: "https://codeload.github.com/Graffino/Browser-Update/tar.gz/0edda8c7f53ad2cbe68538c00b8c790513096d60: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/phil/git/owncloud/core/build/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Makefile:166: recipe for target 'build/node_modules' failed
make: *** [build/node_modules] Error 1
```

The similar problem happened in a nightly build https://drone.owncloud.com/owncloud/wopi/813/2/2
```
error An unexpected error occurred: "https://codeload.github.com/Graffino/Browser-Update/tar.gz/0edda8c7f53ad2cbe68538c00b8c790513096d60: Request failed \"404 Not Found\""
```

It seems that https://github.com/Graffino/browser-update/releases has new releases like `v2.0.3` but the old tags are gone - no more `v2.0.2`

Probably we will have to update to `v2.0.3`

**Comment by phil-davis** [comment]
But drone jobs like https://drone.owncloud.com/owncloud/core/23463/14/5 are OK.
```
+ make install-nodejs-deps
cd build && /usr/bin/yarn install
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.0.7: The platform "linux" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
```

I guess the cache-restore step before yarn-install has the old Graffino/Browser-Update v2.0.2 tarball still in it, so we are not yet noticing that the upstream repo is broken.

But the `wopi` build does not have the cache stuff, so it went to the upstream repo, which is broken.

**Comment by phil-davis** [comment]
Note: there were lots of code changes in that repo in the last 24 hours. The Travis script got deleted, and the site that is pointed to for browser updates changed from `http://browser-update.org/` to `http://bestvpn.org/outdatedbrowser/en`

IMO it looks a bit strange. We should somehow verify that the new code is OK (that the repo has not been hacked) or stop using this or...

**Comment by phil-davis** [comment]
There might be problems when nightly job builds `daily-qa-master` - it may or may not find Graffino/Browser-Update v2.0.2 in a cache somewhere. If not, then it may fail to build `daily-qa-master` (which or be OK for a day...). If it does build something without some Graffino/Browser-Update then a lot of app nightly tests may start failing... Let's see.

**Comment by zenopopovici** [comment]
@phil-davis Reverting changes now, we weren't aware this extension was used.

**Comment by zenopopovici** [comment]
Repository has been restored and version v2.0.5 has been released to bump the reverted code. Really sorry for the trouble caused.
