### ISSUE TITLE
Upgrade from owncloud 10.2.1.4 to owncloud 10.3.2.2 failed

### ISSUE THREAD

**Issue by phellmon** [owncloud/core#36974]
### Steps to reproduce
1. Log into owncloud's Web interface
2. Click on the upgrade button
3. See the error message

### Expected behaviour
I was upgrading from ownCloud 10.2.1.4 to current version using the updater. I would have expected the upgrader to conclude successfully and give me access to the Web interface for the latest version 10.3.2.

### Actual behaviour
The upgrader exited with an error message:

== begin error message ==
Updating to 10.3.2
OC\RepairException: Upgrade is not possible

Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Repair warning: Please install or update the following apps manually or disable them with: occ app:disable ownbackup
Repair warning: For manually updating, see https://doc.owncloud.org/server/10.3/go.php?to=admin-marketplace-apps

Detailed logs:
Preparing update
Set log level to debug
Turned on maintenance mode
Repair warning: You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Repair warning: Please install or update the following apps manually or disable them with: occ app:disable ownbackup
Repair warning: For manually updating, see https://doc.owncloud.org/server/10.3/go.php?to=admin-marketplace-apps
OC\RepairException: Upgrade is not possible

The update was unsuccessful. Please report this issue to the ownCloud community.

== end error message ==

### Server configuration
**Operating system**:
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian

Distributor ID:	Debian
Description:	Debian GNU/Linux 8.11 (jessie)
Release:	8.11
Codename:	jessie

**Web server:**
Apache

**Database:**
Server type: MySQL
Server version: 5.5.60-0+deb7u1-log - (Debian)
Protocol version: 10

**PHP version:**
php7.3

**ownCloud version:** (see ownCloud admin page)
10.2.1.4 in the process of upgrading to 10.3.2.2

**Updated from an older ownCloud or fresh install:**
10.2.1.4 in the process of upgrading to 10.3.2.2

**Where did you install ownCloud from:**
downloaded from owncloud.org

**Signing status (ownCloud 9.0 and above):**
??

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.

Cannot login to admin user in my owncloud to access the resource


**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

Don't have access to the sudo command with my privileges on the webhosting command line.
Executing the command without sudo to the www-data user results in an error as the wrong PHP version is being used.

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```
Don't have access to the sudo command with my privileges on the webhosting command line.
Executing the command without sudo to the www-data user results in an error as the wrong PHP version is being used.

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Safari

**Operating system:**
macOS Catalina

### Logs
#### Web server error log
```
Insert your webserver log here
```
don't have access to the Webserver log

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
All of the 18+ MB of log file? You must be kidding.

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

It's not a browser issue.

**Comment by phellmon** [comment]
Previous update from 10.2.1 to 10.2.1.4 was successful on 2019-10-09 at 13:20:54+00:00

However, in-between this, PHP Version was changed from 7.2 to 7.3, and owncloud didn't work due to wrong PHP Version. Migrated PHP back to Version 7.2, was able to access user interface again, then saw information that 10.3.2.2 was available, and started the update process, resulting in the error message.

Now back to PHP 7.2, as this shows:

HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Keep-Alive: timeout=15
Date: Tue, 18 Feb 2020 18:19:39 GMT
Server: Apache
X-Powered-By: PHP/7.2.27

**Comment by cortho** [comment]
As you already found out, support for php 7.3 ist starting with ownCloud 10.3, see https://owncloud.org/changelog/server/

Closing, since this is not an issue.

**Comment by phellmon** [comment]
Sorry, the error can be repeated with PHP 7.2, so it's an issue.

My problem is that I don't have access to sudo on the command line, so cannot remove the offending app the recommended way. I would appreciate if someone could tell me an alternative way. I have ssh access to the command line and can remove or rename files or directories, or upload. 

Unfortunately, I fell sick with the flu and don't have access to the backups that were done before the failure. 

Any pointer to a possible solution within the limitations (no sudo) is highly appreciated.

**Comment by butonic** [comment]
@phellmon you should be able to move away the incompatible app `ownbackup` ... move it out of the apps folder to make sure oc does not pick up the info.xml. Just renaming the folder won't help.

**Comment by phellmon** [comment]
RESOLVED: 
The solution was to set a value in the database from "yes" to "no", which effectively disabled the app that was giving error messages. Moving the app directory out of the owncloud tree alone did not work.
