### ISSUE TITLE
Content-Type response header issue

### ISSUE THREAD

**Issue by ijazm123** [owncloud/core#36996]
We need to upload an HTML file and get the public direct URL. If we load this public direct URL in the browser it should render this as an HTML but instead, it downloads the file. Is there any API to render the HTML file in the browser instead of downloading it.

The pattern we observed is when we give the public URL
<URL>/download - In the response header Content-Type is text/plain

If this response header Content-Type is text/HTML browser can render this.

Help us how to achieve this.

**Comment by ijazm123** [comment]
We need to upload an HTML file and get the public direct URL. If we load this public direct URL in the browser it should render this as an HTML but instead, it downloads the file. Is there any API to render the HTML file in the browser instead of downloading it.

The pattern we observed is when we give the public URL
<URL>/download - In the response header Content-Type is text/plain

If this response header Content-Type is text/HTML browser can render this.

Help us how to achieve this.

**Comment by DeepDiver1975** [comment]
This is by intention. Same goes for js and css files.
Die to security reasons we deliver them as plain/text
