### ISSUE TITLE
blacklisted_files_regex and excluded_directories_regex overlap behavior

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/core#37005]
Original PR and more details in https://github.com/owncloud/core/pull/36360

`blacklisted_files_regex` should apply to files and `excluded_directories_regex` to directories, currently their behaviour overlaps. Both options apply to both files and directories

Tested with desktop client 2.6.1 (build 13096), macOS 10.15.3
Server: 10.4.0 RC3

**Comment by phil-davis** [comment]
Note: IMO the existing `blacklisted_files` and `excluded_directories` also overlap like this.

**Comment by mmattel** [comment]
@HanaGemela fyi,
- blacklist = you can see them in the browser if present in the filesystem but you cant create/modify content/sync them
- exclude = they are present in the FS but they are not scanned and therefore not further processed, not creatable

**Comment by micbar** [comment]
@HanaGemela @mmattel So as far as I understand you, this works as designed.

**Comment by micbar** [comment]
@pmaier1 FYI

**Comment by pmaier1** [comment]
> @HanaGemela @mmattel So as far as I understand you, this works as designed.

Yep, as far as I understand, I agree as well. Is it documented in that way?

**Comment by mmattel** [comment]
@pmaier1 
Yes there is a documentation about it available in docs.
I will improve it to make things more clear.

**Comment by mmattel** [comment]
Documentation has been updated
