### ISSUE TITLE
Allow oauth2 and openidconnect to coexist

### ISSUE THREAD

**Issue by butonic** [owncloud/core#37059]
When enabling the oauth2 app and the openidconnect app at the same time the openidconnect app does not get a chance to authenticate the bearer token header when authenticating oidc auth tokens, because the oauth2 app will throw an exception while the [Session](https://github.com/owncloud/core/blob/18831fa81167a9a876d0bb0d06c5106460714743/lib/private/User/Session.php#L1152-L1179) checks the auth headers.

The IAuthModules ([TokenAuthModule](https://github.com/owncloud/core/blob/2de709ee929ff8ffd480019c82e09929134ad41d/lib/private/User/TokenAuthModule.php#L64), [OAuth2\AuthModule](https://github.com/owncloud/oauth2/blob/master/lib/AuthModule.php#L47), [OpenIdConnectAuthModule](https://github.com/owncloud/openidconnect/blob/master/lib/OpenIdConnectAuthModule.php#L84) and [BasicAuthModule](https://github.com/owncloud/core/blob/2de709ee929ff8ffd480019c82e09929134ad41d/lib/private/User/BasicAuthModule.php#L124)) are built in a way to return null when they cannot authenticate a user. But they also throw exceptions, when something goes wrong.

An exception from the OAuth2 AuthModuleThis prevents the OpenIDConnectAuth Module the verify the Bearer token.

Also looking at the code flow it seems the Session relies on the BasicAuthModule to throw an exception in case it could not verify a user ... like a catch all. Because if no backend throws an exception the user will not be logged out... Which seems to be wrong?

Shouldnt the Session ignore all exceptions as long as one backend can authenticate the user (the Token / cookie / php session being one of them)? Or at least leave the user logged in as long as all auth modules agree on which user is logged in ...

**Comment by butonic** [comment]
fixed by  The only conflicting apps are oauth2 and openidconnect.

**Comment by mmattel** [comment]
Closing because of fix ?
