### ISSUE TITLE
proppatch request gives incorrect status code

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/core#37079]
### Steps to reproduce
 When we make `proppatch` request, we get correct status codes in the simple xml response but incorrect http status code. 
Here, as shown in screenshot1 our test passes with a status code of `207` i.e. `multi-status`.
But if we check the xml response it shows status code `403`, which is the correct status code for this scenario. 
![1](https://user-images.githubusercontent.com/34328907/75963964-82541f80-5eee-11ea-9993-cd24121f8fb2.png)
![2](https://user-images.githubusercontent.com/34328907/75964081-b3345480-5eee-11ea-8820-bcc444286257.png)

**Comment by DeepDiver1975** [comment]
This is correct from my pov. 207 is multi Status. And within the multistatus you get the explicit status for each affected element.

**Comment by phil-davis** [comment]
OK, I guess that is a bit "tricky" when the one-and-only "multi" status inside the XML is 403. But I see that in general it would be difficult to provide an "overall" HTTP status based on the set of internal statuses.

We will make sure that these sort of tests are checking the status codes inside the multi-status XML.
