### ISSUE TITLE
download should offer proper mime types

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#37072]
This is a public link of an svg file. My browser receives the download as mime-type text/plain

![image](https://user-images.githubusercontent.com/1108546/75898838-f03f0f00-5e3a-11ea-8357-afee3a071f46.png)

It should be image/svg+xml instead of text/plain.
On linux systems, this information is e.g. available with
```
$ grep svg /etc/mime.types 
image/svg+xml					svg svgz
```

**Comment by DeepDiver1975** [comment]
This is done by intention due to security reasons. Same goes for html. js, xml and so on.

**Comment by DeepDiver1975** [comment]
the mapping is defined in here - https://github.com/owncloud/core/blob/7d74dd51e4648ecc197f5a8f8c601e49297e83c5/resources/config/mimetypemapping.dist.json#L147
