### ISSUE TITLE
Growing number of ajax requests when clicking "Shared with X" sections

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#37085]
### Steps

1. Open the files app
1. Open the network console
1. Switch repeatedly between "All files" and on of the "Shared with X" sections

### Expected result
No repeated requests when opening the "Shared with X" section

### Actual result
Every time the section is opened again, an additional request is made.
The first time 1, the second time 2, the third time 3 requests, etc.
For "Shared with you" there's a pair of request. That pair gets repeated multiple times when returning.

### Version
ownCloud 10.4.1 pre-alpha git master 433ba3ee41cedb7387424f108534bfd62ae6eb28

Likely minor issue as this is not a proper use case.

**Comment by karakayasemi** [comment]
Fixed with #38385
