### ISSUE TITLE
Missing DAV share types for reshares when viewed as share owner

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#37092]
### Steps

1. Setup Phoenix with the test share scenarios: https://github.com/owncloud/product-internal/blob/master/tools/create_all_possible_share_scenarios.py
1. Login as "Alice"
1. Enter the folder "alice2bob2charlie+link (IUP, OUP, OLP)
1. Examine the indicators
1. Open the share panel for each of the four entries successively

### Expected result
The two entries which have an direct outgoing share must have it shown in the indicator directly (blue instead of grey)

### Actual result
All indicators are grey until the share panel is open, then the relevant ones will become blue.

### Version
Phoenix master 0dec7af44bb3023c696908c43b91fdcb1c2ae2c7

Somehow blocks https://github.com/owncloud/phoenix/pull/3135 where an indicator test failed, so could be related

Related story: https://github.com/owncloud/product-internal/issues/36

**Comment by PVince81** [comment]
Yep, also happening in OC 10, steps:

1. Setup OC 10.4.0 with the test share scenarios: https://github.com/owncloud/product-internal/blob/master/tools/create_all_possible_share_scenarios.py
1. Login as "Alice"
1. Enter the folder "alice2bob2charlie+link (IUP, OUP, OLP)
1. Examine the indicators
1. Open the share panel for each of the four entries successively and click "Sharing" tab

As soon as the Sharing tab is opened, the indicator in line now says "Shared".

It seems this is a very old undiscovered bug...

**Comment by PVince81** [comment]
@micbar FYI

I don't think we can work this around easily in Phoenix without making even more expensive calls

**Comment by jvillafanez** [comment]
https://github.com/owncloud/core/pull/37107 patch over OC master code should fix the problem. Checked with OC 10, but not with phoenix

**Comment by jvillafanez** [comment]
PR merged, closing
