### ISSUE TITLE
Unsucessfull OwnCloud Update

### ISSUE THREAD

**Issue by tomhtz** [owncloud/core#37093]
### Steps to reproduce
1. Tried to update from OwnCLoud 8.2.11.1 to 9.0.11
2. Followed the steps in https://jankarres.de/2014/08/raspberry-pi-owncloud-server-upgrade/
3. When trying open my OwnCloud in Step 5 of the above steps I encountered the message:

dav: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_addressbooks' already exists

### Expected behaviour
Successful update

### Actual behaviour
see above error message

### Server configuration
Windows 10

**Web server:**
unknown

**Database:**
unknown

**PHP version:**
unknown

**ownCloud version:** (see ownCloud admin page)
8.2.11.1

**Updated from an older ownCloud or fresh install:**
Update

**Where did you install ownCloud from:**
https://attic.owncloud.org/community/

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ho4ho** [comment]
Why 8.2.11 to 9.0.11?

https://doc.owncloud.org/server/10.4/admin_manual/maintenance/upgrade.html:

Version | Can Upgrade to 10.4.0? | Requirements
-- | -- | --
8.2.11 | Yes

**Comment by tomhtz** [comment]
Hi, 
didn't want to skip so many versions.
Right now I'm trying to replace OwnCloud by NextCloud. Wanted to evaluate it anyway...
Am 08.03.2020 12:57 nachm. schrieb ho4ho <notifications@github.com>:Why 8.2.11 to 9.0.11?
https://doc.owncloud.org/server/10.4/admin_manual/maintenance/upgrade.html:
VersionCan Upgrade to 10.4.0?Requirements8.2.11Yes

**Comment by ho4ho** [comment]
But upgrade like this (8.2.11 by 10.4.0) recommended by docs, why not follow?

**Comment by DeepDiver1975** [comment]
> But upgrade like this (8.2.11 by 10.4.0) recommended by docs, why not follow?

please do it that way
