### ISSUE TITLE
100% downtime due to broken Debian 9 repository

### ISSUE THREAD

**Issue by israel-lugo** [owncloud/core#37104]
### Steps to reproduce
Debian 9.12 server, using http://download.owncloud.org/download/repositories/production/Debian_9.0/

1. apt update && apt full-upgrade, get owncloud-files 10.4.0-1+1.1
2. ownCloud is broken, "requires at least PHP 7.1.0"

### Expected behaviour
Official ownCloud repository for Debian 9 should be compatible with official Debian 9.

APT package should specify its dependencies, so it is not possible to upgrade to a version which will not meet its dependencies.

Upgrading a package should not leave the package in a state which is broken by design and from which rolling back is [apparently](https://doc.owncloud.com/server/admin_manual/maintenance/upgrade.html) not possible without risking data corruption.

### Actual behaviour
New version installs cleanly, then dies at run time due to unmet dependency.

Dead ownCloud with 100% downtime and no clear path to roll back.

### Server configuration
**Operating system**: Debian 9.12

**Web server:** Apache 2.x

**Database:** PostgreSQL

**PHP version:** 7.0.33-0+deb9u7 - official Debian version

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:** Upgrade.

**Where did you install ownCloud from:** Official ownCloud repository for Debian 9.

**Signing status (ownCloud 9.0 and above):** ?

See https://central.owncloud.org/t/debian-9-repo-broken/24789 for another affected user.

I understand support for old systems cannot go on forever. However, I would've preferred to be told "No more ownCloud for Debian 9, you need to upgrade your system" than to have an upgrade that silently kills the installation.

Please, help me (and others) fix this. I am not about to compile PHP to get 7.1, nor install from some random overlay. This is a production server, and it runs other applications which also use PHP.

Upgrading to Debian 10 is not an easy option for me due to other software installed on the server. Plus a package in a Debian 9 repository shouldn't require upgrading to Debian 10 in the first place...

**Comment by netlane** [comment]
I managed to get it running only after installing php 7.2 (not 7.1, which gave errors) from some random overlay.
This version of the owncloud server definitely should not be part of the Ubuntu 16.04 Distro

**Comment by dleducq** [comment]
I was bitten by this one too. In my case it was for a fresh install, so nothing broken, at least. But upgrading to Buster isn't an option for this server at the moment, because of other installed apps not compatible with it. Older packages are not even available in the repo, nor did I found them elsewhere.
Maintainers should either patch this version to accept PHP 7.0, or put back older (compatible) versions of the package in the repo or some accessible  place...

**Comment by israel-lugo** [comment]
Why was this issue closed without any comment or explanation? This is a real issue and is affecting multiple people.

The Debian 9 repository is currently not compatible with official Debian 9 packages and therefore broken. People are left with irrecoverable installations that cannot be downgraded.

ownCloud aims to be production-ready software, correct? So are you not going to address this obvious production issue?

**Comment by dleducq** [comment]
Well, obviously the OC team don't bother very much providing useful packages : no dependencies handling, no integration scripts... I could understand that they don't want to support Debian oldstable, or even Debian at all, or maybe any distro, but breaking things like that, and then closing issues without fixing them or even leaving a comment, shows a lack of respect for their users, IMHO !

**Comment by blubbi321** [comment]
Same issue on Ubuntu 16.04 LTS:

Install source: deb http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/ 

Apache + PHP from Ubuntu repos. 

Error message: 
```
This version of ownCloud requires at least PHP 7.1.0
You are currently running PHP 7.0.33-0ubuntu0.16.04.12. Please update your PHP version.
```

**Comment by netlane** [comment]
Right, there is no php7.1 or above package in Ubuntu xenial (16.04LTS) 
(see: https://packages.ubuntu.com)
Yet it is an owncloud server 10.4 installation prerequisite
(see https://doc.owncloud.org/server/10.4/admin_manual/installation/system_requirements.html)

This page needs to be changed (remove last section "Ubuntu_16.04 owncloud-files-10.4.0-1+1.1")
https://download.owncloud.org/download/repositories/production/owncloud/

And this archive to be either removed or changed to the last owncloud server that worked with php7.0
https://download.owncloud.org/download/repositories/production/Ubuntu_16.04/

ATTENTION: Anyone who has added the repository in the past to Ubuntu_16.04 will break his owncloud installation in the moment he does a normal update of his distribution

**Comment by Herschdorfer** [comment]
I just ran in the same issue on Debian 9.12, precisely a OMV Installation 

> Linux omv.tl-photography.at 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u2~bpo9+1 (2019-11-12) x86_64 GNU/Linux)

> This version of ownCloud requires at least PHP 7.1.0 You are currently running PHP 7.0.33-0+deb9u6. Please update your PHP version. debian

i solved it with a downgrade but this cannot be the solution.

Downgrade:
```
wget https://download.owncloud.org/download/repositories/10.3.2/general/Debian_9.0/all/owncloud-files_10.3.2-1+2.1_all.deb
dpkg -i owncloud-files_10.3.2-1+2.1_all.deb
sudo dpkg -i owncloud-files_10.3.2-1+2.1_all.deb
```

**Comment by mr-smidge** [comment]
I was bitten by this packaging issue on an Ubuntu 16.04 LTS Production server.  Similar to @Herschdorfer 's advice above, I was able to downgrade as follows:

```
$ wget https://download.owncloud.org/download/repositories/10.3.2/general/Ubuntu_16.04/all/owncloud-files_10.3.2-1+2.1_all.deb
$ sudo dpkg -i owncloud-files_10.3.2-1+2.1_all.deb
```

For safety, one can then prevent the package from being updated again by using `apt-mark`:

```
$ apt-mark hold owncloud-files
$ apt dist-upgrade -s
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  owncloud-files
0 to upgrade, 0 to newly install, 0 to remove and 1 not to upgrade.
```

Hope this is useful.

**Comment by ho4ho** [comment]
Duplicate by https://github.com/owncloud/core/issues/36330

**Comment by blubbi321** [comment]
Ok, so if this is not going to be fixed at least the docs need to be updated in regard that Ubuntu 16.04 LTS is not supported with a configuration for apt: https://doc.owncloud.org/server/10.4/admin_manual/installation/linux_installation.html

Thanks @mr-smidge and @Herschdorfer for the workarounds!

**Comment by ho4ho** [comment]
> Ok, so if this is not going to be fixed

Thinking fixing only possible by downgrade ownCloud (unsuggested because outdated) or by upgrade PHP by user (suggested):

https://doc.owncloud.org/server/10.4/admin_manual/release_notes.html#php-7-0-support-discontinued

> at least the docs need to be updated in regard that Ubuntu 16.04 LTS is not supported with a configuration for apt: https://doc.owncloud.org/server/10.4/admin_manual/installation/linux_installation.html

Thinking to, create issue by https://github.com/owncloud/docs/issues ?

**Comment by israel-lugo** [comment]
This is terrible manners, let alone terrible support. A mistake is one thing, but actually being made aware that the official package is silently leaving users in a broken state and closing the bug without even making a comment? That's just not having any pride in one's own work. It is certainty not what I would've expected from a project like owncloud.

The Debian 9 repository doesn't work with Debian 9. And apparently it doesn't work with Ubuntu 16.04 either.

I've spent enough time with this already migrating to a separate Debian 10 system, just to deal with owncloud's brokenness. It seems clear that no one from owncloud is looking at this bug anymore and I will not be following up further.

I would however suggest someone open another bug to get someone's attention, and probably a separate bug for the doc.

On 28 April 2020 18:34:08 BST, ho4ho <notifications@github.com> wrote:
>> Ok, so if this is not going to be fixed
>
>Thinking fixing only possible by downgrade ownCloud (unsuggested
>because outdated) or by upgrade PHP by user (suggested):
>
>https://doc.owncloud.org/server/10.4/admin_manual/release_notes.html#php-7-0-support-discontinued
>
>> at least the docs need to be updated in regard that Ubuntu 16.04 LTS
>is not supported with a configuration for apt:
>https://doc.owncloud.org/server/10.4/admin_manual/installation/linux_installation.html
>
>Thinking to, create issue by https://github.com/owncloud/docs/issues ?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/core/issues/37104#issuecomment-620750568

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ho4ho** [comment]
Found by https://github.com/owncloud/docs/issues/2631:

> 4. To be aware that you'll have to manage the PHP installation independently
