### ISSUE TITLE
https not used on password reset

### ISSUE THREAD

**Issue by rLy07** [owncloud/core#37150]
I'm not sure if the issue is with owncloud or my apache config but when I create a new user and follow the url from the email and arrive on the password setup page, the URL used in the set-password form is not using https 
`<form action="http://cloud.okay-den.net/index.php/setpassword/826213306794660620506/test7" id="set-password" method="post">`
Other than the fact that this is not secure?, this doesn't even work if I turn off the HTTPS Everywhere addon in firefox. If I change http to https within firefox using the dev tools it works as it should. Also even though the site is setup for https the URL in the email that's sent out only uses http. It might be that the issue is with my server setup, but I'm no expert and wasn't able to figure out yet.

### Steps to reproduce
1.Create new user
2.Follow url from email to set password
3.Noting happens upon pressing the button

### Expected behaviour
Successful password setup

### Actual behaviour
Nothing happens

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache 2.4.10

**Database:** MariaDB 10.4.12

**PHP version:** 7.2

**ownCloud version:**10.4.0

**Updated from an older ownCloud or fresh install:** yes

**Where did you install ownCloud from:**downloaded from the website

**Signing status (ownCloud 9.0 and above):**
No errors have been found.

**The content of config/config.php:**
https://gist.github.com/rLy07/55fcdd00bdb6bb9f08387e2900a8475b
apps left out as I don't think it's important

**List of activated apps:**
Related: Password policy from owncloud

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**no

### Client configuration
**Browser:** Firefox 74

**Operating system:** Arch Linux

### Logs
I don't really see any useful lines in the logs but if needed I post fresh logs.

**Comment by DeepDiver1975** [comment]
This can be caused by two things: 
1. in config.php overwrite.cli.url is set to  http://
2. the page from which you are creating the new user is running on http and not on https

In both cases it is a configuration issue - generally speaking all urls in your owncloud instance shall be runing on https only.
