### ISSUE TITLE
test previews via webDAV API tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#37156]
- [x]  make test for previews via WebDAV API
- [x]  use those tests to test the OCIS implementation of the previews see https://github.com/owncloud/ocis-webdav/pull/13

**Comment by phil-davis** [comment]
PR #37166 has been merged. It would be useful to now also add:
- [ ] test scenarios that set the maximum size of a preview (e.g. to 32x32) and then check that previews up to 32x32 can be fetched, but that larger preview requests do not come (or maybe they reply with a 32x32 preview). And try some combinations of prevview max height and width.

**Comment by phil-davis** [comment]
I added this to server QA/CI project so it is still seen. The new scenarios are being added to enhance core coverage anyway.

**Comment by phil-davis** [comment]
@individual-it see the linked PRs. Is this enough tests?
And the scenarios seem to have been sorted out for OCIS  also.
Close?

**Comment by individual-it** [comment]
LGTM
