### ISSUE TITLE
requesting a file preview with an ivalid size results in HTTP error 500

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#37165]
### Steps to reproduce
1. request a preview with size `0` e.g. `curl '172.17.0.1/owncloud-core/remote.php/dav/files/admin/lorem.txt?x=0&y=320&forceIcon=1&preview=1' -u admin:admin  -v`

### Expected behaviour
HTTP code 400 - Bad Request

### Actual behaviour
HTTP code 500 - Internal Server error

**Comment by phil-davis** [comment]
What about `x=-1` `x=1.5` `x=abc` ? :)

**Comment by individual-it** [comment]
> What about `x=-1` `x=1.5` `x=abc` ? :)

on it https://github.com/owncloud/core/pull/37166

**Comment by DeepDiver1975** [comment]
Which version is this? I'm getting a 404 on master

**Comment by DeepDiver1975** [comment]
is there an error in the log file? http 500 should write something into the logs
