### ISSUE TITLE
Can't share any folder to anybody - error "expiration date missing" after upgrade to 10.4.0.4

### ISSUE THREAD

**Issue by soniqsoft** [owncloud/core#37184]
### Steps to reproduce
1. Upgrade to 10.4.0.4
2. Try to share folder
3.

### Expected behaviour
Should be possible to share without specifying any expiration date when not set on admin Sharing page.
### Actual behaviour
Hi support Team,
URGENT CASE!
I'm owncloud user and admin for some time and recently I did upgrade to 10.4.0.4.
Upgrade was smooth and easy but...
AFTER UPGRADE I CAN'T SHARE ANY FOLDER TO ANY USER UNLESS I SET EXPIRATION DATE LESS THAN 7 DAYS FROM TODAY!
ANY LONGER DATE OR MISSING DATE CAUSES ERROR "The expiration date cannot exceed 7 days!".
WHATS ALSO STRANGE - ALL EXPIRATION DATES FOR EVERY USER AND SHARED FOLDER ARE NULL!
I tried to switch on and off several times the option "Set default expiration date for user shares" and Expire after 365 days and "Enforce as maximum expiration date" but no result!
Help me pls as nobody can share any folder to anybody at all!
Thanks!

### Server configuration
**Operating system**:
Centos 7.7.1908
**Web server:**
Apache 2.4.
**Database:**
mysql  Ver 15.1 Distrib 5.5.64-MariaDB, for Linux (x86_64) using readline 5.1
**PHP version:**
PHP 7.2.29 (cli) (built: Mar 17 2020 11:36:18) ( NTS )
**ownCloud version:** (see ownCloud admin page)
10.4.0.4
**Updated from an older ownCloud or fresh install:**
updated
**Where did you install ownCloud from:**
official repo for Centos
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No errors have been found.

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```
Enabled:
  - activity: 2.5.3
  - bookmarks: 0.10.6
  - brute_force_protection: 1.0.1
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.5.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_external_ftp: 0.2.1
  - files_mediaviewer: 1.0.2
  - files_pdfviewer: 0.11.1
  - files_sharing: 0.12.0
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.2.0
  - gallery: 16.1.1
  - guests: 0.9.0
  - impersonate: 0.5.0
  - market: 0.5.0
  - notifications: 0.5.0
  - oauth2: 0.4.3
  - ownbackup: 19.5.0
  - password_policy: 2.1.1
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - twofactor_totp: 0.6.1
  - updatenotification: 0.2.1
  - user_external: 0.6.0
Disabled:
  - encryption
  - external
**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox, Chrome
**Operating system:**
Mac OS X (latest)
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by phil-davis** [comment]
If youare using password policy app, then it could be https://github.com/owncloud/password_policy/issues/287
Workaround: do not set public link expiration policies for now (until the fix is released)

**Comment by karakayasemi** [comment]
There is a known bug which occurs when 10.4.0 and password_policy app used together. You can learn details from the below issues. This bug will be resolved with new password_policy app and server version 10.4.1. As a temporary solution, you can disable public link expiration policies of password_policy app.

https://github.com/owncloud/password_policy/issues/287
https://github.com/owncloud/password_policy/issues/286

**Comment by phil-davis** [comment]
https://doc.owncloud.com/server/admin_manual/release_notes.html#known-issues
