### ISSUE TITLE
ownCloud MySQL SSL connection dbdriveroptions are changed

### ISSUE THREAD

**Issue by cs35-owncloud** [owncloud/core#37201]
Hello everyone,

I run ownCloud 10.3.2 community version and I set MySQL SSL connection to encrypt communication between ownCloud and the MySQL server. It's working but I noticed some weird behavior on the ownCloud side.

### Steps to reproduce
1. Set a MySQL server with encryption, generate a client certificate/key pair
2. Install the certificate, key and ca on the ownCloud server
3. Add the dbdriveroptions in your ownCloud config.php:

```
  'dbdriveroptions' => array(
    PDO::MYSQL_ATTR_SSL_KEY =>'/etc/ssl/client-key.pem',
    PDO::MYSQL_ATTR_SSL_CERT =>'/etc/ssl/lient-cert.pem',
    PDO::MYSQL_ATTR_SSL_CA => '/etc/ssl/ca.pem',
    PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
  ),
```
4. Install (occ maintenance:install) or upgrade (occ upgrade) your ownCloud

### Expected behaviour
The config.php should keep its constants unchanged.

### Actual behaviour
ownCloud seems to change the config.php by replacing the strings of the constants by the numeric values, which gives:

```
  'dbdriveroptions' =>
  array (
    1007 => '/etc/ssl/client-key.pem',
    1008 => '/etc/ssl/client-cert.pem',
    1009 => '/etc/ssl/ca.pem',
    1014 => false,
  ),
```
The encryption still works but the configuration file gets messy to read.

### Server configuration
**Operating system**:

**Web server:** NGinx 1.16.1

**Database:** MySQL 5.7

**PHP version:** 7.3.16

**ownCloud version:** 10.3.2

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** tarball

**Signing status (ownCloud 9.0 and above):** all good

**The content of config/config.php:**

```
# occ config:list system
{
    "system": {
        "datadirectory": "\/var\/owncloud\/data",
        "version.hide": true,
        "logtimezone": "UTC",
        "installed": true,
        "upgrade.disable-web": true,
        "upgrade.automatic-app-update": false,
        "updatechecker": false,
        "updater.server.url": "127.0.0.1",
        "maintenance": false,
        "user.search_min_length": 2,
        "loglevel": 2,
        "log_type": "syslog",
        "singleuser": false,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "apps_paths": [
            {
                "path": "\/var\/owncloud\/apps_orig",
                "url": "\/apps_orig",
                "writable": false
            },
            {
                "path": "\/var\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/owncloud\/theme",
                "url": "\/theme",
                "writable": false
            }
        ],
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "dbdriveroptions": {
            "1007": "\/etc\/ssl\/client-key.pem",
            "1008": "\/etc\/ssl\/client-cert.pem",
            "1009": "\/etc\/ssl\/ca.pem",
            "1014": false
        },
        "trashbin_retention_obligation": "30,auto",
        "versions_retention_obligation": "auto, 7",
        "trashbin_purge_limit": 25,
        "skeletondirectory": "",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "10.3.2.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
    }
}

```

**List of activated apps:**

```
# occ app:list
Enabled:
  - activity: 2.5.3
  - brute_force_protection: 1.0.1
  - calendar: 1.6.4
  - comments: 0.3.0
  - configreport: 0.2.0
  - contacts: 1.5.5
  - dav: 0.5.0
  - encryption: 1.4.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_external_dropbox: 1.2.0
  - files_external_ftp: 0.2.1
  - files_mediaviewer: 1.0.2
  - files_pdfviewer: 0.11.1
  - files_sharing: 0.12.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - guests: 0.8.2
  - notifications: 0.5.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - tasks: 0.9.7
Disabled:
  - external
  - market
  - user_external
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes, master encryption

**Are you using an external user-backend, if yes which one:** no

If you need more informations let me know.
Thanks for your help.

**Comment by DeepDiver1975** [comment]
This happens when owncloud is writing back the config array to the file. Indeed not nice.

But I think there is not much we can do about this.

**Comment by cs35-owncloud** [comment]
Thanks for you fast answer. Just for my knowledge, why is it changed and why it couldn't be fixed ?
If there is really no solution, is it possible to have a workaround like creating an other config.php file such as encryption.config.php and set it as readonly in ownCloud ? It's not a think that will change quite often.

**Comment by DeepDiver1975** [comment]
> why is it changed

there is logic in place which loads all *.config.php into the php process and writes then the-one-and-only config.php. This logic needs to stay in place for various reasons and we have no option to change this logic.

you could try to make the config.php read only. This is documented in the docs.

Let me know if this works out.

**Comment by cs35-owncloud** [comment]
Well my question I guess was not clear enough. I understand that ownCloud rewrites the configuration it makes sense. But why does it change the parameters to their numeric values is what bothers me and should not change. ownCloud doesn't manage itself the certificate, you can't add them via occ or the web interface, so ownCloud shouldn't rename the parameters.

Well the problem is that this [feature](https://doc.owncloud.com/server/admin_manual/configuration/server/config_sample_php_parameters.html#define-if-config-php-is-read-only) sets all the config files in RO as I understand. In my case I want the config.php to be writable and a specific one to be RO. So yes I could do this on the system side but that's messy as hell. Plus I guess ownCloud won't like that.

**Comment by DeepDiver1975** [comment]
> But why does it change the parameters to their numeric values is what bothers me and should not change.

PDO::MYSQL_ATTR_SSL_KEY is a const which defines the integer value. In RAM there is only the integer value and when writing back to disk: it remains to be an integer.

There is no way to find out what the const value was. This is how any programming language works - not much we can do.

**Comment by cs35-owncloud** [comment]
You're right, I thought you might re-use the definition of the constant to rewrite it properly, but I understand it's a pain in the ass.

Well I'll find a workaround then.

Thanks.
