### ISSUE TITLE
Migration to 10.3.2 hangs on Updating DAV - 20170202213905

### ISSUE THREAD

**Issue by StephanThierry** [owncloud/core#37213]
### Steps to reproduce
1. Take a DB with 1.191.719 rows in oc_properties   
2. Try to convert that DB from 9.0.11 to 10.3.2
3. Did it finish?  

It could be a lot of rows in other tables causing the issues - but reading https://github.com/owncloud/core/blob/master/apps/dav/appinfo/Migrations/Version20170202213905.php - oc_properties seems likely.

### Expected behaviour
Updating DAV (20170202213905) should finish, and migration continue to next step  

### Actual behaviour
Updating DAV (20170202213905) runs seemingly infinite - was stopped after 25h. CPU usage on both cores where 30-95% for all 25h, so it did not appear halted.

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL running on localhost

**PHP version:**
PHP 5.6

**ownCloud version:** (see ownCloud admin page)
Upgrade from  9.0.11 to any of the 10+ versions like 10.3.2 

**Updated from an older ownCloud or fresh install:**
Updated from 8.2.1 -> 8.2.11 -> 9.0.11  

**Where did you install ownCloud from:**
Unknown - it's been running for many years

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.

Stuck in upgrade, so the message from the URL is: "This ownCloud instance is currently in maintenance mode, which may take a while."
```

**The content of config/config.php:**

sudo -u www-data php occ config:list system:  
```
{
    "system": {
        "instanceid": "oc35fe4449dc",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "[ourip]",
            "ourdomain.com"
        ],
        "datadirectory": "\/mnt\/storage\/owncloud\/data\/",
        "overwrite.cli.url": "http:\/\/[ourip]\/owncloud",
        "dbtype": "mysql",
        "version": "9.0.11.2",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "log_type": "owncloud",
        "logfile": "\/mnt\/storage\/owncloud\/owncloud_new.log",
        "loglevel": 0,
        "maintenance": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "singleuser": false,
        "logtimezone": "Europe\/Berlin",
        "theme": "",
        "trashbin_retention_obligation": "31",
        "activity_expire_days": 10
    }
}
```

**List of activated apps:**
```
Enabled:
  - activity: 2.5.3
  - comments: 0.2
  - configreport: 0.2.0
  - dav: 0.1.6
  - federatedfilesharing: 0.3.1
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.5.2
  - files_pdfviewer: 0.11.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.3.0
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - firstrunwizard: 1.2.0
  - gallery: 16.1.1
  - market: 0.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.5.0
  - systemtags: 0.2
  - templateeditor: 0.4.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_mediaviewer
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/sftp/...  
no   

**Are you using encryption:** 
no  

**Are you using an external user-backend, if yes which one:** 
no  

### Client configuration
**Browser:**
Chrome  

**Operating system:**
Windows 10  

#### Web server error log
```
No errors  
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VtJfiqKiuQSWmDL0r3Tx","level":0,"time":"2020-04-05T11:43:28+02:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"starting upgrade from 9.0.11.2 to 10.3.2.2"}
{"reqId":"VtJfiqKiuQSWmDL0r3Tx","level":0,"time":"2020-04-05T11:43:30+02:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Migrations: starting 20170202213905 from app dav"}
```
The migration was restarted - so only 2 entries are in the current log.  

#### Browser log
```
Does not apply
```

**Comment by StephanThierry** [comment]
The upgrade now finished - it took  88h

2020-04-10T17:18:03+02:00 Updating database schema
2020-04-10T17:18:03+02:00 Updated database
2020-04-10T17:18:03+02:00 Updating <dav> ...
2020-04-14T09:18:42+02:00 Repair step: Remove invalid calendar and addressbook shares
2020-04-14T09:18:42+02:00 Updated <dav> to 0.5.0
2020-04-14T09:18:42+02:00 Updating <federatedfilesharing> ...
2020-04-14T09:18:42+02:00 Updated <federatedfilesharing> to 0.5.0

**Comment by DeepDiver1975** [comment]
This is a heavy lifting operation which will take some time for 1 million files.
This migration was part of 10.0 and such time consuming operations are to be expected on major releases.

Not much we can do. Sorry
