### ISSUE TITLE
In OCS Share API, the status message is less informative while user update date of a share after enforced maximum date is reduced.

### ISSUE THREAD

**Issue by Talank** [owncloud/core#37217]
### Steps to reproduce
1. With max date enforced to 30 days, create a share for file `lorem.txt` 
2. Reduce the max enforced date to 5 days
3. Try to update the expiry date to 28 days in the future.

### Expected behaviour
A nice OCS error message telling what went wrong Eg: `Cannot set expiration date more than 5 days in the future`

### Actual behaviour
The OCS status message is `Expiration date is in the past`

### Server configuration
**current core master**

**Comment by phil-davis** [comment]
Re-opening. The test scenario to demonstrate the issue has been merged (PR #37206 ) but the issue still needs to be looked into and fixed.

**Comment by JammingBen** [comment]
This issue has been fixed meanwhile. https://github.com/owncloud/core/pull/39200 enables the acceptance tests for the expected behavior.
