### ISSUE TITLE
Permissions Error for ${ocdata}/.htaccess During Upgrade

### ISSUE THREAD

**Issue by miqrogroove** [owncloud/core#37273]
Permissions defined here restrict writing the .htaccess file to the root user only.
https://doc.owncloud.org/server/10.4/admin_manual/installation/ubuntu_18_04.html
```
if [ -f "${datadir}/.htaccess" ]; then
  sudo chmod 0644 "${datadir}/.htaccess"
  sudo chown "${rootuser}:${htgroup}" "${datadir}/.htaccess"
fi
```

As a result, the occ upgrade script logs the following error message.
```
{"reqId":"4LLOPl5yLs1g8X5lRYzy","level":0,"time":"2020-04-16T20:58:53+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"starting upgrade from 10.3.2.2 to 10.4.0.4"}
{"reqId":"4LLOPl5yLs1g8X5lRYzy","level":3,"time":"2020-04-16T20:59:03+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"file_put_contents(\/var\/owncloud-data\/.htaccess): failed to open stream: Permission denied at \/var\/www\/owncloud\/lib\/private\/Setup.php#542"}
```

No other problems so far.  The old .htaccess file seems to work fine for now.

**Comment by ho4ho** [comment]
https://doc.owncloud.org/server/10.4/admin_manual/maintenance/manual_upgrade.html#permissions:

> To finalize the preparation of the upgrade, you need to set the correct ownership of the new ownCloud files and folders.
>
> sudo chown -R www-data:www-data /var/www/owncloud

**Comment by miqrogroove** [comment]
ho4ho that's a different path and you know it.

**Comment by ho4ho** [comment]
Not different path, https://doc.owncloud.org/server/10.4/admin_manual/installation/ubuntu_18_04.html#finalise-the-installation showing default:

```
ocpath="/var/www/owncloud"
datadir="${ocpath}/data"
```

datadir: /var/www/owncloud/data

match:

sudo chown -R www-data:www-data /var/www/owncloud

If changed datadir by you need to think and update above similar.

**Comment by ho4ho** [comment]
> Not bug by ownCloud, suggest: close

+ if doc unclear create issue by https://github.com/owncloud/docs/issues

**Comment by miqrogroove** [comment]
It is not unclear at all.  It LITERALLY says this:

> If you keep your data outside of your owncloud directory, then you don’t have to do anything with it, because its location is configured in your original config.php, and none of the upgrade steps touch it.

**Comment by ho4ho** [comment]
> + if doc unclear create issue by https://github.com/owncloud/docs/issues

Doc done there, not core repository.

**Comment by miqrogroove** [comment]
Fixed in issue above.
