### ISSUE TITLE
Support for PHP 7.4

### ISSUE THREAD

**Issue by apblack96** [owncloud/core#37299]
### Steps to reproduce
1.Unable to install Owncloud on Ubuntu 20.04 due to PHP incompatibility.
2.
3.

### Expected behaviour
Should be able to support PHP 7.4

### Actual behaviour
Unable to support PHP 7.4

### Server configuration
**Operating system**: Ubuntu 20.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4

**ownCloud version:** (see ownCloud admin page) 10.0.4

**Updated from an older ownCloud or fresh install:** Upgraded from old install

**Where did you install ownCloud from:** Owncloud website

**Comment by phil-davis** [comment]
Duplicate of #36509 
It's coming "real soon now" (tm) :)

**Comment by apblack96** [comment]
When will a tarball be available for download for this?

**Comment by phil-davis** [comment]
The nightly tarball build should have this in it overnight:
https://download.owncloud.org/community/daily/owncloud-daily-master.tar.bz2

From tomorrow, that could be used to test on a system with PHP7.4
