### ISSUE TITLE
Undefined index ListCommand.php

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#37305]
### Steps to reproduce
1. Create a local storage, e.g.
```
php occ files_external:create zzz local null::null -c datadir=/home/phil/zzz
Storage created with id 10
```

2. Set it to "read only" but specify `read-only` instead of `read_only`
```
php occ files_external:option 10 read-only 1
```

3. List the mount
```
php occ files_external:list
+----------+-------------+---------+---------------------+------------------------------+--------------+------------------+-------------------+
| Mount ID | Mount Point | Storage | Authentication Type | Configuration                | Options      | Applicable Users | Applicable Groups |
+----------+-------------+---------+---------------------+------------------------------+--------------+------------------+-------------------+
| 10       | /zzz        | Local   | None                | datadir: "\/home\/phil\/zzz" | read-only: 1 | All              |                   |
+----------+-------------+---------+---------------------+------------------------------+--------------+------------------+-------------------+
```

4. Look in the log:
```
cat data/owncloud.log
```

### Expected behaviour
Nothing in the log. (or some message at step 2 to say that `read-only` is not a valid mount option)

### Actual behaviour
Log contains:
```
{"reqId":"9AWg3BKkaywwv8j1Hm4X","level":3,"time":"2020-04-24T10:29:10+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined index: read-only at \/home\/phil\/git\/owncloud\/core\/apps\/files_external\/lib\/Command\/ListCommand.php#222"}
```

### Server configuration
Current git core master

**Comment by mmattel** [comment]
Do I interpret correctly that setting a mount option via occ currently does not check at all if the option exists. Because if there would be a check made, listing would return a correct option if set, and there would be no error logged by design - or?

**Comment by phil-davis** [comment]
> Do I interpret correctly that setting a mount option via occ currently does not check at all if the option exists. Because if there would be a check made, listing would return a correct option if set, and there would be no error logged by design - or?

When setting mount options from the command line, you can set whatever options you want. I guess that allows for different storages that might have their own extra options that are unknown to the core code. So some storage might have an option `special-option` or `read-only` and there is also the known core option `read_only`

There are 2 ways to fix this:
1) If only the known "core" options are allowed, then enforce that in the `php occ files_external:option` command, so you cannot set other "random" options.
or
2) If extra "random/unknown" options are allowed, then fix `php occ files_external:list` so that it does not log errors about that in `owncloud.log`

**Comment by mmattel** [comment]
My suggestion would be the following for `files_external:option`:
1. The standard behaviour should be, that only core allowed/known options are able to be set. This changes nothing on the command itself but on an internal check.
2. Extend the funcionality to allow additional non core allowed/known options, like an additional option `--allow-unkown`

This would imply your second point regarding `files_external:list`.
But also there, I would extend the way of listing to the following:
`files_external:list --mount-options -s` plus additional parameters should print a differnt short list showing the mount ID, mount name and its mount-options plus column if it is standard or unknown.

Having that we would stay with the current functionality but extend it with new parameters.

**Comment by mmattel** [comment]
Question: do we know (and if where), which possible mount options are defined by core?

I am thinking about a extension like `files_external:list --core-mount-options` without more parameters just listing the known mount options. This would help admins to get the known once for proper parametrisation.
