### ISSUE TITLE
Subject of mail when sharing files via link does not get translated to german

### ISSUE THREAD

**Issue by weber-ebusiness** [owncloud/core#37321]
### Steps to reproduce
1. Set default_language to de_DE in the config.php.
2. Click on the sharing button of a file or folder.
3. Create a public link.
4. Share it with someone over mail with the designated button.

### Expected behaviour
The subject "X has shared Y with you" should be in german (default_language).

### Actual behaviour
The subject "X has shared Y with you" is not getting translated to german. 

This is because in **lib/private/Share/MailNotifications.php:257**, the string that should get translated is "%s shared »%s« with you" - which seems correct. 

However, in _apps/files_sharing/l10n/de_DE.json_ there is only the string "%2$s shared %1$s with you" (https://github.com/owncloud/core/blob/master/apps/files_sharing/l10n/de_DE.json#L64) - but not the correct one:
(https://github.com/owncloud/core/blob/master/lib/private/Share/MailNotifications.php#L257). 

To fix this, maybe add the string "%s shared »%s« with you" to the de_DE.json file?

**Comment by DeepDiver1975** [comment]
Which version are you running? We recently fixed an issue in this area? THX

**Comment by DeepDiver1975** [comment]
Actually this issue - https://github.com/owncloud/core/issues/37040 - but this is at a different code location. I'll have a look ....

**Comment by weber-ebusiness** [comment]
Sorry, forgot to mention the version we are running. We are running version 10.4.1. 
 https://github.com/owncloud/core/pull/37056/commits/83823684c85b58b33e90ce512288770f7a10be68 fixxed it for the "sendInternalShareMail", but not for "sendLinkShareMail".

**Comment by DeepDiver1975** [comment]
@weber-ebusiness feel free to test the changes in https://github.com/owncloud/core/pull/37322

**Comment by weber-ebusiness** [comment]
Yes, that fixed the issue. Thank you very much for the fast response!

**Comment by DeepDiver1975** [comment]
> Thank you very much for the fast response!

You are welcome!
