### ISSUE TITLE
BUG - No email value in API create user

### ISSUE THREAD

**Issue by sanilea** [owncloud/core#37323]
### Steps to reproduce
1. curl -X POST http://admin:admin@localhost/owncloud/ocs/v1.php/cloud/users -d userid="testuser" -d email='testuser@yahoo.fr'

### Expected behaviour
It would create a user whithout specify password and send a link to testuser@yahoo.fr

### Actual behaviour
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>101</statuscode>
  <message>A valid password must be provided</message>
 </meta>
 <data/>
</ocs>

If I specify a password in request, the user will be create but the email address is not set  

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache

**Database:** SQLite

**PHP version:** 7.3.11

**ownCloud version:** 10.4.1

**Updated from an older ownCloud or fresh install:** update from 10.4.0.11

**Where did you install ownCloud from:**

**The content of config/config.php:**

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "oc3lsqjlqczk",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.xx.xx"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.xx.xx\/owncloud",
        "dbtype": "sqlite3",
        "version": "10.4.1.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "logtimezone": "UTC",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/owncloud\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "installed": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false
    }
}
```

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.5.0
  - encryption: 1.4.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_mediaviewer: 1.0.2
  - files_sharing: 0.12.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.2.0
  - market: 0.5.0
  - notifications: 0.5.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
Disabled:
  - external
  - user_external
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"Xqrax6BOKQH5vOnGk22W0gAAAAk","level":3,"time":"2020-04-30T14:03:51+00:00","remoteAddr":"10.24.87.5","user":"admin","app":"ocs_api","method":"POST","url":"\/owncloud\/ocs\/v1.php\/cloud\/users","message":"Failed addUser attempt with exception: A valid password must be provided"}```

**Comment by errieman** [comment]
Because of inactivity, I'm just adding that I am experiencing this problem as well.

**Comment by DeepDiver1975** [comment]
While the design seems to be sub optimal ... there is a second api call necessary to add the email.
Since we are not actively working on new features like this I'll close this. THX

**Comment by errieman** [comment]
Since this will not be changed, the documentation should be updated where it says that a password is not required when an e-mail address is provided, because an e-mail address can not be provided when creating a user: https://doc.owncloud.com/server/admin_manual/configuration/user/user_provisioning_api.html#add-user

**Comment by DeepDiver1975** [comment]
Yeah ... Docs are just plain wrong ..... 🙈

**Comment by phil-davis** [comment]
Doc issue https://github.com/owncloud/docs/issues/2723
