### ISSUE TITLE
occ market:upgrade incompatible with read-only /apps directory

### ISSUE THREAD

**Issue by enbrnz** [owncloud/core#37361]
IF you have a config for your application directories like so:
```php
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/owncloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/owncloud/custom',
      'url' => '/custom',
      'writable' => true,
    ),
  ),
```
This is the current standard for our docker containers and ansible deployments.

AND an app that has been shipped with ownCloud receives an update, e.g user_ldap 0.15. -> 0.15.1

AND you either use the WebUI or occ market:upgrade to install the new app version

THEN the new app version will be installed in the folder `/custom` while the old version is still in `/apps`. This obviously leads to problems. Especially when the app update requires an `occ upgrade` command. As the website reports that an app needs an upgrade, but the `occ upgrade` reports that the apps are all up to date.

### Steps to reproduce
I was able to reproduce the issue in a standard docker compose setup like so:
1.Start the docker container 
2. Manually downgrade an app that has been shipped with the container in the `/apps` directory, e.g user_ldap 0.15
2.1 Exec into the container `docker-compose exec owncloud entrypoint bash`
2.2 `cd apps`
2.3 `wget https://github.com/owncloud/user_ldap/releases/download/v0.15.0/user_ldap-0.15.0.tar.gz`
2.4 `rm -r user_ldap`
2.5 `tar xf user_ldap-0.15.0.tar.gz`
2.6 `chown -R --ref user_external user_ldap`
2.7 `chmod -R --ref user_external user_ldap`
3. Run the upgrade `occ market:upgrade user_ldap`

### Expected behaviour
The command should overwrite the existing app

### Actual behaviour
A second version of the app is installed in the folder `/custom`

### Server configuration
**Operating system**: Ubuntu 19.10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3.11

**ownCloud version:** 10.4.1

**Updated from an older ownCloud or fresh install:** no

**Where did you install ownCloud from:** docker

**The content of config/config.php:** [config_report_20200507.txt](https://github.com/owncloud/core/files/4592558/config_report_20200507.txt)

**List of activated apps:**

```
Enabled:
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.5.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_external: 0.7.1
  - files_mediaviewer: 1.0.2
  - files_sharing: 0.12.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.2.0
  - market: 0.5.0
  - notifications: 0.5.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - updatenotification: 0.2.1
  - user_ldap: 0.15.1
Disabled:
  - encryption
  - external
  - user_external
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
No relevant error here
```

#### ownCloud log (data/owncloud.log)
```
No relevant error here
```

#### occ market:upgrade user_ldap stdout
```
user_ldap: Installing new version 0.15.1 ...
user_ldap: App updated.
```

**Comment by VicDeo** [comment]
```
THEN the new app version will be installed in the folder /custom while the old version is still in /apps. This obviously leads to problems. Especially when the app update requires an occ upgrade command. As the website reports that an app needs an upgrade, but the occ upgrade reports that the apps are all up to date.
```
And this is **absolutely correct** due to ` 'writable' => false,` for the first app dir and ` 'writable' => true,` for the second

**Comment by VicDeo** [comment]
for multiple app versions in defferent app directories the most recent version should be loaded.

**Comment by VicDeo** [comment]
duplicate of https://github.com/owncloud/appliance/issues/63 which is confirmed to be fixed in 10.3.1 release

**Comment by enbrnz** [comment]
Just for my understanding:
The expected behavior is to have two app versions in two folders, when updating an app that is installed in the read-only app folder?

I am sure, that I have had this problem since 10.3.1, at multiple sites. Also community users in central have reported this bug recently (upgrade from 10.4 to 10.4.1).

Usually what happens is that even though the latest version of ownCloud including apps has been installed in the filesystem the market app tries to update apps anyway, and puts another version in the `custom` folder. What usually happens next is that you run `occ upgrade` which runs through, but you go to the website and it shows that you still have to run it (`occ upgrade`). When you run it again the command replies that there is nothing to upgrade but the webUI still complains.

**Comment by VicDeo** [comment]
> The expected behavior is to have two app versions in two folders, when updating an app that is installed in the read-only app folder?

yes, `'writable' => false,` means `oC has no permissions to manage files and directories in this app folder` so deletion of the previous app version is not allowed.

**Comment by VicDeo** [comment]
> Usually what happens is that even though the latest version of ownCloud including apps has been installed in the filesystem the market app tries to update apps anyway, and puts another version in the custom folder. What usually happens next is that you run occ upgrade which runs through, but you go to the website and it shows that you still have to run it (occ upgrade). When you run it again the command replies that there is nothing to upgrade but the webUI still complains.

it potentially could be caused by a dirty external cache e.g. redis

**Comment by VicDeo** [comment]
@enbrnz FYI it is  done not by the market app itself but with the core preupgrade step https://github.com/owncloud/core/blob/master/lib/private/Repair/Apps.php
and what needs to be done is 
`'upgrade.automatic-app-update' => false` in config.php 
https://github.com/owncloud/core/blob/master/config/config.sample.php#L1485

then this preupgrade step would be skipped

**Comment by cortho** [comment]
> > The expected behavior is to have two app versions in two folders, when updating an app that is installed in the read-only app folder?
> 
> yes, `'writable' => false,` means `oC has no permissions to manage files and directories in this app folder` so deletion of the previous app version is not allowed.

While I agree with this behavior I think the ownCloud app loading mechanism is broken. I did not dig into the code but shouldn't ownCloud browse all available apps and then use the most recent version, regardless of their locations?

Since it is the default ownCloud behavior to come with a read only apps directory and a writable apps-external directory it must not be delegated to the end user managing apps versions.

I consider this a nasty bug which leads to lots of confusion, especially for beginners. See some postings from central as reference:
* https://central.owncloud.org/t/automatic-updating-is-disabled/32869/
* https://central.owncloud.org/t/update-needed-and-nobody/32982
* https://central.owncloud.org/t/update-needed-although-up-to-date/29413
* https://central.owncloud.org/t/internal-server-error-owncloud-10-7-0/33052
* https://central.owncloud.org/t/server-version-10-5-0-10-requests-an-upgrade-over-and-over-again/30847

and so on ...

**Comment by VicDeo** [comment]
> While I agree with this behavior I think the ownCloud app loading mechanism is broken. I did not dig into the code but shouldn't ownCloud browse all available apps and then use the most recent version, regardless of their locations?


yes, while **loading** the app.
while updating it uses the first available writable directory.

unfortunately your links are irrelevant to this issue... it's rather like https://github.com/owncloud/core/issues/38549
