### ISSUE TITLE
Updating owncloud on Debian Buster 10.4 (current stable) not working

### ISSUE THREAD

**Issue by johnxba** [owncloud/core#37409]
The update server is not working right. It is extremely slow to respond if it responds at all. 

Typical error:
```
# apt-get update
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Hit:4 http://deb.debian.org/debian buster-backports InRelease
Ign:5 https://download.owncloud.org/download/repositories/stable/Debian_10  InRelease
Err:6 https://download.owncloud.org/download/repositories/stable/Debian_10  Release
  Connection timed out Error reading from server - read (11: Resource temporarily unavailable) [IP: 2a01:4f8:1c0c:8147:: 443]
Reading package lists... Done
E: The repository 'https://download.owncloud.org/download/repositories/stable/Debian_10  Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Try to visit `https://download.owncloud.org/download/repositories/production/Debian_10` using wget, or GUI browsers such as Firefox or IE11.

Browsers Edge or Edge Chromium seem to work somewhat, which may cause someone to wrongly assume that it works. Downloads take forever, fail or work only by chance.

It tries to redirect a couple of times, which fails.
The I tried to jump over the not working redirects by changing `/etc/apt/sources.d/owncloud.list`:
`#deb https://download.owncloud.org/download/repositories/stable/Debian_10/ /
deb https://download.owncloud.org/download/repositories/production/Debian_10/ /`

The first line is the commented out original line, the second is the shortcut. If it seems to work, you could see this:

```
# apt-get update
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:3 http://deb.debian.org/debian buster InRelease
Hit:4 http://deb.debian.org/debian buster-updates InRelease
Hit:5 http://deb.debian.org/debian buster-backports InRelease
Ign:2 https://attic.owncloud.org/download/repositories/production/Debian_10  InRelease
Get:6 https://download.owncloud.org/download/repositories/production/Debian_10  Release [601 B]
Get:7 https://download.owncloud.org/download/repositories/production/Debian_10  Release.gpg [481 B]
Get:7 https://download.owncloud.org/download/repositories/production/Debian_10  Release.gpg [481 B]
Get:7 https://download.owncloud.org/download/repositories/production/Debian_10  Release.gpg [481 B]
Get:7 https://download.owncloud.org/download/repositories/production/Debian_10  Release.gpg [481 B]
Get:8 https://download.owncloud.org/download/repositories/production/Debian_10  Packages [743 B]
Get:8 https://download.owncloud.org/download/repositories/production/Debian_10  Packages [743 B]
Get:8 https://download.owncloud.org/download/repositories/production/Debian_10  Packages [743 B]
Get:8 https://download.owncloud.org/download/repositories/production/Debian_10  Packages [743 B]
Fetched 1,825 B in 3min 3s (9 B/s)
```

But new attempts fail again

Without being able to see what's happening, my guess is that there are a bunch of non-working redirects or even a redirect loop. And the server doesn't properly digest HTTP requests.

Also see: https://github.com/owncloud/core/issues/37104

**Comment by DeepDiver1975** [comment]
> E: The repository 'https://download.owncloud.org/download/repositories/stable/Debian_10  Release' no longer has a Release file.

@crrodriguez can you have a look? THX

**Comment by johnxba** [comment]
Currently, updating works at normal speed.

**Comment by DeepDiver1975** [comment]
> Currently, updating works at normal speed.

so we can close this? THX

**Comment by johnxba** [comment]
The problem isn't there any more, it can be closed from that perspective.

I'd recommend the server administrator to take a look and hopefully fix the root cause.

**Comment by crrodriguez** [comment]
Sometimes the mirrors fail, this is a knownn issue that is scheduled to be looked out at some point in the near future.

**Comment by swestlake** [comment]
I get an issue with Debian 10, I haven't been able to successfully update apt for some time,

my apt sources contains,
#deb https://download.owncloud.org/download/repositories/production/Debian_10/ /
deb http://download.owncloud.org/download/repositories/production/Debian_10/ /

and the output is,
"
Err:10 http://download.owncloud.org/download/repositories/production/Debian_10  InRelease           
  301  Moved Permanently [IP: 116.203.164.24 80]
E: Failed to fetch http://download.owncloud.org/download/repositories/production/Debian_10/InRelease  301  Moved Permanently [IP: 116.203.164.24 80]
..
E: The repository 'http://download.owncloud.org/download/repositories/production/Debian_10  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
"

When I do apt-key list, 
"pub   rsa2048 2013-08-26 [SC] [expires: 2023-08-23]
      DDA2 C105 C4B7 3A66 49AD  2BBD 47AE 7F72 479B C94B
uid           [ unknown] ownCloud build service <obsrun@localhost>
sub   rsa2048 2013-08-26 [E] [expires: 2023-08-23]
sub   dsa2048 2013-08-26 [S] [expires: 2023-08-23]
"

I get the same results whether I use http or https... I'm connecting from Montreal, Canada..

**Comment by ho4ho** [comment]
Found by https://github.com/owncloud/docs/issues/2631:

> 4. To be aware that you'll have to manage the PHP installation independently
