### ISSUE TITLE
Non-birthday item in birthdays calendar

### ISSUE THREAD

**Issue by brianjmurrell** [owncloud/core#37429]
### Steps to reproduce
N/A

### Expected behaviour
I shouldn't see non-birthdays in the birthdays calendar and I shouldn't see birthdays for contacts that have been deleted.

### Actual behaviour
I have a completely non-contact/birthday related item in my birthdays calendar.  I also have birthdays for contacts that have been deleted.

### Server configuration
**Operating system:** CentOS 7.7

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.4.16

**ownCloud version:** 9.1.5 (but really relevant?  would upgrading remove the errant entries?)

**Updated from an older ownCloud or fresh install:** Updated (but also, not really relevant)

**Where did you install ownCloud from:** EPEL

**Signing status (ownCloud 9.0 and above):** ??

```
Not Found
The requested URL /index.php/settings/integrity/failed was not found on this server.
```

**The content of config/config.php:**

```
Is config.php really relevant in this case?
```

**List of activated apps:**

```
Again, relevant?
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome

**Operating system:** Fedora 31

I just want to remove the bad calendar entries.  I am a software developer so I am quite familiar with command-line tools, databases, SQL, etc.  I just need guidance on what to edit.

**Comment by brianjmurrell** [comment]
I've identified the record in `calendarobjects` that is showing in my birthday calendar erroneously.  Can I just delete that row without leaving any dangling references anywhere?

Strangely enough the `calendarid` for that row is not actually the `id` for my `Contact birthdays` in `oc_calendars`.  But since I don't even care about the event that it is, showing incorrectly in my `Contact birthdays`, I'd be just as happy to remove the entire record if I can do that without leaving any dangling references.

Advise?

**Comment by brianjmurrell** [comment]
I've also found the birthday calendar entries for the contact that has been removed previously.

So same question there, if I can remove them without leaving dangling references somewhere.

**Comment by DeepDiver1975** [comment]
There is also the table calendarchanges which tracks changes to all calendars. The data in that table is necessary for the caldav sync. In case you remove calendarobject you also need to add a new entry into the calendarchanges table.

**Comment by brianjmurrell** [comment]
Ahhh.  Glad I asked then.  Thanks so much for answering.

What would the entry in that table look like?  I suppose:

|Field|Description|
|-|-|
|`id`|Assigned automatically when I add a new row|
|`uri`|The `uri` field in `oc_calendarobjects`|
|`calendarid`|The `calendarid` value from `oc_calendarobjects`|

But what would be the value of the `operation` be for deletes from `oc_calendarobjects`?

What is `synctoken`?

**Comment by DeepDiver1975** [comment]
This is the logic: https://github.com/owncloud/core/blob/f94214e3660e7719491b9a9748aa76102fc4f2da/apps/dav/lib/CalDAV/CalDavBackend.php#L1477-L1489

- operation is 3 for delete
- the sync token is the current value of the calendar in the calendar table
- finally the syntoken in the calendar table needs to be incrementes

**Comment by brianjmurrell** [comment]
Ok then, so given a calendar:
```
+----+------------------------+-------------------+-------------------+-----------+
| id | principaluri           | displayname       | uri               | synctoken |
+----+------------------------+-------------------+-------------------+-----------+
|  4 | principals/users/brian | Contact birthdays | contact_birthdays |        60 |
+----+------------------------+-------------------+-------------------+-----------+
```

with an object that I want to remove:
```
+-----+---------------------------------------------------+------------+--------------+----------------------------------+------+---------------+----------------+---------------+--------------------------------------------------------+----------------+
| id  | uri                                               | calendarid | lastmodified | etag                             | size | componenttype | firstoccurence | lastoccurence | uid                                                    | classification |
+-----+---------------------------------------------------+------------+--------------+----------------------------------+------+---------------+----------------+---------------+--------------------------------------------------------+----------------+
| 143 | sabredav-90426df1-a0af-4bf1-ae21-e97845f7aca5.ics |          4 |   1493845767 | 443465b0319bf3b13fef13dc5b4058d9 | 6221 | VEVENT        |     1485554400 |    2145916800 | 4bb1d2ac-cb66-4ce4-bb4a-025add97d2a2-caldavsyncadapter |              0 |
+-----+---------------------------------------------------+------------+--------------+----------------------------------+------+---------------+----------------+---------------+--------------------------------------------------------+----------------+
```

```
DELETE FROM oc_calendarobjects WHERE id = 143;
INSERT INTO oc_calendarchanges (uri, synctoken, calendarid, operation) VALUES ('sabredav-90426df1-a0af-4bf1-ae21-e97845f7aca5.ics', 60, 4, 3);
UPDATE oc_calendars SET synctoken 61;
```

Yes?

**Comment by DeepDiver1975** [comment]
Looks good from what I can tell. Please take a backup of the database ... one never knows ....

**Comment by brianjmurrell** [comment]
Databases get backed up every night, so shouldn't be a problem.

Thanks for the confirmation.

**Comment by brianjmurrell** [comment]
Oops!  `UPDATE oc_calendars SET synctoken 61;` should be `UPDATE oc_calendars SET synctoken 61 where id =4`!  Good thing I had dumped that table before starting so I could restore the previous values.  :-)
