### ISSUE TITLE
"occ market:install -l" does not find the info.xml file

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#37447]
Despite the app dir containing the info.xml file at the usual localion `appinfo/info.xml` if I try to install the wopi app with the occ command I get the following error:

```
occ market:install -l wopi-1.3.0.tar.gz wopi
 : App does not provide an info.xml file
```

**Comment by voroyam** [comment]
never mind.

You need to provide an absolute path to the app. Then the command works.

```
occ market:install -l /tmp/wopi-1.3.0.tar.gz wopi
wopi: Installing new app from /tmp/wopi-1.3.0.tar.gz
wopi: App installed.
```

**Comment by jnweiger** [comment]
And you need to have it in a path readable by the www-data user.
