### ISSUE TITLE
Return JSON with information of executed jobs in cron.php

### ISSUE THREAD

**Issue by jbreitung** [owncloud/core#37489]
For some webservices which are calling the cron.php file to control the execution of background jobs of Nextcloud it could be very useful to return information about the executed job(s). This could contain the execution time, the execution status and/or some additional information about the background job.

Currently there is only an empty JSON response returned if the jobs of the joblist were executed. For every executed job, the required information for a response can be collected when iterating through the joblist so that it can be returned as an JSON-Array containing all information about all jobs.

**Comment by DeepDiver1975** [comment]
Since calling cron.php via http is done without any authorization one could consider this an information exposure. Nevertheless cron should be called by crontab on the server(s) anyway. 

I am closing this now since I don't see any need in implementing this. Sorry
