### ISSUE TITLE
Adjust tests that check mixed-case usernames

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#37493]
Some acceptance tests check results when a user is, for example, created as `Alice` and then accessed as `alice` or `ALICE`.

When we do username replacement, and have a replacement username that is the same when "upper" or "lower" (e.g. usernames that are just numbers, dots) then such scenarios do not work nicely, and some fail. e.g. see example PR #37475 

Investigate if we can make those more flexible so that the test scenarios understand when the uppercase/lowercase of the username are the same, and have the appropriate expectations in `Then` steps.

**Comment by dpakach** [comment]
Update here in https://github.com/owncloud/core/pull/37475#issuecomment-641050812
