### ISSUE TITLE
Add migration to disable enterprise_key app

### ISSUE THREAD

**Issue by micbar** [owncloud/core#37510]
## Description

Add a migration to disable the `enterprise_key` app when upgrading to ownCloud 10.5.0.

- This should work with the `enterprise_key` app being absent.

@pmaier1 @phil-davis am I missing something?

Some fancy message?

**Comment by pmaier1** [comment]
Something like: "The enterprise_key app is deprecated and obsolete. It has been disabled therefore."

**Comment by micbar** [comment]
Closed by #37512
