### ISSUE TITLE
Internal Server Error after upgrade

### ISSUE THREAD

**Issue by corsbj** [owncloud/core#37524]
I'm running debian stretch and have added the owncloud repository (http://download.owncloud.org/download/repositories/production/Debian_9.0/) to sources.list.d/owncloud.list.
I was so careless as to run apt update && apt upgrade without thinking and it upgraded my owncloud to 10.4.1. Now the site didn't want to open, because the default php on stretch is 7.0.
I updated to php 7.3 from sury.org, and now the site loads, but just throws an internal server error on the front page.

`Internal Server Error

The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times and include the technical details below in your report.

More details can be found in the server log.`

In the apache logs I get this error:
`[Sun Jun 14 12:17:42.116924 2020] [:error] [pid 31631] [client 192.168.8.5:40158] PHP Fatal error: Uncaught TypeError: Return value of OC::crashLog() must be an instance of void, none returned in /var/www/owncloud/lib/base.php:1056\nStack trace:\n#0 /var/www/owncloud/status.php(58): OC::crashLog(NULL)\n#1 {main}\n thrown in /var/www/owncloud/lib/base.php on line 1056`

There is nothing logged in owncloud.log or the php log.

sudo -u www-data php occ config:list system results:
`An unhandled exception has been thrown:
Error: Call to undefined function simplexml_load_file() in /var/www/owncloud/lib/private/App/InfoParser.php:48
Stack trace:
#0 /var/www/owncloud/lib/private/App/AppManager.php(482): OC\App\InfoParser->parse('/var/www/ownclo...')
#1 /var/www/owncloud/lib/private/App/AppManager.php(771): OC\App\AppManager->getAppInfoByPath('/var/www/ownclo...')
#2 /var/www/owncloud/lib/private/App/AppManager.php(712): OC\App\AppManager->getAppVersionByPath('/var/www/ownclo...')
#3 /var/www/owncloud/lib/private/App/AppManager.php(654): OC\App\AppManager->findAppInDirectories('files')
#4 /var/www/owncloud/lib/private/legacy/app.php(548): OC\App\AppManager->getAppPath('files')
#5 /var/www/owncloud/lib/private/legacy/app.php(114): OC_App::getAppPath('files')
#6 /var/www/owncloud/lib/base.php(585): OC_App::loadApps(Array)
#7 /var/www/owncloud/lib/base.php(1059): OC::init()
#8 /var/www/owncloud/console.php(74): require_once('/var/www/ownclo...')
#9 /var/www/owncloud/occ(11): require_once('/var/www/ownclo...')
#10 {main}`

**Comment by phil-davis** [comment]
`php -m`
Is `xml` listed?
Maybe you need to add various PHP modules for 7.3?

**Comment by corsbj** [comment]
You are 100% correct. I was missing the modules in the new php version. Thanks for the quick answer :)
