### ISSUE TITLE
Whats up with the caching stuff?

### ISSUE THREAD

**Issue by youradds** [owncloud/core#37521]
OMG the caching stuff is painful to setup!!! I've installed:

apt install php-redis
apt install memcached
apt-get install redis
apt install php-apcu

Yet I can't get the bloomin thing to work! As soon as I load the admin area, I get the message:

```
Transactional file locking should be configured to use memory-based locking, not the default slow database-based locking. See the documentation ↗ for more information.
No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our documentation.
Please double check the installation guides ↗, and check for any errors or warnings in the log.
```
As per:

https://doc.owncloud.org/server/10.4/admin_manual/configuration/server/caching_configuration.html#apcu-configuration

`'memcache.local' => '\OC\Memcache\APCu',`

But I get this when I reload the admin area:

> 500 Internal Server Error
> nginx

No error in apache error logs, nginx error logs, or anything I can see.

What am I doing wrong? I've been going round and round in circles with this for days now - and its driving me crazy!

TIA

Andy

**Comment by DeepDiver1975** [comment]
Please seek for help in the public forum https://central.owncloud.org - THX
