### ISSUE TITLE
File versioning for MS Visio files does not work

### ISSUE THREAD

**Issue by jado84** [owncloud/core#37537]
### Steps to reproduce
1. Map WebDAV drive
2. Create MS Visio file "test.vsdx"
3. Save updated Version of Visio file

### Expected behaviour
The file "test.vsdx" should appear in the folder "file_versions" like "test.vsdx.v1562328203"

### Actual behaviour
There are NO versions of file "test.vsdx" in the folder "file_versions", but other files like "*.docx.vNNNN".
If I rename the file "test.vsdx" to "test.tvsdx" the file appears under "file_versions", but is not useable by MS Visio.

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by phil-davis** [comment]
Please fill in the issue template - ownCloud version, owncloud log etc.

I just got a copy of an example https://resources.oreilly.com/examples/9780735669468-files/blob/33ae5dab171fc3ed39d041ea02d98e9912f1ad41/Chapter10/Network%20Diagram_start.vsdx then uploaded that to a test ownCloud 10.5.0 system twice. The "old" version is listed in the UI and is on-disk:
```
$ ls -l data/admin/files_versions/
total 452
-rw-r--r-- 1 phil phil 460714 जून    16 12:55 'Network Diagram_start.vsdx.v1592291347'
```

**Comment by jado84** [comment]
I used the latest stable version "10.4.1.3".
So I am looking forward to the next release.

**Comment by phil-davis** [comment]
I tried `10.4.1.3` and `vsdx` file versions work fine for me with that version.
So there is some other difference with your installation.
