### ISSUE TITLE
E-Mail language is defined by the browser language, not from the ownCloud language settings

### ISSUE THREAD

**Issue by weber-ebusiness** [owncloud/core#37546]
### Steps to reproduce
1. Set the browser language to en_US.
2. Set the ownCloud language to de_DE (either in config.php default_language or in the user settings)
3. Share a file via email.

### Expected behaviour

The recipient should receive the email in the language the sender has set it in the ownCloud settings.

### Actual behaviour

The recipient receives the email in the browser language the sender has set it to.

### Server configuration
**Operating system**: CentOS 6.10

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2

**ownCloud version:** 10.4.1

**Updated from an older ownCloud or fresh install:** updated from older

**Where did you install ownCloud from:** https://download.owncloud.org/community/owncloud-10.4.1.tar.bz2

**Signing status (ownCloud 9.0 and above):** All checks passed.

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36

Is it wanted that the recipient doesn't get the email in the language from the sender's ownCloud language, but rather from the browser language? If yes, why?

**Comment by DeepDiver1975** [comment]
@pmaier1
