### ISSUE TITLE
List of locked files

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#37551]
@pmaier1 
After merging https://github.com/owncloud/core/pull/37460 (Add file action to explicitly lock a file)

You can now lock a file manually, but there is currently no functionality for users available to show which files have been locked. This can, and imho will be an issue because after a short period of time, nobody will remember which file shave been locked.

Please consider an entry like we have for files shared (by you / from you ect) in the UI for locked files. Customers and support will thank you.

@DeepDiver1975 @mic fyi

**Comment by mmattel** [comment]
Related: https://github.com/owncloud/core/pull/36452 (Include settings for the persistent locks)

**Comment by pmaier1** [comment]
Thanks for opening this issue!

Basically, the new file locking feature should be used to **temporarily** lock files to prevent concurrent edits. For that reason it has a default and a maximum lock timeout to expire locks after a certain amount of time. In essence, files will not stay locked infinitely and there's an indication for locked files in the file list.

There are no plans (and I don't see the necessity) to add a separate view to list locked files. Close?

**Comment by mmattel** [comment]
Closing is fine.
FYI when opening this issue, there was no link from #37460 to #36452, and I have not seen it.
Therefore it was necessary to highlight a possible problem.
This is solved with #36452.

> There are no plans (and I don't see the necessity) to add a separate view to list locked files

Complete right !
