### ISSUE TITLE
application/gzip mimetypealiases.dist.json addition

### ISSUE THREAD

**Issue by ho4ho** [owncloud/core#37564]
Add to:

resources/config/mimetypealiases.dist.json
resources/config/mimetypemapping.dist.json

following:

`application/gzip` similar of #37467, #37559

**Comment by phil-davis** [comment]
ToDo: add appropriate tests to cover this sort of mime-type stuff.

**Comment by ho4ho** [comment]
Also update https://github.com/owncloud/core/blob/master/core/js/mimetypelist.js required?

**Comment by phil-davis** [comment]
> Also update https://github.com/owncloud/core/blob/master/core/js/mimetypelist.js required?

PR #37570 

Are there even more places to update the mimetype lists?

**Comment by ho4ho** [comment]
Found:

https://doc.owncloud.com/server/10.5/admin_manual/configuration/mimetypes/

Maybe helps?

**Comment by ho4ho** [comment]
Found also https://github.com/owncloud/docs/issues/620
