### ISSUE TITLE
No limits for for persistent lock values

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#37579]
Referencing: owncloud/core#36452 (Include settings for the persistent locks)

Based on comment: https://github.com/owncloud/docs/issues/2696#issuecomment-648081007

> As far as I see in the PR, there is no explicit lock timeout being set, so it will use whatever default value is configured in the settings page.

This is a dangerous situation, because one can accidatially set a long lasting lock time. Remember IOS devices being locket out for "ever"...

@jvillafanez @micbar @pmaier1

**Comment by pmaier1** [comment]
Locks set via WebUI will use the default value configured in the settings. By default it's 30 minutes, admin can change it as desired in the range of the maximum timeout. All good.

**Comment by phil-davis** [comment]
The admin sets a maximum, and if some client asks for more than the maximum, then they only get the maximum. The client cannot successfully set lock timeout 9999999999.

**Comment by mmattel** [comment]
Sorry for the confusion, I have clarified the referenced doc comment.
