### ISSUE TITLE
Patch htmlPrefilter

### ISSUE THREAD

**Issue by C0rby** [owncloud/core#37598]
https://github.com/advisories/GHSA-gxr4-xjj5-5px2

Implement the suggested workaround:

> To workaround the issue without upgrading, adding the following to your code:
>```javascript
>jQuery.htmlPrefilter = function( html ) {
>	return html;
> };
> ```
> You need to use at least jQuery 1.12/2.2 or newer to be able to apply this workaround.

**Comment by mmattel** [comment]
PR:
https://github.com/owncloud/core/pull/37596 make htmlPrefilter an identity function
#37599 [10.5.0] make htmlPrefilter an identity function

Closing, both merged
