### ISSUE TITLE
global region format

### ISSUE THREAD

**Issue by georgehrke** [owncloud/core#376]
It would be really useful to have a global region format setting.

An american is expecting something like:
Monday, November 12, 2012
11/12/12
03:45pm

In contrast, a german is expecting something like:
Monday, 12. November 2012
12.11.12
15:45

There should be some methods which expect an DateTime object as parameter.
For example if a user set region format to US:
OC_Localization::getTime($datetimeobject) - returns 03:45pm
OC_Localization::getShortDate($datetimeobject) - returns 11/12/12
OC_Localization::getFullDate($datetimeobject) - Monday, November 12, 2012

Furthermore, it should be possible to parse localized dates
OC_Localization::parseTime('03:45pm') - returns an DateTime object
OC_Localization::parseShortDate('returns 11/12/12') - returns an DateTime object
OC_Localization::parseFullDate('Monday, November 12, 2012') - returns an DateTime object

**Comment by georgehrke** [comment]
reopened because there should be a dedicated region setting

**Comment by enoch85** [comment]
The oldest issue on GitHub, any new here? :)

**Comment by vsq** [comment]
Hello, a user here!
I always prefer English UI with Finnish or ISO date format. It should be possible to set combinations like this.

**Comment by jancborchardt** [comment]
@vsq as you can see from the screenshot I posted above https://github.com/owncloud/core/issues/376#issuecomment-19878427, of course language and date format will be separate.

**Comment by georgehrke** [comment]
@DeepDiver1975 @PVince81 Can you please assign a milestone

**Comment by PVince81** [comment]
before this can work, there is more work to be done especially regarding numbers in the web UI: https://github.com/owncloud/core/issues/20674
