### ISSUE TITLE
Inconsistent use of "Login" and  "Log in"

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#37603]
`core/templates/login.php` has:

```
				placeholder="<?php $_['strictLoginEnforced'] === true ? p($l->t('Login')) : p($l->t('Username or email')); ?>"
```

```
			<label for="user" class="infield"><?php $_['strictLoginEnforced'] === true ? p($l->t('Login')) : p($l->t('Username or email')); ?></label>
```

```
			<input type="submit" id="submit" class="login primary icon-confirm" title="<?php p($l->t('Log in')); ?>" value="" disabled="disabled"/>
```

```
			<?php p($l->t('You took too long to login, please try again now')); ?>
```

```
				<?php p($l->t("You are trying to access a private link. Please log in first.")) ?>
```

```
		<legend><?php p($l->t('Alternative Logins')) ?></legend>
```

There are variations of "log in" and "login"

What, if anything, should be changed?

**Comment by jnweiger** [comment]
The verb in Please log in first and the noun Login should be spelled exactly like seen above. One with a whitespace, the other without.
But `title="<?php p($l->t('Log in')); ?>"` looks strange. It could be read as the imperative `Now log in!` but I'd rather read it as a noun `Here goes your login`.

**Comment by phil-davis** [comment]
PR #37604 implements the suggested changes.

**Comment by phil-davis** [comment]
ToDo: after the weekend, check if translation changes came back from Transifex.

If so, then think about porting PR #37604 and the translation changes across to `release-10.5.0`

**Comment by phil-davis** [comment]
`release-10.5.0` branch was merged back to master, and then branched again. So these changes to words and the translation changes that came back will end up in 10.5.0
