### ISSUE TITLE
Random unit test failure

### ISSUE THREAD

**Issue by dpakach** [owncloud/core#37637]
There was a "random" unit test fail https://drone.owncloud.com/owncloud/core/25704/34/9
```
There was 1 failure:

1) Test\Files\Cache\UpdaterLegacyTest::testWrite
Failed asserting that 1593688056 is equal to 1593688057 or is greater than 1593688057.

/drone/src/tests/lib/Files/Cache/UpdaterLegacyTest.php:118
```
Unrelated to this PR. I will raise a separate issue about that, because I have seen it before.

_Originally posted by @phil-davis in https://github.com/owncloud/core/pull/37630#issuecomment-652963967_

**Comment by phil-davis** [comment]
I guess that the test might start running at some time like 09:10:35.99 and then the second ticks over to 09:10:36.00 and the expectation fails because the current time is different from some request time/saved time by 1 second.

**Comment by dpakach** [comment]
Seems like related to https://github.com/owncloud/core/issues/37726 
can we close this @phil-davis ?
