### ISSUE TITLE
pt_br: Translation error

### ISSUE THREAD

**Issue by samuel-rosa** [owncloud/core#37657]
There is a translation error for the Portuguese language in the following files:

* apps/federatedfilesharing/l10n/pt_BR.js
* apps/federatedfilesharing/l10n/pt_BR.json

In

```
"Add to your ownCloud" : "Adiconar ao seu ownCloud"
```

there is a missing "i" in "Adiconar". The correct form is

```
"Add to your ownCloud" : "Adicionar ao seu ownCloud",
```

**Comment by phil-davis** [comment]
Translations are done at https://www.transifex.com/owncloud-org/
You can register there and join the pt_BR translation group.

**Comment by samuel-rosa** [comment]
OK! Done!
