### ISSUE TITLE
Refactor "the public should be able to download file"  acceptance test steps

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#37671]
There are acceptance test steps like:
```
Then the public should be able to download file "parent.txt" from inside the last public shared folder using the new public WebDAV API with password "abcdefgh" and the content should be "ownCloud test text file parent" plus end-of-line
```
e.g. see PR https://github.com/owncloud/password_policy/pull/312/files

The line is way too long. And actually the last part "and the content should be "ownCloud test text file parent" plus end-of-line" can and should easily be done as a separate step.

`Webdav.php` already has:
```
Then the downloaded content should be "something"
Then the downloaded content should be "something" plus end-of-line
```

- make steps in PublicWebDavContext.php that are shorter
- use the steps from WebDav.php to test the downloaded content
- adjust whatever feature files use these steps (e.g. core, password_policy)

**Comment by HariBhandari07** [comment]
@phil-davis  should we split
 `Then the public download of file "/parent.txt" from inside the last public shared folder using the old public WebDAV API should fail with HTTP status code "404"`  into:
1. `And the public download of file "/parent.txt" from inside the last public shared folder using the new public WebDAV API should fail`
2. `And the HTTP status code should be "404"`

**Comment by phil-davis** [comment]
I think leave that. Even after splitting it is still a long step, and `should fail` will have to have logic added to decide what is "fail".
