### ISSUE TITLE
owncloud10.14.1,httpd2.4.43,mariadb10.5.4,display chinese character wrong

### ISSUE THREAD

**Issue by vechie** [owncloud/core#37677]
Operating system:
CentOS Linux release 7.8.2003 (Core)
Web server:
httpd 2.4.43
Database:
mariadb 10.5.4
PHP version:
php7.2
ownCloud version: (see ownCloud admin page)
owncloud 10.4.1
Updated from an older ownCloud or fresh install:
fresh install
Where did you install ownCloud from:
wget https://download.owncloud.org/community/owncloud-10.4.1.zip
Are you using external storage, if yes which one: local/smb/sftp/…
/var/www/html/owncloud/data
Are you using encryption: yes/no
no
Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/…
no
I create a chinese folder ,called 舍棉衣外套采购申请单青年美科技,and share with user01，and it works well .so I login as user01,first time it works well ,
when I refresh the browser some times，the folder changed to (2) .
I tried several times and sevreal fresh server and database, but the same wrong problem 。
so , the character_set about utf8mb4 not support Chinese characters? or mariadb version not support?

**Comment by phil-davis** [comment]
I am running CI with mariadb 10.5 now in PR #37678 and it is looking OK. That has both API and UI tests that have emojis and devanagari (Nepali-Hindi) Unicode characters in file and folder names. So general Unicode file-folder names with mariadb 10.5 look OK.

We don't have any automated tests specifically with Chinese or other Eats Asian (Korean, Japanese...) characters.

**Comment by vechie** [comment]
Maybe I found the solution of this problem, I update apache version 2.4.6 to 2.4.43 using following step:
1、 yum install yum-changelog
2、yum changelog httpd
3、yum install -y epel-release
4、cd /etc/yum.repos.d && wget https://repo.codeit.guru/codeit.elrpm -q --qf "%{VERSION}" $(rpm -q --whatprovides redhat-release).repo
5、yum info httpd
6、yum install httpd
and I delete the .repo file , remove httpd2.4.43, and install default version 2.4.6. the chinese character problem didn’t arise.
 :sweat_smile: :sweat_smile: :sweat_smile:

**Comment by VicDeo** [comment]
I guess it's an environment issue as downgrade of  httpd to a default v2.4.6 solved it. 
Nothing to fix from the ownCloud standpoint.
I'm closing this issue. Feel free to reopen.
