### ISSUE TITLE
Login screen design in ie11 is off ...

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#37690]
![Screenshot from 2020-07-14 10-56-24](https://user-images.githubusercontent.com/1005065/87409044-ad4d2f00-c5c4-11ea-9c5d-f7f7f1b97cd9.png)

**Comment by pmaier1** [comment]
@ChrisEdS

**Comment by micbar** [comment]
@DeepDiver1975 What theme is that?

**Comment by ChrisEdS** [comment]
Our new Community background.

**Comment by davitol** [comment]
<img width="1020" alt="Screen Shot 2020-07-14 at 12 22 41" src="https://user-images.githubusercontent.com/10596560/87415690-c0183180-c5cd-11ea-8907-a259fc35c7b3.png">
Internet explorer 11 and 10.4.1

**Comment by phil-davis** [comment]
In Firefox I see:
![Screenshot_2020-07-14 ownCloud](https://user-images.githubusercontent.com/1535615/87417223-92dc7b00-c5ef-11ea-988b-a2e678a0921e.png)

Which is the "new" background image for the login screen.
I guess that is the way it should be - logo images and Username/Password fields are centered.

**Comment by ChrisEdS** [comment]
Correct. Do you have a IE11 to validate the bug?

**Comment by phil-davis** [comment]
I installed IE11 on a laptop running current Windows10 (sad). The login looks OK  to me:
![IE11-oC10-login](https://user-images.githubusercontent.com/1535615/87420598-4c8a1a80-c5f5-11ea-88a2-0d1255d71ef3.png)

**Comment by phil-davis** [comment]
If I drag the bottom of the window to make it smaller, then the username and password fields do not resize automagically. They end up out of view:
![IE11-oC10-login-small](https://user-images.githubusercontent.com/1535615/87420708-7ba08c00-c5f5-11ea-9183-3b52bda86854.png)

On other browsers the username and password fields stay in view until the vertical height gets very small.

But that might be an existing "feature" with IE11.

**Comment by ChrisEdS** [comment]
> If I drag the bottom of the window to make it smaller, then the username and password fields do not resize automagically. They end up out of view:

You can still scroll to the credential fields, right?

**Comment by phil-davis** [comment]
> You can still scroll to the credential fields, right?

Yes

**Comment by phil-davis** [comment]
If I start with the window wide, or drag the window wide, then I get the screen like the first post - with the logo and credentials fields at the top, not centered. When I do the same in chrome or Edge they stay centered.

**Comment by ChrisEdS** [comment]
Fix is here https://github.com/owncloud/core/pull/37692
