### ISSUE TITLE
config:app:list command

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#37703]
### Steps to reproduce
1. There are `config:app:get` and `config:app:set` commands 
2. but no `config:app:list`

### Expected behaviour
New command: `config:app:list` + options

### Actual behaviour
Missing command, refrencing discussion starting at: https://github.com/owncloud/core/issues/37697#issuecomment-660071523

This is not only an admin but also a documentation nightmare. Nobody will remember config:app variables days after implementaion without a list command and documentation! In addition, a mistyped variable or value will be accepted but not considered in the program leading to confusion.

### Suggestion:
`config:app:list <options>` 
`<options>`:
`--app <appname>`  (the app name, else all)
`--internal` (list known changeable interal variables and their possible predifined values)
`--set` (list of changeable variables set and their values independent of internal or manually set)

(--set and --internal are mutually exclusive)

Example:
`config:app:list --app files --internal` 

### Server configuration
**ownCloud version:** 10.4.1 (10.5 RC2)

@phil-davis @pmaier1 @micbar

**Comment by phil-davis** [comment]
This would be handy to have. But it will require some engineering design so that when it is given the app name it can call some standard method in the app that is expected to return the information. And error handling for apps that do not yet have such a method.

**Comment by DeepDiver1975** [comment]
And please keep in mind: oc10 is soon EOL. Why waste energy on such things.

**Comment by phil-davis** [comment]
There is already the `config:list` command. That lets you put an app name to list just the configs for that app:
```
$ php occ config:list files_sharing
{
    "apps": {
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "yes",
            "installed_version": "0.14.0",
            "outgoing_server2server_share_enabled": "yes",
            "types": "filesystem"
        }
    }
}
```


and you can do `config:list core` to get various settings that are deemed to be `core` app.
Or `config:list system` to list what is is `config/config.php`

**Comment by phil-davis** [comment]
And documentation is here: https://doc.owncloud.com/server/next/admin_manual/configuration/server/occ_command.html#config-commands
