### ISSUE TITLE
File deleted from local storage exists in file cache

### ISSUE THREAD

**Issue by jasson99** [owncloud/core#37723]
### Steps to reproduce
1. Admin creates a local storage `local_storage`
2. Create user `Alice`
3. `Alice` creates folder `local_storage/foo3`
4. Alice creates file `textfile0.txt`
5. Alice moves file `textfile0.txt` to `local_storage/foo/textfile0.txt`
6. Delete `foo/textfile0.txt` from local storage on the server

### Expected behaviour
When user `Alice` downloads file `local_storage/foo3/textfile0.txt` as 
``` 
curl -u alice:1234 -X GET "http://172.17.0.1/oc/remote.php/webdav/local_storage/foo3/textfile0.txt" -v

< HTTP/1.1 404 Not Found

```

But when `Alice` checks if the file exists or not as: 
```
curl -u alice:1234 -X PROPFIND "http://172.17.0.1/oc/remote.php/webdav/local_storage/foo3/textfile0.txt" -v

```
Then the response is expected to contain status code `404` i.e the file is not expected to exist.

### Actual behaviour
When user `Alice` downloads file `local_storage/foo3/textfile0.txt` as 
``` 
curl -u alice:1234 -X GET "http://172.17.0.1/oc/remote.php/webdav/local_storage/foo3/textfile0.txt" -v

< HTTP/1.1 404 Not Found

```

But when `Alice` checks if the file exists or not as: 
```
curl -u alice:1234 -X PROPFIND "http://172.17.0.1/oc/remote.php/webdav/local_storage/foo3/textfile0.txt" | xmllint --format -

```
Then the response is as follows: 
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
  <d:response>
    <d:href>/oc/remote.php/webdav/local_storage/foo3/textfile0.txt</d:href>
    <d:propstat>
      <d:prop>
        <d:getlastmodified>Thu, 23 Jul 2020 10:56:35 GMT</d:getlastmodified>
        <d:getcontentlength>26</d:getcontentlength>
        <d:resourcetype/>
        <d:getetag>"c9c8161f5fe38aeb37f5227b47bb5656"</d:getetag>
        <d:getcontenttype>text/plain</d:getcontenttype>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
  </d:response>
</d:multistatus>


```

**Comment by phil-davis** [comment]
This is a case where the database "file cache" gets out-of-sync with the actual content of the local storage. e.g. if a local storage folder contains files that are added/changed/deleted "underneath". That can be a reasonable use case - some "standard reference data" is provided to everyone in a "local storage" which is set read-only. Some sysadmin updates the contents on a regular basis by adding/deleting/changing the files at the filesystem level.

I was hoping that when somebody attempts to download a file that actually that exists in the database file cache, but no longer exists on-disk in the filesystem, then the file would be removed from the database file cache.

If that happened, then at least the database file cache and filesystem would get themselves in sync as attempts were made to download non-existent files.

**Comment by hodyroff** [comment]
ownCloud expects to be the only consumer of its primary file system. There is a -rescan option for the rate cases where this is a useful requirement. There is no self-healing Phil.
Thank you so much for your report and effort, but this is an expected case in those circumstances. When you use external storage we have re-scan options on access, etc.
