### ISSUE TITLE
Add invalid uids

### ISSUE THREAD

**Issue by C0rby** [owncloud/core#37765]
There was a pull request before https://github.com/owncloud/core/pull/37268 which implemented a uid block list.
Add `.htaccess`, `.ocdata`, `owncloud.db` and `owncloud.log` to that list.

**Comment by phil-davis** [comment]
These normally appear in the default data directory:
`.htaccess`
`.ocdata`
`owncloud.log`

People could, for example, redirect their log somewhere else and then (presumably) username `owncloud.log` will work.

`owncloud.db` probably only exists if someone is using SQLite? That is not supported/encouraged for production installs anyway. But probably it will not hurt anyone to ban the username `owncloud.db`.

IMO it is reasonable to ban these usernames. I wonder if any existing site actually has any of these?

**Comment by C0rby** [comment]
> IMO it is reasonable to ban these usernames. I wonder if any existing site actually has any of these?

I hope not...
