### ISSUE TITLE
Reporting of unexpected failures when running just a single feature

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#37815]
If a developer runs just a single feature, e.g. putting
```
make test-acceptance-api BEHAT_FEATURE=tests/acceptance/features/apiComments/editComments.feature
```

and `EXPECTED_FAILURES_FILE` is defined,

then `tests/acceptance/run.sh` does understand to check just the expected failures for the `apiComments` suite - that is a good start.

But it will also report about expected failures in other feature files like `apiComments/createComments.feature`

1) Make it smarter so that when running just a single feature, it only processes expected failure for the feature.
2) Make it even smarter so that when running just a single scenario, it only processes expected failure for that exact scenario line number (if that is not "too hard" to do)

**Comment by phil-davis** [comment]
I think #37852 works nicely when running a single feature by the line number in the feature file.

But if you run a whole feature file (do not specify a line number) then it won't match up the expected failures.

**Comment by swoichha** [comment]
The problem with running a whole feature file without providing a specify line-number which won't match up the expected failures, has been fixed in https://github.com/owncloud/core/pull/38049. So, closing this issue.
