### ISSUE TITLE
Cannot clear lock notification message

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#37877]
### Steps to reproduce
1. share a file with another user - e.g. Alice shares to Brian
2. as Alice, lock the file with the new manual file locking on the web UI
3. as Brian, navigate to the folder that contains the file
4. click the lock icon to display the lock details
5. click the "unlock" icon for the lock by Alice
6. notification "Could not unlock, please contact the lock owner  Alice" is displayed
7. look for some way to acknowledge and clear the notification
8. navigate into other folders...

### Expected behaviour
There is some way to acknowledge and clear the notification

### Actual behaviour
The notification stays displayed, even after navigating into another folder, or displaying sharing details of other files...

### Server configuration
Current core master.

**Comment by phil-davis** [comment]
This was noticed because of failing CI in #37875 - in that PR the notifications ares has been moved to the bottom of the screen. In that case it obscures the file(s) that is listed at the bottom of the screen. The automated test fails because it cannot click on a file that it should be able to.

For a real user, there needs to be some way to clear the notification.

**Comment by hurradieweltgehtunter** [comment]
Solution: Change all notifications to `type: error`
Notification without closing icon is generated by: `OC.Notification.show("test")`
Notification with closing icon is generated by: `OC.Notification.show("test", {type: "error"})`

Question is if we really want to have all messages clearable or if some are intentional not clearable (e.g. CSFR check fails)

**Comment by phil-davis** [comment]
IMO Notifications that are related to a particular file and/or user action need to be clearable (or automatically go away after some seconds...) - otherwise users will navigate to other folders and files, and the notification stays "forever" but is stale - it does not apply to the folder/file currently displayed.

**Comment by hurradieweltgehtunter** [comment]
see latest comment in https://github.com/owncloud/core/pull/37875#issuecomment-690270635

**Comment by hurradieweltgehtunter** [comment]
#37875 implemented clearable notifications by default. I think this issue can be closed?

**Comment by phil-davis** [comment]
Yes, done. And the file lock test scenarios in the webUI tests do click the "dismiss/close" button to clear the message.
