### ISSUE TITLE
cloud/apps endpoint does not report always-enabled-apps in list of all apps

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#37884]
### Steps to reproduce
1. `curl -k -u admin:admin -X GET http://172.17.0.1:8080/ocs/v1.php/cloud/apps?filter=enabled`
Some reasonable list is returned:
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <apps>
   <element>files</element>
   <element>comments</element>
   <element>dav</element>
   <element>federatedfilesharing</element>
   <element>federation</element>
   <element>files_external</element>
   <element>files_sharing</element>
   <element>files_trashbin</element>
   <element>files_versions</element>
   <element>provisioning_api</element>
   <element>systemtags</element>
   <element>systemtags_management</element>
   <element>testing</element>
   <element>updatenotification</element>
  </apps>
 </data>
</ocs>
```

2. `curl -k -u admin:admin -X GET http://172.17.0.1:8080/ocs/v1.php/cloud/apps?filter=disabled`
Another reasonable list is returned:
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <apps>
   <element>files_classifier</element>
   <element>configreport</element>
...
   <element>files_mediaviewer</element>
  </apps>
 </data>
</ocs>
```
3. `curl -k -u admin:admin -X GET http://172.17.0.1:8080/ocs/v1.php/cloud/apps`
Query for all apps:
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <apps>
   <element>files_classifier</element>
   <element>configreport</element>
...
   <element>files_mediaviewer</element>
  </apps>
 </data>
</ocs>

```

### Expected behaviour
All the apps listed at (1) and (2) are in the combined list at (3)

### Actual behaviour
The "always-enabled-apps" are missing from the list. The missing apps are the ones listed in https://github.com/owncloud/core/blob/master/core/shipped.json

```
  "alwaysEnabled": [
    "files",
    "files_external",
    "dav",
    "federatedfilesharing"
  ]
```

### Server configuration
Current core master.

**Comment by phil-davis** [comment]
This seems a bit odd. 

https://github.com/owncloud/core/blob/master/lib/private/legacy/app.php `listAllApps()` excludes them.

But https://github.com/owncloud/core/blob/master/apps/provisioning_api/lib/Apps.php `getApps()` will end up "putting them back" if `filter=enabled` is provided, because they are in the enabled list.

In some other situations that  call `listAllApps()` it might be good to only return the apps that can be successfully enabled/disabled. But in this `cloud/apps` API request it looks like an accident that the always-enabled-apps can get filtered out.

**Comment by phil-davis** [comment]
I added some test scenarios to get coverage of both getting disabled apps and getting all apps. That was missing anyway from the acceptance tests.

Someone can decide if this is a bug or the intended behavior.

**Comment by phil-davis** [comment]
@micbar if someone can decide if this is a bug, then I already have code to fix it. It was easy to fix while making test scenarios.

**Comment by jnweiger** [comment]
##Retested with 10.6.0 RC1
List 1 and list 2 perfectly add up to list 3 on my system. OK
