### ISSUE TITLE
Wrong timezone in event details (linked calendars)

### ISSUE THREAD

**Issue by crunchy-github** [owncloud/core#37903]
### Steps to reproduce
1. subscribe for calendar https://ics.fixtur.es/v2/werder-bremen.ics
2. click on an event of the calendar
3. see the wrong timestamps (start end and) in the popup window )off by two hours)

### Expected behaviour
In the overview all events show the correct time. When clickinh on an event the popup window should show the same time (looks like the popup window is shown UTC (my timezone is CET)

### Actual behaviour
The popup windows seems to show the timestampsin UTC instead of CET

### Server configuration
**Operating system**:

Debian GNU/Linux 10

**Web server:**

Apache 2.5.38

**Database:**

MariaDB 10.3.22

**PHP version:**

7.3.14

**ownCloud version:**

18.0.9

**Updated from an older ownCloud or fresh install:**

update

**Where did you install ownCloud from:**

downloaded from owncloud servers

**Signing status (ownCloud 9.0 and above):** 

```
No errors have been found.
```

**The content of config/config.php:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/example.com",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "version": "18.0.9.1",
        "installed": true,
        "loglevel": 0,
        "maintenance": false,
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": 60,
        "app_install_overwrite": [
            "joplin"
        ]
    }
}
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 5.0.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - polls: 1.4.3
  - previewgenerator: 2.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.10
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.13.3
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
```

**Are you using external storage, if yes which one:**

no

**Are you using encryption:** 

no

**Are you using an external user-backend, if yes which one:**

no
### Client configuration
**Browser:**

Mozilla Firefox 80.0.1

**Operating system:**

Fedora 32

### Logs

if you need any logs just tell me

**Comment by karakayasemi** [comment]
There is no 18.0.9 version of the ownCloud. I guess, you need to open an issue on nextcloud repository. I am closing this one, thanks.
