### ISSUE TITLE
Review acceptance tests for case-sensitive user and group combinations

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#37940]
PR #37397 changed the test scenarios from using `user1` `user2`... to `Alice`, `Brian`...

There are some test scenarios that purposely create a group name that matches a user name - e.g. they create a group callled `Brian`. Those seem to have been adjusted OK.

But there are some scenarios that purposely create a group name that matches a user name, but with different case - e.g. have user `Brian` and group `brian`. Those seem to have ended up using group `Brian` rather than group `brian`.

Find them and adjust them back to testing this special user-and-group-name mixture.

e.g. https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiShareCreateSpecial2/createShareGroupAndUserWithSameName.feature "  Scenario: creating a new share with user and a group having same name but different case"

**Comment by swoichha** [comment]
Fixed by #38069
