### ISSUE TITLE
Gallery no longer working after upgrade to Owncloud 10.5.0

### ISSUE THREAD

**Issue by pappastech** [owncloud/core#37994]
I was running 10.0.10 for a while and just did an upgrade to the current 10.5.0. The upgrade process went smoothly with no errors/issues. However, the Gallery app now does not display anything other than the sorting icons at the top left and the share icon at the top right. No thumbnails and browsing is available. I don't see anything in the ownload log file at all. Anyone have any thoughts about where to start looking to troubleshoot this?

Kindly,
Tom

**Comment by DeepDiver1975** [comment]
The gallery app is discontinued - as a replacement files_mediaviewer is to be used (not yet a full replacement ....)

**Comment by ho4ho** [comment]
@DeepDiver1975 Release final gallery by set max vers 10.4 if not work?

**Comment by ho4ho** [comment]
Looked like compatibility problem by files_mediaviewer vs. gallery: https://github.com/owncloud/files_mediaviewer/pull/310, https://github.com/owncloud/files_mediaviewer/issues/102
