### ISSUE TITLE
[Tests-Only] Review and fix the tests that have sharing step to work with ocis

### ISSUE THREAD

**Issue by dpakach** [owncloud/core#38006]
In ocis shares are received by default on the `Shares` folder and auto accept is off
Many test scenarios outside of `apiSharing...` suite use sharing steps assuming that shares are received on root by default.

fix those tests to work with ocis as well.

**Comment by individual-it** [comment]
- [x] apiTrashbin https://github.com/owncloud/core/pull/38013
