### ISSUE TITLE
Gallery mark ownCloud 10.5 incompatible

### ISSUE THREAD

**Issue by ho4ho** [owncloud/core#38015]
Reporting here because https://github.com/owncloud/gallery archived:

Gallery not work ownCloud 10.5.0: #37994 , improve user experience by set max-version="10.4"/>:

https://github.com/owncloud/gallery/blob/v16.1.1/appinfo/info.xml#L36

with release v16.1.2 by https://marketplace.owncloud.com/apps/gallery ?

**Comment by jvillafanez** [comment]
If I remember correctly, the gallery app was deprecated / discontinued in favor of the files_mediaviewer. I don't think there are plans to change the decision, so it's up to you if you want to fork the app and make the required changes locally, or maintain it on your own.

**Comment by ho4ho** [comment]
@jvillafanez Sorry, thinking misunderstood (sorry, not good english by me).

> gallery app was deprecated / discontinued in favor of the files_mediaviewer

Not problem here, problem is by gallery app install possibility on ownCloud 10.5 but gallery app nothing compatible anymore: #37994 -> User experience bad

**Comment by ho4ho** [comment]
Looked like compatibility problem by files_mediaviewer vs. gallery: https://github.com/owncloud/files_mediaviewer/pull/310, https://github.com/owncloud/files_mediaviewer/issues/102
