### ISSUE TITLE
[QA] Disk full is reported as 'you took too long to log in'

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38010]
One of my test systems ran out of disk space.
The web UI shows a misleading error message when trying to log in
![image](https://user-images.githubusercontent.com/1108546/95971205-2f8dff00-0e11-11eb-93cc-f11b086a4d51.png)

Expected behaviour: an error related to the disk full condition is shown.

**Comment by DeepDiver1975** [comment]
> Expected behaviour: an error related to the disk full condition is shown.

I'd never expose system internal states to un-authenticated pages - considered as information disclosure .....

**Comment by DeepDiver1975** [comment]
Furhermore: if the disk is full - the code simply cannot run properly (e.g. no session file is written to disk) there is not much we can do as far as I can tell.

Vote for: close as won't fix :shrug:

**Comment by jnweiger** [comment]
No. I vote for: Remove the wrong message. Or at least add "Please see the server log for details"

**Comment by DeepDiver1975** [comment]
> No. I vote for: Remove the wrong message. Or at least add "Please see the server log for details"

As I tried to explain: the code can not properly if the disk is full. We have no control over the situation. We cannot change the message (easily).

**Comment by hodyroff** [comment]
Disk full = ownCloud will behave crazy. non predictable. Period. Closing. Always make sure the disk is not full. General a good thing for Linux anyway.
We can look at this for oCIS. Stays for oC10.
