### ISSUE TITLE
Excess of negative file system lookups

### ISSUE THREAD

**Issue by cavassin** [owncloud/core#38063]
Owncloud is making a lot of negative file system lookups looking for received shared files.
A negative lookup is a lookup to a non-existent file.
It's observed when a file is received by share from another user.
Them the file is being searched in several places.

Since it is a shared file, I think OC should look only at the database, avoiding the high cost of FS lookups.

In my setup, I have tons of these negative lookups, because there are a lot of files shared by several users within the same large group. The lookups have a high cost to glusterfs, which does not have yet a cache to negative lookups.

### Steps to reproduce

1. Create 3 test users (user01, user02, user03)

2. Create a group (group01) with the 3 users

3. user03 configure its Windows Desktop client to sync her account

4. user01 shares file SHARED_BY_USER01.TXT with group01

strace httpd shows 3 file system lookup for that shared file when the desktop client does a propfind.
```
13:25:22 lstat("/var/www/html/owncloud/data//user03/files/SHARED_BY_USER01.TXT", 0x7ffdf1ea9c00) = -1 ENOENT (No such file or directory)
13:25:22 lstat("/var/www/html/owncloud/data//user03/files/SHARED_BY_USER01.TXT", 0x7ffdf1eacc50) = -1 ENOENT (No such file or directory)
13:25:22 access("/var/www/html/owncloud/data//user03/files/SHARED_BY_USER01.TXT", F_OK) = -1 ENOENT (No such file or directory)
```
I think OC should not be making any FS lookups at all because it should be clear from the database that such a file is coming from user01 sharing, not from user03 own files.

If needed, maybe OC could make just one lookup or at least cache them.

5. user02 shares file SHARED_BY_USER02.TXT with group01

strace httpd now shows 12 file system lookup for those 2 shared files (again just user03 have the desktop client sync configured).
```
13:28:22 lstat("/var/www/html/owncloud/data//user03/files/SHARED_BY_USER01.TXT", 0x7ffdf1ea9c00) = -1 ENOENT (No such file or directory)
13:28:22 lstat("/var/www/html/owncloud/data//user03/files/SHARED_BY_USER01.TXT", 0x7ffdf1eacc50) = -1 ENOENT (No such file or directory)
13:28:22 access("/var/www/html/owncloud/data//user03/files/SHARED_BY_USER01.TXT", F_OK) = -1 ENOENT (No such file or directory)

13:28:22 lstat("/var/www/html/owncloud/data//user03/files/SHARED_BY_USER02.TXT", 0x7ffdf1ea9c00) = -1 ENOENT (No such file or directory)
13:28:22 lstat("/var/www/html/owncloud/data//user03/files/SHARED_BY_USER02.TXT", 0x7ffdf1eacc50) = -1 ENOENT (No such file or directory)
13:28:22 access("/var/www/html/owncloud/data//user03/files/SHARED_BY_USER02.TXT", F_OK) = -1 ENOENT (No such file or directory)

13:28:22 lstat("/var/www/html/owncloud/data//user01/files/SHARED_BY_USER02.TXT", 0x7ffdf1ea9440) = -1 ENOENT (No such file or directory)
13:28:22 lstat("/var/www/html/owncloud/data//user01/files/SHARED_BY_USER02.TXT", 0x7ffdf1eac490) = -1 ENOENT (No such file or directory)
13:28:22 access("/var/www/html/owncloud/data//user01/files/SHARED_BY_USER02.TXT", F_OK) = -1 ENOENT (No such file or directory)

13:28:22 lstat("/var/www/html/owncloud/data//user02/files/SHARED_BY_USER01.TXT", 0x7ffdf1ea9440) = -1 ENOENT (No such file or directory)
13:28:22 lstat("/var/www/html/owncloud/data//user02/files/SHARED_BY_USER01.TXT", 0x7ffdf1eac490) = -1 ENOENT (No such file or directory)
13:28:22 access("/var/www/html/owncloud/data//user02/files/SHARED_BY_USER01.TXT", F_OK) = -1 ENOENT (No such file or directory)
```

I think the lookups are unneeded. But the worse is that OC, besides looking up for both files in the user03 area, now is looking for SHARED_BY_USER01.TXT in the user02 area, and SHARED_BY_USER02.TXT in the user01 area.

Now imagine having dozens of users sharing within their large groups. And all users syncing their files.
Result: system load caused by glusterfs lookups, just to tell that files are not there.

I have to confirm yet, bu I think these lookups are happening also at logon time for any users that receive a share.

Please consider avoiding those negative lookups at all, or at least cache them within owncloud.

### Server Environment:

OS: CentOS 7
WEB Server: Apache 2.4.6
PHP: 7.2
Owncloud: 10.5.0

### Client Environment:
OS: Windows 10
Owncloud desktop version: 2.6.3

**Comment by wnabrud** [comment]
Hi @cavassin , I read and tested your report, and would like to give it a try to fix this issue. I would like to ask you if you can clarify the problem. since I see 2 problems in your report.
The first problem is that the dav subsystem is doing some dumb checks to see if the files are updated, and the second that you mention is that the GlusterFS is having a big hit for this lookups.
My proposed solution will be to only do the lookups on the files this user has assigned, what means in your example only 2 lookups. But you also proposed to implement a cache or more intelligent ways to know if there are changes, and hot always look the files. Is that ok?

**Comment by wnabrud** [comment]
@phil-davis sorry to mention you in this, but will like to know your opinion on my previous comment. Do I try to fix the extra lookups?

**Comment by cavassin** [comment]
> My proposed solution will be to only do the lookups on the files this user has assigned, what means in your example only 2 lookups. But you also proposed to implement a cache or more intelligent ways to know if there are changes, and hot always look the files. Is that ok?

Yes, your proposal is OK!
It will reduce the number of lookups, and that will probably fix my issue at all.

**Comment by phil-davis** [comment]
> @phil-davis sorry to mention you in this, but will like to know your opinion on my previous comment. Do I try to fix the extra lookups?

TBH I am not familiar with the detail of this code. It needs some different person to comment on minimizing file-system actions without missing some edge case.

**Comment by wnabrud** [comment]
Ok, after some hours debugging the code for the first time, I think I know what is going on, and will need some confirmation from @phil-davis or @DeepDiver1975 to check if I am in the right track.

The performance hit with distributed FS is that in every request to PROPFIND (and probably others) we are loading the file SharedMount and in its constructor is checking for duplicate names for files/directories for every shared file against the filesystem, line 145. This is done to deduplicate the file names and then updated in the database. If 2 files have the same name, only one will be shown.

I find a place where we can probably code a fix, and is in the class View, in line 1604 to 1610, where we detect also name collisions, and we can update the database instead of deleting the duplicated file.

If you think this can work, I could try to provide a change for this, and if you think I am missing something, just let me know and can put some more hours on it.

**Comment by phil-davis** [comment]
@micbar I don'/t have any real experience in the detail of this. Is there someone who could respond with some opinions/advice/assistance?

**Comment by wnabrud** [comment]
Hope this can have some comments added to continue or just stop the work. I am in the meantime trying to run the test locally. @micbar any comment?

**Comment by micbar** [comment]
@mrow4a Maybe you have a hunch on that?

**Comment by mrow4a** [comment]
@wnabrud @cavassin did you have a chance to find out what exact calls are hitting "non-existing file" ? I would be grateful for detailed code analysis in that regard to suggest something that hopefully fixes this issue.

**Comment by mrow4a** [comment]
@wnabrud @cavassin ok, indeed I see excesive number of calls to filesystem native calls https://www.php.net/manual/en/ref.filesystem.php , even for operations that do not require it (https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/SharedMount.php#L129) or could be taken from filecache. I totally agree, that in case of shared files (shares are just metadata), calls to filesystem shall not be done if they are not required. 

One challenge I see one would really need to sit down and see where are all these excessive calls done in the code, and see whether number of calls decreased after optimizing.

**Comment by mrow4a** [comment]
@cavassin I followed your instruction and reproduction steps (creating share, running strace), and I can confirm such operation [1] generates strace logs [2] e.g. hitting in https://github.com/owncloud/core/blob/master/apps/files_sharing/lib/SharedMount.php#L145 . Not sure how many such calls are there, but I can confirm negative lookup calls are generated.

[1]
```
curl -b XDEBUG_SESSION=VSCODE -X PROPFIND -u test3:test -H "Depth: 1" --data-binary "<?xml version=\"1.0\"?>
<d:propfind  xmlns:d=\"DAV:\" xmlns:oc=\"http://owncloud.org/ns\">
  <d:prop>
    <d:getlastmodified />
    <oc:checksums />
    <oc:size />
  </d:prop>
</d:propfind>" "http://localhost:8000/remote.php/dav/files/test3/TESTFSLOOKUPS.txt"
```

[2]
```
[pid   166] lstat("/mnt/data/files/test3/files/TESTFSLOOKUPS.txt", 0x7ffdef746620) = -1 ENOENT (No such file or directory)
```

**Comment by mrow4a** [comment]
@cavassin below I will carefully explain why we cannot fix this issue, HOWEVER you can fix it yourself by upgrading glusterFS -> https://docs.gluster.org/en/latest/release-notes/3.11.0/ . @micbar @cdamken could be interesting info for some other customers that we recommend upgrading for performance reasons? 

Reasoning:
- the code that is check for file existence in SharedMount, is used to detect whether there is already existing "real file" with the same name. In that care, SharedMount creates unique name with some suffix like `<filename> ( 2 ).txt`
- we HAVE to check in storage (in your case in glusterFS) if this file exists just to be sure we do not have some "not yet scanned and addded to filecache" file that e.g. got uploaded in the meantime
- if we would implement reading just from filecache, we could risk file integrity issues. This is also old code so god only knows what issues we could bump into if we do not ensure filename uniquenes by checking fs.

**Comment by cavassin** [comment]
Thank you @mrow4a for the analisys and pointing the new glusterfs release.
I undertood the reasoning to close this and I'm sure glusterfs negative lookup cache will solve the problem at all.
