### ISSUE TITLE
[QA] App update notification misses port number

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38074]
Tested with `docker run -ti -p 8080:8080 owncloud/server:10.6.0-beta1` on my 'localhost' and firefox browser.

* Log in as admin/admin
* after a while notice the red dot on the bell icon
* click the bell icon. An update notfication pops up, as an app update was released since the beta1 was built.

![image](https://user-images.githubusercontent.com/1108546/98032850-e845cd80-1e14-11eb-8b39-3e99d0609102.png)

The link in the notification reads `http://localhost/index.php/apps/market/#/app/activity`
* click the link. An error occurs:

![image](https://user-images.githubusercontent.com/1108546/98032959-14614e80-1e15-11eb-846a-26a932a37d0e.png)

Expected behaviour: the link contains the port number 8080.
If edited to include this, the app update can be viewed:

![image](https://user-images.githubusercontent.com/1108546/98033128-52f70900-1e15-11eb-8d5f-2ffb29419ca9.png)

**Comment by DeepDiver1975** [comment]
Config issue
The hostname / url need to be properly setup in config.php
Please follow the docs

**Comment by jnweiger** [comment]
Following https://doc.owncloud.com/server/10.5/admin_manual/installation/docker/#installation-on-a-local-machine to the letter, except that  use
VERSION=10.6.0-beta1 in my .env file, I get exactly the same behaviour.
the port number is missing.

**Comment by DeepDiver1975** [comment]
Then move this to the docker repo please. There is nothing to be done in this repo

**Comment by DeepDiver1975** [comment]
Docs are clear on how to use this -> closing
