### ISSUE TITLE
Tests for adding public link to your ownCloud

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#38109]
https://github.com/owncloud/core/blob/master/tests/acceptance/features/webUISharingPublic2/shareByPublicLink.feature has some scenarios that check that the "add to your ownCloud" button is displayed.

Create new scenarios that actually click the button, add the public link, and check that the user can see the file(s).

Probably this will need to be done in federated sharing test suites. The remote federated system can use the sharing API to create the public link. Then the scenario can browse to the public link with the webUI, click the "add"  button, and add to the local system. Then check that the files are available on the local system.

**Comment by phil-davis** [comment]
PR #38107 is related - it changes some code related to public links, so would be nice to have more automated tests available.

**Comment by mrow4a** [comment]
just a note - clicking a button can be quite complex, I think it does a redirect. what we are more interested is to test the part after the redirect to receiving side.

**Comment by phil-davis** [comment]
I looked more closely. The first scenario of https://github.com/owncloud/core/blob/master/tests/acceptance/features/webUISharingPublic2/shareByPublicLink.feature is:
```
  Scenario: mount public link
    Given using server "REMOTE"
    And user "Brian" has been created with default attributes and without skeleton files
    And using server "LOCAL"
    And user "Alice" has created folder "/simple-folder"
    And user "Alice" has uploaded file with content "original content" to "/simple-folder/lorem.txt"
    And user "Alice" has logged in using the webUI
    When the user creates a new public link for folder "simple-folder" using the webUI
    And the user logs out of the webUI
    And the public accesses the last created public link using the webUI
    And the public adds the public link to "%remote_server%" as user "Brian" using the webUI
    And the user accepts the offered remote shares using the webUI
    Then folder "simple-folder" should be listed on the webUI
    When the user opens folder "simple-folder" using the webUI
    Then file "lorem.txt" should be listed on the webUI
    And the content of file "simple-folder/lorem.txt" for user "Brian" on server "REMOTE" should be "original content"
    And it should not be possible to delete file "lorem.txt" using the webUI
```

That does the whole sequence of Alice creating a public link, the link being accessed, the link being added to Brian's ownCloud, Brian accessing the content of a file in the public link folder.

**Comment by phil-davis** [comment]
I added and extra scenario for "add to your ownCloud" when the public link is just a file (not a folder).
