### ISSUE TITLE
Clear text password in config/config.php after installation

### ISSUE THREAD

**Issue by rems28** [owncloud/core#38115]
### Steps to reproduce
1.Normal installation
2.Go to config/config.php
3.See the DB password

### Expected behaviour
The db password should hashed  for security reasons, in my mind

### Actual behaviour
Password in plain text

### Server configuration
**Operating system**:
Linux Debian 10
**Web server:**
Apache from package manager
**Database:**
Mariadb from package manager
**PHP version:**
7.3
**ownCloud version:** (see ownCloud admin page)
10.5
**Updated from an older ownCloud or fresh install:**
fresh insatll
**Where did you install ownCloud from:**
From your download package with .deb file or standalone .tar.*
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
Doesn't seems to be critical for this issue

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```
Doesn't seems to be critical for this issue

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox 78.4
**Operating system:**
Gentoo Linux
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by cortho** [comment]
I do not share your point of view.

The database password is required to establish a connection to the server. So at some point it must be present in "plain text". Having it hashed in config php would only be security by obscurity since the hashing algorithm would be readable somewhere in the code. It would only require a few steps to get back to the plain text password.

Storing passwords in configuration files in plain text is absolutely not uncommon (think e.g. of the postfix MTA sasl_passwd).

Since the config.php file should only be readable by the webserver, read access from other users is definitively prevented.

my 2 cents
