### ISSUE TITLE
Use icon from theme when sharing a llink in public post

### ISSUE THREAD

**Issue by T0mWz** [owncloud/core#38124]
When a public link is shared on a Social Media or other location, in some cases the ownCloud favicon-fb.png is shown.  This icon is located in core/img. But when a custom theme is used, then this icon should be taken from these theme instead of core. 

### Steps to reproduce
1. Create public link of a folder
2. Share that public link on a social media

### Expected behaviour
Your own icon should be displayed there.

### Actual behaviour
ownCloud favicon-fb icon from core is used

**Comment by T0mWz** [comment]
Example; ![Screenshot 2020-11-19 at 17 06 08](https://user-images.githubusercontent.com/2477797/99691505-96927980-2a89-11eb-8a39-a7dc25cdf881.png)

**Comment by T0mWz** [comment]
https://github.com/owncloud/core/compare/master...T0mWz:patch-4

**Comment by T0mWz** [comment]
https://github.com/owncloud/core/pull/38125

**Comment by T0mWz** [comment]
Oh, huh? Which version of ownCloud are you using?
Have cleared all my cache, but the social icon keeps coming from core instead of the theme. 
Have tested with 10.4.1, but will test 10.5 too. Will let you know. Thanks for helping!

**Comment by micbar** [comment]
@T0mWz still neded?

**Comment by T0mWz** [comment]
Have upgrade to 10.6.0 yesterday. But icon still not appears, really strange..

**Comment by micbar** [comment]
maybe releated to https://github.com/owncloud/core/pull/38246

**Comment by T0mWz** [comment]
Hi @micbar , @jvillafanez 
Sorry for my late reply. But with https://github.com/owncloud/core/pull/38246, my fix isn't needed anymore.
But had you already applied this patch to your environment, @jvillafanez ?

**Comment by jvillafanez** [comment]
Probably I tested it with 10.5.0 version, which I don't think it has the bug. The bug mentioned in https://github.com/owncloud/core/pull/38246 was introduced after 10.5.0 and is probably present in 10.6.0, so the patch should fix that.

**Comment by T0mWz** [comment]
Had the issue too with 10.5.0. But never mind, it's fixed with this patch.
