### ISSUE TITLE
Design forward: Global grouping system (categories/tags/topics/…) [$20]

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#3812]
First let me say: It might be a surprise to you that I think tags are a good idea now. This is _only_ when the system is holistic and across the whole platform – and when tags are the main/only system of categorization, not tacked on as an afterthought. Here we go:

There are several apps which use grouping, for instance Contacts, Bookmarks, (Files uses folders), etc. The problem is that every app uses their own system, which makes the whole thing a chore of repeatedly needing to organize your things.

But this can become a powerful system to aid filtering and search when these tags are shared across apps. @tanghus told me that there’s already backend code for it there, just not used / hooked up / finished yet.

Example: I would have tags for: »Design«, »ownCloud«, »Read«, »Watch«, »Psychology«, »Philosophy«, »Games«, »Nomadism«, »Berlin«, »San Francisco«, »Munich«, etc etc., so it would be topics, places, type of content, what to do with it, projects, and more. I currently use these manually in my apps for notes, reading stuff later, contacts, file system, news app, …. I guess you get the point because you probably also use tags or whatever system of categorization where these categories overlap across apps.

Another example: Planning your next vacation and you have a shared task list, some bookmarks, some files and some people you’re traveling with? No problem, just create the tag »Vacation yeah!« and share it with the friends involved in it!
Now no matter where you first created that tag (let’s say in the Files app to share a folder), it will also be available in the other apps for autocompletion.

Then there would need to be a view where you can see all the items in that category, even if they are across apps (easiest way: Show which other apps make use of that tag. Or show images or names of task lists directly).

Here’s a bit more of a stretch and maybe not a good idea, but it could even be automatic – wherever you create a tag, it will also be created in other apps (albeit we will probably not use the word »Tag« for it. Maybe rather »Topic«):
- Files can have a »bookmark« type quick filter in the sidebar, like other file managers
- Contacts will have a group of which the contacts you shared the topic with are members of
- Calendar will have a calendar named by that topic, automatically shared with those people.
- Tasks will have a task list named by that topic, automatically shared with those people.
- Bookmars will have a category …
- Pictures will have an album …
- News will have a folder …

Now I think the first step would be to get the apps which already use a notion of tags to use this. Namely Bookmarks @emerzh and Contacts @tanghus (because contacts can be in multiple groups).

I’m guessing @tanghus likes this (and would like to help implementing it ;)
cc app devs @icewind1991 @georgehrke @emerzh @Raydiation @zimba12 @bartv2

What do you think? @karlitschek @MTRichards @butonic @DeepDiver1975

**Comment by Bugsbane** [comment]
>  the City-class would generate a link to the citiy via GoogleMaps
> ...
> What do you think about the idea?

I think I'd rather Open Street Map. :)

**Comment by jancborchardt** [comment]
@zocker22 these are all nice technical ideas. We should start out with the purpose though: What is the actual value we can provide to people? And then design solutions for that. :)

**Comment by Bugsbane** [comment]
The value we can provide is simply to **make resources easily accessible based on the concepts and people that are relevant to the user**.

Currently, having to use folder structures makes finding things difficult, as files can only be assigned to one folder / concept (eg. photos/personal/family or photos/location/barcelona but not both) rather than multiple concepts (eg my kids + travel + Barcelona + DSLR + personal + 2014)

While there are a lot of fancy and complicated (but very cool) potential uses, I submit that 99% of what 99% of users would actually use tagging for is simply finding and sharing the stuff they want to.

eg. They want to **find**:

* "That document I worked on last week as part of project X" or...
* "That photo of my kids on the beach in Barcelona that a bunch of my family members liked" or...
* "That person that I emailed a couple of months ago about my taxes."

...or they wish to **share**:
* "All of the photos of my kids that are my favorites, with my family"
* "All of my tax doicuments with my accountant"
* "My party music with my media player on the deck outside"

Personally, what I really want tagging for is to be able to:

1. Share the best pictures of my kids with my family, while being able to sort them by both date, place and people involved
2. See which ones were liked the best by my family members
3. Let them give feedback such as ratings and later comments (no, comments aren't part of "tags")
3. Identify sets of files related to specific projects

**Comment by jancborchardt** [comment]
That’s what I wanted to hear. :) Just making sure we don’t start a feature by talking about how cool it would be and how to implement it, but how it will be valuable to actual people.

**Comment by Bugsbane** [comment]
> Just making sure we don’t start a feature by talking about how cool it would be and how to implement it

Lol. I'm just a user, without any ability to code / implement anything beyond a bug report or some graphic design. :) I **have** been desperately waiting for tags for a long time though, for the ability to do what I outlined above.

**Comment by jospoortvliet** [comment]
It looks like @Wattos has moved on and implemented an UI for this: https://github.com/Wattos/oc-custom-tags quite awesome, yes?

**Comment by oparoz** [comment]
Sharing is just as important as tagging. I was about to suggest introducing virtual folders, but grouping via tags would work as long as these clusters can be shared. It's currently a pain to have to duplicate files several times just because they need to be shared in different combinations.

**Comment by Bugsbane** [comment]
> Sharing is just as important as tagging.

Somewhere, I filed a feature request to be able to share by tag, which would solve this.

**Comment by oparoz** [comment]
@Bugsbane's request: https://github.com/owncloud/core/issues/13168

**Comment by Bugsbane** [comment]
Thanks @oparoz for being less lazy than I and doing the 15 seconds of research. ;-)

**Comment by oparoz** [comment]
lol, I was just curious. Sometimes referenced issues are not an exact match :)

**Comment by Bugsbane** [comment]
This seems, according to https://github.com/owncloud/core/issues/16325 to be targeted for v9. Possibly we should (ironically) be tagging this with both feature:tags and milestone 9.0-current

**Comment by maclag** [comment]
Resurrecting the thread to add some requests that may or may not belong here, but let's try:
If tags are to become a "main" feature, it would be appropriate they get easier to use:

When you deal with a lot of documents or photo, tagging them one by one is a real pain.
I would like to see a way to select a bench of documents and give them same tags all at once.

On a similar basis, tags should be visible when you browse a directory (I can't even figure out which photos are tagged and which are not!).

Finally, it would be really cool if one could make boolean operations on tags filter (eg: say I want to show photos of my house but maintain privacy of my family, I would use 'home' AND (NOT ('spouse' OR 'kid')).

**Comment by Bugsbane** [comment]
> I would like to see a way to select a bench of documents and give them same tags all at once.

Agreed, although I'd add that there are many other uses for being able to select multiple files at once and apply an operation (delete, move, copy, add to music que etc). 

Some kind of view for untagged files in the side bar would be useful as well.

**Comment by PVince81** [comment]
I suggest making separate tickets for these:
1) make it possible to view sidebar entries with multiple selection
2) adjust tags field to support showing/editing tags from multiple files
3) improve "Tags" filter field to allow boolean operations
