### ISSUE TITLE
Scrollbar hard to see

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/core#38182]
### Steps to reproduce
1. Open OwnCloud UI in Browser
2. Head to a site which scrollable content

### Expected behaviour
Scrollbar should be easy to see

### Actual behaviour
Scrollbar is too thin and to bright, so you can't see it well 

![Screenshot_20201202_112832](https://user-images.githubusercontent.com/26169327/100861943-c9c60700-3492-11eb-9f51-7030ebcc2fae.png)

**Comment by jnweiger** [comment]
Confirmed fixed for google-chrome in 10.7.0RC1
Firefox always had nice scrollbars, but in chrome 10.6.0 had the issue.
