### ISSUE TITLE
[QA] wrong password on a public share causes CSRF error

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38206]
Seen with 10.5.0:
* created a public link to a folder with password 1234
* in a fresh browser session, open the link and enter a wrong password xxxx

![image](https://user-images.githubusercontent.com/1108546/101904654-77819600-3bb6-11eb-9764-e8dbddceff3a.png)

Expected behaviour: Access denied. Without refering to CSRF checks.

**Comment by JanAckermann** [comment]
Not present anymore in master

![image](https://user-images.githubusercontent.com/26169327/105714350-8204ae80-5f1c-11eb-90e7-3fd190921236.png)
