### ISSUE TITLE
[QA] arabic translation is incomplete

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38219]
Tested with `docker- run --rm -ti -p 8080:8080 owncloud/server:10.6.0-rc6 

Coverage is very good in general. There are some remaining strings peeking through in English. E.g.
![image](https://user-images.githubusercontent.com/1108546/102337045-488e6a00-3f92-11eb-8b3e-2156f37121f1.png)

Transifex reports: Arabic 89.8% complete, 718 strings to translate 

@pmaier1 I suggest to
* involve @Akidxx as a native speaker. :-) 
* focus on one-click (and maybe two-click ?) reachability.

Milestone: later, I assume?

**Comment by jnweiger** [comment]
market app is untranslated.

**Comment by Akidxx** [comment]
Ok I will check it :+1:

**Comment by phil-davis** [comment]
Note: any recently-added translations will have been synced from Transifex to core master. They will not auto-magically get into the `release-10.6.0` branch. So if anyone want to improve the translations for 10.6.0 release, then manual action would be needed to carefully "backport".

**Comment by jnweiger** [comment]
nothing to do for 10.6.0 here
