### ISSUE TITLE
Deprecated "X-XSS-Protection" HTTP header suggest

### ISSUE THREAD

**Issue by ho4ho** [owncloud/core#38236]
Suggest by ownCloud:

> The "X-XSS-Protection" HTTP header is not configured to equal to "1; mode=block". This is a potential security or privacy risk and we recommend adjusting this setting.
https://github.com/owncloud/core/blob/a539f3f8e5f5cfff42005163e76bb2715980e747/core/js/tests/specs/setupchecksSpec.js#L419
https://github.com/owncloud/core/blob/a539f3f8e5f5cfff42005163e76bb2715980e747/.htaccess#L20-L21

but read by https://github.com/metabase/metabase/issues/11444

> From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection):
>
>> - Chrome has an "[Intent to Deprecate and Remove the XSS Auditor](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/TuYw-EZhO9g/blGViehIAwAJ)"
>> - Firefox have not, and [will not implement X-XSS-Protection](https://bugzilla.mozilla.org/show_bug.cgi?id=528661)
>> - Edge have [retired their XSS filter](https://blogs.windows.com/windowsexperience/2018/07/25/announcing-windows-10-insider-preview-build-17723-and-build-18204/)
>>
>> This means that if you do not need to support legacy browsers, it is recommended that you use Content-Security-Policy without allowing unsafe-inline scripts instead.

**Comment by ho4ho** [comment]
Also https://github.com/OWASP/CheatSheetSeries/issues/376#issuecomment-602663932:

> I've been studying this issue for a while and it's *dangerous* to set this header. It makes sites that are
not vulnerable to XSS, vulnerable.
> ...
> Developers need to either remove the header or set it to zero, I think the debate is over. There is NO good reason to set this header to blocking mode.

**Comment by mmattel** [comment]
Reading this, what is your suggestion to be made?

**Comment by ho4ho** [comment]
Suggest already above https://github.com/owncloud/core/issues/38236#issuecomment-748451720:

> Also https://github.com/OWASP/CheatSheetSeries/issues/376#issuecomment-602663932:
>
> > I've been studying this issue for a while and it's *dangerous* to set this header. It makes sites that are not vulnerable to XSS, vulnerable.
> > ...
> > Developers need to either remove the header or set it to zero, I think the debate is over. There is NO good reason to set this header to blocking mode.

Not nothing which better :-/

**Comment by mmattel** [comment]
Make a PR...

**Comment by ho4ho** [comment]
Sorry, me not good knowledge writing code so can't do PR :frowning_face:

**Comment by ho4ho** [comment]
> Sorry, me not good knowledge writing code so can't do PR :frowning_face:

Didn't think was easy like this: #38305

**Comment by ho4ho** [comment]
Also seen suggest remove vs. "0" by https://github.com/helmetjs/helmet/issues/230#issuecomment-614106165:

> The recommendation as a security community is to have a default value of 0 so that browsers don't set their own defaults.
