### ISSUE TITLE
Ubuntu 18.04 update to 20.04 [ownCloud 10.0.10] 

### ISSUE THREAD

**Issue by hannesa2** [owncloud/core#38253]
I updated Ubuntu 18.04 to 20.04 but I run into a trap and ownCloud sucks.

With `sudo -u www-data php occ check -vvv` I see

```
This version of ownCloud is not compatible with PHP 7.3
You are currently running PHP 7.4.3
```

I guess, I've to update ownCloud. What's the best way to update with less source of problems ?
How does it works with db update ?

Btw, my fear is growing when I see this 
<img width="121" alt="image" src="https://user-images.githubusercontent.com/3314607/103296120-b8bad800-49f5-11eb-85fa-9df5f72cd5a0.png">

**Comment by phil-davis** [comment]
Install PHP 7.3 on Ubuntu 20.04 and I expect that ownCloud 10.0.10 will run.
Then upgrade ownCloud to the latest version 10.6.0
Then switch back to PHP 7.4 on Ubuntu 20.04.

Alternatively, if you still have the Ubuntu 18.04 system with PHP 7.3 (or 7.2), upgrade ownCloud on that to 10.6.0. Then upgrade to Ubuntu 20.04 (which gives you PHP 7.4 by default)

**Comment by hannesa2** [comment]
I will document my nightmare, maybe someone read it, and can benefit from it

Ok, I installed `7.2` (`7.3` was too modern too)

```
sudo apt-get purge 'php*'
sudo apt install software-properties-commonsudo add-apt-repository ppa:ondrej/php
sudo add-apt-repository ppa:ondrej/php
sudo apt update
sudo apt install -y php7.2
php -v
```

Then I was forced to update my Postgres database to 12

```
sudo systemctl stop postgres
sudo apt-get install -y postgresql-12 postgresql-server-dev-12 postgresql-contrib-12 postgresql-client-12 libpq-dev postgresql-12-hypopg
sudo pg_dropcluster 12 main --stop
sudo pg_upgradecluster 10 main
sudo pg_dropcluster 10 main --stop
```

To be able to connect to Postgres from PHP

`sudo apt-get install php7.2-pdo-pgsql`

Now I run with `sudo -u www-data php occ maintenance:mode --on` into 

> An unhandled exception has been thrown:
> Error: Call to undefined function simplexml_load_file() in /srv/www/vhosts/mxdocs/owncloud/lib/private/App/InfoParser.php:41
> Stack trace:
> #0 /srv/www/vhosts/mxdocs/owncloud/lib/private/legacy/app.php(645): OC\App\InfoParser->parse('/srv/www/vhosts...')
> #1 /srv/www/vhosts/mxdocs/owncloud/lib/private/legacy/app.php(618): OC_App::getAppInfo('/srv/www/vhosts...', true)
> #2 /srv/www/vhosts/mxdocs/owncloud/lib/private/App/AppManager.php(630): OC_App::getAppVersionByPath('/srv/www/vhosts...')
> #3 /srv/www/vhosts/mxdocs/owncloud/lib/private/App/AppManager.php(579): OC\App\AppManager->getAppVersionByPath('/srv/www/vhosts...')
> #4 /srv/www/vhosts/mxdocs/owncloud/lib/private/App/AppManager.php(522): OC\App\AppManager->findAppInDirectories('files')
> #5 /srv/www/vhosts/mxdocs/owncloud/lib/private/legacy/app.php(570): OC\App\AppManager->getAppPath('files')
> #6 /srv/www/vhosts/mxdocs/owncloud/lib/private/legacy/app.php(117): OC_App::getAppPath('files')
> #7 /srv/www/vhosts/mxdocs/owncloud/lib/base.php(577): OC_App::loadApps(Array)
> #8 /srv/www/vhosts/mxdocs/owncloud/lib/base.php(994): OC::init()
> #9 /srv/www/vhosts/mxdocs/owncloud/console.php(64): require_once('/srv/www/vhosts...')
> #10 /srv/www/vhosts/mxdocs/owncloud/occ(11): require_once('/srv/www/vhosts...')

**Comment by hannesa2** [comment]
Does someone knows how to get rid of it ?

**Comment by hannesa2** [comment]
To solve it, you need install some additional php 7.2 extension

```
sudo apt-get install php7.2-{bcmath,bz2,intl,gd,mbstring,mysql,zip,fpm} -y
sudo apt-get install php7.2-curl
```

Now you can disable all apps, first list

`sudo -u www-data php occ app:list`

> ownCloud is in maintenance mode - no app have been loaded
> 
> Enabled:
>   -- activity: 2.4.0
>   -- calendar: 1.6.0
>   -- comments: 0.3.0
>   -- configreport: 0.1.1
>   -- contacts: 1.5.4
>   -- dav: 0.4.0
>   -- federatedfilesharing: 0.3.1
>   -- federation: 0.1.0
>   -- files: 1.5.1
>   -- files_external: 0.7.1
>   -- files_pdfviewer: 0.9.0
>   -- files_sharing: 0.11.0
>   -- files_texteditor: 2.2.1
>   -- files_trashbin: 0.9.1
>   -- files_versions: 1.3.0
>   -- files_videoplayer: 0.9.8
>   -- firstrunwizard: 1.1
>   -- gallery: 16.1.0
>   -- market: 0.2.5
>   -- notifications: 0.3.5
>   -- provisioning_api: 0.5.0
>   -- systemtags: 0.3.0
>   -- tasks: 0.9.6
>   -- templateeditor: 0.3.1
>   -- updatenotification: 0.2.1
> Disabled:
>   -- encryption
>   -- external
>   -- user_external
> 

You can disable most of them with on command 

`sudo -u www-data php occ app:list | grep - | cut -d'-' -f2 | cut -d':' -f1 | xargs -n 1 sudo -u www-data php occ app:disable`

But I was not able to disable all, there are still some remaining

```
Enabled:
  - dav: 0.4.0
  - federatedfilesharing: 0.3.1
  - files: 1.5.1
  - files_external: 0.7.1
Disabled:
  - activity
  - calendar
  - ...
```

**Comment by hannesa2** [comment]
When you are done with normal update https://doc.owncloud.com/server/admin_manual/maintenance/manual_upgrade.html

activate app(s)

`sudo -u www-data php occ app:list | grep - | cut -d'-' -f2 | cut -d':' -f1 | xargs -n 1 sudo -u www-data php occ app:enable`

and switch back to previous PHP `7.4`

```
sudo apt-get purge 'php*'
sudo rm /etc/apt/sources.list.d/ondrej-ubuntu-php-focal.list
sudo apt update
sudo apt install -y php
php -v
sudo apt-get install php-{bcmath,bz2,intl,xml,pdo-pgsql,curl,gd,mbstring,mysql,zip,fpm}
```
