### ISSUE TITLE
Enterprise apps ?

### ISSUE THREAD

**Issue by hannesa2** [owncloud/core#38256]
I upgraded from 10.0.4 to 10.5 and run into this dialog 

![image](https://user-images.githubusercontent.com/3314607/103312640-f7fd1f00-4a1d-11eb-96b4-406560248b38.png)

How can I figure out, which app(s) are these ?

**Comment by micbar** [comment]
@hannesa2 These are the enterprise apps from ownCloud publisher

https://marketplace.owncloud.com/bundles/enterprise_apps
https://marketplace.owncloud.com/apps/files_lifecycle
