### ISSUE TITLE
Replace patchwork/utf8

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#38276]
PR #38275 bumps to the latest release of `patchwork/utf8` https://github.com/tchwork/utf8/releases/tag/v1.3.3

https://packagist.org/packages/patchwork/utf8

This is the last release. "This package is abandoned and no longer maintained. The author suggests using the symfony/polyfill-mbstring or symfony/string package instead."

Investigate where `patchwork/utf8` is actually used and sort out how to replace with something else.

**Comment by phil-davis** [comment]
@micbar add to a project somewhere?

**Comment by micbar** [comment]
done

**Comment by JanAckermann** [comment]
https://packagist.org/?query=utf8

**Comment by JanAckermann** [comment]
@mrow4a or @JammingBen  can you give me a hint on this,
IHMO this lib gets only used to overcome a missing intl extension. 

I don't find any suitable replacement.
But I guess, https://github.com/symfony/intl would to the trick here.

**Comment by JammingBen** [comment]
> IHMO this lib gets only used to overcome a missing intl extension.

Would second that after a quick look into this.

Not directly related to this, but it would be really nice to have a proper error in case the intl extension is missing. I remember having this rather cryptic error when I first installed OC 10: `Cannot redeclare normalizer_normalize()`. I also stumbled upon a recent issue regarding this: https://github.com/owncloud/core/issues/38248

**Comment by VicDeo** [comment]
I second that missing `intl` exception produces a crash on master:
```
[Mon Jan 11 17:29:13.425393 2021] [php7:notice] [pid 27223] [client ::1:54798] PHP Fatal error:  Cannot redeclare normalizer_is_normalized() (previously declared in /home/deo/public_html/oc-tmp/lib/composer/symfony/polyfill-intl-normalizer/bootstrap.php:15) in /home/deo/public_html/oc-tmp/lib/composer/patchwork/utf8/src/Patchwork/Utf8/Bootup/intl.php on line 20
[Mon Jan 11 17:29:13.425436 2021] [php7:notice] [pid 27223] [client ::1:54798] PHP Stack trace:
[Mon Jan 11 17:29:13.425447 2021] [php7:notice] [pid 27223] [client ::1:54798] PHP   1. {main}() /home/deo/public_html/oc-tmp/index.php:0
[Mon Jan 11 17:29:13.425456 2021] [php7:notice] [pid 27223] [client ::1:54798] PHP   2. require_once() /home/deo/public_html/oc-tmp/index.php:53
[Mon Jan 11 17:29:13.425464 2021] [php7:notice] [pid 27223] [client ::1:54798] PHP   3. OC::init() /home/deo/public_html/oc-tmp/lib/base.php:1060
[Mon Jan 11 17:29:13.425473 2021] [php7:notice] [pid 27223] [client ::1:54798] PHP   4. Patchwork\\Utf8\\Bootup::initIntl() /home/deo/public_html/oc-tmp/lib/base.php:569
```

**Comment by JanAckermann** [comment]
@VicDeo right, intl is a required extension, the Patchwork/Utf8 package will be removed soon, due not needed and EOL
