### ISSUE TITLE
Subadmins cannot add users to groups they manage

### ISSUE THREAD

**Issue by rpocklin** [owncloud/core#38279]
### Background
I have read the background on this topic, through the Github repo issues and PRs and this seems to be a point of conjecture about how subadmins and groups work.  At a high-level, we want to be able to have subadmins create and manage groups in a dynamic fashion (creating groups, adding and removing users to these groups by the subadmin, or deleting groups).  In our system, users do not have any files in their own personal space, and we do not support impersonation for security reasons.  I am not sure how custom groups work internally but cannot see them appear as normal groups via the **owncloud-sdk**.

There appear to be business rules in place so that users created by a subadmin, implicitly get added to the group(s) the creator is a subadmin of.  They can be added and removed to groups (at least in the OC10 UI) freely, but cannot be detached from every group the subadmin is a subadmin of.

Further reading here:
https://github.com/owncloud/core/issues/31016
https://github.com/owncloud/core/issues/12349
https://github.com/owncloud/core/pull/31337

### Steps to reproduce
1.  From a default OC 10 instance, login as **admin** and a user (x), add a group (y) and make user (x) a subadmin of group (y).
2.  In the OC10 PHP UI, login as user (x) create a new user (z) then add user (z) as a member of group (y) - **successful**.
3.  Attempt the same as user (x) calling the **owncloud-sdk** method eg `client.users.addToGroup(z, y)` which fails with a 401 Unauthorised.

This is inconsistent behaviour.  Subadmins are currently (consistently) allowed to remove users from their groups, but not add them.  This means they effectively cannot 'manage' the group, which is the purpose of being a subadmin of a group.  If a subadmin accidently removed a user from a group, they could not re-add.

### Expected behaviour
Correct behaviour should be to allow subadministrators to add users to groups they are a subadmin of.  AARNet needs this feature to properly implement group management policies for delegation of group management.

### Actual behaviour
Fails with a 401 Unauthorised.

## Related Issues
This relates to an old issue and PR that was merged here: https://github.com/owncloud/core/pull/25788 however it seems @IljaN made a commit on 15 May 2018 that broke this feature (see https://github.com/owncloud/core/commit/792728ad9ce59f48009677129048ab81bcfc92cd#diff-5a8fe7b8beda1a977aa1886d1b2aa92f91ab686864c00f58fe9eed947044a054) and this has left the system in an inconsistent state.

_Subadmins need to be able to add users to groups they are subadmins of._

### Server configuration
**ownCloud version:** ownCloud 10.5.0

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
Docker image

No other settings have any relationship to this raised issue, the issue is in the code for the Provisioning API.

**Comment by phil-davis** [comment]
The challenge here is that there would need to be the possibility for 2 types of sub-admins:

1) Current subadmin:
a) can change the password and other attributes of users in "their" group(s)
b) can delete users in "their" group(s)
c) can remove users from "their" group(s) (in which case they lose "control" of that user)

2) Extra-style of subadmin (a group-membership-admin):
a) can add users to "their" group(s)
b) can remove users from "their" group(s)

The security problem comes if we add (2a) to the things that (1) can do. In that case any sub-admin can:
- add the CEO, HR Manager or any user to "their" group
- change the password of the user
- login as that user
- have access to all files that that user has access to
- change files writeable by that user (for example edit Board Minutes, edit personnel documents...
- then they can delete the user, if they like

So that, in effect, makes any subadmin almost a full admin, and they can certainly gain access to all data stored in the system.

If you allow a single person to both be able to add members to group X and to change the password of members of group X then that person has full access to all data, and needs to be fully-trusted.

**Comment by mrow4a** [comment]
@phil-davis I think this is bug with the owncloud-sdk, as the required feature works in web ui. I will have a look

**Comment by mrow4a** [comment]
there is PR in review pending https://github.com/owncloud/core/pull/38280

**Comment by phil-davis** [comment]
Yes, the PR addresses an inconsistency in the existing API. The webUI uses some "private" API call. The "public" Provisioning API call needs fixing. For that PR, we just need to make sure that no "bonus" loophole is accidentally opened for users that are not a sub-admin.

But the top post of this issue talks about "At a high-level, we want to be able to have subadmins create and manage groups in a dynamic fashion (creating groups, adding and removing users to these groups by the subadmin, or deleting groups)" That is a different set of actions to what the "subadmin role" currently does in oC10. IMO that needs discussion in this issue about what sort of "other subadmin role" is useful/required/needed.

**Comment by mrow4a** [comment]
@phil-davis good points. Will have a look how the private API call is exactly implemented so we do not open any loophole. 

The other high-level topic, I agree, needs design discussion. It is not simple bugfix.

**Comment by rpocklin** [comment]
@mrow4a Yep as I learn more about the way subadmins have been implemented (esp. with @phil-davis's explanation) I agree it's probably not a simple bugfix.

The simplest change I can think of that would not allow for the subadmin to become basically a `full admin` would be to only allow a subadmin (x) to add a user(z) to a new group (y) if that subadmin and user already share a group that that subadmin manages.  This is also consistent with the existing business rules for subadmins managing users and you are not giving the subadmin any control they don't already have (in essence) and would mitigate the scenario @phil-davis mentions.

**Comment by phil-davis** [comment]
> The simplest change I can think of that would not allow for the subadmin to become basically a full admin would be to only allow a subadmin (x) to add a user (z) to a new group (y) if that subadmin and user already share a group that that subadmin manages.

The new group (y) would have to also be a group that the subadmin (x) already manages - probably you meant that.

For example, subadmin (x) is subadmin for groups (y1) and (y2). User (z) is already a member of group (y1). So subadmin (x) is allowed to add user (z) to group (y2).

**Comment by rpocklin** [comment]
@phil-davis yep that's right.

Here's a commit which would achieve that (I believe): https://github.com/rpocklin/core/commit/822c4cef22f6c578d333c0cdb607f948064f6470

Curious to know your thoughts on it.

**Comment by mrow4a** [comment]
@rpocklin @phil-davis This is the function that gets called there https://github.com/owncloud/core/blob/master/settings/Controller/UsersController.php#L477 in UI. And this is the validation logic that is run https://github.com/owncloud/core/blob/master/settings/Controller/UsersController.php#L407-L433 . 

In UI, basically when you specify groups that the users should be added to, it just checks https://github.com/owncloud/core/blob/master/settings/Controller/UsersController.php#L409-L420 if user that attempts to add another user, is subadmin of that group.

**Comment by rpocklin** [comment]
Thanks for pointing that out.

I actually think the **owncloud-sdk** reflects the intended functionality from Owncloud, based on the history of the discussions I've referenced at the top of this issue, but the OC10 PHP UI is not in sync with this.

Please let me know if you would consider accepting a PR for https://github.com/rpocklin/core/commit/8a81469a660b799615bd3802fa06132ed65ed26e (with a matching change in https://github.com/owncloud/core/blob/master/settings/Controller/UsersController.php) as this is what we require long-term.

**Comment by mrow4a** [comment]
@rpocklin @phil-davis lets summarize:
1. current OC10 User Management UI has a bug that allows subadmin of a group to add arbitrary member to the group he is subadmin of. This according to @rpocklin and @phil-davis is a bug -> good explanation here https://github.com/owncloud/core/issues/38279#issuecomment-757685626 .
2. @rpocklin suggested a fix https://github.com/owncloud/core/issues/38279#issuecomment-759120827 , that should be backported to OC10 UI. This ensures using https://github.com/owncloud/core/blob/master/lib/private/SubAdmin.php#L249-L269 that subadmin can only add to the group users that are part of the groups he himself is member of. @pmaier1 can you please "bless" this and I merge/implement the fixes?

**Comment by micbar** [comment]
@mrow4a @rpocklin I agree with this. From PO perspective fine.

I am not sure though about the usecase at some other instances.

**Comment by micbar** [comment]
@pmaier1 @hodyroff Can you approve?

**Comment by mrow4a** [comment]
Ok some more input. There is NO ISSUE in current OC10 UI. In UI yes, SUBADMIN can CREATE user, and while doing it he can ADD TO THE GROUP. This is not possible in Provisioning API, because while creating you cannot immedietally at to "your group". 

If we even consider accepting this feature request, subadmin should only be able to add to groups he himself is member of, but this needs to be confirmed. This however needs consideration on whether provisioning API should be user here, and e.g. to use custom groups.

**Comment by mrow4a** [comment]
@rpocklin did you investigate using https://github.com/owncloud/customgroups for your usecase, this seems to satisfy your requirements.

**Comment by mrow4a** [comment]
@hodyroff @micbar **theoretically** our OC10 UserSettings **private API** allows to do what @rpocklin requires, with strict restriction for https://github.com/owncloud/core/issues/38279#issuecomment-758369940 already. Code is in https://github.com/owncloud/core/blob/master/settings/ajax/togglegroups.php#L49-L55 . What @phil-davis explained is exactly implemented as part of that call. 

So we might want to align both OC10 UserSettings API with OC10 Provisioning API to do the same thing.. 

The **theoretical** OC10 UI API to add ANY user to the group managed by subadmin, with restriction to subadmin groups only:
                                                                                                                                  
```
curl 'http://localhost:8000/index.php/settings/ajax/togglegroups.php' \
  -H 'Connection: keep-alive' \
  -H 'Accept: */*' \
  -H 'requesttoken: redacted' \
  -H 'X-Requested-With: XMLHttpRequest' \
  -H 'Accept-Language: en' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36' \
  -H 'OCS-APIREQUEST: true' \
  -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
  -H 'Origin: http://localhost:8000' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Cookie: redacted' \
  --data-raw 'username=test1&group=test2'
```

with result 

```
{"data":{"username":"test1","action":"add","groupname":"test2"},"status":"success"}
```

Still, probably using Custom Groups could be better idea @rpocklin ?

**Comment by rpocklin** [comment]
I have looked at custom groups briefly and this is my understanding:

They provide, via the OC10 UI only, a way for users to manage groups, however:
1) This group design does not allow adding, removing or fetching of these groups via the **owncloud-sdk** API; and
2) This group does not support the concept of a subadmin which would let subadmins create users in Owncloud under the groups they manage.

I am curious how custom groups are implemented as I'm a little confused why you would need them, along with the Groups implementation already existing.  I'll review and reply to the different options between how the OC10 UI and **owncloud-sdk** separately.

**Comment by mrow4a** [comment]
@rpocklin 
- if you really want to push for equalizing provisioning API (https://github.com/owncloud/core/blob/master/apps/provisioning_api/lib/Users.php#L487-L494) with web UI (https://github.com/owncloud/core/blob/master/settings/ajax/togglegroups.php#L39-L55) , to speed up you might need to adjust your PR as is wrong and add unit tests. Please note in Users.php, that subadmin is `$user->getUID()`, and user to add is `$parameters['userid']`.
- I agree custom groups do not expose an API to the clients
- customgroups documentation is here https://doc.owncloud.org/server/10.6/user_manual/files/webgui/custom_groups.html

**Comment by rpocklin** [comment]
> Ok some more input. There is NO ISSUE in current OC10 UI. In UI yes, SUBADMIN can CREATE user, and while doing it he can ADD TO THE GROUP. This is not possible in Provisioning API, because while creating you cannot immedietally add to "your group".

I beg to differ - in the Provisioning API, as a subadmin, you *must* specify a group you manage when you call *createUser* otherwise that call will fail.

The OC10 UI is consistent with the **createUser** API call in the **owncloud-sdk**.

The difference I am raising is that, after creation, as a subadmin, for users who are members of groups you manage, you can add and remove users to any groups you manage (save removing the final group).

This is not consistent with the **addUserToGroup** API call in the **owncloud-sdk**.

**Comment by mrow4a** [comment]
@rpocklin ok, I see it now. Would extending addUserToGroup API and align with https://github.com/owncloud/core/blob/master/settings/ajax/togglegroups.php#L39-L55 solve it?

**Comment by rpocklin** [comment]
@mrow4a sorry for the late reply, been busy with CS3 Conference and other things - yes that is correct that would solve it.  I made an example commit [here](https://github.com/rpocklin/core/commit/8a81469a660b799615bd3802fa06132ed65ed26e) but would appreciate it if you could lead this change as you have a deeper knowledge of the codebase.

**Comment by mrow4a** [comment]
@rpocklin currently handling just misses handling in https://github.com/owncloud/core/issues/38279#issuecomment-766657834 . The commot you prepared is not complete

**Comment by micbar** [comment]
@mrow4a @rpocklin Great that we have alignment.

Move on please, and don't forget to adapt the dev docs 😄

**Comment by rpocklin** [comment]
> @rpocklin currently handling just misses handling in [#38279 (comment)](https://github.com/owncloud/core/issues/38279#issuecomment-766657834) . The commit you prepared is not complete. Was it tested?

No it was just to demonstrate the POV, I will try to prepare a new PR to raise based https://github.com/owncloud/core/blob/master/settings/ajax/togglegroups.php#L39-L55

**Comment by micbar** [comment]
@rpocklin Please move on, if you need help please just ping @mrow4a  and @phil-davis for the tests.

**Comment by rpocklin** [comment]
Just updating this thread, still have plans to implement as agreed similar to https://github.com/owncloud/core/blob/master/settings/ajax/togglegroups.php#L39-L55

**Comment by rpocklin** [comment]
I'm picking this up again :)
