### ISSUE TITLE
Inconsistent authorization to see user and group names

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#38332]
### Steps to reproduce
1. As admin, list the groups in the system - good:
```
curl "http://172.17.0.1:8080/ocs/v1.php/cloud/groups" -X GET --user "admin:admin"
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <groups>
   <element>admin</element>
   <element>t123</element>
  </groups>
 </data>
</ocs>
```
2. As a subadmin, list the groups in the system - good:
(I made `boss` a subadmin of group `t123`)
```
$ curl "http://172.17.0.1:8080/ocs/v1.php/cloud/groups" -X GET --user "boss:boss"
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message/>
 </meta>
 <data>
  <groups>
   <element>admin</element>
   <element>t123</element>
  </groups>
 </data>
</ocs>
```

3. as an ordinary user, try to list the groups in the system:
```
curl "http://172.17.0.1:8080/ocs/v1.php/cloud/groups" -X GET --user "new:new"
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message>Unauthorised</message>
 </meta>
 <data/>
</ocs>
```

But as an ordinary user, get information about the users and groups that you can share with:
```
curl "http://172.17.0.1:8080/ocs/v1.php/apps/files_sharing/api/v1/sharees?itemType=folder" --user "new:new"
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data>
  <exact>
   <users>
    <element>
     <label>The admin</label>
     <value>
      <shareType>0</shareType>
      <shareWith>admin</shareWith>
     </value>
    </element>
    <element>
     <label>boss</label>
     <value>
      <shareType>0</shareType>
      <shareWith>boss</shareWith>
     </value>
    </element>
    <element>
     <label>ceo</label>
     <value>
      <shareType>0</shareType>
      <shareWith>ceo</shareWith>
     </value>
    </element>
    <element>
     <label>new</label>
     <value>
      <shareType>0</shareType>
      <shareWith>new</shareWith>
     </value>
    </element>
    <element>
     <label>someone</label>
     <value>
      <shareType>0</shareType>
      <shareWith>someone</shareWith>
     </value>
    </element>
   </users>
   <groups/>
   <remotes/>
  </exact>
  <users/>
  <groups>
   <element>
    <label>admin</label>
    <value>
     <shareType>1</shareType>
     <shareWith>admin</shareWith>
    </value>
   </element>
   <element>
    <label>t123</label>
    <value>
     <shareType>1</shareType>
     <shareWith>t123</shareWith>
    </value>
   </element>
  </groups>
  <remotes/>
 </data>
</ocs>
```

### Expected behaviour
Not sure - but IMO ordinary users should be able to find out the group names on the system, so they should be able to request to any of the API endpoints that provide that information.

### Actual behaviour
An ordinary user can find out all the user and group names by querying the `apps/files_sharing/api/v1/sharees` API endpoint, which seems reasonable. But they get "unauthorised" if they try to get the same data (list of group names) from the `cloud/groups` API endpoint. That seems inconsistent.

### Server configuration
Current core master.

**Comment by phil-davis** [comment]
And similar for users. The `apps/files_sharing/api/v1/sharees` API endpoint lets a user find out the other usernames on the system.

But `curl "http://172.17.0.1:8080/ocs/v1.php/cloud/users" -X GET --user "new:new"` gives:
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message>Unauthorised</message>
 </meta>
 <data/>
</ocs>
```

**Comment by phil-davis** [comment]
@micbar @pmaier1 what is the expected behaviour?

Should ordinary users be able to use the `ocs/v1.php/cloud/groups` and `ocs/v1.php/cloud/users` endpoints to list the groups and users in the system? Or not?

**Comment by JanAckermann** [comment]
@phil-davis I would not recommend opening the API endpoint  /ocs/v1.php/cloud/groups  for common users, why:
* If we open the /groups endpoint for common users we should also open the endpoint /groups/<groupid> for consistence 
* In the endpoint /groups/<groupid> **you can now see which user is in which group**

IHMO apps/files_sharing/api/v1/sharees should be viewed as a different API, which provides minimal information for sharing

**Comment by phil-davis** [comment]
Yes, agree. If we did open the `groups` endpoint then we would have to be careful to open just the "vanilla" list of groups, not the details of group members.

I mainly want to get agreement on the current behaviour - if it is OK then the new test scenarios that will cover this sort of stuff can be added to the "gold" test suite, and we expect oCIS to behave in the same way.

**Comment by JanAckermann** [comment]
>I mainly want to get agreement on the current behaviour 
Would vote for yes since `groups` is part of the Provisioning_API, common users should not be allowed to access
