### ISSUE TITLE
update failed

### ISSUE THREAD

**Issue by tczillay** [owncloud/core#38335]
### Steps to reproduce
1. started update in browser
2. update hanged
3. edited file config.php
4. reload owncloud in browser
5. pressed button Update
6. got errormessage:
7. Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Reparaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable templateeditor
Reparaturwarnung:For manually updating, see https://doc.owncloud.org/server/10.1/go.php?to=admin-marketplace-apps
OC\RepairException: Upgrade is not possible
8. Cannot login to owncloud anymore
9. 
### Expected behaviour
I want to get access to my data-

### Actual behaviour
Cannot login to owncloud anymore

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**
tried update to Aktualisierung auf 10.1.1  but failed
**Where did you install ownCloud from:**
goneo clickstart

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
cannot login

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocmod8l5qeZ5UrIATYuK',
  'passwordsalt' => '',
  'secret' => 'someLetters',
  'trusted_domains' => 
  array (
    0 => 'www.mydomain.de',
  ),
  'datadirectory' => '/web/1/000/021/851/44037/htdocs/owncloud/data',
  'overwrite.cli.url' => 'www.mydomain.de',
  'dbtype' => 'mysql',
  'version' => '10.1.1.1',
  'dbname' => dbname',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => dbuser',
  'dbpassword' => 'secret',
  'logtimezone' => 'UTC',
  'installed' => true,
  'updater.secret' => '$2y$10$e9HG9Yf5aRjcfMUAiDUxwOS4YFBzW2gb5Ql20.qqwqp51j6CCjMX.',
  'loglevel' => 2,
  'maintenance' => false,
);

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**
I remember only standard installation
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

### Client configuration
**Browser:**
Firefox 84.0.2 (64-Bit)

**Operating system:**
Ubuntu Mate 20.04
#### Web server error log
```

Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
where do I get this without login?```

**Comment by ho4ho** [comment]
> You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
> Please install or update the following apps manually or disable them with: occ app:disable templateeditor
> For manually updating, see https://doc.owncloud.org/server/10.1/go.php?to=admin-marketplace-apps

**Comment by tczillay** [comment]
I read this in the errormessage already, thanks.But I cannot reach the oc anymore.I already read the documents how to update manually but its not very easy to understand. I cant remember to have anything else installed than whats offered as easy installed by the goneo package is offered.Thx theoTheo Stern-------- Originalnachricht --------Betreff: Re: [owncloud/core] update failed (#38335)Von: ho4ho An: owncloud/core Cc: tczillay ,Author 

You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Please install or update the following apps manually or disable them with: occ app:disable templateeditor
For manually updating, see https://doc.owncloud.org/server/10.1/go.php?to=admin-marketplace-apps


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/owncloud/core/issues/38335#issuecomment-765885949",
"url": "https://github.com/owncloud/core/issues/38335#issuecomment-765885949",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ho4ho** [comment]
Thinking not bug by ownCloud, could help finding in https://central.owncloud.org/

**Comment by VicDeo** [comment]
we need to stress out that this is not a bug, but just an inconsistent state.
May be `You have incompatible or missing apps enabled that could not be found or updated via the marketplace` is not self-explanatory

**Comment by tczillay** [comment]
I haven't any app activated. It doesnt matter anyway, i deleted the whole shit.Thx.Theo Stern-------- Originalnachricht --------Betreff: Re: [owncloud/core] update failed (#38335)Von: Viktar Dubiniuk An: owncloud/core Cc: tczillay ,Author 
we need to stress out that this is not a bug, but just an inconsistent state.
May be You have incompatible or missing apps enabled that could not be found or updated via the marketplace is not self-explanatory

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/owncloud/core/issues/38335#issuecomment-766609609",
"url": "https://github.com/owncloud/core/issues/38335#issuecomment-766609609",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by VicDeo** [comment]
> i deleted the whole shit

Would you like me to answer using the same lexics? ;)
1. you have an app that is INCOMPATIBLE with the version you are going to migrate
2. you've been asked by OC to RTFM and just **disable the incompatible** app before to proceed with upgrade.

you chose not to read the docs at all (not before the upgrade and while doing it) and not to disable the app but to delete everything you have. That's fine. Good bye.

**Comment by tczillay** [comment]
And thats why i wrote to you. Oc never told me to deactivate any apps. Thats why i wrote the feedback to include some of this before the update. Okay?Thats all.You always told me that i have such apps or so, but i only had the simple first installation without any other configuration made by me.Thats what i tried to tell you.Theo Stern-------- Originalnachricht --------Betreff: Re: [owncloud/core] update failed (#38335)Von: Viktar Dubiniuk An: owncloud/core Cc: tczillay ,Author 

i deleted the whole shit

Would you like me to answer using the same lexics? ;)

you have an app that is INCOMPATIBLE with the version you are going to migrate
you've been asked by OC to RTFM and just disable the incompatible app before to proceed with upgrade.

you chose not to read the docs at all (not before the upgrade and while doing it) and not to disable the app but to delete everything you have. That's fine. Good bye.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/owncloud/core/issues/38335#issuecomment-766633853",
"url": "https://github.com/owncloud/core/issues/38335#issuecomment-766633853",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
