### ISSUE TITLE
Trying to access array offset on value of type bool at

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#38373]
### Steps to reproduce
1. I have no idea why this error popped up

### Expected behaviour
No php error message

### Actual behaviour
`Trying to access array offset on value of type bool at \/var\/www\/owncloud\/apps\/files_versions\/lib\/Storage.php#579`

This is the erroring line is:
`$nextVersion = $firstVersion['version'] - $step;`

### Server configuration
**Operating system**: Ubuntu 20.04

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.4

**ownCloud version:** 10.6 stable

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tar

**Signing status (ownCloud 9.0 and above):**

```
all green
```

**The content of config/config.php:**

[config_report_20210203.zip](https://github.com/owncloud/core/files/5916971/config_report_20210203.zip)

**List of activated apps:**

```
Enabled:
  - activity: 2.6.0
  - audioplayer: 2.8.4
  - comments: 0.3.0
  - configreport: 0.2.0
  - dav: 0.6.0
  - federatedfilesharing: 0.5.0
  - federation: 0.1.0
  - files: 1.5.2
  - files_clipboard: 1.0.3
  - files_external: 0.7.1
  - files_external_dropbox: 1.2.0
  - files_external_ftp: 0.2.1
  - files_mediaviewer: 1.0.4
  - files_pdfviewer: 0.11.2
  - files_sharing: 0.14.0
  - files_texteditor: 2.3.0
  - files_trashbin: 0.9.1
  - files_versions: 1.3.0
  - firstrunwizard: 1.2.0
  - market: 0.6.0
  - notifications: 0.5.2
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.4.0
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - guests
  - user_external
```

**Are you using external storage, if yes which one:** local/smb/gd

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** Opera

**Operating system:** W10x64Pro

#### Web server error log
```
No relevant entry
```

#### ownCloud log (data/owncloud.log)
```
Trying to access array offset on value of type bool at \/var\/www\/owncloud\/apps\/files_versions\/lib\/Storage.php#579
```

**Comment by JammingBen** [comment]
@mmattel see https://github.com/owncloud/core/pull/38390
