### ISSUE TITLE
Review API scenario outline examples

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#38371]
The API acceptance tests are taking longer-and-longer as we add more coverage. In some places we have `Scenario Outline` with a significant list in the `Examples` table. For every example, the users, groups, files... have to all be created, the example is run, the users, groups, files are all deleted, then they are created again... This is, of course, the theoretically correct way to do this stuff.

But our job is not to keep every data center in Europe warm ;)

Review the current API Scenario Outlines for scenarios that "just" test a list of edge-cases (for example, using various unusual file or folder names, using various unusual group names...) See if those can be converted into single scenarios that have steps that do this sort of thing:
```
Given user "Alice" has uploaded the following files:

When user "Alice" deletes the following files:

Given the following groups have been created:

When the administrator deletes the following groups:

Then the following files should exist for user "Alice":
```

with a table in each step.

Some of these steps already exist.

When writing such steps, make sure that when looping through the items in the table, if something goes wrong, then try to remember all the things that went wrong and report them in the exception message - so that someone looking at the test failure can know which files do not exist, which groups did not get deleted...

**Comment by phil-davis** [comment]
Also see comment https://github.com/owncloud/core/pull/38366#pullrequestreview-580953203 for some discussion.

@individual-it @dpakach what do you think? Is this worth doing?

**Comment by individual-it** [comment]
or split the example tables and run some of the tests only on nightly jobs, with the current version on Behat we can do that

**Comment by HariBhandari07** [comment]
All edge case scenario outlines have been refactored so closing the issue.
