### ISSUE TITLE
Sharee endpoint gives response including the user who requested the recipients list

### ISSUE THREAD

**Issue by jasson99** [owncloud/core#38397]
### Steps to reproduce
1. Create user `test123
2. Create user `testABC`
3. Request to get share recipient as user `test123` as follows:
```curl -u test123:test123 -X GET "http://localhost/oc/ocs/v2.php/apps/files_sharing/api/v1/sharees?search=test&itemType=folder&page=1&perPage=200&format=json"```

Then the response is as follows:

```{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK","totalitems":"","itemsperpage":""},"data":{"exact":{"users":[],"groups":[],"remotes":[]},"users":[{"label":"test123","value":{"shareType":0,"shareWith":"test123"}},{"label":"testABC","value":{"shareType":0,"shareWith":"testABC"}}],"groups":[],"remotes":[]}}}```
### Expected behaviour
The response should not include the user requesting the share recipients.

### Actual behaviour
The requesting user is included as the share recipient user.

**Comment by phil-davis** [comment]
what should be the response?
The user `test123` cannot share to themselves, so probably the server should not include them in the response.

There might be a similar thing happen with display name matches. For example, if my display name is set to "Phil Davis" and I ask for the potential sharees starting with `phil` then I should not get myself back in the list. I should get other "Phil"s in the system - "Phil Jones", "Phil Smith" and if there is another user with display name "Phil Davis" then I should get that user in the list.
