### ISSUE TITLE
Spelling mistake in french authentification in Admin panel

### ISSUE THREAD

**Issue by Philippe34** [owncloud/core#38398]
Hi,

I'd like to report a spelling mistake in french translation in admin 
![image](https://user-images.githubusercontent.com/12435553/107794732-13b34f00-6d58-11eb-9421-433d60b1688e.png)

"Authentification" is like in english : "Authentification de l'utilisateur" is right

Thanks

**Comment by phil-davis** [comment]
Translations are manged in Transifex. Please signup to Transifex and you can contribute translations there.
https://www.transifex.com/owncloud-org/owncloud/dashboard/

**Comment by Philippe34** [comment]
Thanks @phil-davis 
I did not known Owncloud translations were from Transifex and I wish to contribute in the future.
When I modify a translation, will the changes appear in the next version ?

**Comment by phil-davis** [comment]
> When I modify a translation, will the changes appear in the next version ?

Yes, changes from Transifex are imported in a daily job. They end up in the next release.

You are most welcome to contribute translations for whatever languages you know!
