### ISSUE TITLE
[QA] guest user email is shown as normal user, when used for the second time

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38422]
Seen with owncloud server 10.6.0 and guests app 0.9.0 

* Enter a yet unknown email address in the share dialog.
* A choice appears for "federated" or "guest". OK

![image](https://user-images.githubusercontent.com/1108546/108185028-23da7e00-710c-11eb-9608-645c00c8a1ce.png)

* Click the guest. ownCloud creates a user entry for the guest. 
* Can be verified in Admin Users or e.g. metrics overview:
![image](https://user-images.githubusercontent.com/1108546/108185580-bf6bee80-710c-11eb-97b9-b5054c465e09.png)

* Enter the same email address again for another share. The choice now is "user" and "Federated". BAD
![image](https://user-images.githubusercontent.com/1108546/108185893-12de3c80-710d-11eb-8779-680f67cd447f.png)

Expected behaviour: guest users are always flagged as "guest".

**Comment by JanAckermann** [comment]
> Expected behaviour: guest users are always flagged as "guest".
correct!

**Comment by jnweiger** [comment]
Confirmed fixed in 10.7.0RC1
