### ISSUE TITLE
Favicon since OC 10.6

### ISSUE THREAD

**Issue by eripslionoac** [owncloud/core#38469]
Hello,
Since OC 10.6, the favicon from custom theme is loaded on login screen (/apps-external/theme-example-master/core/img/favicon.ico), but when connected it's /core/img/favicon.ico). This problem is not present in OC 10.5.

**Comment by ho4ho** [comment]
Looked like known fixed soon https://doc.owncloud.org/server/10.6/admin_manual/release_notes.html#known-issues:

> There is an issue with themes which causes some themed icons and logos not to be replaced (the original icon/image will be displayed). The issue will be fixed in the next release. #38246

Suggest: closing

**Comment by ChrisEdS** [comment]
We fixed that in the next server release. Thanks for reporting.

You can patch your instance with small effort: https://central.owncloud.org/t/custom-logo-mail-gif-in-the-notification-email-sometimes-is-owncloud-logo/30842/3?u=cscherm
