### ISSUE TITLE
PostgreSQL setupDatabases prints wrong error

### ISSUE THREAD

**Issue by grischdian** [owncloud/core#38461]
### Steps to reproduce
1. Install PostgreSQL >= 10
- Set password_encryption = scram-sha-256 in postgresql.conf
- Create user with password
- Create DB with user as owner
- Configure pg_hba.conf to allow Connections from remote Host with scram-sha-256
2. Install ownCloud on RHEL 7.9 with php 7.3 from softwarecollection
3. Try to connect ownCloud to postgresql

### Expected behaviour
The Installation Wizard should be able to complete or show a correct Error Message.
The ownCloud Logfile should show a correct Error Message.
Connection is not working because php7.3 uses pgsql 9.2.24 and scram-sha-256 was introduced in pgsql 10

### Actual behaviour
An Error Message "PostgreSQL username and/or password not valid" is shown.
Additionally you find logs in owncloud.log (see below)

### Server configuration
**Operating system**: 
Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Web server:**
apache 2.4 from softwarecollection

**Database:**
PostgreSQL 10

**PHP version:**
7.3 from Softwarecollection

**ownCloud version:** (see ownCloud admin page)
10.6

**Updated from an older ownCloud or fresh install:**
fresh

**Where did you install ownCloud from:**
owncloud.com -> Downloaded tar.bz2

#### ownCloud log (data/owncloud.log)
```
{"reqId":"YD612nejNJOg-FUR1tJxJAAAAAU","level":2,"time":"2021-03-02T22:02:02+00:00","remoteAddr":"37.209.111.0","user":"--","app":"no app in context","method":"POST","url":"\/index.php","message":"Error occurred while checking PostgreSQL version, assuming >= 9"}
{"reqId":"YD612nejNJOg-FUR1tJxJAAAAAU","level":3,"time":"2021-03-02T22:02:02+00:00","remoteAddr":"37.209.111.0","user":"--","app":"no app in context","method":"POST","url":"\/index.php","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\DBALException\",\"Message\":\"Failed to connect to the database: An exception occurred in driver: SQLSTATE[08006] [7] FATAL:  no PostgreSQL user name specified in startup packet\",\"Code\":0,\"Trace\":\"#0 \\\/data\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(428): OC\\\\DB\\\\Connection->connect()\\n#1 \\\/data\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(388): Doctrine\\\\DBAL\\\\Connection->getDatabasePlatformVersion()\\n#2 \\\/data\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(330): Doctrine\\\\DBAL\\\\Connection->detectDatabasePlatform()\\n#3 \\\/data\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(695): Doctrine\\\\DBAL\\\\Connection->getDatabasePlatform()\\n#4 \\\/data\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php(144): Doctrine\\\\DBAL\\\\Connection->setTransactionIsolation(2)\\n#5 \\\/data\\\/owncloud\\\/lib\\\/composer\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DriverManager.php(194): OC\\\\DB\\\\Connection->__construct(Array, Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#6 \\\/data\\\/owncloud\\\/lib\\\/private\\\/DB\\\/ConnectionFactory.php(134): Doctrine\\\\DBAL\\\\DriverManager::getConnection(Array, Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#7 \\\/data\\\/owncloud\\\/lib\\\/private\\\/Server.php(536): OC\\\\DB\\\\ConnectionFactory->getConnection('pgsql', Array)\\n#8 \\\/data\\\/owncloud\\\/lib\\\/composer\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(118): OC\\\\Server->OC\\\\{closure}(*** sensitive parameters replaced ***)\\n#9 \\\/data\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(108): Pimple\\\\Container->offsetGet('DatabaseConnect...')\\n#10 \\\/data\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(86): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('DatabaseConnect...')\\n#11 \\\/data\\\/owncloud\\\/lib\\\/private\\\/Server.php(1239): OC\\\\ServerContainer->query('DatabaseConnect...')\\n#12 \\\/data\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/db.php(56): OC\\\\Server->getDatabaseConnection()\\n#13 \\\/data\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/db.php(133): OC_DB::prepare('SHOW SERVER_VER...', NULL, NULL)\\n#14 \\\/data\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(948): OC_DB::executeAudited(Array)\\n#15 \\\/data\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(928): OC_Util::checkDatabaseVersion()\\n#16 \\\/data\\\/owncloud\\\/lib\\\/base.php(603): OC_Util::checkServer(Object(OC\\\\AllConfig))\\n#17 \\\/data\\\/owncloud\\\/lib\\\/base.php(1060): OC::init()\\n#18 \\\/data\\\/owncloud\\\/index.php(53): require_once('\\\/data\\\/owncloud\\\/...')\\n#19 {main}\",\"File\":\"\\\/data\\\/owncloud\\\/lib\\\/private\\\/DB\\\/Connection.php\",\"Line\":62}"}
{"reqId":"YD612nejNJOg-FUR1tJxJAAAAAU","level":3,"time":"2021-03-02T22:02:02+00:00","remoteAddr":"37.209.111.0","user":"--","app":"PHP","method":"POST","url":"\/index.php","message":"Undefined index: dbconnectionstring at \/data\/owncloud\/lib\/private\/Setup\/AbstractDatabase.php#82"}
```
### Code
https://github.com/owncloud/core/blob/bd300dd3b819f1610da350c758726087daec95f8/lib/private/Setup/PostgreSQL.php#L45-L56
This pg_connect fails first (I think) but errors are supressed.
There should be more meaningful errors here. Username / Password invalid is not always correct.

Without `@\` the owncloud log showed
```
{"reqId":"YD65FjH-7KUvBlh92jFA1wAAAAM","level":3,"time":"2021-03-02T22:15:50+00:00","remoteAddr":"37.209.111.0","user":"--","app":"PHP","method":"POST","url":"\/index.php","message":"pg_connect(): Unable to connect to PostgreSQL server: SCRAM authentication requires libpq version 10 or above at \/data\/owncloud\/lib\/private\/Setup\/PostgreSQL.php#51"}
```

**Comment by JanAckermann** [comment]
@jvillafanez Any Idea, why we have this strange error handling?

**Comment by jvillafanez** [comment]
I don't know, but there are several problems we have to deal with:
* `pg_connect` only returns false and an php error message (which, by the way, it's undocumented). From php side, we don't know what has been the reason of the failure.
* I don't know if we can catch the php error with a try / catch block, trying to catch the throwable. This could be the best bet we have to try to do something with the connection error, but I'm not sure if it's going to work.
* I guess the `DatabaseSetupException` is intended to hold a message that will be shown to the admin in the web UI. While I think there are better solutions, the problem is that we can't translate a random error message, so I guess we have to provide a generic error message, and probably the "invalid password" is the most common error case.

From my point of view, there are several things to do here:
* Somehow distinguish what kind of error the `pg_connect` function is throwing (if possible)
* Write the error as such in the log file. Suppressing errors is a bad practice because of tickets like this.
* Provide an adequate error message in the web UI.
