### ISSUE TITLE
Translation for LDAP Persmission Manager is missing

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#38480]
oC version 10.6

Language setting is English

but

![image](https://user-images.githubusercontent.com/24212810/110408343-ac9e6700-8085-11eb-923b-f383f03e85ae.png)

Need translation for Berechtigungsmanager to Permissionmanager.

**Comment by phil-davis** [comment]
It is not a problem for me:
![Screenshot_2021-03-09 Settings - ownCloud](https://user-images.githubusercontent.com/1535615/110428737-e301d380-80d1-11eb-978a-945a72e75dba.png)

And the WND code looks like it has the words "Permission Manager"

**Comment by phil-davis** [comment]
That's strange that it showed Deutsch translation when British English has no translation. For me it keeps saying "Permission Manager" with British English.
