### ISSUE TITLE
[QA] Favorites or Edit on a PDF file

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38497]
Seen in 10.7 beta2

Click the 3 dots menu of a PDF File. A dropdown opens, containing an entry 'Favorite".
This does not set or clear favorites status. It simply opens the PDF in a viewer.

Compare with 10.6 (left) and 10.7 (right)
![image](https://user-images.githubusercontent.com/1108546/110828036-ee522c00-8296-11eb-81fb-722614dbaf9e.png)

In 10.6 Edit and Rename had the same icon. But it is unclear, what Edit should mean on a PDF file.
The Favorite function is normally accessed through a yellow star on the far left hand side. Inclusion in this menu is a duplicate. (If it was intended and would work)..

Expected behaviour: 
  * All entries should have icons, and distinct icons.
  * Function should match name.
  * A favorites function should not be duplicated here (if that was intended).

**Comment by ChrisEdS** [comment]
The action for `Favorite` is `view`

![image](https://user-images.githubusercontent.com/33026403/110828761-ab448880-8297-11eb-95ad-c61983d3e095.png)

**Comment by JanAckermann** [comment]
Not an owncloud core issue
https://github.com/owncloud/files_pdfviewer/pull/227

**Comment by jnweiger** [comment]
Confirmed fixed in files_pdfviewer 0.12.0 RC1 with server core 10.7.0 RC1

![image](https://user-images.githubusercontent.com/1108546/110925372-65cd9d00-8323-11eb-805c-cc59ba575602.png)
