### ISSUE TITLE
[QA] Tag implementation: UX improvement - Delete

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/core#38495]
### Delete

As a user, to delete a tag, I have to click on 'Rename' first. I can not delete the tag before I rename it which is confusing.

![image](https://user-images.githubusercontent.com/33026403/110822251-2b1b2480-8291-11eb-9b40-0b87eedc1a59.png)

#### Steps to reproduce
1. Create a tag
2. Try to delete the tag

#### Expected behaviour
1. As a user I can delete the tag directly in the menu

![image](https://user-images.githubusercontent.com/33026403/110820714-a4197c80-828f-11eb-8b37-6141554d9b34.png)

2. As a user I can delete the tag directly via the tag tag

![image](https://user-images.githubusercontent.com/33026403/110820920-dc20bf80-828f-11eb-8206-ce55194a68a5.png)

#### Current behaviour
As a user I have to click on `Rename` in order to see the `trashbin` to delete the tag

![image](https://user-images.githubusercontent.com/33026403/110821245-2ace5980-8290-11eb-8170-fb3c9915cf24.png)

**ownCloud version:** (see ownCloud admin page)
10.7.0 Beta2

**Comment by jnweiger** [comment]
#38498 implements the trashcan next to the pencil icon.

The [x] suggestion is not implemtned.
![image](https://user-images.githubusercontent.com/1108546/111166870-da613f80-85a0-11eb-96cd-a0549d98a13e.png)

OK.
