### ISSUE TITLE
API tests for case-sensitive tags

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#38500]
PR #38498 adjusted the webUI so that tags are properly displayed case-sensitive - tags `test` and `Test` are different and should display as separate tags in the UI.
![Screenshot_2021-03-12 Files - ownCloud](https://user-images.githubusercontent.com/1535615/110891784-d1f7d300-831a-11eb-91e1-e0311b1cbcae.png)

Tags with different case should also be separate in the API.

Add some API test scenarios that verify that tags with different case really are processed as different.

**Comment by individual-it** [comment]
@SwikritiT @phil-davis is this done?

**Comment by phil-davis** [comment]
PR #38503 added some webUI test scenarios for tags that are only different in their case. So this is covered for the display on the webUI. And #38512 covers direct use of the API.

Done - closing.
