### ISSUE TITLE
[QA] pdf_viewer does not translate 'close'

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38525]
Seen in server 10.7.0 RC1 with pdfviewser 0.12.0 RC1

Languange switching affects almost all the pdfviewer interface as expected due to #38181 
Except for the close button. It always says 'Close'

![image](https://user-images.githubusercontent.com/1108546/111254285-fdc5d200-8614-11eb-9d72-6418d3b1da3c.png)

**Comment by JanAckermann** [comment]
@micbar no transifex in this repo :/

**Comment by micbar** [comment]
ok @jnweiger @JanAckermann Nice finding.

Out of scope for 10.7 as this is not a regression and could be released separately with files_pdfviewer.

**Comment by ChrisEdS** [comment]
It's not only `Download`:

![image](https://user-images.githubusercontent.com/33026403/111685218-ef033900-8827-11eb-8cbf-4b9d8e1d428f.png)

**Comment by JanAckermann** [comment]
Will be done with https://github.com/owncloud/files_pdfviewer/pull/248
closing issue
