### ISSUE TITLE
[QA] server logging is defective when inside docker

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38535]
seen with
`docker run -ti -p 8080:8080 owncloud/server:10.7.0-rc1`

* log in as admin, go to setting general,
* change loglevel to Everything....
* the green autosave notice appears. OK

![image](https://user-images.githubusercontent.com/1108546/111459520-11f3f700-871b-11eb-8e03-9efce0bf0cd9.png)

* navigate back files view
* navigate to settings, genera
* scroll down to the log settings
* they are back to Warnings... BAD

![image](https://user-images.githubusercontent.com/1108546/111459816-7c0c9c00-871b-11eb-857a-ad3e0ce60424.png)

* the download option for the logfile is missing. BAD
* the logfile remains empty.

```
$ docker exec -ti 6826f3ccf35a occ log:owncloud
Log backend ownCloud: enabled
Log file: /mnt/data/files/owncloud.log
Rotate at: disabled

$ docker exec -ti 6826f3ccf35a ls -la /mnt/data/files/owncloud.log
-rw-r----- 1 www-data www-data 0 Mar 17 11:18 /mnt/data/files/owncloud.log

**Comment by jnweiger** [comment]
The docker framework spools some log messages on stdout, but this is mostly http logging only and log level cannot be changed.

**Comment by micbar** [comment]
The log level in Docker needs to be set in the ENV variable 

OWNCLOUD_LOG_LEVEL

The UI changes are not persisted in docker.

**Comment by micbar** [comment]
@pmaier1 IMO works as designed.

**Comment by jnweiger** [comment]
That is broken by design then. If the plan is to disable UI elements, then please gray them out or remove them. 
"not persisted" is an euphemism. It does not work at all.

**Comment by micbar** [comment]
no, it is not a two liner. It is the design. The UI tries to write a system config, which will be reverted on docker restart.

**Comment by jnweiger** [comment]
@micbar re-opening. I have a one-liner fix for the special case of the OWNCLOUD_LOGLEVEL on the docker side. Can you re-evaluate there please?

**Comment by cdamken** [comment]
The pull request from @jnweiger fix my problem.

**Comment by micbar** [comment]
see my comment in the issue.
