### ISSUE TITLE
[QA] Download link misaligned after using pdfviewer

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38547]
Seen with `docker run -ti -p 888:8080 owncloud/server:10.7.0-rc1`
and both Firefox 86 or google chrome 86 accessing `https://localhost:888`

* login as admin
* see the pdf file, click it open, the builtin files_pdfviewer starts
* close the pdfviewer (either using the white X at the right hand side, or browser back)
* select any file or folder at its icon
* as soon as the blue checkmark overlay appears on the icon, the columns headings change
* download is offered, but is offset far to the right (Delete should also be there, it is outside the screen). BAD.
* resize the browser window slighty, the headings snap back in place, so that download is above the sharing icons, and delete is at the far right.

![Screenshot from 2021-03-18 19-41-19](https://user-images.githubusercontent.com/1108546/111680874-f116c900-8822-11eb-9c93-36dda3bdb75a.png)
![Screenshot from 2021-03-18 19-42-53](https://user-images.githubusercontent.com/1108546/111680872-f07e3280-8822-11eb-8155-6fc2e3b762c1.png)
![Screenshot from 2021-03-18 19-43-44](https://user-images.githubusercontent.com/1108546/111680871-efe59c00-8822-11eb-9c96-ea5309f8a252.png)
![Screenshot from 2021-03-18 19-45-08](https://user-images.githubusercontent.com/1108546/111680870-ef4d0580-8822-11eb-9f57-6de6d3e17386.png)

Expected behaviour: no UI glitch; download is aways above the sharing icons, and delete is at the far right

**Comment by ChrisEdS** [comment]
It's not only `Download`:

![image](https://user-images.githubusercontent.com/33026403/111685321-0e01cb00-8828-11eb-96d8-8ff9a714520f.png)

**Comment by JanAckermann** [comment]
Not related to files_pdfviewer itself, more related to vierMode in core

**Comment by micbar** [comment]
@JanAckermann sorry to re open, but we need a backport to the release-10.7.0 branch. For the changelog item, we need same name, exactly the same content and in the 10.7.0 folder

**Comment by JanAckermann** [comment]
A

**Comment by micbar** [comment]
yes

**Comment by JanAckermann** [comment]
@micbar need some help here, do I need to copy the changelog file on the current branch ?

**Comment by micbar** [comment]
Yes. the docs are here https://confluence.owncloud.com/display/OG/Generating+Changelog+Entries

But the real challenge here is that we are doing a backport.

The `release-10.7.0` branch will be merged into master after the release.
So the copy of the changelog item will be in the subfolder `changelog/10.7.0_YYYY_MM_DD` and should not create a merge conflict in master.

After pushing, you will see this in #38518
I keep this PR open to get notified about merge conflicts very early. Just give it a try.

**Comment by JanAckermann** [comment]
@micbar So if I get it correct?
1. pull latest release-10.7.0 branch
2. Do a copy of the recent changelog item to the changelog/10.7.0_2021-03-05 folder
3. Commit and push to this branch? 

For me the branch release-10.7.0 is write protected

**Comment by jnweiger** [comment]
> For me the branch release-10.7.0 is write protected

You cannot directly push to the release-10.7.0 branch, please branch from there, and make us a PR back into release-10.7.0

**Comment by JanAckermann** [comment]
@jnweiger already done
