### ISSUE TITLE
problem to update linux server 10.6

### ISSUE THREAD

**Issue by alexdrastic** [owncloud/core#38558]
I'm on update owncloud server from 10.1 to 10.6 on linux server and i have this error. Can anybody help me? thanks

You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Avviso di riparazionePlease install or update the following apps manually or disable them with: occ app:disable files_reader

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by phil-davis** [comment]
That app seems to only support up to ownCloud 10.0:
https://github.com/Yetangitu/owncloud-apps/blob/master/files_reader/appinfo/info.xml#L54
```
<owncloud min-version="8.2" max-version="10.0" />
```

I am surprised that you could run it on ownCloud 10.1./

Disable the app and then do the upgrade, like the message suggests.

https://github.com/Yetangitu/owncloud-apps/issues/119 is about this problem. Nobody has updated the app in a long time. If you want to keep using it, then I suggest that you (or "someone") contribute to update the app to support the latest ownCloud10 release.

**Comment by alexdrastic** [comment]
> That app seems to only support up to ownCloud 10.0:
> https://github.com/Yetangitu/owncloud-apps/blob/master/files_reader/appinfo/info.xml#L54
> 
> ```
> <owncloud min-version="8.2" max-version="10.0" />
> ```
> 
> I am surprised that you could run it on ownCloud 10.1./
> 
> Disable the app and then do the upgrade, like the message suggests.
> 
> [Yetangitu/owncloud-apps#119](https://github.com/Yetangitu/owncloud-apps/issues/119) is about this problem. Nobody has updated the app in a long time. If you want to keep using it, then I suggest that you (or "someone") contribute to update the app to support the latest ownCloud10 release.

Hi,

thank you. now i delete all and I reinstall all. I hope not have problem. But on owncloud is changed more setting

**Comment by alexdrastic** [comment]
I'm on serverweb view but i cannot digit line of code. i can only set configure.php and other little setting. I hope all return work ok.

**Comment by alexdrastic** [comment]
can you help me about. i cannot restart owncloud. regards

**Comment by alexdrastic** [comment]
> That app seems to only support up to ownCloud 10.0:
> https://github.com/Yetangitu/owncloud-apps/blob/master/files_reader/appinfo/info.xml#L54
> 
> ```
> <owncloud min-version="8.2" max-version="10.0" />
> ```
> 
> I am surprised that you could run it on ownCloud 10.1./
> 
> Disable the app and then do the upgrade, like the message suggests.
> 
> [Yetangitu/owncloud-apps#119](https://github.com/Yetangitu/owncloud-apps/issues/119) is about this problem. Nobody has updated the app in a long time. If you want to keep using it, then I suggest that you (or "someone") contribute to update the app to support the latest ownCloud10 release.

thank you. I install all and now run ok!!

GRAZIE!!
