### ISSUE TITLE
[QA] Setting menu icons from a theme doesn't work

### ISSUE THREAD

**Issue by gabi18** [owncloud/core#38566]
Related to [Fix a regression with theming of settings menu icons](https://github.com/owncloud/core/pull/38246)
Test instructions from above:
1.    Enable any app-theme.
2.    Override users icon in the top right menu in your app-theme (settings/img/users.svg)

Tested on 10.7.0RC1

Steps done:
1. Installed app-theme according to https://doc.owncloud.org/server/10.6/developer_manual/core/theming.html
2. Put a customized icon users.svg to /var/www/owncloud/apps/mynewtheme/settings/img
3. Checked icon in 'admin' menu 

Expected behaviour: 
The new icon should be shown

Actual behaviour
Nothing changed, still the icon from core is there

![app-theme](https://user-images.githubusercontent.com/75983861/112009860-13605d80-8b27-11eb-8c46-1615f74a666b.png)

**Comment by gabi18** [comment]
Is there something to add to /var/www/owncloud/apps/mynewtheme/core/css/styles.css ?

**Comment by gabi18** [comment]
root@64981c0be98d: /var/www/owncloud/apps/mynewtheme/settings # ll -R
.:
total 12K
drwxr-xr-x 3 www-data root 4.0K Mar 22 12:29 ./
drwxr-xr-x 5 www-data root 4.0K Mar 22 12:28 ../
drwxr-xr-x 2 www-data root 4.0K Mar 22 13:15 img/

./img:
total 12K
drwxr-xr-x 2 www-data root 4.0K Mar 22 13:15 ./
drwxr-xr-x 3 www-data root 4.0K Mar 22 12:29 ../
-rw-r--r-- 1 www-data root  971 Mar 22 13:10 users.svg

root@64981c0be98d: /var/www/owncloud/apps/mynewtheme/settings #

**Comment by VicDeo** [comment]
works properly for me.
```
>cd apps-external/
>git clone git@github.com:owncloud/theme-example.git
Cloning into 'theme-example'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 77 (delta 6), reused 5 (delta 0), pack-reused 57
Receiving objects: 100% (77/77), 241.99 KiB | 524.00 KiB/s, done.
Resolving deltas: 100% (15/15), done.
>cd ..
>php occ a:e theme-example
>mkdir -p apps-external/theme-example/settings/img
>cp core/img/appstore.svg  apps-external/theme-example/settings/img/users.svg
```

![Screenshot_20210322_185324](https://user-images.githubusercontent.com/991300/112019181-3cd9b300-8b40-11eb-998f-265298aab112.png)


is `mynewtheme`  actually enabled?

**Comment by gabi18** [comment]
Yes, it is enabled. 
I will retest doing the steps you described above. 
Thanks!

**Comment by gabi18** [comment]
I have found out what the problem is:
It's the name "mynewtheme". If the app-name doesn't start with "theme" the icons in 'settings' directory aren't found. The app itself is enabled correctly, the purple menu bar is shown.
After renaming my theme to "theme-mynew" the new icon 'users.svg'  is taken.

**Comment by gabi18** [comment]
Shouldn't it also be possible to replace the 'admin.svg' icon besides 'Settings'? For me it doesn't work.

**Comment by ChrisEdS** [comment]
@gabi18 The <id> in the info.xml file has to match with the folder name.
https://github.com/owncloud/theme-example/blob/21495712d4aac25e3a38bda9c431251505b45d97/appinfo/info.xml#L3

**Comment by gabi18** [comment]
@ChrisEdS  Foldername and name in info.xml match. With 'theme-myown' I get the new icon in menu.

 /var/www/owncloud/apps/theme-mynew/appinfo # cat info.xml
<?xml version="1.0"?>
<info>
  <id>theme-mynew</id>
  <name>My ownCloud Theme</name>
  <description>This App provides the example ownCloud theme.</description>
  <licence>AGPL</licence>
  <author>Philipp Schaffrath</author>
  <version>1.0.0</version>
  <types>
    <theme/>
  </types>
  <dependencies>
    <owncloud min-version="10.2" max-version="10" />
  </dependencies>
  <namespace>Theme</namespace>
</info>

![breadcrumb_screenshot](https://user-images.githubusercontent.com/75983861/112119514-bbc10100-8bbd-11eb-8627-3b04f9bc0502.png)

**Comment by gabi18** [comment]
I don't get the new icon if the name is 'mynewtheme'.
/var/www/owncloud/apps/mynewtheme/appinfo # cat info.xml 
```
<?xml version="1.0"?>
<info>
        <id>mynewtheme</id>
 ...
```

**Comment by ChrisEdS** [comment]
That's weird.

**Comment by VicDeo** [comment]
```
> cp -r apps-external/theme-example/ apps/mynewtheme
> sed -i 's/theme-example/mynewtheme/g' apps/mynewtheme/appinfo/info.xml
> php occ a:d theme-example
theme-example disabled
> php occ a:e mynewtheme
mynewtheme enabled
```

Still works for me. I suspect that there is something with the theme itself...

**Comment by gabi18** [comment]
Can confirm now that in the end replacing users.svg and admin.svg also works for me.

I' am not sure where exactly the problem was. After trying several renames, finally when I renamed 'mynewtheme' to 'mytheme', disabled the running app and enabled the new one, the icons are shown correctly. It seems to me that the order of renaming, reloading page, enabling, disabling the app might have an influence. Maybe also that I did my tests in a docker container.
My test on a server without docker using the 'apps-external' directory was successful almost at once (just one rename).

**Comment by gabi18** [comment]
What I couldn't do so far is replacing 'logout.svg'. 
Where must it provided? I tried 'apps-external/new-theme/settings/img' and 'apps-external/new-theme/settings/img/actions'.

**Comment by VicDeo** [comment]
@gabi18 `apps-external/new-theme/core/img/actions/logout.svg`

**Comment by gabi18** [comment]
Succeeded with replacing all 3 icons from menu - but only when I renamed the app-theme.

Steps done:
```
# mkdir apps-external/new-theme/core/img/actions
# cp core/img/facicon.svg  apps-external/new-theme/core/img/actions/logout.svg
# occ app:disable new-theme
# occ app:enable new-theme
```
Result: the new icon isn't shown in menu after reloading browser page

Succeeded after:
```
# mv new-theme mynew-theme
# sed -i 's/new-theme/mynew-theme/g' mynew-theme/appinfo/info.xml
# occ app:disable new-theme
# occ app:enable mynew-theme
```

Result:

![all_replaced](https://user-images.githubusercontent.com/75983861/112275352-d0fe6400-8c7f-11eb-9af1-670817f05503.png)

**Comment by VicDeo** [comment]
> but only when I renamed the app-theme.

unfortunately no idea what could be a reason here except permissions/cache...

**Comment by micbar** [comment]
ok, seems to be not an  issue.

@gabi18 renaming always breaks the data in about an app in the database. If you do a rename, you need to purge the entries from the database or reset your instance.

As we see, it works with a clean install and a proper naming. Closing.
