### ISSUE TITLE
code style checks failing with php-cs-fixer 2.18.4

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#38563]
For various `class` `interface` etc statements, php-cs-fixer 2.18.4 wants the opening `{` to be on a new line:
```
-interface IParameter {
+interface IParameter
+{
```

See demo CI in PR #38561

**Comment by phil-davis** [comment]
The php-cs-fixer patch release is not backward-compatible. I raised issue https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5566

For now, we could pin the version of php-cs-fixer that is used. See PR #38562 - and then see if a 2.18.5 release comes to correct the problem.

Otherwise, if we "fix" the style, there are 2411 files changed! See PR #38560 - and we will need to adjust the php-code-sniffer settings also.

**Comment by phil-davis** [comment]
I have pinned php-cs-fixer to 2.18.3 in https://github.com/owncloud/coding-standard/pull/21

`owncloud/coding-standard` 2.0.1 has been released, and that gets CI passing again, without needing to pin it in each and every core and oC10 app repo.

**Comment by phil-davis** [comment]
ToDo: sort out how to unpin php-cs-fixer version for the future.

**Comment by korelstar** [comment]
> ToDo: sort out how to unpin php-cs-fixer version for the future.

You could exclude a buggy version instead of pinning an older version: `"^2.17 !=2.18.4"`

**Comment by phil-davis** [comment]
We pinned to 2.18.3 already. When 2.18.5 comes out, I will unpin it...

**Comment by phil-davis** [comment]
I created https://github.com/owncloud/coding-standard/releases/tag/2.0.2 which has:
```
        "friendsofphp/php-cs-fixer": "^2.19"
```

The problem with 2.18.4 has been fixed. 2.19 has some things marked deprecated, and those have been adjusted in https://github.com/owncloud/coding-standard/blob/master/src/Config.php

We also need to rename .php_cs.dist -> .php-cs-fixer.dist.php for 2.19 (the old name is deprecated). That is happening in #38823 aand can also be done in oC10 app repos.
