### ISSUE TITLE
[QA] group_admin can't select his groups to create user (403 forbidden)

### ISSUE THREAD

**Issue by iHerrmann77** [owncloud/core#38580]
Server: 10.7 RC2
 
### Steps to reproduce
1. as admin create userX
2. create groupX
3. make userX group_admin of groupX
4. login with userX
5. show Users
6. enter username and mail
7. click on dropdown Groups -> inspect network monitor -> 403 forbidden

### Expected behaviour
- a group_admin can see his groups (screen left side)
- the select to create user should have his groups too!!!

### Actual behaviour
-- The group_admin is creating a user, but in Groups (admin role) where he is not allowed.

![group_admin](https://user-images.githubusercontent.com/63246306/112327059-623bfd80-8cb5-11eb-8843-a014c8b29b6e.png)

**Comment by micbar** [comment]
maybe related https://github.com/owncloud/core/pull/38280

**Comment by micbar** [comment]
@iHerrmann77 Can you please re test with 10.6.0 to check that this is not a regression?

**Comment by iHerrmann77** [comment]
retested on server 10.6.0

![Screenshot from 2021-03-25 13-38-49](https://user-images.githubusercontent.com/63246306/112474268-ae4b7880-8d6f-11eb-935d-07b61eb1c415.png)

**Comment by phil-davis** [comment]
Note: in 10.6.0, as a sub-admin, you get to see and choose the group(s) for a new user. The list correctly shows the groups that you have sub-admin rights for. Slightly weirdly, if you do not select any of the groups then the new user is put into all the groups (as if you had selected all the groups in the dropdown).

Ideally the sub-admin should be forced to have at least 1 group selected.
The sub-admin can edit the groups that a user is in. That dropdown list of groups behaves correctly - the user must remain in at least 1 group that the sub-admin has rights to.

I also checked on 10.7.0 and it is broken - the sub-admin cannot choose any groups when creating a new user. But when they do create a new user, the new user is put into all the groups that the sub-admin has sub-admin rights for. The sub-admin cannot then adjust the group membership (e.g. the new user is a member of group_1 and group_2, the sub-admin cannot remove the new user from one of those groups).

If a sub-admin has rights for just one group then there is no real problem - new users end up in the group and there is no need to be able to edit the group membership anyway. So this issue will really effect sub-admins that have rights to more than one group.

**Comment by phil-davis** [comment]
Fixed in master by PR #38584 
Fixed in release-10.7.0 by #38587

**Comment by jnweiger** [comment]
Confirmed fixed in final 10.7.0 aka https://download.owncloud.org/community/owncloud-complete-20210326.tar.bz2
