### ISSUE TITLE
Test coverage for user with zero quota

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#38592]
Add API test coverage for the problem fixed in PR #38591 

A user that has zero quota (or not sufficient quota) tries to move a file from a received share into their own folder. The move should not be allowed.

Think of other scenarios where a user can have received access to a file and try to move it into their own folder, and test those.

Check existing test scenarios about quota and make sure they are covered well (e.g. uploading a file when the user does not have enough quota)

**Comment by dpakach** [comment]
Added in https://github.com/owncloud/core/pull/38591
