### ISSUE TITLE
No files displayed in Web UI

### ISSUE THREAD

**Issue by misse** [owncloud/core#38609]
owncloud_1  | Creating volume folders...
owncloud_1  | Creating hook folders...
owncloud_1  | Waiting for MySQL...
owncloud_1  | services are ready!
owncloud_1  | Waiting for Redis...
owncloud_1  | services are ready!
owncloud_1  | Removing custom folder...
owncloud_1  | Linking custom folder...
owncloud_1  | Removing config folder...
owncloud_1  | Linking config folder...
owncloud_1  | Writing config file...
owncloud_1  | Fixing base perms...
owncloud_1  | Fixing data perms...
owncloud_1  | Fixing hook perms...
owncloud_1  | Upgrading server database...
owncloud_1  | ownCloud or one of the apps require upgrade - only a limited number of commands are available
owncloud_1  | You may use your browser or the occ upgrade command to do the upgrade
owncloud_1  | 2021-04-01T10:33:43+00:00 Set log level to debug
owncloud_1  | 2021-04-01T10:33:43+00:00 Repair step: Upgrade app code from the marketplace
owncloud_1  | 2021-04-01T10:33:43+00:00 Repair info: Using market to update existing apps
owncloud_1  | 2021-04-01T10:33:43+00:00 Repair info: Attempting to update the following existing compatible apps from market: activity, comments, configreport, dav, federatedfilesharing, federation, files, files_external, files_mediaviewer, files_pdfviewer, files_sharing, files_texteditor, files_trashbin, files_versions, firstrunwizard, market, notifications, provisioning_api, systemtags, templateeditor, updatenotification, user_ldap
owncloud_1  | 2021-04-01T10:33:43+00:00 Repair info: Fetching app from market: activity
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info:
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: comments
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App (comments) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: configreport
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App (configreport) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: dav
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App (dav) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: federatedfilesharing
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App (federatedfilesharing) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: federation
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App (federation) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App (files) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files_external
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App (files_external) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files_mediaviewer
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info:
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files_pdfviewer
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info:
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files_sharing
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App (files_sharing) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files_texteditor
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info:
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files_trashbin
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App (files_trashbin) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: files_versions
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App (files_versions) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: firstrunwizard
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App (firstrunwizard) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: market
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info:
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: notifications
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App (notifications) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: provisioning_api
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App (provisioning_api) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: systemtags
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: templateeditor
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info:
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: updatenotification
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App (updatenotification) is not known at the marketplace.
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: Fetching app from market: user_ldap
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info:
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: activity
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: comments
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: configreport
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: dav
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: federatedfilesharing
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: federation
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files_external
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files_mediaviewer
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files_pdfviewer
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files_sharing
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files_texteditor
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files_trashbin
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: files_versions
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: firstrunwizard
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: market
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: notifications
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: provisioning_api
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: systemtags
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: templateeditor
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: updatenotification
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: App was not updated: user_ldap
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair step: Repair MySQL database engine
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair step: Repair MySQL collation
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: All tables already have the correct collation -> nothing to do
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair step: Repair SQLite autoincrement
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair step: Repair orphaned reshare
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair step: Repair duplicate entries in oc_lucene_status
owncloud_1  | 2021-04-01T10:33:44+00:00 Repair info: lucene_status table does not exist -> nothing to do
owncloud_1  | 2021-04-01T10:33:44+00:00 Updating database schema
owncloud_1  | 2021-04-01T10:33:44+00:00 Updated database
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair step: Repair mime types
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair step: Detect file cache entries with path that does not match parent-child relationships
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair step: Generate ETags for file where no ETag is present.
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair info: ETags have been fixed for 0 files/folders.
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair step: Clean tags and favorites
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair info: 0 tags of deleted users have been removed.
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair info: 0 tags for delete files have been removed.
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair info: 0 tag entries for deleted tags have been removed.
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair info: 0 tags with no entries have been removed.
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair step: Drop old database tables
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair step: Drop old background jobs
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair step: Remove getetag entries in properties table
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair info: Removed 0 unneeded "{DAV:}getetag" entries from properties table.
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair step: Repair invalid shares
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair step: Repair sub shares
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair step: Remove old share propagation app entries
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair step: Move user avatars outside the homes to the new location
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair info: No action required
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair step: Fix user avatars location
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair info: No action required
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair step: Remove shares of a users root folder
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair step: Repair unmerged shares
owncloud_1  | 2021-04-01T10:33:45+00:00 Repair step: Disable extra themes
owncloud_1  | 2021-04-01T10:33:46+00:00 Starting code integrity check...
owncloud_1  | 2021-04-01T10:34:09+00:00 Finished code integrity check
owncloud_1  | 2021-04-01T10:34:09+00:00 Update successful
owncloud_1  | 2021-04-01T10:34:09+00:00 Maintenance mode is kept active
owncloud_1  | 2021-04-01T10:34:09+00:00 Reset log level
owncloud_1  | ownCloud is in maintenance mode - no app have been loaded
owncloud_1  |
owncloud_1  | ownCloud is in maintenance mode - no app have been loaded
owncloud_1  |
owncloud_1  | <warning>ownCloud is in maintenance mode</warning>
owncloud_1  | Maybe an upgrade is already in process. Please check the logfile (data/owncloud.log). If you want to re-run the upgrade procedure, remove the "maintenance mode" from config.php and call this script again.
owncloud_1  | Writing objectstore config...
owncloud_1  | Writing php config...
owncloud_1  | ownCloud is in maintenance mode - no app have been loaded
owncloud_1  |
owncloud_1  | Updating htaccess config...
owncloud_1  | ownCloud is in maintenance mode - no app have been loaded
owncloud_1  |
owncloud_1  | .htaccess has been updated
owncloud_1  | Writing apache config...
owncloud_1  | Enabling cron background...
owncloud_1  | ownCloud is in maintenance mode - no app have been loaded
owncloud_1  |
owncloud_1  | Set mode for background jobs to 'cron'
owncloud_1  | Touching cron configs...
owncloud_1  | Starting cron daemon...
owncloud_1  | Starting apache daemon...
owncloud_1  | [Thu Apr 01 10:34:13.681818 2021] [mpm_prefork:notice] [pid 217] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
owncloud_1  | [Thu Apr 01 10:34:13.681862 2021] [core:notice] [pid 217] AH00094: Command line: '/usr/sbin/apache2 -f /etc/apache2/apache2.conf -D FOREGROUND'
owncloud_1  | 127.0.0.1 - - [01/Apr/2021:10:34:32 +0000] "GET /status.php HTTP/1.1" 200 1090 "-" "curl/7.68.0"
owncloud_1  | 159.153.150.4 - - [01/Apr/2021:10:34:32 +0000] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 798 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 159.153.150.4 - misse [01/Apr/2021:10:34:43 +0000] "GET /status.php HTTP/1.1" 200 811 "-" "Mozilla/5.0 (Macintosh) mirall/2.7.6 (build 3261) (ownCloud, osx-18.7.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:30 +0000] "GET / HTTP/1.1" 302 1496 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safa
ri/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:30 +0000] "GET /login HTTP/1.1" 200 2844 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90
 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:30 +0000] "GET /core/js/oc.js?v=5cd084d532a5af08f8389b35e806788c HTTP/1.1" 200 3798 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537
.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:31 +0000] "GET /core/vendor/browser-update/browser-update.js?_=1617275671108 HTTP/1.1" 200 11351 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) Ap
pleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:33 +0000] "POST /login HTTP/1.1" 303 788 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90
 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:34 +0000] "GET /apps/files/ HTTP/1.1" 200 5490 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4
389.90 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:34 +0000] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 798 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) Ap
pleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 85.225.169.174 - misse [01/Apr/2021:11:14:34 +0000] "PROPFIND /remote.php/dav/files/87bbc64e-5b02-11e9-a376-5254008c30e5/ HTTP/1.1" 207 909 "-" "Mozilla/5.0 (Macintosh) mirall/2.7.6 (build 3
261) (ownCloud, osx-18.7.0 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:34 +0000] "PROPFIND /remote.php/dav/files/null/ HTTP/1.1" 404 769 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:39 +0000] "REPORT /remote.php/dav/files/null/ HTTP/1.1" 404 719 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:41 +0000] "PROPFIND /remote.php/dav/files/null/ HTTP/1.1" 404 769 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:46 +0000] "GET /apps/files/?dir=/& HTTP/1.1" 200 5481 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:46 +0000] "GET /core/vendor/select2/select2.css?v=5cd084d532a5af08f8389b35e806788c HTTP/1.1" 200 3731 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:46 +0000] "GET /core/css/header.css?v=5cd084d532a5af08f8389b35e806788c HTTP/1.1" 200 2858 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:46 +0000] "GET /core/css/styles.css?v=5cd084d532a5af08f8389b35e806788c HTTP/1.1" 200 6727 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:46 +0000] "GET /core/css/icons.css?v=5cd084d532a5af08f8389b35e806788c HTTP/1.1" 200 2022 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:46 +0000] "GET /core/css/inputs.css?v=5cd084d532a5af08f8389b35e806788c HTTP/1.1" 200 2503 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:46 +0000] "GET /core/css/fonts.css?v=5cd084d532a5af08f8389b35e806788c HTTP/1.1" 200 778 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:46 +0000] "GET /core/css/apps.css?v=5cd084d532a5af08f8389b35e806788c HTTP/1.1" 200 4045 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
owncloud_1  | 85.225.169.174 - - [01/Apr/2021:11:14:46 +0000] "GET /core/css/global.css?v=5cd084d532a5af08f8389b35e806788c HTTP/1.1" 200 974 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"

**Comment by pascalwengerter** [comment]
Okay so this issue has found a more suitable home ;) could you head over to https://github.com/owncloud/web/issues/new and update your inital comment with more information?

The more you provide, the easier and faster it is to resolve it. Is this a new install or did it happen after an update, which steps have you gone through when installing, Docker vs bare metal, how does `config.php` look like etc etc

**Comment by misse** [comment]
I see now that my I messed up my post and only submitted my log and not all the rest. My bad, I'll open the issue and submit everything required in the form. Thanks for your patience @pascalwengerter
