### ISSUE TITLE
Acceptance tests with no skeleton have welcome.txt

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#38607]
See PR #38606 for an idea of what was unexpected.

In core drone CI test scenarios pass that create a user "without skeleton files" and then make use of "welcome.txt".

Actually there should be no skeleton files at all. When drone CI runs for an oC10 app, such test scenarios fail. There is no "welcome.txt".

Investigate what is happening, why "without skeleton files" is not completely effective in some cases. And fix the code. (We want to have "without skeleton files" behave as expected in core, so that we immediately find any accidental uses of files like `welcome.txt`)

**Comment by phil-davis** [comment]
See PR #38629 - `welcome.txt` still exists even when the test steps specify no skeleton files.

**Comment by individual-it** [comment]
yes it does exist, but why is that a problem? the tests just should not use it

**Comment by phil-davis** [comment]
Somehow when the oC10 app tests run, there is no `welcome.txt`. So we notice then if someone accidentally depends on `welcome.txt` in an acceptance test. But when run acceptance tests in core, there is a `welcome.txt` and so the scenario passes when run in core.

It would be nice if the environment in core CI and in app CI behaved the same.

**Comment by phil-davis** [comment]
https://github.com/owncloud/core/blob/master/lib/private/legacy/util.php#L383
```
$skeletonDirectory = \OC::$server->getConfig()->getSystemValue('skeletondirectory', \OC::$SERVERROOT . '/core/skeleton');
```

When no skeleton is set, it defaults to `/core/skeleton` and that has `welcome.txt` in it.

**Comment by phil-davis** [comment]
https://download.owncloud.org/community/daily/owncloud-latest.tar.bz2 (the release tarball) has different content in `/core/skeleton` - it has some files in Documents and Photos, and has `ownCloud Manual.pdf`

https://download.owncloud.org/community/daily/owncloud-daily-master-qa.tar.bz2 (the daily tarball that also has the testing app) has the same - some files in Documents and Photos, and has `ownCloud Manual.pdf`

So when using those tarballs there will be no `welcome.txt` but there will be `ownCloud Manual.pdf` etc.

Hmmm - what is a useful thing to do for testing?

**Comment by kiranparajuli589** [comment]
we call the tests end-to-end so the tests should behave similarly to how the server behave in actuality. any extra configuration can confuse the users. e2e users get a welcome.txt and we test with similar users. but also we're writing gherkin and make the end-users understand by the language so that we can gain a little bit of speed and similar behavior in all apps, clients, and server

**Comment by individual-it** [comment]
what about clearing `/core/skeleton` altogether to make sure there is no skeleton files at all?

**Comment by phil-davis** [comment]
> what about clearing `/core/skeleton` altogether to make sure there is no skeleton files at all?

The challenge is that the system-under-test has stuff in `core/skeleton` and so we would need to get the testing app to clear it for us. And we want our tests to be "less destructive" when possible, so we would need to save whatever is in `core/skeleton` and put it back when the tests exit. For example, local developers running tests. If we delete `core/skeleton` then that will show in the developer's git as a change waiting to be committed.

It is possible, but maybe it is easier to have an "almost empty" skeleton to use in tests.
