### ISSUE TITLE
Apt Repo download.owncloud.org not uptodate (10.7)

### ISSUE THREAD

**Issue by DevertNet** [owncloud/core#38612]
Hey,

is there a reason why version 10.7 is not in the repo?
https://download.owncloud.org/download/repositories/production/Debian_10/

Is there a reason why the apt repo feels neglected? Referring to the last update: https://github.com/owncloud/core/issues/38381

Best regards!

**Comment by DevertNet** [comment]
*bump*

**Comment by jnweiger** [comment]
Fixed meanwhile. Sorry for the delay.

**Comment by PeterPablo** [comment]
what is the scheduled release on apt for 10.8?
