### ISSUE TITLE
Feature Request: Make `last_login` field accessible through the Provisioning API

### ISSUE THREAD

**Issue by ctcq** [owncloud/core#38624]
Submitting as an issue over here as we cannot find an issue type for feature requests.

#### Reason we need it
We are maintaining a custom (de-)provisioning routine for multiple owncloud instances and need a better way to access the `last_login` column from the `oc_accounts` table. Our custom provisioning routines need this bit of information and we cannot access the database directly.

We found that implementing access to this field via Provisioning API would be trivial.

#### Possible Implementation
The necessary changes to the code minimal. The API already exposes parts of the [IUser](https://github.com/owncloud/core/blob/master/lib/public/IUser.php#L90) interface, though that particular interface method is not used by the Provisioning API yet.

```diff
--- a/apps/provisioning_api/lib/Users.php
+++ b/apps/provisioning_api/lib/Users.php
@@ -217,6 +217,7 @@ class Users {
                $data['displayname'] = $targetUserObject->getDisplayName();
                $data['home'] = $targetUserObject->getHome();
                $data['two_factor_auth_enabled'] = $this->twoFactorAuthManager->isTwoFactorAuthenticated($targetUserObject) ? 'true' : 'false';
+               $data['last_login'] = $targetUserObject->getLastLogin();
 
                return new Result($data);
        }
```

We've forked this repo as we're not permitted to push new branches. You can find it over here: https://github.com/ctcq/core/tree/provisioning-api-last-login

If there are additional changes to be made we'd be glad to contribute further.

#### Testing
We couldn't find existing Unit-Tests for the API and therefore couldn't expand them for this new feature. Manual testing on a local instance has been successful, however.

**Comment by phil-davis** [comment]
https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiProvisioning-v1/getUser.feature has API acceptance tests that check some of the data that is delivered in Provisioning API responses. If `last_login` is added, then it will be easy to add an appropriate test scenario.

https://github.com/owncloud/core/blob/master/apps/provisioning_api/tests/UsersTest.php has unit tests for that Users class. For example, `testGetUserAsAdmin` checks the structure returned by `getUser`

You can make a PR from a fork to `owncloud/core`

**Comment by ctcq** [comment]
Thank you for the help. 

Since this is my first time contributing, I'm still struggling with the setup a bit. But here's an update: 

Unit tests have been implemented and seem to work just fine: https://github.com/ctcq/core/blob/provisioning-api-last-login/apps/provisioning_api/tests/UsersTest.php

I've also created modified the relevant acceptance tests: https://github.com/ctcq/core/blob/provisioning-api-last-login/tests/acceptance/features/apiProvisioning-v1/getUser.feature

However, I'm can't get the acceptance test to run properly, even without any modifications. I'm aware of the [Developer Documentation](https://doc.owncloud.com/server/developer_manual/testing/acceptance-tests.html) and tried to follow it. Here's the output from 
```
make test-acceptance-api BEHAT_FEATURE=tests/acceptance/features/apiProvisioning-v1/getUser.feature
```

[acceptance.log](https://github.com/owncloud/core/files/6317468/acceptance.log)

I'd appreciate if someone could help me with that.

**Comment by phil-davis** [comment]
@ctcq PR #39351 has been merged. It should be in the next ownCloud release 10.9.0
