### ISSUE TITLE
newly uploaded files appears in search result list before reloading the webUI

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/core#38641]
### Steps to reproduce
1. Create a user `Alice` and log in with the user. You should be redirected to the files page.
2. create a directory at the root
  ```sh
  curl -X MKCOL -u admin:admin http://localhost/core/remote.php/dav/files/admin/simple-folder
2. Upload two new files using API
  ```sh
  curl -X PUT http://localhost/core/remote.php/dav/files/admin/torem.txt -u Alice:1234 -d "new content"
  curl -X PUT http://localhost/core/remote.php/dav/files/admin/simple-folder/torem.txt -u Alice:1234 -d "new content"
  ```
3. now do not reload your and search for `torem` using the web UI

### Expected behaviour
As the web UI is not reloaded yet...it should not be aware of these recently uploaded files.
> If new folders are created using API and the search is done without the reload....the web UI is unware of new folders

### Actual behaviour
newly uploaded files are found on the search results as:
![Screenshot from 2021-04-15 12-42-45](https://user-images.githubusercontent.com/39373750/114827443-6e186c80-9de8-11eb-8497-4fb5d755ad2e.png)

### Server configuration
**Operating system**:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**Web server:**

**Database:** mysql

**PHP version:** 7.4

**ownCloud version:** (see ownCloud admin page) ownCloud 10.7.1 prealpha (git)

**Updated from an older ownCloud or fresh install:** update

**Where did you install ownCloud from:** git

**Are you using external storage, if yes which one:** None

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by JammingBen** [comment]
This is normal behavior. Searching resources will result in a new request, which of course finds the newly created files in your example. The API itself is stateless, thus there is no way for the server to detect what was loaded by a request before that.
