### ISSUE TITLE
OwnCloud update from 10.6.05 to 10.7.0 does not end

### ISSUE THREAD

**Issue by Theater-im-Pariser-Hof** [owncloud/core#38642]
OwnCloud update from 10.6.05 to 10.7.0 does not end

### Steps to reproduce
1. Go to your cloud version 10.6.05 (stable) as admin
2. start updater
3. wait till update is done

### Expected behaviour
Updater should go through all points till FINISH THE UPDATE and DONE

### Actual behaviour
Updater does all till point UPDATING CORE --> even after 40 minutes it does not come back or goes to next point 
I can still login and see my date (a checkpoint was also created --> Created checkpoint 10.6.0.5-60781bf653714)

### Server configuration
linux

**Web server:**

**Database:**

**PHP version:**
php 7.4

**ownCloud version:** (see ownCloud admin page)
10.6.05 (stable)

**Updated from an older ownCloud or fresh install:**
updated in the past from 10.5

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed  --> done --> No errors have been found.

```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
[owncloud.log](https://github.com/owncloud/core/files/6317484/owncloud.log)

```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by Theater-im-Pariser-Hof** [comment]
Did anyone see such a behavior? Can someone help out here?

**Comment by ho4ho** [comment]
Tryed https://doc.owncloud.com/server/10.7/admin_manual/maintenance/update.html:

> If the update fails, then you must [update manually](https://doc.owncloud.com/server/10.7/admin_manual/maintenance/manual_upgrade.html).

**Comment by Theater-im-Pariser-Hof** [comment]
Yes the update only creates 2 entries in the log and nothing more happens. I can not update manually, as I am not the hoster of the cloud, it is running on our webspace. I do not have a comman line access. And so far the updater was working very good.
The only difference between now and the past was the fact, that we did enable ssl (https) some weeks ago for the cloud and our webpage.

**Comment by VicDeo** [comment]
@Theater-im-Pariser-Hof could you share 
`data/update.log`

**Comment by Theater-im-Pariser-Hof** [comment]
yes sure, please see file attached.
[update.log](https://github.com/owncloud/core/files/6507989/update.log)

Thanks for looking into it.

**Comment by Theater-im-Pariser-Hof** [comment]
As far as I can see and understand, in the log we can see that former updates did run successfully. But the latest one just does somehow not proceed, with no error. As you can see, I did try to start the auto updater several times with no success. There is no timestamp in the log, but I did wait for a long time, at least 30 minutes or more.

**Comment by VicDeo** [comment]
@Theater-im-Pariser-Hof 
> the latest one just does somehow not proceed, with no error.
`executeCoreUpgradeScripts`  was started but hadn't succeed. This step should unzip a new owncloud package and replace the files. As udpdate.log doesn't contain anything about replacement something went wrong in the middle of unzipping.

updater doesn't write anything to owncloud log as it is completely standalone application. So you need to check webserver error log file to get more details

Was your environment changed since the last update?
It could be related either to some php extensions missing or to https://www.php.net/manual/en/info.configuration.php#ini.max-execution-time config option. So `executeCoreUpgradeScripts` has not enough time to compete and it is just killed by timeout. 

But these are just guesses. Webserver error log should give a clue.

**Comment by Theater-im-Pariser-Hof** [comment]
The only thing what was changed in the past, was that we changed the website from http to https.
But the cloud for sure did work after that change and also all other our webpages. So let me see if I can find the webserver error log...

**Comment by Theater-im-Pariser-Hof** [comment]
So I did find out, that the host does not run any logging, so there is no webserver error log. They mentioned to set debug level to 0 for the owncloud and re-run the updater. Is there something like a debug log level for the own cloud? How to set and where would I find the log then?

The base of all this is, that the host of the website and the cloud does not really do good servcie, so I can not update cloud manually. So if no auto update as in the past, one day the cloud will be old and I can just create a new cloud in my webspace. All from scratch then. I did that once and it is a hassle. So auto updater is essential.

**Comment by ho4ho** [comment]
> Is there something like a debug log level for the own cloud?

Looking available:

https://doc.owncloud.com/server/10.7/admin_manual/configuration/server/logging/logging_configuration.html

**Comment by VicDeo** [comment]
> https://doc.owncloud.com/server/10.7/admin_manual/configuration/server/logging/logging_configuration.html

that won't help as logging for updater is needed
It could be achieved by reconfiguring error logging in PHP with cPanel or whatever is available 
e.g. https://chemicloud.com/kb/article/how-to-enable-or-disable-php-error-logging-in-cpanel/

**Comment by Theater-im-Pariser-Hof** [comment]
Sorry, there is no error logging available, I did check with the host.

**Comment by Theater-im-Pariser-Hof** [comment]
It is sad, but also the update to the now current version 10.8.0 is hanging at the same point. Still not possible to use the updater to update the cloud....

**Comment by Theater-im-Pariser-Hof** [comment]
![Cloud updater](https://user-images.githubusercontent.com/58738708/132316417-5c233531-fa8c-4213-99f0-0bbb534862bd.JPG)
