### ISSUE TITLE
Opening and closing PDF displaces buttons over the file list

### ISSUE THREAD

**Issue by elizavetaRa** [owncloud/core#38650]
### Steps to reproduce
1. Open a PDF on the embedded PDF viewer
2. Close it with the 'X' button on the right side of the viewer bar
3. Click on any file/folder checkbox - the download, delete buttons on the right appear displaced

Tested in newest Versions of Chrome, Mozilla, Safari with different browser-sizes

![Bildschirmfoto vom 2021-04-23 10-11-21](https://user-images.githubusercontent.com/7430156/115840822-637b5a00-a41c-11eb-9eb0-4a5c5a8f7cd7.png)

**Comment by ho4ho** [comment]
Duplicate by #38547

**Comment by JanAckermann** [comment]
Please upgrade to 10.7 which should fix this Problem 👍
