### ISSUE TITLE
Potential fix for slow Oracle in CI?

### ISSUE THREAD

**Issue by IljaN** [owncloud/core#38679]
https://github.com/oracle/docker-images/issues/601
https://github.com/oracle/docker-images/issues/601#issuecomment-509250667
https://github.com/oracle/docker-images/issues/601#issuecomment-509251710

And maybe https://github.com/oracle/docker-images/issues/959#issuecomment-756949007
Could be worth a try.

@phil-davis  @individual-it

**Comment by individual-it** [comment]
If I understand it correctly those fixes are for oracle 12.x we are using 11.2 and I cannot run the `ALTER SESSION` command

```
Connected to:
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

SQL> ALTER SESSION SET CONTAINER = ORCLPDB1
                  *
ERROR at line 1:
ORA-02248: invalid option for ALTER SESSION
```

**Comment by individual-it** [comment]
strange `SHOW PARAMETER DISK_ASYNCH_IO` always shows `TRUE` regardless of what I do set

**Comment by individual-it** [comment]
after setting 
`ALTER SYSTEM SET FILESYSTEMIO_OPTIONS=DIRECTIO SCOPE=SPFILE`
and
`ALTER SYSTEM SET DISK_ASYNCH_IO=FALSE SCOPE=SPFILE`

it does not look like it got any faster. The `install-server` step still takes 13min :-(

https://drone.owncloud.com/owncloud/core/30244/19/6

**Comment by individual-it** [comment]
any other ideas or close this?

**Comment by phil-davis** [comment]
@IljaN @individual-it @dpakach what to do next? Close?

Oracle PHP unit tests are annoying in many oC10 apps - it takes longer to install Oracle than anything in any other pipelines. So there is a minimum of 15 to 20 minutes for app CI, waiting for that one pipeline to finish. Maybe we don't run unit tests with Oracle on oC10 app PRs, just run it in cron nightly.

**Comment by phil-davis** [comment]
I will switch off Oracle testing in app PRs, and leave in running just in nightly. That is a simple help with no real impact - in the rare case that someone breaks Oracle on an app PR, we will know the night after merge and can investigate.

**Comment by phil-davis** [comment]
PR https://github.com/owncloud/activity/pull/1068 has the code to not run Oracle in CI of PRs.

That needs to be updated in all other oC10 app repos at some time. There is no big hurry to do that - it can be done when there is an opportunity.

**Comment by phil-davis** [comment]
Also note that issue https://github.com/owncloud/QA/issues/700 will touch drone starlark. It will be good to also do that issue in the activity app, then do one pass of copying to the other oC10 apps.

**Comment by phil-davis** [comment]
I removed my assignment - the demo is merged in https://github.com/owncloud/activity/pull/1068 

ToDo:
- [ ] check the night CI of the activity app and confirm that PHP unit tests with Oracle are running there
- [ ] apply the drone starlark change to all app repos

**Comment by saw-jan** [comment]
PHP unit tests with Oracle are only run nightly. The implementation has been ported to all the oC apps.
Closing this for now.
