### ISSUE TITLE
Investigate webUIRestrictSharing/restrictSharing.feature:53 test failures

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#38677]
For example: https://drone.owncloud.com/owncloud/files_primary_s3/2213/29/19
```
  Scenario: Forbid sharing with groups                                                               # /var/www/owncloud/testrunner/tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature:53
    Given the setting "Allow sharing with groups" in the section "Sharing" has been disabled         # WebUIGeneralContext::settingInSectionHasBeen()
    When the user browses to the files page                                                          # WebUIFilesContext::theUserBrowsesToTheFilesPage()
INFORMATION: timed out waiting for ajax calls to start
    Then it should not be possible to share folder "simple-folder" with group "grp1" using the webUI # WebUISharingContext::itShouldNotBePossibleToShareFileFolderUsingTheWebUI()
      │ INFORMATION: timed out waiting for ajax calls to start
INFORMATION: timed out waiting for ajax calls to start
    And it should not be possible to share folder "simple-folder" with group "grp2" using the webUI  # WebUISharingContext::itShouldNotBePossibleToShareFileFolderUsingTheWebUI()
      │ INFORMATION: timed out waiting for ajax calls to start
    When the user shares folder "simple-folder" with user "Alice" using the webUI                    # WebUISharingContext::theUserSharesFileFolderWithUserUsingTheWebUI()
      element click intercepted: Element <a class="action action-share permanent" href="#" data-action="Share" data-original-title="" title="">...</a> is not clickable at point (777, 165). Other element would receive the click: <a href="#">...</a>
        (Session info: chrome=74.0.3729.169)
        (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.15.0-142-generic x86_64) (Exception)
    And the user re-logs in as "Alice" using the webUI                                               # WebUILoginContext::theUserRelogsInUsingTheWebUI()
    Then folder "simple-folder (2)" should be listed on the webUI                                    # WebUIFilesContext::fileFolderShouldBeListedOnTheWebUI()
SCENARIO RESULT: (fail)
```

That webUI test scenario failed twice in files_primary_s3 nightly testing.

"not clickable" indicates that there can sometimes be another UI element that covers sharing dialogs.

webUI tests get re-run automatically when they fail the first time. So we only notice the failure if the scenario fails twice.

- look to see if this scenario is failing often (look in some ordinary core PR drone builds, and in nightly of user_ldap, encryption and files_primary_s3 to find examples)
- try to reproduce and find out what is covering the sharing dialog
- fix it

**Comment by SwikritiT** [comment]
@phil-davis  I couldn't reproduce this error locally. I tried running the failing test on loop in both core and files_primary_s3. They passed every time. 
I tried to run the test in CI as well
## Core 
https://drone.owncloud.com/owncloud/core/29838/25/15
https://drone.owncloud.com/owncloud/core/29826/25/15 

## files_primary_s3 
The test did fail once on yesterday's build , CI was still green, probably because it only failed once.
https://drone.owncloud.com/owncloud/files_primary_s3/2245/14/19

Today I tried running it again on CI by running same failing scenario for 42 times and it has not failed once  
https://drone.owncloud.com/owncloud/files_primary_s3/2247/6/19

**Comment by phil-davis** [comment]
@SwikritiT thanks for the work investigating. I guess we have to close this, because we cannot reproduce it.

I will make another issue to run various webUI CI without the auto-rerun of failed scenarios, to see if we can find other scenarios that have intermittent failures.
