### ISSUE TITLE
Unable to run acceptance test

### ISSUE THREAD

**Issue by cheh2** [owncloud/core#38713]
**Steps to reproduce**

1. Remove current configuration (if exists)
sudo rm -rf $owncloud_installation_path/data/*
sudo rm -rf $owncloud_installation_path/config/*

2. Drop existing DB user and database (if any)
mysql -u root -e “DROP DATABASE owncloud;
DROP USER ‘oc_admin’;
DROP USER ‘oc_admin’@‘localhost’;
DROP USER ‘owncloud’@‘localhost’;
FLUSH PRIVILEGES”;

3. Create new database, DB user and grants
mysql -u root -e “CREATE DATABASE IF NOT EXISTS owncloud;
CREATE USER ‘owncloud’@‘localhost’ IDENTIFIED BY ‘owncloud’;
CREATE USER ‘’@‘localhost’ IDENTIFIED BY ‘’;
GRANT ALL PRIVILEGES ON owncloud.* TO ‘’@‘localhost’;
GRANT ALL PRIVILEGES ON owncloud.* TO ‘owncloud’@‘localhost’;
GRANT ALL PRIVILEGES ON mysql.* TO ‘owncloud’@‘localhost’;
FLUSH PRIVILEGES”;

4. Configure new DB
occ maintenance:install
–database “mysql”
–database-name “owncloud”
–database-user “owncloud”
–database-pass “owncloud”
–admin-user “admin”
–admin-pass “admin”

5. Set DEBUG env variables
export DEBUG_ACCEPTANCE_REQUESTS=true
export DEBUG_ACCEPTANCE_RESPONSES=true
export DEBUG_ACCEPTANCE_API_CALLS=true

6. Run a test case
sudo –u www-data make test-acceptance-api
SKELETON_DIR=apps/testing/data/apiSkeleton BEHAT_FEATURE=tests/acceptance/features/apiComments/comments.feature SHOW_OC_LOGS=true

Note: Other features were also tested and they resulted in similar errors.

**Expected behaviour**
Acceptance test cases should run successfully.

**Actual behaviour**
Unable to execute acceptance test cases to completion.

Getting response code 404 with message “The requested resource xxxxx was not found on this server.” for requests sent to http:/ / localhost:8180/xxxxx.

**Server configuration**
**Operating system:** Ubuntu 20.04.2 LTS

**Web server:** Apache/2.4.41

**Database:** MariaDB 10.3.25

**PHP version:** PHP 7.4.3

**ownCloud version: (see ownCloud admin page)** 10.7.0

**Updated from an older ownCloud or fresh install:** New install

**Where did you install ownCloud from:** Repository: https:/ / github. com/ owncloud/ core.git
**branch:** release-10.7.0

**The content of config/config.php:**
https://gist.github.com/benn8/d4adcac3c1b6a08832b8b075426072bf

**List of activated apps:**
root@***:/var/www/html/core/tests# occ app:list
Enabled:

- comments:
  - Version: 0.3.0
  - Path: /var/www/html/core/apps/comments
- dav:
  - Version: 0.6.0
  - Path: /var/www/html/core/apps/dav
- federatedfilesharing:
  - Version: 0.5.0
  - Path: /var/www/html/core/apps/federatedfilesharing
- federation:
  - Version: 0.1.0
  - Path: /var/www/html/core/apps/federation
- files:
  - Version: 1.5.2
  - Path: /var/www/html/core/apps/files
- files_external:
  - Version: 0.7.1
  - Path: /var/www/html/core/apps/files_external
- files_sharing:
  - Version: 0.14.0
  - Path: /var/www/html/core/apps/files_sharing
- files_trashbin:
  - Version: 0.9.1
  - Path: /var/www/html/core/apps/files_trashbin
- files_versions:
  - Version: 1.3.0
  - Path: /var/www/html/core/apps/files_versions
- provisioning_api:
  - Version: 0.5.0
  - Path: /var/www/html/core/apps/provisioning_api
- systemtags:
  - Version: 0.3.0
  - Path: /var/www/html/core/apps/systemtags
- testing:
  - Version: 0.1.0
  - Path: /var/www/html/core/apps/testing
- updatenotification:
  - Version: 0.2.1
  - Path: /var/www/html/core/apps/updatenotification
 
**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

**Logs**
**Console log**
https://gist.github.com/benn8/c67b93a4f189d065a60491600b626537

Would appreciate any help on the issue! Thank you very much!

**Comment by phil-davis** [comment]
You should not need to define `SKELETON_DIR` - the test runner and test scenarios set the skeleton the way they want these days.

Did you have the locations of the system-under-test defined?
```
export TEST_SERVER_URL=http://localhost:8080
export TEST_SERVER_FED_URL=http://localhost:8180
```
I think it defaults to that, and so it will try to access the "federated" server also, in case one of the test scenarios needs it. You can set up another ownCloud10 install and have it running on port 8180. But for most tests that is not needed. So just define:
```
export TEST_SERVER_URL=http://localhost:8080
```
And it should not bother trying to access a "federated" server.

**Comment by phil-davis** [comment]
`[Fri May  7 23:56:43 2021] Failed to listen on localhost:8180 (reason: Address already in use)`

You already have something running on port 8180. If that is your test ownCloud install (running in another terminal window, or with Apache or whatever) then great. You want to tell the test runner that the system-under-test is there:
`export TEST_SERVER_URL=http://localhost:8180`

The test runner is starting a local PHP dev server:
```
Using php inbuilt server for running scenario ...
8080
3356
8180
3357
```

That indicates that you do not have `TEST_SERVER_URL` defined. If you run the tests that way, then the test runner starts the PHP dev servr(s) and you see all that "noise" of the PHP dev server output telling what it is doing. Personally, I find it nicer to have the system-under-test running somewhere else (either with Apache or in a separate terminal window) I just run a PHP dev server:
```
phil@phil-OptiPlex-3050:~/git/owncloud/core$ php -S localhost:8080
[Sat May  8 19:16:34 2021] PHP 7.4.18 Development Server (http://localhost:8080) started
```

The test code uses the testing app to try to set up the system-under-test into a known state.
`127.0.0.1:54372 [400]: POST /ocs/v2.php/apps/testing/api/v1/occ`
indicates that the testing app is not enabled.
You should install and enable the testing app in the system-under-test. (Some tests might work without it, if the system-under-test is already in a "reasonable default state" anyway.

**Comment by cheh2** [comment]
Thanks for your help! Per your suggestion, I started 2 separate instances (each with own db) and set as follows in the command line (exporting the environment variable didn't work for some reason):
```
   TEST_SERVER_URL=http://localhost:80
   TEST_SERVER_FED_URL=http://localhost:8180
```
(Also double checked that the testing app was already enabled in both instances)
Below is the output of running the acceptance tests: (all passed)
https://gist.github.com/benn8/e8c7ee0e02b19f3122986bcdfb141b1f

I no longer get the parser error, which is great! There are still some initial 400/404 errors as shown in the two gist files below. Are they minor errors that can be ignored?
https://gist.github.com/benn8/a2d294af20367e444560792d3b8997d9
https://gist.github.com/benn8/8b50ff9cc60a4454a8b5402dac381c51

**Comment by phil-davis** [comment]
> I no longer get the parser error, which is great! There are still some initial 400/404 errors as shown in the two gist files below. Are they minor errors that can be ignored?

I am a bit surprised by that. The testing up does attempt to cleanup things that may not exist (trying to be sure to cleanup/setup). But usually those result in 404. Make sure that you have pulled the latest testing app code, because there have been extra testing app endpoints added over time.

If the tests pass, then it must be good ;)

**Comment by cheh2** [comment]
Yeah I did pull the latest testing app code. So it's weird why I'm getting the 400 errors. But so far, the tests are passing! :)

Thank you so much for all the help, I really appreciate it! I'll close the issue then. ;)
