### ISSUE TITLE
[QA] test coverage for adding public share to ownCloud

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#38752]
A public link share can be added to another ownCloud. The UI for that had some changes in PR #38712 

Check what API and UI test scenarios that already exist for this. Add API and UI scenarios to cover adding a public link share from a remote ownCloud to a local ownCloud. The test scenarios need to confirm that the added public link share "works" (download/upload of files... as the permission allows)

**Comment by saw-jan** [comment]
TODO:
- [ ] webUI
- [ ] API

**Comment by saw-jan** [comment]
@phil-davis maybe we can close this issue for now.

**Comment by phil-davis** [comment]
Done
