### ISSUE TITLE
Saved public shared folder doesn't get deleted when the sharer deletes the folder

### ISSUE THREAD

**Issue by saw-jan** [owncloud/core#38763]
### Steps to reproduce
1. create users `Alice` and `Brian`
3. `Alice` creates folder `FOLDER` and creates public share for `FOLDER`
5. access Public-share link in incognito mode
6. click `Add to localhost` and login as `Brian`
7. accept the remote share (folder `FOLDER` is there)
8. as `Alice`, delete folder `FOLDER`
9. as `Brian`, folder `FOLDER` is still there
10. as`Brian`, open `FOLDER` and go back to root dir (`FOLDER` is gone)

### Expected behaviour
whenever the sharer deletes the public-shared folder, the user who has added the public-share to his/her oC server should not see the shared folder on his/her files list.

### Actual behaviour
Despite the sharer has deleted the shared folder, the user who has added the public-share to his/her oC server can still see the shared folder.
But when he/she opens the shared folder and returns back to root directory, the shared folder is gone.

https://user-images.githubusercontent.com/52366632/119086471-3f179b00-ba25-11eb-99b1-46b127e01425.mp4

### Server configuration
**Operating system**: Ubuntu 20.04

**Web server:** Apache

**Database:** MySql

**PHP version:** 7.4

**ownCloud version:** 10.8.0 prealpha (git)

**Comment by saw-jan** [comment]
Or is it the expected behavior?

**Comment by saw-jan** [comment]
IMO, this is the expected behavior.
Since the shared folder's content cannot be accessed after deletion by the sharer and the folder gets auto-deleted after trying to access it, this behavior is OK.

CC @phil-davis (What do you think about it?)

**Comment by phil-davis** [comment]
I think this is reasonable behavior. The existence of the remote public link share is not going to be checked at every moment. The next time that `Brian` attempts to access it, the server works out that it no longer exists and stops showing it.

Behavior is OK - closing.
