### ISSUE TITLE
[QA] Add test scenarios for sharing the Shares folder

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#38777]
When the system-wide `share_folder` is defined, for example to `Shares` then users see a folder called `Shares` and their received shares are inside that.

A user can try to share the `Shares` folder. Add API tests that try to do that, and "document" the current behaviour. 

Then someone can decide what is the desired behaviour.

**Comment by phil-davis** [comment]
See https://github.com/owncloud/web/issues/5152 for an example where this was noticed in the web UI.

**Comment by dpakach** [comment]
Added API tests in https://github.com/owncloud/core/pull/38780
Added UI tests for web in  https://github.com/owncloud/web/pull/5156
