### ISSUE TITLE
Prevent `occ files:checksum:verify -r` from crashing on exception

### ISSUE THREAD

**Issue by JammingBen** [owncloud/core#38782]
### Steps to reproduce
1. Create an external storage for userA and add some files
2. Make the storage unavailable (not by removing the storage but by altering the access data or shutting down the remote server)
3. Run `occ files:checksum:verify -r`

### Expected behaviour
The command should do what it's supposed to do without crashing midterm because of any exception.

### Actual behaviour
The command crashes with `OCP\Files\StorageNotAvailableException`.

**Comment by jnweiger** [comment]
@JammingBen please compare #38979
