### ISSUE TITLE
Using ownCloud Web as the default frontend

### ISSUE THREAD

**Issue by pmaier1** [owncloud/core#38799]
As a service operator I want to make ownCloud Web the default frontend that users see when they log in to ownCloud for that they do not have to switch from "Classic Design" to the "New Design" first.

**Expected behavior**
1. Have ownCloud Web installed and properly set up so that it's working via the app switcher
2. Set `'defaultapp' => 'web',` in config.php (https://doc.owncloud.com/server/10.7/admin_manual/configuration/server/config_sample_php_parameters.html#define-the-default-app-to-open-on-user-login)
3. After logging in, users will see ownCloud Web's default view

**Actual behavior**
1. Have ownCloud Web installed and properly set up so that it's working via the app switcher
2. Set `'defaultapp' => 'web',` in config.php
3. After logging in, users see an error "The page isn't redirecting properly" (tested with Chromium 91)

![Screenshot from 2021-06-01 16-08-23](https://user-images.githubusercontent.com/21193500/120449614-df5bb100-c38f-11eb-97d5-af96ac0809ba.png)

**Comment by JammingBen** [comment]
@micbar We have a proper fix, but it would need a new release of the Web app. Is this sufficient regarding 10.8.0? Or should we rather implement a quick fix in OC core?

**Comment by micbar** [comment]
@JammingBen Let us do the fix in the web app
we could release anytime.
