### ISSUE TITLE
Recovery needed (urgent)

### ISSUE THREAD

**Issue by ElectronicArts-SRM** [owncloud/core#38814]
Hi Everyone. I am the Chief Systems Engineer at a large game development studio.
Let me explain my issue.
We are running OwnCloud 10.0.9. During a recent audit, one of our LDAP service accounts we used for storing files on NextCloud accidently got removed.

I need to find a way to move the files from the disabled LDAP user to a local OwnCloud user.
Now here's the issue: The LDAP account can't be re-enabled or setup again without approval from a senior executive (out of the question. takes weeks) and the SSH login for the OwnCloud machine is lost, hence the ancient 10.0.9 version. (and the SSH password reset requires a engineer to attend the DC and OPS team are highly against booting in to recovery mode, its already a unstable storage cluster with ~13pb.

The Owncloud account i need to recover has around 500gb of data on it. Mostly in zips. - any advice to convert the LDAP account to a local account OR move the files from the disabled account to a local account somehow, from the database? (i have superuser db access)

Any advice is highly appreciated! I can probably convince management to 'reward' whoever helps me!

**Comment by ElectronicArts-SRM** [comment]
Bumping..

**Comment by ho4ho** [comment]
Not bug / issue by ownCloud. Suggest: close

**Comment by ElectronicArts-SRM** [comment]
but i need help.

**Comment by cortho** [comment]
This is as bug tracker not a support forum. Visit https://central.owncloud.org/ instead.
