### ISSUE TITLE
Copy a folder to existing folder overwrites without any warning and auto rename

### ISSUE THREAD

**Issue by dpakach** [owncloud/core#38826]
### Steps to reproduce
1. Create two empty folders `new1`  and `new2`
2. In `new2` upload a file `lorem.txt`
3. Copy folder `new1` to `new2` using webdav
```
curl http://localhost/core/remote.php/webdav/new1 -XCOPY -H Destination:http://localhost/core/remote.php/webdav/new2 -vk -u admin:admin
```
### Expected behaviour
It should give some warning or create a autorenamed folder such as `new2 (2)`

### Actual behaviour
Request passes with 204 and the folder `new2` is overwritten with an empty folder. file `new2/lorem.txt` is lost.

the original folder `new2` with file `lorem.txt` is now in the trashbin.

### Server configuration
**Operating system**: ubuntu 20.04

**Web server:** apache2

**Database:** mysql

**PHP version:** 7.4

**ownCloud version:** (see ownCloud admin page) git latest

**Updated from an older ownCloud or fresh install:** yes

**Where did you install ownCloud from:** git

**Signing status (ownCloud 9.0 and above):**

**Comment by dpakach** [comment]
@phil-davis do you think this is expected behavior or bug?

**Comment by phil-davis** [comment]
> @phil-davis do you think this is expected behavior or bug?

https://datatracker.ietf.org/doc/html/rfc4918#section-9.8.4 COPY and Overwriting Destination Resources

1) "If a COPY request has an Overwrite header with a value of "F", and a resource exists at the Destination URL, the server MUST fail the request." - it is possible to request "do not overwrite" and the server should respect that, and do nothing if the copy would overwrite an existing resource.

2) "When a collection is overwritten, the membership of the destination collection after the successful COPY request MUST be the same membership as the source collection immediately before the COPY. Thus, merging the membership of the source and destination collections together in the destination is not a compliant behavior." - COPY is supposed to effectively remove any existing target resource and make a copy of the source resource (no "merging".

So it does seem correct that the target resource (if it exists) is moved to the trashbin.

**Comment by phil-davis** [comment]
If clients do not want to overwrite "unexpectedly" then they would need to set Overwrite "F", then check the response, and if it is fail, then do what they like to generate a new target for the copy (add (2) to the file/folder name, or whatever) and send the COPY again.

**Comment by phil-davis** [comment]
@dpakach Do core and OCIS behave differently?

**Comment by dpakach** [comment]
@phil-davis Yes, ocis behaves differently, it doesn't overwrites even if there are no headers set. So judging from the rfc, the behavior in ocis seems to be a bug.
