### ISSUE TITLE
tooltip opens link

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/core#38859]
### Steps to reproduce
1. login to ownCloud
2. select a file
3. choose "sharing" -> "user and group"
4. click on info - "i" on the right to the input field
5. new window opens

### Expected behaviour
on klick no new window should open (just the tooltip)

### Actual behaviour
new window opens

### Server configuration
**Operating system**:
macos

**Web server:**
apache

**Database:**

**PHP version:**

**ownCloud version:** 
10.7

### Client configuration
**Browser:**
chrome 91.0

**Operating system:**
macos

![image](https://user-images.githubusercontent.com/26610733/122236178-968f1680-cebe-11eb-8df9-a0b903f6ed16.png)

**Comment by micbar** [comment]
There should be a doc link to https://doc.owncloud.com/server/10.0/go.php?to=user-sharing-federated

**Comment by micbar** [comment]
Seems that the js templating is broken.

**Comment by micbar** [comment]
this should open a page on owncloud documentation https://doc.owncloud.com/server/10.0/go.php?to=user-sharing-federated

**Comment by hurradieweltgehtunter** [comment]
oh yes, just seen it. sry

**Comment by jnweiger** [comment]
> this should open a page on owncloud documentation https://doc.owncloud.com/server/10.0/go.php?to=user-sharing-federated

No. The link must go to https://doc.owncloud.com/server/10.8/go.php?to=user-sharing-federated
