### ISSUE TITLE
"remote" or "federated" share

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#38871]
1) On the webUI admin sharing settings page there are settings for "Set default expiration date for remote shares"
2) Further down that settings page there is a section about "Federation" and "Federated Cloud Sharing"
3) When a user shares with a user on a different cloud storage, the sharing tab uses the word "Federated" to describe the share type.

Item (1) seems inconsistent. Should the words be adjusted to replace "remote" with "federated"?

(and look for anywhere else where there is a mixed of "remote" and "federated")

Note: the capabilities API reports about these under a key `remote`

**Comment by JammingBen** [comment]
@pmaier1 Opinions here?

**Comment by pmaier1** [comment]
"Remote" is the old wording. We changed that to "Federated" some time ago. That's the current state that should be consistent. In the future we want to call it "on another cloud" or "on other clouds" to make it more user-friendly.

**Comment by phil-davis** [comment]
I made a PR to change what I could find of "front-facing" things from "remote" to "federated"  without breaking any APIs.

That would need to be merged well before a release, so that translations have time to happen. So if we want to do this, then that would be after 10.8.

**Comment by pmaier1** [comment]
Thanks. I'm pretty sure that we already have translation strings as "federated" exists for some time.

**Comment by phil-davis** [comment]
There are a couple of sentences that has "remote" embedded in them, that will now have "federated" in them. The whole sentence has to be "re-translated" in each language. Usually that will just be replacing 1 word in the sentence. But someone has to do the action in Transifex for every language.

**Comment by jnweiger** [comment]
@micbar Seen two remaining translatable(!) strings that say 'remote share'

./apps/files_sharing/lib/Activity.php:					return (string) $l->t('Received remote share from %1$s', $params);
./apps/files_sharing/lib/Activity.php:				return (string) $l->t('Received remote share from %s', $params);

Thus the translations there also speak about 

./apps/files_sharing/l10n/de.json:    "Received remote share from %1$s" : "Du hast eine Remotefreigabe von %1$s erhalten.",
./apps/files_sharing/l10n/de.json:    "Received remote share from %s" : "Du hast eine Remotefreigabe von %s erhalten.",

Suggest to also say federated there.

**Comment by phil-davis** [comment]
Note: those were added in PR #38880 which was merged on 2021-06-23. 

I created PR #38877 on 2021-06-22, just one day before. So that is why I would not have found these in my search of the code-base.

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/core/pull/39578. Not sure why the auto linking does not work currently, maybe because were not merging to master? 🤔
