### ISSUE TITLE
[QA] Public link password protection web shows a misplaced arrow in mobile browser

### ISSUE THREAD

**Issue by jesmrec** [owncloud/core#38893]
### Steps to reproduce

1. Create a public link with password
2. In a mobile device, copy the link and paste it in a web browser

### Actual behaviour

The arrow icon to submit the password is out of place (also in landscape orientation):

| Safari (iOS) | Firefox (Android)| Chrome (Android) |
|:-:|:-:|:-:|
|![Screen Shot 2021-06-25 at 13 46 36](https://user-images.githubusercontent.com/14894746/123424022-911d8480-d5c0-11eb-8b16-fe1fc137f159.png)|![device-2021-06-25-140558](https://user-images.githubusercontent.com/14894746/123423649-1d7b7780-d5c0-11eb-9285-3882866ed49c.png)|![device-2021-06-25-141929](https://user-images.githubusercontent.com/14894746/123423922-70edc580-d5c0-11eb-9bfa-abe6cab13554.png)|

### Expected behaviour

As before, it should be placed on the right side of the enter password field

![Screen Shot 2021-06-25 at 13 48 25](https://user-images.githubusercontent.com/14894746/123424217-db066a80-d5c0-11eb-8813-05b765045677.png)

__________

Server: `10.8.0-beta1` from docker image

Android: Pixel2 v11

iOS: iPhoneXR v14.6

**Comment by JanAckermann** [comment]
@hurradieweltgehtunter @micbar @pmaier1  should we change this arrow to a button? to be more consistent?

**Comment by hurradieweltgehtunter** [comment]
Good catch. Yeah let's put a button there instead of the arrow.

**Comment by JanAckermann** [comment]
on it
