### ISSUE TITLE
Translation of Cheers is wrong in Dutch

### ISSUE THREAD

**Issue by voroyam** [owncloud/core#38892]
A customer noticed issues with the dutch translation:

> the translation for ‘Cheers’ in Dutch should be ’Tot ziens’ instead of ‘Proficiat’.

@DeepDiver1975 

He also noticed other issues, but they weren't as high prio as the dutch one.

> There are several more wrong translations of ‘Cheers’ in other languages. Luxemburgish, Norwegian, Azerbaijani and Romanian have the meaning ‘Prost’ as in a toast for a drink, Portuguese/Portugal has the meaning “Congratulations’.
> 
> Those are not the most important languages. But if you want to tidy this up, you should tell the translators that ownCloud uses ‘Cheers’ in the meaning of ‘Goodbye’ and not in the meaning of ’Thank you’ or as a toast for a drink. Definitely not as ‘Congratulations’.

**Comment by phil-davis** [comment]
Is there some way that we can provide "translation hints"  in the code that will be visible to translators on Transifex?
(Maybe some sort of code comment tagging or?)

**Comment by mmattel** [comment]
Please highlight where we do have in docs a dutch traslation, this is new to me.
If it belongs to core or an app, you have to change the relevant string on transifex, wait for an approval respectively notify eg @ChrisEdS and if approved wait for the next core release.

@EParzefall fyi

**Comment by DeepDiver1975** [comment]
> Is there some way that we can provide "translation hints" in the code that will be visible to translators on Transifex?
> (Maybe some sort of code comment tagging or?)

translation hints are in place already: https://github.com/owncloud/core/blob/eebd754771a99bc44820eb67a6d57cea238e6b86/settings/templates/email.new_user_plain_text.php#L4

**Comment by DeepDiver1975** [comment]
And hints to show up on transifex .... what else can we do? :shrug: 


![Screenshot from 2021-07-16 11-33-52](https://user-images.githubusercontent.com/1005065/125926913-4f8f7426-b1e9-4487-a394-934f56696649.png)

**Comment by phil-davis** [comment]
> translation hints are in place already: 

Great - now I realize how to "pass across" translation hints. As you say, now how to get translators to understand and pay attention to the hints ;)

**Comment by voroyam** [comment]
I feel like we have gotten away from the actual point of this issue.

Customer asked to change, not suggest, the string in the current transfix translation for certain words. Can we fulfil this request?

**Comment by DeepDiver1975** [comment]
> Can we fulfil this request?

Join dutch translation team and fix it .... translations are community effort .... 
Anybody speaking Dutch?

**Comment by phil-davis** [comment]
- Go to The Netherlands
- Drink beer with Dutch people
- Say "Cheers" and learn what they say in this situation
- Then explain to them that there are other uses of "Cheers"
- Login to Transifex while you are sitting at the bar.
- Between you and them, sort out the appropriate translation of "Cheers" in each context

Go to the top and repeat for each country. Try not to drink too much beer on the trip ;)

**Comment by voroyam** [comment]
Can we stay on topic and limit the suggestions to what can be actually done?
If I write something out of professional context my comment get's deleted and I get a talking to. Does not apply for others as I see...

Again, this is the original simple request from the customer:

In the Language Dutch
for the English word ‘Cheers’
Change ‘Proficiat’
To ’Tot ziens’

This and this alone was the original topic. If you want I can remove the part that was optional.

Please show me how I can do it, put me in the right team or show me how I can join the dutch team. I want to solve this for my customer. So far I don't know how.

**Comment by ChrisEdS** [comment]
Let me change that for you.

**Comment by ChrisEdS** [comment]
Done. Will be in the next app versions.

**Comment by voroyam** [comment]
> Let me change that for you.

can you show me how to do it so I can do it next time?

**Comment by phil-davis** [comment]
The changes came across into core `master` last night:
https://github.com/owncloud/core/commit/1379b63bee0d4da4b9338a13d6a81f7903234bbf

They have missed being in 10.8.0 release. If someone really needs the updated translation in 10.8.0 release, then the "[tx] updated from transifex" commits need to be backported to the `release-10.8.0` branch.
