### ISSUE TITLE
[QA] add remote share dialog has confusion choice

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38932]
Seen with oc10.8.0-beta1 and wopi-1.5.0 rc3
* Create a public link with an office document
* open the link in a new browser session
* click the add to link in the top right title bar.
* after logging in, the user sees

![image](https://user-images.githubusercontent.com/1108546/124305612-a1f06c00-db65-11eb-8dd3-f82e209da690.png)

What is the difference between the answer "Add remote share" and "Yes" ?   -- (Well, the "Add remote share" button acts as "No"!)

Expected behaviour: The choice is between "No" and "Yes".

**Comment by jnweiger** [comment]
Trying the same again, the answers are different:

![image](https://user-images.githubusercontent.com/1108546/124306220-65714000-db66-11eb-9fd2-c6248fa999f7.png)

That makes more sense, but why was it different in the first try?

**Comment by jnweiger** [comment]
Also: When adding the share to the same server, where it originated from, we should not call it a Remote share.

Suggested wording for that case:

User share
Do you want to add the share new_mso.docx from admin?

**Comment by JanAckermann** [comment]
@jnweiger is this related to wopi or does this happen with every remote share or maybe every share (if accept is required) ?

**Comment by jnweiger** [comment]
I had observed that when sending from a machine, where wopi is active, to the same machine.

Re-testing from demo.owncloud.org to the wopi instance. Looks good:
![image](https://user-images.githubusercontent.com/1108546/124655717-873d3080-dea0-11eb-9b8a-150e239c6cc7.png)

Re-testing from 10.8.0-beta2 without wopi enabled to the same machine. Looks good too:
![image](https://user-images.githubusercontent.com/1108546/124656218-32e68080-dea1-11eb-91e3-6e217cb8d73a.png)

I have not tested any other combinations yet. So far, it indeed looks like it is somehow wopi-related.

**Comment by JanAckermann** [comment]
And this problem is still existing? I mean this could be a caching problem ?

**Comment by JanAckermann** [comment]
@jnweiger For me this is error can be caused by 2 issues:
1. Caching issue
2. Some other javascript errors which makes the other code stop to work

Can you invalidate your cache and try again, is the error reproducible ? If yes any js errors in browser console ?

**Comment by micbar** [comment]
@jnweiger so far we could not confirm it. Can we close?
