### ISSUE TITLE
[QA] Password protected public link has no button to click

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38933]
Seen with server 10.8.0-beta1 and wopi-1.5.0-rc3, using firefox 89.0

* create a password protected public link from an office file
* in a fresh brower session try open the link
* a password entry appears, without a button to click

![image](https://user-images.githubusercontent.com/1108546/124308032-ef220d00-db68-11eb-8ce3-86699014e2df.png)

There is a half hidden right-arrow at the top center of the password field...
One has to click to the very left of the field in order to enter some text. Clicking in the middle automatically submits.

Expected behaviour: A nice bright blue "[Enter]" or "[Submit]" button is there, similar to the "[Login]" button we now have.

**Comment by phil-davis** [comment]
Note: this should be fixed by #38894 

`10.8.0-beta1` is getting "old". We really need to release `beta2` (or `rc1`  or whatever it will be called) so that testing can continue with the latest fixxes.
