### ISSUE TITLE
[QA] Plus (+) button is no longer square

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/core#38945]
### Expected behaviour
In version 10.7 the plus button to upload things was sqare.

![image](https://user-images.githubusercontent.com/33026403/124588888-a06ebe80-de59-11eb-992b-11c59c5f4311.png)

### Actual behaviour
The button looks like this in the upcoming version.

![image](https://user-images.githubusercontent.com/33026403/124588959-b7151580-de59-11eb-8ea0-a337bec1c489.png)

### Server configuration
**ownCloud version:** 
ownCloud 10.8 Beta2

**Comment by jnweiger** [comment]
`docker run owncloud/server:10.8.0-beta1` also shows me the perfect square button from 10.7 -- seems the regression was introduced in beta2 only.

**Comment by phil-davis** [comment]
Introduced by https://github.com/owncloud/core/pull/38928

If I locally go 1 commit before that in core master:
```
git checkout 82f26997e3b0d1197c745cd71f498cc69c5a82ea
```

And refresh the files page, then the button is square.
