### ISSUE TITLE
[QA] message confirms invitation mail as sent, even when mailer is not configured

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38955]
Seen in 10.8.0 bets2

Try this on a docker, where no mailer is configured:

* admin creates a new user (specifying an email address
* admin gets a warning, that the "password reset mail" (check that wording) could not be sent. OK
* admin tries to resend the invitation mail. He sees a friednly send confirmation:
![image](https://user-images.githubusercontent.com/1108546/124844201-f5165480-df93-11eb-9713-1a11d9699354.png)
* in reality no mail was sent. BAD.

**Comment by JanAckermann** [comment]
We reuse the resendToken, if think this is the wrong approach, we should implement a new endpoint and this should also be called by admins only

**Comment by JanAckermann** [comment]
Fixed via https://github.com/owncloud/core/pull/38963
