### ISSUE TITLE
[QA] broken links on the first login banner

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38957]
Seen in 10.8.0 beta2

When a user logs in for the first time, he sees a banner like this:
![image](https://user-images.githubusercontent.com/1108546/124847585-7ae9ce00-df9b-11eb-8128-cbaf806f58ec.png)

The button "Connect your calendar" has a broken link:  https://doc.owncloud.org/server/10.8/go.php?to=user-sync-calendars
The button "Connect your contacts" has a broken link: https://doc.owncloud.org/server/10.8/go.php?to=user-sync-contacts

**Comment by jnweiger** [comment]
The "Desktop app" button links to https://owncloud.org/install/#install-clients -- only server downloads are advertised there. BAD

It should link to https://owncloud.com/desktop-app/

**Comment by JanAckermann** [comment]
@mmattel can you clarify when the 10.8 docs will be accessible ?`

**Comment by JanAckermann** [comment]
> The "Desktop app" button links to https://owncloud.org/install/#install-clients -- only server downloads are advertised there. BAD

It should link to https://owncloud.com/desktop-app/

Iam on that

**Comment by mmattel** [comment]
@JanAckermann the 10.8 docs are already available (since sunday). The go.php issue which is outside docs has been fixed by @xoxys already. Please retry and tell if this is still an issue.

**Comment by JanAckermann** [comment]
@mmattel well if you open the url: https://doc.owncloud.org/server/10.8/go.php?to=user-sync-contacts
you will get a 404

**Comment by mmattel** [comment]
@xoxys can you pls take a look on, thanks

**Comment by xoxys** [comment]
As mentioned internally already, please set up a short meeting to discuss the setup in general...

**Comment by jnweiger** [comment]
confirmed fixed in 10.9.0 beta1

(Still wondering why we advertise contacts and calender apps so prominently, and don't speak about anything that we update more frequently.)
