### ISSUE TITLE
[QA] resent invitation email invalidates original invitation link

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38954]
## Seen in 10.8.0 beta2

* admin creates a new user account and only specifies username and email.
* the system sends out an email to the user 
![image](https://user-images.githubusercontent.com/1108546/124842596-3f95d200-df90-11eb-9879-0ab582d05cd2.png)
* admin hits the mail envelope icon near the trashbin. Another email is generated with a different link.
* before the first invitaiton timeout expires, user attends to his mailbox and chooses the link from the first invitation email. It does not work. BAD.

Expected behaviour:  the re-sent mail has the same link. The expiration is extended accordingly.

**Comment by JanAckermann** [comment]
@C0rby what does your security alerts tell about extending tokens? I would say it is not best practice

**Comment by C0rby** [comment]
Yeah I think in this case invalidating the old links is good from a security PoV.

**Comment by micbar** [comment]
Also good IMO.
