### ISSUE TITLE
Unintentinal delete caused by clients becomes dangerous through trashbin skip

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38953]
Seen in 10.8.0 beta2

Given the nature of desktop clients, it can happen that a delete is unintentional and only discovered much later.
Traditionally the ownCloud server has all the files in the trashbin, that makes it easy to recover from unintended deletes. With the introduction of the config.php settings
trashbin_skip_directories, trashbin_skip_extensions, and trashbin_skip_size_threshold this safety net is compromised.

Enhancement ideas:
 - To raise awareness of the new feature: notify user whenever trashbin was skipped.
 - explicit skip
   - expand the files's three dot menu in the web UI to have two delete options: The normal delete, and a hard delete that skips the trashbin.
   - allow for a popup in the WebUI, asking for skip trashbin, when the deleted file would not fit into the trashbin.
 - refined policies
   - allow to distinguish between delete through a received share or delete by owner.
   - allow to distinguish between delete from client versus delete from Web UI.
   - allow to distinguish between an apparent delete (client moves an item out of the sync root) and a real delete.
 
Usecase "Delete a file bigger than the trashbin storage space" would benefit from the explicit skip options or refined policies while keeping the risk for unrecoverable deletes low.

**Comment by jnweiger** [comment]
Default in 10.8.0 beta2 currently is: everything still goes through trashbin. GOOD.

**Comment by gabi18** [comment]
I also see that the trash bin skip could cause unexpected results for the desktop client user.
So far the user can rely on the trash bin and all unintended deletes can be restored on the server.

With certain rules configured on the server to skip the trash bin this behavior changes with the user probably not aware which files/folders are skipped.

Beside unintended deletes from user side there might be also problems with the desktop client (
https://github.com/owncloud/client/issues/8610).

**Comment by JanAckermann** [comment]
Well, I get the point: 'Communicate to the user'
But this is more an admin setting and he should communicate it to the users (besides we can also add a hint)...

IHMO this setting will be only set in special cases by the admins

**Comment by micbar** [comment]
will not be advertised to use right now.

We currently only need it for the backup use case.

Closing  now

@hodyroff @pmaier1
