### ISSUE TITLE
[QA] Cannot confirm: Fix tab headers on small display ratio

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38967]
Seen in oc10.8.0 beta2

The desited effects of https://github.com/owncloud/core/pull/38653 cannot be seen.
Tried android and firefox, Both look like what was described as 'Before':

![image](https://user-images.githubusercontent.com/1108546/125003350-54896880-e057-11eb-9564-79be9f932e45.png)
![image](https://user-images.githubusercontent.com/1108546/125003364-5a7f4980-e057-11eb-9551-3a48547ad717.png)

**Comment by JanAckermann** [comment]
@jnweiger The first screenshot is definitely not how it looks before:
![image](https://user-images.githubusercontent.com/26169327/125043450-39404c80-e09b-11eb-85c5-4f7d7081eb00.png)

**Comment by micbar** [comment]
Thanks @JanAckermann I can confirm it
