### ISSUE TITLE
[QA] auto:automation creates my files, when workflow and files_lifecycle are active

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38966]
Seen in oc10.8.0 beta2 while testing  https://github.com/owncloud/enterprise/issues/4222

* enabe workflow app
* upload a file
* disable workflow app
* upload a file
* enable workflow app
* upload a file

Activity shows that the files were crated alternating by myself, 'You' and by 'auto:automation'
![image](https://user-images.githubusercontent.com/1108546/125002549-83064400-e055-11eb-9d8f-a8c731efe32a.png)

Expected behaviour: Automation never creates files. I do.

**Comment by JanAckermann** [comment]
This is not good, need to fix it before release the automation user will be written in database and can cause faulty entries

**Comment by JanAckermann** [comment]
I am not quite able to reproduce it with the given steps above, 
can you detail them?

1. Does the error occurs with files_lifecycle enabled/disabled 
2. Do you set any workflow
3. auto:automation user is always the issuer  if workflow app is enabled ? 

If you could provide more steps to reproduce it would be much easier

**Comment by JanAckermann** [comment]
@jvillafanez We call a lot of $this->manager->restoreAgentAuthor(); but it might be possible that a call above will throw an error and the author won't be reset, maybe we should take care ?

**Comment by jvillafanez** [comment]
> @jvillafanez We call a lot of $this->manager->restoreAgentAuthor(); but it might be possible that a call above will throw an error and the author won't be reset, maybe we should take care with try...catch...finally ?

Definitely. We have to restore the original author no matter what.

**Comment by JanAckermann** [comment]
Fixed via: https://github.com/owncloud/core/pull/38970 and https://github.com/owncloud/workflow/pull/264#event-5000788250 workflow 0.5.4 required

**Comment by jnweiger** [comment]
Confirmed fixed in 0.5.3-rc1
