### ISSUE TITLE
[Tests-only] Add more test coverage for listing files with PROPFIND 

### ISSUE THREAD

**Issue by dpakach** [owncloud/core#38981]
We mostly have tests that test the existence of each files which sends request to the dav endpoint of each file/folder. But we dont have tests that try to get the entire file list with webdav.

We need to add tests to get the list of files from webdav
- Test getting files list on user files, public link, trashbin
- Use Depth Header to get the nested files/folders

**Comment by phil-davis** [comment]
Note: the lack of API test coverage of PROPFIND was noticed in `owncloud/web` tests, where we happened to use this kind of PROPFIND API in `webdavHelper.js` https://github.com/owncloud/web/pull/5511

I would have been nicer if the regression in reva-OCIS was noticed by core API tests. So adding coverage here is good.
