### ISSUE TITLE
[QA] over-eager foldername elipsis

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38988]
Seen with 10.8.0 beta2

PR #38748 works into using more space for filenames, and less for meta data, when horizontal space is limited. On my adroid 10, I see a result that is half way between the before and after screenshots.

![image](https://user-images.githubusercontent.com/1108546/125532181-2f25ea87-7a65-448f-a18d-7f49646086f8.png)

A very short folder name `WND` gets truncated after the first character `W...`,  whereas the folder name `beta2adminphotos` is truncated only after 12 chars. 
Sharefolder2, Sharefolder Documents, and demo_photos have exactly their last three characters replaced with '...' -- that indicates a broken algorithm.

It seems that there is a difference between filename and folder names. Filenames can use the available space 

![image](https://user-images.githubusercontent.com/1108546/125532519-f16d117e-d77e-44bf-92a4-04ddad084960.png)

Expected behavior: do not truncate without need. In the sceenhots, almost all names would have fit.

**Comment by JanAckermann** [comment]
@jnweiger Yep, unfortunately, @ChrisEdS has already reported this issue, can't wrap my head around whats have been change since my PR :(

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/core/pull/39009
