### ISSUE TITLE
[QA] doctrine/dbal is only 2.12.2-DEV

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#38990]
seen in oc 10.8.0-beta2

PR https://github.com/owncloud/core/pull/38647 claims to update octrine/dbal to 2.13.1

But lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Version.php says
```
class Version
{
    /**
     * Current Doctrine Version.
     */
    public const VERSION = '2.12.2-DEV';

```

Is this the expected version?

**Comment by phil-davis** [comment]
The version is incorrect in the release. I  raised issue https://github.com/doctrine/dbal/issues/4711
And made PR https://github.com/doctrine/dbal/pull/4712

IMO this constant does not effect anything "real".

**Comment by JanAckermann** [comment]
Does not effect anything, hopefully they will fix it in minor patch, your level of finding those things is outstanding :+1:

Closing due to no (bad) effect
