### ISSUE TITLE
Add test coverage for Allow public link sharing only for certain groups

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39002]
Related issue #3632

Make a branch on top of PR #38980 `enterprise/issues/3632` and add acceptance test coverage.

1) Add API tests
- when a user is in a group that is "allowed to create public links" then they should be able to create a public link
- if not in any of the groups then they should get a 4xx HTTP status when they try to create a public link.
- if not in any of the groups but have existing Public Links then they should still be able to edit and/or delete their existing Public Links. But they should not be able to create a new public link.

2) Add UI tests

- when a user is in a group that is "allowed to create public links" then they should be able to create a public link with the existing UI workflow. 
- if they are not in any of the groups, then they should not even see the "Public Links" tab when they open the sharing panel for a resource.
- if they are not in any of the groups, and they had some Public Links before the settings were enabled, then they should still be able to edit and/or delete their existing Public Links. But they should not be able to create a new public link.
- if they are in one of the "allowed to create public links", have created Public Link shares, then get removed from the "allowed" groups, then they should still be able to edit and/or delete their existing Public Links. But they should not be able to create a new public link.

**Comment by kiranparajuli589** [comment]
The task stated in the issue description has been completed.
