### ISSUE TITLE
[QA] login page says 'update' needed, when an 'upgrade' is needed

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39028]
Seen while upgrading from 10.7.0 to 10.8.0 RC1

![image](https://user-images.githubusercontent.com/1108546/126232222-0205bea8-8100-44c1-9a29-e674eaa9ebf4.png)

This message is inconsistent with the occ command required. the occ command reads 'upgrade', the message reads 'update'.

Expected behaviour: same wording. Use 'upgrade' in the message.

**Comment by phil-davis** [comment]
FYI: This text is in https://github.com/owncloud/core/blob/master/core/templates/update.use-cli.php
And has been this way ever since PR #23922 was merged on 18 Apr 2016.
