### ISSUE TITLE
Update from core version 10.6 to 10.7 crashed

### ISSUE THREAD

**Issue by zubanst** [owncloud/core#39040]
### Steps to reproduce
 Owncloud version 10.6, login as admin and start the updater

### Expected behaviour
Updater completes the update

### Actual behaviour
Updater starts than crashes and leaves the site in maintenance. The issue is the incompatibility with CAS 1.9.0. Even thought there is an incompatibility, updater should do a kind of dry run, and not leave the server in a unusable state. This is very disturbing for production environments. Fortunately, the site could be rolled back from a backup. Updater should be fixed to prevent update in case update would fail. This is a serious issue.

### Server configuration
**Operating system**:
Ubuntu 18.04 LTS
**Web server:**
Apache 2.4.29
**Database:**
Mysql  5.7.34
**PHP version:**
PHP 7.2.24
**ownCloud version:** (see ownCloud admin page)
10.6.0.5
**Updated from an older ownCloud or fresh install:**
Updated from 10.5
**Where did you install ownCloud from:**
Ownclud web site
**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and put the link here.
```
No errors have been found.
[config_report_20210721.zip](https://github.com/owncloud/core/files/6853527/config_report_20210721.zip)

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**
CAS 1.9.0
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by cortho** [comment]
In the documentation at https://doc.owncloud.com/server/admin_manual/maintenance/manual_upgrade.html#review-third-party-apps it reads "Review any installed third-party apps for compatibility with the new ownCloud release. Ensure that they are all disabled before beginning the upgrade."
At marketplace the app states compatibility up to ownCloud 10.6, see https://marketplace.owncloud.com/apps/user_cas

However, having the upgrader stop with this error message before performing any upgrades could help novices or users that did not read the documentation.

**Comment by ho4ho** [comment]
Looking related by https://github.com/owncloud/updater/issues/481 but unknownly closed

Could solved / duplicate by: https://github.com/owncloud/core/issues/31180

**Comment by VicDeo** [comment]
well, if the app is stated as compatible but  is incompatible it's an app issue.

**Comment by ho4ho** [comment]
> well, if the app is stated as compatible but is incompatible it's an app issue.

Looked like app states incompatible by 10.7:

https://github.com/felixrupp/user_cas/blob/1.9.0/appinfo/info.xml#L32

so really problem by app?

**Comment by JammingBen** [comment]
As the comments above have already mentioned, the CAS app is supported for OC versions <= 10.6. Also see https://marketplace.owncloud.com/apps/user_cas -> closing here as this is not a core issue.

If you need to run the app in versions >= 10.7, please create an issue in https://github.com/felixrupp/user_cas/issues.
