### ISSUE TITLE
PHP unit test OwncloudTest sometimes fails

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39046]
Here is an example from last night:

https://drone.owncloud.com/owncloud/core/31438/31/10
```
PHPUnit 8.5.18 by Sebastian Bergmann and contributors.

Runtime:       PHPDBG 7.2.34-23+ubuntu18.04.1+deb.sury.org+1
Configuration: /drone/src/tests/phpunit-autotest-external.xml

.............................................S.....E............. 65 / 85 ( 76%)
....................                                              85 / 85 (100%)

Time: 1.86 minutes, Memory: 52.63 MB

There was 1 error:

1) OCA\Files_External\Tests\Storage\OwncloudTest::testFOpen with data set #4 ('spéciäl fäile')
OCP\Files\StorageNotAvailableException: Sabre\HTTP\ClientHttpException: Internal Server Error

/drone/src/lib/private/Files/Storage/DAV.php:901
/drone/src/lib/private/Files/Storage/DAV.php:859
/drone/src/lib/private/Files/Storage/DAV.php:694
/drone/src/lib/private/Files/Storage/DAV.php:188
/drone/src/apps/files_external/tests/Storage/OwncloudTest.php:55

```

I have noticed this a couple of times recently. There is always "Internal Server Error" reported.

**Comment by phil-davis** [comment]
Here is another example:
https://drone.owncloud.com/owncloud/core/31461/35/10
```
1) OCA\Files_External\Tests\Storage\OwncloudTest::testRenameOverWriteFile
OCP\Files\StorageNotAvailableException: Sabre\HTTP\ClientHttpException: Internal Server Error

/drone/src/lib/private/Files/Storage/DAV.php:901
/drone/src/lib/private/Files/Storage/DAV.php:859
/drone/src/lib/private/Files/Storage/DAV.php:694
/drone/src/lib/private/Files/Storage/DAV.php:188
/drone/src/apps/files_external/tests/Storage/OwncloudTest.php:55
```

This time with a different test case.

**Comment by phil-davis** [comment]
Another example this morning:
https://drone.owncloud.com/owncloud/core/31535/34/10
```
There was 1 error:

1) OCA\Files_External\Tests\Storage\OwncloudTest::testCopyFromSameStorage with data set #3 ('/source with space.txt', '/target with space.txt')
OCP\Files\StorageNotAvailableException: Sabre\HTTP\ClientHttpException: Internal Server Error

/drone/src/lib/private/Files/Storage/DAV.php:902
/drone/src/lib/private/Files/Storage/DAV.php:860
/drone/src/lib/private/Files/Storage/DAV.php:695
/drone/src/lib/private/Files/Storage/DAV.php:188
/drone/src/apps/files_external/tests/Storage/OwncloudTest.php:55
```

**Comment by JammingBen** [comment]
@phil-davis When was the first time this error occurred? Did it happen before the 10.8 release?

**Comment by phil-davis** [comment]
> @phil-davis When was the first time this error occurred? Did it happen before the 10.8 release?

Yes, I have seen it before 10.8. But I am not sure exactly when I first noticed it - maybe 2 or 3 weeks ago?

**Comment by JammingBen** [comment]
The error is a `Doctrine\DBAL\Exception\LockWaitTimeoutException`. It seems that the database has tiny variations in performance during each pipeline run. So sometimes, we run into this exception as the database is still busy with another transaction.

The DAV tests already provide a `wait()` method to bypass these kind of errors. I will try to fix the issue this way. 

```
<s:exception>Doctrine\DBAL\Exception\LockWaitTimeoutException</s:exception>
--
116 | <s:message>An exception occurred while executing 'UPDATE "oc_filecache" SET "storage" = ?, "path" = ?, "path_hash" = ? WHERE "fileid" = ?' with params [3, "files_trashbin\/files\/fO50WWmjGjj9g.d1627470002\/source with space.txt", "c27f06924f223e3bc259c5a134643614", "108"]:
117 |  
118 | SQLSTATE[HY000]: General error: 5 database is locked</s:message>
```

Also see https://drone.owncloud.com/owncloud/core/31606/1/10

**Comment by JammingBen** [comment]
@phil-davis https://drone.owncloud.com/owncloud/core/31626/30/10 -> Doesn't seem to be fixed :(

**Comment by phil-davis** [comment]
> Doesn't seem to be fixed :(

That's sad - that merge CI is from an up-to-date merge that should have the "fix".

What to do?  Hack the wait to be longer?

**Comment by JammingBen** [comment]
> What to do? Hack the wait to be longer?

I would try this by increasing the wait to `0.5`. Either way I don't like this approach, but it would be interesting to see if it helps.

Is it an option to run those external storage tests with MySQL or Postgres? Maybe we run into limitations of SQLite with its concurrency handling.

**Comment by phil-davis** [comment]
> Is it an option to run those external storage tests with MySQL or Postgres? Maybe we run into limitations of SQLite with its concurrency handling.

I am not familiar with that. I won't have a chance to look before next week - so feel free to dig into it.

**Comment by phil-davis** [comment]
Good - hopefully this attempt succeeds! We will know in a few days, if there are no more fails.
