### ISSUE TITLE
Login page has vertical scroll bar

### ISSUE THREAD

**Issue by xoxys** [owncloud/core#39043]
### Steps to reproduce
1. `docker run -p 8080:8080 -it owncloud/server:latest`
2. Open localhost:8080 in your browser

### Expected behavior
No vertical scroll bar.

### Actual behavior
Scroll bar on the right side.

Firefox:
![image](https://user-images.githubusercontent.com/3391958/126502606-691edd93-3df4-4579-b80b-cd4eb50f484f.png)

Chrome:
![image](https://user-images.githubusercontent.com/3391958/126502746-a63731ad-54f0-4045-af2a-75b7befcbe65.png)

**Comment by JanAckermann** [comment]
@hurradieweltgehtunter FYI

**Comment by hurradieweltgehtunter** [comment]
This is intended because some constellations with error notices or other login forms exceed the screens height. This would result in a jump of the forms location (because the scroll bar will be added). To prevent his "jump" the scrollbar is displayed any time.

**Comment by xoxys** [comment]
Interesting. In this case, feel free to close the issue.

**Comment by hurradieweltgehtunter** [comment]
@xoxys see PR for improvement fix
