### ISSUE TITLE
Atualizando para 10.8.0

### ISSUE THREAD

**Issue by orivaldo09** [owncloud/core#39081]
Preparando atualização
Definir o nível de log para debug
Ativar modo de manutenção
Aviso de defesa: Você tem aplicativos incompatíveis ou ausentes ativados que não puderam ser encontrados ou atualizados através do marketplace.
Aviso de restrições: Instale ou atualize os seguintes aplicativos manualmente ou desative-os com: occ app: disable files_videoplayer
Aviso de reparação:For manually updating, see https://doc.owncloud.com/server/10.8/go.php?to=admin-marketplace-apps
OC \ RepairException: A atualização não é possível

**Comment by ho4ho** [comment]
Duplicate by https://github.com/owncloud/core/issues/39040 + many other: https://github.com/owncloud/core/issues/32388, https://github.com/owncloud/core/issues/32376, https://github.com/owncloud/core/issues/32374, https://github.com/owncloud/core/issues/32338, https://github.com/owncloud/core/issues/32265

**Comment by phil-davis** [comment]
Translation:
Preparing update
Set logging level for debug
Enable maintenance mode
Defense notice: You have incompatible or missing apps activated that could not be found or updated through the marketplace.
Restrictions notice: Install or update the following apps manually or disable them with: occ app: disable files_videoplayer
Repair Notice:For manually updating, see https://doc.owncloud.com/server/10.8/go.php?to=admin-marketplace-apps
OC \ RepairException: Update is not possible

**Comment by ho4ho** [comment]
Still duplicate by issues linking upper.

**Comment by JammingBen** [comment]
@orivaldo09 

Please disable the `files_videoplayer` app manually and then try running the update again. You can do so via CLI:

`occ app:disable files_videoplayer`

or via database query if you don't have access via CLI:

`UPDATE oc_appconfig SET configvalue = 'no' WHERE configkey = 'enabled' AND appid IN ('files_videoplayer');`

**Comment by JammingBen** [comment]
Closing this one as no interaction happened for nearly two months now. Feel free to re-open if needed.
