### ISSUE TITLE
Federated share selection dropdown "Add to cloud" won't close 

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/core#39093]
### Steps to reproduce
1. Open a file shared with a public link
2. Click on button "Add to cloud.com" (top right corner)
3. Selection dropdown opens
4. Click somewhere else

### Expected behaviour
Selection dropdown should be closed

### Actual behaviour
Selection dropdown stays

![grafik](https://user-images.githubusercontent.com/16665512/128335395-56530fca-19e4-4ff6-842c-c22530c32dd9.png)

**Comment by JanAckermann** [comment]
should be already fixed with: 
https://github.com/owncloud/core/pull/38942

Could you check ?

**Comment by hurradieweltgehtunter** [comment]
You're right. Clicking on the blue header bar closes the menu.
Seems the PDF viewport isn't propagating the event properly? meh ...

**Comment by JanAckermann** [comment]
Yes, typically click events get eaten by iFrames but the linked PR should fix it.
