### ISSUE TITLE
Add acceptance test case for syncing files with UTF-8 names

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39095]
See issue https://github.com/owncloud/enterprise/issues/4692 and PR https://github.com/owncloud/core/pull/39088

The code for v2 "new" chunking NG was changed so that maximum-length file names can be uploaded with this chunking. Previously filenames that reached the limit of about 255 characters would fail to upload with chunking, because the the internal implementation of storing the chunks would make longer filenames for the chunking parts.

1) Make an extra scenario that demonstrates uploading the maximum-length filename possible. The scenario can probably go in https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdavUpload2/uploadFileUsingNewChunking.feature

2) Also make a scenario for "old" v1 chunking that demonstrates uploading the maximum-length filename possible fpr v1 chunking. The scenario can probably go in https://github.com/owncloud/core/blob/master/tests/acceptance/features/apiWebdavUpload2/uploadFileUsingOldChunking.feature

This will prevent regressions of the max filename length.

**Comment by cortho** [comment]
@phil-davis we have met this issue as well, so there are some questions regarding the PR
* What is the official maximum file length? I have spent quite a time in the docs and didn't find any value. In the `oc_filecache` table path has got a size of 4000 
* So if this is the limit the test file name in the test is far too short. Our customer faces this issue with the following string:
`2017 История России. XX век. Деградация тоталитарного государства и движение к новой России (1953—2008). Том III, Андрей Борисович Зубов.epub_1.png`

**Comment by phil-davis** [comment]
We have "documented"  the maximum file name length by making a test scenario that "just passes". If you add 1 character to the file name in the test scenario, then the scenario fails. That will help prevent any future regression (reduction) of the maximum working file name. The length in bytes of the full string depends on the way the script characters get encoded as UTF. Maybe Cyrillic script (Russian) has a lot of 2-byte encodings, and the Devanagari script (Hindi/Nepali) has 3 or 4 byte encodings. So the written file name looks shorter.

IMO you can have long paths - a whole list of directories and sub-directories ending with a file name. And those can be up to a total of 4000 bytes. But the length of a single file name depends on the file system being written to by the server:
Example: Linux https://en.wikipedia.org/wiki/Ext4

Max. filename length - 255 bytes

And so an `fopen()` to create a file with a longer name will fail.

If oC10 is installed on a file system that allows longer filenames, then it should be able to store them.

**Comment by cortho** [comment]
Thank you for your explanation, especially for the Devanagari encoding and thus the test. So I can understand the test and my other question is more a documentation issue.

**Comment by phil-davis** [comment]
I raised a doc issue https://github.com/owncloud/docs/issues/3945 to discuss how we could usefully document this.

**Comment by individual-it** [comment]
tests added in #39099 and documentation done in https://github.com/owncloud/docs/pull/3950
