### ISSUE TITLE
public share not working after upgrade 10.7 > 10.8

### ISSUE THREAD

**Issue by thommierother** [owncloud/core#39098]
### Steps to reproduce
1. create folder, upload file
2. add public share link, type "Download / View"
3. open created share link

### Expected behaviour
public share working and delivered through classic file app (files) because web app is only installed "on demand", not as default

### Actual behaviour
1. created share link: https://www.netzwissen.de/owncloud/index.php/s/2u5BMO0Tjt9NWjl
2. this re-directs to  https://www.netzwissen.de/owncloud/index.php/apps/web/index.html#/s/2u5BMO0Tjt9NWjl 
3. and then shows "Lade öffentlichen Link… Error: Unknown error"
4. web app should NOT be used in this sharing link

### Server configuration
**Operating system**:

**Web server:**
apache 2.4 with haproxy for ssl

**Database:**
mariadb

**PHP version:**
7.4

**ownCloud version:** (see ownCloud admin page)
10.8

**Updated from an older ownCloud or fresh install:**
10.7 >> 10.8

**Where did you install ownCloud from:**
tar.gz

**Signing status (ownCloud 9.0 and above):**
enterprise version
```
Note: web App is integrated following https://owncloud.dev/clients/web/deployments/oc10-app/ and NOT as default, config
  'default_language' => 'de',
  'defaultapp' => 'files',
[config.txt](https://github.com/owncloud/core/files/6945609/config.txt)
```

**Comment by pmaier1** [comment]
Since 10.8 you can configure whether public/private links redirect to ownCloud Web or to the Classic UI (https://doc.owncloud.com/server/10.8/admin_manual/release_notes.html#fixed-known-issues). See [here](https://owncloud.dev/clients/web/deployments/oc10-app/#configure-link-routing) for the config.php option.

**Comment by thommierother** [comment]
youre right, and that was my error, I simply had a wrong property in  'web.rewriteLinks' => true, when setting it to false, all is fine again.
