### ISSUE TITLE
Add UI acceptance tests for quick action for creating public links

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39132]
PR #39130 implemented a "quick action" button to create a read-only public link in 1-click.

Add a couple of UI acceptance test scenarios:
- check that the "quick action" button works when the setting is enabled
- check that the "quick action" button is not displayed when the setting is not enabled
- enable enforced password protection for read-only links and check that the "quick action" button is not displayed (in this case the user has to click through the usual public link dialogs and put in a password

**Comment by JammingBen** [comment]
@phil-davis @SwikritiT https://github.com/owncloud/core/pull/39167 will change the behavior a bit so that public quick links are only created once per resource. Sorry that this pops up now, we didn't know this was the desired behavior earlier.

**Comment by phil-davis** [comment]
That should not be a problem. The first-time click will behave the same as now.

@SwikritiT do the "easy" test first that clicks the "quick link" button once.

Then when #39167 is finished, you can add a scenario that "moves away and back" (maybe even logout and login again) and clicks the "quick link" button a 2nd time, and confirm that a new public link is not created - the same already-created public link share link should be copied.
