### ISSUE TITLE
Auto upgrade fails if unzip is not installed

### ISSUE THREAD

**Issue by vimar** [owncloud/core#39135]
### Steps to reproduce
1. From owncloud 10.7.0, try to upgrade using web interface (/index.php/settings/admin?sectionid=general)
2. Start upgrade

### Expected behaviour
During checking system, owncloud should stop upgrade with following message:
"unzip command is not found, please install it before executing upgrade"

### Actual behaviour
Checking System display an ok message and start updating core. At some point, the upgrade fails with following message:

> Extracting source into /var/www/owncloud/data/updater-data/_oc_upgrade/10.8.0
> sh: 1: unzip: not found

### Server configuration
**Operating system**: Linux Ubuntu 20.04LTS

**Web server:** Apache

**Database:** Mysql

**PHP version:** PHP 7.4.3

**ownCloud version:** (see ownCloud admin page)

**Comment by brunofcat** [comment]
The same, but after refreshing the page was it possible to complete the update.
