### ISSUE TITLE
Edit/Delete tag actions are highly misleading

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/core#39147]
### Steps to reproduce
1. Create a tag
2. Go to file list
3. Open file details (right sidebar)
4. Click on "Tags"
5. Click in input field
6. Click on Trash bin icon right to a tag

### Expected behaviour
The UI suggests that the trash bin icon removes the tag from the file

### Actual behaviour
The tag gets deleted completely possibly having huge consequences, for example on retention policies.

### Server configuration
**ownCloud version:** 10.8

![grafik](https://user-images.githubusercontent.com/16665512/131366943-2ae1ffa1-64dc-4ebf-9326-f55a27765607.png)

**Comment by JanAckermann** [comment]
See #38495
