### ISSUE TITLE
Disabled Web Updater still functional

### ISSUE THREAD

**Issue by xoxys** [owncloud/core#39183]
### Steps to reproduce
1. `docker run -p 8080:8080 -it owncloud/server:10.8`
2. Login and go to http://localhost:8000/settings/admin?sectionid=general
3. Change `Update channel` to`daily`
4. You will see the "Open Updater"

![image](https://user-images.githubusercontent.com/3391958/132485159-5a627abe-1a02-408e-ad45-aabdb6a51374.png)

### Expected behaviour
If `'upgrade.disable-web' => true` is set, the web updater should be disabled entirely. This setting is the default for our docker images, see https://github.com/owncloud-docker/base/blob/master/latest/overlay/etc/templates/config.php#L51

### Actual behaviour

"Open Updater" button is displayed, and the web updater is still functional.

**Comment by JanAckermann** [comment]
@xoxys Did you mistaken Expected and Actual behavior?

**Comment by xoxys** [comment]
Yes fixed. Thanks!

**Comment by pmaier1** [comment]
Agree with the expected behavior. Not sure why the behavior currently is as described. I'd actually expect the whole section to be hidden if the setting is true.
