### ISSUE TITLE
[encryption] cannot change key storage root

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/core#39188]
### Steps to reproduce
1. Encryption status
    ```console
    ❯ sudo -u www-data occ encryption:status
      - enabled: true
      - defaultModule: OC_DEFAULT_MODULE
    ```
2. Current storage root
    ```console
    ❯ sudo -u www-data encryption:show-key-storage-root
    Current key storage root:  default storage location (data/)
    ```
3. Now try to change key storage root
    - create a folder at `/tmp/oc-keys`
    - change ownership of the folder to `www-data` and provide write permission
    ```console
    ❯ occ encryption:change-key-storage-root ../../../../tmp/oc-keys
    Change key storage root from default storage location to ../../../../tmp/oc-keys
    Start to move keys:
  
    In ChangeKeyStorageRoot.php line 141:
                                                                               
      New root folder doesn't exist. Please create the folder or check the permissions and try again.
                                                                               
  
    encryption:change-key-storage-root [<newRoot>]
    ```

### Expected behaviour
Key root should be change to provided new root

### Actual behaviour
Exits with error message:
```console
New root folder doesn't exist. Please create the folder or check the permissions and try again.
```

### Server configuration
**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4.3

**ownCloud version:** ownCloud 10.8.1 prealpha (git)

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** git

**Comment by JammingBen** [comment]
This command is only supposed to move keys inside your data directory, see https://doc.owncloud.com/server/10.8/admin_manual/configuration/files/encryption/encryption_configuration.html#move-key-location.

**Comment by phil-davis** [comment]
@kiranparajuli589 please raise a docs issue, because the example in the docs that shows moving the keys to `/etc` is not correct.
