### ISSUE TITLE
Downloading all files from the root directory delivers the file ".zip"

### ISSUE THREAD

**Issue by cortho** [owncloud/core#39187]
### Steps to reproduce
1. Login at https://demo.owncloud.org/
2. Click the "select all files" checkbox
3. Click "Download"

### Expected behavior
The file name offered for download is somefilename.zip, not only the extension

### Actual behavior
The file name offered for download is .zip

### Server configuration
demo.owncloud.org

**ownCloud version:** (see ownCloud admin page)
10.8

This behavior makes it impossible for users of some operating systems to directly open the file without renaming it.

"I also noticed that if I select 3 or 4 files, but not all, then “download.zip” is downloaded. But as soon as I put a check mark to select all files, then only “zip” is downloaded."

Reference: https://central.owncloud.org/t/files-are-downloaded-as-a-file-without-extension/33798

**Comment by JanAckermann** [comment]
@cortho Thanks for submitting this issue!
