### ISSUE TITLE
create acceptance tests for download.zip

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39199]
Part of issue #39187 
Related to PR #39198 

1) check what acceptance tests we already have that select files/folders in the webUI and then click the "Download" button:
![select-for-download](https://user-images.githubusercontent.com/1535615/132655310-2538d71c-a8ac-46ef-b0df-39d325e96340.png)

2) create/add scenarios so that we cover at least:
a) select 1 file and download it
b) select 1 folder and download it (the download should be `folderName.zip`)
c) select multiple files/folders and download (the download should be called `download.zip`)
d) select all files/folders and download (the download should be called `download.zip`)
e) inside a folder, do each of the above. For (c) and (d) the zip file should be named the same as the parent folder

**Comment by JanAckermann** [comment]
Might we also check the content of the zip file, if it is not too hard to implement?

**Comment by SwikritiT** [comment]
@JanAckermann we are currently testing that the zip file is downloaded by checking the downloads page of the browser and making sure that the element is present in the DOM. I couldn't access the downloads folder in CI. I could easily do that locally using some docker commands but docker commands don't work in CI. So I don't know how we can check the content of the zip file. If you have some suggestions I'm open to it.

**Comment by phil-davis** [comment]
FYI: the challenge is that the browser is running in a docker container with selenium (which controls the browser). Downloads end up in some "Download" folder of the browser "user" in the docker container. The test runner is running in another docker container, so it is not possible to directly open the browser's "Downloads" folder from the test runner.

Some way around this is needed, that is workable.

**Comment by JanAckermann** [comment]
Note: We can make use of a named docker volume, which is able to share files and folders (download) around docker <-> host and so docker <-> docker

See: https://docs.docker.com/storage/volumes/

**Comment by phil-davis** [comment]
PR #39220 has been merged - that checks the file name of the download.

Next week we can see if we can check the content of the zip file.

**Comment by phil-davis** [comment]
@SwikritiT have a look at what the webUI actually does to get the file (what API call it makes)
We could make an API test that sends the API request. Then we will get the file and can write it wherever we like, and then check its content.
