### ISSUE TITLE
add cli tests for `occ` db commands

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/core#39190]
From https://github.com/owncloud/core/issues/33051

add cli tests for `db` commands (might have to setup a ci pipeline to start with multiple dbs and convert them back and forth)

Ref:
[Databse conversion command docs](https://doc.owncloud.com/server/10.8/admin_manual/configuration/server/occ_command.html#database-conversion)

**Comment by saw-jan** [comment]
I was working on this issue before and the PR is WIP. see https://github.com/owncloud/core/pull/39393
problem encountered: one db-convert scenario finishes and then after & before hooks fail. Maybe some problem occurred in reverting server state after converting the db type

I got occupied by tasks in desktop-client and was hoping to look back into this issue.

I will leave this issue for others to take. But I will take it later if this is still in ToDo

**Comment by phil-davis** [comment]
Ref: https://doc.owncloud.com/server/10.8/admin_manual/configuration/database/db_conversion.html

We can just have a single scenario that, for example, starts with an SQLite database and converts to MariaDB (or mySQL), and run that in its own pipeline. Don't then try to revert in an AfterScenario. This is a by-definition infrastructure-changing test. It is something that can be run in a throw-away environment (separate drone pipeline).

Tag in a way that it will not accidentally be run by any oC10 app or other CI that runs tests core tests.

**Comment by kiranparajuli589** [comment]
#39393 has been cherry-picked for master see [here](https://github.com/owncloud/core/pull/39393#issuecomment-990666550 "cherry-pick comment")
