### ISSUE TITLE
create acceptance tests for `occ` sharing commands

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/core#39192]
From https://github.com/owncloud/core/issues/33051

add cli acceptance tests for `occ` sharing commands

Ref:
[sharing commands docs](https://doc.owncloud.com/server/10.8/admin_manual/configuration/server/occ_command.html#sharing)

**Comment by sakshamgurung** [comment]
PR https://github.com/owncloud/core/pull/39436 closes this issue.
