### ISSUE TITLE
create acceptance tests for `occ` files_external commands

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/core#39195]
From https://github.com/owncloud/core/issues/33051

- Add cli acceptance tests for `occ` files_external commands
- some tests for this commands are already present in `cliExternalStorage/filesExternalWebdavOwncloud.feature`

Ref:
[Files External Commands Docs](https://doc.owncloud.com/server/10.8/admin_manual/configuration/server/occ_command.html#files-external)

**Comment by Talank** [comment]
@kiranparajuli589 is it still review in progress? Is there any work being done?

**Comment by kiranparajuli589** [comment]
hmm..the related pr of @sakshamgurung has been merged. no further work here. i think we can close this.
cc @phil-davis

**Comment by phil-davis** [comment]
Agree - closing.
