### ISSUE TITLE
Icon/Preview of image file not updated in non-owner WebUI shared folders after updating the file

### ISSUE THREAD

**Issue by sigma-design** [owncloud/core#39202]
### Steps to reproduce
1. Run ownCloud docker container as 'admin' user.
2. Create another user, e.g. 'Tester'.
3. Create and share folder with 'Tester'.
4. Place an image file (jpg or png) inside the shared folder.
5. Use WebUI to login as 'Tester' and observe an image file in the shared folder.
6. Logout as 'Tester' from WebUI.
7. Update the image file with some different content, but using the same file name (replace the file).
8. Use WebUI to login as 'Tester' and observe an image file in the shared folder.

### Expected behaviour
Expected to see the file icon and preview to reflect the updated content.

### Actual behaviour
The file icon and preview show the previous content, but size and upload are correct.

### Server configuration
**Operating system**: Ubuntu 20.04

**Web server:** Caddy as reverse proxy (also tested on Plesk with Nginx)

**Database:** ownCloud default

**PHP version:** 7.4.3

**ownCloud version:** 10.8.0 (stable)

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** owncloud/server:latest from Docker Hub

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:** ownCloud default plus Wallpaper

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 92.0 and/or Google Chrome 93.0.4577.63

**Operating system:** Windows 10

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by phil-davis** [comment]
Looks the same as #31855

**Comment by sigma-design** [comment]
Yes, it seems to be in the same vein, as well as [https://github.com/owncloud/gallery/issues/826#](url) - as mentioned there, it's rather inconvenient and misleading for potential users when updated shared files are not correct when previewing them.
