### ISSUE TITLE
[QA] name clash: user name index.html should be prevented

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39205]
Seen in oc10.8.0

The /var/www/owncloud/data folder contains
```
/var/www/owncloud/data# ll
total 100
drwxrwx---  5 www-data www-data  4096 Sep  9 17:06 ./
drwxr-xr-x 14 www-data www-data  4096 Sep  9 16:54 ../
-rw-rw-r--  1 www-data www-data   323 Sep  9 16:55 .htaccess
-rw-rw-r--  1 www-data www-data     0 Sep  9 16:55 .ocdata
drwxr-xr-x  5 www-data www-data  4096 Sep  9 17:06 admin/
drwxr-xr-x  2 www-data www-data  4096 Sep  9 17:06 avatars/
drwxr-xr-x  2 www-data www-data  4096 Sep  9 17:06 files_external/
-rw-rw-r--  1 www-data www-data     0 Sep  9 16:55 index.html
-rw-r-----  1 www-data www-data 72088 Sep  9 17:11 owncloud.log
```

User names can possibly collide with the other entries in this folder.  
All of them are properly prevented (e.g. "Error creating user: The special username avatars is not allowed") except for `index.html`
![image](https://user-images.githubusercontent.com/1108546/132713859-a4d14065-6c3f-4ca7-8d0d-ea9695abc682.png)

When user index.html then tries to log in, it -- of course -- cannot work:

![image](https://user-images.githubusercontent.com/1108546/132714070-cbacbb49-b19a-4dac-a88a-6cd8ba550ec0.png)

**Comment by phil-davis** [comment]
Note: the list f these "special" invalid usernames is here:
https://github.com/owncloud/core/blob/master/lib/private/User/Manager.php#L370
```
			$invalidUids = [
				'avatars',
				'meta',
				'files_external',
				'files_encryption',
				'.htaccess',
				'.ocdata',
				'owncloud.db',
				'owncloud.log'
			];
```

I also have a zero-byte `index.html` in my `data` folder. I wonder what creates that and why?

**Comment by JanAckermann** [comment]
If we touch that list, any more ideas what we could add here?

**Comment by phil-davis** [comment]
> If we touch that list, any more ideas what we could add here?

I am not aware of any others.

**Comment by JanAckermann** [comment]
@phil-davis I will open another ticket for the index.html in the data folder
