### ISSUE TITLE
Zero-Byte index.html in data folder

### ISSUE THREAD

**Issue by JanAckermann** [owncloud/core#39207]
oC 10.8 (git-master)

In the data folder is a index.html file with zero bytes.

- Why is it there ? 
- How it gets created ?
- Can we prevent its creation ? 

![image](https://user-images.githubusercontent.com/26169327/132829126-a7f20fde-5679-4071-93ae-a0ad709435b2.png)

**Comment by ho4ho** [comment]
https://forum.getkirby.com/t/empty-index-html-files-for-what-reason/6835

**Comment by DeepDiver1975** [comment]
questions seems answered - thx @ho4ho
