### ISSUE TITLE
Enabled encryption, encrypted all files, corrupted uploads, can't disable encryption, dangling `.part` files everywhere that can't be deleted

### ISSUE THREAD

**Issue by posita** [owncloud/core#39212]
I am evaluating an instance I have created using [`files_primary_s3`](https://marketplace.owncloud.com/apps/files_primary_s3) for use at my company. I have onboarded a handful of users who have been using the system for several weeks. They have migrated their contacts, calendars, etc. Recently, after performing what appeared to be a successful upgrade to 10.8.0.4, I enabled server-side encryption per [these instructions](https://doc.owncloud.com/server/10.8/admin_manual/configuration/files/encryption/encryption_configuration.html) and did `occ encryption:encrypt-all`. Shortly thereafter, users started complaining of corruption with newly-synced files. (Sources include desktop and iOS app). I attempted to `decrypt-all` so that I could disable encryption, which failed on the post-encryption corrupted files. In addition, several newly created file entries appeared as a result of the `decrypt-all` step alongside those corrupt files with suffixes like `.decrypted.<timestamp>.part`. These showed up in users' folders (at least on web). Users were able to delete their own post-encryption corrupted files from their instances, but not the newly-created `.part` files in their home directories because apparently `.part` is a reserved suffix (but they _**could**_ remove parent folders where `.part` files resided without issue).

Now I am stuck. I can't `decrypt-all` because of the corrupted `.part` files (even with the originals gone), which means I can't turn off encryption. Users can't sync new content because after turning on encryption, all files coming from desktop and iOS apps get corrupted.

**Comment by posita** [comment]
UPDATE: I have managed to disable encryption by doing `UPDATE `oc_filecache` SET encrypted = 0` long enough for `./occ encryption:disable` to "work" (or at least complete successfully). Users are now able to sync files from their desktops and iOS apps again. They were able to restore most of the corrupted uploads from local copies. But some users still have `.part` files in their home directories (visible on web). How can my users get rid of them without me blowing away their user accounts? Also, how do I ensure that there are no dangling files in my S3 buckets? My users are prepared to resync all of their content from their local desktops, if necessary, but restoring contacts, calendars, etc., would be a real pain.

**Comment by posita** [comment]
<img width="749" alt="Screen Shot 2021-09-10 at 08 39 13" src="https://user-images.githubusercontent.com/222581/132862589-9c9f5132-8ca5-46e9-8832-e7847a4fd2c4.png">

**Comment by JammingBen** [comment]
These part-files are part of the chunking process ownCloud uses to process uploads. With that being said, I never experienced a scenario where those files suddenly show up in the file list. Did you enable the maintenance mode before running *all* of those encryption commands?

There is a [cleanup chunks command](https://doc.owncloud.com/server/next/admin_manual/configuration/server/occ_commands/core_commands/dav_commands.html) and/or a [file scan command](https://doc.owncloud.com/server/next/admin_manual/configuration/server/occ_commands/core_commands/file_commands.html#the-filesscan-command) which could repair these entries. I wouldn't bet on it though, this is a super strange scenario. The cleanest way would definitely be to re-create those users. If you want to try these commands, be sure to backup your database and data first and use maintenance mode!

**Comment by posita** [comment]
> These part-files are part of the chunking process ownCloud uses to process uploads. With that being said, I never experienced a scenario where those files suddenly show up in the file list. Did you enable the maintenance mode before running _all_ of those encryption commands?

I followed the instructions as written. It's possible I could have made an error, but being careful was a priority for me. Has anyone tested server-side encrypting with `files_primary_s3`?

> There is a [cleanup chunks command](https://doc.owncloud.com/server/next/admin_manual/configuration/server/occ_commands/core_commands/dav_commands.html) and/or a [file scan command](https://doc.owncloud.com/server/next/admin_manual/configuration/server/occ_commands/core_commands/file_commands.html#the-filesscan-command) which could repair these entries. … If you want to try these commands, be sure to backup your database and data first and use maintenance mode!

The first notes in both sets of instructions you referenced read:

> These commands are not available in single-user (maintenance) mode.

I ran them anyway. Nothing helped:

```
$ ./occ dav:cleanup-chunks
Cleaning chunks older than 2 days(2021-09-11T12:09:24+00:00)
Cleaning chunks for admin
    0 [->--------------------------]
Cleaning chunks for …
    0 [->--------------------------]
Cleaning chunks for …
    0 [->--------------------------]
…
$ ./occ files:scan --all

Scanning files for … users
Starting scan for user 1 out of … (admin)
Starting scan for user 2 out of … (…)
Starting scan for user 3 out of … (…)
Starting scan for user 4 out of … (…)
…

+---------+-------+--------------+------------------+
| Folders | Files | Elapsed time | Items per second |
+---------+-------+--------------+------------------+
| 0       | 0     | 00:00:00     | 0                |
+---------+-------+--------------+------------------+
% ./occ files:cleanup
0 orphaned file cache entries deleted
```

Where do the `.part` entries live? What table(s)? What manages them? Is there (or should there be) an ownCloud analogy to `fsck (8)` that detects and repairs all internal inconsistencies (like the ones I'm experiencing)?

**Comment by posita** [comment]
It's probably useful to not lose sight of the forest for the trees here. The `.part` files are symptomatic of corruption for files synced (via desktop and mobile) **_after_** encryption was enabled. `encryption:decrypt-all` failed on _**only**_ those files, and resulted in all these `.part` files. Each attempt created more.

This was after my first attempt (that failed on `File1.png`:

```
File1.png.decrypted.1631241567.part
```

After my second:

```
File1.png.decrypted.1631241567.part
File1.png.decrypted.1631243783.part
File1.png.decrypted.1631241567.part.decrypted.1631243784.part
```

After my third:

```
File1.png.decrypted.1631241567.part
File1.png.decrypted.1631243783.part
File1.png.decrypted.1631241567.part.decrypted.1631243784.part
File1.png.decrypted.1631241567.part.decrypted.1631247922.part
File1.png.decrypted.1631241567.part.decrypted.1631243784.part.decrypted.1631247923.part
File1.png.decrypted.1631243783.part.decrypted.1631247923.part
```

And so on. It's pretty clear to see that not only was the decrypter choking on the corrupted `File1.png`, but also each of the `.part` files it created (and left dangling) in the process.

**Comment by posita** [comment]
The `.part` files do not sync to the desktop client, but they're visible on web and mobile. If you try to download a single one (e.g., via `https://…/remote.php/webdav/File1.png.decrypted.1631241567.part?downloadStartSecret=…`), it results in a Bad Request error.

<img width="672" alt="Screen Shot 2021-09-13 at 09 38 41" src="https://user-images.githubusercontent.com/222581/133103968-2018ee3f-984e-4175-ac9e-a02c136ccdc4.png">

However, it **_is_** possible to select and download these via a `tar` file (e.g., via `https://…/index.php/apps/files/ajax/download.php?dir=%2F&files[]=File1.png.decrypted.1631241567.part&files[]=File1.png.decrypted.1631241567.part.decrypted.1631243784.part&downloadStartSecret=…`). (They're, unsurprisingly, a bunch of zero byte files.)

**Comment by JammingBen** [comment]
I digged a bit into this topic and found out that encryption is indeed not fully compatible with the S3 object storage. The docs mentioned this in the past, but the information got lost over time for some unknown reason...

**Comment by posita** [comment]
Yikes! Okay. That seems pretty important. How do I get rid of the `.part` files?

**Comment by JammingBen** [comment]
I'm assuming these part-files are in your `oc_filecache` table, too? I still don't know how this happened, this shouldn't happen under any circumstances. AFAIK OC provides no "nice" way to deal with this scenario.

I'd suggest you backup the database and run a SQL-query on `oc_filecache` to remove all entries which include `.decrypted.` and end with `.part` in both the columns `path` and `name`. This way, the files shouldn't appear in your user's file lists. Additionally, you might delete those files on your storage (if you haven't already).

**Comment by JammingBen** [comment]
@posita I'm not a S3 object storage expert, but it seems that it already brings encryption. You can specify `serversideencryption` in your `config.php` alongside your object storage configuration.

We're currently working on the docs to bring some more light into this whole topic.

**Comment by posita** [comment]
I don't see any reference to `serversideencryption` on owncloud.com, but if you're talking about [this](https://doc.owncloud.com/server/next/admin_manual/configuration/files/encryption/encryption_configuration.html), then that's precisely what led to this predicament. If you're talking about [this](https://github.com/search?q=org%3Aowncloud+serversideencryption&type=code), I would be _**really**_ reluctant to turn that one without understanding more about what it does, how it operates, recovery modes, etc. [This](https://central.owncloud.org/t/gentle-easy-and-complete-steps-to-configure-new-s3-using-ceph-backend/14818), for example hardly mentions it.

**Comment by JammingBen** [comment]
I'm not talking about the [Encryption documentation](https://doc.owncloud.com/server/next/admin_manual/configuration/files/encryption/encryption_configuration.html). This is ownCloud's encryption mechanism which is, as stated above, not compatible with the S3 object storage unfortunately. I meant the `serversideencryption` setting that you've found already. Again, we're currently working on the documentation for this. I'll keep you updated once we gathered all the missing information in our docs.

**Comment by posita** [comment]
> I'm assuming these part-files are in your `oc_filecache` table, too? I still don't know how this happened, this shouldn't happen under any circumstances. AFAIK OC provides no "nice" way to deal with this scenario.
> 
> I'd suggest you backup the database and run a SQL-query on `oc_filecache` to remove all entries which include `.decrypted.` and end with `.part` in both the columns `path` and `name`. This way, the files shouldn't appear in your user's file lists. Additionally, you might delete those files on your storage (if you haven't already).

I see a lot of entries with the `path` set to something like `files_encryption/keys/files/File1.png.decrypted.1631241567.part.fake` or `files/File1.png.decrypted.1631241567.part.fake` (where both share a `name` like `File1.png.decrypted.1631241567.part`). Should I remove all of those? Also, how do I map back to my bucket entries? Those all have names like `urn:oid:12345`. Is the number portion the same as the `fileid`?

**Comment by posita** [comment]
Possibly related to #39954?

**Comment by posita** [comment]
Also, why was this closed? AFAIK, this is still an issue?
