### ISSUE TITLE
Add acceptance tests for updating previews

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39211]
There are already some acceptance tests that check characteristics of generated previews (size, dimensions...)

https://github.com/owncloud/core/tree/master/tests/acceptance/features/apiWebdavPreviews

Add test scenarios to check that the content of previews gets updated when the file is changed by the owner, and by sharees.

PR #39203 made some fixes to this. They should be covered by acceptance tests.

**Comment by phil-davis** [comment]
See #39261 for a first idea for an approach. We should be able to do this with API tests that fetch previews and compare the binary content to expected binary content.

**Comment by kiranparajuli589** [comment]
added scenarios with #39268
- [x] preview content changes with the change in file content
- [x] when owner updates a shared file, previews for sharee are also updated
- [x] when owner updates a shared file, previews for sharee are also updated (to shared folder)

**Comment by phil-davis** [comment]
@SwikritiT @kiranparajuli589 I don't see scenarios for:

- Alice creates folder `f1`  and puts a text file `t.txt` in it.
- Alice shares `f` with Brian
- Alice changes the contents of `t.txt`
- Both Alice and Brian see the changed preview
- Brian changes the contents of `t.txt`
- Both Alice and Brian see the changed preview

And a scenario for group sharing is needed:
- Brian and Carol are members of group `grp1`
- Alice creates folder `f1`  and puts a text file `t.txt` in it.
- Alice shares `f` with group `grp1`
- Alice changes the contents of `t.txt`
- Alice, Brian and Carol see the changed preview
- Brian changes the contents of `t.txt`
- Alice, Brian and Carol see the changed preview

**Comment by phil-davis** [comment]
Done - good.
