### ISSUE TITLE
Cannot view `create` button in mobile view. Test fails.

### ISSUE THREAD

**Issue by sakshamgurung** [owncloud/core#39237]
### Steps to reproduce
1. Go to `users` page
2. Resize the browser to mobile size (eg: 375 width by 812 height)

### Expected behaviour
`create` button should be clearly visible in mobile view. Hope more pages will be responsive and suitable for mobile view 👍.

### Actual behaviour
 `create` button is barely visible in remmina so tests pass locally. But are failing in drone with error `element click intercepted: Element is not clickable at point (506, 66)`. Cannot scroll horizontally to make it more visible.
Local screeshot in remmina:
![Screenshot from 2021-09-15 14-22-23](https://user-images.githubusercontent.com/41365307/133401826-44694f59-a7d3-48a1-aafa-ea2abe3758c3.png)

### Server configuration
**Operating system**:
Ubuntu 20.04.3 LTS
**Web server:**
Apache
**Database:**
mysql  Ver 8.0.26-0ubuntu0.20.04.2 for Linux on x86_64 ((Ubuntu))
**PHP version:**
PHP 7.4.3
**ownCloud version:** (see ownCloud admin page)
Latest master branch from github repo
**Updated from an older ownCloud or fresh install:**
Fresh install
**Where did you install ownCloud from:**
Github

**Comment by JanAckermann** [comment]
@sakshamgurung @phil-davis @pmaier1 
What is the requirement for the mobile view? I think if start with the settings, we will be trapepd in A lot refactoring to make the mobile view 100% accessible

**Comment by phil-davis** [comment]
> What is the requirement for the mobile view?

yes, I wonder if it is 'required/reasonable" that an admin be able to do all the settings and user management from their mobile phone.

**Comment by sakshamgurung** [comment]
> > What is the requirement for the mobile view?
> 
> yes, I wonder if it is 'required/reasonable" that an admin be able to do all the settings and user management from their mobile phone.

@phil-davis If that is the case then I think new filter tag like `@mobileResolutionTest` should be created because right now we are running test for all `@smokeTest`.

**Comment by phil-davis** [comment]
> If that is the case then I think new filter tag like @mobileResolutionTest should be created because right now we are running test for all @smokeTest. What do you think @phil-davis ?

Yes, that sounds good. For a first try, add the tag to all the `@smokeTest` scenarios expect for "admin" stuff like user management and admin/system settings.

**Comment by sakshamgurung** [comment]
Closing issue. Not doing tests in mobile resolution for "admin" stuff like user management and settings.
