### ISSUE TITLE
No image zoom functionality in Android web browser

### ISSUE THREAD

**Issue by hannesa2** [owncloud/core#39256]
I use `ownCloud 10.5.0 (stable) ` and when I open images I can't zoom into images with gestures

### Steps to reproduce
1. open images on Android in standard web browser
2. try to zoom with gestures

### Expected behaviour
A zoom with gestures

### Actual behaviour
nothing happens

### Server configuration

**Web server:**
2.4.41 Apache on Ubuntu 20.04

**Database:**
Postgresql

**PHP version:**
PHP 7.4.3 (cli) (built: Aug 13 2021 05:39:12) ( NTS )

**ownCloud version:** (see ownCloud admin page)
ownCloud 10.5.0 (stable)

**The content of config/config.php:**

[config_report_20210920.json.zip](https://github.com/owncloud/web/files/7193770/config_report_20210920.json.zip)

**Comment by kulmann** [comment]
Hey, I transferred your issue to the `core` repo, as it concerns the classic UI.

**Comment by JanAckermann** [comment]
@hannesa2 how do you open images ? With the gallery app ?

**Comment by hannesa2** [comment]
Yes, wirh the gallery app

**Comment by hannesa2** [comment]
Btw, in Firefox on macOS gallery shows me no image at all. But this is an additional issue

**Comment by JanAckermann** [comment]
@hannesa2  as far I can see pinch to zoom is not supported in the gallery app so far. However did you tried the android/ios app for better mobile support?
You can also try the owncloud/web repo.

**Comment by hannesa2** [comment]
Unfortunately on mobile you need the zoom most.

I already use Android app (and [theses](https://github.com/owncloud/android/pulls?q=is%3Apr+author%3A%40me+is%3Aclosed) are my contributions) but when I share a public link, most of them have no Android app installed. And login is annoying too

**Comment by JanAckermann** [comment]
@hannesa2 Did you already tried to upgrade and using the new owncloud/web frontend?
 https://owncloud.dev/clients/web/getting-started/

I tried it and pinch and zoom works

**Comment by hannesa2** [comment]
> @hannesa2 Did you already tried to upgrade and using the new owncloud/web frontend?
> https://owncloud.dev/clients/web/getting-started/
> 
> I tried it and pinch and zoom works

I already use `ownCloud 10.5.0 (stable)` and is `owncloud/web` something different ?

When you wrote _zoom works_, does it mean zoom on Andorid Web browser works ?

**Comment by JanAckermann** [comment]
owncloud/web is a new user interface, you can change between the classic ui and the the ui (web).
You are able to turn it on if you are on 10.6 or higher (but I would suggest updating to the newest package).


> When you wrote zoom works, does it mean zoom on Andorid Web browser works ?
Yes =)

**Comment by kulmann** [comment]
The current version of ownCloud Web actually requires a 10.8 instance, see https://github.com/owncloud/web/blob/6fd163fafafc9d19926192d2826f99170d05b4e5/packages/web-integration-oc10/appinfo/info.xml#L27

**Comment by kulmann** [comment]
@hannesa2 if you give ownCloud Web a try (which I'd appreciate a lot), please be aware that ownCloud Web is a rewrite in a different tech stack and doesn't automatically support all the different apps that are available for ownCloud. At the moment we have a files app, a mediaviewer and OnlyOffice, not much else. You can set up menu items to apps in the classic UI as well though, so doesn't hurt to try it out. :-)

**Comment by hannesa2** [comment]
Sure, I don't want to use an archeological stack 😉 and sooner or later I've to jump into it. 
I love to dockerise all my hosted services, but currently the architecture is not clear to me. A `10.8` instance is needed and a docker of `web` too ? Do you have a graphical overview of the architecture ?

**Comment by kulmann** [comment]
The dockerized ownCloud `10.8` comes with a `web` app included, but it needs additional config to enable that. Docs are available here: https://owncloud.dev/clients/web/deployments/oc10-app/

We have updates of the `web` app available every 3 weeks on https://marketplace.owncloud.com/apps/web 

We also have a dockerized version of the new `web` UI, if you want to host it as a sidecar container, which is possible as well if you don't want to use the oc10 app. There is additional documentation available here: https://owncloud.dev/clients/web/backend-oc10/ 

If you'll use `oauth2` for authentication, there is the possibility now to add `web` as a trusted client. There's no documentation available for that, yet, as that was only released a week ago.
