### ISSUE TITLE
Remove missing license notification

### ISSUE THREAD

**Issue by hannesa2** [owncloud/core#39255]
How to get rid of this message ? I don't need a license because I didn't use all there features
<img width="566" alt="image" src="https://user-images.githubusercontent.com/3314607/133961877-ec64fc83-9af0-4137-8eba-0ceecf7dd493.png">

I guess it was 100 times asked, but I don't found it in issues.

**Expected beahavior**
A simple remove button in GUI would be nice too.

**Config**
The server comes with this owncloud/web#5821 configuration

**Comment by kulmann** [comment]
Hey, I transferred your issue to the `core` repo (it fits best here).

**Comment by JammingBen** [comment]
If you don't need a license, you can simply remove it. OC 10.8 introduced a UI button for this:

![image](https://user-images.githubusercontent.com/50302941/134127510-5a40a39c-d8a7-42bd-a3fc-96cb9af1c278.png)

On earlier OC versions you have to do this in your database directly: `delete from oc_appconfig where appid = 'enterprise_key' and configkey = 'license-key';`
