### ISSUE TITLE
Update ownCloud with Updater app don't works

### ISSUE THREAD

**Issue by hannesa2** [owncloud/core#39266]
I try to update my installation (here you see my setup ##39256) with this promising button.

<img width="571" alt="image" src="https://user-images.githubusercontent.com/3314607/134292432-df5ac9d2-bf7b-4a75-9389-f39c6ff074e4.png">

but I run into

![image](https://user-images.githubusercontent.com/3314607/134292637-f80e4dad-b470-4d43-a9cd-affaa97aa40a.png)

I'm behind a fritz.box

**Comment by JanAckermann** [comment]
Seems like we don't trust self signed certificates
@C0rby any ideas?

**Comment by hannesa2** [comment]
But I don't have one ! But maybe my fritz.box ?

**Comment by JanAckermann** [comment]
I don't know which service is running behind the Fritzbox, I guess a self signed certificate will be issued by the service. Trying to find if we can allow this kind of certificate ☺️

**Comment by hannesa2** [comment]
Now it looks like this 

`Client error response [url] https://localhost/owncloud/index.php/occ/config:list [status code] 404 [reason phrase] Not Found `
