### ISSUE TITLE
add acceptance test scenarios for previews with Unicode characters

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/core#39273]
### Description
with PR #39272, previews of text files that have Unicode characters have been improved. After we make test scenarios for `previews` with ordinary text, add some example(s) with Nepali characters

**Comment by kiranparajuli589** [comment]
@phil-davis @JammingBen 
- if a file has some Unicode characters in its content, the preview will show those Unicode characters, but the other (English) characters are shown as boxes []
- Unicode preview is not the same as content: if we save a file with content `किरण पराजुली`, the previews shows `करिण पराजुली`
![Screenshot from 2021-10-01 12-43-57](https://user-images.githubusercontent.com/39373750/135578723-d0292763-3d00-4bfb-97e4-5f0b9b655613.png)

**Comment by phil-davis** [comment]
Hmmm - I thought that the Devanagari font would also have the usual ASCII Latin characters also in it.

Note: PR #39296 is also coming with more changes to this. It might get better.

@kiranparajuli589 for now, make some test scenarios with just Devanagari script in the text file. Those will pass.

We can make more complex scenarios for PR #39296

**Comment by kiranparajuli589** [comment]
### TODO:
add scenarios to check preview of file containing:
- [ ] just `Devanagari` script
- [ ] `mixed` script

**Comment by jvillafanez** [comment]
> Unicode preview is not the same as content: if we save a file with content `किरण पराजुली`, the previews shows `करिण पराजुली`

It seems to be a php bug: https://bugs.php.net/bug.php?id=34670 . I don't think we can do anything on our side because it seems to be a rendering problem.

The detected char sequence is below (first chars until the space). Trying to reorder the character sequence will cause problems, so I don't think we can do anything about it.
```
    [details] => Array
        (
            [0] => Array
                (
                    [range] => 0-2
                    [str] => क
                    [unicode] => 2325
                    [unicodeHex] => 915
                    [script] => Devanagari
                )

            [1] => Array
                (
                    [range] => 3-5
                    [str] => ि
                    [unicode] => 2367
                    [unicodeHex] => 93f
                    [script] => Devanagari
                )

            [2] => Array
                (
                    [range] => 6-8
                    [str] => र
                    [unicode] => 2352
                    [unicodeHex] => 930
                    [script] => Devanagari
                )

            [3] => Array
                (
                    [range] => 9-11
                    [str] => ण
                    [unicode] => 2339
                    [unicodeHex] => 923
                    [script] => Devanagari
                )
```

**Comment by phil-davis** [comment]
> It seems to be a php bug: https://bugs.php.net/bug.php?id=34670 . I don't think we can do anything on our side because it seems to be a rendering problem.

And that has been reported further upstream:
https://github.com/libgd/libgd/issues/758

And that issue has had discussion and been closed. "Closing this one as it can't be fixed/done without rewriting everything and handling the whole unicode and rules ourselves." - essentially "won't fix".

Our tests should just be checking that "some reasonable version of the script" is rendered. IMO use example Devanagari text that does render OK.

**Comment by phil-davis** [comment]
> if a file has some Unicode characters in its content, the preview will show those Unicode characters, but the other (English) characters are shown as boxes

I agree with the comments above. IMO the objective is to provide some reasonable rendering of the text so that is might be recognizable and helpful to the user. In the vast majority of cases the text is likely to be all in a single script, and even if the script does change, it is likely that whole "fragments" of text are in the same script.

**Comment by phil-davis** [comment]
Tests for the "usual" scenario(s) of detection of a script are done. Closing.
