### ISSUE TITLE
Grid functionality in web browser doesn't work

### ISSUE THREAD

**Issue by hannesa2** [owncloud/core#39291]
Here you can read my setup #39256 . In short I use ownCloud `10.5.0 (stable)`

When I use grid function in web browser, eg Firefox or Chrome it shows nothing  and switch back to list doesn't work either
https://user-images.githubusercontent.com/3314607/134870632-2cfa840c-7500-4133-9bda-cef4ed490751.mov

**Comment by JammingBen** [comment]
Does your browser console report any errors or other messages?

**Comment by hannesa2** [comment]
I guess this is interesting 
<img width="887" alt="image" src="https://user-images.githubusercontent.com/3314607/134877344-4a59096e-8991-49f6-96bc-9f0a847eaeb2.png">

**Comment by JammingBen** [comment]
Nearly :) Additionally it would be nice to see where exactly the `TypeError` was thrown. It should be on the very right side of the red line.

**Comment by hannesa2** [comment]
Better ?

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/3314607/134878574-b106f8c5-31fb-4a6d-ae79-5becb1ab9703.png">

**Comment by JammingBen** [comment]
It seems that the error comes from the `files_mediaviewer` app. Since you want to use the `gallery` app anyway, could you try disabling `files_mediaviewer`?

**Comment by hannesa2** [comment]
👍 It works now. Thank you. 

Btw, I don't know which functionally I'm loosing now. Anyway, now I can see the pictures !

**Comment by hannesa2** [comment]
Yes ! It's working too.

But now the pictures in detail are smaller (because of navigation arrows), combined with #39256 it's almost no more usable in Android browser.
It seams like `files_mediaviewe`r is not really tested on mobile devices
