### ISSUE TITLE
Update to owncloud 10.8.0 impossible

### ISSUE THREAD

**Issue by jh2087** [owncloud/core#39308]
OC\RepairException: Upgrade is not possible

        Reparaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
        Reparaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable calendar occ app:disable contacts occ app:disable files_pdfviewer occ app:disable files_texteditor occ app:disable files_videoplayer occ app:disable gallery occ app:disable tasks occ app:disable twofactor_privacyidea
        Reparaturwarnung:For manually updating, see https://doc.owncloud.com/server/10.8/go.php?to=admin-marketplace-apps

Detaillierte Fehlermeldungen
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturwarnung:You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
Reparaturwarnung:Please install or update the following apps manually or disable them with: occ app:disable calendar occ app:disable contacts occ app:disable files_pdfviewer occ app:disable files_texteditor occ app:disable files_videoplayer occ app:disable gallery occ app:disable tasks occ app:disable twofactor_privacyidea
Reparaturwarnung:For manually updating, see https://doc.owncloud.com/server/10.8/go.php?to=admin-marketplace-apps
OC\RepairException: Upgrade is not possible

**Comment by JammingBen** [comment]
As stated in the error message: please disable the mentioned apps via command line and try the upgrade again.

**Comment by cortho** [comment]
Not an issue -> closing.
@jh2087 If you have got further questions regarding your problem feel free to visit the forum at https://central.owncloud.org/
