### ISSUE TITLE
CloudNotes Sync Error with NC 20.0.5

### ISSUE THREAD

**Issue by gitty-123** [owncloud/core#39324]
### Steps to reproduce
1. While Nextcloud running on the latest Update (21.0.5) with no issues, i open the "Notes" Page and edit a new note
2. Then i go on my iphone or ipad and try to synchronize (with the CloudNotes App) it with my nextcloud instance
3. There is always the "timed out error" and no synchronization will happen
4. When i disable the config.php entry on my nc server ('filelocking.enabled' => false,) everything is working and synchronizing as it should.

### Expected behaviour
Synchonization as it should be

### Actual behaviour
"timed out" error

### Server configuration
**Operating system**:
Ubuntu 20.04 LTS latest patch level

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.4

As i mentioned, there are many people who have the same issue.

To disable "filelocking" the whole time cant be the right way :-)

**Comment by phil-davis** [comment]
@gitty-123 this is the ownCloud repository, but you say you are using NextCloud ???
