### ISSUE TITLE
Add acceptance tests for PROPFINDs on a folder including an external storage

### ISSUE THREAD

**Issue by JammingBen** [owncloud/core#39350]
The following scenario should be tested:

* Add a folder in OC including an external storage that includes some files (the user's root directly including an external storage should also work)
* Make the external storage unavailable (e.g. by renaming the folder on the local storage)
* Do a PROPFIND on the external storage -> returns `404`
* Do a PROPFIND with `depth=infinite` on the parent folder -> the local storage should be listed, but none if its content (that's the current behavior, so it seems right...?)
* Rename the external storage back again
* Do a PROPFIND on the external storage -> returns a `207`
* Do a PROPFIND with `depth=infinite` on the parent folder  -> the external storage and all its contents should be listed

**Comment by dpakach** [comment]
There seems to be one small issue with the external storage
https://github.com/owncloud/core/issues/39470
