### ISSUE TITLE
[FR] Bind specific auth mechanisms to specific external storages

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#39448]
### Steps to reproduce
1. Install WND app
2. In the mount point configuration, choose SFTP storage with any WND auth mechanism
3. Disable WND app

### Expected behaviour
Step 2 shouldn't be possible. WND auth mechanisms should only be used by the WND app

### Actual behaviour
SFTP mounts get broken since the WND auth mechanism isn't available any longer

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

As far as I know, auth mechanisms are bound to a schema, being the most common one the "password" one (I guess, representing the classic username + password). Other schemas available are "oauth2" and "public key".

Each external storage can choose what schema wants to use. For example, google uses the "oauth2" schema, and SFTP uses "public key" and "password" schemas.
The problem is there is no control of which auth mechanism will be used by the external storage. The external storage has available ALL the auth mechanisms bound to the chosen schema.

The specific problem is that, SFTP chooses to use the "password" schema, which has "username + password" and "saved in session" auth mechanisms by default. WND will add additional auth mechanisms to that "password" schema, which means that SFTP will also have access to those auth mechanisms
While this isn't apparently a big deal, the issue is that the WND app can be disabled any time, which would break any storage that uses any WND auth mechanism. This means that usage of the auth mechanisms included in the WND app outside of the WND app should be discouraged.

@pmaier1 @mmattel

**Comment by mmattel** [comment]
Another way solving this would be to move the implementation of the "Credentials hardcoded in config file" auth mechanism to core and provide it to all relevant storage apps. That could be imho much easier and quicker to implement.
