### ISSUE TITLE
Group admin cannot resend invitation email

### ISSUE THREAD

**Issue by cortho** [owncloud/core#39476]
### Steps to reproduce
1. Log in as a group administrator and enter the User panel
2. Create a new user by setting the email address
3. Click the envelope to resend the invitation mail
4. The notfication "The invitation email for this user could not be resent" is shown
5. The POST request results in "Logged in user must be an admin"

### Expected behaviour
In the docs at https://doc.owncloud.com/server/next/admin_manual/configuration/user/user_configuration.html#granting-administrator-privileges it reads
>  Group administrators have the rights to create, edit and delete users in their assigned groups.

So it is expected that the invitation email can be resent.

### Actual behaviour
The email is not sent, an error notification is shown.

### Server configuration
**Operating system**:
Ubuntu 20.04

**Web server:**
apache 2.4.41

**Database:**

**PHP version:**
PHP 7.4

**ownCloud version:** (see ownCloud admin page)
10.8

### Client configuration
irrelevant

#### ownCloud log (data/owncloud.log)
```
{"reqId":"YYvBz7SdEDu86-F@JGkXHAAAAAA","level":0,"time":"2021-11-10T12:57:51+00:00","remoteAddr":"127.0.0.1","user":"grpadmin","app":"no app in context","method":"POST","url":"/owncloud/index.php/resend/invitation/test2","message":"Logged in user must be an admin"}
```

#### Browser log
```
POST https://localhost/owncloud/index.php/resend/invitation/test2 403 Forbidden
```
Edit: Reference: https://central.owncloud.org/t/group-admin-cannot-change-email-address-or-resend-invite-email/34853

**Comment by JammingBen** [comment]
Thx for noticing! The issue was fixed via https://github.com/owncloud/core/pull/39477, will be released in 10.9 soon.
