### ISSUE TITLE
Group admin cannot change group member's email address

### ISSUE THREAD

**Issue by cortho** [owncloud/core#39475]
### Steps to reproduce
1. Log in as a group administrator of a group with at least one member and enter the User panel
2. Change a user's email address
3. The circle next to the email address is spinning endlessly
4. The PUT request results in "Logged in user must be an admin"

### Expected behaviour
In the docs at https://doc.owncloud.com/server/next/admin_manual/configuration/user/user_configuration.html#granting-administrator-privileges it reads
>  Group administrators have the rights to create, edit and delete users in their assigned groups.

So it is expected that the email address can be changed,

### Actual behaviour
After having changed an email address the circle next to the email address is spinning endlessly.

### Server configuration
**Operating system**:
Ubuntu 20.04

**Web server:**
apache 2.4.41

**Database:**

**PHP version:**
PHP 7.4

**ownCloud version:** (see ownCloud admin page)
10.8

### Client configuration
irrelevant

#### ownCloud log (data/owncloud.log)
```
{"reqId":"YYu-8tb42wCQ97ILvwvhXQAAAAc","level":0,"time":"2021-11-10T12:49:54+00:00","remoteAddr":"127.0.0.1","user":"grpadmin","app":"no app in context","method":"PUT","url":"/owncloud/index.php/settings/admin/test/mailAddress","message":"Logged in user must be an admin"}
```

#### Browser log
```
PUT https://localhost/owncloud/index.php/settings/admin/test/mailAddress 403 Forbidden
Uncaught TypeError: result.responseJSON is undefined
users.js:903
```

Edit: Reference: https://central.owncloud.org/t/group-admin-cannot-change-email-address-or-resend-invite-email/34853

**Comment by JammingBen** [comment]
This was also fixed via https://github.com/owncloud/core/pull/39477.
