### ISSUE TITLE
Add API tests to check that app passwords are preserved on password change

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39490]
PR #26731 reported some years ago that there was a problem that app passwords disappeared when a user changed their ordinary password. I don't think that we cover this sequence of events.

A a test scenario(s) to cover a sequence like:
- a user adds an app password
- the user uses the app password successfully
- the user changes their ordinary password
- the changed ordinary password works
- the app password still works

Add for:
- basic auth
- LDAP (might need to add a scenario in the API tests of the user_ldap app)

**Comment by sakshamgurung** [comment]
@phil-davis What is app password. Does ordinary password mean login password?

**Comment by phil-davis** [comment]
"ordinary password" is "login password"
Look in AuthContext `userGeneratesNewAppPasswordNamed` and the code around there.
Users can create app passwords in the webUI or with the API.

**Comment by phil-davis** [comment]
PR #39491 has been merged. That provides test coverage here.
