### ISSUE TITLE
[tests-only] Add acceptance tests for version metadata

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39504]
See PR  #39126 

oC10 core is being enhanced to remember the author of each version of a file.

Add acceptance tests to cover this new feature:
- API tests to check that the author of each version can be returned in API requests
- webUI tests to check that the author is displayed against each version in the version history
- also have test cases to check what happens when the feature is enabled and there are existing files that are then edited after the feature is enabled.

Here is an example screenshot of the feature:

![edits-by-group-members](https://user-images.githubusercontent.com/1535615/142352709-178c1b76-9fbe-4cfa-bf24-1ef33eba5b4b.png)

**Comment by phil-davis** [comment]
Note: as of now, the code in the PR has an "off-by-one" error (read the latest discussion in the PR)

Tests should expect the following sort of behavior:

Alice creates folder "f1"
Alice shares "f1" with Brian and Carol and David
Brian creates "f1/textfile.txt"
Carol edits "f1/textfile.txt"
Alice edits "f1/textfile.txt"
Davis edits "f1/textfile.txt"

The version history should show versions with authors Brian, Carol and Alice.
David should not be mentioned in the version history. David is the author of the current data in "f1/textfile.txt", and that information is not displayed anywhere.

**Comment by phil-davis** [comment]
Until PR #39126 is merged, please work on tests in a separate branch on top of the PR  branch.

**Comment by JammingBen** [comment]
There is a PR already, maybe it can be extended: https://github.com/owncloud/core/pull/39478

**Comment by phil-davis** [comment]
> There is a PR already, maybe it can be extended: #39478

Thanks - I didn't notice that. We can review with @IljaN

**Comment by phil-davis** [comment]
Note: this needs to be followed-up async as the issue is sorted out in core.

**Comment by saw-jan** [comment]
@phil-davis do we have some tasks to do here?

**Comment by phil-davis** [comment]
> @phil-davis do we have some tasks to do here?

https://github.com/owncloud/core/blob/master/tests/acceptance/features/webUIFiles/versions.feature needs some scenarios and/or add steps to the existing scenarios. Combinations of sharing a file or folder with file(s) that have versions and check that the "author" of each version is displayed correctly in the list.

And review the current scenarios - there might be a couple more that would be useful to check common combinations of things that users do with versions?
