### ISSUE TITLE
additional occ user commands necessary

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#39502]
Post merging https://github.com/owncloud/core/pull/39136 (feat: new command to move a user's home folder - occ user:move-home)

* A users home can now be moved with the `occ user:move` command
* You can report for a particular user which home he has:
```
sudo -uwww-data ./occ user:list hugo -a home
  - hugo: /var/www/owncloud/data/hugo
```
* There are commands missing:
1.) list which homes are present like:
`user:homes` --> `/var/www/owncloud/data/` (only unique entries)
2.) list which users belong to a particular home like:
`user:homes -u (or --users)` `/var/www/owncloud/data/` --> `<line by line list of users>`

**Reason**
After moving a users home, you have no knowledge which directories you have to maintain and which users have their home in an particular directory. From an admin pov a nightmare, except you take a physically look into directories and do a search for - if you know the directory...

IMHO both commands are not a big deal as the data is already present and just needs to be queried only and printed.

@pmaier1 as discussed

**Comment by pmaier1** [comment]
@JanAckermann @JammingBen Let's check whether this is a quick thing, as time permits. I think it would add value to the user:move command as it makes it traceable where user homes have been moved.

**Comment by JammingBen** [comment]
If we really want to have two different kinds of output in one command (home paths <> users), I'd prefer to force the user to always specify. Otherwise it seems confusing to me. @pmaier1 What do you think?

* `user:homes -l (--list)` List all user home directories
* `user:homes -u (--users) path` List all users that have their home within a given directory

**Comment by mmattel** [comment]
Q: how do you know the different locations you have (user independent) without a query?

**Comment by JammingBen** [comment]
The backend basically needs to look up all users including their home directories and then generate a list with unique items. Is that answering your question? I'm not sure what you mean by "query" in this context.

**Comment by mmattel** [comment]
After having an audio call with @JammingBen, things are clarified.

**Comment by JammingBen** [comment]
Implemented via https://github.com/owncloud/core/pull/39579

**Comment by jnweiger** [comment]
Confirmed fixed in 10.9.0 RC1


For me, who *wants* to see the two different outputs together, this is my favorite invocation:

```
$ occ user:home:list-dirs | sed -e 's/ - //' | xargs -t -n 1 occ user:home:list-users
occ user:home:list-users /mnt/data/files 
  - admin
  - user02
occ user:home:list-users /tmp 
  - user01
```

**Comment by mmattel** [comment]
@jnweiger I like the test command sequence 👍

**Comment by mmattel** [comment]
https://github.com/owncloud/docs/issues/4492 (New occ commands extending user:move these are user:homes:list-dir and user:home:list-users <path>)
