### ISSUE TITLE
Improve Then steps in API acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39512]
We run the core API acceptance tests in various different environments including:
- regular `owncloud/core`
- oC10 apps (for example, user_ldap, files_primary_s3, admin_audit, activity, password_policy...) where significant different backend components, hooks, events happen for those apps, and there can potentially be any sort of regression of behavior.
- `owncloud/ocis` which has a completely different server-under-test
- `cs3org/reva` which has a completely different server-under-test

`When` steps are expected to run just the `When` action, and not fail. The later `Then` steps in the scenario should check the result of the `When` step. We do this because:
- sometimes a `When` step is expected to sometimes give a "bad" HTTP status. For example, if dome with a valid user the API request returns 2xx, if done with a non-existent user it gives a 4xx. So the `When` step code cannot and should not guess if a 4xx is "a bad thing".
- in API tests we want to be clear about what are the expected results of the `When` action. So writing out the expected HTTP status, and something about the expected request body etc in separate `Then` steps is useful for people who read the scenario. (rather than hiding this inside the test code as "assumed knowledge")

Issue https://github.com/owncloud/ocis/issues/1420 has a discussion about this. In that case the scenario did not have `Then` steps to check the HTTP status. The test for public link access failed, and it was not clear that actually the `When` step failed completely.

ToDo: add `Then` steps to existing API test scenarios to better check the results of `When` steps.

**Comment by phil-davis** [comment]
Whoever starts this, please do an initial PR that just adjusts a single API feature file. Then we can all review and discuss to make sure we choose a "best" way forward.

**Comment by phil-davis** [comment]
Note: there are some simple examples done for disable-user tests at commit https://github.com/owncloud/core/pull/39514/commits/6e5eb23d3cdc425c2b2a5ab72bfda67e21dcdd06

**Comment by kiranparajuli589** [comment]
@grgprarup is working on this

**Comment by grgprarup** [comment]
TODO:
- [x] apiAuth (no need)
- [x] apiAuthOcs (no need)
- [x] apiAuthWebDav (no need)
- [x] apiCapabilities (no need)
- [ ] apiComments (@grgprarup )
- [ ] apiFavorites ()
- [ ] apiFederationToRoot1 ()
- [ ] apiFederationToRoot2 ()
- [ ] apiFederationToShares1 ()
- [ ] apiFederationToShares2 ()
- [ ] apiMain ()
- [ ] apiProvisioningGroups-v1 ()
- [ ] apiProvisioningGroups-v2 ()
- [ ] apiProvisioning-v1 ()
- [ ] apiProvisioning-v2 ()
- [ ] apiShareCreateSpecialToRoot1 ()
- [ ] apiShareCreateSpecialToRoot2 ()
- [ ] apiShareCreateSpecialToShares1 ()
- [ ] apiShareCreateSpecialToShares2 ()
- [ ] apiSharees ()
- [ ] apiShareManagementBasicToRoot ()
- [ ] apiShareManagementBasicToShares ()
- [ ] apiShareManagementToRoot ()
- [ ] apiShareManagementToShares ()
- [ ] apiShareOperationsToRoot1 ()
- [ ] apiShareOperationsToRoot2 ()
- [ ] apiShareOperationsToShares1 ()
- [ ] apiShareOperationsToShares2 ()
- [ ] apiSharePublicLink1 ()
- [ ] apiSharePublicLink2 ()
- [ ] apiShareReshareToRoot1 ()
- [ ] apiShareReshareToRoot2 ()
- [ ] apiShareReshareToRoot3 ()
- [ ] apiShareReshareToShares1 ()
- [ ] apiShareReshareToShares2 ()
- [ ] apiShareReshareToShares3 ()
- [ ] apiShareUpdateToRoot ()
- [ ] apiShareUpdateToShares ()
- [ ] apiSharingNotificationsToRoot ()
- [ ] apiSharingNotificationsToShare ()
- [ ] apiTags ()
- [ ] apiTranslation ()
- [ ] apiTrashbin ()
- [ ] apiTrashbinRestore ()
- [ ] apiVersions ()
- [ ] apiWebdavEtagPropagation ()
- [ ] apiWebdavEtagPropagation ()
- [ ] apiWebdavLocks ()
- [ ] apiWebdavLocks2 ()
- [ ] apiWebdavLocks3 ()
- [ ] apiWebdavLocksUnlock ()
- [ ] apiWebdavMove ()
- [ ] apiWebdavMove2 ()
- [ ] apiWebdavOperations ()
- [ ] apiWebdavPreviews ()
- [ ] apiWebdavProperties ()
- [ ] apiWebdavProperties ()
- [ ] apiWebdavUpload1 ()
- [ ] apiWebdavUpload2 ()
- [ ] apiWebdavUploadTUS ()

**Comment by kiranparajuli589** [comment]
finally done! great work @SagarGi, @amrita-shrestha, @grgprarup and @sushmita56 :crown: :+1:
