### ISSUE TITLE
Selecting the "show password" icon in password input field does not show the password

### ISSUE THREAD

**Issue by Talank** [owncloud/core#39527]
### Description
During the new installation of core, if we select the "show password" (👁️ ) icon on the password input field, it does not show us the password that we entered. This issue exists on all the password fields of the core setup page (where the 👁️ icon exists).

### Steps to reproduce
1. Start fresh installation of core, or remove the existing data directory and create a new one so that it ask you to create a database.
2. Click in the 👁️ icon on the password input field.

### Expected behaviour
User should see what password that they have entered.

### Actual behaviour
Selecting the "show password" icon does nothing, as shown in the screen capture below. 

### Server configuration
**Operating system**: Ubuntu 20.04

**Database:** mysql

**PHP version:** 7.4.3

**ownCloud version:** current master with commit ssh `762780a23c9eadda4fb5fa8db99eba66a5100b6e`

**Updated from an older ownCloud or fresh install:** fresh install

### Screenshot

https://user-images.githubusercontent.com/27364813/142972301-3e3bf451-08a5-4bbb-972c-e7d6a73a0e75.mp4

![Screenshot from 2021-11-23 10-48-13](https://user-images.githubusercontent.com/27364813/142973804-a894e133-9c07-46ee-82bc-e5224476e463.png)

**Comment by JanAckermann** [comment]
Thx for opening this issue

**Comment by phil-davis** [comment]
Fixed in #39528 - will be in release 10.9.0
