### ISSUE TITLE
Creating a group with space at end does not work

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39533]
### Steps to reproduce
```
  Background:
    Given using OCS API version "2"

  @issue-39533 @skipOnOcis
  Scenario: admin creates a group that has white space at the end of the name
    When the administrator sends a group creation request for group "white-space-at-end " using the provisioning API
    Then the OCS status code should be "200"
    And the HTTP status code should be "200"
    # Note: it seems that white space at the end of a group name gets stripped off
    # Groups "white-space-at-end " and "white-space-at-end" seem to be effectively the same
    And group "white-space-at-end " should exist
    And group "white-space-at-end" should exist
```

### Expected behaviour
I am not sure, but it should be consistent.
Maybe white-space at the end of a group name should not be allowed, and the initial group creation request should fail?
Maybe it should be allowed, and in that case the groups "abc" and "abc " should be 2 different groups.

### Actual behaviour
When a group is created with white-space on the end of the name, the request seems to work.
But when querying the group it looks like 2 groups exist - both the group with and without the white-space at the end.

### Server configuration
current core master

**Comment by phil-davis** [comment]
Note1: space at the start of a group name is currently allowed, and the 2 groups "abc" and " abc" get created and work as 2 different groups.

Note2: the current implementation of the Provisioning API on oCIS seems to allow space at either or both ends of a grup name, and treats all such groups as distinct/different.

**Comment by phil-davis** [comment]
PR #39540 prohibits space at the start or end of a group name.

**Comment by individual-it** [comment]
@phil-davis anything left to do here or close the issue?

**Comment by phil-davis** [comment]
white space at the beginning or end of a group name is now not allowed. The code for that was reviewed in PR #39540 and ended-up in #39612 which has now been merged to master.
