### ISSUE TITLE
No app tab except files, activity and market

### ISSUE THREAD

**Issue by Entretoize** [owncloud/core#39534]
### Steps to reproduce
1. Install owncloud from deb on debian 9
2. Move the owncloud folder to the good place
3. Add apps to the apps folder

### Expected behaviour
There should be some button, tab or link to acces the apps somewhere

### Actual behaviour
When I go to mywebsite/owncloud/ it redirects me to mywebsite/owncloud/index.php/apps/files/?dir=/&fileid=3 and clicking the top left only propose me Files / Activity / Market (and market throws an error 60 with curl).

### Server configuration
Debian 9

Apache 2

mysql

php 8.0.8

owncloud 10.8.0.4

fresh install

Heard from google

**Comment by ho4ho** [comment]
Looking not like bug, looking support question belonging to https://central.owncloud.org/

> There should be some button, tab or link to acces the apps somewhere

Look docs:

https://doc.owncloud.com/server/10.8/admin_manual/installation/apps_management_installation.html#installing-apps-manually

**Comment by Entretoize** [comment]
Added app don't show in activated nor disabled apps, curl doesn't work, I have file integrity issues, I think I will just forget about owncloud...
