### ISSUE TITLE
occ config:app:set stores an empty string that cannot be overwritten when called without --value

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39553]
Seen in 10.9.0 beta1 

```
# occ config:app:delete foo bar
# occ config:app:set foo bar
Config value bar for app foo set to 
# occ config:app:get foo bar

# occ config:app:set foo bar --value='hammer'
Config value bar for app foo set to hammer
# occ config:app:get foo bar

#
```

The second `set` command reports that it did set the value to `hammer`, but in reality it failed.

Expected behaviour:
* Invoking config:app:set without --value should print a syntax error.
* Correct commands that fail should print an error, not a success message.

Workaround: `occ config:app:delete foo bar`

**Comment by phil-davis** [comment]
The unspecified value ends up being NULL in the database. (I would have hoped that it would be the empty string)

There is code in https://github.com/owncloud/core/blob/master/lib/private/AppConfig.php#L190
```
				// Only update the value when it is not the same
				$sql->andWhere($sql->expr()->neq('configvalue', $sql->createParameter('configvalue')))
					->setParameter('configvalue', $value);
```

Unfortunately that SQL not-equal expression does not "see" that a new value "some-string" is not-equal to NULL. For existing database rows that have `configvalue` NULL, the new value never gets written to the database.

I don't think there is ever a reason to record a `configvalue` of NULL in the first place. Maybe we just prevent NULL from being able to happen in the `config:app:set` command.
