### ISSUE TITLE
occ user:move results in unwritable home folder

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39560]
Seen with 10.9.0 beta1 while testing #39136

* Log in user01 at the web UI, upload and rename some files. All works fine.
* As Linux root user run `mkdir /tmp/oc; chown www-data. /tmp/oc; occ user:move user01 /tmp/oc`
* At the web UI user01 can access his existing files normally, but cannot rename nor upload nor delete. BAD

![image](https://user-images.githubusercontent.com/1108546/144848005-61fc6053-2548-4583-b418-9454769d70be.png)

`occ file:scan user01 -vvv --repair` does not help.

The logfile says:
```
{"reqId":"Ya4Cvuji2v7LWF1z6alV6gAAAAY","level":3,"time":"2021-12-06T12:31:58+00:00","remoteAddr":"2.247.253.5","user":"user01","app":"no app in context","method":"POST","url":"\/index.php\/login","message":"User backend OC\\User\\Database is returning home: \/var\/www\/owncloud\/data\/user01 for user: user01 which differs from existing value: \/tmp\/oc\/user01"}
{"reqId":"Ya4D7Oji2v7LWF1z6alV8AAAAAY","level":3,"time":"2021-12-06T12:37:00+00:00","remoteAddr":"2.247.253.5","user":"user01","app":"no app in context","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"User backend OC\\User\\Database is returning home: \/var\/www\/owncloud\/data\/user01 for user: user01 which differs from existing value: \/tmp\/oc\/user01"}
{"reqId":"Ya4FGCleWFR6jjT1-9JkbQAAABA","level":3,"time":"2021-12-06T12:42:00+00:00","remoteAddr":"2.247.253.5","user":"user01","app":"no app in context","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"User backend OC\\User\\Database is returning home: \/var\/www\/owncloud\/data\/user01 for user: user01 which differs from existing value: \/tmp\/oc\/user01"}
```

**Comment by jnweiger** [comment]
Workaround: 
* Move back, to make the database happy and the user operative again: `occ user:move user01 /var/www/owncloud/data/`

**Comment by JammingBen** [comment]
I also get the log:

`{"reqId":"Ya4Cvuji2v7LWF1z6alV6gAAAAY","level":3,"time":"2021-12-06T12:31:58+00:00","remoteAddr":"2.247.253.5","user":"user01","app":"no app in context","method":"POST","url":"\/index.php\/login","message":"User backend OC\\User\\Database is returning home: \/var\/www\/owncloud\/data\/user01 for user: user01 which differs from existing value: \/tmp\/oc\/user01"}`

But other than that, everything works flawlessly on my local machine.

Using the `10.9.0-beta1` docker image however, I get an error when running the occ move command:

```
Syncing files from /mnt/data/files/test/ to /tmp/oc/test ...
sh: 1: rsync: not found
```

Installed rsync, tried again, worked just fine. @jnweiger Did you also get the rsync error? Maybe the command somehow silently failed because of that?

**Comment by jnweiger** [comment]
When rsync is not available, the user becomes disabled:

```
# mv /usr/bin/rsync{,.weg}
# occ user:move user01 /tmp/oc/
Move user01 from /var/www/owncloud/data/user01 to /tmp/oc/user01
Disabling user ....
Syncing files from /var/www/owncloud/data/user01/ to /tmp/oc/user01 ...
sh: 1: rsync: not found

In MoveHome.php line 134:
                          
  Copying files failed:   
   Array                  
                          

user:move-home <user_id> <new_location>
```

Trying to log in user01 at the web ui results in:
![image](https://user-images.githubusercontent.com/1108546/145027221-ae0e9545-40a4-4063-8803-4608d358cceb.png)

```
{"reqId":"Ya9PneknR4GYTk2uuzSEMQAAAAY","level":0,"time":"2021-12-07T12:12:13+00:00","remoteAddr":"2.247.253.191","user":"user01","app":"OC\\User\\Session::checkTokenCredentials","method":"GET","url":"\/index.php\/apps\/files\/undefined\/img\/notifications.svg","message":"user uid user01, email u1@ex.com, displayName user01 was disabled or password changed"}
```

Rsync is definitly a new dependency for oc 10.9 !

**Comment by JammingBen** [comment]
Yep. First time, how do we usually deal with such scenarios? At least the docs and the docker images need to be updated I assume.

Anyway, that does not solve the issue you initially had. Any ideas what you did different? Any 3rd party apps involved maybe? Could you verify that the permissions for `/tmp/oc` have been set correctly?

**Comment by jnweiger** [comment]
Not a permission issue on my side. the entire /tmp/oc subtree is owned by `www-data:www-data` with user write permissions. Both the folder that I created, and the files that rsync created.

Another surprise: the moved user can apparently delete files. No error messages when he does so. But only the file cache is affected. The files are not deleted from the storage. An `occ file:scan` brings them back.

**Comment by jnweiger** [comment]
The issue is specific to the location in the filesystem:
* Errors seen in 
   * /var/tmp/oc_users/
   * /tmp/oc_users/
* No problems in 
   * /home/oc_users
   * /var/run/oc_users
   * /oc_users

**Comment by JammingBen** [comment]
Problem is related to the `PrivateTmp` setting of the apache service - not ownCloud specific. More info: https://www.maxoberberger.net/blog/2017/10/debian-9-private-tmp.html

Closing here, Doc issue will follow 👍

**Comment by jnweiger** [comment]
Background: http://systemd.io/TEMPORARY_DIRECTORIES/

For system services systemd provides the PrivateTmp= boolean setting. If turned on for a service (👍 which is highly recommended), /tmp/ and /var/tmp/ are replaced by private sub-directories, implemented through Linux file system namespacing and bind mounts. This means from the service’s point of view /tmp/ and /var/tmp/ look and behave like they normally do, but in reality they are private sub-directories of the host’s real /tmp/ and /var/tmp/, and thus not system-wide locations anymore, but service-specific ones. This reduces the surface for local DoS ...
