### ISSUE TITLE
Windows IIS SMB Mounts: Can't mount SMBs on Windows

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#3956]
When I try to use the SMB option in external storage, the option isn't in the drop down because the package smb is not installed.  BUT, of course, this is windows, so there is no formal package for SMB on windows. 

So technically you can't enable this at all.  So we deactivate the check for the package, and get the drop down - but then it can't mount.  So that didn't work.

Then, we try to mount a local filesystem instead.  Select local.  Except in this case, the local filesystem doesn't recognize the path to a mounted folder that is not c: in php on windows.

So essentially, it is impossible to mount SMB filesystems and use them in ownCloud on Windows...which is sort of silly, you would think it would be easy since SMB is windows.

We will need to be able to get this resolved at some point.

**Comment by PVince81** [comment]
So does it mean this will be a completely new project, possibly a special Storage backend just for connecting to SMB on Windows ?
