### ISSUE TITLE
encryption util excludedPaths is different to excluded usernames constants

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39573]
https://github.com/owncloud/core/blob/master/lib/public/User/Constants.php has:
`DIRECTORIES_THAT_ARE_NOT_USERS`
`FILES_THAT_ARE_NOT_USERS`

These keep the lists of strings that should not be allowed as usernames.

https://github.com/owncloud/core/blob/master/lib/private/Encryption/Util.php has `excludedPaths`
The constructor fills in the array with the names of files and directories that should be excluded from processing by encryption.
```
		$this->excludedPaths[] = 'files_encryption';
		// contains certificates
		$this->excludedPaths[] = 'files_external';
		$this->excludedPaths[] = 'avatars';
		$this->excludedPaths[] = 'avatar.png';
		$this->excludedPaths[] = 'avatar.jpg';
```

Maybe that list for encryption should be in-sync-with (the same as?) the lists of strings that cannot be usernames?

And have the list in one place, that is used the same everywhere.

**Comment by phil-davis** [comment]
@JanAckermann @IljaN @jvillafanez and others - please give you thoughts.
This could easily be sorted out...

**Comment by jvillafanez** [comment]
I think they represent different things, so it's ok if there are different lists for each of them. For example, the "meta" directory could need to be encrypted (I'm not sure about the current state, maybe not) or we might need to encrypt data outside of the users folder.
If we sync the lists, that would mean that any folder that doesn't represent a user won't be encrypted, which might be wrong.

You could also think that the "directories that aren't users" is a way to mitigate the terrible decision of having additional data inside a folder that should only contain user's data. As said, the purpose of those 2 variables is different.

**Comment by phil-davis** [comment]
One question is:

Is the encryption list in https://github.com/owncloud/core/blob/master/lib/private/Encryption/Util.php correct?
Or are there some folder/file names that should be added?

**Comment by jvillafanez** [comment]
Unless there is a reason not to encrypt the folder, I think all the folders should be considered as "encryptable".
I'm not sure what the "meta" folder contains (maybe @JanAckermann knows), but it doesn't seem a must-not-encrypt folder. Other than that folder, I don't think there isn't any new folder that we need to check.

**Comment by JammingBen** [comment]
I agree with @jvillafanez , these two represent different things.

I'm pretty sure this list is good/complete as it is. The names in `excludedPaths` are only checked in `isExcluded()` (see https://github.com/owncloud/core/blob/master/lib/private/Encryption/Util.php#L340) and have to be in a certain positions of the path to evaluate to "is excluded". So we're dealing with a special case here.

> I'm not sure what the "meta" folder contains

Both Jan and me don't now what this folder is for. @phil-davis Do you maybe know, it seems that you introduced this some time ago: https://github.com/owncloud/core/commit/4aa37a8ef53bae9a93f4f1dcc5fb221ddec3bf14#diff-de2bc523f24a5389c1b49a15dafb6eff26e5cd79939095478e127aede2825072

**Comment by phil-davis** [comment]
> Do you maybe know, it seems that you introduced this some time ago

I introduced the checks to ban a username "meta". The discussion about "meta" is in issue #32547

**Comment by phil-davis** [comment]
"somebody" feel free to close this if we are happy that the encryption `excludedPaths` has correct data.
