### ISSUE TITLE
provisioning API report is incomplete when user name casing is not exact

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39577]
Seen in 10.9.0 beta1

In https://github.com/owncloud/core/issues/36139#issuecomment-923832433 @phil-davis reported that quota details are missing, when unexpected upper case is used on a username.
This is still reproduced in 10.9.0 beta1

**Comment by JammingBen** [comment]
Tried to reproduce this, but everything looks fine for me, regardless of the casing. One thing to notice though: Curling a user that has never logged in (`curl -u admin:admin http://172.17.0.1:8080/ocs/v2.php/cloud/users/uu1`) results in missing quota details - this is expected IMO.

@phil-davis @jnweiger Could you please re-evaluate? Am I missing something?

**Comment by phil-davis** [comment]
> Could you please re-evaluate? Am I missing something?

I can reproduce, and I have a fix coming... Making tests to confirm it.

**Comment by phil-davis** [comment]
See PR #39586

**Comment by JammingBen** [comment]
Has been merged -> closing.
