### ISSUE TITLE
[QA] name clash: user name htaccesstest.txt  should be prevented

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39570]
Seen in 10.9.0 beta1

The /var/www/owncloud/data folder contains

```
total 172
drwxrwx---  5 www-data www-data   4096 Dec  8 01:35 ./
drwxr-xr-x 14 www-data www-data   4096 Dec  8 01:31 ../
-rw-r--r--  1 www-data www-data    323 Dec  8 01:34 .htaccess
-rw-rw-r--  1 www-data www-data      0 Dec  8 01:34 .ocdata
drwxr-xr-x  6 www-data www-data   4096 Dec  8 01:24 admin/
drwxr-xr-x  2 www-data www-data   4096 Dec  8 01:16 avatars/
drwxr-xr-x  2 www-data www-data   4096 Dec  8 01:16 files_external/
-rw-r--r--  1 www-data www-data    145 Dec  8 01:35 htaccesstest.txt
-rw-rw-r--  1 www-data www-data      0 Dec  8 01:34 index.html
-rw-r--r--  1 www-data www-data   4096 Dec  8 01:29 owncloud.db
-rw-r-----  1 www-data www-data 135325 Dec  8 01:47 owncloud.log
```

User names can possibly collide with the other entries in this folder.
All of them are properly prevented (e.g. "Error creating user: The special username avatars is not allowed") except for htaccesstest.txt

Followup on https://github.com/owncloud/core/issues/39205
(Sorry for these minor nitpicks)

**Comment by phil-davis** [comment]
That file has been used by code for a long time:
https://github.com/owncloud/core/blob/master/settings/Panels/Admin/SecurityWarning.php
```
	public function getPanel() {
		// create htaccess test file
		$util = new \OC_Util();
		$util->createHtaccessTestFile($this->config);
...
```

I don't have one in my local environment, but I usually just run the PHP dev server locally, and the code path does not create it in that case.

Even if it is a "tmeporary"  file that is not always there, it will cause pain if some installation creates a username `htaccesstest.txt` !

**Comment by JammingBen** [comment]
Fixed via https://github.com/owncloud/core/pull/39572
