### ISSUE TITLE
Temporary maintenance mode of federated server breaks sharing

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39576]
Seen on 10.9.0 beta1 while testing  https://github.com/owncloud/core/pull/38474

* create two machines fed1 and fed2
* all as admin users:
  * prepare a folder Photos_from_fed1 on server fed1
  * prepare a folder Photos_from_fed2 on server fed2
* connect a desktop client to both accounts, wait for sync to complete.
* mutually share the folders to the other server and accept the shares there.
* put server fed1 in maintenance mode.
* on server fed2 try to access the folder Photos_from_fed1 via web UI. An error occurs. OK
![Screenshot from 2021-12-08 19-22-46](https://user-images.githubusercontent.com/1108546/145263991-7c417cdc-d154-4e20-9cca-7f969ddccca3.png)
----

* within the desktop sync folder navigate to the folder Photos_from_fed1 and add a test.txt file. An error occurs. OK
![Screenshot from 2021-12-08 19-21-20](https://user-images.githubusercontent.com/1108546/145263993-dd159d6e-4a96-47be-bb2c-9496c0a60030.png)
----
* on server fed2 unshare the folder Photos_from_fed2
* on server fed1 switch off maintenance mode.
* on server fed2 try to access the folder Photos_from_fed1 via web UI. The same error still occurs. BAD.
![Screenshot from 2021-12-08 19-25-41](https://user-images.githubusercontent.com/1108546/145263984-c928bc33-cb39-413b-9c32-4f75d88d71ab.png)
----
* on server fed1 visit inbound shares. The folder Photos_from_fed2 is gone, without a notice. BAD.
![Screenshot from 2021-12-08 19-24-43](https://user-images.githubusercontent.com/1108546/145263989-0f9134eb-5e34-408b-841d-a2e2449a0c8c.png)

Expected behaviour:
* share Photos_from_Fed1 should reconnect, when fed1 comes back online.
* "to be done" items from https://github.com/owncloud/core/pull/38474 should be visible.
   * e.g. "provide most basic notification"

**Comment by jnweiger** [comment]
@mrow4a Not sure if my expectations are correct. Please confirm.

**Comment by mrow4a** [comment]
@jnweiger I think the behaviour here might be expected. The problem: there is mechanism in [Storage Availability](https://github.com/owncloud/core/blob/v10.8.0/lib/private/Files/Storage/Wrapper/Availability.php#L32-L40 ) that it would only recheck if storage was last available 10 minutes ago. 

The information on availability is stored in [oc_storages table](https://github.com/owncloud/core/blob/v10.8.0/lib/private/Files/Cache/Storage.php#L226-L235)
