### ISSUE TITLE
The Calendar App is not accessible by OAUTH2 authorization

### ISSUE THREAD

**Issue by a-sanders** [owncloud/core#39582]
Hello,

I’m using ownCloud 10.8.0.4 Community edition. There is an activated Calendar application. And I just activated the OAuth2 application. I have done it hoping to access the calendar from my code through oauth2 instead of login/password.

I’ve checked the access to protected URL “https://{{server}}/ocs/v1.php/cloud/capabilities” by OAuth2 and it works as expected without any issues.

When I read events from Calendar using HTTP request with authorization “Basic” by login/password I got all the expected data. 

### Steps to reproduce
My request looks like this:

```
REPORT https://{{server}}/remote.php/dav/calendars/{{user}}/{{calendar}} HTTP/1.1
User-Agent: Mozilla/5.0
Content-Type: application/xml; charset="utf-8"
Authorization: ......

<?xml version='1.0' encoding='utf-8'?>
<C:calendar-query xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
    <D:prop>
        <C:calendar-data/>
    </D:prop>
    <C:filter>
        <C:comp-filter name="VCALENDAR"><C:comp-filter name="VEVENT"/>
        </C:comp-filter>
    </C:filter>
</C:calendar-query>
```

### Actual behaviour

When I tried to make the same request using authorization “Bearer” by Oauth2 token I’ve got something weird and unexpected:

```
HTTP/1.1 404 Not Found
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File not found: USER_NAME in 'principals'</s:message>
</d:error>
```

I’ve tested the case with the official docker container owncloud/server too and I got the same results.
So it looks there is a bug in some part of ownCloud related to OAuth2.

#### ownCloud log (data/owncloud.log)
[owncloud.log](https://github.com/owncloud/core/files/7693624/owncloud.log)

There are 3 records related to the issue in the owncloud.log:
1)
```
{
"reqId": "YZuBuqkKn29YeRuiHw5ZCAAAAEA",
"level": 0,
"time": "2021-11-22T12:40:42+01:00",
"remoteAddr": "xxx.xxx.xxx.xxx",
"user": "--",
"app": "OC\\Authentication\\Token\\DefaultTokenProvider::invalidateToken",
"method": "GET",
"url": "\/remote.php\/dav\/calendars\/USER_NAME\/CALENDAR_NAME\/?export",
"message": "invalidating token c764fe1fe4ab9e365010dd16531214d05e22099ff8b3a1f613e176d9667199310365b2eb4f9c4ab30970a27b9b83ad0e8e81042b6a9e537ec23d827b78f0c2c5"
}
```

2)
```
{
"reqId": "YZuBuqkKn29YeRuiHw5ZCAAAAEA",
"level": 0,
"time": "2021-11-22T12:40:42+01:00",
"remoteAddr": "xxx.xxx.xxx.xxx",
"user": "--",
"app": "OC\\Authentication\\Token\\DefaultTokenProvider::generateToken",
"method": "GET",
"url": "\/remote.php\/dav\/calendars\/USER_NAME\/CALENDAR_NAME\/?export",
"message": "generating token c764fe1fe4ab9e365010dd16531214d05e22099ff8b3a1f613e176d9667199310365b2eb4f9c4ab30970a27b9b83ad0e8e81042b6a9e537ec23d827b78f0c2c5, uid USER_NAME, loginName USER_NAME, pwd empty, name python-requests\/2.26.0, type temporary"
}
```

3)
```
{
"reqId": "YZuBuqkKn29YeRuiHw5ZCAAAAEA",
"level": 0,
"time": "2021-11-22T12:40:42+01:00",
"remoteAddr": "xxx.xxx.xxx.xxx",
"user": "USER_NAME",
"app": "webdav",
"method": "GET",
"url": "\/remote.php\/dav\/calendars\/USER_NAME\/CALENDAR_NAME\/?export",
"message": "Exception: HTTP\/1.1 404 File not found: USER_NAME in 'principals': {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"File not found: USER_NAME in 'principals'\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(78): Sabre\\\\DAV\\\\SimpleCollection->getChild('USER_NAME')\\n#1 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/apps\\\/dav\\\/lib\\\/Tree.php(51): Sabre\\\\DAV\\\\Tree->getNodeForPath('principals\\\/USER...')\\n#2 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(335): OCA\\\\DAV\\\\Tree->getNodeForPath('principals\\\/USER...')\\n#3 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(388): Sabre\\\\DAVACL\\\\Plugin->getPrincipalMembership('principals\\\/USER...')\\n#4 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(641): Sabre\\\\DAVACL\\\\Plugin->principalMatchesPrincipal('principals\\\/user...')\\n#5 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(199): Sabre\\\\DAVACL\\\\Plugin->getCurrentUserPrivilegeSet(Object(OCA\\\\DAV\\\\CalDAV\\\\Calendar))\\n#6 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/DavAclPlugin.php(51): Sabre\\\\DAVACL\\\\Plugin->checkPrivileges('calendars\\\/USER_...', Array, 1, false)\\n#7 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(846): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\DavAclPlugin->checkPrivileges('calendars\\\/USER_...', '{DAV:}read')\\n#8 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAVACL\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\DAV\\\\Server->emit('beforeMethod:GE...', Array)\\n#10 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/apps\\\/dav\\\/lib\\\/Server.php(334): Sabre\\\\DAV\\\\Server->start()\\n#12 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#13 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/remote.php(165): require_once('\\\/www\\\/htdocs\\\/w99...')\\n#14 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/SimpleCollection.php\",\"Line\":97}"
}
```

### Server configuration
ownCloud 10.8.0.4 Community edition
Official docker container owncloud/server

**Comment by a-sanders** [comment]
BTW the latest log message has exception info:
```
{
"Exception": "Sabre\DAV\Exception\NotFound",
"Message": "File not found: USER_NAME in 'principals'",
"Code": 0,
"Trace": "......"
"File": "/www/htdocs/w999999e/domain.tld/lib/composer/sabre/dav/lib/DAV/SimpleCollection.php",
"Line": 97
}
```

I’ve decoded and prettified the trace data a bit:
```
#0 /www/htdocs/w999999e/domain.tld/lib/composer/sabre/dav/lib/DAV/Tree.php(78): Sabre\DAV\SimpleCollection->getChild('USER_NAME')
#1 /www/htdocs/w999999e/domain.tld/apps/dav/lib/Tree.php(51): Sabre\DAV\Tree->getNodeForPath('principals/USER...')
#2 /www/htdocs/w999999e/domain.tld/lib/composer/sabre/dav/lib/DAVACL/Plugin.php(335): OCA\DAV\Tree->getNodeForPath('principals/USER...')
#3 /www/htdocs/w999999e/domain.tld/lib/composer/sabre/dav/lib/DAVACL/Plugin.php(388): Sabre\DAVACL\Plugin->getPrincipalMembership('principals/USER...')
#4 /www/htdocs/w999999e/domain.tld/lib/composer/sabre/dav/lib/DAVACL/Plugin.php(641): Sabre\DAVACL\Plugin->principalMatchesPrincipal('principals/user...')
#5 /www/htdocs/w999999e/domain.tld/lib/composer/sabre/dav/lib/DAVACL/Plugin.php(199): Sabre\DAVACL\Plugin->getCurrentUserPrivilegeSet(Object(OCA\DAV\CalDAV\Calendar))
#6 /www/htdocs/w999999e/domain.tld/apps/dav/lib/Connector/Sabre/DavAclPlugin.php(51): Sabre\DAVACL\Plugin->checkPrivileges('calendars/USER_...', Array, 1, false)
#7 /www/htdocs/w999999e/domain.tld/lib/composer/sabre/dav/lib/DAVACL/Plugin.php(846): OCA\DAV\Connector\Sabre\DavAclPlugin->checkPrivileges('calendars/USER_...', '{DAV:}read')
#8 /www/htdocs/w999999e/domain.tld/lib/composer/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAVACL\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#9 /www/htdocs/w999999e/domain.tld/lib/composer/sabre/dav/lib/DAV/Server.php(456): Sabre\DAV\Server->emit('beforeMethod:GE...', Array)
#10 /www/htdocs/w999999e/domain.tld/lib/composer/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#11 /www/htdocs/w999999e/domain.tld/apps/dav/lib/Server.php(334): Sabre\DAV\Server->start()
#12 /www/htdocs/w999999e/domain.tld/apps/dav/appinfo/v2/remote.php(31): OCA\DAV\Server->exec()
#13 /www/htdocs/w999999e/domain.tld/remote.php(165): require_once('/www/htdocs/w99...')
#14 {main}
```

**Comment by a-sanders** [comment]
> Hello,
> 
> I’m using ownCloud 10.8.0.4 Community edition. There is an activated Calendar application. And I just activated the OAuth2 application. I have done it hoping to access the calendar from my code through oauth2 instead of login/password.
> 
> I’ve checked the access to protected URL “https://{{server}}/ocs/v1.php/cloud/capabilities” by OAuth2 and it works as expected without any issues.
> 
> When I read events from Calendar using HTTP request with authorization “Basic” by login/password I got all the expected data.
> ### Steps to reproduce
> 
> My request looks like this:
> 
> ```
> REPORT https://{{server}}/remote.php/dav/calendars/{{user}}/{{calendar}} HTTP/1.1
> User-Agent: Mozilla/5.0
> Content-Type: application/xml; charset="utf-8"
> Authorization: ......
> 
> <?xml version='1.0' encoding='utf-8'?>
> <C:calendar-query xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
>     <D:prop>
>         <C:calendar-data/>
>     </D:prop>
>     <C:filter>
>         <C:comp-filter name="VCALENDAR"><C:comp-filter name="VEVENT"/>
>         </C:comp-filter>
>     </C:filter>
> </C:calendar-query>
> ```
> 
> ### Actual behaviour
> 
> When I tried to make the same request using authorization “Bearer” by Oauth2 token I’ve got something weird and unexpected:
> 
> ```
> HTTP/1.1 404 Not Found
> Content-Type: application/xml; charset=utf-8
> 
> <?xml version="1.0" encoding="utf-8"?>
> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
>   <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
>   <s:message>File not found: USER_NAME in 'principals'</s:message>
> </d:error>
> ```
> 
> I’ve tested the case with the official docker container owncloud/server too and I got the same results. So it looks there is a bug in some part of ownCloud related to OAuth2.
> ### Logs
> #### ownCloud log (data/owncloud.log)
> 
> [owncloud.log](https://github.com/owncloud/core/files/7693624/owncloud.log)
> 
> There are 3 records related to the issue in the owncloud.log: 1)
> 
> ```
> {
> "reqId": "YZuBuqkKn29YeRuiHw5ZCAAAAEA",
> "level": 0,
> "time": "2021-11-22T12:40:42+01:00",
> "remoteAddr": "xxx.xxx.xxx.xxx",
> "user": "--",
> "app": "OC\\Authentication\\Token\\DefaultTokenProvider::invalidateToken",
> "method": "GET",
> "url": "\/remote.php\/dav\/calendars\/USER_NAME\/CALENDAR_NAME\/?export",
> "message": "invalidating token c764fe1fe4ab9e365010dd16531214d05e22099ff8b3a1f613e176d9667199310365b2eb4f9c4ab30970a27b9b83ad0e8e81042b6a9e537ec23d827b78f0c2c5"
> }
> ```
> 
> 
> ```
> {
> "reqId": "YZuBuqkKn29YeRuiHw5ZCAAAAEA",
> "level": 0,
> "time": "2021-11-22T12:40:42+01:00",
> "remoteAddr": "xxx.xxx.xxx.xxx",
> "user": "--",
> "app": "OC\\Authentication\\Token\\DefaultTokenProvider::generateToken",
> "method": "GET",
> "url": "\/remote.php\/dav\/calendars\/USER_NAME\/CALENDAR_NAME\/?export",
> "message": "generating token c764fe1fe4ab9e365010dd16531214d05e22099ff8b3a1f613e176d9667199310365b2eb4f9c4ab30970a27b9b83ad0e8e81042b6a9e537ec23d827b78f0c2c5, uid USER_NAME, loginName USER_NAME, pwd empty, name python-requests\/2.26.0, type temporary"
> }
> ```
> 
> 
> ```
> {
> "reqId": "YZuBuqkKn29YeRuiHw5ZCAAAAEA",
> "level": 0,
> "time": "2021-11-22T12:40:42+01:00",
> "remoteAddr": "xxx.xxx.xxx.xxx",
> "user": "USER_NAME",
> "app": "webdav",
> "method": "GET",
> "url": "\/remote.php\/dav\/calendars\/USER_NAME\/CALENDAR_NAME\/?export",
> "message": "Exception: HTTP\/1.1 404 File not found: USER_NAME in 'principals': {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Message\":\"File not found: USER_NAME in 'principals'\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(78): Sabre\\\\DAV\\\\SimpleCollection->getChild('USER_NAME')\\n#1 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/apps\\\/dav\\\/lib\\\/Tree.php(51): Sabre\\\\DAV\\\\Tree->getNodeForPath('principals\\\/USER...')\\n#2 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(335): OCA\\\\DAV\\\\Tree->getNodeForPath('principals\\\/USER...')\\n#3 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(388): Sabre\\\\DAVACL\\\\Plugin->getPrincipalMembership('principals\\\/USER...')\\n#4 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(641): Sabre\\\\DAVACL\\\\Plugin->principalMatchesPrincipal('principals\\\/user...')\\n#5 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(199): Sabre\\\\DAVACL\\\\Plugin->getCurrentUserPrivilegeSet(Object(OCA\\\\DAV\\\\CalDAV\\\\Calendar))\\n#6 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/DavAclPlugin.php(51): Sabre\\\\DAVACL\\\\Plugin->checkPrivileges('calendars\\\/USER_...', Array, 1, false)\\n#7 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(846): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\DavAclPlugin->checkPrivileges('calendars\\\/USER_...', '{DAV:}read')\\n#8 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/WildcardEmitterTrait.php(89): Sabre\\\\DAVACL\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\DAV\\\\Server->emit('beforeMethod:GE...', Array)\\n#10 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/apps\\\/dav\\\/lib\\\/Server.php(334): Sabre\\\\DAV\\\\Server->start()\\n#12 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#13 \\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/remote.php(165): require_once('\\\/www\\\/htdocs\\\/w99...')\\n#14 {main}\",\"File\":\"\\\/www\\\/htdocs\\\/w999999e\\\/domain.tld\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/SimpleCollection.php\",\"Line\":97}"
> }
> ```
> 
> ### Server configuration
> 
> ownCloud 10.8.0.4 Community edition Official docker container owncloud/server

**Comment by ho4ho** [comment]
May app password work?

https://doc.owncloud.com/server/next/user_manual/personal_settings/security.html#app-passwords-tokens

**Comment by a-sanders** [comment]
> May app password work?
> 
Yes, it works. As I said at the very beginning - the authentication "Basic" works without any issues. But the issue related to another authentication type - “Bearer” by Oauth2 token.
