### ISSUE TITLE
Need support for Draw/Diagram document type

### ISSUE THREAD

**Issue by merttumer** [owncloud/core#39593]
Right now ownCloud does not have application/vnd.oasis.opendocument.graphics mimetype support. e.g. odf type Diagram/Draw documents. Collabora Online/richdocuments application has support for opening and editing Draw document type. Problem with that is there's no icon in "core/img/filetypes/x-office-drawing.svg" also COOL has the ability to create this documents but we need the mimetype support in TemplateManager. It can be added in the extension manually but it would be better to add it to core I guess.
![image](https://user-images.githubusercontent.com/6226481/145991050-a0e50062-6c42-40cd-a172-010b24dd9a29.png)

I created pr in richdocuments where creating this document type is possible under + menu. However it needs the icon change and TemplateManager addition. 
pr: https://github.com/owncloud/richdocuments/pull/436

**Comment by JammingBen** [comment]
Thx for reporting. We quickly added the mimetype support via https://github.com/owncloud/core/pull/39594, which will be included in the upcoming 10.9 release.
