### ISSUE TITLE
Folders with very short names are hard to open in Web UI

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39591]
Seen in 10.9.0 RC1

* at the web UI create a folder namend 'I' 
* click slightly left if the I, the checkbox toggles.
* click slightly right of the I, the details sidebar opens
![image](https://user-images.githubusercontent.com/1108546/145968987-7b370567-1217-4f0d-a49e-bee264b3b09d.png)

The mousepointer in this position is already too far to the left, although it is only 2 or 3 pixels off.
To the right, one pixel off is already too much. On a thin letter I, the active area seems to be only 3 or 4 pixels wide.

Expected behaviour:
* the active area should be padded left and right, so that very short names still have a sufficiently large target area.
* The mouse should give visual feedback when crossing the border between checkbox and name. Maybe a two pixel inactive gap in between or a different shape?

**Comment by phil-davis** [comment]
@jnweiger is the fix wanted for 10.9.0?
The PR has been merged to master.
