### ISSUE TITLE
Add API acceptance test for zero byte copy

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39595]
See https://github.com/owncloud/ocis/issues/2868

We should have an API acceptance test for this case of copying a zero-byte file, so that we ensure that it works correctly and the same in both oC10 and oCIS.

Add a test scenarios for zero-byte file:
- upload
- download
- move
- rename
- delete

**Comment by kiranparajuli589** [comment]
@grgprarup is currently working in this.
