### ISSUE TITLE
Add more test scenarios for the new version metadata feature

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39601]
The feature is currently only in the `release-10.9.0` branch, so branch from there and make a PR with more acceptance test scenarios for this. (We will probably not actually merge the PR to the release branch, but will merge to master after the release is finished. It depends if we find bugs...)

This will demonstrate that various combinations of actions preserve the version author information for a file with version history.

The first scenario was already added in #39516 and is merged in the release branch.

https://github.com/owncloud/core/pull/39516/files#diff-7914a4efca9905b7e32892b749f72ac8e62facedc6a8bb2a4b5fddefcd5c4f9c

Add more scenarios to demonstrate things like:

- file in a folder shared to a group
- file shared directly to multiple users
- file shared directly to a group
- file renamed after it already has version history
- file moved in/out of a subfolder after it already has version history
- file moved in/out of a share after it already has version history
- other interesting things that could happen to a file,...

and make sure that the version history with version authors is correctly preserved.

**Comment by kiranparajuli589** [comment]
@amrita-shrestha is currently working on this.
