### ISSUE TITLE
Calculate personal space id in tests when running on reva

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39617]
PR #39612 added code to allow the API acceptance tests to access a user's resources (files/folders) via their personal space id. That is a new way to access resources through webDAV. That code is running in oCIS and there is currently just a single test scenario for it.

See commit https://github.com/owncloud/core/pull/39612/commits/a4764208b90e05bf519c41de2b6cd186165f5fc6

`getPersonalSpaceIdForUser()` queries `graph/v1.0/me/drives` to get the list of spaces for a user, and gets the space-id of the user's personal space. That works on oCIS. But that endpoint is not available on reva.

The space id of a user's personal space is the user's UUID.

Adjust the test code so that `getPersonalSpaceIdForUser()` returns the user's UUID when running on oCIS.

That will make it possible for the test scenario(s) to pass on reva.

**Comment by kiranparajuli589** [comment]
done with https://github.com/owncloud/core/pull/39751
