### ISSUE TITLE
[transifex] error of the translation of the settings

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/core#39628]
I have improved the translations in the settings for "These are the web, desktop and mobile clients currently logged in to your .". It would be great if someone saves my suggestion.

The url is MYCLOUD/settings/personal?sectionid=security

For de:
https://www.transifex.com/owncloud-org/owncloud/translate/#de/settings-1/137219200?q=text%3A'These+are+the+web%2C+desktop+and+mobile+clients+currently+logged+in+to+your+%25s.'

For de_DE:
https://www.transifex.com/owncloud-org/owncloud/translate/#de_DE/settings-1/137219200?q=text%3A'These+are+the+web%2C+desktop+and+mobile+clients+currently+logged+in+to+your+%25s.'

**Comment by prsnbrg** [comment]
![image](https://user-images.githubusercontent.com/29964525/148246698-dd43c7f7-b5b4-4309-ab3e-6c8c66900106.png)

Language: Deutsch (förmlich: sie) - de_DE

**Comment by prsnbrg** [comment]
@phil-davis Can you take a look and assign it to someone if necessary?
It would be great to fix this.

**Comment by phil-davis** [comment]
I am not a Deutsch speaker, and do not have the needed Transifex access or knowledge of Deutsch.

@micbar who reviews and approves Transifex changes?

**Comment by prsnbrg** [comment]
@JammingBen can you take a look?

**Comment by prsnbrg** [comment]
@jnweiger can you take a look and possible fix this for 10.11 or 10.12?

**Comment by prsnbrg** [comment]
Ping

**Comment by DeepDiver1975** [comment]
both suggestion accepted -> close

THX @prsnbrg
