### ISSUE TITLE
Thumb nail generator fails with text files with BOM

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39645]
Seen with 10.9.1RC1 (but probably unrelated to the specific release)

* Create a text file via web interface.
* edit the text file with collabora office
* confirm the edits in text editor. the bom is visible as a red dot. OK
![image](https://user-images.githubusercontent.com/1108546/148223790-3a50ec7e-3242-4590-aab6-1cfc4b7fce30.png)

* the thumbnail shows only empty squares:
![image](https://user-images.githubusercontent.com/1108546/148223735-5513c035-da66-47eb-aaf6-11158330a0ea.png)

* The file is a plain ascii text file except for th efist two bytes, which are the well defined form of the BOM, as e.g. defined in 
![image](https://user-images.githubusercontent.com/1108546/148223762-bc685287-1baa-4a19-8790-2912ea57885f.png)

**Comment by jvillafanez** [comment]
PR merged. Closing

**Comment by jnweiger** [comment]
Confirmed fixed in 10.10.0RC1
