### ISSUE TITLE
reduce redudant information in spaces test code

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#39642]
ideas:

- [x] don't return `null` for spaces but `3` in https://github.com/owncloud/core/blob/3e14c1f6ea4179ab4c7cb6aa05ccf4bef43332bd/tests/acceptance/features/bootstrap/WebDav.php#L318-L321
- [x] `\TestHelpers\WebDavHelper::makeDavRequest` does not need `?bool $usingSpacesDavPath = false,` if `$davPathVersionToUse` is `3` for spaces, same for `\TestHelpers\WebDavHelper::getDavPath`. Alternative the decision can be made depending on if `$spaceId` is given or not

CC @phil-davis @kiranparajuli589

**Comment by kiranparajuli589** [comment]
TODO:
- [ ] do not request for the space ID before making every request
  _(save the space id for the user after the first fetch)_

@phil-davis @individual-it should we implement the test code like this?

**Comment by phil-davis** [comment]
> should we implement the test code like this?

yes, just request it once, when first needed, and save it for each user (there might be more than one user in a scenario). If the personal space-id for a user is already saved, then use that. The personal space-id does not change during a scenario!

**Comment by kiranparajuli589** [comment]
all task done
