### ISSUE TITLE
Enabling encryption while users are logged in destroys files

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39663]
Seen in 10.9.1RC1 (with encryption 1.5.1 initially disabled)

* user admin edits file shared in his folder Photos
* user admin shares the folder Photos with user user01 (full permissions)
* both edit the file.

```
occ app:enable encryption
occ encryption:enable
occ encryption:select-encryption-type masterkey -y
```

* user01 tries to edit shared.txt -- errors appear -- faint and gray and only for a few seconds (grrr!)

![image](https://user-images.githubusercontent.com/1108546/148609991-1b5d078a-8acb-428b-8cb0-680c687f5870.png)

* user01 reloads the browser tries again and gets:

![image](https://user-images.githubusercontent.com/1108546/148610069-39428adf-7281-445a-8aab-47a3412f93bc.png)

----

* admin also is asked to logout login:
![image](https://user-images.githubusercontent.com/1108546/148610175-e2eae09d-0e54-4752-95d7-4f9bc6fab1e3.png)

-----

The file already got truncated to 0 size:

```
# ll /var/www/owncloud/data/admin/files/Photos/shared.txt
-rw-r--r-- 1 www-data www-data 0 Jan  7 21:21 /var/www/owncloud/data/admin/files/Photos/shared.txt
```
----
After logout, login, the file is still in a broken state:

![image](https://user-images.githubusercontent.com/1108546/148610366-c7ff6def-6721-42fb-82a1-af6abaa2e5d7.png)

A total of 11 corrupt versions are saved. The 12th one can be restored and has actually the latest content. Phew.

**Comment by jnweiger** [comment]
Expected behaviour:
The encryption machinery does not get confused when keys are not initialized. 
To be safe, enabling encryption should log out all users immediately.

**Comment by jnweiger** [comment]
Enable encryption via admin UI runs into different errors:

 * user admin edits file shared in his folder Photos
 *  user admin shares the folder Photos with user user01 (full permissions)
 *  both edit the file.
 * admin visits the admin settings and enables encryption. A message appers to use the apps menu to add a module
 * admin visits apps -> disabled and enables encryption.
 * user01 tries to edit shared.txt -- errors appear -- faint and gray and only for a few seconds (grrr!)
    "Private key missing for user"
* admin tries to edit shared.txt and also fails.
* admin logs out, logs in again. New error, "This is a shared file as the share owner..."
* admin inspects the settings and finds "User keys already enabled"
* admin and user01 delete all edited files
* admin can now do: `occ encryption:disable; occ encryption:enable; occ encryption:select-encryption-type masterkey -y`
* admin tries to create a new text file and edit:

![image](https://user-images.githubusercontent.com/1108546/148770640-64622253-7aa6-4665-ad30-9f476dd57d73.png)

**Comment by jnweiger** [comment]
I believe the original issue is also related to confusion between user key encryption and master key encryption.

**Comment by IljaN** [comment]
Do you have an owncloud.log for this?

**Comment by JanAckermann** [comment]
Outcome from developers:
Tried to reproduce it 5 times, issue didn't pop up

**Comment by jnweiger** [comment]
> Do you have an owncloud.log for this?

yes, attached. You can log into  root@oc1091rc1-wopi-151-20220110.jw-qa.owncloud.works  and look around yourself.
I'll leave that machine alone for now.

[39663-owncloud.log.zip](https://github.com/owncloud/core/files/7839553/39663-owncloud.log.zip)

**Comment by jnweiger** [comment]
> Outcome from developers: Tried to reproduce it 5 times, issue didn't pop up
Confirmed. The issue does not appear when striclty folloiwing the steps in my initial post.
