### ISSUE TITLE
Acceptance tests for version author after restoring a version

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39677]
Add some acceptance test scenarios to cover restoring a version and check that the version author is preserved.

This will be test coverage for #39673 and whatever other combinations we think of testing.

**Comment by phil-davis** [comment]
I will get some test going, then push to #39639 "Tests 10.9.1"

After 10.9.1 is released the tests will be applied to master.

**Comment by phil-davis** [comment]
This needs a new feature file in https://github.com/owncloud/core/tree/master/tests/acceptance/features/apiVersions for checking that the version author is preserved correctly when versions are restored. It is in my ToDo list!

**Comment by phil-davis** [comment]
I removed my assignment. This can be assigned to someone else. Ping me if you need ideas for the kind of scenarios to make.

**Comment by saw-jan** [comment]
Todo:
- [ ] add file version author tests for oCIS (same as https://github.com/owncloud/core/pull/40538)
