### ISSUE TITLE
Sharing. Select user by email doesn't work

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/core#39696]
web version: 4.9.0
core version: 10.9.1 docker image

Steps:

- create as admin a new user 
- switch the web page to "new design"
- upload file 
- try to share the file with the new user. in user selection, add the user by email

Actual result: we can add user by: name(works), federationId(works) and email(doesn't work)

![Screenshot 2022-01-17 at 10 48 13](https://user-images.githubusercontent.com/84779829/149801928-104fec68-81d8-4b5c-b38b-af26057f54de.png)

![Screenshot 2022-01-17 at 10 56 26](https://user-images.githubusercontent.com/84779829/149802046-91fa257b-cd36-4fd7-a1bc-be40d4d6e966.png)

**Comment by phil-davis** [comment]
Note: with core master and the traditional core webUI this works for me.
