### ISSUE TITLE
Add tests for moving to external storage

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#39725]
Issue #39550 reports some problems with moving shared folders to external storage.

We have some tests in the `cliExternalStorage` test suite that check doing various things with `webdav_owncloud` external storage. Look at what is there and add tests as necessary to cover:

These should succeed:
- user moves their own folder to the external storage
- user moves their own file to the external storage
- user moves a folder out of external storage to their own storage
- user moves a file out of external storage to their own storage

These should get some HTTP 4xx status and a message in the response:
- user tries to move a folder that they have shared to someone, to external storage
- user tries to move a file that they have shared to someone, to external storage
- share receiver tries to move a folder that they have received from someone, to external storage
- share receiver tries to move a file that they have received from someone, to external storage

Merge the tests to core master, to "document" the existing behavior.

Then issue #39550 and PR #39584 can be worked on and the updated test expectations can be decided.

**Comment by phil-davis** [comment]
This might be an interesting introduction for someone who is learning the core API test environment.

I put QA-p2 because it will be nice to have test scenarios available to help with testing PR #39584

**Comment by SwikritiT** [comment]
@grgprarup is working on this issue
