### ISSUE TITLE
App passwords deleted after changing main password

### ISSUE THREAD

**Issue by GismoNo1** [owncloud/core#39734]
Hey there, thanks for your work on ownCloud. Today i encountered the same bug as stated here #26731. Since i can't reopen the issue i wanted to ask if you are still working on a solution?

Otherwise when the main password is changed the user needs to regenerate all app passwords. Then it would be easier to use the main passwords for all apps that need access, so the app passwords are not very useful. Would be great to have this (security) issue fixed. Thank you!

### Steps to reproduce
1. Generate and use app passwords in ownCloud.
2. Change main password for ownCloud.
3. App passwords ale deleted.

### Expected behavior
App passwords persist when main password is changed.

### Actual behavior
Tell us what happens instead

### Server configuration
ownCloud version: 10.1.1

**Comment by phil-davis** [comment]
@GismoNo1 your server version is very old. I will make an acceptance test scenario for this and see how it behaves with the current ownCloud 10.9.1

**Comment by GismoNo1** [comment]
Thank you so much. Unfortunately I'm tied to the version used by my organization. That's why the behavior encountered in v10.9.1.
