### ISSUE TITLE
Docker-compose quick-start is unusable

### ISSUE THREAD

**Issue by kmanwar89** [owncloud/core#39730]
### Steps to reproduce
1. Install a fresh image Ubuntu Server 20.04 in a VM
2. Install docker-engine, docker-compose
3. Attempt the follow the steps outlined on the [Owncloud documentation](https://doc.owncloud.com/server/10.9/admin_manual/installation/docker/) for installing Owncloud using docker-compose

### Expected behaviour
The expected behavior is a user could complete the tutorial in its' entirety

### Actual behaviour
The following error is observed in the output after issuing _docker-compose up -d_

### Server configuration
**Operating system**: Ubuntu 20.04

![image](https://user-images.githubusercontent.com/11323060/151685316-e3ea9375-0f27-4c9f-b286-fc4b5d99fbd9.png)

**Web server:** Apache 2.4.41

**Database:** mysql/mariaDB v15.1 Distrib 10.3.32

**PHP version:** 7.4.3

**ownCloud version:** N/A

**Updated from an older ownCloud or fresh install:** Fresh install

**Where did you install ownCloud from:** Owncloud-provided docker-compose file

**Signing status (ownCloud 9.0 and above):** Unsure how to find this information

**I've removed many of the fields that are requested because I'm not able to get further along in the install in order to even get that information. Any help with this is greatly appreciated; I have attempted to Google and search for existing issues without much luck.**

Evidence of error:
![image](https://user-images.githubusercontent.com/11323060/151685224-5bd86f3b-15f0-4d30-8090-41a8cdca8205.png)

Docker-compose file provided by Owncloud:
[docker-compose_fail.yml.txt](https://github.com/owncloud/core/files/7965239/docker-compose_fail.yml.txt)

```
kadar@shadowcloud:~/owncloud_docker$ apache2 -v
Server version: Apache/2.4.41 (Ubuntu)
Server built:   2022-01-05T14:49:56
kadar@shadowcloud:~/owncloud_docker$ php -v
PHP 7.4.3 (cli) (built: Nov 25 2021 23:16:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
kadar@shadowcloud:~/owncloud_docker$ mysql -V
mysql  Ver 15.1 Distrib 10.3.32-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**Comment by hydrocat** [comment]
the versions of apache2 ad php shouldn't matter as they are configured inside the container.

What are the contents of your `docker-file.yml` ?

**Comment by kmanwar89** [comment]
> the versions of apache2 ad php shouldn't matter as they are configured inside the container.
> 
> What are the contents of your `docker-compose.yml` ?

I mentioned the apache/PHP versions as that is part of the issue template for when I raised the issue.

I'm using the docker-compose.yml file [provided straight from Owncloud](https://doc.owncloud.com/server/10.9/admin_manual/installation/docker/#docker-compose).  Please let me know if you need any further information.

**Comment by kmanwar89** [comment]
I just tested using the same compose file on an Ubuntu Server 21.10 machine and it seems to work. Perhaps it's a dependency issue, but that wouldn't explain the Python 3-specific syntax error, would it?

**Comment by jnweiger** [comment]
I'd guess that docker-compose is broken on your machine. The python error is about versions. Do you have a mix of python2 and python3 installed?
Can you confirm, that some other `docker-compose up` would work?
Here is a basic `docker-compose.yml` you can try:
```
db_1  | 2022-02-11 15:06:10 0 [Note] mariadbd: ready for connections.
db_1  | Version: '10.6.5-MariaDB-1:10.6.5+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
```
When you run `docker-compose up` in the same folder where this yml file is, you should get a lot of output ending in something similar to:
```
...
db_1  | 2022-02-11 15:06:10 0 [Note] mariadbd: ready for connections.
db_1  | Version: '10.6.5-MariaDB-1:10.6.5+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
```

**Comment by kmanwar89** [comment]
Hi there, thanks for your response. I'll respond inline:

> I'd guess that docker-compose is broken on your machine. The python error is about versions. Do you have a mix of python2 and python3 installed? 

This is a fresh Ubuntu 20.04 VM, so should only contain what is installed by default. I double checked and only see Python 3.8.  

![image](https://user-images.githubusercontent.com/11323060/153715672-b1702148-e34e-4ed9-8840-8af9533cfe44.png)

Entirely curious - where do you see an error about versions? The last line in the traceback seems to point to a TypeError, unless I'm interpreting it incorrectly?

Can you confirm, that some other `docker-compose up` would work? Here is a basic `docker-compose.yml` you can try:
> 
> ```
> version: '3'
> services:
>   db:
>     image: mariadb
>     environment:
>     - MYSQL_ROOT_PASSWORD=my-secret-pw
> ```
> 
> When you run `docker-compose up` in the same folder where this yml file is, you should get a lot of output ending in something similar to:
> 
> ```
> ...
> db_1  | 2022-02-11 15:06:10 0 [Note] mariadbd: ready for connections.
> db_1  | Version: '10.6.5-MariaDB-1:10.6.5+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
> ```

I can confirm I was able to run this docker compose file without any issues. Snippet of logs below:

```
db_1  | 2022-02-12 14:39:57 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1  | 2022-02-12 14:39:57 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1  | 2022-02-12 14:39:57 0 [Note] InnoDB: 10.6.5 started; log sequence number 42347; transaction id 14
db_1  | 2022-02-12 14:39:57 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1  | 2022-02-12 14:39:57 0 [Note] Plugin 'FEEDBACK' is disabled.
db_1  | 2022-02-12 14:39:57 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
db_1  | 2022-02-12 14:39:57 0 [Note] Server socket created on IP: '0.0.0.0'.
db_1  | 2022-02-12 14:39:57 0 [Note] Server socket created on IP: '::'.
db_1  | 2022-02-12 14:39:57 0 [Note] InnoDB: Buffer pool(s) load completed at 220212 14:39:57
db_1  | 2022-02-12 14:39:57 0 [Warning] 'proxies_priv' entry '@% root@d0185db78eb5' ignored in --skip-name-resolve mode.
db_1  | 2022-02-12 14:39:57 0 [Note] mariadbd: ready for connections.
db_1  | Version: '10.6.5-MariaDB-1:10.6.5+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
```

Just to be thorough, I reverted my VM back to it's vanilla/fresh install status and did the following:

1) Installed Docker engine, docker-compose (both following the official Docker documentation) and git
2) Created the .env file as mentioned in the documentation
3) Started the container using _docker-compose up -d_

I'm not sure what changed, but I was now able to successfully use the docker-compose file. I'm fairly certain I followed these exact steps last time, and even running a side-by-side comparison I see no difference in the two files. I'm a little stumped as to what caused the error.  Maybe I installed a package that was conflicting without realizing it.

In any case, thanks for your help. If I'm able to reproduce the issue, I may re-open this issue, but will be closing it for the time being.
