### ISSUE TITLE
[QA] upgrade 10.8 to 10.9 fails on Ubuntu 18.04 - rollback is not possible

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39783]
Seen with owncloud complete 10.8.0 running on Ubuntu 18.04
The system is running with php-7.2.24 -- that is sufficient for owncloud 10.8 -- but (probably unknown to the user) not for 10.9

* Admin is greeted with `ownCloud 10.9.1 is available. Get more information on how to update.`

* Admin goes to
Settings->Admin->General
  -> Updater -> Open updater
        -> Start
![image](https://user-images.githubusercontent.com/1108546/153620672-25b9f6b1-2a86-47d4-9aaf-c29c2be58096.png)
----

* The Web-UI is now  unusable:
![image](https://user-images.githubusercontent.com/1108546/153620782-99a340b5-d358-4055-908a-2a3fd459367e.png)
----

* Admin logs in to Linux as root and tries to rescue the situation with
```
sudo -E -u www-data /usr/bin/php /var/www/owncloud/occ upgrade
This version of ownCloud requires at least PHP 7.3.0
You are currently running PHP 7.2.24-0ubuntu0.18.04.10. Please update your PHP version.
```

In case updating the PHP version is not an option, the admin would want to use the checkpoint
that was created during the owncloud upgrade attempt.

Expected behaviour:
 - The online updater ends with a more helpful diagnostics than `undefined`
 - occ would still run.
 - There is instructions how to roll back to a checkpoint.

**Comment by jnweiger** [comment]
Manual rollback:
```
cd /var/www/owncloud/data/updater-data/checkpoint/
ls
10.7.0.4-62066d5b4a6b8  10.8.0.4-62067848e49ab
cd 10.8.0.4-62067848e49ab

ls -la
total 16
drwxr-xr-x  4 www-data www-data 4096 Feb 11 14:52 .
drwxr-xr-x  4 www-data www-data 4096 Feb 11 14:52 ..
drwxr-xr-x 53 www-data www-data 4096 Feb 11 14:53 apps
drwxr-xr-x 10 www-data www-data 4096 Feb 11 14:52 core

cp -a core/* /var/www/owncloud/
cp -a apps/* /var/www/owncloud/apps/
```

**Comment by jnweiger** [comment]
PhP upgrade procedure (instead of the rollback)

```
sudo add-apt-repository ppa:ondrej/php
sudo apt-get install -y php7.4
for pkg in $(dpkg -l php7.2-* | cut -d' ' -f3); do
  newpkg=php7.4-$(echo $pkg | cut -d- -f2)
  echo $newpkg
  apt install -y $newpkg
done

sudo a2dismod php7.2
sudo a2enmod php7.4
systemctl restart apache2
occ upgrade
```

The ownCloud we
In case you get php-8.1 installed, this will also not work with owncloud-10.9 -- it can be deleted after php7.4 is installed successfully:
```
dpkg -l php8* | cut -d' ' -f3 | grep '^php' | xargs apt purge -y
```

**Comment by s-englert** [comment]
The expected behavior of the Updater would be a Warning "You run PHP 7.2.x, at least PHP 7.3 is required for oc 9.x".

**Comment by phil-davis** [comment]
Was there the same problem when PHP 7.1 was dropped? What happened for upgrades with that release?
