### ISSUE TITLE
10.9.1 Password reset not working - page just reloading on confirmation

### ISSUE THREAD

**Issue by ronnyworm** [owncloud/core#39795]
As a user when I enter a wrong password and get a mail to reset my password I expect the password to be changed and redirected to the account.
Instead the page keeps on reloading when I entered the new password and click on the confirmation button (so that I can enter a new password again which doesn't make sense).

I hope this isn't a duplicate - couldn't find anything similar.
Also I'm not sure whether this is an issue of version 10.9.1 specifically. I just recognized it there.

**Comment by phil-davis** [comment]
I just tried this sequence with the current core master (which is almost identical to 10.9.1):
- enter a wrong password when logging in
- click the "Wrong password. Reset it?" button
- receive the email
- click the link in the email, the password reset page opens
- enter a new password twice and OK
- login with the new password

Does the UI display any error message?
Is there anything in owncloud.log?

**Comment by ronnyworm** [comment]
The exact version is 10.9.1 (stable)

No, it doesn't display error messages ...

These are the relevant log lines since logout (entered the new password two times, confirm, enter two times, confirm):

`{"reqId":"e33gg09K3vDox9q7kCaw","level":0,"time":"2022-02-15T19:02:32+00:00","remoteAddr":"x.x.x.x","user":"the_username","app":"OC\\Authentication\\Token\\DefaultTokenProvider::invalidateToken","method":"GET","url":"\/logout?requesttoken=AQIfDAkrFlg7bQNpTD4qVS8XQCRTXjcnEn8\/HXs9Pgg%3D:dHrGKHo0X5O9uNN6Fxkj45UTX%2BvSOXkfr4fJl87Z0kI%3D","message":"invalidating token b35c6e00a299124c5e0927fc0ee648754190bccc3e91bb6ff9e18c98a8dcfbaf55bc277b087ed5673b3a5a14d201133b532c574d50ce80efbeb7c94d871bd61c"}
{"reqId":"VBuz5GpYsXlKpSJw2FKu","level":0,"time":"2022-02-15T19:02:32+00:00","remoteAddr":"x.x.x.x","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::invalidateToken","method":"GET","url":"\/login","message":"invalidating token 40f658798bd24f5d383895df5227cc061ee78e2f098e9afec68b76a765abfe6b7019595030c1fbd7fe6ea12083fb4bcb4889d9ca8fa9c005609046816f5fbc7e"}
{"reqId":"NwnveYmWbbwl3Bzsi9Uo","level":0,"time":"2022-02-15T19:02:42+00:00","remoteAddr":"x.x.x.x","user":"--","app":"OC\\User\\Session::login","method":"POST","url":"\/login","message":"regenerating session id for uid the_username, password set"}
{"reqId":"NwnveYmWbbwl3Bzsi9Uo","level":0,"time":"2022-02-15T19:02:42+00:00","remoteAddr":"x.x.x.x","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"POST","url":"\/login","message":"token 81e05528aef36a5f62570f9cfcaa1e9e0b854c73eb72eacfe38dd326dcc6f10853b816dd87f02eed265361722d0852c512ca4ac57af844b06ddc2e6433eaec65 does not exist"}
{"reqId":"NwnveYmWbbwl3Bzsi9Uo","level":0,"time":"2022-02-15T19:02:42+00:00","remoteAddr":"x.x.x.x","user":"--","app":"OC\\User\\Session::validateToken","method":"POST","url":"\/login","message":"token 81e05528aef36a5f62570f9cfcaa1e9e0b854c73eb72eacfe38dd326dcc6f10853b816dd87f02eed265361722d0852c512ca4ac57af844b06ddc2e6433eaec65, not found"}
{"reqId":"NwnveYmWbbwl3Bzsi9Uo","level":2,"time":"2022-02-15T19:02:42+00:00","remoteAddr":"x.x.x.x","user":"--","app":"core","method":"POST","url":"\/login","message":"Login failed: 'the_username' (Remote IP: 'x.x.x.x')"}
{"reqId":"MdYliFbIxa2JNnGrHRZB","level":0,"time":"2022-02-15T19:02:46+00:00","remoteAddr":"x.x.x.x","user":"--","app":"core","method":"POST","url":"\/lostpassword\/email","message":"Sent mail from \"{\"notification@the_username.xy\":\"ownCloud\"}\" to \"{\"the_username@xy.com\":\"the_username\"}\" with subject \"ownCloud password reset\""}
{"reqId":"XiYCuMT0fWjPXJEyPq6g","level":0,"time":"2022-02-15T19:02:59+00:00","remoteAddr":"127.0.0.1","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::invalidateToken","method":"GET","url":"\/status.php","message":"invalidating token bc2f25be52238f7332e3395e82aadac163451b4b4cbe104faf9eac81ba40291be83395d05dc4e27638c165e50285afc0ce4ccd469f85c6318f8fd4378c891970"}
{"reqId":"2miENQ4DJCiVaK3KK349","level":0,"time":"2022-02-15T19:03:01+00:00","remoteAddr":"","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::invalidateOldTokens","method":"--","url":"--","message":"invalidating old tokens"}
{"reqId":"NbKd9s7ekuWIz7qT3frM","level":0,"time":"2022-02-15T19:03:29+00:00","remoteAddr":"127.0.0.1","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::invalidateToken","method":"GET","url":"\/status.php","message":"invalidating token ada11175258c49722737ba88998d0450ac4baf2c227109d69b9c477cad54951c80a494dda6f0e3f4d6a39b05ff0e44959c8f9d0529cea77a79c067c906eabaf3"}
{"reqId":"6gHGALTjnBpHwNa4pM2v","level":0,"time":"2022-02-15T19:03:59+00:00","remoteAddr":"127.0.0.1","user":"--","app":"OC\\Authentication\\Token\\DefaultTokenProvider::invalidateToken","method":"GET","url":"\/status.php","message":"invalidating token fada23f5c90298d4000e03059d14c8a9f40c98264813d7d151b3b503b9a3e50949fd2f6803d8404505554adf7347990c25eae09bdef62aad542450f70265e139"}
`

**Comment by Simi5599** [comment]
> I just tried this sequence with the current core master (which is almost identical to 10.9.1):
> 
> * enter a wrong password when logging in
> * click the "Wrong password. Reset it?" button
> * receive the email
> * click the link in the email, the password reset page opens
> * enter a new password twice and OK
> * login with the new password
> 
> Does the UI display any error message? Is there anything in owncloud.log?

Hi, can you post your config.php (with sensitive date obfuscated)?
Maybe you altered the `password_recovery_link` option
