### ISSUE TITLE
[QA] search does not start, when using text that was pasted into search field

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39831]
Seen with search_elastic 2.1.0 RC1 in 10.9.1 - but probably unrelated to search_elastic

* write the word 'welcome' into a text document outside of owncloud.
* copy paste the word 'welcome' into the search box
* hit enter. Nothing happens. BAD
* type backspace to delete the last 'e' from 'welcome'. The search starts. Okayish
![image](https://user-images.githubusercontent.com/1108546/155713269-5056704e-039b-4462-9018-634bf26d835e.png)

Expected behaviour:
* text pasted into the seach box can be searched for, without editing.

Not a regression.

**Comment by hodyroff** [comment]
Can't reproduce on Windows/Edge, search starts immediately after word is pasted ...

**Comment by jnweiger** [comment]
Reproduced in 10.11.0-beta.2

**Comment by cristiancardosodexcom** [comment]
Also I noticed that every time that the cron job runs, the index from elastic get affected

**Comment by cristiancardosodexcom** [comment]
Why is this closed?
