### ISSUE TITLE
[acceptance tests] fix feature table indentations

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/core#39852]
there are some indentation problems in the feature tables like:
![Screenshot from 2022-03-07 11-46-35](https://user-images.githubusercontent.com/39373750/156976840-a294ec51-6c59-4163-b7bf-761f9180e9a0.png)

TODO:
- [ ] go through all features and fix the indentations

**Comment by phil-davis** [comment]
Note: the tables with Unicode strings usually do not line up anyway, depending on the UI or IDE or text terminal that is rendering the document, or the diffs, or... mono-spaced fonts for rendering regular ASCII just don't work out for complex characters in other scripts.

We do also find some Scenarios that do not have the current-standard 2-space indentation levels. So it would be useful to get those standardized.

My PHPstorm IDE lets me "reformat code" on a Gherking feature file, and does a good job. Someone could get the IDE to "reformat code" on all feature files (should be a very quick job), and submit a PR. Whatever it does to lines with Unicode, we accept its best estimate for spacing.

**Comment by kiranparajuli589** [comment]
This plugin: https://plugins.jetbrains.com/plugin/16289-cucumber- does very fine job for structuring tables in the feature files.
