### ISSUE TITLE
[QA] installation database details

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39871]
Seen with 10.9.1 (not a regression)

* install all packages (also php bindings for mysql and/or postgres) and set up apache.
* bowse to the not yet installed owncloud instance.
* the installation wizard shows the database options like this, when e.g. clicking PostgreSQL
![image](https://user-images.githubusercontent.com/1108546/157957009-174415b6-0853-4c5f-b555-62103a10e6ce.png)

----

Improvement suggestions:
* The hint text at the bottom should be written without whitespace: `localhost:5432`
* For PostgreSQL the hint should mention the special value `/var/run/postgresql` in 'Database host' -- that switches from TCP to local socket (and is probably preferred for both speed and security)

**Comment by phil-davis** [comment]
@jnweiger what exactly should be written for a PostgreSQL hint?
I am not familiar with PostgreSQL.

**Comment by ho4ho** [comment]
@jnweiger Could also disable staling closing by here?

https://github.com/owncloud/core/blob/master/.github/workflows/stale.yml#L25

**Comment by DeepDiver1975** [comment]
Adding all possible configuration options is a nightmare. Finally I also question how often this screen is used these days....

Anyway the space shall be removed

**Comment by DeepDiver1975** [comment]
> Anyway the space shall be removed

which has been taken care of -> no further action required -> close
