### ISSUE TITLE
[QA] browser session silently redirects into trashbin, when client deletes the folder

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#39928]
Seen with owncloud 10.9.1 and desktop client 2.10.1rc2

* Log in with a web browser at e.g. demo.owncloud.org, navigate into the Documents folder
* A file example.odt is there. Refresh the browser session with F5, nothing changes. OK.
![image](https://user-images.githubusercontent.com/1108546/160379458-26922345-268d-442b-b8c1-59b6b77a3eaa.png)
----
* Connect a desktop client to the same server, wait until initial sync completes.
* Delete the Documents folder in the local file system. The client reports that the delete propagates to the server. OK
* Refresh the browser session with F5, nothing much changes. The file example.odt is still "there". BAD.
![image](https://user-images.githubusercontent.com/1108546/160379883-23573c1f-5795-49f1-804c-b43bf700c4da.png)
----
* Looking closer, the user recognizes, that the browser session is no longer the normal 'All files' view. It now shows the Trashbin. BAD.

Expected behaviour: 
* The folder no longer exists. Click here to view the trashbin.

**Comment by jnweiger** [comment]
Same, when a second browser session does the delete.

**Comment by jnweiger** [comment]
not fixed, but closed :-(

**Comment by DeepDiver1975** [comment]
This works as intended. The file/folder is referenced by the file id.
No matter where the folder is moved to the browser will follow.

Was designed this way from the first day.
Works as intended.
