### ISSUE TITLE
Forbid Google Chrome to translate frontend

### ISSUE THREAD

**Issue by GeraldLeikam** [owncloud/core#39946]
If you use google chrome and the auto translation for websites is activated, all elements (including file and folder names) will be translated into the selected language.

Auto translation
![grafik](https://user-images.githubusercontent.com/54261654/161515610-1717a8d9-819c-4d0d-9f46-3b49fda812ad.png)

Orignal
![grafik](https://user-images.githubusercontent.com/54261654/161515493-d8b1546e-d9fa-4a02-abdf-7a36c8a342dc.png)

Auto translation
![grafik](https://user-images.githubusercontent.com/54261654/161529155-5a1c6e20-110f-48d4-a9d7-371bc94a6e20.png)

Orginal
![grafik](https://user-images.githubusercontent.com/54261654/161528920-a5e6dc15-b741-43dc-830d-bc67b4999fd3.png)

This can possibly be fixed with an additional line in the head

```
<meta name="google" content="notranslate"/>
```

**Comment by jnweiger** [comment]
notranslate should be added to the file listing and defintively also to the texteditor. 
In other places autotranslation may make sense.

**Comment by cortho** [comment]
Using github's search function within this repository resulted in
> We couldn’t find any code matching 'notranslate' in owncloud/core

and there is no PR for this ticket, so I'll better reopen this one

**Comment by mijarena** [comment]
I dug a little into it and my idea would be, that the initial filename will not be just the name of the file, but embedded into a span-tag like this:

`<span translate="no">MyFileName<span>`
Same goes with folder names.

This way directory names / file names would never be translated, but the user can use the browser function as he likes. And as it is the initially value, no templates and functions needed to be changed.

And by "never" I mean, that we can not control the behavior of the browser.

**Comment by jnweiger** [comment]
Good idea! Files and folder should be flagged with translate=no -- second part of this issue is the files_texteditor app. There I belive we should add a general translate=no for everything.

At some point, we can argue that chromium users need to learn what their "translate this to German" button actually means.
It can help greatly for languages that we do not offer. But when chromium translates into German, it is very likely that these translations differ from our translations.
Thus causing great confusion, when discussing contents or reporting errors.

**Comment by jnweiger** [comment]
Unsolicited translation attempts are also seen with Microsoft edge 114.0.1823.45

![image](https://github.com/owncloud/core/assets/1108546/5f719152-8f71-4f96-8733-45ccad0d9850)

**Comment by hodyroff** [comment]
We should do the proper settings so this is not translated.

**Comment by DeepDiver1975** [comment]
We offer translations into a lot of languages - I see no point in using browser translation capabilities.

**Comment by jnweiger** [comment]
This fix was not included in 10.13.3
With the latest upgrade of firefox, they now also advertise their unsolicited translations.

![image](https://github.com/owncloud/core/assets/1108546/6a747ce4-306c-40f7-b2e1-89a3f92d2d1c)
