### ISSUE TITLE
Ubuntu distribution key expired

### ISSUE THREAD

**Issue by bwlang** [owncloud/core#39943]
it seems that the GPG keys have expired...

following the instructions at:
https://software.opensuse.org//download.html?project=isv%3AownCloud%3Aserver%3A10&package=owncloud-complete-files
produces this error:
```
Err:7 http://download.opensuse.org/repositories/isv:/ownCloud:/server:/10/Ubuntu_20.04  InRelease
  The following signatures were invalid: EXPKEYSIG 4ABE1AC7557BEFF9 isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>
Reading package lists... Done
W: GPG error: http://download.opensuse.org/repositories/isv:/ownCloud:/server:/10/Ubuntu_20.04  InRelease: The following signatures were invalid: EXPKEYSIG 4ABE1AC7557BEFF9 isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/isv:/ownCloud:/server:/10/Ubuntu_20.04  InRelease' is not signed.
```

**Comment by jnweiger** [comment]
Indeed:
```
curl -L https://download.opensuse.org/repositories/isv:ownCloud:server:10/Ubuntu_20.04/Release.key | gpg -
...
pub   rsa2048 2016-09-25 [SC] [expired: 2022-04-02]
      1B07204CD71B690D409F57D24ABE1AC7557BEFF9
uid           isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>
```
Although:
```
osc signkey isv:ownCloud:server:10 | gpg -
...
pub   rsa2048 2016-09-25 [SC] [expires: 2024-03-23]
      1B07204CD71B690D409F57D24ABE1AC7557BEFF9
uid           isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>
```

**Comment by jnweiger** [comment]
Found that 
* isv:ownCloud:server:10/Ubuntu_20.04
* isv:ownCloud:server:10.9.1/Ubuntu_20.04
are affected, but nothing in the isv:ownCloud:server:10.9 repository. Ubuntu_21.10 is also always fine. 
This is odd. Seems Suse OBS is out of sync with the moon phase?
I am retriggering the build for these two.

**Comment by ian-abbott** [comment]
Debian_9.0 is also affected. Debian_11 is OK. I guess Debian_10 will be affected based on file timestamps but haven't checked it specifically.

**Comment by ian-abbott** [comment]
Using the Release.key in the Debian_10 directory for checking the packages in the Debian_9.0 directory seems to work!

**Comment by jnweiger** [comment]
Thanks @ian-abbott 
I've retriggered Debian_9.0 too.
Yes, 2024-03-23 is the expire date we want to see.

While a rebuild consistently fixes the situation, I am still puzzled how that happened in the first place.

**Comment by ian-abbott** [comment]
Looks like the following still have expired keys: CentOS_7, CentOS_8, Fedora_33, Fedora_34, RHEL_7, Ubuntu_20.10, Ubuntu_21.04.

**Comment by ian-abbott** [comment]
This is the current expiry state of the keys for all the server repos AFAICT:

|      |  10.8.0 |  10.8 | 10.9.0 | 10.9.1 | 10.9 | 10 |
| --- | --- | --- | --- | --- | --- | --- |
| **15.3** | Expired | N/A | Expired | OK | N/A | N/A |
| **15.4** | N/A | N/A | Expired | OK | OK | OK |
| **CentOS_7** | Expired | Expired | Expired | Expired | Expired | Expired |
| **CentOS_8** | Expired | Expired | Expired | Expired | Expired | Expired |
| **Debian_9.0** | Expired | Expired | Expired | OK | Expired | OK |
| **Debian_10** |  Expired | Expired | Expired | Expired | Expired | OK |
| **Debian_11** | OK | OK | OK | OK | OK | OK |
| **Fedora_32** | Expired | Expired | Expired | OK | Expired | OK |
| **Fedora_33** | Expired | Expired | Expired | Expired | Expired | Expired |
| **Fedora_34** | Expired | Expired | Expired | Expired | Expired | Expired |
| **Fedora_35** | N/A | N/A | Expired | OK | OK | OK |
| **openSUSE_Leap_15.2** | Expired | Expired | Expired | OK | OK | OK |
| **openSUSE_Leap_15.3** | Expired | Expired | Expired | OK | OK | OK |
| **RHEL_7** | Expired | Expired | Expired | Expired | Expired | Expired |
| **RHEL_8** | N/A | N/A | OK | OK | N/A | N/A |
| **Ubuntu_18.04** | Expired | Expired | Expired | OK | Expired | OK |
| **Ubuntu_20.04** | Expired | Expired | Expired | OK | OK | OK |
| **Ubuntu_20.10** | Expired | Expired | Expired | OK | Expired | Expired |
| **Ubuntu_21.04** | Expired | Expired | Expired | Expired | Expired | Expired |
| **Ubuntu_21.10** | N/A | N/A | OK | OK | OK | OK |

**Comment by markphopwood** [comment]
This still seems to be an issue. Is it something I can solve for myself or does the repo need some fixing?

**Comment by ttsak** [comment]
What I did and solved the problem (in Debian 9):



trust latest available key from the [download](https://software.opensuse.org//download.html?project=isv:ownCloud:server:10&package=owncloud-complete-files) page:

`curl -fsSL https://download.opensuse.org/repositories/isv:ownCloud:server:10/Debian_9.0/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/isv_ownCloud_server_10.gpg > /dev/null`

`apt-key list` and find the owncloud expired key

`cd /etc/apt/trusted.gpg.d` , `ls` to see the files and `rm` the expired key

then `apt-get update` worked without errors

**Comment by ian-abbott** [comment]
@markphopwood wrote:
> This still seems to be an issue. Is it something I can solve for myself or does the repo need some fixing?

The repo needs fixing, but you may be able to solve it for yourself manually by installing one of the keys from the from one of the working distro repos. The good keys are identical in all the repos, but have a different name and subfolder in the distro repo depending on whether it is RPM based or DEB based.

**Comment by markphopwood** [comment]
> What I did and solved the problem (in Debian 9):
> 
> trust latest available key from the [download](https://software.opensuse.org//download.html?project=isv:ownCloud:server:10&package=owncloud-complete-files) page:
> 
> `curl -fsSL https://download.opensuse.org/repositories/isv:ownCloud:server:10/Debian_9.0/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/isv_ownCloud_server_10.gpg > /dev/null`
> 
> `apt-key list` and find the owncloud expired key
> 
> `cd /etc/apt/trusted.gpg.d` , `ls` to see the files and `rm` the expired key
> 
> then `apt-get update` worked without errors

That worked great, thank you.

**Comment by jnweiger** [comment]
Probably related: https://central.owncloud.org/t/expired-gpg-key-on-ubuntu-20-04/37281

**Comment by jnweiger** [comment]
Thanks @ian-abbott for that expiry matrix.

My best guess is, that Suse OBS triggers rebuilds "when needed", thus leaving some repos untouched for long time, but updating others. The "when needed" part is puzzling. It seems a to be a random pattern. Dependencies are pretty much all the same on all server repos.

I am fixing the situation by manually triggering (quite massive) rebuilds. (Sorry the energy waste...)

**Comment by jnweiger** [comment]
openSUSE platforms are too clever. These all decide to skip the rebuild, as nothing changed:
10.8.0/15.3 10.9.0/15.3 10.9.0/15.4 10.8.0/openSUSE_Leap_15.2 10.8/openSUSE_Leap_15.2 10.9.0/openSUSE_Leap_15.2 10.8.0/openSUSE_Leap_15.3 10.8/openSUSE_Leap_15.3 10.9.0/openSUSE_Leap_15.3

For them we wipe the binaries first, then retrigger.

**Comment by jnweiger** [comment]
Fixed all.
