### ISSUE TITLE
Ubuntu 22.04 x64 development branch wayland

### ISSUE THREAD

**Issue by h4wkm00ner** [owncloud/core#39960]
fixed

**Comment by ho4ho** [comment]
@h4wkm00ner Close?

**Comment by h4wkm00ner** [comment]
there is problem on new 22.04 ubuntu owncloud client with wayland, i tryed nextcloud client and its ok
wayland Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.

**Comment by ho4ho** [comment]
Client issue tracker by https://github.com/owncloud/client/issues

**Comment by ho4ho** [comment]
Duplicate by https://github.com/owncloud/client/issues/8328
