### ISSUE TITLE
mk-ca-bundle.pl location is outdated

### ISSUE THREAD

**Issue by VicDeo** [owncloud/core#39977]
https://github.com/owncloud/core/blob/master/resources/config/readme.md?plain=1#L19

`https://github.com/curl/curl/blob/master/lib/mk-ca-bundle.pl`
 is
 `https://github.com/curl/curl/blob/master/scripts/mk-ca-bundle.pl` 
now

**Comment by Deaddy** [comment]
Also note that the `ca-bundle.crt` is outdated, as DST Root CA X3 must be removed as it is expired and leads to Errors when receiving federated shares from servers with letsencrypt certificates. (https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/)
