### ISSUE TITLE
Add test scenarios for meta endpoint PROPFIND with oc:meta-path-for-user

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#40012]
For reference see #40010 and https://github.com/cs3org/reva/pull/2741

https://doc.owncloud.com/server/next/developer_manual/webdav_api/meta.html#meta-files-xml documents that the `remote.php/dav/meta` endpoint should be accessed by doing a PROPFIND that includes a request body:
```
<?xml version="1.0"?>
<a:propfind xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns">
    <a:prop>
        <oc:meta-path-for-user/>
    </a:prop>
</a:propfind>
```

Currently the test scenarios send an empty body, and oC10 replies with the `oc:meta-path-for-user` data item anyway.

But implementations do not have to do that. An implementation can be coded to only return the `oc:meta-path-for-user` data if it was explicitly requested.

Keep some of the existing "no body" test cases, so that we still test that. But also add test scenarios that send the documented body, and verify that the correct `oc:meta-path-for-user` data is returned (or that suitable "4xx" status is returned for the edge cases where the file-id is invalid, belongs to another user, etc.)

**Comment by SwikritiT** [comment]
Closing this as the linked PR has been merged https://github.com/owncloud/core/pull/40042
