### ISSUE TITLE
Acceptance tests for Default for propfind depth infinity should be false as in the past

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#40035]
The default was changed in PR #40016 which has been merged to core master. The existing tests are all passing, and some of those explicitly check that infinite depth PROPFIND works when it is enabled.

Add some tests for:
- infinite depth PROPFIND is disabled, check doing various PROPFIND requests that ask for depth infinity and check the response (they should give some 4xx HTTP status)
- review the coverage of tests that have infinite depth PROPFIND enabled. Add a few tests so that there is reasonable coverage, to avoid accidental regression of the infinite depth PROPFIND behavior in future.

**Comment by SagarGi** [comment]
@phil-davis by default propfind depth infinity is set to `false` but still but the system config key is not set for `dav.propfind.depth_infinity` and it allows depth infinity untill `And the administrator has set depth_infinity_allowed to 0` this step is invoked. so is above step compulsory for scenarios to not to allow depth infinity or the default should have done the same?

**Comment by phil-davis** [comment]
@SagarGi if `dav.propfind.depth_infinity` is not mentioned at all in `config.php` then the system should have it disabled - PROPFIND with depth infinity should return 412 (or some 4xx HTTP status).

Please check on a local system, and then maybe we need to debug the test code to see why there is unexpected behavior.

**Comment by SagarGi** [comment]
Tests has been added for `dav.propfind.depth_infinity` disabled. Closing this issue.
