### ISSUE TITLE
no connection to owncloud, server replied "599 Broken" to GET https://keyaidconsulting.owncloud.online/status.php

### ISSUE THREAD

**Issue by nataschaminnitt** [owncloud/core#40139]
Noticed that my ownCloud desktop app was not syncing. Opened the app settings on Mac desktop version of ownCloud (version 2.10.1 (build 7187)). Received an error message: server replied "599 Broken" to GET https://keyaidconsulting.owncloud.online/status.php 
Clicked on link in error message, but ownCloud online won't open, page isn't working HTTP ERROR 599 on Chrome and Safari. Colleagues are not experiencing the same issue with the company ownCloud server.

**Comment by icomputeUK** [comment]
I have the same issue on Mac client desktop and cannot login in via web GUI either.

<img width="336" alt="image" src="https://user-images.githubusercontent.com/32702985/175567861-fc0ed320-abfa-4039-97e6-19af53232617.png">

**Comment by jvillafanez** [comment]
Without server logs there is nothing we can do. If the server is crashing so badly for a 599 error, the usual problem is a broken config.php file, but there could be other causes. There should be a crash log file somewhere in the server (`crash-<date>.log`, such as `crash-2002-11-23.log`).
