### ISSUE TITLE
Add API test scenarios for webDAV COPY

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#40145]
We have various API test scenarios for webDAV MOVE, but not many for webDAV COPY.

Add some test scenarios for:
- copy within a user's own storage
- copy into a received share
- copy from a received share
- copy between shares received from different users
- attempt to copy into a read-only received share
- copy in/out of local storage
- any other combination that seems "interesting"

Raise issues for any bugs found in oC10 (I don't expect to find any!)

It will be useful to have some reasonable coverage so that we also will know that these things work in oCIS/reva.

**Comment by SagarGi** [comment]
Most of the scenarios mentioned above are covered in suite `apiWebdavProperties1/copyFile.feature`. I will be adding scenarios which are missed above and also different combination to test the `COPY` request. @phil-davis

**Comment by SagarGi** [comment]
https://github.com/owncloud/core/pull/40173 With this PR, this issue can be closed.
