### ISSUE TITLE
Proper error message not displayed while trying to add a group with invalid name

### ISSUE THREAD

**Issue by kiranadh1452** [owncloud/core#40162]
### Steps to reproduce
1. Login to owncloud and navigate to 'users'
2. Type any invalid name (ending with a whitespace ) in the placeholder 'Group...'
3. Click on '+' button (Button to add a new group)

### Expected behaviour
The message saying `Error creating group: Invalid group name` should be popped up.

### Actual behaviour
The actual pop up says `Error creating group: {message}`
![image](https://user-images.githubusercontent.com/48694785/174982453-89977120-4d43-4ed4-b752-b49855f078a9.png)

The issue is not in the API because on making API call to add a group "newgroup ", it returns the correct error message.
> API Call
  ```bash
  curl -X POST http://admin:secret@example.com/ocs/v1.php/cloud/groups -d groupid="newgroup "
  ```

>Obtained Response
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>101</statuscode>
  <message>Invalid group name</message>
 </meta>
 <data/>
</ocs>
```

### Server configuration
**Operating system**: ubuntu 20.04

**Web server:** apache2

**Database:** MySQL

**PHP version:** 7.4.3

**ownCloud version:** 10.11.0 prealpha (git)

**Updated from an older ownCloud or fresh install:** fresh

**Where did you install ownCloud from:** github

**Comment by phil-davis** [comment]
Happens on my system also. I am surprised that I did not notice this when I did the back-end changes that preventing creating group names that begin or end with white-space. It seems that the front-end error message processing is not quite right.
