### ISSUE TITLE
Test federated sharing with Guzzle7

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#40177]
Related issue #39387 

We have some automated federated sharing tests that are all passing, so that is a good start.

We want to check that federated sharing between a new ownCloud core 10.11 system and another ownCloud core 10.10, 10.9 or 10.8 system works OK. Federated sharing needs to work across mixed versions of ownCloud 10 because people will want to upgrade installations one-at-a-time rather than having to do a "mass upgrade" of their whole set of federated ownCloud servers.

**Comment by phil-davis** [comment]
Before any 10.11 release tarballs exist, we can still locally do some manual testing.

- install a system running 10.10.0
- run a development 10.11 system using the latest master code in a repo cloned from github

- share files and folders between users/groups on the two systems, in both directions
- use various combinations of permissions (read, edit...)
- add public links from one server to the other
- check that the files/folders can be remotely accessed (upload, download, create sub-folders...)

**Comment by phil-davis** [comment]
@jnweiger FYI Kiran is doing some manual tests to check the above federated-sharing between different oC10 versions. That is all built-in to core, so does not need any app RC tarballs or... etc. And it is an area where there could be issues found when the new Guzzle7 client accesses and old oC10 server, or the old Guzzle5 client from an old oC10 server accesses a new oC10.11 server.

**Comment by kiranadh1452** [comment]
Issue: #40179

**Comment by kiranadh1452** [comment]
## Shared from v10.11 to v10.10
  ### User A: Uses v10.11 (owner)

  ### User B: Uses v10.10 (with whom the file/folder is shared)

  - File Sharing Test: Pass
  - File Permissions Test:
    - Sharing : Pass
    - Change (Edit) : Pass
  - Folder Sharing Test: Pass
  - Folder Permissions Test:
    - Sharing : Pass
    - Create: Pass
    - Change: Pass
    - Delete: Pass

## Shared from v10.10 to v10.11
  ### User A: Uses v10.10 (owner)
  
  ### User B: Uses v10.11 (with whom the file/folder is shared)

  - File Sharing Test: Pass
  - File Permissions Test:
    - Sharing : Pass
    - Change (Edit) : Pass
  - Folder Sharing Test: Pass
  - Folder Permissions Test:
    - Sharing : Pass
    - Create: Pass
    - Change: Pass
    - Delete: Pass

# Shared from v10.11 to v10.09
  ### User A: Uses v10.11.0 (owner)

  ### User B: Uses v10.9.0 (with whom the file/folder is shared)

  - File Sharing Test: Pass
  - File Permissions Test:
    - Sharing : Pass
    - Change (Edit) : Pass
  - Folder Sharing Test: Pass
  - Folder Permissions Test:
    - Sharing : Pass
    - Create: Pass
    - Change: Pass
    - Delete: Pass

## Shared from v10.09 to v10.11
  ### User A: Uses v10.09.0 (owner)

  ### User B: Uses v10.11(with whom the file/folder is shared)

  - File Sharing Test: Pass
  - File Permissions Test:
    - Sharing : Pass
    - Change (Edit) : Pass
  - Folder Sharing Test: Pass
  - Folder Permissions Test:
    - Sharing : Pass
    - Create: Pass
    - Change: Pass
    - Delete: Pass

# Shared from v10.11 to v10.8
  ### User A: Uses v10.11 (owner)

  ### User B: Uses v10.08 (with whom the file/folder is shared)

  - File Sharing Test: Pass
  - File Permissions Test:
    - Sharing : Pass
    - Change (Edit) : Pass
  - Folder Sharing Test: Pass
  - Folder Permissions Test:
    - Sharing : Pass
    - Create: Pass
    - Change: Pass
    - Delete: Pass

# Shared from v10.08 to v10.11
  ### User A: Uses v10.08 (owner)

  ### User B: Uses v10.11 (with whom the file/folder is shared)

  - File Sharing Test: Pass
  - File Permissions Test:
    - Sharing : Pass
    - Change (Edit) : Pass
  - Folder Sharing Test: Pass
  - Folder Permissions Test:
    - Sharing : Pass
    - Create: Pass
    - Change: Pass
    - Delete: Pass

**Comment by kiranadh1452** [comment]
### PS: This is an existing issue in older version as well. The same issue occurs between two servers running on v10.10 as well.

**Comment by phil-davis** [comment]
This was a manual testing/verification issue for the 10.11 ownCloud core release. It has been done.
