### ISSUE TITLE
Add webUI acceptance tests for sharing with multiple users at once

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#40178]
PR #40155 adds the ability to share with multiple users at the same time.

For example, Alice could paste `Brian,Carol` into the share-with text box, and the UI will suggest sharing with both of them.

The multiple-sharing is only with users. To share with groups, you can only do one at a time.

Group names can have a comma in them. So it is possible to have a group with the exact name `Brian,Carol`. When that happens, then the UI should suggest 2 options for sharing - share with the group `Brian,Carol` or share with each of the users `Brian` and `Carol`.

If a string in the comma-separated list is not a valid user then it should be omitted from the list of people to share with. Paste in `Brian,unknown,Carol` and the UI should suggest sharing with only `Brian` and `Carol`.

Add some automated webUI test scenarios to cover the basic behavior, so that we don't get accidental regressions in future.

**Comment by grgprarup** [comment]
Implemented in PR https://github.com/owncloud/core/pull/40546. So closing this.
