### ISSUE TITLE
make reports requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#40187]
Tried to run `make` respectively `make test-php-style-fix` I get following error:
Note the I used the recent master, all is rebased.

@phil-davis maybe you can help...

```
make
Building core

Note: You can type 'make help' for more targets

php /usr/local/bin/composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bamarni/composer-bin-plugin 1.6.0 -> satisfiable by bamarni/composer-bin-plugin[1.6.0].
    - bamarni/composer-bin-plugin 1.6.0 requires composer-plugin-api ^2.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
make: *** [Makefile:149: lib/composer/phpunit] Error 2
```

**Comment by mmattel** [comment]
Thanks for the info, I am currently running on my U20.04:
```
composer --version
Composer version 1.8.4
```
There is no info about this in README.md...

**Comment by phil-davis** [comment]
I guess that we should write something somewhere about this for developers. composer v2 is really needed nowadays in all the repos that have PHP (oC10 core, oC10 apps, repos that have PHP-based acceptance tests)

Where to write such things?

**Comment by mmattel** [comment]
> Where to write such things?

IMHO, this should be part of a building prerequisites section in readme.md

**Comment by mmattel** [comment]
I just installed composer v2 accoding this guide: https://www.how2shout.com/linux/how-to-install-composer-on-ubuntu-22-04-20-04-lts/ `make` works now.
