### ISSUE TITLE
TUS tests (most of them) cannot check the HTTP status code

### ISSUE THREAD

**Issue by individual-it** [owncloud/core#40215]
In most test-cases for TUS we are using a library and that does not report the HTTP status code, so the checks should be deleted from there

e.g. 
```
    And user "Alice" uploads file with content "01234" in 5 chunks to "/myChunkedFile.txt" using the TUS protocol on the WebDAV API        # TUSContext::userUploadsAFileWithContentInChunksUsingTus()
    Then the HTTP status code should be "200" 
```
above, the Then the HTTP status code should be "200" passes because it checks a completely different response code, not the one returned by the tus upload (which uses 201 for the initial POST and 204 for PATCH requests).

Note: There are some steps e.g. `@When user :user creates a new TUS resource on the WebDAV API with these headers:` that do low-level API calls with our own code and those DO report the HTTP status code, for those cases the checks should stay in place

**Comment by ScharfViktor** [comment]
user uploads file with content "01234" in 5 chunks -> it means that he sends 5 times PatchRequest. But we don't check that evert requests get us 204
