### ISSUE TITLE
Add API test scenario for removing a password from a public link

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#40227]
https://github.com/cs3org/reva/pull/3094 fixed this problem in reva, but there was no test that started passing.

The problem was noticed in issue https://github.com/owncloud/web/issues/7307

- check to see if we do have an API test scenario for this
- if not,, add one
- if we do, investigate why it did not start passing in reva/oCIS

**Comment by phil-davis** [comment]
Related issue: https://github.com/owncloud/web/issues/7307

After this is pulled into oCIS, then the web problem will likely be fixed.

**Comment by SagarGi** [comment]
I looked up there is no tests that updates(removes) the `password`. Looks like we need to add one.

**Comment by SagarGi** [comment]
API tests has been aded with this PR https://github.com/owncloud/core/pull/40230. So closing this issue.
