### ISSUE TITLE
owncloud/index.php/login 404 Not Found

### ISSUE THREAD

**Issue by kmg76** [owncloud/core#40258]
After adding the trusted domain name to the config.php file, refresh the browser and redirect to owncloud/index php/login，404 Not Found。owncloud.log has not changed。

nginx php config：
[
![image](https://user-images.githubusercontent.com/83706001/182188927-87e01899-4f4a-4137-a20e-36846d0ccb3b.png)
](url)

**Comment by cortho** [comment]
This is a bugtracker not a support forum. Visit https://central.owncloud.org/ instead
