### ISSUE TITLE
"Invalid token format" when attempting to use Google Drive

### ISSUE THREAD

**Issue by SeeJayEmm** [owncloud/core#40273]
### Steps to reproduce
1. Click the Red stop square next to the Google Drive external access.
2.
3.

### Expected behaviour
Icon turns green and the external mount works.

### Actual behaviour
External mount fails:
There was an error with message: InvalidArgumentException: Invalid token format. Do you want to review mount point config in personal settings page?

### Server configuration
**Operating system**: 
CentOS Linux release 7.9.2009 (Core)

**Web server:**  
httpd-2.4.6-97.el7.centos.5.x86_64

**Database:**
MariaDB-server-10.5.16-1.el7.centos.x86_64

**PHP version:**
php-7.3.33-3.el7.remi.x86_64

**ownCloud version:** (see ownCloud admin page)
10.10.0.3

**Updated from an older ownCloud or fresh install:**
Most recent update was from 10.8.x a couple days ago.

**Where did you install ownCloud from:**
Website

**Signing status (ownCloud 9.0 and above):**
Unsure how to answer

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and put the link here.
```
"No errors have been found."

**The content of config/config.php:**
https://gist.github.com/SeeJayEmm/4e80769ae200c1f75cdcd6b1a018ed7a

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to diligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**
Enabled:
  - activity:
    - Version: 2.7.0
    - Path: /var/www/html/apps-external/activity
  - comments:
    - Version: 0.3.0
    - Path: /var/www/html/apps/comments
  - configreport:
    - Version: 0.2.1
    - Path: /var/www/html/apps/configreport
  - contacts:
    - Version: 1.5.5
    - Path: /var/www/html/apps-external/contacts
  - dav:
    - Version: 0.7.0
    - Path: /var/www/html/apps/dav
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /var/www/html/apps/federatedfilesharing
  - files:
    - Version: 1.5.2
    - Path: /var/www/html/apps/files
  - files_external:
    - Version: 0.9.0
    - Path: /var/www/html/apps/files_external
  - files_external_dropbox:
    - Version: 1.2.0
    - Path: /var/www/html/apps-external/files_external_dropbox
  - files_external_ftp:
    - Version: 0.2.1
    - Path: /var/www/html/apps-external/files_external_ftp
  - files_external_s3:
    - Version: 1.0.0
    - Path: /var/www/html/apps-external/files_external_s3
  - files_mediaviewer:
    - Version: 1.0.5
    - Path: /var/www/html/apps/files_mediaviewer
  - files_pdfviewer:
    - Version: 1.0.1
    - Path: /var/www/html/apps-external/files_pdfviewer
  - files_sharing:
    - Version: 0.14.0
    - Path: /var/www/html/apps/files_sharing
  - files_texteditor:
    - Version: 2.4.1
    - Path: /var/www/html/apps-external/files_texteditor
  - files_trashbin:
    - Version: 0.9.1
    - Path: /var/www/html/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /var/www/html/apps/files_versions
  - firstrunwizard:
    - Version: 1.2.0
    - Path: /var/www/html/apps/firstrunwizard
  - market:
    - Version: 0.6.3
    - Path: /var/www/html/apps/market
  - notifications:
    - Version: 0.5.4
    - Path: /var/www/html/apps/notifications
  - provisioning_api:
    - Version: 0.5.0
    - Path: /var/www/html/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /var/www/html/apps/systemtags
  - templateeditor:
    - Version: 0.4.0
    - Path: /var/www/html/apps-external/templateeditor
  - twofactor_totp:
    - Version: 0.7.4
    - Path: /var/www/html/apps-external/twofactor_totp
  - updatenotification:
    - Version: 0.2.1
    - Path: /var/www/html/apps/updatenotification
Disabled:
  - encryption:
    - Path: /var/www/html/apps/encryption
  - external:
    - Path: /var/www/html/apps/external
  - federation:
    - Path: /var/www/html/apps/federation
  - user_external:
    - Path: /var/www/html/apps/user_external

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, Local & Google Drive

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 103.0.1

**Operating system:**
Windows 10

#### Web server error log
```
Insert your webserver log here
```
[Fri Aug 05 15:15:49.073433 2022] [suexec:notice] [pid 1331] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Aug 05 15:15:49.144682 2022] [lbmethod_heartbeat:notice] [pid 1331] AH02282: No slotmem from mod_heartmonitor
[Fri Aug 05 15:15:49.317231 2022] [mpm_prefork:notice] [pid 1331] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/7.3.33 co
nfigured -- resuming normal operations
[Fri Aug 05 15:15:49.317255 2022] [core:notice] [pid 1331] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Fri Aug 05 15:15:56.097868 2022] [authz_core:error] [pid 1605] [client ::1:36130] AH01630: client denied by server configuration: /dev/null
[Fri Aug 05 15:15:59.091959 2022] [authz_core:error] [pid 1419] [client ::1:36380] AH01630: client denied by server configuration: /dev/null
[Fri Aug 05 15:15:59.093611 2022] [authz_core:error] [pid 1420] [client ::1:36386] AH01630: client denied by server configuration: /dev/null
[Fri Aug 05 15:21:21.791861 2022] [mpm_prefork:notice] [pid 1331] AH00170: caught SIGWINCH, shutting down gracefully
[Fri Aug 05 15:22:44.111393 2022] [suexec:notice] [pid 1323] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Aug 05 15:22:44.127178 2022] [lbmethod_heartbeat:notice] [pid 1323] AH02282: No slotmem from mod_heartmonitor
[Fri Aug 05 15:22:44.205214 2022] [mpm_prefork:notice] [pid 1323] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/7.3.33 co
nfigured -- resuming normal operations
[Fri Aug 05 15:22:44.205239 2022] [core:notice] [pid 1323] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Fri Aug 05 15:22:46.218396 2022] [authz_core:error] [pid 2002] [client ::1:38092] AH01630: client denied by server configuration: /dev/null
[Fri Aug 05 15:23:09.141589 2022] [authz_core:error] [pid 1533] [client ::1:39976] AH01630: client denied by server configuration: /dev/null
[Fri Aug 05 15:23:09.148403 2022] [authz_core:error] [pid 2009] [client ::1:39988] AH01630: client denied by server configuration: /dev/null
[Fri Aug 05 16:19:56.532558 2022] [mpm_prefork:notice] [pid 1323] AH00170: caught SIGWINCH, shutting down gracefully
[Fri Aug 05 16:19:57.741253 2022] [suexec:notice] [pid 12259] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Aug 05 16:19:57.764891 2022] [lbmethod_heartbeat:notice] [pid 12259] AH02282: No slotmem from mod_heartmonitor
[Fri Aug 05 16:19:57.817042 2022] [mpm_prefork:notice] [pid 12259] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/7.3.33 c
onfigured -- resuming normal operations
[Fri Aug 05 16:19:57.817066 2022] [core:notice] [pid 12259] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
https://gist.github.com/SeeJayEmm/ef95c92ec21965a62e10c90f8a755998

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by kochs-online** [comment]
I'm seeing this as well running ownCloud version 10.11.0.6. Any update or workaround?

**Comment by ho4ho** [comment]
Following docs step by step?

https://doc.owncloud.com/server/10.11/admin_manual/configuration/files/external_storage/google.html

**Comment by DeepDiver1975** [comment]
How does your token look like? It is expected to be a json string. Was the token potentially created and setup in owncloud long ago?

**Comment by DeepDiver1975** [comment]
ah - https://github.com/owncloud/core/commit/e94a503ba292401d8ed8e5e70641ab8b25fbed35

the token information was changed back then - please try to setup the token again. THX
