### ISSUE TITLE
Refactor acceptance tests for public link (and other) shares

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#40285]
In API acceptance tests we create shares with API requests. The API response has lots of information about the new public link share. We currently remember that in `tests/acceptance/features/bootstrap/Sharing.php` `$lastShareDataByUser` `$lastShareIdByUser` `$userWhoCreatedLastShare` `$userWhoCreatedLastPublicShare` `$lastPublicShareData` `$lastPublicShareId` etc. That information is used by `Then` steps when they want to check if the "last created share" actually exists, if users can download/upload from/to the share etc. There is enough information remembered that the test code can easily find the expected share(s) and use it.

In webUI tests, the shares are created from the UI, by opening the sharing details panel and entering/clicking to create user, group or public link shares. The test code does not have direct access to the API  request-response that the webUI  does when it creates the share. So the test code saves what information it can find out - for example in `$createdPublicLinks`

After the webUI has created a public link share, later `Then` steps need to find the information about the share (token, name, path...) in `$createdPublicLinks` and use that to construct API requests that test the public link share. But if the `Then` step is in an API test scenario then it needs to look in `$lastShareDataByUser` to find the share token etc. Some `Then` steps have code that checks in both places - so that the same `Then` step will work in both web and API test scenarios.

For example, see what was done in #40264 and improve all-the-things.

It should be better if we have a single place where we save the data items about shares that have been created during any test scenario, and that place should save all the data items of interest (getting them from the API  response or webUI action that created the share). And `Then` steps can just reference this single place/interface to find the known share data.

Design and implement improved code!

**Comment by saw-jan** [comment]
Done for oCIS: https://github.com/owncloud/ocis/pull/6775 (API tests)

**Comment by SwikritiT** [comment]
Need to do same in core as well co re-opening
