### ISSUE TITLE
Demo theme

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#4031]
Create a very simple demo theme showing what can be changed. Use just CSS, images and the defaults.php – NO TEMPLATE CHANGES.

Anyone interested, @owncloud/designers?

cc @karlitschek @schiesbn @DeepDiver1975

**Comment by jon-tlmi** [comment]
ack. Sleep deprivation. I'd copied over the css file from /core and not deleted the relevant parts. This works fine.. 
What's the markdown for a facepalm?

**Comment by MorrisJobke** [comment]
:dizzy_face: :palm_tree: ? :smiley:

**Comment by jon-tlmi** [comment]
OK, there's a super simple theme here: 
https://github.com/jon-tlmi/themes
Changes the logo, a gradient value and generally shows how a whiteboxing ownCloud should work by replaces things like defaultEntity, defaultTitle and all that stuff.
As requested higher up, there are NO templates changed. Comments are not overly detailed, but I feel if you're digging this deep, you should be a decent enough web dev/designer to understand what you're doing, you just need an example to start you off...
I'm not very experienced with github so I didn't want to kick off any pull requests without someone else casting an eye over it. Code is provided free of copyright and free of support as my job is taking me away from this ;-) It works on my ownCloud install

**Comment by jon-tlmi** [comment]
OK, the theme I posted earlier has been worked on a bit more - I'm prepared to support it with some more work if someone wants to look it over. Should I create a pull request to replace the current (and very limited) demo theme in owncloud / themes ?

**Comment by jancborchardt** [comment]
Pull request at https://github.com/owncloud/core/pull/16519
