### ISSUE TITLE
You took too long to login, please try again now

### ISSUE THREAD

**Issue by tbird20d** [owncloud/core#40321]
### Steps to reproduce
1. go to http://<myowncloudserver.org>/index.php/login
2. Enter name and password (correctly)
3. See error message "You took too long to login, please try again now"

Note that I can access the login page via both http and https.

In my apache config, I have both of these:
VirtualHost *:80 with DocumentRoot /var/www/owncloud
VirtualHost *:443 with DocumentRoot /var/www/owncloud

Not everything under this DocumentRoot is owncloud material.  There are some items that it is OK to
have be accessible on port 80 (without http security).

### Expected behaviour
It should say that access to the server is only allowed over https, and provide a link to do so.
Or, it should redirect to https://<myowncloudserver.org>/index.php/login automatically.

### Actual behaviour
It gives an unhelpful message saying to just try again.  However, trying again will *never* work,
using the http.

This appears to be related to this issue:
https://github.com/owncloud/core/issues/32067

This security "feature" seems to have introduced the behavior:
https://github.com/owncloud/core/issues/29462

### Server configuration
**Operating system**:  Linux (Ubuntu 18.04.03 LTS)

**Web server:** Apache2

**Database:** mysql 5.7.39

**PHP version:** 7.2.24

**ownCloud version:** (see ownCloud admin page) 10.1.0.4

**Updated from an older ownCloud or fresh install:** from older version

**Where did you install ownCloud from:** don't recall

**Signing status (ownCloud 9.0 and above):** ??

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
exact text (not on gist.github.com): No errors have been found.

**The content of config/config.php:**

'''
<?php
$CONFIG = array (
  'updatechecker' => false,
  'instanceid' => 'ocglavh9o72z',
  'passwordsalt' => 'xxxx',
  'secret' => 'xxxx',
  'trusted_domains' => 
  array (
    0 => 'xxxxxxxx',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://xxxxxx',
  'dbtype' => 'mysql',
  'version' => '10.1.0.4',
  'dbname' => 'xxxxxxx',
  'dbhost' => 'xxxxxxxx',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'xxxx',
  'dbpassword' => 'xxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
);
```
```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Chrome version 103.0.5060.134 (64-bit)

**Operating system:** Linux - Ubuntu 20.04

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```
Note: I tried the login on http://<myowncloudserver>/index.php/login, and nothing appears
in the owncloud log as a result of the login attempt.

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by DeepDiver1975** [comment]
Setup your instance properly and only let it run on https. You should never use plain http. Passwords will be visible on the network.
Redirect to https is to be done on apache config.

**Comment by rundekugel** [comment]
Some people reported this issue because of less space on harddrive.
