### ISSUE TITLE
Transifex Japanese is adding and then removing translations

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#40332]
See the recent Transifex nightly commits:

https://github.com/owncloud/core/commit/7ca2b843181e81bea24334dccbe7f354f0b0f96f
https://github.com/owncloud/core/commit/8ddc4fe1a09261fd2ea0f3a79afec8afa34a2d93
https://github.com/owncloud/core/commit/eb33b570eedc4b32cb13bb3f12ccc6c092e9b7c2
https://github.com/owncloud/core/commit/5b5af0cc4056b3703363daddd24519807e1140f2
https://github.com/owncloud/core/commit/2a1561b645496f44af51e134ffedcbe9c89641d0
https://github.com/owncloud/core/commit/848d32885997b38cc64ad9bf1856f2dc2178445c
https://github.com/owncloud/core/commit/e312e51c2e38b505927f8d619bfa652836c99555

Lots of Japanese translations get removed, and then added back in the next commit a day later.

What is happening to cause this? It needs investigation.

**Comment by phil-davis** [comment]
This has stopped happening this week. I don't know what was the cause or the fix.
Closing - if it happens again then I will try to find someone who knows what to look for.

**Comment by phil-davis** [comment]
It is happening again. Transifex deleted a lot of `ja` translations last night: https://github.com/owncloud/core/commit/31529dcebe93e1d856d7034a8c0bbbde3b782390

Who knows about Transifex and has privs in Transifex to sort out what is going on? @micbar or?

**Comment by phil-davis** [comment]
Lots of `ja` translations were deleted last night by Transifex ommit https://github.com/owncloud/core/commit/fd7ddf1f3bcf138c497a459b259659e9f0e8b17c

**Comment by phil-davis** [comment]
And they were added back again in commit https://github.com/owncloud/core/commit/e15ea6dfe4a2924445d6b873601bf0fa7ef691b2

It seems that there are 2 sources of translations that are fighting each other?

@micbar or anyone - who can look into this?

**Comment by phil-davis** [comment]
Not seeing this happening recently - closing

**Comment by phil-davis** [comment]
Happened again last night: https://github.com/owncloud/core/commit/79b947803cba8996274c2792367870c2d39beb39

A lot of Japanese translations were removed in the automatic Transifex commit.

Who knows what is set up in Transifex for Japanese?

**Comment by DeepDiver1975** [comment]
Will have a look

**Comment by DeepDiver1975** [comment]
We have `ja` and `ja_JP` on transifex.
The tranisfex config is mapping ja_JP to ja - https://github.com/owncloud/core/blob/79b947803cba8996274c2792367870c2d39beb39/l10n/.tx/config#L3

So depending on the pull order in ci - we either see ja or ja_JP in our code base

![image](https://github.com/owncloud/core/assets/1005065/3c29fbc8-b631-4575-9474-020958e2a6c3)

**Comment by DeepDiver1975** [comment]
`ja` had almost no translations - I killed it. Should be good now ......

**Comment by phil-davis** [comment]
I will report back on the weekend results. It should apply the full translations again tonight, and leave them there.

**Comment by phil-davis** [comment]
https://github.com/owncloud/core/commit/fac5dc20cb2e96686e6d7a185e3499f4fd744ba2

Japanese translations came back - good.
