### ISSUE TITLE
[QA] repeated users are only partially filtered when sharing with multiple users

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#40344]
Seen while testing #40155 with core 10.11.0-rc.1

In a system, where admin, user1, and user2 exist:
User admin tries to share with "user1, user2, user1, user2"
The duplicate user2 is recognized:

![image](https://user-images.githubusercontent.com/1108546/188812674-97f9980f-0a10-4db5-887d-d8c17b27ae9f.png)

Expected behaviour:
* The duplicate user1 is also recognized
* the popup never contains duplicates.

The issue is only about the preview in the popup. No errors occur (the duplicate is silently ignored) when submitting the list.

**Comment by phil-davis** [comment]
That is fixable - PR incoming...

**Comment by phil-davis** [comment]
@jnweiger fixed  by #40347 - please try it and close here if it works. Whenever the next 10.11.0 tarbalss are generated, this will get included.

**Comment by grgprarup** [comment]
This issue has been fixed and the current behavior is 
![repeatedname](https://user-images.githubusercontent.com/8559121/208626389-0d0a170e-fd20-4b5c-aa8b-93f5f0ed8b9e.png)
