### ISSUE TITLE
Implement clearing occ status code function

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/core#40351]
Currently, the occ code never gets clear after it has been set. If by any chance the server response is slow then the previous occ code set in variable let checking occ code function pass but failed on the later step.

Add resetOccLastCode function in needed places so that the previous value cleared before the new occ request 
Take reference to this PR
https://github.com/owncloud/core/pull/40350

List of suites
 - [ ] apiAuth 
 - [ ] apiAuthOcs 
 - [ ] apiAuthWebDav  (@kiranadh1452 )
 - [ ] apiCapabilities 
 - [ ] apiComments 
 - [ ] apiFavorites 
 - [ ] apiFederationToRoot1 ()
 - [ ] apiFederationToRoot2 ()
 - [ ] apiFederationToShares1 ()
 - [ ] apiFederationToShares2 ()
 - [ ] apiMain 
 - [ ] apiProvisioning-v1 
 - [ ] apiProvisioning-v2 
 - [ ] apiProvisioningGroups-v1 
 - [ ] apiProvisioningGroups-v2 
 - [ ] apiShareCreateSpecialToRoot1 ()
 - [ ] apiShareCreateSpecialToRoot2 ()
 - [ ] apiShareCreateSpecialToShares1 ()
 - [ ] apiShareCreateSpecialToShares2 ()
 - [ ] apiSharees
 - [ ] apiShareManagementBasicToRoot ()
 - [ ] apiShareManagementBasicToShares ()
 - [ ] apiShareManagementToRoot ()
 - [ ] apiShareManagementToShares ()
 - [ ] apiShareOperationsToRoot1 ()
 - [ ] apiShareOperationsToRoot2 ()
 - [ ] apiShareOperationsToShares1 ()
 - [ ] apiShareOperationsToShares2 ()
 - [ ] apiSharePublicLink1 
 - [ ] apiSharePublicLink2 
 - [ ] apiShareReshareToRoot1 ()
 - [ ] apiShareReshareToRoot2 ()
 - [ ] apiShareReshareToRoot3 ()
 - [ ] apiShareReshareToShares1 ()
 - [ ] apiShareReshareToShares2 ()
 - [ ] apiShareReshareToShares3 ()
 - [ ] apiShareUpdateToRoot ()
 - [ ] apiShareUpdateToShares ()
 - [ ] apiSharingNotificationsToRoot ()
 - [ ] apiSharingNotificationsToShares ()
 - [ ] apiTags ()
 - [ ] apiTranslation ()
 - [ ] apiTrashbin ()
 - [ ] apiTrashbinRestore ()
 - [ ] apiVersions ()
 - [ ] apiWebdavEtagPropagation1 ()
 - [ ] apiWebdavEtagPropagation2 ()
 - [ ] apiWebdavLocks
 - [ ] apiWebdavLocks2 
 - [ ] apiWebdavLocks3
 - [ ] apiWebdavLocksUnlock 
 - [ ] apiWebdavMove1 
 - [ ] apiWebdavMove2 
 - [ ] apiWebdavOperations 
 - [ ] apiWebdavPreviews
 - [ ] apiWebdavProperties1 
 - [ ] apiWebdavProperties2 
 - [ ] apiWebdavUpload1 
 - [ ] apiWebdavUpload2 
 - [ ] apiWebdavUploadTUS
 look in cli suites too

**Comment by saw-jan** [comment]
@kiranadh1452 Please, check if everything is done and close the issue accordingly.

**Comment by kiranadh1452** [comment]
#40359 was successfully merged and all issues after the changes have also been closed.
