### ISSUE TITLE
Support other test mail services in testsuite

### ISSUE THREAD

**Issue by xoxys** [owncloud/core#40366]
Today, the test suite is hard-coded to mailhog as test mail service due to the API usage. As mailhog is poorly maintained and for a while was completely unmaintained, some CI pipelines/demo deployments have switched to other solutions like [inbucket](https://github.com/inbucket/inbucket).

Would it be possible to use pop3 to communicate with the mail service instead of an API? This way it would be more generic and easier to replace the used test mail service. As we currently only support unauthenticated requests to the mailhog API, I would keep it simple for now and only support unauthenticated pop3 as well.

**Comment by phil-davis** [comment]
QA people - please first investigate a bit to see if this will be "moderately easy", and then we can discuss what is the way forward for implementing.

**Comment by kiranparajuli589** [comment]
The working of _inbucket_ is quite similar to the mailhog. We can start the service using [docker](https://inbucket.org/packages/docker.html) and then fetch the sent mails using the [REST API](https://github.com/inbucket/inbucket/wiki/REST-API).

IMO, the integration will be easy. The point that the mailhog is no more maintained, this can be a good option.

cc @phil-davis

**Comment by SagarGi** [comment]
https://github.com/owncloud/core/pull/40442 with this PR merged this issue can be closed but we have another issue to make it work for other OC apps here https://github.com/owncloud/QA/issues/771
