### ISSUE TITLE
Wrong Content Security Header for marketplace

### ISSUE THREAD

**Issue by sbourdette** [owncloud/core#40370]
### Steps to reproduce
1. Log as admin
2. Go to the marketplace
3. open browser console

### Expected behaviour

No error in the console

### Actual behaviour

When browsing the marketplace, no images are shown.

Content Security Policy alert in the browser console : 

`Refused to load the image 'https://marketplace-storage.owncloud.com/screenshots/5c0fd0343e177' because it violates the following Content Security Policy directive: "img-src 'self' data: blob: https://storage.marketplace.owncloud.com https://marketplace-storage.int.owncloud.com http://minio:9000".`

It seems that the url of the marketplace is wrong in the content security header

### Server configuration
**Operating system**:
Ubuntu 22.04

**Web server:**
nginx version: nginx/1.18.0 (Ubuntu)

**Database:**
Version du serveur : 8.0.30-0ubuntu0.20.04.2 - (Ubuntu)

**PHP version:**
7.4

**ownCloud version:** (see ownCloud admin page)

[ownCloud ](https://owncloud.com/)10.9.0 (production)

**Updated from an older ownCloud or fresh install:**
updated from older ownCloud

**Where did you install ownCloud from:**

using ansible role

**Comment by sbourdette** [comment]
updating markep app to 0.6.3 solve the issue

**Comment by ho4ho** [comment]
Looked like expect and fix by https://github.com/owncloud/market/pull/913

Suggest: Close

**Comment by hodyroff** [comment]
Thanks!
