### ISSUE TITLE
folders missing after rsync via davfs

### ISSUE THREAD

**Issue by drdisk** [owncloud/core#40375]
### Steps to reproduce

I have to keep an very big directory structure from a fileserver in sync with the owncloud server (> 1 TB). To do this I mount every 4 hours the data dir from an owncloud user to my linux server via davfs. After that I start a rsync to sync the data. Just the usual things: creating new files and folders, deleting those that no longer exist. In terms of the process, there are no changes to the data on the owncloud side. This one direction of sync is completely sufficient for me. Also, the changes are not that big now, they always fit easily into the 4 hour time window. When rsync has finished the folder will be unmounted. There is a special user for this sync who shares his data with the actual users. Only one session is open at a time for the sync user itself.

### Expected behaviour

All new files and folders should be visible for a user via WebUI when the syncing process has completely finished.

### Actual behaviour

Sometimes a few new synced folders are missing (currently about twice a week - to be more precise, the customer notices twice a week that something is missing). But they exist in local data directory and after an occ files:scan all folders are visible in the WebUI as expected.

### Server configuration

Operating system: Ubuntu 20.04

Web server: apache

Database: maria

PHP version: 7.4

ownCloud version: 10.10.0.3

Updated from an older ownCloud or fresh install: updated (fresh install about 3 month ago)

Where did you install ownCloud from: tar

**Comment by ho4ho** [comment]
By https://doc.owncloud.com/server/10.10/admin_manual/troubleshooting/general_troubleshooting.html#debugging-sync-issues:

> The data directory on the server is exclusive to ownCloud and must not be modified manually.

**Comment by drdisk** [comment]
I know. That's why I'm using the way described here: 
[https://doc.owncloud.com/webui/next/classic_ui/files/access_webdav.html#creating-webdav-mounts-on-the-linux-command-line](https://doc.owncloud.com/webui/next/classic_ui/files/access_webdav.html#creating-webdav-mounts-on-the-linux-command-line)
I have an owncloud server as described above. On an other linux system I mount via davfs one user account, run rsync against that mounted folder, umount it. Works great. Apart from the folders which are occasionally missing.

Thanks for your reply,
Steffen

**Comment by DeepDiver1975** [comment]
Pretty hard to analyse the situation from a far. Any explicit error log messages?

please reopen if still an issue
