### ISSUE TITLE
Improvement: Save storage in google APIs

### ISSUE THREAD

**Issue by d7oc** [owncloud/core#40384]
Right now the google APIs consume 78 MB in `apps/files_external/3rdparty/google/apiclient-services/`. On https://github.com/googleapis/google-api-php-client#cleaning-up-unused-services google described how the total set of 200 services can be stripped down to those which are actually needed. I think oC10 could benefit here if the services are limited as e.g. YouTube API should not be required.

**Comment by NannaBarz** [comment]
@pmaier1 FR or will you approve it?

**Comment by pmaier1** [comment]
Approved from my side.

**Comment by phil-davis** [comment]
Note: follow-on issue #40445 - I am now getting some trouble when trying to update dependencies in apps/files_external/3rdparty

**Comment by jnweiger** [comment]
Confirmed in 10.12.0-rc.2
