### ISSUE TITLE
MySQL error when updating to 10.11.0 (1067 Invalid default value for 'startdate')

### ISSUE THREAD

**Issue by vstokesjr** [owncloud/core#40381]
### Steps to reproduce
1. Performed apt dist-upgrade
2. owncloud-complete-files package downloaded and applied successfully
3. Used browser to load owncloud site
4. Upgrade started
5. Upgrade failed with SQL error

### Expected behaviour
Upgrade should have successfully completed.

### Actual behaviour
Received the following error:

```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_calendar_repeat` CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;': SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'startdate'
```

### Server configuration
**Operating system**
Ubuntu 22.04.1 LTS (Jammy Jellyfish)

**Web server:**
Apache/2.4.52 (Ubuntu)

**Database:**
MySQL version 8.0.30-0ubuntu0.22.04.1

**PHP version:**
7.4.30

**Updated from an older ownCloud or fresh install:**
Updated from a 10 version

**Where did you install ownCloud from:**
apt source:
deb http://download.opensuse.org/repositories/isv:/ownCloud:/server:/10/Ubuntu_21.10/ /

### Client configuration
**Browser:** 
Brave

**Operating system:**
Ubuntu 22.04.0 LTS

![Screenshot from 2022-09-20 15-29-14](https://user-images.githubusercontent.com/3577587/191359591-83242e8d-1557-4900-83fc-9a734eb74bd0.png)

**Comment by vstokesjr** [comment]
The `startdate` and `enddate` columns in the database table `oc_calendar_repeat` had their "default" value set to `0000-00-00 00:00:00`. That is not a valid `datetime` value for MySQL 8 (or MySQL 5.7 with STRICT MODE enabled). I had to execute this DDL statement manually prior to re-running the upgrade:

```
ALTER TABLE oc_calendar_repeat
MODIFY COLUMN startdate datetime NULL,
MODIFY COLUMN enddate datetime NULL;
```

**Comment by DeepDiver1975** [comment]
This table is not used by owncloud. This table is from an very old calendar app installation about ~10 years ago - https://github.com/nextcloud/apps/blob/52c85c704d28491205ddae5885d9146ea30ffcbd/calendar/appinfo/database.xml#L295

You can savely drop this table and move ahead.
