### ISSUE TITLE
Documentation links lead to nirvana

### ISSUE THREAD

**Issue by cortho** [owncloud/core#40405]
All the documentation links used at https://github.com/owncloud/core/search?q=admin-dir_permissions do not link to the expected page.

https://doc.owncloud.com/server/10.11/go.php?to=admin-dir_permissions

There might be more go.php dead links, I didn't search/test all of them. Are there any tests checking if the links are working?

**Comment by cortho** [comment]
The above link again is failing. Now it points to "The Installation Wizard"

**Comment by xoxys** [comment]
Link fixed. Thanks for the report, and sorry for the delay. I'm going to close the issue, but please add any further comment if something is missing.
