### ISSUE TITLE
Error page: add link to login page

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#40403]
> Enhancement idea:
> 
>     * add a link to the login form to this error page, if needed with a special parameter to invalidate the session.
>       (similar to the logout-redirect-url that is used, when a user properly logs out from the idp)

core issue.

for anything else: well - this is the pain of integration :shrug:

_Originally posted by @DeepDiver1975 in https://github.com/owncloud/openidconnect/issues/213#issuecomment-1266447203_

**Comment by jnweiger** [comment]
E.g. when user clicks 'cancel' at the IDP, he is returned to  https://oc1091-oidc220rc5-20220928.jw-qa.owncloud.works/index.php/apps/openidconnect/redirect?error=access_denied&error_description=consent%20denied&state=4817cbafc47ed2fa0039f

and sees 
![image](https://user-images.githubusercontent.com/1108546/193787852-7cf0711e-8116-4ce7-b430-4feb0732a6bc.png)

**Comment by jnweiger** [comment]
Test case | Actions | Expected behaviour  |   | ...
-- | -- | -- | -- | --
Logout | 1. Complete login process in a OIDC server2. Logout in the idP | Session logged out. Needed credentials again to enter the account |   | Stranded at kopano-url, oc-url would be better

**Comment by jnweiger** [comment]
With keycloak, there is no option to cancel. So this issue does not directly apply there.
But when logging out from owncloud, the user is stranded at
![grafik](https://user-images.githubusercontent.com/1108546/211623514-d5149d98-82b0-4c99-91c8-3a014d4e2bae.png)
