### ISSUE TITLE
[External storage - Dropbox] Allowed memory size  exhausted

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#4040]
I don´t know why I get this messages but external storage is working really bad for me. Should I allow a certain OAuth adress in the app i created in Dropbox, or what seems to be the error?

```
Fatal	 PHP	 Allowed memory size of 536870912 bytes exhausted (tried to allocate 408230542 bytes) at /var/www/owncloud/3rdparty/Dropbox/OAuth/Curl.php#102	 12.07.2013 13:29:22
Fatal	 PHP	 Allowed memory size of 536870912 bytes exhausted (tried to allocate 408230542 bytes) at /var/www/owncloud/3rdparty/Dropbox/OAuth/Curl.php#102	 10.07.2013 10:45:28
Fatal	 PHP	 Call to a member function t() on a non-object at /var/www/owncloud/apps/files_mv/ajax/autocompletedir.php#48	 09.07.2013 23:24:33
Fatal	PHP	Call to a member function t() on a non-object at /var/www/owncloud/apps/files_mv/ajax/autocompletedir.php#48	09.07.2013 23:24
Fatal	PHP	Call to a member function t() on a non-object at /var/www/owncloud/apps/files_mv/ajax/autocompletedir.php#48	09.07.2013 23:24
```

I can also add that I have 22 GB on my Dropbox as we speak, and I´m not able to download the content from either WebDAV or OC web interferance. In OC web interferance I get "server error message". In WebDAV it loads in like 10 kB/s, thou I have a 100 MBit/s internet.

OS: Windows 7 Ultimate
Server: Ubuntu Server 12.04 LTS
OC: 5.0.8
WebDAV client: Netdrive

**Comment by arkascha** [comment]
Looks like this is still not fixed in OC-7.0.4?

**Comment by MorrisJobke** [comment]
https://github.com/owncloud/core/issues/13874#issuecomment-72836055

**Comment by PVince81** [comment]
@enoch85 I discovered that the old Dropbox library used by ownCloud doesn't stream files. When downloading, it puts the whole file in memory. This will break with bigger files.

We should switch to a better library, maybe the official Dropbox lib or use Flysystem's Dropbox plugin.

Let's keep this ticket to track the library update.

**Comment by enoch85** [comment]
@PVince81 I´m really glad you found the reason here. Finally we can fix it. Thanks!

**Comment by PVince81** [comment]
We're past feature freeze, will not update the dropbox lib at this point => 9.0.
Ideally we need a new better lib, maybe the official one from Dropbox, which might need rewriting the storage backend class.

**Comment by PVince81** [comment]
Something to look at: whether Flysystem's Dropbox library is properly managing memory. If yes, then might be easier to switch to using Flysystem's Dropbox impl.

CC @Xenopathic if you're looking for a challenge :wink:

**Comment by PVince81** [comment]
Or use a direct URL like it was done in https://github.com/owncloud/core/pull/21732

**Comment by PVince81** [comment]
Fix for download here: https://github.com/owncloud/core/pull/23272

**Comment by PVince81** [comment]
I had a look at the library and from what I see it doesn't store the file in memory on upload, it even uses chunking when possible.

**Comment by PVince81** [comment]
Reopening as there were issues when testing downloading big files (timeouts).

Alternative approach with stream download: https://github.com/owncloud/core/pull/23516

**Comment by PVince81** [comment]
This already made it into 9.0.1: https://github.com/owncloud/core/pull/23522

Closing
