### ISSUE TITLE
files_version app lacks configuration options

### ISSUE THREAD

**Issue by cortho** [owncloud/core#40411]
For our hosted ownCloud customers we ware watching that data usage is highly increasing without any chance to reasonably manage it. The is because the `files_versions` app cannot be configured in detail as it is possible with `files_trashbin`.

* It is not possible to **exclude certain file types** from versioning, for `files_trashbin` this is configurable. (e.g. .pst, .iso).
* There is no setting of the **maximum file size** that will be versioned. I want to be able to determine as a customer that e.g. files from 500MB should not be versioned. This is configurable for `files_trashbin`,
* There is no chance to configure **how many versions** are created
 * As a regular user and even as an admin I **cannot delete any version**.
* There is no possibility to **see that and how much space is used** for versions.

As configuration option only the retention policy is present, see https://doc.owncloud.com/server/next/admin_manual/configuration/server/config_sample_php_parameters.html#file-versions

This does not help, when e.g. an Outlook pst is synced multiple times a day filling up to gigabytes of versions within one day that cannot be deleted.

Tested wit the most recent files_versions 1.3.0
NB: I did not fill out the issue template since this is not applicable in this case

**Comment by cortho** [comment]
unstale

**Comment by cortho** [comment]
unstale

**Comment by cortho** [comment]
unstale

**Comment by DeepDiver1975** [comment]
We can close this - there are no plans to build new features into ownCloud 10
