### ISSUE TITLE
"Trusted_domains" login issue after the latest release update (no useful hint on 'error' web page)

### ISSUE THREAD

**Issue by sigma-design** [owncloud/core#40439]
### Steps to reproduce
1. Update to the latest available version of ownCloud.
2. Try to enter ownCloud web page after update.

### Expected behaviour
Login screen as before update.

### Actual behaviour
Error screen about "untrusted domain" with reference **only to config.php** (modifications to config.php did not help).

Suggested improvement: for users/admins benefit please consider adding to error page (rather important) information about now required "trusted domains" environment variable, so people are made aware about this important change there and then.

Note: it's a potential UI improvment, not a code bug as such, so further details are not very relevant, but provided anyway.

### Server configuration
**Operating system**: Ubuntu 22.04

**Web server:** ownCloud/server:latest Docker container behind Caddy reverse proxy.

**Database:** ownCloud

**PHP version:** 8.1.2

**ownCloud version:** the latest (v10.11.0)

**Updated from an older ownCloud or fresh install:** updated from previous 'latest'

**Where did you install ownCloud from:** Docker Hub

**Signing status (ownCloud 9.0 and above):** Could not log in until discovering that a new environment variable about "trusted domains" is critical and required.

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and put the link here.
```

**The content of config/config.php:** The content of config.php turns out not to be relevant, see above. 

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by xoxys** [comment]
AFAIK we don't have a way to display different messages (regardless of the particular case) depending on the installation method.

As reference if someone else is stumbling over this issue and is still looking for a solution:

https://central.owncloud.org/t/important-changes-to-owncloud-server-container-deployments/39642/3
https://central.owncloud.org/t/docker-compose-multiple-trusted-domains-issue/39659/7

**Comment by sigma-design** [comment]
The issue is not about the installation method, rather about improving web UI/UX by modifying/extending returned error screen message - the error web-UI screen is already specific about "untrusted domain", but lacks any mention about now required environment variable.

Adding such text to the already existing message looks as a very simple, but effective UI/UX improvement saving headaches and frustration when waking up to not working ownCloud instances/services (calendars, logins, etc.) after automatic overnight update and not having a real clue of what's going on.

N.B. As an example, I have spent a few fruitless hours trying to restore ownCloud functionality by following error screen recommendation about config.php before digging out the information about now required environment variable for "trusted domains".

**Comment by sigma-design** [comment]
This is the ownCloud web-UI screen I am referring to:

![image](https://user-images.githubusercontent.com/46909189/197045608-7456cbe6-3ed8-4763-9a61-519e67da09aa.png)

**Comment by ho4ho** [comment]
But env var `OWNCLOUD_TRUSTED_DOMAINS` only valid by docker installs, not by normal ownCloud install and not possible to see differences by ownCloud like saying by @xoxys :

> AFAIK we don't have a way to display different messages (regardless of the particular case) depending on the installation method.

Current message include link by documentation, could be solved by extending documentation? -> https://github.com/owncloud/docs/issues ?

**Comment by sigma-design** [comment]
IMHO, the less hurdles the better - I believe that Docker installations are popular enough to warrant some slight text changes, e.g.:

_... If you are an administrator of this instance, configure the "trusted_domains" setting in config/config.php **(also configure OWNCLOUD_TRUSTED_DOMAINS environment variable if using Docker installation)**. ..._

**Comment by sigma-design** [comment]
10M+ pulls are shown on Docker Hub for owncloud/server image:
![image](https://user-images.githubusercontent.com/46909189/197288544-f10e7914-be25-4308-ba8c-d66841013a29.png)

**Comment by ho4ho** [comment]
Personally IMHO not worthing effort:

Only available by next ownCloud update released by many months later

Needing additional work by translators

https://hub.docker.com/r/owncloud/server/ documents:

> IMPORTANT: We had to change the behavior of the ownCloud setting for trusted domains. Instead of automatic detection, it is now required to set all trusted domains with the environment variable "OWNCLOUD_TRUSTED_DOMAINS".

https://doc.owncloud.com/server/10.11/admin_manual/installation/docker/ documents OWNCLOUD_TRUSTED_DOMAINS also

but let's seeing what ownCloud people thinking because work needing to be done by them.

**Comment by Still34** [comment]
I wasn't aware of such change until I stumbled across this issue while researching. Would be a nice UI improvement.

**Comment by phoenix-bjoern** [comment]
It is actually a bug in `overwrite.config.php`: `$domain` should be an array and for the env variable `OWNCLOUD_TRUSTED_DOMAINS` it is implemented correctly. But for the env variable `OWNCLOUD_DOMAIN`, which is used as a fallback, the following code returns a string instead of an array:

```
  if (getenv('OWNCLOUD_TRUSTED_DOMAINS') != '') {
    $domain =  array_map('trim', explode(',', getenv('OWNCLOUD_TRUSTED_DOMAINS')));
  } else {
    $domain = explode(':', getenv('OWNCLOUD_DOMAIN'))[0];
  }
```

A fix could be to remove the `[0]` at the end:

```    $domain = explode(':', getenv('OWNCLOUD_DOMAIN'));```

I would love to create a PR but I can't find the `overwrite.config.php` in the code base.

**Comment by ho4ho** [comment]
Looked unrelated by ownCloud core but code by docker container itself:

https://github.com/owncloud-docker/base/blob/master/latest/overlay/etc/templates/config.php#L4-L8

**Comment by phoenix-bjoern** [comment]
The MR has been accepted, so I think this issue can be closed as soon as a new release is available on Docker Hub.

**Comment by PatrickHsu36** [comment]
For this issue, I just think, ownCloud should not force to ask users to set "ALL" trusted domains via docker env every time.
The docker env can be set once, but the configuration should be overwrite by config.php. That means the trusted_doamins of config.php should overwrite the docker env. That will be easily for users to maintain the configuration. Not always set "All" trusted_domain via docker env "OWNCLOUD_TRUSTED_DOMAINS".
Once I remove the line 

'trusted_domains' => $domain,

from overwrite.config.php, then ownCloud can allow to follow up the trusted_domains configuration on config.php.

How do you think?

**Comment by PatrickHsu36** [comment]
I know that ownCloud 10.10 and above is forced request to use OWNCLOUD_TRUSTED_DOMAINS for docker container ONLY. But that is really not a good design for using the docker container. While users want to add another trusted domain, he need to stop container, edit the env, start it again. While update the container, the settings may need to change again. Since this kind of design, some people met the problem, and  they always don't understand, why the trusted_domains in config.php cannot work anymore. But config.php is designed for users to edit or add extra and specific configuration by himself, but ownCloud break this kind of normal behavior for docker container users, it's not user friendly.
Anyway, this is the opinion by users, I think this is not a good design for use.

**Comment by djjudas21** [comment]
@PatrickHsu36 Containers are designed to be immutable and you start them up with whatever env vars you need. You restart them if you need to change the env. If this sounds like a pain (because it is), that's what container orchestrators like Kubernetes are for :slightly_smiling_face:

**Comment by firephreek** [comment]
@PatrickHsu36 Given that I just filed a new bug (#41086 ) for this issue, I'd say that it hasn't yet been addressed entirely.  Whether it's a bug or a lack of clarity in documentation, I can't really say given the various 'solutions' I've seen.  And while I can appreciate a philosophy of container immutability, it is also the case that any number of servers have configuration values that can be changed at run time. If owncloud isn't capable or designed to support these kinds of configuration changes at runtime, it might be better to say that than to tell people they're using docker 'wrong'.

**Comment by chrisdu** [comment]
Please can someone tell me if there is a solution now?

**Comment by iasdeoupxe** [comment]
@chrisdu See existing documentation for a solution:

https://doc.owncloud.com/server/10.13/admin_manual/configuration/server/config_sample_php_parameters.html#define-list-of-trusted-domains-that-users-can-log-into

**Comment by jcvikl** [comment]
This is so painful... 404!!!
https://doc.owncloud.com/server/10.13/admin_manual/configuration/server/config_sample_php_parameters.html#define-list-of-trusted-domains-that-users-can-log-into

or when using Docker (See OWNCLOUD_TRUSTED_DOMAINS there):

https://doc.owncloud.com/server/10.13/admin_manual/installation/docker/#docker-compose

**Comment by iasdeoupxe** [comment]
Replace 10.13 with 10.14 :wink: 

https://doc.owncloud.com/server/10.14/admin_manual/configuration/server/config_sample_php_parameters.html#define-list-of-trusted-domains-that-users-can-log-into

https://doc.owncloud.com/server/10.14/admin_manual/installation/docker/#docker-compose
