### ISSUE TITLE
Cleanup old skip tags in acceptance tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#40443]
The acceptance tests have a lot of old skip tags like `@skipOnOcV10.6 @skipOnOcV10.7 @skipOnOcV10.8.0` etc.

These are used when we have new tests or changed tests (because of changed behavior in a newer oC10 release), to prevent the test scenarios being run if and when we run the test set against an older version of oC10.

We sometimes run the core tests in the CI of an oC10 app repo to verify that having the app installed and enabled does not break any of the "ordinary" core external behavior. For example, with S3 storage, or encryption, or LDAP authentication apps enabled, the core functionality should still all work the same. In order to ensure that the code of an oC10 app release still works with older versions of core oC10, we run the CI from the app repo with one or two older versions of oC10 in place.

For the current core master test suite, we only ever need to run the tests against a current core master, or against 10.11 (latest release at the time of writing) or against 10.10 (2nd-latest release).

So the following can be done:
- remove any `@skipOnOcV10.*` tags for versions before 10.10
- remove any example tables, or scenarios, or scenario outlines that will never actually run any more. For example, there is tag `@skipOnAllVersionsGreaterThanOcV10.8.0` - I think that those scenarios will only run on 10.7 10.6... - and so they can be deleted completely.

This should cleanup the tagging a lot, which will reduce future confusion.

**Comment by amrita-shrestha** [comment]
currently, @roshanlc is looking into this issue

**Comment by roshanlc** [comment]
The issue has been resolved. It can be closed now.

**Comment by SwikritiT** [comment]
Closing the issue as completed.
