### ISSUE TITLE
CORS / wrong response to OPTIONS request

### ISSUE THREAD

**Issue by stefansaenger** [owncloud/core#40458]
### Steps to reproduce
try requesting owncloud resources with credentials from a differnet origin than the actual owncloud deployment

### Expected behaviour
response to the OPTIONS request uses the actual origin in Access-Control-Allow-Origin header, as required 
see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin for reference

### Actual behaviour
response to OPTIONS is created with Access-Control-Allow-Origin: "*" - which breaks for requests with credentials

### Server configuration
official owncloud/server image 

### root cause
 setOptionsRequestHeaders in lib/private/legacy/response.php does not use the origin, but returns a hardcoded "*"

ref: https://github.com/owncloud/core/blob/master/lib/private/legacy/response.php#L334

**Comment by DeepDiver1975** [comment]
Seems reasonable. THX for reporting

**Comment by DeepDiver1975** [comment]
@stefansaenger Which API are you calling? Can you maybe even provide a code snippet of the client code calling this API? THX
