### ISSUE TITLE
PHP Unit test failing for sqlite windows

### ISSUE THREAD

**Issue by grgprarup** [owncloud/core#40457]
Drone build: https://drone.owncloud.com/owncloud/core/37121/19/6, https://drone.owncloud.com/owncloud/core/37123/23/6, https://drone.owncloud.com/owncloud/core/37124/23/7, https://drone.owncloud.com/owncloud/core/37128/23/7
Tests are failing for pipeline `phpunit-php7.4-sqlite-windows`
```
+ phpunit_cmd='php ../lib/composer/bin/phpunit'
+ [[ true == \t\r\u\e ]]
+ phpunit_cmd='phpdbg -d memory_limit=6G -rr ../lib/composer/bin/phpunit'
+ [[ -n windows ]]
+ set_up_external_storage
+ php occ app:enable files_external
files_external enabled
+ php occ config:app:set core enable_external_storage --value=yes
Config value enable_external_storage for app core set to yes
+ case "${FILES_EXTERNAL_TYPE}" in
+ wait-for-it -t 600 fsweb.test.owncloud.com:445
services aren't ready in 10m0s
```

**Comment by grgprarup** [comment]
@phil-davis Do you have any idea about this failure?

**Comment by saw-jan** [comment]
Looks like the external server is down. I don't think we can do anything other than the discussion on what to do in such cases.

Some queries that may help to decide:
- Will `fsweb.test.owncloud.com:445` be available or is it permanently down?
- Any ideas on what can be done whenever the external service is down?

**Comment by phil-davis** [comment]
PR #40426 is waiting for a decision. The fsweb server seems to have gone down again.
I suggest that we merge the PR to get CI green. And then someone can decide what to do to get a CI environment going again.

**Comment by jnweiger** [comment]
@GeraldLeikam this is the one that is waiting for your new AD server

**Comment by phil-davis** [comment]
@GeraldLeikam (cc @jnweiger ) what happened about getting a new server for this?

**Comment by saw-jan** [comment]
The windows pipeline has been removed: https://github.com/owncloud/core/pull/40426

**Comment by DeepDiver1975** [comment]
Once the new server is there we will reactivate the pipeline.
