### ISSUE TITLE
Solve locking ?

### ISSUE THREAD

**Issue by hannesa2** [owncloud/core#40453]
How to solve this locking ? 
<img width="768" alt="image" src="https://user-images.githubusercontent.com/3314607/198230059-a79e3815-eedc-412c-81c2-d22ed212d16c.png">

I use version `10.5.0.10`

**Comment by JammingBen** [comment]
I transferred your issue to the ownCloud core repository. General oC10 issues are best suited there :) The [Web repository](https://github.com/owncloud/web) is for everything related to the new Web UI.

As for your locking issue, maybe the file is locked manually? See https://doc.owncloud.com/server/next/admin_manual/configuration/files/manual_file_locking.html.

 `10.5.0.10` is pretty out-dated though, we’re currently running `10.11.0`. If upgrading is a possibility, I strongly recommend that. Possibly solves the locking issue as well.
