### ISSUE TITLE
Own Cloud Updater fails (Current version is 10.6.0.5, Online version is 10.8.0 [stable])

### ISSUE THREAD

**Issue by Theater-im-Pariser-Hof** [owncloud/core#40474]
### Steps to reproduce
1. Open Own Cloud as admin
2. Go to Updater
3. Start it

### Expected behaviour
Should update own cloud

### Actual behaviour
fails with error: 
Current version is 10.6.0.5
Online version is 10.8.0 [stable]
Downloaded 100% (17 of 17) Downloaded 100% (17 of 17)
Deleted 10.8.0.zip due to wrong checksum

### Server configuration
Linux

**Web server:**

**Database:**

**PHP version:**
PHP 7.4

**ownCloud version:** (see ownCloud admin page)
Current version is 10.6.0.5
**Updated from an older ownCloud or fresh install:**
Updated
**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ho4ho** [comment]
Better using manual upgradation:

> (Recommended) Perform a [manual upgrade](https://doc.owncloud.com/server/10.11/admin_manual/maintenance/upgrading/manual_upgrade.html), using the [latest ownCloud release](https://owncloud.com/download-server/).

https://doc.owncloud.com/server/10.11/admin_manual/maintenance/upgrading/upgrade.html#upgrade-options

**Comment by Theater-im-Pariser-Hof** [comment]
Not able to fix it... Also I did hear, own cloud does not support PHP 8
