### ISSUE TITLE
Update message erroneously prompts upgrade to 10.11.0 even though that's what's already installed

### ISSUE THREAD

**Issue by posita** [owncloud/core#40491]
After a manual upgrade to 10.11.0, my admin user is continually prompted to upgrade to 10.11.0.

![Screenshot from 2022-11-13 22-26-12](https://user-images.githubusercontent.com/222581/201575638-f42461f3-d9a5-4cbd-91b1-22839685d27c.png)
![Screenshot from 2022-11-13 22-26-31](https://user-images.githubusercontent.com/222581/201575645-4be0b95a-d103-4def-862b-c19f8a85944a.png)

### Environment general
**Operating system**: Linux

``` sh
% uname -srvmpio
Linux 4.14.117-grsec-grsec+ owncloud/web#1 SMP Fri May 10 17:15:47 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Backend (ownCloud Core or Infinite Scale)**: core

**Are you using an external user-backend, if yes which one:** none

### Environment ownCloud Core
**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4.15

**Version:** 10.11.0.6

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tarball

**Signing status (ownCloud 9.0 and above):** ???

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and put the link here.
```

https://gist.github.com/posita/e6ccab936c7b99ff8463221b47153a20#file-failed

**The content of config/config.php:**

https://gist.github.com/posita/e6ccab936c7b99ff8463221b47153a20#file-occ-config-list-system

**List of activated apps:**

https://gist.github.com/posita/e6ccab936c7b99ff8463221b47153a20#file-occ-app-list

**Are you using external storage, if yes which one:** s3

**Are you using encryption:**  no (not available with s3)

**Comment by kulmann** [comment]
Hey @posita I've transferred your issue to the ownCloud `core` repo. Usually someone looks into new issues quickly. If nothing happens here please ping me again (I'm not a developer of the `core` but could ask around).

**Comment by ho4ho** [comment]
Could be cause by cache problem? Apache restart? Browser cache cleared?

**Comment by ho4ho** [comment]
Looking also like `owncloud.log` entrys not provided.

**Comment by posita** [comment]
I cleared my browser data for my installation domain and logged back in. There were no entries made to `owncloud.log` during this period, but the above behavior persists.

I do not have control over the Apache instances (I am on shared hosting). However, I can kill my own PHP Fast CGI processes, which I've done, also to no avail.

@ho4ho, are you asking because you cannot reproduce on your end?

**Comment by posita** [comment]
How does [`apps/updatenotification/js/notification.js`#L15-L17](https://github.com/owncloud/core/blob/e4c8e50a55b30c17ffc0688d6e308bf2d06a3829/apps/updatenotification/js/notification.js#L15-L17) get invoked (i.e., where's the code that triggers it)?

**Comment by VicDeo** [comment]
> How does [`apps/updatenotification/js/notification.js`#L15-L17](https://github.com/owncloud/core/blob/e4c8e50a55b30c17ffc0688d6e308bf2d06a3829/apps/updatenotification/js/notification.js#L15-L17) get invoked (i.e., where's the code that triggers it)?

https://github.com/owncloud/core/blob/e4c8e50a55b30c17ffc0688d6e308bf2d06a3829/apps/updatenotification/templates/admin.php#L2
