### ISSUE TITLE
OCM sharing to groups not supported?

### ISSUE THREAD

**Issue by michielbdejong** [owncloud/core#40530]
### Steps to reproduce
1. create a regular group or a custom group called 'mygroup' on server2.com
2. log in to server1.com
3. click a file and go to Share ...
4. type "mygroup@server2.com" as the recipient

### Expected behaviour
As described in [the OCM spec](https://cs3org.github.io/OCM-API/docs.html?branch=develop&repo=OCM-API&user=cs3org) the `shareWith` of an OCM share can be a username or a group name.
### Actual behaviour
The sharing will fail with a "user 'mygroup' not found" error, thrown from [these line of code](https://github.com/owncloud/core/blob/08a63ec/apps/federatedfilesharing/lib/Controller/OcmController.php#L226-L230)

**ownCloud version:** (see ownCloud admin page)
lastest master

**Comment by DeepDiver1975** [comment]
Yes - group sharing is not implemented. I doubt it will ever be due to conceptual complexity and the rare need. 
Closing for now

**Comment by jvillafanez** [comment]
Yes. The basic idea is that ownCloud will provide a way to switch the federated share provider so they can use their own implementation. This way their implementation can have group sharing the way they want.
