### ISSUE TITLE
Any chance to stop using PROPFIND for webdav?

### ISSUE THREAD

**Issue by skironDotNet** [owncloud/core#40541]
I have `Directory "/" not found` error in owncloud.
I think the problem I have with OC is it is behind Nginx Proxy Manager that may not be supporting PROPFIND as reported here 
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2490

![image](https://user-images.githubusercontent.com/2981715/208479286-8026f0da-835d-457e-929e-defd5ca27afb.png)

Any chance to replace that method with GET ?
I know this is no OC fault that "some" proxy is not handling HTTP method well, but I think lot's of software may not handle rather exotic HTTP PROPFIND method?

Thoughts? in the meantime I'll expose OC directly to check if will work without NPM...

**Comment by skironDotNet** [comment]
This was solved for NPM by disabling "Cache Assets", so the only thing the team could do it to **add to documentation:**

"If you experience `Directory "/" not found` when hosting behind Nginx Proxy Manager, disable `Cache Assets` option"

![image](https://user-images.githubusercontent.com/2981715/208581558-03d353a0-b058-4ac0-8271-e6e4a636d67d.png)

**Comment by ho4ho** [comment]
> This was solved for NPM by disabling "Cache Assets", so the only thing the team could do it to add to documentation:

Suggest:
- Ask by https://github.com/owncloud/docs-server/issues (not knowing if will accepted)
- This issue closing

**Comment by DeepDiver1975** [comment]
PROPFIND is an integral part of webdav - the question itself is not really reasonable.
