### ISSUE TITLE
File Versions diff comparison

### ISSUE THREAD

**Issue by johnmanko** [owncloud/core#4056]
I'd like to see an enhancement where one can view the diff between file versions.  

First, on the version dropdown menu, a command link should be added to each version option that will take the user to a version diff page, which will show the diff between the selected version and the previous version.

Second, on the page that lists all versions, each version entry should have a command to view the diff.  You can easily put a diff panel on the right side.

Third, on the file/directory list, when you select a version for a file, then there should be a clear indicator that the file is not on the latest version. 

There are many enhancement that can be made to versioning, but these are a good start.

**Comment by gw0** [comment]
This would be great! Although a check to not display binary files should be done.

Does any app already implement a simple diff on text files?

**Comment by Yamakasi** [comment]
@gw0 Yes Pydio does, I used it but Owncloud has more better features. They use git for it I thought.

**Comment by PVince81** [comment]
Core's versions app should provide JS APIs for other apps to provide diff views for whatever file types is being diffed. Then the text editor app could be extended to provide a diff view there using said API.
