### ISSUE TITLE
"Trusted Domains" list not working, despite adding my public IP

### ISSUE THREAD

**Issue by IveMalfunctioned** [owncloud/core#40578]
I am using the ownCloud version `10.11.0.6` Docker image with Docker engine version `v20.10.22` on Windows 10 x64 build `19045.2486`. 

After finding the `config.php` file located in `\\wsl$\docker-desktop-data\data\docker\volumes\d533f7e52dce0742f31d52707bd57639185d43a4ef0e3a2d19968f34eed5a440\_data\config` and editing it to add my public IP as the ONLY trusted domain (removing localhost also), it doesn't work to connect to it through port 8080 (I get the message "You are accessing the server from an untrusted domain." when trying to connect with it, yet localhost does despite it being removed. The config doesn't revert back, suggesting I edited it correctly, and restarting both the Docker VM and my PC doesn't solve the issue. Any help is appreciated.
![image](https://user-images.githubusercontent.com/20033421/212486302-6421051c-eef5-45a2-8265-4f16edf2555b.png)

**Comment by ho4ho** [comment]
Duplicate by: #40439

**Comment by DeepDiver1975** [comment]
Thx @ho4ho

**Comment by IveMalfunctioned** [comment]
ok and how do I access the OWNCLOUD_TRUSTED_DOMAINS environment variable. That second link directs me to the docs which cover what I already did which is what I said was not working in my comment.

**Comment by ho4ho** [comment]
Here: bugtracker, better use support by https://central.owncloud.org/

**Comment by IveMalfunctioned** [comment]
@ho4ho The thread already exists, can you just tell me

**Comment by DeepDiver1975** [comment]
> can you just tell me

It might sound harsh - but just learn how docker works. https://stackoverflow.com/questions/30494050/how-do-i-pass-environment-variables-to-docker-containers
