### ISSUE TITLE
Doctrine\DBAL\Exception\ConnectionLost during integrity check

### ISSUE THREAD

**Issue by nzerdh** [owncloud/core#40590]
Hi there,

I'm upgrading to 10.11 from 10.10. During the code integrity check I get this error:

Doctrine\DBAL\Exception\ConnectionLost: An exception occurred while executing 'INSERT INTO `oc_appconfig` (`appid`,`configkey`,`configvalue`) SELECT ?,?,? FROM `oc_appconfig` WHERE `appid` = ? AND `configkey` = ? HAVING COUNT(*) = 0' with params ["core", "oc.integritycheck.checker", "[]", "core", "oc.integritycheck.checker"]:

SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

Update failed.

How do I get pass this? Thank you.

**Comment by ho4ho** [comment]
Not problem/bug by ownCloud, problem by config database. Suggest: close

- https://doc.owncloud.com/server/10.11/admin_manual/troubleshooting/general_troubleshooting.html#common-problems-error-messages
- https://doc.owncloud.com/server/10.11/admin_manual/configuration/database/linux_database_configuration.html#how-to-workaround-general-error-2006-mysql-server-has-gone-away
- https://dev.mysql.com/doc/refman/8.0/en/gone-away.html
- https://haydenjames.io/mysql-server-has-gone-away-error-solutions/

**Comment by DeepDiver1975** [comment]
Thx @ho4ho
