### ISSUE TITLE
OC\RepairException: Upgrade is not possible - Please Help...

### ISSUE THREAD

**Issue by 66gold66** [owncloud/core#40601]
i had owncloud version 10.8 i wanted to upgrade to 10.11. Unfortunately, the update did not complete because it shows the following errors:
- You have incompatible or missing apps enabled that could not be found or updated via the marketplace.
- Please install or update the following apps manually or disable them with: occ app:disable phonetrack
- For manually updating, see https://doc.owncloud.com/server/10.11/go.php?to=admin-marketplace-apps

Unfortunately I can't manually update marketplease. I didn't find any helpful material in the FAQ or similar thread here...
I'm begging for help :(
link to the disk: http://www.dysk.proinspect.pl/

**Comment by ho4ho** [comment]
Not bug by update problem by incompatible app.

Suggest:
- Close
- Follow now "or disable them with: occ app:disable phonetrack"
- Future following https://doc.owncloud.com/server/10.11/admin_manual/maintenance/upgrading/upgrade.html before upgradation:
  > Review any installed [third-party apps](https://doc.owncloud.com/server/10.11/admin_manual/maintenance/upgrading/manual_upgrade.html#review-third-party-apps) for compatibility with the new ownCloud release.

**Comment by VicDeo** [comment]
@66gold66 
> Please install or update the following apps manually or disable them with: occ app:disable phonetrack

You have an app that is incompatible with the target ownCloud version
That's what you are expected to do:
**disable** phonetrack app with the command above or via UI **before** upgrading ownCloud
or
**wait** until phonetrack app for ownCloud  10.11 is released
