### ISSUE TITLE
Disable Password,Email,DisplayName change etc.

### ISSUE THREAD

**Issue by IljaN** [owncloud/core#40610]
Since the user is coming from OIDC he shouldn't have this options inside ownCloud.

**Comment by DeepDiver1975** [comment]
core functionality:
- disallow password reset for auto provisioned accounts (will this expose information to potential attackers? - if so do proper error handling - refs #40512) 
- disallow user to change password, email, displayname and profile pic
- app must still be capable to update user information (shib, ldap, openid)
