### ISSUE TITLE
 PDFViewer / Content Security Policy blocks 'blob:' and 'frame-src'

### ISSUE THREAD

**Issue by vkael** [owncloud/core#40639]
### Steps to reproduce
1. Install latest OwnCloud server
2. Configure it to use OwnCloud Web application new front-end
3. Upload a PDF
4. Try to preview said PDF

### Expected behaviour
PDF is shown.

### Actual behaviour
CSP configuration does not allow neither `blob:` (Chrome/Firefox), nor `frame-src` (Chrome only) : 
![image](https://user-images.githubusercontent.com/85616869/218868731-66115eb7-0a72-4ef3-938c-4f61271966bb.png)

View :
![image](https://user-images.githubusercontent.com/85616869/218868452-ad322a68-0379-46f5-8829-0c3c68b725cf.png)

### Server configuration
**Operating system**: Debian 11

**Web server:** NGINX

**Database:** MySQL

**PHP version:**

**ownCloud version:** 10.11

**Updated from an older ownCloud or fresh install:** Updated

**Where did you install ownCloud from:** OwnCloud website

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
"preview",
"pdf-viewer",
"search",
"text-editor",
"draw-io"
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome 110.0.5481.100 and Firefox 110

**Operating system:** Windows 11

#### Browser log
```
Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://xyz.com/bb6b39b8-1d71-4960-bc4c-16ab79bc1044 (“default-src”).
```

**Comment by DeepDiver1975** [comment]
not a core issue - thx for your contribtion
