### ISSUE TITLE
Docker: Logged out whenever browser is closed and opened again

### ISSUE THREAD

**Issue by dillfrescott** [owncloud/core#40635]
There seems to be no way to fix this

**Comment by dillfrescott** [comment]
I tried adding session and cookie values to the config.php, and I also tried the related env variables on the docker container. Nothing is working.

**Comment by ho4ho** [comment]
Needing:
- 10.11.0+
- > "stay logged in" checkbox in the login page
- > Note that this feature relies on all the enabled apps to allow this feature. Some apps such as "files_external" or "encryption" can disable this feature if they're enabled.

#40170, #40176
