### ISSUE TITLE
client file index does not update when files are deleted by outside source, such as the host

### ISSUE THREAD

**Issue by IveMalfunctioned** [owncloud/core#40634]
### Steps to reproduce
1. Create a file
2. Delete it from the server host OS
3. Refresh client

### Expected behaviour
File no longer exists in the file list

### Actual behaviour
It's still there and fails to load when clicked on, then is removed.

### Server configuration
**Operating system**:
Windows 10 22H2, 19045.2486
Docker Desktop v4.16.1

**Web server:**
`ownCloud 10.11.0`

**Database:**
N/A

**PHP version:**
N/A

**ownCloud version:** (see ownCloud admin page)
`10.11.0.6`

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
https://hub.docker.com/r/owncloud/server/
`docker pull ownCloud/server` in PowerShell

**Signing status (ownCloud 9.0 and above):**
N/A

Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and put the link here.
`No errors have been found.`

**The content of config/config.php:**
[config_report_20230211.txt](https://github.com/owncloud/core/files/10712282/config_report_20230211.txt)

**List of activated apps:**
N/A

### Client configuration 1
**Browser:** Mozilla Firefox 109.0.1 x64

**Operating system:** Windows 10 22H2, 19045.2486

### Client configuration 2
**Browser:** ownCloud App version 3.0.2

**Operating system:** Android 11

#### Web server log
https://gist.github.com/IveMalfunctioned/8fe1957f6ffebe57418417c00a7327a6

#### ownCloud log (data/owncloud.log)
N/A

#### Browser log
N/A

**Comment by ho4ho** [comment]
Not bug by ownCloud, works designed. Never ever touch manually files:

> The data directory on the server is exclusive to ownCloud and must not be modified manually.

https://doc.owncloud.com/server/10.11/admin_manual/troubleshooting/general_troubleshooting.html#debugging-sync-issues

**Comment by IveMalfunctioned** [comment]
Oh, ok. Is there a re-sync button somewhere?

**Comment by IveMalfunctioned** [comment]
@ho4ho

**Comment by DeepDiver1975** [comment]
Try file scan command.
