### ISSUE TITLE
[QA] Manual file lock prevents owner from changing the file

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#40637]
Seen in 10.11.0.6 
* Admin enables manual file locking (General settings section)
* Admin shares his documents folder with Alice (to make a scenario where concurrent changes can happen - issue can be reproduced without this step too.)
* Admin uploads a file foo.txt into his documents folder.
* Admin locks the file (right hand side 3-dots menu)
* Admin tries to upload a new copy of foo.txt - a compare dialog appears
* Admin chooses new version. An error occurs. The file is currently locked. BAD

![grafik](https://user-images.githubusercontent.com/1108546/218419119-75608932-f935-4a4b-86f7-6af9b9a44004.png)

https://doc.owncloud.com/server/next/admin_manual/configuration/files/manual_file_locking.html#introduction says:
"Manual file locking allows users, if enabled, to lock files in shared areas while working on them in order to prevent concurrent changes from other users (check-in/check-out)."
...
"While a file is locked, other users can still access it but they can not make any changes."

Expected behaviour:
* Code behaviour and documentation should be in sync.
* The user who locked the file can still upload new copies.
* The user who locked the file can use text editor to change the file.
* Other users are downgraded to readonly while a lock exists.

I am absolutely unsure if that feature works as designed.

**Comment by jnweiger** [comment]
The language in the docs is a bit weird "in shared areas" and "(check-in/check-out)" -- that seems to include upload, edit through desktop clients, etc.

**Comment by phil-davis** [comment]
As a user, I would like the following:

- I can potentially change a file using multiple apps and/or clients. For example, I can do an upload-overwrite in the webUI, I can change the file on my laptop and the desktop client will sync it up to the server, maybe I can change the file on my Android or iOS device and it will be synced up to the server, I can edit the file in some app-package like Office365, or Collabora or..
- I can share a file with write access to someone else, and they can change the file (with any of the methods above...)

I want to work on a file using an "app". I want to prevent anyone and anything else from modifying the file while I am working on it, including preventing myself from changing it from another "app" or "client".

And so I think that technically I might need some way to:

- take out a lock that knows my user id and some app id (for example, locked by Alice for use from files_texteditor)
- the lock has some sort of lock-override "token" that is made available to the app or client
- a request to update the file that has good authentication for Alice, and provides the lock-override "token" is allowed to update the file content and metadata
- any other update request (from another user, or from Alice from a different app or client that does not know the "token") is, is rejected

This is the kind of lock that I am used to. For example, in an OS file system, a process can lock a file for write-lock, the process can still write to the file, but no-one else can write to the file.

**Comment by mmattel** [comment]
If a doc change is needed, an issue needs to be filed in docs-server with an exact description what needs changing - best file a PR, we will then take care finalizing it.

**Comment by hodyroff** [comment]
Sorry, All discussed. A lock is a lock. Period. Lock set = works from everywhere. We also do it for files only = no folders. Too many corner cases otherwise. Must be practical. Works as designed.

**Comment by phil-davis** [comment]
Note: from my reading, webDAV does do locking like in my comment https://github.com/owncloud/core/issues/40637#issuecomment-1427690896
The client that requests the lock is returned a lock token, and can do updates by providing that token (along with the usual authentication and the new file content).
Also see https://www.w3.org/Amaya/User/doc/WebDAV.html
https://www.webdavsystem.com/ajax/programming/locking/

If a client "understands" this, the client can take out a lock, remember the lock, and use the lock to update the file. Then unlock the file when it wants. I suppose that Collabora, MS Office etc. do this kind of thing under the hood.

So if there is enough of a use case, this locking can be implemented in any app/client.

**Comment by hodyroff** [comment]
Cool, lets keep it in mind when we integrate locks with the desktop. @michaelstingl

**Comment by michaelstingl** [comment]
> Cool, lets keep it in mind when we integrate locks with the desktop. @michaelstingl

Currently there's no technical concept for locking in desktop and mobile clients. Backend lacks capability to propagate locks to the clients, and clients would just wait for unlock, then perform all actions when the lock ended. Needs concept work that can't be done in the clients alone…
