### ISSUE TITLE
 How do we disable the PHP check for trusted domains? 

### ISSUE THREAD

**Issue by erik777** [owncloud/core#40655]
I’ve been considering ownCloud as part of a solution to provide to thousands of people to be able to just plug in and use. In order for this to work, it needs to be a blackbox that just works. Internal runtime target is Linux with docker.

Up until the recent change, anyone could then configure their networking outside the box to do any port forwarding, reverse proxy, or whatever to give access to their instance, or just use as is on their LAN.

Requiring end users to edit any files inside the box, whether that be PHP or YAML, is not an option.  The primary goal is plug-and-play. 

I'd like an option to return it to pre-10.11.x behavior, perhaps via a YML environment variable.  Ideally, something like OWNCLOUD_TRUSTED_DOMAINS=*.

**Comment by ho4ho** [comment]
> I'd like an option to return it to pre-10.11.x behavior,

Not changing done by ownCloud, ownCloud always had same behavior. Need to discuss by ownCloud docker peps:

https://github.com/owncloud-docker/server/issues

**Comment by ho4ho** [comment]
- Same posting by https://central.owncloud.org/t/how-do-we-disable-the-php-check-for-trusted-domains/41293, not thinking good posting both places
- Old behave security issue: https://owncloud.com/security-advisories/url-spoofing-in-password-reset-mail/

**Comment by ho4ho** [comment]
By https://github.com/owncloud-docker/base/pull/238#issuecomment-1445325740:

> That was a security related change well explained in the PR description. We have added a note about this to all repo readmes and pinned a post in central for a while **and there are no plans to revert this change.**

**Comment by xoxys** [comment]
> Not changing done by ownCloud, ownCloud always had same behavior.

This is not true. The `trusted_domain` setting is a configuration option from ownCloud core `config.php`. This configuration was always and still is mandatory for each deployment. 

In the past, the ownCloud container has done some magic on a container startup that was using Client Headers to auto-detect the used domain and set the `trusted_domain` configuration accordingly. As client headers can't be trusted, this auto-detection mechanism was removed in https://github.com/owncloud-docker/base/pull/238 and ownCloud the container behaves like every other host-based ownCloud deployment as well now.

**Comment by ho4ho** [comment]
> This configuration was always and still is mandatory for each deployment.

Yes, me saying this exactly. But user said:

> Up until the recent change
>
> I'd like an option to return it to pre-10.11.x behavior

but only behavior changed by ownCloud docker container but ownCloud core always needing requiring option.

Only wanting saying that ownCloud core not have changing, only ownCloud docker container changing.

**Comment by erik777** [comment]
Did you close the ticket because you want me to post the request to the owncloud-docker project?  

Thanks you for the PR link @xoxys.  I was looking in the code in core and it didn't add up how it changed, though I did find a line where I could remove check for trusted domains and did see where I could add the logic I described.  Despite the breaking change in owncloud-docker, you could implement this request for "*" (trust all domains) in isTrustedDomain in TrustedDomainHelper.php.  

Can you please re-open this ticket so we can discuss this option?

**Comment by xoxys** [comment]
> Did you close the ticket because you want me to post the request to the owncloud-docker project?

No, we will not change the behavior of the container.

> Can you please re-open this ticket so we can discuss this option?

I do not understand why this needs to be discussed. Every application has mandatory settings. For ownCloud, it is necessary to configure `trusted_domains` accordingly for it to work properly. Just set it to the real domain and you are done. For production setups, there are also a lot of other important settings that need to be adjusted.

**Comment by erik777** [comment]
@xoxys 

This is absolutely required to be able to roll this out to a larger demographic via a plug-and-play device they just plug into a LAN port or configure to connect to their wireless router and it works.  By refusing to discuss you are closing and entire demographic of potential users to ownCloud.  And, it is a very simple change request that will not impact current users.

**Comment by xoxys** [comment]
I have not closed the issue, maybe @DeepDiver1975 wants to add something. However, if you really need it to work this way, you can also build your own container image and add a custom setup logic.

**Comment by erik777** [comment]
@xoxys I understand I could modify a fork.  If I do that, I'd do it for core, because that is the best place to add this new feature.  But, then I'll constantly have to merge new changes into the fork and I'd really like to avoid that for what is basically a few lines of code difference.  

I am open to providing a PR of the change if, ahead of time, we can agree this is a viable option.

**Comment by ho4ho** [comment]
User of box need other settings specifying like admin user, why not requiring them config `OWNCLOUD_TRUSTED_DOMAINS` as well?

**Comment by DeepDiver1975** [comment]
Simply define all trusted domains in the config and you are done.

**Comment by erik777** [comment]
@DeepDiver1975 and what domains can you configure one time that will let grandma plug her portable ownCloud into any LAN and access it from anywhere?

**Comment by ho4ho** [comment]
Not Diver but answering still:
- grandma using domain for access: `OWNCLOUD_TRUSTED_DOMAINS = "domain for access"`
- grandma using IP for access: `OWNCLOUD_TRUSTED_DOMAINS = "current dynamic ip of box"`

**Comment by erik777** [comment]
@ho4ho so you want grandma to ssh into the portable owncloud, and use vi to edit the YML?

**Comment by ho4ho** [comment]
No, portable ownCloud know own IP and set `OWNCLOUD_TRUSTED_DOMAINS` by current IP by automatic script and done?

**Comment by erik777** [comment]
@ho4ho or just add one line to isTrustedDomain and done.  It is up to us, the users, if we want to use a wildcard.

**Comment by ho4ho** [comment]
Thinking software not allow users shooting in own foot, but only personal opinion mine.

**Comment by erik777** [comment]
@ho4ho Grandma plugs her portable owncloud into a LAN port and accesses via the IP without fuss because it has the domain check wild carded.  How does grandma shoot herself in the foot?

**Comment by ho4ho** [comment]
`trusted_domains: security functionality by ownCloud, use wildcard: Disables security

**Comment by ho4ho** [comment]
e.g. could using by host by startup:

```
export OWNCLOUD_TRUSTED_DOMAINS=`hostname -I | awk '{print $1}'`
```

Not knowing what problem not knowing box but could solve easily for special use case by not weakining security?

**Comment by erik777** [comment]
It disables host checking.  It does not disable security.  Passwords still work.  Can only access via one IP and port.  That IP is by default only on the LAN.  Even if someone puts on the Internet with port forwarding, why is it so important that it only be accessible by a limited list of host names?  If it is really important to me, I can route through a reverse proxy via named virtual hosting.  But, honestly, I can care less if someone creates a host "the.best.owncloud" and points it to my owncloud.  

I understand the change in docker.  But, I don't understand why on we're so quick to rule out expanding the demographics of potential ownCloud users and increasing the size of our community because someone thinks that allowing users to wild card host names to their own instances can cause disaster.

**Comment by ho4ho** [comment]
> https://owncloud.com/security-advisories/url-spoofing-in-password-reset-mail/
> The docker image of the ownCloud server contained a misconfiguration which rendered the ‘trusted_domains’ config useless. This could be abused to spoof the URL in password reset mails.

+

> https://doc.owncloud.com/server/10.11/admin_manual/configuration/server/config_sample_php_parameters.html#define-list-of-trusted-domains-that-users-can-log-into
> Specifying trusted domains prevents host header poisoning.
>
> Do not remove this, as it performs necessary security checks.

Wildcard allowing -> Cause security issues

**Comment by erik777** [comment]
@ho4ho only for users who (a) put their owncloud on the internet and (b) do not use a reverse proxy with named virtual hosting and (c) intentionally put in a wild card.  

But, with today's configuration, grandma has to print and carry her photos and recipes because she does not have a portable owncloud.  I guess you can argue you are keeping grandma secure by telling her that owncloud is not for her.

**Comment by ho4ho** [comment]
Or following https://github.com/owncloud/core/issues/40655#issuecomment-1445380898:

- Keep ownCloud secure not weakening security
- Solve problem on special portable ownCloud by that

?

**Comment by erik777** [comment]
@xoxys @DeepDiver1975 Please let me know if you would like me to create a PR.  Perhaps you need time to think about this.

**Comment by TheRealKasumi** [comment]
@erik777 I also was looking for an option to disable it. But from reading the comments in this (and other) issue(s), such a thing will probably never exist. Generally, I felt like everyone I found asking for it was put down quickly xD ... God damn it, just let ppl do what they want with their own system.

When you are still looking for a (hacky) way to get around that stupid thing you can try the config below. It at least works in some cases.

```php
  'trusted_domains' => array (0 => $_SERVER['HTTP_HOST']),
```

And before someone is throwing `but this will make your server explode` into my face ... Yeah yeah... I am a grown girl and can decide that for myself😉.

**Comment by DeepDiver1975** [comment]
> God damn it, just let ppl do what they want with their own system.



> am a grown girl and can decide that for myselfwink.

You have the source code - change it as you like. :shrug:

**Comment by TheRealKasumi** [comment]
> You have the source code - change it as you like. 🤷

Don't take it too serious. Should have added a warning that my comment might contain some fun and sarcasm. Ofc, the source is available and can be adjusted. In my case simply not worth it for a temporary, internal solution that will be shut down after a few days.

**Comment by transilluminate** [comment]
For those arriving via Google, and bashing their heads against this problem...

The `trusted_domains` should be the hostname of the machine ownCloud is running on (not your subnet, etc). This is a problem for Docker instances, where the hostname can be a bit funny. 😄 The Docker .env file does not really work to fix this, and opening a terminal into the Docker instance is a big challenge as it does not have the needed tools to investigate and troubleshoot.

It seems `/files/config/config.php` is overridden by `overwrite.config.php` so changing this is pointless, and changing `overwrite.config.php` does not seem to persist across restarts.

But, as the files in `/files/config` are read alphabetically, you can create a file starting with a 'zz' which will override the previous ones. So, add the following to `/files/config/zz-user.config.php`

```
<?php
$CONFIG = array (
  'trusted_domains' =>
  array (
    0 => $_SERVER['HTTP_HOST'],
  ),
);
```
This will grab whatever the server thinks is it's proper hostname, and configure itself correctly.

(thanks @TheRealKasumi !)

**Comment by marenostrum1981** [comment]
> For those arriving via Google, and bashing their heads against this problem...
> 
> The `trusted_domains` should be the hostname of the machine ownCloud is running on (not your subnet, etc). This is a problem for Docker instances, where the hostname can be a bit funny. 😄 The Docker .env file does not really work to fix this, and opening a terminal into the Docker instance is a big challenge as it does not have the needed tools to investigate and troubleshoot.
> 
> It seems `/files/config/config.php` is overridden by `overwrite.config.php` so changing this is pointless, and changing `overwrite.config.php` does not seem to persist across restarts.
> 
> But, as the files in `/files/config` are read alphabetically, you can create a file starting with a 'zz' which will override the previous ones. So, add the following to `/files/config/zz-user.config.php`
> 
> ```
> <?php
> $CONFIG = array (
>   'trusted_domains' =>
>   array (
>     0 => $_SERVER['HTTP_HOST'],
>   ),
> );
> ```
> 
> This will grab whatever the server thinks is it's proper hostname, and configure itself correctly.
> 
> (thanks [@TheRealKasumi](https://github.com/TheRealKasumi) !)

Thank you. You are a lifesaver!
