### ISSUE TITLE
Upload date or Modify date

### ISSUE THREAD

**Issue by thesplox0** [owncloud/core#40679]
**Hello i am using cronjob which removes older files than 7 days. 
Here is my script = >  find /var/www/owncloud/data/*/* -name '*' -mtime +7 -delete
but when i have uploaded file owncloud shows modified date not uploaded data, can u help me?**

**Comment by ho4ho** [comment]
Bugtracker only here, support only by https://central.owncloud.org/

Suggest: Close

Also by https://doc.owncloud.com/server/10.11/admin_manual/troubleshooting/general_troubleshooting.html#debugging-sync-issues:

> The data directory on the server is exclusive to ownCloud and must not be modified manually.
