### ISSUE TITLE
Since update from 10.11 to 10.12 I get this error: Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken

### ISSUE THREAD

**Issue by HazMatt69** [owncloud/core#40686]
Since I've updated to 10.12, I get this error: Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken. And I don't have access to my files anymore.
I'm using Apache 2.4.54, PHP 7.4 and MariaDB version 10.5.18 on Debian 11.6
[owncloud.log](https://github.com/owncloud/core/files/10979319/owncloud.log)

**Comment by DeepDiver1975** [comment]
I could not spot any relevant log entries which relate to this error.

Never the less: please ask community support question at https://central.owncloud.com - THX

**Comment by HazMatt69** [comment]
@DeepDiver1975 You may have closed this a bit fast as another user reported the same error here: https://central.owncloud.org/t/owncloud-stoped-working-after-update/41513

**Comment by DeepDiver1975** [comment]
Once it has been identified as a bug I happily open an issue and fix it.

**Comment by HazMatt69** [comment]
Sounds good, thx!

**Comment by Krysztophe** [comment]
Seems to be a bug in the last version .htaccess : https://central.owncloud.org/t/owncloud-stoped-working-after-update/41513/15?u=kalligraphe 
Reverting the change solved the problem for me.

**Comment by ho4ho** [comment]
Cause by #40584 by `^` addition not match by e.g. `/owncloud/remote.php` if use sub-dir install?

All have problem: Use sub-dir install `/owncloud`?

**Comment by ho4ho** [comment]
Now also report by #40696 and possible fix by #40697
