### ISSUE TITLE
[QA] Persistent major versions are deleted by `occ versions:cleanup`

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#40680]
Seen with 10.12.0-rc.3

* enable the persistent version feature with `occ config:system:set file_storage.save_version_metadata --value true --type boolean`
* use texteditor to create a file, and do a few changes.
* click open details -> versions and click the checkmark. A persistent version 1.0 becomes 'published'
* edit some more changes with the texteditor
* click open details -> versions and click the checkmark. A persistent version 2.0 becomes 'published'
* edit some more changes with the texteditor
* run `occ versions:cleanup` - all persistent versions disappear. BAD

Expected behaviour:
* As documented in https://doc.owncloud.com/server/next/admin_manual/configuration/files/file_versioning.html#conscious-persistent-major-versions 
  `Major versions are persistent versions that are not subject to any retention policies set by ownCloud. Publishing the version persists it until the original file is deleted.`
* Versions:cleanup ist not the same as file deletion. The pesristent version should persist.
* (Or we should mention occ versions:cleanup as a way to remove peristent versions in the docs.)

**Comment by hodyroff** [comment]
"... is deleted by somebody with the permission or by the system administrator via occ versions:cleanup command."
For me it is correct that this commands deletes all versions. Its not a retention policy, it is a purposeful command.

**Comment by jnweiger** [comment]
Thanks!
Followup -> https://github.com/owncloud/docs-server/pull/899
