### ISSUE TITLE
X-Robots-Tag security check

### ISSUE THREAD

**Issue by rizlas** [owncloud/core#40713]
Hi, 
I'm running ownCloud (docker version) behind a proxy with a subpath configuration. I recently noticed that if I override the header X-Robots-Tag the security check fails.

Digging in the code I found this https://github.com/owncloud/core/blob/v10.12.0/core/js/setupchecks.js#L237

Currently the only accepted value for the robots tag is `none` but:

- duplicate headers are acceptable https://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable
- the value `none` is only used by Google. Check this https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name and https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers. 
- `X-Robots-Tag': 'noindex nofollow'`, should be considered as valid

As of today, if I want to add other values to x-robots-tag that would not be possible, without raising a false positive warning.

curl output of  https://my_beautiful_fqdn/owncloud

```
< x-robots-tag: none
< x-frame-options: SAMEORIGIN
< x-download-options: noopen
< x-permitted-cross-domain-policies: none
< location: /owncloud/
< strict-transport-security: max-age=15724800; includeSubDomains
< x-robots-tag: noindex, nofollow, nosnippet, noarchive
```

@osianderG (cc)

### Steps to reproduce

1. Specify another x-robots-tag header with value different from none in your proxy 
2. curl -vvvv https://your_beautiful_fqdn/owncloud (2 x-robots-tag headers are shown)

### Expected behaviour

No warning raised if `none` or `noindex+nofollow+<other custom values>` values are specified

### Actual behaviour

A warning is raised

### Server configuration

**ownCloud version:** 10.12.0

**Updated from an older ownCloud or fresh install:** updated from 10.11.0

**Where did you install ownCloud from:** docker official image

**Comment by IljaN** [comment]
Hi rizlas,

thanks for the issue and PR.

> I recently noticed that if I override the header X-Robots-Tag the security check fails.

Which security-check are you talking about exactly?

**Comment by rizlas** [comment]
Hi,
the security-check is shown in settings->Admin->General. 
![immagine](https://user-images.githubusercontent.com/8522635/229120404-62fe41a5-0ae5-4094-acf9-2c56b642cd43.png)

Currently I'm running ownCloud in kubernetes (under a subpath) and I'm adding this server snippet to the ingress.

`add_header  X-Robots-Tag "nofollow, noarchive";`

I need it for other resources that are running "behind" this ingress, but ownCloud does not like it :-)
Sending a curl to my ownCloud instance I spotted that the header is received twice. One from the ingress and one from the apache where ownCloud is running.

In this particular case if you print xhr response header (https://github.com/owncloud/core/blob/master/core/js/setupchecks.js#L248) you will read:

`none [from ownCloud], nofollow [from ingress], noarchive [from ingress]`

The code right now is only accepting `none` as a valid value. Bear in mind that `noindex, nofollow` are the same as passing the value `none`. Also `noindex, nofollow` values are valid for all search engines (check documentation links in my previous post).

Hope it clarifies both the issue and PR.
