### ISSUE TITLE
Directory / not found

### ISSUE THREAD

**Issue by jacksonhull** [owncloud/core#40723]
### Steps to reproduce
1.  Enable external storage and configure some folders
2.  Log in to OwnCloud.  See "Directory / not found", with no folders or files available to browse.
3.  Wait 10-15m, refresh Files and folders appear
This occurs every time after a server restart, and then sporadically.

### Expected behaviour
Logging in every time, configured folders should be available to browse.

### Actual behaviour
"Directory / not found" is shown.  
<img width="476" alt="Screenshot 2023-04-02 at 18 19 03" src="https://user-images.githubusercontent.com/931286/229608382-ea76867e-39f1-4d8f-bde0-8a9c0782e03d.png">

### Server configuration
**Operating system**:
Docker: owncloud/server:10.12

**ownCloud version:** (see ownCloud admin page)
10.12.0 (stable)

**Updated from an older ownCloud or fresh install:**
Fresh install

**Where did you install ownCloud from:**
Dockerhub

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No errors have been found.

**The content of config/config.php:**
https://gist.github.com/jacksonhull/83c085643127c19e634c26da778173cb

**List of activated apps:**
Admin Config Report 0.2.1
Deleted files 0.9.1
External storage support 0.9.0
Federation 0.1.0
Provisioning API 0.5.0
Share Files 0.14.0
Update notification 0.2.1
Versions 1.3.0
First run wizard 1.2.0
Market 0.7.0
Media Viewer 1.0.5
Notifications 0.5.4
ONLYOFFICE 7.8.1
PDF Viewer 1.0.1
Text Editor 2.5.1

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Chrome Version 111.0.5563.146

**Operating system:**
Mac Ventura 13.2.1 (22D68)

#### Web server error log
<img width="1116" alt="Screenshot 2023-04-02 at 18 25 04" src="https://user-images.githubusercontent.com/931286/229608226-231afb96-6dd5-49fc-a093-a37976e5f437.png">

#### ownCloud log (data/owncloud.log)
I am unable to locate this log in the docker container

#### Browser log
Console:
<img width="1023" alt="Screenshot 2023-04-02 at 18 19 15" src="https://user-images.githubusercontent.com/931286/229608335-9ed51f5f-74d7-4316-b1de-968a9020ba0d.png">

Screenshot of External Storage:
<img width="1425" alt="Screenshot 2023-04-02 at 18 21 55" src="https://user-images.githubusercontent.com/931286/229608423-f82c0f30-b178-4798-80da-ddc15dabab79.png">

thanks in advance!

**Comment by lubomben** [comment]
Same issue for me but also without the use of external storage.

Clean install with docker compose, only one user created... After 10-15 minutes admin can see files on web UI... normal user can not see files in web UI and "Directory / not found" message always appears on top.

At every refresh of admin user I can find this message in the logs:
`cloud_server   | 93.55.168.126 - - [14/Apr/2023:10:43:33 +0000] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 779 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
cloud_server   | 93.55.168.126 - - [14/Apr/2023:10:43:35 +0000] "GET /apps/files/?dir=/&fileid=3 HTTP/1.1" 303 981 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
cloud_server   | 93.55.168.126 - - [14/Apr/2023:10:43:35 +0000] "GET /apps/files/?dir=/ HTTP/1.1" 200 5729 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
cloud_server   | 93.55.168.126 - - [14/Apr/2023:10:43:35 +0000] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 779 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
cloud_server   | 93.55.168.126 - - [14/Apr/2023:10:43:35 +0000] "PROPFIND /remote.php/dav/files/admin/ HTTP/1.1" 207 2080 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
cloud_server   | 93.55.168.126 - - [14/Apr/2023:10:43:36 +0000] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" 200 810 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"`

Instead at every refresh od normal user I can see this in the logs:
`cloud_server   | 93.55.168.126 - - [14/Apr/2023:10:44:06 +0000] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 779 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
cloud_server   | 127.0.0.1 - - [14/Apr/2023:10:44:11 +0000] "GET /status.php HTTP/1.1" 200 1174 "-" "curl/7.68.0"
cloud_server   | 93.55.168.126 - - [14/Apr/2023:10:44:14 +0000] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 779 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0"
cloud_server   | 93.55.168.126 - - [14/Apr/2023:10:44:36 +0000] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 779 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
cloud_server   | 127.0.0.1 - - [14/Apr/2023:10:44:41 +0000] "GET /status.php HTTP/1.1" 200 1176 "-" "curl/7.68.0"
cloud_server   | 93.55.168.126 - - [14/Apr/2023:10:44:44 +0000] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 779 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0"
cloud_server   | 93.55.168.126 - - [14/Apr/2023:10:44:49 +0000] "GET /apps/files/ HTTP/1.1" 200 5665 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0"
cloud_server   | 93.55.168.126 - - [14/Apr/2023:10:44:50 +0000] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 779 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0"
cloud_server   | 93.55.168.126 - - [14/Apr/2023:10:44:50 +0000] "PROPFIND /remote.php/dav/files/null/ HTTP/1.1" 404 700 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0"
`

**Comment by jacksonhull** [comment]
Are you using a proxy?

**Comment by lubomben** [comment]
> Are you using a proxy?

Me no. owncloud is self hosted on a raspberry and the issue is present on internal LAN and also from external (Nginx Proxy Manager on front).

**Comment by Just-Danuse** [comment]
I have tried installing [files clipboard app](https://cloud.newtly.eu/apps/market/#/app/files_clipboard) and [ this theme](https://marketplace.owncloud.com/themes/theme-enterprise) and it seems to be working great now. Clean docker install - directory not found in web view, tho in desktop and mobile app it is working great. I think that theme fixed it, but I am not sure. As there are no errors in console and in containers, i suspect web interface for that.

**Comment by lubomben** [comment]
I resolved disabling "cache assets" in Nginx Proxy Manager for the ownCloud host.

**Comment by Just-Danuse** [comment]
Yikes, thanks. I also run OC behind npm, but I didn't think of that.

**Comment by jacksonhull** [comment]
That makes sense. I switched recently to Traefik which cleared it up.

Jackson

**Comment by lubomben** [comment]
For reference:

https://github.com/owncloud/core/issues/40541

**Comment by joshtheclipper** [comment]
> I resolved disabling "cache assets" in Nginx Proxy Manager for the ownCloud host.

Thanks, this helped me out!

**Comment by elliottparedes** [comment]
Thanks disabling cached assets worked for me too!

**Comment by misse** [comment]
> I resolved disabling "cache assets" in Nginx Proxy Manager for the ownCloud host.

Thank you, years of pain resolved.
