### ISSUE TITLE
[QA] allow javascript .map files in .htaccess

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#40734]
## Seen in 10.12.1 RC3 (and also 10.12.0)

* Setup server with index-php-less mode.
* Access the files view with chrome. Several '... is not valid JSON' errors are shown. BAD
![grafik](https://user-images.githubusercontent.com/1108546/231781340-09fcb1fa-6321-4382-b603-de1cb2121d57.png)
----
* Access the files view with firefox. A parse error is shown. BAD
![grafik](https://user-images.githubusercontent.com/1108546/231781834-ba00379e-ede4-4bc0-919f-85798d8eadd8.png)
----

### Expected behaviour
* The javascript map files are delivered correctly to the browser.
* No javascript errors are logged when accessing the files view.

**Comment by jnweiger** [comment]
Sidenote:

A minified js file is used to speed up loading, due to a substantially smaller size. But it seems to also cause loading of an additional map file, which can be quite large.
In the case of jquery.js the sizes are:
-rw-r--r-- 1 www-data www-data 247597 Apr  6 14:42 jquery.js
-rw-r--r-- 1 www-data www-data  84380 Apr 13 13:18 jquery.min.js
-rw-r--r-- 1 www-data www-data 127576 Apr  6 14:42 jquery.min.map

The sum of 127576 + 84380 = 211956 is only ca 16% smaller than the original jquery.js

**Comment by DeepDiver1975** [comment]
map files are only required during development - as long a you keep the dev tool closed they will not be loaded.

**Comment by jnweiger** [comment]
Ah, then this is far from a blocker for 10.12.1 - thanks!

**Comment by cdamken** [comment]
Done ;)
