### ISSUE TITLE
Package swiftmailer/swiftmailer is abandoned

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#40773]
```
composer install
...
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
...
```

I suppose we should change over some time.

**Comment by phil-davis** [comment]
Note: I started PR #40774 to see if it might be easy. But not so:
https://github.com/owncloud/core/pull/40774#issuecomment-1535989171

This can be prioritized and scheduled and assigned to someone when needed.

**Comment by cortho** [comment]
fyi: @enbrnz filed this issue in January https://github.com/owncloud/core/issues/40564
