### ISSUE TITLE
Php's `is_writable` function always returns `false` on NFS mounts

### ISSUE THREAD

**Issue by axelrindle** [owncloud/core#40810]
I opened the issue owncloud-docker/server#394 and tracked down the problem to be in the following piece of code:

https://github.com/owncloud/core/blob/12737e7a107101acffe9a4073dee9936b6566c3e/lib/private/legacy/util.php#L786-L797

The `is_writable` function seems to function improperly when operating on NFS mounts. Although the mount is writable by the executing user, Php falsely states that it is not writable. This has also been discussed in [this StackOverflow thread](https://stackoverflow.com/questions/50707811/php-is-writable-false-for-nfs-folder-although-files-can-be-written).

The problem already got address in NextCloud via nextcloud/server#13237. I hereby propose to merge those changes into the ownCloud core.

**Comment by phil-davis** [comment]
@axelrindle can you make a proposed PR to https://github.com/owncloud/core
