### ISSUE TITLE
PHP 7.4 is past end-of-life, yet 7.4 is the only version supported

### ISSUE THREAD

**Issue by posita** [owncloud/core#40811]
PHP 7.4 is unsupported as of Nov, 2022. See:

* https://www.php.net/eol.php
* https://www.php.net/supported-versions.php

But see: https://github.com/owncloud/core/blob/6aa97f6fb0348dacc8d1e41bdc142ba8dea78636/index.php#L30-L43

**Comment by DeepDiver1975** [comment]
https://central.owncloud.org/t/announcement-owncloud-10-and-php-versions/40251
