### ISSUE TITLE
Add max-height to sharing dialog

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/core#40872]
Add max-width to sharing dialog

### Expected behaviour
The dialog should give me a quick overview of the groups and people I can share with. 
It would be great to extend that to approx 6 items.

### Actual behaviour
The sharing dialog shows 2,5 items

<img width="341" alt="image" src="https://github.com/owncloud/core/assets/33026403/9b2baa19-ce99-461d-8cba-25521e0a0d37">

In some situations, there may be multiple options - I have to scroll in order to see them.

**Comment by steelcuts** [comment]
PR: https://github.com/owncloud/core/pull/40873
