### ISSUE TITLE
Saving Files in Microsoft Excel

### ISSUE THREAD

**Issue by LucasNoack** [owncloud/core#40870]
### Steps to reproduce
1. Create new Excel File
2. Try to open it

### Expected behaviour
The file should be editable because I just created it

### Actual behaviour
There is an error that says, that an other person is editing the file

### Server configuration
**Operating system**:
Ubuntu 20.04.6 LTS

**Web server:**
Apache/2.4.57 (Ubuntu)

**Database:**
10.11.4-MariaDB

**PHP version:**
PHP 7.4.33

**ownCloud version:** (see ownCloud admin page)
10.12.2.1

**Updated from an older ownCloud or fresh install:**
Updated from older version

**Where did you install ownCloud from:**
apt

**Signing status (ownCloud 9.0 and above):**
Free Version

**Login as admin user into your ownCloud and access **

No errors have been found.

**The content of config/config.php:**
{
    "system": {
        "updatechecker": false,
        "updater.server.url": "https:\/\/updates.owncloud.com\/server\/",
        "operation.mode": "single-instance",
        "instanceid": "oc2jjyw9e4lx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "217.160.6.210",
            "files.dfp-service.de"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/files.dfp-service.de\/owncloud",
        "dbtype": "mysql",
        "version": "10.12.2.1",
        "dbname": "ownCloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis-server.sock",
            "port": 0
        },
        "logtimezone": "Europe\/Berlin",
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "installed": true,
        "htaccess.RewriteBase": "\/owncloud",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "trashbin_retention_obligation": "auto, 20",
        "versions_retention_obligation": "auto, 20",
        "check_for_working_webdav": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "singleuser": false,
        "allow_user_to_change_mail_address": ""
    }
}

**List of activated apps:**

Enabled:
  - comments:
    - Version: 0.3.0
    - Path: /var/www/owncloud/apps/comments
  - configreport:
    - Version: 0.2.1
    - Path: /var/www/owncloud/apps/configreport
  - dav:
    - Version: 0.7.0
    - Path: /var/www/owncloud/apps/dav
  - encryption:
    - Version: 1.5.3
    - Path: /var/www/owncloud/apps/encryption
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /var/www/owncloud/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /var/www/owncloud/apps/federation
  - files:
    - Version: 1.5.2
    - Path: /var/www/owncloud/apps/files
  - files_external:
    - Version: 0.9.0
    - Path: /var/www/owncloud/apps/files_external
  - files_mediaviewer:
    - Version: 1.0.5
    - Path: /var/www/owncloud/apps/files_mediaviewer
  - files_sharing:
    - Version: 0.14.0
    - Path: /var/www/owncloud/apps/files_sharing
  - files_trashbin:
    - Version: 0.9.1
    - Path: /var/www/owncloud/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /var/www/owncloud/apps/files_versions
  - firstrunwizard:
    - Version: 1.2.0
    - Path: /var/www/owncloud/apps/firstrunwizard
  - notifications:
    - Version: 0.5.4
    - Path: /var/www/owncloud/apps/notifications
  - provisioning_api:
    - Version: 0.5.0
    - Path: /var/www/owncloud/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /var/www/owncloud/apps/systemtags
  - updatenotification:
    - Version: 0.2.1
    - Path: /var/www/owncloud/apps/updatenotification

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Webdav

### Client configuration
**Browser:**

**Operating system:**
Windows

**Comment by JayAige** [comment]
I'm facing the same issue. Since last week, Microsoft Office programs (tested with PowerPoint, Word and Excel) produce an error while saving a file via WebDAV. It seems like the UNLOCK command ist not properly send or processed. Here is what we tested so far:
- Open a file: File is locked like expected (verified by webinterface)
- Close the file without editing/saving: File is unlocked like expected
- Open a file, edit and save: File is locked as expected
- Close the edited file: File stays locked (not expected) for approx. 30 min

This error greatly affects our workflow, as we have to manually unlock each file. Is there a way to disable file locking via WebDAV temporarly until this error is fixed?

**Comment by jaeger-sb** [comment]
I can confirm the issue as well! In a previous minor release it worked!
