### ISSUE TITLE
owncloud/server image config.php `trusted_domains` is not working

### ISSUE THREAD

**Issue by joriewong** [owncloud/core#40884]
### Steps to reproduce
1. pull owncloud/server:latest
2. `docker run --rm --name oc-eval -d -p8080:8080 owncloud/server`
3. `'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 'ip:8080'
  ),`
5. visit ip:8080

### Expected behaviour

trusted

### Actual behaviour

You are accessing the server through an untrusted domain.
Please contact your administrator. If you are an administrator of this instance, configure the "trusted_domains" setting in config/config.php. An example configuration is provided in config/config.sample.php or at the [documentation](https://doc.owncloud.com/server/10.12/go.php?to=admin-untrusted-domain).

### Server configuration
**Operating system**: centos 7

**Comment by DeepDiver1975** [comment]
https://central.owncloud.org/t/docker-compose-multiple-trusted-domains-issue/39659/2

**Comment by joriewong** [comment]
https://github.com/owncloud/ocis/issues/6684#issuecomment-1641307754

**Comment by DeepDiver1975** [comment]
please use central.owncloud.org for community support. the issue tracker is for real bugs and feature requests. THX
