### ISSUE TITLE
setting volume "/mnt/data" to path on host throws error "environment not properly prepared" on docker

### ISSUE THREAD

**Issue by IveMalfunctioned** [owncloud/core#40903]
windows server 2019 x64
ownCloud version latest
docker version 20.10.14
php 7.4.3
fresh install

--> 
### Steps to reproduce
1. docker pull owncloud/server
2. run image with volume /mnt/data set to something like F:\ownCloud
3. see that it does not work

### Expected behaviour
it should run no problem

### Actual behaviour
bunch of random errors
https://gist.github.com/IveMalfunctioned/c4a6052c42dfbf2875222586404194d5

I used ownCloud about 7 months ago (on a separate capable PC) just to figure out setting it up, but I didn't have capable server hardware to run it on. Now I do and I'm trying to set it up again but it's not working. I am using the exact same container settings to run it as I did and there's now all these errors. what do I need to do to fix it

**Comment by IveMalfunctioned** [comment]
thanks for nothing guys

**Comment by DeepDiver1975** [comment]
I guess the Chmod Operation is not working on a windows filesystem.

I have never seen a setup like this and knowing the internals I strongly advise not to use a windows host system.

**Comment by IveMalfunctioned** [comment]
> I guess the Chmod Operation is not working on a windows filesystem.
> 
> I have never seen a setup like this and knowing the internals I strongly advise not to use a windows host system.

I never had this issue when I used it with the exact same settings on my PC before I got my server. Maybe it has something to do with WSL not being installed yet?

**Comment by IveMalfunctioned** [comment]
When I was running it, it was able to be accessed at the path
\\wsl$\docker-desktop-data\data\docker\volumes\0ca5c22aa5db974bc855a0e6d58d3c2c320ed13f257d976aa0e6f1f80290ef95\_data\files\admin\files
which was able to be mounted to my external drive. How can I replicate this

**Comment by DeepDiver1975** [comment]
Please head over to https://central.owncloud.org/ for community help! THX

**Comment by IveMalfunctioned** [comment]
No Thomas cause it's not completed
