### ISSUE TITLE
[FEATURE REQUEST] Full office integration into owncloud server

### ISSUE THREAD

**Issue by nemethstarproductions** [owncloud/core#40908]
Hello,

sorry for using the "bug report" for this but it was not possible to place a feature request in the "oc core" section.

It would be great to see a full integration of OnlyOffice in the owncloud community server core, without the need of an "document server"- plugin and an external hosted OnlyOffice instance.
I know it is requested since long time but i believe this would make the community server edition much better. It would also close the gap to other products and will be able users and admins - without the chance to easily switch to Infinitie Scale - with an easy usable online office solution. I hope this will one day be considered by owncloud and the developers who have the skills to make this possible.

**Comment by DeepDiver1975** [comment]
Office solutions have quite a complexity and we will not implement this on our own from scratch.

This is why we partner with projects like only office and collabora to bring this to the ownCloud community.

Just use what is there. 💪

**Comment by nemethstarproductions** [comment]
I can understand this. From a perspective of an all-in-one soluction to host on a shared webhosting and if you want to have the control about everything and not use a 3rd party server as document server, then it's a serious problem. This is also the reason of my post.

**Comment by DeepDiver1975** [comment]
> From a perspective of an all-in-one soluction to host on a shared webhosting

see https://owncloud.online/ - it is possible to build an all-in-one solution. :shrug:
