### ISSUE TITLE
Removed from owncloud GitHub Organization

### ISSUE THREAD

**Issue by Spacefish** [owncloud/core#40928]
GitHub automatically removed me from the owncloud Organization.. Can someone re-add me? I have two-factor enabled now.

![image](https://github.com/owncloud/core/assets/375633/dcb73532-ca51-4c3d-90ea-6906319cbf81)

**Comment by DeepDiver1975** [comment]
What did you contribute in the past times? In case you want to contribute you can still do this from a repo fork.
