### ISSUE TITLE
Upload via webdav does not check for quota?

### ISSUE THREAD

**Issue by dschkomm-one** [owncloud/core#40921]
### Steps to reproduce
1.  Give a user a Quota of ex. 1 GB
2.  Upload a file of (in this case 14,6 GB) over webdav (here: Owncloud Android App) 
3.  The File gets uploaded, in my case multiple time. In total 90 GB was uploaded in 15 tries to ./<user>/uploads

### Expected behaviour
The Server should check for uploaded filesize and end connection over quota

### Actual behaviour
It got reuploaded multiple time

### Server configuration
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"

**Web server:**
Package: apache2
Version: 2.4.56-1~deb11u2

**Database:**
Package: mariadb-server
Version: 1:10.5.19-0+deb11u2

**PHP version:**
Package: mariadb-server
Version: 1:10.5.19-0+deb11u2

**ownCloud version:** (see ownCloud admin page)
10.12.2

**Updated from an older ownCloud or fresh install:**
For updates I move the Folder away and use a new one from the zip File.

**Where did you install ownCloud from:**
Owncloud Website

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by michaelstingl** [comment]
> * Upload a file of (in this case 14,6 GB) over webdav (here: Owncloud Android App)

ownCloud Android app tries a plain `PUT` with the `14,6 GB` file. For ownCloud Infinite Scale, TUS upload is planned. Could be improved there…

AFAIK HTTP1.1 spec requires to accept the full body, and not kill it before.

Sending a request before every upload to check quota would result in poor overall performance.

Clients retry, because they assume quota issue could be resolved in the meantime. Desktop app retries with increasing delays (up to 24h)

**Comment by dschkomm-one** [comment]
Thanks for the feedback.
