### ISSUE TITLE
Files with an extension without a name are not synchronized

### ISSUE THREAD

**Issue by VeyDlin** [owncloud/core#40936]
Version ownCloud 10.12.2 

Any files that do not have a name are not displayed in the web interface and in the interface of the android application

I still have them in folder on the server

But they also don't sync to other computers

How to reproduce the bug? Just create a file without a name, for example:
.gitignore, .editorconfig, .txt, .test

**Comment by DeepDiver1975** [comment]
these are hidden files in the linux world - look for options to display hidden files.
