### ISSUE TITLE
[QA] skeleton files are added as corrupt files, when the user was created with 0 B quota

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#40931]
Seen in 10.13.0-rc.1 (probably not a regression)

* admin creates user Marie with 0b quota. E.g. this user should only work in received shares.
* when user Marie logs in for the first time all the skeleton folders and files appear. BAD
* Each of these files is corrupt. 0 Bytes. BAD
![image](https://github.com/owncloud/core/assets/1108546/975b0804-b71b-46aa-b409-bdf1eb4acd06)

Expected behavior:
* The skeleton creation process checks for errors during copying and either produces a correct file, or no file.

**Comment by pako81** [comment]
Known issue. Related to https://github.com/owncloud/core/pull/40567
