### ISSUE TITLE
"/usr/bin/occ : Illegal instruction" from v10.11 and higher

### ISSUE THREAD

**Issue by simondubrulle** [owncloud/core#40933]
### Steps to reproduce
1. Following command works as expected (for version 10.10) :
```
docker run --rm --entrypoint "/usr/bin/occ" owncloud/server:10.10
```
It returns normal output:
```
ownCloud is not installed - only a limited number of commands are available
ownCloud 10.10.0

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
[... skipping as not important]
```
2. Same command but using version '10.11' (will do the same with '10.12' or even '10.13.0-rc.1')

```
docker run --rm --entrypoint "/usr/bin/occ" owncloud/server:10.11
```

returns error:

```
/usr/bin/occ: line 16:    15 Illegal instruction     (core dumped) setpriv --reuid=www-data --regid=www-data --init-groups php /var/www/owncloud/occ "$@"
```
4.

### Expected behaviour
The basic Docker run command for v10.11+ should return occ help/usage.
### Actual behaviour
It returns an illegal instruction. Actually preventing me from running Owncloud via docker for versions higher than 10.10.

### Server configuration
**Operating system**:
```
$ cat /etc/os-release

PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
```
$ uname -a

Linux toshiba-pc 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ docker -v

Docker version 24.0.5, build ced0996
```

```
$ cat /proc/cpuinfo

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 58
model name      : Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
stepping        : 9
microcode       : 0x21
cpu MHz         : 1200.000
cache size      : 6144 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
vmx flags       : vnmi preemption_timer invvpid ept_x_only flexpriority tsc_offset vtpr mtf vapic ept vpid unrestricted_guest
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds mmio_unknown
bogomips        : 4788.99
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

[... same for other cores]
```

**Web server:**

Not sure how to retrieve that information.

**Database:**

Default (sqlite)

**PHP version:**

7.4 (I can see it by listing /usr/bin/) but I noticed that running `php -v` on 10.11 version I get empty response:

```
$ docker run --rm --entrypoint "php" owncloud/server:10.11 "-v"


```

While running it on 10.10 version gives normal output :
```
$ docker run --rm --entrypoint "php" owncloud/server:10.10 "-v"

PHP 7.4.3-4ubuntu2.18 (cli) (built: Feb 23 2023 12:43:23) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3-4ubuntu2.18, Copyright (c), by Zend Technologies
```

**ownCloud version:** (see ownCloud admin page)

Version 10.11 and higher

**Updated from an older ownCloud or fresh install:**

Fresh install

**Where did you install ownCloud from:**

Docker Hub image.

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
Cannot acces it.

**The content of config/config.php:**

Default from Docker image.

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

Default from Docker image.

**Are you using external storage, if yes which one:** local/smb/sftp/...

No.

**Are you using encryption:** yes/no

No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:**
N/A

**Operating system:**
N/A

#### Web server error log

/
#### ownCloud log (data/owncloud.log)

No log file created.

#### Browser log
/

**Comment by simondubrulle** [comment]
To me it seems like my CPU cannot understand a new cpu instruction. It might be this is coming from the PHP build (which is also php7.4). But I am pulling the amd64 image of Owncloud and I am not expecting new cpu instruction (should I?).

Changelog of v10.11 states : `Change - Update PHP dependencies: [#39368](https://github.com/owncloud/core/pull/39368)`. Can this be related to these dependencies?

**Comment by noc-noc** [comment]
Same here. After update, I get
```
Fixing base perms...
Fixing data perms...
Fixing hook perms...
/usr/bin/occ: line 16:    68 Illegal instruction     setpriv --reuid=www-data --regid=www-data --init-groups php /var/www/owncloud/occ "$@"
Upgrading server database...
/usr/bin/occ: line 16:    75 Illegal instruction     setpriv --reuid=www-data --regid=www-data --init-groups php /var/www/owncloud/occ "$@"
```

I tried to start 10.12.1, but got `OC\HintException: [0]: Downgrading is not supported and is likely to cause unpredictable issues (from 10.12.2.1 to 10.12.1.3) ()`.
So I am currently stuck with a broken owncloud installation, probably have to try and rollback to a backup.

**Comment by simondubrulle** [comment]
> Same here. After update, I get
> 
> ```
> Fixing base perms...
> Fixing data perms...
> Fixing hook perms...
> /usr/bin/occ: line 16:    68 Illegal instruction     setpriv --reuid=www-data --regid=www-data --init-groups php /var/www/owncloud/occ "$@"
> Upgrading server database...
> /usr/bin/occ: line 16:    75 Illegal instruction     setpriv --reuid=www-data --regid=www-data --init-groups php /var/www/owncloud/occ "$@"
> ```
> 
> I tried to start 10.12.1, but got `OC\HintException: [0]: Downgrading is not supported and is likely to cause unpredictable issues (from 10.12.2.1 to 10.12.1.3) ()`. So I am currently stuck with a broken owncloud installation, probably have to try and rollback to a backup.

I was able to fix it (temporarily) by rebuilding a custom image and forcing some updates :

```
FROM owncloud/server:10.12

RUN apt update -y && \
  apt install -y software-properties-common && \
  add-apt-repository ppa:ondrej/php -y && \
  apt install -o Dpkg::Options::="--force-confold" --force-yes -y php7.4 php7.4-intl php7.4-mysql php7.4-mbstring \
       php7.4-imagick php7.4-igbinary php7.4-gmp php7.4-bcmath \
       php7.4-curl php7.4-gd php7.4-zip php7.4-imap php7.4-ldap \
       php7.4-bz2 php7.4-ssh2 php7.4-common php7.4-json \
       php7.4-xml php7.4-dev php7.4-apcu php7.4-redis \
       libsmbclient-dev php-pear php-phpseclib && \
  ln -fs /usr/bin/php7.4 /usr/bin/php
```
Let me know if you need some help.

**Comment by noc-noc** [comment]
> Let me know if you need some help.

Thanks a lot for the offer. Just noticed issue https://github.com/owncloud/core/issues/40929 where a different workaround was mentioned. Will give that a try and otherwise create my own image following your approach.

**Comment by jnweiger** [comment]
I cannot reproduce this on any of the Intel x86_64 CPUs I have available. 
As for the missing php output on your 10.11 docker, I assume php also crashes with illegal instruction for you. In my case, it happily reports:
`docker run --rm --entrypoint "php" owncloud/server:10.11 "-v"`
```
PHP 7.4.3-4ubuntu2.19 (cli) (built: Jun 27 2023 15:49:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3-4ubuntu2.19, Copyright (c), by Zend Technologies
```

I see little chance to diagnose the cause witout having an affected CPU.
Maybe we learn something by running php under gdb. If one of you can post the output of 
`docker run --rm -ti owncloud/server:10.11 bash -c "apt update -y; apt install -y gdb; gdb php -ex 'run -v'"`

In my case gdb just happily runs php -v, that is the boring output:
```
Reading symbols from php...
(No debugging symbols found in php)
Starting program: /usr/bin/php -v
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
PHP 7.4.3-4ubuntu2.19 (cli) (built: Jun 27 2023 15:49:59) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3-4ubuntu2.19, Copyright (c), by Zend Technologies
[Inferior 1 (process 345) exited normally]
(gdb) 
```

**Comment by jnweiger** [comment]
#40929 has great hints for dignosing this, and the correct workaound `phpdismod imagick`
