### ISSUE TITLE
New default minimum supported client version breaks owncloudcmd on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by beyondwatts** [owncloud/core#40949]
Minimum client updated from 2.3.3 to 3.2.1 according to release notes
https://owncloud.com/news/owncloud-server-10-13/#Default_Minimum_Supported_Desktop_Client_Version

### Steps to reproduce
1. Attempt to connect to an owncloud 10.13 server using owncloudcmd on Ubuntu 22.04 LTS

### Expected behaviour
- Files should synchronise

### Actual behaviour
- User appears to authenticate ok "[ info sync.networkjob.jsonapi ]:    JsonApiJob of QUrl("https://REMOVED/ocs/v1.php/cloud/user?format=json") FINISHED WITH STATUS "OK""
- owncloudcmd reports "[ warning sync.networkjob ]: QNetworkReply::ContentAccessDenied "Server replied \"403 Forbidden\""
- sync fails

Note: windows desktop client and browser access works ok

### Server configuration
Docker Image
owncloud/server:10.13.0

### Client configuration
owncloudcmd on Ubuntu 22.04 LTS
```
# owncloudcmd -v
ownCloud version 2.6.3
Git revision f28dd972e941986edc3e1803a25cf067f520b7e3
Using Qt 5.15.3, built against Qt 5.15.2
Using 'OpenSSL 3.0.2 15 Mar 2022'
```

### Workaround
Override OWNCLOUD_MINIMUM_SUPPORTED_DESKTOP_VERSION environment variable
```
  - name: OWNCLOUD_MINIMUM_SUPPORTED_DESKTOP_VERSION
  value: "2.3.3"
```

**Comment by DeepDiver1975** [comment]
Please head over to https://central.owncloud.org/ for community help! THX

**Comment by lupus0802** [comment]
I don't quite get why this is closed as being a support request - with the new minimum client version, owncloudcmd will break for all instances except for the few ones who actually set that version number back (making the change unnecessary in the first place). Perhaps make an exemption for the command line (as the newest version "still" is 2.6.3) - just bumping the version number doesn't seem to be efficient.

**Comment by DeepDiver1975** [comment]
If you set the minimum desktop client version to 3.2.1 it is expected that clients with a lower version cannot connect. 
Please get the latest version from https://owncloud.com/desktop-app/

**Comment by beyondwatts** [comment]
As mentioned in the original post, the owncloud package sets the minimum client version to a default that is incompatible with the owncloud client included with Ubuntu 22.04 LTS.

**Comment by lupus0802** [comment]
> If you set the minimum desktop client version to 3.2.1 it is expected that clients with a lower version cannot connect. 
> 
> Please get the latest version from https://owncloud.com/desktop-app/

That may be, but then please also publish a usable Linux version within the Ubuntu default repositories or mark it as deprecated.

**Comment by lupus0802** [comment]
@beyondwatts You can alternatively get the version 4.2.0 for Linux which includes the command client here https://attic.owncloud.com/desktop/ownCloud/stable/latest/linux/download/
Make sure to remove the other versions of owncloud first.

**Comment by iasdeoupxe** [comment]
> but then please also publish a usable Linux version within the Ubuntu default repositories or mark it as deprecated.

AFAICT these packages are not maintained by them (the ownCloud team) and out of their reach.
