### ISSUE TITLE
SMB(SAMBA) Collabortive Account and Code

### ISSUE THREAD

**Issue by kenrmayfield** [owncloud/core#40948]
@DeepDiver1975 
@phil-davis 

 I installed smbclient on CentOS 8 Stream and SMB Personal worked with my Shares.

For the SMB Collabortive do you have too Purchase a License since it is asking for a Account and Code?

I was trying to find the Cost but had no luck.

**Comment by DeepDiver1975** [comment]
https://owncloud.com/pricing

**Comment by kenrmayfield** [comment]
@DeepDiver1975 

So with SMB Collaborative you have to have a Account and Code Setup.....Right?
