### ISSUE TITLE
[QA] AppRegistry loads icons from 3rd party URLs

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#40953]
Seen in https://github.com/owncloud/core/blame/v10.13.0/core/Controller/AppRegistryController.php#L71-L86

I don't have steps to reproduce, currently. Sorry.

### Expected behaviour

* Icons should be provided by owncloud core

### Actual behaviour
* Icons are loaded from 
  - https://www.collaboraoffice.com/wp-content/uploads/2019/01/CP-icon.png
  - https://www.pikpng.com/pngl/m/343-3435764_onlyoffice-desktop-editors-onlyoffice-logo-clipart.png
  - https://avatars.githubusercontent.com/u/1769238?s=200&v=4

The pikpng URL currently has an expired cert. (Sun, 09 Jul 2023 08:23:50 GMT)

Icons downloaded and added here for reference.
![1769238](https://github.com/owncloud/core/assets/1108546/ad579f2a-3145-4b26-be4b-476ab8198acd)
![343-3435764_onlyoffice-desktop-editors-onlyoffice-logo-clipart](https://github.com/owncloud/core/assets/1108546/72f8d5fd-0df6-4419-b5a6-f348b66047b5)
![CP-icon](https://github.com/owncloud/core/assets/1108546/5c58d650-4460-46cc-b677-71fca0cde425)

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by michaelstingl** [comment]
Results in an ugly error in the iOS app with `demo.owncloud.com`

![Simulator Screenshot - iPhone SE (3rd generation, iOS 16 4) - 2023-08-28 at 18 17 38](https://github.com/owncloud/core/assets/214010/f4b6efe3-9d7d-4f1a-81dd-b8d44e7818ea) | ![Simulator Screenshot - iPhone SE (3rd generation, iOS 16 4) - 2023-08-28 at 18 18 13](https://github.com/owncloud/core/assets/214010/4e15a9cb-4f92-46a5-aab4-8e804c97f01f)
-- | --

```
ownCloud release version 12.0.3 build 271 (Mon Aug 28 18:12:23 CEST 2023)
(app: c12.0.2-53-ga455ce1d - milestone/12.0.3@a455ce1d, sdk: v12.0.2-20-g112bb23 - @112bb23)
```

@xoxys @TheRealBro deploy a patch?

**Comment by xoxys** [comment]
We dont deploy manual patches.

**Comment by DeepDiver1975** [comment]
We anyway have no patch at hand .....

**Comment by tbsbdr** [comment]
PB1
- fix should be provided via a patch release
