### ISSUE TITLE
unit tests on windows SMB server do not run

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#40979]
For example: https://drone.owncloud.com/owncloud/core/39055/23/7

The Windows Server that is the backing store for this core unit test pipeline is no available.

Can it be made available again please?

Otherwise, what to do - remove that test pipeline from CI?

**Comment by phil-davis** [comment]
@jnweiger I raised this issue so that the problem with this CI pipeline is documented.
What can be done in the near future?

**Comment by jnweiger** [comment]
Should be fixed again. wnd.testlab.owncloud.works was offline. It is back.
