### ISSUE TITLE
External Storage：webdav can not support Thumbnail ?? 

### ISSUE THREAD

**Issue by xujiehehe** [owncloud/core#40989]
I installed OwnCloud using the Docker method, and the version used is owncloud/server: 10.12. I have inserted an external hard drive on my machine and deployed the webdav service using the webdav Docker. The version used is ugeek/webdav: arm64. On the settings page of owncloud, it is set to enable external storage and preview is enabled. I uploaded image files to this directory through the UI, but I was unable to generate a preview image.

system state：
Installed 1
Maintenance
NeedsDbUpgrade
Version 10.12.1.3
Versionstring 10.12.1
Editing Community
Productname ownCloud
Product ownCloud
Hostname 056e7cda47c8

Docker Running：
```
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
056e7cda47c8 owncloud/server:10.12 "/usr/bin/entrypoint…" 14 hours ago Up 54 minutes 0.0.0.0:6081->8080/tcp, :::6081->8080/tcp owncloud
d0953e3ab767 ugeek/webdav:arm64 "/bin/sh -c '/entryp…" 2 weeks ago Up 54 minutes 0.0.0.0:20000->80/tcp, :::20000->80/tcp e0cc60bd-c10c-4dab-b2be-5781f6cd4140
```
Settings page ：
![269146164-936193c1-fe27-437e-a396-4c79f199a8a9](https://github.com/owncloud/core/assets/5696783/8f83919b-5af2-47a5-841f-b7e834edb0b3)

Upload File Page：(This page cannot preview images. Does owncloud not support generating image thumbnails in this way? I have also installed nextcloud, and this feature is fine)
![269146266-11f11d50-7646-4446-b41a-c867e7225670](https://github.com/owncloud/core/assets/5696783/7e161e76-4f0e-405b-a89a-285916642812)

Additional information：
Generate Config Report：
[config_report_20230920.log](https://github.com/owncloud/core/files/12679421/config_report_20230920.log)

**Comment by cdamken** [comment]
Hi @xujiehehe, is it possible for you to provide the log files?

**Comment by xujiehehe** [comment]
Thank you, this is my operation log.
[owncloud.log](https://github.com/owncloud/core/files/12837008/owncloud.log)

**Comment by IljaN** [comment]
@pako81 @cdamken @ValentinKruegl Take another look at the reproduction, sometimes it works and sometimes it doesn't?

**Comment by jvillafanez** [comment]
It might be a problem with your webdav service.
As far as I know, these are the webdav properties requested:
```
'{DAV:}getlastmodified',
'{DAV:}getcontentlength',
'{DAV:}getcontenttype',
'{http://owncloud.org/ns}permissions',
'{http://open-collaboration-services.org/ns}share-permissions',
'{DAV:}resourcetype',
'{DAV:}getetag',
```
In particular the `'{DAV:}getcontenttype',` is the one used for the mime type. That property doesn't seem to be returned by your webdav server.
Since we don't know the mime type of the file (as said, the webdav server isn't returning it), we consider the content type to be a generic "octet-stream", and ownCloud doesn't generate thumbnails for that content type (it could be an .exe file or a .zip file, or an .iso)

I don't know if it's possible to configure your webdav server in order to return that property. Otherwise you could try a different webdav server.
Note that you can check with the ownCloud's demo server to prove that the thumbnails work with webdav.

**Comment by xujiehehe** [comment]
@jvillafanez Thank you very much. Please help recommend a webdav server, preferably one that can be installed using Docker。

**Comment by cdamken** [comment]
After a lot of testing, the thumbnails are shown, sometimes slow depending on where is the storage and the performance.

Tested with version 10.11.X , 10.12.X and 10.13.X

**Comment by jvillafanez** [comment]
I can't recommend any server. I've just quickly checked https://hub.docker.com/r/bytemark/webdav/ and it seems to work fine, but I don't know anything else about it.

In any case, the goal of the external storage app is to bring data to ownCloud from external sources, which means the data is already there and you need to get it using any protocol available.
The only use case where you might use external out of the main use case is to increase the overall storage capacity if you can't increase the size of your primary storage, and if this is the case you could use any other protocol that ownCloud supports.
