### ISSUE TITLE
Attendies won't recieve email CalDAV notification upon creating an event on calendar made by different user.

### ISSUE THREAD

**Issue by lubomirblazekcz** [owncloud/core#40982]
### Steps to reproduce
1. Create an event on calendar shared by different user.
2. Add attendies emails, and create event.
3. Attendies won't recieve CalDAV invite, if the event is created on same user calendar it works

note: upon deleting the event, notification is recieved correctly

### Expected behaviour
Tell us what should happen

CalDAV invite should be sent

### Actual behaviour
Tell us what happens instead

CalDAV invite is not sent

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4

**ownCloud version:** (see ownCloud admin page) 10.13.0

**Updated from an older ownCloud or fresh install:** older

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
```
No errors have been found.

**The content of config/config.php:**
https://gist.github.com/lubomirblazekcz/ed9653fcd2a8b593f8c2a2f5efde658f

**List of activated apps:**

calendar

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

**Comment by DeepDiver1975** [comment]
> 1. Create an event on calendar shared by different user.

calendar sharing and invitations don't work together properly. Best is to either use shared calendars or work with invites.

**Comment by lubomirblazekcz** [comment]
That's unfortunate as we use shared calendars for company wide events, but no one is being notified when an event is added with attendies, which clearly is a bug and should be addressed.

**Comment by lubomirblazekcz** [comment]
Maybe at least adding an info that the attendees can't be notified on a shared event? That only attendies added by calendar owner will be notified? Now it's really unclear when the notification works and when not.

Somewhere here:
![obrazek](https://github.com/owncloud/core/assets/6872956/97031b77-6c3b-420a-8d2e-849c150c7caa)
