### ISSUE TITLE
'make install-composer-deps' can run into a deadlock

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#41011]
Originally only wanted to run the php-style fixer, I wanted to update the dependencies to be up to date.

Running `make install-composer-deps` to update dependencies complains in my environment about missing php extensions (correct, I dont need them, I have not installed them therefore): 
```
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - Root composer.json requires PHP extension ext-apcu * but it is missing from your system. Install or enable PHP's apcu extension.
  Problem 2
    - Root composer.json requires PHP extension ext-memcached * but it is missing from your system. Install or enable PHP's memcached extension.
```
The solution printed:
```
Alternatively, you can run Composer with `--ignore-platform-req=ext-apcu --ignore-platform-req=ext-memcached` to temporarily ignore these required extensions.
```
And added as parameter:
`make install-composer-deps --ignore-platform-req=ext-apcu --ignore-platform-req=ext-memcached`
will then print:
```
make: unrecognized option '--ignore-platform-req=ext-apcu'
make: unrecognized option '--ignore-platform-req=ext-memcached'
```

This is now a kind of deadlock in updating dependencies and needs a fix.

@phil-davis @pako81

**Comment by DeepDiver1975** [comment]
We recently added some more php extensions to composer.json. You have to install these.

**Comment by mmattel** [comment]
I need to install apcu and memcached just for updating dependencies to run php-style-fix?? really?? 🤦‍♂️

**Comment by DeepDiver1975** [comment]
You can run fixer stand alone as well. But if you run composer install you better meet the requirements of the project.

You could also ask why-do-i-need-ext-foo ...... 🤷

**Comment by mmattel** [comment]
With support of @DeepDiver1975 the solution was after installing the dependencies (I never use) to run `make clean`.

As suggestion, when running `make install-composer-deps` why not running the `clean` process upfront automatically?

**Comment by DeepDiver1975** [comment]
Under normal circumstances make clean is not required. I run make clean when necessary..... one. In two months or so.

It is necessary when things are too outdated on your local installation.

**Comment by mmattel** [comment]
> It is necessary when things are too outdated on your local installation.

Fully agree, but to ease this for those who are not hard core devs as you are (😅), an automatically clean as part of the install would be quite useful and reduces times finding errors...

**Comment by DeepDiver1975** [comment]
let's keep this simple - the make file is working in this way since the past 8+ years - and it was never a problem. I see no need in any change
