### ISSUE TITLE
docker cannot work with Nginx

### ISSUE THREAD

**Issue by NickLin910221** [owncloud/core#41043]
I have built owncloud with docker.
![telegram-cloud-photo-size-5-6132065018162822006-x](https://github.com/owncloud/core/assets/39323130/0295fe01-1584-4c5e-ad0e-e5d27b1687f3)
And expose the 3333 port for the owncloud.
I can access the backend with http:/{host_ip}:3333
But when I using Nginx for proxy service.
I cannot access the owncloud backend.

When I went into Nginx docker to test about network
![telegram-cloud-photo-size-5-6132065018162822011-x](https://github.com/owncloud/core/assets/39323130/580f4d58-9d64-4ef5-a2d6-d5d8ce842966)
I can ping the owncloud-server and 8080 port, but cannot telnet 3333 port.

The following image is about my docker network inspect.
![telegram-cloud-photo-size-5-6132065018162822012-x](https://github.com/owncloud/core/assets/39323130/7cf743dd-d2c1-4a7a-84b1-3d8b3d502b53)

**Comment by DeepDiver1975** [comment]
Not really related to owncloud. More a question for the docker community. Closing this here.
