### ISSUE TITLE
PDF Preview only shows last section of pdf

### ISSUE THREAD

**Issue by ZeeSarp** [owncloud/core#41042]
Hi!
I enabled the PDF preview provider.
That did work, however, the thumbnail images generated for documents with multiple pages are not as expected.
I tried to fix this in /var/www/owncloud/lib/private/Preview/Bitmap.php, but I can't get it to work as I don't fully understand imagick and how it works with pdfs when using stream handles.
Is there an easy fix I could apply?
Every Idea is very appreaciated!

### Steps to reproduce
1. Enable PDF Preview
2. Upload a PDF File with more than 2 pages
3. Open file detail view

### Expected behaviour
My expectation was, that the very first page would be used to generate the preview like when the document only has one page.

### Actual behaviour
When a preview for a PDF with 2 or more pages is generated, the thumbnail only shows the last visible portion of the bottom most page instead of the upmost part of the first page.

### Server configuration
**Operating system**:
Debian 10

**Web server:**
Included in docker image, don't know

**Database:**
MariaDB10.6
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
10.12.2 
**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
dockerhub

**Comment by DeepDiver1975** [comment]
@ZeeSarp see the pull request above ...

**Comment by ZeeSarp** [comment]
@DeepDiver1975 
Wow, thank you so much for the quick fix!
What confuses me a bit is that the change you made in Bitmap.php was the first thing i tried, when trying to fix it myself, but the generated image was simply blank.
Will try again today as soon as possible.
Did you notice anything similar in your tests at any time?

**Comment by ZeeSarp** [comment]
@DeepDiver1975 just tested it by modifying the Bitmap.php in the running docker container, uploaded a new PDF with multiple pages and let owncloud generate a new preview.
Still the same behavior, the preview only shows the bottommost part.
A restart of the container does not seem to resolve the issue.
Is there anything besides the Bitmap.php that I need to adjust?

**Comment by DeepDiver1975** [comment]
You need to restart the apache server once code was changed. In a docker environment you need to restart the docker container - but you might loose the changes on disk depending on the setup. I am not too deep into the oc docker images and cannot tell right away if restarting will keep the changes or not ....

**Comment by ZeeSarp** [comment]
@DeepDiver1975 
Just restarted the container made sure that the changes in Bitmap.php still persist and generated some new PDF-Previews.
Unfortunately still got the same issue.
Have you tried this locally?

**Comment by jnweiger** [comment]
Confirmed fixed in 10.14.0-rc.1
