### ISSUE TITLE
Upgrade from 10.13.1.3 to 10.13.2 fails.

### ISSUE THREAD

**Issue by sfadschm** [owncloud/core#41057]
### Steps to reproduce
1. Run update via _/.../updater/application.php_
2. Error: _upgrade:backupDBlb command is not implemented_
3. Updater exits.

1. Run update via webUI admin panel.
2. Update is successfull, but aborts with error: _upgrade:restartWebServer command is not implemented_.
3. UI is stuck and upgrade appears to not be finished.
4. Actually, update was successful.

### Expected behaviour
The upgrade runs smoothly...

### Actual behaviour
The upgrade fails at the first step or is successfull but shows an error.

### Server configuration
**Operating system**: Ubuntu 20.04.6 LTS

**Web server:** Apache

**Database:**

**PHP version:** 

**ownCloud version:** 10.13.1.3

**Updated from an older ownCloud or fresh install:** Updated.

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

**Comment by tombii** [comment]
Happened to me as well, Debian 12.

**Comment by iasdeoupxe** [comment]
Could probably better fit into https://github.com/owncloud/updater

**Comment by sfadschm** [comment]
Reasonably... Moved :-)

**Comment by hknet** [comment]
well this problem is (still) seen (also) during update to v10.14.0.3

**Comment by sfadschm** [comment]
Yes,
 But the underlying issue is fixed. It was just not yet merged into core: #731

**Comment by iasdeoupxe** [comment]
Plus this from https://github.com/owncloud/updater/issues/713#issuecomment-1867176111 / #41149 :

> Installations will get the "release" after they upgrade to a recent release. There is no automated/scripted way to update the updater in a existing older installation. So it can be a bit of a catch-22 if someone needs the updated updater in order to update!

AFAICT manual update is currently the way to go.
