### ISSUE TITLE
Hard to read white on pink text when license is invalid

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#41064]
Seen with 10.13.1 univention appliance

![grafik](https://github.com/owncloud/core/assets/1108546/b8b3eef6-e78f-4748-a996-987cf5e5ea99)

**Comment by jnweiger** [comment]
Expected behaviour:
  * sales@owncloud.com should be clearly readable. E.g. printed in black, like the rest of the text.

**Comment by DeepDiver1975** [comment]
duplicate https://github.com/owncloud/core/issues/40976
