### ISSUE TITLE
Sync failed after moving lots of files

### ISSUE THREAD

**Issue by christophschwitter** [owncloud/core#41087]
After moving a few thousand files, sync failed (it might have failed a few hours before).
Failed to fix the issue. Updated server to newest version: 10.13.2.3
Also using newest client version 3.0.0.9215

### Steps to reproduce
1. moving several thousand files in 1 folder + subfolders, before and after within the same sync folder connection
2. wait for sync as usual.. failed
3. updated server to new version using web interface
4. wait for sync as usual.. failed

### Expected behaviour
1. sync successful

### Actual behaviour
Client aborts with following error messages
"Server replied with an error while reading directory " : error transferring <url> - server replied: Forbidden

Client log

23-11-12 17:54:49:978 [ warning gui.account.state ]:	checkConnectivity blocking: false
23-11-12 17:54:49:978 [ debug sync.connectionvalidator ]	[ OCC::ConnectionValidator::checkServer ]:	Checking server and authentication
23-11-12 17:54:49:978 [ debug sync.connectionvalidator ]	[ OCC::ConnectionValidator::checkServer ]:	Trying to look up system proxy
23-11-12 17:54:49:980 [ info sync.connectionvalidator ]:	No system proxy set by OS
23-11-12 17:54:50:062 [ info sync.checkserverjob ]:	status.php returns:  QJsonDocument({"edition":"Community","installed":true,"maintenance":false,"needsDbUpgrade":false,"product":"ownCloud","productname":"ownCloud","version":"10.13.2.3","versionstring":"10.13.2"})   QNetworkReply::NoError  Reply:  QNetworkReplyHttpImpl(0x21fb2346470)
23-11-12 17:54:50:062 [ info sync.connectionvalidator ]:	** Application: ownCloud found:  QUrl("http://192.168.1.123/owncloud/")  with version  "10.13.2"
23-11-12 17:54:50:062 [ debug sync.connectionvalidator ]	[ OCC::ConnectionValidator::checkAuthentication ]:	# Check whether authenticated propfind works.
23-11-12 17:54:50:062 [ info sync.networkjob ]:	Created OCC::PropfindJob(OCC::Account("Chris@192.168.1.123"), "http://192.168.1.123/owncloud/remote.php/webdav/", "PROPFIND", Original-Request-ID: "090d9d18-29c8-47e9-ad40-3e294c86af1e", X-Request-ID: "090d9d18-29c8-47e9-ad40-3e294c86af1e") for OCC::ConnectionValidator(0x21fb26480c0)
23-11-12 17:54:50:351 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::needsRetry ]:	Not Retry auth job OCC::PropfindJob(OCC::Account("Chris@192.168.1.123"), "http://192.168.1.123/owncloud/remote.php/webdav/", "PROPFIND", Original-Request-ID: "090d9d18-29c8-47e9-ad40-3e294c86af1e", X-Request-ID: "090d9d18-29c8-47e9-ad40-3e294c86af1e", NetworkError: "Error transferring http://192.168.1.123/owncloud/remote.php/webdav/ - server replied: Forbidden") QUrl("http://192.168.1.123/owncloud/remote.php/webdav/")
23-11-12 17:54:50:351 [ info sync.networkjob.propfind ]:	LSCOL of QUrl("http://192.168.1.123/owncloud/remote.php/webdav/") FINISHED WITH STATUS "ContentAccessDenied, Server replied \"403 Forbidden\" to \"PROPFIND http://192.168.1.123/owncloud/remote.php/webdav/\""
23-11-12 17:54:50:353 [ info gui.folder.manager ]:	Account "Chris@192.168.1.123" disconnected or paused, terminating or descheduling sync folders
23-11-12 17:54:50:353 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job finished OCC::PropfindJob(OCC::Account("Chris@192.168.1.123"), "http://192.168.1.123/owncloud/remote.php/webdav/", "PROPFIND", Original-Request-ID: "090d9d18-29c8-47e9-ad40-3e294c86af1e", X-Request-ID: "090d9d18-29c8-47e9-ad40-3e294c86af1e", NetworkError: "Error transferring http://192.168.1.123/owncloud/remote.php/webdav/ - server replied: Forbidden")
23-11-12 17:55:51:982 [ warning gui.account.state ]:	checkConnectivity blocking: false
23-11-12 17:55:51:982 [ debug sync.connectionvalidator ]	[ OCC::ConnectionValidator::checkServer ]:	Checking server and authentication
23-11-12 17:55:51:982 [ debug sync.connectionvalidator ]	[ OCC::ConnectionValidator::checkServer ]:	Trying to look up system proxy
23-11-12 17:55:51:985 [ info sync.connectionvalidator ]:	No system proxy set by OS
23-11-12 17:55:52:037 [ info sync.checkserverjob ]:	status.php returns:  QJsonDocument({"edition":"Community","installed":true,"maintenance":false,"needsDbUpgrade":false,"product":"ownCloud","productname":"ownCloud","version":"10.13.2.3","versionstring":"10.13.2"})   QNetworkReply::NoError  Reply:  QNetworkReplyHttpImpl(0x21fb23468e0)
23-11-12 17:55:52:037 [ info sync.connectionvalidator ]:	** Application: ownCloud found:  QUrl("http://192.168.1.123/owncloud/")  with version  "10.13.2"
23-11-12 17:55:52:037 [ debug sync.connectionvalidator ]	[ OCC::ConnectionValidator::checkAuthentication ]:	# Check whether authenticated propfind works.
23-11-12 17:55:52:037 [ info sync.networkjob ]:	Created OCC::PropfindJob(OCC::Account("Chris@192.168.1.123"), "http://192.168.1.123/owncloud/remote.php/webdav/", "PROPFIND", Original-Request-ID: "66eab74e-e82c-4159-b4ac-4d9060070b2f", X-Request-ID: "66eab74e-e82c-4159-b4ac-4d9060070b2f") for OCC::ConnectionValidator(0x21fb281bff0)
23-11-12 17:55:52:356 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::needsRetry ]:	Not Retry auth job OCC::PropfindJob(OCC::Account("Chris@192.168.1.123"), "http://192.168.1.123/owncloud/remote.php/webdav/", "PROPFIND", Original-Request-ID: "66eab74e-e82c-4159-b4ac-4d9060070b2f", X-Request-ID: "66eab74e-e82c-4159-b4ac-4d9060070b2f", NetworkError: "Error transferring http://192.168.1.123/owncloud/remote.php/webdav/ - server replied: Forbidden") QUrl("http://192.168.1.123/owncloud/remote.php/webdav/")
23-11-12 17:55:52:356 [ info sync.networkjob.propfind ]:	LSCOL of QUrl("http://192.168.1.123/owncloud/remote.php/webdav/") FINISHED WITH STATUS "ContentAccessDenied, Server replied \"403 Forbidden\" to \"PROPFIND http://192.168.1.123/owncloud/remote.php/webdav/\""
23-11-12 17:55:52:357 [ info gui.folder.manager ]:	Account "Chris@192.168.1.123" disconnected or paused, terminating or descheduling sync folders
23-11-12 17:55:52:357 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job finished OCC::PropfindJob(OCC::Account("Chris@192.168.1.123"), "http://192.168.1.123/owncloud/remote.php/webdav/", "PROPFIND", Original-Request-ID: "66eab74e-e82c-4159-b4ac-4d9060070b2f", X-Request-ID: "66eab74e-e82c-4159-b4ac-4d9060070b2f", NetworkError: "Error transferring http://192.168.1.123/owncloud/remote.php/webdav/ - server replied: Forbidden")

### Server configuration

server log after end part of update
{"reqId":"ZGEPHFjon71uHA7RPN9O","level":0,"time":"2023-11-12T16:08:39+00:00","remoteAddr":"192.168.1.123","user":"--","app":"core","method":"POST","url":"\/owncloud\/index.php\/occ\/upgrade","message":"Migrations: starting 20230105001100 from app core"}
{"reqId":"ZGEPHFjon71uHA7RPN9O","level":0,"time":"2023-11-12T16:08:39+00:00","remoteAddr":"192.168.1.123","user":"--","app":"core","method":"POST","url":"\/owncloud\/index.php\/occ\/upgrade","message":"Migrations: completed 20230105001100 from app core"}
{"reqId":"ZGEPHFjon71uHA7RPN9O","level":0,"time":"2023-11-12T16:08:39+00:00","remoteAddr":"192.168.1.123","user":"--","app":"core","method":"POST","url":"\/owncloud\/index.php\/occ\/upgrade","message":"Migrations: starting 20230120101715 from app core"}
{"reqId":"ZGEPHFjon71uHA7RPN9O","level":0,"time":"2023-11-12T16:08:40+00:00","remoteAddr":"192.168.1.123","user":"--","app":"core","method":"POST","url":"\/owncloud\/index.php\/occ\/upgrade","message":"Migrations: completed 20230120101715 from app core"}
{"reqId":"ZGEPHFjon71uHA7RPN9O","level":0,"time":"2023-11-12T16:08:40+00:00","remoteAddr":"192.168.1.123","user":"--","app":"core","method":"POST","url":"\/owncloud\/index.php\/occ\/upgrade","message":"Migrations: starting 20230210073645 from app core"}
{"reqId":"ZGEPHFjon71uHA7RPN9O","level":0,"time":"2023-11-12T16:08:44+00:00","remoteAddr":"192.168.1.123","user":"--","app":"core","method":"POST","url":"\/owncloud\/index.php\/occ\/upgrade","message":"Migrations: completed 20230210073645 from app core"}
{"reqId":"ZGEPHFjon71uHA7RPN9O","level":0,"time":"2023-11-12T16:08:44+00:00","remoteAddr":"192.168.1.123","user":"--","app":"core","method":"POST","url":"\/owncloud\/index.php\/occ\/upgrade","message":"Migrations: starting 20230210103154 from app core"}
{"reqId":"ZGEPHFjon71uHA7RPN9O","level":0,"time":"2023-11-12T16:08:44+00:00","remoteAddr":"192.168.1.123","user":"--","app":"core","method":"POST","url":"\/owncloud\/index.php\/occ\/upgrade","message":"Migrations: completed 20230210103154 from app core"}
{"reqId":"isXrk4QxVcK8HaqGlXhr","level":3,"time":"2023-11-12T16:13:11+00:00","remoteAddr":"192.168.1.128","user":"admin","app":"no app in context","method":"GET","url":"\/owncloud\/index.php\/settings\/personal","message":"User backend OC\\User\\Database is returning home: \/mnt\/ocdata\/data\/admin for user: admin which differs from existing value: \/mnt\/dietpi_userdata\/owncloud_data\/admin"}
{"reqId":"wb48rz1fVezogKPnfkW9","level":3,"time":"2023-11-12T16:57:41+00:00","remoteAddr":"192.168.1.128","user":"--","app":"PHP","method":"GET","url":"\/owncloud\/index.php\/login?user=root","message":"Undefined index: loginName at \/var\/www\/owncloud\/core\/Controller\/LoginController.php#171"}
{"reqId":"MFPX31REii6ziGk7r25I","level":3,"time":"2023-11-12T16:57:46+00:00","remoteAddr":"192.168.1.128","user":"--","app":"no app in context","method":"POST","url":"\/owncloud\/index.php\/login?user=root","message":"User backend OC\\User\\Database is returning home: \/mnt\/ocdata\/data\/admin for user: admin which differs from existing value: \/mnt\/dietpi_userdata\/owncloud_data\/admin"}
{"reqId":"SYu8L4OrNmE8Zm56bXcB","level":3,"time":"2023-11-12T17:02:58+00:00","remoteAddr":"192.168.1.128","user":"admin","app":"no app in context","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"User backend OC\\User\\Database is returning home: \/mnt\/ocdata\/data\/admin for user: admin which differs from existing value: \/mnt\/dietpi_userdata\/owncloud_data\/admin"}
{"reqId":"FeSgLdjfzdRDnTRKCWZP","level":3,"time":"2023-11-12T17:07:58+00:00","remoteAddr":"192.168.1.128","user":"admin","app":"no app in context","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"User backend OC\\User\\Database is returning home: \/mnt\/ocdata\/data\/admin for user: admin which differs from existing value: \/mnt\/dietpi_userdata\/owncloud_data\/admin"}
{"reqId":"vuXcOoys4HbjCGZh5naL","level":3,"time":"2023-11-12T17:13:00+00:00","remoteAddr":"192.168.1.128","user":"admin","app":"no app in context","method":"GET","url":"\/owncloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","message":"User backend OC\\User\\Database is returning home: \/mnt\/ocdata\/data\/admin for user: admin which differs from existing value: \/mnt\/dietpi_userdata\/owncloud_data\/admin"}

Before the error occurred, nothing changed on the server. Same config running as usual. The only thing I am aware of is moving those files (they were by mistake moved before, which worked, now moved back).

Any ideas how to fix this would be appreciated. Thanks!

**Comment by DeepDiver1975** [comment]
There has been a change on the server setup which need to be analysed:

User backend OC\User\Database is returning home: /mnt/ocdata/data/admin for user: admin which differs from existing value: /mnt/dietpi_userdata/owncloud_data/admin

**Comment by christophschwitter** [comment]
Thanks.

I used the standard setup from dietpi, installed quite some time ago. Always worked like that, I certainly did not move the database. 

What do I need to do? Can I just update some configuration path to the correct database location?

**Comment by DeepDiver1975** [comment]
To be honest this is the first time I hear about dietpi. :see_no_evil: 
But it looks like a docker setup (due to `/mnt/`) ?

Is this docker setup provided by dietpi? Was something changed there?

**Comment by iasdeoupxe** [comment]
I have seen such messages recently if the `datadirectory` option in the `config.php` got changed but it was missed to update the database entries correctly:

https://doc.owncloud.com/server/next/admin_manual/maintenance/manually-moving-data-folders.html#adjust-ownclouds-configuration

**Comment by DeepDiver1975** [comment]
Everything fixed now - or are you still facing any issues?

**Comment by christophschwitter** [comment]
Thank you for your help, and sorry for the delay. Between work an kids, there is not much time left.

I tried what you suggested. Unfortunately, it did not help.
- directories in the database where wrong for the admin user, which has no data, no client, nothing to sync.. however: fixed
- now the oc_storages and oc_accounts table contain only valid directories

However, on the client side, nothing has changed. Some error. (with user Chris)

Server Log: 

{"reqId":"gOwLpWmwWMlCOmRwmDmJ","level":3,"time":"2021-09-13T19:40:14+00:00","remoteAddr":"192.168.1.118","user":"--","app":"no app in context","method":"POST","url":"\/owncloud\/index.php\/login","message":"User backend OC\\User\\Database is returning home: \/mnt\/u4t\/ocdata\/Chris for user: Chris which differs from existing value: \/mnt\/ocdata\/data\/Chris"}
{"reqId":"gOwLpWmwWMlCOmRwmDmJ","level":3,"time":"2021-09-13T19:40:15+00:00","remoteAddr":"192.168.1.118","user":"Chris","app":"PHP","method":"POST","url":"\/owncloud\/index.php\/login","message":"opendir(\/mnt\/ocdata\/data\/Chris\/cache): failed to open dir: No such file or directory at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#118"}

{"reqId":"94db17e3-c9de-4233-be23-94ddf2350b44","level":3,"time":"2021-09-13T19:40:30+00:00","remoteAddr":"192.168.1.118","user":"--","app":"no app in context","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/Chris\/","message":"User backend OC\\User\\Database is returning home: \/mnt\/u4t\/ocdata\/Chris for user: Chris which differs from existing value: \/mnt\/ocdata\/data\/Chris"}
{"reqId":"8421eb76-714f-40d0-bdca-0a69d995d9bc","level":3,"time":"2021-09-13T19:40:30+00:00","remoteAddr":"192.168.1.118","user":"--","app":"no app in context","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/Public\/","message":"User backend OC\\User\\Database is returning home: \/mnt\/u4t\/ocdata\/Public for user: Public which differs from existing value: \/mnt\/ocdata\/data\/Public"}
{"reqId":"94db17e3-c9de-4233-be23-94ddf2350b44","level":3,"time":"2021-09-13T19:40:30+00:00","remoteAddr":"192.168.1.118","user":"Chris","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/Chris\/","message":"opendir(\/mnt\/ocdata\/data\/Chris\/cache): failed to open dir: No such file or directory at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#118"}
{"reqId":"e6986b8e-6de7-442b-a274-67bfd4b39de4","level":3,"time":"2021-09-13T19:40:30+00:00","remoteAddr":"192.168.1.118","user":"--","app":"no app in context","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/Weisi\/","message":"User backend OC\\User\\Database is returning home: \/mnt\/u4t\/ocdata\/Weisi for user: Weisi which differs from existing value: \/mnt\/ocdata\/data\/Weisi"}
{"reqId":"8421eb76-714f-40d0-bdca-0a69d995d9bc","level":3,"time":"2021-09-13T19:40:30+00:00","remoteAddr":"192.168.1.118","user":"Public","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/Public\/","message":"opendir(\/mnt\/ocdata\/data\/Public\/cache): failed to open dir: No such file or directory at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#118"}
{"reqId":"e6986b8e-6de7-442b-a274-67bfd4b39de4","level":3,"time":"2021-09-13T19:40:30+00:00","remoteAddr":"192.168.1.118","user":"Weisi","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/Weisi\/","message":"opendir(\/mnt\/ocdata\/data\/Weisi\/cache): failed to open dir: No such file or directory at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#118"}
{"reqId":"01f71fbc-0a36-4847-92b4-8f14e6bf553e","level":3,"time":"2021-09-13T19:40:31+00:00","remoteAddr":"192.168.1.118","user":"Chris","app":"no app in context","method":"GET","url":"\/owncloud\/ocs\/v1.php\/cloud\/capabilities?format=json","message":"User backend OC\\User\\Database is returning home: \/mnt\/u4t\/ocdata\/Chris for user: Chris which differs from existing value: \/mnt\/ocdata\/data\/Chris"}
{"reqId":"34899651-90e1-4dbc-a20f-f7807ea0ba5e","level":3,"time":"2021-09-13T19:40:31+00:00","remoteAddr":"192.168.1.118","user":"Public","app":"no app in context","method":"GET","url":"\/owncloud\/ocs\/v1.php\/cloud\/capabilities?format=json","message":"User backend OC\\User\\Database is returning home: \/mnt\/u4t\/ocdata\/Public for user: Public which differs from existing value: \/mnt\/ocdata\/data\/Public"}
{"reqId":"4ec28fa8-4697-4e57-b712-abdc9ab9fb02","level":3,"time":"2021-09-13T19:40:31+00:00","remoteAddr":"192.168.1.118","user":"Weisi","app":"no app in context","method":"GET","url":"\/owncloud\/ocs\/v1.php\/cloud\/capabilities?format=json","message":"User backend OC\\User\\Database is returning home: \/mnt\/u4t\/ocdata\/Weisi for user: Weisi which differs from existing value: \/mnt\/ocdata\/data\/Weisi"}
{"reqId":"XNRS03p7kI693LFkN7LP","level":3,"time":"2021-09-13T19:41:14+00:00","remoteAddr":"192.168.1.118","user":"--","app":"no app in context","method":"POST","url":"\/owncloud\/index.php\/login","message":"User backend OC\\User\\Database is returning home: \/mnt\/u4t\/ocdata\/Public for user: Public which differs from existing value: \/mnt\/ocdata\/data\/Public"}
{"reqId":"XNRS03p7kI693LFkN7LP","level":3,"time":"2021-09-13T19:41:14+00:00","remoteAddr":"192.168.1.118","user":"Public","app":"PHP","method":"POST","url":"\/owncloud\/index.php\/login","message":"opendir(\/mnt\/ocdata\/data\/Public\/cache): failed to open dir: No such file or directory at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#118"}
{"reqId":"b06b4e05-873d-4327-b212-cba9f23324e9","level":3,"time":"2021-09-13T19:43:19+00:00","remoteAddr":"192.168.1.112","user":"--","app":"no app in context","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"User backend OC\\User\\Database is returning home: \/mnt\/u4t\/ocdata\/Chris for user: Chris which differs from existing value: \/mnt\/ocdata\/data\/Chris"}
{"reqId":"70b83a4e-6d12-459a-a134-17230abd5583","level":3,"time":"2021-09-13T19:43:19+00:00","remoteAddr":"192.168.1.112","user":"--","app":"no app in context","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"User backend OC\\User\\Database is returning home: \/mnt\/u4t\/ocdata\/Public for user: Public which differs from existing value: \/mnt\/ocdata\/data\/Public"}
{"reqId":"b06b4e05-873d-4327-b212-cba9f23324e9","level":3,"time":"2021-09-13T19:43:19+00:00","remoteAddr":"192.168.1.112","user":"Chris","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"opendir(\/mnt\/ocdata\/data\/Chris\/cache): failed to open dir: No such file or directory at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#118"}
{"reqId":"70b83a4e-6d12-459a-a134-17230abd5583","level":3,"time":"2021-09-13T19:43:19+00:00","remoteAddr":"192.168.1.112","user":"Public","app":"PHP","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/","message":"opendir(\/mnt\/ocdata\/data\/Public\/cache): failed to open dir: No such file or directory at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#118"}
{"reqId":"c3a4b649-efb0-4b7c-8e7b-d60302e43dd4","level":3,"time":"2021-09-13T19:43:20+00:00","remoteAddr":"192.168.1.112","user":"Chris","app":"no app in context","method":"GET","url":"\/owncloud\/ocs\/v1.php\/cloud\/capabilities?format=json","message":"User backend OC\\User\\Database is returning home: \/mnt\/u4t\/ocdata\/Chris for user: Chris which differs from existing value: \/mnt\/ocdata\/data\/Chris"}
{"reqId":"cf0a2383-adb0-49c5-9759-e27c92a1daef","level":3,"time":"2021-09-13T19:43:20+00:00","remoteAddr":"192.168.1.112","user":"Public","app":"no app in context","method":"GET","url":"\/owncloud\/ocs\/v1.php\/config?format=json","message":"User backend OC\\User\\Database is returning home: \/mnt\/u4t\/ocdata\/Public for user: Public which differs from existing value: \/mnt\/ocdata\/data\/Public"}



rest of the log is filled with repetitions of the following: 





{"reqId":"Qcu7w4putRUqwCtft4Oh","level":3,"time":"2021-10-01T14:30:02+00:00","remoteAddr":"","user":"--","app":"core","method":"--","url":"--","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve OCA\\\\Federation\\\\SyncJob! Class OCA\\\\Federation\\\\SyncJob does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(110): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/ServerContainer.php(86): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/JobList.php(253): OC\\\\ServerContainer->query()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/BackgroundJob\\\/JobList.php(209): OC\\\\BackgroundJob\\\\JobList->buildJob()\\n#4 \\\/var\\\/www\\\/owncloud\\\/core\\\/Command\\\/System\\\/Cron.php(116): OC\\\\BackgroundJob\\\\JobList->getNext()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/console\\\/Command\\\/Command.php(255): OC\\\\Core\\\\Command\\\\System\\\\Cron->execute()\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(1009): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(273): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/composer\\\/symfony\\\/console\\\/Application.php(149): Symfony\\\\Component\\\\Console\\\\Application->doRun()\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Console\\\/Application.php(165): Symfony\\\\Component\\\\Console\\\\Application->run()\\n#10 \\\/var\\\/www\\\/owncloud\\\/console.php(116): OC\\\\Console\\\\Application->run()\\n#11 \\\/var\\\/www\\\/owncloud\\\/occ(11): require_once('\\\/var\\\/www\\\/ownclo...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php\",\"Line\":96}"}




When installing it, I moved the data directory, first to something "u4T", which appears in the log, then to what its now (ocdata). This was running fine for several years. I did not move the data directory, its fine as it is (if it worked). 
Recently I installed the urbackup client on the owncloud server system, thats all. 

Any ideas?

**Comment by iasdeoupxe** [comment]
```
User backend OC\User\Database is returning home: /mnt/u4t/ocdata/Chris for user: Chris which differs from existing value: /mnt/ocdata/data/Chris
User backend OC\User\Database is returning home: /mnt/u4t/ocdata/Public for user: Public which differs from existing value: /mnt/ocdata/data/Public
```

vs. the previous posted:

```
User backend OC\User\Database is returning home: /mnt/ocdata/data/admin for user: admin which differs from existing value: /mnt/dietpi_userdata/owncloud_data/admin
```

Looks like still some path in the database which needs to be adjusted, but AFAICT giving support is more in the scope of https://central.owncloud.org/
