### ISSUE TITLE
Web Updater cURL Error 35: SSL Routines Error during ownCloud Update from 10.13.2.3 to 10.13.4 on DietPi

### ISSUE THREAD

**Issue by byalvaroft** [owncloud/core#41160]
### Steps to reproduce
1. Attempt to update ownCloud from version 10.13.2.3 to 10.13.4 using the web updater.
2. Click on "Open the Updater."
3. Encounter cURL error 35: error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name for https://localhost/owncloud/index.php/occ/config:list.

### Expected behaviour
The update process should proceed without errors.

### Actual behaviour
Encounter cURL error 35 during the update process.

### Server configuration
**Operating system**: Linux (DietPi)

**Web server**: Nginx

**Database**: MySQL

**PHP version**: 7.4.33

**ownCloud version**: 10.13.2.3

**Updated from an older ownCloud or fresh install**: Fresh install

**Where did you install ownCloud from**: DietPi-software script

**Signing status (ownCloud 9.0 and above)**:
No errors have been found.

**The content of config/config.php**:

    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.100.22",
            "byalvaroft.duckdns.org",
            "cloud.byalvaroft.duckdns.org"
        ],
        "datadirectory": "\/mnt\/dietpi_userdata\/owncloud_data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud",
        "dbtype": "mysql",
        "version": "10.13.2.3",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/run\/redis\/redis-server.sock",
            "port": 0
        },
        "dbname": "owncloud",
        "dbconnectionstring": "",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "allow_user_to_change_mail_address": "",
        "logtimezone": "UTC",
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/owncloud\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "installed": true,
        "instanceid": "oc6erpskfg6m",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**List of activated apps**:
Enabled:
  - activity:
    - Version: 2.7.2
    - Path: /var/www/owncloud/apps-external/activity
  - camerarawpreviews:
    - Version: 0.7.13
    - Path: /var/www/owncloud/apps-external/camerarawpreviews
  - comments:
    - Version: 0.3.0
    - Path: /var/www/owncloud/apps/comments
  - configreport:
    - Version: 0.2.2
    - Path: /var/www/owncloud/apps/configreport
  - dav:
    - Version: 0.7.0
    - Path: /var/www/owncloud/apps/dav
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /var/www/owncloud/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /var/www/owncloud/apps/federation
  - files:
    - Version: 1.6.0
    - Path: /var/www/owncloud/apps/files
  - files_external:
    - Version: 0.9.0
    - Path: /var/www/owncloud/apps/files_external
  - files_mediaviewer:
    - Version: 1.0.5
    - Path: /var/www/owncloud/apps/files_mediaviewer
  - files_pdfviewer:
    - Version: 1.0.1
    - Path: /var/www/owncloud/apps-external/files_pdfviewer
  - files_sharing:
    - Version: 0.14.0
    - Path: /var/www/owncloud/apps/files_sharing
  - files_trashbin:
    - Version: 0.9.1
    - Path: /var/www/owncloud/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /var/www/owncloud/apps/files_versions
  - firstrunwizard:
    - Version: 1.3.0
    - Path: /var/www/owncloud/apps/firstrunwizard
  - market:
    - Version: 0.8.0
    - Path: /var/www/owncloud/apps/market
  - notifications:
    - Version: 0.6.0
    - Path: /var/www/owncloud/apps/notifications
  - provisioning_api:
    - Version: 0.5.0
    - Path: /var/www/owncloud/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /var/www/owncloud/apps/systemtags
  - twofactor_totp:
    - Version: 0.9.0
    - Path: /var/www/owncloud/apps-external/twofactor_totp
  - updatenotification:
    - Version: 0.2.1
    - Path: /var/www/owncloud/apps/updatenotification
Disabled:
  - encryption:
    - Path: /var/www/owncloud/apps/encryption
  - external:
    - Path: /var/www/owncloud/apps/external
  - user_external:
    - Path: /var/www/owncloud/apps/user_external

**Are you using external storage, if yes which one**: <your details here>
no
  
**Are you using encryption**: <yes/no>
no
  
**Are you using an external user-backend, if yes which one**: <your details here>
no

### Client configuration
Thorium (Or any other browser)

**Operating system**: 
Dietpi Version: v8.25 tried before in v8.23

**Comment by iasdeoupxe** [comment]
Should be the same reason (server misconfiguration) similar to #729 and probably moved over to https://github.com/owncloud/updater/issues

Generally better not rely on the updater (#41149) and do a manual update instead.

**Comment by hannesa2** [comment]
The question is: How to solve this server misconfiguration ? -nothing more-

**Comment by hannesa2** [comment]
> Generally better not rely on the updater (#41149) and do a manual update instead.

Maybe there is a reason, why there is an update plugin ? Probable the update is too complicated ?

**Comment by iasdeoupxe** [comment]
I guess how to solve the server misconfiguration would need to be handled via https://central.owncloud.org/
