### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by hannesa2** [owncloud/core#41165]
I use ownCloud Server version 10.5.0.10 and one user can't login.
![image](https://github.com/owncloud/web/assets/3314607/4b0adb59-fe73-4b3e-98c7-fc0b3185bd76)
I tested this enterprise license, but I'm not interested, but I can't remove it. (as a feedback, it's too complicated to remove it)
But my issue is that he can't login. Even with stored password
I'm as admin, changed his password
![image](https://github.com/owncloud/web/assets/3314607/6016d72d-e634-4ed2-8259-fa8525735c87)
But he still can't login.
I can't see his email, so I don't know where is password reset is sent. No email from him, received anything. (as a feedback, I want to see his password)

**How to enable him to login ?**

Btw, someone will mention the old version, but update is not working and too complicated https://github.com/owncloud/updater/issues/729

**Comment by iasdeoupxe** [comment]
Support questions like this usually belongs to https://central.owncloud.org/

This instance definitely needs to be updated to 10.13.4 first (No one probably will be give support for a version released many years ago...)

Not sure why the update should be complicated, there are four simple steps required:
1. Disable all 3rdparty apps
2. Delete all files and folders except `data` and `config` (and maybe also `apps-external` if there) from the current ownCloud install folder on the server
3. Upload the new files from 10.13.4 to the current ownCloud install folder on the server
4. Either run `./occ upgrade` or open the Web GUI and click on "update"

Already did that a few times and took me just a few minutes so not sure why this should be complicated :thinking:

**Comment by hannesa2** [comment]
@iasdeoupxe
Do you really thing update of ownCloud is easy ? 
Now I run into 
```
This version of ownCloud is not compatible with PHP 7.5
You are currently running PHP 8.1.2-1ubuntu2.14. 
```
You should listen to your users: it's not easy

**Comment by hannesa2** [comment]
> * Disable all 3rdparty apps
> 
> * Delete all files and folders except `data` and `config` (and also keep `apps-external` if there) from the current ownCloud install folder on the server
> 
> * Upload the new files from 10.13.4 to the current ownCloud install folder on the server and make sure to adjust the required (environment specific) permissions accordingly
> 
> * Either run `./occ upgrade` (preferred) or open the Web GUI and click on "update" (could run into timeouts)

@iasdeoupxe
It sounds promising. Do you have for each step a command line command ?

**Comment by phil-davis** [comment]
> Do you really thing update of ownCloud is easy ?
Now I run into

```
This version of ownCloud is not compatible with PHP 7.5
You are currently running PHP 8.1.2-1ubuntu2.14. 
```

https://doc.owncloud.com/server/10.13/admin_manual/installation/system_requirements.html
clearly says that PHP 7.4 is required.

**Comment by hannesa2** [comment]
Keep in mind. my primary goal is to fix the broken login from my son, and then the pain begins ...

Yes, writing some requirements somewhere does not mean, that it makes no pain.
Now I installed php7.4 (php7.5 is not available in  ppa:ondrej/php ) and error still exists.

Is there a way to move to a dockerized installation without loosing my users and shares ?

**Comment by hannesa2** [comment]
One more issue: when you search for solutions you find e.g this here https://central.owncloud.org/t/how-to-disable-an-app-without-access-to-the-gui/832

but all links are broken. -wtf-
To ignore continuation is not a sign of a good maintenance. You could keep an eye on this in the future.

**Comment by iasdeoupxe** [comment]
> Do you really thing update of ownCloud is easy ?

From my experiences yes, did already a few such updates on my own instances (starting from around a year ago) without any issues so far

> You should listen to your users: it's not easy

To avoid misunderstandings: I'm a user as you are. If some one is posting in a public issue tracker of a project please don't assume automatically that there is an affiliation with that project :-)

> but all links are broken. -wtf-

Looks like community generated content (AFAICT central is purely community based / maintained) so stuff like this for non-official things are happening :man_shrugging:

Still think that this issue should be closed and the whole "how to update" should be moved over to https://central.owncloud.org/.

And if there is an issue in the documentation around this updating topic suggestions can be made over at https://github.com/owncloud/docs/issues

**Comment by hannesa2** [comment]
> From my experiences yes, did already a few such updates on my own instances (starting from around a year ago) without any issues so far

lucky guy

> To avoid misunderstandings: I'm a user as you are. If some one is posting in a public issue tracker of a project please don't assume automatically that there is an affiliation with that project :-)

Don't feel personal hit. I hope someone who feels/is responsible will read about the pain and see it as feedback to have a better software.

**After 5 days, I'm able to login.**

Here are some commands which helps me to solve it. Maybe it helps some other guys to save some live time  
```
sudo apt install software-properties-common 
sudo add-apt-repository ppa:ondrej/php 
sudo apt install php7.4
sudo apt-get install php-pgsql
sudo apt install php7.4 libapache2-mod-php7.4 php7.4-imagick php7.4-common php7.4-mysql php7.4-gmp php7.4-imap php7.4-json php7.4-pgsql php7.4-ssh2 php7.4-sqlite3 php7.4-ldap php7.4-curl php7.4-intl php
sudo apt-get install php7.4-zip
sudo apt install php7.4-xml
sudo apt install php7.4-gd
sudo systemctl restart apache2
sudo systemctl status apache2
sudo -u www-data ./occ status
sudo -u www-data ./occ upgrade
sudo a2dismod php8.1 
sudo a2dismod php8.0
sudo a2enmod php7.4
sudo systemctl restart apache2
sudo systemctl status apache2
```
fixing `/etc/apache2/mods-enabled/php7.4.load `

**Comment by DeepDiver1975** [comment]
> I hope someone who feels/is responsible will read about the pain and see it as feedback to have a better software.

Unfortunately operating systems like owncloud requires IT understanding and knowledge and as soon as this is missing it is for sure a pure pain. 
We do our best to provide as many information and tutorials as possible.

If you have ideas on how to provide a better user experience on our documentation - please head over to https://github.com/owncloud/docs-server/issues.

**Comment by hannesa2** [comment]
> Unfortunately operating systems like owncloud requires IT understanding and knowledge and as soon as this is missing it is for sure a pure pain.

That's cheeky.

If the update button had worked, I wouldn't have wasted so much time.

When you relay that much on older php (Ubuntu 22.04 comes with php 8.3 out of the box and Ubuntu 24.04 is on the way....), probably you should force a docker installation. Doing so, an easy way to migrate from non-docker to docker usage would be super helpful.

If all is working properly you don't need too overfloat users with an additional documentation source. Documentation is like a news paper, as soon as it is printed, it's outdated.
