### ISSUE TITLE
Sync is broken after ownCloud update

### ISSUE THREAD

**Issue by hannesa2** [owncloud/core#41170]
After I updated #41165 to recent `10.13.4.1` I see on my Mac few minutes "Sync Activity errors" popping up, in Mac ownCloud client shows me this

<img width="364" alt="image" src="https://github.com/owncloud/core/assets/3314607/7074c325-231d-4720-84d1-d030ea10ae26">

and in owcloud .log I see 

```
{
  "reqId": "88f173d6-f969-4a2c-84b5-58d99b0e85d9",
  "level": 2,
  "time": "2024-01-31T11:14:59+00:00",
  "remoteAddr": "111.222.333.444",
  "user": "hannes",
  "app": "no app in context",
  "method": "PROPFIND",
  "url": "\/owncloud\/remote.php\/dav\/files\/hannes\/privateDok\/Filename.jpg",
  "message": "Could not decrypt the private key from user \"hannes\"\" during login. Assume password change on the user back-end. Error message: Bad Signature"
}
{
  "reqId": "7939feaf-89de-4953-857b-1e0df05ecb2e",
  "level": 2,
  "time": "2024-01-31T11:29:35+00:00",
  "remoteAddr": "111.222.333.444",
  "user": "hannes",
  "app": "core",
  "method": "POST",
  "url": "\/owncloud\/index.php\/apps\/oauth2\/api\/v1\/token",
  "message": "Login failed: 'xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69' (Remote IP: '111.222.333.444')"
}
{
  "reqId": "c5a4eecf-6b36-4d89-9a93-a25ff3c49610",
  "level": 2,
  "time": "2024-01-31T11:29:35+00:00",
  "remoteAddr": "111.222.333.444",
  "user": "hannes",
  "app": "no app in context",
  "method": "PROPFIND",
  "url": "\/owncloud\/remote.php\/dav\/files\/hannes\/",
  "message": "Could not decrypt the private key from user \"hannes\"\" during login. Assume password change on the user back-end. Error message: Bad Signature"
}
```
But I can login on web site with my known password !
Does someone has an idea, what's wrong here after the ownCloud update ?

**Comment by iasdeoupxe** [comment]
Could be relevant that the underlying operating system got updated to a more recent version (as indicated in / via the PHP version message in https://github.com/owncloud/core/issues/41165#issuecomment-1916175994) with an update jump from OpenSSL 1.x to 3.x while using the encryption app.

There seems to be a note about OpenSSL versions here:

https://doc.owncloud.com/server/10.13/admin_manual/configuration/files/encryption/encryption_configuration.html#general-notes

leading to the following with an important note about OpenSSL:

https://doc.owncloud.com/server/10.13/admin_manual/installation/manual_installation/manual_installation_prerequisites.html#openssl-version

**Comment by hannesa2** [comment]
In the meantime I got one step further by `'filelocking.enabled' => false,`

I see, when ownCloud needs older stuff, only docker is the way to got

**Comment by iasdeoupxe** [comment]
If there is no external storage (means storage hosted on a different, external system) attached to this system i would even disable encryption as this is pretty useless on systems having the files stored on the same system ownCloud is hosted at:

https://doc.owncloud.com/server/10.13/admin_manual/configuration/files/encryption/encryption_configuration.html#general-notes

> The primary purpose of the ownCloud server-side encryption is to protect users’ files when they’re located on remote storage sites, such as Dropbox and Google Drive
> ...
> Encryption keys are stored only on the ownCloud server, eliminating exposure of your data to third-party storage providers. The encryption application does not protect your data if your ownCloud server is compromised, and it does not prevent ownCloud administrators from reading users’ files.

**Comment by hannesa2** [comment]
> In the meantime I got one step further by `'filelocking.enabled' => false,`

The second thing was, I moved local the content of an consumed share. But the message was not clear to me.
It works now

**Comment by iasdeoupxe** [comment]
I would still disable encryption, it doesn't provide any security benefit and just adds complexity to your setup less people are able to give support for :-)
