### ISSUE TITLE
Cannot set the download repository for owncloud 2.10 on Ubuntu 22.04.3 LTS

### ISSUE THREAD

**Issue by fposseik** [owncloud/core#41181]
I want to install the stable owncloud client following the owncloud installation instructions from https://download.owncloud.com/desktop/ownCloud/stable/2.10/linux/download/. The first step is to set a download repository and that fails.

### Steps to reproduce
1. Fresh installation of Ubuntu 22.04.3 LTS
2. The instructions recommends: 
`$ wget -nv https://download.owncloud.com/desktop/ownCloud/stable/2.10/linux/Ubuntu_22.04/Release.key -O - | sudo apt-key add -`
But I get the following error: 
`Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead`

3. I then adapt the command to get the key set:
`$ wget -nv https://download.owncloud.com/desktop/ownCloud/stable/2.10/linux/Ubuntu_22.04/Release.key -O - | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/owncloud.gpg`
That seems to work:
`$ ls /etc/apt/trusted.gpg.d/`
`owncloud.gpg  ubuntu-keyring-2012-cdimage.gpg  ubuntu-keyring-2018-archive.gpg`

 This is what I get from this key:
```
$ gpg --show-keys /etc/apt/trusted.gpg.d/owncloud.gpg 
pub   rsa2048 2015-09-28 [SC] [expired: 2023-04-28]
      06D7EADE708A40FA136EB4540700205DFD41A71A
uid                      devel OBS Project <devel@s2.owncloud.com>
```

4. I then continue with the instructions:
`$ echo 'deb https://download.owncloud.com/desktop/ownCloud/stable/2.10/linux/Ubuntu_22.04/ /' | sudo tee -a /etc/apt/sources.list.d/owncloud.list`
That makes no troubles.

5. The main problem comes in this step:
```
$ sudo apt update
Hit:1 http://de.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://de.archive.ubuntu.com/ubuntu jammy-updates InRelease                   
Hit:3 http://de.archive.ubuntu.com/ubuntu jammy-backports InRelease                 
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:5 https://download.owncloud.com/desktop/ownCloud/stable/2.10/linux/Ubuntu_22.04  InRelease [1.436 B]
Err:5 https://download.owncloud.com/desktop/ownCloud/stable/2.10/linux/Ubuntu_22.04  InRelease
  The following signatures were invalid: EXPKEYSIG 0700205DFD41A71A devel OBS Project <devel@s2.owncloud.com>
Reading package lists... Done
W: GPG error: https://download.owncloud.com/desktop/ownCloud/stable/2.10/linux/Ubuntu_22.04  InRelease: The following signatures were invalid: EXPKEYSIG 0700205DFD41A71A devel OBS Project <devel@s2.owncloud.com>
E: The repository 'https://download.owncloud.com/desktop/ownCloud/stable/2.10/linux/Ubuntu_22.04  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Target Packages (Packages) is configured multiple times in /etc/apt/sources.list.d/owncloud.list:1 and /etc/apt/sources.list.d/owncloud.list:2
W: Target Translations (en_US) is configured multiple times in /etc/apt/sources.list.d/owncloud.list:1 and /etc/apt/sources.list.d/owncloud.list:2
W: Target Translations (en) is configured multiple times in /etc/apt/sources.list.d/owncloud.list:1 and /etc/apt/sources.list.d/owncloud.list:2
```

6. If I now go to installation step `$ sudo apt install owncloud-client` a very old version of owncloud is installed (2.6), which produces a `Segmentation fault (core dumped)`...

### Expected behaviour
Get owncloud installed with problems

### Actual behaviour
It seems that the Release.key file downloaded in step 2 is not working. Is the fact that it is expired the main issue?
Possibly, my solution in point 3 may not be correct.
1. **Please update the installation instructions to avoid using `apt-key`.**
2. **Please update the Release.key file.**

**Comment by iasdeoupxe** [comment]
Why not using version 5.2.1 (2.10 is from 2020...)?

https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/

As this is not a bug in ownCloud server this should be closed.
