### ISSUE TITLE
Update Translation on ownCloud Instance

### ISSUE THREAD

**Issue by Keram-Yasin** [owncloud/core#41190]
This is not bug but a question about updating translation files on ownCloud instance. I am asking here because I haven't got answer from https://central.owncloud.org/.

I would like to update quickly the translation files after I have completed translation of one or more file(s) on Transifex. I have read document about how the translations are nightly synched to master branch. But, how are those translations are synched to ownCloud instance which is already installed? 

Test: I have manually overwritten the old json and js file with the new json and js files with latest translations from Transifex. But when I change the language to that language on ownCloud instance, The new translations are not loaded even if I remove the browser catches.

Expected behavior:
The new translation should be appeared when the language is changed to the language of updated translations.

**Comment by DeepDiver1975** [comment]
> ut, how are those translations are synched to ownCloud instance which is already installed?

this requires a release by the owncloud project.

**Comment by DeepDiver1975** [comment]
> Test: I have manually overwritten the old json and js file with the new json and js files with latest translations from Transifex. But when I change the language to that language on ownCloud instance, The new translations are not loaded even if I remove the browser catches.

various caching mechanics can kick in here - besides clearing browser cache I suggest to restart apache ....

Better approach would be to put your changed translation files into a custom theme. Please follow the docs on this.

**Comment by Keram-Yasin** [comment]
@DeepDiver1975 thanks for your advices. I have made some other tests today. The test is very simple as described below:

Test1: I changed an existing string on Italian translation files (apps/files/l10n/it.js, apps/files/l10n/it.json), e.g. changed the first letters of all words in a string to capital. And then changed the owncloud language to Italian, The modified string appears immediately.

Test2: repeat the same procedure on translation files (apps/files/l10n/ug.js, apps/files/l10n/ug.json), and then change the language to Uyghur. But the translation string is not even appeared in Uyghur but in English.

I think there are some constrain on languages with which the owncloud strings appear or something. The goal of this translation update was to translate more owncloud apps in target language so that the target users benefit from the translation as soon as the next version arrives. If the translations are not loaded on target language, the work of translation is meaningless. So, I am quite confused what to do next. can you please check why this happens in some less popular language like Uyghur? Thanks you very much.
