### ISSUE TITLE
[QA] typical Photos from a smartphone are no longer rendered in the builtin image viewer

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#41192]
Seen in 10.14.0-rc.2

* Make a photo with a phone.
   - E.g. my old Samsung S3 from 2015 produced JPEGs with 9.6 MegaPixels (4128 x 2322)
   - more recent phones often have higher MegaPixel counts. 
* Upload such a photo to the Photos folder. Refresh. Wait. Refresh. No thumbnail icon appears. BAD.
* Click on the photo, files_mediaviewer opens. But nothing is shown. BAD
![grafik](https://github.com/owncloud/core/assets/1108546/1f23e9ba-07e4-40df-869a-2ef3d7c84675)

----

### Expected behaviour
* "normal" sized photos can be viewed in the media-viewer.

This behaviour apparently "works as designed" due to https://github.com/owncloud/core/blame/master/lib/private/Preview/Image.php#L49
Do we know, why this change was made? Such a hardcoded limit is disruptive from an end user perspective.

### Suggested behaviour
* Make the exact values configurable (as is, a change will trigger the integrity checker)
* make the default values an order of magnitude higher

**Comment by DeepDiver1975** [comment]
Sec hardening against pixel dos

**Comment by jnweiger** [comment]
> Sec hardening against pixel dos

Understood. How about increasing the limits by factor 10?

**Comment by DeepDiver1975** [comment]
This will result in x100 more memory and processing time.

A 24 mega pixel camera produces pics with 6016 x 4000 - that reads more reasonable.

I was choosing 4096×2160 because is the 4k video dimension - I totally missed the camera use case which has much higher dimensions.

**Comment by DeepDiver1975** [comment]
hmmm ... okay - there are also 50 megapixel cameras out there - or even 100 mega pixel and more ....

But at some point these images are out of scope for processing :shrug: - for the current architecture ...

**Comment by DeepDiver1975** [comment]
@jnweiger same on avatar - FYI - https://github.com/owncloud/core/blob/235c014359675ffd39c40acd5fce7c6f9c86df58/core/Controller/AvatarController.php#L219

**Comment by pako81** [comment]
30MP seems to be around the range 6.700 x 4.400, I guess with 6100 x 4100 for 24MP we should cover everything.

**Comment by pauliusm** [comment]
30MP camera (e.g. Canon EOS-R) would require 6580x4297 or 4297x6580 (depending on orientation).

**Comment by DeepDiver1975** [comment]
There has to be a cut of at some point. In case anybody wants previews being processed for pics with higher dimensions -> please adjust the config parameter.

I vote to close this ....
