### ISSUE TITLE
subfolder pane sorting by last modified function not working

### ISSUE THREAD

**Issue by joomlafun** [owncloud/core#41202]
### Steps to reproduce
1.activate via settings>panels>subfolder>sort by last change
2.modify a note
3.

### Expected behaviour
Folder with last note modified should be on top of the list

### Actual behaviour
Folder with last note modified is not on top of the list

Somehow my folder order never changes both for root folders than for subfolders.
I would expect root folder to be sorted by last modified note and same for subfolders in those root folders.

According to me the best implementation for folders would be : Recent folders + pinned folders like in any OS explorer

### Server configuration
**Operating system**:
ubuntu 23.10 plasma 5.27.8
qownote 24.2.5

**Comment by DeepDiver1975** [comment]
> qownote 24.2.5

this is the wrong repository

**Comment by DeepDiver1975** [comment]
https://github.com/pbek/QOwnNotes
