### ISSUE TITLE
[QA] Previews fail for SVG images with gradients

### ISSUE THREAD

**Issue by jnweiger** [owncloud/core#41218]
Seen in e.g. 10.14.0, (but not a regression)

* download two test images:
  - https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/car.svg
  - https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/adobe.svg
* Start ownCloud with enabled SVG previews, e.g. like this:
  `docker run --rm -ti -p 8080:8080 -e 'OWNCLOUD_ENABLED_PREVIEW_PROVIDERS=OC\Preview\SVG'  owncloud/server:10.14.0`
* Upload adobe.svg -> a thumbnail preview is generated in the files view. OK.
* Upload car.svg -> a generic SVG icon is seen.

The car.svg file contains several defs that are used like this:
```
   <linearGradient
       inkscape:collect="always"
       xlink:href="#linearGradient4061"
       id="linearGradient4067"
       x1="708.0863"
       y1="416.54196"
       x2="710.52051"
       y2="423.02032"
       gradientUnits="userSpaceOnUse"
       gradientTransform="translate(-74.8682,-105.3782)" />
```

## Workaround
 - comment out this code block in function getThumbnail in ./lib/private/Preview/SVG.php
```
                        // Do not parse SVG files with references
                        if (\stripos($content, 'xlink:href') !== false) {
                                return false;
                        }
```
## Expected behaviour
 - only SVG files with external references are rejected. E.g. by matching for `'xlink:href=http'` and similar.
 - SVG files with internal references like e.g. `xlink:href="#linearGradient4061"` are accepted.
 - documentation about the Preview configuration should talk about this.
 

Note that there is also the syntax     `<path style="fill:url(#linearGradient3893);`... used to access local references.

**Comment by jnweiger** [comment]
Affected by #41234

**Comment by IljaN** [comment]
@jnweiger As far as we understand this can be closed? Please re-open if needed.
