### ISSUE TITLE
OwnCloud freezes my system during first account creation

### ISSUE THREAD

**Issue by HenraL** [owncloud/core#41220]
Hardware configuration:
Hypervisor: Proxmox (8.1.4)
VM:
* RAM: 8GB
* Processor: 8 (2 sockets, 4 cores)
* BIOS: default: SeaBIOS
* Machine: Default (i440fx)
* SCSI Controller: VirtIO SCSI Single
* Hard disk one, size: 200G, has the operating system and the apps installed on it
* Hard disk two, size: 500G, has the folders data and apps-external on it (it as meant to store the user's data)
* OS Type: Linux 6.x - 2.6 Kernel
* KVM Hardware virtualization: yes
* QEMU Guest Agent: Enabled
* Cloud-init: not set up

### Steps to reproduce
1. Download Ubuntu server 22.04.3 (ubuntu-22.04.3-live-server-amd64.iso)
2. Follow the tutorial for manual installation
3. Run the script when asked (for the automation)
    (during the installation, make sure that data and apps-external point to a secondary drive [that is mounted at boot to the system])
4. Install mariadb
5. set ownership of folders: /mnt/owncloud_data/apps-external, /mnt/owncloud_data/data,/var/www/owncloud/data 
6. create a second user in the database to use for initial connection
7. attempt to connect
8. During the connection, you should see a hung task timeout sec error repeatedly and any command you try to run after seeing that message (including reboot) will have no effect, effectively forcing you to force shutdown the system.

### Expected behaviour
Create the admin account and (basically do the normal steps owncloud would do upon the admin account creation)

### Actual behaviour
During the connection, you should see a hung task timeout sec error repeatedly and any command you try to run after seeing that message (including reboot) will have no effect, effectively forcing you to force shutdown the system.
If one looks into the database, they will see two oc_<their_account_name> that would have been created.

### Server configuration
**Operating system**: `ubuntu-22.04.3-live-server-amd64` (downloaded from the official ubuntu website)

**Web server:** 
```
Server version: Apache/2.4.52 (Ubuntu)
Server built:   2023-10-26T13:44:44
```

**Database:**
```
mariadb  Ver 15.1 Distrib 10.6.16-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
```

**PHP version:**
```
PHP 7.4.33 (cli) (built: Sep  2 2023 08:03:46) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies
```

**ownCloud version:** (see ownCloud admin page): Cannot access owncloud due to being stuck on the initial account creation page.

**Updated from an older ownCloud or fresh install:**: `fresh install`

**Where did you install ownCloud from:** `source (latest version [as of march 2024)`

**Signing status (ownCloud 9.0 and above):**
```
Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'oc_Hanra'@'localhost' to database 'owncloud'
```

(But when you look into the database, the user exists, the database exists)

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and puth the link here.
(can't do that)
```

**The content of config/config.php:**

```
Log in to the web-UI with an administrator account and click on
'admin' -> 'Generate Config Report' -> 'Download ownCloud config report'
This report includes the config.php settings, the list of activated apps
and other details in a well sanitized form.

or 

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

*ATTENTION:* Do not post your config.php file in public as is. Please use one of the above
methods whenever possible. Both, the generated reports from the web-ui and from occ config:list
consistently remove sensitive data. You still may want to review the report before sending.
If done manually then it is critical for your own privacy to dilligently
remove *all* host names, passwords, usernames, salts and other credentials before posting.
You should assume that attackers find such information and will use them against your systems.
```

\# represents (my manual) comments for metadata about blurring sensitive content
<a_sentence> is another method I use to hide sensitive content
```
<?php
$CONFIG = array (
  'instanceid' => 'ocoepv85738m',
  'passwordsalt' => '<some_hash_with_plus_signs>',
  'secret' => '<the_secret_key>',
  'trusted_domains' =>
  array (
    0 => '***.***.***.***', # The stars represent the sections of my ip
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://***.***.***.***/owncloud',
  'dbtype' => 'mysql',
  'version' => '10.14.0.3',
  'dbname' => 'owncloud',
  'dbconnectionstring' => '',
  'dbhost' => 'localhost:<port>',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'oc_<my_account_name>',
  'dbpassword' => '<a_hash_of_the_password>',
);
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder.
```
No apps where activated because I have not passed the first page of owncloud.

**Are you using external storage, if yes which one:** local/smb/sftp/...: `yes`, local, a mounted drive for the data and app-external (that was an option offered by the installation script owncloud provided)

**Are you using encryption:** yes/no: `no`

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... `Just the vanilla owncloud`

### Client configuration
**Browser:** : `Google Chrome` and `Firefox`

**Operating system:**: `Windows 10`

#### Web server error log
```
Insert your webserver log here
```
I don't know which logs to show.

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

```
<empty>
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
```
> JQMIGRATE: Migrate is installed, version 1.4.0
```
b) The network log 
```
> None to show.

**Comment by iasdeoupxe** [comment]
Sounds more like a support request for https://central.owncloud.org/

**Comment by HenraL** [comment]
will look into that, thank you
