### ISSUE TITLE
Ideas on encryption

### ISSUE THREAD

**Issue by GRMrGecko** [owncloud/core#4122]
I just read http://blog.schiessle.org/2013/05/28/introduction-to-the-new-owncloud-encryption-app/

Reading it, it sounds like the encryption keys for files are randomly generated. Why not change the encryption key to be based on the file contents using a hash. Example, use sha256 to hash the file, and use the resulted hash as the encryption key for the file.

Using the hash as an encryption key makes it possible to do some de-duplication of files. If the file being uploaded has the same hash, then it's not needed to be uploaded again. Of course, you'll use a salt to make the hash stronger. But you won't be using random salts for each file as it is needed to be the same for de-duplication. You'll have 2 salts. One for the de-dup hash, and the other for the encryption hash.

For de-dup, you'll have a database with the folder structure for each user. The name of files, the encryption key which was encrypted with the user public key and so on. You will then make the data folder be based on file hashes. Due to filesystem limits, you'll have to split them into folders somehow... Maybe have the first part of the hash be a folder name. This hash will be the one salted for de-dup.

The web based interface should allow the users to disable viewing files via the web based interface and anything else that has the server decrypt the files. Make sure the clients for iOS/Android/Linux/Mac/Windows supports decryption and encryption client side. Making this be a trust no one solution.

I do not know if my idea is too crazy, but it's an idea. My implementation thoughts may be wrong, but it gets the idea across.

**Comment by LukasReschke** [comment]
I don't think that's worth the hassle. Will potentially introduce other attack vectors.
