### ISSUE TITLE
Invalid signature EXPKEYSIG 4ABE1AC7557BEFF9

### ISSUE THREAD

**Issue by G0ldmember** [owncloud/core#41224]
It seems the key signature expired again 2 days ago. 

`pub   rsa2048 2016-09-25 [SC] [verfallen: 2024-03-23]
      1B07 204C D71B 690D 409F  57D2 4ABE 1AC7 557B EFF9
uid        [ verfallen ] isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>`

### Steps to reproduce
1. Try to run `apt update` with owncloud repo active (Debian 11 / Bullseye)
2. See error message appearing "EXPKEYSIG 4ABE1AC7557BEFF9"

### Expected behaviour
apt update should run fine without errors

### Actual behaviour
error about expired key signature is thrown

### Server configuration
**Operating system**: Debian 11 / Bullseye

**Web server:** apache2

**Database:** psql

**ownCloud version:** 10.14.0-1+10.1

**Comment by DeepDiver1975** [comment]
@jnweiger

**Comment by jnweiger** [comment]
I've run an extendkey command command on the isv:ownCloud:server:10 repository again. It seems that some parts were misssed last time, the command was run.
I can now see expiry dates 2025-06-25 and 2026-05-07 in different places -- not sure why they differ. but at least both are valid for a while.

@G0ldmember please check again. To me, this now looks good:
`curl -sL https://download.opensuse.org/repositories/isv:ownCloud:server:10/Debian_11/Release.key | gpg`

**Comment by G0ldmember** [comment]
> I've run an extendkey procedure on the isv:ownCloud:server:10 repository again. It seems that some parts were misssed last time, the command was run. I can now see expiry dates 2025-06-25 and 2026-05-07 in different places -- not sure why they differ. but at least both are valid for a while.
> 
> @G0ldmember please check again. To me, this now looks good: `curl -sL https://download.opensuse.org/repositories/isv:ownCloud:server:10/Debian_11/Release.key | gpg`

`apt-key list 4ABE1AC7557BEFF9
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
pub   rsa2048 2016-09-25 [SC] [verfällt: 2026-05-07]
      1B07 204C D71B 690D 409F  57D2 4ABE 1AC7 557B EFF9
uid        [ unbekannt ] isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>
`
Thanks, seems to work now.

**Comment by G0ldmember** [comment]
Can be closed
