### ISSUE TITLE
Discovery url returns url with incorrect port

### ISSUE THREAD

**Issue by Windree** [owncloud/core#41223]
### Steps to reproduce
1. Install owncloud docker server using docker-compose.yml [docker-compose.txt](https://github.com/owncloud/core/files/14649574/docker-compose.txt)
(from attachment). Specify OWNCLOUD_DOMAIN=cloud.dragonsoul.com in the .env file
[env.txt](https://github.com/owncloud/core/files/14649597/env.txt)

2. Run docker docker-compose up --build
3. Setup nginx reverse proxy using following http server configuration [nginx-http-server.txt](https://github.com/owncloud/core/files/14649623/nginx-http-server.txt)
4. Run/reload nginx
5. add `nginx_server_ip_address cloud.dragonsoul.com` in you local hosts file
6. open browser and enter https://cloud.dragonsoul.com/
7. login owncloud using credentials from .env
9. Install calendar and contacts apps
10. Request https://cloud.dragonsoul.com/.well-known/caldav with curl or a browser

### Expected behaviour
https://cloud.dragonsoul.com/.well-known/caldav should returns redirect to http://cloud.dragonsoul.com/remote.php/dav/

### Actual behaviour
https://cloud.dragonsoul.com/.well-known/caldav returns redirect to http://cloud.dragonsoul.com:8080/remote.php/dav/. With 8080 port ignoring OWNCLOUD_DOMAIN env setting

### Server configuration
**Operating system**:
Ubuntu 22.04 Docker version 24.0.5, build 24.0.5-0ubuntu1~22.04.1
**Web server:**
Apache/2.4.41 (Ubuntu)
**Database:**
mariadb:10.11
**PHP version:**
PHP 7.4.3-4ubuntu2.20 (cli) (built: Feb 21 2024 13:54:34) ( NTS )
**ownCloud version:** (see ownCloud admin page)
10.14.0 (stable)
**Updated from an older ownCloud or fresh install:**
fresh install
**Where did you install ownCloud from:**
dockerhub

**Comment by iasdeoupxe** [comment]
Looks more like a support request for https://central.owncloud.org/ rather that a bug / issue in ownCloud directly.
