### ISSUE TITLE
404 Error when trying to load a preview of the photo (JPG)

### ISSUE THREAD

**Issue by temkalol41** [owncloud/core#41238]
## Describe the bug
I have deployed the most up-to-date copy of OwnCloud on my server with the latest updates. During usage, I encountered an issue with loading previews for photos. While previews were successfully generated for some photos, they were not created for 90% of them. What could be the problem and how can it be resolved within the product?

The image preview returns a 404 error in the console. There are no errors recorded in the web server logs or PHP logs.

## Steps to reproduce
To reproduce the issue:
1. Create a folder in OwnCloud.
2. Add several files of different sizes to the folder (JPG).
3. Check the display of previews for the photos.

## Expected behavior
It is expected that the images will be available for preview to be opened using the standard photo viewing module.

## Actual behavior
A 404 error is displayed for the previews of random photos.

## Setup
Fresh installation on a virtual machine running Ubuntu 20.04.6 LTS, with the hypervisor being the latest version of Proxmox.

<details>
<p>

```OC Version
$OC_Version = array(10,14,0,3);
$OC_VersionString = '10.14.0';
$OC_Channel = 'stable';
$OC_Edition = 'community';
```

</p>
</details>
<img width="1385" alt="Console-log" src="https://github.com/owncloud/web/assets/23693997/185a0843-18b3-45ac-8d7f-2a6c851b0e35">
<img width="1007" alt="Failed-preview" src="https://github.com/owncloud/web/assets/23693997/27ca31ab-1739-4eb5-80c4-ff44a36b51c7">
<img width="1010" alt="Photos-list" src="https://github.com/owncloud/web/assets/23693997/3084584f-9821-47d5-a5f2-2dce2632a52c">

**Comment by JammingBen** [comment]
Fyi I transferred this issue to the core repository since this is not a Web client issue.

**Comment by DeepDiver1975** [comment]
Which ownCloud version?
What is the dimensions of the image?

please see https://github.com/owncloud/core/blob/986ebba88a2b7ba85361be18c552e24500c1f1f6/config/config.sample.php#L1024

**Comment by temkalol41** [comment]
@DeepDiver1975 thanks for the advice! I managed to find a solution to the issue. My photos were of very high resolution, I added parameters from the specified file. After adding new parameters, I restarted the server and the previews were displayed without errors.

**Comment by x0r13** [comment]
@temkalol41 

Could you please tell me what exactly you changed? Because I have the same problem. I just installed owncloud docker for the first time (10.14.0 (stable) ) and there is no preview for jpg files, other files (tested png and webp) seem to work fine.
