### ISSUE TITLE
New Spanish variant es_ES has been created with very few translations

### ISSUE THREAD

**Issue by phil-davis** [owncloud/core#41245]
The Transifex trnaslations update yesterday pushed new files for language variant `es_ES` with only a few translations.

But there is already base language `es` with a lot of translations.

IMO this new "variant" will be confusing because `es_ES` should really just be the base Spanish `es`. People who choose `es_ES` will be surprised that there are very few things translated on the UI.

https://github.com/owncloud/core/commit/c74810da0d457f60be84ee3c46dfb4d3d4eb8638

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Selecting a "vanilla" Spanish language gets a very high percentage of translations.

### Actual behaviour
Selecting `es_ES` has very few translations.

### Server configuration
core master

**Comment by phil-davis** [comment]
I noticed this because some translation acceptance tests started failing:
https://drone.owncloud.com/owncloud/core/39897/74/14

```
Failed step: And the OCS status message should be "Wrong share ID, share doesn't exist" in language "es-ES"
        Unexpected OCS status message :"Wrong share ID, share doesn't exist" in response
        Failed asserting that two strings are equal.
        --- Expected
        +++ Actual
        @@ @@
        -'El ID del recurso compartido no es correcto, el recurso compartido no existe'
        +'Wrong share ID, share doesn't exist'
```

**Comment by DeepDiver1975** [comment]
remove the language again then - we don't need it.
let me know if you don't have enough privileges to do so

**Comment by phil-davis** [comment]
@DeepDiver1975 I do not have any privileged access to Transifex. Please sort it out, or get someone with privilege to sort it out.

**Comment by DeepDiver1975** [comment]
taken care of .... and some other languages as well
