### ISSUE TITLE
owncloud 10.14.0 is broken when files_external app is removed

### ISSUE THREAD

**Issue by cortho** [owncloud/core#41266]
When ```files_external``` app is removed from the app directory all ownCloud functionality stops because of hard coded dependencies.

### Steps to reproduce
1. Remove files_external directory from app folder
2. Call the instance URL or run any occ command
3. See the exception:

```
$ sudo -u www-data php occ app:list
PHP Warning:  require(/var/www/owncloud/lib/composer/composer/../../../apps/files_external/lib/config.php): failed to open stream: No such file or directory in /var/www/owncloud/lib/composer/composer/autoload_real.php on line 59
PHP Fatal error:  require(): Failed opening required '/var/www/owncloud/lib/composer/composer/../../../apps/files_external/lib/config.php' (include_path='/var/www/owncloud/lib/composer/pear/console_getopt:/var/www/owncloud/lib/composer/pear/pear_exception:/var/www/owncloud/lib/composer/pear/pear-core-minimal/src:/var/www/owncloud/lib/composer/pear/archive_tar:.:/usr/share/php') in /var/www/owncloud/lib/composer/composer/autoload_real.php on line 59
```

For some reason files_external is hard coded on some places:
```
$ fgrep -R files_external lib/composer/
lib/composer/composer/autoload_files.php:    '6570395c00f0dfed47ca218ded344b80' => $baseDir . '/apps/files_external/lib/config.php',
lib/composer/composer/autoload_static.php:        '6570395c00f0dfed47ca218ded344b80' => __DIR__ . '/../../..' . '/apps/files_external/lib/config.php',
```

### Expected behaviour
ownCloud is working without files_external app

### Actual behaviour
ownCloud is dead once files_external app is deleted

### Server configuration
**PHP version:**
7.4.3

**ownCloud version:** (see ownCloud admin page)
10.14.0.3

**Updated from an older ownCloud or fresh install:**
fresh install

**Where did you install ownCloud from:**
https://owncloud.com/download-server/

**Comment by DeepDiver1975** [comment]
App dependencies simple never got fully resolved which makes files_external a hard dependency.
basically the same as with the files app

**Comment by phil-davis** [comment]
https://github.com/owncloud/core/tree/master/apps/files_external is a "bundled app that is in the core repo.

You can disable it:
`php occ app:disable files_external`

and the rest of the system should still work.

But actually deleting the code is a step too far ;)
