### ISSUE TITLE
Extend telemetry.enabled description in config.sample.php -> Only enterprise users affected

### ISSUE THREAD

**Issue by iasdeoupxe** [owncloud/core#41285]
### What?
Addition suggestion for:
- owncloud/configreport#197
- owncloud/docs-server#1347
- #41283

I'm not good in providing texts so just raising this issue here instead of providing a PR.

### Suggestion
The change would raise red alerts for me as a community user as "Telemetry" is enabled by default but looks like only enterprise users (with valid licenses) are affected -> https://github.com/owncloud/configreport/pull/197#discussion_r1667488313

Extend the text from #41284 to make this more clear, otherwise this will raise concerns by community users.

Possibly to be clarified and documented as well: Is this also only sending data if the configreport app is enabled or independent from that?

**Comment by jnweiger** [comment]
Clarified the enterprise only featue in the text in config.sample.php - thanks for the hint.

Nothing can be sent, when the configreport app is disabled. E.g. the background job for sending telemetry is only present in `occ background:queue:status` while the app is enabled.

**Comment by iasdeoupxe** [comment]
#41286 is already merged
