### ISSUE TITLE
HEIC: multikeydecrypt with share key failed, digital envelope routines::unsupported

### ISSUE THREAD

**Issue by mtojek** [owncloud/core#41292]
### Steps to reproduce
1. Upload .HEIC photos.
2. Try to access them using browser.

I'm happy to provide more reference data, but not sure what you need.

### Expected behaviour

I should be able to download media files.

### Actual behaviour

I can't access .HEIC files. It might be related with an update on shared hosting?

```
Encryption not ready: multikeydecrypt with share key failed:error:0308010C:digital envelope routines::unsupported
```

### Server configuration

**ownCloud version:** [ownCloud ](https://owncloud.org/)10.8.0 (stable)

**Comment by iasdeoupxe** [comment]
> ownCloud version: 10.8.0 (stable)

This is from 2021-07-15 so three years old: https://owncloud.com/changelog/server/#changelog-for-owncloud-core-1080-2021-07-15

Better get some support from https://central.owncloud.org/, could be also related to https://doc.owncloud.com/server/10.14/admin_manual/installation/manual_installation/manual_installation_prerequisites.html#openssl-version
