### ISSUE TITLE
Files: if file does not have versions, disable »versions« entry and show »No Versions«

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#4178]
As talked about in https://github.com/owncloud/core/pull/4168 – files without versions currently show an uninformative dropdown with »this file has no versions«.

Instead, files without versions should not have the »Versions« action at all.

cc @schiesbn @icewind1991 @owncloud/designers

**Comment by PVince81** [comment]
This would be technically possible with the file actions dropdown. If we move the versions there, the dropdown could be loaded asynchronously (spinner) and use the opportunity to check if the files has versions.

However it was decided that the versions will eventually be moved to the right sidebar anyway: https://github.com/owncloud/core/issues/16308#issuecomment-113526558

Closing as obsolete.
