### ISSUE TITLE
Enable GNOME users to use ownCloud account to log in

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#4338]
Talked to @stefwalter at GUADEC that it would be cool if GNOME users who have their ownCloud connected via GNOME Online Accounts could log in to their computer by putting in their ownCloud credentials rather than a local log in.

@stefwalter I understood that correctly, right? :) I suppose you need to talk to Debarshi/rishi about how to add that to GOA. What do we need to do to make the rest possible?

In addition, we could sync the user image and name from the Personal settings because that is shown on the log in screen of GNOME.

cc @DeepDiver1975 @butonic

**Comment by hodyroff** [comment]
Please comment and/or reopen if this makes sense outside of oAuth implementation.
