### ISSUE TITLE
Virtual Hosting with LDAP Authentication

### ISSUE THREAD

**Issue by prologic** [owncloud/core#4412]
Hi there,

I'm integrating (at present) owncloud with kolab 3.0
and as such have configured my ownCloud instnace
to authenticate against the kolab LDAP tree.

This works fine. What I'd also like is to be able to
dynamically change the Base DN and User and Group DN
appropriately depending on HTTP_HOST.

Basically using the one ownCloud instance to support
multiple domains authenticated against a central LDAP tree.

Can this be added?

cheers
James

**Comment by blizzz** [comment]
Not that I would really have resources for it, but since this is lying around for some time: is there still interest?

**Comment by blizzz** [comment]
> Not that I would really have resources for it, but since this is lying around for some time: is there still interest?

No further comment, so apparently not → closing.
