### ISSUE TITLE
Design forward: Sharing behavior

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#4437]
# Sharing improvements

As talked about with @DeepDiver1975 @butonic @MTRichards @karlitschek etc.

Precursors:

* Review new Share API, see #3969
* Improve the sharing dialog, see »Design forward: Sharing dialog« #3224 
* Decide on how quota is calculated, see https://github.com/owncloud/core/issues/2796

## Indicate owner and participants
Currently, you need to click on the dropdown to know who is the original owner of a file shared with you.
* [x] Instead, this should be directly in the file list row, where the »Shared« icon is right now.
* [x] In the future we can do that with user images or other autogenerated visual identifiers.

## Get rid of the »Shared« folder – DONE!
Currently, there is an empty read-only »Shared« folder where files/folders shared _with_ you will appear. This is very confusing.
* [x] Instead, shares should by default directly go into the root folder.

## Ability to move and rename shares freely - DONE
* [x] As people arrange their files differently, one should be able to freely move and rename the root of the share. That is, folder and file name.

## Notify recipients and prompt to accept/decline shares
Currently, shared files are immediately added to your account, which can fill up your storage. Then they get synced via the desktop client which in turn fills up your computer space.
We should have a mechanism to notify people of incoming shares so they can accept or decline them.
That should also be configurable for admins for cases where people need to be in shares.

**Comment by DeepDiver1975** [comment]
@jancborchardt anything missing in here?

please either close or move to 8.1-next - THX

**Comment by jancborchardt** [comment]
Yep, all the original items are done. Other issues are tracked separately.
