### ISSUE TITLE
LDAP Feature request: custom Group-Member association LDAP attribute

### ISSUE THREAD

**Issue by ismailyenigul** [owncloud/core#4547]
In Advanced LDAP settings Group-Member association parameter accepts predefined values (uniqueMember,memberuid,member.) We have custom LDAP settings and use different ldap attribute. It would be great, if we can define custom ldap attribute name

**Comment by mohamedhagag** [comment]
@blizzz anyway to get zimbra or custom Group-Member attribute ?

any solution ?

**Comment by blizzz** [comment]
@mohamedhagag nothing on the horizon, and also I do not have a zimbra instance. If there is something special that needs to be done about it, then a pull requested should be provided to get this introduced. I don't see me implementing this in a foreseeable future, sorry.

**Comment by PVince81** [comment]
Isn't that possibly with "dynamic group membership" ? I'm not an LDAP expert but I remember checking out this fix from @alexweirig https://github.com/owncloud/core/pull/23344 and remembered seeing a "membership URL" attribute somewhere where one could specify an LDAP URL (or attribute?) to specify custom memberships ?

**Comment by alexweirig** [comment]
@PVince81 that's correct, but as far as I remember the code to support dynamic group membership was never added to the 8.2 release ... but maybe I just missed it.
Therefore I thought backporting it to 8.2 could be helpful.

**Comment by PVince81** [comment]
If the feature did not exist in 8.2, we don't backport features but only bugfixes.

**Comment by alexweirig** [comment]
@PVince81 OK no problem then

**Comment by PVince81** [comment]
Please reopen in the [user_ldap app repo](https://github.com/owncloud/user_ldap) if the issue persists with 10.0.4 and the latest version of the user_ldap app from the marketplace.
