### ISSUE TITLE
Feature Request: Allow different permissions for Subfolder  [$130]

### ISSUE THREAD

**Issue by prearisto** [owncloud/core#4579]
Issue 3515 is unjustly closed - this is a needed function, that I really cannot see how any company with structured data and user-restricted access could use this solution.

Example:
Customers - shared folder with all sales agents
Customers/customer_1 - shared folder with sales agent handling this [1] account and supervisor. That folder should be hidden from other sales agents.
Customers/customer_2 - shared folder with sales agent handling this [2] account and supervisor. That folder should be hidden from other sales agents.

So all users will see
Shared/Customers/
But each agent will see there only folders for his clients and supervisor will see them all (in same structure)
One sales agent will see
Shared/Customers/customer_1
Another will see
Shared/Customers/customer_2
And supervisor will see
Shared/Customers/customer_1
Shared/Customers/customer_2

How is that "way too complicated for user experience"?

**Comment by MTRichards** [comment]
This same conversation surfaced again, so it is still out there and may be something we need to look at.

**Comment by hodyroff** [comment]
https://github.com/owncloud/core/issues/4579
