### ISSUE TITLE
app database policy/rules. How apps should use the database.

### ISSUE THREAD

**Issue by kiranos** [owncloud/core#4591]
thought about app database policy/rules. It would be great to have limitations on what an app gets access to. IMO an app will have to create its own table in the db and only get read access to the other tables of the owncloud db. So that it cant update core tables or other apps etc.

**Comment by Xenopathic** [comment]
Apps are reviewed on the app store by hand, and we mark any unverified apps in the app listing. A misbehaving app will therefore not ever be marked as verified, so the 'policy' is effectively enforced.
