### ISSUE TITLE
[5.0.11RC1] Share link -- expiration date was set to past date -- link still valid

### ISSUE THREAD

**Issue by ser72** [owncloud/core#4649]
Expected behavior
Link is expired

Actual behavior
Link is accessible.  ownCloud shows the file as “Shared”.  Under shared tab, ownCloud seems to be unshared.

Steps to reproduce
1. Share a file via a link
2. Set an expiration date – by accident (on purpose) set it to an already expired date as below (current date is 8/29/13).
 
![share_1](https://f.cloud.github.com/assets/5174383/1051689/895eeafe-10cf-11e3-822c-2af2885d01ae.png)

3. In another browser (simulating a different user), go to the link.  Notice it is available even though it should be expired:

![share_2](https://f.cloud.github.com/assets/5174383/1051676/5c028246-10cf-11e3-9290-1a6d8f48213d.png)

 
Files can be viewed and downloaded.
4. Go back to ownCloud web page.  Top level on files shows it is shared.  However, when you select “share” there are no users listed and the “Share as Link” is not checked:
 

![share_3](https://f.cloud.github.com/assets/5174383/1051677/64634754-10cf-11e3-9de7-55b5aaedebff.png)

5. At this point, go back to the link and it has expired.

SUGGESTIONS:
1)	Gray out all dates prior to the current date so a user cannot accidently select a previous date
2)	Make sure the link is expired if the expiration date is passed

{"installed":"true","version":"5.0.15","versionstring":"5.0.11RC1"}
Ubuntu
apache
Internet Explorer 9, Google Chrome, Mozilla firefox

**Comment by wshadow** [comment]
@bantu does removing yourself from the issue mean that everything is ok and this can be closed?

**Comment by DeepDiver1975** [comment]
closing - has been verified to work now as designed - see https://github.com/owncloud/core/issues/4649#issuecomment-56083111
