### ISSUE TITLE
Feature Request: Alternate Storage limits for External Storage

### ISSUE THREAD

**Issue by jeffclay** [owncloud/core#4668]
Currently, the users local storage restriction is applied to external storage paths/locations. It would be great to be able to either disable storage limits completely for external locations or to be able to set alternate storage restrictions per external storage location much in the same way local storage restrictions are handled.

If I haven't made this very clear, please ask any questions and I will elaborate.

Thanks

**Comment by PVince81** [comment]
not implemented, reopening
