### ISSUE TITLE
File upload in browser

### ISSUE THREAD

**Issue by butonic** [owncloud/core#4767]
With https://github.com/owncloud/core/pull/4766 we will add proper conflict handling back to OC. But that is only a fallback mechanism that triggers when a conflict arises.

We can do better:
- [x] If uploading to the filelist check for conflicts before uploading. On conflict show a simple dialog like [win8](https://www.youtube.com/watch?v=4zbY6vr4DK4) showing only the number of conflicting files and allowing the user to choose a general resolution: skip all conflicts, overwrite all files, choose which files to keep (and show the conflicts dialog) or cancel upload.
- [ ] When file versioning is enabled never show any dialog and always overwrite the file on the server. If the user made a mistake he can always get back the old version from the file history. (This is how dropbox does it)
- [ ] Use [xdg_user_dirs](http://www.freedesktop.org/wiki/Software/xdg-user-dirs/) standard to upload files to meaningful default directories from an upload button in Apps like Pictures and Music: 
- [ ] Render progress bar in file list row, tracked in https://github.com/owncloud/core/issues/991

**Comment by PVince81** [comment]
The first checkbox was implemented in 8.2.2, see https://github.com/owncloud/core/pull/19417

Moving the rest to 9.1
