### ISSUE TITLE
Feature Request due to inconsistent behavior of passwort setting while using LDAP

### ISSUE THREAD

**Issue by dietmaroc** [owncloud/core#4833]
Feature Request: Inconsistent behavior of passwort setting while using LDAP
### Expected behaviour

If a user authentication goes over LDAP, then other ways of setting user and password should be linked to LDAP also or
not be possible / deactivated.
It would be usefull to switch this section invisible (by CSS) while LDAP is used. 
### Actual behaviour

If a user is added via LDAP, then inside the admin backend it's still offered to change the password 
via the "normal" user administration: Personal --> Password. But this way of administration isn't working any longer 
because of LDAP connection. 
### Steps to reproduce
1. connect your system to an LDAP / AD Server
2. got to the admin settings: Personal-->Password
3. Try to change the password here
### Server configuration

hasn't been reproduced by myself but by Holger and Matt
#### Web server error log

```
Insert your webserver log here
```
#### ownCloud log (data/owncloud.log)

```
Insert your ownCloud log here
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by butonic** [comment]
oc uses a read only connection to ldap. As a work around you can hide the change password section in the personal settings by adding something like this to your theme:
```css
#content.app-settings #passwordform.section {
	display: none;
}
```

cc @dercorn

**Comment by PVince81** [comment]
Please reopen in the [user_ldap app repo](https://github.com/owncloud/user_ldap) if the issue persists with 10.0.4 and the latest version of the user_ldap app from the marketplace.
