### ISSUE TITLE
Design forward: Admin settings for apps should go into the apps management

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#4944]
Currently we have an »Admin« section which is free for population by apps just like the »Personal« section used to be for app settings.

Enabling or disabling an app is also a setting, the most fundamental one. All the other app settings are specifics and should be in the same place with enable/disable as well as the app info text.
Let’s say you want to enable LDAP, you have to first go to Apps to enable it, then know that there are admin settings for it, then go to Admin and find them. That’s cumbersome.

Hence we should move the admin settings of apps into the apps management. Then we can also get rid of the »Admin« page.

All the admin settings which have no specific app bound to it should go to the »Personal« page of admins. The page should be renamed to »Settings« and the admin-specific settings should be below an »Administration« header, with a notice like »This will affect all users of this ownCloud«. These are for example ZIP download size, HTTPS enforcement, Cron and Log.

What do you think @karlitschek @MTRichards @DeepDiver1975 @butonic @blizzz @schiesbn @owncloud/designers ?

**Comment by DeepDiver1975** [comment]
moving this to the backlog - neither critical nor broken at the moment

**Comment by jancborchardt** [comment]
Yep – something we _could_ think about for the future. But backlog is ok since it would be quite a big change.

**Comment by MartinDesigner** [comment]
Regarding only to design, look at this stuff:
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, as a supplement, however as a main point try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. You can even design UI mockups for mobile as for standard display (html, js, css always generating without any coding required from you). Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by jancborchardt** [comment]
@MTRichards I’d request this for consideration for 9.1 or the release after that. Currently it’s very confusing where app settings are, and the admin settings just get more stuff piled into them and end up being a dump.

**Comment by karlitschek** [comment]
Hmm. Let's discuss this. There are pros and cons for both ways.

**Comment by jancborchardt** [comment]
Yep – I listed my reasoning above and still stand by it. What are other pros and cons? cc @DeepDiver1975 @PVince81

**Comment by MTRichards** [comment]
I can get behind this, but it does require a significant bit of discussion - and the other questions is why now? Is there something about what we have, or need, or something that makes right now the time to do it? OR, alternatively, is this just a continued iteration? It feels a lot bigger than the more recent changes, so it doesn't seem to be an iteration, more a rebuild...

**Comment by jancborchardt** [comment]
It’s a continued iteration, a refinement of information architecture. It’s also a change I have been thinking about since a long time. As you can see, this issue was opened by me more than 2 years ago.

**Comment by DeepDiver1975** [comment]
one day -> backlog

**Comment by DeepDiver1975** [comment]
we are reorganizing settings -> #26449 -> close
