### ISSUE TITLE
Group Background Interface should work with ids

### ISSUE THREAD

**Issue by frisco82** [owncloud/core#4972]
Currently Group Backends use the name as the only identifier, that is great for the basic setup and Backend provided but aside of names being a really bad id as they can change over time and not great for DB indexes, there are use cases where different groups can have the same name.

In our case we are binding the backend with our external app backed where the users can create their own groups and thus several users can have a group called 'friends' and this is incompatible with the current interface.

Think of it as your Gmail group for 'friends' and it makes sense to be able to share files or events with your own groups.

Anyway I am not asking to change the current DB group backend and UI to support that only add a getDisplayName to group backend interface and add the corresponding functions for searching as they are in the User Backend and use them where is needed (Share App mainly, not sure how it deals now with group renaming).

**Comment by MorrisJobke** [comment]
Maybe something for #12998
