### ISSUE TITLE
OC_FileChunking on external file systems

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#4997]
The current implementation of OC_FileChunking is storing the chunks in the servers file cache (hidden/private folder on the server).

After all chunks have been received the file is reassembled and moved to the final target location.

While this approach seems valid for local filesystems this can case issues with respect to external filesystems and big files, because the final move of assembled file will consume some time.

From the overall system behavior it might be interesting to move the chunks already to the external filesystem.

My suggestion would be to store the chunks already in the target file but name it differently, append the .part and even make it hidden if possible.

This approach would speedup the process on the local filesystem as there is no reassembly step which as of today adds additional execution time.

@karlitschek @bartv2 @icewind1991 @danimo @dragotin 
Please add your comments - THX

**Comment by PVince81** [comment]
Some additional ideas coming from https://github.com/owncloud/core/issues/13157.
When the ext storage server is ownCloud (ownCloud backend or server to server sharing), we might not need part files at all. So every storage should also be possible to tell whether they need part files or not.

I suspect that Dropbox might not need part files either if their upload mechanism is atomic as well. I don't think that they'll directly overwrite the current file like FTP or SMB would do. This could save the part file step.

**Comment by VincentvgNn** [comment]
@PVince81 
Help, I cannot upload and share large files of 20-50MB !!
Please judge whether my problem fits to this issue.

I have OC server 7.0.4 running on a 5GB space at a webhost. The connection is very slow, upload speed 20 - 60 kB/sec. When uploading these large files, I get at about each 6 min a "Connection closed" and "Operation cancelled" error message.
From an OC admin account I have 8 folders r/w shared with client 1 and client 2 (without encryption).
Client 1: Win XP and OC version 1-7.1
Client 2: Win 8.1 and OC version 1.8.0.4536-nightly20150108
Data size: 280 MB, 1600 files, 400 folders.
The large 20 MB+ files are uploaded at the end when most of data has already been shared. It doesn't matter much whether client 1 or client 2 starts uploading all this data. The indexing after a reconnect takes quite long (1-2 min.).
The server cash folder of the uploading client get's many "chunking" files (100 MB). In the attached picture you can see the size and the 6 min. timing interval of these files. The original file is 20.951 kB. All chunking files are just a little bit to small for completing the final file. When uploading from the Win XP side the upload speed is slower and the chunks are smaller (about 2-8 MB).

![150213 oc chunking files](https://cloud.githubusercontent.com/assets/7522929/6179902/48c120b4-b31e-11e4-9428-caee7e73cca8.jpg)

**Comment by PVince81** [comment]
@VincentvgNn it mostly looks like the timeout makes it unable to finish the chunks ? Are you using php-fpm which auto-kills PHP processes when the network connection is broken ? (mod_php doesn't kill the PHP process, it would continue working)

**Comment by VincentvgNn** [comment]
@PVince81 
Thanks for your response.
Where can I find that php-fpm or mod_php setting? Within the OC server settings (as downloaded and set by the auto-installer) or outside?
I just tried phpinfo.php and found PHP-version 5.5.21 and a lot more, but nothing about these settings. And above, I would not be able to change something there.

Shouldn't a killed process be able to recover by using the available "chunking" files?
As it is now the cashed files seem to stay forever.

**Comment by PVince81** [comment]
@VincentvgNn it's not a setting it's your setup. phpinfo might tell you.

If the chunk files aren't complete there is no way to recover them. The client should then resend the chunk again, with a different transaction id (@dragotin can you confirm?). This would leave canceled chunks lying around, which is a known issue.

**Comment by VincentvgNn** [comment]
@PVince81
php-fpm was introduced from PHP 5.3.3 onwards. So I bet that I have php-fpm and and no more mod_php. Phpinfo mentions the authors for CGI / FastCGI and FastCGI, but nothing about php-fpm or mod_php.
I seem to experience auto-kill for PHP processes at a broken connection.

**Comment by VincentvgNn** [comment]
@PVince81 
On Feb. 13th you confirmed that chunks lying around is a known issue.
Today I tested server 8.0.2 and client 1.8.0. There was a moment where the file transfer ran very slow resulting in quite some interrupts and producing many chunks. The chunks occupied more space than the good files!
Is anyone working on solving the problem of chunks that should be automatically removed after some time?

**Comment by PVince81** [comment]
The chunk cleanup will be a background job starting with 8.1: https://github.com/owncloud/core/pull/14500

**Comment by PVince81** [comment]
We're past feature freeze => 9.0.

**Comment by DeepDiver1975** [comment]
closing this in favor of #20118
