### ISSUE TITLE
Restrict password change for guest account

### ISSUE THREAD

**Issue by ronnystandtke** [owncloud/core#4998]
We have set up an ownCloud installation with a single guest account for our external users. They access ownCloud via WebDAV. This works great minus one feature: One of our guests could just change the guest account password and this way exclude all the others.

There is already a small code snippet in the forums to support this feature (without any administrative frontend):
http://forum.owncloud.org/viewtopic.php?f=23&t=16776

Would it be possible to implement this feature in future ownCloud versions?

**Comment by butonic** [comment]
@DeepDiver1975 @PVince81 covered by the guest app, closing

**Comment by Henk1060** [comment]
Hy tim4dev
where do i insert these lines in the settings/changepassword/controller.php ?

Thank you very much
