### ISSUE TITLE
Links not visually recognizable (red-green blind user)

### ISSUE THREAD

**Issue by despens** [owncloud/core#5021]
![0136](https://f.cloud.github.com/assets/571494/1227367/2698b8e6-2790-11e3-846b-9cd5a220d295.png)

I don't know if you guys can distinguish the "text color" from the "link color" here, but I certainly cannot (I suffer red-green blindness).

Within longform text pages like the admin panel, I can make out stronger contrast for links, but in between lots of different widgets it is just not visible for me and I have to hover over the textual elements to see what they can do.

How about some classic underlines and/or bright blue?

**Comment by DeepDiver1975** [comment]
@jancborchardt covered by your recent work regarding accessibility? THX

close or move to 8.1 milestone please - THX

**Comment by jancborchardt** [comment]
This specific issue in the Calendar has been fixed. The links are now in input fields to make them easier to copy.

When there are other issues of links not being visible, please let us know in new issues. :)
