### ISSUE TITLE
"hasUpdated" function is not being called from the OC root folder for mounted FSs

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#5036]
### Expected behaviour
When you click in the OC root folder (/index.php/apps/files) the hasUpdated function is called for each mounted storage inside the root folder so that we can know that there are changes inside the mounted storage.

### Actual behaviour
That function is not being called for the mounted storage (just for local storage) so other mounted storages don't report a change until we enter in them.

### Steps to reproduce
1. Mount an external FS under the OC root. You'll access to the OC root in the url "/index.php/apps/files" and to the external FS in "/index.php/apps/files?dir=//out" (change the directory name if needed)
2. Add a new file to that external FS outside OC (don't use OC to upload the file)
3. Go to the OC root dir "/index.php/apps/files"
4. Check that the mtime of the "out" folder hasn't changed.
5. Go inside the "out" folder and back and check that the mtime is now the correct one

### Server configuration
Web server: apache
Database: sqlite3
PHP version: 5.3.10
ownCloud version: 5.0.11RC2

### Client configuration
Browser: chromium and firefox

**Comment by timm2k** [comment]
Until sync of external storages will not work reliable it would be a workaround for us to exclude sync of external storages. Could this excludes be done by modifying plugins at server-side or use file-firewall eg?

**Comment by PVince81** [comment]
The ext storage mount points can be excluded by using selective sync in the client: you can select what folders to sync there.

**Comment by PVince81** [comment]
@icewind1991 @DeepDiver1975 if we introduce external storage options as per https://github.com/owncloud/core/issues/12216 we could add an option "do a full rescan of this storage on a regular interval" ? The interval should probably be configurable so admins could decide how important/timely the change detection needs to be.

Then the full rescan would be done in a background job (cron).

**Comment by PVince81** [comment]
This would at least solve the potential performance issue mentionned here https://github.com/owncloud/core/issues/5036#issuecomment-29617445 in case of multiple storages. Assuming that not all ext storages are important.

Additionally this means that the option is only needed for storages that are used **outside** of ownCloud. If some storages are using exclusively through ownCloud, they wouldn't need that option and wouldn't cause any performance issue.

**Comment by timm2k** [comment]
@PVince81 thanks for your reply. I can't tell 1000+ users to use selective sync to disable their whatever-named external storage. I need a centrally managed workaround.

**Comment by PVince81** [comment]
@icewind1991 how about a new option for "occ files:scan" to scan a specific storage id ? (like an external storage mount point). Then admins could put this in a cron job as a workaround to force rescan every 10-15 minutes.

**Comment by PVince81** [comment]
If I remember well this issue here was mostly about calling "hasUpdated()". So at least the CLI tool (or whichever solution we use) could at least run hasUpdated() on every known external storage roots.
Whether to force a full scan could be an additional option.

**Comment by theroch** [comment]
Workaround for local SMB shares from #8892:
The workaround is to run the command line tool ./occ files:scan --all in a cron job to force rescanning / checking for updates on the remote server.

**Comment by PVince81** [comment]
Well thing is that the scanner will rescan all home folders, not only the remote ones.
Ideal would be at least to have what I suggested here: https://github.com/owncloud/core/issues/5036#issuecomment-77127387

**Comment by khlem** [comment]
this method : ./occ files:scan --all does not function when the share is mounted with SMB / CIFS.
The files modification are not update in Owncloud Client, we must add a new file or navigate in Website to force the update of Client.

**Comment by directict** [comment]
We only use SMB for WEB access outside company + sharing with ppl outside our company, having it synchronised is not possible casue its never up2date on your laptop because changes are not seen by the client.

Just wondering, how does the enterprise version do this? (in case of SMB?)

**Comment by khlem** [comment]
"Just wondering, how does the enterprise version do this? (in case of SMB?)"

Same problem between enterprise and community version :( .

**Comment by directict** [comment]
OK.. i thought in the enterprise edition it was not an issue...

**Comment by khlem** [comment]
Nop i tested this version and the same error appears.

The core is the same between the community and enterprise edition.

**Comment by directict** [comment]
Ok, i thought those were 2 different plugins:

https://owncloud.com/features/#WindowsNetworkDrive

where the "SMB/CIFS" feature of the Community Edition is available here:
https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/external_storage_configuration_gui.html#smb-cifs

**Comment by PVince81** [comment]
They are different plugins, but detecting remote updates is a general problem for every external storages, nothing specific to the plugin implementations, more something in core.

**Comment by directict** [comment]
ok that makes sense thanks, in 8.1 there will be improvement right?

**Comment by PVince81** [comment]
8.1 will contain some new switches for external storages to tell how often the rescan needs to be done (never, detect changes (default), on every access).

But I'm not sure whether this will fix update detection when someone changed a file very deep in the folder structure of an external storage (from outside ownCloud).

@icewind1991 will the "Always" mode rescan the whole external storage regardless of update detection ?

**Comment by directict** [comment]
Yes, i read everywhere that the SCAN function for SMB will not fix it indeed. its good to see you are working on this.. i think loads of people use ownCloud for SMB access.. atleast, thats what we like the most!

**Comment by icewind1991** [comment]
8.1 will not fix this issue

**Comment by khlem** [comment]
This is not a good news.

When do you think this issue will be resolved ?

Same issue in enterprise version, we can't use the system with SMB/CIFS and Owncloud Client.

Strange problem like this in a cloud system.

Thank you for your efforts.

Regards,

Clément.

**Comment by PVince81** [comment]
The main ticket about update detection https://github.com/owncloud/core/issues/11797 has been scheduled for 8.2, so there is hope.

**Comment by Xenopathic** [comment]
We have a ticket about update detection -> close
