### ISSUE TITLE
Using csync for external storage / fed shares syncing

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#5225]
To improve the performance of syncing data when mounting another ownCloud instance, how about using csync instead of a direct WebDAV connection ?

Could csync also sync with other providers ?

This would be the equivalent of having mirall/csync or dropbox running on a server along with ownCloud and auto-syncing inside of "data/files/mountpoint" directory using their own optimized algorithm.

If the target server is offline, the files could still be accessed and be synced later.

Let's discuss whether it makes sense at all. I know that there might be a few technical challenges, like potentially having to port csync to PHP for providers that don't have it...

@schiesbn @karlitschek @DeepDiver1975 @icewind1991 @dragotin

**Comment by PVince81** [comment]
With mirroring, conflicts could occur. If at some point we'd allow syncing conflict files anyway and provide a good UX for conflict resolution in the web UI (somewhat related https://github.com/owncloud/client/issues/3222), then conflicts with ext storage wouldn't be such a big issue any more.

**Comment by PVince81** [comment]
Note: mirroring could also be useful for server to server sharing aka federation, especially when going over the internet where the connections can be slower.

**Comment by PVince81** [comment]
@etiess to mount another ownCloud, please check out the "External Storage" app and use the "ownCloud" type to mount another ownCloud. Please note that this (the current version) is NOT a mirror, it mounts ownCloud directly.

**Comment by jwillmer** [comment]
Is this still on the roadmap or is it already solved (by another issue)? I am interessted in it as well.

**Comment by hodyroff** [comment]
It is still in the backlog/pool of ideas which might make it eventually in when more people make a good case why its needed and what the use case for it can be and of course help with volunteering time to program it.

**Comment by PVince81** [comment]
Also see https://github.com/owncloud/core/issues/11839 and especially my comment regarding conflict files: https://github.com/owncloud/core/issues/11839#issuecomment-351105376.
