### ISSUE TITLE
Mounting external storage from the files app

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#5240]
Some idea: making it possible to mount external storage from the files app ?

Potential steps:
1. User opens file app
2. User clicks on "New"
3. User picks "External Storage" in the menu
4. Popup (or dropdown) appears where the user can pick the type of external storage
5. User types in name of directory
6. User inputs additional settings for external storage
7. User clicks apply
8. System tests the connection 
9. System creates a subdir in the current dir with the name from step 5
10. System adds the mountpoint into the config (mount.json)
11. Popup closes

Let's discuss @karlitschek @jancborchardt @schiesbn

But before we do this we should probably make sure the external storage feature works smoothly because this would "advertise" the feature to users (if that app is enabled by default)

**Comment by jancborchardt** [comment]
Closing this in favor of https://github.com/owncloud/core/issues/11517
