### ISSUE TITLE
File is deleted when it shouldn't after trying to move a file (from a shared folder) with the same name as one that is already in root

### ISSUE THREAD

**Issue by purigarcia** [owncloud/core#5251]
### Expected behaviour
The file "photo.JPG" shouldn't be deleted from root and it is been deleted
The file "photo.JPG" shouldn't be deleted from folder "A" inside "Shared" folder and it doesn't

### Actual behaviour
The file "photo.JPG" is deleted from root when it shouldn't

### Steps to reproduce
1. There are two users in the server (user1 and user2)
2. In the server, log in owncloud as user 1
3. Share a folder called "A" with user2. 
4. Give him only update permission
5. Log in own cloud as user2
6. Upload in root a file, for instance photo.JPG
7. Now using webdav protocol, try to move a file called "photo.JPG" from a shared folder "A" to root. Notice that you don't have the correct permission so in the end the file isn't going to be moved.
We are going to see do it using poster (complement in firefox) (screenshot is attached)

         * URL:server/remote.php/webdav/Shared/A/photo.JPG
         * User: user2 
         * password:
         * Action:MOVE
         * Headers
                  - Destination: server/remote.php/webdav/photo.JPG
                  - Overwrite: T
![screen shot 2013-10-09 at 6 40 39 pm 2](https://f.cloud.github.com/assets/4538201/1304060/00a3613a-3173-11e3-9fc0-e180d5b2a604.png)
5. An error 403 is sent
6. In the server, logged as user2 account, refresh the account and then photo.JPG is deleted from root when it shouldn't

### Server configuration
Operating system: openSUSE

Database: SQLite 3

ownCloud version: {"installed":"true","version":"5.80.8.1","versionstring":"6.0 pre alpha","edition":""}

### Client configuration
Browser: Chrome

Operating system: MaOs 10.7.5

**Comment by DeepDiver1975** [comment]
we should reevaluate this now in master with the new sabredav implementation -> 8.2

**Comment by PVince81** [comment]
Is this still happening with 7.0.7, 8.0.5 or 8.1 ? (8.1 has the new sabredav implementation)

**Comment by purigarcia** [comment]
@davitol could you check it? thank you

**Comment by davitol** [comment]
:+1:
Tested in 8.1.1 ("version":"8.1.1.3","versionstring":"8.1.1") and it works fine :white_check_mark: 
Tested in 8.0.5 ("version":"8.0.5.2","versionstring":"8.0.5") and it works fine :white_check_mark:
Tested in 7.0.7 ("version":"7.0.7.2","versionstring":"7.0.7") and it works fine :white_check_mark:

**Comment by PVince81** [comment]
:-1: still happening in 8.1.1. I used cadaver to move "/A/test.txt" to "/test.txt" as recipient. Even though I have no move permission for that file, the file "/test.txt" disappeared.

@davitol I guess you probably misread some of the steps.

**Comment by PVince81** [comment]
There are limitations in Sabre that makes it close to impossible to prevent it to auto-delete the target file. Raised here: https://github.com/fruux/sabre-dav/issues/705

**Comment by davitol** [comment]
@PVince81 Which permission did you marked as "update permission" in 8.1.1? When I tested it, the did not dissapear. Maybe you're right and I made a mistake in one of the steps...

**Comment by PVince81** [comment]
@davitol when sharing the folder with "user2", I unchecked all the checkboxes in the share entry and only kept "change" enabled.

**Comment by davitol** [comment]
Tested again and the file dissapears checking checkboxes can edit--> change ("version":"8.1.1.3","versionstring":"8.1.1","edition":"Enterprise") :cry:

**Comment by PVince81** [comment]
The sabre lib was updated with https://github.com/fruux/sabre-dav/issues/705.
Do we want to update the Sabre library at this point, past feature freeze ?

Updating the lib is only the first step, additional fixing will be needed in OC to be able to prevent deletion. Also this will not be backportable because past OC versions will also require updating the Sabre library.

@DeepDiver1975 @cmonteroluque @karlitschek

**Comment by karlitschek** [comment]
which sabredav version contains the fix? updating so late is bad. but the bug is also bad. :-(

**Comment by PVince81** [comment]
According to the labels in the PR https://github.com/fruux/sabre-dav/pull/714 it was fixed in 2.0, 2.1 and 3.0.

**Comment by PVince81** [comment]
To be more precise, I checked the changelogs:
- 2.1.7: http://sabre.io/blog/2015/sabre-dav-2.1.7-released/
- 3.0.4/5: http://sabre.io/blog/2015/sabre-dav-3.0.4-released/

Master and 8.1 both use 2.1.6.

**Comment by PVince81** [comment]
It looks like 2.1.7 was only release because of that specific fix we need. :smile:

**Comment by karlitschek** [comment]
I guess an update from 2.1.6 to 2.1.7 should be fine. I'm voting to do this. @DeepDiver1975 What do you think?

**Comment by DeepDiver1975** [comment]
agreed ... will take care

**Comment by rullzer** [comment]
PR in #19609

**Comment by rperezb** [comment]
@SergioBertolinSG can you please take care of this one?
