### ISSUE TITLE
Allow formatting/markup in app description

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#5322]
Currently the app description in the apps list has the following issues:
1. Newlines are not recognized which makes blocks of text look ugly and unreadable
2. Links aren't converted to links
3. Previews aren't clickable

It was suggested to use bbcode or HTML (or a limited allowed subset of it)

CC @karlitschek @schiesbn

**Comment by oparoz** [comment]
The solution is to support Markdown via https://github.com/chjj/marked

**Comment by karlitschek** [comment]
yes. markdown would be nice. unfortunately we are after feature freeze for 8.1 :-(

**Comment by DeepDiver1975** [comment]
I'm moving this to the backlog - pull request to implement this is welcome at any time - THX

**Comment by jancborchardt** [comment]
Can we at least handle line-breaks properly? As in, properly render them as linebreaks instead of ignoring them – hence requiring double linebreaks which results in huge descriptions. See the Galleryplus description, ref https://github.com/owncloud/gallery/pull/148#issuecomment-126596723

**Comment by cmonteroluque** [comment]
@DeepDiver1975 @jancborchardt at this point without a PR, I think this moves to 9.0

**Comment by DeepDiver1975** [comment]
Maybe even backlog - this is nice to have - but we can perfectly live without it

**Comment by PVince81** [comment]
As far as I remember this is done @DeepDiver1975 ?

**Comment by DeepDiver1975** [comment]
yes - https://github.com/owncloud/core/pull/28191
