### ISSUE TITLE
Message for LDAP test

### ISSUE THREAD

**Issue by ubellavance** [owncloud/core#5355]
It would be a good idea to differentiate the success and failure error messages that pop-up when clicking the test buttton in the LDAP config.  They are very similar so I thought I was doing it wrong for a while until I realize the message changed.  Maybe put the failure in red and leave the success in blue?

Thanks,

**Comment by MorrisJobke** [comment]
The error handling in the LDAP wizard improved a lot since this issue was reported -> I will close this until something more specific to fix pops up.
