### ISSUE TITLE
"Login failed" message in owncloud log because SFTP server is unavailable

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/core#5377]
I get this message two times for each request and after a while browsing my ownCloud it appears every 2 seconds and any ownCloud page/app doesn't load anymore. I restarted apache and it loads (still the 2 log messages per request). After the restart I look into the personal settings page and the SFTP mount is marked red.

```
{"app":"core","message":"Login failed","level":3,"time":"2013-10-17T09:02:02+00:00"}
{"app":"core","message":"Login failed","level":3,"time":"2013-10-17T09:02:05+00:00"}
{"app":"core","message":"Login failed","level":3,"time":"2013-10-17T09:02:07+00:00"}
{"app":"core","message":"Login failed","level":3,"time":"2013-10-17T09:02:10+00:00"}
{"app":"core","message":"Login failed","level":3,"time":"2013-10-17T09:02:12+00:00"}
{"app":"core","message":"Login failed","level":3,"time":"2013-10-17T09:02:14+00:00"}
{"app":"core","message":"Login failed","level":3,"time":"2013-10-17T09:02:16+00:00"}
```

```
PHP 5.5.4 (cli) (built: Sep 19 2013 17:10:06) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2013 Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans
```

cc @icewind1991 @MTGap

**Comment by DeepDiver1975** [comment]
We have to touch ftp/sftp in 8.2

**Comment by Xenopathic** [comment]
This would be fixed by the combination of #13641 to provide stateful storage status and #13390 to throw the right exceptions to trigger that.

**Comment by PVince81** [comment]
https://github.com/owncloud/core/pull/13390 is the way to go which is scheduled for 9.0. Moving this ticket to 9.0 too.

**Comment by PVince81** [comment]
@MorrisJobke @cmonteroluque I set the sev to medium, feel free to change if you think this is more critical.

**Comment by cmonteroluque** [comment]
@PVince81 @MorrisJobke That seems right to me

**Comment by PVince81** [comment]
This should already be mitigated by the "Availability" storage that will only try the login once every 15 minutes.
