### ISSUE TITLE
Make it possible to request an auth token (nonce)

### ISSUE THREAD

**Issue by danimo** [owncloud/core#5453]
For the client to provide a seamless experience, it would be nice if it could request an one-time auth token from the server which would act as a replacement for username and password to launch a browser session. This could be used for a number of things, most prominently "Open Folder in ownCloud" without additional login.

**Comment by PVince81** [comment]
@ChristophWurst oh look what I found.

Duplicate of one of your tickets ?

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/core/issues/24794

**Comment by ogoffart** [comment]
Reopening. We need this for https://github.com/owncloud/client/issues/633
This is not the same as oauth, which is about authenticating the client.  It is about an already authenticated client opening a browser on owncloud whithout having tio type the password again.

As mentioned before, the spec is in https://github.com/owncloud/client/issues/633#issuecomment-52024677

**Comment by micbar** [comment]
@michaelstingl is this still relevant?

Why isn't that covered with single sign on?

**Comment by michaelstingl** [comment]
It's solved with true SSO, but only very few ownCloud instances I know (and desktop environments), have true SSO configured.

Nearly every time I open the web UI from the client, I have to login again:

![CleanShot 2021-09-16 at 13 05 27@2x](https://user-images.githubusercontent.com/214010/133602817-ffe1ba4a-7081-418a-aa4e-7c4549233bec.png)

Maybe there's a solution with OIDC or we solve this on oCIS…
