### ISSUE TITLE
The warning message for when a user is running out of space is not explicit enough

### ISSUE THREAD

**Issue by eddie-dunn** [owncloud/core#5475]
When logging in to my owncloud account, I got this message:  `Your storage is almost full (94%)`.

Since I have set the account to have 10GB available storage and I was nowhere near that limit,  I assumed there was a bug in ownCloud. However, after further investigation, I realized that I was seeing this message because my root partition was almost full, not because my account had used up its allotted share.

I've also discovered that on my user accounts `Personal` page, there's this gem: `You have used 1.7 GB of the available 2 GB`. 

These messages are very misleading, as they nowhere state __which__ storage they are referring to -- the user storage quota, or the total available storage. 

I propose that they should be more explicit, in order to avoid this kind of confusion.

**Comment by DeepDiver1975** [comment]
@pellaeon where are we with this? Please get back to us - THX

**Comment by pellaeon** [comment]
I remember at the conf asking @PVince81 about this, he said this is not a priority, so we did not discuss more on this.

**Comment by DeepDiver1975** [comment]
moving this and the pr to backlog then - feel free to catch up on this at any time - THX
