### ISSUE TITLE
[Sharing] Avoid loop shares

### ISSUE THREAD

**Issue by dragotin** [owncloud/core#5491]
Consider this szenario:

```
User Tom shares a directory with the two users Betty and John. 
Now these both decide to share this folder with Carl. So the 
same shared folder would appear twice on Carls data set. 
```
That must not happen. The server has to check if the shared folder is already there at Carl.

**Comment by PVince81** [comment]
Just observed a similar case today on master:
1. user1 shares "test" with user2
2. user2 shares "test" with user3
3. user3 shares "test" with user1

Now user1 has two folders "test" and "test (2)" with the same contents.
If you move then rename "test (2)" you can use it almost like a symlink/hardlink :wink:

**Comment by PVince81** [comment]
There was a discussion to change how reshare works: https://github.com/owncloud/core/issues/9058
Basically have a single list of people who have access to the folder instead of having a reshare chain.

**Comment by PVince81** [comment]
I suggest to defer this to after https://github.com/owncloud/core/issues/9058 is implemented (possibly 8.2)

**Comment by MorrisJobke** [comment]
#9058 was moved to 9.0 -> move this too.

**Comment by DeepDiver1975** [comment]
reshares will die in 9.0 -> closing. THX @dragotin
