### ISSUE TITLE
Error page for missing/broken apps

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#5508]
When an app fails, can't start and/or throws an exception, a blank page is shown.

It would be good if it could still load the navigation but show an exception / error message instead.
It would look a bit less broken, at least the user could navigate away instead of wondering too much.

**Comment by PVince81** [comment]
First step is to prevent hard fail for missing JS/CSS: https://github.com/owncloud/core/issues/14689

Next step is trying to detect errors like missing classes or such.

I noticed that `require_once` propagates exceptions that are thrown within the required script.
However if that error is "Class not found", it will fail and die there without giving us a chance to catch the error.

Maybe there's a way to tweak the autoloader to throw a custom exception instead of a fatal fail: http://stackoverflow.com/questions/4421320/why-doesnt-php-catch-a-class-not-found-error

**Comment by jancborchardt** [comment]
Is this possible with PHP @PVince81 @LukasReschke? Then we should indeed do that to make ownCloud more failsafe.

**Comment by PVince81** [comment]
The white page has already been replaced by a plain exception where possible.

Syntax errors or errors on `require_once` cannot be detected or caught, so nothing we can do here.

As for exceptions happening in "appinfo/app.php" and others, the app loader already automatically disables the app.
