### ISSUE TITLE
Shared file (with all the permissions) can't be moved

### ISSUE THREAD

**Issue by purigarcia** [owncloud/core#5594]
### Expected behaviour
File should be moved

### Actual behaviour
File can't be moved

### Steps to reproduce
1.	There are two users in the server (user1 and user2)
2.	log in owncloud as user1:
	* On the root upload a file and call it: doc.pdf
3.	Share the file called "doc.pdf" with ALL (update, delete and share) permission with user2.
4.	Log in as user2
5.	Now using webdav protocol, move a file called "doc.pdf" which is inside folder "Shared" to root.  Notice that you have the right permission to do this.

	We are going to see do it using poster (complement in firefox) (screenshot is attached)

        * URL:server/remote.php/webdav/Shared/doc.pdf

        * User: user2 

        * password:

        * Action:MOVE

        * Headers

              - Destination: server/remote.php/webdav/doc.pdf

              - Overwrite: T

![screen shot 2013-10-29 at 9 40 24 am 2](https://f.cloud.github.com/assets/4538201/1426752/3a72e78e-4076-11e3-9a6c-fce3d7c80997.png)

6. An 403 error is shown when it shouldn't because the file has all the permissions, so it should be moved

### Server configuration

Owncloud version: It was tested in daily
{"installed":"true","version":"6.0.0.2","versionstring":"6.0 beta 1","edition":""}

### Client configuration
Browser: Firefox
Operating system: MaOs 10.7.5

**Comment by DeepDiver1975** [comment]
related to https://github.com/owncloud/core/issues/5251 - maybe even the same issue? @purigarcia

**Comment by PVince81** [comment]
>The things is that maybe it doesn't make sense to move a shared file from "Shared" folder as you said before.

Yes, this wasn't allowed in OC 6.
Since OC 7 shared files/folders can be moved freely.

Closing.
