### ISSUE TITLE
Replace "OC\Files\Type\Detection" with "Symfony\Component\HttpFoundation\File\MimeType\..."

### ISSUE THREAD

**Issue by bantu** [owncloud/core#5600]
Refs #5516

Either use `Symfony\Component\HttpFoundation\File\MimeType\...` in `OC\Files\Type\Detection` or remove `OC\Files\Type\Detection` completely.

See http://api.symfony.com/2.3/Symfony/Component/HttpFoundation/File/MimeType.html

**Comment by bantu** [comment]
Owncloud master does currently not depend on HttpFoundation. I believe it has been available earlier, but not sure.

**Comment by bantu** [comment]
@LukasReschke Can you please have a quick look at this? It might be no longer necessary.

**Comment by DeepDiver1975** [comment]
I'm pretty fine with our current mime type detection - I see no need to change this at the moment -> backlog

**Comment by MorrisJobke** [comment]
> I'm pretty fine with our current mime type detection - I see no need to change this at the moment -> backlog

We should care about this once we have a specific issue with our current solution. Let's close it as it is working just fine right now.
