### ISSUE TITLE
[OC6Beta1] Upload 0 byte file hangs IE10

### ISSUE THREAD

**Issue by ser72** [owncloud/core#5604]
**Expected behavior:**
Empty file to be uploaded to ownCloud

**Actual behavior:**
ownCloud hangs.  Progress bar appears with "Cancel Upload" button
The only way to recover is to Cancel the upload

**Steps:**
1) On PC, create a 0 byte file
2) Either drag and drop or upload directly into OC6 browser

{"installed":"true","version":"6.0.0.2","versionstring":"6.0 beta 1","edition":""}

IE 10 on Windows 7
Works in Mozilla Firefox and Chrome

**Comment by Xenopathic** [comment]
This definitely doesn't happen with master on IE 11, in case anyone is thinking of fixing this.

**Comment by DeepDiver1975** [comment]
corner case and old browser involved
