### ISSUE TITLE
[OC6Beta2] Two users save shared file simultaneously -- one gets error

### ISSUE THREAD

**Issue by ser72** [owncloud/core#5629]
**Expected result**
Conflict file created

**Actual result**
Second user to save file gets error "FAILED TO SAVE FILE"

**Steps**
1) UserA shares text file with UserB
2) Both UserA and UserB edit the file and save simultaneously
3) The user who hits save second gets the above error and must exit out of the edit view.

@jancborchardt : Would we want a conflict file here or is this proper behavior?

**Comment by enoch85** [comment]
Soon to be one year old issue. Any update here?

**Comment by DeepDiver1975** [comment]
refs https://github.com/owncloud/core/issues/11804
