### ISSUE TITLE
[OC5 - OC6Beta2] - similar display names

### ISSUE THREAD

**Issue by Elodrin** [owncloud/core#5686]
Hi :)

when I was writing on my owncloud chat-app I found out that there is a security problem with the display-name. Because if there are more than one person with the same display-name every share function will display the double names. So a user must click though every single (double) name, to find out the right user he wants to share with.

Only OC6 shows for a short second the real name, after it changes again to the display name. In the current OC5 (5.0.12) there is no opportunity for a user finding out the right user. (By the way, he do not share with both users which have the same display-name)

Maybe the "getShareWith"-Object shows the wrong content? (

$.get(OC.filePath('core', 'ajax', 'share.php'), {
			fetch : 'getShareWith',
			search : search.term,
[...]

Greetings

PS: Hope you will find a better solution :/

**Comment by alekiy** [comment]
related to #8194

**Comment by jancborchardt** [comment]
Closing this in favor of https://github.com/owncloud/core/issues/20291
