### ISSUE TITLE
Get rid of index.php in the url

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#5744]
to be clear this is optional and we cannot rely on this.

more info to come ....

**Comment by tessus** [comment]
@DeepDiver1975 Did you see my last comment? What do you think? Is this issue just for the removal of `index.php`, or `.php` altogether?
Is there anything I can help with?

**Comment by DeepDiver1975** [comment]
from my understanding neither index.php, public.php nor remote.php shall be visible in the url.

but this is a long way - I need to rethink on how to make this happen ....

**Comment by tessus** [comment]
well, you can drop me an email. maybe I can help.

**Comment by LukasReschke** [comment]
Proposal is at https://github.com/owncloud/core/pull/14081

**Comment by tessus** [comment]
@DeepDiver1975 are you still looking into this? just wondering. `index.php` and `remote.php` are still present in URLs.

If you want, I can have a look at it as well. Please drop me an email or we can discuss this in this thread. I believe there are several ways to handle this. (e.g. remove index.php completely or replace it by something else, let's say `cloud`).

What do you think? Is it worth looking into this again?

**Comment by karlitschek** [comment]
low priority from my point of view

**Comment by gsosna** [comment]
Hmmm.... seems that some people REALLY want it and others REALLY couldn't care less. Is there any way of judging the community desire for this? What's being asked is pretty trivial, and is already possible with a couple of hacks in either httpd or nginx, yet even that is frowned upon here... ;-(

**Comment by karlitschek** [comment]
well if it's possible with some webserver config then this should be fine for the people who REALLY care how the urls look like. i assume that most core contributors are looking into more serious bugs and improvements at the moment. :-)

**Comment by DeepDiver1975** [comment]
> What's being asked is pretty trivial,

@gsosna you are very welcome to submit a pull request to fix this

![bildschirmfoto von 2015-09-15 09-59-25](https://cloud.githubusercontent.com/assets/1005065/9870940/7ae30a10-5b90-11e5-847b-5f495c05b903.png)

**Comment by jospoortvliet** [comment]
One way of judging demand is bountysource: https://www.bountysource.com/issues/1328006-get-rid-of-index-php-in-the-url

But that, too, isn't entirely objective - you can promote an issue a bit and it will get more support, of course. And not everybody has money ;-)

**Comment by jospoortvliet** [comment]
And as @karlitschek pointed out - if it is indeed a simple server setting, let's document it! I offer help with that as, personally, I like shorter sharing links ;-)

**Comment by LukasReschke** [comment]
A simple server setting won't fix this. Our routing will explode then in some cases. There needs to be at least 1 change to the router as done in https://github.com/owncloud/core/pull/14081

That said https://github.com/owncloud/core/pull/14081 is pretty much complete but just requires somebody with time to fix all the unit tests etc…
