### ISSUE TITLE
file upload conflict dialog - "Continue" without selecting any action

### ISSUE THREAD

**Issue by moscicki** [owncloud/core#5764]
I can click on "Continue" in the file upload conflict dialog box without really selecting
what to do. I don't know what happens then. This should not be possible without making sure that there is an action defined for every file, or it should be made clear what is the default behaviour.

BTW: it's a great functionality and good improvement from version 5!

![image](https://f.cloud.github.com/assets/621965/1499701/3fc444a6-4861-11e3-86f9-50cabeabe014.png)

**Comment by PVince81** [comment]
@butonic will you still have time for this ? Else I tagged it as junior job.

**Comment by butonic** [comment]
Junior Job makes sense.

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19645
