### ISSUE TITLE
mirall and the server display a wrong "storage usage"

### ISSUE THREAD

**Issue by flurischt** [owncloud/core#5786]
This is the third or fourth time that this problem happened. That's why I'm creating an issue ticket.
I'm using the latest mirall version and owncloud 5.0.13. The problem existed also with 5.0.12 and below. From time to time mirall shows me a storage usage of <= 1GB although I have ~50 GB in my owncloud. 

Its not only mirall. When I login to the webapplication I get the same (wrong) result: 
![before](https://f.cloud.github.com/assets/191603/1507508/1340d29c-4987-11e3-997d-e054e118d622.png)

The webapplication shows me a low storage usage although there are directories that are bigger than the displayed storage usage:
![not_determined](https://f.cloud.github.com/assets/191603/1507509/1342775a-4987-11e3-94eb-1f3d43683e90.png)
![big_dir](https://f.cloud.github.com/assets/191603/1507510/134297c6-4987-11e3-81a0-db48b83460c0.png)

The strange thing is, that I can "fix" this problem by clicking around in the webapplication. I have no idea why, but everytime I have this problem in mirall, I go to the webapplication and randomly open directories. after a couple of minutes the webapplication AND the desktop client show the correct storage usage:
![after](https://f.cloud.github.com/assets/191603/1507507/12efa67e-4987-11e3-894e-76080d6ca431.png)

Maybe I should mention that I only work with the desktop client. I guess users who use the webapplication regularly wont see this problem. My last three logins to the webinterface were only for the "fix" mentioned above.

Let me know what addintional infos you need.

**Comment by enoch85** [comment]
@hdering Is the issue solved?

**Comment by MorrisJobke** [comment]
@hdering Please reopen if this issue still exists.
