### ISSUE TITLE
Info.xml enhancement

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#5856]
Copyright information and a list of developers can be needed to be shown in the app listing page.

I'd like to recommend the following changes in the info.xml file structure:
- change the licence and author tags, it should be changed to:

``` xml
<info>
    <license-info>
        <license>AGPL</license>
        <licensee>current author</licensee>
    </license-info>
</info>
```

This should show the same license text we have now if the license-info tag exists:
"AGPL-licensed by current author"
- add copyright info

``` xml
<info>
    <copyright>ownCloud, Inc</copyright>
</info>
```

This should show:
"Copyright: ownCloud, Inc"
- add developer info

``` xml
<info>
    <developers>
        <developer>Armin Guuren</developer>
        <developer>James Cubel</developer>
        <developer>Alice Sampson - EESS</developer>
    </developers>
</info>
```

This should show a list with all the developers:
"Developed by:
· Armin Guuren
· James Cubel
· Alice Sampson - EESS"

Thanks

**Comment by Prakharsvnit** [comment]
PR here [#27255](https://github.com/owncloud/core/pull/27255)

**Comment by DeepDiver1975** [comment]
we will not walk this path - discussion continues in #27255
