### ISSUE TITLE
Sharing dialog difference file / folder

### ISSUE THREAD

**Issue by simonruber** [owncloud/core#5858]
Referencing to the design forward share dialog #3224  I have grabbed here a specific point. 

The Dialog for the sharing user should present for files just the possibilities to give the permissions: "can edit" and "can share". The Options: create and delete are not useful there. Create isn't there at the moment, so thats not the issue. The Option delete is as @DeepDiver1975 agreed at #5836, maybe not really needed in the ui. 
So the dialog can be shortened to "can edit" and "can share".

The sharing Dialog for folders should contain the "can edit" with a drop-down, as @jancborchardt suggested in his mockup #3224. Is the delete function for folders useful? or should it be the same as with files, merged with "can edit"?

**Comment by PVince81** [comment]
See https://github.com/owncloud/core/issues/12970 for a discussion about "create" and "delete" and having only "read-only" and "read-write".

**Comment by rullzer** [comment]
This is fixed now that we use the webdav permissions.
