### ISSUE TITLE
Able to assign group admin to unexisting group

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#5868]
### Steps to reproduce
1. Go to the users page
2. In the controls bar behind the password field, click the "Groups" dropdown
3. Click "+ add group"
4. Type in "unexist"
5. Close the dropdown, do NOT click "Create".
6. In the user list, assign a user to the group "unexist"
7. Refresh the page

### Expected result
At step 6, the non-existing group should not happen yet in the "Group admin" dropdown of the users list.

### Actual result
Possible to select the not existing group.
After refresh the dropdown appears empty because it tries to select a value that it not in the dropdown.
The database table oc_group_admin has an entry with the non-existing group.

### Versions
OC 6 beta 4

This is not a showstopper, as it doesn't break much.
It is still possible to create group admins.

Is there a reason why we're not using foreign keys to prevent such cases, maybe database compatibility ? @DeepDiver1975

**Comment by DeepDiver1975** [comment]
@MorrisJobke please have a look once you work on user management for 8.1 - THX

**Comment by PVince81** [comment]
or @LukasReschke.

I haven't retried in 8.0 yet

**Comment by PVince81** [comment]
Still happening on master (8.2 pre-alpha)

**Comment by cmonteroluque** [comment]
moving to 9.0

**Comment by rullzer** [comment]
I can't reprodce this anymore. The user page does not even shot the bug anymore and the subadmin stuff should not also properly handle this.

@PVince81 please confirm and close ;)

**Comment by PVince81** [comment]
Works fine now on master 1b369870f247b78776559e13d3da0f689210868d / 9.0 pre-alpha
