### ISSUE TITLE
sharing dialog in modal

### ISSUE THREAD

**Issue by simonruber** [owncloud/core#5873]
@jancborchardt 
I think it would be a great improvement if the sharing dialog is not anymore in this tiny drop down menu. 

To give it more space has the advantage, that we can display everything needed, in an acceptable format. But the biggest advantage could be, that we can start to use nearly similar share dialogs for every app. Also it would give you a better focus on the specific share task.

The file icon and the filename are displayed first, next to a clearly visible close button (cross)

The next point is the file owner, which is really important for anyone to know. (for e.g. if permissions are missing etc.)

The actual share dialog is put in an scrollbox with the searchbar on top.

For files, the user has just two different choices. Edit and create. The delete issue is going to be dicussed at #5858 .

The "share link" and "set expiration date" checkboxes are as now, just optional. 

The sharing has to be confirmed

What do you think about this concept?

![bildschirmfoto 2013-11-14 um 15 15 34](https://f.cloud.github.com/assets/5917496/1541545/b9d1fb72-4d38-11e3-9c55-f6433fc0ce56.png)
![bildschirmfoto 2013-11-14 um 15 15 51](https://f.cloud.github.com/assets/5917496/1541603/2a8c2fb2-4d3a-11e3-8e72-0e0ca67a3c6f.png)
![bildschirmfoto 2013-11-14 um 15 16 05](https://f.cloud.github.com/assets/5917496/1541606/323e127a-4d3a-11e3-93a2-0666557f3e4d.png)

for a folder the dialog would look nearly the same, but with little difference from the one for files. 

The difference would be mainly, the user permissions. Here for folders a dropdown would do the trick for us and you could decide about the create issue.

![bildschirmfoto 2013-11-14 um 15 16 16](https://f.cloud.github.com/assets/5917496/1541627/9520a8bc-4d3a-11e3-8723-8abe63ed3908.png)

The share dialog for events / calendar could be nearly similar and I can post my ideas to this if you want me to do so.

**Comment by jancborchardt** [comment]
We need to move to the modal for 8.1 so we can use the sharing dialog elsewhere too. For example the file detail view, and make it look properly in the Gallery.

**Comment by PVince81** [comment]
As discussed on IRC: the core/js/share.php code is super messy and it would take too long to beat it into shape.

Proposed plan:
- Write a new ShareDialog class that contains the new dialog:
   - make it use the OCS share endpoints instead of "ajax/*"
   - use handlebars for templates
   - it needs to be callable from any app
   - has to be unit-testable with JS Unit Tests
- Once the dialog exists and works, we can wire it to the files app first
- If the dialog works well, then rewire "OC.Share.showDropDown()" to use the dialog instead, if technically possible (that's the function already used by other apps)

This way if the dialog isn't finished, we can still switch back to the dropdown.
Goal is to move forward with the dialog.

CC @rullzer

**Comment by PVince81** [comment]
@jancborchardt can you address the points from @schiesbn https://github.com/owncloud/core/issues/5873#issuecomment-28686364 ?

Work can still start on this: some ground work needs to be done to provide the necessary dialog / classes.

**Comment by rullzer** [comment]
So I started working on this. However I need some input:

The OCS API uses paths to obtain shares. However the ajax calls us file id's. Now this is not a big deal because we make the apps call the function with paths. I assume that the fill path is present in all apps working with the files/dirs?

**Comment by PVince81** [comment]
@rullzer yes I think so. All apps working with file sharing (ex: gallery) should know what directory they are in.

**Comment by MorrisJobke** [comment]
Keep in mind to not redo stuff like https://github.com/owncloud/core/issues/14787 for files ;)

**Comment by PVince81** [comment]
We might want to go with the alternative approach: right side bar https://github.com/owncloud/core/issues/16308

Also see https://github.com/owncloud/core/issues/3224

**Comment by jancborchardt** [comment]
Closing as we are moving the share dialog to the right sidebar with the new version. See https://github.com/owncloud/core/issues/3224 for any UX improvements left.
