### ISSUE TITLE
add suhosin detection and warning during install / investigate how to make compliant with suhosin

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#5888]
It seems that the suhosin patch triggers some bugs in ownCloud. We should detect it and show an error during install. See here for more information.
https://github.com/owncloud/core/pull/3439#issuecomment-28567268

http://en.wikipedia.org/wiki/Suhosin

**Comment by LukasReschke** [comment]
I think it might make sense to investigate how we can make this work. Assigning to myself, though *NOT* a high priority thing.

**Comment by LukasReschke** [comment]
(most probably most of the things would need to get deactivated as they are not really useful anyways)

**Comment by Xenopathic** [comment]
Suhosin seems to be dead now.
