### ISSUE TITLE
Detail log/control of sync process

### ISSUE THREAD

**Issue by c-holtermann** [owncloud/core#5902]
I want to have a detailed log of which file has been synchronised why and when and by whom.

I had some strange behavior when testing owncloud.

On one client I chose a wrong base directory ( one level below ) so all files were duplicated on both sides. I interrupted that process and deleted the wrong files some time afterwards. But some other client must have copied them and they kept reappeating but I couldn't really find out from where they came. After having them deleted about twenty times they were finally gone.

Then just some days ago all the files from a connected dropbox vanished. The dropbox itself has not been touched as far as i could see - there were no files missing there, so I guess it's a problem with the interface rather than that someone accidentally deleted the files.

Just in these two case I would have been happy to be able to see from where the "commands" came. Then I could have gone to the specific source of the problem and cleaned it up. But I just couldn't find out.

Then it would be nice to be able to have a more transparent insight into the synchronisation process, not only from a diagnostic view but also being able to change it. Unisons gui is an example here. I can choose which files not to transfer and to keep in a different state.

In a situation where something is going clearly wrong I would like to be able to stop the synchronisation and change the process. Stopping is possible in the client. But I would like to know 1) What is going to happen further on and 2) be able to stop a specific synchronisation task. 3) I want to know who or what triggered the sync process.

I see that this is also a design question. In commercial software you don't have influence to these fine tuning aspects. That's one reason that I use free software: I can change the way things happen. But 1) for the majority it is a hindrance to have too many config options. And 2) if a system works you don't need finetuning.

But as far as I can see 1) owncloud is not yet in the state of being so stable that it runs as smoothly as dropbox or other commercial software and 2) I personnaly would like to be able to fiddle with the underlying process and not have it hidden like in modern cars where the engine is sealed in plastic.

**Comment by DeepDiver1975** [comment]
I guess we can close this one
