### ISSUE TITLE
Improve scanner performance

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#5938]
When mounting external storage that contain many files, the scanning process can be very slow (especially for SFTP).

This can be improved by:
1) Disabling preview for external storage: https://github.com/owncloud/core/issues/5917#issuecomment-28775193

2) Remove the "file" approach for mime type detection which sometimes causes the whole file to be downloaded (ex: SMB) CC @karlitschek @DeepDiver1975 @icewind1991 

3) Look into making the scanning process run in the background / passively while making the UI still usable (mimetype detection could be done after the files are already displayed). Needs some research.

This ticket is to track general tracker improvements

**Comment by Xenopathic** [comment]
We have separate tickets open for all remaining issues -> close
