### ISSUE TITLE
Improving ext storage with streaming

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#5949]
Currently the performance of external storage is bad because the file must first be downloaded into a temporary file, then fopen() is called on that file and the handle is returned. This means that downloading a 4 GB file from an ext storage will first create a 4 GB temporary file which is then passed to the client as download.

In some cases like downloading, mimetype scanning (if we keep it), antivirus app, etc we are only interested in getting either the first bytes of the stream (fread() then fclose()) or stream the whole file sequentially. No fseek() needed.

In such cases, it might be more efficient to do a fopen() on the stream directly, if possible. It seems that PHP allows fopen() on HTTP URLs. We could just stream the body of the response as it comes into the hooks and back to the client.

I had a quick look and it looks like most external storages could be modified to use streaming, as many of them use HTTP calls anyway.

The alternative to this would be to use a library like CURL that uses threads to pre-download the file into the temporary file. The control could be given back to the caller before the file is finished downloading, so that they can already start working on the start of the temporary file.

Please let me know what you think of this idea.
@icewind1991 @karlitschek @schiesbn @DeepDiver1975 @bantu 
### List of storages
- [x] SMB (possible since 8.2 with the SMB library from @icewind1991 and libphp5-smbclient)
- [ ] FTP (might be possible with stream wrapper)
- [x] SFTP
- [x] WebDAV ~~https://github.com/owncloud/core/pull/11000~~ https://github.com/owncloud/core/pull/18653
- [x] ownCloud
- [x] Federated shares
- [ ] S3
- [ ] SWIFT: https://github.com/owncloud/core/pull/19002
- [ ] Dropbox
- [ ] GDrive: https://github.com/owncloud/core/issues/21357

**Comment by cmonteroluque** [comment]
marked for consideration for the 9.1 release cycle after the external storage refresh

**Comment by PVince81** [comment]
Looks like Guzzle could be used with a stream factory: https://github.com/owncloud/core/pull/19002/files#diff-2ab592dfd95e06115a358d1b5b20cdc5R318

**Comment by PVince81** [comment]
Okay, looks like it might be even easier, as long as the remote supports HTTP: https://github.com/owncloud/core/pull/18653/files#diff-782207b41e0a420a99054e41c7e7946dR348

**Comment by PVince81** [comment]
- [ ] TODO: double check every storage and distinguish **stream download** from **stream upload**.
Many already have stream download but not necessarily upload.

**Comment by PVince81** [comment]
- [ ] Beware: we discovered that when using Guzzle for stream download it will do a `fopen` directly on the target URL. This means that calling `fread` might not return the number of requested bytes. This situation can happen when using encryption.

We might need to fix the encryption code first to not assume that `fread` always returns the number of expected bytes. The alternative is to make sure that all external storages using `fopen` streams also have some caching / buffering in place (for example Guzzle's `CachingStream`).

**Comment by PVince81** [comment]
GDrive stream download: https://github.com/owncloud/core/pull/23517
Dropbox stream download: https://github.com/owncloud/core/pull/23516

**Comment by PVince81** [comment]
Streaming upload would help reduce the occurrences of PHP timeouts like https://github.com/owncloud/core/issues/24454#issuecomment-217447279

**Comment by PVince81** [comment]
@mmattel FYI I added this to the planning discussion: https://github.com/owncloud/core/issues/24684#issuecomment-220258868
