### ISSUE TITLE
FTP mount doesn't work with encryption

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#5950]
### Steps
1. Mount an FTP storage (vsftpd)
2. Enable encryption
3. Upload file
4. Download file

### Expected result
Downloaded file is not encrypted.

### Actual result
Downloaded file is still encrypted

CC @schiesbn FYI
I suspect it could be another fseek() issue.

**Comment by PVince81** [comment]
@schiesbn we should retry with the new encryption

**Comment by schiesbn** [comment]
works with new encryption: https://github.com/owncloud/core/issues/23657
