### ISSUE TITLE
ownCloud external storage mount doesn't work with encryption

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#5952]
### Steps
1. Mount a WebDAV storage (another ownCloud)
2. Enable encryption
3. Upload file
4. Download file

### Expected result

Downloaded file is not encrypted.

### Actual result

Downloaded file is still encrypted

CC @schiesbn FYI
I suspect it could be another fseek() issue.

**Comment by DeepDiver1975** [comment]
I'm moving this to OC8.1 where we want to work on encryption anyhow (keywords: storage wrapper and mount config option) @schiesbn

**Comment by schiesbn** [comment]
We already disable encryption for server2server sharing based on the storage. We can extend the check to also disable it for ownCloud mounts (see: https://github.com/owncloud/core/blob/master/apps/files_encryption/lib/proxy.php#L76)

Maybe it make even more sense to base the storage for server2server sharing on the "ownCloud-mount-storage" so that we only have to check for this one.

**Comment by DeepDiver1975** [comment]
> We already disable encryption for server2server sharing based on the storage. We can extend the check to also disable it for ownCloud mounts (see: https://github.com/owncloud/core/blob/master/apps/files_encryption/lib/proxy.php#L76)

Hmm - this could be the cheap-ass integration point to enable encryption on storage level .... anyway - topic for OC8.1

But in order to solve this issue for OC8 we could add a second condition?

**Comment by DeepDiver1975** [comment]
> But in order to solve this issue for OC8 we could add a second condition?

@schiesbn can you come up with a PR - THX

**Comment by schiesbn** [comment]
> But in order to solve this issue for OC8 we could add a second condition?

yes, this would be the simple and quick solution. I will prepare a PR later today

**Comment by DeepDiver1975** [comment]
> yes, this would be the simple and quick solution. I will prepare a PR later today

great - thx

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/13156

CC @ZacharyDuBois FYI

**Comment by PVince81** [comment]
There's a better fix here https://github.com/owncloud/core/pull/13160
Please ignore the previous one.

Note that it will still encrypt files on the target OC for now (see comment here: https://github.com/owncloud/core/pull/13156#issuecomment-69089558)

**Comment by ZacharyDuBois** [comment]
I will give it a test the next time I get a chance :)

**Comment by MorrisJobke** [comment]
fixed with #13160

**Comment by carlaschroder** [comment]
removing release note tag cos 13160
