### ISSUE TITLE
Add support for Bitcasa to the files_external app

### ISSUE THREAD

**Issue by gpaumier** [owncloud/core#5953]
Bitcasa is a cloud storage service that has recently opened an API to access a user's file: https://developer.bitcasa.com 

This could be a nice addition to the files_external app. They're providing a PHP SDK at https://github.com/bitcasa/bitcasa-sdk-php . 

Unfortunately, they're apparently using a model where developers need to "Save a Client ID and a Client Secret locally" so this might be problematic in the context of an ownCloud app.

In any case, I thought I'd open this issue to document the discussion on this topic, and perhaps point the Bitcasa folks to it if we need them to weigh in.

**Comment by Xenopathic** [comment]
This can be implemented as an app (especially with the new backend API)
