### ISSUE TITLE
failed chunked upload in the loop - unknown error (errno 5) on otherwise healthy local disk

### ISSUE THREAD

**Issue by moscicki** [owncloud/core#5964]
Hello,

One of my files fails to upload with Unknown Error. Server: 5.0.13 (EE), client 1.4.2 redhat.

It's a 2.2 GB movie: the progress bar looks good until ~1.1GB and then immediately goes to 2.2GB with error message.

Nothing in the owncloud.log on the server.

Only first chunk created on the server:
````
# ls -l ..../moscicki/cache/
-rw-r--r--. 1 apache apache 10M Nov 21  2013 CIMG1029.MOV-chunking-3089998825-0
````
I can touch and write into this directory on the server without problems (as apache user).

ssl_access_log also only shows one chunk being PUT.

In mirall log: 230 chunks are prepared but then mirall fails at the first chunk upload:
````
11-20 15:09:22:933 status.php returns:  "{"installed":"true","version":"5.0.24","versionstring":"5.0.13","edition":"Enterprise"}"   0  Reply:  QNetworkReplyImpl(0x1182fe0) 
11-20 15:09:22:933 #-------# oC found on  "https://cbox05.cern.ch/owncloud" 
11-20 15:09:23:328 oc_module: Chunk upload completed for 'ownclouds://cbox05.cern.ch/owncloud/remote.php/webdav/BLAH/CHEP-VIDEO/CIMG1029.MOV' (10485760 bytes out of 2411724800)
11-20 15:09:53:444 _csync_push_file: file: /home/moscicki/ownCloud-cbox05/BLAH/CHEP-VIDEO/CIMG1029.MOV, command: sendfile, error: Unknown error. from errno 5
11-20 15:09:53:444 _csync_push_file: remember chunk: 0  (transfer id -1204968471 )
11-20 15:09:53:444 _csync_report_parent_error: Mark parent directoy `BLAH/CHEP-VIDEO` as an error
````

**Comment by DeepDiver1975** [comment]
> Server: 5.0.13 (EE),

these days are long gone :speak_no_evil: 

This is most probably related to timeouts on assembly of the chunks -> we will address this in 8.2. Closing this as kind-of-duplicate. THX
