### ISSUE TITLE
[Feature request] Show last modifying user for shared files

### ISSUE THREAD

**Issue by tigran-a** [owncloud/core#6033]
Hello, 

For the folders that are shared, it would be good to show who was the last user who modified (or uploaded new version of) the file.  (Like in dropbox) 

Thanks

**Comment by jancborchardt** [comment]
Hey @tigran-a this is a duplicate of https://github.com/owncloud/core/issues/2263 (Show who owns a file / uploaded a revision) – let’s continue there.
