### ISSUE TITLE
Error message kept when accessing to another folder

### ISSUE THREAD

**Issue by rperezb** [owncloud/core#6049]
### Expected behaviour
Alert error is not shown if we change to another folder

### Actual behaviour
Error message, "fileXx already exists" is kept although you access to another

### Steps to reproduce
1. Upload "photo.jpg" to the server
2. Upload another photo with the same name ("photo.jpg")
3. In the folder, there are two files ("photo.jpg" and "photo (2).jpg")
4. Rename "photo (2).jpg" as "photo.jpg"
5- An alert message is shown "photo.png already exists", having the message on the screen
6. Access to another folder
7. The error message is kept 

### Server configuration
Operating system: MacOS 10.7.5

{"installed":"true","version":"6.0.0.8","versionstring":"6.0 beta 5","edition":""}

Browser: Chrome and FF

![screen shot 2013-11-26 at 10 48 19](https://f.cloud.github.com/assets/1846927/1620829/e6a18410-567f-11e3-8679-0eccff0794d8.png)

**Comment by DeepDiver1975** [comment]
refs https://github.com/owncloud/core/issues/14543

**Comment by PVince81** [comment]
Sev low, reloading the page makes it disappear. Feel free to increase if you think this is not suitable.

@rperezb does it still happen on 8.2 ? Note that we switched to a new tooltip lib which might or might not solve this.

**Comment by rperezb** [comment]
Hey @PVince81 i have not been able to reproduce the error. 
Checked with: ownCloud 8.2 beta1 (daily) Build:2015-10-02T03:39:51+00:00 f891b91cf8475eee16ab1ca08869430bd2dbe51b 
FF and Chrome

(very old one, btw!)
