### ISSUE TITLE
Decide which character set the server should support

### ISSUE THREAD

**Issue by danimo** [owncloud/core#6102]
Currently, the client does not allow to upload files with characters that are illegal in a filename on any supported OS. However, some people argue that the server should accept _any_ files on upload, because some people might have a Linux- or Mac- only environment and do not care about the restrictions imposed by Windows (https://github.com/owncloud/mirall/issues/854).

However before we either remove the black list or make it optional, we need an agreement on the server side that it is the intent of the server team to support all characters on any platform the server supports. @DeepDiver1975 has stated this needs debating, but IMHO we already guarantee this.

**Comment by DeepDiver1975** [comment]
@danimo I guess we can close this in favor of https://github.com/owncloud/core/issues/12015

**Comment by MorrisJobke** [comment]
@danimo Please reopen or comment on #12015 if this isn't fully covered in there.

**Comment by danimo** [comment]
Hmm, I thought we agreed that #12015 was not the way to go...

**Comment by DeepDiver1975** [comment]
> Hmm, I thought we agreed that #12015 was not the way to go...

actually the way to go is: https://github.com/owncloud/core/issues/12015#issuecomment-62686429

**Comment by danimo** [comment]
@DeepDiver1975 Yes, but shouldn' we put that in a new issue.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 Yes, but shouldn' we put that in a new issue.

indeed - will take care about this on Monday ...

**Comment by DeepDiver1975** [comment]
> indeed - will take care about this on Monday ...

okay - did it right away - https://github.com/owncloud/core/issues/13640
