### ISSUE TITLE
Extend file cache' and view's search functionality ...

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#6103]
- [ ] allow limit and offset parameters
- [ ] support order by criteria
- [ ] allow search in files only - no folders
- [ ] allow search by list of mime-types

@icewind1991 THX

**Comment by DeepDiver1975** [comment]
I guess we have to touch this once we move the files app to webdav with all consequences

**Comment by PVince81** [comment]
Ah yes, this good old topic.

Linking with pagination: https://github.com/owncloud/core/issues/13915
