### ISSUE TITLE
WebUI showing NaN for folder size

### ISSUE THREAD

**Issue by Pro** [owncloud/core#6237]
### Expected behaviour
If the folder size is unknown, the total size is indicated as `NaN undefined`:
![nan](https://f.cloud.github.com/assets/251973/1700444/bacc8d76-6016-11e3-97ce-e12b70760d3b.PNG)

Why is the folder size even unknown? The server should know how big the folder is?

### Server configuration
Operating system: Ubuntu 10.04 Server

Web server: Apache

Database: MySQL

ownCloud version: 6.0RC4

Updated from an older ownCloud or fresh install: fresh install

List of activated app: Encryption

### Client configuration
Browser: Firefox

**Comment by PVince81** [comment]
@Xenopathic didn't you fix something similar a while ago ?

**Comment by Xenopathic** [comment]
The only thing I could find was #12639, but that was for the modified date not the file size.

**Comment by PVince81** [comment]
Works properly on OC 8.0.6 and later. No more "NaN" but "Pending" appears.
