### ISSUE TITLE
Share dialog: better suggestions for who to share with

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#6296]
Currently you are faced with a blank input field where you need to remember people’s user names and email addresses.

We can ease that process. ownCloud knows whom you often share with. These people should be suggested and placed at the top with their avatars in some way.

I don’t have an exact design idea for that yet. A beginning would be that already when you click into the input field, the suggestion dropdown comes down with the people you most frequently share with up top.

@owncloud/designers

**Comment by jancborchardt** [comment]
cc @rullzer for sharing here, and @owncloud/designers

**Comment by PVince81** [comment]
@pmaier1 @felixheidecke

**Comment by felixheidecke** [comment]
@PVince81 you keep digging up the weirdest things ;-) I would say this is "future music" waaaaaay in the future.
