### ISSUE TITLE
[Enhancement] Progress bar when encrypting and decrypting 

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#6387]
If you like me, have a lot of data to be either encrypted or decrypted it would be nice to have a progress bar for the process.

The preferred way for this would be that instead of a "spinning wheel" it should be in % instead, or maybe even like "XX MB of XX MB is done".

Personally I have 600 GB of data to be decrypted as we speak, and it´s been processing for 2 days now. If there was a progress bar instead I would know how much was left, and don´t have to be worried that something was wrong.

@schiesbn

**Comment by PVince81** [comment]
This is obsolete: initial encryption doesn't happen any more at login time.

Encrypting and decrypting can be done by the admin on the CLI since 8.2, and that one has a progress bar.
