### ISSUE TITLE
Ubuntu package extracts to /var/www

### ISSUE THREAD

**Issue by netAction** [owncloud/core#6388]
### Expected behaviour

When installing ownCloud from Opensuse repository it should appear in */usr/share/owncloud*

### Actual behaviour

It is in */var/www/owncloud*

This is the default webspace path. Users might have Wordpress here or whatever else. If you want to help the user just add a symlink or better an ALIAS directive to Apache config. Please get out of user content areas where you do not have a clue how users might use it.

### Steps to reproduce

apt-get install owncloud

### Server configuration

ownCloud version: 6.0

**Comment by Xenopathic** [comment]
@jnweiger Perhaps we could move /var/www/owncloud to /usr/share/webapps/owncloud for 8.2?

**Comment by jnweiger** [comment]
Debian lintian also produces an error for every file under /var/www/owncloud.
If we decide to move to the proper location for Linux packages, we should also reconsider where the tar ball install goes to!
