### ISSUE TITLE
Text editor: longer folder names are not shortened when editing a text file

### ISSUE THREAD

**Issue by j-ed** [owncloud/core#6403]
## Expected behavior

If the directory path to a text file which should be edited is very long, the displayed path should be shortened as usual to prevent header line glitches.
![20131213-1_oc6_text_file_in_long_folder_path_with_shortened_path](https://f.cloud.github.com/assets/2572764/1742935/ccbe0694-6404-11e3-977f-0957e00d603f.png)

## Actual behavior

If the directory path to a text file which should be edited is very long, the displayed path is not shortened which causes header line glitches.

## Steps to reproduce

1.) Click on the `New` button in long folder path to create a new text file, e.g. 20131213_text.txt
2.) Right after the file name has been entered the new file is opened to enter text and the search box is displayed at the beginning of the line where the new text is being displayed. The search box overlays the entered text.
     ![20131213-2_oc6_create_text_file_in_long_folder_path](https://f.cloud.github.com/assets/2572764/1742899/f82e0190-6403-11e3-87cb-72ac0dcae80e.png)

3.) If you press the `Save` button, the search box is moved to the right side of the screen under the header line.
    ![20131213-3_oc6_create_text_file_in_long_folder_path_and_entered_text](https://f.cloud.github.com/assets/2572764/1742915/621633c0-6404-11e3-8ffc-3884154073d8.png)

4.) As soon as you press enter to enter the second line of the text the search box is moved to the beginning of the line again.

#### Server Configuration

OS: Linux 2.6.24-24
Web server: Apache2 2.4.6
Database: MySQL 5.1.72
PHP version: 5.4.21
ownCloud version: 6.0

#### Client Configuration

Browser: Firefox 26.0
Operating system: Windows 7

**Comment by DeepDiver1975** [comment]
Still an issue with oc8

**Comment by jancborchardt** [comment]
@tomneedham

**Comment by jancborchardt** [comment]
@tomneedham any fix in the pipeline?

**Comment by tomneedham** [comment]
Off for exams till June :( Fix is in my rewrite code from Nürnberg meetup, along with a ton of other fixes

**Comment by jancborchardt** [comment]
@tomneedham so is that reviewable / up as a pull request? Ideally in a branch so someone else can take over?

**Comment by jancborchardt** [comment]
This is fixed with the merge of the rewrite.
