### ISSUE TITLE
Not possible to view files inside of Deleted Files

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#6409]
In the Deleted Files view, the file name is not clickable. Thus it’s impossible to view a file and check if it’s the correct one to restore.

Viewing should be possible just like in Files.

cc @schiesbn @owncloud/designers

**Comment by PVince81** [comment]
There is a challenge with this. It's not only a matter of linking any editors/viewer.
The problem is that we need to be able to pass the correct download URL to the editor for it to be able to show the file read-only.

This could be added as extension of the new JS viewer API task: #13414

**Comment by jancborchardt** [comment]
@PVince81 @schiesbn so we postpone this to 8.2?

**Comment by PVince81** [comment]
Yeah, let's do that.
