### ISSUE TITLE
Initial encryption: must disable input fields (minor)

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#6444]
### Steps to reproduce
1. Upload a few (big) files
2. Enable encryption
3. Logout
4. Log in
5. Click in the login or password field and continue typing

### Expected result
"Login", "Password" fields and "Log in" buttons must be disabled when the "initial encryption message appears"

### Actual result
Fields not disabled.

### Versions
ownCloud 6.0.0a

@schiesbn please have a look

**Comment by MorrisJobke** [comment]
Isn't a problem anymore with the new encryption.
