### ISSUE TITLE
Rewrite FTP ext storage impl to use an FTP connection/session

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#6468]
Currently, the FTP ext storage is using a URL-based approach.
It calls stat('ftp://...'), fopen('ftp://'...') etc without keeping an explicit connection.

It seems that this approach has many issues:
1) PHP can't get mtime for directories using the URL approach, neither with `stat()` not with `mtime()`: #6395 which makes it impossible to detect folder changes

2) Some PHP environments have stat() failing for some unknown reasons #5655 #3408 

We should maybe rewrite it to use `ftp_connect()` instead which might provide a more stable and compatible connection.

Let's discuss @icewind1991 @karlitschek @DeepDiver1975 @schiesbn

Before going with a full fledged implementation, we must try out whether the ftp_connect() approach can solve the above issues.

**Comment by j-ed** [comment]
Here you will find my attempt to create a custom FTP stat() function:
https://github.com/j-ed/core/blob/master/apps/files_external/lib/ftp.php

Unfortunately @PVince81 and I weren't able to identified what else
need to be modified to get this peace of code running.

**Comment by cdamken** [comment]
@PVince81 Any news?

**Comment by PVince81** [comment]
This hasn't been scheduled.
If needed please raise priority.

**Comment by cdamken** [comment]
@craigpg can be this scheduled?

**Comment by PVince81** [comment]
@Xenopathic did you get a chance to have a look ?

@cdamken it is not confirmed yet that this solution would fix the issues, so first thing would be to research whether it does.

**Comment by craigpg** [comment]
@cdamdken, please work with @markviens et. al. to get this properly scheduled.

**Comment by Xenopathic** [comment]
Not yet unfortunately, but it's definitely something I will look at, hopefully for oC 8.1

**Comment by PVince81** [comment]
In that case I'll set the milestone to 8.1 and assign to you if you don't mind. :smile: 
Let us know (with a WIP PR) if you start working on this.

**Comment by Xenopathic** [comment]
Will be redundant with #14551

**Comment by oparoz** [comment]
One more reason to do it https://github.com/owncloud/core/issues/16906
Hopefully flysystem will be the solution...

**Comment by Xenopathic** [comment]
Closing as we want to move to Flysystem
