### ISSUE TITLE
Feature Request - Disable Storage Options from Admin

### ISSUE THREAD

**Issue by jfreak53** [owncloud/core#6532]
It would be AMAZING to be able to disable certain storage options from the admin panel :)

I for instance have this need. I need to completely disable local storage for all my users current and future. Only allowing them to use a remote storage option. My ownCloud install is hosted in a different location than the users emails and data. So if I don't disable local storage then I cannot control space usage as it's already controlled in the other location by quotas.

So if I could disable local storage and only allow them Dav or SFTP or even FTP then that would be amazing as they all have those options through the other server.

**Comment by Xenopathic** [comment]
Closing in favour of #10198 (it's clearer)
