### ISSUE TITLE
Opera Mini does not render ownCloud correctly

### ISSUE THREAD

**Issue by rakekniven** [owncloud/core#6631]
Content is below left menu bar. It does not matter which app is activ.

See attached screenshot

![owncloud-opera-mini-display-error png](https://f.cloud.github.com/assets/2069590/1844803/3515de78-7554-11e3-8020-ee923febcb0d.jpg)

oC Version : 6.0.0a
Client system: iOS 7.0.4
Opera Mini 7.0.5

**Comment by Xenopathic** [comment]
Please try again with oC 8.1.1 and/or the latest version of Opera Mini
