### ISSUE TITLE
Allow public uploaders to create folders

### ISSUE THREAD

**Issue by fafische** [owncloud/core#6635]
When sharing pictures it will be great when public uploaders can create a subfolder and place theire pictures in it.

**Comment by PVince81** [comment]
If we move the whole web UI of the files app to use WebDAV for file operations (https://github.com/owncloud/core/issues/12353), then we can point it to "public.php/webdav" for the public page, which will automatically make all file operations (including creating folders) available.

**Comment by PVince81** [comment]
The problem also exists in 8.0.

Will now try and find how to fix this...

**Comment by MorrisJobke** [comment]
@michaelstingl Got a request for this -> blue ticket

**Comment by michaelstingl** [comment]
@MorrisJobke Thanks!

00002582

**Comment by DeepDiver1975** [comment]
@craigpg I honestly don't see this happening for 8.1 - as described by @PVince81 above - we will touch the files app for 8.2 - nothing is planned for 8.1 with this respect. Introducing a feature now which we need to touch in 6 weeks from now again is a waste of time.

**Comment by DeepDiver1975** [comment]
Furhermore: how does blue-ticket and feature request live together?

**Comment by cdamken** [comment]
@DeepDiver1975 Its a problem that has to be solved (blue) and the solution is not planned as bug, but as feature request. example: LDAP user erase or in the future Shibboleth user erase :smiling_imp:

**Comment by craigpg** [comment]
@DeepDiver1975, I wasn't advocating for when this gets fixed.  Rather, I was just adjusting the blue-ticket label since it's a feature request.

**Comment by PVince81** [comment]
The PR that makes the web UI use WebDAV: https://github.com/owncloud/core/pull/16902
It also implicitly adds operations like rename, create folder, delete to the public file list :smile:

**Comment by alois74** [comment]
Are you going to implement deletion of files / folders via publicly shared link?

**Comment by PVince81** [comment]
Not using the old ajax/* endpoints as it needs a lot of code duplication and extra code paths.

But the switch to WebDAV makes it possible already on this work in progress PR: https://github.com/owncloud/core/pull/16902

**Comment by michaelstingl** [comment]
@bboule @felixboehm milestone?

**Comment by alois74** [comment]
Ich bin am 14.09.2015 wieder anwesend

Ich werde Ihre Nachrichten nach meiner Rückkehr beantworten.

In dringenden Fällen können Sie sich an Hr. Stephan Unsin (089/2868-3280,
sunsin@gv-bayern.de) wenden.

Mit freundlichen Grüßen
Alois Schmid


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re: [core]
Allow public uploaders to create folders (#6635)" gesendet am 24.08.2015
10:44:02.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

**Comment by TDannhauer** [comment]
What is the current status of this ticket? Now 8.2 is out but creating folder in public shares is still not possible..

**Comment by MorrisJobke** [comment]
> What is the current status of this ticket? Now 8.2 is out but creating folder in public shares is still not possible..

It's currently not on the roadmap. But with 9.0 there is the migration to use the WebDAV api in the files app too. Then it would be easier to also bring the folder creation to the public interface.

**Comment by michaelstingl** [comment]
@MorrisJobke Another user requested this too.

00004149

**Comment by MTRichards** [comment]
Tagging as 9.1 to consider when that planning begins.

**Comment by MorrisJobke** [comment]
* [ ] also delete items in the public link share if change permission is granted #20646

**Comment by PVince81** [comment]
Note, creating folders in public link page is already implemented in this PR: https://github.com/owncloud/core/pull/16902

Not sure about the item deletion issue though...

**Comment by PVince81** [comment]
@MorrisJobke can you retest on master/9.0 about the item deletion you mentionned ? Does it work now ?

**Comment by MorrisJobke** [comment]
> @MorrisJobke can you retest on master/9.0 about the item deletion you mentionned ? Does it work now ?

I just tested on current master: It works! :) Creating folder, renaming files, delete folders/files. I guess we need to add some more fine granular permissions here - like "only create new files/folders" to avoid data destruction ;) (but this is a separate ticket.

**Comment by PVince81** [comment]
@MorrisJobke can you raise it ?

**Comment by MorrisJobke** [comment]
> 00002582

@michaelstingl ;)

**Comment by PVince81** [comment]
hint: not backportable

**Comment by MorrisJobke** [comment]
> @MorrisJobke can you raise it ?

https://github.com/owncloud/core/issues/20699
