### ISSUE TITLE
change data path from absolute to relative

### ISSUE THREAD

**Issue by Jas2Ma** [owncloud/core#6653]
I'm using a Beaglebone black as an webserver. So I have to store all may webdata at an external hdd, which I link symbolicly into my /var/www directory. Yesterday I renamed the original owncloud folder at the hdd, while keeping the link-name at /var/www the same. This leads to an database error: "database could not be opened" (sqlite error 14). It took me at least two hours to understand, that this renameing caused the error.

I think this is connected to your absolute declaration of the directory in config/config.php. If possible you should give this path relative or at least please add an hint for database-error 14 is connected to wronge pathes in config/config.php in your documentation.

**Comment by LukasReschke** [comment]
Makes sense to only allow an absolute one. No need to change from my PoV. Closing.

**Comment by shoeper** [comment]
Relative paths would be great. On my shared hosting the path via ssh is /data (or ../data as relative path) and when accessing via web it is something like /var/www/vhosts/myaccountsfolder/data (or ../data).

Because of thise I have to change the config manually before using occ every time.

**Comment by RafaelKa** [comment]
Please reopen, many Webhoster are using non-CHROOT env. for web (PHP-FPM, mod_php, etc.) but CHROOTED for SSH. So the paths are different in both environments!

**Comment by PVince81** [comment]
Hmm, fair enough.
