### ISSUE TITLE
realpath_cache for owncloud code base not working

### ISSUE THREAD

**Issue by dietmaroc** [owncloud/core#6710]
### Expected behaviour
if you synch files, the number of stats should be kept as low as possible
(in this case most liklely by using/enabling/configuring the REALPATH_CACHE for looking up paths
insteas of using stat, lstat etc over and over

### Actual behaviour (not yet re-enacted by support):
Customer has a huge number of lstats
into the /var/www/html/owncloud tree
This introduces a very high overhead for each request.
The customers machine shows:
The number of stats (stat, lstat, open) into /boxstorage is close to 400 instead of being
at maximum 20 or 40. This is killing storage backends over the network (# of files see below)

### Steps to reproduce
1. have 20 files in the top-level directory
2. sync them to an empty directory
3. pure download test - no upload

### Server configuration
Operating system: redhat 6

Web server: 

Database: apache2

PHP version: php 5.4

ownCloud version: 5.0.14 EE

more info aubout the customer  server is to come

**Comment by LukasReschke** [comment]
Open since more than one year, I guess this is not relevant anymore. Closing, feel fee to reopen though.
