### ISSUE TITLE
Feature Request: On-Demand Sync

### ISSUE THREAD

**Issue by Gankro** [owncloud/core#6760]
My Apologies if there is a better place to put this.

Ever since I read [this article](http://arstechnica.com/information-technology/2013/07/skydrive-in-windows-8-1-cloud-storage-the-way-its-meant-to-be/) on new skydrive functionality, I've been very excited by the idea of on-demand syncing of files. 

The relevant excerpt is this:

> SkyDrive now shows all your files as if they had been synced locally. They just look like normal files. They have thumbnails, filenames, all the usual metadata. What they don't do is take up space on disk.
> 
> As soon as an app opens a file (and this applies to both Metro apps and desktop apps), SkyDrive pulls it from the server. Modifications are then synced back normally. The same occurs if a file is copied or moved; it gets automatically retrieved.
> 
> Instead of the normal selective sync options, folders can be right clicked (in both the Metro app and Explorer) and set as available offline, forcing files to be downloaded, or online only, removing local copies and doing on-demand downloads.
> 
> Behind the scenes, the first time a PC syncs with SkyDrive, it pulls down all the basic metadata: the tree structure, filenames, and so on. Then, it pulls down special metadata, such as thumbnails and full text. In many ways, this makes the files act like normal files. They can be found in searches; they have the right icons in Explorer.
> 
> The files themselves use the reparse point mechanism first introduced in Windows 2000. During that first sync, stub files ("reparse points") are created to mimic the directory structure stored on SkyDrive. Any operation on these files is intercepted automatically, allowing SkyDrive to download the file on-demand.
> 
> The use of this (rather low-level) mechanism makes SkyDrive in Windows 8.1 very transparent. Virtually any application should work correctly, with only a download delay disclosing that a file isn't stored locally. Even the command-line can work with SkyDrive files. The system should even work correctly with backup applications. Backup software should understand reparse points and treat them specially, so backing up your SkyDrive folder shouldn't cause the entire thing to be downloaded.
> 
> As a result, you can have tens or hundreds of gigabytes of files stored on a server, while still retaining pseudo-instant access. There's no long sync process.

In summary, it would be very desirable to be able to configure OwnCloud to always sync metadata stubs for all files that appear to be full files when browsed by the user, and only actually sync the contents of files _after they have been requested at least once_.

Here's a more concrete usecase if you want:

I am a member of a lab with several desktops. Each system has Ubuntu and all software locally installed on the machines, but the contents of each user's home folder are in fact stored on a central remote server that is just mounted over NFS. Unsurprisingly, this has substantial performance consequences, especially since this is largely pointless when 99.99% of the time everyone uses the same machine as they did the last day. 

The alternative would be to sync the home folder locally, but then if we need to change workstation (perhaps to use some special hardware), we experience the all-too-familiar lock-up of a massive syncing, where the vast majority of the files aren't needed (I don't need all my music and code to use the lab's scanner).

This is exactly where on-demand syncing would be desirable. A user logs into a machine they haven't used before, and only the files they request are downloaded as they (or applications) request them. If that machine becomes their new regular machine, all their files will become locally cached/synced as they access them.

To avoid machines getting clogged up with tons of files from random people logging in a couple times, it would also be desirable to be able to "garbage collect" files that haven't been accessed after a while, at least when space is running low.

Some of these things are, of course, probably beyond the scope of ownCloud, but some of this certainly seems to be within scope. Would it be possible to introduce some on-demand functionality to ownCloud?

**Comment by jancborchardt** [comment]
@DeepDiver1975 @PVince81 will this ever happen? If not I’d suggest to close this issue.

**Comment by PVince81** [comment]
@MTRichards @karlitschek @cmonteroluque

**Comment by MTRichards** [comment]
I would consider this a good use case for a virtual filesystem, so I wouldn't close the issue - but not sure how to handle long term conversations of this kind.

@karlitschek @dragotin @danimo

**Comment by karlitschek** [comment]
Agreed. This is something for the virtual filesystem

**Comment by amagliul** [comment]
Just wanted to propose an alternative client if anyone is interested. We've had many OwnCloud users (of which I'm one) report that they successfully use our odrive desktop client with OwnCloud's WebDAV integration.

**Comment by PVince81** [comment]
closing in favor of https://github.com/owncloud/client/issues/4341
