### ISSUE TITLE
Feature request: Symlinked files [$20]

### ISSUE THREAD

**Issue by fieldse** [owncloud/core#6771]
Feature request: The ability to symlink files in the Owncloud synced folder on the local computer.

as per this discussion at github/owncloud/mirall: https://github.com/owncloud/mirall/issues/665

This is possible in Dropbox: 
(see: http://lifehacker.com/5154698/sync-files-and-folders-outside-your-my-dropbox-folder)

Purpose: to allow a more unified collection in the Owncloud sync folder, and including files from other directories. This is standard feature in Dropbox, and users accustomed to working under this paradigm might expect the same functionality. 

Here's a few comments from users in that thread requesting this support:
![15-01-2014_001](https://f.cloud.github.com/assets/394065/1918599/c11e214e-7dc1-11e3-9ac4-d9d191710d1f.jpg)

![image](https://f.cloud.github.com/assets/394065/1918643/783f017c-7dc2-11e3-8c76-5e602a3db944.png)

The moderator Danimo in that thread responded it's impossible, and to open a feature request in core:

> danimo commented: 
> "The main problem is that the sever is not capable of storing symlinks. Feel free to open an issue in core about that."

Thanks for your hard work, devs, and will appreciate any consideration of this idea. Awesome application.

**Comment by PVince81** [comment]
For the Webdav nodes, could use redirect refs: https://www.ietf.org/rfc/rfc4437.txt.
