### ISSUE TITLE
Change fileactions icons on icons in theme folder

### ISSUE THREAD

**Issue by tamvodopad** [owncloud/core#6773]
Steps to reproduce:
1. Put new icons in /themes/new-theme/core/img/actions/
2. Open page with filelist in browser
3. Move mouse to file

Expected results:
App uses new icons from theme folder

Actual results:
App uses old icons from /core/img/actions/ folder

I see in /core/js/js.js filePath function, and this function only uses OC.appswebroots[app] prefix and not uses theme prefix for image files.

**Comment by michaelstingl** [comment]
@MorrisJobke Could you check the current status for me?

00002266

**Comment by MorrisJobke** [comment]
> @MorrisJobke Could you check the current status for me?

This is still broken. #15320 is very similiar (PHP part of the theme icon detection) and there is a fixing PR #15586

**Comment by rullzer** [comment]
Let me look into this once I'm done with #16724 this looks very similar.

**Comment by rullzer** [comment]
OK, it is not hard to make OC use the right action files.
But to avoid a whole bunch of calls to the server (for every file) we need to know that the file will be there.

If we require themes to ship the action files this is easy to solve. But if we do not this is a real pain.
@jancborchardt do we have a list of required theme files?

**Comment by jancborchardt** [comment]
We do _not_ have any requirements for themes and will not have that. A theme can technically change anything, and we recommend logo, texts and color: https://github.com/owncloud/core/blob/master/themes/README

But we definitely do not recommend and will never ever require themes to ship any other assets. We always need to have a fallback to the default.

**Comment by rullzer** [comment]
Then I predict that a lot of theming stuff does not work if icons/images are loaded from javascript.

**Comment by MorrisJobke** [comment]
> Then I predict that a lot of theming stuff does not work if icons/images are loaded from javascript.

Can't we do something like the mimetype command? That reads all folders and then put the info in a json file? Then the command needs to be executed on each change to a theme, but this is acceptable.

**Comment by rullzer** [comment]
Well yes we can :)
I was thinking about that. but then we would need a more generic way. So maybe add a list of available images in OC.theme.images or something...

I think that is the cleanest solution.

**Comment by MorrisJobke** [comment]
> So maybe add a list of available images in OC.theme.images or something...
> 
> I think that is the cleanest solution.

But it's involves a higher maintenance overhead for the theme creator.

**Comment by rullzer** [comment]
Of course that can be generated automatically via a command. i was just thinking it would be best to have all the avaialble stuff in 1 location so we do not end up with a 100 commands for each part of a theme.

**Comment by MorrisJobke** [comment]
> Of course that can be generated automatically via a command. i was just thinking it would be best to have all the avaialble stuff in 1 location so we do not end up with a 100 commands for each part of a theme.

Got it. Was just confused :)

**Comment by jancborchardt** [comment]
Keep in mind that a normal theme definitely does not change the filetype icons. So it shouldnt get any more complicated to do a simple theme just to improve the complicated ones. ;)

**Comment by michaelstingl** [comment]
@jancborchardt What is this "a normal theme"? Enterprise users can modify filetype icons in iOS and Android apps. Of course they want to modify the filetype icons in their (web) files app as well.

**Comment by MorrisJobke** [comment]
> Keep in mind that a normal theme definitely does not change the filetype icons.

Why not? It should be themable like all the other icons in the web UI.

**Comment by jancborchardt** [comment]
@michaelstingl @MorrisJobke what I mean is »the majority of themes will only change color, logo and text – filetype icons will probably only be changed by a few«. So we should not have a strange requirement for _every_ theme to add in filetype icons. That kills the simplicity of theming.

**Comment by stefan-niedermann** [comment]
> Why not? It should be themable like all the other icons in the web UI.
exactly. A theme should be able to change filetype icons. the simple reason is corporate identity - if i want to style my owncloud instance to match my corporate colors, i'd like to change the colors of folders for example.

**Comment by wirebug** [comment]
@jancborchardt Don't get me wrong, but I don't think that putting some image in a folder is complicating the process of theming at all. It's just a question of let the designer overwrite some images with the right name and size. That doesn't kill the simp. licity at all but at more options too designers.
BTW I'm absolutly agree with u@stefan-niedermann

**Comment by hedii** [comment]
I have just finished writing my very first owncloud theme, it was a very intuitive work, but changing the files type icons was the harder part... putting the icons in a the right folder on the theme folder should be available. And when you theme an owncloud instance, filetypes icons **have to** be changed. It was the first thing i wanted to do

**Comment by jancborchardt** [comment]
Well, all I can say is that simply putting different icons in `themes/themefolder/core/img/fileactions/` should overwrite the existing icons. It shouldn’t be any more complicated than that.

If that doesn’t happen it’s a bug, and I summon @schiesbn @MorrisJobke @michaelstingl or someone else to fix it.

**Comment by MorrisJobke** [comment]
> If that doesn’t happen it’s a bug, and I summon @schiesbn @MorrisJobke @michaelstingl or someone else to fix it.

Yes. This is not working. The biggest problem is to choose the correct path on JS side :see_no_evil:

**Comment by cdamken** [comment]
@MorrisJobke could be this part of the solution:https://github.com/owncloud/core/pull/15586

**Comment by rullzer** [comment]
So it is easy to get the right icon. But it is hard to get the right icon in an efficient way. Assume you load a folder with 100 files. Now we need to do a 100 requests to the server to say... give me the icon for this file. While normally you want: give me this icon. Where in 99.9% of the cases this icon is cached.

I'm still not sure how we can solve this in a simple way and still keep performance. Since if you can't make any assumptions you also can't cache anything! Because if all of a sudden an icon is present it should pop up right away.

**Comment by jancborchardt** [comment]
So 9.0 for sure, right?

**Comment by blackcrack** [comment]
there it is an mimetyperegestry in php for my phpfilemirror for easy adapting for OC 

http://www.blackysgate.net/phpfilemirror/upload/mimetype-plugin

but if anyone want adjust / adapt  this for owncloud
to have the possible for use the kde-mimetypes icons theme,
can he use this mimetype.php and can adapt it for owncloud
to use the kde-iconthemes/mimetypes ..
in this mimetypes be all mimeipes into, 
what what it is needed by all files in the world and in kde, 
also include other things also, how ever, 
it is a very large mimetypes collecting, mus only be adapted .

best regards
Blacky

**Comment by bboule** [comment]
@michaelstingl @cdamken @MorrisJobke What are the next steps here (if any) ??  are we just waiting?

**Comment by cdamken** [comment]
Well, we just are waiting... specially the customers.. The next step would be to fix it.

What is "Waiting Internal"?

**Comment by bboule** [comment]
Thanks @cdamken for the insight.... I am asking where we are in the fix?  Is someone working on it?  Do I need to enlist help?

**Comment by rullzer** [comment]
I still don't know how to properly do this.

We want:

1. users just put an icon in the theme folder and it gets used
2. proper performance of the webUI.

They are kind of multally exclusive. Since the webUI can't know if only 1 icon was replaced. So it has to request the iconed version for each icon. And if that is not there fetch the default one. And it has to do this on every page load since the user could have updated the theme and added a new icon.

Basically the only solution I see here is as we do with the mimetypes.
We add an OCC command that allows you to update the current theme. This creates a json file with all the icons that actually are themed. Then we can on the client side easily find out which icon we need to fetch. This break the 'simple' theming where you just add an icon. But I think that use case is rare enough to justify such a command for the sake of performance.

@jancborchardt @cdamken @bboule would this be an acceptable solution?

**Comment by rullzer** [comment]
Anyway... past feature freeze.. so nothing for 9.0 @PVince81 @cmonteroluque

**Comment by cmonteroluque** [comment]
@bboule @MorrisJobke Not moving it yet beyond 9.0, we need to hear from you. Can this wait till 9.1? If not we are going to have to get a plan, eitther for 9.0 or 9.0.1

**Comment by cmonteroluque** [comment]
@rulizer let's fix it inelegantly. It's post feature-freeze, however, it is a bug. So let's fix it and make it better post 9.0

**Comment by MorrisJobke** [comment]
> @rullzer let's fix it inelegantly. It's post feature-freeze, however, it is a bug. So make it better post 9.0

The biggest problem here is that it needs a lot of logic to accomplish the goal :(

**Comment by PVince81** [comment]
One thing to try: make file actions use CSS icons instead of using image URLs.

**Comment by blackcrack** [comment]
mimetypeicons into an /theme/mimetype/*.png folder  
and the Design icon/pictures into the single /theme/style-icons.css file

for hold all clean apart .. and it is able for use different icon themes with an style-icons.css

where it is maybe in the 
/theme/my-theme-folder/style-icons.css
and
/theme/my-theme-folder/mythemeicons/

easy downloadable and put it easy in the themefolder where it is create by wdesigner's
so it is able later to create iconthemes for owncloud ;)

(iconthemes and mime-iconthemes
(and the mimetype/icon-regestry it is able for updating by updating)
..
(and the iconthemes it's able for uploading as owncloud-Icontheme for other with style-icons.css and iconfolder) 
for composing an nice theme compilation)

so 2 folders..
/mimetypes/*.png (hardcoded by mimetype-regesty)
make an example on my phpfilemirror : 
http://www.blackysgate.net/phpfilemirror/
-> test-extensions
----
/icontheme/
+
style-icons.css
as one zip/tar.gz  dor download to choose
different types of iconlook's
and therewith also able for make different themes around..

and at last, diffrent type of mimeicons.. from kde-look
for adding to the theme.. in the themefolder

example:
/mytheme/

//----------mimetype-icons from kde4^ in png/&svg/&svgz
/mytheme/mimetype/*png 

//-----able to pack in one compressed file
/mytheme//mythemeicons/
/mytheme/style-icons.css



best regards
Blacky

**Comment by cdamken** [comment]
>@bboule @MorrisJobke Not moving it yet beyond 9.0, we need to hear from you. Can this wait till 9.1? If not we are going to have to get a plan, eitther for 9.0 or 9.0.1

@cmonteroluque A customer solution was expected since 8.1.1, at least we need a workaround for the 9.0, probably what @PVince81  mentioned:

> One thing to try: make file actions use CSS icons instead of using image URLs.

**Comment by rullzer** [comment]
@cdamken yes that is what we are trying in https://github.com/owncloud/core/issues/22461. Seems to be doable but we need somebody with actual css knowledge to fix the displaying of the icons.
