### ISSUE TITLE
Inconsistent display of path information in apps

### ISSUE THREAD

**Issue by despens** [owncloud/core#6797]
Using owncloud 6.0.0a

Path information is very helpful when editing a file.

(Links lead to relevant screenshots of commercial editors.)

I always see students struggling to find the right file to edit if they use for example [sublime edit](http://www.sublimetext.com/). A common problem is that they will edit a file on their desktop and wonder why the server version is not updated, thinking that they edited the file on a network drive.

If they use [coda](http://panic.com/coda/) or [textwrangler](http://www.barebones.com/images/textwrangler/tour-editing-lg.png), they are much more secure because the full paths for files are shown. 

The simple text editor of owncloud is doing the same in this regard:
![0156](https://f.cloud.github.com/assets/571494/1930641/f86c30ce-7eb0-11e3-81a1-e260d4c268cf.png)
Since the URL line of the browser does not contain the file name it is superb that the whole path is shown above the text.

Documents doesn't show any useful information about the file's location and therefore offers no context. If I edit an invoice.odt from the folder 2013 it will not be distinguishable from invoice.odt in the folder 2012.
![0157](https://f.cloud.github.com/assets/571494/1930682/efc56f2a-7eb1-11e3-9827-06b8f960ad0e.png)
I could also be editing and saving a template while thinking I am editing an actual file.

The PDF viewer is leaving room for the interface but shows no path information:
![0159](https://f.cloud.github.com/assets/571494/1930687/0176ccaa-7eb2-11e3-9ef1-98f252fd667b.png)
(Sorry for the broken pdf. :))

I think it would be great if apps working with files would behave consistently and show full path info everywhere.

**Comment by PVince81** [comment]
Yes, I'd love to have a proper file viewer API / container where such apps can register themselves.
Closing in favor of https://github.com/owncloud/core/issues/13414
