### ISSUE TITLE
Future Request / Folder & File > annotations

### ISSUE THREAD

**Issue by stephriedel** [owncloud/core#6816]
Hello!

I would like to utilize OwnCloud with coded annotations in directories- and file names. I wish for the following functions:

1) In the database -> Fields for annotations
2) In the web interface -> In each case, a comment field for the annotations 
3) In the core OC a folder-file-name analyzer for annotations
4) In the administration interface a switch that turns the analysis function On/Off
5) In the administration interface a switch that turns a "Use only in Web-UI-Interface" Option on/off -> Save the annotations only in the database and show it only in the Web-UI 

Store example of a annotation in file and folder names:

filename!annotation!.txt or foldername!annotation!

use case:
--------------
We work with encoded folder and file name. We would like to give the end user a help.

THX!

**Comment by DeepDiver1975** [comment]
with 9.0 you can comment on files and apply tags - should be enough -> close
