### ISSUE TITLE
default folder not found

### ISSUE THREAD

**Issue by heavymanto** [owncloud/core#6845]
in the OC6 a don't found default folder in themes folder. In oc5 there is, as indicate in documentation

http://doc.owncloud.org/server/5.0/developer_manual/core/theming.html

I work a lot of with web application e i love to divide web application and presentation layout. In OC css and image are not in only folder like "theme" and ALL inside,  but some css is in core, setting, lostpassword, search.... folder. Is terrible to custom

**Comment by Xenopathic** [comment]
Moved to documentation repo

**Comment by rakekniven** [comment]
Please add reference to new issue.

**Comment by Xenopathic** [comment]
![screenshot_2015-09-04_13-57-28](https://cloud.githubusercontent.com/assets/2016878/9684065/03d6058e-530d-11e5-9775-72b2a5f23664.png)
