### ISSUE TITLE
[6.0.1] Slow sync to oC server.  Delay in sending packets from oC server to NFS server

### ISSUE THREAD

**Issue by ser72** [owncloud/core#6937]
We are seeing instances of slow syncing between the ownCloud client (1.5.0) and the ownCloud server (6.0.1)

The setup is as follows (3 separate servers):

oC6.0.1 on Ubuntu
Postgresql 9 database
local data is via NFS mount

Client is on MAC 

We have taken a variety of traces and upon analyzing them it appears there are delays in the ownCloud server sending requests to the NFS server.

Tests have been done with the following:
1) 1000 empty files in one flat folder
2) Many files in many folders

It was noted in the traces taken 01_23_2014 that there was delay in the ownCloud server sending a request to the NFS server to open the mount.json file.
True, there was a mount.json file in existance, however, the user in question had no external mounts, and in fact, there were no "working" mounts configured.

In traces taken 01_24_2014, the mount.json file was removed and there was still delay.  This time prior to NFS "PUTFH, LOOKUP, GETFH, GETATTR" packets.

As it turns out, it would take about .5 seconds for each file to sync on average.  This increased, obviously, with more folders.

In the ownCloud lab, I was unable to reproduce the latency with the same setup as above.  I was seeing .20-.25 seconds per file which is acceptable.

Need assistance in figuring out where the delay is and how best to resolve this issue.

ZIP file "traces.zip" is in the following location:  s3.ownlcloud.com/owncloud/support/Slow Sync
```
Contains the following data within:
"Data 01_23_2014"/"Sync Git"
    client.pcap -- Wireshark trace taken at the Client's MAC.
					Client IP: .219
					oC server IP: .166
					Shows significant delays up to 0.5 seconds in receiving packets from the oC server.
						This basically eliminates the client from being at fault
	git.pcap -- Wireshark trace taken between the oC server and the Postgresql server.
					oC server IP: .48
					SQL IP: .42
					Shows no significant delays
						This basically eliminates the SQL server from being at fault
	nfs.pcap -- Wireshark trace taken between the oC server and NFS server.
					oC server IP: .48
					NFS IP: .35
					Shows significant delay in oC server sending requests to the NFS server as mentioned above
	
	"Data 01_24_2014 No ext storage"
	nfs-no-shared-storage -- Wireshark trace taken between oC server and NFS server.  mount.json still exists
					Shows delay in oC server sending requests to open mount.json to the NFS server
	nfs-no-shared-storage-no-mount.pcap -- Wireshark trace taken between oC server and NFS server.  mount.json has been deleted.
					Shows delay in oC server sending PUTF, LOOKUP, GETFH, GETATTR to NFS server
	nfs-no-shared-storage-no-mount-1.pcap -- Wireshark trace taken between oC server and NFS server.  mount.json removed
					Shows delay in oC server sending LOOKUP DH to NFS server

Then the three access logs associated with the above traces
```
As it appears, all delays are in the oC server's communication (origination) with the NFS server.

**Comment by Xenopathic** [comment]
NFS is a server-level filesystem, ownCloud has no control over it. We support object store external storages for larger installations

**Comment by shoeper** [comment]
Obviously you didn't read anything here.

**Comment by Xenopathic** [comment]
@shoeper The original issue is about NFS, but it rapidly derailed from there. Please open a relevant issue with an appropriate description if you are still seeing performance problems.

**Comment by shoeper** [comment]
It is not importand anymore, but it wasn't really about NFS from the beginning on.

> We have taken a variety of traces and upon analyzing them it appears there are delays in the ownCloud server sending requests to the NFS server. - from the initial issues text

And in 2014 those delays were there no matter which storage backend is being used.

**Comment by Xenopathic** [comment]
@shoeper Please open an issue report if you have problems with ownCloud that are not being handled in any existing issues. This issue was (originally) about NFS, which is invalid from an ownCloud perspective, thus it was closed.

**Comment by shoeper** [comment]
This issue wasn't about NFS.
