### ISSUE TITLE
Decrypt all files after disabling encryption app is too long

### ISSUE THREAD

**Issue by seal20** [owncloud/core#6949]
### Expected behaviour
1) enable the encryption apps, the files get encrypted
2) disable the encryption apps the banner "need to decrypt your files" appears
3) enter my password hit "decrypt all" the files get decrypted in a reasonnable time and an indicator shows how many percent/files remain
4) uncryption continues even if i close the session and I am greeted with an success/still on goind/error banner at next login.

### Actual behaviour
1) enable the encryption apps, the files get encrypted
2) disable the encryption apps the banner "need to decrypt your files" appears
3) enter my password hit "decrypt all" the files seems to be decrypted but it takes days (litterally), there is no indication how many files remain to be decrypted or even if it is working.
4) I don't know if uncryption continues after closing the session. 
I had to look in my data folder to finally found 2 files uncrypted and many still encrypted... I have 7Go of data and it has been running for days. 

### Steps to reproduce
1. enable encryption and encrypt a ot of files
2. disable encryption

### Server configuration
Operating system: Linux (hared hosting)

Web server: Apache

Database:MySQL

PHP version:5.4.24

ownCloud version: 6.0.1

Updated from an older ownCloud or fresh install: updated from 6.0.0a

List of activated app: core apps + news

The content of config/config.php: 
```
<?php
$CONFIG = array (
  'instanceid' => 'oc3053678514',
  'passwordsalt' => 'salt',
  'datadirectory' => '/home/agoremix/public_html/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '6.0.0.16',
  'dbname' => 'agoremix_owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'agoremix_sylvain',
  'dbpassword' => 'pass',
  'installed' => true,
  'forcessl' => true,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => '0',
  'theme' => '',
  'maintenance' => false,
);
```

Are you using external storage, if yes which one: used sftp and dropbox but disabled them before any files were uploaded to them.

#### Web server error log
```
empty
```

#### ownCloud log (data/owncloud.log)
```
 Error 	PHP 	PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20100525/suhosin.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20100525/suhosin.so: cannot open shared object file: No such file or directory at Unknown#0 	2014-01-26T06:06:24+00:00
Error 	PHP 	PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20100525/suhosin.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20100525/suhosin.so: cannot open shared object file: No such file or directory at Unknown#0 	2014-01-26T06:06:22+00:00
Error 	PHP 	PHP Startup: Unable to load dynamic library '/usr/local/lib/php/extensions/no-debug-non-zts-20100525/suhosin.so' - /usr/local/lib/php/extensions/no-debug-non-zts-20100525/suhosin.so: cannot open shared object file: No such file or directory at Unknown#0 
```

**Comment by simonspa** [comment]
I also built in some debug messages to see what happens. First, the crawling for files (findEncFiles) takes ages:
```
{"app":"Encryption library","message":"Enter decryptAll function()","level":4,"time":"2015-01-07T12:22:33+00:00"}
{"app":"Encryption library","message":"findEncFiles return: Array","level":4,"time":"2015-01-07T13:19:23+00:00"}
```
that is more than one hour for just a couple of thousand of files (all in all less than 8GB)

When finally starting decryption, everything first looks fine:
```
{"app":"Encryption library","message":"After the if statement","level":4,"time":"2015-01-07T13:19:23+00:00"}
{"app":"Encryption library","message":"Start Decrypting: whatever/file/image.png","level":3,"time":"2015-01-07T13:19:23+00:00"}
{"app":"Encryption library","message":"Start Decrypting: whatever/file/image2.png","level":3,"time":"2015-01-07T13:19:31+00:00"}
```

But then the decryption routine reaches one of these `ocTransferId<>.part` files which might result from a broken upload (missing e-tag, see #12725) I get the following:

Additional output from the findEncFiles function for this file:
```
{"app":"Encryption library","message":"Filepath user/myfiles/panel.css.ocTransferId1419129547.part is encrypted: 1","level":4,"time":"2015-01-07T12:23:55+00:00"}
```

Output from the decrypt routine:
```
{"app":"Encryption library","message":"Start Decrypting: user/myfiles/panel.css.ocTransferId1419129547.part","level":3,"time":"2015-01-07T13:25:01+00:00"}
{"app":"PHP","message":"Call to a member function getPath() on a non-object at \/var\/www\/owncloud\/lib\/private\/share\/share.php#112","level":3,"time":"2015-01-07T13:25:07+00:00"}
```

Can anyone make sense of this?

**Comment by PVince81** [comment]
@schiesbn is there a ticket for adding a progress bar ?

**Comment by Armada651** [comment]
I also can't decrypt the file storage when a large amount of files are present. It seems to be unrelated to the size of the files, but rather the number of them.

For example in case a git repository has been uploaded to owncloud, decryption it is almost certain to fail.

@PVince81 There is: https://github.com/owncloud/core/issues/6387

**Comment by DeepDiver1975** [comment]
we need to move off all these long running tasks to async jobs - in case of encryption this requires the capability to pass the user password to the executing process - which will not run in the session context (most probably :speak_no_evil: ).

**Comment by nickvergessen** [comment]
Closing because the feature has been removed for now.
