### ISSUE TITLE
Can't autocomplete search to share on users' Full Name when the "Allow users to only share with users in their groups" option is set

### ISSUE THREAD

**Issue by cvpsmith** [owncloud/core#6967]
If you have the "Allow users to only share with users in their groups" option set, the share dropdown will only autocomplete on the username.  It will not autocomplete on users' Full Names, even when those users are in your group.

Setup details:
RHEL6.5
ownCloud 6.0.1-5.1
php-5.3.3-27
mysql-server-5.1.71-1 backend

**Comment by strowi** [comment]
I seem to be running into the same issue.

Setup:
Owncloud 7.4
Debian 7.6
PHP 5.5.15-1~dotdeb.1
Postgresql: 9.1+134wheezy4

**Comment by rullzer** [comment]
Can confirm this is still happening on master.

**Comment by rullzer** [comment]
WIP PR in #15169

**Comment by MorrisJobke** [comment]
fixed in above PR
