### ISSUE TITLE
Username is case sensitive for password reset email

### ISSUE THREAD

**Issue by ghost** [owncloud/core#6982]
ownCloud v6.0.0a

Example

1) You created "User1"

2) Webinterface: Login is not case sensitive. "User1" or "user1" will work!

3) When you want to do a password reset by email, the username has to be case sensitive. If you typed the username "user1" you geht the message: "Request failed!<br>Did you make sure your email/username was right?" "User1" will work fine.

Kind regards,
Cooliminati

**Comment by jancborchardt** [comment]
@kerhac is the fix you committed above in master? If so we could close this.

**Comment by jancborchardt** [comment]
@ghost also can you test if this is fixed for you? I’ll close since I assume it is.

**Comment by kerhac** [comment]
@jancborchardt I pushed this fix to a fork, never to the owncloud/core repo, I should not/don't have access to the owncloud master. The fix never passed my testing that's why I didn't opened a Pull Request but deleted the fork. I'm a little surprised to see the commit show up here. 
Regards Julian

**Comment by jancborchardt** [comment]
@kerhac yeah, I can’t find the commit in the history, so it showing up in here is probably due to some Github linking magic.

**Comment by jancborchardt** [comment]
Duplicate of https://github.com/owncloud/core/issues/10102, let’s continue there.
