### ISSUE TITLE
Deleting a folder does not delete affected shares fore files within it

### ISSUE THREAD

**Issue by butonic** [owncloud/core#6985]
### Expected behaviour
When deleting a folder all shares on files within should be deleted as well

### Actual behaviour
Only the share for the folder is deleted. Other shares are left in place, cluttering up the oc_share table

### Steps to reproduce
1. Create folder 'foo'
2. Create file 'foo/bar.txt'
3. Share file 'foo/bar.txt' via link
4. Share folder 'foo' via link
5. Delete folder 'foo'
6. use sql and `SELECT * FROM oc_share WHERE file_target='/bar.txt'` to see the leftover share row in the db

@schiesbn @karlitschek something to consider for sharing.

**Comment by PVince81** [comment]
We might still want to delete orphaned shares in the background, experimental PR here: https://github.com/owncloud/core/issues/14676

**Comment by PVince81** [comment]
Assigning to self, I'd say the bkg job is the way to go now.

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/core/pull/14676

**Comment by butonic** [comment]
Thx a lot @PVince81
