### ISSUE TITLE
Sticky footer for public share page

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#6991]
First I thought it was broken at some point, but it seems we never had a sticky footer for the public share page.

Try sharing a folder with just a small number of files – the footer will be directly below the content. Instead it should stick to the bottom of the viewport.

We should add that to sharing just as we added it to the log in and installation page: 38bfae5

cc @owncloud/designers

**Comment by jancborchardt** [comment]
@requist do you want to take another stab at this, maybe fixing it for 9.0? cc @owncloud/designers

**Comment by requist** [comment]
I'll have to undust my VM but yes I can take this up. Can take a little since I am a bit busy on another project but Milestone 9 should not be a problem.

**Comment by jancborchardt** [comment]
@requist great! You’re always welcome to ask questions here if you need help, or join our IRC channel #owncloud-dev where plenty of other devs will be able to help you. :)
