### ISSUE TITLE
Use JS to calculate humanFileSize

### ISSUE THREAD

**Issue by pellaeon** [owncloud/core#7016]
Currently many parts are still using `OC_Helper::humanFileSize` or `OCP\Util::humanFileSize`, most of them should use JS to calculate instead. This will increase simplicity and consistency.
If this blueprint is approved I will work on this.

**Comment by jancborchardt** [comment]
@PVince81 has this been solved meanwhile?

**Comment by PVince81** [comment]
This is solved already. @rullzer removed it from list.php as it is already computed on the JS side.
