### ISSUE TITLE
Imposibility to forward connectivity issues from an external storage to ownCloud clients

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#7022]
There could be issues in the connection between ownCloud and the external storage, such a server down, network temporary cut, etc.
We can detect this kind of issue in the external storage plugin and rise an exception to the core, but there is no specific exception to be risen here.

If we use another exception to send an error to the client (a "not found" exception for example) the behaviour could be different than the user expects (which probably will be not to take any action at all).

I think a new exception is needed so these kind of errors are correctly propagated to clients.

Thanks!

**Comment by Xenopathic** [comment]
Closing in favour of #11792
