### ISSUE TITLE
Download multiple files

### ISSUE THREAD

**Issue by buesche** [owncloud/core#7039]
If I want to download multiple files (say, 4 GB), the server will generate a ZIP for me which includes every single file. This process can take a while if there are many files to ZIP. For better User Experience I would suggest something similar what GoogleDrive does. 

-- "Email when ready"
-- "Cancel file zipping"
-- Show Estimated time

![2014-02-01_235853](https://f.cloud.github.com/assets/3862409/2059063/ba54ffe6-8b94-11e3-820c-026887d3d088.png)

![2014-02-01_235930](https://f.cloud.github.com/assets/3862409/2059066/bd69ae02-8b94-11e3-9f22-656e5befd8cb.png)

**Comment by PVince81** [comment]
Please note that since OC 8 (or was it 7 ?) the ZIP file is created on the fly and streamed back to the client. In the past it would create the ZIP file upfront and cause a delay.

Closing as obsolete.
