### ISSUE TITLE
File deletion shows spinner for a long time

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#7060]
When deleting files, there’s spinners shown on the right. Since this often takes quite some time I assume the spinners directly reflect what happens in the backend.

If that takes long, it’s annoying. Can’t we have the entries disppear right away (ideally animated collapsing) instead?

In the future, this should be followed by #119 (improve how undo deletion works with sync)

@schiesbn @owncloud/designers

**Comment by PVince81** [comment]
Closing in favor of the undo logic https://github.com/owncloud/core/issues/119

**Comment by jancborchardt** [comment]
Yup, correct. With undo, the file should vanish directly (ideally with quick slideUp animation) and a longer deletion process will be invisible to people.
