### ISSUE TITLE
Internet connection not working

### ISSUE THREAD

**Issue by zzjet1** [owncloud/core#7074]
Greeting,

OwnCloud 6.0.1 stable installed on Fedora 19 64-bit saw the following message in red when admin user clicked on Admin menu.

Internet connection not working
This server has no working internet connection. This means that some of the features like mounting of external storage, notifications about updates or installation of 3rd party apps don´t work. Accessing files from remote and sending of notification emails might also not work. We suggest to enable internet connection for this server if you want to have all features.

In addition after clicked on Admin menu, it took 3-4 minute before it displayed the Admin section.  I think it tried to verify Internet connectivity and timeout 3-4 minutes later.

In configure.php file, I inserted variable and value restarted httpd, rebooted OS, etc.. no joy.

'proxy' => 'myproxyserver.domain.com:80',

Not sure if it is a bug or something is not right.

My OwnCloud 6.0.1 ($OC_Build = '2014-01-22T11:26:13+00:00';) is behind an Internet proxy server.  I tested my proxy server setting for other apps, yum and OS environment worked fine.

I saw the same issue on CentOS v6.4 64-bit installed too.

OwnCloud needs testing behind Internet proxy, so far not see it not working with my company Internet proxy.

I welcome workaround suggestions or fixes.

Many thanks!!!

**Comment by PVince81** [comment]
@LukasReschke I guess the introduction of Guzzle should fix the proxy situation ?

**Comment by PVince81** [comment]
Closing this all issue. I think we already use Guzzle everywhere now so it should work.
