### ISSUE TITLE
file cache on a local disk for chunked upload

### ISSUE THREAD

**Issue by moscicki** [owncloud/core#7127]
Is there a possibility to configure the file cache to be on a local disk (so not under datadir/user/cache but in another directory, e.g. /tmp/user/cache)?

The reason is simple: if datadir/user is on a remote storage, in the current implementation of chunked upload the transfer is very inefficient: we transfer the chunk to the remote storage, the we read it back to the application server and write it back again assembled to the remote storage. This is 3 (or 2, depending on fs caching) remote transfers instead of 1.

I think it is easier to have the cache in the shared storage but very inefficient and not scalable really. 

Normally we should assume that the sessions are sticky so we could take advantage of the local cache of the application server under normal circumstances. In an event of a failover switch to another application server, the missing chunks would need to be retransmitted by the sync client. But that's an exceptional situation.

**Comment by PVince81** [comment]
Yes, see https://github.com/owncloud/core/blob/v8.0.9/config/config.sample.php#L784
