### ISSUE TITLE
Sharing: Sharee gets error when trying to share a file with someone whom it already has been shared with

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#7128]
1. Admin shares a file with Heinz and Annette
2. Heinz sees the file in his shared folder as »Shared by admin«. He has no idea that it is shared with Annette as well (Problem 1).
3. Because he wants to make sure Annette has it as well, he tries to add her to the share. Heinz then gets an error that file is already shared with her. (Problem 2)

This is related to #4437 (design forward: sharing behavior)

cc @DeepDiver1975 @karlitschek @owncloud/designers

**Comment by MorrisJobke** [comment]
Just verified. This is still an issue on master

**Comment by PVince81** [comment]
Hopefully this issue can be obsolete with #9058 resharing behavior update.

**Comment by jancborchardt** [comment]
We still have to make sure that the suggestion dropdown does not list people who you already shared with. ;)

**Comment by MorrisJobke** [comment]
Once #9058 is solved we don't have this issue anymore.

> We still have to make sure that the suggestion dropdown does not list people who you already shared with. ;)

This is already build in and will work once #9058 is done.


As this issue is a subset of #9058 I will close it.
