### ISSUE TITLE
SEND button for share a link only , not available for "Notify by email" checkbox

### ISSUE THREAD

**Issue by ukirfan** [owncloud/core#7165]
Hello,

When people share a folder or file  there is a checkbox to " notify by email". 
(REQUIREMENT: end users want a simple email notification that such an item has been shared "without" any link.) there is no SEND notification button. 

where as for " share link "  there is  a "SEND" button which emails the link.

code FILE : \\owncloud\core\ajax\share.php 
action= share

Regards,
IA

**Comment by blizzz** [comment]
Meanwhile, an error message is shown, when a user could not be notified. Is there anything left to do here?

**Comment by Xenopathic** [comment]
We do what we can reasonably do
