### ISSUE TITLE
Feature Request: modificate progressbar while file upload

### ISSUE THREAD

**Issue by dietmaroc** [owncloud/core#7173]
State so far:
- If your uploading a file via web interface, the progressbar shows the
ratio of the already transfered data amount.
- By beeing cached at server side before beeing saved to the file system,
a delay occures, after the file transfer over network was succesful done.
- In this delay time. The progressbar doesn't move any more.

Desired Change:
Display the progress bar that way, that the ratio of the coloured lenght is considering the upload time including the transfer time from chache to filesystem correctly.

**Comment by PVince81** [comment]
Since 9.1 the web UI uses Webdav PUT which streams the file directly to storage, so this delay should disappear.
