### ISSUE TITLE
getting some error logs

### ISSUE THREAD

**Issue by SunboX** [owncloud/core#7180]
### Expected behaviour
no log

### Actual behaviour
gettings logs

### Steps to reproduce
Don't know where it happens. Seems to be a cron or sync client.

### Server configuration
Operating system:
Raspbian Weezy

Web server: 
Raspberry Pi Model B

Database:
SQLite

PHP version:
5.4

ownCloud version: (see ownCloud admin page)
6.0.1

Updated from an older ownCloud or fresh install:
Update from 6.0.0

List of activated app:
default ones

The content of config/config.php: (Without the database password and passwordsalt)
```
<?php
$CONFIG = array (
  'instanceid' => 'ocd93cb20***',
  'passwordsalt' => '***',
  'datadirectory' => '/var/www/data',
  'dbtype' => 'sqlite3',
  'version' => '6.0.0.16',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 2147483648,
  'allowZipDownload' => true,
)
```

Are you using external storage, if yes which one:
no

### Client configuration
Browser: Firefox 26.0

Operating system:
Mac OS X 10.9.1

#### Web server error log
```
no
```

#### ownCloud log (data/owncloud.log)
```
{"app":"PHP","message":"json_encode(): Invalid UTF-8 sequence in argument at /var/www/lib/private/log/owncloud.php#74","level":2,"time":"2014-02-12T15:33:23+00:00"}
{"app":"PHP","message":"filemtime(): stat failed for /var/www/data/smith/thumbnails/42 at /var/www/lib/private/files/storage/local.php#127","level":2,"time":"2014-02-11T22:45:03+00:00"}
```

#### Browser log
```
no
```

**Comment by PVince81** [comment]
Please try again with 7.0.4 where the fix is likely in (or the soon to be coming 7.0.5 or 8.0.1)
Thanks.

If you still have this issue, feel free to reopen.
