### ISSUE TITLE
[FEATURE REQUEST]: Provide admin ability to configure initial display folder

### ISSUE THREAD

**Issue by ser72** [owncloud/core#7181]
Currently when a user logs into ownCloud via their webUI they are brought the "Home" directory.

In an instance when a master user shares a directory to all other users, it would be nice to be able to configure the initially displayed directory as the "Shared" directory, as an example so users don't have to navigate the extra step/steps.

if the configured folder doesn't exist for a user,  Default back to HOME

**Comment by Xenopathic** [comment]
We can change the default page upon login, and there is an issue already open for replacing the user root folder with an external storage -> closing

**Comment by PVince81** [comment]
@Xenopathic can you paste the link to that issue ? Thanks

**Comment by Xenopathic** [comment]
#10198
