### ISSUE TITLE
Fix MappedLocal / Local class definition

### ISSUE THREAD

**Issue by bantu** [owncloud/core#7187]
Problem:
There are two class definition, depending on whether we are on Windows or not. There should be only one class definition. On Windows an instance of MappedLocal should be used, otherwise Local.

Problem:
The inheritance "has the wrong direction". MappedLocal is a Local storage with a path transformation and thus should extend class Local instead of the other way around.

https://github.com/owncloud/core/blob/master/lib/private/files/storage/local.php#L12

**Comment by PVince81** [comment]
MappedLocal is :skull:
