### ISSUE TITLE
add option to create an initial OC database to the occ command line tool

### ISSUE THREAD

**Issue by j-ed** [owncloud/core#7194]
## Expected behavior
As an administrator you should be able to create the initial owncloud database from the command line, using the newly introduced occ command line tool.

## Actual behavior
As an administrator you cannot create an initial owncloud database from the command line.

## Steps to reproduce
1.) open a console window and run the occ command line tool.

#### Server Configuration
OS: Linux 2.6.24-24
Web server: Apache2 2.4.6
Database: MySQL 5.1.73
PHP version: 5.4.23
ownCloud version: 6.0.1

#### Client Configuration
Browser: Firefox 27.0
Operating system: Windows 7

**Comment by DeepDiver1975** [comment]
with 8.1 we have a setup command in place now
