### ISSUE TITLE
The Function constructor is a form of eval.

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#7212]
see https://scrutinizer-ci.com/g/owncloud/core/issues/files/core/js/js.js?selectedSeverities%5B0%5D=15&orderField=path&order=asc#inspectioncomment-31421521

**Comment by LukasReschke** [comment]
http://slexaxton.github.io/Jed/ looks promising

**Comment by LukasReschke** [comment]
> Jed parses plural forms using a grammar instead of running eval. This results in both safer and faster plural-form function generations. The jison grammar that was used to generate the parser is included in the source.

**Comment by LukasReschke** [comment]
Absolutely naive approach without much changes and no idea if it behaves as we want is at https://github.com/owncloud/core/pull/14402
