### ISSUE TITLE
Feature Request: ability to exclude external storage mounts from being synced by sync client

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#7234]
During the tests with mirall (desktop sync client), I saw that you have the ability to sync all possible "mount points" you have. Not only the personal one (home) but also those who are assigned to you. Because I have mount points with capacities >2TB, I immediatly recognized that this will become problematic for many reasons.

Possible reasons to exclude mounts from beeing synced:
1. Capacity limitations
2. Mounts to work with but you want to implement a no sync ability (single download would be still possible = harden misuse)
3. Mounts which are set read only
4. Shared folders
5. Double synced like dropbox (dropbox can use a lot of space...)
6. ...

In particular, the ability to exclude should be a must for an administrator who creates mounts and assignes them to users/groups ect. The other cases are to be discussed.

There are two aspects:
a. core  ... provide the ability to exclude mount points from beeing synced
b. mirall ... exclude the marked mount points from the sync list presented

It is of course a question if we want to differenciate the ability to sync based on the mount itself and/or refine further on the user/group. This question targets core only and not mirall.

**Comment by Aesculapius** [comment]
I think this would be an immensely useful feature! (and has to be seen seperate of issue 100 which looks at the user side.
For me, I include a mount point for users in the "backup" user-group, that points to the backup-folder of their account. This folder contains incremental backups - every 4 hours - using hardlinks. So it really doesn't eat that much space on the server, but if clients start syncing these folders, they turn into terabytes of harddrive space!

So being able as an admin to exclude specific external storage shares from syncing, would be a great feature I think.
Also, I'd like to see an option to also exclude external mount points from being indexed by owncloud, as this also is of no use in case of backup folders and only slows things down. (there is no need to search these folders or anything - you'd just need to have access to them via the webinterface).

**Comment by PVince81** [comment]
If the exclusion is only a "soft" exclusion, one idea would be to have the server return a special WebDAV attribute on the folders that should not be synced, for example "oc:nosync". When the sync client sees this attribute, it would have to skip that folder.
Then in the external storage mount options add an option "Exclude from sync" and make it so that the attribute "oc:nosync" is returned for such mount points.

**Comment by Xenopathic** [comment]
The thing is, the user should *always* be able to override an automatic decision, if they so wish. An admin can suggest that the user doesn't sync a directory, but if the user really wants to synchronise it then they should be able to. I think a way of pushing defaults to the client (that can be overridden) is a better way of solving this than hard-disallowing synchronisation of certain directories. -> #7956

**Comment by mmattel** [comment]
@PVince81 :+1: Admin driven, the user can only sync what is allowed by the precense or abscense of a particular attribute.

@Xenopathic :-1: I disagree. An admin ALWAYS overrides a user decision (or whish), that´s what an admin is for. Having a huge or sensitive datastore that is beeing able to be synced based on a user decision is a no-go. Admin decisions are usually not democratic...

**Comment by hameno** [comment]
Please implement this, I cannot use external storage as my users would never know how to do this themselves (+ I explicitly want to prevent this, as our share is just too big)

**Comment by PVince81** [comment]
Add webdav property to tell sync client to not sync an entry: https://github.com/owncloud/core/issues/26311

**Comment by guruz** [comment]
This is done in recent client versions.
![](https://cloud.githubusercontent.com/assets/2644445/22258989/e928fa92-e263-11e6-9c70-575316035231.png)

For reset see https://github.com/owncloud/core/issues/26311

**Comment by imthenachoman** [comment]
Can't this be achieved by creating an external storage to specific folders (instead of the root folder) and assigning permissions? Like I share `/folder/one` and `/folder/two` instead of `/folder`.

**Comment by mmattel** [comment]
...Yes. I agree that there are two cases: soft and hard "do-not-sync"....
https://github.com/owncloud/core/issues/26311#issuecomment-300794589
