### ISSUE TITLE
Provide Feedback when Sending Email on Share

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#7263]
When sharing a document in ownCloud, if you check the "send email" on sharing a file within the ownCloud system (not an external link), provide a message that indicates the email was sent. Right now, it is not clear that the email was sent properly.

![untitled2](https://f.cloud.github.com/assets/1818977/2196822/d311c50a-98b4-11e3-9400-5dfbb49723f1.png)
How do I know?  Do I need to hit enter to get it to send, or...??? What do I do?

@jancborchardt

**Comment by MorrisJobke** [comment]
The input changes to `Sending...` and then to `E-Mail sent` -> issue fixed
