### ISSUE TITLE
Trashbin: Enable admin config of retention policy

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#7265]
As an admin, I would like a way to easily configure the trash bin policy so that I can set retention policies for files that are being retained - or deleted - by the server automatically.

Acceptance Criteria:
In the admin panel
Have a place where I can set policy visually
Choose between:
Delete oldest files when user quota reaches x % <admin can set x>
Delete oldest files after x days <admin can set x>
Message user that they are nearing quota, and that older deleted files are about to be deleted

**Comment by schiesbn** [comment]
I assume that this is superseded by https://github.com/owncloud/core/issues/16300 which was implemented for 8.2

If I missed something feel free to re-open the issue,  @MTRichards

**Comment by MTRichards** [comment]
Yes, superseded - thanks for closing @schiesbn
