### ISSUE TITLE
Edit link (and link from Document) follow to old version of file

### ISSUE THREAD

**Issue by loadaverage** [owncloud/core#7299]
When I upload (or update/save) *.odt file via webdav, edit link (in web interface) show me not updated document. But if I click right on file name (preview mode) I saw updated document.

Additional info:
ownCloud 6.0.1 (stable)
PHP 5.4.4
Debian 3.2.51-1 x86_64

**Comment by gioele** [comment]
This problem is still present in version 8.

The same issue has been reported in https://github.com/owncloud/documents/issues/447.

**Comment by RealRancor** [comment]
Yes, really looks like a dup of https://github.com/owncloud/documents/issues/447 So why keep this open?
