### ISSUE TITLE
Support for early-failure custom logging class

### ISSUE THREAD

**Issue by ringmaster** [owncloud/core#7339]
ownCloud supports the use of a custom log class by specifying the suffix of the class within the 'log_type' config setting.  However, there may be cases where errors occur prior to (or during!) config class initialization.  In this case, the default setting is used, which is ok, but then subsequent log writes are written to the default log, even after the config setting is read.

It would be ideal to compare the log class being used to the one that is specified in the config, and if these do not match, then the config-specified log class should be created and used for subsequent log writes.

**Comment by Xenopathic** [comment]
This can only happen if an error occurs during the reading of the config, in which case we cannot get the right logging backend - at any point during the request. Nothing we can do here.
