### ISSUE TITLE
[6.0.1] Unexistent mountpoint

### ISSUE THREAD

**Issue by nerzhul** [owncloud/core#7373]
Hi,
since issue https://github.com/owncloud/core/issues/7203, i have another issue with mountpoint, after fixing the shares:

Undefined index: at /usr/local/www/owncloud/apps/files_sharing/lib/cache.php#50 
Call to a member function getMountPoint() on a non-object at /usr/local/www/owncloud/apps/files_sharing/lib/cache.php#50

To fix it i have patched the line from:
if (is_array($mount)) {

to:
if (is_array($mount) && isset($mount[key($mount)])) {

But i'm not sure what this fix does on the client.

Can you help me ?

**Comment by PVince81** [comment]
Shared storage has changed a bit in OC 7 (especially now that shares work differently) and shouldn't be as sensitive (aka crashy) as before with orphaned shares.
Also OC 8 contains a repair step to hopefully clean up legacy storage entries (or at least detect bogus ones).

Closing this for now.

If you still have issues with OC 7.0.5 or 8.0.2 please reopen.
