### ISSUE TITLE
Admin Specify Log File Path

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#7442]
Admin can specify syslog and ownCloud log file name (cool).

Admin should also be able to specify, in the ownCloud config file, the path for ownCloud.log files to be written to. On Windows, for example, this path is very important for enabling log management as syslog doesn't seem to work.

If the log file is not write-able, an error shows up in the admin panel that the log file path specified in the config file can't be written.

**Comment by Xenopathic** [comment]
The `logfile` parameter in config.php specified the full path to the ownCloud log, so I guess this is solved
