### ISSUE TITLE
APCu support broken, bad side effects

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#7447]
### Steps to reproduce
1. Use a PHP version with APCu (e.g. 5.5.3)
2. Use an app that makes use of memcache (e.g. user_ldap)
3. E.g. see User List is not populated

It is not reproducible when the cache is already populated.

Reverting https://github.com/owncloud/core/pull/6610 fixes the issue. Alas, it is not sustainable.

The problems is that APCu is not compatible with the doc http://www.php.net/manual/en/apciterator.construct.php but leaves out the first  parameter, see  https://github.com/krakjoe/apcu/blob/simplify/apc_iterator.c#L321-L329 (PHP bug https://bugs.php.net/bug.php?id=65567)

### Expected behaviour
User List should be populated ;) LDAP uses memcache, if available, to store LDAP results.

### Actual behaviour
No users, because malfunction of APCu support breaks getUsers.

### Server configuration
**Operating system**:
Kubuntu 13.10

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.3

**ownCloud version:** (see ownCloud admin page)
current stable6

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Firefox 27.0.1

**Operating system:**
same as server

#### ownCloud log (data/owncloud.log)
```
{"app":"user_ldap","message":"getGroups getGroups---","level":0,"time":"2014-02-27T09:01:57+00:00"}
{"app":"PHP","message":"APCIterator::__construct() expects parameter 2 to be long, string given at \/home\/blizzz\/owncloud\/dev\/stable6\/lib\/private\/memcache\/apcu.php#15","level":3,"time":"2014-02-27T09:02:20+00:00"}
```

**Comment by LukasReschke** [comment]
Ping? :)

**Comment by DeepDiver1975** [comment]
closing this -> not seen in the past months
