### ISSUE TITLE
Missing indexes to speed up large installations

### ISSUE THREAD

**Issue by butonic** [owncloud/core#7474]
Moving this here so we don't forget them:
```sql
   create index oc_group_user_uid on oc_group_user(uid);
   create index oc_share_file_target on oc_share(file_target);
```

**EDIT: Those are no longer needed:**
```sql
   create index oc_filepath on oc_filecache(storage,size);
   create index oc_files_versions_user on oc_files_versions(user);
   create index oc_files_trashsize_user on oc_files_trashsize(user);
```

Would be awesome if someone chould verify that they are actually helpful.

**Comment by butonic** [comment]
@DeepDiver1975 can you enlighten me why this has been closed? obviously these indexes are not yet in core. So who takes care of testing these?

**Comment by DeepDiver1975** [comment]
you seriously ask why I closed something one year back? :speak_no_evil: 

from my pov this issue in it self was not helpful - it contains no longer existing tables are contained wrong syntax. In addition: these optional indexes are documented - done.

**Comment by DeepDiver1975** [comment]
> In addition: these optional indexes are documented - done.

LOL the documentation is referencing this issue - this is so wrong.

**Comment by carlaschroder** [comment]
Well I asked multiple times for an update on this issue and didn't get an answer, so if you think that's funny enjoy a good laugh.

**Comment by butonic** [comment]
well, if indexes are missing it is a bug. nothing else. users should not be forced to find missing indexas in the documentation ...

**Comment by DeepDiver1975** [comment]
> well, if indexes are missing it is a bug. nothing else. users should not be forced to find missing indexas in the documentation ...

thanks for repeating my sentences :speak_no_evil: PR are welcome

**Comment by MorrisJobke** [comment]
> `create index oc_filepath on oc_filecache(storage,size);`

https://github.com/owncloud/core/commit/a339855b4c85812e0c7e35ff3f83a8534fc24289

**Comment by MorrisJobke** [comment]
> create index oc_files_trashsize_user on oc_files_trashsize(user);

6fcd135d0e871a918b2842647385b527cb823bb2

**Comment by MorrisJobke** [comment]
> create index oc_files_versions_user on oc_files_versions(user);

7ad0fee0b56d9ab678cbb52128d427ebd641b05e

**Comment by MorrisJobke** [comment]
I added the remaining indexes in #17498
