### ISSUE TITLE
don't allow upload/creation of .part files

### ISSUE THREAD

**Issue by schiessle** [owncloud/core#7496]
we use the file extension .part for uploading large files. Therefore we ignore .part files and don't expose them in the web ui or to a webdav client.

Our sync client, correctly doesn't upload .part files. Also direct webdav uploads refuse to upload .part files. But it is possible to:
- upload .part files over the web interface
- create a new empty .part file
- rename a regular file to a .part file

This will result in files on the server which are no longer accessible by the user. All this operation should be blocked.

@nickvergessen maybe you want to have a look at it if you have some time? Thanks!

cc @PVince81

**Comment by PVince81** [comment]
This won't be fully fixable as long as OC 7 is supported due to federation, see https://github.com/owncloud/core/pull/7514#issuecomment-118319191 for an explanation.

Moving to 9.0 to keep it in sight.

**Comment by PVince81** [comment]
Since OC 7 will still be around when OC 9 is out, moving to 9.1.

See https://github.com/owncloud/core/pull/7514#issuecomment-118319191 for the explanation why.

**Comment by PVince81** [comment]
CC @cmonteroluque

**Comment by cmonteroluque** [comment]
thanks @PVince81

**Comment by felixheidecke** [comment]
See PR https://github.com/owncloud/core/pull/27149

**Comment by PVince81** [comment]
PR for frontend was merged: https://github.com/owncloud/core/pull/27149

Now requires backend changes @IljaN

**Comment by IljaN** [comment]
@PVince81 #27269

**Comment by PVince81** [comment]
This fix is incomplete, part file upload is still possible with Webdav on v10.0.2.

On v10.0.3 another bug prevents it, but we need this fix this correctly.

Reopening.

**Comment by PVince81** [comment]
@IljaN please have a look

**Comment by PVince81** [comment]
also please add integration tests to make sure we can't:
- upload part files through Webdav
- rename or copy any file to ".part" with Webdav
