### ISSUE TITLE
Show changelog for admins after/before update

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/core#7527]
Admins should be shown a changelog after an update, therefore we can more easily communicate breaking changes like the `trusted_domains` thing and avoid bug reports.

\cc @karlitschek @blizzz @jancborchardt

**Comment by PVince81** [comment]
@nickvergessen you mentionned a similar idea recently ?

**Comment by PVince81** [comment]
Now that the changelog is stored in a bundled file this becomes possible @pmaier1

**Comment by PVince81** [comment]
Have something in a separate app that can be disabled. Not all admin update flows would fit this pattern.
