### ISSUE TITLE
Adding custom actions on the table's header

### ISSUE THREAD

**Issue by fpiraneo** [owncloud/core#7538]
Do someone know if it's possible for an app to add an extra action button on the file's header? As file header I means the red area indicated by the picture below.
Thank you very much.
![schermata 2014-03-04 alle 20 55 47](https://f.cloud.github.com/assets/6309842/2325644/413e7cb6-a3d8-11e3-8514-5a81da43dcfb.png)

::NeedsInfo::app:file::

**Comment by PVince81** [comment]
Yes, would be nice to add support for bulk actions in the `FileActions` structure.
