### ISSUE TITLE
Multiple S3 configurations w/same access keys

### ISSUE THREAD

**Issue by colinc** [owncloud/core#7543]
### Steps to reproduce
1. Admin > External Storage
2. Add an Amazon S3 configuration
3. Add another Amazon S3 configuration with the same keys but a different bucket
4. Browse to the first bucket
5. Browse to the second bucket
### Expected behavior

The second bucket should list the items in the second S3 bucket
### Actual behavior

The second bucket lists the items in the first S3 bucket and throws 404 Not Found errors in the log.

The exception is being caught here:
https://github.com/owncloud/core/blob/master/apps/files_external/lib/amazons3.php#L278
### Server configuration

**ownCloud version:** 6.0.2 (happened on previous 6.x releases)
### Code

It looks like this is a result of a non-unique ID in the AmazonS3 __construct function.

https://github.com/owncloud/core/blob/master/apps/files_external/lib/amazons3.php#L81

Using the same IAM account with unique access keys resolves the problem.

**Comment by DeepDiver1975** [comment]
Secondary s3 storage integration just got move over to https://github.com/owncloud/files_external_s3.

Unfortunately GitHub does not allow to move issues. Please reopen the issue at https://github.com/owncloud/files_external_s3/issues
