### ISSUE TITLE
could not find driver

### ISSUE THREAD

**Issue by kryogenic** [owncloud/core#7551]
This error message is thrown by Doctrine\DBAL\Connection when connect() is called. It's not a great error message, could you perhaps add that the driver might not be installed?

I was setting up the admin user when I ran into this. ownCloud had already created the user oc_username in my mysql database, and I already passed the preliminary set of tests (/lib/private/util.php lines 375-500), so I thought that I had installed all necessary extensions and ownCloud could connect to my db without issues.
It took me a couple of hours to find out that pdo_mysql was required.

While you're at it... https://forum.owncloud.org/viewtopic.php?f=26&t=20125
The error handling in ownCloud setup needs a bit of work imo :+1:

**Comment by Xenopathic** [comment]
We throw an exception if we can't connect to the DB - not much else we can do. PHP modules are checked during setup
