### ISSUE TITLE
Overwrite folder by uploading a file with the same name

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#7573]
### Steps to reproduce
1. Create a folder called "test.txt" in the root folder
2. Create or upload some file inside
3. Prepare a local file called "test.txt"
4. Upload the local file "test.txt" into the root folder (where the dir with the same name exists)
5. The overwrite prompt dialog appears, select "New file" then click "Continue"

### Actual result
Overwrite prompt appears and picking "New file".
"test.txt" appears in the folder as a file, the folder is gone.
Refresh the page and the "test.txt" folder is back.

### Expected result
Overwrite prompt must not appear because it's not possible to overwrite directories.
An error notification could be shown for that file.

### Versions
ownCloud 7 pre-alpha (git master)
Apache 2.4

**Comment by enoch85** [comment]
Add milestone @PVince81 ?

**Comment by PVince81** [comment]
Cannot reproduce on 8.1 pre-alpha git master (8906158d3b6c0f0d3e120cccbe036a2d36f3cdbe)

It is not possible any more to overwrite a folder this way.
