### ISSUE TITLE
Enhancement: Allow admin to create DENY and ALLOW lists for external users

### ISSUE THREAD

**Issue by jmanko** [owncloud/core#7615]
For some auth types, like IMAP, there is no way to restrict users to Owncloud.  As it stands, if they have an email, they have OC access.  

I'd like the admin to have the ability to create both DENY and ALLOW lists.  It can work like other access list methodologies, where I create a DENY list of users, or an ALLOW list of users.

**Comment by LukasReschke** [comment]
`user_external` is tracked at https://github.com/owncloud/apps – please reopen there. THX. Not something for core from my PoV.
