### ISSUE TITLE
Usability enhancement:  Improve content sharing

### ISSUE THREAD

**Issue by scoopex** [owncloud/core#7637]
I often use owncloud to to exchange vacation pictures with friends. Some of these friends do not know owncloud and/or do not know very much about computers. This sometimes prevents them to upload/download content.

Please modify the mail notification mechanism to:
* that the notification language can be defined
* change the wording of the notification text to get a better understanding for users with a lower internet/information technology-affinity
(describe that this access can be used to download and upload files)
* modify the link to open the owncloud interface with the language which corresponds to the mail language

Please modify the of the folder view to:
* help users to ease file upload 
 * add a text description "upload files" to the upload arrow
 * provide a help text which guides users to upload multiple files at once
* help users to ease file download (especially download of a entire folder)
 * add a extra button "download folder" to download the entire folder
 * add a help text to help users to download specific files combined in a zip file

From the view of persons which have a good it-affinity this seems to be too trivial to make changes like this - but it seems to be relevant for all other users.

**Comment by jancborchardt** [comment]
We solved most of these issues. If there are any further issues, please open them as _individual_ issues.
