### ISSUE TITLE
network quota (Data usage)

### ISSUE THREAD

**Issue by slurm** [owncloud/core#7705]
It would be nice to be able to set a limit on users on how much data they use, (not diskspace).  and that would also show Total transfered, and monthly usage,  for them
and for admins. and also sort, to see who uses the most, etc.. 

Being able to set it individually on each user, or have groups that have predefined would be nice as well.

**Comment by hamiltont** [comment]
+1. I looked into the available hooks, not sure this would be possible for an optional app to implement given the current setup. Personally, I don't think this feature request is to "count 100% of network traffic" (which is really tough), I think it is "count usage each time someone downloads a file/directory, either directly or via the share API" (which is probably much easier to implement). I would love to set a quota, in terms of GB/week perhaps, for how much a user is allowed to download

**Comment by PVince81** [comment]
more ideas in duplicate ticket https://github.com/owncloud/core/issues/12787 (by group).

I'm not sure ownCloud / PHP can really measure network traffic because it's on another level.
Also it is possible that the web server adds more overhead or even use compression to reduce the traffic (mod_deflate?).

**Comment by PVince81** [comment]
@tboerger you talked about getting server metrics recently. Not sure where / how this would fit and whether this needs anything to be added to core that cannot be done on a different level
