### ISSUE TITLE
console.php error from command line

### ISSUE THREAD

**Issue by oclmuc** [owncloud/core#7715]
### Steps to reproduce
1. call console.php from the command line, e.g. "php console.php" or with the "occ" client

### Expected behaviour
console functionality should be available

### Actual behaviour
error:
Status: 302 Moved Temporarily
X-Powered-By: PHP/5.5.9
Set-Cookie: xxx93ee43baf=xxxfmuh0ishb1uj425ttc32jf5; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Strict-Transport-Security: max-age=31536000
Location: https://
Content-type: text/html

Notice: Undefined index: SCRIPT_FILENAME in /mnt/webh/e1/05/xxx/htdocs/owncloud/lib/base.php on line 103
Notice: Undefined index: SCRIPT_NAME in /mnt/webh/e1/05/xxx/htdocs/owncloud/lib/private/request.php on line 122

### Server configuration
**Operating system**:
shared hosting on Strato Powerweb, SunOS 5.10

**Web server:**
Apache/2.2.26 (Unix) 

**Database:**
mySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
6.0.2

**Updated from an older ownCloud or fresh install:**
update 

Also see:
https://forum.owncloud.org/viewtopic.php?f=26&t=20266

**Comment by DeepDiver1975** [comment]
refs #https://github.com/owncloud/core/issues/15054

**Comment by DeepDiver1975** [comment]
OC6 is out of support -> close
