### ISSUE TITLE
Configurable avatar, quota, email updates and ldap

### ISSUE THREAD

**Issue by PtY1968** [owncloud/core#7729]
The check period of updates on ldap jpegPhoto and thumbnailPhoto properties is fixed (one day).
It should be configurable on administrator console.

**Comment by blizzz** [comment]
FYI, Affects also email and quota values

**Comment by blizzz** [comment]
Everything is refreshed upon login, and everything leightweight (without avatar) on search, when LDAP is queried anyway.

**Comment by PtY1968** [comment]
Wonderful! :)
