### ISSUE TITLE
Audit logging

### ISSUE THREAD

**Issue by PtY1968** [owncloud/core#7730]
I  used the app superlog for logging the user's activity, but it show only the activity on the web interface not in his/her desktop/mobile client. I could handle it with modify one of the core .php file, but every upgrade shut down this feature and I need to do it again.
The perfect way (I think) a core audit logging possiblity (with configurable syslog server feature too). I think this should be an enterprise level feature.

**Comment by Xenopathic** [comment]
Please try with the activity app
