### ISSUE TITLE
Upgrade from 5.x to 6.x fails if using pgsql database and Doctrine-DBAL 2.4.2

### ISSUE THREAD

**Issue by AdamWill** [owncloud/core#7778]
This is a bit of an odd issue, and we recognize it's not really a clearly supported case, but we thought it would still be best to report to OC devs initially.

We (Fedora) are working to make OwnCloud 6.x available to Fedora 20 users (and eventually F19 and RHEL 6/7, via EPEL). As I've discussed with some OC and Doctrine devs already, we've been working to use the system copy of Doctrine-DBAL instead of OC's bundled copy, and both OC and Doctrine devs have been helpful in getting OC's patches to DBAL upstreamed. Upstream Doctrine 2.4.2 includes all but one of OC's patches.

In testing with the combination of OC 6 and upstream DBAL 2.4.2, I've confirmed that OC 6 deployment with MySQL, sqlite and PostgreSQL databases all work fine. Upgrades from OC 5 to OC 6 with MySQL and sqlite both work fine. However, upgrades from OC 5 to 6 with PostgreSQL databases fail in this configuration. The failure doesn't look the same as any of the ones in https://github.com/owncloud/core/issues/6310 , though, and indeed as near as I can tell, all the fixes identified in that bug are a part of DBAL 2.4.2 already. It looks like it's some kind of new issue.

The failure I get is this:

    An exception occurred while executing 'DROP INDEX file_map_lp_index':
    SQLSTATE[2BP01]: Dependent objects still exist: 7 ERROR: cannot drop
    index file_map_lp_index because constraint file_map_lp_index on table
    oc_file_map requires it HINT: You can drop constraint file_map_lp_index
    on table oc_file_map instead.

is this enough info to work with? I can try and provide step-by-step instructions to reproduce using a fresh Fedora 20 deployment (in a VM is the easy way to test, obviously) if it helps.

Thanks!

**Comment by PVince81** [comment]
Is this still an issue ?

**Comment by AdamWill** [comment]
god, I don't honestly remember the details and I'm not sure I have a lot of time to try and reproduce. I've got all Fedora repo-based platforms up to minimum OC 6 at this point, though, so whatever it was it clearly didn't stop me...

**Comment by DeepDiver1975** [comment]
closing as oc5 is long gone .... :speak_no_evil:
