### ISSUE TITLE
[6.0.2] oc_fscache table

### ISSUE THREAD

**Issue by ser72** [owncloud/core#7788]
The following is occuring in the Postgresql log:
```
2014-03-18 08:14:13 UTC ERROR:  relation "oc_fscache" does not exist at character 18
2014-03-18 08:14:13 UTC STATEMENT:  SELECT "id" FROM "oc_fscache" WHERE "user" = $1 LIMIT 1
```

In examining the code, there are very few references to the oc_fscache table.  Several issues existed, but they are mostly early oC5.  My guess, from research, is that this table is a precursor to the oc_filecache table, however I cannot be certain of that.

In this particular instance, the Postgresql database does NOT contain this table.  ownCloud seems to be referencing it somehow and for some reason and that causes this error.

Everything seems to be working as it should, but this error still appears occasionally.

We have been unable, at this time, to determine what set of actions cause this error to occur.

**QUESTION**
What is this oc_fscache table?
Does it exist in oC6?
If not, can the references in the code be removed so it doesn't query the database for that table?

**NOTE**
This instance of ownCloud was initially installed with oC6 and never the early versions of oC5.

**Comment by LukasReschke** [comment]
I assume this is fixed => Closing.
