### ISSUE TITLE
[FEATURE REQUEST] One Time download for public shares

### ISSUE THREAD

**Issue by ser72** [owncloud/core#7811]
It is desired that when a user shares a file/folder as a link, that as soon as the file/folder is downloaded via the link, the share expires.

In the event there is a folder with multiple files inside, the entire share should not expire until all files are downloaded.  However, as an individual file is downloaded, it should be expired and not be allowed to be downloaded again.

@MTRichards @karlitschek

**Comment by js94x** [comment]
@lupusmeatus 
We would like to use the feature in your described way too.

Does someone knows a plugin that provides this function ?

**Comment by PVince81** [comment]
@pmaier1
