### ISSUE TITLE
[Feature Request] Share as link read notification

### ISSUE THREAD

**Issue by ser72** [owncloud/core#7812]
It is desired that when a shared link is accessed, a log is written (via the Share Log app) stating the file was accessed.

Currently, there is a log indicating the file/folder was shared as a link, but nothing when the link is actually accessed

@karlitschek @MTRichards

**Comment by gig13** [comment]
@MTRichards @karlitschek 
Any idea if/when this will be available?

**Comment by MTRichards** [comment]
It is on the backlog now, but it has no date. We are full up for oC 8.0 and 8.1, so no sooner than 8.2.

**Comment by MTRichards** [comment]
We have demonstrated that this is available in the activity stream for a user, but not in the log file. Still needed, possibly 8.2.

**Comment by derekblankmccoy** [comment]
This is an absolute must for a project I'm working on. Shared files with users must have traceability of who downloaded them and when. It's not so much to see if a user read an important document, but mainly to check who HASN'T read it. "Did you get the memo?" "No" "I shared it with the group" "Oh, well I didn't get it".
There's an app that can sort of do it called "file counter", but it doesn't work with oc8, and theres another one called "eslog" that sends hooks to elasticsearch but it doesn't record file reads as it doesn't seem to be a filesystem hook that gets recorded.

*** Willing to put a bounty on this feature ***

**Comment by jazzcrack** [comment]
Visible in log and in UI too is needed.

**Comment by Xenopathic** [comment]
It does not make sense for this information to be logged to the log file, since the user (who is the only one interested in the information) cannot see that. The Activity app provides the appropriate place to display this information.
