### ISSUE TITLE
[FEATURE REQUEST] Share link with multiple users has different link

### ISSUE THREAD

**Issue by ser72** [owncloud/core#7813]
It is desired to track which individuals access a shared link.
In the instance that a link is shared with an email, each email address should receive a separate link to access the data.  This, in conjunction with #7812 will allow admins to see when and who accessed a link.

@MTRichards @karlitschek

**Comment by jancborchardt** [comment]
That exactly is the plan as written up in https://github.com/owncloud/core/issues/3224 (back in May 2013 ;)

> future: generate unique link per email address so revocation on a per-person basis is possible

Closing this in favor of the other issue hence.
