### ISSUE TITLE
Dropbox Mount File 50MB Download issue

### ISSUE THREAD

**Issue by pittsey44** [owncloud/core#7821]
I have a dropbox mounted into owncloud, works very well except for when downloading files over 50MB, it offers me the 'save as' dialog box, but when clicked to save it downloads immediately and all I get is a 1KB file, doesn't matter what the file type is.

Large files download ok if they are in the actual file structure of owncloud, its only the dropbox mount

Help!!

Am I missing something?

**Comment by DeepDiver1975** [comment]
hopefully fixed with 8.2 where we migrate to the official dropbox sdk - refs https://github.com/owncloud/core/issues/13841
