### ISSUE TITLE
Add option to reactivate current theme after upgrade

### ISSUE THREAD

**Issue by aiguanachein** [owncloud/core#7822]
The 'Theme' parameter from config.php its emptied after each update in order to prevent breaking anything between version changes. Could you add a parameter that defines whether "taking the risk" and mantaining the current theme?

**Comment by MorrisJobke** [comment]
Can be achieved by placing another file to the config/ folder named `theme.config.php` with following content:

```
<?php

$CONFIG = [
	'theme' => 'my_theme'
];
