### ISSUE TITLE
filecache.encrypted_size = 0 -> upgrade fails

### ISSUE THREAD

**Issue by sfabel** [owncloud/core#7849]
### Steps to reproduce
1. upgrade from 5.0.14a to 6.0.2 (Enterprise releases)
2. IF filecache.encrypted_size has entries with '0' in them
3. THEN upgrade fails

### Expected behaviour
filecache.encrypted_size should be adjusted / fixed on upgrade. As it is, OC gives no indication as to what values are expected there, and the existence of these columns is questionable to begin with if we don't have the encryption app enabled.

### Actual behaviour
On upgrade, the following error message appears:

An exception occurred while executing 'ALTER TABLE "oc_filecache" ALTER 
unencrypted_size SET NOT NULL': SQLSTATE[23502]: Not null violation: 7 ERROR: 
column "unencrypted_size" contains null values

Subsequent accesses to the index.php yield:

An exception occurred while executing 'SELECT "id" FROM "oc_jobs" WHERE "class" = ? AND "argument" = ?': SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "oc_jobs" does not exist LINE 1: SELECT "id" FROM "oc_jobs" WHERE "class" = $1 AND "argument"... ^

If I remember correctly, 5.0.10 or 5.0.11 shipped with a bad db_structure.xml, which introduced these problems. To date I have not been able to resolve what values are expected there by default.

There is no clear recovery path offered, and the two error messages have nothing to do with each other, at least at first glance. Presumably, the upgrade went wrong (restart the upgrade?), but who knows what kind of cruft is now cluttered around my data.

### Server configuration
**Operating system**:  Ubuntu 12.0.4.4

**Web server:**  nginx 1.4.7-1~precise

**Database:** postgresql 9.3.4-1.pgdg12.4+1

**PHP version:** 5.3.10-1ubuntu3.10

**ownCloud version:** 6.0.2 Enterprise

**Updated from an older ownCloud or fresh install:** Updated; this database/fileset has been upgraded continuously from 5.0.5 onwards, all Enterprise codebase.

**List of activated apps:**

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'datadirectory' => '/mnt/data',
  'dbtype' => 'pgsql',
  'version' => '6.0.2.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => '2',
  'log_type' => 'syslog',
  'log_file' => '',
  'trashbin_retention_obligation' => '365',
  'theme' => '',
  'maintenance' => false,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'trusted_domains' => 
  array (
    0 => 'host',
  ),
);
```

**Are you using external storage, if yes which one:**  yes; 'local', 'smb', s3

**Are you using encryption:**  no

**Comment by MorrisJobke** [comment]
@cdamken Once you have time: Please have a look if this is still valid ;) Thanks.

**Comment by MorrisJobke** [comment]
The workaround here was often to add the default value `0` to the filesize column before the upgrade. Could be a race condition related to cron.php and the ignored maintenance mode.

I will close this due to inactivity then.
