### ISSUE TITLE
Share API - wrong HTTP code sharing a non-existing file

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#7858]
### Steps to reproduce
1. Execute the following command (adjusting the parameters)
curl -v -u admin:password -f -X POST -F path=test/folder/mimimi.txt -F shareType=0 -F shareWith=oc-jive-user -F publicUpload=false -F permissions=1 http://ec2-54-224-21-59.compute-1.amazonaws.com/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares

Notice: use valid users and a missing target path

### Expected behaviour
HTTP status should be 4xx, so the curl command with the -f option should fail

### Actual behaviour
HTTP status is 200. The status in the body response show a 404 status

### Server configuration
**ownCloud version:**
{"installed":"true","version":"6.0.0.16","versionstring":"6.0.1","edition":""}
{"installed":"true","version":"6.0.2.4","versionstring":"6.0.2","edition":""}

The server response (verbose)
```
< HTTP/1.1 100 Continue
< HTTP/1.1 200 OK
< Date: Mon, 24 Mar 2014 09:21:37 GMT
< Server: Apache/2.2.22 (Ubuntu)
< X-Powered-By: PHP/5.3.10-1ubuntu3.6
< Set-Cookie: oc50748b6487=mbr12jb4mbmqalgt9bu05mtao3; path=/owncloud; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Set-Cookie: oc50748b6487=deprgarjvpi1jfmt8bqfekj7u0; path=/owncloud; HttpOnly
< Set-Cookie: oc_username=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/owncloud
< Set-Cookie: oc_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/owncloud
< Set-Cookie: oc_remember_login=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/owncloud
< Set-Cookie: oc_username=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/owncloud/
< Set-Cookie: oc_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/owncloud/
< Set-Cookie: oc_remember_login=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/owncloud/
< Vary: Accept-Encoding
< Content-Length: 179
< Content-Type: text/xml; charset=UTF-8
< 
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>404</statuscode>
  <message>wrong path, file/folder doesn't exist.</message>
 </meta>
 <data/>
</ocs>
* Connection #0 to host ec2-54-224-21-59.compute-1.amazonaws.com left intact
* Closing connection #0
```
Notes:
I've only checked with that call. Other calls might have the same behaviour

**Comment by enoch85** [comment]
> As you'll have seen on the mailing list doesn't look like this can be fixed till OC8 now.

@tomneedham @PVince81 Issue solved?

**Comment by DeepDiver1975** [comment]
> HTTP status should be 4xx, so the curl command with the -f option should fail

as of today the owncloud api being based on the OCS spec does not use http error codes -> closing as won't fix
