### ISSUE TITLE
Error adding Dropbox as external storage.

### ISSUE THREAD

**Issue by Amplificator** [owncloud/core#7863]
### Steps to reproduce
1. Followed documentation for adding Dropbox: http://doc.owncloud.org/server/6.0/admin_manual/apps/files_external/index.html

### Expected behaviour
After clicking "Grant access" it should add Dropbox as external storage.

### Actual behaviour
When clicking "Grant access" I get a window saying:

```
Fetching request tokens failed. Verify that your Dropbox app key and secret are correct.
```
However, they are correct.

I have tried adding the following SSL root certificates (using the 'Personal' page for the account I'm trying to add Dropbox to):
- The SSL certificate I created for the server on which I run ownCloud.
- From www.dropbox.com
- Go Daddy Class 2 Certification Authority Root Certificate 
- Go Daddy Secure Server Certificate (Intermediate Certificate)
- Go Daddy Secure Server Certificate (Cross Intermediate Certificate)
- https://code.google.com/p/google-drive-sdk-samples/source/browse/php/libs/gd-v2-php/io/cacerts.pem

### Server configuration
**Operating system:**
Debian Testing (64-bit)

**Web server:**
nginx-extras 1.4.7-1

**Database:**
postgresql 9.3.3-2

**PHP version:**
php5-fpm 5.5.9+dfsg-1

**ownCloud version:**
6.0.2+dfsg-1

**Updated from an older ownCloud or fresh install:**
Fresh install.

**List of activated apps:**
Currently all built-in apps except encryption, but disaling them except for 'External storage' have no effect.

**The content of config/config.php:**
'forcessl' => true

**Are you using external storage, if yes which one:**
Google Drive is mounted and working fine.

**Are you using encryption:**
No

### Client configuration
**Browser:**
Firefox, Chrome, Internet Explorer

**Operating system:**
Windows 8 and Windows 8.1

#### ownCloud log (data/owncloud.log)
Nothing shows up related to this problem.

**Comment by DeepDiver1975** [comment]
we will move to the official dropbox sdk in OC8.2 - https://github.com/owncloud/core/issues/13841 - closing this issue therefore
