### ISSUE TITLE
Path is not readable - wedav // DEVONthink

### ISSUE THREAD

**Issue by jozefmares** [owncloud/core#7865]
Hello,

I have problem with syncing DEVONthink using Owncloud.

Apache setup:
<code>
<Directory /var/www/html/owncloud>
AllowOverride All
RewriteEngine On
SetEnv MOD_X_SENDFILE_ENABLED 1
XSendFile On
XSendFilePath /tmp/oc-noclean
</Directory>
</code>
Apache built-in webdav module is disabled.

Using official client sync works perfectly.

Using DEVONthink built-in webdav sync plugin fails on error 403.

Snap from Apache log:
<code>
 "MOVE /remote.php/webdav/devon.dtSyncStore/transactions/1E3AC67D-92F9-42E6-BF3A-6053ED87197C/incomplete/C2E3A06D-C6DA-49B0-B1DF-F16F320EA79C HTTP/1.1" 403 242 "-" "DEVONthink Sync Plugin/2.5"
</code>

Snap from owncloud.log:
<code>
files\/devon.dtSyncStore\/transactions\/1E3AC67D-92F9-42E6-BF3A-6053ED87197C\/incomplete\/C2E3A06D-C6DA-49B0-B1DF-F16F320EA79C' is not readable !!!",
</code>

Using Cadaver I found this:
 * moving C2E3A06D-C6DA-49B0-B1DF-F16F320EA79C to blah
<code>
dav:/remote.php/webdav/devon.dtSyncStore/transactions/1E3AC67D-92F9-42E6-BF3A-6053ED87197C/incomplete/> move C2E3A06D-C6DA-49B0-B1DF-F16F320EA79C blah
Moving `/remote.php/webdav/devon.dtSyncStore/transactions/1E3AC67D-92F9-42E6-BF3A-6053ED87197C/incomplete/C2E3A06D-C6DA-49B0-B1DF-F16F320EA79C' to `/remote.php/webdav/devon.dtSyncStore/transactions/1E3AC67D-92F9-42E6-BF3A-6053ED87197C/incomplete/blah':  succeeded.
</code>

 * moving blah to C2E3A06D-C6DA-49B0-B1DF-F16F320EA79C (reversed)
<code>
dav:/remote.php/webdav/devon.dtSyncStore/transactions/1E3AC67D-92F9-42E6-BF3A-6053ED87197C/incomplete/> move blah C2E3A06D-C6DA-49B0-B1DF-F16F320EA79C
Moving `/remote.php/webdav/devon.dtSyncStore/transactions/1E3AC67D-92F9-42E6-BF3A-6053ED87197C/incomplete/blah' to `/remote.php/webdav/devon.dtSyncStore/transactions/1E3AC67D-92F9-42E6-BF3A-6053ED87197C/incomplete/C2E3A06D-C6DA-49B0-B1DF-F16F320EA79C':  failed:
403 Forbidden
</code>

What should I investigate to identify error and achieve successful sync with DEVONThink?

Thanks.

**Comment by PVince81** [comment]
Thanks, glad to hear it worked for you now. Closing.
