### ISSUE TITLE
Local file incorrectly deleted due to server timeout

### ISSUE THREAD

**Issue by mdieterich** [owncloud/core#7868]
This may be a challenging bug to reproduce, but I've seen it happen on a few occasions now and am convinced the behavior is not ideal.  First a bit about my setup.  I have a reverse proxy running nginx, which redirects clients to multiple ownCloud instances running under apache.  Connections are tracked based on IP address, so clients are predictably routed to the same ownCloud instance.  The server side is running ownCloud version 6.0.2, with the client running 1.5.3.

We were having some issues with clients uploading large files.  Initially we were testing with a 16Gb file, but ultimately could cause a repeat of the failure with a 6Gb file.  The upload progressed a variable amount through the process.  Some times it completed.  Other times it failed part way through the upload.  A few times, the upload failed AND the local file was deleted!  Ultimately, we tracked this down to a timeout between the proxy and the apache servers, we'd see error messages like this:

upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.116.73.2, server: sync.cs.brown.edu, request: "PUT /remote.php/webdav/xfer/mmandal.tgz-chunking-1569175972-678-677 HTTP/1.1", upstream: "https://10.116.111.64:443/remote.php/webdav/xfer/mmandal.tgz-chunking-1569175972-678-677", host: "sync.cs.brown.edu"

upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.116.73.2, server: sync.cs.brown.edu, request: "PROPFIND /remote.php/webdav/ HTTP/1.1", upstream: "https://10.116.111.64:443/remote.php/webdav/", host: "sync.cs.brown.edu"

upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.116.73.2, server: sync.cs.brown.edu, request: "PUT /remote.php/webdav/xfer/mmandal.tgz-chunking-1569175972-678-677 HTTP/1.1", upstream: "https://10.116.111.66:443/remote.php/webdav/xfer/mmandal.tgz-chunking-1569175972-678-677", host: "sync.cs.brown.edu"

Since increasing the timeout on the nginx proxy, things have been working just great. But we wanted to alert the community and let them know that this type of server side error can somehow cause a file local to the client.  This is what had us really concerned, users were having their files just disappear.

I have a copy of the sync client log during one of these failures, if it would be of help to see what was going on and how it ever got into a state where it thought the local file should be deleted.  Let me know if there is interest and, if so, how to get this 17M log to you.

Thanks!

Mark

**Comment by Xenopathic** [comment]
If anyone is still getting issues, please open an issue on the client repo.
