### ISSUE TITLE
Add repair step to delete file cache when storage entry is gone

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#7874]
Delete all "oc_filecache" entries where there is no matching entry in the "oc_storages" table.

This could happen after running #7539 but also in some other cases or old bugs where the oc_filecache for deleted users wasn't deleted.

**Comment by PVince81** [comment]
@DeepDiver1975 setting to 8.1, it's about time we implemented this.
Please set to backlog if not acceptable.

**Comment by MorrisJobke** [comment]
It is now a command: #15437

@PVince81 Should we move this to a repair step?

**Comment by PVince81** [comment]
Hmm maybe if we consider that the upgrade time is the best time to do a bit of cleanup.

**Comment by MorrisJobke** [comment]
> Hmm maybe if we consider that the upgrade time is the best time to do a bit of cleanup.

I don't think so, because this step could take very long and simply would longer the maintenance for no actual reason. This cleanup can be done while running the instance in normal mode with no impact (except the load impact on the database for doing the query)

**Comment by MorrisJobke** [comment]
I would leave this as it is now.
