### ISSUE TITLE
[6.0.2] Many SQL inserts/deletes upon file upload

### ISSUE THREAD

**Issue by ser72** [owncloud/core#7876]
A user synced a folder with a git repository that he just had pulled into.
The syncing of around 400 files was extremely slow (more so than usual)
Here's the breakdown of one of those requests:

![one](https://f.cloud.github.com/assets/5174383/2513656/ec64fdc2-b431-11e3-8083-bad400e715c4.PNG)

As you can see there are literally hundreds of INSERTS into the oc_permissions table

![two](https://f.cloud.github.com/assets/5174383/2513665/06e1006a-b432-11e3-852d-0aac60ddbd66.PNG)

![three](https://f.cloud.github.com/assets/5174383/2513674/1624ddd0-b432-11e3-8e45-9fc6806b6de4.PNG)
![four](https://f.cloud.github.com/assets/5174383/2513679/24f8dec4-b432-11e3-93dc-a5e0f18c2a6c.PNG)

The time is spent in OC\Files\View::getDirectoryContent . It seems that the code is iterating over a complete directory tree - on every request….

@DeepDiver1975   States this is potentially fixed in oC7 with an option to not perform a complete file scan.
@schiesbn : Per @DeepDiver1975 can you confirm?

**Comment by DeepDiver1975** [comment]
oc8.1 will come with a cron based version cleanup - refs https://github.com/owncloud/core/issues/13117
