### ISSUE TITLE
Cache image dimensions

### ISSUE THREAD

**Issue by jbtbnl** [owncloud/core#7881]
Feature request: cache the dimensions of all images.

I'm currently working on a seamless display for the Gallery app (https://github.com/owncloud/gallery/pull/17). The current situation is that pictures get downloaded and the dimensions are calculated at the client side. After enough pictures for an entire row are downloaded the images of that row are justified and then displayed. Therefore it takes a while before the first row of images is shown, forcing the user to wait longer then necessary.

The above can be fixed by caching the dimensions of all images. The dimensions can be sent to the client before actually downloading the images, enabling the client to calculate the justification beforehand and display the image instantly on arrival at the right location.

**Comment by oparoz** [comment]
Seems this is no longer necessary as thumbnails are now displayed quickly in the gallery. Can we close this?

**Comment by oparoz** [comment]
Now that we generate the max preview, it should be easy to add its dimensions to the file cache at generation time.
