### ISSUE TITLE
Slowness in owncloud (storage in swift)

### ISSUE THREAD

**Issue by leonardofln** [owncloud/core#7882]
**Steps:** 
- Go Apps (/ settings / apps installed?) 
-> Disable all active apps 
-> Enable only the app "External storage support" 
- Go <User> -> Admin (/ settings / admin) 
-> Under "External Storage", provide the name of the folder, data connection and choose the storage type "OpenStack Object Storage" 
-> The icon will become green if the connection was established 
- Click the "Files" icon 
- And then in the Swift folder that was previously configured 

**Expected Result:**
- List files / directories Swift folder without slowdowns 

**Current results:**
- You are listing the files / directories Swift folder too slowly 

**Versions:**
- OwnCloud 6.0.1 
- PHP 5.4.4 
- MySQL 5.0.10 
- Apache 2.4.2 
- Windows 7 32bit

**Notes:**
- I added in each method swift.php file (apps / filex_external / lib), written in owncloud.log to know how many times each method was run. 
- I also added the writing on owncloud.log the execute () method of Curl.php (apps/files_external/3rdparty/php-opencloud/lib/OpenCloud/Common/Request) file to see how many requests were being made. 
- With 4 files in the folder Swift, ownCloud made approximately 300 CURL requests to the server, and this 230 requests were from the doesObjectExist() method (swift.php).

**Comment by enoch85** [comment]
Any progress here?

**Comment by PVince81** [comment]
Yeah, my PR that no one wants to review: https://github.com/owncloud/core/pull/7897

**Comment by PVince81** [comment]
Tagging as 8.2 like the PR

**Comment by PVince81** [comment]
PR was moved to 9.0 and there is a discussion whether there's a better approach.

**Comment by PVince81** [comment]
The stat cache has finally been merged into 9.1.
