### ISSUE TITLE
Send HTTP 500 instead of 200 on PHP error

### ISSUE THREAD

**Issue by guruz** [owncloud/core#7890]
With a broken PHP (can happen anytime when developing a storage backend or anything else :-) the server still sends a HTTP 200 to the sync client when doing WebDAV requests, e.g.:

```
 << 200 OK 1.43kB
    Server: nginx/1.4.1
    Date: Wed, 26 Mar 2014 12:57:11 GMT
    Content-Type: text/html
    Transfer-Encoding: chunked
    Connection: keep-alive
    X-Powered-By: PHP/5.3.27
    Expires: Thu, 19 Nov 1981 08:52:00 GMT
    Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
    Pragma: no-cache

    <br />
    <font size='1'><table class='xdebug-error xe-fatal-error' dir='ltr' border='1' cellspacing='0' cellpadding='1'>
    <tr><th align='left' bgcolor='#f57900' colspan="5"><span style='background-color: #cc0000; color: #fce94f; font-size: x-large;'>( ! )</span> Fatal error: Using $this when not in object context in ..../webdav.php on line <i>527</i></th></tr>
    <tr><th align='left' bgcolor='#e9b96e' colspan='5'>Call Stack</th></tr>
    <tr><th align='center' bgcolor='#eeeeec'>#</th><th align='left' bgcolor='#eeeeec'>Time</th><th align='left' bgcolor='#eeeeec'>Memory</th><th align='left' bgcolor='#eeeeec'>Function</th><th align='left' bgcolor='#eeeeec'>Location</th></tr>
    <tr><td bgcolor='#eeeeec' align='center'>1</td><td bgcolor='#eeeeec' align='center'>0.0002</td><td bgcolor='#eeeeec' align='right'>636464</td><td bgcolor='#eeeeec'>{main}(  )</td><td title='..../remote.php' bgcolor='#eeeeec'>../remote.php<b>:</b>0</td></tr>
    <tr><td bgcolor='#eeeeec' align='center'>2</td><td bgcolor='#eeeeec' align='center'>0.0070</td><td bgcolor='#eeeeec' align='right'>1191392</td><td bgcolor='#eeeeec'>require_once( <font color='#00bb00'>'..../webdav.php'</font> )</td><td title='..../remote.php' bgcolor='#eeeeec'>../remote.php<b>:</b>40</td></tr>
    </table></font>
```

Can we somehow get the server to always send a 5xx error? This helps us making the syncing less fragile (right now we use sanity checks like checking if the reply is text/xml etc)

I tested this with nginx, php-fpm and oC 5.0.13, maybe this is a setup issue or was already fixed

CC @dragotin @ogoffart @danimo

**Comment by enoch85** [comment]
Any update here @guruz ?

**Comment by guruz** [comment]
This was more of a general bug report, where it came from here doesn't play a role.

As far as I (not very much) understand the server architecture a WebDAV request can trigger any app load and any bug in an app could then create such an invalid error..

**Comment by PVince81** [comment]
The behavior in general is hard to control, especially with the messy base.php and the several different entry points.

I'm able to reproduce the issue in question by adding `$this->test()` anywhere inside of "remote.php" (the one in the ownCloud root) or "files/remote.php". If I do a PROPFIND on "remote.php/webdav" it will return 200 OK with an error page.

This is mostly similar to https://github.com/owncloud/core/issues/11834

**Comment by PVince81** [comment]
@DeepDiver1975 @LukasReschke  what do you think ?

I'm not sure what code generates that error page nor why PHP would choose to return 200.

**Comment by MorrisJobke** [comment]
> I'm able to reproduce the issue in question by adding $this->test() anywhere inside of "remote.php" (the one in the ownCloud root) or "files/remote.php". If I do a PROPFIND on "remote.php/webdav" it will return 200 OK with an error page.

On current master this is handled with a 500, except the case it is before the `require 'lib/base.php';` in https://github.com/owncloud/core/blob/675c6963ba2986e8a5609d5a2cf79e1e89167947/remote.php#L87

Also broken apps can't create a 200 anymore. So this is fixed. Closing.

**Comment by chrissound** [comment]
Might be the following bug: https://bugs.xdebug.org/view.php?id=587
