### ISSUE TITLE
Deleting some files/folders permanently

### ISSUE THREAD

**Issue by heaven988** [owncloud/core#7892]
I think that some behaviour of owncloud is not very convenient.

The trash bin is very usefull, so we can get back the file we delete by mistake (even with the sync-client). And the behaviour of the trash bin is good (as it is describe here : http://doc.owncloud.org/server/6.0/user_manual/files/deletedfiles.html).

But sometimes, we just want to delete permanently a big file or a big folder (a deleting of a 72GB folders is actually in progress), and we have to wait that this folder is moved in the trash_bin, and that take a lot of time (like an hour for some folders...), whereas i am sure that the delete must be permanently.

Is it possible to add an option "Deleting permanently" when we choose to delete something ? It will be very usefull in my case, but i think i am not the only one in this case.

I didn't find any subject with this proposal for now, i hope i didn't miss one :)
Thanks to all the developers for this awesome tool, owncloud is nearly perfect ;)

**Comment by MorrisJobke** [comment]
> But sometimes, we just want to delete permanently a big file or a big folder (a deleting of a 72GB folders is actually in progress), and we have to wait that this folder is moved in the trash_bin, and that take a lot of time (like an hour for some folders...), whereas i am sure that the delete must be permanently.

This has changed a lot. We fixed the trashbin logic to move the files instead of copying. So the deletion is more or less instant. If you still have trouble with this issue feel free to reopen the ticket. Thanks :)
