### ISSUE TITLE
LDAP TLS missed on testConfiguration

### ISSUE THREAD

**Issue by philtweir** [owncloud/core#7908]
### Notes

Test Configuration seems to miss the default TLS setting. The LDAP wizard (in lib/wizard.php:guessPortAndTLS(...)) can discover it and set the configuration variable, but the test configuration, as it does not use settings not passed in the $_POST variable, does not have any ldapTLS setting and, on a server requiring TLS reports connection problems.

As a workaround on admin/testConfiguration.php:32
- $connection = new \OCA\user_ldap\lib\Connection($ldapWrapper, '', null);
+ $connection = new \OCA\user_ldap\lib\Connection($ldapWrapper, '');

or manually setting the TLS value before passing the $_POST variable setConfiguration.

### Steps to reproduce
1. Require TLS on LDAP server
2. Fill in details on Owncloud LDAP admin
3. Test Configuration (under Advanced)

### Expected behaviour
Message saying "The configuration is valid and the connection could be established!"

### Actual behaviour
Message saying "The configuration is valid, but the Bind failed. Please check the server settings and credentials."

### Server configuration
**Operating system**: Ubuntu 13.10

**Web server:** Apache/2.4.6 (Ubuntu)

**PHP version:** PHP 5.5.3-1ubuntu2.2

**ownCloud version:** (see ownCloud admin page)  ownCloud 6.0.2 (stable)

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:**
 Activity
Calendar
Contacts
Deleted files
Documents
First Run Wizard
Full Text Search
LDAP user and group backend
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Versions
Video Viewer
JavaScript XMPP Chat 3rd Party	

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => 'oc54167ce45b',
...
  'trusted_domains' => 
  array (
    0 => 'XXX.XXX.XXX',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '6.0.2.2',
  'installed' => true,
  'forcessl' => true,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => '0',
);

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

### Client configuration
**Browser:** Firefox 28.0

**Operating system:** Ubuntu 13.10

#### Web server error log

No output due to AJAX request

#### ownCloud log (data/owncloud.log)
```
 {"app":"user_ldap","message":"LDAP error Confidentiality required (13) after calling ldap_bind","level":0,"time":"2014-03-27T09:27:49+00:00"}
 {"app":"user_ldap","message":"LDAP error Confidentiality required (13) after calling ldap_errno","level":0,"time":"2014-03-27T09:27:49+00:00"}
 {"app":"user_ldap","message":"LDAP error Confidentiality required (13) after calling ldap_error","level":0,"time":"2014-03-27T09:27:49+00:00"}
 {"app":"user_ldap","message":"Bind failed: 13: Confidentiality required","level":3,"time":"2014-03-27T09:27:49+00:00"}     
```

#### Browser log
```
POST https://cloud.numa.lan/index.php/apps/user_ldap/ajax/testConfiguration.php
```

**Comment by blizzz** [comment]
Fixed in master (for 8.1) with https://github.com/owncloud/core/pull/15492

**Comment by didierm** [comment]
FYI : 
With the latest 8.2.2, the LDAP configuration wizard (_LDAP user and group backend 0.7.1_) did not auto-detect TLS (as revealed by packet sniffing network traffic between the LDAP server and the oC server).
I was required to force TLS by means of : 
`update oc_appconfig set configvalue=1 where configkey='ldap_tls';`

**Comment by blizzz** [comment]
@didierm please open a new bug report.
