### ISSUE TITLE
/files_trashbin/files is not created after oC install

### ISSUE THREAD

**Issue by mmattel** [owncloud/core#7919]
### Expected behaviour
```<user>/files_trashbin/files should be created when a user gets created.```
The error message appears as one of the first oC-log messages after the installing oC
(I have not tested it when a new user gets created from the admin)
Checked from the console if the directory(s) exist - they do not.

### Actual behaviour
Directory structure doesnt get created.
opendir(/mnt/www/owncloud-git/data/xxxxxxx/files_trashbin/files): failed to open dir: No such file or directory at /mnt/www/owncloud-git/lib/private/files/storage/local.php#66

### Server configuration
Ubuntu Ubuntu 12.04.4 LTS, 64 bit, latest patches

Apache 2.2.22, MySQL 5.5.35, PHP 5.3.10

ownCloud version:ownCloud 7.0 pre alpha (git), master 2014.03.27 (morning)

Updated from an older ownCloud or fresh install: complete fresh install with empty DB

List of activated apps:
Deleted files, External storage support, Music, ownCloud dependencies info, Pictures, Share Files, Versions

The content of config/config.php:
```
<?php
$CONFIG = array (
  'instanceid' => 'oc8fef95c86c',
  'passwordsalt' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'www.xxxxx.xxx',
  ),
  'datadirectory' => '/mnt/www/owncloud-git/data',
  'dbtype' => 'mysql',
  'version' => '6.90.0.2',
  'dbname' => 'owncloud-git',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => xxx,
  'installed' => true,

  'forcessl' => true,
  'apps_paths' =>
    array (
      0 =>
       array (
        'path' => OC::$SERVERROOT.'/apps',
        'url' => '/apps',
        'writable' => true,
       ),
      1 =>
       array (
        'path' => OC::$SERVERROOT.'/apps2',
        'url' => '/apps2',
        'writable' => false,
       )
      ),
);
```

**Are you using external storage, if yes which one:** local, see example screenshot below
Local ubuntu mounted smb shares
![image](https://cloud.githubusercontent.com/assets/3321281/2539662/47a49f1e-b5ca-11e3-821e-ff2dec89baaf.png)

**Are you using encryption:** no

### Client configuration
Browser: Opera 20 (Chrome engine)

Operating system: W7

#### ownCloud log (data/owncloud.log)
![image](https://cloud.githubusercontent.com/assets/3321281/2540470/c49deef4-b5d3-11e3-8c7e-844c31124759.png)

#### mount.json (formatted)
{"group":{"admin":{"\/$user\/files\/iTunes Media":{"class":"\\OC\\Files\\Storage\\Local","options":{"datadir":"\/mnt\/smb\/itunes_media"}},"\/$user\/files\/Martin":{"class":"\\OC\\Files\\Storage\\Local","options":{"datadir":"\/mnt\/smb\/martin"}},"\/$user\/files\/Video Mac":{"class":"\\OC\\Files\\Storage\\Local","options":{"datadir":"\/mnt\/smb\/video_mac"}},"\/$user\/files\/Video H.264":{"class":"\\OC\\Files\\Storage\\Local","options":{"datadir":"\/mnt\/smb\/tv_shows"}},"\/$user\/files\/Bilder":{"class":"\\OC\\Files\\Storage\\Local","options":{"datadir":"\/mnt\/smb\/bilder_public"}}}}}

**Comment by PVince81** [comment]
Thanks, closing.
