### ISSUE TITLE
Conflict dialog is confusing

### ISSUE THREAD

**Issue by purigarcia** [owncloud/core#7961]
When you try to upload a file with a name already in use, conflict dialog pops up. This popup is confusing, two options are shown but they are not clear enough for me.
Maybe "overwrite", "keep both" and "cancel" could be better?
![screen shot 2014-03-31 at 1 00 53 pm](https://cloud.githubusercontent.com/assets/4538201/2566429/fe80d098-b8c4-11e3-8371-49c8905a0ce4.png)

**Comment by PVince81** [comment]
Moving to backlog. Nice to have at some point to improve UX.

@pmaier1

**Comment by butonic** [comment]
something for phoenix @felixheidecke
