### ISSUE TITLE
Don't consider it a separate directory if a parent directory was already shared

### ISSUE THREAD

**Issue by osamak** [owncloud/core#7991]
I'm in a situation where I need to share a directory with a group of people (with a read-only privilege) and to give a few them the ability to modify specific subdirectories within it.  What happens now is that ownCloud considers each subdirectory a separate one in the Shared directory of the modifiers.  This results in a weird layout, especially if two subdirectories have the same name.

The proposed solution is not to list subdirectories as separate ones if their parents are already shared. 

To be considered in designing the sharing component: #4437

**Comment by PVince81** [comment]
@schiesbn @rullzer I thought we might have a duplicate for this already ?

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/4579
