### ISSUE TITLE
[Idea] Seamless integration with Openoffice/Libreoffice

### ISSUE THREAD

**Issue by proteansec** [owncloud/core#8000]
Hi,

I've been talking to some people on the owncloud IRC channel (PVince81 and frinring) and we've come to the conclusion that it would be a good idea to provide seamless integration of Owncloud with Openoffice/Libreoffice.

I mean that in much the same way as it's done with Sharepoint, where you can browse to the document you want and click on it after which Microsoft Word takes over and opens the file over webdav without downloading it. Therefore we don't need to download the file, edit it and reupload it every time we want to do some changes.

I'm assuming that we're not using Owncloud Client, which isn't suitable for this kind of thing: most of the edits are very simple and the idea of opening a .doc document directly from web browser in Openoffice is really good.

I'm starting this discussion to see what your point of views are and whether it would be better to write an Openoffice plugin instead.

**Comment by uzuzjmd** [comment]
CMIS would open the door to a lot of other systems like liferay, alfresco etc.. Also webdav is limited in terms of transmitting ACLs and remote queries. WebDav is nice but CMIS is a must in the longterm.

**Comment by butonic** [comment]
there is an apache library to interface with a CMIS server .... but we need to make a storage wrepper out of it: https://github.com/apache/chemistry-phpclient

**Comment by LukasReschke** [comment]
http://news.softpedia.com/news/introducing-the-libreoffice-online-app-for-owncloud-video-497154.shtml?utm_content=buffer6c9a2&utm_medium=social&utm_source=plus.google.com&utm_campaign=buffer#sgal_0
