### ISSUE TITLE
Not all autoconfig values that endup in config.php are respected by the gui

### ISSUE THREAD

**Issue by duritong** [owncloud/core#8022]
Setting up owncloud by using autoconfig.php is not respecting all values:

Having an autoconfig, like:

    <?php
    $AUTOCONFIG = array(
      "dbtype"        => "mysql",
      ....
      'forcessl'      => true,
    );

Will end up, with a proper config.php

    <?php
    $CONFIG = array (
      .....
      'dbtype' => 'mysql',
      'version' => '6.0.2.2',
      ....
      'installed' => true,
      'forcessl' => true,
    );

However, the forcessl option is not selected in the gui if I login as root afterwards. When selecting the option, it just adds it another time:

    <?php
    $CONFIG = array (
      .....
      'dbtype' => 'mysql',
      'version' => '6.0.2.2',
      ....
      'installed' => true,
      'forcessl' => true,
      'forcessl' => true,
    );

Then it remains selected.

**Comment by DeepDiver1975** [comment]
as explained above - I see no reason to keep this open

**Comment by duritong** [comment]
If all the config files in config holding a $CONFIG array are merged together, then yes, we can close that. => There is a possibility to configure additional settings without touching the central config file.

**Comment by LukasReschke** [comment]
> If all the config files in config holding a $CONFIG array are merged together, then yes, we can close that. => There is a possibility to configure additional settings without touching the central config file.

They do if the file is named correctly.
