### ISSUE TITLE
Thoughts on replacing filename slugify() with a bijection

### ISSUE THREAD

**Issue by bantu** [owncloud/core#8043]
E.g. UTF7 or a modified variant thereof, see http://en.wikipedia.org/wiki/UTF-7

Pros:
 * No strict database dependency. Reversible without the database.

Cons:
 * Possibly length extending and thus possibly reaching filesystem max filename limits (255 chars on NTFS)
 * Possibly bad readability of generated filenames

Refs #8040
http://en.wikipedia.org/wiki/Bijection
https://github.com/owncloud/core/blob/master/lib/private/files/mapper.php#L221

@DeepDiver1975

**Comment by PVince81** [comment]
AFAIK we got rid of slugify when dropping Windows Server support.
