### ISSUE TITLE
URL issues with IOS and Safari

### ISSUE THREAD

**Issue by codyxbell** [owncloud/core#8046]
I have been trying to get to the bottom of this issue since installing Owncloud. When visiting a shared link on IOS devices I get a play button with a line through it. I finally had the bright idea of visiting my links inside of IOS simulator and have determined the issue is with the way owncloud rewrites URLs. Here is a sample output:

Apr  4 00:09:50 C.local MobileSafari[21716] <Error>: <<<< FigPluginView >>>> -[FigPluginView validationFailedWithMessage:resultCode:]: unplayable URL (https://owncloudURL.com/public.php?service=files&t=da7573730a67e16937ec221efc28b9db&download) (error=0 -- Movie could not be played.)

Im sure I am not the only person having an issue with this, I have been searching for weeks and could not find a thread on this. Could someone point me to the right place to track this issue?

Thanks everyone.

**Comment by MorrisJobke** [comment]
@DeepDiver1975 @PVince81 This is again a similiar issue to our "we should use WebDAV everywhere" issue.

**Comment by MorrisJobke** [comment]
@PVince81 Wasn't there also an issue about the public URLs and adding the proper filename to it, because then the downloaded file is properly named (if it doesn't support the HTTP header containing the correct file name)

**Comment by PVince81** [comment]
Not that I remember.

**Comment by MorrisJobke** [comment]
@LukasReschke Do you know something abut this?

**Comment by LukasReschke** [comment]
Mobile browsers are pain – this is related to https://github.com/owncloud/core/issues/12931 once we tackle this this should be fixed.

**Comment by MorrisJobke** [comment]
Tested with Safari, Chrome and Chrome on Android -> this is fixed on master (9.0)
