### ISSUE TITLE
Versions app: Save more versions

### ISSUE THREAD

**Issue by Johan-Stockholm** [owncloud/core#8063]
I'd like to request the possibility to save more versions using the Versions App. It's a great feature to save a couple of versions. But saving more version would be even better :)

Perhaps have a configuration to specify the number of versions to save? Ideally having a "0" options to retain all versions?

**Comment by PVince81** [comment]
Since 8.2 there are new settings for the versions: https://github.com/owncloud/core/blob/v8.2.0/config/config.sample.php#L439
But that one is time based, not the number of versions.

**Comment by VicDeo** [comment]
well, to retain all the versions, just set retention obligation to disabled:
`'versions_retention_obligation' => 'disabled'`
