### ISSUE TITLE
Installer wizard fails in case a /templates directory exists in the root of the filesystem

### ISSUE THREAD

**Issue by rrjk** [owncloud/core#8071]
### Steps to reproduce
1. Ensure a /templates directory exists in the root of the file system
2. Install Owncloud
3. Go to the http://domain.ext/owncloud to start the installer

### Expected behaviour
Installer wizard should start

### Actual behaviour
A blank screen is shown

### Server configuration
Ubuntu 13.10

**Web server:**
Apache

**Database:**
None yet

**PHP version:**
5

**ownCloud version:** (see ownCloud admin page)
Installed 6.0.2

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**
None yet

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc161f5b47c6',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

### Client configuration
**Browser: Firefox

**Operating system: Kubuntu 13.10

#### Web server error log
[Sat Apr 05 23:32:47.392083 2014] [access_compat:error] [pid 31574] [client 192.168.2.12:58028] AH01797: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt

#### ownCloud log (data/owncloud.log)
{"app":"PHP","message":"Undefined variable: message at \/var\/www\/owncloud\/lib\/public\/util.php#95","level":3,"time":"2014-04-05T19:38:24+00:00"}
{"app":"index","message":"Exception: template file not found: template:layout.guest formfactor:","level":4,"time":"2014-04-05T19:38:24+00:00"}
{"app":"PHP","message":"template file not found: template:layout.guest formfactor: at \/var\/www\/owncloud\/lib\/private\/template\/templatefilelocator.php#43","level":3,"time":"2014-04-05T19:38:24+00:00"}
{"app":"PHP","message":"Undefined variable: message at \/var\/www\/owncloud\/lib\/public\/util.php#95","level":3,"time":"2014-04-05T19:38:25+00:00"}
{"app":"index","message":"Exception: template file not found: template:layout.guest formfactor:","level":4,"time":"2014-04-05T19:38:25+00:00"}
{"app":"PHP","message":"template file not found: template:layout.guest formfactor: at \/var\/www\/owncloud\/lib\/private\/template\/templatefilelocator.php#43","level":3,"time":"2014-04-05T19:38:25+00:00"}
{"app":"PHP","message":"Undefined variable: message at \/var\/www\/owncloud\/lib\/public\/util.php#95","level":3,"time":"2014-04-05T19:38:26+00:00"}
{"app":"index","message":"Exception: template file not found: template:layout.guest formfactor:","level":4,"time":"2014-04-05T19:38:26+00:00"}
{"app":"PHP","message":"template file not found: template:layout.guest formfactor: at \/var\/www\/owncloud\/lib\/private\/template\/templatefilelocator.php#43","level":3,"time":"2014-04-05T19:38:26+00:00"}
{"app":"PHP","message":"Undefined variable: message at \/var\/www\/owncloud\/lib\/public\/util.php#95","level":3,"time":"2014-04-05T19:38:26+00:00"}
{"app":"index","message":"Exception: template file not found: template:layout.guest formfactor:","level":4,"time":"2014-04-05T19:38:26+00:00"}
{"app":"PHP","message":"template file not found: template:layout.guest formfactor: at \/var\/www\/owncloud\/lib\/private\/template\/templatefilelocator.php#43","level":3,"time":"2014-04-05T19:38:26+00:00"}
{"app":"PHP","message":"Undefined variable: message at \/var\/www\/owncloud\/lib\/public\/util.php#95","level":3,"time":"2014-04-05T19:38:26+00:00"}
{"app":"index","message":"Exception: template file not found: template:layout.guest formfactor:","level":4,"time":"2014-04-05T19:38:26+00:00"}
{"app":"PHP","message":"template file not found: template:layout.guest formfactor: at \/var\/www\/owncloud\/lib\/private\/template\/templatefilelocator.php#43","level":3,"time":"2014-04-05T19:38:26+00:00"}
{"app":"PHP","message":"Undefined variable: message at \/var\/www\/owncloud\/lib\/public\/util.php#95","level":3,"time":"2014-04-05T19:40:09+00:00"}
{"app":"index","message":"Exception: template file not found: template:layout.guest formfactor:","level":4,"time":"2014-04-05T19:40:09+00:00"}

#### Browser log
n/a

### Own investigation into the problem, possibly showing the function where the bug is:
Installation of owncloud fails with a blank screen, in case a directory /templates exists in the root directory of the filesystem in which owncloud is installed.

Installed on ubuntu 13.10

When a clean owncloud install is first accessed, it first tries to load the template "installation". This works fine.

After that, it tries to load the template "layout.guest", which fails in "var/www/owncloud/lib/private/template.php(171): OC\Template\TemplateFileLocator->find('layout.guest')"

As part of the above function, amongst others 
"protected function findTemplate($theme, $app, $name, $fext) {"
is called.

For the second template, the $app is equal to "core"
which means "$dirs = $this->getAppTemplateDirs($theme, $app, OC::$SERVERROOT, OC_App::getAppPath($app));" gets executed.

This function is as follows:

        protected function getAppTemplateDirs($theme, $app, $serverroot,$app_dir) {
                // Check if the app is in the app folder or in the root
                if( file_exists($app_dir.'/templates/' )) {
                        return array(
                                $serverroot.'/themes/'.$theme.'/apps/'.$app.'/templates/',
                                $app_dir.'/templates/',
                        );
                }
                return array(
                        $serverroot.'/themes/'.$theme.'/'.$app.'/templates/',
                        $serverroot.'/'.$app.'/templates/',
                );
        }

For some reason, the app directory for "core"is empty.
That means that the if statement file_exists($app_dir.'/templates/' )) checks whether a templates directory exists in the root of the filesystem. If it exists, exactly that directory is returned as the AppTemplateDirs (and another directory). Obviously in the /templates directory in the root no owncloud templates can be found, resulting in owncloud presenting a blank screen, with no clue of the problem at hand.

Removing the /templates directory in the root shows the installer.

**Comment by bluedinoco** [comment]
@Remus110 I just had similar problem. In my cass was in root a directory with the name templates (/templates) $app_dir was empty and  file_exists($app_dir.'/templates/' ) was true.
I just add  && $app_dir != '' to the if statement from rrjk an its working for me.

The function in lib/private/template/base.php looks the as follows:
```
protected function getAppTemplateDirs($theme, $app, $serverroot, $app_dir) {
		// Check if the app is in the app folder or in the root
		if( file_exists($app_dir.'/templates/' ) && $app_dir != '') {
			return array(
				$serverroot.'/themes/'.$theme.'/apps/'.$app.'/templates/',
				$app_dir.'/templates/',
			);
		}
		return array(
			$serverroot.'/themes/'.$theme.'/'.$app.'/templates/',
			$serverroot.'/'.$app.'/templates/',
		);
	}
```

**Comment by DeepDiver1975** [comment]
> corner case

closing therefore
