### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry XXX for key 'id_user_index'

### ISSUE THREAD

**Issue by moscicki** [owncloud/core#8096]
Server: 5.0.14a EE

While syncing I am getting Internal Server Error which I tracked down to:

 SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '530433-_test_debug' for key 'id_user_index'

I am getting this for MKCOL, PROPFIND, PUT. The user name is: _test_debug.

Here is the log of the backend server:

<pre>
[Mon Apr 07 15:38:42 2014] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_out (data-HEAP): <?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>PDOException</s:exception>\n  <s:message>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '530433-_test_debug' for key 'id_user_index'</s:message>\n  <s:sabredav-version>1.7.6</s:sabredav-version>\n</d:error>\n
[Mon Apr 07 15:40:02 2014] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_out (data-HEAP): <?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>PDOException</s:exception>\n  <s:message>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '531182-_test_debug' for key 'id_user_index'</s:message>\n  <s:sabredav-version>1.7.6</s:sabredav-version>\n</d:error>\n
[Mon Apr 07 15:40:40 2014] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_out (data-HEAP): <?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>PDOException</s:exception>\n  <s:message>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '531271-_test_debug' for key 'id_user_index'</s:message>\n  <s:sabredav-version>1.7.6</s:sabredav-version>\n</d:error>\n
[Mon Apr 07 15:40:44 2014] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_out (data-HEAP): <?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>PDOException</s:exception>\n  <s:message>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '529617-_test_debug' for key 'id_user_index'</s:message>\n  <s:sabredav-version>1.7.6</s:sabredav-version>\n</d:error>\n
[Mon Apr 07 15:41:29 2014] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_out (data-HEAP): <?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>PDOException</s:exception>\n  <s:message>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '531167-_test_debug' for key 'id_user_index'</s:message>\n  <s:sabredav-version>1.7.6</s:sabredav-version>\n</d:error>\n
[Mon Apr 07 15:41:30 2014] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_out (data-HEAP): <?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>PDOException</s:exception>\n  <s:message>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '531135-_test_debug' for key 'id_user_index'</s:message>\n  <s:sabredav-version>1.7.6</s:sabredav-version>\n</d:error>\n
[Mon Apr 07 15:44:37 2014] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_out (data-HEAP): <?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>PDOException</s:exception>\n  <s:message>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '531631-_test_debug' for key 'id_user_index'</s:message>\n  <s:sabredav-version>1.7.6</s:sabredav-version>\n</d:error>\n
[Mon Apr 07 15:44:40 2014] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_out (data-HEAP): <?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>PDOException</s:exception>\n  <s:message>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '529617-_test_debug' for key 'id_user_index'</s:message>\n  <s:sabredav-version>1.7.6</s:sabredav-version>\n</d:error>\n
[Mon Apr 07 15:44:55 2014] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_out (data-HEAP): <?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>PDOException</s:exception>\n  <s:message>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '531622-_test_debug' for key 'id_user_index'</s:message>\n  <s:sabredav-version>1.7.6</s:sabredav-version>\n</d:error>\n
[Mon Apr 07 15:45:34 2014] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_out (data-HEAP): <?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>PDOException</s:exception>\n  <s:message>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '531606-_test_debug' for key 'id_user_index'</s:message>\n  <s:sabredav-version>1.7.6</s:sabredav-version>\n</d:error>\n
[Mon Apr 07 15:46:02 2014] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_out (data-HEAP): <?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>PDOException</s:exception>\n  <s:message>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '531622-_test_debug' for key 'id_user_index'</s:message>\n  <s:sabredav-version>1.7.6</s:sabredav-version>\n</d:error>\n
[Mon Apr 07 15:46:51 2014] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_out (data-HEAP): <?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>PDOException</s:exception>\n  <s:message>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '531606-_test_debug' for key 'id_user_index'</s:message>\n  <s:sabredav-version>1.7.6</s:sabredav-version>\n</d:error>\n
[Mon Apr 07 15:49:08 2014] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_out (data-HEAP): <?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>PDOException</s:exception>\n  <s:message>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '531605-_test_debug' for key 'id_user_index'</s:message>\n  <s:sabredav-version>1.7.6</s:sabredav-version>\n</d:error>\n
[Mon Apr 07 15:49:08 2014] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_out (data-HEAP): <?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>PDOException</s:exception>\n  <s:message>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '532392-_test_debug' for key 'id_user_index'</s:message>\n  <s:sabredav-version>1.7.6</s:sabredav-version>\n</d:error>\n
[Mon Apr 07 15:49:39 2014] [debug] mod_dumpio.c(74): mod_dumpio:  dumpio_out (data-HEAP): <?xml version="1.0" encoding="utf-8"?>\n<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">\n  <s:exception>PDOException</s:exception>\n  <s:message>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '531605-_test_debug' for key 'id_user_index'</s:message>\n  <s:sabredav-version>1.7.6</s:sabredav-version>\n</d:error>\n
</pre>

**Comment by DeepDiver1975** [comment]
this will be fixed with 8.1 - backport to 8.0.3 pending - closing therefore - THX
