### ISSUE TITLE
Deleted Files: Hidden folder not visible

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#8101]
Today I had a sync conflict with a different WebDAV app which caused some files to be lost. I initially did not find them in the Deleted Files because they were inside a folder called ```.d1396879045```. The row was visible and the icon too, but there was just no name. It was the whole root folder, so maybe it should have been »home.d1396879045«?

Probably related to it being a hidden folder? @schiesbn any ides? The »nametext« span was completely empty. When I navigate into the folder however, the breadcrumb shows the correct name with dot preceding.

**Comment by DeepDiver1975** [comment]
close due to inactivity

**Comment by PVince81** [comment]
Looks like this bug is back https://github.com/owncloud/core/issues/22824
