### ISSUE TITLE
[FR] Free trash bin using cron

### ISSUE THREAD

**Issue by dietmaroc** [owncloud/core#8109]
### Steps to reproduce
1. call oc-cron.php via system cron
2. files in trashbin, that exceed thrascan_retention_obligation from config.php won't be deleted

### Expected behaviour
calling oc-cron.php via system cron should delete files in trashbin, that exceed thrascan_retention_obligation from config.php.

### Actual behaviour
calling oc-cron.php via system cron doesn't delete files in trashbin, that exceed thrascan_retention_obligation from config.php.

### Server configuration
**ownCloud version:**
6.0.2

**Comment by DeepDiver1975** [comment]
@icewind1991 something for the job queue - as discussed - THX

**Comment by DeepDiver1975** [comment]
fixed with https://github.com/owncloud/core/pull/14644
