### ISSUE TITLE
Blank Page in Files Area of a Specific User

### ISSUE THREAD

**Issue by lucianop** [owncloud/core#8116]
### Steps to reproduce
1. Syncing files normally, with Linux sync client
2. Client gets abruptly turned off (power outage)

### Expected behaviour
When system gets back, ownCloud website continues to work normally.

### Actual behaviour
Although the sync client continues to work fine, I can't get to the files area of the website for the user (blank page after a long wait). Other users (or other pages for the same user) continue to work normally. 

After a while, I also tried running ``php console.php files:scan <user_id>`` on the server, but it hangs at some point for a long while, and then the process is Killed. The same command works ok for other users.

### Server configuration
**Operating system**:
Debian 7.4

**Web server:**
Nginx 1.2.1

**Database:**
MySQL 5.5.35

**PHP version:**
5.4.4-14+deb7u8

**ownCloud version:** (see ownCloud admin page)
6.02

**Updated from an older ownCloud or fresh install:**
6.01

**List of activated apps:**
Just the default ones

**The content of config/config.php:**

```
  'instanceid' => 'oc02e5e8ec9f',
  'passwordsalt' => <HIDDEN>
  'datadirectory' => '/usr/share/nginx/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '6.0.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud_user',
  'dbpassword' => <HIDDEN>
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Tried on many browsers and operating systems, this is clearly a server issue.

#### Web server error log
```
2014/04/08 14:33:16 [error] 1072#0: *2515 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in /usr/share/nginx/www/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php on line 231" while reading response header from upstream, client: 192.168.1.101, server: <HIDDEN>, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "<HIDDEN>"
```

#### ownCloud log (data/owncloud.log)
```
{"app":"PHP","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) at \/usr\/share\/nginx\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php#231","level":3,"time":"2014-04-08T17:33:16+00:00"}
```

**Comment by DeepDiver1975** [comment]
basically this can happen everywhere - we shall abandon any use of fetchAll() -> new tech dept issue please
