### ISSUE TITLE
Slowness in the basic operations ( storage swift )

### ISSUE THREAD

**Issue by leonardofln** [owncloud/core#8142]
**Steps:**
- Assuming that the storage swift is configured
- Click the "Files " icon
- And then in the swift folder
- And run one of the basic operations (rename, download, upload, create, or delete a file/folder)

**Expected result:**
- A fast response time of the application

**Current results:**
- Slowness in response time of the basic operations

**Versions:**
- ownCloud 6.0.1
- PHP 5.4.4
- MySQL 5.0.10
- Apache 2.4.2
- Windows 7 32bit

**Notes:**
- The number of requests cURLs for each basic operation is very high
 - Rename a file / folder ( 22 requests cURL )
 - Download a file / folder ( 5 requests cURL )
 - Upload a file / folder ( 24 requests cURL )
 - Create a file / folder ( 21 requests cURL )
 - Delete a file / folder ( 14 requests cURL )
- Some basic operations are no feedback to the user, eg after uploading a file when the upload finishes, you still have time to send the swift storage, and this last step has no feedback to the user ( eg charging icon )

**Comment by enoch85** [comment]
Closing this in favor for #7882 Please continue the discussion there.
