### ISSUE TITLE
Unable to decrypt files

### ISSUE THREAD

**Issue by claneys** [owncloud/core#8149]
### Steps to reproduce
1. Having files crypted
2. Disable Encryption
3. Decrypt File

### Expected behaviour
Decrypt all files

### Actual behaviour
Almost all files are still crypted and unrecoverable. I can see my private key under data/owncloud_private_key directory.

### Server configuration
**Operating system**:
Fedora 20
**Web server:**
apache 2.4.9
**Database:**
sqlite

**PHP version:**
5.5.10

**ownCloud version:** (see ownCloud admin page)
6.0.2

**Updated from an older ownCloud or fresh install:**

**List of activated apps:**
 Activity
Bookmarks
Calendar
Full Text Search
LDAP user and group backend
PDF Viewer
Pictures
Share Files
Tasks
Text Editor
Updater

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'passwordsalt' => '......',
  'datadirectory' => '/var/www/html/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '6.0.2.2',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => '2',
  'instanceid' => '50bdf7e34b61b',
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'theme' => '',
  'maintenance' => false,
  'forcessl' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Trying to disable it....

### Client configuration
**Browser:**
Firefox 28.0

**Operating system:**
Windows 7 Pro

#### Web server error log
```
[Thu Apr 10 15:08:11.252524 2014] [access_compat:error] [pid 1350] [client 192.168.1.20:47234] AH01797: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Thu Apr 10 15:44:50.836690 2014] [access_compat:error] [pid 2259] [client 192.168.1.20:47662] AH01797: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
[Thu Apr 10 15:57:26.960490 2014] [access_compat:error] [pid 2482] [client 192.168.1.20:47890] AH01797: client denied by server configuration: /var/www/html/owncloud/data/htaccesstest.txt
```
#### data/.htaccess Content
```
deny from all
#Allow from 192.168.1., 127.0.0.1
#Allow from all
IndexIgnore *
```
#### ownCloud log (data/owncloud.log)
```
[...]
{"app":"encryption library","message":"No keys available to decrypt the file: claneys\/files\/Docs Romain\/Scolaires\/note bts ..jpg","level":3,"time":"2014-04-10T13:54:10+00:00"}
{"app":"encryption library","message":"No keys available to decrypt the file: claneys\/files\/Docs Romain\/Scolaires\/Dipl\u00f4me BTS.pdf","level":3,"time":"2014-04-10T13:54:10+00:00"}
{"app":"encryption library","message":"No keys available to decrypt the file: claneys\/files\/Docs Romain\/Scolaires\/Dipl\u00f4me Bac Techno.pdf","level":3,"time":"2014-04-10T13:54:10+00:00"}
{"app":"encryption library","message":"No keys available to decrypt the file: claneys\/files\/Docs Romain\/Sydel.pfx","level":3,"time":"2014-04-10T13:54:10+00:00"}
{"app":"encryption library","message":"No keys available to decrypt the file: claneys\/files\/Docs Romain\/Pro\/IDPE\/dossier remplissabe ecran.pdf","level":3,"time":"2014-04-10T13:54:10+00:00"}
{"app":"encryption library","message":"No keys available to decrypt the file: claneys\/files\/Docs Romain\/Pro\/Travail\/Sydel\/Salaires\/Salaire_2013-12.pdf","level":3,"time":"2014-04-10T13:54:10+00:00"}
{"app":"encryption library","message":"No keys available to decrypt the file: claneys\/files\/Documentations\/2013_09_24\/Je d\u00e9couvre le yoga.jpg","level":3,"time":"2014-04-10T13:54:11+00:00"}
{"app":"encryption library","message":"No keys available to decrypt the file: claneys\/files\/Documentations\/The-Hackers-Underground-Handbook.pdf","level":3,"time":"2014-04-10T13:54:11+00:00"}
{"app":"encryption library","message":"No keys available to decrypt the file: claneys\/files\/Documentations\/Elektor.Electronics.33-366.-.Jun.2007.-.OBD-2.DIY.Project.pdf","level":3,"time":"2014-04-10T13:54:11+00:00"}
{"app":"encryption library","message":"No keys available to decrypt the file: claneys\/files\/Documentations\/AN143XINST.PDF","level":3,"time":"2014-04-10T13:54:11+00:00"}
```

#### Browser log
```
Content Security Policy: Les paramètres de la page ont empêché le chargement d'une ressource : Une tentative d'exécution de scripts embarqués a été bloquée
https://owncloud.claneys.com/index.php/settings/personal
Line 0
```

**Comment by PVince81** [comment]
There was a nasty but in OC 7.0.2 and older OC 6 versions where files could be moved and they would carry the wrong keys with them. It is mostly file names with similar name patterns like "test.txt" and "test_123.txt". Moving "test.txt" to another folder would also take the keys from "test_123.txt".

To find out whether it is that case you might be able to find the lost keys in the wrong folders.
For example if you have a file "broken.txt" that you cannot decrypt, try searching for key files in any other folder.

**Comment by etiess** [comment]
Thank you @PVince81 
Unfortunately, I already made a fresh install, resynced everything and I don't use encryption anymore.
So I'm not able to investigate :(

**Comment by PVince81** [comment]
That's fine.

@claneys how about you ?

**Comment by tflidd** [comment]
Is there any solution to this? I try to decrypt about 15 GB of files, # files=2652. In the beginning there were some files where the keyfile couldn't be found, I manually deleted all these files. I rescanned the folder for this user and restarted the decryption process. Apache process starts with some load, then it throws this error:
````
{"reqId":"54fd514e08e8b","app":"PHP","message":"Call to a member function getPath() on a non-object at \/var\/www\/owncloud\/lib\/private\/share\/share.php#112","level":3,"time":"March 09, 2015 07:52:46","method":"POST","url":"\/owncloud\/index.php\/settings\/ajax\/decryptall.php"}
````
Then CPU usage drops, I can't tell if files get decrypted. But the number of encrypted files in the database doesn't change:
````
SELECT count( * )
FROM `filecache`
WHERE `encrypted` =1
AND `storage` =3
````
PHP has 1 GB of memory (execution time 1 day), CPU: Intel Core i7. I decrypted a newer user with only about 1 GB of files which took more than 30 minutes.

What can I do?

And nearly every user has some keyfiles missing. I couldn't find them elsewhere on the filesystem.

**Comment by PVince81** [comment]
If the keyfiles are missing and not found in any other folder (in case it was the bug that moved the wrong keys), there is nothing that can be done to decrypt the broken files.

Are you saying the decryption process stops at every broken file ? The code where it fails seems to be the one where it tries to find which users have access to a given file through sharing, but for some reason the file info is missing. https://github.com/owncloud/core/blob/v8.0.0/lib/private/share/share.php#L113

You could try adding `if (!$meta) { return array(); }` after the `getFileInfo` line and see whether it continues.

**Comment by tflidd** [comment]
The keys without logfiles left a report in the logfile but the apache process (via top) continued for hours. At some point, the apache process stopped, the wheel for decryption kept spinning. I thought maybe it confuses the decryption, so I deleted these files and rescanned the user-folder.

Now, I introduced the line you proposed. Decryption starts, there are plenty of log-messages (of all files decrypted) and the decryption process runs smoothly. It took 15 minutes! I am still on OC 7.0.4.

**Comment by PVince81** [comment]
Decryption should probably be moved to a background job at some point @schiesbn @icewind1991 

I'll prepare a PR with the fix from https://github.com/owncloud/core/issues/8149#issuecomment-77821822 though

**Comment by PVince81** [comment]
Hmmm, very strange. I tried 7.0.4 and manually deleted file key or share keys, then decrypt the files either as sharer or recipient, but I could never get the warning from https://github.com/owncloud/core/issues/8149#issuecomment-77812850

**Comment by tflidd** [comment]
I tried to figure out how it had happened but some of the files were uploaded 6 or 12 months ago. I can't really tell you if the files have been modified at some time on a client or not. Only thing, some followed the old encryption scheme without any headers in the encrypted file. And it were only some file in a folder, never all of them (even if uploaded at the same time). I still have a backup of OC before decrypting everything, so if you want me to test something...

**Comment by tflidd** [comment]
One hint: in a buggy directory, I have a lot of PDF and PPT from a workshop (quite big files). Although I never changed or copied the files, I have a lot of conflict files. Often I have the key of the conflict files but not from the original ones. This goes back at least to OC 5 (when OC created a clientsync directory).

**Comment by MorrisJobke** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/9.0/developer_manual/). :)

Thank you!
