### ISSUE TITLE
Timeout using webdav on IIS 8.0

### ISSUE THREAD

**Issue by dib0** [owncloud/core#8173]
### Steps to reproduce
A timout occurs everytime a HTTP post/put is send with data (so POST, PUT, PROPFIND, LOCK, etc.). I traced the timout to the following statement:
$this->body = fopen('php://input','r');
In the Request.php of Sabre (/owncloud/3rdparty/Sabre/HTTP). If I solve this by using $this->body = $HTTP_RAW_POST_DATA; most actions do succeed, but uploading a file stills failes. A timeout occurs later on when OwnCloud (Sabre Owncloud connectors) is trying to check the filesystem (if the file exists).

### Expected behaviour
The timeout shouldn't occur.

### Actual behaviour
I get a timeout whenever I send a HTTP request containing data from the app, the windows client software or a webdav client.

### Server configuration
**Operating system**:
Windows server 2012

**Web server:**
IIS 8.0

**Database:**
MySQL 6.0

**PHP version:**
PHP 5.4.xx

**ownCloud version:** (see ownCloud admin page)
6.2

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**
Activity
Calendar
Contacts
Deleted files
Documents
First Run Wizard
Full Text Search
PDF viewer
Pictures
Share Files
Text editor
Updater
Versions
Video Viewer
Mozilla sync

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oce*********',
  'passwordsalt' => '**************************',
  'trusted_domains' => 
  array (
    0 => 'www.mydomein.com',
  ),
  'datadirectory' => 'D:\\www\\mydomein.com\\www\\owncloud\\data',
  'dbtype' => 'mysql',
  'version' => '6.0.2.2',
  'dbname' => 'myusername',
  'dbhost' => 'mysql.mydomain.com',
  'dbtableprefix' => 'oc_',
  'dbuser' => '******',
  'dbpassword' => '*************',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => '3',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:**
No

### Client configuration
**Browser:**
Diverse, Firefox 28 and 29, sync client and webdav clients (also Windows Explorer as a webdav client)

**Operating system:**
Diverse. Linux Mandriva, Windows 7

#### Web server error log
I'm using a shared webhosting provider. I cannot get to the webserver logs.

#### ownCloud log (data/owncloud.log)
I can post the ownCloud log, but when the timeout occurs it doesn't log anything (not before, not after). Even when I set the log level to debug.

#### Browser log
Not relevant. Problem does not occur in the browser.

**Comment by LukasReschke** [comment]
Still reproducible?

**Comment by DeepDiver1975** [comment]
no feedback -> close
