### ISSUE TITLE
LDAP only supports group checks when you have a memberof overlay active

### ISSUE THREAD

**Issue by cpo** [owncloud/core#8175]
We are planning to do a pilot with owncloud for use in a medium-sized organisation.

This organisation has a combination of openldap which uses the "glue" overlay to incorporate the Active Directory LDAP from within the openldap tree. We cannot have the memberof layer active, as we do not have write access to the AD part.

LDAP integration works, but we cannot restrict login to everyone in a certain group. This is typically done in the second "User filter" tab but the group selection list is grayed out as our LDAP does not support the "memberof" attribute on users.

Normally, when an application we build autenticates, we do a separate lookup in the groups we are interested in to see if the user DN is mentioned as "member" of the group to determine the roles of the user, instead of inspecting the "member" attributes of a user object.

It would be very very nice to have this option instead of depending on a "memberof" layer being active!

**Comment by Xenopathic** [comment]
Please retry with oC 8.1.1

**Comment by blizzz** [comment]
There are no changes, group memberships in the user and login filter still require memberOf. Please reopen if the feature is still desired.

**Comment by Eifoen** [comment]
Has anything about this changed by now? This basically makes the ldap integration a showstopper when using ApacheDS (which does not support memberof overlay).

funfact: The LDAP groups integration works without the overlay because it searches the other way around using the member attribute of the group.
