### ISSUE TITLE
Share Dialog: duplicate displaynames cannot be distinguished

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/core#8194]
Assuming two different users have the same full name/display name
e.g. Thomas Müller :wink: - the most common name in Germany
there is no way to distinguish them in the share drop down.

Possible solution:
Adding the user id or email address in brackets - maybe user backend specific

Example:
Thomas Müller (thomas@müller.net)

@jancborchardt @blizzz @karlitschek

**Comment by alekiy** [comment]
We are facing the same problem. The UID in brackets after the display name would be nice. :+1:

**Comment by blizzz** [comment]
There's another problem. If there are severl Thomas Müllersens and they are differentiated  in the share dialogue, that's fine. But names are also shown when they share files with you. In that case you need the detail as well, and/or the avatar, but at that point of time we do not know about name collisions.

**Comment by jancborchardt** [comment]
So – can we show the avatars next to the name? Both in the share dialog and in the autocomplete dropdown would be good.

**Comment by PVince81** [comment]
Avatars are already displayed now in 8.1.1
But if the users have no avatar, then you'd see both "Thomas Müller" with a "T" avatar, wouldn't help much.

**Comment by jancborchardt** [comment]
Closing this in favor of the newer issue https://github.com/owncloud/core/issues/20291
