### ISSUE TITLE
Automatic User Defined "Virtual Groups"

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#8201]
Thinking about usability, and considering a feature called “user defined groups”. The concept of user defined groups is based on users wanting to share their files, and having the annoyance of constantly having to add the same users to the share dialog over and over again every time a file or folder is shared with these people. Think of being able to create a "local" group, which is not a full group in the ownCloud sense, but more of a shortcut to a list of user names within the sharing interface so that people can share quickly with their coworkers as needed.

What if we looked at folder shares and something like a virtual groups. Say I have a folder called "User mgmt designs" shared with user 1, user 2, user 3 and user4. I could type either one of the names and the second entry would be "User mgmt designs (user 1, user 2, user 3 and user4)" or I could directly type "user mgmt .." and that group would be suggested.

Thoughts?
@jancborchardt @karlitschek @blizzz

**Comment by atroxix** [comment]
To me it seems that full group management function would still be best. Ideally those user-defined groups could also be shared.

Whether it should be part of Core functionality is another matter - maybe more proper way would implement it in Contacts app and sharing capability could be just extended to groups in Contacts app (individual contacts with Federated ID are already supported).

**Comment by PVince81** [comment]
Not exactly automatic, but in this other ticket I had the feeling that there is a need for an admin role to administrate group memberships instead of administrating users, see https://github.com/owncloud/core/issues/3362#issuecomment-220918674

**Comment by PVince81** [comment]
User-defined groups could be address books on the technical level, in which people can be added and also remove themselves when they want to leave.

Then extend oc_share to have "share with contact" and "share with address book".
A lot of code would then have to do the lookup through this.

**Comment by pmaier1** [comment]
Has been implemented as Custom Groups app https://marketplace.owncloud.com/apps/customgroups.
All further FRs in the repo, please https://github.com/owncloud/customgroups. Closing here.
