### ISSUE TITLE
search username with multiple name parts

### ISSUE THREAD

**Issue by felixboehm** [owncloud/core#8208]
Search in the sharing dialog searches for all entries beginning with the search string. Since the entry in complete name can look like „firstname lastname“ a search for lastname would fail which results in the necessity to know pretty precisely what the guy’s name or email address is you want to share with. 
 
It could be improved (not completely resolved, though) if the search went for all entries containing (!) the search string instead of just beginning with it (*x* instead of x*)

**Comment by DeepDiver1975** [comment]
@felixboehm from my understanding this is fixed - tested with 8.1 - searching for the lastname is possibe - please reopen if still existing
