### ISSUE TITLE
Enhancement: Add possibility to do a full backup of Owncloud (Data & Database) in admin panel

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#8219]
Hi!

Just noticed that you have taken away the possibility to do a full backup of your Owncloud instance in the admin panel. Why?

I need to format and re-install my server, but I don´t want to loose all my data or user data. Especially as I have 30+ users with stored own accounts and such. So a full backup option would be preferable. 

Could this be planned for Owncloud 7, or could it be a feature to implement?

I have read the documentation about backing up your Owncloud here: http://doc.owncloud.org/server/6.0/admin_manual/maintenance/backup.html but for me that isn´t that good in Linux (yet) it would be much better to have an option in the admin panel instead. It would also be preferable to choose where to save the backup, if you want to save it on another HDD for instance. And I also think that this feature would be appreciated by other users with the same (low) knowledge as me.

What do you think?

**Comment by Xenopathic** [comment]
https://github.com/pbek/ownbackup
