### ISSUE TITLE
[master] Some methods still treat view::getFileInfo result as an array

### ISSUE THREAD

**Issue by VicDeo** [owncloud/core#8224]
view::getFileInfo was changed recently to return a File object
https://github.com/owncloud/core/blob/master/lib/private/files/view.php#L826

Some core classes still try to address this object data in old fashioned manner  e.g.
https://github.com/owncloud/core/blob/master/lib/private/files/node/node.php#L120

**Comment by Xenopathic** [comment]
As this isn't a significant enhancement, or even really a technical debt, I'm closing this. Correct me if this is important to track

**Comment by VicDeo** [comment]
np, will reopen as soon as new bugs are risen against the apps I maintain. ;)

**Comment by VicDeo** [comment]
It is fixed for OC\Files\Node\Node in stable8/master btw
