### ISSUE TITLE
web interface confusion about max upload size

### ISSUE THREAD

**Issue by Supermathie** [owncloud/core#8225]
Prior to changes, post_max_size and upload_max_filesize weren't set anywhere.

The web interface reported a maximum file upload size of 2M (for both version 6.0.2 and today's version (7.0 pre alpha (daily) Build:2014-04-15T03:09:51+00:00)

I've set a max upload size in my php_fpm configuration as follows:

```
php_value[post_max_size] = 1G
php_value[upload_max_filesize] = 800M
```

But the web interface didn't seem to notice those limits - it now reports:

* 6.0.2: max file upload size of 8.6GB (which is the amount of quota I have left)
* daily: max file upload size of 10GB (unlimited quota here, shows 376GB free)

If I try and upload a file larger than upload_max_filesize I get the expected error from PHP:

```
[15-Apr-2014 21:28:46 UTC] PHP Warning:  POST Content-Length of 711983534 bytes exceeds the limit of 536870912 bytes in Unknown on line 0
```

(this was when I had 512MB set as the max upload size)

**Comment by PVince81** [comment]
@Supermathie are you still seeing this with 7.0.5 or 8.0.2 ?

If yes, maybe OC has trouble reading the value from the php_fpm settings somehow (I believe this is exposed with some PHP API)

**Comment by Supermathie** [comment]
We're still on 6.0.2 - we've decided that our Owncloud deployment failed and we're end-of-lifing it.

**Comment by MorrisJobke** [comment]
This will be fixed with the chunked upload in the WebUI https://github.com/owncloud/core/issues/20047

The client doesn't have any upload limitations because it already uses chunked upload.
