### ISSUE TITLE
Do not show the original sharer or already shared to people in the sharing suggestions

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#8231]
People who the file is already shared with should not show up in the suggestions of the sharing input field. That includes:
* [ ] the original sharer if you received the share and want to reshare
* [x] anyone already in the list (PR #15182)

@schiesbn

**Comment by rullzer** [comment]
WIP PR in #15182 that should solve the second bullet.

**Comment by jancborchardt** [comment]
Cool stuff, will look at it after lunch! :)

**Comment by jancborchardt** [comment]
@rullzer any love for the first issue as well? ;)

**Comment by rullzer** [comment]
@jancborchardt not plannend currently. Since the code where the php results is not unit testable. Probably would be best to tackle this once the we get the new sharing modal. Since a lot of corner cases have to be covered.

A quick fix might be to make sure the javascript filters out the user. Let me see what I can do there.

**Comment by rullzer** [comment]
Moved to 9.0 since implementing this (correctly) in the current sharing code is a huge pain. But we will tackle this in the sharing 2.0 (#13014)

**Comment by MorrisJobke** [comment]
@rullzer This is done on the client side to have a stateless shares endpoint, right? Can this then be closed?

**Comment by rullzer** [comment]
@MorrisJobke well yes... but out webui is also a client... I'm not sure all is fixed there currently...

**Comment by MorrisJobke** [comment]
> @MorrisJobke well yes... but out webui is also a client... I'm not sure all is fixed there currently...

The web UI properly hides people that this file is already shared to and the owner. So this is fine from my point of view.

**Comment by rullzer** [comment]
Okidoki... then I guess it is OK to close :)
