### ISSUE TITLE
Share API: Allow renaming item_target

### ISSUE THREAD

**Issue by tanghus** [owncloud/core#8256]
For files it will be possible to for "sharees" to rename the share using the `files_target` column. It would be nice to have this feature for other share types, such as calendars and address books.

Related comments:
https://github.com/owncloud/core/pull/8026#issuecomment-40720738
https://github.com/owncloud/core/pull/8026#issuecomment-40722020

@schiesbn @georgehrke

**Comment by rullzer** [comment]
We are moving calendar and contats into core. And at the same time out of the oc_share table. So I'm closing this.
