### ISSUE TITLE
manage LDAP passwords and group association

### ISSUE THREAD

**Issue by anarcat** [owncloud/core#8257]
it would be nice if the LDAP plugin would manage LDAP passwords and generally be able to manipulate the LDAP directory.

OC wouldn't need any special access for this, and could simply relegate the access control to the LDAP server, prompting for the user password for any change (without storing it in the session, which is already a problem it seems, see #7199).

i was under the impression that not writing to LDAP was a deliberate design decision (source: https://forum.owncloud.org/viewtopic.php?f=3&t=4064), but I think it could be reconsidered if it's done properly.

a basic thing would be to allow users to change their passwords. an improvement would be to allow users to change group memberships. then this could be extended to edit quotas and so on.

**Comment by blizzz** [comment]
A third party could do this in future when #23992 gets ready and merged.
