### ISSUE TITLE
owncloud users page ldap shows only first 120 users from LDAP

### ISSUE THREAD

**Issue by liska12** [owncloud/core#8258]
Hi, 
I have found that my OC installation shows only first 120 users from ldap based on their UID. On admin page in LDAP settings it shows correctly all 169 users and this value is changing depending on ldap db. When I had deleted a user with lower id from my openldap directory then next user with higher uid appeared on users page of admin interface. I installed another new instances of OC (5.0.14 and 6.0.2) and they were working as expected. I have found some wrong settings on ldap expert tab concerning uuid override and change them from auto to uid - I do not remember if I set this manually. Also I typed uid to internal username, it was blank before.
Since that all users can login to OC but still only old users appeared on my users page. Only "old" users could login before this change.

This installation is upddated regularly since some 4.x version now to latest 6.0.2. 
OS: Debian Wheezy with all updates applied  
Webserver: Apache 2.2
PHP: 5.4
Database: Mysql 5.5

In logs I can only find this error messages related to this problem
ldap_search(): Partial search results returned: Sizelimit exceeded at /var/www/owncloud/apps/user_ldap/lib/ldap.php#141

**Comment by dpackman** [comment]
We are running owncloud 7.0.4. I see all of our 342 contacts. Another user consistently only sees 200. I have tested on linux and macos. He is on a windows machine.

**Comment by blizzz** [comment]
Does https://github.com/owncloud/core/pull/14707 fixes it for you?

**Comment by dpackman** [comment]
> On Mar 24, 2015, at 5:13 AM, blizzz <notifications@github.com> wrote:
> 
> Does #14707 <https://github.com/owncloud/core/pull/14707> fixes it for you?
> 
Interesting.
I am in the process of trying to update to version 8 so can’t test this.

I am running an “occ upgrade” command which seems to be hanging.
Is there any log output somewhere I can see that would indicate progress
or a problem?

I did a “mysqlcheck” and an “occ maintenance:repair"
 both with no errors.

Dan

**Comment by blizzz** [comment]
Well the log is always at data/owncloud.log, but please discuss this on the IRC, Forums or User Mailing list. Let's leave this bug report for the bug :)

**Comment by blizzz** [comment]
Closed for inactivity, and possibly fixed. Please reopen if not.
