### ISSUE TITLE
New Feature -  Share on social network

### ISSUE THREAD

**Issue by ocontant** [owncloud/core#8271]
Add social network share button to share an object via a social network. 
Would create a tinyurl and post on the social site.

**Comment by d121096** [comment]
would be really nice to share pictures on facebook directly from owncloud

**Comment by DeepDiver1975** [comment]
> This can/should be a separate app.

Indeed topic for an app - nothing we will support directly in core. I'm closing this ticket therefore. THX

**Comment by tflidd** [comment]
I agree that this isn't an issue for core. Can you give such issues a label that people liking this feature can give some money via bountysource or do you have a different repo for potential features outside core?
