### ISSUE TITLE
New Feature - API functions related to billing

### ISSUE THREAD

**Issue by ocontant** [owncloud/core#8273]
Would be useful to have API call related to billing statistic. List example _some are probably already implemented_
- Get config Quota for User
- Get storage usage by User _Including external source that use local space_
- Get nbs of files stored by User
- Get list of devices linked to account of User
- Get bandwidth usage per User

**Comment by PVince81** [comment]
storage stats raised here https://github.com/owncloud/core/issues/1344

**Comment by PVince81** [comment]
@pmaier1 FYI
