### ISSUE TITLE
ensure that objectguid or guid really return binary data before converting it

### ISSUE THREAD

**Issue by fleish** [owncloud/core#8317]
I am unable to login to owncloud using certain ldap usernames that contain a period. I get:
{"app":"core","message":"Login failed: user 'some.username' , wrong password, IP:set log_authfailip=true in conf","level":2,"time":"2014-04-23T00:26:24+00:00"}

updating this to say it's not all ldap users with periods in their names. but a good number of them fail to login and do not even show up in the user list. however, when I look at the owncloud ldap configuration the user filter shows 61 users found which includes all of the users with periods in their names.

another update to say I figured out the cause of my issue. the problem users were not in the sqlite3 owncloud.db for oc_ldap_user_mapping & oc_group_user. not sure why these users were not added into there by owncloud automatically though so not closing this just yet. hopefully @blizzz or someone can shed some light.

@blizzz

**Comment by blizzz** [comment]
@fleish did you upgrate to 7 and swtich to MySQL?

**Comment by fleish** [comment]
@blizz I did upgrade using a funky path, details here: https://github.com/owncloud/core/issues/12801#issuecomment-85255342

I assume I still have to manually add new LDAP users to the mysql database which is what I've been doing. If that's correct & expected we can probably close this.

**Comment by blizzz** [comment]
Manually adding rows to the database is never expected, actually.

**Comment by blizzz** [comment]
@fleish does it work better with mysql now?

**Comment by fleish** [comment]
@blizzz I haven't had any complaints since moving to mysql. we do still have to manually insert a row into the db for each new LDAP user. It would be nice if OC automatically checked the LDAP server for new users periodically IMO, but we're used to doing it now so it's not a big burden.

**Comment by blizzz** [comment]
This is what is supposed to do. Just yesterday I tried again with both periods and commas in the DN and it worked fine. However I also have another report who has troubles. 

Do run it against OpenLDAP, AD or another server?

**Comment by blizzz** [comment]
Also, could you paste your LDAP configuration?

**Comment by blizz** [comment]
Please remove me from the CC line.
Brett
 


     On Wednesday, June 17, 2015 5:34 AM, blizzz <notifications@github.com> wrote:
   

 Also, could you paste your LDAP configuration? —

**Comment by fleish** [comment]
@blizzz are you saying OC is supposed to sync with LDAP or are you referring to periods in usernames? for clarity, the periods in usernames issue hasn't been observed in a long time now. I think it was probably user error being masked as something else.

We are using OpenLDAP. Configuration below:
+------------------------------+---------------------------------------------+
| Configuration                |                                             |
+------------------------------+---------------------------------------------+
| hasMemberOfFilterSupport     |                                             |
| hasPagedResultSupport        |                                             |
| homeFolderNamingRule         |                                             |
| lastJpegPhotoLookup          | 0                                           |
| ldapAgentName                |                                             |
| ldapAgentPassword            | ***                                         |
| ldapAttributesForGroupSearch |                                             |
| ldapAttributesForUserSearch  |                                             |
| ldapBackupHost               |                                             |
| ldapBackupPort               |                                             |
| ldapBase                     | dc=domain,dc=org                         |
| ldapBaseGroups               | dc=domain,dc=org                         |
| ldapBaseUsers                | dc=domain,dc=org                         |
| ldapCacheTTL                 | 5                                           |
| ldapConfigurationActive      | 1                                           |
| ldapEmailAttribute           |                                             |
| ldapExperiencedAdmin         | 0                                           |
| ldapExpertUUIDGroupAttr      |                                             |
| ldapExpertUUIDUserAttr       | UUID                                        |
| ldapExpertUsernameAttr       |                                             |
| ldapGroupDisplayName         | cn                                          |
| ldapGroupFilter              | (|(cn=owncloud))                            |
| ldapGroupFilterGroups        |                                             |
| ldapGroupFilterMode          | 0                                           |
| ldapGroupFilterObjectclass   |                                             |
| ldapGroupMemberAssocAttr     | memberUid                                   |
| ldapHost                     | ldaps://ldap.domain.org/                 |
| ldapIgnoreNamingRules        |                                             |
| ldapLoginFilter              | (&(|(objectclass=inetOrgPerson))(uid=%uid)) |
| ldapLoginFilterAttributes    |                                             |
| ldapLoginFilterEmail         | 0                                           |
| ldapLoginFilterMode          | 1                                           |
| ldapLoginFilterUsername      | 1                                           |
| ldapNestedGroups             | 0                                           |
| ldapNoCase                   | 0                                           |
| ldapOverrideMainServer       | 0                                           |
| ldapPagingSize               | 500                                         |
| ldapPort                     | 636                                         |
| ldapQuotaAttribute           |                                             |
| ldapQuotaDefault             |                                             |
| ldapTLS                      | 0                                           |
| ldapUserDisplayName          | cn                                          |
| ldapUserFilter               | (|(objectclass=inetOrgPerson))              |
| ldapUserFilterGroups         |                                             |
| ldapUserFilterMode           | 1                                           |
| ldapUserFilterObjectclass    | inetOrgPerson                               |
| ldapUuidGroupAttribute       | auto                                        |
| ldapUuidUserAttribute        | auto                                        |
| turnOffCertCheck             | 0                                           |
+------------------------------+---------------------------------------------+

@blizz I don't see where you were tagged here for cc, nor do I see a way for me to remove you. You should be able to unsubscribe from notifications by visiting the github thread directly here: https://github.com/owncloud/core/issues/8317

**Comment by blizz** [comment]
Am on the CC line.  Do I need to log into github to unsubscribe?  Please know that I have never subscribed to any of these hundreds of messages that are often filling up my inbox and notifying my cell.
Brett



fleishToowncloud/coreCCblizzToday at 10:37 AM@blizzz are you saying OC is supposed to sync with LDAP or are you referring to periods in usernames? for clarity, the periods in usernames issue hasn't been observed in a long time now. I think it was probably user error being masked as something else.We are using OpenLDAP. Configuration below:
+------------------------------+---------------------------------------------+ 



     On Wednesday, June 17, 2015 10:37 AM, fleish <notifications@github.com> wrote:
   

 @blizzz are you saying OC is supposed to sync with LDAP or are you referring to periods in usernames? for clarity, the periods in usernames issue hasn't been observed in a long time now. I think it was probably user error being masked as something else.We are using OpenLDAP. Configuration below:
+------------------------------+---------------------------------------------+
| Configuration | |
+------------------------------+---------------------------------------------+
| hasMemberOfFilterSupport | |
| hasPagedResultSupport | |
| homeFolderNamingRule | |
| lastJpegPhotoLookup | 0 |
| ldapAgentName | |
| ldapAgentPassword | *** |
| ldapAttributesForGroupSearch | |
| ldapAttributesForUserSearch | |
| ldapBackupHost | |
| ldapBackupPort | |
| ldapBase | dc=domain,dc=org |
| ldapBaseGroups | dc=domain,dc=org |
| ldapBaseUsers | dc=domain,dc=org |
| ldapCacheTTL | 5 |
| ldapConfigurationActive | 1 |
| ldapEmailAttribute | |
| ldapExperiencedAdmin | 0 |
| ldapExpertUUIDGroupAttr | |
| ldapExpertUUIDUserAttr | UUID |
| ldapExpertUsernameAttr | |
| ldapGroupDisplayName | cn |
| ldapGroupFilter | (|(cn=owncloud)) |
| ldapGroupFilterGroups | |
| ldapGroupFilterMode | 0 |
| ldapGroupFilterObjectclass | |
| ldapGroupMemberAssocAttr | memberUid |
| ldapHost | ldaps://ldap.domain.org/ |
| ldapIgnoreNamingRules | |
| ldapLoginFilter | (&(|(objectclass=inetOrgPerson))(uid=%uid)) |
| ldapLoginFilterAttributes | |
| ldapLoginFilterEmail | 0 |
| ldapLoginFilterMode | 1 |
| ldapLoginFilterUsername | 1 |
| ldapNestedGroups | 0 |
| ldapNoCase | 0 |
| ldapOverrideMainServer | 0 |
| ldapPagingSize | 500 |
| ldapPort | 636 |
| ldapQuotaAttribute | |
| ldapQuotaDefault | |
| ldapTLS | 0 |
| ldapUserDisplayName | cn |
| ldapUserFilter | (|(objectclass=inetOrgPerson)) |
| ldapUserFilterGroups | |
| ldapUserFilterMode | 1 |
| ldapUserFilterObjectclass | inetOrgPerson |
| ldapUuidGroupAttribute | auto |
| ldapUuidUserAttribute | auto |
| turnOffCertCheck | 0 |
+------------------------------+---------------------------------------------+@blizz I don't see where you were tagged here for cc, nor do I see a way for me to remove you. You should be able to unsubscribe from notifications by visiting the github thread directly here: #8317—

**Comment by LukasReschke** [comment]
@blizz 

![2015-06-17_20-06-09](https://cloud.githubusercontent.com/assets/878997/8214843/55f2f760-152c-11e5-9aa4-0c3654a0ecd0.png)

**Comment by blizzz** [comment]
@fleish 

> are you saying OC is supposed to sync with LDAP or are you referring to periods in usernames?

ownCloud is getting it's users live form LDAP, unless cache is in effect (10min per default, but yours is set to 5sec. So it's working pretty much online for you). Known users are mapped in the database table. A constraint is that users to be fetched must have the display name attribute set, but we ensured it is in your case. 

About periods in usernames I don't know, but they should not be an issue anyway.

In your configuration i've seen this:

> | ldapExpertUUIDUserAttr | UUID |

That is most likely the issue here. UUID itself is not an attribute, thus ownCloud is not able to read it and will not map the users. When you inserted the user manually into the DB table, what did you set for directory_uuid? 

This value is checked against the UUID attribute (either set or auto-detected) in case a DN changes to be able to find the user again.

**Comment by fleish** [comment]
@blizzz we modified our directory to have an attribute named UUID for each user for OC and other things that require it. when we insert a user into the table, we provide the user's UUID from our LDAP like so: 
INSERT INTO oc_ldap_user_mapping VALUES('uid=userfirst.userlast,dc=domain,dc=org','49bda228-6cbf-4f12-a987-49b9ed08f6df','49bda228-6cbf-4f12-a987-49b9ed08f6df');

**Comment by blizzz** [comment]
Does the attribute contain string or binary data?

**Comment by fleish** [comment]
String. And now that I'm looking closer at it, the attribute isn't UUID, it's GUID.

Going in the way-back part of my brain, I think GUID might have been setup for caldav initially and then OC piggy-backed onto it. I'm now thinking it was not necessary for the latter (and maybe even the former) since LDAP auto-generates "entryUUID" for every record anyway. We manually add GUID to each user we create which now seems like extra work over just re-using the entryUUID and telling apps to look for that instead of GUID.

Anyway, for OC in particular it seems like this should be set to GUID instead of UUID in our current setup. This also explains why some of our initial users UUID in OC does not match their GUID in ldap. These users are actually using their entryUUID instead of GUID value. So on second though, perhaps we cannot switch this value to GUID as it might break the old users who are setup like this.

**Comment by blizzz** [comment]
That is the answer to that riddle. 

If you would decide to switch from invalid UUID to GUID, old users are not affected from the change, as long as you don't clear the mappings (which you should not do in production for exactly this reason). In case a DN might change for a user, you would run into an issue right now as well. So changing it to GUID should be safe and help with new users. :warning: **EXCEPT** :warning: GUID is used by AD (i think) in a binary format (definitely) and we would attempt to convert it. Likely you get something useless out of it, in the worst case even same results for different users. 

So don't do it right now (unless you have something else that is not called GUID or objectGUID, or just openLDAPs own entryuuid which would be used by default if you empty the setting).

**Comment by blizzz** [comment]
Task on ownCloud is now to figure out whether it's possible to distinguish whether we get binary or string data from LDAP (I assume so) and to build in a check to avoid such happenings.

**Comment by fleish** [comment]
@blizzz Doh! I just confirmed by removing UUID and new user logins have entries auto-created in DB with internal LDAP entryUUID. I suspect when I implemented GUID for our calendarserver I thought it would be good to have a single GUID across all services and mistakenly changed Owncloud to UUID instead of GUID.

And for sure something weird happens if set to GUID, I got a non-matching (and much longer) UUID inserted into the database along with some constraint violations logged (pasted below).

{"app":"hook","message":"error while running hook (OCA\\Encryption\\Hooks::login): An exception occurred while executing 'INSERT INTO oc_preferences (userid, appid, configkey, configvalue) VALUES (?, ?, ?, ?)' with params [\"65646434-3664-3161-2D63-3334392D346232372D613339322D663862353164653437653361\", \"files_encryption\", \"migration_status\", \"0\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '65646434-3664-3161-2D63-3334392D346232372D613339322D663862353164' for key 'PRIMARY'","level":3,"time":"2015-06-22T19:52:25+00:00"}

{"app":"index","message":"Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO oc_preferences (userid, appid, configkey, configvalue) VALUES (?, ?, ?, ?)' with params [\"65646434-3664-3161-2D63-3334392D346232372D613339322D663862353164653437653361\", \"files_encryption\", \"migration_status\", \"0\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '65646434-3664-3161-2D63-3334392D346232372D613339322D663862353164' for key 'PRIMARY'","level":4,"time":"2015-06-22T19:52:25+00:00"}

{"app":"index","message":"Doctrine\\DBAL\\DBALException: An exception occurred while executing 'INSERT INTO oc_preferences (userid, appid, configkey, configvalue) VALUES (?, ?, ?, ?)' with params [\"65646434-3664-3161-2D63-3334392D346232372D613339322D663862353164653437653361\", \"files_encryption\", \"migration_status\", \"0\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '65646434-3664-3161-2D63-3334392D346232372D613339322D663862353164' for key 'PRIMARY'","level":4,"time":"2015-06-22T19:52:27+00:00"}

**Comment by blizzz** [comment]
> And for sure something weird happens if set to GUID, I got a non-matching (and much longer) UUID inserted into the database along with some constraint violations logged (pasted below).

Because we assume that a binary value was retrieved and convert it. Works with string data apparently as well.

**Comment by PVince81** [comment]
@fleish are you still seeing this in 8.1 ?

@blizzz what's the status ?

**Comment by blizzz** [comment]
Moving to 9.0 since it's feature/enhancement

**Comment by fleish** [comment]
@pvince81 I'm not yet on 8.1, but I can't imagine any behavior has changed unless the code/logic around the GUID/UUID value has changed. We'll probably be forced to continue setting this manually and creating users in the DB by hand until it is addressed in a future release since changing the GUID for all of our users so we could go back to using UUID seems like it'd have the potential to be a major issue.

**Comment by PVince81** [comment]
@jvillafanez your thoughts ?

**Comment by PVince81** [comment]
likely obsolete as the code has changed

if the problem still exists in 9.1.4 or 10.0 beta, feel free to reopen
