### ISSUE TITLE
Feature request encrypting keys using PGP

### ISSUE THREAD

**Issue by howlett** [owncloud/core#8330]
I would like to add an option to encrypt the already existing encryption keys with PGP and move the decryption to the device.

This will:
1. Allow users with slower connections to store content externally without the worry of the admin or on-the-wire interception.
2. Allow external data stores to send the content directly to the user (think an Amazon S3 sending the encrypted file instead of sending it to the owncloud server that has a slow uplink).

Sharing content could be accomplished by decrypting the key, encrypting with the new users public key and sending it that user.

My main reason for requesting this feature is the limited upload speed of my local internet connection and requiring the trust of the external server admin.

I'm going to look into adding this myself, but I would like to hear comments/suggestions/support for the idea.

**Comment by LukasReschke** [comment]
Can be implemented as custom app with encryption 2.0. I don't really see this happening in core.
