### ISSUE TITLE
Trying to upload same files with no changes..

### ISSUE THREAD

**Issue by tripmonkey** [owncloud/core#8346]
I use ownCloud to sync files between my PC and Pandora handheld device. These are usually Game saves etc. which I don't want to loose or get corrupted.

My PC uses ownCloud version 1.5.3 and the Pandora uses 1.5.0.2.

It tries to upload the same 3 zip files every minute from my PC which in turn causes the Pandora to download the files and upload them again. It does this continuously until I turn ownCloud off. If I turn the Pandora off the PC just keeps syncing them with the server.

I've tried removing the files from both devices and the server and then adding them back again but it didn't help. It just seems stuck in a loop and fixated with these 3 files.

Anything I can do to sort it out from this end?

**Comment by enoch85** [comment]
@tripmonkey Any update on this?

**Comment by nickvergessen** [comment]
If the issue does still happen on OC8 with the new client 1.8, please open a new issue
