### ISSUE TITLE
User management: Confirmation for deleting users

### ISSUE THREAD

**Issue by tessus** [owncloud/core#8347]
(openening a separate issue as requested by @jancborchardt in #1212)

I understand the concept of undo, but this concept is wrong for deleting users. Somebody could hit the mouse button twice and thus the data of the first user is gone w/o being able to undo the damage. 

There should be a confirmation. But I don't mean simple *are you sure* and *yes/no*, but something like:
**Enter the name of the user to delete the user and ALL their data.**

**Comment by Xenopathic** [comment]
There is the undo notification, which cannot simply be discarded by clicking on the main form. I think this covers the requirement (there's no way to accidentally delete a user)

**Comment by tessus** [comment]
@Xenopathic This is only true, if you don't leave the user page by mistake. Unless you have the undo option (next to the deleted user) for - let's say - 120 minutes (no matter where you click and go), this current behavior is far too dangerous.

**Comment by jancborchardt** [comment]
@tessus a timeout this long will lead to one of these situations:
* complaints that users can’t be deleted fast enough (in the case we’re lying about deletion and keep them activated for 120 minutes [120!?] still)
* lots of stuff being moved in the filesystem and database if the user data gets moved right away

**Comment by tessus** [comment]
@jancborchardt 
> complaints that users can’t be deleted fast enough (in the case we’re lying about deletion and keep them activated for 120 minutes [120!?] still)

no, you misunderstood. the user should be set to an inactive state, but the data should still be avilable to undo the deletion. but this was just a suggestion, because the issue was closed, even though I've opened it on your request. so at some point, you also thought that having a confirmation was not a bad idea.

This was my original idea:

There should be a confirmation. But I don't mean simple are you sure and yes/no, but something like:
**Enter the name of the user to delete the user and ALL their data.**
