### ISSUE TITLE
Provide a super user for sharing folders of all users

### ISSUE THREAD

**Issue by gig13** [owncloud/core#8359]
Can there be a super user which is capable of sharing folders for other users? This would be useful in providing folders for an "organizational unit" by an admin.

**Comment by hodyroff** [comment]
It seems an extra user is no problem to address this. Access to other peoples folders is not a default action we like. For support needs, we do have an app available (for subscription customers) which also allows this, but usage of that is and should be restricted. (Impersonate app).
