### ISSUE TITLE
[Enhancement] Hooks in the files_versions app

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/core#8379]
I think it could be useful to trigger an event when a new version of a file is created.

Right now this task is complex. I've tried the following:

1) Use the FS copy hook, looking for copies from /files to /files_versions. This seems not to be working because the triggers seems disabled at that point.

2) Use the FS write hook. Not working because we cannot guarantee the order of the callbacks. My callback seems to be executed before the callback who creates the copy, so the version is not created yet.

3) Use the FS post_write hook. This should make possible to get the information of the version created (my callback is executed after the version is created), but I need to know how version names are created (I don't think I should know).

I'm currently using the 3rd one, but I cannot prevent the copy if something goes wrong. In addition, the callback triggers more times that it should (twice per write it seems - I'll recheck if needed), and there is also the problem that we cannot distinguish between a new file and a new version being created (I'm just interested in the version, so the callback shouldn't trigger when a file is created)

Just to provide information, I need to know the fileid of the created version to be able to map correctly an external id with the fileid. Since the fileid of the original file is changed, I need to know this new fileid to update it in my own table.

**Comment by PVince81** [comment]
@jvillafanez did we ever add such hooks ?

Note that fileid can be retrieved from the path, see https://github.com/owncloud/core/issues/29604
