### ISSUE TITLE
Feature Request: Choose if an account is able to use sync client or not

### ISSUE THREAD

**Issue by KKyang** [owncloud/core#8385]
Is it able to add any limitations to choose whether an account is able to use sync client or not? Cause if there are multiples admins, they might delete any shared files accidentally while accidentally using sync-client (but they shouldn't).
I know this request may sounds strange but it may help someone that is careless.

**Comment by Xenopathic** [comment]
This is an XY problem - your problem isn't that certain people can use the sync client when they shouln't be, but rather that the permissions are incorrectly configured and/or your admins need training. Blocking WebDAV is not only technically infeasible, but would effectively prevent access to all of ownCloud (especially with files moving to use it) so you might as well delete the user in this case.
