### ISSUE TITLE
openstack swift external mount doesn't support v1 auth api

### ISSUE THREAD

**Issue by johnl** [owncloud/core#8410]
It looks as though the openstack swift external mount now only supports v2.0 keystone auth and no longer supports v1 auth api.

I'm entering a v1.0 auth url and the logs show owncloud is appending /tokens onto it when making the request, which is a v2 keystone thing.

Not only that, the gui seems very confused now. For example, it says "region" is optional, but the logs claim is is required. And it won't proceed with just the "api key" box filled (it won't even write data/user/mount.js config file) - it requires the "Password" box filled too.

All in all, it looks like the recent work done to add v2.0 keystone support has broken or removed v1.0 auth support, and the gui hasn't caught up yet.

It should be possible to support both v1 and v2 (v1 used to be supported!)

tested with latest stable v6.0 release of owncloud and also ownCloud 7.0 pre alpha (daily) Build:2014-03-21T03:13:27+00:00

**Comment by PVince81** [comment]
What to do with this ? Should support be added for both v1 and v2 auth ? (not sure if the lib supports that but would be nice)

**Comment by butonic** [comment]
Just had a look at the ZF2 implementation. It seems they support v1 as well as v2: 
https://github.com/zendframework/ZendService_OpenStack/blob/master/tests/ZendService/OpenStack/Identity/IdentityTest.php#L99
https://github.com/zendframework/ZendService_OpenStack/blob/master/tests/ZendService/OpenStack/Identity/IdentityTest.php#L109

zf2 also has implementations for windows azure, rackspace and whatnot:
https://github.com/zendframework?utf8=%E2%9C%93&query=zendservice

**Comment by PVince81** [comment]
Is this still required or did all server providers have moved to auth v2 ?

ownCloud uses the php-opencloud lib and if that one doesn't support v1 auth then it is unlikely that an upgrade would provide such support. I haven't done a deeper research there so I might be wrong.

If the lib doesn't support auth v1, switching to a different library is a bigger change.

**Comment by johnl** [comment]
My provider is still using v1, I don't know how prevalent it is overall though. It's still supported by openstack swift, doesn't seem to be marked deprecated and it's used by their example TempAuth middleware too.

**Comment by bradjones1** [comment]
@johnl v1 is not supported by the php-openstack library that OwnCloud is using, see https://github.com/rackspace/php-opencloud/issues/404

I am looking into maybe coding one, but this is for a personal project so all dependent on time. But that's the answer to your question.

**Comment by hodyroff** [comment]
As we got requests for v3 now, I doubt v1 will ever come. If somebody is willing to invest, please reopen. If somebody is willing to implement v3, please step up!
