### ISSUE TITLE
Cancel a long list of upload, notification blinks

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#8433]
#### Steps:
1. Click on the upload button in the web UI
2. Select a long list of files that will take a few minutes to upload
3. While the upload runs, click on "Cancel Upload"
4. Observe the notification area

### Expected result
Upload cancelled, notification appears once.

### Actual result
Upload cancelled, notification blinks once for every file.

### Versions
ownCloud 7 pre-alpha (git master 6519b9672a7294282c9535d8544baea9a9d74ffd)

**Comment by jancborchardt** [comment]
@PVince81 any news on this? Is anyone working on this for 8.1 actually?

**Comment by PVince81** [comment]
Deferring killing the disco effect to 8.2

**Comment by kkampardi** [comment]
Hi there, i'm interesting in working on this feature, is anybody else working too?

**Comment by kkampardi** [comment]
Hi there,i 'm interesting in working onthis feature. Is anybody else working too?

**Comment by PVince81** [comment]
@kkampardi feel free to take over :smile:

**Comment by kkampardi** [comment]
@PVince81 i'll keep you posted :-)

**Comment by jancborchardt** [comment]
@kkampardi you're also welcome in our IRC channels #owncloud-dev and #owncloud-design (freenode IRC network). :) Let us know if you have any questions.

**Comment by kkampardi** [comment]
@jancborchardt thanx!! That would be very helpful :)

**Comment by cmonteroluque** [comment]
@kkampardi any progress? Thank you for your help!

**Comment by kkampardi** [comment]
I had some time issues the last two months so i don't have any progress to
show :-/
However i have already done some work and id' like to give it another
chance
unless you need to assign this  issue to another collaborator

Thanks in advance


On Wed, Sep 9, 2015 at 11:35 PM, C. Montero Luque <notifications@github.com>
wrote:

> @kkampardi <https://github.com/kkampardi> any progress? Thank you for
> your help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/core/issues/8433#issuecomment-139038178>.
>



-- 
Κατερίνα Καμπάρδη
Web Developer
*Graphicode - Web  applications*
211 790 2526, 6976 985 131
www.graphicode.gr

**Comment by jancborchardt** [comment]
@kkampardi that’s totally fine. :) If you have some work-in-progress done, you can already open a pull request. Then we can help you and collaborate on that. :)

**Comment by kkampardi** [comment]
@jancborchardt  ( or anyone who can help) i think i have locate that the problem is in  apps/files/js/file-upload.js
I think that the code for notifications should be directly in  cancelUploads (line 66 )
instead of  fail (line 382). To do this correctly i need to change the prototype of cancelUploads() to cancelUploads(data). Do you think  that 'll work?

I am a newbie with js dev so any help will be appreciated :)

**Comment by jancborchardt** [comment]
cc @PVince81 & @MorrisJobke for JS help ^ :)

**Comment by PVince81** [comment]
Fix is here https://github.com/owncloud/core/pull/19628

**Comment by PVince81** [comment]
Fixed through https://github.com/owncloud/core/pull/19628

**Comment by MorrisJobke** [comment]
master: https://github.com/owncloud/core/pull/19710
stable8.2: #19778
