### ISSUE TITLE
User Privacy

### ISSUE THREAD

**Issue by Huster-at-github** [owncloud/core#8446]
OC should have the possibility for all users to choose their privacy inside the ownCloud: To be seen by others users or not.

I.e. a personality setting like
"Should your account been seen by others users or not? (private/public)"
would be nice.

Default-Setting (private) should be an administrator issue.

Regarding this forum-topic: https://forum.owncloud.org/viewtopic.php?f=21&t=21200

**Comment by jancborchardt** [comment]
The comparison to Dropbox doesn’t really hold since not all ownCloud users are on one server. It’s intended for teams, so this option doesn’t really make sense.
