### ISSUE TITLE
WebDav fails or gets really slow using Windows mapped Drives or WebDav Clients

### ISSUE THREAD

**Issue by viasys** [owncloud/core#8449]
Hello,

I hope this is the correct area to post this Issue. I tried to find similiar Issues with the Search here and with google but i couldn't find any.

I am experiencing the following Issue(s) when I'm trying to either map the Owncloud WebDav Interface via Windows Explorer or with a WebDav Client like Cyberduck:

The Connection to the private area of the User works almost instant and without any Problems, but as soon as i navigate to Shared, it takes around 15 Seconds to load the contents of the Directory (there are 12 Folders). When I now try to navigate even deeper it either takes several Minutes to load the contents or it fails completly, while Windows tells me the Network Path is not available.
When i try to access the WebDav Interface with Firefox or with cadaver it takes only around 2 seconds to load the Folders.

I'm not sure how i can further debug this Issue, the only errors i can find in the Owncloud Log are:

Fatal 	webdav 	Sabre_DAV_Exception_NotFound: File with name desktop.ini could not be located 
Fatal	webdav	Sabre_DAV_Exception_NotFound: File with name Shared/desktop.ini could not be located
Fatal	webdav	Sabre_DAV_Exception_NotFound: File with name Shared/folder.jpg could not be located
Fatal	webdav	Sabre_DAV_Exception_NotFound: File with name Shared/folder.gif could not be located
Debug 	OC\Files\Cache\Scanner 	!!! Path 'Vi Projects/folder.gif' is not readable !!! 
Debug	OC\Files\Cache\Scanner	!!! Path 'Vi Projects/desktop.ini' is not readable !!!

The Folder "Vi Projects" is directly within the Shared folder, there are no such files as "folder.gif, folder.jpg or desktop.ini". When I browse to those location using the normal Owncloud Browser Interface i dont get any errors. Also syncing the Files using the Owncloud Sync Client is working without any Problems. Files and Folders are readable. As soon as i navigate to the Directorys below Shared, one Apache process jumps up to 100% CPU of 1 of the 6 CPU Cores and the database jumps to ~25%.

My Setup:
XenServer virtual Host, 6CPU-Cores 8GB RAM, Gigabit Ethernet.
Owncloud 6.0.3
Debian 7
PHP 5.4.4-14+deb7u9
MariaDB 5.5
Apache
The Cloud contains around 200GB of Files

**Comment by MorrisJobke** [comment]
@viasys @gonetil Please update to a more recent version of ownCloud like 8.0.5 or 8.1.0 because many performance enhancement landed in there. If the problem still exists you can report back here and we will reopen the ticket.

Thanks
