### ISSUE TITLE
Deleted Files Recovery doesn't work

### ISSUE THREAD

**Issue by polaris20** [owncloud/core#8463]
### Expected behavior
After files are deleted, I should be able to click on the "Deleted Files" button, and select from files deleted to recover. 

### Actual behavior
After deleting files, the "Deleted Files" button is there, but greyed out and non-functional.

### Server configuration
**Operating system**: Ubuntu 14.04LTS x64

**Web server:** Apache 2.4.7

**Database:** MySQL 5.5.37

**PHP version:** 5

**ownCloud version:** (see ownCloud admin page) 6.0.3

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:** Activity, Files

**The content of config/config.php:** 

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...Local

**Are you using encryption:** No

### Client configuration
**Browser:** Safari, Chrome, Firefox, IE11

**Operating system:** Ubuntu Linux, OS X 10.9, Windows 8.1.

The rest of the information required is irrelevant at this point, because I've already gone back to an earlier snapshot and discovered what the problem is. 

If the installer configures a data directory outside of the /www/var/owncloud folder prior to first-time setup wizard, and designates it within the first-time install, Deleted Files functionality works fine. If the installer goes through the first-time install, and then following that creates a new data directory, and then manually changes it within /var/www/owncloud/config/config.php, all functionality appears to work fine EXCEPT "Deleted Files".

**Comment by Xenopathic** [comment]
@polaris20 Is this still an issue for you? I've tried moving the data directory to a different location, and @stanelie 's config.php options, but have been unable to replicate the problem.

**Comment by polaris20** [comment]
No I am not having the issue anymore; seems to have worked itself out during one of the updates.

From: Robin McCorkell
Reply-To: owncloud/core
Date: Friday, March 6, 2015 at 5:17 AM
To: owncloud/core
Cc: Jeff Biesiadecki
Subject: Re: [core] Deleted Files Recovery doesn't work (#8463)


@polaris20<https://github.com/polaris20> Is this still an issue for you? I've tried moving the data directory to a different location, and @stanelie<https://github.com/stanelie> 's config.php options, but have been unable to replicate the problem.

**Comment by Xenopathic** [comment]
Excellent. Thanks for the confirmation :smile:
