### ISSUE TITLE
Add file with link does not work behind proxy

### ISSUE THREAD

**Issue by tomys** [owncloud/core#8485]
If a file was added by the function "New" -> "From Link" this does not work behind a proxy. The tcpdump show me that the request goes directly to the url without a proxy request.
The "proxy" setting in config.php is present and correct.
No error in the admin panel about a proxy issue.

**Comment by LukasReschke** [comment]
We had a discussion about this feature and decided to remove it with ownCloud 8.1.0 (the next upcoming major release) as it was barely used and added a lot of additional code to the logic.

Thus we will not fix this bug in specific for now. I'd recommend you to take a look at apps like ocDownloader from https://apps.owncloud.com/

Thanks!
