### ISSUE TITLE
New Feature: Wipe remotely data on client

### ISSUE THREAD

**Issue by ocontant** [owncloud/core#8495]
An important feature for business is the capacity to control data on remote device.  If an employee is fired, it is important to revoke his access to the data.  Remote wiping is crucial for any business with sensible material.  A way to somehow validate that the data has been successfully erased. 

I had many request like this from my clients.  

Is it implementable on the current architecture/design model?

**Comment by Xenopathic** [comment]
This would be implemented as a separate app along with a patch for the desktop client (or a separate mini-client that just handles this feature)
