### ISSUE TITLE
Error - files_external: Curl error: (28) Operation timed out after 300013 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#8498]
Just got this message when trying to restore from the trash bin. 

Is it a debug message or should I be worried?

Btw, not logging DEBUG atm, but still got it.

### Steps to reproduce
In conection with the 404 Forbidden in this issue: #8501 

### Expected behaviour
No timeout or error logging

### Actual behaviour
Timeout as described in the error logging

### Server configuration
Ubuntu Server (viritual)

**Database:**
MySQL latest
**PHP version:**
Latest PHP version
**ownCloud version:** (see ownCloud admin page)
6.0.3
**Updated from an older ownCloud or fresh install:**
Updated from 6.0.2 and 6.0.1
**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
External Storage Support
First Run Wizard
Full Text Search
Music
PDF Viewer
Pictures
Share Files
Tasks
Text Editor
Updater
Versions
Video Viewer

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'oc106ccbdf7c',
  'passwordsalt' => ',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '6.0.3.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost.localdomain',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_enoch',
  'dbpassword' => '',
  'installed' => true,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'session_lifetime' => 1800,
  'check_for_working_webdav' => false,
  'forcessl' => true,
  'updatechecker' => true,
  'loglevel' => '2',
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' =>
  array (
    0 => 'enochowncloud.no-ip.org',
  ),
);

```
Insert your config.php content here
(Without the database password and passwordsalt)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
Dropbox
**Are you using encryption:** yes/no
No
### Client configuration
**Browser:**
Chrome Version 34.0.1847.131 m
**Operating system:**
Windows 8.1
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
I guess you're still seeing this with 7.0.5 or 8.0.2 ?

**Comment by enoch85** [comment]
Nope. Forgot to close this. Thanks.
