### ISSUE TITLE
cron.php warning: first array member is not a valid class name or object

### ISSUE THREAD

**Issue by rasos** [owncloud/core#8500]
We use as cronjob option crontab, as suggested here on a OC 6.0.3 server:
http://doc.owncloud.org/server/5.0/admin_manual/configuration/background_jobs.html

Several times a day, but not at every call, we get the following:
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, first array member is not a valid class name or object in /var/www/owncloud/lib/private/backgroundjob/legacy/queuedjob.php on line 16

Trying to get rid of e-mails sent due to the cron error (which is the default behaviour with crontab) by redirecting cron errors to a logfile:
*/15  *  *  *  * php -f /var/www/owncloud/cron.php > /var/log/owncloudcron.log 2>&1

We are also facing some folders, which are new on OC (provided through the GroupOffice App), not being triggered for syncing, but this may be another issue (will report, when we see some pattern and can exclude cron or app misbehaviour).

**Comment by PVince81** [comment]
I don't see anything wrong with these class names.

Also the "XML parsing" issues in the log are suspicious.

@rasos are you still seeing this in 7.0.5 or 8.0.2 ?

**Comment by PVince81** [comment]
Please try again with 8.1.3 or 8.2RC1
