### ISSUE TITLE
 Fatal webdav: Sabre_DAV_Exception_Forbidden:

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#8501]
(Sorry for not using the issue form, I didn´t find it...)

I have my sync client connected to a single folder on one of my comupters. The folder that´s connected is Dropbox and I sync a small amount of files.

Recently I noticed that I got 
"Fatal	 webdav	 Sabre_DAV_Exception_Forbidden:". And this message is getting logged  at the same time as I try to upload some files with the desktop sync-client. 

At th same time the files dosen´t get synced to my dropbox accont, and the client shows me the same error. 404 forbidden.

I don´t know if it´s related to the sync client or to the core, so I begin with posting the issue here.

### Client
1.5.4 (Windows 8.1)

1.5.5 (Android)

### Server

OC 6.0.3

### PHP & MySQL 

Everything is updated to the latest

### Server Enviroment
Ubuntu Server (viritual)

### Logs

Owncloud.log - as posted above

**Comment by enoch85** [comment]
@PVince81 Ping

**Comment by enoch85** [comment]
Related? #11797

**Comment by enoch85** [comment]
And also #13097

**Comment by enoch85** [comment]
@PVince81 Should we take a look at this?

**Comment by PVince81** [comment]
This ticket seemed to be related to renaming files on Dropbox, when putting special chars in it ? And that would cause the "Forbidden" to appear ?

**Comment by enoch85** [comment]
Not using Dropbox anymore, so can't tell you right now. But yes, I think this is Dropbox related. Keep open / Close / Fix? @PVince81

**Comment by PVince81** [comment]
I'll try and reproduce it first.

**Comment by enoch85** [comment]
Setting milestone 8.2 as @DeepDiver1975 said you will take a look at Dropbox then.

**Comment by PVince81** [comment]
Makes sense, thanks

**Comment by PVince81** [comment]
Dropbox works for me properly, even with special characters. I tried renaming a file "test.txt" to "aöäe.txt" and also moving it into a subdir. All worked fine.

I'll close this, maybe it was an old issue or something.
