### ISSUE TITLE
[6.0.3] - user attributes get updated on every request

### ISSUE THREAD

**Issue by jcfischer** [owncloud/core#8508]
fyi @karlitschek - that's what I said to you on tuesday

Version: ownCloud 6.0.3

The user_ldap function `userExists` https://github.com/owncloud/core/blob/master/apps/user_ldap/user_ldap.php#L247 calls `updateQuota` https://github.com/owncloud/core/blob/master/apps/user_ldap/user_ldap.php#L268 

This happens (afai can tell) on every request. UpdateQuota eventually ends up in `private/preferences.php` https://github.com/owncloud/core/blob/master/lib/private/preferences.php#L172 and updates the quota in the database.

The `setValue` function is kind of stupid and updates the value regardless if is the same in as the one stored in the database. Fixing this is quite easy:

```
	public function setValue( $user, $app, $key, $value ) {
		// Check if the key does exist by trying to pull old value

		$old_value = $this->getValue($user, $app, $key);
		$exists = $old_value !== null;
		if( !$exists ) {
			$data = array(
				'userid' => $user,
				'appid' => $app,
				'configkey' => $key,
				'configvalue' => $value,
			);
			$this->conn->insert('*PREFIX*preferences', $data);
		} else {
			// only update the key if the value has changed
			if( $old_value !== $value) {
				$data = array(
					'configvalue' => $value,
				);
				$where = array(
					'userid' => $user,
					'appid' => $app,
					'configkey' => $key,
				);
				$this->conn->update('*PREFIX*preferences', $data, $where);
			}
		}
	}
```

but I wonder, if the `userExists` function really should have the responsibility of updating quota (and email and avatar) on every request.

I would suggest to have 2 functions: one to check if the user exists and one to update the data (and then still fix the continous updating of the code, of course)

cheers
jc

**Comment by PVince81** [comment]
@DeepDiver1975 8.2 or backlog ?

**Comment by blizzz** [comment]
Meanwhile, quota, avatar and mail are updated only once in 24h and the save methods will not write to DB if the value has not changed. → Closing.
