### ISSUE TITLE
User management: filtering and groups

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#8516]
From https://github.com/owncloud/core/pull/7151

> I'm unclear on what the behavior should be when typing in the search box in regard to how the group list responds. Previously, I think the group list responded to the search criteria? I'm not sure, nor can I think of how that would work properly anyway.

@ringmaster @blizzz yes, that was the case previously. Filtering should filter both on users (both username and displayname) as well as the groups that users belong to.

Say I have the user »testing« who belongs to no group. Then the users »owen« and »jan« who belong to the group »Test«. Then the user »thomas« whose full name is »Thomas Test« (weird last name, I know).

Now when I search for »test«, all these users should show up. Prioritizing those which have a matching username/displayname.

And the group list should be updated accordingly – with the updated numbers next to the groups. And when there are groups of which neither a group name nor a user inside that group is a match, they should not be shown in the group list.

**Comment by DeepDiver1975** [comment]
@MorrisJobke @LukasReschke solved with OC8? THX

**Comment by MorrisJobke** [comment]
Nope

**Comment by MorrisJobke** [comment]
Or let's say it in another way: We didn't changed anything related to this

**Comment by DeepDiver1975** [comment]
> Or let's say it in another way: We didn't changed anything related to this

covered by another issue -> close
if not -> OC8.1

**Comment by MorrisJobke** [comment]
I added this to the list for 8.1 in #12998

**Comment by DeepDiver1975** [comment]
> I added this to the list for 8.1 in #12998

thx

**Comment by MorrisJobke** [comment]
Nope. I just referenced this issue ;)

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/8516

**Comment by cdamken** [comment]
> Closing in favor of #8516

😸

**Comment by PVince81** [comment]
Hmm, I don't remember which one. Let's keep it open then, it will surely pop up again.
