### ISSUE TITLE
User management: Search/filtering feedback

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#8517]
When there are no results when searching/filtering, there should be a text saying:
**No users or groups found for '`searchterm`'.**

Otherwise it’s confusing as to if it’s still searching or not.

cc @raghunayyar @blizzz @ringmaster

**Comment by jancborchardt** [comment]
@blizzz @icewind1991 this is the only section now where search doesn’t have an emptycontent message. Can you implement showing it? Just copy the HTML from the emptycontent of Files, what is shown for an empty folder.

**Comment by jancborchardt** [comment]
This is a bug, because no feedback makes it seem like the system is broken. @blizzz or @icewind1991 can you fix this, or cc the person who can?

**Comment by PVince81** [comment]
Indeed, still an issue in 9.1.0beta2 in user search.

**Comment by hodyroff** [comment]
Yes, should be fixed. Same behaviour like in the sharing user input field would be perfect. If user/group does not exist, the input field gets a red lining and says that user/group is not available.
@felixheidecke

**Comment by hodyroff** [comment]
Works in 10.0 Beta. Closing.
