### ISSUE TITLE
Can't share between users (external user support - smb)

### ISSUE THREAD

**Issue by morrigan777** [owncloud/core#8533]
I have external user support enabled using smb - localhost.
I can log in to owncloud with my local useraccounts.
But I can not share anything with an other account.

Example:
in windows i have 2 useraccounts: userA and userB
in owncloud I can log i with both users, using windows password.
in owncloud admin interface i only see my adminuser (none windows), this is correct according docu.

But when userA wants the share anything (files,calendar,contacts,..) with userB, userB can't be selected.
If I enter userB manually and hit enter, message no people found.

When I tried to create an userB in the owncloud admin interface, I got the message user already exists.

Does anyone have any suggestions?

### Steps to reproduce
in windows i have 2 useraccounts: userA and userB
in owncloud I can log i with both users, using windows password.
in owncloud admin interface i only see my adminuser (none windows), this is correct according 

docu.

But when userA wants the share anything (files,calendar,contacts,..) with userB, userB can't 

be selected.
If I enter userB manually and hit enter, message no people found.

When I tried to create an userB in the owncloud admin interface, I got the message user 

already exists.

PS: in your admin backend, the option to share with everyone is active..

### Expected behaviour
being able to share between userA and userB, being able to select them

### Actual behaviour
If I enter userB manually and hit enter, message no people found.
### Server configuration
**Operating system**: windows 7

**Web server:** IIS

**Database:** Mysql

**PHP version:** 5.3

**ownCloud version:** 6.0.1

**Updated from an older ownCloud or fresh install:** fresh install

**List of activated apps:** activity, bookmarks, calendar, contacts, delete files, documets, 

external user support (smb - localhost), first run wizard, full text search, pdf viewer, 

pictures, share files, tasks, text editor, updater, versions, video viewer, mozilla sunc

**The content of config/config.php:**

<?php
$CONFIG = array (
  'instanceid' => 'oc19f5fbbc86',
  'passwordsalt' => 

'e72d74234c61873fa507294e74ef36',
  'datadirectory' => 'D:\\ProgData\\CloudData',
  'dbtype' => 

'mysql',
  'version' => '6.0.0.16',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  

'dbtableprefix' => 'oc_',
  'dbuser' => 'sql**',
  'dbpassword' => 'pw**',
  'installed' => 

true,
"user_backends" => array (
    0 => array (
            "class"     => "OC_User_SMB",
            "arguments" => array (
                              0 => 'localhost'
                              ),
    ),
),
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
IE and firefox

**Operating system:**
win7

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
can't find any entrys about this, please let me know what's needed

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by MorrisJobke** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that the issue is not reproducible or it has been fixed in a newer version.

Please reopen if you still encounter this issue with the [latest stable version](http://owncloud.org/install/) and then please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md). You can also contribute directly by providing a patch – see the [developer manual](http://doc.owncloud.org/server/5.0/developer_manual/). :)

Thank you!
