### ISSUE TITLE
Uploading through WebDAV in Windows 7 gets error

### ISSUE THREAD

**Issue by KKyang** [owncloud/core#8563]
### System Configuration
**OS:** Ubuntu 14.04
**Server:** Apache 2.4.7
**PHP version:** 5.5.9
**Database:** MySQL
**OwnCloud:** 6.0.3 update from 6.0.2

### Step to Reproduce
1. Open explorer in Windows 7
2. Connect to Owncloud with WebDAV
3. copy a lot of files to Owncloud

### Actual Behavior
File upload progress stops randomly.

### Expect Behavior
Able to upload files without issues

### Owncloud log
```
Fatal	webdav	Sabre_DAV_Exception_NotFound: File with name desktop.ini could not be located	2014-05-13T03:58:50+00:00
Fatal	webdav	Sabre_DAV_Exception_NotFound: File with name Shared/share resources/南征北討/2012由田/desktop.ini could not be located	2014-05-13T03:58:02+00:00
Fatal	webdav	Sabre_DAV_Exception_Forbidden: 	2014-05-13T03:58:02+00:00
Fatal	webdav	Sabre_DAV_Exception_Forbidden: 	2014-05-13T03:58:02+00:00
Fatal	webdav	Sabre_DAV_Exception_Forbidden: 	2014-05-13T03:58:01+00:00
Fatal	webdav	Sabre_DAV_Exception_Forbidden: 	2014-05-13T03:58:01+00:00
Error	PHP	Maximum execution time of 30 seconds exceeded at Unknown#0	2014-05-13T03:58:00+00:00
Fatal	webdav	Sabre_DAV_Exception_LockTokenMatchesRequestUri: The locktoken supplied does not match any locks on this entity	2014-05-13T03:58:00+00:00
Fatal	webdav	Sabre_DAV_Exception_PreconditionFailed: The tokens provided in the if header did not match
```

**Comment by PVince81** [comment]
And now we removed WebDAV locking in the upcoming 8.1.

Would it work to just comment out the plugin as a workaround for older versions ?
The line is here: https://github.com/owncloud/core/blob/stable7/apps/files/appinfo/remote.php#L40
And in the server to server share code: https://github.com/owncloud/core/blob/stable7/apps/files_sharing/publicwebdav.php#L34

**Comment by PVince81** [comment]
@KKyang are you still seeing this with 8.1 or 8.2RC1 ?
