### ISSUE TITLE
Drag and Drop into Breadcrumbs

### ISSUE THREAD

**Issue by MTRichards** [owncloud/core#8570]
As a web user, I would like to be able to drag files and folders from inside the files view into the breadcrumbs at the top to make it easier to move files around inside ownCloud.

Today, you can drop files and folders down a level in ownCloud, but you can't drag files up a level. It would be great to be able to drag files around the interface both higher and lower in the file tree.

Not high priority, but a nice to have.

**Comment by colmoneill** [comment]
+1 for this enhancement!

**Comment by jancborchardt** [comment]
@colmoneill you interested in working on this? ;)

**Comment by notklaatu** [comment]
Agreed, moving files is extremely difficult.

I would love to have a Copy/Cut/Paste option in the '...' menu of items.

**Comment by PVince81** [comment]
I think I'd still want the drag/drop to breadcrumb.
You are right that it wouldn't work on mobile so might additionally need a cut/copy/paste feature too.

We're past feature freeze, moving to 9.1

**Comment by PVince81** [comment]
If someone has time, would be good to make UI mock up proposals for how cut/copy/paste would look like (actions menu vs selection bar vs sidebar vs ...) to see which could be the better approach.

**Comment by PVince81** [comment]
no more in scope. [Phoenix](https://github.com/owncloud/phoenix) is the future.
