### ISSUE TITLE
Speed up navigation by preloading hovered pages

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#8581]
We can probably learn a thing or two from the library at http://instantclick.io

> Before visitors click on a link, they hover over that link. Between these two events, 200 ms to 300 ms usually pass by (test yourself here). InstantClick makes use of that time to preload the page, so that the page is already there when you click.
> On mobile devices, preloading starts on “touchstart”, letting 300 ms (Android) to 450 ms (iOS) for preloading the page.2
> If you want your website to not be flooded by requests, you can set a delay before preloading starts when users hover a link. It will still feel instant. 

cc @owncloud/designers @DeepDiver1975

**Comment by PVince81** [comment]
Unlikely to work with dynamic web apps like ownCloud.

There are very few cases where links in the web UI would open a new page. Most links are either in-page actions (toggles) or app actions (ex: file actions). The only exception is probably the app switcher.

I don't think it's worth spending time on this as the benefit isn't that big.
Closing.
