### ISSUE TITLE
Feature Request: creating a "new user template"

### ISSUE THREAD

**Issue by chrisjscott** [owncloud/core#8595]
In considering using ownCloud in a SMB environment, it seems to me that it would be key to be able to create a standardized user template so that any newly-created user automatically includes a predetermined collection of bookmarks, contacts, etc.

**Comment by PVince81** [comment]
In 9.2 we'll trigger a "first login hook" so it should be possible to create an app that uses user templates to pre-populate the user data. Maybe it should even be the responsibility of the respective apps (calendar app for calendars, etc).

... and eventually move the skeleton stuff to be a separate app (cc @butonic)

**Comment by PVince81** [comment]
first login hook exists since 10.0, so apps can listen to it to automatically create whatever is necessary
