### ISSUE TITLE
upload new apps in webGUI

### ISSUE THREAD

**Issue by happyreacer** [owncloud/core#8608]
HI;
i miss a function or butten to upload lokal app - folder in a apps folder in owncloud. 
My problem is when i'm not on my server, i can't test or install apps from apps.owncloud.com but i have admin access on my webGUI everywere.

**Comment by oparoz** [comment]
Would love this

**Comment by DeepDiver1975** [comment]
I'm putting this to the backlog - pull request to implement this is welcome at any time.

**Comment by PVince81** [comment]
and also a command "occ app:install $sourceFolder"

**Comment by PVince81** [comment]
market app has `occ market:install --local package.tar.gz`.

if that's not enough, please reopen in https://github.com/owncloud/market repo
