### ISSUE TITLE
To many options to delete a file

### ISSUE THREAD

**Issue by schiessle** [owncloud/core#8630]
While working on some improvements for sharing I discovered that we have three ways to delete a file/directoy: `unlink()`, `deleteAll()` and `rmdir()`. Well I knew it already before, but this time it made a difference.

All three methods are able to delete single files and folders recursively. In fact if you delete a folder from the web interface we call "unlink()", while the same operation over webdav calls "rmdir()". This doesn't make a difference if you listen to hooks because we will trigger a "delete" hook for all three operations. But if you use proxies it makes a difference because then we call 'preUnlink()" and "preRmdir()" while "deleteAll()" seems to be converted to a "rmdir()".

I don't see the need to have all three operations. I would suggest to mark "deleteAll()" and "rmdir()" as depreciated for OC7 and remove them for OC8. Or did I miss something? Opinions?

cc @icewind1991 @DeepDiver1975 @PVince81 @karlitschek  @craigpg

**Comment by butonic** [comment]
I also just stumbled over the Storage tests for unlink and delete:
```php
	public function testRecursiveRmdir() {
		$this->instance->mkdir('folder');
		$this->instance->mkdir('folder/bar');
		$this->wait();
		$this->instance->file_put_contents('folder/asd.txt', 'foobar');
		$this->instance->file_put_contents('folder/bar/foo.txt', 'asd');
		$this->assertTrue($this->instance->rmdir('folder'));
		$this->wait();
		$this->assertFalse($this->instance->file_exists('folder/asd.txt'));
		$this->assertFalse($this->instance->file_exists('folder/bar/foo.txt'));
		$this->assertFalse($this->instance->file_exists('folder/bar'));
		$this->assertFalse($this->instance->file_exists('folder'));
	}

	public function testRecursiveUnlink() {
		$this->instance->mkdir('folder');
		$this->instance->mkdir('folder/bar');
		$this->instance->file_put_contents('folder/asd.txt', 'foobar');
		$this->instance->file_put_contents('folder/bar/foo.txt', 'asd');
		$this->assertTrue($this->instance->unlink('folder'));
		$this->wait();
		$this->assertFalse($this->instance->file_exists('folder/asd.txt'));
		$this->assertFalse($this->instance->file_exists('folder/bar/foo.txt'));
		$this->assertFalse($this->instance->file_exists('folder/bar'));
		$this->assertFalse($this->instance->file_exists('folder'));
	}
```

In contrast to php we seem to have added functionality to unlink until it could do the same as rmdir. I agree with @schiesbn on reducing this redundancy. I would however make the methods more php like, since we reference the php doc:
*`unlink` deletes single files,
* `rmdir` deletes empty directories
* rename `deleteAll` to `rrmdir` to have the recursive delete.

**Comment by PVince81** [comment]
Yeah, would be cool to get rid of all these different options and points of entry...

**Comment by PVince81** [comment]
We need a new simplified storage API anyway as discussed with @butonic.

@butonic please link to ticket with our discussions from last time once raised
