### ISSUE TITLE
File is being uploaded twice

### ISSUE THREAD

**Issue by Thurion** [owncloud/core#8664]
When someone uses the browser to upload a file which already exists the file is being uploaded and a dialog pops up to ask what to do. If the user chooses to overwrite the file, it is uploaded again (upload file -> ask user -> upload file). This can be annoying when dealing with big files or a slow internet connection.

A few information about the server:
Debian 
ownCloud 6.0.3
PHP Version 5.4.4-14+deb7u9
Apache 2.2.22

**Comment by DeepDiver1975** [comment]
need to be addresses in 8.2

> @DeepDiver1975 how will it be fixed ? I'm not aware of any good solution yet.

we will overhault that dialog handling as soon as we move to webdav. We basically can perform the conflict resolution on the client side by getting meta information about the existing file using PROPFIND

**Comment by bboule** [comment]
@CaptionF please note your issue is now being tracked here... looks like this is 8.2 please advise as to priority against your user expectations

**Comment by MorrisJobke** [comment]
> @CaptionF please note your issue is now being tracked here... looks like this is 8.2 please advise as to priority against your user expectations

The problem with this ticket is, that there is no really way to bring this into older versions. :(

**Comment by PVince81** [comment]
I guess we could still do https://github.com/owncloud/core/issues/8664#issuecomment-44663643 as a quickfix...

**Comment by CaptionF** [comment]
@cmonteroluque this has been communicated as been fixed with 8.2 and we should stick to this.

**Comment by PVince81** [comment]
The only case where it will still have to reupload is when someone is concurrently uploading the same file into the folder, thus creating a duplicate before the list has been refreshed. The latter is a more rare case.

The most common case is when the file is already in the list, visible, and someone (sometimes deliberately) overwrites existing files. This can be covered by uncommenting and finishing https://github.com/owncloud/core/issues/8664#issuecomment-44663643 and should do short term.

**Comment by cmonteroluque** [comment]
@CaptionF is the exception listed by @PVince81 acceptable? @PVince81 would you finish this one?

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/19417

**Comment by PVince81** [comment]
Note: the fix only pre-checks the currently visible list before attempting to upload files.

**Comment by CaptionF** [comment]
@PVince81 Thanks. @MorrisJobke please ensure, it gets reviewed and included in 8.2. Thanks a lot!

**Comment by MorrisJobke** [comment]
> @PVince81 Thanks. @MorrisJobke please ensure, it gets reviewed and included in 8.2. Thanks a lot!

Already in.
