### ISSUE TITLE
Long folder names are corrupted after sync and sync is not possible afterwards

### ISSUE THREAD

**Issue by JamborJan** [owncloud/core#8668]
Mac OS X (and also other OS) support long file and folder names. In OwnCloud seems to be an issue when these names are longer than 249 characters. This is a very high limit but when there is an folder with a longer name the sync process tries to upload the folder and creates a corrupted folder in OwnCloud. The result is that the sync process get’s stuccoed and brings a not readable message (the text is so long that it cannot be displayed but it is the folder name).

![owncloud error](https://cloud.githubusercontent.com/assets/7508960/3051100/4da21ddc-e186-11e3-8728-0752279859c8.png)

When logged in as administrator you see the following in the log:

```
Sabre_DAV_Exception_NotFound: File with name Shared/Folder/SubFolder/SubSubFolder/SubSubSubFolder/FolderWithMoreThan249CharactersButOnly249Displayed could not be located
```

The folders cannot be removed or renamed in OwnCloud. The only solution is to delete the parent folder.

The expected behavior would be, that OwnCloud accepts the file and folder name limitation from the supported OS.

**Comment by enoch85** [comment]
@JamborJan Is this still an issue?

**Comment by DeepDiver1975** [comment]
Might be fixed with upcoming 8.1 where we check for max filename length.

**Comment by JamborJan** [comment]
Hi guys,

Still nearly the same issue.

I have created a folder with 256 characters which is the maximum on OS X.
There is an error reported on syncing.
The folder is created anyway in owncloud.
Folder cannot be opened (the web UI always switches to the welcome screen)
But I somehow now can delete the folder directly which was not possible before.

Hope that helps.

**Comment by PVince81** [comment]
Have you tried with 8.1.0 ? Or was your last comment about that version ?

**Comment by JamborJan** [comment]
Hi guys, unfortunately I am not using ownCloud at the moment so I have no chance to test it right away. I have a upcpmming project where ownCloud might be part of the scope and I will include tests for this issue there. Thanks for the feedback!

**Comment by DeepDiver1975** [comment]
please reopen if you encounter issues in the future - THX
