### ISSUE TITLE
occ upgrade -  ownCloud is already latest version

### ISSUE THREAD

**Issue by hostingnuggets** [owncloud/core#8693]
I would like to upgrade my ownCloud 6.0.2 to 6.0.3 using the occ command line. For that purpose I ran the following command in my owncloud directory:

sudo -u www-data php occ upgrade 

But it does not work as I get the following message:

ownCloud is already latest version

Is this a known bug or am I missing something?

**Comment by DeepDiver1975** [comment]
duplicate https://github.com/owncloud/core/issues/14864
