### ISSUE TITLE
IMAP authentication

### ISSUE THREAD

**Issue by muecke77** [owncloud/core#8706]
### Steps to reproduce
1. Enable IMAP authentication only
2. login with an email address all lower case and add some files
3. logoff and logon again with the same address but one capital letter

### Expected behaviour
All files should visaible like login with all lower case address

### Actual behaviour
Fresh account will be created including a seperate directory on the server

### Server configuration
**Operating system**: Debian Wheezy

**Web server:**Apache 2.2.22

**Database:**Mysql 5.5

**PHP version:**5.4.4

**ownCloud version:** (see ownCloud admin page): 6.0.3

**Updated from an older ownCloud or fresh install:** Fresh install

**List of activated apps:**
Activity
Bookmarks
Calendar
Contacts
Deleted Files
Documents
Encryption
External User Support
First Run Wizard
Full Text Search
PDF Viewer
Pictures
Shared Files
Tasks
Text Editor
Updates
Version
Video Viewer
App Framework
News

**The content of config/config.php:**
<?php
$CONFIG = array (
   array (
    0 => 'cloud.yyy.net',
  ),
  'datadirectory' => '/opt/qcloud/',
  'dbtype' => 'mysql',
  'version' => '6.0.3.1',
  'dbname' => 'qcloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'qcloud',
  'log_authfailip' => true,
  'logtimezone' => 'Europe/Vienna',
  'installed' => true,
  'forcessl' => true,
  'ldapIgnoreNamingRules' => false,
  'mail_smtpmode' => 'php',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => 25,
  'mail_smtptimeout' => 10,
  'mail_smtpsecure' => '',
  'mail_smtpauth' => false,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'loglevel' => '3',
  'mail_domain' => ‚yyy.net',
  'mail_smtpdebug' => true,
  'maxZipInputSize' => 1073741824,
  'allowZipDownload' => true,
  'theme' => '',
  'maintenance' => false,
  'user_backends' =>
  array (
    0 =>
    array (
      'class' => 'OC_User_IMAP',
      'arguments' =>
      array (
        0 => '{imap.yyy.net:993/imap/ssl}',
      ),
    ),
  ),
);

**Are you using external storage, if yes which one: No

**Are you using encryption:** yes

### Client configuration
**Browser:**
Any browser
**Operating system:**
Windows, MAC OS, IOS

**Comment by DeepDiver1975** [comment]
refs #10102

**Comment by DeepDiver1975** [comment]
close as duplicate
