### ISSUE TITLE
Drag file to sidebar

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#8717]
When dragging a file to the sidebar:
1) Drag to "All files" will move the file into the root
2) Drag to "Deleted files" will delete the file

Ideally I think it would make sense to have a more advanced gesture: hold over "All files" that will switch the view to root, then drag onto the file list. (combine this with hold over folders).

But as a first step, being able to drag to the sidebar would already be an improvement.

Note that this will require cleaning up the currently very ugly drag and drop code first to make it easier to extend.

CC @owncloud/designers

**Comment by jancborchardt** [comment]
Also, dragging over Favorites could favorite the file.

Anyone of you @owncloud/designers interested in implementing this? :)
