### ISSUE TITLE
Provide "requiremin" and "requiremax" fields for apps

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#8726]
- [x] Add "requiremin" and "requiremax" version fields for apps
- [x] Fix compatibility check to use this range
- [x] "require" is interpreted as "requiremin"
- [x] Update docs (https://github.com/owncloud/documentation/issues/386)
- [ ] Notify mailing list
- [x] Update apps
- [x] Update apps.owncloud.com with both fields

**Comment by LukasReschke** [comment]
Seems to be documented now and apps are adjusted. Closing for now.
