### ISSUE TITLE
Import data from different cloud services

### ISSUE THREAD

**Issue by vbsampath** [owncloud/core#8752]
My context is for a single user who is using owncloud just to make sure he is in control of his data.
Well till the advent of owncloud he must have been using some sort of cloud service for his needs like google, apple, microsoft etc.,. 
Most of the people are only concerned with ease of use and using owncloud is not easy as apple or google I guess. Why don't we make this easy for new users. Apart from new users there are established users with their data locked up in third party corporate servers and they cant get out easily. In this regard if we make efforts to get their data back then the usage of owncloud will be drastically improved.

These might be some services which we use and store our data on their services

Contacts - google, icloud, nokia sync, outlook
Tasks - google, icloud, nokia sync, outlook
Pictures - Picasa, icloud
Files - Google Drive, icloud, dropbox, onedrive etc
Notes - Evernote, Keep, Drive, Dropbox, icloud, nokia sync, one note, outlook ...
Calendar - outlook, google calendar, icloud etc.,
Passwords - lastpass, keepassx etc.,
Bookmarks - Firefox Sync, Xmarks, icloud, chrome sync etc.,
......
Like this we have many cloud services where we have our data in different formats.
The data which can be retrieved in standard formats are contacts, calendars and for remaining things we need to put a lot of effort in getting them into owncloud or sometimes we can forget some of the data.

The main point is how does a user use owncloud when his data is stuck somewhere and he has to start new in owncloud. We need to make effort in getting all those stuck data so that an average user gets interest in using owncloud.

**Comment by hodyroff** [comment]
Should be a seperate app. We have this somewhat for files. Mount external storage and move over ...
