### ISSUE TITLE
Calling CalDAV, CardDAV or News-API should trigger cron.php

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/core#8761]
### Steps to reproduce
1. Select "Ajax" as Cron
![2014-05-28_10h14_29](https://cloud.githubusercontent.com/assets/4741199/3102026/1a4c590c-e640-11e3-85b5-0594c1ff5fd0.jpg)
2. Sync your Contacts or Calendar with DAVDroid (or another software). **or** sync your News with the Android News-App

### Expected behaviour
The Sync-Requests should trigger the cron.php, so the News-App should always display current and actual news.

### Actual behaviour
No new news are shown, so I have to manually press F5 in the Webinterface to force triggering Cron and fetching new news from the rss-feeds.

### Server configuration
**Operating system**: Debian

**Web server:** Apache

**Database:** MySQL

**PHP version:** Any

**ownCloud version:** 6.0.3

**Updated from an older ownCloud or fresh install:** updated from 6.0.1

**List of activated apps:** News-App and all Standard-Apps

**The content of config/config.php:** err.... does not matter?

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:** Any

**Operating system:** Any

#### Web server error log
Logs are not available since i am on a share hoster

**Comment by DeepDiver1975** [comment]
We should not put the burden of background processing onto any dav operation -> close
