### ISSUE TITLE
Better version control + check-in / check out function.

### ISSUE THREAD

**Issue by NobodyAnybody** [owncloud/core#8764]
OwnCloud is a great solution for your private or small business data-control but I do miss two functions.

The version control  is lacking. To be honest I am not even sure how it works (it should be be intuitive). When I edit a file it should save the old version as an old version but it does not. When I upload a file with the same name it should also give me the question if it's a newer version and if so the older version can be put in as older version in stead of just adding in a new copy (makes sense right?)..

Even if I upload a file with a new name I should be able to say it's a new version of an already existing file (because also a name change can be an update to an older file).

Then the whole version control starts to make more sense and becomes useful. There should also be some control as to when older files / versions get deleted. I did read the part about version-control in the manual but it's extreme vague. 
“For the first 10 seconds ownCloud keeps one version every 2 seconds“
To me that sentence makes no sense at all but as I don't  get version-control to work it might be that the version control works completely different from how I see version control.

In addition to that I do work one the same (video) files as other people and then a checkout / check-in option would be great. It does not have to be much more then a bool that you can turn on or of to just inform another person somebody is using it.

You could also show who checked it out but that does not work if multiple people use the same account (as what is the case with me)

I put this check-in / -out function in the same 'issue' as the version-control because it can have some functions working together with version-control. Whenever downloading an item you can get the question “do you want to check this file out” and then when uploading it and attaching it to an existing file as being a newer version it can ask you if you want to check it back in. In version history it's then also easy to see what user made what version (and when).

This should be a great addition to OwnCloud in my opinion.

**Comment by MorrisJobke** [comment]
This is nothing we want to implement in core. Feel free to open this app proposal in the apps repo: https://github.com/owncloud/apps

I will close this here
