### ISSUE TITLE
occ / console.php app:disable deletes app instead of disabling it

### ISSUE THREAD

**Issue by EmPeWe** [owncloud/core#8790]
### Steps to reproduce
1. $ occ app:enable app-id
2. $ occ app:disable app-id

### Expected behaviour
The app should be disabled within oc_appconfig

### Actual behaviour
The app directory will be deleted completely

### Server configuration
**ownCloud version:** 6.0.3.1

### Proposal
additional command app:delete could be implemented

**Comment by Xenopathic** [comment]
This behaviour was changed with #8808, which was released as part of oC 7.0.0. No `app:delete` functionality is available, but from the CLI it is expected that `rm -rf` works as normal.
