### ISSUE TITLE
Add size and mtime columns to the sharing overview pages

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#8792]
FYI @owncloud/designers 

@schiesbn please have a look at extending the OCS API to also return the FileInfo of the shared files, possibly only when a flag "includeFileInfo=true" was passed.

Thanks.

**Comment by jancborchardt** [comment]
So, currently we have a different column there, when you shared it.

Should the view not be the exact same as in the »All files« view? What do you think @owncloud/designers?

**Comment by MorrisJobke** [comment]
Also see https://github.com/owncloud/core/pull/19513

**Comment by jancborchardt** [comment]
@MorrisJobke yep, thanks for linking that! What do you actually personally think about the question? Have the columns for »Share date / Expiration date« or the standard »Size / Modified date«?

**Comment by MorrisJobke** [comment]
> Have the columns for »Share date / Expiration date« or the standard »Size / Modified date«?

For that view it makes sense to have the more related columns.

**Comment by PVince81** [comment]
Also note that we need the columns to be able to show the same info in the sidebar.
