### ISSUE TITLE
Request for more options to CLI files:scan

### ISSUE THREAD

**Issue by timreeves** [owncloud/core#8794]
Hi all,
currently some issues with auto (re)scan of mounted storage (not happening) are forcing me to use the CLI files:scan. Since it accepts hardly any options, I had to think out a plan involving a Pseudo-User, whose visible items are limited to those external local mountpoints that I need to manually scan. Otherwise I would be scanning my whole filespace, which is very large in comparison to the mountpoints which DO need a scan.

So here's my requests:
* A "quiet" option to suppress output (for cron jobs, just an exit code is enough)
* A further optional parameter limiting the scan to a particular directory of the user space.
* Or even better, a list of directories to be scanned :)

Cheers, Thanks!

**Comment by Xenopathic** [comment]
Fixed in #11892
