### ISSUE TITLE
Getting errors with WebDav sync against Keepass2Droid

### ISSUE THREAD

**Issue by JonTheNiceGuy** [owncloud/core#8818]
I have ownCloud 6.0.3 on my hosting server, and I'm using the Keepass2Droid Android application to synchronize my KeePass .kdbx file between my phone and laptop.

I've found that when I make an amendment to the kdbx file, I'm finding subsequent errors immediately both on the phone and laptop. On the server-end I'm seeing these errors:

{"app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'files\/Passwords\/Personal.kdbx.64B44D.tmp' is not readable !!!","level":0,"time":"2014-06-02T13:14:11+00:00"}
{"app":"webdav","message":"Sabre_DAV_Exception_NotFound: File with name Passwords\/Personal.kdbx.64B44D.tmp could not be located","level":4,"time":"2014-06-02T13:14:11+00:00"}
{"app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files\/Passwords' !!! \ncache: Array\n(\n    [fileid] => 24311\n    [storage] => local::\/var\/www\/oc.url\/data\/jontheniceguy\/\n    [path] => files\/Passwords\n    [parent] => 9\n    [name] => Passwords\n    [mimetype] => httpd\/unix-directory\n    [mimepart] => httpd\n    [size] => 258456\n    [mtime] => 1401714332\n    [storage_mtime] => 1401714332\n    [encrypted] => \n    [unencrypted_size] => 193244\n    [etag] => 538c769c7e783\n)\n \ndata: Array\n(\n    [mimetype] => httpd\/unix-directory\n    [mtime] => 1401714851\n    [size] => -1\n    [etag] => 538c78a3e002f\n    [storage_mtime] => 1401714851\n)\n","level":0,"time":"2014-06-02T13:14:11+00:00"}
{"app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'files\/Passwords\/Personal.kdbx.64B44D.tmp' is not readable !!!","level":0,"time":"2014-06-02T13:14:11+00:00"}
{"app":"OC\\Files\\Cache\\Scanner","message":"!!! No reuse of etag for 'files_versions\/Passwords' !!! \ncache: Array\n(\n    [fileid] => 24314\n    [storage] => local::\/var\/www\/oc.url\/data\/jontheniceguy\/\n    [path] => files_versions\/Passwords\n    [parent] => 112\n    [name] => Passwords\n    [mimetype] => httpd\/unix-directory\n    [mimepart] => httpd\n    [size] => 0\n    [mtime] => 1401714332\n    [storage_mtime] => 1401714332\n    [encrypted] => \n    [unencrypted_size] => 0\n    [etag] => 538c769c449e7\n)\n \ndata: Array\n(\n    [mimetype] => httpd\/unix-directory\n    [mtime] => 1401714852\n    [size] => -1\n    [etag] => 538c78a4d45e1\n    [storage_mtime] => 1401714852\n)\n","level":0,"time":"2014-06-02T13:14:12+00:00"}
{"app":"OC\\Files\\Cache\\Scanner","message":"!!! Path 'files\/Passwords\/Personal.kdbx' is not readable !!!","level":0,"time":"2014-06-02T13:14:12+00:00"}

Even moving the file out of the ownCloud sync and putting it back in again doesn't resolve the issue - actually, what I've had to do is to copy the file in the FS, then delete the original file and rename the copied file to replace it.

The error I've been receiving is a 409 error on Keepass2Droid and when trying to access the file via my web browser, I get redirected to http://oc.url/apps/files_encryption/files/error.php?p=0&errorCode=3

I'd like to get some help to identify whether this is an issue with Keepass2Droid or in ownCloud, but without another webdav service, I don't know where else to check.

One thing that I think might be working against me is that in /var/www/oc.url/data/ I have two directories: jontheniceguy and JonTheNiceGuy - a cased and uncased version of the names.

**Comment by PVince81** [comment]
Note: I noticed that a WebDAV MOVE that would overwrite a file internally generates a delete operation.

Do you guys still observe this on 7.0.5 or 8.0.2 ?

**Comment by johnnyzz** [comment]
Hi, I'm on 8.1.0.8 (server linux), 2.0.1 (client linux), and it works well. (sync conflict appears after upgrade, but only for the first time, then it is ok)

**Comment by PVince81** [comment]
@JonTheNiceGuy can you try again with 8.1.3 ?
From what I remember there were some header-related issues with some third party webdav clients that should be fixed now.

Please reopen if you still observe the issue in this version

**Comment by JonTheNiceGuy** [comment]
Sorry for the delay. Life etc. Yes, this seems to be resolved now. Thanks for digging into it!
