### ISSUE TITLE
"Wrong Password" when successfully changing password

### ISSUE THREAD

**Issue by steveydevey** [owncloud/core#8826]
I've set up a pile of new users, and they each get the same error message when changing their password. This happens the first, and any subsequent attempt it seems. Going into the personal settings, and using the two password fields to change a password gives me these results:

Password
Your password was changed
Wrong password

It DOES change the password, but errors every time.

This is oc 6.0.3, by the way.

**Comment by PVince81** [comment]
This seems to work fine in 7.0.5, probably fixed recently.
