### ISSUE TITLE
Files sidebar: Entry for file conflicts

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#8835]
(An idea @icewind1991 had:)

In the Files sidebar there could be an entry called »File conflicts«. That should of course only show if there _are_ conflicts.

That way people could quickly see that there are problems, and directly fix them.

@owncloud/designers @karlitschek

**Comment by PVince81** [comment]
Linking with "upload conflict file" from client: https://github.com/owncloud/client/issues/4557

And diff view: https://github.com/owncloud/core/issues/4056
