### ISSUE TITLE
[All] Translation Errors and Typos

### ISSUE THREAD

**Issue by wakeup** [owncloud/core#8904]
Please comment here to help us fix translation errors and typos by providing the context.

Thanks.

**Comment by DeepDiver1975** [comment]
@enoch85 can I ask you to report this in the issue tracker of the client? https://github.com/owncloud/client - THX

**Comment by DeepDiver1975** [comment]
I'm closing this issue now - please open new issues as soon as translations errors occur again - many thanks to all for you for taking care of these issues!
