### ISSUE TITLE
Cannot remove the groups in new user management

### ISSUE THREAD

**Issue by vgezer** [owncloud/core#8993]
Latest git,

Reproduce with:

1. Create a new group
2. Try to remove newly created group by clicking on it.

Expected:

1 or 2 weeks ago, I was able to see the trash icon to remove the group.

**Comment by DeepDiver1975** [comment]
@MorrisJobke @LukasReschke can you please reevaluate this issue with the recent changes applied to master/OC8. In case this is still an issue we move this to OC8.1 and implement this with the remaining changes. THX

**Comment by MorrisJobke** [comment]
@DeepDiver1975 It's already on my todo list for verification ;)

**Comment by MorrisJobke** [comment]
Removal isn't supported in current master -> move this to 8.1

**Comment by nickvergessen** [comment]
Can not reproduce anymore, seems to be fixed in master
