### ISSUE TITLE
issue with german umlauts in linux with desktop client

### ISSUE THREAD

**Issue by sknohsalla** [owncloud/core#9009]
http://storage9.static.itmages.com/i/14/0612/h_1402580388_7910081_44c8911181.png

Hi,
when sharing files containing german umlauts in file name, the files will be synced locally by linux 1.6.0. client properly, modifying these files ends up in creating asci symbols in files or break sync.

Underlaying OS: Debian Wheezy 7.5 64bit

This effect does not occur for actual Windows or Mac client.
Folder names may contain umlauts with no issue occuring under linux client.

is this issue already known?

**Comment by sknohsalla** [comment]
@karlitschek, did try with :
- Debian 7.7 latest 64bit 
- OwnCloud 7.04 & linux client 1.70

still same issue even UTF-8 is set explicitly:

LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

Working only if adding file with umlauts directly via https.
Linux client is downloading this file as expected.

Upload ends up in log:
�����.txt - No such file or directory

If u need further information, please let me know.

**Comment by DeepDiver1975** [comment]
@danimo @dragotin shall we move this issue over to the client tracker? Not really much we can do here on the server side - THX

**Comment by dragotin** [comment]
Well, sounds like the server is still running on en_US and **not** UTF8 according to the log above, see *server locale*. @sknohsalla could you double check that both client and server run in a proper UTF8 environment? Thanks.

**Comment by dragotin** [comment]
Also, when you changed the locale on either server or client, the journal database might be screwed as it was written with the non utf8 locale eventually.

**Comment by danimo** [comment]
@dragotin `en_US` is the collation. Afaik, if the 'utf-8' is missing, and nothing else is specified, utf-8 should be implied on all Linux distros that are not 10 years old.

**Comment by sknohsalla** [comment]
on server
Debian 7.7 64bit

dpkg-reconfigure locales 
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
on client
Debian 7.7 64bit
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE=C
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

@danimo , yes UTF-8 wasn't missing, but not set as default.
![selection_032](https://cloud.githubusercontent.com/assets/7531646/5665083/fa949102-9755-11e4-8252-28ac9e52b9c1.png)

**Comment by sknohsalla** [comment]
So umlauts will just be cropped, eg vü3rdtestfile will turn into v3rdtestfile on linux client.

**Comment by dragotin** [comment]
For the client, you can simply delete the files .csync_journal.db* while the client is stopped. It will recreate the journal. But I am not sure if that helps. You should not do that to the server db content btw.

**Comment by dronus** [comment]
Happens for me too, under weird circumstances. Creating a directory 'täst': works and is synched to server. Also appears on web frontend. Creating a file 'täst.txt' inside 'täst': Does not sync, client shows 'File not found'. Checking the folder in web frontend again, it is named 'tst'.  So in fact, the sync process does maim the folder name after it was once synced successfully. 
This looks arkward, as changing the folders contents seem to trigger the erratic rename.

**Comment by karlitschek** [comment]
should be fixed. utf-8 is a hard requirement now
