### ISSUE TITLE
Enhancement Request: Allow Sharing to Contacts

### ISSUE THREAD

**Issue by DaremoTono** [owncloud/core#9013]
I believe it would be a good enhancement to allow sharing links to persons in your contacts, by contact name in a drop box.  similar to sharing between user accounts.

Even though emails used for sharing are kept and can be conveniently re-used, it can still lead to confusion.  By just looking at email addresses you may not remember which one is for who as, many times, email addresses do not reflect the person's true name or two addresses may be similar.    By using contacts all ambiguity is removed.

Thank you for your consideration

**Comment by jancborchardt** [comment]
@LEDfan I assume this was fixed by your pull request. :)
