### ISSUE TITLE
Setting to turn off mailing

### ISSUE THREAD

**Issue by monreal** [owncloud/core#9021]
### Expected behaviour

If I do not want to get mail I expect to have a setting to turn mailing off. If turned off, I would also expect the mail settings to be hidden or grayed out.
### Actual behaviour

There are two new settings about mail in OC7 (Mail templates, Email Server) but there is no preference to turn mailing off.
### Server configuration

**Operating system**: CentOS 6.5
**Web server:** nginx 1.6
**Database:** MySQL 5.5
**PHP version:** 5.4.x
**ownCloud version:** 7 alpha 1

**Comment by hodyroff** [comment]
Why should the ownCloud Server not provide any mail at all? Can you describe the use case?
