### ISSUE TITLE
Uploading dot-files & unreadable files. Renaming plugin?

### ISSUE THREAD

**Issue by webbakery** [owncloud/core#9034]
Yes, I found a lot of threads with the same issue, I'm aware. But mine is a bit more than an issue.
Because I'm working with a lot of website's (which have .htaccess file), I want to backup them with owncloud wich works just fine except with these dot-files. I understand the issue that uploading these file's inside the web root isn't best practice.

HOWEVER, I think it would be nice to have some kind of solution. For me, a solution would be that dot-files are automatically renamed without the dot. This way I'm certainly not losing any files and it doesn't change anything to the web-server.

Anyone who can create a plugin for this? Or is it possible that I create one myself? I'm just not that familiar yet in OwnCloud. Any help is welcome!

+ It would also be nice to automatically rename files with special chars (just strip them out). I have a couple of files here which have a " / " in them, which is perfectly possible to work with on OS X but not an a web-server (logically), just striping them out would be fine anyway.

**Comment by jancborchardt** [comment]
We’re most probably not going to do rename magic like this. Closing for now.
