### ISSUE TITLE
Do not abuse session storage as a cache

### ISSUE THREAD

**Issue by bantu** [owncloud/core#9079]
This leads to unnecessary duplication of data and to all sorts of bugs due to "old session data".

Example
https://github.com/owncloud/core/blob/master@{2014-06-18}/lib/private/util.php#L196

Solution
Use a proper application-wide cache or the database instead.

**Comment by PVince81** [comment]
seems we stopped storing version into session already.

I'm not aware of any other session abuse as we've been careful to never use the session for anything else than just user id.
