### ISSUE TITLE
Consistently implement Dependency Injection

### ISSUE THREAD

**Issue by bantu** [owncloud/core#9082]
A large number of bugs can be avoided by making dependencies explicit by using the Dependency Injection paradigm. Class dependencies are received via the constructor, method dependencies are passed as method parameters.

See
http://fabien.potencier.org/article/11/what-is-dependency-injection
http://en.wikipedia.org/wiki/Dependency_injection#Constructor_injection

### Examples for lack of dependency injection
https://github.com/owncloud/core/blob/master/lib/private/files/cache/cache.php#L77
(database connection object)
https://github.com/owncloud/core/blob/master/lib/private/files/cache/storage.php#L36
(database connection object, this is throughout the software)
https://github.com/owncloud/core/blob/master/lib/private/allconfig.php#L35 
(should depend on config object)
...

### Implications

* Global variables need to go away. Static class properties are global variables with a fancy name.
Example: https://github.com/owncloud/core/blob/master/lib/base.php#L34

* Static methods need to go away. There should be objects that can be passed around as dependencies.
Example: https://github.com/owncloud/core/blob/master/lib/private/util.php

### Benefits

* No unexpected side-effects.
* Easier unit tests: Usually: Mock all dependencies, then create an instance of the class under test.
* ...

**Comment by Xenopathic** [comment]
Well, we have the AppFramework which heavily makes use of DI, and most of oC core makes use of it. I think it's time to close this.
