### ISSUE TITLE
Move to twig for template rendering

### ISSUE THREAD

**Issue by butonic** [owncloud/core#9091]
Currently we render base templates with php and a combination of `p()`, `print_unescaped()` and translation calls. That works quite well, but still allows mixing in any php code into templates that can lead to all kinds of security issues because a simple print or echo is used. Furthermore, we now have an [app](https://github.com/owncloud/templateeditor) that allows administrators to customize the email templates from within ownCloud. Currently the three templates are hardcoded, but in the future a well known approach to templates should be taken to allow users to customize the mails or other aspects of their owncloud appearance. An example may be personalized emails or public share pages without the risk of end users writing php that wipes all data.

[twig](http://twig.sensiolabs.org/) together with the [i18n](http://twig.sensiolabs.org/doc/extensions/i18n.html) extension should meet our requirements and is available via composer.

To be done:
- [ ] add twig to 3rdparty via composer
- [ ] implement twig based templates in oc core
- [ ] add extraction of translatable strings for transifex. We can look at wallabag to get an idea of [how to do that](https://github.com/mariroz/wallabag/blob/cbcae4037c02cd6c1ce7c373c6dae390565b7c51/TRANSLATION.md).
- [ ] migrate templates to twig

**Comment by jancborchardt** [comment]
So what’s the call on this?

**Comment by DeepDiver1975** [comment]
> So what’s the call on this?

some day ....

**Comment by DeepDiver1975** [comment]
From my pov this is no longer an open issue

**Comment by rakekniven** [comment]
Does that mean moving to twig will not be done? Does ownCloud use another template system?

**Comment by oparoz** [comment]
> From my pov this is no longer an open issue

Why? 
Handlebar is fine for partial views, but PHP is faster at rendering the main templates with the app's scaffolding (there is no need to make extra ajax requests to load them).
On the other hand, if the ultimate goal is to be a pure RESTful API, without any shared technology and code with apps (OCP, templates, JS), then it's good-bye integrated apps/app store (no point in being integrated if we have to build everything from scratch). The only interesting projects will be libs/extensions to make it possible to build exciting external apps.

**Comment by DeepDiver1975** [comment]
> Does that mean moving to twig will not be done? Does ownCloud use another template system?

we have a working templating mechanism in ownCloud since it's very first version.
Form a pure technical POV twig might be nicer - but meanwhile I see no need to go into this direction.

**Comment by karlitschek** [comment]
i agree with @deepdiver1975 Let's keep it simple for now.
