### ISSUE TITLE
Make it possible to mount remote shares with self signed certs

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#9096]
When trying to mount a remote share (server to server sharing) that is on a remote server with HTTPS that has a self-signed / invalid certificate, mounting fails.

We need to find a way to make this possible, or at least to show a fat warning to the user that they can override.

To be discussed @LukasReschke @icewind1991 @schiesbn

**Comment by icewind1991** [comment]
> or close it and open a new ticket for the new feature.

Will make a new issue

**Comment by icewind1991** [comment]
#13175
