### ISSUE TITLE
Show that the encryption recovery key password is set (usability)

### ISSUE THREAD

**Issue by DanielRuf** [owncloud/core#9134]
It might be better for the user to show, that it is set. Currently we just get a blank field after loading the page and the password is set. Is it not suggested to show it? But why not just dots or a text that say, that it is already set?

**Comment by PVince81** [comment]
In encryption 2.0, the field is now shown with the label "Disable recovery" which is an indirect indication that recovery key was enabled. CC @schiesbn 

Closing
