### ISSUE TITLE
No File Size shown for files bigger than 2 GB with FTP and "External storage support" (Even on 64bit Server)

### ISSUE THREAD

**Issue by CM000n** [owncloud/core#9144]
Hi all,

I've installed Owncloud 6.0.3 a few weeks ago on my webspace @ http://alfahosting.de/
I have the Multi L package with the following specifications:

Apache Version: 2.x
PHP-Version: 5.4.24
MySQL-Version:5.5.31

I use Owncloud in combination with the external Storage Support App and added some FTP Folders from my NAS at home with TV Recordings in it.

Everything works smooth so far, but there are no filesize shown in Owncloud for Files that are bigger than 2 GB.
It seems related to the external storage support in combination with FTP because owncloud can get the size of folders when they are bigger than 2 GB.
It just don't works with single files that are bigger than 2 GB.
But I can get access to that files, when I try to reach them directly via FTP.

![4xj926oh](https://cloud.githubusercontent.com/assets/7945681/3352017/88035292-fa2d-11e3-8a81-182394ef6b0d.png)

Issue template File: http://cloud.hoerrle.eu/public.php?service=files&t=c7c4d30ff60dda4eb20f647eb56bf897

(Sorry, but it was to big for posting it inside this issue reporting)

**Comment by PVince81** [comment]
You could also try with this new experimental fix that uses another library for FTP: https://github.com/owncloud/core/pull/14551

**Comment by PVince81** [comment]
Possibly related https://github.com/owncloud/core/issues/14100

**Comment by PVince81** [comment]
Is this still an issue in OC 8.2.2 ?

**Comment by Nibbels** [comment]
I have this issue. 
![version](https://cloud.githubusercontent.com/assets/3265671/14067356/f9ea1670-f463-11e5-9895-58de3bdcff5d.png)
![ftp](https://cloud.githubusercontent.com/assets/3265671/14067355/f9e9bcac-f463-11e5-861d-f8d31c69e2b5.png)
![version_app](https://cloud.githubusercontent.com/assets/3265671/14067359/f9eafafe-f463-11e5-9a43-ed65ffea399d.png)
![filesinodin](https://cloud.githubusercontent.com/assets/3265671/14067357/f9eb312c-f463-11e5-948c-52bc95dd95b1.png)
![files_plesk](https://cloud.githubusercontent.com/assets/3265671/14067358/f9eb196c-f463-11e5-9ea3-734ce3fa7a80.png)
![files_lftp](https://cloud.githubusercontent.com/assets/3265671/14067360/f9ebb3c2-f463-11e5-8a0e-aa277c601604.png)
![php](https://cloud.githubusercontent.com/assets/3265671/14067361/f9ff6e80-f463-11e5-9954-d40fa1d554b2.png)

Today I wanted to test this feature but then I stumbled upon this bug with wrong filesizes. But this is not the only issue I saw.

When I tried to delete Files within my newly added FTP-Space Owncloud told me that it is not able to delete several files. And when seemed to successfully delete some Folders they reappeared after a reload.

I was able to 
- create some folder, 
- to delete some of the files (smaller ones) and to 
- drag and drop some files to other directorys.

Then I deleted those "not able to delete"-files within lftp on my ssh command line. But owncloud still showed them to me.

Then I deleted everything in ownclouds "deleted files" - but those not existing files didnot vanish in my ownclouds ftp-space.

Then I deleted the FTP-Space within Ownclouds Settings.
When I added the FTP-Space again, those files vanished as they should have vanished earlier.

It seemed that Owncloud read in the directory etc. again. But the size still stayed at < 1GB

So I calculated the file-sizes:

File1: 
13842207916 - 3 * 2^32 = 957306028
(1MB = 1024B vs. 1MB = 1000B -> )
957306028 / 2^20 = 912,9 ~ 913MB
Owncloud thinks that the 13842207916 Byte size file is 913 MB.

File2:
13773517996 - 3 * 2^32 = 888616108
888616108 / 2^20 = 847,45MB ~ 847,5MB
Owncloud thinks that the 13773517996 Byte size file is 847,5MB

Does this help you?

**Comment by Nibbels** [comment]
Well I forgot to tell you things about my machine:

I have a Strato Server with Centos 7 and Plesk 12.4
It is a 64bit machine.

And this is the only thing that got me wondering when I rebooted the machine yesterday but I really really cannot know what this means or if this might have something to do with this behaviour:

![maybe](https://cloud.githubusercontent.com/assets/3265671/14067535/bec0872a-f466-11e5-8834-08de7763facf.png)

Because this is a hint to something that is maybe 32bit. But I did not think that php or owncloud or something other than my ftp server would use proftpd. And this is not the server to which I connect using owncloud! 
this is just a message I get when I type in "dmesg --ctime" after a reboot.

**Comment by hodyroff** [comment]
Still happening with 9.1? Can this be easily reproduced with standard setups?

**Comment by PVince81** [comment]
Please reopen if still reproducible on recent versions on a standard supported setup.

**Comment by cmonjeau** [comment]
Hello,

I'm running on owncloud 9.1.4 and I've this problem. Files > 2Gb are in a pending state size.

The main problem is the file is not downloadable:

> Bad Gateway
> 
> The proxy server received an invalid response from an upstream server.

**Comment by Nibbels** [comment]
My problem still persists, but I am running Nextcloud 11.0.2.
I did not try to fix this anymore since last year.
Nor did I reset the database or anything that would force a re-read (in case refreshing file-information does not happen automaticaly).
