### ISSUE TITLE
7.0 alpha 2 - [RC2] sharing doesn't work

### ISSUE THREAD

**Issue by MU7L3Y** [owncloud/core#9146]
### Steps to reproduce
1. Create a folder with files in it.
2. Create users to share with.
3. Share the folder.
4. Log in as one if the users shared that the folder was shared with.
5. No folder appears with the files. 'Shared with you' shows the folder but 'All files' doesn't and when clicking on the folder inside 'Shared with you' it doesn't show any files.

### Expected behaviour
When a folder is shared the users should see it and the files in it.

### Actual behaviour
The users don't see the shared folder or files. Folder is not listed in the 'All files'.

### Server configuration
**Operating system**: Linux shared hosting

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.4.27

**ownCloud version:** 7.0 alpha 2

**Updated from an older ownCloud or fresh install:** upgrade from 6.0.3 with data and config.php.

**List of activated apps:** The standard ones that come activated

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'occb8bd11dbe',
  'passwordsalt' => 'REMOVED',
  'trusted_domains' => 
  array (
    0 => 'mutleyproductions.com',
  ),
  'datadirectory' => '/home/mutleypr/public_html/cloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.0.1',
  'dbname' => 'mutleypr_db1',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'mutleypr_mutley',
  'dbpassword' => 'REMOVED',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'mutley',
  'mail_smtppassword' => 'REMOVED',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:** Chrome

**Operating system:** Win 7 64bit

#### ownCloud log (data/owncloud.log)
```
call_user_func() expects parameter 1 to be a valid callback, class '\OC\Files\Cache\BackgroundWatcher' not found at /home/mutleypr/public_html/cloud/lib/private/backgroundjob/legacy/regularjob.php#13
curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set at /home/mutleypr/public_html/cloud/3rdparty/sabre/dav/lib/Sabre/DAV/Client.php#466
```

**Comment by MorrisJobke** [comment]
@MU7L3Y As this is now a completely different issue you have. Can you please reopen a new ticket for that one and provide the information requested by the issue template https://github.com/owncloud/core/blob/master/issue_template.md

Thanks
