### ISSUE TITLE
Run database repair steps during update simulation

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#9151]
Currently, the database repair steps are run before and after an upgrade/migration.

The repair steps need to also be able to run during the migration simulation.

This means that they need to be able to work on the clone of the database tables.

**Comment by PVince81** [comment]
Is it now possible to set a global prefix for database tables ? @DeepDiver1975 @MorrisJobke 

If yes, then this could be done before running the update.php code to make sure the upgrade runs only on the simulated database/table.

This means that update.php would be called twice, once for the simulation with the prefix of simulated tables and once again with the real tables.

**Comment by MorrisJobke** [comment]
Yes. There was a doctrine method to set the prefix. See #12995

**Comment by PVince81** [comment]
upgrade simulation removed in 9.2, closing
