### ISSUE TITLE
Add remote share with "Add link" from the "New" menu

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#9155]
It should be possible to mount remote public shares by doing the following:
1. Click "New" in the files app
2. Pick "Add from URL"
3. Paste the public URL

@owncloud/designers

**Comment by PVince81** [comment]
"Add from link" was dropped as per https://github.com/owncloud/core/pull/14652

But this feature could still be useful and could be renamed to "Add remote share".

**Comment by jancborchardt** [comment]
This way of adding a share seems quite cumbersome and really inferior to just opening the link and entering the address of your ownCloud. Especially because the browser will remember the URL of your ownCloud in that input field.

**Comment by PVince81** [comment]
The "Add from link" feature has been removed due to security considerations.

And as @jancborchardt said it is easier to just open the link and click "add to ownCloud".
