### ISSUE TITLE
Introduce microevent library

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#9227]
Introduce this: https://github.com/jeromeetienne/microevent.js

Because currently we're just hijacking jQuery's DOM events to do stuff it wasn't designed for.

Having an event lib will make it possible to better sync events between objects (ex: register a new file actions should notify the file lists so they can redraw themselves)

**Comment by DeepDiver1975** [comment]
higher level js framework have their own machanism - we need to make sure they do not intercept -> backlog, let's grab it if we need it @PVince81

**Comment by PVince81** [comment]
Talked with @blizzz and we'd like to introduce MicroEvent for the right sidebar.
Goal is to be able to updte the FileInfo object and have the changes be automatically reflected in the FileList.

I think MicroEvent is a mixin, so it shouldn't interfere with other frameworks. Classes that want its functions need to explicitly use it as mixin.

**Comment by DeepDiver1975** [comment]
> Talked with @blizzz and we'd like to introduce MicroEvent for the right sidebar.

Well - give it a try

**Comment by blizzz** [comment]
Discussing with @PVince81 we would like to use Backbone.js which, next to an event system, also gives us Model and View base classes, which we would like to use for Sidebar stuff before reinventing wheels (which I already have partly in LDAP wizard). It enables/forces us to use a consistent coding pattern, instead of growing "Insellösungen".

**Comment by blizzz** [comment]
opinions? ^ @MorrisJobke @schiesbn @oparoz @rullzer @karlitschek 

Of course the introduction needs to be non-intrusive. It would not influence any current usage or app developer (we make sure to not intervene with possible provided backbone imports by apps), so contributors would not need to relearn anything.

**Comment by PVince81** [comment]
This came up when we noticed that @blizzz and I were using slightly different approaches for model/views. So we'd need to introduce base classes as a common ground. But then we'd need to maintain those classes and write the event functionality and other stuff ourselves, test it and maintain it... so why not just benefit from a library that already does that: Backbone JS.

**Comment by DeepDiver1975** [comment]
I like backbone :+1:

**Comment by oparoz** [comment]
:+1: for Backbone. What does @Raydiation think?

**Comment by Raydiation** [comment]
As long as it's loaded only for the files app it's a major improvement over the current state. Backbone is designed pretty well and if the people who work on it want to use it am all for it :)

**Comment by PVince81** [comment]
@Raydiation it will have to be loaded in core always because it will be required for some common code (the sharing dialog rewrite which resides in core). However it will use "noConflict" and be accessible under "OC.Backbone" to avoid conflict with other apps that might have backbone.
Hope it's ok.

**Comment by PVince81** [comment]
See the PR https://github.com/owncloud/core/issues/18091

**Comment by PVince81** [comment]
(always for now, hopefully one day with some requirejs-like library https://github.com/owncloud/core/issues/17169)

**Comment by blizzz** [comment]
Closed via https://github.com/owncloud/core/pull/18091
