### ISSUE TITLE
public sharing an encrypted file in 7.0b1 failed

### ISSUE THREAD

**Issue by MarvinFS** [owncloud/core#9238]
### Steps to reproduce
1. Enable encryption
2. Log on to user account and log off to complete key issuing process
3. Log on again and share any file (password protected or not - it doesn't matter) via "share link"

### Expected behaviour
1. Open link from a public location to download file
2. File should be downloaded

### Actual behaviour
Despite that "share link" is actually working, showing user a download page with correct filename. etc. When one try to press download button or access the direct download link you got an empty screen with the following URL in the address bar:
https://cloud.soulfly.us:8443/apps/files_encryption/files/error.php?p=0&errorCode=3
(when using firefox)

and ERROR 500 when using IE and direct download link like this:
https://cloud.soulfly.us:8443/public.php?service=files&t=178f51d8c33242ee589123d714fe5647&download
HTTP ERROR 500

also you got the following in owncloud.log
[Thu Jun 26 22:51:33 2014] [error] [client 91.191.240.207] PHP Fatal error:  Class 'OCA\\Encryption\\Crypt' not found in /var/www/owncloud/apps/files_encryption/files/error.php on line 11, referer: https://cloud.soulfly.us:8443/public.php?service=files&t=178f51d8c33242ee589123d714fe5647

### Server configuration
**Operating system**:
Ubuntu 12.04.4 LTS
**Web server:**
Apache/2.2.22
**Database:**
mysql  5.5.37,
**PHP version:**
PHP Version => 5.3.10

**ownCloud version:** (see ownCloud admin page)
7.0 beta1
**Updated from an older ownCloud or fresh install:**
fresh
**List of activated apps:**
only default ones and encryption
**The content of config/config.php:**
cat ./config.php
<?php
$CONFIG = array (
  'instanceid' => 'occa635',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => 'cloud.soulfly.us:8443',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.0.2',
  'dbname' => 'own',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'ff_',
  'dbuser' => 'ffad',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'loglevel' => '0',
  'forcessl' => true,

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

### Client configuration
**Browser:**
Firefox 29
IE 11

**Operating system:**
Windows 7
Windows 8.1

#### ownCloud log (data/owncloud.log)
[Thu Jun 26 22:51:33 2014] [error] [client 91.191.240.207] PHP Fatal error:  Class 'OCA\\Encryption\\Crypt' not found in /var/www/owncloud/apps/files_encryption/files/error.php on line 11, referer: https://cloud.soulfly.us:8443/public.php?service=files&t=178f51d8c33242ee589123d714fe5647

#### Browser log
https://cloud.soulfly.us:8443/apps/files_encryption/files/error.php?p=0&errorCode=3

**Comment by enoch85** [comment]
@MarvinFS Is this issue still present?

**Comment by MarvinFS** [comment]
@enoch85 
Daniel, i cannot tell now - the project went a long way forward and changed a lot.I have to do the testing again! May be it's better to close this thread and make a new one, relevant to the current version.

**Comment by enoch85** [comment]
@MarvinFS Yes, that sounds like a good idea. :)
