### ISSUE TITLE
Folder specific views

### ISSUE THREAD

**Issue by butonic** [owncloud/core#9243]
The new preview icons give us the ability to not only show a list of files but also a thumbnail icon grid as is the default in gnomes nautilus and windows explorer.

Depending on the folder different views make sense: `/Pictures` and `/Videos` folders should show the *grid*. `/Documents` might default to the list *view*. 

In this regard it might make sense to have a *browse with gallery* view, or *show in music* view.

@owncloud/designers we should decide on a default for all folders in the [XDG_USER_DIRS](http://cgit.freedesktop.org/xdg/xdg-user-dirs/tree/user-dirs.defaults)

**Comment by jancborchardt** [comment]
Closing in favor of #17357 »Add a thumbnail/grid view to the Files app«

**Comment by Bugsbane** [comment]
Maybe I'm missing something, but I don't see any discussion of sort order in #17357, nor about remembering sort order per folder. There is more discussion of this in https://github.com/owncloud/gallery/issues/197 which ironically, also points over to #17357.

**Comment by jancborchardt** [comment]
@Bugsbane this issue is primarily about the view, not the sort order. :)
