### ISSUE TITLE
Sabre_DAV_Exception_Forbidden level 4 error, when it's not an error

### ISSUE THREAD

**Issue by jakubcjusz** [owncloud/core#9246]
Step to reproduce:

1. Create account end insert some file to it.
2. Share file/folder with someone, but don't give him/her delete rights.
3. Let this person try to delete this file on hard drive.

Whats happend? In access.log:
95.143.242.123 - user [27/Jun/2014:08:33:52 +0200] "DELETE /remote.php/webdav/Shared/file-to-delete.pdf HTTP/1.1" 403 242 "-" "Mozilla/5.0 (Windows) csyncoC/0.91.5 neon/0.30.0"
95.143.242.123 - user [27/Jun/2014:08:33:52 +0200] "GET /remote.php/webdav/Shared/file-to-delete.pdf HTTP/1.1" 200 137996 "-" "Mozilla/5.0 (Windows) csyncoC/0.91.5 neon/0.30.0"

In owncloud.log:
{"app":"webdav","message":"Sabre_DAV_Exception_Forbidden: ","level":4,"time":"2014-06-27T06:33:52+00:00"}

I think in this case it's not a level 4 error. User tried to delete, and get 403 response, but owncloud server says it's an error.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/15171
