### ISSUE TITLE
Allow users to edit email message before its sent.

### ISSUE THREAD

**Issue by Bridgesltd** [owncloud/core#9253]
Please could you allow end users to configure the email message before its sent.
Almost every time, our users would like to share files with clients and need to include additional information about the issue of files.

I have created a mock design on how this can be easily achieved.
![popup](https://cloud.githubusercontent.com/assets/5995648/3410814/222ea41c-fded-11e3-9b3d-8644c81d9fac.jpg)

**Comment by pornstarsui** [comment]
I'm wondering if there is any progress on this 3 year old issue. Our users would also greatly appreciate the possibility to add their own comment to the mail that is sent. A small personal text area would be perfect for that!

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/29696
