### ISSUE TITLE
Issues with Sabre DAV's web UI and invalid URLs

### ISSUE THREAD

**Issue by stopspazzing** [owncloud/core#9267]
There are several minor bugs including invalid HTML5 pages that are generated by webdav and common warning on nginx due to "&" being the icon url instead of "& amp ;" which is causing the follow issue:
Warning	core	isWebDAVWorking: NO - Reason: The passed data is not valid XML (InvalidArgumentException)

Curious why owncloud isn't using the latest stable version of Sabre? Is there a planned update before 7.0 release?

https://github.com/fruux/sabre-dav/

**Comment by DeepDiver1975** [comment]
we meanwhile did remove the sabredav browser plugin
