### ISSUE TITLE
Cache groups (and users?) as exisiting when fetched from server

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#9271]
When groups are retrieved from LDAP it is most likely that the existance check will be requested from  the ownCloud group manager. If not cached, the existance check will finally call the LDAP server to  verify this. Since we retrieved the groups just before, we should cache them as existing and save those unnecessary requests to LDAP. 

This makes probably sense for users as well. 

The caching could be triggered from within Access::ldap2ownCloudNames (where we already cache user display names for the same reason).

This will have  a positive performance impact, which OTOH is not overly high. Nevertheless it is always better to use as few LDAP requests as possible :)

**Comment by PVince81** [comment]
I suppose that if we had a local table with all users from all user managers, that would be even better ?
See https://github.com/owncloud/core/issues/21282

**Comment by PVince81** [comment]
I see a key `$cachedGroupMembers`, so maybe it's already implemented ? @owncloud/ldap

**Comment by hodyroff** [comment]
Closing as its implemented for users and we are about to implement it for groups.
