### ISSUE TITLE
Native swift containers and accounts

### ISSUE THREAD

**Issue by enorniel** [owncloud/core#9299]
Hello,

I checked a bit the merged branch in OC 7.

If I understood correctly, the mounted swift is at the container level and not account level, isn't it ?

We loose a lot of Swift native features in that kind of setup. Quotas, versionning, encryption...

Is there a way to handle it on the account level when we own a swift cluster ?

Thanks.

**Comment by ddxgz** [comment]
How is this feature going right now? 
As far as I know, too many objects (millions) in one container will significantly slow down the performance of Swift, since the container data is stored in sqlite. 
Without multi-container, the Swift backend feature means nothing in production.

**Comment by michaelstingl** [comment]
A user shared his ideas recently:

> Recently I have been playing around with Openstack swift as primary storage backend for Owncloud.

> I have seen that Owncloud puts all data from all users in one single container. This does not look OK to us since the SWIFT storage nodes use sqlite (on every node) for their metadata. One sqlite database is created for every container. This means that in the Onwcloud case this database can become really big. Now sqlite supports databases upto 140TB if I am correct, so that is a limit you don't run easily into but having a single database, the tables can become really large and the
performance of sqlite decreases with an increasing size of the tables. So here is a potential performance bottleneck for large installations.

> Wouldn't it be much better to give every user his own container. Wouldn't that make deleting users and do accounting more easy and fast compared to putting everything into one single container?

00003895

**Comment by MTRichards** [comment]
Yep. Known issue, though I did see a pull request to address this recently I think. 

-- 
Matt Richards
VP Products & Markets 
ownCloud, inc.

**Comment by rontrompert** [comment]
Hi Matt et. al.,

That user is me, Ron from SURFsara. At the moment we are using gluster fs and we are not very pleased with it. We would like to migrate a few months from now to SWIFT. So a fix for this would be really neat.

Cheers,

Ron

**Comment by MTRichards** [comment]
00004263

**Comment by hodyroff** [comment]
Closing as SWIFT protocol will be deprecated in favor of full S3 support.
