### ISSUE TITLE
[webdav] Etag does not change when disabling share api

### ISSUE THREAD

**Issue by purigarcia** [owncloud/core#9304]
### Steps to reproduce
1. user1 has shared several folder with user2
2. Using poster, check the etag of the parent folder
	- URL: http://server/remote.php/webdav
	- user/password
	- Click on Profind
3. In the web, uncheck “Allow apps to use Share api”
4. Check using poster that the etag is the same one as before for user2 although the share folders are not in the file list anymore.
The problem is that since the etag is not changed, in the mobile device these folders are still shown although you refresh the folder.

### Expected behaviour
Etag is changed if shared folders/files are gone when disabling share api. In order, to refresh mobile client

### Actual behaviour
Etag is not changed if shared folders/files are gone when disabling share api

### Server configuration
Operating system: MaOs 10.7.5
Database: SQLite 
ownCloud version: {"installed":"true","version":"7.0.0.2","versionstring":"7.0 beta 1","edition":""}

**Comment by MorrisJobke** [comment]
@icewind1991 @rullzer Can there be added a similiar solution like #19511 ?

**Comment by rullzer** [comment]
Mmmm the thing is that this would require chaning the etag on every users root folder. Which of course does not scale when you have huge installations.

@icewind1991 will this be fixed if we have your new fancy propegator stuff?

**Comment by PVince81** [comment]
It might because the new propagator is computing the root etag on the fly based on all mount points.
So if sharing gets disabled, the share mount points disappear, so the computed etag will change.

This is the PR that does this: https://github.com/owncloud/core/pull/20439

**Comment by rullzer** [comment]
This seems to be fixed in 9.0

Steps I took

1. Share file with USER
2. Get etag of root folder for USER
3. Disable sharing
4. Get etag of root folder for USER
5. Assert etag in 2 and 4 are different.

**Comment by PVince81** [comment]
Yes, @icewind1991 revamped the etag change detection with mount points to be computed based on the etag of all mounts.. So if shares disappear, the etag automatically changes.
