### ISSUE TITLE
Version and share dropdown conflict

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/core#9309]
1. Open the version dropdown
2. Open the share dropdown
3. Try to close the share dropdown, by pressing on the Share option again

### Expected
It closes the share dropdown and no other dropdown is open

### Actual
The share dropdown stays open

PS: OC7 CE?

**Comment by PVince81** [comment]
Not a showstopper and not that bad a bug, I will not risk it in OC 8 (and also there are open issues). Defer to 8.1

**Comment by PVince81** [comment]
8.2 says goodbye dropdowns.

And I don't think this is critical enough to make a 8.1 specific fix, closing.

Feel free to reopen if you think otherwise.
