### ISSUE TITLE
Enforcing "Do not repeat yourself" and code deduplication

### ISSUE THREAD

**Issue by bantu** [owncloud/core#9310]
* We should look into permanently setting up tools for finding duplicate code as copy and pasting code seems to be very common practice in the ownCloud code base.

* We should establish that pull requests introducing massive duplication are not acceptable.

* We should get rid of any code duplication already present.

Duplicate code causes problems as such "Purpose masking" and "Update anomalies". See http://en.wikipedia.org/wiki/Duplicate_code#Problems_associated_with_duplicate_code

Sometimes the duplicated blocks are even next to each other, e.g. https://github.com/owncloud/core/blob/master/lib/base.php#L472
```php
		if (isset($_SERVER['HTTP_AUTHORIZATION'])
			&& preg_match('/Basic\s+(.*)$/i', $_SERVER['HTTP_AUTHORIZATION'], $matches)
		) {
			list($name, $password) = explode(':', base64_decode($matches[1]), 2);
			$_SERVER['PHP_AUTH_USER'] = strip_tags($name);
			$_SERVER['PHP_AUTH_PW'] = strip_tags($password);
		}

		//set http auth headers for apache+php-cgi work around if variable gets renamed by apache
		if (isset($_SERVER['REDIRECT_HTTP_AUTHORIZATION'])
			&& preg_match('/Basic\s+(.*)$/i', $_SERVER['REDIRECT_HTTP_AUTHORIZATION'], $matches)
		) {
			list($name, $password) = explode(':', base64_decode($matches[1]), 2);
			$_SERVER['PHP_AUTH_USER'] = strip_tags($name);
			$_SERVER['PHP_AUTH_PW'] = strip_tags($password);
		}
```

**Comment by MorrisJobke** [comment]
We should address this in a more special favor. Just having a ticket about "best practices in programming" doesn't solve anything -> closing
