### ISSUE TITLE
Storage full message shows NaN as the remaining free space.

### ISSUE THREAD

**Issue by wakeup** [owncloud/core#9342]
Reproduce:

1. Reduce the available storage for one user below to the used space.
2. Upload a file using the web interface

The message shown is:

*Not enough free space, you are uploading 527 B but only NaN undefined is left*

It seems the code is [here](https://github.com/owncloud/core/blob/master/apps/files/js/file-upload.js#L292)

**Comment by a-schild** [comment]
I have created a "read-only" login with a storage quota of 0Bytes.
When I login with this user and try to upload a file via Drag&Drop I also see the Nan message.
![dateien - owncloud_2015-01-29_11-55-25](https://cloud.githubusercontent.com/assets/1441009/5956519/fe734e12-a7ae-11e4-97af-be9318f2e9be.png)
