### ISSUE TITLE
Sync Client List

### ISSUE THREAD

**Issue by dubsflyt** [owncloud/core#9346]
Could we possibly get a section in the admin panel which shows a list of sync clients / map drives and which users are using which version.

Basically in an environment where a user cannnot update the sync client themselves (e.g. domains which require admin access to do) it can be a nightmare to track who has which version of the client. A single admin screen which shows whos using which version (and possible from which ip) would be a godsend

**Comment by LukasReschke** [comment]
Very related to https://github.com/owncloud/core/issues/6120
