### ISSUE TITLE
exclude "computer" object class in user list filter

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#9353]
In Active Directory computers are persons, which is why they will likely show up as users.  To exclude computers the Wizard should add "(!(objectClass=computer))" to the user list filter. 

Kudos to @danimo for reporting.

**Comment by DeepDiver1975** [comment]
@blizzz close, 8.0 or 8.1 ? THX

**Comment by blizzz** [comment]
8.1, nothing urgent

**Comment by PVince81** [comment]
@butonic reopen in user_ldap repo if this is still needed
