### ISSUE TITLE
Without configuration file `config.php` don’t require to enter an admin and allow to use existing users

### ISSUE THREAD

**Issue by paulepanter** [owncloud/core#9375]
ownCloud 6.0.4, but also present in 5.0.15

The setup dialog should allow the scenario of a non-existing configuration file `config.php` but existing users in the database. Without the database credentials in the configuration file, which does not exist yet, it is not possible to list the existing users. Therefore the dialog should be changed so the credentials can be inserted first and when the user does that the users are fetched and presented.

If that is not possible the user should be able to leave the admin field empty or to just enter an existing user. Currently that fails with the error message, that the user already exists.

**Comment by PVince81** [comment]
This is not technically possible. There are many things in the database that require the instance id and the secret from config.php file. So restarting from scratch like this will likely break other things.
