### ISSUE TITLE
If you share a file/folder with user called “admin”, it is shared with all the admin (group)

### ISSUE THREAD

**Issue by purigarcia** [owncloud/core#9400]
### Steps to reproduce
1. There are several users in a server
	- “user2” which is in admin group 
 	- “admin” which is in admin group 
	- “user1” which does not matter if it is in admin group or not
2. Login as user1
3. Share folder called “a” with user “admin”, not with admin (group)
4. Login as user2.
And you can see a shared folder called “a” when it should not because it was not share with him

### Expected behaviour
Shared folder “a” is not in the file list of user2

### Actual behaviour
Shared folder “a” is in the file list of user2

### Client configuration
Operating system: MacOs 10.7.5
Web server: Firefox, Chrome
Owncloud version: It was tested in daily
{"installed":"true","version":"7.0.0.3","versionstring":"7.0 beta 1","edition":""}

**Comment by nickvergessen** [comment]
Can not reproduce on current master anymore
