### ISSUE TITLE
updates not working, update screen empty

### ISSUE THREAD

**Issue by joernhees** [owncloud/core#9409]
Hi,

after manually upgrading owncloud for several releases now, the updater still seems to have problems in the 6.0.4 release. Going to the admin's update screen i see this:

![update screen](https://cloud.githubusercontent.com/assets/464192/3468369/130b4012-029d-11e4-8ee0-8c0c6dee963f.png)

Owncloud is hosted on shared webspace from domainfactory and their settings allow writing to /tmp but not listing the directory (which seems to be common for shared webspace providers). Could this be the reason? I don't see anything in the logs though :(

**Comment by MorrisJobke** [comment]
New PR that is merged to master (will be released with ownCloud 8) #12664 - according to @VicDeo this change should fix your issue

**Comment by MorrisJobke** [comment]
@baem2 Please report back if you still have these problems with ownCloud 8
