### ISSUE TITLE
Server-server sharing UX improvements

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#9429]
These are the issues from https://github.com/owncloud/core/issues/8934 with a bit less importance (or requiring significantly more work) than the other items. Setting for ownCloud 8.
- [x] Display remote shares in "Shared with you" section https://github.com/owncloud/core/issues/9098
- [ ] combine »Download« and »Add to your ownCloud« buttons in a »Download« dropdown on the top right to save space.
- [ ] slight animation when clicking the »Add to your ownCloud« button, or popover (not just replace)
- [ ] »Accept share« popover: show thumbnail / preview /folder icon if possible
- [ ] highlight the entry which was added: requires https://github.com/owncloud/core/pull/9195 => OC 8
- [ ] Better error messages whenever mounting shares is not allowed either locally or remotely

cc @owncloud/designers @craigpg

**Comment by DeepDiver1975** [comment]
@icewind1991 was anything taken care of within the scope of oc8? THX

**Comment by icewind1991** [comment]
No

**Comment by DeepDiver1975** [comment]
thx - moving to 8.1 then

**Comment by jancborchardt** [comment]
cc @schiesbn

**Comment by jancborchardt** [comment]
Or @rullzer maybe you’re interested in checking some of this out, since you do a lot of sharing stuff recently?

**Comment by jancborchardt** [comment]
Moved to 9.0 as discussed @karlitschek. Unfortunate but then with 9.0 we can polish the remote sharing mechanism.

**Comment by PVince81** [comment]
We're past feature freeze, moving to 9.1.

Most items aren't trivial and cannot be done quickly.

The only one that might do is "highlight" after adding/accepting remote share, if you like you can put it in a separate ticket and set it to 9.0.1. (I have an idea how to do this)

**Comment by ChristophWurst** [comment]
@PVince81 I think we should move this to 9.2 as we're past feature freeze again.
