### ISSUE TITLE
[7RC1] strftime encoding issue

### ISSUE THREAD

**Issue by Kondou-ger** [owncloud/core#9448]
__Edit__: See https://github.com/owncloud/core/issues/9448#issuecomment-49683027 too. This reproduction report isn't the root, but rather just a specific symptom to my instance.

### Steps to reproduce
1. Put [this image](http://ts.unde.re/ls/Screenshot_2014-03-01-08-04-07.png) into any directory
2. Browse into the directory

### Expected behaviour
Show the directory with its contents

### Actual behaviour
Nothing, when clicking again – return to your root directory

### Server configuration
**Operating system**: opensuse 12.3

**Web server:** nginx 1.5.12

**Database:** postgresql

**PHP version:** php 5.5.14

**ownCloud version:** (see ownCloud admin page) 7 RC1

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:**
- Activity
- Calendar
- Files
- Contacts
- Deleted files
- PDF Viewer
- Share Files
- Text editor
- Versions
- Imprint

**The content of config/config.php:**

```php
<?php
$CONFIG = array (
  'loglevel' => '2',
  'instanceid' => '…',
  'passwordsalt' => '…',
  'datadirectory' => '/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.0.4',
  'dbname' => '…',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => '…',
  'dbpassword' => '…',
  'installed' => true,
  'appstoreenabled' => false,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/apps',
      'url' => '/apps',
      'writable' => true,
    ),
    1 => 
    array (
      'path' => '/apps-git',
      'url' => '/apps-git',
      'writable' => false,
    ),
  ),
  'forcessl' => true,
  'maxZipInputSize' => 419430400,
  'allowZipDownload' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => '…',
  ),
  'custom_csp_policy' => 'style-src \'self\' \'unsafe-inline\'; frame-src *; img-src *; font-src \'self\' data:; media-src *',
);
```

**Are you using external storage, if yes which one:** nope

**Are you using encryption:** nope

### Client configuration
**Browser:**  Firefox 30.0 & Chromium 35.0.1916.153

**Operating system:** opensuse 13.1

#### Web server error log
```
… - - [04/Jul/2014:15:10:42 +0200] "GET /index.php/apps/files/ajax/list.php?dir=%2FBilder%2Fbroken&sort=name&sortdirection=asc HTTP/1.1" 200 20 "https://…/index.php/apps/files?dir=%2FBilder%2Fbroken" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36"
```

#### ownCloud log (data/owncloud.log)
```
Nothing, yup.
```

#### Browser log
```
Uncaught TypeError: Cannot read property 'data' of null
filelist.js?v=315b4df935f4775ef5033a4833a9e0e1:948
```

**Comment by enoch85** [comment]
Any update here, or close?

**Comment by Kondou-ger** [comment]
@enoch85 The issue mentioned in the opening post seems to be fixed, and the underlying issue (mentioned here https://github.com/owncloud/core/issues/9448#issuecomment-49683027) too.

But the root reason @DeepDiver1975 mentioned just above your post https://github.com/owncloud/core/issues/9448#issuecomment-51519337 is still there:

Data from apps/files/ajax/list.php:
```
{"data": {
  "directory":"\/Bilder\/broken",
  "files":[{
    "id":31578,
    "parentId":30989,
    "date":"5. M\u00e4rz 2014 um 12:52:05 MEZ",
    "mtime":1394020325000,
    "icon":"\/core\/img\/filetypes\/image.svg",
    "isPreviewAvailable":true,
    "name":"….jpg",
    "permissions":27,
    "mimetype":"image\/jpeg",
    "size":1275708,
    "type":"file",
    "etag":"af567bb12f0ec3607ea1c033f282647a"
    }],
  "permissions":31
  },
"status":"success"
}
```

`"date":"5. M\u00e4rz 2014 um 12:52:05 MEZ",` is still translated at server and transferred translated.

**Comment by DeepDiver1975** [comment]
The date issue is handled in another isset.
