### ISSUE TITLE
proxy not called because of wrong method name

### ISSUE THREAD

**Issue by schiesbn** [owncloud/core#9454]
The encryption app implements a postGetFileInfo proxy (see: https://github.com/owncloud/core/blob/master/apps/files_encryption/lib/proxy.php#L301)

In OC\Files\View we call the proxy with a lower case 'g', see https://github.com/owncloud/core/blob/master/lib/private/files/view.php#L907

In OC6 we do exactly the same. But for some reasons in ownCloud7 the proxy is no longer called. If I change the method name in "postgetFileInfo()" the proxy gets called.

@icewind1991 can you have a look at it? What is the correct behavior? Of course I could easily change the method name but I would prefer to know the root of the problem because there are a lot of other proxies which still use a upper case for the first letter and they work just fine.

**Comment by PVince81** [comment]
So far it seemed the encryption app worked well.

Also, the encryption app will move away from proxies in #14472, so I think this will be obsolete anyway. Closing.
