### ISSUE TITLE
System time is wrong on ownCloud but correct in system

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#9456]
Just noticed that the system time is wrong, both in oC 6.0.4 and oC 7 beta1.

Following is my system time in linux:
root@owncloud:~# date
Fri Jul  4 19:41:24 CEST 2014

But in ownCloud the time differs by several hours:
![image](https://cloud.githubusercontent.com/assets/4511254/3484228/614555ea-03a3-11e4-8073-04af4574bbaa.png)
Notice the time of the picture, and the time ownCloud thinks it´s uploaded.

Same thing is regarding the owncloud.log file. There, the time also is wrong by several hours.

Another thing is the calendar app that automatically sets "Copenhagen" as the timezone, but it should be Stockholm.

### Expected behavior
Time stamps and time in general should be correct and synced with the time on the server

### Actual behavior
Time differs by several hours

### Server configuration
Ubuntu Server 12.04

**Database:**
MySQL latest
**PHP version:**
PHP 5.3.10-1ubuntu3.12 with Suhosin-Patch (cli) (built: Jun 20 2014 00:38:55)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
**ownCloud version:** (see ownCloud admin page)
6.0.4 & 7.0 beta1
**Updated from an older ownCloud or fresh install:**
Updated from 6.0.3, 6.0.2 and 6.0.1 (fresh install on oC 7.0 beta1)
**List of activated apps:**
Activity
Calender 
Contacts
Deleted files
Documents
External Storage Support
First Run Wizard
Full Text Search
Music
PDF Viewer
Pictures
Share Files
Tasks
Text Editor
Updater
Versions
Video Viewer

### Client configuration
**Browser:**
Chrome Version 34.0.1847.131 m
**Operating system:**
Windows 7 Ultimate

**Comment by nickvergessen** [comment]
@enoch85 does this still happen?
Please also make sure that your php has set the timezone internally

**Comment by enoch85** [comment]
@nickvergessen No problem does not presist. *But* it should be in 24h format and not 12h format. So 19 should be 19 and not 7. Want to make a PR? ;)

**Comment by enoch85** [comment]
@nickvergessen Just noticed that the error still happening in owncloud.log.

**Comment by nickvergessen** [comment]
https://github.com/owncloud/core/blob/master/config/config.sample.php#L494-L498

**Comment by enoch85** [comment]
Thanks!
