### ISSUE TITLE
Double deletion with trashbin

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#9464]
Backgournd info: I have a very sensitive touchpad and sometimes when I want to tap once it just double taps.

### Steps to reproduce:
1. Create a folder "test" with a few files in it
2. Move the mouse to the delete icon
3. Quickly double click / double tap the delete icon
4. Go to trashbin

### Expected result
Files deleted only once.

### Actual result
Error message "Could not delete test".
In trashbin there are two separate instances of "test".

### More information
Observed on ownCloud 7 RC 1 but I'm pretty sure it could happen in other versions like 6.0.4 (not tested yet).

This might be a general issue and could happen for other actions as well...
Not sure how to block this ?

@schiesbn @icewind1991

**Comment by Xenopathic** [comment]
Looks like this has been fixed - as soon as the click on Delete is registered, the icon becomes a spinner.

**Comment by PVince81** [comment]
@Xenopathic did you click fast enough ? :wink:
