### ISSUE TITLE
Installation: Combine database errors

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#9465]
Currently when there are installation errors like some database fields omitted, the error looks like this:
![owncloud installation errors](https://cloud.githubusercontent.com/assets/925062/3486056/643ebb52-041a-11e4-8f5b-f16bb2897bfa.png)

That could really be combined instead, and given a sensical title, to:
> **Database info missing**
> Please enter the database username and password.

**Comment by DeepDiver1975** [comment]
moving to backlog -> not critical

**Comment by jancborchardt** [comment]
I’d say 8.1 since it’s lack of polish and doesn’t seem particularly difficult to fix.

**Comment by jancborchardt** [comment]
Anyone up for fixing this junior job? @enoch85 @MorrisJobke someone? :)

**Comment by enoch85** [comment]
@jancborchardt Please give me the lines this issue is regarding, and I'll have a look.

**Comment by jancborchardt** [comment]
@enoch85 simply use your text editor or tool of choice to search the codebase for »enter the database username«. ;)

**Comment by enoch85** [comment]
@jancborchardt Is it here somewhere https://github.com/owncloud/core/tree/90810cc6052b38ac03dd8f08a200c5928a355d20/lib/private/setup ?

**Comment by jancborchardt** [comment]
Yep. When I meant »search the codebase« I’d recommend a text editor which can automatically search strings across all files. I recommend [Atom](https://atom.io/). :) (With Ctrl-Shift-F you can search across the whole project.)

**Comment by MorrisJobke** [comment]
Fixed by #23326
