### ISSUE TITLE
Calendar and addressbook sync through webdav broken after upgrading from 6.0.3 to 6.0.4

### ISSUE THREAD

**Issue by torlasz** [owncloud/core#9487]
After I upgraded from 6.0.3 to 6.0.4 everything works as expected except webdav sync of calendars and addressbooks. Syncing of files is ok. The sync client reports: Server error (status code 500). The webserver logs are always the same:
[error] [client xx.xx.xx.xx] PHP Fatal error:  Call to a member function instanceOfStorage() on a non-object in /var/www/owncloud/lib/private/util.php on line 67

It doesn't matter if I try to sync with a remote calendar or addressbook, the error is the same.

The same error was reported in issue #9424, but it was triggered by accessing a google drive.

This is on RHEL 6.5, mysql-server-5.1.73-3.el6_5.x86_64, httpd-2.2.15-30.el6_5.x86_64, 
php-5.3.3-27.el6_5.x86_64.

**Comment by PVince81** [comment]
Please try again with 7.0.5 or  8.0.2 where setup/mounting is done in a more lazy manner (on-demand), which should fix this too.

If you're still seeing the issue in those versions, feel free to reopen.
Thanks.
