### ISSUE TITLE
File uploader init problem

### ISSUE THREAD

**Issue by patrick1990** [owncloud/core#9508]
I've located a problem in my situation with the file uploader in the files app of owncloud. I have users on my owncloud who have no own space and are just allowed to write to directories connected to them over the external storage app. So I have cleared the write permission on their owncloud data directory.

Expected behaviour:
Owncloud should tell the user that he has no permission to write to his root directory. When the user changes to a dir from the external storage app he should get the button for uploading files and should be able to do so.

Current behaviour of owncloud:
Owncloud shows the user that he has no permission to write to his root directory and hides the upload button. When the user changes to a dir from the external storage app owncloud shows him the upload button, but when he presses the upload button and selects a file to upload, owncloud doesn't start the upload process.

Cause of the problem (Owncloud version 6.0.4):
On line 173 of the file apps/files/js/file-upload.js there is an if statement which checks, if the file upload button exists and if it is visible. If that's the case then the program initializes the file upload system on line 381. The problem is, that this code is only executed once, when the file app is loaded (see Line 171) and it will not be executed when the folder is changed (DOM will not be reloaded).

Solution approach:
Maybe it is a solution to delete the if on line 173. When this if is important, maybe there is a way to check the visible state of the upload button more often, maybe on a "dir change event".

**Comment by Xenopathic** [comment]
Appears to be fixed in master. @PVince81 Will this be necessary to check in stable7?

**Comment by PVince81** [comment]
Not sure. Do you mind having a look ?

**Comment by Xenopathic** [comment]
Yep, seems fixed there too.
