### ISSUE TITLE
big folder owncloud/data/<user>/cache

### ISSUE THREAD

**Issue by mzaian** [owncloud/core#9513]
Hello,
I'm having a big issue with my owncloud setup at work i recently upgraded the server to 6.04 and the latest client 1.6.1.

Some owncloud users have a big cache directory and still creating chunks of 10mb in their respective directory i tried to delete these files manually but its hitting back again and my storage is growing since i'm having the issue with half of my users.

I need to solve it as soon as possible.

Thanks,

**Comment by PVince81** [comment]
Cleanup of chunks will now happen as part of a background job as per https://github.com/owncloud/core/pull/14500 (CC @icewind1991)

**Comment by mzaian** [comment]
Which owncloud server version im currently using 7.0.3

**Comment by PVince81** [comment]
It will be in the upcoming 8.1

**Comment by PVince81** [comment]
I see it was backported, so will probably be in 8.0.3
