### ISSUE TITLE
Enhance question in DB migration script

### ISSUE THREAD

**Issue by unclejamal3000** [owncloud/core#9526]
I have tested the DB migration with the latest OC server version:
In the beginning I was asked if I want to continue the conversion. The script should give an option which input is expected [Y/N, default: N]

In the first time I just hit "Enter" and the conversion quit.

```
$  ./occ db:convert-type --password="***" --all-apps mysql ocdba localhost owncloud
Creating schema in new database
The following tables will not be converted:
oc_news_feeds
oc_news_folders
oc_news_items
oc_permissions
Continue with the conversion?
```
### Expected behaviour
Only accept the mentioned keys in a predictable way.

### Actual behaviour
You don't really know what happens, also because it seems there is no documentation yet for this script.

### Server configuration
**Operating system**:
Debian Wheezy
**Web server:**
Nginx 1.2.1-2.2+wheezy2
**Database:**
MySQL 5.5.37-0+wheezy1
**PHP version:**
5.4.4-14+deb7u11
**ownCloud version:** (see ownCloud admin page)
7.0 RC 1 (testing)
**Updated from an older ownCloud or fresh install:**
Updated from 6.0.4
**List of activated apps:**
Activity
Deleted files
Documents
First Run Wizard
Full Text Search
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Versions
Video Viewer

**Comment by wshadow** [comment]
#9891 seems to be a different problem

The issue here seems to be fixed with the already merged PR #11902. I'll close this even if the change is not in the current stable (7.0.4) release. If anyone still has this issue with version greater then 8.x feel free to comment/re-openthis.
