### ISSUE TITLE
Feature Request: Password Protected Folders

### ISSUE THREAD

**Issue by ghost** [owncloud/core#9530]
I'm requesting a Feature to give a folder a password. Thats a Thing for security, and for Multiusers.

**Comment by mobigraph** [comment]
I have a similar requirement as @PhantomicLP  
The Main Idea of this feature is to restrict users Seeing other Development Folders.
We have an Organisation where we give code-base to several clients & individual clients shall not be seeing the development other clients are doing , can be Hidden from other Client or password protected

**Comment by MatthieuPERIN** [comment]
:+1: 

For me the usage is the following:

/projetcA           -> shared among all participant using group / user permission
/projetcA/work  -> shared among all participant using group / user permission
/projecta/team  -> shared among all participant using group / user permission
/projectA/admin -> **protected** folder with password for administrator of project
/projetcA/admin/finacial -> protected by the upper folder
.....

The features:

* Admin of the shared folder should be able to protect the access of a (sub)folder using a password using web interface (minimal feature)
* Admin of the shared folder should be able to protect the access of a (sub)folder using a password directly using the local desktop agent (improvement feature)

This is clearly a way to produce a more accurate accès control for sub folder inside a shared folder.

**Comment by luhaijiao** [comment]
+1

This is a flexible way to further control access within a big folder, keen to see it in coming release. :-)

**Comment by DeepDiver1975** [comment]
Please Start a feature discussion at https://central.owncliud.org thx
