### ISSUE TITLE
Ignore files on server side

### ISSUE THREAD

**Issue by kurtgeebelen** [owncloud/core#9542]
Hi all,

I have some folders that I have on my ownCloud via SMB. Scattered throughout these folders are subfolders that are needed on the server (all called .metadata), but that I don't want to sync to other machines, or even show up in the web client.

I have found that for the reversed problem where a client creates those type of files that you don't want to sync, you can put it in sync-exclude.lst, but not something the other way around. 

Would this in any way be possible? E.g. a similar sync-exclude.lst that the admin can fill in, such that those files are ignored on the server side?

**Comment by justmiles** [comment]
Adding my +1
I'm surprised there hasn't been more demand for this. Is there a workaround?

**Comment by RealRancor** [comment]
Just to have a context why this was closed:

A new app is now providing this functionality: https://apps.owncloud.com/content/show.php/files_filter?content=174667

**Comment by fduraibi** [comment]
@RealRancor The app doesn't solve the problem the OP is talking about. I have never needed to exclude by file type, I always exclude by file/ext names like *.tmp .git *-debug ....etc  just like sync-exclude.lst but I want that at the server level. My server is full of these files that were synced by clients that are missing the exclude rules or where synced before I added the rule.

I would love to have a server exclude list that will update the clients and also delete previously synced files/folders that matched the exclude list.

**Comment by RealRancor** [comment]
@fduraibi Have a look at https://github.com/musaa32/files_filter/issues/6

**Comment by fduraibi** [comment]
@RealRancor That is just a request from a user and it is not implemented. The way that filter works is different from what we are asking for. The app deletes the files from the server after getting synced. I don't want the file to be synced to begin with. 

Just like how you can add patterns to the client "Ignored files" there should be an option to allow the user to sync that list (or some of it, like a check box for each element) to the server to be populated to the other clients for the same user.

**Comment by RealRancor** [comment]
If you think this is something which should be included in core just create a new feature request specifying your requirements. Maybe some one will pick it up

**Comment by RealRancor** [comment]
Maybe one of those still open feature requests are already matching your requirements:

https://github.com/owncloud/core/issues/19385, https://github.com/owncloud/core/issues/22607

**Comment by RuudschMaHinda** [comment]
just add this to your config.php
you can add any more number of files like this. I just chose those nasty tmp files from the mac users

  ```
'blacklisted_files' =>
  array (
    0 => '._*',
    1 => '.DS_Store',
    2 => '.DS_STORE',
    3 => '.ds_store',
  ),
```

**Comment by bonanza123** [comment]
@RuudschMaHinda I added 

```
  'blacklisted_files' =>
  array (
    0 => '._*',
    1 => '.DS_Store',
    2 => '.DS_STORE',
    3 => '.ds_store',
    4 => '.log',
    5 => '.bbl',
    6 => '.out',
    7 => '.blg',
    8 => '.aux',
  ),

```

to my ```/var/www/owncloud/config/config.php```. Deleted some ```.log``` files via webinterface and then added some via the owncloud client and they are still being uploaded. Am I doing something wrong?

**Comment by RuudschMaHinda** [comment]
Yes, you are doing something wrong:
you exclude files that are solely named .log that means any file that is named abc.log will get uploaded. if you want all files ending in .log not be uploaded you should name it *.log
(see filename character placeholders)
so in your case, you want to do this:
```
  'blacklisted_files' =>
  array (
    0 => '._*',
    1 => '.DS_Store',
    2 => '.DS_STORE',
    3 => '.ds_store',
    4 => '*.log',
    5 => '*.bbl',
    6 => '*.out',
    7 => '*.blg',
    8 => '*.aux',
  ),
```
there is no ' * ' before the .ds_store files, because that is their actual filename in my example and the '._*' stop any file that starts with '._abc' to not get uploaded, again the asterisk meaning 'whatever comes here is valid'
I hope I could help

**Comment by kiu-ball** [comment]
@RuudschMaHinda 

This does not work. Looks like wildcards are not supported at this point.
