### ISSUE TITLE
Activate / Deactivate / Activate LDAP Backend

### ISSUE THREAD

**Issue by PhilJung** [owncloud/core#9545]
Activate LDAP backend
Deactivate LDAP backend

Try to activate LDAP backend

An exception occurred while executing 'CREATE TABLE "ldap_user_mapping" ("ldap_dn" VARCHAR(255) DEFAULT '' NOT NULL, "owncloud_name" VARCHAR(255) DEFAULT '' NOT NULL, "directory_uuid" VARCHAR(255) DEFAULT '' NOT NULL, PRIMARY KEY("owncloud_name"))': SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "ldap_user_mapping" already exists

So LDAP backend activation is no longuer possible

**Comment by enoch85** [comment]
@PhilJung Is this issue still present?

**Comment by blizzz** [comment]
Closed for inactivity.
