### ISSUE TITLE
[users] Adding users in filtered list bug

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#9551]
### Steps to reproduce
1. Go to the user management page
2. Create a group "group1" in the sidebar
3. Create a group "group2" in the sidebar
4. Filter by "group1"
5. Add a user "user1" using the top form and assign to "group2" (but not "group1")

### Expected result
User "user1" does not appear in the list, as it doesn't match the current filter.

### Actual result
User "user1" appears in the list.

### Versions
OC 7 git master 404ac8bcd32aca8f9b004621ac737800cd86dfd1

@blizzz  @raghunayyar

**Comment by Xenopathic** [comment]
This happens if you assign no group as well (but are still filtering by group). Is this behaviour really that bad though? Perhaps if you add a new user, all user/group filters should be cleared (it makes no sense to be filtering visible users when adding a new one IMO).

**Comment by blizzz** [comment]
Um, what is described as "Expected" would let a user action with any feedback. As @Xenopathic  i don't think that's good.  Maybe the admin just forgot or does not care about the filter this moment?
Another possible scenario next to clearing filters: maybe, user should be created, but also already with the group assigned?

cc @jancborchardt

**Comment by jancborchardt** [comment]
I agree with @PVince81 here. It’s obviously a bug – users shouldn’t show up in a group that they haven’t been added to.

**Comment by PVince81** [comment]
Fix is here: https://github.com/owncloud/core/pull/15258
