### ISSUE TITLE
Update from 5.0.16 to 5.0.17 failed to update database structure

### ISSUE THREAD

**Issue by fireraizor** [owncloud/core#9555]
I wanted to update from 5.0.16 to 5.0.17 and received following error message:
>Failed to update database structure (MDB2 Error: already exists, _doQuery: [Error message: Could not execute statement] [Last executed query: CREATE TABLE "oc_appconfig" ("appid" VARCHAR(32) DEFAULT ' ' NOT NULL, "configkey" VARCHAR(64) DEFAULT ' ' NOT NULL, "configvalue" LONGTEXT)] [Native code: 1] [Native message: table "oc_appconfig" already exists] )

Now the owncloud doesn't load anymore. Is there a way to fix that without reinstalling the backup?

**Comment by LukasReschke** [comment]
ownCloud 5 will reach EoL next month and it is unlikely that we will ever fix this in the stable5 branch. Sorry. Please try a newer ownCloud version.
