### ISSUE TITLE
Add contact / public accounts

### ISSUE THREAD

**Issue by butonic** [owncloud/core#9568]
We currently maintain a separate code path to render public pages. Pages that can be accessed without an account, eg. because someone visits a public share link. There are severas drawbacks with this approach:
- we have to maintain a separate code path for accessing files
- we already added a code path to also render the files with the gallery
- we have to maintain a separate code path in sharing for public shares as well
- the approach is inflexible as there is no easy way to allow guests to use other apps like music
- guests cannot access the content shared with them via webdav -> no desktop / mobile sync

For a customer I already implemented a guest user backend that on the fly creates users for contacts when something is shared with them. The email is sued as the username, a random password is created and they get a quota of 0. After logging in they can use all features of ownlcoud. For the customer there was no problem with the calender or contacts apps because he does not use them.

To use this approach as a general solution for ownCloud we should introduce a permission check to use an app at least by group. IIRC there is already a mechanism that can hide apps based on groups.

In addition to these contact accounts (that can actually be provided by the contacts app) we can add a public account. It can be used to grant access to all publicly shared content.

It will allow us to reduce the amount of code necessary to provide public content, as well as allow guest accounts to use the moblie / desktop clients to directly sync shared content and use other apps like music - all with the standart ownCloud web ui.

**Comment by tobiasKaminsky** [comment]
Coming from #6635 I am wondering if this public account will work with passwords and is folder specific?
My use case in #6635 is that I have shot many photos of an event and want to share them with other people. Therefore I create a new folder and provide the link via "public share" and a password.
The other people now should be allowed to add new folders. Currently I am creating folders for them.
The link and password is individual for all folders.

So one public account would not be sufficient...
But creating many public accounts will lead to just something like a user account that is shared between people.

For me the public sharing of files/folders should be kept simply and easy as it is now.

**Comment by MorrisJobke** [comment]
There is a firstworking app for this: https://github.com/butonic/guests

**Comment by butonic** [comment]
Beware, it currently opens up you instance up to everyone... I really need to fix that ...

**Comment by PVince81** [comment]
Guest app exists since a while: https://marketplace.owncloud.com/apps/guests
