### ISSUE TITLE
Clarify fields on password reset page

### ISSUE THREAD

**Issue by paulepanter** [owncloud/core#9588]
ownCloud: 6.0.4

I tested the password reset. The email was delivered and I clicked on the link. There it is not clear what to do. There is a password field with something filled in and below a button to reset the password. I did not change anything and clicked the button and it looks like the old password is still there and was not updated. This kind of contradicts the meaning of the button to reset the password and should be improved.

Please add instructions explaining the behavior that the old password is filled in/used if nothing is done.

> Please enter the new password below. If you do not enter anything and click on the button to reset the password, the old password is kept.

**Comment by PVince81** [comment]
I see this on master:

![passwordreset](https://cloud.githubusercontent.com/assets/277525/6859148/0eb12a90-d416-11e4-87ed-3b71d7ecfa9c.png)

It seems to be clear what is to be done.

But if you used IE8, maybe the placeholder shim bugged and showed the text as if it was the password ?
