### ISSUE TITLE
7.0 RC 2. Mac Client: "Requested Range Not Satisfiable" error

### ISSUE THREAD

**Issue by jameslbrown** [owncloud/core#9616]
After Upgrading server to 7.0 RC 2.

Mac Client (Version 1.6.1 build 359), Activity tab shows this error for each item:

9:53 pm facts ownCloud The item is not synced because of previous errors: Error downloading https://server.bordo.com.au:9100/owncloud/remote.php/webdav/facts - server replied: Requested Range Not Satisfiable

Mac is running OS X 10.10 Yosemite (build14A283o)

I have also reported this in the owncloud/mirall issues page. See #1967 https://github.com/owncloud/mirall/issues/1967#issuecomment-48892042

**Comment by ogoffart** [comment]
I believe this was caused by a bug in old version of the clients,  and it should not happen again with the client 1.7.1
