### ISSUE TITLE
Drop use of OwnCloud's autoloader (in favour of Composer's) for non-OwnCloud classes

### ISSUE THREAD

**Issue by AdamWill** [owncloud/core#9643]
By my reading the OC autoloader is now needed only for OC-specific classes that are not PSR-0 or PSR-4 compatible. The OC autoloader's handling of non-OC classes is very basic:

	    foreach ($this->prefixPaths as $prefix => $dir) {
            if (0 === strpos($class, $prefix)) {
            $path = str_replace('\\', '/', $class) . '.php';
            $path = str_replace('_', '/', $path);
            $paths[] = $dir . '/' . $path;
        }

this is a not-quite-PSR-0 compliant implementation. The Composer autoloader is fully PSR-0 compliant and also PSR-4 compliant, and does a bunch of other tricks too; it's comfortably superior to the code above. I believe the bits of autoloader.php that relate to non-OC classes should be dropped, and the prefixes for any bundled libraries that aren't directly handled by Composer should be registered with Composer's autoloader (instead of the OC autoloader) in base.php .

**Comment by DeepDiver1975** [comment]
Any 3rdparty code is already loaded now using composer's autoloader - more to come with #13241 -> close
