### ISSUE TITLE
make trashbin/versions auto cleanup configurable

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#9651]
By default ownCloud is using all the available space on the disk to store trashed files and versions. There are scenarios where a server actually has a lot of physical storage but ownCloud shouldn´t use it.
So it would be great to have a config variable where an admin can set the percentage of space on the disc that should be used before tash and versions is expired.

**Comment by PVince81** [comment]
Is this covered by the retention changes ?

**Comment by PVince81** [comment]
@VicDeo

**Comment by VicDeo** [comment]
@PVince81 retention is about `time`, not `disk size`
