### ISSUE TITLE
trashbin/version cleanup occ command

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#9652]
There are scenarios where an admin wants to empty all versions or trashbins from all users with the command-line. For example if an admin want´s to migrate an instance to a different server or want´s to do an upgrade.
So it would be great to be able to remove all data that is not absolutely necessary.

**Comment by jab416171** [comment]
Is this still on the roadmap?

**Comment by PVince81** [comment]
@MTRichards @cmonteroluque

**Comment by PVince81** [comment]
Fixed in 8.2 by https://github.com/owncloud/core/issues/16964 and https://github.com/owncloud/core/issues/17140

**Comment by disy-mk** [comment]
I am currently using OC 7.x: looking at the src of merged #16964 I assume simply deleting files_versions folder by hand is exactly what the cli tool does?
I also did not find any entries refferring to file versions in the db.

Thanks
