### ISSUE TITLE
UI improvements for external storage configuration

### ISSUE THREAD

**Issue by Xenopathic** [owncloud/core#9663]
As noted in a few places (#9653, #7736) the UI for configuration of external storages is very limited. Some storages require many parameters, which causes problems with small screens; some parameter names are very long, and get truncated (especially in more 'verbose' languages); and some options can be considered 'advanced' and could be hidden in a submenu (#8167 for example).

One way to improve could be an icon at the far right of every storage, next to the 'delete' button, to allow access to advanced settings. This menu would hide options like "Use ownCloud credentials" (#7875), advanced settings for OpenStack storages (#8410), or SFTP asymmetric key configuration (#9198). These options will usually only be used in advanced cases, where the user is well aware of the settings required. This can help keep the base GUI clean and uncluttered for new users.

Please write any suggestions here (this is a discussion!) and when a consensus has been reached we can start working on the code

**Comment by PVince81** [comment]
Mount options dropdown was added through https://github.com/owncloud/core/pull/14925

**Comment by PVince81** [comment]
The dropdown currently contains hard-coded options, so it's not possible yet to have backends add their own stuff there.

**Comment by Xenopathic** [comment]
I think this is mostly solved now. The configuration fields still make the page quite wide, but they are unavoidable.
