### ISSUE TITLE
Do not ignore exceptions in hooks

### ISSUE THREAD

**Issue by PVince81** [owncloud/core#9667]
Currently if a hook throws an exception, it is logged then ignored.
Since an exception occurred, we cannot guarantee that the state of the system is adequate for the next hooks and operations to run.

Exceptions should be rethrown further after logging here:
https://github.com/owncloud/core/blob/master/lib/private/hook.php#L80

Let's discuss
@brantje @speijnik @icewind1991 @schiesbn

**Comment by GitHubUser4234** [comment]
@PVince81 : Is there any roadmap for this ? :relaxed:  I'm implementing some hooks also right now, and have gotta use `die()` as workaround, too

**Comment by PVince81** [comment]
Not sure, changing hook behavior has a risk of causing other regressions.

**Comment by GitHubUser4234** [comment]
Yeah, I think it would be a one-off pain, but after that it would be clear skies, wouldn't it? :sunrise:  
Would really be a useful, I mean on the one hand something very nice like hooks are offered, but on the other hand developers are forced to use a dirty approach to stop things from continuing when there was an error :relieved:

**Comment by DeepDiver1975** [comment]
> Yeah, I think it would be an one-off pain, but after that it would be clear skies, wouldn't it? :sunrise:

Things never are that easy as they seem .... :sunglasses:

**Comment by DeepDiver1975** [comment]
In addition hooks shall be replace by using Symfony event dispatcher - the behavior is quite clear there ...

**Comment by PVince81** [comment]
I suppose it should be possible to additionally add a dispatch call in the proper locations, and add the logic there to check whether it needs to continue or not.

**Comment by GitHubUser4234** [comment]
Meaning the usage of `stopPropagation()` and even letting developers manipulate the event's response? If yes, it sounds promising :+1:

**Comment by PVince81** [comment]
Closing this. Let's not touch the hook system any more.

We need to move to the Symfony dispatcher way anyway, which supports throwing exceptions from inside a hook handler.
