### ISSUE TITLE
Get rid of the extra »svg« class for the image fallback

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/core#9679]
Currently every img tag or element which has a class inserting an icon needs to add the class »svg« in addition. This class is only so that browsers which don’t support SVG (most notably IE8) will be served with PNG instead.

Can we get rid of the SVG class and have the JS/PHP just detect if it’s either an img or if the class starts with »icon-«? Basically now the svg class is just stupid duplication and people forget it – because it does not make a whole lot of sense to need to add an additional indicator.

cc @icewind1991 @PVince81 @owncloud/designers

**Comment by PVince81** [comment]
Are there other cases where "svg" might be used which isn't an icon ?

From what I understand you are suggesting to use the "icon-*" selector instead of "svg" when applying the workaround, is that correct ?

**Comment by jancborchardt** [comment]
@PVince81 right, it’s also used for the logo and in other places where it’s not prefixed with "icon-". And for the logo we don’t have another way of figuring out it needs SVG replacement except checking what CSS is applied to it – and I assume that is very costly, right?

I guess what I wanted is that "icon-" already suffices for SVG replacement in the case of icons. For others we have to add the svg class still.

**Comment by PVince81** [comment]
I suggest we keep the "svg" class as is then, for consistency and to avoid confusion.
Also it is likely that the "svg" class selector is faster than the partial "icon-*" class selector.

**Comment by jancborchardt** [comment]
Ok, agreed. Closing this then.
