### ISSUE TITLE
don´t break with broken config.php

### ISSUE THREAD

**Issue by karlitschek** [owncloud/core#9713]
config.php is a php file. This means that a syntax error in there can break ownCloud.
It is not a huge problem but still would be nice to detect a potential parse error in config.php somehow so show a proper error. This needs some investigation if this is possible at all with PHP.
Low priority.

**Comment by cdamken** [comment]
I found the server still works with wrong configurations, e.g.:
```
        "redis": {
            "host": "10.100.2.38",
            "port": "6379",
            "timeout": 0,
            "password": "CarlosDamken"
        },
```
The users sometimes doen't know that [] is different as {} and 

> Alternative config file formats would be yaml - mostly used these days from my understanding

yaml files will be a god way to avoid this problems.

**Comment by DeepDiver1975** [comment]
> a god way

:godmode:

**Comment by cdamken** [comment]
:smile:

**Comment by PVince81** [comment]
Closing in favor of https://github.com/owncloud/core/issues/11843

**Comment by PVince81** [comment]
btw when an admin edits the config they should anyway be in maintenance mode to be able to catch the error
