### ISSUE TITLE
Sailfish OS: sidebar reappers when hamburger button is touched to hide it

### ISSUE THREAD

**Issue by blizzz** [owncloud/core#9729]
### Steps to reproduce
1. Have ownCloud from git master
2. Go to Files app from your mobile phone
3. Click the hamburger button – the sidebar appears
4. Click the hamburg button again to make sidebar disappear

### Expected behaviour
The sidebar disappears

### Actual behaviour
It disappears – and comes back immediately 

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache 2

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:** (see ownCloud admin page)
git master

### Client configuration
**Browser:**
SailfishOS Browser (Gecko based)

**Operating system:**
SailfishOS

**Comment by LukasReschke** [comment]
Still waiting?

**Comment by blizzz** [comment]
No, works meanwhile :)

**Comment by LukasReschke** [comment]
:tada:

**Comment by jancborchardt** [comment]
Great stuff, other people fixing their issues as well :rocket:
