### ISSUE TITLE
Browsing files by keyboard arrows in web browser does not scroll the screen down

### ISSUE THREAD

**Issue by brozkeff** [owncloud/core#9740]
### Steps to reproduce

As a user open the web interface with files and folders on Firefox, and use keyboard arrows to navigate in the folder structure by keyboard by pressing up and down, try to go below what is displayed on the bottom of the screen to scroll to nextr folders and files.
### Expected behaviour

By having a file or folder selected in the web interface, and using a keyboard "down" key to scroll down, the list of files and folders should scroll and I should be able to select files or folders that were originally not visible on screen and not visible because of lazy loading "on demand".
Also one should be able to just press up and down which should trigger selecting the first file/folder. Now one needs to click to a particular area of the screen to first "select" the frame with the files and folders and this is complicated and unreliable.
### Actual behaviour

Scrolling by keyboard works only if you first manage to "select" the window/frame of the page with the files and folders, and then it selects only among the the already visible files and folders, it does not trigger the scroll-bar so the files naturally scroll as when using mouse.
### Server configuration

Operating system: Ubuntu 14.04 server in a OpenVZ container

Web server: Apache 2.4.7-1ubuntu4

Database: MySQL 5.5.35+dfsg-1ubuntu1

PHP version: 5.5.9+dfsg-1ubuntu4

ownCloud version: 7.0RC3

Updated from an older ownCloud or fresh install: update via apt-get from 6.0.4, then gradually 7.0RC1, RC2

**List of activated apps:**

Activity
Deleted files
Documents
Owncloud dep.info
Pictures
Share files
Text editor
Versions

**Are you using encryption:** no
### Client configuration

**Browser:**  Firefox 30 for Linux Mint

**Operating system:** Linux Mint 13 MATE 1.8 32bit

**Comment by DeepDiver1975** [comment]
@jancborchardt did your recent work related to accessibility help with this? THX

**Comment by jancborchardt** [comment]
No, this is unrelated. I presume to fix this it takes some advanced JS to check if the currently focused file/folder is below the viewport and if not make sure the view is scrolled to make it visible.

**Comment by PVince81** [comment]
Keyboard navigation was broken for a long time and needs a more extensive fix to work properly with scrolling and the sidebar. Work has started here https://github.com/owncloud/core/pull/19445

**Comment by MorrisJobke** [comment]
> Keyboard navigation was broken for a long time and needs a more extensive fix to work properly with scrolling and the sidebar. Work has started here #19445

So we move this to 9.0?

cc @cmonteroluque @PVince81

**Comment by PVince81** [comment]
Yes, I don't want to risk breaking the web UI that late

**Comment by cmonteroluque** [comment]
ok, thanks

**Comment by PVince81** [comment]
Closing in favor of general files app keyboard issue ticket: https://github.com/owncloud/core/issues/27580
