### ISSUE TITLE
[OC 7.0 RC 3] redirect fail for caldav and webdav

### ISSUE THREAD

**Issue by sedrubal** [owncloud/core#9768]
hi,

I don't know, whether I failed or this is a bug: When I'm not logged in and I go to /remote.php/caldav or /remote.php/carddav I'll be redirected to /index.php. So no [cal/card]dav-app or programm will connect to  my cloud, because they don't find a dav-page.
I checked the /.htacces and the /remote.php (and the /index.php) but they are the same as when I download the owncloud 7.0 RC 3 archieve from the official site.

**Comment by enoch85** [comment]
@sedrubal Is this solved with the new versions?

**Comment by sedrubal** [comment]
Hi, thank you for asking.

Meanwhile I totally reinstalled owncloud and now it is working fine. I think that this was my fail, even if I don't know exactly, how I killed it...

**Comment by enoch85** [comment]
@sedrubal Thanks, don't forget to close no longer existing issues in the future.
