### ISSUE TITLE
[OC7RC3] Sorting in User Management

### ISSUE THREAD

**Issue by hdering** [owncloud/core#9780]
The sorting of user names and groups should be like in Windows/Linux.

![user_management_sorting](https://cloud.githubusercontent.com/assets/3204979/3662397/425bb126-11ca-11e4-8e1f-997a7310baa9.PNG)

Benutzer1
Benutzer2
...
...
Benutzer10
Benutzer11
...
...

**Comment by enoch85** [comment]
Any news here?

**Comment by PVince81** [comment]
Slightly related: #7244

**Comment by PVince81** [comment]
Natural sort has been added to the user list a while ago.
Please try again with 8.1.3
