### ISSUE TITLE
Naming folder 'Documents' and 'Photos' causes sync issues

### ISSUE THREAD

**Issue by apach3guy** [owncloud/core#9783]
An issue that originally began for me on 6.0.4 led me to completely reinstall my ownCloud installation including all database entries and data folders.  The issue persisted even when I upgraded to 7.0 RC 3, again with a completely fresh installation.  I have documented it extensively here:

http://forum.owncloud.org/viewtopic.php?f=26&t=22165

Steps to replicate the issue:

1. Install a new ownCloud server.
2. Delete all default folders and files.
3. Configure the client to sync a local folder to a remote folder named 'Documents' or 'Photos'

While sync may appear to proceed initially, no files are actually being synced.  ownCloud server and client logs display many errors.  Issue appears to arise because the folders contained the same name as the default cloud folders created by ownCloud upon new user configuration.

**Comment by Xenopathic** [comment]
From the forum thread linked in the OP, it looks like the original issue was solved with 7.0. If this isn't the case, feel free to re-open this.
