### ISSUE TITLE
Add layout.public page

### ISSUE THREAD

**Issue by requist** [owncloud/core#9793]
For #9760 I implemented the sticky footer the same way it was implemented in layout.user.php For this I moved the footer to layout.base.php because it needed to be in the wrapper.
Later I realized the name layout.BASE.php probably had a purpose :-)

While thinking about a solution for this, I thought it might be nice to have a template with header and footer for public access anyway, this reduces the code in the public.php from the apps and certifies a common look.
I mentioned this to @jancborchardt and he asked to open an issue on this matter so here it is :)

@Pvince81 @deepdiver1975 @karlitschek

**Comment by alekiy** [comment]
We are looking forward to have a possibility to use our own header and footer of the corporate design, so :+1: 
As @jancborchardt said a pull request would be nice. Currently the documents app is causing some problems using custom header and footer defined in *layout.guest.php*.

**Comment by jancborchardt** [comment]
@oparoz @VicDeo @schiesbn @requist maybe you want to get together on this as the relevant people? (of Gallery, Documents, Sharing, and this request)

**Comment by oparoz** [comment]
Gallery uses the public template (like sharing) and has a sticky footer, which is themed via the main themeing mechanism. I need to test further, but I think the header also comes from the theme. I need to check the standard template, but we wouldn't want a footer there.

**Comment by jancborchardt** [comment]
So it’s only Documents which uses a custom mechanism here?

**Comment by VicDeo** [comment]
@jancborchardt Documents needs footer only for password-protected links (to enter a password) and 404 (if the link to document is incorrect)
There is a little sense to have a footer inside the editor

**Comment by jancborchardt** [comment]
Well, the template could account for that and make footer optional. Shared calendars for example also don’t need a footer.

**Comment by PVince81** [comment]
The PR was merged, what's the next step ?

We're past feature freeze, moving to 9.1

**Comment by PVince81** [comment]
Anyone interested in continuing this ?

Moving to backlog for now.
