### ISSUE TITLE
[7.0] Link not found after failed login

### ISSUE THREAD

**Issue by ramschmaerchen** [owncloud/core#9804]
### Steps to reproduce
1. Copy https://mysub.myurl.tld/index.php/settings/personal
2. Paste in Browser (tested Firefox, Safari and Chromium)
3. Type wrong password
4. Type correct password
5. Browser Error: 

> 404 Not Found
> The requested URL //index.php/settings/personal was not found on this server.

### Expected behaviour
The browser should direct to right URL after successful login

### Actual behaviour
Browser gives wrong url, resulting in following error message:
> 404 Not Found
> The requested URL //index.php/settings/personal was not found on this server.

### Server configuration
**Updated from an older ownCloud or fresh install:**
Updated from 6.0.4 to 7.0

**Activated Apps**
* Notes

### Client configuration
**Browser:**
* Safari
* Firefox

**Operating system:**
* OSX
* Windows

#### Web server error log

```

File does not exist: /owncloud/%2Findex.php%2Fsettings%2Fpersonal, referer: https://sub.example.com/index.php?redirect_url=%2Findex.php%2Fsettings%2Fpersonal
File does not exist: /owncloud/%2Findex.php%2Fsettings%2Fpersonal, referer: https://sub.example.com/index.php?redirect_url=%2Findex.php%2Fsettings%2Fpersonal
File does not exist: /owncloud/favicon.ico, referer: https://sub.example.com/%2Findex.php%2Fsettings%2Fpersonal
```

#### ownCloud log (data/owncloud.log)
```
No error/warning/notice
```

#### Browser log
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL //index.php/settings/personal was not found on this server.</p>
<hr>
<address>Apache/2.2.22 (Ubuntu) Server at cloud.gerade.org Port 443</address>
</body></html>
```

**Comment by LukasReschke** [comment]
Sorry for the delay. Patch is at https://github.com/owncloud/core/pull/13830 – testing would be welcome. Thanks!
