### ISSUE TITLE
7.0 CE - subadmin search returning no results

### ISSUE THREAD

**Issue by sqlgeek** [owncloud/core#9808]
1. Create a group
2. Assign group admin
3. Log in as subadmin
4. Choose Users in dropdown
5. Begin typing in Search Users and Groups textbox
6. Nothing displayed - remove search text and all users in group appear once again

**Comment by Xenopathic** [comment]
I've just tried this, and cannot reproduce on master. Given the age of this issue, I can only assume it's been fixed at some point. Feel free to re-open if you encounter this issue again, but include your oC version.
