### ISSUE TITLE
Upgrade 6.0.4 to 7.0 MySQL Failure

### ISSUE THREAD

**Issue by twistedgrim** [owncloud/core#9828]
An exception occurred while executing 'SELECT `oc_permissions`.`fileid`, `permissions` FROM `oc_permissions` INNER JOIN `oc_filecache` ON `oc_permissions`.`fileid` = `oc_filecache`.`fileid` WHERE `oc_filecache`.`parent` = ? AND `oc_permissions`.`user` = ?': SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'permissions' in field list is ambiguous

Had a failure after copying the directory over via the update documentation, changing the config file and starting the webserver/upgrade. Showed the upgrade page then threw the SQL error above.

**Comment by karlitschek** [comment]
closing because I assume it is fixed in 8
