### ISSUE TITLE
owncloud deb packages at suse factory incompatible with owncloud packages from debian and ubuntu

### ISSUE THREAD

**Issue by callegar** [owncloud/core#9840]
This bug report is about a huge risk of data loss.

The owncloud packages for debian and ubuntu that are found at 
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client
are completely incompatible with the owncloud packages that are distributed by debian and ubuntu.

Basically, they place almost everything in different locations from the packages shipped by debian and ubuntu.

As a result, *when you switch between the debian or ubuntu packages and the packages on the opensuse factory or viceversa, you destroy your owncloud installation and you may well loose the data you have in your owncloud.

The issue is that when you install the opensuse built package, you cannot know what people at debian do. So, once you have installed the opensuse-built owncloud,  your system may happily decide upgrade to a debian/ubuntu-shipped version.  And all your files are gone. The other way round, if you have the debian shipped packages installed, but you have the suse deb repo listed in your apt lists, when a new owncloud release comes out, your system upgrades and your data is gone.

Just experienced it, not happy.

So, please consider either:

1) stop providing the opensuse built packages, unless you can make them really compatible with the debian/ubuntu ones.  As is, they are just dangerous.

2) assure that the opensuse built packages have a different name from the debian/ubuntu shipped ones (e.g. owncloud-upstream or owncloud-suse) so that on debian machines the system does not auto-upgrade back and forth from debian-shipped and suse-shipped owncloud deb packages

Also, please provide some big warning about the fact that installing the deb packages shipped by suse may well break your system, since they are in fact not debian compatible.

**Comment by erwdavid** [comment]
Another problem is that debian packages are limited ones with some features of owncloud removed (eg. apps installation), which can lead to problems.

**Comment by etiess** [comment]
@PVince81 I know this is an old issue, and that it is more a Ubuntu problem than a OC problem.

But I'm not sure to have understood you. I'm under Ubuntu 14.10. I installed OC7 with the opensuse repo. How can I be sure, in the future, that my system will update the owncloud package using ONLY the opensuse repo? For example, How can I be sure that the command "apt-get upgrade" will use the opensuse repo to install OC8?

Thank you very much!

**Comment by callegar** [comment]
To be sure you need to use a function of apt that is known as pinning. Pinning involves manually editing the /etc/apt/preferences file. Here, if I am not mistaken (sorry, I am not on the right machine, so I cannot experiment and I need to work by memory) you will need to have something like

Package: owncloud-*
Pin: release o=obs://build.opensuse.org/isv:ownCloud:community/Debian_7.0
Pin-Priority: 900

**Comment by callegar** [comment]
To erwdawid:
The problem is not that the debian packages are limited ones: I think that we are all more than happy that the owncloud deb packages provided by the developers can do more. The problem is that the deb packages provided by the owncloud developers, as they are currently shipped, do not play well with the debian environment because they does not respect the assumptions that other packages and the package installer have wrt how a debian package should be packaged.  This can cause big issues and even data loss if the users who install the owncloud provided debs are not aware of the need to set up pinning because the package is not compatible with the debian supplied package with the same name.

This is why I advocate either (in priority order):
1) Providing a deb package that agrees with the debian guidelines (that IMHO should be interpreted at the same level as an API, wrt developing for debian derivatives).
2) Renaming the owncloud server package provided by the owncloud developers differently from the debian provided package (e.g. owncloud_upstream)
3) Convincing debian developers to rename their owncloud package differently from the package provided by the owncloud developers (e.g. owncloud_debian)
4) Putting in the download page a big sign about the need to set up pinning to safely use the owncloud provided package.

**Comment by callegar** [comment]
As a side issue, the deb package provided by opensuse is problematic whenever "data" is a symbolic link to another partition and happily removes the link, sets up a new empty data storage, updates the database to reflect the fact that the owncloud storage is empty.

**Comment by jnweiger** [comment]
@callegar that is an issue. Let me look into that!

**Comment by jnweiger** [comment]
@callegar I just started reading about pinning, we definitly should discourage users to switch between packages provided by debian and packages provided by owncloud. Pinning looks like a good thing while the situation is as it is. Can you suggest a working /etc/apt/preferences entry?

Best solution is to make our packages comply with the packaging guidelines. I had most location changes drafted but then reverted to the classic all-under-webroot-layout, as we had not enough resources to implement and test the changes.

**Comment by etiess** [comment]
Thank you very much @callegar 

I knew the ability to hold an upgrade (<code>sudo apt-mark hold owncloud</code>), to unhold it (<code>sudo apt-mark unhold owncloud</code>) and to have information on it (<code>sudo apt-cache policy owncloud</code>). But I didn't know the ability to manage repositories too. Great!

Just to be sure, in https://software.opensuse.org/download/package?project=isv:ownCloud:community&package=owncloud I find this repo for Ubuntu 14.10: http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.10/

So in /etc/apt/preferences I wrote: 
<code>Package: owncloud-*</code>
<code>Pin: release o=obs://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.10/</code>
<code>Pin-Priority: 900</code>

Is it correct?

The command <code>sudo apt-cache policy owncloud</code> gives:
owncloud:
  Installed: 7.0.4-3
  Candidate: 8.0.0-5
 Version table:
     8.0.0-5 0
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_14.10/  Packages
 *** 7.0.4-3 0
        100 /var/lib/dpkg/status

**Comment by etiess** [comment]
@jnweiger I did not see your message before, sorry. 

I understand your concern about pinning. What would be the right answer to this issue: 

How can I be sure that the command <code>apt-get upgrade</code> will use the opensuse repo provided by ownCloud for the owncloud package, and not a Ubuntu repo, or any other repo in my sources.list ?

**Comment by jnweiger** [comment]
Testing ...

    cat /etc/apt/sources.list.d/owncloud.list 
    deb http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0//xUbuntu_14.04/ /
    deb http://download.opensuse.org/repositories/isv:/ownCloud:/community:/7.0//xUbuntu_14.04/ /

    cat /etc/apt/preferences.d/owncloud-7 
    Package: ownclou*
    Pin: release o=http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0//xUbuntu_14.04/
    Pin-Priority: 900

With this I get 

    apt-cache policy owncloud
    owncloud:
      Installed: 7.0.4-3
      Candidate: 7.0.4-3
      Package pin: (not found)
      Version table:
         8.0.0-5 900
            500 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/8.0//xUbuntu_14.04/  Packages
     *** 7.0.4-3 900
            500 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/7.0//xUbuntu_14.04/  Packages
            100 /var/lib/dpkg/status
         6.0.1+dfsg-1ubuntu1.2 900
            500 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe amd64 Packages
         6.0.1+dfsg-1ubuntu1 900
            500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages

@etiess Slightly different syntax than yours. http:// instead of obs:// makes a difference, apt-cache policy reports that there is a package pin, but '(not found)' indicates something is still wrong.

**Comment by jnweiger** [comment]
Started an experimental owncloud-fhs package that would have config, data, and code in more correct places, from a distributors point of view. @karlitschek will now hate me for tearing his tar ball into pieces.

https://build.opensuse.org/package/show/isv:ownCloud:community:testing/owncloud-fhs

CAUTION: Experimental unsupported package. Do not use, except for testing!

**Comment by PVince81** [comment]
From what I heard now the number of packages was reduced. Would this help with preventing the data loss situation described here ? @jnweiger

**Comment by jospoortvliet** [comment]
I think the solution is for Debian to stop shipping ownCloud... It's a bad idea anyhow.

**Comment by Xenopathic** [comment]
And now they have :cry:
