### ISSUE TITLE
[OC7.0 stable] opendir(/var/www/owncloud/data/XXX/files_trashbin/files/): failed to open dir: No such file or directory at /var/www/owncloud/lib/private/files/storage/local.php#75

### ISSUE THREAD

**Issue by enoch85** [owncloud/core#9855]
### Steps to reproduce
Don´t know, but maybe because I deleted some files before?

### Expected behavior
No error

### Actual behavior
opendir(/var/www/owncloud/data/XXX/files_trashbin/files/): failed to open dir: No such file or directory at /var/www/owncloud/lib/private/files/storage/local.php#75

### Server configuration
Ubuntu Server 12.04

**Database:**
Server version: 5.5.38-0ubuntu0.12.04.1 (Ubuntu)
**PHP version:**
PHP 5.5.9-1ubuntu4.3 (cli) (built: Jul  7 2014 16:36:58)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
**ownCloud version:** (see ownCloud admin page)
7.0 stable
**Updated from an older ownCloud or fresh install:**
Update from 6.0.4

**Are you using external storage, if yes which one:** local/smb/sftp/...
Dropbox
**Are you using encryption:** yes/no
No
### Client configuration
**Browser:**
Chrome Version 34.0.1847.131 m
**Operating system:**
Windows 8.1
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Error PHP	 opendir(/var/www/owncloud/data/XXX/files_trashbin/files/): failed to open dir: No such file or directory at /var/www/owncloud/lib/private/files/storage/local.php#75
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by PVince81** [comment]
Ha, I got this today while working on the trashbin, I believe the steps are as follows:
1. Delete several files
2. Select ALL files in trashbin and delete, this will internally trigger the deletion of the "files_trashbin" folder, but that folder isn't created any more
3. Somehow trigger the expiration logic (I had it through the new background job)

The message should disappear if we make sure to recreate those folders, like done in this unrelated PR: https://github.com/owncloud/core/pull/14676/files#diff-a73f4a8f22c2260365def923d5a51904R511

**Comment by PVince81** [comment]
Possible fix here: https://github.com/owncloud/core/pull/15179

**Comment by DeepDiver1975** [comment]
close?
