### ISSUE TITLE
OC7.0.0 Cannot upload 2 directories through Drag and Drop

### ISSUE THREAD

**Issue by PhilJung** [owncloud/core#9857]
Create 2 folders Folder1 & Folder 2. Put one text file in each folder.
Select the 2 folders in explorer (Linux Mint 17 file explorer)
Drag and drop into OC Documents folder (displayed in Firefox 31)
File transfert starts and fails immediately. A small orange notification zone is displayed. It is empty
POST requests receive no answer.
owncloud.log contains:
{"reqId":"53d10a32b13d4","app":"files","message":"Upload error: 3 - Le fichier n'a \u00e9t\u00e9 que partiellement envoy\u00e9.","level":3,"time":"2014\/07\/24 15:29:22","method":"POST","url":"\/index.php\/apps\/files\/ajax\/upload.php"}
{"reqId":"53d10a32f157c","app":"files","message":"Upload error: 3 - Le fichier n'a \u00e9t\u00e9 que partiellement envoy\u00e9.","level":3,"time":"2014\/07\/24 15:29:22","method":"POST","url":"\/index.php\/apps\/files\/ajax\/upload.php"}
=> The file has been only partially sent.
No other message in the web server (Apache 2.2 under Centos 6.5 with PHP 5.3) log

Made another test: the feature works with Chrome 36.

So two solutions:
- there is a problem inside Firefox browser
- there is a problem with browser side OC code that occurs only in Firefox

Can somebody help me locate the javascript (jQuery?) code that calls apps/files/ajax/upload.php ?

**Comment by nickvergessen** [comment]
Work is done in #13940 (PR: #13941)
