### ISSUE TITLE
OC7 Stable - App option to "Enable only for specific groups" breaks CalDav

### ISSUE THREAD

**Issue by Enzo-Matrix** [owncloud/core#9865]
See https://github.com/owncloud/calendar/issues/481 for my configuration details. The only change is I am now on OC7 Stable.

NOTE: This only impacts external access over caldav. The web GUI functions as expected with the correct application filter.

### Steps to reproduce
1. Go to App
2. Select Calendar App
3. Check the "Enable only for specific groups" option
4. Select other Apps
4. Check "Enable only for specific groups" option if applicable

### Expected behaviour
CalDav access should be enabled for users in the specified group.

### Actual behaviour
CalDav access seize to function for all users. With "Enable only for specific groups"  enabled for the Calendar App, caldav fails immediately when a sync occurs. With "Enable only for specific groups" disabled for Calendar App but enabled on another app (it was also enabled for Contacts App), caldav syncs initiates, however a 500 error is returned by the web server, along with a "Sharing backend for addressbook not found" in the OC logs (detailed errors below). With  "Enable only for specific groups" disabled on all apps (confirmed with Contacts and Updater), CalDav functions normally and sync completes successfully with no errors.

#### Web server error log
```
 "PROPFIND /remote.php/caldav/calendars/user/defaultcalendar HTTP/1.1" 500 -
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"53d11c24e8563","app":"remote","message":"Sharing backend for addressbook not found","level":4,"time":"2014-07-24T10:45:56-04:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user\/defaultcalendar"}
{"reqId":"53d11c24e8563","app":"PHP","message":"Session has been closed - no further changes to the session as allowed at \/srv\/www\/htdocs\/owncloud-7.0.0\/lib\/private\/session\/memory.php#80","level":3,"time":"2014-07-24T10:45:56-04:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user\/defaultcalendar"}
```

#### Thunderbird Lightning log (TO BE ADDED)
```
```

**Comment by PVince81** [comment]
@icewind1991 didn't you fix this recently ? Or was it something else ?

**Comment by georgehrke** [comment]
https://github.com/owncloud/calendar/pull/502

**Comment by georgehrke** [comment]
wrong repo
