### ISSUE TITLE
[Clarification request, or suggestion] "Bulk changes" of e-mail notification settings for file events

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/core#9875]
As an admin, I want to set the e-mail notification for all users to certain values, e.g. to enable notifications for all file events.

How can this be achieved?

**Comment by PVince81** [comment]
closing as duplicate of https://github.com/owncloud/activity/issues/429

**Comment by Wikinaut** [comment]
Still interested in such a feature.

**Comment by micbar** [comment]
1) There is a system default
2) The user overrides it
3) Why should the admin change it and annoy the user with that action?

I don't get the use case.
