### ISSUE TITLE
Double-slash at URL root breaks browsing into subdirectories

### ISSUE THREAD

**Issue by CyberShadow** [owncloud/core#9881]
When I log in to my ownCloud instance or visit the site root (`https://owncloud.example.com/`), I am redirected to `https://owncloud.example.com//index.php/apps/files/`. Note the double-slash before `index.php`.

From there, I cannot browse into subdirectories. Attempting to browse into a subdirectory results in the following JS error:

```
Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'https://index.php/apps/files/?dir=%2Fdefault' cannot be created in a document with origin 'https://owncloud.example.com'. js.js?v=decc2e06a44e61f12a030bc4951563eb:1386
OC.Util.History.pushState js.js?v=decc2e06a44e61f12a030bc4951563eb:1386
App._changeUrl app.js?v=decc2e06a44e61f12a030bc4951563eb:189
App._onDirectoryChanged app.js?v=decc2e06a44e61f12a030bc4951563eb:148
x.event.dispatch jquery-1.10.0.min.js?v=decc2e06a44e61f12a030bc4951563eb:5
v.handle jquery-1.10.0.min.js?v=decc2e06a44e61f12a030bc4951563eb:5
x.event.trigger jquery-1.10.0.min.js?v=decc2e06a44e61f12a030bc4951563eb:5
e.event.trigger jquery-migrate-1.2.1.min.js?v=decc2e06a44e61f12a030bc4951563eb:2
(anonymous function) jquery-1.10.0.min.js?v=decc2e06a44e61f12a030bc4951563eb:5
x.extend.each jquery-1.10.0.min.js?v=decc2e06a44e61f12a030bc4951563eb:4
x.fn.x.each jquery-1.10.0.min.js?v=decc2e06a44e61f12a030bc4951563eb:4
x.fn.extend.trigger jquery-1.10.0.min.js?v=decc2e06a44e61f12a030bc4951563eb:5
FileList._setCurrentDir filelist.js?v=decc2e06a44e61f12a030bc4951563eb:899
FileList.changeDirectory filelist.js?v=decc2e06a44e61f12a030bc4951563eb:866
(anonymous function) fileactions.js?v=decc2e06a44e61f12a030bc4951563eb:354
FileList._onClickFile filelist.js?v=decc2e06a44e61f12a030bc4951563eb:288
x.event.dispatch jquery-1.10.0.min.js?v=decc2e06a44e61f12a030bc4951563eb:5
v.handle jquery-1.10.0.min.js?v=decc2e06a44e61f12a030bc4951563eb:5
```

### Server configuration
This is a Linux machine with an Apache SSL reverse proxy in front of an unprivileged Apache instance running as the owncloud user. MySQL 5.5.38-0ubuntu0.14.04.1-log, PHP 5.5.9-1ubuntu4.3, ownCloud 7.0.0 (stable), fresh install.

Activated apps:

* Activity
* Deleted files
* First Run Wizard
* Full Text Search
* PDF Viewer
* Pictures
* Text Editor
* Updater
* Versions
* Video Viewer

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'trusted_domains' =>
  array (
    0 => 'owncloud.example.com',
  ),
  'datadirectory' => '/home/owncloud/www/data',
  'dbtype' => 'mysql',
  'version' => '7.0.0.8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'installed' => true,
  'mail_from_address' => 'owncloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'owncloud.example.com',
  'mail_smtpname' => 'cybershadow',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
No (only HTTPS).

### Client configuration
**Browser:**
Happens in Opera 12 and Chrome.

**Operating system:**
Windows

#### Web server error log
Nothing relevant.

#### ownCloud log (data/owncloud.log)
Nothing relevant.

#### Browser log
See above.

**Comment by DeepDiver1975** [comment]
From my understanding this has been fixed with https://github.com/owncloud/core/pull/13552

Will be shipped with 8.0.0 and 7.0.5 - THX
