### ISSUE TITLE
Setup for Postgres

### ISSUE THREAD

**Issue by mrflow** [owncloud/core#9889]
The setup with PostgreSQL is "kind of" broken.
owncloud does not allow an empty database host, if the field is left empty, the value will be replaced by "localhost". This is not a good thing, because empty host means "use unix socket" to Postgres.

I could fix the setup by editing the line 41 in private/setup/abstractdatabase.php

Indeed it is a big Problem if one does not want to setup postgres to listen on tcp connections.

**Comment by strk** [comment]
I suggest renaming the issue title to be more specific about the unix socket support.

**Comment by Xenopathic** [comment]
As per the [documentation](https://doc.owncloud.org/server/9.0/admin_manual/configuration_database/linux_database_configuration.html#postgresql-database) this is supported by passing the path to the Postgres socket directory

**Comment by strk** [comment]
Specifying "/var/run/postgresql" triggers an Internal Server Error here.
Note that the filename is stiill dependent on port, `.s.PGSQL.5433` in my case.
Can it be the code hard-codes the socket name to the default port ?

**Comment by strk** [comment]
Ok, `/var/run/postgresql:5433` works
