### ISSUE TITLE
Nginx ModAuthLdap and OpenLdap Users

### ISSUE THREAD

**Issue by eskimos78** [owncloud/core#9908]
Hi,
I have a problem automatically authenticating users against ldap with nginx module.
I have compiled nginx with LDAP authentication module 
 https://github.com/kvspb/nginx-auth-ldap , webserver LDAP authentications works fine but the problem is that ldap users cannot automatically login to OC. 
If I create a local user with same LDAP username and password the auto login process to OC works well.

### Steps to reproduce
1. login to nginx authentication as user stored in ldap

### Expected behaviour
Ldap users should be able to log in without problems

### Actual behaviour
User login with Nginx authentication but not in OC

### Server configuration
**Operating system**:
Centos 6.5

**Web server:**
Nginx 1.6 + php5-fpm + nginx-auth-ldap 

**Database:**
SqLite
slapd 2.4.23 

**PHP version:**
5.4.30

**ownCloud version:** (see ownCloud admin page)
7.0.0

**Updated from an older ownCloud or fresh install:**
fresh

**List of activated apps:**
standard apps after fresh install + ldap user backend activated

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'removed',
  'passwordsalt' => 'removed',
  'trusted_domains' => 
  array (
    0 => 'owncloud.removed.com',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'sqlite3',
  'version' => '7.8.0.0',
  'installed' => true,
  'loglevel' => '0',
  'ldapIgnoreNamingRules' => false,
'check_for_working_webdav' => false,
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
makes no difference

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Firefox, Chrome

**Operating system:**
Linux, Mac

#### Web server error log
nothing of special

#### ownCloud log (data/owncloud.log)
Please note ”No DN found for **uid**  on ldap.server.com”, the problem probably is that: **uid** value is empty

```
{"reqId":"53d283c389478","app":"user_ldap","message":"No DN found for  on ldap.server.com","level":0,"time":"2014-07-25T16:20:19+00:00","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=decc2e06a44e61f12a030bc4951563eb"
```

#### Browser log
I don't see anything related. Please ask if you think there could be something useful somewhere.

Something else I can provide?

**Comment by DeepDiver1975** [comment]
This is a currently not supported configuration. For LDAP authentication you need to configure ownCloud itself to connect to the ldap server within the admin page.

ldap auth on web server level is not supported - THX
