### ISSUE TITLE
update to version 7 fails

### ISSUE THREAD

**Issue by jonnius** [owncloud/core#9927]
I tried to update my owncloud to version 7, but it fails with the following error:

An exception occurred while executing 'INSERT INTO oc_filecache (fileid, storage, "path", path_hash, parent, name, mimetype, mimepart, "size", mtime, storage_mtime, encrypted, "unencrypted_size", etag) SELECT fileid, storage, path, path_hash, parent, name, mimetype, mimepart, size, mtime, storage_mtime, encrypted, unencrypted_size, etag FROM __temp__oc_filecache': SQLSTATE[23000]: Integrity constraint violation: 19 PRIMARY KEY must be unique

Can anyone tell me what is the problem and how to fix it?

**Comment by karlitschek** [comment]
@icewind1991 @PVince81 any idea?

**Comment by jonnius** [comment]
I already reinstalled owncloud. Now i am using version 7, hoping not to face same problem when updating to owncloud 8...

**Comment by PVince81** [comment]
If you do face the same problem with 8.0 and/or 8.1, please reopen.

**Comment by ruccc** [comment]
Hello,
This is happening with me trying to update to 8.1.4.2 from 8.1.3.0.
