### ISSUE TITLE
[7.0.0] Encryption not working. 

### ISSUE THREAD

**Issue by Happyfeet01** [owncloud/core#9936]
Hello,

I have installed Owncloud 7 and the encryption App. 
These App don't work. You can enable it but, after that no Login possible. 

Steps to reproduce:

1. Enable the encryption App
2. Switch to the User Account and you will see only "Verschlüsselung" look at this picture https://plus.google.com/109997039457522607355/posts/HGYnws1WDMv

3.no login possible. 

My Owncloudsetup:

Owncloud 7.0.0.6
PHP 5.6
CentOS

**Comment by enoch85** [comment]
Is this fixed?

**Comment by PVince81** [comment]
@Happyfeet01 did you have any more luck with 7.0.7 or 8.0.5 ?

**Comment by PVince81** [comment]
Please try again with 8.1.3
