### ISSUE TITLE
Files and folders renamed after 6 -> 7 migration

### ISSUE THREAD

**Issue by sirFlomo** [owncloud/core#9941]
### Steps to reproduce
1. Have owncloud 6 up and running containing files and folders containing upper case letters
2. Migrate to owncloud 7 following the migration guide
3. Find the folders renamed containing only lower case letters causing shares and sync to fail

### Expected behavior
Migration should not touch any file/folder names

### Actual behavior
After migration files/folders have different names

### Server configuration
**Operating system**: Windows 7

**Web server:** Apache 2.2

**Database:** MySQL

**ownCloud version:** 7.0.0

**Updated from an older ownCloud or fresh install:** Updated from OC 6.0.4

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Comment by enoch85** [comment]
Any update here?

**Comment by DeepDiver1975** [comment]
Solution: move away from windows. Seriously we need to drop that windows mess. We never should have walked this path.

**Comment by enoch85** [comment]
Won't fix?
