### ISSUE TITLE
Shared video freezes web browser (FireFox, Chrome, etc)

### ISSUE THREAD

**Issue by Crasha** [owncloud/core#9952]
When I share a video and test the link on any machine, the web browser locks up with the owncloud page with the video in the middle; with the page continuously loading. you cannot interact with anything on the page as it's frozen.

I can also recall the "share" option for the video froze the browser too and made it crash, however worked flawlessly another time.

**Comment by jancborchardt** [comment]
@Crasha @KKyang @gdepratt is this still an issue with ownCloud 8?

cc @schiesbn @icewind1991

**Comment by gdepratt** [comment]
Haven't had a chance to upgrade yet. I will test and get back to you soon.

**Comment by KKyang** [comment]
Nope, the freezing problem is solved. But I cannot choose the time line of the video. Every time I've done this Owncloud will replay my cideo.

**Comment by PVince81** [comment]
@KKyang this is another issue, see https://github.com/owncloud/apps/issues/2064

If anyone is still having freezing video issues with 8.0.6 or 8.1.1, feel free to reopen.
