### ISSUE TITLE
owncloud windows client doesnt syncs

### ISSUE THREAD

**Issue by AlexGerasymenko** [owncloud/core#9954]
Hello,

i updated my 6.0.4 installation to the latest owncloud v.7 and shared about 90 folders with web ui with 6.0.4 for 4 clients, which are using client version 1.6. 4 days have passed - but any of client havent synced anything except OwnCloud "greeting files". I clearly see in web server logs that they are sending access requests to this files, though sync still havent occur.

**Comment by PVince81** [comment]
When you say they aren't syncing, do you mean they still downloaded the files initially, but when someone changes a file, it doesn't redownload them ?
Are the shared folders deep in a subfolder for the sharer/owner of the files ? (for example "a/b/c" where "c" is the shared folder)

**Comment by PVince81** [comment]
Please try again with 8.1.1 and sync client 1.8.4.
In 8.1.1 there have been fixes related to etag propagation which should fix syncing issues with shared files.

If you're still having trouble with these versions, feel free to reopen.
