### ISSUE TITLE
Search results displayed incorrectly

### ISSUE THREAD

**Issue by tribut** [owncloud/core#9955]
I noticed search results displaying weirdly (for example calendar events displaying only as the date, contacts only their email):
![search results](https://cloud.githubusercontent.com/assets/719105/3719068/c0fd111e-163e-11e4-8af3-7c0c2bfb9d19.png)

This appears to be due to the results.js looking for `name` and `text` properties in the json returned by the ajax call. The [`OC_Search_Result`](https://github.com/owncloud/core/blob/master/lib/public/search/result.php#L32) however, only has `id` and `name`. Looking at the search providers, they seem to think they are interacting with an object that provides `name` and `text` and are therefore passing the title as first and some description as second parameter, for example look at this comment [from the calendar app](https://github.com/owncloud/calendar/blob/master/lib/search.php#L43):
~~~ php
$results[]=new OC_Search_Result([...]);//$name,$text,$link,$type
~~~

Replacing `name` by `id` and `text` by `name` in [results.js](https://github.com/owncloud/core/blob/master/search/js/result.js#L61) works, but that is just a quick workaround. What is the correct way to solve this? Is there some sort of API docs that I didn't find?
![workaround](https://cloud.githubusercontent.com/assets/719105/3719071/cdfb44c6-163e-11e4-9b97-48e42cbd3624.png)

Using ownCloud 7.0.0 installed from release tarball.

**Comment by jancborchardt** [comment]
This has been fixed long ago with the new Files search.
