### ISSUE TITLE
GoogleDrive: 'Invalid Content Length' and folder duplicates synchronizing with linux-client

### ISSUE THREAD

**Issue by maste9** [owncloud/core#9958]
After upgrading my owncloud running on a bananapi to **OC7** I tried to connect my **GoogleDrive**-Account following the instructions in the manual.
Generally it works fine so that using the webinterface of OC there was nothing wrong. BUT ... then my **desktop-client** on an *Linux Mint 17 desktop* system (synchronizing via local ip 192.168.1.x) tried to sync which broke with syncing folders in my GDrive. The client reported *'Invalid Content Length'* per each folder and file in it. When examining this defective process I could see that the client tried to sync these files showing **negative filesizes** (-2kB, -32kB) for them and stopping with incomplete sync after a while.
In the WebInterface I find an **incountable multiplication of the certain folders** with size of 0kB and constantly updating the index.
Only removing GDrive from external storage mounts made client sync completely.
While GDrive remains unusable to me **FTP-sync causes no trouble**.

**Comment by bolausson** [comment]
Similar issue here.

It happens for me on **Google files** (Type Googe {Docs,Sheets,Slides,Forms,Drawings}) which have been created and edited in the browser.

All files have a **negative size (-2B)** and as error I get:
**GDrive/test: Invalid Content-Length in response**
(where "test" is a "Google Docs" document containing some random lines of text)

I am not sure how Google drive handles these files in terms of file format - when you want to download them you have to select to which format they should be saved - so I think these files should not be synced as they can only be edited and exported with a browser.

Files (.doc .docx .pdf etc..) which are uploaded to the drive do work fine.

**Steps to reproduce:**
1) Setup Google drive in ownCloud
2) Upload some documents
3) Wait for sync (until here everything should work fine)
4) With a browser go to you drive (https://drive.google.com)
5) Click "New"
6) Select "Google Docs" (Sheets, or Slides will trigger the failure as well)
7) Write something to the document
8) give it a name (Top left, klick on "untitled document")
9) Wait for sync or trigger sync in the ownCloud client (Hit Pause, then Resume)

**Versions used:**
Server: 7.0.4 (stable) (Debian Linux 3.2.57-3)
Client: 1.7.1 (Gentoo Linux 3.17.4)
Client: 1.7.1 (Windows 8.1)

**Suggested solution:**
Exclude Google {Docs,Sheets,Slides,Forms,Drawings} from sync

Kind regards,
Bjoern Olausson

**Comment by bolausson** [comment]
Mhhh, I have to adjust some of my comments:

Interestingly I can sync the documents on another client (my laptop) and the files just seem to be OpenDocument files without file extension.

But the problem remains, they don't sync on my Desktop *wondering*

**Comment by DeepDiver1975** [comment]
@karlitschek @cmonteroluque GDrive is a bigger beast - suggest to move to 9.0 or backlog - depending on the intention to address GDrive external storage implementation - which means:
kill the code in core and implement it as an app on it's own using flysystem.

**Comment by karlitschek** [comment]
No time for 8.2

**Comment by cmonteroluque** [comment]
OK, we have a lot of work for external storage for 9.0. This would seem the right time to look into it

**Comment by morriswinkler** [comment]
any idea on how to use GDrive for the time being, it looks like that syncing is interrupted every 2 minutes, is there a way to exclude google document formats from all clients that sync ?

**Comment by PVince81** [comment]
Unfortunately there is no way to exclude files or folders from an external storage mount.

**Comment by PVince81** [comment]
I found a bug with GDrive special formats while debugging something else.
Turns out that "fileExtension" is null instead of empty string when browsing special Google Drive files.
It seems that changing the code to react on `null` too makes it work.

Will submit a PR for this.

**Comment by PVince81** [comment]
Looks like it's not enough... that fix works for downloading office files but not reuploading. On upload one would have to strip away the extension again, I didn't find such logic.

**Comment by PVince81** [comment]
Okay, there is logic that tries to find the file with extension and if it's not found, then again without.

I fixed the logic to make it do what it was supposed to do in the first place, it should work better with office files and sync client now, please help testing: https://github.com/owncloud/core/pull/22405

**Comment by PVince81** [comment]
Okay, thanks @ferdiga and @bolausson for pointing out that "Invalid Content Length" is actually an related to resuming downloads, so not related to this fix https://github.com/owncloud/core/pull/22405

Maybe the fseek isn't working properly for some reason. Will try and reproduce it.

**Comment by PVince81** [comment]
Did some debugging, this is likely the cause for fseek not working: https://github.com/owncloud/core/issues/22476

**Comment by PVince81** [comment]
Or this http://php.net/manual/de/streamwrapper.stream-metadata.php :smile:

**Comment by PVince81** [comment]
The linked PR doesn't solve this issue.

However I'm leaving this closed in favor of the range request ticket https://github.com/owncloud/core/issues/22476
